### ISSUE TITLE
query: running deconz-rest-plugin on something other than an RPi

### ISSUE THREAD

**Issue by mrose17** [dresden-elektronik/deconz-rest-plugin#1]
hi. let's say i had a computer (Mac, RPi, BBB, etc.) that ran some unix/linux OS and i had a deRFusb23e0x wireless USB dongle.

what would i need to do to get the rest plugin running?

my goal is to write a node-deaconz-rest package for node.js which will talk to the deRFusb23e0x directly. i suspect that would be quite a bit of work, so the interim project is just to get the rest plugin running on a local server and then use node.js to talk to the REST service.

thanks!

**Comment by nikhilupadhyay** [comment]
I would like to ask you guys whether this RaspBee premium can be able to communicate with other series 2 xbee devices. If so waht are the changes required to be made in order to get it working
