### ISSUE TITLE
Can't change color of tradfri bulbs with alexa

### ISSUE THREAD

**Issue by tiwo85** [dresden-elektronik/deconz-rest-plugin#1007]
Hello,
When i say "Alexa change colour of living room to Red" the Alexa say some thing like "the light doesn't work correctly". When i say "Alexa dim light up" then it works. In deconz App it works correctly and i can change the colour perfectly.
My System ist deconz 2.05.48 on debian stretch with conbee Stick.

**Comment by KodeCR** [comment]
Sorry, the native hue support does not do colours. You need the hue skill for that which doesn’t work with deconz because of the propriety cloud login. You would need to create your own Alexa smart home skill or use something like homebridge-Alexa with homebridge-hue.
