### ISSUE TITLE
completely delete (light) 

### ISSUE THREAD

**Issue by Somberland** [dresden-elektronik/deconz-rest-plugin#1012]
hey there, 
is there an easy way to delete a device (light) completely from deconz/phosconapp? 
i already tried it with the phoscon-app (delete light) and deconz (delete node) and via REST. unfortunately settings (name etc) are visible again in phoscon after you add them again. got some sensors I can't reach easily so gateway-reset is not rly possible.

ConBee
Version: 2.05.49 / 29.11.2018
Firmware: 262F0500

thanks :)

**Comment by manup** [comment]
Deleting has improved in recent versions 2.05.54 and upwards, so deleted artifacts shouldn't return.

Closing the issue for now.
