### ISSUE TITLE
lumi.sensor_motion.aq2 comes with ZHAALarm?

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#1017]
I was testing here with a Aqara motion sensor and had to rescan the device to move it between gateways. to my surprise a ZHAAlarm is created in the REST API, next to a ZHAPresence and ZHALightlevel? It seems this is an empty object really as lastupdated stays as "none". what is the purpose of the ZHAAlarm here? I suspect this should not have been created?

>    "57": {
        "config": {
            "battery": null,
            "duration": 60,
            "on": true,
            "reachable": true,
            "temperature": null
        },
        "ep": 1,
        "etag": "373794cef2300d6bad1b25abfe6d9cda",
        "manufacturername": "LUMI",
        "modelid": "lumi.sensor_motion.aq2",
        "name": "Presence 57",
        "state": {
            "lastupdated": "2018-12-09T12:38:19",
            "presence": false
        },
        "type": "ZHAPresence",
        "uniqueid": "00:15:8d:00:01:e5:62:85-01-0406"
    },
    "58": {
        "config": {
            "battery": null,
            "on": true,
            "reachable": true,
            "temperature": null,
            "tholddark": 12000,
            "tholdoffset": 7000
        },
        "ep": 1,
        "etag": "373794cef2300d6bad1b25abfe6d9cda",
        "manufacturername": "LUMI",
        "modelid": "lumi.sensor_motion.aq2",
        "name": "LightLevel 58",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2018-12-09T12:37:18",
            "lightlevel": 13803,
            "lux": 24
        },
        "type": "ZHALightLevel",
        "uniqueid": "00:15:8d:00:01:e5:62:85-01-0400"
    },
    "59": {
        "config": {
            "battery": null,
            "on": true,
            "reachable": true,
            "temperature": null
        },
        "ep": 1,
        "etag": "95e81560c617f39bf45eaa9b6a9f1b28",
        "manufacturername": "LUMI",
        "modelid": "lumi.sensor_motion.aq2",
        "name": "Alarm 59",
        "state": {
            "alarm": false,
            "lastupdated": "none",
            "lowbattery": false,
            "tampered": false
        },
        "type": "ZHAAlarm",
        "uniqueid": "00:15:8d:00:01:e5:62:85-01-0500"
    }

**Comment by ebaauw** [comment]
Looking at the `uniqueid`, the ZHAAlarm is created for the _IAS Zone_ cluster.  In theory, it could raise alarms for low battery, tampering, or general alarm.  I don't know the Aqara motion sensor, so I wouldn't know whether this cluster reports anything useful in practice.  When did you last pair one of these?  The sensor resource is probably created now, because the improved reading of the node descriptors now reveals the _IAS Zone_ cluster.

Did deCONZ enroll the device?  If not, try writing the RaspBee/ConBee mac address to the _IAS_CIE_Address_.  What _Zone Type_ does it report?

**Comment by wvuyk** [comment]
This is an motion sensor that has been working for a year. But with 2.0.5.49 (on an ikea routered network) it reported unreachable over and over. I do not think it was the cause of IKEA, but I limited (switched off) bulbs. This made the Aqara motion sensor become unreachable.
So I did reset the sensor and paired it to my RaspBee. This is where the ZHAAlarm was added. So indeed I guess you might be right, between a year ago and now this ZHAAlarm was added. Guess I will have to wait to see its purpose for now (battery might be most usefull besides percentage?)

**Comment by manup** [comment]
Might be related: https://github.com/dresden-elektronik/deconz-rest-plugin/commit/f0ba5e017172b74cc1201bbc0f73b95da1a65b5f

**Comment by wvuyk** [comment]
@manup thanks, it might. Will wait for a new version and will rejoin the sensor to see what happens.

**Comment by manup** [comment]
Looks like the sensor might just have a newer firmware and also includes IAS Zone cluster

![image](https://user-images.githubusercontent.com/383386/49732244-43e59b80-fc7e-11e8-9c86-e46604b35d61.png)

Note also application version 5

![image](https://user-images.githubusercontent.com/383386/49732279-5eb81000-fc7e-11e8-9b02-ecc87e7db689.png)

**Comment by wvuyk** [comment]
Not here, pressing 0, pressing read, causing motion does not fill the basic cluster. IAS zone here is also filled. This sensor came in last year I think, should be a first version?

**Comment by ebaauw** [comment]
Or the cluster had been there all along, but is only discovered by deCONZ with the improved pairing logic.  I’m seeing a lot of “new” clusters for many Xiaomi devices since these improvements.

**Comment by manup** [comment]
Her is a sample from my other motion sensor bought in 2017

No IAZ Zone cluster and device type Dimmer Switch

![image](https://user-images.githubusercontent.com/383386/49748697-b5d1db00-fca6-11e8-945b-223910038c6f.png)

Has application version 3

![image](https://user-images.githubusercontent.com/383386/49748722-c5e9ba80-fca6-11e8-95d9-e8943254b7c1.png)

**Comment by manup** [comment]
Sniffer Simple Descriptor response for the 2017 sensor

![image](https://user-images.githubusercontent.com/383386/49749421-88862c80-fca8-11e8-9527-86595526c2a1.png)

**Comment by wvuyk** [comment]
Good old Hitchhikers Guide! LOL Still love the humor in it.

I had to go back into histroy here, but indeed the sensors (7 total) came in April this year, so they might be newer in version. Have been trying again to read the cluster here, but it does not go any further then getting the model identifier. For some reason it does not want to reveal its secrets :-)

![image](https://user-images.githubusercontent.com/30700296/49753164-ce47f280-fcb2-11e8-80b6-4ab730104711.png)

**Comment by manup** [comment]
The Xiaomi sensors are very quite, there are only two ways to query data (ZDP, ZCL)

* Within 500 milliseconds after the hourly special report is received
* Read a single attribute in cluster info, and quickly press the button on the sensor once
* For switches it seems to be possible to 5 times press a button to trigger a parent/mac poll request

Just added some code to automatically read the datecode of Xiaomi end-devices (after hourly report) if it works we can use this to queue pending tasks like the vibration sensor configuration in this manner.

**Comment by wvuyk** [comment]
owww.. and update the sensitivity of the vibration sensor? That would be a nice one. Have one here, but it does not update very easy so far.

**Comment by manup** [comment]
![image](https://user-images.githubusercontent.com/383386/49756605-9f357f00-fcba-11e8-9acc-33ca61bf2c6d.png)

Cool, automatic query after hourly report seems to work.

A few notable things
* After special report is received (seq 202)
* Automatic read of datecode 
* The response has APS ACK enabled (might be handy haven't seen this before for Xiaomi sensors)
* Right after the ACK the sensor polls again (Data Request)


>owww.. and update the sensitivity of the vibration sensor? That would be a nice one. Have one here, but it does not update very easy so far.

Yes should be quite easy using the pending attribute, since we now know when the sensors are also listening we have a hopefully reliable window to configure the sensor (not only during setup).

**Comment by wvuyk** [comment]
Upgraded to 2.05.52, these motion sensors still add the ZHAAlarm sensor, although no attributes for this sensor are updated (lastupdated="none")... 

Should we just ignore this for now, or surpress it?

**Comment by MattL0** [comment]
Adding a xiaomi motion sensors still create a zhaalarm device.

any ways to delete this attribute?

**Comment by MattL0** [comment]
Please don’t forget :p
