### ISSUE TITLE
Device Integration: Add Heiman HS3SA Smoke Sensor

### ISSUE THREAD

**Issue by peer69** [dresden-elektronik/deconz-rest-plugin#1021]
I have receives the Heiman HS3SA Smoke Sensor. Is it possible to add it as a device? 

Basic Cluster: 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/28559804/50969118-9fa17f80-14dd-11e9-8366-4eb6c19d05a5.png">

IAS Zone Attributes: 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/28559804/50969132-ab8d4180-14dd-11e9-9828-d5e96f8112ab.png">

Node Info Panel:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/28559804/50960915-c3a59680-14c6-11e9-8266-cb524a25179f.png">

If needed I will provide the debug output.

**Comment by saxn-paule** [comment]
I also got two of the HS3SA-E smoke detectors. Pairing via Phoscon was possible, but it's always shown as not connected:
![image](https://user-images.githubusercontent.com/8352690/133047763-9c883679-8393-4956-8074-dda8c9c0a500.png)

Via Home-Assistant three entities are detected:
![image](https://user-images.githubusercontent.com/8352690/133048028-6b03ddfe-156e-414e-9c32-79ea85ae1801.png)

But they don't provide a status. In case of testing the alarm function nothing happens in Phoscon/HA.

**Comment by Mimiix** [comment]
@peer69 Does this device work correctly for you?

**Comment by peer69** [comment]
@Mimiix : Phoscon looks the same but the GUI shows connected and API also returns values that seem to be correct. So, yes. As much as its supposed to, it is working.
