### ISSUE TITLE
Xiaomi sensor going becoming unavailable for a very specific amount of time

### ISSUE THREAD

**Issue by GatoPharaoh** [dresden-elektronik/deconz-rest-plugin#1026]
for a few weeks now I am having trouble with some of my xiaomi door/window sensors. they seem to get unavailable pretty regularly. two of the sensors just become unavailable for about 50 minutes, then return for about 20 minutes to then become unavailable again for about 50 minutes.

this happens throughout the whole day. I reset them once which made the problem go away. but after some days and a reboot of my hub, one of the sensors started doing it again. a third sensor is also acting weirdly for a few weeks now, but there seems to be no pattern when it does so.

![sensor 1](https://user-images.githubusercontent.com/12106737/49838610-b607ce80-fdab-11e8-8882-b2d1359ab0c0.png)

![sensor 3](https://user-images.githubusercontent.com/12106737/49838644-e5b6d680-fdab-11e8-89f6-e71f731b3e28.png)

Any ideas what's the problem here?

thanks in advance

**Comment by rafuz** [comment]
I am using deconz in a docker container (from marthoc) and I am experiencing exactly this issue. When I reboot deconz some Xiaomi Mi Door/Window sensors starts to drop out on a timely basis:

![image](https://user-images.githubusercontent.com/22271829/49864515-ef1f5d80-fe02-11e8-98e1-b00d0505fc9f.png)


The sensors having this problem are always the same and if I reset them (10 seconds press + rejoin) the issue disappear and the sensor is stable again.
Yesterday evening a did a reboot of deconz and I collected the logs until this morning. I did a reset only of a couple of the affected sensosr and I have left the others in their unstable behaviour.

![image](https://user-images.githubusercontent.com/22271829/49864535-f8a8c580-fe02-11e8-915e-50a1d2ba0afd.png)

I have a full deconz log from the reboot yesterday to this morning.

[deconz.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2671558/deconz.zip)

I am using deconz for some smart plugs, tap switches and water sensors.

**Comment by rafuz** [comment]
Any idea about that?
I did a delete and rejoin of some of the problematic nodes. I will update if I find something different when I reboot Deconz

**Comment by manup** [comment]
Not sure how is dropout meant? Once the sensors become available there is in fact currently no code to mark them non reachable again.

Note for all Xiaomi battery devices it's important to know that if nothing happens (like window is closed all the time) they just send a heartbeat once per hour.

**Comment by manup** [comment]
>This thing happens only when I restart Deconz.

Since 2.05.50 the reachable state of sensors should be restored right after startup. Versions before did set reachable to false and waited until a sensor sends data.

>EDIT - Just an observation: the sensors goes back online exactly every hour when he sends the heartbeat and the goes back "not reachable" after 13-15 minutes. Everything can be seen in the log I attached in my first post.

Interesting, I'll check the logs I thought this isn't possible with current version looking forward to fix it in next version. I'm only having the Aqara version of the door/window contact which doesn't show this behavior.

**Comment by ebaauw** [comment]
>  I thought this isn't possible with current version

@manup, maybe deCONZ is trying to poll the sensor for a non-existing cluster, like you saw for the ZHAConsumption?

**Comment by rafuz** [comment]
> > This thing happens only when I restart Deconz.
> 
> Since 2.05.50 the reachable state of sensors should be restored right after startup. Versions before did set reachable to false and waited until a sensor sends data.
> 
> > EDIT - Just an observation: the sensors goes back online exactly every hour when he sends the heartbeat and the goes back "not reachable" after 13-15 minutes. Everything can be seen in the log I attached in my first post.
> 
> Interesting, I'll check the logs I thought this isn't possible with current version looking forward to fix it in next version. I'm only having the Aqara version of the door/window contact which doesn't show this behavior.

It should be ok to just set the sensor reachable at boot and to not query it for something that could bring it to "not reachable". In fact the sensor alway report the open/close state when the window moves so "it works". Only the states in Deconz seems messed up.

**Comment by rafuz** [comment]
I have done a reboot of deconz right now, many sensors are not reachable, also the ones that I have deleted and re-added in phoscon. I will check later the situation and report back with logs.

**Comment by rafuz** [comment]
After the reboot all re-created sensors came back online.
This evening I have deleted and re-paired all the remaining problematic sensors and I will try a reboot tomorrow in the evening to check if they begin to flap again. At this point I think that the original pairing of these sensors had some unknown issue and deleting from the REST interface and rejoining them fixed the issue.

**Comment by GatoPharaoh** [comment]
today shortly after midnight all the sensors in question stopped having trouble. I did not do any manual updates so I don't know why they suddenly started working again but as of now they do report as expected.

will continue to monitor the situation

**Comment by manup** [comment]
With version 2.05.54 the Xiaomi Mi branded sensors and switches should behave better and stay alive.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_54

**Comment by GatoPharaoh** [comment]
@manup after 24 hours I can say the following
door/window sensors started to act up after the update (I updated from 2.05.52) - I deleted and repaired them and the seem to work for now - but I'll continue to monitor it

_but one problem came with the update_
my xiaomi motion sensors now get stuck for hours reporting "movement.  they report movement when passing but sometimes the just do not go back to "no movement".
i then have to pass them again which makes them return to no movement after a minute. but they get stuck pretty regularly. 

one sensor also changed to movement by itself and got stuck there. don't know what's  going on with them.
![grafik](https://user-images.githubusercontent.com/12106737/50803176-f34b7780-12e9-11e9-9309-1bcc85a7e3e6.png)

**Comment by henel321** [comment]
I had the exact same issue yesterday after doing a restore of my config on 2.05.52 and then updating to 2.05.57 (Intrestingly enough the sensors where completely invisible after the restore on 2.05.52 so I thought my setup was completely dead, after updating to 2.05.57 all my config looked good again but 2 out of 4 Xiaomi window sensors going unavailable for periods of time. Not the same periods though.)

I reset/repaired them this afternoon and since then they are reporting properly again. So feels like this is a "fringe" case when sensors get into a weird state -  but it still is around post 2.05.54...  

I'm on 2.05.57, dpkg-installed on Debian so no Docker image. 

@rafuz what version were you on when you had problems and are you having any now?

**Comment by GatoPharaoh** [comment]
I'm now on 2.05.55 and reset the sensors which acted weird. After more than a week and multiple restarts they haven't gone unavailable yet. Only thing I still want to try is if this is still the case after updating to v .57.

**Comment by GatoPharaoh** [comment]
issue hasn't reoccured
