### ISSUE TITLE
No Issue - How to start with Restapi

### ISSUE THREAD

**Issue by Nobbbi** [dresden-elektronik/deconz-rest-plugin#1029]
Hi,

i use the Xiaomi WXKG01LM Round Switch.
Until now i used iobroker and a script to switch my ikea bulbs within deconz.

I would like to use the restapi to switch these lamps, i have problems to get startet.
I know the documentation from dresden elektronik.
What i need for a better understanding, are some examples.

What i like to do: 
one klick - lamp1 on/off
two klicks - lamp2 on/off 
three klick - all off 

Maybe someone can give me some hints, thank you !

**Comment by Smanar** [comment]
I haven't see something like that in API, I think you need to make all with your script, Counting the klick on a special period and send request according to it.

**Comment by manup** [comment]
>I thought that i can use the rest api to define rules, for all the things i can not realize with the phoscon web app.

That's correct, and intended. Currently our docs are very outdated, a more comprehensive version is in development. Anyway I suggest you study the Hue API rule and sensor example as they mostly work the same in the deCONZ REST-API.

The Hue Dimmer Switch and Hue Tap examples are a great entry point.

**Comment by Smanar** [comment]
Have you a public link for that pls ?
I m trying to search but the only link I found need a Hue developer account on philips site.

**Comment by manup** [comment]
I'm afraid you need to register to see the content, a bit cumbersome but it's free and worth it to get some docs.

**Comment by Smanar** [comment]
NP, I m going to see, thx.

**Comment by Nobbbi** [comment]
Thanks, i'll give it a try !

**Comment by manup** [comment]
Closing the issue for now.
