### ISSUE TITLE
Xiaomi Body motion sensor tempreture data

### ISSUE THREAD

**Issue by clockworkant** [dresden-elektronik/deconz-rest-plugin#1039]
I have a number of Xiaomi motion body sensors connected to a conbee.

In the rest api and the web gui I can see a temperature value which appears to be accurate!

What frequency is this temperature value updated and is there a way to have this value emitted by the web sockets api when it is available?

I've tried looking in the deconz-gui and I couldn't see the temperature as a readable field.

**Comment by manup** [comment]
The value is very coarse and is transmitted once per hour. It's available in the `config.temperature` attribute of the sensor resource.
