### ISSUE TITLE
Is there a way to see if a device meshes ? 

### ISSUE THREAD

**Issue by donnib** [dresden-elektronik/deconz-rest-plugin#104]
Hi,
I am interested in knowing whether OSRAM and IKEA lights will mesh together if both are ZLL devices ?

The reason i ask is that today i added a Osram Lightify Gardenpole which is a ZLL device. 3 meteres from it there is a GU10 Ikea spot (upgraded to newest firmware) so it's a ZLL device. I can't control the Osram lights, the Signal Monitor sends packs but doesn't give any useful results back so it's clearly a range issue. I was hoping the Osram could mesh with the IKEA GU10 light but doesn't seem so. I tried switching the Osram lights on/off in hope it will mesh thru the GU10 light but nothing happened. 

Is there a way i can see if a device meshes with another ? Should i be able to see it in the lines ? Can i somehow force it into this mode ?

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
