### ISSUE TITLE
Issue when switch configuration uses inc_bri

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#1040]
Up till now I have had no issues with my plugin geting the json information. 
But I have at least one user of my plugin who is using the switch configuration in Phoscon. He created a rule for his switch that increases his lights brightness. 

But because of that my plugin starts throwing errors reading the Json of the bridge - there is a rule present with a decimal value of "bri_inc": 63.5
To my knowledge bri_inc is normaly an integer, not decimals?

**Comment by ebaauw** [comment]
Correct.  Who created the rule?

**Comment by wvuyk** [comment]
The switch configurator in Phoscon?

**Comment by manup** [comment]
Good catch, will be fixed in 2.05.51, also the uniqueid issue for CLIP sensors created by the switch editor.

**Comment by manup** [comment]
2.05.51 is available now, however the new rules will only be written when the related switch editor configuration is updated or newly created.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_51
