### ISSUE TITLE
Remove a light from a group scene

### ISSUE THREAD

**Issue by Markkuuss** [dresden-elektronik/deconz-rest-plugin#1052]
Once a light has been added to a scene, it is no longer possible to remove the light from the scene with Phoscon.

It would be nice if you could add the feature in Phoscon that you can remove a light from scenes:
https://dresden-elektronik.github.io/deconz-rest-doc/lights/#removescenes

**Comment by Markkuuss** [comment]
This problem is not obsolete, it would still be desirable to remove a lamp from the scene. Currently this is not possible in Phoscon.

**Comment by remcotjeerdsma** [comment]
Still not fixed..
