### ISSUE TITLE
Centralite 3328-G and Motion Sensor-A integration request

### ISSUE THREAD

**Issue by imortkz** [dresden-elektronik/deconz-rest-plugin#1053]
https://www.amazon.com/gp/product/B0713STYJQ/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

https://www.amazon.com/gp/product/B01LXPGXQ1/ref=oh_aui_detailpage_o00_s01?ie=UTF8&psc=1

Can connect both to the deCONZ app, and can see temperature readings there, but not recognized in the webapp (and obviously REST API) sensors list.

Can I help adding them to the supported device list?
I have both on hand.
Is there any resources available to start working on them?

Thank you

**Comment by manup** [comment]
>Is there any resources available to start working on them?

Please provide the info as described in the Wiki
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by imortkz** [comment]
![sensor1 1](https://user-images.githubusercontent.com/12543016/50333393-69e92680-052f-11e9-83fa-cb1e464f0082.png)
![sensor1 2](https://user-images.githubusercontent.com/12543016/50333394-69e92680-052f-11e9-9148-539cc7bd631f.png)
![sensor1 3](https://user-images.githubusercontent.com/12543016/50333389-68b7f980-052f-11e9-9f99-47fd9b5000f1.png)

![sensor2 1](https://user-images.githubusercontent.com/12543016/50333392-69509000-052f-11e9-98ef-5933071d78ed.png)
![sensor2 2](https://user-images.githubusercontent.com/12543016/50333390-69509000-052f-11e9-88c6-1d23adae5692.png)
![sensor2 3](https://user-images.githubusercontent.com/12543016/50333391-69509000-052f-11e9-8ee9-380bed2c03f3.png)


Is there anything else I could help with?
Thank you!

**Comment by manup** [comment]
The Motion Sensor-A is fixed now and will be fully supported with 2.05.57.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/881

3328-G should work too, but needs to be tested.

**Comment by imortkz** [comment]
Will test them in the next couple of days and report, thank you!

**Comment by Spielvererber** [comment]
Retested this with 2.05.59. Battery status is now reported correctly (binary). I've also been able to validate the fix for continuous motion. I've noticed that the sensor irregularly falls back to "no motion" despite the presence of motion after 3-5 minutes, but haven't figured out a pattern yet.

**Comment by bramd** [comment]
I have two Centralite 3328-G sensors connected and can access them via the REST API. However, they don't show up in the webapp.

I suspect this might be due to the swversion field containing garbage. Both sensors don't report their swversion correctly. Could we ignore invalid swversion data or make the webapp cope with it?

Sensors output from REST API:

```
{
  "11": {
    "config": {
      "battery": null,
      "duration": 60,
      "on": true,
      "pending": [],
      "reachable": true
    },
    "ep": 1,
    "etag": "5b3ae9b337779030f779a327172300c5",
    "manufacturername": "CentraLite",
    "modelid": "3328-G",
    "name": "3328-G (2)",
    "state": {
      "lastupdated": "2019-12-30T09:36:48",
      "lowbattery": false,
      "presence": true,
      "tampered": false
    },
    "swversion": "����������������",
    "type": "ZHAPresence",
    "uniqueid": "00:0d:6f:00:0b:be:07:13-01-0500"
  },
  "12": {
    "config": {
      "battery": null,
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "5e11647ca48b3d19c28d79d2b4ee1c5c",
    "manufacturername": "CentraLite",
    "modelid": "3328-G",
    "name": "3328-G (2)",
    "state": {
      "lastupdated": "2019-12-30T09:33:16",
      "temperature": 1780
    },
    "swversion": "����������������",
    "type": "ZHATemperature",
    "uniqueid": "00:0d:6f:00:0b:be:07:13-01-0402"
  },
  "2": {
    "config": {
      "battery": null,
      "duration": 60,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "1c523b746fd66fbbf79593c3620c61eb",
    "manufacturername": "CentraLite",
    "modelid": "3328-G",
    "name": "3328-G",
    "state": {
      "lastupdated": "2019-12-30T09:36:41",
      "lowbattery": false,
      "presence": true,
      "tampered": false
    },
    "swversion": "����������������",
    "type": "ZHAPresence",
    "uniqueid": "00:0d:6f:00:0b:bd:0d:b3-01-0500"
  },
  "3": {
    "config": {
      "battery": null,
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "77568e9c7215d27ca542c1ad329c4305",
    "manufacturername": "CentraLite",
    "modelid": "3328-G",
    "name": "3328-G",
    "state": {
      "lastupdated": "2019-12-30T09:33:21",
      "temperature": 1757
    },
    "swversion": "����������������",
    "type": "ZHATemperature",
    "uniqueid": "00:0d:6f:00:0b:bd:0d:b3-01-0402"
  }
}
```
