### ISSUE TITLE
Don't succeed in updating deConz

### ISSUE THREAD

**Issue by olderbag** [dresden-elektronik/deconz-rest-plugin#1054]
I'm running deConz in a UBUNTU 16.04 VM on Proxmox.

Tried to update deConz with following output:
`user@VM-Ubuntu:~$ sudo dpkg -i deconz-dev-2.05.52.deb
(Lese Datenbank ... 185502 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von deconz-dev-2.05.52.deb ...
Entpacken von deconz-dev (2.05.52) über (2.05.52) ...
deconz-dev (2.05.52) wird eingerichtet ...
user@VM-Ubuntu:~$`

Bt even after rebbot of the VM still 2.05.20 is running:
![image](https://user-images.githubusercontent.com/39123738/50158178-afa9b300-02d3-11e9-956a-1326d577ad19.png)

Can u help me pls to analyse what's going wrong? Unfortunately i'm not the LINUX expert.

**Comment by manup** [comment]
This is only the -dev package, you also need to install the deCONZ package

https://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.05.52-qt5.deb

**Comment by manup** [comment]
And please make a backup first in the Phoscon App :)

**Comment by olderbag** [comment]
Worked finally - after chanching the path to UBUNTU sources. :-)

Thanks!!!
