### ISSUE TITLE
Aqara TW LED (ZNLDP12LM) looks in Deconz like a Color bulb, not a TW one.

### ISSUE THREAD

**Issue by oleg77s** [dresden-elektronik/deconz-rest-plugin#1057]

**Comment by Arsur** [comment]
How where you able to find it over phoscon? Iam using a Conbee with docker (everything updated to final version). I have several bulbs from different vendors already in use, witch all work perfect. Only this Aqara TW E27 is not findable...

**Comment by oleg77s** [comment]
Just reset Aqara bulb before add it to Phoscon

**Comment by Arsur** [comment]
Okay its pair by 5x On and Off. I can aprove that the TW bulbs are wrong mapped as color blubs

**Comment by manup** [comment]
Can you please check which value is shown in the *Color Control* cluster for the *Color Capabilities* attribute?

Do the sensor clusters actually provide real values or are they dummies?

**Comment by oleg77s** [comment]
value is shown in the Color Control cluster
![1](https://user-images.githubusercontent.com/23496372/51625824-3430c680-1f4f-11e9-9b49-f5cbf5f52150.png)
![2](https://user-images.githubusercontent.com/23496372/51625829-37c44d80-1f4f-11e9-8b5b-31975d780144.png)

sensor clusters values?
occupancy sensing, pressure, humidity and temperature values are dummies

**Comment by manup** [comment]
Okay that is messed up. Since the light is a Home Automation lights and doesn't support color capabilities, technically it isn't allowed to support color temperature.

Guess it's another Xiaomi interpretation of the standard ;)

Question is wether it support the color temperature control commands or the color can only be set with xy commands.

You may check if the "Move to Color Temperature" commands work with values like 160, 300, 400, ...

**Comment by oleg77s** [comment]
yes, bulb changed CT if  Move to Color exec 100, 200, 500 from cold to warm

**Comment by oleg77s** [comment]
deCONZ 2.05.58:  you can change color temperature now
Thanks so much, manup 
![2019-01-31 21 12 07](https://user-images.githubusercontent.com/23496372/52075589-b6e40200-259d-11e9-9013-fcb84736e9e3.png)

**Comment by Klagio** [comment]
> Just reset Aqara bulb before add it to Phoscon

Hi, I did this (5 times on off, last on), the bulb seems to be reset (turns itself on-off-on), then I click add new light in phoscon ... but no light is detected..?

**Comment by morfei1** [comment]
The Aqara TW LED (ZNLDP12LM) does not update it's state, if it's switch Off (Phoscon, HA) and then, it's powered off (from the wall switch). The light state is reported as Off. It does not updates to unavailable for example as Tradfri Bulbs.

The workaround for this to not mess it's state is to never switch it off from Phoscon, HA, but instead dim it to 1%, or never power it Off from the wall switch.

**Comment by azelinc** [comment]
since this is zigbee, can it act as repeater? i wanted to extend the range of my zigbee coverage. i read that powered zigbee devices will automatically act as repeater. is it as simple as that?

**Comment by morfei1** [comment]
Yes it will be a repeater. Anyway, if you power it off from the wall switch it's not able to repeat.

**Comment by azelinc** [comment]
> Yes it will be a repeater. Anyway, if you power it off from the wall switch it's not able to repeat.

I did not get you. Then how do i power it if i want it to be repeater?

**Comment by morfei1** [comment]
You have to switch it on/off from software, for example phoscon, Home Assistant and so on.

**Comment by azelinc** [comment]
> You have to switch it on/off from software, for example phoscon, Home Assistant and so on.

i see. you mean it cannot be powered off thru the wall switch (=cut off power entirely).
Then it s okay, that s the plan anyway. Thanks!

**Comment by MrMimic** [comment]
Hi guys. I'm not able to include any ZNLDP12LM in DeconZ with the RaspBee II gateway.

Nothing happens neither in DeconZ nor in Phoscon when the bulb is tuned on/off several times until it blinks.

WHat gateway are you using ?
