### ISSUE TITLE
Lightify a19 tunable white showing unexpected fields in rest api

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#1059]
A user of my plugin is using this lightifyl bulb. It should support CT values, but it is not presented in the REST API results. It shows as a xy only bulb?
Sending a CT command through the REST API addresses the bulb correctly and the CT is set on the bulb. Main issue, the CT value is not returned through the api. Is this because it is OSRAM (....) or just a miss for some reason?

![image](https://user-images.githubusercontent.com/30700296/50177537-85bbb500-0302-11e9-8c23-34306b16c538.png)

**Comment by manup** [comment]
Some screenshots of the endpoints and clusters would be helpful.
Also in the color control cluster the `color capabilities` attribute.

**Comment by MattL0** [comment]
I manup,

I am sorry I am running deconz on a headless machine :s So i can’t have access to those values I think?

And i removed thoses two osram bulbs and replaced them with hue bulbs.

But I can readd then for testing purpose
