### ISSUE TITLE
v2.05.52 lost connection to Deconz and Phoscon

### ISSUE THREAD

**Issue by heitec11** [dresden-elektronik/deconz-rest-plugin#1061]
After update from 44 to 52 the connection between Raspbee and Deconz/Phoscon has lost. The Rest-API is still running but only with the existing sensors. To add new sensors which are now available in the software is not possible. The update of the firmware was successful by the GCFFlasher but has no effects.

**Comment by manup** [comment]
>After update from 44 to 52 the connection between Raspbee and Deconz/Phoscon has lost. T

Do you mean deCONZ doesn't show any nodes?

**Comment by heitec11** [comment]
deCONZ was unable to connet. I have start with a new image, automatic update to 50 and then manuell update to 52. At the moment the system is running.
