### ISSUE TITLE
Samsung SmartThings outletv4 power plug

### ISSUE THREAD

**Issue by apmon** [dresden-elektronik/deconz-rest-plugin#1062]
Hello,
Is it possible to get the power metering for the Samsung SmartThings power plug (US) exported through the rest API?

Attached are the screenshots from deCONZ:

![screen shot 2018-12-19 at 11 23 45 am](https://user-images.githubusercontent.com/251447/50240197-644dde00-0381-11e9-9f37-f68993b057b0.png)

![screen shot 2018-12-19 at 11 23 13 am](https://user-images.githubusercontent.com/251447/50240226-716acd00-0381-11e9-9ba3-f4645e50ba7c.png)

![screen shot 2018-12-19 at 11 22 03 am](https://user-images.githubusercontent.com/251447/50240252-83e50680-0381-11e9-93d1-0b58a4c7b9a8.png)

![screen shot 2018-12-19 at 11 21 40 am](https://user-images.githubusercontent.com/251447/50240268-8d6e6e80-0381-11e9-8246-ecf97d51ece5.png)

**Comment by clementx2006** [comment]
seems Duplicate of #819 ?

**Comment by apmon** [comment]
Manufacturer Name and model number seem different, which is why I opened a separate ticket. The electrical measurement cluster also seems to have some differences.

**Comment by clementx2006** [comment]
em - not sure if this one is ever going to be resolved...

**Comment by manup** [comment]
Our near future plan is to order and support most of the LEDVANCE, Samsung / Smart Things devices which are popular in the US.

**Comment by clementx2006** [comment]
Can we reopen this? Samsung released a new plug this year (2019). Would really love to see this one working (for power monitoring)...

**Comment by smartypantsuk** [comment]
I'll second this. Samsung have released a Smartthing Smart Plug with power metering (UK) too.
Reasonably well priced and good quality. Can we get support? I think the UK model variant is GP-WOU019BBDWG
