### ISSUE TITLE
Jung Transmitter module 4-gang

### ISSUE THREAD

**Issue by esseki** [dresden-elektronik/deconz-rest-plugin#1064]
Hi,

i'm planning to go for some of those Jung ZigBee radio transmitter module 4-gang : https://www.jung.de/en/online-catalogue/374871597/

But when checking in the list of Deconz supported devices : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices it is not mentioned what kind of events i can expect to be fired from this transmitter. Unless it means that no event are actually fired and it works only in direct association mode (when bulbs are added to the group created by the transmitter itself) ?

It is important to me that the transmitter fires event as i plan to catch them from my Home Automation solution (Home assistant) to trigger some scenarios that might not be related to lightning.

I would expect that this transmitter is capable of the following events : 123, 123 (for both dim buttons at the top) and at least 2, 2, 2, 2 (for the 4 scene buttons at the bottom).

Can anybody having one of these transmitter confirm that this is actually the case before i order any ?

Thank you in advance for your responses.

**Comment by manup** [comment]
>I would expect that this transmitter is capable of the following events : 123, 123 (for both dim buttons at the top) and at least 2, 2, 2, 2 (for the 4 scene buttons at the bottom).

That's correct. You can Either use these events to program some logic, or put lights in the group which the switch controls. The latter also works when the gateway is not available/powered.

**Comment by esseki** [comment]
Thank you @manup  for your quick response. Will order one and test it.

**Comment by manup** [comment]
One thing to note: Try to avoid connecting it via Ikea lights, if possible force the switch to chose a parent from a different brand or the gateway directly.

**Comment by Slofware** [comment]
@manup How do you do that? I have some Ikea lights and they give me a problem after a day that the switch is no longer working.

**Comment by esseki** [comment]
@Slofware I think to do that you should switch off (with the wall switch connected to your electricity network) all the bulbs in your install. Since the bulb won't be live in your Zigbee network, the Jung switches will not have other option than connecting to the gateway directly.
