### ISSUE TITLE
DeConz hangs waiting for firmware update

### ISSUE THREAD

**Issue by gmitch64** [dresden-elektronik/deconz-rest-plugin#1065]
I'm currently running deConz 2.05.48 (I'm waiting for the issues from versions 50/51 etc. to stabilize). All my lights are on my Hue hub, and I'm running deConz on a Pi, which is where all my switches are connected.

I came down this morning, and none of my switches would work. Since the bulbs were on the Hue hub, I was able to control them with my phone. When I went to check why the switches weren't working, I did a VNC into the Pi, and deConz was at the firmware update screen, waiting for me to press a key to start the update.

I ran the update (to version 0x262F0500, which processed fine, and as soon as it was completed, all the switches started to work. Unfortunately, I didn't make a note of the previous firmware version.

Is there a setting to turn off that behavior? The system shouldn't basically go non responsive because it wants a firmware update.

G

**Comment by manup** [comment]
Does the issue still remain with recent versions?
