### ISSUE TITLE
Phoscon App can't find gateway

### ISSUE THREAD

**Issue by braini1511** [dresden-elektronik/deconz-rest-plugin#1070]
Hi there,

after installing Deconz on raspbian i got some troubles with deconz. I need to start it manually, it will not auto-start. But after starting and trying to login i get the new Phoscon-GUI. It searching for a Phoscon-Gateway but can't find the Pi with the Raspbee module.
Not saure what the problem is here. Any ideas? what infos do you need for helping me here?

Best regards
René

**Comment by manup** [comment]
To enable autostart you need to enable the systemd service:

    sudo systemctl enable deconz-gui

Which browser are you using? There is currently an related issue with Safari, which is already fixed in the online version http://dresden-elektronik.de/pwa
