### ISSUE TITLE
Xiaomi Door Sensor MCCGQ11LM looses connection

### ISSUE THREAD

**Issue by alex0411** [dresden-elektronik/deconz-rest-plugin#1074]
Hello,
one of my xiaomi door sensor MCCGQ11LM looses the connection after some time. I already tried switching the battery and placing a osram smart plug (as router) next to it, but that did not help. 
The only way to get the sensor working again, is to rejoin the network.
Do you have an idea what the reason for this could be?

**Comment by manup** [comment]
I hope this issue is addressed with the latest commits https://github.com/dresden-elektronik/deconz-rest-plugin/commit/e59018a28dbe16bf38e9fbe097d8dad347306d8b

(Given this is a older Mi version of the sensor)

**Comment by alex0411** [comment]
The sensor is an Aqara version....

**Comment by manup** [comment]
Is the datecode shown in the Phoscon App?

Which version of deCONZ and firmware are you running?

**Comment by alex0411** [comment]
What do you mean with "datecode"?
![image](https://user-images.githubusercontent.com/45571502/50538049-2e6edd80-0b69-11e9-8b8c-0dff9e7bf148.png)
Phoscon 2.05.52 / Firmware 262F0500

**Comment by ebaauw** [comment]
Same version as mine (but I've got one with 20161014 as well).  Never had any issues with these.  Probably caused by routing issues in the network.

**Comment by alex0411** [comment]
Can you tell me how to solve routing issues, never had any until now...

**Comment by manup** [comment]
![image](https://user-images.githubusercontent.com/383386/50538484-d045f880-0b70-11e9-85e3-c99047dc598f.png)

Might be related, I have another window/door (MCCGQ11LM) sensor running since yesterday, were the parent (light stripe) was powered off. Till now the sensor didn't recover on its own. As you can see in the sniffer it stubbornly tries to route through the powered off router.

The sensor was in same closed state the whole time.

However after doing open/close manually a few times the sensor did recover and selected a new parent:

![image](https://user-images.githubusercontent.com/383386/50538525-5a8e5c80-0b71-11e9-84d6-952a9cbd15f7.png)

**Comment by alex0411** [comment]
I did a few open/close manually too and then the sensor started to blink a few times, but still no recover. A Osram Smart Plug is next to the sensor.
Any ideas?

**Comment by manup** [comment]
Just a test, but can you please power off the plug and do the open/close again.

If possible you may provide a screenshot of deCONZ to see connection quality.

**Comment by alex0411** [comment]
Yes, deCONZ is running in headless mode...is there no way without the GUI version?

**Comment by manup** [comment]
Only by logging, it's a bit verbose but also contains more details.

You can start deCONZ with the following parameters to create a log.txt file:

    deCONZ --dbg-aps=1 --dbg-zdp=1 --dbg-info=1 --http-port=80 > log.txt

All nodes are periodically polled for their neighbors and children tables, these contain the link quality (LQI)  between nodes.

This provides the information:
* To which parent the sensor is connected
* How good/bad the LQI is

**Comment by alex0411** [comment]
Okay I did the debugging, but I wasn't able to find the sensor. I had to rejoin the sensor to see it in the logging:
`14:32:28:416 APS-DATA.indication srcAddr: 0x00158d000236fd0d, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x0013, lqi: 255, rssi: -38
14:32:28:416 ZDP device announce: 0x00158D000236FD0D, 0x9AE3, 0x80
14:32:28:416 0xA844 nwk changed to 0x9AE3
14:32:28:417 DeviceAnnce of SensorNode: 0x00158D000236FD0D [1]
14:32:28:417 	nwk address changed 0x0000 -> 0x9AE3 [2]
14:32:28:417 device announce 0x00158D000236FD0D (0x9AE3) mac capabilities 0x80
14:32:28:417 set fast probe address to 0x00158D000236FD0D (0x9AE3)
14:32:28:417 device announce 0x00158D000236FD0D (0x9AE3) mac capabilities 0x80
14:32:28:417 set fast probe address to 0x00158D000236FD0D (0x9AE3)
14:32:28:432 APS-DATA.confirm id: 53, status: 0x00 SUCCESS
14:32:28:432 APS-DATA.confirm request id: 53 -> confirmed, timeout 34503288
14:32:28:497 APS-DATA.indication srcAddr: 0x0017880103dc1187, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -45
14:32:28:497 APS-DATA.indication request id: 53 -> finished
14:32:28:497 APS-DATA.request id: 53 erase from queue
14:32:28:497 ZDP status = 0x00 -> SUCCESS
14:32:28:497 ZDP Mgmt_Lqi_rsp zdpSeq: 16 from 0x0017880103DC1187 total: 10, startIndex: 6, listCount: 2
14:32:28:497     * neighbor: 0x7CB03EAA0A02CE1E (0x736D), LQI: 160, relation: 0x03 rxOnWHenIdle: 1
14:32:28:497     * neighbor: 0x001788010302C4DC (0x3C3B), LQI: 191, relation: 0x03 rxOnWHenIdle: 1
14:32:28:523 [1] get node descriptor for 0x00158d000236fd0d
14:32:28:523 APS-DATA.request id: 57, addrmode: 0x02, addr: 0x9ae3, profile: 0x0000, cluster: 0x0002, ep: 0x00 -> 0x00 queue: 0 len: 3 tx.options 0x04
14:32:28:609 APS-DATA.indication srcAddr: 0x00158d000236fd0d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 255, rssi: -39
14:32:28:609 no button map for: lumi.sensor_magnet.aq2 ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 005
14:32:28:610 ZCL attribute report 0x00158D000236FD0D for cluster 0x0000, ep 0x01
14:32:28:610 0x00158D000236FD0D skip Xiaomi attribute 0x0005
14:32:28:615 wait response fastEnddeviceProbe() 0x00158D000236FD0D, elapsed 93 ms
14:32:28:737 APS-DATA.indication srcAddr: 0x00158d000236fd0d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 255, rssi: -37
14:32:28:738 no button map for: lumi.sensor_magnet.aq2 ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 001
14:32:28:738 ZCL attribute report 0x00158D000236FD0D for cluster 0x0000, ep 0x01
14:32:28:738 0x00158D000236FD0D extract Xiaomi special
14:32:28:738 	01 battery 3015 (0x0BC7)
14:32:28:738 	03 temperature 22 °C
14:32:28:738 	04 unknown 424 (0x01A8)
14:32:28:738 	05 RSSI dB (?) 9363 (0x2493)
14:32:28:738 	06 LQI (?) 4294967296 (0x0100000000)
14:32:28:738 	0a unknown 23913 (0x5D69)
14:32:28:738 	64 on/off 0
14:32:28:742 discard sensor config push for config/temperature (already pushed)
14:32:28:744 wait response fastEnddeviceProbe() 0x00158D000236FD0D, elapsed 221 ms`

`14:32:29:361 APS-DATA.indication srcAddr: 0x00158d000236fd0d, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8002, lqi: 255, rssi: -38
14:32:29:361 APS-DATA.indication request id: 57 -> finished
14:32:29:361 APS-DATA.request id: 57 erase from queue
14:32:29:361 ZDP status = 0x00 -> SUCCESS
14:32:29:361 ZDP Node_Descriptor_rsp 0x00158D000236FD0D - 0x9AE3
14:32:29:361 DB save zll database items 0x000008C0
14:32:30:160 DB saved in 799 ms
14:32:30:161 ZDP indication search sensors 0x00158D000236FD0D (0x9AE3) cluster 0x8002
14:32:30:175 [2] get active endpoints for 0x00158d000236fd0d
14:32:30:175 APS-DATA.request id: 69, addrmode: 0x02, addr: 0x9ae3, profile: 0x0000, cluster: 0x0005, ep: 0x00 -> 0x00 queue: 0 len: 3 tx.options 0x00
14:32:30:241 APS-DATA.confirm id: 69, status: 0x00 SUCCESS
14:32:30:241 APS-DATA.confirm request id: 69 -> confirmed, timeout 35495704
14:32:32:851 APS-DATA.indication srcAddr: 0x00158d000236fd0d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 255, rssi: -37
14:32:32:852 no button map for: lumi.sensor_magnet.aq2 ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 005
14:32:32:852 ZCL attribute report 0x00158D000236FD0D for cluster 0x0000, ep 0x01
14:32:32:852 0x00158D000236FD0D skip Xiaomi attribute 0x0005
14:32:32:852 0x00158D000236FD0D extract Xiaomi special
14:32:32:852 	01 battery 3015 (0x0BC7)
14:32:32:852 	03 temperature 23 °C
14:32:32:852 	04 unknown 424 (0x01A8)
14:32:32:852 	05 RSSI dB (?) 9363 (0x2493)
14:32:32:852 	06 LQI (?) 0 (0x0000000000)
14:32:32:852 	0a unknown 23913 (0x5D69)
14:32:32:852 	64 on/off 0
14:32:32:856 discard sensor config push for config/temperature (already pushed)
14:32:32:857 wait response fastEnddeviceProbe() 0x00158D000236FD0D, elapsed 2682 ms`

**Comment by alex0411** [comment]
And after some time, no signal from the sensor:

```
14:55:57:977 ZDP Mgmt_Lqi_rsp zdpSeq: 158 from 0x0017880102EBDC91 total: 11, startIndex: 10, listCount: 1
14:55:57:977     * neighbor: 0x00158D000236FD0D (0x9AE3), LQI: 255, relation: 0x01 rxOnWHenIdle: 0
```

**Comment by manup** [comment]
Hmm actually initial communication looks fine, all data is received. 

The following commands need to be watched:
```
14:55:57:977 ZDP Mgmt_Lqi_rsp zdpSeq: 158 from 0x0017880102EBDC91 total: 11, startIndex: 10, listCount: 1
14:55:57:977     * neighbor: 0x00158D000236FD0D (0x9AE3), LQI: 255, relation: 0x01 rxOnWHenIdle: 0
```

These should appear from time to time for all routers and show the local neighbor tables of that device. With 2–3 entries per response.

Here you can see that the sensor has selected the 0x0017880102EBDC91, the Hue light, as its parent. Relation 0x01 means child relation and LQI 255 is best quality.

Is this light always powered?
Further, if between the light and the sensor are doors/windows they can affect signal – albeit I don't think that's the issue here.

**Comment by alex0411** [comment]
Yes the light is always powered.

I deleted the sensor again and placed the raspberry with deconz next to the sensor. After pairing it worked pretty well. 10 minutes later no signal from the sensor.

Do you have any further ideas what I could do? Or maybe the sensor is broken?

**Comment by alex0411** [comment]
Okay now my second Xiaomi window sensor lost its connection...
Could there be an issue with routers (like Hue Bulbs or Osram Plugs)? Because since I moved the conbee closer to the first sensor, the second is next to a hue Bulb.

**Comment by BenLinnik** [comment]
I have the same issue. 
Devices just lose connection over night. 
![image](https://user-images.githubusercontent.com/12953323/56090894-4a905380-5ea8-11e9-9456-5aad8a3dff61.png)
![image](https://user-images.githubusercontent.com/12953323/56090904-698ee580-5ea8-11e9-90fd-31130b65f291.png)
![image](https://user-images.githubusercontent.com/12953323/56090925-a2c75580-5ea8-11e9-9893-1f793cb7ec24.png)

Pressing buttons on the door sensors doesn't work.. I'm afraid if there is no fix I will send my Conbee II back.

**Comment by manup** [comment]
Hi, please update deCONZ to latest 2.05.62 and upgrade the firmware to 0x26480700.

We had to modify some handling in last versions, in order to keep Xiaomi devices connected.

**Comment by BenLinnik** [comment]
> Hi, please update deCONZ to latest 2.05.62 and upgrade the firmware to 0x26480700.
> 
> We had to modify some handling in last versions, in order to keep Xiaomi devices connected.

Wow, quick reply! Will try! Thanks a lot for the quick reply!

**Comment by pergolafabio** [comment]
Does this also fix with xiaomi pir motion sensors? I see above door sensors...
But I have pir sensors, they loose connection too after a while , but the connection also comes back after a short while, maybe like 15 min...
Also using Osram smart plugs here as routers

**Comment by BenLinnik** [comment]
My first 24 hours of stable operation of two Xiaomi Door/Window sensors so far. Let's see how it will behave tomorrow. Installation was easy: Have a raspberry pi image,
```
1) logged in via vnc or ssh ( pi // raspbeegw )
2) Stop deconz
$ sudo systemctl stop deconz (Headless version), or
$ sudo systemctl stop deconz-gui (GUI version)
2) downloaded the latest deCONZ beta deb file [here](https://www.dresden-elektronik.de/rpi/deconz/beta/):
$ wget https://www.dresden-elektronik.de/rpi/deconz/beta/deconz-latest-beta.deb
3) install: $ sudo dpkg -i deconz-latest-beta.deb
4) Have deCONZ up and running again.
sudo systemctl start deconz (Headless version), or
sudo systemctl start deconz-gui (GUI version)
```
