### ISSUE TITLE
Heiman Carbon Monoxide Sensor cannot connect

### ISSUE THREAD

**Issue by Thoit** [dresden-elektronik/deconz-rest-plugin#1077]
Hi,

I've bought a Heiman Smart Carbon Monoxide Sensor. Before I bought the sensor, I checked the compatibility list, and the sensor is in the list. I've tried to connect it now for more then one hour, but no success. 

I'm trying to connect it by quick pressing the connect button 3 times. When I hold the connect button for about 10 seconds, the light blinks a couple of times and the connection status in Phoscon says ready, but no device is displayed. 

The setup: 
- Home Assistant (Version 141)
- Deconz (Version 2.05.52)
- Heiman HS1CA-M
- Phoscon (Version 2.05.52 / 12/16/2018 Firmware 261F0500)

I've got connected 14 other devices without any problem (Xiaomi and Ikea devices), so the Conbee stick is working correctly.

**Comment by robrea** [comment]
Hi @Thoit,

Did you find a solution? I am having the same problem.

Thanks,
Rob

**Comment by robrea** [comment]
Hi @Thoit,

Did you find a solution? I am having the same problem.

Thanks,
Rob

**Comment by Thoit** [comment]
Unfortunately not @robrea never received any suggestions from Dresden Electronics

**Comment by robroll** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1563

**Comment by GitHubxtsnl** [comment]
I'm having the same issue.
I'm running Home Assistant 2021.2.3
deCONZ 6.7.0
ConBee II 26660700 / 2.09.03 / 12/23/2020

I've got this CO device from Ali:
https://www.aliexpress.com/item/4001031100655.html?spm=a2g0s.9042311.0.0.6da04c4dTuT4Ht

![image](https://user-images.githubusercontent.com/43134674/107992415-f2ad6100-6fd8-11eb-9f32-ef28ba599b42.png)

![image](https://user-images.githubusercontent.com/43134674/107992443-035dd700-6fd9-11eb-8fbc-8749f7349f4d.png)

![image](https://user-images.githubusercontent.com/43134674/107992474-14a6e380-6fd9-11eb-9e21-3ab2bb942186.png)

I can see it is connected, the green line, but I cannot change the Node name nor does it come up in HA.
I think it is not supported yet by deCONZ / ConBee

any ideas or suggestions on how to get this device working?

**Comment by SwoopX** [comment]
The device is not supported yet. It just looks like a Heiman, but to 99% isn't one. Please raise a device support request.

**Comment by GitHubxtsnl** [comment]
thank you @SwoopX for the reply. Sorry for my ignorance but how do I raise a device support request?
