### ISSUE TITLE
Add support for Lupus Mains Socket

### ISSUE THREAD

**Issue by tseroo** [dresden-elektronik/deconz-rest-plugin#1082]
Any chance to get this device integrated? Struggling to get the powermeter data.

![image](https://user-images.githubusercontent.com/10330889/50635451-7f5c4880-0f52-11e9-9447-4ab95b18c08c.png)

![image](https://user-images.githubusercontent.com/10330889/50635500-b9c5e580-0f52-11e9-8de8-71190d646a19.png)
![image](https://user-images.githubusercontent.com/10330889/50635506-c34f4d80-0f52-11e9-9b7a-86ad8fa4d678.png)

![image](https://user-images.githubusercontent.com/10330889/50635545-e24ddf80-0f52-11e9-8ca6-83ececec10af.png)

**Comment by tseroo** [comment]
Seems the Lupus device is identical in construction with the Bitron 902010/25, still I'm not able to get the power measurements as there is no Sensor created for the device. Any chance to get this added?

**Comment by manup** [comment]
The are both branded versions of the Climax Plug. I'll add the modelid to whitelist,  the related sensors should then be created.

**Comment by tseroo** [comment]
Sounds good. Just tell me if/when I should do some testing.

**Comment by tseroo** [comment]
@manup Any idea when you can make the change?

**Comment by manup** [comment]
Should work with 2.05.55, but the plug needs to be joined again to create the resource.

**Comment by tseroo** [comment]
Finally I had some time to test this and the good news is, it is working. But some tweaking is still needed as the scaling is not correct. It reports 377 W instead of 37.7W. So both values, power and consumption, have to be divided by 10 to deliver the correct values. Thanks so far!

**Comment by tseroo** [comment]
@manup Any chance you can get the scaling fixed for the Lupus plug?
