### ISSUE TITLE
Switch wxkg01lm

### ISSUE THREAD

**Issue by fonzies83** [dresden-elektronik/deconz-rest-plugin#1084]
Dear,
I try to add this switch using the instruction to press the reset button for 5 second after click add switch. In the Deconz the sensor is present liche lumi.sensor and if i click the button of the switch in the deconz the led of lumi.sensor blink. But in the phoscon app appear always failed to connect. In this way I cannot see the switch in home assistant and use it. Any solution?
Thank you and regards

![schermata da 2019-01-03 21-52-03](https://user-images.githubusercontent.com/46358264/50661168-9460c800-0fa2-11e9-9d01-6a717ee53891.png)
![schermata da 2019-01-03 21-52-44](https://user-images.githubusercontent.com/46358264/50661180-9cb90300-0fa2-11e9-8150-dae4a367a8ac.png)

**Comment by heitec11** [comment]
Try to use at Deconz/Edit "Reset seleceted nodes" or "Delet seleceted nodes". I had the same problem in the past with another sensor.

**Comment by fonzies83** [comment]
Sorry, I try several time to delete or reset the node but always the same, is showed in deconz but not in the phosocon app and home assistant. Any other solution?
Thank you.
