### ISSUE TITLE
Device Integration: Swann One Key Fob Remote

### ISSUE THREAD

**Issue by mysteryan** [dresden-elektronik/deconz-rest-plugin#1085]
Been trying to integrate some Swann devices in deconz.  One of which is a key fob remote classified as an “IAS Ancillary Control Equipment”.  It can be found deeply discounted since it’s only intended to run on Swann’s Home Hub.  Here are some screenshots:
![a8010235-01a7-4821-9dfd-e689c6f4fbd7](https://user-images.githubusercontent.com/15268211/50664059-ade12000-0f60-11e9-8754-b9bb4ad7fa0a.jpeg)
![cc646561-1dec-48e0-8694-10c6ee44ed7f](https://user-images.githubusercontent.com/15268211/50664081-bc2f3c00-0f60-11e9-82ef-bf2a86bfebef.jpeg)
![09ae65d4-d120-4d5a-9c77-bc89f4e30566](https://user-images.githubusercontent.com/15268211/50664082-bc2f3c00-0f60-11e9-8017-f17419129fc0.jpeg)
![f4df905f-eac2-4210-9657-f4f442377379](https://user-images.githubusercontent.com/15268211/50664117-dff28200-0f60-11e9-8e27-5f16c98567a1.jpeg)
It looks like it transmits button events endpoint 01, cluster 0501.  It sends command 0x04 with parameter 0 for first button, cmd 0x00 w/ param 0 for second button, cmd 0x00 w/ param 3 for third button and cmd 0x00 with param 2 for fourth button.

I’ve added to de_web_plugin.cpp with the following:
```
    { VENDOR_NONE, "SWO-KEF1PA", tiMacPrefix }, // SwannOne Key Fob
    { VENDOR_NONE, "SWO-MOS1PA", tiMacPrefix }, // SwannOne Motion Sensor
```
And also added the following to sensor.cpp:

```
static const Sensor::ButtonMap swannSWOKEF1PAMap[] = {
//    mode                          ep    cluster cmd   param button                                       name
//  vendor specific
    // top button
    { Sensor::ModeScenes,           0x01, 0x0501, 0x04, 0,  S_BUTTON_1 + S_BUTTON_ACTION_SHORT_RELEASED, "Panic" },
    // second button
    { Sensor::ModeScenes,           0x01, 0x0501, 0x00, 0,  S_BUTTON_2 + S_BUTTON_ACTION_SHORT_RELEASED,           "Home" },
    // third button
    { Sensor::ModeScenes,           0x01, 0x0501, 0x00, 3,  S_BUTTON_3 + S_BUTTON_ACTION_SHORT_RELEASED,           "Away" },
    // bottom button
    { Sensor::ModeScenes,           0x01, 0x0501, 0x00, 2,  S_BUTTON_4 + S_BUTTON_ACTION_SHORT_RELEASED,  "Night" },

    // end
    { Sensor::ModeNone,             0x00, 0x0000, 0x00, 0,    0,                                           0 }
};
```

And also further down the file:
```
else if (m_manufacturer == QLatin1String("SwannONe"))
        {
            if      (modelid.contains(QLatin1String("KEF1PA")))      { m_buttonMap = swannSWOKEF1PAMap; }
        }
```
It seems to properly report buttonevent 1002 for first button (Panic) and buttonevent 2002 for second button (Home) to rest.  But for the third and fourth buttons, it seems to also report buttonevent 2002 and showing discard sensor state push in the log alongside.

Not sure what I’m doing wrong.  Maybe using improper sensor mode?

**Comment by xhemp** [comment]
Would be nice to re-open this. Any logs/debug, let me know and I can test on my side.
