### ISSUE TITLE
Bulb can only be controled via via group

### ISSUE THREAD

**Issue by andenmad** [dresden-elektronik/deconz-rest-plugin#1088]
hi 
i running version 2.05.54 firmware 262F0500

i have seen my ikea bulbs not able to switch on ore off individual from Phoscon app ore from HA but if i tricker the group from Phoscon it will turn on/off the bulb 

and if i switch it a couple off times it will start working individual agian.

**Comment by manup** [comment]
The issue is there for a while now and is related to startup until the lights have been discovered as truly reachable. This will be improved in next versions.

**Comment by andenmad** [comment]
okay i will test it as when update is avialible :)
