### ISSUE TITLE
Reseller issue

### ISSUE THREAD

**Issue by 00lex** [dresden-elektronik/deconz-rest-plugin#1091]
Hi and sorry to write here, but where can I buy Heiman or Climax devices?
Cant find any store on the internet. 

does anybody know if this the same as the "Heiman | HS1CA carbon monoxide sensor" 
which is supported from deconz? 

https://de.aliexpress.com/item/Wireless-Zigbee-smart-carbon-monoxide-sensor-CO-detector/32728420566.html 

and btw any advice for a good working light sensor? I want go away from my esp. 
aqara and hue sent to rarely for my case. 

thank you

**Comment by MadMonkey87** [comment]
Climax appears to sell only in bigger quantities to business (b2b), not to private users:/

No Idea about Heiman but it appears you can get them at amazon (btw: sounds german, but is chinese in fact😂)
