### ISSUE TITLE
Xiaomi Smart Plug creates extra sensors ZHAPresence, ZHALightLevel

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#1094]
A user of my plugin uses a Xiaomi smart plug (modelid: "lumi.plug", swversion: "02-28-2017")

With the latest updates of deCONZ (Looks like issue #1017 ) extra sensors are created in REST API that are not present on the hardware ((ZHAPresence, ZHALightLevel).
The ZHAPresence is updated then the plug is switched on. After 5 minutes the ZHAPresence is set to off again (internal timer?). This is rather confusing? I think these should not even exist?

Can this be corrected?

Details of the extra sensors that should not be exposed?

ZHAPresence

**************************** Object info *****************************
{
"state": {
"presence": false,
"lastupdated": "2019-01-02T23:28:17"
},
"config": {
"on": true,
"battery": 100,
"duration": 60,
"reachable": true
},
"name": "Presence 27",
"type": "ZHAPresence",
"modelid": "lumi.plug",
"manufacturername": "LUMI",
"swversion": "02-28-2017",
"uniqueid": "00:15:8d:00:02:4f:29:52-01-0406",
"ep": 1,
"etag": "f88e656bbcd7db7c2a54cbd5678bc464"
}
************************* End Object info ***************************

ZHALightLevel

**************************** Object info *****************************
{
"state": {
"daylight": false,
"lastupdated": "2018-12-20T07:46:21",
"lightlevel": 26,
"dark": true,
"lux": 1
},
"config": {
"on": true,
"reachable": false,
"tholddark": 12000,
"tholdoffset": 7000
},
"name": "LightLevel 26",
"type": "ZHALightLevel",
"modelid": "lumi.plug",
"manufacturername": "LUMI",
"swversion": "02-28-2017",
"uniqueid": "00:15:8d:00:02:4f:29:52-01-0400",
"ep": 1,
"etag": "baad6249b2b6f35d7817c927c308149c"
}
************************* End Object info ***************************

Details of the sensor that should be there I think:

**************************** Object info *****************************
{
"type": "Smart plug",
"name": "Light 5",
"modelid": "lumi.plug",
"swversion": "02-28-2017",
"uniqueid": "00:15:8d:00:02:4f:29:52-01",
"manufacturername": "LUMI",
"state": {
"on": false,
"alert": "none",
"reachable": true
},
"etag": "d4f9ab1b6d2a78f4e9076bdec1f18845",
"hascolor": false
}
************************* End Object info ***************************

details of the ZHAConsumption

ZHAConsumption

**************************** Object info *****************************
{
"state": {
"lastupdated": "none"
},
"config": {
"on": true,
"reachable": true
},
"name": "Desumidificador Root",
"type": "ZHAConsumption",
"modelid": "lumi.plug",
"manufacturername": "LUMI",
"swversion": "02-28-2017",
"uniqueid": "00:15:8d:00:02:4f:29:52-03-000c",
"ep": 3,
"etag": "16ffa24ed5017412ffda7f835f70f9c6"
}
************************* End Object info ***************************

details of the ZHAPower
'
ZHAPower

**************************** Object info *****************************
{
"state": {
"lastupdated": "2019-01-03T09:43:45",
"power": 0
},
"config": {
"on": true,
"reachable": true
},
"name": "Power 7",
"type": "ZHAPower",
"modelid": "lumi.plug",
"manufacturername": "LUMI",
"swversion": "02-28-2017",
"uniqueid": "00:15:8d:00:02:4f:29:52-02-000c",
"ep": 2,
"etag": "78a637e48e1edd251b8e04febf9aae1c"
}
************************* End Object info ***************************
`

**Comment by ebaauw** [comment]
Looks like #967.

**Comment by wvuyk** [comment]
The user is using 2.05.52 , so the solution was included already I think? He also removed the sensor through Phoscon already and re-added the sensor. It would be a bit of surprise if the same issue would occur twice?

What can we do more to see what is happening?

**Comment by ebaauw** [comment]
When you remove the sensor, the corresponding records in the database are marked as _deleted_.  When you re-add the device, the records are restored.  You might need to physically delete the records from the database (from the `sensors` table).

**Comment by wvuyk** [comment]
Not really a process that is user friendly I am afraid... why are thos records kept in the database, any Idea? I noticed that before too but cannot think of any reason to do that? 

Maybe we need a process to really delete the record through REST API? A clear command?

**Comment by wvuyk** [comment]
@manup 
Any chance there will be a way to really reset a faulty device as described here? Or at least reset it to basic information, so the old errors do not return after removing and re-adding the device?

**Comment by manup** [comment]
The upcoming version 2.05.55 has many fixes for this very problem, records which are marked as deleted won't be reused. It just causes too many troubles.

**Comment by wvuyk** [comment]
Weird, but the use of 2.05.55 did not solve the issue. The user has deleted the Lumi plug through Phoscon and re-added it. The same extra sensors are created for this plug device. So either the deleted record was still used or the device is really reporting the presence and lightlevel parts?

But he also added two other lumi plugs (same model) earlier (using 2.05.54) and these never created extra sensors?

**Comment by manup** [comment]
Hmm strange, can he please send a backup file to mpi@dresden-elektronik.de (with the invalid resources).

I need to check the descriptors of the plug.

**Comment by manup** [comment]
I've checked the samples from the database and got two different simple descriptors for endpoint 1, both plugs report the same firmware version.

Maybe the various sensor clusters are added by received reports from the plugs?

The only thing we can do here is to skip the related clusters when it is a lumi.plug.

```
00:15:8d:00:02:4f:29:52

device id 27

01 endpoint
0401 profileId (HA)
5100 deviceId (Smart Plug)
01

0a   10 server clusters
0000 Basic
0400 Groups
0300 Identify
0600 On/off
1000 Binary output (ZCLDB Todo)
0500 Scenes
0a00 Time 
0100 Power configuration
0200 Device temperature configuration (ZCLDB Todo)
0604 Occupancy

02
1900 OTA 
0a00 Time


00:15:8d:00:01:da:d4:c4

device id 2

01
0401
5100
01

0c
0000 Basic
0400 Groups
0300 Identify
0600 On/off
1000 Binary output
0500 Scenes
0a00 Time
0100 Power configuration
0200 Device temperature configuration
0204 Temperature
0504 Humidity
0304 Pressure

02  
1900
0a00
```

**Comment by nunoary** [comment]
Hi @wvuyk and @manup 

the last version (V2_05_57) did not solve the problem, for me it still got worse, now they are two with the same problem. I have three lumi.plug and before only one of them created the extra sensors in REST API that are not present on the hardware, now they are two.

Apart from the problem with the first, which still holds, now I have another lumi.plug that has created the three following extra sensors: ZHATemperature-44; ZHAHumidity-45; ZHAPressure-46

I have deleted and re-added several times, with phoscon app, but the sensors are always created.

I will send you my zll file to see if that can help.
Thanks!
Nuno

**Comment by manup** [comment]
Thanks for the info, looking forward to fix this in 2.05.58.

I'll add a broader filter inside addSensor() and also when loading the database.

**Comment by MattL0** [comment]
Still have the alarm sensor created with v59

**Comment by MattL0** [comment]
V. 60 still have the zhaalarm device

**Comment by manup** [comment]
Yes, sorry still an open issue, will be addressed in 2.05.61.

**Comment by MattL0** [comment]
Thank Manup :)

**Comment by MattL0** [comment]
> Yes, sorry still an open issue, will be addressed in 2.05.61.



is the zhaalarm stil present on some xiaomi sensors?

**Comment by MattL0** [comment]
I can confirm the zhaalarm sensors is still present.

**Comment by xbmcnut** [comment]
I'm seeing this in 2.0.66 with Xiaomi smart plugs and the Hassio add-on. deCONZ firmware is 26490700 and Hassio add-on version is 3.1.

I have 8 x Xiaomi smart plugs, and every one has created a rogue sensor called `sensor.consumption_xx` with a state of unknown. The switch and power usage get added correctly.

![image](https://user-images.githubusercontent.com/1492137/62516827-2f43bc80-b87a-11e9-81c6-2c380ecc7fc6.png)
