### ISSUE TITLE
New Tradfri repeater

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#1095]
Hi
Ikea has listed a new Tradfri device that enhances the signal. See here https://m2.ikea.com/de/de/p/tradfri-signalverstaerker-10400408/

Sounds interesting for the price.
The effectiveness has to be evaluated though..

**Comment by 00lex** [comment]
you can use a bulb or a socket for the same price as extender

**Comment by ebaauw** [comment]
I think they created it for their smart blinds.

**Comment by AntiHeld889** [comment]
![unbenannt](https://user-images.githubusercontent.com/4448275/52531791-3c448080-2d1b-11e9-9e4d-40e518867e3d.JPG)
![node](https://user-images.githubusercontent.com/4448275/52531792-3f3f7100-2d1b-11e9-8b04-35d4a337c0f8.JPG)
![basic](https://user-images.githubusercontent.com/4448275/52531793-423a6180-2d1b-11e9-88eb-bae62cf3e401.JPG)
![diag](https://user-images.githubusercontent.com/4448275/52531795-45cde880-2d1b-11e9-9b83-3a341f0b767f.JPG)
![ikea](https://user-images.githubusercontent.com/4448275/52531796-49616f80-2d1b-11e9-8d48-a06bcf6dae3e.JPG)
![green](https://user-images.githubusercontent.com/4448275/52531797-4bc3c980-2d1b-11e9-8173-35f5a176ff9a.JPG)

**Comment by ebaauw** [comment]
Cool.  I don't think there's anything useful to expose through the REST API?

Did you buy this one separately, or did it come with the smart blinds?

**Comment by AntiHeld889** [comment]
I have buy it separately, i don‘t think there‘s anything usefull for Rest API too

**Comment by szoller** [comment]
@AntiHeld889 
How did you pair your tradfri repeater? mines aren't visible in DeConz (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1258 )

**Comment by AntiHeld889** [comment]
Start light or sensor search and nearby reset the repeater

**Comment by szoller** [comment]
I guess with reset you mean pressing the reset-button for 5 sec?

Thank you, i'll try again tonight

**Comment by smingoli** [comment]
Went to Ikea today to take a look at a new desk and saw the repeater..... didn't even know it came out so I forgot the desk and grabbed one of those instead..... Seems to work like a charm...

**Comment by SeraphimSerapis** [comment]
A little late to the party. Is this only for the deconz application or also for the Phoscon web interface? I did the reset, ran both sensor and light search and the repeater does not appear.

I tried with two devices to make sure it's not a hardware defect.

**Comment by ebaauw** [comment]
It does (or rather should) show in the deCONZ GUI, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1258#issuecomment-464484232.  It doesn't have any functionality to to expose, so no REST API resource is created for it.  Consequently, it's invisible to apps (incl. Phoscon).

**Comment by SeraphimSerapis** [comment]
I understand. A number of people -- including myself -- run deCONZ headless. That way I don't have access to the GUI and can't check if it paired correctly. Maybe some of this information could be exposed without a fully fledged implementation in Phoscon?

**Comment by manup** [comment]
Jep, I think it makes sense to show it in the app perhaps with a icon and `reachable` status. I've put it on the todo list.

**Comment by Dinth** [comment]
Im also waiting for it. As @SeraphimSerapis said above, i run deconz in docker in HassIO - so ive got no access to Deconz other than through Phoscon app

**Comment by gekomax** [comment]
Hi, any news here?
I Need to add a Ikea pure reapeter on a conbee device that Is working on Hassio. 

It Is possibile to add the reapeter by mounting the conbee hardware on a pc, using deconz desktop software to add that Ikea reapeter and then export It to the Hassio configuration?
Thanks and Sorry for my english.
Bye

**Comment by fbrinker** [comment]
This would be great.

Any chance to check, on my remote headless instance, if it paired successfully without any indicator in phoscon?

**Comment by Nastras** [comment]
Is it foreseeable when it will be implemented?

**Comment by pattyland** [comment]
@manup I looked through the commits from V2_05_67 and V2_05_69 and I didn't see a hint to the repeater. I think I paired mine successfully but as I don't see any feedback it's hard to tell

**Comment by alundstroem** [comment]
Yeah, I agree with @pattyland, +1 on that (:

**Comment by manup** [comment]
Sorry took a while, it is added now as light and will be part of the next release.
The led on the repeater can be used to identify the device via the `light.state.alert` attribute.

![image](https://user-images.githubusercontent.com/383386/65838075-61641e80-e2ff-11e9-8fa5-c62c79ced4af.png)

**Comment by alundstroem** [comment]
Sounds awesome, will be looking forward to upgrading then (;

**Comment by pattyland** [comment]
@manup Thanks! Do I have to repair the repeater to see it in Phoscon? Or should this work automatically?

If anyone is interested, this is the commit: 627a742de94ad2021133d946c79a013f2b885b08
I would like to be able to implement this for #1899 too :(

**Comment by alundstroem** [comment]
@pattyland, +1 on both questions/suggestions (;

**Comment by manup** [comment]
>@manup Thanks! Do I have to repair the repeater to see it in Phoscon? Or should this work automatically?

Fortunately repairing isn't needed.

* Start the lights search
* Power-cycle the repeater

The repeater should then be added to the list of lights.

**Comment by NedSin** [comment]
Hey together, 
i run Deconz Version 2.05.69 AddOn on HassOS with RaspBee Module.
I`m happy my new motion Sensor and on/off switch from ikea is directly working i just dont get this repeater to work. 
Try recycle the power, press the reset for 5 seconds. I`m not 1m away from the RaspBee Module. 
My english is not the best is this repeater in Phoscon Version 2.05.69 now Supported or do we HASS people has to wait for next release ? 

Thanks for the Answer 

Best Greetings 
Ned

**Comment by manup** [comment]
The repeater will be part of the next version 2.05.70, which should arrive soon.

**Comment by NedSin** [comment]
Thank you for the Info, also for the great Work ...

**Comment by tnowak** [comment]
I'm running version 2.05.67, firmware 264A0700 now and I'm totally unable to add Ikea repeater as a light now (as on screenshot above). I've tried power cycling, reseting (5s), etc.

Do I need to wait for 2.05.70 to get it in Phoscon app?
Any news when 2.05.70 will be released?

**Comment by pattyland** [comment]
@tnowak As @manup wrote 2 comments before yours the repeater will be part of 2.05.70. If you look at the release cycle I guess there will be one in the next 2 weeks.

Tip: If you see the repeater in deCONZ it does its job. The listing in Phoscon doesn't matter

**Comment by tnowak** [comment]
I have Conbee stick in docker on RPi, I suppose deCONZ app is for Win/USB only (?)

**Comment by pattyland** [comment]
@tnowak This is no the right place to ask for general support. I'm running deCONZ in Docker on a RPi too and use VNC to connect to the container and use the App. This has nothing to do with your client system

**Comment by tnowak** [comment]
@pattyland thanks for the tip. I've connected with VNC and found... mess of blocks and lines :) After moving those blocks with mouse I've figured out that it presents a diagram of connections. Ikea reperater is actually there, unfortunately it seems it does not do repeater job (connected only with powered devices). I've bought it to extend range to Aqara_Door_Sensor_2 exclusively and it doesn't :/
![image](https://user-images.githubusercontent.com/54801553/67129544-44848200-f1ff-11e9-98f6-7643750dea02.png)

**Comment by LintHart** [comment]
@tnowak I read somewhere on my initial research into deCONZ that xiaomi sensors always look like they’re coming directly off the main gateway, regardless of where they’re actually routing through. I could be very wrong and have no evidence to support but if I find the thread I’ll link it. 

I’ve just started the migration process myself from a xiaomi gateway to a Conbee 2 stick so I’d be very interested in getting the ikea repeater if it all works together. 

Just to confirm, the graph shows one thing, but does the door sensor happen to function reliably? Do you think that with the distance of the sensor it may actually be routing through a repeater somewhere?

Cheers,

Linton

**Comment by tnowak** [comment]
@LintHart Didn't seem to me. I've noticed no distance extension on that Aqara Door Sensor neither when Ikea Repeater was pluged-in somewhere in between nor when plugged closer the and of ZigBee range. I ditched it for now and moved to another technology with that sensor.

**Comment by LintHart** [comment]
@tnowak how interesting. Perhaps the xiaomi stuff simply does not play well with others (which wouldn’t surprise me in the slightest). Out of interest for my own future, what technology did you move to with that sensor?

**Comment by tnowak** [comment]
@LintHart RF 433Mhz, but let's stop here as this is out of topic of this issue

**Comment by LintHart** [comment]
This may help someone in the future, I plan to try it myself. Basically it seems if you add a repeater after your Xiaomi sensors are set up, they will not automatically attach themselves Like other devices. We need to add the repeaters and then re-pair the sensors in the location they’re to be used so they latch on to the appropriate repeater. 

Advice seems to be repair and rename to previously used to avoid mishaps in things like home assistant

More discussion here:
https://forums.homeseer.com/forum/lighting-primary-technology-plug-ins/lighting-primary-technology-discussion/jowihue-w-vuyk/1300637-zigbee-extender

**Comment by S474N** [comment]
> > @manup Thanks! Do I have to repair the repeater to see it in Phoscon? Or should this work automatically?
> 
> Fortunately repairing isn't needed.
> 
> * Start the lights search
> * Power-cycle the repeater
> 
> The repeater should then be added to the list of lights.

This is only for light or also for Ikea Tradfri Repeater? I cannot add it :(

**Comment by Smanar** [comment]
The ikea repeater haven't a small hole and you need to use a paperclip to press the buton ?

**Comment by S474N** [comment]
> The ikea repeater haven't a small hole and you need to use a paperclip to press the buton ?

Thank you! Solved! :)))

Range extender is in lights :)

**Comment by adrianmihalko** [comment]
Previously I had successfully connected Tradfri Repeater, but after upgrade it is not connected:

<img width="1004" alt="Screenshot 2020-07-11 at 19 07 01" src="https://user-images.githubusercontent.com/733361/87229609-b615e900-c3a9-11ea-96af-c64a4c39bda0.png">

Do I need to re-join every device again after fw upgrade?

**Comment by Smanar** [comment]
No, perhaps it need a power cycle, off/off. But no, router ususaly don't need to be re-included (it s another story for Xiaomi devices)
