### ISSUE TITLE
OSRAM Lightify strips - deConz not storing values

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#1096]
Just installed conbee and updated fw. I have a bunch of older Osram Lightify strips (latest firmware) & the newer Smart+ LEDVANCE A19 bulbs and one Strip.

Problem is that which the color changes occur properly, deConz doesnt seem to store the HUE & SAT settings, only BRI.  So, when I change one in Phoscon, it sets the other to the 'default' - thus, its all wrong.

Confirmed this in 3 ways...
1. Homeseer plugin (JowiHue) I'm using - the plugin writer helped me confirm this after many hours of his time too. The HUE and SAT are correct in the plugin until the next refresh / polling period.
2. Hue Essentials app will wipe the HUE & SAT settings for the lights after its polling period.
3. Phoscon web ui also exhibits the same problem

Repro example:
in Phoscon, or any other app... Set HUE & SAT & BRI.
Wait until the refresh or click on a different light and back to that light in Phoscon - the GUI will show the HUE & SAT back to 0 (slider at the very bottom) while BRI slider will not have changed (thus, still correct)

so, when I go to set the HUE, deConz things SAT is at 0 and HUE gets set proper, and SAT is also set back to 0 on the light.  (and vice versa, if I set SAT and not HUE)

see screenshots

I have propro'd this on several lights and even tried removing and re-adding to the Conbee. Same
![capture1](https://user-images.githubusercontent.com/1626802/50743633-e9d1ea80-11d7-11e9-84a3-30496e17f9d3.PNG)
![capture2](https://user-images.githubusercontent.com/1626802/50743634-e9d1ea80-11d7-11e9-86a2-910bff599713.PNG)

**Comment by manup** [comment]
Hard to tell, why the hue/sat isn't set correctly. It works for all other brands. I have a OSRAM Flex RGBW strip here, will check later with the sniffer if I can find something causing this.

**Comment by manup** [comment]
Notes while investigating. Right after join and no interaction the device reports:
* ct mode with color temperature 370
* hue and saturation both 0
* xy coordinates matching the ct value

```
{
    "ctmax": 666,
    "ctmin": 125,
    "etag": "450dcbb2e45c94c5449681e59a2653f8",
    "hascolor": true,
    "manufacturername": "OSRAM",
    "modelid": "Flex RGBW",
    "name": "OSRAM Flex",
    "state": {
        "alert": "none",
        "bri": 254,
        "colormode": "ct",
        "ct": 370,
        "effect": "none",
        "hue": 0,
        "on": true,
        "reachable": true,
        "sat": 0,
        "xy": [
            0.382037,
            0.378391
        ]
    },
    "swversion": "V1.05.10",
    "type": "Extended color light",
    "uniqueid": "7c:b0:3e:aa:00:00:10:de-03"
}
```

**Comment by manup** [comment]
Setting color to green in Phoscon App:

* deCONZ sends xy coordinates for this color
* color mode changes correctly to xy
* reading the attributes manually yields correct values
* hue and saturation are also updated properly

```
{
    "ctmax": 666,
    "ctmin": 125,
    "etag": "92b12a66791265fd53a5349e29f33d20",
    "hascolor": true,
    "manufacturername": "OSRAM",
    "modelid": "Flex RGBW",
    "name": "OSRAM Flex",
    "state": {
        "alert": "none",
        "bri": 254,
        "colormode": "xy",
        "ct": 370,
        "effect": "none",
        "hue": 21504,
        "on": true,
        "reachable": true,
        "sat": 254,
        "xy": [
            0.130409,
            0.643377
        ]
    },
    "swversion": "V1.05.10",
    "type": "Extended color light",
    "uniqueid": "7c:b0:3e:aa:00:00:10:de-03"
}
```

**Comment by manup** [comment]
Tried a few other colors:
* All are set as good as the light is able to set them
* The xy colors and hue and saturation are reported (or read)
* Saturation is often a bit off but that's likely due xy > hue sat conversation

All in all it seems to work here and is also synchronized in the REST-API as well as Phoscon App.

Note I'am using the European version of Osram Flex RGBW strip, firmware version in OTA cluster is 0x01020510.

**Comment by manup** [comment]
Can you please provide the REST-API output of your lights?

**Comment by Ltek** [comment]
Please let me know where to get the info you want. Capture the REST output, OTA Cluster version, etc? I dont see a debug log or a way to turn on logging?

lights I have...
OSRAM LIGHTIFY FLEX OUTDOOR RGBW Version 01020492  (3 in use, many more in boxes)
LEDVANCE A19 RGBW Version 00102411  (1 in use)
LEDVANCE FLEX RGBW Version 00102055  (1 in use)
OSRAM LIGHTIFY Flex RGBW Version 01020492 (1 in use, many more in boxes)

**Comment by wvuyk** [comment]
@manup 
Here is one sample of a ledstrip not reporting well in Phoscon and in my plugin:

```
 LEDVANCE Smart+ A19 bulb

{
"type": "Color dimmable light",
"name": "Dresser Colors",
"modelid": "A19 RGBW",
"swversion": "00102411",
"uniqueid": "f0:d1:b8:00:00:01:46:40-01",
"manufacturername": "LEDVANCE",
"state": {
"on": false,
"bri": 100,
"hue": 6966,
"sat": 221,
"xy": [
0.415892,
0.313378
],
"alert": "none",
"effect": "none",
"colormode": "ct",
"reachable": false
},
"etag": "535873cf65e88ea2b8d266ff2a521ff0",
"hascolor": true
}

```
Notic the colormode is showing ct, but there is no ct value produced? Hue and  Sat are reported here, but with the next polling cycle they seem to reset to 0's . This also shows on the Homeseer interface.
I will like @ebaauw  suggests try to switch to xy control only to see if things change then. But I think the missing ct value here is not really logical?

**Comment by Ltek** [comment]
All my Lights are US versions

**Comment by manup** [comment]
Interesting the related attribute would be added if it can be queried.

@Ltek can you please read the color cluster attributes in deCONZ and show what the colr capabilities field reports.

![image](https://user-images.githubusercontent.com/383386/50900383-4f5eea80-1415-11e9-8bb7-355c65f23570.png)

If the device reports color mode `ct` and not supporting color temperature it would cause problems for sure.

**Comment by Ltek** [comment]
screenshot from properties.
![osram_properties](https://user-images.githubusercontent.com/1626802/50909548-5243e600-13e9-11e9-92d6-42ae1b910fef.PNG)

Cluster info cant be easily screenshot (non-sizable window) and looks like I cant copy the text data. Would be helpful if you provided a way to export that data...
![osram_attributes](https://user-images.githubusercontent.com/1626802/50909880-f4fc6480-13e9-11e9-92d8-fe376c9902ae.PNG)

**Comment by manup** [comment]
Thanks, the screenshots shows this is a HA light and therefore doesn't support the Color capabilities.

(The European versions are ZLL)

We can use color mode (0x0008), looks correct. I think we kind of expect ended color mode 0x4001 to exist, which might cause some issues here.

I'll check the code to handle non-existence of these attributes.

**Comment by manup** [comment]
It's a different problem, the Ikea color bulbs don't support hue saturation color commands. Otherwise they are ZLL lights and support the above attributes.

**Comment by Ltek** [comment]
Gotcha.
Let me know when you have some beta code ready  - I'd love to test so I can get these lights working. :)

**Comment by Ltek** [comment]
Tested .54  --- issue not fixed.  I can literally watch the XY values set when using Phoscon, then change in 1 or 2 seconds.  Posted a video showing the issue

https://vimeo.com/user93918128/review/311377188/fee7acc365

**Comment by manup** [comment]
>Tested .54 --- issue not fixed

It's 2.05.55, have you installed this?

**Comment by Ltek** [comment]
Test .55  (sorry about typo in prior post, corrected).. Check out the video I posted.  I didnt see any debug log feature - maybe a debug log would help?

**Comment by manup** [comment]
Checked the video this is actually how it works :) when you use the sliders in the Phoscon App deCONZ will send xy color commands.

When you scroll down the attribute list, the color mode should also indicate xy. Note only one color mode can be active at a given time.

**Comment by Ltek** [comment]
> 
> 
> Checked the video this is actually how it works :) when you use the sliders in the Phoscon App deCONZ will send xy color commands.
> 
> When you scroll down the attribute list, the color mode should also indicate xy. Note only one color mode can be active at a given time.

... you are saying that Phoscon is showing the Wrong Settings, by design?

When using Phoscon sliders, they properly change the physical color

Here's the test...
1. move the sliders - at the same time, the deConz XY values change (expected result)
2. once the color is set in the sliders, the deConz XY values stop changing (expected result)
3. one to two seconds later, the deConz XY values CHANGE (not expected, since on the previous step, they already stopped changing) while the physical light stays (expected result)
4. when you manually refresh Phoscon (or wait until it refreshes automatically), the sliders MOVE from where you set them - thus NOT the Hue and Sat you set them at  (not expected)

to me, # 3 & 4 are related... and still show a bug exists where Hue/Sat values are not retained.

It would help greatly if there was a Debug Log AND if Phoson was useful and showed the Hue/Sat/Bright values - current and as the sliders are changing.

We need an easy, visual, way to validate that the colors are set to what we intended to set them to - and that they stay that way.  Phoson doesnt give us that - it should.

**Comment by manup** [comment]
>... you are saying that Phoscon is showing the Wrong Settings, by design?
>When using Phoscon sliders, they properly change the physical color - but a second later, the sliders are all wrong, deConz values change on their own, physical light color stays the same

The video only shows that the sliders are set manually, not that they move on their own, or do I miss something?

Can you confirm that the color mode in the Attribute panel is xy all the time, while using the sliders?

To enable the debug output you can start deCONZ as follows:
```
deCONZ --dbg-info=1 --dbg-aps=2 --dbg-zcl=2 --http-port=80 > log.txt
```

**Comment by Ltek** [comment]
> 
> 
> > ... you are saying that Phoscon is showing the Wrong Settings, by design?
> > When using Phoscon sliders, they properly change the physical color - but a second later, the sliders are all wrong, deConz values change on their own, physical light color stays the same
> 
> The video only shows that the sliders are set manually, not that they move on their own, or do I miss something?
> 
> Can you confirm that the color mode in the Attribute panel is xy all the time, while using the sliders?
> 
> To enable the debug output you can start deCONZ as follows:
> 
> ```
> deCONZ --dbg-info=1 --dbg-aps=2 --dbg-zcl=2 --http-port=80 > log.txt
> ```

here's the correct video showing the refreshes... https://ufile.io/e1kbj

that command doesnt output a debug log. here's exactly what I'm using...

"C:\Program Files (x86)\deCONZ\bin\deCONZ.exe" --dbg-info=1 --dbg-aps=2 --dbg-zcl=2 --http-port=8080 > C:\deConz_debug.txt

also tried... 

"C:\Program Files (x86)\deCONZ\bin\deCONZ.exe" --dbg-info=1 --dbg-aps=2 --dbg-zcl=2 --http-port=8080 > log.txt

**Comment by Ltek** [comment]
Looks like this might be fixed as it seems to be working in Phoscon - but since Phoscon doesnt show any actual Hue, Sat, or Bri values; I cannot know for sure. 

I need to do some more testing and report back after Homeseer Plugin and Hue Essentials is updated to see if the values are being passed properly.

**Comment by Ltek** [comment]
> In that case @Ltek wait for the next beta of my plugin as this one should better catch the xy setting and convert it to the hue/sat/bri settings. it will no change Phoscon, but it is a work around for the plugin.
> 
> Curious question, but did the json on the LEDVANCE Smart+ A19 bulb change in a way that CT is shown now?

@wvuyk ... any ETA on releasing the new beta for JowiHue?

**Comment by wvuyk** [comment]
@Ltek 
If I remember right you have already an answer on the JowiHue forum on this. No need to do this here.

**Comment by Ltek** [comment]
@manup 

A debug/trace logging in deConz would have really helped cut the testing time. Being able to see the values being set.
Which brings me to shameless begging. PLEASE, PLEASE, PLEASE add a way to input new & view existing values for RGB Hex, XY, SAT, BRI -- on screen in Phoscon.
... This would have also cut testing time down in half.  I'm guessing if the apps are correctly reading/displaying the info by looking at the colors rendered onscreen (PC & Android). With Phoscon slider its impossible to know what the color looks like (slider is mainly useless to setting anything accurately without seeing the values.

Testing Results - I think deConz is working now. I will need more time to test another light version but for the 2 I test, its working.  (except JowiHue, which is not working)

Tested:
OSRAM LIGHTIFY FLEX OUTDOOR RGBW - NA Version 01020492 
LEDVANCE A19 RGBW - NA Version 00102411

Phoscon & Hue Essentials used to change values; Results...

* Phoscon: Color/Sat changes ARE retained. Slider do move on refresh but not to the Top like they did before. I suspect this is the inaccuracy of the sliders/values onscreen. 

* Hue Essentials: Looks to be reflecting the correct values! Not 100% sure since H.E. doesnt show XY values or RGB Hex values. 

* JowiHue: Looks to be reflrecting the correct value. Not 100% sure since JowiHue shows the RGB Hex value (and not XY), AND we don't know what the RGB Hex value is in Phoscon.


JowiHue to change values; Results...

* JowiHue shows incorrect value. Its obvious when I set the LED to Red and JH Hue changes immediately to Blue (002AAA), and never corrects itself even after a minute or two. What's funny, is if I enter #002AAA into Hue Essentials (the value JH shows as 'red')... LEDs change to correct color then JH changes to #008B15 (green)! Something Very wrong with how JH is reading or converting values.

* Phoscon & Hue Essentials - work properly, show correct values immediately.

**Comment by manup** [comment]
>Which brings me to shameless begging. PLEASE, PLEASE, PLEASE add a way to input new & view existing values for RGB Hex, XY, SAT, BRI -- on screen in Phoscon.

I understand this would help debugging but this is not the use case for the Phoscon App. Our designer would through a cup of coffee against me ;)

Note also RGB values have little to no value to represent colors of lights.

However there are apps like all4hue which provide deeper insight in current values, or even using REST-API clients like Postman to check raw data might be useful here.

>Testing Results - I think deConz is working now. I will need more time to test another light version but for the 2 I test, its working. 

Can this issue be closed now?
