### ISSUE TITLE
Phoscon App changed values in timing

### ISSUE THREAD

**Issue by Ronoon** [dresden-elektronik/deconz-rest-plugin#1099]
Since the update to  .. 54 the timing for light Control has changed.
Before i could use 1 or 2 min for Lights off now it is up to min 3 minutes on Raspberry 
an the odd it is on PC up to 4 minutes :-(.
Looks like the window scaling fails to show the uppervalues in the box because off the screen values.
Maybe you should configure the timing values as input values and not as defined boxes ( or maybe the boxes should be scrolling to the upper values).

Screenshot from PC values:

 
![phoscon](https://user-images.githubusercontent.com/41126336/50789332-37278800-12bc-11e9-97c7-d4fa74c78094.jpg)

**Comment by manup** [comment]
>Looks like the window scaling fails to show the uppervalues in the box because off the screen values.

Good catch, seems indeed to be the problem. Looking forward to fix this in 2.05.55.

**Comment by Ronoon** [comment]
Well thx

**Comment by Ronoon** [comment]
Well we are at .57 and this issue hasn´t been fixed. 
Maybe it´s just forgotten to fix due to the workload you have there.

**Comment by manup** [comment]
It was already fixed in the last version. Maybe your Browser cache hasn't updated yet.

You can force update the cache with a random query string in the url bar like:

    http://<your-gateway-ip-address>/pwa/group-sensors.html?12345

![image](https://user-images.githubusercontent.com/383386/51561794-7216e780-1e88-11e9-963b-1f6efec10156.png)

**Comment by Ronoon** [comment]
Yep 
had to reinstall the complete precompiled version to run it the you showed.
The simple cache cleaning wouldn´t help with this issue.
But thx for the reply, it is really appreciated
