### ISSUE TITLE
Device integration Bitron AV2010/21B window sensor with ext.contact

### ISSUE THREAD

**Issue by Ronoon** [dresden-elektronik/deconz-rest-plugin#1100]
![bitron5](https://user-images.githubusercontent.com/41126336/50790415-288ea000-12bf-11e9-8bad-5b549708fd73.png)
Could you pls integrate the window sensor 

![bitron 1](https://user-images.githubusercontent.com/41126336/50790140-64753580-12be-11e9-926b-94439517ef4e.png)
![bitron2](https://user-images.githubusercontent.com/41126336/50790225-a605e080-12be-11e9-8219-bed4f4d056be.png)
![bitron3](https://user-images.githubusercontent.com/41126336/50790320-ed8c6c80-12be-11e9-84f2-3f105396f07b.png)
![bitron4](https://user-images.githubusercontent.com/41126336/50790324-efeec680-12be-11e9-8782-c80b9b0c179f.png)

**Comment by Ronoon** [comment]
Integration is about 50% done cause only the "Namespace" is recognized but there is something missing in this part or somewhere else:

                case IAS_ZONE_CLUSTER_ID:
                {
                    if (modelId.startsWith(QLatin1String("CO_")))                     // Heiman CO sensor
                    {
                        fpCarbonMonoxideSensor.inClusters.push_back(ci->id());
                    }
                    else if (modelId.startsWith(QLatin1String("DOOR_")))              // **Heiman door/window sensor**
                    {
                        fpOpenCloseSensor.inClusters.push_back(ci->id());
                    }
                    else if (modelId.startsWith(QLatin1String("PIR_")) ||             // Heiman motion sensor
                             modelId.startsWith(QLatin1String("902010/22")))          // Bitron motion sensor
                    {
                        fpPresenceSensor.inClusters.push_back(ci->id());
                    }
                    else if (modelId.startsWith(QLatin1String("GAS_")) ||             // Heiman gas sensor
                             modelId.startsWith(QLatin1String("SMOK_")) ||            // Heiman fire sensor
                             modelId.startsWith(QLatin1String("902010/24")) ||        // Bitron smoke detector
                             modelId.startsWith(QLatin1String("lumi.sensor_smoke")))  // Xiaomi Mi smoke sensor


Missing are the integration for 902010/21 +/32

In the commit of Ma Ca was this originally integratet but there is also nothing anymore

**Comment by Ronoon** [comment]
Just got the including done so the 902010/21 will show up in the API and Tada its working
Just added the line for the 902010/21 into the de_web_plugin.cpp as shown below:


case IAS_ZONE_CLUSTER_ID:
                {
                    if (modelId.startsWith(QLatin1String("CO_")))                     // Heiman CO sensor
                    {
                        fpCarbonMonoxideSensor.inClusters.push_back(ci->id());
                    }
                    else if (modelId.startsWith(QLatin1String("DOOR_")) ||	      // Heiman door/window sensor
			     modelId.startsWith(QLatin1String("902010/21")))          // Bitron window sensor
                    {
                        fpOpenCloseSensor.inClusters.push_back(ci->id());
                    }
                    else if (modelId.startsWith(QLatin1String("PIR_")) ||             // Heiman motion sensor
                             modelId.startsWith(QLatin1String("902010/22")))          // Bitron motion sensor

**Comment by manup** [comment]
Thanks for figuring this out, I've added this to the repository.

**Comment by Ronoon** [comment]
Well thx for the integration of this sensor, maybe you could integrate it into the visible part of Phoscon so that it could be used through the app.
Also the is this little issue with the timing problem about the sliders in the app.....

**Comment by manup** [comment]
The sensor should be visible in 2.05.58, can you please check if it works?
