### ISSUE TITLE
Deconz tries to open on port 80, conflicts with web server.

### ISSUE THREAD

**Issue by Andreas-Pedersen** [dresden-elektronik/deconz-rest-plugin#1101]
Windows 10 Pro
Installed Deconz 2.0.54, and tried to open webapp and Phoscon App but 
since i already have a webserver running on port 80(Homeseer), this doesnt work.
Are there any workarounds?
If i shutdown Homeseer, then the login works, but I need the port 80 for HS.

-Andreas
![deconz1](https://user-images.githubusercontent.com/33702554/50791873-68f01d00-12c3-11e9-8995-d4b7484d49b5.PNG)
![deconz2](https://user-images.githubusercontent.com/33702554/50791876-6ab9e080-12c3-11e9-824f-d34d1d534f36.PNG)

**Comment by Smanar** [comment]
There is a command line to change server port 
`--http-port=<port>`

But I haven't tried it on windows.

**Comment by Andreas-Pedersen** [comment]
Worked perfect! Changed the Deconz shortcut. Added the 
![deconz4](https://user-images.githubusercontent.com/33702554/50794081-7066f480-12ca-11e9-9e1d-09da9ae9c7f6.PNG)

> --http-port=8080

**Comment by pillemats** [comment]
works not for me... any other solution ?
