### ISSUE TITLE
Phoscon app - finds indefinate GW's

### ISSUE THREAD

**Issue by Andreas-Pedersen** [dresden-elektronik/deconz-rest-plugin#1102]
Why does this happen?

![deconz3](https://user-images.githubusercontent.com/33702554/50794157-a60bdd80-12ca-11e9-9cfb-0f8ec592d236.PNG)

**Comment by johol** [comment]
After updating to 2.05.54 I have the same problem and can not log in.

**Comment by johol** [comment]
Downgrading to 2.05.52 fixed the problem for me.

**Comment by johol** [comment]
Today I did a update to 2.05.60. The problem still exists.

**Comment by johol** [comment]
It seems to be a problem with the bridgeid but I found a ugly workaround.
Use sqlite3 command to find your bridgeid
sqlite3 zll.db "select value from config2 where key=\"bridgeid\""
00212EFFFF00B79A

After this put the id in the login.html page

--- login.html.orig     2019-03-15 12:56:02.712971203 +0100
+++ login.html  2019-03-15 14:11:17.158575108 +0100
@@ -267,6 +267,9 @@
                     var rsp = xhr.response;
                     rsp.id = rsp.bridgeid;
                     rsp.ip = url.hostname;
+                    if (typeof rsp.id==="undefined") {
+                         rsp.id = '00212EFFFF00B79A';
+                     }
                     if (url.port)
                         rsp.port = url.port;
                     rsp.reachable = true;

**Comment by johol** [comment]
Today I tried some older git commits. With commit e7cb33f0f61d801f33400cb0f037cb06a7060427 title "Add authorisation status to request and move rest handlers back to rest_configuration."  the problem started.

**Comment by johol** [comment]
The problem still exists in 2.05.66. Before commit e7cb33f0f61d801f33400cb0f037cb06a7060427 login is working as expected.
