### ISSUE TITLE
Motiondetection Sensor from Aqara

### ISSUE THREAD

**Issue by kugelkopf123** [dresden-elektronik/deconz-rest-plugin#1103]
Hey! 

I have 4 Motion Detection Sensors from Aqara. The type that can detect the light (Lux),too.

Since the last update to the latest version 2.05.54 the Motionsensors no longer work correctly. I use them in combination with the Rasbee. It used to be that they detected a movement every 60 seconds. Now, after detecting the first movement, stay in Motion Detect status for 12 sec. After these 12 seconds, the sensors can detect another movement. Again the status "detect" remains for 12 sec. Now you have to wait 90sec until the next movement is detected. Then it starts again from the beginning. 2x short 1x long.
You can manipulate this value a little bit via Phoscon: EditGoup / Sensor control / add rule and than play with these values and add the sensors to this rule. In ioBroker / objects, the value "Duration" changes if you do so.

It would be great if these values could best be changed via ioBroker itself. So the value: Trigger after Xsec and the value: Arm for new detection Xsec.

**Comment by kugelkopf123** [comment]
As I just discovered, they will not be added correctly in the new version. I deleted My Motionsensors and wanted to reconnect them. Now they are only recognized as "LightLevel".

**Comment by manup** [comment]
I've seen this with the Xiaomi cube, looks like some times not all resources are created in one run. Until this is fixed please try the following workaround:

* Start sensor search again
* **Don't** delete the sensor
* Reset the sensor by pressing the button until it blinks and starts to join the network again

This should hopefully create the missing presence resource.

**Comment by kugelkopf123** [comment]
No. Thats not the Problem. I have all the resources... I tried it anyway but its stil the same. iobroker "Duration" is a readonly state. You only see that its changing if you manipulate it via: Phoscon: EditGoup / Sensor control / add rule and than play with these values and add the sensors to this rule. As i already mentioned in my first post.
There must be other mistakes with the readings. I've tried it many times. Please grap one and try it by yourself ten times in a row. You will see the problem. There are differences between: Keep in Motion and let it once detect a Motion and wait. 
It looks like several timers are being started. Because if you stay in Motion over a longer period then changing the presence state true takes longer. And you can see that he obviously recognizes the movement, because the Lux values are changing, but the "presence state" not.

Incidentally, I would appreciate it if you could set the time to recognize a Motion and also the time that the value "presence" is "true".

**Comment by kugelkopf123** [comment]
I logged the messages in ioBroker and marked them in color. Green: Presence true, orange: false, dark blue: Lux change.

The entire time was movement in front of the sensor. That you can tell by the fact that the Lux value has changed.
ioBroker Duration Value: 12 (seconds?)

<img width="1647" alt="bildschirmfoto 2019-01-09 um 18 40 59" src="https://user-images.githubusercontent.com/45996965/50917593-374f9100-143e-11e9-8329-9f9b2ac811e2.png">
<img width="1651" alt="bildschirmfoto 2019-01-09 um 18 41 13" src="https://user-images.githubusercontent.com/45996965/50917595-374f9100-143e-11e9-9d00-2f1149e9afc6.png">
<img width="1670" alt="bildschirmfoto 2019-01-09 um 18 41 27" src="https://user-images.githubusercontent.com/45996965/50917596-374f9100-143e-11e9-9240-f5c558b9fb0c.png">

> Just to confirm I understand correctly: the presence is false albeit lux level changes?

Yes, as you can see in my Photos.
Hope this helps =)

**Comment by manup** [comment]
Interesting, looks like the `config.duration` is rather small – 10 seconds?

It shouldn't be less than 60 better 90 seconds. Once the sensor leaves the setup mode the time between two presence signals is no less than 60 seconds.

Still I wonder why the lightlevel values are updated that often.

Can you please provide the REST-API output for the sensor? I thought I've added code in the past to check for a proper value here.

**Comment by kugelkopf123** [comment]
> Can you please provide the REST-API output for the sensor? I thought I've added code in the past to check for a proper value here.

I dont know how to do this. Perhaps you can tell it me?

**Comment by manup** [comment]
I've checked the code, the current Phoscon App should configure the Xiaomi Sensor to duration to 90  if it is lower. This is only done if an existing sensor control is changed or a new one is created.

```
                    // Xiaomi sensor min duration must be 60 seconds
                    if (modelid.indexOf('lumi.sensor_motion') !== -1) {
                        if (duration < 90)
                            config['duration'] = 90;
                    } else if (uniqueid.indexOf('-0500') !== -1) {
                        if (duration < 90)
                            config['duration'] = 90;
                    }
```

> It would be great if you could adjust the different values by yourself.

This is only possible via REST-API.

> 90 seconds are in my case too long.

90 was chosen for this particular sensor since 60 is the absolut minimum for this sensor and we've seen that sometimes not even 60 is enough, so the 30 seconds are added as sanity.

**Comment by sveip** [comment]
My Xiaomi sensors also does not work as they should in 54. They stay detected forever, and some does not detect at all. All of them are added in a previous version, so should not be related to adding. Any hints @manup?

**Comment by manup** [comment]
It might be the same problem as here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/672

Hence the hourly reports set them always to `true` (given this is the Xiaomi Mi version), should be fixed in 2.05.55.

**Comment by kugelkopf123** [comment]
> This is only possible via REST-API. 
How?

> 90 was chosen for this particular sensor since 60 is the absolut minimum for this sensor and we've seen that sometimes not even 60 is enough, so the 30 seconds are added as sanity.
Why?
Why not 65sec ? 
And how does it work precisely? The Sensor give a short Signal that it is activated > deconz recogniced it and set a timer from X sec that set the presence value to true and back to false after the timer is over? > The next time the sensor can trigger again is after 60 sec. from the time of the last trigger event? Or does the sensor stay true for the time there is Motion in front of him? 

I totally reinstalled my Raspberry pi3 yesterday night. I didnt had the time to test it, but it seams to be better now. i will check it and report it here...

**Comment by manup** [comment]
>Why not 65sec ?

This was just chosen by trial and error, 5 seconds was not enough 30 seconds provided a higher success rate.

>Or does the sensor stay true for the time there is Motion in front of him?

The timeout will be reset every time a presence signal  is received. So the `false` is set only 90 seconds after the last signal is received.

**Comment by manup** [comment]
>The status hasn't yet been set back to Not Detected.
I have this issue across multiple motion sensors (Mijia version).

This will be fixed in deCONZ 2.05.55.

**Comment by chimpy** [comment]
> > The status hasn't yet been set back to Not Detected.
> > I have this issue across multiple motion sensors (Mijia version).
> 
> This will be fixed in deCONZ 2.05.55.

Thanks! For the moment I'm back to .52 and everything seems to be fine.

**Comment by xhemp** [comment]
I have the same issue, just downgraded to 2.02.52 and it is working fine again

**Comment by xhemp** [comment]
All good here, working as expected. Thanks @manup.

**Comment by manup** [comment]
Thanks for the feedback glad that it works.
Closing the issue for now.
