### ISSUE TITLE
Hint for integrating things

### ISSUE THREAD

**Issue by 00lex** [dresden-elektronik/deconz-rest-plugin#1106]
Hi, sry if im wrong. Im just a user. 
But do you know this site or rather the attached documentation for every certified device? 
does this help when it comes to integrating things to deconz?

https://www.zigbee.org/zigbee-products-2/#zigbeecertifiedproducts/?view_30_search=aqara&view_30_page=1

**Comment by manup** [comment]
@00lex the site helps to get an overview of existing and often upcoming devices, but for integration access to the physical devices is most helpful.
