### ISSUE TITLE
Question: reader/sensor for NFC/RFID

### ISSUE THREAD

**Issue by pergolafabio** [dresden-elektronik/deconz-rest-plugin#1108]
just a question , is there also some kind of NFC/RFID device, thats compatible with deconz? so it can be used with an NFC / RFID badge or something? for example to arm / disarm an alarm?

thnx

**Comment by manup** [comment]
No deCONZ only supports Zigbee devices. The only way to integrate other devices is via REST-API und create CLIP sensors.

**Comment by pergolafabio** [comment]
maybe there is a deconz/zigbee device thats is reading rfid/nfc badges? 
something like a motion sensor, but then a sensor for NFC / RFUD
