### ISSUE TITLE
rest api incorrectly returns success for setting bri together with on: false

### ISSUE THREAD

**Issue by ErnstEeldert** [dresden-elektronik/deconz-rest-plugin#1110]
If I combine on=false and bri=n in a single state update on a light, the REST api returns success for the bri=n state update, but in reality, it gets ignored. Like so:

`$ PUT /lights/47/state '{ "on": true, "bri": 1 }' && GET /lights/47 | jq .`
```json
[{"success":{"/lights/47/state/on":true}},{"success":{"/lights/47/state/bri":1}}]
{
  "ctmax": 454,
  "ctmin": 250,
  "etag": "7f7bb8686764ebf2ae872925d3b8cfcc",
  "hascolor": true,
  "manufacturername": "IKEA of Sweden",
  "modelid": "TRADFRI bulb E27 WS opal 980lm",
  "name": "Kantoor Dressoir",
  "state": {
    "alert": "none",
    "bri": 1,
    "colormode": "ct",
    "ct": 454,
    "on": true,
    "reachable": true
  },
  "swversion": "1.2.217",
  "type": "Color temperature light",
  "uniqueid": "00:0b:57:ff:fe:f3:56:3c-01"
}
```
`$ PUT /lights/47/state '{ "on": false, "bri": 255 }' && GET /lights/47 | jq .`
```json
[{"success":{"/lights/47/state/on":false}},{"success":{"/lights/47/state/bri":255}}]
{
  "ctmax": 454,
  "ctmin": 250,
  "etag": "2383e8b5dc4e9b9d5bbffa9b5705ee49",
  "hascolor": true,
  "manufacturername": "IKEA of Sweden",
  "modelid": "TRADFRI bulb E27 WS opal 980lm",
  "name": "Kantoor Dressoir",
  "state": {
    "alert": "none",
    "bri": 0,
    "colormode": "ct",
    "ct": 454,
    "on": false,
    "reachable": true
  },
  "swversion": "1.2.217",
  "type": "Color temperature light",
  "uniqueid": "00:0b:57:ff:fe:f3:56:3c-01"
}
```

I understand bri gets overwritten to 0 by the on=false state, but would expect the REST API in this case to return an error for the provided bri=n state.

**Comment by olemr** [comment]
I had the same (naive?) experience my first time around with my Tradfri lights.
I am controlling the lights from openHab and found I had to insert a 500ms delay between 'on and 'bri'

Putting more Tradfri awareness into the API has been discussed before if you search the issues.
