### ISSUE TITLE
Joining of new Remote Controls and Motion sensors not working with .54 <edited>

### ISSUE THREAD

**Issue by tubalainen** [dresden-elektronik/deconz-rest-plugin#1112]
Hello!

Long story short, I have had quite some issues with my IKEA Trådfri setup. So I decided to reset all and start fresh. Oh my what an endeavor to undertake.

I have just updated to .54 after having problems joining IKEA Trådfri lights to deconz. All lights are now joined and works fine. (Thanks for the fixes in the code!)

Now I am trying to add my remaining "normal round" IKEA remote controls and my IKEA motion sensors to the system with no luck. They were very easy to join in previous versions.

This is what I get in the log:
```
19:17:14:255 Current channel 15
19:17:17:188 send permit join, duration: 0
19:17:18:188 send permit join, duration: 59
19:17:22:188 send permit join, duration: 0
19:17:24:188 send permit join, duration: 59
19:17:27:187 send permit join, duration: 0
19:17:28:188 send permit join, duration: 59
19:17:31:716 0xAA24 nwk changed to 0x7E79
19:17:31:716 device announce 0xD0CF5EFFFE0809FD (0x7E79) mac capabilities 0x80
19:17:31:716 set fast probe address to 0xD0CF5EFFFE0809FD (0x7E79)
19:17:31:716 device announce 0xD0CF5EFFFE0809FD (0x7E79) mac capabilities 0x80
19:17:31:716 set fast probe address to 0xD0CF5EFFFE0809FD (0x7E79)
19:17:31:811 [1] get node descriptor for 0xd0cf5efffe0809fd
19:17:32:188 send permit join, duration: 0
19:17:33:941 ZCL attribute report 0x90FD9FFFFE0F12AA for cluster 0x0006, ep 0x01
19:17:34:188 send permit join, duration: 59
19:17:34:789 ZCL attribute report 0x000B57FFFEE838C0 for cluster 0x0006, ep 0x01
19:17:36:966 DB save zll database items 0x00000800
19:17:36:976 DB saved in 10 ms
19:17:36:976 don't close database yet, keep open for 900 seconds

```

![image](https://user-images.githubusercontent.com/26795429/50853809-a1573000-1383-11e9-9fe1-33f2ddf58873.png)

**Comment by tubalainen** [comment]
Another update, can confirm that I have got the same issues with joing a Philips Dimmer Switch as well in .54.
```
08:58:32:188 send permit join, duration: 59
08:58:37:188 send permit join, duration: 0
08:58:38:188 send permit join, duration: 59
08:58:39:329 Beacon src: 0x2C44 ch: 15 updateId: 0
08:58:39:336 Beacon src: 0x16B4 ch: 15 updateId: 0
08:58:39:377 Beacon src: 0x3B97 ch: 15 updateId: 0
08:58:39:393 Beacon src: 0xD010 ch: 15 updateId: 0
08:58:39:408 Beacon src: 0x6AD6 ch: 15 updateId: 0
08:58:40:625 0x92F4 nwk changed to 0x0AB2
08:58:40:625 device announce 0x001788011048AB4A (0x0AB2) mac capabilities 0x80
08:58:40:625 set fast probe address to 0x001788011048AB4A (0x0AB2)
08:58:40:625 device announce 0x001788011048AB4A (0x0AB2) mac capabilities 0x80
08:58:40:625 set fast probe address to 0x001788011048AB4A (0x0AB2)
08:58:40:720 [1] get node descriptor for 0x001788011048ab4a
08:58:42:188 send permit join, duration: 0
08:58:43:250 Current channel 15
08:58:43:282 Device TTL 864 s
08:58:44:188 send permit join, duration: 59
```
![image](https://user-images.githubusercontent.com/26795429/50888196-67267680-13f5-11e9-8ea0-ea42e9bc8bf7.png)

**Comment by manup** [comment]
Hmm strange, thanks for the logs I will do some pairing tests with these to check whats wrong. Might be related to the other issues where not all resources are created in one run.

**Comment by tubalainen** [comment]
> Hmm strange, thanks for the logs I will do some pairing tests with these to check whats wrong. Might be related to the other issues where not all resources are created in one run.

Please tell me if there is anything else I can do to help in the troubleshooting and solution finding! <3

**Comment by glassbase** [comment]
I cannot add Xiaomi door/window sensor on .54... will attempt downgrade and report back.

**Comment by manup** [comment]
Version 2.05.55 has quite some fixes for this issue, please check if it works now.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_55

**Comment by eggman0131** [comment]
I'm having the same issue with xiaomi door sensors, also one I managed to add under a previous version is working but not showing in phoscon.  It's updating home assistant just fine.

I'm using 2.05.55

**Comment by manup** [comment]
Are the other devices displayed and working in the Phoscon App?

**Comment by eggman0131** [comment]
Hi - all my lights are but I have an xiaomi motion sensors, an xiaomi door sensor and two trust motion sensors that are working and controlling lights, but not showing in phoscon.  I also have a tradfri motion sensor and that is showing.

**Comment by manup** [comment]
Hmm strange, when you are on the sensors page can you please open the developer console via F12 and reload the page, are there any Javascript errors shown (red color) in the console?

**Comment by eggman0131** [comment]
I get this

`Uncaught TypeError: Cannot read property 'vendor' of undefined jquery-min.js?0baf29:2
    at n.initialize (devices-sensors.js?44d5f2:3)
    at n.e.View (backbone-min.js?cedae4:1)
    at new n (backbone-min.js?cedae4:1)
    at n.addOne (devices-sensors.js?44d5f2:3)
    at app.sensors.forEach.sensor (devices-sensors.js?44d5f2:3)
    at Function.m.each.m.forEach (underscore-min.js?2a5156:5)
    at n.forEach (backbone-min.js?cedae4:1)
    at n.reload (devices-sensors.js?44d5f2:3)
    at n.initialize (devices-sensors.js?44d5f2:3)
    at n.e.View (backbone-min.js?cedae4:1)`

**Comment by eggman0131** [comment]
cheers, any idea why I (and whoever started this) can't pair new sensors?

**Comment by manup** [comment]
Please try again with latest version 2.05.57

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_57

Hope it was the same error.

**Comment by eggman0131** [comment]
Hi, thanks.  2.05.57 fixed both issues for me.
