### ISSUE TITLE
Xiaomi pir stuck at detected

### ISSUE THREAD

**Issue by Gnaget2** [dresden-elektronik/deconz-rest-plugin#1118]
After upgrade to .54 of deconz my xiaomi pir switch to detected after a while of inactivity and stay as detected until next motion. 

Causing nex trigger on movement not to happen as the sensor is already in state detected 

I have tried to power cycle it but that only solved the issue for the movement. After some time of no motion the same thing happen

Product ConBee
Version 2.05.54 / 2019-01-04
Firmware 262F0500

**Comment by Gnaget2** [comment]
Was working perfect in .52 with the same FW. No other changes made or new devices.

**Comment by kugelkopf123** [comment]
#1103 Look on the last comments

**Comment by Gnaget2** [comment]
Yes sounds like the same problem. Closing this one
