### ISSUE TITLE
Decimals, Accuracy on Xiaomi Aqara WSDCGQ11LM Temperature Humidity Sensor in Phoscon App

### ISSUE THREAD

**Issue by EarlOfBurton** [dresden-elektronik/deconz-rest-plugin#1119]
Hello,
I installed five Xiaomi Aqara WSDCGQ11LM Temperature Humidity Sensors.
The Phoscon App that I run on a Raspberry Pi 3+ with the preconfigured image by dresden elektronik does not show decimals on the temperature reading while the Xiaomi App does.
Can I somewhere define in the Phoscon App how accurate the measurements should be shown?
To my understanding the Phoscon App seems to round to Integer, which I do not like, I would love to have a decimal as well.

My Versions are:
Version 2.05.54 / 04/01/2019
Firmware 26300500

Thanks for your help in advance,
Hermann

![bildschirmfoto 2019-01-11 um 21 01 38](https://user-images.githubusercontent.com/16398996/51056890-57b95000-15e4-11e9-9f4e-2baf194ee55d.png)

![bildschirmfoto 2019-01-11 um 21 05 10](https://user-images.githubusercontent.com/16398996/51057028-b54d9c80-15e4-11e9-97e5-0e4fe423a020.png)

![bildschirmfoto 2019-01-11 um 21 15 29](https://user-images.githubusercontent.com/16398996/51057513-25a8ed80-15e6-11e9-946d-1d3cb5277f29.png)

**Comment by jan-dewit** [comment]
I think I have ordered exactly the same, I will report when they arrive (should be soon).

**Comment by EarlOfBurton** [comment]
Thank you!
