### ISSUE TITLE
missing association response

### ISSUE THREAD

**Issue by maxjung96** [dresden-elektronik/deconz-rest-plugin#1133]
Hi,
I'm using RaspBee with deCONZ as PAN coordinator and are trying to association to the network with another USB dongle.

deCONZ sends back matching ACK packets after my Association Request and Data Request, but I don't receive the Association Response.
The only log output from the terminal I can find for this is that every time I try to associate the following error shows up:
ZM: Skip unknown command with id = 31

Cheers

**Comment by Darchiv** [comment]
It seems that the network layer does not permit joins - if this is the case, the acknowledgements will be sent but not the Associate Response. Assure that permit join settings in deCONZ are correct.
