### ISSUE TITLE
WebSocket authorization

### ISSUE THREAD

**Issue by MadMonkey87** [dresden-elektronik/deconz-rest-plugin#1134]
I've just came across the websocket doku over here https://dresden-elektronik.github.io/deconz-rest-doc/websocket/

It appears that the appkey is only required to retrieve the correct port for the websocket, but it should not be difficult to simply start with 443 or try some port sniffing. So in fact anyone knowing the ip and port can read all sensor events?

I feel a bit uncomfortable with this, is there any way to support any kind of authorization? A super simple approach would be that the client first has to send an appkey and only after that the events are sent to that client. What do you think about authorization on the websocket?

Thx

**Comment by manup** [comment]
>I feel a bit uncomfortable with this, is there any way to support any kind of authorization? A super simple approach would be that the client first has to send an appkey and only after that the events are sent to that client. What do you think about authorization on the websocket?

Good point I'll put it on the todo list, security in general should be improved. Another approach would be encryption of the outgoing websocket stream.
