### ISSUE TITLE
Extra colon in API response when updating a sensor

### ISSUE THREAD

**Issue by Thomas-Vos** [dresden-elektronik/deconz-rest-plugin#1135]
When updating a sensor like this (PUT request):
URL: `http://IPADDRESS/api/KEY/sensors/1`

```
{
  "name": "Test"
}
```
This is the response from deCONZ:
```
[
	{
		"success": {
			"/sensors/1/name:": "Test"
		}
	}
]
```
Why is there a colon after `name`? This is not in line with the rest of the API (for example /lights).
Edit: created a pull request.

Related code:
- https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/rest_sensors.cpp#L927
- https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/rest_sensors.cpp#L952

**Comment by manup** [comment]
Good catch, thanks for the fix.
