### ISSUE TITLE
Wifi missing Parameter wifiname // Spam im syslog.

### ISSUE THREAD

**Issue by kugelkopf123** [dresden-elektronik/deconz-rest-plugin#1142]
Moin! 

Mir ist aufgefallen, dass seit dem update auf die neuste version .55 der syslog sekündlich mit einem Fehler vollgemüllt wird:

`Jan 17 02:27:10 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:11 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:13 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:14 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:15 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:17 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:18 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:20 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:21 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
Jan 17 02:27:22 raspi4 deCONZ-WIFI2.sh[308]: missing parameter wifiname
`

Grüße!

**Comment by manup** [comment]
Huch, will be fixed in next version.

**Comment by panzerfahrer** [comment]
This seems to put massive load onto my raspi, making it fail to operate and respond completely.
I disabled the `checkConfig` function in `/usr/bin/deCONZ-WIFI2.sh` as a workaround.

**Comment by manup** [comment]
Can you please provide more details, it this running in as normal systemd deconz.service/deconz-gui.service or in a Docker container?

**Comment by kugelkopf123** [comment]
For me on a Raspberry Pi 3b+. Headless mode. Wifi setup was done via Raspi-config befor i installed deconz...

**Comment by det-box** [comment]
Hello, 
I also have this message in the system log. 
Raspi 3+ 
I Back to 2.05.54.
waiting for new Version with Patch.

**Comment by det-box** [comment]
Hi, 
Is this error Patched in Version .05.57 ?

**Comment by manup** [comment]
>Is this error Patched in Version .05.57 ?

Yes log level is down to normal and high load was also improved (but still work in progress).

**Comment by manup** [comment]
Closing this for now.
