### ISSUE TITLE
Xiaomi motion sensors wrong state

### ISSUE THREAD

**Issue by rtenklooster** [dresden-elektronik/deconz-rest-plugin#1145]
Hi, 
Since I’ve updated to 2.05.54 my motion sensors report motion while there is no motion.  Rest api also reports the wrong state. 

Anyone else experiencing these issues? Have rebooted, powered off, nothing helps. 

I have made a backup before upgrading, does restoring a backup reverts the version?

**Comment by AndreasRavn** [comment]
Known bug in 2.05.54, upgrade to 2.05.55 and its fixed.

**Comment by rtenklooster** [comment]
Thanx, I’m wondering why the update isn’t automatically available. I’m using the Deconz image, it’s no problem there is a bug, however I would expect the update would be published like the .55 update was.

**Comment by manup** [comment]
>Thanx, I’m wondering why the update isn’t automatically available. I’m using the Deconz image, it’s no problem there is a bug, however I would expect the update would be published like the .55 update was.

The updates via the update button are published delayed when the version is considered stable and available for a few days via manual install.
