### ISSUE TITLE
Previously paired sensor doesn't show up in neighbor table

### ISSUE THREAD

**Issue by mrjerryjohns** [dresden-elektronik/deconz-rest-plugin#1146]
I have a sensor (a Samsung SmartThings Multi-purpose Sensor) that I'm able to successfully join the network, show up in the neighbor table of the Deconz dongle (MgmtLqiResp in the ZDO profile), and enumerate it's endpoints, profiles, etc.

If I power down the dongle, then power it back up again, I notice that the sensor doesn't show up in the neighbor table, but it still emits indication messages that I'm able to intercept on the dongle.

How is this possible?

**Comment by mysteryan** [comment]
Paired, but not properly saved in database?

**Comment by SwampNinja** [comment]
How would I check that?
