### ISSUE TITLE
Make wifi on frontend visually configurable 

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#1153]
For containers there is no reason to show wifi in the frontend. Could you make this configurable as to not be visible in setups where it is not relevant

**Comment by manup** [comment]
As first step in 2.05.57 the deconz-wifi service is not loaded and displayed when used with Docker containers. In next versions we'll add a easier way to disable the service via Phoscon App or REST-API.

**Comment by Kane610** [comment]
Solved with latest release!

**Comment by Ronoon** [comment]
@manup 
Looks like you´ve done a bit to much this time cause without changing my WiFi settings they disappeared completly on my Raspi 3+ on version .59 maybe before but i didn noticed.
Before this change i could switch between Wifi and Host mode ... right now i have a blank page as where my settings belonged to
Maybe you could have a look at that.
