### ISSUE TITLE
Hue dimmer how to assign keys from phoscon app?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#1156]
I can assign the Hue dimmer to a group of lights and it works, but I wish to assign to the ON Keys multiple scenes (to multiple click), is this possible?

**Comment by ebaauw** [comment]
Not using the group linked to the switch.  The Hue dimmer switch doesn't send scene commands, so you would need to create rules on the gateway to recall a scene.  Also, the Hue dimmer doesn't issue events for multiple clicks.  You would need to create a CLIPGenericStatus sensor to count the clicks, again using rules on the gateway.

**Comment by manup** [comment]
>I can assign the Hue dimmer to a group of lights and it works, but I wish to assign to the ON Keys multiple scenes (to multiple click), is this possible?

Yes, as described in the other comment.

https://github.com/dresden-elektronik/phoscon-app-beta/issues/13#issuecomment-455855634

One feature is that you can cycle through existing scenes with one button.

**Comment by ebaauw** [comment]
Cool.  I assume Phoscon creates the rules and CLIP sensor for this case?

**Comment by manup** [comment]
Yes for some button features plenty of them :)

The scenes cycling is actually implemented in deCONZ /groups endpoint to simply the related rules.

    PUT /api/<apikey>/groups/<group_id>/scenes/<scene_id>/recall
    PUT /api/<apikey>/groups/<group_id>/scenes/next/recall
    PUT /api/<apikey>/groups/<group_id>/scenes/prev/recall

**Comment by ebaauw** [comment]
Cool, so you only need a single rule and no CLIPGenericStatus.  Dare I ask for an update of the REST API documentation?

**Comment by Klagio** [comment]
I found it and works great. I do have 2 hue dimmer, with one everything worked. With the other (which I paired, factory reset, multiple times) now nothing works. It is seen in the phoscon app, I can assign keys... But then... nothing. Is there any way to start from scratch deleting the device from the Conbee (apparently the phoscon app does not delete it totally from the system)? Or any other action I can do?

**Comment by manup** [comment]
>Cool, so you only need a single rule and no CLIPGenericStatus. 

Exactly, we still use CLIPGenericFlag for toggle on/off but might replace this in favor of group.any_on in the future.

>Dare I ask for an update of the REST API documentation?

We're working on it, it's in the progress of a complete refactor. Hopefully it gets online within the next two months.

Here are some impressions of the current state:

![image](https://user-images.githubusercontent.com/383386/51438650-37a62280-1caf-11e9-9c50-fb5b21244606.png)

![image](https://user-images.githubusercontent.com/383386/51438846-c320b300-1cb1-11e9-9cbd-09fdc2ff2d8a.png)

**Comment by manup** [comment]
Which deCONZ version are you using?

> Is there any way to start from scratch deleting the device from the Conbee (apparently the phoscon app does not delete it totally from the system)? Or any other action I can do?

The latest version does delete all relevant resources when you delete the Switch in the Phoscon App.

**Comment by Klagio** [comment]
2.05.55
