### ISSUE TITLE
Group rest sensors by physical device

### ISSUE THREAD

**Issue by MadMonkey87** [dresden-elektronik/deconz-rest-plugin#1162]
It appers that the sensors retrieved from the api does not correlate directly to physical devices. I.e if you have a xiaomi temperature sensor, you would get one sensor for the temperature, one for the humidity and one for the air pressure - which is perfectly fine.

Now I try to group them into physical devices (the phoscon app seems to do this as well). My naive approach would be the unique id which seem to consist of the mac address of the physical device + some postfix (cluster id or something?)

- can I simply take the first 23 characters of the unique id aka mac address and assume that if I've found some matching ones -> they belong to the same physical device?
- where from do I receive properties of the device (name, battery state)?

**Comment by ebaauw** [comment]
> can I simply take the first 23 characters of the unique id aka mac address and assume that if I've found some matching ones -> they belong to the same physical device?

Yes, for resources belonging to Zigbee devices.  For other resources (groups, CLIP sensors) `uniqueid` isn’t or is missing.

> where from do I receive properties of the device (name, battery state)?

The battery state is exposed on all sensor resources belonging to the device, and should have the same value on each.  The name is a property of the resource, not of the device.
