### ISSUE TITLE
[request device support] Plugwise smart plug (not circle) Zigbee HA Qupit model 160-01

### ISSUE THREAD

**Issue by herwarth** [dresden-elektronik/deconz-rest-plugin#1167]
Hello,
Plugwise has created a new smart plug which is now Zigbee HA compatible. It is not the Plugwise Circle but the successor of it (although they look the same).
I have added it to deCONZ and I can read the power usage. It also measures several other power related stuff like received power (solar panels?).
The requested info:
![screenshot from 2019-01-21 19-00-07](https://user-images.githubusercontent.com/1688562/51491778-b7b3b180-1daf-11e9-85fd-8a20013ccbdc.png)
![screenshot from 2019-01-21 18-58-30](https://user-images.githubusercontent.com/1688562/51491791-c26e4680-1daf-11e9-8d9d-092164b843b9.png)

**Comment by herwarth** [comment]
adding additional screenshots
<img width="244" alt="screen shot 2019-02-22 at 20 29 44" src="https://user-images.githubusercontent.com/1688562/53266637-b0026800-36e1-11e9-9060-c96eb7791e40.png">
<img width="472" alt="screen shot 2019-02-22 at 20 30 35" src="https://user-images.githubusercontent.com/1688562/53266642-b4c71c00-36e1-11e9-8bff-6cb1cde5d30b.png">
<img width="479" alt="screen shot 2019-02-22 at 20 31 51" src="https://user-images.githubusercontent.com/1688562/53266650-b8f33980-36e1-11e9-9111-1a6d061c7cc5.png">
<img width="477" alt="screen shot 2019-02-22 at 20 32 07" src="https://user-images.githubusercontent.com/1688562/53266653-bbee2a00-36e1-11e9-9510-88c2a03ffc0e.png">

**Comment by herwarth** [comment]
simple on/off switching works, but power metering is a must. please help me out, because i am waiting for this to be implemented

**Comment by kasteleman** [comment]
Keep in mind the plug from time to time reports -2 Watt although nothing
connected.

Op vr 22 feb. 2019 om 20:39 schreef herwarth <notifications@github.com>

**Comment by alexdepalex** [comment]
Does this plug properly measure power? Or is there still some work that needs to be done?

**Comment by alexdepalex** [comment]
Do we need any additional information to get this forward?

**Comment by Mimiix** [comment]
@alexdepalex is this still open?

**Comment by alexdepalex** [comment]
Yeah. I think it is. The plug works, but HA detects it as a light, so it doesn't expose for example power measurement. And that's something that I need. Not many switches that support power measurement and 16A.

**Comment by Mimiix** [comment]
Can you provide the debug logs of the addon in home-assistant? ? Info on how to enable that are on the info page of the addon. 

If you are in discord, use the .hadebug command and it will show you.

**Comment by SwoopX** [comment]
Somebody just needs to read the electrical measurement and simple metering clusters attributes while a load is allied where you have an estimate of how much that is (e.g. 15W charger for mobiles). That helps.

**Comment by alexdepalex** [comment]
8W led bulb
<img width="390" alt="Schermafbeelding 2020-06-16 om 18 47 54" src="https://user-images.githubusercontent.com/713019/84803337-2b3c0b80-b002-11ea-9f9e-6d1dc151787f.png">
40W filament bulb
<img width="396" alt="Schermafbeelding 2020-06-16 om 18 36 07" src="https://user-images.githubusercontent.com/713019/84803403-3f800880-b002-11ea-8984-b6d710e9d4e7.png">
100W filament bulb
<img width="389" alt="Schermafbeelding 2020-06-16 om 18 33 35" src="https://user-images.githubusercontent.com/713019/84803370-33944680-b002-11ea-989e-a356cb28dfa4.png">

**Comment by alexdepalex** [comment]
I do see that sometimes negative values are reported for `Total Active Power`.

**Comment by SwoopX** [comment]
Why have you cut off the 500-series attributes? Usually, this is where the misuc plays for that cluster.

The other cluster is missing as well! ;)

**Comment by alexdepalex** [comment]
<img width="559" alt="Schermafbeelding 2020-06-16 om 22 49 58" src="https://user-images.githubusercontent.com/713019/84826787-c7c2d580-b023-11ea-80ff-53892d017c86.png">

Which cluster are you missing?

**Comment by SwoopX** [comment]
Simple metering. Current summation and instantaneous demand is of interest.

**Comment by alexdepalex** [comment]
Seems like they're not being used.

<img width="564" alt="Schermafbeelding 2020-06-16 om 23 57 05" src="https://user-images.githubusercontent.com/713019/84832197-1fb20a00-b02d-11ea-84a7-26ea0c57dec4.png">

**Comment by SwoopX** [comment]
Closing this as PR has been merged. Supported with .78
