### ISSUE TITLE
Question: Using server for simple websites

### ISSUE THREAD

**Issue by ferby09** [dresden-elektronik/deconz-rest-plugin#1170]
Hello,
I'm wondering if it is possible to use the environment the Phoscon App creates to host another website locally.
I'm trying to provide another website like `http://xxx.xxx.xxx.xxx/pwa/test/index.html` which is basically just an index tree of the folder test and where I can download files by clicking on them or editing the URL, as I can't run another server on port 80 (or can I?).
If I create a simple index tree I can see the files, but they can't be downloaded because the file cannot be found.
I'm nowhere experienced with web servers, but I think that the most important information for me would be the environment Phoscon is using, like nginx, Apache etc.
Can someone help me with this please?

**Comment by manup** [comment]
The default http root is `/usr/share/deCONZ/webapp`. It can be overwritten with the commandline paramater `--http-root=<path>` be aware that neither WebApp nor Phoscon App won't work then.

As alternative you may add a directory inside the http root directory, but it might get deleted when updating or removing deCONZ (not sure about that).

**Comment by ferby09** [comment]
Yes, I did that. When adding an own index.html to a new directory in `/usr/share/deCONZ/webapp` I can access it in my browser but I can't download any file from it. Maybe I'm missing essential knowledge about web developing but I thought that I could download a file from there by rightclicking and saving it, but it always just tells me that the file is not found.
Also php isn't working either, that's why I'm wondering what kind of server it is or which restrictions it has.

**Comment by manup** [comment]
Not sure, but can also run the other web server on a different port.

**Comment by ferby09** [comment]
Unfortunately the other server needs to run on port 80.
I changed deCONZ' port to 8080 and I could control my lamps with Alexa.
The only problem I've got now is that FHEM looks for port 80 when defining a HUE-Bridge. But that has nothing to do with deCONZ.
Thank you very much for your help!
