### ISSUE TITLE
Isolicht Zigbee 220 to 220 compatible?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#1173]
Is this compatible?

Its an interesting article for those who already have a system in place and to not want to dismount everything, but you should be able to bring normal led lights to be dimmerable

https://www.amazon.it/controller-compatibile-Philips-Lightify®-TRÅDFRI®/dp/B076KPQWFW/ref=sr_1_20?ie=UTF8&qid=1548316860&sr=8-20&keywords=zigbee+gu10

**Comment by manup** [comment]
I guess it should work, likely as dimmable light.
