### ISSUE TITLE
Not able to control GLEDOPTO devices any longer

### ISSUE THREAD

**Issue by saxn-paule** [dresden-elektronik/deconz-rest-plugin#1176]
Today I updated to the .57 firmware. Its not possible to control GLEDOPTO devices via Phoscon any longer.

The controllers are shown and could be added to groups but the sliders don't appear.

EDIT: After a little time the sliders appear again. But I'm not able to turn the light on. No reaction on changing the dimlevel or clicking on/off the group.

It's a GLEDOPTO 009

**Comment by manup** [comment]
I have only the GLEDOPTO RGBW version with SMILB brand here for testing, this one works fine.

Version: 1.0.2
Datecode: 20131206

You may try to force Phoscon App cache refresh by appending some random search query in the URL bar.

    http://<gateway-ip-address>/pwa/index.html?12345

**Comment by saxn-paule** [comment]
Still no change. If I click the lights icon of a group, the dim slider jumps to ~50% but the lights stay off.

Do you live in DD? The I could give you a 009 for testing.

**Comment by saxn-paule** [comment]
007 and 008 still work like before.

**Comment by saxn-paule** [comment]
I use Deconz in headless mode, so I can't make any screenshots.
With .55 controlling the 009 was still possible.

I only updated the firmware. Nothing else.

**Comment by saxn-paule** [comment]
With the .58 version the 009 isn't detected at all any longer:

![image](https://user-images.githubusercontent.com/8352690/52012744-b08d5180-24db-11e9-968f-25d3bb0b077c.png)

**Comment by saxn-paule** [comment]
I just tried a second 009 controller. It isn't detected at all. Nothing shown in Phoscon.

**Comment by saxn-paule** [comment]
I changed the controller. The new one is controllable again. So, my fault. Sorry.

**Comment by manup** [comment]
:) I guess these require a bit patience, the missing modelid and manufacturer names are populated in an idle timer which takes a bit. But once set these should be directly available in further restarts.

**Comment by ebaauw** [comment]
As I understand, the GL-C-009 is a Dimmable Light (no colour nor colour temperature)?  I suspect it has both a ZLL and a ZHA endpoint doing the same, like the GL-C-007 (RGBW), see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/952.  Could you post a screenshot from the deCONZ GUI and the resources as exposed by the REST API?

The GL-C-008 (RGB+CCT) doesn't seem to react to _Move to Level (with On/Off)_, see https://github.com/ebaauw/homebridge-hue/issues/424.  If the 009 does the same, PUTting `{"bri": 0}` wouldn't turn it off.  Also, it wouldn't turn on if you PUT `{"on": true, "bri": 254}`.

**Comment by saxn-paule** [comment]
Yes it's only a dimmer. I use deconz in headless mode. How could I provide these screenshots?

**Comment by ebaauw** [comment]
> Yes it's only a dimmer. I use deconz in headless mode. How could I provide these screenshots?

You need to run the GUI for that.  I use VNC on a headless Raspberry Pi to share the graphical screen to my Mac.

**Comment by nagyL** [comment]
Some sample images related to my GL-C-009:

![image](https://user-images.githubusercontent.com/11348171/53291420-4d799c80-37b3-11e9-8296-a5b7fcc674a1.png)

![image](https://user-images.githubusercontent.com/11348171/53291436-a5b09e80-37b3-11e9-9cc9-a46502ad2358.png)
