### ISSUE TITLE
Harmony Hub/Deconz and Osram Smartplug

### ISSUE THREAD

**Issue by Nobbbi** [dresden-elektronik/deconz-rest-plugin#1179]
Hi 
i have paired my Harmony Hub with the companion Remote with deconz as a Philips Hue device. 
I use the small smarthome buttons on the right, each of them for one osram smart plug.
A short press on the button turns the osram smart plug on and a long press off. 

My problem is, after a mount of time, i press the button short the plug stays off.  
To enable the plug i have to press the dimming buttons up. 

If I turn the devices on and off again the problem does not exist.

The smartplugs are controlled only by the remote control and not by another device. 
Not even about Phoscon.

I have the feeling that after a certain time some value in deconz changes and the remote control means it would have to dim the light to turn it on.

The smart plug has no dimming function

cheers

**Comment by tomfritz1** [comment]
I have the same issue
