### ISSUE TITLE
 Xiaomi Mijia (HonneyWell) gas detector

### ISSUE THREAD

**Issue by AdamWeglarz** [dresden-elektronik/deconz-rest-plugin#1182]
Hi,

I have also Xiaomi Mijia (HonneyWell) gas detector. It connects without any issue to Xiaomi Gateway so it work correctly. It does not connect at all to Deconz zigbee. It is not visible in Deconz graphical interface (In oposite to Xiaomi smoke sensor, which is visible in Deconz app).
How I can help to diagnoze issue?

Adam

**Comment by manup** [comment]
The device is currently not supported.

Please provide the details as described here:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by SirJMD** [comment]
I've hit the same road block, I also have a gas detector I'd like to use.

I'd be more than happy to supply the needed details, but I have no idea where to find "Cluster Info Panel" and the rest mentioned in the link. I guess it's no via Phoscon?

**Comment by AdamWeglarz** [comment]
For starters. Tomorrow I will buy lighter to start alarm and capture what is send by the device when alarm is raised and cleared:

![obraz](https://user-images.githubusercontent.com/45738893/51779538-3c803180-2108-11e9-84cf-eadc9f84b63e.png)
![obraz](https://user-images.githubusercontent.com/45738893/51779563-5e79b400-2108-11e9-82cb-270c61a2a719.png)
![obraz](https://user-images.githubusercontent.com/45738893/51779582-7e10dc80-2108-11e9-8076-889a16851080.png)

**Comment by ebaauw** [comment]
This one plugs into the mains power?  It looks a lot like the Heiman sensor I had on loan, also Jennic based.  While detecting gas, it issues an alarm from the _IAS Zone_ cluster while making a lot of noise.  Same for pressing the test button.  Unfortunately, the siren cannot be activated externally.

It’s probably enough to whitelist the sensor (twice: in the sensor whitelist and in the _IAS Zone_ logic, to create the right sensor type).  Could you press _Read_ on the cluster into panel so the attribute values get populated?

**Comment by SirJMD** [comment]
It's powered by 12V and comes with a mains adapter. It also have a NO set of contacts, for hard wired alarm.

**Comment by SirJMD** [comment]
There's no battery.

**Comment by ebaauw** [comment]
Ah, OK.  Then it's "just" an external power adapter.

**Comment by AdamWeglarz** [comment]
Basic
![obraz](https://user-images.githubusercontent.com/45738893/51786266-0bcce600-2162-11e9-8fad-5d18c978eee6.png)
Ias
![obraz](https://user-images.githubusercontent.com/45738893/51786293-6b2af600-2162-11e9-9f39-b7712788755f.png)
power
![obraz](https://user-images.githubusercontent.com/45738893/51786302-a62d2980-2162-11e9-93a8-3cfe5fd53115.png)
 
Rest is empty.
There are two push options 
- Test alarm
- Sensitivity of the sensor

Is it possible to sniff traffic between xiaomi gateway and gas sensor?
PS The same options are available for smoke sensor.

Adam

**Comment by ebaauw** [comment]
OK, if you write the mac address of the RaspBee or ConBee to the _IAS_CIE_Address_ attribute (0x0010 in the _IAS Zone_ cluster), _Zone State_ should change to _Enrolled_ and you should see alarms in _Zone Status_ when pressing the test button.  Be sure to protect your ears ;-)

It doesn't look like the sensitivity is exposed over Zigbee.

**Comment by AdamWeglarz** [comment]
Hi,

should it be visible in Rest API?
![obraz](https://user-images.githubusercontent.com/45738893/51787831-f44c2800-2176-11e9-90eb-cdd0af8b9fb5.png)
It is recognized as co2 sensor after putting MAC as you recommended. Not enrolled

Adam

**Comment by SirJMD** [comment]
Is there any additional information required before it can be added? If so, I'd be happy to help.

**Comment by fuzzysb** [comment]
I have one with the same issue, when updating the address of the Deconz Gateway in to the  IAS_CIE_Address i am also unenrolled, when trying to read the reporting configuration i get the following error
![image](https://user-images.githubusercontent.com/16162689/54443086-dbec9880-4737-11e9-987d-290050bc2f66.png)

**Comment by alahdal** [comment]
Hi,
Are you going to support this device? Or is it already compatible with RaspBee?

**Comment by alahdal** [comment]
I got my new Xiaomi Mijia (HonneyWell) gas detector, it is not connecting to RaspBee. Any plan?

**Comment by iamkarlson** [comment]
Any hope to get this available?

**Comment by Otnow** [comment]
> 
> 
> Is there any additional information required before it can be added? If so, I'd be happy to help.

+1

I have this device and Conbee II. What information needs to be provided to add support?

**Comment by WladyX** [comment]
I also have 2 of these and Conbee 2 and also can help with info.

**Comment by AdamWeglarz** [comment]
So any news?

**Comment by fastsonic** [comment]
hi, i also try to connect to the Gas Sensors,
when its poosibel to Help ? please contact me
Thanks

**Comment by L3H0** [comment]
> 
> 
> Any hope to get this available?

+1

**Comment by WladyX** [comment]
This was working on zigbee2mqtt, maybe it's possible to get some inspiration from that code? :)

**Comment by SirJMD** [comment]
I've given up on deconz, zigbee2mqtt is being maintained much better.

**Comment by WladyX** [comment]
Maybe, in my case it did not handle the size of my network well (+80 nodes).
On topic: If we can help in anyway to get this supported, please let us know.

**Comment by mwhiegl** [comment]
I second the request and offer to help. Not a coder, but let me know if any more data is needed or so.

**Comment by fastsonic** [comment]
push Also available for any Help

**Comment by iamkarlson** [comment]
@SirJMD is there also a way to set up direct bindings with zigbee2mqtt?

**Comment by AdamWeglarz** [comment]
Hello,

Can you tell that you plan to add support for this device?

**Comment by JohCo-hassio** [comment]
Hello,
I also bought this sensor last week and unfortunately it does not come online even in the Rest-api not receiving anything to HA. What is different is that the site now supports the ZYCT-202.

**Comment by alahdal** [comment]
any update?

**Comment by AdamWeglarz** [comment]
I gave up and setup zigbee2mqtt :-(

**Comment by L3H0** [comment]
> 
> 
> I gave up and setup zigbee2mqtt :-(

z2m on Conbee2 or C2538?

**Comment by And3rsL** [comment]
is this device supported now? i currently looking for a gas detector to buy and i would like to buy the xiaomi one

**Comment by L3H0** [comment]
@And3rsL nope, till today this device is not supported.

**Comment by andriej** [comment]
It can be seen in integrations using API (like HomeAssistant) not in Phoscon.
Nor you will be able to set sensitivity as in app.
But I still recommend the sensor, I had tested it. I just hope dresden will finally wake up some day and keep up to the market...

**Comment by AdamWeglarz** [comment]
> 
> 
> It can be seen in integrations using API (like HomeAssistant) not in Phoscon.
> Nor you will be able to set sensitivity as in app.
> But I still recommend the sensor, I had tested it. I just hope dresden will finally wake up some day and keep up to the market...

No it is not. You are mixing gas sensor with smoke sensor which is really working like you explain.

**Comment by andriej** [comment]
Sorry! You're right.

**Comment by SwoopX** [comment]
I'll add it soon, should be a quick one

**Comment by alahdal** [comment]
Very much appreciated! @SwoopX

**Comment by JohCo-hassio** [comment]
Very nice 👍🏻

**Comment by OldSystemMan** [comment]
At last 👍

**Comment by SwoopX** [comment]
I still need someone to collect me 1h of log data so I can inspect the special attribute reporting for this device.

`sudo systemctl stop deconz-gui`
`/usr/bin/deCONZ --dbg-info=2 > xiaomi_debug`

**Comment by alahdal** [comment]
I hope you find the file helpful this time. It is worth mentioning that the Gas detector is not connected to the RaspBee, because it is not supported yet.

Please let me know if there is anything else I can do.

[xiaomi_debug.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4804925/xiaomi_debug.txt)

**Comment by SwoopX** [comment]
That's perfect, thanks!! Lots of stuff in there I always wanted to get a look at.

What I actually do not see it the gas sensor as far as I can tell. You got one right?

**Comment by alahdal** [comment]
@SwoopX I got the Gas Sensor, but it is not connected with RaspBee. When I try to connect via Phoscon App (web), it does not connect.

**Comment by SwoopX** [comment]
@alahdal I see. Will come with the next release. Do you use HA or docker? If not, you could compile a dev version of the plugin and become my lab rat ;)

**Comment by alahdal** [comment]
It is installed on a Raspbian.

**Comment by SwoopX** [comment]
So, you might want to try the following. Would really appreciate if you could generate another debug file when you want to play with it (then use `/usr/bin/deCONZ --dbg-info=2 > xiaomi_debug2` for step 5 mentioned below):

1. Clone my repository containing the changes
`git clone https://github.com/SwoopX/deconz-rest-plugin.git`
`cd deconz-rest-plugin`
2. Shut down deconz
`sudo systemctl stop deconz-gui`
3. Make a backup of file "general.xml"
`sudo mv /usr/share/deCONZ/zcl/general.xml /usr/share/deCONZ/zcl/bak_general.xml`
4. Copy the amended general.xml to the required location
`sudo cp general.xml /usr/share/deCONZ/zcl/`
5. Start deconz again
`sudo systemctl start deconz-gui`

For the smoke sensors, you should see 2 additional attributes in cluster `0x0500 IAS Zone`. For attribute `Selftest/Density`, double click on it and read the value (not read config!). Please share a screenshot from that.

Now, if all wen well, you should be able to initiate selftest by writing value `03010000` to that attribite. Sensitivity should be setable with values as follows:
- Low: `04010000`
- Medium: `04020000`
- High: `04030000`

**Comment by alahdal** [comment]
@SwoopX These are the screenshot for the attributes in 0x0500.

<img width="870" alt="Screen Shot 2020-06-21 at 4 56 38 PM" src="https://user-images.githubusercontent.com/7605173/85226500-767a6380-b3e0-11ea-9c3f-1c232a0f6724.png">


<img width="870" alt="Screen Shot 2020-06-21 at 4 56 50 PM" src="https://user-images.githubusercontent.com/7605173/85226482-59459500-b3e0-11ea-931e-718ed8109754.png">

**Comment by SwoopX** [comment]
My bad, used the wrong manufacturer code. Can you try once again? Start with deleting the downloaded repository locally `sudo rm -rf ./deconz-rest-plugin`.

**Comment by alahdal** [comment]
Reading Failed.

PS. Just to clarify, we are at the Gas detector topic not the [Smoke Detector](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2954#issuecomment-645613868)

<img width="870" alt="Screen Shot 2020-06-21 at 5 26 42 PM" src="https://user-images.githubusercontent.com/7605173/85227168-649abf80-b3e4-11ea-9893-c32da159e5d3.png">

**Comment by SwoopX** [comment]
Yes, but if I understand this correctly, it should work for both, smoke and gas. I'm not in front of my desktop to double check, but at least both attributes are offered. Did sesnitivity succeed in reading? If yes, can you share the screenshot?

From what I've read, those devices are deep sleepers, waking up only every 30 secs. So you might try a bit for reading. The node should blink blue/green when ready...

**Comment by alahdal** [comment]
I tried to read from another sensor that is close to the RaspBee system (I thought maybe with better connection I may get different results), I got different error:

<img width="1018" alt="Screen Shot 2020-06-21 at 6 34 11 PM" src="https://user-images.githubusercontent.com/7605173/85228757-1d193100-b3ee-11ea-9846-8dc255b2689a.png">


<img width="1018" alt="Screen Shot 2020-06-21 at 6 34 37 PM" src="https://user-images.githubusercontent.com/7605173/85228758-21dde500-b3ee-11ea-90a0-54ee851a41c2.png">


Moreover, I tried reading other basic attributes all gives the same error (reading failed), maybe something wrong with my setup?

**Comment by alahdal** [comment]
Here is a log 
[xiaomi_debug2.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4809795/xiaomi_debug2.txt)

**Comment by alahdal** [comment]
I restarted deCONZ with sudo, however, it showed all nodes without names and not does not show all clusters. I will leave it for sometime and check again, I noticed the clusters are shown gradually.

Why I run as sudo, I noticed that I can read the cluster info when it is run as sudo.

**Comment by alahdal** [comment]
I have stopped deCONZ and restarted without sudo, when I tried to read attribute in basic cluster info, it worked without problem. However, for the new two new attributes, I am still getting the error shared in the last screenshot

**Comment by SwoopX** [comment]
Hm, maybe the 2 attributes are not required to be manufacturer specific. The additions to `general.xml` were the following

```
<attribute-set id="0xf000" description="Xiaomi specific" mfcode="0x1037">
    <attribute id="0xfff0" name="Sensitivity" type="u32" access="r" required="o" mfcode="0x1037"></attribute>
    <attribute id="0xfff1" name="Selftest/Density" type="u32" access="rw" required="o" mfcode="0x1037"></attribute>
</attribute-set>
```

You could try removing this part for the data above `mfcode="0x1037"` to see if that changes anything.

Btw, if you pull my repo now, support for the gas sensor is included.

**Comment by alahdal** [comment]
@SwoopX after removing (mfcode="0x1037") from above data, I get "unsupported attribute" error.

<img width="1018" alt="Screen Shot 2020-06-22 at 9 04 24 AM" src="https://user-images.githubusercontent.com/7605173/85255084-3fe92b00-b46a-11ea-8ddd-bdb9c6a8959a.png">

I believe the Gas Sensor is connected now, and I could read some of its attributes. However, the item does not appear in the REST API nor discovered by Phoscon.

<img width="1236" alt="Screen Shot 2020-06-22 at 9 26 20 AM" src="https://user-images.githubusercontent.com/7605173/85255189-76bf4100-b46a-11ea-91ab-94b170670919.png">

**Comment by SwoopX** [comment]
@alahdal Please leave the `Sensitivity `attribute for further tests. Have you tried to write any of the low/medium/high values yet to `Selftest/density` yet? If not, please do so (with and without the mfcode in general.xml). You can also test the selftest value if you're brave.

For the gas sensor to work, you need to compile my repo. Instructions are in the readme.

**Comment by alahdal** [comment]
@SwoopX when I remove the mfcode, both attributes are not supported, hence, I cannot read or write. With the mfcode, I get the error shared earlier [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1182#issuecomment-647144930) where I read/write.

**Comment by DaveRuijter** [comment]
Hi! I'm wondering about the status of this development 🤗. @SwoopX can you share what is going on?
I can't wait to try this capability in Home Assistant (for the smoke detectors!).
Thanks!

**Comment by AdamWeglarz** [comment]
> Hi! I'm wondering about the status of this development . @SwoopX can you share what is going on?
> I can't wait to try this capability in Home Assistant (for the smoke detectors!).
> Thanks!

Smoke sensor is working with test api even though it is not visible in phoscon

**Comment by DaveRuijter** [comment]
Yes, and I'm aware of that 👍 . But this extra development is about having a trigger for the alarm test functionality and support for more sensors (actually the related issue is about that, but they are a combined effort with the gas detector if I understand it correct).

**Comment by Mimiix** [comment]
@DaveRuijter Is this something you want in Phoscon?

**Comment by SwoopX** [comment]
@Mimiix Slow down ;)

It either doesn't work or hasn't been tested correctly. z2m has a 30 sec delay with that. Anyway, should be able to be easily tested as mentioned above.

**Comment by alahdal** [comment]
@SwoopX I made a clean install and I am going to try again :) and compile your repo

**Comment by alahdal** [comment]
> For the gas sensor to work, you need to compile my repo. Instructions are in the readme.

I compiled your plugin and now the Gas Sensor appears in the Rest API, very cool.

Tell me what do you want next for both the Gas and the Smoke.

**Comment by L3H0** [comment]
On the latest beta, sensor visible in VNC.
In Home Assistant too.
![Adnotacja 2020-07-24 115211](https://user-images.githubusercontent.com/45450565/88380211-6caf9b80-cda4-11ea-8ee3-29ffec424ec2.png)

**Comment by alahdal** [comment]
Yes with @SwoopX plugin, I have the gas sensor visible in OpenHAB and tested working fine.

**Comment by SwoopX** [comment]
Closing this one as support has been provided with version .79.

**Comment by mwegener-com** [comment]
Any news on support for this device?

**Comment by leonardpitzu** [comment]
a nice addition would be to add a toggle exposed also in HA in order to manually trigger the siren. currently in HA only a sensor is exposed

**Comment by SAOPP** [comment]
Guys, as far as I understand, you can already buy this device?

**Comment by SAOPP** [comment]
So guys, it's not possible to set sensitivity at this sensor via gui?

**Comment by SAOPP** [comment]
> a nice addition would be to add a toggle exposed also in HA in order to manually trigger the siren. currently in HA only a sensor is exposed

Btw, I got gas sensor, tamper and temperature:

![image](https://user-images.githubusercontent.com/5647009/125515356-43d1b571-5b2f-4892-9182-86f2c80e5070.png)

**Comment by SAOPP** [comment]
Really, it would not be bad to adjust the sensitivity through the HA. That would be great.
