### ISSUE TITLE
Unknown Xiaomi device showing up after updating from .55 to .57

### ISSUE THREAD

**Issue by cnrd** [dresden-elektronik/deconz-rest-plugin#1184]
I don't own any door locks, however this device is showing up after updating from .55 to .57

Anyone who can identify what it is and if it is supposed to be there?

![Device](https://i.imgur.com/gZWklQS.png)
![Basic cluster](https://i.imgur.com/Otmo8DW.png)
![Door Lock Cluster 1](https://i.imgur.com/Nb28sAM.png)
![Door Lock Cluster 2](https://i.imgur.com/k8Dv4ks.png)
![Door Lock Cluster 3](https://i.imgur.com/YoaYfNE.png)

**Comment by ebaauw** [comment]
It’s a `lumi.vibration`.

**Comment by manup** [comment]
Side note if it is not shown in the REST-API and Phoscon App as vibration sensor, you need to rejoin the sensor via sensor search to be fully detected.
