### ISSUE TITLE
Issue: Philips Dimmer switch not working properly 

### ISSUE THREAD

**Issue by ftonat** [dresden-elektronik/deconz-rest-plugin#1188]
Hi,
Using
Version 2.05.57 / 20.1.2019
Firmware 26300500

I have successfully paired a Philips dimmer switch to deconz via phoscon (10s long press reset button)

I can assign existing light to the switch (Paulmann).

Issues:
- No Scene editor available in Phoscon for this switch
- controlling the lights only possible: Off, dim up, dim down. ON is not working

Any hints?

![img_0046](https://user-images.githubusercontent.com/30591339/51818681-1ad1a680-22d0-11e9-915e-aed4d3ae64d4.png)

![img_0045](https://user-images.githubusercontent.com/30591339/51818694-22914b00-22d0-11e9-9ac0-b654d826f2c0.png)

![img_0044](https://user-images.githubusercontent.com/30591339/51818704-29b85900-22d0-11e9-8057-25dffeeb9b47.png)

**Comment by manup** [comment]
To use more functions other than the default ones, please use the switch editor as described here:

https://doc.phoscon.de/app/doc.html#group-edit-switches-en

**Important**

* Don't assign lights directly to the switch (as in your screenshots), this would collide with the switch editor.
* The switch editor works on *normal light groups*.  Please check out the small video in the docs, which shows this.

We will describe this better in the Phoscon App in future versions, to make this more clear and less confusing.
