### ISSUE TITLE
disable pir, if switch activated lamps - in group

### ISSUE THREAD

**Issue by thrusty66** [dresden-elektronik/deconz-rest-plugin#1191]
Hi, there is an option missing in phoscon Web ui. 
Example: a group with switch, pir, some lamps.
The pir switches on and off one of the lamps during the night, using the logic of deconz, as a night light.
If now all lamps are switched, then the logic of the pir switches off one lamp after some time.

Is it possible to insert a function to disable the pir when the switch is activated?

**Comment by manup** [comment]
>Is it possible to insert a function to disable the pir when the switch is activated?

Yes, the related configuration is described in the docs:

https://doc.phoscon.de/app/doc.html#group-edit-sensors-example-motion-switch-en

Albeit not all switches are listed there yet, looking forward to add all switches which are also supported in the switch editor in next version 2.05.58.
