### ISSUE TITLE
Cannot pair iConnectHue with deCONZ 2.05.57

### ISSUE THREAD

**Issue by waywit** [dresden-elektronik/deconz-rest-plugin#1193]
Hi

actually I have issues with pairing my raspbee with deCONZ 2.05.57 and iConnectHue. Prior this has worked, but actually I cannot pair it anymore. Does anyone has some tips how to go on and get it work? What can I try? 
I already deleted iConnectHue and original Hue App, after that it will be found with correct IP... but after adding it has errors and cannot be used. After that the reaspbee bridge is not found anymore...

Thanks and best regards!

**Comment by markbajaj** [comment]
I am new to deCONZ and am on 2.05.57. I cant get deCONZ to pair with any HUE app or iConnectHue either - iConnectHue finds the bridge but says unknown error. Does anyone know if this is possible to do?

**Comment by ottelo9** [comment]
I have a Conbee 2 Stick and use Version 2.05.63 / 3.4.2019. I can find my Base with the Hue App but with iConnectHue I get the same error.

**Comment by ottelo9** [comment]
The problem still exists with the newest version

**Comment by bubffm** [comment]
I cant connect my RaspBee neither. deConz 2.05.65

**Comment by alert82** [comment]
Does it work now ?
