### ISSUE TITLE
Problems with Phoscon

### ISSUE THREAD

**Issue by Nobbbi** [dresden-elektronik/deconz-rest-plugin#1194]
Unfortunately, the switch editor is not reliable.

1st case
I have controlled 3 Ikea lamps with Hue or Ikea remote. There are different scenes on the buttons.
Switching the scenes is very unreliable. Most individual lamps remain in the old state or do not react. Sometimes the lights go off even though they should only change the brightness. Switching the scenes usually confuses everything. Turning everything off and on again is usually not a problem.

2 case
I have an Osram smartplug with a 15 minute timer and controlled with a Xiaomi single button. The scenario envisages that the Osram will be switched on and switch off automatically after 15 min. This does not work in most cases. Either the smart plug stays on for over 15 minutes or does not turn off at all. In very rare cases it works.

Nobby

**Comment by manup** [comment]
Usual first question: which deCONZ version are you running?

The switch editor only sends a command to the group that a scene should be activated, the scene is stored on the bulbs itself.

If this doesn't work well, please check if the scene is working properly in the scene editor. For Ikea lights for now I'd recommend setup each light individually not via group control and then save the scene.

>I have an Osram smartplug with a 15 minute timer and controlled with a Xiaomi single button. The scenario envisages that the Osram will be switched on and switch off automatically after 15 min. This does not work in most cases. Either the smart plug stays on for over 15 minutes or does not turn off at all. In very rare cases it works.

I don't understand, how is this setup done? The switch editor doesn't support timers.

**Comment by Nobbbi** [comment]
Hi Manup

It ist Build 57
Switching in the scene editor ist the same behavior and the lamps are setup individually not as a group. 

My fault not the switch editor, the timer setting in a group was mean

Nobby

**Comment by manup** [comment]
Which Ikea light models are you using? Maybe I can recreate the issue, it's been a while since I've testes scenes with Ikea lights.

>My fault not the switch editor, i mean the timer setting in a group.

Can you please provide a screenshot how the switch is configured in the sensor control?

**Comment by manup** [comment]
The versions of the Ikea lights would also be interesting, maybe they can be updated.

**Comment by Nobbbi** [comment]
The Model of the Ikea Lights are TRÅDFRI Lampe E27 opal 1000lm with  V 1.2.214.
I have the feeling that the commands to the lamps are quite slow if i change the scenes.
Is there a way to check that or to tweak the zigbee network? 

Here some Screenshots of the Group with the Timer

<img width="414" alt="bildschirmfoto 2019-01-29 um 19 39 45" src="https://user-images.githubusercontent.com/44261565/51931783-f7a51500-23fd-11e9-87c8-6ee07bf2d512.png">
<img width="757" alt="bildschirmfoto 2019-01-29 um 19 41 39" src="https://user-images.githubusercontent.com/44261565/51931784-f7a51500-23fd-11e9-9b33-63fa106cc72b.png">
<img width="863" alt="bildschirmfoto 2019-01-29 um 19 41 25" src="https://user-images.githubusercontent.com/44261565/51931785-f7a51500-23fd-11e9-97d4-d7772e203c82.png">
<img width="293" alt="bildschirmfoto 2019-01-29 um 19 40 49" src="https://user-images.githubusercontent.com/44261565/51931786-f83dab80-23fd-11e9-9865-63f3b1d516b1.png">

**Comment by Nobbbi** [comment]
Ok thank you for testing !
Did you change the scenes 1x, 2x and 3x klicks with the xiaomi button?

I am rotating the scenes with 2 buttons at a hue switch.
Could this make a differenz?

![bild](https://user-images.githubusercontent.com/44261565/51973910-054eaf00-247f-11e9-8a82-787ae1e59993.png)


How can i check or tweak  that my zigbee network, is working with best results. 
As i wrote before i have the feeling that the communication between the devices are slow or somtimes the lamps are not getting the new seetings. If i look at the networkmap with vnc everything looks ok.

**Comment by Nobbbi** [comment]
I read your hint in another bug entry, and changed it already  !
