### ISSUE TITLE
Xiaomi Mi Smart Cube (not Aqara)

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#1198]
It is paired correclty but is not sending events to Home Assistant. Any clue/advice?

**Comment by chimpy** [comment]
What version of the software and firmware?

**Comment by Klagio** [comment]
. 58 and 12 December firmware)

**Comment by Klagio** [comment]
thats trhe model MFKZQ01LM

**Comment by manup** [comment]
Which version is shown for the cube in the Phoscon App? I guess this is the Aqara version with newer date code.

**Comment by Klagio** [comment]
> Which version is shown for the cube in the Phoscon App? I guess this is the Aqara version with newer date code.

That's what is shown in the phoscon app ... I don't know how to look for model number elsewhere. Please note I bought it long ago, if I am not mistaken before Aqara brand came out (not 100% sure though)

**Comment by manup** [comment]
I mean which version is shown in the Phoscon App.
Here is my cube, it's the Xiaomi Mi version.

![image](https://user-images.githubusercontent.com/383386/52166911-a5bd0180-2713-11e9-9e0f-ff2253c30c3e.png)
