### ISSUE TITLE
I think its time you put XIaomi as manufacturer option for adding Sensor/Switches ... not OTHER

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#1199]

**Comment by manup** [comment]
Status update: The switches and sensor integration sections are in refactoring for more robustness and to easily support more devices. As for Xiaomi we'll add wizards for the battery powered devices.

**Comment by manup** [comment]
Small update on this, we are currently working on integration wizards for the most popular devices including Xiaomi.
