### ISSUE TITLE
deCONZ bugs for GLEDOPTO GL-C-007

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#1204]
LED Trading kindly provided me with a new loaner GLEDOPTO GL-C-007 RGBW controller.  Unlike the one in #952, this one doesn't show a superfluous 0x0C ZHA endpoint.  @manup: I don't think you've done anything yet to suppress the ZHA endpoint, haven't you?  This one has a _SW Build ID_ of 1.0.6 instead of 1.0.2, maybe that's the difference?
![screenshot 2019-02-01 at 14 46](https://user-images.githubusercontent.com/22179355/52126719-64075a80-2630-11e9-940c-25b79715a4b2.png)

It shows a _Basic_ cluster on both light endpoints.  The attributes are provided on both endpoints, but with a different value for _Model Identifier_ (like the Heiman Temperature/Humidity sensor):
- For 0x0B it's GL-C-007 (the RGBW model):
![screenshot 2019-02-01 at 14 51](https://user-images.githubusercontent.com/22179355/52126931-f27bdc00-2630-11e9-8410-55164d131e42.png)
- For 0x0F, it's GL-C-009 (the dimmer model):
![screenshot 2019-02-01 at 14 50](https://user-images.githubusercontent.com/22179355/52126949-fe679e00-2630-11e9-96ac-642597d0d058.png)

**Bug 1:** When watching the _Basic_ cluster in the GUI's _Cluster Info_ panel, I see the model number change when the REST API plugin polls the light.  It's as if the REST API plugin updates the cached ZCL values on both endpoints for each _Read Attributes Response_.  After disabling the REST API plugin, the values remain stable.

I see the same for the other clusters, the _OnOff_, _Level Control_ and even the _Color Control_ clusters.  Note the last cluster shouldn't be present on endpoint 0x0F (it's a _Dimmable Light_!), but luckily, it does report all attributes as unsupported.

I'm running v2.05.58.  I think this might be related to https://github.com/dresden-elektronik/deconz-rest-plugin/commit/a9c38bf111181a596febce77ffbdac2c1c620dd3, but maybe it's another issue that causes the missing values for `manufacturer`, `modelid`, etc. in the second light endpoint.  As with the previous model (with _Model Identifier_ of GLEDOPTO), there's a _Basic_ cluster on each light endpoint, supporting the corresponding attributes on both.

**Bug 2:** The _Color Control_ cluster on endpoint 0x0B doesn't support _Color temperature min_ nor _Color temperature max_:
![screenshot 2019-02-01 at 15 12](https://user-images.githubusercontent.com/22179355/52128229-af236c80-2634-11e9-8d5b-ea0350f51e55.png)
![screenshot 2019-02-01 at 15 12 1](https://user-images.githubusercontent.com/22179355/52128233-b185c680-2634-11e9-9f78-aa850076cf2a.png)
![screenshot 2019-02-01 at 15 12 2](https://user-images.githubusercontent.com/22179355/52128235-b34f8a00-2634-11e9-98c2-59ff0c87c281.png)
![screenshot 2019-02-01 at 15 13](https://user-images.githubusercontent.com/22179355/52128238-b480b700-2634-11e9-818f-3bce28f0406b.png)

deCONZ reports both as 0 (causing homebridge-hue to expose _Color Temperature_ with only 0 as allowed value, so it cannot be changed from HomeKit):
```json
{
  "ctmax": 0,
  "ctmin": 0,
  "etag": "81121203ead61bb849c64a0fb64927ff",
  "hascolor": true,
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-007",
  "name": "Light 4",
  "state": {
    "alert": "none",
    "bri": 1,
    "colormode": "xy",
    "ct": 500,
    "effect": "none",
    "hue": 1792,
    "on": true,
    "reachable": true,
    "sat": 253,
    "xy": [
      0.693599,
      0.296086
    ]
  },
  "swversion": "1.0.6",
  "type": "Extended color light",
  "uniqueid": "00:12:4b:00:1b:34:52:7f-0b"
}
```
The Hue bridge reports `capabilities.ct.max` as 65535 (the default value).

**Bug 3:** While the REST API plugin seems to understand correctly that the 0x0F endpoint doesn't do colour (no `state.xy`, `state.ct`, `state.hue`, `state.sat`, nor `state.effect`), even though it has a _Color Control_ cluster, it still exposes `state.colormode` and reports `hascolor` as true:
```json
{
  "etag": "2b8db715e2137034072d98c9cdec076a",
  "hascolor": true,
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-009",
  "name": "Light 5",
  "state": {
    "alert": "none",
    "bri": 0,
    "colormode": "hs",
    "on": false,
    "reachable": true
  },
  "swversion": "1.0.6",
  "type": "Dimmable light",
  "uniqueid": "00:12:4b:00:1b:34:52:7f-0f"
}
```

**Comment by ebaauw** [comment]
Both endpoints turn on when receiving _Move to Level (with On/Off)_ while they're off, but they don't turn off when receiving _Move to Level (with On/Off)_ to level 0 while on.  They even turn on when receiving _Move to Level (with On/Off)_ to level 0 when off.

**Comment by manup** [comment]
> @manup: I don't think you've done anything yet to suppress the ZHA endpoint, haven't you?

Correct, I've only added little code so that attributes are copied from basic cluster in all light resources.

>Bug 2: The Color Control cluster on endpoint 0x0B doesn't support Color temperature min nor Color temperature max:
>The Hue bridge reports capabilities.ct.max as 65535 (the default value).

I guess it makes sense to do the same, use 65535 unless value is available on the device.

>Bug 3: While the REST API plugin seems to understand correctly that the 0x0F endpoint doesn't do colour (no state.xy, state.ct, state.hue, state.sat, nor state.effect), even though it has a Color Control cluster, it still exposes state.colormode and reports hascolor as true:

Oh my :) we can add an exception (GLEDOPTO + Dimmable light) --> ignore color control cluster?

>Each endpoint turns on when receiving Move to Level (with On/Off) while it's off, but they don't turn off when receiving Move to Level (with On/Off) to level 0 while on. They even turn on when receiving Move to Level (with On/Off) to level 0 when off.

Not sure how to deal with this, seems to be a pretty messed up bug.

**Comment by ebaauw** [comment]
> we can add an exception (GLEDOPTO + Dimmable light) --> ignore color control cluster?

That would work, I suppose, but "if neither `xy` nor `ct` nor `hue`/`sat` --> no color" seems more generic.

> > Each endpoint turns on when receiving Move to Level (with On/Off) while it's off, but they don't turn off when receiving Move to Level (with On/Off) to level 0 while on. They even turn on when receiving Move to Level (with On/Off) to level 0 when off.

> Not sure how to deal with this, seems to be a pretty messed up bug.

In this case: in the GLEDOPTO firmware.  OSRAM has a similar bug in firmware V1.03.07.

For the latter, I created a workaround in homebridge-hue, to include `"transitiontime": 0` when PUTting `{"on": false}`, so deCONZ (and the Hue bridge) send _Off_ instead of _Move to Level (with On/Off)_.  I can easily set the same parameter for the GL-C-009/007.

For the GL-C-008, that doesn't turn on on _Move to Level (with On/Off)_, I created another workaround in homebridge-hue, not to collect multiple characteristic changes into a single REST API call.  So I'm sending `{"on": true}` and `{"bri": `_b_`}` as two separate PUTs, instead of a single `{"on": true, "bri": `_b_`}`, again preventing deCONZ (and the Hue bridge) from sending _Move to Level (with On/Off)_.

You might prefer workarounds in deCONZ, so all clients would benefit (although clients also catering for the Hue bridge might still need the workaround).  For this, I'm half planning to refactor the handling of PUTting `state.on` and `state.bri` to be more in line with the Hue bridge, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1111#issuecomment-456464872.  At least, for Hue lights; for non-Hue lights, we might take different actions (e.g. not assuming a default `transitiontime` of 4).

Rather than whitelisting each light, I would eventually want to model the light capabilities (or lack thereof), see https://github.com/dresden-elektronik/deconz-rest-plugin/pull/718#issuecomment-455766380.  Looks like the model should contain separate capabilities for turning on and turning off on receiving _Move to Level (with On/Off)_ (cf. `noTransitionTime` vs `noWaitUpdate` in homebridge-hue).

Any idea on bug 1?

**Comment by ebaauw** [comment]
For reference, here's what it looks like on the Hue bridge:
```json
{
  "capabilities": {
    "certified": false,
    "control": {
      "colorgamuttype": "other",
      "ct": {
        "max": 65535,
        "min": 0
      }
    },
    "streaming": {
      "proxy": false,
      "renderer": false
    }
  },
  "config": {
    "archetype": "classicbulb",
    "direction": "omnidirectional",
    "function": "mixed"
  },
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-007",
  "name": "Extended color light 1",
  "productname": "Extended color light",
  "state": {
    "alert": "none",
    "bri": 254,
    "colormode": "xy",
    "ct": 500,
    "effect": "none",
    "hue": 18176,
    "mode": "homeautomation",
    "on": true,
    "reachable": true,
    "sat": 1,
    "xy": [
      0.1904,
      0.7201
    ]
  },
  "swupdate": {
    "lastinstall": "2019-02-01T16:17:22",
    "state": "notupdatable"
  },
  "swversion": "1.0.6",
  "type": "Extended color light",
  "uniqueid": "00:12:4b:00:1b:34:52:7f-0b"
}
```
```json
{
  "capabilities": {
    "certified": false,
    "control": {},
    "streaming": {
      "proxy": false,
      "renderer": false
    }
  },
  "config": {
    "archetype": "classicbulb",
    "direction": "omnidirectional",
    "function": "functional"
  },
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-009",
  "name": "Dimmable light 1",
  "productname": "Dimmable light",
  "state": {
    "alert": "none",
    "bri": 1,
    "mode": "homeautomation",
    "on": true,
    "reachable": true
  },
  "swupdate": {
    "lastinstall": "2019-02-01T16:17:22",
    "state": "notupdatable"
  },
  "swversion": "1.0.6",
  "type": "Dimmable light",
  "uniqueid": "00:12:4b:00:1b:34:52:7f-0f"
}
```

**Comment by shadowtsw** [comment]
Do someone know if the SW-build could be update in any way ?

**Comment by ebaauw** [comment]
PR fixes bugs 2 and 3.  I have no clue what's causing bug 1.
```json
{
  "ctmax": 65535,
  "ctmin": 0,
  "etag": "188daeac4fa20454df2993bef2ee6137",
  "hascolor": true,
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-007",
  "name": "Light 3",
  "state": {
    "alert": "none",
    "bri": 1,
    "colormode": "xy",
    "ct": 500,
    "effect": "none",
    "hue": 18176,
    "on": true,
    "reachable": true,
    "sat": 1,
    "xy": [
      0.190433,
      0.720073
    ]
  },
  "swversion": "20180920",
  "type": "Extended color light",
  "uniqueid": "00:12:4b:00:1b:34:52:7f-0b"
}
```
```json
{
  "etag": "1c429e5136084201cf024bd728ab33b8",
  "hascolor": false,
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-009",
  "name": "Light 4",
  "state": {
    "alert": "none",
    "bri": 0,
    "on": false,
    "reachable": true
  },
  "swversion": "1.0.6",
  "type": "Dimmable light",
  "uniqueid": "00:12:4b:00:1b:34:52:7f-0f"
}
```

**Comment by ebaauw** [comment]
PR has a funny side-effect, probably related to bug 1.  The REST API plugin now issues a websocket notification that `colormode` has changed to `"xy"`, every time the light is polled.

**Comment by shadowtsw** [comment]
I don’t know if it’s matter, but it seems the manufacturer has changed their process. Since a few weeks they offer 1-ID and 2-ID devices. First one can just control rgb or w, the second one enables rgb and w at the same time.

**Comment by ebaauw** [comment]
There’s different Zigbee commands to turn off (or on) a light.  I sniffed how the Hue bridge translates REST API bodies to these commands, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1111#issuecomment-456464872, but I haven’t yet made the same overview for deCONZ.  I want to bring deCONZ more in line with the Hue bridge, but not all lights by other manufacturers might support the same commands as the Hue lights.  Or worse, they support them, but react differently.  I fear, deCONZ might need to take the light manufacturer into account, and send different commands to different lights.  Sorry, work in progress.
