### ISSUE TITLE
Lights unreachable at start with 2.05.58

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#1207]
Starting with 2.05.58 lights are `unreachable` when deCONZ starts? 
I do not know why this change has been done, but this is not nice behaviour with my plugin. Since long the plugin has the ability to restore light settings if they change from being unreachable to reachable.  This was done to work around power outages (given that an UPS was used) and such. Especially with Philips Hue behaviour it was used, but even now users want it for other brands.

So it now happens that lights go on if deCONZ is restarted and resets lights, where they should not be on at all. Is it possible to start deCONZ with the last known status instead of `unreachable?`

**Comment by manup** [comment]
>Starting with 2.05.58 lights are unreachable when deCONZ starts?

Yes this was done to mitigate another problem. Lights were reachable but couldn't be controlled until they were discovered again.

>Is it possible to start deCONZ with the last known status instead of unreachable?

Yes this is already on the 2.05.59 todo list, the issue was reported already.
The restore will be done like for sensors.

**Comment by wvuyk** [comment]
That sounds great to me! Thanks!

**Comment by manup** [comment]
>So it now happens that lights go on if deCONZ is restarted and resets lights, where they should not be on at all.

Just understood this part now. Big sorry, totally haven't thought about the impact on such features.

**Comment by MattL0** [comment]
This is not just that. 

When i restart deconz I have to mannually unplug some hue light before beeing able to control them again.

**Comment by wvuyk** [comment]
@MattL0 With a restart of deCONZ it can take a few minutes before the lights can be controlled. I can see the same here, it can take up to 3 minutes here before all lights respond. 
Does your Hue light stay uncontrollable after 5 minutes or so?

**Comment by MattL0** [comment]
Yes

**Comment by WhistleMaster** [comment]
Something related, somehow, with #1213 ?

**Comment by MattL0** [comment]
> @MattL0 With a restart of deCONZ it can take a few minutes before the lights can be controlled. I can see the same here, it can take up to 3 minutes here before all lights respond.
> Does your Hue light stay uncontrollable after 5 minutes or so?

5-8 minutes i think

**Comment by MattL0** [comment]
But,...In the phoscon app, some are ''unreachable'' after 25 mins. But i can control them with the grouping function.

**Comment by MattL0** [comment]
One hue light is not controlable at all after 25 minutes. This one has no group assigned.

**Comment by MattL0** [comment]
What firmware and deconz version do you recommend me to get a stable networks as before ( I do not remember) thanks

**Comment by MattL0** [comment]
Thanks manup!!

**Comment by MattL0** [comment]
with .58 

Removed the ability of my sensors to report light Level and temps. 

The lights seems to reachable a lot sooner !
