### ISSUE TITLE
Heiman SmartPlug new version

### ISSUE THREAD

**Issue by d-litvinov** [dresden-elektronik/deconz-rest-plugin#1222]
I've get new version of the Heiman SmartPlug and it dosn't show the power consumption information, but turning on/off works. I have an older version of the same plug and it works like a charm.

I use the latest version of deCONZ (V2_05_58).
Looks like it should be added in the whitelist, but I don't know how.

<img width="635" alt="screenshot 2019-02-05 at 16 19 30" src="https://user-images.githubusercontent.com/9209784/52276525-83b9be00-2963-11e9-988f-7ca110dd8c1c.png">
<img width="957" alt="screenshot 2019-02-05 at 16 17 20" src="https://user-images.githubusercontent.com/9209784/52276527-83b9be00-2963-11e9-9d65-9041fb1f5802.png">
<img width="961" alt="screenshot 2019-02-05 at 16 16 56" src="https://user-images.githubusercontent.com/9209784/52276528-84525480-2963-11e9-9e1e-62decd859dc4.png">
<img width="953" alt="screenshot 2019-02-05 at 16 16 36" src="https://user-images.githubusercontent.com/9209784/52276529-84525480-2963-11e9-9882-0dea7464b807.png">
<img width="962" alt="screenshot 2019-02-05 at 16 15 00" src="https://user-images.githubusercontent.com/9209784/52276530-84525480-2963-11e9-84e6-335b9c86ba1e.png">
[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2832268/deconz.log)

**Comment by d-litvinov** [comment]
logs here https://github.com/dresden-elektronik/deconz-rest-plugin/files/2832268/deconz.log

**Comment by d-litvinov** [comment]
I've just checked the master branch, and the plug now reports the power consumption. 
Thank you so much for such a quick fix!

**Comment by arnonel** [comment]
Hi - wasnt sure where to ask this

I have the Heiman HS2SK (UK Version)

How do you put it into pairing mode so that app can find it?
