### ISSUE TITLE
All light lost connection, sponanously!

### ISSUE THREAD

**Issue by posixx** [dresden-elektronik/deconz-rest-plugin#1226]
Hello,

I was running 2.05.58 for some days now, and an hour ago no light can be controlled anymore! All connections are gone somehow. Taps were working as i saw the socket events coming in on my homeseer. I tried downgrading to .54 but now i only have 1 connection left: one motion sensor is working, but all my lights are disconnected. What to do? 

Frans

**Comment by posixx** [comment]
![image](https://user-images.githubusercontent.com/2280400/52305614-d4e2a580-2995-11e9-8058-bf216ac28879.png)

This is the state currently, it found one motion sensor again. All hue lights.

**Comment by manup** [comment]
Have you tried power on/off the gateway? (not just reboot)

**Comment by posixx** [comment]
no will try soon, building latest from source now to see it that helps.. keep you posted

**Comment by manup** [comment]
I think the firmware is stuck not higher level deCONZ , easiest way to check this is to power on/off.

**Comment by manup** [comment]
Odd, can please create a fresh backup and send it to mpi@dresden-elektronik.de all network changes are stored in there.

I can check if this is a known bug (can be fixed manually).

**Comment by posixx** [comment]
really appreciated! just sent 2 backups, one form junu 2018 and one from a half hour ago. let me know if you got them as i don't know if .dat files are accepted at your end

**Comment by l-mb** [comment]
I think I'm seeing the same. All lights are unavailable, there's nothing in the UI and the web UX reports "not connected". I'd appreciate if you'd share how this can be fixed manually?

**Comment by posixx** [comment]
@i-mb: i'm seeing all lights in the web-ui and dezonz-gui, just no online one, all unreachable. don't know if this is the same as your problem..

**Comment by manup** [comment]
@posixx I've mailed you a workaround to fix the configuration, hope it works.

**Comment by manup** [comment]
>I think I'm seeing the same. All lights are unavailable, there's nothing in the UI and the web UX reports "not connected". I'd appreciate if you'd share how this can be fixed manually?

Not connected would be another problem. Can you please provide more details on your setup (versions/firmware)?

**Comment by posixx** [comment]
@manup you are a lifesaver. Your workaround works, currenly i see the network rebuilding connections again. Thanks for your quick help, i can shut down lights again when i go to bed:-)

**Comment by smallgreyrock** [comment]
Can you share the workaround? I'm seeing a similar or identical issue with my lights that just started last night.

Sensors/switches are still visible in the deconz web interface, but no lights are displayed or controllable, and they can't be re-added. The devices are still present in zll.db. Unfortunately I have no db backup to revert to.

This is with 2.05.57 (and .58 I guess) and firmware 0x26300500.

**Comment by l-mb** [comment]
Okay, same issue then - not connected might have been the wrong word. I can see them, but they flag as unavailable and I cannot perform any actions on them.

**Comment by manup** [comment]
2.05.59 is available now and contains a Zigbee configuration page to inspect and repair broken configuration.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59

**Comment by fillilutten** [comment]
I tried going back 2 versions when I know everything worked. But unfortunately it didn't help. Still can't reach some of my lights. The hue works great but the IKEA ones are still unreachable.

What I did was - revert back 2 versions to when it worked > rebooted my pi > turned on and off my IKEA bulbs > Still greyed out 

Hm. Anything I'm missing?

**Comment by manup** [comment]
>rebooted my pi

No need to reboot.

>Hm. Anything I'm missing?

When the Hues work but IKEA don't it is a indication that network settings are okay now but the IKEA lights might be on the wrong channel.

If you have a IKEA bulb near to the gateway you me check where it is:

* Phoscon App > Help > Open Wireless Light Control (2016)
* Menu > Settings > Scan for Devices

If the light can be found you can see on which channel/panid it is and if it is different from your current channel.

![image](https://user-images.githubusercontent.com/383386/52896936-8ff91300-31ce-11e9-9c0c-ddf5781539cd.png)

Note Hue lights detect a channel change on their own after a power cycle, IKEA lights sadly don't.

**Comment by fillilutten** [comment]
Thanks! You where right, it is on the wrong channel and also network id. Tried pushing the reset and then paired it again, it shows up as connected now but when changing brightness nothing happens.

**Comment by manup** [comment]
>it shows up as connected now but when changing brightness nothing happens.

It should work soon after the light joins. May take a few seconds in worst case minutes.

**Comment by fillilutten** [comment]
Just after a minut it's now back to greyed out. To me it seemed like the reset button didn't do anything, when I did reset and then scanned again for devices the bulb hade the same wrong network id and channel.

**Comment by manup** [comment]
Yeah IKEA reset can be a bit tricky.

I usually use the reset sequence, since it's most reliable:
* Start light search in Phoscon App
* Reset light as shown in the video https://www.youtube.com/watch?v=mJm9YpPrGzk
  (import toggle on/off quickly)
* When the light flickers, toggle on/off once more

**Comment by fillilutten** [comment]
Thanks so much @manup! It's now all up and running again. 
Wow you saved me so much time and effort, have a great weekend!

**Comment by manup** [comment]
:) cool glad that it works now.

**Comment by fillilutten** [comment]
Some deconz god doesn't like me :(

Was away a couple of hours. When I come back the whole apt lights up when I arrive, just as I've programmed. But after adding my newly bought Innr 120 I realize that all my IKEA bulbs are now gone from the UI. They work if I send a scene request but they are totally gone.

Can see them in HA but they don't do anything and my newly added power plug doesn't show up within HA.

**Comment by smallgreyrock** [comment]
> I think the firmware is stuck not higher level deCONZ , easiest way to check this is to power on/off.

Unplugging and reinserting the ConBee fixed things for me.

**Comment by manup** [comment]
>But after adding my newly bought Innr 120 I realize that all my IKEA bulbs are now gone from the UI.

Do you mean not visible in the deCONZ Node View or Phoscon App shown as not reachable?

By the way, which firmware version are you using?

**Comment by fillilutten** [comment]
> Do you mean not visible in the deCONZ Node View or Phoscon App shown as not reachable?
> 
> By the way, which firmware version are you using?

I'm running HassIO and the deCONZ addon and they are not visible in Phoscon Web UI. Not sure but I don't think there are any deCONZ Node View when using the deCONZ addon.
Running fw version 262F0500 conbee.

**Comment by manup** [comment]
>and they are not visible in Phoscon Web UI

I see, but do you mean not listed at all or they are listed but shown as reachable?

If they aren't listed at all there is something wrong with you configuration, since this should always work regardless of any Zigbee traffic. The lights, sensors and switches are just loaded from the database and should be shown even when no ConBee/RaspBee is attached.

 Is this running on a Raspberry Pi?

**Comment by fillilutten** [comment]
> > and they are not visible in Phoscon Web UI
> 
> I see, but do you mean not listed at all or they are listed but shown as reachable?
> 
> If they aren't listed at all there is something wrong with you configuration, since this should always work regardless of any Zigbee traffic. The lights, sensors and switches are just loaded from the database and should be shown even when no ConBee/RaspBee is attached.
> 
> Is this running on a Raspberry Pi?

Not listed at all, they are just gone, not in the old 'Open Wireless Light Control (2016)' or the "default mode". Haven't had the time to try and redo the reset > repair I did yesterday when all started working again.

Also tried to reinstall deconz addon and then backup from .dat save file but didn't make any difference.

Yes running on a Raspberry Pi 2.

**Comment by manup** [comment]
>Not listed at all, they are just gone, not in the old 'Open Wireless Light Control (2016)' or the "default mode". Haven't had the time to try and redo the reset > repair I did yesterday when all started working again.

>Also tried to reinstall deconz addon and then backup from .dat save file but didn't make any difference.

Something is not working here with the database, if devices are gone without doing anything. Note the backup can just work if it was created when everything still worked and devices were listed.

To me the question is, where is the data gone? Hard to tell. Possible reasons in the past:
* sd-card failure
* Multiple instances of deCONZ running (unlikely in default Hass.io install)

You may send me the backup file to mpi@dresden-elektronik.de I can check if at least device data was in there or as it looks like it is empty.

**Comment by rich710se** [comment]
Today suddenly all my zigbee devicesw stopped working, nothing happens, I have rebooted my rpi several times, pulled out my conbee stick. Powered my bulbs on and off, but nothing happens except that some xiaomi endpoints get connected. How can I find out what to do, my wife is very angry now ;) I have deconz 2.05.59 since the day it was released, have worked flawless since then.
![image](https://user-images.githubusercontent.com/38072363/53117295-dd68dd80-354a-11e9-9de9-9810985fcbbc.png)

**Comment by manup** [comment]
@rich710se  please check if the network configuration parameters are stable in the new Zigbee configuration page.

To open the page, follow the instructions from the release note: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59

**Comment by rich710se** [comment]
The page looks like this, nothing have happened over night still no connections. Are there more too look at, that is interesting for you?
![image](https://user-images.githubusercontent.com/38072363/53145062-116dee00-359f-11e9-9f7a-64376157d556.png)
![image](https://user-images.githubusercontent.com/38072363/53145074-1df24680-359f-11e9-8010-bf1f319e2d1c.png)

**Comment by rich710se** [comment]
Nothing happened when i took "Load" on the first entry, but I think that is because I tried to reinstall 2.05.59 yesterday after I lost it. So maybe I reverted back to that position. But when i took Load on my second entry in this list, every bulp started talking again!! :) Thanks alot!!.

**Comment by posixx** [comment]
Exactly, your PANID was changes, reverting back to the orginal one did the trick.

**Comment by manup** [comment]
>Exactly, your PANID was changes, reverting back to the orginal one did the trick.

This. 

Next firmware update should fix this issue to happen in first place.
