### ISSUE TITLE
FLS-PP lp support

### ISSUE THREAD

**Issue by Oliviakrkk** [dresden-elektronik/deconz-rest-plugin#1228]
Hi

Is dresden elektronik FLS-PP lp supported by deconz/phoscon? 

I am having issues adding it to my network :/.

**Comment by Hypfer** [comment]
Yes, it is supported.

**Comment by Oliviakrkk** [comment]
How to pair it?

**Comment by manup** [comment]
It can be added by just starting the light search.

If it doesn't join you need to reset the controller with the following sequence:

![image](https://user-images.githubusercontent.com/383386/52447196-5ec67600-2b30-11e9-99fb-44706b63d1d4.png)

**Comment by Oliviakrkk** [comment]
Ok it worked. Thanks!

**Comment by Maschler** [comment]
I have the same problem. FLS-PP3 SW:020E.201000A0

I cant find the light with Phoscon. But with the hue Bridge it works fine.
