### ISSUE TITLE
add support for Blaupunkt SCM-S1 roller shutter

### ISSUE THREAD

**Issue by steveknoefler** [dresden-elektronik/deconz-rest-plugin#1229]
Hello,
please add support for the Blaupunkt roller shutter scm-s1.

thanks
Steve

<img width="386" alt="bildschirmfoto 2019-02-07 um 19 51 34" src="https://user-images.githubusercontent.com/13857839/52435726-d4234e00-2b12-11e9-8339-4c58e72a82e4.png">
<img width="243" alt="bildschirmfoto 2019-02-07 um 19 51 51" src="https://user-images.githubusercontent.com/13857839/52435728-d4bbe480-2b12-11e9-841b-847b93136209.png">
<img width="175" alt="bildschirmfoto 2019-02-07 um 19 52 01" src="https://user-images.githubusercontent.com/13857839/52435729-d4bbe480-2b12-11e9-990e-8cfd045be925.png">
<img width="393" alt="bildschirmfoto 2019-02-07 um 19 52 31" src="https://user-images.githubusercontent.com/13857839/52435730-d4bbe480-2b12-11e9-8649-b5d9ea167a5f.png">
<img width="393" alt="bildschirmfoto 2019-02-07 um 19 52 55" src="https://user-images.githubusercontent.com/13857839/52435731-d4bbe480-2b12-11e9-9df5-3155fe065cd3.png">
<img width="481" alt="bildschirmfoto 2019-02-07 um 19 55 06" src="https://user-images.githubusercontent.com/13857839/52435733-d5547b00-2b12-11e9-8a54-93b61f060bca.png">
<img width="481" alt="bildschirmfoto 2019-02-07 um 19 55 39" src="https://user-images.githubusercontent.com/13857839/52435735-d5547b00-2b12-11e9-9618-2ef7a7780c6a.png">

**Comment by ebaauw** [comment]
@steveknoefler It is already exposed by the REST API as `/lights/26`.I don’t think there’s anymore we can do, unless there something useful in cluster 0x0100.

**Comment by ebaauw** [comment]
0x0100 is _Shade Configuration_.  No cluster-specific commands, but a number of cluster-specific attributes:

Id | Name | Type | Range | Access | Default | M/O
-- | -- | -- | -- | -- | -- | --
0x0000 | PhysicalClosedLimit | uint16 | 0x0001 – 0xfffe | Read Only | - | O
0x0001 | MotorStepSize | uint8 | 0x00 – 0xfe | Read Only | - | O
0x0002 | Status | map8 | 0b0000 xxxx | Read/Write | 0b0000 0000 | M
0x0010 | ClosedLimit | uint16 | 0x0001 – 0xfffe | Read/Write | 0x0001 | M
0x0011 | Mode | enum8 | 0x00 – 0xfe | Read/Write | 0x00 | M

I don't think exposing them through the REST API would be of much value, but it would make sense to include them in general.xml, so they can be queries and set through the deCONZ GUI.

**Comment by steveknoefler** [comment]
oh sorry my mistake its now working :)

**Comment by sammy98** [comment]
I have a hard time to get it working. 
It is paired as light but i cannot trigger up and down and dont see the current position of the device.

![shade](https://user-images.githubusercontent.com/927070/71883748-55c29800-3137-11ea-834d-236817ce6b2a.png)

Any hints for me?
