### ISSUE TITLE
daylight sensor (built in)

### ISSUE THREAD

**Issue by OstertagM** [dresden-elektronik/deconz-rest-plugin#1243]
I have a question to the values that this sensor is posting.
What are the valid values for the "Status" state with description?
thanks

**Comment by manup** [comment]
They are not documented yet, but the related header file has some descriptive defines:

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/daylight.h

**Comment by OstertagM** [comment]
Many thanks :-)
