### ISSUE TITLE
NYCE Door/Window Sensor NCZ-3011-HA

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/deconz-rest-plugin#1245]
Hello,
According to issue #548, it looks like this device was suppose to gain Phoscon support in 2.05.57. I'm running 2.05.58, but I cannot get this to show in Phoscon. I can see it in deconz. Is there a special joining procedure? Or for those that have successfully discovered this device with Phoscon, do you have any advice or suggestions?

Thanks!

**Comment by bdickhaus** [comment]
Issue 548 was only for the ceiling motion sensor NYCE NCZ-3043-HA. Each of the NYCE sensors has to be defined in deCONZ. There is also the garage door tilt sensor NYCE NCZ-3014-HA. I have one of those but haven't taken the time to capture all the info yet.

**Comment by stevenwfoley** [comment]
That's how 548 started, but one of the posts asked about support for the 3011 device and the release notes for 2.05.57 say it added support for both NYCE devices, so I assumed it was because of 548. The supported devices wiki also says its supported.

**Comment by manup** [comment]
Can you please provide the device info as described in the  wiki:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

Currently there is code for the following two sensors:

    { VENDOR_NYCE, "3011", emberMacPrefix }, // NYCE door/window sensor
    { VENDOR_NYCE, "3043", emberMacPrefix }, // NYCE ceiling motion sensor

This indicates the NCZ-3011-HA should work but I can't test it here since I don't own the sensor.

**Comment by wvuyk** [comment]
> Hello,
> According to issue #548, it looks like this device was suppose to gain Phoscon support in 2.05.57. I'm running 2.05.58, but I cannot get this to show in Phoscon. I can see it in deconz. Is there a special joining procedure? Or for those that have successfully discovered this device with Phoscon, do you have any advice or suggestions?
> 
> Thanks!

How does the sensor show in deCONZ? As 0xnnnn or as "name nn"?

**Comment by stevenwfoley** [comment]
Here is the requested info from deCONZ. Please let me know if you need any further info. And thanks for adding support!

![nodeinfo](https://user-images.githubusercontent.com/37962790/52602589-48bafd00-2e31-11e9-8348-a64af2a75606.JPG)
![clusterbasic](https://user-images.githubusercontent.com/37962790/52602603-507aa180-2e31-11e9-9678-46d5efcb924e.JPG)
![clusterpower](https://user-images.githubusercontent.com/37962790/52602607-53759200-2e31-11e9-8249-08da0ce8ff6b.JPG)

**Comment by bdickhaus** [comment]
This is for the tilt sensor NYCE NCZ-3014-HA

![capture0](https://user-images.githubusercontent.com/31450833/52660334-79e90b00-2ecd-11e9-8f42-4f7c27826889.JPG)
![capture1](https://user-images.githubusercontent.com/31450833/52660335-7a81a180-2ecd-11e9-8106-583e6151d167.JPG)
![capture2](https://user-images.githubusercontent.com/31450833/52660337-7a81a180-2ecd-11e9-93ef-44ac8b9e71ca.JPG)
![capture3](https://user-images.githubusercontent.com/31450833/52660338-7a81a180-2ecd-11e9-9625-aaf97d325cea.JPG)
![capture4](https://user-images.githubusercontent.com/31450833/52660340-7b1a3800-2ecd-11e9-89da-57dfc34d296f.JPG)
![capture5](https://user-images.githubusercontent.com/31450833/52660341-7b1a3800-2ecd-11e9-9e1f-600f8e123789.JPG)
![capture6](https://user-images.githubusercontent.com/31450833/52660342-7b1a3800-2ecd-11e9-97fa-e796beb15068.JPG)

**Comment by manup** [comment]
Thanks the NCZ-3014-HA garage door/tilt sensor is added now.

@stevenwfoley unfortunately the basic cluster doesn't show the needed attributes like modelid. Can you make another screenshot after reset and pairing the sensor again. This should populate the attributes.

**Comment by stevenwfoley** [comment]
So after resetting the NCZ-3011-HA door/window sensor device a couple times, it joined the network and showed up in Phoscon as expected. I've included updated screenshots for completeness.

![clusterbasic](https://user-images.githubusercontent.com/37962790/52681837-5c3a9680-2f0b-11e9-939b-8890013f2908.JPG)
![clusterpolecontrol](https://user-images.githubusercontent.com/37962790/52681868-80967300-2f0b-11e9-8544-813879cf6eae.JPG)
![clusterzone2](https://user-images.githubusercontent.com/37962790/52681869-80967300-2f0b-11e9-8cae-20a33827db47.JPG)
![clusterzone1](https://user-images.githubusercontent.com/37962790/52681870-80967300-2f0b-11e9-9687-9ce8031545b5.JPG)
![clusteridentify](https://user-images.githubusercontent.com/37962790/52681871-80967300-2f0b-11e9-8c21-0cdf9e90840a.JPG)
![clusterpower](https://user-images.githubusercontent.com/37962790/52681872-80967300-2f0b-11e9-86ab-ca3639a896d8.JPG)
![nodeinfo](https://user-images.githubusercontent.com/37962790/52682063-26e27880-2f0c-11e9-9800-41a1cb08d85a.JPG)
