### ISSUE TITLE
Strange available/unavailable issue with Sengled Element bulb

### ISSUE THREAD

**Issue by marthoc** [dresden-elektronik/deconz-rest-plugin#1252]
I'm seeing a strange problem with a Sengled Element BR30 bulb - it shows as reachable for 5 minutes, then unreachable for 5 minutes, back and forth, constantly. I think these bulbs are end-devices only and not routers. At this point I think the bulb is defective, but I wasn't sure if they constant pattern could demonstrate a problem that is traceable to deCONZ.

**Comment by JSkier21** [comment]
I have two as well. They worked for a couple of days, then unavailable for awhile, sometimes available. Sometimes one works and the other is still unavailable.
