### ISSUE TITLE
Dim group

### ISSUE THREAD

**Issue by halloamt** [dresden-elektronik/deconz-rest-plugin#1254]
Hi,

thanks for making deConz great :-)
Is there a possibility to send a dim up or dim down command to a group? That would make dimming a scene via API a lot more beautiful as not all lights would get the same level of brightness but brightness stays relative to the original scene definition. I'd love to add that to the REST plugin but I cannot write C :-(

Greetings from the Black Forest

**Comment by manup** [comment]
Thanks :)

It's not documented but you can send a `action.bri_inc` to a group.
Range is `-254 .. 254`

    PUT /api/<apikey>/groups/<id>/action
    
    { "bri_inc": 25 }

**Comment by halloamt** [comment]
Perfect, thanks :-)
Another PR for iobroker.deconz is coming soon...
