### ISSUE TITLE
Relay switch compatibility

### ISSUE THREAD

**Issue by mredz** [dresden-elektronik/deconz-rest-plugin#1257]
To the support team,
I'm super happy with the Conbee so far thanks. 
I have this switch:
https://www.ebay.com.au/itm/Zigbee-OnOff-Controller-Single-Channel-Smart-Switch-For-Amazon-Alexa-SmartThings/263804968596?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
It is working great except for one confounding thing. It switches on and off then on and off then on and off again remaining in the state that it started in. The light in Phoscon switches on and off with the fluctuations accordingly. It is also coming up as a light and not a switch but that is not a huge issue. It seems like it is super close to being compatible? Is there anything I can do on my side to tweak it to work?
![zig-switch](https://user-images.githubusercontent.com/9872183/52768853-53b49e00-307a-11e9-8c3d-4cabe82cf0f5.png)
Edit: Just to clarify when I click on the light switch to turn the relay on in Phoscon it switches on and off three times and finishes back in the off position.

**Comment by Smanar** [comment]
It works on your side ?
Another person is trying too, but the device still supplies power in off or on state > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1090

**Comment by mredz** [comment]
Actually I’ve not tested something on the relay yet so it may be started and finishing in the on position rather than the other way round but I can definitely hear it clicking on and off. So the trigger is working it’s just occurring too many times.

**Comment by mredz** [comment]
Ok just to clarify this. I have put a light on the relay. The device will switch anywhere from 3-6 times. Sometimes returning the unit to an on state and sometimes an off state. There doesn't seem to be any rhyme or reason to how many times it will fluctuate.

**Comment by manup** [comment]
Closing this issue, please continue discussion in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1090
