### ISSUE TITLE
Restoring from one host to another

### ISSUE THREAD

**Issue by Shaolo** [dresden-elektronik/deconz-rest-plugin#1259]
I was doing some testing tonight by moving the conbee from the π to a windows box. When I logged in to Phoscon some of the devices are missing their names. Instead they have default "Light xx" names. There are also additional groups, lights are in the wrong groups, etc.
I did a restore from the backup I made immediately before disconnecting the Conbee and no change. Same weird data.

I moved the Conbee back to the Π and everything is still there and operating as expected. Nodes have the correct names.

Is this form of restore supported or still in beta?

My ultimate goal is to move off the Pi to a Mac VM running Ubuntu. I was hoping I could move devices, do a restore and hit the ground running.

**Comment by manup** [comment]
Yes normally this shouzld work, not sure why it doesn't work in your setup.

You can also just copy the zll.db file from the pi into Ubuntu (deCONZ must be closed first).

For the related paths use:

    find  /home -name zll.db
