### ISSUE TITLE
Double Press being registered on single press (Xiaomi WXKG01LM)

### ISSUE THREAD

**Issue by wlatic** [dresden-elektronik/deconz-rest-plugin#1262]
Have just updated to the latest deconz

Version 2.05.58 / 30/01/2019
Firmware 262F0500

and now I'm getting double clicks registered on single clicks of the button.

{"event_type":"deconz_event","event":{"id":"switch_2","event":1003}}
In addition to this two of the events are being registered each time.

**Comment by ebaauw** [comment]
x003 is release (after hold, aka long release).  Typically it's preceded by a x001 (hold).  Double press is x004.  See https://github.com/dresden-elektronik/deconz-rest-plugin/blob/4c37242fe13753c066ff9cbc4bc8dc0c07c9e8ab/sensor.h#L22-L32.

**Comment by wlatic** [comment]
Sorry.

So its registering a long hold, rather than a single press.

**Comment by wlatic** [comment]
Looks like the newest released version of the software resolves this.
