### ISSUE TITLE
Lights in Supported Devices wiki

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/deconz-rest-plugin#1265]
Hello,
I was just curious why lights are not listed on the Supported Devices wiki page?
Is that intentional, or do we just need to help by submitting our known working lights so they can be added?

**Comment by manup** [comment]
Main reason is that most of the lights work out of the box and don't need special integration.
Also there are so many lights that it is hard to list all of them and their variants.

However it makes sense to at least describe this in a small light section, I'll add that to the wiki.

**Comment by stevenwfoley** [comment]
That makes sense.
Thank you.
