### ISSUE TITLE
deCONZ Homebridge Service no longer starts with v2.05.59

### ISSUE THREAD

**Issue by saurabh984** [dresden-elektronik/deconz-rest-plugin#1266]
deconz homebridge integration doesn't start or show any logs after upgrading to v2.05.59.

How do I get more debug logs?

**Comment by manup** [comment]
Ah sorry we did forgot the latest commit. I've updated the Raspbian package:

https://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.05.59-qt5.deb

Guess the service needs to be restarted afterwards.

To debug the homebridge script you can raise the debug level in `/usr/bin/deCONZ-homebridge.sh`

**Comment by saurabh984** [comment]
Still no luck

`Feb 15 16:40:59 deconz deCONZ-homebridge.sh[10876]: /usr/bin/deCONZ-homebridge.sh: line 244: syntax error near unexpected token `done'
Feb 15 16:40:59 deconz deCONZ-homebridge.sh[10876]: /usr/bin/deCONZ-homebridge.sh: line 244: `#011#011#011done'
F`

**Comment by saurabh984** [comment]
Changed the file `/usr/bin/deCONZ-homebridge.sh` with latest in git fixed it!

**Comment by manup** [comment]
Yes commit is (should be) also in the updated package :)
