### ISSUE TITLE
curl is an undocumented dependency

### ISSUE THREAD

**Issue by joubbi** [dresden-elektronik/deconz-rest-plugin#1268]
I am running deconz on a minimal debian.

I noticed this in `/var/log/syslog`:
`deCONZ-update2.sh[249]: /usr/bin/deCONZ-update2.sh: line 49: curl: command not found`

I did an `apt install curl` to fix it.
I think this should at least be mentioned in the README.md if it's not possible to handle the dependency by the installation.

**Comment by manup** [comment]
Interesting didn't know there are distributions (or variants) without curl out there.
I'll add it to the package dependencies.

**Comment by manup** [comment]
Dependencies are added now, will be available in 2.05.60.
