### ISSUE TITLE
Each time I reboot my raspberry pi, I do need to type deCONZ to make it start, anyway to make it start automatically after reboot?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#1269]
Sorry Linux newb here

**Comment by Smanar** [comment]
On my side I have created a deCONZ.desktop file, with the same content than the /usr/share/applications/deCONZ.desktop file.

But don't work on headless system.

**Comment by manup** [comment]
You need to enable the deconz.service (headless) or deconz-gui.service (gui)

https://github.com/dresden-elektronik/deconz-rest-plugin#headless-support

**Comment by Klagio** [comment]
> Are you using headless mode ?
> On my side I have created a deCONZ.desktop file (in ~/.config/autostart), with the same content than the /usr/share/applications/deCONZ.desktop file.
> 
> But don't work on headless system.

no I use GUI

**Comment by Klagio** [comment]
> You need to enable the deconz.service (headless) or deconz-gui.service (gui)
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin#headless-support

so I have to do this?

sudo systemctl enable deconz-gui

**Comment by manup** [comment]
Yes. But since you are running under a different user now you might need to edit the systemd service, since it will start deCONZ as user with id 1000 (which is pi).

    sudo systemctl edit deconz-gui

Add line:

    User=<username>

**Comment by Klagio** [comment]
> Yes. But since you are running under a different user now you might need to edit the systemd service, since it will start deCONZ as user with id 1000 (which is pi).
> 
> ```
> sudo systemctl edit deconz-gui
> ```
> Add line:
> 
> ```
> User=<username>
> ```

Ok, just to make sure I understand, I did
sudo systemctl edit deconz-gui

but it comes an empty file. Is that correct? Then I will add 
User=pi

**Comment by manup** [comment]
>Ok, just to make sure I understand, I did
sudo systemctl edit deconz-gui
but it comes an empty file. Is that correct? Then I will add
User=pi

Yep, that should work (but frankly I never testet this myself).

**Comment by Klagio** [comment]
> Are you using headless mode ?
> On my side I have created a deCONZ.desktop file (in ~/.config/autostart), with the same content than the /usr/share/applications/deCONZ.desktop file.
> 
> But don't work on headless system.

Hi, I did this, and it works. Only pèroblem that it is needed to put credentials at start (user and password) makinng it not ideal since it still needs human interaction to make it start. 

YOu have same problem, or how did you solve?

**Comment by Smanar** [comment]
This method is not the easier ^^.
But no, I don't need to type user and password. You are speaking for deconz or phoscon ? Deconz never ask for password.

**Comment by Klagio** [comment]
> This method is not the easier ^^. The @manup one don't works for you ?
> But no, I don't need to type user and password. You are speaking for deconz or phoscon ? Deconz never ask for password, it s not your system that ask that ?

Debian

**Comment by Smanar** [comment]
I think it's from your system configuration and I don't know Unix at all.
Try just with enabling the service

`$ sudo systemctl enable deconz-gui`

**Comment by mmarras** [comment]
> You need to enable the deconz.service (headless) or deconz-gui.service (gui)
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin#headless-support

Link update: 
https://github.com/dresden-elektronik/deconz-rest-plugin#headless-support-for-linux
