### ISSUE TITLE
[Device Support Request] Sinope 600W Smart Dimmer - DM2500ZB

### ISSUE THREAD

**Issue by ericvandamme** [dresden-elektronik/deconz-rest-plugin#1272]
Hello,

I am requesting support for the [Sinope 600W Smart Dimmer](https://www.sinopetech.com/en/product/smart-dimmer-600-w-zigbee/). I have managed to make everything work via deCONZ, but it won't pair through Phoscon. It is, as far as all my searching has came up with, the only reasonably priced Zigbee switch certified for Canada Electrical code using 120V. It is also a very strong repeater with a strong connection to all Zigbee devices in my home and its compact form factor easily fits in the smaller electrical boxes found in older homes.

*Special Note, it wouldn't join the network unless I read Basic info during the pairing process. I would be more than happy to repeat the process to provide any additional information as required.

Thank you very much for your consideration.
![nodeinfo](https://user-images.githubusercontent.com/28657401/52894592-ea1bb900-3179-11e9-93bf-48d1c3640496.PNG)
![clusters](https://user-images.githubusercontent.com/28657401/52894593-ee47d680-3179-11e9-8a57-8d46f15a1c51.PNG)
![cluster0000](https://user-images.githubusercontent.com/28657401/52894595-f0aa3080-3179-11e9-95a4-259212fa95f7.PNG)

**Comment by manup** [comment]
Some Zigbee details in the SmartThings device driver: 

https://www.sinopetech.com/wp-content/uploads/2018/05/Sinope-Technologies-DM2500ZB-SVN-365.txt

To my understanding:
* The device can be supported as dimmable light
* Supports reporting for On/Off and Level Control cluster 
* Does not provide capabilities to remote control other lights

**Comment by ericvandamme** [comment]
Tested with DeCONZ in version 2.05.60 and the device is working as expected.
