### ISSUE TITLE
Add daylight control

### ISSUE THREAD

**Issue by ronaldvans** [dresden-elektronik/deconz-rest-plugin#1276]
While using Phoscon I can't add a daylight control using the build in sensor. In "Create sensor control" and selecting "Daylight control" the Create button is grayed out irrespective of text in the Name box.

**Comment by choogendoorn** [comment]
Yup, same here

**Comment by 1968-Larry** [comment]
Me too...

**Comment by sajox** [comment]
Same here. 
Also tried to enable the "network service" in the old webapp without result. Reboot doesent help either.

**Comment by RDG88** [comment]
Same for me

**Comment by ronaldvans** [comment]
@manup, any ideas how we can enable this through the Phoscon app?

**Comment by manup** [comment]
Hi, sorry the button is misleading and will be removed or hidden in next versions.

The truth is this feature isn't implemented in the Phoscon App yet. There is only an older version of a daylight control in the old WebApp but I don't recommend it anymore.

Albeit a new proper daylight control is on the todo list for a long time now, we don't have an ETA for it.

**Comment by pilotniq** [comment]
The button is still there in the latest version which I installed today, November 19, 2019.
