### ISSUE TITLE
ZSHARK capture to file

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#1281]
I'm running ZSHARK on a dedicated Raspberry Pi, but WireShark on my macBook.  I'd like to run ZHARK continuously, even when I'm on the road with my macBook.  Would it be possible for ZSHARK to write the packets directly to a `.pcapng` file, rather than streaming them over the network to WireShark?  Maybe getting rid of the ZigBee encapsulation, to see the IEEE 802.15.4 Acks correctly?  Maybe with an option to start a new file every _x_ packets or _x_ hours?

**Comment by manup** [comment]
Perhaps this can be done, with libpcap. There will be a small update to ZSHARK in the coming weeks, I'll put it on the check list.

Note you can also run Wireshark directly on the Raspberry Pi and just save the file there or better to  an usb storage :)

**Comment by ebaauw** [comment]
Thanks.

Is zshark available thru the apt repository?

**Comment by manup** [comment]
It's not yet included, but it will be in the near future for all supported platforms.
