### ISSUE TITLE
Cannot create a backup

### ISSUE THREAD

**Issue by iamkarlson** [dresden-elektronik/deconz-rest-plugin#1283]
Hi, I'm using version 58 and I haven't tried to create a backup in any other version. I go to the settings and click backup and then nothing happens but red cross with a "close" button. How can I find an issue and possibly solve it?

**Comment by manup** [comment]
Can you also try with 2.05.59?

If it still doesn't work some more details would be helpful.

* Operating system
* If Linux which is the environment?
  Docker, Hass.io or started via systemd gui or headless mode?

**Comment by iamkarlson** [comment]
Hi, 
After some investigation, I found that RaspBee was out of the network. So, that's the reason. However, it would be great if I know that from the error message rather than digging into all system components. What do you think?

**Comment by manup** [comment]
Indeed, that should be improved. The reliance on connected Zigbee network isn't needed anymore since the related data is stored in the database anyway.

Will put this on the todo list.

**Comment by iamkarlson** [comment]
Thanks @manup
