### ISSUE TITLE
GLEDOPTO GL-S-007Z (GU10)

### ISSUE THREAD

**Issue by wrenchse** [dresden-elektronik/deconz-rest-plugin#1284]
2.05.59
The Gledopto Soposh Dual White and Color GU10 spotlights are added as two lights. 
Color works fine, but using color temperature, the lights turn off whenever brightness is set using either of the lights. 

The first light added, with Vendor GLEDOPTO, does no even allow to switch to color temp mode. The other light, Vendor: Unknown, does allow for color temp. 

Setting the color temperature works as intended, but touching brightness turns the light off. If then changing color temp the light will turn back on at the correct brightness.

My theory is that since the first of the two lights lacks the color temp mode, the brightness change of the other lamp will set the first one to 0.

Note this is using Phoscon. Let me know if you want me to check something in the cluster-view.

Hue hub v2 handles these spots correctly, which is the only reason I still have a hue hub lying around. I also have have a Soposh E27, unsure what the model number is, but that bulb has the same issue.

**Comment by Ronoon** [comment]
For advice to the issue please read the following link and send the requestet documentation to this issue for the programmer to inspect
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support
