### ISSUE TITLE
Bosch in wall light controller

### ISSUE THREAD

**Issue by jasase** [dresden-elektronik/deconz-rest-plugin#1285]
Does anyone has any experiences with the Bosch in wall light controller?
[https://www.bosch-smarthome.com/de/de/produkte/smart-system-solutions/lichtsteuerung](https://www.bosch-smarthome.com/de/de/produkte/smart-system-solutions/lichtsteuerung)

**Comment by manup** [comment]
The referenced controller seems to use 868,3 MHz and 869,5 MHz frequencies, unfortunately this is not Zigbee and won't work with deCONZ.

**Comment by Spy-1** [comment]
Bosch Smart Home System verwendeten Zigbee Funkprotokoll 868 MHz; 2,4 GHz !!
