### ISSUE TITLE
Configuration reverts

### ISSUE THREAD

**Issue by titanous** [dresden-elektronik/deconz-rest-plugin#1287]
Whenever I restart deCONZ, the names of my devices/groups revert to a previous configuration (it's always the same). Not sure what debugging information would be helpful, there's no information in the logs that is obviously useful.

Version: 2.05.59

**Comment by manup** [comment]
Which operation system/environment is deCONZ running in?

Might be related to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1288

**Comment by titanous** [comment]
Linux amd64, using the non-HASS Docker image.

**Comment by baranovoleg** [comment]
I am very excuse, but @titanous may you review this https://github.com/tent/http-link-go/pull/2 ?

**Comment by rafadesu** [comment]
I have the same issue. Let me know if I can help debugging it.

**Comment by titanous** [comment]
Root cause figured out in #1697.
