### ISSUE TITLE
deCONZ doesn't accept key after restart

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#1288]
Hi @manup 

Sometimes users get a really weird behaviour in deCONZ that after a restart of deCONZ it doesn't accept previously registered key. Reregistering with deCONZ after restart makes everything work again.

https://community.home-assistant.io/t/deconz-integration-hassio-0-88-all-disappeared-help/100691/12

**Comment by skeptizzle** [comment]
I'm one of the folks having this issue in the link above.

**Comment by manup** [comment]
I've checked the code, looks ok so far.
When a new api key is generated it is saved in the database in the next 5 seconds.

Can you check that the key is in the database after creation:

    sqlite3 zll.db 'select * from auth where apikey="B5EE783573"'

(replace with your apikey)

Then reboot, and check it it is still there.

**Comment by skeptizzle** [comment]
@manup where is the database and where do I input the command?

Thanks for your time!

**Comment by manup** [comment]
Just a quick check, I've logged in the hassio environment via ssh as described in https://developers.home-assistant.io/docs/en/hassio_debugging.html

To check where the zll.db is located:

    docker inspect -f "{{ .Mounts }}" addon_core_deconz
 
Accroding to the output the zll.db file is located in:

    /mnt/data/supervisor/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ

**Comment by skeptizzle** [comment]
Okay so, sorry for the late reply..
If i inspect the container for mounts i get:

```
root@dockerhost:~# docker inspect -f "{{ .Mounts }}" addon_core_deconz
[{bind  /usr/share/hassio/addons/data/core_deconz /data  rw true rprivate} {bind  /lib/modules /lib/modules  ro false rprivate}]
```

I get this when looking up the api key from core.config_entries in the zll.db
```
root@core-deconz:/# sqlite3 zll.db 'select * from auth where apikey="D35620B975"'
Error: no such table: auth
```

What's next, @manup? Your help is much appreciated, i already learned some nifty commands!

Cheers!

**Comment by hekm77** [comment]
I had same issue. HA 0.88.1. 
After removing the custom_updater component, deCONZ is working fine again.

**Comment by skeptizzle** [comment]
@hekm77 great find, have you reported it over there? I will try this tomorrow and report back..

Cheers

**Comment by hekm77** [comment]
@skeptizzle , This is not my find

https://community.home-assistant.io/t/deconz-official-thread/100504/6

**Comment by skeptizzle** [comment]
@hekm77 ok, but thanks anyway. It was nice of you to reply here.

**Comment by Kane610** [comment]
Some of these issues where affected by custom updater and the developer have taken steps to improve its performance. But there also was a bug with deCONZ component retry mechanism if getting a time out on start up. This will be fixed with Hass 0.89

**Comment by Kane610** [comment]
No action for 10 days, closing this issue

**Comment by nographix** [comment]
I have the same issue using homebridge
homebridge is running on RPi3
deconz is running on RPi4

does anyone know how to save the apikey?
The key gets lost after deconz restart.
Every power outage means that I cannot access to my zigbee network thru homebridge/homekit

I checked the database:
> sqlite3 zll.db 'select * from auth where apikey="xxxxxxxxxx"'
and got:
> Error: no such table: auth

**Comment by Mimiix** [comment]
That means the DB isn't there/not complete

Anyway, please open your own issue, as this issue is way to old @nographix
