### ISSUE TITLE
[Request device support] Sinope TH1300ZB floor heating thermostat

### ISSUE THREAD

**Issue by warrenmr** [dresden-elektronik/deconz-rest-plugin#1289]
https://www.sinopetech.com/en/product/smart-floor-heating-thermostat-3600-w-zigbee/

**Comment by warrenmr** [comment]
I will post more details once I receive the deCONZ stick.

**Comment by warrenmr** [comment]
![image](https://user-images.githubusercontent.com/47881637/54496006-6a335c80-48a7-11e9-8d3d-f46ef09199e3.png)

This is where the temperature is set:

![image](https://user-images.githubusercontent.com/47881637/54496028-9fd84580-48a7-11e9-9c03-69790d108dc4.png)

Node info:

![image](https://user-images.githubusercontent.com/47881637/54496052-dd3cd300-48a7-11e9-8630-36eb70521f4f.png)

**Comment by justinfanok** [comment]
Would love this as well

**Comment by the-speedmax** [comment]
Hello,
I already own a Conbee II. I'm looking to add some thermostat to my setup.
Do you know if this model can work with deconz? Sinope TH1123ZB & TH1124ZB 
These are Zigbee. 
https://www.sinopetech.com/en/product/smart-thermostat-for-electric-heating-3000-w-zigbee/?setLang=en
Tks for your help!
