### ISSUE TITLE
What is the REST-Plugin?

### ISSUE THREAD

**Issue by patrickjane** [dresden-elektronik/deconz-rest-plugin#1301]
Sorry if this might sound like a stupid question, but I am a bit confused what the core deCONZ debian package is, what on top of that the REST-plugin is, or what its good for?

I installed the debian package on my raspberry pi and started the deconz service, and now I can access the phoscon app, and also integrate deCONZ with my home assistant installation. I have not yet tried adding devices because currently I don't have deCONZ hardware.

But what would I need to compile and install the separate REST-plugin for?

**Comment by bdickhaus** [comment]
Not a stupid question, I was confused at first. The REST plugin is what phoscon, home assistant and many other packages use to communicate with deCONZ. It is included in the deCONZ package and you do not need to compile it.
