### ISSUE TITLE
Ubisys S2 firmware update instructions 

### ISSUE THREAD

**Issue by saurabh984** [dresden-elektronik/deconz-rest-plugin#1305]
Is there any instructions on how to do firmware updates using deCONZ for Ubisysy devices?

**Comment by ebaauw** [comment]
See #712.

**Comment by saurabh984** [comment]
Thanks @ebaauw 

Any idea what’s the difference between rms2 and fms2?

I’m assuming ‘rm’ is the DIN Rail module

**Comment by ebaauw** [comment]
I never decoded the full file name, beyond the obvious fields (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/712#issuecomment-465744443).  I used the _Image Type_ to select the right file, but deCONZ should be able to figure that out itself if you unpack the files to `~/otau`.

**Comment by saurabh984** [comment]
Hmm I did extract them in that folder but I still had to go manually select a file. I’m trying it with fms2

Is your dimmer DIN Rail or switch mounted one?

**Comment by ebaauw** [comment]
> I’m trying it with fms2

You should see the _Image_ in the STD OTAU plugin panel (press _Query_ when the S2 is selected in the panel).

> Is your dimmer DIN Rail or switch mounted one?

Switch mounted (the non-R version).
