### ISSUE TITLE
Know permit join is on via Websocket or via Api

### ISSUE THREAD

**Issue by sarakha63** [dresden-elektronik/deconz-rest-plugin#1313]
Hello

Is there any way to know that permit join is on or off or time left trough api.
The get config doesnt seem to give this information (and polling the api to have this info wouldnt be that good).

Could it be possible to send an event trough Websocket with the change of permit join state ?

Regards

**Comment by ebaauw** [comment]
If you GET `/lights/new` or `/sensors/new` while the network is open, it returns `{"lastscan": "active"}`.  Otherwise `lastscan` is `"none"` or the date of the last scan.  Afaik there's no web socket event for this (nor for any `/config` atttribute), so for now, polling is your only option here.
