### ISSUE TITLE
RaspBee Discovery is not finding my RaspBee

### ISSUE THREAD

**Issue by StreamsYT** [dresden-elektronik/deconz-rest-plugin#1315]
Hey guys,

im fairly new to all this Staff so hopefully i didnt do any stupid mistake.
I have installed on a RasperiPi a Raspian-Stretch version and install deconz for the Zigbee module following the instruction on the Github page. Works fine. But if i try the Discover call from 

https://dresden-light.appspot.com/discover

he is returning empty result. So he is not finding my Raspbee which i would expect.

**Comment by ebaauw** [comment]
Are you checking the URL from the host that runs deCONZ?  Discovery will fail if deCONZ registers using IPv6 and the discovery uses IPv4 or vice versa.  Try:
```
$ curl -6 https://dresden-light.appspot.com/discover
```
versus
```
$ curl -4 https://dresden-light.appspot.com/discover
```

If both fail: are you sure discovery is enabled?  In the old web app, it's _Internet Service_ under _Menu_|_Settings_ when you press _Enable Advanced Settings_.  I don't think the Phoscon app supports this.  In the REST API it's `/config/discovery`, but this is exposed only when the HTTP request header contains `Accept: vnd.ddel.v1`.
