### ISSUE TITLE
Userinterface

### ISSUE THREAD

**Issue by joecas1** [dresden-elektronik/deconz-rest-plugin#1317]
Hi experts,

is there any planing to split the UI into a normal user and an administrator one?
In addition to a lot of switches I‘m using the app as well to provide more scenes and give the possibility to create own colors. But because of misuse some of my kids are reconfigure groups and switches sometimes. 😜

Greetings from D-E hometown,
Joe

**Comment by Webserve** [comment]
Use Home assistant ? :-)

**Comment by joecas1** [comment]
> Use Home assistant ? :-)

no way ... ;-)
