### ISSUE TITLE
Aqara/Xiaomi Sensor inactiv 

### ISSUE THREAD

**Issue by Sturmhorst** [dresden-elektronik/deconz-rest-plugin#1318]
Hey Folks,

Sometimes my Aqara sensors are grayed out.
When I press the little button on the sensors they go back to the plain black status.

Why is this happend?

Kind regrets

**Comment by Sturmhorst** [comment]
Push

**Comment by Smanar** [comment]
Hello, they stop working too ? And you don't sill have the green line ?
It's the only one device you loose ?
Wich one deCONZ version are you using ?
