### ISSUE TITLE
Brightness Issue 

### ISSUE THREAD

**Issue by Sturmhorst** [dresden-elektronik/deconz-rest-plugin#1319]
Hey Folks,

sometimes the Lights won’t switch to the setted brightness.

I switch to 100% and the light is switch to 60% or 70% 

issue with:

IKEA, Hue and Innr

**Comment by Sturmhorst** [comment]
Push

**Comment by Smanar** [comment]
Hello, what are you using to set the bulb ? Phoscon ?
So you are using the slider, you put it on 100%, and you see the bulb is only at 60 %
