### ISSUE TITLE
Network Map scrolling

### ISSUE THREAD

**Issue by martynwendon** [dresden-elektronik/deconz-rest-plugin#1332]
Somehow I've ended up clicking on the network map on the deCONZ UI and "moved" it .... and now no amount of scrolling around seems to find the map.

Is there a way to "center" the map, or otherwise find it?

I know I can stop and restart deCONZ and it will re-center itself but that seems extreme!

![net_map](https://user-images.githubusercontent.com/1092273/54023121-05338480-418c-11e9-9285-cb779c971b2d.png)

**Comment by ebaauw** [comment]
> Is there a way to "center" the map, or otherwise find it?

Not as far as I know.  I would welcome such a feature.  I've had to resort to the "extreme" workaround of stopping and restarting deCONZ a couple of times, since I couldn't find the nodes anymore., even after zooming out all the way (scrolling down from the mouse).

**Comment by martynwendon** [comment]
Oh dear, I feared as much :-(

Please consider it a feature request if possible!

**Comment by manup** [comment]
Also internally a long requested feature :)

In the next weeks deCONZ will get a subtle face-lift to improve the currently cryptic toolbar.
A center and zoom to 100% button should be a useful addition.

**Comment by martynwendon** [comment]
Thanks, glad it's on the to-do list.  

Even if it were to simply recenter itself if the main window were to be minimised then maximised or otherwise resized, that would be good enough.

At the moment I am trying to painfully do a scroll / grid search to find it ..... I really don't want to restart if I don't have to!

**Comment by manup** [comment]
>At the moment I am trying to painfully do a scroll / grid search to find it ..... I really don't want to restart if I don't have to!

Just curious, what's so painful on restarting deCONZ? Should at most take just a few minutes until everything is discovered again.

**Comment by martynwendon** [comment]
No problem restarting as such, I'm just new to deCONZ though and reading through the issues list there's quite some reports about things not working well following a restart so was trying to avoid it if possible.

**Comment by ebaauw** [comment]
> Just curious, what's so painful on restarting deCONZ? Should at most take just a few minutes until everything is discovered again.

To name a few:
- Quite often, light and groups states are wrong until all lights have been polled.
- CLIPGenricFlag/Status sensors are set to false/0.
- Rules `timestriggered` are reset to 0.

**Comment by ebaauw** [comment]
> In the next weeks deCONZ will get a subtle face-lift 

Could you please also have a look at the OTAU plugin, in particular support sorting by selecting the column header, cf. the _Node List_ panel.

**Comment by manup** [comment]
Fair points, I guessfor lights/groups these can be improved by storing the current state to the database (already done but seems not to be complete). And restore this state properly.

`timestriggered` could be stored as well on large interval/restart.

>CLIPGenricFlag/Status sensors are set to false/0.

Here we could add logic to restore the last value when it is fresh enough, but maybe this is not desired and more preferable to get a clean state after restart.

>Could you please also have a look at the OTAU plugin, in particular support sorting by selecting the column header, cf. the Node List panel.

Absolutely

**Comment by lbschenkel** [comment]
I second the request to allow sorting by clicking on a header in the OTAU table. :-)

**Comment by JaumeMuste** [comment]
Is there an option to redraw the links between devices in a different way? For example, drawing it from the center of the box instead of the corner.

**Comment by kiat-huang** [comment]
+1 for centering the view and ideally a "fit in the screen" button.  And/or make the default canvas size a lot smaller - it seems to be about 100x too big, hence can easily lose one's work.  I understand someone may have 100s of devices (I'm about a 1/3 of the way there), but most users I'm pretty certain, will have 10-30 which should be easily findable.

**Comment by kiat-huang** [comment]
Is this still on the roadmap as mentioned?  Or is not, won't be, hence closed?

**Comment by Mimiix** [comment]
Still have this one open :( @donnib 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2997

**Comment by Mimiix** [comment]
@manup It's better to post this in #2997

**Comment by barts2108** [comment]
I am not sure of other people also noticed, but to me it seems that the zoom-in and zoom-out with the mousewheel works in the opposite way as nearly all other zoom that I know with mousewheel. For example, a webbrowser (Edge, Firefox)m notepad++, ms paint etc etc when you hold down Ctrl then the mousewheel forward is zoom in and mousehweel backward is zoom out.

In deCONZ, mousewheel forward is zoom out and bakward is zoom in

**Comment by rEs-84** [comment]
Might of zoomed or moved the nodes out of the view.
Still no way to reset the map/view back to normal? or locate a node on the map from double clicking it from the list?
