### ISSUE TITLE
Pairing Problems with Alexa

### ISSUE THREAD

**Issue by DarkEav** [dresden-elektronik/deconz-rest-plugin#1340]
I can't pair Phoscon with my Alexa.
First I turn on the connection mode in Phoscon, then i start looking for devices with Alexa but it wont find anything.

I'm using the Combee stick with my raspberry 3b+.
Phoscon Version: 2.05.59
Router: Fritz!Box 7590

**Comment by Smanar** [comment]
Hello, have you take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/759 ?
You have some tips to help you.

**Comment by Creatish** [comment]
Same for me L(
