### ISSUE TITLE
Phoscon Group exhibits unsupported light options to Home Assistant

### ISSUE THREAD

**Issue by capstan1** [dresden-elektronik/deconz-rest-plugin#1341]
Hi,
I just ran into a smaller issue. I have 2-lights-groups (made in phoscon) which group dimmable only lights. I connected Phoscon to Hassio using [this ](https://github.com/marthoc/hassio-addons/tree/master/deconz)addon.

When turning on the group, HA frontend displays light options that aren't available for this lights (white saturation and color).
Option for individual light:
![image](https://user-images.githubusercontent.com/17147867/54082487-ced64080-4316-11e9-88d9-edf888a2320c.png)

options for 2 equal lights grouped in phoscon:
https://user-images.githubusercontent.com/17147867/54071915-beb95500-4273-11e9-8c11-79beccc1ab01.png

However, the same group in phoscon doesn't show as having these attributes, I'm seeing the dimming slider only. So I think somehow the info Deconz is parsing for groups might be wrong.

Happy to give more info if needed!

**Comment by tleegaard** [comment]
Seems to be the same as https://github.com/dresden-elektronik/deconz-rest-plugin/issues/415
