### ISSUE TITLE
Running deconz on a loxberry

### ISSUE THREAD

**Issue by elmocito** [dresden-elektronik/deconz-rest-plugin#1344]
I try to run deconz on a [loxberry](https://www.loxwiki.eu/pages/viewpage.action?pageId=27100273) and get the following error codes after running _sudo service deconz-gui status_

`Mar 10 22:47:39 loxberry systemd[1]: deconz-gui.service: Failed with result 'exit-code'.
Mar 10 22:47:39 loxberry systemd[1]: deconz-gui.service: Service hold-off time over, scheduling restart.
Mar 10 22:47:39 loxberry systemd[1]: Stopped deCONZ: ZigBee gateway -- GUI/REST API.
Mar 10 22:47:39 loxberry systemd[1]: deconz-gui.service: Start request repeated too quickly.
Mar 10 22:47:39 loxberry systemd[1]: Failed to start deCONZ: ZigBee gateway -- GUI/REST API.
Mar 10 22:47:39 loxberry systemd[1]: deconz-gui.service: Unit entered failed state.
Mar 10 22:47:39 loxberry systemd[1]: deconz-gui.service: Failed with result 'exit-code'.
`

What is the problem? I read something about a "Pi user", but I cannot add another user to the Loxberry instance.

**Comment by wlatic** [comment]
Do you have the log where you saw the pi user error?

Also please provide the start up script you are using and the username you want to run deconz under.

**Comment by MBeeken73** [comment]
Hat jemand Deconz lauffähig auf einen loxberry?

**Comment by elmocito** [comment]
> Do you have the log where you saw the pi user error?
> 
> Also please provide the start up script you are using and the username you want to run deconz under.

Where do I get that?
