### ISSUE TITLE
Xiaomi vibration sensor; information leckage between deconz and Phoscon

### ISSUE THREAD

**Issue by heitec11** [dresden-elektronik/deconz-rest-plugin#1354]
Phoscon is only update the status with an vibration.
After 2 days the acuall status is not reachable.
![grafik](https://user-images.githubusercontent.com/44260876/54355342-26e3ae80-4659-11e9-9602-9fe3d60e14b4.png)

But deconz shows that the conection is still alive:
![grafik](https://user-images.githubusercontent.com/44260876/54355591-c2751f00-4659-11e9-91b8-e88e4ed1affd.png)

The value "lastupdated" shows the last "buttonevent".
Maybe 2 values are nessary. "lastupdated_buttonevent" and "lastupdated"

**Comment by MattL0** [comment]
I have 6 of those. But just added one to deconz. Most of the time it is showing that is is not reachable

**Comment by jerrychong25** [comment]
Similar issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1378
