### ISSUE TITLE
Missing battery level in Aqara Multisensor WSDCGQ11LM (2.05.60)

### ISSUE THREAD

**Issue by Mr-REM-Esq** [dresden-elektronik/deconz-rest-plugin#1358]
I installed the new firmware version and readded the sensors.
<img width="1021" alt="Снимок экрана 2019-03-15 в 16 23 25" src="https://user-images.githubusercontent.com/42520242/54434512-7bf9f000-473f-11e9-8cc3-433a77c21c4f.png">
<img width="1004" alt="Снимок экрана 2019-03-15 в 16 23 06" src="https://user-images.githubusercontent.com/42520242/54434535-8fa55680-473f-11e9-9528-2dea9d7ab64a.png">

**Comment by QonosSWE** [comment]
![xia](https://user-images.githubusercontent.com/47745541/55029168-ad10d500-5009-11e9-9e87-8999cf522a5a.png)

Same here, but the round sensor have battery status.

**Comment by Smanar** [comment]
Hello, just by curiosity, the problem was resolved by itself, or you have done something ?
I know someone with the same problem, all devices are goods except this one (and 2 time the same device).

**Comment by Mr-REM-Esq** [comment]
I completely deleted the old version of deconz and installed the new one (2.05.63).

<img width="1012" alt="Снимок экрана 2019-04-20 в 17 33 38" src="https://user-images.githubusercontent.com/42520242/56458687-9bb1b300-6392-11e9-98f6-a70f694c2eeb.png">

<img width="1036" alt="Снимок экрана 2019-04-20 в 17 29 56" src="https://user-images.githubusercontent.com/42520242/56458694-af5d1980-6392-11e9-9b39-874896d793b4.png">

**Comment by Smanar** [comment]
I know someone with this version too, but same bug
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1450

Perhaps the same problem than your problem update from the sensor that did not come within 3 hours.

**Comment by Mr-REM-Esq** [comment]
Yes, it looks probably.

**Comment by bcutter** [comment]
What was the "solution" for this?
