### ISSUE TITLE
Request adding of vibration state/attributes for Xiaomi Aqara Vibration Sensor in Home Assistant

### ISSUE THREAD

**Issue by jerrychong25** [dresden-elektronik/deconz-rest-plugin#1362]
Hi all,

I have added **Xiaomi Aqara Vibration Sensor** via deCONZ integration plugin into Home Assistant.

However, it show only **sensor.vibration_sensor_battery_level** for current entities, as per screenshot below:
![8345c44d6d96ef2e515d1ebe2bb3cf76b2ed69df](https://user-images.githubusercontent.com/15714095/54581379-60485f80-4a47-11e9-81b0-cd4897e4a0ba.png)

So, I can't access this sensor vibration state/attributes due to this problem.

Could deCONZ add this vibration sensor state/attributes into Home Assistant?

So that I could display this vibration sensor state/attributes into Home Assistant Home Page.

Thanks.

**Comment by WhistleMaster** [comment]
Have a look here [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748](url)

**Comment by jerrychong25** [comment]
> Have a look at #748

Looks like it does not have this option as mentioned in
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748#issuecomment-439899605:
![Capture](https://user-images.githubusercontent.com/15714095/54794893-c2da6f00-4c84-11e9-89b2-ab7321805961.JPG)

Possible have any changes by adding this vibration sensor state/attributes into HA soon?

**Comment by imbaimbaimba** [comment]
> > Have a look at #748
> 
> Looks like it does not have this option as mentioned in
> [#748 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748#issuecomment-439899605):
> ![Capture](https://user-images.githubusercontent.com/15714095/54794893-c2da6f00-4c84-11e9-89b2-ab7321805961.JPG)
> 
> Possible have any changes by adding this vibration sensor state/attributes into HA soon?

I'm also interested in getting it into Home Assistant. No clue whether it is possible or not?
Can we have an update on this? :)

**Comment by Kane610** [comment]
@imbaimbaimba see my latest comment in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748#issuecomment-476242634

**Comment by jerrychong25** [comment]
@Kane610,

Thanks for the updates.

So this fix will only appear on 0.90.2?

**Comment by Kane610** [comment]
> @Kane610,
> 
> Thanks for the updates.
> 
> So this fix will only appear on HA 0.90.2?

New features are not added in betas. 0.91

**Comment by jerrychong25** [comment]
> > @Kane610,
> > Thanks for the updates.
> > So this fix will only appear on HA 0.90.2?
> 
> New features are not added in betas. 0.91

Noted and thanks

**Comment by jerrychong25** [comment]
Since this issue no longer affect my Raspberry Pi performance, I will close this issue.
