### ISSUE TITLE
Request: add xiaomi smart plug attributes for led and restore state

### ISSUE THREAD

**Issue by subzero79** [dresden-elektronik/deconz-rest-plugin#1363]
Long time ago i reported in zigbee2mqtt how the xiaomi gateway sets to use the color led for On/Off state and restore state after mains off, by capturing zigbee traffic of the gateway

I left all information here
https://github.com/Koenkk/zigbee2mqtt/issues/201#issuecomment-415231510

there is a  link with wireshark data capture.

If you need to me do more capture i still have the xiaomi gw.

Thanks

**Comment by Thulinma** [comment]
Is anyone working on, or planning to work on this?

If not, can I help?
I know practically nothing of Zigbee protocol and herdsman is pretty daunting in scope, but I'm an experienced JS dev with a pair of ZNCZ02LM's lying around to test on (assuming this functionality indeed works on that model, which I believe it should...). With a few pointers I will likely be able to get this into a working state relatively quickly. :grin:
