### ISSUE TITLE
Offset for Aqara Temp/Hum/Press Sensor

### ISSUE THREAD

**Issue by kugelkopf123** [dresden-elektronik/deconz-rest-plugin#1377]
I've found a solution to change the offset. I tried an offset of -10 but nothing changed on the Temp value.

command:`curl -H 'Content-Type: application/json' -X PUT -d '{"offset": -10}' http://192.168.1.73:8080/api/ABCDEFG/sensors/2/config
`
Result:` {"config":{"battery":100,"offset":-10,"on":true,"reachable":true},"ep":1,"etag":"469a3fa20640dca88f0240552a054701","manufacturername":"LUMI","modelid":"lumi.weather","name":"Sensor2","state":{"lastupdated":"2019-03-23T12:56:46","temperature":2302},"swversion":"20161129","type":"ZHATemperature","uniqueid":"aa:15:55:00:x2:2c:cy:a3-01-0402"}`
<img width="321" alt="Bildschirmfoto 2019-03-23 um 14 09 17" src="https://user-images.githubusercontent.com/45996965/54884688-41493380-4e74-11e9-9794-db2602344132.png">
<img width="1920" alt="Bildschirmfoto 2019-03-23 um 13 26 35" src="https://user-images.githubusercontent.com/45996965/54884695-4d34f580-4e74-11e9-8e7a-90ffc06cc29c.png">
<img width="1907" alt="Bildschirmfoto 2019-03-23 um 13 26 13" src="https://user-images.githubusercontent.com/45996965/54884696-4d34f580-4e74-11e9-96b7-a0b73d3f45a9.png">

**Comment by ebaauw** [comment]
`config.offset` is in 0.01°C, just like `state.temperature`

**Comment by kugelkopf123** [comment]
> `config.offset` is in 0.01°C, just like `state.temperature`

Thank you!! It works! But is there a special reason that the range from the offset ist +/-500 ? eg. +/- 5.00°C

**Comment by ebaauw** [comment]
No special reason.  It seemed like a reasonable range to calibrate the sensor.

**Comment by kugelkopf123** [comment]
May I ask if it is possible to make this value freely selectable? Especially in the field of Humidity 5% are not the most. As far as I've seen, there is no offset at Pressure ?!
