### ISSUE TITLE
re-pairing xiaomi sensors - name reset for contact sensor

### ISSUE THREAD

**Issue by ErnstEeldert** [dresden-elektronik/deconz-rest-plugin#1381]
As probably everyone else stuck with Xiaomi sensors, they need regular repairing if something has changed wrt their parent node in the network. When I do so, I see different behavior between motion and contact sensors:

* for motion sensor, the device is re-paired and everything is looking fine
* for contact sensor however, the device is re-paired, but the name is set to the standard 'Window/Door Sensor'.

**Comment by sragas** [comment]
Got the same problem randomly, names are resetted after pairing or repairing a device. Occurs with Xiaomi sensors, but also with Philips Hue dimmer switches/tap and Philips motion sensors. Actually all devices setup in deCONZ
