### ISSUE TITLE
Aqara Vibration Sensor

### ISSUE THREAD

**Issue by erichsch** [dresden-elektronik/deconz-rest-plugin#1383]
Is it possible that the "angle" or the "position" is logged.

like this:

Resting position | Raw Value | Raw (X, Y, Z) | Angles (X, Y, Z)
-- | -- | -- | --
Front side up | 0x04de00100031 | (49, 16, 1246) | (2°, 1°, 88°)
Battery side up | 0xfc7000270054 | (84, 39, -912) | (5°, 2°, -84°)
Reset button up | 0x00780424001a | (26, 1060, 120) | (1°, 83°, 6°)
Reset button right | 0x0093001ffc7e | (-898, 31, 147) | (-81°, 2°, 9°)
Reset button down | 0x006efc27006d | (109, -985, 110) | (6°, -81°, 6°)
Reset button left | 0x007c00230408 | (1032, 35, 124) | (83°, 2°, 7°)

thank you

**Comment by chimpy** [comment]
Looks like it'll be in 0.61 and HA 0.91 https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748
