### ISSUE TITLE
Unsupported Sensor - Aqara Motion Sensor

### ISSUE THREAD

**Issue by holdestmade** [dresden-elektronik/deconz-rest-plugin#1385]
When I add an Aqara Motion Sensor using Phoscon APP, it adds and works fine but this appears in HA log:

Unsupported sensor {'e': 'added', 'id': '49', 'r': 'sensors', 'sensor': {'config': {'battery': 100, 'on': True, 'pending': [], 'reachable': True, 'temperature': 2200}, 'ep': 1, 'etag': 'f9161910a7b59582bf61c0ff2c3cd830', 'id': '49', 'manufacturername': 'LUMI', 'modelid': 'lumi.sensor_motion.aq2', 'name': 'Living Room Motion', 'state': {'alarm': False, 'lastupdated': 'none', 'lowbattery': False, 'tampered': False}, 'type': 'ZHAAlarm', 'uniqueid': '00:15:8d:00:02:f3:99:75-01-0500'}, 't': 'event', 'uniqueid': '00:15:8d:00:02:f3:99:75-01-0500'}

Is there a fix or a workaround ?

**Comment by manup** [comment]
Fixed with latest commit and will be available in 2.05.63.

Close this issue in favor of: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1017
