### ISSUE TITLE
Xiaomi sensors become unavailable in Home Assistant after Raspberry Pi device IP is changed due to DHCP settings

### ISSUE THREAD

**Issue by jerrychong25** [dresden-elektronik/deconz-rest-plugin#1389]
Hi all,

I found out one issue with Xiaomi sensors connection to Home Assistant after Raspberry Pi own device IP is changed due to DHCP settings. 

Originally my Raspberry Pi IP is **192.168.1.160**, after that it changes to **192.168.1.170**.

After IP changed, in Home Assistant these sensors become unreachable, but in deCONZ Phoscon App these sensors are working fine without any issues. 

Home Assistant Error Screenshot:
![deCONZ DHCP Error 1](https://user-images.githubusercontent.com/15714095/55124764-5c50c780-5142-11e9-8e23-02e8efe5a1f3.JPG)
![deCONZ DHCP Error 2](https://user-images.githubusercontent.com/15714095/55124772-62df3f00-5142-11e9-99f1-f4a8e93f643e.jpg)

deCONZ Sensor Screenshot:
![deCONZ DHCP Error 3](https://user-images.githubusercontent.com/15714095/55124783-6ffc2e00-5142-11e9-95c9-57f7caf1cc10.JPG)

To solve this, I forced set Raspberry Pi static IP back to **192.168.1.160**, then everythings working fine again.

Just to confirm, is this error an expected deCONZ behaviour after Raspberry PI device IP is changed?

Thanks.

**Comment by Kane610** [comment]
This is not a deCONZ issue. The integration sets the IP on registration, there is no auto updating the IP after that.

I have on my to do to enable updating of IP on gateways further down the line

**Comment by chimpy** [comment]
+1 to what @Kane610 said. You should also consider giving out DHCP IP reservations to at least all the smart devices on your network if you are using HA. This will avoid your config breaking because of some arbitrary IP change.

**Comment by jerrychong25** [comment]
@Kane610 and @chimpy,

Thanks for the info.

For now, I would set static IP for Raspberry Pi solving this issue.

Thanks.

**Comment by Kane610** [comment]
This issue can be closed since the issue has been clarified
