### ISSUE TITLE
Sensor control within a group

### ISSUE THREAD

**Issue by realwax** [dresden-elektronik/deconz-rest-plugin#1391]
Hi,

I don't know if it is to be called an issue, or maybe a feature request. But due to the existing situation some scenarios are hard to set up or achieve.

I am missing the option to directly set a scene through a motion sensor. As this feature is not present on motion you need to create special groups to only adress some lights on motion and even color can not be changed. May this belongs to Phosconn App or to the rest plugin. I don't know.
Furthermore it would be helping being able to define a timeframe in addition to daytime/darktime settings. I want the motion to be triggered only in betwenn 22;00 and 06:00 and not when it's getting dark. I am able to do this in iobroker but as Phoscon app has such nice features it would complete what's there and extend the functionality for a better usability and use cases.

Thank you

Wolfgang

**Comment by maikkoe** [comment]
I posted similar request yesterday #1384
