### ISSUE TITLE
Support Aqara Motion sensor speed hardware hack

### ISSUE THREAD

**Issue by abena1234** [dresden-elektronik/deconz-rest-plugin#1395]
There is this super easy hardware hack (https://community.smartthings.com/t/making-xiaomi-motion-sensor-a-super-motion-sensor/139806) to make Aqara motion sensor send new state ALWAYS in 5 second intervals. Is there a way to support this on deconz? I want to decide all timeouts in home assistant.

**Comment by Kane610** [comment]
I've seen in comments on other issues that you can configure the timeout in deconz

**Comment by kugelkopf123** [comment]
#1366

**Comment by kugelkopf123** [comment]
I did it with all 4 PIR Sensors i have.. It works great since 3 Days =)
