### ISSUE TITLE
FLS-PP Ip Bundle not receiving Web App Commands

### ISSUE THREAD

**Issue by senyorsombrero** [dresden-elektronik/deconz-rest-plugin#14]
Hello:
I recently Acquired a Raspbee as well as a FLS-PP Ip  Bundle (RGB) with LED Light Strip through the Dresden Elektronik Website. I configured the Raspberry Pi as mentioned in  the guide and through deCONZ I  am able to see the Raspberry Pi as the coordinator and the FLS-PP as an End-Device. Through the deCONZ app I am able to operate and change parameters and values of the LED strip, as well as turning it on and off.
The problem is, when I try to operate the lights through the Web App, it won't respond to the commands (it won't turn off and on the light, it won't change colour, etc.). The lightstrip is in a group and the latest update of the Web App is installed (2.04.18).
Is there something wrong I am doing? Or how can I fix this?

**Comment by manup** [comment]
Damn I haven't seen this one, hopefully works meanwhile.

Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
