### ISSUE TITLE
Unable to find Raspberry PI device host IP in Home Assistant Integration Page deCONZ gateway New Setup

### ISSUE THREAD

**Issue by jerrychong25** [dresden-elektronik/deconz-rest-plugin#1408]
Hi all,

I have installed deCONZ manually mentioned in https://github.com/dresden-elektronik/deconz-rest-plugin, as per following  steps:

**1) Install deCONZ Command**
```
wget http://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.05.60-qt5.deb
sudo dpkg -i deconz-2.05.60-qt5.deb
sudo apt update
sudo apt install -f
```

**2) Set Software Requirements**
```
sudo raspi-config

() Interfacting Options > Serial

    * Would you like a login shell accessible over serial?
      > No
    * Would you like the serial port hardware to be enabled?
      > Yes
```

**3) Reboot Raspberry Pi.**

**4) Enter Home Assistant Integration page.**

**5) Press **CONFIGURE** button for deCONZ Zigbee gateway, but it don't have my Raspberry PI device host IP.**
![image](https://user-images.githubusercontent.com/15714095/55599152-f808b600-5788-11e9-8d35-73273f224715.png)

Could advise how to solve this issue?

Thanks.

**Comment by curryhoden** [comment]
Did you press the "Connect app" button in 
Deconz => Gateway  ?

**Comment by jerrychong25** [comment]
> Did you press the "Connect app" button in
> Deconz => Gateway ?

Hi @curryhoden,

Now able to get IP and connect, not sure what is happening.

However, after I pressed **Authenticate app** button in deCONZ Phoscon App, it will displays **Couldn't get an API key** when I pressed SUBMIT button.

Any idea on solving this issue?

Thanks.

**Comment by jerrychong25** [comment]
> > Did you press the "Connect app" button in
> > Deconz => Gateway ?
> 
> Hi @curryhoden,
> 
> Now able to get IP and connect, not sure what is happening.
> 
> However, after I pressed **Authenticate app** button in deCONZ Phoscon App, it will displays **Couldn't get an API key** when I pressed SUBMIT button.
> ![image](https://user-images.githubusercontent.com/15714095/55773678-39200380-5ac4-11e9-9f10-71834f89c803.png)
> 
> Any idea on solving this issue?
> 
> Thanks.

As this is a new issue, I would open a new thread instead.

Kindly follow https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1418 for this new issue.
