### ISSUE TITLE
Paulmann Light switching on randomly

### ISSUE THREAD

**Issue by beatpaul** [dresden-elektronik/deconz-rest-plugin#1415]
Hi!

The problem i have is, that just this light (Paulmann Dimmer) switches on randomly. That happened since i installed it, but first i didnt care to much ... but now my gf gets nervous ;)

Is anyone having the same issue? / any solution ?
I already tried to get some help ... but issue was closed:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/231#issuecomment-463584657
here are some details and logs, 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/231#issuecomment-464442285:

thx,

Paul

**Comment by daaaaa** [comment]
Is this still happening to you @beatpaul ?
I am interested on buying the Paulmann Dimmer 50044, but the problem you are facing seems to be annoying.

**Comment by beatpaul** [comment]
Hi!
It was so annoying i kicked it out of my System :(


I Bought this instead and it is working flawless

iluminize Zigbee 3.0 Dimm-Aktor... https://www.amazon.de/dp/B07HQFP3PJ?ref=ppx_pop_mob_ap_share

**Comment by daaaaa** [comment]
Oh, ok. Thanks. 
Just wondering if it a device problem or a problem with the integration with deconz.

The one you linked is a little more expensive, but if it works, I'll give a try :)
Thanks!
