### ISSUE TITLE
New Conbee version ?

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#1417]
Hello, It's not an issue, but I find informations nowhere.

The Conbee have disapear on dresden-elektronik site (and sadly on amazon too) and a new one have appear with as name "Conbee II".
Someone have informations ?

https://shop.dresden-elektronik.de/wireless-light-control/raspbee-gateway-153/conbee-2.html

**Comment by ebaauw** [comment]
Faster 32-bit microprocessor, same amount of memory, same serial interface, same Zigbee stack, but different firmware build (ending in 0700).  Most importantly: it’s really cute ;-)

See https://github.com/dresden-elektronik/deconz-rest-plugin/commit/e7b905d6b420a0abfa9010932ba320b05b78a5a6.

**Comment by Smanar** [comment]
Lol, I prefer the white Conbee even I never see it in reality ^^.
So this Conbee have an improvement, it's not only packaging. And she is already available, so I think it will be soon on amazon too.

**Comment by manup** [comment]
More information about the ConBee II will be available very soon, took a bit longer than expected to build the new homepage.

As ebauuw mentioned, on the Zigbee side it is feature wise identical to ConBee I. We'll maintain both code bases as they share a common firmware core on application level.

>so I hope it will be soon on amazon too

First batch is on its way to Amazon Germany and further Amazon markets will follow shortly.

**Comment by Oliviakrkk** [comment]
Should we upgrade from I to II?

**Comment by Hasenpups** [comment]
What are the advantages of the Conbee II in comparison to the old version?

**Comment by manup** [comment]
There is no technical advantage. It's only the look and that it's smaller.
Albeit the MCU is faster it isn't noticeable, the ConBee I/RaspBee MCU is perfectly fine for the Zigbee load.

>but should we think about to upgrade?

No, an upgrade from ConBee I to II isn't needed.

**Comment by Oliviakrkk** [comment]
Thank you for clarification.

**Comment by jerrychong25** [comment]
> There is no technical advantage. It's only the look and that it's smaller.
> Albeit the MCU is faster it isn't noticeable, the ConBee I/RaspBee MCU is perfectly fine for the Zigbee load.
> 
> > but should we think about to upgrade?
> 
> No, an upgrade from ConBee I to II isn't needed.

Thanks for the clarification.
