### ISSUE TITLE
Unable to set integration with deCONZ Zigbee gateway in Home Assistant for RaspBee device

### ISSUE THREAD

**Issue by jerrychong25** [dresden-elektronik/deconz-rest-plugin#1418]
Hi all,

I would like to set integration with deCONZ Zigbee gateway in Home Assistant for RaspBee.

It will displays **Couldn't get an API key** after I pressed **SUBMIT** button, even though I already pressed **Authenticate app** button in deCONZ Phoscon App, as per screenshot below:
![image](https://user-images.githubusercontent.com/15714095/55773678-39200380-5ac4-11e9-9f10-71834f89c803.png)

Any idea on solving this issue?

Thanks.

**Comment by Kane610** [comment]
There is a bug in the configuration flow initiated from the frontend, work around is to create an entry in configuration.yaml 
```
deconz:
  host: x
  port: y
```
and then finish the flow from the frontend

**Comment by Kane610** [comment]
Home assistant issue: https://github.com/home-assistant/home-assistant/issues/22795

**Comment by jerrychong25** [comment]
> There is a bug in the configuration flow initiated from the frontend, work around is to create an entry in configuration.yaml
> 
> ```
> deconz:
>   host: x
>   port: y
> ```
> and then finish the flow from the frontend

Values of **x** and **y** replaced with my device own IP and Port, right?

**Comment by Kane610** [comment]
Yes

**Comment by jerrychong25** [comment]
@Kane610,

Successfully linked to HA.

However, there is one issue, whereby deCONZ Phoscon App falsely recognize my RaspBee as ConBee icon in deCONZ Phoscon App Login Page.

Due to this, I cannot add my sensor successfully.

Any idea how to solve this?

Thanks.

**Comment by Kane610** [comment]
I've seen it mentioned. Search around here and you will probably find a solution

**Comment by jerrychong25** [comment]
I have opened another issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1433 for this new issue on detecting RaspBee as ConBee, to prevent any confusion.

Therefore, I will close this issue.

Thanks.
