### ISSUE TITLE
[Request Device Support] Develco meizh-061 meter interface

### ISSUE THREAD

**Issue by 02dag** [dresden-elektronik/deconz-rest-plugin#1424]
I have a develco meter interface with zigbee made for a kamstrup energy meter. This shows up in deconz.

I'm wondering if it would be possible to add support for this?

Please let me know if I can provide any additional information

![bilde](https://user-images.githubusercontent.com/42731754/56060376-f598f400-5d66-11e9-873f-3449b3549b2e.png)

![bilde](https://user-images.githubusercontent.com/42731754/56060398-06e20080-5d67-11e9-86fa-30041b9d6c83.png)

![bilde](https://user-images.githubusercontent.com/42731754/56060461-34c74500-5d67-11e9-848b-2bcf899eb36c.png)

**Comment by djwlindenaar** [comment]
Where do you get these things? Only thing I can find, it seems develco is OEM; MOQ 5000.

**Comment by gpl1998** [comment]
see here: https://www.develcoproducts.com/products/

**Comment by 02dag** [comment]
What do you mean by that

**Comment by djwlindenaar** [comment]
Well, I know about the site mentioned by @gpl1998 however that site does not allow ordering. Also it seems develco only does business2business with a minimum order of thousands.

**Comment by 02dag** [comment]
To you djwlindenaar: I got this plug-in for my kamstrup meter from my energy company. To get the gateway I had to sell my soul to them. So I figured I might as well try to get it working without the gateway. It is a zigbee device and the data is most certainly there, just have to provide the necessary code to get hold of it.

**Comment by ebaauw** [comment]
@djwlindenaar, Different countries use different standards to open up smart utility meters for consumers.  E.g. here in the Netherlands they provide a serial interface as per the DSMR standard.  I suspect “my” electricity meter receives data from “my” gas meter over Zigbee Smart Energy, but the network provider locked that down.  Even if I could get my hands on such a plugin, I could not use it.  See also https://github.com/dresden-elektronik/deconz-rest-plugin/issues/502.

@02dag please provide the info listed in the Wiki, https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support.

**Comment by djwlindenaar** [comment]
@ebaauw, I am also in the Netherlands, and there should indeed be a P1 interface on the smart meter. I have seen a develco product that will translate the P1 to ZigBee, but the main thing seems to be that develco product are not easily obtained. I liked their smart plug as well, but same story...

**Comment by 02dag** [comment]
@ebaauw, I have already seen issue 502, however my plugin manages to connect to the zigbee network. Unless it will ask for a secret code at some later time. Thank you for the link. With that I found out to get more information out of it.

Here it is, and if you need something more detailed let me know. I have taken some photos of the Basic, simple metering and time
![bilde](https://user-images.githubusercontent.com/42731754/56079739-91267500-5df8-11e9-9e8b-e9761f615b12.png)

![bilde](https://user-images.githubusercontent.com/42731754/56079757-b4512480-5df8-11e9-99f7-170a65afc7a7.png)

![bilde](https://user-images.githubusercontent.com/42731754/56079772-01cd9180-5df9-11e9-96d5-9418b1ea4005.png)

![bilde](https://user-images.githubusercontent.com/42731754/56079988-d4361780-5dfb-11e9-967f-bd149b051abc.png)
![bilde](https://user-images.githubusercontent.com/42731754/56080027-1d866700-5dfc-11e9-8c06-d95f6006bcd7.png)
![bilde](https://user-images.githubusercontent.com/42731754/56080035-2d9e4680-5dfc-11e9-846d-067d7fc22cdf.png)
![bilde](https://user-images.githubusercontent.com/42731754/56080055-59b9c780-5dfc-11e9-86c5-443d9ffa6a45.png)
![bilde](https://user-images.githubusercontent.com/42731754/56080084-c92fb700-5dfc-11e9-961f-dbaee87bc85b.png)

[part of debuglog.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/3076184/part.of.debuglog.txt)

**Comment by 02dag** [comment]
For me it seems that the zigbee device works. When I press the read button, the values change.
I am not sure what a supported device will give me, but I reckon that I can click on a page in phoscon gateway and have a presentation of the data of some sorts there. 

I am not sure if that is necessary, if there is another way for me to fetch the data and present them myself on a webpage on the raspberry PI? some guidance in the correct direction is all I need. I am a total newb in this , but wht I have read so far is that maybe a script using python or xbee or something, will fetch me my data. Then use something else to present it?

**Comment by ebaauw** [comment]
@djwlindenaar: I expose the data from my P1 interface directly to HomeKit, using [homebridge-p1](https://github.com/ebaauw/homebridge-p1).  I suppose technically, I could expose it as a ZigBee device, using an XBee (or even a RaspBee or ConBee configured as as router), but I would end up exposing it to HomeKit using homebride-hue anyways.  Also, writing a Zigbee application using the serial protocol to interface with the Zigbee radio is a non-trivial endeavour.  You'd need to run it on an Arduino with two serial ports (one for the XBee and one for the P1) or on a Raspberry.

> I am not sure what a supported device will give me

@2dag: Support through the REST API, which would be needed for support in Phoscon (it uses the REST API to communicate with deCONZ) and/or fetching the data for your home automation environment, webpage, app, or whatever.

**Comment by SwoopX** [comment]
Eventually, this might help ([technical manual](https://www.develcoproducts.com/media/1933/kamstrup-meter-interface-meizh-061-technical-manual.pdf))
