### ISSUE TITLE
Expand range with CC2530 

### ISSUE THREAD

**Issue by lubbertkramer** [dresden-elektronik/deconz-rest-plugin#1428]
Is it possible to use the Router CC2530 as a router in the network i have with my conbee to expand the range of my zigbee (battery) devices?

Using the CC2530 as router to expand network:
https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html

**Comment by heitec11** [comment]
Yes, it is possible.
Only the connection (as line) is not showing, but without router (repeater) it is not working.
![grafik](https://user-images.githubusercontent.com/44260876/56451990-b2262300-632e-11e9-8177-1b5a0276c58e.png)

**Comment by lubbertkramer** [comment]
Great to hear, will test it out!

**Comment by florianru1984** [comment]
How is the CC2530 router is connected? I use Deconz as a headless setup

**Comment by gerard33** [comment]
I have the CC2531 as a router in my network. It's added as a light.

See this link for more details -> https://community.home-assistant.io/t/deconz-official-thread/100504/88?u=gerard33
