### ISSUE TITLE
Calex Color Scene Controller

### ISSUE THREAD

**Issue by mathos77** [dresden-elektronik/deconz-rest-plugin#1429]
Hi all,

I have a new device, Calex Color Scene controller:
https://www.calex.nl/en/products/product/CALEXZIGBEEAFSTANDSBEDIENING/

https://www.amazon.de/Calex-Farbsteuerung-kompatibel-Leuchtmittel-Leuchtmitteln/dp/B07H5HC2GH

![image](https://user-images.githubusercontent.com/19706662/56094156-2432de00-5ed1-11e9-8d1c-c47a2fc16f39.png)

[image](https://user-images.githubusercontent.com/19706662/56094157-2d23af80-5ed1-11e9-8cfa-7a9696d11f5e.png)

And it seems to connect to deCONZ just fine.

however, none of the nodes are supported it seems.

Would love to see this supported by deCONZ ! ;-)

In deCONZ it looks like:
![image](https://user-images.githubusercontent.com/19706662/56094208-ee422980-5ed1-11e9-8a7f-d76bb6dd4079.png)

![image](https://user-images.githubusercontent.com/19706662/56094215-0154f980-5ed2-11e9-9bbd-c8a75ca3329f.png)

![image](https://user-images.githubusercontent.com/19706662/56094221-234e7c00-5ed2-11e9-98f6-15f90be351f3.png)

![image](https://user-images.githubusercontent.com/19706662/56094224-3cefc380-5ed2-11e9-9972-ac1f6fa4e8de.png)

**Comment by mathos77** [comment]
Some debugging in deCONZ (aps=2)

![image](https://user-images.githubusercontent.com/19706662/56094784-9823b500-5ed6-11e9-9aa2-43f0226018e0.png)

![image](https://user-images.githubusercontent.com/19706662/56094787-a83b9480-5ed6-11e9-9e7f-4a3ffd433df5.png)

**Comment by mathos77** [comment]
@manup @ebaauw Do you have any idea what else is required besides the provided, to get this switch supported ?
Somehow I have lost my Conbee....so sniffering is a bit a non-option atm.....

**Comment by ebaauw** [comment]
We need to see what commands the switch sends.  That's in the `asdu` message following each of the `APS-DATA.indication` messages (for profile 0x0104).  Unfortunately, that message doesn't include the mac address, so filtering the output won't work.  
Make sure for each button to capture: press/release, press/hold.../release.  It the (W) in the middle also a button?

Did you bind it to any lights, or does it control all your lights out of the box?

Exposing the colour ring might be challenging: how to translate the colour to buttonevent values?

**Comment by mathos77** [comment]
for the Color-ring I was hoping to have something similar as we have with the TRADFRI dimmers
they seems to operate quite well directly....

**Comment by ebaauw** [comment]
That'll work: the switch sends the command to change the colour to (I hope) a group.  The lights in that group will respond, even is deCONZ is down.  If you bind the switch client clusters 0x0006, 0x0008, 0x0C00 to a group in the deCONZ GUI and assign a light to that same group (again in the GUI), the switch should already be able to control the light.  Then the REST API plugin should pickup the group from the light, after which you can assign lights to the group using Phoscon or whatever API client.

We'd need REST API support to do the binding automatically (if the switch doesn't already come with a random group configured after reset to factory defaults) and to reverse engineer the commands into buttonevents, so the switch can be used from deCONZ rules.
