### ISSUE TITLE
Rest command reliability problems

### ISSUE THREAD

**Issue by TheWizz** [dresden-elektronik/deconz-rest-plugin#1435]
I've found that commands sent through the REST API may not work reliably if other commands are sent before. See enclosed wireshark log, where the last command sent set the "brightness" value to 0 and the "on" value  to false. If this command is sent on its own, it typically works reliably. However, if other commands are sent before this command (as in this case) the final brightness command may be ignored. The values sent in this example all set the "brightness" and "on" values, according to a slider moved by the user. I tried spacing the commands out more sparsely, which appears to improve the reliability somewhat. However, even if I space them 0.2 seconds apart (or more), commands still fail quite often.

Attempting to increase reliability by spacing the commadns even further apart may help I guess. But once you get up to several 100 milliseconds of spacing, the slider starts to feel very sluggish and unresponsive. Besides, merely adding more temporal "padding" between commands feels like a very inprecise way of getting to a reliable system.

Since we're dealing with a REST API here, it would be more appropriate for the _gateway_ to handle any "handshaking" necessary. If throttling of the rate of commands is required, the REST API could enforce that by simply delaying its "200 OK" response until the command has been successfully handed over to the light (or at least the zigbee bus).

In this case, I'm controlling a single light in a group. There are only two groups in the system (one with one light and another group of two lights). All lamps are close to the transciever.

Any advise on what I can do to get a reliable brightness slider through the REST API would be most appreciated.

-JM

![Screenshot 2019-04-15 at 16 56 37](https://user-images.githubusercontent.com/4129909/56152080-0c338b00-5fb3-11e9-9ac2-ca6b75bcbdbb.png)

**Comment by cree8** [comment]
I see this behavior as well, simply when turning lights on and off in succession. The command may or may not go through, yet there is no acknowledgement if the command was rejected. This does not allow for reliable automations.
