### ISSUE TITLE
Support for Osram Smart+ Contact Sensor

### ISSUE THREAD

**Issue by JSkier21** [dresden-elektronik/deconz-rest-plugin#1437]
This is similar to the motion sensor (which is working wonderfully): #881

This sensor is for door / window open closed status monitor, and also has a temperature sensor read. Commonly branded as Sylvania Smart+ door / window sensors here in the US. 

I attached a bunch of screen caps. deCONZ gui appears to pair with it appropriately, but phoscon never sees the sensor. 

I'm looking into API more, but am pretty new to this and would greatly appreciate some pointers. If you need more information, please let me know. 

![Basic Cluster info](https://user-images.githubusercontent.com/3190223/56156568-235a8480-5f83-11e9-9d83-33ea7c04d26b.png)
![NodeInfo](https://user-images.githubusercontent.com/3190223/56156569-235a8480-5f83-11e9-8e23-ae21ca210824.png)
![Power info](https://user-images.githubusercontent.com/3190223/56156570-235a8480-5f83-11e9-9685-137efd44e8f9.png)
![Temperature measurement](https://user-images.githubusercontent.com/3190223/56156571-23f31b00-5f83-11e9-8ed7-0c181ab96e49.png)

**Comment by netmanchris** [comment]
I'm interested in getting the Sylvania Contact sensor to work as well. If there's more data needed, please let us know!

**Comment by JSkier21** [comment]
I tried playing around with the api last week, device doesn't show up there either (yet deconz qt app still shows it as connected and paired). I'm new to this project, seems weird, but I guess this makes sense from other devices people have added in the past. 

I think it makes sense to recompile the device in as supported, and see how the api responds to that. I'm on a time crunch, but I'll try that next when I have time. If I get that done, would you be interested in testing that code @netmanchris? I assume you have this contact sensor on hand?

**Comment by netmanchris** [comment]
I"m new to this project as well, but I'm happy to test given I have some instructions on whats expected to be tested and how it's to be tested.  :) Happy to help, but very new to this project so want to make sure I'm not committing to something where I'm totally out of my depth.  Yes - I do have a couple of Sylvania Contact sensors on hand.
