### ISSUE TITLE
Hue Dimmer Switch controls a group of bulbs - some bulbs very often dont react on commands

### ISSUE THREAD

**Issue by ottelo9** [dresden-elektronik/deconz-rest-plugin#1446]
I bought a new ConBee Stick 2 and wanted to change from a Philips Hue Bridge to (I thought) a more stable and transparent ZigBee system. To test the conbee I put the phoscon ready image to my raspberry Pi 3 and connect 4 bulbs (2 TRADFRI bulb GU10 W 400lm, 2 Osram Tunable White GU10) and 1 hue dimmer switch to it. I put all lamps to one single group and let the switch control it. During testing I removed the Philips Hue Bridge from power. The 2 Osram bulbs are 2m apart from each other. The other two bulbs are very close to each other in another room. Then I press On and 1s later Off button on my Hue Dimmer to test the reaction. The pair of Ikea bulbs very often dont get the command or only one bulb stays off or on. The same for the OSRAM lights, but they dont have the problem that sometimes only one light is off/on. If I use my smartphone to control the group everything seems to work fine (except sometimes the lights need some time for the command).

I noticed that the Phoscon App/Deconz get the command from the Hue Switch. The status of the group/lights show e.g. "off"  but the lights are still on (or partly on). This status dont change until I press the OFF button again.

I use ZigBee channel 25 (same for Philips Hue Bridge) to avoid interference with my WiFi Router (fixed channel 6). I thought the Rpi3 is too slow for it and changed to my Win10 PC and use a 1m extension usb cable but this changes nothing.

![2019-04-19 13_30_25-deCONZ - ConBee II (__ _COM4)](https://user-images.githubusercontent.com/33122175/56422385-5e242b80-62a7-11e9-97c6-e231bb93df5a.png)
![2019-04-19 13_31_17-Phoscon App](https://user-images.githubusercontent.com/33122175/56422410-7ac06380-62a7-11e9-8211-57bb9a5e467b.png)
![2019-04-19 13_31_33-Phoscon App](https://user-images.githubusercontent.com/33122175/56422412-7d22bd80-62a7-11e9-9199-728fcb9f6051.png)

**Comment by manup** [comment]
>Then I press On and 1s later Off button on my Hue Dimmer to test the reaction.

Is the problem also present when there s more time between On / Off , like 5–10 seconds?

If no we can add some spacing to the handling of group commands.

**Comment by ottelo9** [comment]
> Is the problem also present when there s more time between On / Off , like 5–10 seconds?

If I wait 5s then it works! But I dont understand that the status of the bulbs in the Phoscon App is e.g. off but the bulbs (or some bulbs) are still on. I thought the bulbs send the status to the conbee?

**Comment by ottelo9** [comment]
Only a note: Every press on the switch successfully received from Deconz because I can see it in the app. But Deconz seems to have problems to send the commands. But if I do the same test via Phoscon or HomeKit (group on...1s....off...1s....on and so on) the lights are switched on or off without problems.  It’s strange....

**Comment by ottelo9** [comment]
2. Note. I use home assistant + deconz addon. I have the same problems there but I figured out how to fix it. I removed all bulb groups from deconz and create light groups in home assistant. Now it works.!
