### ISSUE TITLE
Attribute ID in Cluster Info panel

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#145]
The _Cluster Info_ panel in deCONZ GUI shows attribute IDs in hex when they're part of an `<attribute-set>` in the xml file, but in decimal when they're not.  For example, see the _Level cluster_ (0x0008), where _On/Off transition time_ (0x10) is shown as 16.

I think it should show the attribute ID in hex always, to avoid confusion.  Alternatively, could `general.xml` be adjusted, so all attributes are part of an attibute-set?

**Comment by manup** [comment]
> The Cluster Info panel in deCONZ GUI shows attribute IDs in hex when they're part of an <attribute-set> in the xml file, but in decimal when they're not. For example, see the Level cluster (0x0008), where On/Off transition time (0x10) is shown as 16.

Fixed and will be available in version 2.04.70

![image](https://user-images.githubusercontent.com/383386/29789008-eb87b65e-8c34-11e7-933e-e6e36aeb5e07.png)

I think it should show the attribute ID in hex always, to avoid confusion. Alternatively, could general.xml be adjusted, so all attributes are part of an attibute-set?

Attribute sets are defined in the ZCL but not for all clusters, therefore some have them some not.
