### ISSUE TITLE
How to update the bulb firmwares?

### ISSUE THREAD

**Issue by LightningRhino** [dresden-elektronik/deconz-rest-plugin#1452]
Can you tell me how to update the firmware of IKEA (and maybe Philips) bulbs with deCONZ/Phoscon)?
Is there a recommended way?

**Comment by ottelo9** [comment]
https://forum.iobroker.net/topic/14514/anleitung-firmware-update-ikea-leuchten-mit-deconz

**Comment by Philje123** [comment]
Philips cannot be updated with deconz as their firmware files are not made public.

As for ipdating ikea bulbs I had to do it on my windows PC as I couldn't figure out how to use the download scripts on my Hass.io install.

Download the firmware for your device from the links in the version_info.json file:

http://fw.ota.homesmart.ikea.net/feed/version_info.json

And open up the deconz interface and then the OTAU window and choose the file in there.

**Comment by LightningRhino** [comment]
Thanks @otello9 and @Philje123 
I downloaded the files and put it in the /root/ota folder.
Via VNC I opened the deCONZ App.
For my GU10 bulb I chose the right file and started with "Query". Unfortunately after 16% the update process stopped. What now?
I have another bulb "TRADFRI bulb E14 W op/ch 400lm" but don't know which of the ota files is the right one. When I click "Query" nothing happens.
Well, this is quite unsatisfying. 
Why isn't there any official documentation?

**Comment by manup** [comment]
When the files are in the `~/ota` directory, you don't need do do anything in deCONZ.
Just power-cycle a bulb and the update should start automatically.

**Comment by Philje123** [comment]
Yeah as above. Are you power cycling the bulb first? Battery devices need the battery taking out and putting back in too.

I've succesfully updated several Ikea wireless dimmers and switches.

**Comment by LightningRhino** [comment]
Yes, I powercycled the bulbs more than 12 hours ago. Nothing happened yet.

@manup 
~/ota OR ~/otau ?

And is it really necessary to activate the "Otau Server" in the old WebApp Version (Wireless Light Control)?

**Comment by manup** [comment]
Sorry was a typo `~/otau`

>And is it really necessary to activate the "Otau Server" in the old WebApp Version (Wireless Light Control)?

Only if it isn't already activated.

**Comment by LightningRhino** [comment]
> Only if it isn't already activated.

I'll take it as a yes then.  :)
Why has this option not been implemented in Phoscon yet?

**Comment by manup** [comment]
>Why has this option not been implemented in Phoscon yet?

Limited time :) but it's on the near future todo list with a proper per device ota update page.

**Comment by LightningRhino** [comment]
Sounds great. Keep up the good work.

**Comment by LightningRhino** [comment]
The only downside using the docker container is after updating the image the /root/~otau directory is empty again and I have to copy the firmware files over once more.  =/

**Comment by MickL** [comment]
The issue for having an option in the CLI is here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1516

Shouldnt we close this issue then @LightningRhino ?

**Comment by MickL** [comment]
Still relevant

**Comment by k2dp2k** [comment]
Still relevant

**Comment by Schnuecks** [comment]
The only thing why i have not switch my bulbs to deconz.

**Comment by Mimiix** [comment]
There is a guide somewhere. I'll put this on To-Do and get back to it later.

**Comment by Mimiix** [comment]
https://phoscon.de/en/support#ota-update-osram-devices

Update guide there. This goes for pretty much all devices.

**Comment by mansdahlstrom1** [comment]
This Issue helped me https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2330
