### ISSUE TITLE
Conbee II on Amazon geographically limited

### ISSUE THREAD

**Issue by Oliviakrkk** [dresden-elektronik/deconz-rest-plugin#1455]
Why Conbee II is limited to Germany on Amazon.de?? All other dresden products are available for purchase without any limits...

**Comment by manup** [comment]
Currently it's not clear why, we're trying to figure this out soon. Normally in Europe it should already be available, but for some reason the stock is not reachable yet in at least Poland and Austria. Current  workaround is the dresden elektronik onlineshop.

**Comment by Oliviakrkk** [comment]
Thanks!
