### ISSUE TITLE
[Development] Should all sensors appear in Phoscon?

### ISSUE THREAD

**Issue by ericvandamme** [dresden-elektronik/deconz-rest-plugin#1456]
I created support for a water leak detector for the REST API, but it does not appear in Phoscon. Is this normal behaviour for sensors? Otherwise, the REST API functionality works without issue.

**Comment by manup** [comment]
The Phoscon App holds a list of sensors and switches to show.
Can you provide the REST-API output of the sensor, we can add it then in the Phoscon App.

**Comment by ericvandamme** [comment]
Rest Output:
`{
    "config": {
        "battery": 100,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "0af04dc26efd1f9b174bbc576993652c",
    "manufacturername": "Sinope Technologies",
    "modelid": "WL4200S",
    "name": "Basement",
    "state": {
        "lastupdated": "2019-05-04T02:56:05",
        "lowbattery": false,
        "tampered": false,
        "water": false
    },
    "swversion": "363",
    "type": "ZHAWater",
    "uniqueid": "50:0b:91:40:00:01:02:41-01-0500"
}`

**Comment by manup** [comment]
Took a while, the sensor should now appear in 2.05.66

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_66

**Comment by manup** [comment]
Closing for now.
