### ISSUE TITLE
Hue Dimmer Switch problem (lost connection)

### ISSUE THREAD

**Issue by ottelo9** [dresden-elektronik/deconz-rest-plugin#1458]
Is my problem still an open issue? For testing I have 3 Dimmer Switches that control 3 groups of lights. After some time (over this weekend) all switches have lost their connection lines (see picture). If I press a button the blue circle in deconz flashes but nothing happens. The switches seem to work normally and flashes green if I press a button.
![56526143-3acdda80-654c-11e9-836b-1e0b1f0708ae](https://user-images.githubusercontent.com/33122175/56561336-400c4300-65a7-11e9-8745-baa73a7b0ff2.png)

**Comment by manup** [comment]
Were the switches configured via Phoscon App switch editor?

**Comment by ottelo9** [comment]
Via Phoscon, in the Light Group "Switch editor".

**Comment by manup** [comment]
Ok that's fine, which firmware version of ConBee II is installed?
We had seen end-device connection problems with earlier versions but they should be fixed since 0x2648070.

**Comment by ottelo9** [comment]
Vendor dresden elektronik
Product ConBee II
Version 2.05.63 / 3.4.2019
Firmware 26480700

**Comment by manup** [comment]
Note to myself: Not sure if it is related, but I noticed something odd for routing ACKs back.

![image](https://user-images.githubusercontent.com/383386/56604547-732ff000-6602-11e9-8301-1fbfc7816a7d.png)

I'll do more tests.

In the meantime can you please try to bring back one remote by pressing all four buttons for about 5 seconds.

**Comment by ottelo9** [comment]
I arrive at home after work and noticed that two of my 3 dimmer switches work again. In Deconz I see two connection lines for my switches. One sensor is still without a connection line.

**Comment by ottelo9** [comment]
I dont know why but now everything works.
