### ISSUE TITLE
No deconz-latest.deb for ubuntu

### ISSUE THREAD

**Issue by zoic21** [dresden-elektronik/deconz-rest-plugin#1464]
Hello,

I wonder why for rpi we have https://www.dresden-elektronik.de/rpi/deconz/deconz-latest.deb and not for ubuntu package ?

It's more easy to auto-update with one link, for ubuntu I need to go on https://www.dresden-elektronik.de/deconz/ubuntu/beta/ and find last version, update url then launch my script for auto update...

**Comment by manup** [comment]
There is an APT repository now which should simplify updating.

http://phoscon.de/conbee2/install#ubuntu


And to update deCONZ:

    sudo apt update && sudo apt upgrade

**Comment by zoic21** [comment]
Ok thank, but it's update all system and I only want to update deconz...
