### ISSUE TITLE
Since I cloned my conbee to the conbee II , the sensors take a long time to be reachable 

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#1467]
this issue was in a old firware of the conbee 1 if i remember correctly

**Comment by MattL0** [comment]
I need to mannually pres the button of some sensors... or I have to walk in front of them.., move them etc.

**Comment by MattL0** [comment]
i am on deCONZ_ConBeeII_0x26490700.bin.GCF

**Comment by manup** [comment]
Since this handling is in deCONZ (not firmware specific) there shouldn't be any difference. Some devices like Xiaomi sensors take up to one hour to become reachable. But once they are reachable they should stay this way.

**Comment by MattL0** [comment]
Ok . Maybe i didn’t notice this behavior before .

Thanks manup
