### ISSUE TITLE
auto backup

### ISSUE THREAD

**Issue by sweebee** [dresden-elektronik/deconz-rest-plugin#1475]
Is there a way to create a backup within the command line to a specific folder?

I want to auto backup deconz with a cronjob to git.

**Comment by manup** [comment]
Basically you just need to backup the zll.db file, since it holds all the important data.

**Comment by sweebee** [comment]
Thanks, where can I find this file? (installed on raspberry)

**Comment by sweebee** [comment]
already found it, thanks. Got the auto backup working.
