### ISSUE TITLE
PWA: Trådfri remote control group name not reflected in REST /groups/{"name"}

### ISSUE THREAD

**Issue by olemr** [dresden-elektronik/deconz-rest-plugin#1476]
![image](https://user-images.githubusercontent.com/28068256/56863433-7f2b0180-69b6-11e9-93b6-096e02b7c84a.png)

After adding a new 5 button Ikea remote and renaming it in PWA, the "name" field in REST /groups/ is not updated. (making it hard to find the right group id among many remotes. Added 6 new yesterday)

In PWA:
![image](https://user-images.githubusercontent.com/28068256/56863447-ada8dc80-69b6-11e9-8188-5a729e4e9f79.png)

In REST:
![image](https://user-images.githubusercontent.com/28068256/56863462-cdd89b80-69b6-11e9-95c1-2a88a1d9e493.png)

**Comment by ricmik** [comment]
It’s the same thing with sensor names. 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1299#issuecomment-506054435
