### ISSUE TITLE
 TRÅDFRI Motion sensor dark attribute isn't updated

### ISSUE THREAD

**Issue by phdelodder** [dresden-elektronik/deconz-rest-plugin#1481]
I'm using deconz component for HA and the dark attribute isn't updated of 
TRÅDFRI Motion sensor. 

Using version V2_05_64_stable

**Comment by ebaauw** [comment]
You need to set the sensor’s dial to _Night_.  It’s only updated when the sensor reports motion.

**Comment by phdelodder** [comment]
When set to night do I still get motion during the day?

**Comment by ebaauw** [comment]
Yes.

**Comment by phdelodder** [comment]
Set the dial to night, the motion is detected. It's also slow to report the dark property.
