### ISSUE TITLE
Aqara Curtain B1

### ISSUE THREAD

**Issue by netRunner0** [dresden-elektronik/deconz-rest-plugin#1483]
![IMG_0078](https://user-images.githubusercontent.com/44049295/56965164-14282900-6b76-11e9-9b4f-3f998adfddc2.jpeg)

Please add

**Comment by ebaauw** [comment]
Please provide the info described here: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support.  Without this info, we won’t be able to add support.
