### ISSUE TITLE
KEEN Vent Battery Reporting

### ISSUE THREAD

**Issue by tenholde** [dresden-elektronik/deconz-rest-plugin#1484]
The value for battery percentage appears to be reported incorrectly in the REST information.

Comparing the Power Configuration value to REST:

100% appears as 50% in REST
75% appears as 37% in REST
50% appears as 25% in REST

See attached for example of 75%/37%

Let me know if I can supply anything additional.
![PowerCluster](https://user-images.githubusercontent.com/19240584/56968913-a48c4c80-6b29-11e9-8b12-5f19cfff07b4.jpg)

![temperature](https://user-images.githubusercontent.com/19240584/56968930-ace48780-6b29-11e9-855d-af072fa5715d.jpg)

![pressure](https://user-images.githubusercontent.com/19240584/56968935-b1a93b80-6b29-11e9-870f-9f58b10bd9a5.jpg)

**Comment by tenholde** [comment]
![about](https://user-images.githubusercontent.com/19240584/56969153-2da38380-6b2a-11e9-9600-d7b7878d9fad.jpg)

version information

**Comment by ebaauw** [comment]
The ZCL spec states that _Battery Percentage Remaining_ is in 0.5%.  Did you check what value theKeen Vent reports for a fresh battery?

**Comment by tenholde** [comment]
I put in new batteries, and the Power Configuration Cluster reads as 100.  The REST info contains 50.

**Comment by ebaauw** [comment]
Apparently Keen Home don't adhere to the standard, just like IKEA and iCasa.  I'll add them to the appropriate exception list.

**Comment by tenholde** [comment]
Thank you.  How does this get accomplished?  Will this be included in the next release of deCONZ?

Ed Tenholder
ed@tenholder.net
