### ISSUE TITLE
Aqara sensors are disconnected after some time when connected through router

### ISSUE THREAD

**Issue by imortkz** [dresden-elektronik/deconz-rest-plugin#1488]
Aqara sensor connected to the router disconnects and became unavailable after some time. Other sensors, connected to the coordinator, are stable.

Router: Sylvania SMART+ Smart Plug (72922-A)
Sensors: Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)

When connected to the router keeps online for hour or so, then didn't send any update.

Connect sensor to the router and wait for a while.
Aqara sends 5 updates in 41 minutes after rejoin and connected to the router, and no more updates after.

ConBee is upgraded to the last firmware.
Should I expect any messages in the logs while debug is on?

**Comment by manup** [comment]
>Should I expect any messages in the logs while debug is on?

I'm afraid the logs won't show the required details. Since the direct connection with coordinator is stable I assume the plug does one of the following:
* Throw the sensor out of the child table and doesn't forward the messages to coordinator
* Forces the sensor to leave the network

Only sniffer logs can tell what happens exactly.


Related issues:
https://github.com/Koenkk/zigbee2mqtt/issues/1474
https://github.com/Koenkk/zigbee2mqtt/issues/1485

**Comment by imortkz** [comment]
Yeah, I tried zigbee2mqtt to find out that I have the same problem as with ConBee stick.
Will try to get another router to check if it's happened because of smartplug.

Thank you

**Comment by pergolafabio** [comment]
i had the same exact issue with my xiaomi pir sensors, now as test i removed all osram smart plugs, to the xiaomi are paired directly with stick... seems more stable now

**Comment by imortkz** [comment]
I need to have a routers present in the network, so I'll try to build and add a CC2530-based router next week and test it.

**Comment by sragas** [comment]
Do have exact the same issue. Using two IKEA Tradfri repeater as router and since a few days all paired  xiaomi end devices (door and multi sensors) are not reachable any more. The ones paired with conbee stick are still functional. Could also not managed to rejoin them till now.

**Comment by aodro** [comment]
The same issue here. CC2531, CC2530+CC2591 and an ikea bulb as routers. Xiaomi devices do not work, while a ikea remote does. Maybe is only a problem with xioami devices (they do not want to use routers)?

**Comment by pergolafabio** [comment]
well, i have only 4 x xiaomi pir's paired with Conee, no routers at this moment
today 1  xiaomi lost connection too , after about 3 weeks
dont know why , but i need to pair it again, verry frustating

all connections are good, green lines

**Comment by sragas** [comment]
Also got only issues with Xiaomi end devices, all other work properly (till now).
The Xiamoi end devices paired with conbee are still working at this point (about 2 weeks now) but the other ones are unreachable after 2-3 days from pairing.

**Comment by pergolafabio** [comment]
yeah , same experience :(

**Comment by imortkz** [comment]
> The same issue here. CC2531, CC2530+CC2591 and an ikea bulb as routers. Xiaomi devices do not work, while a ikea remote does. Maybe is only a problem with xioami devices (they do not want to use routers)?

Have CC2530-based router and looks like Xiaomi sensor is stable connected for the day, and survive a 12h coordinator downtime (connected to the router).

Will see how it goes for the next couple of days.

**Comment by sragas** [comment]
@imortkz do you working with the reworked version from manup or an official release?

**Comment by imortkz** [comment]
Official Docker image

**Comment by sragas** [comment]
@manup I build the plugin from the actual master branch source including your commit to test. Unfortunately the plugin didn't get loaded if I use my self compiled version. Build on Ubuntu and used in x86 Docker Image. Are there any plans for a new official release in short term, or do you have any hints to get the self build one running?

**Comment by P1Rebo** [comment]
Any updates? Experiencing the same issues using Osram Smart Plug als repeaters. Updated ConBee (1) to the latest Firmware, using latest Deconz release. These damn Xiaomi Sensors... cheap but so much effort to get / keep them running...

**Comment by sragas** [comment]
I didn‘t manage to get the self compiled plugin to run, so as soon as v 2.05.65 is released i will give it a try. And as you said, cheap but sometimes pain in the...

**Comment by imortkz** [comment]
I've a working setup with zigbee2mqtt and two kinds of router: DIY cc2530 routers, SmartThings Outlet (IM6001-OTP05). Sensors are steady connected to the router, no issues.

Didn't tried them with deCONZ stick, but I have a strong feeling that it will be the same.

I has exactly the same constant disconnects with Osram both for deCONZ and zigbee2mqtt.

**Comment by hgelpke** [comment]
Hopefully it works with Deconz. I'm having the exact same issue and I think it might be the Tradfri repeater. I've taken it out for now and can can add a cc2530 if that helps.

**Comment by sragas** [comment]
Just updated deCONZ yesterday to v2.05.65, which may fix the issue, and repaired lost Xiaomi Aqara sensors. Till now (14h) all sensors are up and running. All paired with conbee stick or one of two tradfri repeater. Keep you posted

**Comment by sragas** [comment]
Still all sensors up and running. New release seems to fix the issue on my site.

**Comment by hawkefly** [comment]
It seems that 20200312 firmware in dev branch fix this issue

**Comment by cagnulein** [comment]
i'm still having this issue with 
version: 2.05.84 / 14/9/2020
firmware: 26580700

maybe a regression? do you have still problems?
thanks

**Comment by thueske** [comment]
I have this issue, too.

My temperature sensor works fine for several weeks, but since some days it continuously disappears / disconnects.

<img width="1120" alt="Bildschirmfoto 2020-12-15 um 19 07 05" src="https://user-images.githubusercontent.com/436986/102254307-c148e400-3f08-11eb-8a2b-1b78d112a9e3.png">

(Last time where repairing worked there were a red line before...)

Version: 2.07.01 / 8.12.2020
Firmware: 26660700

Any ideas @sragas?

**Comment by cagnulein** [comment]
@thueske i opened a new one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3929

**Comment by sragas** [comment]
@thueske Moved my place and setup all devices from scratch. Only have one device (temp sensor) which is disappearing continuously, but this may be a hardware fault. No idea how to solve this and it will be replaced soon. But my old setup runs for months without any problems.

**Comment by IgnacioHR** [comment]
I've the same or similar issue with a Xiaomi temperature sensor.
See the picture all other devices works!
In my net, there are two OSRAM bubles close to the Xiaomi sensor but the sensor it is unable to send data anymore.
If I take the Xiaomi temperature and humidity sensor closer to the RaspBee and start the sensor discovery in the gateway the sensor works (connected to the RaspBee) but once I move it to its location it disappears again. It is not discovered in its location. It was operative for about 3 months and connected to the RaspBee.
It might be:
- The battery went down a bit after 3 months of operation and now, it has no power to reach the RaspBee anymore?
- The Xiaomi sensors are unable to use a router and require direct connection to the RaspBee?
- Maybe this is NOT a RaspBee problem but a Xiaomi problem. 

![phoscon_chiton__phoscon___VNC_Viewer](https://user-images.githubusercontent.com/16385090/117259693-95de7b80-ae4e-11eb-93bd-1a1d34b6af96.jpg)
