### ISSUE TITLE
Switch toggle & scene issue

### ISSUE THREAD

**Issue by lenisko** [dresden-elektronik/deconz-rest-plugin#1495]
There is small issue with buttons assigned like that for group of lights:

![2019-05-04_19-07-18-firefox](https://user-images.githubusercontent.com/10072920/57182510-10f7aa80-6ea0-11e9-8dec-4a27659a26ab.png)

**Typical Case:**
[Lights OFF]
Pressed ON/OFF once
[Lights ON]
Pressed ON/OFF once
[Lights OFF]

**Incorrect Cases:**
[Lights OFF]
Pressed Scene once
[Lights ON]
Pressed ON/OFF once
**[Lights ON]**
Pressed ON/OFF once
[Lights OFF]

Most likely SCENE is not swapping power status value which is used for TOGGLE key?

-------
Product RaspBee
Version 2.05.63 / 4/3/2019
Firmware 26330500

**Comment by daaaaa** [comment]
Same behavior happens to me.
It would be nice if this behavior would be fixed.

**Comment by carloscae** [comment]
Yeah, this also works like this with Aqara Switches. Probably all switches.
Made me move away from switch automation on Phoscon to Home Assistant.

Switch will not pool current state of light, just change from last click. Weird.

**Comment by manup** [comment]
The issue will be fixed soon (hopefully by 2.05.66)

Currently toggle is implemented via a extra flag which isn't synchronized with the groups actual on/off state. The fix will just use the `group.any_on` flag which reflects the real state no matter how it was applied.

Related issues: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1360 https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1181

**Comment by carloscae** [comment]
@manup you deserve a huge pitcher of beer for this.

**Comment by DOliana** [comment]
@manup Version 2.05.66 was released a few days ago. I guess this fix did not make it, right?

**Comment by manup** [comment]
>@manup Version 2.05.66 was released a few days ago. I guess this fix did not make it, right?

Sadly not yet, hope to get id done asap.

**Comment by mike43525** [comment]
I am also experiencing this problem. When can I expect a fix?

**Comment by mike43525** [comment]
Hello @manup,
what's the current status? Do you even plan to fix this bug?

I am seriously considering switching to zigbee2mqtt...

**Comment by lenisko** [comment]
go away stale bot! ;-)
