### ISSUE TITLE
please add heiman water leak (HS1-WL-E) support

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#1498]
Can you please add heiman water leak (HS1-WL-E)?

![sshot-2019-05-06- 4](https://user-images.githubusercontent.com/32480002/57246912-bc3e6600-703e-11e9-8fad-ff55ca06bfd8.jpg)
![sshot-2019-05-06- 1](https://user-images.githubusercontent.com/32480002/57246913-bc3e6600-703e-11e9-8e4f-a0adc493f07c.jpg)
![sshot-2019-05-06- 2](https://user-images.githubusercontent.com/32480002/57246914-bc3e6600-703e-11e9-8aee-3d96d6048518.jpg)
![sshot-2019-05-06- 3](https://user-images.githubusercontent.com/32480002/57246915-bcd6fc80-703e-11e9-96b5-dab6d61d276f.jpg)

**Comment by ebaauw** [comment]
What's the _Manufacturer Code_ in the _Node Info_ panel?

**Comment by salopette** [comment]
![sshot-2019-05-07- 1](https://user-images.githubusercontent.com/32480002/57269266-119e6580-7087-11e9-98b3-4257f9569747.jpg)

**Comment by salopette** [comment]
Hello, has something been done? How can it test?
Should I contribute something else?

**Comment by Ronoon** [comment]
You have to look in the code section for updates in e-g- Bindings etc . Maybe it is integrated in the next version if you are lucky.

**Comment by salopette** [comment]
Hello, I have made today on V2_05_65 update.
The sensor is connected, but it does not appear in the list.
I only see it at the nodes.

**Comment by BottlecapDave** [comment]
I too am on the latest version and can't see the item in the list. I am using this in conjunction with Home Assistant, and it seems to have picked it up in there, however when the sensor is wet it's not reporting it.

I've migrated this device from Smartthings, where it was working as a "SmartSense Moisture Sensor".

**Comment by opechunka** [comment]
I'm using Domoticz. Heiman Water sensor works fine, but no battery reports. Can it be fixed? The same problem with Heiman Smoke sensor. In contrary Heyman Temperature and humidity sensor reports battery well.

**Comment by BottlecapDave** [comment]
I've taken another look at the traffic for the phoscon app. When I look at the "sensors" traffic, I can see the traffic

>  {
			"config": {
				"battery": 100,
				"on": true,
				"reachable": true
			},
			"ep": 1,
			"etag": "---",
			"manufacturername": "Heiman",
			"modelid": "WaterSensor-EM",
			"name": "WaterSensor-EM",
			"state": {
				"lastupdated": "none",
				"lowbattery": null,
				"tampered": null,
				"water": null
			},
			"swversion": "1.1.1",
			"type": "ZHAWater",
			"uniqueid": "---"
		},

Water always appears null even when the sensor is submerged in the water.

Interestingly, the api request to "sensors/new" is always reporting the water sensor back. I don't know if this means it hasn't finished setting up?

**Comment by BottlecapDave** [comment]
I've just deleted the node and attempted to add it again (pushing the tamper button after joining), and it's now picking up the wet/dry state in HA.

However like @opechunka I'm also not geting battery information, which is odd as it looks like in my last post this was populated.

I've got another water sensor to setup, so I guess we'll see what that provides.
