### ISSUE TITLE
Private beta of new app

### ISSUE THREAD

**Issue by manup** [dresden-elektronik/deconz-rest-plugin#150]
**Phoscon App**
There is a new app available as private beta which can be testet with recent deCONZ versions (ConBee, RaspBee).

To get access just leave a small note here and you will be invited to the private GitHub repository wich contains the install instructions.

Thanks in advance for any feedback.

**Comment by Hector47** [comment]
Hello,
I'm interested in the beta app :-)

Thanks

**Comment by Krocko** [comment]
I am also interested.

**Comment by AntiHeld889** [comment]
I am also interested. :)

**Comment by ebaauw** [comment]
Yes, please

**Comment by buzatu** [comment]
Hi,
Me too, please :)

**Comment by NisseDILLIGAF** [comment]
I'm interested :)

**Comment by mploetne** [comment]
I'm also interested.
Thank you
Marko

**Comment by snozzlebert** [comment]
Yes, please.

**Comment by dghh** [comment]
I´m also very interested, thanks.

**Comment by wvuyk** [comment]
Interested too here

**Comment by posixx** [comment]
Same here!

**Comment by grover** [comment]
I'm interested. Would be good as I'm just starting.

**Comment by shayanhaider** [comment]
I'm interested too. Looking forward to trying out the new app.

**Comment by YoungCereal** [comment]
More interested me is the app an only deamon no XServer interface ? than check me in ;)

**Comment by manup** [comment]
> More interested me is the app an only deamon no XServer interface ? than check me in ;)

Still experimental, but you can start deCONZ without running X11 server.

    $ deCONZ -platform minimal --http-port=8080 --dbg-info=1

To start deCONZ at boot time use the *systemd* service:

    $ systemctl enable deconz

**Comment by YoungCereal** [comment]
Naja wir sind ja beide deutsch ;)
nien ich habe ein System das ohne display oder grafischen Output ist und da ich mit dem gesamten Xserver echt zu viel Ressourcen verbrauche ist das nicht wirklich ne Lösung für mich.
Was ist eigentlich der unterschied zur neuen App ?

gruß
Michael

**Comment by manup** [comment]
> Naja wir sind ja beide deutsch ;)

stimmt aber hier bei GH bitte englisch bleiben damit jeder was versteht :)

>nien ich habe ein System das ohne display oder grafischen Output ist und da ich mit dem gesamten Xserver echt zu viel Ressourcen verbrauche ist das nicht wirklich ne Lösung für mich.

Only a few megabytes for the X11 libs on sd-card, with todays sd-card sizes and prices this is hardly a real life dealbreaker.

deCONZ is able to run completely headless now, getting rid of X11 entirely will take some time and has no high priority due the the minimal benefits (safe 20-30 MB for X11 libs).

> Was ist eigentlich der unterschied zur neuen App ?

It's a complete overhaul of the old one with expanded device support.

**Comment by alexsporn** [comment]
Count me in!

**Comment by pfleghar** [comment]
Das ist spannend ... bin sehr interessiert an der Beta!

**Comment by rtenklooster** [comment]
Yes, I would like to give it a try!

**Comment by ebaauw** [comment]
>Thanks in advance for any feedback.

Be careful what you wish for ;-)

**General Impression**
- I really like where this is going.  The UI is refreshing
- The login screen asks for _Passwort_ (in German).
- App works over VPN!
- Would like to see support for sorting for Groups, Lights, Switches, Sensors on ID, Name, Type, Manufacturer, Model.

**Groups**
- Regular groups are reverse ordered by group ID, groups for switches are ordered on sensor ID.
- Took me a while to realise these are the groups linked to the switches, not the switches themselves.
- Hidden groups are shown anyway.
- Groups linked to not yet supported switches (yes, I’m talking about my ubisys dimmer ;-) are not shown at all.  Maybe show these as regular groups until support for the switch is added?
- Why the reduced functionality (no scenes, schedules, sensor controls) for groups linked to switches?
- I would put the slider for _Brightness_ to the left, and _Hue_ / _Saturation_ or _Temperature_ sliders to the right: easier on the eye when switching between these or between lights of different types.  Also, place the icon to switch between _Color_ and _Temperature_ under the _Color_ or _Temperature_ slider.
- The _Color_ on the slider doesn’t match the light colour.  You really need to do RGB to CIE conversion in the app and use `xy` instead of `hue` and `sat` - see Hue developer’s guidelines.  Alternatively, implement this in the deCONZ REST API - best discuss this in a different issue.
- The _Temperature_ slider doesn’t take into account min/max supported values (needs API support as well, see issue #123).

**Settings**
- App doesn’t allow changing the date/time format.
- Open Gateway is missing.

**Lights**
- My OSRAM plug shows as an outlet icon instead of a bulb icon - nice.  I take it, the icon is from the `type`?  Would be nice to show spots vs bulbs, etc like the Hue app, but this would require whitelisting lights and associated icons.  Maybe different icons for different types of light (Dimmable Light, Color Temeperature Light, etc), or maybe add a column for _Type_.
- Detailed window misses label for _Version_.  Maybe add _Date Code_ and _Type_?
- Lights are sorted on ID, as with the API.  I like that, because I hacked the database so my lights are numbered in the right order.  For less neurotic users, order on Name or custom defined order would make more sense.  Or add ID and allow sorting on columns.

**Switches**
- Love this screen, although I’m deeply disappointed that my Xiaomi smart cube isn’t shown ;-)
- Order is by sensor ID.
- Detailed window: 
  - maybe add _Date Code_, _Last Button Pressed_ (incl. date/time);
  - Would like option to enable/disable the switch (once we have `config.on` working in the API, see issue #90);
  - I expect we’ll be able to click the buttons on the image to set rules?

**Sensors**
- Love this screen!
- Order is by sensor ID.
- Motion symbol (walking man) is not really clear in showing the difference between motion and no motion.  Maybe add colour, or use different symbols (cf. traffic light symbols: stopped man vs walking man).
- Having two decimals for temperature and humidity makes no sense, given the accuracy of the sensors - just round to nearest integer.
- Detailed window, general:
  -  Would like option for to enable/disable the sensor (once we have `config.on` working in the API, see issue #90).
- Detailed screen Hue motion sensor:
  - Icon is too big for iPad - text is shown below instead of next and doesn’t scroll so _Temperature_ and _Refreshed_ cannot be seen.
  - Would like different _Refreshed_ values for Motion, Light level and Temperature.
  - Would like config options for `duration`, `tholddark`, `tholdoffset`, and for `sensitivity`, `ledindication`, and `usertest` (once we have these working in the API, see issue #20).  Maybe add wizzard for calibrating light level and sensitivity, cf. Hue app.

**Comment by bdickhaus** [comment]
I am interested.

**Comment by manup** [comment]
@ebaauw Thanks for comprehensive review, very good points which we'll address soon there possible..

>General Impression

> * I really like where this is going. The UI is refreshing
> * The login screen asks for Passwort (auf Deutsch).

Will be fixed asap, there are more translations which will be fixed soon. We also consider https://pontoon.mozilla.org/ to support more languages in the future.

> * App works over VPN!

Yes in the end it just connects to the gateway via its IP, supporting *common* subnets and anything WebRTC provides. In comparison to the old web app it doesn't need to run on the same origin (gateway). When WebRTC will be supported in full, access will also work remotely without needing a VPN in a secured peer-to-peer fashion.

> * Would like to see support for sorting for Groups, Lights, Switches, Sensors on ID, Name, Type, Manufacturer, Model.

Absolutely we plan to add sorting &mdash; also via drag and drop &mdash; to all of those, once the basics are solid. For some lists we will also add filtering to quickly find devices and lights by any characteristic.

> **Groups**

> * Regular groups are reverse ordered by group ID, groups for switches are ordered on sensor ID.
> * Took me a while to realise these are the groups linked to the switches, not the switches themselves.

The idea is that switches are just switches to which lights can be assigned. Currently scenes are only supported for normal light groups (3 bulb icon) and switches which support scenes via ZLL Scene Cluster (JUNG, GIRA, Busch-Jaeger, dresden elektronik).

Switches like Philips Hue dimmer or the IKEA Switch don't send *recall scene* commands, which is why the scenes button is not active for them yet. Once we figured out a simple way to configure "custom" commands for buttons in the UI these will follow.

Since lights can be assigned to multiple switches and groups pressing the buttons should also update the lights state in the group.

> * Hidden groups are shown anyway.
> * Groups linked to not yet supported switches (yes, I’m talking about my ubisys dimmer ;-) are not shown at all. Maybe show these as regular groups until support for the switch is added?

> *Why the reduced functionality (no scenes, schedules, sensor controls) for groups linked to switches?

See the commend above, currently this is like a whitelist: Scenes are supported for some switches, for sensor controls we have decided it is easier to configure *sensor controls* for a normal group and in there assign sensors and switches which should act in the specific sensor control.

Imagine a *sensor control* for a long floor with multiple motion sensors and switches.

> * I would put the slider for Brightness to the left, and Hue / Saturation or Temperature sliders to the right: easier on the eye when switching between these or between lights of different types. Also, place the icon to switch between Color and Temperature under the Color or Temperature slider.

Makes sense, we'll adjust that soon.

> * The Color on the slider doesn’t match the light colour. You really need to do RGB to CIE conversion in the app and use xy instead of hue and sat - see Hue developer’s guidelines. Alternatively, implement this in the deCONZ REST API - best discuss this in a different issue.

Yes we'll add more fine tuned color modes respecting the specific capabilities of the devices over time. Hue saturation was chosen as start since most devices support it (albeit it's not very precise).

> * The Temperature slider doesn’t take into account min/max supported values (needs API support as well, see issue #123).

Agree, that's already on my todo list :)

> **Settings**

> * App doesn’t allow changing the date/time format.

Our ultimate goal is to let the app determine the correct date/time format on it's own. Currently this is not very sophisticated and fails in many cases, but it should be possible. The plan is to decide afterwards if a manual changing should be implemented too.

> * Open Gateway is missing.

This will be added soon (to fake the Hue push button pressed).

> **Lights**

> * My OSRAM plug shows as an outlet icon instead of a bulb icon - nice. I take it, the icon is from the type? Would be nice to show spots vs bulbs, etc like the Hue app, but this would require whitelisting lights and associated icons. Maybe different icons for different types of light (Dimmable Light, Color Temeperature Light, etc), or maybe add a column for Type.

Yes that's planned, for switches and sensors we already created tables to provide meaningful human readable product names and icons. For lights these will follow.

> * Detailed window misses label for Version. Maybe add Date Code and Type?

Strange, I'm sure there was a label once, should be back soon. Agree the Date Code can be added too. For the type the device tables will be used to provide translated friendly types.

> * Lights are sorted on ID, as with the API. I like that, because I hacked the database so my lights are numbered in the right order. For less neurotic users, order on Name or custom defined order would make more sense. Or add ID and allow sorting on columns.

Sorting right now is more or less by accident :) as mentioned above this will be improved in various ways.

> **Switches**

> * Love this screen, although I’m deeply disappointed that my Xiaomi smart cube isn’t shown ;-)

Not yet colleges are very keen to add this too, so it shouldn't take too long :)

> * Order is by sensor ID.
> * Detailed window:
>    * maybe add Date Code, Last Button Pressed (incl. date/time);

Yes will definitely be considered.

>    * Would like option to enable/disable the switch (once we have config.on working in the API, see issue #90);

Depends, for switches which are entirely controlled by rules this works, but it could be confusing if a user can disable a switch but it continues to work anyway, like the IKEA switch buttons which sens group casts.

>      * I expect we’ll be able to click the buttons on the image to set rules?

This will will be added somehow, but we still don't have a clear vision how. It's tricky to provide something powerful which could also be configured by average users.

> **Sensors**

> * Love this screen!

Thanks :) it's a early version, I like the realtime view via websockets. We'll add further icons and improved details to this view.

> * Order is by sensor ID.
> * Motion symbol (walking man) is not really clear in showing the difference between motion and no motion. Maybe add colour, or use different symbols (cf. traffic light symbols: stopped man vs walking man).

This should be fixed now, currently by a simple filled symbol for detected motion.

> * Having two decimals for temperature and humidity makes no sense, given the accuracy of the sensors - just round to nearest integer.

Agree

> * Detailed window, general:
>     * Would like option for to enable/disable the sensor (once we have config.on working in the API, see issue #90).

I think in comparison to switches it will be easier to implement this here, since sensors will most likely be controlled via rules.

> * Detailed screen Hue motion sensor:
>     * Icon is too big for iPad - text is shown below instead of next and doesn’t scroll so Temperature and Refreshed cannot be seen.

Should be fixed very soon.

>     * Would like different Refreshed values for Motion, Light level and Temperature.

I've also noticed that, makes sense, the UI should then be more polished to not overload it.

>     * Would like config options for duration, tholddark, tholdoffset, and for sensitivity, ledindication, and usertest (once we have these working in the API, see issue #20). Maybe add wizzard for calibrating light level and sensitivity, cf. Hue app.

The ledindication will arrive first (since many sensors provide it). Albeit it will take a while a wizard for the further configuration should be possible.

Thanks again for the review, this is very helpful. We will improve and update the app regularly like the beta versions.

**Comment by wizkidorg** [comment]
I would like to try the new Beta App.

**Comment by adsmf** [comment]
Another interested in the beta.

**Comment by wizkidorg** [comment]
Any update on the private beta app?

**Comment by manup** [comment]
>Any update on the private beta app?

Hi, yes we are currently fixing a few bugs and UX issues based on feedback, during the week you will get access to the app.

**Comment by holli73** [comment]
i'm interested as well

**Comment by felixstorm** [comment]
I would also like to to try the new beta app.

**Comment by stefan-kaiser** [comment]
I like to participate too.
Thanks in advance!

**Comment by CannyDuck** [comment]
Please give me a chance to test it. Thanks.

**Comment by mtornblad** [comment]
I would like to test it out also!

**Comment by Yannic-HAW** [comment]
I would like to be beta tester as well

**Comment by mrmadcow** [comment]
Hi, I'd be interested too, please.

**Comment by abmantis** [comment]
Hey, I would be glad to test it too, please.

**Comment by wizkidorg** [comment]
Any update on the availability of the Private beta?

**Comment by manup** [comment]
> Any update on the availability of the Private beta?

Yep, sorry for the delay as usual it takes longer than expected :/ we had to rethink a few ux choices, which I wanted to be solved before inviting more people &mdash; details matter. These changes will be finished within the coming days and I post here when invitations are out.

**Comment by snillevilla** [comment]
Hi, just found this. I am a huge fan of your products and am really, really interested to test the app. Please invite!

**Comment by maikburd** [comment]
Hello,

I'm verry interested. Can you invite me please?

**Comment by sandman72** [comment]
I started to play around with the "old" app this weekend and ran into a few limitations.

I would love to try out the new version. Please invite me!

**Comment by to0b** [comment]
Hello everyone,

I'm intrested to test the new Software. Could you please invite me?

**Comment by markuspf** [comment]
I would like to try the new app, too.

**Comment by GatoPharaoh** [comment]
hi :)
I'm verry interested. Can you invite me please?

**Comment by manup** [comment]
Took a while; invitations are out, please make sure to use latest version of deCONZ :)

**Comment by mysteryan** [comment]
I need an invite

**Comment by ronaldvans** [comment]
I would appreciate an invite as well!

**Comment by etique57** [comment]
@manup more than willing to test the new beta app ;)

**Comment by banjohb** [comment]
Hey :) Want test the beta too. Please invite *_*

**Comment by oleg77s** [comment]
it is interesting to me to test a new app

**Comment by andrejem** [comment]
Hey, I also want to try out. thx.

**Comment by dkmh** [comment]
If testing is still in progress, please add me in.

**Comment by woodkazor** [comment]
Please let me test it! Dankeschön

**Comment by knappkaj** [comment]
Hi, I would like to have an access to the BETA Repo. Thank you in advance.
Best regards from Austria.

**Comment by ziggyre** [comment]
Very good work! Please invite me. :-)

**Comment by manup** [comment]
Invitations are out, please make sure to use latest version of deCONZ.
Ubuntu and Windows versions will be updated during the next days too.

**Comment by josefku** [comment]
Hallo, I would like to have an access to the BETA App. Thank you.

**Comment by basty2** [comment]
I would like to test the beta App.

**Comment by ensamresande** [comment]
Interested!

**Comment by sparkcz** [comment]
Please invite me, thanks.

**Comment by simonporter007** [comment]
More than willing to give this a go!

**Comment by manup** [comment]
invitations sent out, hope to get the app public in the next days.

**Comment by det-box** [comment]
Please invite me, thanks.

**Comment by Kohle81** [comment]
I am interested too. Please invite me ;-)

**Comment by manup** [comment]
done :)

**Comment by Larsn1** [comment]
I would like to help too

**Comment by spedja** [comment]
Please invite me, thanks.

**Comment by etique57** [comment]
I tried assigning scenes to the left/right button of the Tradfri remote in the Phoscon app, but it does'nt work. Then the main (center) button simply switches from one scene to another when pushed.

**Comment by manup** [comment]
Currently assigning scenes (or any specific action) to switch buttons is not supported by the app. Only the default actions work. For the IKEA remote that is toggle, dimming and color temperature control.

Later on we will provide a editor to allow to assign any action to a switch button, this will happen in early 2018. Till then the same can only be achieved by creating rules with the REST API.

**Comment by tseel** [comment]
Please invite me, thanks.

**Comment by manup** [comment]
@tseel 

the beta is public now:

https://github.com/dresden-elektronik/phoscon-app-beta

**Comment by ldplusse** [comment]
Any news on getting the Cube in the Phoscon app.
I have 3 Xiaomi Cubes and they do still not show in Phoscon.
There can be controlled from HomeSeer.

I am using DeCONZ .99

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
