### ISSUE TITLE
Compiling error QNetworkAccessManager in rest_rules.cpp:1625

### ISSUE THREAD

**Issue by ma-ca** [dresden-elektronik/deconz-rest-plugin#1503]
The latest commit fails to compile `rest_rules.cpp` on Raspbian stretch with the error:
```
rest_rules.cpp: In member function ‘int DeRestPluginPrivate::handleWebHook(const RuleAction&)’:
rest_rules.cpp:1625:102: error: no matching function for call to ‘QNetworkAccessManager::sendCustomRequest(QNetworkRequest&, const char*, const char*)’
     if (webhookManager->sendCustomRequest(req, qPrintable(action.method()), qPrintable(action.body())) != nullptr)
                                                                                                      ^
...
candidate: QNetworkReply* QNetworkAccessManager::sendCustomRequest(const QNetworkRequest&, const QByteArray&, QIODevice*)
```
Raspbian stretch has Qt5 version 5.7.1 installed. 

But the failed function `QNetworkReply *sendCustomRequest` with the matching arguments is available from Qt 5.8.

https://doc.qt.io/qt-5/qnetworkaccessmanager.html#sendCustomRequest-1

> This is an overloaded function.
Sends the contents of the data byte array to the destination specified by request.
This function was introduced in Qt 5.8.

The same function with other arguments are available from Qt 4.7.

**Comment by ebaauw** [comment]
Same here.

**Comment by manup** [comment]
Oops on it, commit was made with newer Qt version.
