### ISSUE TITLE
End device removal problem

### ISSUE THREAD

**Issue by lenisko** [dresden-elektronik/deconz-rest-plugin#1505]
I have some trouble removing devices from network, steps I took:

- Add new device
Device is successfully added
- Remove it via `Delete switch` from Phoscon App
Device disappears from network
- Removed battery from switch
- Wait a few seconds
After some time it's getting re-added.

Problematic devices:
* WXKG11LM
* Xiaomi Motion Sensor (same problem)

Few screens below

---

1. Successfully added device
![2019-05-10_04-31-56-tvnviewer](https://user-images.githubusercontent.com/10072920/57498689-2ffd9e80-72dd-11e9-8e10-d33fb1c24eb0.png)

2. Removal step
![2019-05-10_04-32-05-firefox](https://user-images.githubusercontent.com/10072920/57498690-30963500-72dd-11e9-90eb-d3fd8cf53e45.png)

3. Device is removed
![2019-05-10_04-32-10-tvnviewer](https://user-images.githubusercontent.com/10072920/57498707-4c014000-72dd-11e9-80b6-21786b1c6267.png)

4. And it's re-added?
![2019-05-10_04-33-29-tvnviewer](https://user-images.githubusercontent.com/10072920/57498692-32f88f00-72dd-11e9-86f4-f9a91d2b86fa.png)

---

Product RaspBee
Version 2.05.63 / 4/3/2019
Firmware 26330500

**Comment by Smanar** [comment]
Its something that can happen, it's because "neighbour table"
More info here, just wait some days before retrying to remove it.

**Comment by lenisko** [comment]
@Smanar how can I remove it, after it was removed from the page? also `here` is missing an URL ;-)

**Comment by Smanar** [comment]
Oups sorry, the link is here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1375
In fact ATM you need to wait some time for the "cached data" be cleared, and after that just make like you have done previously. Delete it in phoscon, and check in deconz if it's ok, else you can try to select the node in deconz and press delete key on keyboard.

**Comment by lenisko** [comment]
Thank you @Smanar !
