### ISSUE TITLE
Websocket and light return

### ISSUE THREAD

**Issue by zoic21** [dresden-elektronik/deconz-rest-plugin#1507]
Hello,

I wonder why when in websocket we have a message from sensor I have uniqueid but when it's light I don't have uniqueid. It's little anoying because I used this uniqueid to find which command I need to update.

Another question, for light uniqueid always end with -03 ? 

Thank in advance.

**Comment by Smanar** [comment]
???
You don't have uniqueid for light ? On my side I have
`2019-05-10 16:14:51.013 (deCONZ) ###### WebSocket Data : {'state': {'on': False, 'reachable': True, 'bri': 254, 'xy': [0.4962, 0.3527], 'hue': 0, 'x': 32520, 'y': 23116, 'sat': 0, 'alert': None, 'colormode': 'xy'}, 'r': 'lights', 'e': 'changed', 't': 'event', 'id': '2', 'uniqueid': '90:fd:9f:ff:fe:83:1d:17-01'}`
And nope, on my exemple the uniqueid end with "-01"
The last part in uniqueID is the endpoint.

**Comment by zoic21** [comment]
No I only have : 
`{"e":"changed","state":{"y":15609},"id":"1","t":"event","r":"lights"}` or 
`{"e":"changed","id":"1","r":"lights","state":{"on":false},"t":"event"}`

Only deconz id not uniqueid....

**Comment by Smanar** [comment]
On the config try to check the option called "websocketnotifyall", set it to "true".
But I never have same socket return than you, IDK if it's something normal.
Which one version have you ?

**Comment by manup** [comment]
@zoic21 which deCONZ version are you using?

**Comment by zoic21** [comment]
It's 2.5.25 so pretty old, I don't see that, I will ask user to update it.

**Comment by manup** [comment]
Yes it was added in later version 2.05.44 so updating should fix the issue.

**Comment by zoic21** [comment]
Ok after update all it's ok, thank for your reply, sorry for this stupide question...
