### ISSUE TITLE
How to SSH rasberry pi 3 b+ when using deCONZ ? 

### ISSUE THREAD

**Issue by lina7500** [dresden-elektronik/deconz-rest-plugin#1508]
I can't SSH the rasberry pi 

When I select network options i get
N1 Hostname
N2 Wi-Fi
N3 Network interface

I select Wi-Fi 
it says that it could not communicate with wpa-supplicant
Can assign a static address to the rasberry pi ? would that solve the problem ? 

the ifconfig command gives the following output 
...
wlan0: flags=4163<UP, BROADCAST,RUNNING,MULTICAST> mtu 1500
           inet 192.168.8.1 netmask 255.255.255.0 broadcast 192.168.8.255
          inet6 
...

**Comment by manup** [comment]
This is not related to deCONZ.
You need to check *Interfacing Options > SSH* in the `raspi-config` tool.
