### ISSUE TITLE
Switch: on/off action (depending on actual light status)

### ISSUE THREAD

**Issue by rendgeor** [dresden-elektronik/deconz-rest-plugin#1510]
How is it possible to switch the lamps on/off regarding the actual state.

For example: actual scene (one of 3 lights on)
on/off button should switch off the light rather than switching o the other two.

In Hue rules like: 
- if at least one light on then off-action
- if no light is on the on-action

In Phoscon there isn any option:
![image](https://user-images.githubusercontent.com/10161748/57574674-a3b6bd00-743d-11e9-9b06-f9da5ea1daa0.png)

Is it possible to create such rules using the REST-api?

Extension of this could also enable daily dependent default scenes: like dimmed at night and bright at dinner time.

**Comment by manup** [comment]
Basically all the switch editor does is creating rules via the REST-API, so the easiest way is to just look at the created rules. Depending on the switch action some are more complex than others.
