### ISSUE TITLE
Get network node link for map in rest api

### ISSUE THREAD

**Issue by zoic21** [dresden-elektronik/deconz-rest-plugin#1515]
Hello,

Are they any solution to get node link in deconz api ? I want to add network map of node but I can't find any solution get link between node...

**Comment by sebastianlorenzen** [comment]
Any comments from Dresden Elektronik?
I'm also interested in such a feature.

**Comment by manup** [comment]
Currently there is not supported way to get a map via the api, there is only an old connectivity api but it isn't maintained anymore.

However I can image such a feature or raw Zigbee passthrough via Websockets will be available in the future.

**Comment by kotarokun** [comment]
Is here any new Infos about?
