### ISSUE TITLE
Xiaomi Multisensor reports each value as a seperate Sensor

### ISSUE THREAD

**Issue by JoschaMiddendorf** [dresden-elektronik/deconz-rest-plugin#1527]
My Xiaomi Multisensors are reporting each value as a separate Sensors via API.
That means the API shows 3 Sensors for every Multisensor
Temperature, Humidity and Pressure.
That means I have to subscribe to 24 Sensors to get all the Values for just 8 Physical Multisensors. Not very Elegant! 
Is there any option to put all measured values in one API reported Sensor as it is shown in Phoscon and as the Xiaomi Vibration sensor realizes it?

**Comment by Smanar** [comment]
Nope, because you have 1 device sensor by cluster (and 1 by endpoint)
IDK what you are doing with the API, but for exemple you can manage the 3 sensors to make only one with the application that use the API.

**Comment by JoschaMiddendorf** [comment]
I don’t really understand what you mean with „1 device sensor by cluster (and 1 by endpoint)„. In Phoscon the sensor is shown as one. And on the API another sensor, the Xiaomi Vibration Sensor is also shown as one sensor with multiple values. 
battery
orientation
reachable
temperature
tiltangle
vibration
vibrationstrength

Why can’t Temperature, Humidity and Pressure be reported together as the vibration sensor is doing it?

I’m using the API to integrate the Sensor Values in my Smart Home Systen (FHEM).

**Comment by chimpy** [comment]
Does your sensor look like this?

<img width="883" alt="Screenshot 2019-06-23 at 19 21 18" src="https://user-images.githubusercontent.com/380577/59979743-d7176a80-95eb-11e9-9327-0f56cb841451.png">

<img width="817" alt="Screenshot 2019-06-23 at 19 21 23" src="https://user-images.githubusercontent.com/380577/59979744-daaaf180-95eb-11e9-939b-682b5cf7eca0.png">

**Comment by JoschaMiddendorf** [comment]
Yes it does. Besides the picture and an additional Pressure value. Hence I’m using the Aqara type Mulisensor.
