### ISSUE TITLE
Xiaomi Aqara Multi Sensor - Battery value is no longer shown

### ISSUE THREAD

**Issue by holdestmade** [dresden-elektronik/deconz-rest-plugin#1528]
Used to have battery level shown and battery_level attribute in Home Assistant.

Other Aqara sensors still have the battery shown

Copied from Phoscon App:

Multi Sensor:
```
Vendor  Xiaomi
Product  Multi Sensor
Version  unknown
Air pressure  1007 hPa
Temperature  20 °C
Humidity  56 %
Refreshed  05/20/2019 11:29:02 AM
```

Window / Door Sensor:
```
Vendor  Xiaomi
Product  Window / Door Sensor
Version  20161128
Battery  91 %
State  closed
Temperature  21  °C
Refreshed  05/20/2019 11:02:10 AM
```

**Comment by Smanar** [comment]
Hello, there is already a correctif (to test), just wait for it https://github.com/dresden-elektronik/deconz-rest-plugin/commit/31ef3962a4507e6310c23e4c497278f1fedb050b

**Comment by JoschaMiddendorf** [comment]
Will that be implemented any time?

**Comment by Smanar** [comment]
It is. Still not working on your side ?

**Comment by JoschaMiddendorf** [comment]
I'm sorry, it works fine. Thank you.

**Comment by bratanon** [comment]
Same issue here with the temperature sensor. Running 2.05.69

```
Vendor  Xiaomi
Product  Multi Sensor
Version  unknown
Air pressure  1003 hPa
Temperature  25 °C
Humidity  43 %
Refreshed  10/03/2019 12:40:39 AM 8 minutes ago
``

**Comment by govido** [comment]
Hi, im running deconz 2.05.72 and added 3 Aqara multisensors today (new pressure version).
I'm missing version and battery as well, also 1 of my 2 Aqara buttons (gyro) doesn't report the battery level. The other one does...
Is there a problem with the pairing process?
