### ISSUE TITLE
Support for Develco smoke sensor

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#1534]
Hi there,

I'm hoping to get the smoke sensor integrated in deconz. Interestingly, it was quite a hassle to have it paired so the clusters become visible but what you can pull out of it seems quite useless (similar to [#1294](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1294)). However, I managed to find the [Technical manual](https://www.develcoproducts.com/media/3374/smszb-120-technical-manual-smoke-alarm.pdf), hoping that's equally good.

Thanks!

Edit:
![3](https://user-images.githubusercontent.com/4005212/58288951-57f90180-7db5-11e9-8e40-cabd6c4f2a07.jpg)
![1](https://user-images.githubusercontent.com/4005212/58288952-57f90180-7db5-11e9-9c6c-8c0e77dfef9c.jpg)
![2](https://user-images.githubusercontent.com/4005212/58288953-58919800-7db5-11e9-9c5f-123236774144.jpg)

**Comment by ebaauw** [comment]
Interesting, this looks like the first smoke detector whose siren can be activated remotely.  Where did you buy it?

**Comment by SwoopX** [comment]
:) Always looking for interesting stuff. I actually bought it as new at ebay Kleinanzeigen for 40€ after some research regarding zigbee smoke detectors. Just found 2 shops really selling them. The one associated to ubisys in GER (78€) and Cozify in FI (~49€)

**Comment by b2un0** [comment]
You cal also activate the siren on Xiaomi MiJia Honeywell smoke detector

https://github.com/Koenkk/zigbee2mqtt/issues/420

**Comment by SwoopX** [comment]
> you can also activate the siren on Xiaomi MiJia Honeywell smoke detector

Might bentrue but as farmasmI know, those do not have necessary certifications to be officially operated in Europe. The Develco‘s do ;)

**Comment by ebaauw** [comment]
> you can also activate the siren on Xiaomi MiJia Honeywell smoke detector

That's not what I read.  Apparently, they managed to activate the sensor's self-test remotely (causing it to beep), but it doesn't support the _IAS_WD_ cluster.

**Comment by ma-ca** [comment]
The Bitron 902010/24 smoke detector with siren has an _IAS_WD_ cluster that can be used to remotely start the siren.

**Comment by ebaauw** [comment]
Cool, I totally missed that.  Does the REST API expose the _IAS WD_ cluster as a `/lights` resource (as it does for the Heiman Siren)?  I didn’t see that in your PR from January.

**Comment by SwoopX** [comment]
@manup Mind taking a look at this and flag it for device integration? Much appreciated!

**Comment by ma-ca** [comment]
I have created PR #1593 for siren support on smoke sensors. I also added the Develco smoke sensor to supported devices.

**Comment by Smanar** [comment]
@SwoopX, sorry to make the undertaker, but this device is fully supported ATM or partially ?

**Comment by SwoopX** [comment]
Fully, why?

**Comment by Smanar** [comment]
I m reading your comment about the 2 clusters, this device create both ? the ZHAFire and the one for the siren ?

**Comment by SwoopX** [comment]
The stuff here is 2 years old and I now got 6 of them 😂

You get 2 sensors (fire and temperature) + 1 light for the siren.

**Comment by labaland** [comment]
The on/off switch for siren is not working correctly :( I just bought this as my wake up alarm :( i can start alarm but disable is not easy :/ any help ?

**Comment by SwoopX** [comment]
Erm, you're using the smoke detector's siren as a wakeup alarm? You must be even more desperate than I am to not oversleep :)

Regardless, which on/off switch, the device doesn't have any? You can silence any alarm giving the device a firm press.

**Comment by labaland** [comment]
> Erm, you're using the smoke detector's siren as a wakeup alarm? You must be even more desperate than I am to not oversleep :)
> 
> Regardless, which on/off switch, the device doesn't have any? You can silence any alarm giving the device a firm press.

i have so hard to wake up  my alarm clocks, i can sleep 1 hour to my "sonic boom" alarm clock :(

I have this entity on the siren: 
![image](https://user-images.githubusercontent.com/20958435/154584492-1afd6208-2bbd-4d17-b001-4376bb3b6092.png)

**Comment by labaland** [comment]
When i turn on the switch it instantly turn it self off, but the siren starts, where can i report so they can fix it ?

**Comment by dc911x** [comment]
@labaland Did you find a solution for this? My Frient smoke alarm (rebrand of the develco) also does the same.

When turning on the alarm, the switch turns off immediately and the alarms starts beeping. Only way to stop it is to press the "test" button. Also after a while it starts beeping again. It always needs 2 presses.

I wouldn't use it as a wake up alarm but was looking into using it as a burglar alarm.

**Comment by Smanar** [comment]
Are you sure it s not a problem from the third app ?
If I m right you can trigger the siren using "alert":"select" and dtop it using "alert":"none".

**Comment by dc911x** [comment]
> Are you sure it s not a problem from the third app ? If I m right you can trigger the siren using "alert":"select" and stop it using "alert":"none".

Haven't tried it with those settings only with the build-in toggle from HA. I'll try when I got a moment.

![afbeelding](https://user-images.githubusercontent.com/49455017/162184527-b0d664e5-dc57-4147-b625-c4fbdc144e4e.png)
