### ISSUE TITLE
Support request for LifeControl MCLH-08

### ISSUE THREAD

**Issue by bastshoes** [dresden-elektronik/deconz-rest-plugin#1540]
I would like to ask for support of LifeControl MCLH-08. This enviroment sensor which provide information about temperature, humidity, eCO2 and VOC. Screen shots of clusters below.
![image](https://user-images.githubusercontent.com/22978694/58323137-c2e51f80-7e2b-11e9-9269-21c0dff50346.png)
![image](https://user-images.githubusercontent.com/22978694/58323151-d1cbd200-7e2b-11e9-8536-04392dfa8e62.png)
![image](https://user-images.githubusercontent.com/22978694/58323171-dee8c100-7e2b-11e9-92ea-8d22e002f32b.png)
![image](https://user-images.githubusercontent.com/22978694/58323197-f0ca6400-7e2b-11e9-92b8-738cf6e29026.png)
![image](https://user-images.githubusercontent.com/22978694/58323241-10618c80-7e2c-11e9-90a4-82c4976c60cd.png)
![image](https://user-images.githubusercontent.com/22978694/58323255-1fe0d580-7e2c-11e9-843f-8a2bba9a7aaa.png)
![image](https://user-images.githubusercontent.com/22978694/58323270-2e2ef180-7e2c-11e9-8b38-151b8f046052.png)

Measured parameters located in Temperature measurement cluster.

0x0000 Measured Value - Temperature value. Should be divided by 100 
0x0001 Min Measured Value - Humidity value. Should be divided by 100
0x0002 Max Measured Value - eCO2 value in ppm
0x0003 Tolerance - VOC value in ppm. Should be divided by  10000.

**Comment by bastshoes** [comment]
Trying to implement support of this sensor my self. Got a few questions.
1. There is no finggerprint for VOC sensor. Can I just add SensorFingerprint  fpVolatileOrganicCompoundsSensor?
2. How to deal with sensor which hold all his values in Humidity cluster under different endpoints?

**Comment by MadMonkey87** [comment]
Hey @bastshoes 
Where did you buy this sensor, is it available anywhere?

**Comment by bastshoes** [comment]
It's available in Russia and on aliexpress
LifeControl Store - https://a.aliexpress.ru/_eOyIy0
