### ISSUE TITLE
Support request for LifeControl MCLH-03

### ISSUE THREAD

**Issue by bastshoes** [dresden-elektronik/deconz-rest-plugin#1541]
I would like to ask for support of LifeControl MCLH-03 - smart plug.
Actually it working for switching. But it also supports metering. Screen shots of clusters below:
![image](https://user-images.githubusercontent.com/22978694/58323687-5f5bf180-7e2d-11e9-9942-e75b988d0de6.png)
![image](https://user-images.githubusercontent.com/22978694/58323709-700c6780-7e2d-11e9-844f-5d329257913f.png)
![image](https://user-images.githubusercontent.com/22978694/58323719-7f8bb080-7e2d-11e9-8c46-779898711a4d.png)
![image](https://user-images.githubusercontent.com/22978694/58323767-a518ba00-7e2d-11e9-920d-c32f643ecf92.png)
![image](https://user-images.githubusercontent.com/22978694/58323798-b661c680-7e2d-11e9-87a0-4e699a2c0eb1.png)
![image](https://user-images.githubusercontent.com/22978694/58323817-c2e61f00-7e2d-11e9-8dec-ab1b9a1d9711.png)
![image](https://user-images.githubusercontent.com/22978694/58323848-d5f8ef00-7e2d-11e9-9aa5-9133a1b63b8d.png)
![image](https://user-images.githubusercontent.com/22978694/58323957-283a1000-7e2e-11e9-8936-e9afd95553e0.png)

**Comment by bastshoes** [comment]
Could you provide general guide line how to add sensors with power consumption for plug? I'll try to do it myself.

**Comment by gonczarov** [comment]
make support please

**Comment by bastshoes** [comment]
Support added via PR#1726
