### ISSUE TITLE
WXKG01LM Stating only battery level.

### ISSUE THREAD

**Issue by ispiropoulos** [dresden-elektronik/deconz-rest-plugin#1545]
On the latest version of deConz I pair a Mijia round switch (WXKG01LM) but it does not report state.
![773F9800-3709-42DB-A2E6-4EBE36EDAECF](https://user-images.githubusercontent.com/2028642/58373924-10ea4800-7f3e-11e9-840c-8bdf3230da17.png)

Only on Hass.io via the deConz addon there is an entity created just for battery level.
![7DEAD645-390E-40F6-877E-DEC5A1CDA965](https://user-images.githubusercontent.com/2028642/58373881-aafdc080-7f3d-11e9-99d6-86cef7979db4.png)

I have tried several switches with the same result (I actually bought 10 because I saw they were compatible and I’ve tried 4-5 of them)

**Comment by bastshoes** [comment]
Switches do not have states. They are produce events.
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#wireless-switches

**Comment by ispiropoulos** [comment]
@bastshoes that is totally my bad. I was keen to the previous Xiaomi gateway integration where it created stateful entities for the buttons as well :\
