### ISSUE TITLE
Channel 26

### ISSUE THREAD

**Issue by fantomnotabene** [dresden-elektronik/deconz-rest-plugin#1557]
Can I somehow set my RaspBee to use 26th channel?
Web-interface offers 11, 15, 20 and 25
I want to [connect Livolo switches](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/997#issuecomment-497272761) that only works on 26th channel as I know

**Comment by Smanar** [comment]
If you are looking on deconz option, you can choose the level 26.
But it is perhaps disabled because of reglementation on some countries.
