### ISSUE TITLE
Counter doesn't stop at 0 when updating config manually in v2.05.65

### ISSUE THREAD

**Issue by ghost** [dresden-elektronik/deconz-rest-plugin#1568]
Hi,

just updated to V2_05_65 and detected the following behavior: if I trigger a config-update manually (see screenshot), then the counter doesn't stop at 0 (as in V2_05_64) but runs (more or less) infinite.

![screenshot2](https://user-images.githubusercontent.com/47315068/58990559-75cb5b00-87e6-11e9-8f6a-b583e840c01d.jpg)

**Comment by Mimiix** [comment]
As per time, i close this for now. Please re-open if it still is a issue.
