### ISSUE TITLE
[Question] green dot blinking permanently

### ISSUE THREAD

**Issue by gpl1998** [dresden-elektronik/deconz-rest-plugin#1569]
Hi,

Quick question: just added a third Heiman Smoke Detector to my configuration. In contrast to the other two Heiman Smoke Detectors, there is a green dot blinking every two seconds (see screenshot). I wondering why as all other devices in my configuration are blinking blue (and much less frequent).

(I'm using v2.05.65) 

![screenshot](https://user-images.githubusercontent.com/47315068/58990839-32252100-87e7-11e9-8aab-a13fe0257046.jpg)

**Comment by Smanar** [comment]
Some infos here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1496
It's working perfectly ?

**Comment by gpl1998** [comment]
now, 3 days later, the device has lost connection (again) :-( 

I've 94 nodes in my configuration, this device is the only one that makes constantly troubles.
I powered off/on as well as re-added this device multiple times, but sooner or later the connection gets lost again. As said before, I have two more Heiman smoke detectors, which work properly without any issues.

Any hints/tips are highly appreciated to get this device working more reliable.

![Bildschirmfoto 2019-06-08 um 16 45 01](https://user-images.githubusercontent.com/47315068/59148801-785bc980-8a0d-11e9-88a8-ca41d0cb7dc1.png)

**Comment by Smanar** [comment]
The green blinking can say the "pairing procedure" is not finished.
So on my side, that I would do is trying pairing the device using another router or with direct connexion to coordinator
