### ISSUE TITLE
Gateway tab not working since update to 2.05.65

### ISSUE THREAD

**Issue by ademobile** [dresden-elektronik/deconz-rest-plugin#1572]
Since updating to v2.05.65 the gateway tab no longer displays correctly or functions. Please note the German at the bottom under the icons.

<img width="670" alt="Screenshot 2019-06-07 at 11 48 34" src="https://user-images.githubusercontent.com/25222110/59099413-f4291980-891a-11e9-8401-cec56b730b45.png">

I have tried with both Safari and Chrome with the same results

**Comment by manup** [comment]
Can you please open the developers console (F12) and reload the page. It seems that loading stops because some error is thrown.

As workaround you can also open the old version of this page by changing the url to settings-gateway.html (without the 2).

**Comment by ademobile** [comment]
Taking the 2 out worked - thank you. I guess this will be addressed and maybe is this issue with those that cannot do a backup?

**Comment by Kugelfang666** [comment]
I can also confirm, removing the "2" works!

**Comment by manup** [comment]
The issue will be fixed in version 2.05.67.

**Comment by manup** [comment]
Closed to continue further discussion in: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1630
