### ISSUE TITLE
LifeContol MCLH-03 smart plug doesn't show power and consumption via deconz 

### ISSUE THREAD

**Issue by Spirituss** [dresden-elektronik/deconz-rest-plugin#1573]
1) The zigbee smart plug LifeContol MCLH-03 with TexasInstruments RICI01 chipset works as light via Phoscon app but doesn't show it's power and consumption in Home Assistant via standard integration, while it can be shown in original 'Life control' app. It would be grateful to add the full support of this power plug.

2) The power changes made with hardware  button on the power plug nor doesn’t update power plug state in deconz. 

Soft used: Conbee I, deconz 2.0.65, Raspbian Stretch

Link to original site of this power plug:
[Life control smart plug](https://lifecontrol.ru/devices/smart-plug/)

Main clusters info from deconz-gui for this plug:
 
![Screen Shot 2019-06-07 at 15 10 23](https://user-images.githubusercontent.com/47206760/59103539-d5854b80-8937-11e9-926e-87a0e7a1fc68.png)

![Screen Shot 2019-06-07 at 15 09 21](https://user-images.githubusercontent.com/47206760/59103567-e33ad100-8937-11e9-8e90-16d3209c2730.png)

![Screen Shot 2019-06-07 at 15 10 00](https://user-images.githubusercontent.com/47206760/59103583-e9c94880-8937-11e9-9ac7-1f3234b0c8e1.png)

**Comment by bastshoes** [comment]
Please add support for metering cluster. Device details could be found in #1541

**Comment by Spirituss** [comment]
Any news regarding the issue?

**Comment by bastshoes** [comment]
Already supported. Check latest release.

**Comment by Spirituss** [comment]
I have updated Deconz and re-added the plug into Deconz. Energy power and consumptions have added but the plug itself become a disaster. Now each 5-10 mins it switches off the relay for just a second and then switches it on again. At the same time there is no any event in HA log regarding it, HA believes that nothing happens. Thus now I can't use the plug because it so regularly restarts a plugged device. 
I have to emphasize that there was no such plug's behavior before the last Deconz update.

**Comment by Spirituss** [comment]
Still waiting for the fix. 0.99.3 The device now doesn't work at all with the last deconz. Regular on/off auto switching + sometime loosing the device from deconz.

**Comment by bastshoes** [comment]
Hello @Spirituss I have three plugs. All work fine in terms of loosing connection. 
Regrading switching. I've noticed it on one plug before sensors was addded. One plug switches for a second around 1 am. Maybe other too but they usually staying in off stated.

**Comment by macros0** [comment]
> @bastshoes I have updated Deconz and re-added the plug into Deconz. Energy power and consumptions have added but the plug itself become a disaster. Now each 5-10 mins it switches off the relay for just a second and then switches it on again. At the same time there is no any event in HA log regarding it, HA believes that nothing happens. Thus now I can't use the plug because it so regularly restarts a plugged device.

What to do, bought a plug in too have all these problems?
