### ISSUE TITLE
repo seems to be offline 

### ISSUE THREAD

**Issue by 00lex** [dresden-elektronik/deconz-rest-plugin#1574]
can't get V2_05_65 via apt-get..

**Comment by manup** [comment]
The repo is up, if it still doesn't work, please provide the output of:

    cat /etc/apt/sources.list.d/deconz.list

**Comment by 00lex** [comment]
> deb http://phoscon.de/apt/deconz stretch main

is 2_05_65 a beta Version?
if not, its strange.  I updated to 2_05_64 via apt-get a few weeks ago without issues

**Comment by 00lex** [comment]
my fault. 2_05_65 is not a stable version
