### ISSUE TITLE
No more lines | every device unavailable

### ISSUE THREAD

**Issue by maui1911** [dresden-elektronik/deconz-rest-plugin#1587]
Not sure what happened, no errors from logs. But every device is unavailable in the Phoscon app and there are no more lines in the VNC app. 

I'm running deconz in docker with a Conbee v1 stick. Updated firmware to the last version.

![image](https://user-images.githubusercontent.com/1742072/59296494-66389000-8c86-11e9-94cd-ac412207574c.png)

sometimes I get this error: "otau failed to send image notify request"

edit:

this just repeats in the logs:

```
05:38:43:187 Device TTL 2520 s flags: 0x7
05:39:07:594 otau failed to send image notify request
05:39:43:159 Current channel 15
05:39:43:191 Device TTL 2460 s flags: 0x7
05:40:17:594 otau failed to send image notify request
05:40:43:162 Current channel 15
05:40:43:194 Device TTL 2400 s flags: 0x7
05:40:48:107 GW firmware version: 0x26330500
05:40:48:107 GW firmware version is up to date: 0x26330500
05:41:27:595 otau failed to send image notify request
05:41:43:166 Current channel 15
05:41:43:198 Device TTL 2340 s flags: 0x7
05:42:37:594 otau failed to send image notify request
05:42:43:170 Current channel 15
05:42:43:202 Device TTL 2280 s flags: 0x7
05:43:43:157 Current channel 15
05:43:43:189 Device TTL 2220 s flags: 0x7
05:43:47:594 otau failed to send image notify request
05:44:43:160 Current channel 15
05:44:43:192 Device TTL 2160 s flags: 0x7
05:44:48:103 GW firmware version: 0x26330500
05:44:48:103 GW firmware version is up to date: 0x26330500
05:44:57:594 otau failed to send image notify request
05:45:43:164 Current channel 15
05:45:43:196 Device TTL 2100 s flags: 0x7
05:46:07:594 otau failed to send image notify request
05:46:43:167 Current channel 15
05:46:43:199 Device TTL 2040 s flags: 0x7
```

**Comment by maui1911** [comment]
I managed to add a new thing, nice new green line.

How do I get the stick to connect to all the old things, please help :(

![image](https://user-images.githubusercontent.com/1742072/59372639-3d78cf00-8d48-11e9-800f-1c3167c2fb59.png)

**Comment by Smanar** [comment]
Arf, all devices are grayed. It mean they are not in the network ATM. It's like you have loose all yours devices.
Have you tried the "network configuration recovery" https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59 ?
Have you tried unplug/replug the conbee (to check for firmware hangs) ?

**Comment by maui1911** [comment]
I think it happend after I did a firmware upgrade.

But thanks a lot man, loading an old configuration worked like a charm!

![image](https://user-images.githubusercontent.com/1742072/59381582-057b8700-8d5c-11e9-8d69-f588dbac51cc.png)
