### ISSUE TITLE
Xiaomi Smart Plug miss sensor device (ZHAConsumption)?

### ISSUE THREAD

**Issue by stccmaya** [dresden-elektronik/deconz-rest-plugin#1592]
I have one Xiaomi smart plug (modelid: "lumi.plug.mitw01", swversion: "01-10-2018")

The plugin creates three devices (lumi.plug; ZHAPower)

Have some problem

1. loss one device (ZHAConsumption)

2. ZHAPower device no value : (

------------------------------------
detail information: (I use: ConebeeII)

ZHAPower

**************************** Object info *****************************
{
"state": {
"lastupdated": "2019-06-06T02:41:11",
"power": -1
},
"config": {
"on": true,
"reachable": true
},
"name": "Power 3",
"type": "ZHAPower",
"modelid": "lumi.plug.mitw01",
"manufacturername": "LUMI",
"swversion": "01-10-2018",
"uniqueid": "00:15:8d:00:02:8b:3d:0c-01-0b04",
"ep": 1,
"etag": "bf511a13f8b44cb357694252ad67edd1"
}
************************* End Object info ***************************
![image_79688](https://user-images.githubusercontent.com/51429278/59492309-46d67880-8ebb-11e9-957a-d9de19e7aa62.png)
![image_79690](https://user-images.githubusercontent.com/51429278/59492319-4b9b2c80-8ebb-11e9-9bcc-587333531d4e.png)
![image_79691](https://user-images.githubusercontent.com/51429278/59492324-4d64f000-8ebb-11e9-8e1d-6711002187c8.png)

**Comment by stccmaya** [comment]
no any respone : (

**Comment by renedis** [comment]
Select analog Input on the second device. After that, pres READ on the left side
