### ISSUE TITLE
headless Image - password for Phoscon-Gateaway-FFCF

### ISSUE THREAD

**Issue by flex-0** [dresden-elektronik/deconz-rest-plugin#1600]
Hey guys,

so I installed the headless version of the images. I get that it runs in AP mode and I can change that within the app. 

But how can I access the Phoscon-Gateaway-FFCF?

I can't find a password and "raspbeegw" is not working so could you tell me how to access the AP?

**Comment by manup** [comment]
Normally on a fresh installation you're asked to specify a new password for the Phoscon App.

https://phoscon.de/en/app/doc#commissioning-login-password-en

**Comment by Sennevds** [comment]
@manup he's talking about the sd-image. If you boot the first time it creates a access point but there isn't any information about the password of the wifi.
The ssid of the wifi is something like 'Phoscon-Gateway-[random 4 letters]'.
It's nice that it creates a access point to configure the the app but we need a password!

**Comment by jsemmler** [comment]
same problem
