### ISSUE TITLE
[Request Device Support] Centralite Pearl Touch Screen Thermostat - 3157100-WE

### ISSUE THREAD

**Issue by rb2k** [dresden-elektronik/deconz-rest-plugin#1601]
Had this still lying around, so I thought I'd try to add it to my network.

https://www.mydigitaldiscount.com/centralite-pearl-touch-screen-thermostat-3157100-we-works-with-amazon-alexa-google-home-samsung-smartthings-w-zigbee-support/

These are the logs around the time that I added it:

```
17:07:22:069 device announce 0x000D6F00055B811A (0x499A) mac capabilities 0x80
17:07:22:069 set fast probe address to 0x000D6F00055B811A (0x499A)
17:07:22:069 FP indication 0x0000 / 0x0013 (0x000D6F00055B811A / 0x499A)
17:07:22:069                       ...     (0x000D6F00055B811A / 0x499A)
17:07:22:069 device announce 0x000D6F00055B811A (0x499A) mac capabilities 0x80
17:07:22:947 [1] get node descriptor for 0x000d6f00055b811a
17:07:36:438 FP indication 0x0000 / 0x8002 (0x000D6F00055B811A / 0x499A)
17:07:36:438                       ...     (0x000D6F00055B811A / 0x499A)
17:07:36:438 ZDP indication search sensors 0x000D6F00055B811A (0x499A) cluster 0x8002
17:07:36:438 ZDP indication search sensors 0x000D6F00055B811A (0x499A) clear timeout on cluster 0x8002
17:07:36:444 [2] get active endpoints for 0x000d6f00055b811a
17:07:36:675 FP indication 0x0000 / 0x8005 (0x000D6F00055B811A / 0x499A)
17:07:36:675                       ...     (0x000D6F00055B811A / 0x499A)
17:07:36:675 ZDP indication search sensors 0x000D6F00055B811A (0x499A) cluster 0x8005
17:07:36:675 ZDP indication search sensors 0x000D6F00055B811A (0x499A) clear timeout on cluster 0x8005
17:07:39:299 FP indication 0x0104 / 0x000A (0x000D6F00055B811A / 0x499A)
17:07:39:299                       ...     (0x000D6F00055B811A / 0x499A)
17:07:44:370 ZCL attribute report 0xF0D1B80000019542 for cluster 0x0300, ep 0x01
17:07:44:411 ZCL attribute report 0xF0D1B80000019542 for cluster 0x0300, ep 0x01
17:08:04:306 Current channel 25
17:08:04:338 Device TTL 4920 s flags: 0x7
17:08:08:371 verified group capacity: 255 and group count: 1 of LightNode 0x000d6ffffe28349c
17:08:08:371 0x000d6ffffe28349c found group 0x0006
17:08:17:491 CTRL skip polling while permit join is set
17:08:20:353 Search sensors done
17:08:25:965 Websocket disconnected 192.168.1.82:60417 (state: 0) 
17:08:28:225 New websocket 192.168.1.82:60468 (state: 3) 
17:08:29:015 Websocket disconnected 192.168.1.82:60468 (state: 0) 
17:08:30:076 New websocket 192.168.1.82:60469 (state: 3) 
17:08:31:020 Websocket disconnected 192.168.1.82:60469 (state: 0) 
17:08:32:149 New websocket 192.168.1.82:60472 (state: 3) 
17:08:42:747 binding for cluster 0x0000 of 0x000D6FFFFE28349C exists (verified by reporting)
17:08:42:747 binding for cluster 0x0006 of 0x000D6FFFFE28349C exists (verified by reporting)
17:08:42:747 binding for cluster 0x0008 of 0x000D6FFFFE28349C exists (verified by reporting)
17:08:42:900 ZCL configure reporting rsp seq: 189 0x000D6FFFFE28349C for cluster 0x0006 attr 0x0000 status 0x00
17:08:42:964 ZCL configure reporting rsp seq: 190 0x000D6FFFFE28349C for cluster 0x0008 attr 0x0000 status 0x00
17:09:02:481 Unhandled node key 16777249
17:09:04:309 Current channel 25
17:09:04:341 Device TTL 4860 s flags: 0x7
17:09:05:529 Unhandled node key 16777249
17:09:07:846 Unhandled node key 16777251
17:09:07:939 Unhandled node key 16777248
17:09:08:036 Unhandled node key 36
17:09:09:702 Unhandled node key 16777251
17:09:09:723 Unhandled node key 16777248
17:09:09:834 Unhandled node key 36
17:09:11:919 Unhandled node key 16777248
17:09:11:920 Unhandled node key 16777251
17:09:12:095 Unhandled node key 36
17:09:17:782 CTRL skip polling while permit join is set
```

These are the requested screenshots:

<img width="204" alt="Screen Shot 2019-06-16 at 5 09 18 PM" src="https://user-images.githubusercontent.com/9519/59571500-3f010a80-905a-11e9-8fcf-aebd6e03b8f7.png">

<img width="551" alt="Screen Shot 2019-06-16 at 5 13 04 PM" src="https://user-images.githubusercontent.com/9519/59571490-3e687400-905a-11e9-9d39-32b03dd8c13c.png">
<img width="547" alt="Screen Shot 2019-06-16 at 5 12 54 PM" src="https://user-images.githubusercontent.com/9519/59571491-3e687400-905a-11e9-8ecf-e97f18749fde.png">
<img width="538" alt="Screen Shot 2019-06-16 at 5 12 43 PM" src="https://user-images.githubusercontent.com/9519/59571492-3e687400-905a-11e9-9819-c0775042b389.png">
<img width="552" alt="Screen Shot 2019-06-16 at 5 12 30 PM" src="https://user-images.githubusercontent.com/9519/59571493-3e687400-905a-11e9-9644-c91e94be15ce.png">
<img width="550" alt="Screen Shot 2019-06-16 at 5 12 18 PM" src="https://user-images.githubusercontent.com/9519/59571494-3e687400-905a-11e9-92dd-e098124827dc.png">
<img width="553" alt="Screen Shot 2019-06-16 at 5 12 07 PM" src="https://user-images.githubusercontent.com/9519/59571495-3e687400-905a-11e9-93a2-a5faab327c50.png">
<img width="534" alt="Screen Shot 2019-06-16 at 5 11 58 PM" src="https://user-images.githubusercontent.com/9519/59571496-3f010a80-905a-11e9-83bc-3a3d9a138fe0.png">
<img width="541" alt="Screen Shot 2019-06-16 at 5 11 50 PM" src="https://user-images.githubusercontent.com/9519/59571497-3f010a80-905a-11e9-98bd-9a3a6c13dca3.png">
<img width="557" alt="Screen Shot 2019-06-16 at 5 10 56 PM" src="https://user-images.githubusercontent.com/9519/59571499-3f010a80-905a-11e9-9210-90a6c3cecec0.png">

**Comment by wvuyk** [comment]
This one would be really nice if supported.......

**Comment by rb2k** [comment]
I wonder if there's anything else I have to do?
I tried to follow https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support and did everything besides the debug logging. I think this should be enough?

**Comment by manup** [comment]
Thanks, I think this should be enough data to get a first implementation ready.

**Comment by rb2k** [comment]
Is there any ETA on these kind of things?
I'm thinking about getting rid of my Nest thermostat over the next month and was wondering if I should just wait it out or switch to something already supported :)
