### ISSUE TITLE
Docker & REST API - IP address issue after restart

### ISSUE THREAD

**Issue by ualex73** [dresden-elektronik/deconz-rest-plugin#1602]
I am running DeCONZ in Docker (marthoc/deconz:2.0.5.65), this works fine. Only when I reboot my NUC, the DeCONZ REST API looses its way and starts using an internal Docker IP address. A restart of the container fixes it, so it seems to only an issue during start-up of the container.

Procedure to reproduce it:
- Start DeCONZ container with network-mode 'host'
- Reboot node
- Check with curl http:/deconz.lan:3080/api/2AF753696B the content
- Notice it uses the "172.x.x.x" from the Docker internal network

`{
    "config": {
        "UTC": "2019-06-17T10:55:15",
        "apiversion": "1.16.0",
        "backup": {
            "errorcode": 0,
            "status": "idle"
        },
        "bridgeid": "00212EFFFF04237B",
        "datastoreversion": "60",
        "devicename": "RaspBee",
        "dhcp": true,
        "factorynew": false,
        "fwversion": "0x26490700",
        "gateway": "172.18.0.1",
        "internetservices": {
            "remoteaccess": "disconnected"
        },
        "ipaddress": "172.18.0.1",
        "linkbutton": false,
        "localtime": "2019-06-17T12:55:15",
        "mac": "02:42:48:e9:a3:03",
        "modelid": "deCONZ",
        "name": "deconz",
        "netmask": "255.255.0.0",
...`
- It should use an IP address in the range 192.168.x.x.

**Comment by Kane610** [comment]
It could be a docker issue as well I think
