### ISSUE TITLE
Support request for Paulmann 500.67 Zigbee Remote

### ISSUE THREAD

**Issue by a005** [dresden-elektronik/deconz-rest-plugin#1603]
Is it possible to support Paulmann 500.67 Zigbee Remote Controller?
Product page is [here](https://en.paulmann.com/indoor-lighting/smart-home/zigbee/controlling/smarthome-zigbee-remote-control-gent-with-wall-mounting-bracket/50067).
Some comments about connection to Philips Hue Bridge were found [here (customer questions and answers)](https://www.amazon.de/Paulmann-500-67-Smarthome-Fernbedienung-Wandhalterung/dp/B071WZZ12Y).
Node info:
![node info](https://user-images.githubusercontent.com/16546417/59708663-e5414180-920d-11e9-9656-e13031f7c427.png)

Basic cluster info:
![basic - cluster info](https://user-images.githubusercontent.com/16546417/59708699-fb4f0200-920d-11e9-8645-db84e1e20586.png)

If needed, I'm ready to provide additional information.
Thank you.

**Comment by kayhannay** [comment]
I would also like to see support for this controller. Is there something I can provide to support the integration?

**Comment by ITSSeu** [comment]
> 
> 
> I would also like to see support for this controller. Is there something I can provide to support the integration?

I also like to see support for this controller, thanks!

**Comment by svrnwnsch** [comment]
Pleas reopen the Issue as I would also love support for this controller.

**Comment by mawa85** [comment]
+1

**Comment by neledo** [comment]
+1
