### ISSUE TITLE
Ikea OTA download

### ISSUE THREAD

**Issue by olivertheobald** [dresden-elektronik/deconz-rest-plugin#1606]
I am using the deconz docker container and i dont want to install python on my host, or inside the container. so i wrote a little shell script, which dowloads the ikea firmware files.
Should i create a pull request? Probably we could put the additional scripts inside a tools folder?
jq is already installed in the docker image.

```sh
#!/bin/bash

dir=$PWD

curl 'http://fw.ota.homesmart.ikea.net/feed/version_info.json' | jq -r '[.[] | .fw_binary_url] | .[]'  > $dir/files.txt

cd /root/otau && xargs -n 1 curl -O < $dir/files.txt

rm $dir/files.txt
```

**Comment by manup** [comment]
Cool, always nice to see use of `jq` :)

I think it can be put in `https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/linux/deCONZ/usr/bin`

One suggestion `cd /root/otau` could be more genral as `cd $HOME/otau`.
