### ISSUE TITLE
 [Request Device Support] Heimann HS1HT-E

### ISSUE THREAD

**Issue by bedaes** [dresden-elektronik/deconz-rest-plugin#1611]
I've just received a Heimann HS1HT-E. There is the HS1HT on the supported devices page, so I'm not entirely sure if they are the same? At least I can't add the sensor through Phoscon App.

The sensor has two nodes:

![00-nodes](https://user-images.githubusercontent.com/8410205/59790414-2e59ca00-92d0-11e9-8c28-f5b88a0399d7.png)

### Node 01 Info

![01-node](https://user-images.githubusercontent.com/8410205/59790420-2ef26080-92d0-11e9-9b2c-03470a4f7dfa.png)

### Node 01 Cluster Info

![01-basic](https://user-images.githubusercontent.com/8410205/59790416-2e59ca00-92d0-11e9-9f05-0cc201c7eef9.png)

![01-power](https://user-images.githubusercontent.com/8410205/59790422-2f8af700-92d0-11e9-8b5d-0a55c6204dfc.png)

![01-identify](https://user-images.githubusercontent.com/8410205/59790418-2ef26080-92d0-11e9-956b-1499aa4123c9.png)

![01-alarms](https://user-images.githubusercontent.com/8410205/59790415-2e59ca00-92d0-11e9-8c86-eef3fad11628.png)

![01-temperature](https://user-images.githubusercontent.com/8410205/59790424-2f8af700-92d0-11e9-8381-f6f48fbf6755.png)

### Node 02 Info

![02-node](https://user-images.githubusercontent.com/8410205/59790429-30238d80-92d0-11e9-8226-f41b88c922d8.png)

### Node 02 Cluster Info

![02-basic](https://user-images.githubusercontent.com/8410205/59790425-30238d80-92d0-11e9-97e1-fa9e17dfa0b8.png)

![02-power](https://user-images.githubusercontent.com/8410205/59790430-30bc2400-92d0-11e9-9993-35610f2b62dc.png)

![02-identify](https://user-images.githubusercontent.com/8410205/59790427-30238d80-92d0-11e9-9079-fe0fa96fd3f7.png)
 
![02-humidtiy](https://user-images.githubusercontent.com/8410205/59790426-30238d80-92d0-11e9-9e35-1f17592fef0d.png)

**Comment by ebaauw** [comment]
Looks like a newer model, with the new _Manufacturer Code_.  It simply needs to be whitelisted for support by the REST API plugin.  Note to self: double check that it’s whitelisted for setting up  attribute reporting.

Are you sure it exposes the same _Model Identifier_ on both endpoints?  The old model uses different values.

**Comment by bedaes** [comment]
That was quick :+1: 

I double checked and yes, the _Model Identifier_ is reported as `TH-EM` on both endpoints.

**Comment by bedaes** [comment]
I have successfully added the sensor using Phoscon App and it's working fine using Home Assistant. It doesn't show up in Phoscon App though, therefore I can't rename the sensor. Is this to be expected?
