### ISSUE TITLE
Bosch Pro-Grade ISW-ZPR1-WP13  Motion Detector

### ISSUE THREAD

**Issue by hgelpke** [dresden-elektronik/deconz-rest-plugin#1619]
The device pairs properly and reports motion for awhile but seems to go into a sleep mode that stops reporting information. It can be woken up by pressing a button with the case open similar to the pairing procedure but otherwise goes dead. 

Device also fails to report temperature and based on the smartthings discussion that might be what keeps it alive.

**Comment by bdickhaus** [comment]
I am seeing the same thing.

**Comment by mamrai1** [comment]
![Screenshot_20201009_222221_io homeassistant companion android](https://user-images.githubusercontent.com/57288344/95623472-fefb3d80-0a7d-11eb-8a75-234c4ba67c4f.jpg)
![Screenshot_20201009_222205_io homeassistant companion android](https://user-images.githubusercontent.com/57288344/95623475-002c6a80-0a7e-11eb-8227-5982c7817ef9.jpg)
![Screenshot_20201009_222201_io homeassistant companion android](https://user-images.githubusercontent.com/57288344/95623476-00c50100-0a7e-11eb-8411-06d521532302.jpg)
Just paired 2 Bosch motion sensors.. Temp is shown but battery state shouldn't report persentage?

**Comment by SwoopX** [comment]
Yes, probably. However, any information on what values the devices uses has never been provided. For that, we require a screenshot from the power configuration cluster of deconz GUI while the attributes have been read.
