### ISSUE TITLE
Unknown device connected

### ISSUE THREAD

**Issue by WhistleMaster** [dresden-elektronik/deconz-rest-plugin#1626]
I have a device connected to my zigbee network but I cannot figure out what this device is. All the device I have are reported correctly and this one is an additional device I have no idea what it is. Even if I delete it, after a few moment, it comes back in the network.

<img width="277" alt="Screenshot 2019-06-23 at 18 48 30" src="https://user-images.githubusercontent.com/1544568/59979461-923e0480-95e8-11e9-907a-3dc34d23a833.png">

<img width="356" alt="Screenshot 2019-06-23 at 18 48 36" src="https://user-images.githubusercontent.com/1544568/59979462-923e0480-95e8-11e9-9ef5-b4ccc9e76a84.png">

**Comment by ebaauw** [comment]
> Even if I delete it, after a few moment, it comes back in the network.

It's probably a stale entry in the neighbour table of one of your routers.  You may want to power cycle the router at the other end of the red line.

**Comment by pergolafabio** [comment]
Yeah, I have the same , deleting doesn't help, just comes back... I have it only on one of my osrams power plug, always connected to that one...

Don't see it in phoscon, only in the mesh

Power cycle doesn't help either, even deleting the Osram, Brings that specific node back

**Comment by WhistleMaster** [comment]
> It's probably a stale entry in the neighbour table of one of your routers. You may want to power cycle the router at the other end of the red line.

I tried your proposition, without success unfortunately.

**Comment by pergolafabio** [comment]
see my screen here, i have them too , no idea what it is :)

i just ignore them

https://www.dropbox.com/s/i49dqpsx1x4im33/unknowdevices.JPG?dl=0

**Comment by gpl1998** [comment]
same here. 

I deleted my five hue motion sensors in Phoscon. All 5 sensor disappeared in Phoscon permanently and for a while in Deconz. After a while, they came back in Deconz (but not in Phoscon). I deleted the 5 nodes in Deconz one more time - again, they disappeared for a while and came back after a little while. 

I sold the sensors and they left my house. Again, I deleted the nodes in Deconz and now the were gone. This weekend, I rebooted the Raspberry and - really strange - three of the five sensors appeared again. One more time, I deleted the sensor. Not restarted my Raspberry in the meanwhile, I'm really curious how it looks like after the next reboot.

In general: this is not a big issue as it doesn't have any impact on functionality or stability to the rest of the network.

**Comment by pergolafabio** [comment]
in your case its a real hardware device (sensor)
in my screenshots , its  a unknown device, its not a hardware device :)

**Comment by ebaauw** [comment]
> Power cycle doesn't help either, even deleting the Osram, Brings that specific node back
> I tried your proposition, without success unfortunately.

Maybe the router keeps the associated end devices in non-volatile memory.  I’m not too familiar with this part of the standard, and maybe different manufacturers handle this differently.  Only a factory reset of the router clears the non-volatile memory, but I’m not sure if that’s worth the trouble.

**Comment by Smanar** [comment]
On my side, this kind of "ghost device" become deletable after somes days, just wait somes days before retrying to delete them.

**Comment by pergolafabio** [comment]
I have them already like 4 months ;)

**Comment by Smanar** [comment]
Hur, lol, ok, forget that I have said ^^.

**Comment by WhistleMaster** [comment]
> > Power cycle doesn't help either, even deleting the Osram, Brings that specific node back
> > I tried your proposition, without success unfortunately.
> 
> Maybe the router keeps the associated end devices in non-volatile memory. I’m not too familiar with this part of the standard, and maybe different manufacturers handle this differently. Only a factory reset of the router clears the non-volatile memory, but I’m not sure if that’s worth the trouble.

I tried, same result, it keeps coming back.

**Comment by walshtj** [comment]
For me this turned out to be a Smarthings Motion sensor which was still supposed to be paired with the (soon to be decommissioned) Smartthings hub.  There is a chance it might have not been paired but I can't be sure.

The deConz app allowed me to find the hardware address and product name which was "centralite 3325-s".
Using the ST graph backend I found the two hardware addresses matched. 

I temporarily re-paired to ST and problem seemed to go away.
