### ISSUE TITLE
Broken Gateway Site on Phoscon Webapp @ 2.05.66

### ISSUE THREAD

**Issue by brandungskieker** [dresden-elektronik/deconz-rest-plugin#1630]
Having Trouble to open Gateway-page on Phoscon Webapp since updating to 2.05.66. The page is interrupted by JS and HTTP Errors. 
Occurs on Safari and Chrome (latest) for Mac. 
See Screenshots for more details

<img width="1378" alt="Bildschirmfoto 2019-06-24 um 22 21 46" src="https://user-images.githubusercontent.com/5999709/60049664-0e127c80-96cf-11e9-9b6f-32a3c812f224.png">
<img width="1389" alt="Bildschirmfoto 2019-06-24 um 22 25 52" src="https://user-images.githubusercontent.com/5999709/60049665-0e127c80-96cf-11e9-80f9-2a7688b2af1b.png">

**Comment by ademobile** [comment]
See issue #1572 on a work round until they fix it!

**Comment by manup** [comment]
Thanks for the report, that's a new one, will be fixed in the next version.

**Comment by TilBumble** [comment]
I updated manually to 2.05.67 (openHABianPi headless) and retrieving the gateway page from a Windows 10 PC (Microsoft Edge browser) still leads to a more or less blank page.
(No text, only left and top frames)

The console shows the following warnings and Infos (no errors):
__________________________
HTML1300: Navigation wurde ausgeführt.
settings-gateway2.html (1,1)

2CSS3121: Die Medienabfrage -ms-viewport ist veraltet.

3HTML1500: Die Markierung kann nicht selbstschließend sein. Verwenden Sie eine explizite schließende Markierung.
settings-gateway2.html (82,5)

HTML1512: Endmarkierung ohne Entsprechung.
settings-gateway2.html (130,12)

HTML1500: Die Markierung kann nicht selbstschließend sein. Verwenden Sie eine explizite schließende Markierung.
settings-gateway2.html (215,3)
______________________

The workaround still works.

Can i be of further assistance to clear up this issue?

**Comment by brandungskieker** [comment]
Had the same. Cleaning up the browser cache helps.
