### ISSUE TITLE
Conbee II - make firmware 0x26420700 available

### ISSUE THREAD

**Issue by dbdbdb** [dresden-elektronik/deconz-rest-plugin#1641]
I have bought a conbee II with firmware 0x26420700. I've developed an application that speaks the serial protocol and it works fine.

There are new firmwares I can install but I can't find the 0x26420700 that is currently installed in my stick. I want to be able to downgrade again to make sure that the application works with all versions of the firmware.

Would it be possible for you to put the 0x26420700 somewhere for download?

Kind regards,
Dennis

**Comment by Kane610** [comment]
So many improvements to fw so far and it's quite new. Wouldn't it be better to require the latest available right now? Makes life easier for you

**Comment by dbdbdb** [comment]
I'm sure the latest version is much better but it's still nice if the code work with whatever version is in the stick. I use an old conbee myself and I bought a new conbee II just to make sure the code work with it as well.

I already have an easy life :-)

So far the differences I've seen are minor. Like the Device State response has a frame length of 7 instead of the documented 8. Plus the watchdog stuff that is new of course.

**Comment by manup** [comment]
>Would it be possible for you to put the 0x26420700 somewhere for download?

It is online now, but keep in mind this versions has some real issues and updating for users is highly recommended.

https://www.dresden-elektronik.de/rpi/deconz-firmware/

**Comment by dbdbdb** [comment]
Great. Thanks a lot!
