### ISSUE TITLE
Add support for Xiaomi vibration sensor

### ISSUE THREAD

**Issue by snics** [dresden-elektronik/deconz-rest-plugin#1651]
Hello,

I would be happy if there is support for the Xiaomi vibration sensor. I can teach it, but it will only show updated and no traffic jams, vibration, etc. 

I don't know if this makes sense but the water sensor also displays "water" or "no water".

Here is link which sensor I mean: https://de.gearbest.com/smart-home-controls/pp_009661787808.html

**Comment by wvuyk** [comment]
it is already present I think see #748

**Comment by snics** [comment]
Okay, thanks to you. Then I'll probably have to do an update, because unfortunately only the last status update is displayed.
