### ISSUE TITLE
Zigbee HA or Zigbee SE

### ISSUE THREAD

**Issue by cnrd** [dresden-elektronik/deconz-rest-plugin#1656]
Hi

So I'm about to buy a zigbee module for my electricity meter and the vendor I found have both a Zigbee HA and a Zigbee SE version of the meter, which one should I get to hopefully get it supported in deconz?

I'm guessing the Zigbee HA version?

**Comment by mysteryan** [comment]
You sure its not Zigbee HAN, not HA?

**Comment by cnrd** [comment]
Yes they are all HAN modules, but one is based on Zigbee HA, the other on Zigbee SE
