### ISSUE TITLE
Some lights (Tradfri) continuously switching between available and not unavailable

### ISSUE THREAD

**Issue by JBS5** [dresden-elektronik/deconz-rest-plugin#1657]
Some of my Tradfri GU10 lights are continuously switching between available and not unavailable

![image](https://user-images.githubusercontent.com/25594213/60710729-a3094700-9f13-11e9-97bb-227a1ba30d69.png)

deCONZ: 2.05.66
Conbee firmware: 26330500
deCONZ in Docker running on a NUC with Ubuntu
Had this before (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1597), but the issue is here again.

Does anyone recognize this behaviour? 
Any clue why?

**Comment by JBS5** [comment]
A few days later this issue has disappeared (again). Not sure why en how.
In the meantime, the deCONZ docker container is restarted but not sure if this is related.

**Comment by Smanar** [comment]
But have you problem in working mode ?
Have you sometime a bulb that doesn't light on or off after a command ?

**Comment by JBS5** [comment]
I do not have problems with switching the light on or off during described behaviour.

**Comment by Smanar** [comment]
You are sure it's not a problem from the application you are using for log ?
If the bulb was realy unavailable 50% of the time, you will have problem using it ?

**Comment by JBS5** [comment]
> You are sure it's not a problem from the application you are using for log ?

The screenshot in my first post is from Home Assistant where the state of the entitiy is going to unavailable which is coming from the rest API. Also in the Phoscon app, the bulb is marked as unavailable.
> If the bulb was realy unavailable 50% of the time, you will have problem using it ?

Could be, but switching the lights happens up to a few times a day.

**Comment by AlexMekkering** [comment]
I'm seeing the same behaviour

**Comment by JBS5** [comment]
This issue appears and disappears over the days:

![image](https://user-images.githubusercontent.com/25594213/61198715-83280f00-a6db-11e9-95ac-7c50ba1f4309.png)

**Comment by JBS5** [comment]
And example of a light where the issue arises and disappears.

![image](https://user-images.githubusercontent.com/25594213/62353888-ef907400-b50b-11e9-9907-3be1473748ab.png)

**Comment by JBS5** [comment]
This issue still present. Happy to provide any information needed..

**Comment by JBS5** [comment]
Still happening..
