### ISSUE TITLE
Single cklick on WXKG01LM in ioBroker

### ISSUE THREAD

**Issue by DanielHD80** [dresden-elektronik/deconz-rest-plugin#1658]
I'm a new ConBee II user and now I have a little problem.

I use the ioBroker, where all devices could be easily added and used. I'm having trouble with the Xiaomi WXKG01LM button.

At the beginning, I only used one button for light on and off. For this I triggered on 1002, which went without problems! But now I want to control another lamp with a double click. So I wanted to trigger this on 1004. Works also wonderful! However, the first lamp is also activated, as the 1002 is briefly transmitted. Is this an error? 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG01LM

says that 1002 is for a SINGLE short release and not for a double! Which values should I best use in ioBroker to evaluate at least single, double (1004?) And triple (1005?) Clicks, and best still long press (1003?). Am I correct with my assumed values? And which is the correct one for one short? 1002 as in the wiki, it is definitely not ...

In the switch-editor in phoscon-app there is single-5x press... but I can't use it in ioBroker!

**Comment by Smanar** [comment]
I have just make a try with the WXKG02LM, and If I make double click, I have only 1 return > 'buttonevent': 1004, if I make a simple click >  'buttonevent': 1002.
