### ISSUE TITLE
OTA upgrade of IKEA GU 10 bulbs gets stuck

### ISSUE THREAD

**Issue by donnib** [dresden-elektronik/deconz-rest-plugin#166]
Hi, i did a a comment here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/96#issuecomment-324965537 about a problem I have with my new GU 10 IKEA bulbs which all get stuck on OTA upgrade. What can I do ?

I am on 2.04.73 and firmware 0x26160500

**Comment by donnib** [comment]
![Image](https://i.imgur.com/Q5Pf0fK.jpg)

**Comment by manup** [comment]
On it, I have a lamp here (non IKEA) with the same problem, might be an issue in the OTA plugin. I'll report back when there are news.

**Comment by donnib** [comment]
Cool Nice to know that you can reproduce it. Hope u can find a fix.

**Comment by manup** [comment]
I could fix the issue for the non IKEA light, can you please test the new version with your lights.

http://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.04.75-qt5.deb

**Comment by ebaauw** [comment]
Would this also fix the issue with the firmware update getting stuck on the ubisys dimmer?

**Comment by manup** [comment]
I'm afraid it won't, the issue here was a too long OTA reply packet which was rejected from the firmware.

You may try it, I'll put an ubisys OTA test on the list.

**Comment by donnib** [comment]
@manup thank you, that nailed it

**Comment by donnib** [comment]
@manup I have many GU10 which get's stuck on OTA, what can i do to fix this ?

**Comment by Mimiix** [comment]
@donnib Please do not necro post. Open a new issue with your question. 

Use the template!

**Comment by Smanar** [comment]
@donnib if your problem is the update reach 99% but don't work, please make a new issue with the firmware you have used, I have perhaps a solution (perhaps same bug but on another manufacture, corrected on m y side)
