### ISSUE TITLE
Request Device Support: Wall Switch 4 key Terncy (xiaoyan)

### ISSUE THREAD

**Issue by cacherocks** [dresden-elektronik/deconz-rest-plugin#1664]
**Node Info**
<img width="514" alt="Снимок экрана 2019-07-09 в 23 23 35" src="https://user-images.githubusercontent.com/25862599/60920340-9d5b8a80-a2a0-11e9-8131-2b243950623a.png">

**Node** (1 button load without zero line and programmable 3 buttons for automation; programmable buttons understand single press, double press and long press)
<img width="331" alt="Снимок экрана 2019-07-09 в 23 24 19" src="https://user-images.githubusercontent.com/25862599/60920375-b401e180-a2a0-11e9-8e73-baa7f77e3e7d.png">

**Basic Cluster 0000**
<img width="502" alt="Снимок экрана 2019-07-09 в 23 25 26" src="https://user-images.githubusercontent.com/25862599/60920443-e0b5f900-a2a0-11e9-969d-463de3c53170.png">

**Identify cluster 0003**
<img width="507" alt="Снимок экрана 2019-07-09 в 23 26 03" src="https://user-images.githubusercontent.com/25862599/60920490-f5928c80-a2a0-11e9-959d-3d7f1b641740.png">

**on/off cluster 0006** (on, off and toggle work)
<img width="507" alt="Снимок экрана 2019-07-09 в 23 27 11" src="https://user-images.githubusercontent.com/25862599/60920550-1eb31d00-a2a1-11e9-96de-30355dfd8cba.png">

**Poll Control cluster 0020**
<img width="502" alt="Снимок экрана 2019-07-09 в 23 28 39" src="https://user-images.githubusercontent.com/25862599/60920636-59b55080-a2a1-11e9-937b-6ba16f344209.png">

**OTAU cluster 0019**
<img width="503" alt="Снимок экрана 2019-07-09 в 23 29 40" src="https://user-images.githubusercontent.com/25862599/60920696-794c7900-a2a1-11e9-8bf9-c5e2ea44d681.png">

It is not added to сonbee 1, it is added only to conbee2.

[The official page on the manufacturer's website](https://xiaoyan.io/en-us/wallswitch-noneutral/)
![wall-switches-2](https://user-images.githubusercontent.com/25862599/60959979-d97b0380-a311-11e9-98f4-f0d9fcd0a0df.png)

**Comment by cacherocks** [comment]
Upd. The request to add a switch is relevant.

**Comment by Mimiix** [comment]
@manup is this solved?
