### ISSUE TITLE
Question: Orvibo ZigBee CR11S8UZ and Deconz

### ISSUE THREAD

**Issue by SAOPP** [dresden-elektronik/deconz-rest-plugin#1666]
Hi guys!

I'm sorry for opened this topic, but I can't found any info about compatibility of this switch with Deconz.

I plan to order it right now - but I would like to get at least some information regarding working with Deconz, can someone share any infos? Thanks in advance guys!

This is the official page of the switch: https://www.orvibo.com/en/product/tie.html

**Comment by SAOPP** [comment]
So guys any no info regarding this switch?

**Comment by SAOPP** [comment]
@Hypfer thanks homie, but I don't have it, and I just try to get some infos because I want to buy it. Of course if I get this switch I share all debug infos about it if this stuff doesn't work with deconz right now.

**Comment by SAOPP** [comment]
Guys, I gotted some information about this Tie switch connected to the Deconz.

Here we go:

![image](https://user-images.githubusercontent.com/5647009/61539205-ac320200-aa43-11e9-8b67-4665631b1826.png)

![image](https://user-images.githubusercontent.com/5647009/61539213-b3591000-aa43-11e9-88fe-f41c86f38ae6.png)

Also, what else we need to be future implementing this connection? Best regards to all Devs guys!

**Comment by Smanar** [comment]
They need cluster list and Basic Cluster in detail.

**Comment by SAOPP** [comment]
How I can get this list and this details, please?

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/61547036-3b92e180-aa53-11e9-811e-f7eba6d35d8e.png)

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/61547107-63824500-aa53-11e9-82dc-680cb19e449b.png)

**Comment by SAOPP** [comment]
Here is on?

**Comment by SAOPP** [comment]
I post some pics of it, for understanding what about we are talking :)

![image](https://user-images.githubusercontent.com/5647009/61548420-5450c680-aa56-11e9-84d0-a09ffe191b4f.png)
![image](https://user-images.githubusercontent.com/5647009/61548426-57e44d80-aa56-11e9-96f0-a7d7f3e906b1.png)
![image](https://user-images.githubusercontent.com/5647009/61548431-5adf3e00-aa56-11e9-8648-1229215d10a5.png)
![image](https://user-images.githubusercontent.com/5647009/61548432-5e72c500-aa56-11e9-9d63-e755ac9cce95.png)
![image](https://user-images.githubusercontent.com/5647009/61548438-616db580-aa56-11e9-9e57-a09196b8e318.png)

**Comment by Smanar** [comment]
Yes, it's that, but I don't understand how work your device, I don't reconize your clusters. The only one that can be used is "unknow" ...

**Comment by SAOPP** [comment]
Could u please explain, what need to do else for better information of it? Thanks.

**Comment by Smanar** [comment]
Nothing you can do I think.
If your device realy have only the cluster 0017 to "communicate", someone need to search how works its attributes.

**Comment by SAOPP** [comment]
@Smanar Ok thanks, but is that enough for someone to add this device? I mean, is the current data sufficient for a device to be expected in the future? :)

Big thanks to all guys.

**Comment by Smanar** [comment]
I would not want to be a bad omen ^^, But for me, you need a motivated user to use a zigbee sniffer to "decode" how works this cluster, on this project or another zigbee project.
So for me it's not for tommorow, but I m not a specialist.

**Comment by SAOPP** [comment]
Okay, thank u for replys homie. I think we are get startred the Tie way to the Deconz. ;)

**Comment by kelvin5290** [comment]
Hi, May I know is this repo helpful?
https://github.com/Koenkk/zigbee-herdsman/issues/84

**Comment by SAOPP** [comment]
Btw yep, I also saw this topic about konkee...

**Comment by kelvin5290** [comment]
I own CR11S8UZ too and I am thinking is it useful for deconz to support this device.
