### ISSUE TITLE
New Device Request: Develco magnetic switch w/temperature sensor

### ISSUE THREAD

**Issue by pivot69** [dresden-elektronik/deconz-rest-plugin#1667]
I am trying to get this Develco magnetic switch to work and I have managed to get it included in the network.

Here's is all the info I could get:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/24453970/60983803-e829e080-a33a-11e9-8ab8-5d722c6c51f4.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/24453970/60983924-1e676000-a33b-11e9-89cb-717f49be1d99.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/24453970/60983982-37701100-a33b-11e9-83cc-b28ba827dd83.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/24453970/60984029-48b91d80-a33b-11e9-87ad-803da34fa511.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/24453970/60984066-5bcbed80-a33b-11e9-85b4-0729466ef78a.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/24453970/60984127-743c0800-a33b-11e9-84ea-436eb7e669d3.png">

Most of the clusters are either invalid or with general info like this:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/24453970/60984347-dd238000-a33b-11e9-8141-19a084cf8054.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/24453970/60984397-ed3b5f80-a33b-11e9-8f89-bb8109f79eac.png">

What I really need is to have a way of reading change status of the switch, when it happens.
It would also be nice with temperature reading, and of course battery status (it seems to be wrong now, they are fresh batteries).

If there is any more info I can send you to add this device just let me know :-)
Thanks!

**Comment by SwoopX** [comment]
Yay, another guinea pig :)

Could you please restart deconz and check if the node info panel changes (#1644 )?

General Develco support has already merged into the code. If you feel funny, you may compile the latest version and give it a try or you wait for the next official release.

**Comment by pivot69** [comment]
I’m happy to be a lab rat, especially when I can collaborate with the scientist to get the results needed 😎

Restart the device (from deconz GUI), the service or the raspberry pi itself?

**Comment by SwoopX** [comment]
:)
Deconz service should suffice...

**Comment by pivot69** [comment]
Now there is more! :-)

<img width="434" alt="image" src="https://user-images.githubusercontent.com/24453970/61005792-250ccc00-a369-11e9-9ad0-a4adfb4aafd5.png">
<img width="429" alt="image" src="https://user-images.githubusercontent.com/24453970/61005837-37870580-a369-11e9-83c9-9745d6893bf8.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/24453970/61005865-479ee500-a369-11e9-86ce-43f59bdd80da.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/24453970/61005884-54bbd400-a369-11e9-9e9d-db943f37cc69.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/24453970/61005907-5eddd280-a369-11e9-9b99-dc529106b149.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/24453970/61005922-6d2bee80-a369-11e9-9f58-9edc942bb963.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/24453970/61005948-7a48dd80-a369-11e9-93c9-de65d5f0d4f2.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/24453970/61005973-87fe6300-a369-11e9-9369-aeab7dd499c4.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/24453970/61005994-93518e80-a369-11e9-9ae5-b4eaeb31ae0d.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/24453970/61006006-9d738d00-a369-11e9-8e58-4f1f9722bb93.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/24453970/61006027-a7958b80-a369-11e9-9a3b-004243b2dc9c.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/24453970/61006044-b11ef380-a369-11e9-9a1d-a6f407d5e843.png">

**Comment by SwoopX** [comment]
Hm, first screenshot is not exactly what I expected. Funny thing is, the device has an IKEA manufacturer code but that is without the changes made for Develco. My smoke sensor, however, is mentioned as Dresden Elektronik device, even with the changes. The corresponding zigbee traffic doesn't show anything reasonable as mentioned in the referenced issue of my first reply. I'd love to have an opinion from @manup on this one though.

As I said, you may want to compile the current version of the plugin following the instructions in the readme. There's a chance getting it to work then (delete and new join). Otherwise, a bit patience is required.

**Comment by pivot69** [comment]
Strange that it identified it as a Router and not an End device too, right? 
But now its changed:

After triggering it (it seems unresponsive to the actual magnet switch, so i had to wake it by holding the sync-button until it started blinking) I could read some more via the clusters. It is alive for about 30 seconds when i trigger it like this.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/24453970/61124895-7e2f4980-a4a8-11e9-81d9-0c34d34b5243.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/24453970/61124912-8be4cf00-a4a8-11e9-9f1c-36890f2294af.png">
<img width="516" alt="image" src="https://user-images.githubusercontent.com/24453970/61124938-a4ed8000-a4a8-11e9-9f9c-d7d9d8546086.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/24453970/61124943-acad2480-a4a8-11e9-86d9-ea373db89e42.png">
<img width="516" alt="image" src="https://user-images.githubusercontent.com/24453970/61124955-b6cf2300-a4a8-11e9-85b1-0557affc3af7.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/24453970/61124965-bdf63100-a4a8-11e9-8318-a0dd13ee48b4.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/24453970/61124984-c64e6c00-a4a8-11e9-9330-7902609be0aa.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/24453970/61124999-ce0e1080-a4a8-11e9-8f57-530fdc1275ba.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/24453970/61125008-d8300f00-a4a8-11e9-8592-5d8d5a0ce339.png">

I cant seem to find the attribute for the actual magnet switch anywhere though... Is there something thats not being detected? I notice the c0c9 level control switch section being pretty much unknown...

I could compile the new version of the plugin, but first I think its best to cover all this so I dont break stuff for no purpose :-)

**Comment by SwoopX** [comment]
> Funny thing is, the device has an IKEA manufacturer code but that is without the changes made for Develco. My smoke sensor, however, is mentioned as Dresden Elektronik device, even with the changes.

What I mentioned earlier seems to be some "ghosting effect". I'd assume you also have some IKEA devices running...? No big deal, I hope

> I could compile the new version of the plugin, but first I think its best to cover all this so I dont break stuff for no purpose :-)

True story. I can fiddle with the code to support it, but I'd prefer to do that in my own fork first before pulling it. Also, it will only be exposed via REST API, meaning that you will most likely don't see it in Phoscon...

**Comment by pivot69** [comment]
Thanks for your follow up on this 🙂

Yep, got about 10 ikea remotes and maybe 35-40 ikea lights (float panels, spots and bulbs).

But what’s the next logical step now? Anything more I can share or try? 

Don’t want to way for a future fix, and would much rather try something and contribute with the development of this now. I have been needing these magnetic switches for a while now (got about 15-20 of them, ready to be used).

Also gonna get my Danalocks working, some smart outlets - and potentially some flammex smoke detectors... but that’s another story and another thread 😎

**Comment by SwoopX** [comment]
Well, point is, it needs to be tested.

**Theoretically**: With the change I made in my fork, the device should generally be supported. As to my understanding, the switching events should come in via IAS Zone cluster. Based on your latest screenshots, you've read the IAS Zone cluster attributes, but it reported not enrolled. I would expect this to change due to my commit. As a result, a sensor node in the REST API should be created and the device should also do/show switching.

Now the BUT: As I learned from my smoke detector, the device is a little bit subborn. First of all, the join is a pain in the ... and I have to restart deconz twice to have all nodes created and identified properly. Secondly, I get a rubbish response while reading the node descriptor, as all values are zero when I sniff the traffic. I'm not a zigbee expert, but this cannot be normal ( #1653). I'd also assume that this is the root cause for the join difficulties.
Now, I know that my device has an older firmware which can be concluded based on available documentation (technical manuals from develco and other sites). The latest (from develco) shows clusters which I do not have. My theory is that the firmware update could eventually fix the node descriptor as well as some other issues I experienced (e.g. temperature not being reported at all, not too sure if battery reporting is ok). Already reached out to Develco support but no response. Turned to Cozify support as well, as their gateway supports the sensors, but they seems to be not allowed to share the firmware.

I couldn't find any technical manual for your device on a quick search, however, I suspect it has the same issue with the node descriptor as well. To be honest, I currently do not see a high chance to get your sensors to work. Sniffing the zigbee traffic could give some further insights. Bought a CC2531 and another Raspbee for testing purposes and being able to play around if required.

As of now, I'm also a bit hesitant to buy another smoke sensor. Risk is too high that it has the same firmware for 50€ or the experienced behaviour persists. Too expensive for a try. But in #1424, I've seem that Develco has also devices which identify correctly ;)

**Comment by pivot69** [comment]
> Well, point is, it needs to be tested.
> 
> **Theoretically**: With the change I made in my fork, the device should generally be supported. As to my understanding, the switching events should come in via IAS Zone cluster. Based on your latest screenshots, you've read the IAS Zone cluster attributes, but it reported not enrolled. I would expect this to change due to my commit. As a result, a sensor node in the REST API should be created and the device should also do/show switching.
> 

Yeah, I was thinking the same and I have tried sending it commands to get it enrolled. Only reply I have managed to get is something like "UNSUP_CLUST_CMD" (if I remember correctly, I'm not near the device now so I cannot check...) even when trying to use the "standard" command of "Initiate Normal Operation Mode"

![image](https://user-images.githubusercontent.com/24453970/61202608-444c8600-a6e8-11e9-9548-dee8b3208004.png)


> **Now the BUT**: As I learned from my smoke detector, the device is a little bit subborn. First of all, the join is a pain in the ... and I have to restart deconz twice to have all nodes created and identified properly. Secondly, I get a rubbish response while reading the node descriptor, as all values are zero when I sniff the traffic. I'm not a zigbee expert, but this cannot be normal ( #1653). I'd also assume that this is the root cause for the join difficulties.
> Now, I know that my device has an older firmware which can be concluded based on available documentation (technical manuals from develco and other sites). The latest (from develco) shows clusters which I do not have. My theory is that the firmware update could eventually fix the node descriptor as well as some other issues I experienced (e.g. temperature not being reported at all, not too sure if battery reporting is ok). Already reached out to Develco support but no response. Turned to Cozify support as well, as their gateway supports the sensors, but they seems to be not allowed to share the firmware.
> 

The switch I have is actually a rebranded Develco product, sold by a company called "Home Control" in Norway with a product line called "Wattle". (The ones I have is the previous models, not the one your find on their site)

They use a lot of the Develco products with their controller and they are both eager to learn and has been very helpful with my support requests. It might be worth getting in touch with them to ask your in depth tech questions, and they might have valuable info to share about the Develco products and getting them working properly. They have been at it a while. 

https://wattle.com/support-main/contact-us/

> I couldn't find any technical manual for your device on a quick search, however, I suspect it has the same issue with the node descriptor as well. To be honest, I currently do not see a high chance to get your sensors to work. Sniffing the zigbee traffic could give some further insights. Bought a CC2531 and another Raspbee for testing purposes and being able to play around if required.
> 
> As of now, I'm also a bit hesitant to buy another smoke sensor. Risk is too high that it has the same firmware for 50€ or the experienced behaviour persists. Too expensive for a try. But in #1424, I've seem that Develco has also devices which identify correctly ;)

If you want I can send you one of my (new, still in the box) switches. I'll pay for the postage too. They are small and light, and should be quick and cheap to send. If you get it working you have a new magnetic switch for your network too ;-)

Can you DM me your shipping address? 
(is there even a direct message function on github??)

**Comment by ebaauw** [comment]
> I have tried sending it commands to get it enrolled. Only reply I have managed to get is something like "UNSUP_CLUST_CMD" 

I've yet to see a device that has implemented this command.  To enroll an _IAS Zone_ device manually, write the mac address of the RaspBee or ConBee to the _IAS_CIE_Address_ attribute.  The REST API plugin should take care of this automatically, once the device has been whitelisted.

**Comment by SwoopX** [comment]
> They use a lot of the Develco products with their controller and they are both eager to learn and has been very helpful with my support requests. It might be worth getting in touch with them to ask your in depth tech questions, and they might have valuable info to share about the Develco products and getting them working properly. They have been at it a while.

Yeah, great. I wanted to walk away from Develco and you keep me tempted... 😋  Are they also still fine if you don't use their gateway? I suppose you own one of those [https://wattle.com/product/magnetic-sensor/](https://wattle.com/product/magnetic-sensor/). Also seen that they have the somek sensors as well. I'd love to get my hands on any technical documentation as well as the firmware files...

**Comment by SwoopX** [comment]
Some good news.

Out of a sudden, attribute reporting started to work (temperature and battery). No idea why, but good that is does. Let me see what additions are required for the switch and prepare a PR. However, you still need to test it.

**Comment by pivot69** [comment]
> Some good news.
> 
> Out of a sudden, attribute reporting started to work (temperature and battery). No idea why, but good that is does. Let me see what additions are required for the switch and prepare a PR. However, you still need to test it.

NICE! :-D

I see that you have requested a merge. How long will it take before its merged? Tried running an upgrade now, but as I can see its still open so no changes on the source yet.

**Comment by pivot69** [comment]
> > I have tried sending it commands to get it enrolled. Only reply I have managed to get is something like "UNSUP_CLUST_CMD"
> 
> I've yet to see a device that has implemented this command. To enroll an _IAS Zone_ device manually, write the mac address of the RaspBee or ConBee to the _IAS_CIE_Address_ attribute. The REST API plugin should take care of this automatically, once the device has been whitelisted.

That doesnt seem possible. Its greyed out, not accessible for writing (see new screenshot, and earlier screenshot). Even when I try writing other places where the attribute has a rw settings I cannot write anything and it just gives me a "writing failed"...

<img width="536" alt="image" src="https://user-images.githubusercontent.com/24453970/61369191-e195ee80-a88f-11e9-81ac-ffb25deea0fc.png">

Or am I missing something? How can I write the mac-address to the attribute?

**Comment by pivot69** [comment]
> Yeah, great. I wanted to walk away from Develco and you keep me tempted... 😋 Are they also still fine if you don't use their gateway? I suppose you own one of those https://wattle.com/product/magnetic-sensor/. Also seen that they have the somek sensors as well. I'd love to get my hands on any technical documentation as well as the firmware files...

They are fine with it, but regular first line support cant offer me much support when using other gateways than theirs. But their technicians should be able to, and with your knowledge you might also be able to contribute something back so they also gain something. 

You can contact them through their regular support. I have a reference/name you can have so that you get in touch with the guy I've had contact with. He can probably direct you or help you directly.

But I guess I should rather send it through some kind of DM and not share it open here ;-)

I have the same magnetic switch, but its their previous version. Afaik it's the same on the inside.

**Comment by SwoopX** [comment]
> Or am I missing something? How can I write the mac-address to the attribute?

Jep, the whitelisting. That's part of my commit.

> I see that you have requested a merge. How long will it take before its merged?

Good questions. Just picked up manup is on vaccation...
I'd say let's wait for the merge and ideally an official release. We could use the discord channel mentioned in one of the latest issues.
