### ISSUE TITLE
Power-on default osram lights

### ISSUE THREAD

**Issue by intruder7777** [dresden-elektronik/deconz-rest-plugin#1668]
as mentioned in issue #102 is it possible to implement this functionality for osram lights?

**Comment by quotschmacher** [comment]
i would think this would be very useful. maybe even automated - whenever a parameter changes the new values could be stored as default to the bulbs (only the changed values). but this would be the next step - the first would be a simple button to store values (maybe even a feature for the deconz rest api)

**Comment by ebaauw** [comment]
Not sure that's a good idea.  The power-on settings are stored in non-volatile memory, which typically can be written only a limited number of times.  Writing it every time you change the light state might severely shorten the life time of the light.

**Comment by quotschmacher** [comment]
depends on how many write cycles the memory supports during life time and how often i want to write... but you are right. 
but as long as one can't wirte vie deconz that's not the question.

**Comment by lrybak** [comment]
Writing the power-on defaults each time the switch/light is toggled is not good idea as it can wearout the momory. Fully agree here.
But there should be an option to save power-on defaults on demand for paticular node. At the momment my OSRAM Flex strip is not usable as each time once power is lost (unfortunatelly common thing in my area) it turn on with furious bright light.

**Comment by intruder7777** [comment]
I think a possibility to store the actual  values as power-on default is enough . it is possible to do it with the osram gateway and the lightify app so it should be possible to do it with deconz

**Comment by lrybak** [comment]
> I think a possibility to store the actual values as power-on default is enough . it is possible to do it with the osram gateway and the lightify app so it should be possible to do it with deconz

Can you point me how to do that with deconz?

**Comment by intruder7777** [comment]
no sorry, actually it is not possible with deconz. it should be implemented by developer
