### ISSUE TITLE
Request to add NYCE NCZ-3041 Motion Sensor

### ISSUE THREAD

**Issue by ScottGA** [dresden-elektronik/deconz-rest-plugin#1669]
I saw a couple other version of NYCE motion detectors, but not the 3041.  Please add.  Thank you!!!

<img width="394" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/15620223/61029472-1b935c00-a389-11e9-8e37-8bf7930d02a1.png">
<img width="252" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/15620223/61029473-1b935c00-a389-11e9-9ad4-5a9401e8acaa.png">
<img width="363" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/15620223/61029475-1b935c00-a389-11e9-968c-9e33aa125790.png">
<img width="363" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/15620223/61029476-1b935c00-a389-11e9-938e-03f09ef3a1af.png">
<img width="363" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/15620223/61029477-1b935c00-a389-11e9-951c-d1c65e072d00.png">
<img width="369" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/15620223/61029478-1b935c00-a389-11e9-81b9-51b7fc89199a.png">
<img width="369" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/15620223/61029480-1b935c00-a389-11e9-9d84-793f852cb622.png">
<img width="369" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/15620223/61029481-1c2bf280-a389-11e9-95e2-e5f70dcd25a4.png">
<img width="369" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/15620223/61029482-1c2bf280-a389-11e9-9d22-519040f4314a.png">
<img width="369" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/15620223/61029483-1c2bf280-a389-11e9-8147-359bf6a86596.png">
<img width="369" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/15620223/61029484-1c2bf280-a389-11e9-9f53-cda0d3fba13d.png">

**Comment by ScottGA** [comment]
I would also like to add an additional request to include a different type of NYCE sensor in the updated database - the NYCE Door Hinge Sensor Model NCZ-3010.  I pasted the related screenshots below:
<img width="369" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/15620223/61088391-4b347980-a406-11e9-87fc-a3b3a18257dc.png">
<img width="361" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/15620223/61088393-4b347980-a406-11e9-82a6-a25b1c823425.png">
<img width="361" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/15620223/61088394-4b347980-a406-11e9-97b7-b7eaae1bbf53.png">
<img width="361" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/15620223/61088395-4b347980-a406-11e9-8849-90a2511897e9.png">
<img width="361" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/15620223/61088396-4b347980-a406-11e9-9f32-146ca1361ff1.png">
<img width="361" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/15620223/61088397-4b347980-a406-11e9-8981-4cafef472f23.png">
<img width="361" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/15620223/61088398-4bcd1000-a406-11e9-8af4-980cf67248bd.png">
<img width="361" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/15620223/61088399-4bcd1000-a406-11e9-8a02-a1539032ffc7.png">
<img width="369" alt="Screen Shot" src="https://user-images.githubusercontent.com/15620223/61088400-4bcd1000-a406-11e9-8f79-6bc2cace1627.png">

**Comment by ScottGA** [comment]
Is there anything I can do myself to use the above devices with deconz?

**Comment by ScottGA** [comment]
Is there any update on getting this sensor device added?

**Comment by jensflorian** [comment]
The NYCE3041 is HA1.2 compliant, so incorporation should be not too difficult. It is now sold in Germany by ubisys: https://www.smarthome-store.de/media/documents/NYCE_Feature%20Sheet_Motion%20Sensor.pdf  Is anyone able to use this in the deconz REST API?

**Comment by amunamu** [comment]
I would also like to have support for NCZ-3041
