### ISSUE TITLE
Cant control Philips LWB010

### ISSUE THREAD

**Issue by peer69** [dresden-elektronik/deconz-rest-plugin#1673]
Starting with 2.05.66 i cant control LWB010 Lamps from Phoscon GUI anymore. The gui only shows the slider for brightness which doesnt seem to work. 
Looking at Homekit using Homebridge-Hue I now see only a switch which still works but i cant dim the lights any longer: 

![IMG_5334](https://user-images.githubusercontent.com/28559804/61121384-58ea0d80-a49f-11e9-9bd3-61510637f482.png)
![IMG_5333](https://user-images.githubusercontent.com/28559804/61121386-5ab3d100-a49f-11e9-8759-42db1335e804.png)

Downgrading so 2.05.65 solves the problem.

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1616

**Comment by peer69** [comment]
Thanks for the reference. So this should be fixed with .67.
