### ISSUE TITLE
Power value of powerplug (lumi.plug)

### ISSUE THREAD

**Issue by renedis** [dresden-elektronik/deconz-rest-plugin#1692]
When using the API the output power number is round down.

e.g.:
11.55W = 11W
9.27W = 9W

When checking this in the GUI it's logging the values correct:
![reading-1155](https://user-images.githubusercontent.com/10537789/61535093-a92e1600-aa31-11e9-9c2b-794c4525c513.png)

While reported by the API as one round (rounded down) number.
![reading-1155-2](https://user-images.githubusercontent.com/10537789/61535142-c6fb7b00-aa31-11e9-82d8-f6562c92c972.png)

Please change this to the correct measured values in the API.
Also, please change this value to "report on change" to get good correct readings.

**Comment by renedis** [comment]
Is there any progress in this? Is there a way I can contribute?

**Comment by renedis** [comment]
Asking this again.. Is there any progress on this? Is there a way I can contribute?

**Comment by Smanar** [comment]
You can take a look in the code, I think it's de_web_plugin.cpp around line 6841.
But 11.5 W or 11 W don't change something, and I m not sure the device is accurate enought for that.

And I m not sure for report, but I think all devices works like that, spamming websocket. But you are right, if someone know a reason for that ? The home application can make calculation if it have only changed value every 30mn instead of the same value every 60s.

**Comment by renedis** [comment]
I've tried several times to find and adjust parameters but I couldn't find any solution to this.

Anyone else got an idea/solution?

**Comment by SwoopX** [comment]
Well, as I see it, you can steer value reporting to a certain extend, if the device has working attribute reporting. Check it out by double clicking on the numeric value in question in deconz GUI and please post a screenshot. By looking at the binding code, it might not be the case.
Anyhow, you might want to try increasing the min interval to see if it has any noticable effect. Values are in seconds.

**Comment by renedis** [comment]
issue still exists

**Comment by Mimiix** [comment]
@SwoopX We spoke about this the other day?

**Comment by SwoopX** [comment]
@Mimiix No, but leave it open. Still valid, but low prio. What's been implemented previously occurs only rarely...

**Comment by SwoopX** [comment]
bump

**Comment by SwoopX** [comment]
I'll implement a change which now does appropriate rounding.

![grafik](https://user-images.githubusercontent.com/4005212/87258061-e2f8f780-c4a0-11ea-8e7f-7a92ae72f1fa.png)

1. Value from the cluster
2. Currently reported via API
3. Updated report via API

**Comment by Mimiix** [comment]
@SwoopX This is where i can be of use. Integers in SQL environments oftenly just use the first number and don't round at all. Your CAST does fix this indeed, but it isn't appropriate. 

Can't we store it as a float with a round?

**Comment by SwoopX** [comment]
Taken care of with version .79. Closing this
