### ISSUE TITLE
Device support request for Zen Thermostat

### ISSUE THREAD

**Issue by arakasi55** [dresden-elektronik/deconz-rest-plugin#1702]
Hi, I have a Zen Thermostat that I'd like to have supported by DeConz. 
Here are the node and cluster info screenshots.
Thanks.

<img width="445" alt="Screen Shot 2019-07-23 at 7 36 34 pm" src="https://user-images.githubusercontent.com/51733827/61704008-20dba800-ad86-11e9-9130-bcc36164c2f8.png">

<img width="444" alt="Screen Shot 2019-07-23 at 7 36 46 pm" src="https://user-images.githubusercontent.com/51733827/61704029-2c2ed380-ad86-11e9-9028-8b45d140c2a9.png">

<img width="425" alt="Screen Shot 2019-07-23 at 7 39 18 pm" src="https://user-images.githubusercontent.com/51733827/61704042-351fa500-ad86-11e9-8e19-d90671176bc4.png">

<img width="587" alt="Screen Shot 2019-07-23 at 7 44 57 pm" src="https://user-images.githubusercontent.com/51733827/61704050-3b158600-ad86-11e9-9226-9bed42bc300b.png">

<img width="587" alt="Screen Shot 2019-07-23 at 7 45 11 pm" src="https://user-images.githubusercontent.com/51733827/61704062-47014800-ad86-11e9-939d-516b8adbb9b9.png">

<img width="589" alt="Screen Shot 2019-07-23 at 7 45 17 pm" src="https://user-images.githubusercontent.com/51733827/61704079-508ab000-ad86-11e9-8304-0d15308d0d6f.png">

<img width="399" alt="Screen Shot 2019-07-23 at 6 53 40 pm" src="https://user-images.githubusercontent.com/51733827/61704184-8334a880-ad86-11e9-8df3-9cbb9edc8685.png">

**Comment by MarhyCZ** [comment]
Hi, I was just looking for a thermostat to use in HomeAssistant. Either through Wifi or ZigBee. This Zen one has a really nice design. Are you planning on adding this to REST API? 

Have a nice day :)

**Comment by ggg22** [comment]
Hi, I wonder if the Zen thermostat is fully supported. Google searches suggest that is not the case since I haven't seen anybody posting a successful implementation.
While I am able to join the network with the Zen thermostat, the device is not visible in the Phoscon app. From there I plan to use it in Homeseer but at the moment this is not possible.
Can anybody comment, please?

![image](https://user-images.githubusercontent.com/18381748/71925632-626fdc00-3189-11ea-8c36-929ff1442753.png)

**Comment by crixyd** [comment]
For anyone who is reviewing this ticket to confirm support, I can confirm full ZEN thermostat compatibility for temperature reporting and control & mode reporting and control. It's rock solid, and vastly superior to the MQTT implementation 👍

**Comment by ggg22** [comment]
Thanks very much for this update! Much appreciated!

 

Regards,

-George

**Comment by ggg22** [comment]
Thanks for the tips.

I still have to update to 2.05.79 and also figure out how to use VNC interface to modify the report intervals.

I noticed that it’s not updating temperature from the device.

The “set point” is updated TO the device but nothing is updated FROM the device.

If you change the “set point” temperature on the device itself this is not updated to Phoscon either.

 

Thanks,

-George

**Comment by barryl93** [comment]
Does this device support switching mode ("Off" to "Heat" for example) through Zigbee? I have it set up through Homebridge-Hue and it communicates the temperature and set point in both directions, but if I switch from Heat to Off or vice versa on my phone, the mode doesn't switch on the thermostat. If I switch from Heat to Off on the thermostat, it WILL update correctly on my phone, though.

Does anyone have any experience with this device and this issue?

**Comment by crixyd** [comment]
This used to work, however somewhere along the line they updated the integration and now to turn off the unit you just need to set the temp to the lowest possible. Still works but not as well as it used to.

**Comment by barryl93** [comment]
Thanks for the confirmation. Yeah, now I just crank the temp way down to emulate "Off." Kinda frustrating, though, that I can't just say, "Hey, Siri, turn off the heat!" She'll turn it off on my phone, but it won't actually change anything on the thermostat. So  I just have to keep that in mind.

**Comment by ericyew** [comment]
don't understand why the control doesn't work. Can someone have a look at this?
