### ISSUE TITLE
Aqara Zigbee 3 Devices

### ISSUE THREAD

**Issue by brettyj** [dresden-elektronik/deconz-rest-plugin#1704]
Hi All,

Sorry for posting here, I'm not sure where else to post to ask this question - but with the announcement of the new Zigbee 3 Aqara devices (https://homekitnews.com/2019/07/08/aqara-unveils-new-m2-homekit-hub-switches-locks-cameras-and-more/), has anyone noticed them for sale yet? Will they work with deconz? Now they are zigbee 3, does that mean that they are more compatible with other devices now?

I was about to purchase a bunch of aqara devices, is it worth waiting for these T1s?

**Comment by MattL0** [comment]
Following

**Comment by kmplngj** [comment]
Does any one have news about this?
