### ISSUE TITLE
raspbee module not detected

### ISSUE THREAD

**Issue by mariusmotea** [dresden-elektronik/deconz-rest-plugin#171]
Hi,

Today i received my raspbee module, plugged it in my Raspberry 2 as explained, parse all software installation steps from this README and when i start deconz it is unable to connect to the raspbee module. Is there a way to debug what is the problem here? 
I'm very good with linux and electronics but i don't know how this is working, so i'm helpless. The sd card was flashed with latest raspbian version, i had issues to compile de rest plugin (/usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory) and in order to solve it i add ```qmake QMAKE_CFLAGS_ISYSTEM= && make -j2```. On boot the led on module is blinking green 2 times fast then remain red.

Update: if i start deconz-autostart.sh with sudo, then it will connect for a few seconds to raspbee module, then disconnect and ask for firmware update. This produce a reset to module, but next time ask again for firmware update.

Thanks,
Marius.

**Comment by mariusmotea** [comment]
I found the issue. Raspbee module is using the serial interface for communications with raspberry pi, and by default serial port is used by system for shell login/messages, and this cause a conflict. I run raspi-config and under serial interface i disable login shell access over serial interface ( leave hardware enabled). Please update README because new users will spend lot of time to solve same problems.

**Comment by donnib** [comment]
Eu am folosit imaginea oficială de la Dresden si a funcționat ok dar bănuiesc că ai dreptate dacă folosești o imagine generica.
