### ISSUE TITLE
Philips lamp reset vs. deconz

### ISSUE THREAD

**Issue by WWebber** [dresden-elektronik/deconz-rest-plugin#1713]
Is it possible to reset the bulb via deconz-REST-API when I know the serial number, but have no dimmer for a factory reset handy?

**Comment by ebaauw** [comment]
No.

You might try and reset the bulb in the old web app using touchlink.

The Hue bridge factory resets the light when it's removed from the bridge, so there must be a regular Zigbee command for that.  The deCONZ GUI shows the _Restore to Factory Defaults_ command in the _Cluster Info_ panel for the _Basic_ cluster, but I'm not sure if that's the actual command the Hue bridge sends.
