### ISSUE TITLE
Conbee 2 will not connect to IKEA devices

### ISSUE THREAD

**Issue by KrisBird** [dresden-elektronik/deconz-rest-plugin#1716]
I have installed deConz on a windows PC and is able to find the Conbee both in deConz and when opening 192.168.1.160. It will however not add any IKEA devices - have tried 3 different  light blubs (was reset before) and 1 remote control.

I have tried 4 different channels (11, 15, 20, 25) - both changing them Phoscon app and the deConz app.  Set scanning time for 10 minutes.

The Conbee II is updated to latest firmware 26490700.

I have also tried with Docker on a Synology NAS. Same issue - I can see the conbee II gateway but it will not connect to anything.

Have also tried with USB extender cord.

![2019-07-29 (3)](https://user-images.githubusercontent.com/43586475/62063387-0cd2f300-b22b-11e9-9b24-8fc61fd2b408.png)
![2019-07-29 (2)](https://user-images.githubusercontent.com/43586475/62063393-0f354d00-b22b-11e9-8446-dbad243355e1.png)

**Comment by Smanar** [comment]
Hello, have you tried whith "reseting" (playing with on/off) the bulb during the permit join and not before ?

**Comment by KrisBird** [comment]
Yes the light bulbs have been reset by switching them on and off 6 times and I saw it blinking at the end.

**Comment by Smanar** [comment]
I think there is nothing to see with your issue, but someone have a strange bug too, He need to power cycle his gateway to make pairing working > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1691

By curiosity, you haven't tried with another manufacturer ? Remote control don't pair too ?

**Comment by KrisBird** [comment]
Thanks for trying to help.
I have tried now with docker, windows and a raspberry pi image from phoscon.de. I have tried pairing with both remote and brand new IKEA light bulb. I can see the conbee but it will not pair at all. Tried all different channels and different security modes.

I am in contact with dresden-electronics to see if they are able to help out.

**Comment by thecem** [comment]
Did you try:

sudo systemctl stop deconz
sudo GCFFlasher_internal -r
sudo systemctl start deconz

and try to pairing in the next 5 minutes?

**Comment by Sku1ly** [comment]
I had this issue and solved it but reseting the ikea lights using a Philips hue remote. Hold on and off right next to it until it flashes, goes off then on again.

**Comment by Smanar** [comment]
You can try too the touchlink feature, but your bulb need to be realy close to the gateway, I can tell you how it work exactly, I have never tried it.
Go in phoscon help/old web app version then menu/setting/scan for devices.

**Comment by masterpanic** [comment]
Jop it works !!!

**Comment by thetravellor** [comment]
Im having the same problem, have just returned the stick to Amazon as faulty.
