### ISSUE TITLE
Xiaomi Door contact as sensor for lighting control

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#1717]
Hello, I have a door contact in the Deconz, but I can not use it for any of the lights. Neither as a switch nor as a sensor.

I wanted to set it that way when the door is open, the light goes on.
And if too light then off.

Can you do that?

Thank you

![sshot-2019-07-30- 1](https://user-images.githubusercontent.com/32480002/62136576-aad6c400-b2e4-11e9-857c-ce16c93fcfa9.jpg)

**Comment by Smanar** [comment]
Hello, you can take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1674
But I think it will easier to do that with your home automation application.

**Comment by RezzZ** [comment]
@Smanar sorry but I have to disagree with that statement.

Saying it is easier to do it with home automation might be right at this point as we cannot do this properly in Deconz but shouldn't deconz allow us to select these sensors as well in the first place?
The control via zigbee sensors should remain in deconz and should not be handled by other homeautomation software like nodered or homeassistant.

An open/close sensor is just as valid as a motion sensor to turn on/off lights. At leats for my case:
I have an attic foldable stairs and I have an open/close sensor there. If the stairs are 'open', meaning I can walk up to the attic I want my lights to stay on. If I close the attic door the lights should turn off. Same would be usable for closets etc.

If the door remains open, the light should be turned on and stay on until the door is closed again...

**Comment by mgrn0** [comment]
I would love to be able to do exactly the same thing - use a door sensor to turn off a light. please?

**Comment by Proche72** [comment]
Hi, is there any development on this?

**Comment by SwoopX** [comment]
That is a question to be raised at the Phoscon repository, not here.

**Comment by mgrn0** [comment]
@SwoopX I am confused since there was a lot discussion about this specific topic here, and not in the Phoscon repository. Can you point us in the right direction or should we open an identical issue there?  is https://github.com/dresden-elektronik/phoscon-app-beta/issues the right place?

**Comment by SwoopX** [comment]
Yes, the link you mention is the right place. DE has just recently re-opened the repo to keep the topics seperated.

**Comment by mgrn0** [comment]
thanks @SwoopX , opened an issue there. (@Proche72 , @RezzZ  - you might want to jump in ;)
