### ISSUE TITLE
Cirtical: ConBee 2 on Raspberry Pi 4: "not in network" - caused by any other USB device plugged to the Raspberry

### ISSUE THREAD

**Issue by flobernd** [dresden-elektronik/deconz-rest-plugin#1723]
Hi there,

I'm getting the above problem with my ConBee 2 stick using the new Raspberry Pi 4.

The strange thing is that e.g. the flasher is able to update the firmware and the deconz app is able to connect and even read network infos for example.

Just no network connection ..

Is there anything I can do? I'm using version 2.05.66 in a docker container.

Best regards

**Comment by flobernd** [comment]
Well .. this is .. frustrating. The ConBee 2 works fine if I don't connect any other USB device to my Raspberry.

This is no option for me sadly. Let me know if I can help you out fixing this problem.

**Comment by ebaauw** [comment]
See #1643.
