### ISSUE TITLE
CentraLite 3326 Motion Sensors

### ISSUE THREAD

**Issue by DrJeff** [dresden-elektronik/deconz-rest-plugin#1731]
Having some trouble adding 3326-L Motion Sensors (Iris Motion Gen2) and 3320-L Door Sensors (Iris Gen2). Is the only way to get these working still to follow this guide https://github.com/dresden-elektronik/deconz-rest-plugin/issues/623#issuecomment-437649093 and compile myself? After compiling and adding can I revert to using the Docker version? Or do i have to continue to use the compiled version running on Ubuntu?

**Comment by dale3h** [comment]
I am having similar issues as well. Have you found a solution to this yet?

**Comment by nphil** [comment]
I would like to know this too, I tried adding these via Phoscon, but they would not pair.

**Comment by mike3y** [comment]
Love to know if this gets fixed. I bought the dongle, but just cancelled my order until I hear more.

**Comment by nphil** [comment]
Attached screenshot with information
<img width="1371" alt="Screen Shot 2019-10-25 at 12 26 59 PM" src="https://user-images.githubusercontent.com/1761280/67587957-e4bc3880-f722-11e9-85e7-b71b463f26c3.png">

**Comment by dbmet** [comment]
Just curious if there has been any movement on getting these working?

**Comment by arraylabs** [comment]
Curios as well. I have a pile of these.

**Comment by Hackshaq** [comment]
I am having a similar issue. I have been able to pair these and have them show up in the Wired view but not the web app. How do I fully add them to the mesh?

![Deconz 3326L](https://user-images.githubusercontent.com/7549065/72489051-6da1b800-37d8-11ea-99a8-13bb5a9dfcc0.png)

**Comment by rmotapar** [comment]
Any updates on this issue? I am a newbie trying to move from hubitat to hassio/Deconz setup for my ZigBee devices. I have a bunch of Centralite 3326 motion sensors. Wish I knew about this issue before I started the project.

**Comment by manup** [comment]
Interesting, the manufacturer code seems to be different.
Here is mine (working):

![image](https://user-images.githubusercontent.com/383386/74955490-04c7e400-5405-11ea-8d76-aca59a78d0bb.png)

![image](https://user-images.githubusercontent.com/383386/74955615-304ace80-5405-11ea-85c1-35899cca6d35.png)


Can you please also provide a screenshot of the basic cluster after reading the attributes. I'll add the sensor to the list then.

**Comment by rmotapar** [comment]
> Interesting, the manufacturer code seems to be different.
> Here is mine (working):
> 
> ![image](https://user-images.githubusercontent.com/383386/74955490-04c7e400-5405-11ea-8d76-aca59a78d0bb.png)
> 
> ![image](https://user-images.githubusercontent.com/383386/74955615-304ace80-5405-11ea-85c1-35899cca6d35.png)
> 
> Can you please also provide a screenshot of the basic cluster after reading the attributes. I'll add the sensor to the list then.

Thank you for the quick response. Assuming you were asking me, I am not yet sure how to get you the screenshots you asked for but I should be able to setup whatever is necessary. My setup until now involved adding the deconz add-on to hassio which has access to conbee ii. I was almost about to return the Conbee ii but this gives me hope. I will paste the screenshots soon. Thanks again @manup

**Comment by manup** [comment]
Thanks, want I'd like to check is the basic cluster "Model Id" attribute of the sensor version with the manufacturer code 0xc2df from above.

**Comment by dbmet** [comment]
> Thanks, want I'd like to check is the basic cluster "Model Id" attribute of the sensor version with the manufacturer code 0xc2df from above.

Let see If this works. 
![Screenshot from 2020-02-20 15-54-54](https://user-images.githubusercontent.com/7477742/74982302-7e59d500-53f9-11ea-85dd-cb75943c5c28.png)

![Screenshot from 2020-02-20 15-54-33](https://user-images.githubusercontent.com/7477742/74982311-8285f280-53f9-11ea-8766-09d3b5d6958c.png)

**Comment by rmotapar** [comment]
@manup I have two different kinds of lowes motion sensors. One is 3326-L and another is iL07_1 which measures himidity as well (this was the latest lowes version). I tried to add two 3326-L and one iL07_1 units and all three don't appear in the deconz UI. Attached some screenshots. Please let me know if you need anything else.

![Centralite 3326-L Motion Sensor 2](https://user-images.githubusercontent.com/13870280/74991365-5f643e80-540b-11ea-9ff0-6e4746d2deea.PNG)



![Centralite 3326-L Motion Sensor Cluster Info](https://user-images.githubusercontent.com/13870280/74991374-64c18900-540b-11ea-93cb-51f0cba36703.PNG)
![Centralite iL07_1 motion sensor](https://user-images.githubusercontent.com/13870280/74991376-68551000-540b-11ea-9b5e-275bc7fc245c.PNG)

**Comment by manup** [comment]
Thanks I'll check the respective code sections if there is something missing for these.

**Comment by soydeboca** [comment]
I'm also trying to pair these gen2 contact sensors from Lowe's that I was using flawlessly in Smartthings, but it appears that the pairing process does not complete (the green dot is blinking permanently). 

![2020 02 25_17 21 01 - HA__deCONZ_(Home_Assistant_-_deCONZ)_-_VNC_Viewer](https://user-images.githubusercontent.com/27639753/75284297-4684d000-57f3-11ea-89fa-9aec38c411f9.png)

**Comment by rmotapar** [comment]
@manup @SwoopX Would you please consider adding support for these sensors in the next release if at all possible?

**Comment by SwoopX** [comment]
@manup are you already into this? Otherwise, I'd put it on my list ;)

**Comment by SwoopX** [comment]
Ok, let me take care of that. Manup has already made some preparations. Can any of you guys please poste a screenshot of the power configuration cluster with the attributes being read?

**Comment by rmotapar** [comment]
@SwoopX  Thank you for looking into this. Is this what you were asking?

![image](https://user-images.githubusercontent.com/13870280/75822180-24e09700-5d65-11ea-90d7-910a1492380f.png)

**Comment by SwoopX** [comment]
Jep, thanks, Wanted to be sure about the battery voltage.

**Comment by soydeboca** [comment]
Mine looks like this
![2020 03 03_19 59 12 - HA__deCONZ_RPI4_(Home_Assistant_-_deCONZ)_-_VNC_V](https://user-images.githubusercontent.com/27639753/75828014-acd89800-5d89-11ea-8648-212b4a82c3d3.png)

Thanks SwoopX!

**Comment by Hackshaq** [comment]
@manup <https://github.com/manup> @SwoopX <https://github.com/SwoopX> While
we are talking about these Centralite sensors, can you guys work to
officially support as many of their devices as possible? Now that the
Lowes/Iris platform is dead, ebay is flooded with Centralite stuff, and it
is cheap. Iris had a bunch of useful stuff I would love to add to my Deconz
zigbee, such as the 3460 Smart Button. In the US at least, the Deconz
platform would be a lot more useful if you had more complete support for
this Centralite stuff, just based on the amount of devices available. I
dont want to go get a bunch of these, only to find out they are not working
with Deconz at the moment.

Thanks. David

**Comment by SwoopX** [comment]
Well, that's easier said than done. Each and every device may have it's quirks which need to be known and sorted out. With a detailed technical documentation, that would be far easier, as it usually provides the necessary details.

A good example for that is cluster FC0F from the screenshot above. We don't know nothing about it unless we do some reverse engineering and/or sniff the traffic.

**Comment by DrJeff** [comment]
@SwoopX What else do ya need more power attributes?

**Comment by soydeboca** [comment]
Sorry if I missunderstood, it's supposed to be working for both sensors mentioned on the first post (3326 and 3320)?

I'm using deconz v2.05.75 as an Home Assistant add-on and cannot add my Iris contact door sensors that DrJeff also mentioned on the first post (CentraLite 3320-L). This issue is only about the CentraLite 3326 and I have to open a new one? Thanks

**Comment by SwoopX** [comment]
Please open a new request for that. It has not been integrated yet.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!

**Comment by dmike3** [comment]
Any update on this? Is it working?

**Comment by dbmet** [comment]
> Any update on this? Is it working?

Yes they work. I have a couple added to my system
