### ISSUE TITLE
Xiaomi WXKG01LM switch/button creates bogus light switch

### ISSUE THREAD

**Issue by xbmcnut** [dresden-elektronik/deconz-rest-plugin#1733]
I have two WXKG01LM buttons in deCONZ under Hassio and one created a battery level sensor in the add-ons integrations page along with a bogus light switch that responds to button pushes. Light is always on and goes off when button pushed.

![image](https://user-images.githubusercontent.com/1492137/62517804-41bef580-b87c-11e9-8b5a-ac7ca7101374.png)

![image](https://user-images.githubusercontent.com/1492137/62531434-8c4d6b80-b896-11e9-910e-4efd5fa2f18d.png)

![image](https://user-images.githubusercontent.com/1492137/62517824-4a173080-b87c-11e9-88aa-7fc50f4d16b3.png)

The other switch/button for the master bedroom works and creates deCONZ events in Hass but does not show any sensors in the add-on configuration page.

Is there a fix for that?

Conbee II 26490700
Hassio add-on version 3.1
deCONZ version 2.05.66

**Comment by Smanar** [comment]
Hello, have you tried to delete then and re-pair them ?
It's not normal having 2 differents reactions for same sensor. All the "magic" is done during the pairing process, but it can be defective.

**Comment by xbmcnut** [comment]
That worked, thanks.
