### ISSUE TITLE
IKEA Tradfri Bewegungsmelder schaltet OSRAM Steckdosen willkürlich

### ISSUE THREAD

**Issue by LJSven** [dresden-elektronik/deconz-rest-plugin#1734]
Ich habe am 2 neue IKEA Tradfri Bewegungsmelder angelernt. Ich habe den Eindruck, daß wenn wenn der Bewegungsmelder auslöst, die OSRAM Smart Plugs geschaltet werden / zumindest sind sie aktiv in der App (und im ioBroker). Gibt es dafür eine Lösung?

**Comment by Smanar** [comment]
I m not sure (I have used google translate) But I think you have more information here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1676
But no solution yet.
