### ISSUE TITLE
Hue tap is not displayed under deconz-gui and problem with rename coordinator

### ISSUE THREAD

**Issue by Nastras** [dresden-elektronik/deconz-rest-plugin#1735]
Hello everyone, can anyone tell me if it is normal that the Hue Tap is not displayed in the deconz-gui? I have to test a hue lamp and a hue tap integrated but only the lamp is displayed.

<img width="853" alt="Bildschirmfoto 2019-08-06 um 13 49 56" src="https://user-images.githubusercontent.com/27686185/62537603-1d99ef00-b851-11e9-958b-956b40f71c09.png">

Is it because the hue tap is not a battery powered device?

Another thing still, if I change the name of the coordinator in the Node Info window this is not saved. After a restart it disappeared again. 

Thanks for the help.

King Regards

Nastra

**Comment by ebaauw** [comment]
ZGP switches don’t show in the GUI.

The possibility to change the coordinator name was lost several versions ago, when the database was extended to persist devices.

**Comment by Nastras** [comment]
@ebaauw Thank a lot for the answer.
