### ISSUE TITLE
Phoscon App does not connect to ConBee 2 stick

### ISSUE THREAD

**Issue by Mikha495** [dresden-elektronik/deconz-rest-plugin#1736]
Hi!

have an issue with the ConBee 2 stick. Installed everything according to the manual on my Raspberry Pi with HOOBS as platform (Homebridge). After logging into the Phoscon App, the stick seems to be not recognized. 
Running lsusb in terminal, shows me a Dresden Electronics device connected. 
Can you help, please?

<img width="660" alt="image" src="https://user-images.githubusercontent.com/53826518/62572859-02e96980-b895-11e9-88ce-17606bc82d0a.png">

Here's the log:
Started Homebridge.
pam_unix(sudo:session): session closed for user root
[8/6/2019, 9:50:08 PM] Loaded config.json with 2 accessories and 2 platforms.
[8/6/2019, 9:50:08 PM] ---
[8/6/2019, 9:50:08 PM] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[8/6/2019, 9:50:08 PM] Loaded plugin: homebridge-config-ui-x
[8/6/2019, 9:50:08 PM] Registering platform 'homebridge-config-ui-x.config'
[8/6/2019, 9:50:08 PM] ---
[8/6/2019, 9:50:09 PM] Loaded plugin: homebridge-hue
[8/6/2019, 9:50:09 PM] Registering platform 'homebridge-hue.Hue'
[8/6/2019, 9:50:09 PM] ---
[8/6/2019, 9:50:09 PM] Loaded plugin: homebridge-shelly-shutter
[8/6/2019, 9:50:09 PM] Registering accessory 'homebridge-shelly-shutter.shelly-shutter'
[8/6/2019, 9:50:09 PM] ---
[8/6/2019, 9:50:10 PM] Loaded plugin: homebridge-xiaomi-roborock-vacuum
[8/6/2019, 9:50:10 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[8/6/2019, 9:50:10 PM] ---
[8/6/2019, 9:50:10 PM] Loading 2 platforms...
[8/6/2019, 9:50:10 PM] [Config] Initializing config platform...
[8/6/2019, 9:50:10 PM] [Config] Running in Standalone Mode.
[8/6/2019, 9:50:10 PM] [Hue] Initializing Hue platform...
[8/6/2019, 9:50:10 PM] [Hue] config.json: warning: philipsLights: ignoring unknown key
[8/6/2019, 9:50:10 PM] [Hue] homebridge-hue v0.11.31, node v10.16.1, homebridge v0.4.50
[8/6/2019, 9:50:10 PM] Loading 2 accessories...
[8/6/2019, 9:50:10 PM] [Rollade groß] Initializing shelly-shutter accessory...
[8/6/2019, 9:50:10 PM] [Roborock] Initializing XiaomiRoborockVacuum accessory...
[8/6/2019, 9:50:10 PM] [Roborock] ERR Constructor | No vacuum cleaner is discovered yet.
[8/6/2019, 9:50:10 PM] [Roborock] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
[8/6/2019, 9:50:11 PM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.66, api v1.16.0
[8/6/2019, 9:50:11 PM] [Hue] Daylight: set homekit light level from 0.0001 lux to 9.9977 lux
[8/6/2019, 9:50:11 PM] [Hue] Phoscon-GW: 1 accessories
[8/6/2019, 9:50:11 PM] [Hue] masked debug info dumped to /var/lib/homebridge/homebridge-hue.json.gz
[8/6/2019, 9:50:11 PM] [Hue] Initializing platform accessory 'Phoscon-GW'...
[8/6/2019, 9:50:11 PM] [Hue] Phoscon-GW: 3 services
Setup Payload:
X-HM://0023ISYWYJ717
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
...                              
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
...

[8/6/2019, 9:50:11 PM] Homebridge is running on port 51826.
[8/6/2019, 9:50:58 PM] [Config] Starting terminal session
[8/6/2019, 9:52:09 PM] [Config] Terminal session ended.
   hoobs : TTY=pts/1 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x
pam_unix(sudo:session): session opened for user root by (uid=0)
[8/6/2019, 9:54:44 PM] [Hue] Daylight: set homekit status from 200 to 210
[8/6/2019, 9:54:44 PM] [Hue] Daylight: set homekit light level from 9.9977 lux to 1.2586 lux
[8/6/2019, 9:54:44 PM] [Hue] Daylight: set homekit last event from Sunset to Dusk
[8/6/2019, 9:54:44 PM] [Hue] Daylight: set homekit period from Twilight to Nautical Twilight

**Comment by Mikha495** [comment]
Have the Conbee 2 directly connected to the Raspberry, as no USB extension cable available at the moment. Can this cause this issue?

**Comment by Mikha495** [comment]
> Have the Conbee 2 directly connected to the Raspberry, as no USB extension cable available at the moment. Can this cause this issue?

Have now connected a 1,8m USB extension cable and restarted Homebridge. No result, no change...
Please help!

**Comment by Smanar** [comment]
Hello, you have another problem, your conbee is detected as raspbee.
Take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1433

**Comment by Mikha495** [comment]
Result is:
hoobs@hoobs:/var/lib/homebridge $ sudo GCFFlasher_internal -l
GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Path | Vendor | Product | Serial | Type
-----------------+--------+---------+------------+-------
/dev/ttyS0 | 0x0000 | 0x0000 | | RaspBee
/dev/ttyACM0 | 0x1CF1 | 0x0030 | DE1995980 | ConBee II

Unfortunately, can't follow the solution in #1433. If this would solve the issue, could you be so kind and describe me the necessary steps to move the device to a different location?

**Comment by manup** [comment]
Hi, can you please check the basic troubleshooting for ConBee II on Linux:

http://phoscon.de/en/support#conbee2-connection-issues

**Comment by Smanar** [comment]
Hello, why in some case the conbee is see at /dev/ttyACM0 and for some other config as /dev/ttyUSB0 ?
With a simple raspberry ?

**Comment by manup** [comment]
>it's an hardware difference between conbee 1 and 2 ?

This.
* The ConBee I has a FTDI USB chip and enumerates as /dev/ttyUSBx.
* The ConBee II has native USB support and enumerates as /dev/ttyACMx.

**Comment by Mikha495** [comment]
It's working now. I believe the issue was the missing
sudo gpasswd -a $USER dialout

However, I believe to remember, that I did entered it during the initial installation.

**Comment by Mikha495** [comment]
After trying to add a new light, Phoscon again lost the connection to the ConBee II and I'm back, where I've been before. 
Any suggestions?

**Comment by Mikha495** [comment]
Now I deleted flashed the ConBee, deleted and reinstalled deconz. Now, Phoscon doesn't find the ConBee during the search sequence at all. 
I'm lost...

**Comment by Smanar** [comment]
Restart all checks from the start from @manup link.

> GCFFlasher_internal -l

Unplug/replug the conbee to restart the gateway

**Comment by Mikha495** [comment]
Did everything from the troubleshooting page. No results

**Comment by Smanar** [comment]
And the result for "GCFFlasher_internal -l" ?

**Comment by Mikha495** [comment]
CFFlasher V3_06 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyS0       | 0x0000 | 0x0000  |            | RaspBee 
/dev/ttyACM0     | 0x1CF1 | 0x0030  | DE1995980  | ConBee II

**Comment by Mikha495** [comment]
Is it what it should show?

**Comment by Smanar** [comment]
Unfortunately yes, she is correctly detected.
Have you tried to force a firmware update with the GCFFlasher_internal  command ?
You config is still like this one (I think yes, if she have suddenly stopped working) ?
https://user-images.githubusercontent.com/1177810/44988558-66835c80-af8b-11e8-9cc1-751f60c2b439.png
I realy don't have more ideas, I think  the next step will be logs, but I can't help you a lot for that.

**Comment by Mikha495** [comment]
I've reinstalled deconz as root. No changes. 
I'm using hoobs for Homebridge, so as my understanding the default username is hoobs. Hence I'm putting in 
sudo gpasswd -a hoobs dialout
Is that correct?

**Comment by Smanar** [comment]
Yep, you can use 
`whoami`
To be sure having the good user name, then your command (and restart)

You have no error message when trying to update your firmware whith command ?

**Comment by Mikha495** [comment]
Have flashed the firmware with 
sudo GCFFlasher_internal -d /dev/ttyACM0 -f deCONZ_ConBeeII_0x26490700.bin.GCF
and it ran well. Now, Phoscon lets me login and I see a device, which is "not connected". Basically, I'm there, where I've been before. 
Going crazy...
<img width="653" alt="image" src="https://user-images.githubusercontent.com/53826518/62831306-2e65ae80-bc1d-11e9-9a06-a636da815e1e.png">

**Comment by Mikha495** [comment]
After several attempts successfully installed deCONZ in debugg mode. 
Now, everything runs, as it should. Will see for how long...

**Comment by Smanar** [comment]
By curiosity, you don't have special hardware ? External drive, PI4 with usb 3.0, or other ?

**Comment by Mikha495** [comment]
Nope, nothing else connected to the Raspbi

**Comment by Mikha495** [comment]
After taking all my network devices incl. Raspberry from power, the ConBee II again can’t be connected. 
Same issue as before... 
anyone an idea what is going wrong with my setup???

**Comment by jose-d** [comment]
1) try to change your USB power source incl. possible cabling
2) try to go with vanilla Raspbian + standard clean installation of deCONZ

**Comment by Mikha495** [comment]
Found out, that deCONZ is somehow not booting (or not booting correctly) after unplugging from power. 
I’ve to manually stop and disable deCONZ, restart Homebridge and start and enable deCONZ. 
Then it runs. 

Any idea how to set it up correctly?

**Comment by ebaauw** [comment]
deCONZ crashes (SIGABRT) when started in non-minimal mode before the graphical environment (X11 server) has been started.  During boot, this happens a few times in quick succession, and sometimes `systemctl` gives up on the `deconz-gui` service.

We haven’t been able to find the proper dependencies for the `deconz-gui` service to prevent this, but using a timer to  delay starting the service works, see #1535.

**Comment by Mikha495** [comment]
Ok, but deconz-gui is disabled in my setup. Is what you are writing also valid for deconz (headless)?

**Comment by ebaauw** [comment]
I don’t run headless, but I don’t think so.  You should be able see in the syslog.

**Comment by zladukas** [comment]
@Mikha, 
I'm using 3minutes timer for homebridge, just try and You'll see.

**Comment by Nastras** [comment]
@Mikha495 You can set it headless exactly as described in #1535 only that the service is not called deconz-gui.service but is it only deconz.service

By the way. Despite the delay of the service I often had the case that he didn't recognize the conbee stick and the firmware update screen appeared.

I also created a systemd timer which performs a soft reset (sudo GCFFlasher_internal -r) of the conbee shortly after boot. Now it is 100% reliable when recognizing the conbee.

Here my timer and the service as someone would like to use it:

sudo nano /etc/systemd/system/deconz-conbee-reset.timer
`[Unit]
Description=deconz-conbee-reset.timer

[Timer]
OnBootSec=20
Unit=deconz-conbee-reset.service

[Install]
WantedBy=timers.target	
`

then create the service with:
sudo nano /etc/systemd/system/deconz-conbee-reset.service

`[Unit]
Description=deconz-conbee-reset.service
Wants=network.target

[Service]
Type=oneshot
User=dannypiper
ExecStart=/usr/bin/sudo GCFFlasher_internal -r

[Install]
WantedBy=multi-user.target`

now activate the timer with :
sudo systemctl enable deconz-conbee-reset.timer

**Comment by Mikha495** [comment]
@Nastras thank you! Set up the timer for deconz.service.

Regarding the second timer (sudo GCFFlasher_internal -r):
Do I have first to disable the deconz.timer by `sudo systemctl diable deconz-gui.timer`? Or do both timers run parallel?

**Comment by Nastras** [comment]
Both timers run in parallel. Both timers start once after a reboot.

The deconz-conbee-reset.timer starts a command which performs a soft reset on the conbee. The deconz-gui.timer starts the service deconz-gui. This service will be active as long as deconz is running.

Both timers are in standby after execution until the boot event occurs again.

**Comment by Mikha495** [comment]
So today I unplugged my Raspberry in order to do a backup. After restarting, I receive following error:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/53826518/64018430-acd2b380-cb2c-11e9-8bc4-443883ec8e8a.png">
Already disabled both timers, enabled decent.service, restarted everything, re-installed the Homebridge.hue plug-in. Nothing helps. Somehow the REST-API cannot connect. Phoscon is is running well and displays all connected devices. 
How can I solve this?

**Comment by Mikha495** [comment]
Ok, this was strange.
Have ran the  GET request to https://dresden-light.appspot.com/discover in the REST plug-in for Firefox and it showed me the Phoscon-GW is now running on a different port, than before. I included the new port to the "host" in the Homebridge-hue entry of the config.json and now it runs. 

Maybe I should now reactivate the timers... but what would prevent the change of the ports? Any setting in my router? Don't think it's possible to set a fixed port for a service, isn't it?

**Comment by ebaauw** [comment]
The ports are specified as command line parameters when starting deCONZ.  If you hard-code these in `deconz.service` or `deconz-gui.service`, they will be overwritten with each deCONZ upgrade.  You need to use an override instead.

I use `/etc/systemd/system/deconz-gui.service.d/override.conf`:
```
[Service]
EnvironmentFile=/etc/default/deconz
ExecStart=
ExecStart=/usr/bin/deCONZ $DECONZ_OPTS
```
And then specify the options in `/etc/defaults/deconz`:
```
# DECONZ_OPTS="--http-port=80 --upnp=0 --dbg-info=2 --dbg-aps=2 --dbg-zcl=1 --dbg-zdp=1 --dbg-http=1 --dbg-error=1"

DECONZ_OPTS="--http-port=80 --dbg-info=2 --dbg-aps=2 --dbg-error=1"
```
