### ISSUE TITLE
Add support for Samsung Door/Window sensor

### ISSUE THREAD

**Issue by srg74** [dresden-elektronik/deconz-rest-plugin#1737]
Please add proper support for Samsung (Samjin) door/window sensor. This devise is very common in US. Thank you.
<img width="840" alt="Screen Shot 2019-08-06 at 4 43 08 PM" src="https://user-images.githubusercontent.com/28492985/62575964-dec46300-b869-11e9-8c4d-ecdb82afaf69.png">
<img width="597" alt="Screen Shot 2019-08-06 at 4 44 49 PM" src="https://user-images.githubusercontent.com/28492985/62576072-17fcd300-b86a-11e9-93e7-26b354b1bf25.png">

**Comment by hellcry37** [comment]
up

**Comment by hellcry37** [comment]
this is added but vibration sensor still not working as it should

**Comment by srg74** [comment]
Now it's working more stable.
