### ISSUE TITLE
Deconz in Home Assistant - Password at first login

### ISSUE THREAD

**Issue by andyjsawyer** [dresden-elektronik/deconz-rest-plugin#1749]
I have recently installed the Deconz addon under Hassio and when access the gateway for the first time is it asking me for a password. The issue is I haven't set one and returning it to default (delight) is not working either.

![deconz-gateway-login](https://user-images.githubusercontent.com/9380879/62963022-0d0cea00-bdf8-11e9-95ce-4b7fc8e42ec2.png)

Also created issue https://github.com/home-assistant/hassio-addons/issues/658

**Comment by Smanar** [comment]
And if you use "Lost password" ?

**Comment by andyjsawyer** [comment]
Lost Password returns it to default and that is supposed to be delight and that doesn't work.

**Comment by andyjsawyer** [comment]
Just Solved it by opening in a new browser (icognito)
