### ISSUE TITLE
Contact sensor not available at rule list

### ISSUE THREAD

**Issue by alex2000-ha** [dresden-elektronik/deconz-rest-plugin#1755]
Hi
I connected sucessfully the aquara window/ door sensor. At phonscon sensors, they are shown as Xiaomi Sensor, open/close status is working. 
![Screenshot_20190816-082652_Chrome](https://user-images.githubusercontent.com/54167169/63148049-49129b80-c000-11e9-85da-31ced587611f.jpg)

But I can not add them to the sensor control rule, because thy are not visible there.
![Screenshot_20190816-082741_Chrome](https://user-images.githubusercontent.com/54167169/63148072-5596f400-c000-11e9-8cf3-be74585c7bf7.jpg)

Does anyone know how I can add them there?

thx

**Comment by salopette** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1717

**Comment by alex2000-ha** [comment]
firmware 2.05.69 ... no contact senor @rule list :(

**Comment by mgrn0** [comment]
could this please be re-evaluated? it would really make sense for some people to have e.g. door sensors in rules.

**Comment by Proche72** [comment]
Hi, is there any development on this?

**Comment by SwoopX** [comment]
That is a question to be raised at the Phoscon repository, not here.

**Comment by mgrn0** [comment]
@SwoopX I am confused since there was a lot discussion about this specific topic here, and not in the Phoscon repository. Can you point us in the right direction or should we open an identical issue there? is https://github.com/dresden-elektronik/phoscon-app-beta/issues the right place?

**Comment by SwoopX** [comment]
Yes, the link you mention is the right place. DE has just recently re-opened the repo to keep the topics seperated.

**Comment by mgrn0** [comment]
thanks @SwoopX , opened an issue there. (@Proche72 - you might want to jump in ;)

**Comment by SwoopX** [comment]
Nope, since this is nothing I can help with :wink:
