### ISSUE TITLE
deCONZ randomly thinks some lights are on. But they are not.

### ISSUE THREAD

**Issue by ACrazyConcept** [dresden-elektronik/deconz-rest-plugin#1759]
Lately some of my lights and plugs randomly appear as turned on even though they are not.
I can turn them off and on just fine from deconz groups and home assistant and then they will appear with the correct state.

RPI 3B
RaspBee
Version: 2.05.66
Firmware: 26330500

**Comment by Smanar** [comment]
Hello, do you have the ikea motion sensor ?

**Comment by ACrazyConcept** [comment]
I have recently added the new IP44 IKEA motion sensor. That is the only one.

**Comment by Smanar** [comment]
Take a look here > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1676
