### ISSUE TITLE
Can create 2 sensors with same UniqueId using Phoscon.

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#1760]
Hello, so easy to reproduce
In Phosocon
1 - select a group
2 - Edit / switch editor
3 - Select a Xiaomi switch with double key
4 - Set "Toggle" fonction to right button
5 - Set "Toggle" fonction to left button

Sensor 26
> 
> config |  
> -- | --
> on | true
> reachable | true
> etag | "503d3ad81bb5a267cec21124ba436720"
> manufacturername | "Phoscon"
> modelid | "PHOSCON_FSM_FLAG"
> name | "CLIP-Sensor TOOGLE-ON-OFF"
> state |  
> flag | true
> lastupdated | "2019-08-18T14:40:11"
> swversion | "1.0"
> type | "CLIPGenericFlag"
> uniqueid | "00:15:8d:00:02:13:17:a8-01-0006-toogle-on-off"

Sensor 27
> config |  
> -- | --
> on | true
> reachable | true
> etag | "39d5f002ace51429217e75424eff13bb"
> manufacturername | "Phoscon"
> modelid | "PHOSCON_FSM_FLAG"
> name | "CLIP-Sensor TOOGLE-ON-OFF"
> state |  
> flag | true
> lastupdated | "2019-08-18T14:40:13"
> swversion | "1.0"
> type | "CLIPGenericFlag"
> uniqueid | "00:15:8d:00:02:13:17:a8-01-0006-toogle-on-off"

**Comment by Zehir** [comment]
If anyone came here one day, this issue is fixed because now phoscon use rules instead of CLIP.
