### ISSUE TITLE
deCONZ sometimes change my localtime to UTC

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-rest-plugin#177]
Sometimes, if i work with the Webapp, deCONZ change my time to UTC. After restart from the Raspberry Pi 3 the time is right again.

**Comment by Kohle81** [comment]
Hello, I have this problem too!

**Comment by manup** [comment]
I can confirm this, will be fixed in the next releases.

**Comment by Krocko** [comment]
Good morning Manuel.
It only happens, if you are on the settings page from the web app.
