### ISSUE TITLE
Start Phoscon Backup option via Terminal ?

### ISSUE THREAD

**Issue by Nastras** [dresden-elektronik/deconz-rest-plugin#1778]
I would like to have a systemd timer and service to automatically create a backup of deCONZ every 24 hours.

Is it possible to start the backup option in phoscon from the command line?

If no where u what does everything have to be backed up ?

Is this folder enough?
 ~/.local/share/dresden-elektronik 

Thanks!

**Comment by ebaauw** [comment]
Not directly, but it’s an API call, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1307, so you can use `curl` or `ph` from the command line.

**Comment by Nastras** [comment]
Erik, what would we do without you?

Thanks again for the super fast help 😘!
