### ISSUE TITLE
How can a switch be removed from a group?

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#1779]
I cannot find a button in phoscon to remove a switch from a group:

![image](https://user-images.githubusercontent.com/10351272/63654092-0aa27c80-c776-11e9-92a8-797519e5b819.png)

**Comment by Smanar** [comment]
I have make tries on my side, and if I select the switch I have "delete key asssignement" that appear on the right top corner.

**Comment by jo-me** [comment]
Yes, I can remove the key assignment but I cannot remove the switch altogether (so that it disappears from the list on the left).

**Comment by Smanar** [comment]
On the left side ""Xiaomi_Bedroom"  ? It'a group name ? Try delete the group.

**Comment by jo-me** [comment]
No, the group has two remotes / switches assigned "xiaomi_bedroom" and "dimmschalter..." .
I can maintain the key assignments but I cannot remove the switches from the group once I added them to the list on the left.

**Comment by Smanar** [comment]
Lol, right, I have same problem too ^^.

I will try with API

**Comment by JackPoint** [comment]
- From the main page, select the group
- Click manage lights
- Remove lights from the left part of the page

**Comment by Smanar** [comment]
And this procedure remove the switch too ?

**Comment by JackPoint** [comment]
This is to remove it from a group, not completely remove it

**Comment by noerstad** [comment]
Delete all key assignments, then go to the group setting. The switch automagically dissapears when you have no key assignments.
NOTE: I also removed one light from the group, might be that forced the group to update
