### ISSUE TITLE
Duplicated "lastupdated" websocket arttribute on every IKEA switch/sensor event 

### ISSUE THREAD

**Issue by mariusmotea** [dresden-elektronik/deconz-rest-plugin#178]
Hi,

I start to implement the zigbee module on my Hue Bridge emulator and one issue that i saw is that deconz send two records for every sensor or switch action on websocket. First is the correct one and contain all needed details, second one contain again the "lastupdated" attribute. This cause the processing of the rules on my hue bridge two times and in case of the IKEA remote the on/off button is pressed twice if i don't implement a lock mechanism.

example motion sensor:
```
{"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2017-09-07T08:06:36","presence":true},"t":"event"}
{"e":"changed","id":"3","r":"sensors","state":{"lastupdated":"2017-09-07T08:06:36"},"t":"event"}
```
example remote:
```
{"e":"changed","id":"1","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2017-09-07T08:19:50"},"t":"event"}
{"e":"changed","id":"1","r":"sensors","state":{"lastupdated":"2017-09-07T08:19:50"},"t":"event"}
```

**Comment by ebaauw** [comment]
This is an issue with 2.04.75, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/98#issuecomment-327583606.
