### ISSUE TITLE
"Toggle" action does not work properly

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#1780]
I have a Xiaomi switch with 2 buttons configured to each toggle a Osram Smart Plug. Switch and plug are in the same group.

Now, when I press each button repeatedly, the plug turns on/off as it should.

However, when alternating between the 2 buttons (with reasonable delay of 1-2s ), frequently nothing happens. It looks like Deconz is getting confused about which action to take and turns on the plug twice instead of toggling its state. 
So I get the impression that the "next" state is not based on the actual state of the plug but on the state it had after last pressing the same button.

Can you confirm that this is a bug?

It could be related to another issue (#1181) where the first button press is ignored.

**Comment by manup** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_67

The issue is fixed in 2.05.67, but you need to update or re-create the switch button assignment.

**Comment by jo-me** [comment]
Seems to work fine after the update :) 
Thank you!

**Comment by LJSven** [comment]
What does it mean? What to do?

„update or re-create the switch“

**Comment by manup** [comment]
You need to edit the related switch assignment in the Phoscon App switch editor.
Easiest way:
* Change toggle to "turn on"
* "turn on" to toggle again
* Press the Save button

That way the related rules will be rewritten and corrected.

**Comment by LJSven** [comment]
Is it also necessary, if i´m using it for ioBroker? I don´t want to control the lights / scenes in the Phoscon app.

**Comment by manup** [comment]
The issue is only related to the switches which are configured via Phoscon App switch editor.
