### ISSUE TITLE
[Feature] "advanced" zigbee API

### ISSUE THREAD

**Issue by Equidamoid** [dresden-elektronik/deconz-rest-plugin#1797]
Just as an idea, how about adding more low-level API closer to the actual zigbee messages?

For example I'd like to send `OnWithTimedOff` message so I'll be sure the device will turn off even in case of some zigbee connectivity problem or even a nicely timed cat bite to some wires.

**Comment by Kane610** [comment]
Being able to send this similar to bri_inc would be nice. Why keep timers in automations when the light can keep it self

**Comment by ebaauw** [comment]
I appreciate the call for a “raw” API, closer to ZigBee, see #1688.

Last January, I already implemented _On with Timed Off_ through `state.ontime`, see https://github.com/dresden-elektronik/deconz-rest-plugin/commit/6ed48e272450beff7555a428ab5467d4da11b7a8.

**Comment by Equidamoid** [comment]
@ebaauw 
Oh, it's nice to hear that such idea also comes "from inside"!
Thanks for the `ontime` hint, that will do in the meantime
