### ISSUE TITLE
Question: what are the suitable API calls to turn on/off OSRAM Smart+ Plug ?

### ISSUE THREAD

**Issue by maxstein242** [dresden-elektronik/deconz-rest-plugin#1800]
Dear all,

in the REST API documentation I was not able to find the APIs for smart plugs (OSRAM Smart+ in my case), any advice on a workaround?

thanks and best regards,
Max

**Comment by Smanar** [comment]
Hello,
plugs use same API than bulb, so you can use exactly same.

**Comment by maxstein242** [comment]
Thanks a lot for your quick answer @Smanar  !
