### ISSUE TITLE
Samjin sensors vanished from Phoscon sensors tab

### ISSUE THREAD

**Issue by srg74** [dresden-elektronik/deconz-rest-plugin#1801]
Deconz 2.05.67 - Samjin Multipurpose Sensor and Samjin Water Sensor disappears from sensor listing in Phoscon but remain visible in VNC. Is that a feature or a bug?

**Comment by hellcry37** [comment]
Sensor in question is Samsung GP-U999SJVLAEA SmartThings Multipurpose and it used to work partially on deconz firmware 2.05.66
- behave 2.05.66: sensor could be paired and used for open/close and temperature (vibration did not work well, vibration sensor detected every ~ 1h)
- behave 2.05.67: when you pair the sensor apparently successfully you can't see the paired sensor in Phoscon app after pairing. sensor will appear with no name or "multi" name in VNC but not usable.

Note: can not delete sensors in vnc at all, all deleted sensors under VNC interface reappear

**Comment by manup** [comment]
In my home setup I have the water sensor which is still visible and working in the Phoscon App with 2.05.67.

I'll need to test the multipurpose sensor and also if joining them freshly still works. Since there were no related changes in the Phoscon App I figure it might be an issue in the REST-API.

**Comment by hellcry37** [comment]
> 
> 
> In my home setup I have the water sensor which is still visible and working in the Phoscon App with 2.05.67.
> 
> I'll need to test the multipurpose sensor and also if joining them freshly still works. Since there were no related changes in the Phoscon App I figure it might be an issue in the REST-API.

thank you

**Comment by manup** [comment]
I've tested the multipurpose sensor and it works in my setup. The formerly created resources worked and were shown in the Phoscon App as well as deleting the sensor and rejoining it worked.

The test was done with deCONZ 2.05.69 but there were no changes related to the sensor since 2.05.67.

**Comment by hellcry37** [comment]
for me latest update offered by deconz addon is 2.05.67, still, waiting for update, thanks for testing this

**Comment by hellcry37** [comment]
I'll test after update and get back with a report

**Comment by hellcry37** [comment]
Like promise I got back with a report about "Samsung GP-U999SJVLAEA SmartThings Multipurpose" sensor.
Sensor is idd working again on deCONZ 2.05.69. If the vibration trigger ~ 1h still occurs i will open a new ticket.

@manup Thank you very much for your help and tests, much appreciated.

**Comment by marcelodavanzo** [comment]
> Like promised I got back with a report about "Samsung GP-U999SJVLAEA SmartThings Multipurpose" sensor.
> Sensor is idd working again on deCONZ 2.05.69. If the vibration trigger ~ 1h still occurs I will open a new ticket.
> 
> @manup Thank you very much for your help and tests, much appreciated.
> 
> SOLVED

Have you managed to fix the issue with the vibration triggering every 1h? I'm on 2.05.69 and have this same issue.

**Comment by hellcry37** [comment]
opened this for it: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1848

**Comment by hellcry37** [comment]
#1848 failed

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue.
