### ISSUE TITLE
Update - notification and auto install

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#1805]
would be great to have an option to autoupdate Deconz and/or alert us (email, text, pushover, etc) of the update being available, with changelog link.

**Comment by ragzilla** [comment]
Are you installing via source (or windows binaries), or Linux package?

If you're using source/windows binary releases, on the main repo page you can use the dropdown on Watch to select 'Releases Only' to get an email when they tag a new release.  

If you're using Debian/Raspbian/Ubuntu, use [apticron](https://debian-administration.org/article/491/Automatic_package_update_nagging_with_apticron).
