### ISSUE TITLE
Is there a node js package for handling deconz APIs and websocket events?

### ISSUE THREAD

**Issue by maxstein242** [dresden-elektronik/deconz-rest-plugin#1810]
Dear all,

Is there a node js package for handling deconz APIs and websocket events available?
My research on npm did not result in any success , so I try my luck here in the community.

Thanks and best regards,
Max

**Comment by ebaauw** [comment]
[homebridge-hue](https://github.com/ebaauw/homebridge-hue) is written for NodeJS.  The `HueCLient` module handles the interaction with the API.  The `ph` command builds on this, providing a command-line interface to the API. The `dc_eventlog` command logs web socket notifications.

**Comment by maxstein242** [comment]
Thank you very much @ebaauw !
