### ISSUE TITLE
Conbee 2, ikea motion sensor and led bulb

### ISSUE THREAD

**Issue by xavax59** [dresden-elektronik/deconz-rest-plugin#1819]
Hi,

I've got a Conbee key 2, a smart plug Ikea tradfri and a motion detector sensor Ikea tradfri.

In the phoscon app, I created a group to turn on the light when it's dark. Sometimes it works and sometimes not. Phoscon often indicates that the light is on but she is not.

And the plug (which isn't in the group) also indicates that it's on though it's clearly off.

What can I do? 

Thanks

Screenshots
https://www.dropbox.com/sh/24o0hezqxfaqdhm/AAAS-mieafmMoDIndXZOkS1Ra?dl=0

**Comment by Smanar** [comment]
Hello, I think it's "normal", there is lot of issue ATM because of the ikea motion sensor.
And It seem the correction wasn't on the last version 02.05.67

You can find some informations here > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1676
