### ISSUE TITLE
IPv6 and HTTPS: support is fully required

### ISSUE THREAD

**Issue by flechaig** [dresden-elektronik/deconz-rest-plugin#1820]
So we are in 2019 and IPv6 is still not supported.
The better I could get is to start the REST API on an IPv6 with the listen=:: stanza in config.ini.
But the websocket still remains in IPv4.

All this lacks HTTPS suppport, and there is no way of setting things up the right way with nginx as a reverse-proxy.

**Comment by jose-d** [comment]
> no way of setting things up the right way with nginx as a reverse-proxy.

What's blocking us from using nginx?
Actually, this is a good point, use nginx + letsencrypt could be nice and cheap way to https..
