### ISSUE TITLE
Innr bulbs losing connection and then reconnect. 

### ISSUE THREAD

**Issue by vandalon** [dresden-elektronik/deconz-rest-plugin#1829]
Hi,

I'm not sure if this is deconz issue or a innr issue but here we go:

I have 2 innr bulps who seem to keep disconnecting and reconnecting after a while again.
While looking in deconz I see them disconnecting, all links towards other lights are dropped and then start building up again. Also I see the red "linkled" in deconz blinking red now and then when it's not working. Can I do more to debug this issue?

**Comment by petosak** [comment]
I have same problem with innr RF 263.

**Comment by HennigStein** [comment]
Hi, i have the same problem.
i have new deconz, iobroker and the innr comfort with 420 lm.

i lose the conection.
