### ISSUE TITLE
Is there a was to Update Osram Ledvance Downlights TW?

### ISSUE THREAD

**Issue by lons81** [dresden-elektronik/deconz-rest-plugin#1833]
Hello

How can i Update my Ledvance Downlights 25W to a newer Firmware?
In every Switch on the go to cold white with 100% and dont remember the last state.

Thanks, Marcel

**Comment by ebaauw** [comment]
> How can i Update my Ledvance Downlights 25W to a newer Firmware?

Afaik OSRAM/Ledvance haven't published their firmware, so I'm afraid the only answer is: through their gateway.

> In every Switch on the go to cold white with 100% and dont remember the last state.

Unlike Hue, OSRAM use a manufacturer-specific cluster for the power-on settings, see #102.  They have been for as long as I remember (over several years), so I doubt you'd actually need a firmware update for this functionality.

Unlikely that REST API will support this anytime soon, but the `general.xml` from the above commit adds support to the deCONZ GUI:
![Screenshot 2019-09-08 at 14 57](https://user-images.githubusercontent.com/22179355/64488545-79d5a180-d249-11e9-93a1-fa97791dde6c.png)

Copy `general.xml` to `/usr/share/deCONZ/zcl` and restart deCONZ.  You should then see the updates in the GUI.  Set the bulbs brightness and colour temperature to the desired values and press the button to store them as new power-on defaults.  I don't think they support powering-on the lights as off.  Their app used to demand a minimal brightness, but I don't think their lights actually enforce this.

I have only tested this on an OSRAM Classic B40 TW - LIGHTIFY with firmware V1.05.10.

**Comment by lrybak** [comment]
Hi Eric (@ebaauw),
I've copy the general.xml file to the /usr/share/deCONZ/zcl but see no change in GUI. Still no power-on Defaults option. Any hint?

![image](https://user-images.githubusercontent.com/5631648/70148168-f0960580-16a5-11ea-93da-26c84bc0b049.png)

**Comment by ebaauw** [comment]
You need to select the 0xfc0f cluster.

**Comment by lrybak** [comment]
Where it is?

**Comment by lrybak** [comment]
Forgive me, I was blind. Now I found it, thx.

**Comment by 7wells** [comment]
Please consider also this post over there:
https://github.com/dresden-elektronik/phoscon-app-beta/issues/213#issuecomment-701205883
