### ISSUE TITLE
REST API plugin compilation

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#1838]
I see you managed to get rid of all warning messages when compiling the REST API plugin.  Kudos!

When I compile the plugin on my Raspberry Pi 4B, I cannot run it on my Pi 3B+ machines.  Is that due to different processors (BCM2711 vs BCM2837) or different versions of Raspbian (buster vs stretch)?  It runs fine on the 3B+ when compiled on the same type of machine.

Pi 3B+:
```
$ uname -a
Linux pi1 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
$ apt list deconz deconz-dev
Listing... Done
deconz/unknown,now 2.05.69-raspbian-stretch-beta armhf [installed]
deconz-dev/unknown,now 2.05.69-raspbian-stretch-beta armhf [installed]
```
Pi 4B:
```
$ uname -a
Linux pi5 4.19.66-v7l+ #1253 SMP Thu Aug 15 12:02:08 BST 2019 armv7l GNU/Linux
$ apt list deconz deconz-dev
Listing... Done
deconz-dev/unknown,now 2.05.69-raspbian-buster-beta armhf [installed]
deconz/unknown,now 2.05.69-raspbian-buster-beta armhf [installed]
```

**Comment by manup** [comment]
It's still a up-hill battle :) depending on the platform and compiler/qt version we still see many warnings. 

To get the greatest compatibility it's recommended to compile on the oldest Raspberry Pi which is to be supported. Same goes the the Raspbian version. So I guess when you compile on the Pi 3B+ on stretch it should also run on Pi 4B.

Our build server, which is a Ubuntu VM, does cross-compile for Raspbian Jessie, Stretch and buster emulating a Raspberry Pi 1 (we use balenalib Docker images with qemu emulator for ARM).
