### ISSUE TITLE
Xiaomi Magic Cube not showing up in Switch Editor

### ISSUE THREAD

**Issue by andjandre** [dresden-elektronik/deconz-rest-plugin#1846]
I updated to the latest snapshot but my Magic Cube isn't showing up in the Switch Editor. I restarted DeconZ and Phoscon and repared my Magic Cube a couple times but it still isn't appearing in Switch Editor. I can still use it within Homekit with Homebridge. Odd thing is that I cannot pair it within the "Add Switch" dialogue but with the "Add Sensor" functionality. It then is pairing successful and showing up within switches.

Looking forward for your help because i was really looking forward for this feature.

**Comment by wilfredsmit** [comment]
I second that, although I have a Xiaomi Mi Magic Cube. And I also misses the 'analog'/rotation sensor in the REST Api.

**Comment by wilfredsmit** [comment]
I've managed to get my Mi Magic Cube in the Switch Editor. I tried to search for the sensor a second time: Add new switch and push the reset button on the cube for two to five seconds (blue led on). In the mean time move and rotate the cube. In the REST api I know see two sensors: sensors/42 (flip, etc.) and sensors/46 (rotate).

**Comment by KennethLavrsen** [comment]
I have added the Magic Cube 5 times now and hammered rotated moved. It shows up. But how am I supposed to get a Switch Editor to show? What is the user interface?

**Comment by Smanar** [comment]
Hello,
Home page > select a group > edit > switch editor.

https://www.phoscon.de/en/app/doc

**Comment by KennethLavrsen** [comment]
Thanks @Smanar - I had never found that without your help
