### ISSUE TITLE
Support for new IKEA GU10

### ISSUE THREAD

**Issue by JanLp** [dresden-elektronik/deconz-rest-plugin#1860]
Is it possible to add support for the new LED bulb from IKEA (IKEA LED1837R5) [https://ikeacy.azureedge.net/files/Buying_guides/HFB10/en/Smart_lighting_buying_guide_AUG19CY_en.pdf](url)
Thanks in advance.

**Comment by Kane610** [comment]
Go to the wiki and follow the guide on how to request support for new devices

**Comment by JanLp** [comment]
> Go to the wiki and follow the guide on how to request support for new devices

I don't know how to do it. I use a Conbee 2 with Hass.io and add my devices via Phoscon

**Comment by manup** [comment]
We haven't yet tested this particular downlight but usually all IKEA lights should work out of the box. Have you tried to reset the light with the IKEA reset sequence before joining?

https://phoscon.de/en/support#faq-ikea1
