### ISSUE TITLE
phoscon breaks schedules from WLC

### ISSUE THREAD

**Issue by jose-d** [dresden-elektronik/deconz-rest-plugin#1867]
When there is "on" schedule, Phoscon app will break it and change "group ON" to "group OFF" when touching schedule config there in PWA.

## Reproducible on:

**pwa** 2.05.69 / 6.9.2019
**fw** 264 907 00

Conbee II + Raspberry Pi4

### 1) create schedule in Wireles Light Control (WLC) web:

![01_wlc_schedule_overview](https://user-images.githubusercontent.com/7630424/64920961-a6e00200-d7bd-11e9-8dc3-04b01efb9fec.png)

detail of the Group **ON** schedule:

![01_schedule_detail](https://user-images.githubusercontent.com/7630424/64920975-d858cd80-d7bd-11e9-8ce0-1d210075398b.png)

### 2) go to the Phoscon web GUI, schedule is still there:

![02_pwa_schedule_still_present](https://user-images.githubusercontent.com/7630424/64921011-1a820f00-d7be-11e9-928d-7d34695db9f9.png)

**3) click on the "ON" action - it will disappear and schedule is automatically saved**

(and there is no way how to add the action again here)

![03_pwa_on_schedule_disappeared](https://user-images.githubusercontent.com/7630424/64921049-6765e580-d7be-11e9-858a-36119ac56738.png)

### 4) go back to WLC - the "Group **ON**" schedule changed to "Group **OFF**"

![04_schedule_changed_to_off](https://user-images.githubusercontent.com/7630424/64921075-c3306e80-d7be-11e9-9d1d-be9f0f6ce77e.png)

## expected behavior:

Phoscon is not breaking schedules from WLC or schedules planning is implemented in PWA.

**Comment by manup** [comment]
Interesting, I've put it on our check list. I guess this might be related to a prior decision to favour scenes over "on" or "brightness" settings for a schedule in the Phoscon App, since scenes are more fine grained and allow setting the state for each light individually.

So we have a few choices to improve the issue:

1. Treat WLC schedules or any schedules which are not created with the Phoscon App as readonly, perhaps with a small hint why they are readonly
2. Add the functionally provided by WLC to the Phoscon App
3. Don't show non Phoscon App schedules at all

**Comment by jose-d** [comment]
>  to favour scenes over "on" or "brightness" settings for a schedule in the Phoscon App

ah, thanks, ok, this was quite unobvious for me - as I had no scenes for WC fan, I thought the schedule support is simply not yet implemented there in PWA - that was the reason why I used WLC.

So for my usecase it's enough to create scene fan_on and fan_off.

Perhaps some hint that one needs to add scene at the "Schedules of group"  (http://192.168.1.208/pwa/group-time.html) could be added.

**Comment by manup** [comment]
>Perhaps some hint that one needs to add scene at the "Schedules of group" (http://192.168.1.208/pwa/group-time.html) could be added.

Indeed we should make this more clear, the page looks way too empty when no scenes are defined for a group.

https://phoscon.de/en/app/doc#group-schedules-en
