### ISSUE TITLE
All Lamps are displayed as on, when i use a Ikea motion detector 

### ISSUE THREAD

**Issue by daendaen** [dresden-elektronik/deconz-rest-plugin#1869]
Hi,

when i use the ikea motion detector, after a recognized movement all lamps are on in the app "phoscon". 
But the lamps are off, in reality. 

I use the stick in a docker container on a ubuntu. The stick an all devices run good. The problem comes only, when i use the ikea tradrfi motion detector.

I delete the motion dector from the conbee stick many times, but the probem is still there.

Need help :)

Greetings

**Comment by ebaauw** [comment]
See #1676

**Comment by daendaen** [comment]
thx
