### ISSUE TITLE
IKEA blinds closed logic reversed

### ISSUE THREAD

**Issue by DarkFox** [dresden-elektronik/deconz-rest-plugin#1870]
It seems like, as a possible artifact of the reversing logic being removed, the state of the blind is reported as `closed` whenever it's anything but at 100% open (fully retracted). It seems to me (and going by [this fix to a HA lovelace card](https://github.com/thomasloven/lovelace-slider-entity-row/commit/77eedac4ad27aa1383e41d7e54d620382a82516e)), it should be the opposite, and it should only report `closed` when it is at 0% (fully extended).

_Originally posted by @DarkFox in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1121#issuecomment-531503873_

**Comment by eggman0131** [comment]
I have the same issue, not sure if it's a problem with deconz or the ha integration?
