### ISSUE TITLE
Deconz in docker on Ubuntu doesn't show correct status of lights, switches etc

### ISSUE THREAD

**Issue by 4ndersjensen** [dresden-elektronik/deconz-rest-plugin#1872]
I installed Hassio in Docker on Ubuntu on an Intel NUC
I the installed deconz from hassio but lights, switches etc. doesn't report correct status.
I have a group, i.e. Kid1, which includes 2 Philips Hue lights and an IKEA Trådfri wallplug.
The Kid1 group is alway on, even though when checking the lights they are off, but the switch seems to be on, though it isn't. When clicking the switch the icon changes to off and clicking it again turns it on AND the switch correctly turns on as well.
Is this a known issue?

**Comment by denwald** [comment]
I have the same problem with one newly bought Trådfri bulb (1000 lm). When my pi comes online after a reboot one of the bulbs shows as on in home assistant, while it's actually off (but online). In  Phoscon the same bulb has the correct state (off). To resolve the issue I have to use the Phoscon webapp to turn the bulb on and off again. After that the state will propagate to home assistant.

Strangely two identical IKEA Trådfri bulbs don't have the problem.
