### ISSUE TITLE
Orvibo smoke sensor SF21

### ISSUE THREAD

**Issue by mn26826** [dresden-elektronik/deconz-rest-plugin#1875]
It would be great if someone could add support for the SF21 smoke sensor by Orvibo. The SF20 is already supported, so maybe it's an easy job? I don't know ;)

Here are two screenshots:

![sf21_nodeinfo](https://user-images.githubusercontent.com/1651699/64976384-682b7400-d8b1-11e9-9140-e31c29478777.png)

![sf21_cluster](https://user-images.githubusercontent.com/1651699/64976394-7083af00-d8b1-11e9-9b1c-f6e5a6f6274b.png)

Thanks in advance. Really appriciate it.

**Comment by udoewich** [comment]
@mn26826 can you please copy (i.e. select the value field and use Ctrl+C) the complete Model Identifier and post it here?  I believe it's missing the last four digits in your screenshot.

**Comment by mn26826** [comment]
@udoewich the complete Model ID is 98293058552c49f38ad0748541ee96ba.

**Comment by BeamMeUpTo** [comment]
Tried to connect an Orvibo SF21 with Phoscon App but it seems not to recognize him...
get sensors/lights shows nothing, too.

But in deCONZ (Raspbee Version 2.05.69 26330500) it is visible - with the same Model-ID!

Is there some kind of trick? First Resetted the sensor --> press 5 seconds Connect-Button.
For connecting it I started phoscon --> connect new sensor --> Press 2 sec Connect-Button! 

But no new sensor :(

Any hints for me? Please...
Thanks

![Orvibo-SF21-Node-Basic](https://user-images.githubusercontent.com/45270879/68084440-c39bcc00-fe35-11e9-874a-f352e3bf89ee.png)

![IAS-Zone-Cluster](https://user-images.githubusercontent.com/45270879/68084443-c7c7e980-fe35-11e9-830c-ca75a133231d.png)

![Orvibo-SF21-Node-Basic-Model](https://user-images.githubusercontent.com/45270879/68084445-ce566100-fe35-11e9-9ad5-805916552cdc.png)

**Comment by udoewich** [comment]
@BeamMeUpTo support has been added, but it's not in .69 - it should be part of the next release (.70 presumably?).

**Comment by BeamMeUpTo** [comment]
Deleted the node in deconz. Resetted the sensor.
Upgraded to .../raspbian/beta/deconz-2.05.70-qt5.deb
Phoscon --> New Sensor.... Nothing :(

But visible in deconz again - no phoscon/REST-API (get sensors/lights) recognition...
Still wrong version? No yet comitted?

Thanks for the help

**Comment by udoewich** [comment]
I'm not sure, as .70 hasn't released officially yet (not listed under releases).  Someone else would have to chime in as to how a smoke sensor would show up in Phoscon, as I don't have any sensors of that kind in my setup.

I assume @mn26826 hasn't been able to test the integration yet either?

**Comment by BeamMeUpTo** [comment]
I'm now on V2_05_71

Deleted the old node in deconz. Resetted the sensor.
Phoscon --> New Sensor.... Nothing :(

But visible in deconz again - no phoscon/REST-API (get sensors/lights) recognition...

Same question? Still wrong version? Not yet comitted?
Can I do something to help accelerate the development?

Thanks Beam

**Comment by udoewich** [comment]
I checked just now: the support for both SF20 and SF21 is in the source code since .70.

Again, since I don't have one of these, I can't be 100% sure it's properly supported.

I suggest the follow procedure:

2) reset the device, to get rid of any old pairing info
3) once the device shows up in deCONZ again, look at the Basic Cluster and make sure it shows the Model Identifier (might take a while to show up), since that is what Phoscon needs for proper identification
4) put your device in pairing mode and have it physically close to the ConBee/RaspBee
5) go the the Devices > Sensors page in Phoscon and use the "Add new sensor" button

That should normally do it.

**Comment by BeamMeUpTo** [comment]
Did it exactly your way... sensor shows up in deconz - then read the basic Cluster, while phoscon searches for new sensors - but did not find any. REST-API as well: get sensors - no new device is listed :(
Thats what deCONZ shows, after reading BASIC-Cluster while phoscon searches for new sensors
:
![Orvibo-SF21-mit-98xxxba](https://user-images.githubusercontent.com/45270879/69420089-47065a00-0d1e-11ea-98fe-f4d63602aa74.png)

**Comment by udoewich** [comment]
Your last screen shot does not show any active links to the device.  AFAIK, it will only communicate properly if it has at least one link.

Can you capture some of the deCONZ log messages?  Look for messages with the address of your device (0x000d6f0010dd0c6c).

@mn26826 is your SF21 working with .70 or .71?

**Comment by BeamMeUpTo** [comment]
Its my first deCONZ log! I have no clue if it is the right way - please help, if its the wrong way.

I tried to generate the log with: 

`deCONZ --dbg-info=1 --dbg-zdp=1 --dbg-zcl=1 --db-aps=1 --dbg-http=1 --dbg-error=1 > deCONZ.log`

but the connected Orvibo with id 0x000d6f0010dd0c6c never showed up in the log - but is connected, see new screenshot.

![Orvibo-connected-SF21-mit-98xxxba](https://user-images.githubusercontent.com/45270879/69477025-99f51580-0de1-11ea-95e2-9dfe1ca31a22.png)

**Comment by udoewich** [comment]
Sorry, looks like I missed that the SF21 uses a different vendor and MAC prefix compared to the SF20.  I just issued a pull request with the fix.

**Comment by BeamMeUpTo** [comment]
Hopefully fixed then ;) - in .72??
Feel free to ask me for some more tests... if the fix is committed in the next version. 

Thanks, Beam

**Comment by udoewich** [comment]
Hopefully, yes. :)  If all goes well, it should be part of the next release.

**Comment by BeamMeUpTo** [comment]
So, finally I got the SF21 working with deconz-2.05.72-qt5.deb.

Sensor shows up in deconz - then read the basic Cluster, while phoscon searches for new sensors! Phoscon detects the new sensor - ready ;) REST-API as well: get sensors output

40: SF21 smoke sensor OG.FL.Rauchmelder ZHAFire    

But phoscon itself shows no new device - is that right?
Thanks so far ;)

**Comment by udoewich** [comment]
Great, and thanks for the letting us know!

Sorry, but I have no experience with Zigbee alarm sensors in Phoscon, so don't know where they would show up (if at all).

**Comment by BeamMeUpTo** [comment]
Just for letting you know.... I ordered 2 more devices and all (now 3) got recognized ;)

**Comment by mkuutti** [comment]
Hi, is the SF21 supported or not Phoscon yet? BeamMeUpTo’s comment leaves me uncertain. As well as the fact that I'm getting the same behaviour as he did on 14 Dec, device is found by Phoscon but does not show up in the sensors list. I'm on 2.5.72.

**Comment by BeamMeUpTo** [comment]
They do not show up in Phoscon!!!
But you need the Phoscon "New Sensor Connect"-Button to pair the sensor. 
SF21 is accessed through REST-API ONLY!!! - which in my case is managed by "FHEM".

**Comment by mkuutti** [comment]
Right. I’ll use Home on my Apple devices. I hope Phoscon gets to support them at some point.

Thanks.

Mikko


On 16. Jan 2020, at 21.03, BeamMeUpTo <notifications@github.com> wrote:

﻿

They do not show up in Phoscon!!!
But you need the Phoscon "New Sensor Connect"-Button to pair the sensor.
SF21 is accessed through REST-API ONLY!!! - which in my case is managed by "FHEM".

**Comment by BeamMeUpTo** [comment]
Today, I received ten new "Schwaiger ZHS20" smoke sensors, which are totally the same as Orvibio SF20 and SF21 (perhaps only differences in model-id). 
Disadvantage of the Orvibos is the complicated pairing process - with paring while read-out the basic cluster. While the Schwaiger ones integrate fluently in Phoscon AND deCONZ with correct naming.

But PHOSCON is only recognizing the Schwaiger ones and none of the Orvibios! 
-> What makes the difference? 
-> Any additional information needed? 
-> Which? - I would try to provide! Talk to me ;)

RaspBee with 
deCONZ 
2.05.83 und 
Firm 
26350500

**Comment by Mimiix** [comment]
@BeamMeUpTo Request device support. Just open a new issue. They need to be whitelisted.

**Comment by Starsurfer78** [comment]
I have also the SF21 smoke sensor. After a fault Fire Alarm, the Senor show Fire = 1. (in FHEM)
Does anyone know how I can reset it?
Delet and repair did't change the status.

**Comment by SwoopX** [comment]
Can you please open a seperate issue for your experience? This is a device support request.
Especially the environment details requested there are important.
