### ISSUE TITLE
All the lights unresponsive

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#1876]
Hi, I started getting these logs, and most of my lights don't respond anymore, ideas?

```
deconz           | 21:08:18:294 0x90FD9FFFFE01C6A2 error APSDE-DATA.confirm: 0xA7 on task
deconz           | 21:08:24:944 0x90FD9FFFFE820117 error APSDE-DATA.confirm: 0xA7 on task
deconz           | 21:08:26:041 delay sending request 195 dt 2 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:141 delay sending request 195 dt 2 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:240 delay sending request 195 dt 2 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:341 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:441 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:540 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:641 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:740 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:840 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:26:940 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:040 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:140 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:241 delay sending request 195 dt 3 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:340 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:441 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:540 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:641 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:741 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:840 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:27:941 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:28:040 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:28:142 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:28:240 delay sending request 195 dt 4 ms to 0x90FD9FFFFE8294D2, cluster 0x0300
deconz           | 21:08:30:025 0x90FD9FFFFE8294D2 error APSDE-DATA.confirm: 0xA7 on task
deconz           | 21:08:33:522 0x90FD9FFFFE8294D2 error APSDE-DATA.confirm: 0xA7 on task
deconz           | 21:08:33:522 max transmit errors for node 0x90FD9FFFFE8294D2, last seen by neighbors 242 s
deconz           | 21:08:36:340 binding for cluster 0x0006 of 0x90FD9FFFFE820117 exists (verified by reporting)
deconz           | 21:08:37:765 discovery for zombie 0x000b57fffeefc2fd dropped, last try was 135 s ago
deconz           | 21:08:38:884 Current channel 25
deconz           | 21:08:38:905 Device TTL 968 s flags: 0x7
deconz           | 21:08:39:966 0x90FD9FFFFE901334 error APSDE-DATA.confirm: 0xA7 on task
deconz           | 21:08:43:046 max transmit errors for node 0x90FD9FFFFE01C6A2, last seen by neighbors 91 s
deconz           | 21:08:44:871 dev /dev/ttyAMA0
deconz           | 21:08:44:871 GW firmware version: 0x26330500
deconz           | 21:08:44:871 GW firmware version is up to date: 0x26330500
deconz           | 21:08:45:036 max transmit errors for node 0x90FD9FFFFE01C6A2, last seen by neighbors 93 s
deconz           | 21:08:46:106 max transmit errors for node 0x90FD9FFFFE01C6A2, last seen by neighbors 94 s
deconz           | 21:08:48:673 0x90FD9FFFFE792F0F error APSDE-DATA.confirm: 0xA7 on task
deconz           | 21:08:51:753 no button handler for: RWL021 ep: 0x02 cl: 0x0001 cmd: 0x0A pl[0]: 021
```

edit: now they work again... I'd like to understand what's going on

edit2: stopped working

**Comment by FezVrasta** [comment]
I'm on latest RaspBee firmware and latest DeCONZ software, running through Docker on a Raspberry Pi 4.

I already tried to change the channel to all of the available ones with no avail.

My wife hates me when lights stop working, help :-(

**Comment by FezVrasta** [comment]
I tried to plug off the power from the RPi and plug it back, still no luck

**Comment by FezVrasta** [comment]
It may be related to this:

https://github.com/marthoc/docker-deconz/issues/153#issuecomment-532163658

**Comment by sub0ne** [comment]
Same for me. I got Conbee 2 stick running with Pi 3b+ & Raspbian. I got two groups with several light in them. After several hours the light can not be accessed directly anymore. Via the groups the still can be turned on and of. But the individual lights can not be controlled anymore. This makes the whole thing useless.

**Comment by manup** [comment]
Can you please provide some details about which lights you are using, a screenshot from the *Phoscon App > Menu > Lights* would be useful.

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/65234604-2bd85d80-dad5-11e9-8867-b2443b379e8a.png)

now it marks "Cookers" as available, but actually it doesn't respond to any command.

**Comment by FezVrasta** [comment]
I also got some switches and they are unavailable too.

![image](https://user-images.githubusercontent.com/5382443/65234809-95f10280-dad5-11e9-8721-eaf3a0620a76.png)

**Comment by FezVrasta** [comment]
@manup what's the plan to address this issue? There are ton of people reporting the very same problem.

I've been 2 weeks without lights for now. What am I supposed to do?

**Comment by manup** [comment]
Big sorry for the delay. Can you please provide a screenshot from *Phoscon App > Menu > Settings > Gateway* or a log like in your first post.

I'd like to check if the RaspBee is still connected.

A screenshot from the Zigbee configuration page would also be helpful to see if the configuration has issues and was changed somehow.

The page is described in: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59

Do you have any other devices connected to your Raspberry Pi like USB disks?

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/65887380-21a04400-e39e-11e9-82f7-74656d8eb228.png)

I have an externally powered hard drive, but I tried to disconnect it and nothing changed. Also, it used to work just fine for over a week before the issue happened.

**Comment by manup** [comment]
Looks finde, since the firmware version is shown the connection is there.

Please also check the Zigbee configuration page:

>A screenshot from the Zigbee configuration page would also be helpful to see if the configuration has issues and was changed somehow.

>The page is described in: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59

Here the network parameters should indicate that they haven't changed recently.

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/65900697-e0685e00-e3b6-11e9-8534-ccf076ae1e94.png)

![image](https://user-images.githubusercontent.com/5382443/65900714-e78f6c00-e3b6-11e9-8505-b2b7263fe5d7.png)

**Comment by manup** [comment]
Looks fine too, I suppose the channel change from 15 to 25 was done a while ago?
I'm not sure what's causing the non responding devices.

So next step is to figure out if your lights are using the same parameters.

1. *Phoscon App > Menu > Help > Open Wireless Light Control (2016)*
2. *Old WebApp > Menu > Settings > Scan for Devices* (on the bottom of the page)

Hopefully that that should list a few nearby lights. In the list we can see if the same channel and PANID are used.

![image](https://user-images.githubusercontent.com/383386/65908049-e0238f00-e3c5-11e9-8a75-e20284581d29.png)

**Comment by FezVrasta** [comment]
It finds only 1 light, but I have at least 7 lights powered on at the moment.

![image](https://user-images.githubusercontent.com/5382443/65951730-f1f64800-e440-11e9-9b39-eda9cd5c5dca.png)

**Comment by manup** [comment]
>It finds only 1 light, but I have at least 7 lights powered on at the moment.
The scanner can only see lights which are rather close to the gateway.

>I changed the channel a few times when it stopped working to see if it helped with the issue.

Hmm, this is a danger zone (that's why we've put a big red warning to the channel change dialog).
So in worst case your devices are now scattered to multiple channels (which can be solved).

But first things first, can you position the gateway near to some other lights (or bring the lights to the gateway) and issue the "Scan for Devices" again. I really wonder that the light in your screenshot is not only on a different channel but also has a different PANID of 0x4326 instead of your gateways 0x3f1d.

**Comment by dxxxm** [comment]
Interesting.  No probs here. All fine. 62 Nodes. ~40 Lights
Just out of curiosity replayed the 'scan for Devices' instructions as given and get this:
![Screenshot_2019-10-02 Wireless Light Control - Settings](https://user-images.githubusercontent.com/7277625/66055610-7aa6de00-e53e-11e9-9dd0-e710af0815ab.png)
None of the blink buttons make any of my lights blink.
@manup What is the danger zone about ?
ConBee1 on RPI3
`FW 26330500`
`{
  "apiversion": "1.16.0",
  "bridgeid": "00xxxxxxxxxxxxxxxxx",
  "datastoreversion": "60",
  "devicename": "ConBee",
  "factorynew": false,
  "mac": "b8:27:xxxxxxxxxx",
  "modelid": "deCONZ",
  "name": "deconz-xxxxxxxxx",
  "replacesbridgeid": null,
  "starterkitid": "",
  "swversion": "2.5.69"
}`

**Comment by FezVrasta** [comment]
@manup here's the screenshot. I moved a light close to the gateway.

Also, discard my previous screenshot, the device listed was a spare smart plug I had plugged in and forgot to configure.

![image](https://user-images.githubusercontent.com/5382443/66063553-e63f7a00-e543-11e9-9aa3-190dfba1eb58.png)

If I click "blink" nothing happens.

**Comment by manup** [comment]
Ah okay so that indicates (at least some) lights are on channel 20.
Please switch the Zigbee channel to 20 in the Phoscon App.

If the lights are there it will take a while until the gateway picks them up, but after 10-20 minutes  they should be controllable again.

**Comment by FezVrasta** [comment]
Thanks, I changed the channel to 20 a few hours ago and most of the lights are now back online.

I still have 1 light unresponsive, and all my Philips Dimmers.

What else can I try?

**Comment by FezVrasta** [comment]
@manup may you give me guidance please? :-(

**Comment by ebaauw** [comment]
To revive the Hue dimmer, press all four buttons until the LED starts cycling colour.

**Comment by FezVrasta** [comment]
no luck, they seem death. maybe they kept looking for a network for the whole time my lights were unresponsive and the battery ran out 🤷‍♂️ I'll try to replace them

**Comment by ebaauw** [comment]
They should blink red when pressed while dropped off from the network.  If they don’t it might indeed be a battery issue.  To re-pair them, press and hold the reset button (hole) on the back for 10 sec.

**Comment by S474N** [comment]
After connecting Sonoff ZBMINI have all lights, IKEA repeater offline.

RPi 4B + Docker version

ConBee II
2.12.03 / 12. 7. 2021
266F0700

In log:
```
today at 18:45:30 18:41:11:656 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:41:23:453 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:41:30:453 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:41:40:904 Device TTL 5290 s flags: 0x7
today at 18:45:30 18:41:53:458 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:42:00:456 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:42:23:458 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:42:30:556 0x00158D000XXXXX error APSDE-DATA.confirm: 0xF0 on task
today at 18:45:30 18:42:40:890 Device TTL 5230 s flags: 0x7
today at 18:45:30 18:42:46:864 GW firmware version: 0x266f0700
today at 18:45:30 18:42:46:864 GW firmware version is up to date: 0x266f0700
```

**Comment by stefpb** [comment]
Change the usb cable works for me!

**Comment by S474N** [comment]
IoT are connected (with "old" USB gold plated cable), but my log is still flooded:

![image](https://user-images.githubusercontent.com/16512337/129860826-51a820e2-7fe6-47a8-b3d8-e8ce613e5cad.png)

**Comment by SwoopX** [comment]
As far as I can tell, this is harmless. The coordinator is trying to query the modelID from your Xiaomi deep sleepers.
