### ISSUE TITLE
xiaomi mijia aqara bulb zigbee supported?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#1880]
Hi are those zigbee bulbs already supported?

https://www.aliexpress.com/item/32987611284.html?spm=a2g0o.productlist.0.0.2a673ac8hJ5Y4r&algo_pvid=fcdbe2df-baf8-4847-8914-796694e6dac4&algo_expid=fcdbe2df-baf8-4847-8914-796694e6dac4-1&btsid=287ae2b0-eb23-47c1-ab6f-4cace038fe6d&ws_ab_test=searchweb0_0,searchweb201602_3,searchweb201603_52

**Comment by hellcry37** [comment]
bump, i'am also interested

**Comment by Smanar** [comment]
After using the search feature > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1057
