### ISSUE TITLE
New device request without GUI

### ISSUE THREAD

**Issue by nigobo** [dresden-elektronik/deconz-rest-plugin#1888]
Hi!

I am wondering if it is possible to help with _New device requests_ when running the Deconz software without GUI. I recently bought two new IKEA lamps that aren't supported.

- IKEA 250 lm filament light E27 (2200K) LED1842G3 (https://www.ikea.com/fr/fr/p/tradfri-ampoule-led-e27-250-lumen-sans-fil-a-variateur-dintensite-lumiere-chaude-globe-verre-transparent-brun-70455676/)
- IKEA 806 lm E27 (2700K) LED1836G9 (https://www.ikea.com/fr/fr/p/tradfri-ampoule-led-e27-806-lumen-sans-fil-a-variateur-dintensite-blanc-chaud-opalin-90408797/)

Regards,
Jocke

**Comment by MattL0** [comment]
+1

**Comment by bhansson** [comment]
+1

**Comment by aagator** [comment]
Either this or add IKEA 250 lm filament light E27 (2200K) LED1842G3 ;)

**Comment by Smanar** [comment]
The pairing procedure don't work ?
Almost all bulbs are working out of the box.

**Comment by aagator** [comment]
IT starts to pair but suddenly stops. The bulb will not enter pairing again unless reset. Tried several times...

**Comment by nigobo** [comment]
Tried again today. Both works.  

The procedure was: 

1. Start the "new lights" search in Phoscon
2. Do the reset sequence on/off six times and make sure that the light starts to flicker/pulse
3. Wait, and now it works.

_The strange thing is that both worked on the first try today. I really don't understand what the difference is. But I'm happy it works!_

<img width="615" alt="Screenshot 2019-09-27 at 10 11 30" src="https://user-images.githubusercontent.com/2266769/65753397-3a46fa80-e10f-11e9-8057-e57670314c76.png">
<img width="653" alt="Screenshot 2019-09-27 at 10 11 37" src="https://user-images.githubusercontent.com/2266769/65753398-3adf9100-e10f-11e9-9398-869e7934fd48.png">
