### ISSUE TITLE
Connect OSRAM Smart+ Switch Mini (AC0251)

### ISSUE THREAD

**Issue by AlexKusnezov** [dresden-elektronik/deconz-rest-plugin#1893]
Hey guys, 

I'm having trouble to connect this one to my ConBee (1st gen.):
https://www.amazon.de/Osram-Lichtschalter-schwarz-Fernbedienung-Erweiterung/dp/B074PZWNPB/ref=sr_1_8?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=OSRAM+Smart%2B+Switch+Mini&qid=1569057721&s=gateway&sr=8-8

How can I add this?

**Comment by bdickhaus** [comment]
It doesn't look like it is supported yet. None of the OSRAM or Lightify switches are. #374

**Comment by Philje123** [comment]
It connects but controls all the lights with no way to stop this. Not supported yet.
