### ISSUE TITLE
IKEA blinds pairings issues

### ISSUE THREAD

**Issue by probize** [dresden-elektronik/deconz-rest-plugin#1900]
Hi I have 3 Fyrtur, and 1 Kadrilj smart blinds. I have been able to pair all besides one Fyrtur. I have done the following.

=Tried to initialize pairing for hours. 
=Validated that the software version is the same as for the once there will pair 
=Paired with ikea bridge successfully and tried to register again
=Paired solo with repeater and button and tried to register again
=Moved the blind to another location = two different one as close as Deconz stick as possible and the other whee I successfully paired another blind 
=Reset the blinds accordingly to the manual - many times
=Set a repeater nearby 3 meters while pairing 
=Set a socket 2 cm away while pairing. 
=Wait a day a try again - with same result 

I know there that there are some debugging option and I will gladly enable them, if it would be at any help for you. I have almost given up and have thought about returning the one there would not pair. But it works fine on pure ikea..

**Comment by fastender** [comment]
I have the same problem, one of the Fyrtur Blind cannot paired, I tried everything. I think it is some firmware problem.
