### ISSUE TITLE
Request device support EweLink

### ISSUE THREAD

**Issue by Cyrox49** [dresden-elektronik/deconz-rest-plugin#1902]
Hi,

Could you add support for the on/off module EWELINK.

I can add other screen if you need.

Thanks

![node info](https://user-images.githubusercontent.com/32438192/65524881-dfcf5380-deee-11e9-9b6e-29475dd4141e.jpg)
![cluster info](https://user-images.githubusercontent.com/32438192/65524887-e362da80-deee-11e9-9179-9c0a94c8233e.jpg)
![Basic cluster info](https://user-images.githubusercontent.com/32438192/65524900-e65dcb00-deee-11e9-9e34-0c29d369c418.jpg)
![identify cluster info](https://user-images.githubusercontent.com/32438192/65524905-e8c02500-deee-11e9-9abc-d5c8d91d77ed.jpg)

**Comment by ebaauw** [comment]
I would think it’s already supported as a `/lights` resource?

**Comment by Cyrox49** [comment]
Yes it is, but it show in unknow device in deconz jeedom plugin.
