### ISSUE TITLE
Philips Hue Filament Globe (E27)

### ISSUE THREAD

**Issue by SimplyGardner** [dresden-elektronik/deconz-rest-plugin#1906]
I have just received the new [Philips Hue Filament Globe (E27)](https://www.argos.co.uk/product/2057312) and connected it to my ConBee II stick. 

Wondering what I can do to help test to ensure it functions correctly and can be added to the support devices list?

It seems to operate fine through Home Assistant and the Deconz GUI. Although there is a 2/3 second delay when operating through HomeKit (Home Assistant >> [HomeKit Component](https://www.home-assistant.io/components/homekit/)).

**Comment by Kane610** [comment]
There are some issues with Hass HomeKit integration (I've noticed poor color mappings) that I will investigate further down the road

**Comment by SimplyGardner** [comment]
Awesome - thanks @Kane610. Great to hear that the HomeKit component is still getting maintained :)

**Comment by Kane610** [comment]
Well Im doing it from the angle of making sure that the deCONZ integration works as good as possible :)

**Comment by SimplyGardner** [comment]
Understood and you are doing an awesome job - saw your contribution to the Ikea blinds too!

**Comment by Kane610** [comment]
Haha, thanks! I was mostly harassing deCONZ upstream developers :P
