### ISSUE TITLE
zigbee: 'Install codes' support

### ISSUE THREAD

**Issue by imammedo** [dresden-elektronik/deconz-rest-plugin#1909]
I wonder if it's possible to add to deconz  'Install codes' as per BDBv1.0 spec (chapter 10.1),
(coordinator part of it)?

**Comment by manup** [comment]
We have a internal prototype for Install Codes which already works with a few devices.

The current REST-API interface was added in commit https://github.com/dresden-elektronik/deconz-rest-plugin/commit/24c7ff9d3047b7a6bde698e56d734120b63025ee. Note that it requires the `hashing-cli` executable from the Zigbee Alliance.

We hope to release it in 2020 with a simple user interface in the Phoscon App.

**Comment by Adminiuga** [comment]
@manup 
two questions:
1. what Zigbee devices with install code have you used to test with?
2. For deCONZ serial protocol, how do I add the derived key to ConBee?
