### ISSUE TITLE
Unknown icon in front of the group name

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-rest-plugin#191]
Any chance, to get rid of this icons in front of the group names "Küche" and "Flur"?

![img_0472](https://user-images.githubusercontent.com/29394115/30250358-2f027bb8-964d-11e7-8ed9-680e32103fff.png)

**Comment by manup** [comment]
This is actually a "feature" ;)

The symbol is shown for groups which are affected by sensors (I rekon in this case it's a brightness sensor).
Since the new app handles this differently it won't be changed in the wireless control webapp.
