### ISSUE TITLE
Phoscon App founds only Battery

### ISSUE THREAD

**Issue by MiguelESP89** [dresden-elektronik/deconz-rest-plugin#1918]
Hey, 
I connected my Xiaomi Aqara Mijia Smart home Light Control ZiGBee Wireless Key and Wall Switch in Phoscon. 
After this I installed Deconz in Hassio. 
In Integrations i found the my switch but it founds only the battery attribute and not he physical switches. 

Is it possible to trigger the buttons on the switch? 

Thank you for your help. 

Miguel 
![Bildschirmfoto 2019-10-01 um 19 31 49](https://user-images.githubusercontent.com/39128034/65985455-23dbce80-e482-11e9-9185-446f67c3123b.png)

**Comment by bastshoes** [comment]
Wireless switches like buttons do not have entity. You have to use events in your automations.
