### ISSUE TITLE
Req for device support. Heiman gas sensor HS1CG-E

### ISSUE THREAD

**Issue by Asbjoern** [dresden-elektronik/deconz-rest-plugin#1919]
It looks like there is a new Heiman Combustible gas sensor HS1CG-E. The non-E is on the supported list.
This one does is not detected by the Phoscon app.
![label](https://user-images.githubusercontent.com/2461422/65986179-a618c280-e483-11e9-88a6-5a31f69d5ada.jpg)
![Screenshot 2019-10-01 at 19 29 18](https://user-images.githubusercontent.com/2461422/65986230-bfba0a00-e483-11e9-990d-a1fddee7d05b.png)
![Screenshot 2019-10-01 at 19 30 33](https://user-images.githubusercontent.com/2461422/65986252-c6488180-e483-11e9-817e-a814ec3e4e5e.png)

**Comment by andrem99** [comment]
Could you please add support for this sensor model in Deconz.
Many thanks!

**Comment by milkwithfish** [comment]
I've got the same problem. It would be awesome to add this sensor to supported list.

**Comment by andrem99** [comment]
Hi @manup! Thanks for paying attention to the request. How long do you think it will take to integrate this version of the sensor to deconz?

**Comment by michis0806** [comment]
How do you set the Heiman to pairing mode?

**Comment by andrem99** [comment]
With a long press, nothing special.

**Comment by michis0806** [comment]
Yes, I didn't manage to connect it to a deconz/phoscon gateway...

**Comment by SCoe2k** [comment]
Same problem. Cannot connect hs1cg-e. Thank you for taking it up to devoce integration.
@manup : any indication about timing?

**Comment by michis0806** [comment]
> With a long press. I tried all possible ways. Is there a trick, you mean?

Still no luck here. I think I tried any possible combinations of pressing the buttons of the Heiman, but phoscon does not recognize it :/

**Comment by andrem99** [comment]
@manup Hi, Manuel, any update on this issue? quite a few people are suffering already:) would appreciate if you could give at least some update. thank you upfront!

**Comment by SwoopX** [comment]
This post might hold the solution: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2403#issuecomment-581164140

**Comment by flavio20002** [comment]
No way to pair this device....the post was not helpful...any hint?
Thanks

**Comment by flavio20002** [comment]
Sorry, it works perfectly

`
    "43": {
        "config": {
            "on": true,
            "pending": [],
            "reachable": true
        },
        "ep": 1,
        "etag": "a35e061f17a70c456da16f7520e85040",
        "manufacturername": "Heiman",
        "modelid": "GASSensor-EM",
        "name": "Gas Sensor",
        "state": {
            "carbonmonoxide": false,
            "lastupdated": "none",
            "lowbattery": false,
            "tampered": false
        },
        "swversion": "2018.3.26",
        "type": "ZHACarbonMonoxide",
        "uniqueid": "xxxxxxx"
    },
`

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
