### ISSUE TITLE
Connecting to a Siterwell GS361

### ISSUE THREAD

**Issue by larskohlenberg** [dresden-elektronik/deconz-rest-plugin#1927]
Hi, 

I got a Siterwell GS361 radiator themostat and see it in the deCONZ:
![Siterwell1](https://user-images.githubusercontent.com/56118337/66125579-9a461100-e5e7-11e9-85b2-b645fecb48ed.JPG)

![Siterwell2](https://user-images.githubusercontent.com/56118337/66125697-f9a42100-e5e7-11e9-8266-fb34b1e2c155.JPG)

But I do not get any further cluster infos and also do not see this device in the phoscon webinterface.

Any ideas?

Thanks and best regards
Lars

**Comment by Shurov** [comment]
Sorry for off-topic, but where could you find it available for purchase?

**Comment by BTopbas** [comment]
I am interesting this TRV. @larskohlenberg did you find solution?

**Comment by BTopbas** [comment]
@larskohlenberg and where did you purchase it?

**Comment by sylvaing** [comment]
Hi, No news about gs361 and Deconz support ?

**Comment by Wonkavator** [comment]
Winter is coming and I ordered the same device.
Would appriciate, if there could be a support by deconz. Is there some way how I could support development?

There is one article that was sniffing the communication, might that help:
https://medium.com/@dzegarra/zigbee2mqtt-how-to-add-support-for-a-new-tuya-based-device-part-2-5492707e882d

**Comment by kylegordon** [comment]
@BTopbas @Shurov I've found it at https://www.aliexpress.com/item/1005001349186776.html

Also wondering if there's support or not, or upcoming

**Comment by Mimiix** [comment]
@Smanar Is this something for you?
