### ISSUE TITLE
Raspbee never online *stuck in joining*

### ISSUE THREAD

**Issue by SSkull995** [dresden-elektronik/deconz-rest-plugin#1929]
Hello! 
I just installed my Raspbee, I received it yesterday, on my rasp. The thing is, it doesn’t connect to my network, the red led is always blinking! 
I tried everything already done, I upgrade it to the 300500 version, because I read it helped another person, but not me apparently. 
I just check the network settings, weird thing is that TC address is all 0 (0x0000000) as the network key and tc link key. 
Device type is coordinator, as should be, but I cannot save any thing I change. 
Do you have any idea on how to solve this problem? Thanks a lot! Bye!

**Comment by manup** [comment]
>I tried everything already done, I upgrade it to the 300500 version, because I read it helped another person, but not me apparently.

There is no such version, the latest RaspBee firmware version is 0x26330500. See also https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

Can you click the "Leave" button in deCONZ? The LED should then stop to blink and we can reconfigure the settings.

**Comment by SSkull995** [comment]
Hi! I can assure you there is the 0x26300500, I downloaded it. No all the buttons are grayed out!

**Comment by SSkull995** [comment]
As a result, I can’t change anything

**Comment by manup** [comment]
0x26300500 (I totally forgot it existed) is older than 0x26330500, please upgrade to the latest version first.

https://www.dresden-elektronik.de/rpi/deconz-firmware/deCONZ_Rpi_0x26330500.bin.GCF

We can then check the configuration and try to repair it manually, for that can you please provide the mac address printed on the RaspBee radio module, it should start with 00-21-2E...

**Comment by SSkull995** [comment]
Wait, I passed from the 330500 to the 300500 because even with the 330500 I had the same exact problem. Buttons grayed and nothing can be changed

**Comment by SSkull995** [comment]
How do I enable the debug mode? Thanks!!

**Comment by manup** [comment]
You really need to use 0x26330500 it has the latest bug fixes. The issue with the buttons can be resolved by reconfiguring afterwards. It's a bit tricky but can be done, I assume currently the firmware is running in circles because no valid configuration is present.

Debugging can be enabled by starting deCONZ from a terminal (but it won't help here much):

    deCONZ --http-port=8080 --dbg-info=1 --dbg-error=1

**Comment by SSkull995** [comment]
ok so I installed the latests firmware, I am checking now with the gui

**Comment by manup** [comment]
Glad there is progress. The network key can be selected freely and should use some random numbers.
To create new random key you can use the "Reset gateway" function in  the Phoscon App.

https://phoscon.de/en/app/doc#settings-gateway-general-en

Be aware that this will reset all settings including already paired devices.
