### ISSUE TITLE
Swicth - Friends of Hue - doesnt' work in deconz/conbee Stick

### ISSUE THREAD

**Issue by daendaen** [dresden-elektronik/deconz-rest-plugin#1936]
Hi,

today my senic switches have come. But deconz can't find the switch.

Can not the switch be integrated?

Greetings

**Comment by daendaen** [comment]
Now the switch is connected to the conbee stick. But the switch doesn't work. 
I have assigned the switch a Osram Light, but nothing happens

Important infomation for connect the switch comes from dresden elktronik Mr. Preuß. Thank you.

I little manual:
1) Lock in the Gateway which Zigbee channel you use.
2) Go in the App to Switch and select other switch
3) Then press the button from the richt channel on the switch with the energy bar for 7-12 seconds

Now The switch is recognized.


 
![image](https://user-images.githubusercontent.com/44930653/66492251-602bb200-eab4-11e9-8b63-09c830e37d04.png)

**Comment by fazerize** [comment]
Hey, did you get the switch to work?
I asigned the buttons but they won't work.
Idk what I'm doing wrong...

**Comment by manup** [comment]
We've just created a small FAQ entry on how to join the Friends of Hue switches. Note that step 5) is very important to keep the switch on the required Zigbee channel.

https://phoscon.de/en/support#pairing-friends-of-hue-switch
