### ISSUE TITLE
Expose groups to Alexa

### ISSUE THREAD

**Issue by DSchumacher2104** [dresden-elektronik/deconz-rest-plugin#1937]
I can't expose my groups created with Phoscon to Alexa. All lights are found, but no groups. Is it possible to expose groups to Alexa?

**Comment by silent-303** [comment]
I am interested too :-)

**Comment by eifeler-thd** [comment]
That's interesting for me too. A group of single lamps in Alexa is not controlled properly.

**Comment by Tscherno** [comment]
Same here. The Grouping on Alexa itself is turning the lights not at once but sequentially.

**Comment by Xploder** [comment]
Is this really the intended behaviour?
Hue essentials and Home Assistant see and control the groups just fine.
