### ISSUE TITLE
add deconz to hue app

### ISSUE THREAD

**Issue by curla92** [dresden-elektronik/deconz-rest-plugin#1938]
I want to add deconz to hue app official. during the scan is founded but when i try to register this it doesn't work. Who can help me? thank y

**Comment by puckthefly** [comment]
Same problem here, no chance to connect to the hue app and also no chance to connect to iConnect on a iPhone.

**Comment by Chewb4cc4** [comment]
I have the same problem. Cannot connect third party apps to my Raspbee

**Comment by th3cube** [comment]
Doesn't the official App require https? Anyway iConnectHue shout be compatible but it wont connect to the denconz-api either.
