### ISSUE TITLE
Cannot setup new Conbee 2

### ISSUE THREAD

**Issue by michaelblight** [dresden-elektronik/deconz-rest-plugin#1951]
I'm not sure if I should post this here because it may be a hardware problem. Anyway, for anybody else who has the same problem, hopefully it can be fixed.

I bought a ConBee 2 and had problems with installation. I followed the instructions and within deCONZ it did not show up as connected, so I followed the technical support, and got through all of the steps until it suggested I reflash the firmware with the following instruction:

```
sudo GCFFlasher_internal -d /dev/ttyACM0 -t 60 \
-f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26490700.bin.GCF
```
However, when I did this, it kept timing out...

```
GCFFlasher V3_06 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM0 (ConBee II)
action: update firmware after 46 ms
flashing 158985 bytes: |======error: timeout flashing firmware after 3009 ms
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
action: update firmware after 18 ms
flashing 158985 bytes: |=============error: timeout flashing firmware after 3005 ms
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
action: update firmware after 14 ms
flashing 158985 bytes: |=======error: timeout flashing firmware after 3005 ms
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
action: update firmware after 23 ms
flashing 158985 bytes: |======error: timeout flashing firmware after 3009 ms
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
action: update firmware after 18 ms
flashing 158985 bytes: |======error: timeout flashing firmware after 3002 ms
retry, failed

1607: Error: uart reset failed, check retry

```
Before I did this, I confirmed it was present as /dev/ACM0, but after the attempt at flashing, it now shows:

```
michaelblight@NUC:~$ ls -l /dev/ttyACM*
ls: cannot access '/dev/ttyACM*': No such file or directory
```
And "lsusb" no longer shows the ConBee 2, so is it bricked?

I have the ConBee plugged into an Intel NUC (directly or via a USB extension, in multiple USB ports), and it's running Ubuntu 18.04. I am not running deCONZ under Docker or a VM, although I do have Docker running on the machine as well as VirtualBox.

I also tried connecting it to a Windows machine and it keeps connecting and disconnecting from USB. It only stays connected for a second before it disconnects, so nothing useful can be done with it.

**Comment by michaelblight** [comment]
But then again.

I ordered it very recently, via Amazon US and then shipped to Australia. So hopefully it's a recent one, and lets not complain too much that Amazon put it in a huge box which resulted in higher postage costs.

I kept trying different combinations and Windows kept beeping the USB connected/disconnected sound. Then at one point I launched the deCONZ GUI and, as expected, Conbee II appeared for a while, then disappeared for a while. This went on for several minutes, but then it said "a new version of firmware needs to be downloaded". I leapt across the room and clicked Ok (or whatever) and it started updating. Even though I heard one more USB beep, it got to 100% and then appeared in deCONZ. I then disconnected it and plugged it into the Ubuntu machine (where I actually want it), and although it was a bit stubborn at first, it finally worked.

I was then able to pair an Aqara cube and can get events from it in Node Red. Woo hoo! Not that I have a warm feeling about the whole experience, but at least it's going right now. Thanks for the quick response @manup - I assume this can be closed now?

**Comment by rsaffi** [comment]
Exact same as I described [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1598#issuecomment-541972208). Ordered it on Oct 12th on Amazon Germany.

**Comment by michaelblight** [comment]
Have you tried what worked for me? Leave the deCONZ program running; the Conbee appears and disappears every few seconds, but for me after a while it showed a dialog box to upgrade the firmware which then worked.

**Comment by rsaffi** [comment]
> Have you tried what worked for me? Leave the deCONZ program running; the Conbee appears and disappears every few seconds, but for me after a while it showed a dialog box to upgrade the firmware which then worked.

I ended up going with the USB 2.0 extension cable and that did the trick. If you look below the comment I had linked to you'll find newer comments from me reporting back my progress. 

Glad it worked for you to simply wait, because for me it didn't. I left it there for hours, but it would keep on connecting/disconnecting intermittently.
