### ISSUE TITLE
Commits for v2.04.77?

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#196]
I see v2.04.77 has been published yesterday evening, but the changes are not yet committed to GitHub.  Should I ignore this version for now?

**Comment by Krocko** [comment]
Today deCONZ lost all my devices, with this Version and i can‘t reconnect. Increase the nwk by 1 solved this Problem

**Comment by manup** [comment]
The commits are up now, sorry for the delay.

>Today deCONZ lost all my devices, with this Version and i can‘t reconnect. Increase the nwk by 1 solved this Problem

The problem is not related to the version and was reported for prior versions, a fix is in progress but will take some more time.
