### ISSUE TITLE
Device Support Request HEIMAN Gaz Sensor Heiman HS1CG

### ISSUE THREAD

**Issue by laurent941** [dresden-elektronik/deconz-rest-plugin#1973]
Hi,

Could you add support for EIMAN Gaz Sensor Heiman HS1CG ( european version )

![image](https://user-images.githubusercontent.com/56654098/66952950-dd7b9780-f05d-11e9-9244-d83b1365e8ba.png)

![image](https://user-images.githubusercontent.com/56654098/66952899-c6d54080-f05d-11e9-9344-51382c3d9c8b.png)

![image](https://user-images.githubusercontent.com/56654098/66952925-d18fd580-f05d-11e9-840d-eb64fe50a285.png)

![image](https://user-images.githubusercontent.com/56654098/66952937-d785b680-f05d-11e9-8448-e1727dd1c322.png)

thank you in advance

**Comment by laurent941** [comment]
no answer ?

**Comment by andriej** [comment]
I'm also interested, just have ordered it.

**Comment by andriej** [comment]
It just arrived. Paired but no further options to use it...

**Comment by michis0806** [comment]
> It just arrived. Paired but no further options to use it...

How did you pair it? In Phoscon?

**Comment by andriej** [comment]
No, through the VNC UI. I can see it in mesh but even without name. 
Currently unusable :(

**Comment by michis0806** [comment]
Okay, thanks though. ;)

**Comment by andriej** [comment]
FYI: [Here is the instruction](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2403#issuecomment-581164140) from different user how to pair it so at least it can be seen in API, not in Phoscon tho
