### ISSUE TITLE
Device Support Request HEIMAN Smart motion Sensor HS1MS-E

### ISSUE THREAD

**Issue by laurent941** [dresden-elektronik/deconz-rest-plugin#1974]
Hi,

Could you add support for EIMAN Smart motion Sensor HS1MS-E ( european version )

![image](https://user-images.githubusercontent.com/56654098/66953148-351a0300-f05e-11e9-910b-b5001531e4db.png)

![image](https://user-images.githubusercontent.com/56654098/66953087-1ca9e880-f05e-11e9-8661-a95fa83374a2.png)

![image](https://user-images.githubusercontent.com/56654098/66953101-23d0f680-f05e-11e9-982f-b3ff16516349.png)

![image](https://user-images.githubusercontent.com/56654098/66953126-2b909b00-f05e-11e9-9339-726ba4c672d3.png)

**Comment by laurent941** [comment]
no answer ?

**Comment by Deinara** [comment]
I also bought one of these thinking they were supported as shown on the [Supported Devices](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#supported-sensors) page. Seems I have the -E variant which is not supported. 

Is there a point in doing any verification of the data you presented with my device? (and how would I go about creating those screenshots? I can't seem to find a guide on the wiki)

**Comment by Deinara** [comment]
I can confirm that my device is the exact same as the one in this issue.

For extra info, I've included the cluster info below:
Basic:
![image](https://user-images.githubusercontent.com/18037953/70242734-9f534800-1771-11ea-8c88-8e464f6a4eb8.png)

Power configuration:
![image](https://user-images.githubusercontent.com/18037953/70242757-aaa67380-1771-11ea-9bcb-b5af5b4ece64.png)

Identify:
![image](https://user-images.githubusercontent.com/18037953/70242786-beea7080-1771-11ea-8502-f98118e92e03.png)

IAS Zone:
![image](https://user-images.githubusercontent.com/18037953/70242820-cdd12300-1771-11ea-8de6-1970bbe11653.png)

OTAU:
![image](https://user-images.githubusercontent.com/18037953/70242949-01ac4880-1772-11ea-927d-0500bf5387bd.png)

**Comment by Hypfer** [comment]
Same device. Same issue.
I suppose it's just a matter of whitelisting this variant.

It might be interesting to compare IDs etc with a non -E version.

**Comment by Harry-1976** [comment]
Would like to see this sensor being supported. 
Heiman probably only ships out the E-version to Europe now anyway.

**Comment by sylviepipi** [comment]
same problem, any progress ?

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by Mimiix** [comment]
Re opening until merged.

**Comment by laurent941** [comment]
it's really sad that dresden-elektronik is not compatible with most of the heiman products in european version none of my tickets were managed

**Comment by laurent941** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1973
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1974
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1972
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1975

**Comment by Mimiix** [comment]
@SwoopX

**Comment by SwoopX** [comment]
deconz can handle most of the Heiman devices and therefore supports them. An exception might be the switch mentioned before.

**Comment by laurent941** [comment]
Thank you for your response SwoopX
but I assure you the Heiman devices I mentioned above are not yet supported. 
How can we help to support what information do you need?

#1973
#1974
#1972
#1975

**Comment by SwoopX** [comment]
So, the first two is ok. For the motion sensor, this one came just in lately as the modelID had changed for newer versions. However, as HA downgraded thwir addon and subsequently deconz as well, support git kicked out again.

So that leaves us with the switch. It requires some debugging and ideally the ability to compile a dev version of deconz REST API plugin for testing.

**Comment by laurent941** [comment]
hello swoopx  I'm not a developer but I own both versions of switch tell me how to do and I'll give you all the connexion sceenshot I have.  :)

**Comment by SwoopX** [comment]
Well, the challenge is that you're using HA if I understood correctly. Is deconz running in docker or on bare metal?

**Comment by laurent941** [comment]
Hello SwoopX

I have a synology and a dockworker.
I'm using Conbee II  Zigbee Gateway  and t phoscon with
https://registry.hub.docker.com/u/marthoc/deconz/

And HA with 
https://registry.hub.docker.com/u/homeassistant/home-assistant/

an Aqara Homekit gateway thanks to API to HA
so I'm combining 

Zigbee conbee 2 deconz
Aqara in homekit version 
and HA in homekit and zigbee with conbee 2

and in the end I manage to connect many manufacturers together.

What I find a pity and that heiman is currently one of the only ones to have products in the European format and with very attractive prices.

For exemple I have been using Smart Metering Plug HEIMAN ( french version ) for almost 1 year at less than 30 USD per plug and the power monitoring works perfectly. in HA
.
Look at their smart scene switch.
http://www.heimantech.com/product/?type=detail&id=22

I think many people will be happy to use more Heiman products as they are often the same product in the UK / european / German and French / south european format.

**Comment by Mimiix** [comment]
@SwoopX @laurent941  As this original issue is solved, 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1972 

I re-opened that one.

**Comment by SilverWx** [comment]
Doesn't work for me, pairing ok but the state keep on RAS even if a move is detected, any tips ?
