### ISSUE TITLE
Device Support Request HEIMAN Smart metering plug HS2SK-E-FR

### ISSUE THREAD

**Issue by laurent941** [dresden-elektronik/deconz-rest-plugin#1975]
Hi

Could you add support for  HEIMAN Smart metering plug HS2SK-E-FR ( European /french version )
it is currently recognized as an  light image in phoscon but the information goes up well in home assistant

![image](https://user-images.githubusercontent.com/56654098/66953998-d48bc580-f05f-11e9-80a9-c082cc3009c7.png)

![image](https://user-images.githubusercontent.com/56654098/66953598-23852b00-f05f-11e9-9dca-daddf10796f4.png)

![image](https://user-images.githubusercontent.com/56654098/66953503-f3d62300-f05e-11e9-814d-c8f1efa27649.png)

![image](https://user-images.githubusercontent.com/56654098/66953418-c4271b00-f05e-11e9-9d5f-a83216ba9bcd.png)

![image](https://user-images.githubusercontent.com/56654098/66953429-c9846580-f05e-11e9-8edc-9eb72eb80fed.png)

![image](https://user-images.githubusercontent.com/56654098/66953449-d2753700-f05e-11e9-8cd9-2cd0d4cfd561.png)

thank you in advance

**Comment by laurent941** [comment]
no answer ?

**Comment by twobeass** [comment]
Still not sending Power Infos via REST API... Possible to implement ?

**Comment by SwoopX** [comment]
What is your request to look for it?
