### ISSUE TITLE
Request Device Support - Xiaomi A6121 Vima Smart Lock

### ISSUE THREAD

**Issue by davidramosweb** [dresden-elektronik/deconz-rest-plugin#1977]
Hello,
Could you add support for Xiaomi A6121 Vima Smart Lock lumi.lock.v1
Thanks.
https://www.zigbee2mqtt.io/devices/A6121.html
![image](https://user-images.githubusercontent.com/4605169/67032442-e29b1e00-f113-11e9-940c-9310fcebac30.png)
<img width="733" alt="Captura de pantalla 2019-10-17 a las 19 21 56" src="https://user-images.githubusercontent.com/4605169/67032561-1ece7e80-f114-11e9-9505-a3a583064c2e.png">
<img width="724" alt="Captura de pantalla 2019-10-17 a las 19 21 46" src="https://user-images.githubusercontent.com/4605169/67032583-28f07d00-f114-11e9-84bb-30a4e5352cb5.png">
<img width="728" alt="Captura de pantalla 2019-10-17 a las 19 21 38" src="https://user-images.githubusercontent.com/4605169/67032584-29891380-f114-11e9-9f87-e57878aefb7b.png">
<img width="750" alt="Captura de pantalla 2019-10-17 a las 19 21 18" src="https://user-images.githubusercontent.com/4605169/67032586-29891380-f114-11e9-8ddf-02b025709942.png">
<img width="759" alt="Captura de pantalla 2019-10-17 a las 19 21 12" src="https://user-images.githubusercontent.com/4605169/67032587-29891380-f114-11e9-99de-88604f618f32.png">
<img width="718" alt="Captura de pantalla 2019-10-17 a las 19 21 02" src="https://user-images.githubusercontent.com/4605169/67032590-29891380-f114-11e9-9cde-097cbf730c0e.png">
<img width="716" alt="Captura de pantalla 2019-10-17 a las 19 20 31" src="https://user-images.githubusercontent.com/4605169/67032591-29891380-f114-11e9-9c99-9dead4ffc243.png">
<img width="719" alt="Captura de pantalla 2019-10-17 a las 19 20 24" src="https://user-images.githubusercontent.com/4605169/67032592-2a21aa00-f114-11e9-91a7-1fb639634b8d.png">
<img width="720" alt="Captura de pantalla 2019-10-17 a las 19 20 18" src="https://user-images.githubusercontent.com/4605169/67032593-2a21aa00-f114-11e9-9471-08ba34bc6a3a.png">

**Comment by TTP1106** [comment]
I also recommend to add this device. it's a good alternative of danalock v3. :)

**Comment by wuppi83** [comment]
Please add the device :0)

**Comment by wuppi83** [comment]
Some news :D

**Comment by pollinolas** [comment]
Hi, nothing new about Vima smart lock no deconz?
Regards

**Comment by Smanar** [comment]
According to z2m, you can't use this device to open/close door.
It s just a sensor, that give some information.

**Comment by pollinolas** [comment]
> According to z2m, you can't use this device to open/close door.
> It s just a sensor, that give some information.

Thanks for answering, if I know that, I have already read it in the forums, but my question is if it can be added even as a sensor to home assistant through deconz greetings again and thanks

**Comment by Smanar** [comment]
Hello.
On my side I m justy trying to report the same value the device send to the Xiaomi application.
The encoding is only usefull to add new key I presume ? It s done by the Xiaomi application too, and using zigbee ? Because I don't see those feature on the capture.

**Comment by Nemesis24** [comment]
Please add the device :0)

**Comment by Smanar** [comment]
I have started the code https://github.com/Smanar/deconz-rest-plugin/tree/divers
But need someone with the device and an Unix machine.

**Comment by Mimiix** [comment]
@Smanar Do we need to re-open?

**Comment by Smanar** [comment]
IDK, for the moment I m ready but waiting for a "candidate" ^^, and can take long time

**Comment by Nemesis24** [comment]
If i can help I'm with a rasbee1  on rasberry pi 3b+ i'm using zha on hassio with zigpy ... zigpy deconz...zha device handlers

**Comment by Smanar** [comment]
:( Not possible recompile code on Hassio, and zigpy don't use deconz only the conbee.

**Comment by pollinolas** [comment]
> I have started the code https://github.com/Smanar/deconz-rest-plugin/tree/divers
> But need someone with the device and an Unix machine.

Hi, no news about that?

**Comment by Smanar** [comment]
No-one to test it, so the code is still in waiting mode.

**Comment by pollinolas** [comment]
what do you need to test it?

**Comment by Smanar** [comment]
To have a working code, I haven't the device to make test on my side.

**Comment by pollinolas** [comment]
I have the device and a unix machine now, how I can help?

**Comment by pollinolas** [comment]
> To have a working code, I haven't the device to make test on my side.

could you give some instruction to be able to try to add it to phoscon?

**Comment by Smanar** [comment]
Oups sorry, haven't see you answer.
I m searching the code, and not find it yet. I will make a new one for tonight (or found the previous one)

**Comment by Smanar** [comment]
OK, so sorry, I have realy loose the code.

You can take a look here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

So it will be for you

```
sudo apt install deconz-dev
git clone --branch vimar https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

For the moment the code will just create a door sensor.

After that you can return to deconz, enable log, and use the door lock, I need logs starting with "extract Xiaomi special attribute", and you need info_L2 to have them.
