### ISSUE TITLE
Bind a light to (existing) group in deCONZ GUI (via VNC)

### ISSUE THREAD

**Issue by JBS5** [dresden-elektronik/deconz-rest-plugin#1979]
I'm trying to bind a light to a (exsisting) group created by a Hue Dimmer Switch using deCONZ GUI (via VNC). Based on https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Pairing-Devices this should be possible using the 'Bind Dropbox' panel, but I think I do not understand how to use that. No matter what I select (the Hue Dimmer Switch or a light), I am not able to do anything in that panel. Could anyone point to in the right direction how to use this part of the deCONZ GUI?

![image](https://user-images.githubusercontent.com/25594213/67097395-4b3cd600-f1ba-11e9-93c4-9c224d686f37.png)

(I am asking this because one of the 8 GU10 lights which are in a group went offline and I had to pair this one again. Adding this newly paired light to the existing Hue Dimmer group in the Phoscon add did not result in switching on/off together with the other 7. So I guess the binding is not set for this new added light).

\\Edit: Just found in https://www.dresden-elektronik.de/funktechnik/products/software/pc/deconz/?eID=dam_frontend_push&docID=694 how to use the panel. Dragging a light by selecting the list which is shown by selecting the right radio.

![image](https://user-images.githubusercontent.com/25594213/67098027-ade2a180-f1bb-11e9-9e74-d990fb264369.png)

![image](https://user-images.githubusercontent.com/25594213/67098200-0619a380-f1bc-11e9-8aef-dbec47eff2e3.png)

**Comment by ottelo9** [comment]
@JBS5 
I can't get it to work :(
I want to directly bind my Hue Dimming Switch to a bulb. I open the Bind Dropbox.

Source = "Hue Dimming Switch" -> "0006 OnOff" cluster (grey)
Destination = "tradfri bulb GU10" -> "0006 OnOff" cluster (blue)

click on bind = success
But I cannot switch the light on with my dimming switch (press I on the remote). Nothing happens.

![2022_08_15_20_48_19_deCONZ_Home_Assistant](https://user-images.githubusercontent.com/33122175/184697126-e9833373-f6c0-4700-8a5b-cf9c50aedb0b.png)
![2022-08-15 20_47_06-deCONZ – Home Assistant](https://user-images.githubusercontent.com/33122175/184697128-7eb94e8f-5aed-4248-9f6d-70139ae84b37.png)
![2022_08_15_20_47_18_deCONZ_Home_Assistant](https://user-images.githubusercontent.com/33122175/184697129-757fa254-926a-45a5-8840-37c6cc87badf.png)

**Comment by JBS5** [comment]
@ottelo9 I am not using deCONZ anymore so hopefully anyone else can help you with.

**Comment by ottelo9** [comment]
@JBS5 oh ok. Why?

**Comment by JBS5** [comment]
@ottelo9 I was curious about Zigbee2MQTT.

**Comment by ottelo9** [comment]
@JBS5 ok thx. Are you happy with z2m? Whats about ConbeeII updates and the killing feature with the vnc deconz view.

**Comment by JBS5** [comment]
@ottelo9 Yes. I am not using the Conbee anymore but switched to a Sonoff Zigbee Dongle https://sonoff.tech/product/diy-smart-switch/sonoff-zigbee-dongle-plus-efr32mg21/

I guess this is not the best place to discuss the benefits of Z2M ;-)

**Comment by ottelo9** [comment]
:D I know, this was the last question ;)
