### ISSUE TITLE
Different URLs lead to different Gateway versions

### ISSUE THREAD

**Issue by daniel-lo** [dresden-elektronik/deconz-rest-plugin#1982]
Via my LAN IP http://192.168.178.xxx:8080/ Phoscon shows version 2.05.67 / **26.8.2019**
Via the generic  http://dresden-elektronik.de/pwa/ my Gateway shows Version 2.05.67 / **4.10.2019**

Same Gateway. How come?

**Comment by salopette** [comment]
me to

**Comment by ebaauw** [comment]
Same gateway version, 2.05.67; different version of the Phoscon web app.

**Comment by daniel-lo** [comment]
Product - Version - Firmware .. how should one know that this is related to the Phoscon app version?
Also I read that everything stays local even if you use that external link - so I expected it to call my local phoscon app  .. and no external one. I am confused .. clarification would be much appreciated.

Ultimately: Is it better to use the DE-Link because the version is newer?

**Comment by ebaauw** [comment]
The gateway runs locally on your server.  The Phoscon app runs locally in your web browser.  It uses the REST API to talk to the gateway.  You can load the Phoscon app from your local server (the version included in the deCONZ package), or from the dresden elektronik web site (the latest version).

**Comment by daniel-lo** [comment]
thank you .. so my interpretation is: use the one from d-e web site then you may benefit from the newest features or fixes.
