### ISSUE TITLE
Stopping Fyrtur

### ISSUE THREAD

**Issue by CopyCat73** [dresden-elektronik/deconz-rest-plugin#1984]
I'm trying to implement a stop function with the rest API; there doesn't seem to be a dedicated command for it in the api since the curtains are in the light group, but I'd like to stop the motion once I press the same direction a second time on the remote. So when buttonevent is 1002, fyrtur is opening, 1002 received again, stop. Since there's no stop command I'd need to send the bri parameter with the same value it is at at the time of pressing the button for the second time. Any way to implement this in deconz itself?

**Comment by ebaauw** [comment]
Sending `”bri_inc”: 0` should work.

**Comment by CopyCat73** [comment]
that worked, thanks!
