### ISSUE TITLE
Conditions based on sunset/sunrise

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-rest-plugin#200]
Is it possible, to use conditions based on sunset/sunrise?

**Comment by ebaauw** [comment]
Not yet, as deCONZ doesn't yet have a Daylight sensor, see #73.

As workaround, I use a CLIPGenericFlag sensor exposed to HomeKit by homebridge-hue, which I set and clear from HomeKit.  Note that you can only use the iOS builtin Home app to define automations based on sunrise and sunset.

**Comment by Krocko** [comment]
With iOS 11 sunset and sunrise is build in the Home App.

**Comment by ebaauw** [comment]
> With iOS 11 sunset and sunrise is build in the Home App.

This is already the case with the Home app on iOS 10.

> You can use it in Automations.

For some reason Apple decided to keep this functionality exclusive to the Home app.  It's not included in the HomeKit API, used by other HomeKit apps, even though the Automations run on the AppleTV (or iPad when used as a HomeKit Hub).

**Comment by Krocko** [comment]
It is also in the EVE App.

![img_0490](https://user-images.githubusercontent.com/29394115/30520844-b7e99bb0-9bb5-11e7-9350-0d0053e7fb70.png)

**Comment by ebaauw** [comment]
That's a condition, not a trigger.

**Comment by Hypfer** [comment]
You could simply use the websocket to script that. Thats what I'm doing.

**Comment by Krocko** [comment]
@Hypfer can you please describe this in more detail?

**Comment by Hypfer** [comment]
You can use the REST API of DeConz to trigger a Scene/do basically whatever you want to do. I for example use it to set the color temperature according to the current position of the sun.

https://github.com/mourner/suncalc I'm using that library to calculate sunrise/sunset.

**Comment by Hypfer** [comment]
To do that I'm running node-red on that deconz rpi. I've exported the relevant flow for you. You can find it in this gist:
https://gist.github.com/Hypfer/c7fa63a4f6d99e0fd856247adf81fae2

You do however need to change a few things:
URL_OF_DECONZ
APIKEY
Group ID
LAT
LONG

Maybe you'll also need some node-red plugins. I'm not sure since I've made that a few months ago at 3am. It still works fine, though.

**Comment by Krocko** [comment]
Thank you. Will give it a try.

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
