### ISSUE TITLE
Ikea Fyrtur repairing and current_position issue in HA

### ISSUE THREAD

**Issue by allanpersson** [dresden-elektronik/deconz-rest-plugin#2003]
My Ikea Fyrtur covers are working fine in HA, but i have a couple of issues:

- When i update/downgrade Home Assistant i have to go to Deconz and start searching for lights and put the covers in pairing mode, and then they repair and works until next update.

- The value in "current_position" is not updating, and using the current position of the covers as condition is not possible.

Testet/used on:
Home Assistant: vers. 0.100.3 and 0.101.0b1
Conbee II: vers. 2.05.69 / 6.9.2019     Firmware: 26490700
Addon: Native Deconz

**Comment by bratanon** [comment]
I think this is fixed in 2.05.70 which should be released any day now.

**Comment by allanpersson** [comment]
@bratanon Awesome, I'll keep an eye on it 🙏

**Comment by bratanon** [comment]
@allanpersson Im having the same issue are you, so I'm also waiting. 

The release question were asked a week ago here #1956

**Comment by allanpersson** [comment]
@cyberoida how did you manage to get the fyrtur repeaters into deconz?

**Comment by cyberoida** [comment]
@allanpersson I have the EU version, I just started searching for sensors (or lights, I don't remember) and held the button on the repeater for a few seconds. Then it showed up in the desktop program and starts meshing.

**Comment by allanpersson** [comment]
@cyberoida I got the range extenders in now, but current position is not updating 🤷‍♂️

**Comment by allanpersson** [comment]
Reparing fixed with 2.05.70 and conditions is starting to work also (0.102.0b1)...

**Comment by D3nnisd** [comment]
the current position was working for me prior 2.05.70. Now it stopped working.

**Comment by allanpersson** [comment]
Strange, for me so far it's been opposite 😳
I'll keep this issue open until I'm sure it's working

**Comment by allanpersson** [comment]
@D3nnisd how is the problem with your installation?
Mine is working and I'll close the issue if you don't have problem anymore!?

**Comment by D3nnisd** [comment]
@allanpersson It seems fixed here. A restart (complete RPI + Docker) worked.

**Comment by allanpersson** [comment]
@D3nnisd perfect, I close the issue 👌
