### ISSUE TITLE
Ikea Omlopp Led Power Supply compatible ?

### ISSUE THREAD

**Issue by t-rimbo** [dresden-elektronik/deconz-rest-plugin#2004]
I have a RaspBee unit and I thought I could connect my Ikea Omlopp lights and control them.
My Led driver is Ikea Omlopp "Led Power Supply" Model: "YHL30G240-1250CV" (IKEA art:nr 80300764). It says on the unit with wireless receiver. 

I bought this a few years ago for a kitchen rebuild and now I've had the time to install them.

I hope I've done something wrong when I tried to synk the lights but I suspect that I have an older unit that is not ZigBee compatible. 

My question is: Is this correct or have I missted something
![80300764](https://user-images.githubusercontent.com/57033781/67618222-e05c5200-f7ec-11e9-81a7-dad5b7927329.png)
.

**Comment by ebaauw** [comment]
Indeed, I think these old drivers don't do ZigBee.  You should be able to replace them by Trådfri drivers, though.
