### ISSUE TITLE
Explain why update/install unofficial WiringPi on RPi4?

### ISSUE THREAD

**Issue by 00lex** [dresden-elektronik/deconz-rest-plugin#2005]
Excuse me, but I don't understand the context.

im using deconz Raspbee since 2 Years and 3 Months on a Rpi4. 
I have never issues with my rpi4. with the last update you write we have to install the latest version of WiringPi without exception of usage reaspbee/conbee. 

Why is WiringPi needed? And is it necessary if someone use conbee stick?
is unofficial WiringPi just a recommendation or is it needed to avoid some issues? 
thanks

I've update to the latest version on deconz and everything works without unofficial WiringPi installation. 

btw wiringpi seems to be in the raspbian repo
```
root@home:~# apt search wiringpi
Sorting... Done
Full Text Search... Done
wiringpi/testing,now 2.50 armhf [installed,automatic]
  The wiringPi libraries, headers and gpio command
```

why install unofficial? 
```
 wget https://project-downloads.drogon.net/wiringpi-latest.deb
 sudo dpkg -i wiringpi-latest.deb
```

**Comment by schwatvogel** [comment]
I'd also like some information regarding wiringpi, especially as its unsupported now.
Gordon got to frustrated by supporting commercial products using his code.
As i am on archlinux for arm7h, i need to create my own packages from those debs (not shure if it works though), how will you proceed from here without gordons code?

**Comment by manup** [comment]
The wiringpi package will be replaced by libgpiod which is available for more architectures. It will further be loaded dynamically so it is only required when RaspBee is used. Note that for ConBee II neither wiringpi nor libgpiod is needed.

No ETA yet but we already have made a successful test with RaspBee and libgpiod.
