### ISSUE TITLE
deCONZ crashes when opening hidden settings

### ISSUE THREAD

**Issue by peer69** [dresden-elektronik/deconz-rest-plugin#2007]
When trying to open the hidden gateway settings via Alt+click on "advanced" in the gateway settings, the deconz process goes to 100% CPU and crashes eventually. Is there another way to show these options? Trying to migrate to a Conbee II which seems to be impossible without.

**Comment by peer69** [comment]
This is the latest log entry before deconz crashes: 

`void DeRestPluginPrivate::getZigbeeConfigDb(QVariantList&),4918: assertion 'rc == SQLITE_ROW' failed`

**Comment by Smanar** [comment]
Yeah I think you have a problem, but hidden configuration is needed for a migration ?
If you use just backup and restore, it will not be enought ?

**Comment by peer69** [comment]
Nope. Its a different GW. Restoring Phoscon config isnt enough in this case.

**Comment by peer69** [comment]
A new install doenst show this problem. I guess my zll.db is just f*cked up. I'll do what I wanted to do for a long time now (due to connection issues), reset and repair about 65 devices and hope the systems runs smoother afterwards.
