### ISSUE TITLE
[Device Support request] Integrate SwannOne BX_SWO-OUS1P

### ISSUE THREAD

**Issue by xhemp** [dresden-elektronik/deconz-rest-plugin#2013]
Trying to get a BX_SWO-OUS1P  SwannOne Siren on my deCONZ.
Thing is that the siren is being recognised as light on deCONZ although it is showing up on HomeAssistant as a switch.
Even being a switch on HA, I can switch on the siren (so I would be able to have it ringing when the alarm is triggered) but I am not able to switch it off.
Here are the screenshots i got from deCONZ:

<img width="556" alt="Screenshot 2019-10-28 at 13 51 41" src="https://user-images.githubusercontent.com/13650956/67683969-3adee500-f98a-11e9-9649-88340d84646a.png">
<img width="571" alt="Screenshot 2019-10-28 at 13 51 55" src="https://user-images.githubusercontent.com/13650956/67683970-3adee500-f98a-11e9-9c4c-8d1b575e333c.png">
<img width="562" alt="Screenshot 2019-10-28 at 13 52 05" src="https://user-images.githubusercontent.com/13650956/67683971-3b777b80-f98a-11e9-8c7f-40ebc0e27f16.png">
<img width="559" alt="Screenshot 2019-10-28 at 13 52 16" src="https://user-images.githubusercontent.com/13650956/67683972-3b777b80-f98a-11e9-9357-852f0de4e10c.png">
<img width="194" alt="Screenshot 2019-10-28 at 13 52 25" src="https://user-images.githubusercontent.com/13650956/67683973-3b777b80-f98a-11e9-8137-0f397f7bdbee.png">

**Comment by xhemp** [comment]
Looks like this has been looked at #404.

**Comment by xhemp** [comment]
I was able to use the state.alert to control the siren (none/select/lselect work as intended).
The only thing that I couldn't get it working was "blink", it does the siren and the strobe at the same time.

**Comment by xhemp** [comment]
Re-opening this one as I would like to get this sorted. The siren work fine for me (even though the strobe doesn't work on state.alert = blink but it's not a big deal.
Problem with it is that it just loses connection after some hours and I can't control the siren anymore. It also beeps sometimes out of the blue with no interaction at all. Just wondering if something else needs to be done on its configuration.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
