### ISSUE TITLE
users login clone

### ISSUE THREAD

**Issue by curla92** [dresden-elektronik/deconz-rest-plugin#2025]
Hi, i have two phoscon login on my raspbee. how can i delete one of this? it seems as a clone of my first user. thank y

<img width="2910" alt="Schermata 2019-11-01 alle 10 19 28" src="https://user-images.githubusercontent.com/22404058/68014942-2d2ea580-fc91-11e9-9231-bbac4875cdfa.png">

**Comment by manup** [comment]
I suppose this is a bug in our discovery server, returning also old entries.
This will be fixed in the next days.

**Comment by curla92** [comment]
> I suppose this is a bug in our discovery server, returning also old entries.
> This will be fixed in the next days.

ohh perfect, thank y
