### ISSUE TITLE
can´t pair Hue Lights

### ISSUE THREAD

**Issue by wuast94** [dresden-elektronik/deconz-rest-plugin#2028]
I Reset The lights with the remote .. the bulbs blink 3 times and switch back on again. but either in phoscon or in deconz shows up anything. 
I power cycled bevor after and bevor and after. but nothing. The Bulb is a few centimeters away. 

I had the bulbs working for long time without problems with the exact same setup. i switched the usb place of the stick and since then just the half of my zigbee network showed up. so i did a clean reinstall from deconz and factory reset of the conbee 1 stick. 
I go into Deconz via VNC. i see my deconz stick but as i said above. i cant pair the lights

**Comment by wuast94** [comment]
it seems that i can´t pair aqara door sensors and aqara temp sensors too.

**Comment by wuast94** [comment]
i updated the conbee firmware but no changes

**Comment by ebaauw** [comment]
> i switched the usb place of the stick and since then just the half of my zigbee network showed up

Sounds like radio interference.  Are you using a USB extension cable?  And a USB2 port?  Did you switch off Wifi and bluetooth?  Did you disconnect any USB3 devices?

**Comment by wuast94** [comment]
> > i switched the usb place of the stick and since then just the half of my zigbee network showed up
> 
> Sounds like radio interference. Are you using a USB extension cable? And a USB2 port? Did you switch off Wifi and bluetooth? Did you disconnect any USB3 devices?

i switched the stick back where it was before too. so i dont think that this is the problem

**Comment by wuast94** [comment]
ok now it works. don´t know why but it works again.
