### ISSUE TITLE
xiaomi cube is not displayed as a switch

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#2030]
I have vebunden my cube today, but this is not displayed as a switch editor, I have already deleted several times and also restarted Gatway, but no result

![sshot-2019-11-03- 3](https://user-images.githubusercontent.com/32480002/68089013-1345bc00-fe65-11e9-9a77-73508a0877ec.jpg)
![sshot-2019-11-03- 2](https://user-images.githubusercontent.com/32480002/68089018-15a81600-fe65-11e9-8b0b-da9ef373342a.jpg)
![sshot-2019-11-03- 1](https://user-images.githubusercontent.com/32480002/68089019-18a30680-fe65-11e9-8688-e71e10d2eb1d.jpg)

**Comment by Smanar** [comment]
Do you still have the problem ?
It sem this device is a little shitting to add, but it works on other configuration > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1846

Perhaps if you haven't all sensors created you can see it in phoscon but not in switch editor.

**Comment by salopette** [comment]
I have omitted it first. I'm back to the stable, which was with the last ... 70 reboot problems

**Comment by Smanar** [comment]
Long time the V70 is out and still not in stable branch, bad sign ^^, I think they have too lot of problem with it.

**Comment by salopette** [comment]
Yes, wait, the guys of Zigbee2Mqtt and Zigate have made it! There, however, the Comuniti is bigger!
