### ISSUE TITLE
Xiaomi Vima lock support 

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#2031]
Pretty cool 50 USD smart lock, zigbee. 

Is it supported? 

[
https://banggood.app.link/26AvOS8jl1

**Comment by Nemesis24** [comment]
Please add the device :0)

**Comment by Mimiix** [comment]
@Nemesis24 Follow the device request procedure.

**Comment by Nemesis24** [comment]
> @Nemesis24 Follow the device request procedure.

Like this https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1977
