### ISSUE TITLE
EnOcean Senic friends oh hue switch

### ISSUE THREAD

**Issue by rendgeor** [dresden-elektronik/deconz-rest-plugin#2038]
The switch can be connected after some tries (Channel15, upper left button).
Unfortunately it is not shown in deconz gui.

The key mapping in phoscon works but the assigned action does not happen:
![image](https://user-images.githubusercontent.com/10161748/68242679-46c54980-0011-11ea-8101-6ca03659ec8a.png)

**Comment by rendgeor** [comment]
@manup How can the  Request-device-support be done if the device isn shown in the deconz gui?
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by bedaes** [comment]
Same problem with my Senic switch. Did you already solve it?

**Comment by bedaes** [comment]
Nevermind, I missed step 5 from here: https://phoscon.de/en/support#pairing-friends-of-hue-switch

**Comment by rendgeor** [comment]
Update: Short key presses work if assigned directly within a lamp group.

But how can long press events defined?
![image](https://user-images.githubusercontent.com/10161748/71033539-c4ec3400-2117-11ea-8813-2c0ff91ac291.png)
