### ISSUE TITLE
Change color of the light

### ISSUE THREAD

**Issue by mrlook2** [dresden-elektronik/deconz-rest-plugin#2041]
Is it possible to change the color of an ikea light with the ikea remote and deconze app?

**Comment by Smanar** [comment]
Yep, but not possible using the direct connexion (by putting the light in the same group than the remote), you need to use the same procedure than for an other manufacture.

I have just make try with temperature color, I have selected a group, edit, switch editor, link ikea remote. Then "key assignement", i select the up button "long press for warmer", I select the bottom button "long press for colder'
