### ISSUE TITLE
Simple descriptors can't be fetched

### ISSUE THREAD

**Issue by dklundvall** [dresden-elektronik/deconz-rest-plugin#2043]
I have been trying to connect both IKEA lights, a IKEA motion sensor, and a Aqara temperature sensor to a ConBee II. If i initiate a light/sensor search from the Phoscon app, it does not find anything, but the end devices/routers show up in the deCONZ app straight after. However they have only the drop down menu for configurations, and when i try to force fetch with the "Read simple descriptor", it just instantly switches off, unlike the other buttons that starts counting down.

All sensors and lights have been properly reset before connecting, and the ConBee II is connected via a usb extension cable. I run it through my laptop with Ubuntu 18.04.

![Screenshot from 2019-11-06 18-45-52](https://user-images.githubusercontent.com/37441407/68323503-e3e1ba00-00c5-11ea-886d-045077f02699.png)

**Comment by SwoopX** [comment]
I recall this one from my Develco smoke sensors... It was and still is always painful to have then paired. Interestingly, it works with zigbee2mqtt like a charm.

Regardless, some hints which might help. Have you tried to reboot the system running the gateway? Also, what might help is re-pairing the devices without deleting them in the GUI. Just make sure you initiate pairing via Phoscon.
Another thing to try (although it is kinda silly and doesn't really makes sense, but did the trick for me) is initiating pairing in Phoscon. After around 30 secs setting the pairing timer in the deconz GUI to 0 and then read the simple descriptors.

Good luck!
