### ISSUE TITLE
Crash after update to .70

### ISSUE THREAD

**Issue by djwlindenaar** [dresden-elektronik/deconz-rest-plugin#2046]
I'm getting a Crash after upgrading to the .70 beta. I'm on a raspbian with the raspbee hardware. I get:

```
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5SerialPort.so.5: no version information available (required by deCONZ)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5: no version information available (required by deCONZ)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: no version information available (required by deCONZ)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5: no version information available (required by deCONZ)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5: no version information available (required by deCONZ)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5: no version information available (required by /usr/lib/libdeCONZ.so.1)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5SerialPort.so.5: no version information available (required by /usr/lib/libdeCONZ.so.1)
deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: no version information available (required by /usr/lib/libdeCONZ.so.1)
libEGL warning: DRI2: failed to authenticate
deCONZ: relocation error: deCONZ: symbol _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```

**Comment by mysteryan** [comment]
GUI seems to crash for me as well on .70, but runs fine without GUI on Pi 3 / Stretch / Conbee.

**Comment by manup** [comment]
Are you using the shipped plugin or is that compiled manually?

**Comment by mysteryan** [comment]
Both for me.  Shipped .69 seems to be okay.  I noticed that it started crashing with a manually compiled one sometime after that.  Thinking it's an issue with my own compilation, I've just kept quiet about it.  With shipped .70, the crashing still seems to persist.

**Comment by djwlindenaar** [comment]
As shipped. I noticed the name of the package changed to ....Buster.... from ...Jessie... 
Could that be the issue? I'm still on Jessie...

**Comment by manup** [comment]
When installing via APT repository the Jessie package (also compiled on Jessie) should be selected. The steps in the installation instructions should setup the matching distribution:

https://phoscon.de/conbee2/install#raspbian

**Comment by djwlindenaar** [comment]
I installed from here:
https://www.dresden-elektronik.de/deconz/raspbian/beta/

I guess that is now outdated... Maybe it's time to start using the apt route...

**Comment by mysteryan** [comment]
> I installed from here:
> https://www.dresden-elektronik.de/deconz/raspbian/beta/
> 
> I guess that is now outdated... Maybe it's time to start using the apt route...

I also used that download link instead of using apt route.

**Comment by salopette** [comment]
I also have the problem that Deconz has always restarted after a few seconds and was always asked for firmware update.

I have now reinstalled .67 and it works. Do not trust me to make an update again.

**Comment by mysteryan** [comment]
Not sure about OP, but this issue seems resolved after using a manually compiled version of today’s commits.  GUI seems to runs as it should for me (via headless VNC).

**Comment by salopette** [comment]
What is the best way to update Pi3 to the last beta?

**Comment by Smanar** [comment]
Last deconz beta ? using package I think.
But if the V70 is not yet in stable branch after 15 days, I think there is a reason.

**Comment by salopette** [comment]
Thx

**Comment by salopette** [comment]
How can you downgrade from .70 to .69?

**Comment by manup** [comment]
Depends on the platform, assuming Linux you need to manually install the .deb package:

    dpkg -i <deconz deb file>

The files can be downloaded from:
https://github.com/dresden-elektronik/deconz-rest-plugin#precompiled-deconz-packages-for-manual-installation

**Comment by salopette** [comment]
I have Pi3, is that right?

wget https://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.05.70-qt5.deb

sudo dpkg -i deconz-2.05.70-qt5.deb

**Comment by manup** [comment]
Yes but to downgrade you need the .69 version.

**Comment by salopette** [comment]
Ok, THX!
