### ISSUE TITLE
[Device Support Request] SZ-SRN12N Sercomm Corp.

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#2051]
Can you please add SmartThing siren!

![sshot-2019-11-09- 6](https://user-images.githubusercontent.com/32480002/68533181-6916da00-0325-11ea-8927-1f025a85721c.jpg)
![1](https://user-images.githubusercontent.com/32480002/68533182-6916da00-0325-11ea-9b3e-079cf2e4e5b8.jpg)
![sshot-2019-11-09- 1](https://user-images.githubusercontent.com/32480002/68533183-6916da00-0325-11ea-921b-0013a91047d1.jpg)
![sshot-2019-11-09- 2](https://user-images.githubusercontent.com/32480002/68533185-69af7080-0325-11ea-9c2f-83d259424844.jpg)
![sshot-2019-11-09- 3](https://user-images.githubusercontent.com/32480002/68533186-69af7080-0325-11ea-81e0-7de1e4c698f3.jpg)
![sshot-2019-11-09- 4](https://user-images.githubusercontent.com/32480002/68533187-69af7080-0325-11ea-821e-a7902f103bcd.jpg)
![sshot-2019-11-09- 5](https://user-images.githubusercontent.com/32480002/68533189-69af7080-0325-11ea-9566-9a0650602cab.jpg)

**Comment by salopette** [comment]
do you need more info?

**Comment by Smanar** [comment]
I think it's enought, but no user motivated ^^.
You can try yourself.  You have 2 situations, the device is standard and you have already a siren that work like yours, so you just have somes lines to change on the code or you can have an exotic device and need to use so much workaround.

If you wana try your luck, I can explain you how to make modification on the code, but I can't promise you it will working.

**Comment by salopette** [comment]
Hi, I think the device itself is problematic.
When I reset it and relearn it, it is connected for a short time and then the connection breaks off.

**Comment by Smanar** [comment]
Ha ok, so not the same problem, harder.

**Comment by salopette** [comment]
Why closed?
Please add the device.

**Comment by Smanar** [comment]
It's a bot that close issue if no one is using it.

But ATM if the device can't be include in deconz, It's harder. You need something with a sniffer take a look on trafiic to see the problem

>When I reset it and relearn it, it is connected for a short time and then the connection breaks off.

**Comment by beneffm** [comment]
Hi all!
I also have the device here, experiencing the same issue. Is there any chance to get it running? How can I help :) ?

**Comment by paulmann1590** [comment]
The sirene is at the moment quite cheap available for 6 euros, so is there any chance to get it running? :)

**Comment by SwoopX** [comment]
The device is supported out of the box as far as I can tell. However. for the pairing to be successful, it is required to apply a configuration change in deconz GUI. For that, go to _Edit -> Network settings -> Endpoints_ (or press F9 -> Endpoints) and add `0x0502` to the `Out clusters` of endpoint 0x01.

![grafik](https://user-images.githubusercontent.com/4005212/79495160-75196d00-8024-11ea-949f-bab4e782d76d.png)

When the device has been paired, it is further (currently) required to manually enroll it to the coordinator. Again from deconz GUI, select the `IAS Zone` cluster of the device and enter the MAC address of your coordinator for attribute `IAS_CIE_Address` by double clicking on the value field (must be entered with a leading "0x"). If that is not done and the device looses power, it leaves the network and gets reset when connected to power again.

![grafik](https://user-images.githubusercontent.com/4005212/79511865-68a30d80-8040-11ea-8162-43fa1470ed8e.png)

**Comment by ebaauw** [comment]
> When the device has been paired, it is further (currently) required to manually enroll it to the coordinator.

@SwoopX you need to whitelist the device so a ZHAAlarm `/sensors` resource is created, for the REST API plugin will do the _IAS Zone_ enrollment.  Check the code for the Heiman siren.

**Comment by SwoopX** [comment]
@ebaauw Pretty sure it did that during the tests, but let me double check it again. Thanks for the hint. There's always one more place to whitelist...

**Comment by SwoopX** [comment]
> @SwoopX you need to whitelist the device so a ZHAAlarm /sensors resource is created, for the REST API plugin will do the IAS Zone enrollment. Check the code for the Heiman siren.

The reason actually was that the device is NOT IAS zone, but IAS warning device. The logic didn't handle that. It's fixed now and works smoothly.

**Comment by Greglog** [comment]
Hey guys,

I am trying to get the siren working. Its visible in the Phoscon App, but I am not able to switch on the siren - neither directly in the app nor via OpenHab. 
The strange thing is: on the setting page, when trying to change the name, it goes on and make the alarm-sound
Any ideas? What could I check?

**Comment by SwoopX** [comment]
It can be triggered via REST API only and works with values select and lselect on parameter alert for the lights resource.

**Comment by Greglog** [comment]
Ahh - thanks
It works...
