### ISSUE TITLE
lights unresponsive after power outage

### ISSUE THREAD

**Issue by andreibanaru** [dresden-elektronik/deconz-rest-plugin#2063]
Had a power outage and now all 10 lights from the living-room, hallway light and 3 lights from bathroom no longer respond. Kitchen and 3 more from bedroom seem to work just fine.

Don't want to do manual reset on 14 lights. What else can be done?

![image](https://user-images.githubusercontent.com/38393163/68622364-a5d80200-04da-11ea-9194-5980f53ef1c5.png)

**Comment by manup** [comment]
Have you tried to power-cycle the affected lights?

A reset shouldn't be needed, since devices store all network parameters.

**Comment by andreibanaru** [comment]
Yes, no changes. I find it weird since this happened per room basis.

**Comment by andreibanaru** [comment]
> Have you tried to power-cycle the affected lights?
> 
> A reset shouldn't be needed, since devices store all network parameters.

Could bringing the Tradfri switch close to the light bulb push the settings again?
