### ISSUE TITLE
can't get rid of group0

### ISSUE THREAD

**Issue by WladyX** [dresden-elektronik/deconz-rest-plugin#2065]
Hello,
When I installed conbee2 for the first time i skipped the group creating phase and so I got Group 0, to which i added some lights.
I reset to factory defaults the conbee2, but those xiaomi lights are subborn and do not want to move out of group 0.
I've used the rest API to remove the groups from the lights, it kinda worked for a while, but when I got a power outage the switches remembered group 0 and so they are back in group 0.
Please help me get rid of this group. The other switches that I did not add manually to group 0 are not visible there, but the ones I added initially are there whatever steps i take.
If I reset the conbee2 to factory defaults that means that the group got stuck on the switch itself? Any ideea how to reset it? Seems pairing (hold a button for 5s until the led starts blinking) does not remove the group bit.
Thank you for the great work you are doing.

**Comment by WladyX** [comment]
![image](https://user-images.githubusercontent.com/1106868/68668734-8cbe6800-0551-11ea-992b-f802054d8ff8.png)
![image](https://user-images.githubusercontent.com/1106868/68668827-bf686080-0551-11ea-882f-b2ffe09dbf51.png)

**Comment by Exhortae** [comment]
Hi,

I have the same problem, I tried adding a new aqara switch (same as poster) with neutral wire. And I got this Group 0 that I can't delete. Also the left gang has been added as a light in group 0 and I also cannot remove it.

**Comment by BrianPuccio** [comment]
I ran into the same problem when I added an Aqara plug to my collection of Ikea Tradfri plugs. No Group 0 until the Aqara was added, cannot get rid of it now.

**Comment by xxLeoxx93** [comment]
Same issue here!

**Comment by jeanclode76** [comment]
Same here !!!!!!!!!!!!!!!!!!

**Comment by pawelbudynek** [comment]
same here

**Comment by smesguich** [comment]
Same issue Here #2679 but affecting all my devices :

> I've just check something strange. I'm mooving from my Legrand GW to Deconz and with an Aqara/LUMI Power Outlet, a "Group 0" is created but it's affecting all Legrand devices. As far as I can see in the IHM (Phoscon and old one), the Group 0 contain only the Aqara Device.

**Comment by Gerben321** [comment]
Same here after added some Ikea E27 lights.

**Comment by Smanar** [comment]
But you have problem with this group ?
You can't just ignore it ?

**Comment by Gerben321** [comment]
I get what you're saying, no I don't have a problem, yes I can ignore it. But really? That's no solution, it's not even a work-around. This is clearly some kind of bug that should be addressed and looked at. I understand it's no high priority issue but still. :)

**Comment by Smanar** [comment]
Yeah make something to make it invisble in phoscon.
But it can be more problematic on some users.

**Comment by skitzow88** [comment]
Well i worked arround this issue as follows using the rest api https://dresden-elektronik.github.io/deconz-rest-doc. 

- GET https://dresden-light.appspot.com/discover
- POST ip:port/api -> raw : { "devicetype": "my application" } -> get the username, this is your apikey you will use in the next step.
- ip:port/api/apikey/groups/0
- DELETE ip:port/api/apikey/groups/0

**Comment by Smanar** [comment]
But I have checked the code, it s not possible to delete the group.

>    if (!group || (group->state() == Group::StateDeleted) || (group->address() == gwGroup0))
    {
        rsp.httpStatus = HttpStatusNotFound;
        rsp.list.append(errorToMap(ERR_RESOURCE_NOT_AVAILABLE, QString("/groups/%1").arg(id), QString("resource, /groups/%1, not available").arg(id)));
        return REQ_READY_SEND;
    }


This procedure change something for you ?

**Comment by xxLeoxx93** [comment]
Not solved for me -> Should be still open!

**Comment by ebaauw** [comment]
`/groups/0` is a standard group containing all `/lights` resources.  Same as Hue API. You shouldn’t be able to delete it, nor add or remove lights to it.  Probably only bug is that when you try anyway, the API returns unclear error messages, or none at all.

**Comment by xxLeoxx93** [comment]
But why then is the group 0 not hidden then in phoscon?

**Comment by ebaauw** [comment]
That's a question for Phoson, not for the REST API Plugin.
