### ISSUE TITLE
Cluster marked as unknow

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#2069]
Hello, we are trying to include new device and whe have something strange.
 ![image](https://user-images.githubusercontent.com/25209236/68803156-7ef70880-065f-11ea-8dcb-57b1dcdf2939.png)

Clusters are good, but marked as unknow ! There is a bug during the pairing procedure.
Someone know a procedure to solve that ?

**Comment by ebaauw** [comment]
Looks like a missing or invalid `general.xml`.

**Comment by Smanar** [comment]
Arf, I thought about that but the manufacturer part is only for the cluster FC01, and is marked as "unknow" too, I thought the rest was standard.

It can't be an inclusion bug during the procedure  ?

**Comment by ebaauw** [comment]
Yep.  The cluster names and _Custer Info_ panel are populated from `general.xml`.  A single XML error causes the entire file to be ignored.

**Comment by Smanar** [comment]
Lol, right, it's exactly that.
