### ISSUE TITLE
Request Support Lightify Dimming Switch

### ISSUE THREAD

**Issue by warllo54** [dresden-elektronik/deconz-rest-plugin#2070]
Hoping to get support for these switches

https://consumer.sylvania.com/our-products/smart/product-info/zigbee/sylvania-smart-zigbee-2-button-dimming-switch/index.jsp

![image](https://user-images.githubusercontent.com/20650065/68815253-8eb32480-0640-11ea-9fb5-b308a6f642b5.png)

![image](https://user-images.githubusercontent.com/20650065/68815272-9e326d80-0640-11ea-9f98-5cd366516d61.png)

![image](https://user-images.githubusercontent.com/20650065/68815292-aab6c600-0640-11ea-8493-72c4f9526afe.png)

![image](https://user-images.githubusercontent.com/20650065/68815325-b86c4b80-0640-11ea-8f35-97069379db50.png)

![image](https://user-images.githubusercontent.com/20650065/68815340-c6ba6780-0640-11ea-8860-7f9fa0ccdbbc.png)

![image](https://user-images.githubusercontent.com/20650065/68815365-d46fed00-0640-11ea-871e-488b3e47ba59.png)

![image](https://user-images.githubusercontent.com/20650065/68815382-e05baf00-0640-11ea-9bdf-fb3ff494b177.png)

![image](https://user-images.githubusercontent.com/20650065/68815399-ed789e00-0640-11ea-9852-c3162ceffecd.png)

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
