### ISSUE TITLE
Download site no longer exist?

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#2080]
Hi Guys,

I've been using the URL under to download new version of deconz for windows. But the site dont exist anymore. Where to get the latest version now?

Used to use this one:
https://www.dresden-elektronik.de/deconz/win/

**Comment by Smanar** [comment]
try this one http://deconz.dresden-elektronik.de/win/

**Comment by PrimaryInc** [comment]
> try this one http://deconz.dresden-elektronik.de/win/

Thanks @Smanar :)
