### ISSUE TITLE
Compiled plugin does not start in hass.io docker container

### ISSUE THREAD

**Issue by jukmanty** [dresden-elektronik/deconz-rest-plugin#2081]
I'm trying to test deconz rest plugin changes by SwoopX

https://github.com/SwoopX/deconz-rest-plugin 

in my RPi 3B+ + Raspbee + Hass.io environment. Changes include support for my Develco sensors FLSZB-110 and MOSZB-130.

I was able to compile rest plugin with modifications to armhf architecture in raspbian/stretch docker container, but could not get it running with deCONZ. I modified official addon_core_deconz docker container https://github.com/home-assistant/hassio-addons/tree/master/deconz and altered run.sh script to copy compiled plugin to /usr/share/deCONZ/plugins/libde_rest_plugin.so Then I stopped and started container.

Phoscon webapp starts, but REST API does not. Requests to /api are routed to webapp and it responds in html <p>The file /api couldn't be found</p>. I cannot login to Phoscon app, it does not accept any password. Also if VNC server port is configured then docker container exits with error code at VNC server startup.

If I add dbg-error=1 to deCONZ parameters I can see from the logs some errors during plugin lookup:

```
2019-11-06T18:53:20.963558000Z 20:53:17:688 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
2019-11-06T18:53:20.963868000Z 20:53:17:781 sub element size does not match real size
... 40 similar rows removed ...
2019-11-06T18:53:20.976747000Z 20:53:20:761 sub element size does not match real size
2019-11-06T18:53:20.977036000Z 20:53:20:764 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
```

Can anyone assist how compiled plugin can be tested in my environment? I do not have separate linux installation for testing and I'm not very familiar with C++ and Linux/GNU tools.

**Comment by SwoopX** [comment]
Looks like you're not the only one #2052
