### ISSUE TITLE
Osram Smart+ Switch Mini support

### ISSUE THREAD

**Issue by henkkakay** [dresden-elektronik/deconz-rest-plugin#2082]
On the back of the switch, there are some details (model number?):
AC0251 100NJ | x 0218

The switch has 3 buttons, up (close to LED), centre/circle, down. Below is lists the long/short presses for each button. Screencaps show the info panels that I could find with possibly useful info.

===============

Down - short press:
02:34:45:661 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 191, rssi: -67

Down - long press:
02:40:02:070 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 191, rssi: -67
02:40:02:158 APS-DATA.indication srcAddr: 0xa5a1, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:02:159 ZCL attribute report 0x000B3CFFFEFAD82E for cluster 0x0008, ep 0x01
02:40:02:159 APS-DATA.request id: 225, addrmode: 0x02, addr: 0xa5a1, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:02:182 APS-DATA.indication srcAddr: 0x61c4, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:02:183 ZCL attribute report 0x000D6FFFFEAF9D14 for cluster 0x0008, ep 0x01
02:40:02:188 APS-DATA.request id: 228, addrmode: 0x02, addr: 0x61c4, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 2 len: 5 tx.options 0x00
02:40:02:212 APS-DATA.indication srcAddr: 0xfd84, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:02:214 ZCL attribute report 0x086BD7FFFE06BB89 for cluster 0x0008, ep 0x01
02:40:02:214 APS-DATA.request id: 232, addrmode: 0x02, addr: 0xfd84, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 3 len: 5 tx.options 0x00
02:40:02:251 APS-DATA.indication srcAddr: 0x0919, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:02:252 ZCL attribute report 0x086BD7FFFE065A7E for cluster 0x0008, ep 0x01
02:40:02:252 APS-DATA.request id: 235, addrmode: 0x02, addr: 0x0919, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 4 len: 5 tx.options 0x00
02:40:02:272 APS-DATA.indication srcAddr: 0x55bc, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:02:273 ZCL attribute report 0x000B3CFFFEF931EB for cluster 0x0008, ep 0x01
02:40:02:273 APS-DATA.request id: 238, addrmode: 0x02, addr: 0x55bc, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 5 len: 5 tx.options 0x00
02:40:02:321 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:02:322 0x14B457FFFE3208F1 level 254 --> 251
02:40:02:323 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:02:324 APS-DATA.request id: 241, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 6 len: 5 tx.options 0x00
02:40:02:410 APS-DATA.confirm id: 225, status: 0x00 SUCCESS
02:40:02:410 APS-DATA.confirm request id: 225 -> erase from queue
02:40:02:427 APS-DATA.confirm id: 228, status: 0x00 SUCCESS
02:40:02:427 APS-DATA.confirm request id: 228 -> erase from queue
02:40:02:489 aps request id: 225 finished, erase from queue
02:40:02:519 APS-DATA.confirm id: 232, status: 0x00 SUCCESS
02:40:02:519 APS-DATA.confirm request id: 232 -> erase from queue
02:40:02:533 APS-DATA.confirm id: 235, status: 0x00 SUCCESS
02:40:02:533 APS-DATA.confirm request id: 235 -> erase from queue
02:40:02:569 aps request id: 228 finished, erase from queue
02:40:02:610 APS-DATA.confirm id: 238, status: 0x00 SUCCESS
02:40:02:610 APS-DATA.confirm request id: 238 -> erase from queue
02:40:02:624 APS-DATA.confirm id: 241, status: 0x00 SUCCESS
02:40:02:624 APS-DATA.confirm request id: 241 -> erase from queue
02:40:02:679 aps request id: 232 finished, erase from queue
02:40:02:731 aps request id: 235 finished, erase from queue
02:40:02:809 aps request id: 238 finished, erase from queue
02:40:02:889 aps request id: 241 finished, erase from queue
02:40:03:234 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:03:235 0x14B457FFFE3208F1 level 251 --> 213
02:40:03:236 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:03:236 APS-DATA.request id: 250, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:03:302 APS-DATA.confirm id: 250, status: 0x00 SUCCESS
02:40:03:302 APS-DATA.confirm request id: 250 -> erase from queue
02:40:03:369 aps request id: 250 finished, erase from queue
02:40:04:238 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:04:239 0x14B457FFFE3208F1 level 213 --> 174
02:40:04:240 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:04:240 APS-DATA.request id: 3, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:04:293 APS-DATA.confirm id: 3, status: 0x00 SUCCESS
02:40:04:293 APS-DATA.confirm request id: 3 -> erase from queue
02:40:04:329 aps request id: 3 finished, erase from queue
02:40:05:005 Current channel 15
02:40:05:028 Device TTL 1087 s flags: 0x7
02:40:05:240 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:05:241 0x14B457FFFE3208F1 level 174 --> 136
02:40:05:241 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:05:241 APS-DATA.request id: 13, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:05:302 APS-DATA.confirm id: 13, status: 0x00 SUCCESS
02:40:05:302 APS-DATA.confirm request id: 13 -> erase from queue
02:40:05:385 aps request id: 13 finished, erase from queue
02:40:06:171 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 183, rssi: -68
02:40:06:253 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:06:254 0x14B457FFFE3208F1 level 136 --> 99
02:40:06:254 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:06:254 APS-DATA.request id: 24, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:06:347 APS-DATA.confirm id: 24, status: 0x00 SUCCESS
02:40:06:347 APS-DATA.confirm request id: 24 -> erase from queue
02:40:06:409 aps request id: 24 finished, erase from queue
02:40:14:549 APS-DATA.request id: 77, addrmode: 0x03, addr: 0x7cb03eaa0a0017cd, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x03 queue: 1 len: 5 tx.options 0x00
02:40:14:712 0x7CB03EAA0A0017CD error APSDE-DATA.confirm: 0xE1 on task
02:40:14:712 APS-DATA.confirm id: 77, status: 0xE1 

Down - long press #2:
02:40:55:446 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 191, rssi: -67
02:40:55:608 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:55:609 0x14B457FFFE3208F1 level 99 --> 96
02:40:55:610 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:55:610 APS-DATA.request id: 89, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:55:669 APS-DATA.confirm id: 89, status: 0x00 SUCCESS
02:40:55:669 APS-DATA.confirm request id: 89 -> erase from queue
02:40:55:689 aps request id: 89 finished, erase from queue
02:40:56:549 APS-DATA.request id: 97, addrmode: 0x03, addr: 0x7cb03eaa0a0017cd, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x03 queue: 1 len: 5 tx.options 0x00
02:40:56:702 APS-DATA.confirm id: 97, status: 0x00 SUCCESS
02:40:56:702 APS-DATA.confirm request id: 97 -> erase from queue
02:40:56:729 aps request id: 97 finished, erase from queue
02:40:56:745 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:56:745 0x14B457FFFE3208F1 level 96 --> 58
02:40:56:746 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:56:746 APS-DATA.request id: 101, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:56:799 APS-DATA.indication srcAddr: 0x7f6f, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 167, rssi: -70
02:40:56:799 ZCL got data for node=0x7F6F, cl=0x0006, at=0x0000, status=0x00, type=0x10
02:40:56:913 APS-DATA.confirm id: 101, status: 0x00 SUCCESS
02:40:56:914 APS-DATA.confirm request id: 101 -> erase from queue
02:40:56:970 aps request id: 101 finished, erase from queue
02:40:57:614 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:57:614 0x14B457FFFE3208F1 level 58 --> 19
02:40:57:615 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:57:615 APS-DATA.request id: 111, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:57:668 APS-DATA.confirm id: 111, status: 0x00 SUCCESS
02:40:57:668 APS-DATA.confirm request id: 111 -> erase from queue
02:40:57:689 aps request id: 111 finished, erase from queue
02:40:58:613 APS-DATA.indication srcAddr: 0x5378, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -52
02:40:58:614 0x14B457FFFE3208F1 level 19 --> 1
02:40:58:615 ZCL attribute report 0x14B457FFFE3208F1 for cluster 0x0008, ep 0x01
02:40:58:615 APS-DATA.request id: 120, addrmode: 0x02, addr: 0x5378, profile: 0x0104, cluster: 0x0008, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
02:40:58:663 APS-DATA.confirm id: 120, status: 0x00 SUCCESS
02:40:58:664 APS-DATA.confirm request id: 120 -> erase from queue
02:40:58:729 aps request id: 120 finished, erase from queue
02:40:59:616 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x02 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 191, rssi: -67

Up - short press:
02:37:47:341 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 175, rssi: -69
02:37:48:521 ZDP active ep request to 0x086bd7fffe06bb89
02:37:48:521 APS-DATA.request id: 72, addrmode: 0x02, addr: 0xfd84, profile: 0x0000, cluster: 0x0005, ep: 0x00 -> 0x00 queue: 1 len: 3 tx.options 0x00
02:37:48:521 ZDP send request id: 0x07 to 0x086bd7fffe06bb89
02:37:48:573 APS-DATA.confirm id: 72, status: 0x00 SUCCESS
02:37:48:573 APS-DATA.confirm request id: 72 -> confirmed, timeout 36486656
02:37:48:661 APS-DATA.indication srcAddr: 0xfd84, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8005, lqi: 255, rssi: -52
02:37:48:661 APS-DATA.indication request id: 72 -> finished
02:37:48:661 APS-DATA.request id: 72 erase from queue
02:37:48:661 ZDP status = 0x00 -> SUCCESS
02:37:48:661 ZDP active ep response for 0x086bd7fffe06bb89
02:37:48:661 	ep: 0x01
02:37:48:661 	ep: 0xF2
02:37:49:161 ZDP active ep request to 0x7cb03eaa0a0017cd
02:37:49:161 APS-DATA.request id: 76, addrmode: 0x02, addr: 0x7f6f, profile: 0x0000, cluster: 0x0005, ep: 0x00 -> 0x00 queue: 1 len: 3 tx.options 0x00
02:37:49:161 ZDP send request id: 0x07 to 0x7cb03eaa0a0017cd
02:37:49:253 APS-DATA.confirm id: 76, status: 0xE9 MAC_NO_ACK
02:37:49:358 APS-DATA.indication srcAddr: 0x7f6f, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8005, lqi: 167, rssi: -70
02:37:49:358 ZDP status = 0x00 -> SUCCESS
02:37:49:358 ZDP active ep response for 0x7cb03eaa0a0017cd
02:37:49:358 	ep: 0x03

Up - long press:
02:38:23:541 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 239, rssi: -61
02:38:24:374 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 175, rssi: -69
02:38:26:041 aps request id: 206 prf: 0x0000 cl: 0x0031 timeout (confirmed: 1) to 0x000D6FFFFEAF9D14 (0x61C4)
02:38:26:121 aps request id: 206 finished, erase from queue
02:38:26:520 Mgmt_Lqi_req zdpSeq: 121 to 0x000B3CFFFEFAD82E start index 0
02:38:26:521 APS-DATA.request id: 62, addrmode: 0x03, addr: 0x000b3cfffefad82e, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
02:38:26:650 APS-DATA.confirm id: 62, status: 0xE1 
02:38:26:897 APS-DATA.indication srcAddr: 0xa5a1, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -52
02:38:26:897 ZDP status = 0x00 -> SUCCESS
02:38:26:897 ZDP Mgmt_Lqi_rsp zdpSeq: 121 from 0x000B3CFFFEFAD82E total: 9, startIndex: 0, listCount: 3
02:38:26:897     * neighbor: 0x086BD7FFFE065A7E (0x0919), LQI: 159, relation: 0x02 rxOnWHenIdle: 1
02:38:26:897     * neighbor: 0x7CB03EAA00B20D1D (0x484C), LQI: 77, relation: 0x02 rxOnWHenIdle: 1
02:38:26:898     * neighbor: 0x14B457FFFE3208F1 (0x5378), LQI: 155, relation: 0x02 rxOnWHenIdle: 1
02:38:27:001 Mgmt_Lqi_req zdpSeq: 123 to 0x000B3CFFFEFAD82E start index 3
02:38:27:001 APS-DATA.request id: 67, addrmode: 0x03, addr: 0x000b3cfffefad82e, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
02:38:27:056 APS-DATA.confirm id: 67, status: 0x00 SUCCESS
02:38:27:056 APS-DATA.confirm request id: 67 -> confirmed, timeout 36754728

Up - long press - second time:
02:39:04:049 APS-DATA.request id: 44, addrmode: 0x03, addr: 0x7cb03eaa0a002d42, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x03 queue: 1 len: 5 tx.options 0x00
02:39:04:118 APS-DATA.confirm id: 44, status: 0x00 SUCCESS
02:39:04:119 APS-DATA.confirm request id: 44 -> erase from queue
02:39:04:126 aps request id: 44 finished, erase from queue
02:39:04:315 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 255, rssi: -46
02:39:04:994 Current channel 15
02:39:05:017 Device TTL 1147 s flags: 0x7
02:39:06:049 APS-DATA.request id: 61, addrmode: 0x03, addr: 0x7cb03eaa00b20d1d, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x03 queue: 1 len: 5 tx.options 0x00
02:39:06:066 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 170, rssi: -48
02:39:06:138 APS-DATA.confirm id: 61, status: 0x00 SUCCESS
02:39:06:138 APS-DATA.confirm request id: 61 -> erase from queue
02:39:06:201 aps request id: 61 finished, erase from queue
02:39:06:234 APS-DATA.indication srcAddr: 0x484c, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -58
02:39:06:235 ZCL got data for node=0x484C, cl=0x0006, at=0x0000, status=0x00, type=0x10
02:39:14:049 APS-DATA.request id: 117, addrmode: 0x03, addr: 0x7cb03eaa0a002d42, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x03 queue: 1 len: 5 tx.options 0x00
02:39:14:101 APS-DATA.confirm id: 117, status: 0x00 SUCCESS
02:39:14:102 APS-DATA.confirm request id: 117 -> erase from queue
02:39:14:121 aps request id: 117 finished, erase from queue

Centre/Circle - short press:
2:36:56:594 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0008, lqi: 175, rssi: -69
02:36:57:591 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0300, lqi: 167, rssi: -70

Centre/Circle - long press:
02:41:38:209 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0300, lqi: 170, rssi: -47
02:41:39:203 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0300, lqi: 255, rssi: -47
02:41:41:200 APS-DATA.indication srcAddr: 0x613d, srcEp: 0x03 dstAddrMode: 2, profile: 0x0104, cluster: 0x0300, lqi: 255, rssi: -50

===================================

![Node Info](https://user-images.githubusercontent.com/11836264/69000886-ae677880-08de-11ea-8c8a-7129f6785f1d.jpg)
![01-basic cluster](https://user-images.githubusercontent.com/11836264/69000887-ae677880-08de-11ea-8a49-f89db0441374.png)
![01-poll control](https://user-images.githubusercontent.com/11836264/69000888-af000f00-08de-11ea-80b8-eaf2eca4e57f.png)
![01-power config](https://user-images.githubusercontent.com/11836264/69000889-af000f00-08de-11ea-8ca4-bd7b41ae784f.png)
![02 -basic](https://user-images.githubusercontent.com/11836264/69000890-af000f00-08de-11ea-92f4-129a93504376.png)
![03-basic](https://user-images.githubusercontent.com/11836264/69000891-af000f00-08de-11ea-85f0-1e2bc4cca24c.png)
![Node Clusters](https://user-images.githubusercontent.com/11836264/69000892-af98a580-08de-11ea-82a7-d9c0a3c37ba1.png)

**Comment by henkkakay** [comment]
Appears to be similar to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1893

**Comment by danzbox** [comment]
And also https://github.com/dresden-elektronik/deconz-rest-plugin/issues/294
and I don't get the lack of support. This is not some unpopular noname sensor but from Osram Smart+ Series. 
@manup in #294 there is already a link to the solution by kkoenig. What is needed from the Community to add support of this switch.

**Comment by alloro72** [comment]
How to use the switch mini without zigbee2mqtt?

**Comment by henkkakay** [comment]
whats the etiquette for "up" in github? Anyway - this is still relevant

**Comment by hensoko** [comment]
👍

**Comment by alloro72** [comment]
Please add support to Osram Switch mini on Deconz
Thank you

**Comment by capellavacancies** [comment]
I can see this switch on deconz but can't see it in phoscon app

**Comment by Larx** [comment]
Please support this device. It is a low-price solution from a major manufacturer with the selling point of being kind-of semi-outdoor usable.

**Comment by jlangebek** [comment]
Please add support to Osram Switch mini on Deconz
Thank you

**Comment by jeanclode76** [comment]
Hello,
yes please add support to Osram+ Switch mini on Deconz !
Thanks

**Comment by Florian-Schmidt** [comment]
Hello, 

already voted for Osram 4 button switch but I would appreciate Osram Smart+ Switch also! please add these switches.

**Comment by olicooper** [comment]
I've waited 2 years for support, is there a guide to follow to add support ourselves?
I don't quite understand where the lack of support lies - is it in the rest plugin, deconz firmware or the core application? There isn't enough documentation to be able to understand and fix this ourselves imo.
Can we suppress the button controlling all lights via the GUI?

**Comment by Larx** [comment]
I'd like to support, too, but as nobody "official" seems interested in this issue, I'm lacking the knowledge where to start.

**Comment by Florian-Schmidt** [comment]
It's strange that nothing happens from deconz side on the issues. I'm watching two issues linked other issues, seems that there are enought persons who want to use Osram components with deconz. 

The other issue is #374 

@olicooper These repositories are interesting as they provide python scripts to handle Osram mini switch and 4 button switches. I hadn't found them yet.
The 4 button switch repository (chalford-st) seems to work with home assistants zigpy integration (have seen this integration during last HA beta).
Until today I added all my devices via deconz (Phoscon WebGUI) and I didn't try home assistant zigpy yet. Perhaps this could be an option and/or using these repositories as custom_components.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open! 

Continue in #2763
