### ISSUE TITLE
Add support for Elko Thermostat

### ISSUE THREAD

**Issue by corvy** [dresden-elektronik/deconz-rest-plugin#2088]
I have one of these thermostat installed and successfully paired with Deconz. But I cannot control it in any way (I understand at least). So I can give you the data I have on this devices. 

[http://proff.elko.no/getfile.php/13124148/produkter/doc/EKO05680/Datasheet4523430.pdf](url)

![Screenshot 2019-11-18 08 12 05](https://user-images.githubusercontent.com/138292/69032053-eaccce80-09db-11ea-945f-4c04c52180fd.png)

![Screenshot 2019-11-18 08 10 50](https://user-images.githubusercontent.com/138292/69032068-eef8ec00-09db-11ea-92d4-58d71f0189f8.png)

![Screenshot 2019-11-18 08 12 51](https://user-images.githubusercontent.com/138292/69032082-f4563680-09db-11ea-87dc-b69a424fce27.png)

![Screenshot 2019-11-18 08 13 12](https://user-images.githubusercontent.com/138292/69032088-f91aea80-09db-11ea-85a4-c83a6b8ee5c5.png)

![Screenshot 2019-11-18 08 13 27](https://user-images.githubusercontent.com/138292/69032093-fd470800-09db-11ea-9ddf-a3f621e59197.png)

**Comment by ebaauw** [comment]
You should be able to set the target temperature by writing the _Occupied Heating Setpoint_ attribute 0x0012.  The _Local Temperature_ attribute 0x0000, reports the current temperature.  It doesn't look like the thermostat provides much more functionality.

You might want to check if you can create a binding from the _Thermostat_ cluster to the RaspBee/ConBee and setup reporting for the above attributes.

As thermostats are expose as `/sensors` resources, the device needs to be whitelisted for support by the REST API plugin.  For that, we'd need a screenshot of the _Node Info_ panel with the _Manufacturer Code_.

**Comment by corvy** [comment]
Grand, then I could create a simple REST API integration from Home Asssistant to control it. I think I will be able to do that. The screenshot of Node Info: 

![Screenshot 2019-11-19 08 40 34](https://user-images.githubusercontent.com/138292/69126383-6300c600-0aa8-11ea-881b-b6190e2efad5.png)

**Comment by corvy** [comment]
![Screenshot 2019-11-19 08 50 04](https://user-images.githubusercontent.com/138292/69126943-9db72e00-0aa9-11ea-933b-e7f8f589d25a.png)

![Screenshot 2019-11-19 08 45 20](https://user-images.githubusercontent.com/138292/69126998-b6274880-0aa9-11ea-8b2a-3a035b4f48e1.png)

Seems it has some more functionality :)

**Comment by ebaauw** [comment]
I’ve got no clue what that does.

**Comment by corvy** [comment]
Ok, well I can try it out on the API and see what I get from it. You can now whitelist it? Any way I could patch my install or does it require compilation?

**Comment by corvy** [comment]
I think this has been added here: 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1291
