### ISSUE TITLE
add automatic polling aqara curtain motor

### ISSUE THREAD

**Issue by daddvok** [dresden-elektronik/deconz-rest-plugin#2089]
If you manually pull the curtains, the motor does not automatically give a new state, but if you count the cluster window covering, then the state is updated to the correct. Please add automatic polling of this device

**Comment by pitikay** [comment]
I would love to see something like this implemented, my IKEA Fyrtur automatically updates its position every second or so, while the aqara motor needs around 5 minutes to send me an updated position (open/closed) sometimes! Can I somehow make a script that simply polls the current position every second?

**Comment by Mimiix** [comment]
It seems this issue is resolved. If it is not, please re-open or create another issue.
