### ISSUE TITLE
Ecozy radiator valve

### ISSUE THREAD

**Issue by twansevriens** [dresden-elektronik/deconz-rest-plugin#209]
Does anyone have any experience with the zigbee ecozy (ecozy.de) thermostat?

**Comment by mshli** [comment]
I have the same issue. I am using deconz with a raspbee module and i want to connect some eCozy valves. Does anybody have a solution?

**Comment by ebaauw** [comment]
From their manual:
> eCozy is compatible with ZigBee home automation profile 1.2, and can therefore, operate with smart home platforms like Qivicon or Almond and many others (please contact  support@ecozy.de  for more information).

You could mail them and ask for technical documentation (which endpoints/clusters does the thermostat support?).

**Comment by mshli** [comment]
I send the email to ecozy, but i‘m still waiting for an answer. 
I found this (https://github.com/ckpt-martin/SmartThings) here on github. It‘s a plugin to integrate ecozy thermostate valves into an Samsung smartThings Hub. Maybe it helps for developing.

**Comment by mshli** [comment]
I got something from eCozy. I hope, it's the right thing. With the implementation i definitly need your help.

[eCozy_thermostat_List_of_clusters_and_attributes.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/1772919/eCozy_thermostat_List_of_clusters_and_attributes.pdf)

**Comment by mshli** [comment]
How do i add a new device?

**Comment by rygel** [comment]
I would also be interested in support for these Thermostatic Radiator Valves. They are currently available in Germany for little money.

**Comment by ebaauw** [comment]
That will be a huge change, impacting at least de_web_plugin.cpp, sensors.cpp, rest_sensors.cpp, and database.cpp.  Probably also bindings.cpp and various .h files.  There’s currently no support in the REST API for the 0x0200 and 0x0204 clusters.  As it’s battery powered, you probably need to use `config.pending` or something similar to collect changes until the device is awake.

Not even sure if we’d want to expose the radiator valve as a `/sensors` or a `/lights` resource.  See also the discussion on Keen vents, #269 and the Heiman Siren, #404.

**Comment by mshli** [comment]
OK. Thanks for the information. What do you think how long does it takes to implement de ecozy's? Do you need weeks, months or years?

**Comment by mshli** [comment]
Did you find a solution for integrating the radiator valves? Any advances?

**Comment by Jasonthefirst** [comment]
I would be interested in this too. 
I am not so good in integrating it myself.

**Comment by ethologus** [comment]
Is there a way to use ecozy with deconz?

**Comment by simonbove** [comment]
Anything new about this or other radiator valve?
