### ISSUE TITLE
Xiaomi Bewegunsmelder mit fehlerhaftem Batteriestatus

### ISSUE THREAD

**Issue by Uwe1984** [dresden-elektronik/deconz-rest-plugin#2093]
Der Batteriestatus Meine 5 Sensoren bleibt immer bei 100%.
Ich habe einige davon bereits ein Jahr und da kann der Status nicht stimmen.
Ein korrekter Status wäre gut um die Lebensdsuer einschätzen zu können und frühzeitig zu reagieren. 
Andere Xiaomi Batteriewerte ( Temp. )werden richtig angezeigt.

![Anmerkung 2019-11-19 220451](https://user-images.githubusercontent.com/45272859/69186343-a4c95500-0b18-11ea-8237-c3b08212f660.png)

**Comment by Smanar** [comment]
It's something normal, the device send a battery voltage, so Deconz make a convertion to a percentage.
It's the normal working mode for a battery. 
You have just buy the battery : 13.5V
One year later : 12V
6 mont later : 10 V
1 month later 4V.

A battery discharge is not something regular. You can have 100% for 1 year, and the device go to 95% to 50% in 1 month.

**Comment by Uwe1984** [comment]
Thank you for your answer. I can understand that and will observe it for a while. I had other values with the CC2531 Zigbee Stick. That's why I thought it was a issue
