### ISSUE TITLE
Add Support for Livolo TI0001 Switch

### ISSUE THREAD

**Issue by Olepir** [dresden-elektronik/deconz-rest-plugin#2096]
Is it possible to add support for Livolo TI0001 Switch?
It uses some kind of custom Zigbee protocol

https://github.com/Koenkk/zigbee2mqtt/issues/592

**Comment by Cyrille63** [comment]
Is it possible to add support for Livolo switches ?

**Comment by MOE-JOE2** [comment]
+1 here

**Comment by Smanar** [comment]
There is someone that can compile the code for some tests ?

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2036

**Comment by Cyrille63** [comment]
I can do that, is there a procedure to compile ?

**Comment by Cyrille63** [comment]
I have install a linux machine - Lubuntu 18.04.04 - deCONZ is working - I have installed hte development package, compilation is OK

I can do test

**Comment by Smanar** [comment]
Lol, choose an issue, you don't need to post on both I receive double notification.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
