### ISSUE TITLE
Phoscon App als localhost keine Gateway Anzeige

### ISSUE THREAD

**Issue by JBSullivan** [dresden-elektronik/deconz-rest-plugin#2097]
Ich habe das Problem, wenn ich die Phoscon App an dem Rechner aufrufe, wo der ConBee2 Stick drin steckt ( localhost oder 127.0.01.), ich kein Menü für das Gateway angezeigt bekomme. Auch wenn ich die Netzwerk IP Adresse dieses Rechners am selben PC aufrufe, ist kein Menü für das Gateway zu sehen.

Rufe ich aber die Netzwerk IP des Rechner wo der Stick drin steck über einen anderen PC aus dem gleichen Netzwerk auf, bekomme ich das Gateway Menü angezeigt.

Zum Einsatz kommt die letzte deConz Version (2.05.71)

![2019-11-20 15_19_37-Window](https://user-images.githubusercontent.com/44617472/69247313-814eea80-0baa-11ea-96ae-f8fea99c9159.png)

**Comment by manup** [comment]
Hmm, this should work with localhost and 127.0.0.1.
Which browser is that?

Does the address http://127.0.0.1/pwa yield any Javascript errors in the browser developer console (F12)?

**Comment by JBSullivan** [comment]
Browser is Edge in Version
![2019-11-20 19_44_20-Window](https://user-images.githubusercontent.com/44617472/69267807-321ab100-0bce-11ea-95a9-56ab95e57ba8.png)

No erros in the console, but hier is a screenshot of some warnings if i had followed the Gateway Link

![2019-11-20 19_42_47-Window](https://user-images.githubusercontent.com/44617472/69267808-321ab100-0bce-11ea-8f23-1fd4300ac017.png)

**Comment by manup** [comment]
Looks like the have some tricky HTML brackets here which this version of Edge doesn't parse. I'll put that on the todo list to check.

Can you please try with another browser or a recent Edge version (this here seems to be from 2018).

**Comment by JBSullivan** [comment]
That`s (maybe) the next Problem - if i try annother Browser on the same PC (Chrome, Firefox) i MUST set a new Password. If i use the same Password i used at the Edge Browser there is no login possible.

**Comment by b2un0** [comment]
relates to #2106

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
