### ISSUE TITLE
Request Support for Develco Heat Alarm (HESZB-120)

### ISSUE THREAD

**Issue by tyr84** [dresden-elektronik/deconz-rest-plugin#2100]
Develco smoke detector (SMSZB-120) is allready supported. Looks like the heat alarm is more or less the same device.

It can be added as of now, however it seems like only the "switch" is recognised by phoscon. There should also be a binary sensor (smoke/heat detected) and a temperature sensor.

![image](https://user-images.githubusercontent.com/27015255/69270562-752b5300-0bd3-11ea-91e1-e7f244579d6e.png)
![image](https://user-images.githubusercontent.com/27015255/69271477-39918880-0bd5-11ea-8bfa-a94ca550fc66.png)
![image](https://user-images.githubusercontent.com/27015255/69271567-5a59de00-0bd5-11ea-8e0a-b7c7ac5fcee7.png)

[Technical manual](https://www.develcoproducts.com/media/3372/heszb-120-technical-manual-heat-alarm.pdf)

**Comment by SwoopX** [comment]
Jep, from the cluster perspective, it looks identical. I can take care of integration, but it will probably take a week or two...

> It can be added as of now, however it seems like only the "switch" is recognised by phoscon. There should also be a binary sensor (smoke/heat detected) and a temperature sensor.

This one is on Phoscon. It needs to be implemented seperately. I'd also love to see the sensors popping up.

OT: Damn, I don't get why for all other sensors than the smoke the manufacturer code is read. I'd assume pairing went smoothly without any tricks? Would love to understand the differences then.

**Comment by tyr84** [comment]
yep, went smooth. I got a feeling it might be some firmware issue on the smoke detectors themselves

**Comment by SwoopX** [comment]
Thanks, thought so. Pretty sure I finally got the reason why. If I'm right, it's literally on incorrectly set bit causing all the trouble (for the smoke sensors)

**Comment by SwoopX** [comment]
Just updated the open pull request for this device ;)

**Comment by SwoopX** [comment]
@tyr84 is the device working ok?

**Comment by SwoopX** [comment]
#3775
