### ISSUE TITLE
Pi with Deconz always goes offline at night

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#2105]
Hello, I since the last update ... 71 the problem that my pi is not in the evening in the network, about 20 clock. Only a restart helps.

PS: I connected it via LAN cable

**Comment by Smanar** [comment]
Hi, but the problem can come from your system, not from deconz. You are using the SD pre-installed with deconz ?

Deconz is still running ? To check if it's the whole system that is freezeing or only network problem.

Can you enable Wifi to make tests with it ?

Can you see it on your router admin page when it was offline ?

**Comment by salopette** [comment]
I have wlan switched paralell now, and since few days no problem. Do not know what that is.
