### ISSUE TITLE
Strange issue with IKEA Tradfri ON/OFF (Dimmer) Switch CB10

### ISSUE THREAD

**Issue by dasFelix** [dresden-elektronik/deconz-rest-plugin#2107]
I am running deCONZ rest-API v2.5.71 (Beetlejuice) with conbee II on a raspberry PI 4+.

I tried to add a brand-new never added before IKEA on/off switch (aka small dimmer switch):
![image](https://user-images.githubusercontent.com/4163534/69374865-53030500-0ca7-11ea-9b3f-e7b5fa9f4736.png)

I tried to add it in phoscon web-gui by "adding Switch" => "other". Nothing happened, connection failure - seems not to work. After a few tries I had a look into deconz-gui. There I found the added switch. I removed that node and tried again several times - but always with the same result. 
Then I tried a 2nd brand-new, never added before switch. But also the same result again. They never shows up in phoscon, but always in deconz-gui.

But the **really strange thing** is the following... 
In the overview of phoscon web-ui (main page), where you see all groups and lights/plugs of selected group the added IKEA dimmer switch seems to switch ON/OFF all of the lights/plugs when switch is pressed. So the bulbs  go to grey state if you switch OFF and according to press ON they become a yellow state. This is just _"virtually"_ , the lights do not really switch on or off. After some seconds the lights on web-gui are going back to their real state one after each other. It does NOT really switch ON or OFF the lights / plugs but phoscon shows up like this. 

I tried also to restart "deconz-gui" and also to reboot the PI 4+. But the behaviour was the same. Just to note: I never added this switch (or any other of them) before nor did I connected a switch to "all of my devices". 

Like this it´s not useable with this behaviour of course. I like to provide further necessary information when I know what could help. Any help on this is really appreciated. Thank you in advance.

**Comment by olemr** [comment]
Have you tried using the old WEB App?
I had to assign lights to the Open/Close switch in there:
![image](https://user-images.githubusercontent.com/28068256/69385918-3673c680-0cc1-11ea-994f-5046006dfb7b.png)

**Comment by dasFelix** [comment]
Interesting. I didn´t even know this exists. But the switch does not show up in the "old" version. I can´t bind it there either. I deleted it in deconz-guy before try to bind. But no success :(

**Comment by marcelkordek** [comment]
I'm using v2.5.71 (Docker) on my Synology. I have multiple Ikea ON/OFF switches and they work great. After first Pairing attempt they appear in the GUI and Web App (new and old).

**Comment by dasFelix** [comment]
That's nice it's working for you. I know from other posts that normally this on / off button may be working. But for me it's not working at all :-/
Not the pairing process is a problem. This always works but the device seems not to be recognized correctly.
The phoscon web-ui fails after 3 minutes by time out. But always an object / node apears in deconz-gui. All the attributes makes no real sense to me:
![2019-11-22 11_52_21-Start](https://user-images.githubusercontent.com/4163534/69420494-1246d280-0d1f-11ea-9b6f-5755c2ab2096.png)
![2019-11-22 11_52_45-Suche](https://user-images.githubusercontent.com/4163534/69420502-17a41d00-0d1f-11ea-98ba-46d6cd8338b9.png)
As you see "factory defaults" to device fails also. 

Meanwile I tried another dozen times to get it working. I also tried going back to 2.5.69 with no success. 

I tried to pair other devices (2 Ikea tradfri LED color bulbs, 2 Ikea range extender) which works without any issue. 
I also removed and paired again a xiaomi aqara wall switch. This also works...

Only this tiny on/off switch refuses to work for me. I don't know what may cause this. Maybe the added a new firmware. Since I have no tradfri - gateway I cannot check this.

**Comment by dasFelix** [comment]
Little update
Probably I just didn't wait long enough. But I can read some node information. Seems to be logic to me. 
![2019-11-22 12_19_55-Suche](https://user-images.githubusercontent.com/4163534/69421933-a7979600-0d22-11ea-8005-13334987dc36.png)
Maybe a newer version? Date seems to be 4th of October 2019 ... hmm

Software Infos from OTAU Cluster info:
![2019-11-22 12_19_15-Suche](https://user-images.githubusercontent.com/4163534/69421991-cc8c0900-0d22-11ea-8680-80b20f9e597a.png)

**Comment by robidog** [comment]
NB: Zigbee standard specifies datecode in  ISO8601 format, i.e. YYYYMMDD. Therefore it's 10th of April, 2019.

**Comment by thowi** [comment]
I had to try ~10 times to pair the on/off switch. Eventually, it worked.

**Comment by IDmedia** [comment]
I have the same issue with the "TRADFRI open/close remote" which I guess is basically the same as this. The only difference is that there's a Sun/Three lines instead of I/O.

The scan and web UI does not show any new switches when trying to pair it, but I can see it using VNC (I'm using the HASSIO docker container) and I can see its events in Home-Assistant. It's just not listed in the Phoscon UI or old UI.

**Comment by ebaauw** [comment]
The open/close remote is *very* different from the on/off switch.  It sends _Window Covering_ commands instead of _On/Off_ and _Level Control_ commands.

**Comment by IDmedia** [comment]
> The open/close remote is _very_ different from the on/off switch. It sends _Window Covering_ commands instead of _On/Off_ and _Level Control_ commands.

Thanks for the info. Is there any way of getting it to show up in the Phoscon UI?
It seems to work well apart from not showing up...

**Comment by ebaauw** [comment]
Phoscon is not open source; dresden elektronik needs to change it themselves.

**Comment by mastervol** [comment]
I have the same problem as described in the the opening post.

ConBee II on Raspberry 2
Version: 2.05.75/8.3.2020
Firmware: 26580700

I cannot add a Ikea Tradfri On/Off Switch, not as IKEA and not as OTHER.
It is not recognized in the phoscon app.

Thanks for comments.

**Comment by BenAndDevelopment** [comment]
I was able to add them, but not they right way I guess. I added them as on off switch but the UI didn't show it. Then I just closed the "add new" layer and there it was. But then I couldn't add it to any room as switch. So I switched to the old interface where I was able to add my blinds to it. Now they mostly work but it's kinda strange.

**Comment by slurpey** [comment]
Same here. Are there any other ways, it drives me nuts. I'm using in hassio the "deconz" link, then in gateway I try to add it. Nothing happens.
-is there a way to reset that on off switch to factory settings?
-is there any other action than pushing 4 times the pair button?
-people are talking about the old interface in this thread but where is that link?
The crazy part is that this was already paired and I deleted it because I wanted to change its name. Regrets....

**Comment by drbytes** [comment]
Here it gets added, I see it in the Switches tab but not in the overview where I would assign it lamps. So that blows, but I understand, Ikea is a super small company, very difficult to support every vendor out there.
Running latest everything on a conbeeII

**Comment by drbytes** [comment]
Here it gets added but in PWA I can't assign it lights.

**Comment by slurpey** [comment]
Just in case... If they show in phoscon, in HA, go to configuration, integration, the 3 dots next to phoscon and reload.

They do not typically show up under entities. They can only be reached by services.  (Use device as trigger)
`alias: ikea switch via phoscon
description: ''
trigger:
  - device_id: e7810661d9794914800560293e2d8c06
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
condition: []
action:
  - service: light.toggle
    data: {}
    entity_id: light.color_temperature_light_44
mode: single
`
And on the pairing, I find it handy to make a light turn on, off, brighter, etc at the same time phoscon is trying. Most of the time the interface doesn't find anything but once I close and check, it's paired...
It's a bit wizardry...

**Comment by drbytes** [comment]
What would be really nice is that they would appear on the left side on the main PWA page --like all the others, so I can assign lights to them.
