### ISSUE TITLE
Innr light strip not reacting to signals in .71, works in .70

### ISSUE THREAD

**Issue by magistra** [dresden-elektronik/deconz-rest-plugin#2110]
I have an Innr light strip (FL 130C) which has been working fine until I updated to version .71 a couple of days ago. It simply does not respond to any calls but it looks alive in phoscon (not grayed out). Downgrading deconz back to the previous version I ran makes the light strip work again. Also works after upgrading to the intermediate .70 release..

What can I do to help debug this?

**Comment by magistra** [comment]
Works in .70 too, so it seems to have broken in. 71.

**Comment by manup** [comment]
That's odd, can you please post a screenshot of the endpoint/cluster list of the light strip?

**Comment by magistra** [comment]
Is this what you need?

![Screenshot_2019-11-26_21-38-04](https://user-images.githubusercontent.com/25285639/69671816-15332180-1097-11ea-9361-8efa84c2fa4a.png)
![Screenshot_2019-11-26_21-39-21](https://user-images.githubusercontent.com/25285639/69671874-2b40e200-1097-11ea-8e99-63dd6838a939.png)

These are taken with the .70 release.
