### ISSUE TITLE
Getting unexpected error while aquiring api key

### ISSUE THREAD

**Issue by cheak1974** [dresden-elektronik/deconz-rest-plugin#2115]
Hi,

I pressed the Unlock Gateway Button and sent the following request:

curl http://127.0.0.1:8080/api/ -X PUT -d '{"devicetype": "test"}' | python -m json.tool

and getting the response:

[
    {
        "error": {
            "address": "/",
            "description": "unauthorized user",
            "type": 1
        }
    }
]

...but I expected to get an API Key back. Is there something wrong with my request?
Would it not be easier to generate an API Key in the WebApp which could be copied by the user?

regards

Chris

**Comment by cheak1974** [comment]
Ah, OK I changed the command to POST instead of PUT and it worked instantly. 
I close the issue, but maybe for new users aquiring the API Key via Web App would still be easier to understand. Maybe you could consider to change this in future version.

regards 
Chris

**Comment by ebaauw** [comment]
> Maybe you could consider to change this in future version.

You're creating a new resource (the whitelist entry), so POST is semantically correct.
