### ISSUE TITLE
No refresh firmware version

### ISSUE THREAD

**Issue by jasimancas** [dresden-elektronik/deconz-rest-plugin#2122]
I've updated the firmware of 2 Ikea controllers and an Osram plug, but I don't see the new versions on the Phoscon website.

![image](https://user-images.githubusercontent.com/15717847/69496446-8a092e80-0ed2-11ea-9a40-3d0606aad7ce.png)

And in the web:
![image](https://user-images.githubusercontent.com/15717847/69496450-968d8700-0ed2-11ea-88f6-223c15e9740e.png)

Same with controller:
![image](https://user-images.githubusercontent.com/15717847/69496472-c9377f80-0ed2-11ea-8b14-f234df1fbc21.png)

And the web:
![image](https://user-images.githubusercontent.com/15717847/69496475-d3597e00-0ed2-11ea-8d62-f0eedc631ffb.png)

Any idea?

**Comment by Smanar** [comment]
I think the API doesn't manage update return (and idk if if there is any). So to update the version in the API, try to re-include your device, without deleting it.
Or easier (harder with battery device), make phoscon in permit join, go on deconz, on the updated device, on the cluster 0000, and make a read attribute.

**Comment by hellcry37** [comment]
I have the same issue

**Comment by ebaauw** [comment]
> I think the API doesn't manage update return (and idk if if there is any).

Indeed.  The update is done by the (closed source) STD OTAU plugin, unknown to the REST API plugin.  The issue applies to all devices.

> make phoscon in permit join, go on deconz, on the updated device, on the cluster 0000, and make a read attribute.

When the device fingerprint has changed by the firmware upgrade (e.g. update from ZLL to ZigBee 3; new clusters), you also need to re-read the _Node descriptor_ and _Simple Descriptor(s)_ from the GUI.
