### ISSUE TITLE
Info Ikea LED1736G9 / LED1836G9

### ISSUE THREAD

**Issue by wes1993** [dresden-elektronik/deconz-rest-plugin#2125]
Hello can someone help me to know if this led lamp E27 is supported?

https://www.ikea.com/it/it/p/tradfri-lampadina-a-led-e27-806-lumen-intensita-regolabile-wireless-bianco-caldo-bianco-opalino-90408797/

Thanks a Lot
Stefano

**Comment by Flurkmark** [comment]
See #2062

**Comment by wes1993** [comment]
Thanks a lot for your reply!! Sorry but I can’t have find the issue when I opened this..
