### ISSUE TITLE
unable to join Kit Pro mation sensor from Konke 

### ISSUE THREAD

**Issue by adonno** [dresden-elektronik/deconz-rest-plugin#2132]
Hello I found these sensors, but I am unable to pair them in deconz  
http://www.ikonke.us/pro/kitpro/index.php#kitpro 
Have you ever seen those? will there be support for these? 

![image](https://user-images.githubusercontent.com/13216947/69668382-101ea400-1090-11ea-8057-7cb1ad6a4c89.png)

**Comment by Smanar** [comment]
IDK for this sensors, but from my memory konke don't work on all channel (15, 20, 25)

**Comment by adonno** [comment]
are these the chennels they work on ?

**Comment by Smanar** [comment]
Yep

**Comment by gijsje** [comment]
I can see this sensor being added to my VNC view of the network but if i try to add this it does not show in the phoscom app and the ofcourse it will not be added to Home Assistant.
Is there a way to solve this?

**Comment by adonno** [comment]
so I tried on all available channels and i was unable to join them

**Comment by amirthraj** [comment]
Is there any solution for this issue?
