### ISSUE TITLE
Hue Tap not working / not pairable again

### ISSUE THREAD

**Issue by michis0806** [dresden-elektronik/deconz-rest-plugin#2141]
Hi,

my Hue Tap hasn't worked since yesterday. None of the keys performs any function. When I decoupled the tap and wanted to reconnect it, I couldn't find that the "normal" dimmer is available under Switch > Philips, but the tap is grayed out.
<img width="673" alt="Bildschirmfoto 2019-11-28 um 20 47 08" src="https://user-images.githubusercontent.com/11705647/69829448-53a81800-1220-11ea-8c94-377e2cf0073e.png">

Does anyone have an idea how to fix this?

Thanks
Michael

**Comment by johanneswilm** [comment]
Same here. I was actually able to pair it by right clicking the philips tap image, clicking on "inspect" then removing the "disabled" from the class of that element. After that I could click it and pair it like any other switch. However, after setting it up, it seems like the buttons don't actually have any effect on anything.

Any clues, @manup ?

**Comment by johanneswilm** [comment]
Update: the switch is actually working now, so it seems to just be a minor issue with the web app adding that "disabled" class. I'm guessing it's something left over from testing, maybe?

**Comment by michis0806** [comment]
I used the "other" way to connect the Tap again and that worked...

**Comment by johanneswilm** [comment]
What is the "other" way?

**Comment by michis0806** [comment]
Add new switch => "Other" ;)
