### ISSUE TITLE
Cannot disable WiFi

### ISSUE THREAD

**Issue by tomasrudh** [dresden-elektronik/deconz-rest-plugin#2142]
I have deconz 2.05.66 running on a Raspberry Pi with Raspbian 10 Buster. I have WiFi disabled in /boot/config.txt. I have stopped deconz using systemctl stop deconz-wifi and disabled using systemctl disable deconz-wifi. Nevertheless, after a couple of days is deconz-wifi running again, filling syslog with error messages. Is there a way to permanently turn off deconz-wifi?

**Comment by Smanar** [comment]
You have perhaps your solution here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1738

**Comment by tomasrudh** [comment]
An update of deconz solved the problem with log spam. I have also disabled the daemon deconz-wifi because I do not use it, my resources are a bit sparse. I am curious as to why the daemon is enabled again automatically, and the daemon started.

**Comment by tomasrudh** [comment]
Is there any progress to this case? Anything I can do to turn off deCONZ WiFi?
