### ISSUE TITLE
.71 installer download not on web site?

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#2147]
Why is .71 not on deconz.dresden-elektronik.de/win/?C=M;O=D

and, oddly... always wondered why the download links were not posted on the git page... https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by Ltek** [comment]
@manup  ...    .71 has the Osram power-on default, I'd like to use that. Would appreciate if you can post the .71 Windows compiled installer. thx

**Comment by manup** [comment]
Hmm I need to check the upload script, something went wrong. The .71 exe is uploaded now.

>and, oddly... always wondered why the download links were not posted on the git page... https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

Indeed that would be useful, I'll add them later on.
