### ISSUE TITLE
How to pair a living colors gen 2 lamp

### ISSUE THREAD

**Issue by frankhommers** [dresden-elektronik/deconz-rest-plugin#2150]
I can't find a way to do this. How can I pair a living colors gen 2 lamp?

The lamp pairs fine via "Lamp Finder" with the Hue Bridge v2

**Comment by frittes** [comment]
I also would like to know. Is it possible with the remote?

**Comment by frankhommers** [comment]
Despite being stale, I'd still like to know!

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by jowallis** [comment]
I have the same issue and could not find a solution anywhere. 
Could somebody point me to the thread, that solved the issue or if not available maybe reopen this issue? 
Thank you.

**Comment by frankhommers** [comment]
I didn't find a way.
