### ISSUE TITLE
Sengled E13-A21 PAR38 bulb

### ISSUE THREAD

**Issue by donnacha** [dresden-elektronik/deconz-rest-plugin#2155]
Hi - looking to add device support for the above bulb (Sengled E13-A21 PAR38) with integrated motion sensor. Any help appreciated.

Bulbs do turn on and off via deConz, but no info from motion sensor or ability to toggle motion conditions on or off. 

Clusters:
![image](https://user-images.githubusercontent.com/471398/69909474-732d8380-1460-11ea-80c5-fd95417175a8.png)

Basic cluster:
![image](https://user-images.githubusercontent.com/471398/69909518-f2bb5280-1460-11ea-8e5c-d71fd5a329c7.png)

Scenes cluster:
![image](https://user-images.githubusercontent.com/471398/69909533-17172f00-1461-11ea-99d2-4f765812912d.png)

Metering cluster:
![image](https://user-images.githubusercontent.com/471398/69909552-4c238180-1461-11ea-975b-9d4a4c0c076b.png)

OTAU:
![image](https://user-images.githubusercontent.com/471398/69909558-7117f480-1461-11ea-9a1a-a73dad43b658.png)

**Comment by donnacha** [comment]
It appears SmartThings implements this product as 'Zigbee Dimmer with Motion Sensor' - see https://github.com/liurenju/buildsys-19-code/blob/0c61fc44f9a04bfa01e43e999cd3718a3d2a8199/smartThingsGroovy/zigbee-dimmer-with-motion-sensor.groovy

**Comment by ebaauw** [comment]
According to the `.groovy` file, it has an _IAS Zone_ cluster, presumably for the motion.  Can you try reading the _Simple Descriptor(s)_ in the deCONZ GUI (from the left drop-down button in the node).  After that. the 0x0500 cluster should appear.  If you write the mac address of the RaspBee/ConBee in the _IAS_CIE_Address_ attribute, you should get reports for motion, at least in the GUI.

**Comment by donnacha** [comment]
@ebaauw Just tried that - I get a countdown when I reset the node, but no further clusters that I can see.

![image](https://user-images.githubusercontent.com/471398/69920230-1c6c8c00-14ea-11ea-8533-f03c6eb449eb.png)

![image](https://user-images.githubusercontent.com/471398/69920234-27bfb780-14ea-11ea-916d-840f6c4d57b8.png)

**Comment by stevewull** [comment]
I, too, am using the Sengled PAR38 bulb and would like to access the motion and light sensors in Deconz (and through the integration to Home Assistant, which I use for automation).  My cluster info looks similar to donnacha's.

I tried your suggestion: turned on _read simple description_ and was able to see the 0x0500 cluster. I pasted the mac address of the _Conbee II_ into the _IAS_CIE_Address_. No change in the Phoscon App. I do not see the motion and light sensors.

![image](https://user-images.githubusercontent.com/46251961/76570204-13d50b80-6472-11ea-93ff-b0f3f715e04c.png)

![image](https://user-images.githubusercontent.com/46251961/76570227-1f283700-6472-11ea-85fd-4db260941aac.png)

**Comment by SwoopX** [comment]
Ok, can you read the IAS zone attributes and share a screenshot? In doubt, add the IAS CIE address as you did before and write that attribute, then issue a zone enroll request with the right zone type right above by pressing `exec`. That should trigger enrollment.

Read the IAS zone attributes again afterwards. It should hopefully report enrolled.
