### ISSUE TITLE
Unable to start GUI via RDP Xorg

### ISSUE THREAD

**Issue by jaddel** [dresden-elektronik/deconz-rest-plugin#2156]
When i enter `sudo service deconz-gui status`

i get the following output.

`
● deconz-gui.service - deCONZ: ZigBee gateway -- GUI/REST API
   Loaded: loaded (/lib/systemd/system/deconz-gui.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-12-01 12:20:59 CET; 28s ago
  Process: 4189 ExecStart=/usr/bin/deCONZ --http-port=80 (code=exited, status=1/FAILURE)
 Main PID: 4189 (code=exited, status=1/FAILURE)`

**Comment by Larsn1** [comment]
Have you stopped the deconz service before?

**Comment by jaddel** [comment]
yes

**Comment by jaddel** [comment]
i followed this guide to install the desktop since i was coming from a ligth img. 
https://www.az-delivery.de/blogs/azdelivery-blog-fur-arduino-und-raspberry-pi/raspbian-stretch-desktop-und-xrdp-nachinstallieren

Could this be the root of my problem?
