### ISSUE TITLE
Trying to POST APi-key returns "invalid Json" Error

### ISSUE THREAD

**Issue by bubffm** [dresden-elektronik/deconz-rest-plugin#2157]
Trying to connect to REST API via various Rest clients on MacOS without success.

When POSTing http://192.168.x.xx:80/api

i get;

`[
    {
        "error": {
            "address": "/",
            "description": "body contains invalid JSON",
            "type": 2
        }
    }
]`

Any idea?  The IP and port are definitely correct.

**Comment by bubffm** [comment]
Solved

**Comment by Vissertje1980** [comment]
I'm struggling with the same problem, what was your solution??

**Comment by Smanar** [comment]
What are the data you are posting with this command ?

**Comment by Vissertje1980** [comment]
I did someting wrong, i dit not send the body with the request. Yesterday i was able to get an api key :-)

**Comment by bubffm** [comment]
only saw this now.  That was actually also my error.  Missing body....

Am Do., 12. Dez. 2019 um 08:07 Uhr schrieb Vissertje1980 <
notifications@github.com>:
