### ISSUE TITLE
no api key required for websocket

### ISSUE THREAD

**Issue by mqtt-fan** [dresden-elektronik/deconz-rest-plugin#2169]
Hi all,

I tried the javascript sample from the deconz rest documentation.

It works very well, but the websocket can access the device without any authentication. 
How can I acitvate authentication?

**Comment by Smanar** [comment]
The websocket don't acess to device. It just permit deconz send notifications in real time for other applications. You can't make action on device with it.

But yes, ATM there is no authentification for it, so someone can connect to it to see the temperature in your living room, or if you have turn off the light.

**Comment by johanneswilm** [comment]
@Smanar That sounds like a really bad security issue. Is this open source so that others can fix it if Dresden Elektronik doesn't have the resources to do so?

**Comment by Smanar** [comment]
It depends on the point of view.

I was joking on my previous post ^^. For me using https is totaly useless too. The only security issue I can find is if someone use a door locker and using the api url with random apikey and it depend of your own security network, easy to securise.
You can publish your websocket on live streaming if you want, no danger for you.

I don't know their priorities, but for me there is lot of things more important than theses security issues.
