### ISSUE TITLE
Odroid N2 ARM64 

### ISSUE THREAD

**Issue by fle44** [dresden-elektronik/deconz-rest-plugin#2170]
Hi,

I'm running my smart home from an arm64 os system (the Odroid N2) with ubuntu 18 and with a soft called jeedom, I bought a conbee 2 USB and some zigbee sensors.

I just realize, as I'm trying to install it, that there is no arm64 deCONZ binary available.

Is there a way to run deCONZ on an arm64 system and to make it compatible with my software jeedom?

Or better have you planed to develop a arm64 library even in beta ?

Best regards

Thanks,

Franck

**Comment by manup** [comment]
There are .deb packages available for arm64.

http://deconz.dresden-elektronik.de/raspbian/alpha/

These can be installed as described briefly in:
https://github.com/dresden-elektronik/deconz-rest-plugin#precompiled-deconz-packages-for-manual-installation

**Comment by fle44** [comment]
Hello
 
Thank you, it works on debian strech but not with ubuntu 18...
 
Do you have a package for ubuntu 18 arm64 ?
 
best regards
 
Franck
 
 
 
 
> Message du 05/12/19 19:03> De : "Manuel Pietschmann" > A : "dresden-elektronik/deconz-rest-plugin" > Copie à : "fle44" , "Author" > Objet : Re: [dresden-elektronik/deconz-rest-plugin] Odroid N2 ARM64  (#2170)> >
> There are .deb packages available for arm64.
> http://deconz.dresden-elektronik.de/raspbian/alpha/
> These can be installed as described briefly in:> https://github.com/dresden-elektronik/deconz-rest-plugin#precompiled-deconz-packages-for-manual-installation
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2170?email_source=notifications\u0026email_token=AKGBMXDRMXLRL23AWRJAEC3QXE65DA5CNFSM4JVXBHEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGBSVGA#issuecomment-562244248", "url": "https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2170?email_source=notifications\u0026email_token=AKGBMXDRMXLRL23AWRJAEC3QXE65DA5CNFSM4JVXBHEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGBSVGA#issuecomment-562244248", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
