### ISSUE TITLE
Is it possible to compile on Windows?

### ISSUE THREAD

**Issue by mdolnik** [dresden-elektronik/deconz-rest-plugin#2172]
I am aware of the instructions on how to compile the development package [on the main page](https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only) but as it mentions, it is for linux only.

Is there any way to do this on the Windows version? Are there any existing instructions anywhere or is it even possible in the first place?

**Comment by smartypantsuk** [comment]
While possible, there doesn't seem to be any information on compiling for Windows unfrotunately, which seems bizarre... I'm not sure if it's more complicated or something. 

I did email Dresden about Windows compiling but I haven't received a reply to date.
I'd like to know why we can't, it seems a big limiting factor from my perspective, although I have literally just dusted off my linux system just to compile a plugin that I currently cannot even use on my fully fledged windows home automation system.
