### ISSUE TITLE
Senic Friends of Hue Smart Switch - no deconz_event ?

### ISSUE THREAD

**Issue by bedaes** [dresden-elektronik/deconz-rest-plugin#2176]
I just received some Senic Friends of Hue Smart Switches. I succesfully added them in Phoscon App. It's deteced as:

Vendor: PhilipsFoH
Product: Friends of Hue Switch

However, in appdaemon I don't receive any `deconz_event` events when pressing the buttons. When I run `deCONZ --dbg-info=1`and press any buttons there is no output. I would have expected something like `18:17:31:055 button 1002 Toggle` like on my IKEA remotes?

**Comment by bedaes** [comment]
Nevermind, I missed step 5 from here: https://phoscon.de/en/support#pairing-friends-of-hue-switch

**Comment by sildehoop** [comment]
hey I have the same problem, but i did do step 5 is it necessary to have a bulb in your house? because i can't put the switch in a group.

**Comment by sildehoop** [comment]
<img width="379" alt="Schermafbeelding 2020-02-10 om 12 01 14" src="https://user-images.githubusercontent.com/34340385/74144459-0c191180-4bfd-11ea-9b53-b953ccc56b16.png">

**Comment by sildehoop** [comment]
<img width="1665" alt="Schermafbeelding 2020-02-10 om 12 01 40" src="https://user-images.githubusercontent.com/34340385/74144489-1cc98780-4bfd-11ea-8f04-92dfe4c52977.png">

**Comment by sildehoop** [comment]
<img width="1665" alt="Schermafbeelding 2020-02-10 om 12 02 24" src="https://user-images.githubusercontent.com/34340385/74144538-3bc81980-4bfd-11ea-94f3-8c297b805d9b.png">
