### ISSUE TITLE
Coordinator unable to join network?

### ISSUE THREAD

**Issue by MrJanD** [dresden-elektronik/deconz-rest-plugin#2178]
Hi there!

First of all: I tried many Zigbee solutions before (HUE bridge, IKEA Gateway, Zigbee2MQTT) and now I got the ConBee II. Together with FHEM it seems to be working really great for over half a year and I thought I finally got the right solution. THANKS!!
But since a sudden power loss end of last week at night (woke up by a whole shining house with lots of light ;) ) it seems to be broken somehow. Similar problems like [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1596](url) do not really help in my case. 
I tried it with an USB extension cable, even though it worked before without any extension cable - noting changed. 
Updated deCONZ docker container - nothing changed.
Updated firmware although I got the latest - noting changed.
Even an empty, fresh docker container with no devices showed the same issue (weird: Channel and other settings seem to be the same as before, even though everything shall be up like new with no relics!?).
I was so desperate, I already bought another ConBee II USB gateway, maybe it's broken. 

However, I will try to fix the problem until the new one arrives... 
Attached you can find the log with activated info, APS, ZCL, ZDP and OTAU log flags. Moreover, the configuration with a blackened configuration screenshot and an extract of the docker-compose.yml

System: Raspberry PI 4 (4GB)
Raspbian Buster 10
deCONZ Docker Image marthoc/docker-deconz
Current deCONZ version: 2.05.71
GW firmware version: 0x26490700
I deactivated the WiFi interface on my PI. However, there are several other emitter in the vicinity with the ConBee II (Homematic HM-MOD-RPI-PCB, Rademacher DUOFern Stick). I unplugged them for a quick test, but it makes no difference.

Any help would be appreciated! Thanks in advance!

![config](https://user-images.githubusercontent.com/40394719/70355664-fee54c80-1872-11ea-9879-f4b77733a296.jpg)
[deconzOut.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/3933932/deconzOut.txt)
[DoCoEx.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/3933953/DoCoEx.txt)

**Comment by MrJanD** [comment]
As it turn out, it was a missing braid breaker on the power supply cable of the raspberry. 
Since it worked before and all of a sudden unscrutable behavior popped up, I expected it to be something similar. Homematic recommended to use a braid breaker when multiple RF solutions are in vicinity or even attached to the host PC. 
However, again great praise for your Zigbee solution and keep on the good work. :)

**Comment by robertlandes** [comment]
@MrJanD is this issue resolved for you? If yes could you please close it?

Thanks
