### ISSUE TITLE
Add support for ecosmart zbt-cctswitch-d0001

### ISSUE THREAD

**Issue by crazifyngers** [dresden-elektronik/deconz-rest-plugin#2181]
These are inexpensive remotes that come with ecosmart zigbee bulbs.  The bulbs are zigbee 3.0 and work with the default light component.  The remotes though are not recognized.  Attached are the cluster info.  Any chance of getting these added? Thanks!

![image](https://user-images.githubusercontent.com/3136615/70364345-2da2f900-185a-11ea-99b4-9655206fc0dd.png)
![image](https://user-images.githubusercontent.com/3136615/70364353-34317080-185a-11ea-9a51-4fe66c360128.png)
![image](https://user-images.githubusercontent.com/3136615/70364362-3bf11500-185a-11ea-83d7-1ac30657c2ab.png)

**Comment by crazifyngers** [comment]
here is a link to the actual light/remote with an included picture because apparently their product code does not list any results in google.

https://www.homedepot.com/p/EcoSmart-60-Watt-Equivalent-A19-SMART-LED-Light-Bulb-Tunable-White-Starter-Kit-1-Bulb-A9A19A60WESDZR1/310288335

**Comment by mbafford** [comment]
See my PR on zigbee2mqtt for a potential implementation guide: https://github.com/Koenkk/zigbee-herdsman-converters/pull/822

And the Home Assistant PR, which doesn't look to be attempting to sanitize the fairly random inputs from the remote.
https://github.com/dmulcahey/zha-device-handlers/pull/211/files

**Comment by thedannymullen** [comment]
I picked one of these up it didn’t pair in the version of deconz I had.  Curious is it supported in any beta releases currently?

**Comment by thedannymullen** [comment]
Any updates on whether this feature will be added?  Very curious!  I will probably also order another remote but hate throwing the few of these I have in the trash.  The bulbs integrate great with deconz.

**Comment by raz0rf0x** [comment]
I still have this problem with DeconZ. Is this issue going to be addressed?

**Comment by thedannymullen** [comment]
Which problem is it you are having?
