### ISSUE TITLE
Part of node is not visible in GUI.

### ISSUE THREAD

**Issue by AdamWeglarz** [dresden-elektronik/deconz-rest-plugin#2184]
Hi,

I have issue that part of node is not visible in GUI. They are available on phoscon and works correctly with external systems (I use domoticz)
Using latest deconz version and latest Conbee FW
![obraz](https://user-images.githubusercontent.com/45738893/70374724-3812d080-18f6-11ea-9c94-2bd9a505f250.png)
![obraz](https://user-images.githubusercontent.com/45738893/70374818-4f05f280-18f7-11ea-98c0-7e90a7482fe3.png)
I am missing for example this device.

![obraz](https://user-images.githubusercontent.com/45738893/70374793-15cd8280-18f7-11ea-8f9f-dc8be2c4ce1f.png)

Any hint why?

Adam

**Comment by Smanar** [comment]
Can you take a look in the api, to have the MAC adress of this device ?
Something like http://<deconz_ip>/api/<api_key>/sensors

You can just have diffrent name.

**Comment by AdamWeglarz** [comment]
In API there are all devices and I expected that as they all work correctly in domoticz.

**Comment by Smanar** [comment]
Try to change the name in Phoscon, take a look if another device name haven't changed in deconz.
You can see too the name changement in domoticz logs, with more info, mac adress, previous name, ect ...

**Comment by AdamWeglarz** [comment]
On domoticz everything is perfectly perfect. Issue is on GUI of deconz.

**Comment by Smanar** [comment]
I m not saying something is wrong on domoticz.
I m saying "you need the mac adress to reconize the device and check if it's realy not in deconz" and I give you some way to have this adress.
