### ISSUE TITLE
deconz phoscon raspbee update not possible

### ISSUE THREAD

**Issue by overdrive69** [dresden-elektronik/deconz-rest-plugin#2188]
Hi, i tried to update via phoscon webinterface from 26050500 to 26330500.
The update starts, but after the update it shows again the old firmware.

<img width="670" alt="Anmerkung 2019-12-08 172921" src="https://user-images.githubusercontent.com/8517462/70392472-be0b4600-19e0-11ea-8eab-502d7f38a7e5.png">

**Comment by brusarp** [comment]
Are you on Hassio with Raspberry?
I've the same error...
Try this:
https://github.com/marthoc/hassio-addons/blob/master/deconz/FIRMWARE-UPGRADE.md
For me worked very good!

**Comment by salopette** [comment]
For me also a problem always after reboot


![sshot-1](https://user-images.githubusercontent.com/32480002/70522440-6b956b00-1b41-11ea-9839-a1f05abafc7a.png)

**Comment by overdrive69** [comment]
@brusarp I have raspbian (openhabian). So i think your solution didnt work for me.
@salopette 
For me the problem is different i think. I want to update to a new firmware but after the update it again shows the number of the old firmware.
Does anyone know something

**Comment by forast3r** [comment]
Similar issue here, running deconz Hass.io addon, stuck in fw version 26230500.
Have tried several times to upgrade to 26330500 but after update successful, phoscon reconnects to  deconz and the fw version stays in old version.
Any solution?

![image](https://user-images.githubusercontent.com/38989444/71078082-f9e49f00-2188-11ea-9ea4-d8412b1a0cd5.png)

**Comment by overdrive69** [comment]
So this seams to be a general problem.
Is there a official contact where we can ask for support?

**Comment by overdrive69** [comment]
There is an instruction to update the firmware manualy:
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

I tried this but i got following error:

/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

**Comment by m5x** [comment]
I get the same error. Looks like `/usr/bin/GCFFlasher_internal.bin` is compiled against version 2.28 of glibc but there is version 2.50 used in the docker container.

**Comment by m5x** [comment]
Or `/usr/bin/GCFFlasher_internal.bin` uses `/usr/lib/libwiringPi.so` which requires that version of glibc to be exact.

**Comment by m5x** [comment]
I get the same error. Found the fix [here (issue 153)](https://github.com/marthoc/docker-deconz/issues/153#issuecomment-538689683).

**Comment by mnpg** [comment]
I get the same error also (RPI3B+, raspbian stretch and Raspbee) -> i've post this fix [here (issue 207)](https://github.com/marthoc/docker-deconz/issues/207#issuecomment-597246324)

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
