### ISSUE TITLE
Expose Scenes to Harmony Hub?

### ISSUE THREAD

**Issue by clutwo** [dresden-elektronik/deconz-rest-plugin#2189]
I have added deconz as a hue brigde in the harmony app, but it only imports individual lights. Is there a way to expose / import scenes or is this not possible with this setup?

**Comment by ebaauw** [comment]
I don’t know the Harmony, but the deCONZ API for scenes is very different from the Hue API.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
