### ISSUE TITLE
Spirit SPZB0001 with ConBeeII/deconz and Home Assistant (setpoint-behavior)

### ISSUE THREAD

**Issue by ZEkE-999** [dresden-elektronik/deconz-rest-plugin#2192]
Hey there,

I'm using two SPZB0001 on deconz with Home Assistant. Pairing of the two was a bit tricky but worked finally (Resetting and pairing multiple times) and both are visible and controllable in HA.

The problem I have is, that I maybe don't understand how the modes (Heat, Auto) should work in detail. When I set the target-temperature to 22° and hit heat in HA, the target-temperature raises automatically to 30°.  When I set the target-temperature back to 22° in HA, the device gets in the mode auto. When I set it to Off, it sets 7° for target. So when I go to auto-mode I have to set the temperature back to 22° (or lower down from 30° in heat-mode...). 

I also tried to use a custom-card in HA (nervetattoo/simple-thermostat) - with this card, the target-temperatur sets back automatically... (when go down from 30° to 29,5°, card sets back to 30°).

Does somebody know if this is how it should be in HA or deconz? Is there a way to set a fix target-temperature even in the heat-mode?

Thanks,
ZEkE-

**Comment by wvuyk** [comment]
Heat-mode is a setting that will last 15 minutes, it sets at 30°C and will return to the last known setting in auto-mode after 15 minutes.. The heat setting is really a temporary burst setting, which you normally might not need.
It moves to in automode when you set it to 22. Or if you need to set it at low temperature, you can set it lower. Off is what it is, I think it  will not move the valve even when it is freezing.
Normally, you can just leave it in automode and  need to set the temperature only.

I do not know what HA does with it, but this is just how the device interprests these settings.
