### ISSUE TITLE
Xiaomi wall wired switch with no neutral creating 4 devices when added

### ISSUE THREAD

**Issue by xhemp** [dresden-elektronik/deconz-rest-plugin#2193]
Bought some Single Button Xiaomi wall wired switches(no neutral) and installed today.
When I add them, I can see that 4 different devices are created:

<img width="632" alt="Screenshot 2019-12-11 at 12 12 04" src="https://user-images.githubusercontent.com/13650956/70622051-f6926600-1c12-11ea-9ed2-df22611720b2.png">

Then to change the name, I do it on the last one but the other 3 devices remain there on Phoscon (where the issue probably lies). If I try to delete any of those, all 4 devices are deleted.If I check deCONz, I can see just one device but with multiple clusters:

<img width="199" alt="Screenshot 2019-12-11 at 12 08 44" src="https://user-images.githubusercontent.com/13650956/70622148-2fcad600-1c13-11ea-9415-0b76c8f5b243.png">

The basic cluster is as follows:

<img width="527" alt="Screenshot 2019-12-11 at 12 07 59" src="https://user-images.githubusercontent.com/13650956/70622166-3ce7c500-1c13-11ea-81bd-9b40cae9f7bd.png">

The device works well (no issue there) but the lights part on Phoscon has 9 extra devices ( I have 3 switches).
If you need anything else, please, let me know.

**Comment by lonebaggie** [comment]
same issue here. After a while two of bulbs disappear.  The switch works without a problem . If you attempt to delete the phantom bulbs , the switch and all the bulbs are removed.

As per screenshot no manufacturer or switch type is displayed just unknown

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
