### ISSUE TITLE
Update deCONZ software on Windows

### ISSUE THREAD

**Issue by smartypantsuk** [dresden-elektronik/deconz-rest-plugin#2194]
I noticed the manual update procedure but that seemed to be for the firmware on the Conbee.
I'm using deCONZ on Windows and I see there is a new version of the software, is there any update procedure? How do I know it's been updated, I can't see any versioning information anywhere in the deCONZ application.

Thanks

**Comment by Smanar** [comment]
For windows it's easy ^^
Here you can find the last deconz version, just download and install it http://deconz.dresden-elektronik.de/win/
After that go in phoscon , gateway and you will find a button to update firmware if needed.

**Comment by smartypantsuk** [comment]
> For windows it's easy ^^
> Here you can find the last deconz version, just download and install it http://deconz.dresden-elektronik.de/win/
> After that go in phoscon , gateway and you will find a button to update firmware if needed.

Thanks, just checking there weren't any pitfalls.
Just updated.

**Comment by iantait** [comment]
Semi-hijacking this thread - is 5.73 available for windows as yet (or osx :-)
Thanks.

**Comment by Smanar** [comment]
It' s a question ?
Take a look here http://deconz.dresden-elektronik.de/win/

**Comment by iantait** [comment]
thanks - it just appeared 🙂

________________________________

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
