### ISSUE TITLE
Paulmann RGBW 500.47 LED Controller

### ISSUE THREAD

**Issue by snador1977** [dresden-elektronik/deconz-rest-plugin#2200]
The RGBW controller is detected but the controller is not working properly. The RGB part can be controlled but the W part is not. If you want to control the W part in the Phoscon app, the white LEDs of the controller flicker briefly and the controller switches to the RGB part. Commonly encountered in the API 2 devices (RGB and W), so it is at least with other RGBW controllers in Deconz. In Paulmann, however, only the RGB part is created.

**Comment by ebaauw** [comment]
> Commonly encountered in the API 2 devices (RGB and W), so it is at least with other RGBW controllers in Deconz. In Paulmann, however, only the RGB part is created.

The API plugin creates a resource per ZigBee endpoint, so it’s really up to the light/controller how it advertises itself.  Could you post a screenshot of the endpoints and cluster, see Wiki.

**Comment by alessandroceleste** [comment]
I experience the same problem within Phoscon-App. Color temperature can't be adjusted since slider "flies away" when changing to color temperature mode.

![image](https://user-images.githubusercontent.com/37930300/70848417-6bfb7200-1e71-11ea-9381-5d8ef852e150.png)
