### ISSUE TITLE
Programming Custom Door Lock

### ISSUE THREAD

**Issue by ericvandamme** [dresden-elektronik/deconz-rest-plugin#2208]
I purchased a Zigbee door lock, and would like to start working on integrating it into deCONZ API. But for the hope of having it merged at some point, is there an expectation to how it should be developed to be accepted? Just curious because I would hate to get locked into a version long term if the door lock could be available for all.

Everything works as expected in deCONZ.

**Comment by Smanar** [comment]
If it works fine in deconz its a good starting point.

There is 2 issues with door lock integration, but I think none was finished, if it can answer to your questions
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/579
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/520

**Comment by ericvandamme** [comment]
I have read those in the past. But nothing official seemed to come of the conversation. Just guidelines to how it might be approached in the future, including (possibly) new device types.

**Comment by powermarcel10** [comment]
Wich zigbee doorlock are you using exactly?

**Comment by ericvandamme** [comment]
Schlage Connect Smart Deadbolt with Century Trim in Satin Nickel, Zigbee Certified - BE468GBAK CEN 619 (https://www.amazon.ca/gp/product/B07H3P3JKG/)
