### ISSUE TITLE
Trust Remote control switch

### ISSUE THREAD

**Issue by vamanea** [dresden-elektronik/deconz-rest-plugin#221]
Has anybody gotten the Trust Remote Control switch(model ZYCT-202) to join the network. As far as I can tell from their website it should be perfectly compatible yet no matter what I tried it does not join the raspbee network.

Does anybody have better experiences?

**Comment by manup** [comment]
No, they are not included yet, I wonder why they look *very* similar to the Philips dimmer switch.

**Comment by vamanea** [comment]
I'm sure it's just a _coincidence_ that it has exactly the same shape and it even fits in the Philips switch holder.
Is there something I can do to help adding support? I noticed on the back of the PCB they have some test pads marked as SPI which I suppose would be useful to dump the flash.

**Comment by andrejem** [comment]
I have bought a Trust motions sensor and Window OpenClose sensor, but i am not able to get them work with deconz for now.

**Comment by vamanea** [comment]
I commented on the other thread as well:

I can confirm I got the remote ZYCT-202 to join the network and through my deConz -> mqtt bridge I can see some events from the remote.

I have no yet tried the REST API but things are looking much better, thanks for your hard work.

**Comment by mat1990dj** [comment]
I also bought some remotes and motion sensors and are unable to see the info on the rest API. There are a couple threads already

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
