### ISSUE TITLE
Bug in Phoscon password verification?

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#2215]
It appears that whenever I call phoscon locally on the device it is running on via http://localhost, I can completely bypass authentication by entering a single arbitrary character. How can that be?

**Comment by jensflorian** [comment]
I can't reproduce this in Chromium. Authentication is required. What browser do you use?

**Comment by SwoopX** [comment]
It's latest Firefox. Also noted that the shown gateway displays localhost instead of any IP.
