### ISSUE TITLE
No API Key provided :(

### ISSUE THREAD

**Issue by nicedevil007** [dresden-elektronik/deconz-rest-plugin#2217]
Hello folks,

my little problem is, that my conbee stick won't give me a new API key. It was installed on other instance that worked well, but now I just want to add it to a new instance.

I always get this one:

![image](https://user-images.githubusercontent.com/17103076/70867913-232fe000-1f7b-11ea-991a-3b7d65160dc5.png)

**Comment by ebaauw** [comment]
You do need to provide a body to the POST request.

**Comment by nicedevil007** [comment]
I got it to work after some more trys with the "Discover device" Button in Node-RED. Unfurtunately I can't say what I changed to get it to work :(
