### ISSUE TITLE
No clue how to add Conbee to Harmony Hub

### ISSUE THREAD

**Issue by spudje** [dresden-elektronik/deconz-rest-plugin#2219]
Hope to find some help here. I'm totally lost. I'm running Phoscon/DeConz (port 8080) and Home assistant Docker images on a Synology NAS. I also have a Hue bridge and a Harmony Hub. I use Hue Bridge only for my lights. I use Conbee for smart plugs, sensors and switches. Everything works greatly together via Home Assistant.

In the Harmony Hub though, I only managed to detect the Hue Bridge. I have no clue how to also add the Conbee?

All help appreciated!

**Comment by D3nnisd** [comment]
You cannot.

I had the same issue and i used Home Assistant with a Roku emulation on it. Harmony is able to detect Roku and from there you can configure the roku buttons with your devices on Conbee.

**Comment by spudje** [comment]
Oh, OK, so I'm not as stupid as I thought :)

Thanks, I will try the Roku emulation.

**Comment by D3nnisd** [comment]
Still a issue!


Op di 14 apr. 2020 om 10:42 schreef stale[bot] <notifications@github.com>:

**Comment by Mimiix** [comment]
More discussion here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2486

Will close this one.
