### ISSUE TITLE
Ghost Device

### ISSUE THREAD

**Issue by 00lex** [dresden-elektronik/deconz-rest-plugin#2222]
Hi! Im using a Raspbee Device and today I see first time a Conbee Instance in my Web Interface, which can't be accessed. No matter if I clear Browser Cache or restart deconz service or the whole system. 

Im on Buster and the actual official Release of deConz. What could it be..?  

<img width="452" alt="Bildschirmfoto 2019-12-16 um 16 24 20" src="https://user-images.githubusercontent.com/39100562/70919801-cdfad980-2021-11ea-802a-1e91c257de7e.png">

**Comment by ebaauw** [comment]
Most likely, your ISP shares “your” public IPv4 address with others, and you’re seeing the gateway of one of your Internet neighbours.

**Comment by 00lex** [comment]
Why I can see others if Im on my local ip:port of phoscon?

**Comment by ebaauw** [comment]
That’s how gateway discovery works.  The Phoscon web app doesn’t know whether it’s being loaded from the gateway or from elsewhere.  It needs to discover the gateway like any other REST API client.  Each gateway registers with the appspot portal using the public IPv4 address.  The web app queries the appspot portal for registered gateways, which returns all registrations under that IPv4 address.

**Comment by giss69** [comment]
Hello,

i've suddenly the same issue. 2 more gateways with absolut different Its. Is it possible to block/hide other gateways?
Thank you
<img width="1072" alt="Bildschirmfoto 2019-12-21 um 17 13 39" src="https://user-images.githubusercontent.com/46527669/71310611-527c9c00-2416-11ea-8413-6fb2ebec2b98.png">
