### ISSUE TITLE
Phoscon - setting new password after GW reset leads to Login failed.

### ISSUE THREAD

**Issue by mvasicek** [dresden-elektronik/deconz-rest-plugin#2223]
Hi, I performed GW reset and setting new password leads to Login failed message. No other way to move further. Device power cycled, docker container ran fresh.

**Comment by mvasicek** [comment]
Issue solved by clearing browser's cache.

**Comment by manup** [comment]
>Issue solved by clearing browser's cache.

Glad it works now.

Small side note, next year we'll introduce a new login page which will fix a bunch of issues like this one.

**Comment by increddibelly** [comment]
is it too soon to talk about an expected update? I keep having this problem again and again to the point that it's just unusable.

**Comment by SHxKM** [comment]
I'm also experiencing this issue. Any updates?

**Comment by ttrueten** [comment]
I'm also interested in a solution. Reset Link doesn't work. Deleting zll.db and restoring of backup is ok, but seems to overwrite the new password with the forgotten one...

:-(
