### ISSUE TITLE
Ikea Tradfri On/Off Switch

### ISSUE THREAD

**Issue by nicedevil007** [dresden-elektronik/deconz-rest-plugin#2231]
I've got multiple IKEA Tradfri switches (that one with an upper and lower button, not the big round one).

In Node-RED I can use the buttonevent 1001/1003 and 1002 + 2001/2003 and 2002.
In the Phoscon App I can only setup 1002 and 2002.

**Comment by D3nnisd** [comment]
This switch behaves differently anyway. I use it to make the Fyrtur go up and down (just with the open cover command) within HAS. But going up makes it go for 1 second and after that it is stuck. A Philips remote functions as intended.

**Comment by nicedevil007** [comment]
Mhhh maybe someone can solve this prob? :)

**Comment by allanpersson** [comment]
Any plans to implement this in the app under switches?

**Comment by manup** [comment]
Yes, the whole switch support as in integration wizards and switch editor support will be largely extended.
We're working on it since a few months now, can't provide an ETA yet other than during the next months.

**Comment by allanpersson** [comment]
@manup awesome news 👏 It's just much easier with the stuff in the UI 😉
Thank you for the great work your doing 🙏
