### ISSUE TITLE
Moving lights from Hue Bridge to Deconz

### ISSUE THREAD

**Issue by kmplngj** [dresden-elektronik/deconz-rest-plugin#2233]
Hello,

this is more an ask for help than an issue.

I tried to find the best way to move my lights from the hue bridge to Deconz.

I found some informations about Touchlink, which I could not do in my setup. And I found some info regarding hue lights resets with a hue dimmer. But this did not work for me.

Could someone write a Wiki entry to describe the process in detail?

Thanks
Jan

**Comment by Smanar** [comment]
It works https://www.youtube.com/watch?v=qvlEAELiJKs
You can too without remote, video available on same site.

**Comment by Kane610** [comment]
Make sure the light is removed from all rooms groups remotes and then remove it from hue. Then it would just be to pair it
