### ISSUE TITLE
Iobroker error in new FW

### ISSUE THREAD

**Issue by Gizimo** [dresden-elektronik/deconz-rest-plugin#2242]
Hi,

wir haben wohl in der neuen Firmware ein Problem mit dem WebSocket:

https://forum.iobroker.net/topic/26758/deconz-aktualisiert-nicht-stati-von-phoscon-aqara/44

**Comment by Smanar** [comment]
There is a new firmware ?
The last I know is 4/5 month old.

**Comment by Smanar** [comment]
Perhaps duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2228
