### ISSUE TITLE
Device Support Request Bitron 902010/32 Wall Thermostat

### ISSUE THREAD

**Issue by easybeat** [dresden-elektronik/deconz-rest-plugin#2248]
Hi

It would be really good if this device would be supported. Here the link [https://www.amazon.de/Bitron-902010-32-BITRONVIDEO-Wandtermostat-ZigBee/dp/B016V7IJRG](url)

I think a device like that is missing to integrate a heating system.

Kind regards

Beat

**Comment by rgraenitz** [comment]
I actually searching for a compatible wall thermostat so that not just the light can be controlled. The only Zigbee thermostat I found was the above one .... did anybody already check if its compatible with deCONZ??

**Comment by SwoopX** [comment]
Sould already be supported according to #1003

**Comment by easybeat** [comment]
Thank you for this information! I will order one and test.

**Comment by Coalado** [comment]
@easybeat  Please give feedback

**Comment by easybeat** [comment]
@Coalado I finally got it tested and the device is recognized in Deconz but does not show up in Phoscon app.

And I'm using Deconz adapter in ioBroker and there I can see it and it also updates the current temperature BUT if I change the setpoint on the device, this value is not coming through to ioBroker. But if I change the setpoint in ioBroker it shows up on the device.

Can I test if the value is shown in Deconz if I change it on the device? This would mean that there is a problem with the ioBroker adapter and this here could be closed.

Thank you for help.

Beat

**Comment by SwoopX** [comment]
> Can I test if the value is shown in Deconz if I change it on the device? This would mean that there is a problem with the ioBroker adapter and this here could be closed.

You can easily do that via deconz GUI, if you read the attributes of the corresponding cluster (I presume thermostat cluster).

**Comment by easybeat** [comment]
> > Can I test if the value is shown in Deconz if I change it on the device? This would mean that there is a problem with the ioBroker adapter and this here could be closed.
> 
> You can easily do that via deconz GUI, if you read the attributes of the corresponding cluster (I presume thermostat cluster).

Hi

my current deconz version is 2.5.82.

Ok I finally managed to do the test and investigate the problem. The attribute is fine in deconz:
![Bitron Heating Setpoint attribute](https://user-images.githubusercontent.com/37217887/93802875-4ee7a100-fc44-11ea-9a21-0fb5eada6fb7.png)

Not sure if it is working ok as I had to press "read" button all the time after I changed the setpoint on the device? Should it not update automatically?

Because what I figured out is that if I press the read button the value get update also in ioBroker where I use the deconz adpater:
![ioBroker Deconz adapter Bitron Setpoint State](https://user-images.githubusercontent.com/37217887/93803037-8f471f00-fc44-11ea-8782-09875b584a94.png)

So my question is where is the problem? Should the setpoint automatically update in deconz after I change it on the device or does the ioBroker adapter have to send a "read" command to the attribute all the time?

Thank you for your help.

Kind regards

Beat

**Comment by SwoopX** [comment]
Looks like the attribute reporting is not defined. You may want to try this https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-configure-attribute-reporting

**Comment by easybeat** [comment]
OK will try this but is this a bug on this device integration?

Am 2020-09-21 22:28, schrieb SwoopX:

> Looks like the attribute reporting is not defined. You may want to try 
> this 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-configure-attribute-reporting
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2248#issuecomment-696355479
[2]

**Comment by SwoopX** [comment]
No, it's not specific to the device. More a topic for the default settings.

**Comment by easybeat** [comment]
Hi

yes after I configured the attribute reporting it is now working!

Thank you very much.

Kind regards

Beat

Am 2020-09-21 22:28, schrieb SwoopX:

> Looks like the attribute reporting is not defined. You may want to try 
> this 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-configure-attribute-reporting
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2248#issuecomment-696355479
[2]

**Comment by easybeat** [comment]
@SwoopX Hi, I just realised that the battery level is also not "reported" and I don't get it in ioBroker at all. Is this a similar problem or could that be not handled correctly in the ioBroker adaptor?

![Screenshot 2021-02-02 082815](https://user-images.githubusercontent.com/37217887/106566455-9f470780-6530-11eb-898f-96946a528c81.png)
![Screenshot 2021-02-02 082752](https://user-images.githubusercontent.com/37217887/106566462-a0783480-6530-11eb-86e0-79482cddfae3.png)

**Comment by Mimiix** [comment]
I dont see the battery percentage in there at all. Just the voltage ? The cluster for that is greyed out afaik.
