### ISSUE TITLE
Alexa cant discover my deviceI(s)

### ISSUE THREAD

**Issue by Craig01988** [dresden-elektronik/deconz-rest-plugin#2252]
I allow access to the device and get the 60 second timer, ask alexa to discover devices but nothing. Any suiggestions?

**Comment by kmplngj** [comment]
>I allow access to the device and get the 60 second timer, ask alexa to discover devices but nothing. Any suiggestions?

@Craig01988 Tell a bit more about your setup. How do you run Deconz?

**Comment by Craig01988** [comment]
Hi, I'm running deconz via hassio on a rpi4, I toought I may be able to link with out relying on the cloud but I've enabled the ha cloud service trial and can link to Alexa that way 😁. Is it possible without cloud services?

**Comment by kmplngj** [comment]
I think the Hassio Deconz Add On will run on another port than port 80. 
Deconz need to be running on Port 80 to work with Alexa.

Perhaps you could ask @frenck if this is so.
