### ISSUE TITLE
Feature request: backup from command line

### ISSUE THREAD

**Issue by bogdanm** [dresden-elektronik/deconz-rest-plugin#2254]
Hi, I'm using HA and I have a script that automatically backs up its configuration every night. I'd love to do the same thing with the configuration of deCONZ, but apparently there's no way to get a backup from the command line, you have to do it manually from Phoscon. If there's a way to get a backup file from the command line that I've missed, I'd love to hear about it. Thank you.

**Comment by ebaauw** [comment]
See #1307.

**Comment by bogdanm** [comment]
Thank you! This is exactly what I was looking for.
