### ISSUE TITLE
[Device Support Request] Smarthings Motion Sensor (GP-U999SJVLBAA)

### ISSUE THREAD

**Issue by shnhrrsn** [dresden-elektronik/deconz-rest-plugin#2259]
This was originally requested in #1260 and there appears to have been work done in 
d2c33bd, however it’s still not working and there seems to be a lot of confusion in original issue (which was closed), so reopening with fresh screenshots.

<img width="1106" alt="Screen Shot 2019-12-29 at 6 36 49 PM" src="https://user-images.githubusercontent.com/42901/71564216-2347d980-2a6b-11ea-9092-6153999410c0.png">
<img width="1104" alt="Screen Shot 2019-12-29 at 6 37 04 PM" src="https://user-images.githubusercontent.com/42901/71564217-26db6080-2a6b-11ea-828c-f2b824dd25bf.png">
<img width="1104" alt="Screen Shot 2019-12-29 at 6 37 34 PM" src="https://user-images.githubusercontent.com/42901/71564233-32c72280-2a6b-11ea-8250-62715fda7c2c.png">
<img width="1105" alt="Screen Shot 2019-12-29 at 6 37 52 PM" src="https://user-images.githubusercontent.com/42901/71564234-35297c80-2a6b-11ea-9ece-5c7f2646fb74.png">
<img width="1105" alt="Screen Shot 2019-12-29 at 6 38 20 PM" src="https://user-images.githubusercontent.com/42901/71564236-38246d00-2a6b-11ea-8df8-729735c9068b.png">
<img width="1103" alt="Screen Shot 2019-12-29 at 6 43 27 PM" src="https://user-images.githubusercontent.com/42901/71564237-3a86c700-2a6b-11ea-9982-ec12e043164e.png">

**Comment by SwoopX** [comment]
I'm afraid you haven't read the clusters before taking the screenshots. What specifically is not working?

**Comment by shnhrrsn** [comment]
Ahh sorry, I'll try it again tomorrow — need to unpair with my other hub first.

As far as not working, it’s not appearing in the rest API at all under `/sensors` (I’ve checked `/lights` and `/switches` to be safe, but nothing there either).

**Comment by SwoopX** [comment]
@shnhrrsn Sry, must have overlooked this one completely. Still an issue? Otherwise, I'd take another look.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
