### ISSUE TITLE
Wall switch loosing connection

### ISSUE THREAD

**Issue by abmantis** [dresden-elektronik/deconz-rest-plugin#226]
I have a power outlet from my electricity provider which I can successfully connect to deCONZ and control it. After a minute or so it stops updating on deCONZ and trying to control it results in timeout. The device is close to conbee.

I'm pretty new to deCONZ so I cannot debug much, but please let me know if you need any info. On the console I see a lot of "node busy" messages.

Maybe related to #33?

**Comment by manup** [comment]
Can you provide more info which switch it is, a link, type or name?

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
