### ISSUE TITLE
Strange - why is the remote control not visible?

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2266]
I connected a remote control (up/down) from insite a package of the curtain "KADRILJ" to conbee2.

The connection was not established after three minutes, so I aborted it.
But than I saw that remote control in the objekt-list of ioBroker, and it is working!!

Strange, because the remote control is not shown up in the phoscon app...

Anybody who can explain what happened?

Greetings
Michael 
![Unbenannt](https://user-images.githubusercontent.com/42386692/71588362-7e3c0800-2b21-11ea-9cfe-7f57f4d612a2.png)

**Comment by Smanar** [comment]
Some device are not supported by phoson, but are full working in the API.

**Comment by olemr** [comment]
You will find and link to it here: 
![image](https://user-images.githubusercontent.com/28068256/71590207-de35ad00-2b27-11ea-8578-adb3e85ad842.png)

**Comment by Michaelnorge** [comment]
Thank you all for your informations!
