### ISSUE TITLE
Deconz showing wrong state on Aqara door/windows sensors

### ISSUE THREAD

**Issue by HaaVeeEnn** [dresden-elektronik/deconz-rest-plugin#2269]
Version 2.05.72 / 12/12/2019
Conbee 2 firmware 264A0700
Hass.io version 0.103.5
Some first times it worked correctly but after it stopped.
Even if i open and close window state not changes, refreshed staying "21 minutes ago"
![Screenshot (39)](https://user-images.githubusercontent.com/16451882/71622130-69707a80-2bdc-11ea-92e6-3f6515e7839b.png)
![Screenshot (40)](https://user-images.githubusercontent.com/16451882/71622135-6d9c9800-2bdc-11ea-9adc-56ce715749b4.png)
![Screenshot (41)](https://user-images.githubusercontent.com/16451882/71622141-71c8b580-2bdc-11ea-9712-f6cf5e71b2ad.png)
![20191230_210105](https://user-images.githubusercontent.com/16451882/71622142-755c3c80-2bdc-11ea-9900-a6014f710a11.jpg)
![conbee](https://user-images.githubusercontent.com/16451882/71622156-8c9b2a00-2bdc-11ea-9187-ade3b4f970e7.PNG)
![conbee2](https://user-images.githubusercontent.com/16451882/71622159-8e64ed80-2bdc-11ea-88b4-0aaaeffe2dc7.PNG)

**Comment by ebaauw** [comment]
Did you replace the sensor's battery?

**Comment by HaaVeeEnn** [comment]
new device with 100%

**Comment by D34DC3N73R** [comment]
I have the same sensor with conbee II but running deconz in docker on ubuntu 18.04 and it seems to be working fine, Strange that yours is reporting vibration and doesn't have the version.
![image](https://user-images.githubusercontent.com/9123670/71638120-1adad480-2c0c-11ea-8bb5-3d8d30894b69.png)

**Comment by robertlandes** [comment]
Did you try to press the little button on the sensor (blue LED should blink once or twice) ? That should actually trigger an update to the state more or less immediately.

**Comment by HaaVeeEnn** [comment]
i repaired all those sensors who not shown version, and  now it works fine. but definitely there is some kind a problem why it wasn't paired correctly with first time

**Comment by TilBumble** [comment]
After updating from 2.05.71 to 2.05.72, my sensors still seem to work, but they show an additional line in their details page, as in the opening post, stating "Vibration {vibration}".

This refers to all my sensors:
- TRÅDFRI Motion sensor (2 pcs.)
- Xiaomi Multi Sensor 20161129 (2 pcs.)
- Xiaomi Window / Door Sensor 20161128 (2 pcs.)
- Xiaomi Water Sensor 20170721 (1 pcs.)

In Openhab 2.5.1-2, no new channels were created.

The only other change i noticed is that my Tradfri 5-button-remotes have disappeared from the start page, but are working and shown under "Switches".
(I had no lights directly assigned to them)

As the system seems to be functional, both issues are only minor flaws for me, but perhaps might be interesting for some of you.

Raspberry Pi 3 B+
ConBee 26330500
headless on openhabian
