### ISSUE TITLE
How do you change 'power failure' modes and fade durations?

### ISSUE THREAD

**Issue by Webunity** [dresden-elektronik/deconz-rest-plugin#2270]
I have the Docker Deconz running, all seems to work fine; paired about 10 Hue bulbs but i would like to change their power failure settings and for example how long it takes for a bulb to fade from one setting to another (currently it is a second i think).

I cant seem to find these settings in the GUI, but maybe i have to change it in the config in the docker image itself? The URL i am looking at starts with /pwa/index.html?...

**Comment by robertlandes** [comment]
Inital power on state is IMO currently not supported in deCONZ (only through HUE bridge). Fade duration (transition time) can be set on the edit tab in scenes configuration.

![2020-01-02_000213-](https://user-images.githubusercontent.com/4080985/71660685-2503ec80-2d4c-11ea-9dc2-d2f4a28f9a3f.png)
![2020-01-02_000214-](https://user-images.githubusercontent.com/4080985/71660686-27664680-2d4c-11ea-9cb1-161fb7cf1063.png)

**Comment by ebaauw** [comment]
See #1014.  With some tweaking of `general.xml` it's possible to set the poweron state of Hue lights through the deCONZ GUI.
