### ISSUE TITLE
How to integrate/connect a unsupported device?

### ISSUE THREAD

**Issue by Monnem** [dresden-elektronik/deconz-rest-plugin#2275]
Hi,
I got some motion sensors from the big A called:
"pegtopone otion Sensor ZigBee" (yes, without m in motion) ;-)
The sensor itself works as the LED lights when motion is detected.
But I fail to pair it with deconz. Any hints how to do that?

Thanks and regards

**Comment by SwoopX** [comment]
Please issue a device support request as described in the wiki.

**Comment by Smanar** [comment]
But the first step for this is make the device pairing with deconz.
If you can't include the device, it will be harder, need to check if it use correct zigbee request, ect ...

**Comment by Hassfabi** [comment]
Hi Together,
guess I purchased the same motion sensor on Amazon.
Here's what I got via VNC (searched for new sensors via phoscon web interface,  resetted the motion sensor and it joined the network):
![screen1](https://user-images.githubusercontent.com/59710787/72202227-1fe62200-345d-11ea-802b-7867168225eb.PNG)
Node info:
![image](https://user-images.githubusercontent.com/59710787/72202326-5ec8a780-345e-11ea-8ec0-5f861ecd66f8.png)
Cluster IAS Zone:
![image](https://user-images.githubusercontent.com/59710787/72202349-a4857000-345e-11ea-9439-cc4907dad149.png)
![image](https://user-images.githubusercontent.com/59710787/72202364-bff07b00-345e-11ea-8eb3-00b28abb9928.png)

If there's anything else you need, please let me know. How long does it usually take until a new device is added?
I'm also wondering if there's a way to use motion sensor already with the help of the binding drop box? Is there anything to read about how to set up a motion sensor, switching on and off a light with the binding drop box?

**Comment by jensflorian** [comment]
I am also looking for examples using the binding drop box. So far I have found only this:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/881#issuecomment-431654926

**Comment by Smanar** [comment]
The binding alone will be not usefull.

You can try to add yourself the device in the API, if the device is standard take a look on a previous pull request, some device just need 4/5 lines to be added, but for test it s better if you have the device.
