### ISSUE TITLE
Battery display in Volt

### ISSUE THREAD

**Issue by Typ1er** [dresden-elektronik/deconz-rest-plugin#2279]
Is it possible to display the measured voltage in addition to the battery display in percent and then pass it on via REST-API?

I only noticed that when the Aqara sensors on the mi-gateway are read out in FHEM I get a voltage display and in DeCONZ a percentage.

At which value should I change the battery?

**Comment by ebaauw** [comment]
> At which value should I change the battery?

For the Xiaomi CR2032 powered devices: any value under 100%, when the device starts acting erroneously.  For other devices under 10-20%.  In my experience, ymmv.
