### ISSUE TITLE
Add support for Lupus small ZigBee Temperaturersensor

### ISSUE THREAD

**Issue by sergiosaizolmo** [dresden-elektronik/deconz-rest-plugin#2281]
It's posible to add this device:
Lupus small ZigBee Temperatursensor (https://www.lupus-electronics.de/shop/en/Alarm-Smarthome/Smarthome-Home-Automation/LUPUS-Small-ZigBee-Temperatursensor-p.html)
Thanks in advance. 

![image](https://user-images.githubusercontent.com/26596910/71747104-13ffcc00-2e6f-11ea-9e82-bd70219da281.png)
![image](https://user-images.githubusercontent.com/26596910/71747135-2e39aa00-2e6f-11ea-8b06-2bb1a8c96258.png)
![image](https://user-images.githubusercontent.com/26596910/71747156-385ba880-2e6f-11ea-922b-4f2335381837.png)
![image](https://user-images.githubusercontent.com/26596910/71747171-427da700-2e6f-11ea-9a3d-dc35f5e12cb2.png)
![image](https://user-images.githubusercontent.com/26596910/71747184-4b6e7880-2e6f-11ea-9293-9b8859d17abe.png)
![image](https://user-images.githubusercontent.com/26596910/71747201-54f7e080-2e6f-11ea-9d13-4644f7bad999.png)
![image](https://user-images.githubusercontent.com/26596910/71747218-604b0c00-2e6f-11ea-8a38-ba64bec6c16e.png)
![image](https://user-images.githubusercontent.com/26596910/71747238-68a34700-2e6f-11ea-87c3-6eebc4274ede.png)
![image](https://user-images.githubusercontent.com/26596910/71747259-76f16300-2e6f-11ea-8810-c2d2ad3b4f53.png)

**Comment by SwoopX** [comment]
Looks like you haven't read the attributes before taking the screenshots. Please do so.

**Comment by sergiosaizolmo** [comment]
Sorry for the lapsus. Here is the updated screenshot:
![image](https://user-images.githubusercontent.com/26596910/71767966-3860b480-2f12-11ea-9a73-ba66613ea045.png)

**Comment by sbonfert** [comment]
I got the same device, however, it does not show up in phoscon. I therefore looked at the device properties in deCONZ. Most notably, the manufacturer name seems to differ for my device.
Is it necessary for you to add support for my device or am I configuring it wrong?

![lupus-1](https://user-images.githubusercontent.com/456502/86799496-4aaedd00-c072-11ea-94ee-9b4a17f4f5cf.png)
![lupus-2](https://user-images.githubusercontent.com/456502/86799492-4a164680-c072-11ea-956e-cb15b7f81f9a.png)
![lupus-3](https://user-images.githubusercontent.com/456502/86799486-497db000-c072-11ea-92f3-dc2ed87b920c.png)
