### ISSUE TITLE
Add support for Illuminize Wall Switch

### ISSUE THREAD

**Issue by AppleCarrotFlame** [dresden-elektronik/deconz-rest-plugin#2282]
Please add support for the Iluminize wall switch with 4 functions (on/off, cold/warm, brightness and colour). 

![illuminize_picture_large](https://user-images.githubusercontent.com/59490565/71784286-3f5ef400-2ff2-11ea-8fd8-9819c56975a1.png)

[Web page with device info](https://www.iluminize.com/de/shop/led-steuerung/product/540-511-577-zigbee-wand-dimmer-schalter-rgb-wei%C3%9F-duo-wei%C3%9F-led-1-zone.html)

![illuminize_clusterinfo](https://user-images.githubusercontent.com/59490565/71754739-cfccf580-2e87-11ea-8f03-7605e110dcc3.png)

![illuminize_nodeinfo](https://user-images.githubusercontent.com/59490565/71754741-d2c7e600-2e87-11ea-85be-f1593574d236.png)

![illuminize_basic](https://user-images.githubusercontent.com/59490565/71754873-774a2800-2e88-11ea-8656-f8c3436fb338.png)

edit1: the brand name is iluminize (with 1 L) and the model number is 511.557

**Comment by AppleCarrotFlame** [comment]
I managed to assign a few bindings via the Bind Dropbox. A single lamp (via IEEE address) can now be switched On/Off (cluster 6) or be dimmed (cluster 8). I have yet to find out how to manage groups via deCONZ, because I think it'd be more manageable in the future. 

The device still is not announced via the API to phoscon or to HASS.io.

**Comment by Shamal2008** [comment]
I would also really appreciate the support of this device. Is there a chance at the moment to get this switch in the deCONZ Webapp?
