### ISSUE TITLE
No WiFi DHCP IP after connecting RaspBee

### ISSUE THREAD

**Issue by markus-fischbacher** [dresden-elektronik/deconz-rest-plugin#2284]
After connecting RaspBee to Raspberry Pi I do not get a WiFi IP address anymore. Without the shield it‘s working. Is it possible to fix that or is RaspBee using resources of WiFi? Beside that, RaspBee is working as expected.

**Comment by caplam** [comment]
Is there any news on that subject ?
I have a raspbee with the raspbian image from dresden. As soon as deconz starts the wifi interface is disabled.
