### ISSUE TITLE
Add support for 3AZB-41-DE

### ISSUE THREAD

**Issue by AppleCarrotFlame** [dresden-elektronik/deconz-rest-plugin#2285]
This device is made by a company called 3A, and it is a zigbee 3.0 light switch for a single zone which replaces the in-wall switch. The unit is also known under the Nue brand, and retains the legacy on/off functionality of a normal switch when the zigbee signal is not available.

![3AZB-41-DE_small](https://user-images.githubusercontent.com/59490565/71773211-9369ca00-2f59-11ea-80d9-e49231f94e5f.png)

![3AZB-41-DE-node](https://user-images.githubusercontent.com/59490565/71773105-15a4bf00-2f57-11ea-8b0c-c17b7fd19ab5.png)

![3AZB-41-DE-nodeinfo](https://user-images.githubusercontent.com/59490565/71773106-18071900-2f57-11ea-9748-e6283676d170.png)

![3AZB-41-DE-cluster](https://user-images.githubusercontent.com/59490565/71773107-19d0dc80-2f57-11ea-94f5-34520a4a1550.png)

https://www.amazon.de/gp/product/B07GXGQHB2/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1

**Comment by Smanar** [comment]
And it don't work natively ?
If you go in cluster 0006, you can change the bulb state ?

**Comment by AppleCarrotFlame** [comment]
It works natively (on/off/toggle works fine). It just does not appear in phoscon nor in HASS.io. All my devices that are named 0x.... do not appear.

**Comment by Smanar** [comment]
And you can't see it in the API ?
I don't see anything special on your device, I can explain you how to add it in white list, but as it, from my memory all lights have a device created in api list by defaut.

**Comment by AppleCarrotFlame** [comment]
This last post gave me the hint (whitelist in API) I needed. I started the search for "lights" in phoscon again, and then switched the light on and off again. In phoscon there suddenly appeared an On/Off Light 19 with unknown manufacturer, but after a few seconds both the manufacturer and model appeared. 

Thanks! This request can be closed.
