### ISSUE TITLE
Bosch ZigBee Wireless Motion Detector RFDL-ZB-MS

### ISSUE THREAD

**Issue by geelenbert** [dresden-elektronik/deconz-rest-plugin#2289]
I tried to pair a couple of Bosch zigbee motion detectors.

I was hoping it would work out of the box as the devices should support Zigbee HA1.2:
[https://zigbeealliance.org/zigbee_products/radion-tritech-zb-4/](url)

For the Zigbee2mqtt project there has also been a request:
[https://github.com/Koenkk/zigbee2mqtt/issues/769](https://github.com/Koenkk/zigbee2mqtt/issues/769)

It pairs ok, but not shure what i need to do to get it working.
Ultimate i want to connect it to Home Assistant.

![image](https://user-images.githubusercontent.com/91923/71810583-00bd4e00-3073-11ea-90ae-2df63a9b41ea.png)

**Comment by SwoopX** [comment]
Can you please provide additional info as described in the wiki? Also, please make sure having the attributes read before taking the screenshots.

**Comment by geelenbert** [comment]
![image](https://user-images.githubusercontent.com/91923/72047031-ecb75d80-32b9-11ea-807e-388f4d103747.png)

![image](https://user-images.githubusercontent.com/91923/72046997-dc06e780-32b9-11ea-9bb3-275847d055e0.png)

![image](https://user-images.githubusercontent.com/91923/72047053-f9d44c80-32b9-11ea-8774-bb587400184e.png)

![image](https://user-images.githubusercontent.com/91923/72047073-05277800-32ba-11ea-83f6-5a5f496c10f6.png)

![image](https://user-images.githubusercontent.com/91923/72047116-183a4800-32ba-11ea-8b2f-a56b773868f7.png)

![image](https://user-images.githubusercontent.com/91923/72047180-3dc75180-32ba-11ea-802f-addd145d8e4d.png)

![image](https://user-images.githubusercontent.com/91923/72047198-47e95000-32ba-11ea-8fe9-220cf6765a1b.png)

![image](https://user-images.githubusercontent.com/91923/72047232-5899c600-32ba-11ea-9053-6e7cd33f0e37.png)

![image](https://user-images.githubusercontent.com/91923/72047250-63ecf180-32ba-11ea-975c-69ae9293c200.png)

![image](https://user-images.githubusercontent.com/91923/72047267-7109e080-32ba-11ea-9968-d74855b64f60.png)

**Comment by geelenbert** [comment]
Is there any insigt in when the next build will be done?

I don't want to be pushing anyone, but i just want to know when the next build will be. The last one was from over 2 months ago, and i'm ready to test the fix.

**Comment by SwoopX** [comment]
> The last one was from over 2 months ago, and i'm ready to test the fix.

You may want to compile the current version yourself ang give it a try?

**Comment by geelenbert** [comment]
I would like to do this, but it's not that easy.
My setup is running deconz in as Hass.io addon. 
I can run deconz in a Ubuntu VM for testing.

But what should be te expected behaviour?

**Comment by SwoopX** [comment]
Well, from your initial post, I conclude you do not see any sensors exposed through deconz' REST API and therefore also not in Hass.io.
Since the updates have been merged, but .73 is not available yet, compiling the plugin and doing the pairing should expose those sensors now. Pretty much straigh forward.

**Comment by jensflorian** [comment]
Does anyone know whether the RFDL-ZB-MS is  to the model sold as Smart Home motion sensor https://www.bosch-smarthome.com/uk/en/shop?url=products/smart-system-solutions/motion-detector ?

**Comment by geelenbert** [comment]
So i compiled the latest version and runned the rest plugin into a virtual machine:

![image](https://user-images.githubusercontent.com/91923/73272648-01b14d80-41e3-11ea-878f-5b96476807ef.png)

I removed the old Deconz integration from home assistant.
I started Home assstant again and paired the new Deconz instance. 

All my sensors are now added, but I can't find a new motion sensor.

Am i looking into the wrong place? Or is there anything i'm missing ?

**Comment by SwoopX** [comment]
Did the sensor search give you a green indication of a successful pairing process with the Bosch sensor? Have you queried the deconz REST API for all sensors and double checked?

**Comment by geelenbert** [comment]
I paired the sensor again and now it shows up in Home Assistant.

I enabled the light indicator on the device to see if motion is detected.

But the state of the sensor does not change in Home Assistant:

<img width="364" alt="Screenshot 2020-01-28 at 23 31 26" src="https://user-images.githubusercontent.com/91923/73311309-6c37ad00-4226-11ea-8ba3-f5277eb656ba.png">

Any suggestions ?

**Comment by SwoopX** [comment]
Hm, can you double check in deconz GUI (IAS Zone cluster) if the sensor is enrolled? Also, please check deconz REST API if the state changes there.

**Comment by geelenbert** [comment]
<img width="720" alt="Screenshot 2020-01-29 at 07 45 11" src="https://user-images.githubusercontent.com/91923/73333858-67491c80-426b-11ea-9a92-f9862f53360a.png">

<img width="701" alt="Screenshot 2020-01-29 at 07 46 59" src="https://user-images.githubusercontent.com/91923/73333934-8c3d8f80-426b-11ea-9c92-ddfc7fd260d0.png">

**Comment by SwoopX** [comment]
I'm afraid the screenshots are not much of a help since they neither show the read attributes of the IAS Zone cluster nor answer the question, if you've checked the REST API.

**Comment by geelenbert** [comment]
<img width="918" alt="Screenshot 2020-01-30 at 20 07 15" src="https://user-images.githubusercontent.com/91923/73481464-2866b400-439c-11ea-9305-678f17ca56e4.png">

I paired a second one.
Looks the same. I read the IAS zone attribute. 

Do you think the device needs to be configured ? Or should the motion sensor work all the time ?

I'm not sure how to test the rest api. Should a debug log help ? If so, which log ?

**Comment by SwoopX** [comment]
Thanks for the screenshot, that one is workable. It is strange that it hasn't been enrolled automatically (which should have happened). I can check the code once mor to see if I've overlooked something.

You can have a look here regarding API usage: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2373#issuecomment-578511439

**Comment by geelenbert** [comment]
Did you have a momment to check if there was an issue in the code ?

I'm not technical enough I think to enroll it manually

**Comment by SwoopX** [comment]
Yes, but haven't spotted anything suspicious so far.

> I'm not technical enough I think to enroll it manually

This is really just like 3 clicks and typing the MAC address of your conbee/raspbee in there. Looks worse than it is. I'm dependent on you with this since I don't have that device, otherwise I cannot really help.

**Comment by geelenbert** [comment]
It was a bit of a struggle, but i finally found the steps that need to be taken.

By putting the mac address into the field the status changed to enrolled.
Home assistant does look like it reports changes of motion state.

So for now it looks like it is working!
<img width="256" alt="Screenshot 2020-02-02 at 21 47 07" src="https://user-images.githubusercontent.com/91923/74102777-1547a700-4b47-11ea-8cba-928dbda54ce8.png">

**Comment by SwoopX** [comment]
That doesn't sound too bad, great. Say, do you get reasonable battery readings from your device? My feeling would say no.

**Comment by geelenbert** [comment]
I don't get any battery readings. 
Is there any way to check or improve this ?

**Comment by SwoopX** [comment]
Already prepared an update.

**Comment by geelenbert** [comment]
Cool!
Let me know when I can test it.

**Comment by SwoopX** [comment]
Available already in my repo, so go for it.

**Comment by Mimiix** [comment]
It seems this issue is resolved. If it is not, please re-open or create another issue.

**Comment by geelenbert** [comment]
I dusted off this project again and i would like to mention that the device works out of the box.
Motion, 

Motion, temperature, lux and battery level:
![image](https://user-images.githubusercontent.com/91923/103523866-da481380-4e7c-11eb-83c5-ad1585fa8b46.png)

Not sure yet if the battery level indicator is realistic, but 90% for a device that has been laying in the storage for some time seems reasonable.

One issue i'm having tough is that Phoscon does not show all these devices.
I have now added 7 of these sensors:

Deconz:
![image](https://user-images.githubusercontent.com/91923/103524939-b1c11900-4e7e-11eb-963b-c9988350e290.png)

Home Assistant shows this: 
![image](https://user-images.githubusercontent.com/91923/103524095-4296f500-4e7d-11eb-8be0-b0fe4160b9f4.png)

Phoscon:
![image](https://user-images.githubusercontent.com/91923/103524347-b2a57b00-4e7d-11eb-9740-963225e301a5.png)

The problem is that Phoscon only shows 4 of the 7 devices. I can use Phoscon to automate lights and rename the devices. 

Here is the node info per node:
![image](https://user-images.githubusercontent.com/91923/103525100-f9e03b80-4e7e-11eb-808c-ca77c36236ce.png)
![image](https://user-images.githubusercontent.com/91923/103525118-02387680-4e7f-11eb-8876-db6b4ecec117.png)
![image](https://user-images.githubusercontent.com/91923/103525132-0795c100-4e7f-11eb-93ed-9b326c47ba33.png)
![image](https://user-images.githubusercontent.com/91923/103525147-0d8ba200-4e7f-11eb-8582-dc0f7316f6fe.png)
![image](https://user-images.githubusercontent.com/91923/103525159-13818300-4e7f-11eb-9a00-9e431e7918e7.png)
![image](https://user-images.githubusercontent.com/91923/103525171-18decd80-4e7f-11eb-988f-5e692ffc7b4b.png)
![image](https://user-images.githubusercontent.com/91923/103525184-1f6d4500-4e7f-11eb-852b-bb085604cf0a.png)


From my perspective, i don;t see any difference between the devices being shown in Phoscon, and the ones that are not. 
Removing and adding them again results in the same result.

Any idea what is going on ?

**Comment by SwoopX** [comment]
I'll have a look later. Anyway, thanks for confirming!

**Comment by geelenbert** [comment]
@SwoopX any change of pointing me in a direction ? 
i want to integrate the sensors, but i don't want to change the entities further on.

**Comment by SwoopX** [comment]
This one drowned, sorry for that. Can you please read the IAS cluster attributes of both. I'd assume one is not enrolled.

**Comment by geelenbert** [comment]
This is from one that is not detected:
![Screenshot 2021-01-08 at 18 06 04](https://user-images.githubusercontent.com/91923/104043602-54113180-51dc-11eb-8a23-566c9cb5d085.png)

This is one that has been detected:
![Screenshot 2021-01-08 at 18 08 06](https://user-images.githubusercontent.com/91923/104043705-7acf6800-51dc-11eb-8f68-da6340bbef5a.png)

I think they are enrolled successfully. When i started this thread, the devices did not enrol at all, so somewhere along updates of deconz or my system this looks fixed. Now they do not show up in Phoscon yet.

**Comment by SwoopX** [comment]
Hm, that's odd. You could try entering sensor search in Phoscon again and trigger one of the problematic devices my provocing motion. In addition to that, it might be a good idea to push the physical button on the device.

Alternatively, you may want to try removing the batteries and re-inserting them while searching for sensors.
