### ISSUE TITLE
Rest plugin not working with SmartThings/CentraLite Motion and Contact sensor

### ISSUE THREAD

**Issue by mikem2te** [dresden-elektronik/deconz-rest-plugin#229]
The plugin doesn't work with my SmartThings Motion and Contact sensors. They both support IAS Zone cluster and adding two additional supported devices in to the de_web_plugin.cpp file seems to make them work for me.

@@ -79,6 +79,7 @@ static const SupportedDevice supportedDevices[] = {
     { VENDOR_BUSCH_JAEGER, "RM01", bjeMacPrefix },
     { VENDOR_CENTRALITE, "Motion Sensor-A", emberMacPrefix },
+    { VENDOR_CENTRALITE, "3325-S", emberMacPrefix }, 
+    { VENDOR_CENTRALITE, "3321-S", emberMacPrefix },
     { VENDOR_NONE, "LM_",  tiMacPrefix },
     { VENDOR_NONE, "LMHT_", tiMacPrefix },

I've put the change above if it useful for you guys.

**Comment by manup** [comment]
Thanks I've added them to the list, will be available in 2.04.83.

**Comment by mikem2te** [comment]
Thank you.
