### ISSUE TITLE
Active power is not exposed as sensor to Home Assistant for Osram Lightify Plug

### ISSUE THREAD

**Issue by AbDhops** [dresden-elektronik/deconz-rest-plugin#2296]
I am using Deconz version 2.05.71. Home Assistant is configured using Deconz plugin and sees all available devices.
For Osram Lightify plug, I could see "Electrical Measurement cluster". And some values are also read in Deconz, however, those values are not available as sensors to Home Assistant.
Not sure where is limitation.

**Comment by ebaauw** [comment]
The OSRAM plug doesn’t report anything useful, so deCONZ no longer exposes a ZHAConsumption sensor for it.

**Comment by AbDhops** [comment]
Okay... then may he we can close this issue....
