### ISSUE TITLE
Cannot rename sensor

### ISSUE THREAD

**Issue by XerXes777** [dresden-elektronik/deconz-rest-plugin#2297]
<img width="513" alt="Bildschirmfoto 2020-01-09 um 05 40 30" src="https://user-images.githubusercontent.com/28979354/72038737-bcb09000-32a2-11ea-9e2a-9225051ec01d.png">

I can rename in deconz app the plug by the lights,
but i cant rename in deconz app the sensor ( power consumption) from my innr sp120 plug
because in deconz app by sensors isnt an entry.

**Comment by Smanar** [comment]
I think for the moment the only way is using the API https://dresden-elektronik.github.io/deconz-rest-doc/sensors/ for sensor, for light you can use the old webapp.

**Comment by XerXes777** [comment]
okay thanks and the next is...
why i have 2 entrys in iobroker for one innr smart plug in the sensors dir?
by example the picture sensor id 8 and 9 is the same smart plug,
becaus i have actually one smart plug connectet to deconz.

**Comment by Smanar** [comment]
It's because consumption and current are not on the same cluster.
Deconz create 1 entry by sensor, if you have the Xiaomi multi sensor, you will have 3 entries, temperature/barometer/pression.

**Comment by XerXes777** [comment]
thank you verry much !!
it can be closed.
