### ISSUE TITLE
Add support for Xiaomi Mijia Smart Light Sensor (GZCGQ01LM)

### ISSUE THREAD

**Issue by jeroenvdheuvel** [dresden-elektronik/deconz-rest-plugin#2300]
Unfortunately, I'm unable to find a link on an official website. This is the actual device: 

![image](https://user-images.githubusercontent.com/5213151/72068590-b98ac380-32e5-11ea-84d3-dbf2af12a7b7.png)

Here is a link to seller: https://aliexpress.com/item/4000475208359.html

Information about the device:
![image](https://user-images.githubusercontent.com/5213151/72068755-14241f80-32e6-11ea-99a0-0194316b6a16.png)

![image](https://user-images.githubusercontent.com/5213151/72068878-4170cd80-32e6-11ea-91fd-67b4d6b16165.png)

![image](https://user-images.githubusercontent.com/5213151/72070131-12a82680-32e9-11ea-99aa-60d218ffcfa6.png)

![image](https://user-images.githubusercontent.com/5213151/72069022-872d9600-32e6-11ea-9fb8-4a0ca143002e.png)

![image](https://user-images.githubusercontent.com/5213151/72070189-34a1a900-32e9-11ea-8533-58aab6c96585.png)

I'm unsure of this data is useful. I enabled debugging and here's some log information related to this device (when activates/data requested). The device id is: 0xb267
>14:00:02:657 ZCL cmd-req nwk: 0xB267, profile: 0x0104, cluster: 0x0400 cmd: 0x00
14:00:02:657 APS-DATA.request id: 234, addrmode: 0x02, addr: 0xb267, profile: 0x0104, cluster: 0x0400, ep: 0x01 -> 0x01 queue: 0 len: 11 tx.options 0x00
14:00:02:657 ZCL read cluster: 0x0400, attribute: 0x0004
14:00:02:657 ZCL cmd-req nwk: 0xB267, profile: 0x0104, cluster: 0x0400 cmd: 0x00
14:00:02:658 APS-DATA.request id: 235, addrmode: 0x02, addr: 0xb267, profile: 0x0104, cluster: 0x0400, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
14:00:02:658 Delay APS request diff = 0
14:00:02:677 APS-DATA.confirm id: 234, status: 0x00 SUCCESS
14:00:02:677 APS-DATA.confirm request id: 234 -> erase from queue
14:00:02:730 aps request id: 234 finished, erase from queue
14:00:02:918 Delay APS request diff = 260
14:00:03:023 APS-DATA.indication srcAddr: 0xb267, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0400, lqi: 255, rssi: -62
14:00:03:023 Delay APS request diff = 366
14:00:03:023 ZCL got data for node=0xB267, cl=0x0400, at=0x0000, status=0x00, type=0x21
14:00:03:023 ZCL got data for node=0xB267, cl=0x0400, at=0x0001, status=0x00, type=0x21
14:00:03:023 ZCL got data for node=0xB267, cl=0x0400, at=0x0002, status=0x00, type=0x21
14:00:03:023 ZCL got data for node=0xB267, cl=0x0400, at=0x0003, status=0x00, type=0x21
14:00:03:255 APS-DATA.confirm id: 235, status: 0x00 SUCCESS
14:00:03:255 APS-DATA.confirm request id: 235 -> erase from queue
14:00:03:291 aps request id: 235 finished, erase from queue
14:00:04:891 Mgmt_Lqi_req zdpSeq: 67 to 0x086BD7FFFE4D52AF start index 0

**Comment by jeroenvdheuvel** [comment]
What's the best way for me to start implementing this sensor? Is there documentation that would help me get up to scratch?

**Comment by Smanar** [comment]
Depend of your luck ^^.

- Be sure it's working on deconz, correct pairing, can read information, can send action to it, ect ...
- Add it in "white list" if needed. This part is mostly for sensor
- Recompile the code, replace the file and restart deconz, the process is described on github mainpage https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
- Submit a Pull.

If you are lucky it will be enought else describe your problem, perhaps someone will have idea.

You can find usefull informations and one exemple on this issue https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2002

**Comment by Alexxander0** [comment]
Hello,
did you find any way to pair it and make it work?

**Comment by xCruziX** [comment]
A status update would be great.

**Comment by tjaena** [comment]
There is a duplicate issue (#2380) to this one. Which resulted in a pull request (#2375), which was already merged to master.

As of my understanding, you could either try to compile from the source or wait for a new release with the support for the sensors.

I’ll try the first one at a later time this week and see if it works out.

**Comment by jeroenvdheuvel** [comment]
Like @Alexxander0 I'm having trouble pairing the sensor.

It's being recognized now:
![image](https://user-images.githubusercontent.com/5213151/76314358-ea33ad00-62d6-11ea-825e-1814971ca587.png)

The console output:
![image](https://user-images.githubusercontent.com/5213151/76314444-19e2b500-62d7-11ea-86a7-10acf2dbad7a.png)


But when I click the "ready" button, the sensor is not there.

**Comment by sjee105** [comment]
It doesn't showup in phoscon but you should see it on your network map. I have two working with HA.

**Comment by jeroenvdheuvel** [comment]
@sjee105 you're right I also see the sensor in HA and it works fine.

I'm not sure if this issue should still be kept open. The pairing is confusing but it does work in the end.

**Comment by SwoopX** [comment]
If I understand the release notes of .75 correctly, the sensor should now also show up in Phoscon. Afaik, it is fully supported now.

@jeroenvdheuvel What's exactly confusing from the pairing perspective?

**Comment by jeroenvdheuvel** [comment]
The pairing works fine. But after pairing the sensor isn't visible in the Phoscon web interface. That means that there's no way to change the name.

You can see this in the recording I made:
![Recording](https://user-images.githubusercontent.com/5213151/76315200-86aa7f00-62d8-11ea-9980-8f11a0c28a0f.gif)

**Comment by SwoopX** [comment]
Ok. I see. One needs to understand that Phoscon is decoupled from deconz in terms of device support. Phoscon is closed source and therefore, new devices must not automatically be shown. Sad, but true.

However, the green success message is what's important.

**Comment by Janky0** [comment]
But how can i use this sensor in FHEM when its not shown in deconz?

**Comment by SwoopX** [comment]
It depends a bit if in FHEM stuff is created automatically or not. If the sensor is paired correctly, it will be visable via REST API and therefore also visible for FHEM. You may want to check your deconz device there and get the list of sensors (don't think anything's available as light for the device). Then you require the corresponding ID to create a new device inside FHEM (or multiple in case more than one sensor is created for the Xiaomi by deconz).

**Comment by Janky0** [comment]
yes thats no problem but i get no lux or something like that

`Internals:
   CFGFN     
   DEF        sensor 2  IODev=deCONZ
   FUUID      5ea85d71-f33f-0688-81a1-3b7723ced27c58e5
   FVERSION   31_HUEDevice.pm:0.217030/2020-04-16
   ID         S2
   INTERVAL   
   IODev      deCONZ
   NAME       Lichtsensor
   NR         738
   STATE      Initialized
   TYPE       HUEDevice
   manufacturername LUMI
   modelid    lumi.sen_ill.mgl01
   name       Lichtsensor
   on         1
   reachable  1
   swversion  20191118
   tholddark  12000
   type       ZHALightLevel
   uniqueid   04:cf:8c:df:3c:77:26:ae-01-0400
   helper:
     devtype    S
     reachable  0
     update_timeout 1
     configList:
     json:
       ep         1
       etag       14a2900bb5e3ab4c90316cf9defb8124
       lastseen   2020-04-28T16:44:47.781
       manufacturername LUMI
       modelid    lumi.sen_ill.mgl01
       name       Lichtsensor
       swversion  20191118
       type       ZHALightLevel
       uniqueid   04:cf:8c:df:3c:77:26:ae-01-0400
       config:
         battery   
         temperature 0
         tholddark  12000
         tholdoffset 7000
       state:
         dark       
         daylight   
         lastupdated none
         lightlevel
         lux       
     setList:
Attributes:
   IODev      deCONZ
   model      lumi.sen_ill.mgl01`

**Comment by ragefan** [comment]
Same issue with same captor. I compiled from source. Anything i can do to collect logs ?
The captor seems detected but no value from the sensor.

**Comment by ragefan** [comment]
> 
> 
> @sjee105 you're right I also see the sensor in HA and it works fine.
> 
> I'm not sure if this issue should still be kept open. The pairing is confusing but it does work in the end.

Hi,
Can you read the sensor value ?
I cannot in Jeedom.

**Comment by SwoopX** [comment]
@ragefan we could do pretty much the same exercise here as for the smart plug. Might be that here's still some room for improvement as I don't know (yet) what's been reported.

**Comment by ragefan** [comment]
Let's go : can you please have a look to those logs ? The sensor is inside.
[putty.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4658884/putty.log)

Screenshot from deconz have already been posted at the beginning of the thread.

**Comment by Smanar** [comment]
Can try to make manual binding ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2380#issuecomment-588213553

I know it's already in the code, but we can see in log
>18:47:33:783 MAC poll fastEnddeviceProbe() 0x04CF8CDF3C78815D
18:47:33:783 don't create binding for attribute reporting of sensor Light Sensor

**Comment by ragefan** [comment]
Is it saved somewhere ? I was using a headless device up to now.

**Comment by SwoopX** [comment]
@ragefan You require deconz GUI to set up binding and reporting manually. However, we could also do that via a code change for testing purposes. In bindings.cpp, search for that line
`sensor->modelId().startsWith(QLatin1String("lumi.plug.maeu01")) ||`
and change it to
`sensor->modelId().startsWith(QLatin1String("lumi.")) ||`

I've introduced general binding for Xiaomi with version .74, but reverted as people started to report strange issues with the motion sensor. As I don't have the devices in hand, I simply do not know if they support binding and attribute reporting or not. However, as this is an Aqara ZB3.0, it seems it does, so we probalby should include it as well.

**Comment by Smanar** [comment]
I have see a screenshoot from you ? Was just for some test ?
And good question ^^. Some information are stored on the device (reporting values), but I have a doubt for "binding table".

@SwoopX have perhaps an answer ?
All xiaomi device have binding/report disabled because Xiaomi use it's own notifications, perhaps it's somethinf different for this device ?

**Comment by ragefan** [comment]
Yes, just for some tests under windows (not "production" env)

**Comment by ragefan** [comment]
![image](https://user-images.githubusercontent.com/11183119/82496570-455ef880-9aed-11ea-8bf6-ab276fdff566.png)

Just a screenshot from HA, showing "unknown" value for light sensor

**Comment by Smanar** [comment]
I m searching information ATM, but this device is zigbee 3.0, so perhaps a better one with other method than classic Xiaomi.

**Comment by SwoopX** [comment]
One thing to note: Aqara != Mija

The Aqara ZB3.0 devices seem to be closer to "normal and expected" behaviour than the ZB3.0 Mija's.

**Comment by ragefan** [comment]
Hum ... is this helping ?
https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/GZCGQ01LM.md

**Comment by Smanar** [comment]
OK so it s that
This device need binding.

We need to bind the cluster 0400

**Comment by ragefan** [comment]
Thanks ! Sorry but i don't know what "bind the cluster" mean :-(
Can it be done using some command lines ?
Where is it store ? if in the device, is there a risk to crash it ?

**Comment by SwoopX** [comment]
@Smanar That's not adequate, I'm afraid. Take the sensors (temp, door, etc.). The round one (Mija) are crappy and unstable as hell. The Edged ones (Aqara) are much more reliable, although far from being perfect.

Now, in ZB3.0 land, the Mija smart plugs still use that analog cluster stuff, have their embedded attribute reporting, manufacturer specific cluster and the special Xiaomi attribute reporting thingy. With the ZB3,0 sensor here and also with the smart plug, you seem to have what everybody else expects and uses: binding and attribute reporting, NO Xiaomi special attributes as it seems.

**Comment by SwoopX** [comment]
@ragefan Recomplie with the proposed change. It's way easier with your headless setup.

**Comment by ragefan** [comment]
which one ? is there a pull request somewhere ?

**Comment by SwoopX** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2300#issuecomment-631716756

**Comment by ragefan** [comment]
Ouch, just missed that one ! Thanks, will try that :)

**Comment by SwoopX** [comment]
Np

**Comment by ragefan** [comment]
Well well well, that's sound better as i get new attributes :
![image](https://user-images.githubusercontent.com/11183119/82503217-1b133800-9af9-11ea-9224-d6aec8b920bf.png)

However, it seems i still cannot collect the intensity of light ?
How often is it refreshed ?

**Comment by SwoopX** [comment]
Please allow me. You now patched what I reverted some days ago :)

**Comment by ragefan** [comment]
:) come on! This was a nice working patch. :) Do you need more clues in order to put it back again?

Indeed that one is working now 😁 Thanks!

**Comment by SwoopX** [comment]
😄 Just wasn't explicit enough. All done.

**Comment by ragefan** [comment]
Thanks! I guess we can close that one as well then 😉 Go for the next one, I am waiting some brand new xiaomi sensors.

**Comment by DukeNuken** [comment]
Guys. I have the same sensor from aliexpress and it does not show up in deconz. So what should be done here? Will it be added to deconz addon after some update?

**Comment by ragefan** [comment]
Hi! You need to build from source or wait the next release. It is fixed in the current source.

**Comment by SwoopX** [comment]
What is your deconz version? Do you really mean it doesn't show up in deconz or rather Phoscon?

**Comment by DukeNuken** [comment]
I am using HassOS 3.13 with HomeAsistastant and there are installed deconz addon. 
![Screenshot_37](https://user-images.githubusercontent.com/2789880/83009709-d10de300-a01f-11ea-9394-d50a0c6a95b5.png)
When I am adding the new sensor with the Phoscon web interface it shows sensor added but there are no new devices in the list.

**Comment by SwoopX** [comment]
Thanks, so the device should be fully functional. This repo is about the REST API, not Phoscon.

However, for Phoscon, they are putting quite some effort in catching up right now.

**Comment by ragefan** [comment]
> I am using HassOS 3.13 with HomeAsistastant and there are installed deconz addon.
> ![Screenshot_37](https://user-images.githubusercontent.com/2789880/83009709-d10de300-a01f-11ea-9394-d50a0c6a95b5.png)
> When I am adding the new sensor with the Phoscon web interface it shows sensor added but there are no new devices in the list.

I ve got same issue with phoscon but as said this is another topic.

**Comment by Mimiix** [comment]
As mentioned before in the other topic / issue: not everything is shown in Phoscon due to the fact it needs to be added manually.

**Comment by bcutter** [comment]
So is this device fully supported (deCONZ/Phoscon)?

Meaning sensor values are provided (battery state, illuminate).

**Comment by SAOPP** [comment]
> So is this device fully supported (deCONZ/Phoscon)?
> 
> Meaning sensor values are provided (battery state, illuminate).

Yes, I have been using the device for almost a year.

![image](https://user-images.githubusercontent.com/5647009/108966807-5265d500-7687-11eb-9249-ebb75ad3198f.png)

**Comment by goegsig** [comment]
> 
> 
> > So is this device fully supported (deCONZ/Phoscon)?
> > Meaning sensor values are provided (battery state, illuminate).
> 
> Yes, I have been using the device for almost a year.
> 
> ![image](https://user-images.githubusercontent.com/5647009/108966807-5265d500-7687-11eb-9249-ebb75ad3198f.png)

How did you pair it ? Mine just shows up like this. Nothing in phoscon.
![billede](https://user-images.githubusercontent.com/7282538/112058355-c8603d80-8b5a-11eb-9140-f1588dc8d808.png)

**Comment by SAOPP** [comment]
U'd better tell me what version of Deconz u have.

**Comment by goegsig** [comment]
![billede](https://user-images.githubusercontent.com/7282538/112135126-b9ff3980-8bcd-11eb-9a74-de20c3a155f6.png)

**Comment by SAOPP** [comment]
Strange, but the sensor should be in Phoscon, u probably have a different revision, but these are just thoughts aloud, probably Phoscon doesn't know your revision... try to reconnect it.
