### ISSUE TITLE
Add support for KlikAanKlikUit Smoke Sensor 

### ISSUE THREAD

**Issue by mathim** [dresden-elektronik/deconz-rest-plugin#2301]
Hello

I would like to request support for device support for
- KlikAanKlikUit Smoke Sensor
- ID ZSDR-850

Device looks pretty much the same as the Heiman HS1SA

![image](https://user-images.githubusercontent.com/724241/72092779-5152d680-3313-11ea-8de2-f1464baef114.png)
![image](https://user-images.githubusercontent.com/724241/72092798-5a43a800-3313-11ea-81ad-ab4fd122fbd0.png)
Thanks in advance
Kr

**Comment by SwoopX** [comment]
According to the code and info provided, it should already be supported.

**Comment by ebaauw** [comment]
Can the siren on this sensor be activated over ZigBee.  Does the device have a working _IAS WD_ cluster?

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
