### ISSUE TITLE
Ok, I think I got it finally!

### ISSUE THREAD

**Issue by cobch** [dresden-elektronik/deconz-rest-plugin#2308]
Ok, I think I got it finally! 
For future newbies (like myself) who arrive in this github like I did:
1) Setup VNC in deconz config and open the GUI
2) You see your zigbee mesh. Open Cluster info tab (bottom left)
3) Click on the second dot next to each light's name and choose Legrand-Specific clusters option
4) Edit (double click) the attribute on the cluster info tab ("0x0101" for enabling Dimmer on and "true" for enabling the led on the switch) and click **write** for both.

It should be working now! Thanks guys, if it weren't for this github, I would have called an electrician (because I thought I did the cabling wrong :P :P )

_Originally posted by @nassost79 in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883#issuecomment-564976964_

**Comment by cobch** [comment]
Hi,

I am a newbie and thanks to you I have managed to activate the dimmer function of my Legrand Céliane Switch with dimmer without neutral in home assistant with ConBee. 
My only problem is to activate the dimmer function when I push the switch manually (-:
I only can use on/off when I push on the switch. Any ideas what I should do to make it work?

Thanks in advance for your help.

**Comment by Smanar** [comment]
Hello, just for information the second option is not necessary for dimmer, it's just to have the LED always on.

**Comment by nassost79** [comment]
@cobch hi! Happy I could help! Unfortunately, I haven't managed to do this (and have not bothered to find a solution for it to be frank).

**Comment by Smanar** [comment]
@cobch have you the Legrand gateway ? to update the switch ?

**Comment by cobch** [comment]
Hi,
I have updated the switch with Legrand gateway and managed to fix the config above. I can use the dimming function through deconz app or home asssistant. But when I long press the switch manually no dimming is working. I guess I have to do another config either in home assistant or maybe in deconz GUI. Any advices will be welcome with pleasure.

**Comment by Smanar** [comment]
Ha ?
Lol, first time I see a device working in deconz and not in the reality.
It have worked on Legrand gateway ?

The dimmer feature is working offline, without deconz or home assistant, so it's realy strange.

You can see some return on websocket when you long press the switch ?

**Comment by Smanar** [comment]
An easy thing to try.
Try the dimmer feature but with deconz turned off, to be sure it's not him or HA that trun the switch itself.

**Comment by cobch** [comment]
When I used the switch with Legrand gateway I had to choose the option "light dimmer option" in order to make the dimming functions worked when I was pushing on the switch manually. The standard is "dimming" not activated. See picture below
![IMG_F3C462951F1D-1](https://user-images.githubusercontent.com/50397676/72207909-4a57cf80-349d-11ea-9264-5dad1e848d87.jpeg)

I then removed the switch from Legrand gateway in order to import it in Deconz. As described above I managed to imported it and make the dimming function work in Deconz/Home assistant, but nothing happen when I long press the switch manually )-:

I tried to stop Hassio (and home assistant) but the dimming function is still not working. I have read the following articles and it seems that to activate a wireless dimmer, a code is needed in home assistant:
https://community.home-assistant.io/t/deconz-switch-configuration/93346
https://www.home-assistant.io/integrations/deconz/

But my switch is wired and I wonder what to do next to make it works manually?

You advised me the following:
"You can see some return on websocket when you long press the switch ?"
I am a newbie and will need some help to check that (-:

**Comment by Smanar** [comment]
Yep the switch in the legrand application do the same job than the option 0101 described in deconz.

It's not hardware because it have already worked with the standard gateway.
It's not a configuration problem, because you can dim the light using deconz.

Can you make a try with deconz turned off (just for 1 minute) ?
I don't know Hass , but I m sure somewhere you can find some logs for the plugin ?

BTW can you give me the firmware version of the device ? you can see it in Phoscon too.

**Comment by cobch** [comment]
Ok. I understand. Really strange...
I tried to turn off Deconz but the dimmer still does not react.
The version of the plug is 0029, see below.
![IMG_0764](https://user-images.githubusercontent.com/50397676/72209370-a9254500-34ad-11ea-8f55-4e7503844dde.PNG)

I have managed to check the log, it seems that nothing happen when I press long on the switch manually. I get something only when I switch on or off. See the logs below I get.
![IMG_0765](https://user-images.githubusercontent.com/50397676/72209403-f1446780-34ad-11ea-963c-8d4520238c3e.PNG)

Any ideas?
It seems that I use channel 15, do you think it can be the solution to change it to channel 11 (I saw somewhere that channel 11 should be used)

**Comment by nassost79** [comment]
@cobch I 'm using channel 11 but it still doesn't work. I don't think it makes a difference for the issue we 're trying to solve.

**Comment by cobch** [comment]
Do you have the same problem?

**Comment by nassost79** [comment]
@cobch if we are talking about the lack of dimming control via the actual legrand dimmer switch, yes.

**Comment by cobch** [comment]
@nassost79 So we have the same troubles. Really weird! I hope we will managed to fix that because it is nothing I will implement at home otherwise.

**Comment by Smanar** [comment]
I will update mine to the same version to make tries.
But it's realy something strange, because the dimming feature is hardware, so I don't care channel or gateway.
Perhaps a new setting.

**Comment by cobch** [comment]
@Smanar Thanks. Lets me know if you find something! It will be so great (-:

**Comment by Smanar** [comment]
BTW, if you don't have too much device, I think it's a good idea to go on channel 11, even it works today, not sure you won't have problem later, better to do that when you don't have too much devices.

**Comment by cobch** [comment]
Ok, should I change it in deconz GUI, and choose 11 instead for 15?
I have tried before to change to 11 and lost some pairing with 3 multi sensor from Xiaomi... But for the moment I have only 15-20 sensors totally so I will follow your advice and repair in case of problem.

**Comment by Smanar** [comment]
No, don't worry. I have enought informations.
I have reproduced the problem, I m already on it.

**Comment by Smanar** [comment]
Ok, so sorry, It's realy a mystery for me.
I have sniffed all the traffic with the original gateway, no difference with me. I have tried randomly some setting, no changes.

I can't understand how the hardware can be broked, it s supposed to work off line ...

When you long press, the device don't react at all, it don't send command, don't change level, nothing.

**Comment by cobch** [comment]
So sad. I have looked on the zigate forum and I wonder if there is some compabilties there? Maybe some help?
https://zigate.fr/le-materiel-compatible-zigate/#inventory_filter

Do you know if it is possible to downgrade the version of the switch to the one you used before which was working with both deconz and manual dimming?

**Comment by cobch** [comment]
What is that for? Min-max? Nowhere to set level neither?
<img width="559" alt="Screenshot 2020-01-12 at 20 50 57" src="https://user-images.githubusercontent.com/50397676/72224690-6a5ec000-357d-11ea-9c75-84b2cf6afef8.png">

**Comment by ebaauw** [comment]
As the header says: that the configuration for attribute reporting.  See section 7.2.3 in the deCONZ user manual, available under the _Help_ menu.

**Comment by cobch** [comment]
I will have a look. Thanks. Any ideas about how to activate the dimming function?

**Comment by Smanar** [comment]
Yep, I know zigate, I have one, but to test the dimmer we need the last (not public firmware), I have ask help to pipiche and he will probably help us.
So I will have another hardare to make comparaison.

But I still have some other tests to do, I haven't missed a command, but I have perhaps do too much of them, I need to make tries with API disabled or less effective.

And no, we can't downgrade the device, because we haven't the firwmare ^^, and my GF realy don't like the "max power" light, not good for me.

I suspect something in attribute reporting setting too, it' the only command that are not identical.

**Comment by cobch** [comment]
Ok. So nice to get information from you. I will wait and sincerely hope it will be fix soon so I can move all my dimmer into Deconz (-:

**Comment by Smanar** [comment]
So some news (bad).
I realy don't understnad why the device stop working manualy with deconz (and only it)
I have tried with the API removed, same problem, so it's perhaps from deconz itself, but I can't say If there is something too much or less.
If someone have an idea ...

For the moment I m waiting for a new sniffer.

**Comment by cobch** [comment]
So sad to hear that only on Deconz a problem occurs. Shall we adress a special issue to them? Great to hear that you are trying anyway and good luck!

**Comment by Smanar** [comment]
Ok, so good news, I have finally found the problem.

I m trying to clean the code, to make a PR, I will be away this WE so need some days.

**Comment by cobch** [comment]
Hi Smanar,
Just give us some news when you will have done the work. Do you know whether the wireless dimmer is working or not in Deconz? What about the legrand micromodule?

**Comment by Smanar** [comment]
@cobch the code is finish, it is pull request, you can compile it to test it.
For the moment I m waiting validation or comment.

The wireless dimmer is working too, but you need to update the device (like the wired one)
Micromodule is working too.

**Comment by cobch** [comment]
@Smanar As mentionned in my first post I am a passionnant newbie but a newbie. I will maybe need some guidance to manage what you describe above (-: Or shall I wait for a new update from Deconz? My GF is joking with me everyday about this dimmer that is not working (-;

**Comment by Smanar** [comment]
Looool, I can understand, I had same problem, and I have broked mine just for tests.

To compile my changes:
- you need to be on linux/raspbian.
- you have all the command on githup mainpage "Install deCONZ development package (optional, Linux only)"
- You just need to change the step 1
`git clone https://github.com/Smanar/deconz-rest-plugin.git`
instead of
`git clone https://github.com/dresden-elektronik/deconz-rest-plugin.git`

You can to wait for deconz dev return, but some PR are without answer since 15 days, and not sure they will validate mine.

**Comment by cobch** [comment]
Ok, so I have a problem since I have installed Hass.io on a raspberry Pi and so I have not raspbian... I have to pray or is there another solution?

**Comment by Smanar** [comment]
Arf, right, will be complicated with Hass.io.

I can send you mine, but it was compiled for raspberry 3, and IDK wich one OS you have on your HASS.Io ? It have lot of chance to don't be compatible.

**Comment by cobch** [comment]
Ok. I have HassOs 2.12
I understand if you cannot help me further in that... I asked just in case.

**Comment by cobch** [comment]
Hi @Smanar 
I wonder what I can do to inform Deconz to update their program according to your code?
Shall I close this issue or let it open till they update their version?

Thanks and have a nice week end

**Comment by Smanar** [comment]
Hello,
It's ok the code was already validated, 2 days ago.
Now we just need to wait for next beta version.

You can keep it open, time for you to test the next version.

**Comment by cobch** [comment]
Great. I will wait to close the issue.
Do you know if the wireless switch home/away included in the starting kit is working with Deconz? 

![0DF169FE-7963-4D88-937B-2F04E30F9910](https://user-images.githubusercontent.com/50397676/73614402-fbfea200-45fe-11ea-803b-5185183829e2.jpeg)

**Comment by Smanar** [comment]
Good question ^^.
I think not, but there is a problem. To include it in deconz, you need to reset it, and if you reset it, it become unusable for the Legrand gateway, and I m sure you know how this device is vital for the Legrand gateway.

So no-one have already tried with the one included in the starting kit (In reality I know someone, but he had problem after).

So to resume, if you have only 1 home/away switch, avoid, it's possible but dangerous.

**Comment by cobch** [comment]
I have tried earlier to include it in Deconz but it did not worked. To reconnect  it with Legrand Gateway I just followed the Instructions on #883 
Do not remember where exactly.
It seems I will buy a new wireless switch in order to make my home/away function into home assistant. Safer but more expensive.

**Comment by Smanar** [comment]
You need it to enable the permit join on Legrand gateway (pressing the "middle" button), so how have you re-include it ?

The wireless switch is a little cheaper than the home/away and have been already tested in deconz.

**Comment by cobch** [comment]
Hi @Smanar 
I just follow the instructions given by Legrand to @bsheepdiy:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883#issuecomment-570767677

But as you mentioned earlier, it is better to buy a new wireless switch and use it as a "Home/Away" switch since I can soon connect it to my Home assistant and call some script with it (-:

**Comment by bsheepdiy** [comment]
@cobch 
I've try modified deconz to include/whitelist "Home/Away" device and it doesn't pair ...
Using wireshark dump, the device only send beacon and that's all. So I ve tried using zigbee2mqtt (version 1.9.0) I have the same issue. I think the Home/away packaged with the "Prise control" has a special firmware which is locked to the Legrand official network.

I'll need to buy an additional "Home/Away" device which will be unlocked ...

**Comment by cobch** [comment]
@bsheepdiy same issue for me when I tried!

**Comment by Smanar** [comment]
It's perhaps something missing in code.
The remote do "read attribute request" on cluster 0000 attribute F000 (to other device/gateway) ?
If yes, the problem is from here.

And no, I dont think legrand have locked devices, they have realy try to respect the zigbee protocol. And they don't make special device, if for exemple you loose the "special remote", you can buy one other alone, you don't need to buy a complete kit.

**Comment by cobch** [comment]
In my case I think I will need to spend an extra 50 euros to use the Home/away command within Home assistant but it is still frustrated not to be abble to integrate it into Deconz. Same thing for the smart socket with diamond...

**Comment by bsheepdiy** [comment]
@cobch 
Wait, the Home/away device is not yet supported by deconz ...

**Comment by cobch** [comment]
@bsheepdiy I will buy instead a wireless switch since that one is supported. Do you know if the smart outlet with diamond (gateway) will be supported one day?

**Comment by bsheepdiy** [comment]
@cobch 
I dont think you can separate the gateway from the device. The reset buton is the same ...

**Comment by Smanar** [comment]
> 
> 
> @cobch
> I dont think you can separate the gateway from the device. The reset buton is the same ...

Yep, I have already try to see if we can separate them, but it's realy a device make to work with the diamond.

And I m agree Legrand is realy expensive (the minimum I have found for a simple wireless switch on celiance is 41 Euros), but for the moment it's realy good devices, less battery consumption, they don't leave the network like xiaomi. I have some Legrand device, and I m realy happy with them.

@cobch you can't transform an existing switch in a double one ? and using one of them with a cheaper xiaomi device (with some hack) ?

Pipiche too have tried but this device is a little special

> The Home/Away remote which is provided with the Legrand Hub and which in addition of Home/Away scene allow to switch the Legrand Hub in pairing mode, do not show any Zigbee traffic .

**Comment by cobch** [comment]
@ Smanar I agree Legrand is great quality (except the plastic that breaks that you have to remove when you want to pair it to deconz) and I have already equiped all my flat with wired switches. I just think Legrand should consider to decrease the price of their wireless switch since it is the same price as a wired one. Strange. I will wait the new release of Deconz and order a new switch as soon I have tested that is is working.  Great thanks for @ Smanar that really help/make a great job!

**Comment by Smanar** [comment]
Lol, yep a 5mm wireless switch  cost the same price than a 4cm  one working with 230V ^^.

And I have too broken one too, I have one of them with a little hole make with a drill :) , because I m using the same device for production and tests , so it's easier for reset it.

**Comment by cobch** [comment]
Hi again @Smanar 
I am still waiting for the new update of Deconz to solve my dimmer problem. Do you have any ideas how long will I wait?

Another question. I am now playing with the wireless dimmer from Legrand (-: I bought a new one (to avoid to play with my current home settings) and its version is 25. I do not know how to update it (the current version showing for my other wireless dimmer is 33). Any ideas how to force the update of the firmware version thought Legrand gateway?

**Comment by Smanar** [comment]
The new beta version is just out http://deconz.dresden-elektronik.de/ubuntu/beta/ for ubuntu

Easy to force the update, you just need to let your device on Legrand network for some hours, I think more for wireless device, but the procedure is the same.

And for information @bsheepdiy have discoverer some tips for the home/away switch.

**Comment by cobch** [comment]
Ok. I run Home Assistant and deconz on raspberry pi so I will wait a bit longer (-;
I will wait tomorrow and hopefully the firmware will be updated.

I will have a look for the home/away switch since I am interested by it as well. Thanks for the information.

**Comment by Smanar** [comment]
You have too the version for raspbian > http://deconz.dresden-elektronik.de/raspbian/beta/

**Comment by cobch** [comment]
Hi again @Smanar 
I am now trying to add my wireless switch to deconz. I reset the switch with 8s long press till the red light shows and then press each second till the blue light is showing. The switch does not appear in Phoscon app but appears in Deconz WebUI. 
In Home assistant I only get an entitiy showing the battery level of my switch. It is not possible to use it as a switch since I guess I am missing some installation... 
What to do next to make the switch showing in Phoscon and to make it usable in Home assistant?

**Comment by cobch** [comment]
I added the wireless switch with the "Add new lights" in Phoscon. Is it right or should I include it as a "new switch" instead?

**Comment by cobch** [comment]
![Deconz WebUI (Hass io - deCONZ) - VNC Viewer](https://user-images.githubusercontent.com/50397676/74611817-ca5a0080-50ff-11ea-8dd4-e0567f9ff11c.png)

**Comment by Smanar** [comment]
Hello,
The dimmer is working now on the wired one ?

And you are unlucky ^^, another person have tried, and have the switch displayed in phoscon too.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883#issuecomment-586731584

Add new light is for wired device, so better to use "add new switch".

If it still not working, can you show me the json of the device ?

And this option is not working on wireless device, it's enabled by defaut after the first update by legrand gateway, out of the box, only on/off working, after the update dimmer is added.

**Comment by cobch** [comment]
@Smanar 
> The dimmer is working now on the wired one ?
I did not really get how to install the beta version of Deconz. I'm now on 2.05.72. Should I install the 2.05.73?

I will try to reset the wireless switch and add it as a switch. My problem is now to remove my ghost cluster that are still present on the Deconz webUI. Any tips? They are coming again after deleting them in Deconz )-:

Where can I find the json of the device on HassIO?

**Comment by Smanar** [comment]
Yep, just waiting ^^. This bug can be provoked by neigboard table, just retry in some days.
Or you can re-include the device and make it leave the network again.
The name is grayed ?

Retry first with "add as switch", but you can find it in plugin log, or using a webbrowser with something like
`http://deconz_ip:deconz_port/api/api_key/sensors`

**Comment by cobch** [comment]
Yes the name is grayed.
Should I use beta version of Deconz in order to make the wireless switch work or it is possible already to include it with v 2.05.72?

I will try out the plugin log and the web browser. What should I do with that afterwards? (Sorry for so many questions)

**Comment by Smanar** [comment]
You need the 2.05.73 for the dimmer bug (for the wired one), and the user have used this version too to have the wireless switch on phoscon.

If the device not working you will have a json like that
```
"1": {
        "etag": "026bcfe544ad76c7534e5ca8ed39047c"
        "hascolor": true
        "manufacturer": "dresden elektronik"
        "modelid": "FLS-PP3"
        "name": "Light 1"
        "pointsymbol": {}
        "state": {
            "alert": "none"
            "bri": 111
            "colormode": "ct"
            "ct": 307
            "effect": "none"
            "hue": 7998
            "on": false
            "reachable": true
            "sat": 172
            "xy": [ 0.421253, 0.39921 ]
        }
        "swversion": "020C.201000A0"
        "type": "Extended color light"
        "uniqueid": "00:21:2E:FF:FF:00:73:9F-0A"
    }
```

I need it to see what is missing on your device (if it don't work)

**Comment by cobch** [comment]
Ok. I understand.
The json file is possible to get through plugin log, or using a webbrowser with something like
http://deconz_ip:deconz_port/api/api_key/sensors. Am I right?

**Comment by Smanar** [comment]
yep, but I need it only if it don't work, and it works for other users, so I think yours will too.

**Comment by cobch** [comment]
Great! I finally make it work in Deconz. It appears now as a switch called "REMOTE SWITCH".
My only problem now is how to use it in HA since it appears only as a sensor with a batteri level when I want to create an automation. See below an example for the wireless Legrand switch and another for an Ikea switch I used before.

Legrand wireless switch:
<img width="487" alt="Screenshot 2020-02-17 at 22 34 09" src="https://user-images.githubusercontent.com/50397676/74687927-21320980-51d6-11ea-9d32-3dae12c01ece.png">

Ikea wireless switch:
<img width="488" alt="Screenshot 2020-02-17 at 22 38 37" src="https://user-images.githubusercontent.com/50397676/74687969-46267c80-51d6-11ea-8897-d13c3756fe86.png">

**Comment by cobch** [comment]
It seems as well as the remote switch does not connect to the network:
<img width="255" alt="Screenshot 2020-02-17 at 22 43 08" src="https://user-images.githubusercontent.com/50397676/74688187-06ac6000-51d7-11ea-921c-0b3b13496b84.png">

**Comment by cobch** [comment]
Two more weird things:
1- The dimmer function of my wired switch is still not working in deconz after the 2.05.73 upgrade.
2- The remote wireless switch does not connect to my Zigbee network (as shown above)

When I try to log the event for both of them and I press ON/OFF, I do not get any response an no .json file are created... any clues?

**Comment by Smanar** [comment]
For the connexion it can be normal, this device don't make notification at all, if you don't use it during 1 day, it can stay 24h without notification, so deconz can consider it offline. And the name is not grayed, so for deconz the device is still connected (for the moment)

But can you show me the JSON on the device from sensor list ? You have it else you can't see it on HA.
I think the Json is incomplete, when you make pairing procedure make an on/off for better recognition.

For the (1), it's easy, set phoscon on permit join, if the led go green we have a problem ^^. But I m sure the led go blue, it mean the pairing was bad, just remove the device and include it again with new version.

**Comment by cobch** [comment]
Ok @Smanar. I have tried to repair my wireless switchs. Both are now showing the version in Phoscon, they are also connected in Deconz (-:

<img width="241" alt="Screenshot 2020-02-18 at 20 34 16" src="https://user-images.githubusercontent.com/50397676/74772473-5bf87800-5290-11ea-9239-7020509dd2d0.png">

I get these following event when I short press On and then Off:

_{
    "event_type": "deconz_event",
    "data": {
        "id": "remote_switch_hall",
        "unique_id": "00:04:74:00:00:89:48:be",
        "event": 1002
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-18T19:48:03.429847+00:00",
    "context": {
        "id": "3e71710c31db46449022cf3e26acc86a",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 8:48 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "remote_switch_hall",
        "unique_id": "00:04:74:00:00:89:48:be",
        "event": 2002
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-18T19:48:02.382161+00:00",
    "context": {
        "id": "2a690b72361644a99c953c69a0ca07de",
        "parent_id": null,
        "user_id": null
    }
}
Event 1 fired 8:47 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "remote_switch_home_away",
        "unique_id": "00:04:74:00:00:79:20:1c",
        "event": 2002
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-18T19:47:51.635544+00:00",
    "context": {
        "id": "e579433afe974a7193bc2df7f8d964cd",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 8:47 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "remote_switch_home_away",
        "unique_id": "00:04:74:00:00:79:20:1c",
        "event": 1002
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-18T19:47:49.799497+00:00",
    "context": {
        "id": "aff50224ba504dd7a606a14ca7b3978a",
        "parent_id": null,
        "user_id": null
    }
}_

What is next step for me to be able to enable them as real switch?

**Comment by cobch** [comment]
> For the (1), it's easy, set phoscon on permit join, if the led of the switch go green, we have a problem ^^. But I m sure the led go blue, it mean the pairing was bad, just remove the device and include it again with the 2.05.73 version (and after use deconz to enable the dimmer).

I have managed finally to make the dimmer work ((((-: I just followed the instruction given above. Thanks a million. Only need to make the wireless working now...

**Comment by Smanar** [comment]
You still miss something ?

In HA I think event on = 1002 and off = 2002
And you will have 2 other value for short press and long press.

I think it's enought for HA.

**Comment by cobch** [comment]
Actually not (-:
I have been confused since in HassIO there is an automation editor that use to make a switch editable directly in an automation without the need of calling the "deconz_event". I have managed to create a manual automation and everything is working wonderful. I can now close this issue (a bit sad but I am sure I will need more help for eventually the home/away wireless switch (-;

**Comment by cobch** [comment]
I tested the long press of the wireless switch and it returns each time 2 events. Do you have any idea how to use it and which event to call for an automation?

_{
    "event_type": "deconz_event",
    "data": {
        "id": "remote_switch_hall",
        "unique_id": "00:04:74:00:00:89:48:be",
        "event": 1003
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-18T22:54:27.103879+00:00",
    "context": {
        "id": "a1355fb9e4714d00b60c6645fd42bcf8",
        "parent_id": null,
        "user_id": null
    }
}
Event 9 fired 11:54 PM:
{
    "event_type": "deconz_event",
    "data": {
        "id": "remote_switch_hall",
        "unique_id": "00:04:74:00:00:89:48:be",
        "event": 1001
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-18T22:54:26.175584+00:00",
    "context": {
        "id": "d57f09e6920549558e906c1ad4632c04",
        "parent_id": null,
        "user_id": null
    }
}_

**Comment by cobch** [comment]
I managed with the 1001 event to create a long press automation. No worry about that!

**Comment by Smanar** [comment]
I think it 's button pressed (long press) and button released.

**Comment by cobch** [comment]
Yes it is! Great thanks for all the help. I am now looking forward to be able to include the home/away wireless switch (-;
