### ISSUE TITLE
Deconz config folder and mounts for synology nas

### ISSUE THREAD

**Issue by IIIdefconIII** [dresden-elektronik/deconz-rest-plugin#2310]
Hi, first of all, i love this deconz package.

I am stuck with a question, whenever i update my deconz image from a Synology NAS device it removes my settings, cause I am clearing the deconz cache,
Previous this was for all docker containers for synology.
I  have SMB share called docker, withing that i have several folders from several docker containers which saved its important user settings in that folder. I will show you a example down below from Radarr. So whenever i update Radarr to a newer image on synology and i "clear" the docker cache, I am getting the same settings because of the settings i have in the docker container. Like this:
![image](https://user-images.githubusercontent.com/9917659/72195328-0966a900-3412-11ea-9203-d26f70022830.png)

The folder that include the user settings are mounted a a folder on my NAS:

Now i tried several settings for the deconz container, as i updated it and cleared the cache i lost my whole  config.

![image](https://user-images.githubusercontent.com/9917659/72195363-31eea300-3412-11ea-8e5d-8f53e5e087d6.png)

When i ssh in to my nas i cannot find any docker folder that is related with the settings of deconz. Maybe is obvious saved somewhere but i cannot find it.

Which setting can or should i use to save the deconz settings to a mounted SMB folder.

This would help me alot. Thank you in advance and love your project, is there any play i can buy you a coffee/beer?

**Comment by kTitan** [comment]
If you use the docker image from https://hub.docker.com/r/marthoc/deconz/ you should need only the volume mount for /root/.local/share/dresden-elektronik/deCONZ
Have a look in its Readme, there is a example for the volume mount.

**Comment by IIIdefconIII** [comment]
Thank you, indeed now its saving to my path.
![image](https://user-images.githubusercontent.com/9917659/72482524-4d84ef80-37fe-11ea-96a4-5b2bda3c3db0.png)
![image](https://user-images.githubusercontent.com/9917659/72482531-537ad080-37fe-11ea-9d0f-034c0534d94b.png)


Case closed added some screenshots if anyone ever needs it
