### ISSUE TITLE
NodOn philips hue switch.

### ISSUE THREAD

**Issue by vandalon** [dresden-elektronik/deconz-rest-plugin#2314]
Hi Guys,

Anyone tested this switch by any change?

https://nodon.fr/wp-content/uploads/2019/10/Fiche-technique-EN-CWS-PhH-191030.pdf

Seems like a nice one ;)

**Comment by addellll** [comment]
I have not tried it, but i am quite sure it use same electronics like the Hue Tap and all other Friends of Hue switches like Niko, Vimar and so on.

**Comment by vandalon** [comment]
Ok. I'll order one and let you know :)

**Comment by jensflorian** [comment]
Did the switch appear in phoscon?
