### ISSUE TITLE
 Tradfri remote control automatically switches devices

### ISSUE THREAD

**Issue by snador1977** [dresden-elektronik/deconz-rest-plugin#2318]
The Ikea Tradfri remote control automatically switches various devices after teaching via Phoscon. In my case these are 6 Zigbee sockets. I haven't made any further adjustments. I tried this with 3 different remote controls and the result is always the same.

**Comment by jensflorian** [comment]
Did you reset them before pairing with  deconz (https://www.youtube.com/watch?v=vKk5TJULblQ)?
In bundled offers, they may be sold already paired with the associated devices.
