### ISSUE TITLE
Can't connect Konke Motion Sensor 

### ISSUE THREAD

**Issue by jaschkopf** [dresden-elektronik/deconz-rest-plugin#2319]
Hey. I use a Conbee 2 USB Stick with a Raspberry Pi in headless mode without GUI. I bought three Konke Motion Sensors and I'm not able to connect them to my Conbee. How can I connect them?

**Comment by Adminiuga** [comment]
Konke would connect only if the network is running on Channel 11, 15 or 20

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
