### ISSUE TITLE
Problem with connection of all devices 

### ISSUE THREAD

**Issue by erazorv** [dresden-elektronik/deconz-rest-plugin#2326]
Hello,
I don't know if there is a Issue to this yet but I have sporadically the problem that all devices which are connected to deconz(RasBi), don't work after a period of time. Only by switching off and on the lamps it works again after some time.
The problem occurs about every 2 months

Is the problem known?

thanks era

**Comment by osos** [comment]
Since which version?

**Comment by erazorv** [comment]
Maybe since the last firmware update version 2.5.54 
I have the Problem a Long time 
Current installed Version 2.5.72

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
