### ISSUE TITLE
Not in Network

### ISSUE THREAD

**Issue by haasi0000** [dresden-elektronik/deconz-rest-plugin#2328]
Hey guys,

I spent a lot of hours without any success.
I use the conbee 2 USB tongle und a raspbee 3 together with hombebridge.
Till yesterday everything worked but now the usb stick can't connect.

The USB Tongle is recognized on the raspberry.

There are my settings. I also uninstall and reinstall the deconz software but also without any success.

<img width="907" alt="Bildschirmfoto 2020-01-16 um 12 20 20" src="https://user-images.githubusercontent.com/59959989/72521091-12fd7000-385b-11ea-924d-1f889fc88d1b.png">

<img width="900" alt="Bildschirmfoto 2020-01-16 um 12 19 43" src="https://user-images.githubusercontent.com/59959989/72521099-185aba80-385b-11ea-9c63-14e3ce0c56de.png">

<img width="860" alt="Bildschirmfoto 2020-01-16 um 12 19 18" src="https://user-images.githubusercontent.com/59959989/72521117-1ee93200-385b-11ea-9a95-33c1b63245bb.png">

Thanks for your help!!!!

**Comment by Smanar** [comment]
I don't think it's your response but there is something strange in your config, device type > "router" instead of "coordinator"

**Comment by manup** [comment]
Indeed it should be coordinator. Have you tried the load button in the first screenshot?
