### ISSUE TITLE
Konke Kit Pro Motion Sensor

### ISSUE THREAD

**Issue by dbweb-ch** [dresden-elektronik/deconz-rest-plugin#2329]
This sensor was already requested:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1607

But this request was closed without having a working solution.
I've got that sensor and can see it in deconz, but not in the api.
Node Info:
![image](https://user-images.githubusercontent.com/57174794/72523468-27903700-3860-11ea-80d8-3c316deeb4a5.png)
Cluster Info 0000 Basic:
![image](https://user-images.githubusercontent.com/57174794/72523520-4abae680-3860-11ea-9f42-237baa4ab837.png)
Cluster Info 0001 Power Configuration:
![image](https://user-images.githubusercontent.com/57174794/72523602-71791d00-3860-11ea-9485-1e819203104b.png)
Cluster Info 0500 IAS Zone:
![image](https://user-images.githubusercontent.com/57174794/72523672-979ebd00-3860-11ea-8927-be5839cd6945.png)

It gets updated when I move my Hand over (Last Seen gets Updated) so it seems to be working, but how can I get it to the API and Finally to ioBroker?

**Comment by gijsje** [comment]
Yes please

**Comment by Juanezm** [comment]
👏🏻

**Comment by realwax** [comment]
+1 dear Devs, please implement it in deconz and phoscon.

**Comment by mapsrof** [comment]
+1

**Comment by Mimiix** [comment]
Is this already implemented?

**Comment by Mimiix** [comment]
Without a reply on the above, i'll close the issue.

**Comment by Doreinie** [comment]
H, When will this be working in the Phscon App?
I can see it in Deconz and iobroker. in there surprisingly the battery value appears as 0 %.
If needed for the developper I can provide screenshots, data etc with instruction

**Comment by SilverWx** [comment]
I have no battery reported for konke in hassio

**Comment by Doreinie** [comment]
Today I see the Konke movement sensor in Phoscon. great and Thanks!

**Comment by SilverWx** [comment]
same but no battery
