### ISSUE TITLE
Serial port configuration with ConBee?

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#233]
HI,
the readme has a step to change the serial port config:
> Important The serial port must be configured as follows to allow communication with the RaspBee.

Does this step also apply for the ConBee?

Thanks

**Comment by andrejem** [comment]
No. When I did this step with my Conbee it did not work. Changed back to default setting (no/no). Then i got the REST api working for me.

**Comment by manup** [comment]
It is only needed for RaspBee.

Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
