### ISSUE TITLE
deconz doesn't pick up the OTA file

### ISSUE THREAD

**Issue by donnib** [dresden-elektronik/deconz-rest-plugin#2330]
@manup i have my files in /home/pi/otau

I click on one of the lights in the OTAU list and then Query but it doesn't populate the file so it can update but i can browse to it and ask it to update. What can i do so it picks it up also i can't remember if i have to click each of them and do Query or can it find the files self and start update ?

I run 2.05.72

**Comment by manup** [comment]
In case of IKEA OTA files you may have to restart deCONZ once after the files are copied into the otau directory. This is because the files are transformed if needed into a more  standard naming format.

**Comment by donnib** [comment]
I did that few times, where should i see the change be made ?

**Comment by manup** [comment]
Directly in the otau/ directory, there should be new files witch names like xxxx-yyyy-...zigbee

**Comment by donnib** [comment]
![image](https://user-images.githubusercontent.com/252702/72600991-dee68580-3914-11ea-80a1-6340dc19f97d.png)
i don't see them, permissions issue or ? is there a log file i can check if there are errors ?

**Comment by ebaauw** [comment]
Is the OTAU server enabled?  Check under _Advanced Settings_ in the _Settings_ page in the old web app.

**Comment by donnib** [comment]
@ebaauw thx Erik but where is that ? _Advanced Settings_ where ? I looked different places and couldn't find that.

**Comment by ebaauw** [comment]
And deCONZ is running under user `pi`?

**Comment by donnib** [comment]
I am running the official image from dresden, so i don't know how it's setup.

**Comment by donnib** [comment]
more ideas ?

**Comment by g3wd** [comment]
I'm having the same issue. 
Deconz is run by user `pi`
otau is enabled in old web interface
deconz 2.05.75
i use a rasbee 1 with a raspi b+ (armv6)

**Comment by g3wd** [comment]
Solved it, otau folder was owned by root, changed it to pi:pi `sudo chown pi:pi otau/` restarted deconz and like that the -zigbee files could be created.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
