### ISSUE TITLE
help installing on ubuntu server

### ISSUE THREAD

**Issue by jscherry** [dresden-elektronik/deconz-rest-plugin#2335]
i've tried several ways of installing for headless ubuntu server 64bit. i can install the software but can't figure out how to get the info needed to do the integration with hass.io addon. how do i get the host ip and api key. i have a brand new conbee 2 plugged into a hp microserver. the sever has the conbee 2 connected and showing up properly? please help

**Comment by SwoopX** [comment]
That may be of help:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2121#issuecomment-564770517
