### ISSUE TITLE
Possible to include LQI / RSSI in websocket events?

### ISSUE THREAD

**Issue by jkinghed** [dresden-elektronik/deconz-rest-plugin#234]
I did some testing on LQI levels with a IKEA Trådfri remote and based on the levels I saw, I think it could be possible to identify which room the remote is in based on this.

I'm using Node-Red to listen for events using the websocket, and using the LQI / RSSI information would then mean that I could control different devices depending on the room the remote is in - for instance my Sonos speakers. 

Since it seems this information is already in each event ([ref](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/23#issuecomment-320491343)) I'd think it would be possible to include in the websocket event?

It might not be 100% accurate for short distances, but in a house or a larger apartment, the LQI/RSSI signatures / intervals should be specific enough to identify an area for controlling lights or music in that area. 

Thanks.

**Comment by manup** [comment]
Late answer: LQI / RSSI will only tell the last hop and might not be useful without considering all links in the mesh.

Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
