### ISSUE TITLE
Phoscon app changing IP

### ISSUE THREAD

**Issue by joselito11** [dresden-elektronik/deconz-rest-plugin#2341]
Deconz addon for Home Assistant on Ubuntu server.
Phoscon deconz app is changing IP address on every system reboot. It is 172.33.30.1 or 172.33.30.2., somethimes 172.33.30.3 Any option to make this IP stable? Because I must readd deconz integration on every system reboot.

**Comment by Vartkat** [comment]
Same here, ubuntu 19 dockerized Deconz.

**Comment by Mimiix** [comment]
Unfortunately, this is a docker issue and not a issue with the plugin itself. Closing it.
