### ISSUE TITLE
Network Id is changing randomly

### ISSUE THREAD

**Issue by Larsn1** [dresden-elektronik/deconz-rest-plugin#2349]
Hi there,
I had to reset my gateway yesterday  (raspberry 3 with rasbee, 2.5.72) and configure everything as new. Yesterday evening I noticed that the network I’d has. changed. I added the bulps and everything again just to see that while I was working the network Id has changed again. Will provide logs of today later this evening.

Wife is not happy ...

**Comment by Larsn1** [comment]
Tried to add the log yesterday evening just to find out that the logging was disabled. Jumped back to 2.5.69 because of fyrtur blinds and added one room again. Let’s see what happens today.

**Comment by Larsn1** [comment]
Network I’d is the same as yesterday. Everything is still reachable and running well. Seems like 2.5.69 is safe and breaking changes have been made later.

**Comment by Larsn1** [comment]
Two days and everything is running well. As I havent seen a commit that could influence that it probably is a misconfiguration on the user side. Maybe you can find out what could have caused this. Meanwhile I stay back from newest versions.

**Comment by easybeat** [comment]
Hi,
I think I did face the same problem after I did update to 2.5.72 on Rasbee and didn't understand at all what it caused. But reading your post I understand.
I am back on 2.5.64, rejoined every device and it is working fine since 2 weeks now!
Thanks

**Comment by Larsn1** [comment]
Everything is still working. Unfortunately I don’t expect the developers to answer here because we don’t have the log of the moment where the device is changing the network id. I hope it was helpful to narrow down the version that might could be affected
