### ISSUE TITLE
Are Osram Lightify Motion Sensor and Lightify Switch (4 button) supported by the deCONZ REST API plugin ?

### ISSUE THREAD

**Issue by oleg77s** [dresden-elektronik/deconz-rest-plugin#235]
Osram Lightify Motion Sensor and Lightify Switch (4 buttons) in deCONZ:
![2017-10-18-201045_1920x1080_scrot](https://user-images.githubusercontent.com/23496372/31782223-04e6dcc8-b503-11e7-89a5-3b56a869d1d6.png)
![2017-10-18-201101_1920x1080_scrot](https://user-images.githubusercontent.com/23496372/31782227-09910c26-b503-11e7-9e85-4007bcfadbb3.png)

Are Osram Lightify Motion Sensor and Lightify Switch (4 button) supported by the deCONZ REST API plugin ?

**Comment by manup** [comment]
The motion sensor is supported in the REST API, you might have to 

1) start sensor search (open network in the webapp);
2) power cycle the sensor by pull out battery press side button, put battery in again

It kinda works but in my short tests the sensor didn't work reliable compared to hue one.

The switch isn't supported currently.

**Comment by oleg77s** [comment]
Ok, 
Thanks
