### ISSUE TITLE
Develco?

### ISSUE THREAD

**Issue by eddiex666** [dresden-elektronik/deconz-rest-plugin#2350]
Hi,

sorry for this question here, i was'nt able to find a other forum from deconz.

I would like to get all my devices from deconz into Domoticz or some other smart home software.
I have connected the plugins, but i can only see the devices from Phoscon?

Inside deconz i have many devices, but i cannot see them.

is there any way to "un-filter" and get all devices from the app deconz and into domoticz?

**Comment by Smanar** [comment]
Hello, 
You can see your device in Phoscon (the web app) but not in deconz (the desktop application) ?

For domoticz, if it works on phoscon/deconz, better to ask in the plugin section on domoticz forum. But for information, if it works on deconz, and if you use correct setting on the plugin, all the deconz devices will be visible on domoticz, there is no filter.

**Comment by eddiex666** [comment]
Hi.

I can ses the devices in deconz app 

And not in phoscon web app :-)

I guess the phoscon app not support all devices.


Domoticz deconz plugin only ser the valid devices in phoscon.

Can this be fixed?



Den 21. januar 2020 09:06:54 CET, skrev Smanar <notifications@github.com>:
>Hello, 
>You can see your device in Phoscon (the web app) but not in deconz (the
>desktop application) ?
>
>For domoticz, if it works on phoscon/deconz, better to ask in the
>plugin section on domoticz forum. But for information, if it works on
>deconz, and if you use correct setting on the plugin, all the deconz
>devices will be visible on domoticz, there is no filter.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2350#issuecomment-576564666

-- 
Sendt fra min Android-enhet med K-9 e-post. Unnskyld min kortfattethet.

**Comment by Smanar** [comment]
Ha ok so the devices are visible in deconz and domoticz but not Phoscon ?
If it's that, I m sorry, but it's something "normal", you are right Phoscon not support all devices and only deconz dev can do something.
