### ISSUE TITLE
New device support request: STSS-MULT-001

### ISSUE THREAD

**Issue by kkellner** [dresden-elektronik/deconz-rest-plugin#2354]
SmartThings Multipurpose Sensor 
Model: STSS-MULT-001
Description: The Multi can detect movement as in open/close, vibration, orientation or angle, and temperature all in one

https://support.smartthings.com/hc/en-us/articles/205382174-SmartThings-Multipurpose-Sensor-previous-generations-

![image](https://user-images.githubusercontent.com/9540241/72861169-535b5480-3c86-11ea-84f9-deea30eb5028.png)

![image](https://user-images.githubusercontent.com/9540241/72861085-1a22e480-3c86-11ea-89f3-5b5d50e95201.png)

![image](https://user-images.githubusercontent.com/9540241/72861102-24dd7980-3c86-11ea-9dda-9d1d3667711d.png)

**Comment by YayC** [comment]
I also have this old smart things multipurpose sensor! What are the chances support will be added for it?
