### ISSUE TITLE
Switch group default behavior when bound

### ISSUE THREAD

**Issue by thedannymullen** [dresden-elektronik/deconz-rest-plugin#2358]
Hello I have deconz setup and fully working with no issues.  I want to make an improvement to my system.  I have the Phillips Hue remote setup as described here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1744.  It is setup so that even when deconz is not running the lights toggle on and off.  

My question is can I modify this group json below to force lights always to 25% brightness on one click: 
`{
    "action": {
        "bri": 127,
        "colormode": "hs",
        "ct": 0,
        "effect": "none",
        "hue": 0,
        "on": true,
        "sat": 127,
        "scene": null,
        "xy": [
            0,
            0
        ]
    },
    "devicemembership": [
        "6"
    ],
    "etag": "79eb24fafd93e99bcebe1f241d194b02",
    "id": "27510",
    "lights": [
        "10",
        "11",
        "13",
        "12",
        "14",
        "15",
        "17",
        "18"
    ],
    "name": "RWL020 16",
    "scenes": [],
    "state": {
        "all_on": true,
        "any_on": true
    },
    "type": "LightGroup"
}`

If I can I am not sure what parameter to modify.

**Comment by ebaauw** [comment]
No, if you control the lights directly from the dimmer switch, you’re stuck with the commands that the switch sends.  If you want something else, you need to setup rules, which, of course, only work when deCONZ is running.
