### ISSUE TITLE
Is it possible to configure a ConBee2/deCONZ ZigBee Network whithout the phoscon webinterface?

### ISSUE THREAD

**Issue by Andreyooo** [dresden-elektronik/deconz-rest-plugin#2365]
The REST API only supports lighting so far. Is it possible to configure the ZigBee Network without a graphical interface? Is there an API for manual communication?

**Comment by Smanar** [comment]
Depend of feature you want, but I think all phoscon feature can be used with API.
Open network, change channel, ect ...

**Comment by Smanar** [comment]
Depend of feature you want ?
But I think all you can make with phoscon can be made with API, open network, change channel, ect ...

**Comment by ebaauw** [comment]
Phoscon is just another API client; deCONZ runs perfectly well without it.  The link to the API documentation is in the README.

**Comment by Andreyooo** [comment]
Oh I see, the REST API does support all kinds of devices, I misread the repo title.
So this means I can access all kind of ZigBee 3.0 devices through the API, even devices that the Phoscon webinterface does not support yet?

**Comment by ebaauw** [comment]
Yes.  The REST API plugin is open source, so we can add API support for new devices ourselves.  Phoscon isn’t and can only be updated by dresden elektronik, so adding support for new devices typically takes a bit longer.

**Comment by Andreyooo** [comment]
Okay, ty very much :)
