### ISSUE TITLE
FYRTUR IKEA after restart not reachable

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2368]
The window shutters from IKEA are unavailable after restart.
I am using the latest version of Deconz.
That is not shown in the Phoscon-App (there they are still online, but not assessable.

But in ioBroker the indicator show "FALSE"

Maybe time to give the shutters new icons as well, they coming up with a lamp-symbol
![Unbenannt](https://user-images.githubusercontent.com/42386692/73008495-f939cb00-3e0e-11ea-8764-dd8efc678640.png)

**Comment by handy80** [comment]
Hi Michaelnorge, I cannot help you but can you point me to a guide how I can get my fyrtur set (blind, switch and repeater) connected to deconz/phoscon I would like to control the blind with the switch and by ioBroker as you but I unfortunately don't know how. The set components are paired all right and work well.

**Comment by Michaelnorge** [comment]
Hello.
You don¨t need that stuff, just the shutters.
Press both buttons on the shutters about 5 seconds until the light starts turning on.
Let ioBroker find "lamps" - finish!

**Comment by greetoz** [comment]
I have a similar problem. After a restart from deconz the blinds are not always reacting. I have to go into the VNC GUI, Go into basic cluster info and press the READ attributes then the manufacturer strings etc get filled in and the blind is usable again.

Before pressing the read button
![smartblind](https://user-images.githubusercontent.com/6904465/73118346-445cf680-3f53-11ea-9248-2122b3423ff8.JPG)

After pressing the read button
![smartblind2](https://user-images.githubusercontent.com/6904465/73118347-445cf680-3f53-11ea-9761-ce6d432f5c45.JPG)

**Comment by Michaelnorge** [comment]
I could¨t get installed VNC GUI for some reason.
I just reconnect the shutters by pressing both buttons of the shutters.

But it is strange that I have three shutters, but just two of them are disconnected after reboot.

**Comment by handy80** [comment]
thanks, tried that and stuck in the same situation (even if I messed up and paired twice the old light shows reachable = 'true' and the new shows 'false'
Both lights are not working from within ioBroker and the PhosconApp.
Any news here?

**Comment by ginkel** [comment]
Are the blinds connected directly to the ConBee or to another router?

**Comment by Michaelnorge** [comment]
> 
> 
> Are the blinds connected directly to the ConBee or to another router?

Directly...

**Comment by Smus** [comment]
I have the exact same issue. I connect Ikea fyrtur blinds to conbee2, everything work.. restarts and all is lost again

**Comment by Michaelnorge** [comment]
... but its easy to get them connected again. Just click on "pair" in the Phoscon App and go around and keep pushing the two buttons on the shutters until they start moving. 
Its even possible to pair a lot of them at the same time :-)

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
