### ISSUE TITLE
deCONZ Rest API and Xiaomi WXKG03LM  Aqara Smart Light Switch Wireless 

### ISSUE THREAD

**Issue by oleg77s** [dresden-elektronik/deconz-rest-plugin#239]
It seems, that deCONZ Rest API don't support  Xiaomi WXKG03LM  Aqara Smart Light Switch Wireless 
b.r.
oleg

**Comment by ebaauw** [comment]
See also #165.

**Comment by oleg77s** [comment]
Aha, i see
