### ISSUE TITLE
Deconz ignore previous API entry after a restart.

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#2390]
Hello, I have something strange again. (Long version here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/883#issuecomment-578411698)

An user is making some code for a new device support.
When he make the inclusion, all is fine, but after a restart, the device stop working, and on deconz he have the NWK adresse instead of name.

After association, all is good :
![association_ok](https://user-images.githubusercontent.com/58689380/73123085-1d6ee680-3f8c-11ea-9e2a-01802440c1a7.png)
After deconz restart
![unrecognized_after_deconz_restart](https://user-images.githubusercontent.com/58689380/73123088-219b0400-3f8c-11ea-844e-7472c3db2ac5.png)

There is some log to https://github.com/dresden-elektronik/deconz-rest-plugin/files/4112125/err.log

All informations seem to be saved and loaded on log.
This device make a device announce every time we use it, it's something normal, there is another that do same, but works without problem.

Deconz use the uniqueID to reconize device ? so how this can happen ? (and at a moment deconz see the NKW change and update the sql database).
On my side, I have some device that are out of network since many month, and deconz are still using correct name.

I can't say if it's from deconz, the new code or the device.

I take all possible ideas/suggestions ^^.

**Comment by Kane610** [comment]
Can you enable debug for deconz integration and share the logs describing the device both from when it works and when it doesn't

**Comment by Smanar** [comment]
No-one have already something like this ?

It's not like all device are lost. Because in this situation devices are out of network, but name in deconz appear.

And there is no message in log about an ignored entry, or something like that.

**Comment by Smanar** [comment]
@manup , we are realy blocked.
I have compared the zll.db file before and after the restart, files are same.

There is something in deconz code that can make it ignore an entry present in database ? Or do I need to search in API code ?

**Comment by manup** [comment]
Some devices needs to be configured in the `sqliteLoadAllSensorsCallback()` in database.cpp file, similar to when they are configured while joining them. I guess this part might be missing?

**Comment by Smanar** [comment]
Thx, we will check that.

So for you the problem is from a missing code in API, even it works before the restart, some data would be used but not memorized ,

**Comment by Smanar** [comment]
Ok, so was exactly that.
It miss the cluster WINDOW_COVERING_CLUSTER_ID.

Thx again.
