### ISSUE TITLE
Removing double conbee stick on login screen

### ISSUE THREAD

**Issue by Luigi-01** [dresden-elektronik/deconz-rest-plugin#2391]
When I  login, there are two conbee sticks.
One old from a previous installation and the new installation.
How to remove the old conbee stick from the login screen.
Where this information is stored is unknown to me.
How can I corrected this. Very irritating.
Be. Walter

**Comment by rogro82** [comment]
If i remember correctly clearing browser cache did the trick for me. You can test this by visiting the app with a different browser or using incognito mode.
