### ISSUE TITLE
IKEA buld connected, but I cannot turn it on/off

### ISSUE THREAD

**Issue by hver** [dresden-elektronik/deconz-rest-plugin#2398]
Hi, I have Conbee II stick running in RPi4 as Home Assistant addon. I added Hue bulbs to Deconz and they work flawlessly. 
But I have a problem with my new Ikea bulb, I can add it to Deconz, but cannot control it. Deconz identifies the bulb as **"TRADFRI bulb E14 W op/ch 400lm", Version 1.2.214**. Maybe it worth to mention, that I can only add this bulb after 6x on/off cycle. 
I logged in to the Deconz app via VNC, and tried some cluster commands from UI, I can run all "read" commands, but if I try to issue some "write" commands, nothing happens - the bulb stays 100% bright. 
Do you have some ideas how can I get the bulb to respond to commands? Maybe it is just broken? 

<img width="431" alt="Screenshot 2020-01-31 at 19 44 32" src="https://user-images.githubusercontent.com/3062750/73566853-39c7c300-4465-11ea-86fa-3c5bdaa070a4.png">
<img width="437" alt="Screenshot 2020-01-31 at 19 42 23" src="https://user-images.githubusercontent.com/3062750/73566854-3a605980-4465-11ea-9305-bbed8e9b0b5e.png">
<img width="432" alt="Screenshot 2020-01-31 at 19 40 08" src="https://user-images.githubusercontent.com/3062750/73566856-3a605980-4465-11ea-9a3b-eb9bf38b6a10.png">
<img width="843" alt="Screenshot 2020-01-31 at 19 38 31" src="https://user-images.githubusercontent.com/3062750/73566858-3a605980-4465-11ea-8a5a-8b665b6d3542.png">

**Comment by MunkeyBalls** [comment]
I'm might be running into similar problems with deconz II (2.05.72) on rpi3 with the marthoc/deconz docker image. 

I have a TRÅDFRI bulb E27 CWS opal 600lm running version 1.3.009 and for some reason I can turn the light on, but cannot turn it off anymore afterwards. Weird thing is, after I change the color I can turn it off perfectly fine. I can reproduce this every single time.
The two other tradfri bulbs I'm using are working fine, but they different bulbs, namely TRÅDFRI bulb E27 WS opal 980lm lights running 2.3.007

I only just received my deconz, so I'm still getting used to how the apps work. As far as I can see my lights are all up to date (updated via deconz). I didn't figure out yet how to get to the cluster settings. Whenever I go to the cluster info via VNC it asks me to select a cluster, but not sure where I need to do this.

**Comment by stormmurdoc** [comment]
Same probleme here with a OSRAM Classic A60 TW. Other bulbs are working finde.
V1.03.07
