### ISSUE TITLE
[Device Support Request] Please ad support for Wattle zigbee smoke detector

### ISSUE THREAD

**Issue by htreo** [dresden-elektronik/deconz-rest-plugin#2400]
![Screen-2-1-2020_20135_PM (2)](https://user-images.githubusercontent.com/54037687/73592715-53b4e480-44fd-11ea-8b84-8b7a7a5af301.png)

https://wattle.com/support-main/wattle-devices/smoke-detectors/smoke-alarm/

**Comment by SwoopX** [comment]
Hi there,

this is not a Develco device. Based on your screenshot, I'd put my bet on a Heiman device (which is already supported). Please provide the screenshots as described in the wiki for requesting device support to be certains. Also make sure the attributes have been read before taking these.

**Comment by htreo** [comment]
It looks like Heiman smokedector. But wattle is the brand you can buy in Scandinavia. But can't be seen in phoscon app /  but shows in the home assistant.

**Comment by SwoopX** [comment]
> But can't be seen in phoscon app / but shows in the home assistant.

That's because Phoscon is closed source. As it is available in HA, I conclude there's nothing to do for us.
