### ISSUE TITLE
Heiman gas sensor HS1CG-M support

### ISSUE THREAD

**Issue by stickpin** [dresden-elektronik/deconz-rest-plugin#2403]
Hi,

I've received a new Heiman gas sensor HS1CG-M. I was able to connect it to deConz, but it seems that whitelisting is needed as some of the HS1CG series already supported.

The sensor is working well and detecting a regular natural "cooking" gas correctly.

Here are the details:
![IMG_1128](https://user-images.githubusercontent.com/630000/73605400-0ccafb80-459e-11ea-9ba7-4659b64f086a.jpeg)

<img width="482" alt="Screenshot 2020-02-02 at 08 36 20" src="https://user-images.githubusercontent.com/630000/73605423-4bf94c80-459e-11ea-917f-e74444dbf743.png">

<img width="485" alt="Screenshot 2020-02-02 at 08 36 59" src="https://user-images.githubusercontent.com/630000/73605424-5582b480-459e-11ea-9050-8311b8a00659.png">

<img width="319" alt="Screenshot 2020-02-02 at 08 38 12" src="https://user-images.githubusercontent.com/630000/73605427-5f0c1c80-459e-11ea-91c8-7e1616b14c4b.png">

Please let me know if more details are needed.

Thanks a lot in advance!

**Comment by SwoopX** [comment]
I wonder what your request is.

You say, it has been paired successfully and is correctly detecting gas. This leads to the conclusion that it is fully functional. What else should be done?

**Comment by stickpin** [comment]
@SwoopX is not available on the API level. 
/sensors are not reflecting it.

**Comment by SwoopX** [comment]
Interesting, because the sensor IS already supported.

**Comment by andriej** [comment]
It is not, same on mine - can be seen on VNC and works as a repeater, can't use it any further on (Phoscon, HomeAssistant).

**Comment by stickpin** [comment]
@SwoopX anything I can do on my side that will help to understand why deCONZ not exposing it through API?

**Comment by andriej** [comment]
Same as in #1973

**Comment by SwoopX** [comment]
@andriej 

> It is not, same on mine

It is. I don't argue on that.

@stickpin how have you paired the sensor, via Phoscon?

**Comment by stickpin** [comment]
@SwoopX yes, I’ve used Phoscon.

**Comment by SwoopX** [comment]
How exactly have you done it, via sensor search? if yes, did you get a green notification of success?

From my experience, pairing does not necessarily for out, even for supported devices, on the very first time. Trying to reset and re-pair the device mostly leads to success.

**Comment by andriej** [comment]
I've tried to pair it through Phoscon like dozen times (seeing other Heisman devices supported) and none of it succeded.
I can only see it in VNC

**Comment by stickpin** [comment]
I see that my manufacturer code detected as: 0xbbaa which i guess is leading to the issue. I will try to re-pair once again when I will get home. Will let you know later today if it’s succeeded.

**Comment by SwoopX** [comment]
What makes you think it is related to the manufacturer code being 0xbbaa?

**Comment by stickpin** [comment]
@SwoopX if my understanding of the code is  correct. In case for deCONZ to detect the device in a proper way, deCONZ should know from which manufacturer it’s coming from, in my case it should be 0x120b, this is a Heiman manufacturer code. After that it goes to device type. 0xbbaa it seems like Osram Plug manufacturer or something like this. So as far a i see, there is two ways to solve it: 1. Gas sensor should be identified with proper manufacturer code. 2. To make deCONZ to recognize 0xbbaa with type Gas Sensor.

Please correct me if i’m missing something...

**Comment by SwoopX** [comment]
I'm afraid your understanding is based on wrong assumptions. I'll explain that later.

Quick shot: It might be related to the sensor being a full functional device. Seen that previously with another device...

**Comment by stickpin** [comment]
@SwoopX You were right, re-pairing solved the issue.
Now devices detected as a smoke sensor and triggered correctly through Homebrdige-Hue.

Thanks a lot for your help!

**Comment by andriej** [comment]
@stickpin what was the way you did the pairing? step by step as I've tried different approach and still end up with undetected sensor...

**Comment by stickpin** [comment]
@andriej I did it few steps:

**Unpair:**
1. Un-plugged it from the power socket completely.
2. Plug it back and wait for approximately 3 minutes so the green light stay still.
3. Use a small hole on a side to unpair the device. Press and hold the button inside the hole for approximately 5 seconds.
4. Connect to deCONZ GUI via VNC and delete your Gas sensor.
If device appears again, delete it again. 

**Pair:**
1. Press and hold the button inside the hole for approximately 2 seconds. The led on a device will blick for 2-3 seconds.
2. Go to Phoscon and do a new sensor search.
The next steps were a bit strange... 
The device should re-appear in deCONZ GUI. Go to the device and read basic information from it.
Right after that Phoscon will say that the device is ready.

Check if you can see it in sensors.
For me it's represented in the following way:

```
    "38": {
        "config": {
            "on": true,
            "pending": [],
            "reachable": true
        },
        "ep": 1,
        "etag": "183093b394920a24d0f89e88a07b67e9",
        "manufacturername": "Heiman",
        "modelid": "GAS_V15",
        "name": "GAS_V15",
        "state": {
            "fire": false,
            "lastupdated": "none",
            "lowbattery": false,
            "tampered": false
        },
        "swversion": "20150330",
        "type": "ZHAFire",
        "uniqueid": "00:40:22:e9:b3:24:45:15-01-0500"
    }
```

I hope it helps...

**Comment by andriej** [comment]
@stickpin - the "read basic information" in VNC was the key. 
It did pair fully, even tho not visible in Phoscon.

Thanks!

(It should be in manual somewhere I guess, or at least maybe someone will google it)

**Comment by SwoopX** [comment]
@stickpin Great work, also regarding your write-up. The short explanation I owe you from the previous post in short: Although Heiman seems to be an OWM doesn't necessarily mean they use their own hardware for devices. We've seen that quite a number of times. The device you have has an Osram manufacturer code and a jennix (not heiman) MAC address. Code-wise, this has been taken into account.

@andriej Glad it worked out for you as well. Unfortunately, you will no be able to see it in Phoscon unless DE implements it. Phoscon is different software and not open source.

**Comment by michis0806** [comment]
Any chance to get this working on a headless installation?

**Comment by SwoopX** [comment]
Check out the wiki on how to access headless setups

**Comment by ruabo** [comment]
Sorry, total noob here, I'm thinking about buying that sensor; is it possibile to remotely mute the siren if on ? Or can I turn the siren on ? May I have a code snipplet ? Thanks

**Comment by Mimiix** [comment]
@Gordan74 https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Access-deCONZ-GUI-in-headless-setups

**Comment by Gordan74** [comment]
Hello,
I am able to get this sensor in Deconz VNC see attachment #1.
I even gave name "GAS" but it was not visible as entity in Home assistant.
Dou you have and idea how to add it as a device/entity?
Kind regards,
Gordan

**Comment by Mimiix** [comment]
I don't see any attachments.

**Comment by Gordan74** [comment]
I guess that is because we are messaging through github notifications. Can
you send me your mail and I wil resend my screenshot with data...
Kind regards,
Gordan

**Comment by Mimiix** [comment]
@Gordan74 You can post directly here: 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2403

**Comment by Gordan74** [comment]
OK, Here is current situation.
My Conbee II is "Configuration tool 1" and there is "unnamed" device which is Gas detector appearing in VNC.
![Config toolt Conbee II and Gas detector](https://user-images.githubusercontent.com/71788227/99358269-93db2d00-28ad-11eb-82d5-5a2770259cca.png)

And here are details of node info for this device when I click on it.
![Heiman GAS detector in VNC](https://user-images.githubusercontent.com/71788227/99358308-9e95c200-28ad-11eb-831f-e80039c19d07.png)

How do I get to use it within HA? I cant find it under devices or entities.
I one of posts I saw someone finding it under binary sesors with name set to IEEE code.
I don't see this either.
Thanks for help,
Goedan

**Comment by Mimiix** [comment]
The name suggests it's not supported yet . Can you click the right DOT and click "basic" Then click the "read"button?
 For more info https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by Gordan74** [comment]
Yes, here it is...

![rigt click on dot for GAS](https://user-images.githubusercontent.com/71788227/99359116-d5200c80-28ae-11eb-9f52-33141fda77c0.png)

Cheers,
Gordan

**Comment by Gordan74** [comment]
wait wait..

**Comment by Gordan74** [comment]
Here it is...

![info for GASđ](https://user-images.githubusercontent.com/71788227/99359336-3811a380-28af-11eb-8410-5d8ccbf6916a.png)

**Comment by Mimiix** [comment]
@SwoopX Why isn't the above working?

**Comment by Gordan74** [comment]
Is there any log file that I can get for you to troubleshoot?

**Comment by Mimiix** [comment]
Nope, because as far as i can see it should work. So i have to wait for Swoop here

**Comment by Gordan74** [comment]
Coll, Thanks guys!

**Comment by SwoopX** [comment]
The device is supported but apparently, the sensor(s) has not been created. Try entering sensor search in Phoscon again and read the basic cluter.

**Comment by Gordan74** [comment]
Hi,
I have tried it many times. I followed suggested route (unpair  and pair). When paired  delete within VNC and pair again. But to no avail.
When I click on add sensor (choose Other) it is searching and 3 minutes pass and i do not get message sensor
![searching](https://user-images.githubusercontent.com/71788227/99394480-3c55b500-28df-11eb-9b1f-02fca6ef0b32.png)
 ready (green). It just searches until time is over. then I can see it in VNC as shown above.

**Comment by SwoopX** [comment]
Have you read the basic cluster attributes during search? Another option is to quickly "tickle" the device by briefly pressing the button used for device reset.

**Comment by Gordan74** [comment]
sorry for stupid question, how can I read cluster during search. I should initiate Phoscon search and then on other browser tab look in VNC?

**Comment by SwoopX** [comment]
Yes, like you already did before.

**Comment by Gordan74** [comment]
Now it was discovered and got name Gas Sensor.

![found](https://user-images.githubusercontent.com/71788227/99397889-f0f1d580-28e3-11eb-961a-76ec876c72ca.png)

![gas found](https://user-images.githubusercontent.com/71788227/99397921-f94a1080-28e3-11eb-8838-dce66d78b1eb.png)

**Comment by Gordan74** [comment]
what is next step?

**Comment by Gordan74** [comment]
Found it!

![gas_fire](https://user-images.githubusercontent.com/71788227/99398902-3cf14a00-28e5-11eb-942c-2de0fef61ef7.png)

**Comment by Gordan74** [comment]
Thank you @SwoopX  and @Mimiix !
Faaboulous!
