### ISSUE TITLE
Add Support for iHorn Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by Slothinger** [dresden-elektronik/deconz-rest-plugin#2406]
Hi,

I'm having trouble adding this [iHorn (Huawei) Temperature and Humidity Sensor](https://de.aliexpress.com/item/4000192768667.html?spm=a2g0s.9042311.0.0.397e4c4dzq1n8G) as a Sensor in the Phoscon App.
When i put the temp sensor into paring mode the deconz application detects this device:
![vncviewer_2020-02-02_16-13-14](https://user-images.githubusercontent.com/47176133/73610396-fa20e880-45d6-11ea-96dd-85d1a2e041e7.png)

The webinterface doesnt detect it and tells me "Failed to connect".
Is there something i can try or do i have to wait till this device gets eventually supported?

cheers

**Comment by SwoopX** [comment]
Have you tried pairing more than once? It happens that those need a couple of attempts. Also, make sure you're close enough to a zigbee router device.

**Comment by Slothinger** [comment]
yeah many times and with different devices running the software. conbee2 with my windows notebook, raspberry with raspian and with the image from the website.
zigbee router device = conbee2? (tried to switch to router mode)

**Comment by SwoopX** [comment]
Ok, then let's check the details. Can you please provide the screenshots required as described in the wiki for requesting device support? Also, please make sure to read the attributes before taking them.

**Comment by Slothinger** [comment]
![vncviewer_2020-02-04_22-04-05](https://user-images.githubusercontent.com/47176133/73786834-5e3fda00-479a-11ea-967b-97c069523d10.png)

Measured Value of the humidity looks correct in the attributes table.
but its still not possible to add it as a sensor in the phoscon webinterface (verndor = other).
thx for your help!

**Comment by SwoopX** [comment]
Basic cluster is more important.

**Comment by Slothinger** [comment]
![image](https://user-images.githubusercontent.com/47176133/73789892-e379bd80-479f-11ea-9ce9-626d6551288c.png)

ok should be this

**Comment by SwoopX** [comment]
Sorry, but you forgot to read the attribute. Thanks.

**Comment by Slothinger** [comment]
tried it but it doesn't work in the basic view.
is there another way to provide you this data?

**Comment by SwoopX** [comment]
That's a bit strange. However, having a closer look at your initial screenshot, it seems that you run an older version of deconz. I'd recommend an update and giving it another try.

**Comment by Slothinger** [comment]
![deCONZ_2020-02-05_08-31-17](https://user-images.githubusercontent.com/47176133/73820391-f0270180-47f1-11ea-87fa-653282fd37bd.png)
![opera_2020-02-05_08-28-38](https://user-images.githubusercontent.com/47176133/73820393-f0bf9800-47f1-11ea-9993-9c022fca9e66.png)

**Comment by SwoopX** [comment]
Just realized that I misread the vendor (thought it was Xiaomi, not Huawei). Those devices will not bee seen in Phoscon, as it is a different software and closed source on top of that.

Does the sensor work anyway with whatever middleware you might use? Otherwise, you must make a device support request out of it.

**Comment by Slothinger** [comment]
I'll try if i can use it directly in home assistant but it would be nice if the device gets supported.
Should i recreate this issue as device support request?

**Comment by SwoopX** [comment]
Check out HA first. Otherwise, ti would be sufficient to just rename the issue. I guess all relevant screenshots are already there.

**Comment by Slothinger** [comment]
@SwoopX renamed the issue because i didn't found a way to get it into ha.
Would be great if there is a way to get it supported.
Thanks for your help so far!

**Comment by SwoopX** [comment]
> So i deleted the device in deconz gui and after reconnecting and checking the correct temp and humidity values its still not possible to add the sensor in phoscon. (Sensors -> Add new sensor -> Other)

How did the pairing go while searching for new sensors, did it end with a green success message? If not, you may need to wake it up while pairing. See if there's any physical button and press it during the procedure. I hope that those sensors are not fiddled together like the Xiaomi ones because that would pretty much require traffic sniffing.

Even after a successful paring, it will not show up in Phoscon as it is a different software and we cannot do any integration there. Best way to verify if the sensors have been created successfully would be via REST API calls. Nothing automatically created in HA so far?

Btw, new version .74 is out since today so no need any more (for now) to manually compile the plugin.

**Comment by rmotapar** [comment]
> > So i deleted the device in deconz gui and after reconnecting and checking the correct temp and humidity values its still not possible to add the sensor in phoscon. (Sensors -> Add new sensor -> Other)
> 
> How did the pairing go while searching for new sensors, did it end with a green success message? If not, you may need to wake it up while pairing. See if there's any physical button and press it during the procedure. I hope that those sensors are not fiddled together like the Xiaomi ones because that would pretty much require traffic sniffing.
> 
> Even after a successful paring, it will not show up in Phoscon as it is a different software and we cannot do any integration there. Best way to verify if the sensors have been created successfully would be via REST API calls. Nothing automatically created in HA so far?
> 
> Btw, new version .74 is out since today so no need any more (for now) to manually compile the plugin.

@SwoopX Trying to see how to get the devices integrated into HA when they don't show up in the phoscon app. Is there a user guide or instructions somewhere that talks about this process? Also, I am using the deconz add-on in home assistant. How would I go about getting the latest version?

**Comment by SwoopX** [comment]
Are you using docker?

**Comment by rmotapar** [comment]
> Are you using docker?

I am using hassio which uses docker. Here's the link to the Deconz hassio add-on : https://github.com/home-assistant/hassio-addons/tree/master/deconz

**Comment by Slothinger** [comment]
> > So i deleted the device in deconz gui and after reconnecting and checking the correct temp and humidity values its still not possible to add the sensor in phoscon. (Sensors -> Add new sensor -> Other)
> 
> How did the pairing go while searching for new sensors, did it end with a green success message? If not, you may need to wake it up while pairing. See if there's any physical button and press it during the procedure. I hope that those sensors are not fiddled together like the Xiaomi ones because that would pretty much require traffic sniffing.
> 
> Even after a successful paring, it will not show up in Phoscon as it is a different software and we cannot do any integration there. Best way to verify if the sensors have been created successfully would be via REST API calls. Nothing automatically created in HA so far?
> 
> Btw, new version .74 is out since today so no need any more (for now) to manually compile the plugin.

I think it was the green dot was there, but i can confirm that tomorrow.
For the pairing i tried any combination (longpress, klicking, 1 click....) 
When i look at the cluster in deconz gui the temp and humidity updates the values faster when i press the button.

Last thing i tried today was the rest api thing:
Post { "devicetype": [Name] }
to get the key and then
GET --> http://[ip]/api/[API-Key]/sensors 
to list the sensors.
But there was only the default software day and night sensor and not my temp&humidity sensor.
I think it only lists devices from phoscon, right?

Wanted to try this Home Assistant Rest integration:
https://www.home-assistant.io/integrations/rest/

im using docker btw.

**Comment by SwoopX** [comment]
Just to be clear, I meant sensor search in Phoscon, not deconz GUI. Successful pairing should look like this:

![grafik](https://user-images.githubusercontent.com/4005212/75295355-c24e3f00-582a-11ea-944f-20ea5c87304b.png)

I don't have any experience with HA since I'm using a different middleware. However, since you haven't seen the sensors via the API call, it looks like they haven't been created. Xiaomi devices e.g. may be a little stubborn at times and require re-pairing multiple times. You may want to repeat pairing a couple of times to see if that hepls, if you haven't tried already.

**Comment by Slothinger** [comment]
Ah ok, i tought they must be connected first in the deconz gui (with the green line). 
But yeah i tried the sensor search many times in phoscon with the "other" option as in your screenshot. Also tried the deconz option etc...

What do you mean with "it looks like they haven't been created"? When deconz gui sees the zigbee device and can read the values, it should be possible to read them via api right?

**Comment by SwoopX** [comment]
> What do you mean with "it looks like they haven't been created"? When deconz gui sees the zigbee device and can read the values, it should be possible to read them via api right?

Unfortunately not. with the modifications made, there should have been at least 2 sensors created (temperature and humidity) accessible via API. As this is not the case, we need to find out why. Could have various reasons... But debugging, it's good that you can compile and test changes I provide to my repo.

**Comment by Slothinger** [comment]
hm, the first test (Rest + pull battery) didnt work.

Here ist the output:
[ihorn_join.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4256375/ihorn_join.txt)

**Comment by SwoopX** [comment]
Would prefer to stay with english, so the rest of the people may follow.

Thanks for the log. Are you 100% sure you're using deconz version .74 on your ubuntu? The log shows the previous version

> 15:42:51:221 Load config apiversion: 2.05.73 from db.

**Comment by Slothinger** [comment]
Ah sry didnt noticed that there is a update available. Now im on 2.05.74

And here is the new file:
[ihorn_join.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4258159/ihorn_join.txt)

**Comment by SwoopX** [comment]
Thanks again. Just to be sure, have you reset the sensor every time before pairing? I'd assume not because I don't see some particular data I'm after. Also, have you restarted deconz after the update?

**Comment by Slothinger** [comment]
Yep, i rebooted the whole system.
Here are two logfiles, one with a sensor delete and one with a reset of the sensor:
[ihorn_join_reset_sensor.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4260451/ihorn_join_reset_sensor.txt)
[ihorn_join_delete_sensor.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4260452/ihorn_join_delete_sensor.txt)

**Comment by SwoopX** [comment]
This still does not look right.

How did you reset the sensor? Have you hold a button somewhere on the device for like 10 seconds and what does the manual say about it. Point is, essential information regarding the pairing process is not there, but it must be...

**Comment by Slothinger** [comment]
The manual is in chinese but with google translate i found out that i have to press the button 5 sec. 
I did reset the sensor in deconz gui, klick on the sensor and select reset in the top left corner menu bar. Same with the delete function...

I can show you that over teamviewer, otherwise i think i should dump that sensor and get another one...

**Comment by SwoopX** [comment]
> I did reset the sensor in deconz gui, klick on the sensor and select reset in the top left corner menu bar.

That could eventually be the reason. I never tried this to reset a device to be honest, but please give it another go physically on the device. Usually, it gives you some kind of feedback upon a successful reset (e.g. some lights blinking or so).

After physical reset, give the sensor search in Phoscon another go with the debug output enabled. If it remains stubborn for whatever reason, we can see if we can have a session on the weekend or you send it over.

**Comment by Slothinger** [comment]
The manual says 5 sec to reset the sensor and after that it enters network distribution state.
a single press updates the temp, humidity and mby battery values.

Here is antoher log where i tried that; 
[ihorn_join4.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4272413/ihorn_join4.txt)
Would be great if we can arrange such a session. (I joined the deconz discord mby we will meet there)

**Comment by SwoopX** [comment]
Finally made it:

```
"4": {
    "config": {
      "battery": null,
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "a15664738b4a66137336aa341cc16712",
    "manufacturername": "iHorn",
    "modelid": "113D",
    "name": "113D",
    "state": {
      "lastupdated": "2020-03-21T21:37:44",
      "temperature": 2170
    },
    "type": "ZHATemperature",
    "uniqueid": "00:15:8d:00:04:c4:74:d2-01-0402"
  },
  "8": {
    "config": {
      "battery": null,
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "2e83d507f061b408d3b0254c4d391890",
    "manufacturername": "iHorn",
    "modelid": "113D",
    "name": "113D",
    "state": {
      "humidity": 2950,
      "lastupdated": "2020-03-21T21:38:04"
    },
    "type": "ZHAHumidity",
    "uniqueid": "00:15:8d:00:04:c4:74:d2-01-0405"
  },
  "9": {
    "config": {
      "battery": null,
      "on": true,
      "pending": [],
      "reachable": true
    },
    "ep": 1,
    "etag": "b657f3e9cb591ccdc99a1c780b2b68d5",
    "manufacturername": "iHorn",
    "modelid": "113D",
    "name": "113D",
    "state": {
      "alarm": false,
      "lastupdated": "none",
      "lowbattery": false,
      "tampered": false
    },
    "type": "ZHAAlarm",
    "uniqueid": "00:15:8d:00:04:c4:74:d2-01-0500"
  }
}
```

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
