### ISSUE TITLE
deCONZ Support for Zigbee Thermostatic Valves (TRVs)

### ISSUE THREAD

**Issue by DrJohnT** [dresden-elektronik/deconz-rest-plugin#2418]
Any chance Conbee II deCONZ could support Zigbee Thermostatic Valves (TRVs) such as the 
Salus TRV10RFM or Drayton Wiser Smart Radiator Thermostat ??

**Comment by SwoopX** [comment]
Generally, this would be doable. However, you or someone else must have the device, provide necessary screenshots and support in testing. Eventually, this could be rather technical depending on the device.

**Comment by DrJohnT** [comment]
Actually I found an integration for the Wiser heating controller and TRVs from Home Assistant, so I will use that proven route.  Thanks for the offer
