### ISSUE TITLE
Centralite 3321-S Open/Close Sensor & Centralite 3325S-S Motion Sensor

### ISSUE THREAD

**Issue by bal0o** [dresden-elektronik/deconz-rest-plugin#2421]
Trying to move away from SmartThings and get everything on deconz - I have a couple of sensors that are not working. They are detected in the DeConz app, but not showing in the Phoscon web app. Strangely they are picked up in HA, and report basic status (on / off) OK. 

The first is a door open/close sensor - The sensor is this one - it appears as a CentraLite 3321-S, but is smart things branded that came with the hub;

![image](https://user-images.githubusercontent.com/8915325/73828700-a215fc00-47f9-11ea-971e-c5c3a8e70931.png)

Details below - hopefully this is what you need! If you need any more just let me know

![image](https://user-images.githubusercontent.com/8915325/73828243-cd4c1b80-47f8-11ea-88a1-93d4d110ed9d.png)

![image](https://user-images.githubusercontent.com/8915325/73828214-c2918680-47f8-11ea-9795-c09eac98ac91.png)

Second is a Motion sensor from smart things doing the same - appears as a CentraLite 3325-S;

![image](https://user-images.githubusercontent.com/8915325/73828398-14d2a780-47f9-11ea-9e6f-56766fa05732.png)

![image](https://user-images.githubusercontent.com/8915325/73828617-814da680-47f9-11ea-866a-4d4ee11cda2c.png)

![image](https://user-images.githubusercontent.com/8915325/73828629-890d4b00-47f9-11ea-9f4d-42c5392e446b.png)

**Comment by SwoopX** [comment]
The devices seem to be supported looking at the code. The reason why you don't see them in Phoscon is because it is a different software and closed source on top of that.

**Comment by jjanderson** [comment]
These devices do not show up in the UI only via VNC. Additionally, when trying to delete them (i sold mine) they will simply not get deleted.... Please advise?

Thanks

**Comment by SwoopX** [comment]
What exactly do you mean with UI?

"Orphan devices" are unfortunately quite common as there's currently no way to permanently delete them as far as I know. The only way is by hacking deconz' database and for that, you should know what you're doing.

**Comment by jjanderson** [comment]
User interface being webui vs vnc where you can view the network.

When I delete them from the vnc application, i would expect them to be deleted and therefore the application should delete them from the db. If not then I would argue it should.

Otherwise, do tou know what db it uses? Maybe I can fiddle around with one if the backup files?

It is really annoying as I want rules in homeassistant based around “unavailable devices” and any orphan sensors will get pulled through...

**Comment by SwoopX** [comment]
> User interface being webui vs vnc where you can view the network.

So I conclude you mean Phoscon. Devices need to be integrated seperately and there's unfortunately nothing we can do here.

> When I delete them from the vnc application, i would expect them to be deleted and therefore the application should delete them from the db. If not then I would argue it should.
> 
> Otherwise, do tou know what db it uses? Maybe I can fiddle around with one if the backup files?

Agreed, but that's the current situation. DB is sqlite, located in the home directory of the user running deconz (e.g. /root/.local/share/dresden-elektronik/deCONZ/zll.db). You may want to make a backup first to be on the safe side and be sure to have deconz shut down. The following tables should require amendments, if I recall correctly: devices, device_descriptors, device_gui, sensors, nodes. Good luck!

**Comment by jjanderson** [comment]
Not being able to delete sensors that are intended to be connected to hardware with the software provided is a pretty fundamental shortcoming in my humble opinion. It’s like selling a door and then saying, yea you can only use it to go in, but once you are in you cant go out... sorry, that is the nature of the doors we sell....

**Comment by Mimiix** [comment]
It seems this issue is solved. If it is not, please re-open!
