### ISSUE TITLE
Stale devices in deCONZ

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#243]
I have been experimenting regulary with devices in deCONZ for the REST API. But now I have a few devices in deCONZ I think two IKEA's which are explainable as I removed them long ago and a Philips device for which I do not know where it came from (neighbours?) 

Each time I delete them with the delete key, but each time they are 'discovered' again, and even exist for some time with green lines - red box (but no cluster ifo). How do I get rid of these as they are really powered off and should not be known anymore by deCONZ?

Wim
![2017-10-26 16_07_59-raspbee raspberrypi - vnc viewer](https://user-images.githubusercontent.com/30700296/32057572-e6aab666-ba67-11e7-8d23-8fc317c73b79.png)

**Comment by ebaauw** [comment]
Looking at the mac address, the third device is by dresden elektronik, not by Philips.

If the devices are (were) sensors, you might try deleting the corresponding resources using the REST API.

**Comment by wvuyk** [comment]
Ok the third device might have been the ConBee then in router mode maybe? 
The IKEA devices are no sensors, both are lights - one GU10 and an E27. I tried to reattach these 2 weeks ago, without luck, could not connect them and could not reset them. 

Wim

**Comment by ebaauw** [comment]
Odd.  If they're stale neighbour entries, power cycling all your routers (lights) and the RaspBee/Conbee should get rid of them.

**Comment by wvuyk** [comment]
Will try... does take some crawling here LOL

**Comment by wvuyk** [comment]
Had to hunt for the last bulb, all reset and now it seems to be solved. Will test leter again by bringing back on tof the bulb and removing again. A delete through the REST API of lights doesn't work?

**Comment by wvuyk** [comment]
Not funny, with a restart of the deCONZ, all lights show not connected anymore....

**Comment by wvuyk** [comment]
Raised nwk id and rejoined network... works again!
