### ISSUE TITLE
deconZ can't reset password.. pls help m8

### ISSUE THREAD

**Issue by stewie777** [dresden-elektronik/deconz-rest-plugin#2430]
hello everyone, as the title says I write because I can't reset the password of deconZ
I tried to uninstall and install the addon, I tried to restore hassio from backup to before the problem arose, but without solving the problem.  when I reset password it's impossible for me to click on "set new password".  is there a way to reset the password from the terminal?
The default password will be "delight" right? Well.. it doesn't work
thank you all in advance for your support

**Comment by stewie777** [comment]
![20200205_194031](https://user-images.githubusercontent.com/1301893/73918312-b1607c80-48c1-11ea-936e-678395a45149.jpg)
I can't click on it

**Comment by acid115** [comment]
But this is a hassio problem! 
Did you try to login with default user/pw?
delight/delight

**Comment by stewie777** [comment]
> Ma questo è un problema di hassio!
> Hai provato ad accedere con l'utente / pw predefinito?
> gioia / piacere

![Screenshot_20200206-094910_Chrome Beta](https://user-images.githubusercontent.com/1301893/73920618-0ef6c800-48c6-11ea-8f37-d4b071959250.jpg)

as you can see if I try to access the addon ui web I see this page where I can only put the password, where can I try to log in with username and password?  maybe I miss some steps

**Comment by cobch** [comment]
I have the same problem. Updated HassOs yesterday. Impossible to reset nor to have a new log in session to enter default password? How can I reset the password/username of the Deconz webui when the reset function is not working?

**Comment by stewie777** [comment]
is it possible that the only solution is to do a new hassio installation?  it is impossible that deconZ cannot be accessed from the terminal to change and reset the password

**Comment by cobch** [comment]
I have already installed Hassio from an earlier backup but same problem.

**Comment by Highjack77** [comment]
I have the exactely same problem since today. any solution yet ?

**Comment by cobch** [comment]
Today everything is working again... I have not done anything. Really strange. It may may some long delay between the password reset in Deconz?

**Comment by cobch** [comment]
Update to the supervisor  199. See #1049 for more information.

**Comment by busshi** [comment]
Hello I just bought a Conbee II but I succeed only once to log in. Impossible to change the password neither to connect with the one I give on the first install...
How did you make it work ? I am using it on a raspberry with Domoticz running.

**Comment by Mimiix** [comment]
This issue seems to be resolved. 

@busshi , if you still have a issue, please create a new one.
