### ISSUE TITLE
Question about API ( want to make disco)

### ISSUE THREAD

**Issue by 00lex** [dresden-elektronik/deconz-rest-plugin#2431]
how can I put following commands into one?  

```
# start
curl -X PUT -d '{"effect": "colorloop" }' http://127.0.0.1:8009/api/xx/lights/2/state
# set speed
curl -X PUT -d '{"colorloopspeed": 150 }' http://127.0.0.1:8009/api/xx/lights/2/state
# set sat
curl -X PUT -d '{"sat": 250 }' http://127.0.0.1:8009/api/xx/lights/2/state
```

and is it possible to trigger multiple lights with one command? 

thank you

**Comment by ebaauw** [comment]
Just combine the attributes in a single object: `{"effect": "colorloop", "colorloopspeed": 150}`.

Use a `/groups` resource to send a command to all lights in that group.

**Comment by 00lex** [comment]
thank you. that's what im done.
I was focused on the command line and colorloopspeed in contrast to effect, sat and bri gaves no output from curl. I was a little hasty :)
