### ISSUE TITLE
Support for Xinghuoyuan relay

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#2433]
http://en.xhycloud.com/products/relay-module

**Comment by wvuyk** [comment]
Bitdefender gives an alert on this link. Guess y'all need to ignorw this link

**Comment by Klagio** [comment]
This link better?
http://cnremote.com/en/products.aspx?ProductsCateID=88&CateID=88

they have so many nice zigbee products

**Comment by Mimiix** [comment]
If you still need this device implemented, please follow: 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support
