### ISSUE TITLE
Support for Xiaomi Bluetooth Temperature Smart Humidity Sensor?

### ISSUE THREAD

**Issue by 3PO** [dresden-elektronik/deconz-rest-plugin#2434]
Does deconz support Xiaomi Bluetooth Temperature Smart Humidity Sensors?

![enter image description here](http://dreipo.cc/test/Xiaomi.jpg)

**Comment by bastshoes** [comment]
It's different protocol. deCONZ supports only zigbee devices.

**Comment by Sjonnie2018** [comment]
There is a ZigBee version for this device "made" by Blitzwolf: https://www.aliexpress.com/item/4000640062775.html

**Comment by G3rry71** [comment]
> There is a ZigBee version for this device "made" by Blitzwolf: https://www.aliexpress.com/item/4000640062775.html

Is it really supported in Deconz?
I have this https://www.aliexpress.com/item/4000578239423.html and it is not fully discovered

**Comment by Sjonnie2018** [comment]
I don't know because I haven't bought it yet (but I am tempted :-) ). It would be great if you could tell me/us what is supported and what not. Preferably with some screenshots of the device in Deconz.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue.
