### ISSUE TITLE
Pairing HUE Smart Button

### ISSUE THREAD

**Issue by vantino** [dresden-elektronik/deconz-rest-plugin#2436]
Ciao

I'm struggeling to pair the phillips smart button on my current deconz version 2.05.66 running on a pi3.

Does the 2.05.66 know that new device?
The device reset works, but is not being recogniced. 

Apreciate a any help.

Thanks
Vantino

**Comment by carpii** [comment]
Duplicate of #2077

**Comment by Mimiix** [comment]
As @carpii said, its a duplicate. #close
