### ISSUE TITLE
Wrong IP address while requesting config via API

### ISSUE THREAD

**Issue by imabot2** [dresden-elektronik/deconz-rest-plugin#2438]
The IP address of my API is `192.168.1.2`. When I request configuration through the following address : `http://192.168.1.2/api/XXXXXXXXXX/config` here is what I get:
```
{
  "UTC": "2020-02-12T08:01:01",
  "apiversion": "1.16.0",
  "backup": {
    "errorcode": 0,
    "status": "idle"
  },
  "bridgeid": "XXXXXXXXXXXXXXXX",
  "datastoreversion": "60",
  "devicename": "ConBee II",
  "dhcp": true,
  "factorynew": false,
  "fwversion": "0x26490700",
  "gateway": "172.18.124.1",
  "internetservices": {
    "remoteaccess": "disconnected"
  },
  "ipaddress": "172.18.124.108",
```
I do not understand the following properties : 
```
"gateway": "172.18.124.1",
"ipaddress": "172.18.124.108",
```
Why the IP are not `192.168.1.2`?

**Comment by Mimiix** [comment]
It seems that you are running a docker version as the 172 xxx ip is a docker IP. 

Because its a old issue and there haven't been any activity on it, i assume it has been resolved. 

If you feel it's not, please re-open.
