### ISSUE TITLE
command line params and deCONZ-autostart.sh

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#244]
Related to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/238:

I saw in the different Dockerfiles that people attempt to start deCONZ with the deCONZ-autostart.sh like this:

`DECONZ_OPTS="-platform minimal --auto-connect=1 --http-port=8080" deCONZ-autostart.sh`

However, for me this does not work because the DECONZ_OPTS are ignored - even when executed without docker like this. It just uses the default values. 

![image](https://user-images.githubusercontent.com/10351272/32113474-b50ebf2e-bb40-11e7-831c-9b13ad39f782.png)

What would be the correct way to override the default settings provided in deCONZ-autostart ?

**Comment by manup** [comment]
When used in a docker container I would suggest not using the deCONZ-autostart.sh script but just plain deCONZ.

`$  deCONZ -platform minimal --auto-connect=1 --http-port=8080`

Or use the systemd script as described here:

https://github.com/dresden-elektronik/deconz-rest-plugin#headless-support

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
