### ISSUE TITLE
Support for Wireless Temperature and Humidity Detector / Sensor 

### ISSUE THREAD

**Issue by G3rry71** [dresden-elektronik/deconz-rest-plugin#2442]
I am running ConBee II, Deconz Addon in HASSIO and would like to know if this sensor is supported: https://www.aliexpress.com/item/4000578239423.html

![Schermata 2020-02-12 alle 19 49 06](https://user-images.githubusercontent.com/53312671/74366715-cd3bb500-4dd0-11ea-88e1-511d183de5c5.png)

Measured Value of Temp, battery and humidity looks correct in the attributes table.
but its still not possible to add it as a sensor in the phoscon web interface
![Schermata 2020-02-12 alle 20 13 04](https://user-images.githubusercontent.com/53312671/74368996-ed6d7300-4dd4-11ea-998a-591973d44e53.png)
![Schermata 2020-02-12 alle 20 15 39](https://user-images.githubusercontent.com/53312671/74369099-142ba980-4dd5-11ea-95e4-03b7d27a12c5.png)
![Schermata 2020-02-12 alle 20 15 46](https://user-images.githubusercontent.com/53312671/74369123-1a218a80-4dd5-11ea-942a-86233950b27c.png)
![Schermata 2020-02-12 alle 20 15 52](https://user-images.githubusercontent.com/53312671/74369151-27d71000-4dd5-11ea-880f-5277be206f8c.png)
![Schermata 2020-02-12 alle 20 18 35](https://user-images.githubusercontent.com/53312671/74369166-2e658780-4dd5-11ea-9565-259b848a2220.png)
![Schermata 2020-02-12 alle 20 16 06](https://user-images.githubusercontent.com/53312671/74369173-31f90e80-4dd5-11ea-8eb2-220b4af6ff6e.png)

Please let know how I can help!
Thanks

**Comment by SwoopX** [comment]
You must read the attributes before taking the screenshots. Additionally, please provide one of the node info panel.

**Comment by Darkwin101** [comment]
Ok I Try to help, i Have the same Sensor from Tuya
![OTAU_Cluster](https://user-images.githubusercontent.com/60988041/74377093-958a3880-4de3-11ea-804f-85602c40c9f2.png)
![Humidity](https://user-images.githubusercontent.com/60988041/74377568-73dd8100-4de4-11ea-8b94-b30a25831d79.png)
![Temperature](https://user-images.githubusercontent.com/60988041/74377576-76d87180-4de4-11ea-9c10-9af6f47fb1fd.png)
![basic](https://user-images.githubusercontent.com/60988041/74377579-793acb80-4de4-11ea-8618-ba54907bbcb4.png)
![node](https://user-images.githubusercontent.com/60988041/74377582-7b048f00-4de4-11ea-8fd1-fff9933636e5.png)

**Comment by G3rry71** [comment]
Here they are, thanks
![Schermata 2020-02-13 alle 12 51 56](https://user-images.githubusercontent.com/53312671/74433028-e770a400-4e5f-11ea-83bb-9ae195693208.png)
![Schermata 2020-02-13 alle 12 52 16](https://user-images.githubusercontent.com/53312671/74433033-ec355800-4e5f-11ea-9fcd-b19418dd6883.png)
![Schermata 2020-02-13 alle 12 52 33](https://user-images.githubusercontent.com/53312671/74433046-f0617580-4e5f-11ea-9472-8719df37e3a6.png)

**Comment by Sjonnie2018** [comment]
> Ok I Try to help, i Have the same Sensor from Tuya
 So you are saying the device is found and supported in Deconz REST api? I would like to know because I am thinking of buying the Blitzwolf version for my setup.

TIA

**Comment by Darkwin101** [comment]
No it is not supported i want to help with the screenshots

**Comment by Sjonnie2018** [comment]
Aha! Clear! I will postpone buying the sensor then😉

**Comment by SwoopX** [comment]
Guys, can you please provide another screenshot of the power configuration cluster but with the attributes read? Thanks!

**Comment by Darkwin101** [comment]
![power](https://user-images.githubusercontent.com/60988041/74675213-59742080-51b3-11ea-9a69-3340f80d812e.png)

**Comment by G3rry71** [comment]
Here is mine:
![Schermata 2020-02-17 alle 20 21 53](https://user-images.githubusercontent.com/53312671/74681269-3c474e00-51c3-11ea-9f37-3a8e3cb30f8a.png)

**Comment by SwoopX** [comment]
@Darkwin101 Thanks! I'll provide a pull request soon.

**Comment by WhistleMaster** [comment]
@G3rry71 How is this device running so far ? Any issue ? Could you share your opinion on that sensor ? Thanks !

**Comment by mmychu** [comment]
I have the BlitzWolf version and is not discovered by Conbee2/deconz at this moment

**Comment by Darkwin101** [comment]
I have no Problem with the Tuya and the Blitzwolf Version in Deconz. It is not showing in Phoscon App but there it is  not supportet at this Time

**Comment by mmychu** [comment]
Any chance to see this sensor in Home Assistant?

**Comment by Darkwin101** [comment]
i use openhab and there is no Problem with this Sensor since Version XXX...74

**Comment by SwoopX** [comment]
@mmychu Maybe you should try to re-pair the device. It should be visible in HA like any other sensor, if pairing has been successful.

**Comment by mmychu** [comment]
@SwoopX can you help me with pairing? I try keeping the top button for 5-10 seconds and don't see any new Node in VNC network. I always used PhosconApp discovery, first time doing by VNC.
Should I open network for new devices? How to do it in deconz GUI via VNC?

**Comment by SwoopX** [comment]
Always pair via Phoscon. Start sensor search and reset the device. Success should be indicated by a green message.

**Comment by mmychu** [comment]
@SwoopX works like a charm in Home Assistant. Thank you very much!

**Comment by G3rry71** [comment]
> @G3rry71 How is this device running so far ? Any issue ? Could you share your opinion on that sensor ? Thanks !

Hi, it working correctly now! I can see it in HA and in VNC network. Still not showing up as a sensor in deCONZ Phoscon web interface.

Thanks a lot!

**Comment by SwoopX** [comment]
Nice. 👍

Can we close the issue then?

**Comment by mmychu** [comment]
Yes. Thank you

**Comment by G3rry71** [comment]
Thanks for supporting

**Comment by SargonofAssyria** [comment]
I am using zigbee2mqtt and there is a bad update frequency of Temperature and Humidity.
Temperature is only updated if change is 0.7 degrees ore more and Humidity only if change is 2% or more.
I wonder if that is the same here and if not how it is solved.

**Comment by G3rry71** [comment]
> @G3rry71 How is this device running so far ? Any issue ? Could you share your opinion on that sensor ? Thanks !

Hi @WhistleMaster , working very well, not an issue after months. I have temp, humidity and battery level in HomeAssistat

**Comment by easybeat** [comment]
I've got them but they seem to have different Firmware compared to the Blitzwolf device. The temperature change is only reported at a change > 0.7 degrees. The Blitzwolf reports temperature changes of 0.1 degrees.

Is there somewhere this can be set/configured?

Thanks for help.

Beat

**Comment by answer35** [comment]
> > @G3rry71 How is this device running so far ? Any issue ? Could you share your opinion on that sensor ? Thanks !
> 
> Hi, it working correctly now! I can see it in HA and in VNC network. Still not showing up as a sensor in deCONZ Phoscon web interface.
> 
> Thanks a lot!

Hi I have the same situation with one sensor. Any trick to fix it ? Because I have a second one that I bought first which was automatically detected in Phoscon, DeconZ, and HA but that new one cannot come visible on Phoscon.

**Comment by SAOPP** [comment]
hey guys, I added it to my conbee 2, and I don't see it in phoscon, but this sensor is presens in gui and in ha, it's correct behaviour? 'coz I saw guys are posted  screenshots from phoscon with this sensor... any comments?

**Comment by answer35** [comment]
> hey guys, I added it to my conbee 2, and I don't see it in phoscon, but this sensor is presens in gui and in ha, it's correct behaviour? 'coz I saw guys are posted screenshots from phoscon with this sensor... any comments?

Hi, I don't know exactly what can be wrong with this type of sensor but it is random issue, I have two sensors like that. First one showed up on Phoscon, second doesn't. But it is in HA & deCONZ GUI.

**Comment by G3rry71** [comment]
Hello,
mine still working both in. Phoscon and HA.Only minor issue is it update
not so frequently.

Here it is in Phoscon under sensor:
VendorHeiman
ProductMultipurpose Sensor
Versionunknown
Battery100 %
Temperature20 °C
Humidity46 %
Refreshed02/28/2021 11:44:08 AM

HA:

Filtra entità

Filtra stati

Filtra attributi
 sensor.sensors_anticamera
<https://casagerry.no-ip.org:8124/developer-tools/state#> 20.6 on: true
unit_of_measurement: °C friendly_name: Temperatura Anticamera icon:
mdi:thermometer device_class: temperature
 sensor.sensors_anticamera_2
<https://casagerry.no-ip.org:8124/developer-tools/state#> 46.4 on: true
unit_of_measurement: % friendly_name: Umidità Anticamera device_class:
humidity


deConz:


[image: Schermata 2021-02-28 alle 11.51.01.png]

Hope this help.


Il giorno dom 28 feb 2021 alle ore 11:32 answer35 <notifications@github.com>
ha scritto:

**Comment by Thanh-Binh** [comment]
I have the same sensor in ZigBee  but produced by Moes, but can not see it in HA.
Could you please help me by HA integration?
Thanks

**Comment by Mimiix** [comment]
> I have the same sensor in ZigBee but produced by Moes, but can not see it in HA. Could you please help me by HA integration? Thanks

Please open an new request with requested information in the template.
