### ISSUE TITLE
Sensors freeze / stuck / not refresh

### ISSUE THREAD

**Issue by IsraelShok** [dresden-elektronik/deconz-rest-plugin#2443]
Hi, I just connected my new Conbee before 3 days and paired a few Xiaomi sensors.
everything works great for a day.
After a day, all the sensors not refreshed and freeze in the same last status.
I connected to extension cable, and move it away from the router and raspberry, but with no success.

distance Conbee stick from sensors: 5-7 meters
stick channel: 15, tried to change the channel with no success.
version 2.05.72
firmware 264A0700
working with Hassio as deCONZ add-on

Please help me with this issue
Thanks

**Comment by CHornhues** [comment]
Hello, I have the same Problem. Very annoying. Xiami Sensors. They show green and were seen in the Conbee App. But they don't update values... Batteries all new.. as devices are new.


![image](https://user-images.githubusercontent.com/60758215/74565621-e891f600-4f71-11ea-86bc-6d9ae45be3df.png)

![image](https://user-images.githubusercontent.com/60758215/74565723-268f1a00-4f72-11ea-8611-e5e9c9baafd9.png)


What can we do? I think it is an firmware issue..

**Comment by TuomasPakkanen** [comment]
Having the same kind of issue with a hue motion sensor.

**Comment by xxLeoxx93** [comment]
Same here! But for me only the Sqare "Aqara" version seems to have this issue. The round version works well here so far.
Do you have a Xiaomi Gateway running at the same time?

**Comment by CHornhues** [comment]
Nope. Aquara Gateway didn't work due to restriction of Servers. I removed all Aqara and zigbee devices. Replaced all of them with z-wave devices. No problems anymore.

**Comment by xxLeoxx93** [comment]
Alright, I got Ikea Tradfri bulbs and they work great as a repeater. It just seems like the stick doesn't have a good long& stable range.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
