### ISSUE TITLE
How to change device id in the Web UI or via Rest API

### ISSUE THREAD

**Issue by Liese2007** [dresden-elektronik/deconz-rest-plugin#2447]
Hi,
in Home Assistant I get following error after reconnecting a sensor (Aqara Window Open/Close):
`Platform deconz does not generate unique IDs`

How can I access the IDs ? Via a Database file or via the Rest API?

Best regards,
Jörg

**Comment by Smanar** [comment]
Hello,
Can you take a look on the JSON of the device ? I think you can find it in HASS log.

I can't understand if the device miss an uniqueID or if you have 2 time the same.

**Comment by Liese2007** [comment]
Sorry @Smanar , I am a Noob.... Just started in December. May you explain where a JSON output of the device can be found?

The error log shows the following kind of fault several times:
`
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: binary_sensor.openclose_21. Platform deconz does not generate unique IDs
2020-02-14 09:49:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: binary_sensor.water_5. Platform deconz does not generate unique IDs
2020-02-14 09:49:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
`
Does the Log extraction help?

Regards,
Jörg

**Comment by Smanar** [comment]
Not realy for me ^^.
You don't have specific log for the deconz plugin ?
Or tale a look here https://dresden-elektronik.github.io/deconz-rest-doc/
You can have a JSON list with all your sensors with something like that
`http://ip_deconz:por_tdeconz/api/api_key/sensors`

And you can see the guilty.

Or you can try at random with removing sensor from Phosocn.

**Comment by Liese2007** [comment]
I tried to get access to RestAPI before, but the GATEWAY UNLOCK button is not available in my Phoscon Frontend.

Any hint :-)
Or need to open othe rissue maybe?

Regards,
Jörg
![Screenshot-RestAPI](https://user-images.githubusercontent.com/55997073/74604809-b4c5e600-50c1-11ea-8fa4-2516e6a4f1ba.jpg)
![Screenshot-Phoscon-Gateway-1](https://user-images.githubusercontent.com/55997073/74604849-20a84e80-50c2-11ea-88c8-e4a38f561cbb.jpg)
![Screenshot-Phoscon-Gateway-2](https://user-images.githubusercontent.com/55997073/74604851-256d0280-50c2-11ea-8c9a-082c5e140023.jpg)

**Comment by Smanar** [comment]
Oups sorry I have forget you.
I have see someone else have answer to you https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2469

And yep, sorry the site is not in date.

But it s not the easier way, I think you can find an API key somewhere in the plugin config in HA.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!

**Comment by Davst** [comment]
I'm having this same issue and looking for a sollution.

**Comment by Smanar** [comment]
What is your issue ?
