### ISSUE TITLE
Add support of GS SKHMP30-I1 smart plug (manufactured by Heiman)

### ISSUE THREAD

**Issue by andreypolyak** [dresden-elektronik/deconz-rest-plugin#2453]
Hi team,
Recently I bought [GS SKHMP30-I1](https://www.gs.ru/catalog/umnyy-dom/umnaya-rozetka-gs-skhmp30-i1/) smart plug which is only sold in Russia by one of the satellite TV operators. This smart plug is in fact produced by Heiman and is a copy of [Heiman's smart plug](http://www.heimantech.com/product/139.html). However, it has a different manufacturer and model id in the Basic cluster.
I was able to add this smart plug but it only supports On/Off commands, no power metering is available (I'm using Home Assistant).

![2020-02-15 18_19_16-Window](https://user-images.githubusercontent.com/7446762/74591179-bd1d1300-5026-11ea-9f69-45c2c9ddc8af.png)
![2020-02-15 18_19_29-Window](https://user-images.githubusercontent.com/7446762/74591181-bdb5a980-5026-11ea-906a-537a251dded5.png)
![2020-02-15 18_19_41-Window](https://user-images.githubusercontent.com/7446762/74591182-bdb5a980-5026-11ea-9b4e-3c7ceb7120e7.png)
![2020-02-15 18_20_13-Window](https://user-images.githubusercontent.com/7446762/74591183-be4e4000-5026-11ea-9c0b-5b76e03419bf.png)
![2020-02-15 18_20_26-Window](https://user-images.githubusercontent.com/7446762/74591184-bee6d680-5026-11ea-8c06-3310a99264ff.png)
![2020-02-15 18_54_14-Window](https://user-images.githubusercontent.com/7446762/74591175-bb534f80-5026-11ea-9bb2-0ea4e829471c.png)
![2020-02-15 18_54_29-Window](https://user-images.githubusercontent.com/7446762/74591176-bc847c80-5026-11ea-9867-4619750db016.png)
![2020-02-15 18_54_52-Window](https://user-images.githubusercontent.com/7446762/74591177-bc847c80-5026-11ea-90e4-eb4fdab66d67.png)
![2020-02-15 19_06_07-Window](https://user-images.githubusercontent.com/7446762/74591178-bd1d1300-5026-11ea-816a-93cd3ff42258.png)

**Comment by SwoopX** [comment]
What load was applied when you took the screenshot, 388W or 38,8W?

**Comment by andreypolyak** [comment]
Hi @SwoopX,
It was 38,8W

**Comment by andreypolyak** [comment]
Hi @SwoopX ,
I updated to 2.05.74, but still can't see power usage neither in Home Assistant nor in Phoscon. I have deleted smart plug from Phoscon and then added it again. Something wrong?

Thanks!

**Comment by SwoopX** [comment]
Hm, not really what I expected. Could you please try once again, but this time after deleting the device in Phoscon also physically reset the device? Meanwhile, I double check the code if something went wrong.

**Comment by andreypolyak** [comment]
Hi @SwoopX,
please ignore my last message. I restarted HA and deConz, deleted the device from Phoscon once again and Power and Consumption sensors appeared in Home Assistant. Thank you so much!

**Comment by SwoopX** [comment]
Could you please double check the consumption value is reasonable? Might be that I made a mistake and set the comma wrongly.

**Comment by andreypolyak** [comment]
Hi @SwoopX ,
to be honest, I don't understand how consumption value is calculated. Should it show consumption over the last hour? Or real-time consumption? For test purposes, I put an LED bulb to the smart plug. The bulb is marked as 23W and that's approximately what I get as power value (25-26W). However, consumption value is shown as 0.134-0.154 kWh. 

Thanks

**Comment by SwoopX** [comment]
It is the total power consumed since last device reset, so it should constantly grow over time. With the LED, it takes some minutes for the value to change.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
