### ISSUE TITLE
Cant get my deConz online.

### ISSUE THREAD

**Issue by najklez** [dresden-elektronik/deconz-rest-plugin#2458]
Hi
Am a total novice in this subject but have done some awsom work with Hassio and conbee2.
After I moved hassio from Rpi to Oracle VM on PC windows7 I got problems. Tried to connect to Hue Essential app on android. No success. Tried to re install deConz. That's where all problems started. DeConz cant connect. 
![20200216_192933](https://user-images.githubusercontent.com/12038810/74610336-b4920e80-50f2-11ea-8d04-5c6679f713bd.jpg)
![Screenshot_20200216-192817_Chrome](https://user-images.githubusercontent.com/12038810/74610338-b65bd200-50f2-11ea-8183-3cb96a42ba6a.jpg)
  #####![Screenshot_20200216-192733_Chrome](https://user-images.githubusercontent.com/12038810/74610339-b6f46880-50f2-11ea-9d69-073677374822.jpg)

**Comment by najklez** [comment]
Now im sure im using the rigt string, /dev/ttyACM0. it will not start if i use something else, 

![image](https://user-images.githubusercontent.com/12038810/74627241-83e1c180-5152-11ea-9263-fb14566f27f1.png)

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
