### ISSUE TITLE
Add Support for TS0201 Temperature and Humidity Sensor with Display

### ISSUE THREAD

**Issue by kroimon** [dresden-elektronik/deconz-rest-plugin#2461]
Manufacturer: TuYa? BlitzWolf? (seems to be sold under different brands)
Model Identifier: TS0201
Bought from: https://banggood.app.link/pfaR2ccl93

![2020-02-17 11-17-55 SRADO393N HomeAssistant VNC (Hass io - deCONZ) – VNC Viewer](https://user-images.githubusercontent.com/628587/74645228-cec20000-5177-11ea-82e5-a32a1bd3dac1.png)
![2020-02-17 11-18-32 SRADO393N HomeAssistant VNC (Hass io - deCONZ) – VNC Viewer](https://user-images.githubusercontent.com/628587/74645234-d2558700-5177-11ea-8be1-33e6c37db8bf.png)
![2020-02-17 11-21-30 SRADO393N HomeAssistant VNC (Hass io - deCONZ) – VNC Viewer](https://user-images.githubusercontent.com/628587/74645238-d386b400-5177-11ea-9e4c-1801fe87bbeb.png)
![2020-02-17 11-21-44 SRADO393N HomeAssistant VNC (Hass io - deCONZ) – VNC Viewer](https://user-images.githubusercontent.com/628587/74645241-d4b7e100-5177-11ea-943b-a9af603c7c76.png)
![2020-02-17 11-21-55 SRADO393N HomeAssistant VNC (Hass io - deCONZ) – VNC Viewer](https://user-images.githubusercontent.com/628587/74645247-d681a480-5177-11ea-8f4f-d678f180dc17.png)

**Comment by Darkwin101** [comment]
#2442 is the same Request

**Comment by kroimon** [comment]
Duplicate of #2442
