### ISSUE TITLE
Develco Smart Relay features

### ISSUE THREAD

**Issue by espen4001** [dresden-elektronik/deconz-rest-plugin#2464]
Hi! I have a Develco Smart Relay which, in addition to perform on/off-control of connected load, has the ability to send power measurement data, i.e. consumed power, voltage level, phase voltage etc.

How can I get these features available in my Home Assistant setup? They are available in deCONZ, but the Phoscon-app show only a single switch with on/off feature, and in Home Assistant, this switch is the only entity available.

I did try using the native ZHA integration in Home Assistant, and when the relay was connected, all features was available in Home Assistant; power measurement data, switching on/on etc.

I am pretty new to this ZigBee-stuff, so if this is something that needs modifying the API from deCONZ, or if I can do this by myself by modifying the unit in deCONZ, please help pointing me in the right direction. I can post a more "official" feature request if this is needs modification in the core of deCONZ.

Ref technical manual from manufacturer: 

[https://www.develcoproducts.com/media/1793/smrzb-332-technical-manual-smart-relay-din-16a.pdf](url)

**2.2 Key features**
The ZigBee based Smart Relay is a router in the ZigBee Pro network.
Key features are:
-  Remote on/off control
-  Power Failure alarm
-  Accurate power consumption
-  Certified ZigBee Home Automation 1.2
-  ZigBee OTA cluster for firmware upgrades
-  ETSI compliant.
-  RoHS compliant according to the EU Directive 2002/95/EC.

**Comment by SwoopX** [comment]
Hi, I can take car of this when I've some time to spare. Meanwhile, does the device create the ZHAconsumption and ZHApower sensors alright in deconz? I understand HA did create something for power measurement and would assume, the values are empty?

Btw, you won't see any more in Phoscon than the light or switch you currently see. Phoscon is a different software and closed source, so nothing we can do about it. What matters here is what the REST API offers.

**Comment by espen4001** [comment]
Thank you! I can provide screenshots from Deconz, maybe you can tell me what you need to see? As far as I can see, all the features listed in the manual are available.

**Comment by espen4001** [comment]
Regarding what you are asking for about the ZHA. Not sure if I understand what you are asking. The only thing created in HomeAssistant from Deconz, is the switch on/off. Nothing else. When using the native ZHA in HomeAssistant, there is alot more. Current consumption, consumption last period, on/off, voltage and power fault alarm.

But please feel free to explain, as I really want to learn more about how zigbee works!

**Comment by SwoopX** [comment]
It think I got everything I need for the moment regarding the screenshots. Maybe one of the node info panel, as Develco devices showed quite stubborn in some cases.

Bringing in support should be quite easy as I already implemented most of what's painful.

**Comment by espen4001** [comment]
<img width="402" alt="Skjermbilde 2020-02-18 kl  20 03 17" src="https://user-images.githubusercontent.com/38804642/74769201-41230500-528a-11ea-9a7a-a7ac91f9f740.png">

Here is a screenshot of the node-info view. I really appreciate your help on this!

**Comment by espen4001** [comment]
I will get you some screenshots tomorrow!
I see you made a commit with initial support, I can update and see if you got the units correct.

**Comment by espen4001** [comment]
Electrical measurement cluster - Relay On:
<img width="792" alt="Electrical measurement cluster - Relay on" src="https://user-images.githubusercontent.com/38804642/74948128-2375ad00-53fc-11ea-90ab-ba632cdd7e87.png">

Electrical measurement cluster - Relay off:
<img width="792" alt="Electrical measurement cluster - Relay off" src="https://user-images.githubusercontent.com/38804642/74948153-2a042480-53fc-11ea-8f7c-1f8f4d8df2a1.png">

Simple metering cluster - Relay on:
<img width="792" alt="Simple metering cluster - Relay on" src="https://user-images.githubusercontent.com/38804642/74948145-283a6100-53fc-11ea-9d64-b0daf54aa88b.png">

Simple metering cluster - Relay off:
<img width="792" alt="Simple metering cluster - Relay off" src="https://user-images.githubusercontent.com/38804642/74948147-28d2f780-53fc-11ea-8ee9-b0dfe153f633.png">

Basic cluster - Relay off:
<img width="792" alt="Basic cluster  - Relay off" src="https://user-images.githubusercontent.com/38804642/74948148-296b8e00-53fc-11ea-869f-f92833b867c1.png">

**Comment by SwoopX** [comment]
Thanks. Looks like only the voltage required an update.

**Comment by espen4001** [comment]
Finally got my docker updated to 2.05.74. But still nothing more than the «light» entity in home assistant. Shouldn’t I expect to see more entities? Or did I misunderstand it all? Am I mistaken by thinking that deConz talks directly to home assistant? That the phoscon app is only a more visual interpretation of the functionality of the Deconz?

**Comment by SwoopX** [comment]
> That the phoscon app is only a more visual interpretation of the functionality of the Deconz?

Pretty much correct.

You may need to repair the device to have the sensors available. I'd recommend to go for the sensor search then. You should see something greenish upon success.

**Comment by espen4001** [comment]
Thanks for the tip @SwoopX! A new search for lights in phoscon did the trick. Now I have two more entities in Home Assistant; Total consumption (Current summation delivered) and the current demand (Instantaneous demand). Just what I was looking for!
I also see that the device is able to measure temperature. Is it too much to ask for this value to be available also? Am I correct if this is cluster 0002, ID 0x0000?
Screenshot of the cluster info of the Device Temperature configuration:
![2D8D252B-E3B2-4E72-BE6E-5279CFE8D300](https://user-images.githubusercontent.com/38804642/75925664-5d699900-5e69-11ea-9bdf-6c7a66ac0212.jpeg)

**Comment by SwoopX** [comment]
@espen4001 Glad it worked out, great. Regarding the device temperature, this is a rather extensive change I'm afraid. As I see it, changes on the API and sensor creation routines are required for that "compareable simple request". However, I'd vouche for that.

Maybe we should put that and the alarms cluster as well for discussion.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!

**Comment by jd1900** [comment]
> Hi! I have a Develco Smart Relay which, in addition to perform on/off-control of connected load, has the ability to send power measurement data, i.e. consumed power, voltage level, phase voltage etc.

Where did you buy it?
I'm trying to buy it but I cannot find it...

**Comment by espen4001** [comment]
> > Hi! I have a Develco Smart Relay which, in addition to perform on/off-control of connected load, has the ability to send power measurement data, i.e. consumed power, voltage level, phase voltage etc.
> 
> Where did you buy it?
> I'm trying to buy it but I cannot find it...

https://www.elektroimportoren.no/develco-smartrele-16a-din/4514734/Product.html?Event=brandlist

**Comment by jh83** [comment]
> > Hi! I have a Develco Smart Relay which, in addition to perform on/off-control of connected load, has the ability to send power measurement data, i.e. consumed power, voltage level, phase voltage etc.
> 
> Where did you buy it?
> I'm trying to buy it but I cannot find it...

Bought 4 of them from here: https://en.cozify.fi/collections/devices/products/develco-smart-relay-16a-din

Delivered to Sweden in less than a week
