### ISSUE TITLE
Lupusec / PSMP5_00.00.03.11TC / no power meter in deconz iobroker showing

### ISSUE THREAD

**Issue by ricosander** [dresden-elektronik/deconz-rest-plugin#2468]
The Lupusec smart plug "LUPUSEC Funksteckdose mit Stromzähler und Repeater" is recognized as PSMP5_00.00.03.11TC. 
It is working to switch on/off, but the powermeter, included in the device is not showing up in deconz adapter in iobroker.

I dunno if it is supported at all, or just not displayed or can be added.

**Comment by SwoopX** [comment]
Can you please issue a device support request as described in the wiki?

**Comment by ricosander** [comment]
Of course. Thank you.
