### ISSUE TITLE
How to access Rest API- No 'Gateway unlock' button

### ISSUE THREAD

**Issue by Liese2007** [dresden-elektronik/deconz-rest-plugin#2469]
Hi, I try to work with REST API, but the button mentiond in documentation is missing... Imho.
Please check pictures:
![74604849-20a84e80-50c2-11ea-88c8-e4a38f561cbb](https://user-images.githubusercontent.com/55997073/74847506-81d65900-5332-11ea-9d1e-4dcf5eea8f00.jpg)
![74604851-256d0280-50c2-11ea-8c9a-082c5e140023](https://user-images.githubusercontent.com/55997073/74847508-83078600-5332-11ea-89c1-47b21c779c6b.jpg)
 Regards
Jörg

**Comment by ademobile** [comment]
I believe you want 'App verbinden'. Sorry I don't read/speak German, however that's the button I use, if I have understood you correctly.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
