### ISSUE TITLE
Device Request LUPUS 12050 ZigBee

### ISSUE THREAD

**Issue by ricosander** [dresden-elektronik/deconz-rest-plugin#2476]
The device is recognized, but without measuring information on deconz adapter in iobroker.

![image](https://user-images.githubusercontent.com/61231999/74975142-dc50e180-5426-11ea-9fc6-76711291d885.png)

deconz screenshots:
![image](https://user-images.githubusercontent.com/61231999/74975175-eb379400-5426-11ea-8beb-f028a7404c61.png)
![image](https://user-images.githubusercontent.com/61231999/74975181-effc4800-5426-11ea-9843-98e347c7fae2.png)
![image](https://user-images.githubusercontent.com/61231999/74975190-f38fcf00-5426-11ea-8b8e-b1ddaaf19f97.png)

**Comment by SwoopX** [comment]
Please issue a new device support request according to the wiki.

**Comment by ricosander** [comment]
I tried with this issue. What can I do better?

**Comment by SwoopX** [comment]
We'd require at lease a screenshot from the basic and simple metering cluster (for simple metering, there's the remaining attributes missing) with the attributes being read.

**Comment by ricosander** [comment]
Basic READ:![image](https://user-images.githubusercontent.com/61231999/75027672-3db49700-549f-11ea-8784-b1dda08fe7c5.png)
![image](https://user-images.githubusercontent.com/61231999/75027675-40af8780-549f-11ea-8b11-7f7532dc0a44.png)

Simple Metering READ:
![image](https://user-images.githubusercontent.com/61231999/75027699-4c9b4980-549f-11ea-99f9-3dbeb9701d6d.png)
![image](https://user-images.githubusercontent.com/61231999/75027706-4efda380-549f-11ea-80b5-8c22744ab4e9.png)

**Comment by SwoopX** [comment]
Sorry, but you forgot to read the attributes before. All values are default and therefore not usable.

**Comment by ricosander** [comment]
I changed the basic read picture in the post above.

**Comment by SwoopX** [comment]
Thanks, I'll follow up the next couple of days. Btw, does the "instantaneous demand" attribute show any reasonable values if you apply a load to the plug?

**Comment by SwoopX** [comment]
I checked the code and support is already implemented. You should definitively update your deconz version since it is rather old. After update, you may also restart iobroker.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
