### ISSUE TITLE
Not able to add Deconz to Harmony Hub as Hue bridge

### ISSUE THREAD

**Issue by Mimiix** [dresden-elektronik/deconz-rest-plugin#2486]
Today i learned you are able to add Deconz to Harmony as a Hue Bridge. However, my Harmony doesn't see it.

I configured Deconz on Home-Assistant in such a way (port 80), that i can use the Hue app and other apps.  

Is this new since the last versions? or is this Home-Assistant related?

**Comment by alex0411** [comment]
I also noticed this: A few versions back I was able to control deconz from my Harmony. Deconz is still added as Hue bridge in harmony, when I try to readd it, the Harmony Hub cannot find it.

**Comment by alex0411** [comment]
Are you using deconz in a docker Container?

**Comment by D3nnisd** [comment]
Yes i am. Using it with Home Assistant.

**Comment by alex0411** [comment]
Me too and I noticed this issue since I migrated to the docker environment. Could this be related? I will try to verify it

**Comment by ldplusse** [comment]
I have the same problem. I am just using DeCONZ with ConBee on Windows 10.
My Harmony Companion cannot find any Hue bridge.

**Comment by Mimiix** [comment]
Any news on this?

**Comment by w00druff** [comment]
I was only able to add Deconz to my harmony hub after switching Deconz to port 80.
Works with Deconz v2.05.75, 76 and 77 here.

**Comment by alex0411** [comment]
> I was only able to find Deconz with my harmony hub after switching Deconz to port 80.
> Works with Deconz v2.05.75, 76 and 77 here.

Hi,
What do you mean exactly with port 80? I am also running my deconz on port 80 (deconz is running in a docket container) and I am not able to add it to my harmony hub.

**Comment by w00druff** [comment]
Exactly what i mean.
Im not really concern with docker but is your Deconz container configured as bridge, host or macvlan network ?

**Comment by Mimiix** [comment]
I did some testing myself. 

I am running a VM with HA Generic linux install. the VM is within my DS218+ Synology nas. I run deCONZ with the addon.

In that case, the UPNP device sniffer didn't find it. 

I installed a second VM, installed clean ubuntu and installed deconz there. 

Now, my Harmony can find it. The issue is within either the Marthoc container or within the HA addon as i can use it within my HA.

**Comment by alex0411** [comment]
> Exactly what i mean.
> Im not really concern with docker but is your Deconz container configured as bridge, host or macvlan network ?

I have tested it with bridge and host network. With bridge I cannot find it at all, with host I am able to find it, but I cannot add it.

@Mimiix : Could you also add it? Because I can find deconz with my harmony hub, but I cannot add it. When I try to connect, nothing happens.

**Comment by Mimiix** [comment]
I can. I can provide a screen on discord.

**Comment by w00druff** [comment]
But when you find it you also start 60sec pairing mode at the Deconz Webinterface right ?
You should try macvlan, only with this network mode your container gets handled like a normal device in lan environment.

**Comment by Mimiix** [comment]
@w00druff I don't use a container. I installed the deconz package from apt.

After that, i told Harmony to search for a hue bridge. Then it asked me to press the Authenticate button in Phoscon.

Then it imported :)

**Comment by w00druff** [comment]
My message was related to alex0411 posts :-)

**Comment by alex0411** [comment]
> But when you find it you also start 60sec pairing mode at the Deconz Webinterface right ?
> You should try macvlan, only with this network mode your container gets handled like a normal device in lan environment.

Yes, I start the pairing mode and nothing happens.
I will try macvlan...

**Comment by alex0411** [comment]
Today I tested my setup with docker and macvlan: Now I am able to add deconz as bridge to the harmony :-)

**Comment by w00druff** [comment]
Great !

**Comment by Mimiix** [comment]
As this is my own issue and seems to be resolved for others. I'll close this on my own behalf. For me it is solved!
