### ISSUE TITLE
Device support - Blitzwolf temp and humidity sensor BW-IS4

### ISSUE THREAD

**Issue by Valcob** [dresden-elektronik/deconz-rest-plugin#2489]
Hey and thanks in advance for a great job!
I would like to get support for this small temp and humidity sensor from Blitzwolf the [BW-IS4](https://www.banggood.com/custlink/vKmvUY5pLF)
![image](https://user-images.githubusercontent.com/37367415/75275494-4abde700-580d-11ea-8d43-973e32dd209c.png)
It's totally fine discover-able by the  Deconz and I would like it to be passed to UI and my instance of home assistance

Basic Cluster:
![image](https://user-images.githubusercontent.com/37367415/75275693-91abdc80-580d-11ea-9393-0caf0669006f.png)
Blitzwolf by the way what the hell is this naming though??

Power Cluster:
![image](https://user-images.githubusercontent.com/37367415/75275800-bb650380-580d-11ea-88ba-7ba4127e7e99.png)

Temperature Cluster:
![image](https://user-images.githubusercontent.com/37367415/75275869-d59ee180-580d-11ea-8840-3897913c6091.png)

Humidity Cluster:
![image](https://user-images.githubusercontent.com/37367415/75275906-e5b6c100-580d-11ea-90c2-3635ef80de91.png)

Please let me know if there is some thing else I need to post or add may be

**Comment by SwoopX** [comment]
Already supported with release .74 from today.

**Comment by Valcob** [comment]
Tested, It's working thanks !!!

**Comment by srtxema** [comment]
i can´t sync with phoscon. is there any special sync mode?
