### ISSUE TITLE
Xiaomi Doube Tap Switch (WXKG02LM)

### ISSUE THREAD

**Issue by markuspf** [dresden-elektronik/deconz-rest-plugin#249]
I have 2 Xiaomi switches (https://www.gearbest.com/alarm-systems/pp_610095.html) which identify themselves as `lumi.switch_86sw2` (that is, they successfully seem to be joining the network, albeit they only seem to connect to one router);

From grepping the source they shouldn't be supported yet, but you might have guessed that I would like them to be ;).

**Comment by oleg77s** [comment]
[#165](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/165)
