### ISSUE TITLE
Device support request - Elko 316 GLED RF dimmer

### ISSUE THREAD

**Issue by uphillbattle** [dresden-elektronik/deconz-rest-plugin#2497]
https://proff.elko.no/getfile.php/13124115/produkter/doc/EKO05821/Datasheet4523410.pdf

This dimmer can be paired and controlled using the ConBee stick. 

Pairing is a pain - takes many tries - but eventually works.

Controlling the dimmer works, but setting the brightness at the same time as switching on or off does not work. For example, if the dimmer is off, it does not turn on if you set the brightness (to, for example, 50 %). So, if it is off, you first have to switch it on, then set the brightness.

Node info:
![image](https://user-images.githubusercontent.com/15340540/75435361-33891180-5953-11ea-882a-be4eb1fa95d1.png)

Clusters:
![image](https://user-images.githubusercontent.com/15340540/75435429-4996d200-5953-11ea-962a-a0c5fdeaf74e.png)

Basic cluster:
![image](https://user-images.githubusercontent.com/15340540/75435449-53203a00-5953-11ea-9f88-0ec8a6f6a70f.png)

Level Control cluster:
![image](https://user-images.githubusercontent.com/15340540/75435461-59161b00-5953-11ea-9ad4-f9455b92f4b4.png)

**Comment by ebaauw** [comment]
Most likely, the dimmer’s firmware doesn’t support _Move to Level with On/Off_.  See #2475.

**Comment by uphillbattle** [comment]
Yes, I belive that's the case. I read the thread you referenced [#1111](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1111#issuecomment-456464872). Were you able to make the ConBee send on and brightness commands sequentially? If so, it could be done like this for the Elko dimmer (if it was supported). It's what I'm currently doing with an automation in Home Assistant, so for controlling the dimmer alone from HA, I've got it working, but I can't use "scenes" in HA since there I can't make it send command sequentially.

**Comment by Mimiix** [comment]
@uphillbattle Is this  implemented?

**Comment by uphillbattle** [comment]
I'm not sure. Maybe @ebaauw knows.

**Comment by ebaauw** [comment]
> Were you able to make the ConBee send on and brightness commands sequentially?

Yes, but it's causing some other issues, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2824#issuecomment-635883214.
