### ISSUE TITLE
Hourly ghost events Samjin door/window contact causing false tamper state

### ISSUE THREAD

**Issue by jcallaghan** [dresden-elektronik/deconz-rest-plugin#2498]
Similar to ["Ghost events with Aqara vibration Sensor #2128"](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2128) I am seeing regular "vibration" events from my Smartthings sensors. I have reset sensor and changed the battery to troubleshoot however this is occurring on 20+ sensors.

I'm seeing an active state triggered usually in 60-minute intervals or 60 minutes from the last state change. These sensors form triggers in Home Assistant so I've had the automation disabled since I moved over to my Conbee II. 

The Conbee II is connected to deCONZ running in docker. I have 109 nodes made up of battery-powered sensors and 66 powered lights. 

## deCONZ 
![image](https://user-images.githubusercontent.com/7449908/75439069-08052780-5951-11ea-9576-fe318ebd8172.png)

![image](https://user-images.githubusercontent.com/7449908/75439844-7b5b6900-5952-11ea-97cf-b2b15ce84416.png)

![image](https://user-images.githubusercontent.com/7449908/75440219-41d72d80-5953-11ea-8ac1-3823b3ff7917.png)

## Home Assistant
![image](https://user-images.githubusercontent.com/7449908/75434047-db4d1200-5948-11ea-926b-c9909bf68923.png)

![image](https://user-images.githubusercontent.com/7449908/75434186-13eceb80-5949-11ea-8ad0-50957962e313.png)

![image](https://user-images.githubusercontent.com/7449908/75434210-1c452680-5949-11ea-8c34-04c98f9f1588.png)

It feels like the device is waking up and causing a false tamper alert. Can I share a log or anything from deCONZ to help troubleshoot this?

Off-topic. Any other pointers or tips I should be considering with this network?

**Comment by marcelodavanzo** [comment]
This is discussinf the same issue, unfortunately it doesn't look like there's any interest in fixing this.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1848

**Comment by jcallaghan** [comment]
@ebaauw has kindly reviewed at the code and with the help of the device will look at this further. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1848#issuecomment-593000538

**Comment by Mimiix** [comment]
As it's a duplicate, this issue will be closed. However, i've assigned a label to #1848 to prioritize it.
