### ISSUE TITLE
Aqara switch WXKG12LM not able to pair

### ISSUE THREAD

**Issue by Eppie66** [dresden-elektronik/deconz-rest-plugin#2499]
Within my Hassio DeConz install with Conbee II stick, I added these Aqara switches earlier. When I try to add in recent version 2.05.74 nothing works to get additional switches paired. The old ones are in the config and work. Very frustrating...anyone a suggestion? Rebooting or restarting is not the solution, and I tried different switches of the same type.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
