### ISSUE TITLE
Aqara switch is missing from deconz ui

### ISSUE THREAD

**Issue by Knapoc** [dresden-elektronik/deconz-rest-plugin#2501]
My Aqara round smart switch is showing up in phoscon and via the rest api, but is missing from deconz ui. The switch/sensor is missing from the node list and is not visible in the node map.
However it is fully functioning when I'm listing to its button events in home assistant via the deconz integration.

phoscon:
![phoscon](https://i.imgur.com/mwdF2Pu.png "phoscon")

rest-api:
**GET**: `http://ip:8080/api/apikey/sensors/12`
```
{
  "config": {
    "battery": 100,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "f23b18aa5609e765feb9d01198acc080",
  "manufacturername": "LUMI",
  "mode": 1,
  "modelid": "lumi.sensor_switch",
  "name": "Smart Switch Robovac",
  "state": {
    "buttonevent": 1002,
    "lastupdated": "2020-02-27T18:38:12"
  },
  "type": "ZHASwitch",
  "uniqueid": "00:15:8d:00:04:23:f2:45-01-0006"
}
```

**Comment by Smanar** [comment]
I don't think it's possible.
Have you check using UniqueId ?

**Comment by Knapoc** [comment]
what do you mean exactly? I do have the unique id as a value in the rest api. Is there something else I should check?

**Comment by Mimiix** [comment]
@Knapoc is this fixed?

**Comment by Knapoc** [comment]
Yeah repairing fixed the issue.
