### ISSUE TITLE
Ikea Trådfri Rollos sind nach Neustart weg

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2508]
Auch nach dem Update auf 2.05.74 sind die IKEA-Rolläden nach einem Neustart nicht mehr vorhanden.
Die Phoscon App zeigt keinen Fehler, den Fehler bemerkt hingegen ioBroker.

**Comment by SwoopX** [comment]
Die Informationslage ist hier doch eher dünn, so dass es schwierig wird zu helfen.

Was ist genau passiert? Welches Modell? Wo verschwinden die Geräte? In de deconz GUI, oder Phoscon, oder beides?

Ich würde übrigens empfehlen, den Post auf englisch zu verfassen. So ist die Chance wesentlich größer, dass andere bei der Ursachenforschung helfen können.

**Comment by Mimiix** [comment]
After consultin @SwoopX , Closing #2508
