### ISSUE TITLE
Conbee 2 not functional after manual firmware update failure

### ISSUE THREAD

**Issue by jacgl** [dresden-elektronik/deconz-rest-plugin#2509]
Hi,
I am using Conbee 2 with ubuntu 18.04. Today I started manual FW upgrade with last image (264A0700->26530700), according to ubuntu procedure.
Unfortunately, GCFFlasher_internal stopped the update in about 30% of progress with exit message like lost connection to device (reason? really not known for me).
Now Conbee dongle is not functional, it periodically appears on usb as /dev/ttyACM0 for a second or 2, then dissapears for a few seconds. Anyway, it is not visible by deconz/phoscon.
What can be the next step to investigate?
Regards

**Comment by Smanar** [comment]
Perhaps that https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2493 ?

**Comment by jacgl** [comment]
Thanks, it works.
But I had to start the command many, many times. At the and FW programmed correctly.

**Comment by salopette** [comment]
Are there any new FW for the Conbee-ll?

I didn't find it in the wiky.

ConBee II
wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26490700.bin.GCF

![sshot-3](https://user-images.githubusercontent.com/32480002/75604573-804b2480-5ada-11ea-8ffa-e572172f1670.jpg)

**Comment by Knapoc** [comment]
> Are there any new FW for the Conbee-ll?

The newest firmware release for Conbee II is `0x264a0700` as [found here](http://deconz.dresden-elektronik.de/deconz-firmware/).

**Comment by ebaauw** [comment]
> it seems 0x26530700.bin.GCF is the newest one

Beware, that's a beta version, and doesn't work in all situations, see #1261.  I think `4a` is the latest stable release.  It's distributed with recent versions of deCONZ in installed to `/usr/share/deCONZ/firmware`.

**Comment by Knapoc** [comment]
I just recognised that and will update my previous post to avoid frustration :).

**Comment by salopette** [comment]
ok, but it is really sad that Wiky is not kept up to date.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
