### ISSUE TITLE
Busch Jaeger FOH domoticz

### ISSUE THREAD

**Issue by Bastiaan1981** [dresden-elektronik/deconz-rest-plugin#2510]
Hello,

There is an issue with the new Busch Jaeger Frinds of Hue switch.
I have updated the conbee2 firmware and updated the deconz software.

My issue is that when i press button 1 long. Domoticz sees it as button 2
Long press 2 in domoticz button 4
Long press 3 in domoticz button 6
Long press 4 in domoticz button 8

It needs to be
Long press 1 in domoticz button 5
Long press 2 in domoticz button 6
Long press 3 in domoticz button 7
Long press 4 in domoticz button 8

Anyway to fix this ??

Kind regards
Bastiaan

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
