### ISSUE TITLE
REST-api reports wrong position/brightness value for Fyrtur

### ISSUE THREAD

**Issue by Knapoc** [dresden-elektronik/deconz-rest-plugin#2511]
In the releases after 2.05.71 there's a mismatch between the value reported from deconz GUI and the rest-api.

As far as I understand the rest api should report `bri: 255` and not `bri: 254` at a lift percentage of 100

REST output:
```json
{
  "etag": "5481e5d77f899bdb4c2cb42d2cfca47a",
  "hascolor": false,
  "manufacturername": "IKEA of Sweden",
  "modelid": "FYRTUR block-out roller blind",
  "name": "Fyrtur 1",
  "state": {
    "alert": "none",
    "bri": 254,
    "on": true,
    "reachable": true
  },
  "swversion": "2.2.009",
  "type": "Window covering device",
  "uniqueid": "cc:cc:cc:ff:fe:f4:c9:24-01"
}
```

![deconz](https://i.imgur.com/XTKv7m3.png "text")

**Comment by Kane610** [comment]
From what I've seen in comments from @ebaauw 254 is indeed the correct value

**Comment by ebaauw** [comment]
Correct.  254 is the max value for `state.bri`.

**Comment by Knapoc** [comment]
Ah I just saw the pull request. It seems the [documentation](https://dresden-elektronik.github.io/deconz-rest-doc/lights/#getstate) is outdated or I'm missing something in my understanding: 

Field | Type | Description
-- | -- | --
state.bri | Number (0..255) | Brightness of the light. Depending on the light type 0 might not mean visible "off" but minimum brightness.

But it seems that 254 is the appropriate value, since lights show the same on full brightness.
