### ISSUE TITLE
Installed Deconz worked fine! Next day lights do not respond.

### ISSUE THREAD

**Issue by skitzow88** [dresden-elektronik/deconz-rest-plugin#2513]
I installed Deconz and ordered a Conbee2 to replace my hue and aqara hub. Everything worked fine when installing only thing i didnt get to work is to add independent bulbs within phoscon. I worked arround this by adding light groups. The next morning my lights wont respond. (Both aqara and hue bulbs and switches stopped working, sensors are working fine. When running Homebridge -I -D i dont see any errors. Where do i even begin with troubleshooting? Keep in mind that i suspect that i got some wifi issue in here, as my sonos keeps drifting and losing connection. (Edit: Never mind, definitely not a wifi related issue. Sensors keep connection) 

When looking within the phoscon webapp i can see that the lights are greyed out, so i suspect i lost connection with my bulbs.

**Comment by Smanar** [comment]
So you have loose bulbs and not sensors ?
Thery are coming back if you make a power on/off ?

Are you using the last firmware ?

**Comment by skitzow88** [comment]
Yes i lost all the bulbs (they are greyed out within the phoscon webapp) Sensors working fine. 
No they wont come back after rebooting/shutting down. 

My gateway information: 

<img width="369" alt="Screenshot 2020-02-29 at 15 18 59" src="https://user-images.githubusercontent.com/56042035/75609207-db930c00-5b06-11ea-9ef0-d18d0afc527d.png">

The greyed out bulbs: 
<img width="1200" alt="Screenshot 2020-02-29 at 15 17 08" src="https://user-images.githubusercontent.com/56042035/75609212-e352b080-5b06-11ea-9327-6f8ee45cc02f.png">

Sensors: 

<img width="996" alt="Screenshot 2020-02-29 at 15 17 26" src="https://user-images.githubusercontent.com/56042035/75609217-eea5dc00-5b06-11ea-8824-8020081f7e23.png">

**Comment by Smanar** [comment]
Have you try to take a look on last posts on this issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1261

On my side I m thinking like you, not an hardware or connexion problem (but sensors need more time to be marked as unrecheable, are you sure they are working ATM ?)

**Comment by skitzow88** [comment]
Well i did read the article, but thats related to losing some light bulbs, my setup keeps losing every light bulb possible. At this moment i can also not confirm if the sensor respond. I will start a fresh reinstall of  homebridge, conbee and all of the plugins. Will report back when everything is reinstalled.

**Comment by Smanar** [comment]
I don't thnik re-install will change something, as deconz is working as stand alone app.

**Comment by skitzow88** [comment]
i agree, but will be easier to troubleshoot when everything is freshly setup. Almost done, got homebridge up and running again. Still gotta install 2 plugins and then deconz

**Comment by skitzow88** [comment]
Well reinstalling everything did gave me the option to expose the lightbulbs separately to homebridge this time! At the moment everything is running as expected.

<img width="724" alt="Screenshot 2020-03-01 at 00 00 56" src="https://user-images.githubusercontent.com/56042035/75616788-3142d500-5b56-11ea-8261-24d5c6387078.png">

<img width="695" alt="Screenshot 2020-03-01 at 00 01 09" src="https://user-images.githubusercontent.com/56042035/75616791-343dc580-5b56-11ea-90c0-9e20b146e03f.png">

<img width="884" alt="Screenshot 2020-03-01 at 00 01 16" src="https://user-images.githubusercontent.com/56042035/75616792-343dc580-5b56-11ea-89fc-25242c94bd83.png">

**Comment by skitzow88** [comment]
Well next day everything is still working as expected! HomeKit automations with smart switches don't respond as they should but i think homekit software is to blame. When i configure the smart switches within in phoscon they work fine.

**Comment by skitzow88** [comment]
Issue closed, im quite sure that i did something wrong when configuring/installing Deconz the first time. A fresh installation did solve all problems i was experiencing in the first configuration. Now i can see more options within Phoscon.
