### ISSUE TITLE
ASDU frame example. Please help

### ISSUE THREAD

**Issue by DoctorZIP** [dresden-elektronik/deconz-rest-plugin#2521]
Hi,
I'm developing Android Things software driver for ConBee2. UART document is very useful and all of request/response works as documented but it lack of information about ASDU frame (and that's right). Few hours discovery of ZigBee specification and ZCL specification documents doesn't gives any result. Could anybody provide me with ASDU frame example (e.g. how to get device Manufacturer name and so on)? Or point me out place in ZigBee corresponding docs. Thanks for further help!

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
