### ISSUE TITLE
How to get wlan AND deConz working?

### ISSUE THREAD

**Issue by cynaut** [dresden-elektronik/deconz-rest-plugin#2522]
Hi there,

there is a problem I can't fix as a beginner.
I want my wlan working and deConz working.
Now the deConz kicks out the wlan every time when I start the software.

Is there a code or update I can use?

Thanks in advance

cynaut

**Comment by Smanar** [comment]
Perhaps something like that https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2387

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
