### ISSUE TITLE
Dresden scene switch re-added but not working

### ISSUE THREAD

**Issue by ftonat** [dresden-elektronik/deconz-rest-plugin#2524]
Hi,
I have reset an existing scene switch after battery replacement.
Now I cannot get it working again.

I have re-joined the switch via phoscon.
It was recognized as scene switch.
I was wondering why there is no “group” for this switch, for for other scene and lighning switches.

My intention is to get the switch working with basic functions (on/off and 4 scenes), like the others, even when deconz gateway is offline.

The other switch for the same room is still working as intended. This one is also visible as “group” in phoscon main page, but not the re-connected one.

As my installation is old and lots of lights, switches and sensors were connected in the last years, I am afraid the database or installation itself is not consistent anymore

Any hints?

Frank

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
