### ISSUE TITLE
Coordinator gets name of new device (Elvis Container)

### ISSUE THREAD

**Issue by lukicsl** [dresden-elektronik/deconz-rest-plugin#2525]
I upgraded my docker container to the newest version Elvis
I tried to add a new GU10 Ikea lamp.
After adding the lamp through Phoscon and renaming it I see that the coordinator got the new name of the lamp.

![image](https://user-images.githubusercontent.com/23736716/75664402-b4f1e400-5c72-11ea-9fc3-1379a0caf59a.png)

The light has also no attributes in phoscon:
![image](https://user-images.githubusercontent.com/23736716/75664592-fbdfd980-5c72-11ea-93d7-00de02ed1833.png)

**Comment by manup** [comment]
An update will be released shortly, which filters the Gateway resources out of the lights list in the Phoscon App.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
