### ISSUE TITLE
Device support request - Samsung Smarthings 2014 Motion Sensor - Centralite 3305-S 

### ISSUE THREAD

**Issue by rmotapar** [dresden-elektronik/deconz-rest-plugin#2529]
I would like to request adding support for Samsung Smarthings motion sensor 2014 version. It's made by Centralite and model is 3305-S. When I tried to pair via Phoscon app, it did say that the sensor is ready but I am not seeing anything in home assistant. Attached couple of screenshots. Please let me know if there is anyway I can add this to home assistant. It does appear to read the temperature value correctly in Deconz GUI.

![image](https://user-images.githubusercontent.com/13870280/75788814-5f7b0d00-5d2e-11ea-8043-8c1153fb196c.png)

![image](https://user-images.githubusercontent.com/13870280/75788891-7d487200-5d2e-11ea-87bc-664e2c9fb260.png)

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
