### ISSUE TITLE
Phoscon webapp Gateway Settings only accessible from phoscon.de

### ISSUE THREAD

**Issue by kibbles6** [dresden-elektronik/deconz-rest-plugin#2530]
Trying to access the Gateway settings from the local homepage gives a "Gateway is not reachable..."
error. 
Using the going back to login option links to phoscon.de all settings work there but i'd much rather have everything locally without relying on an external homepage is there a way to get the old behavior back? 
using version 2.05.74 / 12/12/2019 
firmware 264A0700

**Comment by Smanar** [comment]
Perhaps same issue than https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2517

**Comment by kibbles6** [comment]
> I know it's not the same problem, but take a look here #2517

Thank you that helped me fix it!
