### ISSUE TITLE
New Light dresden elektronik	ConBee II ??

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2536]
I have the entry "Unknown 39 | dresden elektronik | ConBee II -- | -- | --" in the list of lamps.
Don´t know what to do with it. Entry is coming back after deleting it.

**Comment by Smanar** [comment]
Yep, it' s a new feature
>Support RaspBee, ConBee, ConBee II, XBee under lights resources

But with a little issue > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2525

**Comment by Mimiix** [comment]
Please read: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2472#issuecomment-590541006

Closed for now :)!
