### ISSUE TITLE
Suggestion: deCONZ groups should pass child scenes as an attribute

### ISSUE THREAD

**Issue by Davst** [dresden-elektronik/deconz-rest-plugin#2537]
It would be nice if deCONZ groups could pass scenes along as an attribute so you could set up a button in Home Assistant that could cycle among the available scenes.

**Comment by ebaauw** [comment]
They do.  It’s called... `scenes`.

**Comment by Davst** [comment]
Hey. Cool. Someone trying to be clever, on the internet. So original. 

And no. The groups don’t pass the scenes contained in them as an attribute of the group. If they do Home Assistant doesn’t seem pick them up and I should ask for it on the HA forum instead. But I do think HA sees everything that’s passed through. 

Which is:
```
effect_list
is_deconz_group
all_on
friendly_name
supported_features
```

And as I said. For using switches in more clever ways. It’s be nice to have the list of the scenes available *in this group* since that’d help cycling through scenes. Or creating selects on cards for for available scenes

**Comment by Kane610** [comment]
No @ebaauw is correct in the context of this repository that is absolutely true. You are talking about Home Assistant which has nothing to do with this repository.

**Comment by Davst** [comment]
@Kane610 Ok, so I appologise.. it seems I made the mistake that the attribute would need to be made available in the REST API för Homeassistant to be able to consume it. I'll post in the Home Assistant repo about the request instead.

Is there a suggestion as to how they should read the scenes belonging to a group that I can pass on to them?

**Comment by Kane610** [comment]
It depends on what way you want to develop your logic. It would be quite easy in Appdaemon.

The naming follow this logic https://github.com/Kane610/deconz/blob/2a51655128148fe77a838097234877f6df6d2b2a/pydeconz/group.py#L267

**Comment by Davst** [comment]
Wouldnt this still run intro issues with say if groups “Kitchen” and ”kitchen windows” both existing as one groups scenes would be container in the name path for the other?

**Comment by Kane610** [comment]
I guess that's up to you

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
