### ISSUE TITLE
Philips Hue Go

### ISSUE THREAD

**Issue by cookingeek** [dresden-elektronik/deconz-rest-plugin#2540]
I have the problem that my Philips Hue GO in battery mode is not reachable via deconz after a while. 

Does anyone else have the problem or is the lamp broken?

**Comment by maikkoe** [comment]
I think this is not an issue. Me and a friend have the same behavior with Hue Go (first and second Gen.).

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
