### ISSUE TITLE
Pair Iluminize Zigbee 3.0 Schalt-Aktor Mini

### ISSUE THREAD

**Issue by MornLum** [dresden-elektronik/deconz-rest-plugin#2543]
Hallo,

I have no tried everything to connect the Iluminize | Zigbee 3.0 Schalt-Aktor Mini to my Zigbee. I am Working with deCONZ / Phoscon and nearly had any issues until know. Anybody some experinece with this Aktor to connect and suggestions?

**Comment by SwoopX** [comment]
What's the issue?

**Comment by MornLum** [comment]
I cannnot pair with Phoscon/deconz. Am I right that it is supported?

**Comment by MornLum** [comment]
Hallo, solved the issue myselfe. It is important to pair near the Zigbee-Stick. Next to a repeater is not sufficient.
