### ISSUE TITLE
IKEA Trådfri 250lm E27 Bulbs are incorrectly identified

### ISSUE THREAD

**Issue by scottsweb** [dresden-elektronik/deconz-rest-plugin#2544]
I recently grabbed a few of these bulbs (https://www.ikea.com/se/sv/p/tradfri-led-ljuskaella-e27-250-lumen-tradloes-dimbar-varmt-sken-globformad-brun-klarglas-70455676/) and I am attempting to pair them with my Conbee 2. The bulbs show up in the software but are incorrectly identified as:

```
Vendor: dresden elektronik
Model: ConBee II
Version: 0x26490700
```

I am running software `2.05.74 25/02/2020` and firmware `26490700` on a Rasberry Pi 4 using the docker image from `marthoc/deconz`.

I believe them being incorrectly identified is not allowing me to control them properly. Turning them on and off from Deconz does nothing.

**Comment by Smanar** [comment]
I think you have same problem than here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2456

Was not your device that are detected but the conbee.

**Comment by joch** [comment]
I have that light, and it's detected successfully, so it's probably related to the issue mentioned above.

**Comment by scottsweb** [comment]
Thanks for the pointers. Just upgraded to `2.05.75` and the phantom device/Conbee is no longer appearing which is good (and less confusing) during a scan. 

I am still struggling getting these bulbs to pair though. Will keep trying! They pair with the remote just fine :/

**Comment by scottsweb** [comment]
Changing the Zigbee channel to `11` seems to have fixed it. I wasn't able to change the Zigbee channel until this version `2.05.75` so that is progress to. Closing.
