### ISSUE TITLE
Several errors after installing Deconz and Hue-emulator

### ISSUE THREAD

**Issue by NightFalcon650** [dresden-elektronik/deconz-rest-plugin#2545]
Goodday,

After installing deconz and hue-emulator according the manual on github everything worked.
After rebooting i have to start the services by hand and they stil keep giving errors.

![image](https://user-images.githubusercontent.com/7109209/76147500-211e7e80-609d-11ea-8a10-32ece17b18fe.png)

Whats wrong and what could i do to fix it?

**Comment by SwoopX** [comment]
To me it looks like you are trying to start 2 deconz services simultaneously. "deconz.service" is for headless setups and "deconz-gui.service" for GUI mode, requiring and X-Server. Choose the one you need and do `sudo systemctl enable SERVICE`, for the other one `sudo systemctl disable SERVICE`. Afterwards, restart the serivce of your choice.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
