### ISSUE TITLE
Device support request - Iris Contact Sensor V3

### ISSUE THREAD

**Issue by redwoodimage** [dresden-elektronik/deconz-rest-plugin#2548]
Manufacturer: iMagic by GreatStar
Model Number: 1116-S
deviceTypeId: 176
idAsInt : 1
inClusters : 0000,0001,0003,0020,0402,0500,0B05,FC01,FC02
endpointId : 01
profileId : 0104
outClusters : 0003,0019
model : 1116-S
![x6](https://user-images.githubusercontent.com/39349413/76154513-743f0400-6092-11ea-9084-baae35c555a5.png)
![x5](https://user-images.githubusercontent.com/39349413/76154474-d9462a00-6091-11ea-8dd1-f46e3cc2924a.png)
![x4](https://user-images.githubusercontent.com/39349413/76154475-da775700-6091-11ea-9d59-e9d2dcc2c672.png)
![x3](https://user-images.githubusercontent.com/39349413/76154477-db0fed80-6091-11ea-9e5f-a4c5d3b14dce.png)
![x2](https://user-images.githubusercontent.com/39349413/76154478-dba88400-6091-11ea-8fbb-c63a444ebd6e.png)
![x1](https://user-images.githubusercontent.com/39349413/76154479-dba88400-6091-11ea-9feb-4a176b60665e.png)

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
