### ISSUE TITLE
I am using docker and the bind drop down box is grayed out 

### ISSUE THREAD

**Issue by redwoodimage** [dresden-elektronik/deconz-rest-plugin#2549]
When I vnc into the container the bind drop down box is grayed out. Am I missing something what do I have to do to enable it.

**Comment by redwoodimage** [comment]
I am using phoscon 2.05.74 and firmware 26490700, yes the conbee is detected. 

root@debian:/# GCFFlasher_internal -l
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
![xx](https://user-images.githubusercontent.com/39349413/76167105-85832180-6121-11ea-91fb-bdb66ad14458.png)

**Comment by Smanar** [comment]
Haaa ok^^ I understand.

You want to make a bind ?

Just use drag and drop. Wait 5mn I m searching the procedure.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
