### ISSUE TITLE
Request Device Support Tuyatec door/window sensors

### ISSUE THREAD

**Issue by artipa** [dresden-elektronik/deconz-rest-plugin#2559]
I would like to request adding support for Tuyatec Door/Window sensor

![image](https://user-images.githubusercontent.com/17012691/76235940-21994f80-622c-11ea-8ee8-e11074c595a5.png)

![image](https://user-images.githubusercontent.com/17012691/76235989-3d9cf100-622c-11ea-812e-1bb867f256f3.png)

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by martins8977** [comment]
Hi,

After trying to add the nedis sensor, it seems that doesn't have a configuration in deconz.
