### ISSUE TITLE
[Device Support Request] Samsung SmartThings Outlet 2018 Model ID: GP-U999SJVLDAA

### ISSUE THREAD

**Issue by jbruening** [dresden-elektronik/deconz-rest-plugin#2576]
https://www.samsung.com/us/smart-home/smartthings/outlets/samsung-smartthings-outlet-2018-gp-u999sjvldaa/

Side of the unit also lists M/N "IM6001-OTP01"

This looks similar to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2121, but lacks the 'Simple Metering' cluster

Phoscon currently treats this as an on/off "light". It supposedly supports power monitoring as well though.

![image](https://user-images.githubusercontent.com/1760487/76475900-9e0f6800-63bd-11ea-92c8-68471502da10.png)

![image](https://user-images.githubusercontent.com/1760487/76475942-b4b5bf00-63bd-11ea-9c91-c1065f276bc3.png)

![image](https://user-images.githubusercontent.com/1760487/76476106-360d5180-63be-11ea-83b0-558e0454399f.png)

Electrical measurement cluster picture taken with a 20 inch box fan set to slowest setting of 3
![image](https://user-images.githubusercontent.com/1760487/76476211-85ec1880-63be-11ea-984c-6bb8aab63ecb.png)

**Comment by SwoopX** [comment]
I can take care of that. Can you please provide a screenshot of the node info panel as well? Thanks!

**Comment by jbruening** [comment]
![image](https://user-images.githubusercontent.com/1760487/76568566-51d03080-646e-11ea-9ede-21ac3a6524b4.png)

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by jbruening** [comment]
Yes, it is resolved. I re-added the device in deconz (2.5.75) (which appeared to show nothing different in phoscon about it), and then restarted home assistant.  There is now a wattage sensor showing up.

![Uploading firefox_2020-06-11_12-10-28.png…]()
