### ISSUE TITLE
Aqara vibration sensor changes sensitivity by itself not showing in config

### ISSUE THREAD

**Issue by mickejo** [dresden-elektronik/deconz-rest-plugin#2581]
I have a Aqara vibration sensor to detect wash machine vibrations. I set the sensitivity to 1 and it worked very well for a few days until it suddenly stopped to detect vibrations. If I shake the sensor by hand it detects vibration so it seems the sensitivity has changed somehow. The sensitivity level is still 1 according to the sensor config.
I then tried alot of things, resetting the sensitivity level to 21, and back to 1 taking out the battery, pushing the button on the sensor to check connectivity. Suddenly it started to work as expected and everything was fine for approximately 3 or 4 days and the same thing happened.
Could it be that the sensor resets its sensitivity and this somehow is not shown in the config?
I know the Aqara motion sensor duration configuration resets itself after some time, but that is shown in the config.

I used Deconz 2.05.67 and a Raspbee

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
