### ISSUE TITLE
All sensors takes a while to be reachable . 

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#2584]
Or i need to mannually activate them by passing in front of them.. or  closing doors etc.. 

I am on deconz .73 . Was on .75 when i saw this... 

I can't remember what build didn't have this problem.

**Comment by MattL0** [comment]
what is the last release? do not want to be on beta

**Comment by Smanar** [comment]
You mean after a restart ?
Or all the time, when you have triger one, it stay reachable for a long time ?

**Comment by MattL0** [comment]
After restarting deconz only.

**Comment by Smanar** [comment]
Ok so it's something normal.
For exemple Xiaomi device send notification only every hour or if you have a changement, the rest of time they are sleeping.
So if the device have already send its notification and nothing change for him, the conbee need 1 hour for the next notification and set the device in reachable state.

Sensor can send request, but they don't answer to the gateway.

**Comment by MattL0** [comment]
Ha ok thanks a lot!  So the xiaomi sensors will stay in the network, even if they are unreachable since one hour?

**Comment by MattL0** [comment]
Will have to modify some automation here. But it is weird that it was no behaving like that before... the last time I saw this was in the .35-50 deconz version

**Comment by Smanar** [comment]
Warning, I m say that, just if you restart deconz.
You will not have this problem if deconz stay online.

>Or i need to mannually activate them by passing in front of them.. or closing doors etc..

If the device was realy out of the network, you will not see it when you activate them using them.

**Comment by MattL0** [comment]
Then deconz should mark them as reachable ...and if there is no sign of then after 2 hours then it should set them as unreachable .



Sent from an Iphone
________________________________

**Comment by Smanar** [comment]
Only 2 hours ?
I was sure it was at least 24h.

**Comment by ebaauw** [comment]
`reachable` is utterly useless and best ignored.  See #2590.

**Comment by MattL0** [comment]
> Only 2 hours ?
> I was sure it was at least 24h.
> 
> BTW.
> Are you looking for reachable state on phoscon or on third application ?
> 
> Because I have just make a fast try (reboot deconz), and reachable state havent moved on Phoscon. But was realy short off line.

I am using it on homeseer (via norered deconz ) . And my sensors becomes unreacheable. 

I will just remove the automation that use the unreachable state to send me a pushover message . Thanks guys. 

Hope it will be removed for last seen !

**Comment by MattL0** [comment]
Didn,t a little test today because this time the senors where not unreacheable ( deconz v.72) at restart of deconz in phoscon

- on restart of deconz sensors are not unreacheable
-on restart of computer sensors are not unreacheable 
-updating to deconz v.2.05.75 : sensors are not unreachable. 


So.. i guess it was some sort of ''healing'' or just a coincidence yesterday?

**Comment by Smanar** [comment]
Coincidence for me ^^, I think it's a timing situation.
