### ISSUE TITLE
Recovering manually from another filesystem

### ISSUE THREAD

**Issue by tuomassa** [dresden-elektronik/deconz-rest-plugin#2588]
My raspberry pi installation broke because of SD card failure probably, but I was able to copy the rootfs to safety. Now I installed new raspbian, and was wondering what folders I need to copy from old rootfs to new rootfs that all my zigbee stuff is automatically there and I dont have to reset and re-do everything?

**Comment by ebaauw** [comment]
The network settings are stored on the device (RaspBee, ConBee), in non-volatile memory.
The REST API settings are stored in the deCONZ database.
After installing deCONZ, _before_ starting it, you want to restore everything under `~/.local/shared/dresden-elektronik/deCONZ`.

**Comment by tuomassa** [comment]
Thanks so much! This worked
