### ISSUE TITLE
Cannot connect to hue bulbs, IKEA works fine

### ISSUE THREAD

**Issue by andersbillesoebeck** [dresden-elektronik/deconz-rest-plugin#2593]
Hi all, 

After a hassio update (to 105.x) i lost All connection to my Hue bulbs (about 10), whereas my Aqara sensors and IKEA bulbs kept working fine.

I reverted to earlier network config, no luck. With help from this forum, I managed to update the aincent firmware I used to the newest. Still no luck.

Now I have a setup,that just will not connect to Hue bulbs, even in a clean install (deleted the Hassio docker many times). Alternate channels tried. I bought a dimmer switch to reset and wait until the bulbs flashes. It have worked before.

Any ideas? Pairing IKEA still works, so ConBee does not seem to be broken.

Help, my entire light system have been out for almost a month!

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
