### ISSUE TITLE
IKEA Blind not showing up in the deconz page, but does show up on the graphical representation

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/deconz-rest-plugin#2597]
I am running deCONZ as a HomeAssistant addon.
I have tried adding an IKEA repeater, IKEA blind and IKEA controller to Deconz.
When I view the deconz connections in the graphical via VNC then all the items show up.
But if I view via the Deconz webinterface I don't see the blind, my guess is that it would appear under lights.

I can't get the blind to react either, so my wish was to remove it from the zigbee network, and then try adding it again, but I don't see how to do that, when it doesn't show up in the first place.

The VNC view:
![image](https://user-images.githubusercontent.com/13660621/76948254-2bdfdb80-6907-11ea-9ecf-a8695c276b1a.png)

**Comment by fribse** [comment]
I have tried re-adding the 'range extender', the controller and the blind. I can get the controller paired with the range extender, and the blind, and it does show up in the VNC console, but I can't make it react through the deconz, it works through the IKEA remote control.

**Comment by fribse** [comment]
Probably the same as #2558, mine is also 2.05.75

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
