### ISSUE TITLE
Raspbee not working with Ubuntu Mate (ARM)

### ISSUE THREAD

**Issue by Giusep502** [dresden-elektronik/deconz-rest-plugin#260]
Hi, 
I have Ubuntu Mate on my Raspberry Pi 3, and i can't use Raspbian now. I Tested the Raspbee with its own image (so with Raspbee) and it worked, so it's not a connection problem.
I tested 3 different version (18, 35 and the new beta), and in all three versions it appears the black connect button, but nothing happens if i press it. Also the icon at the top is the "not connected" one. But somehow it prints "Raspbee". If i have the Bluetooth enable, instead, it says that it needs a firmware update, but i updated it when i tested it with raspbian! (some hours before)... And also if i click on "Update firmware" it seems that it's going, but then it finish and it says "Update Firmware" again, so I think it's a sort of bug.. 
Also, i need the wi fi connection on, so I can disable only the bluetooth

Any ideas?

**Comment by mariusmotea** [comment]
Very likely Deconz ask for firmware update when communication with Raspbee module is not successfully. You need to ensure there is no shell connected to serial port because this enter in conflict with deconz. On raspbian you disable this form raspi-config appication.

**Comment by Giusep502** [comment]
So it doesn't work if i have, let's say, an Arduino in a USB port?
In that case it's possible that the Wi-Fi module can create a conflict too

**Comment by Giusep502** [comment]
The thing is, i have this ROS system with Raspberry and Ubuntu Mate, and i wanted to control Lights using the same raspberry in which i do also other things with ROS. I was thinking to try ROS on Raspbian to make sure the Raspbee works, but i really would like to make it work with Mate, that shouldn't be so different in theory

**Comment by mariusmotea** [comment]
By default Raspberry pi distributions use internal serial port from GPIO pins to allow you a secondary shell access without the need of keyboard + monitor. You need to tell your Ubuntu Mate to not use this serial port (/dev/ttyAMA0) anymore because you needed for Raspbee module. This has anything  to do with what you connect on USB ports.

**Comment by Giusep502** [comment]
I See! I kinda figured that out too, but i really don't know how to say that.. For first i have disabled bluetooth, that was using ttyAMA0, but now i don't know what is using ttyAMA0..
Also I tried using the tool for flashing the Raspbee firmware, and he seemed to recognize the bootloader of the Raspbee after i disabled the bluetooth, and also seemed to flash the firmware (but it was stuck at half of the upload... in fact, then I used a SD with Raspbian to update the firmware). So It seems like something is using ttyAMA0 at the same time

**Comment by Giusep502** [comment]
I figured it out, this works! And I think it should be done in all the distribution of Raspberry:
https://raspberrypi.stackexchange.com/questions/45570/how-do-i-make-serial-work-on-the-raspberry-pi3 (the 6 Steps one)

Thank you! 👍
