### ISSUE TITLE
Device Support Request - Sonoff S31 Lite zb

### ISSUE THREAD

**Issue by Bitmaster20** [dresden-elektronik/deconz-rest-plugin#2601]
Product page can be found here
https://sonoff.tech/product/zigbee-smart-plugs/sonoff-s31-lite-zb

![Sonoff1](https://user-images.githubusercontent.com/62363766/77021216-c4984a80-694b-11ea-98ca-ea3a7433128d.PNG)
![Sonoff2](https://user-images.githubusercontent.com/62363766/77021250-d1b53980-694b-11ea-9c81-2f333097b022.PNG)
![Sonoff3](https://user-images.githubusercontent.com/62363766/77021257-d548c080-694b-11ea-8f43-7d0df8d561cd.PNG)

**Comment by Bitmaster20** [comment]
Devices seem to show up in Phoscon so I'm not sure if there is any further coding needed.   However its not listed on the supported devices page.
![phoscon1](https://user-images.githubusercontent.com/62363766/77032803-0c7a9a00-696b-11ea-967d-661531a9d239.PNG)

**Comment by SwoopX** [comment]
It doesn't have any sensors, so that's beneficial for you. On/off functionality is almost always supported out of the box. Since the device seems to be working, there's nothing left to do.

**Comment by Bitmaster20** [comment]
Thanks.  I’ve tested this and it’s triggering on/off without issues.  Am I allowed to edit the supported devices page to add as a supported device (which I don’t know if I have permission or access to do) or is there a formal process to go through first?

**Comment by SwoopX** [comment]
Well, afaik, it is generally free to edit.

**Comment by Bitmaster20** [comment]
I've added it as a supported device
