### ISSUE TITLE
New Device Request for Hive Motion Sensor

### ISSUE THREAD

**Issue by eddiehowrya** [dresden-elektronik/deconz-rest-plugin#2606]
This request is for the Hive motion sensors which are part of the British Gas family of smart devices.
https://www.hivehome.com/products/hive-motion-sensor?cid=ppc.goo.bran....&icid=mname%3Amega-menu.iname%3Ahive-motion-sensor

Node Info
![node_info](https://user-images.githubusercontent.com/19465180/77057356-bc7fef80-69cb-11ea-87cc-350ce185398a.jpg)

Occupancy Cluster
![occupancy](https://user-images.githubusercontent.com/19465180/77057362-bdb11c80-69cb-11ea-92ca-d976dd419419.jpg)

Power Config Cluster
![power](https://user-images.githubusercontent.com/19465180/77057364-bee24980-69cb-11ea-89f1-dc748da28c83.jpg)

Temperature Cluster
![temperature](https://user-images.githubusercontent.com/19465180/77057372-c144a380-69cb-11ea-902a-a84b7bdbd16e.jpg)

Basic Cluster
![basic](https://user-images.githubusercontent.com/19465180/77057375-c1dd3a00-69cb-11ea-9e0d-d372b4be7c26.jpg)

Illuminance Cluster
![illuminance](https://user-images.githubusercontent.com/19465180/77057382-c30e6700-69cb-11ea-8d3d-1eeddb1dd731.jpg)

**Comment by SwoopX** [comment]
I'll put it on my list.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by eddiehowrya** [comment]
Sensors are working well with the new version, thank you.

**Comment by lwsrbrts** [comment]
> 
> 
> Sensors are working well with the new version, thank you.

@eddiehowrya - apologies for responding on a closed issue. I wondered if you had done anything specific with your Hive sensors after pairing them? I have a sensor that seems to be self-activating - I only have the one Hive motion sensor so don't know if this affects others.

It detects motion for one minute which then clears for 4 minutes and then it detects motion again for a minute...so on and so forth.

Screenshot from Home Assistant of it activating itself overnight.
![sensor_self-activate](https://user-images.githubusercontent.com/15855642/107122673-fc282200-6890-11eb-94bb-466a51bbc8a4.png)
