### ISSUE TITLE
Suddenly firmware not connected

### ISSUE THREAD

**Issue by daniel-lo** [dresden-elektronik/deconz-rest-plugin#2614]
My working installation had suddenly died .. not aware of any changes .. what can I do about this?
![phoscon](https://user-images.githubusercontent.com/4311558/77233596-db87a880-6ba8-11ea-98c4-59c8517d9787.png)

**Comment by Smanar** [comment]
Have you another USB port to test ?
What is your OS ?
Can you try this command 
`GCFFlasher_internal -l`

**Comment by daniel-lo** [comment]
It healed itself over night .. I really have no idea what happened.
How doe I ussue that command .. from Ubutu shell?

I wonder why it tells me firmware 2.5.74 is up to date while "Little Walter ⋅ v2.5.75" is listed in the change history?!

**Comment by Smanar** [comment]
2.5.74 is the deconz version, not the firmware.
You can update deconz if you need it.

Yep this command is for use in a shell.
It can say if the system detect the device or not, it's just an informative command.

**Comment by daniel-lo** [comment]
Next I would have rebooted the machine .. but since it has recovered I see no reason.
How do I update DeConz .. I did an ubuntu update/upgrade yesterday but it still shows .74.

**Comment by Smanar** [comment]
Perhaps it's because stable/beta channel ?
You have all files here http://deconz.dresden-elektronik.de/ubuntu/beta/

**Comment by daniel-lo** [comment]
could you point me to update instructions? I should be on stable .. "Little Walter" sounded stable.

**Comment by Smanar** [comment]
For exemple

```
$> wget http://deconz.dresden-elektronik.de/ubuntu/beta/deconz-latest-beta.deb
$> sudo dpkg -i deconz-latest-beta.deb
$> sudo apt update
$> sudo apt install -f
```

**Comment by daniel-lo** [comment]
thanks .. did so with deconz-dev-2.05.75.deb. Process ran well. But I still see
2.05.74 in my phoscon app.

**Comment by Smanar** [comment]
Ha ?
So it's perhaps normal ^^, it's perhaps for that I m seing 74 too, small bug.

**Comment by daniel-lo** [comment]
do .. I simply followed your steps .. then rebooted

**Comment by Smanar** [comment]
ha ok, so not sure the OS can overwrite the files when the app is already running.

**Comment by daniel-lo** [comment]
pls add how to stop deconz

**Comment by Smanar** [comment]
You have headless or GUI version ?

**Comment by daniel-lo** [comment]
thanks .. tried it .. version number doesn't change .. maybe the string was not maintained.

**Comment by Smanar** [comment]
After so many tries, I think yes ^^.

**Comment by SwoopX** [comment]
@daniel-lo If I read correctly, you installed the development package, not deconz.

**Comment by daniel-lo** [comment]
@SwoopX what makes you think that? At least not intentionally .. I simply wanted a straight forward stable installatino (gui version).

**Comment by SwoopX** [comment]
> thanks .. did so with deconz-**dev**-2.05.75.deb.

**Comment by Smanar** [comment]
Lol, ha yep, good eyes ^^

**Comment by daniel-lo** [comment]
I see .. there is a dev and a qt file .. didn't notice that .. just went for the number. Will switch. Thanks

**Comment by daniel-lo** [comment]
Now it shows the correct number. My bad (using the dev build) .. THANKS Y'ALL!
