### ISSUE TITLE
Domoticz | MQTT | deconz

### ISSUE THREAD

**Issue by michi1g** [dresden-elektronik/deconz-rest-plugin#2623]
I don't know whether it's deconz related or MQTT or domoticz  but since I updated domocticz to 2020.1 some of my devices have developed a weird behaviour:
As soon as I trigger any of my zigbee switches, some of my wifi devices (sonoff) get triggered.
I already posted on domoticz forum but no answers yet:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=31828&p=240807

Any suggestions from your side?

**Comment by Smanar** [comment]
Hello.
So you are using zigbee2mqtt with a deconz dongle ? If it's that you are on the wrong github ^^

BTW have you tried to disable your scripts/rules in domoticz ?

I don't think the deconz hardware can act on sonoff hardware directly (else you will have this bug with domoticz offline), so for me you have something in your domoticz gestion.
