### ISSUE TITLE
Osram Smart+ motion sensor does not report temperature

### ISSUE THREAD

**Issue by tosion** [dresden-elektronik/deconz-rest-plugin#2628]
Hi there,
I have couple similar Home Assistant systems on Raspberry 3B+ where I use Deconz addon and Deconz RaspBee shields. They have been very reliable and I am very pleased with them. I have nodes between 40-70 connected to each system. I have had 4 Osram Smart+ Motion sensors and I added one more. I like them and I also use the temperature measurement adjusted with HA.

This last one just does not report the temperature. I removed it and rejoined again and same result. In Phoscon it shows 0 C (should be around 20) and in HA it reports unknown. In VNC it looks for me just as the others. (I am not an expert here). Can anyone please help me out to figure out is this just broken or is there something I can check deeper?

![image](https://user-images.githubusercontent.com/48414735/77844465-d382c680-71af-11ea-9633-155fb6181107.png)
![image](https://user-images.githubusercontent.com/48414735/77844474-e5646980-71af-11ea-88bd-c065d414dcf7.png)
![image](https://user-images.githubusercontent.com/48414735/77844484-f44b1c00-71af-11ea-8b40-468f2e52abe4.png)

**Comment by SwoopX** [comment]
Based on your screenshot, the modelID may have changed. Can you please double check if the "older" sensors are "Motion Sensor-A"? You should do this in deconz GUI and have the basic cluster attributes read before.

**Comment by tosion** [comment]
Thanks for a quick response!
OK - I am not sure is this what you want but new one on the top and old below - both looks same to me?

![image](https://user-images.githubusercontent.com/48414735/77854764-d94ecb00-71f4-11ea-9ed8-a6b5a8eac05e.png)

![image](https://user-images.githubusercontent.com/48414735/77854742-b6241b80-71f4-11ea-96b9-66eb1cf0b493.png)

**Comment by SwoopX** [comment]
Alright, thanks. Just wanted to make sure there's no change. The Phoscon screenshot is missing the "-A" from the model identifier.

You could try a couple of options. Deconz may misss a sensor every now and then:
- If not already done, delete the device in Phoscon and join it again.
- Start sensor search again and hold the sensor in your hands, so it gets warmer. It may trigger the device to send temperature data
- Start sensor search again in Phoscon and the read the basic and/or temperature attributes in deconz GUI

**Comment by tosion** [comment]
OK - thanks again!

Basically I have done those steps you suggested with no luck. Temperature attribute shows also 0 in Deconz GUI. Right now there in not too much I can do anymore? The sensor is located in my summer cabin and unfortunately because this corona we are not allowed to travel there from my home until it gets better ( I just yesterday came back from the cabin but I am not allowed to go back again ....). Remotely I can use Phoscon and Deconz GUI and delete it but rejoin is not possible remotely. 

So the sensor is perhaps broken?

**Comment by SwoopX** [comment]
> So the sensor is perhaps broken?

Hard to say without physical access. Those sensors are sleeping most of the time and need to be woken up to get any data. While having access, you can force the device to wake up in some ways (e.g. clicking some physical buttons, warm it up, etc.). So, if you don't get any temperature readings via deconz GUI, the device is either sleeping or maybe not correctly paired. I that sense, I'm also not too sure any more whether information presented in your screenshots is actually correct. I'd have expected to see at least some fields greyed out...

**Comment by tosion** [comment]
![image](https://user-images.githubusercontent.com/48414735/77879477-2ff2ee00-7263-11ea-900f-7bbfcc91d103.png)

Excellent - You are a Hero!

After reading again your writing I understood that I can do the cluster check same time when adding a new sensor in Phoscon side. That did the trick! (My bad I did not read your text carefully first time).

Just to make sure the sensor worked correctly as motion sensor at very beginning ...

So now I have a working sensor  - both motion and temperature. Thanks!

**Comment by SwoopX** [comment]
> Excellent - You are a Hero!

Finally someone recognizes it 😛 Just kidding. Glad you made it.

> My bad I did not read your text carefully first time

Happens to me way too often as well.

Would you mind closing the issue then? Hf and take care!
