### ISSUE TITLE
[Device Support Request] CentraLite 3320-L

### ISSUE THREAD

**Issue by soydeboca** [dresden-elektronik/deconz-rest-plugin#2632]
I'm trying to integrate this contact sensors from Iris that I was using flawlessly in SmartThings into Home Assistant. I'm running deconz v2.05.75 as an add-on on a Raspberry Pi 4. If there is another screenshot needed, please tell me. Thanks in advance

![2020 03 30_20 37 35 - HA__deCONZ_RPI4_(Home_Assistant_-_deCONZ)_-_VNC_V](https://user-images.githubusercontent.com/27639753/77972163-04095400-72c7-11ea-98dc-0a58a67dd0aa.png)
![2020 03 30_20 36 48 - HA__deCONZ_RPI4_(Home_Assistant_-_deCONZ)_-_VNC_V](https://user-images.githubusercontent.com/27639753/77972165-053a8100-72c7-11ea-942a-aff2442b6575.png)
![2020 03 30_20 36 30 - HA__deCONZ_RPI4_(Home_Assistant_-_deCONZ)_-_VNC_V](https://user-images.githubusercontent.com/27639753/77972168-07044480-72c7-11ea-864d-9c9fcaee22a4.png)

**Comment by SwoopX** [comment]
Thanks. You could read the power configuration attributes and provide a corresponsing screenshot. Just want to make sure here that I get whatever battery readings from the device right.

**Comment by soydeboca** [comment]
Done! Thanks SwoopX!

![2020 03 31_15 48 51 - HA__deCONZ_RPI4_(Home_Assistant_-_deCONZ)_-_VNC_V](https://user-images.githubusercontent.com/27639753/78063912-4e421200-7367-11ea-844f-68ce884f7de9.png)

**Comment by SwoopX** [comment]
Thanks, done.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
