### ISSUE TITLE
[Device Support Request] Tuya Gas Detector

### ISSUE THREAD

**Issue by timbru31** [dresden-elektronik/deconz-rest-plugin#2633]
I've bought a new Zigbee device: The Tuya (combustible) gas detector (model TS0204) - sadly, it's not yet supported.
See attached Node and Cluster info below:

![tuya2](https://user-images.githubusercontent.com/838003/78023599-753c1c00-7346-11ea-8bca-9c9a025ad157.jpg)
![tuya3](https://user-images.githubusercontent.com/838003/78023600-75d4b280-7346-11ea-824f-b275d7051ad6.jpg)
![tuya1](https://user-images.githubusercontent.com/838003/78023602-766d4900-7346-11ea-90a4-1a32fd9e582d.jpg)

---

Hardware image:
![TS0204](https://user-images.githubusercontent.com/838003/78023694-a1579d00-7346-11ea-9af7-0b63784b467c.jpg)

---

PS: Deconz GUI says it's a CO sensor, it seems the translation of the attribute `e16ZoneType` (i.e., E_CLD_IASZONE_TYPE_GAS_SENSOR (0x002B)) is wrong, since it _can_ but is not always a CO sensor.

**Comment by SwoopX** [comment]
Can you also please provide a screenshot with the available clusters? Thanks.

**Comment by timbru31** [comment]
Sure:
![tuya4](https://user-images.githubusercontent.com/838003/78028357-6c4f4880-734e-11ea-82bf-7662a7954e44.jpg)


I'll work on a PR, too. Hopefully it's just adjusting the bindings to whitelist the model id.

**Comment by SwoopX** [comment]
Nope, it isn't ;)

**Comment by timbru31** [comment]
What should be missing then? Basically it's yet another gas sensor, the clusters aren't very special (as expected)

**Comment by ebaauw** [comment]
> Deconz GUI says it's a CO sensor, it seems the translation of the attribute e16ZoneType (i.e., E_CLD_IASZONE_TYPE_GAS_SENSOR (0x002B)) is wrong, since it can but is not always a CO sensor.

It advertises incorrectly as a CO sensor.  Make sure to expose it as ZHAFire instead of ZHACarbonMonoxide, see #2515.

**Comment by SwoopX** [comment]
Ah, wait. Seems that I mixed it up as it doen't have the IAS WD cluster...

Don't even think any binding is required here. Probably just add them on top of de_web_plugin.cpp as the other devices and the changes mentioned by @ebaauw somewhere around line 3989.

**Comment by timbru31** [comment]
> > Deconz GUI says it's a CO sensor, it seems the translation of the attribute e16ZoneType (i.e., E_CLD_IASZONE_TYPE_GAS_SENSOR (0x002B)) is wrong, since it can but is not always a CO sensor.
> 
> It advertises incorrectly as a CO sensor. Make sure to expose it as ZHAFire instead of ZHACarbonMonoxide, see #2515.

There are no dumb question: why should I force the sensor to be a fire sensor when the current zone is correct spec wise?

**Comment by ebaauw** [comment]
What spec?  See #2634.

**Comment by timbru31** [comment]
> Ah, wait. Seems that I mixed it up as it doen't have the IAS WD cluster...
> 
> Don't even think any binding is required here. Probably just add them on top of de_web_plugin.cpp as the other devices and the changes mentioned by @ebaauw somewhere around line 3989.

Hmm, interestingly this doesn't seem to do the trick:
```cpp
diff --git a/de_web_plugin.cpp b/de_web_plugin.cpp
index 39b2a58..6836ee4 100644
--- a/de_web_plugin.cpp
+++ b/de_web_plugin.cpp
@@ -274,6 +274,7 @@ static const SupportedDevice supportedDevices[] = {
     { VENDOR_HANGZHOU_IMAGIC, "1117-S", energyMiMacPrefix }, // iris motion sensor v3
     { VENDOR_JENNIC, "113D", jennicMacPrefix }, // iHorn (Huawei) temperature and humidity sensor
     { VENDOR_SERCOMM, "SZ-ESW01", emberMacPrefix }, // Sercomm / Telstra smart plug
+    { VENDOR_NONE, "TS0204", silabs3MacPrefix }, // Tuya gas sensor
     { 0, nullptr, 0 }
 };

@@ -3976,7 +3977,8 @@ void DeRestPluginPrivate::addSensorNode(const deCONZ::Node *node, const deCONZ::
                              modelId.startsWith(QLatin1String("SMSZB-120")) ||        // Develco smoke detector
                              modelId.startsWith(QLatin1String("HESZB-120")) ||        // Develco heat detector
                              modelId.startsWith(QLatin1String("SF2")) ||              // ORVIBO (Heiman) smoke sensor
-                             modelId.startsWith(QLatin1String("lumi.sensor_smoke")))  // Xiaomi Mi smoke sensor
+                             modelId.startsWith(QLatin1String("lumi.sensor_smoke")) || // Xiaomi Mi smoke sensor
+                             modelId.startsWith(QLatin1String("TS0204")))  // Tuya gas sensor
                     {
                         // Gas sensor detects combustable gas, so fire is more appropriate than CO.
                         fpFireSensor.inClusters.push_back(ci->id());
```

Any ideas? Re-paring the sensor doesn't even yield the green success message in Phoscon. Debug logs show a successful network join of the device though.

**Comment by SwoopX** [comment]
Try reading the basic cluster while sensor search is active.

**Comment by timbru31** [comment]
Nice, that did the trick!

**Comment by SwoopX** [comment]
👍

**Comment by SwoopX** [comment]
@timbru31 Did the sensot enroll automatically?

**Comment by timbru31** [comment]
To the IAS Zone? I'm not sure anymore, but I think that I've manually set the value.

**Comment by SwoopX** [comment]
@timbru31 Thanks for your feedback, that would be my expectation. I'm currently after integrating another mains powered IAS zone device and it does not enroll automatically, simply because the code seems not be able to handle that (yet).

If you maybe got some time over the weekend, I'd appreciate if you could double check that with a sensor reset.

**Comment by timbru31** [comment]
After a reset it's not enrolled automatically.

**Comment by SwoopX** [comment]
Thanks a lot. I was hoping not to be alone with this, it might be a rare phenomenon though. I made some tests with corresponding code changes and managed to have it enrolled automatically now.
