### ISSUE TITLE
Alert sent as string 'none'  instead of None

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#264]
It seems as if the alert attribute is sent as 'none' as a string instead of None.

/R

**Comment by ebaauw** [comment]
A light `state.alert` or a sensor `config.alert`attribute takes a string value, so `”none”`.  The literal `none` is not valid json, nor is leaving out the value, see http://json.org.

**Comment by Kane610** [comment]
I see, so it is the literal state then? Well, less whine and I might have got that... Thanks for the quick answer.
