### ISSUE TITLE
[Device Support Request] Shyne Smart Filament LED

### ISSUE THREAD

**Issue by hagenuck1** [dresden-elektronik/deconz-rest-plugin#2642]
Hi there, 
Would be great to have the Shyne Filament LEDs from click-Licht supported und Deconz. 
They’re working fine for me, but aren’t listed in supported devices till now.

![41E9C612-4B23-4E83-B95F-D23B35A4AC93](https://user-images.githubusercontent.com/15811973/78153088-fe347f80-743a-11ea-9afa-f1c352560251.png)
![BAABCAD6-5088-44DA-A346-EC6B34EBFE7E](https://user-images.githubusercontent.com/15811973/78153095-012f7000-743b-11ea-8364-87f74a1ad438.jpeg)
![3327A672-F7F0-462E-8F5B-36360D4FBEEB](https://user-images.githubusercontent.com/15811973/78153099-01c80680-743b-11ea-8429-cfbf25485563.png)

Hope this is enough info. 
Turn on/ off, dimming and changing color temperature is working fine. 

I‘m using the Edison styled one.

**Comment by SwoopX** [comment]
Well, if it works without any issues, there's probably nothing left to do for us here.

**Comment by hagenuck1** [comment]
Thanks, then it should be listed as compatible at least for other users.

**Comment by SwoopX** [comment]
Feel free to add them ;)
