### ISSUE TITLE
Conbee changed name to Unkown 17 and I lost control of all devices temporarily 

### ISSUE THREAD

**Issue by kses** [dresden-elektronik/deconz-rest-plugin#2644]
Hi!

The Conbee stick changed it name and shows up as a light with name unknown 17 and I can not control anything or get any sensor input. Conbee 1 running in a docker.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/17168512/78282010-e680f800-751b-11ea-8290-7db57a681757.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/17168512/78282054-f6004100-751b-11ea-95fb-cf7ae6f2db40.png">

For a while I got this error every where:
error APSDE-DATA.confirm: 0xE1 on task

But know it started working after a few restarts... Happened yesterday evening as well.

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log: radio interference.

**Comment by kses** [comment]
> See https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log: radio interference.

Thank you! That is interesting... Do the channels are the same as for wlan? Will see if I can check the radio with my unifi AP


What about the unknown 17 lamp issue (Conbee USB drive)

**Comment by ebaauw** [comment]
Interference is most likely caused by USB3.

ConBee should be listed as a Configuration Tool.  See #2534.

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
