### ISSUE TITLE
[Device Support Request] NYCE NCZ-3014 Garage Door Tilt Sensor

### ISSUE THREAD

**Issue by mccracken** [dresden-elektronik/deconz-rest-plugin#2646]
NYCE NCZ-3014 Garage Door Tilt Sensor

![Annotation 2020-04-02 142730](https://user-images.githubusercontent.com/61435/78510576-7d2e0d00-77d9-11ea-9b39-977c10e525d3.png)

![Annotation 2020-04-02 151455](https://user-images.githubusercontent.com/61435/78313091-14f0e880-7599-11ea-9a1b-abc646904209.png)

![image](https://user-images.githubusercontent.com/61435/78512450-e7e64500-77e7-11ea-88a0-99575a11d230.png)

**Comment by mccracken** [comment]
![image](https://user-images.githubusercontent.com/61435/78512440-ca18e000-77e7-11ea-80fa-69f788ca4461.png)

**Comment by mccracken** [comment]
> Can you please provide further screenshots as described in the wiki for requesting device support? Thanks!

Fixed now - thanks.

**Comment by SwoopX** [comment]
The device should already be supported.

**Comment by mccracken** [comment]
Doesn't seem to want to work. Any thing else I can try to test it out?

**Comment by SwoopX** [comment]
What makes you believe it didn't work out. From the screenshot you posted earlier, I can see that pairing went alright and the simple descriptors have been read. Please don't tell me it's just because you cannot see it in Phoscon. You must check the REST API to be sure and verify sensor creation.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
