### ISSUE TITLE
Xiaomi mijia door/window sensor

### ISSUE THREAD

**Issue by Kristian8606** [dresden-elektronik/deconz-rest-plugin#2647]
The door sensor of Xiaomi mijia often does not respond and sometimes even disappears from deconz gui

**Comment by Sjonnie2018** [comment]
Have you checked the device close(r) to your ZigBee receiver? Is the battery level of the sensor OK?

**Comment by Kristian8606** [comment]
The battery is good 95%.  i didn't bring the sensor close to conbee because it is currently working and the problem arises when the door is open and i have to restart deconz then it does not respond until i remove it and add it again

**Comment by Kristian8606** [comment]
In fact, the problem with the sensor manifests itself at all times.  Today for no reason he is not responding again

**Comment by Mimiix** [comment]
@Kristian8606 is this still a issue?

**Comment by Kristian8606** [comment]
Yes last night I restart my raspberry pi and the sensor stopped responding.  12 hours later, he began counting the opening and closing of the door again.
