### ISSUE TITLE
Klik Aan Klik Uit ZTHS-100 zigbee pairing problem

### ISSUE THREAD

**Issue by martinvanbuuren** [dresden-elektronik/deconz-rest-plugin#2657]
Hey all,

I'd like to switch completely over to home assistant for my home automation. One of the products I'm currently using to control my ventilation is the Klik Aan Klik Uit (SEO: KAKU Trust) ZTHS-100 Temperatuur- en Luchtvochtigheidsensor (Eng: Temperature and Humidity sensor). At the current date, this product is not listed as a supported on deCONZ. That is why I was looking to gather information for a Device Support Request.

Unfortunally, I'm stuck. The Phoscon Windows 10 app can not find/pair the sensor ("Failed to connect" after 3 minutes) even though the sensor is in learning mode (Manual: "verbindingsmodus"), and hence, I cannot see it in deCONZ (although it seems to see a device with a battery, which I don't understand). I know the sensor is not broken because it connects perfectly with the Klik Aan Klik Uit control station ICS-2000. And on the other hand, other products I purchased from their Zigbee line do work perfectly with the ConBee ii, such as the ZPIR-8000 motion detector and some Zigbee smart lights. Therefor I conclude that the ConBee ii (and most likely the software) is not broken. 

So lately I've spend a couple of hours thinking of a reason and trying to find a solution, so far without any luck. Any insight is very appreciated.

Thanks!

Hartelijke groet,

~Martin
edit: grammar

**Comment by SwoopX** [comment]
The device is currently not supported so you need to raise a corresponding request. Please refer to the wiki for further details. Thanks.

**Comment by martinvanbuuren** [comment]
Thanks for the respons. That is what I’m trying to explain: it cannot bind so I cannot file a request.

**Comment by SwoopX** [comment]
If Phoscon does tell you "Failed to connect" does not necessarily mean that the pairing has not completed successfully. It basically tells you either that or that no sensors have been created. Therefore, check the deconz GUI for the device in question.

**Comment by ebaauw** [comment]
It looks like an OEMed Heiman.  It should be able to join the network created by deCONZ.  Are you sure you factory-reset the device correctly?  How many routers and end-devices does your network currently have?

**Comment by martinvanbuuren** [comment]
Thanks guys, that's it. I expected that initial pairing must be done though Phoscon (with an message telling that the device is not supported) and deCONZ was just to read the details out. The device it saw with the battery, as mentioned in the first post, was indeed the ZTHS-100. For future reference to others: you should click the right of the two gray buttons to access the details.

I'll make an overview of the sensor's Device Support Request. Thanks again!

PS. FYI as a side note: The motion sensor Klik Aan Klik Uit ZPIR-8000 shows up in deCONZ as an Adurolight:
- NWK: 0x0770
- Name: VMS_ADUROLIGHT
- Model: VMS_ADUROLIGHT
- Vendor: Trust International B.V.
- Version: v0.1.5
However, it is recognized as a motion sensor in Phoscon and it signals correctly, so I think only the naming feels off. Feel free to ask me for additional screenshots or information if you seems fit.

**Comment by SwoopX** [comment]
Seems like this one is supported already. Apparently, there was a hickup on your first join attempt.

**Comment by martinvanbuuren** [comment]
Let's keep it on a hickup. :-) The most relevant screenshots are displayed below, see the attached zip below for a full overview.
<img width="203" alt="ZTHS-100_00_Overview" src="https://user-images.githubusercontent.com/62382424/78549640-fee66080-7802-11ea-8625-86b2b4493af7.png">
<img width="310" alt="ZTHS-100_01_NodeInfo" src="https://user-images.githubusercontent.com/62382424/78549641-fee66080-7802-11ea-960a-c7e233b4d2d0.png">
<img width="532" alt="ZTHS-100_02_Temp_BasicCluster_Part_1_of_2" src="https://user-images.githubusercontent.com/62382424/78549642-ff7ef700-7802-11ea-858d-afcf85968156.png">
<img width="528" alt="ZTHS-100_03_Temp_BasicCluster_Part_2_of_2" src="https://user-images.githubusercontent.com/62382424/78549645-ff7ef700-7802-11ea-84b5-cea19aa94a01.png">
<img width="535" alt="ZTHS-100_04_Temp_PowerConfigurationCluster" src="https://user-images.githubusercontent.com/62382424/78549646-00178d80-7803-11ea-9363-c0000e149928.png">
<img width="307" alt="ZTHS-100_07_Temp_TemperatureMeasurementCluster" src="https://user-images.githubusercontent.com/62382424/78549648-00178d80-7803-11ea-9004-319f4f8aa779.png">
<img width="437" alt="ZTHS-100_11_Humid_BasicCluster_Part_1_of_2" src="https://user-images.githubusercontent.com/62382424/78549649-00178d80-7803-11ea-8692-27797aac132f.png">
<img width="421" alt="ZTHS-100_12_Humid_BasicCluster_Part_2_of_2" src="https://user-images.githubusercontent.com/62382424/78549636-fe4dca00-7802-11ea-9079-1c9e4e2d25f0.png">
<img width="333" alt="ZTHS-100_15_Humid_RelativeHumidityMeasurementCluster" src="https://user-images.githubusercontent.com/62382424/78549638-fee66080-7802-11ea-8f17-12a5fccf5a8a.png">


All 16 screenshots are contained in the ZIP-file hereafter. Please notice that the orders of the files correspond with the clusters in the overview, when sorted on file name.
[ZTHS-100_deCONZ_All_Screenshots.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4437725/ZTHS-100_deCONZ_All_Screenshots.zip)

**Comment by SwoopX** [comment]
Thanks. Should be enough to do the magic.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
