### ISSUE TITLE
deConz 2.05.75 - Ikea Tradfri Remote - Volume Up/Down Problem

### ISSUE THREAD

**Issue by bierlos** [dresden-elektronik/deconz-rest-plugin#2660]
hello
I recently updated my docker image from 2.05.72 to 2.05.75.
now the volume buttons don't work correct.
I use it from apple home kit via homebridge.
i have not changed anything in homekit or homebridge.
long press on volume buttons don't execute a "long press" action, but a "multiple short press" will be released. is it a problem by this deconz docker image? or by deconz firmware? or by deconz software?

**Comment by Wildbill-Z** [comment]
Have a look [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2618)

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
