### ISSUE TITLE
Firmware shows latest even though there are newer

### ISSUE THREAD

**Issue by mat1990dj** [dresden-elektronik/deconz-rest-plugin#2664]
I've searched to see if this issue is already reported by didn't find anything.

My phoscon is showing the following:
![image](https://user-images.githubusercontent.com/5220059/78654477-d6269f80-78c4-11ea-87d8-17e786fbf1b0.png)

Even though I've seen that there is a new firmware on http://deconz.dresden-elektronik.de/deconz-firmware/?C=M;O=D

Is it working as expected?

**Comment by SwoopX** [comment]
If I'm not mistaken, the newer firmwares are to be considered beta versions (at least for Conbee II). Not sure how the update check works and if it is based on any functionality from the deconz REST plugin, which can be checked.

Btw, Phoscon is closed source, before you ask.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
