### ISSUE TITLE
Vimar New Radiofrequency line that support both Zigbee and BT 5

### ISSUE THREAD

**Issue by cafedo** [dresden-elektronik/deconz-rest-plugin#2665]
Hi everyone,
do you know if the the new Vimar Radiofrequency line based both on Zigbee and BT 5 ( https://www.vimar.com/en/int/your-wiring-system-becomes-connected-15482132.html) is supported?

In particular I would like to know if these devices can be managed by deconz:
- switch: https://www.vimar.com/en/int/catalog/product/index/code/14592.0
- connected actuator for power: https://www.vimar.com/en/int/catalog/product/index/code/14593

Thanks in advance.

**Comment by SwoopX** [comment]
In theory, yes. We can probably include support but as far as I can tell, they don't provide a detailed technical reference on the used clusters and enpoints (at least not publicly or I've overlooked it). You may want to reach out to their support and ask for it.

In case we don't have that documentation, somebody must buy it, issue a new device support request and stay with it for testing, which eventually can be rather technical. Even better would be to also have the corresponding gateway and sniff the traffic.

**Comment by cafedo** [comment]
Ok, I’ve bought a switch to test; when it arrives, I’ll post a new device support request including all the info that I can track. Thanks.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
