### ISSUE TITLE
Conbee II USB stick on PI4: can't get API KEY

### ISSUE THREAD

**Issue by vdiogo** [dresden-elektronik/deconz-rest-plugin#2676]
I have a Conbee II USB stick on a PI4 running the deCONZ addon on HASSIO, and I need to get the API KEY so I can connect deCONZ to node-red.

After getting the IP and port using the instructions here https://dresden-elektronik.github.io/deconz-rest-doc/getting_started/, the POST request to get the API KEY is not successful (ends with a _Could not get any response_ error after running for about 1 min).

Any suggestion on what could be the issue?

**Comment by Smanar** [comment]
For me it's not a API key problem.
You are sure for ip and port ? If you use them on a web browser you will obtain the old web app from deconz ?

**Comment by vdiogo** [comment]
> For me it's not a API key problem.
> 
> You are sure for ip and port ? If you use them on a web browser you will obtain the old web app from deconz ?
> 
> 
> 
> Else it will be the same IP than you are using for Phoscon.

Can you elaborate on your comment? What do you mean when you say it’s not an API key problem? And how should I test the IP on a web browser?

**Comment by Smanar** [comment]
If it was API problem, you will have an error message like "not autorised" or a bad answer. Here you have a connexion problem.

Just type in a browser http://IP:PORT then press enter, if you are right you will have the  old webapp, else you are using bad ip or have something blocking in your network.

**Comment by CarpeDiemRo** [comment]
I have the same issue. I'm using Postman on macOS. 

at 
`GET https://dresden-light.appspot.com/discover `

 I receive the 200 OK, but at 

`POST 172.30.33.1:40850/api`
or 
`POST https://172.30.33.1:40850/api`

I'm receiving 

> Could not get any response
There was an error connecting to http://172.30.33.1:40850/api.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

The body content is 
```
{
    "devicetype": "myapplication"
}
```
raw button checked

Any advice or suggestions?

**Comment by mmychu** [comment]
I have the same problem with getting API key
After about 1 minute, there is an error after POST request
![image](https://user-images.githubusercontent.com/25245131/80766149-03bddc00-8b45-11ea-9d7a-1b744d7c962d.png)

**Comment by mmychu** [comment]
Set the correct PORT, restart decozn and try again
![image](https://user-images.githubusercontent.com/25245131/80767738-e428b280-8b48-11ea-8005-cc905bacccfa.png)

**Comment by CarpeDiemRo** [comment]
Thanks for your answer. It Works!

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
