### ISSUE TITLE
Device Support Tuya Smart Plug TS0121

### ISSUE THREAD

**Issue by bilbon0bud** [dresden-elektronik/deconz-rest-plugin#2677]
Hello

here is a smart plug zigbee from tuya, she have a power meter report, but i can't see him in deconz or in home assistant.
This device isn't inside the supported device list, so i give you some elements to integrate it in deconz.

Thanks for Your work.

Best Regards

![capture4](https://user-images.githubusercontent.com/4129173/78994272-ec8c5f80-7b3f-11ea-9e72-a4da2b2607c9.png)
![capture3](https://user-images.githubusercontent.com/4129173/78994276-edbd8c80-7b3f-11ea-9067-acf1c2b0243f.png)
![capture2](https://user-images.githubusercontent.com/4129173/78994278-ee562300-7b3f-11ea-82b4-6b9489d673f5.png)
![Capture1](https://user-images.githubusercontent.com/4129173/78994280-eeeeb980-7b3f-11ea-9c8d-eff22f9fcf36.png)

**Comment by SwoopX** [comment]
I can take care of that. Can you please also provide screenshots from the Electrical Measurement cluster as well (make sure the attributes have been read)? Thanks!

**Comment by bilbon0bud** [comment]
![capture5](https://user-images.githubusercontent.com/4129173/78995426-9967dc00-7b42-11ea-95ed-d90c7657d4f1.png)

do you need more ?

**Comment by bilbon0bud** [comment]
![capture7](https://user-images.githubusercontent.com/4129173/78995545-e2b82b80-7b42-11ea-9090-c1331a93a4fe.png)

**Comment by SwoopX** [comment]
Thanks. Can you please apply a load on the plug and take another screenshot (1st one of the 2)? Since neither multipliers nor divisors are maintained, I need to know the active power to get the units right.

**Comment by bilbon0bud** [comment]
![capture8](https://user-images.githubusercontent.com/4129173/79000209-7e01ce80-7b4c-11ea-968b-7f35bafad5f3.png)

**Comment by bilbon0bud** [comment]
here is the cature with a charge.

**Comment by SwoopX** [comment]
Thanks again. How much power was it? I'd assume 96W?

**Comment by bilbon0bud** [comment]
I ll try tomorrow the same test with a zwave plug from fibaro to give you the answer.

I plug my fruit juicer so 96w seem to be a good response.

Thanks for tour work see you tomorrow

**Comment by SwoopX** [comment]
Cool. And don't forget to also make a screenshot of the basic cluster while the attributes have been read. Pretty sure I already know what's in there, but I wanna be on the safe side.

**Comment by bilbon0bud** [comment]
![capture11](https://user-images.githubusercontent.com/4129173/79041653-ae4f7880-7bf1-11ea-8c92-54aa7f6635ab.png)
![capture10](https://user-images.githubusercontent.com/4129173/79041654-af80a580-7bf1-11ea-9fc8-da8de32eb4d4.png)
![capture9](https://user-images.githubusercontent.com/4129173/79041655-af80a580-7bf1-11ea-8002-34bf32f84c9f.png)

the power you gave me seem to be good.

**Comment by SwoopX** [comment]
Thanks! So in your last screenshot, the values already are as they should without any additional modification. Units are V, mA and W, great.

However, the Current Summation does not seem to fit your last screenshot (from the app). Deconz is saying 61 (presumably Wh) and the app much more. Was the device reset recently?

**Comment by bilbon0bud** [comment]
Hello

The device as been unplugged.
I don’t reset it, but i don’t use it too.

It was just plug for the test.

Best regards

**Comment by Klagio** [comment]
Hi, do you know if its this model?

https://it.aliexpress.com/item/4000688486196.html?spm=a2g0o.productlist.0.0.7cbb1c206TOJki&algo_pvid=c1e518a8-418b-49ce-9255-8879d8eaf6a2&algo_expid=c1e518a8-418b-49ce-9255-8879d8eaf6a2-0&btsid=0ab6f8ad15891440488305543eff36&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by vdbrink** [comment]
@bilbon0bud I received today the same but when I bought it it was advertised as metered but they changed that now to no-metered (they removed that text).
Did you test if it's metered?
It doesn't send metered data over zigbee.

**Comment by bilbon0bud** [comment]
It seem to be metered, i m waiting the next release of deconz to test the
plugs.
the change made by swoopX seem to be merged, now i just have to wait a
little more.

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by mhin76** [comment]
Hi all. I also bought such a plug recently (Model ID TS0121 and Manufacturer Name _TZ3000_rdtixbnu). I see under deCONZ the RMS current and active power incl. values. But I don't see any power nor consumption info under Homebridge - Homebridge Hue plugin. Not sure if maybe there an update is missing. With what REST API call can I try it out directly on deconz to see if that part is correct?
