### ISSUE TITLE
[Device support request] innr SP220 smart plug

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#2678]
![grafik](https://user-images.githubusercontent.com/4005212/79052827-70764280-7c39-11ea-8e56-7b541ec88808.png)

**Basic cluster**
![grafik](https://user-images.githubusercontent.com/4005212/79052872-a0bde100-7c39-11ea-8cdb-ceb4a6a25ecb.png)
![grafik](https://user-images.githubusercontent.com/4005212/79052896-c77c1780-7c39-11ea-9fcf-12479ddf4095.png)

**Level Control**
![grafik](https://user-images.githubusercontent.com/4005212/79052913-eb3f5d80-7c39-11ea-9ff3-6471d3c3ae95.png)

**Power**
![grafik](https://user-images.githubusercontent.com/4005212/79056418-c3aabe00-7c56-11ea-9bd1-570a7e4a5a97.png)

**Comment by SwoopX** [comment]
Manufacturer specific luster **FC82**

```
ZigBee Cluster Library Frame, Mfr: INNR Lighting BV (0x1166), Command: Discover Attributes Response, Seq: 208
    Frame Control Field: Profile-wide (0x1c)
    Manufacturer Code: INNR Lighting BV (0x1166)
    Sequence Number: 208
    Command: Discover Attributes Response (0x0d)
    Attribute Status Record
        Attribute: 0x0006
        Data Type: Character String (0x42)
    Attribute Status Record
        Attribute: 0x0010
        Data Type: 32-Bit Unsigned Integer (0x23)
    Attribute Status Record
        Attribute: 0x0011
        Data Type: 32-Bit Unsigned Integer (0x23)
    Attribute Status Record
        Attribute: 0x0012
        Data Type: 32-Bit Unsigned Integer (0x23)
    Attribute Status Record
        Attribute: 0x0013
        Data Type: 32-Bit Unsigned Integer (0x23)
    Attribute Status Record
        Attribute: 0x0014
        Data Type: 32-Bit Unsigned Integer (0x23)
    Attribute Status Record
        Attribute: 0x0015
        Data Type: 32-Bit Unsigned Integer (0x23)
    Attribute Status Record
        Attribute: 0xfffd
        Data Type: 16-Bit Unsigned Integer (0x21)

```

**Comment by ebaauw** [comment]
So indeed Zigbee 3.0 as expected and no _Simple Metering_ nor _Electrical Measurement_ as expected/feared.  What's the _Image Type_ (in the OTAU panel)?  The 0xFC82 cluster is new.  Do the values change, as load increases?  I do have an unused innr bridge lying around, if you want to sniff how it interacts with the SP 220.  However, last time I checked, it was really unsophisticated.

The device should already be exposed by the REST API plugin (as not-so-smart plug).  Only thing to check is the whitelisting in `bindings.cpp` for the attribute reporting.  Best change `modelId.startsWith(QLatin1String("SP 120"))` to `modelId.startsWith(QLatin1String("SP "))` (only in that file).

BTW how do you do to send the _Discover Attributes_?  deconz-cli-plugin?  What's the byte code?

**Comment by kasteleman** [comment]
The SP 220 does Indeed not support Simple Metering nor Electrical
Measurement as confirmed by INNR itself!

So no need to snif because it only does on/off

Op za 11 apr. 2020 om 22:09 schreef Erik Baauw <notifications@github.com>

**Comment by SwoopX** [comment]
@ebaauw 

> What's the Image Type (in the OTAU panel)?

Image type is 0x0310

> Do the values change, as load increases?

No, none of the values changes a bloody bit, even after 1h of my Sonos plaing stuff. Looks pretty useless.

> BTW how do you do to send the Discover Attributes? deconz-cli-plugin?

Indeed. Pretty handy, at least for mains powered devices.

```
zclattrmanu 0xcaca 1 0xfc82 0x1166 0C00001D
               |   |    |      |    |   | |------- # of attributes to read (1D)
               |   |    |      |    |   |--------- # Attribute to start with (0000)
               |   |    |      |    |------------- Command (Discover Attributes)
               |   |    |      |------------------ Manufacturer code
               |   |    |------------------------- Manufacturer specific cluster
               |   |------------------------------ Endpoint
               |---------------------------------- Device
```

**Comment by ebaauw** [comment]
Holy crap, while documenting the GUI's keyboard shortcuts, I discovered that you can also send this request from the GUI.  Select a cluster, select the node, press `9`.  Updated the "deCONZ for Dummies" Wiki.  It doesn't set the _Manufacturer Code_ though, so useless for clusters with that code.

**Comment by SwoopX** [comment]
Gee, where did you get that from, trying?

**Comment by ebaauw** [comment]
While editing the "deCONZ for Dummies" Wiki, I was double-checking the keys with the sniffer running.  I did try all digit keys, but not all the letters, there could be another hidden gem (I was hoping for a _Read Attributes_ of the _Basic_ cluster).

**Comment by SwoopX** [comment]
Nice one.

**Comment by ualex73** [comment]
No measurements is a "downgrade" from SP120, because I bought the SP120 for that ;-) So I can skip the SP220 completely.

**Comment by kasteleman** [comment]
I mentioned that to INNR also. But the main customers use the HUE bridge for example and then there is no measurement available even with the SP120. Therefore they did not implement it in the SP220 and thereby reduced the costs for the new plug.

**Comment by ualex73** [comment]
I understand the business logic behind it, but they just lost me as a customer for plugs ;-)

**Comment by kasteleman** [comment]
And again, did mention that to them. 1 of the + of the SP120 and reason some people use that plug.
Would have been a nice upgrade because of ZigBee 3.0 and attribute reporting…...

**Comment by SwoopX** [comment]
Indeed. From my perspective, power measurement was more a unique selling proposition. Since it's not in anymore, I'm out. Really enjoyed the SP 120.

The SP 220 are more expensive btw ;)

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!

**Comment by P1Rebo** [comment]
Unfortunately I can't pair with my Conbee I stick plugged in... Any suggestions? My SP 120 could be connected without any problems... thanks in advance!

**Comment by jee67** [comment]
Anyone, is the Sp220 accessable  in the Phoscon app, and if so how should I do this?

**Comment by lryjnks** [comment]
> Anyone, is the Sp220 accessable in the Phoscon app, and if so how should I do this?

Same question here..

**Comment by lryjnks** [comment]
Ok, strangely enough I now see the innr in the menu Lights. But in the search it had not found anything.

![image](https://user-images.githubusercontent.com/33368776/189474828-521f2259-5c05-42e6-970b-5a98615b1c43.png)
