### ISSUE TITLE
Xiaomi Aquara dont connect after channel change

### ISSUE THREAD

**Issue by yabbah** [dresden-elektronik/deconz-rest-plugin#2682]
I noticed that if I change used channel in deconz, my Aquara units dont re-connect after that. To get them in the network again I have to press the button on each device then it works again. Anyone more have this issue and is there a fix?

Just notice that this just affect the temperature-sensors (square ones) and the open/close sensor. The Mi Cube seems to reconnect fine tho.

**Comment by pergolafabio** [comment]
yeah, notice the same, if i change channel, i need to pair them again
i think its normal, so dont care
i have  a good channel now

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
