### ISSUE TITLE
Conbee II Stick not found after a some time

### ISSUE THREAD

**Issue by kmplngj** [dresden-elektronik/deconz-rest-plugin#2683]
Hello,

since one of the last Deconz updates my Conbee II does not show a fireware version after some hours after a reboot and stops working.

I did not change anything on the hardware site. Before the system was running months without problems.

Any idea where I could look to find the problem?

Thanks
Jan

**Comment by kmplngj** [comment]
[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4539668/deconz.log)

I added my log file. It show the process between same restarts. 

Any one have an idea?

Thanks a lot
Jan

**Comment by Smanar** [comment]
Hello, how are you powering the device ?
Have you tried the USB extension cable ?

You device don't alternate connexion / deconnexion ? like https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2493

**Comment by kmplngj** [comment]
I run it on my ESXi host.
I have an USB extension cable. 

The setup was running for months. Since I did an update of the docker image I have the problems.

I think I have to check my logs to find if I have the same problem as #2419

**Comment by Smanar** [comment]
I know lot of user with the issue #2419, for most of them to reconize the defaut
- Pluged on a Windows machine they hear the "USB sound" endlessly
- The firmware version appear/disapear endlessly

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!

**Comment by kmplngj** [comment]
@Mimiix no not solved ):
