### ISSUE TITLE
deCONZ for Dummies

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#2684]
I (finally) created a [deCONZ for Dummies](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-for-Dummies) page on the Wiki from my notes that I collected over the years.

I hope to be referring to the Wiki more often, instead of giving the same answers over and over again in issue comments (where they never can be found later on).
Please let me know here if this helps and how we can improve on it.

Please feel free to edit and improve - it's a Wiki, after all.

**Comment by Sjonnie2018** [comment]
Reading the Wiki provided me with new insights regarding the difference between deconz and deconz-gui. So thank you for that!
