### ISSUE TITLE
HEEEEELP!  houstan we have a "open" issue problem here. Please close issues.

### ISSUE THREAD

**Issue by scobby** [dresden-elektronik/deconz-rest-plugin#2685]
Hello Community!
Please help and close some of the issues, so we get things cleaned up for better overview!
If an issue is solved or not an issue anymore, just close it. If its still open, ask the author if this problem is still there.

Any other suggestions how to get the messy issues away?

**Comment by Sjonnie2018** [comment]
Agree! I have closed my issues as soon as they were resolved. Seems like the issues not closed are related to "hit-and-run" users. Maybe introduce a bot that marks issues closed after 10 days?

**Comment by Hypfer** [comment]
The bot already exists and is closing issues. Even the ones which are still relevant so that's definitely not the best solution.

Honestly this meta-issue is just making it worse.

**Comment by wvuyk** [comment]
So better close this one...
