### ISSUE TITLE
[Device support request] Heiman remote control HS1RC-M

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#2697]
![grafik](https://user-images.githubusercontent.com/4005212/79493261-857c1880-8021-11ea-9a9f-05ef4c033483.png)

**Power cluster**
![grafik](https://user-images.githubusercontent.com/4005212/79493538-e86daf80-8021-11ea-902c-0d77a45e333e.png)

For the remote to properly join, the coordinator has to be extended by "IAS ACE" cluster manually in deconz GUI. For that, go to _Edit -> Network settings -> Endpoints_ (or press F9 -> Endpoints) and add `0x0501` to the `in clusters` of endpoint 0x01.

![grafik](https://user-images.githubusercontent.com/4005212/79495160-75196d00-8024-11ea-949f-bab4e782d76d.png)

After successful join, the device sends IAS ACE commands on all its buttons as below:

**Top button**: Arm Mode - Arm Day/Home Zones Only
**Right button**: Arm Mode - Disarm
**Bottom button**: Command - Emergency
**Left button**: Arm Mode: Arm All -Zones

**Update:**
I'ce modified the device to be exposed as a switch via REST API, so it now issues 4 "normal" button events. Presumably not really usable with Phoscon, but with other home automation software picking up the websocket messages.

**Comment by accelle17** [comment]
Hi @SwoopX, do you have a confirmation from the web app that you were able to add the remote? I followed your instruction by adding 0x0501 but can only see the device on the VNC/phoscon. Not able to see any new device or events but can see it appears on the logs

**Comment by SwoopX** [comment]
Yeah, you get a confirmation, at least I got one. However, that remote is pretty much unusuable. It uses IAS ACE commands which deconz has no logic for. And that's unfortunately nothing to be added like in 5 mins. Thinking about bending to towards a regular remote, if that's feasible.

**Comment by SwoopX** [comment]
I've made an update so it can be used as a regular remote to the extend feasible. It should be available as a switch and allows 4 short press button events.

**Comment by accelle17** [comment]
great, thanks. I'll test it as soon as it releases and appears on hass add-on since I don't have any dev environment for it.

**Comment by joschaschultze** [comment]
I've added the new endpoint and can see the device in deconz-gui but there is no home automation software which shows the remote. I've tried domoticz and iobroker.

**Comment by SwoopX** [comment]
Closing this as PR has been merged. Supported with .78

**Comment by rweise** [comment]
Also here, why it is closed? i can see the remote in Deconz-gui as conected  but not in Phoscon and not in the iobroker
