### ISSUE TITLE
IKEA color bulb have wrong color

### ISSUE THREAD

**Issue by freekode** [dresden-elektronik/deconz-rest-plugin#2699]
Hi, I moved from Tradfri hub to conbee + deCONZ and paired my two bulbs.
All it controller via home-assistant.
Now when I set some color for bulb I see that bulb actually has slightly different color than I choose.
Warm orange now is more red and white is more yellow.

So, how it can be fixed? 

just found this warning in logs, about incorrect sRGB profile:
```
Apr 09 18:19:02 raspberrypi systemd[1]: Started deCONZ: ZigBee gateway -- REST API.
Apr 09 18:19:02 raspberrypi deCONZ[12239]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pi'
Apr 09 18:19:02 raspberrypi deCONZ[12239]: libpng warning: iCCP: known incorrect sRGB profile
Apr 09 18:19:02 raspberrypi deCONZ[12239]: This plugin does not support propagateSizeHints()
```

**Comment by SwoopX** [comment]
Sounds familiar https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2304#issuecomment-573443753

**Comment by freekode** [comment]
Yeah, sounds the same.
Tried locally resolve merge conflicts and apply #2402, no luck, too many changes on master 😞

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
