### ISSUE TITLE
Disconnected devices - better visability

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#2708]
Hi @manup,

Just a thought, when a device is disconnected it show up as just a bit "grayed" out in DeConz app.
Would it be possible to get this a bit more visible? 
Example, connected devices has green "header" and disconnected has a red "header"?

Similar to the where the device has the color yellow on screenshot?

<img width="175" alt="Screenshot 2020-04-22 at 11 33 41" src="https://user-images.githubusercontent.com/45151934/79966326-94cdec80-848d-11ea-9d12-d711a3b3ed24.png">

**Comment by PrimaryInc** [comment]
No Comments?

**Comment by PrimaryInc** [comment]
Okay, so guess it was a bad idea :)

**Comment by Smanar** [comment]
lol.
No, you are right for me, but I think they have more important in the "TODO list'

**Comment by PrimaryInc** [comment]
I guess that it would take @manup approx 10min to change it. But as you say, probably not a priority :)
