### ISSUE TITLE
deconz completely crashed

### ISSUE THREAD

**Issue by cosmo84** [dresden-elektronik/deconz-rest-plugin#2711]
Hi all,

I bought a new RPi 4b and installed OS ( raspbian buster) and deconz from scratch. Then I imported the backup from my previous Pi, all lights and sensors are in the GUI, but greyed out and nothing works. In the deconz GUI all routers are blinking red on the left side. 
I use latest software and firmware with a raspbee module (I moved this from the old to the new Pi).

Any idea is welcome.

Thanks,

Stephan

**Comment by ebaauw** [comment]
Are you using a ConBee?  Make sure it's connected to a USB2 port, preferably through a USB extension cable.  Don't connect anything to the USB3 ports.

**Comment by cosmo84** [comment]
No, it‘s a raspbee module

**Comment by ebaauw** [comment]
Did you set the serial port config?

**Comment by cosmo84** [comment]
Yes, I followed exactly the online manual.

**Comment by SwoopX** [comment]
Did you install with desktop? are you using docker?

**Comment by cosmo84** [comment]
Desktop: yes, Docker:No

Thanks!!!

**Comment by cosmo84** [comment]
Okay, I did another fresh install, same procedure, and now It‘s working again, but only after resetting all lights. I don‘t understand it, but it‘s working again. 

Thanks to all!!!

**Comment by SwoopX** [comment]
Have you tried to restore configuration via that special page in Phoscon? Check the wiki for guidance.
