### ISSUE TITLE
Hue Motion keeps losing connection and shows red blinking led

### ISSUE THREAD

**Issue by saberone** [dresden-elektronik/deconz-rest-plugin#2713]
Since a couple of weeks my Hue Motion keeps losing connection with the controller. I used to work rock solid, but sometimes it disconnects. And if it doesn't detect motion, the motion itself has a red blinking led.

Is this a known bug? I'm on the latest firmware (26350500) and controller software.

**Comment by Webserve** [comment]
did you try to change the batteries?

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
