### ISSUE TITLE
[BUG REST API] ConBee itself is listed as light in deCONZ 2.5.75

### ISSUE THREAD

**Issue by nodefeet** [dresden-elektronik/deconz-rest-plugin#2717]
I updated to 2.5.75 and noticed that after searching for new lights Conbee itself is now shown as a light.

In Postman I receive for: GET: xxx/api/xxx/lights
```json
{
    "3": {
        "etag": "xxx",
        "hascolor": false,
        "manufacturername": "dresden elektronik",
        "modelid": "ConBee II",
        "name": "Configuration tool 3",
        "state": {
            "reachable": true
        },
        "swversion": "0x264a0700",
        "type": "Configuration tool",
        "uniqueid": "xxx"
    }
}
```

At least I do not see any reason to do that. 
Hardware: RPi3B+, Conbee 2, deconz headless

**Comment by jensflorian** [comment]
See #2536

**Comment by Mimiix** [comment]
Please read: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2472#issuecomment-590541006

Closed for now :)!
