### ISSUE TITLE
New Device Support - Sercomm SZ-DWS04 Micro Door Window Sensor

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2722]
Please add support for the above Device

![image](https://user-images.githubusercontent.com/52735978/80294131-82172880-87a9-11ea-82d0-962427e9d86c.png)

![image](https://user-images.githubusercontent.com/52735978/80294121-5eec7900-87a9-11ea-9ae7-86ed0b0fe2d4.png)

Thank you

**Comment by SwoopX** [comment]
Please provide all relevant screenshots. You may take #2583 as an example. Thanks!

**Comment by meremortals70** [comment]
I apologise for not providing all the information.  Your info on providing info only mentions the basic cluster.

![image](https://user-images.githubusercontent.com/52735978/80322860-08e00a00-886b-11ea-86d6-b69407844ea3.png)


![image](https://user-images.githubusercontent.com/52735978/80322844-f960c100-886a-11ea-90a9-f97aff485a79.png)

![image](https://user-images.githubusercontent.com/52735978/80322869-1b5a4380-886b-11ea-8647-3943631d27ae.png)

![image](https://user-images.githubusercontent.com/52735978/80322886-3a58d580-886b-11ea-93fe-2e88ad8e51bb.png)

![image](https://user-images.githubusercontent.com/52735978/80322877-2c0ab980-886b-11ea-8559-7f6aef66a31a.png)

![image](https://user-images.githubusercontent.com/52735978/80322900-4e9cd280-886b-11ea-9a9b-b07405a8be34.png)

![image](https://user-images.githubusercontent.com/52735978/80322908-5bb9c180-886b-11ea-88ed-1606b5f38f37.png)

![image](https://user-images.githubusercontent.com/52735978/80322917-6b390a80-886b-11ea-9bcf-16059df942ad.png)

![image](https://user-images.githubusercontent.com/52735978/80322929-755b0900-886b-11ea-83e0-bd86691ef555.png)

![image](https://user-images.githubusercontent.com/52735978/80322942-83108e80-886b-11ea-9efb-7ac5d3c20b20.png)

![image](https://user-images.githubusercontent.com/52735978/80322953-91f74100-886b-11ea-802d-571574725689.png)

**Comment by SwoopX** [comment]
Unfortunately, the screenshots are vastly not usable. When making the screenshots, please ensure the devices are "awake". You can wake them by pushing any physical button on the device repeatedly, wave you hand infront of a motion sensor, move the magnet for a dor sensor, etc.. All the attributes are not populated with usable values right now.

**Comment by meremortals70** [comment]
Lets try this again. I deleted the device and re-added

![IMG-2352](https://user-images.githubusercontent.com/52735978/80357289-1a9ecd00-88be-11ea-84e9-b441e7284658.PNG)

![IMG-2353](https://user-images.githubusercontent.com/52735978/80357313-25f1f880-88be-11ea-8dea-853a3a82fd66.PNG)

![IMG-2354](https://user-images.githubusercontent.com/52735978/80357354-386c3200-88be-11ea-886d-3a4b4e13d742.PNG)

![IMG-2355](https://user-images.githubusercontent.com/52735978/80357380-4457f400-88be-11ea-8257-2ae2c2f8023a.PNG)

![IMG-2356](https://user-images.githubusercontent.com/52735978/80357433-53d73d00-88be-11ea-84e5-020858f83d08.PNG)

![IMG-2357](https://user-images.githubusercontent.com/52735978/80357482-63568600-88be-11ea-8be7-9950aead13fa.PNG)

![IMG-2358](https://user-images.githubusercontent.com/52735978/80357515-70737500-88be-11ea-9201-df61250ace5e.PNG)

![IMG-2359](https://user-images.githubusercontent.com/52735978/80357552-7d906400-88be-11ea-98c7-186ecfa57086.PNG)

**Comment by SwoopX** [comment]
Much better now, thanks! I'll let you know if I need anything else.

**Comment by SwoopX** [comment]
@meremortals70 Could you please double check the value for battery voltage of the power configuration cluster? Please double click on the value and the press read in the opened dialog (not read config). 255 does not feel right but eventually, only low battery is reported through battery alarm mask...

**Comment by meremortals70** [comment]
Thanks for working on this.  Does this look better?

![image](https://user-images.githubusercontent.com/52735978/81518514-a6fec480-9381-11ea-9334-430b93c36624.png)

**Comment by SwoopX** [comment]
Indeed, thanks!

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
