### ISSUE TITLE
Tuya 16A zigbee power plug, compatible?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#2723]
Hi, I saw this on Aliexpress.  Will they work with deCONZ Conbee1? Also power metering and energy? Other values readable?

https://it.aliexpress.com/item/4000688486196.html?spm=a2g0y.12057483.0.0.1fcb649f1ge1zD

**Comment by SwoopX** [comment]
Support has not yet been requested. I expect it shouldn't be hard to add.

**Comment by SwoopX** [comment]
Hey, if the plugh would have the model ID TS0121, then it should be already supported, see #2677

**Comment by Mimiix** [comment]
It seems this issue is inactive / resolved. If it is not, please re-open or create another issue!
