### ISSUE TITLE
Issue Tracker for Phoscon

### ISSUE THREAD

**Issue by pattyland** [dresden-elektronik/deconz-rest-plugin#2724]
Hi,

I asked this question already [here](https://github.com/dresden-elektronik/phoscon-app-beta/issues/66) but maybe that repository is not longer monitored.

What is the right place to report bugs in Phoscon?

Best Regards
Sören

**Comment by SwoopX** [comment]
You may reach out to Dresden Elektronik support.

**Comment by pattyland** [comment]
Hm ok, is Phoscon not on GitHub?
I would also do a PR if the developers agree to my proposal

**Comment by SwoopX** [comment]
Well, the repository says it's no longer maintained so from my perspective, their support is the only chance you have.

**Comment by SwoopX** [comment]
Phoscon repo has been reopened. You may want to raise it there and close the issue here. Thanks!

**Comment by StephanStS** [comment]
You find the Phoscon repo [there](https://github.com/dresden-elektronik/phoscon-app-beta/issues).
@pattyland: Would you then please close this issue?
