### ISSUE TITLE
Ikea on-off switch E1743

### ISSUE THREAD

**Issue by gck303** [dresden-elektronik/deconz-rest-plugin#2728]
I am a new owner of a conbee II stick. I am running it in a docker on a HP380e Ubuntu server. 

Can the attached Ikea switches please be supported? I have tried adding them, but cannot. Only two Ikea switches seem to be available to be added (the rotating dimmer and five button control). 

I am happy to supply any additonal information needed. I only have access to the phoscon app, as I am not sure how to open up the X interface on a CLI-only machine. 

Many thanks, George

![20-04-28 16-46-48 1697](https://user-images.githubusercontent.com/30334661/80508653-3c588c80-8970-11ea-93d2-aa6aa6faeefc.jpg)
![20-04-28 16-46-53 1698](https://user-images.githubusercontent.com/30334661/80508665-3e225000-8970-11ea-9865-39abccd8f4dc.jpg)

**Comment by jensflorian** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/853#issuecomment-458695666

**Comment by gck303** [comment]
Thank you. That works.
