### ISSUE TITLE
Can't get API KEY

### ISSUE THREAD

**Issue by CarpeDiemRo** [dresden-elektronik/deconz-rest-plugin#2729]
**Prerequisites**

1. Conbee II USB stick
2. RPI 4
3. Hassio 0.108.9
4. Postman on macOS
5. RESTClient 2 for Mozilla

**How to reproduce**
`GET https://dresden-light.appspot.com/discover`
--> 200 OK

`POST 172.30.33.1:40850/api` or
`POST https://172.30.33.1:40850/api`

> Could not get any response
There was an error connecting to http://172.30.33.1:40850/api.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

--> in Postman and NO answer in RESTClient 2

The body is 
`{
    "devicetype": "myapplication"
}`

and **raw** button is checked 

Check attached image

![Screenshot 2020-04-28 at 19 32 12](https://user-images.githubusercontent.com/38489167/80513207-60739800-8987-11ea-9819-59042e1a05b9.png)

**Comment by Smanar** [comment]
Hello, perhaps https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2716

**Comment by CarpeDiemRo** [comment]
@Smanar Thank you, I will try.

**Comment by CarpeDiemRo** [comment]
Everything is OK. It's worth mentioning that the IP that must be used is the **server IP** not the internal IP of the Deconz Gateway. 
 Therefore: 192.168.x.y. instead of 172.30.33.1
