### ISSUE TITLE
RGBW bulb color temperature ...

### ISSUE THREAD

**Issue by Kristian8606** [dresden-elektronik/deconz-rest-plugin#2733]
Hello!  I have a problem with the rgbw bulb that is described here.

https://github.com/ebaauw/homebridge-hue/issues/682#issuecomment-621470457

Can it be improved?

**Comment by ebaauw** [comment]
Looking at the code, the REST API plugin creates `state.ct`, when it receives a value for _Color Temperature_, irrespective of the value of _Color Capabilities_.  
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/1caed496f90b01c69be6f03886597004183152c8/de_web_plugin.cpp#L2529-L2547

I guess more devices report the wrong capabilities than colour temperature wrongly.  I'm afraid, for now, we have to whitelist the light to prevent this.

Could you attach a screenshot of the _Basic_ cluster (making sure the attributes have been read).

**Comment by Kristian8606** [comment]
Is this enough?

![F4E3735B-1F24-4FE2-B397-219394AB2B94](https://user-images.githubusercontent.com/34716572/82091394-f0dc0780-96ff-11ea-8386-676a8e971830.jpeg)

**Comment by ebaauw** [comment]
Yes, thanks.  The model looks like a generated password, I hope I can copy that without making a typo...

**Comment by Kristian8606** [comment]
The problem is solved! 
Thanks @ebaauw
