### ISSUE TITLE
Option to disable deconz ssdp server

### ISSUE THREAD

**Issue by mariusmotea** [dresden-elektronik/deconz-rest-plugin#274]
Hi,

So far i was not bother so much by the ssdp conflict with my hue emulator, but currently i'm using a kody cinema plugin that perform every time ssdp detection and it fail. The procedure is complicated, i need to stop deconz, disable deconz support in my emulator config (otherwise will fail to start because deconz is not reachable) and then restart the hue emulator. After successful detection i need to undo all these changes and this is very frustrating for me. I'm using deconz as service so if a parameter can be passed in systemd file for this it will be great.
Thanks.

**Comment by manup** [comment]
With the last commit you can start deCONZ with `--upnp=0` to disable the SSDP discovery.

**Comment by mariusmotea** [comment]
Thanks, what will be the release that will contain this commit?

**Comment by manup** [comment]
That will be 2.04.90 :)

**Comment by mariusmotea** [comment]
Works, thanks!
