### ISSUE TITLE
[Request Device Integration] Iris Contact Sensor v2 (CentraLite 3320-L)

### ISSUE THREAD

**Issue by poblabs** [dresden-elektronik/deconz-rest-plugin#2741]
I know the Iris Contact Sensor **v3** is supported but it doesn't look like the v2 is. 

Looks like it's really a CentraLite 3320-L based on the information below.

Looks like they can pair and be discovered but nothing shows in Phoscon or in Home Assistant 

Let me know if I can provide more info. Excited to get these working since I have a bunch of them!

![image](https://user-images.githubusercontent.com/3484775/80965594-c8d7d480-8de0-11ea-85fe-e7c1d0292c2e.png)

![image](https://user-images.githubusercontent.com/3484775/80965482-97f79f80-8de0-11ea-95e1-394da0fb7842.png)

![image](https://user-images.githubusercontent.com/3484775/80965432-80b8b200-8de0-11ea-875e-a140219161be.png)

**Comment by SwoopX** [comment]
Duplicate of #2632.

It is already supported by this commit https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2572/commits/1896ee207424ba99285d4db0bce866c6ed457596 and should be available with the next release.

**Comment by poblabs** [comment]
@SwoopX Awesome! Is there a way to integrate it sooner than the new release in the hass.io package? Maybe a custom dockerfile or something?

**Comment by SwoopX** [comment]
You can always compile the latest version available here but since I don't use docker, HA or HassIO, I cannot tell you how it's done.

Folks ate deconz Discord channel may help you out with that https://discord.gg/rgpT96

**Comment by SwoopX** [comment]
@poblabs Mind closing this issue if your questions have answered?

**Comment by poblabs** [comment]
Sure will. Do you know when the release will come out? Looking forward to
start using these devices.

**Comment by SwoopX** [comment]
Folks are saying it should be next week ;)

**Comment by poblabs** [comment]
Looking forward to it!
