### ISSUE TITLE
How many devices can I pair with Deconz

### ISSUE THREAD

**Issue by CarpeDiemRo** [dresden-elektronik/deconz-rest-plugin#2744]
Hi, I have a Conbee2 stick that I'm using with Hassio intalled on a RPI4. My question is how many zigbee devices can be paired with Deconz. I was trying to find this details in the product specifications but I didn't find it.
Thanks for your help.

**Comment by Mimiix** [comment]
Was answered in : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1379

**Comment by CarpeDiemRo** [comment]
@Mimiix Thanks a lot for your quick answer. My bad, because I wasn't clear enough. 

My use case: 64 Gledopto lights spots. Can we all be managed by one Deconz stick? All are routers, no end point.

**Comment by Mimiix** [comment]
Should work fine :)

**Comment by CarpeDiemRo** [comment]
@Mimiix Thanks a lot. I dare to ask if you have tried or it is an assumption based on equipment specifications?

**Comment by Mimiix** [comment]
The moderator on the deCONZ discord (Yabbah) has 80~ ish nodes connected :)

**Comment by CarpeDiemRo** [comment]
Got it. Thanks a lot.

**Comment by Mimiix** [comment]
> Got it. Thanks a lot.

You're welcome:)
