### ISSUE TITLE
Interlock

### ISSUE THREAD

**Issue by LukaszP2** [dresden-elektronik/deconz-rest-plugin#2746]
Hi,

How can I do interlock to 3 gang switch. Is there any option in conbee?

**Comment by LukaszP2** [comment]
No... Lonsonho 
https://a.aliexpress.com/_BTuRoq

**Comment by Smanar** [comment]
I can't be sure, but it seem it works https://easydomoticz.com/forum/viewtopic.php?p=81287#p81287

**Comment by LukaszP2** [comment]
I dont see inter lock option (only one gang on at time) i want do use it for roller

**Comment by Smanar** [comment]
Ha ok, sorry I haven't understand, so you want to make an lock feature to transform a double gang in a roller command ?

No, it's not possible in deconz, because on a normal double gang you can set both to "on", I think you need to program your "lock" using your home automation application.

**Comment by LukaszP2** [comment]
i do this but it takes time (small but it is)... 
I see this future in shelly, than zigbee2mqtt and I hope I can do this in conbee ;/ 
maybe add this :)

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
