### ISSUE TITLE
Schedules fire an hour early

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#275]
Timing for schedules seems to be broken by https://github.com/dresden-elektronik/deconz-rest-plugin/commit/8f43b4cd0be46238ac550559406dbd5787f972e4.  My alarms now fire an hour early.  In the web app the localtime is shown, based on the value of the `time` attribute as UTC, but it would seem the firing is based on the value of the `time` attribute as localtime.  Setting `time` through the API doesn't update `localtime`; setting `localtime` doesn't update `time`.

**Comment by manup** [comment]
Confirmed, holy crap just tried and sit immediately in the dark (created new schedule ETA in an hour: group off).

On it ...
