### ISSUE TITLE
Are these ZigBee roller shades supported?

### ISSUE THREAD

**Issue by hemmingsentfromhell** [dresden-elektronik/deconz-rest-plugin#2759]
Will this device work with deconz / ConBee II ?

Anyone has experience with them?

https://www.zemismart.com/zemismart-tuya-zigbee-roller-shade-motor-for-38mm-tube-alexa-echo-google-home-control-electric-engine-shutter-rod-p0274.html

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
