### ISSUE TITLE
Some devices suddenly don't connect

### ISSUE THREAD

**Issue by StoricU** [dresden-elektronik/deconz-rest-plugin#2762]
Hi,

My setup have been working great for the last few months, but when I woke up today I  was not able to operate my Hue dimmer switch.
The battery is ok, it flashes when I'm pressing a button, but there is no reaction in deConz.
![image](https://user-images.githubusercontent.com/50556267/81647847-fdc1d800-942d-11ea-8fe2-8eb6f60a2330.png)

As you can see og the picture, I have also lost contact with a light, that is just beside the light below. So there is no distance/signal problem.

Anyone have a suggestion for troubleshooting or a way to fix it?

**Comment by Smanar** [comment]
And the light don't come back after a power cycle ?

**Comment by StoricU** [comment]
> Hello, and the light don't come back after a power cycle ?

Did not think of trying that.
My main focus was why the remote did not work, since the light is always on anyway.

But testing this also fixed the remote problem. After the power cycle, the light connected and 1 second later the remote connected.
![image](https://user-images.githubusercontent.com/50556267/81710097-c45f8b80-9472-11ea-9c42-f947f16bc99f.png)

Don't know what happened, but it works now! :)

**Comment by Smanar** [comment]
Lol, yep but the light wasn't the remote parent.
Zigbee magic :)
