### ISSUE TITLE
disable router function

### ISSUE THREAD

**Issue by LukaszP2** [dresden-elektronik/deconz-rest-plugin#2770]
Hi

I got problem with my wall switchs. In VNC I see it's a router. When I add new device it connecting to them but for few minuts/hour its disconnected. 
How to turn off router function in it or what to do to start working as a router?

**Comment by SwoopX** [comment]
Typically, mains powered devices are routers. The device type is determined base on the information provided in the node descriptor response packages. The corresponding data comes from the device firmware, so no way to change it.

The behaviour you're experiencing should have nothing to do with the device type. Please provide more information about the devices in question (Brand, Model, modelID, etc.).

**Comment by Smanar** [comment]
Just by curiosity, it' s a legrand or Osram device, and the device that disconnect are Xioami ?

It's not possible to turn on or off the router feature but @pipiche38 have find a good tips.
Instead of sending the permit join request in broadcast, it's possible to send it at only one router, so you can select wich one device you want to use as router.

**Comment by LukaszP2** [comment]
End devices its aqara. Switch is lonsonho (
https://a.aliexpress.com/_BOtzDk ) 
![IMG_20200514_104429](https://user-images.githubusercontent.com/44735995/81913216-f1758080-95cf-11ea-9d5c-ed52b4a7af43.jpg)
![IMG_20200514_104634](https://user-images.githubusercontent.com/44735995/81913393-36011c00-95d0-11ea-8c06-60719031e4d7.jpg)

**Comment by Smanar** [comment]
Ha, tuya and Xiaomi ? First time I m seing this issue
You have some informations here https://community.hubitat.com/t/xiaomi-aqara-devices-pairing-keeping-them-connected/623
But nothing about tuya.

**Comment by LukaszP2** [comment]
I disconnect all this switch and everything was ok.  I reconnected aqara sensor direct to conbee. After 12h I turn on switch. Only motion detectors (7 from 9) reconnected to switch. The rest of sensors: windows (15), temperature (8) and battery switch (2) works ok.
A have two Aqara wire switch (LLKZMK11LM) maybe this help if I add them somewhere...

**Comment by Smanar** [comment]
>Only motion detectors (7 from 9) reconnected to switch
You mean they was directly connected to the conbee, and have leave it to reconnect them using the switch, 12h after ?

**Comment by LukaszP2** [comment]
Exactly.. 1-12h and they change conbee to switch

**Comment by Smanar** [comment]
WTF ?
And it's Aquara sensor ? You are looking the mesh on deconz ?

**Comment by LukaszP2** [comment]
Yes aqara motion.
Im looking on vnc

**Comment by Smanar** [comment]
If you don't know where is it, I don't think you have used it ^^.

But it's realy strange, xiaomi device never do that, they prefer leave than using another way.

**Comment by LukaszP2** [comment]
i forgot about permint join. I will try add with that.

**Comment by Smanar** [comment]
No, don't worry, you can't add device without that, when you use in phoscin "add new device" it will enable the permit join for some minut.

**Comment by LukaszP2** [comment]
still nothing ;/ I think I sell this switch and buy some think else....

**Comment by Smanar** [comment]
I haven't find similar issue with Xiaomi<>Tuya.
But you are the first one I see having Xiaomi device that change router .....

**Comment by LukaszP2** [comment]
I buy CC2531 with Zigbee2MQTT and have the some problem. I add montion detector and about 11:30 we go outside. We back about 13:30

![aqara motion](https://user-images.githubusercontent.com/44735995/82730035-0f905e80-9cfd-11ea-841c-8309e64ee866.PNG)

this is link quality ... 

![aqara](https://user-images.githubusercontent.com/44735995/82729986-af99b800-9cfc-11ea-9ca8-8431c7adbf0f.PNG)

**Comment by Smanar** [comment]
Ok, so we can add tuya to problematic device with Xiomi ....

**Comment by LukaszP2** [comment]
I just upgrade 2.05.76 maybe this can help...

**Comment by Mimiix** [comment]
@LukaszP2 Is this fixed?

**Comment by LukaszP2** [comment]
X3 33xd w d
