### ISSUE TITLE
How to change MAC

### ISSUE THREAD

**Issue by bastshoes** [dresden-elektronik/deconz-rest-plugin#2776]
I've moved from Conbee I to Conbee II via backup restore. Now to sticks have same MAC. It have negative impact on discovery process.

How can I change MAC on stick?

**Comment by Smanar** [comment]
You can in deconz (In the GUI) in network setting.
But I don't understand the problem, your 2 conbee don't work in same time ? So they can have the same MAC.

**Comment by bastshoes** [comment]
They work some how. But when I try to replace rests_api lib in my installation I can't login to web GUI. pwa app discovers second stick instead of my.

**Comment by Smanar** [comment]
Have you tried with deleting browser cache ? or using another browser (or using iconito mode) ?

**Comment by bastshoes** [comment]
Yes, I've tried all this. 3 different browsers. Incognito mode in all of them.
Starnge ting that https://phoscon.de/discover returns data of sescond stick only when I try to use new rest_api lib. If return old one back in 5 minutes in starts return rmy data

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
