### ISSUE TITLE
Deconz stick not connected

### ISSUE THREAD

**Issue by Curtis777** [dresden-elektronik/deconz-rest-plugin#2779]
Hey Guys 
I just installed a fresh ubuntu VM installed 
iobroker 
and added my deconz stick and my zigbee texas instruments stick
but at firmware it says not connected.

in the shell i see its on ttyACM1
everything works great exept my deconz.
![image](https://user-images.githubusercontent.com/35459158/82102747-c6467a80-9710-11ea-9dee-3c1b03ca69b1.png)

**Comment by SwoopX** [comment]
Is the user under which you're running deconz member of the dialout group? What do `id` and `ps aux | grep deCONZ` give as output?

**Comment by Mimiix** [comment]
It seems this issue is resolved or otherwise inactive. If it is not, please re-open!
