### ISSUE TITLE
Legrand - Cable Outlet integration

### ISSUE THREAD

**Issue by Frederic7391** [dresden-elektronik/deconz-rest-plugin#2782]
Hi,

I try to communicate with Legrand Cable Outlet, but it's not working totally.
When I plug the key on my laptop and use the software Deconz, it works perfectly, I can change mode, I turn ON, turn OFF.
But I don't see any "sensor" , "switch" or "light" in webapp, nothing appear.
How is it possible ?

Thanks, 

![image](https://user-images.githubusercontent.com/65504174/82155002-26a0fd80-9872-11ea-97d6-d0a1a876c535.png)

**Comment by Smanar** [comment]
Yep, Phoscon is just an application that use the API.
It don't display all devices.
But if you use the on/off mode, you will have a visible device in light.
For the "fil pilote" mode you need to use another application or command line.

This device create 3 device
- 1 light that can can be used with on/off if enabled
- 1 sensor ZHAthermostat to set the "fil pilote" mode if enabled.
- 1 sensor ZHAconsumption for powe consumption.
Only the first one can be visible in Phoscon. And you need to update the device for the 2 sensor can be enabled.

**Comment by Frederic7391** [comment]
Where I should see light? ZHAthermostat and ZHAConsumption?
Once i see it in deconz, if I do a command rest like "GET LIST" I should see my equipments? right?

**Comment by Smanar** [comment]
You can see them only by the API.
Wich one application are you using (other than phoscon) ? Jeedom/HA/OpenHab/Domoticz/... ?

If you don't use other application I will give you a curl command to change the mode.

**Comment by Frederic7391** [comment]
I use Jeedom.
But in jeedom I don't see any devices and I try to figure out why.
In deconz everything good and in jeedom nothing appear, no devices.

**Comment by Smanar** [comment]
Ok So an easy way to check your sensor is using a web Browser with this url

`http://IP:PORTapi/API_KEY/sensors`

IP and PORT are the same you are using to go to Phoscon, and you can use the same api_key you are using in Jeedom

If you realy miss the sensors :
- set Phoscon in permit join (add new light)
- return in deconz select the node , select the cluster 0000 "Basic"
- on the cluster tab, clic on the "read" button (to read attribute)

**Comment by Frederic7391** [comment]
Thanks, I followed your procedure and it works, I can operate with this device.
