### ISSUE TITLE
Centralite 3323 -Geu Door-/Window Sensor and Thermometer

### ISSUE THREAD

**Issue by babajun12** [dresden-elektronik/deconz-rest-plugin#2783]
Request for support of following Sensor:
Centrallite 3323-Geu

![grafik](https://user-images.githubusercontent.com/65506616/82156626-7d133980-987c-11ea-98fa-36248d1e35ef.png)

![grafik](https://user-images.githubusercontent.com/65506616/82156631-8f8d7300-987c-11ea-903f-a20b9c4a0b97.png)

Best Regards,
Gerhard

**Comment by babajun12** [comment]
![grafik](https://user-images.githubusercontent.com/65506616/82157129-eba5c680-987f-11ea-9eb2-b617da5685c7.png)

**Comment by SwoopX** [comment]
Please follow https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support and provide all mentioned screenshots. Thanks!

**Comment by babajun12** [comment]
With pleasure:
PowerConfiguration:
![grafik](https://user-images.githubusercontent.com/65506616/82159043-f8301c00-988b-11ea-857a-0f2e1fb3e7ac.png)
TempertureMeasurement:
![grafik](https://user-images.githubusercontent.com/65506616/82159111-4513f280-988c-11ea-9a3f-61991a5974d7.png)
IAS Zone:
![grafik](https://user-images.githubusercontent.com/65506616/82159132-64128480-988c-11ea-977e-75be9a708b3e.png)
Simple sensor clusters are empty:
![grafik](https://user-images.githubusercontent.com/65506616/82159158-97551380-988c-11ea-9df0-ee38a0dc7c7f.png)

Poll control:
![grafik](https://user-images.githubusercontent.com/65506616/82159291-7fca5a80-988d-11ea-8511-36dab736a498.png)
Diagnostics:
![grafik](https://user-images.githubusercontent.com/65506616/82159385-00895680-988e-11ea-8007-2c5f530f358f.png)
OTAU:
![grafik](https://user-images.githubusercontent.com/65506616/82159397-0f700900-988e-11ea-899b-b7abd431e653.png)



Basic cluster and node iofo above.

Please reply if you need more information,
Thanks Gerhard

**Comment by babajun12** [comment]
I added the IAS_CIE_Address

**Comment by Mimiix** [comment]
Case closed!
