### ISSUE TITLE
Migrated from raspbee to conbee - firmware update fails

### ISSUE THREAD

**Issue by tosion** [dresden-elektronik/deconz-rest-plugin#2784]
I just migrated my old homeassistant system using official Deconz addon running Raspbee in RPI3B+ to Conbee in Intel NUC.  I used cloning to get new Conbee to run my old existing zigbee mesh with 67 nodes. It works like a charm and I am very pleased with the result.

However I have one open question. In Phoscon Gateway it says there is a new firmware update available. I run the update process and it looks it updates. But the result is that it shows firmware did not change?

Could this be related to cloning or something else? Any help is appreciated.

![image](https://user-images.githubusercontent.com/48414735/82157810-6379ee00-988c-11ea-911d-8d1e70b6d0b7.png)

![image](https://user-images.githubusercontent.com/48414735/82157852-8c9a7e80-988c-11ea-9e8c-eb29748016b0.png)

![image](https://user-images.githubusercontent.com/48414735/82157881-c4092b00-988c-11ea-8414-e96071168620.png)

**Comment by SwoopX** [comment]
If memory serves, you must either restart deconz or just wait.

**Comment by tosion** [comment]
Thanks for your response!

I updated first time yesterday - I have restarted the whole system couple times with totally power of.
I have done the update procedure couple times  ...

Now after the latest restart it says that version is up to date but firmware is 26320500 not 26330500.

BTW which one it should be?

**Comment by tosion** [comment]
One more observation. In Deconz GUI behind VNC the node list still show the Coordinator as Raspbee with 26330500 firmware. In Phoscon it shows Conbee with 26320500 firmware.

Propable result of this cloning method - should I worry about this?

![image](https://user-images.githubusercontent.com/48414735/82249985-5ffd6a00-9953-11ea-9ea9-48d71130c17b.png)

**Comment by SwoopX** [comment]
Trust deconz GUI

**Comment by tosion** [comment]
OK - thanks!

Probably there is no reason to worry about this?
