### ISSUE TITLE
INNR SP120 detected as light instead of switch

### ISSUE THREAD

**Issue by Webunity** [dresden-elektronik/deconz-rest-plugin#2786]
I tried adding a new Innr SP120, but adding it as a switch (by searching) the led on the switch went to a red color. Then i resetted it by pressing the button 5 secs so it went back in search mode.
Tried adding it as a sensor and it went OK, but appeared at the lights section.

<img width="905" alt="Screenshot 2020-05-19 at 14 22 51" src="https://user-images.githubusercontent.com/186093/82325898-45230800-99dc-11ea-92e5-c7ac1511d69b.png">

I am running 2.05.75

What i am looking for as improvement:
1) That it is detected as a switch
2) That in case you are searching for something else and a device has been found some sort of toast message in the UI that a new device has been found.

**Comment by Mimiix** [comment]
Hi!

I don't think it is a switch, as it isn't usable as something that switches something else on or off(within Phoscon).

**Comment by Webunity** [comment]
Good point; but then it should appear as sensor at least.

As a side question;
> can you also configure this plug to have a default 'on' state? i want it to measure the power from my washing machine but power cuts should not put the plug into an 'off' state.

**Comment by Webunity** [comment]
Related: I think mine is a duplicate then; https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2578
