### ISSUE TITLE
API key request

### ISSUE THREAD

**Issue by Luigi-01** [dresden-elektronik/deconz-rest-plugin#2793]
Hi, 
I made a small backup server server for Domoticz and Phoscon.
- Server is an Ubuntu server with Domoticz, Phoscon, Pihole and Unifi.
 - Backup server is a Raspberry pi 3. Domoticz works and Phoscon as well.
However getting an API key is an issue:  POST > http://192.168.0.108:80/api 
[
  {
    "error": {
      "address": "/",
      "description": "body contains invalid JSON",
      "type": 2
    }
  }
]

Has anybody an idea how too solve this.

**Comment by SwoopX** [comment]
Have you unlocked the gateway and used the correct parameter to obtain the key?

**Comment by ebaauw** [comment]
What body to you specify to the POST?
