### ISSUE TITLE
Tradfri ON/OFF Switch

### ISSUE THREAD

**Issue by Christiandk1986** [dresden-elektronik/deconz-rest-plugin#2799]
I am installing Ikea Tradfri ON/OFF switches. If one of the buttons are pressed down for more than 3-4 seconds, the remote fails to send/deconz fail to pick up the e.g. "2003" signal to tell my system that the button has been released. Is there a workaround on this since the button is currently pretty much of no use.

**Comment by ebaauw** [comment]
What deCONZ version are you on?  I'm getting the x003 alright, even after holding over 10 sec.

**Comment by Christiandk1986** [comment]
I am on 2.05.75 and firmware 26580700

**Comment by Christiandk1986** [comment]
Node-red DeConz version is 1.1.14

**Comment by Mimiix** [comment]
As this is in Node-Red, i will close this issue as it is unrelated to the plugin.
