### ISSUE TITLE
Search for new devices through API

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#28]
When I issue a POST to `/api/<username>/lights` the deCONZ REST API responds: `[{"success":{"/lights":"Searching for new devices"}}]`.  The Wireless Light Control web interface shows that the network is open for new devices.  However, when doing a GET of `/api/<username>/lights/new`, it always returns `{"lastscan":"2012-10-29T12:00:00"}`, even when the search is active.

When I issue a POST to `/api/<username>/sensors`, the API responds: `[{"success":{"/sensors":"Searching for new devices","/sensors/duration":60}}]`.  Again, the web interface shows that the network is open.  A GET of `/api/<username>/sensors/new` returns `{"lastscan":"active"}`.  After the search is done, it returns: `{"lastscan":"2017-04-21T15:44:57"}`.

When I open the network from the Wireless Light Control web interface, `/sensors/new` reports an active scan, but `/lights/new` doesn't.  When I open the network through POST `/lights`, `/sensors/new` doesn't show an active scan.  According to Wireshark, the web interface PUTs `{"permitjoin": 60}` to `/api/<username>/config`

On the Hue bridge, `/lights/new` and `/sensors/new` always return the same value for `lastscan`, regardless whether the search is initiated from POST `/lights` or POST `/sensors`.

**Comment by manup** [comment]
The POST interface `/api/<username>/lights` needs to be improved, it's already on the list.
However sensor and light search will be kept separated.

It's planned to have optional filters for the request, like searching only for a certain model identifier. Especially in larger environments there is always the risk that devices join the network which were not intended to join. The gateway should be able to take care of it and send ZDP leave requests to these devices.

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
