### ISSUE TITLE
Changes are not saved - Pls help me!

### ISSUE THREAD

**Issue by banjohb** [dresden-elektronik/deconz-rest-plugin#2802]
Hi. 

I have a big problem. I use deconz 2.05.76 with the Raspbee module. If I want to change the gateway name, the change is not saved. 

The same problem occurs when I want to save the switch control. The settings are deleted after each restart.

What can I do? I tryed to reinstall the deconz service, i removed the folders with the settings and load the backup. The same problem again!

**Comment by Mimiix** [comment]
Is this still a issue? 

What raspbee? What name do you mean?

Where do you try to change the name?
