### ISSUE TITLE
Tradfri up/down switch cant be used in switch-editor

### ISSUE THREAD

**Issue by yabbah** [dresden-elektronik/deconz-rest-plugin#2807]
Hi, the remote for IKEA FYRTUR blinds, the up/down button cant be choosed as switch in the switch editor for the group with the blinds. Would be nice to use Phoscon to conf the remote and not HA automations or node-red :)

**Comment by StephanStS** [comment]
Phoscon repo has been reopened [there](https://github.com/dresden-elektronik/phoscon-app-beta/issues). You may want to raise it there and close the issue here. Thanks!
