### ISSUE TITLE
Tradfri Dimmer (on/off switch) pairing problems

### ISSUE THREAD

**Issue by mastervol** [dresden-elektronik/deconz-rest-plugin#2816]
ConBee II on Raspberry 2
Version: 2.05.77/8.3.2020
Firmware: 26580700
OS Openhabian
OS Release Raspbian GNU/Linux 8 (jessie)

I cannot add a new purchased Ikea Tradfri On/Off Dimmer Switch, not as IKEA and not as OTHER.
I tried it with pushing 4 times the link button as well as holding the link button for 10+ seconds.
It is not recognized in the phoscon app.
Every other light bulb I had was recognized perfectly.

Thanks for comments.

**Comment by meremortals70** [comment]
I have just placed an issue for a Philips Hue Dimmer with the same problem

**Comment by jvyoralek** [comment]
I have ConBee II as well with slightly newer version 2.05.77/22.5.2020 and maybe older firmware 264A700 and was able to pair it via Ikea TRÅDFRI option and see it in the list of connected switches:

![image](https://user-images.githubusercontent.com/15640266/83352104-88209c00-a349-11ea-9883-e58ee201eab4.png)

Have you seen red blinking led after pressing 4 times?

**Comment by mastervol** [comment]
> Have you seen red blinking led after pressing 4 times?
Yes it blinks a few times, but it is not added.

I will try to install an older deconz version, hopefully all other items will stay.

**Comment by mastervol** [comment]
Ok it turns out I actually cannot downgrade.
I tried now installing http://deconz.dresden-elektronik.de/raspbian/alpha/deconz_2.05.77-raspbian-jessie-alpha_armhf.deb and the stable one from apt-get.
Still I cannot add the switch.

**Comment by mastervol** [comment]
Thanks it is fixed with version http://deconz.dresden-elektronik.de/raspbian/alpha/deconz_2.05.78-raspbian-jessie-alpha_armhf.deb.
;-)

**Comment by ohjohnsen** [comment]
Struggling with the same problem, on Windows platform.  How long until 2.05.78 for Windows is released?

**Comment by LeducH** [comment]
Still not working on version 

```
version 2.09.03 / 23/12/2020
Firmware 26660700
```

**Comment by Mimiix** [comment]
@LeducH BEst would be to open a seperate issue :)

**Comment by TuomasPakkanen** [comment]
> Still not working on version
> 
> ```
> version 2.09.03 / 23/12/2020
> Firmware 26660700
> ```

Pairing worked for me by using the "Other switch" option. Did not work with the Ikea Trådfri dimmer option.

**Comment by vbaros** [comment]
Same for me. Tried multiple times to pair using Ikea option and it didn't work. It worked immediately using Other option. Version 2.09.03 / 12/23/2020. Firmware 26660700.

**Comment by juniorz** [comment]
I have just paired two brand new switches. Both switches at version 2.2.010 and were bought from an IKEA store in Germany (if the region matters).

```
2.10.04 / 14/03/2021
26660700
```

Add New Switch > IKEA > TRÅDFRI remote control

Press the reset button 4x. Wait for the red(?) light on the switch to turn on. Wait for the light on the switch to turn off. Close the window with the instructions.

**Comment by istepaniuk** [comment]
All my TRAFI (E1743) pair normally with deconz, except the one I updated the firmware to (using zigbee2mqtt OTA feature). This last firmware from this year (TRADFI firmware 20230308) does not pair with deconz. 

It does "something" if I choose "Other" instead of IKEA. Though the device seems to finish pairing and the phoscon app says "Compound prepared" (whatever that means), no new device is added to deconz.
