### ISSUE TITLE
New Device Request (Sort of) Embertec BQZ10-AU-01 Plug

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2823]
Good Evening

I have managed to pair this plug to deconz (and HA).

![image](https://user-images.githubusercontent.com/52735978/82876453-27c1e100-9f7c-11ea-8a5b-024540efd633.png)

I am able to operate the on/off function from HA without an issue so I am thinking someone has had a look at this device previously, however, could not find it in issues or any support list.

Are we able to add full functionality for power consumption etc?

![image](https://user-images.githubusercontent.com/52735978/82876637-75d6e480-9f7c-11ea-96fd-220384835fcc.png)

![image](https://user-images.githubusercontent.com/52735978/82876733-9868fd80-9f7c-11ea-8a60-f3cb9b4f29a1.png)

![image](https://user-images.githubusercontent.com/52735978/82876808-b59dcc00-9f7c-11ea-89bd-6c1078dc184b.png)

![image](https://user-images.githubusercontent.com/52735978/82876883-cc442300-9f7c-11ea-9035-c6a6a8af7a72.png)

![image](https://user-images.githubusercontent.com/52735978/82877038-0d3c3780-9f7d-11ea-9fb6-0e806a76db7f.png)

![image](https://user-images.githubusercontent.com/52735978/82877108-247b2500-9f7d-11ea-8bfb-0baa01e4bdfc.png)

![image](https://user-images.githubusercontent.com/52735978/82877176-38268b80-9f7d-11ea-85df-388dce92db8d.png)

![image](https://user-images.githubusercontent.com/52735978/82877275-4ffe0f80-9f7d-11ea-8fa2-1d8577795169.png)

![image](https://user-images.githubusercontent.com/52735978/82877349-66a46680-9f7d-11ea-8b65-886a63b48286.png)

![image](https://user-images.githubusercontent.com/52735978/82877491-95224180-9f7d-11ea-829c-82dac6e5d59d.png)

![image](https://user-images.githubusercontent.com/52735978/82877544-ac612f00-9f7d-11ea-9bd1-fda6b58c9727.png)

![image](https://user-images.githubusercontent.com/52735978/82877623-c8fd6700-9f7d-11ea-9a84-d4772e47ce59.png)

![image](https://user-images.githubusercontent.com/52735978/82877694-de729100-9f7d-11ea-95df-e21a456dc7ab.png)

![image](https://user-images.githubusercontent.com/52735978/82877769-f813d880-9f7d-11ea-81cf-4566f499f7bf.png)

![image](https://user-images.githubusercontent.com/52735978/82877850-0feb5c80-9f7e-11ea-9a04-f0b01b1ceffb.png)

![image](https://user-images.githubusercontent.com/52735978/82877917-2396c300-9f7e-11ea-919b-1579e63b1645.png)

![image](https://user-images.githubusercontent.com/52735978/82877972-37dac000-9f7e-11ea-84b0-38602ec1567b.png)

![image](https://user-images.githubusercontent.com/52735978/82878022-4aed9000-9f7e-11ea-97ba-4ccc44a30487.png)

![image](https://user-images.githubusercontent.com/52735978/82878087-5f318d00-9f7e-11ea-912a-11b740f9d23d.png)

![image](https://user-images.githubusercontent.com/52735978/82878156-74a6b700-9f7e-11ea-9153-a2a976483ad9.png)

![image](https://user-images.githubusercontent.com/52735978/82878213-8720f080-9f7e-11ea-9c39-a9d719dab8cb.png)

![image](https://user-images.githubusercontent.com/52735978/82878297-a6b81900-9f7e-11ea-96f3-b28825214dd6.png)

**Comment by SwoopX** [comment]
Closing this as PR has been merged. Supported with .78
