### ISSUE TITLE
Manually Upgrading Conbee II Firmware

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2831]
I have searched high and low for a guide to manually upgrade the firmware on the Conbee II for my implementation

Ubuntu Linux>>HA installed in Docker>>Deconz add-in for HA.

Nothing seems to explain upgrading the firmware when you are running the Deconz add-in on HA where HA is in a docker container. Not a separate docker container for Deconz.

Can anyone help?

**Comment by stickpin** [comment]
@meremortals70, you can follow this guide: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

I've done an upgrade to my Conbee II two days ago using the Docker method and everything went well.

**Comment by meremortals70** [comment]
Sorry, that will not work.

It is for the marthoc's deCONZ Docker image

not the add-on installed in HA which is a docker image.

That is a separate docker image for deconz standalone.

**Comment by stickpin** [comment]
@meremortals70 ok.
If you running HASS.IO, you can install the Portainer, but please be careful, you can destroy your setup if you will do something wrong with your dockers.

In the Portainer go to the `Settings` - `Settings` and remove all the filters from `Hidden containers`.
Now go to the `Containers`, you would see `addon_core_deconz`, press `exec console` button and connect using `/bin/bash`.

Now execute the following:
- `/usr/bin/GCFFlasher_internal -l`
You would see list of the devices. Something like this:
<img width="617" alt="Screenshot 2020-05-27 at 15 36 15" src="https://user-images.githubusercontent.com/630000/83027124-0a4e4f00-a030-11ea-9526-eb9e2b253273.png">
- `ls -1 /usr/share/deCONZ/firmware` to see list of available firmware in this docker. Should look something like this:
<img width="503" alt="Screenshot 2020-05-27 at 15 40 02" src="https://user-images.githubusercontent.com/630000/83027566-8c3e7800-a030-11ea-997f-3c35f0e5f482.png">

Now be careful and make sure you choose the correct firmware and correct device.
If you sure the next command should be:
- `/usr/bin/GCFFlasher_internal -d <device_path> -f /usr/share/deCONZ/firmware/<firmware_filename>`

So if you want to flash Conbee II, your command should look like this:
- `/usr/bin/GCFFlasher_internal -d /dev/ttyACM0 -f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF`

Please enter and pray. :)

I hope it helps.
You can remove Portainer Addon after that if you don't need it.

**Comment by Smanar** [comment]
And the methos explained on the marthoc's deCONZ Docker Github ?
https://github.com/marthoc/docker-deconz

**Comment by stickpin** [comment]
> And the method explained on the marthoc's deCONZ Docker Github ?
> https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

Your access to `bash` is limited once you running managed Hass.IO image. So you cannot do what is explained in this link.

**Comment by Smanar** [comment]
Ha ok, my bad I have read he use a container for "deconz", not for the "deconz HA add on"

**Comment by Mimiix** [comment]
As there was no response from @meremortals70 on this, i'll be closing this up!

**Comment by meremortals70** [comment]
There was no response because no one was actually listening to my problem.

**Comment by Mimiix** [comment]
@meremortals70 : @stickpin gave some comprehensive input on your issue. I'm happy to reopen if you need some more debugging on this with him.

**Comment by meremortals70** [comment]
Actually no because I am not running that docker image as previously explained

**Comment by Mimiix** [comment]
As far as i know, the Addon in HA does run in a seperate containers.  I'm still on the old firmware, i'll try his method later today.

**Comment by meremortals70** [comment]
Can’t paste an image here as I am currently on an iPad. However I only have three containers in my docker and they are HA, Hassio multicast and assistant relay.

With the Mathic image, you create and container by loading the image.

What I have is I loaded the HA image and then added the Deconz add-in from supervisor.

**Comment by Mimiix** [comment]
I've had that too(i'm trying now), but did you go to settings and remove the labels? That made deconz show up for me.

**Comment by meremortals70** [comment]
I think this is mute for the moment as I have downgraded to .75 because .76 and .77 are so troublesome

**Comment by meremortals70** [comment]
But what do you mean by removing the labels

**Comment by Mimiix** [comment]
@stickpin Wrote: 

**In the Portainer go to the Settings - Settings and remove all the filters from Hidden containers.**

I just did that, but not i'm getting another error on trying to flash. Not sure how to fix that though. I'm using a Nas so that complicates things in terms of usb devices. Maybe its trough that, i don't know. 

I've created a issue for that:  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2935

**Comment by oat1** [comment]
After the last step i recive:
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

How to solve this ?

> @meremortals70 ok.
> If you running HASS.IO, you can install the Portainer Addon from the Addons Store, but please be careful, you can destroy your setup if you will do something wrong with your dockers.
> 
> In the Portainer go to the `Settings` - `Settings` and remove all the filters from `Hidden containers`.
> Now go to the `Containers`, you would see `addon_core_deconz`, press `exec console` button and connect using `/bin/bash`.
> 
> Now execute the following:
> 
> * `/usr/bin/GCFFlasher_internal -l`
>   You would see list of the devices. Something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 36 15" width="617" src="https://user-images.githubusercontent.com/630000/83027124-0a4e4f00-a030-11ea-9526-eb9e2b253273.png">
> 
> * `ls -1 /usr/share/deCONZ/firmware` to see list of available firmware in this docker. Should look something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 40 02" width="503" src="https://user-images.githubusercontent.com/630000/83027566-8c3e7800-a030-11ea-997f-3c35f0e5f482.png">
> 
> Now be careful and make sure you choose the correct firmware and correct device.
> If you sure the next command should be:
> 
> * `/usr/bin/GCFFlasher_internal -d <device_path> -f /usr/share/deCONZ/firmware/<firmware_filename>`
> 
> So if you want to flash Conbee II, your command should look like this:
> 
> * `/usr/bin/GCFFlasher_internal -d /dev/ttyACM0 -f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF`
> 
> Please enter and pray. :)
> 
> I hope it helps.
> You can remove Portainer Addon after that if you don't need it.



> @meremortals70 ok.
> If you running HASS.IO, you can install the Portainer Addon from the Addons Store, but please be careful, you can destroy your setup if you will do something wrong with your dockers.
> 
> In the Portainer go to the `Settings` - `Settings` and remove all the filters from `Hidden containers`.
> Now go to the `Containers`, you would see `addon_core_deconz`, press `exec console` button and connect using `/bin/bash`.
> 
> Now execute the following:
> 
> * `/usr/bin/GCFFlasher_internal -l`
>   You would see list of the devices. Something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 36 15" width="617" src="https://user-images.githubusercontent.com/630000/83027124-0a4e4f00-a030-11ea-9526-eb9e2b253273.png">
> 
> * `ls -1 /usr/share/deCONZ/firmware` to see list of available firmware in this docker. Should look something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 40 02" width="503" src="https://user-images.githubusercontent.com/630000/83027566-8c3e7800-a030-11ea-997f-3c35f0e5f482.png">
> 
> Now be careful and make sure you choose the correct firmware and correct device.
> If you sure the next command should be:
> 
> * `/usr/bin/GCFFlasher_internal -d <device_path> -f /usr/share/deCONZ/firmware/<firmware_filename>`
> 
> So if you want to flash Conbee II, your command should look like this:
> 
> * `/usr/bin/GCFFlasher_internal -d /dev/ttyACM0 -f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF`
> 
> Please enter and pray. :)
> 
> I hope it helps.
> You can remove Portainer Addon after that if you don't need it.

After last step, I'm receiving 

/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

How to solve this ?

**Comment by Mimiix** [comment]
@oat1 Please open your own Bug report for this :)

**Comment by SwoopX** [comment]
The messages seems to indicate missing packages. Try `sudo apt -f install`

**Comment by Mimiix** [comment]
@meremortals70 Did you manage to upgrade yet?

**Comment by meremortals70** [comment]
@Mimiix no I haven't and I have dropped the Deconz add-on for ZHA in HA

**Comment by Mimiix** [comment]
Okido! Then I will proceed and close this issue :)

**Comment by bgmn** [comment]
> @meremortals70 ok.
> If you running HASS.IO, you can install the Portainer Addon from the Addons Store, but please be careful, you can destroy your setup if you will do something wrong with your dockers.
> 
> In the Portainer go to the `Settings` - `Settings` and remove all the filters from `Hidden containers`.
> Now go to the `Containers`, you would see `addon_core_deconz`, press `exec console` button and connect using `/bin/bash`.
> 
> Now execute the following:
> 
> * `/usr/bin/GCFFlasher_internal -l`
>   You would see list of the devices. Something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 36 15" width="617" src="https://user-images.githubusercontent.com/630000/83027124-0a4e4f00-a030-11ea-9526-eb9e2b253273.png">
> 
> * `ls -1 /usr/share/deCONZ/firmware` to see list of available firmware in this docker. Should look something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 40 02" width="503" src="https://user-images.githubusercontent.com/630000/83027566-8c3e7800-a030-11ea-997f-3c35f0e5f482.png">
> 
> Now be careful and make sure you choose the correct firmware and correct device.
> If you sure the next command should be:
> 
> * `/usr/bin/GCFFlasher_internal -d <device_path> -f /usr/share/deCONZ/firmware/<firmware_filename>`
> 
> So if you want to flash Conbee II, your command should look like this:
> 
> * `/usr/bin/GCFFlasher_internal -d /dev/ttyACM0 -f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF`
> 
> Please enter and pray. :)
> 
> I hope it helps.
> You can remove Portainer Addon after that if you don't need it.

Hi!

I tried upgrading with portrainer but it gives me the following error
![image](https://user-images.githubusercontent.com/17111226/88728167-c95edd80-d139-11ea-80d7-c37b909d63e2.png)

If I try to kill deCONZ process, the whole container will reboot.
I have supported VMDK running on my Synology NAS. Conbee II is working otherwise just fine.

**Comment by Mimiix** [comment]
@bgmn As per documentation (and what i wrote before) : VM's are not claimed to be supported to update the device upon. Please refer to [This page](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-update-manually).

**Comment by bgmn** [comment]
> @bgmn As per documentation (and what i wrote before) : VM's are not claimed to be supported to update the device upon. Please refer to [This page](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-update-manually).

Thank you for the quick reply. I was hoping that it would be possible to update them easily via docker container but it's not so big task to update them manually on another computer.

**Comment by Mimiix** [comment]
@bgmn You can, but not within a VM. 

VM's add some complexity to serial connections.

**Comment by Harry-1976** [comment]
> @meremortals70 ok.
> If you running HASS.IO, you can install the Portainer Addon from the Addons Store, but please be careful, you can destroy your setup if you will do something wrong with your dockers.
> 
> In the Portainer go to the `Settings` - `Settings` and remove all the filters from `Hidden containers`.
> Now go to the `Containers`, you would see `addon_core_deconz`, press `exec console` button and connect using `/bin/bash`.
> 
> Now execute the following:
> 
> * `/usr/bin/GCFFlasher_internal -l`
>   You would see list of the devices. Something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 36 15" width="617" src="https://user-images.githubusercontent.com/630000/83027124-0a4e4f00-a030-11ea-9526-eb9e2b253273.png">
> 
> * `ls -1 /usr/share/deCONZ/firmware` to see list of available firmware in this docker. Should look something like this:
> 
> <img alt="Screenshot 2020-05-27 at 15 40 02" width="503" src="https://user-images.githubusercontent.com/630000/83027566-8c3e7800-a030-11ea-997f-3c35f0e5f482.png">
> 
> Now be careful and make sure you choose the correct firmware and correct device.
> If you sure the next command should be:
> 
> * `/usr/bin/GCFFlasher_internal -d <device_path> -f /usr/share/deCONZ/firmware/<firmware_filename>`
> 
> So if you want to flash Conbee II, your command should look like this:
> 
> * `/usr/bin/GCFFlasher_internal -d /dev/ttyACM0 -f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF`
> 
> Please enter and pray. :)
> 
> I hope it helps.
> You can remove Portainer Addon after that if you don't need it.

Thanks for this guide. It assumes the firmware is already in the /firmware folder. How do i pull the latest firmware to this folder with Portainer?

**Comment by Mimiix** [comment]
@Harry-1976 They should come with the latest versions. HA isn't putting those in because of their own reasons. You should open a issue in their Addon repository for this question.

**Comment by stickpin** [comment]
@Harry-1976 just go to the folder:
`cd /usr/share/deCONZ/firmware/`
and then do:
`wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_<FIRMWARE_YOU_NEED>.bin.GCF`

and then it supposed to work fine. :)

**Comment by Harry-1976** [comment]
@stickpin Thanks! That worked.
Update failed though.
Now to find a solution for the 781 error (same error as @bgmn posted) i got.

**Comment by stickpin** [comment]
@Harry-1976 it seems that you running on some other kind of virtualization.
I am also lately moved to vmware esxi approach and also was not able to upgrade the firmware today. 

So my solution was to use some old windows machine to update my Conbee II.

I hope it helps.

**Comment by Harry-1976** [comment]
@stickpin Yes, that's how i use to do it. I guess i'll have to stick to it for now.

Cheers.

**Comment by Mimiix** [comment]
@Harry-1976 @stickpin  upgrading on virtual installations is not supported / recommended.

**Comment by Harry-1976** [comment]
@Mimiix I understand that Mimiix. I’m running with the standard pi4 installation which i believe is not a virtual installation.
