### ISSUE TITLE
New Device Request: Aurora AONE Smart Remote

### ISSUE THREAD

**Issue by jlmkerr** [dresden-elektronik/deconz-rest-plugin#2834]
Please could you consider adding support for the following remote control:
https://auroralighting.com/gb/ProductDetail/AU-A1ZBRC

Cluster:
![image](https://user-images.githubusercontent.com/15086388/83019276-922b5d80-a01e-11ea-91a6-14e5a2499e8e.png)
![image](https://user-images.githubusercontent.com/15086388/83019779-6b215b80-a01f-11ea-880e-a405605fc250.png)

Node Info:
![image](https://user-images.githubusercontent.com/15086388/83019816-7b393b00-a01f-11ea-8e1b-59646bff1c09.png)

**Comment by Puntoboy** [comment]
Bump. Is this supported?
