### ISSUE TITLE
Gledopto ct colormode stopped working

### ISSUE THREAD

**Issue by Jolle666** [dresden-elektronik/deconz-rest-plugin#2840]
Hi, 

Since deCONZ v2.05.76 ct colormode stopped working with my Gledopto lights (GL-C-006 and GL-C-008). API error in Node-RED/Home Assistant. 2.05.75 is fine. 

Maybe it's related to [#2798](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2798)?

Thanks!

**Comment by SwoopX** [comment]
Update to .77, there's a fix for ct as I recall

**Comment by ebaauw** [comment]
Only for IKEA.  What type of GLEDOPTOs are these?  Could you list the resources and screenshots of the _Color Control_ cluster (after reading the attributes)?

**Comment by Jolle666** [comment]
The Gledopto GL-C-006 is the WW/CW LED controller (firmware 1.0.6). The GL-C-008 is the RGB+CCT LED controller (firmware 2.0.0).

I run Home Assistant with the Phoscon app on a RPI4 with Conbee II. I'm sorry, but not sure where to find resources and Color Control cluster.

**Comment by ebaauw** [comment]
Hm, both should expose `state.ct` and work?!  Did you happen to try .77?

What API error do you see?  Can you find out what API request are sent?

**Comment by ebaauw** [comment]
Double-checked the `GL-C-008`: it's working in 2.05.77:
```
$ ph get /lights/5
{
  "ctmax": 65535,
  "ctmin": 0,
  "etag": "34b94379dede7d32b61d6d6d480b7b11",
  "hascolor": true,
  "lastseen": "2020-05-28T19:55:36.214",
  "manufacturername": "GLEDOPTO",
  "modelid": "GL-C-008",
  "name": "GL-C-008",
  "state": {
    "alert": "none",
    "bri": 1,
    "colormode": "hs",
    "ct": 153,
    "effect": "none",
    "hue": 0,
    "on": true,
    "reachable": true,
    "sat": 0,
    "xy": [
      0.3125,
      0.3333
    ]
  },
  "swversion": "1.0.6",
  "type": "Extended color light",
  "uniqueid": "00:12:4b:00:1b:91:ec:83-0b"
}
$ ph put -v /lights/5/state '{"ct": 500}'
{
  "ct": 500
}
$ ph put -v /lights/5/state '{"ct": 153}'
{
  "ct": 153
}
```

**Comment by Jolle666** [comment]
@ebaauw thank you so much.

Just testet once more. This is the JSON in Node-RED:
![image](https://user-images.githubusercontent.com/58005432/83192470-df4e2300-a135-11ea-9fee-7a0471674c0b.png)

With 2.05.75 the LED controller is working and with no error in Node-RED:
![image](https://user-images.githubusercontent.com/58005432/83193099-c7c36a00-a136-11ea-9bb7-346f1ca37902.png)

With 2.05.77 the LED controller is not working and I get this API error in Node-RED:
![image](https://user-images.githubusercontent.com/58005432/83193288-08bb7e80-a137-11ea-86ac-68ed1a5b2be7.png)
with this debug message:
![image](https://user-images.githubusercontent.com/58005432/83193433-520bce00-a137-11ea-84ef-44038828add8.png)

This is the info in the Phoscon app:
![image](https://user-images.githubusercontent.com/58005432/83193537-841d3000-a137-11ea-9729-b375ed9110bd.png)

**Comment by ebaauw** [comment]
Ah OK: you cannot set `colormode`: it's a read-only attribute.  It's set automatically when you set the colour (temperature) trough `xy`, `hue` and `sat` (`hs`), or `ct`.

It has never done anything, but was silently ignored.  I fixed the handling of errors for a PUT of the light state, so you're only seeing the error since v2.05.76.

**Comment by Jolle666** [comment]
@ebaauw Ah, now it all makes sense and is working perfect. Thank you so much!
