### ISSUE TITLE
Door/window sensors

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2850]
Anyone have some good news for me?

I’m looking for a Door/Window Sensor that has the following attributes:

1. Reliable
2. Plays well with Routers
3. Reports Battery Accurately

Have quite a few Aqara devices and as my network has grown they have started to drop off. Not interference as close by routers have no problems.

Was thinking about Smartthings but they seem to have problems as well

Any one using visonic, climax or bosch?

**Comment by Mimiix** [comment]
As this question is not related to a issue with deCONZ or Phoscon, i close this issue for now. For advice or user reviews please use Discord or a dedicated forum.
