### ISSUE TITLE
RGBgenie ZB-5001 pairing issue

### ISSUE THREAD

**Issue by gmitch64** [dresden-elektronik/deconz-rest-plugin#2857]
Currently running 2.05.77

I broke out my RGBgenie remote to try and pair it up, since I believe that it's supported. I did have it paired up before

> https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1256

but since the buttons weren't working at the time, I removed it from my setup.
I've now come back to it, and I'm getting it to pair up, but it's not getting past the NWK address stage, no matter how I poke and prod it (I've removed it from the network, done a factory reset on it, included it again, pressed buttons on the remote when trying to read the basic cluster etc. And there's also a new battery in the remote as well, just in case)

One thing that I did notice, is that when I come to open the network to include it, as soon as I press the 2nd button for pairing, the network closes (I have it set for 10 mins open at the moment). I've repeated the inclusion process several times, and every time, then network immediately closes on pressing the 2nd button.

I don't know if that that's new behavior, but in the past when I've included new devices, the network has remained open for the 10 mins duration that I set. The only thing that I've added to the network recently has been a fan, and I don't remember whether that showed the same issue or not.

I don't have anything that's not already included to test with at the moment, but I'm wondering if anyone else is seeing issues pairing with 2.05.77?

![image](https://user-images.githubusercontent.com/27970644/83362101-a17f1380-a35c-11ea-885f-9ee48a3afe26.png)

**Comment by gmitch64** [comment]
And just to clarify, it does seem to read the additional buttons on the remote (it goes all the way up to 5:) but not 11).


![image](https://user-images.githubusercontent.com/27970644/83362239-adb7a080-a35d-11ea-8e77-0022d84679b9.png)

**Comment by SwoopX** [comment]
Can you please paste a screenshot from all available endpoints/clusters? The device seems to have more than just the 2 thought endpoints.

> One thing that I did notice, is that when I come to open the network to include it, as soon as I press the 2nd button for pairing, the network closes (I have it set for 10 mins open at the moment).

What does that mean? How does it close? Do you get a success message?

> but it's not getting past the NWK address stage

What is the NWK stage?

**Comment by gmitch64** [comment]
Sorry it's taken a couple of days to get back with you - work has been a bear this week.

> What is the NWK stage?

Maybe not the best description, but I get as far as this...

![image](https://user-images.githubusercontent.com/27970644/83946619-ff3db080-a7df-11ea-9b2b-66cdd946ab57.png)

Where as other recognized devices get past the NWK stage, and present this..

![image](https://user-images.githubusercontent.com/27970644/83946627-1381ad80-a7e0-11ea-9c49-883488744f9c.png)

> Can you please paste a screenshot from all available endpoints/clusters?

Yup.. Hopefully these come out ok. If there's any other info you need, please let me know.

Thanks.

G

![image](https://user-images.githubusercontent.com/27970644/83946641-2ac09b00-a7e0-11ea-9ae5-8f4212bce9ee.png)

![image](https://user-images.githubusercontent.com/27970644/83946659-40ce5b80-a7e0-11ea-8627-41ea42bb4058.png)

![image](https://user-images.githubusercontent.com/27970644/83946669-4cba1d80-a7e0-11ea-8036-ff2eff54bdd2.png)

![image](https://user-images.githubusercontent.com/27970644/83946682-59d70c80-a7e0-11ea-9dbc-1594609f27dc.png)

![image](https://user-images.githubusercontent.com/27970644/83946689-68bdbf00-a7e0-11ea-92c8-e31804414e13.png)

![image](https://user-images.githubusercontent.com/27970644/83946696-74a98100-a7e0-11ea-9cd1-3e958c0d1d8d.png)

![image](https://user-images.githubusercontent.com/27970644/83946718-9acf2100-a7e0-11ea-8c37-012c16b6f141.png)

![image](https://user-images.githubusercontent.com/27970644/83946737-acb0c400-a7e0-11ea-952d-28d5cdce5801.png)

![image](https://user-images.githubusercontent.com/27970644/83946755-ba664980-a7e0-11ea-852d-0ddb4968216a.png)

![image](https://user-images.githubusercontent.com/27970644/83946769-d5d15480-a7e0-11ea-9893-0a2f12300fde.png)

![image](https://user-images.githubusercontent.com/27970644/83946787-eeda0580-a7e0-11ea-8844-1dfa97b37412.png)
![image](https://user-images.githubusercontent.com/27970644/83946795-00231200-a7e1-11ea-8ee3-bf892be1059e.png)

![image](https://user-images.githubusercontent.com/27970644/83946813-1761ff80-a7e1-11ea-9a39-64510cb0b15e.png)

![image](https://user-images.githubusercontent.com/27970644/83946818-2183fe00-a7e1-11ea-9d18-721119093af0.png)

![image](https://user-images.githubusercontent.com/27970644/83946822-2943a280-a7e1-11ea-9d65-848d3d4a3510.png)

![image](https://user-images.githubusercontent.com/27970644/83946826-32cd0a80-a7e1-11ea-9843-c40553992e0c.png)

![image](https://user-images.githubusercontent.com/27970644/83946836-46787100-a7e1-11ea-92f0-ac93d6cbffb5.png)
![image](https://user-images.githubusercontent.com/27970644/83946844-58f2aa80-a7e1-11ea-959c-15fca18f1608.png)

![image](https://user-images.githubusercontent.com/27970644/83946851-6445d600-a7e1-11ea-94ad-e2fa9e40b441.png)

**Comment by SwoopX** [comment]
Thanks. So it appears that data from the initial issue was incomplete and the support with I previously mentioned might have been for a different device with a similar modelID (or it was best effort). Let's jump over to the original issue then and continue from there. 

@Mimiix please close, moving over to #1256
