### ISSUE TITLE
Device Support: YWSDCGQ

### ISSUE THREAD

**Issue by andi78** [dresden-elektronik/deconz-rest-plugin#2877]
Can the "Xiaomi Mijia Bluetooth Temperatur Luftfeuchtigkeit Sensor LCD Bildschirm Digital Thermometer Hygrometer Feuchtigkeitsmesser" be supported as well?

**Comment by jensflorian** [comment]
Hmm, is this really a zigbee device?

**Comment by andi78** [comment]
no.
https://www.nairaland.com/4791550/compare-3-xiaomi-temperature-sensors

This probe does not communicate with the Zigbee protocol, its communication mode is BLE (Bluetooth Low Energy) which implies having a Bluetooth gateway.

**Comment by SwoopX** [comment]
Then you've given yourself the answer already.
