### ISSUE TITLE
Raspbee 2 is not recognized on Raspberry

### ISSUE THREAD

**Issue by ebrger** [dresden-elektronik/deconz-rest-plugin#2878]
Hello, I have a Raspbee 2 since today. I installed it with the help of the manual. Phoscon or deconz is also reachable. But it does not show me any information under device.
What am I doing wrong?
i have already made an lsusb, it does not appear there. 
thank you
![phoscon](https://user-images.githubusercontent.com/31549020/83790337-4fa9f680-a698-11ea-8bdb-9de9b9c51148.PNG)

**Comment by StephanStS** [comment]
Hello @ebrger, 
which Pi hardware do you use? 
Did you went through the installation via https://phoscon.de/de/raspbee2/install
Or did you take this: https://phoscon.de/de/conbee2/install

As far as I assume the Raspbee II is connected via the GPIO connector (-> I2C) and not via USB (this would be a Conbee II). So a lsusb will not show the Raspbee2.
In every case, if you have a Raspbee II, [this](https://phoscon.de/de/support#conbee2-connection-issues) will not help. 

Hello Dennis (@Mimiix), 
is the Rasbee II connected via I2C? Then I propose to add a section 9 "Testen der Ansprechbarkeit des Rasbee II Moduls" in the [installation manual](https://phoscon.de/de/raspbee2/install) regarding checking whether the module is detected by the Pi hardware (via i2cdetect command).

The same could be in the Conbee II installation (you have a perfect description already [there](https://phoscon.de/de/support#conbee2-connection-issues)). Checking this during the installation gives a clear step-by-step advise. Of course this is needed for all different OS types...

**Comment by ebaauw** [comment]
The RaspBee and RaspBee II use the Pi's internal serial port on GPIO pins 14 and 15 (Broadcom numbers, not the physical pins).  See https://pinout.xyz/pinout/raspbee.  In additional to that, the RaspBee II uses I2C for the real-time clock.  I think they also use another GPIO pin for hardware reset.

**Comment by StephanStS** [comment]
@ebaauw: Hello Erik, do you know whether there is a small command line test program checking the correct presence of a Raspbee II board which eberger might test?

**Comment by ebaauw** [comment]
```
$ sudo GCFFlasher_internal -r
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26520700
Bootloader version 0x00030003, app crc: 0xD4E57E35
```

**Comment by StephanStS** [comment]
@ebrger: Would you post here whether and what solved your issue?
Thanks for closing it.

**Comment by ebrger** [comment]
Switched to conbee2 with usb after a connection could not be established even with a second raspbee and an image from Phoscon.

**Comment by Tim-AQ** [comment]
Hi,
I'm havint the same issue. When using the CGFFlasher to reset it i get this output:

```
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)

952: Error: failed to open device, status: Permission error while locking the device (2)
```

Any idea the issue is?

**Comment by StephanStS** [comment]
Did you use ‚sudo‘?

 

Von: Tim-AQ <notifications@github.com> 
Gesendet: Sonntag, 21. Februar 2021 11:58
An: dresden-elektronik/deconz-rest-plugin <deconz-rest-plugin@noreply.github.com>
Cc: StephanStS <stephan.schultze@schultze-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Raspbee 2 is not recognized on Raspberry (#2878)

 

Hi,
I'm havint the same issue. When using the CGFFlasher to reset it i get this output:

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
 
952: Error: failed to open device, status: Permission error while locking the device (2)

Any idea the issue is?

**Comment by Tim-AQ** [comment]
> 
> Did you use ‚sudo‘? ----------------------------
> […](#)
> I'm havint the same issue. When using the CGFFlasher to reset it i get this output: GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh Reboot device RaspBee (RaspBee) 952: Error: failed to open device, status: Permission error while locking the device (2) Any idea the issue is?

Sorry, deleted the original comment as a managed to resolve the issue.

I did use sudo, but got the error because deconz was running. The issue turned out to be the powersupply. Didnt notice any stability issues other than raspbee behaving inconsistent. However, replacing it solved the issue.
