### ISSUE TITLE
Type of lights are Unknown

### ISSUE THREAD

**Issue by snozzlebert** [dresden-elektronik/deconz-rest-plugin#288]
Crashes are fixed in .92, however all lights are reported as ```"type": "Unknown"``` in the rest api.
Reverted back to .90 and types are reported again (e.g. ```"type": "Dimmable light"```).

**Comment by ebaauw** [comment]
Indeed, with 2.04.92, type is Unknown for all my lights (and plugs) as well.

**Comment by manup** [comment]
Hmm strange, will be fixed during the day; `type` is now a ResourceItem `RAttrType`, seems that I missed some spots during the transition.

**Comment by ebaauw** [comment]
Not a spot, a level of nesting, see PR #289.

**Comment by manup** [comment]
Nice, thanks for the fix :)

**Comment by snozzlebert** [comment]
Fixed in 2.04.93, thanks.

**Comment by wvuyk** [comment]
Can 2.04.93 also be compiled for the ConBee Windows environment?

**Comment by manup** [comment]
Yes, sorry for the delay it's uploaded now.

https://www.dresden-elektronik.de/deconz/win/deCONZ_Setup_Win32_V2_04_93.exe
