### ISSUE TITLE
Info: not only deconz that loses lights.

### ISSUE THREAD

**Issue by olemr** [dresden-elektronik/deconz-rest-plugin#2887]
Hello.

I run 3 Zigbee networks at home, mostly to stay updated with what is going on with the different vendors.
Deconz is my main network, with 40 lights, 15 switches and 1 sensor. Multiple groups.
A Philips HUE bridge caters for 2 6xGU10 fixtures in the den, and 16 E27 CT facade lights. 2 groups.
Ikea bridge just have one Ikea remote and 1 single E27 CT bulb.

All my E14, E27 and GU10 bulbs are Ikea Trådfri, 4-5 HUE strips and 3xLillies.

I must say that the Pilips HUE bridge loses Ikea bulbs just as often as deconz.
Losing HUE lights are rear, but it does happen.
Even Ikea loses its own bulb, and after the battery ran out on the remote, I had to re-pair it.

Just to let you all know that none of these systems are yet perfect, but I'm hopeful that the analysis now going on will improve matters.

Thank you all for contributing.

**Comment by Smanar** [comment]
So to resume philips have better hardare than ikea ?

**Comment by olemr** [comment]
Yes, or better firmware?
But you are right. Topology and other 2.4 GHz interference can also play a role.

**Comment by Smanar** [comment]
It's personnal, but for me Philips is expensive but they are the better router.
