### ISSUE TITLE
Wish: Implement Danalock V3-Zigbee

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2893]
One wish: I have a Danalock V3 / Danabridge. Can anyone implement that?
The front door lock supports Zigbee v3 and is supported by "homebridge" and the chip "cc2531".
According to the manufacturer, the lock can be operated with IFTTT, which is (no longer) true.
Now there is no way for me to make the lock "smart".

When I try to connect the danalock to conbee, the blinking on the lock goes out, which indicates that it has received an answer from Conbee.
Unfortunately, the lock cannot be seen in the phoscon, which indicates that the front door lock was blocked by conbee.
greetings
Michael

**Comment by Mimiix** [comment]
Hi! 

There is a huge issue on it already here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/520 AFAIK it is implemented. 

However, a device not in Phoscon doesn't mean it is not supported. This is due the fact that it needs to be added manually in Phoscon by a dev. Therefore, if you find this device to work correctly in deCONZ, you should open a issue here: https://github.com/dresden-elektronik/phoscon-app-beta.

Depending on the system you host deCONZ on, you need to use either VNC(Linux based systems) or theres a application in Windows (If Windows is the host system).

**Comment by Michaelnorge** [comment]
Thank you 👍
