### ISSUE TITLE
Renamed devices do not stay renamed after reboot

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#2896]
Hi there 

On a couple of recently added devices to Deconz having some issues.

**First Issue**

When the SZ-ESW01 plugs are added to Deconz, they have different names.  This normally isn't an issue as when you change the name in Phoscon it updates in Deconz.  However, when these plugs which are detected as lights, are renamed in Phoscon the names are either not updated in Deconz or are updated but not persistent so when Deconz is restarted the names revert.

![image](https://user-images.githubusercontent.com/52735978/83985134-5461f980-a97b-11ea-95c4-f3cd71c614ad.png)

Second Issue

When the SZ-DWS04 are added the don't appear in Phoscon however will appear under the Deconz Integration in HA,  they don't appear in Phoscon.  They cannot be renamed here which normally propagates up to HA and down to Deconz.  When renamed in the HA Deconz integration this does not propagate down to Deconz. when Deconz is restarted they reset their names and as a consequence become unavailable in HA as I have renamed them there.

![image](https://user-images.githubusercontent.com/52735978/83985315-08fc1b00-a97c-11ea-9781-5cb71c98de47.png)

This is the same for some Tuya Temperature/Humidity Sensors.

![image](https://user-images.githubusercontent.com/52735978/83985338-2f21bb00-a97c-11ea-9638-5891bb7b4890.png)

I have downgraded deconz to .75 due to the issues with .76 and .77

**Comment by Mimiix** [comment]
Hi!

Can you please move the issues regarding to Phoscon to this repository: https://github.com/dresden-elektronik/phoscon-app-beta

I will create a PSA later today and making clear to post stuff at the correct places, as this hasnt been communicated before.

On the other questions, i cannot answer. However, i've noticed that more people have issues with devices not keeping their renamed name.

I will bring that up to @manup later today.

Thanks!

**Comment by meremortals70** [comment]
Well the issue is I don’t know if it is a Deconz or a Phoscon issue as it’s about the interaction between the two

**Comment by Mimiix** [comment]
Devices not showing up in Phoscon is something that is phoscon related. Devices need to be added there manually by @YKO-de .

**Comment by Mimiix** [comment]
You can keep it open for the remaining issue on renaming devices :)

**Comment by zombielinux** [comment]
This is still an ongoing issue. I have several of the Tuya Temperature and Humidity sensors, all coming in a RH3052 (n) where n is some integer. I cannot rename them at all. 

This is with the latest docker image as well.

**Comment by SwoopX** [comment]
Rename them via REST API.

**Comment by zombielinux** [comment]
Confirmed the REST api works. Still broken in the deConz application though.

**Comment by ebaauw** [comment]
There's no function in the GUI to rename a node.  You can set the _User Descriptor_ from the _Node Info_ panel, but I have yet to see a device that supports this descriptor.  The name on the node is set by the REST API plugin when the name of (one of the) corresponding resource(s) is changed through the API.

**Comment by manup** [comment]
Indeed the User Descriptor is not used much anymore, I also only know the FLS-PP lp which supports it. In the Zigbee specification it's an optional feature and presence of the User Descriptor is visible in the Node Descriptor flag.

**Comment by Mimiix** [comment]
@manup @ebaauw So this is a wontfix?

**Comment by kyletpugh** [comment]
Has this been fixed? Because I am having an issue with names being saved (using beta channel packages). I have tried from the REST API, the phoscon app, and the old web interface. The names are always wrong when deCONZ is restarted, I have to go through and rename about fifteen devices every time.

**Comment by Smanar** [comment]
Perhaps here > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4255#issuecomment-768090804
If name are still good in phoscan but bad in deconz.
