### ISSUE TITLE
POST /api/username/config/restartapp no longer works

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#290]
In .92, doing a POST to `/api/<username>/config/restartapp` still returns `[{"success":{"/config/restartapp":true}}]`, but deCONZ is no longer restarted.

**Comment by manup** [comment]
Is deCONZ running headless as systemd service? 

The gui version currently doesn't restart, will be fixed in the next versions.

**Comment by ebaauw** [comment]
No, I'm still on the GUI version.  It used to work some versions ago.  I only use restartapp in my scripts to re-create the gateway rules (so that the rules are re-created from `/rules/1`).  I don't do this regularly, so I don't know which version or commit broke it.

**Comment by manup** [comment]
Must have happened recently while we worked on the systemd deconz-update.service script.

**Comment by ebaauw** [comment]
Seems to be working in v2.04.99.
