### ISSUE TITLE
1.3.8 fehlerhafte Objekte

### ISSUE THREAD

**Issue by Xenon-s** [dresden-elektronik/deconz-rest-plugin#2901]
Hello, if you delete objects in version 1.3.8 (e.g. "lights" or "groups") the folder is not created again, but only an object "lights" is created. I tested it several times and after a downgrade to 1.3.7 it works. After a new update the error was there again, nothing is in the log.

However, the log also indicated that the device was switched (via Phoscon), but as I said, it just did not appear in the objects. Also restarting several times did not help.

**Comment by Mimiix** [comment]
Goodmorning!
Is this a issue with Phoscon?

**Comment by Xenon-s** [comment]
Hello, sorry. No ioBroker in combination with Phsocon. Everything works in Phoscon, but in ioBroker deconz version 1.3.8 is not properly synchronized. If you switch a device in Phsocon, the log also shows as debug that the switching status has changed, but no data point appears in the objects. Downgrade to version 1.3.7 and the objects are already available.

**Comment by Mimiix** [comment]
I think you have to ask this question at their GIT repo, as this is not a issue within the deCONZ rest plugin.
