### ISSUE TITLE
Sensors and Switches not visible in Phoscon

### ISSUE THREAD

**Issue by nunoary** [dresden-elektronik/deconz-rest-plugin#2905]
All my sensors and switches disappeared from Phoscon, but they are accessible via the Deconz GUI, and they seems to communicate normally. The lights are visible. 

This happen with version 2.05.77 after adding a new switch (IKEA ON/OFF), reverted to 2.05.75 but still not showing. Have  already tried several browsers.
I run Deconz under Windows 10. My Conbee 1 is updated to 26350500.

I get one Javascript error. These are the errors from the page:

DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/underscore-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/backbone-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

global.js?70da81:3 apikey = xxxxxxxxxxx
global.js?70da81:3 activated theme Bright
poll.js?5bcca9:3 add poll repeated sensors
open-beta.js?78d500:3 

GET http://MyIPxxxxxx/pwa/developer.js 404 (Not Found)
(anonymous) @ open-beta.js?78d500:3
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/underscore-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/backbone-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
websocket.js?e9ddc6:3 websocket connected: ws://MyIPxxxxxx/
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}

**Comment by Mimiix** [comment]
As per guidelines, Phoscon issues should be made in their repository. Please create it there: https://github.com/dresden-elektronik/phoscon-app-beta
