### ISSUE TITLE
New device request - ZBT DIMController D0800 Müller Licht

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#2906]
can you add this Müller Licht remote control please!

![sshot-1](https://user-images.githubusercontent.com/32480002/84074618-201a2780-a9d3-11ea-9288-a76eccb63b02.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/84074621-20b2be00-a9d3-11ea-962a-c4a86b4fa6ad.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/84074623-214b5480-a9d3-11ea-8ef6-e0a76800f507.jpg)
![sshot-4](https://user-images.githubusercontent.com/32480002/84074625-214b5480-a9d3-11ea-9aab-20b3439f7943.jpg)
![sshot-5](https://user-images.githubusercontent.com/32480002/84074626-214b5480-a9d3-11ea-854f-6d1aef8bf8b1.jpg)

**Comment by og9gjz567** [comment]
Hi, is there any chance to get the remote working? ;)

**Comment by ebaauw** [comment]
Duplicate issue.  See #4134 for integration/support progress.
