### ISSUE TITLE
innr SP 120 smart plug reset meter

### ISSUE THREAD

**Issue by wuast94** [dresden-elektronik/deconz-rest-plugin#2907]
Is there a way to Reset the kWh reading to 0 automaticly ? i hope the api can do it

**Comment by SwoopX** [comment]
This is nothing where deconz or the API can do anyhting. You have to reset the plug for that.

**Comment by wuast94** [comment]
> This is nothing where deconz or the API can do anyhting. You have to reset the plug for that.

shit ... was hoping that this is possible with api and i dont find it but then i must find a workaround for that :/ thanks :)
