### ISSUE TITLE
Devices unavailable after reboot VM 

### ISSUE THREAD

**Issue by HammerNL89** [dresden-elektronik/deconz-rest-plugin#2918]
This is basically a copy paste of my issue posted in this issue, but it was requested to create a separate one: 

Since a couple of months my Zigbee entities would become unavailable, I was able to fix the problem by just restarting Home assistant (NOT the VM). First I thought it was just a one time issue, but then the next week, the same day, my entities were unavailable. Then I realized, that I have fixed VM backup schedule running that's shutdowns my HA VM overnight, takes a backup and restarts the VM.

So then I found the issue, started googling and found other people having the same issue:

Zigbee entities not available after a reboot. (in my case, the VM)
The strange thing is however that everything 'seems' to be operating normally, with that I mean:

I can't find any errors in the deconz log
Gateway Status is connected
With the VNC viewer the network seems fine?
Just by restarting HA (NOT) the VM the problem is fixed, but that's not a solution for the long term.
Let me state that i'm not an expert, so if others could point me in the right direction where to look for errors that DO state there is a problem, please let me know. The only thing I have now is, entities shown as unavailable with a system that seems fine on first sight...

Info:
Hardware running the ConbeeII: Custom NAS (UnRaid) running Hassio in a VM
Connected to USB3: No, USB 2.0 with extension cable
deconz version: e.g. 2.05.75 
Firmware version: e.g. 26580700

![](https://user-images.githubusercontent.com/6350295/79586896-0eeb2380-80d2-11ea-8b2a-53c84c9b005c.JPG)

![](https://user-images.githubusercontent.com/6350295/79586920-15799b00-80d2-11ea-95eb-fb9d79ec0d9e.JPG)

I did some more testing and found the following:

If I turn off auto start of Deconz and reboot the VM and then manually start Deconz afterwards, there is no problem: entities are available.
So with this knowledge, how do I investigate this further? Is it a HA issue?

For the meantime I created an automation that starts the Deconz addon with a one minute delay, after HA startup.

**Comment by ebaauw** [comment]
> What's really interesting is the fact that some safeguard for starting deconz too early has been implemented if I recall correctly

Unfortunately it hasn’t.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2482

**Comment by HammerNL89** [comment]
> @HammerNL89 Thanks for all the provided details and great that you observed what's making the difference here. What's really interesting is the fact that some safeguard for starting deconz too early has been implemented if I recall correctly. However, since you're working with a VM, the stick might not be ready yet or maybe HA is overwriting those safeguards somehow.
> 
> I guess it could be valuable what's really happening when deconz is on autostart. Is deconz started through HA or seperately by systemd in your case. Would love to see a debug output with `--dbg-info=2` when stuff is non-functional.

I would like to help, but could you guide me a bit, how to enable that debug option? 

So is basically I restarted my VM to get the zigbee devices into an unavailable state, then I ssh into home assistant and can list the docker containers, but what do I do next? Or should that debug option be enabled before I reboot the vm?

![has](https://user-images.githubusercontent.com/6350295/84419388-d4f15600-ac18-11ea-9854-c73085f41e33.JPG)

**Comment by HammerNL89** [comment]
Okay, so I restarted the VM --> Zigbee devices unavailable: 
![lights](https://user-images.githubusercontent.com/6350295/84484069-8ab0b900-ac9a-11ea-8386-d357aadf3de5.jpg)
VNC view: 
![vnc](https://user-images.githubusercontent.com/6350295/84484104-94d2b780-ac9a-11ea-9b15-bef787d63edf.JPG)

Log file with --dbg-info=2:
[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4769772/deconz.log)

If you need more information, let me know.

**Comment by SwoopX** [comment]
Thanks. Now from what I see in the screenshot and in the debug log, deconz is doing just fine. The lights should be controllable by using deconz REST API only.

From my perspective, that's an issue on HA end.
