### ISSUE TITLE
Hive door sensors and active plugs. 

### ISSUE THREAD

**Issue by donpearson** [dresden-elektronik/deconz-rest-plugin#2920]
Any chance I could get the hive door sensors working with the conbee 2 deCONZ?
https://zigbee.blakadder.com/Hive_DWS003.html

Just got my cobee today hoping it would work and clearly not…

I know it works with the hive motion sensors.
https://zigbee.blakadder.com/Hive_MOT003.html

Also the hive active plugs as well, any way I can get them working?
https://zigbee.blakadder.com/Hive_1613V.html

Or am I going to have to get Zigbee2mqtt running as well, I’d rather not as I’ve just get this nice expensive £40 cobee 2 when the cheap one seems to do everything I want.

Looks like I’m going to send the cobee back and get the cheap cc2531 instead.
Thanks for your help.

**Comment by Mimiix** [comment]
I have no clue what addon you are speaking about or where that message pops up. 

However, Blakadder's site isn't maintained by DE. The official list contains supported devices. I haven't found a issue/PR on this git mentioning the hive device before. 

If you want to have a device integrated, please read this wiki page: 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by donpearson** [comment]
> I have no clue what addon you are speaking about or where that message pops up.
> 
> However, Blakadder's site isn't maintained by DE. The official list contains supported devices. The only device that should work is the motion sensor. The user requesting it confirmed it works since 0.76: #2606
> 
> If you want to have another device integrated, please read this wiki page:
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

No need to worry about the sites I gave, I know they have nothing to do with DE..
I was just using then to show the devises I’m talking about. 
I’m not asking about the motion sensor as I said In my original post I know that’s working. 
I’m talking about the door sensors.

**Comment by Mimiix** [comment]
> > I have no clue what addon you are speaking about or where that message pops up.
> > However, Blakadder's site isn't maintained by DE. The official list contains supported devices. The only device that should work is the motion sensor. The user requesting it confirmed it works since 0.76: #2606
> > If you want to have another device integrated, please read this wiki page:
> > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support
> 
> No need to worry about the sites I gave, I know they have nothing to do with DE..
> I was just using then to show the devises I’m talking about.
> I’m not asking about the motion sensor as I said In my original post I know that’s working.
> I’m talking about the door sensors.

Fair enough :)

Then you need to follow https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support  and create a request :)

**Comment by donpearson** [comment]
So I have the plugs working so no need to worry about that. 
I’m going to close this post and make a new one for the motion sensor that I can’t get connected and it’s supported, if we solve that then maybe the rest will follow. 
Thanks
