### ISSUE TITLE
deCONZ registers under 127.0.0.1 with discovery portal

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#2927]
See: https://github.com/ebaauw/homebridge-hue/issues/710

Sometimes deCONZ registers with the discovery portal with internal address `127.0.0.1` instead of the proper IP address.  I suspect it's when deCONZ is started before the IP address has been assigned.

Device
Screenshots

**Comment by SwoopX** [comment]
#2215 is related to that.

**Comment by ebaauw** [comment]
Still an issue, see https://github.com/ebaauw/homebridge-hue/issues/710

**Comment by Mimiix** [comment]
@ebaauw Even you have to stick with the templates ;)
