### ISSUE TITLE
Heiman Siren Zigbee signal repeating question

### ISSUE THREAD

**Issue by thogens** [dresden-elektronik/deconz-rest-plugin#2928]
Hi!

I have a Heiman Siren, a couple of Heiman Smoke Detectors and many Aqara Sensors in my Setup.
Interestingly the Heiman Siren does only function as repeater for the Smoke Detectors. All Aqara Sensors only connect to my Conbee 2 Stick. They do not connect to the Siren.
Any idea why the Siren only routes to the Smoke Detectors coming from the same manufacturer?! Anything I can do to fix that?
Thanks,
Thomas

**Comment by ebaauw** [comment]
Xiaomi devices don't switch routers: they stick to the parent to which they paired originally.  Reset and re-pair them close to where you want to use them, to have them select a more appropriate parent.  Note that there's a limited number of end devices that a router supports; when it's "full", the end device will select another router.
