### ISSUE TITLE
Connect deCONZ to Tradfri Gateway

### ISSUE THREAD

**Issue by emcxh35** [dresden-elektronik/deconz-rest-plugin#293]
Hi,

Is there any way to connect my Raspbee module to my existing Tradfri network?

Thanks :)

**Comment by manup** [comment]
Currently this is not possible, might be added in future versions via Touchlink, IKEA remote control.

**Comment by oleg77s** [comment]
Is it possible to do the same touchlink trick, using a round living color remote (paired with hue bridge) and existing hue bridge network?

**Comment by emcxh35** [comment]
Hi oleg77s - which trick is this?

I am happy to try any technique.

**Comment by oleg77s** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/266

**Comment by leifnel** [comment]
node-red talks over ethernet with the IKEA Hub.
https://flows.nodered.org/node/node-red-contrib-tradfri
