### ISSUE TITLE
Flash deCONZ firmware for a RaspBee II

### ISSUE THREAD

**Issue by nimric** [dresden-elektronik/deconz-rest-plugin#2934]
How should I flash deCONZ firmware for a RaspBee II? I had no success with "sudo GCFFlasher_internal -f deCONZ_RaspBeeII_0x26610700.bin.GCF".

Regards

**Comment by Mimiix** [comment]
Hi!

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

Shows how, depending on the host system.

**Comment by nimric** [comment]
HI Mimixx!

I know the page, but for my RaspBee II it was not working with the command for the old RaspBee. Therefore I was wondering if the command is a different now like for the ConBee and the ConBee II.

**Comment by Mimiix** [comment]
Hi Nimric,

can you provide me with a error?

**Comment by nimric** [comment]
It's working. Seems I did something wrong. Thanks for your time Mimiix!

**Comment by phwagner82** [comment]
Hello! 
is there a way to update the firmware in HomeAssistantOS?

Regards
Philipp
