### ISSUE TITLE
[Request device support] Support for Namron 2-channel switch (Luzense/Sunricher clone)

### ISSUE THREAD

**Issue by ArmasSamra** [dresden-elektronik/deconz-rest-plugin#2937]
@phithor added the 4-channel version of the Namron switch. It would be great to have support for the 2-channel version
https://www.elektroimportoren.no/namron-zigbee-2-kanaler-bryter-k4/4512719/Product.html?Event=searchlist

**Comment by SwoopX** [comment]
Please close this one and file a new request based on the offered template. Thanks!
