### ISSUE TITLE
Osram Smart+ Mini Switch and deCONZ

### ISSUE THREAD

**Issue by oleg77s** [dresden-elektronik/deconz-rest-plugin#294]
Just added a new Osram Smart+ Mini Switch to the deCONZ network.
![2017-11-26-145550_1824x984_scrot](https://user-images.githubusercontent.com/23496372/33241190-f57f14ba-d2d2-11e7-94d0-4c86a38dedf8.png)
And it's working out of the box: switch controls all the lights and plug in the network and it's impossible  manually configure each light, as in the case with DE switches, all switch settings are factory default
![2017-11-24 18 34 55](https://user-images.githubusercontent.com/23496372/33241196-0ecb0190-d2d3-11e7-9808-99cf397f2155.PNG)
Exactly the same switch behaviour is in the Philips Hue bridge network and besides, switch is invisible in hue bridge network, as DE ones.
Is it possible to add support for this switch to deCONZ (and homebridge-hue) 
to be able to configure it ?
Regards

P.S. Switch has a touchlink function:
![2017-11-26 18 14 54](https://user-images.githubusercontent.com/23496372/33241477-ef8c8b9c-d2d6-11e7-8ed4-f2965cc8a25f.jpg)
![2017-11-24 17 56 38](https://user-images.githubusercontent.com/23496372/33241478-f50e6400-d2d6-11e7-96d9-704f4c19a609.jpg)

**Comment by manup** [comment]
Cool, part of it can be implemented similar to IKEA remote control where the incoming group-/broadcasts are mapped to REST API button events. Question is if it is possible to to configure the switch to not reach all lights but only a group.

**Comment by oleg77s** [comment]
It's possible in native Osram app and Osram gateway network, but how to do this in deCONZ network?

**Comment by manup** [comment]
Guess we need to sniff the traffic to know what commands the OSRAM gateway sends, but good that it is possible at least.

**Comment by alvar0rodrig0** [comment]
Can I add something else to this issue to request the support of this switch? I'm also looking forward to this switch to be added to deconz.
The cluster info is already published and it is the same that I have, except for the Power Source that I have it as unknown and the SW Build ID is empty in my case.

**Comment by cristimi** [comment]
I have two of this switches as well and I am interested of using them with deconz.

**Comment by Philje123** [comment]
I've just acquired one of these cheaply.

Just updating the software on it now and gonna give it a go.

**Comment by redlegoman** [comment]
> I've just acquired one of these cheaply.
> 
> Just updating the software on it now and gonna give it a go.

How did it go?

**Comment by Philje123** [comment]
No change. It still just switches all lights on and off.

**Comment by olicooper** [comment]
Is there anything currently in development for this?

**Comment by jamestutton** [comment]
If it helps someone fix it in deconz it has been sorted in zigbee2mqtt 

https://github.com/Koenkk/zigbee-shepherd-converters/commit/ad2d5aab2c541948da965874a219922433766f00

**Comment by weltmeyer** [comment]
I would also like to see this switch working with deconz...

**Comment by olicooper** [comment]
Not stale..

**Comment by manueligno78** [comment]
Please support this device

**Comment by olicooper** [comment]
Me and @Smanar are working on adding support for the device in the REST API (we can't add support in Phoscon as it is not open source). So far I have got the buttons to output API updates but it is not finished yet. I can't guarantee support as that is up to the repo maintainers if they merge our pull requests and also if there are no hidden issues we haven't discovered yet.
Fingers crossed we can add some form of support! 🤞

**Comment by Fabian7727** [comment]
How do you even add it to the network. It’s simply not working at all in my system.

**Comment by olicooper** [comment]
Until this PR is closed https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2917 you can't use it unless you build your own version from the PR code

**Comment by Smanar** [comment]
Or if all is fine, you will it have in future deconz version in 10 days.
