### ISSUE TITLE
New Device Request: Centralite 3315 Water Sensor

### ISSUE THREAD

**Issue by cjs28** [dresden-elektronik/deconz-rest-plugin#2944]
Hello,

I see you have support for other Centralite devices but not this one. I am looking to get this one added as well.

**Clusters of the node:**
![image](https://user-images.githubusercontent.com/9389195/84604557-74eaf180-ae5c-11ea-8b24-829c20b5af9e.png)

**Node Info Panel:**
![image](https://user-images.githubusercontent.com/9389195/84604618-e3c84a80-ae5c-11ea-835f-2a2b22a82ec4.png)

**Basic cluster's attributes:**
![image](https://user-images.githubusercontent.com/9389195/84604638-05293680-ae5d-11ea-99bd-1eb167ed051a.png)

**Power Configuration:**
![image](https://user-images.githubusercontent.com/9389195/84604682-53d6d080-ae5d-11ea-9755-4536e7277b70.png)

**IAZ Zone:**
![image](https://user-images.githubusercontent.com/9389195/84604711-98626c00-ae5d-11ea-936d-353aefc6bf38.png)

Poll Control:
![image](https://user-images.githubusercontent.com/9389195/84604734-b92ac180-ae5d-11ea-8f30-8053fe16280a.png)

**Diagnostics:**
![image](https://user-images.githubusercontent.com/9389195/84604759-da8bad80-ae5d-11ea-9fe2-d2dbecee3497.png)

**OTAU:**
![image](https://user-images.githubusercontent.com/9389195/84604777-0149e400-ae5e-11ea-9405-38a917b5de8b.png)

**Comment by Mimiix** [comment]
As per request from @SwoopX , i close the issue.
