### ISSUE TITLE
Add support for Stelpro baseboard thermostat STZB402+ please

### ISSUE THREAD

**Issue by biggerfooter** [dresden-elektronik/deconz-rest-plugin#2945]
Is is possible to add support for the Stelpro baseboard thermostat STZB402+ ?

Here are the details:
![stelpro_stzb402 node info](https://user-images.githubusercontent.com/52938290/84607742-dcf10600-ae63-11ea-98cc-20750d16a17e.png)

![stelpro_stzb402  cluster identify](https://user-images.githubusercontent.com/52938290/84607749-e37f7d80-ae63-11ea-8ab0-95e4d553c6d1.png)

![stelpro_stzb402 cluster thermostat UI](https://user-images.githubusercontent.com/52938290/84607755-e7ab9b00-ae63-11ea-8618-c2ab88e7e1d7.png)
![stelpro_stzb402 cluster groups](https://user-images.githubusercontent.com/52938290/84607756-e9755e80-ae63-11ea-8f2d-41cb1982bcdb.png)

**Comment by biggerfooter** [comment]
Read info for basic cluster and thermostat cluster

![stelpro_stzb402  cluster basic REV1](https://user-images.githubusercontent.com/52938290/84609242-0b261400-ae6b-11ea-8639-8e12eaa3968c.png)
![stelpro_stzb402 cluster thermostat REV1](https://user-images.githubusercontent.com/52938290/84609247-0d886e00-ae6b-11ea-82f8-67b610a600e5.png)

**Comment by Mimiix** [comment]
As per request from @SwoopX i'll close this issue.
