### ISSUE TITLE
Device can't be deleted - SmartThings button

### ISSUE THREAD

**Issue by alaghbar** [dresden-elektronik/deconz-rest-plugin#2946]
Smarthings button did not pair properly first time. Did reset button many times. It pairs OK but no events detected. Only reports temperature and battery level. I have another identical button pairs OK.
Using deCONZ container and all other devices OK. Button is removed OK in Phoscon app. Then I manually delete the device and all its entities in home assistant. However, I think it is not completely removed in deconz. After deleting it in Phoscon, using VNC viewer, I can still see it under device named "Temperature 28", I don't see anyway to delete this entity.

When I attempt to pair it again (after resetting the button), it pairs OK in Phoscon and does appear back in Home Assistant, but no events when button pushed, double pushed or held. Please help
![button](https://user-images.githubusercontent.com/59179396/84615400-e5166900-ae96-11ea-8e08-918d92c9cd4a.png)

**Comment by Mimiix** [comment]
Hi!

Can you provide me:
deCONZ version
HA Addon version
Device Product ID (the type/productnumber)

Thanks!

**Comment by alaghbar** [comment]
Sure thing;
HA & deCONZ on docker setup so there's no HA Addon.
HA is 0.111.2
deCONZ: 2.05.77
Device: Samsung SmartThings Button / PN GP-U999SJVLEDA
Please let me know if you require any further information.
Thank you!!

**Comment by loopphoto** [comment]
I’m also having this problem where the device events don’t appear.

**Comment by Mimiix** [comment]
@loopphoto Either create a own issue with related information or continue to debug on Discord :) 

@alaghbar For some reason, i missed this issue. Can you let me know if you figured it out?

**Comment by SwoopX** [comment]
The question would be if the REST API delivers button events. If yes, it's not an issue on our side.

**Comment by alaghbar** [comment]
@Mimiix Events come OK from SmartThings Button but when name is assigned/edited in Phoscon, it is not updated in deconz portal, it keeps its initial name "Temperature 24". When it is deleted in Phsocon, it stays in deconz. I use its in docker - latest version. Otherwise, events come out OK

**Comment by Mimiix** [comment]
@alaghbar use the Rest API to change its name :) Check documentation on that ^^
