### ISSUE TITLE
Correctly paired ikea bulb not turning on and off deconz

### ISSUE THREAD

**Issue by sunsgs** [dresden-elektronik/deconz-rest-plugin#2953]
Hi All,
i've correctly paired my ikea bulb IKEA TRÅDFRI Bulb E14 WS opal 400lm Color temperature light to deconz. I can see it. I have added simply to a group, but when i try to change the brightness for example nothing is happening with the bulb. The same for on and off. All the status are correctly set also from hassio, simply the light is not moving from initial state (also if from the ui the brightness has changed)
Any tip?

**Comment by Mimiix** [comment]
Hi Sunsgs! 

This sounds like a Phoscon issue. If you agree, i can move this issue to the appropriate repository.

Thanks!
