### ISSUE TITLE
Deconz updates without new version number?

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#2958]
Hello!
That´s not a really bug, but a small question:

I´m taking updates from the site: [http://deconz.dresden-elektronik.de/raspbian/beta/?C=M;O=D](url)
The newest version there is the 2.05.77, but the date of the "last modified" changed three times until now. 
Are there changes or isn´t it nessesary to updates versions with just a newer date?

Greetings
Michael

**Comment by Mimiix** [comment]
Hi! i thought i've already replied here but no clue why i didn't.

To answer your question: Most of the time they are minor tweaks. Nothing serious AFAIK.

**Comment by Michaelnorge** [comment]
Hi.
Thank you for your answere :-))
