### ISSUE TITLE
Mark Pre-releases as Pre-releases on the Releases Page

### ISSUE THREAD

**Issue by pattyland** [dresden-elektronik/deconz-rest-plugin#2961]
Right now Pre-release are marked as "Release" on the [releases page](https://github.com/dresden-elektronik/deconz-rest-plugin/releases) which is confusing.
For example V2_05_78 is marked as "Release" but described as "beta".

**Comment by manup** [comment]
Thanks, good hint yes makes sense that beta releases marked as such &rarr; done.
