### ISSUE TITLE
Ikea Tradfri Repeater - Latency

### ISSUE THREAD

**Issue by rufinus** [dresden-elektronik/deconz-rest-plugin#2963]
I recently bought some Ikea Blinds - the work as expected. With the blinds they ship small usb plugable repeaters. (Type E1746)

I thought why not and added them to my zigbee mesh. Adding them in phoscon worked with no problems.

The problems started a few hours later. There was a noticable latency in the whole Zigbee Mesh. Aktivating a light in phoscon could take up to 6 seconds befor the light activated. No matter if the bulb had a connection via the repeater or via a other route. Sometimes the commands even doesnt execute.
the deconz gui showed nothing out of the ordinary.

A few minutes/hours after removing the repeaters the mesh was back at a normal speed.

I dont need the repeaters - so i dont have a problem with not using them - but maybe someone is searching for long latency and this may give some pointers.

**Comment by Mimiix** [comment]
Hi @rufinus !

Would you please stick to the [templates](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose) we've created? This would help others greatly in answering your question. 

I'd like to ask you to either add the details from the template in your next comment on this issue or to close this issue and start a new issue with the [templates](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose).

Thank you!

- Dennis
