### ISSUE TITLE
Nach tausch vom Conbee2, alte Config laden noch möglich?

### ISSUE THREAD

**Issue by Typ1er** [dresden-elektronik/deconz-rest-plugin#2964]
Wie kann ich bei einem neuen Conbee2 (der alte ist defekt), die Lampen wieder verbinden, muss man alle Lampen und Sensoren und Schalter neu anlernen?

Angezeigt werden sie noch in Phoscon, schalten ist nicht mehr möglich.

**Comment by manup** [comment]
Hi please keep it english here, since the issue tracker is highly international :)

You can try to load the configuration of the former ConBee II to the new one with help of the Zigbee configuration page: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Network-lost-issues

**Comment by Mimiix** [comment]
As i seen this issue been handled on TS and no further reply, it seems solved.
