### ISSUE TITLE
Paulmann Controller Modell: 371000001 SW: 1400-0001

### ISSUE THREAD

**Issue by Rambo79** [dresden-elektronik/deconz-rest-plugin#2966]
The Paulmann Controller 371000001 will be detected but controlling the connected lights is not possible.

**Comment by Mimiix** [comment]
Hi @Rambo79 !

Would you please stick to the [templates](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose) we've created? This would help others greatly in answering your question. 

I'd like to ask you to either add the details from the template in your next comment on this issue or to close this issue and start a new issue with the [templates](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose).

Thank you!

- Dennis

**Comment by Rambo79** [comment]
Made a new Device Request by template

**Comment by Mimiix** [comment]
@Rambo79 Your my hero :)
Thank you!

**Comment by Rambo79** [comment]
> @Rambo79 Your my hero :)
> Thank you!

:-) You made my day !
