### ISSUE TITLE
Paulmann WW/CW Controller Modell: 371000001 

### ISSUE THREAD

**Issue by Rambo79** [dresden-elektronik/deconz-rest-plugin#2969]
## Device

- Product name: Paulmann Controller 371000001
- Manufacturer: Paulmann Licht
- Model identifier: 371000001
- Device type:
  - [X] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

## Screenshots
<img width="544" alt="Bildschirmfoto 2020-06-19 um 07 38 26" src="https://user-images.githubusercontent.com/42409118/85100286-0f05bd80-b200-11ea-8fee-d6ca128e1e52.png">
<img width="466" alt="Bildschirmfoto 2020-06-19 um 07 37 37" src="https://user-images.githubusercontent.com/42409118/85100296-175df880-b200-11ea-8ee5-aff3fe3f7ab4.png">
<img width="324" alt="Bildschirmfoto 2020-06-19 um 07 40 48" src="https://user-images.githubusercontent.com/42409118/85100368-42484c80-b200-11ea-9dff-05e9b750c56c.png">

**Comment by SwoopX** [comment]
It should work right out of the box. Doesn't it?

**Comment by Rambo79** [comment]
I can found the controller (have 2 of them) but can‘t control the connected lights. The wirering is correct (tested with another controller)

**Comment by SwoopX** [comment]
So, when you select the `on/off` cluster and then toggle the light, it doesn't work?

**Comment by Rambo79** [comment]
@SwoopX No, nothing happens :-(

**Comment by Smanar** [comment]
And if you try the level control ?

**Comment by Rambo79** [comment]
@SwoopX The Same. My Conbee is integrated in ioBroker and i tried it with every data point. No Function at all

**Comment by Smanar** [comment]
The answer was for me ?
So even the level control cluster using transition time not working ?

**Comment by SwoopX** [comment]
Please try it directly via deconz' REST API, so not with ioBroker

**Comment by Rambo79** [comment]
@Smanar 
> The answer was for me ?
> So even the level control cluster using transition time not working ?
> 
> You have error message or no result ?

Sorry, hit the wrong name on the mobile phone display.

Again no result by controlling the level by Rest-Api :-(

It says "success" but no light goes on

**Comment by SwoopX** [comment]
This all doesn't fit together. Can you reset the light and re-pair it?

**Comment by Rambo79** [comment]
@SwoopX 
Sorry for m late response. I had to do something different the last few days. Your right. After a reset (which is a little bit complicated) and new pairing, it works. I will close the request. Thanks!!! for any help.
