### ISSUE TITLE
trouble on my - Blitzwolf temp and humidity sensor BW-IS4

### ISSUE THREAD

**Issue by rix30** [dresden-elektronik/deconz-rest-plugin#2970]
Hi, I'm newbye in deconz so I try to write clearly, thank you in advance for your help.
I've seen in other resolved issue that Blitzwolf IS4 is  supported from deconz if FW and app are updated, I've  a Conbee II updated to FW 26580700,  deconz updated too to version 2.05.77.
This is all I can see in vnc:
![image](https://user-images.githubusercontent.com/59541959/85125433-ec899980-b22b-11ea-95bd-8263852db810.png)

I can't see the device in webapp nor in home assistant. What am I supposed to do to use it?

THX Riccardo

**Comment by SwoopX** [comment]
Try re-pairing it. Might not always work on the first take. Just to prepare you: it will not show up in Phoscon.

**Comment by rix30** [comment]
Thank you SwoopX, I've tried to re-pair it a million of times, it always  appears as in the image, and nothing in home assistant, even if I force resync. I'm thinking to change way to create my thermos regulation.

**Comment by SwoopX** [comment]
Can you please read the attributes of the basic cluster? Make sure the device is awake, so e.g. take it in hand and/or warm it.

**Comment by rix30** [comment]
just yesterday may raspberry stopped working due to a SD fault, now I'm reinstalling all because my backup is too old and deconz is missing.  I'll answer here as soon as the system will be online.
Thank you

**Comment by rix30** [comment]
Here I am, with a new SD and the old configuration with the same problem. @SwoopX you've asked me to read the basic cluster, I don't know how to do, I've seen other reading it and posting in the forum, but I don't know where to see. 
Thank you

**Comment by SwoopX** [comment]
![grafik](https://user-images.githubusercontent.com/4005212/86851758-c9783a00-c0b3-11ea-8130-7d8a8ba6c01d.png)

**Comment by rix30** [comment]
I did it, I've lost cluster window, now I've found it under under. It gave this:
![image](https://user-images.githubusercontent.com/59541959/86931239-274e6580-c138-11ea-97ff-eb1705e4bafa.png)

**Comment by SwoopX** [comment]
Thanks. Now do the same when sensor search in Phoscon is active, please. The name of the node should change then.

**Comment by rix30** [comment]
YES!!! It works! Thank you a lot! Now I can see it in HA too. You rock!
I close this issue.
Riccardo

**Comment by SwoopX** [comment]
I know 😉 

Enjoy!
