### ISSUE TITLE
Paulmann RGBW light

### ISSUE THREAD

**Issue by cma-bw** [dresden-elektronik/deconz-rest-plugin#2971]
## Device

- Product name: Smarthome Zigbee Maxled RGBW Controller.
- Manufacturer: Paulmann Licht GmbH.
- Model identifier: RGBW light.
- Device type:
  - [x] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

## Problem
The controller is detected but is not working properly. Only the RGB part can be controlled.

## Screenshots

<img width="1182" alt="Screenshot 2020-06-19 at 18 39 04" src="https://user-images.githubusercontent.com/67160897/85160076-b3b6e800-b25e-11ea-861d-72b378c4cc45.png">
<img width="743" alt="Screenshot 2020-06-19 at 18 36 56" src="https://user-images.githubusercontent.com/67160897/85160652-e4971d00-b25e-11ea-8a32-183fc5ed8409.png">

**Comment by SwoopX** [comment]
> The controller is detected but is not working properly. Only the RGB part can be controlled.

Can you be a bit more specific on this part? Where?

**Comment by ebaauw** [comment]
As it only exposes a single endpoint, it would seem the controller doesn’t allow independent control of the RGB and W channels.  It probably mixes in the W channel when using colours with low saturation, or when setting colour temperature.

**Comment by cma-bw** [comment]
You're right. With increasing saturation, the RGB leds become brighter and the W leds become darker. Unfortunately the controller doesn‘t allow independent control like the FLS-PP.
Thanks for the hint.
