### ISSUE TITLE
Restoring Gateway Configuration causes "segmentation fault" and deletes all lights

### ISSUE THREAD

**Issue by xxLeoxx93** [dresden-elektronik/deconz-rest-plugin#2975]
## Describe the bug
Hello,

since I've many issues like not working switches since I updated to the latest beta (and downgraded again) I tried to resore the zigbee configuration.
However this caused a segmentation fault and deleted all my lights.
Luckily after a some tries I still got the segmentation fault by my lights were back.
It could be that the two Ikea Tradfri switches that I can't readd are causing this (see issue #2973 ).
## Steps to reproduce the behavior

"Alt" + Click on the advanced tab in Phoscon Web app -> The restored the configuration from the last stable version I had installed.

## Expected behavior

I was hoping this would fix my not responding devices since I'll not readd ~70 devices by hand.

## Screenshots
![image](https://user-images.githubusercontent.com/61089790/85221564-e3780400-b3b4-11ea-96ef-d2c2ac254dd1.png)

## Environment

 - Host system: Rasberry Pi
 - Running method: Raspbian
 - Firmware version: 26580700
 - deCONZ version: 2.05.77 
 - Device: ConBee II
 - Do you use an USB extension cable: yes

**Comment by SwoopX** [comment]
Can you please try to share a core dump?

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Enable-core-dumps-on-Raspbian

**Comment by xxLeoxx93** [comment]
> Can you please try to share a core dump?
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Enable-core-dumps-on-Raspbian

Do I need to replicate the issue afterwards? Because I'm very affraid of loosing all my lights again and not getting them back.
