### ISSUE TITLE
Hive Active Heating Receiver SLR2

### ISSUE THREAD

**Issue by peterguy04** [dresden-elektronik/deconz-rest-plugin#2978]
## Device

- Product name: Hive Active Heating
- Manufacturer: Computime
- Model identifier: SLR2
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [x] Thermostat
  - [ ] Other: 

## Screenshots

  - Endpoints and clusters of the node
![End point and clusters](https://user-images.githubusercontent.com/45408070/85296639-9d48a080-b499-11ea-9213-3570917d338f.PNG)

  - Node Info panel
![Node INFO](https://user-images.githubusercontent.com/45408070/85296649-a174be00-b499-11ea-92c7-bf7e67099664.PNG)

  - Basic Cluster attributes in the Cluster Info panel.
![05basic cluster](https://user-images.githubusercontent.com/45408070/85296657-a5084500-b499-11ea-9f6a-fd5b992ad27d.PNG)

 ## 05
![05OTAU](https://user-images.githubusercontent.com/45408070/85296737-bfdab980-b499-11ea-8380-110d485720c4.PNG)
![05thermostat 1](https://user-images.githubusercontent.com/45408070/85296741-c1a47d00-b499-11ea-935f-7212f7499b5f.PNG)
![05thermostat2](https://user-images.githubusercontent.com/45408070/85296750-c36e4080-b499-11ea-8b67-d3d274f64cf9.PNG)

## 06
![06thermostat 1](https://user-images.githubusercontent.com/45408070/85296768-c9fcb800-b499-11ea-8abb-bf487fe11813.PNG)
![06thermostat 2](https://user-images.githubusercontent.com/45408070/85296775-cbc67b80-b499-11ea-8b89-1e43a4ed2141.PNG)

## 07
![07 temp measurement](https://user-images.githubusercontent.com/45408070/85296791-d254f300-b499-11ea-9d10-c1d211d8f36f.PNG)

## 08
![08 temp measurement](https://user-images.githubusercontent.com/45408070/85296814-d97c0100-b499-11ea-8f59-3d1ec1bef601.PNG)

**Comment by Smanar** [comment]
Lol, but you have the complete collection ?

**Comment by peterguy04** [comment]
@Smanar haha yes i have a few Hive devices.

**Comment by Smanar** [comment]
I will take it, like that I will make a package

**Comment by Smanar** [comment]
We are searchaing how to act on the second relay.
Is someone have information ?

**Comment by Smanar** [comment]
@peterguy04 have sniffed the original gateway, for info

> ---------------------------------------------------------
> 
> Endpoint 6
> cluster 0201
> 
> for "on - manual"
> 
> attribute 0x001C > 0x04 = "heat"
> attribute 0x0023 > 0x01 = "Setpoint Hold On"
> 
> For "off"
> 
> attribute 0x001C > 0x00 = "off"
> attribute 0x0023 > 0x00 = "Setpoint Hold Off"
> 
> For "boost"
> 
> attribute 0x001C > 0x05 = "Emergency heating"
> attribute 0x0023 > 0x01 = "Setpoint Hold On"
> attribute 0x0024 > 0x3C = 60
> 
> ------------------------------------------------------------
> 
> Endpoint 5
> cluster 0201
> 
> for "on - manual"
> 
> attribute 0x001C > 0x04 = "heat"
> attribute 0x0023 > 0x01 = "Setpoint Hold On"
> attribute 0x0012 > 1150
> 
> For "off"
> 
> attribute 0x001C > 0x00 = "off"
> attribute 0x0023 > 0x00 = "Setpoint Hold Off"
> attribute 0x0012 > 0
> 
> For "boost"
> 
> attribute 0x001C > 0x05 = "Emergency heating"
> attribute 0x0023 > 0x01 = "Setpoint Hold On"
> attribute 0x0024 > 0x3C = 60
> attribute 0x0012 > 2400
