### ISSUE TITLE
Hive Active Heating Thermostat SLT2

### ISSUE THREAD

**Issue by peterguy04** [dresden-elektronik/deconz-rest-plugin#2979]
## Device

- Product name: Hive Active Heating Thermostat
- Manufacturer: Computime
- Model identifier: SLT2
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [x] Thermostat
  - [ ] Other: 

## Screenshots

  - Endpoints and clusters of the node
![end point and clusters](https://user-images.githubusercontent.com/45408070/85297220-64f59200-b49a-11ea-8051-fa07fd93c37a.PNG)

  - Node Info panel
![Node INFO](https://user-images.githubusercontent.com/45408070/85297242-6aeb7300-b49a-11ea-88e0-4164b01bde66.PNG)

  - Basic Cluster attributes in the Cluster Info panel.
![basic](https://user-images.githubusercontent.com/45408070/85297258-6f179080-b49a-11ea-807c-3a76b7338434.PNG)

## Other Clusters

![thermostat1](https://user-images.githubusercontent.com/45408070/85297364-91111300-b49a-11ea-82f8-552628064a7a.PNG)
![thermostat2](https://user-images.githubusercontent.com/45408070/85297369-92424000-b49a-11ea-9363-e313d9cd5562.PNG)
![OTAU](https://user-images.githubusercontent.com/45408070/85297388-98382100-b49a-11ea-8f2e-bb4a1b9088a7.PNG)
![poll control](https://user-images.githubusercontent.com/45408070/85297393-99694e00-b49a-11ea-8978-28ec8a195609.PNG)
![power config cluster](https://user-images.githubusercontent.com/45408070/85297394-9a01e480-b49a-11ea-8b50-43f93be75100.PNG)
![temp measurement](https://user-images.githubusercontent.com/45408070/85297395-9a01e480-b49a-11ea-8f79-e45da07e262a.PNG)
![thermostat user int conf](https://user-images.githubusercontent.com/45408070/85297398-9a9a7b00-b49a-11ea-807f-94b24e05330b.PNG)

**Comment by Smanar** [comment]
I take it too.
