### ISSUE TITLE
Danfoss Ally

### ISSUE THREAD

**Issue by JSteunou** [dresden-elektronik/deconz-rest-plugin#2983]
## Device

- Product name: Danfoss Ally
- Manufacturer: Danfoss
- Model identifier: eTVR0100
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [X] Thermostat
  - [ ] Other: 

## Screenshots

![grafik](https://user-images.githubusercontent.com/4005212/87411254-bdb2d900-c5c7-11ea-8e72-f82b52c2008d.png)
![2020-07-14 10_43_05-Window](https://user-images.githubusercontent.com/4005212/87410761-0027e600-c5c7-11ea-9eb4-90bae1b2de54.png)
![2020-07-14 10_42_01-Window](https://user-images.githubusercontent.com/4005212/87410862-26e61c80-c5c7-11ea-83dc-5310b9fa02d1.png)
![2020-07-14 10_42_16-Window](https://user-images.githubusercontent.com/4005212/87410868-29e10d00-c5c7-11ea-8d2b-b1f3d8b5abbe.png)
![2020-07-14 10_42_33-Window](https://user-images.githubusercontent.com/4005212/87410879-2c436700-c5c7-11ea-8587-b64310a45fa7.png)
![grafik](https://user-images.githubusercontent.com/4005212/87410920-3bc2b000-c5c7-11ea-9b2e-42c7711eff22.png)
![grafik](https://user-images.githubusercontent.com/4005212/87413749-028c3f00-c5cb-11ea-956c-1fd001c02973.png)

I do not have screenshots yet because I'm planning on buying those devices, but not owning one ATM.

**BUT** Danfoss was kind enough, through a Chief Salesman, to provide clusters specification and documentation. This is rare enough to be noted and I appreciate that from them. A good brand for the people and the workers, with good stuff.

[Draft - Zigbee Cluster Specifications Danfoss eTRV.xlsx](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4818269/Draft.-.Zigbee.Cluster.Specifications.Danfoss.eTRV.xlsx)
[Danfoss Ally™ Datasheet color.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4818270/Danfoss.Ally.Datasheet.color.pdf)

**Comment by Mimiix** [comment]
[Draft.-.Zigbee.Cluster.Specifications.Danfoss.eTRV (1).pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4818393/Draft.-.Zigbee.Cluster.Specifications.Danfoss.eTRV.1.pdf)
Sheet 1 (Commands)

**Comment by Mimiix** [comment]
Sheet 2: Attributes 
[Draft.-.Zigbee.Cluster.Specifications.Danfoss.eTRV (1)_attributes.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/4818501/Draft.-.Zigbee.Cluster.Specifications.Danfoss.eTRV.1._attributes.pdf)

**Comment by Mimiix** [comment]
If anyone actually has this device, please let us know. We lack the MAC prefix.

**Comment by zozogb** [comment]
Hello, if it helps, I have a new Danfoss Ally ZigBee. And I'm French so sorry for my English.

**Comment by Smanar** [comment]
Hello, I m french too if you have problem.
We miss some information for this device, you can find information here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

For information, someone in the dev team have buy one too, but need some time for livraison.

_Pour résumer, on aurait besoin des mêmes capture que sur le lien precedent, capture faites avec deconz._

**Comment by JSteunou** [comment]
@zozogb come on to the discord channel to talk about it if you want, I'm french too ;)

**Comment by zozogb** [comment]
Ok, @JSteunou but you seem to have the screenshot which you miss now and I do not see how I can be useful to you.

**Comment by JSteunou** [comment]
just if have some question or wanna chitchat about it ;)

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.

**Comment by JSteunou** [comment]
Victory Dance :tada:

**Comment by Mimiix** [comment]
@JSteunou I'd like a video of that ;D

**Comment by ComPeter33** [comment]
i got a Danfoss Ally radiator thermostat (prototype)
Without any manual.

How can reset device and pair it in Phoscon App (Conbee 2)

**Comment by SwoopX** [comment]
Should be something like pushing the button 10 secs or so to set it into pairing mode

**Comment by ComPeter33** [comment]
Thnx, i got my Ally thermostat connceted in DeConz and working in Domoticz
When i set the temp on the Thermostat the value changes in Domoticz

But when i set the temp in Domoticz i get this error: 

2020-08-20 15:28:12.425 (ConBee 2) onCommand called for Unit 11: Parameter 'Set Level', Level: 26.5, Hue:
2020-08-20 15:28:12.414 Status: User: competer initiated a SetPoint command
2020-08-20 15:28:12.448 Error: (ConBee 2) Connexion problem (1) with Gateway : 400

My Deconz is on a serperate PI than my Domoticz installation

What can i do to resolve this issue?

**Comment by SwoopX** [comment]
This is no deconz issue, the REST API is working here.

**Comment by dowhiletrue** [comment]
I wonder if `0x4015 External Measured Room Sensor` might be set as writable attribute in `general.xml` since [Danfoss trv.xlsx](https://github.com/Koenkk/zigbee2mqtt/files/5493076/Danfoss.trv.xlsx) states the attribute to be writable. I changed this for testing purposes in and wrote a value. The TRV does not honor the value. Does anybody know what else has to be configured in order to get an external room sensor to integrate with the TRV?

**Comment by JSteunou** [comment]
I wondered the same thing. Maybe it is just to give external measure in the
sense of outside the house temperature so the trv can adapt its logic like
the external sensor for boilers.

Le sam. 12 déc. 2020 à 10:59, dowhiletrue <notifications@github.com> a
écrit :
