### ISSUE TITLE
Niko 170-33505 

### ISSUE THREAD

**Issue by Sennevds** [dresden-elektronik/deconz-rest-plugin#2984]
## Device

- Product name: 170-33505 
- Manufacturer: Niko
- Model identifier: Connected socket outlet
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [x] Other: Connected socket(recognized as light)

## Screenshots
![image](https://user-images.githubusercontent.com/3531609/85563236-8044d680-b62d-11ea-84bb-fec28f88c5b8.png)
![image](https://user-images.githubusercontent.com/3531609/85563257-833fc700-b62d-11ea-8b30-48afaf4c44fb.png)
![image](https://user-images.githubusercontent.com/3531609/85563276-86d34e00-b62d-11ea-9b7b-8037f1bdbda2.png)
![image](https://user-images.githubusercontent.com/3531609/85563293-8a66d500-b62d-11ea-8d02-64da6d8909bc.png)
![image](https://user-images.githubusercontent.com/3531609/85563311-8dfa5c00-b62d-11ea-9071-ae48ef8642ba.png)

Is recognized as light but doens't expose the measurements as sensors (checked via postman and the deconz api)
So the request is to expose the measurements as a sensor so I can use these in Home Assistant.
If there's any information missing let me know!

**Comment by SwoopX** [comment]
@Sennevds Yeah, you're my hero! So they're finally out?! Wanted to get my hands on them for months now. Where did you buy and at what price?

**Comment by pergolafabio** [comment]
yeah, really interesting!! gonna buy those too
here for example : 

https://www.zelektro.be/slim-stopcontact-zigbee-geconnecteerd-schakelbaar.html

**Comment by Sennevds** [comment]
Ha now they have them at zelektro(normally I buy my gear there but 3 days ago they didn't had them in stock) I've bought them at gigatek.

**Comment by pergolafabio** [comment]
btw, is there also an hardware button on the Niko itself? not quite clear on the pictures... i only see a led , no button
or can you only turn them off/on with the deconz?

**Comment by Sennevds** [comment]
The LED is also a button

**Comment by pergolafabio** [comment]
Cool

**Comment by SwoopX** [comment]
But the size and the frame is a crime... I'd need 55mm instead of 45mm and I'm not sure if adapters may do the trick.

**Comment by Sennevds** [comment]
I used a standard niko frame

**Comment by SwoopX** [comment]
@Sennevds How do you pair those things? Seems I cannot get it to work...

**Comment by SwoopX** [comment]
Nvm, got a reply from their support. It's not even mentioned in the manual...

**The sequence to put the socket in pairing mode is: 3x short button press**

**Comment by pergolafabio** [comment]
Where did you buy now?

**Comment by SwoopX** [comment]
@pergolafabio electro-colli.be

Quite some extensive manufacturer specific cluster

![grafik](https://user-images.githubusercontent.com/4005212/86479491-91d45f80-bd4c-11ea-9f19-6cfd5490894e.png)

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.

**Comment by pergolafabio** [comment]
@SwoopX  @Sennevds 
look at this one : https://www.niko.eu/nl-be/artikel/122-91004
that switchs seems without a battery, seems the power is mechical with a press of a button
do you guys also tried that one?

**Comment by Sennevds** [comment]
I have it at home and it works with deconz

**Comment by pergolafabio** [comment]
seems only 4 buttons , is there no 2 button variant? 
and is there indeed no battery ? thats nice!

**Comment by Sennevds** [comment]
Only 4 buttons and no battery. The buttons are harder to push then a standard niko push switch because when you push you generate the energy needed to send out the signal(piezo effect)

**Comment by pergolafabio** [comment]
ok, but its indeed a nice switch, but maybe not interesting for kids then

**Comment by camarillla** [comment]
> ## Device
> * Product name: 170-33505
> * Manufacturer: Niko
> * Model identifier: Connected socket outlet
> * Device type:
>   
>   * [ ]  Light
>   * [ ]  Lock
>   * [ ]  Remote
>   * [ ]  Sensor
>   * [ ]  Siren
>   * [ ]  Thermostat
>   * [x]  Other: Connected socket(recognized as light)

What's the status of this request? Is it possible to get the power measurements with deconz (without using ZigbeeM2qtt)?

Please let me know.  Tanks in advance!

**Comment by swannes** [comment]
Did anyone try the Niko connected switch/double switch/dimmer yet ?
https://www.niko.eu/en/article/552-72122 https://www.niko.eu/en/article/552-72201 https://www.niko.eu/en/article/552-72101
Should be Zigbee
(yes, these are expensive devices)

**Comment by swannes** [comment]
My bad, not yet available, although I see them in some webshops
