### ISSUE TITLE
Sonoff SNZB-01

### ISSUE THREAD

**Issue by madman2143** [dresden-elektronik/deconz-rest-plugin#2990]
## Device

- Product name: Wireless Switch
- Manufacturer: Sonoff
- Model identifier: SNZB-01
- Device type:
  - [ ] Light
  - [ ] Lock
  - [x] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [x] Other: Wireless Switch

![image](https://user-images.githubusercontent.com/67551791/85951821-fe72e700-b965-11ea-8ef4-fd35e6bca0b0.png)
![image](https://user-images.githubusercontent.com/67551791/85951849-21050000-b966-11ea-926a-b588460ab3ce.png)

**Comment by madman2143** [comment]
Product Page:
https://sonoff.tech/product/smart-home-security/snzb-01

**Comment by SwoopX** [comment]
Please add the missing information as mentioned in the device request, thanks!

**Comment by madman2143** [comment]
Sorry, I'm new to this!

Are you talking about this?
![image](https://user-images.githubusercontent.com/67551791/86160117-9827c900-bb0b-11ea-97d7-de078dc6e53d.png)

**Comment by NovaGL** [comment]
Any update on this. Do you need more information?

**Comment by lbouriez** [comment]
Very interested on this switch

**Comment by SAOPP** [comment]
Hi! Guys, I just get this device, but one question, I have only two actions: double and long, and missing single click.

![image](https://user-images.githubusercontent.com/5647009/93667383-25851480-fa8e-11ea-8e11-2af9b770ad97.png)

![image](https://user-images.githubusercontent.com/5647009/93667393-2fa71300-fa8e-11ea-88ba-c4f6f39b93fa.png)

![image](https://user-images.githubusercontent.com/5647009/93667402-39c91180-fa8e-11ea-9074-c48b20b25a9f.png)

![image](https://user-images.githubusercontent.com/5647009/93667413-477e9700-fa8e-11ea-9239-da4e717fdebd.png)

Any suggestion for this situation or at current moment device is not fully supported yet?

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/93667509-2b2f2a00-fa8f-11ea-856f-722af34a947f.png)

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/93667630-2028c980-fa90-11ea-963b-172acd9566f5.png)

**Comment by Smanar** [comment]
Can you try to run deconz with log enabled, and make a short press , pls ?

**Comment by SAOPP** [comment]
If I correctly understood your question 'bout values of buttons... double 1002, long 2002 (at Home Assistant events)

**Comment by Smanar** [comment]
Ok so it seem this devices have other return value.
I have used the @SAOPP log to make the table, but will be nice if someone can test it ?

Modifications > https://github.com/Smanar/deconz-rest-plugin/commit/1b4540a35a1a089ce4a6af39eba2454d0a3fdb3c

To test the code

```
git clone --branch sonoff https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by bonelessc** [comment]
I would be very happy to test this, but I am running DeConz in docker. Is that possible?

**Comment by Smanar** [comment]
Nope, need a classic OS to compile the code.
But not in hurry.

**Comment by NovaGL** [comment]
I would like to test to but don't know how on RPI2

**Comment by pippo73** [comment]
Does it works only for snzb-01 or maybe also with 03?

**Comment by Smanar** [comment]
@pippo73 The 03 is a motion sensor ? not a switch ?

@NovaGL If you have a Rpi with a classic OS (not HA for exemple), you have the procedure on homepage https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

Just change a little for step (1- 4)
```
git clone --branch sonoff https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by NovaGL** [comment]
How do I install qmake?

**Comment by Smanar** [comment]
You have tested 
`sudo apt install deconz-dev`

**Comment by NovaGL** [comment]
Doesn't work for me, can you make a package for RPI2 and I'll test it.

**Comment by NovaGL** [comment]
I tried I built it on ubuntu but get login failed

**Comment by pippo73** [comment]
Yes @Smanar I'm talking about the motion sensor

**Comment by SAOPP** [comment]
> I tried I built it on ubuntu but get login failed

Login failed - what u r mean? U can't login into phoscon with ur creds or?

**Comment by NovaGL** [comment]
The error was misleading, it actually wasn't compiled for the right arch i believe.

Don't know what I'm doing. Tried in an ubuntu vm i can build it but don't know what arch its building for.

Any tips for compiling would be appreciated.

**Comment by Smanar** [comment]
@pippo73 this code is for the switch what is the problem with the motion sensor ? It seem work since the version 79 > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2991

@NovaGL You just need to use `sudo apt install deconz-dev` it will make the correct "environement" according to your system. If this command work, the rest will be fine

And after use the same commands than me, what is your error displayed, it can come from me, I don't test all the code.

**Comment by NovaGL** [comment]
Hi @Smanar I struggle at this stage
``sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins ``

Before I copy the file everything works fine, the moment I copy the file I can't access anything. No error

If you can tell me how to debug it I'll send you what error I can find but the logs I have dont show errors.

**Comment by SAOPP** [comment]
See what are the access rights for the new library that you compiled?

**Comment by NovaGL** [comment]
I think I was getting confused and rebooting the computer shows it not as accessible.
So it looks like it was compiled for the wrong arch when used on the PI and it shouldn't have been accessible on Ubuntu as it wasn't physically connected to it.

Is there anyway I can compile for the Raspberry PI when using Ubuntu VM.

**Comment by SAOPP** [comment]
as far as I remember, it's a universal library, I can of course be wrong, the last time I compiled a few months ago

**Comment by Smanar** [comment]
Compilation are machine specific, you can't compile on a machine and use the file on a different one.

>Before I copy the file everything works fine, the moment I copy the file I can't access anything. No error

The system freeze ? Better to close deconz before replacing the file.

**Comment by NovaGL** [comment]
I don't have a proper computer to test it on as Hyper-V doesn't do USB Passthrough and can't compile on a RPI2 so I'll have to leave this for others to test.

**Comment by pippo73** [comment]
@Smanar I've bought 5 of them, and I can connect only 2 of them. anyway I will try to ask in the 3d yo indicated me. Thank you anyway

**Comment by NovaGL** [comment]
I moved to zigbee2mqtt and these devices are working flawlessly

**Comment by Mimiix** [comment]
@NovaGL This is not a proper solution 😉

**Comment by Mimiix** [comment]
@Smanar Do we need to re-open this?

**Comment by NovaGL** [comment]
I agree this issue needs to be re-opened as it is not implemented correctly. Missing single click.

Happy to test but I just can't build it.

**Comment by SwoopX** [comment]
The current code base allows you to "fix" that on your own with a little guidance.

**Comment by NovaGL** [comment]
Awesome, can you point me in the right direction and I'll try and report back.

**Comment by SAOPP** [comment]
I can put my raspbee at official image, so maybe I can tested it...

**Comment by SwoopX** [comment]
You need to compile the current code of the offical repo. The instructions are mentioned there, in the readme.
Additionally, you need to copy file button_maps.json to the location where your database (zll.db) resides. In the json file, you cann add the missing entry which is either known or can be taken from deconz debug output.

**Comment by NovaGL** [comment]
Thanks I gave up on that cause I couldn't compile it on my RPI2

**Comment by Smanar** [comment]
@SwoopX It s an old code make before your change so for this one they don't need yet to use the button_maps.json

**Comment by Jimmy-SafeCash** [comment]
Hey guys, has this now been tested and confirmed working and will be merged into the next release?

**Comment by Smanar** [comment]
It s not tested yet ^^

**Comment by Jimmy-SafeCash** [comment]
> It s not tested yet ^^

Will it be pushed into beta branch for testing? Seems odd to have half of the sonoff range working and the other half not.

**Comment by Smanar** [comment]
PR done, but still untested.

**Comment by Jimmy-SafeCash** [comment]
> PR done, untested, but you will be able to edit the file yourself on next version, will be json file.

Excellent, I'll wait for it to be released. Good job and thanks.

**Comment by jdonofrio728** [comment]
@Smanar I just received this exact switch in the mail today and stumbled upon this thread when it didn't work. I cloned down your branch, compiled, and copied over the libde_rest_plugin.so and button_maps.json file. It didn't work for me. I still see the following logged when I do any of the button presses:

```
# Short
[INFO] - No button map for: WB01 endpoint: 0x01 cluster: 0x0006 command: 0x02 payload[0]: 000
# Double
[INFO] - No button map for: WB01 endpoint: 0x01 cluster: 0x0006 command: 0x01 payload[0]: 000
# Long
[INFO] - No button map for: WB01 endpoint: 0x01 cluster: 0x0006 command: 0x00 payload[0]: 000
```

**Comment by NovaGL** [comment]
What device are you using with the combee? Maybe you have to update button maps json

**Comment by jdonofrio728** [comment]
I'm using the ConBee 2. I copied the button maps file from Smanar's branch to the `./.local/share/dresden-elektronik/deCONZ/button_maps.json`. I guess I'm not sure if that is the right place, but its the same directory as the zll.db file.

**Comment by NovaGL** [comment]
I mean what device is the combee connected too? A raspberry Pi?

**Comment by jdonofrio728** [comment]
Oh sorry. Deconz is installed on an LXD container.

**Comment by SwoopX** [comment]
Try creating a folder called devices where your zll.db resides and copy the json file there.

**Comment by jdonofrio728** [comment]
@SwoopX  Yeah that made a difference. However the double press and the long press might be mixed up.

```
# Short
[INFO] - Button 1002 short
# Double
[INFO] - Button 1003 Long
# Long
Button 1004 double
```

if I edit the button_maps.json to switch the too like this then the log output is as expected:

```json
"sonoffOnOffMap": [
                        [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "double"],
                        [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_DOUBLE_PRESS", "Long"],
                        [1, "0x01", "ONOFF", "TOGGLE", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "short"]
                ]
```

**Comment by Smanar** [comment]
Thx, corrected on my side.

**Comment by SwoopX** [comment]
So, now with some more freedom and keyboard in front of me ;)

Manu changed the file path and obviously forgot to mention it. I found this out just yesterday myself. The path must be

`~/.local/share/dresden-elektronik/deCONZ/devices/button_maps.json`

@jdonofrio728 Glad it worked out, so the new approach already paid off.

**Comment by jdonofrio728** [comment]
I will say that even though the log messages look better, something still doesn't seem right. Home assistant (out of scope here) doesn't see this switch as a "switch", rather only detects the battery level. Deconz also only shows the same.

I expected the cluster object for On/Off or something else to be available. Perhaps I'm just misunderstanding something?

**Comment by SwoopX** [comment]
You got your ZHASwitch resource, don't you?

**Comment by jdonofrio728** [comment]
The only entity that home assistant found was the battery:

![image](https://user-images.githubusercontent.com/10515329/94729725-19bc0c80-0330-11eb-8bfd-4eb0f4111fe6.png)

**Comment by jdonofrio728** [comment]
I'm sorry, I re-read the deconz integration documentation and found out that this is working correctly. Button pushes only fire events which I am fully able to capture. Sorry about that!

**Comment by NovaGL** [comment]
Seems to be working now with the new button map which is good.

**Comment by SAOPP** [comment]
Glad to hear this.

**Comment by Jimmy-SafeCash** [comment]
What's the current status of this regarding v2.05.84 and latest FW?

Do we still require the above workaround? For me, the switch does not work at all via the normal method. It is seen by phoscon but never registers and event in developer listening tab.

**Comment by SAOPP** [comment]
Not working with 84 too.

**Comment by SAOPP** [comment]
Ony like as before, 1002 double, and long 1003 events.

**Comment by Jimmy-SafeCash** [comment]
> Only like as before, 1002 double, and long 1003 events.

I cannot see any events in HA when listening to deconz_events :/

**Comment by SAOPP** [comment]
Try to reconnect the device, because initially there was no only a the single click event, double and long clicks should work.

**Comment by Jimmy-SafeCash** [comment]
> Try to reconnect the device, because initially there was no only a the single click event, double and long clicks should work.

I've removed and added 3 times with no difference. Not sure what I'm doing wrong.

**Comment by SAOPP** [comment]
Strange, what the stick u have?

**Comment by Jimmy-SafeCash** [comment]
> Strange, what the stick u have?

Conbee II, RPi 4, Docker

**Comment by SAOPP** [comment]
@SwoopX @Smanar guys, could u please clarify this situation with this device? Thanks in advance!

**Comment by Mimiix** [comment]
@SAOPP @Jimmy-SafeCash As far as i can see, it is added properly. Tagging Swoop won't help, he didn't integrate it.

**Comment by adamkanovak** [comment]
I have checked with the latest HA deconz addon with version 2.05.84. Short button press is still not recognized.

**Comment by NovaGL** [comment]
Using the button map file works maybe update your button map and try again

**Comment by SwoopX** [comment]
The change will come with .85 Why does nobody read the release notes, it's not mentioned there.

**Comment by SAOPP** [comment]
Thanks buddy, I didn't read and know it. I thought these fixes should have been at 83 or 84... okay. So wait for 15th October. :)

**Comment by Jimmy-SafeCash** [comment]
Have now updated to 85 and re-added the switch. Still not working for me. Listening to deconz_events shows nothing - for any of my sensors (but they still work). Any ideas why the switch doesn't? It used to work on double press and long press (not single), but now nothing at all.

**Comment by Jimmy-SafeCash** [comment]
> Thanks buddy, I didn't read and know it. I thought these fixes should have been at 83 or 84... okay. So wait for 15th October. :)

Have now updated to 85 and re-added the switch. Still not working for me. Listening to deconz_events shows nothing for any of my sensors (but they still work). Any ideas why the switch doesn't? It used to work on double press and long press (not single), but now nothing at all. It also used to show in events.

I can confirm that all other sonoff sensors work fine.

**Comment by SwoopX** [comment]
I do not see any apparent reason why it shouldn't work. Can you share some deconz logs which include the button presses?

**Comment by Jimmy-SafeCash** [comment]
> I do not see any apparent reason why it shouldn't work. Can you share some deconz logs which include the button presses?

Thanks @SwoopX for the prompt reply. Here are my logs:

`23:50:01:032 GW firmware version: 0x26660700
23:50:01:032 GW firmware version is up to date: 0x26660700
23:50:08:837 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0406 command: 0x0A payload[0]: 000
23:50:08:837 ZCL attribute report 0x0017880106F4F8F9 for cluster: 0x0406, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:50:25:112 New websocket 192.168.2.40:51170 (state: 3)
23:50:54:971 Current channel 15
23:50:54:979 Device TTL 836 s flags: 0x7
23:51:26:761 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0406 command: 0x0A payload[0]: 000
23:51:26:761 ZCL attribute report 0x0017880106F4E208 for cluster: 0x0406, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:51:26:845 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0400 command: 0x0A payload[0]: 000
23:51:26:845 ZCL attribute report 0x0017880106F4E208 for cluster: 0x0400, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:51:30:306 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0402 command: 0x0A payload[0]: 000
23:51:30:306 ZCL attribute report 0x0017880106F4F8F9 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:51:54:967 Current channel 15
23:51:54:975 Device TTL 776 s flags: 0x7
23:52:36:484 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0402 command: 0x0A payload[0]: 000
23:52:36:484 ZCL attribute report 0x0017880106F4E208 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:52:39:063 [INFO] - No button handler for: RWL021 endpoint: 0x02 cluster: 0x0001 command: 0x0A payload[0]: 021
23:52:39:064 ZCL attribute report 0x0017880104F32359 for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:52:54:959 Current channel 15
23:52:54:967 Device TTL 716 s flags: 0x7
23:53:12:460 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0406 command: 0x0A payload[0]: 000
23:53:12:460 ZCL attribute report 0x0017880106F4D4F9 for cluster: 0x0406, ep: 0x02, frame control: 0x08, mfcode: 0x0000
23:53:12:555 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0400 command: 0x0A payload[0]: 000
23:53:12:555 ZCL attribute report 0x0017880106F4D4F9 for cluster: 0x0400, ep: 0x02, frame control: 0x08, mfcode: 0x0000
`

The device is added via phoscon and shows as it always has. I have added the button_maps.json in the /device folder

**Comment by Jimmy-SafeCash** [comment]
Update: The switch is connected to the network. When I press the button the VNC map shows the switch blinking blue and green.

deconz_events in HA shows nothing and never has (no matter which sensor I activate). 

Latest logs when spamming button presses:

`22:29:32:390 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0402 command: 0x0A payload[0]: 000
22:29:32:390 ZCL attribute report 0x0017880106F4F8F9 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:29:33:961 Current channel 15
22:29:33:969 Device TTL 5639 s flags: 0x7
22:29:39:220 [INFO] - Button 1002 short
22:29:42:004 [INFO] - Button 1002 short
22:29:45:960 [INFO] - No button handler for: TH01 endpoint: 0x01 cluster: 0x0402 command: 0x0A payload[0]: 000
22:29:45:960 ZCL attribute report 0x00124B002228CA84 for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000
22:29:46:151 [INFO] - Button 1003 long
22:29:53:344 sensor 2 (SML001): disable presence
22:29:53:548 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0406 command: 0x0A payload[0]: 000
22:29:53:548 ZCL attribute report 0x0017880106F4ECA3 for cluster: 0x0406, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:30:13:926 [INFO] - Button 1002 short
22:30:15:927 [INFO] - Button 1004 double
22:30:16:941 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0406 command: 0x0A payload[0]: 000
22:30:16:941 ZCL attribute report 0x0017880106F4D4F9 for cluster: 0x0406, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:30:17:031 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0400 command: 0x0A payload[0]: 000
22:30:17:031 ZCL attribute report 0x0017880106F4D4F9 for cluster: 0x0400, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:30:18:366 [INFO] - Button 1002 short
22:30:18:530 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0400 command: 0x0A payload[0]: 000
22:30:18:530 ZCL attribute report 0x0017880106F4D4F9 for cluster: 0x0400, ep: 0x02, frame control: 0x18, mfcode: 0x0000
22:30:19:225 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0400 command: 0x0A payload[0]: 000
22:30:19:225 ZCL attribute report 0x0017880106F4F8F9 for cluster: 0x0400, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:30:20:792 [INFO] - Button 1004 double
22:30:24:050 [INFO] - Button 1002 short
22:30:27:196 [INFO] - Button 1002 short
22:30:31:694 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0402 command: 0x0A payload[0]: 000
22:30:31:694 ZCL attribute report 0x0017880106F4E208 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:30:33:958 Current channel 15
22:30:33:966 Device TTL 5579 s flags: 0x7
22:31:20:908 [INFO] - No button handler for: RWL021 endpoint: 0x02 cluster: 0x0001 command: 0x0A payload[0]: 021
22:31:20:908 ZCL attribute report 0x0017880104F32359 for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:31:25:859 [INFO] - No button handler for: TH01 endpoint: 0x01 cluster: 0x0405 command: 0x0A payload[0]: 000
22:31:25:859 ZCL attribute report 0x00124B002228CA84 for cluster: 0x0405, ep: 0x01, frame control: 0x18, mfcode: 0x0000
22:31:33:968 Current channel 15
22:31:33:976 Device TTL 5519 s flags: 0x7
22:31:47:732 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0402 command: 0x0A payload[0]: 000
22:31:47:732 ZCL attribute report 0x0017880106F4D4F9 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:31:53:383 [INFO] - Button 1002 short
22:32:33:960 Current channel 15
22:32:33:969 Device TTL 5458 s flags: 0x7
22:32:40:047 dev /dev/ttyAMA0
22:32:40:047 GW firmware version: 0x26660700
22:32:40:047 GW firmware version is up to date: 0x26660700
22:33:05:271 [INFO] - No button handler for: RWL021 endpoint: 0x02 cluster: 0x0001 command: 0x0A payload[0]: 021
22:33:05:271 ZCL attribute report 0x0017880106A7F62F for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000
22:33:17:495 [INFO] - No button handler for: SML001 endpoint: 0x02 cluster: 0x0402 command: 0x0A payload[0]: 000
22:33:17:495 ZCL attribute report 0x0017880106F4ECA3 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000
`

**Comment by Jimmy-SafeCash** [comment]
Fixed! For some reason when I had added the switch it had created a light group with the same switch ID? I deleted the light group, reloaded the integration and bingo, it worked.

**Comment by SAOPP** [comment]
Guys 86th version, any events is not presents :(

**Comment by SwoopX** [comment]
Please check out the Phoscon beta repository for your question. Phoscon is just another REST API client, the switch itself is fully supported.

**Comment by Smanar** [comment]
This device don't have group capabilities, it s possible to make group with it in phoscon ?

**Comment by SwoopX** [comment]
I wouldn't place a sure bet on it yet. However, I cannot check it as I don't have any such device.

**Comment by carloaugx** [comment]
Confirm same issue;
SNZB-01 recognized with deconz 2.06.00 / 11/15/2020
Raspbee 2 Firmware Version: 26660700

But cannot be added to an existing group as available switch.

**Comment by SwoopX** [comment]
You need to do it via the old webapp.

**Comment by carloaugx** [comment]
Thanks @SwoopX, but what exact version I need to use of deconz?
![image](https://user-images.githubusercontent.com/47906351/100498874-95d2a500-3165-11eb-9242-40b222c7067b.png)

**Comment by SwoopX** [comment]
It's not a version thing. Your screenshot is from Phoscon and not the old webapp.

Iirc, you reach the old webapp via http://YOUR_IP_ADDRESS/login.html
Username id: delight

**Comment by carloaugx** [comment]
Great @SwoopX it works! Thanks a lot for your help.

**Comment by riyas1980** [comment]
> It's not a version thing. Your screenshot is from Phoscon and not the old webapp.
> 
> Iirc, you reach the old webapp via http://YOUR_IP_ADDRESS/login.html
> Username is: delight

I have the same issue. It's detected by phoscon but I can't use it. I've tried to follow your suggestion by using the old webapp but it's not connecting. I am using raspberry pi 4 with Hassio. Can you please help me how to do that ?

**Comment by TadFocus** [comment]
hello, I´m the same issue as @riyaas1980, please help

**Comment by rudak** [comment]
I have a result after pairing it with `Conbee II` on `Jeedom`

```json
{
    "22": {
        "config": {
            "battery": 100,
            "group": "2",
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "822d1c3c54107d08a8e4d755eddd8df8",
        "lastseen": "2021-02-03T18:59Z",
        "manufacturername": "eWeLink",
        "mode": 1,
        "modelid": "WB01",
        "name": "WB01 22",
        "state": {
            "buttonevent": 2002,
            "lastupdated": "2021-02-03T18:14:10.812"
        },
        "swversion": "20200718",
        "type": "ZHASwitch",
        "uniqueid": "00:12:4b:00:1f:66:18:aa-01-0006"
    }
}
```
Only the double clic is recognized... lol

**Comment by KMDobrev** [comment]
> Hi guys
> I have a SNZB-01 that i try to get to work with the phoscon app, at the moment i use a win10 PC.
> For me in deCONZ everything looks fine since the new version 86. In Debugview i see that the events are printed out correct:
> [1248] 19:37:50:010 [INFO] - Button 1002 short
> [1248] 19:37:52:487 [INFO] - Button 1004 double
> [1248] 19:38:00:549 [INFO] - Button 1003 long
> 
> In Phoscon the switch is detected but i can not add it to a group

I am having the same problem. Sorry, I couldn't find a solution.

**Comment by TadFocus** [comment]
For me after last update all works ;)

> hello, I have the same issue as @riyas1980, please help @SwoopX
> But my phoscon didn´t detect it.

Everything works for me after the last update

**Comment by KMDobrev** [comment]
> > hello, I have the same issue as @riyas1980, please help @SwoopX
> > But my phoscon didn´t detect it.
> 
> Everything works for me after the last update

What is the update version?

**Comment by FreshJonte** [comment]
> > > hello, I have the same issue as @riyas1980, please help @SwoopX
> > > But my phoscon didn´t detect it.
> > 
> > 
> > Everything works for me after the last update
> 
> What is the update version?

Having the same issue. Any update?

**Comment by sunshineautomate** [comment]
Thanks to the devs for looking at this.
Same issue, Alot of people will be buying this Sonoff gear as their zigbee implementation is decent. Hoping for a resolution.

**Comment by chatainsim** [comment]
Same issue here, unable to include switch.
![image](https://user-images.githubusercontent.com/1167931/119725322-1998f000-be70-11eb-90eb-2d84ec595402.png)

**Comment by Smanar** [comment]
Hello, the device is not correclty included.
This device don't support mesh for inclusion, try to include it close to the conbee, and after move it at definitive place.

**Comment by Smanar** [comment]
The device is not correclty included.
The powered one don't support mesh for inclusion, can you try to include this one close to the conbee ?

Press button during inclusion, to prevent it going to sleep.

**Comment by chatainsim** [comment]
> 
> 
> yours devices are not correclty included.
> The powered one don't support mesh for inclusion, can you try to include this one close to the conbee ?
> 
> Press button during inclusion, to prevent it going to sleep.

I've tried to include at less than 2 meter with the same issue.
Tried to press button but nothing help. I've already included two ZBMIINI and one xiaomi aquara switch with success.

**Comment by Smanar** [comment]
Wired device on 220V.

Click on the first circle, you will have a popup, if you click on squares you can resend command to the device, try with the command with 'descriptor", it will enable the second circle.

Problem, the device need to be awake when you make the request. And idk how to do  with this device, use it or press shortly the reset button.

**Comment by chatainsim** [comment]
It's both battery powered devices, no 220v.
I'll try the descriptor command tomorrow I think.
Thanks

**Comment by chatainsim** [comment]
I've managed to add one of the two switchs but still struggling with the second.

**Comment by Smanar** [comment]
Battery are good too ?

**Comment by chatainsim** [comment]
Battery are new. Yes, so far it's the only device with this issue.
I've, for now, only two ZBMIINI and one Xiaomi aquara switch.
I will try with router CC2530+CC2591 soon and some more xiaomi sensor.
