### ISSUE TITLE
Sonoff SNZB-03

### ISSUE THREAD

**Issue by madman2143** [dresden-elektronik/deconz-rest-plugin#2991]
## Device

- Product name: Sonoff SNZB-03
- Manufacturer: Sonoff
- Model identifier: SNZB-03
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [x] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

## Screenshots

![image](https://user-images.githubusercontent.com/67551791/85955282-bb247280-b97d-11ea-88a3-d454756f5f0d.png)
![image](https://user-images.githubusercontent.com/67551791/85955296-cecfd900-b97d-11ea-83a3-5f371417bcc4.png)

**Comment by madman2143** [comment]
Product Page:
https://sonoff.tech/product/smart-home-security/snzb-03

**Comment by SwoopX** [comment]
Please add the missing information as mentioned in the device request, thanks!

**Comment by madman2143** [comment]
![image](https://user-images.githubusercontent.com/67551791/86160337-e1781880-bb0b-11ea-8b7e-af47ca0dd0b6.png)

**Comment by SwoopX** [comment]
The IAS Zone cluster is still missing.

**Comment by GeospatialDaryl** [comment]
Hi devs - thanks so much.  I'm also looking to use this device.  I went to supplement this request but it looks like the screenshots above include the (1) Cluster Info panel, (2) Node Info panel, and the supplemental screenshot [(3)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2991#issuecomment-651950941) has the IAS Zone information. 
![image](https://user-images.githubusercontent.com/5481509/86986773-53261700-c149-11ea-98d4-e8ad10ebaebe.png)

I'm a new user, but wanted to help.  Can you indicate what info is still needed, and where in the codebase I can find the device definition files?  I perused the source but didn't find it.  I'd like to contribute PR.

**Comment by GeospatialDaryl** [comment]
![image](https://user-images.githubusercontent.com/5481509/86986955-bf087f80-c149-11ea-9522-b5e0c89af873.png)

![image](https://user-images.githubusercontent.com/5481509/86986849-7f419800-c149-11ea-9109-154e4be21a1f.png)

**Comment by SwoopX** [comment]
![grafik](https://user-images.githubusercontent.com/4005212/86851758-c9783a00-c0b3-11ea-8130-7d8a8ba6c01d.png)

Select the IAS zone cluster in your case and scroll down for the read button. Make sure the device is awake, so trigger it's function. The button must be pressed 1-2 seconds afterwards.

**Comment by GeospatialDaryl** [comment]
Thanks for the update - and the clear instructions.   I can get the IAS zone cluster panel up, but can't get the read button to populate any of the attributes.  I've observed the network object on the gui blinking red on the left-hand button, but even pressing the reset/join button on the device and then re-querying with the read button hasn't returned any info.
![image](https://user-images.githubusercontent.com/5481509/87221258-6b4f8f00-c31f-11ea-96f2-4692d7c8aad3.png)

Thanks for the great instructions and I'll continue to experiment with trying to poll the Sonoff device.

**Comment by GeospatialDaryl** [comment]
Again - thanks for your patience, clear instructions, and help.
![image](https://user-images.githubusercontent.com/5481509/87221299-c41f2780-c31f-11ea-931a-8793b736cd0a.png)

**Comment by cllatser** [comment]
Good morning, I make my contribution to this sensor. When it detects movement, the check is set to Alarm 1 and in the IAS Zone cluster the zone status parameter changes to 0x0001.

Thank you so much.
![SNZB-03 Basic Cluster](https://user-images.githubusercontent.com/65849393/87303259-2ab86700-c513-11ea-966d-32606f42c090.jpg)
![SNZB-03 IAS Zone Motion Detected](https://user-images.githubusercontent.com/65849393/87303270-3015b180-c513-11ea-83ee-15fbcfc86568.jpg)
![SNZB-03 IAS Zone Motion NO Detected](https://user-images.githubusercontent.com/65849393/87303274-3146de80-c513-11ea-925b-b285eb5619e1.jpg)
![SNZB-03 Indenty Cluster](https://user-images.githubusercontent.com/65849393/87303280-33a93880-c513-11ea-9729-4192e953e4c4.jpg)
![SNZB-03 Power Configuration Cluster](https://user-images.githubusercontent.com/65849393/87303282-34da6580-c513-11ea-96f8-178b5e485910.jpg)

**Comment by SwoopX** [comment]
Yes, thanks. That's what I needed.

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.

**Comment by pippo73** [comment]
> Closing this as device is now supported with .79 beta.

Hi all, 
I've bought 5 sensors. I don't know why only 2 of them are connected.
I've tried to connect the other 3 in the same way but it does not work. 
What should I try? are there any magical thing to make it work?

**Comment by Mimiix** [comment]
@pippo73 Feel free to open a own Issue (User question).

**Comment by SwoopX** [comment]
PR is already prepared.

**Comment by pippo73** [comment]
@Mimiix ok, I will

> PR is already prepared.

Sorry @SwoopX what does it mean?

**Comment by Jimmy-SafeCash** [comment]
This is now working in 2.05.84 but it doesn't show within Phoscon App (just as events in HA).

Furthermore, I'm pretty underwhelmed by it compared to a Hue motion sensor. I guess it's to be expected with such a cheap price... Shame. (hoping that it can be improved through better integration with deconz perhaps?)

**Comment by SwoopX** [comment]
Deconz is not Phoscon. If its missing there, feel free to raise it in the Phoscon repo.

What better integration in deconz do you expect? It is done and you get what you paid for.

**Comment by Jimmy-SafeCash** [comment]
> Deconz is not Phoscon. If its missing there, feel free to raise it in the Phoscon repo.
> 
> What better integration in deconz do you expect? It is done and you get what you paid for.

Yes, perhaps should have left Phoscon out as it's not related (but thought it would be useful for the many people who will be using it).

I'm not expecting anything, just stating that for my setup the sensor doesn't work that well. I wasn't sure whether that was due to preliminary support in deconz that will be enhanced, or whether it is just symptomatic of the device and therefore nothing can be done. From your response, I take it's the latter.

**Comment by SwoopX** [comment]
It's unfortunately not too uncommon that devices do not work too well or differently than expected. And than mainly happens for cheaper devices. I specifically recal the Hive motion sensor here...

If you could be a bit more elaborate on hat the device does (or doesn't do), we might judge if it is device related.

**Comment by Jimmy-SafeCash** [comment]
> It's unfortunately not too uncommon that devices do not work too well or differently than expected. And than mainly happens for cheaper devices. I specifically recal the Hive motion sensor here...
> 
> If you could be a bit more elaborate on hat the device does (or doesn't do), we might judge if it is device related.

Sure. My only comparison is with the Hue Sensor. Compared to the Hue sensor the Sonoff is a lot less reliable. Motion is typically not detected as well (can walk past sometimes and nothing happens, other times fine), the same is witnessed when I have a no motion automation e.g. "2 mins", it doesn't seem to fire reliably. The Hue never skips a beat on that front. 

Wondering if the reset time of the firing of events can be adjusted?

**Comment by damajor** [comment]
I have some trouble with these devices.

Here are the info:
![image](https://user-images.githubusercontent.com/1475820/99161000-a870c700-26ed-11eb-999e-114c02405b75.png)
![image](https://user-images.githubusercontent.com/1475820/99160970-6d6e9380-26ed-11eb-8e9b-f1786df7cc08.png)
![image](https://user-images.githubusercontent.com/1475820/99160984-7b241900-26ed-11eb-89c7-1f8357f049cb.png)
![image](https://user-images.githubusercontent.com/1475820/99160989-88410800-26ed-11eb-81f7-adb348fa7e95.png)
![image](https://user-images.githubusercontent.com/1475820/99160991-90994300-26ed-11eb-926a-6b17db442000.png)
![image](https://user-images.githubusercontent.com/1475820/99160996-98f17e00-26ed-11eb-86af-19507a3c38d1.png)

And a second one (the cluster data seems to be the same as the first one):
![image](https://user-images.githubusercontent.com/1475820/99161044-1cab6a80-26ee-11eb-9150-2e9e61909da9.png)

**Comment by Thoky81** [comment]
I would like to ask if somebody else have an following issue with the Sonoff Zigbee motion sensors. I have two of them in different rooms for about 2 weeks and I have realized that they trigger motions it selfs almost periodically. It doesn't matter if is night or day, one of them is triggering exactly every 1,5 hour and the other one every 2 hours. I am using several Aqara Motion sensors too but without this strange behavior. The connection in deconz is green line therefore the issue must be somewhere else.

![image](https://user-images.githubusercontent.com/27979225/103130384-cb06e000-469c-11eb-8467-2ec3d8ef5ba5.jpeg)

**Comment by damajor** [comment]
I just checked mine and I got a simillar behavior. The sensor seems to be
unstable and fire event when there is nothing to detect.
I cannot test much now but I think SonOff stuff is not very good quality.

>

**Comment by Thoky81** [comment]
@damajor I agree with you. Another magical thing is the blind time which in my case is 10 min! If somebody have any idea how to deal with this It would be great. Thanks

**Comment by SwoopX** [comment]
Can you guys please open a separate issue for that? What you experience has nothing to do with the initial device support.

Please take note that we'd require some logs catching this automatic trigger, occurring every 1.5hrs.
