### ISSUE TITLE
Hue not set correctly

### ISSUE THREAD

**Issue by willem4ever** [dresden-elektronik/deconz-rest-plugin#3]
Not sure if this has to do with rest-plugin or deconz itself, or maybe just the ballast-pp. Anyway here is the issue. I send bri, hue and sat to the bridge using the rest api. All parameters are acknowledged with success, however the ledstrip shows the wrong colour. Sending just the single parameter with the hue value sets the colour right. The behaviour seems only to apply to ballasts, philips hue spots seems to respond fine. 

Using The colour control cluster in the deconz guy and doing an exec enhanced move to hue sets the colour also right in one go, but I guess this is comparable with just sending  a hue command thru the rest api.

**Comment by willem4ever** [comment]
Any news here ?

**Comment by willem4ever** [comment]
disappointing there is still no update for this ....

**Comment by dwaldhans** [comment]
Hello there!

I just found this thread because I am having exactly the same problem with my FLS-PP devices. Are there any news on this bug?

Kind regards,
David

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
