### ISSUE TITLE
HEIMAN RC-EM

### ISSUE THREAD

**Issue by cllatser** [dresden-elektronik/deconz-rest-plugin#3004]
## Device

- Product name: HEIMAN RC-EM
- Manufacturer: ETIGER
- Model identifier: RC-EM
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [X] Other: Remote Alarm

## Screenshots
![HEIMAN RC-EM](https://user-images.githubusercontent.com/65849393/86264379-b997bc00-bbc2-11ea-94b0-b3bf19bdcc9a.jpg)
![HEIMAN RC-EM-1](https://user-images.githubusercontent.com/65849393/86264398-c0beca00-bbc2-11ea-9a1e-6a35e15bcccd.jpg)
![HEIMAN RC-EM-2](https://user-images.githubusercontent.com/65849393/86264399-c3212400-bbc2-11ea-8ef3-efe848033245.jpg)
![HEIMAN RC-EM-3](https://user-images.githubusercontent.com/65849393/86264412-c6b4ab00-bbc2-11ea-9542-f4e167494e6a.jpg)
![HEIMAN RC-EM-4](https://user-images.githubusercontent.com/65849393/86264415-c87e6e80-bbc2-11ea-9e4e-dd91ae3c4346.jpg)
![HEIMAN RC-EM-5](https://user-images.githubusercontent.com/65849393/86264465-d7fdb780-bbc2-11ea-876e-c068baabf2f4.jpg)
![HEIMAN RC-EM-6](https://user-images.githubusercontent.com/65849393/86264477-daf8a800-bbc2-11ea-9a07-352ba0a4eaf7.jpg)
![HEIMAN RC-EM-7](https://user-images.githubusercontent.com/65849393/86264482-dcc26b80-bbc2-11ea-8413-e6985366dc0c.jpg)
![HEIMAN RC-EM-8](https://user-images.githubusercontent.com/65849393/86264487-ddf39880-bbc2-11ea-8729-433217cf414d.jpg)

**Comment by SwoopX** [comment]
You are aware that this no regular remote but for steering security gateways? And it will especially not work if deconz or your middleware goes down.

**Comment by cllatser** [comment]
Yes I know, I have a small flat. I don't need high security. I started recently and now I have everything connected to the Conbee II. I bought this because the seller's website sold it as the Heiman RS1RC. I did not want to put an RF bridge. Thank you very much.

https://es.aliexpress.com/item/32975159931.html?spm=a2g0s.9042311.0.0.501e63c0274yWo

Note: I have all the sensors connected directly to the Conbee II and the Conbee II to the Rpi4 and the Rpi4 and router lte to the UPS, so I would just go without an alarm if the Rsi4 failed :)

**Comment by SwoopX** [comment]
What do you plan to do with it anyway?

**Comment by cllatser** [comment]
Simply that each button has an event. And then I in Node-red will assign them to the control panel.

**Comment by SwoopX** [comment]
Alright, just wanted to set expectations correctly. Hope it works the same way as the other remote...

**Comment by cllatser** [comment]
You will make me happy. Thank you very much.

**Comment by SwoopX** [comment]
For the remote to properly join, the coordinator has to be extended by "IAS ACE" cluster manually in deconz GUI. For that, go to _Edit -> Network settings -> Endpoints_ (or press F9 -> Endpoints) and add `0x0501` to the `in clusters` of endpoint 0x01.

grafik

After successful join, the device should send IAS ACE commands on all its buttons as below:

**Top button**: Arm Mode - Arm Day/Home Zones Only -> translates to 1001
**Right button**: Arm Mode - Disarm -> translates to 2001
**Bottom button**: Command - Emergency -> translates to 3001
**Left button**: Arm Mode: Arm All -Zones -> translates to 4001

**Comment by cllatser** [comment]
Hello, I was away from home. I already tried before opening this incident the cluster 0x0501 and it did not send me any event. Do I have to wait for an update?

**Comment by SwoopX** [comment]
yes, what else?

**Comment by cllatser** [comment]
Excuse my English. I have already put the 0x0501 in "in clusters". I have paired the controller with Phoscon as a switch. But I see neither in HA nor in Node-Red any control event. Do I have to wait for the next version of deconz or would it already have to work? Thank you very much.
![HEIMAN RC-EM GIT](https://user-images.githubusercontent.com/65849393/86923199-04b74f00-c12e-11ea-895b-c8e55fb0fbc1.jpg)

**Comment by SwoopX** [comment]
I have updated the codebase to handle it in future. That has not yet been merged and a new version hasn't been released. The comment I added is just a set of prerequisites and explains what to expect.

**Comment by cllatser** [comment]
Thank you very much. :)

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.

**Comment by Xam54580** [comment]
> Excuse mon anglais. J'ai déjà mis le 0x0501 dans "en clusters". J'ai couplé le contrôleur avec Phoscon en tant que commutateur. Mais je ne vois ni dans HA ni dans Node-Red aucun événement de contrôle. Dois-je attendre la prochaine version de deconz ou est-ce que cela devrait déjà fonctionner? Merci beaucoup.
> ![HEIMAN RC-EM GIT](https://user-images.githubusercontent.com/65849393/86923199-04b74f00-c12e-11ea-895b-c8e55fb0fbc1.jpg)

Hello did you manage to make it work? I have the same problem
