### ISSUE TITLE
Namron 1CH K4 (Rebrand of Sunricher SR-ZG9001K4-DIM)

### ISSUE THREAD

**Issue by MoonguardGITHUB** [dresden-elektronik/deconz-rest-plugin#3006]
## Device

- Product name: Namron 1CH K4
- Manufacturer: Namron AS
- Model identifier: 4512702
- Device type:
  - [ ] Light
  - [ ] Lock
  - [x] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

Namron is re-brand of this product:

https://www.sunricher.com/single-color-wall-mounted-2-groups-zigbee-push-button-remote-sr-zg9001k4-dim.html

## Screenshots
![image](https://user-images.githubusercontent.com/67728863/86324772-5ac45800-bc3f-11ea-896a-6f2edb82372b.png)
![image (1)](https://user-images.githubusercontent.com/67728863/86324861-7b8cad80-bc3f-11ea-85c3-e6759c6113b7.png)

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.
