### ISSUE TITLE
New device EcoDim 8 button wall remote

### ISSUE THREAD

**Issue by KekieM** [dresden-elektronik/deconz-rest-plugin#3009]
![image](https://user-images.githubusercontent.com/54375425/86387961-39da2200-bc94-11ea-8a33-d021ca255627.png)

- Product name:  ED-10015
- Manufacturer: EcoDiM
- Model identifier: ED-10015
- Device type:
  - [ ] Light
  - [ ] Lock
  - [X ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

https://www.ecobright.nl/z-wave-wandschakelaar/z-wave-wandschakelaar-draadloos-zwart-4-zones/

## Screenshots

![image](https://user-images.githubusercontent.com/54375425/86384990-d3530500-bc8f-11ea-98eb-afa95e709a95.png)
![image](https://user-images.githubusercontent.com/54375425/86385056-f087d380-bc8f-11ea-936f-d777b3ac232d.png)
![image](https://user-images.githubusercontent.com/54375425/86385089-03020d00-bc90-11ea-9634-4d545d458ca9.png)
![image](https://user-images.githubusercontent.com/54375425/86385131-12815600-bc90-11ea-8c81-6aeca070b4e6.png)
![image](https://user-images.githubusercontent.com/54375425/86385195-2c229d80-bc90-11ea-834a-cc4520e2b371.png)

**Comment by Sjonnie2018** [comment]
You're linking to the Z-wave version of the switch. For those interested this is the link to the ZigBee version: https://www.ecobright.nl/zigbee-wandschakelaar/zigbee-wandschakelaar-draadloos-zwart-4-zones/

**Comment by SwoopX** [comment]
Can you please read the attributes of the power configuration cluster and then provide an updated screenshot? Thanks!

**Comment by KekieM** [comment]
Power configuration 1 (does not seem to change with read)
![image](https://user-images.githubusercontent.com/54375425/86637679-48974080-bfd6-11ea-98a1-f80ebfb2c955.png)

Power configuration 2 ( updated after read)
![image](https://user-images.githubusercontent.com/54375425/86637757-6664a580-bfd6-11ea-9c49-828c53480412.png)

Power configuration 3 (no change after read)
![image](https://user-images.githubusercontent.com/54375425/86637889-a2980600-bfd6-11ea-870c-a76fbb26e9f3.png)

Power configuration 4 (no change after read)
![image](https://user-images.githubusercontent.com/54375425/86637967-c3605b80-bfd6-11ea-8ca5-273afea4c92a.png)

**Comment by SwoopX** [comment]
Unfortunately, beta .79 contains an incorrect button map. A confirmed fix will be available with the following version.

**Comment by KekieM** [comment]
> Unfortunately, beta .79 contains an incorrect button map. A confirmed fix will be available with the following version.

is that the reason only the top row of buttons seems to work?

**Comment by SwoopX** [comment]
Yes, ideed. I ordered 2 of them but unfortunately, they arrived after our release deadline so I couldn't verify.

**Comment by wvuyk** [comment]
awaiting merge triggers the awful bot?

**Comment by SwoopX** [comment]
> awaiting merge triggers the awful bot?
> Could need some updates there...

No, it doesn't. And why don't you consider checking release notes? It's a valuable source to understand, what has happened.

**Comment by wvuyk** [comment]
I did a search for the EcoDim 8 button wall remote regularly but guess I missed it then? Sorry for stepping on your toes here, as that is not what I wanted. 
I was monitoring this thread because I would like to use the switch as well. This thread did not show the switch was implemented,  so I assumed it was not finished yet?

**Comment by SwoopX** [comment]
Np, guess you really overlooked it. Check out my recent commit for all the details (the release notes also mention it): https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3073

However, please take note that the device now exposes only one `ZHASwitch` resource instead of 4. I'd recommend resetting and re-pairing it.

I'm closing this issue now since the device is fully supported with version 2.05.80.

**Comment by Mimiix** [comment]
I recognize this one. You got me to ship it right? @SwoopX ?

**Comment by SwoopX** [comment]
Guilty 😜

**Comment by ronaldt80** [comment]
Perhaps a silly question but how do I use this switch in the Phoscon App? Is that possible? I have paired it and see it as available in my devices (switches) but can not seem to link the switch to a light/group.  Other switches (eg Aqara) work smoothly. I use a Conbee II, 2.05.80 / 8/14/2020 with FW v.26580700

**Comment by SwoopX** [comment]
Not sure since I don't use Phoscon. However, the device groups should be visible and usable in the old webapp.

**Comment by ronaldt80** [comment]
Thanks @SwoopX - that indeed works! Even after linking the devices in the old webapp it doesn't show up in Phoscon though.

**Comment by SwoopX** [comment]
Glad that it works. You might want to raise the visibility topic in the Phoscon beta repo.
