### ISSUE TITLE
WS-EUB1-ZG

### ISSUE THREAD

**Issue by rosti76** [dresden-elektronik/deconz-rest-plugin#3011]
## Device

- Product name: Zigbee Smart Switch
- Manufacturer: _TZE200_7tdtqgwv
- Model identifier: TS0601
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ x] Other: Mains powered Wall Swith

## Screenshots
![image](https://user-images.githubusercontent.com/59706471/86472428-7151d880-bd3f-11ea-95c8-8e5cbe875243.png)
![image](https://user-images.githubusercontent.com/59706471/86472456-7b73d700-bd3f-11ea-85d1-7843ed337031.png)

**Comment by Smanar** [comment]
for information , another device with tuya manufacture specific cluster EF00 > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2879

**Comment by Smanar** [comment]
Ok in fact it s not another device, but a duplicate ^^

Can you go on the other issue and try the code proposed, pls ?
