### ISSUE TITLE
Xiaomi door sensors are added to 'lights'

### ISSUE THREAD

**Issue by fi-sch** [dresden-elektronik/deconz-rest-plugin#3016]
## Describe the bug
Newly added Xiaomi door sensors are being added **additionally** as a light in Phoscon. In Home Assistant I can see additional 'light' entity which is being controlled (turned off/on) by sensor itself. 

## Steps to reproduce the behavior
1. Go to Phoscon -> Sensors
2. Add new sensor –> Others
3. Pair Xiaomi Mija door sensor
4. Push pair button once more
5. "Open" and "close" the sensor.
6. Go to the Phoscon –> Lights

## Expected behavior
Sensors shouldn't be added to Lights group, just Sensors. No additional entity should be added in Home Assistant

## Screenshots
<img width="742" alt="Phoscon – what I see in sensors" src="https://user-images.githubusercontent.com/59969726/86529099-286c6200-beae-11ea-96a3-2de425d557de.png">
<img width="552" alt="Phoscon – what I see in sensors" src="https://user-images.githubusercontent.com/59969726/86529102-2bffe900-beae-11ea-8fc4-cda8f6038f74.png">
<img width="337" alt="Home Assistant – entities added by integration" src="https://user-images.githubusercontent.com/59969726/86529105-302c0680-beae-11ea-8467-7ee4bd3eabd8.png">

## Environment
 - Host system: Intel NUC8 i3
 - Running method: Proxmox + HassOS + Home Assistent deCONZ Add-on
 - Firmware version: 26580700
 - deCONZ version: 2.05.78
 - Device: ConBee II
 - Do you use an USB extension cable: no

## Additional context
No issues with previously (weeks/months ago) added sensors.
I struggled with pairing new sensors before (in 2.05.77). However, it seemed that pairing and then immediately opening and closing the window helps with proper pairing.

**Comment by Smanar** [comment]
It s normal, it s because the device led can be used as light ....

Seriously, that's a funny bug.
Can you find and show us the JSON for the light entry ?
I think you can find it somewhere in HA or using the API if you know how to do that (with api key ) ?

**Comment by fi-sch** [comment]
> It s normal, it s because the device led can be used as light ....
> 
> Seriously, that's a funny bug.
> Can you find and show us the JSON for the light entry ?
> I think you can find it somewhere in HA or using the API if you know how to do that (with api key ) ?

Here you go:
```
"19": {
        "etag": "b3869321f635a4b00fe2734e1902f6a2",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2020-07-05T08:34:13Z",
        "manufacturername": "Unknown",
        "modelid": null,
        "name": "Okno Kuchnia",
        "state": {
            "alert": "none",
            "on": false,
            "reachable": true
        },
        "swversion": null,
        "type": "Dimmer switch",
        "uniqueid": "00:15:8d:00:03:e6:f9:93-01"
    }
```

**Comment by fi-sch** [comment]
Just in case someone asks about the clusters :) 
<img width="192" alt="Clusters in deCONZ" src="https://user-images.githubusercontent.com/59969726/86530296-eba56880-beb7-11ea-89e6-e1208477d464.png">

**Comment by SwoopX** [comment]
What is the model identifier from basic cluster? Do you have a dimmer switch and was it paired as last device before this one?

The reason why it comes up as light is that it identifies itself as dimmer switch, which is whitelisted for lights.

Could you also please share a screenshot of the node info panel?

**Comment by Smanar** [comment]
Lot of differences with mines, I haven't OTAU cluster, another model id, and no thoses output cluster ....
There is definitively something strange.

You only one sensor with this problem ?

**Comment by fi-sch** [comment]
> What is the model identifier from basic cluster? Do you have a dimmer switch and was it paired as last device before this one?
> 
> The reason why it comes up as light is that it identifies itself as dimmer switch, which is whitelisted for lights.
> 
> Could you also please share a screenshot of the node info panel?

There you go:
<img width="343" alt="Zrzut ekranu 2020-07-5 o 12 53 11" src="https://user-images.githubusercontent.com/59969726/86531092-ad5f7780-bebe-11ea-870e-7e6a071e55a0.png">

No, I do not have any dimmer switch right now. I did pair dimmable light before, but it was quite long time ago (at least two months ago) and I see it in deCONZ reappearing even I tried to delete this node many times.


> Lot of differences with mines, I haven't OTAU cluster, another model id, and no thoses outputs clusters ....
> There is definitively something strange.
> 
> You only one sensor with this problem ?

I have this issue for all 4 Xiaomi sensors that I paired yesterday, not only this one.

**Comment by fi-sch** [comment]
Just to add. Here's a screenshot of Phoscon with 3 identical sensors shown in Lights as 3 different products. All of them were paired yesterday.

<img width="651" alt="Phoscon – Sensors displayed in Lights" src="https://user-images.githubusercontent.com/59969726/86533985-54e7a480-bed5-11ea-9b5d-1f95e951dcdc.png">

**Comment by morfei1** [comment]
IMHO, it looks like a phoscon related problem.

https://github.com/dresden-elektronik/phoscon-app-beta

**Comment by ebaauw** [comment]
The door sensor looks like a light because of the server _On/Off_ cluster.  In some crooked Xiaomi way, it uses attribute reporting on this cluster to indicate open vs close.  Normally, the API shouldn’t create a `/lights` resource, because the sensor’s _Receiver on When Idle_ is false.  Not sure if the API plugin was changed or if a new version of the sensor or sensor firmware has changed the descriptor.

I only have the (square-ish) Aqara sensor, I think this is the round-ish Mi sensor?  Are you able to read the _Basic_ cluster attributes, notably _Date Code_ and _SW Build ID_?  Can you sniff the _Simple Descriptor Response_?  And the _Device Announce_?

**Comment by fi-sch** [comment]
> I only have the (square-ish) Aqara sensor, I think this is the round-ish Mi sensor?

Yes. It's round-ish one.

>Are you able to read the _Basic_ cluster attributes, notably _Date Code_ and _SW Build ID_?

Here you go, it was already posted above:
<img width="343" alt="Basic Cluster" src="https://user-images.githubusercontent.com/59969726/86531092-ad5f7780-bebe-11ea-870e-7e6a071e55a0.png">

>Can you sniff the _Simple Descriptor Response_? And the _Device Announce_?

I suppose I can but I don't know how to achieve that :)

**Comment by fi-sch** [comment]
Here's Basic Cluster with Date Code and SW Build ID:
<img width="327" alt="Zrzut ekranu 2020-07-6 o 09 15 49" src="https://user-images.githubusercontent.com/59969726/86566103-5e225100-bf69-11ea-99ba-a1c2ca60fb27.png">

**Comment by ebaauw** [comment]
That's a fairly old date.

Looking at the code, the manufacturer code `VENDOR_JENNIC` (0x1037) has been whitelisted, for the `lumi.ctrl_neutral` wired switches.  That has been the case since years.  The device advertises a device type of _Dimmer Switch_, this has been whitelisted since Feb 2019, in https://github.com/dresden-elektronik/deconz-rest-plugin/commit/d976ed33dfe4f27de33869b248f826de8aff2c10 to support the Sinope.

Not sure how to remedy this in the current code: the `/lights` resource is created before the _Basic_ cluster has been read (see also the missing values in the resource), so there's no way to distinguish the door sensor from the dimmer switch.

**Comment by Smanar** [comment]
And using Mac capabilities ?

**Comment by Smanar** [comment]
I don't see the Mac capabilities for the switch on the capture for the sinope.
But one is FFD and the other RFD ?

**Comment by fi-sch** [comment]
> But one is FFD and the other RFD ?
All I can say add from my side at this point is that all of those 4 sensors that I paired recently appeared in deCONZ as an end devices (RFD).


There's one more thing that maybe will give you some clue:

I struggled with pairing 2 Xiaomi door sensors before (under v.2.05.77). (One of those sensors is also 1 of those 4 that are he matter of this topic.) Both sensors were visible in deCONZ without any name, but I couldn't make any of them visible in Phoscon.
Suddenly, just before an update to 2.05.77, I saw that out of the blue one of those sensors finally appeared in Phoscon – but it DID NOT appeared under /lights. Still no luck with the second one.
So after a couple of days I've updated deCONZ to 2.05.78 and tried again pairing this one "waiting" sensor and additional 3 similar guys. (It seemed that pairing and then immediately opening and closing the window helped me with "proper" pairing.) I was able to pair all 4 sensors using that method – but every each on of them DID appear under both /lights and /sensors.

I'm not sure about 2 things:
- If this one sensor that was visible only in deCONZ long time before and now finally paired (in 2.05.78, and is affected by the issue) was also from the same batch of sensors.
- If it isn't just deCONZ issue.

PS I still have a couple of those Xiaomi sensors (brand-new) so I may do some testing.

**Comment by ebaauw** [comment]
> There is already an ugly hack in void LightNode::setHaEndpoint(const deCONZ::SimpleDescriptor &endpoint) for Xiaomi (to force modelid read before continuing), we can't use the same ?

If you have a LightNode, the resource has already been created.

**Comment by SwoopX** [comment]
I also see no other reason than to change the pairing process and to recklessly force a manufacturer and modelId read directly after the simple descriptors. But that's a major.

**Comment by fi-sch** [comment]
It should remain opened as I assume it wasn't fixed yet.

**Comment by Kristian8606** [comment]
With Deconz version .84, this sensor still shows a light switch when paired again

**Comment by Smanar** [comment]
Pls mùake a try with version 85, from my memory it s repared now.

**Comment by SwoopX** [comment]
Tbh, I don't think so. Presumably, Manu meant Tuya instead of Xiaomi as I haven't seen any change for Xiaomi

**Comment by Smanar** [comment]
This PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3364

**Comment by SwoopX** [comment]
Yup

**Comment by Smanar** [comment]
But this code can works for Xiaomi too ?
It will set the device as light for only danalock device, so it will disable the problem for Xiaomi.

**Comment by fi-sch** [comment]
I think it was solved, so I'm closing this issue.
