### ISSUE TITLE
How to reset ?

### ISSUE THREAD

**Issue by Galiwyx** [dresden-elektronik/deconz-rest-plugin#3017]
Hello,

I'm trying using deCONZ with homebridge on docker. I use unRaid as OS. 

First I checked if conbee II stick was discovered : 
![image](https://user-images.githubusercontent.com/206181/86638676-0969ef00-bfd8-11ea-83a1-a8847032f630.png)

Second, I go to https://phoscon.de/pwa to add the new Conbee USB stick
![image](https://user-images.githubusercontent.com/206181/86638753-2bfc0800-bfd8-11ea-8aa0-5da8befbefca.png)

Buty stick is already here, I don't understand why, it's a clean installation of deCONZ. How can I remove the previous installation ? Of course I can't login (connection failed). 

Please find below my deCONZ docker configuration:
![image](https://user-images.githubusercontent.com/206181/86639926-0ec83900-bfda-11ea-8396-e6064bdeb182.png)

192.168.1.9:7080 displays a blank page.

**Comment by Galiwyx** [comment]
The problem was the url, it's not  https://phoscon.de/pwa but  https://phoscon.de/app

**Comment by Mimiix** [comment]
So it is fixed :)?

**Comment by Galiwyx** [comment]
Yes :)
