### ISSUE TITLE
Climax EMD-1ZBS power meter

### ISSUE THREAD

**Issue by Ocramius** [dresden-elektronik/deconz-rest-plugin#3020]
Hey there! First of all, thanks for all the hard work around deconz: looks awesome so far!

I'm here to ask for device support as per https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

## Device

This is a Climax EMD-1ZBS (https://zigbeealliance.org/zigbee_products/energy-meter-emd-1zbs/ & https://www.climax.com.tw/new/downloads/EMD-1ZBS%20Energy%20Meter_Product%20News_11.11.2016.pdf):
 

![Selection_430](https://user-images.githubusercontent.com/154256/86841529-5adfb000-c0a4-11ea-819a-0cef751d338e.png)

Not much available online about how it operates. Retailer is Lupus - they sell it re-branded as "Electric Meter Smart Home Module". It uses a diode to detect the blinking light on a power meter, and infers KWh metrics from that.

- Product name: EMD-1ZBS
- Manufacturer: Climax
- Model identifier: **no model identifier displayed**
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [x] Other: power meter

## Screenshots

Cluster screenshot: 

![Selection_431](https://user-images.githubusercontent.com/154256/86843144-72b83380-c0a6-11ea-88d7-41fb0b300395.png)

![Selection_432](https://user-images.githubusercontent.com/154256/86843272-a2673b80-c0a6-11ea-8092-792d0b1bd765.png)

![Selection_433](https://user-images.githubusercontent.com/154256/86843345-b7dc6580-c0a6-11ea-8884-6b94a1feccab.png)

Lemme know if I can help in any way to get this one detected: couldn't find much about it in other gateways.

### 0000 Basic:

![Selection_435](https://user-images.githubusercontent.com/154256/86904034-6a94de00-c110-11ea-9356-27d963262531.png)

### 0001 Power Configuration

![Selection_436](https://user-images.githubusercontent.com/154256/86904130-8a2c0680-c110-11ea-8a85-e7bc243d7336.png)

### 0003 Identify 

![Selection_437](https://user-images.githubusercontent.com/154256/86904196-a2038a80-c110-11ea-81f1-3eb61544929d.png)

#### 0702 Simple Metering

![Selection_438](https://user-images.githubusercontent.com/154256/86904269-bba4d200-c110-11ea-90fc-5818a5066309.png)

**Comment by SwoopX** [comment]
You forgot the screenshot for the simple metering cluster.

**Comment by Ocramius** [comment]
Thanks @SwoopX: I've added the screenshots of all cluster info sub-sections (didn't know you could select them :D )

**Comment by SwoopX** [comment]
Thanks, but it looks like you haven't read the attributes via the button...

**Comment by Ocramius** [comment]
This is after pressing "read": will retry though 👍

**Comment by SwoopX** [comment]
The device was probably not awake.

**Comment by Ocramius** [comment]
I've re-done the reads: since I don't really understand how the GUI works, I've selected each field individually and used the "read" button each time.

Here are the results:

### 0000 Basic

![Selection_440](https://user-images.githubusercontent.com/154256/86910008-4be71500-c119-11ea-984f-7edfe8ebe07c.png)

### 0001 Power Configuration

![Selection_441](https://user-images.githubusercontent.com/154256/86910071-64572f80-c119-11ea-9fb1-e3d44c199245.png)

### 0003 Identify

![Selection_442](https://user-images.githubusercontent.com/154256/86910111-7769ff80-c119-11ea-8ab1-0e4346bb634d.png)

### 0702 Simple Metering

![Selection_443](https://user-images.githubusercontent.com/154256/86910203-94063780-c119-11ea-8c52-3b578a22379d.png)

**Comment by Ocramius** [comment]
> The device was probably not awake.

Hmm, I've forced it to try "pairing" (not sure if that's what it's called in the ZigBee world). How would that be forced on other appliances, such as other meters? Trying to query through `Identify` GUI seems to only produce timeouts.

**Comment by SwoopX** [comment]
Now it looks ok-ish. But the values are all 0, probably due to a reset?

Got no clue what the measurement units are. For now, I'd assume it's all in W.

**Comment by Ocramius** [comment]
> probably due to a reset?

Hard to say: this thing came with zero manual, besides "press and hold for 10 seconds to start looking for a gateway".
I can most certainly act as guinea pig to get this polished over time.

> For now, I'd assume it's all in W.

Very likely

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.

**Comment by Ocramius** [comment]
Amazing, will try reading through the diffs and give it a spin soon 👍

**Comment by 00lex** [comment]
its frustrating to get or just find a shop for some zigbee devices :(
@Ocramius can you give us a link? 

thank you

**Comment by Ocramius** [comment]
@00lex here you go: https://www.lupus-electronics.de/shop/Alarm-Smarthome/Smarthome-Hausautomation/LUPUSEC-Hauptstromz%E4hler-p.html

Indeed, I had to contact Climax too in order to find a local reseller :shrug:

**Comment by spripe** [comment]
Any solution for this?
My meter is also reporting 0 kWh

**Comment by spripe** [comment]
And would be nice if it could report watt and not kWh :(

**Comment by Ocramius** [comment]
@spripe I suggest opening a new issue: my device now connects and shows up (as a siren) within Phoscon, but I didn't have time to debug further into metrics: doesn't seem to pick up anything meaningful, for now.

**Comment by SwoopX** [comment]
> And would be nice if it could report watt and not kWh :(

Not gonna happen. Firstly, what you get is dependent on the device (99% report any values smaller than kWh) and secondly, the values exposed by the REST API are integers, no doubles.

If you guys don't get any values in the simple metering cluster via deconz GUI, then there's not much we can do. In that case I'd suspect it to not collect any usable data.

**Comment by luka6000** [comment]
I'm very interested in this meter. Found some docs
https://fccid.io/GX9EMDZB/User-Manual/Users-Manual-3242046.pdf
Implementation looks ok. Looking at the screenshots I can see that Basic-Device enabled attribute is set to false. Maybe that's why no values are returned?

**Comment by Ocramius** [comment]
Attaching it here, since I don't trust the external URI to stay stable :D 

[Users-Manual-3242046.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6115439/Users-Manual-3242046.pdf)

**Comment by luka6000** [comment]
@Ocramius, so can you confirm that this meter works? Can you set attribute to enable the readings?

**Comment by Ocramius** [comment]
@luka6000 I haven't really been able to get back to it - will certainly try it though, as I'm setting up my small solar farm, so it should come back to my priorities soon-ish :)
