### ISSUE TITLE
Aqara Wireless Switch Controller (WXKG06LM)

### ISSUE THREAD

**Issue by elpablillo** [dresden-elektronik/deconz-rest-plugin#3028]
Hi, I've bought specifically the model WXKG03LM, but I've received WXKG06LM. I can pair it the device but PhosconApp says that  cannot find any device, so, it shows in the GUI and that's it. Can you add this model ? 
Thanks 

## Device

- Product name: Aqara Wireless Switch Controller
- Manufacturer: 0x1037
- Model identifier: 
- Device type: RFD
  - [ ] Light
  - [ ] Lock
  - [X] Remote
  - [ ] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [X] Other: Switch

## Screenshots

![image](https://user-images.githubusercontent.com/68110358/87150758-f9d9f700-c2b2-11ea-9588-50f7f5870a43.png)

**Comment by Mimiix** [comment]
I think it is implemented already. What does the RestAPI show?

If you see devices within deCONZ but not in Phoscon, that is most of the time perfectly normal. Phoscon is closed source and needs devices to be added manually by their Developer. However, the device will still be usable with the API/Home-Assistant/OpenHAB etc.

**Comment by elpablillo** [comment]
RestAPI nothing... no switch, I've tried to add it many times, I delete the node in GUI, I put the device in pair mode, scan in the RestAPI, the device link to something, in the GUI appears the device ( but with no name,Model,Vender,etc..it's in the 1st pic) but in the RestAPI  it falis
![image](https://user-images.githubusercontent.com/68110358/87152671-6dc9ce80-c2b6-11ea-87cc-3b9bb2d67893.png)

**Comment by SwoopX** [comment]
Please provide all requested screenshots. The basic cluster is missing (when the attributes have been read)

**Comment by elpablillo** [comment]
I'm not sure what screenshot do you need... this one? (I'm starting so I don't have much) 
![image](https://user-images.githubusercontent.com/68110358/87154293-46c0cc00-c2b9-11ea-8796-92f65284db72.png)

**Comment by Mimiix** [comment]
Please refer to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by elpablillo** [comment]
Oh, thanks for the link...
![image](https://user-images.githubusercontent.com/68110358/87166594-1898b780-c2cc-11ea-8632-6281e124cf68.png)

**Comment by SwoopX** [comment]
Huh? Isn't that an Aqara Opple 3 gang?

**Comment by elpablillo** [comment]
Well, not very well... I have two devices of this model and both with the same result, they show in the GUI but that's all, not in HA and not in PhosconApp...And I have the last firmware v2.5.77, So...What am I doing wrong?; the process it is not complicate, it's quite easy :(

**Comment by Mimiix** [comment]
Can you provide some HA logging?

If you need guidance, join the Discord. In the readme there is a URL to the server :)

**Comment by elpablillo** [comment]
Hi all, are you going to add the lumi.remote.b186acn02 to the Firmware version V2_05_78, I didn't see those new lines in the Pre-release, and I wouldn't want you to forget about my device :). Thanks

**Comment by ekesgin** [comment]
I'm also waiting the support for this device.

**Comment by king7222** [comment]
+1 here 😊, exactly like elpablillo I bought two WXKG03LM and received two WXKG06LM, and they are not detected in my Jeedom with Deconz plug-in after activating the include mode 😕.
I hope this device will be included in the next update, because I have no use for these switches otherwise. 

Thanks for all the work

**Comment by Smanar** [comment]
What is the model id, it s not the same device than https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3066 ?

**Comment by king7222** [comment]
Yes it has only one switch but the model id is the same : lumi.remote.b186acn02

**Comment by Smanar** [comment]
Yep this device is in the PR > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3053/commits/7c01bb1dbefad841684f8d02863d2f7ed208383d

**Comment by king7222** [comment]
Thank you very much for your work, Wxkg06lm (lumi.remote.b186acn02) just works perfectly with 2.05.80 👍
I could add my two switches in Jeedom without any issue. 
Thanks

**Comment by elpablillo** [comment]
Well, in my case it still shows in the deconz-GUI, but still not showing in the WebApp... and in HA it only shows the battery level entity, i had to go to Developer Tools > events and listen the deconz_event: 
{
    "event_type": "deconz_event",
    "data": {
        "id": "lumi_remote_b186acn02_10",
        "unique_id": "00:15:8d:00:04:52:50:4f",
        "event": 1002
    },
    "origin": "LOCAL",
    "time_fired": "2020-08-16T10:03:39.391325+00:00",
    "context": {
        "id": "c1e74d05dfa711ea92fc5d5adfd4cf0f",
        "parent_id": null,
        "user_id": null
    }
}
Getting the ID and the event I could create an automation. 
event_data:
  event: 1002
  id: lumi_remote_b186acn02_9
event_type: deconz_event
platform: event
So, it is working but in a rustic way.

**Comment by SwoopX** [comment]
Phoscon is not deconz. You might want to request support for it at the Phoscon beta repository.

**Comment by maximilien03** [comment]
Hi !
I also got two of those WXKG06LM. It looks like the old references (which were perfectly working with Phoscon app) are not produced anymore.
Pairing was successful with Phoscon app. However, they don't appear in the switch editor. I guess they are not fully supported yet.
HA allows me to make automations based on events, but it would be way better if I could configure those switches with Phoscon.
