### ISSUE TITLE
Model MCLH-05 manufactured by LifeControl

### ISSUE THREAD

**Issue by Keles75** [dresden-elektronik/deconz-rest-plugin#3033]
## Device

- Product name: Model MCLH-05 manufactured by LifeControl
- Manufacturer: LifeControl
- Model identifier: MCLH-05
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [x] Sensor
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

https://zigbee.blakadder.com/LifeControl_MCLH-05.html

## Screenshots

![Снимок экрана 2020-07-11 в 14 45 57](https://user-images.githubusercontent.com/22985524/87223472-ec417180-c385-11ea-8bfd-4c6c17904a59.jpg)
![Снимок экрана 2020-07-11 в 14 44 35](https://user-images.githubusercontent.com/22985524/87223474-f2cfe900-c385-11ea-97d6-2d1863b8bf61.jpg)

**Comment by SwoopX** [comment]
Please provide the requested screenshots as mentioned in the template, thanks!
