### ISSUE TITLE
SONOFF SNZB-04

### ISSUE THREAD

**Issue by cllatser** [dresden-elektronik/deconz-rest-plugin#3036]
## Device

- Product name: SNZB-04
- Manufacturer: SONOFF
- Model identifier: DS01
- Device type:
  - [ ] Light
  - [ ] Lock
  - [ ] Remote
  - [X] Sensor Window / Door
  - [ ] Siren
  - [ ] Thermostat
  - [ ] Other: 

## Screenshots
![SNZB-04 Node Info](https://user-images.githubusercontent.com/65849393/87301164-5d606080-c50f-11ea-8e23-66f04313c317.jpg)
![SNZB-04 Basic Cluster](https://user-images.githubusercontent.com/65849393/87301236-7ec14c80-c50f-11ea-9d4a-80add11177a8.jpg)
![SNZB-04 IAS Zone (Closed)](https://user-images.githubusercontent.com/65849393/87301255-87b21e00-c50f-11ea-869b-ac32ee4379c9.jpg)
![SNZB-04 IAS Zone (Open)](https://user-images.githubusercontent.com/65849393/87301258-8a147800-c50f-11ea-89ed-61d8c7611f29.jpg)
![SNZB-04 Indenty Cluster](https://user-images.githubusercontent.com/65849393/87301272-8e409580-c50f-11ea-89da-1f3a305a7053.jpg)
![SNZB-04 Power Configuration Cluster](https://user-images.githubusercontent.com/65849393/87301281-926cb300-c50f-11ea-85bf-b71c4a27152a.jpg)

**Comment by SwoopX** [comment]
Closing this as device is now supported with .79 beta.

**Comment by derVicthor** [comment]
Device is never available in Phoscon for me. Pairing works, but I never get any device data and it shows up as unavailable from the start. What to do?

<img width="764" alt="Bildschirm­foto 2022-12-29 um 17 03 13" src="https://user-images.githubusercontent.com/39854751/209979020-47e48011-fa52-410d-b930-623328c5a633.png">
