### ISSUE TITLE
Xiaomi Smart Plug (Xiaomi Mija ZB3.0 ZNCZ04LM) doesn't show connection lines / mesh in deconz

### ISSUE THREAD

**Issue by fennsen64** [dresden-elektronik/deconz-rest-plugin#3046]
## Describe the bug
These plugs (see also #2583) doesn't show up the existing connections / mesh to the end devices.
Only the connection to the coordinator is visible (see screenshots).

The connections from the (de-facto connected) devices to these plugs (here the Xiaomi Sensors: Multisensor-6 and Contactsensor-1 ) are also missing. With an other plug(Osram smart +), as well as connected directly to the conbee II stick there were shown up correctly

-I also tried the 2.05.78 beta: same behavior (and reverted because this versions crashes my raspbee gateway on pimatic)
-Tested two of them, same behavior

## Screenshots
![grafik](https://user-images.githubusercontent.com/10127115/87522125-899ded80-c685-11ea-929f-0044ef349742.png)
![grafik](https://user-images.githubusercontent.com/10127115/87522172-97537300-c685-11ea-94aa-36ce7a5fa088.png)

## Environment

 - Host system: (Intel NUC, debian buster)
 - Running method: (Marthoc Docker container)
 - Firmware version: (26580700)
 - deCONZ version: (2.05.77)
 - Device: (ConBee II)
 - Do you use an USB extension cable: yes

**Comment by SwoopX** [comment]
To be honest, I don't know what you want to say here. Do your sensors work?

**Comment by Smanar** [comment]
The mesh is strange for me, why only 1 connection by router ?
They are so far away one from the other ?

1 of your 2 sensor have leave, and I have doubt for the second

**Comment by fennsen64** [comment]
Thats exactly the point and my issue; as I said: ,,The Plugs doesn't show up the existing connections / mesh to the end devices"
Yes: sensors are working. But I like to see to which router they are connected.

**Comment by ebaauw** [comment]
Zigbee doesn’t maintain connections.  The lines show neighbour table entries, not connections.  Not all routers support querying their neighbour table.

**Comment by Smanar** [comment]
I have searched on other issue, I haven't found similar network (with the same device). But yes if all is working (even the grayed one), can be normal. I have never see this bug on my side, so it' s realy strange for me.

If someone else with a ZNCZ04LM can take a look on his own network .....

**Comment by SwoopX** [comment]
Alright, tried it in my test network. Took pretty much the maximum diagonal distance at my place for the coordinator and a wireless switch, the plug in between.

![grafik](https://user-images.githubusercontent.com/4005212/87728840-3c746580-c7c4-11ea-8300-9f7d6bd02838.png)

The plug apparently routes appropriately. The lines didn't show up as well, but to be honest, I couldn't care less.

Maybe I can give it another try tomorrow with a more talkative end device.

**Comment by Smanar** [comment]
Yep, but it s just by curiosity. honestly, if I had the same network I would have asked myself questions too.

Now we know what answer at next one with same problem ^^
