### ISSUE TITLE
SONOFF SNZB-01

### ISSUE THREAD

**Issue by Saptuze** [dresden-elektronik/deconz-rest-plugin#3047]
## Device

- Product name: SNZB-01
- Manufacturer: Sonoff Ewelink
- Model identifier: WB01
- Device type :
  -  Switch

## Screenshots
![image](https://user-images.githubusercontent.com/63117206/87575524-59c80780-c6d0-11ea-9b75-56c1080da6a8.png)
![image](https://user-images.githubusercontent.com/63117206/87575612-7401e580-c6d0-11ea-8eef-07f7a19c2309.png)
![image](https://user-images.githubusercontent.com/63117206/87575643-7ebc7a80-c6d0-11ea-813d-6ae2605d1c5b.png)
![image](https://user-images.githubusercontent.com/63117206/87575703-95fb6800-c6d0-11ea-95c0-e5d671dca764.png)

**Comment by SwoopX** [comment]
Duplicate to #2990 , please close this one. Thanks!
