### ISSUE TITLE
Hive Radiator Valve

### ISSUE THREAD

**Issue by peterguy04** [dresden-elektronik/deconz-rest-plugin#3049]
## Device 

- Product name: Hive Radiator Valve
- Manufacturer: Danfoss
- Model identifier: TRV001
- Device type :  
  [ x ] Thermostat
 

## Screenshots

  Required screenshots:
  - Endpoints and clusters of the node
![endpoints](https://user-images.githubusercontent.com/45408070/87801819-3758fa00-c848-11ea-81c7-4354a5fadf88.PNG)

  - Node Info panel
![node info](https://user-images.githubusercontent.com/45408070/87801835-3cb64480-c848-11ea-8eb9-3c14ec65aad7.PNG)

  - Basic Cluster attributes in the Cluster Info panel.
![basic](https://user-images.githubusercontent.com/45408070/87801856-4475e900-c848-11ea-917a-35f9faab2469.PNG)

 - 0201
![0201 (1)](https://user-images.githubusercontent.com/45408070/87801955-64a5a800-c848-11ea-9aaf-81a11b3d383b.PNG)
![0201 (2)](https://user-images.githubusercontent.com/45408070/87801961-67080200-c848-11ea-8e05-49c2168c284b.PNG)

- 0001
![power config](https://user-images.githubusercontent.com/45408070/87802003-75561e00-c848-11ea-87af-cf37bc318783.PNG)

- 0020
![poll control](https://user-images.githubusercontent.com/45408070/87802039-8010b300-c848-11ea-869c-3b06391ba493.PNG)

- 0204
![0204](https://user-images.githubusercontent.com/45408070/87802077-8a32b180-c848-11ea-8995-ae916bb31d46.PNG)

- 0019
![otau1](https://user-images.githubusercontent.com/45408070/87805033-a20c3480-c84c-11ea-9ed3-29d0558662ea.PNG)
![otau2](https://user-images.githubusercontent.com/45408070/87805043-a59fbb80-c84c-11ea-8944-bf00689a1a41.PNG)

**Comment by Smanar** [comment]
I m on it
