### ISSUE TITLE
Sunricher SRP-ZG9105-50CC (iluminize 511.210T)

### ISSUE THREAD

**Issue by MichaelHeimann** [dresden-elektronik/deconz-rest-plugin#3056]
## Device

- Product name: Sunricher SRP-ZG9105-50CC (relabeled as iluminize "511.210T" or as "LEDXess EOS10 - ZigBee® - CC Controller+Netzteil 1-Kanal 50W")
- Manufacturer: Sunricher
- Model identifier: DIM Lighning
- Device type : Light

## Screenshots
![image](https://user-images.githubusercontent.com/3189562/87864781-26ee6f80-c96d-11ea-9fcb-361e4ec3c2d6.png)

![image](https://user-images.githubusercontent.com/3189562/87864790-4ab1b580-c96d-11ea-9913-8e23d680361a.png)
![image](https://user-images.githubusercontent.com/3189562/87864797-6026df80-c96d-11ea-9a1a-55fd68192d4b.png)
![image](https://user-images.githubusercontent.com/3189562/87864801-6c12a180-c96d-11ea-8c7c-e8bf2a0d9e20.png)
On/Off Cluster:
![image](https://user-images.githubusercontent.com/3189562/87864868-02df5e00-c96e-11ea-8fee-0dc949d56fac.png)
Level Control Cluster:
![image](https://user-images.githubusercontent.com/3189562/87864869-15599780-c96e-11ea-879f-e795f75c1cc7.png)
Diagnostics Cluster:
![image](https://user-images.githubusercontent.com/3189562/87864882-3de19180-c96e-11ea-9848-5d079e467577.png)
![image](https://user-images.githubusercontent.com/3189562/87864885-45089f80-c96e-11ea-89ed-ecf17a80c920.png)
OTAU Cluster:
![image](https://user-images.githubusercontent.com/3189562/87864897-6b2e3f80-c96e-11ea-925d-d3311a550ebe.png)
![image](https://user-images.githubusercontent.com/3189562/87864901-71bcb700-c96e-11ea-8661-cfe964147439.png)

These lights seem to work out of the box pretty well.
I have three of these, one bought from Iluminize and the other two from LEDXess.

I'm adding this since I was asked to on discord after asking a question. For whom it may concern, I do have sometimes issues with one of them: The links in deCONZ GUI/VNC disappear and it only reacts to group commands, the node seems gray in deCONZ and Phoscon. This seems to resolve itself but I'd like to know how to enforce the fix/workaround/repair that.
I had this with Paul Neuhaus Lights before...

Hope that helps :)

**Comment by MichaelHeimann** [comment]
Push.
The Group Command thing seems to be related to sub-optimal reachability. Signal Meter Plugin gives 111 or 119 sometimes.
Nothing related to the device itself.
What's needed to get support?

**Comment by Mimiix** [comment]
I've asked @SwoopX to check on this ;)

**Comment by SwoopX** [comment]
I've added Sunricher mains powered devices to allow attribute reporting, maybe that helps. If not, I'd suspect routing issues, which resolve itself over time.

**Comment by pur3asdf** [comment]
I'm also looking forward to see Sunricher remotes implemented into phoscon app. I can see my [SR-ZG2868](https://www.sunricher.com/dim-cct-rgb-3-in-1-zigbee-remote-sr-zg2868.html) in deconz but i'm unable to add it as a switch in phoscon app.

**Comment by Mimiix** [comment]
@pur3asdf Please read #2684
