### ISSUE TITLE
TuYa TS0001 valve

### ISSUE THREAD

**Issue by renne** [dresden-elektronik/deconz-rest-plugin#3059]
## Device

Product names:
- TuYa TS0001
- CR Smart Home TS0001
- Lonsonho TS0001
- Bandi BDS03G1

![grafik](https://user-images.githubusercontent.com/4548652/87878472-d61a5d80-c9e4-11ea-98f1-8446e0690445.png)

- Manufacturer: [Available in zigbee2mqtt](https://www.zigbee2mqtt.io/devices/TS0001.html)
- Model identifier: [Available in zigbee2mqtt](https://www.zigbee2mqtt.io/devices/TS0001.html)
- Device type :
  - Other: valve

**Comment by Mimiix** [comment]
@renne This is really not how it works unfortunately. We do need the information as per deCONZ screens and it's respectable clusters. Are you able to provide the screenshots as requested?

**Comment by fi-sch** [comment]
Did you check if it doesn't work indeed? I have TS0011 and it works perfectly out of the box.

**Comment by renne** [comment]
It's still in shipping ...

**Comment by Mimiix** [comment]
I'll be closing this. Please create another issue if you do have the device and required information.
