### ISSUE TITLE
EuControls support

### ISSUE THREAD

**Issue by SweNilsson** [dresden-elektronik/deconz-rest-plugin#306]
I have just recieved a EuControls LCM-LV-ZB controller for my LED light driver (Hide-a-Lite). 
I can find the unit using rest-API but I cannot control it. 
Would it be possible to get support for that unit? It would be very appreciated!

**Comment by manup** [comment]
Can you please provide more infos:
* screenshots from basic cluster
* screenshot endpoint list
* how does it look in the REST-API

Does it work when you control it directly in deCONZ on/off and level cluster?

**Comment by SweNilsson** [comment]
I have no control of the unit at all. This is what I see.

<img width="1210" alt="skarmavbild 2017-12-04 kl 18 24 35" src="https://user-images.githubusercontent.com/34248030/33570382-f600fd62-d92c-11e7-93dc-ad8c90a8dd82.png">

**Comment by manup** [comment]
The light isn't assigned to a group yet.

You need to press the `+` button and assign it to a group (for example the Tradrfi group).

**Comment by SweNilsson** [comment]
Wow, sorry and thank you. 
That enables control, however I still cannot get the lights to lit. But that might be some other compatibility issue of course.

**Comment by manup** [comment]
Since it's a 1–10 V control you may need to dimm up the light first in order to turn it on. For that press the three dots symbol next to the lights name and use the dimm bar.

**Comment by SweNilsson** [comment]
I found the remaining issue. My driver was acting as a slave to another driver which generated.a conflict. De-connecting thr sync cable made it work! :)

**Comment by manup** [comment]
Cool glad to hear that :)
