### ISSUE TITLE
Blitzwolf bw-is5

### ISSUE THREAD

**Issue by pszypowicz** [dresden-elektronik/deconz-rest-plugin#3067]
##  Device

- Product name: BlitzWolf BW-IS5
- Manufacturer: _TYZB01_o63ssaah
- Model identifier: TS0207
- Device type : 
  - Sensor

## Screenshots

<img width="353" alt="node_info" src="https://user-images.githubusercontent.com/2733699/88191820-250e0000-cc3c-11ea-8c37-58efe7260b00.png">
<img width="649" alt="otua" src="https://user-images.githubusercontent.com/2733699/88191826-25a69680-cc3c-11ea-8b19-0cc65ea8f4cd.png">
<img width="664" alt="ias zone" src="https://user-images.githubusercontent.com/2733699/88191830-263f2d00-cc3c-11ea-97b9-d86dab66b394.png">
<img width="653" alt="power" src="https://user-images.githubusercontent.com/2733699/88191833-263f2d00-cc3c-11ea-91dc-dfd87740a3e8.png">
<img width="678" alt="cluster_basic" src="https://user-images.githubusercontent.com/2733699/88191839-26d7c380-cc3c-11ea-8629-a25407bd300f.png">

**Comment by tobus3000** [comment]
Got two of these exact same devices. It's a 'unbranded' no-name water leakage detector based on the exact same HW platform.
Manufacturer Name: _TYZB01_sqmd19i1
The rest is identical to the above screenshots. The manual does mention in one place that a "Tuya Gateway" is required to make use of the device...
AFAIK it only reports whether it has detected water or not... No internal temperature, light or any other sensors..

**Comment by Mimiix** [comment]
@SwoopX You able to whitelist on the TYZB01?
