### ISSUE TITLE
deCONZ-WIFI2.sh[382]: Error: database disk image is malformed

### ISSUE THREAD

**Issue by Paalap** [dresden-elektronik/deconz-rest-plugin#3068]
Hi everybody,

I hope someone could help me to fix my issue with the reported error regarding malformed database deCONZ-WIFI2.sh and deCONZ-update2.sh.

Additionally I have also a strange behaviour regarding group "ALL", I get an additional "ALL" group on each reboot. But fist I would like to fix the issue wiht malformed database.

I'm running deconz on pi4 (fresh setup with migrated configuration).

Thank you in advance!

**Comment by Mimiix** [comment]
@Paalap Hi

I am closing this issue, as allot of information is missing. Adding it would be more complicated and time consuming.. Could you please open a new one with [the following template](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new?assignees=&labels=Bug+report&template=bug_report.md&title=)

Thank you!
