### ISSUE TITLE
TUYA Smart Switch (EU) 3-Gang DS-112L-3 is incorrectly specified as a battery device

### ISSUE THREAD

**Issue by snador1977** [dresden-elektronik/deconz-rest-plugin#3072]
The TUYA Smart Switch (EU) 3-speed DS-112L-3 (230V) is incorrectly specified as a battery device.

https://zigbee.blakadder.com/Tuya_DS-112L-3.html

This could be the reason why the device shows no repeater functionality.

Usually all powered Zigbee devices are available as repeaters. The flush-mounted switches would be perfect as a repeater to ensure a stable Zigbee network.

Can you check this out? Thank you!

The same problem exists with another 3-way wall switch. Apparently a white label product.

https://zigbee.blakadder.com/Lerlink_X713A.html

https://de.aliexpress.com/item/4000369677580.html?spm=a2g0s.9042311.0.0.27424c4dJZFTv9

![screenshot](https://user-images.githubusercontent.com/45245918/88330762-2b7ba500-cd2c-11ea-803f-2c89431219f7.jpg)

**Comment by SwoopX** [comment]
There's nothing we can do about it. That info comes from the device and is stored in the firmware to be more precise. You may raise this to Tuya.

**Comment by vegetate7** [comment]
BTW, "No neutral" switches must not be routers. It's kind of "parasite" power supply can not provide enough for router.

**Comment by Smanar** [comment]
No, they can ^^.
I have a switch without neutral that work fine as router, and see as router too.

**Comment by vegetate7** [comment]
Hmm. Ok. I'm wrong then.
