### ISSUE TITLE
Xiaomi Aqara Opple Switches

### ISSUE THREAD

**Issue by SAOPP** [dresden-elektronik/deconz-rest-plugin#3074]
Hi!

Guys, today I have been tested my **three switches** from aqara. 2x6buttons and 1x2buttons.

My two tested stends is working **raspbee** and **conbee2** in **docker**. Raspbee firmware is 26350500, and Conbee2 firmware is 264A0700. **Poscon is 2.05.79**.
 
_The behaviour is next:_ 

1. The switches didn't pass through the pairing mode - are not connected in the final.

2. When pairing mode is active and if you press any key on the switch, the switch is linking with (I don't know if it's right to say direct connection?) a "direct connection" to the bulbs on the network (in my case, it was three e27 Aqara at first stend, and onoff relay at the second stand). 

3. Moreover, if the switch communicates directly with the light bulbs (or with any other device on the network directly), it is not in Phoscon, but its node is present on the network map in Deconz GUI.

4. By some miracle, after several attempts to connect, my 6-button switch got into Phoscon, and it was detected correctly, but I couldn't get any events in the Home Assistant from it. Those. the switch was just useless.

5. Guys, developers, quite a long time has passed since the release of these devices, as well as since the official support of these devices in Deconz... What am doing wrong?

Thanks in advance.

**Comment by ebaauw** [comment]
Just to be sure, could you please attach GUI screenshots of the node, incl. the endpoints and clusters, of the _Node Descriptor_ and of the _Basic_ cluster attributes?  Xiaomi are known to apply undocumented changes to devices.

**Comment by SAOPP** [comment]
@ebaauw Erik I will do it, when I try to connect it again. Thanks.

**Comment by jdeluyck** [comment]
I recently aquired 2 Opple 2x1 switches - adding them to the network is fairly easy (you just scan with phoscon and push the button on the back for 5+ seconds) - they show up in the network.

Switch type is WXCJRG12LM

I'm searching though how i can link them to a specific group - right now they're triggering everything :/

![power_cluster](https://user-images.githubusercontent.com/5451787/88413585-f3776f00-cdca-11ea-97ae-2f78d4a065e7.png)
![identity_cluster](https://user-images.githubusercontent.com/5451787/88413587-f4100580-cdca-11ea-89bf-133344dd9567.png)
![basic cluster](https://user-images.githubusercontent.com/5451787/88413588-f4a89c00-cdca-11ea-9811-37f374bec82c.png)
![2](https://user-images.githubusercontent.com/5451787/88413592-f4a89c00-cdca-11ea-83e8-668f34f4b5d6.png)
![1](https://user-images.githubusercontent.com/5451787/88413594-f5413280-cdca-11ea-829f-69a9d9817837.png)

**Comment by jdeluyck** [comment]
Ok. I retried adding them as a switch now in Phoscon, and scanning and then pressing the button for (I guess) around 15 seconds made it show up correctly in Phoscon.

**Comment by ebaauw** [comment]
> Ok. I retried adding them as a switch now in Phoscon, and scanning and then pressing the button for (I guess) around 15 seconds made it show up correctly in Phoscon.

And, I hope, stop controlling all lights directly?

Next time before posting screen shot, please read the attribute first.  No need to do that now, since we know the switch is recognised.  Also next time, please also provide the _Node Info_ panel.

**Comment by jdeluyck** [comment]
> And, I hope, stop controlling all lights directly?
Yes, this indeed now also stopped occurring. 

> Next time before posting screen shot, please read the attribute first. No need to do that now, since we know the switch is 
recognised. Also next time, please also provide the _Node Info_ panel.

Ah, apologies - I didn't quite think that through.

**Comment by SAOPP** [comment]
@ebaauw it's mine:

![image](https://user-images.githubusercontent.com/5647009/88456346-a4dadb00-ce85-11ea-8851-91eec3c0edca.png)
![image](https://user-images.githubusercontent.com/5647009/88456351-b328f700-ce85-11ea-82f5-884a6c94049a.png)
![image](https://user-images.githubusercontent.com/5647009/88456353-bb813200-ce85-11ea-85e5-0f38773d83f6.png)
![image](https://user-images.githubusercontent.com/5647009/88456366-d2c01f80-ce85-11ea-8d0b-a3fa92e1d901.png)
![image](https://user-images.githubusercontent.com/5647009/88456369-dbb0f100-ce85-11ea-8b33-b36b6e1b59c2.png)

 I read all info of node. Anything else is needed?

**Comment by ebaauw** [comment]
That's the same _Model Identifier_, _Manufacturer Name_, and _Date Code_ as mine.  Also the same mac address prefix.  You didn't post the _Node Info_ panel to double check the _Manufacturer Code_, but that's probably 0x1014 as well.   I should pair.

Note that only the first two endpoints are listed: the others should have appeared when pressing the other buttons.  This could be indicative for Zigbee communication issues, which would definitely frustrate the pairing process.

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/88456812-9db5cc00-ce89-11ea-9b33-5c92693ce1e1.png)

**Comment by ebaauw** [comment]
Yep, that's the one.

**Comment by SAOPP** [comment]
So, 0x115f is any news?

**Comment by SwoopX** [comment]
No, it ahs been introduced with the support of those switches as I recall.

**Comment by SAOPP** [comment]
clear, well then, guys, I don't know what to do, I have 2 independent instances and the same behavior with 3 different switches.

**Comment by SAOPP** [comment]
literally 10 minutes ago I tried again to connect the 6-button switch on conbee2. And it all worked out :) Moreover, I didn't press any buttons during the pairing process. Everything turned out as usual.

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/88463515-0158ed00-cebc-11ea-8b6b-bd4427c6e06a.png)
All works fine, in HA has the events.

**Comment by cllatser** [comment]
I have the six button and it works very well with ConBee II.

**Comment by Mimiix** [comment]
So it is solved? @SAOPP

**Comment by SAOPP** [comment]
Well, on of my 3 switches are connected to conbee 2 without any clicking buttons through pairing process.

**Comment by mprajsler** [comment]
Hello guys,

It seems I got similar issue as mentioned here. I use Conbee stick with hassio installed on rpi4. I successfully paired Aqara OPPLE switch 3-gang WXCJKG13LM via Phoscon GUI but it controls nearby devices without any setup from my side. Is there any setting I should disable so I can use it how I want?

Thanks and Regards,
M.

**Comment by mprajsler** [comment]
This seems to help me to create a group and bind all buttons there
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2061#issuecomment-567380475

**Comment by SAOPP** [comment]
I got to connect the next my opple switch, and again the same behaviour, I have paired 15 times already, all the time it connected like directly paired. I'm turn off all my routers/bulbs, and nothing. I saw posts like a short press on the C button helps to select the correct mode during pairing, but somehow it does not help me. :D

**Comment by Mimiix** [comment]
You need to click the C after pairing :)

**Comment by SAOPP** [comment]
Yes ... it seems like it worked from the 20th time :)

**Comment by Lyra1337** [comment]
Same here, I repaired the switch for dozen of times to my deconz. No matter if I press the C switch on the back. It always controls all my zigbee devices at once. Is there a way to get it into the correct mode?

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4589#issuecomment-804348316.

**Comment by Lyra1337** [comment]
> 
> 
> See [#4589 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4589#issuecomment-804348316).

Thank you for pointing me there. I tried to do so, but in my new switch (i already have one successfully paired - somehow) doesn't has your described Multistate Input.

(left one works, right one controls ALL my zigbee switches at once)
![grafik](https://user-images.githubusercontent.com/8735461/115073944-5086f800-9ef9-11eb-8f07-4612ac5b47f8.png)

**Comment by ebaauw** [comment]
The Opples don't poll their parent when you press any of the front buttons.  You need to press the button on the back to make it reachable by the coordinator (e.g. when reading/writing attributes or reading the descriptors).
