### ISSUE TITLE
BlitzWolf Contact Sensor BW-IS2

### ISSUE THREAD

**Issue by nunokaneco** [dresden-elektronik/deconz-rest-plugin#3075]
please can you include  this is  sensor BlitzWolf Contact Sensor BW-IS2
![image](https://user-images.githubusercontent.com/33290686/88399206-662e1d80-cdbe-11ea-96da-f5ed2cd33bb7.png)

Thank you and best regards

**Comment by SwoopX** [comment]
Closing this as device is already supported.

**Comment by nunokaneco** [comment]
The device is still not supported
