### ISSUE TITLE
BlitzWolf Water Leak Sensor BW-IS5

### ISSUE THREAD

**Issue by nunokaneco** [dresden-elektronik/deconz-rest-plugin#3076]
can you please add this is device sensor BlitzWolf Water Leak Sensor    BW-IS5

![image](https://user-images.githubusercontent.com/33290686/88398950-05064a00-cdbe-11ea-8d63-9107b050487c.png)

**Comment by SwoopX** [comment]
Closing this due to incomplete information.

**Comment by Mimiix** [comment]
For those ending up here. Please follow: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3067
