### ISSUE TITLE
Tuya Smart TRV HY369RT Thermostatic Radiator Valve

### ISSUE THREAD

**Issue by vegetate7** [dresden-elektronik/deconz-rest-plugin#3078]
## Device
![Screenshot_20200725_043311](https://user-images.githubusercontent.com/57148620/88440512-f8bad500-ce2f-11ea-8377-790973e1d55d.png)

- Product name: Tuya Smart TRV HY369RT.
- Manufacturer: _TZE200_ckud7u2l.
- Model identifier: TS0601.
- Device type : Please remove all unrelated device types. 
  - Thermostat

## Screenshots

Node info:
![Screenshot_20200725_041215](https://user-images.githubusercontent.com/57148620/88440518-fe181f80-ce2f-11ea-8843-6d10ede6aae2.png)

Basic cluster:
![Screenshot_20200725_041345](https://user-images.githubusercontent.com/57148620/88440536-0f612c00-ce30-11ea-81cd-979b59023d45.png)

0xEF00 cluster:
![Screenshot_20200725_041406](https://user-images.githubusercontent.com/57148620/88440550-1f790b80-ce30-11ea-9f96-bef664ba7817.png)

**Comment by KekieM** [comment]
I have one laying around did not have the time to test is.
