### ISSUE TITLE
Aqara Smart Wall Switch Single Rocker

### ISSUE THREAD

**Issue by jdonofrio728** [dresden-elektronik/deconz-rest-plugin#3083]
## Device

- Product name: Aqara Smart Wall Switch Single Rocker
- Manufacturer: LUMI
- Model identifier: lumi.switch.b1naus01
- Device type : Please remove all unrelated device types. 
  - Light
  - Sensor
  - Thermostat

## Screenshots

Endpoints and clusters of the node and Node Info panel
![image](https://user-images.githubusercontent.com/10515329/88556663-46356e80-cff7-11ea-9956-106f811b2bfc.png)

Basic Cluster Attributes in the Cluster Info Panel:
![image](https://user-images.githubusercontent.com/10515329/88556592-31f17180-cff7-11ea-9d85-f89e154ef81e.png)

Simple Metering:
![image](https://user-images.githubusercontent.com/10515329/88556853-7da41b00-cff7-11ea-8a49-951590315dfc.png)

Electrical Measurement:
![image](https://user-images.githubusercontent.com/10515329/88557033-b80db800-cff7-11ea-82ee-b3f1a6bb4b89.png)

Alarms:
![image](https://user-images.githubusercontent.com/10515329/88556928-91e81800-cff7-11ea-85b4-cd4223fe14fe.png)

Device Temperature:
![image](https://user-images.githubusercontent.com/10515329/88556979-a4625180-cff7-11ea-9c23-446ae6a7d308.png)

**Comment by SwoopX** [comment]
@jdonofrio728 What switch model is this? Looks quite interesting...

**Comment by jdonofrio728** [comment]
@SwoopX From the box Model: WS-USC03

https://www.amazon.com/Aqara-REQUIRES-Automation-Compatible-Assistant/dp/B081ZRND3K/ref=sr_1_1_sspa

**Comment by SwoopX** [comment]
Thanks! Apart from the fact, that it looks fugly, I like the features I see from here.

**Comment by jdonofrio728** [comment]
lol it looks better than some of the cheaper ones that I have.
