### ISSUE TITLE
Neuhaus Lightning Group Q-VITO

### ISSUE THREAD

**Issue by haraldknoll** [dresden-elektronik/deconz-rest-plugin#3086]
Non of new (Model End 2019) Neuhaus Lightning Group lights can be integrated in the Phoscon App. Older Neuhaus Lightning Group lights work well. The new light  can not be joined at all. E.g. the Q-VITO Series https://www.paul-neuhaus.de/shop/de/q-vito-led-deckenleuchte-smart-home-d-79-4cm-44942.html

Current Setup:
-	Raspberry 4 with RaspBee II
-	Phoscon Version 2.05.79
-	Firmware RaspBee II – 26610700

## Device

- Product name: Q-VITO LED-Deckenlampe
- Manufacturer: Paul Neuhaus
- Model identifier: 
- Device type : 
  - Light

**Comment by ebaauw** [comment]
Do they show up in the GUI?  If so, please provide the screenshots mentioned in the wiki.  If not, there’s nothing we can do in the REST API plugin.

**Comment by haraldknoll** [comment]
I run all PI 4 devices headless. Is it possible to list all devices by command line? It is very likely that is will be seen on the network. Seem I have to install a GUI version. BTW: The device joins flawless on a Philips HUE bridge.

**Comment by ebaauw** [comment]
> BTW: The device joins flawless on a Philips HUE bridge.

That's good.  Now we just need the screenshots.

> I run all PI 4 devices headless.

I run all my Pi-s headless (without a monitor connected), but I still run the Pi's graphical environment and deCONZ in GUI mode.  Connecting to the VNC server is a piece of cake from macOS, using the mac's native screen sharing client.

> Is it possible to list all devices by command line?

No.  Using deCONZ without the GUI is like driving a Ferrari without using the gearbox.  It kinda works, but won't unlock the full power.

**Comment by haraldknoll** [comment]
Well, i made a setup with just one "old" Paul Neuhaus Light. It joins. Non of the new Paul Neuhaus Light e.g. Q-VITO Series appears in the deCONZ node list. The "light 3" is an old Paul Neuhaus light.  

![2020-07-29 13_55_32-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/88797192-3a86ab00-d1a3-11ea-80b4-09bf6d0d7560.png)

**Comment by haraldknoll** [comment]
After a while a device pops up which reports as HA simple sensor. Looks like a power save issue, but its a full powered light.

![2020-07-29 14_08_52-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/88798432-2cd22500-d1a5-11ea-9996-5ef387841c73.png)

**Comment by haraldknoll** [comment]
Here we have the Node Info.

![2020-07-29 14_15_00-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/88798914-f648da00-d1a5-11ea-8696-d866d15b246c.png)

**Comment by SwoopX** [comment]
Can you please read the attributes of the basic cluster and share the output? Thanks!

**Comment by haraldknoll** [comment]
Here we go ... 

![2020-07-29 15_07_09-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/88803797-4b3c1e80-d1ad-11ea-91fa-b99910facf54.png)

**Comment by SwoopX** [comment]
As written above, please **READ** the attributes.

**Comment by haraldknoll** [comment]
OK, back to start. Th 0x8ad4 is sensor an attribute read is not possible. Dont know what it is. The 0xC607 is the right one.  Here are the values:

![2020-07-29 15_33_19-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/88807538-239b8500-d1b2-11ea-8f77-8f23b7ec5c22.png)

![2020-07-29 15_40_53-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/88807557-2a29fc80-d1b2-11ea-9db0-bf137400ee64.png)

**Comment by SwoopX** [comment]
Alright, thanks. So, there we have it: your light doesn't expose itself as a light and that's the reason, why it is not recognized out of the box. It also does not expose any clusters or capabilities one would expect to see here. Not sure if that's really zigbee compliant.

Your "problem" is now exactly that. It doesn't even have an "on/off" cluster to switch it. My assumption is that all the functionality is hidden in the manufacturer specific 0xFC00 cluster, and that must be reverse engineered with the help of the device at hand and a sniffer. I don't have much hope that any information around that is publicly available.

I observe offloading functionality quite often these days. Probably the intention behind it is to make it harder for free projects to integrate the devices and kinda force the customer to buy their own products/gateways...

**Comment by haraldknoll** [comment]
Well, deleted node and did a search again. At  the end of the day the lamp was found with the following procedure. Open network and reset lamp. The other way e.g. lamp reset and open network after lamp reset never worked for me, Should we do a sniffer trace to see why the initial join will not work.  

Control of lamp seems to be OK. Looks like only the initial detection of the lamp is a bit sluggish.

![2020-07-31 09_18_29-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/89011363-84d96a80-d310-11ea-9ffe-8f4c8deb01d8.png)

![2020-07-31 09_18_50-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/89011457-a9cddd80-d310-11ea-85f8-f9d50da71902.png)

![2020-07-31 09_19_31-deCONZ - RaspBee (_dev_ttyS0)](https://user-images.githubusercontent.com/68897141/89011466-ae929180-d310-11ea-8a57-14b8f979f28a.png)

![2020-07-31 09_28_04-Phoscon App](https://user-images.githubusercontent.com/68897141/89011476-b2261880-d310-11ea-8930-25e9753ef3c4.png)
