### ISSUE TITLE
Phoscon does not find my deconz instance

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#309]
Is the phoscon web app supposed to find the deconz installation?
In my case it does not find anything. Also after a repeated try.
I have the latest deconz beta installed.

Maybe it is caused by deconz not running on its default port?

**Comment by manup** [comment]
Indeed it's the port, we will provide a input entry to enter custom ip-address:port in the next days.

Till then you can use the workaround:

`http://dresden-elektronik.de/pwa/login.html#host/<ip-address>:<port>`

**Comment by jo-me** [comment]
Perfect thanks! 
Finally all the sensors are visible in the UI ;)
