### ISSUE TITLE
Mijia Light Sensor

### ISSUE THREAD

**Issue by PainElemental** [dresden-elektronik/deconz-rest-plugin#3094]
- Product name: Mijia Light Sensor
- Manufacturer: LUMI
- Model identifier: lumi.sen_ill.mgl01
- Device type : 
  - Sensor
![NodeInfo](https://user-images.githubusercontent.com/52151581/88794986-93544480-d19f-11ea-96f2-3c3d4101b590.jpg)
![NodeInfo2](https://user-images.githubusercontent.com/52151581/88794989-93ecdb00-d19f-11ea-8114-9345fa245b46.jpg)
![NodeList](https://user-images.githubusercontent.com/52151581/88794991-94857180-d19f-11ea-977c-4ea68d0d92e8.jpg)

**Comment by PainElemental** [comment]
Unfortunately I was not able to retrieve ClusterInfo, because the Panel is empty and there is no "read" button.

**Comment by SwoopX** [comment]
Already supported.

**Comment by SwoopX** [comment]
Wait, the manufacturer code is different here.

**Comment by PainElemental** [comment]
It is not in the list of supported devices.
It works using OpenHAB and deconz binding, but does not show up in Phoscon.

**Comment by SwoopX** [comment]
It is in the list of supported devices

![grafik](https://user-images.githubusercontent.com/4005212/88795864-fb575a80-d1a0-11ea-9b60-dca291a71ce0.png)

**Comment by PainElemental** [comment]
OK, sorry. I was looking for "Mijia Light Sensor"...

What do I have to do to get this show up in Phoscon? Raise an issue there: https://github.com/dresden-elektronik/phoscon-app-beta ?

**Comment by SwoopX** [comment]
Either wait for DE to include the latest Phoscon changes in the deconz package or use the phoscon beta app from internet http://phoscon.de/pwabeta/login.html
