### ISSUE TITLE
Swann Home Key Fob: SWO-KEF1PA 

### ISSUE THREAD

**Issue by crixyd** [dresden-elektronik/deconz-rest-plugin#3098]
## Device

- Product name: Smart Home Key Fob Remote Control
- Manufacturer: SwannOne
- Model identifier: SWO-KEF1PA
- Device type : Remote

https://www.swann.com/au/swo-kef1pa
https://www.swann.com/media/wysiwyg/docs/en/Key_Fob_QSG.pdf

## Screenshots

![1](https://user-images.githubusercontent.com/53435824/88905286-756b0a80-d299-11ea-8909-746f16ab7a42.png)
![2](https://user-images.githubusercontent.com/53435824/88905291-7734ce00-d299-11ea-976d-df957502556f.png)
![3](https://user-images.githubusercontent.com/53435824/88905304-7865fb00-d299-11ea-8b0d-a174aae7c6e9.png)
![4](https://user-images.githubusercontent.com/53435824/88905306-78fe9180-d299-11ea-85ad-ddddadac84dc.png)
![5](https://user-images.githubusercontent.com/53435824/88905307-79972800-d299-11ea-8319-fde0ca0713c9.png)
![6](https://user-images.githubusercontent.com/53435824/88905309-7a2fbe80-d299-11ea-8a5e-61815f6734a5.png)

**Comment by Mimiix** [comment]
This device was already requested apparently. I'll check with the devs if anyone would take it.

For reference: #1085

**Comment by Smanar** [comment]
It s realy strange from https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1085 it seem this device is almost working but there is nothing in deconz about the cluster 0x0501

So I have just used information from previous issue to test.

Can you can try the code ? Procedure are on the github page, just chnage the step 1 by
git clone --branch  swann https://github.com/Smanar/deconz-rest-plugin.git

And you can skip "git checkout -b mybranch HEAD"

If I m right, you will have the device in the API
If the issue is right you will have 2 button working
And on log you will have "no button handler"with usefull data for the 2 others buttons.

**Comment by crixyd** [comment]
Ah damn, my apologies guys, I didn't think to search the closed issues given that it's a currently unsupported device. 

I'll try running your branch Smanar, thank you.

**Comment by Smanar** [comment]
Sorry, I have something wrong in my files (version mistake)
I will update the files tommorow.

**Comment by Smanar** [comment]
Ok So I have big problem with my github install, impossible to start on a clean base
So the PR is strange but it s the V 79 base just with the device added in whitelist.

Like I have said before, It s just the line described in the other issue, I can add more, but it seem they are not usefull, if someone can test it ?

**Comment by crixyd** [comment]
Hi Smanar, apologies for taking a while... I've had a couple of issues come up. Will be in touch with more info asap. Thanks!

**Comment by crixyd** [comment]
Hi Smanar, I have just received my new Conbee II and will begin testing with that. I have tried to clone the swann branch, but receive the following error `fatal: Remote branch swann not found in upstream origin`. How should I proceed?

**Comment by Smanar** [comment]
heeee, I have cleaned my fork recently and delete all old code.

So it s ok, I have remake the code.
After instaled the new code, you can include the device, from the other issue you will have 2 workings buttons.

For the 2 other I will explain later, but you will need to use debug.

**Comment by crixyd** [comment]
Hi Smanar,

When you say to install the new code, I presume you mean in an upcoming version of the rest plugin? What version should I look out for? Once i've done that I'll debug for the other two buttons...

Thanks!

**Comment by Smanar** [comment]
Just follow that https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3098#issuecomment-668158588

It will make a lib version V2_05_80 but modified for your device.
