### ISSUE TITLE
Konke Temp Humidty Sensor

### ISSUE THREAD

**Issue by schoven** [dresden-elektronik/deconz-rest-plugin#3099]
Hi, 
I would lie to request device support for Konke KIT PRO Temp Humidity Sensor 

Edit: Overlooked a previous request, i am sorry.  #2164
## Device

- Product name: KIT PRO Temp Humidity Sensor
- Manufacturer: Konke
- Model identifier:3AFE220103020000
- Device type : 
  - Sensor

## Screenshots
basic cluster &  enpoints

![image](https://user-images.githubusercontent.com/62767473/89102835-16c69d80-d40d-11ea-8ecb-265d1d01feac.png)

![image](https://user-images.githubusercontent.com/62767473/88972625-22ec1700-d2b6-11ea-92af-19e6b1ecc0a9.png)

node info panel:
![image](https://user-images.githubusercontent.com/62767473/88972902-8fffac80-d2b6-11ea-8e10-acb702019046.png)

Temperature measurement cluster:
![image](https://user-images.githubusercontent.com/62767473/88973026-c806ef80-d2b6-11ea-8d01-302ad7f5c2c5.png)
Relative humidity measurement cluster:
![image](https://user-images.githubusercontent.com/62767473/88973145-f4227080-d2b6-11ea-811d-e1602464b3aa.png)

**Comment by Mimiix** [comment]
This device was already requested apparently. I'll check with the devs if anyone would take it. 

For reference: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1085

**Comment by Smanar** [comment]
Hello I need the complete table in your first capture ^^
You have cut all usefull informations

**Comment by schoven** [comment]
> 
> 
> Hello I need the complete table in your first capture ^^
> You have cut all usefull informations and the previous issue are missing all informations too.

Updated the picture. Thank you for looking into this!

**Comment by Smanar** [comment]
@schoven missed ^^.
You have empty values, you need to press the "read" button and make the sensor awake in same time (with pressing shortly the pairing button for exemple)

**Comment by schoven** [comment]
Done, pressing the read button in deconz & physical device pairing button simultaniously worked

**Comment by Smanar** [comment]
Ok so was a "2 line edition device" so I have used another PR to add it.

If you can to test it, follow the procedure on github mainpage with chnaging the step 1 by
`git clone --branch Legrand-teleruptor https://github.com/Smanar/deconz-rest-plugin.git`

and can skip the "git checkout -b mybranch HEAD"

You nee dto re-include the device using phoscon, no need to delete it.

**Comment by schoven** [comment]
I tried, but i have to admit i am to much of a noob to do so. Am running deconz ons hass.os and have no experience with Linux.

**Comment by Smanar** [comment]
Yep, better to use another machine for test.
Else you will have in next version but without test, so not sure it will work, and need to wait 30 days again for modifications.
