### ISSUE TITLE
Question about deconz GUI

### ISSUE THREAD

**Issue by PainElemental** [dresden-elektronik/deconz-rest-plugin#3104]
Deconz shows the mesh network of my zigbee devices. But one of my "Aquara water sensors" does not have a line that connects it to the other devices. What does that mean?
It does not seem to be offline as it's "last seen" status gets updated.

![Bildschirmfoto vom 2020-07-30 10-07-18](https://user-images.githubusercontent.com/52151581/89063541-a1a18c80-d368-11ea-86be-2ce8338cfc03.png)

**Comment by Mimiix** [comment]
Hi!

The lines are just a indication and based on neighbour tables. Sometimes they glitch a bit, so if everything works: Don't worry about it ;)
