### ISSUE TITLE
Sengled Element Bulbs

### ISSUE THREAD

**Issue by mercenaryballs** [dresden-elektronik/deconz-rest-plugin#311]
I have these bulbs paired with my Conbee. I can see them in the GUI, but they do not show up in the web app. I believe they are unsupported. I can control them in the GUI (on/off and level control). Here are the atttributes: 

![image](https://user-images.githubusercontent.com/34362886/33752311-2291a6c2-dbaf-11e7-9e23-26554e2aca68.png)
![image](https://user-images.githubusercontent.com/34362886/33752373-817f909a-dbaf-11e7-8300-dd8c6e8cfb62.png)
![image](https://user-images.githubusercontent.com/34362886/33752390-908fb16e-dbaf-11e7-9dbe-72775c2ac014.png)
![image](https://user-images.githubusercontent.com/34362886/33752419-a89f1a24-dbaf-11e7-9fe8-74f0f3b0913f.png)
![image](https://user-images.githubusercontent.com/34362886/33752469-edbc1440-dbaf-11e7-9e71-f6fa6aa6106b.png)
![image](https://user-images.githubusercontent.com/34362886/33752483-fe21d392-dbaf-11e7-88ac-3b4b903d45d4.png)
![image](https://user-images.githubusercontent.com/34362886/33752568-77b97c82-dbb0-11e7-879d-c45558ae6239.png)
![image](https://user-images.githubusercontent.com/34362886/33752573-81b32170-dbb0-11e7-9441-9dae69d796eb.png)
![image](https://user-images.githubusercontent.com/34362886/33752577-8d63dd66-dbb0-11e7-9250-f4d50bc983f2.png)
![image](https://user-images.githubusercontent.com/34362886/33752584-9a48654c-dbb0-11e7-9bad-0441866b5a91.png)
![image](https://user-images.githubusercontent.com/34362886/33752592-a663c59c-dbb0-11e7-9ee8-8074c104232a.png)
![image](https://user-images.githubusercontent.com/34362886/33752598-ae9f54ba-dbb0-11e7-97b0-69a04b2df1f4.png)
![image](https://user-images.githubusercontent.com/34362886/33752605-b965afb6-dbb0-11e7-958b-1f217f7ca077.png)
![image](https://user-images.githubusercontent.com/34362886/33752608-c23f4caa-dbb0-11e7-9d30-55639d43c282.png)
![image](https://user-images.githubusercontent.com/34362886/33752618-cf5769a4-dbb0-11e7-8b89-04e4b07f90f1.png)
![image](https://user-images.githubusercontent.com/34362886/33752625-dad0ee90-dbb0-11e7-91d1-6c7c91756862.png)

**Comment by mysteryan** [comment]
I would try power cycling them.  If it doesnt discover properly, I would manually edit the session.default file and manually input working Extended and Simple Descriptors for that node.

**Comment by manup** [comment]
Normally it should work since this seems to be a simple HA Dimmable Light with no special integration needed. Can you provide output by REST API?

**Comment by mercenaryballs** [comment]
It does not show up in the Web App or the rest API. I have tried searching
for lights in the web app, but that seems to do the same thing as when I
open the network in the deconz gui. Here is the API output:

{
>
> "config":{
>
> "UTC": "2017-12-08T05:20:38",
>
> "apiversion": "1.0.4",
>
> "backup":{
>
> "errorcode": 0,
>
> "status": "idle"
>
> },
>
> "bridgeid": "00212EFFFF013EF7",
>
> "datastoreversion": "60",
>
> "devicename": "ConBee",
>
> "dhcp": true,
>
> "factorynew": false,
>
> "gateway": "192.168.10.1",
>
> "internetservices":{
>
> "remoteaccess": "disconnected"
>
> },
>
> "ipaddress": "192.168.10.15",
>
> "linkbutton": false,
>
> "localtime": "2017-12-08T00:20:38",
>
> "mac": "1c:1b:0d:9a:b0:ce",
>
> "modelid": "deCONZ",
>
> "name": "deCONZ-GW",
>
> "netmask": "255.255.255.0",
>
> "networkopenduration": 60,
>
> "panid": 38530,
>
> "portalconnection": "disconnected",
>
> "portalservices": false,
>
> "portalstate":{"communication": "disconnected", "incoming": false,
>> "outgoing": false, "signedon": false…},
>
> "proxyaddress": "none",
>
> "proxyport": 0,
>
> "replacesbridgeid": null,
>
> "starterkitid": "",
>
> "swupdate":{"checkforupdate": false, "devicetypes":{"bridge": false,
>> "lights":[], "sensors":[]…},
>
> "swupdate2":{"autoinstall":{"on": false, "updatetime": "" },
>> "bridge":{"lastinstall": "",…},
>
> "swversion": "2.4.94",
>
> "timeformat": "12h",
>
> "timezone": "none",
>
> "uuid": "0f333de3-b06e-4f65-ad63-7a0d23d5bf5e",
>
> "websocketnotifyall": true,
>
> "websocketport": 443,
>
> "whitelist":{
>
> "2C807EC599":{
>
> "create date": "2017-12-08T03:30:07",
>
> "last use date": "2017-12-08T05:20:28",
>
> "name": "deCONZ WebApp"
>
> },
>
> "988112a4e198cc1211":{
>
> "create date": "2017-12-08T04:31:48",
>
> "last use date": "2017-12-08T05:20:38",
>
> "name": "my application"
>
> },
>
> "F266FF0A54":{
>
> "create date": "2017-12-08T04:22:12",
>
> "last use date": "2017-12-08T05:14:29",
>
> "name": "Phoscon#B2560x900"
>
> }
>
> },
>
> "zigbeechannel": 15
>
> },
>
> "groups":{
>
> },
>
> "lights":{
>
> },
>
> "rules":{
>
> },
>
> "schedules":{
>
> },
>
> "sensors":{
>
> }
>
> }
>
>

Thanks,

Thomas Pendergrass
thomas.pendergrass@gmail.com
804-874-2570  Cell

On Fri, Dec 8, 2017 at 2:44 PM, Manuel Pietschmann <notifications@github.com

**Comment by manup** [comment]
You may retry with version 2.04.96, we have improved light detection there, it may help here.
After update I recommend to power cycle the lights to speed up discovery.

**Comment by mercenaryballs** [comment]
I just got around to retrying this. Version 2.04.99 now. Still having the same issue. The lights are shown and can be controlled in the desktop app, but they are not shown in the web app or rest api.
![image](https://user-images.githubusercontent.com/34362886/35027510-19902906-fb1f-11e7-9795-0952d7716b4a.png)

`BODY
raw 
{"config":{"UTC":"2018-01-17T05:38:00","apiversion":"1.0.4","backup":{"errorcode":0,"status":"idle"},"bridgeid":"00212EFFFF013EF7","datastoreversion":"60","devicename":"ConBee","dhcp":true,"factorynew":false,"gateway":"192.168.10.1","internetservices":{"remoteaccess":"disconnected"},"ipaddress":"192.168.10.15","linkbutton":true,"localtime":"2018-01-17T00:38:00","mac":"1c:1b:0d:9a:b0:ce","modelid":"deCONZ","name":"deCONZ-GW","netmask":"255.255.255.0","networkopenduration":60,"panid":38530,"portalconnection":"disconnected","portalservices":false,"portalstate":{"communication":"disconnected","incoming":false,"outgoing":false,"signedon":false},"proxyaddress":"none","proxyport":0,"replacesbridgeid":null,"starterkitid":"","swupdate":{"checkforupdate":false,"devicetypes":{"bridge":false,"lights":[],"sensors":[]},"notify":false,"text":"","updatestate":0,"url":""},"swupdate2":{"autoinstall":{"on":false,"updatetime":""},"bridge":{"lastinstall":"","state":"noupdates"},"checkforupdate":false,"install":false,"lastchange":"","lastinstall":"","state":"noupdates"},"swversion":"2.4.99","timeformat":"12h","timezone":"none","uuid":"0f333de3-b06e-4f65-ad63-7a0d23d5bf5e","websocketnotifyall":true,"websocketport":443,"whitelist":{"2C807EC599":{"create date":"2017-12-08T03:30:07","last use date":"2018-01-17T05:37:31","name":"deCONZ WebApp"},"8F61CDD11E":{"create date":"2018-01-17T05:37:38","last use date":"2018-01-17T05:38:00","name":"my application"},"988112a4e198cc1211":{"create date":"2017-12-08T04:31:48","last use date":"2017-12-08T05:20:38","name":"my application"},"F266FF0A54":{"create date":"2017-12-08T04:22:12","last use date":"2017-12-09T06:46:28","name":"Phoscon#B2560x900"}},"zigbeechannel":15},"groups":{},"lights":{},"rules":{},"schedules":{},"sensors":{"1":{"config":{"on":true,"reachable":true},"ep":1,"etag":"a223b40012aa853f966daafeb7884cf0","manufacturername":"LUMI","modelid":"lumi.sensor_magnet.aq2","name":"OpenClose 1","state":{"lastupdated":"2017-12-22T06:11:08","open":false},"type":"ZHAOpenClose","uniqueid":"00:15:8d:00:01:e4:4d:ae-01-0006"}}}`

**Comment by staraxis** [comment]
I have the same issue with a Sengled bulb as well. Shows up and can be controlled via the GUI but not available in the rest API or the webapp. Any workaround or update on this?

**Comment by ebaauw** [comment]
Looks like another end-device light.  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/356#issuecomment-358759456.

**Comment by staraxis** [comment]
Thanks @ebaauw , is there an update on the way to fix this?

**Comment by ebaauw** [comment]
You'll have to ask @manup.  I don't feel comfortable messing with this part of the code.

**Comment by manup** [comment]
Hi I've put it on the todo list should be solved soon, as noted currently only router lights will be recognized by the API.

**Comment by staraxis** [comment]
Any update on the addition of end-device lights to the API and/or webapp? Thanks

**Comment by ebaauw** [comment]
I see @manup included my PR in v2.05.02.  I think they should be recognised by that version, but cannot test myself as I don't have any end-device light or plug.

**Comment by staraxis** [comment]
Thanks @ebaauw and @manup I can confirm that my sengled light is now available via the webapp and also in my Home Assistant UI after updating to v2.05.02. On/Off and brightness work as expected. Cheers

**Comment by mercenaryballs** [comment]
My bulbs are working as well. They show up on the phoscon app and in the REST API.
