### ISSUE TITLE
Trust ZYCT ‑202 - different Manufacture code

### ISSUE THREAD

**Issue by opechunka** [dresden-elektronik/deconz-rest-plugin#3117]
Manufacture code  on my device is  0x122d. 
Which is different than in current source - #define VENDOR_JENNIC       0x1037 // Used by Xiaomi, Trust, Eurotronic

I tried to change the code from 0x1037  to 0x122d and make my local build. Unfortunately deCONZ crashes when I tried to add the device via Phoscon. 
What is strange also, deCONZ GUI doesn't show any cluster info for ZYCT-202

Can it be fixed?   

![ZYCT-202](https://user-images.githubusercontent.com/56726756/89407675-7a0f4300-d71f-11ea-95c0-4edea3253867.png)
![ZYCT-202_2](https://user-images.githubusercontent.com/56726756/89408351-8516a300-d720-11ea-85ce-96248b6b551b.png)

**Comment by Mimiix** [comment]
Hi @opechunka 😄 
I am tempted to close this issue, as you left out vital information as per requested in the bug report template.  Please add this information.

Thanks!

**Comment by SwoopX** [comment]
From what I've read, the devices are a little bit stubborn. Try entering sensor search in Phoscon and then read the simple descriptors (from the bullet you've marked). Please make sure the device is awake, so press a button right before reading the descriptors.

The current code shouldn't require any code changes, as there's also a check on the MAC address prefix, which hasn't changed in your case.

**Comment by opechunka** [comment]
After I've removed all routers and left just RaspBee, I've managed to add ZYCT-202.  It works, thank you.
