### ISSUE TITLE
How can i restore files from a sdcard ? 

### ISSUE THREAD

**Issue by sam-75** [dresden-elektronik/deconz-rest-plugin#3122]
How can i restore files from SDCard 
/home/pi/.local/share/dresden-elektronik  does not exist ?
only to .local after that the folder is empty ... where are the place of the deconz files to backup and restore.

Regards,
marc

**Comment by Mimiix** [comment]
Hi!

There is a lot of information missing as you removed the template information. Add that information as per template or i will close this.
