### ISSUE TITLE
Sunricher Remote control ZGRC-KEY-13 / same as iCasa ICZB-RM11S

### ISSUE THREAD

**Issue by rweise** [dresden-elektronik/deconz-rest-plugin#3125]
<img width="442" alt="Bildschirmfoto 2020-08-07 um 06 28 17" src="https://user-images.githubusercontent.com/13751410/89611312-29156100-d87d-11ea-8e5b-2c21096d40f8.png">
i have both black remote controls with one pair Mater ON/OFF , 4 pairs ON/Off and S1 and S2 Button.
the iCasa is not shown in Phoscon after Installation there was only the Message that it was fine.
the sunricher is shown as a switch in Phoscon.
In IOBroker, Icasa has 1 Buttonevent and shows there a different Buttonevent for Pairs 1-4 and S1 S2. 
sunricher has 4 different sensors and will only have a value for keyevent for Pair 1 that is the same as master ON/OFF. 
Both have the same Firmware! 
<img width="1084" alt="Bildschirmfoto 2020-08-07 um 06 42 16" src="https://user-images.githubusercontent.com/13751410/89611076-7e9d3e00-d87c-11ea-9be4-257c585ae981.png">
<img width="607" alt="Bildschirmfoto 2020-08-07 um 06 36 20" src="https://user-images.githubusercontent.com/13751410/89611120-a55b7480-d87c-11ea-80bc-5d99ee6438d0.png">

Here are the screenshots
<img width="607" alt="Bildschirmfoto 2020-08-07 um 06 37 52" src="https://user-images.githubusercontent.com/13751410/89611194-d9cf3080-d87c-11ea-96f3-2bca813cc7ca.png">
<img width="628" alt="Bildschirmfoto 2020-08-07 um 06 40 07" src="https://user-images.githubusercontent.com/13751410/89611210-e489c580-d87c-11ea-85dc-4f226672db5b.png">

**Comment by alexdepalex** [comment]
fyi: The remote works perfectly fine in hassio when using events.

**Comment by SwoopX** [comment]
Seems to be the same as #2857 and #1256. The icasa and the Sunricher have been implemented differently though. I'll see that we can streamline that.
