### ISSUE TITLE
"Leichen" bei den Objekten - wie loswerden?

### ISSUE THREAD

**Issue by Michaelnorge** [dresden-elektronik/deconz-rest-plugin#3128]
Ich benutze eine Raspberry mit Conbee-II, Phoscon/Deconz und ioBroker.

Ich hatte Rolläden von IKEA verbunden, war nicht zufrieden und hab sie wieder gelöscht.
In der Phoscon-App sind die Rolläden verschwunden, aber unter ioBroker sehe ich noch Einträge der Rolläden.
Komischer Weise befinden sich diese Einträge bei den Sensoren!!

Ich nutze das System headless und hab wenig Ahnung von Linux.
Kann man per Kommando vielleicht eine Liste abrufen und unerwünschte Einträge manuell löschen?

![1](https://user-images.githubusercontent.com/42386692/89737123-eca95700-da6e-11ea-8c1f-8b297bb0abb8.jpg)

**Comment by Mimiix** [comment]
Hi there

As this git is English only, I am closing this issue.

Please use Google translate to help out or contact support directly.

**Comment by Jey-Cee** [comment]
@Michaelnorge https://github.com/iobroker-community-adapters/ioBroker.deconz/issues or forum.iobroker.net is the right place for your question.
