### ISSUE TITLE
Samsung GP-U999SJVLAEA SmartThings Multipurpose sensor vibration not working

### ISSUE THREAD

**Issue by guytaylor** [dresden-elektronik/deconz-rest-plugin#3129]
Sorry if it's poor form to re-open a closed issue but I am getting this bug so I thought I would.
The old bug is here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1848

I set up Samsung GP-U999SJVLAEA SmartThings Multipurpose with deconz and the vibration sensor appears but never seems to trigger, even if I shake the unit.

@ebaauw, did you ever have any luck in getting this working? If there is anything I can do to assist please ask.
Thank you

**Comment by ebaauw** [comment]
See #1848, the sensor is working fine for me.

Does the `state` of the `ZHAVibration` `/sensors` resource change when you read the attributes of the 0xFC02 cluster in the GUI while shaking the sensor?

**Comment by guytaylor** [comment]
Hi, 
I've included a pic of what I think you asked (sorry, I'm new to deconz!).
When I click the read button on the left, and tapped the sensor, none of the value changed.

![image](https://user-images.githubusercontent.com/34499540/89891932-42b9fe00-dc19-11ea-9d9c-8c7e0ed6b775.png)

**Comment by ebaauw** [comment]
It might take a couple of attempts.

If the sensor really doesn’t return any values here, I’m afraid it’s an issue with the sensor itself and there’s nothing we can do in deCONZ.

**Comment by guytaylor** [comment]
I removed the sensors and re-added it. and this time it is now working. thanks
