### ISSUE TITLE
Zemismart New Design Zigbee 3.0 Wall Push Light Switch

### ISSUE THREAD

**Issue by allanlopesprado** [dresden-elektronik/deconz-rest-plugin#3139]
Product name: Zemismart New Design Zigbee 3.0 Wall Push Light Switch SmartThings Control US AU Physical Switches
Manufacturer: FeiBit (ZemiSmart)
Model identifier: FNB56-ZSW01LX2.0
Device type : Switch (One Gang)
Link Device: https://www.zemismart.com/products/zemismart-au-wifi-wallush-light-switch-alexa-google-home-enable-smart-life-app-controlone-gang-two-gangs-three-gangs

**Screenshot of the Basic cluster**
![Cluster Info](https://user-images.githubusercontent.com/17826867/90195425-b7b74000-dd9f-11ea-8054-54ed2b2cb7bf.png)

**Screenshot of the Node Info Panel**
![Node Info](https://user-images.githubusercontent.com/17826867/90195509-fd740880-dd9f-11ea-9463-35ed83d059cf.png)

**Comment by Smanar** [comment]
But this device don't work natively ?

**Comment by allanlopesprado** [comment]
> But this device don't work natively ?

Yes it works, but it is being recognized as Light and not as Switchs, is that correct?

![LIGHT](https://user-images.githubusercontent.com/17826867/90289515-69af4480-de52-11ea-94dc-f715b5b6d0a1.png)

**Comment by Smanar** [comment]
No it s normal ^^.

It s a long story, with different idea, my personnal explanation is switches are actuators and light is receiver. With switch you can send command, but your device receive order to open or close the circuit.

Battery switch are sensor/switch.
Wired switch are light.

**Comment by allanlopesprado** [comment]
Perfect, so we can close the request

Thanks for your time and explanation
