### ISSUE TITLE
Non stop logging (Home Assistant)

### ISSUE THREAD

**Issue by ASNNetworks** [dresden-elektronik/deconz-rest-plugin#3142]
## Describe the bug

So I'm not sure if this is normal, I haven't paid attention to it too much before. But deCONZ is constantly logging and saying to not close database. It's litterally non-stop, 24/7. I restarted the add-on and it still has this behaviour. The reason I checked, is because a light was not working correctly at the same time. That seems to be fixed (I paired it again). But it's still logging non stop. 

## Steps to reproduce the behavior

Nothing

## Expected behavior

I expect it not to keep logging every second, but only when events occur or restarted.

## Environment

 - Host system: Raspberry Pi 4 (4GB)
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26580700
 - deCONZ version: 2.05.79 / 22-05-2020
 - Device: ConBee II
 - Do you use an USB extension cable: yes 

### deCONZ Logs

This is the log:

11:51:35:068 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:51:35:178 ZCL configure reporting rsp seq: 24 0x90FD9FFFFE715946 for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
11:51:35:212 ZCL configure reporting rsp seq: 25 0x90FD9FFFFE715946 for ep: 0x01 cluster: 0x0008 attr: 0x0000 status: 0x00
11:51:40:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:51:40:972 don't close database yet, keep open for 900 seconds
11:51:45:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:51:50:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:51:50:080 Current channel 25
11:51:50:088 Device TTL 7020 s flags: 0x6
11:51:51:971 don't close database yet, keep open for 900 seconds
11:51:55:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:51:57:100 don't close database yet, keep open for 900 seconds
11:52:00:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:05:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:09:616 0x00158D0004B275E8 error APSDE-DATA.confirm: 0xE9 on task
11:52:10:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:13:120 don't close database yet, keep open for 900 seconds
11:52:15:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:20:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:21:349 button 3001 Move Down
11:52:21:531 button 3003 Stop
11:52:21:879 don't close database yet, keep open for 900 seconds
11:52:25:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:28:983 don't close database yet, keep open for 900 seconds
11:52:30:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:31:629 ZCL attribute report 0x7CB03EAA00B035A2 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:52:34:084 don't close database yet, keep open for 900 seconds
11:52:34:639 ZCL attribute report 0x7CB03EAA00B035A2 for cluster: 0x0008, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:52:35:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:39:903 don't close database yet, keep open for 900 seconds
11:52:40:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:45:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:46:082 don't close database yet, keep open for 900 seconds
11:52:50:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:52:50:080 Current channel 25
11:52:50:088 Device TTL 6960 s flags: 0x6
11:52:55:094 don't close database yet, keep open for 900 seconds
11:52:55:095 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:53:00:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:53:02:454 no button map for: lumi.sensor_wleak.aq1 ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 001
11:53:02:454 ZCL attribute report 0x00158D0001BB9237 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
11:53:02:454 0x00158D0001BB9237 extract Xiaomi special attribute 0xFF01
11:53:02:454 	01 battery 3065 (0x0BF9)
11:53:02:454 	03 temperature 32 °C
11:53:02:454 	04 unknown 5032 (0x13A8)
11:53:02:454 	05 RSSI dB (?) 206 (0x00CE)
11:53:02:454 	06 LQI (?) 8589934850 (0x0200000102)
11:53:02:454 	08 unknown 516 (0x0204)
11:53:02:454 	0a unknown 0 (0x0000)
11:53:02:454 	64 on/off 0
11:53:10:066 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:53:11:087 don't close database yet, keep open for 900 seconds
11:53:14:655 ZCL attribute report 0x7CB03EAA00B035A2 for cluster: 0x0300, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:53:19:922 don't close database yet, keep open for 900 seconds
11:53:21:295 ZCL attribute report 0x7CB03EAA0A025CC4 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:53:26:081 don't close database yet, keep open for 900 seconds
11:53:28:655 ZCL attribute report 0x7CB03EAA00B035A2 for cluster: 0x0300, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:53:33:920 don't close database yet, keep open for 900 seconds
11:53:45:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:53:46:975 don't close database yet, keep open for 900 seconds
11:53:50:068 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:53:50:083 Current channel 25
11:53:50:091 Device TTL 6899 s flags: 0x6
11:53:57:118 don't close database yet, keep open for 900 seconds
11:54:10:081 don't close database yet, keep open for 900 seconds
11:54:20:084 don't close database yet, keep open for 900 seconds
11:54:25:068 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:54:27:719 ZCL attribute report 0x7CB03EAA00B035A2 for cluster: 0x0300, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:54:27:745 ZCL attribute report 0x7CB03EAA00B035A2 for cluster: 0x0300, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:54:27:970 don't close database yet, keep open for 900 seconds
11:54:30:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:54:37:080 don't close database yet, keep open for 900 seconds
11:54:46:078 don't close database yet, keep open for 900 seconds
11:54:50:079 Current channel 25
11:54:50:087 Device TTL 6839 s flags: 0x6
11:55:00:083 don't close database yet, keep open for 900 seconds
11:55:05:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:55:07:079 don't close database yet, keep open for 900 seconds
11:55:10:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
11:55:16:132 dev /dev/ttyAMA0
11:55:16:133 GW firmware version: 0x26580700
11:55:16:133 GW firmware version is up to date: 0x26580700
11:55:16:956 don't close database yet, keep open for 900 seconds
11:55:23:086 don't close database yet, keep open for 900 seconds
11:55:31:084 don't close database yet, keep open for 900 seconds
11:55:35:265 ZCL attribute report 0x7CB03EAA0A0131F1 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:55:39:075 	0x7CB03EAA0A00DD99 force poll (2)
11:55:39:117 ZCL attribute report 0x7CB03EAA0A00DD99 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:55:40:090 don't close database yet, keep open for 900 seconds
11:55:40:530 	0x7CB03EAA0A00DD99 force poll (2)
11:55:40:567 ZCL attribute report 0x7CB03EAA0A00DD99 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
11:55:45:257 don't close database yet, keep open for 900 seconds
11:55:46:933 ZCL attribute report 0x00158D00028350F7 for cluster: 0x000D, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
11:55:50:084 Current channel 25
11:55:50:092 Device TTL 6779 s flags: 0x6
11:55:52:085 don't close database yet, keep open for 900 seconds
11:55:57:969 don't close database yet, keep open for 900 seconds
11:56:01:940 ZCL attribute report 0x00158D00028350F7 for cluster: 0x000D, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
11:56:07:082 don't close database yet, keep open for 900 seconds
11:56:15:067 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)

**Comment by Mimiix** [comment]
AS far as i knew, we were going to remove this message. I just did a PR to do this. Thanks for the headsup!

Also: You should check on the device with mac: 00158D0004B275E8 

It gives a error:
`11:52:09:616 0x00158D0004B275E8 error APSDE-DATA.confirm: 0xE9 on task`

For reference on this: 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log

**Comment by ASNNetworks** [comment]
@Mimiix thanks for your quick reply!

The error you mention is one of two INNR E14 lightbulbs. I also saw 0x00158D0004B2EA6D  as an error, which is the second E14. I removed both and paired them again, restarted HA. Still gives that line though... How can I debug what that error is?

**Comment by Mimiix** [comment]
Your welcome. My PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3144



The 0x00 is not a error , the 0xE9 on task is the error. The 0x00 line is the MacAdress of the device.

This seems like a connection issue but it is hard to tell what the issue is. Do you have discord? It might be easier to help you there

**Comment by ASNNetworks** [comment]
> Your welcome. My PR: #3144
> 
> The 0x00 is not a error , the 0xE9 on task is the error. The 0x00 line is the MacAdress of the device.
> 
> This seems like a connection issue but it is hard to tell what the issue is. Do you have discord? It might be easier to help you there

I'm sorry, I meant I saw the same error for that device. So:

13:21:15:113 0x00158D0004B2EA6D error APSDE-DATA.confirm: 0xE9 on task
13:21:33:712 0x00158D0004B275E8 error APSDE-DATA.confirm: 0xE9 on task

I have Discord yes. Can I add you somehow or go to a specific server?

**Comment by Mimiix** [comment]
There we go! 
https://discord.gg/KgXkgv

**Comment by ASNNetworks** [comment]
> There we go!
> https://discord.gg/KgXkgv

thank you! Besides the error I'm getting with both lights: is it normal for Deconz to keep logging and having actitvies? It's as if it's non stop refreshing and looking for firmware updates and saying current channel is 25 etc.

**Comment by Mimiix** [comment]
Yes. It is normal behaviour. I am not sure if it is due to HA having enabled some parameters on default, but nothing strange on that.

**Comment by ASNNetworks** [comment]
> Yes. It is normal behaviour. I am not sure if it is due to HA having enabled parameters on default, but nothing strange on that.

That's good to know, then I;m not worried at least. Since I opened this issue because of that and the other issue you have pointed out can be discussed at Discord, I'll close this.

Thanks again!
