### ISSUE TITLE
Is it possible to disable OTAU (0x0019) cluster in conbee?

### ISSUE THREAD

**Issue by dbdbdb** [dresden-elektronik/deconz-rest-plugin#3143]
I run my conbee stick as a router (not a coordinator) since I have another coordinator in my network. The conbee stick has the OTAU cluster (0x0019) enabled but I would like to disable it. Is that possible?

I do my upgrades from the coordinator and when conbee exposes OTAU then some devices try to get updates from conbee instead of the coordinator and then then fail to update. In DeConz in Edit->"Network Settings"->Endpoints one can remove the 0x0019 cluster and press save. But after a restart it has cluster 0x0019 there again.

**Comment by ebaauw** [comment]
You probably need to leave and rejoin the network for the changed settings to stick.  Make sure to read back the settings after save, to check that they are applied.
