### ISSUE TITLE
deCONZ still tries to announce itself to the old appspot server.

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#3149]
## Describe the bug
deCONZ still tries to announce itself to the decommissioned appspot server.

Seems like the code wasn't updated consistently.

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/17c19c019f8784563330fd9d2f9fd3a5c4815013/de_web_plugin.cpp#L476

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/f245b37194add12c23e1be3f7b96190351da1452/discovery.cpp#L273

## Steps to reproduce the behavior
Newly install deCONZ, or use new database.

## Expected behavior
Should use the new `phoscon.de` server.

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - deCONZ version: 2.05.79

### deCONZ Logs
```
Aug 15 01:44:35 pi6 deCONZ[22907]: 01:44:35:305 discovery network reply error: Error transferring http://dresden-light.appspot.com/discover - server replied: Service Unavailable
```

**Comment by manup** [comment]
Should be fixed since a while.
