### ISSUE TITLE
Color temperature lights once again show state.hue, state.sat, state.xy, state.effect.

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#315]
deCONZ v2.04.94 (or slightly earlier?) re-introduced an old bug (see #30, item 3): color temperature lights show `state.hue`, `state.sat`, `state.xy`, and `state.effect`, even though they don't support colour.  Happens for my Philips Hue, OSRAM, and IKEA lights.

**Comment by marthoc** [comment]
I am also seeing this starting with .94.

**Comment by ebaauw** [comment]
Solved in .97.  Thanks, @manup!
