### ISSUE TITLE
Iko Iko download not available

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#3158]
Hi @manup, 
Will Iko Iko ble compiled for download?

**Comment by Mimiix** [comment]
@PrimaryInc Hi!

you can find the compiled versions here:
http://deconz.dresden-elektronik.de/

**Comment by PrimaryInc** [comment]
@Mimiix, yes correct med version Iko Iko is not there.. Yet.

**Comment by Mimiix** [comment]
Is it?

[Raspbian](http://deconz.dresden-elektronik.de/raspbian/beta/deconz-2.05.80-qt5.deb)
[Ubuntu](http://deconz.dresden-elektronik.de/ubuntu/beta/deconz-dev-2.05.80.deb)

Windows isn't there yet. I'll ask around for that one.

**Comment by PrimaryInc** [comment]
@Mimiix sorry should have been specific. Yes windows 👍

**Comment by Mimiix** [comment]
@PrimaryInc ITS HERE!!!!!!!!
http://deconz.dresden-elektronik.de/win/deCONZ_Setup_Win32_V2_05_80.exe

**Comment by PrimaryInc** [comment]
@Mimiix thank you!!
