### ISSUE TITLE
OBLO SPW35ZD0 SPW35Z-D0 Smart Plug - Power Metrics

### ISSUE THREAD

**Issue by SeoFood** [dresden-elektronik/deconz-rest-plugin#3159]
The on/off works perfect for the device but it doesn't create Power Metrics Sensors.

## Device

- Product name: OBLO SPW35ZD0
- Manufacturer: RT-RK
- Model identifier: SPW35Z-D0
- Device type : Switch

## Screenshots

<img width="771" alt="Screenshot 2020-08-17 at 14 18 54" src="https://user-images.githubusercontent.com/2766011/90395280-9783cb80-e094-11ea-97d4-d06cadf84ba8.png">

<img width="328" alt="Screenshot 2020-08-17 at 14 19 43" src="https://user-images.githubusercontent.com/2766011/90395361-b4200380-e094-11ea-8fba-2b1fe64b85f6.png">

<img width="537" alt="Screenshot 2020-08-17 at 14 20 56" src="https://user-images.githubusercontent.com/2766011/90395454-e0d41b00-e094-11ea-9600-5e630fd9e74b.png">

<img width="512" alt="Screenshot 2020-08-17 at 14 20 13" src="https://user-images.githubusercontent.com/2766011/90395395-c732d380-e094-11ea-95ae-1f90fde8a8e2.png">

**Comment by SwoopX** [comment]
Simple metering cluster is missing as well as the basic cluster.

**Comment by SeoFood** [comment]
<img width="903" alt="Screenshot 2020-08-17 at 15 03 01" src="https://user-images.githubusercontent.com/2766011/90399137-c1d88780-e09a-11ea-8325-ea83db17f2da.png">
<img width="937" alt="Screenshot 2020-08-17 at 15 03 45" src="https://user-images.githubusercontent.com/2766011/90399189-db79cf00-e09a-11ea-9850-d4797270b19a.png">
<img width="915" alt="Screenshot 2020-08-17 at 15 04 26" src="https://user-images.githubusercontent.com/2766011/90399245-f3e9e980-e09a-11ea-98ff-403715c03852.png">
