### ISSUE TITLE
New device request - D-Link DCH-B112

### ISSUE THREAD

**Issue by shjacobs303** [dresden-elektronik/deconz-rest-plugin#3163]
Smart Door / Window Sensor

![image](https://user-images.githubusercontent.com/6812756/90518464-2b938700-e1aa-11ea-9612-1713480e83b9.png)

![image](https://user-images.githubusercontent.com/6812756/90518685-72817c80-e1aa-11ea-95d9-cac0736d7781.png)

![image](https://user-images.githubusercontent.com/6812756/90519035-ddcb4e80-e1aa-11ea-826f-8bee9af4dcff.png)

![image](https://user-images.githubusercontent.com/6812756/90519146-00f5fe00-e1ab-11ea-96c9-686a189a8cc3.png)

![image](https://user-images.githubusercontent.com/6812756/90519363-41ee1280-e1ab-11ea-8ecb-547ee5c077c2.png)

![image](https://user-images.githubusercontent.com/6812756/90519576-91ccd980-e1ab-11ea-8332-44a243f5dda1.png)

**Comment by shjacobs303** [comment]
![image](https://user-images.githubusercontent.com/6812756/90522238-d0b05e80-e1ae-11ea-8f21-a04072204649.png)

**Comment by Mimiix** [comment]
Hi!

I do appreciate the request, as you seem to have the screenshots. But please, could you use the format as per issue template?


Thank you!

**Comment by SwoopX** [comment]
I'd need the attributes of the power configuration cluster to be read. Trigger the device by open/close and then directly press the read button.
