### ISSUE TITLE
VIMAR ZIGBEE devices 14592, 14593, 14594, 19592, 19593, 19594, 20592, 20593, 20594

### ISSUE THREAD

**Issue by samuele2723** [dresden-elektronik/deconz-rest-plugin#3167]
Hello, i am asking the support for VIMAR connected devices radiofrequency.

There are 3 kind of devices manufactured by VIMAR:

Deviator 2 way - XX592

https://www.vimar.com/en/int/catalog/product/index/code/14592.0

Shutter command - XX594

https://www.vimar.com/en/int/catalog/product/index/code/19594.0

Actuator controller - - XX593

https://www.vimar.com/en/int/catalog/product/index/code/14593

XX can be 14, 19 or 20 depending on the series but inside they are all the same device.

They support zigbee 3.0 And third party hubs

  Required screenshots:
  - Endpoints and clusters of the node
  - Node Info panel
  - Basic Cluster attributes in the Cluster Info panel.

  In the Cluster Info panel press "read" button to retreive the values. Please note that at least "Manufacturer Name" and "Model Identifier" must be populated with data (therefore, must not be empty), otherwise that information will not be usable. For battery powered devices, after pressing read it is required to wake-up the device by pressing a button or any other means of interaction.
-->

**Comment by Mimiix** [comment]
Hi @samuele2723!

 I am closing this issue, as all screenshots are missing and there is 0 information provided. Please stick to the template and provide screenshots of the required clusters.

Please open a new device request with the information.

Thanks!

**Comment by testorp** [comment]
![vimar_14592_onoff_switch_configuration](https://user-images.githubusercontent.com/44940599/101484352-c7175600-3959-11eb-8284-d45b2bbd4e40.png)
![vimar_14592_scenes](https://user-images.githubusercontent.com/44940599/101484355-c8e11980-3959-11eb-8dcb-3209b2c9da67.png)
![vimar_14592_cluster_info](https://user-images.githubusercontent.com/44940599/101484356-c979b000-3959-11eb-91d8-9d4a9baec66a.png)
![vimar_14592_config](https://user-images.githubusercontent.com/44940599/101484358-ca124680-3959-11eb-9394-8632d455c89d.png)
![vimar_14592_groups](https://user-images.githubusercontent.com/44940599/101484360-caaadd00-3959-11eb-8ce9-af61b6b268bd.png)
![vimar_14592_identify](https://user-images.githubusercontent.com/44940599/101484364-cb437380-3959-11eb-997b-3c22ad380d02.png)
![vimar_14592_node_info](https://user-images.githubusercontent.com/44940599/101484365-cbdc0a00-3959-11eb-8dd4-e725722a9b44.png)
![vimar_14592_onoff](https://user-images.githubusercontent.com/44940599/101484367-cd0d3700-3959-11eb-9436-975fc9b1afa4.png)

**Comment by testorp** [comment]
hope you can help, because when i pair the switch it appears as a light in Phoscon

![image](https://user-images.githubusercontent.com/44940599/101484545-152c5980-395a-11eb-8624-c4c9dcf15a13.png)

**Comment by Smanar** [comment]
Wired switches are light
Battery switches are sensor.

**Comment by testorp** [comment]
@Smanar so what are switches?
Where can I find this information pls

Thx
Paolo
