### ISSUE TITLE
FEIBIT  SCA01ZB Carbon Monoxide Detector 

### ISSUE THREAD

**Issue by panenka** [dresden-elektronik/deconz-rest-plugin#3168]
- Product name: Carbon Monoxide Detector SCA01ZB
- Manufacturer: feibit
- Model identifier: FNB56-COS06FB1.7.
- Device type : Please remove all unrelated device types. 
  - Sensor
  - Siren

![image](https://user-images.githubusercontent.com/9946446/90652077-094b4900-e23e-11ea-9929-f5803f34c340.png)
![image](https://user-images.githubusercontent.com/9946446/90652154-1d8f4600-e23e-11ea-94ff-f84a706e9970.png)
![image](https://user-images.githubusercontent.com/9946446/90652328-3e579b80-e23e-11ea-8aa3-e41e2a0af5d7.png)
![image](https://user-images.githubusercontent.com/9946446/90652383-4dd6e480-e23e-11ea-99b1-fa401425d551.png)
![image](https://user-images.githubusercontent.com/9946446/90652704-a7d7aa00-e23e-11ea-9ead-a46f5aa746bb.png)
![image](https://user-images.githubusercontent.com/9946446/90652794-bde56a80-e23e-11ea-8592-44395c335017.png)
![image](https://user-images.githubusercontent.com/9946446/90652830-c9389600-e23e-11ea-9b80-39297689e75a.png)
![image](https://user-images.githubusercontent.com/9946446/90652882-d6558500-e23e-11ea-9df1-fccbed7413fa.png)
![image](https://user-images.githubusercontent.com/9946446/90652938-e40b0a80-e23e-11ea-88b3-bb98de15d746.png)
![image](https://user-images.githubusercontent.com/9946446/90652994-f422ea00-e23e-11ea-8d4e-e9537c0104b4.png)
![image](https://user-images.githubusercontent.com/9946446/90653034-ff761580-e23e-11ea-9f6e-a7f7b0a92114.png)
![image](https://user-images.githubusercontent.com/9946446/90653087-0d2b9b00-e23f-11ea-86dd-71c74948c2ef.png)
![image](https://user-images.githubusercontent.com/9946446/90653114-161c6c80-e23f-11ea-813c-78ff2e6a91d4.png)

**Comment by panenka** [comment]
When this device will be added to the database, please?

**Comment by Mimiix** [comment]
@panenka At next relase probably. the 15th.

**Comment by panenka** [comment]
Not understand. Where is problem? New version has been generated, but this device has not been added to V2_05_81_stable.

**Comment by Mimiix** [comment]
@panenka Nope, but will be in the beta of .82. Release should be later today ;)

**Comment by jordibsk10** [comment]
Has been released already? If not, is there any issue?
If it has been release, thank you very much and don't forget to change the status to "Merged" ;)

**Comment by panenka** [comment]
Still waiting for release, not only final version, but for release new version for HA addon. After that tests could begin.

**Comment by SwoopX** [comment]
@jordibsk10 
![grafik](https://user-images.githubusercontent.com/4005212/95024920-56686a80-0686-11eb-8866-c75b36b2d82e.png)
