### ISSUE TITLE
config.duration broken

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#317]
It seems that https://github.com/dresden-elektronik/deconz-rest-plugin/commit/2a29695b155edb4a7aa5c0e549d22a8fc80aff1d has broken `config.duration`.  My Hue motion sensors now show `config.duration` of 60, where _PIR Occupied to Unoccupied Delay_ is 0.

I think we need to recognise at least three different patterns for `config.duration`:
1. The Philips Hue motion sensor;
2. The CLIP motion sensor.
3. The IKEA Trådfri motion sensor.

Ad 1.  The sensor actually sends a notification when motion is no longer detected, setting  _Occupancy_ (0x0406/0x0000) to 0x00.  This notification is used by deCONZ to reset `state.presence` to false.  The sensor implements _PIR Occupied to Unoccupied Delay_ (0x0406/0x0010), which delays the resetting of _Occupancy_ to 0x00.  `config.duration` is mapped to this attribute, and changes to `config.duration` should be written 0x0406/0x0010, also for value `0`.  deCONZ should not reset automatically `state.presence`, irrespective of the value for `config.duration`.

Ad 2.  The real sensor could (a) or could not (b) set the virtual CLIP sensor's `state.presence` to `false`, when motion is no longer detected.  In a), deCONZ should _not_ reset `state.presence`; in b), deCONZ should reset `state.presence`.  I used `config.duration` to indicate this: when setting this to `0`, deCONZ doesn't reset `state.presence` (a), when setting it to _n_ > `0`, deCONZ resets `state.presence` to `false` after _n_ seconds (b).

Ad 3.  The sensor does not send a notification when motion is no longer detected, but it sets the duration (from the physical dial on the sensor) with the group command.  This means that any lights in the group will switch off automatically after the set number of seconds (between 60 and ~600).  I think `state.presence` should match this behaviour, and deCONZ should reset `state.presence` to `false` after the same number of seconds.  Hence, I implemented `config.duration` as read-only for the Trådfri motion sensor.  
However, when you don't use the group, you want to be able to set `config.duration` yourself, see #296.  In fact, this is similar to 2b.  This is a tricky one, as you don't want to overwrite `config.duration` with the value sent by the sensor when motion is detected next.  I saw some logic to set `config.duration` only, when it's between 60 and 600 (presumably set from the sensor's dial).

I'm not familiar with any other motion sensors, but I think they could fall into 2a (when notifying that motion is no longer detected) or 2b (when deCONZ needs to reset `state.presence`).  `config.duration` should be initialised (to 60?) only in case 2b.

**Comment by manup** [comment]
Just a reference: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/386
