### ISSUE TITLE
_TYZB01n0s2mhxq TS0204 CH4 Gas Detector

### ISSUE THREAD

**Issue by panenka** [dresden-elektronik/deconz-rest-plugin#3179]
- Product name: CH4 Natural Gas and LPG Leakage Gas Detector
- Manufacturer: _TYZB01n0s2mhxq
- Model identifier: TS0204
- Device type : 
  - Sensor
  - Siren

![image](https://user-images.githubusercontent.com/9946446/90895403-653eda80-e3c2-11ea-841e-53e03931ce9a.png)
![image](https://user-images.githubusercontent.com/9946446/90895436-71c33300-e3c2-11ea-868c-9800e5421cf9.png)
![image](https://user-images.githubusercontent.com/9946446/90895470-81427c00-e3c2-11ea-8910-5232d308d25e.png)
![image](https://user-images.githubusercontent.com/9946446/90895502-8f909800-e3c2-11ea-91f4-5fe6ffbe9747.png)
![image](https://user-images.githubusercontent.com/9946446/90895544-9f0fe100-e3c2-11ea-8f1a-2beef24daf95.png)
![image](https://user-images.githubusercontent.com/9946446/90895601-b3ec7480-e3c2-11ea-93fb-38a9ce025e66.png)

**Comment by panenka** [comment]
Has been found the reason, why is not recognized when it should be?

**Comment by Smanar** [comment]
Oups sorry, have see your answer.
And no, nothing usefull in the log, the usefull part start for exemple with
>DeviceAnnce of LightNode: %s Permit Join

For light, and 
>device announce 0x%016llX (0x%04X) mac capabilities for sensor

And your device is a "light".

**Comment by panenka** [comment]
Trick is working. Sensor has been named with title Fire 30.
