### ISSUE TITLE
Can't flash firmware

### ISSUE THREAD

**Issue by Alex7802** [dresden-elektronik/deconz-rest-plugin#3181]
raspberry pi3
root@raspberrypi:~# GCFFlasher_internal -l
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
/dev/ttyACM0     | 0x1CF1 | 0x0030  | DE1964343  | ConBee II 

root@raspberrypi:~# sudo GCFFlasher_internal -d /dev/ttyACM0 -f deCONZ_ConBeeII_0x26480700.bin.GCF 
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM0 (ConBee II)
R21B18 Bootloader
Vers: 2.05
build: Mar 22 2019
flashing 159034 bytes: |==============================|
verify: .
Flash update failed, invalid CRC. Please try again.

On the web firmware not connected

Help!

**Comment by Mimiix** [comment]
@Alex7802 Can you add Sudo?

**Comment by Alex7802** [comment]
Yes, I’m loggin in as root




Monday, 24 August 2020, 10:03 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by Mimiix** [comment]
That is not what i asked @Alex7802 . The command states using as sudo...

**Comment by Alex7802** [comment]
Ok, from root to root by sudo:
root@raspberrypi:~# sudo GCFFlasher_internal -d /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x26580700.bin.GCF
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM0 (ConBee II)
R21B18 Bootloader
Vers: 2.05
build: Mar 22 2019
flashing 160930 bytes: |==============================|
verify: .
Flash update failed, invalid CRC. Please try again.
Reboot device /dev/ttyACM0 (ConBee II)
R21B18 Bootloader
Vers: 2.05
build: Mar 22 2019
flashing 160930 bytes: |==============================|
verify: .
Flash update failed, invalid CRC. Please try again.
Reboot device /dev/ttyACM0 (ConBee II)
R21B18 Bootloader
Vers: 2.05
build: Mar 22 2019
flashing 160930 bytes: |==============================|
verify: .
Flash update failed, invalid CRC. Please try again.
Reboot device /dev/ttyACM0 (ConBee II)
R21B18 Bootloader
Vers: 2.05
build: Mar 22 2019
flashing 160930 bytes: |==============================|
verify: .
Flash update failed, invalid CRC. Please try again.
Reboot device /dev/ttyACM0 (ConBee II)
R21B18 Bootloader
Vers: 2.05
build: Mar 22 2019
flashing 160930 bytes: |==============================|
verify: .
Flash update failed, invalid CRC. Please try again.
retry, failed
root@raspberrypi:~# 

no change.
probably device bricked

**Comment by Mimiix** [comment]
Devices can't be bricked. 

I'll ask @manup in private to look at this ;)

**Comment by Alex7802** [comment]
still wait

**Comment by Smanar** [comment]
Have you tried on windows ?

**Comment by manup** [comment]
The logs seem to indicate that the update went through completely but somehow the flash wasn't written, perhaps dead flash section? I haven't seen that one yet.

Can you please send it back for investigation and send us an mail with shipping address for an replacement (+ reference me and this issue).  support@dresden-elektronik.de
