### ISSUE TITLE
New device Request Xiaomi Aqara Smart Home Switch D1 Wall Plug Triple Gang

### ISSUE THREAD

**Issue by pawellygan** [dresden-elektronik/deconz-rest-plugin#3182]
**DEVICE:**

Name: Xiaomi Aqara Smart Home Switch D1 Wall Plug Triple Gang
Manufacturer: Xiaomi
Model Code: QBKG26LM
Device type: In-Wall Switch 3 Gang

**SCREENSHOTS:**

<img width="464" alt="Screenshot 2020-08-22 at 13 15 07" src="https://user-images.githubusercontent.com/45388740/90955897-83b3dd00-e479-11ea-9d5e-a5913022f5df.png">

<img width="839" alt="Screenshot 2020-08-22 at 13 17 12" src="https://user-images.githubusercontent.com/45388740/90955917-cd042c80-e479-11ea-9108-41ba5af22c5d.png">

<img width="845" alt="Screenshot 2020-08-22 at 13 17 57" src="https://user-images.githubusercontent.com/45388740/90955932-e7d6a100-e479-11ea-992b-1efda1e8a212.png">

<img width="844" alt="Screenshot 2020-08-22 at 13 18 15" src="https://user-images.githubusercontent.com/45388740/90955934-f1f89f80-e479-11ea-84f8-e4ec635e6eb4.png">

<img width="854" alt="Screenshot 2020-08-22 at 13 18 37" src="https://user-images.githubusercontent.com/45388740/90955941-0046bb80-e47a-11ea-97f0-3e9df49dd3fa.png">

<img width="834" alt="Screenshot 2020-08-22 at 13 19 01" src="https://user-images.githubusercontent.com/45388740/90955947-0dfc4100-e47a-11ea-87aa-1750a8891888.png">

<img width="706" alt="Screenshot 2020-08-22 at 13 19 29" src="https://user-images.githubusercontent.com/45388740/90955957-1d7b8a00-e47a-11ea-9de9-03a715840e09.png">

<img width="702" alt="Screenshot 2020-08-22 at 13 20 05" src="https://user-images.githubusercontent.com/45388740/90955967-3d12b280-e47a-11ea-8a98-e2e04e0a0f8e.png">

<img width="737" alt="Screenshot 2020-08-22 at 13 20 58" src="https://user-images.githubusercontent.com/45388740/90955977-53207300-e47a-11ea-8aa1-03f90ce4b1bd.png">

<img width="733" alt="Screenshot 2020-08-22 at 13 21 27" src="https://user-images.githubusercontent.com/45388740/90955980-659aac80-e47a-11ea-8435-fe7863554902.png">

**Comment by pawellygan** [comment]
lygi@homeassistant:~/deconz-rest-plugin$ qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
lygi@homeassistant:~/deconz-rest-plugin$ qmake && make -j2
Project ERROR: Unknown module(s) in QT: serialport
lygi@homeassistant:~/deconz-rest-plugin$ 

oh well :\

**Comment by Mimiix** [comment]
@pawellygan On a moderation note: Please use the template next time. You added the correct screens, so no worries. But that template also adds the label :) _Saving me some work 😉_ Thanks!

**Comment by pawellygan** [comment]
> @pawellygan On a moderation note: Please use the template next time. You added the correct screens, so no worries. But that template also adds the label :) _Saving me some work 😉_ Thanks!

Oh! Believe me I tried! No labels available for me or I don't know how to do it but I did my best

**Comment by Mimiix** [comment]
@pawellygan When you create a issue and select the "device request" template, it automatically assigns the label after creating.

No worries!  It's okay :)

**Comment by Smanar** [comment]
I think it s possible on docker, but not on hassio, hassio is not a real OS.

**Comment by pawellygan** [comment]
> I think it s possible on docker, but not on hassio, hassio is not a real OS.
> You haven't another Unix machine ?

I'm running Ubuntu Server 20.04 and HA from docker

**Comment by pawellygan** [comment]
Ok finally I compiled everything - last step left - to swap the plugins. But have no idea where to start. Running Supervised HA from docker , official Deconz plugin, Ubuntu 20.04 server

**Comment by Smanar** [comment]
IDK how o use HA with not local running deconz, but
- If the deivice is visible in phoscon, can use it to check if return is working (use it manualy and check for return in phoscon)
- Can take a look in the API to check power sensors, just use this kind of url `http://IP_DECONZ:PORT/api/API_KEY/sensors`

If you haven't api key on this machine, can use curl
`curl http://127.0.0.1:80/api/ -X POST -d '{"devicetype": "TestKey"}'`

**Comment by pawellygan** [comment]
Unfortunately, I can't make it work with Docker, and HA - I will have to wait for an official release and green light for this device. At this point, I can turn on or off all three gangs together - but there is no cooperation with the switch for NodeRed and switch is not reporting back about its state (when pressed by hand) 
Also, none of them work for scenes, you can add them but when the scene is called - there is no action for the switch.
Because its running from docker I can call http://IP_DECONZ:PORT/api/API_KEY/sensors - I know my API key but link just doesn't work for docker's IP

**Comment by Smanar** [comment]
Ok, so waiting for someone with the device and an Real Unix machine.

**Comment by pawellygan** [comment]
actually got a question - IF I will unplug conbee and use it for a different machine - when I plug it back to my HA host - will everything work like before? I can set a separate Ubuntu machine and test it - got a spare computer here ;)

**Comment by Smanar** [comment]
Yes.
Device are memorised on the host, device configuration on the key, so nothing will change.

No.
Xiaomi device don't like to be without parent too long time (> 1h) and can leave the network without gateway, so need to be fast ^^.

**Comment by ebaauw** [comment]
> can leave the network without gateway

Are you sure?  I would think “without its parent” or maybe “without the coordinator” (if it wants to see ACKs to its reports).  I doubt the end device would look for more than NWK ACKs.  As long as the device is powered, its firmware continues to act as coordinator (incl. the parent function), irrespective of whether deCONZ is running.

**Comment by Smanar** [comment]
Yep, you are right, "language abuse" because generally user that have Xiaomi device, have at least one of them connected to the gateway.

**Comment by pawellygan** [comment]
ok, yesterday I fired up my work laptop as Ubuntu machine, compiled and tested the wall switch. unfortunately, it has been detected as 3 separate lights without reporting back about the pressed rocker. Not sure how I can run more test for you - I think I will need some guidance

**Comment by Smanar** [comment]
Do you know how to use the api ? https://dresden-elektronik.github.io/deconz-rest-doc/

If I m right you will have some sensor, just take a look at url 
`http://IP:PORT/api/API_KEY/sensors`

IP and PORT are the same than for phoscon
If you haven't api key, with curl
`curl http://127.0.0.1:80/api/ -X POST -d '{"devicetype": "TestKey"}'`

**Comment by Creatish** [comment]
Same line of device that works weird for me - https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3156

Overall I have it doing everything I need, by ignoring the other lights and switches it added.

might be intrested in the 2 button switch version soon though and I'd imagine that won't work like this one does just about.

**Comment by lovelylain** [comment]
The D1 two-key version is almost the same as the previous generation, but the D1 three-key version is completely different. After pressing the physical button, no feedback is received. The accurate status of the switch can be read through read('genOnOff', ['onOff']). However, the lack of feedback on the physical buttons makes it difficult to integrate. I hope someone can solve it.

**Comment by Smanar** [comment]
@Creatish so you have tried to install deconz on a virtual machine ?
It have worked or not ?
Have you tried to install the dev package ?

**Comment by Creatish** [comment]
No sorry, I saw the conversation on here and the guy replying has far more understanding in giving you detaisl, i am no where near that so I ain't got a chance on helping with it unfortunately.

hopefully someone with them pop up soon :)

**Comment by andys73** [comment]
Has this QBKG26LM device being added to latest Deconz, is not clear to me, Many thanks!

**Comment by udponly** [comment]
according to this: https://zigbee.blakadder.com/Aqara_QBKG26LM.html it is still not supported by deconz, only by z2m.
is this correct?
could you shine some light please @Creatish  ?
cheers!

**Comment by Smanar** [comment]
If I m right, at least the on/off is working, but not sure for the return.
If you have the device can try to make a DDF ?
