### ISSUE TITLE
Sage doorbell reports empty battery alarm

### ISSUE THREAD

**Issue by sspans** [dresden-elektronik/deconz-rest-plugin#3186]
## Describe the bug
When using the supported sage doorbell sensor via homebridge a 0% battery percentage is reported.
This triggers empty battery warnings in homekit.

## Steps to reproduce the behavior
Configure a sage doorbell.

## Expected behavior
Either report no battery percentage, or an accurate one.

## Environment
Deconz 2.05.80 / 14/08/2020

 - Host system: rpi 4
 - Running method: docker

### deCONZ Logs
I'm happy to provide additional info

## Additional context
https://github.com/Koenkk/zigbee2mqtt/issues/4076
https://github.com/trunzoc/Hubitat/blob/master/Drivers/Sage_Doorbell/Sage_Doorbell.groovy
https://github.com/lmosenk/SAGE-Doorbell-Sensor-ST/blob/master/SAGE_Doorbell_Sensor_ST.txt

**Comment by SwoopX** [comment]
Can you provide me with a screenshot of the power configuration cluster, where the attributes have been read? The corresponding code to update battery readings is already implemented, so it's a bit strange.

**Comment by sspans** [comment]
Here you go:

<img width="539" alt="Screenshot 2020-08-25 at 21 18 26" src="https://user-images.githubusercontent.com/580254/91217939-96980d00-e718-11ea-8ce1-1d65ea4ebff0.png">

**Comment by Smanar** [comment]
Bad luck, it s realy like this device haven't battery report (same reaction on z2m)

**Comment by SwoopX** [comment]
I agree. The device doesn't seem to have any reasonable battery readings then (@Smanar thanks for cross checking). In that case, I'd remove the battery from the device.
