### ISSUE TITLE
VIMAR window covering control IoT device 14594.0 (or 19594.0 or 20594.0)

### ISSUE THREAD

**Issue by samuele2723** [dresden-elektronik/deconz-rest-plugin#3187]
## Device

- Product name: Vimar - 14594.0 (or 19594.0 or 20594.0) - Rolling shutter IoT connected mechanism
- Manufacturer: Vimar
- Model identifier: Window_Covering_v1.0
- Device type : 
  - Other: Window Shutter control

https://www.vimar.com/en/int/catalog/product/index/code/14594.0

![14594_0-vimar-plana-meccanismo-tapparella-connesso-iot 87370](https://user-images.githubusercontent.com/66970905/91225078-4f634980-e723-11ea-9c08-c76c79c73f8b.jpg)

NOTE: device seems working on\off\position but is not reporting automatically state back to Deconz when you interact physically with it. You need to push "read" in the cluster panel to get the position updated

## Screenshots

![node info](https://user-images.githubusercontent.com/66970905/90985812-b267ab80-e57e-11ea-9537-db03112c6209.png)
![scene cluster 2](https://user-images.githubusercontent.com/66970905/90985813-b3004200-e57e-11ea-9f3f-d9501a7c7125.png)
![basic cluster](https://user-images.githubusercontent.com/66970905/90985815-b398d880-e57e-11ea-8c47-07b743991db0.png)
![identify cluster](https://user-images.githubusercontent.com/66970905/90985816-b398d880-e57e-11ea-8b03-05212e2f18e7.png)
![window covering cluster](https://user-images.githubusercontent.com/66970905/90985817-b4316f00-e57e-11ea-9565-346f49a6924d.png)
![scene cluster 1](https://user-images.githubusercontent.com/66970905/90985819-b4ca0580-e57e-11ea-8279-46809302241b.png)
![window covering cluster 2](https://user-images.githubusercontent.com/66970905/90985820-b4ca0580-e57e-11ea-87ac-7e6410a9a17f.png)

NOTE: The device is not updating automatically the states changes when interacted physically. Means i OPEN the shutter and Deconz is not automatically notified and updated, i need to manually press "read" to generate the state update.

NOTE2: The device seems coming by factory with kind of calibration in order to know how long time takes to move for 1% of shutter opened. Nevertheless further calibration should be done when connected to the motor

**Comment by SwoopX** [comment]
With regard to reporting: have you already tried fully open -> fully closed -> fully open? Also, that must be done on each power cycle (in case that applies for you).

**Comment by samuele2723** [comment]
Hello SwoopX, 

I have a update on this, i bought a 30 eur motor on Amazon, connected and now i get payload reporting and state update on lift percentage. I am not sure why this didn’t happen before, but now seems working properly (there are 4-5 sec delay after end of action before payload generation).

Now, only big question remaining is about the 0-100% calibration. How is possible to set that? From my understanding should be possible to change time and speed of the motor connected. Are those parameters configurable in deconz?
