### ISSUE TITLE
Is it possible to reset the Conbee Stick to factory config? 

### ISSUE THREAD

**Issue by o0shojo0o** [dresden-elektronik/deconz-rest-plugin#3189]
Is it possible to reset the Conbee Stick to factory config? 
I accidentally configured mine, and now I'm not sure if the configuration is correct.

![image](https://user-images.githubusercontent.com/19333515/91013817-926cd200-e5e8-11ea-9209-6cbab48c62ce.png)

**Comment by Smanar** [comment]
Hello, all looks fine for me

There is a reset feature in phoscon and you try too with `GCFFlasher_internal -r`

But 
1 - I have never used them, and idk what they reset.
2 - Not sure you need it.

**Comment by o0shojo0o** [comment]
Thanks for your reply, then I will leave it at that for now.
