### ISSUE TITLE
Smart things Multipurpose sensor - incorrect temp being shown

### ISSUE THREAD

**Issue by JamieP83** [dresden-elektronik/deconz-rest-plugin#3190]
## Describe the bug
My samsung smartthings multi purpose sensor, keeps reporting a -46 temperature. its also not showing a battery level?
i have deleted the device and readded.
i have reset the device and readded
no change

## Steps to reproduce the behavior
just added the sensor and it keeps showing the incorrect temp.
i have 10+ other devices, all of those are ok

## Expected behavior
correct temp

## Screenshots
![image](https://user-images.githubusercontent.com/48566948/91081058-6d0ab300-e63e-11ea-8f01-d4dfd4622f4b.png)

![image](https://user-images.githubusercontent.com/48566948/91081143-8f9ccc00-e63e-11ea-9650-6d6034903907.png)

## Environment

 - Host system: Raspberry Pi4 
 - Running method:Home Assistent deCONZ Add-on /
 - Firmware version: 26580700
 - deCONZ version: 2.0.5.79 / 5/22/2020
 - Device:  ConBee II 
 - Do you use an USB extension cable: yes 

![image](https://user-images.githubusercontent.com/48566948/91081255-bc50e380-e63e-11ea-9881-168cea54e36c.png)

## Additional context

```
"113": {
        "config": {
            "battery": null,
            "on": true,
            "pending": [],
            "reachable": true
        },
        "ep": 1,
        "etag": "e1e3b40ffe6763f507e7dd9f86e2926e",
        "lastseen": "2020-08-24T18:20:45.404",
        "manufacturername": "Samjin",
        "modelid": "multi",
        "name": "Dining Room Door ST DZ",
        "state": {
            "lastupdated": "2020-08-24T18:20:45.404",
            "open": false
        },
        "type": "ZHAOpenClose",
        "uniqueid": "28:6d:97:00:01:04:86:73-01-0500"
    },
    "114": {
        "config": {
            "battery": null,
            "offset": 0,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "88168900322514808e1234182225a057",
        "lastseen": "2020-08-24T18:20:45.400",
        "manufacturername": "Samjin",
        "modelid": "multi",
        "name": "Dining Room Door ST DZ",
        "state": {
            "lastupdated": "2020-08-24T18:20:32.470",
            "temperature": -4685
        },
        "type": "ZHATemperature",
        "uniqueid": "28:6d:97:00:01:04:86:73-01-0402"
    },
    "115": {
        "config": {
            "battery": null,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "72cdf4bbf1789c8a9a0855dfaea8554d",
        "lastseen": "2020-08-24T18:20:45.400",
        "manufacturername": "Samjin",
        "modelid": "multi",
        "name": "Dining Room Door ST DZ",
        "state": {
            "lastupdated": "none",
            "orientation": [
                0,
                0,
                0
            ],
            "vibration": false
        },
        "type": "ZHAVibration",
        "uniqueid": "28:6d:97:00:01:04:86:73-01-fc02"
```

**Comment by JamieP83** [comment]
i just replaced the battery and thats fixed the unknown battery issue, but temp is still off

![image](https://user-images.githubusercontent.com/48566948/91155250-7f2a3700-e6ba-11ea-8103-37b5fdabcd90.png)

**Comment by Mimiix** [comment]
@ebaauw As far as i can find, you integrated [this one](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2769) Are you able to give some info on this?

**Comment by JamieP83** [comment]
> @ebaauw As far as i can find, you integrated [this one](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2769) Are you able to give some info on this?

sorry! i missed this one
yes, thats the right model! sorry again

**Comment by JamieP83** [comment]
Hey
This is still an issue

**Comment by Smanar** [comment]
If 10 are working and not this one, I don't think the problem was from code.
You can see a difference beetwen the working and the unworking one in deconz ?

Can you take a look in the cluster 0402 and sho the attribute list (need probable press the "read" button and making the device wake up) ?

**Comment by JamieP83** [comment]
sorry, how do i do that?
i cant see a way to show the info for 0402

![image](https://user-images.githubusercontent.com/48566948/99521941-f0614980-298c-11eb-8803-fe98d3bfbf3b.png)

**Comment by JamieP83** [comment]
sorrry, think i have it now:

This is the bad result from the dining room door sensor

![image](https://user-images.githubusercontent.com/48566948/99522444-90b76e00-298d-11eb-9f36-374bcd292db0.png)
![image](https://user-images.githubusercontent.com/48566948/99522499-a6c52e80-298d-11eb-99a4-29d3598c0e04.png)

this is a result from a "working" device
![image](https://user-images.githubusercontent.com/48566948/99522557-bb092b80-298d-11eb-8b7e-68b94471b6b7.png)

**Comment by JamieP83** [comment]
sorry, i didnt mean/want to close this either

**Comment by JamieP83** [comment]
it seems tolerance is not set for the device thats playing up?

![image](https://user-images.githubusercontent.com/48566948/99523034-61edc780-298e-11eb-8496-f226d8975ba3.png)

**Comment by SwoopX** [comment]
Temperature measurement of the device in question seems to report erroneous data.

**Comment by JamieP83** [comment]
agreed - but how to fix that?

**Comment by SwoopX** [comment]
Erm, return the faulty and get a new one?

**Comment by JamieP83** [comment]
> Erm, return the faulty and get a new one?

sorry, with you now! will order a new one and bin this then
