### ISSUE TITLE
bootloop of the device after upgrade of device with deconz plugin of jeedom

### ISSUE THREAD

**Issue by cedricmercy** [dresden-elektronik/deconz-rest-plugin#3197]
Hello , 

## Environment

 - Host system:  PC 
 - Running method: Ubuntu 20.04
 - Firmware version: 0x26580700
 - deCONZ version: (2.05.77)
 - Device: ConBee II  ( serial number DE2219637
 - Do you use an USB extension cable: no

## Additional context

so I tried to see if I could downgrade the firmware but I don't win to do it with the line command to flash the firmware :

# GCFFlasher_internal -d 0 /dev/ttyACM0 -t 1000 -f deCONZ_ConBeeII_0x264a0700.bin.GCF

sometimes the command to display the device appears, sometimes not :
root@esx1:/home/cedric# GCFFlasher_internal -l
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
root@esx1:/home/cedric# GCFFlasher_internal -l
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  | DE2219637  | ConBee II 
root@esx1:/home/cedric# GCFFlasher_internal -l
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
root@esx1:/home/cedric#

I've well stopped the ModemManager , deconz and deconz-gui on my host ( of course I don't work on the VirtualMachine to try to recover the stick ) , but I'm not able to flash a new time the device to fix the issue.
Do you have an Idea of what I could do to fix the stick ?

Many thanks if you could help me.

Cédric.

**Comment by Mimiix** [comment]
Hi @cedricmercy 

First off, i'd like to ask you to stick to the format. You did provide some information, but not in the way we asked.

To answer your question: [Please follow this guide](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually)

I'd recommend using a windows machine to fix it :)

**Comment by cedricmercy** [comment]
Hello Dennis D, 


Many thanks , sorry to didn't follow the format, I'm a little bit in Panic because I'm really affraid I did brick the device. :-( 




I followed the guide you mentioned on my Linux host. 

I tried to fix it on a windows system too, but the result is the same on my windows 7 Computer. 
I'm not able to see the device sometimes with the list command of the gcfflasher tool 



I've tried to change the parameter -t 60 to -t 1000 but no change. 


My operating system is the last ubuntu 20.04, is it possible that another service ( other than ModemManager could avoid to flash the device ? ) 


thank you. 


Cédric. 

----- Mail original -----

De: "Dennis D" <notifications@github.com> 
À: "dresden-elektronik/deconz-rest-plugin" <deconz-rest-plugin@noreply.github.com> 
Cc: "cedricmercy" <cedric.mercy@free.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mercredi 26 Août 2020 09:09:52 
Objet: Re: [dresden-elektronik/deconz-rest-plugin] bootloop of the device after upgrade of device with deconz plugin of jeedom (#3197) 



Hi @cedricmercy 
First off, i'd like to ask you to stick to the format. You did provide some information, but not in the way we asked. 
To answer your question: Please follow this guide 
I'd recommend using a windows machine to fix it :)

**Comment by Mimiix** [comment]
Hi!

On the linux host, is that a ESXI (as i can tell?)

**Comment by cedricmercy** [comment]
No, I use VirtualBox version 6.1.6, and I configured the key to the Virtual Machine with adding a filter with the name of the device in the configuration of the Virtual Machine in the USB parameter Box.

**Comment by Mimiix** [comment]
To be clear: Are you using Virtual box to **update/flash the conbee?**.

**Comment by cedricmercy** [comment]
The first time , yes, because it was in Jeedom with the plugin in Web Interface, but now, I try to fix it directly from the main host , not the virtual Machine. 
I can't connect the key to the Virtual Machine anymore because VirtualBox hasn't enough time to update the list of Devices during the 2 seconds between the connect and disconnection of the key. 


Thank you for your time 


Cédric 






----- Mail original -----

De: "Dennis D" <notifications@github.com> 
À: "dresden-elektronik/deconz-rest-plugin" <deconz-rest-plugin@noreply.github.com> 
Cc: "cedricmercy" <cedric.mercy@free.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mercredi 26 Août 2020 17:20:28 
Objet: Re: [dresden-elektronik/deconz-rest-plugin] bootloop of the device after upgrade of device with deconz plugin of jeedom (#3197) 



To be clear: Are you using the OS within Virtual box to update/flash the conbee? .

**Comment by Mimiix** [comment]
@cedricmercy 

The host, is that ubuntu? 

The thing that happened here is that the firmware was corrupted due to Jeedom.

To fix that, you need to follow the guide i mentioned earlier. Please make sure to use Sudo and make sure to have deconz STOPPED on the host aswell. Otherwise, the stick is occupied.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by Smanar** [comment]
@cedricmercy you miss some parameter in your command, for exemple "-t 60" to increase timeout.
And like have said Mimixx  make the procedure on REAL machine.

**Comment by cedricmercy** [comment]
Hello all,

I've found my mistake by using the debug mode of the tool, I made a confusion with the device name and the serial name, so I added a 0 before the device name, now I've win to flash a new time the firmware and it works :-)


/usr/bin/GCFFlasher_internal.bin -d 0 /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x264a0700.bin.GCF -x 3


16:24:10:837 using firmware file: deCONZ_ConBeeII_0x264a0700.bin.GCF 
16:24:10:872 device /dev/ttyACM0 not found
16:24:10:872 retry, elapsed 5 seconds
16:24:10:977 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x264a0700.bin.GCF -x 3

16:24:10:977 using firmware file: deCONZ_ConBeeII_0x264a0700.bin.GCF 
16:24:11:010 device /dev/ttyACM0 not found
16:24:11:010 retry, elapsed 5 seconds
16:24:11:109 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x264a0700.bin.GCF -x 3

16:24:11:109 using firmware file: deCONZ_ConBeeII_0x264a0700.bin.GCF 
16:24:11:134 ls dev: /dev/ttyACM0 (0x1CF1/0x0030) sn: DE2219637
Reboot device /dev/ttyACM0 (ConBee II)
16:24:11:140 query bootloader v1 ID after 5 ms
16:24:11:151 RX 60 bytes ASCII 
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
, 08:48:53
 after 15 ms
16:24:11:151 bootloader start after 16 ms
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
16:24:11:152 GCF_ResetDeviceDone
16:24:11:153 bootloader v1 update firmware
flashing 158985 bytes: |==============================|
verify: .
SUCCESS
Wait 10 seconds until application starts
root@esx1:/home/cedric# vi /var/log/kern.log
Many thanks for your help, and sorry that I didn't feel correctly the template .

Regards.
Cédric.

**Comment by Mimiix** [comment]
@cedricmercy Happy to hear that!!

Have a goodnight :)
