### ISSUE TITLE
Aqara wall switch QBKG12LM (lumi.ctrl_ln2.aq1) group toggle problem

### ISSUE THREAD

**Issue by BenDavidson90** [dresden-elektronik/deconz-rest-plugin#3205]
Hi, i got four Aqara wall switch 2 rockers with neutral (QBKG12LM) and I successfully added them in Phoscon.
When added, it creates two lights.

- For two switches, I added the two lights in one only group (two buttons, one group):
![Annotation 2020-08-28 113227](https://user-images.githubusercontent.com/7091140/91546300-85225100-e922-11ea-999c-7eadb936ff9d.png)
![Annotation 2020-08-28 113210](https://user-images.githubusercontent.com/7091140/91546189-5906d000-e922-11ea-880c-ead036c873a1.png)
- For one switch, I added the two lights in two groups (two buttons, one group per button):
![Annotation 2020-08-28 113552](https://user-images.githubusercontent.com/7091140/91546413-af740e80-e922-11ea-829d-14c3b0c20c41.png)
![Annotation 2020-08-28 113835](https://user-images.githubusercontent.com/7091140/91546625-0b3e9780-e923-11ea-9716-26eb4b5e9ddc.png)
- And for the last switch, I added one light alone in one group and the other light in an other group with an other light (from a simple rocker switch):
![Annotation 2020-08-28 114138](https://user-images.githubusercontent.com/7091140/91546933-843def00-e923-11ea-92d5-499d3e5bac4a.png)
![Annotation 2020-08-28 114153](https://user-images.githubusercontent.com/7091140/91546939-856f1c00-e923-11ea-87a5-cda1fe7adde4.png)

### The problem
The problem is that I can control all lights by clicking individually on it HOWEVER in all of the above cases if I switch an entire group the light corresponding to the right button will not toggle (but it's state will).
So, if I link an other switch to toggle the entire group, it will only toggle the left light.

For example:
- In the first of above cases (when the two buttons are in the same group), if I switch on the group, both lights are considered ON by Phoscon but only the left light is really ON ("Lumière Salle de bain" here).
![screencast-200 21 1 5_8484-2020 08 28-11_49_09](https://user-images.githubusercontent.com/7091140/91547828-c582ce80-e924-11ea-9e3f-8b678214e5c2.gif)
- Same in the second case (where the right light is alone in one group), here Phoscon thinks that the light in ON but in real life it is not:
![screencast-200 21 1 5_8484-2020 08 28-11_52_29](https://user-images.githubusercontent.com/7091140/91548041-15619580-e925-11ea-9947-9ef0b27f88f0.gif)

This problem is only with the right button of each switches, no problem with the left button...

Thank's in advance for your help.

**Comment by ebaauw** [comment]
Not sure which switch this is, but if memory serves, the `lumi.ctrl_ln` switches only carry a _Groups_ cluster on the first light endpoint.  They simply don't support groups for the second light.  You might want to check what the switch looks like in the GUI, and whether it has a server (blue) _Groups_ cluster on each light endpoint.

**Comment by BenDavidson90** [comment]
> Not sure which switch this is, but if memory serves, the `lumi.ctrl_ln` switches only carry a _Groups_ cluster on the first light endpoint. They simply don't support groups for the second light. You might want to check what the switch looks like in the GUI, and whether it has a server (blue) _Groups_ cluster on each light endpoint.

It is the `lumi.ctrl_ln2.aq1`.
Not sure on how to verify what you said, is it here ?
![Annotation 2020-08-28 121835](https://user-images.githubusercontent.com/7091140/91550610-14cafe00-e929-11ea-8c33-dace6ef120d6.png)

**Comment by ebaauw** [comment]
Yes, you see the _Groups_ cluster is missing from endpoint 0x02.

**Comment by BenDavidson90** [comment]
Oh ok. So nothing to do... Thanks for your help, I understand better now.
