### ISSUE TITLE
Raspbee / Conbee disable all lights aka leds

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [dresden-elektronik/deconz-rest-plugin#3208]
Hey there.

I try to find a way to disable all my leds on my raspberry-pi 4. On rpi4 istself this is not a problem but I did not find a way to do the same with the raspbee-1 module.

Is there a chance or would it be possible to add this with the next firmware. I dont want to destroy or un-solder the leds on it.
Nice would be a time-based setting for that or the chance to handle this by some lux-sensors.

**Comment by Mimiix** [comment]
Hi @sorryusernameisalreadytaken 

In regard to : #3199  I am closing this issue.

Could you please use the [Feature request template](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new?assignees=&labels=Feature+Request&template=feature_request.md&title=) ?

Thank you!
