### ISSUE TITLE
How to launch dev version ?

### ISSUE THREAD

**Issue by zoic21** [dresden-elektronik/deconz-rest-plugin#3212]
Hello,

I want to test dev version but I can find how to launch it... We used dpkg installation, I install dev version (.80) all it's ok but after launch I am on .78 not .80 ?

Launch is done by command line 

```
["sudo","deCONZ","--auto-connect=1","--dbg-error=1", "--http-port=8484", "--ws-port=20877", "--upnp=0", "-platform", "minimal"]
```

Thank in advance

**Comment by Mimiix** [comment]
Hi,

I am missing information here.

What is your setup? What version are you on? What is your hardware?

As in regard to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3199

I am closing this issue and please file a correct one with template filled in.

Thank you,
