### ISSUE TITLE
Raspberry II integration in Hoobs

### ISSUE THREAD

**Issue by homer123456** [dresden-elektronik/deconz-rest-plugin#3224]
## Problem with Raspberry II integration in Hoobs
  Hi all,
I have a problem integrating the Raspberry II module in hoobs.
1. I have plugged in the Phoscon Raspberry II module to my Raspberry which is running Hoobs.
2. Have installed the deconz package, which is running o.k. 
In my case Hoobs I can reach via 192.168.0.31
and Deconz graphical plugin via 192.68.0.31:1881
3. I was able to link 2 zigbee devices (Xiaomi Sensor and an Osram plug) to Deconz.
4. Was then trying to install the "Hue / Deconz" plugin (homebridge-hue
0.11.75 • Published August 24th) in Hoobs and then link to the Raspberry II.
Via the log function in Hoobs I have received the user data:
"0021xxxxxxxx": "2Axxxxx"
and inserted this in the mask of the plugin in Hoobs.

5. When I press save config for the plugin the Hoobs bridge is not turning on again.
In the log-file I can see that the Hue plugin seem to use a different IP address 
192........192 and others.

6. Have then tried to set Host: "192.168.0.31"
but this is also not working. 

7. Config:

{
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "homebridge-hue"
            },
            "name": "Hue",
            "anyOn": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "hosts": [
                "192.168.0.31"
            ],
            "users": {
                "002xxxxxxxxxxxxx": "9Cxxxxxxxxx"
            }

When I de-install the Hue Plugin Hoobs works again (with the rest).

-->

## Environment

 - Host system: (Raspberry Pi 3B, Raspbee II)
 - Running method: (Hoobs)

**Comment by Mimiix** [comment]
Hi @homer123456 

Unfortunately, we do not provide support for Hoobs. I suggest checking here:https://support.hoobs.org/

All the best,
Dennis
