### ISSUE TITLE
Conbee has unknown device

### ISSUE THREAD

**Issue by gasm67** [dresden-elektronik/deconz-rest-plugin#323]
Hi,

Deconz is seeing an unknown device on the Conbee stick.  How can it be removed, tried deleting but it seems to be there when queried.  Any way to reset the stick to factory default and erase all data from it ?

Thanks,

**Comment by manup** [comment]
I guess the device is in some neighbour table of another device (light). ConBee itself does not store this permanently local neighbour table is cleared on power-up. However it does query the lights for their neighbours and I think from there the unknown device appears. You can see the neighbours relationships in deCONZ.

I would just ignore the device it should go away after some time, Hue lights do remember ghosts for a while. No need to reset the whole network.

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
