### ISSUE TITLE
deCONZ service could not been started because of Qt issues

### ISSUE THREAD

**Issue by thomasklein1975** [dresden-elektronik/deconz-rest-plugin#3230]
Hi,

maybe somebody can help me. Untill now i was able to start service. Seems so that some package are missing.
I already tried "sudo apt -f install" after following instructions from website (https://phoscon.de/en/conbee2/install#raspbian ,stable version). Port changed for testing from 80 to 8090 
Even GUI on Raspi could not be started while using vnc.

Here are the logs:

`Sep 04 08:01:40 pi systemd[1]: deconz-gui.service: main process exited, code=exited, status=1/FAILURE
Sep 04 08:01:40 pi systemd[1]: Unit deconz-gui.service entered failed state.
Sep 04 08:02:10 pi systemd[1]: deconz-gui.service holdoff time over, scheduling restart.
Sep 04 08:02:10 pi systemd[1]: Stopping deCONZ: ZigBee gateway -- GUI/REST API...
Sep 04 08:02:10 pi systemd[1]: Starting deCONZ: ZigBee gateway -- GUI/REST API...
Sep 04 08:02:10 pi systemd[1]: Started deCONZ: ZigBee gateway -- GUI/REST API.
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5SerialPort.so.5: no version information available (required by /usr/bin/deCONZ
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5: no version information available (required by /usr/bin/deCONZ)
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/deCONZ)
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: no version information available (required by /usr/bin/deCONZ)
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5: no version information available (required by /usr/bin/deCONZ)
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5: no version information available (required by /usr/bin/deCONZ)
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5: no version information available (required by /usr/lib/libdeCONZ.so.
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5SerialPort.so.5: no version information available (required by /usr/lib/libdeC
Sep 04 08:02:10 pi deCONZ[2460]: /usr/bin/deCONZ: /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5: no version information available (required by /usr/lib/libdeCONZ.so
Sep 04 08:02:10 pi systemd[1]: deconz-gui.service: main process exited, code=exited, status=1/FAILURE
Sep 04 08:02:10 pi systemd[1]: Unit deconz-gui.service entered failed state.
Sep 04 08:02:18 pi systemd[1]: Starting deCONZ: ZigBee gateway -- GUI/REST API...
Sep 04 08:02:40 pi systemd[1]: deconz-gui.service holdoff time over, scheduling restart.
Sep 04 08:02:40 pi systemd[1]: Stopping deCONZ: ZigBee gateway -- GUI/REST API...
Sep 04 08:02:40 pi systemd[1]: Starting deCONZ: ZigBee gateway -- GUI/REST API...
Sep 04 08:02:40 pi systemd[1]: Started deCONZ: ZigBee gateway -- GUI/REST API.`

system:
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

It would be great to get support/help. I want to ave my ikea smart home devices integrated in my fhem :-)

Greetings & thx in advance
Thomas

**Comment by Mimiix** [comment]
Hi @thomasklein1975 

I am closing this issue as a issue template is not used. Please stick to the issue templates.

**Comment by thomasklein1975** [comment]
sorry didnt get it. what did i wrong?

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
