### ISSUE TITLE
Hive Active Heating Receiver SLR2b (upgraded version of SLR2)

### ISSUE THREAD

**Issue by fryc88** [dresden-elektronik/deconz-rest-plugin#3234]
## Device

- Product name: Hive Active Heating Dual Channel Recviever
- Manufacturer: Computime
- Model identifier: SLR2b
- Device type : 
  - Thermostat

Endpoints and clusters of the node
![1](https://user-images.githubusercontent.com/50572708/92314130-ad1d4e80-efcb-11ea-88e7-149738b74d37.png)

Node Info panel
![2](https://user-images.githubusercontent.com/50572708/92314136-c2927880-efcb-11ea-97e9-cc89ddaf5276.png)

Basic Cluster attributes in the Cluster Info panel.

![2 1](https://user-images.githubusercontent.com/50572708/92314135-c1f9e200-efcb-11ea-9497-6aa70b2c2c54.png)
![3](https://user-images.githubusercontent.com/50572708/92314137-c2927880-efcb-11ea-9807-532e906072e5.png)
![4](https://user-images.githubusercontent.com/50572708/92314138-c32b0f00-efcb-11ea-92ff-4b49d7c74b57.png)
![5 1](https://user-images.githubusercontent.com/50572708/92314139-c32b0f00-efcb-11ea-98a2-6226fcc4b91c.png)
![5 2](https://user-images.githubusercontent.com/50572708/92314140-c3c3a580-efcb-11ea-91fd-1fc88b77fff3.png)
![5 22](https://user-images.githubusercontent.com/50572708/92314141-c3c3a580-efcb-11ea-99ca-6329df5c057c.png)

**Comment by Smanar** [comment]
Hello.
I m comparing the 2 devices, what is the difference ?

I can add the device in 5s, but can you test it (if there is difference, because I don't think I can make something bad just with adding this model)

**Comment by fryc88** [comment]
Visually there is nearly no difference. By hardware it only says it's been upgraded, and i spoke to peterguy04, who suggested me to add it here, because he says it's more like automated one, so not sure if that will cause any problem.
It's not been connected to boiler yet, but i've got it in my hands, so i can do whatever you want. I've got hub Hive Nano 2 V2 as well, but i'm not planning to use it, but if it can help someone else, i can do some stuff with it as well.

**Comment by Smanar** [comment]
If you want to try it.
The procedure is here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
Just replace step 1 by
`git clone --branch slr2b https://github.com/Smanar/deconz-rest-plugin.git`

and skip
`git checkout -b mybranch HEAD`

But I don't think I can be wrong, if you have problem you will just have it on next release.

**Comment by fryc88** [comment]
Got it ready, i'll test it tonight. Thanks

**Comment by fryc88** [comment]
![obraz](https://user-images.githubusercontent.com/50572708/92336132-4ebca280-f095-11ea-800f-817377224099.png)

All works perfect, thanks to Pete Guy for his time to explain it to me how to get it working, but all seems to be fine (except of 'auto' button, but he explained why, so that's not an issue, i'm not going to use their hub&cloud), and of course you, Smanar for adding it for me.
So now i need to wait for official release and hopefully HA will update it soon :)
Thanks!

**Comment by Smanar** [comment]
Yep @ peterguy04 know realy well this stuff ^^.
He have sniffed the hardware, all the protocol used in deconz is from him

**Comment by fryc88** [comment]
> 
> 
> Yep @peterguy04 know realy well this stuff ^^.
> He have sniffed the hardware, all the protocol used in deconz is from him

What's gonna be the version number of deconz which will contain it and possibly some ETA? So i'll keep my eye on it to see if HA will bring me the right version :)

**Comment by Smanar** [comment]
Probably the next one in some days (new version every 15).
But the PR need to be validated (I don't think we can have problem with this light one) and HA need to use the new version too.
