### ISSUE TITLE
Update restAPI documentation with Offsets

### ISSUE THREAD

**Issue by Mimiix** [dresden-elektronik/deconz-rest-plugin#3236]

**Comment by ebaauw** [comment]
This is not an issue for the REST API plugin, but for the documentation repo, https://github.com/dresden-elektronik/deconz-rest-doc.

**Comment by ebaauw** [comment]
And please provide all the info in the template ;-)

**Comment by Mimiix** [comment]
😂 @ebaauw I have another issue: 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3237
