### ISSUE TITLE
Recommendation: run deconz as user or root?

### ISSUE THREAD

**Issue by Stefan-83** [dresden-elektronik/deconz-rest-plugin#3238]
Hi,
I noticed, that there two instances of deconz running?

```
> pi@homebridge:~ $ systemctl restart deconz.service
> ==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
> Authentication is required to restart 'deconz.service'.
> Multiple identities can be used for authentication:
>  1.  ,,, (pi)
>  2.  root
> Choose identity to authenticate as (1-2):
```

Which one is the correct one?
Should I deactivate one?

Thanks again,
Stefan

**Comment by Smanar** [comment]
The security recommend don't use root, so better to use pi.

**Comment by Mimiix** [comment]
@Stefan-83 Use the following command:

sudo systemctl restart deconz.service

**Comment by Stefan-83** [comment]
So, i should deactivate the root-instance, correct?

**Comment by Mimiix** [comment]
No, just run the command i wrote :)

**Comment by Stefan-83** [comment]
ok, when i fire up your command: "sudo systemctl restart deconz.service" nothing happens.

When i type "systemctl restart deconz.service", i got the choice of root or pi (the user).
Should I deactivate the root-instance?

**Comment by Mimiix** [comment]
@Stefan-83 I guess. Because Sudo is like "start as administrator" in Windows.

**Comment by Stefan-83** [comment]
when i'm doing "sudo systemctl start deconz", i don't get any errors.. but nothing happens:
![image](https://user-images.githubusercontent.com/52136837/92398745-68a7c500-f129-11ea-99d8-9ec854a2ce54.png)

**Comment by Mimiix** [comment]
@Stefan-83 Means it started :)
Check the IP of it for it running.

**Comment by Stefan-83** [comment]
yes, it's running. When i'm typing "http://phoscon.de/pwa/" into the browser, I got this:
![image](https://user-images.githubusercontent.com/52136837/92399438-93dee400-f12a-11ea-9438-a58b6f727398.png)
(with IP 192.168.178.94)
But when i'm typing "http://192.168.178.94:8080/" into the browser, I got this:
![image](https://user-images.githubusercontent.com/52136837/92399579-cee11780-f12a-11ea-9a56-28f5794e0e39.png)

Is that correct?
