### ISSUE TITLE
False events after raspbee leaves network

### ISSUE THREAD

**Issue by steveStavros** [dresden-elektronik/deconz-rest-plugin#324]
Hi all,

I have a raspbee and I tried to connect 5 Centralite motion sensors and 5 Centralite door/window sensors.

After I successfully connected 6-7, it seems impossible to make the rest join the network no matter how many times I repeat the needed procedure. 
I used the deconz, made raspbee to leave the network and rejoined it after several minutes.
After this the following issues appeared:
1) some sensors (or none) although they seemed appeared did not response when I tried to get a measurement by using deconz
2) some sensors (or none) disappeared completely from the network
3) some sensors send false alarms to the websocket. For example I get repeatedly 'Door open alarm' although the door is closed.

Any idea why this happens?? Do I have to reset all devices? Also, why it is not possible to connect all sensors? Why every time I have connected 6-7 it is impossible to add new??

**Comment by manup** [comment]
Should work much better with recent versions.

Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
