### ISSUE TITLE
IKEA Tradfri Dimmer - version check

### ISSUE THREAD

**Issue by clementx2006** [dresden-elektronik/deconz-rest-plugin#3242]
Hello - just wondering if this one is supported? The list shows a wireless dimmer from IKEA but seems to be referring to an older generation? 

https://www.ikea.com/gb/en/p/tradfri-wireless-dimmer-white-00468432/

Thanks a lot!

**Comment by ebaauw** [comment]
The used to call this the on/off remote, which still is its technical name.  And yes, it’s supported by the API.

**Comment by Mimiix** [comment]
Hi @clementx2006 ,

As @ebaauw mentioned: It is supported. For your next issue, please stick to the issue templates.

As this issue is answered, i'll close it.

Kind regards,

**Comment by clementx2006** [comment]
Okay thank you
