### ISSUE TITLE
Conbee 2 on Debian 10

### ISSUE THREAD

**Issue by Sasch72** [dresden-elektronik/deconz-rest-plugin#3245]
Hello everybody,

I'm trying to install the Conbee 2 Stick on my Debian. Unfortunately, I made the mistake of installing it as root. I then made up for it again under the user with su. The stick is recognized and deConz also runs. I can also call up the deConz site via the IP of my Beelink. The stick is not displayed under Gateway. Where is my mistake?
Many thanks.

## Environment

 - Host system:  PC)
 - Running method: (Debian 10 without GUI)
 - Firmware version: (26580700)
 - deCONZ version: (2.05.78 / 22.05.2020)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II

**Comment by Sasch72** [comment]
Hi Mimiix,

I have adjusted the enviroment. I hope that's enough for now. Tonight I'll plug the stick into a USB extension cable and then try your instructions.
Thanks first of all.

**Comment by Sasch72** [comment]
Hi,
I have now connected a USB extension cable to my Beelink and misplaced the stick a bit. Then I carried out the installation as in the attached link. Now I can't even get to the "start page". No GUI is installed on the Debian.

**Comment by Smanar** [comment]
Take care, the procedure is for desktop and you are using GUI. Are you sure you are not running both service in same time ?

```
sudo systemctl status deconz
sudo systemctl status deconz-gui
```

Can you make a try on another machine ? It pehaps a problem on the device (firmware, the famous usb disconnect loop)

what is the result of command
`GCFFlasher_internal -l`

**Comment by Sasch72** [comment]
Hi,
I just quickly put on a Raspi and installed the Conbee 2. The data are in the environment.

These are the results of the query:

`root@debianiobroker:/home/pi1# sudo systemctl status deconz
● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: e
   Active: active (running) since Thu 2020-09-10 17:46:44 CEST; 1h 31min ago
 Main PID: 475 (deCONZ)
    Tasks: 2 (limit: 4569)
   Memory: 34.0M
   CGroup: /system.slice/deconz.service
           └─475 /usr/bin/deCONZ -platform minimal --http-port=80`

`root@debianiobroker:/home/pi1# sudo systemctl status deconz-gui
● deconz-gui.service - deCONZ: ZigBee gateway -- GUI/REST API
   Loaded: loaded (/lib/systemd/system/deconz-gui.service; disabled; vendor preset: enabled)
   Active: inactive (dead)`

**Comment by Smanar** [comment]
Not realy, all seem fine ^^.

>I just quickly put on a Raspi and installed the Conbee 2

And it have worked on the pi ?

>Now I can't even get to the "start page"

Even on http://phoscon.de/app ?

**Comment by Sasch72** [comment]
The stick worked without any problems on the Pi.

When I call up the link, it looks for a gateway and finds nothing.

**Comment by Smanar** [comment]
Have you tried to run deconz in debug mode ?

`
deCONZ --dbg-error=2 --dbg-info=2`

**Comment by Sasch72** [comment]
This is the result:
`root@debianiobroker:/home/pi1# deCONZ --dbg-error=2 --dbg-info=2
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.`

**Comment by Sasch72** [comment]
Good Morning,
I've finished the project for now. I installed a backup on my Raspberry Pi and will reinstall the Beelink with the Debian and then look again.
Many thanks for the support.

**Comment by Smanar** [comment]
Ha ?
So you have an idea the problem was from ?
