### ISSUE TITLE
Phoscon Authenticate App

### ISSUE THREAD

**Issue by xibriz** [dresden-elektronik/deconz-rest-plugin#325]
When i try to use the "Authenticate App" button in the Phoscon interface I always get the 403 reponse.

Using the "Unlock Gateway" in the Wireless Light interface works.

**Comment by manup** [comment]
Is this still the case? I wonder because both issue the same REST API command.

**Comment by xibriz** [comment]
No, I have not had any problems lately... probably my own fault :)
