### ISSUE TITLE
Release notes for Venus (v2.05.81) states that firmware should be updated manually

### ISSUE THREAD

**Issue by fi-sch** [dresden-elektronik/deconz-rest-plugin#3266]
## Describe the bug
Not sure if that's a bug in release notes or it is intended but it seem that two points in release notes are inconsistent.

I mean:
`The firmware needs to be installed manually.`
and
`Improved firmware update #3256`

Since #3256 states that `Enable firmware update via Phoscon App again.`, manual update requirement shouldn't be the case.
Am I right?

**Comment by Mimiix** [comment]
You are correct,  However:  some users don;t update their deCONZ versions due to various reasons. You can use the latest deCONZ/Phoscon again to firmware update, but manual updating could be done too.

**Comment by fi-sch** [comment]
Ok. Thanks for clarifying!

**Comment by Mimiix** [comment]
You are most welcome :) @fi-sch
