### ISSUE TITLE
Philips hue plugs 

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#3270]
Anyone tried this us version of the philips hue plug with deconz?

https://www.bestbuy.ca/en-ca/product/philips-hue-smart-bluetooth-plug/13888866

**Comment by MattL0** [comment]
Not in the compatible Deconz devices list...but works perfect here.

**Comment by Mimiix** [comment]
@MattL0 Can you update documentation :)?

**Comment by MattL0** [comment]
yes done :)

**Comment by Mimiix** [comment]
Your my hero!
Thanks!:)
