### ISSUE TITLE
Heavy disk (sdcard) usage since middle August

### ISSUE THREAD

**Issue by tnowak** [dresden-elektronik/deconz-rest-plugin#3271]
Hi. I'm using deConz/Phoscon 2.05.80 / 14.08.2020 in a docker container (marthoc/deconz:latest) on RPi with microSD card.
Lately I've noticed substantial IOPS increase in writes to my sdcard.
Using iotop -ao I've narrowed it down to (most probably) deconz process writing frequently to /opt/deconz/zll.db
Please see my IOPS graphs (only writes are important - colored in red):

![Untitled-3](https://user-images.githubusercontent.com/54801553/93409788-f1e09980-f897-11ea-8391-f57d0bee742e.png)

So it seems it started mid August and that would coincide with new deConz version released on Aug 14th.
At least no other software on my RPI writes to disk/card as much to my knowledge.
I would really like to keep my sdcard writes as low as possible, so my questions are:

1. Is it really by something that changed in deConz software? Can someone confirm my observations?
2. Can I somehow tune / define deConz disk write interval?

**Comment by Smanar** [comment]
Ha, it s perhaps the new filed added in device information `lastseen` ?

**Comment by tnowak** [comment]
Might be. I have quite a lot of devices (~50) so it might be an escalating factor.

**Comment by Smanar** [comment]
And IDK if it s usefull to memorize them, I think they are reseted after a reboot, but not sure.

**Comment by arthurgeek** [comment]
I also see consistent IOPS from my this running on docker. Any advices?

**Comment by Smanar** [comment]
Perhaps we can skip the write for "last seen" modifications ? Or ignore them for database (they don't need to be stored) ?

**Comment by manup** [comment]
> Perhaps we can skip the write for "last seen" modifications ? Or ignore them for database RW (they don't need to be stored) ?

Yes, saving and restoring them through database is ok, but setting the attribute shouldn't trigger a write database.
