### ISSUE TITLE
Retrieve End Dvices consumption

### ISSUE THREAD

**Issue by Rania-M** [dresden-elektronik/deconz-rest-plugin#3274]
Hi, i am implementing a home assistant application and i would like to know if there is an (official) way to retrieve power consumption from zigbee end devices via the deconz API , i searched for it but mostly found only users requests about this subject  (the devices do retrieve the consumption information but it seems that the API doesn't consider it)

- Environment : version : 2.05.78
 - Host system: Raspberry Pi 
 - Running method: Raspbian 
 - Device: RaspBee II

Thank you in advance

**Comment by Smanar** [comment]
I think it s not possible having it. The consumption depend of usage. End device use hibernating working mode, so if you don't disturb it, it will have different consumption than another one that is trigger every 10mn.

**Comment by SwoopX** [comment]
Was is that question supposed to mean? Either a device offers measurement capabilities, then it is exposed though the API, or not. Simple as that.

**Comment by Smanar** [comment]
He don't sepak about power consumption mesured by a device but the device consumption itself (end device never provide power measurement)

**Comment by SwoopX** [comment]
None does afaik

**Comment by Rania-M** [comment]
the device i need to retreive the information from is develco smart plug, in the product presentation, it is clearly mentionned that the device does return the consumed power , i woul like to know if there is a way to get this information using the deconz api, thank you

**Comment by Smanar** [comment]
Ok so perhaps the device is not supported, so you can have light entries, for on/off but not the sensor with consumption.

You have the model id of the device ? (visible in deconz)

**Comment by SwoopX** [comment]
Which zigbee modelID does the device have? I know that a Develco smart plug is supported (SPLZB-131).

**Comment by Rania-M** [comment]
well its the same (SPLZB-131)
The device is supported, i can ,turn  it on and off using the API, the problem is retrieving the power consumption information

**Comment by SwoopX** [comment]
How do you determine the availability of the power and consumption resources? Have you queried the API directly?

Eventually, you need to enter sensor search in Phoscon again and switch the plun on while a load is applied. Alternatively, read the attributes of the basic cluster with active search.

**Comment by Rania-M** [comment]
Well i actually just send a get lights request to the API, i should also mention that the plug is detected as a light, not as a sensor.
When i send this request i get the state information, which i can usé to switch it on and off but there is no consumption value anywhere, maybe im not singers the right method

**Comment by Smanar** [comment]
The on/off feature is an a "light" (always created)
The consumption is in a "sensor" (only crated if device is supported)

**Comment by Rania-M** [comment]
You mean that one device can be represented as a light and sensor at the same time ?

**Comment by Smanar** [comment]
Yep (or more)

**Comment by Rania-M** [comment]
Ok i will check this out , thanks

**Comment by Mimiix** [comment]
@Rania-M Can i close this?
