### ISSUE TITLE
ROBB Rotary dimmer and EcoDim Rotary dimmers state updates

### ISSUE THREAD

**Issue by aryelevin** [dresden-elektronik/deconz-rest-plugin#3275]
When I'm using my ROBB Rotary dimmer and EcoDim Rotary dimmers their state is not reflected either on phoscon or homebridge-hue.

Only after few minutes (about 10 minutes or so).

What could be the problem?

## Environment
deCONZ v2.05.81 on Debian 10.

 - Host system: Debian 10.
 - Running method: VirtualBOX.
 - Firmware version: (26650700)
 - deCONZ version: (2.05.81)
 - Device: ConBee II
 - Do you use an USB extension cable: yes

I have some ubisys D1 units and their state is reflected immediately.

**Comment by SwoopX** [comment]
Which device? Which state? I'm afraid your input is a little rare here.

**Comment by aryelevin** [comment]
OK, so here you have a links to both devices with this issue.
1. https://en.robbshop.nl/draaidimmer-zigbee-ecodim
2. https://en.robbshop.nl/hue-rotary-dimmer-zigbee-2-wire

So the problem is that their state is not being updated in real-time, only after few minutes it changes state on the apps.
Steps to reproduce:
1. Open App/phoscon and navigate to the "light" on the group is it in or inside "lights" list.
2. Toggle power manually on the dimmer itself or change brightness.
3. No changes on the App/phoscon.

Expected behavior: Changes made locally should be reflected on the App/phoscon immediately.

Thanks for everyone.

**Comment by SwoopX** [comment]
Ok, now the picture becomes clearer. It seems both devices are "not fully supported", which means: Typically, lights and wired switches are supported out of the box. However, some details might be missing, which I suspect in your case being the bindings for attribute reporting. That would explain why the attributes are polled like around every 10 mins (and only then updated), whereas the update should be instant with active reporting.

Can you please provide a screenshot from the node info panel as well as from the basic cluster with the attributes being read for both devices?

**Comment by aryelevin** [comment]
OK, here you have it.
<img width="412" alt="Screen Shot 2020-09-21 at 12 34 16" src="https://user-images.githubusercontent.com/5435949/93752402-4a50c780-fc07-11ea-8d2d-e3ab0f2c5517.png">
<img width="412" alt="Screen Shot 2020-09-21 at 12 34 24" src="https://user-images.githubusercontent.com/5435949/93752417-4e7ce500-fc07-11ea-8b82-7c735908f6c7.png">
<img width="474" alt="Screen Shot 2020-09-21 at 12 36 32" src="https://user-images.githubusercontent.com/5435949/93752420-4fae1200-fc07-11ea-882f-ca50b68c2658.png">
<img width="474" alt="Screen Shot 2020-09-21 at 12 36 48" src="https://user-images.githubusercontent.com/5435949/93752421-5046a880-fc07-11ea-8950-a42c1397f175.png">

**Comment by aryelevin** [comment]
@SwoopX Any idea on how to solve it?
Can I configure the bindings myself? (even by updating the db file for example?)

Thanks a lot

**Comment by timovos** [comment]
I'm also having the Robb rotary dimmer. Sometimes the dimmer has to be pushed twice to turn it on. Possibly this issue is related. Following!

**Comment by aryelevin** [comment]
@timovos  I don't think it could be related, since the local control should not be interfering from the wireless control.
It might possible that you dim you lights so low that it appears to be off, and then when you trying to switch them on, your first push is actually turns it off and the second push turns it on at some higher level as configured by defaults.
If this is the case, you should configure the Min. Brightness level to match your bulbs (look on the owners manual came with the dimmer), and then it will be solved.

**Comment by aryelevin** [comment]
For everyone else, I used the "Bind Dropbox" pane to do the Binding myself, simply but dragging the On/Off cluster and the Level Control cluster as source (each at a time of-course) and the Coordinator (Its "Configuration Tool" service) as Destination and clicked Bind Button.
Then it works perfectly.

Thanks for everyone
