### ISSUE TITLE
Sengled E1D-G73 sensor not working

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/deconz-rest-plugin#3276]
- Product name: Sengled Smart Window & Door Sensor (E1D-G73)
- Manufacturer: N/A
- Model identifier: N/A
- Device type : Sensor

![image](https://user-images.githubusercontent.com/37962790/93521553-3acb3900-f8fe-11ea-9c9a-2422eed2cd21.png)

Hello,
I have a couple of the Sengled E1D-G73 sensors that are not working in deconz v2.05.82. The node shows up in the deconz gui app, but is not reading/populating the clusters. The dot for the drop-down cluster menu is not even showing on the node object in the gui.
Issue #2870 indicates that this device should be supported as of v2.05.78.

**Comment by Mimiix** [comment]
Instantly closing this. 

Wrong template used and not all information is provided. Also, use a User Question template.
