### ISSUE TITLE
Sengled Smart Switch E1E-G7F

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/deconz-rest-plugin#3287]
## Describe the question or issue you are having
Hello,
I have a Sengled E1E-G7F Smart Switch that is not working in deconz v2.05.82. The node shows up in the deconz gui app, but is not reading/populating the clusters. The dot for the drop-down cluster menu is not even showing on the node object in the gui.
Without the clusters, I'm not sure how to gather proper data and screenshots.

## Screenshots
![image](https://user-images.githubusercontent.com/37962790/93599652-7a406680-f98c-11ea-97e1-0b6453409ad9.png)

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26370500
 - deCONZ version: 2.05.82
 - Device: RaspBee I

**Comment by Mimiix** [comment]
Hi,

Seems like it's not paired correctly. 

You should re pair a few times.

**Comment by stevenwfoley** [comment]
I've must have tried (re)pairing the device like a dozen times, but I guess it just needed that one last 13th repairing attempt. Its now showing up in deconz gui properly but not in phoscon. Is this suppose to be a supported device? Should I open a device request issue?

**Comment by Mimiix** [comment]
@stevenwfoley 

Phoscon is a different application. If the device works fine with the rest-api / ha /homebridge, you need to request support in the Phoscon repo.

**Comment by SwoopX** [comment]
I cannot recall this devices being supported...

**Comment by stevenwfoley** [comment]
Thanks all, I'll submit a new device request.
