### ISSUE TITLE
Phoscon app doesn't work on Raspberry Stretch default web browser

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#329]
After one of the recent `apt upgrade` runs, Stretch now provides GNOME Web 3.8.2 as default web browser, see https://wiki.gnome.org/Apps/Web.  Somehow that browser doesn't render Phoscon (as distributed with v2.04.97) correctly.  The old web app seems to work under Web; copying/pasting the Phoscon URL into Chromium (which is still installed) also works.

**Comment by manup** [comment]
Yes currently the Phoscon App works and is testet with Chrome, Firefox, Safari, Samsung Browser and Edge (early support). I think on Raspberry the Phoscon App button should open the chromium based browser and maybe issue a warning if opened in a unsupported browser (or when certain features are missing).

**Comment by marthoc** [comment]
Phoscon works great on Safari for Mac but the layouts are a little messed up on mobile Safari.

**Comment by manup** [comment]
> Phoscon works great on Safari for Mac but the layouts are a little messed up on mobile Safari.
On which device and iOS version is your mobile Safari?

We do test with Safari 11 on desktop and Safari 11 iPad (2016), Safari 10 iPad + iPhone 5.

If you can provide a screenshot we check what the issue is.

**Comment by marthoc** [comment]
iPhone 7 Plus on iOS 11. Here are some screenshots:
![b1d11278-9710-4665-82fc-8718f64f1ec9](https://user-images.githubusercontent.com/30442019/34070103-5bc33472-e22d-11e7-9671-4cfa3c78320e.png)
![5902bc32-26ec-48ca-b42d-14dc9ca957ff](https://user-images.githubusercontent.com/30442019/34070104-5bd10a34-e22d-11e7-9c3a-521232e8eea2.png)
![3bbe6111-6fb4-40e0-b253-30aa34aa06c5](https://user-images.githubusercontent.com/30442019/34070105-5bdd6d88-e22d-11e7-9e28-5eb123889017.png)
![ed6db93e-463e-416c-b266-4eef5da1a5f5](https://user-images.githubusercontent.com/30442019/34070106-5be8e97e-e22d-11e7-9520-4bb96fe81423.png)
On the sensor and switch pages I’m missing the “Add” button and an extra Column of information unless I turn my device sideways. Then I can see the Add button. But if I click it then you can also see the next screen for selecting the vendor is not scaling properly.

**Comment by manup** [comment]
Ah I see, yes indeed the mobile phone sensor and switch wizards as well as phone landscape mode are not finished yet. The for now wizards require at least tablet size screen.

**Comment by marthoc** [comment]
Ok! I can live with the layouts because the functionality works as it should! :)
