### ISSUE TITLE
Aqara Opple Switch operates all lights on button click

### ISSUE THREAD

**Issue by easybeat** [dresden-elektronik/deconz-rest-plugin#3290]
Hi

I received an Aqara Opple Switch 6-Button and after some problems I was able to join it in phoscon app. It is showing correctly but when I press one off the top buttons ALL lights on my system switch on or off! I did check if there was a group with all lights assigned to the button but no lights or group is assigned to the switch as I can see in phoscon.

I'm running the latest version 2.5.82 of deconz.

Any ideas what I have todo to get this working without all lights control?

Kind regards

Beat

**Comment by Mimiix** [comment]
Hi @easybeat I am closing this issue instantly. 

A lot of information is missing and you have completely ignored the template.

You are free to open a issue with correct information.
