### ISSUE TITLE
Sonoff SNZB-03 Motion Sensor (MSO1)

### ISSUE THREAD

**Issue by asgothian** [dresden-elektronik/deconz-rest-plugin#3295]
I would like to request support for the new Sonoff Occupancy sensors (They are marketed as Motion Sensors, but i am 99% certain they sense occupancy, not motion)_

<img width="364" alt="Screen Shot 2020-09-21 at 22 42 03 " src="https://user-images.githubusercontent.com/45667167/93819164-af360d00-fc5b-11ea-873e-a10740ee6aa4.png">

## Device

- Product name: Sonoff SNZB-03
- Manufacturer: eWeLink
- Model identifier: MSO1.
- Device type : Occupancy Sensor
   - Sensor
  

## Screenshots

<img width="545" alt="Screen Shot 2020-09-21 at 22 34 26 " src="https://user-images.githubusercontent.com/45667167/93818410-9e38cc00-fc5a-11ea-91e8-16957a80c947.png">
<img width="221" alt="Screen Shot 2020-09-21 at 22 34 49 " src="https://user-images.githubusercontent.com/45667167/93818450-abee5180-fc5a-11ea-800a-72d9719f9a63.png">
<img width="551" alt="Screen Shot 2020-09-21 at 22 35 36 " src="https://user-images.githubusercontent.com/45667167/93818533-c7595c80-fc5a-11ea-90d2-e5ec35c0beb6.png">
<img width="548" alt="Screen Shot 2020-09-21 at 22 37 41 " src="https://user-images.githubusercontent.com/45667167/93818924-4ea6d000-fc5b-11ea-828f-2cb8bd1b6991.png">
<img width="549" alt="Screen Shot 2020-09-21 at 22 36 26 " src="https://user-images.githubusercontent.com/45667167/93818962-5a929200-fc5b-11ea-857e-c2a26809ade9.png">

**Comment by Mimiix** [comment]
Already integrated into deCONZ. 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2991

**Comment by SwoopX** [comment]
Tapped almost in the same trap, different model ID here 😉

**Comment by Mimiix** [comment]
Really?

Good catch!

**Comment by asgothian** [comment]
Which version has this integrated ? I am running 2.05.80 / 8/14/2020, and the sensors are not recognized.

A.

**Comment by SwoopX** [comment]
Please use the search function to find out. You can't miss it.
