### ISSUE TITLE
#define VENDOR_CENTRALITE   0x104E // wrong name?

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/deconz-rest-plugin#3301]
Hello, I have an Osram Smart+ Motion Sensor. Deconz shows the manufacturer ID 0x110c.

However, this is defined differently:
`#define VENDOR_CENTRALITE   0x104E // wrong name?`

Could it be that the manufacturer ID 0x104E is (as well as 0x110c) also for Osram?

**Comment by Smanar** [comment]
No it s ok for me.
0x110c is Osram so no problem for manufacture number
Your device have "CentraLite" as manufacture name, but this value is written on the firmware (String value, not a number for here)

**Comment by Mimiix** [comment]
@7wells Closing this issue. Not using the template.

**Comment by 7wells** [comment]
??

**Comment by Mimiix** [comment]
Please read: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3199

**Comment by 7wells** [comment]
Thanks for reminding me.
