### ISSUE TITLE
New device support request: Linkind Motion Sensor / ZS110040078

### ISSUE THREAD

**Issue by fluffyironboots** [dresden-elektronik/deconz-rest-plugin#3306]
Hi,

I just bought some new motion sensors from Linkind.
https://www.linkind.com/product/pir-motion-sensor-zigbee/
https://www.amazon.de/Linkind-Bewegungssensor-intelligenter-Bewegungsmelder-Tageslichtsensor/dp/B07YFCHYYK/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=linkind+motion&qid=1600869875&sr=8-1

The GU10 CCT lamps from linkind are also not on the official support list but they work flawlessly in Phoscon so i thought i just try the sensor.

Data and Screenshots:
Model ZS110040078
FCC ID: 2ASHKZS110040078
![Linkind_Motion_BasicNode](https://user-images.githubusercontent.com/7325705/94024365-9c384f80-fdb7-11ea-981d-891524e4a3e4.PNG)
![Linkind_Motion_NodeInfo](https://user-images.githubusercontent.com/7325705/94024367-9cd0e600-fdb7-11ea-8f01-33500798e3ac.PNG)

Let me know if you need more info.

Thanks,
Joe

**Comment by Mimiix** [comment]
@SwoopX Could you verify the above is enough? If not, please close this issue.

@fluffyironboots **If Swoop says this is enough to go on, i'll add the device Request label. Otherwise it gets closed. Following the Issue template is mandatory.**

**Comment by fluffyironboots** [comment]
Just had time to test some more.
Got the Basic and PowerConfiguration Cluster Info to successfully read.

![Linkind_Motion_Power](https://user-images.githubusercontent.com/7325705/94162003-8ba2da80-fe86-11ea-8a5e-3c4b7f9b7460.PNG)
![Linkind_Motion_BasicNode_Update](https://user-images.githubusercontent.com/7325705/94162004-8c3b7100-fe86-11ea-86c7-951abb032262.PNG)

**Comment by SwoopX** [comment]
Info provided is sufficient.

**Comment by Mimiix** [comment]
@fluffyironboots I'll keep it open and added the label. For the next request, make sure to use the template.

**Comment by fluffyironboots** [comment]
@Mimiix Thank you for your help. I don't even now how i opened the issue without the template. I clicked on new issue and got right to an empty input without the option to choose a template. Next time i'll do better.
