### ISSUE TITLE
Innr bulb pairing with deconz?

### ISSUE THREAD

**Issue by membersound** [dresden-elektronik/deconz-rest-plugin#3312]
At the moment, my Innr bulb is paired with a Philips Hue Dim Switch, *without* any bridge or hub in between.

Is it possible to connect the Innr *additionally* to deconz, while keeping the dim switch functionality?
If yes, how?

**Comment by ebaauw** [comment]
No, a device can only join one network at a time.

You can pair both the bulb and the dimmer switch to deCONZ, and then add the bulb to the group associated with the dimmer switch, so it will control the light even when the gateway is down.

**Comment by Mimiix** [comment]
@membersound Please use the right template and fill in all details requested.

As the answer is provided, i'll close this issue.
