### ISSUE TITLE
OSRAM Smart+ Candle E14 (B40 DIM Z3) - loosing coordinator after power off

### ISSUE THREAD

**Issue by SAOPP** [dresden-elektronik/deconz-rest-plugin#3315]
Hi!

Guys, OSRAM E14 model B40 DIM Z3. The first time I ran into a problem a few weeks ago - turning off this bulb and turning it on again, I had to reconnect it. Tonight there was a short power outage, and again, the lamp was like from the factory... I had to re-pair it again.

In this regard, the question is, does anyone have the same behaviors with this device too? And the question to the developers, what data is worth sharing based on the above?

Right now, the device is connected to the conbee2 with phoscon 2.05.82 / 14.09.2020 and firmware is 264A0700 in docker at x86.

![image](https://user-images.githubusercontent.com/5647009/94278070-12bd8480-ff53-11ea-8d35-67a1b70083de.png)

![image](https://user-images.githubusercontent.com/5647009/94278178-31bc1680-ff53-11ea-88e8-502d828cc8a9.png)

Thanks.

**Comment by Mimiix** [comment]
Could it be that the device is broken? Maybe it doesn't safe the settings on itself?

**Comment by SAOPP** [comment]
I thought about it too. I do not have a second such lamp, there are two with warm white light. This device is dimmable warm only.
