### ISSUE TITLE
Settings wiped

### ISSUE THREAD

**Issue by timpa82** [dresden-elektronik/deconz-rest-plugin#3318]
I am experiencing problems while using Intel NUC with SSD with docker of Portainer, deconz and Home Assistant. Deconz is running on a Conbee II stick and Home Assistant on a Aeotec stick using /dev/serial/by-id/ kind of naming so is staying the same after booting.

Last night I had a power failure and rebooted the NUC with rest of the network. I decided at the time to pull possible upgrades for my docker-compose, upgrading phoscon to 2.05.82, cant remember what I had earlier but was a few months ago.
When I logged into Phoscon app my settings was wiped and was asked to chose a new gateway username and password, which I did. Everything was wiped. What I could notice the identity of the hardware used to be called Raspbee even if it was Conbee II but I didnt bother. Now it said the right Conbee II, possibly something with .82 version.

I tried restart, stop and start the containers but still had the same issue with deconz, Home Assistant was working as intended.
Tried reboot the NUC with no success. So I decided to readd all my devices (mostly IKEA lights and Osram switch). I tried stop the containers and start them again. After that my settings was wiped yet again, and seem to happen every time I stop and start the cointainers, but only with deconz.

I can add after the power failure I couldnt find the USB stick of Conbee II, but was solved when I removed it physically from the NUC and reinserted it.

Any ideas?

Log from Portainer trying to restart the deconz container: https://pastebin.com/VGAVYfFC
Log from Portainer after rebooting the NUC and restarting the containers: https://pastebin.com/AQRNN5AK

**Comment by Mimiix** [comment]
Closing this issue as it is not following template.

#3199
