### ISSUE TITLE
ptvo switch relay

### ISSUE THREAD

**Issue by moshiko2312** [dresden-elektronik/deconz-rest-plugin#3319]
Hey
First of all thank you so much for the work you do it is just amazing

I use an 8/4 Relay box
My main use is in the Home Assistant system with a CONBEE 2 adapter
* I manage to pair the product and even see it configured in the system
The problem is when I turn on the relay after 30 seconds the on-screen indication shows that the relay is off (actually the relay is still on)
It is possible to get a solution to this issue
Thank you

I enclose some links on the relevant product

[https://www.zigbee2mqtt.io/devices/ptvo.switch.html](url)

[https://ptvo.info/zigbee-switch-configurable-firmware-router-199/](url)

[https://ptvo.info/zigbee-switch-configurable-firmware-v2-210/](url)
![conx1](https://user-images.githubusercontent.com/48163773/94339863-06463400-0006-11eb-8c24-c1d0788d37a1.PNG)
![P4](https://user-images.githubusercontent.com/48163773/94339867-0cd4ab80-0006-11eb-8974-81a8d6d67607.PNG)
![P1](https://user-images.githubusercontent.com/48163773/94339868-0e05d880-0006-11eb-8310-bd737856067f.PNG)
![P2](https://user-images.githubusercontent.com/48163773/94339869-0e9e6f00-0006-11eb-9636-8830874853b4.PNG)
![P3](https://user-images.githubusercontent.com/48163773/94339870-0f370580-0006-11eb-8a29-0a00b3190d98.PNG)
![R8_3](https://user-images.githubusercontent.com/48163773/94340187-70f86f00-0008-11eb-9b02-543a206c2d84.jpeg)
![R8_4](https://user-images.githubusercontent.com/48163773/94340188-71910580-0008-11eb-8595-f6ba39fcc9b6.jpeg)
![R4_1](https://user-images.githubusercontent.com/48163773/94340189-72299c00-0008-11eb-847b-baf680a22e12.jpeg)
![R8_1](https://user-images.githubusercontent.com/48163773/94340190-72c23280-0008-11eb-8f31-f149aaf3c102.jpeg)
![R8_2](https://user-images.githubusercontent.com/48163773/94340191-735ac900-0008-11eb-85a0-6ee3eac89f21.jpeg)

**Comment by kachalex** [comment]
I have this problem too,  status does not show correctly.
I will be very glad, if you solve this problems.
With ziqbee2mqqt works well.

**Comment by Mimiix** [comment]
@moshiko2312 I am really tempted to close this one.

Please fill the template details and i am willing to add the label.

**Comment by moshiko2312** [comment]
Hey
I'm really sorry, this is the second time I'm opening, I do not really know or can change the label.
Can I have an explanation?

**Comment by Mimiix** [comment]
@moshiko2312 When you create a issue, it presents you with 4 options. After selecting the right one for your needs, it already contains text. That text needs to be adjusted to your information.
