### ISSUE TITLE
Bitron plug-in unit 902010/28: device shown as type: "unknown" in REST API

### ISSUE THREAD

**Issue by hpd96** [dresden-elektronik/deconz-rest-plugin#332]
Hello, 

using deconz .99 on RaspBee
using Bitron power plug-in unit "902010/28"
http://www.bitronvideo.eu/index.php/produkte/smart-home-produkte/smart-plug-mit-schaltfunktion/

[ BTW:  thanks a lot: after updating from .86 to .99 my Philips Hue was detected finally. Great new Phoscon App!!  ]  👍 

The REST API and GUI node table showing "type" as
"unknown"
expected
"On/Off plug-in unit"

may be because of that openHAB can't work with Bitron Plug-in unit via "hue binding" using RaspBee

Device can be used using Phoscon App to switch lights.

In the GUI under "Cluster Info Basic" there was also printed "unknown" manufacturer nad no version.

After clicking on "READ" button the fields are updated to "Bitron" and "20170216"

however REST API response stays incomplete.

JSON:
```javascript
  "2": {
    "etag": "d9aca1082bccb957bfc51de8a5fb1e1e",
    "hascolor": false,
    "manufacturername": "Unknown",
    "modelid": "902010/28",
    "name": "WZ Westen",
    "state": {
      "alert": "none",
      "on": false,
      "reachable": true
    },
    "swversion": "",
    "type": "Unknown",
    "uniqueid": "00:12:4b:00:0e:f5:bf:9e-01"
  },
```

![bitron-plug-deconz](https://user-images.githubusercontent.com/17209165/34102415-5f092b92-e3e9-11e7-8abf-386b26c7ccff.jpg)

**Comment by manup** [comment]
The Bitron power-plug should work with recent versions.
