### ISSUE TITLE
Device Add support for Stelpro Orleans Fan (SORB)

### ISSUE THREAD

**Issue by goldriver2** [dresden-elektronik/deconz-rest-plugin#3323]
## Device

- Product name: Stelpro Orleans Fan
- Manufacturer: Stelpro
- Model identifier: SORB
- Device type :  Thermostat
  

## Screenshots
![stelpro1](https://user-images.githubusercontent.com/7215561/94349930-44981f00-0017-11eb-9cc0-6b6cc9f22355.JPG)
![Stelpro2](https://user-images.githubusercontent.com/7215561/94349932-47930f80-0017-11eb-9173-a5ea5d8b8119.JPG)
![Stelpro3](https://user-images.githubusercontent.com/7215561/94349936-4d88f080-0017-11eb-87fa-4812b547c984.JPG)

**Comment by Mimiix** [comment]
Missing cluster info /screens

**Comment by goldriver2** [comment]
Sorry I missed the other cluster... here they are:

![a1](https://user-images.githubusercontent.com/7215561/94420601-62b66a00-0152-11eb-9ab5-c5be6eef0fb7.JPG)
![a2](https://user-images.githubusercontent.com/7215561/94420615-65b15a80-0152-11eb-82a6-29ab31a00f34.JPG)
![a3](https://user-images.githubusercontent.com/7215561/94420625-68ac4b00-0152-11eb-8402-216de491e3c2.JPG)
![a4](https://user-images.githubusercontent.com/7215561/94420633-6b0ea500-0152-11eb-953d-3b51fa89e0e9.JPG)
![a5](https://user-images.githubusercontent.com/7215561/94420642-6ea22c00-0152-11eb-9260-4d3309c76277.JPG)
![a6](https://user-images.githubusercontent.com/7215561/94420651-719d1c80-0152-11eb-8852-4048039ebf6e.JPG)

**Comment by Mimiix** [comment]
@SwoopX Is this complete?

**Comment by goldriver2** [comment]
Is there anything missing in the provided information that prevent the device to be added ?

**Comment by SwoopX** [comment]
The thermostat cluster is incomplete. For the rest, I'm good at guessing which cluster that data comes from...

**Comment by goldriver2** [comment]
sorry I missed the rest of the thermostat cluster, here are all the thermostat cluster informations
![1](https://user-images.githubusercontent.com/7215561/94989599-19945a80-0544-11eb-8e44-51a91e331649.JPG)
![2](https://user-images.githubusercontent.com/7215561/94989601-1bf6b480-0544-11eb-9937-8f3a15c0ed0c.JPG)
![3](https://user-images.githubusercontent.com/7215561/94989617-2d3fc100-0544-11eb-9ca6-680d8a647e03.JPG)
![4](https://user-images.githubusercontent.com/7215561/94989619-303ab180-0544-11eb-8200-05d16f19b06a.JPG)
![5](https://user-images.githubusercontent.com/7215561/94989623-34ff6580-0544-11eb-94a0-00e67243222d.JPG)

**Comment by goldriver2** [comment]
> The thermostat cluster is incomplete. For the rest, I'm good at guessing which cluster that data comes from...

sorry I missed the rest of the thermostat cluster, here are all the thermostat cluster informations
![1](https://user-images.githubusercontent.com/7215561/95256391-c09d1e80-07f0-11eb-9ed5-b738225bcd5a.JPG)
![2](https://user-images.githubusercontent.com/7215561/95256401-c2ff7880-07f0-11eb-9a42-c8397d77a1d6.JPG)
![3](https://user-images.githubusercontent.com/7215561/95256408-c561d280-07f0-11eb-9128-3e0e07feb5d5.JPG)
![4](https://user-images.githubusercontent.com/7215561/95256420-ca268680-07f0-11eb-9463-1385cf22d4f0.JPG)
![5](https://user-images.githubusercontent.com/7215561/95256429-cc88e080-07f0-11eb-9bae-ed82baa71380.JPG)

**Comment by SwoopX** [comment]
Closing this one as it is supported with version 2.06.00.
