### ISSUE TITLE
PTVO Switch Relay 4/8

### ISSUE THREAD

**Issue by moshiko2312** [dresden-elektronik/deconz-rest-plugin#3324]
Hey
First of all thank you so much for the work you do it is just amazing

I use an 8/4 Relay box
My main use is in the Home Assistant system with a CONBEE 2 adapter
* I manage to pair the product and even see it configured in the system
The problem is when I turn on the relay after 30 seconds the on-screen indication shows that the relay is off (actually the relay is still on)
It is possible to get a solution to this issue
Thank you

I enclose some links on the relevant product

[https://www.zigbee2mqtt.io/devices/ptvo.switch.html](url)

[https://ptvo.info/zigbee-switch-configurable-firmware-router-199/](url)

[https://ptvo.info/zigbee-switch-configurable-firmware-v2-210/](url)
![conx1](https://user-images.githubusercontent.com/48163773/94339863-06463400-0006-11eb-8c24-c1d0788d37a1.PNG)
![P4](https://user-images.githubusercontent.com/48163773/94339867-0cd4ab80-0006-11eb-8974-81a8d6d67607.PNG)
![P1](https://user-images.githubusercontent.com/48163773/94339868-0e05d880-0006-11eb-8310-bd737856067f.PNG)
![P2](https://user-images.githubusercontent.com/48163773/94339869-0e9e6f00-0006-11eb-9636-8830874853b4.PNG)
![P3](https://user-images.githubusercontent.com/48163773/94339870-0f370580-0006-11eb-8a29-0a00b3190d98.PNG)
![R8_3](https://user-images.githubusercontent.com/48163773/94340187-70f86f00-0008-11eb-9b02-543a206c2d84.jpeg)
![R8_4](https://user-images.githubusercontent.com/48163773/94340188-71910580-0008-11eb-8595-f6ba39fcc9b6.jpeg)
![R4_1](https://user-images.githubusercontent.com/48163773/94340189-72299c00-0008-11eb-847b-baf680a22e12.jpeg)
![R8_1](https://user-images.githubusercontent.com/48163773/94340190-72c23280-0008-11eb-8f31-f149aaf3c102.jpeg)
![R8_2](https://user-images.githubusercontent.com/48163773/94340191-735ac900-0008-11eb-85a0-6ee3eac89f21.jpeg)

**Comment by kachalex** [comment]
I have this problem too, status does not show correctly.
I will be very glad, if you solve this problems.
With ziqbee2mqqt works well.

**Comment by Mimiix** [comment]
Same as #3319 , But now you need to provide all correct information. 
Please check https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3319#issuecomment-699828336

I am missing all clusters read and your deconz version info.

**Comment by kachalex** [comment]
deconz version info - 2.05.82 / 14.09.2020
firmware - 26580700
![01 Basic 0000](https://user-images.githubusercontent.com/42259721/94407142-bbe6c380-017b-11eb-82fa-aef3c344a01a.png)
![01 Diagnostics 0B05](https://user-images.githubusercontent.com/42259721/94407146-bdb08700-017b-11eb-86c7-cc02aa5e3ab2.png)
![01 Multistate Input Basic 0012](https://user-images.githubusercontent.com/42259721/94407149-bee1b400-017b-11eb-8e4c-7c2039777a57.png)
![01 On off 0006](https://user-images.githubusercontent.com/42259721/94407152-bf7a4a80-017b-11eb-8085-f722b506d246.png)
![02 Basic 0000](https://user-images.githubusercontent.com/42259721/94407154-c012e100-017b-11eb-8c26-cb21a7ba620f.png)
![02 Multistate Input Basic 0012](https://user-images.githubusercontent.com/42259721/94407155-c1440e00-017b-11eb-8345-d9a0c81a636d.png)
![02 On off 0006](https://user-images.githubusercontent.com/42259721/94407158-c1dca480-017b-11eb-89c3-61a46907a5b1.png)
![03 Basic 0000](https://user-images.githubusercontent.com/42259721/94407159-c2753b00-017b-11eb-890b-cd16cd8f2b0a.png)
![03 On off 0006](https://user-images.githubusercontent.com/42259721/94407161-c30dd180-017b-11eb-9667-807a3fe84aba.png)
![04 Basic 0000](https://user-images.githubusercontent.com/42259721/94407167-c43efe80-017b-11eb-8b2b-d76cd39f867b.png)
![04 Multistate Input Basic 0012](https://user-images.githubusercontent.com/42259721/94407170-c4d79500-017b-11eb-82fa-c65893b1d198.png)
![04 On off 0006](https://user-images.githubusercontent.com/42259721/94407175-c5702b80-017b-11eb-9255-c19d9cd807ca.png)
![05 Basic 0000](https://user-images.githubusercontent.com/42259721/94407177-c6a15880-017b-11eb-8afb-bbe3375b5393.png)
![05 On off 0006](https://user-images.githubusercontent.com/42259721/94407178-c739ef00-017b-11eb-82bc-d1deb659fbe2.png)

**Comment by kachalex** [comment]
If i do attributes read - takes the correct status.

![attributes read](https://user-images.githubusercontent.com/42259721/94421662-8dbeaf00-018e-11eb-85db-ab2b6234812f.png)

What should be done? To automatically read the status?

![attributes on read](https://user-images.githubusercontent.com/42259721/94421628-84cddd80-018e-11eb-81b9-3a96c662e369.png)

**Comment by Mimiix** [comment]
Attributes need to be read ;)

**Comment by kachalex** [comment]
I have more than 30 more devices and I don't have to go in and read the status with VNC every time after each change.

**Comment by SwoopX** [comment]
You're still not following the template... Regardless.

What is the issue here? You wrote:

> The problem is when I turn on the relay after 30 seconds the on-screen indication shows that the relay is off (actually the relay is still on)

What on-screen display? On the device? Does it work from a functionality perspective?

**Comment by moshiko2312** [comment]
Hey
Functionally it works but there is no display in Home Assistant
The button returns to the off position
It does not perform a read mode of the Riley box

**Comment by SwoopX** [comment]
This may be a HA thing where we cannot help. However, does the state get right after like 10 mins without touching it?

**Comment by kachalex** [comment]
This problem starts back in Phoscon App, before forwarding to HA. The state does not become correct: not after 10 minutes, not after an hour and a day without touching it. After each status change, you must manually read attributes.

**Comment by kachalex** [comment]
Here is an example how is displayed relay 8 in zigbee2mqtt:
![relay 8](https://user-images.githubusercontent.com/42259721/94995899-fa301880-05a9-11eb-8793-cba418a8603d.png)
![relay 8-1](https://user-images.githubusercontent.com/42259721/94995901-fbf9dc00-05a9-11eb-8253-1236e0484f8f.png)
![relay 8-2](https://user-images.githubusercontent.com/42259721/94995902-fbf9dc00-05a9-11eb-855f-660b7f7ee80c.png)
![relay 8-3](https://user-images.githubusercontent.com/42259721/94995903-fc927280-05a9-11eb-8481-e20c7be9f235.png)
![relay 8-4](https://user-images.githubusercontent.com/42259721/94995905-fc927280-05a9-11eb-8027-ad5937880480.png)




 

0x00124b001fb3df83

Router
Description
[Multi-channel relay switch](https://ptvo.info/zigbee-switch-configurable-firmware-router-199/)
Supports
hold, single, double and triple click, on/off, type, rssi
Firmware build date
2019-06-21
Firmware version
2019-06-21
Vendor
Custom devices (DiY)
Model
ptvo.switch
0x00124b001fb3df83
Endpoint 1
Output clusters
genBasic
haDiagnostic
genOnOff
Input clusters
genBasic
haDiagnostic
genOnOff
Endpoint 2
Output clusters
genOnOff
Input clusters
genOnOff
genMultistateInput
Endpoint 3
Output clusters
genOnOff
Input clusters
genOnOff
genMultistateInput
Endpoint 4
Output clusters
genOnOff
Input clusters
genOnOff
genMultistateInput
Endpoint 5
Output clusters
genOnOff
Input clusters
genOnOff
genMultistateInput
Endpoint 6
Input clusters
genAnalogInput
Endpoint 7
Output clusters
genOnOff
Input clusters
genOnOff
genMultistateInput
Endpoint 8
Output clusters
genOnOff
Input clusters
genOnOff

**Comment by SwoopX** [comment]
Eventually, the attribute reporting is missing/not working. What happens, if you follow https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-bind-server-clusters for on/off cluster and this https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-configure-attribute-reporting for attribute 0x0000 of the on/off cluster?

**Comment by moshiko2312** [comment]
Hey
I really no longer know what to do, I have tried everything I know
I tried to perform the actions according to the pictures you attached in the link, but without success
* I would love it if someone could connect to my computer and show me exactly what I need to do.
I really want this product to be set up perfectly with the system.
Thanks for all the help
![dec1](https://user-images.githubusercontent.com/48163773/96028025-7572b380-0e61-11eb-99ef-5592af4ac8dc.png)
![dec2](https://user-images.githubusercontent.com/48163773/96028034-76a3e080-0e61-11eb-8aed-06ead1c1122c.png)
![dec3](https://user-images.githubusercontent.com/48163773/96028037-773c7700-0e61-11eb-96de-73109ed20d34.png)
![dec4](https://user-images.githubusercontent.com/48163773/96028047-79063a80-0e61-11eb-8e1c-3a61fa71a1a9.png)

**Comment by SwoopX** [comment]
It is called bind dropbox, because you can drag&drop the clusters/endpoints.

As for your last screenshot, why are you taking a different cluster than I asked for? The on/off cluster is important here and attribute 0x000.

**Comment by kachalex** [comment]
Reading config file
![onoff](https://user-images.githubusercontent.com/42259721/96217310-ff6a6b80-0f8a-11eb-9d9c-8c8bc420a56e.png)

**Comment by ICTSMART** [comment]
Hello all, I thought this issue was related to my specific setup, nevertheless I have exactly the same findings.
I am running the following releases / firmware:

RaspBee II
Version 2.05.81 / 9/14/2020
Firmware 26610700
DeDONZ is running as a container on Hassio

When I toggle attribute '006 On/Off' attribute in deCONZ VNC the corresponding port on the device responds  correctly. Unfortunately there is no feedback to Phoscon at all.
Only after reading the attributes in VNC, Phoscon updates its status.

Please let me know what other info you require.

Rgds.

**Comment by SwoopX** [comment]
@kachalex Have you previsouly successfully done the binding? In your last screenshot, was that the server on/off cluster (in blue letters)?

**Comment by kachalex** [comment]
I have not done a binding before. I do not know how to do this.

P.S
In your last screenshot, was that the server on/off cluster (in blue letters)? - Yes.

**Comment by SwoopX** [comment]
If you are not able to drag&drop the server on/off cluster of the device on the left and the Endpoint 1 of the coordinator on the right then I cannot help you.

**Comment by kachalex** [comment]
Can you help me how to do this?

**Comment by SwoopX** [comment]
I did [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3324#issuecomment-703307230) and [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3324#issuecomment-710814755).

**Comment by ICTSMART** [comment]
Hello SwoopX, 

I've read the instructions on how to do the manually binding and did so for this firmware (PTVO). So in my case I used (probably) the same firmware (configured 1 input and 1 output via the PTVO tool). The Output is visible as cluster 0006 On/Off. So sending an off or on command does update the status of the device, what seems missing is what you mentioned above: "...Eventually, the attribute reporting is missing/not working". Therefore I've enabled all debug options in deCONZ (running as add-on in Hassio), hoping this provides further information for you guys to dive in. Please let me know how I can assist further.
I saw Mimiix is also waiting for further info - so let me know what makes debugging easier for you.

[logging_raspbeeII_PTVO.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5506773/logging_raspbeeII_PTVO.txt)
![manual_binding_capture](https://user-images.githubusercontent.com/47152369/98471182-d97f6200-21ea-11eb-933d-d5248ab1b4c0.PNG)

**Comment by SwoopX** [comment]
The binding looks alright, but you also need to configure attribute reporting for 0x0000 of the on/off cluster

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-configure-attribute-reporting

**Comment by ICTSMART** [comment]
Hello, I probably missed that before. New attempt with all logging enabled and report interval set as depicted in attachment.
Maybe good to know that the firmware tool used here, allows you to set 8 inputs and 8 outputs. In this case I've just defined 1 input and 1 output and 'linked' them via 'Link to out 1'. Without 'linking' them in the tool, the node shows up with both a '0006 On/Off' cluster and a '0012 Multistate input (basic) (2nd picture).
![ptvo_configuration_set_unlinked](https://user-images.githubusercontent.com/47152369/98542194-d50d8480-2290-11eb-9e20-4cd81b6fa54c.PNG)
![attribute_editor_set](https://user-images.githubusercontent.com/47152369/98541994-895adb00-2290-11eb-9495-5a6f29e131d6.PNG)
![ptvo_configuration_set](https://user-images.githubusercontent.com/47152369/98542033-95df3380-2290-11eb-8faa-9da8de0ff705.PNG)
[logging_attribute_report.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5510499/logging_attribute_report.txt)

**Comment by ICTSMART** [comment]
Now when reflashing with the 'unlinked' output 1 and input 1, I still can set the attributes on 0006 On/Off. When I try to do the same for the 0012 Multistate inout (Basic) and try to modify the attribute 0x0055 "present value" of which I suspect should be reflecting the status of the input, I get a UNSUPPORTED_ATTRIBUTE back from deCONZ. Same happens for instance for attribute 0x006F. See pictures below. Nevertheless I've created a log when generating an input signal from towards the coordinator. 
![manual_binding_capture_unlinked_setting_attribute_0x0055](https://user-images.githubusercontent.com/47152369/98544058-b5c42680-2293-11eb-89d1-11a6d1e549cd.PNG)
![manual_binding_capture_unlinked_setting_attribute_0x006F](https://user-images.githubusercontent.com/47152369/98544069-b8bf1700-2293-11eb-8116-c7968358ffdc.PNG)

Report corresponding to 'unlinked' and a triggerend 'on/off'command' initiated on the device itself: 
[logging_attribute_report_unlinked.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5510641/logging_attribute_report_unlinked.txt)

**Comment by ICTSMART** [comment]
According to its documentation, the firmware should report the state of an independent button via the “ZCL_CLUSTER_ID_GEN_MULTISTATE_INPUT_BASIC” cluster and the “PRESENT_VALUE” attribute:
1 – single click.
2 – double click.
3 – triple-click.
4 – long click.

**Comment by SwoopX** [comment]
Ok, I guess we're getting closer now. In the 2nd log file, I can see that the device is reporting for cluster 0x0006 and 0x0012, so that's good.

For the on/off events, are those now reflected in Phoscon (or in the REST API) as well?
The multi state input basic reports are currently not taken into account, this will probably require some code changes.

Has the debug log taken with `dbg-info=2`? I'd expected to see some more information regarding the attribute reporting, the exact payload to be precise. I'd generally recommend to collect like 10mins of log data, play around with the device and share the full log, as there's more usefull data dwelling in the depths.

Ideally, you'd also be able to compile a test version of the REST API plugin, given you do not run any HA or docker.

**Comment by ICTSMART** [comment]
Ok. Let me change the dbg-info to 2 and I will play around with the device in order to collect a full log.
As I am running the official deCONZ docker add-on for Home Assistion, I guess I am limited for what I can do there.
I'll be back shortly with better logging.

**Comment by ICTSMART** [comment]
Please find attached an assembly of multiple log snippets. As I am not aware of a complete logfile in the deCONZ container, I tried to copy/paste relevant information here. I adjusted the debugging level to 2.
[logging_snippets_DBG_lvl2.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5512751/logging_snippets_DBG_lvl2.txt)

**Comment by sdhawade** [comment]
Hi I am also facing the same problem, the data appears to reach co-ordinator, I can see the on and off status as 1001 and 1000 respectively in the payload, but no status change in Phoscon. Added log below
-- Light On --
20:29:04:800 Node data 0x00124b001fc64555 profileId: 0x0104, clusterId: 0x0006
20:29:04:801 0x00124B001FC64555: update ZCL value 0x04/0x0006/0x0000 after 0 s
20:29:04:801 ZCL attribute report 0x00124B001FC64555 for cluster: 0x0006, ep: 0x04, frame control: 0x00, mfcode: 0x0000
20:29:04:801    payload: 00001001

--Light Off--
20:34:44:803 Node data 0x00124b001fc64555 profileId: 0x0104, clusterId: 0x0006
20:34:44:803 0x00124B001FC64555: update ZCL value 0x04/0x0006/0x0000 after 0 s
20:34:44:804 ZCL attribute report 0x00124B001FC64555 for cluster: 0x0006, ep: 0x04, frame control: 0x00, mfcode: 0x0000
20:34:44:804    payload: 00001000

**Comment by ICTSMART** [comment]
Not sure whether this topic should be closed yet, as there's quite some interest in having PTVO support in Deconz.
@SwoopX any suggestions on how to continue?

**Comment by sdhawade** [comment]
I had a brief look at the code, looks like there would be multiple changes required to add this to the list of supported devices.  Can anyone point me to raise a request to add support ?

**Comment by ICTSMART** [comment]
@SwoopX , @Mimiix What can I do to provide you guys with further info or testing? Please let me know how I can contribute in getting the PTVO firmware supported.

**Comment by SwoopX** [comment]
Well, I pretty much did what I could from here. What else do you expect or what is not working respectively? As I recall, this was initially about the state changes in deconz.

The challenge with this device is, that it seems to be highly configurable and I do not have any clue what you need to do to "have it working as expected". To have the ultimate insight, somebody from the devs willing to have this covered would probably need to have the device in hands and do some traffic sniffing.

**Comment by ICTSMART** [comment]
@SwoopX You are absolutely right, this software is indeed highly configurable. Nevertheless from what I have read - and based on my own experience is that 'inputs' from this device are not reflected in Deconz. Just that would be a major step forward as we can have the actual status fed back towards Deconz. Who from the devs would you suggest I contact? As I am using these devices for quite some time now, especially in combination with the Raspbee I and Raspbee II, my wild guess is that I should be able to provide the necessary sniffing input. Are you aware of the fact that this device is fully supported in Zigbee2Mqtt? I could imagine some info is reusable to make this also work for Deconz (all be it with limited functionality).

**Comment by wvuyk** [comment]
Her I have an user with the 4 relais version of the device. What I am seeing here is that the webhook keeps sending a second event each time an "on":true command has been send: 

```
11:27:34.7002860 -- (WebCommander.HandleWebQueue) Dequeue command: json {"e":"changed","id":"31","r":"lights","state":{"alert":null,"on":true,"reachable":true},"t":"event","uniqueid":"00:12:4b:00:22:02:80:97-03"} new queue size is 0 on 00212EFFFF05ED63
11:27:34.7537991 -- (WebCommander.HandleWebQueue) Dequeue command: json {"e":"changed","id":"31","r":"lights","state":{"alert":null,"on":false,"reachable":true},"t":"event","uniqueid":"00:12:4b:00:22:02:80:97-03"} new queue size is 0 on 00212EFFFF05ED63

```

Any idea why does this happen?

**Comment by OskarL83** [comment]
Hi,
I also have one of these PTVO relay units. 
I'm using it in Home Assistant with Conbee II as coordinator - but not with deCONZ/Phoscon in between. I'm using the ZHA integration instead, which is using zigpy-deconz library to communicate with the Conbee.
With this setup it's working a bit better than with deCONZ/Phoscon. The state of the relay outputs are mostly reported correctly, but sometimes the state changes to off in HA after some minutes, even if the switch is on and has not changed. Don't know why.

**Comment by OskarL83** [comment]
Any progress on this?

**Comment by mamrai1** [comment]
It would be great if deconz supported also the analog inputs like device temperature and source voltage.. I use 2 of them as routers with backup battery power and they are working great
![Screenshot_20210306_181902_com realvnc viewer android](https://user-images.githubusercontent.com/57288344/110213424-9f785100-7ea8-11eb-8366-afbf283231bc.jpg)
![Screenshot_20210306_181911_com realvnc viewer android](https://user-images.githubusercontent.com/57288344/110213427-a1421480-7ea8-11eb-84ed-6e8b9dec8835.jpg)

**Comment by mamrai1** [comment]
i have just found this issue -  General ZBMini issue. #4016 - It seems that the problem was similar with the on/of cluster and attribute 0x0000!!

**Comment by rafaeledi** [comment]
hello, I have a 4 relays device, but unfortunately it does not report the status of the relay (deconz 6.9.0.). has someone already solved the problem without going to the competition. I've tried everything but still no solution.
