### ISSUE TITLE
Phoscon group ends up as RGBWWZ

### ISSUE THREAD

**Issue by Plantje1978** [dresden-elektronik/deconz-rest-plugin#3331]
## Describe the question or issue you are having
I see IKEA Trädfri lights being correctly added to Phoscon. I can add them to a group there as well and dim the individual lights or the whole group. These are normal dimmable Trädfri lights, so no RGB nor WW.
If I then lookup these devices in Domoticz the group is interpreted as RGBWWZ group.

## Screenshots
![image](https://user-images.githubusercontent.com/50333711/94418545-d459dc80-0181-11eb-885a-b70e189ca7ac.png)
![image](https://user-images.githubusercontent.com/50333711/94418651-f6535f00-0181-11eb-9a53-a8efe2694aef.png)

## Environment
Version 2.05.77 / 22-5-2020
Firmware 26350500

 - Host system: Windows 10 PC
 - Running method: Windows (non virtual)
 - Firmware version: 26350500
 - deCONZ version:  2.05.77
 - Device: ConBee I
 - Do you use an USB extension cable: yes -- only relevant for ConBee I/II

**Comment by Smanar** [comment]
Wrong github ^^
It s not deconz dependant but from domoticz, better use https://github.com/Smanar/Domoticz-deCONZ

I have answered too on domoticz forum.

**Comment by Plantje1978** [comment]
Ah, I see, my bad. Sorry. Since you already responded on the Domoticz forum, there is no need to create a topic on your Github site

**Comment by Mimiix** [comment]
So this can be closed 👍
