### ISSUE TITLE
Renaming of lights, sensors and devices requires restart for the restapi to take the changes

### ISSUE THREAD

**Issue by tubalainen** [dresden-elektronik/deconz-rest-plugin#3332]
## Describe the bug

After joining a device (light, sensors and switches) to the network the device gets a auto generated name based on the product and then a number to follow. This causes all up stream systems to register this name as the device name and that entity will automatically be added.
If a device is renamed after adding the new name does not trigger a change in the restapi - a restart of deconz is needed + possibly cleanup of the autogenerated entity in the up stream system (in my case Home Assistant).

## Steps to reproduce the behavior

Just add a device, any device :)

## Expected behavior

1.)
My suggested and preferred solution - As part of the wizard in Phoscon when adding a light/switch/sensor be asked to name it before the new device is being presented to the API, after the naming is done, register the entity (light/switch/sensor) and present it to the API. -- Let naming be a part of the joining wizard.

2.)
Better than nothing solution - present a information box that a restart of deconz would be needed if using "deconz-rest-api".

## Environment

- Host system: Debian 9 under ESXi VM
- Running method: Marthoc Docker container
- Firmware version: (26370500)
- deCONZ version: (.82)
- Device: ConBee I
- Do you use an USB extension cable: no

**Comment by Kane610** [comment]
This PR solves your issue from the Home Assistant side https://github.com/home-assistant/core/pull/40545
