### ISSUE TITLE
After Update Firmware on Raspbee II - no communication

### ISSUE THREAD

**Issue by weider1** [dresden-elektronik/deconz-rest-plugin#3336]
Hello everybody,

after updating the Raspbee II with firmware deCONZ_RaspBeeII_0x26650700.bin.GCF.md5. Every light is accessable and online. But it wont turn on/off any lights / No motion detected via motion detectors etc.

Already rebooted, reinstalled....

after deleting a "old" light and Searching for new lights, the gateway found it and it´s possible to turn on/off...

Edit: the "old" FW version was the 26520700 /  2.05.75 /14.9.2020

**Comment by Smanar** [comment]
So you have solved the problem ?

**Comment by weider1** [comment]
I had to relearn all devices (38)
Manually.

Thought there would be an easier solution, unfortunately not.

**Comment by Smanar** [comment]
You haven't try the hidden config ? https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Network-lost-issues
Or just a backup ?

**Comment by Mimiix** [comment]
Closing this issue. Please use the Issue templates.
