### ISSUE TITLE
Konke Kit Pro Multi-Function Button

### ISSUE THREAD

**Issue by Doreinie** [dresden-elektronik/deconz-rest-plugin#3338]
Hello,
can you add support for this little Konke button.
Here some tech info
https://zigbee.blakadder.com/Konke_KPKEY.html

## Device

- Product name: Konke Kit Pro Multi-Function Button
- Manufacturer: Konke As per deCONZ GUI Basic cluster.
- Model identifier: IC 23777-KPKEY / As per deCONZ GUI Basic cluster.
- Device type :  Switch

Sorry, I´m not that techy and will need more instructions how to get the data you need so that I can get this little wonder working.
Thank you

**Comment by Mimiix** [comment]
Closed as template is not followed.
