### ISSUE TITLE
Conbee 2 crashing and switching ttyACM's

### ISSUE THREAD

**Issue by Goldwing1973** [dresden-elektronik/deconz-rest-plugin#3340]
About 6 months ago i decided to buy a Conbee 2 to replace my 2 Philips Hue 2.0 bridges because i wanted 1 device to control all my lights (one mesh network)
After moving about 60-65 devices the first Conbee 2 started to act strange in Home Assistant (using the Deconz intigration), stopping without reason and switching (mostly during the night when all the lights were turned off) from ttyACM1 to ttyACM2 (ttyACM0 is my Aeotec z-wave stick) wich resulted in no lights in the morning, i had to change the Deconz configuration according to the new ttyACM for it to work again and one or two days later it switched back again to ttyACM1 (after a full reboot it allways was on ttyACM1).
At first i thought it was a problem with my Home Assistant installation, so i did a couple of fresh installs in different setups each time moving the backup of the config to the new installation (tried fresh install on NUC directly, on a NUC as VM with ESXI using hassio, on a NUC as VM with ESXI using Debian 10 with supervised install and last on a Raspberry Pi4 4GB), all shown the same problems
Then -because i sold my Philips Hue bridges- i bought a second Conbee 2 stick, started over with a completely fresh Home Assistant installation (no backup) and started to rebuild the rooms and the automations one by one to the new Conbee 2 stick, completely rebuilding the system from scratch.
But now, after moving and adding 70 devices the new Conbee 2 stick shows the same problem, this morning it hopped from ttyACM0 to ttyACM2 (on the new setup i have a Aeotec z-wave stick on ttyACM1)
So, the problem looks like a Conbee 2 device limit.

My Zigbee setup
8x OSRAM GU10
21x Philips Hue GU10
9x Philips Hue E27 (4x 1st gen)
8x Philips Hue E14
2x Philips Hue Lightstrip (1st gen)
2x LXT56-LS27LX1.7 (Gelopto lightstip controller)
4x TS0121 (Blitzwolf plug)
1x Osram Adapter Plug
1x Philips Hue Outdoor Floodlight
2x Philips Hue Livingcolors (1x first gen)
5x Philips Hue Motion sensor
3x Aquara Motion sensor
4x Muller light Tint (Smart switch)

Version : 2.05.81 / 14-9-2020
Firmware : 26580700

The Blitzwolf plugs and Aquara motion sensors are new and where not used in my first setup.
The next time the Conbee 2 "hops" i try to capture the logs from Home Assistant and add them here.

How can i pass the 60+ devices without making the Conbee 2 unstable?

**Comment by Mimiix** [comment]
Hi @Goldwing1973,


You are not using the template and information is missing.

Closing the issue. Feel free to open a new one with correct template.
