### ISSUE TITLE
ConBee II not joining network, error 0xE8

### ISSUE THREAD

**Issue by Arquiteto** [dresden-elektronik/deconz-rest-plugin#3345]
## Describe the bug
ConBee II unable to join the network. 
I had some issues with ConBee on my QNAP NAS, that presented as ConBee changing USB device number in the system. After QNAP reboot it was assigned Bus 01 Device 04, and could go up to Device 100+ after few days. Each change caused it to be disconnected from virtual machine and I had to add it to VM manually again. Not sure if this is associated with my current problem, but it caused me to move my deCONZ to Docker container.

After setup of Marthoc deCONZ container I restored backup made on HA. It worked, but all the devices were offline and I couldn't add any new. I decided to upgrade firmware to latest, made it via docker script provided by marthoc. It wouldn't resolve the issue. I tried a fresh install without restoring backup but Phoscon app was now always saying "Firmware: not connected", deCONZ showed Conbee II connected as /dev/ttyACM0 but "Not in network". I tried to change USB port in QNAP, connect extension cable. Then I tried fresh install in Home Assistant again and finally in Windows - on every install issue seems the same.

As a last resort I downgraded firmware to 26580700 again - no change.

To sum up:
- ConBee II seems to be connected to the machine, discovered as USB device and I am at least able to upgrade/downgrade firmware
- doesn't matter if it's fresh install or back-up
- it's probably not a host problem as it doesn't work on QNAP TS-453Be and PC running Windows
- problem is the same regardless of running method
- 2 different firmware versions produce the same results
- logs show multiple connection tries ending with message "NET ZDO start network status 0xE8"

## Screenshots
![image](https://user-images.githubusercontent.com/33292677/94905626-78eb5f80-049d-11eb-9579-22b5a6cf4281.png)
![image](https://user-images.githubusercontent.com/33292677/94905598-6ec96100-049d-11eb-87bd-c4cfe5425da8.png)

## Environment

 - Host system: QNAP NAS and Windows
 - Running method: HA deCONZ Add-on in HassOS QNAP VM, Marthoc Docker container on QNAP, Windows 10
 - Firmware version: 26580700 and 26650700
 - deCONZ version: 2.05.81 on Windows, 2.05.83 on Marthoc Docker and 2.05.81 HA Add-on
 - Device: ConBee II
 - Do you use an USB extension cable: tried both

### deCONZ Logs
10:50:34:774 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF
10:50:34:775 GW firmware version: 0x26580700
10:50:34:775 GW firmware version is up to date: 0x26580700
10:50:41:690 start reconnect to network
10:50:46:690 try to reconnect to network try=1
10:50:46:700 Device protocol version: 0x010B
10:50:46:769 Current channel 25
10:50:46:792 CTRL ANT_CTRL 0x03
10:50:47:214 Device protocol version: 0x010B
10:50:47:282 Current channel 25
10:50:47:303 CTRL ANT_CTRL 0x03
10:50:47:344 NET ZDO start network status 0xE8
10:50:51:689 try to reconnect to network try=2
... (goes until try=10 and starts again)

More log from restart of HA Add-on: https://pastebin.com/ecrbayJY

**Comment by Smanar** [comment]
Make your try on windows as you have one.
Make a firwmare update on windows (the one you prefer) with the command "-t 60" > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

If you still have the "firwmare not connected" can you compare your deconz setting with this one > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Network-lost-and-configuration-restore-does-not-help

**Comment by Arquiteto** [comment]
@Smanar 
I tried on Windows, tried on Docker, tried on Raspbian - also with "-t 60". The firmware updates, verifies and says SUCCESS.

But my settings are different
![image](https://user-images.githubusercontent.com/33292677/94940598-fdf16b80-04d3-11eb-990d-ffdc25e0af6a.png)

When I try to change them they change back before I am able to write even one field and click save

**Comment by SwoopX** [comment]
You need to leave the network before. Check the wiki, there's a larger article.

**Comment by Arquiteto** [comment]
@SwoopX 
Problem is I can't leave it, because ConBee II fails to join the network and the button is always greyed-out. Is there any way I can stop it from trying to join so I can edit?

**Comment by Smanar** [comment]
Perhaps same problem than him https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3154

**Comment by Arquiteto** [comment]
@Smanar

Yes, that was it! After setting custom MAC address it connected to the network!
Thank you very very much.  I was about to declare my ConBee dead.

**Comment by vjonas** [comment]
> @Smanar
> 
> Yes, that was it! After setting custom MAC address it connected to the network! Thank you very very much. I was about to declare my ConBee dead.
> 
> No idea why I didn't find it, I looked over other issues before commiting this one. Must have overlooked it.

How did you set a custom mac address to it?

**Comment by Mimiix** [comment]
> > @Smanar
> > Yes, that was it! After setting custom MAC address it connected to the network! Thank you very very much. I was about to declare my ConBee dead.
> > No idea why I didn't find it, I looked over other issues before commiting this one. Must have overlooked it.
> 
> How did you set a custom mac address to it?

This is something best asked on the forums instead of in an near 3 year old issue.

Locking this up.
