### ISSUE TITLE
Add support for Xiaomi wall switch QBKG03LM

### ISSUE THREAD

**Issue by simonporter007** [dresden-elektronik/deconz-rest-plugin#335]
Creating this as separate issue for better housekeeping.

Requesting to add support for the xiaomi ZigBee wired wall switch - 2 gang.

![](https://i.imgur.com/iRwadVv.png)
![](https://i.imgur.com/2CRrvTM.png)
![](https://i.imgur.com/CXSwXfU.png)

Support was added for the rest plugin in [eb06ca0](https://github.com/dresden-elektronik/deconz-rest-plugin/commit/eb06ca03d9a6a9e6418d5b36a7b737ed309a0d06) but it has a minor typo, missing the "t" in neutral.

Willing to help provide any other info of possible.

**Comment by manup** [comment]
Close this since discussion is continued in  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/356
