### ISSUE TITLE
Sylvania S+ 73693 missing tunable white settings. 

### ISSUE THREAD

**Issue by N5A** [dresden-elektronik/deconz-rest-plugin#3352]
I have two I've added through Phoscon, each only has a RGB color slider , clicking the Color Temperature selector below the color slider has no effect, they remain in RGB mode. I have them connected to a ConbeeII running on a Pi4. Deconz installed a few days ago. running on ver 2.05.81 

Consequently Home Assistant also only gives me RGB control. 

What can I provide to assist in determining the issue I'm facing?

**Comment by SwoopX** [comment]
Closing this for not using the template.

**Comment by N5A** [comment]
I do not know how to gain the info to follow the template.
