### ISSUE TITLE
Xiaomi buttons not visible in Phoscon

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#336]
I have a Xiaomi Smart button and an Aqara Smart button - both added to deconz. Their events are visible in the websocket api and in the REST API.

In the Phoscon App, however, the buttons are neither listed under switches nor under sensors.

**Comment by ebaauw** [comment]
Same here for the Xiaomi Aqara Smart button.  And for the Cube.  The Xiaomi Aqara door sensor and weather sensors do show.

The IKEA Trådfri dimmer shows, but no icon.

**Comment by ldplusse** [comment]
_The IKEA Trådfri dimmer shows, but no icon._
Is that the rund dimmer that you can only rotate?

**Comment by ebaauw** [comment]
Yep.

**Comment by Try2Fly** [comment]
I'm also unable to connect the Xiaomi Smart Home Wireless Switch (round) with Deconz Rest plugin. With the Phoscon App it does connect but not show up. When trying through the Wireless Light Web App I get not connection at all. Is there a fix for this?

**Comment by ErnstEeldert** [comment]
Same here for the Xiaomi cube. It shows up in the REST API like this:

`    "11": {
        "config": {
            "on": true,
            "reachable": true
        },
        "ep": 2,
        "etag": "daade30ae2d367f3848e487902830fd7",
        "manufacturername": "LUMI",
        "mode": 1,
        "modelid": "lumi.sensor_cube",
        "name": "lumi.sensor_cube 11",
        "state": {
            "buttonevent": 4000,
            "lastupdated": "2018-02-03T11:57:38"
        },
        "type": "ZHASwitch",
        "uniqueid": "00:15:8d:00:01:14:82:de-02-0012"
    },
    "12": {
        "config": {
            "on": true,
            "reachable": true
        },
        "ep": 3,
        "etag": "fcb0cdd7c52306b0a788f5abbc0aa599",
        "manufacturername": "LUMI",
        "mode": 1,
        "modelid": "lumi.sensor_cube",
        "name": "lumi.sensor_cube 12",
        "state": {
            "buttonevent": 3065,
            "lastupdated": "2018-02-03T11:45:05"
        },
        "type": "ZHASwitch",
        "uniqueid": "00:15:8d:00:01:14:82:de-03-000c"
    }
}`

But nothing in the classic nor the new web app. Also, it doesn't show up in Home Assistant, but that maybe a different issue?

**Comment by manup** [comment]
The Xiaomi button and cube are currently not visible in the Phoscon App, they can only be configured via REST API and other projects which use the REST API. Work that matter has started already in form of a generic switch configuration editor where various actions can be assigned to physical buttons or gestures (as the cube has). I have no ETA yet but the feature has a high priority for us.

**Comment by etique57** [comment]
hi @manup 

any news on the generic button configurator?
Would existing bindings appear? or would they have to be created anew?

**Comment by Oliviakrkk** [comment]
Hi

Any news on that? 

I added Xiaomi button, it is visible in Windows GUI but not in the phoscon. I connected Home Assistant, and was under impression that it uses the REST api, so the button should be visible there.. But it is missing :/.

**Comment by willsy555** [comment]
> Hi
> 
> Any news on that?
> 
> I added Xiaomi button, it is visible in Windows GUI but not in the phoscon. I connected Home Assistant, and was under impression that it uses the REST api, so the button should be visible there.. But it is missing :/.

Just got mine. Same problem. Shows up in Deconz on the server, but not in the Phoscon app! Nothing in hassio... dammit! :-(
Cheers
Will.

**Comment by manup** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_50

The square buttons are now supported, round one still on the todo list.
