### ISSUE TITLE
Sylvania S+ 73693 missing tunable white settings

### ISSUE THREAD

**Issue by N5A** [dresden-elektronik/deconz-rest-plugin#3365]
## Describe the bug
I have two (Sylv S+ 739693) I've added through Phoscon, each only has a RGB color slider , clicking the Color Temperature selector below the color slider has no effect, they remain in RGB mode. Consequently Home Assistant also only gives me RGB control. Neither having it suggests an issue within Deconz.

## Steps to reproduce the behavior
Add them to Deconz.

## Expected behavior
Full Color and Temp Control to be present.

## Environment
OS: I have them connected to a ConbeeII running on a Pi4 running Raspian(buster).
Deconz Ver :Deconz installed a few days ago. running on ver 2.05.81
USB Ext.. Yes.

## Additional Context
only those two bulbs and a smart outlet on zigbee currently. 
Distance to bulbs from Conbee... roughly. 20-30ft.

What can I provide to assist in determining the issue I'm facing?

by template I don't see whats missing... (Mimiix pointed it out.. lack of headers)

**Comment by Mimiix** [comment]
Is is missing

**Comment by N5A** [comment]
Fixed.

**Comment by N5A** [comment]
May assist.. 
![DeconzClusters](https://user-images.githubusercontent.com/44683831/95114774-72b1e900-0712-11eb-81fd-27d837d50b2a.PNG)
![DeconzNode](https://user-images.githubusercontent.com/44683831/95114777-734a7f80-0712-11eb-8c7d-d4ca6e6f10f6.PNG)
![DeconBasic](https://user-images.githubusercontent.com/44683831/95114779-73e31600-0712-11eb-83ab-09afabf4f4f1.PNG)

**Comment by crazifyngers** [comment]
I am having a similar issue with four sylvania (osram/ledvance) smart+ rt5/6 rgbww downlights.  I moved from 2.05.79, where all channels worked to 2.0.5.84, where the CT channel is no longer working in phoscon and do not reflect changes in the api.  I am however able to change the CT value if I use the 2016 wireless light control interface.  This is how I am able to tell if the API is seeing any state changes.

**Comment by guedeaux** [comment]
I too am having this issue on 2.05.84 with ledvance A19 RGBW.

**Comment by N5A** [comment]
To note this did work on some version installed to my Home Assistant VM a year ago, however i've since moved Deconz to a centrally located Pi and off the Windows PC/HA VM due to unstable ConbeeII connection.

**Comment by guedeaux** [comment]
Yes. These lights were working fine before, but now they have lost the color tuning and white level attributes in Phoscon. I am not sure when it occured, but I am on 2.05.84 now and they aren't working properly.

**Comment by N5A** [comment]
*PUNT* Because the bot emailed me an order to do so.

**Comment by guedeaux** [comment]
I have been hoping that this issue would resolve itself somehow, during a HA restart, host reboot, HA update, etc., but it is still present and super annoying through . I might try moving deconz to its own container instead of the HA add-on, not that doing this will help to resolve the underlying issue, though...

**Comment by EricPalmquist** [comment]
I am having the same problems with the same lights.  ConBee (original) on Raspbee.  Version 2.05.78 firmware 26350500.

**Comment by N5A** [comment]
Updated firmware to newest from LEDVANCE (2.2019). No immediate change.  THey were on older version I'll delete them from the network and readd them during the weekend.

**Comment by guedeaux** [comment]
I deleted one, rebooted, re-added, rebooted... still no tunable white options

**Comment by jasonsinclair5** [comment]
Anyone have any luck with this? I have a couple LEDVANCE BR30 RGBW bulbs that will not use color temp. The only white available is a bright white. I have just upgraded to 2.6.0 and firmware 26660700 on my Conbee II stick. I removed the light and re-added, still no luck. I just did an OTA upgrade to 00102428 on the bulbs, but still no luck with the color temp. I'm running deconz in a docker container, if that helps.

**Comment by EricPalmquist** [comment]
I was able to hack the source code to get it to work for the RB30 RGBW and A19 RGBW.   I can share the source code changes if anyone would like.

**Comment by Mimiix** [comment]
@EricPalmquist Feel free to make a PR from it! We might be able to integrate it then.

**Comment by jasonsinclair5** [comment]
> I was able to hack the source code to get it to work for the RB30 RGBW and A19 RGBW. I can share the source code changes if anyone would like.

That would be awesome, but I'm running on docker, so I'm not sure I could re-compile the source.

**Comment by EricPalmquist** [comment]
@Mimiix I think that I created a PR with my changes - this is my first one ever so not 100% that I did it correctly :)

**Comment by N5A** [comment]
> I was able to hack the source code to get it to work for the RB30 RGBW and A19 RGBW. I can share the source code changes if anyone would like.

This is what Github and open source are for a million brains working on many problems. Anyone can pop in with the workable solution! I'd love to get the functions back! You rock!

**Comment by Mimiix** [comment]
@EricPalmquist Looks good! I've changed the title ;)

**Comment by N5A** [comment]
Thank you for the fix! Everything sees the color temp controls now.

**Comment by Thomas-Vos** [comment]
Any reason this was set to `Color temperature light` in the PR instead of `Extended color light`? Color temperature light means no RGB support so that is wrong.

**Comment by N5A** [comment]
Couldn't tell ya on that. Didn't have a hand in programming.
