### ISSUE TITLE
Smart things Multipurpose sensor - incorrect temp being shown

### ISSUE THREAD

**Issue by JamieP83** [dresden-elektronik/deconz-rest-plugin#3367]
reopened as i didnt reply quickly here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3190
i did integrate this: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2769

current firmware is v14

## Describe the bug
My samsung smartthings multi purpose sensor, keeps reporting a -46 temperature. its also not showing a battery level?
i have deleted the device and readded.
i have reset the device and readded
no change

## Steps to reproduce the behavior
just added the sensor and it keeps showing the incorrect temp.
i have 10+ other devices, all of those are ok

## Expected behavior
correct temp

## Screenshots
![image](https://user-images.githubusercontent.com/48566948/91081058-6d0ab300-e63e-11ea-8f01-d4dfd4622f4b.png)

![image](https://user-images.githubusercontent.com/48566948/91081143-8f9ccc00-e63e-11ea-9650-6d6034903907.png)

## Environment

 - Host system: Raspberry Pi4 
 - Running method:Home Assistent deCONZ Add-on /
 - Firmware version: 26580700
 - deCONZ version: 2.0.5.79 / 5/22/2020
 - Device:  ConBee II 
 - Do you use an USB extension cable: yes 

![image](https://user-images.githubusercontent.com/48566948/91081255-bc50e380-e63e-11ea-9881-168cea54e36c.png)

## Additional context

```
"113": {
        "config": {
            "battery": null,
            "on": true,
            "pending": [],
            "reachable": true
        },
        "ep": 1,
        "etag": "e1e3b40ffe6763f507e7dd9f86e2926e",
        "lastseen": "2020-08-24T18:20:45.404",
        "manufacturername": "Samjin",
        "modelid": "multi",
        "name": "Dining Room Door ST DZ",
        "state": {
            "lastupdated": "2020-08-24T18:20:45.404",
            "open": false
        },
        "type": "ZHAOpenClose",
        "uniqueid": "28:6d:97:00:01:04:86:73-01-0500"
    },
    "114": {
        "config": {
            "battery": null,
            "offset": 0,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "88168900322514808e1234182225a057",
        "lastseen": "2020-08-24T18:20:45.400",
        "manufacturername": "Samjin",
        "modelid": "multi",
        "name": "Dining Room Door ST DZ",
        "state": {
            "lastupdated": "2020-08-24T18:20:32.470",
            "temperature": -4685
        },
        "type": "ZHATemperature",
        "uniqueid": "28:6d:97:00:01:04:86:73-01-0402"
    },
    "115": {
        "config": {
            "battery": null,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "72cdf4bbf1789c8a9a0855dfaea8554d",
        "lastseen": "2020-08-24T18:20:45.400",
        "manufacturername": "Samjin",
        "modelid": "multi",
        "name": "Dining Room Door ST DZ",
        "state": {
            "lastupdated": "none",
            "orientation": [
                0,
                0,
                0
            ],
            "vibration": false
        },
        "type": "ZHAVibration",
        "uniqueid": "28:6d:97:00:01:04:86:73-01-fc02"
```

**Comment by Mimiix** [comment]
Closing this, Re-opening #3190 

Please, next time, just ask me to re-open.
