### ISSUE TITLE
Tuya TS0218 SOS Button

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#3368]
Yet anther Tuya Device

![image](https://user-images.githubusercontent.com/52735978/95167491-1d99d400-07f3-11eb-879c-0867e5de76de.png)

![image](https://user-images.githubusercontent.com/52735978/95167885-bf212580-07f3-11eb-8d5e-b35bbbfb2147.png)

## Device

- Product name: Tuya Pushbutton
- Manufacturer: _TYZB01_trqoesc6
- Model identifier: TS0218
- Device type : Remote

![image](https://user-images.githubusercontent.com/52735978/95167028-41a8e580-07f2-11eb-91ec-ba4abbb99779.png)

![image](https://user-images.githubusercontent.com/52735978/95167079-57b6a600-07f2-11eb-8b3f-961608846e6d.png)

![image](https://user-images.githubusercontent.com/52735978/95167143-76b53800-07f2-11eb-8bb7-117e7b433ad7.png)

![image](https://user-images.githubusercontent.com/52735978/95167194-8e8cbc00-07f2-11eb-9373-41a06d8488ca.png)

![image](https://user-images.githubusercontent.com/52735978/95167236-a5cba980-07f2-11eb-890e-dcb273a89cc1.png)

![image](https://user-images.githubusercontent.com/52735978/95167300-c4ca3b80-07f2-11eb-9103-8100375cde2a.png)

![image](https://user-images.githubusercontent.com/52735978/95167380-e62b2780-07f2-11eb-9d7c-8d77449a7684.png)

![image](https://user-images.githubusercontent.com/52735978/95167435-022ec900-07f3-11eb-99e8-16c318b5402d.png)

![image](https://user-images.githubusercontent.com/52735978/95167471-14106c00-07f3-11eb-8d64-428c5729452c.png)

https://www.zigbee2mqtt.io/devices/TS0218.html

**Comment by alexanderfitu** [comment]
I am looking for support for this to be added if possible. I can provide any logs if needed.

**Comment by darking2539** [comment]
I have issues with this device. Detail in link: https://github.com/Koenkk/zigbee2mqtt/issues/7184. How to solve it? I see log (debug level) but noting at all show.

**Comment by Mimiix** [comment]
@alexanderfitu Can you perhaps open an new issue ?  Follow this procedure: https://forum.phoscon.de/t/read-me-device-request-read-me/23

**Comment by alexanderfitu** [comment]
> @alexanderfitu Can you perhaps open an new issue ? Follow this procedure: https://forum.phoscon.de/t/read-me-device-request-read-me/23

Will do!
