### ISSUE TITLE
Tuya Gas/Water Valve TS0111 Enhancement Please

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/deconz-rest-plugin#3369]
This device registers in deconz as a light and has only one switch exposed.  There are additional sensors and can we make it something other than a light to reflect what it is?

![image](https://user-images.githubusercontent.com/52735978/95169740-b4b45b00-07f6-11eb-9a6e-951f3844c54d.png)

## Device

- Product name: Tuya Smart Valve
- Manufacturer: _TYZB01_ymcdbl3u
- Model identifier: TS0111
- Device type :  Other: Valve

## Screenshots

![image](https://user-images.githubusercontent.com/52735978/95169940-052bb880-07f7-11eb-8ed2-ada57796e914.png)

![image](https://user-images.githubusercontent.com/52735978/95170015-1f659680-07f7-11eb-86e7-41e9da2261b9.png)

![image](https://user-images.githubusercontent.com/52735978/95170077-3b693800-07f7-11eb-8b15-f0e22b522be1.png)

![image](https://user-images.githubusercontent.com/52735978/95170161-53d95280-07f7-11eb-81ba-80fade3b30a6.png)

![image](https://user-images.githubusercontent.com/52735978/95170224-6d7a9a00-07f7-11eb-8519-a192d0e6a3f0.png)

![image](https://user-images.githubusercontent.com/52735978/95170275-85eab480-07f7-11eb-9017-f45a4611ada9.png)

![image](https://user-images.githubusercontent.com/52735978/95170332-9f8bfc00-07f7-11eb-90b6-4dad80f5d54c.png)

![image](https://user-images.githubusercontent.com/52735978/95170396-b6cae980-07f7-11eb-84f8-2ea611e27cd0.png)

![image](https://user-images.githubusercontent.com/52735978/95170462-d19d5e00-07f7-11eb-9191-0ff0eedf6403.png)

![image](https://user-images.githubusercontent.com/52735978/95170536-f1348680-07f7-11eb-9d5e-a26dbca1e944.png)

![image](https://user-images.githubusercontent.com/52735978/95170581-07dadd80-07f8-11eb-9106-db93845ca723.png)

![image](https://user-images.githubusercontent.com/52735978/95170625-204af800-07f8-11eb-9318-818ddd96648a.png)

**Comment by Smanar** [comment]
Your device is in use when you have take the capture ?

On the lasts capture "Simple metring" and "electrical mesurement" you have 0 in all values, can you use it to see if the value change.

But for me it useless, it s electrical mesurement and your device is used for fluid, so I don't think it will be relevant.

And you are lucky with a "light", for me this device need to be displayed as plug ^^.

**Comment by meremortals70** [comment]
Thanks, 
The device was idle when I grabbed the captures.  I had just added it to the network.

I agree the additional sensors are probably not a great value to most people however I do track all my power usage as I have solar and battery with Iotawatt and currently plugs on all my high energy appliances to monitor and graph usage.

I also have automations which stop appliances like the dishwasher, washing machine and air conditioner being switched on when the solar and battery is low. Annoys the wife but she has an option to override manually but it does give her pause to think before she does it.

**Comment by Smanar** [comment]
lol poor wife, take care at WAF.

**Comment by meremortals70** [comment]
Not at all, need to change behaviour otherwise nothing changes

**Comment by falaca** [comment]
@meremortals70 Aside from it showing up as a light, does this device work as expected with deCONZ?
