### ISSUE TITLE
Update Conbee II firmware running in a proxmox VM

### ISSUE THREAD

**Issue by jordindc** [dresden-elektronik/deconz-rest-plugin#3371]
Hi,

I'm trying to update the firmware of my Conbee II gateway that is running in a VM of a proxmox Server. As per your advice saying that updating firmware in a VM installation is not supported (in fact, my VM hangs any time I try it), I'm wondering the way I can update the firmware of the gateway. If I install the gateway on a Raspberry I have for testing and update it there, will I have any problem with the devices I already have included in the gateway, or any other problem with my running installation?

Running Conbee II in a Intel NUC with proxmox server in a debian buster VM

Thanks in advance

**Comment by Mimiix** [comment]
Hi @jordindc  first off: Please use the issue template next time.

To answer your question: There is nothing stored on the stick. So you can safely just update the stick on the raspberry and then put it back afterwards.
