### ISSUE TITLE
OWON AC201 Thermostat (IR Blaster)

### ISSUE THREAD

**Issue by aryelevin** [dresden-elektronik/deconz-rest-plugin#3374]
## Device

- Product name: OWON AC201 Thermostat AC Control
- Manufacturer: OWON
- Model identifier: AC201
- Device type :  Thermostat

## Screenshots

<img width="318" alt="Screen Shot 2020-10-07 at 1 47 28" src="https://user-images.githubusercontent.com/5435949/95268144-6a0b0100-083f-11eb-91c1-0dd446e0abbf.png">
<img width="490" alt="Screen Shot 2020-10-07 at 1 48 46" src="https://user-images.githubusercontent.com/5435949/95268146-6d05f180-083f-11eb-95c0-039eb1aebb6b.png">
<img width="384" alt="Screen Shot 2020-10-07 at 1 47 54" src="https://user-images.githubusercontent.com/5435949/95268151-6f684b80-083f-11eb-82c0-6dafcf614eaa.png">

This device is a thermostat which controls Air conditioners by emitting IR commands.
It features control on the mode and fan speed.
Using the deconz GUI its working perfectly, but it is not exposed to the REST API.
Also, it seems that the pairing process is unfinished since it not gets a name with the number of the sensor (its ID).

**Comment by Mimiix** [comment]
Missing cluster screenshots.

**Comment by aryelevin** [comment]
Which cluster is missing?
Attached the thermostat and fan control clusters:

<img width="575" alt="Screen Shot 2020-10-07 at 11 38 38" src="https://user-images.githubusercontent.com/5435949/95307720-aff0b500-0891-11eb-8fa1-ff05c836e3d3.png">
<img width="575" alt="Screen Shot 2020-10-07 at 11 38 20" src="https://user-images.githubusercontent.com/5435949/95307732-b2eba580-0891-11eb-9962-d2ddbe6d7e2a.png">
<img width="575" alt="Screen Shot 2020-10-07 at 11 38 15" src="https://user-images.githubusercontent.com/5435949/95307737-b4b56900-0891-11eb-8831-f6fd0145b18f.png">
<img width="575" alt="Screen Shot 2020-10-07 at 11 38 10" src="https://user-images.githubusercontent.com/5435949/95307739-b54dff80-0891-11eb-982d-f7a6d037cc48.png">
<img width="575" alt="Screen Shot 2020-10-07 at 11 38 02" src="https://user-images.githubusercontent.com/5435949/95307742-b5e69600-0891-11eb-9dd8-a84617088025.png">
<img width="575" alt="Screen Shot 2020-10-07 at 11 37 55" src="https://user-images.githubusercontent.com/5435949/95307743-b67f2c80-0891-11eb-9a28-0d0b54cefad8.png">

**Comment by SwoopX** [comment]
How does the device work, can it heat and cool? Do you (need to) set the occupied cooling setpoint or do you just use the fan control cluster?

**Comment by aryelevin** [comment]
Yes, I can set all three parameters:
Heating/cooling/auto/dry/etc mode (which is actually handled by the AC itself) -> Thermostat cluster
Target temperature (2 settings for cooling and heating each) -> Thermostat cluster
Fan mode (LOW/MED/HIGH/AUTO) -> Fan cluster

**Comment by aryelevin** [comment]
The IR command which sent to the AC is always includes: Mode, Target Temp, Fan Speed.
So, any changes made to any of those values is immediately sends the up to date state to the AC via IR command.

**Comment by SwoopX** [comment]
Ok, thanks. So that means we require 0x0011, 0x0012, 0x001B, 0x001C to be settable from thermostat cluster.

**Comment by aryelevin** [comment]
I think that 1B has nothing to do with IR controlled Acs, but it is definitely good to allow it to be settable fro cases it might needed.
The fan control also needs to be settable in the Fan cluster.

**Comment by SwoopX** [comment]
Right. Have excluded it as that was thermostat cluster related.

**Comment by aryelevin** [comment]
Ah, OK. Didn't noticed it... 
Thank you very much.

**Comment by aryelevin** [comment]
@SwoopX Just checking out if there is any news with it, and if its expected to be available with this upcoming beta at the 15th October?

Thanks

**Comment by SwoopX** [comment]
That's gonna be though, not sure.

**Comment by aryelevin** [comment]
Thanks a lot for the update...
It gives me a hope hahaha...

**Comment by aryelevin** [comment]
@SwoopX  I see its not in this beta.
Do you have any progress on it which I can join? I'm a developer too (C/C++/JS/ObjC/Swift/Java/Go)?
In case not, do you have any guidelines to tell me where to start?

**Comment by aryelevin** [comment]
Great! Thanks a lot!!!
Will give it a try and will report
Have a nice weekend

**Comment by aryelevin** [comment]
@SwoopX OK, so, after testing a bit, the first problem is that the fanmode is not exists on the config object, I counlnt find the issue by myself, so you help is appreciated.
I've fixed small bugs, and continues to do so except this one, which I have no idea how to solve it , and after all solved, I'll create pull request of course.

Thanks a lot

**Comment by aryelevin** [comment]
@SwoopX Also, After the device is added (which I need to manually read the Basic cluster manually by the GUI in order to trigger the finalization of the process), the On mode is always == "on", and the "mode" is always == null and never exits this state (the if statements is avoiding updating a null "mode", so it never gets out of this loop), and I didn't found where the default setup happens.
BTW, not only the fanmode is not available under config, there is no light resource created.

**Comment by SwoopX** [comment]
@aryelevin Thanks for your feedback so far. It's really good to see that you can test the code and have the programming background to iron out the quirks. It's always hard to make some device inclusions remotely and not having the device at hand.

Gotta hund down a segfault first, but will chime in afterwards!

**Comment by aryelevin** [comment]
I'm happy to assist and enjoy it a much.
I'm are simply don't know the structure well so getting lost quickly in the project.

**Comment by aryelevin** [comment]
Hi @SwoopX ,

Here's my progress with getting it to somewhat working and also the fan is now exposed on the lights resources (still not working and needs adaptions to have the right data on it).
https://github.com/aryelevin/deconz-rest-plugin/commit/9afbf2c30c26fd6f69aedccffd3f0dd7ae4f776c

Please take a look and let me know

**Comment by SwoopX** [comment]
@aryelevin  Can you please show me your current output from the REST API for the sensor? Having `NULL` values is kind of ok when the device has just recently been created. However, the current values should drip in after 10-15 mins as the device first needs to configure the attribute reporting and then wait for the reports to come in after the defined timeframes. The code is based on the assumption that reporting is supported for the interesting attributes. If it isn't, that could explain the values not changing and we need to switch over to polling them.

It would give us some further insights if you could manually set up the bindings and reporting for the newly added REST API values as explained [here](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...).

Also, I'm afraid your proposed changes could cause some unexpected behaviour for other devices, which is the reason I haven't taken that route. The idea was to have the fan mode included in the sensor resource and to no add an additional light resource just for that.

> the On mode is always == "on", and the "mode" is always == null and never exits this state (the if statements is avoiding updating a null "mode", so it never gets out of this loop), and I didn't found where the default setup happens.

Could you point me to that one?

**Comment by aryelevin** [comment]
@SwoopX First of all, thank you very much.
Now, Here's the sensor object as received by the REST API:
{
    "config": {
      "coolsetpoint": null,
      "heatsetpoint": null,
      "mode": null,
      "offset": 0,
      "on": true,
      "reachable": true
    },
    "ep": 1,
    "etag": "87e0b281478062b1b22d4aac6976804c",
    "lastseen": "2020-10-18T17:30Z",
    "manufacturername": "OWON",
    "modelid": "AC201",
    "name": "AC201",
    "state": {
      "lastupdated": "none",
      "on": null,
      "temperature": null
    },
    "type": "ZHAThermostat",
    "uniqueid": "00:60:6e:ff:fe:97:bc:a7-01-0201"
  }
The device is much more than 15 minutes on the system.
I will look into you instructions in the link and will report back here.

Now, for the fan, I totally agree with you that it shouldn't add additional light resource, actually, I thought this is what you've trued to achieve, so I tried to replicate this.
I prefer it to work within the sensor object, but for weird reason the "fanmode" is dropped from the config object, do you have any idea why?

As for your last question, I will try to make it clearer here:
There is "on" key on the config object, and it is always = true, why? (I also referred to the issue with the NULL "mode", but leave this aside at the moment, since we have to check out whether its a attributes reporting issue or not).

**Comment by aryelevin** [comment]
@SwoopX OK, I found the issue with the fanmode:
you defined it at a UInt8 value, but when adding It to the node, you specify it as a string, thus it rejected.
I'm going to revert my fan light Resource changes now.

**Comment by SwoopX** [comment]
Thanks for coming back. I suppose an incorrect data type was the issue for `fanmode`. Already added a new commit for that to the PR.

> There is "on" key on the config object, and it is always = true, why? (I also referred to the issue with the NULL "mode", but leave this aside at the moment, since we have to check out whether its a attributes reporting issue or not).

Funny thing is, I asked that myself like 2hrs ago. I don't know for sure. It's either a relic or required for rules/scenes I'd say. Don't care about it too much.

**Comment by aryelevin** [comment]
OK, so now it looks much better, but you have to merge this commit in order to make the "mode" working.
https://github.com/aryelevin/deconz-rest-plugin/commit/49d9c6b48048ee23d2a44957e19e92437443c632

Now will loointo the attributes reporting stuff.

Thanks

**Comment by aryelevin** [comment]
@SwoopX OK, so after manually configuring the bindings for attributes reporting it seems to be working fine. (also configured the intervals etc.)
What does it means for now? issues with the default settings? or what?

**Comment by SwoopX** [comment]
> OK, so now it looks much better, but you have to merge this commit in order to make the "mode" working.

Right, thanks!

> What does it means for now? issues with the default settings? or what?

Good question. So, when we're good fron the functionality perspective, I'd say you should try to reset and pair the device again. Please make sure to include the updated fixes PR into account. Usually, all the bindings and attribute reportings should be set up automagically. Even if missed, it should be retried every 1-2 hrs. Might also be a good idea to take logs from the join process and the time following. Given you use the GUI mode (ensure the services have been stopped before):
`/usr/bin/deCONZ --dbg-error=2 --dbg-info=2 > debug`

If you feel funny, we could also start exploring the unknown cluster. You need an additional plugin to discover the included attributes there, happy to guide you through.

**Comment by aryelevin** [comment]
OK, I will have to check that out. Will do it later today.
As for the unknown cluster, I think I know what is it, its the IR configuration which allows you to configure the AC model you have and the type of the IR remote it uses.
I still want to expose that out, so lets go on on this haha..

**Comment by SwoopX** [comment]
Alrighty. You need to compile this plugin https://github.com/ma-ca/deconz-cli-plugin, copy it to the deconz plugin folder and restart. How to connect is described in the repo. Then, issue the command below and share the output:

zclattrmanu YOURDEVICENWK 1 0xffac 0x113C 0C00000d
e.g. zclattrmanu 0x78c9 0xffac 0x113C 0C00000d

**Comment by aryelevin** [comment]
@SwoopX I found some more attributes  in the thermostat cluster which I want to support (actually just the swing functions of the AC which is at 0x0045).
I created my general.xml with some of them.
My question is: Should I add all the attributes in this attributes set or I can just add the one I need for it to be merged here?

**Comment by SwoopX** [comment]
Please add all, so we have them readily available

**Comment by aryelevin** [comment]
OK, will do it and get back ASAP

**Comment by aryelevin** [comment]
@SwoopX How to specify map32 data type in the xml?

**Comment by aryelevin** [comment]
@SwoopX OK, never mind, found it: bmp32...
I've finished working on this, where is it in this repo?

**Comment by aryelevin** [comment]
@SwoopX I've implemented the swing mode support in this commit, for me it seems to be working great.
https://github.com/aryelevin/deconz-rest-plugin/commit/3e31aaf50481ac506637af601ad081b4c15a401d

Please take a look and make sure it all fine, if so, just merge...

**Comment by SwoopX** [comment]
I guess it's looking fine so far. You used s8 for the 8 Bit enumeration instead of u8, but that doesn't matter. Setting the attribute will probably not work though. Where have you discovered the attribute (which cluster), was it with my suggested command? Was that the only attribute?

**Comment by aryelevin** [comment]
@SwoopX For me its working setting the attribute via the REST API (I'm using Homebridge for HomeKit integration), but I will look into what you're saying.
Its within the Thermostat cluster.
The way I found it was simple, I thought there must be an option to control the swing mode via Zigbee, so decided to look into Zigbee specs docs, and found something which for me was just seems related, so I gave it a try, and it worked.

**Comment by SwoopX** [comment]
> so unless the number is not exceeding 127 it should work as expected, isn't?

Indeed, and therefore, it doesn't matter here.

> This attribute is within the Thermostat cluster, and there is some more attributes, but those aren't supported by my device and I don't need those functionalities (mostly info about the AC itself like the compressor type and refrigerant type etc).
The way I found it was simple, I thought there must be an option to control the swing mode via Zigbee, so decided to look into Zigbee specs docs, and found something which for me was just seems related, so I gave it a try, and it worked.

Ok, after checking the specs, I now know what you mean/did. I was assuming you did the discovery of the manufacturer specific attribues already and the attribute was from there.

**Comment by aryelevin** [comment]
@SwoopX I will update the general xml.
To which file should I add it? the general xml in the root of this repo @ master?
Also, the plugin you instructed me to use is already installed in my system for a long time, since I used it to write the buttons configuration of the Ubisys D1 dimmer (This cannot change via the GUI for some reason, are this can be supported somehow?)

**Comment by aryelevin** [comment]
@SwoopX Sorry to bother you... Just want to create the PR, and I want to make sure I'm doing it right, so again, my question is: which general xml file should I use to create the PR? the one in the root of this repo at the master branch?

**Comment by aryelevin** [comment]
@SwoopX OK, So created my PR... Waiting for inputs about it...

Thank you very much for your support.

Now I will start looking into the secret cluster haha.

**Comment by aryelevin** [comment]
@SwoopX OK, so, after trying your command (discovering the secret cluster's attributes), it seems it doesn't returns anything.
What could be the reason?

**Comment by SwoopX** [comment]
Been busy lately.

> OK, so, after trying your command (discovering the secret cluster's attributes), it seems it doesn't returns anything.
What could be the reason?

Can you share the output? Eventuelly, the command didn't get recognized on the first time. It could also be possbile that the command is not implemented on the device.

Regarding the PR, we now have it in twice. Ok for you if I just take the necessary parts over in mine?

**Comment by aryelevin** [comment]
> Been busy lately.
We're all the same... Don't worry... hahaha.. Thanks anyways.

> Can you share the output? Eventuelly, the command didn't get recognized on the first time. It could also be possible that the command is not implemented on the device.
I will do it again, I have much of noisy output duo to some plugs reporting their electrical consumption, so a lot of unrelated output.

> Regarding the PR, we now have it in twice. Ok for you if I just take the necessary parts over in mine?
Yes, sure, do it.

**Comment by aryelevin** [comment]
@SwoopX Here's the output:
```
zclattrmanu 0xc506 1 0xffac 0x113C 0C00000d
 --> send OK
<-ZCL attribute report 0x0373 0x0B04 2 05 05 21 FFFFFF9A 59
<-ZCL discover attr 0xC506 for cluster 0xFFAC discoveryComplete = Yes
```
Please note the unrelated attribute report in the middle...
Thanks

**Comment by aryelevin** [comment]
@SwoopX I've added another commit with Swing mode attribute reporting binding (forgot that thing).
(Had no chance to test actually, but just the same as the thermostat mode code, so should be fine).

**Comment by aryelevin** [comment]
@SwoopX Just a ping.. ;-)

**Comment by SwoopX** [comment]
Got your changes all ported to my PR ;)

**Comment by aryelevin** [comment]
OK, so, after signed NDA to receive the secret cluster documentation, I got it, and as I guessed before, its related to the configuration of the thermostat itself (Like LED on/off and AC Remote type etc).
Cannot expose more than that duo to the NDA, so, sadly a big no no... hahaha.
Waiting for a final merge of this supported device as I'm using it now for a few weeks and it seems to be working great.

**Comment by SwoopX** [comment]
@aryelevin Could you do me a favor and try setting the swing mode directly via API? Pretty sure it will not work since the code seems to be at the wrong place and therefore never called.

**Comment by aryelevin** [comment]
@SwoopX You're right, now it is not working.
At the time we've worked on supporting it, it was working for sure, something changed it.
Can you point me to the issue? Or you working on a fix?

**Comment by SwoopX** [comment]
I'll have that covered, thanks for checking. Accidentially stumbled accross that :)

**Comment by aryelevin** [comment]
Great, thank you very much.
Regards

**Comment by aryelevin** [comment]
@SwoopX I'm trying to implement the FFAC cluster commands, but I need to specify a manufacturer code for each command, how this can be achieved in the general.xml? 
I tried to use mfcode=0x113c but it not being included in the request (I sniff using zshark and Wireshark), so what can I do?

**Comment by zhapwey** [comment]
Hi, I have seen this device and it seems very interesting, but I need to know if there is a way to configure the type of AACC so that it sends the correct ir commands, there is some way manually since from zigbee it does not seem to be implementing.

**Comment by aryelevin** [comment]
@zhapwey I were able to configure it using a manufacturer command via the cli plugin and it worked perfectly.
If you need assistance on figuring out the command itself, let me know and I'll do my best to send you an example.

**Comment by zhapwey** [comment]
hello:
I managed to sync the device with deconz without problems.
My problem is that I don't know how to send the code that you tell me, could you help me.

BR

**Comment by aryelevin** [comment]
@zhapwey Here's my configuration I use.
You need to use it with the cli plugin on deconz.
You have to use the device's short ID (or whatever it called) etc.
I hope this helps you.

OWON AC201 set the remote code: 20 is the command and 4403 is the code which in this case 836 decimal.
For example: 836 which 344 in Hex:
zclcmdmanu 0xXXXX 1 0xffac 0x113c 204403
For example: 930 which 3a2 in Hex:
zclcmdmanu 0xXXXX 1 0xffac 0x113c 20a203
For example: 830 which 33e in Hex:
zclcmdmanu 0xXXXX 1 0xffac 0x113c 203e03
Gets the current code:
zclcmdmanu 0xXXXX 1 0xffac 0x113c 00

**Comment by zhapwey** [comment]
thanks, Could you tell me how to access the cli plugin in deconz, I have no idea what this is?
Then I imagine that in that complement it will be necessary to write this line:

For example: 836 which 344 in Hex:
zclcmdmanu 0xXXXX 1 0xffac 0x113c 204403

zclcmdmanu -> command?
I see that the following parameters only change the last one? the rest are all the same?

BR, Thank you very much for your help it is much appreciated.

**Comment by zhapwey** [comment]
Is it possible to use the cli on windows 10?
