### ISSUE TITLE
Namron 2CH K4 (Luzense/Sunricher clone)

### ISSUE THREAD

**Issue by JDolven** [dresden-elektronik/deconz-rest-plugin#3378]
- Product name: Namron 2CH K4
- Manufacturer: NAMRON AS
- Model identifier: 4512719
- Device type : 
  - Switch

**Screenshots**

![bilde](https://user-images.githubusercontent.com/25934110/95437445-3de1a400-0955-11eb-9179-37366d08aaeb.png)

![bilde](https://user-images.githubusercontent.com/25934110/95437526-5d78cc80-0955-11eb-871f-a067c69012c5.png)

**Comment by SwoopX** [comment]
Already supported
