### ISSUE TITLE
Aqara Single Switch Module T1 (with Neutral)

### ISSUE THREAD

**Issue by spn91** [dresden-elektronik/deconz-rest-plugin#3380]
## Device

- Product name: Single Switch Module T1 (with Neutral)
- Manufacturer: LUMI
- Model identifier: lumi.switch.n0agl1
- Device type : Switch

https://www.aqara.cn/en/single_switch_T1_with-neutral.html
  

## Screenshots

![image](https://user-images.githubusercontent.com/6967608/95493823-4e1d7180-099d-11eb-91ce-f3ce9a9eebe7.png)
![image](https://user-images.githubusercontent.com/6967608/95493867-6097ab00-099d-11eb-9c00-7667d4696e8f.png)
![image](https://user-images.githubusercontent.com/6967608/95494424-31ce0480-099e-11eb-9cc0-87fb0d971307.png)
![image](https://user-images.githubusercontent.com/6967608/95494468-414d4d80-099e-11eb-8765-15f4090a5b2a.png)

[aqara-t1-single-switch-connecting-and-triggering.pcapng.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5350391/aqara-t1-single-switch-connecting-and-triggering.pcapng.zip)

[zigbee_pc_keys.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5350406/zigbee_pc_keys.txt)

**Comment by Smanar** [comment]
Ha nice ^^
I have started a discussion yesterday with another user about this device, there is a problem ATM for this device, the cluster 0x0006 is invisible (but present).

Do you have a zigbee sniffer ?

**Comment by Smanar** [comment]
Ok so have a take a look on the sniff with original gateway
- bad luck it don't ask for basic descriptor to compare (it s the device that ask for node descriptor)
- it is using a new attribute 0x00f7 an octet string, but nothing readable.

**Comment by SwoopX** [comment]
That's attribute 0x00f7

```
64 10 00        Boolean                     false
03 28 17        Signed 8-bit integer        23
98 39 00000000  Single precision            0
95 39 00000000  Single precision            0
96 39 90391145  Single precision            2323.59766
97 39 00000000  Single precision            0
05 21 0100      Unsigned 16-bit integer     1
9a 20 00        Unsigned 8-bit integer      0
0b 20 00        Unsigned 8-bit integer      0
08 21 1402      Unsigned 16-bit integer     532
09 21 0001      Unsigned 16-bit integer     256
```

**Comment by Smanar** [comment]
Ha yes lol, the magic attribute ^^.

**Comment by Smanar** [comment]
Ok so bad luck, the device realy forget the cluster 0x0006

![tmp](https://user-images.githubusercontent.com/20152487/95786152-53e5c080-0cd7-11eb-9164-d0c7e2f42f64.jpg)

And it was totaly mute after the inclusion, I realy don't see a way to detect the cluster 0x0006.
It was more active on normal gateway than on deconz.

I think need to use hack based on device type "on/off light" and manufacture number 0x115f ?

**Comment by spunti** [comment]
Any news? Or can I be helpful with something else?

**Comment by Mimiix** [comment]
@spunti I've read about this in Discord. The devs had a internal discussion on this. Manup responded with the following:
![image](https://user-images.githubusercontent.com/43333120/96091234-a25ab100-0ec9-11eb-89f3-a4ae26f7e85e.png)

**Comment by Smanar** [comment]
Yep, for the moment we are waiting to know if manup want to make something clean in the core, or if I make an ugly hack in the api core ^^

**Comment by spunti** [comment]
Any progress from manup with fixing this device? Would be nice to be finally able to control the device via HA :)

**Comment by Smanar** [comment]
No yet sorry, but still in the "todo list"

**Comment by manup** [comment]
Is there a sniffer log when the device sends on/off reports for endpoints other than the first (0x01)?

**Comment by manup** [comment]
> `08 21 1402      Unsigned 16-bit integer     532` 

By looking at the special attribute 0x08 uint16, I think this represents a model identifier.

**Comment by Smanar** [comment]
But the problem is to make the cluster 0x0006 "magically" appear in deconz, for the device can be usable in the API without hack.
Its something possible on deconz side with respecting the "zigbee rules" ?

**Comment by flopp999** [comment]
I can also maybe help with something, just ask me and we will see what I can do

**Comment by Smanar** [comment]
IDK if there is some improvement on deconz side or if we can do something ? (With using new descriptor engine ?)

**Comment by labaland** [comment]
Any progress with fixing this device? Would be nice to control the device via HA

**Comment by flopp999** [comment]
I have never used deConz GUI before, but today I had a look and I can see the WATT for this device.
I attached two pictures I don't know if that can help you.
![image](https://user-images.githubusercontent.com/21694965/101681527-8b1be800-3a62-11eb-85db-ee06eeed9726.png)
![image](https://user-images.githubusercontent.com/21694965/101681542-953de680-3a62-11eb-8f75-ab67adee1b8a.png)

**Comment by Smanar** [comment]
I can see to the cluster 0006.
It was missing on @spunti capture, It s repared ?

The device works for you ?

**Comment by flopp999** [comment]
I do get new values in 0x050B if I turn off/on the T1.
But I do not see any device in API.
This is as a Light, but my other Aqara Plug(different device) is as a sensor and then I get Consumption and Power

Aqara T1 build-in "box"
```
"manufacturername":"LUMI",
"modelid":"lumi.switch.n0agl1",
"type":"On/Off light"
```

Aqara Plug outlet
```
"manufacturername":"LUMI",
"modelid":"lumi.plug.maeu01",
"type":"ZHAConsumption"
```

**Comment by Smanar** [comment]
>But I do not see any device in API.

Ha ? but it  s a ight, the support is native ....

**Comment by flopp999** [comment]
The outlet plug is also under Lights
```
"manufacturername":"LUMI",
"modelid":"lumi.plug.maeu01",
"type":"Smart plug",
```

so what I am missing for T1 is to add it as a sensor, like Plug

**Comment by flopp999** [comment]
Light section:
T1 On/Off
Plug On/Off

Sensor section:
Plug as Consumption
Plug as Power

**Comment by Smanar** [comment]
So https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

```
git clone --branch Xiaomi https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

It s just a start, just make a test and tell me what is working or not, I will correct later.

**Comment by flopp999** [comment]
Tried it now, but I do not see any new devices in API.
I have checked that I use the correct commit 
![image](https://user-images.githubusercontent.com/21694965/101895693-29659600-3ba8-11eb-8c7e-e61d89b5a6c3.png)

**Comment by flopp999** [comment]
It is working now, I deleted the device and add it again, now I do get some new devices

Thank you :)

**Comment by MiAutomations** [comment]
> It is working now, I deleted the device and add it again, now I do get some new devices
> 
> Thank you :)

I just deleted the mine and re-added using the last versions available,  and I can't get the report of the electricity values. 

Can you please share with me what is the version of your deconz and the fw version of your conbeeII

**Comment by flopp999** [comment]
deconz GUI 2.07.01
phoszon GW 2.07.00
conbee FW 26660700

**Comment by MiAutomations** [comment]
Thank you for your reply 

But I still have no report dada from the electricity... Do you install the  deCONZ development package present in this post? 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3380#issuecomment-742687126

**Comment by flopp999** [comment]
> Thank you for your reply 
> 
> 
> 
> But I still have no report dada from the electricity... Do you install the  deCONZ development package present in this post? 
> 
> 
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3380#issuecomment-742687126

Yes I have

**Comment by MiAutomations** [comment]
And if I'm using the hassio OS how can perform this installation ? 
I think I can't, once I don't have core linux available .... maybe somebody can help me in this point ...???

**Comment by Smanar** [comment]
Hassio is not a real OS.
You need one to compile or install something.

**Comment by MiAutomations** [comment]
> Hassio is not a real OS.
> You need one to compile or install something.

Ok thank you, and can you please let me  know how to proceed with this, in order to get this to work?

Thank you

**Comment by Smanar** [comment]
@flopp999 Can you say me the sensor that are working and the one are not working ?

@MiAutomations depend of what you have as Unix machine (with complete OS). 
If you have one, just install deconz on it and after the dev stuff https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3380#issuecomment-742687126

**Comment by flopp999** [comment]
> @flopp999 Can you say me the sensor that are working and the one are not working ?
>

Aqara wall Plug is working

Aqara T1, that you change rest-plugin for, is not working.
I had to comment-out to get it to update

**Comment by Smanar** [comment]
Ha ? ok so I thought it was working because of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3380#issuecomment-743234187

You had to comment out ?  else you have error message ? wich one lines  ?

**Comment by SwoopX** [comment]
I feel those devices have a comparable strange behaviour as the `lumi.plg.mmeu01`. Most of the time, they don't show the simple metering and electrical measurement clusters and then out of a sudden, they pop up simple descriptors due to whatever reason. This theory would be supported by the deviating screenshots here.

Never was able to find any pattern or reason for that...

**Comment by spunti** [comment]
For me it would be ok, if the on/off operation is supported as first step :)

**Comment by MiAutomations** [comment]
@SwoopX Mimiix Can you please let me know if you still need more info about the device in order to get this to work ? 

Thank you and best regards

**Comment by spunti** [comment]
@MiAutomations I have checked your created issue about this switch. There you are writing, that on/off is already working? What have you done to get it working?

**Comment by MiAutomations** [comment]
> here you are writing, that on/off is already working? W

Yes the relay on/off functions are working properly, I have a issue only in get the data from the electricity report for this device once this one support the power consuming report also, but is not available over the deconz/conbeII

**Comment by spunti** [comment]
> > here you are writing, that on/off is already working? W
> 
> Yes the relay on/off functions are working properly, I have a issue only in get the data from the electricity report for this device once this one support the power consuming report also, but is not available over the deconz/conbeII

Please explain what you have done to get it working. Are you using the dev build from @Smanar?

**Comment by spunti** [comment]
@MiAutomations could you please give information about your deconz version? And please let me know, how you have connected the t1 switch to deconz. For me the switch only appears in the software, not at the web interface.

**Comment by Mimiix** [comment]
@SwoopX @Smanar What do we need for measurement? Or is this simply a _lie_ of the devices?

**Comment by spunti** [comment]
As first step it would be cool to have the on/off operation working. It seems to work for one user, but not for me. The switch is not visible in Phoscon (I assume that it should appear under the light section). 
deCONZ Version: 2.07.1

**Comment by ebaauw** [comment]
> but some user have the cluster 0x0006 visible and other not.

I think deCONZ should show the cluster when it sees a message from it, even if it isn't returned on the _Simple Descriptor_.  You probably need to turn the relay on through a wired in-wall swich before it sends an attribute report for the _OnOff_ attribute.

> What do we need for measurement? Or is this simply a lie of the devices?

That's probably reported through the _Analog Input_ clusters.  The second endpoint will be (current) power, the third (life-time) consumption, if they follow the logic of other Aqara wired devices.  The _Multistate Input_ on the fourth endpoint likely reports button actions of the wired switch.  You might want to check if the switch input can be detached from the relay.

**Comment by spunti** [comment]
> > but some user have the cluster 0x0006 visible and other not.
> 
> I think deCONZ should show the cluster when it sees a message from it, even if it isn't returned on the _Simple Descriptor_. You probably need to turn the relay on through a wired in-wall swich before it sends an attribute report for the _OnOff_ attribute.

I'm turning it on and off multiples times every day. Or what do you mean exactly? For me the 0x0006 cluster is not visible (see screenshots from initial post).

**Comment by Smanar** [comment]
You are using a switch to turn it on or off ?

**Comment by spunti** [comment]
> You are using a switch to turn it on or off ?

Yes, it is connected to a switch.

**Comment by Smanar** [comment]
@ebaauw do you think if I use a hack (one more) to force the light entry be created according to the model id, the API code will work ?

**Comment by MiAutomations** [comment]
> you please give information about your deconz version? An

Helo, the version is now Current version: 6.6.2, and in my case appears on the web interface deconz when i search for new device and also in the Home Assistant entities but obly as a switch not the information about the electricity data

**Comment by SwoopX** [comment]
Ok, I've taken another look at the sniffer log initially provided. The switch definititely seems to send attribute reports from the on/off cluster and reacts on those commands...

![grafik](https://user-images.githubusercontent.com/4005212/104058626-55e6ef00-51f4-11eb-9f7b-ea5e4c41b798.png)

Question now is why deconz doesn't pick this up or doesn't represent that cluster in the GUI respectively.

**Comment by Smanar** [comment]
IDk, realy strange, manup have said me tha same thing than ebaauw, and was correctly recently in core from my memory (have same problem for invisible tuya cluster).
From manup if the cluster is know (in the general.xml file) it can be added itself when deconz see it.

**Comment by SwoopX** [comment]
Can anybody please read the attributes from the lumi specific cluster in deconz GUI and share a screenshot? I might have stumbled upon something accidentally I'd like to verify.

**Comment by Smanar** [comment]
Oups, I totaly forget this issue.
I m trying a hack for the invisible cluster https://github.com/Smanar/deconz-rest-plugin/commit/5f6acaf24350e65ac807d32ee4d4dbdd1447bc9b#diff-d0aaee66bc2f60fdd243c0e5b86aebca01fa3eb36c7ec39578d5beeca47078ab

Do you think it can work ?

**Comment by SwoopX** [comment]
No need to do any magic if my theory is right. It is probably related to attribute 0x0009 on that cluster. When it is set to 0, it seems to supress a significant amount of reporting messages, including on/off

**Comment by Smanar** [comment]
Ha ? can be realy nice information.

**Comment by spunti** [comment]
> Can anybody please read the attributes from the lumi specific cluster in deconz GUI and share a screenshot? I might have stumbled upon something accidentally I'd like to verify.

What do you mean with "lumi specific cluster"?

**Comment by SwoopX** [comment]
When viewing the node in deconz GUI, there is a cluster called like that. I need a screenshot with the attributes being read

**Comment by spunti** [comment]
@SwoopX 
![image](https://user-images.githubusercontent.com/6967608/105751317-20593a00-5f46-11eb-8fb1-c6e57d7e8cd3.png)

**Comment by SwoopX** [comment]
Yeees :)

Now double click on the value of  attribute 0x0009 and set it to 1 and cross fingers to let some magic happen. You might need to discinnect the device from power for it to work afterwards.

**Comment by spunti** [comment]
> Now double click on the value of attribute 0x0009 and set it to 1 and cross fingers to let some magic happen. You might need to discinnect the device from power for it to work afterwards.

Ok, set it to 1. It was really strange, tried it two times and every time it told me that the writing has failed after about 30 seconds.
Now I had another look at it and recognized that it is set to 1. But now I am not at home anymore, so I have to check it in the evening, and also to disconnect the power from it. Should it appear automatically, or do I have to do something more?

**Comment by Smanar** [comment]
But if you disconnect the device, it was reseted, so the setting is loose ?

**Comment by spunti** [comment]
What do you mean? I have not disconnected the power yet.

**Comment by Smanar** [comment]
>You might need to discinnect the device from power for it to work afterwards.

My question was for Swoops ^^.

**Comment by MiAutomations** [comment]
> Yeees :)
> 
> Now double click on the value of attribute 0x0009 and set it to 1 and cross fingers to let some magic happen. You might need to discinnect the device from power for it to work afterwards.

Hello and thank you for your support .

I have a different values in the attribute 0x0009 ... is this normal our do I have to perform other task? 

![image](https://user-images.githubusercontent.com/47602733/105866598-0f630400-5fec-11eb-8820-02c09068188c.png)

**Comment by spunti** [comment]
@MiAutomations 

you are looking at the wrong place. This is the basic cluster.

**Comment by MiAutomations** [comment]
> @MiAutomations
> 
> you are looking at the wrong place. This is the basic cluster.
> 
> EDIT: and I think this has nothing to do with your problem. You are already able to switch on/off.

Ok thank you, yes my problem is related to the electricity data or measuring information on this module 

Thank you and best regards

**Comment by spunti** [comment]
@SwoopX The switch was now disconnected from power, but nothing has changed. Also the value of 0x0009 is not changing back to 0.

**Comment by SwoopX** [comment]
Hm, never getting boring with Xiaomi...

The last thing I can think of is: ensure attribute 0x0009 is set to 1 and then re-read the node descriptor, followed by the active endpoints and the simple descriptors.

**Comment by spunti** [comment]
Sry, this is also not working. But what should be the result of executing this steps? Should the switch appear in the light section of phoscon?

**Comment by MiAutomations** [comment]
Any news regarding the power consuming information get from this device anyone have success to get this info over the deconz and conbee II ? 

Thank you and best regards

**Comment by SwoopX** [comment]
At least got an idea what could be checked... Need to dig a little bit into this

**Comment by spunti** [comment]
Any news for us?

**Comment by Mimiix** [comment]
@SwoopX ^

**Comment by spn91** [comment]
Keep it active, no solution yet.

**Comment by cornim** [comment]
Is there anything like a roadmap to know when this is going to be added to conbee 2?

**Comment by Mimiix** [comment]
@cornim  nope. I pinged Swoop :)

**Comment by SwoopX** [comment]
See #4328

Relevant PR just got merged yesterday.

**Comment by Mimiix** [comment]
Is anyone able to compile and test the fix? 

**If you can't/don't know how, please follow this: https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only If you can't after that, please wait for a release or lte someone else test it. Let's keep it clean :)**

**Comment by spn91** [comment]
After nobody replied for such a long time I have replaced it with sonoff devices. So I cannot help with testing anymore. 
But should this fix my problem (no on/off switch) or is this just for power metering?

**Comment by Mimiix** [comment]
@spn91  from the PR (as mentioned by swoop):
Whitelist for binding
Calculate the correct power values
Do not expose current and voltage

**Comment by cobch** [comment]
> Hello Team 
> 
> 
> 
> I removed the device and add again, but I still not see the dada from the power consuming available on the device over the deconz integration, can you please let me know what I have to do in order to get this ?
> 
> 
> 
> deCONZ Current version: 6.8.0 
> 
> Firmware 26660700
> 
> Core Version core-2021.5.2
> 
> 
> 
> Thank you and bets regards

Did you manage to get power/energy in deconz?

**Comment by MSL-DA** [comment]
I don't understand why a switch is added when I add an Aqara Single Switch Module T1 (With Neutral)

```
{
    "capabilities": {
        "alerts": [
            "none",
            "select",
            "lselect"
        ]
    },
    "config": {
        "groups": [
            "1"
        ]
    },
    "etag": "aac090214d5e63c21c51e7884088453b",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2023-09-03T14:32Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.switch.n0agl1",
    "name": "Bad",
    "state": {
        "alert": "none",
        "on": false,
        "reachable": true
    },
    "swversion": "0.0.0_0021",
    "type": "On/Off light",
    "uniqueid": "54:ef:44:10:00:15:95:18-01"
}
```

And the switch which will be added when I add the Single Switch Module T1 (With Neutral)

```
{
    "config": {
        "clickmode": "rocker",
        "devicemode": "compatibility",
        "on": true,
        "reachable": true
    },
    "ep": 41,
    "etag": "1ed98c63bb541be7d6fd255335219204",
    "lastannounced": null,
    "lastseen": "2023-09-03T14:34Z",
    "manufacturername": "LUMI",
    "mode": 1,
    "modelid": "lumi.switch.n0agl1",
    "name": "Switch 31",
    "state": {
        "buttonevent": null,
        "lastupdated": "none"
    },
    "swversion": "0.0.0_0021",
    "type": "ZHASwitch",
    "uniqueid": "54:ef:44:10:00:15:95:18-29-0012"
}
```

**Comment by Smanar** [comment]
From the DDF you need to have :
- a TYPE_ON_OFF_LIGHT finishing by -01
- a TYPE_POWER_SENSOR finishing by 15-000C
- a TYPE_CONSUMPTION_SENSOR finishing by 1F-000C
- a TYPE_SWITCH finishing by 29-0012

**Comment by MSL-DA** [comment]
> From the DDF you need to have :
> 
> * a TYPE_ON_OFF_LIGHT finishing by -01
> * a TYPE_POWER_SENSOR finishing by 15-000C
> * a TYPE_CONSUMPTION_SENSOR finishing by 1F-000C
> * a TYPE_SWITCH finishing by 29-0012
> 
> Perhaps only used on decoupled mode ?

I have to admit I don't know what you are talking about. I add it through Phoscon

**Comment by Smanar** [comment]
No problems, but phoscon is limited as third app, for exemple it don't support power measurement.
