### ISSUE TITLE
Add the ability to adjust cooling setpoints of zigbee thermostats

### ISSUE THREAD

**Issue by andynbaker** [dresden-elektronik/deconz-rest-plugin#3382]
## Feature request type

Extend the REST-API to allow setting of the cooling setpoint of zigbee thermostats, specifically the Zen-01.
## Description

Full disclosure, I have no idea what I'm doing here. I have a conbee II and run the deCONZ Home Assistant add-on and integration. I also have three Zen-01 thermostats that control traditional combined central heating and cooling HVAC systems, (so both HEAT and COOL modes are supported). I have the thermostats successfully paired, and by [tweaking the deCONZ home assistant integration,](https://github.com/home-assistant/core/issues/41182#issuecomment-703255600) I can successfully change the mode between heating and cooling.

However, it appears the deCONZ REST-API (and therefore the deCONZ HA integration) cannot control the cooling setpoint. In cooling mode, I cannot change the setpoint. But in heating mode I can change the setpoint. As I posted [here](https://github.com/home-assistant/core/issues/41182#issuecomment-705759416) in the HA integration, it appears the REST-API does not currently support adjusting the cooling setpoint?

## Considered alternatives

I have run the ZHA Home Assistant integration instead of deCONZ, using the conbee II, and was able to successfully pair the thermostats and control the cooling setpoints. However, I'd prefer to use deCONZ instead of ZHA and would love to get this feature  carried over.

**Comment by SwoopX** [comment]
I got this already waiting locally to be pushed. I expect this to be available with the beta next week.

Does the zen has a fan control cluster btw?

**Comment by andynbaker** [comment]
Yay! And yes, I think it does have a fan control cluster. At least, using the ZHA integration in Home Assistant I was able to change the fan from auto to on (and it was a really nice feature and enabled me to set up circulation routines when the HVAC system was idle for an extended period of time).

Does this help?

![Screen Shot 2020-10-08 at 5 53 15 PM](https://user-images.githubusercontent.com/53503316/95521459-2fb07980-098f-11eb-8c9d-ca656ff8a88c.png)
help?

**Comment by SwoopX** [comment]
Yeah, that helps. Can you please double check if you got a light resource for steering the fan? If not, try searching for lights and change the fan mode.

**Comment by andynbaker** [comment]
Just checked again. I do not have any extra lights representing the fan. I just removed and repaired one to be sure and no lights popped up.

**Comment by SwoopX** [comment]
Just a quick update: Haven't forgotten about that, but I need to wait for other PRs to be merged first before I can bring this one in.

**Comment by andynbaker** [comment]
You da man. Thanks for taking care of it. As soon as you guys push this out, I can work with the guys who manage the home assistant integration to add the function there.

**Comment by andynbaker** [comment]
Hey @SwoopX! I pulled the latest deconz docker image and read through the rest API docs so that I could test this out. As of now, I can both change the thermostat mode to cool and the fanmode to on/auto without an issue with this message body and endpoint:

```
http://[MY_API_IP_AND_PORT]/api/[MY_USERNAME]/sensors/[MY_THERMOSTAT]/config
{"mode":"cool"}
```
or
```
http://[MY_API_IP_AND_PORT]/api/[MY_USERNAME]/sensors/[MY_THERMOSTAT]/config
{"fanmode":"on"}
```
But when I try to change the coolsetpoint I always get an error response:

```
http://[MY_API_IP_AND_PORT]/api/[MY_USERNAME]/sensors/[MY_THERMOSTAT]/config
{"coolsetpoint":"2350"}

[{"error":{"address":"/sensors/2/config/coolsetpoint","description":"invalid value, 2350, for parameter coolsetpoint","type":7}}]
```
Am I doing something wrong here?

CC @Kane610

**Comment by SwoopX** [comment]
Found the issue. I added a type check for that parameter which expects the value to be numeric. However, it seens to arrive as string. Not too sure if I can find the why on short notice before the next release in some hours. I doubt, I remove the check for the time being.

**Comment by SwoopX** [comment]
@andynbaker Hey, could you please let me know how you've send the cool point temperature value? I just made a test with setheatpoint and the data type is, as expected, double when I send it.

**Comment by andynbaker** [comment]
I'm not sure I understand the question exactly. Maybe this helps: I'm using node-red to make a simple http request. Per the documentation here, I'm attempting to adjust the cool set point with the coolsetpoint config attribute:

![Screen Shot 2020-11-30 at 4 11 28 PM](https://user-images.githubusercontent.com/53503316/100672111-1260b180-3327-11eb-936a-c6662ec7e3ae.png)

Here's my PUT request endpoint: `http://[MY_DECONZ_IP_AND_PORT]/api/[MY_USERNAME]/sensors/[MY_DEVICE]/config` and here's my message body: `{"coolsetpoint":"2350"}`. This is the response I get: 

```
address: "/sensors/2/config/coolsetpoint"
description: "invalid value, 2350, for parameter coolsetpoint"
type: 7
```
Is this what you're after?

**Comment by SwoopX** [comment]
I guess so. Please try without "" around the temperature value

**Comment by andynbaker** [comment]
That was it! I'm so used to wrapping everything in node-red that I didn't realize I could even do it without. OK so I can confirm that I can in fact change the mode and the coolsetpoint per the documentation. You're the man.

**Comment by SwoopX** [comment]
Great, riddle solved. Please note, I will re-enable the type check with the next release in 2 weeks.

**Comment by solvisit** [comment]
It is possible to add the same coolingsetpoint to Bitron 902010/32, it has the ablity to switch mode from "heat" to "cool".
For enabling both modes it is necessary to set 0x001B (Control Sequence of Operation) of thermostat cluster to 0x04  (Cooling and Heating 4-pipes) before changing 0x001C (System Mode) to 0x02 (Cool)

**Comment by solvisit** [comment]
I will open a new feature request, maybe is the best way to resolve the issue.
