### ISSUE TITLE
Adurosmart ERIA Smart Wireless Dimming Switch Remote 81825

### ISSUE THREAD

**Issue by stevenwfoley** [dresden-elektronik/deconz-rest-plugin#3383]
## Device
- Product name: ERIA Smart Wireless Dimming Switch Remote
- Manufacturer: ADUROLIGHT
- Model identifier: Adurolight_NCC
- Device type: Switch
https://adurosmart.com/product/eria-smart-wireless-dimming-switch-remote/

## Screenshots
![image](https://user-images.githubusercontent.com/37962790/95523612-131b3e00-099d-11eb-9bd4-c2f0e7e0e15f.png)
![image](https://user-images.githubusercontent.com/37962790/95524593-ca18b900-099f-11eb-82ab-05685daac2a8.png)

**Comment by mdolnik** [comment]
FYI there is an closed / stale issue for this remote (#1730) which never got resolved.

I'm willing to make changes to the source code and test with my Eria remote if someone with more expertise can chime in and suggest what would need to be changed.

**Comment by Mimiix** [comment]
Would like to continue in #1730 ! :)
