### ISSUE TITLE
Tuya TS0601 : Time not synced

### ISSUE THREAD

**Issue by helmuteke** [dresden-elektronik/deconz-rest-plugin#3386]
have a TS0601 thermostat.
I set the time on the device and pair with deconz.

After xx time the thermostat has another time.
Upgraded to lates firmware

**Comment by Smanar** [comment]
I think it will be better if you close this issue, and make it again using template.

And give more information, there is the time on thermostat ?

**Comment by Mimiix** [comment]
Template info is missing. Closing!
