### ISSUE TITLE
light group switches off/on automatically  

### ISSUE THREAD

**Issue by pep4n** [dresden-elektronik/deconz-rest-plugin#3388]
Hi deconz Team,

I have a light group that switches off and after a short time on again. 
Not often. Lets say every one/two hours. 
ioBroker log is empty. I'm using deconz via docker on a synology. 

Is there any deconz log file I could check? 
Or how would you troubleshoot this? 

Thanks,
p

**Comment by SwoopX** [comment]
Closing this for not using the template.
