### ISSUE TITLE
Successful updates to deCONZ_ConBeeII_0x26660700.bin.GCF ?? Anyone?

### ISSUE THREAD

**Issue by Sjonnie2018** [dresden-elektronik/deconz-rest-plugin#3390]
I am wondering if there are (any?) positive/successful upgrades to firmware deCONZ_ConBeeII_0x26660700.bin.GCF? All I read over here are bugs and problems. Much of these related to specific combinations of hard- and software.

I have a habit of upgrading soft- and firmware for my devices and equipment but would like to know what I get into.  So I would like to know who has made a successful upgrade to the latest firmware and how you went about.

Greetz,

Sjonnie

**Comment by Smanar** [comment]
Yes, there is some success ^^.

I can't say if this one is better for you, and to update it just avoid virtual machine, and you can rollback if you have problem with it.

And BTW try to use the template, even for short question, moderator are trying to clean the github.

**Comment by Sjonnie2018** [comment]
Hi Smanar/Thorgal,

Thanks for your reply. I would have liked to stick to the template but couldn't phrase my question in the correct way. Sorry!

I am eager to learn of the experiences of others in this matter!

Greetz,

Sjonnie

**Comment by Smanar** [comment]
For short question try the discord > https://discord.gg/QFhTxqN
Will be faster for you.

**Comment by Sjonnie2018** [comment]
Hi Smanar,

Yet another place? Another registration, another password and another place I have to monitor to get information?

Registered of course but I kinda would have liked it if it was possible to share information here on github...

Regards,

Sjonnie

**Comment by SwoopX** [comment]
Uodated 3 devices, no issues (and never had any).

Btw, your choice of choosing the channel. Discord is faster and more interactive. Github is for development and unfortunately often misused as a forum 🤷‍♂️

**Comment by Sjonnie2018** [comment]
OK, I will close this issue. Thanks for your replies.
