### ISSUE TITLE
Bosch  ISW-ZPR1-WP13 pir sensor missing features like tamper and battery percentage

### ISSUE THREAD

**Issue by mamrai1** [dresden-elektronik/deconz-rest-plugin#3393]
## Device

- Product name: Bosch  ISW-ZPR1-WP13
- Manufacturer: Bosch
- Model identifier:  ISW-ZPR1-WP13
- Device type : Please remove all unrelated device types. 
  - Sensor

  - Other: 

## Screenshots

![basic](https://user-images.githubusercontent.com/57288344/95672373-f81d1980-0ba8-11eb-92c2-d430613d7a96.png)
![diagnostics1](https://user-images.githubusercontent.com/57288344/95672374-f94e4680-0ba8-11eb-8359-ff9bdb96856a.png)
![diagnostics2](https://user-images.githubusercontent.com/57288344/95672376-f9e6dd00-0ba8-11eb-8101-e328306540eb.png)
![iaszone](https://user-images.githubusercontent.com/57288344/95672379-fb180a00-0ba8-11eb-9b9a-385ba702b9d2.png)
![identify](https://user-images.githubusercontent.com/57288344/95672381-fbb0a080-0ba8-11eb-81a1-f8715a53e015.png)
![nodeinfo](https://user-images.githubusercontent.com/57288344/95672383-fc493700-0ba8-11eb-9382-4a17644f5814.png)
![otau](https://user-images.githubusercontent.com/57288344/95672384-fce1cd80-0ba8-11eb-94c8-409fea87ade0.png)
![phoscon](https://user-images.githubusercontent.com/57288344/95672385-fd7a6400-0ba8-11eb-8ea1-0b5873342bb0.png)
![poll](https://user-images.githubusercontent.com/57288344/95672386-fe12fa80-0ba8-11eb-9f59-90335c1b8282.png)
![power1](https://user-images.githubusercontent.com/57288344/95672387-feab9100-0ba8-11eb-8dfc-833a6c1ddd3c.png)
![power2](https://user-images.githubusercontent.com/57288344/95672389-ff442780-0ba8-11eb-9ab6-c24868ce78fa.png)
![temp](https://user-images.githubusercontent.com/57288344/95672390-ffdcbe00-0ba8-11eb-9be3-c45b5d1b3214.png)

**Comment by mamrai1** [comment]
1) motion sensor is triggered for 1 second and then sleeps for 3 minutes..
2) temperature is reported only when there is a change over 0.5 degrees celcius...( as i can see from home assistant history)
3) pairing was done near the conbee ii before moving the sensor to position..(initial pairing on position was not ok_through ikea light)

**Comment by mamrai1** [comment]
api response after opening sensor case shows that tamper works (http://192.168.1.100:40850/api/7A79971660/sensors/17):

{"config":{"battery":null,"duration":60,"on":true,"pending":[],"reachable":true},"ep":5,"etag":"948eaa7befa5835d7fd7a38f6c3c8b1a","lastseen":"2020-10-11T14:43Z","manufacturername":"Bosch","modelid":"ISW-ZPR1-WP13","name":"Kitchen Motion sensor","state":{"lastupdated":"2020-10-11T14:43:57.887","lowbattery":false,"presence":false,"tampered":true},"swversion":"20140929","type":"ZHAPresence","uniqueid":"00:15:5f:00:b4:4d:1c:f2-05-0500"}

but also 2nd id of same sensor (http://192.168.1.100:40850/api/7A79971660/sensors/18):

{"config":{"battery":null,"offset":0,"on":true,"reachable":true},"ep":5,"etag":"cf48ac696715c56e5e79368c96c4c2c2","lastseen":"2020-10-11T14:43Z","manufacturername":"Bosch","modelid":"ISW-ZPR1-WP13","name":"Kitchen Motion sensor","state":{"lastupdated":"2020-10-11T14:43:46.295","temperature":2614},"swversion":"20140929","type":"ZHATemperature","uniqueid":"00:15:5f:00:b4:4d:1c:f2-05-0402"}

Is this normal?

**Comment by SwoopX** [comment]
Erm, I don't understand the question here. In case it's if it is normal to have 2 sensors for the device, then yes.

Thanks for the provided info. That should be sufficient to allow us making the necessary changes for the battery readings.

Regarding the threshold for the temperature change reports, that can be changed at will via deconz GUI. Check out https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#manually-configure-attribute-reporting and choose attribute `Measured value` from Temperature Measurement cluster.

**Comment by mamrai1** [comment]
Thanks. How can I manually expose battery state and tamper on home assistant? Is there a guide?

**Comment by SwoopX** [comment]
No clue, that's what you should ask in the HA universe.

**Comment by mamrai1** [comment]
One more question: Why 'tampered' attribute is not shown in phoscon?
