### ISSUE TITLE
haozee smoke sensor - it's possible to include?

### ISSUE THREAD

**Issue by Jfcanadell** [dresden-elektronik/deconz-rest-plugin#3395]
- Product name:   wireless smoke detector.
- Manufacturer:    _TZYB01_dsjszp0x.
- Model identifier:  TS0205.
- Device type :  Sensor

![smoke sensor 6](https://user-images.githubusercontent.com/69483664/95674588-75e52300-0bb1-11eb-8f2a-fbc0c91ef9a8.jpeg)

![smoke sensor 7](https://user-images.githubusercontent.com/69483664/95674577-67970700-0bb1-11eb-8aad-84dd60e83762.jpeg)

![smoke sensor 1](https://user-images.githubusercontent.com/69483664/95674261-446b5800-0baf-11eb-8782-55b58af663a4.jpg)

![smoke sensor 2](https://user-images.githubusercontent.com/69483664/95674276-58af5500-0baf-11eb-85f8-ac6b3021a8f1.jpg)

![smoke sensor power cluster 1](https://user-images.githubusercontent.com/69483664/95674283-5fd66300-0baf-11eb-86e2-d7bed3eb8f2f.jpg)

![smoke sensor power cluster 2](https://user-images.githubusercontent.com/69483664/95674286-67960780-0baf-11eb-9c0c-e8cd9d42e6e9.jpg)

![smoke sensor IAS zone](https://user-images.githubusercontent.com/69483664/95674291-6c5abb80-0baf-11eb-87b8-f53ad1bc9114.jpg)

![smoke sensor identify cluster](https://user-images.githubusercontent.com/69483664/95674516-053e0680-0bb1-11eb-916c-318a9f92d8d9.jpg)

**Comment by accelle17** [comment]
Here's another screenshot for the device clusters and node info:

  - Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/20294546/97825017-7710f800-1cf8-11eb-9de5-2b1b102d2c62.png)


  - Node Info panel
![image](https://user-images.githubusercontent.com/20294546/97825128-cbb47300-1cf8-11eb-9314-78e4ab573b07.png)


  - Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/20294546/97825061-9445c680-1cf8-11eb-82b2-0b820ea4c41a.png)
![image](https://user-images.githubusercontent.com/20294546/97825070-9a3ba780-1cf8-11eb-80eb-09887029690a.png)

0001 POWER CONFIGURATION CLUSTER:
![image](https://user-images.githubusercontent.com/20294546/97825167-e686e780-1cf8-11eb-970d-576df579bd73.png)
![image](https://user-images.githubusercontent.com/20294546/97825185-f1da1300-1cf8-11eb-96cc-64d4ade52c76.png)

0003 IDENTIFY CLUSTER:
![image](https://user-images.githubusercontent.com/20294546/97825199-fdc5d500-1cf8-11eb-9f5e-24021e14a189.png)

0500 IAS ZONE:
![image](https://user-images.githubusercontent.com/20294546/97825229-1209d200-1cf9-11eb-9a88-54643072e96e.png)
![image](https://user-images.githubusercontent.com/20294546/97825248-1f26c100-1cf9-11eb-86b6-010a856515c6.png)

0003 IDENTIFY CLUSTER (2):
![image](https://user-images.githubusercontent.com/20294546/97825346-56956d80-1cf9-11eb-9677-bfd8dab1d792.png)

0019 OTAU:
![image](https://user-images.githubusercontent.com/20294546/97825278-31a0fa80-1cf9-11eb-8d2e-752e1784cf8c.png)

**Comment by accelle17** [comment]
There's already support for TS0204 which is a gas sensor, so it might just need to be added with the same code. Also, this device can act as a controllable siren I believe.

**Comment by saxn-paule** [comment]
> There's already support for TS0204 which is a gas sensor, so it might just need to be added with the same code. Also, this device can act as a controllable siren I believe.

Exactly this was my intent when I bought it. How could I use it as a siren?

**Comment by SwoopX** [comment]
Unless it hasn't got a IAS Warning cluster, you can't.
