### ISSUE TITLE
Hue bridge not working on windows

### ISSUE THREAD

**Issue by ldplusse** [dresden-elektronik/deconz-rest-plugin#3399]
I am trying to connect my Logitech Harmony remote to the Deconz hue bridge, but it cannot detect it.
Windows 10, 1909. No FW. Conbee original.
Deconz and Harmony on the same network. Harmony can see a 'real' Hue bridge with no problem.

From ealier post, it seems this problem, is only present on the windows version of Conbee.
This problem has existed on windows for years.

Any chance to get a fix?

**Comment by Mimiix** [comment]
Hi,

Closing this issue. No template is used.
