### ISSUE TITLE
Is it possible to change a/the Device ID or "undelete" a device in the db

### ISSUE THREAD

**Issue by Gammenon** [dresden-elektronik/deconz-rest-plugin#3401]
## Describe the question or issue you are having
My bad, github didn't suggest the templates for me in the first try: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3389

So here, my second try...

I unintentionally deleted a sensor which drove me crazy cause of reoccuring pairing problems.
For now I got it reconnected but it has a new ID.
Former 34, now 36.
Is there any way to change the id by hand (over the api) to get the sensor back to its former place?

Otherwise I have to modify all iobroker scripts (and grafana dashboards) usings this sensor.

[...]

I figured out how to connect to the deconz DB and noticed, the "old" device is still in there with a "deleted" state. Would it be possible just to switch it back to "normal" and delete the "false" new one instead.
And just to have things clean, remove this then deleted item sid=36? Or is there an autoincrement and/or dependencies?

Thanks in advance ;)

## Screenshots
n/a

## Environment
Version: 2.05.81 / 14.9.2020
Firmware: 26580700

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: (26580700)
 - deCONZ version: 2.05.81
 - Device: ConBee II
 - Do you use an USB extension cable: yes

### deCONZ Logs
n/a

## Additional context
n/a

**Comment by SwoopX** [comment]
The only way you can possibly do that is by "hacking" the DB, but you should know what you're doing. I don't recall if there's also an update of `device_descriptors` required. Anyway, be advised to make a backup before you start fiddling around.
