### ISSUE TITLE
Hyper Worm compiled for windows yet?

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#3403]
Hi Guys,

Please compile windows version of Hyper Worm please :)

Thank you!!

**Comment by Mimiix** [comment]
Forwarded it to @manup

**Comment by Mimiix** [comment]
And it's up:
http://deconz.dresden-elektronik.de/win/

**Comment by PrimaryInc** [comment]
Thank you!! :)

**Comment by pippo73** [comment]
Thanks @Mimiix
