### ISSUE TITLE
New device - water sensor

### ISSUE THREAD

**Issue by stappel** [dresden-elektronik/deconz-rest-plugin#3411]
Please add the following device as water sensor:
![2020-10-14_113826](https://user-images.githubusercontent.com/13430384/95972143-64e71c80-0e12-11eb-8c8b-12b874ecaf4f.png)
![2020-10-14_113701](https://user-images.githubusercontent.com/13430384/95972176-6b759400-0e12-11eb-919f-8f7b4d4efe3c.png)
![2020-10-14_113804](https://user-images.githubusercontent.com/13430384/95972184-6d3f5780-0e12-11eb-9b49-1134ddb8d053.png)
![2020-10-14_113902](https://user-images.githubusercontent.com/13430384/95972187-6f091b00-0e12-11eb-980d-2722fd005470.png)
![2020-10-14_113914](https://user-images.githubusercontent.com/13430384/95972191-703a4800-0e12-11eb-9e2d-9c74199b6644.png)
![2020-10-14_113930](https://user-images.githubusercontent.com/13430384/95972200-716b7500-0e12-11eb-9293-e3afc7425ef7.png)
![2020-10-14_113946](https://user-images.githubusercontent.com/13430384/95972205-73353880-0e12-11eb-9184-85f21b648e18.png)
![2020-10-14_114002](https://user-images.githubusercontent.com/13430384/95972210-74666580-0e12-11eb-8c90-0d5b3a9f55c0.png)
![2020-10-14_114019](https://user-images.githubusercontent.com/13430384/95972217-77615600-0e12-11eb-9d10-178328033a57.png)

**Comment by Mimiix** [comment]
Closing this issue. Not using template.

**Comment by SwoopX** [comment]
No need to reopen/create a new issue anyway, device is supported.
