### ISSUE TITLE
iHorn - LH05121 - smoke detector

### ISSUE THREAD

**Issue by stappel** [dresden-elektronik/deconz-rest-plugin#3413]
## Device

- Product name: iHorn LH-99ZB
- Manufacturer: iHorn
- Model identifier: LH05121
- Device type : Please remove all unrelated device types. 
  - Sensor (smoke)
## Screenshots
![2020-10-14_120304](https://user-images.githubusercontent.com/13430384/95974884-c6f55100-0e15-11eb-86ac-c31b50d9b679.png)
![2020-10-14_120258](https://user-images.githubusercontent.com/13430384/95974891-c8bf1480-0e15-11eb-81b5-b1d3ad3c0057.png)
![2020-10-14_120318](https://user-images.githubusercontent.com/13430384/95974899-cbba0500-0e15-11eb-96d2-f48595e94b92.png)
![2020-10-14_120325](https://user-images.githubusercontent.com/13430384/95974907-cd83c880-0e15-11eb-9145-ae587a54a559.png)
![2020-10-14_120332](https://user-images.githubusercontent.com/13430384/95974912-cf4d8c00-0e15-11eb-9093-4468a66f79f4.png)
![2020-10-14_120345](https://user-images.githubusercontent.com/13430384/95974916-d1174f80-0e15-11eb-99e0-dbb9bb75fcb7.png)

**Comment by SwoopX** [comment]
Closing this one as it is supported with version 2.06.00.
