### ISSUE TITLE
how to start Deconz-GUI minimized on Raspberry pi

### ISSUE THREAD

**Issue by Deficiency1984** [dresden-elektronik/deconz-rest-plugin#3415]
Hi.

How can i start DECONZ-GUI minimized in Raspberry pi. I use Raspbian.
or is there a non UI Mode available for DECONZ?

Thanks
Florian

**Comment by jose-d** [comment]
non-UI mode is actually implemented in this binary `/usr/bin/deCONZ`.

**Comment by Smanar** [comment]
Minimized or headless ?

For headless
```
$ sudo systemctl disable deconz-gui
$ sudo systemctl stop deconz-gui
$ sudo systemctl enable deconz
```

**Comment by felker** [comment]
@Smanar is there a way to open the GUI minimized and have it automatically select Conbee instead of Raspbee? 

When I setup the headless to start automatically, it prevented me from opening the GUI.

**Comment by Smanar** [comment]
For minimze IDK, but even if at start deconz search for raspbee after 1 mn it switch for conbee itself.

**Comment by tebeso** [comment]
Found this ticket here in the rest-plugin area.. not sure why, but anyways.. i would also like to have a minimized startup function (not headless)
