### ISSUE TITLE
Ikea Tradfri motion sensors with Phoscon and connection to OpenHab (OH)

### ISSUE THREAD

**Issue by FrankH1** [dresden-elektronik/deconz-rest-plugin#3417]
I’m running OH 2.5 on a Raspi Pi. A Conbee II stick is connected to the Pi to deal with a bunch of Zigbee devices and sensors. When I started to integrate Tradfri motion sensors I did run into some unexpected problems and want to share/discuss the findings here. (Admins please feel free to move the topic into an appropriate place (probably phoscon?) or close)

The motion sensors are used for 2 purposes – they trigger in OH alarms, when a movement is spotted in the empty house and a few of them additionally control lights directly in the Phoscon app. Once everything was integrated and tested I spotted that the sensors are sometimes “blind”. After a while they reacted again and showed the expected behavior. I did find a comment on github, but  the proposed solution was way too complex for my understanding, at least I understood that there is something in the software/firmware and I stopped to search my Zigbee-radio coverage. Did some more tests and measurements and found out the following approach:
1)	Sensors used in the Phoscon app to control lights
The Phoscon app allows to control lights directly by sensors. You can define in a profile the brightness when movement is detected and 3 levels of brightness after movement at different times. Let’s name those durations after movement T1, T2, T3.
It turns out, that the Phoscon app is triggered by the first movement and assumes movement for the period of T1 (so whether there is movement or not it shows an active state). Once the duration of T1 has passed the sensor is “blind” for 90 sec. The lights follow correctly the settings in the profile. So if e.g. you set T1=10sec (1.dimming) T2=30sec (2. dimming) T3=1min (turn-off) and you move into the controlled area then the following happens – the light turns on if you enter the area, then after 20sec (10 sec assumed movement + T1) is the first dimming; after 40sec is the 2. dimming and after 1:10 the light turns off and you are in the dark – even if you move – because the sensor is blind for 90sec. Once I discovered that the solution was quite easy – you just need to make sure that T3 (the moment when you switch of) is > than 90secs and your dimming state at times < T1+ 90sec is sufficient to see your way until you are again spotted by your sensor and it turns the light to full power. The timers are not very flexible so I did choose T1=10sec (60%), T2=1min (30%) and T3=2min (turn off). This works quite stable now and no one is forced to walk in a dark smarthome.
OH gets the status from the phoscon/deconz app so you get an “active” from the first movement for the duration of T1. If you trigger something from the first movement that’s ok – otherwise you need to find a workaround. The inbox discovers 2 things with the profile name – so the phoson app seems to create a virtual device. One thing seems to be just an “or” of the 2 movements (named “VPIR “& RuleName; the other thing is a numerical range of values and seems to reflect the status (0=off; 1=dimm1; 2=dimm2 and is named “FSM_STATE “&RuleName - not sure if there was a 3rd value ). Both may help in additional programming.
2)	Sensors only used for alarm purposes
For those sensors there is no special configuration necessary/needed in phoscon/deconz. Although they are identical (all tradfri, all the same firmware) they behave differently. Permanent motion is not spotted as well, but they are shown as active for 1 min (from the beginning of the movement independently on further movement). Once the minute has passed they turn the state to not moving and have a blind time of 30 sec. Again, if you just use a rule triggered by the change to on/active then that should be ok, otherwise you need to put some more effort in it.

So whats the difference between the 2 cases?
a)	The obvious difference between those applications will be the time the sensor is reporting an active/moving state. I guess the 1 min in case2 is the default, which is overwritten by phoscon with T1 once a profile is set.
b)	It can well be that the sensor is blind ~ the same 90 secs in both cases but I rather had the impression in the case of the profile it starts a bit after the first movement. 
Happy to get your comments/other solutions.

**Comment by Mimiix** [comment]
Hi @FrankH1 
Despite you _kinda_ provided info between the lines, i am closing this issue. The issue template is mandatory.

Closing this one.
