### ISSUE TITLE
Tuya TS0012 switches

### ISSUE THREAD

**Issue by bastshoes** [dresden-elektronik/deconz-rest-plugin#3424]
## Describe the bug

After upgrade to 2.05.85-beta Tuya TS0012 switches disappeared from the list. API is also do not show them. They are still joined to network and can be operated via DeconzGUI.

## Steps to reproduce the behavior

Install new version.

## Expected behavior

Switches should persist after upgrade.

## Screenshots

![image](https://user-images.githubusercontent.com/22978694/96265987-cb189e80-0fce-11eb-8577-53ef612eade9.png)
![image](https://user-images.githubusercontent.com/22978694/96266061-e4214f80-0fce-11eb-8f85-b3a5216e43d5.png)

## Environment

 - Host system: PC
 - Running method: Marthoc Docker container
 - Firmware version: 26660700
 - deCONZ version: 2.05.84
 - Device: ConBee II 
 - Do you use an USB extension cable: yes

**Comment by Smanar** [comment]
Hello how many device have you (To know the database size for log)
And if you haven't too much of them can you share the log at startup ? when the code parse the database.

Was wired siwtch ?

wich one version have you before ?

**Comment by bastshoes** [comment]
Hello. Yes this is wired switch without netural line. And yes I was on. 84

**Comment by Smanar** [comment]
ok, so it s my fault sorry.

Your device is a "light" but declared as sensor by itself.

I have some problem because lot of tuya "sensor" are reconized as "light" so I have decreased the "detection tolerance", and your device haven't succed with it.

**Comment by bastshoes** [comment]
Yes, Tuya devices are tricky. Do need any additional info for establishing right criteria?

**Comment by Smanar** [comment]
No it s ok, I know exactly the problem.

I think I will "autorise all" and use a "blacklist" to prevent special device.
The problem is I don't know if there more "zigbee compliant" device or the reverse ^^.

You want the correction for your installation ? But I don't thing you can recompile the code on your side ?

**Comment by bastshoes** [comment]
I'll wait for release. Thanks.
