### ISSUE TITLE
Deconz showing two devices

### ISSUE THREAD

**Issue by silent-303** [dresden-elektronik/deconz-rest-plugin#3432]
Hi there,

my deconz showing two devices (Conbee II & RaspBee) but there is only Conbee II plugged in.

When starting it takes some tome to get a connection. Any idea how i can get rid off the "false" RaspBee?

Thanks alot
![Deconz](https://user-images.githubusercontent.com/55759103/96339806-2910b900-1097-11eb-8335-c1049a379b82.png)

**Comment by silent-303** [comment]
Also asking two times for a firmware update which i confirmed already-
![Firmware](https://user-images.githubusercontent.com/55759103/96340007-6cb7f280-1098-11eb-8094-60073b3e7905.png)


Conbee II has 26660700

**Comment by Smanar** [comment]
I have it too, I think it s something normal.

**Comment by SwoopX** [comment]
And for that reason, I'm closing this one.
