### ISSUE TITLE
Zenismart ZigBee Smart Curtain Switch ZW-EC-01

### ISSUE THREAD

**Issue by psaggiomo** [dresden-elektronik/deconz-rest-plugin#3438]
## Device

- Product name: ZigBee Smart Curtain Switch ZW-EC-01
- Manufacturer: Feibit Co.Ltd
- Model identifier: FB56+CUR17SB2.2
- Device type:
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/51875380/96361977-5ce8ee80-112a-11eb-8c9c-e1fa8bf34bc4.png)

![image](https://user-images.githubusercontent.com/51875380/96362000-830e8e80-112a-11eb-923a-a7e575f4c663.png)

**Comment by Smanar** [comment]
And this device don't work natively ?

**Comment by psaggiomo** [comment]
> And this device don't work natively ?

In Home Assistant works only Close and Stop button. Doesn't work Open button.

**Comment by Smanar** [comment]
Ha yes.
You are not in this situation  > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3269 ?
Can you make the same test pls ?

**Comment by psaggiomo** [comment]
Hi,
the issue is like #3269 .

The Current Position is Grayed.

![image](https://user-images.githubusercontent.com/51875380/96554300-a108fa00-12b6-11eb-9d51-169fa703fe3e.png)

**Comment by psaggiomo** [comment]
- cover.close_cover: nothing
- cover.close_cover_tilt: nothing
- cover.open_cover: works
- cover.open_cover_tilt: nothing
- cover.set_cover_position: works
- cover.set_cover_tilt_position: nothins
- cover.stop_cover: works
- cover.stop_cover_tilt: nothing
- cover.toggle: works to open
- cover.toggle_cover_tilt: nothing

**Comment by Smanar** [comment]
OK so your device don't support "set position" command, it just use "open" and "close ?

**Comment by psaggiomo** [comment]
Yes, I think so.

**Comment by Smanar** [comment]
Ok I have added it to my tuya fork (only 1 line edition) > https://github.com/Smanar/deconz-rest-plugin/commit/53b691b4030773e6e3eacebc9e4e8d566109543f

Do you have an unix machine to test it ?

**Comment by psaggiomo** [comment]
I have a NAS Synology with Deconz in Docker e Home Assistant in Docker.

**Comment by Smanar** [comment]
Ok so it mean "no" ? ^^

No problem, the code will be in next version I think, but without test, you can have to wait for the next one (if I m wrong)

**Comment by psaggiomo** [comment]
No problem, I'll wait the next distribution to test. Thank you.

**Comment by ynnovate** [comment]
hello
also interested to test and help

**Comment by Smanar** [comment]
Hello, do you have an unix machine to compile the code to test it ?

It s is on my fork, tuya branch, I can give you the command to use if you have the good OS.

**Comment by theslash** [comment]
Just to add here, I have a shutter controller which identifies as "Heiman | TS0302" and behaves just like this here.
I have a headless setup, where I cant control it, it just is a light where I can set the brightness.

**Comment by Smanar** [comment]
@theslash and same than them, it don't work if you use "bri" or "lift" ?

**Comment by theslash** [comment]
> @theslash and same than them, it don't work if you use "bri" or "lift" (even those field are present in the json) ?

Yes, nothing happens when I change any of these values.
I'm on 2.05.84 / 26660700 by the  way.

I would suspect there is some kind of calibration needed for the controller. could that be the case?

**Comment by Smanar** [comment]
Ha yep, it s possible too, you haven't the device documentation ?

Some tuya device need calibration to have the set position feature working, but other don't have them at all.

Exemple https://blakadder.com/zemismart-zm25tq/ this one use a 433 mhz remote to set min/max position.

If when you use open and close, the device stop itself at good position, you have lot of chance your device don't need calibration.

If you are in the same situation than other I need you device manufacture name, the model id is useless for tuya.

**Comment by theslash** [comment]
No there is only a leaflet with notes how to use the "smart life" app to control it.
It works perfectly with the buttons on the device. 
I have this device:
https://www.aliexpress.com/item/4000311591651.html?spm=a2g0s.9042311.0.0.39664c4ddQHTXC

Seems to be a tuya device if I can trust the listing.
Is it normal that it only shows up as a light in the deconz web frontend? I have a brightness slider there but it does nothing.

**Comment by Smanar** [comment]
Haaa, I m so stupid ^^, haven't see the word "switch" ^^

So yes, on the switch you have Neutral (N) + phase (L) + up (L1) + down (L2) ?
So no set position command.

So yes I need the manufacture name to add your device.

You still have the "lift"/"bri" field (so still the brightness slider) but the api will convert them to "open" / "close".
And yes phsocon don't manage covering for the moment, better to use your third app.

**Comment by theslash** [comment]
Ok, to get the manufacturer I need the Deconz gui, right? will have to setup this first, my setup is headless.

**Comment by Smanar** [comment]
You have it too in the device JSON (for all device visible in the API)

**Comment by theslash** [comment]
{
  "etag": "e1207f233b15186ee4bf15e8d550760e",
  "hascolor": false,
  "lastannounced": "2020-10-23T10:23:46Z",
  "lastseen": "2020-10-23T17:32Z",
  "manufacturername": "Heiman",
  "modelid": "TS0302",
  "name": "Window covering device 11",
  "state": {
    "bri": 127,
    "lift": 50,
    "on": true,
    "open": true,
    "reachable": true
  },
  "swversion": null,
  "type": "Window covering device",
  "uniqueid": "84:2e:14:ff:fe:fd:9f:bb-01"
}

Hope this helps.

**Comment by Smanar** [comment]
Ok so bad luck, you have the bad manufacture name, not your fault, but we have this problem every 2 days.

By hazard, it s not your device ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3269

But you have a different MAC adress, if you have time, can you make a second inclusion ? and hoping for the good manufacturename.

**Comment by theslash** [comment]
;-DD really? 
yes  #3269 seems to have the same problem as me and at leas the same model number.
I have a second one here, I will have to set it up and try if it differs.

**Comment by theslash** [comment]
Ok, so I had a view at the other issue and PR.
If my manufacturer would be "_TYZB01_dazsid15" then this code should make it work, right:
(from the pull request : https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3316/commits/3a94d2f19febaa09ceeb9456ca1e5ec58d938081)

    //Some device don't support lift, but third app can use it
    if (hasLift)
    {
        if (taskRef.lightNode->manufacturer() == QLatin1String("_TYZB01_dazsid15"))
        {
            hasLift = false;
            hasOpen = true;
            if (targetLiftZigBee > 0)
            {
                targetOpen = false;
            }
            else
            {
                targetOpen = true;
            }
        }
    }

Is there a a way to integrate this device too?

**Comment by Smanar** [comment]
Yep, i just need to add your manufacture name, if you haven't the same device.

But to obtain it, you can re-include the device and hoppping to have the good one, or install deconz with the graphical environnement on another machine and switch the conbee the time to have it.

**Comment by theslash** [comment]
Ok sorry, I think I don't understand what you mean.
I removed the device, and readded it, but it changed nothing.
Can I change the manufacturer of my device with the GUI?

**Comment by Smanar** [comment]
No it s written on the device, but you can read it.
On cluster 0x0000 (basic cluster), attribute 0x0004, you probably need to press the button "read", and make the device awake if it s a sleeping device.

**Comment by psaggiomo** [comment]
> Ok so it mean "no" ? ^^
> 
> No problem, the code will be in next version I think, but without test, you can have to wait for the next one (if I m wrong)

Hi, is the code included in v2.5.88?

**Comment by Smanar** [comment]
Nope, too sensible, 88 is a stable.
All the tuya stuff will be in the beta in some day if there is no problem.

**Comment by psaggiomo** [comment]
Hi. I have installed 2.06 and now it works!
The only problem is the current position grayed and is ever 100.
![image](https://user-images.githubusercontent.com/51875380/99294832-e46a7000-2844-11eb-9d94-31fd6bc368bf.png)

**Comment by Smanar** [comment]
I think it mean the device don't support "set position".
But the returned value in websocket is always 100 too ?

**Comment by psaggiomo** [comment]
> I think it mean the device don't support "set position".
> But the returned value in websocket is always 100 too ?

Yes, always 100.

**Comment by Smanar** [comment]
And it cause problem on third app ?

**Comment by Smanar** [comment]
Haaa yes, your device probably don't use the cluster 0x0102 for return because the attribute used 0x0008 is grayed for you.
So I think it use the cluster 0x0006, can you check the attribute value 0x0000 in the cluster 0x0006 when the device is open or closed.

The deconz code update only "on" and "open" with this cluster.

**Comment by psaggiomo** [comment]
Hi, the 0x0006 il grayed also. I see only 0x0000, 0x0007, 0x0010, 0x0011, 0x0012, 0x0013 and 0x0017, but the values do not change.

**Comment by Smanar** [comment]
Nope the cluster 0x0006 "on/off", it s possible your device send the notification using this cluster instead of the 0x0102 "covering", because it don't need position management.
The cluster 0x0006 is not present on other covering.

**Comment by psaggiomo** [comment]
Yes. I confirm.

**Comment by Smanar** [comment]
Ok so I can probably do something.

Not possible prevent the "bri"/"lift" field creation, but I can update the value in same time than "on"/"open".
BTW the "lift"/"bri" is not updated, but the "open" is or only "on" is updated ? (in the device json)

Have you something to compile and test the code ?

**Comment by HB1300** [comment]
Hi there,
I also have this relay and would change the "physical_close_limit_lift_cm (id: 0x0001)" is that possible?
so that I can take into account the different lengths and thus when I go to 50% it also opens up to halfway

also the open and closed button is swapped in HA - if it is fully open I can only press the open button that close button unenabeled - can i change that?

please help - thank you

**Comment by Smanar** [comment]
>I also have this relay and would change the "physical_close_limit_lift_cm (id: 0x0001)" is that possible?

Depend of device, but here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3438#issuecomment-728255112 it seem this attribute is grayed = not available.

>also the open and closed button is swapped in HA - if it is fully open I can only press the open button that close button unenabeled - can i change that?

ATM using HA, the only way is using "custom widget" (Not sure for name I m not using HA), to use custom requests.
Will be possible soon using DDF, but need to wait too HA use the last deconz version, The next deconz stable is planned around the 15 December

**Comment by HB1300** [comment]
hi smanar,
Thank you for your answer
But is there a possibility to reduce the opening / closing time of this relay?
because not all curtains are the same length

**Comment by HB1300** [comment]
I cannot choose this function in HA - (Time calibration for Tuya coverage - 0xf003)
Is there another way to access / choose this?

**Comment by Smanar** [comment]
How you need to do from the device documentation ?
There is a calibration procedure ? A special remote ?

**Comment by HB1300** [comment]
hi,
I have a new hw here I can select the cluster F001 via demoz but unfortunately not via HA can you help me here?

https://github.com/home-assistant/core/issues/46146#

and can I do a firmware update with the old hardware?

thank you for your help
best regards
harald

**Comment by Smanar** [comment]
Hello
- what is demoz ?
- this device don't have cluster 0xf001 ?
- wich one hardware, gateway or device ?

**Comment by HB1300** [comment]
https://githubmate.com/repo/dresden-elektronik/deconz-rest-plugin/activity
sorry ich meine deconz 

in deconz i hafe this cluster but not in HA 

HW: TS130F Gateway; HA

**Comment by Smanar** [comment]
But on your link it's 0xEF00 ? Its the tuya cluster.
You don't make mistake with the attribute 0xf001 on the covering cluster ? You can use the "calibration" request using the API, but not sure this command is visible on HA.
But not all devices support this attribute, if you have the GUI, better to make a try first with deconz.

How you want to update the device firmware ? tuya give firmwares for it ?

>but even if I calibrate it in deconz - if the supply is gone, the calibration reset to the old value

Ha ? this is a new issue, the calibration procedure is working, but not keep in memory ? you have something writen on the documentation ? you don't forget to change again the calibration state ?
