### ISSUE TITLE
Issues with Heiman TS0503A RGB Strip Controller

### ISSUE THREAD

**Issue by DerpyDoom** [dresden-elektronik/deconz-rest-plugin#3456]
Hi Everyone, this is my first post in the deconz-issue page so please don't be to harsh if I did something wrong.

I have purchased a "cheap" 7€ Zigbee RGB LED Strip Controller which I can pair successfully with deCONZ.
Now comes the problem, the only thing I can do is pair it to the system but I cannot change the Color or the Brightness of the Controller. I am also able to turn the Strip on and Off but only sporadicly.

The Strip is also constantly on in Red when connected to the Controller. Did I do something wrong or is the Controller maybe a different type? Hope You guys can help me since the seller is only capable of the most broken english and doesn't understand me.

This is the controller I bought:: [Ebay](https://www.ebay.de/itm/TUYA-ZIGBEE-RGB-RGBW-RGBCCT-Led-Controller-5V-12V-24V-Stripe-Streifen-f-Alexa/184436891180?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20170511121231%26meid%3D9f28db45de20402a9ed05d6696e12d31%26pid%3D100675%26rk%3D2%26rkt%3D15%26mehot%3Dnone%26sd%3D373216570282%26itm%3D184436891180%26pmt%3D0%26noa%3D1%26pg%3D2380057%26brand%3DMarkenlos&_trksid=p2380057.c100675.m4236&_trkparms=pageci%3A5e38e1f9-12ec-11eb-ba9e-4ae4f1a6cdeb%7Cparentrq%3A46b6f48b1750a9c42de33ceefff6963c%7Ciid%3A1)

**Comment by Mimiix** [comment]
Hi @DerpyDoom 

I am closing this issue as you are not using a issue template. 

Please open a new one. However: you might want to open a device request. Follow the steps in the issue template. Use: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support as guidance.
