### ISSUE TITLE
Heiman TS0503A (Tuya Zigbee RGB LED Controller)

### ISSUE THREAD

**Issue by DerpyDoom** [dresden-elektronik/deconz-rest-plugin#3458]
## Device

- Product name: TUYA ZIGBEE RGB RGBW RGBCCT Led Controller
- Manufacturer: _TZ3000_c5drg1wn
- Model identifier: TS0503A
- Device type : Please remove all unrelated device types. 
  - Light
- deCONZ Version: 2.05.84 / 14.09.2020

## Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/6315513/96616083-6b89fe00-1302-11eb-8dd8-54c685c4f5c1.png)
![Screenshot_2](https://user-images.githubusercontent.com/6315513/96616085-6cbb2b00-1302-11eb-9fd2-bcad3b6647b9.png)
![Screenshot_3](https://user-images.githubusercontent.com/6315513/96616088-6cbb2b00-1302-11eb-978b-0af9706bc971.png)

**Comment by Smanar** [comment]
Hello, this device don't work natively ?

**Comment by DerpyDoom** [comment]
No it is not responding to color, or brightness changes. I am only able to sporadicly turn it on or off if I set the RGB values to Red.

**Comment by Mimiix** [comment]
Missing version information of current deconz version.

**Comment by DerpyDoom** [comment]
Sorry! I have not seen the version information required in the template.

Version: 2.05.84 / 14.09.2020

**Comment by DerpyDoom** [comment]
I just experimented a little bit, and by setting the Hue on "Move to Hue" to different values between 0-254 I am able to control all the colors that are in the led strip. But not with the interface.

![Screenshot_4](https://user-images.githubusercontent.com/6315513/96625919-156f8780-130f-11eb-8d40-309e648c995a.png)

**Comment by Smanar** [comment]
Ha perhaps a bug in reading color capabilies ?
Can you show the device JSON ?

**Comment by DerpyDoom** [comment]
> Ha perhaps a bug in reading color capabilies ?
> Can you show the device JSON ?

Could you tell me where I can find it? I'm quite new to under the hood stuff from deconz.

**Comment by Smanar** [comment]
On your third app if you have one ?
Else using directly the API https://dresden-elektronik.github.io/deconz-rest-doc/ ?

**Comment by DerpyDoom** [comment]
I do have a third party app, well system (Home Assistant) if it's possible with that. Otherwise I have to work with the api.

**Comment by Smanar** [comment]
Ok so I have asked, and it depend on deconz integration you are using ^^.

So yes the easier way is using the api

**If you are in local**
You just need an api key
`curl http://127.0.0.1:80/api/ -X POST -d '{"devicetype": "TestKey"}'`

And use the URL
`http://127.0.0.1:80/api/YOUR_API_KEY/lights`

**Comment by DerpyDoom** [comment]
Hey Smanar, since I'm using the deconz Home Assistant integration, which IP do I have to use?
Because the one where HassIO is running on is not reacting to port 80.

**Comment by Smanar** [comment]
For the ip and port, it s the same you are using for phoscon.

**Comment by DerpyDoom** [comment]
Finally managed to get the JSON You wanted. This is the Controller in question.

`{
      "etag":"9260ad2ad3aebb72f86454a5455b53a4",
      "hascolor":true,
      "lastannounced":null,
      "lastseen":"2020-10-24T01:25Z",
      "manufacturername":"_TZ3000_c5drg1wn",
      "modelid":"TS0503A",
      "name":"Color dimmable light 20",
      "state":{
         "alert":"none",
         "bri":25,
         "colormode":"xy",
         "effect":"none",
         "hue":0,
         "on":false,
         "reachable":false,
         "sat":254,
         "xy":[
            0.1166,
            0.798
         ]
      },
      "swversion":null,
      "type":"Color dimmable light",
      "uniqueid":"08:6b:d7:ff:fe:d3:63:ad-01"
   }`

**Comment by Smanar** [comment]
Ok, so congratulation, you have find a new "not zigbee compliant chinese stuff", cf https://github.com/Koenkk/zigbee2mqtt/issues/4020

>     Device only work with HS color mode
>     Able to turn it off with genOnOff: offWithEffect
>     Able to turn it on with genLevelCtrl: moveToLevelWithOnOff
>     Able to change color with lightingColorCtrl: moveToHue & moveToSaturation seperately
>     moveToHueAndSaturation does not work
>     Can't turn it on with any genOnOff command
>     No brightness control so far

Need to write a code part just for it ...

**Comment by DerpyDoom** [comment]
I'd love to have support for that, I also have some programming experience in C# but i doubt that this will help in this situation :D

The thing is there could be coming more issues with the same device since this is currently the cheapest available (6€ in my case), the others cost around 15€

**Comment by sonar98** [comment]
"5": {
		"etag": "d47e9d5b3db50b4459f4ed3e1bd203cc",
		"hascolor": true,
		"lastannounced": null,
		"lastseen": "2020-11-24T13:16Z",
		"manufacturername": "Heiman",
		"modelid": "TS0601",
		"name": "Color dimmable light 5",
		"state": {
			"alert": "none",
			"bri": 2,
			"colormode": "xy",
			"effect": "none",
			"hue": 65018,
			"on": true,
			"reachable": false,
			"sat": 127,
			"xy": [
				0,
				0
			]
		},
		"swversion": null,
		"type": "Color dimmable light",
		"uniqueid": "58:8e:81:ff:fe:db:7e:9a-01"
	}
