### ISSUE TITLE
Philips TV Firmware Compability + Phoscon

### ISSUE THREAD

**Issue by Z-Rick84** [dresden-elektronik/deconz-rest-plugin#3461]
Dear Forum-Members,

as there seems to be problems with some Philips-TV Firmwares (Ambilight+Hue) in combination with Phoscon / Conbee, I'd like to share my experience and gain the other user experiences here to complete a list of possibly configurations of Philips- and Phoscon/Conbee-Firmware to beware Users of not downgradable Updates.

This combination works fine for me:
**65OLED804 + TPM191E _ 001.001.114.005 (2019/11/11) + Phoscon (FW: 26330500 / Ver: 2.05.75 / 8.3.2020)**

Is there anyone, who uses a newer Philips-FW and can confirm, that it runs good aswell? Let's find out, which is the latest firmware, that still runs well with Phoscon.

Thank you for sharing.

### 2020
**Philips 2K20 85x5/8x5/9x5/9235/9435/9005**
- TPM191E _ 101.001.123.003 – Date: 2020/09/23 (? / not tested)
- TPM191E _ 101.001.079.005 – Date: 2020/08/03 (? / not tested)
- TPM191E _ 101.001.037.004 – Date: 2020/06/15 (? / not tested)
- TPM191E _ 101.000.226.007 – Date: 2020/05/04 (? / not tested)

### 2019
**Philips 2K19 73x4/7504/8x04/8x4/9x4**
- TPM191E _ 101.001.079.005 – Date: 2020/09/15 (? / not tested)
- TPM191E _ 001.004.100.001 UK only – Date: 2020/07/27 (? / not tested)
- TPM191E _ 001.004.100.000 – Date: 2020/07/01 (? / not tested)
- TPM191E _ 001.002.173.010 – Date: 2020/04/20 (? / not tested)
- TPM191E _ 001.002.173.008 – Date: 2020/03/04 (? / not tested)
- TPM191E _ 001.002.173.004 – Date: 2019/12/02 (? / not tested)
- **TPM191E _ 001.001.114.005 – Date: 2019/11/11 (Works / tested)**
- TPM191E _ 001.001.114.002 – Date: 2019/09/30 (seems to work / not tested)
- TPM191E _ 001.001.037.013 – Date: 2019/09/04 (seems to work / not tested)
- TPM191E _ 001.001.037.011 – Date: 2019/08/14 (seems to work / not tested)
- TPM191E _ 001.001.037.009 – Date: 2019/07/24 (seems to work / not tested)
- TPM191E _ 001.001.017.004 – Date: 2019/05/29 (seems to work / not tested)
- TPM191E _ 001.001.017.003 – Date: 2019/05/22 (seems to work / not tested)

### 2017-2019
**Philips 2K19 9104**
**Philips 2K18 73x3/7503/7803/8303/8503/8x3/9x3**
**Philips 2K17 6412/6482/7002/7502/8102/8602/9002**
_- TPM171E _ 107.001.132.000 – Date: 2020/06/29 (not working / tested)_
**- TPM171E _ 107.001.101.002 – Date: 2019/12/02 (seems to be the latest working firmware/ not tested)**
-TPM171E _ 107.001.038.000 – Date: 2019/06/26 (seems to work / not tested)
-TPM171E _ 107.000.239.001 – Date: 2019/03/27 (seems to work / not tested)
-TPM171E _ 107.000.230.000 – Date: 2019/03/11 (seems to work / not tested)
-TPM171E _ 107.000.222.001 – Date: 2019/03/04 (seems to work / not tested)
-TPM171E _ 107.000.163.002 – Date: 2018/11/26 (seems to work / not tested)
-TPM171E _ 105.001.002.084 – Date: 2018/12/20 (seems to work / not tested)
-TPM171E _ 105.001.002.075 – Date: 2018/10/04 (seems to work / not tested)
-TPM171E _ 105.001.002.017 – Date: 2018/09/04 (seems to work / not tested)
-TPM171E _ 105.001.002.006 – Date: 2018/06/28 (seems to work / not tested)
-TPM171E _ 105.000.215.003 – Date: 2018/05/30 (seems to work / not tested)
-TPM171E _ 105.000.197.013 – Date: 2018/05/18 (seems to work / not tested)
-TPM171E _ 105.000.159.034 – Date: 2018/04/04 (seems to work / not tested)
-TPM171E _ 105.000.159.006 – Date: 2018/02/26 (seems to work / not tested)
-TPM171E _ 003.001.012.000 – Date: 2018/09/17 (seems to work / not tested)
-TPM171E _ 003.000.246.005 – Date: 2018/06/18 (seems to work / not tested)
-TPM171E _ 003.000.240.000 – Date: 2018/05/21 (seems to work / not tested)
-TPM171E _ 003.000.208.000 – Date: 2018/02/09 (seems to work / not tested)
-TPM171E _ 003.000.173.001 – Date: 2018/01/08 (seems to work / not tested)
-TPM171E _ 001.002.177.000 – Date: 2017/11/13 (seems to work / not tested)
-TPM171E _ 001.002.176.000 – Date: 2017/10/27 (seems to work / not tested)
-TPM171E _ 001.002.171.000 – Date: 2017/10/16 (seems to work / not tested)
-TPM171E _ 001.002.167.001 – Date: 2017/10/06 (seems to work / not tested)
-TPM171E _ 001.002.161.000 – Date: 2017/09/18 (seems to work / not tested)
-TPM171E _ 001.002.159.000 – Date: 2017/09/06 (seems to work / not tested)
-TPM171E _ 001.002.089.005 – Date: 2017/06/29 (seems to work / not tested)
-TPM171E _ 001.002.089.001 – Date: 2017/06/09 (seems to work / not tested)
-TPM171E _ 001.002.035.013 – Date: 2017/05/11 (seems to work / not tested)
-TPM171E _ 001.002.035.010 – Date: 2017/04/25 (seems to work / not tested)
(Thanks, Mimiix!)

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3088

Contains some related info!

**Comment by unstressable** [comment]
55OLED754/12 with TPM196E_091.004.027.011 does not work. Also tried the latest from 30.10.2022
