### ISSUE TITLE
Empty devicelist on Rademacher Homepilot after Restart

### ISSUE THREAD

**Issue by silent-303** [dresden-elektronik/deconz-rest-plugin#3462]
I have a question about the Rademacher Homepilot:

When I close deCONZ and restart it, the Rademacher Homepilot deletes the associated scenes in the Homepilot. A question at Rademacher gave me the following answer:

I have feedback from development.

It is so that Phoscon does not conform to the original Hue Bridge.
In between, Phoscon delivers an empty device list via the API, whereupon we also remove these devices in the Homepilot.

You might have to ask Phoscon why this is so. This behavior does not occur with the original Hue Bridge.

Does anyone know about an "empty" device list "issue"?

## Environment
 - Host system: Raspberry Pi 3B+
 - Running method: Raspbian Buster latest
 - Firmware version: 26660700
 - deCONZ version: 2.05.84
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
Do you mean deCONZ?

**Comment by silent-303** [comment]
Ups, sorry yes. Corrected :)

**Comment by ebaauw** [comment]
I think this is tye issue of the `/lights` resources missing after deCONZ startup?  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2473.
