### ISSUE TITLE
I can't add Aqara Motion / Door sensor

### ISSUE THREAD

**Issue by Galiwyx** [dresden-elektronik/deconz-rest-plugin#3463]
Hello,

I switched from Raspebrry + Conbee II to a server on Docker (UnRAID).

I added without problem 2 Aqara Temperature Sensor. Works perfectly.

I have some trouble to add Aqara Motion Sensor and Aqara Door Sensor. I tried eveything, long / quick press on reset button. 

On Phoscon App, sensor isn't found : 

![image](https://user-images.githubusercontent.com/206181/96731592-b6198200-13b7-11eb-9d9c-8043cc013dc6.png)

This is my node :

![image](https://user-images.githubusercontent.com/206181/96731627-c3367100-13b7-11eb-9255-78f633d993ba.png)

I don't know what is 0xC43B and 0x1DAB.

Update : when I push the button of the Aqara Motion sensor, a green light blinks on deCONZ UI for 0xC43B

**Comment by Smanar** [comment]
The 0x1DAB is a chinese sensor, perhaps tuya ? Realy generic brand, you can have more information if you clic on the second circle, and check in basic cluster, but I think the field will be empty. If you show the cluster list can be helpfull too.

For the Xiaomi sensor yes, you have some problem, the inclusion is not finished in the API, but in deconz too.

As you have the GUI, something you can try
1 - set phoscon in permit join again (add new sensor)
2 - on deconz clic on the first circle and resend command (read descriptor for exemple) up you have the second circle
3 - when you have the second circle, clic on it, go in basic cluster (0x0000) and read basic attribute again (the button "read")

Problem, thoses sensors are sleeping, si in same time you make a command in deconz you need to wake up the device (short press on button for exemple)

Or make the inclusion normaly and after the blink press shortly the button every second to prevent the device go to sleep.

**Comment by Mimiix** [comment]
Hi,

Closing this issue. Not using the template.

**Comment by Galiwyx** [comment]
> 
> 
> The 0x1DAB is a chinese sensor, perhaps tuya ? Realy generic brand, you can have more information if you click on the second circle, and check in basic cluster, but I think the field will be empty. If you show the cluster list, can be helpfull too.
> 
> For the Xiaomi sensor yes, you have some problem, the inclusion is not finished in the API, but in deconz too.
> 
> As you have the GUI, something you can try
> 1 - set phoscon in permit join again (add new sensor)
> 2 - on deconz clic on the first circle and resend command (read descriptor for exemple) up you have the second circle
> 3 - when you have the second circle, clic on it, go in basic cluster (0x0000) and read basic attribute again (the button "read")
> 
> Problem, thoses sensors are sleeping, si in same time you make a command in deconz you need to wake up the device (short press on button for exemple)
> 
> Or make the inclusion normaly and after the blink press shortly the button every second to prevent the device go to sleep.

Thank you @Smanar, I resetted the gateway before I saw your message and everything is okay now !
