### ISSUE TITLE
ETI/Commercial Electric downlights detected as Color dimmable instead of Color temperature

### ISSUE THREAD

**Issue by mcalderin** [dresden-elektronik/deconz-rest-plugin#3464]
After connecting ETI downlights, the API returns that they're color dimmable (which makes downstream apps like Phoscon) show the RGB selector instead of a simple color temperature selector.

This is reproduceable whenever I add a new ETI downlight of the same model (T62).

In Phoscon, you can see the RGB option, but the color temperature can not be chosen.

![image](https://user-images.githubusercontent.com/73031696/96751525-4bf2e400-139b-11eb-801f-b2f38085bf6e.png)

Host is a RaspBee II v2.05.84 w/ firmware 26610700.  No other USB or serial devices are connected.

Saw comments from @ebaauw in Discord, suggesting these issues be added here and that they can be addressed through a whitelist.

**Comment by ebaauw** [comment]
Please use the template for asking device support, and include the GUI screenshots.  We need that info to verify that this is indeed the case, and to know how to whitelist the device.

**Comment by mcalderin** [comment]
Sorry, I did try to follow the template.

Here's a GUI screenshot showing the light model info.

![image](https://user-images.githubusercontent.com/73031696/96803688-f6d6c280-13da-11eb-8cda-aa274a2ca354.png)

If there's anything else I can provide, please let me know.

**Comment by mcalderin** [comment]
Same thing is happening w/ Eaton lights.  Here are some more screenshots.

![image](https://user-images.githubusercontent.com/73031696/96816774-e8dd6d80-13eb-11eb-8ea9-ef1b95fcb385.png)

![image](https://user-images.githubusercontent.com/73031696/96816802-f72b8980-13eb-11eb-8bd5-66b04e90c9bf.png)

![image](https://user-images.githubusercontent.com/73031696/96816823-027eb500-13ec-11eb-90a6-9ebe3f7bf8f5.png)

**Comment by Mimiix** [comment]
As @ebaauw Asked: Please follow the template.
Closing.
