### ISSUE TITLE
Deconz lost devices

### ISSUE THREAD

**Issue by jbustdel** [dresden-elektronik/deconz-rest-plugin#3468]
Hello,

Yesterday I added a USB Conbee II version 2.05.84 to my rasperry 3+ that runs HassOS 4.13 with Home Assistant 0.116.4

I installed Deconz plugin and seamlessly paired the gateway. The selected channel is 25.

I started incorporating 1 Mijia WSDCGQ01LM temperature and humidity sensor and 4 Mijia RTCGQ01LM motion sensors. The pairing completes without problems, and the 5 sensors appear in Phoscon and Deconz,

The problem occurs if I disconnect the raspberry from the power supply or upgrade the system, as the motion sensor nodes are disconnected and I have to pair them again. In the Phoscon interface they appear but do not detect movement, but in Deconz they disappear directly.

Am I doing something wrong? Is it normal that I have to pair them again?. Sorry but I recently new on this system.

Thank you.

**Comment by Mimiix** [comment]
Closing this issue as it is not using the template.
