### ISSUE TITLE
Philips Hue Motion Sensor don't upgrade

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#3469]
Hi, 

I've downloaded Philips Hue motions sensor otua files and added them to Deconz.
Using OTAU Plugin I query the sensor(s) and they recognise firmware file converter -zigbee by deconz.
File Sensor-ATmega_6.1.1.27575_0012.sbl-ota
Update starts but stops in the middle and falls back to either queued or Idle.

This is what I see:
![Screenshot 2020-10-22 at 12 21 21](https://user-images.githubusercontent.com/45151934/96858883-1f090480-1461-11eb-8962-04b543a7f91f.png)

Stauts been stuck like this for about an hour or so, no new progress.
Motion sensor current firmware

![Screenshot 2020-10-22 at 12 22 55](https://user-images.githubusercontent.com/45151934/96859082-60011900-1461-11eb-9092-b0b473c95de4.png)

DeConz version 2.05.86
Conbee I firmware 26390599
Running on windows 2019 server

Any ideas?

**Comment by Mimiix** [comment]
You need them stay awake! :) 

Next time, use the template please (:

**Comment by PrimaryInc** [comment]
Okay. Thanks :)
