### ISSUE TITLE
Rules: Implement put/post to external ressources

### ISSUE THREAD

**Issue by ujanzen79** [dresden-elektronik/deconz-rest-plugin#347]
I am very in font of the current progress; also for the contributions of many members here.

in regards to outbound communication, I personally realize some complexity which I would like to get some ease on.

I was checking out the websocket functionality and think it is great; however in my setup, getting in a websocket connection does need additional coding to implement with openhab2. I would have to parse on all the events the deconz is transferring, setting up new items and routines to trigger on changes notified by deconz for a specific item.

It causes another point of failure and much effor (scripts, ws connection), which would add complexity in setup.

I would like to reduce the ammount of software needed to transfer information. 

My question would be:
Would it be possible to make the rule engine open up for posting/putting actions to external ressources with http?

e.g. openhab2 allows to change items by using rest api POST/PUT method.

would it be possible to open rules engine to be able to post/put to external ressources (along with http headers?) e.g.;

```
{
    "actions": [
        {
            "address": "http://xxx:8080/rest/items/xxx",
            "body": "OFF",
            "method": "POST"
        }
    ],
    "conditions": [
        {
                "address": "/sensors/4/state/presence",
                "operator": "eq",
                "value": "true"
        }
    ],
    "name": "REST to OH"
}
```

currently, it is doing same as the hue api, responding:

```
[
    {
        "error": {
            "address": "http://xxx:8080/rest/items/xxx",
            "description": "Rule actions contain errors or an action on a unsupported resource",
            "type": 608
        }
    }
]

```
Your advice and help is very much appreciated.

thank you,
Uwe

**Comment by manup** [comment]
Absolutely it's already on the wish list but no ETA yet.
