### ISSUE TITLE
Problem Mijia RTCGQ01LM Motion Sensors

### ISSUE THREAD

**Issue by jbustdel** [dresden-elektronik/deconz-rest-plugin#3473]
Hello,

Yesterday I added a USB Conbee II version 2.05.84 to my rasperry 3+ that runs HassOS 4.13 with Home Assistant 0.116.4

I installed Deconz plugin and seamlessly paired the gateway. The selected channel is 25.

I started incorporating 1 Mijia Temperature and humidity sensor, 4 Mijia RTCGQ01LM motion sensors, 1 Mijia Light Sensor and 3 Mijia Door Sensor. The pairing completes without problems, and the 9 sensors appear in Phoscon and Deconz,

The problem occurs if I disconnect the raspberry from the power supply or upgrade the system, as only the motion sensor nodes are disconnected and I have to pair them again. In the Phoscon interface they appear but do not detect movement, but in Deconz they disappear directly.

Am I doing something wrong? Is it normal that I have to pair them again?. Sorry but I recently new on this system.

Thank you.

## Describe the question or issue you are having

Mijia RTCGQ01LM Motion Sensors disappears fron Deconz  in this situations:

- Power off and on Raspberry.
- HassOS o Home Assistant System Update.
- Deconz Plugin Update.

## Screenshots

![image](https://user-images.githubusercontent.com/72611008/96910408-bf7e1980-149f-11eb-9d22-7eeefa0f646a.png)

## Environment

 - Host system: (Raspberry Pi)
 - Running method: (Home Assistent deCONZ Add-on)
 - Firmware version: (26660700)
 - deCONZ version: (2.05.84)
 - Device: (ConBee II)
 - Do you use an USB extension cable: No
 - Is there any other USB or serial devices connected to the host system?: No

### deCONZ Logs

No avalible
## Additional context

The only solution for now, is reset de Motion Sensor to come back.

**Comment by Mimiix** [comment]
You are missing routers in your network.  Xiaomi mijas tend to drop off once they are directly connected to the coordinator and if there are not routers.

**Comment by jbustdel** [comment]
> You are missing routers in your network. Xiaomi mijas tend to drop off once they are directly connected to the coordinator and if there are not routers.

And what kind of router can i introduce?. Thanks.

**Comment by Mimiix** [comment]
Should be fine, but others complain about that one. The goal is a healthy mesh.

**Comment by jbustdel** [comment]
Is there any updated list?.  Thanks.

**Comment by Mimiix** [comment]
Anything that is on 220V :)

**Comment by Smanar** [comment]
Hello,
How many time the power off ?
You loose them too, if you just done a reboot ?
Only the same device and all of them ?

**Comment by jbustdel** [comment]
> Hello,
> How many time the power off ?
> You loose them too, if you just done a reboot ?
> Only the same device and all of them ?
> 
> And BTW the device disapear in deconz ? No node at all ?

Hi,

The problem is in any case the raspbeerry is out of energy, in deconz's update or Os update. In hassio's reboot all is ok. the loss of devices is random, although motion sensors seem more prone. In deconz some nodes disappear completely and other nodes appear but without connection.

I think xiaomi devices go into sleep mode when they lose network and are not incorporated in any way once reset, only by resetting the sensor. In that case, the device is directly re-incorporated without having to be added.

**Comment by Smanar** [comment]
>I think xiaomi devices go into sleep mode when they lose network and are not incorporated in any way once reset, only by resetting the sensor. In that case, the device is directly re-incorporated without having to be added.

Exactly, they can wait 1 hour before sending  a report, so they can be "unreachable" during this time, without connexion, it s normal.

But not normal node disapear, even if they leave the network, or if the API filter them (because a bug), they are still in the GUI.

**Comment by Jaguaza** [comment]
I join this error.

Problem: some device cant not persistent after restart deconz container

Homeassisant Version: 0.116.4
Deconz Firmware:  26660700
Addons Version: 6.4.1
Purchase Date: 12/10/2020

Item:

I have 7 Hue bulbs, 6 Xiaomi temperature sensors, 10  xiaomi magnetic door / window, 2 flood sensors

Only xiaomi magnetic door / window nodes disappear.

Log:
[log.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5432734/log.txt)

**Comment by Smanar** [comment]
BTW what is exactly the "zombie mode" in deconz ?

**Comment by Jaguaza** [comment]
> So they are marked as "unreachable" but are still present on deconz (the GUI, if you have it) ?
> 
> BTW what is exactly the "zombie mode" in deconz ?

I don't know what is zombie mode. 
In UI it appears but does not update the status. 
In deconz nodes disappear after reboot. 
In deconz it is not that they appear disconnected, it is that they simply are not.

**Comment by jbustdel** [comment]
In the end, I went to ZHA and zero problems. Now I can update, shutdown and reboot and all devices come back quickly.

**Comment by Jaguaza** [comment]
> In the end, I went to ZHA and zero problems. Now I can update, shutdown and reboot and all devices come back quickly.

ZHA???

**Comment by Jaguaza** [comment]
I don't know, here we are reporting an error and nobody checks what is happening. Trust deconz, but maybe it's time to look at other alternatives and return my conbee2

**Comment by jbustdel** [comment]
Zigbee Home Automation. It's a Hassio'integration. Deconz it's too difficult to understand. In ZHA only install integration, pair devices and go. Conbee 2 is compatible.

**Comment by Jaguaza** [comment]
Thanks, we will have to go getting other alternatives, a shame that we also talk about conbee and then lose the nodes after a restart and do not worry about looking why this happens.

**Comment by jbustdel** [comment]
Try ZHA, for me its ok now. If you have problems with Xiaomi devices, ask me, if I cant i hep you. The problem is initial pair, then all is ok.

**Comment by Jaguaza** [comment]
> Try ZHA, for me its ok now. If you have problems with Xiaomi devices, ask me, if I can i help you. The problem is initial pair, then all is ok.

Thank you

**Comment by joaoubaldo** [comment]
I am having the same issue, with Xiaomi motion sensors disappearing after reboots and so on. This makes the sensor network too fragile. Looks like some sensors tend to disconnect indefinitely if they lose connectivity with the parent node for a while.

**Comment by Smanar** [comment]
>Looks like some sensors tend to disconnect indefinitely if they lose connectivity with the parent node for a while

Yep Xiaomi do that, but it need somes hours for that, generally if device disapear after a reboot it s mean the inclusion is not finished.

**Comment by Jaguaza** [comment]
> Yep Xiaomi do that, but it need somes hours for that, generally if device disapear after a reboot it s mean the inclusion is not finished.

The problem that having the device running for several hours, you reboot and the node disappears.  But it is not xiaomi's problem, it is deconz's problem since zha and zigbee2mqtt, this does not happen.  I expected @manup to give a solution, but it never comes.

**Comment by jbustdel** [comment]
With ZHA integration, no problems at all. Works perfect without issues.

**Comment by Smanar** [comment]
> In the Phoscon interface they appear but do not detect movement, but in Deconz they disappear directly.

Ha ok, I have bad read, you mean the device disapear in deconz itself ? no node at all ?

**Comment by Jaguaza** [comment]
> > En la interfaz Phoscon aparecen pero no detectan movimiento, pero en Deconz desaparecen directamente.
> 
> Ja, está bien, he leído mal, ¿quieres que el dispositivo desaparce en la propia desconcisión? ¿ningún nodo en absoluto?

The problem is that the node disappears from deconz after a reboot and never comes back.

**Comment by MattWestb** [comment]
deCONZ have problem with direct chields can / is disappearing.
If having some routers its still happens but the network is working as one mesh network that is not doing without routers.
In Z2M and ZHA Rasb/CornBee have problem getting LIQ from direct connected childs and its well documented in both. I think the neighbor table is bad implemented in the router part of the firmware.

**Comment by SwoopX** [comment]
Solution:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues
