### ISSUE TITLE
Aqara Temperature Sensor not reachable

### ISSUE THREAD

**Issue by dpmworld** [dresden-elektronik/deconz-rest-plugin#3477]
Hi all,
I found my Aqara Temperature/Humidity/Pressure sensor not working anymore and being in "Not reachable" state sinca last night.
I did 2 changes:
1) deconz upgrade from 2.05.80 to 2.05.86 (and conbee ii firmware upgrade)
2) added another Mijia Temperature/Humidity sensor.

From what I can see, the Aqara sensor has been identified as a mains operated device instead of a battery unit.
![image](https://user-images.githubusercontent.com/52251796/96969222-70bd9780-1512-11eb-8aea-cf28e8b2f87e.png)

Any help in debugging is appreciated

**Comment by Mimiix** [comment]
Closing the issue as not using the template.
