### ISSUE TITLE
Conbee2 manuel firmware Update is not working

### ISSUE THREAD

**Issue by tigertim08** [dresden-elektronik/deconz-rest-plugin#3478]
Hello everyone, I've been trying for a while to update the firmware of my Conbee2, unfortunately without success so far. The WebUI shows me that the update was successful, but the overview page still shows me the old one and offers me to do the update again. Then I tried it manually and unfortunately that doesn't work either. Here I get an error message "failed reset".

Does anyone have any idea what else I can try
![2020-10-23_09-37-27](https://user-images.githubusercontent.com/24661102/96970867-99469100-1514-11eb-9cbd-f60275b23323.png)
?

I tried the update on a Windows computer.

**Comment by Mimiix** [comment]
Closing this issue as not using the template.
