### ISSUE TITLE
Commercial Electric Smart LED Downlight T62

### ISSUE THREAD

**Issue by mcalderin** [dresden-elektronik/deconz-rest-plugin#3493]
## Device

- Product name: Commercial Electric Smart LED Downlight T62
- Manufacturer: ETI
- Model identifier: Zigbee CCT Downlight
- Device type:
  - Light

## Screenshots

![image](https://user-images.githubusercontent.com/73031696/97061391-b30fc480-1564-11eb-9e6c-e94c2605fa05.png)
![image](https://user-images.githubusercontent.com/73031696/97061325-7fcd3580-1564-11eb-89e4-9962bd18d384.png)
![image](https://user-images.githubusercontent.com/73031696/97061356-98d5e680-1564-11eb-8cd8-f9b748bc8092.png)
![image](https://user-images.githubusercontent.com/73031696/97061451-e8b4ad80-1564-11eb-961c-6ccb7070e7a2.png)
![image](https://user-images.githubusercontent.com/73031696/97061467-fa965080-1564-11eb-97ee-5ff2be52861c.png)

**Comment by mcalderin** [comment]
Note: this is not a color dimmable light.  It's a color temperature light.

**Comment by ebaauw** [comment]
No it’s not; the HA profile doesn’t define a _Color Temperature Light_, so its type is _Color Dimmable Light_.  Notwithstanding that the API should expose `ct` and not `xy`, `hue`, and `sat`.  The light might need to be whitelisted for that.  How does the API expose it crrently?

**Comment by mcalderin** [comment]
Thanks.  Let me know if I can provide any other info.

**Comment by ebaauw** [comment]
What does the _Color Capabilities_ attribute in the _Color Control_ cluster report?  Make sure to read the attribute.

**Comment by mcalderin** [comment]
![image](https://user-images.githubusercontent.com/73031696/97086751-498ac700-15f3-11eb-9887-a756353dc0b7.png)

**Comment by TheAlphaLaw** [comment]
I would also like these lights to be addend correctly. Previously these added fine and were routers. Now they report as Color changing lights, with no temperature control and are not able to mesh with other devices. Even when they're 5 feet from the Conbee II, they won't mesh.
