### ISSUE TITLE
Do offline search for deCONZ REST Server

### ISSUE THREAD

**Issue by cfrahnow** [dresden-elektronik/deconz-rest-plugin#35]
Currently, it is possible to search for a server simply sending a GET request to [https://dresden-light.appspot.com/discover](https://dresden-light.appspot.com/discover).

Is there a way to get the code that is actually running there? Goal is it to do the search offline.

**Comment by ebaauw** [comment]
You can use UPnP to discover deCONZ locally.  It's still a bit broken, see issue #19.

**Comment by manup** [comment]
The UPnP issues will be improved thanks to @ebaauw findings in the next releases. The fixes then need some testing to verify that various apps like Amazon Echo still work.

The general gateway discovery is also described in the docs:

http://dresden-elektronik.github.io/deconz-rest-doc/discovery/

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
