### ISSUE TITLE
Aurora AONE Smart PIR sensor 

### ISSUE THREAD

**Issue by aberkeley** [dresden-elektronik/deconz-rest-plugin#3503]
## Device

Hi would it be possible to add support for the follow device: 

- Product name: Auora AONE™ PIR SENSOR
- Manufacturer: Aurora
- Model identifier: MotionSensor51AU
- Device type :   - Sensor
  
https://aone.auroralighting.com/ProductDetails/AU-A1ZBPIRS

## Screenshots
![image](https://user-images.githubusercontent.com/73428191/97107006-07c65300-16bd-11eb-9dc3-fb898671490b.png)

![image](https://user-images.githubusercontent.com/73428191/97107085-88854f00-16bd-11eb-982d-e6a51d39c7c1.png)

![image](https://user-images.githubusercontent.com/73428191/97107158-ed40a980-16bd-11eb-9330-b65752193996.png)

**Comment by SwoopX** [comment]
That's a rebranded Develco motion sensor. Integration should be fairly easy.

**Comment by ebaauw** [comment]
Three _Occupancy Sensor_ and an _IAS Zone_ endpoint.  How many motion sensors does it have?

**Comment by SwoopX** [comment]
That's actually correct. You can potentially realize complex scenarios on illuminance and such according to the manual. However, that "power" is supposedly only unleashed with their gateway...

**Comment by aberkeley** [comment]
It just has a single motion sensor, i agree with SwoopX - be good to just get the IAS working to start with. The luminance/occupancy stuff would be fun to use, but basic motion sensing is a start!
