### ISSUE TITLE
Again and again ghost devices.

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#3505]
Hello, I keep getting ghost devices.
I've already restarted Pi, but it doesn't work.
And when I let Alexa search for devices, it also finds which I haven't had for half a year.
Can you empty the cashe?
![sshot-1](https://user-images.githubusercontent.com/32480002/97114490-1d557000-16f1-11eb-9bba-532cd10b49f4.jpg)
![sshot-3](https://user-images.githubusercontent.com/32480002/97114493-1f1f3380-16f1-11eb-9872-34a89ad9a566.jpg)

**Comment by salopette** [comment]
Ich habe bereits alle Infos zur Verfügung gestellt, warum macht dieser scheiß BOT alles zu?

**Comment by salopette** [comment]
Wenn ich die Geräte mit DEL lösche, kommen die nach einer Zeit wieder

![sshot-1](https://user-images.githubusercontent.com/32480002/97117461-3ca9c880-1704-11eb-9a39-72812787dd3b.jpg)

**Comment by Mimiix** [comment]
You need to fill in the form and keep the headers. Please provide all information. And keep it English.
