### ISSUE TITLE
Again and again ghost devices.

### ISSUE THREAD

**Issue by salopette** [dresden-elektronik/deconz-rest-plugin#3506]
## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## Additional context

![sshot-3](https://user-images.githubusercontent.com/32480002/97114529-4fff6880-16f1-11eb-9724-2bb67b3b268a.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/97114530-4fff6880-16f1-11eb-8317-5e7f2a740805.jpg)

**Comment by salopette** [comment]
Hello, I keep getting ghost devices.
I've already restarted Pi, but it doesn't work.
And when I let Alexa search for devices, it also finds which I haven't had for half a year.
Can you empty the cashe?

**Comment by Mimiix** [comment]
Really? First ignoring the template, now tricking the bot?

**Comment by Smanar** [comment]
Hello, but why you have so much ghost device ?
You have all recently ? You havent some sensor not used ATM but already included one time ?

**Comment by Mimiix** [comment]
@Smanar this issue is closed.

**Comment by Smanar** [comment]
Seriously the issue is correct, it s not "tricking the bot", all informations are gived.

**Comment by Mimiix** [comment]
The information is not provided as per request in the template. Thus not correct.

Please check your pm on discord.
