### ISSUE TITLE
deCONZ 2.05.86 Windows 10 Gateway

### ISSUE THREAD

**Issue by UweRP** [dresden-elektronik/deconz-rest-plugin#3518]
Hallo.

## Describe the bug

Wenn ich deCONZ von 2.05.84 auf 2.05.86 unter Windows 10 x64 update wird der Conbee II Stick nicht mehr von der Phoscon App gefunden. deConz selbst zeigt den Stick und die Geräte an aber ohne Namen. Gehe ich zurück auf die 2.05.84 funktioniert es wieder wie erwartet. 
## Screenshots

Version 2.05.86 -- fehlerhaft
![Deconz Version](https://user-images.githubusercontent.com/17329042/97267623-bcca4e00-182a-11eb-9bca-ada8b9b649d1.jpg)
![Deconz](https://user-images.githubusercontent.com/17329042/97267640-c3f15c00-182a-11eb-93de-e281d4168c1c.jpg)

Version 2.05.84 -- ist ok
![Deconz Version 84](https://user-images.githubusercontent.com/17329042/97268294-f2bc0200-182b-11eb-9ac6-b50719dd5821.jpg)
![Deconz 84](https://user-images.githubusercontent.com/17329042/97268309-fb143d00-182b-11eb-872c-9d2053d2694d.jpg)

## Environment

 - Host system: PC
 - Running method: Windows 10 x64
 - Firmware version: 0x26660700
 - deCONZ version: 2.05.86
 - Device: ConBee II
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? If so: KVM (HDMI/USB Switch)

**Comment by Mimiix** [comment]
@UweRP Hi! Can you translate the written text in English? This would help with you issue as not everyone speaks German. Thanks!

**Comment by UweRP** [comment]
Hello Mimiix.
Sorry, I do not speak English. With the help of the Google translator here is the English text. I hope this is understandable.
--
When I update deCONZ from 2.05.84 to 2.05.86 under Windows 10 x64, the Conbee II stick is no longer found by the Phoscon app. deConz itself shows the stick and the devices but without a name. If I go back to the 2.05.84 it works again as expected.
--

**Comment by Mimiix** [comment]
@UweRP Danke!

The translation is fine. I've asked @manup to look at this, as nothing has changed.

**Comment by manup** [comment]
This looks a bit like loading the database fails in .86, could you please send the zll.db file which works in .84 to mpi@dresden-elektronik.de for investigation?

**Comment by SwoopX** [comment]
Just as a side note: I've seen that previously while testing/doing some changes, some of them hilariously simple. I my case, it was definitively not related to the DB, but you never know.

**Comment by UweRP** [comment]
Danke für die Antworten.
@manup die Mail mit der zll.db ist verschickt.

- Google translation
Thank you for the answers.
@manup the mail with the zll.db is sent.

**Comment by manup** [comment]
Thanks, so I tested to load the zll.db file on my Windows PC with 2.05.86 here there were no issues, nodes are loaded fine and also have the names set in the database. I don't now yet why it fails on your machine yet. The next deCONZ Version will contain a little debug message window, hopefully this gives more insights where the error happens.

**Comment by Rolf56** [comment]
Hi all
I had the same issue. After updating to version .86 under Windows 10, I lost all my devices in deCONZ and was not able to log into the Phoscon App web site. The message was the password ist wrong. When I tryed to change it to the default password another error massage was shown.  I can't remember the content of it.
After reinstallation version .84 everything is working fine as before.

**Comment by manup** [comment]
Thanks I'll look into it, my last test was on a Windows 7 pc, I don't think this should make a difference but will test this on Windows 10 again.

**Comment by brunoz78** [comment]
I have the same problem. Back to version 84 and it works fine again.

**Comment by manup** [comment]
Does the issue remain with v2.5.88?

**Comment by brunoz78** [comment]
Unfortunately the display problem is still present with the Verison 88. Back to version 84 and it will display everything correctly again.
![14-11-_2020_07-43-20](https://user-images.githubusercontent.com/74092347/99141688-21b8dd00-264e-11eb-93d4-3e5367d07f33.jpg)

**Comment by UweRP** [comment]
Yes, I still have the problem with v2.5.88.

What else I noticed. A different installation path is suggested depending on the rights I have to start the installation.
The installation file does not automatically request admin rights to install.
The installation is in the directory c:\Program Files (x86)\deCONZ
If I start the installation without admin rights, c:\Users\Uwe\AppData\Local\deCONZ is suggested as the target.

**Comment by Rolf56** [comment]
@UweRP This was always that way in the past. You have to right click and run as administrator. I'm always confused where to place the OTA files. I store them allway on both directories, but think Deconz is using C:\Users\<user>\otau instead of C:\Program Files (x86)\deCONZ\otau.

**Comment by brunoz78** [comment]
Unfortunately the same problem with the new version 2.06.00. Firmware update was also done. With version 2.05.84 everything is still working.
![21-11-_2020_14-00-39](https://user-images.githubusercontent.com/74092347/99878023-a08bb800-2c02-11eb-926e-82247cfa307e.jpg)

**Comment by Rolf56** [comment]
Hi all
I made another trial with version 2.6.0 under Windows 10. It has the same reaction, I lost the names of all my devices in deCONZ and was not able to log into the Phoscon App web site. 
![image](https://user-images.githubusercontent.com/44340206/100515803-f4f0e380-317e-11eb-9437-6353e7a348db.png)

After reinstallation version .84 everything is working fine as before.

I sent you an extract, out of the new debug view as a file to mpi@dresden-elektronik.de for investigation?
In that view, I can see a lot of HTTP/1.1 404 Errors. Especially when reading the sensors but also with other objects.

**Comment by SwoopX** [comment]
Hey folks, could you please try something out? with regard to the lost node names, select one of the routers (yellowish), right click on it and then select reading the simple descriptors.

Would be interested in hearing if they get their names back. Thanks!

**Comment by brunoz78** [comment]
The same result with simple descriptors, no difference. Tested with v2.07.00 and latest firmware 26680700. 
![05-12-_2020_08-50-08](https://user-images.githubusercontent.com/74092347/101237264-97591b80-36d7-11eb-83af-6987f642a74f.jpg)

**Comment by Rolf56** [comment]
Hi all, I still think it has to do with this HTTP Errors 404 Not Found.
I installed Version 2.07.00 now. No info for all devices, see the node list on the right too.
![image](https://user-images.githubusercontent.com/44340206/101504842-f5a22a80-3973-11eb-8eb7-bc5af0554a78.png)

I now tried to connect with Postman and get following error:

![image](https://user-images.githubusercontent.com/44340206/101504530-9fcd8280-3973-11eb-8fd2-ea2b62877543.png)

The node itself gives an answer:

![image](https://user-images.githubusercontent.com/44340206/101506381-9d6c2800-3975-11eb-9e3a-51513cd435e3.png)

but it does not find /api

**Comment by Rolf56** [comment]
Back to version 2.05.84 and everthing is OK-
I also get values and a time from ConBee. In the post before time was 01.01.2000 00:00

![image](https://user-images.githubusercontent.com/44340206/101508401-e9b86780-3977-11eb-83b0-bea4c3fdcec7.png)

**Comment by UweRP** [comment]
I would also like to refer you to the bug report https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3740
Presumably it's the same mistake.

**Comment by Rolf56** [comment]
@brunoz78 : Hey Bruno. your right after copying the file de_rest_plugin.dll it runs also under 2.07.01
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3740#issuecomment-743002564

As I mention before it is the REST API what is bugy.
Hope a fix is available very soon!

**Comment by brunoz78** [comment]
With version 2.08.00 everything works fine again. In addition, the display now also shows the battery level. Thank you very much for the repair.

**Comment by Mimiix** [comment]
@UweRP Can you try on the latest version? It should work again.

**Comment by UweRP** [comment]
Update from 2.05.84 to 2.08.00 seems to fix the problem. The names of the devices are displayed, the Phoscon app finds the ConBee II stick.
Many thanks.

**Comment by Mimiix** [comment]
Case closed!
