### ISSUE TITLE
Smoke detector Schwaiger ZHS20 resp. HEIMAN HS1SA

### ISSUE THREAD

**Issue by zbzhs20** [dresden-elektronik/deconz-rest-plugin#352]
Hi,

I connected a smoke detector to deCONZ, it is labeled "ZHS20" from Schwaiger GmbH (www.schwaiger.de). It seems to be a HEIMAN HS1SA, see Basic Cluster Info.
The HEIMAN smoke detector is certified, id is ZIG16075ZHA25799-24.
There is a Z-WAVE version of the HEIMAN smoke detector, so be careful when ordering.

I can get the cluster infos (sometimes I had to press the button at the device to get a response,
probably because it's a battery powered device).

Is there a way to get the battery status and alarms through the web socket?
The cherry on top would be to turn on the siren through the REST API :-).

If you need more information or if I should check anything for you please feel free to comment!

Here are the cluster infos:

![schwaiger-zhs20-attributes-1](https://user-images.githubusercontent.com/35171815/34651559-10d0239c-f3d2-11e7-855e-eca2778a2a48.png)

![schwaiger-zhs20-attributes-2](https://user-images.githubusercontent.com/35171815/34651572-2d6e0096-f3d2-11e7-9e36-b7a8a6635164.png)

![schwaiger-zhs20-attributes-3](https://user-images.githubusercontent.com/35171815/34651718-f0f514e0-f3d3-11e7-8be9-643634b7cc11.png)

![schwaiger-zhs20-attributes-4](https://user-images.githubusercontent.com/35171815/34651727-084ec3de-f3d4-11e7-91d0-40703579a470.png)

![schwaiger-zhs20-attributes-5](https://user-images.githubusercontent.com/35171815/34651728-103d02e0-f3d4-11e7-9929-2cb6047ede82.png)

![schwaiger-zhs20-attributes-6](https://user-images.githubusercontent.com/35171815/34651734-1e82b00c-f3d4-11e7-9a76-adc57056bfc8.png)

![schwaiger-zhs20-attributes-7](https://user-images.githubusercontent.com/35171815/34651735-237fbdf2-f3d4-11e7-9ee7-be4af780cfa8.png)

![schwaiger-zhs20-attributes-8](https://user-images.githubusercontent.com/35171815/34651736-2943ca80-f3d4-11e7-8674-a40bdc7e3363.png)

**Comment by ebaauw** [comment]
It looks a lot like the Heiman Fire sensor that's now supported with v2.05.04, but with a different _Model Identifier_.  It even reports the same firmware version.

I'll relax the checks for _Model Identifier_ a bit, so this one will be recognised as well.

**Comment by manup** [comment]
I totally need this siren for the office :D

**Comment by ebaauw** [comment]
The Heiman siren would be excellent for the office: it even continues to scream when unplugged.  You can activate the strobe and siren independently or combined through the _IAS WD_ cluster, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/404#issuecomment-364436095.  Now all we need is REST API support...

Still haven't figured out what's easier: a `/lights` resource, or a `/sensors` resource.  It provides an _IAS Zone_ cluster as well, but it doesn't seem to report anything through it.  Maybe I should just create a ZHAAlarm `/sensors` resource for this cluster, and see if deCONZ will commission it.

I suppose it should be possible to bind a sensor directly to the siren so the alarm will sound even when deCONZ isn't running?

**Comment by manup** [comment]
> The Heiman siren would be excellent for the office: it even continues to scream when unplugged. You can activate the strobe and siren independently or combined through the IAS WD cluster, see #404 (comment). Now all we need is REST API support...

Haha can't wait to combine this with a motion detector 

> Still haven't figured out what's easier: a /lights resource, or a /sensors resource. It provides an IAS Zone cluster as well, but it doesn't seem to report anything through it. Maybe I should just create a ZHAAlarm /sensors resource for this cluster, and see if deCONZ will commission it.

Some IAS devices go through a *enroll process* for setup and need to be configured with the writeable IAS_CIE_ADDRESS ZCL attribute (0x0010) before they start to operate.

Might be worth to check the ZigBee specification for this matter, it's likely that there are some bits'n'pieces missing in the deCONZ  configuration of IAS devices.

> I suppose it should be possible to bind a sensor directly to the siren so the alarm will sound even when deCONZ isn't running?

I'm not aware of a device which supports it, ClimaxTechnology does have various IAS products maybe there is one which can trigger the alarm directly.

**Comment by opechunka** [comment]
I'm using Domoticz. Smoke sensor works fine, but no battery reports. Can it be fixed? The same problem with Heiman water sensor. In contrary Heyman Temperature and humidity sensor, which reports battery well.

**Comment by popy2k14** [comment]
@ebaauw Want to get/integrate some of the Schwaiger ZHS20 (Heiman  HS1SA-M) sensors in my deCONZ+fhem system.
Searched here and fhem forum but could not find an answer to my question:

Will they be exposed as an special device or motion sensor?
Means -> Motion -> alarm?

thx

**Comment by popy2k14** [comment]
Got it, the following are supported:

`state.fire
config.battery
state.lowbattery
state.tampered`

In fhem forum a user confirmed they are working: https://forum.fhem.de/index.php?topic=108130.0
