### ISSUE TITLE
SR-ZG2868

### ISSUE THREAD

**Issue by pur3asdf** [dresden-elektronik/deconz-rest-plugin#3527]
## Device

- Product name: [SR-ZG2868](https://www.sunricher.com/dim-cct-rgb-3-in-1-zigbee-remote-sr-zg2868.html)
- Manufacturer: Sunricher
- Model identifier: ZG2868A
- Device type :
-Remote

Also mentioned in [phoscon issue 190](https://github.com/dresden-elektronik/phoscon-app-beta/issues/190)

## Screenshots

  Required screenshots:

![image](https://user-images.githubusercontent.com/66328149/97472014-a7981100-1949-11eb-9b10-f89a90f74401.png)

![image](https://user-images.githubusercontent.com/66328149/97472191-db733680-1949-11eb-855c-b0f67327b47f.png)
![image](https://user-images.githubusercontent.com/66328149/97472292-f9409b80-1949-11eb-8de0-24ad6383922e.png)
![image](https://user-images.githubusercontent.com/66328149/97472340-09587b00-194a-11eb-9e82-f0a368d39588.png)
![image](https://user-images.githubusercontent.com/66328149/97472428-1ffed200-194a-11eb-8e64-cd9b242dfacb.png)
![image](https://user-images.githubusercontent.com/66328149/97472473-2ab96700-194a-11eb-98b9-11af4b3b13ec.png)
![image](https://user-images.githubusercontent.com/66328149/97472511-3442cf00-194a-11eb-8fc2-666f8a41af70.png)
![image](https://user-images.githubusercontent.com/66328149/97472570-40c72780-194a-11eb-9659-aa60886b336f.png)

**Comment by SirMaggot** [comment]
Interested in this.

**Comment by pimw1** [comment]
Hi, i'm also very interested in this. I've the same remote. If needed, i can provide more screenshots. There are actually 4 sections with clusters, not 2. 
![image](https://user-images.githubusercontent.com/74881023/115463250-e4273400-a22b-11eb-9861-65df831fca22.png)
![image](https://user-images.githubusercontent.com/74881023/115463368-0620b680-a22c-11eb-81b7-1d67998606fb.png)

**Comment by pimw1** [comment]
How can I bring this to attention?

**Comment by Smanar** [comment]
Lol, good question.

But this device seem classic, why do you don't try yourself to add it ?
You can just mimic the code for a device that have same cluster list, except this one have 2 endpoint.

**Comment by SirMaggot** [comment]
I did add my remote directly to my lights, like described in the manual, works like a champ.

**Comment by pimw1** [comment]
Thanks! I'll take a look tomorrow. 
Regarding directly connecting it: that's what i am currently doing. But i want to do more advanced stuff via Home Assistant (for example: activating scenes containing not only zigbee bulbs, but also wifi bulbs).

**Comment by pur3asdf** [comment]
Any update on this?

**Comment by pimw1** [comment]
I didn't continued with this, the procedure sounds to complicated (i.e. not worth the effort). My remote is idling at home for 1.5 year now.
