### ISSUE TITLE
Debug end device losing connection

### ISSUE THREAD

**Issue by dergreg** [dresden-elektronik/deconz-rest-plugin#3529]
I have a Xiaomi Aqara Door Contact sensor mounted on my garage door, which used to work flawlessly the last few months, but suddenly stopped working a few weeks ago (didn't notice). I updated deCONZ two days ago to the latest stable version and re-paired the sensor.

However, it doesn't seem to be able to keep a connection established. After pairing, it was connected to the coordinator, but lost connection in the garage.

What can be done to debug the issues? Distance wise, it should be able to connect to the coordinator and the "Osram Diele Repeater".

## Screenshots

<img width="888" alt="Bildschirmfoto 2020-10-28 um 19 04 36" src="https://user-images.githubusercontent.com/39279568/97479352-6b1ce300-1952-11eb-9819-16fe48a52a59.png">

## Environment

 - Host system: Raspberry Pi 3B
 - Running method: Raspbian
 - Firmware version: 26390500
 - deCONZ version: 2.05.84
 - Device: RaspBee I
 - Is there any other USB or serial devices connected to the host system? ZWave.me USB Stick

## deCONZ Logs

I can provide some depending on what you think is relevant for debugging the issue.

**Comment by timovos** [comment]
I'm having the same issues. Xiaomi Aqara door sensor is always fighting with the zigbee network. Everytime I open DeCONZ, there's no line between the sensor and whatever parent.

Though, in my case, the sensor always works.

**Comment by dergreg** [comment]
I repaired the sensor to the nearest repeater and verified it in the deconz application. Let's see if the connection remains

**Comment by Smanar** [comment]
What is the osram device ?
For information Xiaomi have some issue with Osram plug.

**Comment by dergreg** [comment]
It's an Osram plug indeed. What are the issues?

**Comment by Smanar** [comment]
Xiaomi end device leave ^^
https://community.hubitat.com/t/xiaomi-aqara-devices-pairing-keeping-them-connected/623

Long story, but the problem is from Xiaomi.
