### ISSUE TITLE
Namron 4-channel remote control 4512705 device request

### ISSUE THREAD

**Issue by Frederik91** [dresden-elektronik/deconz-rest-plugin#3537]
Hi

I just got this remote and tried to pair it using the phoscon UI. I got no response in the UI but it shows up in deconz. 
Hope you can help med get this device supported. Let me know if you need any more information.

Link to device: https://www.elektroimportoren.no/namron-zigbee-4-kanaler-fjernkontroll/4512705/Product.html?gtin=7070990327688

## Device

- Product name: Namron 4-channel Remote Control
- Manufacturer: NAMRON AS
- Model identifier: 4512705
- Device type : 
  - Remote

### Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/11948105/97629793-e48a0380-1a2e-11eb-80b7-310c623f87a3.png)

### Node Info panel
![image](https://user-images.githubusercontent.com/11948105/97629838-fcfa1e00-1a2e-11eb-8033-0459fe94a822.png)

### Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/11948105/97629825-f53a7980-1a2e-11eb-91b9-7ba06b802a6d.png)

Power Configuration:
![image](https://user-images.githubusercontent.com/11948105/97630116-6b3ee080-1a2f-11eb-9551-0d684ee3b4c2.png)
![image](https://user-images.githubusercontent.com/11948105/97630140-73971b80-1a2f-11eb-94fb-eddf18a2faa1.png)

**Comment by SwoopX** [comment]
The device is already supported. If it is not shown in Phoscon, please raise a corresponding request in the Phoscon beta repo.
