### ISSUE TITLE
Develco Air Quality Sensor (AQSZB-110)

### ISSUE THREAD

**Issue by michael666nan** [dresden-elektronik/deconz-rest-plugin#3542]
## Device

- Product name: Air Quality Sensor
- Manufacturer: Develco Products A/S
- Model identifier: AQSZB-110
- Device type :
  - Sensor
  
## Screenshots
Basic cluster:
![image](https://user-images.githubusercontent.com/69690551/97720413-8c074480-1ac8-11eb-80e6-5e48fdc47a02.png)
![image](https://user-images.githubusercontent.com/69690551/97720445-945f7f80-1ac8-11eb-8876-0a00cb1bd187.png)

Power Configuration:
![image](https://user-images.githubusercontent.com/69690551/97721785-2caa3400-1aca-11eb-873a-26c378b8cb3a.png)
![image](https://user-images.githubusercontent.com/69690551/97721809-35026f00-1aca-11eb-94fb-fdd9f40742af.png)

Identify:
![image](https://user-images.githubusercontent.com/69690551/97721840-3e8bd700-1aca-11eb-967d-e2f4193d925b.png)

Poll Control:
![image](https://user-images.githubusercontent.com/69690551/97721868-48add580-1aca-11eb-8083-7eb6dd6a17f0.png)

Temperature measurement:
![image](https://user-images.githubusercontent.com/69690551/97721915-56fbf180-1aca-11eb-8f4b-f7df929001ca.png)

Relative humidity measurement:
![image](https://user-images.githubusercontent.com/69690551/97721963-64b17700-1aca-11eb-8048-5d509150427b.png)

Node Info Panel:
![image](https://user-images.githubusercontent.com/69690551/97722008-7004a280-1aca-11eb-814b-64436e3dc5db.png)

**Comment by cllatser** [comment]
I am looking for this product to buy, but Develco is a white label. Where did you buy it? Thanks a lot.

**Comment by michael666nan** [comment]
Sorry I can't help since I did not buy these sensors myself, but received some in a project. Best regards.

**Comment by OsteHovel** [comment]
I bought one from [Elektroimportøren ](https://www.elektroimportoren.no/develco-air-quality-sensor/4514806/Product.html) in Norway
