### ISSUE TITLE
LUPUS - Rollladenrelais V2

### ISSUE THREAD

**Issue by benkuly** [dresden-elektronik/deconz-rest-plugin#3543]
## Device

- Product name: LUPUS - Rollladenrelais V2
- Manufacturer: ClimaxTechnology
- Model identifier: SCM-3-OTA_00.00.03.16TC
- Device type :
  - Remote
  - Switch

## Screenshots

![Lupus-RS-1](https://user-images.githubusercontent.com/12199167/97735034-1a37f680-1ada-11eb-9034-54d8d1483147.png)
![Lupus-RS-2](https://user-images.githubusercontent.com/12199167/97735045-1b692380-1ada-11eb-9a51-b0266b792e59.png)
![Lupus-RS-3](https://user-images.githubusercontent.com/12199167/97735047-1c01ba00-1ada-11eb-8b93-644ffb604021.png)
![Lupus-RS-4](https://user-images.githubusercontent.com/12199167/97735051-1d32e700-1ada-11eb-8e2c-88f171220370.png)

**Comment by SwoopX** [comment]
You've skipped vital information as mentioned in the template. Please add it, otherwise the issue will be closed.

**Comment by benkuly** [comment]
Sorry...

![Lupus-RS-1-1](https://user-images.githubusercontent.com/12199167/97774900-0208bb80-1b5c-11eb-9c0a-2a5a50c6b6ed.png)
![Lupus-RS-5](https://user-images.githubusercontent.com/12199167/97774918-22d11100-1b5c-11eb-990a-72f1ed658272.png)

**Comment by SwoopX** [comment]
Alright, now it fits. So, what should we do now? The device seems to be paired alright and resources should have been created.

**Comment by benkuly** [comment]
Its shown as color-light in phoscon web gui and home assistant instead of roller shutter. Because I switched to Home Assistant integration of Zigbee (there it works), this issue can be closed. Otherwise I can try to help :)
