### ISSUE TITLE
How can I use touchlink?

### ISSUE THREAD

**Issue by simplenotezy** [dresden-elektronik/deconz-rest-plugin#3546]
I have paired almost 10 bulbs, but theres ONE bulb that I removed from Hue app, and which I now want to connect to phoscon, however it is not showing up.

I have heard that I could use touchlink to reset it. Is this possible? if so, how do I find it?

I have tried resetting using remote, however, that makes it blink and seems like it's been reset, however, I still cant find it when searching. The stick is 5 centimers away from the bulb..

**Comment by MattWestb** [comment]
If you having one first gen Rasp/CornBee use the "old web app" Menu > Setting. 
At the button "scan for device".

If you is happy owner of gen 2 its not working then the touchlink is not implanted in their firmware. If you like getting implantes do request for getting it implanted as some of us user have don.
