### ISSUE TITLE
Thermostat 902010/32 (mode support)

### ISSUE THREAD

**Issue by keesj** [dresden-elektronik/deconz-rest-plugin#3550]
## Device

The device itself it already added in  #1003 and is the 
Bitron Thermostat 902010/32. For better support however it would be good to be able to set the heating mode 

## Screenshots

![00_basic](https://user-images.githubusercontent.com/57112/97805742-411c3700-1c58-11eb-96f5-bee8b92521ce.png)

![photo_2020-11-01_15-01-55](https://user-images.githubusercontent.com/57112/97805730-319cee00-1c58-11eb-9656-56c3f7dd8b21.jpg)
![photo_2020-11-01_15-01-52](https://user-images.githubusercontent.com/57112/97805732-32358480-1c58-11eb-8ddf-eef7ac33bf9a.jpg)

**Comment by Smanar** [comment]
Hello again.

So to test it, you need an Unix OS (if you have one ?), and take a look here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only with a modification for step 1

```
git clone --branch bitron https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by keesj** [comment]
![mode_added](https://user-images.githubusercontent.com/57112/97806511-3663a100-1c5c-11eb-8492-7a67d55297dd.png)

**Comment by keesj** [comment]
Some more notes on things dicovered:
from deCONZ ui it is possible to set the mode (attribute 0x001C) but only to 2 values , either OFF or Heat, setting to an other value like "AUTO" results in a write failed. but overall I can now set the device off in domoticz
![Screenshot from 2020-11-01 16-54-58](https://user-images.githubusercontent.com/57112/97807804-49c63a80-1c63-11eb-9245-940799a9e122.png)
