### ISSUE TITLE
Why is ID 1 Sensor updated every minute?

### ISSUE THREAD

**Issue by TTP1106** [dresden-elektronik/deconz-rest-plugin#3555]
## Describe the question or issue you are having

 made a Websock which connects to Deconz WS via Browser.
I have a few switches in my envoirment.

If I do nothing then every minute appears new Event from ID: 1 (daylight sensor). But if I request the Sensors´ ID then there is no change. Why is this announced every minute?

## Screenshots

![image](https://user-images.githubusercontent.com/38374361/97811685-6cb11880-1c7c-11eb-9dbd-1821b807384c.png)
![image](https://user-images.githubusercontent.com/38374361/97811689-70dd3600-1c7c-11eb-8caa-6867c664c80b.png)
![image](https://user-images.githubusercontent.com/38374361/97811692-7470bd00-1c7c-11eb-8b59-f46f7e9a5c34.png)

## Environment

 - Host system: OrangePi Zero / Orange Pi One
 - Running method: Marthoc Docker container
 - Firmware version: 264A0700
 - deCONZ version: 2.05.86 / 15.10.2020
 - Device: ConBee II
 - Do you use an USB extension cable: NO
 - Is there any other USB or serial devices connected to the host system? NO

## deCONZ Logs

`   [marthoc/deconz] Starting deCONZ...                                                                                             │
│   [marthoc/deconz] Current deCONZ version: 2.05.86                                                                                │
│   [marthoc/deconz] Web UI port: 8081                                                                                              │
│   [marthoc/deconz] Websockets port: 8443                                                                                          │
│   [marthoc/deconz] VNC Disabled                                                                                                   │
│   QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'                                                      │
│   libpng warning: iCCP: known incorrect sRGB profile                                                                              │
│   This plugin does not support propagateSizeHints()                                                                               │
│   This plugin does not support propagateSizeHints()                                                                               │
│   This plugin does not support propagateSizeHints()                                                                               │
│   [marthoc/deconz] Starting deCONZ...                                                                                             │
│   [marthoc/deconz] Current deCONZ version: 2.05.86                                                                                │
│   [marthoc/deconz] Web UI port: 8081                                                                                              │
│   [marthoc/deconz] Websockets port: 8443                                                                                          │
│   [marthoc/deconz] VNC Disabled                                                                                                   │
│   QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'                                                      │
│   libpng warning: iCCP: known incorrect sRGB profile                                                                              │
│   This plugin does not support propagateSizeHints()                                                                               │
│   This plugin does not support propagateSizeHints()                                                                               │
│   This plugin does not support propagateSizeHints()     `

## Additional context

Why is this close bot so freaky?

Result of Sensor 1 is always:
`{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"0cd6bbee7d839c163b3f23081ea477d9","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":true,"daylight":false,"lastupdated":"2020-11-01T18:10:39.119","status":230,"sunrise":"2020-11-01T06:15:38","sunset":"2020-11-01T15:49:36"},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:05:07:56-01"}` but with another timestamp. Values are not changed

**Comment by Smanar** [comment]
Hello, you have it only for this sensor ?

If I m right all devices send this notification "attr" every minute, to update the "lastseen"

**Comment by TTP1106** [comment]
No I also have temperature Sensors which are only sending notification on change, not time based.
My Aqara Switches and My Osram AC/Plug are also not sending every minute. Its only the Daylight Sensor which is an virtual sensors. So in my opinion this does not make sense...

**Comment by Mimiix** [comment]
@TTP1106 

The bot closes if you are not following the template.

The sensors decide when there is a update, not deCONZ.  The virtual sensor does so apparently.  The update is the timestamp.

As far as i know, @ebaauw implemented this announcement. He might be able to provide some information on this.

**Comment by ebaauw** [comment]
> If I do nothing then every minute appears new Event from ID: 1 (daylight sensor). 

No.  The log shows events for `/lights/1`, not for `/sensors/1`.  The notification is triggered by `lastseen` being updated.  Set `/config/websocketnotifyall` to `false` to receive only the updated attributes in the event.

**Comment by TTP1106** [comment]
That´s strange because I do not have a light connected:
![image](https://user-images.githubusercontent.com/38374361/97884708-b6563d80-1d26-11eb-8eec-8884bafa7d08.png)

I´ll test the /config/websocketnotifyall false flagging

**Comment by TTP1106** [comment]
Why is Conbee II added as light ressource?

**Comment by Smanar** [comment]
Long story but it s normal too, since this version https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_74

>Support RaspBee, ConBee, ConBee II, XBee under lights resources 8c8e4b

**Comment by TTP1106** [comment]
Why is it saying that it does not exists?

> > If I do nothing then every minute appears new Event from ID: 1 (daylight sensor).
> 
> No. The log shows events for `/lights/1`, not for `/sensors/1`. The notification is triggered by `lastseen` being updated. Set `/config/websocketnotifyall` to `false` to receive only the updated attributes in the event.

`[{"error":{"address":"/config/websocketnotifyall","description":"resource, /config/websocketnotifyall, not available","type":3}}]`

**Comment by Smanar** [comment]
Do you have the complete request you have used ?
But for me it s useless (you will have shorter notifications but all will be same, sd write/red, memory usage, process used, ect ...), and your third app can need the websocketnotifyall set to true to work correctly.

**Comment by TTP1106** [comment]
I just made a quick GET via Browser on this URL:
http://mydevice/api/D00000C086/config/websocketnotifyall

**Comment by Smanar** [comment]
You need to make a PUT with a form, for exemple with curl

`curl -H 'Content-Type: application/json' -X PUT -d '{"websocketnotifyall ": false}' http://IP:PORT/api/API_KEY/config`

**Comment by TTP1106** [comment]
Okay, my Mistake.
`curl -X PUT -H "Content-Type: application/json" -d '{"websocketnotifyall":false}' http://localhost:8081/api/D60849C086/config
[{"success":{"/config/websocketnotifyall":false}}]`
This worked to change the Attribute. But it will not change the announcements

![image](https://user-images.githubusercontent.com/38374361/98571483-d781d580-22b4-11eb-9ac5-e2143c5fc4a0.png)

As @Smanar  mentioned, it will not work to reduce it.

**Comment by Smanar** [comment]
For me it s normal, you have this notification on every "lastseen" change, so every minut if I remember.
