### ISSUE TITLE
Tint Müller Licht RGB Colorloop and other effects

### ISSUE THREAD

**Issue by BigHub40** [dresden-elektronik/deconz-rest-plugin#3559]
## Feature request type
Expansion of effects at Müller Licht Tint

## Description
Hello,
i use the Conbee 2 stick in combination with the IOBROKER deconz adapter.
In the adapter itself there is one data point "Effect" and one data point "Colorspeed".
In effect you can enter "Colorloop" or "None". In Colorspeed a value for the speed of the colourloop.
So far very good!
What would be great, of course, would be the other effects you can trigger with the TINT remote control.
Night light, romantic, etc...
The static effects can be seen more as a scene, so you can theoretically create and apply them yourself as "commands".
But what is not so easy to do are the dynamic effects, like the Colorloop.
I find the fire effect that simulates a campfire or candle flickering helpful. It would also be cool if you could create something like this "romantic" effect, where the red and pink tones are slowly "looped".
Ideal would be of course if you had two data points in which you enter a colour value each and then in the effect e.g.
"2 Color Loop", where you can loop back and forth between the two colour values. In principle the same as with the colour loop, only that not through all colours but between the two predefined ones.
Is it possible to integrate the distance effects in addition to Colorloop?
Is it possible to integrate a "2 colour values loop"?
Thank you very much and best regards!

## Considered alternatives
No alternatives would occur to me.

## Additional context
(I had already asked the adapter programmer. There the answer was that the adapter itself cannot do it if it is not integrated at deConz).

**Comment by Mimiix** [comment]
Hi,

As we are fully English here, could you please translate to English? This would help users to understand better :)

Thanks.

**Comment by BigHub40** [comment]
Done :-)

**Comment by Mimiix** [comment]
Thanks :) I just saw it.

Was it this one?
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1209

That was just closed due to inactivity.

**Comment by BigHub40** [comment]
No, not #1209 
#1209 was from somebody who wants to integrate the tint remote into the adapter.

My request was this one:
https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/183

Its only about the above named Color Effekt feature.
Thanks

**Comment by Mimiix** [comment]
Let me check with @jey-cee

**Comment by Jey-Cee** [comment]
I am not sure if this effects are already implemented in the lamp its self like the colorloop, but it sounds so.
If it so deConz has to export it like the colorloop feature.

**Comment by ebaauw** [comment]
The REST API plugin already exposes the built-in "effect scenes" of Tint Müller lights through `state.effect`, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1209#issuecomment-648931529.

I don't think the plugin should support effects that need to be programmed using multiple commands (either using rules, or using external logic, like Node Red, HA, ...).  Maybe Phoscon could, but it would seem they have plenty of other priorities.

**Comment by BigHub40** [comment]
Hi all, i have testet what ebaauw has written. The effects are working if you set them in the "effect" datapoint of the light in the deconz adapter for iobroker. 
First of all that really great !!! (i have overseen this in the long remote #1209 request.)
What i dont understand is: when you klick on the effect datapoint in the deconz adapter in iobroker, only none(none) and colorloop(colorloop) comes up as a drop down. Why does it not shown the other already implemented effects?

If my request about looping to customer defined colours should not be implemented, i will try to solve this with a blockly script in iobroker.

**Comment by BigHub40** [comment]
"sunset", "party", "worklight", "campfire", "romance", or "nightlight" ... are the implemented effects...

**Comment by scobby** [comment]
Still in developement?

**Comment by irekzielinski** [comment]
> Still in developement?

I think it's all done. I am able to use all functionality of this light via REST api (including effects)

**Comment by scobby** [comment]
Can you close it?

**Comment by Mimiix** [comment]
@BigHub40 case closed?

**Comment by BigHub40** [comment]
yes

 
 

Gesendet: Sonntag, 03. Januar 2021 um 23:20 Uhr
Von: "Dennis D" <notifications@github.com>
An: "dresden-elektronik/deconz-rest-plugin" <deconz-rest-plugin@noreply.github.com>
Cc: "BigHub40" <essener23@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Tint Müller Licht RGB Colorloop and other effects (#3559)


 

@BigHub40 case closed?
