### ISSUE TITLE
Ferguson FS2CO Smart Carbon Monoxide Sensor

### ISSUE THREAD

**Issue by kalimero0073** [dresden-elektronik/deconz-rest-plugin#3567]
## Device

- Product name: Ferguson Smart Carbon Monoxide Sensor
- Manufacturer: Heiman
- Model identifier: CoSensor-EM
- Device type : 
  - Sensor
- Product Link (previous version):
  - http://ferguson-digital.eu/en/smart-home-ferguson/smart-home-co-detector-fs2co-gb/

## Screenshots
  - Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/23025107/97881601-e6034680-1d22-11eb-8c97-83e70b9805ad.png)

  - Node Info panel
![image](https://user-images.githubusercontent.com/23025107/97881640-f0bddb80-1d22-11eb-8cc6-6e5faf44c869.png)

  - Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/23025107/97881678-fc110700-1d22-11eb-9ef1-ec9e80a6680a.png)
![image](https://user-images.githubusercontent.com/23025107/97881696-04694200-1d23-11eb-8412-b8a4b91e6231.png)

  - Power Configuration Cluster
![image](https://user-images.githubusercontent.com/23025107/97881730-0d5a1380-1d23-11eb-98a1-bc6005c947c2.png)

**Comment by SwoopX** [comment]
As this a Heiman device, it is already supported.
