### ISSUE TITLE
Constant LOW Battery Warning on Sercomm SZ-DWS04 Micro Door Window Sensor

### ISSUE THREAD

**Issue by perfecblue** [dresden-elektronik/deconz-rest-plugin#3576]
## Describe the bug
Hi, I understand that this device (Sercomm SZ-DWS04 Micro Door Window Sensor) has been added since April, 26 2020 via Issue#2722, thank you very much for the support.  However, when I expose the device through Homebridge's Homebridge-Hue plugin, there's a constant LOW battery warning with incorrect battery status.  This DOES NOT happen in the Phoscon APP as the Battery state is reported as "STATE OK" in the webpage.

I've raised the issue with Homebridge-Hue's dev on this and he has the following response:

_"This is an issue with the deCONZ REST API plugin:  it should populate config.battery or not expose it at all, if the device doesn’t support it."_

Is there anyway to fix this issue?

Thank you very much!

## Steps to reproduce the behavior
As soon as the sensor is paired with deCONZ CONBEE2 and expose to Homebridge-Hue, the LOW BATTERY tile shows up along side the device tile in homekit.

## Expected behavior
Constant LOW BATTERY warning despite new battery being replaced.  Error in the Homebridge-Hue Log:

`[11/3/2020, 15:24:32] [Hue] deconz001: /sensors/2: warning: unknown ZHAOpenClose sensor {"config":{"battery":null,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"588fe1d132c40257fc592b43dd652b34","lastseen":"2020-11-03T07:24Z","manufacturername":"Sercomm Corp.","modelid":"SZ-DWS04","name":"Contact Sensor","state":{"lastupdated":"2020-11-03T07:23:51.388","lowbattery":false,"open":false,"tampered":false},"type":"ZHAOpenClose","uniqueid":"00:0d:6f:00:04:f7:32:7f-01-0500"}`

## Screenshots
[https://imgur.com/a/9TM8ID1](https://imgur.com/a/9TM8ID1) 

## Environment
 - Host system: Raspberry Pi 4 with Homebridge
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.05.84
 - Device: ConBee II
 - Do you use an USB extension cable: YES
 - Is there any other USB or serial devices connected to the host system? NO

**Comment by SwoopX** [comment]
Hm, so then the device does indeed to seem to provide any battery readings whatsoever...

We could try to swtich that over to battery alarm mask (so the `lowbattery` entry for the sensor) in the hope that his is taken into account.

**Comment by perfecblue** [comment]
Thank you for your fast prompt response!  Hope something can be done about it in future updates, thank you guys again!

**Comment by SwoopX** [comment]
Just seen that the reporting configuration for battery voltage was not taken into account. Updated the code in this regard.

**Comment by perfecblue** [comment]
I can now confirm that after the above fix that was merged into #3502, the Sercomm SZ-DWS04 Micro Door Window Sensor is now reporting the battery status correctly!  Like similar Zigbee devices, it’ll take an hour or so for the battery level to be correctly registered so please be patient.  Thank you again for your work on this issue!
