### ISSUE TITLE
Bosch Flush-mounted roller shutter control / Unterputz Rollladen Steuerung

### ISSUE THREAD

**Issue by lViSoRl** [dresden-elektronik/deconz-rest-plugin#3583]
## Device

- Product name: Bosch Smart Home Unterputz Rollladen Steuerung
- Manufacturer: Bosch
- Model identifier: EAN 4057749657862 / Gerätenummer 8750000402
- Device type : 
  - Lock
  - Other: roller shutter

**Comment by Mimiix** [comment]
Screenshots are missing.

Closing.
