### ISSUE TITLE
Loosing contact with IKEA Trådfri controller after upgrade to deCONZ 6.4.1 (2.05.84)

### ISSUE THREAD

**Issue by baunan** [dresden-elektronik/deconz-rest-plugin#3586]
Upgrades my home assistant to 0.116.4 this weekend and at the same time updated deCONZ to the latest available version from 2.05.81 (I think).
I have two IKEA E1702 on/off controller units (https://www.ikea.com/no/no/p/tradfri-adapter-90356166/), where one is used as a repeater and the second used as a on/off switch. This unit is also farthest away in my network of 21 sensors, At the latest LQI check when they where available none of the sensors did have poor signals.

The IKEA unit farthest away was the first one I noticed to dropped in and out of the network and now the second unit used as a repeater. 

## Screenshots

![image](https://user-images.githubusercontent.com/59838425/98016276-0eac3e80-1dfe-11eb-9926-19e0970f2036.png)

## Environment

 - Host system: Raspberry Pi 3B
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26580700)
 - deCONZ version: (2.05.84)
 - Device: ConBee II 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs (from latest startup)
I see the log Classifies 0x680ae2fffef06eca which is the IKEA unit I use as repeater as zombie

17:40:53:460 discovery for zombie 0x680ae2fffef06eca dropped, last try was 354 s ago
17:40:54:625 Websocket disconnected 127.0.0.1:37728, state: 0, close-code: 1000, reason: 
17:40:55:711 New websocket 127.0.0.1:37760 (state: 3) 
17:41:01:137 send permit join, duration: 59
17:41:13:140 discovery for zombie 0x680ae2fffef06eca dropped, last try was 374 s ago
17:41:32:820 discovery for zombie 0x680ae2fffef06eca dropped, last try was 394 s ago
17:41:37:155 Current channel 25
17:41:37:166 Device TTL 2253 s flags: 0x7
17:41:49:140 discovery for zombie 0x680ae2fffef06eca dropped, last try was 410 s ago
17:42:00:135 send permit join, duration: 59
17:42:37:154 Current channel 25
17:42:37:164 Device TTL 2193 s flags: 0x7
17:42:49:203 dev /dev/ttyAMA0
17:42:49:203 GW firmware version: 0x26580700
17:42:49:204 GW firmware version shall be updated to: 0x26660700
17:42:59:136 send permit join, duration: 59
17:43:37:154 Current channel 25
17:43:37:164 Device TTL 2133 s flags: 0x7
17:43:58:138 send permit join, duration: 0
17:43:58:838 Search sensors done
17:44:08:576 Websocket disconnected 127.0.0.1:37760, state: 0, close-code: 1000, reason: 
17:44:11:268 New websocket 127.0.0.1:38436 (state: 3) 
17:44:16:204 discovery for zombie 0x680ae2fffef06eca dropped, last try was 16 s ago
17:44:29:484 Websocket disconnected 127.0.0.1:38436, state: 0, close-code: 1000, reason: 
17:44:30:724 New websocket 127.0.0.1:38470 (state: 3) 
17:44:31:442 Websocket disconnected 127.0.0.1:38470, state: 0, close-code: 1000, reason: 
17:44:32:584 New websocket 127.0.0.1:38490 (state: 3) 
17:44:33:012 discovery for zombie 0x680ae2fffef06eca dropped, last try was 33 s ago
17:44:37:155 Current channel 25
17:44:37:165 Device TTL 2073 s flags: 0x7
17:44:49:332 discovery for zombie 0x680ae2fffef06eca dropped, last try was 49 s ago
17:44:59:199 dev /dev/ttyAMA0
17:44:59:200 GW firmware version: 0x26580700
17:44:59:200 GW firmware version shall be updated to: 0x26660700
17:45:05:652 discovery for zombie 0x680ae2fffef06eca dropped, last try was 65 s ago
17:45:21:972 discovery for zombie 0x680ae2fffef06eca dropped, last try was 82 s ago
17:45:37:154 Current channel 25
17:45:37:164 Device TTL 2013 s flags: 0x7
17:45:38:294 discovery for zombie 0x680ae2fffef06eca dropped, last try was 98 s ago
17:45:51:252 discovery for zombie 0x680ae2fffef06eca dropped, last try was 111 s ago
17:46:04:212 discovery for zombie 0x680ae2fffef06eca dropped, last try was 124 s ago
17:46:17:171 discovery for zombie 0x680ae2fffef06eca dropped, last try was 137 s ago
17:46:30:132 discovery for zombie 0x680ae2fffef06eca dropped, last try was 150 s ago
17:46:37:154 Current channel 25
17:46:37:163 Device TTL 1953 s flags: 0x7
17:46:43:091 discovery for zombie 0x680ae2fffef06eca dropped, last try was 163 s ago
17:46:55:589 [INFO] - No button map for: lumi.sensor_magnet.aq2 endpoint: 0x01 cluster: BASIC (0x0000) command: 0x0A payload[0]: 001
17:46:55:589 ZCL attribute report 0x00158D00041CE6F7 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
17:46:55:589 0x00158D00041CE6F7 extract Xiaomi special attribute 0xFF01
17:46:55:589 	01 battery 3015 (0x0BC7)
17:46:55:589 	03 temperature 24 °C
17:46:55:589 	04 unknown 5032 (0x13A8)
17:46:55:589 	05 RSSI dB (?) 7 (0x0007)
17:46:55:589 	06 LQI (?) 4294967296 (0x0100000000)
17:46:55:589 	0a unknown 0 (0x0000)
17:46:55:589 	64 on/off 0
17:46:56:052 discovery for zombie 0x680ae2fffef06eca dropped, last try was 176 s ago
17:47:09:196 dev /dev/ttyAMA0

17:57:51:412 discovery for zombie 0x680ae2fffef06eca dropped, last try was 336 s ago
17:57:59:198 dev /dev/ttyAMA0
17:57:59:198 GW firmware version: 0x26580700
17:57:59:198 GW firmware version shall be updated to: 0x26660700
17:58:04:372 discovery for zombie 0x680ae2fffef06eca dropped, last try was 348 s ago
17:58:17:332 discovery for zombie 0x680ae2fffef06eca dropped, last try was 361 s ago
17:58:30:292 discovery for zombie 0x680ae2fffef06eca dropped, last try was 374 s ago
17:58:37:153 Current channel 25
17:58:37:163 Device TTL 1232 s flags: 0x7
17:58:43:253 discovery for zombie 0x680ae2fffef06eca dropped, last try was 387 s ago
17:58:56:212 discovery for zombie 0x680ae2fffef06eca dropped, last try was 400 s ago
17:59:09:172 discovery for zombie 0x680ae2fffef06eca dropped, last try was 413 s ago
17:59:22:132 discovery for zombie 0x680ae2fffef06eca dropped, last try was 426 s ago
17:59:33:136 remove outdated neighbor 0xF97C
17:59:35:092 discovery for zombie 0x680ae2fffef06eca dropped, last try was 439 s ago
17:59:37:156 Current channel 25
17:59:37:166 Device TTL 1172 s flags: 0x7
17:59:48:052 discovery for zombie 0x680ae2fffef06eca dropped, last try was 452 s ago
18:00:01:012 discovery for zombie 0x680ae2fffef06eca dropped, last try was 465 s ago
18:00:09:203 dev /dev/ttyAMA0
18:00:09:204 GW firmware version: 0x26580700
18:00:09:204 GW firmware version shall be updated to: 0x26660700
localhost - - [03/Nov/2020 18:00:25] 127.0.0.1:5900: Client closed connection
localhost - - [03/Nov/2020 18:00:25] 127.0.0.1:5900: Closed target
18:00:13:972 discovery for zombie 0x680ae2fffef06eca dropped, last try was2020/11/03 17:00:25 [info] 1210#1210: *491 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 172.30.32.2, server: _, request: "GET /novnc/websockify HTTP/1.1", upstream: "http://127.0.0.1:5901//websockify", host: ""
172.30.32.2 - - [03/Nov/2020:17:00:25 +0000] "GET /novnc/websockify HTTP/1.1" 101 136919 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
Ignoring interrupted syscall
127.0.0.1: new handler Process
localhost - - [03/Nov/2020 18:02:04] "GET //websockify HTTP/1.1" 101 -
localhost - - [03/Nov/2020 18:02:04] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [03/Nov/2020 18:02:04] 127.0.0.1: Version hybi-13, base64: 'False'
localhost - - [03/Nov/2020 18:02:04] 127.0.0.1: Path: '//websockify'
localhost - - [03/Nov/2020 18:02:04] connecting to: 127.0.0.1:5900
localhost - - [03/Nov/2020 18:04:46] 127.0.0.1:5900: Client closed connection
2020/11/03 17:04:46 [info] 1210#1210: *493 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 172.30.32.2, server: _, request: "GET /novnc/websockify HTTP/1.1", upstream: "http://127.0.0.1:5901//websockify", host: ""
172.30.32.2 - - [03/Nov/2020:17:04:46 +0000] "GET /novnc/websockify HTTP/1.1" 101 141822 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
localhost - - [03/Nov/2020 18:04:46] 127.0.0.1:5900: Closed target
Ignoring interrupted syscall
 478 s ago
18:00:26:932 discovery for zombie 0x680ae2fffef06eca dropped, last try was 491 s ago
18:00:30:386 [INFO] - No button map for: lumi.weather endpoint: 0x01 cluster: 0x0402 command: 0x0A payload[0]: 000
18:00:30:386 ZCL attribute report 0x00158D0004460901 for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
18:00:30:403 [INFO] - No button map for: lumi.weather endpoint: 0x01 cluster: 0x0405 command: 0x0A payload[0]: 000
18:00:30:403 ZCL attribute report 0x00158D0004460901 for cluster: 0x0405, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
18:00:30:409 [INFO] - No button map for: lumi.weather endpoint: 0x01 cluster: 0x0403 command: 0x0A payload[0]: 000
18:00:30:409 ZCL attribute report 0x00158D0004460901 for cluster: 0x0403, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
18:00:37:154 Current channel 25
18:00:37:165 Device TTL 1112 s flags: 0x7
18:00:39:892 discovery for zombie 0x680ae2fffef06eca dropped, last try was 504 s ago
18:00:56:211 discovery for zombie 0x680ae2fffef06eca dropped, last try was 520 s ago
18:01:12:532 discovery for zombie 0x680ae2fffef06eca dropped, last try was 537 s ago
18:01:37:154 Current channel 25
18:01:37:164 Device TTL 1052 s flags: 0x7
18:01:45:172 discovery for zombie 0x680ae2fffef06eca dropped, last try was 16 s ago
18:01:58:132 discovery for zombie 0x680ae2fffef06eca dropped, last try was 29 s ago
18:02:11:092 discovery for zombie 0x680ae2fffef06eca dropped, last try was 42 s ago
18:02:19:206 dev /dev/ttyAMA0
18:02:19:207 GW firmware version: 0x26580700
18:02:19:207 GW firmware version shall be updated to: 0x26660700
18:02:24:052 discovery for zombie 0x680ae2fffef06eca dropped, last try was 55 s ago
18:02:37:014 discovery for zombie 0x680ae2fffef06eca dropped, last try was 68 s ago
18:02:37:156 Current channel 25
18:02:37:165 Device TTL 992 s flags: 0x7
18:02:49:978 discovery for zombie 0x680ae2fffef06eca dropped, last try was 81 s ago
18:03:02:932 discovery for zombie 0x680ae2fffef06eca dropped, last try was 94 s ago
18:03:08:746 [INFO] - No button map for: lumi.sensor_wleak.aq1 endpoint: 0x01 cluster: BASIC (0x0000) command: 0x0A payload[0]: 001
18:03:08:746 ZCL attribute report 0x00158D00027AE687 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
18:03:08:746 0x00158D00027AE687 extract Xiaomi special attribute 0xFF01
18:03:08:746 	01 battery 2975 (0x0B9F)
18:03:08:746 	03 temperature 30 °C
18:03:08:746 	04 unknown 5032 (0x13A8)
18:03:08:746 	05 RSSI dB (?) 345 (0x0159)
18:03:08:746 	06 LQI (?) 4294967296 (0x0100000000)
18:03:08:746 	08 unknown 516 (0x0204)
18:03:08:746 	0a unknown 0 (0x0000)
18:03:08:746 	64 on/off 0
18:03:15:892 discovery for zombie 0x680ae2fffef06eca dropped, last try was 107 s ago
18:03:32:212 discovery for zombie 0x680ae2fffef06eca dropped, last try was 123 s ago
18:03:37:156 Current channel 25
18:03:37:165 Device TTL 932 s flags: 0x7
18:03:48:532 discovery for zombie 0x680ae2fffef06eca dropped, last try was 139 s ago
18:03:55:426 [INFO] - No button map for: lumi.sensor_magnet.aq2 endpoint: 0x01 cluster: BASIC (0x0000) command: 0x0A payload[0]: 001
18:03:55:426 ZCL attribute report 0x00158D0004451EB8 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
18:03:55:426 0x00158D0004451EB8 extract Xiaomi special attribute 0xFF01
18:03:55:426 	01 battery 2995 (0x0BB3)
18:03:55:426 	03 temperature 27 °C
18:03:55:426 	04 unknown 5032 (0x13A8)
18:03:55:426 	05 RSSI dB (?) 10 (0x000A)
18:03:55:426 	06 LQI (?) 4294967296 (0x0100000000)
18:03:55:426 	0a unknown 0 (0x0000)
18:03:55:426 	64 on/off 0
18:04:04:852 discovery for zombie 0x680ae2fffef06eca dropped, last try was 155 s ago
18:04:24:532 discovery for zombie 0x680ae2fffef06eca dropped, last try was 175 s ago
18:04:29:205 dev /dev/ttyAMA0
18:04:29:205 GW firmware version: 0x26580700
18:04:29:205 GW firmware version shall be updated to: 0x26660700
18:04:37:155 Current channel 25
18:04:37:165 Device TTL 872 s flags: 0x7
18:04:44:211 discovery for zombie 0x680ae2fffef06eca dropped, last try was 195 s ago
18:04:48:136 remove outdated neighbor 0x4067

21 Sensors in the system mostly Aqara multi sensors, 2 IKEA unit and one Develco Norwegian HAN. All worked OK before the updated.

Uncertain if I am to upgrade to latest firmware or use a backup to downgrade. Please advice

**Comment by Mimiix** [comment]
Hi!

Your mesh is kind of "unhealthy". Zigbee is ment to be meshing thus a healthy mix of routers and sensors. With only 2 Routers and 21 sensors it isn't at this moment. To add to that: Xiaomi's tend to drop off when the host goes down. Most of the time they come back, sometimes they do not.

You might click the devices reset buttons and see what happens, sometimes they come back.

My advice: Add more routers so the mesh gets more healthy.

**Comment by baunan** [comment]
Thanks for the advice. I am not sure what the recommended combination between routers and sensors is. My sensors are not located very far from the Conbee II unit, so they are all within a 10meter radius. For the reason you mentioned I added an IKEA powered unit to act as a repeater so the the unit farthest away could have an alternative connection route and then lately one more to use as a switch for a fan. The sensors I use are a mixture of door/window sensors and multi sensors from Aqara 7 of each. As mentioned in the main post, after the upgrade the IKEA units started to drop in and out of the network some hours on and some off. First the one farthest away and then the repeater. After the a reboot I have not been able to get contact with them  again. As this installation in on my cabin I have not been able to try a reintegration yet. But are mostly concern if there is a software issue as this problem started after an upgrade as I didn't have any problems before.

![image](https://user-images.githubusercontent.com/59838425/98094936-3648e880-1e8a-11eb-9807-8d2e88aa6994.png)

**Comment by DibblesNL** [comment]
I am having the same issues. Upgraded to the latest Deconz and spent a day trying to get my sensors all to reconnect before giving up. Wish i had a more up to date backup of the previous version to restore.

**Comment by MattWestb** [comment]
@baunan you sensors with green line have OK signal and they is connection is no problem but its better if they having some router near so not need emptying the battery so fast and getting problem with to low power. The IKEA power outlet have one good radio module but sadly its one large kondensator mounted behind it and doing the antenna not working optimal but still better then the OSRAM plugs. Xaiomi sensors dont like changing their parent and its not easy way forcing them to pairing with one nearby parent is they have shusing one. Deleting one sensor and re pairing then very near the parent and then its paired moving it to its end position its the easiest in deCONZ. Also trying repairing them then they is in the  end position can working but normally need many tries for success.

Also checking that your wifi is not overlapping with you zigbee network can being one reason way the sensors loosing connection to there parents.

**Comment by baunan** [comment]
Thanks for all the advice given. 
What I did this weeken was to downgrade the deCONZ add-on to 6.3.0 which was the version before my problems started. Added an extension cable to the Conbee II to get it away from the computer and change the wifi 2.4 GHz channel to 1.  Added an additional IKEA repeater (USB version) The system is up again and looks healthy. The only issue I have now is these random dropout which makes the sensors unavailable for 15 seconds. I have quite a few dropouts during the day as one can see from the picture.

![image](https://user-images.githubusercontent.com/59838425/99188679-8747bf00-275d-11eb-80b7-4ce9b077a934.png)
The log only says this:
2020-11-14 11:13:08 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-11-14 11:13:08 DEBUG (MainThread) [pydeconz.websocket] Reconnecting to deCONZ in 15.
2020-11-14 11:13:23 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-11-14 11:13:23 DEBUG (MainThread) [pydeconz.websocket] Websocket running


Could anyone please give an advice on how to investigate these dropout further? I this a plugin or a Home Assistant integration issue?

**Comment by MattWestb** [comment]
Good that your Zigbee part have stabilisation and not making you crazy !!
I think its HA that have loosing the contact with deCONZ and trying reconnecting if i understanding the loog right.
But you is running deCONZ as one adon so its on the same Pi so something is locking the processes on the PI.
First making one backup of both HA and deCONZ if its starting being problems with your SD-Card (I have losing 3 SD-Cards that being killed on My Pi3B and Zero).
Also is good having one SD-Card that is fast for saving small data blocks and can handle it like the the A1 or A2 classes (Application Performance Class) but the Vx classes is not interesting for us (for video that saving large continues files and cant handle small blocks reading / writing fast).
HA have doing some rework of data storage (SQL-Light) that was blocking the processing and most is in place but the last is coming 0.118 so updating HA then the new release is coming in some days / week.

**Comment by MattWestb** [comment]
For try getting the zigbee mesh working better you can also trying repairing sensors that is not using one router that is near them to using one better one so they is getting better signal but its not easy getting them doing that in deCONZ but in ZHA its possible forcing pairing devices thru one router that you like.

**Comment by Mimiix** [comment]
@baunan Seems to be this: https://github.com/home-assistant/core/issues/37372

**Comment by baunan** [comment]
Just to give an update.
What I did this weekend was to go to the step of installing Home Assistant on an Intel Nuc i3 gen10 using Proxmox. 
This setup looks solid and so far not a single dropout of the Conbee II connected sensors has occured. So it could be that a RPi with and an A1 SD card wasn't fast enough for this application or started to be broken. 
I am still on deconz version 6.3.0 (2.05.81).

**Comment by oywino** [comment]
Why is it that this post headline says: eCONZ 6.4.1 (2.05.84) ?
What's the difference in those version numbers?   What is 6.4.1 ? 
I have deCONZ 2.08  (never seen the number 6.4.x anywhere)

**Comment by baunan** [comment]
Hi
The 6.4 is reffering to Home Assistant add-on version. As you can see from the attached picture of this addon's,  change log the deConz version is updated on regular basis.

![image](https://user-images.githubusercontent.com/59838425/103175647-ce9c9180-486b-11eb-8c69-5c408763b2d9.png)

**Comment by oywino** [comment]
Please excuse my ignorance, but what is Home Assistant Add-on ??
I have had Home Assistant running for several years now, but I have never seen anything called "Add-on" !

**Comment by baunan** [comment]
You can find it under the Supervisor menu and in the add-on store.

![image](https://user-images.githubusercontent.com/59838425/103231507-36201300-4938-11eb-95bc-4ec8e7aa6258.png)

**Comment by oywino** [comment]
I don't have any of those menus in my Home Assistant!
