### ISSUE TITLE
Paulmann 500.67 ZigBee Remote Gent

### ISSUE THREAD

**Issue by Wurmi1986** [dresden-elektronik/deconz-rest-plugin#3587]
- If you're unsure whether device support was already requested, please ask for advise in our Discord chat: https://discord.gg/QFhTxqN
--> I asked in Discord an get the Info that are some Infos missing in the past. Now i try to give all required Infos.

## Device

- Product name: Smart Home Zigbee Fernbedienung Gent
- Manufacturer: Paulmann Licht GmbH
- Model identifier: RemoteControl 
- Device type : Please remove all unrelated device types. 
  - Remote
  

## Screenshots
- Node Info panel

![image](https://user-images.githubusercontent.com/20789045/98032287-12e35680-1e14-11eb-97c0-fadea0e91d61.png)

  - Basic Cluster attributes in the Cluster Info panel.

![image](https://user-images.githubusercontent.com/20789045/98032180-e92a2f80-1e13-11eb-8074-3b161846b749.png)

- Level Control

![image](https://user-images.githubusercontent.com/20789045/98032576-7d949200-1e14-11eb-8b41-d31dc4887788.png)
![image](https://user-images.githubusercontent.com/20789045/98032611-89805400-1e14-11eb-96d6-8d3a4cf4d3db.png)

-Scenes

![image](https://user-images.githubusercontent.com/20789045/98032673-a026ab00-1e14-11eb-9bd8-0792d0b5be64.png)
![image](https://user-images.githubusercontent.com/20789045/98032704-afa5f400-1e14-11eb-8f12-474c0634d9f0.png)
![image](https://user-images.githubusercontent.com/20789045/98032770-c9dfd200-1e14-11eb-9cd4-883ba89ad0a5.png)
![image](https://user-images.githubusercontent.com/20789045/98032798-d2380d00-1e14-11eb-9fbc-46aba213a07b.png)

-Color Control

![image](https://user-images.githubusercontent.com/20789045/98032859-eb40be00-1e14-11eb-8a7a-9297d0016af6.png)
![image](https://user-images.githubusercontent.com/20789045/98032901-fa277080-1e14-11eb-8651-fcccecbd5696.png)
![image](https://user-images.githubusercontent.com/20789045/98032939-07dcf600-1e15-11eb-8dea-00d049d20b15.png)
![image](https://user-images.githubusercontent.com/20789045/98032967-16c3a880-1e15-11eb-8fbc-00d1ce1d3b12.png)

-ZLL commissioning

![image](https://user-images.githubusercontent.com/20789045/98033043-2f33c300-1e15-11eb-823d-9e2470d529b1.png)

If there are information missing let me know and i will try to provide them.

best regard

**Comment by Wurmi1986** [comment]
Is there a chance to integrate the device? Or is there still information missing?
Best regards
Wurmi

**Comment by BiberM** [comment]
I own the same remote and would like to use it with the Phoscon App.

I did some more screenshots from the attributes table of the above mentioned clusters:
- 0300 Color Control
![Cluster_0300ColorControl_01](https://user-images.githubusercontent.com/11739148/100278384-0d85b180-2f65-11eb-8bae-5a1eaaa996c1.png)
![Cluster_0300ColorControl_02](https://user-images.githubusercontent.com/11739148/100278385-0d85b180-2f65-11eb-8f27-50c8880596e3.png)
![Cluster_0300ColorControl_03](https://user-images.githubusercontent.com/11739148/100278387-0e1e4800-2f65-11eb-9dbc-96dc6c4c40b3.png)
![Cluster_0300ColorControl_04](https://user-images.githubusercontent.com/11739148/100278388-0e1e4800-2f65-11eb-8912-dec03a34b4ea.png)
![Cluster_0300ColorControl_05](https://user-images.githubusercontent.com/11739148/100278389-0e1e4800-2f65-11eb-928e-c9234fd25389.png)
![Cluster_0300ColorControl_06](https://user-images.githubusercontent.com/11739148/100278390-0eb6de80-2f65-11eb-97ce-eb5b50914ccb.png)
![Cluster_0300ColorControl_07](https://user-images.githubusercontent.com/11739148/100278392-0eb6de80-2f65-11eb-8d72-4710b3c706e6.png)
![Cluster_0300ColorControl_08](https://user-images.githubusercontent.com/11739148/100278394-0eb6de80-2f65-11eb-976d-8f20ff564ec9.png)
![Cluster_0300ColorControl_09](https://user-images.githubusercontent.com/11739148/100278395-0f4f7500-2f65-11eb-8c39-a0c544fb894b.png)
![Cluster_0300ColorControl_10](https://user-images.githubusercontent.com/11739148/100278397-0f4f7500-2f65-11eb-96bf-49352916f89d.png)
![Cluster_0300ColorControl_11](https://user-images.githubusercontent.com/11739148/100278374-0bbbee00-2f65-11eb-9716-46a34c49bceb.png)

- 0005 Scenes
![Cluster_0005Scenes_01](https://user-images.githubusercontent.com/11739148/100278375-0c548480-2f65-11eb-9b9e-4708ca48bf42.png)
![Cluster_0005Scenes_02](https://user-images.githubusercontent.com/11739148/100278377-0c548480-2f65-11eb-99cf-1858e450ca29.png)

- 0006 On Off
![Cluster_0006OnOff_01](https://user-images.githubusercontent.com/11739148/100278379-0c548480-2f65-11eb-9d16-d0f4e90aed1a.png)
![Cluster_0006OnOff_02](https://user-images.githubusercontent.com/11739148/100278380-0ced1b00-2f65-11eb-8523-d16785d0b4f6.png)

- 0008 Level Control
![Cluster_0008LevelControl_01](https://user-images.githubusercontent.com/11739148/100278381-0ced1b00-2f65-11eb-816d-66c40355c717.png)
![Cluster_0008LevelControl_02](https://user-images.githubusercontent.com/11739148/100278383-0d85b180-2f65-11eb-9fd2-66231983db7d.png)

Addionally I turned on debug mode and dumped the output. While in debug mode I used the Signal Monitor PLugin and pressed some buttons on the remote.
[Paulmann_500.67.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5599146/Paulmann_500.67.txt)


What else do you need?

**Comment by Artur-Fedjukevits** [comment]
I have the same remote control. I would also be very grateful to see this device as supported.

**Comment by Kilowatt-W** [comment]
Same for me, hoping to get it online some day :-)

**Comment by OderDochNicht** [comment]
Same for me! Would be nice if the Q remotes will work with deconz sometimes.
