### ISSUE TITLE
Revolt NX-4911-675 Thermostat

### ISSUE THREAD

**Issue by kgorszczyk** [dresden-elektronik/deconz-rest-plugin#3588]
## Device

- Product name: Revolt NX-4911-675
- Manufacturer: (deCONZ GUI:) _TYST11_kfvq6avy
- Model identifier: (deCONZ GUI:) fvq6avy
- Device type : Thermostat
- Product page: [https://www.revolt-power.de/Weltweit-steuerbares-Heizkoerper-Design-Thermostat-NX-4911-919.shtml](https://www.revolt-power.de/Weltweit-steuerbares-Heizkoerper-Design-Thermostat-NX-4911-919.shtml)

## Screenshots

Node Info Panel:
<img width="810" alt="Bildschirmfoto 2020-11-04 um 12 26 49" src="https://user-images.githubusercontent.com/15107518/98106062-2553a380-1e99-11eb-9d58-2f9d3de9eb7d.png">

Basic Cluster:
<img width="876" alt="Bildschirmfoto 2020-11-04 um 12 27 02" src="https://user-images.githubusercontent.com/15107518/98106092-313f6580-1e99-11eb-9624-886508e7f69a.png">

**Comment by Mimiix** [comment]
@Smanar This looks like one of your funny tuya thingys. What interests me is that it's already given a name.

**Comment by kgorszczyk** [comment]
After some Googeling it seems that it's the same device as mentioned in #1927
Original Brand Name: Siterwell
Original Model Number GS361A
According to the Manual (http://www.smart9.com.cn/wp-content/uploads/2019/10/Siterwell-ZigBee-Radiator-Thermostat-GS361A-H04-User-Manual.pdf) they do seem to be Tuya devices

**Comment by kgorszczyk** [comment]
Duplicate of #3381
