### ISSUE TITLE
Ikea firmware non-lights

### ISSUE THREAD

**Issue by ronaldvans** [dresden-elektronik/deconz-rest-plugin#359]
I run the Raspbee module with deconz 2.04.99. I have several Ikea Tradfri remotes and motion sensors that are still on 1.1 instead of the newer 1.2 firmware. Having followed the instructions I ran the script, checked that the OTAU files had correctly been downloaded and restarted deconz. I must be missing something as to date the sensors and remotes have not updated. I know battery powered devices may take a long time but this is taking weeks already!

**Comment by ebaauw** [comment]
After deCONZ has found the new firmware for the device, you need to start the update manually (from the _STD OTAU Plugin_ panel.  Make sure to click the remote or wave in front of the sensor to wake them.  The update itself takes several hours and will drain the remote's battery significantly (100% to 60% on the dimmer).

**Comment by ronaldvans** [comment]
Thanks, will try!
