### ISSUE TITLE
Zigbee switch module MS-104Z (Moes?)

### ISSUE THREAD

**Issue by petosak** [dresden-elektronik/deconz-rest-plugin#3595]
## Device

- Product name: Zigbee switch module MS-104Z (also MS-104BZ, MS-105Z, MS-105BZ) 
- Manufacturer: _TYZB01_iuepbmpv
- Model identifier: TS0121
- Device type : 
  - Switch - wall mount switch (https://zigbee.blakadder.com/Moes_MS-104Z-1.html)

## Screenshots

  Required screenshots:
  - Endpoints and clusters of the node
  - Node Info panel
![image](https://user-images.githubusercontent.com/28576930/98276155-dd667680-1f95-11eb-8917-1f59a7a5031e.png)

  - Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/28576930/98276057-b9a33080-1f95-11eb-9dfa-9ecd613b1fe3.png)

![image](https://user-images.githubusercontent.com/28576930/98276375-28808980-1f96-11eb-8537-eb5853e6c7f3.png)
![image](https://user-images.githubusercontent.com/28576930/98276460-4bab3900-1f96-11eb-9030-8376c40c197a.png)

Phoscon shows me as light with picture of plug...
![image](https://user-images.githubusercontent.com/28576930/98276681-9f1d8700-1f96-11eb-96de-495d4987eade.png)

But it's wall mount switch here:
https://zigbee.blakadder.com/Moes_MS-104Z-1.html

I have HASSIO on RPI4 with ConBee2

**Comment by Mimiix** [comment]
Screenshots of the other clusters are missing. Please attach all of them.

**Comment by petosak** [comment]
Sorry,
all clusters info here:
![image](https://user-images.githubusercontent.com/28576930/98338111-f14bc000-2009-11eb-9704-9fb84dc64d21.png)
![image](https://user-images.githubusercontent.com/28576930/98338152-04f72680-200a-11eb-8656-a923b2a32ef5.png)
![image](https://user-images.githubusercontent.com/28576930/98338189-1a6c5080-200a-11eb-805d-a94e79c8fa81.png)
![image](https://user-images.githubusercontent.com/28576930/98338214-2526e580-200a-11eb-866c-7dc0121b5855.png)
![image](https://user-images.githubusercontent.com/28576930/98338265-37088880-200a-11eb-9cae-ab421514165b.png)
![image](https://user-images.githubusercontent.com/28576930/98338295-44257780-200a-11eb-8a6a-0b5f036b8b13.png)
![image](https://user-images.githubusercontent.com/28576930/98338335-556e8400-200a-11eb-8913-059527b6b240.png)
![image](https://user-images.githubusercontent.com/28576930/98338410-6fa86200-200a-11eb-8063-7592caffe3f4.png)
![image](https://user-images.githubusercontent.com/28576930/98338430-77680680-200a-11eb-8522-8222257c15d0.png)
![image](https://user-images.githubusercontent.com/28576930/98338492-8ea6f400-200a-11eb-8e07-f6477a95a91a.png)
![image](https://user-images.githubusercontent.com/28576930/98338557-a5e5e180-200a-11eb-85e2-ca1599c8c9dd.png)
![image](https://user-images.githubusercontent.com/28576930/98338602-b433fd80-200a-11eb-98ce-3a1b3cc91b9f.png)

**Comment by Mimiix** [comment]
Thanks! that should do it.

**Comment by Smanar** [comment]
But this device is working naturaly ?

The plug picture, is from the device itself, it s an information send by the device.

**Comment by petosak** [comment]
It's different device.
It's light switch:
https://zigbee.blakadder.com/Moes_MS-104Z-1.html
And this is one side pf instruction manual:
![LightSwitch_0001](https://user-images.githubusercontent.com/28576930/98384674-5d501780-204e-11eb-8988-c632b5f37210.jpg)

**Comment by Smanar** [comment]
But it s not our fault ^^, It s tuya that write in his device "PLUG", we are just reading this value, it change nothing in working mode ?

**Comment by petosak** [comment]
Yeah. That's true. Tuya or Moes or WTF factory made this device clonning different device without sw changes. It works as they wrote, but in app looks weird. I have to suppress electrical measurement becase it really can't measure and change type of device.

**Comment by Thoky81** [comment]
Any idea how to pair this MS-104Z switch in deconz? I have followed the instruction: long press for beep twice then again long press for beep continuously and nothing is showing in phoscon or even in deconz UI. I am pairing it as a light. Thanks

**Comment by petosak** [comment]
You'll see it as a light...
![image](https://user-images.githubusercontent.com/28576930/101536344-2ac17380-399a-11eb-9179-ff0515784f45.png)

**Comment by Thoky81** [comment]
@petosak  OK but I dont see it there. Can you pls advice how to set the device in pairing mode? Thanks

**Comment by petosak** [comment]
When i connected device to line i heard sound and started pairing.
You should try turn on and off five times.
![image](https://user-images.githubusercontent.com/28576930/101537359-a1ab3c00-399b-11eb-9025-019930640424.png)

**Comment by Thoky81** [comment]
Well I dont know what is wrong but still no success to pair the device in phoscon 😔

**Comment by Smanar** [comment]
You don't see someting even in the deconz GUI ?
Hav you tried with logs enabled ? (Deconz / help / log)

**Comment by Thoky81** [comment]
No. Long pressing the button on the switch for 10s then the sound beeps continuously so it should be in paring mode. But no success to connecting it to deconz..

**Comment by Smanar** [comment]
Where have you see the long press during 10 s ?
You need to make 5 on/off, but to do that you need to add a physical switch, from this french forum on manual it s picture 4

https://easydomoticz.com/forum/viewtopic.php?f=28&t=10566&start=20

**Comment by Thoky81** [comment]
I think I have different device.![Uploading 101988389...]![Uploading 101988391...]

**Comment by Smanar** [comment]
Ha yes, right.
But you need to see something in deconz itself if the procedure is good, nothing special in logs (in deconz/help) ?

**Comment by Thoky81** [comment]
I think I know why I am not able to pair it. I tried to pair new aqara motion sensor today and I didnt success. So the problem must be somewhere else. I am running the deconz in docker/synology and have recently installed ssd cache. I will try to install the deconz on rpi to see if it helps. Before I will check the logs one more time..

**Comment by Thoky81** [comment]
So finally its working 🙏🏼. The issue was with last docker update for sure. I have loaded the previous network configuration from phoscon hiden menu and now its paired 😀 Thanks

**Comment by Smanar** [comment]
Lol, finally ^^

**Comment by Taemo** [comment]
> So finally its working 🙏🏼. The issue was with last docker update for sure. I have loaded the previous network configuration from phoscon hiden menu and now its paired 😀 Thanks

Hi I have a Tuya MS-104Z - pretty much identical (I think?) to the device you have here, I am trying to pair this with Home Assistant + Conbee ii Deconz - Rpi not Docker. I dont see to be able to pair it either. I have confirmed I am able to pair other devices.

Did you long press once on the modules button and get the Di-Di sound? or did you, long press-5sec-long press and get the long tone ?

Or did you use the power on-off  method ?

Cheers
Taemo

**Comment by Taemo** [comment]
Ok all,

Posting in case anyone else finds this, I have managed to get this working with Home Assistant Conbee ii 2 and Deconz

The Tuya MS-104Z instructions are a bit misleading, the "reset" button of the device does not see to trigger pairing mode, or at least I cant get it too!

Instead wiring it all up and switching the switch input 5 time (with a rocker that is on-off so 10 switches, 5 power events) that puts into a continuous beeping tone, continuous being continuous beep forever :) - at that point it pairs fine with deconz.

Comes up as 

Vendor_TZ3000_zmy1waw6
ModelTS011F
Version 65

And the beeping stops.

The only annoying thing is that the switch input can be switched to fast (on and off) cycle and miss the transition, its not a problem if its only 1 transition ie on to off, but if you go on-off-on within a second it will not register the the off or on state well. Thus requires another switch event to take effect.

Hope all that helps someones else.

Jamie

**Comment by DavidFFerreira** [comment]
Anyway to put it working with Zha?

**Comment by Mimiix** [comment]
@DavidFFerreira that's not what this git is for.

Closing and locking this issue as it is resolved.
