### ISSUE TITLE
Xiaomi Cube Rotation only gives values of 0

### ISSUE THREAD

**Issue by ldplusse** [dresden-elektronik/deconz-rest-plugin#362]
I have 3 Xiaomi Cubes and they all update the Rotation status with a value of 0.
The flipping/sides is working as it should.

Is on DeCONZ .99 using newest HomeSeer with the Jowihue plugin.
Other HomeSeer/Jowihue users report that the rotation is working.

Jowihue plugin author reports that it only receives the '0' value on my installation in the logs and that is also what i see in HomeSeer status. 

How to troubleshoot this?

**Comment by ebaauw** [comment]
Let's first check that the cube notifies deCONZ when it rotates.  In the deCONZ GUI, open the _Cluster Info_ panel for the _Analog Input (Basic)_ cluster (0x000C) of the cube's third endpoint (0x03).  Check that the _Present value_ attribute (0x0055) changes value when you rotate the cube.  Right turns should result in positive values, left turns in negative values.

If not, setup a binding between this cluster and the RaspBee's HA endpoint.  Open the _Bind Dropbox_ panel, drag the 0x000C cluster to the _Source_, drag the RaspBee's HA endpoint to the _Destination_ (make sure _Type_ is IEEE), and press _Bind_.

**Comment by ldplusse** [comment]
Thanks for the answer.
I use Conbee. I tryed your procedure, but cannot get it to bind. i just get a timeout. I have tryed to move, shake, rotate the device while binding and have it close to the ConBee, it just says 'Timeout.
Cluster Info:
![2018-01-14 20_17_11-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/34919736-6b606f24-f968-11e7-8697-928c61154e1c.png)
Cube to Source:
![2018-01-14 20_16_22-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/34919741-77518d2c-f968-11e7-8d85-e6f50fa033f5.png)
ConBee to Destination:
![2018-01-14 20_16_22-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/34919747-84ef6d3c-f968-11e7-87d6-8e32908e950e.png)
Binding:
![2018-01-14 20_14_57-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/34919752-8ee7dce8-f968-11e7-9e78-c662b59317f7.png)

Not sure if i am doing this correct. Its pretty confusing stuff in DeCONZ.

**Comment by ldplusse** [comment]
I got it Bind.
I pushed the button inside right after pushing bind.
Put it still only gives 0 in output.

**Comment by ebaauw** [comment]
That looks right to me, but you never know with Xiaomi.  I take it, the _Multistate input_ cluster does update when you shake, flip, push the cube?  

> In HS3 i can see it updates with the value of 0.

I don't know HS3, nor where it gets the updates from.  Would be interesting to know whether the cube actually sends, and deCONZ actually receives updates, but always with value 0, or whether the updates don't reach deCONZ.  Does the deCONZ REST API send websocket notifications (with `buttonevent` value 0)?

**Comment by ldplusse** [comment]
Yes the Multistate input is working.

When rotation it does send buttonevent value 0 trough the Rest API.
Other users of HomeSeer report that the Cube is working with DeCONZ and rotation.

**Comment by ebaauw** [comment]
I fear they might have changed the hardware and/or firmware.  My cube has a fourth attribute, 0xFF05, in the _Analog Input_ cluster.  Find the other differences (you might need to read each attribute of the _Basic_ cluster individually, while pressing the "inside" button - this might take a couple of attempts):
![untitled](https://user-images.githubusercontent.com/22179355/35008355-70d1fd66-fafc-11e7-8d01-5385072ea309.jpeg)
![untitled 2](https://user-images.githubusercontent.com/22179355/35007678-c16ea3de-fafa-11e7-83e5-5751d9b22224.jpeg)
![untitled 3](https://user-images.githubusercontent.com/22179355/35007696-c4d981ec-fafa-11e7-886d-6221fdb5486d.jpeg)

**Comment by superwerder** [comment]
OK, so after a lot of trying I found a way to get the values and they are identical to yours. Only thing is that 0x0012 and 13 are not "grey" in my setup.
And yeah, I also don't have the 0xFF05 attribute in the analog input cluster. Why is it called unknown?

**Comment by ebaauw** [comment]
Because it's manufacturer specific, not defined by the ZigBee Cluster Library.  I haven't been able to figure out what it's for.  Sometimes it changes value when I rotate the cube, sometimes it doesn't.  Haven't been able to detect a pattern in the values either.

**Comment by superwerder** [comment]
Ok. But as it changes it seems to be important. But why don't we have it. Could it be something with using conbee and not raspbee?

**Comment by ldplusse** [comment]
As superwerder commented.
We are both on the ConBee and i believe Erik is on the RaspBee. Is that right Erik?

We have another Cube user here in denmark confirmed working on the RaspBee.
I am hoping i can get my Cube tested, on his setup.

**Comment by ldplusse** [comment]
I checked my setup and i have the same values but also the two that is not gray and also missing the 0xFF05.
![2018-01-17 13_01_44-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/35043481-18c8b312-fb8d-11e7-9f5c-68a159af857e.png)
![2018-01-17 13_02_22-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/35043487-21dc46bc-fb8d-11e7-920f-744be4b867ce.png)
![2018-01-17 13_03_01-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/35043493-27202652-fb8d-11e7-8ae2-7faa334574ce.png)

**Comment by ebaauw** [comment]
I am on RaspBee, indeed, but I don't see how RaspBee vs ConBee could make a difference.  You might check the ConBee/RaspBee firmware, I'm on 0x261A0500, but, really that's a long shot.

> We have another Cube user here in denmark confirmed working on the RaspBee.
I am hoping i can get my Cube tested, on his setup.

If that would work, it would be interesting to know whether his cube works on your setup.

I have a ConBee lying around, used for ZigBee sniffing.  I could hook it up to my test Raspberry and pair my cube (I only have one) to it.  That will have to wait for the weekend, though - it's rather elaborate.

**Comment by ldplusse** [comment]
I have just arranged the test next tueday.
There is hardware change between RaspBee and ConBee and also the change in the operation system.

Not sure he is willing to lend me his Cube :-)
But is my Cube is working on his RaspBee, i dont see that a test with his Cube on my setup is needed.

**Comment by ldplusse** [comment]
i have an update. Today i tried one of my Cube's at anothers place.
When my Cube was connected to his RaspBee, it worked immediately with rotation.
I also had a ConBee, so we moved the Cube to his Conbee. There the rotation did not work. Only the multistate input was updating with values. It worked in the exact same way as on my ConBee.

So think we can deffently say that there is some different between the ConBee and the RaspBee.
How can i proceed finding the problem.

**Comment by manup** [comment]
There is no difference in hardware or software, I figure tge ConBee might just not have the latest firnware flashed?

**Comment by ldplusse** [comment]
DeCONZ does not say i have a firmware update available.
![2018-01-25 12_54_48-kodi baretten dk - forbindelse til fjernskrivebord](https://user-images.githubusercontent.com/33283434/35387203-1239c8d6-01cf-11e8-9613-250251ae2934.png)

**Comment by superwerder** [comment]
I have the same versions as Idplusse.

**Comment by ldplusse** [comment]
I have checked my FTDI version and it is the newest version 2.12.28
I cannot see any 'manuel' firmware update. So assuming that my ConBee firmware is also the newest available.
How can we proceed with further troubleshooting.

**Comment by ebaauw** [comment]
The latest firmware is 0x261A0500, as I mentioned above.  deCONZ doesn’t prompt to install this version, you need to install it manually.

**Comment by ldplusse** [comment]
Could not find any firmware besides the link.
The reference in the #230 link is not for Windows.

I need info on how to update the ConBee firmware from a windows PC.
All this github is not easy to understand for a windows guy.

And as i have seen DeCONZ auto ask me to update firmware, i dont understand why some firmware versions does not.

**Comment by ebaauw** [comment]
You’re on Windows!  That would have been worth mentioning.  Can some-one please double-check that the Windows distribution contains the latest `general.xml` file, which includes the _Analog Input_ cluster?  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/138#issuecomment-324911430.

**Comment by manup** [comment]
>You’re on Windows! That would have been worth mentioning. Can some-one please double-check that the Windows distribution contains the latest general.xml file, which includes the Analog Input cluster?

You're right it's missing, will be updated in the next release.

**Comment by ldplusse** [comment]
Great findings guys.
Sorry for not providing the 'Windows' information.

Looking forward to the next release.
Any ETA on that.

**Comment by manup** [comment]
New version for all platforms should arrive this week.

**Comment by manup** [comment]
Hi, version 2.05.00 for Windows and Ubuntu is online:
 
https://www.dresden-elektronik.de/deconz/

**Comment by ldplusse** [comment]
Perfekt.
And it works :-)

Thanks for the fix.
