### ISSUE TITLE
Various motion sensors stopped sending status "motion detected"

### ISSUE THREAD

**Issue by vahaldor** [dresden-elektronik/deconz-rest-plugin#3620]
## Describe the bug
I moved to another flat. Reinstalled Rpi 4 with a hassio. Connected Conbee II. Installed hassio deconz add-on. Updated conbee II firmware to 26660700.

IMMAX Multisensor 4in1 worked about two days and suddenly stopped sending one sensor data, the motion sensor. Other sensors (luminance, humidity, temperature) work perfectly.
All three Xiaomi MiSensor stopped within next day to send the changes status to "motion detected".
Respectively even in Phoscon they do not show change to motion detected. So I see "clear" instead "motion detected" in home assistant as well.

I reinstalled hassio and resseted conbee. They dont even start working. Sensor detected in Phoscon but since then it never detected motion.

The same configuration worked smoothly for a year with no troubles. The only difference in new flat is the update to new firmware. The fact that they dont even start working again for a while looks to me to be somewhere between the sensors and the conbee.

## Steps to reproduce the behavior

For me, even fresh reinstall does not change anything. I cannot reproduce this as it does not work completely.

## Expected behavior

Motion detected.

## Environment

 - Host system: Raspberry Pi 4 4GB
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: (6.4.1)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? NO

## deCONZ Logs

These commands does not work in hassio SSH terminal.

**Comment by petr-vytlacil** [comment]
I have same problem.

**Comment by Mimiix** [comment]
Can you provide logs?

**Comment by vahaldor** [comment]
Can you tell me how can I export them, please?

**Comment by Smanar** [comment]
>deCONZ version: (6.4.1)

Can you check again your version in phoscon/gateway pls ?

**Comment by vahaldor** [comment]
I updated the firmware.
If you mean the update of deconz I probably installed newest version after the fresh install of home assistant.

![image](https://user-images.githubusercontent.com/6329152/98799712-c1d4f300-240f-11eb-8cbe-3878c718969d.png)

**Comment by petr-vytlacil** [comment]
My versions, and I have same problem.
![image](https://user-images.githubusercontent.com/13149261/98799822-e7fa9300-240f-11eb-84ab-d09ccdd794a0.png)

**Comment by vahaldor** [comment]
Interesting, why the system does not propose an update to me?

**Comment by Smanar** [comment]
One of you have the gui to check something ?

**Comment by petr-vytlacil** [comment]
![image](https://user-images.githubusercontent.com/13149261/98803437-09aa4900-2415-11eb-8b1c-062102568f01.png)

**Comment by Smanar** [comment]
You are not on the good cluster.
- Click on the second circle on the node title, it will expand cluster list
- Click on cluster 0x0406, it will expend cluster tab
- The attribute table is on the bottom tab, but with bad values.
- Double clic on attribute 0x0000, it will show a window
- Press "Read" with making the device awake

And you will have a value or an error message.

**Comment by vahaldor** [comment]
I dont even have the motion sensors visible in the deconz map. The multisensor with four sensors dont have 0x0406.

**Comment by petr-vytlacil** [comment]
![image](https://user-images.githubusercontent.com/13149261/98809944-ae7d5400-241e-11eb-9e10-689b31d0ff0d.png)

**Comment by vahaldor** [comment]
I also miss the motion measurement which is 0406? Dont know.
![image](https://user-images.githubusercontent.com/6329152/98812207-5c3e3200-2422-11eb-9ea1-42a9449d059d.png)
![image](https://user-images.githubusercontent.com/6329152/98812236-6b24e480-2422-11eb-8748-22ca184cd87f.png)

**Comment by vahaldor** [comment]
Xiaomi Motion Sensor detects motion after several resets, for now, I can report how quickly it will stop.

I would love to provide some logs but I need guidance how to do that. Thanks.

**Comment by petr-vytlacil** [comment]
Plese primarily fix the issue with IMMAX Multisensor 4in1 worked which dont detect motion. Thank you .-)

**Comment by Smanar** [comment]
Was for the Xiaomi, the Immax use cluster 0x0500, and not the same working mode.
And yes there is some logs for IAS part
>DBG_Printf(DBG_ZCL, "IAS Zone Status Change, status: 0x%04X, zoneId: %u, delay: %u\n", zoneStatus, zoneId, delay);

To enable debug https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags

**Comment by vahaldor** [comment]
Where do we use these commands? They dont work in HA SSH terminal

**Comment by petr-vytlacil** [comment]
> Was for the Xiaomi, the Immax use cluster 0x0500, and not the same working mode.
> And yes there is some logs for IAS part
> 
> > DBG_Printf(DBG_ZCL, "IAS Zone Status Change, status: 0x%04X, zoneId: %u, delay: %u\n", zoneStatus, zoneId, delay);
> 
> To enable debug https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags
> 
> The usefull ones are `--dbg-info=2 --dbg-error=2` you can set all other to 0

Is any way how enable debug on Windows OS? THX

**Comment by vahaldor** [comment]
Btw I opened a thread with a bug report related to a particular installation. This is offtopic and destroys this thread.

**Comment by Smanar** [comment]
Not sure this bug was specific to an installation, if you have same ?

**Comment by vahaldor** [comment]
He has Windows 10. So I have to install raspberry OS in order to produce logs?

**Comment by SwoopX** [comment]
Reading the attribute configuration requires the device to be awake, so you need to push the physical button 1-2 seconds before pressing the read button.

**Comment by vahaldor** [comment]
Are you talking about the IMMAX multisensor we both with Petr Vystrcil have? There is only one button

**Comment by Smanar** [comment]
You can't use command line on Hassio ? There is no way to obtain log using HA ?
For windows it s worse, I know a method, but never tried it, and idk if it work ...

**Comment by vahaldor** [comment]
The terminal in HA is a simple one. No /usr/ folder there, so the above mentioned way is not possible. They expect to run raspbian. There is a log though in deconz addon but I cannot alter the output:

20:06:04:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:09:539 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:06:09:539 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:06:09:893 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:06:09:893 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:06:10:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:12:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:12:604 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:06:12:604 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:15:943 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:06:15:943 ZCL attribute report 0x00158D0003CE0A2C for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:06:18:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:20:033 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0402 command: 0x0A payload[0]: 000
20:06:20:033 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0402, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:20:500 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0405 command: 0x0A payload[0]: 000
20:06:20:500 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0405, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:25:220 ZCL attribute report 0xCCCCCCFFFE3CD09E for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:25:246 ZCL attribute report 0xCCCCCCFFFE3CD09E for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:28:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:28:493 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:06:28:493 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:30:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:33:529 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:06:33:529 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:37:223 [INFO] - Button 1002 On
20:06:37:232 rule event /sensors/17/state/lastupdated: 0 -> 0
20:06:37:232 trigger rule 46 - Rule PUSHDIMUP_ON
20:06:37:322 ZCL attribute report 0x000B57FFFED6B06C for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:38:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:38:730 [INFO] - Button 2001 Move down
20:06:38:739 rule event /sensors/17/state/lastupdated: 0 -> 0
20:06:38:739 trigger rule 51 - Rule PUSHDIMDOWN_START
20:06:40:330 [INFO] - Button 2003 Stop
20:06:40:337 rule event /sensors/17/state/lastupdated: 0 -> 0
20:06:40:337 trigger rule 50 - Rule PUSHDIMDOWN_STOP
20:06:40:434 ZCL attribute report 0x000B57FFFED6B06C for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:06:43:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:51:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:06:53:355 skip binding for attribute reporting of ep: 0x01 cluster 0x0001 (end-device might sleep)
20:06:56:870 Current channel 20
20:06:56:878 Device TTL 6899 s flags: 0x7
20:06:59:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:01:355 skip binding for attribute reporting of ep: 0x01 cluster 0x0001 (end-device might sleep)
20:07:02:928 dev /dev/ttyAMA0
20:07:02:929 GW firmware version: 0x26660700
20:07:02:929 GW firmware version is up to date: 0x26660700
20:07:04:780 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:04:781 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:06:148 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:06:148 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:07:354 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:08:268 ZCL attribute report 0xEC1BBDFFFEF433B4 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:07:09:348 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:07:09:348 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:07:10:389 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:10:389 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:12:809 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:12:809 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:13:355 skip binding for attribute reporting of ep: 0x01 cluster 0x0001 (end-device might sleep)
20:07:14:384 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:07:14:384 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:07:15:519 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:15:519 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:18:024 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:18:024 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:20:433 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:20:433 ZCL attribute report 0x00158D0003CE0A2C for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:21:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:21:486 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:21:486 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:24:427 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:24:427 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:25:355 skip binding for attribute reporting of ep: 0x01 cluster 0x0001 (end-device might sleep)
20:07:26:793 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:26:793 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:31:375 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:31:375 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:34:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:36:355 skip binding for attribute reporting of ep: 0x01 cluster 0x0001 (end-device might sleep)
20:07:36:578 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:07:36:578 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:07:37:644 Bind response success for 0x000d6ffffe40055e ep: 0x01 cluster: 0x0500
20:07:39:002 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:39:002 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:39:064 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:39:064 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:41:621 [INFO] - No button map for: 4in1-Sensor-ZB3.0 endpoint: 0x01 cluster: 0x0400 command: 0x0A payload[0]: 000
20:07:41:621 ZCL attribute report 0x000D6FFFFE40055E for cluster: 0x0400, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:07:44:127 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:44:127 ZCL attribute report 0x00158D0003CF5132 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:44:782 [INFO] - No button handler for: TRADFRI remote control endpoint: 0x01 cluster: 0x0001 command: 0x0A payload[0]: 021
20:07:44:782 ZCL attribute report 0x680AE2FFFE838CD7 for cluster: 0x0001, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
20:07:45:346 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:45:346 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:46:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:52:086 [INFO] - No button map for: lumi.sensor_motion endpoint: 0x01 cluster: 0x0406 command: 0x0A payload[0]: 000
20:07:52:086 ZCL attribute report 0x00158D0003D11CF6 for cluster: 0x0406, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
20:07:54:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:56:355 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
20:07:56:869 Current channel 20

**Comment by SwoopX** [comment]
You got tons of motion reports in there. Not from the Immax (I'm surprised that it worked anyway), but from the Xiaomi's...

**Comment by vahaldor** [comment]
I see that. I did reset all three xiaomi and they seem to work for now but as I said previously they lost motions in a couple of days. I did fresh install of HA about three times and it happened everytime after several days.

Immax does not work but also worked at the beginning when I linked it for the first time.

**Comment by SwoopX** [comment]
Regarding the Immax: lucky you. Got one donated by a user and only got it to work with some unknown black magic. That thing simply seem to refuse to send the required IAS reports and there's nothing in the sniffer logs. I'd rather suspect a firmware issue and some feedback I read in some issue here just recently went into that direction as well.

**Comment by vahaldor** [comment]
I reset the Conbee, deleted all entities, deleted integration and addon, restarted HA, set up all zigbee devices from scratch and found that one bulb was behaving unpredictably. So I did not add it to the network and the IMMAX motion sensor begun working. Right now, the luminance sensor seems to return different values. However, motion has been detected several times since then... I would love to uncover this behavior deeper but somebody has to lead me.

![image](https://user-images.githubusercontent.com/6329152/99714164-8d170a80-2aa5-11eb-8b32-427a9c5d1317.png)
