### ISSUE TITLE
OWON Zigbee Thermostat

### ISSUE THREAD

**Issue by leonardpitzu** [dresden-elektronik/deconz-rest-plugin#3627]
## Device

- Product name: Zigbee Smart Thermostat
- Manufacturer: OWON Technology Inc.
- Model identifier: PCT502
- Device type : Thermostat

- Product name: Zigbee Smart Thermostat
- Manufacturer: OWON Technology Inc.
- Model identifier: PR412C
- Device type : Thermostat (relay i guess?!?!)

The device bought comes in 2 pieces - one "desk clock" which measures temperature and humidity and is the actual "brain" of the thermostat (stores date/time/schedule) - and one relay connected to mains (it has 2 internal relays for various boilers and heaters - most basic central heating system in Europe is a on/off system). Product is labeled on the box as "OWON Zigbee Smart Thermostat PCT502-Z" without mentioning the second device product code.
The "desk clock" contains also a rechargeable battery.

Edit: pairing goes through the desk clock only. If the relay is not powered the thermostat complaints that "network is disconnected"

https://www.owon-smart.com/2019-wholesale-price-zigbee-temperature-humidity-sensor-zigbee-combi-boiler-eu-smart-thermostat-temperature-controller-502-owon-product/

## Screenshots

![2020-11-10-163517_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688175-4160b480-2373-11eb-8f80-4942ec67ad6c.png)
![2020-11-10-163528_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688179-4291e180-2373-11eb-95a0-00db8bfc6d03.png)
![2020-11-10-163546_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688183-432a7800-2373-11eb-87fe-3eed19c6ab4f.png)
![2020-11-10-163559_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688187-43c30e80-2373-11eb-8cac-cc8dfd90148d.png)
![2020-11-10-163609_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688193-445ba500-2373-11eb-8470-4cffbf0638e0.png)
![2020-11-10-163626_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688196-445ba500-2373-11eb-940e-ae5f6081dce5.png)
![2020-11-10-163633_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688199-44f43b80-2373-11eb-8fb9-083626774fbf.png)
![2020-11-10-163647_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688201-458cd200-2373-11eb-9814-87a21ea63923.png)
![2020-11-10-163651_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688204-458cd200-2373-11eb-87a2-48d8f03b74f8.png)
![2020-11-10-163702_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688206-46256880-2373-11eb-8aae-95d308b8073f.png)
![2020-11-10-163710_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688209-46bdff00-2373-11eb-999d-256fe430bbe0.png)
![2020-11-10-163717_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688211-47569580-2373-11eb-9304-eaafdbee01cf.png)
![2020-11-10-163722_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688215-47569580-2373-11eb-948a-23935b1a2578.png)
![2020-11-10-163731_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688216-47ef2c00-2373-11eb-952b-1466db6657b9.png)
![2020-11-10-163748_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688219-4887c280-2373-11eb-8fce-78dde5f1a177.png)
![2020-11-10-163756_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688222-4887c280-2373-11eb-8021-87dc77b58ed3.png)
![2020-11-10-163810_1920x1200_scrot](https://user-images.githubusercontent.com/4321813/98688227-49205900-2373-11eb-888c-e180bc747bae.png)

**Comment by SwoopX** [comment]
Tbh, I got no clue how to properly support that thing, especially remotely and without traffic sniffing. I could give it a shot but you should provide additional screenshots of the thermostat cluster's attributes while those have been read and be able to compile a test version of the REST API plugin yourself to test.

**Comment by leonardpitzu** [comment]
Compiling would be no issue as is debugging. Sniffing in zigbeeland I do not know but I am willing to start working on it

**Comment by SwoopX** [comment]
Sounds good. Then don't forget about the screenshots. I guess I could give you something at hand almost as good as a bare zigbee sniffer ;)

**Comment by leonardpitzu** [comment]
Basic cluster
![basic](https://user-images.githubusercontent.com/4321813/99960511-88986d80-2d95-11eb-8322-76a0992fdded.png)

**Comment by leonardpitzu** [comment]
identify cluster
![identify](https://user-images.githubusercontent.com/4321813/99960553-9948e380-2d95-11eb-8a6d-74e860ddea87.png)

**Comment by leonardpitzu** [comment]
groups cluster
![group 1](https://user-images.githubusercontent.com/4321813/99960588-abc31d00-2d95-11eb-9f6c-0b9c6b7a774f.png)
![group 2](https://user-images.githubusercontent.com/4321813/99960591-acf44a00-2d95-11eb-827e-96ea87c71c0f.png)

**Comment by leonardpitzu** [comment]
scenes cluster
![scenes 1](https://user-images.githubusercontent.com/4321813/99960619-b7aedf00-2d95-11eb-8682-d0c1078c1dde.png)
![scenes 2](https://user-images.githubusercontent.com/4321813/99960631-bb426600-2d95-11eb-8553-bed48a14a87c.png)
![scenes 3](https://user-images.githubusercontent.com/4321813/99960635-bd0c2980-2d95-11eb-926f-255bbc7dc32e.png)
![scenes 4](https://user-images.githubusercontent.com/4321813/99960639-be3d5680-2d95-11eb-9549-f41dd286d175.png)

**Comment by leonardpitzu** [comment]
thermostat cluster

set & get weekly schedule result in FAILURE (yet there is a saved schedule); clearing the schedule works in deconz and in reality
get relay status log results in unsup_cluster_command
the rest is depicted below

![thermosta 1](https://user-images.githubusercontent.com/4321813/99960884-28ee9200-2d96-11eb-80a9-cd1d35942c61.png)
![thermostat 2](https://user-images.githubusercontent.com/4321813/99960886-2a1fbf00-2d96-11eb-8fc1-7098e26cf82f.png)
![thermostat 3](https://user-images.githubusercontent.com/4321813/99960889-2b50ec00-2d96-11eb-9e7c-965bbb3320b8.png)
![thermostat 4](https://user-images.githubusercontent.com/4321813/99960894-2be98280-2d96-11eb-8a02-f6afed737369.png)
![thermostat 5](https://user-images.githubusercontent.com/4321813/99960897-2d1aaf80-2d96-11eb-9cd0-f0e7f442e940.png)

**Comment by leonardpitzu** [comment]
thermostat user interface configuration cluster
![Uploading thermostat user interface configuration.png…]()

**Comment by leonardpitzu** [comment]
relative humidity measurement cluster
![relative humidity measurement](https://user-images.githubusercontent.com/4321813/99961331-e7aab200-2d96-11eb-8f1a-a4d3cf0db87e.png)

**Comment by leonardpitzu** [comment]
unknown cluster
![unknown](https://user-images.githubusercontent.com/4321813/99961350-f2654700-2d96-11eb-9571-e66f00fd7572.png)

**Comment by leonardpitzu** [comment]
on/off cluster
![on_off](https://user-images.githubusercontent.com/4321813/99961378-fee99f80-2d96-11eb-9272-a52d4954c6e5.png)

**Comment by leonardpitzu** [comment]
time cluster
![time](https://user-images.githubusercontent.com/4321813/99961395-06a94400-2d97-11eb-9528-33ab1a19586b.png)

**Comment by leonardpitzu** [comment]
Is there anything more i can provide or do in order to help with the issue?

**Comment by SwoopX** [comment]
I'd need toe remaining thermostat cluster attributes from attribute 0x0012 downwards. I'm afraid you'll probably need to manually read each of them via a double click on the value.

**Comment by leonardpitzu** [comment]
![2021-01-20-152400_1680x1000_scrot](https://user-images.githubusercontent.com/4321813/105181299-4ccf1980-5b34-11eb-83ec-78828dd7af50.png)
![2021-01-20-152332_1680x1000_scrot](https://user-images.githubusercontent.com/4321813/105181304-4d67b000-5b34-11eb-8e5c-f9f902fdecdf.png)
![2021-01-20-152345_1680x1000_scrot](https://user-images.githubusercontent.com/4321813/105181306-4f317380-5b34-11eb-9877-9643a51da855.png)
![2021-01-20-152353_1680x1000_scrot](https://user-images.githubusercontent.com/4321813/105181310-5062a080-5b34-11eb-8e9b-36cc0e59dca8.png)
