### ISSUE TITLE
Device name: SilverCrest Smart Motion Sensor

### ISSUE THREAD

**Issue by marval** [dresden-elektronik/deconz-rest-plugin#3628]
## Device

- Product name: SilverCrest Smart Motion Sensor
- Manufacturer: _TZ1800_fcdjzz3s
- Model identifier: TY0202
- Device type : 
  - Sensor

## Screenshots
  - Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/1443599/98692636-a1555c00-236f-11eb-9845-a8224051a71f.png)
  - Node Info panel
![image](https://user-images.githubusercontent.com/1443599/98692677-ad411e00-236f-11eb-89b3-8968cb195829.png)
  - Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/1443599/98692742-bf22c100-236f-11eb-8f62-67c4e7187591.png)
  - Power Configuration
![image](https://user-images.githubusercontent.com/1443599/98719547-2f413f00-2390-11eb-8427-8ce567e8cfbd.png)
  - Identify
![image](https://user-images.githubusercontent.com/1443599/98719615-47b15980-2390-11eb-90d6-252d21a8dccf.png)
  - IAS Zone
![image](https://user-images.githubusercontent.com/1443599/98719667-5566df00-2390-11eb-8b5c-41439be2f024.png)
  - Diagnostics
![image](https://user-images.githubusercontent.com/1443599/98719727-66afeb80-2390-11eb-854e-2a7df06003f2.png)
  - OTAU
![image](https://user-images.githubusercontent.com/1443599/98719780-762f3480-2390-11eb-853e-9d35d73baa6a.png)

**Comment by Mimiix** [comment]
@marval Missing screenshots of all clusters. 

A

**Comment by marval** [comment]
Just added them. I was not aware they were required since they were not part of the template.

**Comment by Mimiix** [comment]
You and I are both right. They are in the template, but a bit down:

![image](https://user-images.githubusercontent.com/43333120/98780578-48300b80-23f5-11eb-9dc6-a7fb817ed400.png)

I might change that to show a bit earlier.

Thanks for adding :)!
