### ISSUE TITLE
Samsung Leak Sensor First Generation

### ISSUE THREAD

**Issue by adawalli** [dresden-elektronik/deconz-rest-plugin#3629]
## Device

- Product name: Samsung SmartThings Water Leak Sensor
- Manufacturer: SmartThings
- Model identifier: moisturev4
- Device type : Please remove all unrelated device types. 
  - Water Sensor
  - Thermostat

### All Clusters
![image](https://user-images.githubusercontent.com/14079121/98751874-f2c11380-238e-11eb-8724-2e0e4c139334.png)

### Basic
![image](https://user-images.githubusercontent.com/14079121/98751438-1afc4280-238e-11eb-8764-cbfd8870e658.png)

### Power
![image](https://user-images.githubusercontent.com/14079121/98751479-349d8a00-238e-11eb-9a3e-3ab9cc175769.png)

![image](https://user-images.githubusercontent.com/14079121/98751513-3ff0b580-238e-11eb-918c-a663e4e4f827.png)

### Binary Input (Basic) Cluster
![image](https://user-images.githubusercontent.com/14079121/98751612-6c0c3680-238e-11eb-988c-7b2c53c05bed.png)

### Poll Control
![image](https://user-images.githubusercontent.com/14079121/98751655-8219f700-238e-11eb-992c-a82a50e0105e.png)

### Temperature Measurement
![image](https://user-images.githubusercontent.com/14079121/98751693-9231d680-238e-11eb-92c9-68c9c83ad54d.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/14079121/98751723-a544a680-238e-11eb-8913-620b79deb8b1.png)

### OTAU
![image](https://user-images.githubusercontent.com/14079121/98751764-bab9d080-238e-11eb-8229-47303ec755c3.png)

**Comment by adawalli** [comment]
Is there any other information I can provide that would be of use?

**Comment by Mimiix** [comment]
Nope, all is there. You need to wait for a dev to integrate it :)

**Comment by SwoopX** [comment]
@adawalli The node info panel screenshot is missing here.
