### ISSUE TITLE
Sonoff ZBMINI

### ISSUE THREAD

**Issue by thomasrenes** [dresden-elektronik/deconz-rest-plugin#3632]
## Device

- Product name: Sonoff ZBMINI
- Manufacturer: SONOFF
- Model identifier: 01MINIZB
- Device type: Switch

## Screenshots

![Node_Info](https://user-images.githubusercontent.com/4504804/98841702-cbc71800-2448-11eb-9ee9-38c6c1d23d4a.png)

![Cluster_Info](https://user-images.githubusercontent.com/4504804/98841717-cec20880-2448-11eb-91a4-0c4ddb492e1c.png)

Identify:
![Cluster_Identify](https://user-images.githubusercontent.com/4504804/98842669-33319780-244a-11eb-8db8-d2a0b2589c3f.png)

Groups:
![Cluster_Group](https://user-images.githubusercontent.com/4504804/98842570-0f6e5180-244a-11eb-8836-33d427c6e702.png)

Scenes:
![Cluster_Scenes](https://user-images.githubusercontent.com/4504804/98842596-172df600-244a-11eb-93dc-79d2736efd17.png)

On/Off:
![Cluster_OnOff](https://user-images.githubusercontent.com/4504804/98842581-1301d880-244a-11eb-8cd0-7f07870bf8a3.png)

**Comment by Mimiix** [comment]
Hi,

Screenshots of other clusters are missing.

**Comment by thomasrenes** [comment]
Sorry about that, didn't thought it would be relevant. Other screenshots added. Need anything else?

**Comment by Mimiix** [comment]
Not that i can figure.  Need to wait for a dev :)

**Comment by SwoopX** [comment]
I see no to do here...

**Comment by Mimiix** [comment]
So it can be closed :) @SwoopX ?

**Comment by SwoopX** [comment]
I'd say yes. I case any other issues appear, please raise a seperate issue.

**Comment by mkuutti** [comment]
I wonder if ZBMINIs work out of the box or why was the request closed?

**Comment by SwoopX** [comment]
It works out of the box.

**Comment by malfroid** [comment]
I tried adding a Sonoff ZBMINI to deCONZ. It works for me to switch dumb lights.

However, for smart bulbs, I would like to disconnect the switch from the relay (e.g. Shelly switches call this "detached mode"). Does anyone know if this is possible with Sonoff ZBMINI?

**Comment by raddi** [comment]
I'm using Phoscon v2.7.1 and i can add the ZBMini without a problem. But: It is not usable. I can switch it only one time. After that switching it on will instantly turn it off again. I have 4 ZBMinis, none of them works.

**Comment by JoeArny** [comment]
> 
> 
> I'm using Phoscon v2.7.1 and i can add the ZBMini without a problem. But: It is not usable. I can switch it only one time. After that switching it on will instantly turn it off again. I have 4 ZBMinis, none of them works.

Same here, the device is recognized but deconz can not even blink it when I click on its icon.

**Comment by raddi** [comment]
Updated to latest beta (2.8) and restarted the raspberry, now everything works fine!

**Comment by crusaderflex** [comment]
Same here, Version 2.9, device could be paired. I can switch device on, but with the phoscon app it would not go to off!

**Comment by spiff42** [comment]
I have the same issue. I just wanted to note that in Phoscon my ZBMINI is reporting:
Vendor Heiman
Model 01MINIZB
Version 20200927
I bought it on AliExpress, so I don't know if the device is genuine or a knock-off.

**Comment by LeoeLeoeL** [comment]
I don't know if this can help somebody.
It seems that ZBMINI in its default configuration works as a relay.
I connected ZBMINI to a PUSH BUTTON and works.
Short pressure to switch on and short pressure to switch off.
If you make a long pressure, it switches on but when you release it switches off.

**Comment by jensorium** [comment]
with the Phoscon App it only allows to switch on, but the "light-icon" in the app stays dark. if i switch the light with the push button i am able to switch it on again

**Comment by LeoeLeoeL** [comment]
This device has a very strange behaviour.
At first it worked as you wrote. Suddenly, without any external action, it begins to pair (green light is blinking). It pairs again with Conbee alone and after that the Sonoff works good with ON and OFF in Home Assistant and Phoscon.
Then suddenly "again", it starts for pairing again. It pairs again alone and this time it works as you wrote!!!!
This turnover happens mostly everyday.

**Comment by nukleuz80** [comment]
Same issue here!

**Comment by epoc83** [comment]
I have the same issue. The device turns on but in phoscon remains off (turns on and off very quick) If I assign to a group of lights, I can turn off the group and the zbmini also turns off. If I try to turn on and off using homebridge and HomeKit, I can turn it on, but not off. It instantly reports being off.

**Comment by Mimiix** [comment]
Please stick to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4016

Im locking this one too until Manup replies there.
