### ISSUE TITLE
Device requeste for VIMAR 14592 Switch

### ISSUE THREAD

**Issue by rafuz** [dresden-elektronik/deconz-rest-plugin#3639]
## Device

- Product name: Vimar - 14592.0 - 2-way switch IoT connected mechanism
- Manufacturer: VIMAR
- Model identifier: On_Off_Switch_v1.0
- Device type : Please remove all unrelated device types. 
  - Light
  - Switch

## Screenshots
![image](https://user-images.githubusercontent.com/22271829/98997727-41a8ad80-2535-11eb-90b4-1e7e462bac12.png)
![image](https://user-images.githubusercontent.com/22271829/98997758-508f6000-2535-11eb-8cf8-af9db6760c5f.png)
![image](https://user-images.githubusercontent.com/22271829/98997780-5c7b2200-2535-11eb-96c0-033ecbcdd919.png)

**Comment by rafuz** [comment]
As said in #3194 right now the switch works but Turn ON/OFF commands are applied as TOGGLE.
Vimar advertises a Scene selection button but no correspondig cluster in zigbee.

https://www.vimar.com/en/int/catalog/product/index/code/14592.0

**Comment by LeoeLeoeL** [comment]
Probably Scene button can't be managed under Zigbee. 
It could be the same as for RGB Led. Vimar answered me via email it works under BT only.

**Comment by Mimiix** [comment]
@SwoopX ?

**Comment by SwoopX** [comment]
No clue what's going on there. One thing that is striking though: cluster 0x0007 (on/off switch configuration) is exposed as client cluster (grey) here, but it should be exposed as server cluster (blue). The server cluster has some attributes to change the switch behaviour only, also if it toggles. This is nothing deconz can change or influence, hence a device specific topic.

From my perspective, only the vendor can explain if and how that behaviour can be changed.

**Comment by testorp** [comment]
![vimar_14592_groups](https://user-images.githubusercontent.com/44940599/101510301-0ce41680-397a-11eb-94c3-ff99273ccf15.png)
![vimar_14592_identify](https://user-images.githubusercontent.com/44940599/101510312-0fdf0700-397a-11eb-9481-524619a34665.png)
![vimar_14592_node_info](https://user-images.githubusercontent.com/44940599/101510313-10779d80-397a-11eb-9f27-944ba2d35620.png)
![vimar_14592_onoff](https://user-images.githubusercontent.com/44940599/101510315-11a8ca80-397a-11eb-8a89-e93024933c95.png)
![vimar_14592_onoff_switch_configuration](https://user-images.githubusercontent.com/44940599/101510317-12d9f780-397a-11eb-9c38-4e59ab824c18.png)
![vimar_14592_scenes](https://user-images.githubusercontent.com/44940599/101510322-13728e00-397a-11eb-9115-d6ec6f3278ce.png)
![vimar_14592_cluster_info](https://user-images.githubusercontent.com/44940599/101510324-14a3bb00-397a-11eb-8237-b1b5be3caf09.png)
![vimar_14592_config](https://user-images.githubusercontent.com/44940599/101510329-15d4e800-397a-11eb-9a61-007a4f187723.png)

@Mimiix  these of from my device today

**Comment by LeoeLeoeL** [comment]
I don't remember cluster 0007 in my device. Even on firmware 2.0
I can't check now because I returned the switch due to the toggle problem.

**Comment by rafuz** [comment]
@testorp I have updated firmware today and re-added device and now I have the same clusters as you.
It is added as a light for me too.

**Comment by rafuz** [comment]
I don't have any update, I have checked if there is a new firmware but nothing has changed.

**Comment by LeoeLeoeL** [comment]
The situation's going worse.
I gave up and migrated alle tue HUE bulbs (14) and one 3A to the HUE bridge.
After that, I had the problem only one time per day so  I didn't solve.

**Comment by TheBisk** [comment]
same problem here also with the latest firmware, the switch works but Turn ON/OFF commands are applied only as TOGGLE.
this bug was not present in some previous firmware version.

**Comment by double1968** [comment]
I contacted Vimar, they announced that an update of the VIEW Wireless App (v1.2.3) has been released with which it is possible to update the switch to Firmware version 2.01. They invite you to update and verify operation.

**Comment by testorp** [comment]
Do you have information as to improvements?
Any release notes

Thx
Paolo

**Comment by double1968** [comment]
I updated the toggle switch issue was fixed

**Comment by monkeypr00f** [comment]
> I updated the toggle switch issue was fixed. the changelog is not available

Did it works? I updated but in deconz is listed as light and it works just in toggle mode...
If you toggle from the button HA is not updated, if you toggle from HA it toggles without any state.

**Comment by rafuz** [comment]
I will update tomorrow and report back.

**Comment by rafuz** [comment]
New Firmware 2.01

![image](https://user-images.githubusercontent.com/22271829/106135079-b9b36680-6167-11eb-8fd1-1f57709651a5.png)

![image](https://user-images.githubusercontent.com/22271829/106135117-cafc7300-6167-11eb-9c3e-dab9f54c08f5.png)

![image](https://user-images.githubusercontent.com/22271829/106135180-dbace900-6167-11eb-9386-401bb2e6f343.png)

Toggle bug seems fixed now

**Comment by testorp** [comment]
I have returned mine, does it work without load now?

Thx
Paolo

**Comment by monkeypr00f** [comment]
I can confirm it works with load! 
But not without, so useful in a traditional scenario, less if the switch is used to load a "remote" scene or similar without a load directly connected.

**Comment by SwoopX** [comment]
One remark in this regard, as I've seen the cluster 0x0007 obviously changed from client (grey) to server (blue). Via the blue server cluster, it should be possible to configure the switching behaviour if desired.

**Comment by TheBisk** [comment]
with the new firmware 2.0.1 everything is working fine now.

**Comment by cafedo** [comment]
> One remark in this regard, as I've seen the cluster 0x0007 obviously changed from client (grey) to server (blue). Via the blue server cluster, it should be possible to configure the switching behaviour if desired.

So, will it be possible integrate completely a Philips Hue Bulb connected to the switch? I mean: leaving the bulb with a constant load and listening the Vimar switch event in order to send to the Philips Hue gateway the virtual “on” and “off” of the bulb..
