### ISSUE TITLE
How do I set timeout on Xiaomi Aqara motion sensors?

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/deconz-rest-plugin#3640]
## Describe the question or issue you are having

I've just gotten a bunch of these very nice compact motion sensors (RTCGQ11LM, version 20170627).
They seem to be quite sensitive, and even has some lux sensor in it, as well as a temperature.
It does howver seem to me that the timout for these are way too long, something like 60s.
I want that to be more like 10 or 5 s.
So I went to the deconz interface, opened the cluster, and tried to write to it, but even though the field is marked rw, it just says 'writing' in the interface, but it still stays at 0, and after a while it says 'writing failed'.
Is it the right place I'm trying to write?

## Screenshots

![image](https://user-images.githubusercontent.com/13660621/99008500-96085900-2546-11eb-8aee-e4076e53f672.png)

## Environment

 - Host system: Intel NUC with PVE
 - Running method: Home Assistant
 - Firmware version: (26580700)
 - deCONZ version: (2.05.84)
 - Device: ConBee II
 - Do you use an USB extension cable: yes USB3
 - Is there any other USB or serial devices connected to the host system? If so: Which? Aeotec zwave usb stick

**Comment by Mimiix** [comment]
Hi,

That's normal behaviour. There is a hack to get it in 5 sec,  but you need to google that.

**Comment by SAOPP** [comment]
U can set between 60 and 90 seconds via rest-api.

**Comment by Smanar** [comment]
IDK what you are doing with it, but you can use it as presence detection, not mouvement detection, increase the timeout, and turn off the light when "presence" go to "off".

**Comment by fribse** [comment]
Ok, got it, thankyou all for the input, very much appreciated. I'm going to redesign the node-red flows to make them handle it instead of the 'old' way.
