### ISSUE TITLE
install Deconz headless

### ISSUE THREAD

**Issue by Try2Fly** [dresden-elektronik/deconz-rest-plugin#365]
Hi,

I installed deconz on a headless raspberry pi following the user manual. [https://www.dresden-elektronik.de/fileadmin/Downloads/Dokumente/Produkte/ZLL/RaspBee-BHB-en.pdf](url)

at 6.1.3 I have to open startx, however I do not have this installed. Is this really necessary?

I'm able to access the gateway through the browser phoscon app, but it is asking for a password I don't have. "delight" and other obvious passwords do not work. What is the password?

Thanks

**Comment by Try2Fly** [comment]
nevermind, got it working.  sudo apt install –f did not process correct

**Comment by bohtho** [comment]
What was the password ??!!
