### ISSUE TITLE
Wohnzimmer fehlt

### ISSUE THREAD

**Issue by r2ixuz** [dresden-elektronik/deconz-rest-plugin#3650]
## Describe the bug
Im Webadmin (Phoscon App) fehlt seit ca. zwei Versions Updates die Gruppe Wohnzimmer. Will man die Gruppe neu erstellen, kommt eine Fehlermeldung, dass sie bereits existiert. Geräte die Wohnzimmer zugeordnet waren, sind nun keiner Gruppe zugeordnet.

Da ich die Weboberfläche nur zur Kontrolle nutze, ist mir das eigentlich egal, wollte es nur mal berichten. :-)

Benutze den letzten stable docker container von marthoc.

## Steps to reproduce the behavior
Phoscon App benutzen

## Expected behavior
Wohnzimmer sollte nicht von geisterhand verschwinden

## Environment

Version 2.05.87 / 15.10.2020
Firmware 26580700 (ConBee II)

## deCONZ Logs
-
## Additional context
-

**Comment by Mimiix** [comment]
Be adviced: if you decide to repost again, make sure to post in English.
