### ISSUE TITLE
Feibit Dimmer Switch HGZB-04D

### ISSUE THREAD

**Issue by shsurury** [dresden-elektronik/deconz-rest-plugin#3657]
## Device

- Product name: Dimmer Switch HGZB-04D
- Manufacturer: Feibit Inc Co.
- Model identifier: FB56+ZSC05HG1.0
- Device type : Please remove all unrelated device types. 
  - Switch
The dimmer switches crasshes when requesting changing the brightness. Also the on/off state is not available when the device is physically turned on/off

 

## Screenshots

![FB56+ZSC05HG1 0 - Dimmer Switch Cluster](https://user-images.githubusercontent.com/7891577/99181721-7199c000-2784-11eb-94a1-0387a42bbd75.png)
![FB56+ZSC05HG1 0 - Dimmer Switch Node](https://user-images.githubusercontent.com/7891577/99181722-7494b080-2784-11eb-9707-b9864c34831d.png)

**Comment by Mimiix** [comment]
You are missing the other cluster screens.

**Comment by shsurury** [comment]
Hopefully I have included all. Please let me know if anything missing

![FB56+ZSC05HG1 0 - Dimmer Switch Group Cluster](https://user-images.githubusercontent.com/7891577/99182455-29c96780-2789-11eb-8907-5dd721134f9f.png)
![FB56+ZSC05HG1 0 - Dimmer Switch Identify Cluster](https://user-images.githubusercontent.com/7891577/99182459-2df58500-2789-11eb-942c-2078849286ad.png)
![FB56+ZSC05HG1 0 - Dimmer Switch Scene Cluster](https://user-images.githubusercontent.com/7891577/99182462-30f07580-2789-11eb-9a4c-9a08c7c1b121.png)
![FB56+ZSC05HG1 0 - Dimmer Switch on of Cluster](https://user-images.githubusercontent.com/7891577/99182499-67c68b80-2789-11eb-802a-baa76e98d06c.png)
![FB56+ZSC05HG1 0 - Dimmer Switch Level Control Cluster](https://user-images.githubusercontent.com/7891577/99182506-6ac17c00-2789-11eb-9db0-73576103530c.png)

**Comment by shsurury** [comment]
Hi is there any update on this request. It will be a great help if this added
