### ISSUE TITLE
Feibit Downlight HGZB-07A

### ISSUE THREAD

**Issue by shsurury** [dresden-elektronik/deconz-rest-plugin#3661]
## Device

- Product name: Downlight HGZB-07A
- Manufacturer: Feibit Inc Co.
- Model identifier: FB56-ZCW11HG1.2
- Device type : Please remove all unrelated device types. 
  - Light
 

## Screenshots

![FB56-ZCW11HG1 2 - Downlight Cluster](https://user-images.githubusercontent.com/7891577/99182130-1fa66980-2787-11eb-8c06-e4479f820eae.png)
![FB56-ZCW11HG1 2 - Downlight Node](https://user-images.githubusercontent.com/7891577/99182134-22a15a00-2787-11eb-91ae-3139b1d1f57c.png)

**Comment by shsurury** [comment]
additional clusters

![FB56-ZCW11HG1 2 - Downlight Color Control Cluster 4](https://user-images.githubusercontent.com/7891577/99183255-854a2400-278e-11eb-9069-95155a3319eb.png)
![FB56-ZCW11HG1 2 - Downlight Color Control Cluster 5](https://user-images.githubusercontent.com/7891577/99183257-867b5100-278e-11eb-90d1-17298fee1dbf.png)
![FB56-ZCW11HG1 2 - Downlight Color Control Cluster 6](https://user-images.githubusercontent.com/7891577/99183258-8713e780-278e-11eb-8abd-e6def114e2ab.png)
![FB56-ZCW11HG1 2 - Downlight Identify Cluster](https://user-images.githubusercontent.com/7891577/99183259-87ac7e00-278e-11eb-8cc2-a9dc564f8220.png)
![FB56-ZCW11HG1 2 - Downlight Level Control Cluster](https://user-images.githubusercontent.com/7891577/99183260-88451480-278e-11eb-9cf6-e6d2185d812f.png)
![FB56-ZCW11HG1 2 - Downlight On Off Cluster](https://user-images.githubusercontent.com/7891577/99183262-88ddab00-278e-11eb-9f96-54895ae4c09b.png)
![FB56-ZCW11HG1 2 - Downlight Scene Cluster](https://user-images.githubusercontent.com/7891577/99183263-89764180-278e-11eb-8f37-8d5f7b1c1c99.png)
![FB56-ZCW11HG1 2 - Downlight Color Control Cluster 1](https://user-images.githubusercontent.com/7891577/99183264-89764180-278e-11eb-9039-136cbd2d78e7.png)
![FB56-ZCW11HG1 2 - Downlight Color Control Cluster 2](https://user-images.githubusercontent.com/7891577/99183265-8a0ed800-278e-11eb-8141-1782a0c13199.png)
![FB56-ZCW11HG1 2 - Downlight Color Control Cluster 3](https://user-images.githubusercontent.com/7891577/99183266-8b400500-278e-11eb-9473-2817641d4c75.png)

**Comment by shsurury** [comment]
![Uploading FB56-ZCW11HG1.2 - Downlight Group Cluster.png…]()

**Comment by shsurury** [comment]
![FB56-ZCW11HG1 2 - Downlight Group Cluster](https://user-images.githubusercontent.com/7891577/99183306-cf330a00-278e-11eb-85cd-f5792c3fd0d1.png)

**Comment by shsurury** [comment]
Hi is there any update on this request. It will be a great help if this added

**Comment by SwoopX** [comment]
What exactly should be done here, is it working?
