### ISSUE TITLE
Feibit RGBW Bulb HGZB-07A

### ISSUE THREAD

**Issue by shsurury** [dresden-elektronik/deconz-rest-plugin#3663]
## Device

- Product name: RGBW Bulb HGZB-07A
- Manufacturer: Feibit Inc Co.
- Model identifier: FB56-ZCW11HG1.2
- Device type : Please remove all unrelated device types. 
  - Light
 

## Screenshots

![FB56-ZCW11HG1 2 - Bulb Color Control Cluster 4](https://user-images.githubusercontent.com/7891577/99184210-6ac77900-2795-11eb-9b06-39b11fdfbcc1.png)
![FB56-ZCW11HG1 2 - Bulb Color Control Cluster 5](https://user-images.githubusercontent.com/7891577/99184211-6c913c80-2795-11eb-9ca2-8695fa4cf26e.png)
![FB56-ZCW11HG1 2 - Bulb Color Control Cluster 6](https://user-images.githubusercontent.com/7891577/99184212-6d29d300-2795-11eb-813c-10b104accf91.png)
![FB56-ZCW11HG1 2 - Bulb Group Cluster](https://user-images.githubusercontent.com/7891577/99184214-6dc26980-2795-11eb-8c68-8e79a60fce3d.png)
![FB56-ZCW11HG1 2 - Bulb Identify Cluster](https://user-images.githubusercontent.com/7891577/99184216-6e5b0000-2795-11eb-8ab3-d4b4bf7e6edf.png)
![FB56-ZCW11HG1 2 - Bulb Level Cluster](https://user-images.githubusercontent.com/7891577/99184217-6e5b0000-2795-11eb-9a7c-4189a3f00b57.png)
![FB56-ZCW11HG1 2 - Bulb Node](https://user-images.githubusercontent.com/7891577/99184218-6ef39680-2795-11eb-8721-2c0fcffd1e18.png)
![FB56-ZCW11HG1 2 - Bulb on off Cluster](https://user-images.githubusercontent.com/7891577/99184220-6f8c2d00-2795-11eb-8c63-4e067e0cf901.png)
![FB56-ZCW11HG1 2 - Bulb Scene Cluster](https://user-images.githubusercontent.com/7891577/99184221-7024c380-2795-11eb-85a8-bc2d3f8719c8.png)
![FB56-ZCW11HG1 2 - Bulb Cluster](https://user-images.githubusercontent.com/7891577/99184223-70bd5a00-2795-11eb-9ff2-54a69c250e5a.png)
![FB56-ZCW11HG1 2 - Bulb Color Control Cluster 1](https://user-images.githubusercontent.com/7891577/99184224-7155f080-2795-11eb-92a6-77e5ddcb14ed.png)
![FB56-ZCW11HG1 2 - Bulb Color Control Cluster 2](https://user-images.githubusercontent.com/7891577/99184226-71ee8700-2795-11eb-9b1f-044db15d8e42.png)
![FB56-ZCW11HG1 2 - Bulb Color Control Cluster 3](https://user-images.githubusercontent.com/7891577/99184227-72871d80-2795-11eb-9e09-70c351299baa.png)

**Comment by shsurury** [comment]
Hi is there any update on this request. It will be a great help if this added

**Comment by SwoopX** [comment]
What exactly should be done here, is it working?

**Comment by shsurury** [comment]
Hi SwoopX,
It is working but the gateway is not able to request the state of the device so when you physically turn the switch on the gateway still shows that it is off

Regards

Sajid Husain Surury
Food Safety Auditor & Consultant
B. Sc., M. Sc., M. App. Sc., MAIFST
RABQSA # 113236
Mobile – 0400571140<tel:0400571140>
Phone/Fax – 03 8839 0538<tel:03%208839%200538>
E mail – sajid@surury.com.au<mailto:sajid@surury.com.au>

On 13 Dec 2020, at 10:33, SwoopX <notifications@github.com> wrote:

﻿

What exactly should be done here, is it working?
