### ISSUE TITLE
Develco Smart Cable

### ISSUE THREAD

**Issue by r0dh3773** [dresden-elektronik/deconz-rest-plugin#3667]
## Device

- Product name: Smart Cable
- Manufacturer: Develco
- Model identifier: SMRZB-143
- Device type : Please remove all unrelated device types. 
  - Other: Smart plug/relay w/ Power consumption

https://www.develcoproducts.com/products/smart-relays/smart-cable/
I only get the on/off functions in home-assistant / node-red (Shows up as a light in phoscon), 
it would be nice to have the power consumption readings from it.

## Screenshots

![SMRZB-143 - Basic Cluster Info](https://user-images.githubusercontent.com/57790635/99193551-0ea32b80-277a-11eb-86cb-66857903f682.png)
![SMRZB-143 - Node Info](https://user-images.githubusercontent.com/57790635/99193556-1367df80-277a-11eb-92c4-701614230de4.png)
![SMRZB-143 - Simple Metering Cluster](https://user-images.githubusercontent.com/57790635/99193561-1793fd00-277a-11eb-8e8e-eee91b3ab53c.png)
![SMRZB-143 - Electrical Measurement Cluster](https://user-images.githubusercontent.com/57790635/99193562-182c9380-277a-11eb-8980-f898a41df8a8.png)
![SMRZB-143 - Device Temperature Configuration Cluster](https://user-images.githubusercontent.com/57790635/99193564-18c52a00-277a-11eb-9b36-c8137c60aed2.png)

**Comment by Smanar** [comment]
Hello, do you have an unix machine to test the code ?
Else the code is small https://github.com/Smanar/deconz-rest-plugin/commit/4ad6e3c56563665df147f446c64e2a463d666298 probably don't need testing.

**Comment by SwoopX** [comment]
@Smanar You need to update calculation for the current, as the value displayed is in mA. Just add it to the already given 13 devices.

You also need to add it for the reporting configuration of voltage and current where reportable change is 100. After that, lemme have a quick look and it should be fine then.

**Comment by Smanar** [comment]
done

**Comment by SwoopX** [comment]
Yup. Then I'd say it's good to go.

**Comment by Smanar** [comment]
Ok, because I don't realy like send code without test.

**Comment by SwoopX** [comment]
@Smanar Can you please raise the PR? Please change the model identifier according to the other develco devices (that has been updated recently) prior to that.

Otherwise, the code is fine, no worries.

**Comment by Smanar** [comment]
Oups sorry, I totaly forget this PR

But what is the problem with the model identifier ?

**Comment by SwoopX** [comment]
Added in 2.10.00-beta
