### ISSUE TITLE
Support lost for Schlage Connect Smart Deadbolt B3468

### ISSUE THREAD

**Issue by ericvandamme** [dresden-elektronik/deconz-rest-plugin#3676]
## Describe the bug
Upgrading to the latest stable release causes Schlage Connect Smart Deadbolt B3468 to no longer be a supported device.

## Steps to reproduce the behavior
  1. Update to v2.5.88 (possibly v2.5.87)
  2. No longer recognized in Phoscon nor name will properly display in deCONZ network map

## Expected behavior
Support expected to continue through versions.

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: (26390500)
 - deCONZ version: (2.5.88)
 - Device: ConBee I
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

## Additional context
Attempted to revert to last known version (I am 99% sure it is v2.5.84) but it is no longer available via apt. *This might be a nice feature to have as versions have broke support for devices before, and being able to revert to a last known working config would be delightful*

**Comment by Smanar** [comment]
Hello, do you have the cluster list for this device ?

**Comment by ericvandamme** [comment]
I have already submitted a Pull Request to add support again. The new stricter check was what made it unsupported.

Attached is the basic cluster information from deCONZ.

![Basic Cluster](https://user-images.githubusercontent.com/28657401/99275257-44d3c000-27f9-11eb-8d51-5f8823d930fa.JPG)

**Comment by ericvandamme** [comment]
Suppose I should also include the node info as well.

![Capture](https://user-images.githubusercontent.com/28657401/99275438-7c426c80-27f9-11eb-9402-cba516b09484.JPG)
