### ISSUE TITLE
New Version of Trust ZYCT Remote/Switch

### ISSUE THREAD

**Issue by Puntoboy** [dresden-elektronik/deconz-rest-plugin#3682]
## Device

- Product name: Trust ZYCT-202 (updated)
- Manufacturer: Trust International B. V.
- Model identifier: ZLL-NonColorController
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots

  - Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/11718878/99294083-78cfd500-283b-11eb-82c5-7244bc419cae.png)

  - Node Info panel
![image](https://user-images.githubusercontent.com/11718878/99294025-62297e00-283b-11eb-9182-760fd11fa2e2.png)

  - Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/11718878/99293995-58077f80-283b-11eb-9b9d-3b1b72629946.png)

This looks like a newer version of the same remote listed here. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/261

**Comment by Mimiix** [comment]
@Puntoboy Missing screens! You need to screenshot all clusters.

**Comment by Puntoboy** [comment]
> 
> 
> @Puntoboy Missing screens! You need to screenshot all clusters.

What does that actually mean? When I submitted a new device request previously I only submitted the above.

**Comment by Mimiix** [comment]
The other clusters. Groups, Identity, On/off etc.

Please read https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by Puntoboy** [comment]
![image](https://user-images.githubusercontent.com/11718878/99299294-f3e8b980-2842-11eb-893d-e53d8cc8aaf1.png)

![image](https://user-images.githubusercontent.com/11718878/99299342-0531c600-2843-11eb-9488-c2cb35306358.png)

![image](https://user-images.githubusercontent.com/11718878/99299397-14b10f00-2843-11eb-8a55-604dd2b8d447.png)

![image](https://user-images.githubusercontent.com/11718878/99299481-2e525680-2843-11eb-8e91-8083fb34bbcb.png)

**Comment by Mimiix** [comment]
I think one might be missing. Add that one if you can. 
Other than that, your ready i think.

**Comment by Puntoboy** [comment]
I tried all of the ones that had attributes sections.

**Comment by Mimiix** [comment]
Now we needa wait for a dev to integrate it 👍

**Comment by Puntoboy** [comment]
Hopefully it's not too long otherwise I might return it.

**Comment by Mimiix** [comment]
I am not going to push anyone just for 1 switch. Be adviced that next beta is expected atleast the 15th of next month. I for a fact know that there's gonna be one at the 30th this month. But  no guarantees on this switch.

**Comment by wilsonlspacheco** [comment]
I have one of this device (updated version).
Waiting news, thks everyone.

**Comment by Puntoboy** [comment]
> 
> 
> I am not going to push anyone just for 1 switch. Be adviced that next beta is expected atleast the 15th of next month. I know for a fact that there's gonna be one at the 30th this month. But no guarantees on this switch.

Not suggesting you should :) I was hoping that this was a easy fix as there is an existing switch with the same model name already in the system.

**Comment by Mimiix** [comment]
The fix itself isnt that hard i think, it's the release schedule in this case :)

I'll ask a dev to check this out for you.

**Comment by SwoopX** [comment]
Closing as supported by 2.07.01

**Comment by Puntoboy** [comment]
So finally been able to test this and it's not working. I can see the device in VNC but if I reset it and then re-pair I don't see it in the Web UI. Also, Home Assistant doesn't see it either. I can see this in the logs.

```
13:07:14:628 CTRL skip polling while permit join is set
13:07:14:629 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
13:07:14:629 FP indication 0x0104 / 0x0008 (0x00158D00038E614F / 0xE71A)
13:07:14:630                       ...     (0x00158D00038E614F / 0xE71A)
13:07:14:635 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
13:07:14:735 CTRL skip polling while permit join is set
13:07:14:737 CTRL skip polling while permit join is set
13:07:14:737 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
13:07:14:738 FP indication 0x0104 / 0x0006 (0x00158D00038E614F / 0xE71A)
13:07:14:738                       ...     (0x00158D00038E614F / 0xE71A)
13:07:14:744 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
13:07:14:753 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
13:07:14:754 FP indication 0x0104 / 0x0008 (0x00158D00038E614F / 0xE71A)
13:07:14:754                       ...     (0x00158D00038E614F / 0xE71A)
13:07:14:761 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
```

**Comment by wilsonlspacheco** [comment]
> So finally been able to test this and it's not working. I can see the device in VNC but if I reset it and then re-pair I don't see it in the Web UI. Also, Home Assistant doesn't see it either. I can see this in the logs.
> 
> ```
> 13:07:14:628 CTRL skip polling while permit join is set
> 13:07:14:629 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
> 13:07:14:629 FP indication 0x0104 / 0x0008 (0x00158D00038E614F / 0xE71A)
> 13:07:14:630                       ...     (0x00158D00038E614F / 0xE71A)
> 13:07:14:635 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
> 13:07:14:735 CTRL skip polling while permit join is set
> 13:07:14:737 CTRL skip polling while permit join is set
> 13:07:14:737 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
> 13:07:14:738 FP indication 0x0104 / 0x0006 (0x00158D00038E614F / 0xE71A)
> 13:07:14:738                       ...     (0x00158D00038E614F / 0xE71A)
> 13:07:14:744 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
> 13:07:14:753 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
> 13:07:14:754 FP indication 0x0104 / 0x0008 (0x00158D00038E614F / 0xE71A)
> 13:07:14:754                       ...     (0x00158D00038E614F / 0xE71A)
> 13:07:14:761 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
> ```
> 
> ![image](https://user-images.githubusercontent.com/11718878/102714610-bce54800-42c7-11eb-9a73-5f62bee65b3a.png)

Same here 😔

**Comment by Mimiix** [comment]
> So finally been able to test this and it's not working. I can see the device in VNC but if I reset it and then re-pair I don't see it in the Web UI. Also, Home Assistant doesn't see it either. I can see this in the logs.
> 
> ```
> 13:07:14:628 CTRL skip polling while permit join is set
> 13:07:14:629 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
> 13:07:14:629 FP indication 0x0104 / 0x0008 (0x00158D00038E614F / 0xE71A)
> 13:07:14:630                       ...     (0x00158D00038E614F / 0xE71A)
> 13:07:14:635 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
> 13:07:14:735 CTRL skip polling while permit join is set
> 13:07:14:737 CTRL skip polling while permit join is set
> 13:07:14:737 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
> 13:07:14:738 FP indication 0x0104 / 0x0006 (0x00158D00038E614F / 0xE71A)
> 13:07:14:738                       ...     (0x00158D00038E614F / 0xE71A)
> 13:07:14:744 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
> 13:07:14:753 unknown neighbor 0x00158D00038E614F (0xE71A), lqi: 143, rssi: -76
> 13:07:14:754 FP indication 0x0104 / 0x0008 (0x00158D00038E614F / 0xE71A)
> 13:07:14:754                       ...     (0x00158D00038E614F / 0xE71A)
> 13:07:14:761 [4] Skipping additional attribute read -  Assumed Trust remote (ZYCT-202)
> ```
> 
> ![image](https://user-images.githubusercontent.com/11718878/102714610-bce54800-42c7-11eb-9a73-5f62bee65b3a.png)

It won't show in the web ui as they need to add support themselves. 

It would show in ha tho. What does the switch look like in vnc?

**Comment by Puntoboy** [comment]
Sorry I thought Phoscon and Deconz was part of the same software? In VNC is appears as per the screenshot at the top.

**Comment by Puntoboy** [comment]
Any update on this?

**Comment by Mimiix** [comment]
@Puntoboy Missed your comment. However: Yes they are, but the Rest API is open source. Phoscon is not. 

https://github.com/dresden-elektronik/phoscon-app-beta/issues

That's the place to ask support for this switch in phoscon 😄

**Comment by Puntoboy** [comment]
So how do I fix this? It doesn't appear in the Web UI or Home Assistant.

**Comment by Mimiix** [comment]
Can you check the restapi if it shows up?

Also: Did you re-pair after updating?

**Comment by Puntoboy** [comment]
Sorry, I don''t really know rest, how do I check please? 

I completely deleted it from VNC and reset the switch.

**Comment by Mimiix** [comment]
https://dresden-elektronik.github.io/deconz-rest-doc/getting_started/

 :)

**Comment by Puntoboy** [comment]
I ran GET /api/<apikey> and I can't see it as a device in the list.

**Comment by Mimiix** [comment]
Should be under sensors.

**Comment by Puntoboy** [comment]
Not sure why it would be under sensors, it's a switch. Anyway I noticed that I must have deleted it again after trying to connect it before, so I re-added it and it now appears in the Rest API.

`      "ep": 1,
      "etag": "6bc8db628882d7668d3ca1f3c56667c1",
      "lastseen": "2021-01-04T12:06Z",
      "manufacturername": "Trust International B.V.",
      "mode": 1,
      "modelid": "ZLL-NonColorController",
      "name": "ZLL-NonColorController 31",
      "state": {
        "buttonevent": 4002,
        "lastupdated": "2021-01-04T12:06:12.361"
      },
      "swversion": "20150212",
      "type": "ZHASwitch",
      "uniqueid": "00:15:8d:00:03:8e:61:4f-01-1000"`

I have it working in Node-Red as that talks to Phoscon directly. I just need to set up the group light controls now as it's currently only able to output one set of buttonevents. 

Thank you :)

**Comment by Mimiix** [comment]
Nice! Great to hear that.

Case closed?

**Comment by Puntoboy** [comment]
I think so!

Kind regards,
Chris Jeffrey

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
