### ISSUE TITLE
Shutters with Legrand switches never down..... always UP !

### ISSUE THREAD

**Issue by blendesign** [dresden-elektronik/deconz-rest-plugin#3685]
Describe the bug
I added my shutter ( Legrand Celiane / Home+ app ) to Home Assistant, via ConBee 2 USB Key.
I can see shutter in Home assistant, with these buttons : UP, STOP, DOWN.
STOP button seem working.
in all cases, when i press buttons UP or DOWN, the shutter ONLY UP, never DOWN.
Sometimes, UP button is in grey color, and i can't press it. ( Sometimes it's DOWN button ).
i Can't up or down the shutter at a certain position ? ( 35% or 50% or 75%....).
Strange thing : when i pair the shutter, Phoscon also find a light ! ( same name as the switch )

Expected behavior
 If applicable, describe what you expected to happen:
 - when i press up ( on my up button on the Home Assistant Card ) : it up the shutter
 - when i press down ( on my down button on the Home Assistant Card ) : it down the shutter

 Screenshots
https://goopics.net/a/7jQTHWK0

 Environment
 - Host system: Raspberry Pi 4 4Go
 - Running method:  Home Assistant deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.05.88
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so : yes, before : USB3 SSD drive. but i removed it, and now, i have only a MicroSD card.

**Comment by Smanar** [comment]
Hello, was not for your problem https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3549
From https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2812
