### ISSUE TITLE
TUYATEC-r9hgssol RH3001 Door/Window Contact Sensor

### ISSUE THREAD

**Issue by panenka** [dresden-elektronik/deconz-rest-plugin#3689]
## Device

- Product name: TUYATEC-r9hgssol RH3001
- Manufacturer:TUYATEC-r9hgsso
- Model identifier: RH3001
- Device type : 
  - Sensor

Still not fully supported, not possible to rename, not shown in Phoscon, previous case - Tuya Smart ZigBee Door Window Contact Sensor adding/pairing #2806

## Screenshots
![image](https://user-images.githubusercontent.com/9946446/99417992-d37c3600-28fa-11eb-86de-671935bdd625.png)
![image](https://user-images.githubusercontent.com/9946446/99418031-de36cb00-28fa-11eb-843b-08cbad530df6.png)
![image](https://user-images.githubusercontent.com/9946446/99411571-0c64dc80-28f4-11eb-96d9-81a7c4fe6760.png)
![image](https://user-images.githubusercontent.com/9946446/99411710-31594f80-28f4-11eb-9957-9aeb8be60a51.png)
![image](https://user-images.githubusercontent.com/9946446/99411763-40400200-28f4-11eb-95b9-2e15bc71333f.png)
![image](https://user-images.githubusercontent.com/9946446/99411821-4e8e1e00-28f4-11eb-94e8-b8af272c0659.png)

Device
Screenshots

**Comment by panenka** [comment]
edited

**Comment by SwoopX** [comment]
The device is fully supported and sensor(s) has been created as depicted in your screenshot. For visibility in Phoscon, please raise a corresponding request in the phoscon-beta repository.
