### ISSUE TITLE
TUYATEC-yg5dcbfu RH3052 Temperature and pressure sensor

### ISSUE THREAD

**Issue by panenka** [dresden-elektronik/deconz-rest-plugin#3690]
## Device

- Product name: TUYATEC-yg5dcbfu RH3052
- Manufacturer: TUYATEC-yg5dcbfu
- Model identifier: RH3052
- Device type : 
  - Sensor

Still not fully supported, not possible to rename, not shown in Phoscon

## Screenshots
![image](https://user-images.githubusercontent.com/9946446/99418202-0f170000-28fb-11eb-9033-1e337a798965.png)
![image](https://user-images.githubusercontent.com/9946446/99418248-1c33ef00-28fb-11eb-8096-9bb14fc8e59a.png)
![image](https://user-images.githubusercontent.com/9946446/99412870-7af66a00-28f5-11eb-8444-e146f4a0b281.png)
![image](https://user-images.githubusercontent.com/9946446/99412960-91042a80-28f5-11eb-9478-ee14f1bfccc1.png)
![image](https://user-images.githubusercontent.com/9946446/99413001-9bbebf80-28f5-11eb-9f6b-ac84cb7203db.png)
![image](https://user-images.githubusercontent.com/9946446/99413103-b729ca80-28f5-11eb-8ca5-d487ad11e2f0.png)
![image](https://user-images.githubusercontent.com/9946446/99413146-c3158c80-28f5-11eb-94f1-30b1e4c7906d.png)

**Comment by SwoopX** [comment]
The device is fully supported and sensor(s) has been created as depicted in your screenshot. For visibility in Phoscon, please raise a corresponding request in the phoscon-beta repository.
