### ISSUE TITLE
TUYATEC-zn9wyqtr RH3040 Motion sensor

### ISSUE THREAD

**Issue by panenka** [dresden-elektronik/deconz-rest-plugin#3691]
## Device

- Product name: TUYATEC-zn9wyqtr RH3040
- Manufacturer: TUYATEC-zn9wyqtr
- Model identifier: RH3040 
- Device type : 
  - Sensor

Still not fully supported, not possible to rename, not shown in Phoscon

## Screenshots
![image](https://user-images.githubusercontent.com/9946446/99418350-379efa00-28fb-11eb-8bf8-472adf15b650.png)
![image](https://user-images.githubusercontent.com/9946446/99418382-42f22580-28fb-11eb-961e-b0a868cefab2.png)
![image](https://user-images.githubusercontent.com/9946446/99414031-af1e5a80-28f6-11eb-9494-b2509c46933e.png)
![image](https://user-images.githubusercontent.com/9946446/99414125-cbba9280-28f6-11eb-896c-a185cf013e80.png)
![image](https://user-images.githubusercontent.com/9946446/99414177-db39db80-28f6-11eb-9eb4-247403be132e.png)
![image](https://user-images.githubusercontent.com/9946446/99414263-f0af0580-28f6-11eb-8ba3-08a802be1efb.png)
![image](https://user-images.githubusercontent.com/9946446/99414346-01f81200-28f7-11eb-9bb4-3911297cdec9.png)

**Comment by SwoopX** [comment]
The device is fully supported and sensor(s) has been created as depicted in your screenshot. For visibility in Phoscon, please raise a corresponding request in the phoscon-beta repository.
