### ISSUE TITLE
deconz Connections / Mesh

### ISSUE THREAD

**Issue by Dominik-1980** [dresden-elektronik/deconz-rest-plugin#3695]
## Describe the question or issue you are having

Hello.

I am new with deconz. I have installed a ConBee II Stick with deconz and now I am wondering why my Unit "Wandschalter Flur oben" is connected with "Configuration tool I" and not to "Steckdose Dachzimmer"...
I installed "Steckdose Dachzimmer" as a repeater because otherwise the signal was very weak an unstable.
Its almost near my "Wandschalter Flur oben" and the head device "Configuration tool I" is on another floor.
Please take a look at the Screenshot below.

## Screenshots

![Bildschirmfoto 2020-11-16 um 11 20 28](https://user-images.githubusercontent.com/32244806/99439218-311d7c00-2915-11eb-89f6-02ec76bf2463.png)
## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian deCONZ Add-on
 - Firmware version: latest
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs

-->

## Additional context

-->

**Comment by Smanar** [comment]
Lol, you are not the first one with this questions ^^.
On my side I have remarked devices always prefer direct connection, and the direct connexion don't look so bad on your side.

The color are just an indication, but I think the connection is better in direct than using "Steckdose Dachzimmer"

It s xiaomi devices ? If yes you can use trick, Xiaomi never (almost) change their parent, so turn off all the router you don't want, put the sensor close the router you want, and remake an inclusion (let it here for 1 hour to be sure), after that you can move it again.

**Comment by DrDoom666** [comment]
Hehe. Okay, thank you.
Yes, it is Xiaomi Aqara.

**Comment by dergreg** [comment]
> It s xiaomi devices ? If yes you can use trick, Xiaomi never (almost) change their parent, so turn off all the router you don't want, put the sensor close the router you want, and remake an inclusion (let it here for 1 hour to be sure), after that you can move it again.

That sounds like a neat workaround, maybe also for my issue #3529 

I repaired my Xiaomi door contact sensor to the nearest repeater and verified it in the deconz application. Let's see if the connection remains 😊
