### ISSUE TITLE
deCONZ Update to 2.05.88 --> homebridge-hue very slow response

### ISSUE THREAD

**Issue by DrDoom666** [dresden-elektronik/deconz-rest-plugin#3704]
## Describe the bug

Not really a bug, but i did an update on my Raspberry with apt update, apt upgrade and now i'm on deCONZ 2.05.88.

I've realized that my devices are now shown with a battery symbol in deCONZ, what is very nice, but the response of the homebridge-hue plugin which controls my light when I toggle my wall switch is very slow.
It takes 3 or 4 seconds, till my lights turn on or off. That's way more slow than in the previous version.
Perhaps you can fix that.

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.05.88
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No.

**Comment by Mimiix** [comment]
The only time this happens if when the SD card is slow or full or broken. I suggest checking there.

**Comment by DrDoom666** [comment]
Okay. Everytime I restart my Raspberry the reaction time is very slow.
After some time the response time is in a normal range about one second.
So I close this. Thank you.
