### ISSUE TITLE
Phoscon Rule Motion Sensor want to add specified time range #3728

### ISSUE THREAD

**Issue by clipse2004** [dresden-elektronik/deconz-rest-plugin#3729]
2.05.88

## Describe the question or issue you are having

I was setting two rules in phoscon for room kitchen. First i set "Daytime! and second "From Dusk Till Dawn", now i wants to specifices the Time for "Daytime" that it only will trigger from 16:00 o clock to the second trigger "From Dusk Till Dawn" before 16:00 it should do nothing. 
i was looking for my created Rule under http://192.168.5.5:8080/api/7B612375BA/rules/ but i cannot find the rule for this sensor (Sensor 59), 
i want to set based condition from 16:00 to 22:00. on which rule i have to add this? where can i look for rules only for this sensor?
i looked here https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/rules/#getrule but i didnt help me :(
what is the best and easiest way to find? 

sorry im new on this, so possible im a little bit stupid to find :)

thanks for helping me

## Environment

26660700

 - Host system: Raspberry
 - Running method: Raspbian / deCONZ
 - Firmware version: 26660700
 - deCONZ version: 2.05.88
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Smanar** [comment]
Hello, I m not using rules on my side, I have found this issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2010 with some usefull comment, but not easy to understand.

**Comment by clipse2004** [comment]
Hello,
Yep I found this too and tried it, but I cannot find my rule to add this.
That’s my problem :/
