### ISSUE TITLE
Philips Hue E14 support

### ISSUE THREAD

**Issue by CannyDuck** [dresden-elektronik/deconz-rest-plugin#373]
Please correct, If I am wrong. Are the Hue E14 are not supported by Deconz right now? I can not find resetet bulbs with the device search.

**Comment by ebaauw** [comment]
I’ve got two Hue E14 bulbs connected to deCONZ without any problems.

With the latest firmware, you need to power-cycle Hue bulbs for them to respond to touchlink.
