### ISSUE TITLE
Lights flash randomly

### ISSUE THREAD

**Issue by MaStahl84** [dresden-elektronik/deconz-rest-plugin#3742]
## Describe the bug
With the last update (deCONZ 2.05.88) some lights flash randomly in full brightness.
When the lights are in the same group, they even flash in sync.

I tried to delete this groups an made some new ones, but same behavior. Also the log in Phoscon had no infos or errors at the time when the lights flashed

Afer i switched back to version 2.05.84, all lights work fine.

## Steps to reproduce the behavior
Update from 2.05.84 to Version 2.05.88

May be there are problems in combination with the lamp
Manufacture: MLI (Müller-Licht)
Modell tint-ColorTemperature
Version TDU18650B01

But also the bulbs from ipcasa showed this Problem.

## Environment
Host system: Raspberry Pi 4
Running method:Home Assistent deCONZ Add-on
Firmware version: (26660700)
deCONZ version: 2.05.88
Device: ConBee II
Do you use an USB extension cable: yes
Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
Sorry, no Logs available. because of donwgrade

**Comment by Mimiix** [comment]
Without logs, its impossible to say anything on this issue.

**Comment by MaStahl84** [comment]
Okay, by time i will make the update again, start the log and wait for the next flash.

**Comment by MrksHfmn** [comment]
I have the same issue with exactly one Osram Smart+ bulb ... out of nowhere it receives 100 % brightness. I created a rule in openHab to suppress this behavior and switch to 0 % immediately

**Comment by gilbert-grape** [comment]
Same issue with Müller Licht and Philips Hue. In different rooms=different groups and scenes.
Power switch off for the bulbs helps. Maybe needed to repeat twice.

**Comment by EduardSarjadjuk** [comment]
Same issue with Oeeone E27 Smart Filament LED Lampe.

**Comment by gilbert-grape** [comment]
What I have found out (an idea):
- today a full day without flashing. But what is different? 
- my wife often switch the old power wall switch on/off, instead of the zigbee ones. Yesterday she did that, and then sometimes i get the flashing. Today she was not at home, the light were always connected.

Is it maybe an issue of initializing?

**Comment by Smanar** [comment]
On my side, I realy don't see how the zigbee stuff can make the hardware flashing. Flashing are generaly hardware problem.

>Afer i switched back to version 2.05.84, all lights work fine.

Total mystery for me.

**Comment by Mimiix** [comment]
Does anyone have some logs on when this happens? That way we can see what triggers this.

**Comment by MrksHfmn** [comment]
Does deCONZ write log files? Which properties must be set for the case to be logged? I can have a message sent to me as soon as a lamp becomes 100% bright and I can look into the logs afterwards. Currently the following logs are written:

      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=1

**Comment by Mimiix** [comment]
the 0 means none.

Can you put APS on 2?

**Comment by MrksHfmn** [comment]
Ok, the issue occured today at 07:55. Unfortunately I can't tell the second and the log is quite big ...

https://pastebin.com/ynwe9q0x

Addr: 0x7cb03eaa00b1066e

I try to narrow it down even further

**Comment by MaStahl84** [comment]
I update again to Version 2.05.88 and the flashes are back.
But the log wasn't yet active. This evening I will wait for the next flash and send the log files.

**Comment by Mimiix** [comment]
@MrksHfmn 07:55:52:151 0x7CB03EAA00B1066E error APSDE-DATA.confirm: 0xE9 on task

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log

Seems like there's something else with it.,

**Comment by alexvduin** [comment]
I have the same issue. Also with the same MLI (Müller-Licht) TDU18650B01. My IKEA bulbs do not have this issue. Is there any progress on this?

**Comment by MaStahl84** [comment]
I tired to reproduce the bug, but with the update to 2.7.1 ther are no flashes anymore...

**Comment by Mimiix** [comment]
That's great! 

Case closed?
