### ISSUE TITLE
Deconz doesn't show 2 devices with 3A Smart Inline-Double Switch

### ISSUE THREAD

**Issue by LeoeLeoeL** [dresden-elektronik/deconz-rest-plugin#3764]
## Describe the bug
  I paired the double switch 3A model LXN59-2S7LX1.0.
Phoscon found:
On/Off light 24
On/Off light 30

while Deconz shows only On/Off light 30 but when I open the cluster window the list is doubled and they are called 01 and 02.

  Help us understand the issue by providing valuable context.
-->

## Screenshots

 
![Cattura](https://user-images.githubusercontent.com/65825223/100466188-cf0d0580-30d0-11eb-8d40-8e48f7662340.PNG)

-->

## Environment

 - Host system: Raspberry Pi 
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.05.88
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Smanar** [comment]
Take a look on uniqueid on the json, you will have a device with XXXXXX-01 and the other XXXXXX-02.
Deconz show the reality, so only one device, but phoscon show some usable entry, so you have 1 bulb by gang I think.
