### ISSUE TITLE
SilverCrest Smart Window or Door Sensor (Lidl)

### ISSUE THREAD

**Issue by bvdberg01** [dresden-elektronik/deconz-rest-plugin#3767]
## Device

- Product name: Smart Windows or Door Sensor.
- Manufacturer: SilverCrest.
- Model identifier: TY0203
- Device type :
  - Sensor

## Screenshots
**Basic cluster:**
![image](https://user-images.githubusercontent.com/74251551/100515305-6169e380-317b-11eb-9f54-ee3491e62606.png)

**Power Configuration Cluster:**
![image](https://user-images.githubusercontent.com/74251551/100515327-92e2af00-317b-11eb-8253-db41f91077f2.png)

**Identify Cluster:**
![image](https://user-images.githubusercontent.com/74251551/100515339-b148aa80-317b-11eb-909f-281ef57b242c.png)

**IAS Zone Cluster:**
![image](https://user-images.githubusercontent.com/74251551/100515355-cd4c4c00-317b-11eb-90ab-032d95cf0cf5.png)
![image](https://user-images.githubusercontent.com/74251551/100515359-d4735a00-317b-11eb-9f45-558ef8ab5d5c.png)

**Diagnostics Cluster:**
![image](https://user-images.githubusercontent.com/74251551/100515393-23b98a80-317c-11eb-855b-0d08eba5b2f3.png)

**OTAU cluster:**
![image](https://user-images.githubusercontent.com/74251551/100515410-4186ef80-317c-11eb-9e2e-5ade3eea7e69.png)

**Node info:**
![image](https://user-images.githubusercontent.com/74251551/100515665-0be30600-317e-11eb-8f75-00503bd8c8a4.png)
![image](https://user-images.githubusercontent.com/74251551/100515571-6cbe0e80-317d-11eb-9399-6c1bf2a050e7.png)

**Comment by Mimiix** [comment]
@Smanar can you do this one :)?

**Comment by Smanar** [comment]
Sure.
@bvdberg01 have you an unix machine for test ?

If yes, you can take a look here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

So it will be for you

sudo apt install deconz-dev
git clone --branch SC_door https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins

After that you can run deconz and include the device. It will probably not be visible in phoscon, so you can use third app or direclty the api to check the device creation.

Not sure for battery return yet, but I think the rest will be ok, realy few modifications.

**Comment by robertklep** [comment]
@Smanar just installed v2.0.7-beta, with which I can pair the motion sensor and contact sensor 🥳

However, it doesn't look like the state of the contact sensor is being updated, it remains `"open" : false` even though the sensor is "open".

The zone status attribute of the IAS cluster does change value:
* 0x0020: no tamper, contact closed
* 0x0021: no tamper, contact open
* 0x0024: tamper, contact closed
* 0x0025: tamper, contact open

**Comment by Mimiix** [comment]
As this is integrated properly and working now, i am closing off this issue :)
