### ISSUE TITLE
deconz and ecozy

### ISSUE THREAD

**Issue by leSandwichman** [dresden-elektronik/deconz-rest-plugin#377]
hello,

so i dont know if i have missed something in the documentation or something else.
i paired an ecozy thermostat with my raspbee. it appears in the deconz gui and it shows the values you can read. but it doesnt appear in the rest API. do i have to add something maually or how do i get the values via the API ? 

best regards

**Comment by manup** [comment]
Discussion continues in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/209
