### ISSUE TITLE
[Jeedom Deconz plugin] not recognised as Hue Bridge by official Harmony and Hue apps

### ISSUE THREAD

**Issue by ArnoM9** [dresden-elektronik/deconz-rest-plugin#3777]
## Describe the question or issue you are having

Hi,
I am using a conbee II dongle with deconz plugin in Jeedom on a Raspberry PI 3B+. Everything is working fine in Jeedom, my zigbee and hue bulbs are included and I can also pair the gateway to hueessentials app.
However I would like also to pair the gateway with Hue and Logitech Harmony official  apps. I tried to authenficate and pair the gateway without success : no "Hue bridge" is found.
I search (a lot) and I might have found that these apps are interrogating port 8080 of the gateway for pairing while the  configured gateway port in jeedom is 8484. I tried to change and redirect it without success.

So, I would like to know if my assumptions are correct and if there is a workaround to pair also with Hue and Harmony official apps.

Thank you
Kind regards/MfG

Arno

## Environment

 - Host system: (Raspberry Pi )
 - Running method: (Jeedom deconz plugin on Raspberry)
 - Firmware version: 26670700
 - deCONZ version: 2.05.88
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
Hi!

It is needed to run on 8080 for those apps. I can say it works for Harmony. However, after a change on the Hue side, the hue app doesn't work anymore. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2852

**Comment by ArnoM9** [comment]
Hello,
Thank you very much. So my assumption was correct...
How can I change the port to 8080 in the jeedom deconz plugin configuration page ?
I tried without success.
Thanks again

Best regards/MfG

Arno

**Comment by Mimiix** [comment]
Hi

Unfortunately, i have no clue. I am not familiar with Jeedom :( 

Kind regards,

**Comment by Smanar** [comment]
What happen if you change the setting here ?

![image](https://community.jeedom.com/uploads/default/original/2X/4/4c99be0a6427b2f6465acfdd2ed4b8c3cbf5d3e3.png)

You probably need to restart the "demon" after that.
To check if it work, try to access to phoscon.

**Comment by ArnoM9** [comment]
Hello,
I already tried this step but then the gateway is unreachable. In fact 8484 port is hardcoded during local installation of the deconz plugin in Jeedom.
I think I will try to uninstall on local and try to install again directly on the raspberry which hosts my jeedom server without using the plugin. Hopefully I will be able to configure the port number.
Thank you

**Comment by Smanar** [comment]
> I already tried this step but then the gateway is unreachable

It mean it  works, no ?

But yes it s probably hard coded, do you have take a look in the file deconz.service

`sudo nano /lib/systemd/system/deconz.service`

But If I remember jeedom don't use service but run deconz with command line ? The problem is files are not open source, so I realy don't know how they do their magic ...

**Comment by ArnoM9** [comment]
Hi
Thanks for your feedback.
I finally installed deconz directly on the raspberry (port 8080). I am now able to pair harmony app. However, I still cannot pair the Hue app, the gateway is not recognized.
Do you know if there is a specific pairing operation in order to have my gateway recognized by Hue app ?
I read an older comment in the forum that a SSL connection was necessary between the app and the gateway. I do not know if if is the case...
Thank you again for your support

Arno

**Comment by Mimiix** [comment]
I think the Hue app won't work anymore, as they changed something on their end.

**Comment by ArnoM9** [comment]
Hello,
I already tried this step but then the gateway is unreachable. In fact 8484
port is hardcoded during local installation.
I think I will try to uninstall on local and try to install again on the
raspberry which hosts my jeedom server.
Thank you
