### ISSUE TITLE
EWelink ZigBee Smart Plug 

### ISSUE THREAD

**Issue by jfparis** [dresden-elektronik/deconz-rest-plugin#3786]
Hi 

Not sure whether the device is supported or partially supported. It does not appears on any list of supported devices but is somehow connected

## Device

- Product name: EWelink ZigBee Smart Plug
- Manufacturer: eWelink
- Model identifier: SA-003=Zigbee
- Device type : Please remove all unrelated device types. 
  - Switch

NB: The device is somehow connected to my conbee II but 
* identified as a "light"
* If I try to edit the name in Phoscon, it starts to switch on /off / on / off until I hit save 

## Screenshots
![Screenshot from 2020-11-30 22-34-46](https://user-images.githubusercontent.com/48999/100676511-f24de400-3360-11eb-9afd-eef0c3503d9a.png)
![Screenshot from 2020-11-30 22-32-32](https://user-images.githubusercontent.com/48999/100676515-f5e16b00-3360-11eb-95b5-a3ee79f20eeb.png)

**Comment by SwoopX** [comment]
Nothing to do for us here, the device works out of the box.

**Comment by Woll3** [comment]
Device is working (on/off) but I don't have power meter! How can I add this? Thanks!

**Comment by Smanar** [comment]
I don't think it have them, no cluster for that on capture.

**Comment by jfparis** [comment]
The model for which I provided the screenshots did not have a power meter in it. @Woll3 might have a new model and should probably submit a new bug / request

**Comment by Woll3** [comment]
> 
> 
> The model for which I provided the screenshots did not have a power meter in it. @Woll3 might have a new model and should probably submit a new bug / request

![grafik](https://user-images.githubusercontent.com/48292646/122673649-b6ca1880-d1d1-11eb-811a-28f0f0473f90.png)

I think that I have the same unit as you! I think I bought the wrong ones!

**Comment by TischerT** [comment]
Sorry to open up this old topic.
I bought an updated version of this plug (SA-030) as the previous model does not seem to be easily available anymore.
I expected that it will just work out of the box as well, but I can't get it connected. Others seem to have it working with Smartthings and Zigbee2MQTT, but of course this does not say anything about the controller they are using.

I'm using an original Raspbee (so I hope I kind of know what I'm doing as I have plenty of other devices working) and assume it's just too old at this point.
I don't expect any work on this to integrate it, just writing down my thoughts for other users.

**Comment by Smanar** [comment]
It don't work or you miss the power mesurement ?
Can you show the node picture from deconz ?

**Comment by TischerT** [comment]
Thanks for the reply!
Unfortunately, no picture from deconz, because I can't get the plug to connect at all. The plug is in pairing mode, I tell phoscon to scan for new devices, but it's not picked up (neither as light nor as plug). Whatever signals the plug is sending out, the raspbee don't seem to find these valid.
I can connect other new devices to my raspbee, so it's not a problem on this end. However, I can't exclude that the plug that I got is somehow dysfunctional.

**Comment by Mimiix** [comment]
> Thanks for the reply! Unfortunately, no picture from deconz, because I can't get the plug to connect at all. The plug is in pairing mode, I tell phoscon to scan for new devices, but it's not picked up (neither as light nor as plug). Whatever signals the plug is sending out, the raspbee doesn't seem to find these valid. I can connect other new devices to my raspbee, so it's not a problem on this end. However, I can't exclude that the plug that I got is somehow dysfunctional.

Can you please open an forum post about this?

Locking this up
