### ISSUE TITLE
Firmware problem ?

### ISSUE THREAD

**Issue by gmezz23** [dresden-elektronik/deconz-rest-plugin#379]
Hello everyone,

I want to realize a network using several "Connect Port X4H", using them as "Router", for 

the management of end points, such as "XBEE Digi Sensors adapter L/H/T". 
They must comunicate with the central "coordinator", realized by a Raspberry Pi2 with 
mounted on a "RaspBee premium" Zigbee manager.

My questions are:

- I installed the deConz package on the dedicated RPi O.S. following the RaspBee User Manual guidelines. The adopted OS is: Raspbian Jessie from: https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/raspbee-gw-sd-card-image/?L=1 .
When I try to automatically find the nodes, deConz do not find the connected nodes. They result associate to the Connect Port X4H, which is a router of my system. Where is the problem?

- Probably, the problem lies in the RaspBee firmware.
Actually on our Digi-based system the Connect Port X4H Nema 4X/IP66 Rated control panel show me that the loaded firmwares are:

Gateway Firmware:   0x21a0
Firmware: 2.14.1.15   (Version 82001536_K2 03/08/2012)
Sensor Node Firmware Version:  0x2ca7 

Where I can find a ".zigbee" extension to update my RaspBee?

You can find the above mentioned component/software in the following:

-Connect Port X4H Nema 4X/IP66 Rated:
https://www.digi.com/resources/documentation/digidocs/PDFs/90000832.pdf
https://www.digi.com/pdf/ds_connectportx4.pdf
-XBEE Digi Sensors adapter L/H/T:http://docs-europe.electrocomponents.com/webdocs/1147/0900766b8114779c.pdf
-RaspBee:https://shop.dresden-elektronik.de/raspbee.html?___store=english
-deConz:https://www.dresden-elektronik.de/funktechnik/products/software/pc/deconz/

I hope you can help me and I thank you all,
Giovanni

**Comment by manup** [comment]
I have no experience with the Connect Port X4H but the XBee S2 modules can be joined as router as described here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/380

The RaspBee doesn't need different firmware and should just run as coordinator (default setting).
