### ISSUE TITLE
Heiman gas sensor HS1CG-E with new model id GASSensor-EF-3.0

### ISSUE THREAD

**Issue by adolfomendes** [dresden-elektronik/deconz-rest-plugin#3796]
# Device

- Product name: Gas sensor HS1CG-E 
- Manufacturer: Heiman
- Model identifier: GASSensor-EF-3.0
- Device type : Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/29480988/101025231-0dcd1080-3554-11eb-9ba4-d3b6f8ca204e.png)
![image](https://user-images.githubusercontent.com/29480988/101025318-2ccba280-3554-11eb-8032-0bef00791496.png)

**Comment by SwoopX** [comment]
Closing this one because a) supported and b) incomplete device request.

**Comment by centauri** [comment]
> Closing this one because a) supported and b) incomplete device request.

Does this mean it is supported see image below?
Version: 2.07.01 
Firmware: 26680700
![image](https://user-images.githubusercontent.com/1310223/102927096-8d386a80-4496-11eb-81b5-00ccc17df741.png)

**Comment by SwoopX** [comment]
This looks like an incorrectly paired device. How have you paired it in Phoscon, via light or sensor search?

Anyway, I'd suggest to remove the device from power, start sensor search in Phoscon and plug it in again. If you're really unlucky, this device is one of the edge cases, which my IAS zone refactor should take care of in future during pairing...

**Comment by centauri** [comment]
> This looks like an incorrectly paired device. How have you paired it in Phoscon, via light or sensor search?
> 
> Anyway, I'd suggest to remove the device from power, start sensor search in Phoscon and plug it in again. If you're really unlucky, this device is one of the edge cases, which my IAS zone refactor should take care of in future during pairing...

Thank you for the reply. I did a "add new sensor" again but this time i kept on pressing the test button every second or so until the text "Gas sensor" appeared in deconz and then it also appeared in phoscon.
