### ISSUE TITLE
Color temperature range - light vs. group

### ISSUE THREAD

**Issue by ACrazyConcept** [dresden-elektronik/deconz-rest-plugin#3808]
## Describe the question or issue you are having

It seems that the color temperature range of a group is always 
min_mireds: 153
max_mireds: 500

Even if only a single light is in the group and its range is e.g.
min_mireds: 140
max_mireds: 650

I don't know if that is a bug or a feature? :)

## Screenshots
This is at least what Home-assistant tells me:
![image](https://user-images.githubusercontent.com/36438756/101179600-be1d4080-364a-11eb-8f93-769e15e7ce9c.png)
![image](https://user-images.githubusercontent.com/36438756/101179645-cc6b5c80-364a-11eb-8ab3-85499794dc75.png)

## Environment
 - Host system: RPi 4
 - Running method: Phoscon image
 - Firmware version: 26680700
 - deCONZ version: 2.07.00
 - Device: ConBee II

**Comment by LindyBalboa** [comment]
There is still something funny here. Disagreement on both HA and deconz side. 

![image](https://user-images.githubusercontent.com/20605205/154454160-9ae6e86d-12be-46ab-8202-6f4157d28fce.png)
for living_room_ceiling_1:
![image](https://user-images.githubusercontent.com/20605205/154454256-7d28f420-9501-4e58-9ddc-79a744b76e12.png)
