### ISSUE TITLE
Lights keep turning on by themselves

### ISSUE THREAD

**Issue by Martin-Gardner** [dresden-elektronik/deconz-rest-plugin#381]
I have an IKEA colour temp bulb and a Philips colour temp bulb in a bedroom group and a Hue dimmer group. The Philips colour bulb is also bound to an IKEA remote. I turn off the lights, then after some minutes they turn back on again! I would say that it is about three minutes before they are turned back on again. I have turned them off using the Phoscon app and the Home Assistant front end. This does not seem to happen so much when using the remotes. Any ideas what is going on here?

I have enclosed a picture on my setup within deCONZ, tell me if you need more information.

Cheers,

Martin

![image](https://user-images.githubusercontent.com/35814778/35449045-cfca7064-02b3-11e8-9cb6-4311f7ed2885.png)
![image](https://user-images.githubusercontent.com/35814778/35449292-8e8494e4-02b4-11e8-8aa1-38825db0c287.png)

**Comment by jonathanweinberg** [comment]
May I ask if you are dead certain there is no flickering of power where they are connected? No dimmer switch? I've had a devil of a time with just such a thing in a setup of my own once upon a time.

**Comment by manup** [comment]
Further are there any rules/motion or sensors controls defined which also turn on the lights?

**Comment by Martin-Gardner** [comment]
No physical dimmer and no rules or sensors.

**Comment by Martin-Gardner** [comment]
The motion sensor is not configured and is in a draw anyway

**Comment by onalzengin** [comment]
@Martin-Gardner If you are using fluxer component with Home Assistant, that is probably the reason.

**Comment by Martin-Gardner** [comment]
reinstalled from todays backup - issue went away
