### ISSUE TITLE
Debug View HowTo Close?

### ISSUE THREAD

**Issue by Alissh** [dresden-elektronik/deconz-rest-plugin#3821]
## Describe the question or issue you are having

When i open the new "Debug View", i don't find the "Close" button.
A 2nd click in the Help --> Debug View don't close it too.
Bug, wrong "doing" or "Home Assistent deCONZ Add-on" bug?

## Screenshots

![deCONZ_Debug_View_20201206](https://user-images.githubusercontent.com/17932650/101279078-1aee3780-37c0-11eb-949e-cd3d3a100e74.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26660700)
 - deCONZ version: (2.05.88)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs

No Logs

**Comment by SwoopX** [comment]
A right click on the title bar doesn't give you any menu?

**Comment by Alissh** [comment]
There is no right click menu on title bar.
Only double click before "title bar text" collapse the window.

**Comment by cllatser** [comment]
Press the ESC key. :) Same thing happened to me.

**Comment by Alissh** [comment]
@cllatser thanx for your fabulous tip, it worked!

**Comment by Dreamoffice** [comment]
how can i copy the text out of the debug window? 
select all > copy but i can t paste it, clipboard is still empty

**Comment by Smanar** [comment]
And ctrl+c ?

**Comment by pattyland** [comment]
As this issue it at the top of Google Results: Clipboardsync does not work with Web VNC. You need a real Deskop VPN Client and activate the VNC port in the addon config
