### ISSUE TITLE
KNYCKLAN Open/Close remote

### ISSUE THREAD

**Issue by frassefraze** [dresden-elektronik/deconz-rest-plugin#3824]
## Device

- Product name: TYPE E1841 -  KNYCKLAN Open/Close remote
- Manufacturer: IKEA of Sweden
- Model identifier: KNYCKLAN Open/Close remote
- Device type : Please remove all unrelated device types. 
  - Remote
  - Switch

## Screenshots
![image](https://user-images.githubusercontent.com/5294314/101351350-c49cf980-3890-11eb-90dd-16c54c1ed89b.png)
![image](https://user-images.githubusercontent.com/5294314/101351398-d4b4d900-3890-11eb-8163-66fce643480e.png)
![image](https://user-images.githubusercontent.com/5294314/101351450-e5654f00-3890-11eb-80f3-b67e4d85f94a.png)

![image](https://user-images.githubusercontent.com/5294314/101356987-21041700-3899-11eb-993a-c79273d48bac.png)
![image](https://user-images.githubusercontent.com/5294314/101357009-295c5200-3899-11eb-9080-44648ef455c7.png)
![image](https://user-images.githubusercontent.com/5294314/101357036-2feac980-3899-11eb-9a90-cd99cd80e058.png)
![image](https://user-images.githubusercontent.com/5294314/101357048-36794100-3899-11eb-8849-a81cecd2f0fe.png)
![image](https://user-images.githubusercontent.com/5294314/101357066-3da04f00-3899-11eb-9bf5-ab08a5aeb619.png)

**Comment by Mimiix** [comment]
Missing screenshots of all other clusters.

**Comment by frassefraze** [comment]
For some reason I took that as optional, sorry about that. Updated the original post with additional clusters.

**Comment by MattWestb** [comment]
Pleas read / (manual) Update SW Build ID from basic cluster (0x4000).
I looking very like the 2 On/Off and Open/Close controllers but have different firmware ID (0x11c9) so new OTA images is coming soon.

E2001 and E2002 STYRBAR Remote control is also on the way :-))

**Comment by frassefraze** [comment]
SW Build ID: 2.3.019

Updated all of the values one by one below (shouldn't the top "Read" button pick them all up?).
![image](https://user-images.githubusercontent.com/5294314/101455318-abe52000-3932-11eb-8891-c37254d93b5e.png)

**Comment by MattWestb** [comment]
Thanks very much i putting the info on known firmware but without known updates.
For My deCONZ is more or less not reading all attributes from the basic cluster automatic or manual must making it manual record by record like you was doing (Undocumented future).

Do you have the receiver E1842 in in deCONZ 2 ? 
Im interested of device ID and FW version if you can getting it. [KNYCKLAN receiver](https://zigbeealliance.org/zigbee_products/knycklan-receiver/)

**Comment by frassefraze** [comment]
Sure, here is the receiver data

![image](https://user-images.githubusercontent.com/5294314/101497770-9cce9400-396b-11eb-9fd1-d4ae53f18d74.png)
![image](https://user-images.githubusercontent.com/5294314/101498306-3c8c2200-396c-11eb-8a86-79ec465036b6.png)
![image](https://user-images.githubusercontent.com/5294314/101497792-a35d0b80-396b-11eb-91d3-fbfd5ba6d7b5.png)

**Comment by MattWestb** [comment]
Gret !!

I need the Image Type ID from the OTA cluster attribute 0x0008.

**Comment by frassefraze** [comment]
There you go ( Image Type ID - 0x1103 ) 
![image](https://user-images.githubusercontent.com/5294314/101499441-917c6800-396d-11eb-8476-d24f59c9d25a.png)

**Comment by MattWestb** [comment]
Tackar och bockar Jonas !

Added to known firmware in the Wiki.

**Comment by MattWestb** [comment]
Is the the KNYCKLAN receiver working in deCONZ and you can sending on / off commands to it and also adding it in one groupe and sending commands ?
If yes try bind the remotes on/off cluster (0x0006) to the the same group in deCONZ GUI.

Its dont getting it nice implanted in Phoscon app but perhaps the funktion working locally and also from HA.

**Comment by frassefraze** [comment]
Yes the KNYCKLAN receiver is working just fine in deconz, I can turn it on and off. 
But I actually just want to use the KNYCKLAN remote as a remote for other stuff picking up the events. I usually (not so much right now) use KNYCKLAN for outdoor watering and start it from HA using a timer, so I don't forget to turn it off, or I just use the cord connected "remote".

**Comment by MattWestb** [comment]
Do you not giving your "Adventsgran" weather ?!?!?!?
And Rudolph the reindeer also need weather then doing the express deliveries of smart things in the north !!!

I dont knowing if its possible getting the events from the remote in deCONZ without the devs have implanting it in the code but I think not then its need being whitelisted and configured in the codebase for working OK.

But if you like you can loading the E1743 firmware and userdata and you can using it as the normal on/off switch (but need little souldring and SWD flasher for doing it) but its more expensive than buying one new (around 6€).

**Comment by MattWestb** [comment]
Im sorry but i think adding support for new devices can taking little time for the moment then its not so easy getting the code being done by the company's devs. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3765
I you or other users can doing it then its can being done faster (company policy ?)

Mhv  MW

**Comment by frassefraze** [comment]
Still want this…

**Comment by Mimiix** [comment]
@SwoopX what do we need to make this happen?

**Comment by oywino** [comment]
@frassefraze can you please post copies of the deconz_event  from the button ?  (short press on/off as well as long press on/off)

**Comment by frassefraze** [comment]
If the events showed up I wouldn't have created this post. Are they supposed to show up even if the device isn't supported or even added in phoscon ? I can only partly see it in deCONZ. But maybe I'm looking in the wrong place…

**Comment by Mimiix** [comment]
It isn't supported yet. However, i think it might be the same as the on/off switch and the fyrtur up/down.

We have to wait for a dev to integrate it.

**Comment by oywino** [comment]
If you can see it in deCONZ, then you're normally good to go. It doesn't have to be visible in Phoscon to operate. Have you tried the REST-API ?

**Comment by Mimiix** [comment]
@oywino That's not correct. The screenshot indicates that it is not supported. You can see that because of its name being hex-valued.

**Comment by oywino** [comment]
I see, my bad. I thought it popped up as a switch or a light perhaps. 
Guess we just have to wait then .....

**Comment by SwoopX** [comment]
It would be best to have that device in hands as Ikea has some twists of it's own. The usual "whitelist and go for it" is probably not enough here, so ideally somebody does it with some experience in Ikea devices.

**Comment by frassefraze** [comment]
I still want to be able to use my little droplet remote, so I'm keeping this active.

**Comment by oywino** [comment]
Bump +1

**Comment by frassefraze** [comment]
Yeah I'm stubborn… I still want this :)

**Comment by Mimiix** [comment]
This remote seems to be the same as the On/Off and Open/Close remote. @ebaauw @SwoopX Can't we take over those configs?

**Comment by ebaauw** [comment]
On/off and open/close remotes may look similarly mechanically, but are very different devices at Zigbee level.  As with any wireless controller, we need to know which commands it sends on what button actions.  Looking at the STYRBAR, it seems IKEA are even putting more variation in their wireless controllers...

**Comment by Mimiix** [comment]
@ebaauw So it would be best if you had one hands on?

**Comment by ebaauw** [comment]
That would be easiest, indeed.

**Comment by frassefraze** [comment]
Bump

**Comment by oywino** [comment]
Bump

**Comment by dabepp** [comment]
Bump! Any update on the Styrbar E2001 FCC ID FHO-E2001?

**Comment by rayitaly** [comment]
Bump! Any update on the Styrbar E2001 FCC ID FHO-E2001?

**Comment by Mimiix** [comment]
Isn't that another switch?

**Comment by dabepp** [comment]
> Isn't that another switch?

Unfortunately no. I can't add it do COnbee II,  neither as others -> switch nor as IKEA remote...

**Comment by Mimiix** [comment]
No, i mean that a Styrbar remote is a different switch than an Knycklan.

**Comment by dabepp** [comment]
> No, i mean that a Styrbar remote is a different switch than an Knycklan.

Yes, I've just hitchhicked the device request. Sorry. I guess I just create another request, right?
