### ISSUE TITLE
Latest beta update for Ubuntu

### ISSUE THREAD

**Issue by lillpjot** [dresden-elektronik/deconz-rest-plugin#383]
Hi,

I'm looking for the latest .deb for Ubuntu (non RPI)?
I've found the 2.05 for RPI but not the same for Ubuntu.

Thanks in advance

**Comment by manup** [comment]
I close the issue since package is online now

https://www.dresden-elektronik.de/deconz/ubuntu/beta/deconz-2.05.00-qt5.deb
