### ISSUE TITLE
LEDVANCE LED Panel Connected+ 625x625 UGR19

### ISSUE THREAD

**Issue by AndreasPollinger** [dresden-elektronik/deconz-rest-plugin#3843]
Tunable White LED Panel is wrongly detected as color light. Phoscon app therefore provides the wrong control sliders for the light.

- Product name: LEDVANCE LED Panel Connected+ 625x625 UGR19
- Manufacturer: LEDVANCE
- Model identifier: Panel TW 620 UGR19
- Device type : Light (Tunable White)

## Screenshots

![image](https://user-images.githubusercontent.com/75698718/101540496-63644b80-39a0-11eb-8dcc-e01b297af9f4.png)
![image](https://user-images.githubusercontent.com/75698718/101540539-737c2b00-39a0-11eb-92fc-f7820b8c5476.png)

Please let me know if additional screenshots/information is required.

**Comment by AndreasPollinger** [comment]
refreshing...

**Comment by Mimiix** [comment]
Can you check if it works correctly with the rest api?

If that's the case  I move the issue to the phoscon repo.

**Comment by AndreasPollinger** [comment]
It works with the rest API. I can set the value of the color temperature there trough the "ct" paramter and the light reacts accordingly.
However I still think that it is not only an issue with the phoscon app, as I am having the same problem with the light in openhab.
From the REST API I get the following information for the LEDVANCE CONNECTED+ lamp:
![Ledvance Connected+](https://user-images.githubusercontent.com/75698718/104094227-c3942900-528f-11eb-9885-b54c203aaeda.JPG)
There is no "ct" value there but the "sat" & "xy" value.
For my LEDVANCE SMART+ lights (also tunable white LED Panels) which are working fine everywhere I get the following from the REST API:
![Ledvance SMART+](https://user-images.githubusercontent.com/75698718/104095244-2092dd80-5296-11eb-9106-d6a7d15d4e5d.JPG)

**Comment by AndreasPollinger** [comment]
Refeshing...

**Comment by AndreasPollinger** [comment]
Refreshing...

**Comment by Smanar** [comment]
The problem is IDK if in the actual deconz version it s possible to block some field in the JSON.
We need something special to reconize the device.

**Comment by AndreasPollinger** [comment]
Hey Smanar,
thank you for looking into this.

What do you mean by you need something special to reconize the device?
The model identifier is shown in my first post. So you need something additional?
