### ISSUE TITLE
Heiman HS2SK-E

### ISSUE THREAD

**Issue by twobeass** [dresden-elektronik/deconz-rest-plugin#3849]
## Device

- Product name: HS2SK-E
- Manufacturer: Heiman
- Model identifier: SmartPlug
- Device type : Please remove all unrelated device types. 
  - Light
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/4639195/101619755-fe4a3d80-3a13-11eb-8094-f12a770a43b8.png)
![image](https://user-images.githubusercontent.com/4639195/101619861-1ae67580-3a14-11eb-863e-e6da6041d375.png)
![image](https://user-images.githubusercontent.com/4639195/101619937-3487bd00-3a14-11eb-85de-cf0673547899.png)
![image](https://user-images.githubusercontent.com/4639195/101619981-436e6f80-3a14-11eb-91e4-65f19c958a62.png)

The Device is only shown as light. The power measurement features are not available via API

**Comment by SwoopX** [comment]
The device is fully supported

**Comment by Mimiix** [comment]
@SwoopX User reported on Discord that he cant use the power measurements from the websocket/api.

**Comment by twobeass** [comment]
Correct, like Mimix said there are no Infos about Power Measurements in the REST API

**Comment by twobeass** [comment]
I am sorry, after a full system restart, i got two new Sensors via REST named "type": "ZHAConsumption" and "type": "ZHAPower" that were missing before... 
Topic closed, Device is fully supported...
