### ISSUE TITLE
No neighbor links visible in deCONZ 2.07.01 

### ISSUE THREAD

**Issue by Einstein2150** [dresden-elektronik/deconz-rest-plugin#3850]
## Describe the question or issue you are having

After `apt upgrade` to the latest Version 2.07.01 everything seems working fine. After a full reboot of the raspberry pi the connection lines "Neighbor Links" are gone but the network is working normal.

## Screenshots

![Bildschirmfoto 2020-12-09 um 11 45 23](https://user-images.githubusercontent.com/22019133/101620263-9a744480-3a14-11eb-9e2b-11ce9c804718.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.07.01)
 - Device: RaspBee I
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs

none

## Additional context

The issue occurred first after the reboot of the pi. After the first manual restart of the deCONZ GUI (without reboot of the whole system) the lines were visible...

**Comment by Einstein2150** [comment]
Now after nearly exact 1 hour after boot the lines start drawing ...

![Bildschirmfoto 2020-12-09 um 12 09 44](https://user-images.githubusercontent.com/22019133/101622550-7c5c1380-3a17-11eb-8c6f-654f47905bed.png)

What is causing this delay?

**Comment by manup** [comment]
Odd, there is a new button `Neighbor Links` which can be used to disable drawing them but after startup it defaults to true.
(The reason for the button are large networks where drawing can be painfully slow)

**Comment by jensflorian** [comment]
I can't find 2.07.01 in https://deconz.dresden-elektronik.de/raspbian/beta/

**Comment by SwoopX** [comment]
Stable

**Comment by Einstein2150** [comment]
Visualisation-bug was fixed by installing the latest raspbian update. Neighbor links are drawing now right after the startup of deCONZ.
