### ISSUE TITLE
LOM004 Philips hue plug is sending a brightness attribute (bri)

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#3860]
## Describe the bug
 LOM004 Philips hue plug is sending a brightness attribute (bri). On Homeseer platform this is wrongly considered as a diming light because of this.

## Steps to reproduce the behavior
 Get the json via the api

## Expected behavior

 return a json without the bri attribute
## Screenshots

![image_96211](https://user-images.githubusercontent.com/27497561/101730151-83bb0580-3a87-11eb-8fd5-d1fae0283ffa.png)
## Environment

 - Firmware version: 26680700
 - deCONZ version: 2.07.01
 - Device: Conbee II

**Comment by SwoopX** [comment]
Can you share a screenshot of the node with the clusters expanded in deconz GUI?

If it doesn't have/support bri, we can filter it out...

**Comment by ebaauw** [comment]
It’s quite common for on/off plugs to carry a _Level Control_ cluster, so they can respond to _Move to Level ( with On/Off)_, and be controlled by switches that send that command instead of _On_ and. _Off_.

**Comment by Mimiix** [comment]
@ebaauw So this is something that Homeseer needs to sort-out?

**Comment by wvuyk** [comment]
There was another post on this github (sorry cannot find it) where the remark made was that for on/off plugs the bri attribute will or should be omitted. And indeed for most plugs the bri attribute is not present. So far I can see plugs used, the LOM004 is the exception to this. 
I can try to recognise the plugs based on the type, but I remember that the type can differ too based on the model? Too many different methods to determine what device is presented....

**Comment by MattL0** [comment]
> Can you share a screenshot of the node with the clusters expanded in deconz GUI?
> 
> If it doesn't have/support bri, we can filter it out...

I would want to.. but I am running headless here, with minimal install

**Comment by ebaauw** [comment]
> So this is something that Homeseer needs to sort-out?

I surely hope not; it should be fixed by the REST API Plugin.  Check the closed issues, we've done so for several plugs already (including the beloved innr SP120).

**Comment by MattL0** [comment]
I deployer a docker install. so it was easy to launch vnc . 

Is that what you need ? 

<img width="149" alt="1" src="https://user-images.githubusercontent.com/27497561/101861232-8c6e1300-3b3d-11eb-88ae-b5896eb5981f.PNG">
<img width="302" alt="2" src="https://user-images.githubusercontent.com/27497561/101861233-8d06a980-3b3d-11eb-82c4-5778e66ce673.PNG">
<img width="278" alt="3" src="https://user-images.githubusercontent.com/27497561/101861234-8d06a980-3b3d-11eb-9c80-05332ff03a52.PNG">
<img width="172" alt="4" src="https://user-images.githubusercontent.com/27497561/101861235-8d06a980-3b3d-11eb-8752-be1f561daaed.PNG">
<img width="150" alt="5" src="https://user-images.githubusercontent.com/27497561/101861237-8d9f4000-3b3d-11eb-99ee-1f6d4afef568.PNG">
<img width="161" alt="6" src="https://user-images.githubusercontent.com/27497561/101861238-8d9f4000-3b3d-11eb-852f-fd8059b29cf0.PNG">
<img width="104" alt="8" src="https://user-images.githubusercontent.com/27497561/101861239-8d9f4000-3b3d-11eb-9121-89724c1147b5.PNG">

**Comment by ebaauw** [comment]
That should do it.
