### ISSUE TITLE
Schwaiger ZHS-15 Plug power consumption to Home-Assistant

### ISSUE THREAD

**Issue by Kedakai** [dresden-elektronik/deconz-rest-plugin#3884]
## Feature request type
- Implement the power consumption submitting feature for this model, so it can be used in HASS

## Description
Manufacturer: RT-RK
Model identifier: SPW35Z-D0
Device type : Switch

## Considered alternatives
I read about Zigbee2MQTT, which works for power consumption. I didn't try it out, but i considered it.
See here: https://www.zigbee2mqtt.io/devices/ZHS-15.html

## Additional context
Both Firmware and deconz are the newest Version.
Deconz: 2.07.01
Firmware for ConBee: 26390500

**Comment by Mimiix** [comment]
Please file a device request issue with all requested info and screenshots. Thanks!
