### ISSUE TITLE
Orvibo ST30 Temp/Humidity Sensor with diplay

### ISSUE THREAD

**Issue by samsam-rolon** [dresden-elektronik/deconz-rest-plugin#3885]
![image](https://user-images.githubusercontent.com/25209236/101970272-ba308600-3c29-11eb-967a-0a43b9177600.png)

## Device

- Product name: Orvibo ST30.
- Manufacturer: FEI
Basic cluster
![image](https://user-images.githubusercontent.com/25209236/101970331-10052e00-3c2a-11eb-91d0-b0603d0df75a.png)

- Model identifier: As screenshot
- Device type : 
  - Sensor
![image](https://user-images.githubusercontent.com/25209236/101970357-257a5800-3c2a-11eb-9f10-a012dfa3e3dc.png)

## Screenshots

PowerConfig cluster
![image](https://user-images.githubusercontent.com/25209236/101970399-683c3000-3c2a-11eb-890e-9a0b1fddeab2.png)

Temp cluster
![image](https://user-images.githubusercontent.com/25209236/101970403-78540f80-3c2a-11eb-966c-77a4faaa4f82.png)

Humidity cluster 01
![image](https://user-images.githubusercontent.com/25209236/101970432-9ae62880-3c2a-11eb-9c2c-c7386a69b8e9.png)

Humidity cluster 02
![image](https://user-images.githubusercontent.com/25209236/101970439-a89bae00-3c2a-11eb-810a-41fbb0974b7a.png)

**Comment by Smanar** [comment]
This device is already in code https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2489
Just need to add some lines, will be fast.

**Comment by samsam-rolon** [comment]
IDK why there is 2 Relative humidity measurement but it's the cluster 0405 which it's standalone (the last one) which is working.
Here the last screenshot 😄 

![image](https://user-images.githubusercontent.com/25209236/101984024-f2ae7f00-3c7e-11eb-8cc9-020c84891720.png)

**Comment by Smanar** [comment]
Ok so first try, you know the procedure now ^^

```
git clone --branch orvibo https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

This PR
- make the device pairable
- change the name "898ca74409a740b28d5841661e72268d" in "ST30 Temperature Sensor", can have made typo here
- Prevent the creation of humidity sensor for cluster 0x01

**Comment by samsam-rolon** [comment]
I think there is a typo error  :S
![image](https://user-images.githubusercontent.com/25209236/102700631-7a802480-424f-11eb-9221-287b41983476.png)

**Comment by Smanar** [comment]
No it s not a typo ^^
I had this bug too, need to update the system (or just deconz-dev if you can)

**Comment by samsam-rolon** [comment]
System is already updated, IDK why. But if i'm changing `dataType_t `in `dataType` it's compiling ! But not working in deconz IHM / API / WebGUI

**Comment by samsam-rolon** [comment]
Okay, my bad compilation works now ...

**Comment by Smanar** [comment]
Yeah, I don't know the moethod to update only the dev package (not worked) so on mu side have upgraded all the OS

```
sudo apt update
sudo apt full-upgrade
```

**Comment by samsam-rolon** [comment]
Yeah, i've done it and it's Okay now for compiling but notthing in GUI or API.

**Comment by Smanar** [comment]
You have tried to re-include it ? (Or read again basic attribute with phoscon in permit join) ?
There is some log about this device ?

**Comment by Smanar** [comment]
Can you share log during inclusion if it s still not working ?

**Comment by srtxema** [comment]
i can´t sync with phoscon. is there any special sync mode?

**Comment by Smanar** [comment]
@srtxema you are using the recompiled code ?

**Comment by samsam-rolon** [comment]
Sorry @Smanar  ! With holidays, not easy to work on it ! I'll will test deeply next week !

**Comment by samsam-rolon** [comment]
Hello @Smanar !
I confirm : re-inclusion let it detected now !
![image](https://user-images.githubusercontent.com/25209236/104122267-4ecef680-5344-11eb-81d7-710c2b6cf263.png)
`json
{
  "config": {
    "battery": 100,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "b7b6b57e79e89d4dd8092b118257fede",
  "lastseen": "2021-01-10T12:03Z",
  "manufacturername": "fei",
  "modelid": "ST30 Temperature Sensor",
  "name": "ST30 Temperature Sensor",
  "state": {
    "lastupdated": "2021-01-10T12:03:44.533",
    "temperature": 1986
  },
  "swversion": "ST01",
  "type": "ZHATemperature",
  "uniqueid": "00:15:8d:00:03:56:9d:2a-01-0402"
}
`

`json

{
  "config": {
    "battery": 100,
    "offset": 0,
    "on": true,
    "reachable": true
  },
  "ep": 2,
  "etag": "01375309452f213eccf49fab3a9d7a4c",
  "lastseen": "2021-01-10T12:03Z",
  "manufacturername": "fei",
  "modelid": "ST30 Temperature Sensor",
  "name": "ST30 Temperature Sensor",
  "state": {
    "humidity": 3952,
    "lastupdated": "2021-01-10T12:03:45.142"
  },
  "swversion": "ST01",
  "type": "ZHAHumidity",
  "uniqueid": "00:15:8d:00:03:56:9d:2a-02-0405"
}`

**Comment by Smanar** [comment]
>But I didn't see the device on web UI, Only through API

Yep new device, need to wait if the phoscon dev want to add it in whitelist.

Will make the PR today.

**Comment by srtxema** [comment]
> @srtxema you are using the recompiled code ?

finally i could. press the button continuosly 3 times for 20 seconds and sync.

**Comment by stifler6969** [comment]
I bought this device (ST30) but it was not recognize by jeedom/deconz (inclusion OK). I have deconz 2.07.01.
How i do ?

**Comment by Mimiix** [comment]
@stifler6969 You need to manually compile deconz on a newer version. Otherwise, you have to wait until merged and released.

**Comment by stifler6969** [comment]
@Mimiix thx for your reply. I will wait...

**Comment by samsam-rolon** [comment]
I've just upgrade deconz in 2.07.03 and it's still not working for both orvibo devices added (#3973)

**Comment by Smanar** [comment]
The pr is not validated ^^.
Easy to see, the issue will be automaticaly closed when the PR will be validated.

**Comment by samsam-rolon** [comment]
Oh yeah ! I've just seen that ! :(

**Comment by samsam-rolon** [comment]
Hello @Smanar 
I've updated in 2.10.01 and I didn't see the device, even after re-inclusion.
![image](https://user-images.githubusercontent.com/25209236/110130939-e3e0ef80-7dc9-11eb-87be-10e4ab773b5a.png)
Pairing still failing in  WebGUI and the name isn't displayed in Software- GUI 

Any idea

**Comment by Mimiix** [comment]
@samsam-rolon Need to be on 2.10.2

**Comment by samsam-rolon** [comment]
Yeah ... my bad ... latest docker image https://hub.docker.com/r/marthoc/deconz is still not maped on the latest beta .... really painful ^^'

**Comment by Leobaillard** [comment]
Hi! First of all, thanks for adding the integration!

After talking about it on the Discord, it would appear that my ST30 has a different ModelID than the one added to the code. Here is the screenshot with the info:
![image](https://user-images.githubusercontent.com/402250/112512358-971e8200-8d93-11eb-874c-4195dc72da1d.png)

For reference, the Model ID is: 50938c4c3c0b4049923cd5afbc151bde

I can provide other info if necessary!

**Comment by Smanar** [comment]
You can mimic the previous model id to make a PR, if you want ? I think you will have only 2 lines to change

**Comment by Leobaillard** [comment]
Yes, I can try to do a PR. I have started looking at the code, but weirdly enough, the manufacturer code is also different (0x1002, which matches VENDOR_EMBER). Is that common for a device that looks exactly the same?
I'm also not sure yet how to test it all as I'm currently using HA and the Deconz plugin, but I can at least work on the PR.

**Comment by stifler6969** [comment]
Hi,

I upgraded my deconz in 2.10.04 and i didn't see my ST30 sensor. I tried an new pairing. It's normal ?

**Comment by Smanar** [comment]
@Leobaillard 
Yep on my side I have see 3 modifications to do, the whitelist with the new manufacture, and 2 place in the code where you need to mimic previous code

To make modification, you need a linux machine, you have the process here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

@stifler6969 can you show the device model id ? and BTW have you a linux machine to test code modification if you need them ^^ ?

**Comment by Leobaillard** [comment]
@Smanar Yes, I gathered some info on the Discord side and started setting up my dev environment. I have resources and knowledge to accomplish that, just need time now. I'll start testing hopefully tonight or this weekend.

**Comment by Leobaillard** [comment]
PR made, the device is working on my end :)

**Comment by Smanar** [comment]
Nice, thx ^^
