### ISSUE TITLE
Device Request - LIdl - Smart Window/Door sensor

### ISSUE THREAD

**Issue by albei** [dresden-elektronik/deconz-rest-plugin#3886]
### **Device:**

- Product name: Smart Window or Door Sensor.
- Manufacturer: SilverCrest. 
- Model identifier: TY0203
- Device type : Sensor
- Other: IAN 341806_1910 SDWZ 1 A1
- https://wikilidl.com/2020/11/09/silverrest-smart-window-or-door-sensor/
### Screenshots:
<img width="1077" alt="Lidl_node_info" src="https://user-images.githubusercontent.com/1080066/101979667-a60b7980-3c67-11eb-997e-a716a5dd39fa.png">
<img width="1077" alt="Lidl_Basic_Info" src="https://user-images.githubusercontent.com/1080066/101979680-bae80d00-3c67-11eb-9a63-7d6d5856c5e5.png">
<img width="1077" alt="Lidl_Power_Config" src="https://user-images.githubusercontent.com/1080066/101979697-e539ca80-3c67-11eb-9324-00993fbc95f2.png">
<img width="1077" alt="Lidl_Identify" src="https://user-images.githubusercontent.com/1080066/101979714-1dd9a400-3c68-11eb-8d44-a5acb1fce7c3.png">
<img width="1077" alt="Lidl_IAS_ZONE" src="https://user-images.githubusercontent.com/1080066/101979717-216d2b00-3c68-11eb-947a-c8cf46b29c24.png">
<img width="1077" alt="Lidl_Diagnostics" src="https://user-images.githubusercontent.com/1080066/101979719-2500b200-3c68-11eb-933e-ca0ea3250035.png">
<img width="1077" alt="Lidl_OTA" src="https://user-images.githubusercontent.com/1080066/101979721-27630c00-3c68-11eb-9a3e-455b5bdf8ce6.png">

**Comment by Smanar** [comment]
This device is already supported, no ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3767

**Comment by albei** [comment]
Oh did not found it on Issues search, probably I was filtering the closed ones.
When I tried to add the sensor in webapp nothing happens nothing gets added.

**Comment by Smanar** [comment]
Np, so I have make an experimental code, to avoid to add 5 lignes by tuya device for all mac adress possible every time.

Do you have an Unix machine to test it ?

Explanations here : https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

```
git clone --branch tuya_general https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

Then retry to include it.

**Comment by albei** [comment]
> Np, so I have make an experimental code, to avoid to add 5 lignes by tuya device for all mac adress possible every time.
> 
> Do you have an Unix machine to test it ?
> 
> Explanations here : https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
> 
> ```
> git clone --branch tuya_general https://github.com/Smanar/deconz-rest-plugin.git
> cd deconz-rest-plugin
> qmake && make -j2
> sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
> ```
> 
> Then retry to include it.

Sadly I have deconz installed via Hassio, so its the docker image. I dont have a local deCONZ install. 
If its possible to do it on the doker image I will happily test is. But a need a hint on how to do it.

**Comment by Smanar** [comment]
You can do nothing on a docker image.
It s possible on a VM, but I have never do it on my side.

**Comment by albei** [comment]
I got the container updated and now I see it, and look like it works!
I am gonna setup a rasp image for testing anyway and install it locally for future test. And I will join discord also.
@Smanar many thanks for your work! If you need me to test it give me shout so we can talk faster on discord.

**Comment by Smanar** [comment]
So it have worked without testing the new code ?

**Comment by albei** [comment]
Yep, I rescan for sensor,pushed the button on the sensor shortly until the led blinked green once and it appeared in the list. I already made automation for it in hassio 😎.
Thanks!

**Comment by Mimiix** [comment]
Case closed
