### ISSUE TITLE
Aqara Motion Sensor doesn't work correctly after server restart

### ISSUE THREAD

**Issue by Dominik-1980** [dresden-elektronik/deconz-rest-plugin#3895]
## Describe the question or issue you are having

Hello.

I have got some problems with my two aqara motion sensors. Especially with one of them.

When I restart the server everything connects again, two remote switches, two door/window sensors, one temp/hum sensor, one Osram Plug that acts as a repeater and the motion sensors. At the beginning there is a very slow response, but after one or two hours it works like it should be, but the second motion sensor always causes trouble.

I have to repair it many times till it works again as expected.
And even then, it doesn't show every cluster in the deconz-gui that it should.
Only Basic, Illuminance measurement and Occupancy sensing is shown there. Temperature and Battery is not.
That cause me an error shown Empty Battery in Homekit.
What can I do to get all the needed cluster? Please take a look at the screenshots...

## Screenshots

![deConz](https://user-images.githubusercontent.com/32244806/101990967-d1af5380-3ca9-11eb-8135-4287d0299a4d.png)

![Bewegungsmelder unten](https://user-images.githubusercontent.com/32244806/101990968-d411ad80-3ca9-11eb-838c-49bc6b120dd0.png)

![Bewegungsmelder oben](https://user-images.githubusercontent.com/32244806/101990971-da078e80-3ca9-11eb-9cc9-3a9766c650fe.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.07.01 / 8.12.2020
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Smanar** [comment]
Strange, an both are using same device as router ?
The battery level is good (when it s displayed) ?

**Comment by Dominik-1980** [comment]
Yes. Battery is 100%. Same router...
I deleted the sensor once again and repaired it, now it shows Battery and Temperature, but only in Phoscon, not in deConz.

What makes it very strange is, that in the Phoscon App, the device recognizes my motion.
If I go in range of the sensor, Phoscon shows me the Refreshed time "some seconds ago" but Motion state still is "none".

![IMG_0008](https://user-images.githubusercontent.com/32244806/101992085-02df5200-3cb1-11eb-8155-633d69c4e91f.PNG)

**Comment by bergiusj** [comment]
I'm facing same sort of problem. One of my Aqara motion sensors are reporting lux correctly, but motion detection is very buggy. Sometimes it detects, and sometimes it's totally dead. If I inspect the sensor i Phoscon I also have Version: unkown which is not the case on the sensors that's working correctly.

**Comment by SwoopX** [comment]
@Dominik-1980 which of the sensors in your screenshot with the expanded clusters is behaving stragely? I'd assume the left one?

**Comment by Dominik-1980** [comment]
Yes. The left one. I think the problem was the repeater (plug) the sensor was connected to.
I deleted the sensor and paired it straight to the ConBee 2 Stick and it worked. 
The missing fields in deCONZ showed up after one or two hours...

**Comment by Mimiix** [comment]
Case closed?

**Comment by Mimiix** [comment]
Case closed!

**Comment by SwoopX** [comment]
Just for reference, this might be related
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3528#issuecomment-743367042
