### ISSUE TITLE
Xiaomi Door Sensor need to resynch after every deCONZ restart

### ISSUE THREAD

**Issue by nerdmovieproduction** [dresden-elektronik/deconz-rest-plugin#3905]
## Describe the bug

Hi Everyone, I have some issue with the Xiaomi Door Sensor. Everytime deCONZ need to reboot (backup upload or complete Raspberry reboot) all my Xiaomi Door Sensor stop working, disapper from VNC and i need to resynch all of it!

## Screenshots
![Catturaasaa](https://user-images.githubusercontent.com/15839123/102029179-c6455080-3dad-11eb-8df6-1b754df3a214.JPG)
![Casddssdttura](https://user-images.githubusercontent.com/15839123/102029181-c7767d80-3dad-11eb-9db3-71a316d0b7e6.JPG)

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26660700)
 - deCONZ version: (2.07.01)
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system?no

**Comment by SwoopX** [comment]
Are those Mija's, the roundish ones?
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3528#issuecomment-743367042

**Comment by nerdmovieproduction** [comment]
> Mija's, the roundish ones?

Yes! So i need to Retrieve missing descriptors in deCONZ GUI For all of it, right?

The only values that changes after this are: Max buffer Size, Max incoming transfert Size and Max Outgoing Transfert Size

**Comment by SwoopX** [comment]
Yes, that sound as if the descriptors were updated. You might want to conduct some tests before you do it on all devices.
