### ISSUE TITLE
daylight sensor not reachable

### ISSUE THREAD

**Issue by talun2075** [dresden-elektronik/deconz-rest-plugin#3907]
![notreachable](https://user-images.githubusercontent.com/27155144/102069891-a5f1b200-3dfe-11eb-923e-00ad55ae30eb.png)
![timezone](https://user-images.githubusercontent.com/27155144/102070558-9030bc80-3dff-11eb-9b5b-2f98ad44eba3.png)
Hi,
the Daylight Sensor is not Reachable.
I Use a Conbee II on a Windows System with deconz.
I add the Timezone over Phoscon App.
Gateway Informations:
2.07.01 / 8.12.2020 with Firmware 26580700

I Have found a Issue and try it do do it on this way.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/521
But it not change the Problem.

I made a put on
/api/APIKEY/sensors/1/config

{
  "long": "4.9098",
  "lat": "52.3423",
  "sunriseoffset": 0,
  "sunsetoffset": 0
}

I got a 200 Back so the Put was successfull with this answer:
[{"success":{"/sensors/1/config/lat":"52.3423","/sensors/1/config/long":"4.9098","/sensors/1/config/sunriseoffset":0,"/sensors/1/config/sunsetoffset":0}}]

After call the Sensor Informations
/api/APIKEY/sensors/1

I got this:

{"config":{"configured":false,"on":true,"sunriseoffset":0,"sunsetoffset":0},"etag":"bd95bc37836298ba594e5c450764863c","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":null,"daylight":null,"lastupdated":"none","status":null},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:06:62:03-01"}
And the Sensor is still not reachable.

Any Idea?

**Comment by talun2075** [comment]
hm..don´t understand why is this closed? Where is the template that the bot mean?

**Comment by Mimiix** [comment]
@talun2075 
![image](https://user-images.githubusercontent.com/43333120/102073427-94f76f80-3e03-11eb-877f-b56114432418.png)

You had to select one then follow the template.
