### ISSUE TITLE
Blitzwolf SHP-13 Smart Plug 

### ISSUE THREAD

**Issue by MrSnatz** [dresden-elektronik/deconz-rest-plugin#3910]
Gerät wird mit on /off unterstützt allerdings ist die Ausgabe der Strommessung im Deconz Adapter vom iobroker etwas durcheinander bzw. der aktuelle Verbrauch und Voltage wird nicht angezeigt (Siehe Bilder). 

## Device

- Product name: Blitzwolf SHP-13
- Manufacturer: _TZ3000_gxawfcq
- Model identifier: TS0121
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots

![1](https://user-images.githubusercontent.com/51195705/102074523-3c28d680-3e05-11eb-8ed6-67a2cade44b0.png)
![2](https://user-images.githubusercontent.com/51195705/102074524-3cc16d00-3e05-11eb-9720-bce2e79ebd16.png)
![3](https://user-images.githubusercontent.com/51195705/102074525-3d5a0380-3e05-11eb-9aa0-8933365f3f1b.png)
![4](https://user-images.githubusercontent.com/51195705/102074526-3d5a0380-3e05-11eb-8818-48db41c2d967.png)
![5](https://user-images.githubusercontent.com/51195705/102074529-3e8b3080-3e05-11eb-8c73-ea6cef9aee90.png)
![6](https://user-images.githubusercontent.com/51195705/102074532-3e8b3080-3e05-11eb-8a5b-d1fbfb1eab5c.png)
![7](https://user-images.githubusercontent.com/51195705/102074539-3fbc5d80-3e05-11eb-8c41-c7506364981d.png)
![8](https://user-images.githubusercontent.com/51195705/102074540-4054f400-3e05-11eb-91e5-bbe7b93835ec.png)
![9](https://user-images.githubusercontent.com/51195705/102074542-4054f400-3e05-11eb-96a9-6df34dc060e8.png)

**Comment by Mimiix** [comment]
Device is already supported. You probably lack on the issue with Iobroker atm. It doesn't work with deCONZ versions above .88

Please be adviced to use english.


#closing.
