### ISSUE TITLE
Feibit Smoke Detector SSA01ZB

### ISSUE THREAD

**Issue by bettie82** [dresden-elektronik/deconz-rest-plugin#3923]
## Device

Product name: Smoke Detector SSA01ZB
Manufacturer: Feibit Inc Co.
Model identifier: FNB56-SMF06FB1.6
Device type : Smoke Detector

## Screenshots

![Power configuration](https://user-images.githubusercontent.com/60618854/102242917-df0f4c80-3efa-11eb-9627-599f9bc471b9.PNG)
![Node info](https://user-images.githubusercontent.com/60618854/102242920-dfa7e300-3efa-11eb-867e-20e935feeda7.PNG)
![basic cluster](https://user-images.githubusercontent.com/60618854/102242921-dfa7e300-3efa-11eb-87b5-2badae72bf75.PNG)
![IAS zone](https://user-images.githubusercontent.com/60618854/102242922-e0407980-3efa-11eb-8629-5c335df2c229.PNG)
![Time](https://user-images.githubusercontent.com/60618854/102242924-e0407980-3efa-11eb-8427-1b02ff339c2c.PNG)
![Identify](https://user-images.githubusercontent.com/60618854/102242925-e0d91000-3efa-11eb-8606-064ae84bac36.PNG)

**Comment by SwoopX** [comment]
Supported with version 2.09.00
