### ISSUE TITLE
edp re:dy plug

### ISSUE THREAD

**Issue by vpedromarques** [dresden-elektronik/deconz-rest-plugin#3926]
## Device

- Product name: edp re:dy plug.
- Manufacturer: EDP-WITHUS.
- Model identifier: ZM-SmartPlug-1.0.0.
- Device type : Please remove all unrelated device types. 
  - Other: Smart Plug with Energy Metering
![Screenshot 2020-12-15 at 18 17 02](https://user-images.githubusercontent.com/10771662/102256416-4a5d1c80-3f03-11eb-8ef9-41e673e3205c.png)
![Screenshot 2020-12-15 at 18 17 40](https://user-images.githubusercontent.com/10771662/102256419-4c26e000-3f03-11eb-9c11-016094ad38d3.png)
![Screenshot 2020-12-15 at 18 24 03](https://user-images.githubusercontent.com/10771662/102256420-4cbf7680-3f03-11eb-873d-597d4a63b62d.png)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by vpedromarques** [comment]
![Screenshot 2020-12-15 at 23 35 36](https://user-images.githubusercontent.com/10771662/102285482-4b577380-3f2e-11eb-9951-5d812e8346b9.png)
![Screenshot 2020-12-15 at 23 35 13](https://user-images.githubusercontent.com/10771662/102285487-4c88a080-3f2e-11eb-93e8-470fdf0322fe.png)
![Screenshot 2020-12-15 at 23 34 57](https://user-images.githubusercontent.com/10771662/102285489-4d213700-3f2e-11eb-9e64-939a348e56a7.png)
![Screenshot 2020-12-15 at 23 34 44](https://user-images.githubusercontent.com/10771662/102285490-4d213700-3f2e-11eb-9a9d-0d1d397472a5.png)
![Screenshot 2020-12-15 at 23 34 36](https://user-images.githubusercontent.com/10771662/102285491-4db9cd80-3f2e-11eb-868a-bd45eea9f371.png)
![Screenshot 2020-12-15 at 23 33 56](https://user-images.githubusercontent.com/10771662/102285492-4e526400-3f2e-11eb-8360-712ddcbd4fe6.png)
![Screenshot 2020-12-15 at 23 32 57](https://user-images.githubusercontent.com/10771662/102285493-4e526400-3f2e-11eb-8dcd-a4068116e70f.png)
![Screenshot 2020-12-15 at 23 32 46](https://user-images.githubusercontent.com/10771662/102285495-4eeafa80-3f2e-11eb-90b3-e981c58f60ee.png)
![Screenshot 2020-12-15 at 23 32 02](https://user-images.githubusercontent.com/10771662/102285497-4eeafa80-3f2e-11eb-9100-fc703140950f.png)

**Comment by SwoopX** [comment]
Can you please apply a load where you can anticipate how much it will draw and see what value attribute 0x0400 (Instantaneous demand) of the simple metering cluster is shown? I need to get the measurement unit (although I think it's in W already).

Also, further above in this cluster, attribute 0x0000 (current summation delivered) there's the usual multipliers/Divisors missing would it be more like 3.7 kWh or 0.37 kWh since you've taken it into operation?

**Comment by vpedromarques** [comment]
> Can you please apply a load where you can anticipate how much it will draw and see what value attribute 0x0400 (Instantaneous demand) of the simple metering cluster is shown? I need to get the measurement unit (although I think it's in W already).

Connected a Hue lamp with a consumption of 8w. The reported "Instantaneous demand)" on 0x0400 is 8.

> Also, further above in this cluster, attribute 0x0000 (current summation delivered) there's the usual multipliers/Divisors missing would it be more like 3.7 kWh or 0.37 kWh since you've taken it into operation?

Made a reset to the counter of that attribute 0x0000 to 0 and with the same hue lamp after 10 minutes it turned to 1 so I would guess it's more like 0.01 kWh...
