### ISSUE TITLE
Sonoff SNZB-01 > new model ID

### ISSUE THREAD

**Issue by MadMonkey87** [dresden-elektronik/deconz-rest-plugin#3931]
## Describe the bug
I've tried to add a Sonoff SNZB-01 multiple times which should be supported according to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2990

I can see the connected device in the UI, but not in the api or in the phoscon app.

## Steps to reproduce the behavior
1) go into the phoscon app
2) go to switches, click add and then other
3) press the reset button on the device until the led flashes, click often to keep the device alive

## Expected behavior
 - the device should get a name and be visible trough the api
 
## Screenshots
![image](https://user-images.githubusercontent.com/29612400/102338989-d79c8180-3f94-11eb-9706-323b6f84fe99.png)
![image](https://user-images.githubusercontent.com/29612400/102338289-f0f0fe00-3f93-11eb-930f-af54fef6311e.png)
![image](https://user-images.githubusercontent.com/29612400/102338321-fbab9300-3f93-11eb-9828-ac263075712b.png)
![image](https://user-images.githubusercontent.com/29612400/102338340-0403ce00-3f94-11eb-81d5-8e493fa794d3.png)
![image](https://user-images.githubusercontent.com/29612400/102338352-0bc37280-3f94-11eb-9556-09401f36daa0.png)

## Environment

 - Host system: RPI
 - Running method: Marthoc Docker container
 - Firmware version: 26350500
 - deCONZ version: (2.08.00 
 - Device: ConBee I
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
No bug. Courtesy of Sonoff to have pretty inconsistent model identifiers, we've seen quite some hilarious variants...

**Comment by MadMonkey87** [comment]
Ah I see. For my [Homey integration](https://github.com/madmonkey87/HomeyCONZ) I've already seen that there are a lot of different identifiers for these devices
