### ISSUE TITLE
Sengled Smart Light Switch

### ISSUE THREAD

**Issue by rexbron** [dresden-elektronik/deconz-rest-plugin#3934]
## Device

- Product name: Smart Light Switch
- Manufacturer: sengled
- Model identifier: E1E-G7F
- Device type :
  - Switch

## Screenshots

![Screenshot 2020-12-16 085611](https://user-images.githubusercontent.com/587341/102358580-af555880-3f7d-11eb-8021-5631c2980404.jpg)

![Screenshot 2020-12-16 085310](https://user-images.githubusercontent.com/587341/102358672-c6944600-3f7d-11eb-984c-4aa1afa8384b.jpg)
![Screenshot 2020-12-16 085535](https://user-images.githubusercontent.com/587341/102358674-c6944600-3f7d-11eb-9dbd-547730b66df2.jpg)
![Screenshot 2020-12-16 085708](https://user-images.githubusercontent.com/587341/102358677-c6944600-3f7d-11eb-8322-3bf2c586b66a.jpg)
![Screenshot 2020-12-16 085745](https://user-images.githubusercontent.com/587341/102358679-c72cdc80-3f7d-11eb-818e-01c39c987143.jpg)

**Comment by SwoopX** [comment]
Supported with v2.6.0-beta and duplicate to #3308
