### ISSUE TITLE
Osram Lightify FlexRGBW (Model 73661)

### ISSUE THREAD

**Issue by RichJeanes** [dresden-elektronik/deconz-rest-plugin#3936]
## Device

I have two light strips that were sold as the same product, but appear slightly differently in deCONZ.
- Product name: SYLVANIA Smart+ Adjustable White and Full Color Flex
- Manufacturer: LEDVANCE, OSRAM
- Model identifier: [blank], Osram Lightify FlexRGBW
- Device type :
  - Light

## Screenshots
Device 1:
![image](https://user-images.githubusercontent.com/6753081/102395051-dd479680-3f97-11eb-9102-429b24ba9b35.png)
![image](https://user-images.githubusercontent.com/6753081/102393605-d586f280-3f95-11eb-878b-64634f2b53d1.png)
![image](https://user-images.githubusercontent.com/6753081/102393645-e5063b80-3f95-11eb-9e32-c2f247f79e8f.png)

Device 2:
![image](https://user-images.githubusercontent.com/6753081/102395092-e9cbef00-3f97-11eb-8f97-396cfb72531a.png)
![image](https://user-images.githubusercontent.com/6753081/102393825-1e3eab80-3f96-11eb-802b-214071c3edf6.png)
![image](https://user-images.githubusercontent.com/6753081/102393897-357d9900-3f96-11eb-9552-759acf8dd08b.png)

Currently, the devices appear in Phoscon (via Home Assistant plug-in), but only have color and brightness control. The white LEDs are never used and the Color Temperature controls are disabled. However, in deCONZ, I can set them to Color Temperature mode and the white LEDs do turn on, but I cannot change the color temperature they are set to. If I set them to a color in Phoscon, the Color Mode attribute changes to "Current x and current y". Issuing a Move Color Temperature command will report success, but the light strip will remain at its set color until being turned off (it switches to the white color, then turns off). The white color is retained when powered on again. Even while in Color Temperature mode, I cannot adjust the temperature through deCONZ, with the strip al;ways reporting a temperature of 370.

**Comment by vperez** [comment]
I purchased the same light strip recently, and I'm seeing the same behavior under Phoscon and deCONZ (Docker image). The Phoscon app has the color temperature controls disabled, but using deCONZ I was able to adjust the color temperature manually.

### Screenshots from deCONZ

![image](https://user-images.githubusercontent.com/1428082/102600059-2a7c5300-40d3-11eb-823b-46eb1bf48cef.png)
![image](https://user-images.githubusercontent.com/1428082/102600424-a37baa80-40d3-11eb-8bae-260ca16947ce.png)
![image](https://user-images.githubusercontent.com/1428082/102600578-dc1b8400-40d3-11eb-9e74-527a7fa5041b.png)
![image](https://user-images.githubusercontent.com/1428082/102600628-ec336380-40d3-11eb-9fe9-5436dcd9c214.png)

**Comment by RichJeanes** [comment]
@vperez Your model seems different, being the outdoor model. Mine are not the Outdoor model. My Move Color Temperature command is also different, having Rate, Min, and Max. Though I'm sure it's possible that we're both facing the same issue in the back-end.
![image](https://user-images.githubusercontent.com/6753081/102648945-9edfe200-4125-11eb-8e2f-ff806aad197f.png)

I don't know if this is helpful, but my device does seem to be reporting its Color Temperature capability under ZLL Extensions:
![image](https://user-images.githubusercontent.com/6753081/102649256-16ae0c80-4126-11eb-93dc-2a11946847df.png)

**Comment by vperez** [comment]
@RichJeanes you're right I did not notice that yours are not the outdoor model. I think both devices do have the ability to support changing white color temperature, but they are just not fully recognized at the moment by the Phoscon app.

**Comment by RichJeanes** [comment]
This issue is not stale.
