### ISSUE TITLE
Apex Smart Plug

### ISSUE THREAD

**Issue by bomaskin** [dresden-elektronik/deconz-rest-plugin#3943]
## Device

- Product name: Apex Smart Plug
- Manufacturer: Datek
- Model identifier: PoP
- Device type : 
   - Other: Smart plug with power metering

## Screenshots

![Basic cluster](https://user-images.githubusercontent.com/76155916/102469032-2fe18b00-404a-11eb-9055-8f3b291ed0d8.PNG)

![Node info](https://user-images.githubusercontent.com/76155916/102469153-4ee01d00-404a-11eb-89d9-b7d43a7e4b10.PNG)

![Electrical Measurement](https://user-images.githubusercontent.com/76155916/102469548-cd3cbf00-404a-11eb-8e1a-132746746497.PNG)

![Green power](https://user-images.githubusercontent.com/76155916/102470400-d5e1c500-404b-11eb-894b-516c4878d6c0.PNG)

**Comment by Mimiix** [comment]
@SwoopX This seems to be missing measurement features? Should i add device enhancement?

**Comment by SwoopX** [comment]
(Now) all is there, you can leave the label as it is

**Comment by haarvig** [comment]
I work for Datek who has developed this Smart Plug. Please let me know if you need a full Zigbee cluster dump from the device. I have it in a word document, but can send in any format.

**Comment by SwoopX** [comment]
It would be really awesome if you could share it as PDF. Feel free to also reach out to me on Discord if required/desired.

**Comment by haarvig** [comment]
[mains_power_outlet.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5709674/mains_power_outlet.pdf)
Here it is. We also have other new sensors coming we would like to have supported.

I´m not on Discord for now.

**Comment by Mimiix** [comment]
> Here it is. We also have other new sensors coming we would like to have supported.

Feel free to reach out trough Discord :) Would love to have you around for user questions and integrations.
