### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by syswombat** [dresden-elektronik/deconz-rest-plugin#3947]
## Device

System: Raspberry Pi 4 Model B Rev 1.1
with a RaspBee II
Distro: Raspbian GNU/Linux 10 (buster)
Host system: (Raspberry Pi)
Running method: (Raspbian)
Firmware version: (26610700)
deCONZ version: (2.07.01 / 14.9.2020)
Device: (RaspBee II)
- Device type : Please remove all unrelated device types.
 
 i Just wonder if the Lidl LED Lamp are added to your system
Lidl.ch LED-Lampe 16 Millionen Farben ZigBee3.0

The Problem is i can't change the color or not all color there are also strange behavior when changing dimming. 

if there should be OK - i will have to Dig deeper into Node Red to find the Problem

**Comment by Mimiix** [comment]
Closing as you are using the wrong template.

Please use a User question template.
