### ISSUE TITLE
Enable selection of interface for deconz network communication

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#3948]
## Feature request type
Enhance deconz by the ability to choose the network interface by which the traffic should be send over. This should explicitly include the loopback interface.

## Description
By default, deconz listens on all available interfaces. From an access restriction point of view, this is not beneficial, especially not if you want to isolate the system and allow/enable only internal services. Currently, to enforce restrictions, it is required to set up/configure a firewall to block all unwanted traffic. While this may have a neglectible performance impact on powerful machines, it becomes more considerable on weaker systems.
By preselecting the interface(s), this situation could be nailed down. Additionally, by restricting access by loopback only, more advanced users could ensure all traffic will pass through a reverse proxy, force stronger authentication and levarage https if available.

## Considered alternatives
Blocking all traffic from unwanted interfaces via firewall, but that requires an additional component come into play, additional administrative efforts and applies additional system load (being especially notable on weak systems).

## Additional context
Selection of interfaces (all, lo, ifX, ifY, ifZ) should ideally be feasible from command line, deconz GUI and via REST API.

**Comment by carver7** [comment]
I'd like to see this too, please. Having unprotected devices on a LAN is getting more risky with time, as East-West style attacks are becoming more and more common, and the concept of a network perimeter firewall sufficiently being able to guard a vulnerable "trusted network" with devices communicating to each other with no encryption is simply becoming less and less effective over time. That applies at home and in the corporate world's on-premises ￼intranets.

A rest api over https really would protect your customers a lot down the road￼, and allowing for the enabling the restrictions described by the op here￼, would at least allow some people to figure out the reverse proxy approach￼.

Thank you for consideration.

**Comment by manup** [comment]
I think that works now :)
