### ISSUE TITLE
Device name MS-104Z 1 Gang 2 Way Zigbee Switch 3.0 Moes

### ISSUE THREAD

**Issue by testpaul999** [dresden-elektronik/deconz-rest-plugin#3967]
## Device

- Product name: The device name as shown on the product or package.
MS-104Z
- Manufacturer: As per deCONZ GUI Basic cluster.
Moes
- Model identifier: As per deCONZ GUI Basic cluster.
Switch Module 
- Device type : Please remove all unrelated device types. 
  - Switch
 

## Screenshots

![IMG_2300](https://user-images.githubusercontent.com/35597907/102690342-09b41a80-4205-11eb-8ab6-d3a4097b5036.jpeg)
![IMG_2301](https://user-images.githubusercontent.com/35597907/102690347-0b7dde00-4205-11eb-9bb6-b8e4bbf805f4.jpeg)
![IMG_2302](https://user-images.githubusercontent.com/35597907/102690349-0de03800-4205-11eb-93de-eb2437d7b2f3.jpeg)

**Comment by Smanar** [comment]
Lol, by capture, it s deconz capture we need ^^
But this device is already suported no ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3595

**Comment by testpaul999** [comment]
Ok, thx try once more to connect.
