### ISSUE TITLE
KlikaanKlikUit smoke detector 

### ISSUE THREAD

**Issue by JMBokhorst** [dresden-elektronik/deconz-rest-plugin#3970]
Hello,

I recently bought a KlikAanKlikUit smoke detector ([link to device](https://klikaanklikuit.nl/product/slimme-draadloze-rookmelder/)). Which I think is a rebrand of the Heiman HS1SA smoke sensor. 

I could pair the device and it is picked up by deconz as a Heiman smoke sensor. The issue I have is that it is _not reachable_ directly after pairing. I tried to pair the device again with the same outcome. I tried to test the device by running it in test-mode but I don't get an update/notification via deconz. 

If I check the device via the GUI, I do see it is connected but I don't see a lot of information. 

Does somebody has experience with this device? Or can somebody help me getting it to work correctly? 

## Screenshots
<img width="653" alt="Screenshot 2020-12-19 at 15 18 56" src="https://user-images.githubusercontent.com/21331645/102691682-8b5c7600-420e-11eb-8ffb-4ff2f56d63ee.png">
<img width="1280" alt="Screenshot 2020-12-19 at 15 21 43" src="https://user-images.githubusercontent.com/21331645/102691684-8e576680-420e-11eb-8c19-c4ffbb04f1b4.png">
<img width="301" alt="Screenshot 2020-12-19 at 15 22 32" src="https://user-images.githubusercontent.com/21331645/102691687-90b9c080-420e-11eb-8f8b-f2b85b4f6316.png">
<img width="213" alt="Screenshot 2020-12-19 at 15 22 45" src="https://user-images.githubusercontent.com/21331645/102691688-931c1a80-420e-11eb-8aa2-fd03f439e5b0.png">
<img width="373" alt="Screenshot 2020-12-19 at 15 23 28" src="https://user-images.githubusercontent.com/21331645/102691691-96170b00-420e-11eb-986b-b39ac7d24548.png">

## Environment

 - Host system: PC
 - Running method: Marthoc Docker container 
 - Firmware version: (26807000)
 - deCONZ version: (2.07.01)
 - Device: ConBee II
 - Do you use an USB extension cable: No
 - Is there any other USB or serial devices connected to the host system? If so: Which? Yes, a DSMR slimmer meter cable (RJ-11 to USB). 

Hope you guys can help me

**Comment by SwoopX** [comment]
What are the values of the IAS Zone cluster? Scroll down and click on read, make sure the device is awake by pushing it's physical button.

**Comment by JMBokhorst** [comment]
Sorry for my ignorance, but I'm not sure where I should scroll down and click on read. I assume the in the tab 'cluster info', there is a read button but it doesn't seem to update the values (even though I selected the smoke detector node):

<img width="316" alt="Screenshot 2021-01-17 at 22 07 46" src="https://user-images.githubusercontent.com/21331645/104856066-94755b80-5910-11eb-90bb-2e729c56062c.png">

**Comment by SwoopX** [comment]
The screenshot is not from the IAS zone cluster. However, that's the button also available there.

As said, you need to wake the device prior to pressing read. You do that by pushing the physical button one or twice (like you would do for a reset, just not that long).

**Comment by JMBokhorst** [comment]
With the devices woken, I see this as information below the IAS zone info. Not sure if this is what you mean, I cannot click on it and press read (might be the VNC viewer). 

![20210117_222626](https://user-images.githubusercontent.com/21331645/104856492-4877e600-5913-11eb-9150-3df5ca6c2293.jpg)

**Comment by JMBokhorst** [comment]
I think I have found it (let me know if this isn't it) 

<img width="334" alt="Screenshot 2021-01-17 at 22 32 07" src="https://user-images.githubusercontent.com/21331645/104856599-e7044700-5913-11eb-889f-bcd7cef21bf0.png">
<img width="324" alt="Screenshot 2021-01-17 at 22 32 14" src="https://user-images.githubusercontent.com/21331645/104856602-e8ce0a80-5913-11eb-998d-3cae6147023b.png">

**Comment by SwoopX** [comment]
You need to enroll it manually (an improvement for this has just been merged):

1. Open deCONZ.
2. Select the Coordinator (blue node) on the map and copy value of the IEEE field.
3. Select the Motionsensor, click the "ias zone" cluster. 
4. Scroll down to the attributes list to attribute 0x0010
5. double click the "value"
6. put the IEEE value you copied earlier in the textbox above. 
7. Make sure the Sensor is awake. This can be done by clicking the reset button once.
8. Click "Write"

**Comment by JMBokhorst** [comment]
I will try that now and will report my findings, thanks!

**Comment by JMBokhorst** [comment]
I have added the IEEE field to the sensor. And now it seems to be set, but it still is unavailable.

**Comment by SwoopX** [comment]
Has the zone state (0x0000 in your last screenshot) changed to enrolled?

**Comment by JMBokhorst** [comment]
No, it's still on 'Not enrolled' 

![Screenshot 2021-01-18 at 10 38 28](https://user-images.githubusercontent.com/21331645/104897936-4ea0ad80-5979-11eb-9f4f-6b291ba4e198.png)

**Comment by SwoopX** [comment]
Hm, that's still odd. Could you update to 2.09.01 once it is available for docker and then re-pair the device? It has some overhauled code taking care of the automatic enrollement and making it more robust.

**Comment by JMBokhorst** [comment]
After updating the node is indeed enrolled, however in the webGUI it still says "Not reachable". Can it be that the did a bit more than just rebrand the device? 

<img width="242" alt="Screenshot 2021-01-18 at 12 24 12" src="https://user-images.githubusercontent.com/21331645/104909463-2e2c1f80-5988-11eb-9fa8-43c0d33833f2.png">
<img width="303" alt="Screenshot 2021-01-18 at 12 24 47" src="https://user-images.githubusercontent.com/21331645/104909455-2bc9c580-5988-11eb-9807-aaa61b9b803f.png">

**Comment by SwoopX** [comment]
Could you share the details from the basic cluster please? I'd particularly interested in the model identifier and manufacturer name to double check the code.

**Comment by JMBokhorst** [comment]
Of course, please find attached the information: 

![Screenshot 2021-01-18 at 13 00 40](https://user-images.githubusercontent.com/21331645/104912971-45b9d700-598d-11eb-8592-9a37addfcf8b.png)

**Comment by SwoopX** [comment]
> Although the information says it's a heiman sensor, the brand on the box is KlikAanKlikUit.

That's not really important here. Code-wise, it looks fine. Could you also share how the device looks like in the REST API?

**Comment by JMBokhorst** [comment]
Using a GET with the REST API might have triggered something(?). Now it seems to be reachable: 

![Screenshot 2021-01-18 at 13 38 41](https://user-images.githubusercontent.com/21331645/104916521-7bad8a00-5992-11eb-9549-a65a497f2674.png)

Thanks for the help! =D

**Comment by JMBokhorst** [comment]
The sensors is working fine since I have updated to version `2.09.01` and manually set the `ias zone`. Therefore I will close this issue.

**Comment by SwoopX** [comment]
Just FYI: with 2.09.01, the enrollment became way more robust and it shouldn't happen again that a device doesn't get enrolled automatically ;)

Great it works now 👍

**Comment by JMBokhorst** [comment]
Super! Thanks for the help :)

**Comment by Gunthervc** [comment]
> The sensors is working fine since I have updated to version `2.09.01` and manually set the `ias zone`. Therefore I will close this issue.

Hi, how did you do this update? i have same issue with Heiman version 2019.8.29
