### ISSUE TITLE
ORVIBO Zigbee Dry Contact CM10ZW support

### ISSUE THREAD

**Issue by samsam-rolon** [dresden-elektronik/deconz-rest-plugin#3973]
Quote [#3879](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3879)
## Device

- Product name: ORVIBO - Module commutateur contact sec Zigbee.
- Manufacturer: ORVIBO 
- Model identifier: CM10ZW
- Device type : 
  - Door Lock

Be careful : the device is configured in the "dry contact mode" but they have 3 mode available with a physical switch on the device :
![image](https://user-images.githubusercontent.com/25209236/102700256-11e37880-424c-11eb-8dda-66b05ded7c2b.png)
file:///C:/Users/Samuel/AppData/Local/Temp/Module-commutateur-contact-sec-CM10ZW-1.pdf
## Screenshots

![Orvibo_1](https://user-images.githubusercontent.com/25209236/102700215-d34dbe00-424b-11eb-8ab6-ec88416f4e45.PNG)
![Orvibo_2](https://user-images.githubusercontent.com/25209236/102700216-d47eeb00-424b-11eb-93f8-4dbd3289ce29.PNG)
![Orvibo_3](https://user-images.githubusercontent.com/25209236/102700220-d5b01800-424b-11eb-90b1-00dc01f6adec.PNG)
![Orvibo_4](https://user-images.githubusercontent.com/25209236/102700225-d8ab0880-424b-11eb-9bf1-1ed426eb446c.PNG)
![Orvibo_5](https://user-images.githubusercontent.com/25209236/102700227-da74cc00-424b-11eb-9586-025074a9d222.PNG)
![Orvibo_6](https://user-images.githubusercontent.com/25209236/102700229-dba5f900-424b-11eb-8c08-631a0c6d7a79.PNG)

**Comment by Smanar** [comment]
Hello, but you miss something ?
This device don't work natively ?

**Comment by samsam-rolon** [comment]
Hum ... no. I didn't see it in API

**Comment by Smanar** [comment]
Ha ?
This device is detected as doorlocker, need to check because with the cluster 0x0006 you need to have a light entry.

**Comment by Smanar** [comment]
I have made something to correct name and make the device visible in api
On the same code than for the temperature device

```
git clone --branch orvibo https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by samsam-rolon** [comment]
![image](https://user-images.githubusercontent.com/25209236/102792427-cabeca00-43a8-11eb-9a07-5abf4307ed0f.png)
Some KO related to a missing `;` line 2213 just before the case (on the break 1 line over)
I've corrected it but the GUI still not showing me a friendly name ; neither the API
![image](https://user-images.githubusercontent.com/25209236/102793564-67359c00-43aa-11eb-8f31-5872cf1cc862.png)

**Comment by samsam-rolon** [comment]
Okay, better now :
I see it in the API under lights now. It's okay to change states with API now 
`
  "10": {
    "etag": "8d805b9e009a3651c7d94a84a9bae608",
    "hascolor": false,
    "lastannounced": "2020-12-21T15:54:12Z",
    "lastseen": "2020-12-21T15:54Z",
    "manufacturername": "Unknown",
    "modelid": null,
    "name": "Unknown 10",
    "state": {
      "alert": "none",
      "on": false,
      "reachable": true
    },
    "swversion": null,
    "type": "Unknown",
    "uniqueid": "00:12:4b:00:22:31:80:70-01"
  },
 "22": {
    "etag": "0dd7696faf61ac6c30666afe1fbd510e",
    "hascolor": false,
    "lastannounced": "2020-12-21T15:54:12Z",
    "lastseen": "2020-12-21T15:53Z",
    "manufacturername": "Unknown",
    "modelid": null,
    "name": "Unknown 22",
    "state": {
      "alert": "none",
      "on": false,
      "reachable": true
    },
    "swversion": null,
    "type": "Unknown",
    "uniqueid": "00:12:4b:00:22:31:80:70-02"
  },
  "23": {
    "etag": "32d8c61ae7ef49768db4209135fbd762",
    "hascolor": false,
    "lastannounced": "2020-12-21T15:54:12Z",
    "lastseen": "2020-12-21T15:54Z",
    "manufacturername": "Unknown",
    "modelid": null,
    "name": "Unknown 23",
    "state": {
      "alert": "none",
      "on": false,
      "reachable": true
    },
    "swversion": null,
    "type": "Unknown",
    "uniqueid": "00:12:4b:00:22:31:80:70-03"
  },
`

**Comment by Smanar** [comment]
Thx, I have corrected the code, and have added something to have a type instead of "unknow"
But I don't understand why you have no model id and no manufacture name ? It same after a reboot ?

**Comment by samsam-rolon** [comment]
> 
> 
> Thx, I have corrected the code, and have added something to have a type instead of "unknow"
> But I don't understand why you have no model id and no manufacture name ? It same after a reboot ?
> 
> And why 3 endpoint ? you have only 1 output ?

I've try to unpair and repair it to join the Zigbee network and same issue : unknow
There is 3 endpoint because I have 3 dry contact relay available on the device

**Comment by Smanar** [comment]
Ok.
Have corrected a typo in the name, but it don't explain why you don't have model id or manufacture name ....

**Comment by nicph** [comment]
Same situation as in the issue here. Is there any progress on the dry contact mode of the CM10ZW ? Can we do something to help ?

**Comment by Smanar** [comment]
@nicph you are using the recompiled code ?

**Comment by nicph** [comment]
No, i did not find the branch mentionned above on this repo, but i just noticed it was on a fork. I'll try

**Comment by nicph** [comment]
Ok I recompiled the plugin and now I can reach the 3 entities from the API, thank you. Is there any plan to merge this here ?

**Comment by Smanar** [comment]
Yep, I will make the PR today, but there is still something strange, the missing model id for exemple.
You have it on the JSON on your side ?

**Comment by nicph** [comment]
Great news !

No, i have `"modelid": null,` for the 3 endpoints.

**Comment by samsam-rolon** [comment]
Same issue on my side :
``` json
{
  "etag": "788c35fb76a9f1ca4381f40f8b099bd5",
  "hascolor": false,
  "lastannounced": "2021-01-10T12:06:49Z",
  "lastseen": "2021-01-10T12:08Z",
  "manufacturername": "Unknown",
  "modelid": null,
  "name": "Door Lock Unit 22",
  "state": {
    "alert": "none",
    "on": false,
    "reachable": true
  },
  "swversion": null,
  "type": "Door Lock Unit",
  "uniqueid": "00:12:4b:00:22:31:80:70-01"
},
{
  "etag": "8c48f6a3e1cc1f9d956bf7c6747c62c5",
  "hascolor": false,
  "lastannounced": "2021-01-10T12:32:31Z",
  "lastseen": "2021-01-10T12:38Z",
  "manufacturername": "Unknown",
  "modelid": null,
  "name": "Door Lock Unit 23",
  "state": {
    "alert": "none",
    "on": false,
    "reachable": true
  },
  "swversion": null,
  "type": "Door Lock Unit",
  "uniqueid": "00:12:4b:00:22:31:80:70-02"
},
{
  "etag": "352d6926639e25e1f2b1ff7196b9bc58",
  "hascolor": false,
  "lastannounced": "2021-01-10T12:39:11Z",
  "lastseen": "2021-01-10T12:38Z",
  "manufacturername": "Unknown",
  "modelid": null,
  "name": "Door Lock Unit 24",
  "state": {
    "alert": "none",
    "on": false,
    "reachable": true
  },
  "swversion": null,
  "type": "Door Lock Unit",
  "uniqueid": "00:12:4b:00:22:31:80:70-03"
}
``` 
![image](https://user-images.githubusercontent.com/25209236/104123083-4927df80-5349-11eb-96b4-97f873bd0652.png)
![image](https://user-images.githubusercontent.com/25209236/104123087-4e852a00-5349-11eb-96c2-40ddbeaef547.png)
![image](https://user-images.githubusercontent.com/25209236/104123098-5e9d0980-5349-11eb-949c-50f45a5a3f00.png)

**Comment by Smanar** [comment]
It s realy strange, someone can share the log (info / info_l2) during the inclusion ?

**Comment by samsam-rolon** [comment]
Sorry, why ?

**Comment by samsam-rolon** [comment]
@Smanar I didn't have it. 
I need to re-include ... Sorry, why ?

**Comment by Smanar** [comment]
Not realy important, just because I don't understand why manufacture and model id are not working.
And more important, just to be sure deconz is not spamming requests to retreive them. For that, you can just take a look on deconz / help / log if you have the desktop.

**Comment by samsam-rolon** [comment]
Stupid question :
Is any way to let works the "delay" part ?
I would like to configure it as a "1 push and relase button" for my garage door 😄 
![image](https://user-images.githubusercontent.com/25209236/104284910-1b5eaa00-54b3-11eb-918a-eec171881de4.png)

**Comment by Smanar** [comment]
Perhaps here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3394
It seem there is an hiden command "on with delay"

**Comment by samsam-rolon** [comment]
With the GUI, the "On time" or "Off wait time" is not working

**Comment by Smanar** [comment]
Ha ok, ok so look at the error message, but it s probably because the device don't support it.

**Comment by nicph** [comment]
> It s realy strange, someone can share the log (info / info_l2) during the inclusion ?

Attached [here](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5811848/orvibo.log)

**Comment by Smanar** [comment]
Thx @nicph but it s worse now ^^

The device is managed like tuya one (because of the manufacture number = 0x0000) so the API search a manufacture name in the database, and find it
>00:48:27:684 DB SELECT manufacturername FROM nodes WHERE mac LIKE '00:12:4b:00:22:02:89:5a%' COLLATE NOCASE: ORVIBO

So the code set it, from the start. So why you loose it during the inclusion ...

You have not waht happen after ? The device was not yet included on your logs.

**Comment by nicph** [comment]
> Thx @nicph but it s worse now ^^

This may be related to the fact I'm not using the patched version anymore ? Because the docker container restarted at some time.

**Comment by nicph** [comment]
@Smanar i had the opportunity to reset my setup, here are the logs with the patched version active
[deconz-0201-orvibo.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5909482/deconz-0201-orvibo.log)

**Comment by Smanar** [comment]
Ok, so now it s working like the samsam-rolon one.
The code ask for model id, but It never have godd response, realy strange.
It seem the task is created, and immediatly erased ....
```
22:33:49:882 read attributes of 0x00124B002202895a cluster: 0x0000: [
22:33:49:886 0x0004
22:33:49:888 ]
22:33:49:891 add task 6500 type 19 to 0x00124B002202895a cluster 0x0000 req.id 103
22:33:50:145 Erase task req-id: 103, type: 19 zcl seqno: 139 send time 0, profileId: 0x0104, clusterId: 0x0000
```

And BTW why you have 3 endpoint ?

**Comment by nicph** [comment]
> And BTW why you have 3 endpoint ?

That's because the device has 3 distinct relays

**Comment by Smanar** [comment]
BTW the manufacture name and the model id is still missing ?
I need to correct that for the PR will be validated.

**Comment by samsam-rolon** [comment]
Yes it's working for me only after re-inclusion

**Comment by Smanar** [comment]
Ha ? ^^ seriously ? you have a complete json now ?
Can you share it pls ?

**Comment by Smanar** [comment]
@samsam-rolon we are waiting for the JSON to validate the PR.
Of if you have the values gived by your third app ? just need the model ID and the manufacture name.

**Comment by samsam-rolon** [comment]
euhm, sorry, I didn't understand what you are waiting for ? I was thinking all was complete for the PR !

**Comment by Smanar** [comment]
Yes, but manup don't want tp merge the PR, if you still have empty value.
And I want to check if the convertion have worked, I m trying to set my own model id, instead of the magic string on the firmware a7z7z4d44ze74z41s5qsz1s1x41d5c.

So I just need thoses 2 values.

**Comment by herveja** [comment]
Hi Smanar,
I'm bit a beginer here, but if I could help, here is what my json look like for the ORVIBO dry contact CM10ZW
I'm waiting for the merge to see how it goes in HA. For now it's not realy usefull :)

 "7": {
        "etag": "9fb62ad1e409eaa37dac6e05a0e4de9b",
        "hascolor": false,
        "lastannounced": "2021-02-22T17:47:59Z",
        "lastseen": "2021-02-22T17:47Z",
        "manufacturername": "ORVIBO",
        "modelid": "82c167c95ed746cdbd21d6817f72c593",
        "name": "Window covering controller 7",
        "state": {
            "bri": 0,
            "lift": 0,
            "on": false,
            "open": false,
            "reachable": false
        },
        "swversion": "v3.1.06",
        "type": "Window covering controller",
        "uniqueid": "00:12:4b:00:22:31:80:5a-01"
    }

**Comment by Smanar** [comment]
Nice Thx a lot, have made a typo

>"modelid": "82c167c95ed746cdbd21d6817f72c593",

And I m using 

>else if (str == QLatin1String("82c167c95ed756cdbd21d6817f72c593"))

I have updated the code, but no need to retest it, I think it will be enought for manup. The code will be probably merged in the next week version.

**Comment by samsam-rolon** [comment]
> "modelid": "82c167c95ed746cdbd21d6817f72c593",

Yead I Confirm this model ID

**Comment by samsam-rolon** [comment]
Is any one get some issues with this devices ? Like not responding ... :(

**Comment by Smanar** [comment]
I haven't the device, but it s strange, it s a router.
Something special visible in deconz GUI or in log ?

**Comment by samsam-rolon** [comment]
It's a router device, yeah ! Sometimes in GUI led is flashing RED instead of Green/Blue
Nothing in logs ... but i'm running it with those options : 
```
environment:
      - DECONZ_WEB_PORT=38080
      - DECONZ_WS_PORT=38081
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=35900
      - DECONZ_VNC_PASSWORD=HIDE
      - DECONZ_UPNP=1
      - DECONZ_DEVICE=/dev/ttyACM0
```

**Comment by samsam-rolon** [comment]
Also, I have a CC2530 + CC2591 for extending zigbee range to this area

**Comment by Smanar** [comment]
Can be a range issue ?
Mesh issue ?

You can try to set other value for reporting (will work up to deconz change them again)

**Comment by samsam-rolon** [comment]
> 
> 
> Can be a range issue ?
> Mesh issue ?
> 
IDK : the device is well connected to my extender router so in theory no
![image](https://user-images.githubusercontent.com/25209236/115605825-4a22c280-a2e3-11eb-8192-5cfa59a1f5a0.png)


> You can try to set other value for reporting (will work up to deconz change them again)

Any advices ?

**Comment by Smanar** [comment]
Not me, and as nothing appear in logs ...
The connexion look good on deconz, but it s just an indication. I think your garage door is in metal ? I have ever see some issues about sensor sensible to metal support ?

**Comment by samsam-rolon** [comment]
Yes my garage door is in metal but the extender and the dry contact are not near the door but on the shortest path "on the fly" to receive good signal ...

**Comment by samsam-rolon** [comment]
I will analyse log with debug options after 1 week

**Comment by 0rsa** [comment]
Hello,
I just received my CM10ZW support and I'm back to the initial problem.
I can see an unknown device in deconz GUI and there is no entry in the API.
Cluster basic info is a bit different from author:
![orbivo](https://user-images.githubusercontent.com/769750/154977640-f53e39ac-723a-4da3-96f2-e1c747dc4dc3.png)
![orbivo2](https://user-images.githubusercontent.com/769750/154977922-d4511431-46db-4df9-89bc-a4585c2e5c67.png)

**Comment by Smanar** [comment]
Different model id mean different device for deconz.
But I have take a look faslty on code, there is nothing special for this device, I think you can use it with DDF.

Do you know what is DDF ? https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
You just need to drag and drop 3 "On/Off plug-in unit" with the good endpoint.

**Comment by 0rsa** [comment]
Thank you @Smanar, your help is really appreciated.
I successfully edited DDF to map a On/Off light with good endpoints.
It is working but I'm disappointed by the module behaviour itself, I mean you have to toggle on to activate dry contact and you have to toggle off to "open" dry contact. There is no security, the module can keep the contact dry forever.

I will stay with my Tuya dry contact which has a dry contact which automatically deactivates after a few hundred ms even if it not officially supported #5685

**Comment by mc4one** [comment]
Hi Guys,

I have a issue like some people there, but I don't understand all :/ I'm french, maybe my english is too bad :D 

I'm on Home Assistant, using Conbee2 and the add-on Deconz.

I tried several times to reset the modul (4 press 5 press long) but when I start a discorey (light or switch) nothing was detected. But on Deconz I see a node with number. In the parameter I see that it's the Orvibo.
For now I have nothing plug into (like my garage door to make a try).
On Home assistant I have aapparel "no name" with no entities.

Like you see here, and l ike some people, manufacturer and model identifiier are empty :

![Capture](https://user-images.githubusercontent.com/83140238/163571673-dae94c7d-153e-417a-b741-e4df92a1445d.PNG)

But on the node I see Door lock Controller :

![2](https://user-images.githubusercontent.com/83140238/163571745-30599cbb-11f8-4c5e-a516-66456b538c54.PNG)

And If I check on "Basic" and "cluster info" I see the name and model identifer...

![3](https://user-images.githubusercontent.com/83140238/163571806-39c82248-0579-4040-8eb3-be64718bfb7c.PNG)

Any idea to help me ? Thank you :)

**Comment by Smanar** [comment]
So I have a bad new and a good new.

You have a new device, nothing to see with the one from this issue (not same model id, not same manufacture number), so natively It will be never detected.

So same answer than here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3973#issuecomment-1047104875
And like @0rsa haven't share his DDF, need to start from scratch.

But don't worry it s fast and easy for this kind of device, you have a video on the link, but he have give some information on the second post.

If it don't work, can you share the DDF you have to correct it.

**Comment by mc4one** [comment]
Thank's @Smanar for your help.

I succeeded something :)

Now I have the Manufacturer and model identifier.
Just one of the 3 dry contact are visible on the light device like switch. And I have 1/3 entitie visible.

I think I forget something on the DDF.

Here my DDF preview (sorry copy past doesn't work :/) : 
![ddf1](https://user-images.githubusercontent.com/83140238/163634209-fb579f6f-dd60-41b8-b6d6-751607198621.PNG)
![ddf2](https://user-images.githubusercontent.com/83140238/163634217-24af906a-d396-40b0-814d-7caef1b955c3.PNG)
![ddf3](https://user-images.githubusercontent.com/83140238/163634229-e1a1771f-91c2-45c9-8a2a-7fc5c3b186dc.PNG)

This screen shot is what I drag and Drop : 

![ddf4](https://user-images.githubusercontent.com/83140238/163634447-450fdbbe-f3b1-4fff-88a1-50bb1eefe2a2.PNG)

**Comment by Smanar** [comment]
>I think I made a mistake about the endpoint. I don't really undestand what I need to do.

Yep exaclty, on your DDF you are creating 3 device, but all with the same uniqueID (uuid) it's based on $adress.ext and the endpoint.

So just use 0x01 0x02 and 0x03

If it don't work after that can be conflict, so we will use the value instead of "auto" on some endpoint field.
And the device will probably work but you will not have return, will be normal, still missing binding/report. Not realy usefull on this kind of device, there is is no manual action possible, but can be usefull if for exemple you restart deconz.

**Comment by mc4one** [comment]
I make a try yesterday before your message. But not in the right place :D 

Now I think it's good :)
![ddf1](https://user-images.githubusercontent.com/83140238/163674100-05e34955-a0ba-4b1f-afe7-072943267063.PNG)

And to show for other users where to change the value : 
![ddf2](https://user-images.githubusercontent.com/83140238/163674112-714612cf-52aa-425e-860f-0c1bec96d864.PNG)

And on Haas I have 3 entities on the device : 
![ddf3](https://user-images.githubusercontent.com/83140238/163674381-ae185a93-ddf5-4978-8eee-2cab28314356.PNG)

@Smanar can I change the name of the product ? Just to have something clear ?
![ddf4](https://user-images.githubusercontent.com/83140238/163674402-3329ce15-5949-419f-ab5a-ce6f26992651.PNG)

And my last question (I hope :D) Where can I configure a quick on/off to have a good dry contact for my garage door.

**Comment by Smanar** [comment]
>can I change the name of the product ? Just to have something clear ?

Yeah and it s a good idea, you just need to keep the "long number" for the model ID.

>Where can I configure a quick on/off to have a good dry contact for my garage door.

Will be in the request you make you need to send for exemple to the /state the body `{"on": true, "ontime": 3}`

You are using it without binding/report ?

**Comment by mc4one** [comment]
> Will be in the request you make you need to send for exemple to the /state the body `{"on": true, "ontime": 3}`
> 
> You are using it without binding/report ?

I don't find the right way to modify the /state  :(
And, I don't know what is binding/report. I have something with "binding" on DDF but nothing on it and I can't do anything.

**Comment by Smanar** [comment]
I don't use HA, so I think it s better to ask on the plugin support if there is a way to use the "ontime" parameter. It's used generaly for bulb.
Will be more robust than using an automation, but yes using automation works too.

>I just see somethinh, @0rsa using "On/Off light" and me using "On/Off plug-in unit". Which is the better ?

Not a big change on the result, but "On/Off light" is generaly for light and "On/Off plug-in unit" for plug. Your device have the type "Door lock controller", this type is not yet in the DDF core (I will make a PR in 10mn). It s possible the parameter "ontime" is only used for a type and not another on HA, but I can't test on my side.

BTW, you have no way to share the DDF as copy paste don't work ? Can't save it in a "shared folder". I can try to make it with a test editor, but easy to make typo error.

**Comment by mc4one** [comment]
It's very difficult, I can't save the file in a other place than the purpose of Deconz :/

And by the way, I finally understand with your link the possibility to drag and drop on Binding section. But... I can't do this. Home assistant use VNC to control Deconz and when I switch between the Zigbee mapping and DDF it's a new window. I can't reduc them and make a drag & drop.

It's never simple...

**Comment by Smanar** [comment]
Lol nope ^^, on docker, never (It's only "easier" if you don't need to touch something)
Perhaps this can help you https://forum.phoscon.de/t/ddf-editor-how-to-drag-bindings/1351

**Comment by mc4one** [comment]
You know what ? I'm disapointing, You have the answer for all :D 

Now it's ok, i have this :) 
![ddf5](https://user-images.githubusercontent.com/83140238/164788951-8c36c824-41bc-41b1-ac21-3707a4aacb35.PNG)

**Comment by Smanar** [comment]
Nice, try to set as setting. min = 1, max = 300. It's the defaut values used for classic device using the cluster 0x0006.
I think it will be fine after a save file and a "hot reload".

**Comment by mc4one** [comment]
I do what you said but nothing.

When I'm using the button on/off for this entitie, I need to click again to have OFF. It's not like a short press :/

In the same time what does this number mean ? 1 is for one second ?

**Comment by Smanar** [comment]
yes 1 is for one second.
I have perhaps find the issue, the endpoint, the device have 3 endpoints (01 02 03), so you will have reportinf only for one of them.
If I m right the device use 1 endpoint by contacts ?

**Comment by mc4one** [comment]
Yep exactly. 3 entities for each contact dry :)

**Comment by Smanar** [comment]
As you have switch.on_off_plug_in_unit_20 switch.on_off_plug_in_unit_22 switch.on_off_plug_in_unit_23, I suppose the switch.on_off_plug_in_unit_20 is te one with the unique id finish by -01 ?

Can make binding for third endpoint, but I don't remember why it's a problem, this device don't have manual mode ? So we don't realy need return ?

**Comment by mc4one** [comment]
Yes it is.

No, I have nothing manual on the device.
If I understand your question, I need a return to have the quick on/off. If I click on the button, he stay on "on" and I need to click again to have "off". But, I can try to plug a light on it and see if he really stay on "on".
With a automation, the button quick pass from on to off and I heard clac clac.

**Comment by mc4one** [comment]
No problem @Smanar, you have already helped me a lot :)

Now I just need to wait a futur integration from Deconz for this device :/

So for moment I will use a automation.

**Comment by mc4one** [comment]
Yes of course,

The UniqueID : 
396483ce8b3f4e0d8e9d79079a35a420

And in yellow the things who are not the exactly the same : 
![2704-1](https://user-images.githubusercontent.com/83140238/165404661-fb37938b-1a22-4314-a2ed-0b0070ec4a2a.PNG)
![2704-2](https://user-images.githubusercontent.com/83140238/165404673-3518842a-8526-43c0-8a07-38294fc29033.PNG)

**Comment by mc4one** [comment]
No problem don't worry :D 

I don't understand, you updated the DDF but where do you have modify it ?

I don't know what "state/alert" is :/

After, i don't know if it's good or not :/ 

But @Smanar who are you ? are you working for Deconz ? you know so many things :D

**Comment by Smanar** [comment]
>I don't understand, you updated the DDF but where do you have modify it ?

Have updated the model id.
For product better to use a better device dscription than just "ORVIBO"
And I don't think we need the state/alert, some device have "special effect" like blinking, that can be used with this field, but on a switch module ....

Have make a PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5985 for the device will be included in the future, just need to wait for the PR will be validated, you can edit it too.

>who are you ? are you working for Deconz ? you know so many things :D

No ^^, I m like you, There is realy few worker from deconz, I know some thing because there is so long time I m using it. Zigbee world is interesting, and deconz permit so much thing without being an enginer, if you have lot of time to spend :)

>After, i don't know if it's good or not :/

No way to be sure, I don't know a way to put/edit a DDF file on HA ...

**Comment by Smanar** [comment]
Was just valided by manup, men you will have it in next version.

**Comment by mc4one** [comment]
So, when I will update Duconz it will be automatic ? Or I will need to delete node and repairing ?

**Comment by Smanar** [comment]
Depend of the place you have installed your DDF.
But in the worse case, just delete your DDF and restart deconz, no need to include the device again.

**Comment by mc4one** [comment]
I never change the location from my DDF. It's like deconz install it :)

At this moment nothing change. DDF is always empty even after a reboot  Deconz and even with a unpairing and repainring.

Still wait :)

**Comment by Smanar** [comment]
There is 2 "devices" folder in the "deconz install stuff"
One is for deconz and will be reseted every time you update deconz, the second one is fixed.

> All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/generic/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/deconzuser/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

**Comment by mc4one** [comment]
Ok I still wait the update's coming alone by a update.

I will reboot Deconz every day. Because at this moment from Home Assistant the connection to Deconz is by integrate VNC and no way to uploade something :/ I see the new DDF on PR #5985 but I can't do anything with it :/

**Comment by mc4one** [comment]
Update done.

But when I tried to open the CM10ZW I found /usr/share/deCONZ/devices/ORVIBO I've got an "fail to open" :(
If I tried a other one (other brand) no problem.

**Comment by Smanar** [comment]
Ha ?
I don't think it's a right issue, as all files in the folder have same.
Can check the permissions with `ls -l`

**Comment by mc4one** [comment]
I don't know how to check the permissions :/

i'm going to be mad...

**Comment by mc4one** [comment]
hooo ok, just need to wait a new update so :) And with luck... :D 

The fail to open was on Deconz. I don't really know how to use console... Yeah yeah a noob... lol

**Comment by Mimic33** [comment]
Hi,
I have a similar issue I can't fixed : I can't include the module in Phoscon. In deConz, I have no name, manufacturer and model. I tried to re include, and re discover the module, read the basic for each of the 3 end points but nothing :
![image](https://user-images.githubusercontent.com/105454698/168144358-a5b2f90f-3798-4161-ad9d-fa3371720855.png)
![image](https://user-images.githubusercontent.com/105454698/168144415-f07c4cb9-5bed-4376-a909-ef64e337d264.png)
I have updated to 2.16 beta and copied the DDF from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6013

**Comment by mc4one** [comment]
Hi, like @Smanar said it's a issue with the typo on the DDF. So it's not the right vesion I guess.
Need to wait a Deconz update...

But if you make the same things like smanar said to me you can make it work.

**Comment by Mimic33** [comment]
I updated deCONZ to the v2.16 beta and replaced manually the DDF with the one from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6013 but it does not work.

**Comment by Smanar** [comment]
Its seem to be the same device.
Can you use "edit DDF" to check if the edited file is used ? You will see the path and the file name on the DDF editor.
If not, take file / open  to use the edited file.

**Comment by Mimic33** [comment]
Hi,

The path is not good, it seems to be in my hom and not in usr/share... :
![image](https://user-images.githubusercontent.com/105454698/168528833-cad84cfb-14db-417b-affe-61dd9003fa16.png)

I tried to open and select the one from usr/share..., it opened but then I don't know how to use it, if I close the window, I loose it and I have the one from my home reloaded.

**Comment by Mimic33** [comment]
It's OK, I've copied the one from usr/share... to the home folder and renamed it. It s nwo recognized as On/Off plugin unit :) :) :)

**Comment by mc4one** [comment]
> It's OK, I've copied the one from usr/share... to the home folder and renamed it. It s nwo recognized as On/Off plugin unit :) :) :)

You use which OS ? Home assistant ? Jeedom ? other ?

**Comment by Mimic33** [comment]
Yes Jeedom with a Raspberry Pi

**Comment by mc4one** [comment]
> Yes Jeedom with a Raspberry Pi

I'm on Home assistant, hard for me to update on the beta version :/ Need to wait the final update :(
