### ISSUE TITLE
Xiaomi Aqara motion sensor timeout

### ISSUE THREAD

**Issue by FrankH1** [dresden-elektronik/deconz-rest-plugin#3980]
## Describe the question or issue you are having
Hi there,

I'm using a ConBee II with several lights/dimmers (different vendors), plugs and sensors (IKEA). Have connected the device to OpenHab and do the most things there. Works quite well and stable. Directly in Phoscon I just use 2 sensors to control a light. That works kind of ok but I had some trouble with the timeout of the IKEA sensors (roughly 1,5 minutes to spot a new movement).
Now I purchased an Xiaomi Aqara motion sensor (reported version 20170627) in the hope that this works better. Xiaomi homepage says it should detect once every minute. Unfortunately I see an update in Phoscon (and correspondingly in OpenHab) only after exactly 5 minutes. To be absolutely precise - once a motion is detected the sensor reports 5 minutes that there is a motion and only afterwards changes to "no motion". The detection of a new motion once it has reported "no motion" happens quickly/nearly immediately.
The report of the brightness behaves even less predictable, but this is less important to me at the moment.
Is there something to solve the problem?

## Environment
Host system: Raspberry Pi 3
Running method: Raspbian /OPENHABian
Firmware version: 26680700
deCONZ version: 2.05.74
Device: ConBee II
Do you use an USB extension cable: yes
Is there any other USB or serial devices connected to the host system? yes - SSD

**Comment by SwoopX** [comment]
You might want to give this here a try:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues
