### ISSUE TITLE
Develco Temperature and Humidity Sensor HMSZB-110

### ISSUE THREAD

**Issue by myka280** [dresden-elektronik/deconz-rest-plugin#3986]
## Device

- Product name: Temperature and Humidity Sensor
- Manufacturer: Develco Products A/S
- Model identifier: HMSZB-110
- Device type : 
  - Sensor
 
## Screenshots

![image](https://user-images.githubusercontent.com/35782404/102769802-d3ed6e00-438b-11eb-92cd-07a679217386.png)
![image](https://user-images.githubusercontent.com/35782404/102769823-da7be580-438b-11eb-8a0c-a03e2910c613.png)
![image](https://user-images.githubusercontent.com/35782404/102769837-de0f6c80-438b-11eb-9615-fc7be7d8da56.png)
![image](https://user-images.githubusercontent.com/35782404/102769844-e071c680-438b-11eb-9e67-b35d5bf9aef7.png)
![image](https://user-images.githubusercontent.com/35782404/102769847-e2d42080-438b-11eb-993b-44ce584c9e40.png)
![image](https://user-images.githubusercontent.com/35782404/102769857-e49de400-438b-11eb-8035-49d6fdd4e058.png)
![image](https://user-images.githubusercontent.com/35782404/102769869-e7003e00-438b-11eb-9427-11612ac6e0d2.png)

Please add device support to Phoscon. Sensor should expose battery, temperature, humidity and link quality readings

**Comment by SwoopX** [comment]
@myka280  Can you please update the 2nd screenshot? The information from the node info panel belongs to your coordinator ;)

**Comment by myka280** [comment]
Sure.
![image](https://user-images.githubusercontent.com/35782404/103011466-a5fe5a00-4542-11eb-84ca-51fe64f9e122.png)
