### ISSUE TITLE
IAS enrollment silently fails

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#3988]
## Describe the bug
Devices containing an IAS zone cluster do not get properly enrolled in some cases, resulting in non-functional sensors (presence, open/close, fire, etc.).

Currently, when new devices are paired and contain an IAS zone cluster, the tone state and IAS CIE address should be read. Based on the response, the code determines if a sensor is already enrolled or not. In case it isn't, the IAS CIE address should be written, thereby initiating the enrollment. `config.pending` shall be used to track the enrollment process.

While this has worked in testings of the previous IAS zone code amendments and for most of the users in the wild, there's been reports in Discord and in some git issues that automatic enrollment was not successful (a prominent example being the LIDL motion sensor).

To pinpoint any potential issue in this regard, the debug output in this regard has been significantly increased. Further tests have shown some hickups in the tracked status of the enrollment process and most notably, attribute reads were marked as being successful without any trace of an attribute read request in the sniffer logs. This happened rarely and randomly.
Apparently, function `readAttribues()` has 3 fail conditions, which do not generate any further debug output. Any fail of an attribute read request is not properly catched and not automatically retried. Also, the enrollment state is currently not stored in memory and also not verified upon any apsde data indication towards the IAS zone cluster.

Currently, a manual enrollment via deconz GUI is required in case the automatic enrollment has not succeeded.

## Steps to reproduce the behavior
Not consistently reproducable. However, if the IAS zone state is `not enrolled` after pairing is a strong indication.

## Expected behavior
IAS zone state should report `enrolled`

## Screenshots

N/A

## Environment
Irrelevant, as this is a software bug. Deconz versions 2.09.00-beta and below are affected.

## deCONZ Logs

N/A

## Additional context

Chapters 8.2.2.2.3 and 8.2.2.3.1.2 of the specs for IAS zone cluster.

As a side note and eventually and additional reason of the failed enrollment, it is not ensured the correct sensor is chosen during processing of IAS zone related data (keeping track of the zone enroll request to be precise).

**Comment by Mimiix** [comment]
Can you provide some more context/Logs/findings?
