### ISSUE TITLE
Unable to use Conbee stick under Debian-distro

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/deconz-rest-plugin#3993]
## Environment

 - Host system: (NAS)
 - Running method: (OpenMediaVault v5.5.11, x64 build)
 - Firmware version: (latest)
 - deCONZ version: (latest)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) 
 - Is there any other USB or serial devices connected to the host system? (no)

**Comment by Mimiix** [comment]
Template not complete. A lot of info missing. 

Closed
