### ISSUE TITLE
[Readme] Link request

### ISSUE THREAD

**Issue by asciidisco** [dresden-elektronik/deconz-rest-plugin#4]
Hi,

I would like to use the software, but the GPIO Pins of my Raspberry are in use,
besides the links of the addon module, you write smth. about a "deRFusb23e0x wireless USB dongle". But unfortunately this one is not linked & my google search wasn't that successful either.

Is it one of the ones listed here: https://shop.dresden-elektronik.de/radiosticks.html ?
Would be really cool if you could provide a link.

Thanks.
Cheers.
Sebastian

**Comment by manup** [comment]
The deRFusb23E0X dongle as well as the newer [ConBee](https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/conbee?L=1) don't have the 5 nodes limit anymore.
