### ISSUE TITLE
Define the used IP ddresses of the System.

### ISSUE THREAD

**Issue by talun2075** [dresden-elektronik/deconz-rest-plugin#4004]
## Describe the question or issue you are having
Is is possible to define the IP Address that the rest Plugin is used? default it takes all ip addresses of the system and use the port for all ip addresses.

I found a paramater for the http and websocket Port but not for the IP.

## Screenshots
![restplugin](https://user-images.githubusercontent.com/27155144/102892796-b5a57200-4460-11eb-84df-72817f1b8a2e.PNG)

## Environment

 - Host system: Windows
 - Running method:  Windows
 - Firmware version: (26680700)
 - deCONZ version: (2.07.01)
 - Device: ConBee II
 - Do you use an USB extension cable: (yes ) -- only relevant for ConBee I/II 
 - Is there any other USB or serial devices connected to the host system? If so: Keyboard Mouse

**Comment by SwoopX** [comment]
This is currently not possible. Closing this in favor of #3948

**Comment by talun2075** [comment]
Perfect. Thanks.
