### ISSUE TITLE
LELLKI WP33, aka E220-KR4N0Z0-HA

### ISSUE THREAD

**Issue by yruss972** [dresden-elektronik/deconz-rest-plugin#4006]
## Device

- Product name: Smart Power Strip WP33
- Manufacturer: <Empty>
- Model identifier: E220-KR4N0Z0-HA
- Device type :
  - Light
  - Other: Shows as On/Off light x4 but really it's 4 outlets  

## Screenshots

 - Basic Cluster attributes in the Cluster Info panel.
![Screen Shot 2020-12-22 at 20 11 09](https://user-images.githubusercontent.com/1858636/102920113-c1119100-4492-11eb-91e5-961b5d150c23.png)

  - Node Info panel
![Screen Shot 2020-12-22 at 20 24 03](https://user-images.githubusercontent.com/1858636/102920595-ad1a5f00-4493-11eb-80a6-31c41e6fed89.png)

  - Endpoints and clusters of the node
![Screen Shot 2020-12-22 at 20 21 28](https://user-images.githubusercontent.com/1858636/102920353-514fd600-4493-11eb-8725-92b4edc6f781.png)

**Comment by SwoopX** [comment]
Can you please read the manufacturer name from basic cluster as well please? Other than that and a small addition to ensure on/off state is reported, the device should be fully functional out of the box.

**Comment by yruss972** [comment]
Nothing comes up for the manufacturer. It's just empty.
The device works partially out of the box.
If the 'lights' are assigned to a group in phoscon they can be switched on and off. Trying to turn them on without a group results in them cycling on and off several times.
Renaming them in phoscon has a similar effect.

**Comment by SwoopX** [comment]
@yruss972 Can you please give me a screenshot where and how exactly you try to switch them in Phoscon?

**Comment by cagnulein** [comment]
i guess i have a little sister of yours @yruss972 

![image](https://user-images.githubusercontent.com/48216/105044199-c6003b00-5a66-11eb-92fc-9d90fca208d6.png)
