### ISSUE TITLE
RaspBee and SSD Interference

### ISSUE THREAD

**Issue by vantino** [dresden-elektronik/deconz-rest-plugin#4009]
Ciao

First, I love it. Used a pi3 and a raspbee sending module for more than 2 years.
Since the kids crashed it, I ordered the new RaspBee2 devive. Installation and configuration was easy and the new pi3+ Rev 1.3 worked.

However !!!

It was placed next to my pi4 cloud maschine which operates at an Samsung M2 SSD (boot media).

And guess what, my fhem suddendly doesnt work anymore. 

Make the storry short.

Interference of SSD /w RaspBee makes it out of order.

I write this to save someones lifetime.

The pitty is, you can not run a full pi4 8GB server, booting from an SSD and have the zipbee sender on board. 

Schade ... 

V.

**Comment by Mimiix** [comment]
This is known. Please read the wiki.

Also, this is not how the template works.

**Comment by vantino** [comment]
ok - can i get a link to your wiki ?

**Comment by ebaauw** [comment]
An SSD in itself shouldn't be causing any issues.  How do you connect the SSD to the Pi4?  USB3 is a known source of interference.

**Comment by Mimiix** [comment]
@vantino https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log

**Comment by vantino** [comment]
danke

**Comment by unwrittenlaw** [comment]
sorry for the stupid question, but can i never boot the pi from an ssd and use the raspbee i? or does it also work with an extension cable? or do I have to take a usb2 case?

i would use pi4+ssd+raspbee i+home assistant 64bit. thanks a lot.

**Comment by Mimiix** [comment]
@unwrittenlaw you need to make sure the USB interference can't reach it.
