### ISSUE TITLE
can I add other devices working with the  ZigBee Home Automation profile to deConz?

### ISSUE THREAD

**Issue by marcogaudino** [dresden-elektronik/deconz-rest-plugin#401]
Hi guys, 
i'm working from few days with deConz. can i visualize in deConz other device instead of the only lights?

I would like to visualize in the software, devices like door lock, smart socket and so on. 

Can someone help me? Thank you very much. 

Marco

**Comment by manup** [comment]
Yes there are some sensors and switches from larger brands supported as well, do you have any specific in mind?

**Comment by marcogaudino** [comment]
Yes, Yale door lock

Il giorno sab 24 feb 2018 alle 13:08 Manuel Pietschmann <
notifications@github.com> ha scritto:

**Comment by manup** [comment]
Currently there is no support for this device it might be added if related debug info can be provided.

**Comment by florischabert** [comment]
Hey @manup, I'm also interested in using a Yale door lock with deconz. Looks like supporting the zigbee lock cluster requires some deeper changes, right? What debug info would you need?

**Comment by davidlzs** [comment]
@manup, I got Yale lock, yale Zigbee module, RPi3B+, RaspBee. Would you let me know what kind of debug need to gather? And how?

**Comment by ebaauw** [comment]
See 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by manup** [comment]
Closing this for now, as suggested please open a device specific issue with the needed details.
