### ISSUE TITLE
TRADFRI Shortcut button

### ISSUE THREAD

**Issue by Romain-76** [dresden-elektronik/deconz-rest-plugin#4011]
## Device

- Product name: IKEA Tradfri shortcut button.
- Manufacturer: IKEA.
- Model identifier: TRADFRI Shortcut button.
- Device type : 
    - Switch

![image](https://user-images.githubusercontent.com/65177666/103013293-2ae67500-453d-11eb-9ba4-ea9dfd06c799.png)

![image](https://user-images.githubusercontent.com/65177666/103013397-5d906d80-453d-11eb-813b-291e057674d0.png)

![image](https://user-images.githubusercontent.com/65177666/103013267-1b672c00-453d-11eb-91ce-403f2fe5d39c.png)

**Comment by Mimiix** [comment]
Please use search. there's already a issue on it and a PR made (and merged..).
