### ISSUE TITLE
Tuya Zigbee 4 gangDevice name

### ISSUE THREAD

**Issue by Simonk007** [dresden-elektronik/deconz-rest-plugin#4012]
Tuya Zigbee 4 gang

- Product name: Wireless Scene Switch 20/36
- Manufacturer: Tuya
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : 4 switch 

Feature

- Name：4 Gang Zigbee smart switch
- Compatible：Tuya,Smartlife,Smartthing
- Operability：Control other Wifi or Zigbee intelligent devices and scene.
- Push the button：single click,double click,long press

Specification

Communication:Zigbee 802.15.4
Button lifecycle:500k
Dimension:86*86*13mm
Material:Mechanical Push On/Off Button
Input power:CR 2430 button battery（Need to buy it yourself）
Battery life:730days
Standby current:10uA
Receive sensitivity:-101dBm
Indicator light:LED
Standby consumption:<=20mW
Transmit power:19dBm
Operating frequency:2.400~2.484GHz

https://www.aliexpress.com/item/1005001302383925.html?spm=a2g0o.productlist.0.0.6570621ddJVL11&algo_pvid=5b5846c7-c06c-4c98-9c0d-8ed2526e1e49&algo_expid=5b5846c7-c06c-4c98-9c0d-8ed2526e1e49-0&btsid=0bb0623d16086744509461424e4973&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

![2020-12-23 20_27_05-Benexmart Tuya Zigbee Switch Control Other Wifi or Zigbee Intelligent Devices an](https://user-images.githubusercontent.com/5716779/103031060-65600a00-455d-11eb-80c9-17f5c2a5f31b.png)

**Comment by dmontes46** [comment]
is this working with deconz ?

**Comment by AssetBurned** [comment]
For me it is detected in Phoscon "2.09.03 / 23/12/2020" running on a Raspberry 2B with RaspBee 1 and Homebridge 1.3.4.
But every button click is detected twice.
