### ISSUE TITLE
Device request for NYCE NCZ-3041-HA motion sensors

### ISSUE THREAD

**Issue by glc650** [dresden-elektronik/deconz-rest-plugin#4013]
## Device

- Product name: Motion Sensor
- Manufacturer: NYCE
- Model identifier: 3041
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

![IMG_0895](https://user-images.githubusercontent.com/6758825/103032176-45f0bf00-4514-11eb-9e06-54aeace207d8.jpg)
![IMG_0920](https://user-images.githubusercontent.com/6758825/103032182-4d17cd00-4514-11eb-8db9-0dc108626a4f.jpg)
![IMG_0898](https://user-images.githubusercontent.com/6758825/103032187-51dc8100-4514-11eb-80c0-685d37a6b194.jpg)
![IMG_0900](https://user-images.githubusercontent.com/6758825/103032192-543edb00-4514-11eb-8a4a-78ae749018c6.jpg)
![IMG_0903](https://user-images.githubusercontent.com/6758825/103032210-5c971600-4514-11eb-9761-19d6c6ac83e9.jpg)
![IMG_0906](https://user-images.githubusercontent.com/6758825/103032227-61f46080-4514-11eb-817c-e4c27bea73c8.jpg)
![IMG_0910](https://user-images.githubusercontent.com/6758825/103032233-64ef5100-4514-11eb-827c-49a3d1f8e1f8.jpg)
![IMG_0911](https://user-images.githubusercontent.com/6758825/103032239-6882d800-4514-11eb-9eab-9f7a46e3eaa0.jpg)
![IMG_0916](https://user-images.githubusercontent.com/6758825/103032241-6b7dc880-4514-11eb-9bec-42379584085d.jpg)
![IMG_0919](https://user-images.githubusercontent.com/6758825/103032248-6d478c00-4514-11eb-9a81-83fa2a64dcad.jpg)

**Comment by wvuyk** [comment]
Is there anything missing for this request?

**Comment by Mimiix** [comment]
Seems correct to me

**Comment by SwoopX** [comment]
Added in 2.10.00-beta
