### ISSUE TITLE
Device request for Kwikset SmartCode 916 door lock

### ISSUE THREAD

**Issue by glc650** [dresden-elektronik/deconz-rest-plugin#4014]
## Device

- Product name: SmartCode 916 touchscreen Electronic Deadbolt
- Manufacturer: Kwikset
- Model identifier: SMARTCODE_DEADBOLT_10T
- Device type : Please remove all unrelated device types. 
  - Lock

## Screenshots

![IMG_0946](https://user-images.githubusercontent.com/6758825/103037121-1cd62b80-4520-11eb-81c4-d283231981ca.jpg)
![IMG_0947](https://user-images.githubusercontent.com/6758825/103037133-23fd3980-4520-11eb-89c9-f400dffa3bc3.jpg)
![IMG_0948](https://user-images.githubusercontent.com/6758825/103037137-25c6fd00-4520-11eb-8c5c-d67de0d7b71d.jpg)
![IMG_0949](https://user-images.githubusercontent.com/6758825/103037142-28c1ed80-4520-11eb-9ce1-e29131508304.jpg)
![IMG_0950](https://user-images.githubusercontent.com/6758825/103037147-2bbcde00-4520-11eb-9c80-a94e0874069c.jpg)
![IMG_0951](https://user-images.githubusercontent.com/6758825/103037149-2e1f3800-4520-11eb-9a29-6c482043ac8e.jpg)
![IMG_0952](https://user-images.githubusercontent.com/6758825/103037151-311a2880-4520-11eb-8c8b-4bb1baa8753a.jpg)
![IMG_0953](https://user-images.githubusercontent.com/6758825/103037236-3d9e8100-4520-11eb-8f05-801af3ffacfc.jpg)
![IMG_0954](https://user-images.githubusercontent.com/6758825/103037254-455e2580-4520-11eb-8e2c-b2acbc553001.jpg)
![IMG_0955](https://user-images.githubusercontent.com/6758825/103037259-48f1ac80-4520-11eb-86e1-cfbd9dc2aa12.jpg)
![IMG_0956](https://user-images.githubusercontent.com/6758825/103037265-4c853380-4520-11eb-88b4-ed2c0650f823.jpg)
![IMG_0957](https://user-images.githubusercontent.com/6758825/103037270-4e4ef700-4520-11eb-8e1d-4c6868cf210c.jpg)
![IMG_0958](https://user-images.githubusercontent.com/6758825/103037272-5018ba80-4520-11eb-8cb1-2db830dbac88.jpg)
![IMG_0959](https://user-images.githubusercontent.com/6758825/103037276-527b1480-4520-11eb-93b0-dba5d61c36f6.jpg)

**Comment by Smanar** [comment]
Hello, I have started the integration for a device that look like yours https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3152

But without return, do you have an unix machine to test code modifications ?

**Comment by glc650** [comment]
Closest thing I have to a unix machine is a Macbook Air.

**Comment by Smanar** [comment]
And with real OS not hassio ?
Macbook Air run on unix ?

**Comment by wvuyk** [comment]
Is this not possible to create it for the REST API?

**Comment by Smanar** [comment]
Nope, It s a long story, but I m rewriting all the code that support doorlock, to create a ZHADoorlock device.
So it s a big change, and I can make a PR without someone to do some test.

The code on this issue is out of date.
