### ISSUE TITLE
v2.05.01 doesn't update RaspBee firmware

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#402]
Just installed v2.05.01 on my test Raspberry.  deCONZ starts and runs without problems, but it doesn't prompt to update the RaspBee firmware.  It's on 0x261A0500 where the code suggests it should want 0x261C0500.

**Comment by ebaauw** [comment]
Now, I see an Update Firmware option under Settings in the Web app.  Maybe there was a hiccup downloading the new firmware file?

**Comment by manup** [comment]
It might take a while till the button appears. Side note 0x261e0500 will be available in the 2.05.02 release.
