### ISSUE TITLE
Device Request: Aurora AOne AU-A1ZBR2GW

### ISSUE THREAD

**Issue by coobnoob** [dresden-elektronik/deconz-rest-plugin#4027]
## Device

- Product name: Aurora AOne Smart Rotary Dimmer Switch - 2 Gang
- Manufacturer: Aurora
- Model identifier: 2GBatteryDimmer50AU
- Device type : 
  - Switch
  - Other:
    - Dimmer 

## Screenshots

![image](https://user-images.githubusercontent.com/29867612/103154233-ef8eb500-478d-11eb-9f23-18b3071486bf.png)
![image](https://user-images.githubusercontent.com/29867612/103154243-ffa69480-478d-11eb-8d5c-5556337ccf8a.png)

![image](https://user-images.githubusercontent.com/29867612/103154281-6035d180-478e-11eb-91e0-2d2d7fc2d341.png)

**Comment by SwoopX** [comment]
Required screenshots as per request template are missing.
