### ISSUE TITLE
Ikea Fyrtur stops working once reconnected

### ISSUE THREAD

**Issue by mzander** [dresden-elektronik/deconz-rest-plugin#4028]
Hi guys,

I am running deconz on a raspberry 4 with a raspbee.

Fyrtur seems only connect to one device and not multiple as other devices do.
That is what the gui shows.

My problem is, that both blinds stops working completely once they have been disconnected. Even if they have reconnected.
If they are connected to the raspbee or repeater and I switch off the repeater and then on again I need to powercycle the blinds. Otherwise they are not controllable anymore.
The UI and also commands via iobroker doesn’t work until the battery has been removed or I repair them again.

Does anyone have the same problem?

Thanks

**Comment by olemr** [comment]
`Does anyone have the same problem?`

Yes. I am not able to control them (2.09.00) even though they appear online, but the open/close remote pairing set up in the old WEB App works, so I'm happy with that.
The 2 Fyrturs are only 1m from the Conbee.
