### ISSUE TITLE
ClimaxTechnology Support

### ISSUE THREAD

**Issue by oz-boy** [dresden-elektronik/deconz-rest-plugin#403]
Evening all .... I bought a relay switch (http://www.climax.com.tw/downloads/PRMD2-ZBS_Product%20News_20170705.pdf) which connects to my deCONZ network without issues. I can toggle its state via 0006 on/off without issues, however the manufacturer code on node info reads 0x0000. After reading issue 24 ( https://github.com/dresden-elektronik/deconz-rest-plugin/issues/24), I modified de_web_plugin_private.h and light_node.cpp but cannot see it as a light in the API. Do you have any suggestions on what to try next? I also have an Osram plug (0xbbaa) that shows up without issues. Thanks for any tips!

**Comment by ebaauw** [comment]
Did you get the PRMD2-ZBS or the PRMD2-ZBSR?  Currently deCONZ only works with “lights” that are routers, see #311.

**Comment by oz-boy** [comment]
I'm not 100% sure which model it is - will try to find out. What about the 0x0000 Manufacturer Code? What effect does this have?

**Comment by ebaauw** [comment]
Not sure.  Does the node show yellow (router) or grey (ebd-device) in the deCONZ GUI?

**Comment by oz-boy** [comment]
The graphics box has a grey stripe on the left hand side ...

**Comment by oz-boy** [comment]
Does anyone have a comment about the 0x0000 Manufacturer Code? Is there any way to assign a manufacturer code? Or can a new firmware/software be installed on the switch? Thanks in advance!

**Comment by ebaauw** [comment]
Looking at the code, there’s other devices with a Manufacturer Code of 0x0000.  I wouldn’t worry about that.

Indeed, you would need new firmware to change it.  If the switch exposes an OTAU cluster, there’s a chance the firmware can be updated through deCONZ, ... if the vendor provides the firmware.  Most don’t, however.

**Comment by manup** [comment]
The Climax devices are often white label OEM products, hence the unspecified manufacturer code. For example some Bitron products are Climax under the hood.
