### ISSUE TITLE
Xiaomi Aqara Motion sensor unavailable in Phoscon / seems to "react" in Deconz

### ISSUE THREAD

**Issue by tosion** [dresden-elektronik/deconz-rest-plugin#4035]
I use Deconz addon with HA NUC image. There is one Aqara motion sensor which became unavailable in HA and Phoscon. I think it happened after the latest addon update. To have a sensor unavailable is nothing new for me but this time in VNC/Deconz it seems the sensor is responsive. Green line will show up after device reboot and addon restart. Also blue dot will blink when "reading cluster info".

I am far away from the sensor location and I am just wondering is there any way to get that sensor remotely available again in HA/Phoscon side.

Or is that "responsiveness" in VNC just some false info..... Based on the green line the sensor is connected thru Osram Smart+ plug to the system.

Any help will be highly appreciated.

![image](https://user-images.githubusercontent.com/48414735/103171335-28915d00-4854-11eb-95e2-b234311ee01e.png)

**Comment by SwoopX** [comment]
Can you provide some deconz logs? Around 5 mins should suffice. Please make sure that the timeframe encompasses at least 2 mins where ther's no motion guaranteed and then motion is triggered. The log levels must be dbg-info=2 and dbg-error=2.

When we'd see an attribute report of the sensor sending occupancy = true on ZCL level, that would confirm the sensors is operational and sending status updates.

**Comment by tosion** [comment]
Thanks for a super fast response!

As mentioned I am far away from this sensor so I can not create a motion remotely.  With logs are you meaning deconz addon logs? But if I can not create a motion?

I also would need some help how to provide this REST API output?

BTW how can I label my question as "User Quoestion" insted of "Bug Report"

**Comment by tosion** [comment]
More info for this issue. I have 6+7 of these Xiaomi Aqara/Mija sensors in two different location. I another location 7 sensors work very well, they react as supposed and in HA/Phoscon/DeconzVNC they seem to "work" OK.

From six sensors in another location 2 work OK in HA/Phoscon/VNC.

One is not available in HA and is greyed and not available in Phoscon, but seem to work OK in VNC.

Three are available in HA, they are not greyed in Phoscon but in sensor details in Phoscon they are not reachable (pic below). In VNC they seem to be OK?

One more observation which is not related to this is that in sensor detail last seen seem to be in German even the language selection is in English (is there a reason to open a new bug report?):

![image](https://user-images.githubusercontent.com/48414735/103270771-6b247800-49c1-11eb-8706-4c6457b50958.png)

![image](https://user-images.githubusercontent.com/48414735/103270328-4c71b180-49c0-11eb-8d3c-7e4b39a52c6d.png)

**Comment by SwoopX** [comment]
Are you able to provide some screenshots of the troublesome sensors from deconz GUI (via VNC) with an expanded cluster list (right most black bullet on the node)?

The symptoms would fit in, check https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by tosion** [comment]
Thanks! You do not mean that picture I had in the first post? Or d you mean like basic cluster sheet?

![image](https://user-images.githubusercontent.com/48414735/103281139-c0b94e80-49da-11eb-8abc-48a170b646e0.png)

**Comment by SwoopX** [comment]
Sorry, overlooked your previous screenshot while writing.

The Aqara I got here looks identical from the clusters perspective. Interesting fact around the lastseen though...

Could you please provide the REST API output from your most troublesome Aqara sensor? I'd be interested in the order of the 2 corresponding sensors.

**Comment by tosion** [comment]
OK thanks!

I think I found (the picture below that log you mentioned earlier (I do not know how to copy it though). But can you help me out where to get that RES API output?


![image](https://user-images.githubusercontent.com/48414735/103289758-9ecac680-49f0-11eb-8f54-3ca27223dfbd.png)

**Comment by Mimiix** [comment]
@tosion In case of the HA addon: this is a limitation by how they implemented the VNC in the browser. I recommend setting up VNC itself and use a VNC client to connect.

**Comment by tosion** [comment]
I can do VNC/VNC - but is it still limited what I can do there. But yes please can you help how to get REST API output with VNC/VNC so I can try it. ( My best bet is I can not do it when running Deconz Addon in HA)

**Comment by tosion** [comment]
Last update for this case. I took a long drive to the location of these sensors. 

Three sensor which were available in HA but greyed in Phoscon became active in Phoscon when motion was triggered - so they worked well HA/Doconz also (I don't know why they were not reachable in Phoscon - now they are)

The one which was not available in Phoscon and HA needed a repair -> worked OK after that. 

Even I do not quite understand this behavior this is pretty much case closed from my side.

Thanks for our help anyway! I do not know should I close this because this "bug" is not solved yet?
