### ISSUE TITLE
How to Turn off Heiman Siren.

### ISSUE THREAD

**Issue by AbDhops** [dresden-elektronik/deconz-rest-plugin#4045]
## Describe the question or issue you are having

I am using Heiman WarningDevice (Siren) with Deconz. It is paired with Home Assistant and Node Red. 
For some of other reason (water leakage), Node red automation triggered an alarm. So far so good. However, even after I switch off the alarm, device didnt stopped ringing. Even though the device was ringing (loud !!), status of Switch in Deconz was off and siren as sensor was also off.

## Environment

 - Host system: NAS
 - Running method: Home Assistent deCONZ Add-on / Marthoc Docker container on Synology
 - Firmware version: 26660700
 - deCONZ version: 2.05.81 / 9/14/2020
 - Device: ConBee II
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? : No

**Comment by RealKanashii** [comment]
Can you post the node red switch? Maybe you don't used the passthrough payload?

**Comment by AbDhops** [comment]
I am directly using "turn_off" service... 
![image](https://user-images.githubusercontent.com/46280644/103227093-dc1a5000-492d-11eb-8b50-a8e6f99686ad.png)

**Comment by AbDhops** [comment]
So, I debugged further. I deleted the Alarm from every where (Home Assistant, Deconz and Node red). Also reseted the device physically. And added again the device as different name i.e. Siren. 
Now, this is visible in Home Assistant as Siren. But multiple devices. See below.

![image](https://user-images.githubusercontent.com/46280644/103231163-729f3f00-4937-11eb-9882-75a51fce7f1c.png)

Now, if I turn on switch.siren, siren goes On. However, switch status (which I had turned On), goes back to off. Siren continues to ring. To switch it off, I must "Turn On" the switch and make it off again while it is in "On" state. Once it goes back to off I can't turn off the siren.

light.siren and sensor.siren are basically useless sensors. They never change the status. 

From PhosconGUI, every thing remains off. No matter if siren is ringing...

**Comment by Smanar** [comment]
Wich one decone filed are you changing with your automation ? for siren it's not state/on and state/off.

**Comment by AbDhops** [comment]
I am not using Deconz field. I am using Home Assistant Deconz integration. In it, device is visible as siren. See image from my previous [post ](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4045#issuecomment-751791861).

If I turn on switch.siren (from Home Assistant), siren starts ringing. However, switch status (which I had turned On in home assistant), goes back to off state automatically. Siren continues to ring. To switch it off, I must "Turn On" the switch (again in Home Assistant) and make it off again while it is in "On" state. Once it goes back to off (it goes off automatically in Home Assistant) I can't turn off the siren.

light.siren and sensor.siren are basically useless sensors in (Home Assistant). They never change the status.

From PhosconGUI, everything remains off. No matter if siren is ringing or not (by using switch in Home Assistant). Also, I am not able to turn on Siren from Phoscon GUI...

**Comment by SwoopX** [comment]
... because this is not how it works.

**Comment by AbDhops** [comment]
Can you please elaborate... How it works... ?

**Comment by Smanar** [comment]
You don't know the command used by HA ?

**Comment by AbDhops** [comment]
No....

**Comment by SwoopX** [comment]
All sirens are exposed as lights, e.g. like this via REST API

```
"1": {
    "etag": "f57956703c228334a640334d6b7505c3",
    "hascolor": false,
    "lastannounced": "2020-12-23T14:54:28Z",
    "lastseen": "2020-12-28T21:20Z",
    "manufacturername": "Develco Products A/S",
    "modelid": "SMSZB-120",
    "name": "fl.sensor.rauchmelder",
    "state": {
      "alert": "none",
      "reachable": true
    },
    "swversion": "2018-11-27 00:40",
    "type": "Warning device",
    "uniqueid": "00:15:bc:00:31:00:42:94-23"
  },
```

They can be triggered and silenced by sending a PUT request through the API and modify the alert parameter

![grafik](https://user-images.githubusercontent.com/4005212/103386703-73370180-4b00-11eb-8c5f-b92242b5c93a.png)

So,
`{"alert": "select"}` lets it sound for 1 sec, `lselect` for maximum duration
`{"alert": "none"}` silences it

**Comment by AbDhops** [comment]
Thanks @SwoopX,
Things started to make sense now. But how can I do that using node red ? Obviously as "alert" is not standard property for "light", `{"alert": "select"}` triggers an `API error`....

**Comment by og9gjz567** [comment]
Hi,
my solution was to do it in node-red with a http-call. First I define the params in a function node:
`msg.method = "PUT"
msg.url = "http://172.30.33.2:40850/api/xxxxxxxxxxxxx/lights/xx:xx:xx:xx:xx:xx:xx:xx-01/state" ;

msg.payload = '{ "alert": "blink" }'; //only blinks
//msg.payload = '{ "alert": "select" }'; //siren for ever
//msg.payload = '{ "alert": "lselect" }'; //sire for 3 seconds
//msg.payload = '{ "alert": "none" }'; //disable alarm
msg.headers = {};
msg.headers['content-type'] = 'application/json';
return msg;`

ans then I use the http request node to put the request. You can get the IP of the REST API by clicking "plugins" and then "REST API Plugin" in the "IP Addresses" Section. Hope this helps to:

![grafik](https://user-images.githubusercontent.com/58255842/103772739-474cdc00-502a-11eb-9725-e45a72df450d.png)

**Comment by AbDhops** [comment]
Can you please export your flow and paste it here...

**Comment by og9gjz567** [comment]
yes:

`[{"id":"87a51622.21d23","type":"tab","label":"export","disabled":false,"info":""},{"id":"182092e5.fba0dd","type":"inject","z":"87a51622.21d23","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":160,"wires":[["b5c915dd.645e08"]]},{"id":"3e3062c4.72a4c6","type":"inject","z":"87a51622.21d23","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":240,"wires":[["5a88c2c4.cc51bc"]]},{"id":"b5c915dd.645e08","type":"function","z":"87a51622.21d23","name":"Sirene: aus","func":"msg.method = \"PUT\"\nmsg.url = \"http://192.168.178.100:40850/api/XXXXXXXXX/lights/xx:xx:xx:xx:xx:xx:xx:xx-01/state\" ;\n\n//msg.payload = '{ \"alert\": \"blink\" }';\n//msg.payload = '{ \"alert\": \"select\" }';\n//msg.payload = '{ \"alert\": \"lselect\" }';\nmsg.payload = '{ \"alert\": \"none\" }';\nmsg.headers = {};\nmsg.headers['content-type'] = 'application/json';\nreturn msg;\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":410,"y":160,"wires":[["77494fde.91d75"]]},{"id":"da8b454d.fd5fb","type":"function","z":"87a51622.21d23","name":"Sirene: Alarm unendlich","func":"msg.method = \"PUT\"\nmsg.url = \"http://192.168.178.100:40850/api/XXXXXXXXX/lights/xx:xx:xx:xx:xx:xx:xx:xx-01/state\" ;\n\n//msg.payload = '{ \"alert\": \"blink\" }';\n//msg.payload = '{ \"alert\": \"select\" }';\nmsg.payload = '{ \"alert\": \"lselect\" }';\n//msg.payload = '{ \"alert\": \"none\" }';\nmsg.headers = {};\nmsg.headers['content-type'] = 'application/json';\nreturn msg;\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":450,"y":200,"wires":[["77494fde.91d75"]]},{"id":"5a88c2c4.cc51bc","type":"function","z":"87a51622.21d23","name":"Sirene: Alarm","func":"msg.method = \"PUT\"\nmsg.url = \"http://192.168.178.100:40850/api/XXXXXXXXX/lights/xx:xx:xx:xx:xx:xx:xx:xx-01/state\" ;\n\n//msg.payload = '{ \"alert\": \"blink\" }';\nmsg.payload = '{ \"alert\": \"select\" }';\n//msg.payload = '{ \"alert\": \"lselect\" }';\n//msg.payload = '{ \"alert\": \"none\" }';\nmsg.headers = {};\nmsg.headers['content-type'] = 'application/json';\nreturn msg;\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":420,"y":240,"wires":[["77494fde.91d75"]]},{"id":"6e8a40bd.d0003","type":"function","z":"87a51622.21d23","name":"Sirene: blinken","func":"msg.method = \"PUT\"\nmsg.url = \"http://192.168.178.100:40850/api/XXXXXXXXX/lights/xx:xx:xx:xx:xx:xx:xx:xx-01/state\" ;\n\nmsg.payload = '{ \"alert\": \"blink\" }';\n//msg.payload = '{ \"alert\": \"select\" }';\n//msg.payload = '{ \"alert\": \"lselect\" }';\n//msg.payload = '{ \"alert\": \"none\" }';\nmsg.headers = {};\nmsg.headers['content-type'] = 'application/json';\nreturn msg;\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":420,"y":280,"wires":[["77494fde.91d75"]]},{"id":"77494fde.91d75","type":"http request","z":"87a51622.21d23","name":"","method":"use","ret":"txt","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"","x":710,"y":220,"wires":[[]]}]`

**Comment by AbDhops** [comment]
Awesome... Works like charm...

**Comment by AbDhops** [comment]
If it helps : 
Max duration which can be triggered by `lselect` is possible to change by calibrating "Max Duration" using VNC in "IAS_WD" cluster for the device.  This max duration is applicable for maximum blink and maximum siren... 
![image](https://user-images.githubusercontent.com/46280644/103925053-34640580-5117-11eb-8a27-9d4c47966392.png)
![image](https://user-images.githubusercontent.com/46280644/103925101-52ca0100-5117-11eb-9581-7488fb9fe800.png)

**Comment by Pedder007** [comment]
Hi all, thanks for the valuable info here.
I've got also here the Heiman siren HS2WD-E.
All commands work fine by 'curl ...', but not the 'lselect'. It doesn't switch off after a second.
Are there any experiences on that?

**Comment by AbDhops** [comment]
I guess default value for "max_duration" is 45 seconds. To switch off
before, you have to send "none" to alarm or else fine tune the value (of
max_duration)

**Comment by Pedder007** [comment]
Thanks for the quick reply.
I understood above, that "max_duration" is only for the lselect, but not for select?
I already checked what currently is in there and it is a 240 (by default, as I didn't change it).
So I would assume, that by sending 'lselect', after 4 minutes the siren would switch of hereself.
With regard to select, I thought to use it e.g. when setting the sensors to 'sharp', then having a kind of short acknowledgement by a 1 sec tone ...

**Comment by Pedder007** [comment]
ok, have no clue why, but suddenly 'select' works propperly, keeping the siren 'on' only for a second
Thanks again!

**Comment by Obelixje** [comment]
> Hi,
> my solution was to do it in node-red with a http-call. First I define the params in a function node:
> 
> ```
> msg.method = "PUT"
> msg.url = "http://172.30.33.2:40850/api/xxxxxxxxxxxxx/lights/xx:xx:xx:xx:xx:xx:xx:xx-01/state" ;
> 
> msg.payload = '{ "alert": "blink" }'; //only blinks
> //msg.payload = '{ "alert": "select" }'; //siren for 1 sec
> //msg.payload = '{ "alert": "lselect" }'; //siren forever
> //msg.payload = '{ "alert": "none" }'; //disable alarm
> msg.headers = {};
> msg.headers['content-type'] = 'application/json';
> return msg;
> ```
> 
> ans then I use the http request node to put the request. You can get the IP of the REST API by clicking "plugins" and then "REST API Plugin" in the "IP Addresses" Section. Hope this helps to:
> 
> ![grafik](https://user-images.githubusercontent.com/58255842/103772739-474cdc00-502a-11eb-9725-e45a72df450d.png)

Hi,

I hope you are able to help me.
I am working with your node red project.
I am unable to find the API key for my stick. Can you help me determine the key?
And /xx:xx:xx:xx:xx:xx:xx:xx-01/ in your call, is this the MAC of the sirene? Or the Sirene deconz nr?

I hope you can help me with this?

**Comment by og9gjz567** [comment]
Hi. Take a look at: https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/configuration/#aquireapikey

**Comment by og9gjz567** [comment]
You may have to expose the docker port to your lan 😅

**Comment by AbDhops** [comment]
Or use MACVLAN and have dedicated IO to your docker...
