### ISSUE TITLE
Neo Coolcam Siren Alarm ( Tuya compatible)

### ISSUE THREAD

**Issue by RealKanashii** [dresden-elektronik/deconz-rest-plugin#4047]
## Device

- Product name: Neo Coolcam Siren Alarm (tuya compatible)
- Manufacturer: _TZE200_d0yu2xgi
- Model identifier: TS0601
- Device type :
  - Sensor ( temp / humidity )
  - Siren 

## Screenshots

![image](https://user-images.githubusercontent.com/9731708/103215178-e8dd7a80-4912-11eb-930e-571e88988038.png)
![image](https://user-images.githubusercontent.com/9731708/103215124-c3e90780-4912-11eb-9e78-2cfbee6d3cb6.png)
![image](https://user-images.githubusercontent.com/9731708/103215264-23dfae00-4913-11eb-880f-596950260f1c.png)

**Comment by RealKanashii** [comment]
I think the device is not really well identified as the Model Identifier is the same that a Tuya Thermostat has ( found in the issues ).

**Comment by Smanar** [comment]
Classic ^^
Model id is useless for tuya, need to use the manufacture name only.

**Comment by machielw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3183

**Comment by Mimiix** [comment]
Closing this as duplicate.

@RealKanashii Next time, please search the git isseus if a request is already open 😄
