### ISSUE TITLE
Stelpro STZB402+ Thermostat Attribute Missing for System Mode 0X001C

### ISSUE THREAD

**Issue by jveniez** [dresden-elektronik/deconz-rest-plugin#4049]
## Describe the bug
Within deCONZ VNC I can set the System Mode to Heat/Off by reading and changing the setting to off, but from HA I can not. When I check the Rest-API, it does not show that attribute. I see the following. Even when I change the state  "on": false, it does nothing.  When I an in HA and the climate.thermostat always show off even when the thermostat is on. I can adjust the temperature and setpoints, the only issues is the heat/off. The unit is in my garage and the lowest set point is 5c and our winters can drop to -20c, I don;t want to heat the garage when I am not home.

{
  "config": {
    "heatsetpoint": 1000,
    "offset": 0,
    "on": true,
    "reachable": true,
    "schedule": {},
    "schedule_on": null
  },
  "ep": 25,
  "etag": "755629c21a70cfa38e59b1883ba97cf6",
  "lastseen": "2020-12-28T11:10Z",
  "manufacturername": "Stelpro",
  "modelid": "STZB402+",
  "name": "Thermostat",
  "state": {
    "lastupdated": "2020-12-28T11:10:39.730",
    "on": false,
    "temperature": 650
  },
  "swversion": "20170411 00141",
  "type": "ZHAThermostat",
  "uniqueid": "f8:f0:05:ff:ff:f7:81:8a-19-0201"
}

## Steps to reproduce the behavior
In YARC! I try sending a put command for the System mode and receive an error back saying, "      "address": "/sensors/system mode",
      "description": "parameter, system mode, not available", 
-->

## Expected behavior
The Thermostat should be able to be set to off mod,. also when the unit is on it show that the unit is off all the time, even when the state is changed to on:true.
-->

## Screenshots
https://user-images.githubusercontent.com/76670160/103225771-aeff7a80-48f8-11eb-8446-5ce38916d780.png
https://user-images.githubusercontent.com/76670160/103225139-4bc11880-48f7-11eb-974b-50ca4206345a.png
https://user-images.githubusercontent.com/76670160/103225173-61ced900-48f7-11eb-89ef-af10b57f5399.png

-->

## Environment
Version 2.07.01 12/8/2020
Firmware 26660700 
- Host system: (Raspberry Pi)
 - Running method: (Home Assistent deCONZ Add-on)
 - Firmware version: (2660700)
 - deCONZ version: (2.07.01)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) 
 - Is there any other USB or serial devices connected to the host system? If so: No

## deCONZ Logs
When I turn off the Thermostat the logs do show the 0x1C in the logs. 

10:31:37:875 ZCL attribute report 0xF8F005FFFFF7818A for cluster: 0x0201, ep: 0x19, frame control: 0x18, mfcode: 0x0000 
10:31:39:599 ZCL attribute report 0xF8F005FFFFF7818A for cluster: 0x0201, ep: 0x19, frame control: 0x1C, mfcode: 0x1185 

-->

**Comment by SwoopX** [comment]
Can you please provide some screenshots from thermostat cluster of all the attributes (while those have been read, important!) until the system mode?

Additionally, can you please double check attribute 0x0008 (Pi heating demand) gives you some values while the device is turned on and heating? Lastly, attribute 0x0001 in thermostat UI configuration cluster should be the cild lock, could you please also check and confirm? Thanks!

**Comment by jveniez** [comment]
Thermostat Top End
![image](https://user-images.githubusercontent.com/76670160/103289803-192a2500-49b6-11eb-9f95-21a29e6ac019.png)

Basic Cluster
![image](https://user-images.githubusercontent.com/76670160/103289811-1e876f80-49b6-11eb-8917-9ec0f95f0605.png)

Identify Cluster
![image](https://user-images.githubusercontent.com/76670160/103289821-234c2380-49b6-11eb-92c7-af563cf45d50.png)

Attributes
![image](https://user-images.githubusercontent.com/76670160/103289835-29420480-49b6-11eb-86a6-65199f023ef6.png)
![image](https://user-images.githubusercontent.com/76670160/103289841-2cd58b80-49b6-11eb-80bb-f0f6030bb221.png)
![image](https://user-images.githubusercontent.com/76670160/103289844-30691280-49b6-11eb-8398-34b731b841f2.png)
![image](https://user-images.githubusercontent.com/76670160/103289852-35c65d00-49b6-11eb-9c64-0ce1d055c7aa.png)
![image](https://user-images.githubusercontent.com/76670160/103289857-3959e400-49b6-11eb-8695-40d4e2917eae.png)
![image](https://user-images.githubusercontent.com/76670160/103289862-3bbc3e00-49b6-11eb-9205-27c91bd27901.png)
![image](https://user-images.githubusercontent.com/76670160/103289866-3fe85b80-49b6-11eb-962d-5bbc14ff5189.png)

0x0008 (Pi heating demand) Heat Running
![image](https://user-images.githubusercontent.com/76670160/103289897-4d9de100-49b6-11eb-9e9d-3089b70d8ca9.png)

attribute 0x0001 Child Lock (Does not look like Lock)
![image](https://user-images.githubusercontent.com/76670160/103289935-63aba180-49b6-11eb-9db0-eaa1021e944e.png)

**Comment by SwoopX** [comment]
Thanks. You got the wrong attribute for the cild lock. It's 0x0001 in **thermostat UI configuration** cluster.

I'm afraid attribute 0x0008 (Pi heating demand) is useless without any heating being on...

**Comment by jveniez** [comment]
Sorry about that, 

here is the Keypad lockout
![image](https://user-images.githubusercontent.com/76670160/103292083-23025700-49bb-11eb-9487-bcb3bd7c92ab.png)
![image](https://user-images.githubusercontent.com/76670160/103292098-27c70b00-49bb-11eb-9fb8-943736dfe563.png)

**Comment by jveniez** [comment]
This is attribute 0x0008 (Pi heating demand)

This is with the heat turned off
![image](https://user-images.githubusercontent.com/76670160/103292309-8b513880-49bb-11eb-972f-f196921d5958.png)

This is with the heat turned on
![image](https://user-images.githubusercontent.com/76670160/103292347-986e2780-49bb-11eb-88d6-869492291ec7.png)


Thank you so much for helping on this..

**Comment by SwoopX** [comment]
Ok, so Pi heating demand is usable as well. Now, as for the child lock, you would have to set `Level 1 lockout` to enable it. Putting that one in as well as im 99% sure it'll work out.

**Comment by MattL0** [comment]
Just a question.I med to purchase 6* ‘120v’ thermostat. Not decided yet on zigbee/zwave version of sinope or stelpro . 

what are all the info the api is returned for this thermostat? 

And what control do you have ? 

Thank you. @jveniez

**Comment by jveniez** [comment]
Hi Matt,  I have control in HA as well as with Alexa, The only issue I have and it looks to be coming in the next feature request is to turn the unit off completely with the API.  Below is the API pulled from HA, the unit is in my garage so the temperature is correct at -6. You can set the Min/Max temperature or adjust the temperature manually in HA or by voice through Alexa.

hvac_modes:
  - auto
  - heat
  - 'off'
min_temp: 5
max_temp: 22
current_temperature: -6
temperature: 20
valve: 0
friendly_name: Thermostat
supported_features: 1

Hope this help @MattL0

**Comment by MattL0** [comment]
Thank you
