### ISSUE TITLE
Can't update Conbee 2 via Phoscon app

### ISSUE THREAD

**Issue by rutkoe** [dresden-elektronik/deconz-rest-plugin#4058]
## Conbee 2 Gateway display's up-to-date but it isn't. Also not showing new updates (it did previously)

I'm trying to update my Conbee 2 gateway trough the Phoscon app but is is showing me up-to-date all te time. I added a screenshot.

Could someone give me advice or tell me what i need to check to provide the latest stable update for my Conbee 2 stick?
Everything is running fine also in HomeBridge i experience no problems.

If any information is needed i will provide it when it is necessary.

Thanks in advance!

## Environment

 - Host system: (Raspberry Pi 3B)
 - Running method: Raspbian GNU/Linux Buster (10)
 - Firmware version: 26580700
 - deCONZ version: HOW CAN I CHECK THIS?
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No other USB devices

**Comment by rutkoe** [comment]
I just discovered through systemctl that "deconz-init.service     loaded failed     failed       deCONZ: ZigBee gateway -- Initialisation". Could this be the cause of the problem?

**Comment by SwoopX** [comment]
![grafik](https://user-images.githubusercontent.com/4005212/103321451-f4779100-4a39-11eb-89b9-eaf2f0478350.png)

**Comment by rutkoe** [comment]
![Schermafbeelding 2020-12-30 om 00 18 46](https://user-images.githubusercontent.com/76755984/103321616-d6f6f700-4a3a-11eb-94a8-c59face4b3b0.png)

**Comment by Mimiix** [comment]
You are on a failry old version of deCONZ. However, you should update the firmware manually.

**Comment by Smanar** [comment]
Or if you want to update it using phoscon, just update deconz, it will propose you new firmware (if they are)

**Comment by rutkoe** [comment]
I managed to update deconz manually, however, I'm still not sure if it is on the latest version.
![image](https://user-images.githubusercontent.com/76755984/103476668-20876f00-4db8-11eb-922c-723cae421887.png)
for example: Version is still on 2.05.78 (it shows me a more recent date)
Firmware seems to be ok to me.

Any suggestions?

**Comment by Mimiix** [comment]
@rutkoe read into how to update Linux packages.

**Comment by Smanar** [comment]
If you have used package installation

```
sudo apt update
sudo apt install deconz
```

else you have it on the Github Homepage.

**Comment by rutkoe** [comment]
Thanks a lot everyone for their responses and suggestions! I will close this one :)
