### ISSUE TITLE
Curtain switch Tuya Smart Life ZigBee 3.0 SC400

### ISSUE THREAD

**Issue by arodriguezf** [dresden-elektronik/deconz-rest-plugin#4061]
## Device

- Product name: Curtain switch Tuya Smart Life ZigBee 3.0 SC400
- Manufacturer: LoraTap
- Model identifier: 
- Device type : 
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/2402819/103353082-2a535e80-4aa8-11eb-81b2-a4ebf603e67c.png)
![image](https://user-images.githubusercontent.com/2402819/103353113-40611f00-4aa8-11eb-8ae3-d7408fda089a.png)
![image](https://user-images.githubusercontent.com/2402819/103353191-79998f00-4aa8-11eb-8068-52217ed11f69.png)

**Comment by arodriguezf** [comment]
Sorry, now it seems to work, the only pending thing is the calibration of the curtain switch

**Comment by Mimiix** [comment]
@Smanar this feels like a duplicate. Can you confirm?

**Comment by Mimiix** [comment]
Closing and Continue in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3134#issuecomment-732957483

@arodriguezf please use search next time.
