### ISSUE TITLE
Tradfri Driver unreachable after connecting Symfonisk Dimmer directly

### ISSUE THREAD

**Issue by pillemats** [dresden-elektronik/deconz-rest-plugin#4073]
## Describe the bug
Hey together,

i have a problem with the symfonisk driver:

i connect my 3 Tradfri driver with phoscon and it works great.
then i connect my symfonisk dimmer directly to the 3 lamps (I dont connect the dimmer over phoson)
after its done the tradfri driver are not reachable in phoscon.

i must delete it and reconnect them to get it work. - if i connect then the symfonisk dimmer after few minutes the same problem

## Steps to reproduce the behavior
i tried it many times - after connecting the dimmer to tradfri driver the triver will be unreachable

## Screenshots

<img width="417" alt="103442613-1fd7c700-4c58-11eb-921a-070ea12b8844" src="https://user-images.githubusercontent.com/26164977/103442698-f2d7e400-4c58-11eb-9a05-c57a87d17ff3.png">

<img width="734" alt="103442622-32520080-4c58-11eb-9601-b41248bdc132" src="https://user-images.githubusercontent.com/26164977/103442701-f53a3e00-4c58-11eb-906e-4ef173c8ecde.png">

## Environment

<img width="357" alt="103442581-bce63000-4c57-11eb-892c-e049d18beda7" src="https://user-images.githubusercontent.com/26164977/103442707-fd927900-4c58-11eb-8e02-9e66a75bd41f.png">

 - Host system: (PC / NAS)
 - Running method: (Windows / Virtual Machine)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes )

**Comment by Mimiix** [comment]
Hi,

You can't do it that way as then they are connected to each other. I suggest you create the group in the old web ui. 

This is intended behavior, not a bug report. I'll change label.

**Comment by pillemats** [comment]
After few Versions ist works Perfect!

what should i do now

**Comment by pillemats** [comment]
i tested the same with the tradfri on off switch and this works great

can anybody help ?

**Comment by pillemats** [comment]
any idea ?

**Comment by SwoopX** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4073#issuecomment-753345285

**Comment by pillemats** [comment]
in the old webif the switch will not shown.

**Comment by pillemats** [comment]
I tried 4 different dimmer 2 black und 2 white versions.

In phoscon the 2 white shown a dfferent firmware version 2.1.024 and 022
022 works perfect without unreachable lamp

The blackversion shown no firmware versions - but why ?
