### ISSUE TITLE
[Device Support Request] Securifi Peanut Smart Plug

### ISSUE THREAD

**Issue by mwegner** [dresden-elektronik/deconz-rest-plugin#4074]
## Device

- Product name: Securifi Peanut Smart Plug
- Manufacturer: Securifi Ltd.
- Model identifier: [blank]
- Device type : Please remove all unrelated device types. 
  - Sensor
  - Switch
 
## Screenshots

<img width="575" alt="Screen Shot 2021-01-01 at 9 59 13 AM" src="https://user-images.githubusercontent.com/271924/103443082-e469d800-4c18-11eb-9c1d-22f6bd1c7006.png">

<img width="549" alt="Screen Shot 2021-01-01 at 10 01 35 AM" src="https://user-images.githubusercontent.com/271924/103443092-f21f5d80-4c18-11eb-9eff-11781933f90e.png">
<img width="531" alt="Screen Shot 2021-01-01 at 10 01 41 AM" src="https://user-images.githubusercontent.com/271924/103443095-f481b780-4c18-11eb-9904-db70ae96e194.png">

## Notes

There is an [older issue thread about updating the Peanut firmware via deCONZ](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/419).

Off the shelf, these units don't have power sensing active, and _both_ manufacturer and model identifier are blank.  Firmware update is required to add power monitoring.  Securifi has some combo wifi access points / smart hub devices that can perform the update, and can be found cheaply on eBay.  These screenshots are post-firmware update.

I realize that the blank model identifier might be a problem--but there aren't many Securifi devices, and hopefully deCONZ internals can handle the assumption that a "Securifi Ltd." device with an electrical measurement cluster is this smart plug.

## Why support this at all?

It's the only cheaply-available US-plug switch with power sensing capabilities out there.  As near as I can tell, the only other US plug / power sensing smart switch in the supported devices is the 3rd-generation Samsung/Smartthings plug.  They're hard to find in any quantity, and $50-60 per when you do (and those will be one-off eBay purchases).

Up until recently, these Peanut plugs were $13 on Amazon.  They're still very easy to find in the $10-15 range on eBay and elsewhere, and in quantity.  Even with the one-time cost of finding some way to update the firmware, they're far cheaper than any Zigbee alternative for US plugs (and far more reliable than ESPHome solutions, especially with 2.4ghz interference).

**Comment by SwoopX** [comment]
I'm sorry, but this is not doable without any manufacturer name and model ID. The code definitively requires it.
