### ISSUE TITLE
Button maps for EcoDim and Namron switches not found anymore

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#4076]
## Describe the bug

Available button maps for EcoDim and Namron switches are not found anymore. This is due to the change in `Sensor::buttonMap()` from `modelid.startsWith()` to `modelid ==`, where the corresponding modelIDs have not been updated in `button_maps.json`.

This affects at least the aforementioned supported switches. However, more might be affected as well.

## Steps to reproduce the behavior

Push a button and observe the switch state on the emitted websocket event.

## Expected behavior

Button presses shall emit numeric state events.

## Screenshots

![grafik](https://user-images.githubusercontent.com/4005212/103448768-7831b780-4c9e-11eb-9e74-629cf0424c46.png)

## Environment

Irrelevant, deconz versions 2.08.00 - 2.09.00 are affected.

## deCONZ Logs

N/A

## Additional context

N/A

**Comment by manup** [comment]
Although I very much favor the strict modelid check it's a real problem that it broke things, my bad.

I'll add a two stage button maps search:
* First look for strict modelid;
* If that doesn't get a result look via `startsWith()`;
* If the "weak" match is found, use that and print a notice that the full modelid needs to be added for the button map.
