### ISSUE TITLE
Connect to Alexa

### ISSUE THREAD

**Issue by gmum4d** [dresden-elektronik/deconz-rest-plugin#4078]
I’m new to decoz. I have a pi4 running a hoobs image and have just installed deconz along side hoobs with a conbee II usb dongle. I can access via phoscon web on port 1881. And have associated .2 hue bulbs and 2 Tradfri on/off dimmers. These all work ok

## Describe the question or issue you are having
I cannot get Alexa to discover the deconz or any of the devices associated with it. I put the deconz into discovery (60 seconds) and tell Alexa to discover devices but if finds nothing

## Environment

 2.07.01 / 08/12/2020

Pi4
 - Firmware version: 26660700
 - deCONZ version:  2.07.01
 - Device: ConBee II
 - Do you use an USB extension cable: NO 
 - Is there any other USB or serial devices connected to the host system? NO

## deCONZ Logs

  Total newbie and don’t know how to get logs

## Additional context
 Orbi mesh network

**Comment by Smanar** [comment]
Hello, perhaps https://github.com/dresden-elektronik/deconz-rest-plugin/issues/759#issuecomment-417944535
