### ISSUE TITLE
TRÅDFRI Motion sensor disconnected from network

### ISSUE THREAD

**Issue by riston** [dresden-elektronik/deconz-rest-plugin#4082]
## Describe the question or issue you are having
Recently my TRÅDFRI Motion sensor lost connection to my Zigbee coordinator initially, I thought it was a problem because of the battery level dropped to 15%. But even after the battery change the issue remained, is it possible to recover/wake up the lost device so I don't have to delete it? 

## Screenshots
<img width="585" alt="Screenshot 2021-01-03 at 00 32 29" src="https://user-images.githubusercontent.com/782237/103468084-32d4bf00-4d5e-11eb-9985-30fd594ace6b.png">

## Environment
 - Host system: (**Raspberry** Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / **Home Assistent deCONZ Add-on** / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00) - latest
 - deCONZ version: (2.xx.yy) - latest
 - Device: (ConBee I / **ConBee II** / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / **no**) -- only relevant for ConBee I/II

**Comment by LeoeLeoeL** [comment]
It could be a problem for Tradfri devices.
With deconz 2.9 and the latest firmware my 3 extenders lost the connection at the same time. I had to pair them again.

**Comment by Mimiix** [comment]
What happens if you re-pair it?

**Comment by maxheadroom999** [comment]
I lost the connection to different lights / on-off switches.

Tradfri, Paulmann (MLI)

I can´t figure out when and why

I need to re-pair then, Groups are still the same, but the naming is gone sometimes

**Comment by riston** [comment]
I wasn't able to repair the device until the node was deleted after that everything worked again.
