### ISSUE TITLE
Aqara Sensor WSDCGQ11LM won't conenct after fresh install

### ISSUE THREAD

**Issue by hflocki** [dresden-elektronik/deconz-rest-plugin#4083]
## Describe the bug

 After a fresh install the Aqara sensor WSDCGQ11LM CMIT ID 2016DP6443 won't connect again

## Environment

 - Host system: Raspberry Pi 
 - Running method: Raspbian 
 - Firmware version: (26680700)
 - deCONZ version: (2.07.01)
 - Device: ConBee II 
 - Do you use an USB extension cable: no 
 - Is there any other USB or serial devices connected to the host system? If so: Which?
 - yes a CUL 848, a CUL 433, TRX device

## Additional context

fhem

**Comment by Metus88** [comment]
Did you tried:
Press and hold the "reset button" for 5 seconds... until blu led blinking... 
Release the "Reset button"
Every 1 second press (singol press) the reset button to keep alive the switch
Continue until the sensor is connected.

I hope it helps you

**Comment by hflocki** [comment]
Yes i have tried this.
But for those sensors you must press and hold the button for 10 seconds and than every 3 seconds. I have tried it many many times and for the timeperiod of 3 minutes.
Also i have tried another combinations of press and holding the button with different times. No way.

**Comment by AURELB87** [comment]
I have exactly the same problem. I just received my sensors AQARA and I think I have the same configuration than you!
I'm using the 'add-on Deconz' with my supervised HA.

**Comment by 0rsa** [comment]
I have also this issue.

**Comment by Mimiix** [comment]
Can you provide some logs?

**Comment by 0rsa** [comment]
I sucessfully linked my sensors using this method:
- Reset sensor, it will blink 3x
- Then it will turn on 1 time (I guess it sends a signal)
- Then it will turn on again one time when he receives an answer

At this moment, two different behaviours :
- The sensor sucessfully connects to Conbee, the sensor blinks again many times quickly
- The sensor does not blink, press again sensor button to send a new signal and receive a new answer and repeat this step to finally get a successfully connection (sometimes I need to press sensor button around 10x to etablish connection).

**Comment by hflocki** [comment]
The solution doesn't work for me.
I can't provide logs because i can't connect them

**Comment by Mimiix** [comment]
@hflocki You can provide logs from during pairing :)
