### ISSUE TITLE
Firmware update not showing on raspbee deCONZ

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#409]
I have installed the 2.05.01 update on the RaspBee here 3 days ago. But until now the update is not showing in the webapp or the Phosconapp. I saw somewhere that it could take some time before it would show up, but is this not a bit long now?

Wim

**Comment by manup** [comment]
Hmm strange, which firmware version is shown in *deCONZ > Help > About deCONZ*?

**Comment by wvuyk** [comment]
Version 0x26190500 here
![2018-02-10 12_23_58-raspbee raspberrypi - vnc viewer](https://user-images.githubusercontent.com/30700296/36061655-69356f9c-0e5d-11e8-9ac9-9575157d2823.png)

**Comment by manup** [comment]
It might be related to the firmware version state advertised by the online update service. I'll check this out, 2.05.02 with firmware version 0x261e0500 will be available soon.

**Comment by wvuyk** [comment]
2.05.02 showed the firmware update correctly again. Thanks!
