### ISSUE TITLE
Migrating from RaspBee (I or II) and ConBee II, Backup/Restore ConBee II

### ISSUE THREAD

**Issue by lukicsl** [dresden-elektronik/deconz-rest-plugin#4099]
## Describe the bug
I am running deCONZ inside docker. 
I started with using RaspBee I and buildup a network of 80+ nodes.
I later bought a ConBee II hoping to migrate the installation to ConBee II.
I failed multiple times and put the idea byside.
2 months ago I ordered RaspBee II and the migration was as: Shutdown Pi, replace the RB I for RB II, boot up, start the container, and it was done. Works as expected.

Yesterday the RB II stopped working as was not visible as a device under /dev.
This incident brought back the idea of migrating the installation on the CB II, having issues to do so. Even a simple backup CB II and restore CB II does not work.

## Steps to reproduce the behavior

I first installed back the RB I into the Pi and it picked up the installation without any issue: 

![image](https://user-images.githubusercontent.com/23736716/103539466-6ca9e080-4e98-11eb-99fb-f0e1f2a05689.png)

I made a fresh backup.
I shut down and removed RB I and install CB II. Booted up, started container, and loaded the backup, as a result, all nodes were visible but not connected to the coordinator:

![image](https://user-images.githubusercontent.com/23736716/103539597-a8dd4100-4e98-11eb-87bf-52fb93fd0733.png)

I have the feeling that the backup restore process does not work on CB II.
I have made a test on a fresh installation with CB II: I added 2 lights from scratch. The installation worked as expected. After back-restore the lights do not connect anymore to the coordinator:

![image](https://user-images.githubusercontent.com/23736716/103540161-93b4e200-4e99-11eb-8aee-4cf8fa25a743.png)

## Expected behavior

  Backup made fro RB I or RB II should be ok to be imported for CB I

## Screenshots

  in the description above

## Environment
 - Host system: (Raspberry Pi )
 - Running method: Marthoc Docker container
 - Firmware version: 264A0700
 - deCONZ version: 2.09.00 / 23.12.2020
 - Device: ConBee II / RaspBee I / RaspBee II
 - Do you use an USB extension cable: no

## deCONZ Logs

No logs
-->

## Additional context

no additional context

**Comment by lukicsl** [comment]
I have downloaded the sd-card image:

![image](https://user-images.githubusercontent.com/23736716/103566741-de971f80-4ec2-11eb-8681-f1b41f728b34.png)

And added my 2 test lights and created a test group. everything worked as expected.

Then I made a backup from this 2nd test configuration.

I then loaded the backup from the previous example created from the docker image and got the following result:

![image](https://user-images.githubusercontent.com/23736716/103567055-5feeb200-4ec3-11eb-88f6-a5f4ab156c6c.png)

More or less as expected

I loaded then the 2nd test configuration backup (from scratch created group and 2 light on the sd-card image installation) and got this result:

I had to wait for connect button to be visible:
![image](https://user-images.githubusercontent.com/23736716/103567356-f0c58d80-4ec3-11eb-8000-72ae00e98604.png)

And after connect:

![image](https://user-images.githubusercontent.com/23736716/103567464-2b2f2a80-4ec4-11eb-811f-9c594536ba3b.png)

one light lost its name no connection to the coordinator and the group has gone

![image](https://user-images.githubusercontent.com/23736716/103567585-5e71b980-4ec4-11eb-8509-d0c7bfbf74f9.png)


I do not have a spare RaspBee yet to state that it is a ConBee issue, but the backup restore process does not work. 

**This is really bad.**

**Comment by SwoopX** [comment]
Restore your backup. Then, as in your 2nd screenshot of the initial post, set `APS Use Ext PAN ID`, copy in the MAC of the `TC address`. That should do the trick.

Had pretty much the same while switching from Raspbee 1 to Raspbee 2 a couple of days before.

Please, do not fiddle around with your network config unless you exactly know what you're doing. Also, there's no need to re-pair devices!

**Comment by lukicsl** [comment]
I had a look at the logs and I see a segmentation fault at Step 9:

```
Segmentation fault (core dumped)
14:05:55:583 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 242, 4, x'f2e0a1610000012100012100', 1609855555 FROM devices WHERE mac = '14:b4:[marthoc/deconz] Starting deCONZ...

```

**Comment by Mimiix** [comment]
That's a nice mac Adress.

**Comment by Mimiix** [comment]
I'll ask Manuel to look at it.

**Comment by lukicsl** [comment]
The mack address I suppose was cut off by the core dump, the "[marthoc/deconz] Starting deCONZ..." is the restarted process starting putting out log entries.

**Comment by Mimiix** [comment]
Aah okay! Fair enough. 
Already found it strange 😂
