### ISSUE TITLE
Problem beim deconz Installieren (Raspian Desktop x86) Issue deconz install

### ISSUE THREAD

**Issue by Nastras** [dresden-elektronik/deconz-rest-plugin#411]
Hallo,

da ihr ja ein Deutsches Unternehmen seit versuche ich es mal auf Deutsch und bitte um Hilfe.

Ich habe bisher einen Raspee an meinem RaspberryPi im Betrieb gehabt dieser hat auch sehr gut funktioniert. Da ich etwas mehr Rechenleistung brauchte habe ich mir auf einem PC Raspian Desktop Stretch installiert und heute bei euch im Shop einen Conbee Stick bestellt.

Voller Vorfreude auf den Stick habe ich gerade probiert deconz zu installieren auf dem oben genannten Rechner. Leider bekomme ich folgende Fehlermeldung:

![db94b406-4118-4bd5-9850-b276e09c8663](https://user-images.githubusercontent.com/27686185/36077822-a5267754-0f6f-11e8-837a-2b64e7e4d22e.jpeg)

Hier noch Infos zum System:

 Operating System: Debian GNU/Linux 9 (stretch)
 Kernel: Linux 4.9.0-5-amd64
 Architecture: x86-64

Ich hoffe ihr könnt mir weiterhelfen?

Hello,

Since you are a German company since I try it in German and ask for help.

I have had a Raspee on my RaspberryPi in operation so far, it worked very well. Since I needed a bit more processing power I installed Raspian Desktop Stretch on a PC and ordered a Conbee stick from you today in the shop.

Full of anticipation for the stick I just tried deconz to install on the above mentioned calculator. Unfortunately I get the following error message:

I hope you can help me?

**Comment by wrmulf** [comment]
Wrong architecture. You need the [i386-binaries](https://www.dresden-elektronik.de/deconz/ubuntu/beta/deconz-2.05.02-qt5.deb) for your computer.

**Comment by Nastras** [comment]
Great, that works !

Where can I find an overview of the downloads for the different systems?

Thank you!!!
