### ISSUE TITLE
New HS1SA-M?

### ISSUE THREAD

**Issue by og9gjz567** [dresden-elektronik/deconz-rest-plugin#4114]
## Device
- Product name: HS1SA-M 
- Manufacturer: Heimann
- Model identifier: SMOK_YDLV10
- Device type :   - Sensor
## Screenshots
![grafik](https://user-images.githubusercontent.com/58255842/103770940-1e771780-5027-11eb-9798-d2a288610a24.png)
![grafik](https://user-images.githubusercontent.com/58255842/103770962-2c2c9d00-5027-11eb-9d7a-6cb1ff78d068.png)
![grafik](https://user-images.githubusercontent.com/58255842/103771508-2c796800-5028-11eb-9962-347023afbbf5.png)

**Comment by SwoopX** [comment]
You should have checked the supported devices list first. It is already supported.

**Comment by og9gjz567** [comment]
Thanks for your reply. But I won't get the battery status. Should I open a new issue?

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2373#issuecomment-595414912

That probably contains your answer.

Either way, this is not something we can fix but something specific to your issue.

**Comment by SwoopX** [comment]
It might taken 1-2 hrs to get any reading...
