### ISSUE TITLE
[Device Support Request] Climax Technology - Smoke Detector SD-8SCZBS

### ISSUE THREAD

**Issue by 3Doty** [dresden-elektronik/deconz-rest-plugin#4117]
## Device

- Product name: Smoke Detector SD-8SCZBS
- Manufacturer: ClimaxTechnology
- Model identifier: SD8SC_00.00.03.09TC
- Device type :  
  - Sensor
  - Siren

The device HW seems to be identical with the Bitron 902010/24: 
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/1063

## Screenshots

<img width="914" alt="Bildschirmfoto 2021-01-06 um 12 06 10" src="https://user-images.githubusercontent.com/76184056/103784746-9bf85300-503a-11eb-8e99-7fe1083012dc.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 12 07 09" src="https://user-images.githubusercontent.com/76184056/103784767-a4508e00-503a-11eb-8825-3bfb9ac08d3e.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 12 07 26" src="https://user-images.githubusercontent.com/76184056/103784797-aca8c900-503a-11eb-91a8-38539f42aae5.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 12 07 43" src="https://user-images.githubusercontent.com/76184056/103784834-b5999a80-503a-11eb-8f0a-11b0ec9c03ab.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 12 07 59" src="https://user-images.githubusercontent.com/76184056/103784851-bc281200-503a-11eb-92f2-ebf6fe9a70ce.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 12 08 15" src="https://user-images.githubusercontent.com/76184056/103784869-c21df300-503a-11eb-9795-5037c102cac6.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 12 08 25" src="https://user-images.githubusercontent.com/76184056/103784885-c813d400-503a-11eb-95aa-5c3048fcfce3.png">

**Comment by SwoopX** [comment]
Added in 2.10.00-beta
