### ISSUE TITLE
[Device Support Request] Sercomm - SZ-PIR02 Motion Detector

### ISSUE THREAD

**Issue by 3Doty** [dresden-elektronik/deconz-rest-plugin#4118]
## Device

- Product name: Sercomm - SZ-PIR02 Motion Detector
- Manufacturer: Sercomm Corp.
- Model identifier: GZ-PIR02
- Device type :  
  - Sensor

There was a similar request before, but the device not got added:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1863

## Screenshots

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 29 10" src="https://user-images.githubusercontent.com/76184056/103786973-55f0be80-503d-11eb-9b0b-8c4f202a1865.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 29 22" src="https://user-images.githubusercontent.com/76184056/103787004-5db06300-503d-11eb-92d5-acf7b14a6e9b.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 29 31" src="https://user-images.githubusercontent.com/76184056/103787024-63a64400-503d-11eb-8857-dbc90e7d104b.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 29 39" src="https://user-images.githubusercontent.com/76184056/103787041-6a34bb80-503d-11eb-81ee-518dd02dcc8c.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 29 48" src="https://user-images.githubusercontent.com/76184056/103787071-70c33300-503d-11eb-9c9c-939606fa08cf.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 30 07" src="https://user-images.githubusercontent.com/76184056/103787094-791b6e00-503d-11eb-9de5-93d8b00308ea.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 30 24" src="https://user-images.githubusercontent.com/76184056/103787118-80427c00-503d-11eb-85d2-ee4d9da2ffc0.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 30 40" src="https://user-images.githubusercontent.com/76184056/103787144-87698a00-503d-11eb-98ae-44e957670672.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 30 52" src="https://user-images.githubusercontent.com/76184056/103787174-8e909800-503d-11eb-9253-222105d94a23.png">

**Comment by SwoopX** [comment]
Can you please read the attributes from the power configuration cluster and provide the screenshot? Make sure the device is awake prior to reading. To wake it, push the physical button on the device 1-2 seconds before reading.
