### ISSUE TITLE
[Device Support Request] Sercomm - SZ-WTD02 Water Sensor

### ISSUE THREAD

**Issue by 3Doty** [dresden-elektronik/deconz-rest-plugin#4119]
## Device

- Product name: Sercomm - SZ-WTD02 Water Sensor
- Manufacturer: Sercomm Corp.
- Model identifier: SZ-WTD02N_CAR
- Device type : 
  - Sensor

## Screenshots

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 56 22" src="https://user-images.githubusercontent.com/76184056/103789984-ec72af00-5040-11eb-92e0-d424f67a62be.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 56 32" src="https://user-images.githubusercontent.com/76184056/103790009-f4325380-5040-11eb-8602-8e3b456ef3f9.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 56 38" src="https://user-images.githubusercontent.com/76184056/103790028-fbf1f800-5040-11eb-8d96-2238e5511e52.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 56 45" src="https://user-images.githubusercontent.com/76184056/103790049-02806f80-5041-11eb-8931-e0c16d4d339d.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 56 53" src="https://user-images.githubusercontent.com/76184056/103790081-09a77d80-5041-11eb-8357-8d95cc8f8aed.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 57 03" src="https://user-images.githubusercontent.com/76184056/103790103-1035f500-5041-11eb-81c1-397925e52131.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 57 15" src="https://user-images.githubusercontent.com/76184056/103790123-162bd600-5041-11eb-9b4c-7823613bf856.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 57 28" src="https://user-images.githubusercontent.com/76184056/103790139-1af08a00-5041-11eb-9ae4-ddeafafee069.png">

<img width="909" alt="Bildschirmfoto 2021-01-06 um 16 57 44" src="https://user-images.githubusercontent.com/76184056/103790163-217f0180-5041-11eb-8ea5-ed7c5152c76c.png">

**Comment by SwoopX** [comment]
Can you please read the attributes from the power configuration cluster and provide the screenshot? Make sure the device is awake prior to reading. To wake it, push the physical button on the device 1-2 seconds before reading.

**Comment by SwoopX** [comment]
Merged
