### ISSUE TITLE
Switch Tuya _TZ3000_y9xprg33 - TS0011

### ISSUE THREAD

**Issue by bsfaxi** [dresden-elektronik/deconz-rest-plugin#4120]
## Device

- Product name: Tuya.
- Manufacturer: _TZ3000_y9xprg33.
- Model identifier: TS0011.
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/23717629/103818884-9ebe6c80-5069-11eb-956c-50d1d28fccdb.png)

![image](https://user-images.githubusercontent.com/23717629/103818791-733b8200-5069-11eb-9603-5ba3e69b686f.png)

![image](https://user-images.githubusercontent.com/23717629/103818916-b269d300-5069-11eb-8791-724e330e7604.png)

Unfortunately, the device does not appear in the Phoscon App as a light like the other Tuya switches, neither in Home Assistant via the integration.
Here is the On/Off cluster:
![image](https://user-images.githubusercontent.com/23717629/103819016-ee049d00-5069-11eb-960f-f3a2ac2df266.png)

Thanks in advance for your great support as always.

**Comment by Mimiix** [comment]
@Smanar

**Comment by bsfaxi** [comment]
I have deselected and then re-selected the "read" buttons. deCONZ has recognized the device and affected him a new name!
It's now operational.
 
![image](https://user-images.githubusercontent.com/23717629/103831570-a3405080-507c-11eb-82d8-310b7abb82d5.png)

Thanks
