### ISSUE TITLE
Aqara smart switch mini not available in entities

### ISSUE THREAD

**Issue by dzurda007** [dresden-elektronik/deconz-rest-plugin#4127]
## Device

- Product name: Smart switch mini - Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types.  
  - Switch

## Screenshots

Hi, Smart switch is not available for me in entities and then not available in Homekit integration as well. Is that a bug on my side? I can see only smart switch battery level in entities.

**Comment by Mimiix** [comment]
This is:
- Not the correct use of a template
- Not the correct template itself.
Closing.
