### ISSUE TITLE
Alcantara 2 Heater/Thermostat

### ISSUE THREAD

**Issue by NicoB35** [dresden-elektronik/deconz-rest-plugin#4129]
## Device

- Product name: Acova Alcanrata 2
- Manufacturer:ZHENDER GROUP VAUX ANDIGNY
- Model identifier: ALCANTARA2 D1.00P1.01Z1.00
- Device type : 
   Thermostat
 

## Screenshots

![BasicCluster1](https://user-images.githubusercontent.com/77122560/103936719-1226b380-5128-11eb-9926-2ee3a9934297.JPG)
![Capture](https://user-images.githubusercontent.com/77122560/103936720-12bf4a00-5128-11eb-9159-fe930d57e060.JPG)
![node](https://user-images.githubusercontent.com/77122560/103936721-1357e080-5128-11eb-8dd2-7660e4c6b014.JPG)
![ThermostatCluster](https://user-images.githubusercontent.com/77122560/103936725-1357e080-5128-11eb-82fd-53caa8bb1577.JPG)
![LevelControlSwitch](https://user-images.githubusercontent.com/77122560/103937162-a7c24300-5128-11eb-9c74-f2b7a4843304.JPG)
![Occupancy](https://user-images.githubusercontent.com/77122560/103937166-a85ad980-5128-11eb-97c7-dd9722ee9e73.JPG)

**Comment by SwoopX** [comment]
We'd need the remaining thermostat cluster attributes from attribute 0x0012 downwards. I'm afraid you'll probably need to manually read each of them via a double click on the value.

**Comment by NicoB35** [comment]
Thank you for answering

When i Read all the thermostat cluster, only :

0x0000
0x0002
0x0003
0x0004
0x0010
0x0011
0x0012
0x0014
0X001B
0x001C
0x001E
0x0029
0x0030

remain black (not greyed)
I hope it will help.


![Capture1](https://user-images.githubusercontent.com/77122560/105007608-7dca2400-5a38-11eb-9f50-d3ae8eba330a.JPG)
![Capture2](https://user-images.githubusercontent.com/77122560/105007610-7e62ba80-5a38-11eb-8ed0-9942161e081f.JPG)
![Capture3](https://user-images.githubusercontent.com/77122560/105007611-7e62ba80-5a38-11eb-99a1-53a5b4b39c5e.JPG)
![Capture4](https://user-images.githubusercontent.com/77122560/105007613-7efb5100-5a38-11eb-9896-7560b6ea6d7d.JPG)
![Capture5](https://user-images.githubusercontent.com/77122560/105007615-7efb5100-5a38-11eb-8f76-3caf4e1b0832.JPG)
![Capture6](https://user-images.githubusercontent.com/77122560/105007616-7f93e780-5a38-11eb-8a79-7502a78c0b76.JPG)
![Capture9](https://user-images.githubusercontent.com/77122560/105007617-7f93e780-5a38-11eb-8973-abdc28e41843.JPG)

**Comment by SwoopX** [comment]
Have you read all the attributes individually as requested? Doesn't look like it.

**Comment by NicoB35** [comment]
Sorry for my bad english and misunderstanding
When i double click on (for example) 0x0012 (Occupied Heating Setpoint)
I get a little window : Attribute info
The read button gives me the value (example 1900 for 19,00°c)
The read config returns "not found"
![Capture](https://user-images.githubusercontent.com/77122560/105040597-4ff9d500-5a62-11eb-9818-f68ceee2488b.JPG)

I think i do something wrong and that you wait for something else
Could you explain me where is my mistake please, or give me the way to get the values you need.
Thank you for your time

**Comment by NicoB35** [comment]
To add information,
I read the REST-API wiki yesterday and tried to find my heaters, nothing in lights / sensors
I also read various post in device request, I saw the same request you made : "We'd need the remaining thermostat cluster attributes from attribute 0x0012 downwards. I'm afraid you'll probably need to manually read each of them via a double click on the value."
Unfortunately, no answer so i couldn't use this request to get the values needed.I need a little walkthrough
I hope it will help

**Comment by SwoopX** [comment]
> When i double click on (for example) 0x0012 (Occupied Heating Setpoint)
> I get a little window : Attribute info
> The read button gives me the value (example 1900 for 19,00°

This is exactly what needs to be done, press the `read` button there. `read config` is irrelevant, at least for now. After the value has been read, the value will be automatically updated in the attribute overview. If an attribute is not found on the device, the read will fail and be grayed out (which is fine and the info we need).

**Comment by NicoB35** [comment]
I think I have the values needed :


0x0012   Occupied heating setpoint           s16          rw    1900

0x0014   Unoccupied Heating setpoint      S16          rw    1550

0x001B   Control Sequence of Operation   enum8    rw    Heating Only (Cooling only / Colling with Reheat / Colling and Heating 4- pipes / Colling and Heating 4-pipes with Reheat)

0x001C   System Mode                              enum8     rw     Auto     (Off / Cool / Heat / Emergency Heating / Precooling / Fan only / Dry / Sleep

0x001E   Thermostat Running Mode         enum8     r     Heat      (Cool / Off)

0x0029   Thermostat Running State          bmp16     r      0x0001   (see capture 0x0029.jpg)
![0x0029](https://user-images.githubusercontent.com/77122560/105215133-2d92b500-5b51-11eb-8b9c-6bcdc2bcb25f.JPG)

0x0030   Setpoint Change Source             enum8     r      Zigbee    (Manual / Scedule)


I hope it will help

**Comment by NicoB35** [comment]
Hello,
The request is still in "waiting for info" status.
I can provide more info if needed.
Don't hesitate to ask, will give them quickly.

Have a good day.

**Comment by Mimiix** [comment]
@SwoopX

**Comment by SwoopX** [comment]
I guess that is sufficient for now, thanks
