### ISSUE TITLE
Tobular Motor Zemismart ZM25TQ Zigbee- new version _TZE200_fzo2pocs

### ISSUE THREAD

**Issue by jameshirka** [dresden-elektronik/deconz-rest-plugin#4132]
## Device
Product name: ZM25TQ
Manufacturer: _TZE200_fzo2pocs
Model identifier: TS0601
Device type : Roll-motor/cover

## Screenshots
![_TZE200_fzo2pocs basic cluster](https://user-images.githubusercontent.com/532602/103977695-e5c57280-51cd-11eb-8be1-71fbda343330.JPG)

This is the same device externally as:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3161
My device has the exact same markings on it as the one mentioned in the issue.

**Comment by Smanar** [comment]
Arf bad luck "smart plug" like switches, not realy good.
You haven't 3 lights entry created when trying to integrate it ?

I need too, the manufacture number on the node info panel pls.

**Comment by jameshirka** [comment]
> Arf bad luck "smart plug" like switches, not realy good.
> You haven't 3 lights entry created when trying to integrate it ?
> 
> I need too, the manufacture number on the node info panel pls.

No, it only creates a single entity which identifies as a smart plug but also a thermostat.
![image](https://user-images.githubusercontent.com/532602/104075741-d5fa6c80-5267-11eb-8c7f-3a804022712c.png)


Node info screenshot:
![image](https://user-images.githubusercontent.com/532602/104075714-be22e880-5267-11eb-9af1-325c9e5656fe.png)

Please let me know if there is anything else you need.

**Comment by Smanar** [comment]
Do you know how to compile the code to make a try ?

```
sudo apt install deconz-dev
git clone --branch ZM25TQ https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by jameshirka** [comment]
> Do you know how to compile the code to make a try ?
> 
> ```
> sudo apt install deconz-dev
> git clone --branch ZM25TQ https://github.com/Smanar/deconz-rest-plugin.git
> cd deconz-rest-plugin
> qmake && make
> sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
> ```

Thanks Smanar.

Sorry it took so long, I got another PI up and running to not have to play with the container that Deconz runs in for HA.

I gave it a shot, unfortunately, now they are seen as fairy lights/ smart plugs:
![image](https://user-images.githubusercontent.com/532602/104117937-2dd4c880-5379-11eb-9697-494b32582d1a.png)

When I hit the API I get:
`    "2": {
        "etag": "77a694d6805b4fa35c415f070a57c6cf",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2021-01-10T08:20Z",
        "manufacturername": "_TZE200_fzo2pocs",
        "modelid": "TS0601",
        "name": "Smart plug 2",
        "state": {
            "alert": "none",
            "on": false,
            "reachable": true
        },
        "swversion": null,
        "type": "Smart plug",
        "uniqueid": "5c:02:72:ff:fe:94:31:fe-01"
    },`

Any thoughts/ ideas?

**Comment by Smanar** [comment]
This is more normal for me.
Can you try to make a second inclusion but without deleting the previous devices ?

If I m right you will have more field on the one with the uniqueid  finishing by "-01"

**Comment by jameshirka** [comment]
You're 100% correct.

I now get (after moving it up and down by doing puts on the lift)

`    "2": {
        "etag": "41af9ec875f96039afa2b135038c1fe0",
        "hascolor": false,
        "lastannounced": "2021-01-10T10:20:47Z",
        "lastseen": "2021-01-10T10:30Z",
        "manufacturername": "_TZE200_fzo2pocs",
        "modelid": "TS0601",
        "name": "Smart plug 2",
        "state": {
            "alert": "none",
            "bri": 254,
            "lift": 100,
            "on": true,
            "open": false,
            "reachable": true
        },
        "swversion": null,
        "type": "Window covering device",
        "uniqueid": "5c:02:72:ff:fe:94:31:fe-01"
    },`

Is there anything else I should be checking?
Also is there a way of setting if the roller is reverse or not?
Ie this motor is installed on the left with the blind rolling forward which unfortunately means up on the remote puts the blind down and vice-e-versa.
Where as the rest of my motors are installed on the right and the remotes work the correct way.

**Comment by Smanar** [comment]
Yep there is an API command to reserse side.

`PUT, PATCH /api/<apikey>/lights/<id> with {"reverse":true}`

I will check later if If I can find a way to prevent the 2 others device creation, but will be complicated because of the device type "smart plug".

**Comment by jameshirka** [comment]
Thanks Smanar.

This is ready to go when you're ready to do the pull request.

Thanks for all your help.

**Comment by Smanar** [comment]
OK, so I have checked, I have no way to detect this device and differentiate from switches.
Will be possible in a future deconz version, but not for the moment.

For the moment I think you can delete the 2 other fake entries ?

It s like you want I can make the PR as it if you want ?

**Comment by jameshirka** [comment]
Please make a PR as is.
I'm happy to have it working today and the new device JSON based DDF might be the right time to look at the multiple entities issue.

Thanks.

**Comment by shlomki** [comment]
Hi @Smanar, I'm using the same device and need some help with setting the up & down limits. I saw that the Tuya app allows to save the up & down positions (as well as a middle position but there's only so much that I could hope for).
I was wondering if there's a chance that an API command could help with that, just like the reverse command?

How can I investigate if there are any other secret commands such as the "reverse" command you've found?
thanks!

**Comment by Smanar** [comment]
Your device is the "_TZE200_fzo2pocs" ?
Because I m not sure this device use a tuya command to set max/min position ?

**Comment by shlomki** [comment]
Yes, that's exactly the device I have.
I saw that `{"calibration": "true"}` is supported in the API but I couldn't figure out how to use it.
The manual says there are two options to calibrate - using a remote and using the app. I don't have a remote... so I'm trying to use deconz. 
You can see the screenshot from their app allows to set up, down, and middle.
![tuya_cover_set_position](https://user-images.githubusercontent.com/34508546/141514424-42d73259-619e-46d5-84d8-18fb5130b177.jpeg)

**Comment by Smanar** [comment]
This command is for device that have the covering cluster.
I have take a look again, and I don't find calibration command for covering that use the tuya cluster.

I m searching on other zigbee project but not more command.

**Comment by shlomki** [comment]
Thanks for looking into it again, it's interesting that the OP doesn't have the window covering cluster - but I do.
For some reason though, it's read only.
![image](https://user-images.githubusercontent.com/34508546/141527942-b8861e10-c442-4337-8e0e-dbaeee9dfee3.png)

**Comment by Smanar** [comment]
Ok, so you have a new version ....

They are not read only, read only can be read, but disabled, it mean generaly the device don't support them.
But have you scroll down the attributes lists (the tab) there is more under, to be sure all are disabled.

**Comment by Drapiece** [comment]
> 좋아, 그래서 당신은 새로운 버전이 있습니다 ....
> 
> 그들은 읽기 전용이 아니라 읽기 전용이 될 수 있지만 비활성화되어 있습니다. 일반적으로 장치가 지원하지 않는다는 것을 의미합니다. 그러나 속성 목록(탭)을 아래로 스크롤하여 모두 비활성화되었는지 확인하십시오.

hello, I'm getting a lot of help from you. (_TZ3000_okaz9tjs, _TZ3000_r6buo8ba)

I recently purchased a tublar motor.
Unfortunately this model. (TZE200_fzo2pocs)

I am using deconz built in hassos.

It seems that the code compile mentioned above is not applicable.
(SUDO APT Install Deconz-Dev
git clone --branch zm25tq https://github.com/smanar/deconz-trugin.git
CD Deconz-REST-PLUGIN
QMake & & Make
sudo cp ../libde_rest_plugin.so/usr/shaer/deconz/plugins)

Are there exists DDF in this environment?
Thank you.

**Comment by Drapiece** [comment]
> 좋아, 당신은 새로운 버전을 출시했습니다 ....
> 
> 낭독이 낭독의 전당에 올랐습니다. 기술이 지원하지 않습니다. 이 목록(프론트)을 먼저 확인하십시오.

but, I find this.

motor STOP
![image](https://user-images.githubusercontent.com/121592/187151431-98e65c8c-4563-4bf1-94a5-8f84071218bc.png)

motor DOWN
![image](https://user-images.githubusercontent.com/121592/187151548-7a91af2c-1541-4100-89c8-c90cba260cc3.png)

motor UP
![image](https://user-images.githubusercontent.com/121592/187151594-6b099ad3-5d1e-413d-93bb-6ad37ed206fc.png)

I tried to create a DDF using the above method,
but I don't know how to insert it.
If there is only UP DOWN STOP, it would be possible to automate somehow in homeassistant.
Please help me again.
thank you!

**Comment by Drapiece** [comment]
> hello, I'm getting a lot of help from you. (_TZ3000_okaz9tjs, _TZ3000_r6buo8ba)
> 
> I recently purchased a tublar motor. Unfortunately this model. (TZE200_fzo2pocs)
> 
> I am using deconz built in hassos.
> 
> It seems that the code compile mentioned above is not applicable. (SUDO APT Install Deconz-Dev git clone --branch zm25tq https://github.com/smanar/deconz-trugin.git CD Deconz-REST-PLUGIN QMake & & Make sudo cp ../libde_rest_plugin.so/usr/shaer/deconz/plugins)
> 
> Are there exists DDF in this environment? Thank you.

**Comment by Smanar** [comment]
It s not possible yet using DDF for Tuya covering.
So to use a new device the only way is adding it using c++ code, and the PR will be probably refused, so you need to make that only for you.

Can mimic one of them
```

    {"_TYST11_wmcdj3aq", "mcdj3aq", "Zemismart", "Tuya_COVD ZM25TQ"},
    {"_TZE200_wmcdj3aq", "TS0601", "Zemismart", "Tuya_COVD ZM25TQ"},
    {"_TZE200_fzo2pocs", "TS0601", "Zemismart", "Tuya_COVD ZM25TQ"},
    {"_TYST11_xu1rkty3", "u1rkty3", "Smart Home", "Tuya_COVD DT82LEMA-1.2N"},
    {"_TZE200_xuzcvlku", "TS0601", "Zemismart", "Tuya_COVD M515EGB"},
    {"_TZE200_rddyvrci", "TS0601", "Moes", "Tuya_COVD AM43-0.45/40-ES-EZ(TY)"},
    {"_TZE200_zah67ekd", "TS0601", "MoesHouse / Livolo", "Tuya_COVD AM43-0.45-40"},
    {"_TZE200_nogaemzt", "TS0601", "Tuya", "Tuya_COVD YS-MT750"},
    {"_TZE200_zpzndjez", "TS0601", "Tuya", "Tuya_COVD DS82"},
    {"_TZE200_cowvfni3", "TS0601", "Zemismart", "Tuya_COVD ZM79E-DT"},
    {"_TZE200_5zbp6j0u", "TS0601", "Tuya/Zemismart", "Tuya_COVD DT82LEMA-1.2N"},
    {"_TZE200_fdtjuw7u", "TS0601", "Yushun", "Tuya_COVD YS-MT750"},
    {"_TZE200_bqcqqjpb", "TS0601", "Yushun", "Tuya_COVD YS-MT750"},
    {"_TZE200_nueqqe6k", "TS0601", "Zemismart", "Tuya_COVD M515EGB"},
    {"_TZE200_iossyxra", "TS0601", "Zemismart", "Tuya_COVD Roller Shade"},
```

For most device you just need to edit product_match.cpp file.

**Comment by Drapiece** [comment]
> It s not possible yet using DDF for Tuya covering. So to use a new device the only way is adding it using c++ code, and the PR will be probably refused, so you need to make that only for you.
> 
> Can mimic one of them
> 
> ```
> 
>     {"_TYST11_wmcdj3aq", "mcdj3aq", "Zemismart", "Tuya_COVD ZM25TQ"},
>     {"_TZE200_wmcdj3aq", "TS0601", "Zemismart", "Tuya_COVD ZM25TQ"},
>     {"_TZE200_fzo2pocs", "TS0601", "Zemismart", "Tuya_COVD ZM25TQ"},
>     {"_TYST11_xu1rkty3", "u1rkty3", "Smart Home", "Tuya_COVD DT82LEMA-1.2N"},
>     {"_TZE200_xuzcvlku", "TS0601", "Zemismart", "Tuya_COVD M515EGB"},
>     {"_TZE200_rddyvrci", "TS0601", "Moes", "Tuya_COVD AM43-0.45/40-ES-EZ(TY)"},
>     {"_TZE200_zah67ekd", "TS0601", "MoesHouse / Livolo", "Tuya_COVD AM43-0.45-40"},
>     {"_TZE200_nogaemzt", "TS0601", "Tuya", "Tuya_COVD YS-MT750"},
>     {"_TZE200_zpzndjez", "TS0601", "Tuya", "Tuya_COVD DS82"},
>     {"_TZE200_cowvfni3", "TS0601", "Zemismart", "Tuya_COVD ZM79E-DT"},
>     {"_TZE200_5zbp6j0u", "TS0601", "Tuya/Zemismart", "Tuya_COVD DT82LEMA-1.2N"},
>     {"_TZE200_fdtjuw7u", "TS0601", "Yushun", "Tuya_COVD YS-MT750"},
>     {"_TZE200_bqcqqjpb", "TS0601", "Yushun", "Tuya_COVD YS-MT750"},
>     {"_TZE200_nueqqe6k", "TS0601", "Zemismart", "Tuya_COVD M515EGB"},
>     {"_TZE200_iossyxra", "TS0601", "Zemismart", "Tuya_COVD Roller Shade"},
> ```
> 
> For most device you just need to edit product_match.cpp file.

thank you for your support!!
but, It can't be on builtin hassos.

suddenly??, tublar motor shown me normal status.
![image](https://user-images.githubusercontent.com/121592/187360988-76725d6b-e412-4a3e-8188-6715e586055f.png)
Temporarily available for use.

And, I ordered tuya zigbee gateway.
first, tuya zigbee gateway connect to tublar motor. and homeassistant connect tuya cloud.
I think it will be can so really normal status and move.

second, I will waiting stable update from deconz.
it is bestest action now. right?

thank you!!

**Comment by Smanar** [comment]
Yes, because the future will be with DDF, there is a DDF for TRV using the Tuya cluster that wait for validation, one time this one will be included, will be the covering turn, but can take lot of time.
