### ISSUE TITLE
Müller-Licht non color scene controller

### ISSUE THREAD

**Issue by helmutGitHub** [dresden-elektronik/deconz-rest-plugin#4134]
## Device

- Product name: mobile switch from Tint Starter Set
- Manufacturer: NA (Müller-Licht)
- Model identifier: NA 
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots
https://www.mueller-licht.de/produktinformationen/artikel/404015/
![Screenshot_20210108_115720](https://user-images.githubusercontent.com/26544542/104011386-4e045c00-51ae-11eb-8197-cc2687d7e777.png)
![Screenshot_20210108_121059](https://user-images.githubusercontent.com/26544542/104011466-6eccb180-51ae-11eb-8b4c-5aab9a514407.png)
![Screenshot_20210108_115510](https://user-images.githubusercontent.com/26544542/104011856-134ef380-51af-11eb-9f0e-827c7a8667c9.png)

**Comment by Mimiix** [comment]
Missing screenshots. Please provide all cluster screenshots.

**Comment by helmutGitHub** [comment]
![Screenshot_20210108_132843](https://user-images.githubusercontent.com/26544542/104016164-05e93780-51b6-11eb-9b37-97ec14a0d25b.png)
![Screenshot_20210108_132902](https://user-images.githubusercontent.com/26544542/104016180-100b3600-51b6-11eb-8861-f739bdd79fac.png)
![Screenshot_20210108_132915](https://user-images.githubusercontent.com/26544542/104016189-1a2d3480-51b6-11eb-935f-9b1595921dfd.png)
![Screenshot_20210108_132930](https://user-images.githubusercontent.com/26544542/104016194-1ef1e880-51b6-11eb-92ac-4b4b6dee1cae.png)
![Screenshot_20210108_132945](https://user-images.githubusercontent.com/26544542/104016200-244f3300-51b6-11eb-9843-e907fb33d794.png)
![Screenshot_20210108_133000](https://user-images.githubusercontent.com/26544542/104016214-2a451400-51b6-11eb-96ce-95c10ec7ca15.png)
![Screenshot_20210108_133009](https://user-images.githubusercontent.com/26544542/104016227-303af500-51b6-11eb-9b91-f2df67b3fdce.png)
![Screenshot_20210108_133019](https://user-images.githubusercontent.com/26544542/104016233-34671280-51b6-11eb-9cef-c2aab86763b8.png)
![Screenshot_20210108_133029](https://user-images.githubusercontent.com/26544542/104016242-39c45d00-51b6-11eb-8b0e-d794d900fcfb.png)

**Comment by duffbeer2000** [comment]
Hi Helmut, please read the wiki: [Request-Device-Support](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support)

The important thing: 

> **Please note that at least "Manufacturer Name" and "Model Identifier" must be populated with data (therefore, must not be empty), otherwise that information will not be usable.** For battery powered devices, after pressing read it is required to wake-up the device by pressing a button or any other means of interaction.

**Comment by helmutGitHub** [comment]
Sorry for missing this information. I didn't know of the part with "read". Is there anything else missing?

![Screenshot_20210108_175124](https://user-images.githubusercontent.com/26544542/104042019-2fb45580-51da-11eb-926a-d9e4b113da25.png)

**Comment by 1100101** [comment]
I too have this device and would like to use the remote with deCONZ.
@Mimiix Is there still information missing that I may provide?

**Comment by Mimiix** [comment]
> I too have this device and would like to use the remote with deCONZ.
> @Mimiix Is there still information missing that I may provide?

I totally missed the added screens..

My apologies!

**Comment by 1100101** [comment]
@Mimiix I don’t want to nit-pick, but shouldn’t you remove the “incomplete issue” label here?

**Comment by Mimiix** [comment]
Wait what.

I removed it 😕

**Comment by Mimiix** [comment]
It better be gone now.

**Comment by 1100101** [comment]
Thanks, all fine now :)

**Comment by helmutGitHub** [comment]
@Mimiix, can you  make a rough estimate how long it takes to include this switch?

**Comment by Mimiix** [comment]
Whenever a devs feels like it. @helmutGitHub . Switches are hard to implement and devs often want a hands on device to make sure to implement it correctly.

**Comment by helmutGitHub** [comment]
@Mimiix, if you wish, i can provide you with a switch.

**Comment by Mimiix** [comment]
> @Mimiix, if you wish, i can provide you with a switch.

I'm not a dev. Perhaps @SwoopX or @ebaauw is interested

**Comment by helmutGitHub** [comment]
@SwoopX, @ebaauw, are you interested?

**Comment by ebaauw** [comment]
Sorry, missed this one.  I’m happy to have a look at the switch, please PM me on Discord.

**Comment by ebaauw** [comment]
Received the remote, thanks, @helmutGitHub.  Apparently, already quite a few issues for this device; linking them to here.

Device seems quite standard: client _On/Off_, _Level Control_, and _Scenes_clusters.  It doesn't send anything, until these are bound.  _OTAU_ cluster seems to be implemented; no _Power Configuration_ and the _Power Descriptor_ doesn't seem to report the battery level (value 0b1100).

The _On_ button alternates between sending _On_ and _Off_ on release.  No distinction between short vs long press.  Will be exposed as 1002.

The _DimUp_ and DimDown_ buttons send _Step_ on short press/release; _Move_ on hold; and _Stop_ on release.  Will be exposed as 2002, 3002, 2001/2003 and 3001/3003.

The _Favorite_ button (manual uses American spelling) sends _Recall Scene_ on press/release, and _Store Scene_ when held for 5 seconds.  The commands are sent to the bound group.  The scene seems to be hard-coded to 4003/01.  Probably best supported as 4002 and 4003.

The server _ZLL Commissioning_ cluster reports four groups, 0x05ae to 0x05b1, but they don't seem to be used for anything (maybe when touchlinking?).

**Comment by helmutGitHub** [comment]
You are really fast and so i'm looking forward for the implementation. Until then, thank you very much.

**Comment by ebaauw** [comment]
Above commit should add support.  The device is a bit wacky, it might take some time after pairing before all the bindings are setup.  Also when holding the DimUp or DimDown button, it sends x002 on press, x001 on hold and x003 on release.  Basically it will always register a short press before a long press.  The Scene button sends 4002 on press/release and 4003 on hold.

**Comment by helmutGitHub** [comment]
Thank you very much, Erik.

**Comment by gforums** [comment]
Thanks also from my side for the fast implementation, appreciate!

**Comment by gforums** [comment]
Switched to newest Beta some minutes ago.
Remote is recognized and visible for me in deconz openhab.
Trigger events work as described for me.

Thanks for the implementation again, being an even more customer now :)
