### ISSUE TITLE
Tuya TS0601 thermostat: “lastupdate” is empty

### ISSUE THREAD

**Issue by TheNON75** [dresden-elektronik/deconz-rest-plugin#4147]
## Describe the bug
Whenever a config or state update occurs, the "lastupdate" information is always empty.

## Steps to reproduce the behavior
Check rest api or websocket
(Referring to the developer, this part is not developed yet)

## Expected behavior
 filled with correct date time

## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Smanar** [comment]
Yep , my fault.
I think there is this bug in all tuya device.

Someone can compile a modification to make a test ?

**Comment by Smanar** [comment]
Ok , have made some tries with @machielw, the problem is found, will be corrected when I will add his device for next beta I think.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3183

**Comment by TheNON75** [comment]
Hi @Smanar,

Thanks for the good news, great work!

**Comment by Smanar** [comment]
And from his test, it solve too a "not reachable" bug.
It s enabled only for him ATM, but will add it for other command too.

**Comment by TheNON75** [comment]
Excellent, @Smanar!
What was the not reachable bug in details?

**Comment by Smanar** [comment]
I think it was the same problem, the "lastupdate " was never updated, and after some time the device was marked as "unreachable".

![image](https://user-images.githubusercontent.com/20505783/103315202-3ba75700-4a25-11eb-904c-c8672424d3f0.png)

**Comment by easybeat** [comment]
> I think it was the same problem, the "lastupdate " was never updated, and after some time the device was marked as "unreachable".
> 
> ![image](https://user-images.githubusercontent.com/20505783/103315202-3ba75700-4a25-11eb-904c-c8672424d3f0.png)

Oh this sounds like a similar problem on TS0601 Radiator TRV. I lose connection with this all the time...is this possible?

**Comment by Smanar** [comment]
Depend of you realy loose the connxion or just have it marked as unreacheable ?
If you still receive information like temperature, yep I think it s same problem, we have soon finished the siren, I will put a link for tries here.

**Comment by easybeat** [comment]
@Smanar I've just updated to 2.09.02 and it looks like on my TS0601 TRV the last updated is still null:

![Screenshot 2021-02-09 124118](https://user-images.githubusercontent.com/37217887/107358789-20277580-6ad4-11eb-8514-eb22afcf71a2.png)

This is a screenshot from ioBroker. Is there a way to check this in Deconz App?

Thanks

**Comment by Smanar** [comment]
The last update issue is normaly corrected here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4379 (not yet validated)

But I have made a mistake for some TRV on a previous PR too, what is your manufacture name ?

**Comment by easybeat** [comment]
> The last update issue is normaly corrected here #4379 (not yet validated)
> 
> But I have made a mistake for some TRV on a previous PR too, what is your manufacture name ?

![Screenshot_20210209-174534](https://user-images.githubusercontent.com/37217887/107397143-b1134680-6afe-11eb-9502-aa8bf7116bb9.png)

**Comment by Smanar** [comment]
Arf bad luck :(, I m asking to manup if I can correct it, but ATM you will probably have problem with preset/mode request if you use them.
In worst situation the corrective will be in the beta, just after the stable, the code is already in PR list.

**Comment by easybeat** [comment]
Hey, no problem!! It can wait.

Thanks for your work.

**Comment by TheNON75** [comment]
Unstale

**Comment by Smanar** [comment]
This bug is still present ?

**Comment by TheNON75** [comment]
I had to revert from the latest version as there was at least one other issue with it, so I cannot tell right now. 
In which stable is it fixed? Sorry it is unclear from the above posts.

**Comment by Smanar** [comment]
The last one is enought, long time this issue is "supposed" to be resolved.

**Comment by TheNON75** [comment]
I confirm it works in the latest. 
(I might need to open a new issue for the "lastseen")

Thank you very much
