### ISSUE TITLE
Drayton Wiser Radiator Thermostat

### ISSUE THREAD

**Issue by fireblade70** [dresden-elektronik/deconz-rest-plugin#4148]
## Device

- Product name: Drayton Wiser Radiator Thermostat.
- Manufacturer: Schneider Electric
- Model identifier: iTRV
- Device type : Thermostat

## Screenshots

![image](https://user-images.githubusercontent.com/77207715/104106161-88075800-52ab-11eb-832d-e210f3b61443.png)
![image](https://user-images.githubusercontent.com/77207715/104106172-a53c2680-52ab-11eb-8417-08153646eb53.png)
![image](https://user-images.githubusercontent.com/77207715/104106175-b5ec9c80-52ab-11eb-80f0-d0ce79b8e754.png)

**Comment by SwoopX** [comment]
Required screenshots as per request template are missing.

**Comment by fireblade70** [comment]
Can you please clarify which screenshot is missing? I followed the instructions as per [Instructions](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support). I see them clearly in my original post?
PS apologies for the delay in responding.

**Comment by fireblade70** [comment]
> Can you please clarify which screenshot is missing? I followed the instructions as per [Instructions](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support). I see them clearly in my original post?
> PS apologies for the delay in responding.

**Comment by Mimiix** [comment]
The cluster screenshots @fireblade70 . https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by fireblade70** [comment]
[Drayton TRV Clusters.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6222111/Drayton.TRV.Clusters.zip)
Sorry for delay. I have screenshot of all the clusters attached

**Comment by Mimiix** [comment]
@fireblade70 Can you add them seperately?

**Comment by sbuelow** [comment]
Hello
I bought a Drayton Wiser Thermostat Valve, fooled by the fact that was reported as working and supported.
After some tests I was only able to pair it with the coordinator (Conbee II), but there's no way to manage it.
Battery level and temperature are reported.
Does anybody know if it has to be reconfigured, in the Thermostat Cluster perhaps ?
Otherwise I have no choice but to return it and look for other working products.
Thanks in advance

**Comment by sbuelow** [comment]
Thanks for your feedback @fireblade70
It looks like this product is on the way home :).
FYI best results up to now obtained with Eurotronic Spirit.

**Comment by Feldi1606** [comment]
Does anyone use this TRV? I would really like to buy the thermostats, but based on the comments I'm not sure whether they work with deconz or not.

**Comment by Feldi1606** [comment]
I have a problem with the iTRV. I connected the thermostat to Deconz and I also see some values. But the battery is always displayed to me at 10 percent. Is there an error there? And can someone help me program the weekly programs and connect them to a room thermostat from the series?

**Comment by SwoopX** [comment]
Hi,

can you please share the DDF automatically generated by deconz? I'd recommend to start deconz and wait somewhere between 30 and 60 minutes before doing it, this will collect as much info as possible from the device based on the legacy code. Thanks!

**Comment by Feldi1606** [comment]
I hope you can do something with it and that I did it right. Otherwise please give instructions on what exactly I have to do.


`{
  "schema": "devcap1.schema.json",
  "manufacturername": "Schneider Electric",
  "modelid": "iTRV",
  "product": "iTRV",
  "sleeper": false,
  "status": "Draft",
  "path": "/devices/Schneider/itrv.json",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0201"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0301",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0201",
          "0x0204",
          "0x0B05"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/mode",
          "description": "Operational mode.",
          "default": 1
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "description": "The current device battery level in 0&ndash;100&thinsp;%.",
          "default": 0
        },
        {
          "name": "config/coolsetpoint",
          "description": "Target cooling temperature of a thermostat.",
          "default": 0
        },
        {
          "name": "config/heatsetpoint",
          "description": "Target temperature of a thermostat.",
          "read": {
            "at": "0x0012",
            "cl": "0x0201",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "write": {
            "at": "0x0012",
            "cl": "0x0201",
            "dt": "0x29",
            "ep": 0,
            "eval": "Item.val;",
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0012",
            "cl": "0x0201",
            "ep": 0,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl:attr"
          },
          "default": 0
        },
        {
          "name": "config/locked",
          "description": "Locks or unlocks the device. This item has to be understood as child-lock.",
          "read": {
            "at": "0x0001",
            "cl": "0x0204",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "write": {
            "at": "0x0001",
            "cl": "0x0204",
            "dt": "0x30",
            "ep": 0,
            "eval": "Item.val",
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0204",
            "ep": 0,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl:attr"
          },
          "default": false
        },
        {
          "name": "config/mode",
          "description": "Mode of the device."
        },
        {
          "name": "config/offset",
          "description": "Relative offset to the main measured value.",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/temperature",
          "description": "The current temperature in °C &times; 100.",
          "parse": {
            "at": "0x0000",
            "cl": "0x0402",
            "ep": 0,
            "eval": "Item.val = Attr.val + R.item('config/offset').val",
            "fn": "zcl:attr"
          },
          "default": 0
        },
        {
          "name": "state/valve",
          "description": "The open percentage of the thermostat valve.",
          "read": {
            "at": "0x0008",
            "cl": "0x0201",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0008",
            "cl": "0x0201",
            "ep": 0,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl:attr"
          },
          "default": 0
        }
      ]
    }
  ]
}`

**Comment by SwoopX** [comment]
That should do fine for a start, thanks. Needs some amendments, will share something once ready.

Accodrong to the screenshots here in this issue, the device does not support any schedules/weekly programs.

**Comment by Feldi1606** [comment]
I recreated all screenshots. I think the device supports weekly programs. Or am I wrong?

![Bildschirmfoto vom 2024-05-31 07-35-23](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/d75bcc99-3be8-485f-8cac-617e0d3a52f7)
![Bildschirmfoto vom 2024-05-31 07-36-13](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/3570005d-d0b8-4d81-ba13-1a55d8af2918)
![Bildschirmfoto vom 2024-05-31 07-36-39](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/f3439330-734c-430b-b9ca-4ceb51218646)
![Bildschirmfoto vom 2024-05-31 07-37-21](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/1ebe90dc-57a3-47bd-aa85-690ae0d1daf0)
![Bildschirmfoto vom 2024-05-31 07-37-54](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/cf92b012-e406-4741-9239-81e623cb28e3)
![Bildschirmfoto vom 2024-05-31 07-38-22](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/003e403b-3516-4135-ba85-71139007a624)
![Bildschirmfoto vom 2024-05-31 07-38-54](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/454a6b79-d754-401b-be49-e8dc7433c6e5)
![Bildschirmfoto vom 2024-05-31 07-39-29](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/23e6d24e-0c9f-44dd-a5be-757cdb0a689c)
![Bildschirmfoto vom 2024-05-31 07-40-02](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/a7d8f942-7bf7-4115-b3b9-94aff0069466)
![Bildschirmfoto vom 2024-05-31 07-40-35](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/9c1b6f99-ebf6-4327-bb88-1feb22046579)
![Bildschirmfoto vom 2024-05-31 07-43-00](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/e74ea3d6-3f5f-4161-893c-fe9825584b7e)
![Bildschirmfoto vom 2024-05-31 07-43-40](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/71de7c7b-d092-4058-8187-ed2c490be725)
![Bildschirmfoto vom 2024-05-31 07-44-20](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/d4eb6b9c-460c-47f8-a85a-69dcfd603d47)
![Bildschirmfoto vom 2024-05-31 07-44-54](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/59752db4-fbbf-4ca0-af87-e1f74a307ce9)
![Bildschirmfoto vom 2024-05-31 07-45-22](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/8043c166-56ff-41d2-b276-3b8a472b9dee)
![Bildschirmfoto vom 2024-05-31 07-46-04](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/63649fde-872f-4b65-acff-0a9e64cc1275)
![Bildschirmfoto vom 2024-05-31 07-46-39](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/84583a6b-9aa9-4751-a9c5-1b4c80dad4a0)
![Bildschirmfoto vom 2024-05-31 07-47-20](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/e82faa76-ba90-4aaa-9664-95a5dd3aebaf)
![Bildschirmfoto vom 2024-05-31 07-47-49](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/5a439bd0-212e-4ba9-9d5f-5e85aae48ee0)
![Bildschirmfoto vom 2024-05-31 07-48-10](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/694bb975-3c73-4cb7-b426-ddcfa61a3402)
![Bildschirmfoto vom 2024-05-31 07-49-11](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/cc89a699-8b53-4d4f-ac73-75ae28adac7e)
![Bildschirmfoto vom 2024-05-31 07-49-41](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/c70642c6-4048-4a40-808c-e8edc7d68fff)
![Bildschirmfoto vom 2024-05-31 07-50-20](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/fdf1c886-5f25-418f-82e3-ff657ebb2ac3)
![Bildschirmfoto vom 2024-05-31 07-50-59](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/a2c4c018-3f68-4666-98af-99ae817fb79f)
![Bildschirmfoto vom 2024-05-31 07-51-21](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/53b0f9e5-41ad-43d6-b920-f86d1d157e11)
![Bildschirmfoto vom 2024-05-31 07-51-52](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/fe402bd0-53ff-4170-8b70-f81682a18a85)
![Bildschirmfoto vom 2024-05-31 07-52-17](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/61701858-8fd7-4484-9825-5bad1a430564)

**Comment by SwoopX** [comment]
> I think the device supports weekly programs. Or am I wrong?

No, it doesn't. What makes you think it does? That is on-device schedules to be more precise allowing the radiators to be steered when any home automation system or deconz is down. With an home automation system, you can of course implement whatever you want.

Could you please give the DDF here a try? #7801

**Comment by Feldi1606** [comment]
That´s what I mean, I would store a Programm on the Thermostat. But I found no manual how to do this.

**Comment by SwoopX** [comment]
> That´s what I mean, I would store a Programm on the Thermostat. But I found no manual how to do this.

Well, as previously said, the device doesn't support it and hence the lack of any supporting documentation.

**Comment by Feldi1606** [comment]
Hello, the battery is always displayed to me at 10%. The Battery ist new so I think it musst shown with near 100%. 
FHEM shows me 2 readings "battery" and "batteryPercent" both say 10%. In Phoscon is can see Batterie with the same value. 
Is ther a Problem in the DDF?
