### ISSUE TITLE
Orvibo anyone?

### ISSUE THREAD

**Issue by almadsen** [dresden-elektronik/deconz-rest-plugin#416]
Hi, does anyone know a way to a orvibo door/window sensor work with anything but their default bridge?

**Comment by ebaauw** [comment]
They [advertise](http://www.orvibo.com/en/product/102.html) the sensor as ZigBee HA, so we should be able to add support for it to deCONZ.

I'm fascinated by their [ZigBee IR remote control](http://www.orvibo.com/en/product/31.html), but it doesn't look like they've published their manuals online.

**Comment by manup** [comment]
At least the motion sensor already works with deCONZ guess the door/window sensor can be supported as well.

**Comment by almadsen** [comment]
No way of making it happen?
I have one laying about, send to you if want it for testing.

**Comment by Chrille2k** [comment]
I have a range of products from Orvibo (motion sensor, door sensor, ir remote control, smoke sensor and more) I have them working with the Orvibo smart hub but would like to run them with deCONZ but with no luck. Can I somehow help with implementing the support for these devices?

**Comment by manup** [comment]
Can you provide some screenshots from the basic cluster read attributes. If we whitelist the modelid it should be easy to integrate.

**Comment by almadsen** [comment]
@Chrille2k can you provide @manup with that info?

@manup, were do I get the data?

**Comment by Chrille2k** [comment]
Sure @manup and @almadsen, but I think I would need some guidance how to obtain the info.

**Comment by aronteh** [comment]
Can anyone confirm that Orvibo Motion Sensor is supported. Can find it in Deconz supported device.
Having trouble paring it as Sensors/Other in Phoscon.

**Comment by manup** [comment]
>Sure @manup and @almadsen, but I think I would need some guidance how to obtain the info.

The info can be seen in the cluster info panel

![image](https://user-images.githubusercontent.com/383386/42212095-70567a82-7eb5-11e8-8a08-85504d58db71.png)

>Can anyone confirm that Orvibo Motion Sensor is supported. Can find it in Deconz supported device.
Having trouble paring it as Sensors/Other in Phoscon.

I've testet the one with the modelid OJB-IR715-Z, this one works, does yours has the same modelid?

**Comment by aronteh** [comment]
The model I have is ORVIBO SN10ZW Motion Sensor. I get very little info from my Cluster Info Panel.
Anything I can help to add support for this motion sensor.
![clipboard01](https://user-images.githubusercontent.com/10260846/42218150-36059030-7efa-11e8-9d63-6c93e75cf0f3.jpg)

This is the screen shot of the unit.
![screen shot 2018-07-03 at 7 49 52 pm](https://user-images.githubusercontent.com/10260846/42218180-4ebb7748-7efa-11e8-92fe-c64e74c901fa.png)

**Comment by Chrille2k** [comment]
I have a Motion senor model SN11 which has the following values:

![image](https://user-images.githubusercontent.com/10073491/42221081-282ae54c-7ed1-11e8-8d58-bc17300e22a0.png)

**Comment by aronteh** [comment]
I am getting very inconsistent result. The basic cluster of my xiaomi motion sensor also show empty manufacturer in a few  nodes. 
![clipboard03](https://user-images.githubusercontent.com/10260846/42221706-98ca8a9e-7f05-11e8-9485-468903f3c586.jpg)

But REST API dump of all the xiaomi sensor show correct manufacturer.
![screen shot 2018-07-03 at 9 10 27 pm](https://user-images.githubusercontent.com/10260846/42221713-a24e8ec6-7f05-11e8-80ec-3b7a88e6106c.png)

**Comment by aronteh** [comment]
I have pair the Orvibo Motion Sensor again. Got a more complete node info, basic cluster and IAS Zone cluster.
Node Info
![orvibo node info](https://user-images.githubusercontent.com/10260846/42414573-282bf4a4-826a-11e8-871a-1e1fe63a7395.jpg)
Basic Cluster
![orvibo basic cluster](https://user-images.githubusercontent.com/10260846/42414578-3d9cf4f0-826a-11e8-85ce-8f39f1305d4a.jpg)
End Point
![orvibo endpoint](https://user-images.githubusercontent.com/10260846/42414579-4455cb00-826a-11e8-8d02-4cec06e5ad41.jpg)
IAS Zone Cluster
![orvibo ias zone](https://user-images.githubusercontent.com/10260846/42414583-5736344e-826a-11e8-865a-88f8bf23b239.jpg)

**Comment by manup** [comment]
The model ids look pretty random, that's strange never seen that before (or is a chinese character set/unicode?). The manufacturer names of the above are also different. I think in this case we need to detect the sensor based on mac address prefix and the IAS Zone cluster.

**Comment by aronteh** [comment]
Yes the manufacturer name is in chinese character set.

**Comment by bparcels** [comment]
I'm far too new to Deconz to know if this will solve things or not, but the gentleman [here](https://faire-ca-soi-meme.fr/test/2017/10/31/test-orvibo-smarthome-compatible-zigate/) noted that the Orvibo sensors seem fully standard - apart from the fact that they assumed the coordinator endpoint address was 0x0A instead of the standard 0x01. For his ZiGate, he basically just aliased the two addresses for the coordinator, and everything worked. Is this something achievable in deCONZ?

**Comment by bparcels** [comment]
Also FWIW, Orvibo seems to whitelabel their products to at least a few other brands... In Canada, [primecables](https://www.primecables.ca/c-17889-smart-home) sell both the Orvibo, and their (at least visually) identical "LivingWise" equivalents... But they also make reference to a "LivingSmart" brand that they say will inter-operate as well. 

I've just ordered a few of the LivingWise components, so I should know more in a few days... I'm definitely curious to see what manufacturer name shows up in deCONZ.

**Comment by manup** [comment]
The motion sensor looks very much like the Trust motion sensor (ZPIR-8000) which is supported since deCONZ version 2.05.39. Maybe they can share the same implementation.

**Comment by bparcels** [comment]
Yep - the "LivingWise" motion sensor showed up as Orvibo, even the same model identifier as Chrille2k if memory serves (the conbee is in a pi at the moment, and I wasn't smart enough to screenshot deCONZ when first playing)... 

It doesn't show up in the web apps or anything, but does appear as a vibration sensor in the restAPI... This works fine when using the websocket->NodeRed->MQTT method... EXCEPT for the fact that after a while, the motion sensor starts to be reported as another device (i.e. when I walk past the motion sensor, I get a change event from a door (contact) sensor ID, saying "Open" (i.e. wrong ID, and wrong state altogether)?!?! Pulling the batteries from the motion sensor, and replacing, brings it back to the correct ID for a bit... but it eventually jumps back to impersonating some other sensor...

I'm not sure if I've just missed a step (again - really new to this, and haven't fully dug in yet) - perhaps I need to be enrolling the motion sensor in a zone or something first from deCONZ GUI?

At any rate - for anyone interested, the "LivingWise" (aka Orvibo) contact sensors DO work nicely  - though I believe they showed up as "Trust" or something. If the Trust motion sensor looks the same - perhaps this is yet another alias of the same actual manufacturer.

**Comment by bparcels** [comment]
Sorry - minor clarification: The motion sensor showed Orvibo when looking at the deCONZ GUI... From REST, all sensors (motion and contact), show as "manufacturername": "Trust".

**Comment by bparcels** [comment]
Sorry - one more bonehead error - mine are "LivingSmart", not "LivingWise"... apparently I'm doing neither!

**Comment by liorm0505** [comment]
hi everyone, 
was there any progress with the orvibo motion sensor? 
i have a couple of these any i would like to use them with deconz.
