### ISSUE TITLE
FEIBIT FNB56-GAS05FB1.4 Gas Sensor without carbonmonoxide state

### ISSUE THREAD

**Issue by chlctt** [dresden-elektronik/deconz-rest-plugin#4166]
Hello,

I have bought a 3rd party gas sensor from china, which has the same case as the HEIMAN Gas Sensor from here: https://www.amazon.de/HEIMAN-Smarthome-Combustible-Gas-warner-kompatibel/dp/B0793RKQWW

This is the device I bought, but with Chinese labeling:
![image](https://user-images.githubusercontent.com/20069317/104231763-b58d0680-544f-11eb-847f-e08ed11b8ce4.png)

I was able to pair the device with deconz, can see device in Phoscon, can access the device in deConz GUI showing the same values as initially presented in #3169 by @panenka.

The following screenshots shows my problem.
![image](https://user-images.githubusercontent.com/20069317/104231931-ea00c280-544f-11eb-9537-e9efe5e7e9f6.png)

I am able to access the states, but there is no carbonmonoxide state I can access. What am I missing? Is this a fake product labeled wrong?

 - Host system: (Raspberry Pi)
 - Running method: (Raspbian)
 - Firmware version: (26680700)
 - deCONZ version: (2.09.00)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
It's a blemish you can ignore. That doesn't impact functionality.

**Comment by chlctt** [comment]
Sorry, I do not understand your point. Do you mean the ZHAFire state shown above will not detect fire, but carbonmonoxide? But there can be carbonmonoxide without fire?

My expactation would be, that the device is publishing the state for carbonmonoxide "ZHACarbonmonoxide", but the only state which is available is "ZHAFire".
