### ISSUE TITLE
Ikea Panel bug on brightness

### ISSUE THREAD

**Issue by slurpey** [dresden-elektronik/deconz-rest-plugin#4170]
## Describe the bug

Made a deconz group

3 ikea lightbulbs
1 ikea light panel
If you change brightness and colour roughly at the same time, the panel doesn't follow suit. Panel only changes colour but not brightness.  (This happens both in Phoscon and via the API call from Hassio)

So in an automation (context Home Assistant) when the deconz group is called, the parameter for brightness and color temp cannot be used simultaneously.

## Steps to reproduce the behavior

Create a group with:
TRÅDFRI bulb E27 opal 1000lm
FLOALT panel WS 60x60

Use API / or Phoscon to change brightness AND color temp simultaneously.
FLOALT panel doesn't change brightness

## Expected behavior

Group should accept all parameters

## Screenshots

  If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/10026060/104317058-afde0200-54dd-11eb-93b0-c73fdfce0019.png)

## Environment

  The deCONZ and firmware versions are found in the Phoscon App: Menu -> Settings -> Gateway,
  as well as in the deCONZ GUI: Menu > Help > About deCONZ.

 - Host system: (Raspberry Pi )
 - Running method: (Home Assistent deCONZ Add-on )
 - Firmware version: (26660700)
 - deCONZ version: (2.05.84 / 9/14/2020)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes)

**Comment by manup** [comment]
@ebaauw Do I remember correctly that in Homebridge-hue you use some serialization to prevent this from happening?

Not sure how to do this in the plugin without creating a mess of code. Later on the device implementation has some better answers for such problems by providing a queue which optionally can be executed in order if needed.

**Comment by ebaauw** [comment]
I simply add a `transitiontime` of 0 before issuing a PUT with more than one attribute in the body.
