### ISSUE TITLE
Xiaomi Aqara D1 1/2/3-gang smart wall switch (no neutral wire)

### ISSUE THREAD

**Issue by isorin** [dresden-elektronik/deconz-rest-plugin#4179]
## Device

- Product name:
Xiaomi Aqara D1 1-gang (no neutral wire) - model: QBKG21LM
Xiaomi Aqara D1 2-gang (no neutral wire) - model: QBKG22LM
Xiaomi Aqara D1 3-gang (no neutral wire) - model: QBKG25LM

- Manufacturer: LUMI

- Model identifier: As per deCONZ GUI Basic cluster.
lumi.switch.b1lacn02 (1-gang)
lumi.switch.b2lacn02 (2-gang)
lumi.switch.l3acn3 (3-gang)
 
- Device type : Please remove all unrelated device types. 
  - Light
  - Switch

## Screenshots

**QBKG21LM** (1-gang)
![lumi switch b1lacn02-basic_cluster_info](https://user-images.githubusercontent.com/17415569/104466249-ec2c6380-55ac-11eb-95be-65eaad742204.png)
![lumi switch b1lacn02-node_info](https://user-images.githubusercontent.com/17415569/104466250-ec2c6380-55ac-11eb-8d0d-55a7314c0a70.png)

**QBKG22LM** (2-gang)
![lumi switch b2lacn02-basic_cluster_info](https://user-images.githubusercontent.com/17415569/104466248-ec2c6380-55ac-11eb-9bc2-f1d44b80cd77.png)
![lumi switch b2lacn02-node_info](https://user-images.githubusercontent.com/17415569/104466246-eb93cd00-55ac-11eb-803c-25a9fcd276dd.png)

**QBKG25LM** (3-gang)
![lumi switch l3acn3-basic_cluster_info](https://user-images.githubusercontent.com/17415569/104466243-eafb3680-55ac-11eb-8423-dba7eae1948e.png)
![lumi switch l3acn3-node_info](https://user-images.githubusercontent.com/17415569/104466242-ea62a000-55ac-11eb-9aeb-c64e99ed2b07.png)

QBKG21LM and QBKG22LM are discovered like this and are working fine (with some delays when switching on/off and sometimes the state is reported wrong when restarting deconz)
Note: There are a couple (can be 1, 2 or 3) "light" entries discovered, some of which disappear after Deconz is restarted
![lumi switch b1lacn02-b2lacn02](https://user-images.githubusercontent.com/17415569/104467068-ce133300-55ad-11eb-86df-9bb9d9a0c780.png)

QBKG25LM is discovered like this and appear to be working better (no apparent delay when switching on/off):
![lumi switch l3acn3](https://user-images.githubusercontent.com/17415569/104466244-eb93cd00-55ac-11eb-9bd4-78d59651fd30.png)

I can provide more details if needed.

**Comment by SwoopX** [comment]
Closing this one as the information requested via the template has not been provided. Also, please file one request per device, thanks!
