### ISSUE TITLE
Nedis Zigbee Remote Control

### ISSUE THREAD

**Issue by freaksteel** [dresden-elektronik/deconz-rest-plugin#4182]
![Screenshot 2021-01-13 at 19 01 14](https://user-images.githubusercontent.com/77398763/104491132-1b090080-55d2-11eb-8d66-3394b05de1f9.png)

## Device

- Product name: nedis Zigbee Remote Control
- Manufacturer: _TZ3000_fsieepnrh
- Model identifier: TS0215A
- Device type : Please remove all unrelated device types. 
  - Remote
  - Switch

**Comment by Mimiix** [comment]
Missing screens of clusters and device itself.
