### ISSUE TITLE
GamaBit Ltd. Window/Door Sensor

### ISSUE THREAD

**Issue by Kristian8606** [dresden-elektronik/deconz-rest-plugin#4189]
## Device

- Product name: Contact Switch.
- Manufacturer: GamaBit Ltd.
- Model identifier: GMB-HAS-DW-B01.
- Device type : Please remove all unrelated device types. 
- Sensor
 

## Screenshots
![Screenshot 2021-01-14 at 0 49 59](https://user-images.githubusercontent.com/34716572/104525721-799da100-5609-11eb-93e0-2b6a0f37b825.png)
![Screenshot 2021-01-14 at 0 50 19](https://user-images.githubusercontent.com/34716572/104525725-7bfffb00-5609-11eb-858a-1b0d96e1d320.png)
![Screenshot 2021-01-14 at 0 51 45](https://user-images.githubusercontent.com/34716572/104525728-7c989180-5609-11eb-95f0-a9bee318dc08.png)

**Comment by SwoopX** [comment]
That would be indeed good if you could test it upfront.

**Comment by Kristian8606** [comment]
Not yet visible in Phoscon

**Comment by SwoopX** [comment]
That's because deconz is not Phoscon. It's the REST API what matters here.

For visibility in Phoscon, you'd need to request it in their repository.

**Comment by Kristian8606** [comment]
I tried `GET API request ip: 80/api/67CE474F7D/sensors` but I don't see it, i see all the other sensors i have.

**Comment by SwoopX** [comment]
Have you re-paired it?

**Comment by Kristian8606** [comment]
Yes I tried twice, the different I see is that there is now a line in the deconz GUI connected to two bulbs as well as a connection to the conbee

**Comment by SwoopX** [comment]
How does the node look like in deconz GUI.

**Comment by Kristian8606** [comment]
I tried a third time. I do the search through Phoscon.
![Screenshot 2021-01-18 at 13 38 44](https://user-images.githubusercontent.com/34716572/104910860-a5ff4780-5992-11eb-8d68-3de8a222289d.png)

**Comment by Kristian8606** [comment]
How could I find it in a database to make sure it's there?

**Comment by Kristian8606** [comment]
GMB-HAS-WD-B01 I noticed a discrepancy in the Model identifier
![Screenshot 2021-01-18 at 13 46 55](https://user-images.githubusercontent.com/34716572/104911557-b6fc8880-5993-11eb-9609-a01b2e3e54a4.png)

**Comment by Kristian8606** [comment]
If this is a mistake I think I wrote it wrong GMB-HAS-WD-B01 instead GMB-HAS-DW-B01

**Comment by Kristian8606** [comment]
I fixed it sorry.

**Comment by SwoopX** [comment]
Ah, a classic ;)

So, does it work now?

**Comment by Kristian8606** [comment]
I fixed it in the title of the post but I expect you to fix it in the code.

**Comment by SwoopX** [comment]
You wanted to say that you'd appreciate if I could change it in the code, I assume.

Yes, I already did that.

**Comment by Kristian8606** [comment]
Yes, is are great you :)

**Comment by Kristian8606** [comment]
Looks like I'll have to wait for the next beta. I'm compiling your storage but I can't see this sensor via an API request.

**Comment by SwoopX** [comment]
So, you're saying it's not working, even with the amendments?

Just to be sure, you cloned the right branch?

**Comment by Kristian8606** [comment]
I follow the instructions in the description, the only difference is that I copy and clone your storage `https://github.com/SwoopX/deconz-rest-plugin.git`  is this the right way?

**Comment by SwoopX** [comment]
No, it isn't. You must specifically clone and compile the branch I made the changes on:

```
git clone --branch=gamabit_oc https://github.com/SwoopX/deconz-rest-plugin.git gamabit
cd gamabit
```

**Comment by Kristian8606** [comment]
The sensor is not yet exposed to the API.
I will try a second time to be sure and I will report.

![AF851A6F-7842-424E-8B5E-5E704F0CE998](https://user-images.githubusercontent.com/34716572/108988956-babfb100-769d-11eb-9c0f-b4a8279c6d00.png)

**Comment by Mimiix** [comment]
> The sensor is not yet exposed to the API.
> I will try a second time to be sure and I will report.
> 
> ![AF851A6F-7842-424E-8B5E-5E704F0CE998](https://user-images.githubusercontent.com/34716572/108988956-babfb100-769d-11eb-9c0f-b4a8279c6d00.png)

It seems not to be paired correctly.

**Comment by Kristian8606** [comment]
Sorry the mistake is mine.
I added it again and now it works.
