### ISSUE TITLE
deconz after update: Can not control devices

### ISSUE THREAD

**Issue by hammermannman** [dresden-elektronik/deconz-rest-plugin#4191]
## Describe the bug
<Hi,
after the update to 26660700 my gateway shows only "Network was not found.."
Then I restart the VM because the stick is not connected after the update. After that the gateway has the old version and I can not control the devices.

## Steps to reproduce the behavior
click on update

## Screenshots

![grafik](https://user-images.githubusercontent.com/44962130/104562464-ade48200-5648-11eb-897c-8f7844a3f3dc.png)

## Environment

 - Host system: unRAID
 - Running method: virtual maschine with hassio vm, deconz addon
 - Firmware version: 26580700
 - deCONZ version:  6.6.2
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: No

## deCONZ Logs
can not copy, nothing happend
![grafik](https://user-images.githubusercontent.com/44962130/104563917-90b0b300-564a-11eb-9256-7fdad898a12e.png)

**Comment by Mimiix** [comment]
Hi,

As per documentation, it is strongly recommended to use a native system to update the stick 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by hammermannman** [comment]
> 
> 
> Hi,
> 
> As per documentation, it is strongly recommended to use a native system to update the stick
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

thanks, that solved my problem!
