### ISSUE TITLE
[Device Support Request] Centralite Smart Plug Mini

### ISSUE THREAD

**Issue by luczk0wiak** [dresden-elektronik/deconz-rest-plugin#4192]
Product name: Smart Plug Mini 
Manufacturer: Centralite Systems
Model identifier: 4200-C
Device type : Plug

![image](https://user-images.githubusercontent.com/25011218/104648705-86f67200-5681-11eb-92b5-e466c2408edb.png)
![image](https://user-images.githubusercontent.com/25011218/104649144-3cc1c080-5682-11eb-9e4f-f9f88f10fc96.png)
![image](https://user-images.githubusercontent.com/25011218/104648738-937aca80-5681-11eb-8bec-7b59a9cc1fea.png)
![image](https://user-images.githubusercontent.com/25011218/104648762-9f668c80-5681-11eb-87fa-4b5ad1110601.png)
![image](https://user-images.githubusercontent.com/25011218/104648791-aa212180-5681-11eb-84c2-20912694c06e.png)
![image](https://user-images.githubusercontent.com/25011218/104648819-b907d400-5681-11eb-9de4-68a1c1a46e87.png)
![image](https://user-images.githubusercontent.com/25011218/104648866-cb820d80-5681-11eb-869f-ba1edb394f29.png)
![image](https://user-images.githubusercontent.com/25011218/104648915-e2286480-5681-11eb-8e61-83909ba6b229.png)
![image](https://user-images.githubusercontent.com/25011218/104648941-ece2f980-5681-11eb-9957-06c8652571ad.png)
![image](https://user-images.githubusercontent.com/25011218/104648999-fff5c980-5681-11eb-83e6-6d69039e80f6.png)
![image](https://user-images.githubusercontent.com/25011218/104649037-0c7a2200-5682-11eb-91fc-c34db0c0c290.png)

**Comment by SwoopX** [comment]
The device should work out of the box. Do you miss anything?

**Comment by luczk0wiak** [comment]
It wasn't pairing correctly, but it seems overnight to have worked itself out. Thought it wasn't supported.
