### ISSUE TITLE
Ubisys S1-R Metering functions

### ISSUE THREAD

**Issue by tgoerlich** [dresden-elektronik/deconz-rest-plugin#4203]
## Describe the question or issue you are having

Hi all,
I successfully conneted the Ubisys S1-R rail switch, however I seem to miss the metering functions that come with it. I cannot see any sensors in the phoscon web app, also not in other connected applications („Hue Essentials“ iOS App, iobroker deconz adapter).
In the deconz application itself I see the sensors, so they must be somewhere! Am I missing something? Can anyone confirm if the metering functions of the S1-R are implemented fully?

## Screenshots

![26407B08-18CC-4E8B-BE44-12252761E774](https://user-images.githubusercontent.com/3259926/104843292-20b06000-58ca-11eb-9a0c-d775a532a450.jpeg)

## Environment

Host system: Raspberry Pi
Running method: Raspbian
Firmware version: 26520700
deCONZ version: 2.05.74/25.2.2020
Device: RaspBee II
Do you use an USB extension cable: no
Is there any other USB or serial devices connected to the host system? No

## Additional context

Thanks

**Comment by tgoerlich** [comment]
Additional info:
In Deconz, I read power measurement values that look plausible. So, the more precise question is: how can the metering sensor be made visible through the API?
Thanks, Thomas

**Comment by ebaauw** [comment]
Should already be exposed as a ZHAConsumption `/sensors` resource for cluster 0x0702 and a ZHAPower `/sensors` resource for 0x0B04.

**Comment by tgoerlich** [comment]
There is no ZHAConsumption or ZHAPower in my `/sensors` list.
According to

**Comment by tgoerlich** [comment]
Ok, Problem solved. It seems that the S1-R is only recognised as a sensor when there is current load during the pairing process. So, switch on a radiator, go downstairs, press reset for 10secs, pair again... and here we are. I have no idea why this is so and if this is a bug or a feature. This behaviour is not mentioned in the documentation, however.
