### ISSUE TITLE
No button map reported for Namron 4-ch Switch

### ISSUE THREAD

**Issue by phithor** [dresden-elektronik/deconz-rest-plugin#4221]
## Describe the bug

No button map is reported for 4-ch Namron switch(Device id: 4512703) in the log. Used to be working.
I can see the error is reported from version 2.08.00
## Steps to reproduce the behavior

Run Deconz and check logs
## Expected behavior

Button map exists and button press pushes the press through deconz rest plugin websocket
## Screenshots

N/A
## Environment

 - Host system: NAS
 - Running method: Marthoc Docker container
 - Firmware version: 0x26390500
 - deCONZ version: 2.09.00/2.08.00
 - Device: ConBee I 
 - Do you use an USB extension cable: yes

## deCONZ Logs

11:42:37:288 [INFO] - No button map for: 4512703 endpoint: 0x03 cluster: ONOFF (0x0006) command: ON (0x01) payload[0]: 000
## Additional context

Works in 2.07.01:
11:39:57:136 [INFO] - Button 5002 On 4512703

**Comment by SwoopX** [comment]
Resolved in 2.09.01, see #4076
