### ISSUE TITLE
Colour Temperature Change not working with  Ikea TRÅDFRI 

### ISSUE THREAD

**Issue by tactmaster** [dresden-elektronik/deconz-rest-plugin#4225]
## Describe the bug

Set up 
Ikea TRÅDFRI bulb E14 opal 400lm or E27 WS opal 1000lm 
and TRÅDFRI remote control
not controlling colour temperature via buttons

## Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/793117/104949426-394e7200-59bf-11eb-8349-fc0989fafcae.png)

< and > buttons don't work. Long press/ short press....repeated pressing
This happen every time I set it up.

## Expected behavior
The colour temperature should get warmer or colder depending on buttons.

## Environment

 - Host system: Raspberry Pi 3B
 - Running method:  Home Assistent deCONZ Add-on 6.6.2  ( Hassio 2021.01.4)
 - deCONZ version: (2.7.1)
 - Device:   ConBee II 
 - Do you use an USB extension cable:   no
 - Is there any other USB or serial devices connected to the host system? Telldus Tellstick/ BT CSR 4.0

## deCONZ Logs
![image](https://user-images.githubusercontent.com/793117/104949938-12447000-59c0-11eb-8f2e-ee1391c4b9d6.png)

Light 
```
        "9": {
            "colorcapabilities": 0,
            "ctmax": 65279,
            "ctmin": 0,
            "etag": "9bcb381dada4fb422d3aa093366ba225",
            "hascolor": true,
            "lastannounced": "2021-01-18T17:24:03Z",
            "lastseen": "2021-01-18T18:07Z",
            "manufacturername": "IKEA of Sweden",
            "modelid": "TRADFRI bulb E14 WS opal 400lm",
            "name": "Side Light",
            "state": {
                "alert": "none",
                "bri": 25,
                "colormode": "ct",
                "ct": 454,
                "on": true,
                "reachable": true
            },
            "swversion": "2.3.050",
            "type": "Color temperature light",
            "uniqueid": "00:0b:57:ff:fe:37:1e:5d-01"
        }

```

**Comment by tactmaster** [comment]
Still a problem. I overriden the setting using Hue Essentials app to make it possible to chnage colour temp from a ikea remote.

**Comment by ebaauw** [comment]
Hm, the Phoson screen says long press, but the log shows short press events.  And the “discard too fast event”, see https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4627#issuecomment-808229188.

Are you sure the remote is in the right mode and sending long press events?  See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3756#issuecomment-808619291.
