### ISSUE TITLE
Compatible? ... Philips Hue Outdoor lights: Econic & Discover

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#4230]
## Describe the question or issue you are having

Are these light compatible?  

[Discover Floodlight](https://www.amazon.com/gp/product/B07NDGD11D/ref=crt_ewc_title_dp_1?ie=UTF8&psc=1&smid=ATVPDKIKX0DER)

[Econic Wall Sconce](https://www.amazon.com/gp/product/B07NDF3VPH/ref=crt_ewc_title_dp_3?ie=UTF8&psc=1&smid=ATVPDKIKX0DER)

## Screenshots
N/A

## Environment
ConBee I / ConBee II 

## deCONZ Logs
N/A

## Additional context
N/A

**Comment by Mimiix** [comment]
Lights often are working out of the box. Especially Hue. So i think it's safe to say they are ;)
