### ISSUE TITLE
Xiaomi Mi Smart Plug not fully usable (only switch feature offered)

### ISSUE THREAD

**Issue by bcutter** [dresden-elektronik/deconz-rest-plugin#4238]
## Describe the question or issue you are having

I paired a *Xiaomi Mi Smart Plug* using Phoscon with category "lights". In my smart home automation system only one entity (switch) is offered, I miss all the others for the power monitoring this device fully supports.

According to https://phoscon.de/de/conbee2/compatible the device is supported.

Do I need to pair it by another way? Did not pop up by trying to add as switch.
**How to get access to the other entities?**

## Screenshots

![grafik](https://user-images.githubusercontent.com/13799156/105091394-12b43800-5aa0-11eb-96a8-b9d088aa1c51.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.07.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? - NO

**Comment by bcutter** [comment]
Update: Grabbing the model code **ZNCZ04LM** from https://www.zigbee2mqtt.io/information/supported_devices.html#xiaomi and looking for this on https://phoscon.de/de/conbee2/compatible I can not find this device.

So... it´s not supported yet, really?

That would be a no-go - 3rd zigbee device to be integrated using Phoscon/deCONZ - and would likely force me to switch to ZigBee2MQTT :-( :-( :-(

**Comment by bcutter** [comment]
Update 2: Could find it on https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#supported-smart-plugs--in-wall-switches--power-meters

![grafik](https://user-images.githubusercontent.com/13799156/105093399-f5349d80-5aa2-11eb-985b-13a8315539e2.png)

Will digg through https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2583, fingers crossed...

**Comment by tonyawad88** [comment]
@bcutter I am using Home Assistant with Phoscon/Conbee II and when I pair it as a "sensor" in Phoscon app, I get 3 entities in Home assistant, 1 switch, 1 current power consumption and 1 historical power consumption. Remove it from Phoscon and re-add it using the Sensor => Other.
<img width="332" alt="Screen Shot 2021-02-04 at 11 53 44 PM" src="https://user-images.githubusercontent.com/3638322/106991459-3e901880-6744-11eb-90e1-5e825271ff58.png">

**Comment by bcutter** [comment]
@tonyawad88 That´s the same result for me. BUT:
- You can start pairing on the sensors page, but the plug will always be listed on the lights page.
- I tried pairing a second Mi Smart Plug. I only get one switch entity in Home Assistant:
![grafik](https://user-images.githubusercontent.com/13799156/107147733-f1809200-694f-11eb-8ae9-de170239a7de.png)

So my issues still are:
1) Only switch entity offered by deCONZ to Home Assistant.
2) With a lot of luck (pairing, waiting, checking, deleting, pairing again, hope and pray, ...) I get 3 entities: switch, current and total power consumption.
3) Total power consumption does not calculate (always 0.001 kWh) and it´s not constantly available:
![grafik](https://user-images.githubusercontent.com/13799156/107147868-a4e98680-6950-11eb-881d-1b9cc6801fd1.png)
4) I still miss all the other entities and sensors which are offered when using another ZigBee Gateway and ZigBee2MQTT (device temperature, overpower, link quality).
5) After deCONZ being not available (restart e. g.) the plug needs to be "awaken" by pressing the button, otherwise it will be unavailable in the ZigBee network.

So that´s HELL OF A PAIN and I´m not sure why it is that horrible. As a friend of mine runs this device just fine with other ZigBee equipment I tend to fingerpoint to the deCONZ part.

**Comment by framesetter99** [comment]
Worked for me. All in all I probably needed 3 pairing attempts to get it right.
I paired it as a Light, waited, checked the sensors with the rest API.
If I got a consumption and power sensor I was good.
If not I removed the "light" via the Phoscon GUI + the sensors via rest API and started again.
Did it step by step with two devices.
Once I was able to see values with the rest API I added it in Home Assistant with the Deconz Integration.

![image](https://user-images.githubusercontent.com/73557254/107148761-3f4bc900-6955-11eb-9206-3793b1d48ecd.png)

**Comment by bcutter** [comment]
After another hour of pairing / deleting / repeat I ended up in a somewhat stable total consumption entity which is acutally usable, so at least issues #1 and #3 are gone:
![grafik](https://user-images.githubusercontent.com/13799156/107151392-9f953780-6962-11eb-80e5-5d795a228152.png)

I think reading the basic cluster in deCONZ after startint sensor search in Phoscon made some difference (or reading the simple descriptos, don´t know exactly).

As you can see the attributes still show no values. @framesetter99 do you see actual values there (check current and total consumption entities)?

![grafik](https://user-images.githubusercontent.com/13799156/107151513-3c57d500-6963-11eb-8aa6-bcb6c133d0b1.png)

**Comment by bcutter** [comment]
Update: Need to revert my word from related to issue 3: it fell back to normal behaviour, so no stable data delivery and values aren´t updated at all.

![grafik](https://user-images.githubusercontent.com/13799156/107851004-d4900700-6e06-11eb-99df-ab2612c91f13.png)

Additionally hope in latest v2.9.3 which should fix the issue 6 were not satisfied (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4139#issuecomment-778615728) so currently I need to sum all my experiences by simply stating **"this device is not usable with Dresden Electronic hardware and software"**.

Will try to swap these plugs, just horrible experience. Same plugs with another ZigBee gateway using ZigBee2MQTT and everything´s working fine. Too bad.

**Comment by bcutter** [comment]
I gave up. Great hardware but not usable with ConBee 2/deCONZ in my case.
