### ISSUE TITLE
Can't pair ikea tradfri button E1812

### ISSUE THREAD

**Issue by capu81** [dresden-elektronik/deconz-rest-plugin#4244]
## Describe the question or issue you are having

Hi, yesterday i've purchased an Ikea Tradfri button (square) E1812 but i can't pair it with Deconz (phoscon App) because no device was found during scan. I've tried with ikea and "other" switch but nothing found (i press 4x time the reset button for pair on the device)

## Environment

- Host system: Raspberry Pi 4
- Running method: Home Assistent deCONZ Add-on
- Firmware version: 26660700
- deCONZ version: 2.07.01 / 8/12/2020
- Device: ConBee II
- Do you use an USB extension cable: no
- Is there any other USB or serial devices connected to the host system? no

## Additional context

I've other working sensor with deconz (Aqara, ikea rgb light and ikea repeater). Type of ikea button is E1812 (square)
I've seen #3495 . I must wait a firmware update?

**Comment by Mimiix** [comment]
You need to have at least deconz 2.9.0.
