### ISSUE TITLE
Lidl Livarno Lux Leuchten

### ISSUE THREAD

**Issue by Schnuecks** [dresden-elektronik/deconz-rest-plugin#4248]
## Device

- Product name: LIVARNO LUX® Stimmungsleuchte
- Link: https://www.lidl.de/de/livarno-lux-stimmungsleuchte-mit-akku-und-lichtfarbensteuerung-rgb-led-zigbee-smart-home/p365242
- Manufacturer: _TZ3000_9cpuaca6
- Model identifier: TS0505A
- Device type : Please remove all unrelated device types. 
  - Light

- Product name: LIVARNO LUX® Lichtleiste
- Link: https://www.lidl.de/de/livarno-lux-lichtleiste-mit-lichtfarbensteuerung/p365241
- Manufacturer: _TZ3000_gek6snaj
- Model identifier: TS0505A
- Device type : Please remove all unrelated device types. 
  - Light

## Screenshots

  Required screenshots:
Node Info
![nodeinfo](https://user-images.githubusercontent.com/27301329/105388696-42398080-5c17-11eb-9750-f0ff1157d8b7.PNG)

Node List
![nodelist](https://user-images.githubusercontent.com/27301329/105388721-4a91bb80-5c17-11eb-8f10-1fdae6416654.PNG)

Coordinator ClusterInfo
![coordinator_clusterinfo](https://user-images.githubusercontent.com/27301329/105388750-52e9f680-5c17-11eb-905e-da23a71461f6.PNG)

Lightbar ClusterInfo
![lidl_livarno_lux_lightbar_clusterinfo](https://user-images.githubusercontent.com/27301329/105388777-5a110480-5c17-11eb-894f-524ad7b83821.PNG)

Lightbox1 ClusterInfo
![lidl_livarno_lux_lightbox1_clusterinfo](https://user-images.githubusercontent.com/27301329/105388813-64330300-5c17-11eb-91a8-bef54b1a4c98.PNG)

Lightbox2 ClusterInfo
![lidl_livarno_lux_lightbox2_clusterinfo](https://user-images.githubusercontent.com/27301329/105389509-3601f300-5c18-11eb-9064-8c8679d7aac2.PNG)

**Comment by ebaauw** [comment]
Looks like they're already exposed by the REST API Plugin?  If not, please provide all screenshots, including, for each of the lights, the node with endpoints and clusters, and the _Node Info_ panel.

We map the weird names for the other Livarno lights to "LIDL Livarno Lux" as manufacturer name and the product number as model id (e.g. HG06106C for the RGB E27 light bulb), so please provide those as well (typically on the box or in the user manual).

**Comment by Schnuecks** [comment]
First thank you for your response, here are the modelnr of the LED-Stimmungslicht 14148906L and the model nr LED-Lichtleiste is 14149505L / black version 14149506L / white version.

yes it seems that it is exposed and working with the api. i have a question that leads me here.

on my openhab installation the lights raises an error message, so i put it here.
```
2021-01-21 16:49:44.881 [INFO ] [z.internal.handler.LightThingHandler] - Could not determine effect light type for thing deconz:extendedcolorlight:b2252869:842e14fffe24b96801, please request adding support on GitHub.
2021-01-21 16:49:44.884 [INFO ] [z.internal.handler.LightThingHandler] - Could not determine effect light type for thing deconz:extendedcolorlight:b2252869:588e81fffeecb2be01, please request adding support on GitHub.
2021-01-21 16:49:45.221 [INFO ] [z.internal.handler.LightThingHandler] - Could not determine effect light type for thing deconz:extendedcolorlight:b2252869:842e14fffe22fe3701, please request adding support on GitHub.
```
The LED light bar does not switch off completely, but remains on at around 10% and continues to light. All other commands such as colors and brightness work normally, they just don't go off completely. I also tried various apps.

**Comment by ebaauw** [comment]
> here are the modelnr of the LED-Stimmungslicht 14148906L and the model nr LED-Lichtleiste is 14149505L / black version 14149506L / white version.

Does the black version of the Lichtleiste have a different _Manufacturer Name_ than the white one?  Otherwise we cannot distinguish them.

> on my openhab installation the lights raises an error message

Best file that with openhab (or the deCONZ/openhab integration).

> And another problem i have is the LED light bar does not switch off completely, but remains on at around 10% and continues to light.

Hoe are trying to switch off the light bar?  What API command are you sending?

Could you check in the GUI whether it reacts to an _Off_ command?  And to a _Move to Level (with On/Off)_, setting level to `0` or `1`?  Could you please include  the _Node Descriptor_ screenshot of the light bar?  Particularly interested in the _Manufacturer Code_.

**Comment by Schnuecks** [comment]
> Does the black version of the Lichtleiste have a different _Manufacturer Name_ than the white one? Otherwise we cannot distinguish them.

No it's the same

> Best file that with openhab (or the deCONZ/openhab integration).

they mentioned it should report it here ;)
https://community.openhab.org/t/deconz-which-thing-type-is-needed-for-lidl-melinera-led-wire/109462/44?u=J-N-K
> 
> > And another problem i have is the LED light bar does not switch off completely, but remains on at around 10% and continues to light.
> 
> Hoe are trying to switch off the light bar? What API command are you sending?

I don't know which command openhab or HueEssentials is sending but both have the same result so that it doesn't go off completly. But i think they do the right thing, because of below.

> Could you check in the GUI whether it reacts to an _Off_ command? And to a _Move to Level (with On/Off)_, setting level to `0` or `1`? Could you please include the _Node Descriptor_ screenshot of the light bar? Particularly interested in the _Manufacturer Code_.

i have toogle power on / off not completly off, same with move to level.

here the node info of the lightbar
![nodeinfo_lightbar](https://user-images.githubusercontent.com/27301329/105493469-ba588280-5cb9-11eb-82fc-7e0819ed6b0b.jpg)


here a small video first On / Off second level 0 to 255 and return
i put it on my space because it's too big for github, 14 days valid

<a href="https://wolke.frickelboxx.de/f/25a91928a114487086ab/" target="_blank">Video Lighbar</a>

best regards

**Comment by ebaauw** [comment]
The link doesn't work.

If the light doesn't react to an _Off_ command the issue is with the light firmware.  Nothing deCONZ nor the REST API Plugin can do.  Never seen this before, though.  You might check _Toggle_ or _Off with Effect_, but these are, I think optional, and I've seen plenty of lights not supporting these.  As there are not supporting _Move to Level (with On/Off)_.

Did you try the LIDL app with their Silvercrest gateway?  Is that able to turn off the light?.

**Comment by Schnuecks** [comment]
Hello,

sorry that it not worked, I put it on Google Drive

https://drive.google.com/file/d/1HGxOfZN0sgvLOzal9CTnOJNfC_LlENvW/view?usp=drivesdk

I don't have the gateway right now because  I would try it without it.

I could give it a try and order one.

**Comment by Schnuecks** [comment]
So, how can we solve the message from openhab with the effect feature?

Is this feature available on the lamp or is openhab mentioning that that kind of lamp has this feature and can't use it?

I just like to understand.

**Comment by Heiner1967** [comment]
Hi, 
I got such Livarno Lux Stimmungsleuchte to work with conbee II and Phoscon, but the related remote i do not get at all to work.
For me the trick to get it  was to apply the learning directly beside the conbee, and not beside another  zigbee device which shall work as range extender - this only after initial registration seems to work.
But it would be great to get the remote to work as well.

**Comment by Mimiix** [comment]
@Heiner1967 Please open a seperate issue for that remote containing all screenshots :)

**Comment by Heiner1967** [comment]
let me add this ping to avoid this get closed unsolved.

**Comment by Hl2run** [comment]
Please add support for the light bar. Thanks :)

**Comment by Einstein2150** [comment]
there is a new model of the light on the market --> [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5900](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5900)
