### ISSUE TITLE
New firmware for Elko Super TR making it not available in REST API and Home Assistant

### ISSUE THREAD

**Issue by henrikrox** [dresden-elektronik/deconz-rest-plugin#4251]
## Device

- Product name: Elko Super TR
- Manufacturer: Elko
- Model identifier: Super TR
- Device type : 
  - Thermostat

## Screenshots

![bgsfgsg](https://user-images.githubusercontent.com/6884716/105410661-943bcf80-5c32-11eb-8f90-7a7573637933.PNG)
![gsdg](https://user-images.githubusercontent.com/6884716/105410710-ac135380-5c32-11eb-8e44-9c83ee8e11ad.PNG)

This should have already been added trough
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2088

However it looks like a i have a new firmware, since there are groups/scenes etc, also in thermostat i have a lot more attributes compared to the original issue #2088

Find the thermostat in deconz, but rest api returns nothing under sensors.

**Comment by henrikrox** [comment]
I also notice a lot of 

`21:53:54:690 No thermostat sensor found for 0x680AE2FFFE6963BF, endpoint: 0x00000001
21:53:54:690 ZCL attribute report 0x680AE2FFFE6963BF for cluster: 0x0201, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
21:54:15:303 Current channel 11
21:54:15:311 Device TTL 1134 s flags: 0x7`

in deconz logs. 

However looking from thermostat attributes, it at least sees the correct temperature (air in this case)
![uøi](https://user-images.githubusercontent.com/6884716/105411435-b2ee9600-5c33-11eb-81b5-172d36d6e65e.PNG)

**Comment by SwoopX** [comment]
Hm, apparently, they changed the RF-Chip. We now see a different MAC address as well as manufacturer code, resulting in a required check to fail. Should be just one line to add.

**Comment by oywino** [comment]
@henrikrox did you update the firmware in your "old" thermostat, or is this a the brand new version from ELKO that they advertise as ZigBee 3.0 compatible?

**Comment by andersop91** [comment]
@oywino seems like the new hardware. I've bought one of this (https://elkosmart.elko.no/produkter/smarttermostat-super), ZigBee 3.0 compatible. It looks just the same in deCONZ at least.

**Comment by jornholm** [comment]
@andersop91 did you get your device to work? I have 2 of the same version and they are not showing up in the api.

**Comment by andersop91** [comment]
@jornholm Yes, it showed up, but weren't seamless. I changed to ZHA instead, where also the PIR was supported.
