### ISSUE TITLE
MeanLED ZB-RE5-1 Remote (zigbee 3.0)

### ISSUE THREAD

**Issue by Hundefreund02** [dresden-elektronik/deconz-rest-plugin#4259]
## Device

- Product name: ZB-RE5-1
- Manufacturer: ? (MeanLED Art.Nr.60520) **
- **vgl. Namron 4512706**  see https://zigbee.blakadder.com/Namron_4512706.html**
- Model identifier: ?
- Device type :  - Remote
  
only MAC Adress and NWK shown !
pairing was ok!

## Screenshots
![image](https://user-images.githubusercontent.com/58217257/105607212-d03f7380-5d9d-11eb-8a5e-b49f2e7922d7.png)
![ZB-RE5-1](https://user-images.githubusercontent.com/58217257/105607228-ea795180-5d9d-11eb-8122-9b6e232561de.jpg)

##
features
- 5-in-1 multifunctional remote control for the ZigBee © network
- 1-channel (dimmer), 2-channel (CCT), or 3-5-channel (RGB, RGBW, RGBCCT)
- easy integration into the network via "Touchlink"
- works with the latest ZigBee © 3.0 protocol
- supports 4 groups with up to 30 devices
- suitable for all ZigBee © lamps, lights and controllers
- suitable for all ZigBee © 3.0 gateways (e.g. Philips HUE, etc.)
- 7 free memory spaces for individual settings

**Comment by SwoopX** [comment]
Please adhere to the template and provide all requested information.
