### ISSUE TITLE
MeanLED ZB-RE5-1

### ISSUE THREAD

**Issue by Hundefreund02** [dresden-elektronik/deconz-rest-plugin#4268]
## Device

- Product name: MeanLED ZB-RE5-1(Nr.60520)
- Manufacturer: Sunricher.
- Model identifier: ZG2868A.
- Device type : 
- Remote
  

## Screenshots

![image](https://user-images.githubusercontent.com/58217257/105623585-2bfc1200-5e1b-11eb-8630-5ff61a9b6321.png)
![image](https://user-images.githubusercontent.com/58217257/105623611-5b128380-5e1b-11eb-99db-44fcc372defa.png)
![image](https://user-images.githubusercontent.com/58217257/105623636-88f7c800-5e1b-11eb-82fc-7bc68e3ff50c.png)
![image](https://user-images.githubusercontent.com/58217257/105623654-a331a600-5e1b-11eb-946f-2db8a9fcf467.png)
![image](https://user-images.githubusercontent.com/58217257/105623862-6cf52600-5e1d-11eb-9a89-a19e77fdd803.png)

## Logs
For further help ;:
Keys of the remote control were pressed one after the other from top left [S1] to bottom right [4] and log Deconz Debug 
(under help) generated.
I had set only the switches APP & APPL2 from the Deconz Debug tool !
[log_FB_Deconz.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5868421/log_FB_Deconz.txt)

## Manual

![ZB-RE5-1](https://user-images.githubusercontent.com/58217257/105623876-7d0d0580-5e1d-11eb-8638-a52517f0da38.jpg)
USER manual de:
[ZB-RE5-1 (4).pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5862306/ZB-RE5-1.4.pdf)
USER manual en: 
[SRZG2868 Data Sheet.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5862519/SRZG2868.Data.Sheet.pdf)

## Identical remotes

**Baugleich Subricher SRZG2868 !** https://www.ledtechnologies.co.uk/sunricher-3-in-1-single-colour-cct-rgb-zigbee-remote-control.html
>>>auch Baugleich mit Namron 4512706 siehe https://zigbee.blakadder.com/Namron_4512706.html **

**Comment by pur3asdf** [comment]
Sunricher ZG2868 also mentioned in [Issue 3527](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3527)
