### ISSUE TITLE
Envilar ZGR904-S remote (same as iCasa remote)

### ISSUE THREAD

**Issue by spiff42** [dresden-elektronik/deconz-rest-plugin#4269]
## Device

- Product name: ZGR904-S Zigbee Fjernbetjening (Touchlink)
- Manufacturer: ENVILAR
- Model identifier: ZGR904-S
- Device type : Remote

The remote is a clone of iCasa remote ICZB-RM11S (see  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2648#issuecomment-760462453). I actually bought it hoping it would work because it looked exactly like the iCasa remote, which was listed on the supported devices page.

It was bought here:
https://www.plusled.dk/zgr904-s-zigbee-fjernbetjening-touchlink.html

The PDF manual (in Danish and English):
https://www.plusled.dk/amfilerating/file/download/file_id/79/

## Screenshots

Just like the iCasa remote, the device has 4 identical endpoints:
![ZGR904-S Node info](https://user-images.githubusercontent.com/12989129/105627905-d4b96a00-5e39-11eb-9ff3-6150d4f36983.png)

EDIT: Some entries were not correctly populated after multiple reads of the cluster. Reading the entries one-by-one leads to this.
The basic cluster of the first endpoint (all look to be the same):
![ZGR904-S Basic cluster upd](https://user-images.githubusercontent.com/12989129/105641369-c7c16880-5e83-11eb-9529-abec712dfd03.png)

![ZGR904-S Power Configuration](https://user-images.githubusercontent.com/12989129/105628122-48a84200-5e3b-11eb-8920-62d368f68720.png)

I can provide screenshots of other clusters if needed, but since this remote appears to be another clone of the iCasa remote (like the Sunrichter Remote #3125), I am assuming this is sufficient.

**Comment by Mimiix** [comment]
@spiff42 please add all clusters. We can't assume anything unfortunately.

**Comment by SwoopX** [comment]
The screenshots given suffice.

I'll check if we can just treat if like the other remotes referred to.

**Comment by spiff42** [comment]
Thanks @SwoopX for picking this up again. Please let me know if I can be of any assistance.
