### ISSUE TITLE
IKEA Trådfri Shortcut button

### ISSUE THREAD

**Issue by enjikaka** [dresden-elektronik/deconz-rest-plugin#4276]
## Device

- Product name: [IKEA Trådfri Genvägsknapp](https://www.ikea.com/se/sv/p/tradfri-genvaegsknapp-vit-40356381/)
- Manufacturer: IKEA of Sweden
- Model identifier: TRADFRI SHORTCUT Button
- Device type:
  - Switch
  - Remote?
<img width="976" alt="Skärmavbild 2021-01-26 kl  15 28 33" src="https://user-images.githubusercontent.com/877455/105858004-281eea00-5feb-11eb-9fcf-3d49bfdc4f24.png">
<img width="455" alt="Skärmavbild 2021-01-26 kl  15 29 34" src="https://user-images.githubusercontent.com/877455/105858156-4be23000-5feb-11eb-9984-134d84a8f4e1.png">

**Comment by ebaauw** [comment]
Support was already added in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3975.

**Comment by enjikaka** [comment]
Ah ok, the hassio addon is very outdated then. Hoping for an update to that soon.
