### ISSUE TITLE
connectivity check not longer working with 2.05.05

### ISSUE THREAD

**Issue by johol** [dresden-elektronik/deconz-rest-plugin#428]
In the past I used the connectivity.html page to check my lamps. After updating from 2.04.35 to 2.05.05 opening connectivity.html causes the deconz process to not response any longer and it has to be restarted. I think, it is a issue with the newer firmware.

**Comment by manup** [comment]
The connectivity.html site and related API isn't maintained since a few years, it was a experiment once but didn't work out. I'm afraid it won't come back, maybe at some day a reincarnation in the Phoscon App but this isn't planned currently.
