### ISSUE TITLE
Lidl LivarnoLux LED Pannel Remote

### ISSUE THREAD

**Issue by Heiner1967** [dresden-elektronik/deconz-rest-plugin#4281]
## Describe the bug

  Hi, i bought some LavarnoLux LED Light pannels including a remote from Lidl.
Those could be introduced to Phoscom in the following steps:

Now the light works with colour adaption and brightness adaption via phoscon, the remote works as well but only for on/off and brightness. The color selection is not working. However no remote is shown inside phoscon.

If however I reset the pannel and the remote, and only connect remote to the pannel, i can on top choose in between of 4 colours.

To note the Pannel is shown in phoscon as from Vendor Heiman and Model TS0502A

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

  1. reset the remote and put into coupling mode, search in phoscom for new lights - it looks like no result, but no worries.
  2. power the light pannel, which blinks to indicate to be in couplng mode, search for lights again, phoscom add a new device.
  3. put the remote in couplingmode again, and the light confirm it works.

  If the problem can't be reproduced and is sporadic, please provide some details
  on how often and when the issue happens.

## Expected behavior

  The remote should be visible in phoscon like a Philips Dim Switsh
the remote should be able to change color by repeating to push the "1" buttom.

## Environment

 - Host system: Raspberry Pi 
 - Running method: Raspbian / fhem 
 - Firmware version: 26660700
 - deCONZ version: 2.05.84
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
1; You are on a old version
2: i am not sure if this remote is supported s you need to request support for it.
3: Phoscon needs to add support on their own in their repository. https://github.com/dresden-elektronik/phoscon-app-beta/issues
Closed.
