### ISSUE TITLE
tint Fernbedienung white

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/deconz-rest-plugin#4292]
## Device

- Product name: tint Fernbedienung white [https://www.mueller-licht.de/produktinformationen/artikel/404022/](url)
- Manufacturer: MLI
- Model identifier: tint-Remote white
- Device type : 
  - Remote

 

## Screenshots
![image](https://user-images.githubusercontent.com/43421040/106200414-39b4ed00-61b7-11eb-9787-cea44dcc2370.png)

![2021_01_28_22_07_39_raspi4_raspi4_VNC_Viewer](https://user-images.githubusercontent.com/43421040/106199835-4a189800-61b6-11eb-9090-5c381f489da6.png)
![2021_01_28_21_54_30_raspi4_raspi4_VNC_Viewer](https://user-images.githubusercontent.com/43421040/106199831-48e76b00-61b6-11eb-9f24-f62280247fd8.png)
![2021_01_28_21_54_46_raspi4_raspi4_VNC_Viewer](https://user-images.githubusercontent.com/43421040/106199833-49800180-61b6-11eb-8b3f-e8f58172384a.png)

**Comment by Mimiix** [comment]
Without screenshots, we can't do anything.

**Comment by Maddinthebrain** [comment]
> Without screenshots, we can't do anything.

Well I'm on it. But Github doesn't let me....
I try it again.

**Comment by Maddinthebrain** [comment]
Can I support this anyhow?

**Comment by Mimiix** [comment]
Need to wait for a dev to do it. Or you need to figure out yourself.

**Comment by Maddinthebrain** [comment]
Okay, that's exactly my question how can help? What steps and tools are needed?

**Comment by Maddinthebrain** [comment]
@Mimiix

**Comment by Maddinthebrain** [comment]
Hello there, 

is there any action about this remote? Unfortunatly the new API featurer doesn't help here. The device only appears in the deconz gui but not in the phoscon app. How can I support?
