### ISSUE TITLE
Livolo Zigbee Power Socket TI0001 Device Request

### ISSUE THREAD

**Issue by bsfaxi** [dresden-elektronik/deconz-rest-plugin#4300]
## Device

- Product name: Livolo Zigbee Power Socket.
- Manufacturer: LIVOLO.
- Model identifier: TI0001.
- Device type : Please remove all unrelated device types. 
  - Switch
  - Other: Power Socket

## Screenshots

![image](https://user-images.githubusercontent.com/23717629/106300227-7daaff00-6256-11eb-99d2-91a3bdf47f5c.png)
![image](https://user-images.githubusercontent.com/23717629/106300305-a03d1800-6256-11eb-933e-8bfb40d02c9e.png)

Nothing in the On/Off cluster!
![image](https://user-images.githubusercontent.com/23717629/106300452-d24e7a00-6256-11eb-99d7-9d02ab4026c1.png)

Here is a link to the product : https://www.aliexpress.com/item/4000343575116.html?spm=a2g0s.9042311.0.0.49316c37sVuqR1.

I found an interesting link on this brand (not the same product) here: https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Livolo-corner.md.

**Comment by bsfaxi** [comment]
anyone please?

**Comment by Mimiix** [comment]
Bumping wont work. Devs need to integrate it. But even if they do, chances are slim that it could be integrated soon. as theres 36 PR's waiting.

**Comment by bsfaxi** [comment]
Thanks @Mimiix.
I understand. Bumping wasn't my goal. :)
I had to request for new devices in the past, and I had the habit to receive a response in the same day.
I have to be patient! ;)

**Comment by Smanar** [comment]
On m y side I m not realy motivated, sorry, your device look realy strange (clusters are not standard) , and last time I havez tried with livolo device was not a success.

**Comment by bsfaxi** [comment]
> On m y side I m not realy motivated, sorry, your device look realy strange (clusters are not standard) , and last time I havez tried with livolo device was not a success.

Hi @Smanar,
I know. :)
Please know that I have a dedicated DEV environment. We can play with it as you wish. :)

**Comment by Smanar** [comment]
Lol, nice, but seriously there is no usefull cluster, so it can be hidden, or another magic one like for tuya, so lot of search to do.

**Comment by bsfaxi** [comment]
Too much work was already done here as mentioned in the initial request :  https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Livolo-corner.md.

Extract:
_"On and OFF are not based on the Cluster 0x0006, but rather on cluster 0x0008. Don't ask me why ... Livolo migh have a reason for that !
On the Cluster 0x0008 (Level Control) Livolo are using those 2 parameters."_

**Comment by Smanar** [comment]
Yeah I know, It that I have used for the livolo switch, to finaly give up, too much work for something not enought stable.

**Comment by bsfaxi** [comment]
Hi @Smanar,
If a beer would motivate you, I would be more than happy to offer you one, virtually or whenever you come to Paris in person. ;)

**Comment by Smanar** [comment]
Lol, you realy want this device ^^.
But seriously even on other project, there is so much problem with this kind of device, will be easier to find another one.

**Comment by bsfaxi** [comment]
> Lol, you realy want this device ^^.
> 
> But seriously even on other project, there is so much problem with this kind of device, will be easier to find another one.

Let's give it a quick try then. I have 3 of them. If it's so much time, we stop.
BTW, could you point me to an equivalent Zigbee euro wall socket, that works already with deCONZ ?

**Comment by Smanar** [comment]
I think I have still the old code for livolo somewhere on my hard disk, but too few time ATM.
Plug or "in wall" models ?

**Comment by bsfaxi** [comment]
Thanks @Smanar .
It's an "in wall" socket.
link : https://www.aliexpress.com/item/4000343575116.html?spm=a2g0s.9042311.0.0.49316c37sVuqR1.

**Comment by Smanar** [comment]
I m using the legrand netatmo one, good product but still not comptibale with Xiaomi and channel locked
This one is not bad https://www.niko.eu/fr-be/article/170-33505 from my memory swoop have already tested it too.

**Comment by bsfaxi** [comment]
> I m using the legrand netatmo one, good product but still not comptaible with Xiaomi and channel locked
> This one is not bad https://www.niko.eu/fr-be/article/170-33505 from my memory swoop have already tested it too.
> 
> Edit:
> #2984

Thanks Smanar. They are indeed good ones.
The only show stopper for me is that they don't have a physical on/off button. If I loose my Zigbee network, or if grandfather wants to turn on the TV and the switch is off, you can imagine the situation... lol

**Comment by Smanar** [comment]
>The only show stopper for me is that they don't have a physical on/off button. If I loose my Zigbee network, or if grandfather wants to turn on the TV and the switch is off, you can imagine the situation... lol

Ha yes, was a criter in the "in wall plug search", but the niko one have it. Can use too a remote with a direct bind (work even if the gateway is off)

**Comment by bsfaxi** [comment]
That sounds really great. Thanks a lot.
I found one with a good price here: https://www.dmlights.fr/niko_home_control_prise_de_courant_connectee_commutable~18G15.
I will order one for test.
Meanwhile, could we have a quick test for the LIVOLO one. :)

**Comment by Smanar** [comment]
lol tenacious.
Not with me, I can share the old file if someone want to test it, but I m realy not interessted, too much work to have too much hack in the code to make a not reliable device working.

**Comment by bsfaxi** [comment]
I understand.
Who can help?
