### ISSUE TITLE
2Gang Wall Switch TZ3000_owgcnkrh / TS0042

### ISSUE THREAD

**Issue by degrammont** [dresden-elektronik/deconz-rest-plugin#4309]
## Device

- Product name: Lonsonho 2 Gang Wall Switch
- Manufacturer: _TZ3000_owgcnkrh
- Model identifier: TS0042
- Device type : Switch

https://fr.aliexpress.com/item/4001095272467.html?spm=a2g0s.9042311.0.0.1e886c37LAyKkC

The device is visible as a light / the 2 Gangs are visible
Battery level (CR2032) is not reported
deconz_event not reported under HA (I'm using deconZ docker under Synology NAS)

## Screenshots

![image](https://user-images.githubusercontent.com/65274861/106356945-67a74800-6303-11eb-9ffd-3bfc77a2c6fd.png)

![image](https://user-images.githubusercontent.com/65274861/106356949-6bd36580-6303-11eb-90aa-96225457c30c.png)

**Comment by Mimiix** [comment]
Please add all screenshots.

**Comment by Smanar** [comment]
Yep, miss the basic attribute panel, select the "basic cluster" 0x0000, then press the "read" button with making the device awake.
For information, this device will be easy to add, but I m waiting for other PR  will be merged first.

**Comment by Smanar** [comment]
Yep, miss the basic attribute table.

**Comment by degrammont** [comment]
I hope that's what you are looking for.

![image](https://user-images.githubusercontent.com/65274861/106365978-47927b80-6339-11eb-83ea-2a2c0e0181da.png)
![image](https://user-images.githubusercontent.com/65274861/106365994-63961d00-6339-11eb-91a3-4727216f76ba.png)

Thanks for your help.

**Comment by Mimiix** [comment]
We need all clusters.

**Comment by degrammont** [comment]
![image](https://user-images.githubusercontent.com/65274861/106366862-f1283b80-633e-11eb-90af-d4fa78619aca.png)
![image](https://user-images.githubusercontent.com/65274861/106366872-043b0b80-633f-11eb-80b9-a3aba1cf7918.png)
![image](https://user-images.githubusercontent.com/65274861/106366876-0ef5a080-633f-11eb-8669-f7e36e659b98.png)

And for the second Gang
![image](https://user-images.githubusercontent.com/65274861/106366883-216fda00-633f-11eb-8ac1-791035385707.png)
![image](https://user-images.githubusercontent.com/65274861/106366892-2af94200-633f-11eb-84f3-43b1c9e4c1f2.png)
![image](https://user-images.githubusercontent.com/65274861/106366897-32205000-633f-11eb-9e62-08a56684ca29.png)

**Comment by Smanar** [comment]
Hello, do you have a linux machine to test the code ? I will explain how to do.

**Comment by degrammont** [comment]
I'm using the docker container on my Synology NAS.

**Comment by Smanar** [comment]
Lol, ok so hard to test, the pr is submitted, hopping for no error from me.
