### ISSUE TITLE
Device name Tuya AM43-0.45-40  Blind drive motor

### ISSUE THREAD

**Issue by Wimaware** [dresden-elektronik/deconz-rest-plugin#4310]
![Snag_5af4410b](https://user-images.githubusercontent.com/78143405/106357502-bc988d80-6306-11eb-93d3-352f121ab362.png)

## Device

- Product name: AM43 Blinds drive
- Manufacturer: _TZE200_zah67ekd
- Model identifier: TS0601
- Device type : _Blinds motor drive
- 
![Snag_5aee15a2](https://user-images.githubusercontent.com/78143405/106357328-cd94cf00-6305-11eb-9a27-c13ba35835e0.png)
![Snag_5aee8ac3](https://user-images.githubusercontent.com/78143405/106357336-dd141800-6305-11eb-95fd-4d0c801d1656.png)
![Snag_5aeea408](https://user-images.githubusercontent.com/78143405/106357339-e1403580-6305-11eb-8a6e-0319744f4956.png)
![Snag_5aeec3d4](https://user-images.githubusercontent.com/78143405/106357341-e604e980-6305-11eb-9758-a21c6b0dfff8.png)
![Snag_5aef2463](https://user-images.githubusercontent.com/78143405/106357355-f4530580-6305-11eb-8226-61bb0f7b17a7.png)

**Comment by Smanar** [comment]
Hello, do you have a Linux machine to test the code ?

**Comment by Wimaware** [comment]
I am running on a Windows machine

**Comment by Smanar** [comment]
No problem, will be in all OS on the future version.
