### ISSUE TITLE
Level change stop

### ISSUE THREAD

**Issue by perfrankling** [dresden-elektronik/deconz-rest-plugin#4313]
## Feature request type
Extend REST-API capabilities

## Description
Implement a way to stop an ongoing brightness level change through the REST-API, leaving the brightness level at the current level, ie the same as executing the "Stop" command in the Cluster info panel for the Level Control Cluster in the deConz application.

**Comment by ebaauw** [comment]
PUT `{"bri_inc": 0}` to the light state.

**Comment by perfrankling** [comment]
Thank you!

The bri_inc parameter is missing from the documentation at https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/

**Comment by ebaauw** [comment]
I'm afraid that's not the only thing missing from the API documentation...

It works for groups as well.

**Comment by Mimiix** [comment]
Case close :)
