### ISSUE TITLE
SilvercrestDevice SAPZ 1 A1 

### ISSUE THREAD

**Issue by WernerSch** [dresden-elektronik/deconz-rest-plugin#4315]
## Describe the bug

The Switch for a plug socket  SAPZ 1 A1 is connected as light. 
 
## Steps to reproduce the behavior

I delete it and connect it again for three times. Its always connect as a light

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.07.01 / 8.12.2020
 - Device: ConBee II
 - Do you use an USB extension cable: no 
 - Is there any other USB or serial devices connected to the host system? If so: Which? RFLink Adapter for iobroker

**Comment by SwoopX** [comment]
No bug here
