### ISSUE TITLE
Woox R7051 Smart Indoor Siren

### ISSUE THREAD

**Issue by EarlOfBurton** [dresden-elektronik/deconz-rest-plugin#4321]
## Device

- Product name: R7051 Smart Indoor Siren
- Manufacturer: _TYZB01_ynsiasng
- Model identifier: TS0219
- Device type : Please remove all unrelated device types. 
  - Siren

Product page see: https://wooxhome.com/uncategorised-c5/new-2020-product-c7/woox-r7051-smart-indoor-siren-p49
## Screenshots

  Required screenshots:
  - Endpoints and clusters of the node
  - Node Info panel
  - Basic Cluster attributes in the Cluster Info panel.
![node_info](https://user-images.githubusercontent.com/16398996/106464623-2ba5eb80-6499-11eb-9319-277d7f8b9717.png)
![power_configuration](https://user-images.githubusercontent.com/16398996/106464631-2ea0dc00-6499-11eb-9638-f971c4b8e550.png)
![cluster_info_basic_cluster](https://user-images.githubusercontent.com/16398996/106464640-32ccf980-6499-11eb-8b0f-01d0671bfd52.png)
![ias_wd_cluster](https://user-images.githubusercontent.com/16398996/106464651-36f91700-6499-11eb-95b4-b4f20dfa967b.png)

**Comment by Mimiix** [comment]
Missing screenshot of total clusters.

**Comment by EarlOfBurton** [comment]
Is this the right missing information?
![2](https://user-images.githubusercontent.com/16398996/106470359-ac1c1a80-64a0-11eb-861d-583099024f50.png)

**Comment by Mimiix** [comment]
Missing IasZONE , Identify, Scenes, Groups and the unknown one too.

**Comment by EarlOfBurton** [comment]
Hi @Mimiix, now I think I do understand, sending you all of the screenshots. If I missed something, please let me know.
Thanks.
## Basic
![01_basic](https://user-images.githubusercontent.com/16398996/106474686-73cb0b00-64a5-11eb-9ad0-bb44441ce895.png)
## Power configuration
![02_power_configuration](https://user-images.githubusercontent.com/16398996/106474719-79c0ec00-64a5-11eb-93d6-360cdee12255.png)
## Identify
![03_identify](https://user-images.githubusercontent.com/16398996/106474739-7e85a000-64a5-11eb-87ca-b89a19e2a65c.png)
## Groups (1/2)
![04_groups1](https://user-images.githubusercontent.com/16398996/106474775-86dddb00-64a5-11eb-89fd-67bcab4c7e9e.png)
## Groups (2/2)
![05_groups2](https://user-images.githubusercontent.com/16398996/106474798-8d6c5280-64a5-11eb-8f9c-610450814b58.png)
## Scenes (1/3)
![06_scenes1](https://user-images.githubusercontent.com/16398996/106474830-95c48d80-64a5-11eb-8edd-197b6df4b99c.png)
## Scenes (2/3)
![07_scenes2](https://user-images.githubusercontent.com/16398996/106474851-9ceb9b80-64a5-11eb-8c9d-f4d184f02121.png)
## Scenes (3/3)
![08_scenes3](https://user-images.githubusercontent.com/16398996/106474872-a248e600-64a5-11eb-9258-d029442bf818.png)
## IAS Zone
![09_ias_zone](https://user-images.githubusercontent.com/16398996/106474893-a70d9a00-64a5-11eb-8d7a-c8e5ce87a4f0.png)
## IAS WD
![10_ias_wd](https://user-images.githubusercontent.com/16398996/106474908-abd24e00-64a5-11eb-8939-4b915e916a54.png)
## Unknown
![11_unknown](https://user-images.githubusercontent.com/16398996/106474937-b260c580-64a5-11eb-8d74-9b33eae402cd.png)
## Identify
![12_identify](https://user-images.githubusercontent.com/16398996/106474955-b7be1000-64a5-11eb-92ca-f56d922f9a15.png)
## OTAU
![13_otau](https://user-images.githubusercontent.com/16398996/106474980-bd1b5a80-64a5-11eb-904e-37e36db4fd58.png)

**Comment by Smanar** [comment]
Loool, seriously ? a new tuya cluster ?

**Comment by EarlOfBurton** [comment]
> Loool, seriously ? a new tuya cluster ?

Hi @Smanar, I don't get the joke... Do they make so many/too many clusters? I'm fairly new to the "deep dive" into Zigbee...

**Comment by Smanar** [comment]
Lol, no, don't worry, it s just 3/4 months we are on a special cluster for tuya, with all to discover, so much work done, and now we know it better you find a new one.

**Comment by EarlOfBurton** [comment]
Hello friends, are you still missing data from my side, since it has still the mark "incomplete issue"? If so, could you let me know what it is, please?

**Comment by Mimiix** [comment]
@EarlOfBurton Sorry, forgot to update. Busy day.

**Comment by EarlOfBurton** [comment]
Bump to keep it alive.

**Comment by matster75** [comment]
bump

**Comment by musznik** [comment]
bump

**Comment by Smanar** [comment]
You speak about the DDF file ?
Yes, no one know the command used by this device (or at least I haven't find it in google).
But like I have said, this device use a new cluster, so we probably need to write a code part just for it, and atm the priority is more cleaning the actual code than adding more line code.

**Comment by kkoenders** [comment]
When you are going to code new clusters, doe I need to reopen this ticket? Or are you going to track all stale (and closed) tickets requesting integration?

**Comment by Smanar** [comment]
Hu, honestly  if I don't need them, I will not re open closed ticket, there is so much of them.
But you can easily re open them yourself.

The priority will be the migration of old code to the ddf core, so first the already known cluster.
