### ISSUE TITLE
raspbee II not accessable

### ISSUE THREAD

**Issue by rene-mueller** [dresden-elektronik/deconz-rest-plugin#4331]
## Describe the bug

I have restarted my raspi. after that the hardware is not available. i cant reset or access informations

## Screenshots

<img width="889" alt="grafik" src="https://user-images.githubusercontent.com/48084558/106607929-23ff4900-6564-11eb-9c88-6ca1760b109d.png">

## Environment

 - Host system: Raspberry Pi
 - Running method: Homebridge Hue plugin via REST-API to deCONZ
 - Firmware version: not available
 - deCONZ version: deconz/unknown,now 2.07.01-raspbian-buster-stable
 - Device: RaspBee II
 - Is there any other USB or serial devices connected to the host system? If so: Which? NO

**Comment by Mimiix** [comment]
Hi,

The above occurs when the Addon doesn't see the Raspbee. Did you click "Firmware update?" What is your Ha addon config?

**Comment by rene-mueller** [comment]
Hi @Mimiix,
I updated the firmware a few months ago and then restarted everything. I then had to set up the entire zigbee devices again.

```
{
            "name": "Hue",
            "anyOn": true,
            "hosts": [
                "127.0.0.1:4530"
            ],
            "users": {
                "XXXXXXXXXXXXXXX": "XXXXXXXXXX"
            },
            "lights": true,
            "linkButton": false,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "sensors": true,
            "wallSwitch": true,
            "effects": true,
            "platform": "Hue"
        }
```

**Comment by Mimiix** [comment]
I have no clue where that comes from...?

**Comment by rene-mueller** [comment]
Same. Is it possible that the chip is broken?

**Comment by Mimiix** [comment]
Where did you get that json from?

**Comment by rene-mueller** [comment]
From homebridge. Sorry I selected the wrong running method

**Comment by Smanar** [comment]
Just by curiosity what is the result of 

`GCFFlasher_internal -l`

**Comment by rene-mueller** [comment]
@Smanar
```
pi@homebridge:~ $ GCFFlasher_internal -l
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyS0       | 0x0000 | 0x0000  |            | RaspBee
```

**Comment by sonk-ai** [comment]
@rene-mueller @Smanar 
I am having the exact same issue as @rene-mueller RaspBee shown with 0x0000 0x0000 after updating
the Firmware and DeCONZ package following this guide: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian

**Comment by rene-mueller** [comment]
I have already done a general apt update and upgrade. So I should reset the gateway completely. Can you (@sonk-ai) tell me how you did that?

**Comment by Smanar** [comment]
Just to be sure can you check if you still have this line too https://prnt.sc/xx5j5l

**Comment by Smanar** [comment]
How is deconz on homebridge ? it s a normal installation or using VM/docker ?
Are you able to run deconz with logging enabled ?

**Comment by rene-mueller** [comment]
Hey @Smanar it's a normal installation. Can you tell me what I need to do for this?

**Comment by Smanar** [comment]
If you are using desktop > deconz / help / log with "info" "info_l2" "error" "error_l2"
If you are using headless > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags

**Comment by sonk-ai** [comment]
> I have already done a general apt update and upgrade. So I should reset the gateway completely. Can you (@sonk-ai) tell me how you did that?

I actually deleted every Light in DeCONZ-GUI directly and afterwards I also did a "Reset Gateway" in Phoscon. 
>Settings > Gateway

**Comment by rene-mueller** [comment]
@sonk-ai this does not work for me. There is an error that the gateway is not accessible.

**Comment by rene-mueller** [comment]
Before the error (from screenshot):

The interface was accessible but there was no lights. Just one switch. And the reset button also doesn't worked.

**Comment by rene-mueller** [comment]
@Smanar 
[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5925900/deconz.log)

**Comment by rene-mueller** [comment]
@Smanar @Mimiix In the meanwhile i tryed to reset the gateway by deleting the configuration in filesystem. The gateway still didn't set up after that. It didn't find any lamps. After skipping this step, the same screen was shown as in the initial issue above.

**Comment by Mimiix** [comment]
Asked @manup to check this issue.

**Comment by rene-mueller** [comment]
ok @Mimiix in the log file are senetive informations. how can i change the the apikey?

**Comment by Smanar** [comment]
Don't worry, not something dangerous, but to create a new one

`curl http://IP:PORT/api/ -X POST -d '{"devicetype": "Newkey"}'`

To delete it

`curl http://IP:PORT/api/KEY/config/whitelist/OLDKEY -X DELETE`

**Comment by manup** [comment]
>I am having the exact same issue as @rene-mueller RaspBee shown with 0x0000 0x0000 after updating

Note that's always the case 0x0000 0x0000 is shown for RaspBee since it's just a UART connection not providing the vendor/product id's of USB devices.

>After a general apt update and upgrade it all seems to work again, though I had to reset the Gateway completely.

A reset isn't needed, usually such problems are on the basic level like deCONZ connecting to the firmware fails for some reason which needs to be figured out. Sometimes it's the serial port configuration changed after a system update, firmware gone rogue (seen in earlier firmware versions), or Zigbee parameters which need to be checked for modifications.

For the RaspBee II I'd recommend to update to the latest firmware version 0x26690700 as it has quite some fixes.
Did you already have this version installed (I can't tell from the logs)?

**Comment by rene-mueller** [comment]
@manup i have tryed the Update. Now the connection and the software works again. :)

Thank you!

**Comment by Mimiix** [comment]
#caseclosed
