### ISSUE TITLE
Centralite 3-Series Smart Outlet (Type F)

### ISSUE THREAD

**Issue by geelenbert** [dresden-elektronik/deconz-rest-plugin#4332]
## Device

- Product name: 3-Series Smart Outlet (Type F)
- Manufacturer: Centralite
- Model identifier: 3200-de
- Device type : Smart plug

## Screenshots
![image](https://user-images.githubusercontent.com/91923/106632361-f32c0d80-657d-11eb-8e78-e010e4e9367c.png)

![image](https://user-images.githubusercontent.com/91923/106632220-cb3caa00-657d-11eb-8ef2-82f230eab9ec.png)

![image](https://user-images.githubusercontent.com/91923/106632318-e7d8e200-657d-11eb-85d4-75bbb09defae.png)

![image](https://user-images.githubusercontent.com/91923/106632710-5a49c200-657e-11eb-8d94-5c612a045f13.png)

The device looks similar to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/819

![image](https://user-images.githubusercontent.com/91923/106635291-f4126e80-6580-11eb-8792-96fae4e7f93c.png)

**Comment by Mimiix** [comment]
Is it just missing the consumption exposure?
