### ISSUE TITLE
Tuya door window sensor (TS0203)

### ISSUE THREAD

**Issue by pavime** [dresden-elektronik/deconz-rest-plugin#4340]
## Device

- Product name: Tuya Contact Sensor
- Manufacturer: _TYZB01_ncdapbwy
- Model identifier: TS0203
- Device type :
  - Sensor

## Screenshots
![image](https://user-images.githubusercontent.com/66842409/106792335-4b364300-6656-11eb-9b3a-a941eaa5f495.png)
![image](https://user-images.githubusercontent.com/66842409/106792529-859fe000-6656-11eb-8e80-0383082cf6c9.png)
![image](https://user-images.githubusercontent.com/66842409/106792616-a405db80-6656-11eb-9be9-654616fc7c11.png)
![image](https://user-images.githubusercontent.com/66842409/106792762-de6f7880-6656-11eb-869c-ddd709ab7c02.png)

Thank you for your great job
Regards

**Comment by pavime** [comment]
Hello,
I upgraded to version 2.9.3, removed and re-discover this sensor, it's still unknown
Thank you for this so good gateway
Regards

**Comment by Smanar** [comment]
Hello, this sensor is not yet added.
Do you have a linux machine to test code modifications ?

**Comment by pavime** [comment]
Hello,
No, sorry, only a Windows PC and a RPi 4 with HAOS 5.12 and the ConBee II stick
Thank you
