### ISSUE TITLE
Aqara Door & Window Sensor T1 MCCGQ12LM

### ISSUE THREAD

**Issue by AntiHeld889** [dresden-elektronik/deconz-rest-plugin#4343]
## Device

- Product name: Aqara Door & Window Sensor T1 MCCGQ12LM
- Manufacturer: LUMI
- Model identifier: lumi.sensor_magnet.agl02
- Device type :
  - Sensor

## Screenshots

![AQ1](https://user-images.githubusercontent.com/4448275/106901671-593ca000-66f8-11eb-9c93-0835d838b1ca.PNG)
![AQ2](https://user-images.githubusercontent.com/4448275/106901673-59d53680-66f8-11eb-8284-e80b4da94086.PNG)
![AQ3](https://user-images.githubusercontent.com/4448275/106901674-5a6dcd00-66f8-11eb-820e-23612c96c6f2.PNG)
![AQ4](https://user-images.githubusercontent.com/4448275/106901676-5a6dcd00-66f8-11eb-9293-df3ed7132bff.PNG)
![AQ5](https://user-images.githubusercontent.com/4448275/106901678-5a6dcd00-66f8-11eb-97c0-ab2096c172b2.PNG)
![AQ6](https://user-images.githubusercontent.com/4448275/106901681-5b066380-66f8-11eb-925c-b9d67e15bd5b.PNG)
![AQ7](https://user-images.githubusercontent.com/4448275/106901684-5b066380-66f8-11eb-8f24-b0912bee334b.PNG)

**Comment by SwoopX** [comment]
Where did you get those? :)

**Comment by AntiHeld889** [comment]
A few stores on Aliexpress are now offering the new Zigbee 3.0 devices.

for example here:
https://de.aliexpress.com/store/911222034?spm=a2g0o.detail.1000007.1.64873fb2N9MFwT

But you have to look carefully to find the right Zigbee 3.0 devices.
