### ISSUE TITLE
Xiaomi Door Sensor (lumi.sensor_magnet) - incorrect pairing

### ISSUE THREAD

**Issue by Nazarbayevv** [dresden-elektronik/deconz-rest-plugin#4345]
## Describe the question or issue you are having

I add new Xiaomi Door Sensor via Phoscon App and I can see sensor status (open/close) from App, But I can not see any Attributes in claster from Deconz. When I restart deconz, node are disappearing. And sensor status does not change in Phoscon App. I can see record in database, but without swversion info.    
P.S. I have 2 Aqara door semsor, which work fine

## Screenshots

![image](https://user-images.githubusercontent.com/50654913/106958056-83ff1680-6741-11eb-8e5e-70fa44eb5bd7.png)
![image](https://user-images.githubusercontent.com/50654913/106958097-924d3280-6741-11eb-98c6-f9f95313b7ea.png)
![image](https://user-images.githubusercontent.com/50654913/106958121-9a0cd700-6741-11eb-810b-843b04e3715e.png)
![image](https://user-images.githubusercontent.com/50654913/106958149-a3963f00-6741-11eb-9b10-5350832152b5.png)
![image](https://user-images.githubusercontent.com/50654913/106958166-a729c600-6741-11eb-9eff-237ecd92b6bc.png)
![image](https://user-images.githubusercontent.com/50654913/106958181-adb83d80-6741-11eb-9040-8ea14ea6186a.png)
![image](https://user-images.githubusercontent.com/50654913/106958196-b4df4b80-6741-11eb-851f-ca0dfb79fe32.png)
![image](https://user-images.githubusercontent.com/50654913/106958229-bdd01d00-6741-11eb-8e7c-8326ce26318f.png)
![image](https://user-images.githubusercontent.com/50654913/106958247-c45e9480-6741-11eb-945b-c0a98282340a.png)
![image](https://user-images.githubusercontent.com/50654913/106958269-cc1e3900-6741-11eb-8be8-96ba488b42bc.png)
![image](https://user-images.githubusercontent.com/50654913/106958298-d2acb080-6741-11eb-8ac3-06f2554954aa.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26390500
 - deCONZ version: 2.07.01 / 08.12.2020
 - Device: RaspBee I
 - Do you use an USB extension cable:  -
 - Is there any other USB or serial devices connected to the host system? cooler to gpio

**Comment by Nazarbayevv** [comment]
[log_xiaomi_door_sensor.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5928739/log_xiaomi_door_sensor.txt)

**Comment by SwoopX** [comment]
This should solve your challenge https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by Nazarbayevv** [comment]
@SwoopX It's a magic! You solved my issue. Thank you very much:)
