### ISSUE TITLE
Blitzwolf BW-SS7 (tuya stuff)

### ISSUE THREAD

**Issue by handy80** [dresden-elektronik/deconz-rest-plugin#4347]
checked with Smanar in discord if this device was reported/requested already, come out with negative. so here's the details.

## Device

- Product name: Blitzwolf BW-SS7
- Manufacturer: _TYZB01_digziiav
- Model identifier: TS0003
- Device type : (2gang switching relay)
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/16490823/107002666-d9601580-678b-11eb-87f8-4475138e4f8b.png)

![image](https://user-images.githubusercontent.com/16490823/107002723-f399f380-678b-11eb-95b8-856307d08996.png)

maybe additional information to be found here: https://www.zigbee2mqtt.io/devices/BW-SS7.html

after I pressed read on Cluster Info, Infos changed slightly:
![image](https://user-images.githubusercontent.com/16490823/107003156-9e121680-678c-11eb-95cc-9426946e815f.png)

**Comment by handy80** [comment]
and basic Cluster Info, selecting the second channel:
![image](https://user-images.githubusercontent.com/16490823/107003373-f517eb80-678c-11eb-90f7-18ff0f91681b.png)

**Comment by handy80** [comment]
groups:
![image](https://user-images.githubusercontent.com/16490823/107003704-7e2f2280-678d-11eb-92e5-4c8c93882639.png)
scenes:
![image](https://user-images.githubusercontent.com/16490823/107003744-90a95c00-678d-11eb-81ce-cffa9201cd92.png)
on/off:
![image](https://user-images.githubusercontent.com/16490823/107003812-ac146700-678d-11eb-8d0e-04bba9b72253.png)
OTAU:
![image](https://user-images.githubusercontent.com/16490823/107003861-bd5d7380-678d-11eb-87ce-300bd34e0e26.png)
Time:
![image](https://user-images.githubusercontent.com/16490823/107003908-ce0de980-678d-11eb-8095-44dcf08757d8.png)

**Comment by Smanar** [comment]
Ha, my bad, lol was a plug in my mind ^^.
But this device realy seem nice, all cluster in good place, seem realy zigbee compliant.

Exccept your problem with missing endpoint during inclusion, I think using both button during inclusion can help for detection.
