### ISSUE TITLE
TYZB01 light sensor 

### ISSUE THREAD

**Issue by seafoodrice** [dresden-elektronik/deconz-rest-plugin#4348]
## Device

- Product name: Light sensor
- Manufacturer: _TYZB01_4mdqxxnn
- Model identifier: TS0222
- Device type : Please remove all unrelated device types.   
  - Sensor

## Screenshots
![image](https://user-images.githubusercontent.com/6946680/107007137-3983a580-67e6-11eb-89b8-afdcd8b6210f.png)

![image](https://user-images.githubusercontent.com/6946680/107007186-4accb200-67e6-11eb-8d08-88e82c3a2163.png)
![image](https://user-images.githubusercontent.com/6946680/107007262-620b9f80-67e6-11eb-964b-d72bbbb58575.png)
![image](https://user-images.githubusercontent.com/6946680/107007361-88c9d600-67e6-11eb-91aa-f4d343164331.png)

**Comment by appleimperio** [comment]
Im waiting for this one too!

**Comment by kiwikern** [comment]
Is any information needed to add this device? I also have one and am happy to help out.

**Comment by seafoodrice** [comment]
This ticket is not resolved. Any Dev able to help?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mimiix** [comment]
@Smanar  Do you have some time to implement this?

**Comment by Smanar** [comment]
Can try, do you have a linux machine to test code modification ?

**Comment by appleimperio** [comment]
Any dev available for help, if more information is needed just let me know. Thanks

**Comment by Smanar** [comment]
Do you have a linux machine with classic OS to test code modifications ?

**Comment by appleimperio** [comment]
Im not sure if this is what you want but a raspberry pi work, or i need another linux distribution?

**Comment by Smanar** [comment]
Ok so first try

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch TYZB01 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

If you have a small raspberry,it can freeze during compilation, my pi 3 do, so remove "-j2"

Then  try to include the device.

**Comment by appleimperio** [comment]
Im having this error E: Unable to locate package deconz-dev

Thanks for your help

**Comment by Smanar** [comment]
Have you installed deconz on the raspberry too ?
https://phoscon.de/en/conbee2/install#raspbian

This procedure will install too the "package stuff"

**Comment by appleimperio** [comment]
Yes through a Docker and im doing this in the Docker console where the deconz is installed. I also try this steps https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2674#issuecomment-615889079 from another post of yours

**Comment by Smanar** [comment]
Better to use a real OS, docker are virtual one, it s possible, but need lot of skill and I can't help you for that,

**Comment by appleimperio** [comment]
Ok got the plugin compiled. Now when i add the device I get a Ready message but no new device is added. Thanks

**Comment by Mimiix** [comment]
@appleimperio did you check the rest api?

**Comment by appleimperio** [comment]
Yes its in there. I don't know where to see if the values are changing but since its a light sensor when i cover and uncover it the green light next to the device in the rest api start blinking. What else i can do to help make this work. Thanks!

**Comment by Smanar** [comment]
>the green light next to the device in the rest api start blinking

You don't mean deconz instead ? The api don't have interface.
It's strange this kind of device is not visible in phoscon, but you haven't third app to make test ?
Else take a look direclty in the api `http://IP:PORT/api/KEY/sensors`

IP and PORT are the same than for deconz and KEY is a deconz API key.

**Comment by appleimperio** [comment]
Ok this what im getting 
"ep":1,"etag":"d2da5f3a60f75eb24fb5c86af027670e","lastseen":"2021-04-08T14:51Z","manufacturername":"Tuya","modelid":"TS0222","name":"LightLevel 17","state":{"dark":false,"daylight":false,"lastupdated":"2021-04-08T14:51:26.110","lightlevel":14625,"lux":29},"type":"ZHALightLevel","uniqueid":"5c:02:72:ff:fe:c7:2c:13-01-0400"},"3":{"config":{"alert":"none","battery":87,"delay":180,"duration":60,"group":"1","on":true,"reachable":true}

**Comment by Smanar** [comment]
Nice thx ^^, making the PR

**Comment by appleimperio** [comment]
Thank you very much!
