### ISSUE TITLE
Zemismart Tuya Zigbee Wall Switch 2 Gang (TS0042, _TZ3000_adkvzooy)

### ISSUE THREAD

**Issue by JasperMC** [dresden-elektronik/deconz-rest-plugin#4349]
## Device

- Product name: Zemismart Tuya Zigbee Wall Switch 2 Gang 
- Link to product: https://nl.aliexpress.com/item/4001227549409.html?spm=a2g0s.9042311.0.0.4d764c4dORIR1I
- Manufacturer: _TZ3000_adkvzooy
- Model identifier: TS0042
- Device type:
  - Switch

Current behavior: On an older version of deconz (tested a few months ago) the two switches were identified as lights instead of switches, but pressing the buttons didn't toggle the virtual lights. In my current version of deconz (Version 2.09.00, ConBee II on firmware 26680700, deconz running in docker) the device does not register in the GUI but is visible in the VNC application. I also don't see any events happening while listening to deconz_event in Home Assistant

There are also variants of this device with one or three switches. From what I can see, those use the same PCB design and chips.

Pictures of the device:

Assembled:
![image1](https://user-images.githubusercontent.com/37154053/107030239-a11efe00-67b0-11eb-984f-6fc2a3ae74c3.jpeg)

Disassembled:
![image0](https://user-images.githubusercontent.com/37154053/107030273-ac722980-67b0-11eb-8cc7-3aad413e860a.jpeg)

## Screenshots

Clusters:
<img width="137" alt="Device Clusters" src="https://user-images.githubusercontent.com/37154053/107029168-e4786d00-67ae-11eb-8e8d-894da24e7ea2.png">

Node Info:
<img width="422" alt="Node Info" src="https://user-images.githubusercontent.com/37154053/107029296-15f13880-67af-11eb-8b9b-e02626ff5069.png">

Basic cluster:
<img width="429" alt="Basic Cluster" src="https://user-images.githubusercontent.com/37154053/107029051-b561fb80-67ae-11eb-945e-10c1d6225026.png">

Power Configuration:
<img width="487" alt="Power Configuration Cluster" src="https://user-images.githubusercontent.com/37154053/107029671-b0ea1280-67af-11eb-9267-4c83adb5ce86.png">

OTAU Cluster:
<img width="427" alt="OTAU Cluster" src="https://user-images.githubusercontent.com/37154053/107029418-45a04080-67af-11eb-9bcf-4c3cede51cb7.png">

**Comment by Smanar** [comment]
Added here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4157 
Do you have a linux machine to test the modification ?

**Comment by JasperMC** [comment]
> Added here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4157 
> 
> Do you have a linux machine to test the modification ?

Thank you sir. I'm running on Docker currently but I can spin up a VM to try. Could you share the instructions for getting the right branch/version to test?

**Comment by Smanar** [comment]
Full explanation here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

```
sudo apt install deconz-dev
git clone --branch tuya_switch https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by JasperMC** [comment]
Thanks! I'm having immense trouble installing deconz-dev. I tried the apt install and the suggested method in #2811, but I keep getting "Unexpected (" syntax error on this line:

```
sudo sh -c "echo 'deb http://phoscon.de/apt/deconz (cat /etc/os-release | grep -oP '(?<=VERSION_CODENAME\=).*')-beta main' > /etc/apt/sources.list.d/deconz.list"

**Comment by JasperMC** [comment]
Hi Smanar,

I've managed to compile the plugin.

I can now successfully pair the switch in the Phoscon Web App. After doing so, it appears as a Switch under switches but still creates two lights (On/Off 9 and On/Off 10 in my case) that don't really do anything. I don't see any data coming through either when I listen for deconz_event in Home Assistant.

Don't know if that is expected behavior, just sharing my findings so far :)

**Comment by Smanar** [comment]
Yes and no ^^.
It s notmal you have it, but weneed to prevent it.

ATM deconz have some problem to reconize tuya stuff, they are a little "exotic".

For this kind of devices you will have 2 (or more ) useless entries in "lights" sections.
You can delete them using the API, it s possible too with some third app, else using command line

`curl -X DELETE http://IP:PORT/api/KEY/lights/ID`

**Comment by JasperMC** [comment]
Thanks! I'll give the deleting a try. As for now, pressing the buttons is not coming through yet.

If there's anything I can do to help let me know. Screenshots or doing a screenshare 😊

**Comment by Smanar** [comment]
>As for now, pressing the buttons is not coming through yet.

Ha, this is not normal, on the "sensor" entry, you need to have a field "buttonevent" and this field containt the button value.

**Comment by JasperMC** [comment]
Where would I find the sensor entry? In a GUI or the API?

**Comment by Smanar** [comment]
Ha yes , my bad.
If you have just compiled the code, you have the new api code, but still the old json, the file is called  button_maps.json.
On raspberry you can find it in /usr/share/deCONZ/devices

The modification is here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4157/commits/39a33e9a14cfb1017ed753161ea0d49120c14b90#diff-a3adce467fe93b9c612c198c187dad34f5284d6c9adf66aa28127f0f619979b5

**Comment by JasperMC** [comment]
Thanks! I updated the mapping and the switch works perfectly now :) 

I see you comitted the changed to master. Are they in the Roanoke 2.9.3? Where possible, I'd like to stay on the official releases vs the compiled plugin for testing :)

**Comment by Smanar** [comment]
Easy to check, this issue will be closed when the PR will be validated. So not yet.

**Comment by JasperMC** [comment]
> Easy to check, this issue will be closed when the PR will be validated. So not yet.

Clear, thanks! I tested the button extensively and all features are working from what I can see. Short press, double press and long press work fine on all buttons.
