### ISSUE TITLE
Sonoff SNZB-03 MotionSensor - random detections

### ISSUE THREAD

**Issue by chrisma4600** [dresden-elektronik/deconz-rest-plugin#4360]
## Describe the bug

I have 2 Sonoff SNZB-03 Motion Sensors installed in my enviroment. Both of them recognize motion even though there is no motion.
I can not see any regularity.  The motion ist detected between 1 and 2 hours also at daytime as in night.   I can rule out, that theire ist any motion in deed the sensor triggers motion
Both Sensors have same behavior

## Steps to reproduce the behavior

use a SNZB-03   you will see

## Expected behavior

to trigger motion only when motion is 
## Screenshots

![image](https://user-images.githubusercontent.com/78685309/107145655-774a1080-6943-11eb-8479-c208b6eaaee6.png)
![image](https://user-images.githubusercontent.com/78685309/107145687-9a74c000-6943-11eb-86e2-c1292bde291c.png)
![image](https://user-images.githubusercontent.com/78685309/107145713-b5473480-6943-11eb-9b78-4634831fbb6c.png)
![image](https://user-images.githubusercontent.com/78685309/107145729-c8f29b00-6943-11eb-822f-39acc287725c.png)
![image](https://user-images.githubusercontent.com/78685309/107145739-e3c50f80-6943-11eb-9f2a-9f1c7b514827.png)

## Environ

 - Host system: Raspberry Pi 
 - Running method: Raspbian
 - Firmware version: 26690700
 - deCONZ version:  2.09.01
 - Device: RaspBee II
 - Do you use an USB extension cable: 

- i use IOBROKER the  deconz adapter to switch lights on and off with a simply blokly script; the trigger is the presence item of the objects
- battery of the sensor i changed multiple times to be sure

**Comment by LindsayReid** [comment]
I too have the same random motion detects. I thought it might be a battery problem but tried a new one and still get spurious alerts.

**Comment by Mimiix** [comment]
Someone reported this earlier (there's a few issues) somewhere, i picked up this url: https://tech.scargill.net/another-itead-sonoff-week/#comment-69873

It is the device that seems to be unreliable here and there's nothing we can do about that 😢.

**Comment by chpego** [comment]
Hi there !
2 of my 4 sensors were not working properly, I decided to open the box of all the sensors and lift up the switch with the battery, then close the box again, and strangely one of the two that had the weird behavior (every 90 minutes) disappeared.
I'm not sure if it's just a hardware problem either.

**Comment by joshhodgson** [comment]
I'm getting this too, though I doubt it's a deconz issue!

**Comment by Mimiix** [comment]
As this seems to be a hardware issue, i suggest closing this issue for now as we can't do anything to fix it.
