### ISSUE TITLE
Can't find Hue Lights from Raspbee II

### ISSUE THREAD

**Issue by ikon106** [dresden-elektronik/deconz-rest-plugin#4362]
## Describe the question or issue you are having
I am trying to find my Hue lights in Phoscon. I have a RasPi with the Raspbian Buster Desktop imaged onto it. I've searched several times, including a 10-min session with no success. The distance between the light and RaspBee is about 2-3 m, with a thin wall in-between. Initially they were still connected to my (unplugged) bridge. However I removed the lights from it, and they still weren't found by the RaspBee.

My main goal was to use Home Assistant, but the add-on wouldn't even connect to the network. When I was running HAss it was connected to my network through WiFi, but now it's connected by Ethernet.

## Screenshots
  N/A

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 0x26610700)
 - deCONZ version: 2.07.01
 - Device: RaspBee II
 - Do you use an USB extension cable: (yes / no) -- N/A
 - Is there any other USB or serial devices connected to the host system? If so: Which? A case fan. Connected to GPIO pins 17 (3V) and 20 (Ground)

## deCONZ Logs
  The log from a 10 min search, after having removed the lights from the Hue Bridge: https://pastebin.com/thSFqety

## Additional context
  The Hue lights are;
 - 1 Hue White and Color (the only one on in the pasted search)
 - 1 Lux (turned off)

**Comment by manup** [comment]
Usually the easiest approach to move lights from the Hue bridge to deCONZ network is:

1. Start light search in the Phoscon App (might be helpful to raise search time in the Phoscon App Gateway Settings);
2. In the Hue App delete the light while it is powered and paired;
3. The Hue bridge now sends a reset command to the light and it will automatically join the deCONZ network.

Since the lights didn't join to the deCONZ network yet I guess they aren't in factory new state, the logs also show no indication of a Hue light joining. You might need to pair them to the Hue bridge again and try above steps.

**Comment by ikon106** [comment]
I re-paired them to the bridge and started a 10-min search in phoscon. Towards the beginning of the search, I deleted the lights from the Hue app. Phoscon was still not able to find them.
Here is the debug from right before the beginning of the search to right after I deleted the lights from the Hue app: https://pastebin.com/nqMyYm3p
Here is the debug from the full search, incuding the above paste: https://pastebin.com/H19tQkex

**Comment by ikon106** [comment]
I forgot to mention that the Hue Bridge is v1 (the round one). I don't know if that's relevant.

**Comment by ikon106** [comment]
I still have not received a solution to my problem.

**Comment by Mimiix** [comment]
What happens when you remove the fan from the RPI? Also: What case are you using?

**Comment by ikon106** [comment]
Thanks for answering, unfortunately, unplugging the fan from the RPI did nothing.
I am using the following [case.](https://www.amazon.se/gp/product/B07V2ZLB9K/ref=ppx_yo_dt_b_asin_title_o01_s02?ie=UTF8&psc=1)

**Comment by wvrneer** [comment]
I have a similar problem. No way to connect a Osram Lightify Flex strip on a new Raspbee II.
Before, the strip was successfully connected on a Raspbee.
For testing I resetted the strip serveral times and tried to connect it alternately on both devices.
Every search was successful with Raspbee, but not a single one with Raspbee II.

Is there a problem with Raspbee II ?

**Comment by Adam-Langley** [comment]
@wvrneer I have had trouble connecting to all my devices using a brand new Raspbee II. Nothing worked to the point I was wondering if the Raspbee II was DOA.
After moving the Raspbee II away from other sources of possible radio interference (my Ubiquiti switch), and moving closer to the device I was attempting to pair with, all the problems went away. It appears once paired, the connection is much more tolerant to a noisy radio environment - possible the pairing process is just more dependent on a strong connection (i.e, timing related?)
