### ISSUE TITLE
Lidl wireless doorbell and phoscon

### ISSUE THREAD

**Issue by dodo124** [dresden-elektronik/deconz-rest-plugin#4367]
## Describe the question or issue you are having
  Hello and good evening.

I´m working with deconz and phoscon for a few month and it is working flawlessly.

And last week I bought a Lidl Smart Home Wireless Doorbell.  And it´s not working as it is supposed to do.

It is found in the deconz app an bond to the conbee2 (running on my RPi). Furthermore the bell is responding inside deconz (responding to the press of the button) but nothing else.

I can´t bind it to anything within phoscon?

## Environment

 dPhoscon =  26680700
deCONZ = 2.09.91

  - Host system: (Raspberry Pi /  Conbee2)
 - Running method: (Raspbian)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.09.91)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) 
 - Is there any other USB or serial devices connected to the host system? Yes: Touchdisplay of the RPi.

## Additional context

  Any idea what´s wrong or how to fix this?

I was unable to find any issue about this doorbell via google, so maybe I do something the wrong way?

Help is welcome

**Comment by T0mWz** [comment]
Pllease, see; https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4260

**Comment by SwoopX** [comment]
The device is not yet supported, hence it is not usable via REST API. Even it it would, that doesn't automatically mean it is visible in Phoscon, as it is a different software. You might want to consider raising a support request at the Phoscon beta repository upfront and reference the corresponding issue here.

Also, please use the search for issues next time to avoid any duplicates. The issue has been shared above.

**Comment by kejXero** [comment]
A litle bit off topic, but could you tell how you added the doorbell to Deconz? I have tried adding it a switch and a sensor without any luck.
