### ISSUE TITLE
 RaspBee II / ConBee II - can't add devices

### ISSUE THREAD

**Issue by schneidermarc** [dresden-elektronik/deconz-rest-plugin#4381]
## RaspBee II / ConBee II - can't add devices

I am completely lost ...

A few days ago I installed my RaspBee II and added the first devices.
At some point I lost the connection to my Zigbee devices.

Since I couldn't find the error and I had only added 10 devices - I decided to:
1. delete the Deconz container
2. delete the linked config folder
3. reboot
4. update the firmware again
5. re-deploy the container

... and try to start with a fresh installation to add the devices as the installation before.

I reset the devices and put them into bind mode but I can't find anything with the Phoscon PWA.

I tried to re-bind:
- Phillips Hue Light Bulbs
- Osram SMART+ Plugs
- Ubisys J1

After a few tries I re-added the devices via Hue Bridge to make sure that they are in bind mode and that worked fine. In the next step I removed the devices again and tried to add it via the Phoscon GW - nothing to find.

I tried it this way:
@manup #4381
> Usually the easiest approach to move lights from the Hue bridge to deCONZ network is:
> 
> Start light search in the Phoscon App (might be helpful to raise search time in the Phoscon App Gateway Settings);
> In the Hue App delete the light while it is powered and paired;
> The Hue bridge now sends a reset command to the light and it will automatically join the deCONZ network.
> Since the lights didn't join to the deCONZ network yet I guess they aren't in factory new state, the logs also show no indication of a Hue light joining. You might need to pair them to the Hue bridge again and try above steps.

But no chance to find devices.

At this point I thought my RaspBee 2 is defective and I bought a Conbee 2 to check.
Unfortunately, I have the same result with ConBee 2 :-(

I repeated _my installation steps_ (2-4) with both devices and tried different Zigbee channels - same result.

## Environment
Raspberry Pi 4 8GB
_- USB Boot from SSD (no other devices connected)_
Docker version 20.10.2, build 2291f61
Deconz Version: 2.09.01
Phoscon Version: 23.12.2020
ConBee II Firmware: 0x26680700
RaspBee II Firmware: 0x26680700
USB extension cable: no
Zigbee Channel: 11

## My Installation Steps

1. /boot/config.txt:
```text
dtparam=audio=on
max_usb_current=1
dtoverlay=disable-bt
dtoverlay=disable-wifi
enable_uart=1
dtoverlay=pi3-miniuart-bt
dtoverlay=uart0-full
core_freq=250
dtoverlay=pi3-miniuart-bt-overlay
```

2. Update Firmware
```console
root@raspberrypi:/home/pi# sudo GCFFlasher_internal -t 60 -d /dev/ttyACM0 -f  deCONZ_ConBeeII_0x26680700.bin.GCF
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2401245-if00 (ConBee II)
deCONZ firmware version 26680700
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
flashing 164373 bytes: |==============================|
verify: .
SUCCESS
Wait 10 seconds until application starts
deCONZ firmware version 26680700
```

3. Reboot

4. Deploy Docker Image
```console
docker run -d \
   --name=deCONZ \
   --network=smart-home \
   -p=8000:80 \
   -p=5901:5900 \
   --restart=always \
   -v /etc/localtime:/etc/localtime:ro \
   -v /docker/deCONZ/:/root/.local/share/dresden-elektronik/deCONZ \
   -v /docker/deCONZ_OTAU:/root/otau \
   --device=/dev/ttyACM0 \
   -e DECONZ_DEVICE=/dev/ttyACM0 \
   -e DECONZ_VNC_MODE=1 \
   -e DECONZ_VNC_PORT=5900 \
   -e  DECONZ_VNC_PASSWORD=password \
   marthoc/deconz:lastest
```
Update:
Also --net=host don't solve it.
And a native deCONZ installation without docker ended with the same result.

## Screenshots
![Network Settings](https://i.paste.pics/c93055c338b7fb0a806624b33f40c7b8.png?trs=2b90c93eb27d7ffe9aabec6abd895d47a3139c4c6f2a17ba0b0864e10e71f6da)

## deCONZ Logs
```console
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.09.01
[marthoc/deconz] Web UI port: 80
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC port: 5900

New '2451731ab0da:0 (root)' desktop at :0 on machine 2451731ab0da

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/2451731ab0da:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd 2451731ab0da:0 to connect to the VNC server.

14:32:35:845 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
14:32:35:859 CTRL. 3.27.214:32:36:000 dev /dev/ttyAMA0
14:32:36:000 COM: /dev/ttyACM0 / serialno: , ConBee II
14:32:36:001 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
14:32:36:193 parent process /bin/sh
14:32:36:194 gw run mode: docker
14:32:36:194 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
14:32:36:202 DB sqlite version 3.27.2
14:32:36:204 DB PRAGMA page_count: 0
14:32:36:205 DB PRAGMA page_size: 4096
14:32:36:205 DB PRAGMA freelist_count: 0
14:32:36:205 DB file size 0 bytes, free pages 0
14:32:36:206 DB PRAGMA user_version: 0
14:32:36:206 DB upgrade to user_version 1
14:32:36:442 DB write sqlite user_version 1
14:32:36:449 DB PRAGMA user_version: 1
14:32:36:449 DB upgrade to user_version 2
14:32:36:466 DB write sqlite user_version 2
14:32:36:474 DB PRAGMA user_version: 2
14:32:36:474 DB upgrade to user_version 6
14:32:36:496 DB write sqlite user_version 6
14:32:36:502 DB PRAGMA user_version: 6
14:32:36:503 DB upgrade to user_version 7
14:32:36:520 DB write sqlite user_version 7
14:32:36:527 DB PRAGMA user_version: 7
14:32:36:527 DB cleanup
14:32:36:528 DB create temporary views
13:32:36:540 started websocket server at port 443
13:32:36:544 create default username and password
13:32:36:553 [INFO] - Found file containing button maps. Parsing data...
13:32:36:559 [WARNING] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...
13:32:36:570 [INFO] - Button maps loaded.
13:32:36:573 dlg action: Read binding table
13:32:36:574 found node plugin: libde_rest_plugin.so - REST API Plugin
13:32:36:580 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
13:32:36:619 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
13:32:36:679 dev /dev/ttyAMA0
13:32:36:680 COM: /dev/ttyACM0 / serialno: , ConBee II
13:32:37:771 dev /dev/ttyAMA0
13:32:37:772 COM: /dev/ttyACM0 / serialno: , ConBee II
13:32:37:787 COM check bootloader
13:32:37:800 COM detected application
13:32:37:865 Device firmware version 0x26680700 ConBee II
13:32:37:869 unlocked max nodes: 200
13:32:37:941 Device protocol version: 0x010E
13:32:37:950 new node - ext: 0x00212effff0693de, nwk: 0x0000
13:32:38:063 Current channel 11
13:32:38:075 CTRL got nwk update id 8
13:32:38:079 CTRL ANT_CTRL 0x03
13:32:38:108 Device protocol version: 0x010E
13:32:38:187 Current channel 11
13:32:38:199 CTRL got nwk update id 8
13:32:38:203 CTRL ANT_CTRL 0x03
13:32:38:227 Device protocol version: 0x010E
13:32:38:311 Current channel 11
13:32:38:323 CTRL got nwk update id 8
13:32:38:327 CTRL ANT_CTRL 0x03
13:32:38:386 DB UPDATE device_descriptors SET data = x'10400f3511472b0040002b0000', timestamp = 1612877558 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:21:2e:ff:ff:06:93:de') AND endpoint = 0 AND type = 2
13:32:38:387 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'10400f3511472b0040002b0000', 1612877558 FROM devices WHERE mac = '00:21:2e:ff:ff:06:93:de'
13:32:38:482 DB UPDATE device_descriptors SET data = x'0104010500010300000a00190003010020000005', timestamp = 1612877558 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:21:2e:ff:ff:06:93:de') AND endpoint = 1 AND type = 4
13:32:38:482 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 1, 4, x'0104010500010300000a00190003010020000005', 1612877558 FROM devices WHERE mac = '00:21:2e:ff:ff:06:93:de'
13:32:38:563 DB UPDATE device_descriptors SET data = x'f2e0a164000100012100', timestamp = 1612877558 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:21:2e:ff:ff:06:93:de') AND endpoint = 242 AND type = 4
13:32:38:564 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 242, 4, x'f2e0a164000100012100', 1612877558 FROM devices WHERE mac = '00:21:2e:ff:ff:06:93:de'
13:32:38:702 ZDP discovery done in 284 ms13:32:41:899 dev /dev/ttyAMA0
13:32:41:902 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
13:32:41:903 GW firmware version: 0x26680700
13:32:41:903 GW firmware version is up to date: 0x26680700
13:32:42:092 Announced to internet https://phoscon.de/discover
13:32:42:093 discovery server date: Tue, 09 Feb 2021 13:32:42 GMT
13:32:42:093 	 local time seems to be ok
13:32:48:550 saved node state in 0 ms
13:32:48:574 sync() in 23 ms
13:32:56:546 Set bridgeid to 00212EFFFF0693DE
13:33:07:543 created username: 57B9543A74, devicetype: Phoscon#B1707x1219
13:33:28:968 Updated password hash: $1$8282jdkm$/dTTIhovhWU7IuI.Vb2mU.
13:33:28:989 created username: 2DC3A196B6, devicetype: Phoscon#B1707x1219
13:33:35:547 send permit join, duration: 59
13:33:35:548 send GP proxy commissioning mode
13:33:35:561 Current channel 11
13:33:35:565 CTRL got nwk update id 8
13:33:35:569 Device TTL 3440 s flags: 0x7
13:33:44:549 LightNode 1: Configuration tool 1 added
13:33:44:551 drop request to zombie (rx = 0)
13:34:34:547 send permit join, duration: 0
13:34:35:349 Search sensors done
13:34:35:571 Current channel 11
13:34:35:575 CTRL got nwk update id 8
13:34:35:579 Device TTL 3380 s flags: 0x7
13:34:36:547 send permit join, duration: 59
13:34:36:547 send GP proxy commissioning mode
13:35:35:546 send permit join, duration: 59
13:35:35:547 send GP proxy commissioning mode
13:35:35:562 Current channel 11
13:35:35:566 CTRL got nwk update id 8
13:35:35:570 Device TTL 3320 s flags: 0x7
13:35:36:256 Search sensors done
13:36:07:145 Search sensors done
13:36:07:274 Search sensors done
13:36:32:161 Search sensors done
13:36:32:546 send permit join, duration: 0
13:36:33:018 Search sensors done
13:36:35:568 Current channel 11
13:36:35:572 CTRL got nwk update id 8
13:36:35:576 Device TTL 3260 s flags: 0x7
13:36:35:914 set gwNetworkOpenDuration to: 180
13:36:41:636 dev /dev/ttyAMA0
13:36:41:637 GW firmware version: 0x26680700
13:36:41:637 GW firmware version is up to date: 0x26680700
13:37:07:547 send permit join, duration: 59
13:37:07:548 send GP proxy commissioning mode
13:37:35:563 Current channel 11
13:37:35:567 CTRL got nwk update id 8
13:37:35:571 Device TTL 3200 s flags: 0x7
13:38:06:546 send permit join, duration: 59
13:38:06:547 send GP proxy commissioning mode
13:38:35:562 Current channel 11
13:38:35:566 CTRL got nwk update id 8
13:38:35:570 Device TTL 3140 s flags: 0x7
13:39:03:576 Search sensors done
13:39:04:547 send permit join, duration: 0
13:39:35:569 Current channel 11
13:39:35:575 CTRL got nwk update id 8
13:39:35:580 Device TTL 3080 s flags: 0x7
13:40:35:570 Current channel 11
13:40:35:575 CTRL got nwk update id 8
13:40:35:579 Device TTL 3020 s flags: 0x7
13:40:41:634 dev /dev/ttyAMA0
13:40:41:635 GW firmware version: 0x26680700
13:40:41:635 GW firmware version is up to date: 0x26680700
13:41:35:568 Current channel 11
13:41:35:573 CTRL got nwk update id 8
13:41:35:577 Device TTL 2960 s flags: 0x7
13:42:35:569 Current channel 11
13:42:35:575 CTRL got nwk update id 8
13:42:35:582 Device TTL 2900 s flags: 0x7
13:42:48:550 saved node state in 0 ms
13:42:48:558 sync() in 7 ms
13:43:35:569 Current channel 11
13:43:35:574 CTRL got nwk update id 8
13:43:35:581 Device TTL 2840 s flags: 0x7
13:44:35:572 Current channel 11
13:44:35:578 CTRL got nwk update id 8
13:44:35:585 Device TTL 2780 s flags: 0x7
13:44:41:628 dev /dev/ttyAMA0
13:44:41:629 GW firmware version: 0x26680700
13:44:41:629 GW firmware version is up to date: 0x26680700
13:45:35:573 Current channel 11
13:45:35:580 CTRL got nwk update id 8
13:45:35:587 Device TTL 2720 s flags: 0x7
13:46:35:571 Current channel 11
13:46:35:578 CTRL got nwk update id 8
13:46:35:585 Device TTL 2660 s flags: 0x7
13:47:35:570 Current channel 11
13:47:35:576 CTRL got nwk update id 8
13:47:35:583 Device TTL 2600 s flags: 0x7
13:48:35:563 Current channel 11
13:48:35:567 CTRL got nwk update id 8
13:48:35:571 Device TTL 2540 s flags: 0x7
13:48:41:639 dev /dev/ttyAMA0
13:48:41:641 GW firmware version: 0x26680700
13:48:41:641 GW firmware version is up to date: 0x26680700
13:49:35:567 Current channel 11
```

**Comment by Smanar** [comment]
So first, thx for your issue, lol, I think I have never see an issue with so much information ^^.
Now if you have a Raspbee why are you using conbee firmware ?

**Comment by schneidermarc** [comment]
> So first, thx for your issue, lol, I think I have never see an issue with so much information ^^.
> Now if you have a Raspbee why are you using conbee firmware ?

I wrote:
> At this point I thought my RaspBee 2 is defective and I bought a Conbee 2 to check.
> Unfortunately, I have the same result with ConBee 2 :-(

I flashed both devices with the correct firmware :-)

**Comment by bsheepdiy** [comment]
A new stable version of deCONZ is out today 2.09.02, check if you still have the issue.
You could try using an USB extension cable.

If you could not add new device, maybe your zigbee channel interfere with some existing Wi-Fi network. Use Wifi scan on your smartphone to scan WiFi network. (see https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html)

Another solution, sniff zigbee using CC2531 with snif firmware to watch in deep Zigbee trames.

**Comment by Smanar** [comment]
> I flashed both devices with the correct firmware :-)

Lol, my bad, too much informations to read this time ^^.

But if you have a conbee, will be better, after have made the bsheepdiy suggestion (USB extension and avoid usb 3.0), if you still have the issue, can you make a try on a PC machine ?

**Comment by Mimiix** [comment]
AS other mentioned: Try a extension cable. Both for the SSD and Conbee. 

What also might be worth your while, to confirm if theres any interference:  Put your OS on a SD card and remove the SSD.

**Comment by schneidermarc** [comment]
@Smanar @Mimiix thank you for your helpful comments! :-)

The last few days I had so many test scenarios and nothing seemed to solve the problem.
With a new Raspberry PI OS installation on a fresh SD-Card I was able to find devices again for the first time.

To keep it short, it was not the SSD, the power supply or something with interferences - **after resetting the GPIO settings in the Raspi-Config everything worked fine** with my old setup.

But to keep in mind - nothing has changed since the last time everything worked fine. I think it's a Raspbian OS Bug (maybe ;-) )

**Comment by schneidermarc** [comment]
Btw why it didn't work with the Conbee either, I didn't find out.

**Comment by Smanar** [comment]
There is a reset procedure in raspi-config for GPIO ?

**Comment by hixus** [comment]
> @Smanar @Mimiix thank you for your helpful comments! :-)
> 
> The last few days I had so many test scenarios and nothing seemed to solve the problem.
> With a new Raspberry PI OS installation on a fresh SD-Card I was able to find devices again for the first time.
> 
> To keep it short, it was not the SSD, the power supply or something with interferences - **after resetting the GPIO settings in the Raspi-Config everything worked fine** with my old setup.
> 
> But to keep in mind - nothing has changed since the last time everything worked fine. I think it's a Raspbian OS Bug (maybe ;-) )

I'm facing similar situation but did only find remote GPIO setting from raspi-config. Could you elaborate what did "resetting the GPIO settings in the Raspi-Config" require?

**Comment by Smanar** [comment]
You have same results when trying to update the firmware ?

**Comment by hixus** [comment]
> You have same results when trying to update the firmware ?

This was with latest stable firmware but after trying latest beta it seems to work fine.
