### ISSUE TITLE
ROBB smarrt ROB_200-010-0 version 2.5.3_r48 (version 2.5.3_r46 works)

### ISSUE THREAD

**Issue by etmrugl** [dresden-elektronik/deconz-rest-plugin#4382]
## Device

- Product name: ROB_200-010-0
- Manufacturer: ROBB smarrt
- Model identifier: ROB_200-010-0
- Device type : 
  - Other: Window Covering Controller (shutter)

## Screenshots
![image](https://user-images.githubusercontent.com/60889628/107379903-adc38f00-6aed-11eb-8e23-bbd7f8cfd933.png)
![image](https://user-images.githubusercontent.com/60889628/107379980-c0d65f00-6aed-11eb-9edf-794b7847fb67.png)
![image](https://user-images.githubusercontent.com/60889628/107380276-05fa9100-6aee-11eb-9b4f-1e1df950f39e.png)

I attached a log. The not-working module is: 15:52:55:626 LightNode 35: Rolluik Keuken added

[deCONZ.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5952160/deCONZ.log)

I can see the node in the deCONZ-Conbee II windows on the Raspberry and I see the node in the Phoscon App. The node does NOT respond to any command.

**Comment by Mimiix** [comment]
Can you please add all cluster screenshots?

**Comment by etmrugl** [comment]
Is this what you ar elooking for? I am not sure if I understand your question.
![image](https://user-images.githubusercontent.com/60889628/107494989-c71d1780-6b8f-11eb-8af2-b692f6d17393.png)

**Comment by etmrugl** [comment]
![image](https://user-images.githubusercontent.com/60889628/107495886-f2543680-6b90-11eb-99f1-19b1188e98ee.png)
![image](https://user-images.githubusercontent.com/60889628/107495966-0730ca00-6b91-11eb-8052-65e3021b2827.png)
![image](https://user-images.githubusercontent.com/60889628/107496009-16177c80-6b91-11eb-8174-edd130154fb3.png)
![image](https://user-images.githubusercontent.com/60889628/107496064-24fe2f00-6b91-11eb-93c3-6b3dba520878.png)
![image](https://user-images.githubusercontent.com/60889628/107496130-3b0bef80-6b91-11eb-8bce-6d4ba9107d79.png)
![image](https://user-images.githubusercontent.com/60889628/107496213-4fe88300-6b91-11eb-8708-c04e42bc956a.png)
![image](https://user-images.githubusercontent.com/60889628/107496249-5aa31800-6b91-11eb-957e-f742802ecbe3.png)
![image](https://user-images.githubusercontent.com/60889628/107496381-83c3a880-6b91-11eb-88c1-bbebee03813e.png)
![image](https://user-images.githubusercontent.com/60889628/107496397-8b834d00-6b91-11eb-8d8d-aad81755290d.png)
![image](https://user-images.githubusercontent.com/60889628/107496475-a6ee5800-6b91-11eb-8311-05031f829fe6.png)
![image](https://user-images.githubusercontent.com/60889628/107496512-afdf2980-6b91-11eb-9311-9292a220c5be.png)

**Comment by etmrugl** [comment]
It gets weirder...
![image](https://user-images.githubusercontent.com/60889628/107496928-37c53380-6b92-11eb-90d9-cfb226c51813.png)

If I use the 'exec' button at Down/close the shutter closes. Also works with the 'exec' button Up/Open. The shtter does not work in the Phoscon App

**Comment by SwoopX** [comment]
What's weird operating a device as it is supposed to be?

You said you can't control it via Phoscon. Well, I also can't control mine, so nothing extraordinary from my perspective. How would one do that at all?

**Comment by etmrugl** [comment]
version 2.5.3_r46 can be controlled in Phoscon as a light on/off. In Domoticz I defined this device as a inverted blind. and voila, it works.

The weird thing is that version 2.5.3_r48 can be controlled through the exec function in the Window covering cluster. In the Phoscon app I see the module as a light, but commands do not work.

**Comment by etmrugl** [comment]
Do I need to add more information?
