### ISSUE TITLE
OTA update Headless

### ISSUE THREAD

**Issue by MeandtheDevilknockingonyourdoor** [dresden-elektronik/deconz-rest-plugin#4389]
## Describe the question or issue you are having

Is it possible to do a OTA update without Gui on a headless system?

## Environment

 - Host system: Raspberry
 - Running method: Rasbian Headless
 - Firmware version: 26680700
 - deCONZ version: 2.09.02 / 23.12.2020
 - Device: ConBee II
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? No

**Comment by Mimiix** [comment]
Nope. You need the gui :)

other option would be to follow this:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Access-deCONZ-GUI-in-headless-setups

**Comment by Smanar** [comment]
It s not possible for sensor, but it s for light nope ?
If files are at good place, and if you enable the option in the old webapp, it don't work ?

**Comment by MeandtheDevilknockingonyourdoor** [comment]
Ok, no with the vnc I try but it didn’t work. 
where is a good place for the updates?
Thx

**Comment by Smanar** [comment]
You can find some informations here 
https://github.com/dresden-elektronik/deconz-ota-plugin
https://phoscon.de/en/support#ota-update-osram-devices

But from my memory it can work without the GUi for light, just need to enable the feature, what is your brand and device ?

**Comment by MeandtheDevilknockingonyourdoor** [comment]
Ok I will check it,

I have only ikea and hue lights and in the future a ikea motion sensor.
