### ISSUE TITLE
eCozy thermostat valves

### ISSUE THREAD

**Issue by mshli** [dresden-elektronik/deconz-rest-plugin#439]
Does anyone has some experience with eCozy thermostat valves? (ecozy.de) They work with ZHA and i want to use them with my Raspbee and deConz.

**Comment by KingTomaHawk** [comment]
+1
The thermostats are very cheap at the moment and have a very cool design. If more device specific data is required, I could buy one and post some screenshots of the requested values in deconz.

**Comment by mshli** [comment]
I have one for testing and it‘s allready connected. If someone needs some screenshots, just say. I have also send a request to the technical support of ecozy. Maybe they send me the required informations.

**Comment by manup** [comment]
Discussion continues in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/209
