### ISSUE TITLE
Device name Amiko Home Smart Plug (Manufacturer Feibit)

### ISSUE THREAD

**Issue by Satmedia** [dresden-elektronik/deconz-rest-plugin#4391]
## Device

- Product name: Amiko Smart Plug
- Manufacturer: Feibit
- Model identifier: FB56+SKT12KJ1.6
- Device type : Other: Smart Plug

Device is connected as Light in Phoscon APP and it is working as an On/Off Plugin Switch.
BUT it is not working as a router in deCONZ!

## Screenshots

![Bild_2021-02-10_161831](https://user-images.githubusercontent.com/78860688/107529869-9f43a900-6bbb-11eb-8a4c-81d5a2fb36d7.png)

![Bild_2021-02-10_161851](https://user-images.githubusercontent.com/78860688/107529933-abc80180-6bbb-11eb-8a33-87a32fb056bc.png)

![Bild_2021-02-10_161910](https://user-images.githubusercontent.com/78860688/107529987-b6829680-6bbb-11eb-85a8-956c7ec530a3.png)

![Bild_2021-02-10_161942](https://user-images.githubusercontent.com/78860688/107530056-c9956680-6bbb-11eb-89e6-d258e397b611.png)

![Bild_2021-02-10_162007](https://user-images.githubusercontent.com/78860688/107530122-d87c1900-6bbb-11eb-92a1-b1e888287b22.png)

![Bild_2021-02-10_162026](https://user-images.githubusercontent.com/78860688/107530161-e3cf4480-6bbb-11eb-86dc-8b606bd6e138.png)

**Comment by Mimiix** [comment]
Hi,

I told you on discord: Devices pick their own routes. We can't do anything on that. There's some information about it here:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4376

As far as i am concerned, this device seems to be suppoted already. I'd like to have @SwoopX or @smanar confirming this.

**Comment by SwoopX** [comment]
Yep, nothing to be done here.

**Comment by Satmedia** [comment]
Thank you for your fast answers. Yes the Smartplug is working well, only no routing :-(

**Comment by Mimiix** [comment]
@Satmedia As i said, devices pick themselves. As long as they work, don't worry.

**Comment by Satmedia** [comment]
Sorry it was a translation error.The devices are working if they are connected to conbee usb stick directly.Means it are in range for direct connection.They do not make a connection to a router.Mfg Ing. Roland Kroiss Satmedia Austriawww.satmedia.atVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Dennis D <notifications@github.com> Datum: 10.02.21  16:55  (GMT+01:00) An: dresden-elektronik/deconz-rest-plugin <deconz-rest-plugin@noreply.github.com> Cc: Satmedia <info@satmedia.at>, Mention <mention@noreply.github.com> Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Device name Amiko Home Smart Plug (Manufacturer Feibit) (#4391) 
@Satmedia As i said, devices pick themselves. As long as they work, don't worry.
