### ISSUE TITLE
Add AMIKO SMART TEMPERATURE & HUMIDITY SENSOR to DeCONZ

### ISSUE THREAD

**Issue by Satmedia** [dresden-elektronik/deconz-rest-plugin#4398]
## Device

- Product name: AMIKO SMART TEMPERATURE & HUMIDITY SENSOR
- Manufacturer: Feibit,co.ltd
- Model identifier: FB56-THM12HM1.4
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots
![image](https://user-images.githubusercontent.com/78860688/107649345-aaf7a400-6c7d-11eb-8f35-ba0242a603c7.png)

![image](https://user-images.githubusercontent.com/78860688/107649406-b6e36600-6c7d-11eb-9674-07c907cc027c.png)

![image](https://user-images.githubusercontent.com/78860688/107649417-b9de5680-6c7d-11eb-8618-a9e810522366.png)

![image](https://user-images.githubusercontent.com/78860688/107649436-bcd94700-6c7d-11eb-80f9-52b1d65dbe72.png)

![image](https://user-images.githubusercontent.com/78860688/107649452-bfd43780-6c7d-11eb-9514-045dd0e2ef1f.png)

![image](https://user-images.githubusercontent.com/78860688/107757260-9bcc3100-6d25-11eb-85bd-7a437d7671be.png)

![image](https://user-images.githubusercontent.com/78860688/107757271-9f5fb800-6d25-11eb-92cf-c13a0ac09979.png)

https://www.amikohome.com/product/85-smart-home-temperature-humidity-sensor

Hi, I was asking to add amiko home (feibit) plugins/switches/sensors to phoscon app and I got this answer:

YKO-de commented
It looks like your devices are not yet correctly supported in deCONZ either. At least they are not listed. Therefore, please open the issue once at https://github.com/dresden-elektronik/deconz-rest-plugin.

**Comment by Mimiix** [comment]
Missing the Power Configuration cluster screenshot. 

Before proceeding (and cluttering the deCONZ/phoscon repo's) please make sure to fully understand what goes where.

**Comment by Satmedia** [comment]
here please

![image](https://user-images.githubusercontent.com/78860688/107756078-f4023380-6d23-11eb-8584-1b5a2961b7c9.png)

![image](https://user-images.githubusercontent.com/78860688/107756120-0a0ff400-6d24-11eb-849c-b4f8665ca201.png)

**Comment by SwoopX** [comment]
@Satmedia The attributes have not been written for power configuration and basic cluster.

**Comment by Satmedia** [comment]
yes, It do not read the Attributes in deCONZ when press the read button.
