### ISSUE TITLE
Add AMIKO SMART WATER LEAKAGE SENSOR to DeCONZ

### ISSUE THREAD

**Issue by Satmedia** [dresden-elektronik/deconz-rest-plugin#4399]
## Device

Product name: AMIKO SMART WATER LEAKAGE SENSOR
Manufacturer: Feibit,co.ltd
Model identifier: FB56-WTS04HM1.1
Device type : Please remove all unrelated device types.
-Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/78860688/107649919-3bce7f80-6c7e-11eb-915b-ff0054280791.png)

![image](https://user-images.githubusercontent.com/78860688/107649938-3f620680-6c7e-11eb-9559-f8a1c9b4f471.png)

![image](https://user-images.githubusercontent.com/78860688/107649944-41c46080-6c7e-11eb-9e09-b23dfee7b5cb.png)

![image](https://user-images.githubusercontent.com/78860688/107649957-4557e780-6c7e-11eb-90fb-f46db749a9de.png)

![image](https://user-images.githubusercontent.com/78860688/108033091-c672fe00-7033-11eb-8ca0-de9aaf469d66.png)

![image](https://user-images.githubusercontent.com/78860688/108033132-d68add80-7033-11eb-94d0-be356f52d2a3.png)

![image](https://user-images.githubusercontent.com/78860688/108033218-f3bfac00-7033-11eb-9fc1-a0c1d6f46a79.png)

![image](https://user-images.githubusercontent.com/78860688/108033280-0cc85d00-7034-11eb-89b1-0c933d840249.png)

![image](https://user-images.githubusercontent.com/78860688/108033535-6b8dd680-7034-11eb-945e-7f8fbeff4475.png)

![image](https://user-images.githubusercontent.com/78860688/108033638-9841ee00-7034-11eb-8989-5a0aaae0e907.png)

**Comment by SwoopX** [comment]
@Satmedia Screenshots for power configuration and IAS Zone cluster with read attributes are missing.
