### ISSUE TITLE
Add AMIKO SMART DOOR SENSOR to DeCONZ

### ISSUE THREAD

**Issue by Satmedia** [dresden-elektronik/deconz-rest-plugin#4400]
## Device

Product name: AMIKO SMART DOOR SENSOR
Manufacturer: Feibit,co.ltd
Model identifier: FB56-DOS06HM1.3
Device type : Please remove all unrelated device types.
-Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/78860688/107650182-7df7c100-6c7e-11eb-88e0-14830de05fc8.png)

![image](https://user-images.githubusercontent.com/78860688/107650210-851ecf00-6c7e-11eb-94e5-19670e21354c.png)

![image](https://user-images.githubusercontent.com/78860688/107650226-88b25600-6c7e-11eb-9727-5ff468cb054d.png)

![image](https://user-images.githubusercontent.com/78860688/107757058-560f6880-6d25-11eb-9865-b4101761e883.png)

![image](https://user-images.githubusercontent.com/78860688/107757086-5d367680-6d25-11eb-940d-224b51e145f4.png)

**Comment by Mimiix** [comment]
Missing screens of other clusters.

**Comment by Mimiix** [comment]
Can you add the Powerconfiguration cluster?

**Comment by Satmedia** [comment]
![image](https://user-images.githubusercontent.com/78860688/107658887-e21e8300-6c86-11eb-88de-659d3ef7debf.png)

![image](https://user-images.githubusercontent.com/78860688/107658945-f2cef900-6c86-11eb-8608-15b316b1ed33.png)

**Comment by Mimiix** [comment]
Please add them to the above post.
