### ISSUE TITLE
MOES 2 gang switch (tuya)

### ISSUE THREAD

**Issue by erikje14** [dresden-elektronik/deconz-rest-plugin#4409]
## Device

- Product name: MOES 2 gang wireless scene switch 22/44
- Manufacturer: TZ3000_arfwfgoa
- Model identifier: TS0042
- Device type : Please remove all unrelated device types. 

  - Switch

**Comment by erikje14** [comment]
![image](https://user-images.githubusercontent.com/78957729/107757527-f9607d80-6d25-11eb-8f8d-3f6820c55bab.png)

**Comment by erikje14** [comment]
![image](https://user-images.githubusercontent.com/78957729/107757561-04b3a900-6d26-11eb-93bc-2c3d3c7ca10f.png)

**Comment by erikje14** [comment]
![image](https://user-images.githubusercontent.com/78957729/107757632-18f7a600-6d26-11eb-87a3-543026270412.png)

**Comment by erikje14** [comment]
![image](https://user-images.githubusercontent.com/78957729/107757677-257bfe80-6d26-11eb-82e9-f1fcf0546599.png)
![image](https://user-images.githubusercontent.com/78957729/107757705-30cf2a00-6d26-11eb-82d5-f95cb5be2e95.png)

**Comment by Mimiix** [comment]
@Smanar

**Comment by erikje14** [comment]
it's this one fyi:
https://nl.aliexpress.com/item/1005001504737652.html?spm=a2g0s.9042311.0.0.6ff84c4dhC00ci

**Comment by Smanar** [comment]
Added in the list https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4157
