### ISSUE TITLE
How to specify serial port/device for deCONZ (in 2.09.03)?

### ISSUE THREAD

**Issue by mptei** [dresden-elektronik/deconz-rest-plugin#4411]
## Describe the question or issue you are having
I would like to use another serial device than /dev/ttyAMA0 to communicate with the RaspBee.

I know it was possible before (in 2.05.39) with command line option "--dev". But now in version 2.09.03 this is no longer possible.
It still uses only /dev/ttyAMA0.

How can I specify the device?

## Environment
 - Host system: Raspberry Pi 
 - Running method: Raspbian
 - Firmware version: 26390500
 - deCONZ version: 2.09.03
 - Device: RaspBee I
 - Do you use an USB extension cable: no -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? raspberries bluetooth uart

Command Line: /usr/bin/deCONZ -platform minimal --http-port=88 --dev=/dev/ttyAMA2

## Additional context
I rewired the Raspbee module to use another serial port (/dev/ttyAMA2) this worked nicely in 2.05.39.

**Comment by manup** [comment]
Currently the code has a hard coded filter which includes ttyAMA0 and ttyS0 for RaspBee, even with `--dev` specified. I'll extend the filter to include whatever is given via `--dev`.

**Comment by mingan666** [comment]
This is still an issue preventing me from upgrading my deconz.
Could we get a status update from the deconz team?

**Comment by Mimiix** [comment]
Let me check with Manuel :)

**Comment by manup** [comment]
Can you please check if this works now with the latest version?

**Comment by mingan666** [comment]
I'm not sure I'm using the correct deconz version, however it does not seem to be working in the version I tried:

```
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.10.03
....
12:36:05:619 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)

As you can see, I use the marthoc/deconz docker container.

**Comment by mptei** [comment]
I can confirm that it works again with deconz-2.10.03-beta.

That means I've added "--dev=/dev/ttyAMA2" to the command line of deCONZ. A RaspbeeII is connected to /dev/ttyAMA2 and is recognized and used,

Thanks for the fix.
