### ISSUE TITLE
openhab2 Binding

### ISSUE THREAD

**Issue by steveknoefler** [dresden-elektronik/deconz-rest-plugin#443]
Hi
could you PLEASE develop a binding for openhab which using web sockets for eg. Motionsensors updates?

thanks
Steve

**Comment by manup** [comment]
Hi, you may checkout the openhab ZigBee binding, there was some early support for the ConBee/RaspBee(?) but I'm not aware of the current state. The development seems quite active so it might be the best bet for ZigBee in openhab.

https://github.com/openhab/org.openhab.binding.zigbee

**Comment by Kane610** [comment]
Or you could come over to Home assistant, it works great here 👍

**Comment by sheineme** [comment]
I'm using the Hue Binding with deConz. It does most of the stuff i need; what is missing is recalling scenes, for this I use the HTTP binding to call deConz REST API directly

**Comment by steveknoefler** [comment]
yes thats right but the polling every seconds is to slow for motion sensors.

**Comment by steveknoefler** [comment]
I checked home assistant but there is no lux in motion sensors properties :/

**Comment by manup** [comment]
> I checked home assistant but there is no lux in motion sensors properties :/

You may ask the developers of the binding if this feature is planned or already existing somehow.

**Comment by steveknoefler** [comment]
I checked it with my own installation

**Comment by steveknoefler** [comment]
oh I missed it :(

**Comment by Kane610** [comment]
@steveknoefler lux is reported as its own sensor from motion sensors

**Comment by radi-ka** [comment]
Hi,

i just started working on a binding that connects to deCONZ via websockets. Right now it only supports temperature, humidity and open/closed sensors in a rudimentary way (only state updates, no update time, no battery level etc).

If you want to have a look:
[https://github.com/radi-ka/deconz_oh2_binding](https://github.com/radi-ka/deconz_oh2_binding)

**Comment by steveknoefler** [comment]
sorry for late. thats what I see on api for my motionsensor: (deconz api)


{"config":{"alert":"none","battery":100,"ledindication":false,"on":true,"pending":[],"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"ep":2,"etag":"86fa3883746c8c6c6ccf6dd173ffbf63","manufacturername":"Philips","modelid":"SML001","name":"FlurOG_Bewegungsmelder_2","state":{"dark":true,"daylight":false,"lastupdated":"2018-03-25T18:04:51","lightlevel":8417,"lux":7},"swversion":"6.1.0.18912","type":"ZHALightLevel","uniqueid":"00:17:88:01:02:13:10:87-02-0400"}

**Comment by TwE3d** [comment]
@sheineme @steveknoefler Can you give any Explanation how you got the motion sensor working in openhab? When i wanted to add the sensor manually there is only the possibility to add lights, not motion sensors... Im kinda stuck right now...

**Comment by goermezer** [comment]
Same for me. I need to integrate motion and door sensors from Xiaomi, which work quite well in deCONZ. But I couldn`t find a way to bring them to OpenHAB. A binding would be really perfect.

**Comment by manup** [comment]
It might be worth reaching out to the OpenHAB community 

https://community.openhab.org/t/raspbee-binding-compatibility/10020

**Comment by renegade2k** [comment]
@radi-ka are you still working on it?
I'm looking for a way to get the Ikea Tradfri motion sensor to work with openhab somehow, without going through the Tradfri Gateway

**Comment by radi-ka** [comment]
@renegade2k sort of. The current state on github is what i am running at home and what fills my (current) needs.

Assuming tradfri motion sensors emit a websocket event like this: `{"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2018-03-18T20:26:21","presence":true},"t":"event"}`
they should work right now.

If you need help configuring the plugin, please open an issue there.

**Comment by sheineme** [comment]
There is now also an openhab2 binding available in the "official" repository.
https://www.openhab.org/addons/bindings/deconz/
