### ISSUE TITLE
deconz startet nicht mehr

### ISSUE THREAD

**Issue by matze1708** [dresden-elektronik/deconz-rest-plugin#4431]
## Describe the question or issue you are having

  Hallo,

ich hatte deCONZ auf meinem Raspberry 3 zusammen mit ioBroker laufen. Ich habe festgestellt, dass ich keine neuen Sensoren oder andere Dinge einlernen kann. Habe dazu einiges im Netz durch forstet, Stick Conbee2 wurde erkannt. Aber ich hatte diese Meldung, Firmware nicht erkannt oder so ähnlich.
Darauf hin wollte ich aus der PhosconApp ein Update der Software starten, dass hatte nicht geklappt.

Dann hatte ich es über dpkg versucht. seit dem streikt mein System. Über
sudo apt-get isntall deconz
findet er das Paket gar nicht mehr.

Auch über die offizielle Methode auf der Seite von Phoscon geht es nicht mehr, Packet nicht gefunden.

Dann hatte ich es mit verschiedenen Versionen probiert aber ich komme einfach nicht weiter.

Im Moment bringt er mir das hier raus:

`deconz.service - deCONZ: ZigBee gateway -- REST API
Loaded: loaded (/lib/systemd/system/deconz.service; enabled)
Active: failed (Result: start-limit) since Di 2021-02-16 09:43:33 CET; 27s ago
Process: 8493 ExecStart=/usr/bin/deCONZ -platform minimal --http-port=80 (code=exited, status=127)
Main PID: 8493 (code=exited, status=127)

Feb 16 09:43:33 ioBroker-RasPi systemd[1]: Unit deconz.service entered failed state.
Feb 16 09:43:33 ioBroker-RasPi systemd[1]: deconz.service holdoff time over, scheduling restart.
Feb 16 09:43:33 ioBroker-RasPi systemd[1]: Stopping deCONZ: ZigBee gateway -- REST API...
Feb 16 09:43:33 ioBroker-RasPi systemd[1]: Starting deCONZ: ZigBee gateway -- REST API...
Feb 16 09:43:33 ioBroker-RasPi systemd[1]: deconz.service start request repeated too quickly, refusing to start.
Feb 16 09:43:33 ioBroker-RasPi systemd[1]: Failed to start deCONZ: ZigBee gateway -- REST API.
Feb 16 09:43:33 ioBroker-RasPi systemd[1]: Unit deconz.service entered failed state.
`

Was kann ich tun?

Danke.

## Environment

  The deCONZ and firmware versions are found in the Phoscon App: Menu -> Settings -> Gateway,
  as well as in the deCONZ GUI: Menu > Help > About deCONZ.

 - Host system: (Raspberry Pi 3
 - Running method: (Raspbian / iobroker
 
 - Device: (ConBee II 
 - Do you use an USB extension cable: (yes ) -

**Comment by Mimiix** [comment]
Can you please stick to english? Either translate it with google translate or rewrite yourself.
