### ISSUE TITLE
Unable to access to Web App 

### ISSUE THREAD

**Issue by markicos** [dresden-elektronik/deconz-rest-plugin#4434]
I have been trying to get into the Web APP by using the User and Password but it seems that the user or password are not the correct one. i have no problem when getting into Phoscon App when i am request only for the Password, so i consider the problem is the user, any of you have an idea of the user i haver to use?

## Screenshots

![image](https://user-images.githubusercontent.com/44501063/108186701-f989c000-710d-11eb-9208-f24b5152561b.png)

## Environment

 - Host system: (Raspberry Pi 4 and PC  )
 - Running method: (Raspbian and Windows )
 - Firmware version: 26660700
 - deCONZ version: 2.09.03 / 23/12/2020
 - Device: ConBee II 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

## Additional context

The final aim of my development is to avoid get into phocon app to get an apiKey

**Comment by SwoopX** [comment]
The username is `delight`. By default,  it's also the password unless you haven't set your own.

**Comment by markicos** [comment]
Yes it is!! thank you very much
