### ISSUE TITLE
Allow to specify a single IP address to use

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#444]
Since I'm running PiHole and DeCONZ on the same Raspberry Pi 3, I setup a virtual interface (`eth0:0`) with its own IP address.

I configured PiHole to run on the virtual interface, but DeCONZ will always listen on both the IPs preventing PiHole from starting.

Could you add an option to specify which IP to use?

**Comment by manup** [comment]
With upcoming deCONZ version 2.05.09 the listen interface can be specified on command line and config file. The special value of 0.0.0.0 means listen on any interface.

```
--http-listen=192.168.70.4
```

or persistant via config.ini:

```
[http]
port=80
listen=0.0.0.0
...
```

**Comment by FezVrasta** [comment]
Great! Is there any approx ETA already maybe?

**Comment by manup** [comment]
For sure this week, not so sure which day :)

**Comment by manup** [comment]
You may checkout version 2.05.10, the above mentioned command line options are included now.

**Comment by FezVrasta** [comment]
I tried to edit the deconz.service and added the `--http-listen` argument but it seems to get ignored.

May you point me to the right way to configure it please?

**Comment by FezVrasta** [comment]
Oh... weirdly now the http://www.dresden-elektronik.de/pwa app won't discover my DeCONZ instance.

The self-hosted web interface works just fine tho.

**Comment by FezVrasta** [comment]
Neither Home Assistant will be able to discover it, and if I set the IP manually it won't allow me to pair it.

**Comment by FWillems** [comment]
@FezVrasta
Have you been able to run two webserver on one raspberry?
I'm trying to get it working to have
1. pimatic (home automation webserver) on port 80 by wlan0 with IP 192.168.2.100 and
2. the raspbee module with its webserver also on port 80 by wlan0:0 with IP 192.168.2.101

Is that possible? Can you explain your solution?
Thank you.

**Comment by FezVrasta** [comment]
You should be able to use the cli argument mentioned above

**Comment by DurrM** [comment]
So after I installed DeCONZ to my Raspberry I was no longer able to access the admin page of PiHole. I would like to keep PiHole on eth0 interface and "move" deconz to the virtual interface eth0:0. I'm just not sure if that's possible and how to do it. 
Sorry but I'm pretty new. Hope somebody can help me or at least give me some link with further information.

Thank you

**Comment by airbone42** [comment]
Sorry for bringing this old thing up again, but I'm trying to use the --http-listen parameter on a Windows 7 machine with deCONZ 2.05.75.

While the --http-port parameter works perfectly it seems to ignore --http-listen. Even when specified the REST plugin and Phoscon web app are available on all ip-addresses, not just the one defined. As I'm running openhab in parallel and want to use the hue emulation form both systems I have to specify a single ip address, to avoid conflicts.

I wanted to try the config.ini setting as well, but couldn't find any information where to find/place the config.ini on a Windows-system.

**Comment by joggs** [comment]
Cannot find config.ini either. Please specify

**Comment by Mimiix** [comment]
Its in the ZLL.db afaik. However, normally this is something that is done in the router or host OS as deCONZ isn't a network adapter.

**Comment by CapitalT** [comment]
Proper way to change service file s it survives updates is to use `sudo systemctl edit deconz`. First empty ExecStart before setting new one.
See: https://github.com/dresden-elektronik/phoscon-app-beta/issues/26#issuecomment-410553910
