### ISSUE TITLE
Aqara Water Leak Sensor T1 SJCGQ12LM

### ISSUE THREAD

**Issue by theCroh** [dresden-elektronik/deconz-rest-plugin#4440]
## Device

- Product name: Aqara Water Leak Sensor T1 SJCGQ12LM
- Manufacturer: LUMI
- Model identifier: lumi.flood.agl02
- Device type : 
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/4679397/108318486-96a92f00-71c8-11eb-98a0-3918e4f2e61f.png)

![image](https://user-images.githubusercontent.com/4679397/108318512-a0329700-71c8-11eb-9014-0cecc8560196.png)

![image](https://user-images.githubusercontent.com/4679397/108318579-bb050b80-71c8-11eb-9b10-8cd745260d1b.png)

![image](https://user-images.githubusercontent.com/4679397/108318716-f30c4e80-71c8-11eb-95a2-7c4d2377fc14.png)

![image](https://user-images.githubusercontent.com/4679397/108318839-3070dc00-71c9-11eb-8288-d2c9009fe82e.png)

![image](https://user-images.githubusercontent.com/4679397/108318957-57c7a900-71c9-11eb-8294-bea5ee1c1b92.png)

![image](https://user-images.githubusercontent.com/4679397/108319020-72018700-71c9-11eb-97f0-81b5f49c21f9.png)

**Comment by Mimiix** [comment]
@SwoopX @Smanar Is this a easy add? I'd like it in for next beta as i suspect a lot of interest.

**Comment by SwoopX** [comment]
@Mimiix The day Manu merges my door/windows sensor PR for the T1, I can easily add this one here as well. I'll reach out to him as I got several other dependencies on top of that.
