### ISSUE TITLE
Double Tab Problem with Aqara Cube

### ISSUE THREAD

**Issue by bruesche** [dresden-elektronik/deconz-rest-plugin#4442]
## Describe the bug
  Hi,

today my Aquara Cube arrived. Connecting to Deconz work without any problems. The I recognized that the double tap action and the rotation action doesn't work. I found here a problem with the pairing and that I should shake and rotate the cube during the pairing. After that the rotation action was working. But the the double tap didn't work.
Can anyone give me a hint to solve "the problem"?

thx for help

## Environment
My Deconz version is 2.10.00 and the cube is shown in deconz with product number MFKZQ01LM.

**Comment by SwoopX** [comment]
Please don't tell me you tapped your finder on it twice... :) You need to "smash" the cube itself twice.

**Comment by bruesche** [comment]
Shame on me. 🤣
