### ISSUE TITLE
Aquara lumi.vibration.aq1 orientation don't change if moving horizontally 

### ISSUE THREAD

**Issue by net1957** [dresden-elektronik/deconz-rest-plugin#4456]
## Describe the question or issue you are having
I have some Aquara lumi.vibration.aq1 sensors. They are working l but I have some questions:

 -temperature is very wrong and not correlated to real one.
 - orientation work but when you turn the sensor horizontally on a table per example, nothing change in the 3 axis values (orientation in the json)

But I would use this to check the position of a dor or a windows and most of them are moving horizontally.
Is this a normal behavior ? Any idea to resolve it ? Any alternative way ?

## Environment
 -  Host system: Raspberry Pi 4
 -  Running method: Raspbian
 -  Firmware version: (26680700)
 -  deCONZ version: (2.09.03)
 -  Device: ConBee II
 -  Do you use an USB extension cable: yes
  - Is there any other USB or serial devices connected to the host system? If so: Rfxcom

## Additional context
on jeedom 4.1.20 the returned json is:
![Capture](https://user-images.githubusercontent.com/17736/108608642-9c6d6300-73c8-11eb-9388-6ed97c0a2ce9.PNG)

**Comment by ebaauw** [comment]
> -temperature is very wrong and not correlated to real one.

Yes.  Best ignore `config.temperature`.  It reports the device temperature, rather crudely, not the ambient temperature.

> orientation work but when you turn the sensor horizontally on a table per example, nothing change in the 3 axis values (orientation in the json)

That's how the sensor works.  Best check the GUI to understand this.  In the _Door Lock_ (!) cluster, there's some _Xiaomi Special_ attributes that the sensor uses.  It reports different types of events (_Event Type_, 0x0055), and depending on this, it reports the _Tilt Angle_ (0x0503), _Vibration Strength_ (0x0505), or _Orientation_ (0x0508).
