### ISSUE TITLE
Smart Tuya Zigbee Socket BR

### ISSUE THREAD

**Issue by fernandodelucca** [dresden-elektronik/deconz-rest-plugin#4457]
## Device
Link: [https://www.zemismart.com/products/brazil-smart-tuya-zigbee-socket-br-plug-wireless-outlet-timing-plug-16a-energy-monitor-alexa-google-home-smart-home-control](https://www.zemismart.com/products/brazil-smart-tuya-zigbee-socket-br-plug-wireless-outlet-timing-plug-16a-energy-monitor-alexa-google-home-smart-home-control)
- Product name: Smart Tuya Zigbee Socket BR
- Manufacturer: _TZ3000_rdtixbnu
- Model identifier: TS0121
- Device type :  
  - Switch
  - Other: Smart Plug

## Screenshots

**Node Info**
![image](https://user-images.githubusercontent.com/5623038/108609356-104d4280-73ac-11eb-8e19-d44d3fd74f38.png)

**Basic Info**
![image](https://user-images.githubusercontent.com/5623038/108609434-99647980-73ac-11eb-87b5-b7bfa9a7cf63.png)

**Groups**
![image](https://user-images.githubusercontent.com/5623038/108609459-c2850a00-73ac-11eb-911b-16ed8e5463a6.png)
![image](https://user-images.githubusercontent.com/5623038/108609474-dcbee800-73ac-11eb-85e9-b04cb1d169bf.png)

**Scenes**
![image](https://user-images.githubusercontent.com/5623038/108609487-f6602f80-73ac-11eb-90d2-8caba415f3de.png)
![image](https://user-images.githubusercontent.com/5623038/108609493-05df7880-73ad-11eb-9d45-f4423405e876.png)
![image](https://user-images.githubusercontent.com/5623038/108609504-14c62b00-73ad-11eb-9b9a-677daad96d70.png)
![image](https://user-images.githubusercontent.com/5623038/108609514-214a8380-73ad-11eb-893e-0b83cf7f794f.png)

**On/Off**
![image](https://user-images.githubusercontent.com/5623038/108609527-36bfad80-73ad-11eb-8c0b-83dd80105c78.png)
![image](https://user-images.githubusercontent.com/5623038/108609539-4dfe9b00-73ad-11eb-9e95-7afa0c3b5af1.png)

**Simple Metring**
![image](https://user-images.githubusercontent.com/5623038/108609615-d5e4a500-73ad-11eb-89c4-ee7dde8cf46e.png)

**Eletrical Measurement**
![image](https://user-images.githubusercontent.com/5623038/108609628-eeed5600-73ad-11eb-9c72-e7f218f3b90f.png)

**OTAU**
![image](https://user-images.githubusercontent.com/5623038/108609641-075d7080-73ae-11eb-8e52-308c8d12c70a.png)

**Time**
![image](https://user-images.githubusercontent.com/5623038/108609658-1c3a0400-73ae-11eb-8b74-2ca0fc28a060.png)

**Comment by SwoopX** [comment]
Already supported.
