### ISSUE TITLE
OSRAM Classic B40 firmware

### ISSUE THREAD

**Issue by roflmao** [dresden-elektronik/deconz-rest-plugin#447]
Hi,

Im having some issues with connectivity with my OSRAM bulbs. (The hub -> bulb is about 4 meters away one story above)
![deconz_docker](https://user-images.githubusercontent.com/599991/36812449-7ec86a9e-1cd1-11e8-8616-c17728b6fdbe.png)

The 2etg_kjokken* bulbs which are my only OSRAM bulbs gets "grey" in Phoscon aka unreachable after some time.

How am i able to upgrade the fw on these with otau?
The current version is:
```
VendorOSRAM
ModelClassic B40 TW - LIGHTIFY
Version V1.03.20
```

**Comment by ebaauw** [comment]
That's pretty old firmware indeed.  Afaik, the only way to update the OSRAM bulbs is through the Lightify gateway.  In theory deCONZ could do the firmware upgrade, but OSRAM haven't published their firmware files.

**Comment by roflmao** [comment]
The bulbs worked great against my Hue hub. Any tips on getting firmware besides the OSRAM hub?

**Comment by jonathanweinberg** [comment]
As a heads up, I’ve been able to update Osram Sylvania BR30 RGBW bulbs via a SmartThings Gen2 hub.
