### ISSUE TITLE
Can't get Touchlink scan to deliver nearby bulb results

### ISSUE THREAD

**Issue by pa1okz** [dresden-elektronik/deconz-rest-plugin#4478]
## Describe the question or issue you are having

I have been playing around for hours now to get the REST API touchlink functionallity to do a scan and then have the results listed. Goal is to identify and finally reset a Philips Hue lightbulb that somehow dissapeared from the Zigbee devices in my network. I do not own a Hue remote nor HUB. Moreover, I cannot open the old WebApp - this leads to a re-login into phoscon, so REST Api seems to be the way to go. The bulb is 5cm away from my Conbee2, which is running in Docker via Home Assistant.

I got access to the API via the Chrome Advanced REST client which works flawless. Of course the Hue bulb has been powered on fresh and is scanned in less than a minute after.

## Screenshots

First the POST scan is performed:
![image](https://user-images.githubusercontent.com/8615280/109155193-946a4600-776f-11eb-9566-8b8865fb89d7.png)

 
Then the GET rcommand gives an empty result:
![image](https://user-images.githubusercontent.com/8615280/109155110-77ce0e00-776f-11eb-913d-ec62c5c46a3a.png)

## Environment

![image](https://user-images.githubusercontent.com/8615280/109154582-c7600a00-776e-11eb-9201-360896dd21ae.png)

![image](https://user-images.githubusercontent.com/8615280/109156016-9e407900-7770-11eb-8e59-e88ceb5d52d6.png)

Host system: (Raspberry Pi 4 - 4Gb, running HASS OS 5.12, running Deconz with a ConbeeII. I use a USB extension cable to optimize Zigbee coverage, no communication glitches ever. Conbee is connected over the USB3 port (running as USB2) and is shared with a DSMR P1 monitor cable - but this doesn't cause any issue.

## deCONZ Logs

![image](https://user-images.githubusercontent.com/8615280/109154816-1d34b200-776f-11eb-9fab-fd6da19a7ea0.png)

## Additional context

I believe that is all, sincerly hope there is a suggestion in the right direction, thank you.

**Comment by Mimiix** [comment]
Touchlink is not yet supported in Conbee II https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3485

**Comment by pa1okz** [comment]
@Mimiix: Ah, I simply missed that little detail. Interesting that the response in the REST API suggests that it -is- working, considering the principle responses. 

Then I believe that I am out of options in resetting these bloody expensive Philips bulbs, other than buying myself a remote. Let's take the positive out of that, luckily enough I can bind it to the ConbeeII.

**Comment by Mimiix** [comment]
@pa1okz I wish i had better news and i do agree with you on that. I've created a feature request.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4498

It's a shame you need those for the Hue devices. However, the remote is nice and cheap and you'll find a use for it!
