### ISSUE TITLE
[Information] A new version of Xiaomi Aqara wireless switch

### ISSUE THREAD

**Issue by oleg77s** [dresden-elektronik/deconz-rest-plugin#448]
[A new version of Xiaomi Aqara wireless switch](https://aliexpress.com/item/Original-Xiaomi-Aqara-Wireless-Switch-Zigbee-System-Remote-Control-Switch-Use-With-Xiaomi-Gateway-Aqara-Air/32826677539.html): clicking, double clicking, long pressing, shaking.
built-in high precision acceleration sensor
new: WXKG12LM, old: WXKG11LM

**Comment by ebaauw** [comment]
Interesting!  On the ouside it looks like my Xiaomi Aqara smart switch, but I don’t think mine supports shaking.  Never tried, actually.  And I couldn’t get any long press, only single, double, treble, and quadruple presses.  Only one message per press/release - no separate press vs release messages.

**Comment by ebaauw** [comment]
Interesting!  On the ouside it looks like my Xiaomi Aqara smart switch, but I don’t think mine supports shaking.  Never tried, actually.  And I couldn’t get any long press, only single, double, treble, and quadruple presses.  Only one message per press/release - no separate press vs release messages.

**Comment by johga1** [comment]
I have three of these. They only report buttonevent 7000 when performing a double press. 

Anything else is not visible in my logs.

I’m running Deconz GW 2.04.99 as a HASS.io 0.64.2 add-on. All in one headless pi3-box.

**Comment by jurriaan** [comment]
I have two of these: https://www.aliexpress.com/item/Xiaomi-Aqara-Smart-Wireless-Switch-Key-Built-In-Gyro-Function-ZigBee-Wifi-Work-With-xiaomi/32847092257.html 

The description says 'Built-in gyro'. This made me think this switch should support that as well?

**Comment by ebaauw** [comment]
Mine has the same type as the one on the aliexpress picture: WXKG11LM.  They could of course have used the wrong picture.
```
  "modelid": "lumi.sensor_switch.aq3",
```
Mine has `lumi.sensor_switch.aq2`.

> They only report buttonevent 7000 when performing a double press.

Afaik, the Xiaomi cube is the only device that previously could issue this buttonevent value.  It correspond to value 0x02 for the _Measured Value_ attribute (0x0055) of the _Multistate Input_ cluster (0x0012).  I'm guessing the new switch exposes this cluster instead of _OnOff_?  Could some-one please post a screenshot of the node in deCONZ, showing the clusters?

My guess is that the switch reports all actions through the _Multistate Input_ cluster, hence you don't see any other buttonevent values.  deCONZ should already update the _Measured Value_ in the GUI.  If some-one could post the values corresponding to the various actions, adding the corresponding buttonevents to deCONZ will be straightforward.  Here's a screenshot of the Cube:

![untitled](https://user-images.githubusercontent.com/22179355/36933226-b0e435d4-1ed5-11e8-9028-40de160667ad.jpeg)

**Comment by jurriaan** [comment]
@ebaauw Mine is also a `lumi.sensor_switch.aq2`, and has no multistate input cluster unfortunately.

**Comment by johga1** [comment]
Hope this helps.

Single:
![image](https://user-images.githubusercontent.com/35565091/36936246-1910e616-1f03-11e8-8f55-9ec62b236544.png)

Double:
![image](https://user-images.githubusercontent.com/35565091/36936248-1e49a0d2-1f03-11e8-8f8d-de943053c76c.png)

Holding (while holding):
![image](https://user-images.githubusercontent.com/35565091/36936250-2797cfd8-1f03-11e8-9beb-42e8b4ecba16.png)

Hold (after release):
![image](https://user-images.githubusercontent.com/35565091/36936254-33137722-1f03-11e8-9e3a-800d05042d0d.png)

Shake:
![image](https://user-images.githubusercontent.com/35565091/36936257-38d70750-1f03-11e8-95c8-ac259f13a49d.png)

**Comment by ebaauw** [comment]
Thanks @johga1, that's just what the doctor ordered.  Created PR #455 which should do the trick.  I hope @manup can still merge it into 2.05.09 later today, or we'll have to wait for 2.05.10.

**Comment by johga1** [comment]
Anyone else having trouble joining these?

I've been able to join my three Xiaomi Wireless Buttons but are now unable to do so. It worked on version 2.04.99 but then the buttons did not work. Now the buttons work on my one device that is joined to the network. 

My other two remotes that I'm trying to join does not show up in Rest.

I am able to join and see them through the deCONZ GUI/App, this does however not add them to Rest API and therefore unusable for me with Home Assistant. 

Anyone else seeing this problem, or is it something with my local config.

**Comment by tuxinger** [comment]
Same here, I cannot use the WXKG12LM as they are not exposed by the api. As I run deconz headless I cannot check if it´s actually joined.

**Comment by johga1** [comment]
It seems like there's been a bug introduced in 2.05.10 when they added support for the AQ3 devices (registering buttonevents which it didnt do earlier). 

I've been able to add my AQ3 devices on a 2.04.99 installation on my computer. I then did a backup and moved my configuration to my headless HASS.io with Deconz. Buttons now work, but I forgot to add my door sensor which also is AQ3. I'm having the same issue adding that one on 2.05.12.

**Comment by ebaauw** [comment]
Haven’t seen an aq3 door sensor before.  What’s the model id for that one?  For all Xiaomi battery-powered devices: you want to be pressing/releasing the reset button (pin hole) like every second during pairing, to make sure it remains awake.  Also, the device should report its model id on pressing/releasing reset.  That, with the mac address and manufacturer code, should be enough for the REST API to recognise the device.

**Comment by bdickhaus** [comment]
I was having the same problem here with a lumi.sensor_switch.aq3. Version 2.05.15. I was able to add it using version 2.04.99, and once added it works properly with 2.05.15.

**Comment by andenmad** [comment]
hi 
i try to add wxkg12lm lumi.sensor_switch.aq3 switch. 

but its not seams to reginize the switch se picthure for details 

 
![image](https://user-images.githubusercontent.com/36310128/38112651-ed5e5b2a-33a2-11e8-88b7-43ee6a9c50e1.png)

![image](https://user-images.githubusercontent.com/36310128/38112729-232e0124-33a3-11e8-846a-63a12fafd8fc.png)


version running 
![image](https://user-images.githubusercontent.com/36310128/38112798-5328e15a-33a3-11e8-9647-051a711055cf.png)


anyone know what im doing wrong

**Comment by manup** [comment]
The Phoscon App won't display the switch yet.
Did you join it while sensor search was active?

*Phoscon App > Menu > Devices > Sensors > Add new sensor > Other*

Then reset the switch, not sure how it is done for this one but the other Xiaomi one button switch had a small button which had to be pressed a few seconds.

The switch should then be visible in the REST API.

**Comment by andenmad** [comment]
yes i discover from the sensor search it dosent find a sensore it just appere with 0x0000 in deconz see picture aborve

**Comment by andenmad** [comment]
i have just check and it dosent appere in REST API. 

i have upgraded to software version 2.05.20 and try to add sonsor again still sam result.

**Comment by andenmad** [comment]
i was thinking it maybe was the first device i got there was a issue with but i just recieved a new one and it is same experience. 

is there other there experience the same ore anyone know why.

**Comment by ebaauw** [comment]
I did receive some new Aqara door sensors earlier this week and during pairing I noticed that the _OnOff_ cluster only becomes visible in the deCONZ GUI when the magnet is moved (i.e. when the sensor sends its first attribute report).  The REST API resource is only created _after_ the _OnOff_ cluster is visible.  Just spamming the reset button is _not_ enough to get the deCONZ REST API to recognise the new sensors.

I suspect the same might be the case for the switch: during pairing you need to press the switch button during pairing (and maybe shake it as well), in addition to pressing the reset button.  I'm expecting delivery of the .aq3 switches this week, to be continued...

**Comment by andenmad** [comment]
the sensor search keep standing like this 
![image](https://user-images.githubusercontent.com/36310128/38580858-640871a4-3d0b-11e8-847d-18500a39c134.png)

and device is pressent in deconz like this. (have pres any key combination i could think of) 

![image](https://user-images.githubusercontent.com/36310128/38581000-c5eed1b0-3d0b-11e8-92ca-83eeed02630a.png)

![image](https://user-images.githubusercontent.com/36310128/38581030-e88fb8b0-3d0b-11e8-9686-c93e87fc3ceb.png)

single click 
![image](https://user-images.githubusercontent.com/36310128/38581079-04883376-3d0c-11e8-9c5e-adc55bea1f68.png)

double click
![image](https://user-images.githubusercontent.com/36310128/38581113-1fa3d43a-3d0c-11e8-8a5a-2f268ffabb98.png)

sharke 
![image](https://user-images.githubusercontent.com/36310128/38581136-31224c3c-3d0c-11e8-8a39-41f5678ccac2.png)

hold 
![image](https://user-images.githubusercontent.com/36310128/38581163-456e334a-3d0c-11e8-8406-000aebc5e88e.png)


release Hold
![image](https://user-images.githubusercontent.com/36310128/38581185-55069c52-3d0c-11e8-94d9-fb57de99c1f3.png)

**Comment by ebaauw** [comment]
Does the switch show as a `/sensors` resource in the REST API? The switch is not yet supported in the Phoscon app, as @manup mentioned earlier.

**Comment by andenmad** [comment]
no it dosent show up in rest Api.

**Comment by ebaauw** [comment]
Found that sensor was not whitelisted when processing _Multistate Input_ cluster.  Could some-one try my latest PR?

**Comment by andenmad** [comment]
how do i implement PR. is it just change files ore do i need to build pakage ?

**Comment by ebaauw** [comment]
You need to build the REST API plugin following instructions in the README.  Or wait for it to be included in the next release.

**Comment by tbergler** [comment]
I have two of "lumi.sensor_switch.aq2" showing up in deCONZ. How can I actually use them to switch any light?

**Comment by Jasonthefirst** [comment]
Is this problem fixed? Because I can't find the switch wxkg11lm in deconz but not on the web and therefore not in home assistant. Could you point me to the instructions to build the REST API?

**Comment by manup** [comment]
Closing this for now, the switches should be supported since 2.05.50.
