### ISSUE TITLE
https://dresden-light.appspot.com/discover reports only one DeCONZ even if two are here.

### ISSUE THREAD

**Issue by androme13** [dresden-elektronik/deconz-rest-plugin#449]
Hi i have two DeCONZ, only one is returned here : https://dresden-light.appspot.com/discover.
I think json string return only the first entry.

But with this URL, both are seen : http://dresden-elektronik.de/pwa/login.html#

**Comment by manup** [comment]
The discover service will return all gateways which have a) discovery enabled and b) can reach out.
The pwa is a bit different since it also searches local gateways (in LAN) which aren't listet in the internet discovery service.

**Comment by androme13** [comment]
i'm running my second deconz in headless mode, may be it's specific ?
Sorry for my lacks in english, i'm french.

**Comment by manup** [comment]
All good :) headless mode shouldn't be a problem, since beside the hidden deCONZ GUI both versions are identical.

You may check in the old WebApp that `Internet Service` is enabled in:
 *Menu > Settings > Show Advanced Settings*:

**Comment by androme13** [comment]
I already checked that, on the second deconz there is not deconz hardware (usb or gpio) yet, only on the first one, may be this is the cause ? but i can reach the web interface and the websocket port.

**Comment by manup** [comment]
Yes that's indeed the cause, the discovery service only lists gateways with a RaspBee/ConBee hardware mac address.

**Comment by androme13** [comment]
Thank you for your help, last question, is the way to achieve a scan like "The pwa is a bit different since it also searches local gateways (in LAN)" documented somewhere ?

**Comment by manup** [comment]
It's not documented, but it works like this:

* detect own ip subnet(s) like 192.168.2.x via WebRTC/ trial n error
* query all hosts 192.168.2.1–254 on this subnet(s)

The query is: `GET http://192.168.2.1/api/config`

It's a bit brute-force but Javascript in browsers is very limited in capabilities to detect devices in LAN.

**Comment by androme13** [comment]
Thanks a lot for your advices.
