### ISSUE TITLE
Xiaomi temperature sensor shows 0 degrees

### ISSUE THREAD

**Issue by Claus1985** [dresden-elektronik/deconz-rest-plugin#4491]
## Describe the bug
I added a new Xiaomi temperature sensor (of which I already use 5 within my network) but it only has 0 degrees Celsius as temperature value. It regularly send updates but always 0 degrees.

## Steps to reproduce the behavior
I tried to delete and add the sensor again for 3 times but that did not help, still shows 0 degrees.

## Expected behavior
Sensor shows real temperature.

## Screenshots
![D763E095-C118-4E7E-982D-2F91AF0E1D9B](https://user-images.githubusercontent.com/69499563/109384240-c1dbfe80-78eb-11eb-9526-cdfe62c71e24.jpeg)

## Environment
Raspberry Pi 2b+
Raspbian
Firmware version: 26680700
deCONZ version: 2.09.03
Device: ConBee II /
Do you use an USB extension cable: yes
Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
You mentioned "but it only has 0 degrees Celsius as temperature value. It regularly send updates but always 0 degrees." Is this in the API?

Can you read the cluster in the Gui? See if that provides the correct temp?

**Comment by SwoopX** [comment]
Try to re-pair the sensor and push the button once a second while it is pairing. I assume it is still the "older" verion WSDCGQ11LM?

**Comment by Claus1985** [comment]
Tried many different things including pressing the button while pairing and repaired like 20 times..
Solution: I´m gonna buy a new sensor.

Thx anyways.

**Comment by Claus1985** [comment]
Tried many different things including pressing the button while pairing and repaired like 20 times..
Solution: I´m gonna buy a new sensor.

Thx anyways.
