### ISSUE TITLE
Add coolsetpoint to Bitron 902010/32 thermostat 

### ISSUE THREAD

**Issue by solvisit** [dresden-elektronik/deconz-rest-plugin#4494]
## Feature request type

Add to REST API config the coolsetpoint for Bitron 902010/32 thermostat and automatically set "Control Sequence of Operation" to "Cooling and Heating 4-pipes" when mode switch to "cool".

## Description

It is possible to add the same coolingsetpoint to Bitron 902010/32? 

It has the ablity to switch mode from "heat" to "cool". The device change to "cool" but it is not possible to set the coolsetpoint.

Besides, for enabling both modes it is necessary to set 0x001B (Control Sequence of Operation) of thermostat cluster to 0x04 (Cooling and Heating 4-pipes) before changing 0x001C (System Mode) to 0x02 (Cool). It is possible to set them to the correct values if the mode is changed to "cool"?

## Considered alternatives

No alternatives found

## Additional context

![Immagine 2021-02-28 140716](https://user-images.githubusercontent.com/31163597/109419619-ad246700-79ce-11eb-8b2a-d8e93db87859.png)
![Immagine 2021-02-28 140904](https://user-images.githubusercontent.com/31163597/109419632-b7466580-79ce-11eb-9ba4-34ad935d0e3e.png)

**Comment by Mimiix** [comment]
@SwoopX I think you did this one?

**Comment by SwoopX** [comment]
No, but regardless. Exposing the cooling setpoint is easy, fiddling the other thing in not so much and I'm a bit hesitant since it's only required once.

Maybe there's some place where we got that one already in...

**Comment by solvisit** [comment]
> Exposing the cooling setpoint is easy

This would be ok for me. I can set the "Control Sequence of Operation" manually at installation time.

**Comment by solvisit** [comment]
Any news about exposing the cooling setpoint? As I said the other thing is not so important. Thank you

**Comment by solvisit** [comment]
@SwoopX Any news? Thx
