### ISSUE TITLE
Adurosmart ERIA Smart Siren

### ISSUE THREAD

**Issue by ikke-zelf** [dresden-elektronik/deconz-rest-plugin#4501]
## Device

- Product name: Adurosmart ERIA Smart Siren.
- Manufacturer: Adurosmart.
- Model identifier: ERIA - SMART SIREN.
- Device type : Please remove all unrelated device types. 
  - Siren

## Screenshots

domoticz info
{
  "etag": "4113fbcd55d170ccaf3dbf95296d6dab",
  "hascolor": false,
  "lastannounced": null,
  "lastseen": "2021-03-01T20:45Z",
  "manufacturername": "AduroSmart Eria",
  "modelid": "Smart Siren",
  "name": "Alarm Sirene",
  "state": {
    "alert": "none",
    "reachable": true
  },
  "swversion": "01000003",
  "type": "Warning device",
  "uniqueid": "00:15:8d:00:05:4f:19:6c-01",
  "id": "10",
  "deviceclass": "lights"
}

Additional info:
It seems you can add/include it by searching for lights. it's show as a siren in lights section, but it can not be activated.
Reading from the product page it should be possible to enable/disable and choose a sound.

Hope you can help me to fully include this in the deconz conbee2.
with regards

**Comment by SwoopX** [comment]
This is not how it works. Please read the template thoroughly and provide all requested information.
