### ISSUE TITLE
could not sync with bootloader

### ISSUE THREAD

**Issue by SuperSchelli** [dresden-elektronik/deconz-rest-plugin#4503]
## Describe the question or issue you are having
-Somehow i had a power outage, after that nothing responded on the network
-the Gateway shows Firmware : not connected
-i used this guide an tried to update the firmware : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian
-i also checked if the serial port in raspi config is set correctly
-i additionally ran the update with -x 3 option, see screenshot

## Screenshots
![raspbee - firmware](https://user-images.githubusercontent.com/45967993/109572558-c07a2400-7aed-11eb-8d90-c26442125201.png)
![pi command line](https://user-images.githubusercontent.com/45967993/109572857-41392000-7aee-11eb-9ea4-ba0c1318ae30.png)
![pi command line x3](https://user-images.githubusercontent.com/45967993/109573082-a3922080-7aee-11eb-9aef-a68f4913df77.png)

## Environment
 - Host system:  Raspberry Pi 4B+ -- gpio -v shows v2.52
 - Running method: Raspbian 
 - Firmware version: (not connected)
 - deCONZ version: (2.10.01)
 - Device:  RaspBee I 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
  well i guess the screenshots show the logs in question

## Additional context
- i cant switch anything at all, nothing is responding etc, so the lights are in the last condition they were in before the crash
- i have a recent backup made from the phoscon app of the config and everything

**Comment by SuperSchelli** [comment]
![pi command line x3](https://user-images.githubusercontent.com/45967993/109573296-16030080-7aef-11eb-9f66-333a99acfc4a.png)
![pi command line](https://user-images.githubusercontent.com/45967993/109573302-1a2f1e00-7aef-11eb-93fd-d43a7a362880.png)
![raspbee - firmware](https://user-images.githubusercontent.com/45967993/109573307-1c917800-7aef-11eb-8ae1-c99c5d9a3ef0.png)

**Comment by SuperSchelli** [comment]
ok, here are the screens, dont know why they failed in my first post

**Comment by Smanar** [comment]
Just by curisity, have you tried this method ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2904

**Comment by SuperSchelli** [comment]
nope havent tried that, will try older gcfflasher versions, thx for the tip, thought they were downward compatible.

**Comment by SuperSchelli** [comment]
hmm, i grabbed the 2.11 gcfflasher deb, the newest one and tried it and bam it flashed without problems, although it also just said GCFFlasher V3_17, same as yesterday, everything in the log looks exactly the same, except this time it did not fail to sync ... well, i will not complain although i do not understand it.
Thx for the help, problem solved
