### ISSUE TITLE
Xiaomi Multisensor no air pressure and humidity

### ISSUE THREAD

**Issue by Schattenruf** [dresden-elektronik/deconz-rest-plugin#4505]
## Describe the question or issue you are having
 After the last deconz update my Xiaomi Multisensor or Temperature Sensor does not show any air pressure or humidity

## Screenshots

This is how it should look like:
![image](https://user-images.githubusercontent.com/12720317/109625097-3490e800-7b3f-11eb-946f-26587af359e6.png)

And how it actually looks:
![image](https://user-images.githubusercontent.com/12720317/109625079-2fcc3400-7b3f-11eb-98ed-ec72626de330.png)

Is there anything I can do to enable those values again?

## Environment

 - Host system: Beelink BT3
 - Running method: Debian with iobroker
 - Firmware version: (264A0700)
 - deCONZ version: (2.05.74)
 - Device: ConBee II 
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so: Which? No

**Comment by fribse** [comment]
I see problems with the xiaomi sensor as well, as described [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4517)

**Comment by Schattenruf** [comment]
@fribse but here is the humidity and air pressure visible... For me it is not.

**Comment by Mimiix** [comment]
Would be useful if we could sniff the traffic here.

**Comment by Schattenruf** [comment]
@Mimiix Is there a manual or anything like this? I could try to get those logs.

**Comment by Mimiix** [comment]
Sorry I missed this one. The traffic sniffing is something you need a cc device for or a ConBee /raspbee 1

**Comment by Schattenruf** [comment]
As I mentioned I have the conbee Stick. I also have a CC Stick that got replaced by the conbee one

**Comment by Smanar** [comment]
And if you try to set phoscon in permit join, and read again basic attribute on deconz ?
Pressing shortly the button every 2/3s after inclusion (just after the 5 + 3 blink) to prevent the device go to sleep ?

**Comment by Schattenruf** [comment]
@Smanar I reseted the device and rejoined it to my Network but no change. No Air pressure or humidity. Just temperature. I did not needed to Push the pair Button twice because He found it immediatly. 

The other values just do not get requested after the latest deconz Upgrade.

I do Not know what to do now. I think it is a bug. But I cannot find any logs or how to sniff the Traffic between these two.

**Comment by Schattenruf** [comment]
Hey again,
seems it works now again:
![image](https://user-images.githubusercontent.com/12720317/113711018-b9de5e00-96e4-11eb-970f-363610eaf12b.png)

I do not know what has happened here or what caused the issue but I will close this post, if it stays like that for the next 3 days.
