### ISSUE TITLE
MLI ZBT-DIMLight-A4700001 bulbs need multiple seconds to turn on

### ISSUE THREAD

**Issue by krombipils** [dresden-elektronik/deconz-rest-plugin#4506]
## Describe the question or issue you are having

My issue/question is probably not directly related to Deconz, but I'm now no longer using the Hue Bridge/zigbee2mqtt and hopefully someone can help:

I'm using some MLI ZBT-DIMLight-A4700001 bulbs still connected to a 'physically' light switch. When turning the bulbs on, most of the time a device announce is immediately received.

But when I turn the power on for the first time on the morning, it takes couple of seconds for the bulbs to turn on and of course the device announce also takes couple of seconds.

This behaviour is quite annoying. Anyone else noticed this? I wonder what happens in the time between turning the power on and the lightbulb going on?! There is no output in the deconz debug log.
I never noticed this behaviour on Philips Hue bulbs...

## Environment

 - Host system: Intel Nuc
 - Running method:  Marthoc Docker container
 - Firmware version: 0x26340500
 - deCONZ version: 2.09.03
 - Device: ConBee
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
I got some "ZBT-ColorTemperature" from MLI, also connected to a physical switch. When I turn it on, the lights do so instantly as well...
