### ISSUE TITLE
Tuya / Moes TRV unavailable after reboot

### ISSUE THREAD

**Issue by swieprecht** [dresden-elektronik/deconz-rest-plugin#4508]
## Describe the question or issue you are having
 Hi everyone, 

So, I've purchased 7 TRV's after I thought getting my test one working fine.

Initially I had issues with them staying on heat, even when they were well over the Target Temperature, then I did a reboot on Deconz and they all went from having basic options to having loads (including the presets, auto mode, valve position etc...)

Ideal I thought... but then they all went unavailable. I tried everything but the only way I could get them to reconnect was to repair each one in Phoscon app.

All working great....

Then I needed to do another reboot on Deconz to get the thermostat working... All now gone to unavailable again.

Is this a known flaw, and is there a way to fix it so I don't have to repair every time I need to reboot Deconz? I don't often reboot Deconz, but it will be really annoying if I have to do this every single time.

## Environment

 - Host system: Raspberry Pi 3b+
 - Running method: Raspian
 - Firmware version: 26660700
 - deCONZ version: 2.07.01 / 23/12/2020
 - Device: ConBee II
 - Do you use an USB extension cable: Yes - 3m
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Smanar** [comment]
Your deconz version is realy old, I think this is Tuya improvement in all versions ATM.
The problem can come from an incomplete inclusion in deconz (visible on the GUI, on the node title)
From an incomplete inclusion in API (visible in logs)
From a right issue on the OS (Have you other devices that work correclty ?)
