### ISSUE TITLE
Tuya siren(TS0216) doesn't expose options to Home Assistant

### ISSUE THREAD

**Issue by aidbish** [dresden-elektronik/deconz-rest-plugin#4510]
## Describe the bug

 i have paired a tuya siren but the options to set volume and siren time and other options are not exposed to Home Assistant, in phoscon app it only has the option to turn on/off the siren

Home Assistant only shows the siren to be and on/off device (works) there are no other options

## Steps to reproduce the behavior

i have reset and repaired but again the options are not available. in the deconz app i can see the clusters and the options and able to set/change but these are not available to home assistant

## Expected behavior

Options to be controllable in Home automation software

## Screenshots

  If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/38182386/109738612-daae2200-7c13-11eb-95c1-6d4b4db632aa.png)
![image](https://user-images.githubusercontent.com/38182386/109738931-7c357380-7c14-11eb-9eca-f1ea19831759.png)
![image](https://user-images.githubusercontent.com/38182386/109738949-86577200-7c14-11eb-9fc1-79d9b67f3497.png)

## Environment

Host system: PC
Running method: Marthoc Docker container
Firmware version: 26680700
deCONZ version: 2.09.01
Device: ConBee II
Do you use an USB extension cable: yes
Is there any other USB or serial devices connected to the host system? If so: Which? No

## Additional context
https://github.com/Koenkk/zigbee2mqtt/issues/4655

https://www.aliexpress.com/item/4001309486955.html

**Comment by aidbish** [comment]
I have just noticed that in Home assistant if i select to turn on the device the siren will work but the toggle in HA return to off position
To turn the alarm off, i have to select on then off in the toggle

**Comment by Mimiix** [comment]
I think this is intended behavior. Options should be set via the rest api or deconz gui.

**Comment by Smanar** [comment]
This device is not yet in deconz, still in PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4379

**Comment by aidbish** [comment]
Hi Smanar
This is a different model to that pr
manufacturer name : _TYZB01_a5tf0bpl
modelTS0216

**Comment by Smanar** [comment]
Ha yes, right, this device have the tuya cluster 0xEF01 but it seem using only the IAS cluster.

**Comment by aidbish** [comment]
Hi smanar

is there anything more you need from me regarding your last comment

**Comment by Mimiix** [comment]
@Smanar :)?

**Comment by Smanar** [comment]
I think this device work like all siren
- You have predefined mode
- You can change the duration using state.ontime

If it don't work, can you show your device JSON ?

You have the predefined mode here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4432#issuecomment-782841021
