### ISSUE TITLE
Can anyone explain how I can find out from which device these entries are coming:

### ISSUE THREAD

**Issue by oywino** [dresden-elektronik/deconz-rest-plugin#4512]
## Describe the question or issue you are having
The screenshot below shows a series of never-ending messages captured from the console.
As you can see, the messages holds no information that I can go by in order to track down the cause of this issue. So ,I need help on how to proceed form here.

## Screenshots

![image](https://user-images.githubusercontent.com/18447119/109849146-52e70880-7c51-11eb-992b-101462b3c2f8.png)

## Environment

 - Host system: (Raspberry Pi / PC / **NAS**)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / **Marthoc Docker container** / Windows / Virtual Machine)
 - Firmware version: (26660700)
 - deCONZ version: (2.10.00 / 12/23/2020)
 - Device: (ConBee I / **ConBee II** / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (**yes** / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## deCONZ Logs

See screenshot above.

**Comment by oywino** [comment]
Bump! Anyone?

**Comment by Smanar** [comment]
Try enabling more flag, like APS
You will be able to see previous logs, with more information like the MAC address

It s a device with the commissioning cluster.

**Comment by oywino** [comment]
Hi, and thank you for stepping in.
However,I have no idea how to enable a flag.  Could you please explain?

**Comment by Smanar** [comment]
Where are you looking logs ?
in console ? > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags
in deconz/help/gui ? > flags are the checkbox.

**Comment by oywino** [comment]
The messages were captured from the console.
I'm not sure if they also appear in the log, but I'll check that. Thank you for guiding me 👍

**Comment by Mimiix** [comment]
@oywino If you open another issue later, please add more info in the description on creation.

**Comment by oywino** [comment]
> @oywino If you open another issue later, please add more info in the description on creation.

Sorry, of course - I have updated. I was hoping that whoever wrote this software would know the meaning of these messages.
