### ISSUE TITLE
zshark and FW update not working for RaspBee II

### ISSUE THREAD

**Issue by romanho** [dresden-elektronik/deconz-rest-plugin#4515]
I've a RasPi 4B with a RaspBee II module and wanted to use zshark to debug a problem with a switch.

## Describe the bug

I've installed zshark-1.00.02.deb and when starting it, I connect it to the only device "RaspBee". Briefly another dialog is visible, then it says "No or wrong firmware found". When I use the "install firmware" button I see some funny chars on stdout, as like the serial protocol written there. After a short while, it says "bootloader not responding" and all starts over again.

I've noticed that GCFFlasher_sniffer coming with zshark.deb is much older (V2_11 from 2017/12/20) than GCFFlasher_internal from deconz package (V3_17, no date). With strace I also can see that they seem to speak different serial protocols.

But I didn't dare trying GCFFlasher_internal with /usr/share/zshark/fw/sniffer_v1_0.bin, as the other flasher tool has an explicit "sniffer" in its name... Is it safe using GCFFlasher_internal for that purpose, too? Would that maybe already fix the problem?

## Steps to reproduce the behavior

1. Start zshark
2. Click "Connect"
3. Click "Install Firmware"
4. [...wait...] then error msg in the terminal
5. Click "Back"
6. goto 2

## Expected behavior

Flashing and zshark working

## Screenshots

![zshark_fw_update](https://user-images.githubusercontent.com/59418986/109880127-d36c3000-7c76-11eb-9c00-6c9ef14cde81.png)
![zshark_output](https://user-images.githubusercontent.com/59418986/109880534-52f9ff00-7c77-11eb-919b-e98c250311f9.png)

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: (26690700)
 - deCONZ version: (2.10.01)
 - Device: RaspBee II
 - Is there any other USB or serial devices connected to the host system? no
 -

**Comment by SwoopX** [comment]
Raspbee II and Conbee II are not supported with zshark.
