### ISSUE TITLE
Some IKEA Tradfri Lights are unreachable and disabled

### ISSUE THREAD

**Issue by rene-mueller** [dresden-elektronik/deconz-rest-plugin#4519]
## Describe the question or issue you are having

Currently, I have set up my system for the entire household. So I have about 20 light balls. Coincidentally after a few days some of them are not accessible, so they can not be controlled via Homebridge and Siri.

Is there an easier way than adding each bulb again?

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: (26690700)
 - deCONZ version: (2.09.03)
 - Device: RaspBee II

**Comment by Mimiix** [comment]
Can you provide some logs?

**Comment by msex67** [comment]
I have the same issue, after installing the latest homeassistant updates. 

![image](https://user-images.githubusercontent.com/70475962/110200633-36b8b680-7e5f-11eb-887e-89e820178f78.png)
