### ISSUE TITLE
Lonsonho Tuya Zigbee 3 way switch (TS0043 / _TZ3000_a7ouggvs)

### ISSUE THREAD

**Issue by Big4SMK** [dresden-elektronik/deconz-rest-plugin#4520]
## Device

- Product name: Lonsonho Tuya Zigbee 3 way switch
- Manufacturer:_TZ3000_a7ouggvs
- Model identifier: TS0043
- Device type : Switch

Note that I already added the manufacturer in my [tuya_testing](https://github.com/Big4SMK/deconz-rest-plugin/tree/tuya_testing) to get to the below screenshots. However, I'm a bit at a loss on how to continue. From other threads I understood that I could use the API to see button presses, but per the below json the state returns null for the buttonevent.
Any help to move things forward would be helpful.

## Screenshots
![image](https://user-images.githubusercontent.com/13876030/110036676-a767b200-7d3d-11eb-8df0-c99c2ad76bbb.png)
![image](https://user-images.githubusercontent.com/13876030/110036609-9323b500-7d3d-11eb-8642-f15551e78217.png)
![image](https://user-images.githubusercontent.com/13876030/110036757-ca926180-7d3d-11eb-927f-cc1996d5be16.png)

```json
{
    "config":{
        "battery": 100,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "4f50140a18929c74b4d9d4788763a07e",
    "lastseen": "2021-03-04T21:44Z",
    "manufacturername": "_TZ3000_a7ouggvs",
    "mode": 1,
    "modelid": "TS0043",
    "name": "Switch",
    "state":{
        "buttonevent": null,
        "lastupdated": "none"
    },
    "type": "ZHASwitch",
    "uniqueid": "5c:02:72:ff:fe:d7:66:c3-01-0006"
}

**Comment by Smanar** [comment]
Your code seem good, but remember you need to edit the json file too.
This file is in /usr/share/deCONZ/device or something like that.

**Comment by Big4SMK** [comment]
Oh thanks! Your comment made me realize that the json is not being used to create the shared object but needed to be copied as a separate file. It seems to be working fine now.
