### ISSUE TITLE
4 button remote Nedis ZBRC10WT R7054

### ISSUE THREAD

**Issue by tunam007** [dresden-elektronik/deconz-rest-plugin#4524]
Hello,

I bought this Nedis remote control but I can't use it with deconz   2.10.2 . The other Zigbee Nedis products work well and are recognised via Jeedom if ever. it the same of that https://www.reichelt.com/de/en/smart-remote-control-zigbee-woox-r7054-p291192.html?r=1

Device

    Product name: Nedis ZBRC10WT
    Manufacturer: TZ3000_fsiepnrh
    Model identifier: TS0215A
    Device type : Remote
    

Screenshots

![image](https://user-images.githubusercontent.com/42495498/110175078-751f8880-7e01-11eb-9544-3f3269b87201.png)

Node Info
![image](https://user-images.githubusercontent.com/42495498/110175184-a6985400-7e01-11eb-951f-1f71e3e5ff88.png)

basic
![image](https://user-images.githubusercontent.com/42495498/110175136-8e283980-7e01-11eb-8fdf-f913eff91ec1.png)

Power Config
![image](https://user-images.githubusercontent.com/42495498/110175312-d6dff280-7e01-11eb-8cf8-f38aba7838ee.png)

IAS Zone
![image](https://user-images.githubusercontent.com/42495498/110175421-0262dd00-7e02-11eb-8cf2-65db9245780d.png)

![image](https://user-images.githubusercontent.com/42495498/110175454-1575ad00-7e02-11eb-8ac1-5d9b7bae3f84.png)

Thank you 

Greg

**Comment by Mimiix** [comment]
Can you make sure the basic cluster is read?

**Comment by tunam007** [comment]
Hello,
Could you tell me how to do this? 

Thank you 

Greg

**Comment by Mimiix** [comment]
Click "read" on the right top :)

**Comment by tunam007** [comment]
Hello,

Sorry I had a lot of work, I'm not used to the software. I use deconz with Jeedom. Here is what I have read:

![image](https://user-images.githubusercontent.com/42495498/111557780-9da66b80-878d-11eb-85ba-520ad6f613d8.png)

Tell me if I can help you more? I am in Belgium, I can even send it to you and you can send it back to me when you are done.

Thanks 

Greg

**Comment by tunam007** [comment]
Hello,

I was able to read one or two more values

![image](https://user-images.githubusercontent.com/42495498/113145240-7db38500-922e-11eb-929b-6bbf9795372d.png)

![image](https://user-images.githubusercontent.com/42495498/113145271-899f4700-922e-11eb-9045-50190dfe169d.png)

**Comment by tunam007** [comment]
I was also able to extract this from the Zigbee plugin on Jeedom:

{
    "ieee": "bc:33:ac:ff:fe:5d:2a:bc",
    "nwk": 24323,
    "status": 2,
    "lqi": "None",
    "rssi": "None",
    "last_seen": "None",
    "node_descriptor": "02:40:80:02:10:52:52:00:00:2c:52:00:00",
    "endpoints": [
        {
            "id": 1,
            "status": 1,
            "device_type": 1025,
            "profile_id": 260,
            "manufacturer": "_TZ3000_fsiepnrh",
            "model": "TS0215A",
            "output_clusters": [
                {
                    "id": 25,
                    "name": "Ota",
                    "attributes": []
                },
                {
                    "id": 10,
                    "name": "Time",
                    "attributes": []
                }
            ],
            "input_clusters": [
                {
                    "id": 0,
                    "name": "Basic",
                    "attributes": [
                        {
                            "id": 0,
                            "name": "zcl_version",
                            "value": 3
                        },
                        {
                            "id": 1,
                            "name": "app_version",
                            "value": 67
                        },
                        {
                            "id": 2,
                            "name": "stack_version",
                            "value": 0
                        },
                        {
                            "id": 3,
                            "name": "hw_version",
                            "value": 1
                        },
                        {
                            "id": 4,
                            "name": "manufacturer",
                            "value": "_TZ3000_fsiepnrh"
                        },
                        {
                            "id": 5,
                            "name": "model",
                            "value": "TS0215A"
                        },
                        {
                            "id": 6,
                            "name": "date_code",
                            "value": ""
                        },
                        {
                            "id": 7,
                            "name": "power_source",
                            "value": 3
                        }
                    ]
                },
                {
                    "id": 1,
                    "name": "Power Configuration",
                    "attributes": []
                },
                {
                    "id": 1280,
                    "name": "IAS Zone",
                    "attributes": []
                },
                {
                    "id": 1281,
                    "name": "IAS Ancillary Control Equipment",
                    "attributes": []
                }
            ]
        }
    ],
    "signature": {
        "manufacturer": "_TZ3000_fsiepnrh",
        "model": "TS0215A",
        "node_desc": {
            "byte1": 2,
            "byte2": 64,
            "mac_capability_flags": 128,
            "manufacturer_code": 4098,
            "maximum_buffer_size": 82,
            "maximum_incoming_transfer_size": 82,
            "server_mask": 11264,
            "maximum_outgoing_transfer_size": 82,
            "descriptor_capability_field": 0
        },
        "endpoints": {
            "1": {
                "profile_id": 260,
                "device_type": 1025,
                "input_clusters": [
                    0,
                    1,
                    1280,
                    1281
                ],
                "output_clusters": [
                    25,
                    10
                ]
            }
        }
    },
    "class": "zigpy.device"
}

**Comment by tunam007** [comment]
:(

**Comment by jhubig** [comment]
@tunam007 Could you make it finally work? I'm looking since long time for a "keyfob" working with deconz. This (https://zigbee.blakadder.com/Immax_07046L.html) would be my preferred one and it should be compatible but I cannot find it anywhere to buy it. Also happy to hear about your alternatives.

**Comment by jordanderoubaix** [comment]
Hello,
I would be very happy to know if it can be paired with deconz also :).
I try using the DDF from R7052 without luck
