### ISSUE TITLE
Raspbee 2 firmware not connected

### ISSUE THREAD

**Issue by murphwiz** [dresden-elektronik/deconz-rest-plugin#4525]
## Describe the bug
 unable to connect or update firmware.

## Steps to reproduce the behavior
 update using SSH fails

## Environment

 - Host system: Raspberry Pi 4b
 - Running method: Homebridge raspbian image add on
 - Firmware version: (not connected)
 - deCONZ version: (2.09.03)
 - Device: (RaspBee II)
 - Do you use an USB extension cable: (/no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?
No, running successfully: homebridge and pi hole.

## deCONZ Logs
 https://pastebin.com/FRR6JJxi

**Comment by Mimiix** [comment]
Hi!

Can we close this as i think we fixed it trough discord already. Can you let me know?

**Comment by murphwiz** [comment]
Yes, please close, thank you for your help!
