### ISSUE TITLE
Deleted devices still exist insivibly and are provided to Home Assistant deCONZ integration

### ISSUE THREAD

**Issue by bcutter** [dresden-elektronik/deconz-rest-plugin#4527]
## Describe the bug
I deleted formerly used devices from Phoscon/deCONZ. They do neither appear on the sensor/lights/switches lists (Phoscon) nor on the node list (deCONZ) anymore.

BUT: deCONZ (running in a Supervisor/HASS addon) still exports those devices to the Home Assistant deCONZ integration (https://www.home-assistant.io/integrations/deconz). Using the `deconz.remove_orphaned_entries` service does not remove those devices. Reloading the integration always (re)imports those deleted devices. Rrestarting deCONZ and Home Assistant does not change anything.

This happened for two "lumi.plug.mmeu01" devices so far (only ones being removed from the ZigBee network).

## Expected behavior
Deleted devices should not be provided anymore.

## Screenshots

![grafik](https://user-images.githubusercontent.com/13799156/110212702-055edb80-7e9d-11eb-8fc0-1267838a6cf1.png)

## Environment

![grafik](https://user-images.githubusercontent.com/13799156/110212713-17d91500-7e9d-11eb-8fe0-52321205966d.png)

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: see screenshot
 - deCONZ version: see screenshot
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which?: no

## Additional context

Questions:
1) ~~How to check the internal devices database of deCONZ?~~
--> answered by myself using https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#get-all-sensors
2) ~~According to 1: how to completely delete/remove devices from deCONZ?~~
--> tried to using https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#delete-sensor

Note: I´m not sure where this issue belongs to (deCONZ side? deCONZ integration for Home Assistant side?). Seeing deleted devices still being exported to the deCONZ HA integration I assume the bug is on the deCONZ side.

**Comment by bcutter** [comment]
Update:
Using https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#get-all-sensors I discovered 8 sensor devices matching the one I had deleted before (`"modelid": "lumi.plug.mmeu01"`).

1) I deleted them using https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#delete-sensor.
2) I ran `deconz.remove_orphaned_entries` service in Home Assistant.
3) I reloaded the deCONZ integration in Home Assistant.

So I "worked around" that issue, fine _for the moment_. Remaining question:

**Why do sensors still exist after they´ve been already deleted?**

Is the deletion / cleanup not done properly?

I keep this issue open until those questions have been answered - because I fear ending up in the same situation soon.

**Comment by Smanar** [comment]
>I deleted formerly used devices from Phoscon/deCONZ. They do neither appear on the sensor/lights/switches lists (Phoscon) nor on the node list (deCONZ) anymore.

Hello, you have used phoscon or deconz ?

**Comment by bcutter** [comment]
> 
> 
> > I deleted formerly used devices from Phoscon/deCONZ. They do neither appear on the sensor/lights/switches lists (Phoscon) nor on the node list (deCONZ) anymore.
> 
> Hello, you have used phoscon or deconz ?

Both. Usually Phoscon, sometimes deCONZ. When deleting it immediately in the other application (Phoscon/deCONZ) devices were removed from the GUI.

I tested it after having deleted all sensors using the API as mentioned few minutes before:
I added/paired one of those devices again and deleted it (using Phoscon). This time they also were removed from the internal deCONZ database (or whatever the storage is called) and were therefore not exported to deCONZ integration for HA.

Maybe this happens when deleting disconnected devices? Or it´s another cause, I have no idea.

**Comment by Smanar** [comment]
From my memory this can happen if you delete the device in deconz instead of phoscon, but I can't find again the explanation.

**Comment by mic4ael** [comment]
Any update on this since I am also curious why deletion of entities doesn't propagate to HA.

**Comment by Rob65** [comment]
This still is an issue on HA 2023.09 with Deconz 6.20.0 addon.
This should be reopened and fixed
