### ISSUE TITLE
LK FUGA® Wiser wireless battery 4 button switch

### ISSUE THREAD

**Issue by jonmoerk** [dresden-elektronik/deconz-rest-plugin#4534]
LK FUGA® Wiser wireless battery 4 button switch
https://www.lk.dk/produkter?iid=13901

## Device

- Product name: 
LK FUGA® Wiser wireless battery 4 button switch
- Manufacturer: Schneider Electric
- Model identifier: FLS/AIRLINK/4
- Device type : 
  - Switch

## Screenshots
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/80209954/110281883-cf754080-7fdd-11eb-9fa2-0c56aa134716.png">

<img width="386" alt="image" src="https://user-images.githubusercontent.com/80209954/110244876-183ae400-7f61-11eb-8185-af006c9a29c9.png">

**Comment by Mimiix** [comment]
Missing clusters screenshots

**Comment by thiesens** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2451715/110289023-246a8400-7fe9-11eb-9948-6a0f57680e6d.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/2451715/110289072-31877300-7fe9-11eb-9279-92130f7b3d8d.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/2451715/110289095-39dfae00-7fe9-11eb-8cac-3a91a719d365.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/2451715/110289116-406e2580-7fe9-11eb-8fcf-595e4291abce.png">

**Comment by tomillr** [comment]
This products seems to be related to the Zigbee-based Wiser-range bei Merten. There's an older request for support that has yet to be addressed:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1615

**Comment by mwaldhauer** [comment]
What is eta on adding device to Phoscon ?
Exited to add new gadgets 😁

**Comment by scaarup** [comment]
> This products seems to be related to the Zigbee-based Wiser-range bei Merten. There's an older request for support that has yet to be addressed:
> 
> #1615

That request is alsost 2 years old. Wiser (Schneider) recently released a series of new devices in Denmark and we are a lot of users eager to get this working.
What's the eta and what can we do, as users, to help?

**Comment by akafester** [comment]
It seems that Zigbee2mqtt has some support for the Merten line. But it overall seems to be a pretty unsupported product line. 
Looks forward to see some support for this!

**Comment by palletodap** [comment]
This would be really great to get supported in Deconz, especially after the Danish marked has a huge focus on these new FUGA Wiser products right now😄 These are going to be the new standard in new smart-homes build in Denmark, since that's the only brand used for traditional switches here😅

**Comment by Cubixzno1** [comment]
Any news on this topic? Would be greatly appreciated!

**Comment by teslafreak1** [comment]
Any news? Really waiting for this to be integrated

**Comment by scaarup** [comment]
This is a valid request and should not auto expire!

**Comment by Noizexx** [comment]
ZHA has this somewhat working if you need pointers.

**Comment by Noizexx** [comment]
> > ZHA has this somewhat working if you need pointers.
> 
> No it is not working well in ZHA.

Working somewhat. With some fiddling, it's fully functional.

**Comment by scaarup** [comment]
Some fiddling? I couldn't detect any key-presses when listening for events. But yes, you can turn on/off, dimm up/down a light - that works. But I would like to do other automations based on pressing a key on the wiser.

**Comment by Cubixzno1** [comment]
Is it possible to use the battery switch only or do I still need the other parts?

**Comment by JonasKristiansen** [comment]
Also very eager to get the Wiser line working with Deconz.

Just purchased a motion sensor, but seems to have no luck getting it connected to Deconz.

**Comment by mwaldhauer** [comment]
@SwoopX I see you have helped with the LK Wiser Temp and Water leak sensors. Can you help here as well ?

**Comment by EjvindHald** [comment]
@SwoopX - if you have time to assist with this one, I would highly appreciate it as well. Thanks in advance.

**Comment by teslafreak1** [comment]
Please keep this alive.

**Comment by EjvindHald** [comment]
Schneider has provided this hardware directly to Dresden Electronics, who are now working on proper integration in Phoscon of this device.

**Comment by EjvindHald** [comment]
This is still relevant, and Dresden Electronics has received the hardware.

**Comment by mwaldhauer** [comment]
Is there an ETA on the integration ?

**Comment by Mimiix** [comment]
Not sure. A dev needs to pick it up. If DE has the device, they need to pick it up. 

I'll ask around :)

**Comment by perevers** [comment]
Looking forward to this working :)

**Comment by EjvindHald** [comment]
It is expected to be included in next version 2.13 according to DE.

**Comment by Cubixzno1** [comment]
That sounds Amazing!

**Comment by perevers** [comment]
That sounds amazing. Any ETA on version 2.13?

**Comment by EjvindHald** [comment]
It is still in progres...

**Comment by BOB-DK** [comment]
@EjvindHald 
Do you know what the status is at the moment?

**Comment by EjvindHald** [comment]
Schneider has provided a sample of many Wiser devices to DE, and I have tested these in beta version.

However, my mistake the 4 button battery device was not included. DE has received that device now, and they will support it in coming release. I do not when, as DE has been impacted by Covid-19.

**Comment by BOB-DK** [comment]
@EjvindHald 
Thanks for the answer.
Hope DE recovers quickly.
Looking forward to the upcoming release.

**Comment by mwaldhauer** [comment]
Still not fixed

**Comment by mwaldhauer** [comment]
Any news ?

**Comment by EjvindHald** [comment]
I tested it on version 2.13.04 and the device cannot be adopted. The result of this test was given to DE support, and today they replied that it has been handed over the development team.

**Comment by jh83** [comment]
Any updates on this?

**Comment by EjvindHald** [comment]
I suggest you contact Dresden Electronics to get latest status on this.

**Comment by Mimiix** [comment]
I ask manup to check

**Comment by manup** [comment]
The Wiser devices will be checked soon, we have a full set of products now for testing and integration.
Plan is to get them all working cleanly with DDF :)

**Comment by jh83** [comment]
> The Wiser devices will be checked soon, we have a full set of products now for testing and integration. Plan is to get them all working cleanly with DDF :)

Sounds great. Does that "full set" also include the "PowerTags"?

**Comment by manup** [comment]
> > The Wiser devices will be checked soon, we have a full set of products now for testing and integration. Plan is to get them all working cleanly with DDF :)
> 
> Sounds great. Does that "full set" also include the "PowerTags"?

The set includes the power plug 16A and connected socket outlet, do you mean these?

**Comment by jh83** [comment]
> > > The Wiser devices will be checked soon, we have a full set of products now for testing and integration. Plan is to get them all working cleanly with DDF :)
> > 
> > 
> > Sounds great. Does that "full set" also include the "PowerTags"?
> 
> The set includes the power plug 16A and connected socket outlet, do you mean these?

I was thinking about these: https://www.se.com/ww/en/product-range/63626-powertag/21517070574-powertag-energy/?N=2766576315

I have one of the three phase powerTags ordered. So if this isn't included in the above integration, then I will create a new ticket

**Comment by EjvindHald** [comment]
Is this PowerTag a part of the Wiser product series?

**Comment by EjvindHald** [comment]
I talked to a Product Manager at Schneider regarding this. The PowerTags are currently not a part of Wiser By SE. They are using ZigBee Green Power and not ZigBee 3.0 for communication.

**Comment by jkbkster** [comment]
> The Wiser devices will be checked soon, we have a full set of products now for testing and integration. Plan is to get them all working cleanly with DDF :)

We are so much looking forward to these devices omboarded. Any new status, or should I just spend all the savings to onboard Wiser for the home ?

**Comment by JesperJI** [comment]
Hi All
Did any of you get the Wiser wireless battery 4 button switch working?
Do you have a working DDF?

**Comment by mwaldhauer** [comment]
Works fine with the built-in check this Node flow though to get the button
press
[image: image.png]

Den lør. 10. feb. 2024 kl. 13.30 skrev JesperJI ***@***.***>:

**Comment by mwaldhauer** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/60813289/7a3db4b0-6727-4b22-a508-afd9979bc273)

**Comment by JesperJI** [comment]
Thank you.
I will buy a few of the battery switches then.
Strange the switch is not on the compatibility list yet.
