### ISSUE TITLE
LIDL Silvercrest Doorbell - HG06668

### ISSUE THREAD

**Issue by knutbrecht** [dresden-elektronik/deconz-rest-plugin#4537]
## Device

- Product name: LIDL Silvercrest Doorbell 
- Manufacturer: _TZ1800_ladpngdx
- Model identifier: TS0211
- Device type : Please remove all unrelated device types. 
  - Remote
  - Switch

## Screenshots

![Screenshot 2021-03-08 114041_Cluster](https://user-images.githubusercontent.com/60777615/110313121-4c1c1500-8006-11eb-8768-11229ca5e59a.png)
![Screenshot 2021-03-08 114140_node-info](https://user-images.githubusercontent.com/60777615/110313132-50e0c900-8006-11eb-866e-baff63add8b3.png)
![Screenshot 2021-03-08 114808_power](https://user-images.githubusercontent.com/60777615/110313143-550ce680-8006-11eb-8b35-ce74ad1ade25.png)

**Comment by knutbrecht** [comment]
![Screenshot 2021-03-08 120657_id](https://user-images.githubusercontent.com/60777615/110313584-f005c080-8006-11eb-9211-398775977bf9.png)
![Screenshot 2021-03-08 120805_ias-zone](https://user-images.githubusercontent.com/60777615/110313705-19265100-8007-11eb-990c-cf27e31e8c7a.png)
![Screenshot 2021-03-08 120851_diag](https://user-images.githubusercontent.com/60777615/110313773-33602f00-8007-11eb-9ad7-f03e05199c3c.png)
![Screenshot 2021-03-08 120936_otau](https://user-images.githubusercontent.com/60777615/110313833-4ecb3a00-8007-11eb-88b4-f72572d704d3.png)

**Comment by Mimiix** [comment]
what version of deCONZ are you on?

**Comment by knutbrecht** [comment]
2.09.03

**Comment by Mimiix** [comment]
It is supported by https://github.com/dresden-elektronik/deconz-rest-plugin/tree/v2.10.0-beta

Also, Make sure to re-pair after updating. It would be visible in the API.
