### ISSUE TITLE
SLC SmartOne S57003 - Wall 4xMono

### ISSUE THREAD

**Issue by svhelge** [dresden-elektronik/deconz-rest-plugin#4544]
The device (https://www.tlg.no/slc-smartone-zigbee-wall-remote-4-x-mono) is a variant of the 4 channel Suncricher remote. Other variants:
  * Namron | 4CH K8 4-gang (4512703)
  * EcoDim 
  * iCasa

## Device

- Product name: SLC SmartOne S57003 - Wall 4xMono
- Manufacturer: THE LIGHT GROUP AS
- Model identifier: S57003
- Device type : Please remove all unrelated device types. 
   - Remote
   - Switch

## Screenshots
  - Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/79386304/110403439-5fb69280-807d-11eb-9cc1-445a05e25441.png)
![image](https://user-images.githubusercontent.com/79386304/110403528-870d5f80-807d-11eb-84e7-ef828600fb29.png)

  - Node Info panel
![image](https://user-images.githubusercontent.com/79386304/110403210-00f11900-807d-11eb-830a-1d48ebcf2c98.png)
![image](https://user-images.githubusercontent.com/79386304/110403279-20884180-807d-11eb-9d89-c18450c03c6f.png)

  - Basic Cluster attributes in the Cluster Info panel.
![image](https://user-images.githubusercontent.com/79386304/110402937-8e803900-807c-11eb-92dc-60f2b791e31c.png)
![image](https://user-images.githubusercontent.com/79386304/110403052-bc657d80-807c-11eb-9166-d8c067b219aa.png)

Power configuration cluster:
![image](https://user-images.githubusercontent.com/79386304/110454787-f740d300-80c7-11eb-87b4-8300b9598e4a.png)
![image](https://user-images.githubusercontent.com/79386304/110454885-13447480-80c8-11eb-9d31-ba9b3c16bb2d.png)

Diagnostic cluster:
![image](https://user-images.githubusercontent.com/79386304/110455198-6c140d00-80c8-11eb-971e-3eef9d38637b.png)
![image](https://user-images.githubusercontent.com/79386304/110455391-ada4b800-80c8-11eb-9f09-1716cabbf588.png)

Identify cluster:
![image](https://user-images.githubusercontent.com/79386304/110455689-07a57d80-80c9-11eb-8d7f-40070257ae24.png)
![image](https://user-images.githubusercontent.com/79386304/110455798-2572e280-80c9-11eb-8c83-ecd6f23e4d55.png)

ZLL commissioning cluster:
![image](https://user-images.githubusercontent.com/79386304/110456830-4c7de400-80ca-11eb-9941-43555e3f32b8.png)
![image](https://user-images.githubusercontent.com/79386304/110457040-8222cd00-80ca-11eb-908d-be94533a83eb.png)

**Comment by Mimiix** [comment]
Can you add screenshots of all clusters?

**Comment by svhelge** [comment]
I added screenshots of
- Power configuration cluster
- Diagnostic cluster
- Identify cluster
- ZLL commissioning cluster
anything else needed?

**Comment by Mimiix** [comment]
I think this is fine. @SwoopX / @Smanar Can you check?

**Comment by svhelge** [comment]
@Mimiix , anything still missing? Or can the "Incomplete issue" label be removed?

**Comment by svhelge** [comment]
I created PR #4711 yesterday in order to resolve the issue.
