### ISSUE TITLE
Tuya Alarm

### ISSUE THREAD

**Issue by iisworks** [dresden-elektronik/deconz-rest-plugin#4549]
I noticed some closed threads, and I think this one should be supported in 2.10.2 (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3183)? 

But it shows up as a Smart Plug.
- Product name: Neo Coolcam Siren Alarm (Tuya)
- Manufacturer: _TZE200_d0yu2xgi
- Model identifier: TS0601
- Device type : Siren

## Screenshots
![image](https://user-images.githubusercontent.com/33196233/110489428-af35a680-80ef-11eb-8bfb-7753d195ca8e.png)

Pairing log:
[siren.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6109365/siren.log)

Ali link to device:
https://nl.aliexpress.com/item/4001252018563.html

**Comment by Smanar** [comment]
I m seing this one in the code, wich one deconz version are you using ?

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.10.2-beta

**Comment by Smanar** [comment]
You have done 2 inclusions without deleting something ?
The first time you will have the plug, the second one the siren.

**Comment by Smanar** [comment]
>I did remove

>without deleting something

**Comment by iisworks** [comment]
You mean in Phoscon? I did not see any sensor there, nor in deCONZ.
In deCONZ I only only the Smart Plug device (and some orphaned fairy Light from an old TVR I don't ee nown any more that keeps popping up, which does not help either).

**Comment by Smanar** [comment]
Ok, so try that.
- Set phosocn in permit join
- Read again basic attribute on deconz, cluster 0x0000, button "read"

It will trigger a new inclusion, if you can share the log during this step (on deconz/help/log with "info" and "info_l2"?

**Comment by iisworks** [comment]
Put Phoscon in Pairing mode (sensor), then read the Basic cluster 2x:
[siren.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6117719/siren.log)

**Comment by iisworks** [comment]
Another try, I deleted the device, and waited for it to reappear and read Basic:
[siren.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6118170/siren.log)

**Comment by Smanar** [comment]
You have tried the log feature in deconz ? deconz/help/log ?

BTW I m still searching the problem, can you check the manufacture number for your device ? in the node Info panel ?

**Comment by Smanar** [comment]
All is fine from your capture.

I have perhaps an idea, your device miss datecode AND SWbuild, I m asking if it can block the device creation.

**Comment by Smanar** [comment]
If I add some log in the coe, are you able to compile it for test ? (need a linux machine)

**Comment by iisworks** [comment]
Sorry, I can't.

**Comment by kxdyz** [comment]
Hi guys, I am also interested in make this Tuya Neo Coolcam siren work, can see it in the mesh but can't pair it in Phoscon at all.. If I can help with testing, please let me know. Thank you!

**Comment by Smanar** [comment]
Yep if you can confirm the manufacture name, and have you a linux machine to test some code modifcation ?

**Comment by kxdyz** [comment]
Does this image help? I have just clean ubuntu headless server and everything runs in docker, Phoscon, HomeAssistant included.. Or I can use for whatever testing necessary RPI4
![image](https://user-images.githubusercontent.com/81013481/111869156-38659c80-897e-11eb-93fb-431010cf6063.png)

**Comment by Smanar** [comment]
Nice ^^
Can you try with this branch

```
sudo apt install deconz-dev
git clone --branch siren_debug https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

And re-try an inclusion with logging "info" and "info_l2", this code will add debug line.

Better to make try on the PI4 (with deconz installed first), to don't perturbe your production network (just need to switch the conbee 5 mn for tests)

**Comment by kxdyz** [comment]
OK, think I got it.. log taken during search period https://textbin.cc/raw/TXTMIB2Ud1 hope it helps

**Comment by Smanar** [comment]
arrrrrr, I think I have find the problem.

```
sudo apt install deconz-dev
git clone --branch siren_model https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

sorry it s a new branch again, but this one will the future PR.

**Comment by kxdyz** [comment]
OK, please see here https://textbin.cc/raw/8rUjpb0FuN. Now I got Sensor ready message during pairing, but the device is not listed between sensors after I confirm by READY button

**Comment by Smanar** [comment]
It have worked ^^
The device is just not visible in phoscon, you haven't third app to use it ?

**Comment by kxdyz** [comment]
OK great.. :-) I connected testing RPI with deconz to HA and can see the device as on the picture.. device is disabled and I cant find how to enable it.. I will play with that later on.. but anyway, thank you very much for your prompt help..! will you make it part of production version for docker? 
![image](https://user-images.githubusercontent.com/81013481/111877652-8097b580-89a4-11eb-89a6-a30265bc13fa.png)

**Comment by Smanar** [comment]
I will make the PR immediatly, so it will be in a future deconz version.

To trigger the siren, you need to use the "light" device with the "state/alert" = "lselect", but not sure you have the "light" entry, I don't see it on the log, you problably need another PR > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4616

So I think, you will be some week for a perfect support withut compiling code yourself.

**Comment by kxdyz** [comment]
That is great, will wait for new version.. thank you very much!

**Comment by iisworks** [comment]
Cool, I will also test when it makes it to the next beta Docker image!

**Comment by machielw** [comment]
koenkk solved it for the newer version V3 in Zigbee2mqtt

https://github.com/Koenkk/zigbee2mqtt/issues/7051

**Comment by Smanar** [comment]
Ha yes, it seem at the good moment (during the pairing ?)
We need to send 2 tuya command
- the reset one 
- A new one, the 0x10 followed by 0x00, 0x02
