### ISSUE TITLE
Lidl Silvercrest Smart Plug (UK)

### ISSUE THREAD

**Issue by evan-shaw** [dresden-elektronik/deconz-rest-plugin#4557]
## Device

- Product name: Lidl Silvercrest Smart Plug
- Manufacturer: Silvercrest
- Model identifier: Heiman  TS011F / _TZ3000_00mk2xzy  Adapter plug
- Device type : Please remove all unrelated device types. 
  - Switch

### Basic
As can be seen above, these are recognised as being 2 different kinds of devices. (i.e. I have 2)
Also they are recognised as lights and not switches.

**Comment by Mimiix** [comment]
Missing some screens/ Differences?

**Comment by evan-shaw** [comment]
![Lidl Silvercrest](https://user-images.githubusercontent.com/34520506/110757746-a5bd5300-8243-11eb-96ab-1d796e559627.png)

The plugs, as far as I can tell, i.e. outside appearance, packaging box and labelling, are all identical, but here's the difference in Phoscon.

**Comment by Mimiix** [comment]
@SwoopX You integrated it, right?

**Comment by evan-shaw** [comment]
Yes they work fine. Just thought the identification was a bit weird.

**Comment by ebaauw** [comment]
Probably just need an entry in:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/db673839f8cf4ec867bb9471cf79477299c5a794/de_web_plugin.cpp#L480

**Comment by evan-shaw** [comment]
The first 4 devices you see in my screen capture above, should all be the same type and model.

**Comment by Mimiix** [comment]
Can you try to read the Basic cluster in deCONZ of those devices?

They aren't switches, as switches are something that "trigger" something else.

**Comment by ebaauw** [comment]
> The first 4 devices you see in my screen capture above, should all be the same type and model.

The third one is probably listed as "Heiman" because of the mac address prefix.  Same for the lightstrip at the bottom of the screenshot.  I don't understand where the "Adapter plug" Product comes from.

> But also, shouldn't they appear in the "Switches" list and not "Lights"?

Wired switches and plugs, used to smartify dumb devices, are exposed as `/lights` resources.  They look, smell, and feel like smart lights (from a Zigbee perspective), and are exposed like these.

Wireless switches, used to control ("trigger") smart devices, are exposed as `/sensors` resources.  They look, smell, and feel completely differently from smart lights, and are exposed differently.

**Comment by evan-shaw** [comment]
> Can you try to read the Basic cluster in deCONZ of those devices?
>                                                                                 Can you tell me how to do that please?
> They aren't switches, as switches are something that "trigger" something else.

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by evan-shaw** [comment]
I've tried earlier this morning to get this info without success. I basically can't start the deconz-gui.
I'm running my RPi headless as it oes quite a few other things. So use RealVNC for X access.
I stop deconz - systemctl stop deconz
start deconz-gui - systemctl start deconz-gui

But the deconz-gui won't attach to my VNC X display, so fails.
I've tried a few things without success. 

_systemd[1]: deconz-gui.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: deconz-gui.service: Failed with result 'exit-code'.
systemd[1]: deconz-gui.service: Service RestartSec=30s expired, scheduling restart.
systemd[1]: deconz-gui.service: Scheduled restart job, restart counter is at 2.
systemd[1]: Stopped deCONZ: ZigBee gateway -- GUI/REST API.
systemd[1]: Started deCONZ: ZigBee gateway -- GUI/REST API.
deCONZ[4428]: qt.qpa.screen: QXcbConnection: Could not connect to display :0
deCONZ[4428]: Could not connect to any X display_

I even tried changing the DISPLAY value to :1 in deconz-gui.service as my X DISPLAY in VNC is :1.0, but got the same as above with a :1 instead of :0

So sorry, I cannot get the cluster info, unless there is a way of getting this from some logs?

**Comment by senilio** [comment]
For getting X forwarding up and running, please take a look at https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Access-deCONZ-GUI-in-headless-setups

**Comment by senilio** [comment]
Feel free to jump on to discord and ping me there, and I'll try to get you sorted.

**Comment by evan-shaw** [comment]
Thanks to Senilo for the deconz-gui help.
Here's the basic cluster info for all 4 devices.
![Selection_320](https://user-images.githubusercontent.com/34520506/110943416-168f6880-8333-11eb-88ee-0c56a24e6fbb.png)
![Selection_319](https://user-images.githubusercontent.com/34520506/110943431-1a22ef80-8333-11eb-80a0-bbbae7491270.png)
![Selection_318](https://user-images.githubusercontent.com/34520506/110943443-1db67680-8333-11eb-9c3d-c39ea4a2eaa4.png)
![Selection_317](https://user-images.githubusercontent.com/34520506/110943452-20b16700-8333-11eb-864c-6837b2f581e5.png)
![Selection_316](https://user-images.githubusercontent.com/34520506/110943461-24dd8480-8333-11eb-8673-055dfa69f9db.png)
![Selection_314](https://user-images.githubusercontent.com/34520506/110943474-27d87500-8333-11eb-8bbe-ece3ba8d2550.png)
![Selection_313](https://user-images.githubusercontent.com/34520506/110943491-2ad36580-8333-11eb-8a13-54b763cbf8f8.png)

**Comment by Mimiix** [comment]
Seems to be paired incorrectly.
