### ISSUE TITLE
YSR-Mini-01

### ISSUE THREAD

**Issue by OnkelBuTscH** [dresden-elektronik/deconz-rest-plugin#4562]
## Device

- Product name: LED Controller YSR-Mini-01
- Manufacturer: YSRSAI
- Model identifier: ZB-CL01
- Device type : 
  - Other: LED Stripe Controller

## Screenshots

![IMG_20210311_152152](https://user-images.githubusercontent.com/33532780/110802473-84c62380-827e-11eb-8061-abe6088da11f.jpg)
![IMG_20210311_152241](https://user-images.githubusercontent.com/33532780/110802484-868fe700-827e-11eb-8176-e9e22b1c5234.jpg)
![IMG_20210311_152322](https://user-images.githubusercontent.com/33532780/110802494-87c11400-827e-11eb-9490-744413bfa1cb.jpg)
![Screenshot 2021-03-11 152637](https://user-images.githubusercontent.com/33532780/110802501-8859aa80-827e-11eb-8009-1291b117f433.png)
Node Info:
![node info](https://user-images.githubusercontent.com/33532780/110823933-d9739980-8292-11eb-820e-438e89f945a6.png)
Basic:
![cluster info](https://user-images.githubusercontent.com/33532780/110823909-d5477c00-8292-11eb-8eb7-3fc9404af323.png)
Identify:
![identify](https://user-images.githubusercontent.com/33532780/110827672-9adfde00-8296-11eb-8947-b819e26cb60c.png)
Groups:
![groups](https://user-images.githubusercontent.com/33532780/110827759-ad5a1780-8296-11eb-81fd-41433a9bdd19.png)
Scenes:
![scenen](https://user-images.githubusercontent.com/33532780/110828081-fb6f1b00-8296-11eb-8af3-cfc76773d00a.png)
On/Off:
![on off](https://user-images.githubusercontent.com/33532780/110827879-c82c8c00-8296-11eb-809e-c93bfcb46ebc.png)
Level Control:
![level](https://user-images.githubusercontent.com/33532780/110832627-cfa26400-829b-11eb-8687-45cee117cefe.png)
Color Control:
![color control 1](https://user-images.githubusercontent.com/33532780/110833622-f01eee00-829c-11eb-8618-25351084e3d7.png)
![color control 2](https://user-images.githubusercontent.com/33532780/110833632-f2814800-829c-11eb-93fa-e3627dba5fe6.png)
![color control 3](https://user-images.githubusercontent.com/33532780/110833638-f44b0b80-829c-11eb-861a-0027dd332210.png)
![color control 4](https://user-images.githubusercontent.com/33532780/110833645-f614cf00-829c-11eb-8dac-d4291d382f69.png)
![color control 5](https://user-images.githubusercontent.com/33532780/110833655-f7de9280-829c-11eb-9895-bc5f0ffdecd3.png)
ZLL comissioning:
![zll](https://user-images.githubusercontent.com/33532780/110834121-70455380-829d-11eb-9376-189297381213.png)
![zll2](https://user-images.githubusercontent.com/33532780/110834125-71768080-829d-11eb-9355-6f9310991fcc.png)

Hi,

I have a problem with the YSRSAI zigbee LED controller.
If I save the current white value as a scene, a wrong white value is set when i activate the scene.
It's the same with preset scenes night light or read etc...
Scenes with colors work properly.
Only scenes warm white - cold white are affected.

Link to the device: 
https://de.aliexpress.com/item/10000201716852.html?spm=a2g0o.productlist.0.0.424627b4s01Esv&algo_pvid=aa803659-f35f-4b76-9558-7279f4caaf3b&algo_expid=aa803659-f35f-4b76-9558-7279f4caaf3b-23&btsid=2100bdd816154701038204596ef3c8&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by Mimiix** [comment]
We need the screenshots from the device in deCONZ.

**Comment by OnkelBuTscH** [comment]
unfortunately i have no access to deconz. 
I use the conbee 2 stick on a pi without a gui in ioBroker.
Or is there another way?

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Access-deCONZ-GUI-in-headless-setups

**Comment by OnkelBuTscH** [comment]
I added screenshots of:

- Node Info
- Basic Cluster
- Identify Cluster
- Groups Cluster
- Scenes Cluster
- On/Off Cluster

**Comment by popy2k14** [comment]
@OnkelBuTscH have the same controller but cant even pair it.
How did you pair it?

I followed the manual -> pressed over 5 seconds -> led stripe flashes but deconz cant find it.

Which version of deconz(phoscon do you have?

**Comment by OnkelBuTscH** [comment]
> pressed over 5 seconds -> led stripe flashes two times and then stops but deconz cant find it.

I did the exact same thing.

> It also stops flashing when do not press "find lights" in deconz

I think it only flashes 2-3 times after pressing the button for 5 seconds that is normal. Then you can search in Phoscon.
After 10-20 seconds Phoscon found them.

The only thing I've changed is the Zigbee channel at 25.
But I don't think it has anything to do with it.?

Phoscon:
Version: 2.09.03 / 23.12.2020
Firmware: 26660700

**Comment by popy2k14** [comment]
ok, thx for clearing things up, then that "flashing" behaviour should be ok.
Have read elsewhere that it flashes until it is paired.

Sadly, i have tried it often but i just does'nt join my network (pairing doesnt work).

The only difference is, you have an older conbee II firmware.
Mine are:

2.09.03 / 23.12.2020
26680700

Do you have an conbee II ?

**Comment by OnkelBuTscH** [comment]
> Do you have an conbee II ?

Yes i have.

Unfortunately, I don't know what else could be the cause. :(
I have 6 led strips of it and none of them had this problem.

Do you have a hue bridge to test it?

**Comment by popy2k14** [comment]
ok, so maybe the lower firmware makes the difference!?
Or mine is just defect.

Sadly no hue bridge, selled them all after the i was gone the deconz way :-)
This is also my first pairing issue with deconz.

**Comment by popy2k14** [comment]
Another question, when it is not paired (like mine) and you connect it to power, does it light up white (the two white leds)?

**Comment by OnkelBuTscH** [comment]
> when it is not paired (like mine) and you connect it to power, does it light up white (the two white leds)?

Yes, only warm white and cold white LED's light up if you only connects to power.

**Comment by popy2k14** [comment]
Exactly the same here, just cant pair it :-(

**Comment by popy2k14** [comment]
Just an idea:

is downgrading the firmware of my conbee II from 26680700 to 26660700 possible without loosing my network?
Or is it not recommended?

**Comment by OnkelBuTscH** [comment]
> is downgrading the firmware of my conbee II from 26680700 to 26660700 possible without loosing my network?

Unfortunately I don't know, ^^ better ask about it in the discord.

**Comment by OnkelBuTscH** [comment]
FYI, I upgraded the Firmware to 26680700.
Still no problem with pairing.
Maybe your LED Controller is damage?

**Comment by popy2k14** [comment]
Tested the device on an friends hue bridge and it works without an issue. Found instantly and Rgb LEDs are working as they should.

So it seems that there incompatibility between 'my' device and deconz+conbee II.

The HUE bridge has detected it as :

Manufacturer: YSRSAI
Model: ZB-CL01
Sw: 1.0.7

How can I help to debug the issue?

**Comment by popy2k14** [comment]
Hey guys, i have successfully paired it after downgrading deconz to 02.07.01.
Have raised an issue here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4615
and can provide a debug log when needed.

PS.: sorry for hijacking this thread and YES i have the same issue with scenes like @OnkelBuTscH

**Comment by popy2k14** [comment]
Not solved

**Comment by popy2k14** [comment]
Not solved

**Comment by Smanar** [comment]
So even with the microSD and the extension cable you are not able to include new devices at all ?

**Comment by popy2k14** [comment]
Sorry for confusion. Pairing works now, I have closed #4615. 

But the OP issue with scenes setting wrong white value is still a thing. Have now 3 of them, and all with the same issue.

**Comment by popy2k14** [comment]
Not solved.

**Comment by popy2k14** [comment]
Not solved.

**Comment by popy2k14** [comment]
Bump

**Comment by popy2k14** [comment]
Bump

**Comment by popy2k14** [comment]
Bump, what is needed to get his working?
