### ISSUE TITLE
Can't connect to REST API

### ISSUE THREAD

**Issue by jscheurwater** [dresden-elektronik/deconz-rest-plugin#4563]
If I execute the GET command in Postman, I'm getting an internal IP like: 172.30.xx.x
As i read in [this ](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2716) discussion, I need another kind of IP (like 192.168.x.x).

Does somebody know how to get this IP address. I can't find troubleshooting on this issue in the REST API documentation.
Thanks in advance!

**Comment by ziegelwiese** [comment]
Hello.
For me, this was a network issue within docker. 
Seems all containers are assigned to a network. Hence, when you start your deconz container be sure to assign it to the same network as your smart home software.
Found clues here: https://www.libe.net/conbee-2 

Enjoy
