### ISSUE TITLE
ZTS-EU Moes switch / ZTS-EU1-W (1 gang) ZTS-EU2-W (2 gangs) ZTS-EU3-W (3 gangs)Device name

### ISSUE THREAD

**Issue by andys73** [dresden-elektronik/deconz-rest-plugin#4571]
## Device

- Product name: ZTS-EU
- Manufacturer: Moes
- Model identifier: It can come in 1, 2 or 3 gang https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/ZTS-EU.md - not detected at all by Deconz - HA + PI3 + CONBEE2
- Device type :  
  - Switch

## Screenshots

N/A - device not detected

### Basic

N/A - device not detected

### Identify

N/A - device not detected

### Alarms

N/A - device not detected

### Device Temperature

N/A - device not detected

### Groups

N/A - device not detected
### Scenes

N/A - device not detected

### On/Off

N/A - device not detected

### Level Control

N/A - device not detected
### Color Control

N/A - device not detected
### Simple Metering

N/A - device not detected
### Diagnostics

N/A - device not detected
### Other clusters that are not mentioned above

N/A - device not detected

**Comment by Mimiix** [comment]
If it's not detected, your not pairing it correctly.

Closing this issue as it's not a request.
