### ISSUE TITLE
D-Link Smart Door/Window Sensor

### ISSUE THREAD

**Issue by jazza1234567** [dresden-elektronik/deconz-rest-plugin#4576]
## Device
Product name: Smart Door/Window Sensor
Manufacturer: D-Link
Model identifier: DCH-B112
Device type : Sensor

### Node Info
![image](https://user-images.githubusercontent.com/76201902/111015440-d7c5e500-83fc-11eb-938c-e2d4dfb7721c.png)
![image](https://user-images.githubusercontent.com/76201902/111015465-017f0c00-83fd-11eb-8f30-47fa8803eeac.png)

### Basic Info
![image](https://user-images.githubusercontent.com/76201902/111015459-f2985980-83fc-11eb-9221-c1b5383d3f79.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/76201902/111015473-0a6fdd80-83fd-11eb-99a6-9b9e7b90d299.png)

### Identify
![image](https://user-images.githubusercontent.com/76201902/111015482-122f8200-83fd-11eb-86df-fe9ddb613249.png)

### Poll Control
![image](https://user-images.githubusercontent.com/76201902/111015488-1b205380-83fd-11eb-9c18-cba02bd372cc.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/76201902/111015496-25425200-83fd-11eb-85fa-b83a9603e626.png)
![image](https://user-images.githubusercontent.com/76201902/111015506-31c6aa80-83fd-11eb-8150-72ef00ce696f.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/76201902/111015518-3ab77c00-83fd-11eb-9b8e-5d5ae6e111b9.png)

### OTAU 
![image](https://user-images.githubusercontent.com/76201902/111015524-41de8a00-83fd-11eb-9a12-98f39113dc53.png)

**Comment by jazza1234567** [comment]
This issue is still pending. If i can contribute anymore data to help I am
more than happy to do so!

**Comment by NW27** [comment]
Hi,
I have some of these sensors. Any idea when they will be available in the app?
Thanks Neil.
