### ISSUE TITLE
Can't manually update because missing file

### ISSUE THREAD

**Issue by Jacksonbm1** [dresden-elektronik/deconz-rest-plugin#4583]
## Describe the bug

I'm trying to update the firmware for my conbee II following the steps here: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian

However, I keep getting an error that seems related to missing /dev/ttyACM0 not found.

## Steps to reproduce the behavior

Once I've reached step 3 (already did 1-2):

`sudo GCFFlasher_internal -t 60 -d /dev/ttyACM0 -f deCONZ_ConBeeII_0x26680700.bin.GCF`, I ensure I'm updating to the most recent firmware and ad `-x 3` for verbosity.

## Expected behavior
It should update, but instead I get an error log. THhe most important line is: `/dev/ttyACM0 not found` That file doesn't seem to exist in my directory.

## Environment

- version 2.09.03 / 12/23/2020
-  firmware 26580700

 - Host system: (Raspberry Pi)
 - Running method: (Raspbian)
 - Firmware version: (26580700)
 - deCONZ version: (2.09.03)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? NO

**Comment by Smanar** [comment]
It s not a "file", it s the "device port".

Can you try just the command
`GCFFlasher_internal -l`
