### ISSUE TITLE
Feature: Get light/sensor from uniqueid

### ISSUE THREAD

**Issue by jonatanolofsson** [dresden-elektronik/deconz-rest-plugin#459]
The invariant of a zigbee device is its ieee id and endpoint id - in deconz combined as the uniqueid. It would be useful to be able to address the REST api using this instead of the assigned node id (which will change between repairings).

My suggestion is to replace getLightNodeForId with a getter that accepts either node id or, if the node id is not found, parses the string as a deCONZ::Address and endpoint and retrieves e.g. lights through getLightNodeForAddress

**Comment by manup** [comment]
> My suggestion is to replace getLightNodeForId with a getter that accepts either node id or, if the node id is not found, parses the string as a deCONZ::Address and endpoint and retrieves e.g. lights through getLightNodeForAddress

Good point, it would improve lifetime of applications as well, since id might change for reasons like reset, deleting and rejoin devices or simply transfer to another ConBee/RaspBee setup/machine.

**Comment by jonatanolofsson** [comment]
Should the uniqueid be sent on the websocket as well?

**Comment by jonatanolofsson** [comment]
Also, the equivalent would of course also apply to sensors
