### ISSUE TITLE
Request initial support for Paulmann Gent color remote control

### ISSUE THREAD

**Issue by christian-fau** [dresden-elektronik/deconz-rest-plugin#4594]
- Product name: Smart Home ZigBee remote control Gent
- Manufacturer: Paulmann Licht GmbH
- Model identifier: RemoteControl
- Device type : 
   - Remote

## Screenshots

<!--
  Screenshots help to identify the device and its capabilities. Please refer to:
  https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support
  for examples of the required screenshots.

  Required screenshots:
  - Endpoints and clusters of the node

  - Node Info panel
  - 
![grafik](https://user-images.githubusercontent.com/59390547/111510692-50ef7000-874e-11eb-92cd-fccb9eb60d73.png)

### Basic
![grafik](https://user-images.githubusercontent.com/59390547/111510590-37e6bf00-874e-11eb-96dd-c06a20eaf1d3.png)

### Identify
![grafik](https://user-images.githubusercontent.com/59390547/111510981-92801b00-874e-11eb-9eba-5c1762f46030.png)

### Groups
![grafik](https://user-images.githubusercontent.com/59390547/111510442-138ae280-874e-11eb-977c-1666a6275488.png)
![grafik](https://user-images.githubusercontent.com/59390547/111510501-21406800-874e-11eb-9deb-ae88be075afc.png)

### Scenes
![grafik](https://user-images.githubusercontent.com/59390547/111511246-d6732000-874e-11eb-9ce2-804a8ff08314.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511346-ef7bd100-874e-11eb-9c5e-417bb67179de.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511420-01f60a80-874f-11eb-948d-ecbc707c6204.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/59390547/111511049-a1ff6400-874e-11eb-9296-f8bd81afa514.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511111-b4799d80-874e-11eb-99a3-f8838665113d.png)

### Level Control
![grafik](https://user-images.githubusercontent.com/59390547/111511154-c0fdf600-874e-11eb-836f-a1c6070f4d4d.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511203-ca875e00-874e-11eb-84b2-47cd47ddf1c4.png)

### Color Control
![grafik](https://user-images.githubusercontent.com/59390547/111511468-0fab9000-874f-11eb-96aa-458ba38224fa.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511512-1d611580-874f-11eb-9d55-e7723f8288da.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511564-29e56e00-874f-11eb-8285-a38d1c5e31aa.png)
![grafik](https://user-images.githubusercontent.com/59390547/111511601-3669c680-874f-11eb-89df-85913f2c1df5.png)

### Simple Metering
![grafik](https://user-images.githubusercontent.com/59390547/111511702-4b465a00-874f-11eb-80f8-afdc79b26498.png)

### Other clusters that are not mentioned above
OTAU
![grafik](https://user-images.githubusercontent.com/59390547/111511908-7761db00-874f-11eb-94c9-73eb1ded0adb.png)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by christian-fau** [comment]
Hi Dennis!
My apologize for the screenshots out of clipboard which did not work :-(
I posted a new request with all the required pictures

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4604

Best regards
Christian

--- Original-Nachricht ---
Von: Dennis D
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Request initial 
support for Paulmann Gent color remote control (#4594)
Datum: 17. März 2021, 19:42
An: dresden-elektronik/deconz-rest-plugin
Cc: christian-fau, Author


Closed #4594.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", 
"potentialAction": { ***@***.***": "ViewAction", "target": 
"https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4594#event-4471981234", 
"url": 
"https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4594#event-4471981234", 
"name": "View Issue" }, "description": "View this Issue on GitHub", 
"publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
"https://github.com" } } ]
