### ISSUE TITLE
Tuya HY368 new manufacturer id

### ISSUE THREAD

**Issue by paule1120** [dresden-elektronik/deconz-rest-plugin#4595]
## Describe the question or issue you are having

 Hello,
i have a problem. I cannot get an entitie of my new Tuya HY368 thermostat.
I have one since some times and it works. I bought 3 new one, but i can´t use them in Home Assistant.
I don´t know if it is a hassio or a deconz problem. I hope you can help.
I tried: reconnect, reset the device, delete the node, search new sensor and add the new device, restart the plugin, restart hassio
but nothing happens. Only the name of the new device changed always.

## Screenshots
This one works since some times
<img width="820" alt="HY368 iO" src="https://user-images.githubusercontent.com/78304880/111521195-2b1b9880-8759-11eb-8852-6441ebe55b64.PNG">

This one is a new one
<img width="832" alt="HY368 no function" src="https://user-images.githubusercontent.com/78304880/111521310-4ab2c100-8759-11eb-80b2-e39f93fcedb9.PNG">

## Environment

 - Host system: Raspberry Pi 4 4GB 
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.09.03
 - Device: ConBee II 
 - Do you use an USB extension cable: yes 3m
 - Is there any other USB or serial devices connected to the host system? If so: USB to SATA (SSD)

**Comment by Mimiix** [comment]
It's a new version I guess. @Smanar

**Comment by Smanar** [comment]
Lol yes ^^, seriously, like pokemons.

But the device is already in the code, at least a part, you can't try with more recent version ?

**Comment by paule1120** [comment]
Hello
@Smanar what you mean with recent version?
Should i update the thermostat? If yes can you tell me how?

**Comment by Smanar** [comment]
No, update deconz, if you want to use only stable version the new one will be in some days I think.

**Comment by paule1120** [comment]
OK. I will wait for the new stable version and test it again and notice you

**Comment by paule1120** [comment]
Hello, I updated today deconz to the new version 6.8.0 and now it works. Thank you

**Comment by ruipalhinhas** [comment]
Hello @Smanar,

Today I received a new HY368 valve but when adding to deconz it seems to be yet again a new model... This time it's __TZE200_cpmgn2cf_
![image](https://user-images.githubusercontent.com/79115158/206039419-617c7084-f764-4e3f-8c27-11cc692210ff.png)
![image](https://user-images.githubusercontent.com/79115158/206039467-7904f0e6-2113-48dc-adf7-fa90b5bd0717.png)

Should I create a new issue for this? Let me know please - thanks!

**Comment by Smanar** [comment]
For the moment not possible adding new tuya TRV, new device need to be added using DDF, and the PR to support TUYA TRV is still in waiting list.
