### ISSUE TITLE
ROBB Smarrt 4-button Transmitter (ROB_200-008-0)

### ISSUE THREAD

**Issue by DieterKoblenz** [dresden-elektronik/deconz-rest-plugin#4601]
## Device

- Product name: ROB_200-008-0
- Manufacturer: ROBB Smarrt
- Model identifier: ROB_200-008
- Device type : Please remove all unrelated device types. 
  - Remote

## Screenshots

![NodeInfo](https://user-images.githubusercontent.com/2961896/111617623-976dba80-87a0-11eb-902b-08e7add9b5dd.png)
![BasicCluster](https://user-images.githubusercontent.com/2961896/111617631-99d01480-87a0-11eb-87d6-e0fdacb2725e.png)
![BasicCluster2](https://user-images.githubusercontent.com/2961896/111617640-9c326e80-87a0-11eb-8879-4e4e02ec25e9.png)

### Other clusters that are not mentioned above
Power:
![ClusterPower-1](https://user-images.githubusercontent.com/2961896/111617914-fb907e80-87a0-11eb-9d60-0d005631ecb0.png)

I hope this is sufficient. Please let me know otherwise.

**Comment by SwoopX** [comment]
From what I see here, the device seems to be paired correctly and at least one seneor node got created. Is the device usable?

**Comment by DieterKoblenz** [comment]
It's not added in phoscon and/or home assistant

**Comment by SwoopX** [comment]
Deconz != Phoscon, so that's expected. Not popping up somehow in HA is an indication it's not fully integrated yet and a look at the code confirms this.

Can you please provide the [INFO] messages on the button presses from the debug output? You can do that from deconz GUI, level INFO and INFO_L2 should be sufficient.

**Comment by DieterKoblenz** [comment]
![image](https://user-images.githubusercontent.com/2961896/112718434-445bdc00-8ef3-11eb-9dbd-8615b0e73801.png)

Button Top Left (I) = On
Button Top Right (O) = Off
Button Bottom Left (I) = On
Button Bottom Right (O) = Off

**Comment by DieterKoblenz** [comment]
Is there a way to add a button map manually?

**Comment by DieterKoblenz** [comment]
Please, I'd appreciate some input or guidance to help add this device.

**Comment by DieterKoblenz** [comment]
Still active issue.
