### ISSUE TITLE
Aurora AU-A1ZBR16A

### ISSUE THREAD

**Issue by stuart-c** [dresden-elektronik/deconz-rest-plugin#4603]
## Device

- Product name: Aurora AU-A1ZBR16A
- Manufacturer: Aurora
- Model identifier: Smart16ARelay51AU
- Device type : 
  - Sensor
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/2722478/111655836-e0a22680-8801-11eb-872a-ee8d041a8d75.png)
![image](https://user-images.githubusercontent.com/2722478/111655942-f9124100-8801-11eb-85d3-7927f7f58713.png)

### Basic
![image](https://user-images.githubusercontent.com/2722478/111656085-1cd58700-8802-11eb-9c0b-559fe61ebca6.png)

### Identify
![image](https://user-images.githubusercontent.com/2722478/111656487-7938a680-8802-11eb-8b67-12e468a1a6b3.png)

### Alarms
![image](https://user-images.githubusercontent.com/2722478/111656522-83f33b80-8802-11eb-9123-e8eca2ff742c.png)

### Device Temperature
![image](https://user-images.githubusercontent.com/2722478/111656570-8f466700-8802-11eb-8d81-723bb700fd07.png)

### Groups
![image](https://user-images.githubusercontent.com/2722478/111656618-9c635600-8802-11eb-9e86-f6cb46a27912.png)

### Scenes
![image](https://user-images.githubusercontent.com/2722478/111656675-a5ecbe00-8802-11eb-954f-14e23effe1a0.png)

### On/Off
![image](https://user-images.githubusercontent.com/2722478/111656713-af762600-8802-11eb-9a5e-e0879f8bde06.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/2722478/111656145-2a8b0c80-8802-11eb-9a42-1872a9c5c015.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/2722478/111656279-48587180-8802-11eb-9294-8cf436118e2f.png)

**Comment by stuart-c** [comment]
Is there anything else needed?

**Comment by SwoopX** [comment]
Nope
