### ISSUE TITLE
Paulmann RGBW remote control Gent

### ISSUE THREAD

**Issue by christian-fau** [dresden-elektronik/deconz-rest-plugin#4604]
I appologize for the first request where all the screenshots from the clipboard didn't work :-(

## Device

- Product name: Paulmann ZigBee remote Control RGB GENT
- Manufacturer: Paulmann Licht GmbH
- Model identifier: RemoteControl
- Device type : Please remove all unrelated device types. 
  - Remote
 
## Screenshots

  Required screenshots:
  - Endpoints and clusters of the node
  - Node Info panel
![Cluster_Node Info 2021-03-18 16-40-07](https://user-images.githubusercontent.com/59390547/111660985-e94d2980-880e-11eb-9c4c-cd681d1d62b2.png)

### Basic
![Basic_Cluster 2021-03-18 16-42-58](https://user-images.githubusercontent.com/59390547/111661202-1bf72200-880f-11eb-909d-fc07ea379264.png)

### Identify
![IdentifyCluster 2021-03-18 16-50-13](https://user-images.githubusercontent.com/59390547/111661266-2ca79800-880f-11eb-8903-77d8fa8fa4a1.png)

### Groups
![GroupsCluster1 2021-03-18 16-44-18](https://user-images.githubusercontent.com/59390547/111661330-3b8e4a80-880f-11eb-880a-d7c785565892.png)
![GroupsCluster2 2021-03-18 16-49-11](https://user-images.githubusercontent.com/59390547/111661361-40eb9500-880f-11eb-833a-451d948fefea.png)

### Scenes
![ScenesCluster1 2021-03-18 16-54-13](https://user-images.githubusercontent.com/59390547/111661408-4b0d9380-880f-11eb-907d-193dc630694d.png)
![ScenesCluster2 2021-03-18 16-54-50](https://user-images.githubusercontent.com/59390547/111661436-4f39b100-880f-11eb-8da2-ebe9f3697c8b.png)
![ScenesCluster3 2021-03-18 16-55-23](https://user-images.githubusercontent.com/59390547/111661458-5365ce80-880f-11eb-89f6-c4a6754c694c.png)
![ScenesCluster4 2021-03-18 16-55-47](https://user-images.githubusercontent.com/59390547/111661487-56f95580-880f-11eb-8db4-cd4742abf0e5.png)

### On/Off
![OnOff1 2021-03-18 16-51-01](https://user-images.githubusercontent.com/59390547/111661506-5d87cd00-880f-11eb-8ad4-4819292723d8.png)
![OnOff2 2021-03-18 16-51-33](https://user-images.githubusercontent.com/59390547/111661531-61b3ea80-880f-11eb-82eb-3365667bf897.png)

### Level Control
![LevelControl1 2021-03-18 16-52-35](https://user-images.githubusercontent.com/59390547/111661547-66789e80-880f-11eb-881c-6b90df157497.png)
![LevelControl2 2021-03-18 16-53-15](https://user-images.githubusercontent.com/59390547/111661565-6aa4bc00-880f-11eb-83f6-5dd9e15351f8.png)

### Color Control
![ColorControl1 2021-03-18 17-16-08](https://user-images.githubusercontent.com/59390547/111661603-742e2400-880f-11eb-8d97-fd98a9d1c644.png)
![ColorControl2 2021-03-18 16-56-55](https://user-images.githubusercontent.com/59390547/111661616-77291480-880f-11eb-9d49-abb4d268fe91.png)
![ColorControl3 2021-03-18 16-57-25](https://user-images.githubusercontent.com/59390547/111661632-7a240500-880f-11eb-9c00-2b9661eb5d0a.png)
![ColorControl4 2021-03-18 16-57-56](https://user-images.githubusercontent.com/59390547/111661648-7d1ef580-880f-11eb-91ec-86ec875c2a1c.png)
![ColorControl5 2021-03-18 16-58-16](https://user-images.githubusercontent.com/59390547/111661661-7f814f80-880f-11eb-936b-ccde1517796d.png)

### ZZL Commisioning
![ZZL Commisioning 2021-03-18 17-31-21](https://user-images.githubusercontent.com/59390547/111662365-2534be80-8810-11eb-9ba7-2fe15d8656c3.png)

### OTAU
![OTAU-Cluster 2021-03-18 16-59-26](https://user-images.githubusercontent.com/59390547/111661704-8b6d1180-880f-11eb-8c3e-ddd429c5d11a.png)

**Comment by elronzo** [comment]
Support for this device would be great!

**Comment by christian-fau** [comment]
Please reopen this request since it isn't solved yet.
Regards Christian


--- Original-Nachricht ---
Von: github-actions[bot]
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Paulmann RGBW remote 
control Gent (#4604)
Datum: 22. April 2021, 3:53
An: dresden-elektronik/deconz-rest-plugin
Cc: christian-fau, Author



As there has not been any response in 28 days, this issue will be closed. 
@ OP: If this issue is solved post what fixed it for you. If it is not 
solved, request to get this opened again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4604#issuecomment-824479269> 
, or unsubscribe

**Comment by elronzo** [comment]
+1 for reopen.

**Comment by christian-fau** [comment]
+1


--- Original-Nachricht ---
Von: elronzo
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Paulmann RGBW remote 
control Gent (#4604)
Datum: 22. April 2021, 9:21
An: dresden-elektronik/deconz-rest-plugin
Cc: christian-fau, Author



+1 for reopen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4604#issuecomment-824605524> 
, or unsubscribe

**Comment by Mimiix** [comment]
Please make sure to bump next time.

**Comment by christian-fau** [comment]
how to bump and why for a request? (Newbee -question)
Is there anybody who can take or will take an assignment?

**Comment by Smanar** [comment]
I think, there is one with free time for this one ATM.
But you can try yourself, this device seem classic, you just need to mimic a similar one and changing some values, like the mac adress or the model id

**Comment by christian-fau** [comment]
No idea how :-(
What would be a similar one? What file(s) to adopt?


--- Original-Nachricht ---
Von: Smanar
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Paulmann RGBW remote 
control Gent (#4604)
Datum: 15. Mai 2021, 19:25
An: dresden-elektronik/deconz-rest-plugin
Cc: christian-fau, Author



I think, there is one with free time for this one ATM.
But you can try yourself, this device seem classic, you just need to mimic 
a similar one and changing some values, like the mac adress or the model id

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4604#issuecomment-841696936> 
, or unsubscribe

**Comment by Smanar** [comment]
Ok so have started something
You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch paulmann https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

If you have a small raspberry,it can freeze during compilation, my pi 3 do, so remove "-j2"

This code just permit to the device be included in the api, so you will have a ZHAswitch but not working
Now you need to enable log, with "info", press a button look at the message and edit the file /usr/share/deCONZ/devices/button_maps.json according to result.

It s  a simple json file, but you need to restart deconz after a modification.

**Comment by Daeny85** [comment]
Hello
I would also be interested in integrating that Paulmann Remote.

**Comment by mat-l** [comment]
Are the mentioned Paulmann coins working already or not yet?

**Comment by mat-l** [comment]
@Smanar I am planning to order some of the devices RGBW and dimmable light from Paulmann. Is there an tutorial or procedure, that I can follow to get them working with Deconz and Home Assistant? I am willing to contribute although I don't know the workflows yet.
