### ISSUE TITLE
PWA and Home Assistant won't work with new version

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#461]
I'm not sure if it's just because of the new version (2.05.10-qt5) or because I added the `--http-listen` option to the start command.

Anyway now both the official PWA and the Home Assistant won't discover DeCONZ.
Also, if I define the IP manually in Home Assistant, it won't be able to connect.

**Comment by FezVrasta** [comment]
I tried without the `--http-listen` and it still doesn't work ("can't get API key"). So it seems like it's the version the problem

**Comment by manup** [comment]
Can you provide a error log from Home Assistant?
Do you run deCONZ on a other port than 80 or 8080?

**Comment by FezVrasta** [comment]
I ran it on port 80. I'll try to provide a log ASAP

**Comment by marthoc** [comment]
@FezVrasta you may also want to raise an Issue for @Kane610 to look at the Home Assistant side: https://github.com/kane610/deconz.

**Comment by FezVrasta** [comment]
I doubt it's an home-assistant problem because it can be reproduced with the official Dresden PWA

**Comment by Kane610** [comment]
I'm awaiting the logs :)

**Comment by FezVrasta** [comment]
I doubt I'll be able to provide them anytime soon unfortunately, my home is the "production" one and I can't afford to stay without lights :-( wifey would get mad

**Comment by Kane610** [comment]
Enable debug with logger component, upgrade deconz, restart hass, collect logs, fall back to old version, profit 👍 15 minutes at most, doesn't really affect the lights

**Comment by FezVrasta** [comment]
Umh, I was going to do some test and I noticed I'm on 2.05.10 even if I remember I did restore the old 2.04.x version... I guess I accidentally installed again the same deb package and that fixed the problem I was having with the PWA app and Home Assistant.
