### ISSUE TITLE
Systemd file replaced on every update

### ISSUE THREAD

**Issue by mariusmotea** [dresden-elektronik/deconz-rest-plugin#462]
Hi,

i monitor this repo for updates and on every update i need to manually revert the systemd file that has some custom settings for my project. If will be possible to ignore this file on updates then it will be much simple to keep deconz up to date.

Thanks,
Marius.

**Comment by snozzlebert** [comment]
Maybe you could use the systemd overlay/override mechanism: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/295#issuecomment-347615035

**Comment by mariusmotea** [comment]
Thanks, this is exactly what i need.
