### ISSUE TITLE
Lutron Aurora paired, detected as a switch, but controls does nothing.

### ISSUE THREAD

**Issue by incognit-o** [dresden-elektronik/deconz-rest-plugin#4620]
## Describe the question or issue you are having

My Lutron Aurora (Z3-1BRL / Friends of Hue Dimmer) successfully pairs and is recognized as a switch in deCONZ. In addition to this, I have 2 RGB LED strip & 2 Sengled RGB LED in a group that works fine with strong connections with my ConBee. They do respond to my controls via web page reliably. I tried adding my Lutron dimmer in the group and mapping controls to it in the switch editor. However, rotating the dimmer dial and the center button do nothing.

## Screenshots

![image](https://user-images.githubusercontent.com/65986845/111887246-09652000-89aa-11eb-8089-50c404224a85.png)

![image](https://user-images.githubusercontent.com/65986845/111887279-429d9000-89aa-11eb-82da-642dafc4fe36.png)

![image](https://user-images.githubusercontent.com/65986845/111887236-f05c6f00-89a9-11eb-8b38-523e401347cb.png)

![image](https://user-images.githubusercontent.com/65986845/111886744-770f4d00-89a6-11eb-86d5-629f67861698.png)

![image](https://user-images.githubusercontent.com/65986845/111886799-eedd7780-89a6-11eb-9921-e07e0620b9dd.png)

![image](https://user-images.githubusercontent.com/65986845/111886805-fac93980-89a6-11eb-9d62-7cbaf2f855f0.png)

## Environment

 - Host system: Raspberry Pi 4 Model B 4GB
 - Running method: Marthoc Docker container on Raspbian (deployed with docker-compose)
 - Firmware version: ~~26580700~~  **Updated to 26680700** 
 - deCONZ version: 2.10.03
 - Device: ConBee II
 - Do you use an USB extension cable: No
 - Is there any other USB or serial devices connected to the host system: None

## deCONZ Logs

I'm not sure which logs to include here. I tried checking out the output with APS, ZDP, ZCL, and INFO and did not see anything potentially related to this issue although I can be wrong. Please let me know if there's anything else I should include.

## Additional context

I know the dimmer switch works and is not defective because the dimmer dial and the button work fine with ZHA. See below for events via ZHA:
![image](https://user-images.githubusercontent.com/65986845/111887556-1a169580-89ac-11eb-8b2c-b7b54da8a29f.png)
When I have everything paired with deCONZ and listening on deconz_event via Developer's Tools on Home Assistant always turns up empty.

Please let me know if I need to include anything more here. I'd like to get this dimmer switch working with deCONZ!

**Comment by incognit-o** [comment]
I just updated my ConBee II from firmware 26580700 to 26680700 but I'm still having the same problem.

![image](https://user-images.githubusercontent.com/65986845/111910369-783c8a80-8a37-11eb-90bf-368ca4d34b95.png)

![image](https://user-images.githubusercontent.com/65986845/111910419-acb04680-8a37-11eb-916e-3e4866220710.png)

**Comment by incognit-o** [comment]
I tried running deCONZ bare metal on my Windows laptop with ConBee II plugged in that instead of in Docker container on Raspberry Pi. I'm still getting the same problem. Pairing works fine, deCONZ recognizes Lutron Aurora correctly, but controls still don't do anything.

**Comment by Mimiix** [comment]
Do you get any events from it in HA?>

**Comment by incognit-o** [comment]
@Mimiix I tried listening for 'deconz_event' on HA. Nothing shows up when I try pressing the button or rotating the dial.

**Comment by Mimiix** [comment]
Wait, is this a dimmer without power?

**Comment by incognit-o** [comment]
Yes, it's a battery operated dimmer if that's what you mean. It goes over a pre-existing light switch like so:
![image](https://user-images.githubusercontent.com/65986845/112042360-cd52cc00-8b1d-11eb-8a10-586c6a3a3adf.png)

**Comment by Mimiix** [comment]
No but, is it a zgp switch? 

Either way, can you get logs on aps 2, info 2 and error 2?

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2305.

**Comment by incognit-o** [comment]
@ebaauw Thanks, I just read that issue. You mention this in the post:
> The switch is supported by the REST API plugin.

Are you suggesting that it doesn't work in Phoscon, only REST API?

Now, I'm not familiar with deCONZ but I'm assuming HA uses REST API for listening on `deconz_event`? If the switch is indeed working via REST API, button events should show up there, right? If so, this is not happening for some reason...

Should I try connecting to deCONZ via WebSockets instead? Would it work there? 

I'm not really exactly sure what to do here... I guess I'd have to watch logs with `--dbg-info=2 and --dbg-error=1` while pairing with Aurora?

**Comment by ebaauw** [comment]
I don't know what changed, but indeed, my Lutron Aurora no longer seems to control anything after pairing to v2.10.3-beta.  Furthermore, the resource now looks like:
```
{
  "config": {
    "battery": 100,
    "group": "162",
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "ad19686e65ba0c00aa9cffef8b4bc29a",
  "lastseen": "2021-03-23T21:02Z",
  "manufacturername": "Lutron",
  "mode": 1,
  "modelid": "Z3-1BRL",
  "name": "Z3-1BRL 19",
  "state": {
    "buttonevent": null,
    "eventduration": null,
    "lastupdated": "none"
  },
  "swversion": "3.8",
  "type": "ZHASwitch",
  "uniqueid": "ff:ff:00:0f:e7:fd:e9:08-01-fc00"
}
```

**Comment by ebaauw** [comment]
What firmware is your dimmer on?  3.8?.  Any-one still on 3.4 having issues as well?

**Comment by SwoopX** [comment]
3.4 seems to work. I recall that from Discord.

**Comment by incognit-o** [comment]
My dimmer is on 3.8.
![image](https://user-images.githubusercontent.com/65986845/112390212-514ab680-8ccc-11eb-8346-6ad91794cdd1.png)

**Comment by incognit-o** [comment]
I think this is what @SwoopX was referring to.
![image](https://user-images.githubusercontent.com/65986845/112396498-9f64b780-8cd6-11eb-9351-15f9a62f065c.png)

**Comment by NBradke** [comment]
I have now tested it in the last beta version (2.10.04). Here, too, I can integrate the switch (3.8), but not configure it.
![image](https://user-images.githubusercontent.com/57136538/112459217-e2b63900-8d5d-11eb-818f-0eb27bd83968.png)

The Lutron Aurora (3.8) is recognized. But it cannot be configured.
![image](https://user-images.githubusercontent.com/57136538/112459159-d3cf8680-8d5d-11eb-8002-6231429986b0.png)

**Comment by NBradke** [comment]
In version 3.4, however, it works without any problems.
![image](https://user-images.githubusercontent.com/57136538/112459531-39bc0e00-8d5e-11eb-8260-df4f88c1e4e3.png)

**Comment by ebaauw** [comment]
So it looks like something changed in the Aurora firmware, and the issues are not dependent on the deCONZ version.  I need again to sniff the pairing of the Aurora with the Hue bridge, to see if they do something different now for the new firmware.  No high hopes, though; never managed to get the Aurora to act with deCONZ as it does with the Hue bridge.

I’m afraid we don’t have a link to the 3.4 firmware, and if we do, we do, we still don’t know whether the Aurora allows OTA downgrading the firmware.  Still, could you post a screenshot of the. _OTAU_ cluster for the 3.4 firmware, making sure to have read each attribute?  Maybe we can deduce the firmware location.

**Comment by ebaauw** [comment]
Here's the log of pairing the Aurora running 3.8 with the Hue bridge:
[Pair_Lutron_Aurora_3_8_ to_Hue_Bridge.pcapng.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6237981/Pair_Lutron_Aurora_3_8_.to_Hue_Bridge.pcapng.zip)

**Comment by ebaauw** [comment]
I found the 3.4 firmware for the Aurora, see https://github.com/dresden-elektronik/deconz-ota-plugin.  I looks like the controller is happy to downgrade the firmware, if you select the file manually.  Currently installing; 2% in 2:20.

**Comment by NBradke** [comment]
I found time yesterday to deal with it. The downgrade to version 3.4 took about 1 hour.
Then I reconnected the two switches and was finally able to configure them. Thank you very, very, very much!!!
Tip: Note version 3.8 as incompatible, otherwise others will be in trouble.

**Comment by Mimiix** [comment]
> Tip: Note version 3.8 as incompatible, otherwise others will be in trouble.

Feel free to edit the wiki page yourself ;)

**Comment by SwoopX** [comment]
Closing this one as the solution is obviously to downgrade the firmware on the device 👍

**Comment by barryl93** [comment]
Sorry to reopen this, but this is the only place I've found that comes close to resolving my issue. I, too, have an Aurora with the 3.8 firmware. I understand I need to downgrade the firmware, but I can't seem to find instructions on how to do this. Can anyone point me in the right direction? Thanks!

**Comment by jorugit** [comment]
Thats a very bad solution! Downgrade to an older Version...

**Comment by pnewell** [comment]
I am attempting to downgrade the aurora to 3.4 but when I select a file in OTA Update and hit the Update button it just stays on Queued indefinitely and never actually updates. I have turned off the only other device on the network (a lightbulb). Any help would be appreciated.

Source Routing is disabled

deCONZ v2.19.3
Raspbian GNU/Linux Buster (10)
Raspbee 2 (26690700)

**Comment by ebaauw** [comment]
Make sure the Aurora is awake by pressing / turning it, while pressing _Update_.
