### ISSUE TITLE
DIYRuZ_Flower V2

### ISSUE THREAD

**Issue by ingo01978** [dresden-elektronik/deconz-rest-plugin#4624]
Hello, can you include this sensor. It is a self construction sensor for monitoring plants.
This sensor can measure soil moisture, temperature and brightness.
Here is the link to the original site:

## Device

Product name: DIYRuZ_FlowerV2
Manufacturer: modkam.ru
Model identifier: DIYRuZ_Flower
Device type : Sensor , Other

## Screenshots
![IMG_1702](https://user-images.githubusercontent.com/33171238/111909906-6ff84580-8a5f-11eb-92c1-2b035e6abdde.PNG)
![IMG_1703](https://user-images.githubusercontent.com/33171238/111909911-71c20900-8a5f-11eb-8b0d-ba638c5ced9c.PNG)
![IMG_1701](https://user-images.githubusercontent.com/33171238/111909913-72f33600-8a5f-11eb-83d7-3fd86240b2a8.PNG)
![IMG_1699](https://user-images.githubusercontent.com/33171238/111909914-738bcc80-8a5f-11eb-8a99-065b66b93369.PNG)

### Basic

https://modkam.ru/?p=1700
https://github.com/diyruz/flower

**Comment by Smanar** [comment]
Hu ? It s normal all cluster are OUT cluster and not IN cluster ?

**Comment by ingo01978** [comment]
Hello yes this is normal. The sensor does not send its values every 30 minutes and more. No settings can be made.

**Comment by ingo01978** [comment]
On the 4 picture you can see the value 0408 with unknown, that should be the soil moisture.

**Comment by Smanar** [comment]
But the problem is cluster need to be the reverse ? Look on other sensor.
It s like this device is able to receive temperature but not sending them.
