### ISSUE TITLE
Unable to pair 3 of 4 ZW25TQ

### ISSUE THREAD

**Issue by gmitch64** [dresden-elektronik/deconz-rest-plugin#4628]
## Describe the bug

I have 3 of the Zemismart ZM25TQ tubular motors. Only one of them will include, the other 3 will not. I did have 2 of them included with a previous version.

## Steps to reproduce the behavior

In Phoscon, search for a new light. On one of the tubular motors, it includes as _TYST11_wmcdj3aq - the other 3 will not include.

## Expected behavior

Expected behaviour is that the tubular motor should include.

## Screenshots

No screenshots. I can supply any that you need.

## Environment

deconz/unknown,now 2.10.03-raspbian-stretch-beta armhf [installed]
deconz-dev/unknown,now 2.10.03-raspbian-stretch-beta armhf [installed]

 - Host system: (Raspberry Pi)
 - Running method: (Raspbian)
 - Firmware version: (26390500)
 - deCONZ version: (2.10.03 / 3/14/2021)
 - Device: (RaspBee I)

## deCONZ Logs

Can supply any logs required.

**Comment by Mimiix** [comment]
As per template, can you add the requested logs? Aps2, error 2 info 2?

**Comment by Smanar** [comment]
They are battery device ? Or are represented as End device in deconz ?

**Comment by gmitch64** [comment]
These are mains powered devices.
I'll try and pull logs during the joining process later today. Anything specific that you want?

**Comment by Mimiix** [comment]
APS 2 , Error 2 and info 2 :)

**Comment by gmitch64** [comment]
Just ran deCONZ to do the debugging, and I'm getting an error that I need a device firmware update, which is odd, as I think I'm on the latest firmware.

![image](https://user-images.githubusercontent.com/27970644/112384307-9f5bbc00-8cc4-11eb-8a6c-5d2423705762.png)

**Comment by Smanar** [comment]
I think it can be usefull for you to make the try on a PC, to check if the problem is not from the conbee.

**Comment by gmitch64** [comment]
I have a RaspBee, so that's not an option unfortunately. 
I see that I have the environment wrong in the initial report. Sorry.

**Comment by gmitch64** [comment]
And a power off/on seems to have brought it somewhat back into life. Running deCONZ from ssh was giving me Qt errors, so I ran it from a VNC session, and now the only devices I'm seeing are these.

![image](https://user-images.githubusercontent.com/27970644/112386130-e185fd00-8cc6-11eb-92e4-022f9de0e54e.png)

**Comment by gmitch64** [comment]
Does this mean my database is dead? It's looking pretty dead from the webUI.
Does deCONZ make backups of the database anywhere?

**Comment by gmitch64** [comment]
OK. I'm still not sure what's going on, but when running in debug mode, the 2 motors connected. The 2nd one doesn't look right, as it's certainly not "fairy lights".

![image](https://user-images.githubusercontent.com/27970644/112389227-c5845a80-8cca-11eb-80d4-abf50fcc1ba6.png)

**Comment by gmitch64** [comment]
And finally the log files.

[M3.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6201210/M3.zip)

**Comment by gmitch64** [comment]
I took deCONZ out of debug mode, rebooted, and they now showed up as smart light 28 and smart plug 29. I'm not sure what is going on.

I also tried to add the 2 additional motors that weren't adding in before, and THEY have added too.

![image](https://user-images.githubusercontent.com/27970644/112403196-5ae01880-8ce4-11eb-8f9d-0a84a00f1168.png)

For On/Off light 28

![image](https://user-images.githubusercontent.com/27970644/112403249-74816000-8ce4-11eb-9d32-56cef656671c.png)

![image](https://user-images.githubusercontent.com/27970644/112403325-91b62e80-8ce4-11eb-80e3-a106cad77045.png)

Form Smart plug 29

![image](https://user-images.githubusercontent.com/27970644/112403446-cde98f00-8ce4-11eb-9eca-54b5cc4abe1d.png)

![image](https://user-images.githubusercontent.com/27970644/112403487-e194f580-8ce4-11eb-9348-c21e968cb709.png)

**Comment by Smanar** [comment]
Just for information you have a third app that try to connect to the API unsuccessfully.
>21:53:30:477 API error 1, /sensors/new, unauthorized user

Remember you need 2 inclusions for tuya device, and without deleting the first entry, to transform the plug entry in covering one.

**Comment by gmitch64** [comment]
Thanks for the info on the 3rd party app - I think I know what that is.

I didn't know about the double inclusion for the tuya device. Just to make sure that I did it right for these motors, since when I did it nothing changed...

Don't delete anything from Phoscon or the VNC console
Do a 3 press to get into inclusion mode
Search for new lights in Phoscon
Wait for things to happen

Did I do it right, or did I get it wrong? I've tried on all 4 motors, and nothing happens.

**Comment by gmitch64** [comment]
Just to update this, in case anyone finds it via search later.
The 2nd inclusion for any of the 3 missing tubular motors didn't work.

What DID work, was reading the basic cluster for each of the motors once they were included. This changed the device in the JSON to a window covering device, which is what they are.

**Comment by Smanar** [comment]
Oups sorry, have forget you.
Yep, the second trick work too, but in fact it s the same thing than making 2 inclusion, idk why it have not worked.
There is a weak ATM in deconz, it miss the manufacture name during inclusion. So the first inclusion create a plug device and memorise data, the second one can use the previous stored data to reconize the device and include it as covering.

It s for that, you need to not delete something.
