### ISSUE TITLE
SHP-13 Blitzwolf - No power consumption in Home Assistant

### ISSUE THREAD

**Issue by marithpl** [dresden-elektronik/deconz-rest-plugin#4629]
## Describe the bug
I connected 2 smart plugs Blitzwolf BW-SHP13 to Deconz.
It looks similar to #3788 where some of people have readings of power in Home Assistant and some of them not.

**Device:**
Blitzwolf BW-SHP13

**Phoscon App:**
Vendor_TZ3000_g5xawfcq

## Screenshots
<img width="389" alt="image" src="https://user-images.githubusercontent.com/25366097/112117227-697ee080-8bbb-11eb-9643-2dcf65bb19ab.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/25366097/112119921-18242080-8bbe-11eb-8ece-ce145695b7be.png">
<img width="593" alt="image" src="https://user-images.githubusercontent.com/25366097/112119974-23774c00-8bbe-11eb-93d8-541ae3fbe36f.png">

## Environment

 - Host system: NAS
 - Running method: Marthoc Docker container
 - Firmware version: 26660700
 - deCONZ version: 2.10.02 / 23.12.2020
 - Device: ConBee II
 - Do you use an USB extension cable: yes

**Comment by Mimiix** [comment]
I'll re-open that other one. I'll close this one.
