### ISSUE TITLE
Busch-Jaeger / Wall mounted transmitter 2-channel :: Can only assign scenes to one pair of buttons

### ISSUE THREAD

**Issue by erikproper** [dresden-elektronik/deconz-rest-plugin#463]
Guess the subject says most of it.
Have a Busch-Jaeger, wall mounted transmitter 2-channel. So,
that is the battery powered one. 
Firmware version 1.2.0 is.
In Phoscan, I can only assign scenes to the lower pair switches. 
The upper one only lets me switch on / off the assigned lights. 
Note: This is the battery powered one ...

**Comment by manup** [comment]
Yes that's a fixed setup, chosen to match the JUNG and GIRA switches which have this fixed setup by design.

We are currently working on a new switch editor in the Phoscon App where buttons can be assigned to a custom actions like calling a scene. But it will take a while till it's available.

**Comment by erikproper** [comment]
Okay! Good to know that there's nothing wrong with the switch then ;-)
Will await future updates ;-)

**Comment by Daniel0984** [comment]
This is same same fault i mentioned here: 368

**Comment by manup** [comment]
Hey guys for your interest here is a graphic mockup with a Busch-Jaeger 4-channel switch which shows how we imagine the editor (German).

[Tastenbelegung.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/1786097/Tastenbelegung.pdf)


Basically various actions can be assigned to a switch button. Also each button may address another target group.

Therefore for each button you can 
* select a target group
* select the action

There will be also some special actions like *activate next scene* to cycle through scenes of a group with just one button.

This should also address the issues mentioned in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/368

**Comment by Daniel0984** [comment]
That would be awesome! :thumbsup:

**Comment by erikproper** [comment]
Looks good!

**Comment by Wyphorn** [comment]
> Hey guys for your interest here is a graphic mockup with a Busch-Jaeger 4-channel switch which shows how we imagine the editor (German).
> 
> [Tastenbelegung.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/1786097/Tastenbelegung.pdf)
> 
> Basically various actions can be assigned to a switch button. Also each button may address another target group.
> 
> Therefore for each button you can
> 
> * select a target group
> * select the action
> 
> There will be also some special actions like _activate next scene_ to cycle through scenes of a group with just one button.
> 
> This should also address the issues mentioned in #368

Is there a release date for this?
