### ISSUE TITLE
Upgrade to 2.10.04 breaks OpenHab Communication

### ISSUE THREAD

**Issue by FrankH1** [dresden-elektronik/deconz-rest-plugin#4638]
## Describe the bug

 Hi,
running OpenHab 2 on a Raspi3 and have a Conbee II stick connected to it.
Tried to upgrade the deconz plugin from 2.05.74 to a more recent version 2.10.04 - as I got a few Sonoff devices, which were not supported by the old version. It breaks the connection to OpenHab - similar to previous versions see issue # 2563.
Went back to 2.05.74.
I thought its fixed?

Cheers
## Environment

 - Host system: Raspberry Pi 
 - Running method: Raspbian 
 - Firmware version: (2680700)
 - deCONZ version: (2.05.74 vs 2.10.04)
 - Device: ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
This appears to be an issue with OH, so please reach out to their community.
