### ISSUE TITLE
Conbee 2 after firmware update 26660700 lights are not manageable

### ISSUE THREAD

**Issue by ngok31** [dresden-elektronik/deconz-rest-plugin#4646]
## Describe the bug
After firmware update  26660700 DEconz Conbee 2 my lights are not manageable. In Home Assistant I can see them, switch on or off but nothing is working in reality. After a short time my light become unavailable.
I have updated the HA Deconz Integrtation to V 6.8.0.

## Steps to reproduce the behavior
Open HA or deconz none of my lights are working In the Deconz app or HA

## Expected behavior
Working lights as before the update.

## Environment

 - Host system: (Raspberry Pi 3B)
 - Running method: (ome Assistent deCONZ Add-on 
 - Firmware version: 26660700
 - deCONZ version: 2.10.04 14/03/2021
 - Device:  ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? Yes SSD with HA installed on it

## deCONZ Logs
10:05:43:639 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:05:44:473 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:05:45:383 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:05:46:360 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:05:47:256 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:05:48:111 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:05:49:011 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:05:49:952 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:05:50:920 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:05:51:812 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:05:52:750 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:05:53:614 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:05:54:482 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:05:55:453 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:05:56:336 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:05:57:139 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:05:58:060 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:05:58:941 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:05:59:804 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:00:715 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:01:589 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:02:446 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:03:233 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:04:036 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:04:844 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:05:710 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:06:695 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:07:611 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:08:469 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:09:449 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:09:744 Current channel 25
10:06:09:749 CTRL got nwk update id 0
10:06:09:754 Device TTL 1534 s flags: 0x7
10:06:10:307 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:11:180 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:11:936 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:12:770 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:13:536 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:14:418 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:15:308 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:16:132 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:16:941 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:17:813 0x7CB03EAA00AF4AA0 error APSDE-DAT172.30.32.2 - - [26/Mar/2021:10:06:50 +0100] "GET /ingress.html HTTP/1.1" 200 2018 "https://192.168.1.78:8123/core_deconz/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
A.confirm: 0xE1 on task
10:06:18:766 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:19:574 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:20:518 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:21:409 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:22:236 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:23:114 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:24:020 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:24:839 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:25:634 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:26:050 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:26:832 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:27:723 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:28:578 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:29:566 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:30:442 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:31:360 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:32:259 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:33:075 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:33:984 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:34:830 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:35:770 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:36:615 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:37:435 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:38:311 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:39:263 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:40:158 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:41:027 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:41:844 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:42:642 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:43:597 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:44:479 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:45:453 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:46:419 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:47:359 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:48:219 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:49:156 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:50:058 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:51:056 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:52:058 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:52:779 unknown node 0x00158D00045CAD24 (0x0728), lqi: 255
10:06:52:780 APS-DATA.indication from unknown node 0x00158D00045CAD24
10:06:52:781 [INFO] - No button handler for: lumi.sensor_switch, unicast to: 0x0000, endpoint: 0x01, cluster: BASIC (0x0000), command: 0x0A, payload: 02FF4C0600100121C40B21A813240100000000214D0B205E, zclSeq: 56
10:06:52:783 ZCL attribute report 0x00158D00045CAD24 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x1234 
10:06:52:784 0x00158D00045CAD24 extract Xiaomi special attribute 0xFF02
10:06:52:785 	64 on/off 1
10:06:52:785 	01 battery 3012 (0x0BC4)
10:06:52:786 	04 unknown 5032 (0x13A8)
10:06:52:787 	06 LQI (?) 4294967296 (0x0100000000)
10:06:52:787 	Struct index 05 unknown (counter?) 2893 (0x0B4D)
10:06:52:788 	Struct index 06 unknown (counter?) 94 (0x5E)
10:06:53:059 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:53:932 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:54:810 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task
10:06:55:636 0x7CB03EAA00AF7DB6 error APSDE-DATA.confirm: 0xE1 on task
10:06:55:981 0x7CB03EAA00AF3EEC error APSDE-DATA.confirm: 0xE1 on task
10:06:56:847 0x7CB03EAA00AF4AA0 error APSDE-DATA.confirm: 0xE1 on task

**Comment by Mimiix** [comment]
I suggest using a extension cable as 0xE1 is interference:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log
