### ISSUE TITLE
Mi Light Detection Sensor

### ISSUE THREAD

**Issue by goegsig** [dresden-elektronik/deconz-rest-plugin#4648]
## Device

- Product name: Mi Light Detection Sensor
- Manufacturer: XIAOMI
- Model identifier: lumi.sen_ill.mgl01
- Device type : 
  - Sensor
![IMG_7734](https://user-images.githubusercontent.com/7282538/112638283-6005aa80-8e3f-11eb-9dd6-10fd50b62ccb.jpg)
![IMG_7733](https://user-images.githubusercontent.com/7282538/112638288-61cf6e00-8e3f-11eb-9c76-68ce07227ab6.jpg)

### Basic
![billede](https://user-images.githubusercontent.com/7282538/112637706-b9b9a500-8e3e-11eb-9452-719d819c2b33.png)

### Identify
![billede](https://user-images.githubusercontent.com/7282538/112637756-c6d69400-8e3e-11eb-9aa6-21887b81b1ee.png)

### Power Configuration
![billede](https://user-images.githubusercontent.com/7282538/112638702-d1ddf400-8e3f-11eb-96fb-92bacd440d43.png)

### Other clusters that are not mentioned above
![billede](https://user-images.githubusercontent.com/7282538/112637798-d2c25600-8e3e-11eb-96ab-91e358cd2e31.png)
![billede](https://user-images.githubusercontent.com/7282538/112637839-dce45480-8e3e-11eb-9189-a4f22cfb325d.png)

Same type of issue. 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2300
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2380

**Comment by SwoopX** [comment]
Hi,

would you be able to compile and test an updated plugin version?

**Comment by goegsig** [comment]
At the moment iam using Home Assistent.  But if there is some guide i can follow i'am willing to try setting at virtual linux op and trying to compile and verify that it works.

**Comment by Finne75** [comment]
Three devices of this type did arrive today. What is a bit curious is that I see this device in the deCONZ GUI with measurements updated (after I did manual binding as recommended in #2380), but it is not visible in the REST API. I did a restart of the gateway, but no success. That means that I also cannot use the device in home assistant currently :/..

**Comment by Finne75** [comment]
@SwoopX success! Do you need any more details?

![image](https://user-images.githubusercontent.com/76888443/113411089-373c6280-93b5-11eb-8a57-ca02f60cf50d.png)

![image](https://user-images.githubusercontent.com/76888443/113411170-64891080-93b5-11eb-8672-ef23e7fdc7a7.png)

**Comment by johandijkstra** [comment]
Hi guys, I have the same sensor and issues stated here :)
How can I get the GZCGQ01LM to work in HA? :)

**Comment by sj3fk3** [comment]
> Hi guys, I have the same sensor and issues stated here :)
> How can I get the GZCGQ01LM to work in HA? :)

Wait a couple of days and it will be in the new version of deconz :-)
