### ISSUE TITLE
ELKO SmartDim Puck Uni 200W (puck dimmer)

### ISSUE THREAD

**Issue by andersop91** [dresden-elektronik/deconz-rest-plugin#4658]
## Device
- Product name: SmartDim puck Uni 200W
- Manufacturer: Schneider Electric
- Model identifier: PUCK/DIMMER/1
- Device type : 
  - Light (dimmer)

The unit works almost out of the box. Can pair it and control it in Phoscon App. It also shows up in Home Assistant.

User guide:
https://proff.elko.no/getfile.php/13158642/produkter/doc/EKO07090/Bruksanv.%20SmartDim%20Puck%202.pdf
Information:
https://elkosmart.elko.no/produkter/smartdim-puck-uni-200w
https://proff.elko.no/smartpuck/category2982.html

## Screenshots
![image](https://user-images.githubusercontent.com/57915164/112732783-4dbd6680-8f3c-11eb-8096-109ce9af23b2.png)

### Basic
![image](https://user-images.githubusercontent.com/57915164/112732810-7f363200-8f3c-11eb-8c50-1036a22df58c.png)

### Identify
![image](https://user-images.githubusercontent.com/57915164/112732815-865d4000-8f3c-11eb-9ab9-7d9f8eb7cc6d.png)

### Groups
![image](https://user-images.githubusercontent.com/57915164/112732823-97a64c80-8f3c-11eb-8c47-3de0e1c1194d.png)

### Scenes
![image](https://user-images.githubusercontent.com/57915164/112732830-a260e180-8f3c-11eb-9a19-f27702ad1f40.png)

### On/Off
![image](https://user-images.githubusercontent.com/57915164/112732843-b4db1b00-8f3c-11eb-94cf-4eddea1595a4.png)
![image](https://user-images.githubusercontent.com/57915164/112732845-b9073880-8f3c-11eb-91b4-1c90f1d0d04f.png)

### Level Control
![image](https://user-images.githubusercontent.com/57915164/112732851-c58b9100-8f3c-11eb-9545-77f27bf0796c.png)
![image](https://user-images.githubusercontent.com/57915164/112732856-ca504500-8f3c-11eb-98ff-6941ddbf5b2a.png)

### Ballast configuration
![image](https://user-images.githubusercontent.com/57915164/112732863-db995180-8f3c-11eb-8d62-5d2b8756931c.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/57915164/112732956-6bd79680-8f3d-11eb-9edf-a691a2be319e.png)

### OTAU
![image](https://user-images.githubusercontent.com/57915164/112732941-52364f00-8f3d-11eb-9fe1-d038ab46c80f.png)

**Comment by Smanar** [comment]
Hello
>The unit works almost out of the box

What is missing ?

**Comment by andersop91** [comment]
Configuration of ballast, and minimum/maximum dim level.

**Comment by Smanar** [comment]
I have read the doc, relay nice device, dimmer module without neutral.
But nothing about "ballast configuration" in the doc, are you sure it s something "made to be modified" ?
Have you tried to use the dimmer feature with deconz ? In cluster 0x0008, it don't work ? Or the device use the "ballast configuration" cluster to make variation ?
