### ISSUE TITLE
ELKO SmartRele Puck 10AX (smart relay)

### ISSUE THREAD

**Issue by andersop91** [dresden-elektronik/deconz-rest-plugin#4659]
## Device
- Product name: SMARTRELE PUCK 10AX
- Manufacturer: Schneider Electric
- Model identifier: PUCK/SWITCH/1
- Device type : 
  - Light 
 
This is a relay, controllable with an impulse switch. The unit works almost out of the box. Can pair it and control it in Phoscon App as a light. It also shows up in Home Assistant as a binary switch.

User Guide:
https://proff.elko.no/getfile.php/13158682/produkter/doc/EKO07144/Bruksanv.%20SmartRele%20Puck%202.pdf
Information:
https://elkosmart.elko.no/produkter/smartrele-puck-10ax
https://proff.elko.no/smartpuck/smartrele-puck-10ax-article3180-2982.html

## Screenshots
![image](https://user-images.githubusercontent.com/57915164/112733026-cf61c400-8f3d-11eb-891a-4d3408ba6be9.png)

### Basic
![image](https://user-images.githubusercontent.com/57915164/112733137-77778d00-8f3e-11eb-9b47-f791b145c8c8.png)

### Identify
![image](https://user-images.githubusercontent.com/57915164/112733139-7c3c4100-8f3e-11eb-84c9-e0d08466e1e5.png)

### Groups
![image](https://user-images.githubusercontent.com/57915164/112733152-85c5a900-8f3e-11eb-80ed-89a680149a73.png)

### Scenes
![image](https://user-images.githubusercontent.com/57915164/112733159-8eb67a80-8f3e-11eb-8951-10217b38237f.png)

### On/Off
![image](https://user-images.githubusercontent.com/57915164/112733166-9a09a600-8f3e-11eb-977d-f38eb930f5bb.png)
![image](https://user-images.githubusercontent.com/57915164/112733173-a130b400-8f3e-11eb-87c3-34ca8549e131.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/57915164/112733178-ad1c7600-8f3e-11eb-9200-f8d462172a98.png)

### OTAU
![image](https://user-images.githubusercontent.com/57915164/112733191-b60d4780-8f3e-11eb-9461-6585b125f3a3.png)

**Comment by jonmoerk** [comment]
Can this be reopened?
