### ISSUE TITLE
ZHAconsumption is not created with current version

### ISSUE THREAD

**Issue by stepman0** [dresden-elektronik/deconz-rest-plugin#4678]
## Describe the bug

I have deconz running with a conbee II. I already use two BitronVideo AV2010/25 smart plugs with metering in my system. Both report energy consumption and power to homeassistant.

Today, I added a third smart plug (same model - bought a 3 pack) and the energy meter function is not working. 

Looking in the rest api, I can see the sensor of type ZHAconsumption for both "old" plugs, but not for the new one.

Both "old" smart plugs were added about half a year ago, I do not know the exact time.

## Expected behavior

A sensor of type ZHAconsumption should be added (as done in an earlier version)
## Environment

 - Host system: VM on Proxmox running on Intel NUC
 - Running method: Marthoc Docker container
 - Firmware version: (26660700)
 - deCONZ version: (2.10.04)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by stepman0** [comment]
I just tested with version marthoc/deconz:amd64-2.05.88 and there it works. So it seems to be some kind a degradation

**Comment by SwoopX** [comment]
Can you please provide a screenshot of the node info panel from deconz GUI as well as a debug log with INFO and INFO_L2? Also, how did you pair the device?

**Comment by Mimiix** [comment]
Forwarded it to @manup earlier. Could be related to the reports of the SHP13 not creating files.
