### ISSUE TITLE
[Device Request] 511.344 Remote for RGB

### ISSUE THREAD

**Issue by BayaroX** [dresden-elektronik/deconz-rest-plugin#4689]
## Device

- Product name: Zigbee 3.0 Remote Mini for RGB (511.344)
- Manufacturer: Iluminize
- Model identifier: unknown (no X on my raspberry)
- Device type :
  - Remote
- Link: https://www.iluminize.com/de/shop/led-steuerung/hand-fernbedienungen/product/488-511-344-hand-fernbedienung-zigbee-rgbw-led-4z.html

## Screenshots

On my raspberry i have no X, so i could only deliver some logs/informations, if someone give me a hint where to find the needed informations.

Thanks in advance and kind regards,
Chris

**Comment by Mimiix** [comment]
Unfortunately, if you are not able to setup x or show screens I have to close this issue.

Follow this guide and open a new issue whenever you got screenshots.
