### ISSUE TITLE
Hue Motion Outdoor Sensor SML002 - how to update firmware?

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#4713]
## Describe the question or issue you are having

I've searched and cannot find the firmware download for March 11, 2019, Software version: 6.1.1.27575

I dont have a Hue Hub. Any help is appreciated!

## Screenshots
n/a

## Environment

 - Host system: PC
 - Running method: Homeseer
 - Firmware version: 26390500
 - deCONZ version: 2.10.04
 - Device: ConBee I
 - Do you use an USB extension cable:  no
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
n/a

## Additional context
blah, stupid template

**Comment by Mimiix** [comment]
Sadly, hue doesn't release their firmware files. That being said: we don't have them either.

**Comment by ebaauw** [comment]
What's the _Image Type_ for the outdoor motion sensor?  There's a good change it uses the same firmware as the (indoor, regular) motion sensor, 0x010d.  The link to that in on the repository for the OTAU plugin, https://github.com/dresden-elektronik/deconz-ota-plugin.
