### ISSUE TITLE
TUYA CURTAIN MOTOR

### ISSUE THREAD

**Issue by NMGAndy** [dresden-elektronik/deconz-rest-plugin#4723]
## Device

- Product name: TUYA CURTAIN MOTOR
- Manufacturer: _TZE200_zpzndjez
- Model identifier: TS0601
- Device type :  Window Covering 

Absolutely same motor as: 
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4288](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4288)

The only difference is Manufacturer (_TZE200_zpzndjez).

<img width="482" alt="Снимок экрана 2021-04-08 в 13 03 51" src="https://user-images.githubusercontent.com/1095547/113976665-a4e00700-986b-11eb-8c8f-95a50e886418.png">
<img width="496" alt="Снимок экрана 2021-04-08 в 13 05 05" src="https://user-images.githubusercontent.com/1095547/113976678-a7426100-986b-11eb-9502-fbef33c76d00.png">
<img width="499" alt="Снимок экрана 2021-04-09 в 16 18 48" src="https://user-images.githubusercontent.com/1095547/114159597-26a96080-9950-11eb-8a3b-8a719a1e755b.png">
<img width="495" alt="Снимок экрана 2021-04-09 в 16 19 07" src="https://user-images.githubusercontent.com/1095547/114159611-2a3ce780-9950-11eb-820b-bfc0416f88f3.png">
<img width="504" alt="Снимок экрана 2021-04-09 в 16 19 31" src="https://user-images.githubusercontent.com/1095547/114159615-2ad57e00-9950-11eb-9a29-237b2b65eb6f.png">
<img width="464" alt="Снимок экрана 2021-04-09 в 16 19 46" src="https://user-images.githubusercontent.com/1095547/114159621-2c06ab00-9950-11eb-9d57-bf79b28f7706.png">
<img width="459" alt="Снимок экрана 2021-04-09 в 16 19 58" src="https://user-images.githubusercontent.com/1095547/114159626-2d37d800-9950-11eb-8f4d-71851b612520.png">
<img width="425" alt="Снимок экрана 2021-04-09 в 16 20 33" src="https://user-images.githubusercontent.com/1095547/114159629-2dd06e80-9950-11eb-9156-46811f3c94c1.png">
<img width="438" alt="Снимок экрана 2021-04-09 в 16 20 49" src="https://user-images.githubusercontent.com/1095547/114159631-2f019b80-9950-11eb-85de-42e8695c0d24.png">
<img width="452" alt="Снимок экрана 2021-04-09 в 16 21 15" src="https://user-images.githubusercontent.com/1095547/114159633-2f019b80-9950-11eb-923b-89af6d157720.png">
<img width="465" alt="Снимок экрана 2021-04-09 в 16 21 34" src="https://user-images.githubusercontent.com/1095547/114159635-2f9a3200-9950-11eb-8fc0-40f1d7a776d9.png">

**Comment by Mimiix** [comment]
We need to have the clusters. They change stuff some times.

Please add all requested screenshots.

**Comment by gmitch64** [comment]
I'm having a similar issue with some Tuya Tubular motors - all are sold as ZM25TQ, but their basic clusters are showing differently.

I have 2 of these ZM25TQ motors which show as a model TS0601
![image](https://user-images.githubusercontent.com/27970644/113929801-75bf8c00-97be-11eb-8301-d0c3efa5f1be.png)

I also have 2 of these ZM25TQ motors which show as a model mcdj3aq
![image](https://user-images.githubusercontent.com/27970644/113929993-b919fa80-97be-11eb-9fed-386968c8825b.png)

I don't know if this is the same issue, or whether it's a separate Tuya weirdness....


Graham

**Comment by NMGAndy** [comment]
> We need to have the clusters. They change stuff some times.
> Please add all requested screenshots.

Added.

**Comment by Mimiix** [comment]
@NMGAndy Can you add _all_ clusters?

**Comment by Smanar** [comment]
_TZE200_zpzndjez is already in the code _TZE200_wmcdj3aq too.

Wich one deconz have you ?
Your devices are routers or End devices, missing on your captures.

**Comment by NMGAndy** [comment]
> _TZE200_zpzndjez is already in the code _TZE200_wmcdj3aq too.
> Wich one deconz version have you ?

<img width="599" alt="Снимок экрана 2021-04-08 в 23 16 29" src="https://user-images.githubusercontent.com/1095547/114061974-32017b00-98c1-11eb-9889-fa82a7199c28.png">
<img width="567" alt="Снимок экрана 2021-04-08 в 23 16 36" src="https://user-images.githubusercontent.com/1095547/114061979-3332a800-98c1-11eb-8d25-88ce8f6686c2.png">
<img width="313" alt="Снимок экрана 2021-04-08 в 23 16 54" src="https://user-images.githubusercontent.com/1095547/114061984-33cb3e80-98c1-11eb-8674-03b7db645f03.png">

_TZE200_zpzndjez is added as outlet and doesn't work.

> Your devices are routers or End devices, missing on your captures.

Routers.

**Comment by Smanar** [comment]
You need the version v2.10.5
The outlet is normal, we have some problem ATM to reconize tuya device, so we need 2 inclusions:

At first inclusion the device is reconized as outlet, and the code write data on the database.
On the second inclusion, the code use data to reconize it as covering.

**Comment by gmitch64** [comment]
> You need the version v2.10.5

Any idea when that's going to be available?
Or what do I need to pull down the code and compile it locally?


Graham

**Comment by gmitch64** [comment]
Here's the clusters for my ZM25TQ/_TYST11_wmcdj3aq after a double inclusion.

![image](https://user-images.githubusercontent.com/27970644/114114848-b3501200-98af-11eb-9a01-61ee0e0dac06.png)

![image](https://user-images.githubusercontent.com/27970644/114114878-c1059780-98af-11eb-829f-3fa6e79fa941.png)


![image](https://user-images.githubusercontent.com/27970644/114114915-d5499480-98af-11eb-83bc-020e57c99b68.png)


![image](https://user-images.githubusercontent.com/27970644/114114941-e4c8dd80-98af-11eb-9013-954d9561af76.png)

![image](https://user-images.githubusercontent.com/27970644/114114978-f3af9000-98af-11eb-8947-ef0c5506df10.png)

**Comment by gmitch64** [comment]
Here's the clusters for my ZM25TQ/_TZE200_wmcdj3aq after a double inclusion.

![image](https://user-images.githubusercontent.com/27970644/114115415-c7484380-98b0-11eb-83cc-68ebac66f8bd.png)


![image](https://user-images.githubusercontent.com/27970644/114115143-48530b00-98b0-11eb-9795-a32aff4c575c.png)


![image](https://user-images.githubusercontent.com/27970644/114115194-599c1780-98b0-11eb-9628-d06a4b5cfa2b.png)


![image](https://user-images.githubusercontent.com/27970644/114115232-67ea3380-98b0-11eb-9d5a-014b3ce08463.png)


![image](https://user-images.githubusercontent.com/27970644/114115354-ac75cf00-98b0-11eb-8577-4fdb54856130.png)

![image](https://user-images.githubusercontent.com/27970644/114115392-b992be00-98b0-11eb-8be3-e88e61743a9a.png)

**Comment by NMGAndy** [comment]
> @NMGAndy Can you add _all_ clusters?

Added all clusters.

**Comment by Mimiix** [comment]
> > You need the version v2.10.5
> 
> Any idea when that's going to be available?
> Or what do I need to pull down the code and compile it locally?
> 
> Graham

There isn't. Afaik it will be 2.11.0 as we have a stable on 2.10 already. 

Not sure when they release Wil be.

**Comment by gmitch64** [comment]
Ah. I was just going off Smanar comment about needing v2.10.5 earlier in the thread.

The release cadence says that the next beta should be on the 15th.

**Comment by Smanar** [comment]
Yep sorry ^^
I m using this page to know on wich one version the PR was merged https://github.com/dresden-elektronik/deconz-rest-plugin/releases
But it don't mean all versions are published.

**Comment by gmitch64** [comment]
>  if you have a linux machine with a real OS

You mean Windows isn't a real OS? :)

I have a Pi, and I've done some deCONZ compilations there in the past, so that's not an issue - I just need to know which git to use to pull the correct code down...

**Comment by Smanar** [comment]
lol
But on linux you can have light OS, totaly unusable.

You can use the official code, official branch, nothing, to change like https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
