### ISSUE TITLE
Phoscon password not working/reset fail, after update

### ISSUE THREAD

**Issue by BrianHarly** [dresden-elektronik/deconz-rest-plugin#4724]
## Environment

 - Host system: synology diskstation DS 916+
 - Running method: Marthoc Docker container
 - Firmware version: (not sure)
 - deCONZ version: 2.10.04
 - Device: ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
Without any logs, information or other description there's not much of a question. 

Closing.

**Comment by BrianHarly** [comment]
I did add logs..or so i thought...
