### ISSUE TITLE
Deconz /Conbee II problem after update

### ISSUE THREAD

**Issue by BrianHarly** [dresden-elektronik/deconz-rest-plugin#4725]
## Environment

 - Host system: NAS
 - Running method: Marthoc Docker container
 - Firmware version: (not sure)
 - deCONZ version: (2.10.04)
 - Device:  ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? no

**Comment by BrianHarly** [comment]
i have pasted screenshots and logs, but the dont show?

**Comment by Smanar** [comment]
lol, can use drag and drop to add them on the issue, a problem with the picture format ?
