### ISSUE TITLE
Wattle Door Lock Pro

### ISSUE THREAD

**Issue by cryzeck** [dresden-elektronik/deconz-rest-plugin#4726]
## Device

- Product name: Wattle Door Lock Pro
- Manufacturer: Home Control AS
- Model identifier: HC-SLM-1
- Device type : Please remove all unrelated device types. 
  - Lock

### Node Info
![image](https://user-images.githubusercontent.com/66617619/113912128-1754d680-97db-11eb-9cca-3705a23fdf27.png)
![image](https://user-images.githubusercontent.com/66617619/113912151-1cb22100-97db-11eb-8687-d9ee66c43c05.png)

### Basic
![image](https://user-images.githubusercontent.com/66617619/113912002-effe0980-97da-11eb-81e1-1503e7615b48.png)

### Lock
![image](https://user-images.githubusercontent.com/66617619/113912098-0c9a4180-97db-11eb-826e-eebbf56b5744.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/66617619/113912230-2b003d00-97db-11eb-9139-c8f8fa3ed2db.png)

### Groups
![image](https://user-images.githubusercontent.com/66617619/113912273-38b5c280-97db-11eb-9174-158ed7a8962d.png)

### Scenes
![image](https://user-images.githubusercontent.com/66617619/113912325-453a1b00-97db-11eb-81a5-ebf7c2fb1b31.png)

**Comment by Smanar** [comment]
For information, the device can be included and work, but it leave after some time.
If someone have information/idea about that ?
