### ISSUE TITLE
Terncy Smart Dial SD01

### ISSUE THREAD

**Issue by m1ke-hub** [dresden-elektronik/deconz-rest-plugin#4728]
## Device

- Product name: Terncy Smart Dial SD01
- Manufacturer: 0x1228
- Model identifier: TERNCY-SD01
- Device type :
  - (Wireless) Switch

https://www.terncy.com/en-us/smartdial/

![TERNCY-SD01](https://user-images.githubusercontent.com/57773976/113947001-f22b8c80-9809-11eb-910c-9f3b665f039c.jpg)

### Node

![node](https://user-images.githubusercontent.com/57773976/113947176-54848d00-980a-11eb-81d2-4804ec91e498.png)

### Basic

![basic_clusters](https://user-images.githubusercontent.com/57773976/113947074-269f4880-980a-11eb-871a-11df8070dbb7.png)

update:
![basic_new](https://user-images.githubusercontent.com/57773976/114033847-eaa5cb00-987d-11eb-95d5-e2cf254f6a20.png)

### Identify

![identify](https://user-images.githubusercontent.com/57773976/113947102-33bc3780-980a-11eb-92f3-403087d55846.png)

### Power configuration

![power_configuration](https://user-images.githubusercontent.com/57773976/113947212-6d8d3e00-980a-11eb-95a6-efac6a163d36.png)

### Poll control

![poll_control](https://user-images.githubusercontent.com/57773976/113947253-885fb280-980a-11eb-8b8d-7dd20918820d.png)

### OTAU

![otau_new](https://user-images.githubusercontent.com/57773976/114033775-d661ce00-987d-11eb-958e-346b01f76656.png)

-----------

Thank you very much in advance - I'd really appreciate if you could implement this device!

Please let me know if I forgot something and/or you need more information.

PS: I saw that there is already support in ZHA and Zigbee2MQTT, if that helps with the implementation.

**Comment by Mimiix** [comment]
Nice device!  Can you perhaps read the clusters prior screenshotting? Without the model id / manufacturer name it can't be added.

**Comment by migo-dev** [comment]
@Mimiix it is! 😃 
Please excuse my inexperience/ignorance, I never really used this view to check all those details and assumed it got filled, after I pressed read.

I hope this helps:

![basic_new](https://user-images.githubusercontent.com/57773976/114033143-4885e300-987d-11eb-828f-6eada0382dbc.png)
(the manufacturer name) stays empty and greyed out, no matter how often I press read and interact with the device - so I attached the below screenshot of the OTAU cluster, which contains the manufacturer id

![otau_new](https://user-images.githubusercontent.com/57773976/114033163-4b80d380-987d-11eb-874a-0b3fc734831f.png)

there are also some more information in this OTAU screenshot, compared to the one in my original post.

**Comment by migo-dev** [comment]
Bump

**Comment by eggertm** [comment]
I have the same device, and it seems that the manufacturer name is always grayed out. Is there some way to read that again?

**Comment by migo-dev** [comment]
@eggertm there is a 'read' button above the attributes, but I could not get it to be filled/not greyed out.

**Comment by m1ke-hub** [comment]
@Mimiix I saw you mentioning in another device request that some devs might be interested in getting a device sent to implement it. Unfortunately, I can't remember the thread nor the names of those devs - so I'd really appreciate it if you could ask/link them, if this interest is still applicable.

BTW, do you know whether they return the devices afterwards (shipping covered ofc) or keep them as a 'fee'? 😄

**Comment by Mimiix** [comment]
@SwoopX are you interested?

**Comment by eggertm** [comment]
Actually, due to logistics issues (shipment took more than 3 months to deliver), I have effectively received a free device.  If a dev wants one to implement, I'll be happy to donate one and pay for shipping (from Iceland).

**Comment by SwoopX** [comment]
Well, the most challenging part I see here is the missing manufacturer name. Would be interesting to see what the sniffer tells us.

So, if you're up to it, feel free to ping me on Discord. I'm happy to have a look at the device and figure something out.

**Comment by m1ke-hub** [comment]
Bump

May I take this opportunity to ask whether there is something to report yet? 😃

**Comment by SwoopX** [comment]
You mean except for lots of pain as it is horrible from a zigbee perspective? 🙃

I guess I'll have the code and the required instructions ready over the weekend.

**Comment by SwoopX** [comment]
So far so good...

![grafik](https://user-images.githubusercontent.com/4005212/121747774-338d3080-cb08-11eb-822b-bf4fe4503504.png)

**Comment by SwoopX** [comment]
Ok, I guess the work is finished. First, some technical observations:

- The device indeed has no attribute for manufacturer name (0x0004)
- It doesn't really support attribute reporting in the sense that any request for configuration gets a success, but is ignored in the end. Consequently, all reports are predefined by the device.
- On each button action, it either sends a cluster specific attribute report (0xfccc) or a manufacturer specific command (mfc: 1228, cluster 0xfccc)
- Almost all communication from the device to the coordinator goes to Endpoint 110, which requires some changes on the coordinator via deconz GUI to make it usable. This can currently lead to a conflict in case also Green Power devices are used (as the corresponding endpoint needs to be reconfigured)
- On a longer press, the device emits the command `0x14` with a payload incrementing each second (1 sec = 01, 2 sec = 02, etc.). However, after releasing the button, no additional command or report is sent which pretty much makes it impossible to leverage these.. Regardless, a long press for 1 sec will be available, but timing is key for the event to get generated.
- The numer of short presses is distinguishable from the 2nd byte of the corresponding command payload. The first byte is apparently a counter which hopefully resets to `00` after `FF` has been reached. In worst case, the payload length would increase to 3 resulting in a button event not being emitted anymore.

The device will have the following capabilities:

**Presses**
- Single (buttonevent `1002`), double(buttonevent `1004`), tripple (buttonevent `1005`) and quadruple (buttonevent `1006`) press
- long press for 1 second (timing is key, buttonevent `1003`)

**Rotation**
- One rotation tick clockwise will give a positive increase of state `angle` by 12, counter-clockwise a negative decrease of -12
- On a clockwise rotation, button event `1030` will be send, counter-clockwise `1031`
- For each rotation, the time in miliseconds is exposed as `eventduration`

**Comment by m1ke-hub** [comment]
Hey @SwoopX, please excuse my late reply. Since I'm using the Home Assistant add-on, I was unable to test the beta. Yesterday, the update was released and I could finally test the device - after changing the network settings as instructed above, everything worked perfectly!! Thank you so much for your work and detailed instructions!

**Comment by SwoopX** [comment]
Thanks for having sent it over. Enjoy!

**Comment by m1ke-hub** [comment]
Can't take credit for that. It was @eggertm
