### ISSUE TITLE
Firmware update from Phoscon fails

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#473]
Hi, 
I'm running deconz 2.05.08 for a ConBee attached to a Raspberry Pi 2. 
In Phoscon, it suggest a firmware update:

![image](https://user-images.githubusercontent.com/10351272/37304570-38766e8c-2632-11e8-828f-941dc01e84e2.png)

When I click the update button it apparently starts the update:

![image](https://user-images.githubusercontent.com/10351272/37304627-68265f34-2632-11e8-9f31-a2b0e5549a65.png)

After 10-15s (!) it finishes and says that the update is completed.
However, it shows the old firmware version and even a deconz version that I had never installed:

![image](https://user-images.githubusercontent.com/10351272/37304658-7df5c336-2632-11e8-97ab-f81314aa17eb.png)

After a while, the same firmware update is suggested again.

What is going wrong here?
Are firmware updates actually possible through phoscon?

In the log I can see this:

> 
> Mär 12 20:24:55 hassbian deCONZ[17488]: This plugin does not support propagateSizeHints()
> Mär 12 20:24:56 hassbian sudo[31894]:       pi : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/GCFFlasher_internal -d 0 -f /usr/share/deCONZ/firmware/deCONZ_Rpi_0x261e0500.bin.
> Mär 12 20:24:56 hassbian sudo[31894]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Mär 12 20:24:56 hassbian sudo[31894]: pam_unix(sudo:session): session closed for user root
>

**Comment by manup** [comment]
>What is going wrong here?

Is deCONZ running as root? The current implementation expects that it is running as normal user with sudo rights (like default user pi).

>Are firmware updates actually possible through phoscon?

Yes but as noted we test usually with the standard Raspbian distro and deCONZ installation and default user pi. For other variations we need to adapt the code to support these.

**Comment by ooii** [comment]
I have the same issue. 
I tried to run the app as root but same behavior as @jo-me.
Note that I'm running version 2.05.11 of 07/03/2018 under Ubuntu and not as the pi user.

**Comment by jo-me** [comment]
I'm running deconz on a hassbian (preconfigured debian/raspbian+ home assistant) installation. Installed it directly on the system. So, it was automatically set up as a systemd service.

The deconz.service file indicates that it is indeed running as pi user:
```
[Service]
User=pi
```

So.. based your assumptions it should've worked, right?

I noticed that there is no such "User" entry in deconz-update.service. Might not be relevant, though.

**Comment by manup** [comment]
Good catch, internally the firmware update should just start when one device is attached, however this seems to be a bit badly implemented since it only checks for USB devices with 0x6015 which fails in your case.

I'll put it on the todo list
