### ISSUE TITLE
legrand - Valena Next with Netatmo - connected wall plug

### ISSUE THREAD

**Issue by kvanisterdael** [dresden-elektronik/deconz-rest-plugin#4731]
## Device

- Product name: Valena Next with Netatmo - connected wall plug
- Manufacturer: Legrand
- Model identifier: Connected outlet
- Device type : Please remove all unrelated device types. 
  - Other: Outlet (plug)

## Screenshots
![afbeelding](https://user-images.githubusercontent.com/13382599/114028570-e925d400-9878-11eb-8c1b-cd54d8ad4641.png)

![afbeelding](https://user-images.githubusercontent.com/13382599/114028598-f216a580-9878-11eb-8787-e47301fad653.png)

### Basic
![afbeelding](https://user-images.githubusercontent.com/13382599/114028634-fe026780-9878-11eb-97da-8df570821887.png)

### Identify
![afbeelding](https://user-images.githubusercontent.com/13382599/114028683-0a86c000-9879-11eb-8d45-c3af8670faf2.png)

### On/Off
![afbeelding](https://user-images.githubusercontent.com/13382599/114028814-3013c980-9879-11eb-8c15-7e266cfb5e79.png)
![afbeelding](https://user-images.githubusercontent.com/13382599/114028851-386c0480-9879-11eb-8ceb-4b33ed0ea37a.png)

**Comment by Smanar** [comment]
This device work natively, bad included for you, the name is grayed in deconz.

**Comment by kvanisterdael** [comment]
I tried another time and I can confirm it works as expected.
