### ISSUE TITLE
legrand - Valena Next with Netatmo - Wireless switch

### ISSUE THREAD

**Issue by kvanisterdael** [dresden-elektronik/deconz-rest-plugin#4732]
## Device

- Product name: Valena Next with Netatmo - Wireless switch (ref. 741813)
- Manufacturer: Legrand
- Model identifier: Remote switch
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots
![afbeelding](https://user-images.githubusercontent.com/13382599/114036688-951eed80-9880-11eb-83a5-4b66026eb898.png)

![afbeelding](https://user-images.githubusercontent.com/13382599/114036736-9e0fbf00-9880-11eb-8131-6cf2c6663632.png)

### Basic
![afbeelding](https://user-images.githubusercontent.com/13382599/114036812-ac5ddb00-9880-11eb-995b-ebaba2c6d18b.png)

### Identify
![afbeelding](https://user-images.githubusercontent.com/13382599/114036862-b8499d00-9880-11eb-9ab3-1729a7dd06ae.png)

### Remark
The button is already recognized by Deconz, but clicking the top and the bottom of the switch results in the same buttonevent (1002).

**Comment by Smanar** [comment]
Hello, have answered here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4695#issuecomment-815886509
