### ISSUE TITLE
HY367RT Tuya Thermostat (_TZE200_cwnjrr72, TS0601)

### ISSUE THREAD

**Issue by katekyonni** [dresden-elektronik/deconz-rest-plugin#4737]
## Device

- Product name: HY367RT
- Manufacturer: _TZE200_cwnjrr72
- Model identifier: TS0601
- Device type :
  - Thermostat

## Screenshots

![vivaldi_2021-04-09_04-24-21](https://user-images.githubusercontent.com/12618582/114120252-68082480-98ec-11eb-917b-13891879a404.png)

![vivaldi_2021-04-09_04-29-41](https://user-images.githubusercontent.com/12618582/114120366-a271c180-98ec-11eb-849c-58bb556330e4.png)

### Basic
![vivaldi_2021-04-09_04-25-08](https://user-images.githubusercontent.com/12618582/114120017-047df700-98ec-11eb-97fa-63b589c317de.png)

### Groups
![vivaldi_2021-04-09_04-27-15](https://user-images.githubusercontent.com/12618582/114120312-85d58980-98ec-11eb-903e-c207dbb7767a.png)

### Scenes
![vivaldi_2021-04-09_04-26-38](https://user-images.githubusercontent.com/12618582/114120289-78b89a80-98ec-11eb-9dae-90c4a26f10e0.png)

Here is a listing of the device on Aliexpress: https://www.aliexpress.com/item/1005002225828787.html?spm=a2g0s.9042311.0.0.2e5c4c4dyb1U2D

I found this issue on the zigbee2mqtt Github where the device was added: https://github.com/Koenkk/zigbee2mqtt/issues/6873

I hope this is all you need, if not let me know.
Thank you!

**Comment by Mimiix** [comment]
Please use search next time. This is a duplicate.

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4675
