### ISSUE TITLE
Develco Motion Sensor Mini v140

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#4738]
There is a similar case for version 130 #1294, adding version 140 via Phoscon works. I use DeConz integrated to HomeSeeer automation. It for some reason create 4 motion devices. Because of this, it seems to be some missing config for device.

DeConz version 2.10.4 installed om windows server 2019

## Device

- Product name: Develco Motion Sensor Mini MOSZB-140 HW 2.1.0
- Manufacturer: Develco Products A/S
- Model identifier: MOSZB-140
- Device type : 
  - Sensor
  - Thermostat
  - Other: Lux, temp, motion

## Screenshots

![Screenshot 2021-04-09 at 08 50 45](https://user-images.githubusercontent.com/45151934/114140551-b3342e80-9910-11eb-8d69-80e119bc91bb.png)

![Screenshot 2021-04-09 at 08 47 03](https://user-images.githubusercontent.com/45151934/114140145-30ab6f00-9910-11eb-9952-482489a84f17.png)

This device hase multiple basic devices, see pictures over. 
Note that device name Develco Privat Profile, Devleco Utility shows as unknown.

![Screenshot 2021-04-09 at 08 57 34](https://user-images.githubusercontent.com/45151934/114141329-bc71cb00-9911-11eb-8acf-d5d4897675da.png)

### Other clusters that are not mentioned above

Phoscon:

![Screenshot 2021-04-09 at 08 52 47](https://user-images.githubusercontent.com/45151934/114140754-fbebe780-9910-11eb-9218-a40924f0ec6f.png)

![Screenshot 2021-04-09 at 08 53 11](https://user-images.githubusercontent.com/45151934/114140806-09a16d00-9911-11eb-9e21-65b2c9073dfb.png)

Note that I´m trying to make device act on motion, but phoscon does not react or react very slow.

HomeSeer devices:
![Screenshot 2021-04-09 at 08 54 11](https://user-images.githubusercontent.com/45151934/114140924-3190d080-9911-11eb-8459-30e03bf54579.png)

Please let me know if other screenshots or information is required :)

**Comment by SwoopX** [comment]
The device is already supported.
