### ISSUE TITLE
Unreachable devices not visible in REST api after restart

### ISSUE THREAD

**Issue by jonatanolofsson** [dresden-elektronik/deconz-rest-plugin#474]
Updating from 2.05.08 to 2.05.12 *, my unpowered lights no longer show in the REST API or in the web interface (not just marked unreachable). 

If they become unreachable later however, they show up as expected. Is this an error in the loading from the database?

 \* I have looked through the commits between the releases, and have not found anything that should cause this. This might very well have been the behaviour before, but that I havn't seen it before.

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/97

**Comment by manup** [comment]
Showing unpowered lights directly after deCONZ restart is on the todo list, there is a solution how to support that, but it will take a few weeks until there is time for that. Main problem is to not show ghost devices which weren't online for months/years, or even aren't part of the network anymore. Hence the database will be extended with a ttl counter or something like that.

**Comment by jonatanolofsson** [comment]
@manup Regarding not showing ghosts, is that desired behaviour? How would one even decide what is too old? The system I am developing is intentionally very static (i.e., dynamic discovery is a no, missing devices are an error), where any 'dynamic' behaviour to the backend has to be worked around/detected as an error, so I personally believe it should be up to the user to remove ghost devices manually. Also, it would save you from having to implement the logic and timeout.

**Comment by jnmarczi** [comment]
@jonatanolofsson +1

**Comment by jonatanolofsson** [comment]
@manup How is progress on this issue? Right now my software is crashing on restart because devices are missing.. =)
I suppose I _could_ fix my own software but... :D :D (j/k, I'm gonna fix that as well ^^ I do think this is a relevant issue though)

**Comment by jonatanolofsson** [comment]
Why not simply list all devices in the database?

**Comment by manup** [comment]
There are setups out there which run since 2013, with many "dead" lights in the database. I guess people would be confused too see lights again which weren't there for years.

In order to support the feature without surprises we need to take care to only show lights which are not from the stoneage. It sounds easier than it is since some refactoring is required to implement it well.

**Comment by tunip** [comment]
Hopefully the implementaion takes not to long. If you use deCONZ together with homebridge-hue, I cant restart my raspberry (deCONZ-gateway) until all my bulbs (19) in 8 rooms are powered on with the (good old) wallswtich. As a workaround I seperated the devices, Philips Hue lights connected to a Hue bridge V2 and the sensors connected to the deCONZ gateway. But the target would be only use one bridge/gateway for all devices which could be restarted in case of software-updates and still works after power outages.

**Comment by ebaauw** [comment]
Use a lightlist to delay hoembridge-hue initialisation, until all lights have been discovered, see https://github.com/ebaauw/homebridge-hue/issues/246.
