### ISSUE TITLE
ZBT-DIMController-D0800 (tint remote small)

### ISSUE THREAD

**Issue by gforums** [dresden-elektronik/deconz-rest-plugin#4742]
Dear all,

thanks in advance for helping me with the following remote, which doesn't seem to be supported in the phoscon app yet:

ZBT-DIMController-D0800 (tint remote small)

![Download](https://user-images.githubusercontent.com/82218762/114197647-d8499100-9952-11eb-94fc-d382a25a7b6b.jpg)

## Device

- Name: ZBT-DIMController-D0800
- Manufacturer: LDS
- Model identifier: ZBT-DIMController-D0800.
- Device type : Remote
  
## Screenshots
 
![no1](https://user-images.githubusercontent.com/82218762/114197652-d8499100-9952-11eb-9f91-c2bd2cacffa8.png)
![basic1](https://user-images.githubusercontent.com/82218762/114197645-d7b0fa80-9952-11eb-89ea-0e15fd64b43d.png)
![no2](https://user-images.githubusercontent.com/82218762/114197654-d8e22780-9952-11eb-8138-66df5bb7633a.png)
![no3](https://user-images.githubusercontent.com/82218762/114197656-d8e22780-9952-11eb-88a6-89e0a80c64e3.png)
![no4](https://user-images.githubusercontent.com/82218762/114197658-d97abe00-9952-11eb-8eae-0f85fd2e1cc5.png)
  
Again thank you!
Should there be missing anything, appreciate a short notice.

Best regards, Christian

**Comment by ebaauw** [comment]
Duplicate issue.  See #4134 for integration/support progress.
