### ISSUE TITLE
Ewelink switch ZigBee 7-32V Self Locking Module ZB-SW01 \ ZG001

### ISSUE THREAD

**Issue by samuele2723** [dresden-elektronik/deconz-rest-plugin#4743]
Ewelink ZB-SW01 (o ZG001 from paper information from the box)

[link to the product ](https://it.aliexpress.com/item/1005002358919462.html?srcSns=sns_Copy&spreadType=socialShare&bizType=ProductDetail&social_params=60047793806&aff_fcid=bd1e20a4776e42dc957e41544fb0e678-1617973207433-08227-_uiJrV3&tt=MG&aff_fsk=_uiJrV3&aff_platform=default&sk=_uiJrV3&aff_trace_key=bd1e20a4776e42dc957e41544fb0e678-1617973207433-08227-_uiJrV3&shareId=60047793806&businessType=ProductDetail&platform=AE&terminal_id=40c9159970ad43a5ba3a65ef6c517983)

- Product name: eWeLink switch ZigBee 7-32V Self Locking Module
- Manufacturer: eWeLink
- Model identifier: ZB-SW01
- Device type :
  - Switch

NOTE: the device pairs but is not controllable, also goes online-offline continuously. I am asking the vendor to replace or giving me support to understand if i have a defective device or is a behaviour due to the compatibility. 

On the device there are 2 lights, blue and red. The red blinking means "looking for network" the red stable means "paired". I have this red light going stable and blinking from time to time.
Blue light is related to RF control i have stable blue but i don't know how to switch or interact with that.

![IMG_6925](https://user-images.githubusercontent.com/66970905/114225451-9c262880-9972-11eb-9df1-3112dfdd6a62.PNG)

## Screenshots

<img width="393" alt="Schermata 25" src="https://user-images.githubusercontent.com/66970905/114209442-eac9c780-995e-11eb-9d6b-4d6a34724cee.png">
<img width="395" alt="Schermata 24" src="https://user-images.githubusercontent.com/66970905/114209475-f3ba9900-995e-11eb-98a5-d0907adbd62f.png">
<img width="394" alt="Schermata 23" src="https://user-images.githubusercontent.com/66970905/114209495-f7e6b680-995e-11eb-8277-e2cf44b19b92.png">
<img width="552" alt="Schermata 27" src="https://user-images.githubusercontent.com/66970905/114214354-801b8a80-9964-11eb-96d2-d1c3a83b4f47.png">

<img width="552" alt="Schermata 27" src="https://user-images.githubusercontent.com/66970905/114214328-785be600-9964-11eb-9bda-6a08256af11a.png">

**Comment by b2un0** [comment]
Duplicate #4642
