### ISSUE TITLE
TUYA Zigbee Smart Led Controller _TZ3000_qqjaziws 

### ISSUE THREAD

**Issue by vanarebane** [dresden-elektronik/deconz-rest-plugin#4750]
## Device

![image](https://user-images.githubusercontent.com/4301343/114300698-46649400-9aca-11eb-8c85-ce2efa9456fd.png)

- Product name: TUYA Zigbee Smart Led Controller for RGBCW Strip. RGB + Colour Temperature
- Manufacturer: _TZ3000_qqjaziws
- Model identifier: TS0505B
- Device type :
  - Light

## Screenshots

![image](https://user-images.githubusercontent.com/4301343/114299770-ca684d00-9ac5-11eb-9f49-c9b9d0417e0b.png)

### Basic
![image](https://user-images.githubusercontent.com/4301343/114299803-f4ba0a80-9ac5-11eb-9229-27b6842ee0b6.png)

### Identify
![image](https://user-images.githubusercontent.com/4301343/114299814-03a0bd00-9ac6-11eb-906f-f5daa8563cea.png)

### Groups
![image](https://user-images.githubusercontent.com/4301343/114299826-10bdac00-9ac6-11eb-833d-bfb07d21b2ce.png)

### Scenes
![image](https://user-images.githubusercontent.com/4301343/114299847-2632d600-9ac6-11eb-9358-aad1a9699208.png)

### On/Off
![image](https://user-images.githubusercontent.com/4301343/114299858-30ed6b00-9ac6-11eb-9b5e-fe6aaf616b8e.png)

### Level Control
![image](https://user-images.githubusercontent.com/4301343/114299883-4498d180-9ac6-11eb-99a5-258ae8562fee.png)

### Color Control
![image](https://user-images.githubusercontent.com/4301343/114300191-b3c2f580-9ac7-11eb-815e-3a14de2d4797.png)

### ZLL
![image](https://user-images.githubusercontent.com/4301343/114300204-c2a9a800-9ac7-11eb-9267-75b1f918df33.png)

### OTAU
![image](https://user-images.githubusercontent.com/4301343/114300219-cf2e0080-9ac7-11eb-9fb1-b0850ab725df.png)

### Time
(Empty)

**Comment by Smanar** [comment]
Hello, this device don't work natively ?

**Comment by vanarebane** [comment]
> Hello, this device don't work natively ?

Hi, This device does not show up in Phoscon when pairing, but device appears in deCONZ. Does not show up in Home Assistant (trough Rest API I guess)

**Comment by vanarebane** [comment]
Oh, it appeared as Extended Light after re-pairing another switch
