### ISSUE TITLE
Tuya ZigBee 3 Button Wireless _TZ3000_rrjr1q0u

### ISSUE THREAD

**Issue by vanarebane** [dresden-elektronik/deconz-rest-plugin#4751]
## Device

- Product name: Tuya ZigBee 3 Button Wireless 9 Scene Switch Push Button
- Manufacturer: _TZ3000_rrjr1q0u
- Model identifier: TS0043
- Device type : 
  - Switch

![image](https://user-images.githubusercontent.com/4301343/114302413-92670700-9ad1-11eb-9812-72a695ea0d9a.png)

## Screenshots

![image](https://user-images.githubusercontent.com/4301343/114302118-541d1800-9ad0-11eb-8142-02da48625aa2.png)

### Basic
![image](https://user-images.githubusercontent.com/4301343/114302146-76af3100-9ad0-11eb-8631-e00b63ca07c6.png)

### Time
![image](https://user-images.githubusercontent.com/4301343/114302162-862e7a00-9ad0-11eb-9f0c-66bdb54988a2.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/4301343/114302185-96def000-9ad0-11eb-9a99-28e237b53155.png)

### On/Off
![image](https://user-images.githubusercontent.com/4301343/114302198-a2321b80-9ad0-11eb-8e3e-66cbb154822a.png)

### OTAU
![image](https://user-images.githubusercontent.com/4301343/114302209-b2e29180-9ad0-11eb-8741-4c2477535fd0.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/4301343/114302226-c988e880-9ad0-11eb-9cc0-ce6ed660b65e.png)

### On/Off
![image](https://user-images.githubusercontent.com/4301343/114302255-dad1f500-9ad0-11eb-9218-7af20a3ad6de.png)

### Basic
![image](https://user-images.githubusercontent.com/4301343/114302266-ede4c500-9ad0-11eb-8513-1dc0267a5ab1.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/4301343/114302281-005efe80-9ad1-11eb-8602-8fa3b6101580.png)

### On/Off
![image](https://user-images.githubusercontent.com/4301343/114302293-1b317300-9ad1-11eb-9098-3b13054d8583.png)

**Comment by Smanar** [comment]
Hello do you have a linux machine to test code ? Else I think it will work, nothing special (except a typo in the "random" name.

**Comment by vanarebane** [comment]
Hi, I don't have Linux machine. I could find time to run a virtual Linux. Do you have any instructions for step-by-step on how to test?

**Comment by Smanar** [comment]
Sure.

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch tuya_33 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

Then re-include the device.
