### ISSUE TITLE
SONOFF SNZB-04 Re-Pairing?

### ISSUE THREAD

**Issue by majorsl** [dresden-elektronik/deconz-rest-plugin#4757]
## Describe the question or issue you are having

I am unsure if this is a bug report, me not doing something right, or just a quirk of the device. I have several of door/window sensors. When the battery dies, I'd expect to replace the battery and just have it show up again in Phoscon. However, almost always I end up have to re-pair or delete and re-add the sensor.

Does anyone have these and is this common, or is there something I'm missing after a battery replacement?

I have about an equal number of Centralite door/window sensors and just replacing a dead battery is good enough to get them going again without having to fiddle with pairing processes.

## Environment

 - Host system: Raspberry Pi
 - Running method: Marthoc Docker container
 - Firmware version: 26680700
 - deCONZ version: 2.09.03
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mschul** [comment]
I am facing the same problem as you. Also with the Sonoff Buttons SNZB-01.

**Comment by Mimiix** [comment]
Would be intresting to see some logs on when this happens

**Comment by SwoopX** [comment]
I doubt this is deconz related. Especially cheap devices do not seem to store the network configuration persistently in memory or seem to fail on the rejoin.

**Comment by majorsl** [comment]
Thanks all for the suggestions so far. I think it might be more related to the device specifically, although if I go in with VNC I can see it (or a representation of it) connected to the controller or the nearest node. It does seem to be "talking".

I am moving away from the SONOFF sensors in favor or Aqara which I have much better luck with.  I think the SONOFF ones are best used for Windows that aren't open/closed often so you get the longest life out of the battery once paired.  If I had it to do again, I wouldn't have purchased them at all.

**Comment by realflash** [comment]
Could someone comment on which logs you would want to see? Sometimes they seem to be OK, sometimes they require re-pairing.
