### ISSUE TITLE
No connection Paulmann LED Controller 500.47 in deconz 

### ISSUE THREAD

**Issue by nodefeet** [dresden-elektronik/deconz-rest-plugin#476]
Is it possible to connect a Paulmann 500.47 LED Controller  [in](https://www.amazon.de/Paulmann-Controller-Kunststoff-Schaltgerät-500-47/dp/B072QSCVS4) in Deconz? 

According to other issues other Paulmann Controllers seem to work but I can't connect this one.

**Comment by manup** [comment]
Yes it should work since RGBW bulbs from Paulmann already work too.
