### ISSUE TITLE
Tuya Multisensor still not visible in Deconz (shows up in Phoscon and HA)

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/deconz-rest-plugin#4760]
## Describe the bug

I have two Heiman Multipurpose sensor's added to the environment. At first they were added some time ago, and showed up nicely in Phoscon. Then I had to readd one to the zigbee, and then it doesn't show up in Deconz, though it does show in Phoscon. It still showed the old one with the right name and all.
With the later version, it now doesn't show the 'old' multisensor either.

## Steps to reproduce the behavior

1. Get a [Tuya Multisensor](https://www.aliexpress.com/item/4000830582090.html?spm=a2g0s.9042311.0.0.27424c4d6mJ2X1)
2. Add it as zigbee device
3. It shows up in Deconz and Home Assistant
4. It does NOT show in Phoscon.

## Expected behavior

It should show up in Phoscon so it can be renamed and managed there.

## Screenshots

![image](https://user-images.githubusercontent.com/13660621/114453467-d7766080-9bd9-11eb-918f-882a06693918.png)
![image](https://user-images.githubusercontent.com/13660621/114454380-d98cef00-9bda-11eb-9b42-2fdbe276ddb4.png)
![image](https://user-images.githubusercontent.com/13660621/114454431-e578b100-9bda-11eb-8bff-9aae61e4d8a3.png)
![image](https://user-images.githubusercontent.com/13660621/114454456-ef021900-9bda-11eb-8a12-d59ccec4b313.png)
![image](https://user-images.githubusercontent.com/13660621/114454491-f75a5400-9bda-11eb-9a0b-61a9bbf83b86.png)

## Environment

 - Host system: NUC with PVE
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26670700)
 - deCONZ version: (2.10.04)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? Yes, AEOTEC Z-wave stick

## Additional context

I also tried the phoscon beta, no change.

**Comment by Smanar** [comment]
>It shows up in Phoscon and Home Assistant
>It does NOT show in Deconz.
>It should show up in Phoscon so it can be renamed and managed there.

And your capture show it in deconz ....

There is no mistake ?

**Comment by fribse** [comment]
I corrected it, sorry! Running a fever here :-( (not covid)

**Comment by SwoopX** [comment]
This is (again) not a Xiaomi device...

**Comment by fribse** [comment]
Arh, this is all bad, sorry, shouldn't be doing this when I'm this sick...

**Comment by Mimiix** [comment]
Take care!
