### ISSUE TITLE
Sengled Smart Light Bulb E21-N1EA

### ISSUE THREAD

**Issue by deviantintegral** [dresden-elektronik/deconz-rest-plugin#4767]
## Device

- Product name: Sengled Smart Light Bulb: https://www.amazon.ca/gp/product/B0899LJHVV/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
- Manufacturer: sengled
- Model identifier: E21-N1EA
- Device type :
  - Light

### Basic

<img width="472" alt="Screen Shot 2021-04-14 at 12 50 49 PM" src="https://user-images.githubusercontent.com/255023/114748552-0b5b9e00-9d20-11eb-8ded-839d433ab2b8.png">

### Identify

<img width="473" alt="Screen Shot 2021-04-14 at 12 51 04 PM" src="https://user-images.githubusercontent.com/255023/114748594-144c6f80-9d20-11eb-800c-36c860d633e7.png">

### Groups

<img width="480" alt="Screen Shot 2021-04-14 at 12 51 44 PM" src="https://user-images.githubusercontent.com/255023/114748711-2cbc8a00-9d20-11eb-958a-4f08db8ec39a.png">

<img width="477" alt="Screen Shot 2021-04-14 at 12 52 13 PM" src="https://user-images.githubusercontent.com/255023/114748777-3cd46980-9d20-11eb-84fa-76410ed1596e.png">

### Scenes

<img width="474" alt="Screen Shot 2021-04-14 at 12 52 30 PM" src="https://user-images.githubusercontent.com/255023/114748821-478efe80-9d20-11eb-9088-57243967b884.png">
<img width="475" alt="Screen Shot 2021-04-14 at 12 52 48 PM" src="https://user-images.githubusercontent.com/255023/114748860-52499380-9d20-11eb-8fa7-fa95ed62bd09.png">

<img width="467" alt="Screen Shot 2021-04-14 at 12 53 12 PM" src="https://user-images.githubusercontent.com/255023/114748916-5fff1900-9d20-11eb-97b1-22c77e7a8f91.png">

### On/Off

<img width="555" alt="Screen Shot 2021-04-14 at 12 53 29 PM" src="https://user-images.githubusercontent.com/255023/114748955-6ab9ae00-9d20-11eb-80af-8fb6a2ec2d52.png">

<img width="544" alt="Screen Shot 2021-04-14 at 12 53 45 PM" src="https://user-images.githubusercontent.com/255023/114748985-74431600-9d20-11eb-8546-7904ec40536c.png">

### Level Control

<img width="554" alt="Screen Shot 2021-04-14 at 12 54 04 PM" src="https://user-images.githubusercontent.com/255023/114749029-7efdab00-9d20-11eb-9c99-a974bc588bb6.png">
<img width="551" alt="Screen Shot 2021-04-14 at 12 54 38 PM" src="https://user-images.githubusercontent.com/255023/114749114-93da3e80-9d20-11eb-95d1-984d81c5cf57.png">

### Color Control

<img width="552" alt="Screen Shot 2021-04-14 at 12 55 21 PM" src="https://user-images.githubusercontent.com/255023/114749199-ad7b8600-9d20-11eb-8fa0-dec6d761f151.png">
<img width="547" alt="Screen Shot 2021-04-14 at 12 55 43 PM" src="https://user-images.githubusercontent.com/255023/114749243-b9ffde80-9d20-11eb-8a12-00d40cc36b42.png">
<img width="548" alt="Screen Shot 2021-04-14 at 12 56 02 PM" src="https://user-images.githubusercontent.com/255023/114749273-c5eba080-9d20-11eb-9069-d8efc9dbc0db.png">
<img width="545" alt="Screen Shot 2021-04-14 at 12 56 20 PM" src="https://user-images.githubusercontent.com/255023/114749310-d00d9f00-9d20-11eb-97b2-57f5bf2bc4f1.png">
<img width="543" alt="Screen Shot 2021-04-14 at 12 56 37 PM" src="https://user-images.githubusercontent.com/255023/114749346-dac83400-9d20-11eb-8a5a-9cc91b284852.png">
<img width="525" alt="Screen Shot 2021-04-14 at 12 56 53 PM" src="https://user-images.githubusercontent.com/255023/114749374-e4519c00-9d20-11eb-8408-9f47ff3ca227.png">
<img width="532" alt="Screen Shot 2021-04-14 at 12 57 30 PM" src="https://user-images.githubusercontent.com/255023/114749471-f9c6c600-9d20-11eb-90dd-23427f7e510a.png">
<img width="524" alt="Screen Shot 2021-04-14 at 12 57 47 PM" src="https://user-images.githubusercontent.com/255023/114749512-04815b00-9d21-11eb-8eef-434986991cea.png">
<img width="525" alt="Screen Shot 2021-04-14 at 12 57 59 PM" src="https://user-images.githubusercontent.com/255023/114749555-0b0fd280-9d21-11eb-94f1-ec43520416f7.png">
<img width="527" alt="Screen Shot 2021-04-14 at 12 58 07 PM" src="https://user-images.githubusercontent.com/255023/114749578-0fd48680-9d21-11eb-8b87-b50d2a30aa25.png">

### Simple Metering
<img width="562" alt="Screen Shot 2021-04-14 at 12 58 49 PM" src="https://user-images.githubusercontent.com/255023/114749659-28dd3780-9d21-11eb-91c5-6f40f72838ae.png">

### Diagnostics

<img width="557" alt="Screen Shot 2021-04-14 at 12 59 04 PM" src="https://user-images.githubusercontent.com/255023/114749699-32669f80-9d21-11eb-8452-877fe25b9a9b.png">

**Comment by deviantintegral** [comment]
For anyone with these bulbs; they somewhat work, but the colour control isn't totally accurate for all colour modes. HSV in particular gives you wrong colours.

**Comment by deviantintegral** [comment]
_bump_

However, since posting this I switched my home setup over to ZHA. I have another install that is using deconz, but my access to it is sporadic so testing may be tricky.

**Comment by mxracer95** [comment]
Re-Requesting support for this bulb. It is recognized as a color dimmable light rather than an extended color light.

**Comment by Mimiix** [comment]
Sure reopening

**Comment by mxracer95** [comment]
Bumping this request since reopening.

**Comment by gizmotronic** [comment]
I just bought a handful of these and have the same problem. [Manually setting the color temperature](/dresden-elektronik/deconz-rest-plugin/issues/4833#issuecomment-894372699) through the API works as expected, even though this is a different model.

**Comment by mxracer95** [comment]
I did create a DDF for this using my best understanding on how to do it. It seems to make the bulb work properly in Phoscon but then it doesn't get the RGB options over into Homeseer (via Jowihue plugin) I only get ColorTemperature. I bought a Philips Hue White and Color Ambiance bulb to test and both RGB and CT are read into Homeseer so I still think the issue is with deConz.

Here's my DDF for the Sengled E21-N1EA:

{
  "schema": "devcap1.schema.json",
  "manufacturername": "sengled",
  "modelid": "E21-N1EA",
  "vendor": "sengled",
  "product": "Smart LED E21-N1EA",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/E21-N1EA.json",
  "subdevices": [
    {
      "type": "$TYPE_COLOR_TEMPERATURE_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/colorcapabilities",
          "refresh.interval": 84000,
          "default": 16
        },
        {
          "name": "config/ctmax",
          "refresh.interval": 84000,
          "default": 455
        },
        {
          "name": "config/ctmin",
          "refresh.interval": 84000,
          "default": 200
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/bri",
          "refresh.interval": 5
        },
        {
          "name": "state/colormode",
          "refresh.interval": 300
        },
        {
          "name": "state/ct",
          "refresh.interval": 5
        },
        {
          "name": "state/effect",
          "default": "none"
        },
        {
          "name": "state/hue"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "state/sat",
          "refresh.interval": 5
        },
        {
          "name": "state/x",
          "refresh.interval": 5,
          "read": {
            "at": "0x0003",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl"
          }
        },
        {
          "name": "state/y",
          "read": {
            "at": "0x0004",
            "cl": "0x0300",
            "ep": 255,
            "fn": "zcl"
          }
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0008",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x20",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0300",
      "report": [
        {
          "at": "0x0007",
          "dt": "0x21",
          "min": 154,
          "max": 500,
          "change": "0x00000001"
        },
        {
          "at": "0x0003",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        },
        {
          "at": "0x0004",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        },
        {
          "at": "0x0008",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    }
  ]
}

**Comment by gizmotronic** [comment]
I added this DDF, reset my bulb, re-paired it, and verified that it was properly recognized. It seems to work properly using the Phoscon sliders. However, when exposed to HomeKit via homebridge-deconz, my bulb reverts to RBG whether I set RGB or color temperature values.

**Comment by Mimiix** [comment]
@gizmotronic  Good to see some progress! That seems to be a issue in Homebrdige, because Phoscon uses the same API as Homebridge does.

**Comment by mxracer95** [comment]
To update, the DDF I posted a few comments up does seem to work. In Homeseer using the JowiHue plugin (v4.0.8.3), the plugin doesn't properly import all the settings so custom settings had to be created in the JowiHueImports.xml file. For anyone looking, I created a post on the Homeseer forums which you can find by searching for the bulb model in HS4, Plugins, JowiHue.

**Comment by BabaIsYou** [comment]
If the DDF seems to be fine, may be you could open a Pull Request (PR) to have it included into a next release ?
