### ISSUE TITLE
Gateway on channel 0 and cannot change it

### ISSUE THREAD

**Issue by ooii** [dresden-elektronik/deconz-rest-plugin#477]
Hi,

My gateway is on channel 0 and I cannot change it to any other channel. I use the webapp advanced settings to select another channel then hit "Apply". Despite the message "OK! Configuration updated", I still have "Your gateway is on channel 0 and has the network Id 0x0000".
Therefore, it cannot find any of my lights.

**Comment by manup** [comment]
Can you provide more details on you setup: RaspBee or ConBee, operating system?
Channel 0 and network 0x0000 means not connected at all, so it seems installation is not complete.

**Comment by ooii** [comment]
I'm running deCONZ under Ubuntu and I'm using a ConBee USB Gateway.

**Comment by manup** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/94

**Comment by ooii** [comment]
> Channel 0 and network 0x0000 means not connected at all, so it seems installation is not complete.
It used to work then stopped. 
Any idea what reason can make the installation not complete now?

**Comment by manup** [comment]
Hard to tell, do you have other FTDI based USB devices connected?

Perhaps debug logs shed some light, start deCONZ via:

    deCONZ --dbg-info=1 --dbg-error=1 --http-port=80 -platform minimal

(stop the deconz service first)

**Comment by ooii** [comment]
I have another one, RFXtrx433 transmitter, which I stopped using during the firmware upgrade.
I'll test later and keep you informed.
Thanks again.

**Comment by ooii** [comment]
The problem comes from another instance (investigating how it has started) of deConz which makes the gateway unavailable for the service I was running.
I can close this issue. Thanks for your help.
