### ISSUE TITLE
MEGOS Smart Home remote

### ISSUE THREAD

**Issue by Jonas-wav** [dresden-elektronik/deconz-rest-plugin#4791]
## Device

- Product name: MEGOS Smart Home remote
  - https://www.megos-light.com/eng/led-assortment/ "LED STARTER SET"
- Manufacturer: _TZ3000_ztrfrcsu
- Model identifier: TS1001
- Device type :
  - Remote
  - Switch
  - (Light)

![IMG_4215](https://user-images.githubusercontent.com/49440861/115618888-8c540000-a2f3-11eb-92a7-74949a8d7e5f.jpeg)

## Screenshots

![Bildschirmfoto 2021-04-21 um 19 44 35](https://user-images.githubusercontent.com/49440861/115619271-f4a2e180-a2f3-11eb-8435-2144c2b05412.png)

### Basic
![basic](https://user-images.githubusercontent.com/49440861/115689254-30719180-a35c-11eb-93a1-93d1394de76a.png)

### Identify
![identify](https://user-images.githubusercontent.com/49440861/115738997-d984b000-a38d-11eb-8df5-23384dfa0776.png)

### Groups
![group](https://user-images.githubusercontent.com/49440861/115739098-eb665300-a38d-11eb-804d-166d16c350c0.png)

### Scenes
![Scenes](https://user-images.githubusercontent.com/49440861/115742514-04bcce80-a391-11eb-9baa-a72b4609a6c5.png)

### Other clusters that are not mentioned above
power configuratoin
![power configuration](https://user-images.githubusercontent.com/49440861/115689602-86463980-a35c-11eb-8157-ee4af766a533.png)

OTAU
![OTAU Cl](https://user-images.githubusercontent.com/49440861/115689944-dd4c0e80-a35c-11eb-963f-6b0f49da7660.png)

scenes
![Scenes](https://user-images.githubusercontent.com/49440861/115742719-40579880-a391-11eb-8013-f7245c605963.png)

ZLL Commissioning
![ZLL commissioning](https://user-images.githubusercontent.com/49440861/115742805-55342c00-a391-11eb-833c-cdfa7cf721ce.png)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by Jonas-wav** [comment]
Sorry, so far I didn't know where to find the other information, and I also thought that this would be sufficient, as shown in the [example](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support). :) 
That's all I've found so far, hope it's what you need.

**Comment by Mimiix** [comment]
Hi,

Screenshots of Identity and Groups clusters are still missing.

Kind regards,

**Comment by Jonas-wav** [comment]
I'm sorry, but I think you need to clarify [there](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support) which screenshots are really needed ("You can typically spare indentify...").

**Comment by Mimiix** [comment]
Further clusters. Meaning  all clusters.

**Comment by Jonas-wav** [comment]
Is it still incomplete?

**Comment by Mimiix** [comment]
Seems fine to me :)
