### ISSUE TITLE
Support for Aqara Wall switch QBKG04LM

### ISSUE THREAD

**Issue by KingTomaHawk** [dresden-elektronik/deconz-rest-plugin#480]
Hi,

I bought two of the Aqara Single key Wall switches (QBKG04LM) and successfully paired them with deconz, but the device name is shown as 0x0000 and there is no enty in the REST Api. 
Am I doing something wrong, because the Aqara Wall Switches are listed as supported with deconz?

Thanks

**Comment by KingTomaHawk** [comment]
Can somebody confirm if the wall switch is supported or not? 
If not, I found someone who seems to have successfuly implemented the wall switch to deconz:

https://github.com/zydeco/deconz-rest-plugin/commit/4d79ea0d08fbd1a32022f033b6fb216a73b7a1d8

**Comment by manup** [comment]
Can you post a screenshot of the basic cluster after the switch joins, we need to verify the modelid is registered.

Note to add the switch please start sensor search in Phoscon App then reset the switch.

**Comment by KingTomaHawk** [comment]
![screen](https://user-images.githubusercontent.com/36895999/37566646-63f4000e-2abc-11e8-98d5-2b7f44e9026a.PNG)
Sorry for the late reply. It seems like some update broke my AP feature so it took a little bit longer then expected.

**Comment by manup** [comment]
Hmm the lumi.ctrl_neutral1 should be supported and visible in the REST-API (added while sensor search is active), can you please double check that it isn't there?

**Comment by KingTomaHawk** [comment]
I can not find it on /api/<apikey>/sensors      :(

**Comment by tomfritz1** [comment]
I have the same issue - the switch is added in WebApp but not to Rest-API - neither as Sensor nor as light.

**Comment by KingTomaHawk** [comment]
I reseted yesterday my deconz and my Pi to test if there was something wrong with my configuration, but it still doesn't list the wall switch in REST Api.

**Comment by KingTomaHawk** [comment]
Any updates on this issue?

**Comment by KingTomaHawk** [comment]
FYI: I updated to the new "latest-deconz-beta" build, and noticed that the wall switch is now listed as a light! But, I think it also created 3 other "lights" in phoscon without any function.

**Comment by ebaauw** [comment]
See #356.  Could you please post the light resources there.  Which one does work?  And check whether any sensor resources where created?  Thanks.

**Comment by lenisko** [comment]
Hey there!

Can this device get somehow moved to `Switch` section?
It's Xiaomi `QBKG04LM` Aqara Wall Switch / one key version / can act as router.


![2019-04-30_21-28-56-tvnviewer](https://user-images.githubusercontent.com/10072920/56987939-15b21b00-6b8f-11e9-9584-46a973bdf94c.png)
