### ISSUE TITLE
LK Wiser Temperature / Humidity Sensor

### ISSUE THREAD

**Issue by jonmoerk** [dresden-elektronik/deconz-rest-plugin#4801]
## Device

- Product name: LK Wiser Temperature and Humidity Sensor
- Manufacturer: Schneider Electric
- Model identifier: CCT593011_AS
- Device type :
  - Sensor

[https://www.lk.dk/produkter?iid=13905](https://www.lk.dk/produkter?iid=13905)
[https://zigbeealliance.org/zigbee_products/wiser-temperature-and-humidity-sensor/](https://zigbeealliance.org/zigbee_products/wiser-temperature-and-humidity-sensor/)

This device is the same product line as:
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4534](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4534)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4800](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4800)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4816](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4816)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4817](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4817)

## Screenshots
![Node info](https://user-images.githubusercontent.com/80209954/115919872-b59e9880-a479-11eb-9bd9-2f79353badeb.PNG)

### Basic
![Basic](https://user-images.githubusercontent.com/80209954/115919880-b8998900-a479-11eb-9f2d-6fd4bd6d4ae2.PNG)

### Identify
![Identity](https://user-images.githubusercontent.com/80209954/115919897-bcc5a680-a479-11eb-8efc-bebe4a4f6a49.PNG)

### Diagnostics
![Diagnostic](https://user-images.githubusercontent.com/80209954/115919953-d0710d00-a479-11eb-9407-49b22e233777.PNG)
### Other clusters that are not mentioned above
![Hum](https://user-images.githubusercontent.com/80209954/115919985-de269280-a479-11eb-95ea-7acfec34c52f.PNG)
![Poll Control](https://user-images.githubusercontent.com/80209954/115919987-debf2900-a479-11eb-89e9-a91332eeeaa1.PNG)
![Power](https://user-images.githubusercontent.com/80209954/115919988-debf2900-a479-11eb-8fe2-38089494ef3f.PNG)
![Temp](https://user-images.githubusercontent.com/80209954/115919990-df57bf80-a479-11eb-956f-f0afa24ef237.PNG)

**Comment by Ozzee** [comment]
Does this work for anyone else? I have the sensor but it won't pair properly in the Phoscon webapp. I think a humidity sensor is created from it as something shows up in the deconz app, but the webapp never shows the sensor as having been found.
