### ISSUE TITLE
LK Wiser Door Window Sensor

### ISSUE THREAD

**Issue by jonmoerk** [dresden-elektronik/deconz-rest-plugin#4816]
## Device

- Product name: LK Wiser Door / Window Sensor
- Manufacturer: Schneider Electric
- Model identifier: CCT591011_AS
- Device type : 
  - Sensor

[https://www.lk.dk/produkter/?iid=550B1023](https://www.lk.dk/produkter/?iid=550B1023)

Aditional info:
[https://zigbeealliance.org/da/zigbee_products/klokere-vinduesd%C3%B8rsensor/](https://zigbeealliance.org/da/zigbee_products/klokere-vinduesd%C3%B8rsensor/)

This device is the same product line as:
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4534](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4534)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4800](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4800)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4817](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4817)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4801](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4801)

## Screenshots
![Node info](https://user-images.githubusercontent.com/80209954/116184781-b86ee700-a720-11eb-8229-8d391a3cb8ff.PNG)
![node](https://user-images.githubusercontent.com/80209954/116184797-befd5e80-a720-11eb-9345-9dc54ee7ff4a.PNG)

### Basic
![Cluster info - basic](https://user-images.githubusercontent.com/80209954/116184803-c1f84f00-a720-11eb-8c51-740ef8165b5d.PNG)

### Identify
![Cluster info - Identity](https://user-images.githubusercontent.com/80209954/116184824-c91f5d00-a720-11eb-966f-2030a724a25e.PNG)

### Diagnostics
![Cluster info - diagnostic](https://user-images.githubusercontent.com/80209954/116184863-d63c4c00-a720-11eb-8f6f-89470bb1a278.PNG)

### Other clusters that are not mentioned above

![Cluster info - Power configuration](https://user-images.githubusercontent.com/80209954/116184900-e6542b80-a720-11eb-954b-6a0946bc4202.PNG)
![Cluster info - IAS Zone](https://user-images.githubusercontent.com/80209954/116184902-e6ecc200-a720-11eb-9de3-6dd7d60422ee.PNG)
![Cluster info - Poll control](https://user-images.githubusercontent.com/80209954/116184903-e6ecc200-a720-11eb-8511-e524381f684e.PNG)

**Comment by JonasKristiansen** [comment]
This is a valid request. LK Wiser will be a huge player in the Smart Home segment in Denmark, as they produce products matching the "standard" switches in Denmark.
