### ISSUE TITLE
LK Wiser Motion Sensor

### ISSUE THREAD

**Issue by jonmoerk** [dresden-elektronik/deconz-rest-plugin#4817]
## Device

- Product name: LK Wiser Motion Sensor
- Manufacturer: Schneider Electric
- Model identifier: CCT595011_AS
- Device type : 
  - Sensor

[https://www.lk.dk/produkter?iid=13903](https://www.lk.dk/produkter?iid=13903)
[https://zigbeealliance.org/zigbee_products/wiser-motion-sensor-2/](https://zigbeealliance.org/zigbee_products/wiser-motion-sensor-2/)

This device is the same product line as:
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4534](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4534)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4800](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4800)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4816](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4816)
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4801](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4801)

## Screenshots

![Motion Sensor](https://user-images.githubusercontent.com/80209954/116186432-ebff4080-a723-11eb-834d-a993f5204bcd.PNG)
![info](https://user-images.githubusercontent.com/80209954/116186434-edc90400-a723-11eb-8ac2-5c8a1efe9931.PNG)

### Basic
![Basic](https://user-images.githubusercontent.com/80209954/116186437-f02b5e00-a723-11eb-987f-7cb3a8e9e93e.PNG)

### Identify
![Indentify](https://user-images.githubusercontent.com/80209954/116186443-f4f01200-a723-11eb-9951-22b8bfddab6d.PNG)

### Diagnostics
![Diagnostic](https://user-images.githubusercontent.com/80209954/116186456-fa4d5c80-a723-11eb-802f-5cdd70872efa.PNG)

### Other clusters that are not mentioned above
![Power](https://user-images.githubusercontent.com/80209954/116186482-05a08800-a724-11eb-92b0-87094f6084b9.PNG)
![Diagnostic](https://user-images.githubusercontent.com/80209954/116186484-06391e80-a724-11eb-936e-abf0f32483db.PNG)
![IAS](https://user-images.githubusercontent.com/80209954/116186486-06391e80-a724-11eb-8063-5b60c3f6939a.PNG)
![Illu](https://user-images.githubusercontent.com/80209954/116186488-06d1b500-a724-11eb-9970-e807d31f9d25.PNG)
![Poll](https://user-images.githubusercontent.com/80209954/116186489-06d1b500-a724-11eb-98ef-ff0857089c6d.PNG)

**Comment by JonasKristiansen** [comment]
Really hope this will be implemented. The new LK wirer are the best solution for a ceiling mounted PIR when talking looks. 

I have purchased one to test with Deconz.
