### ISSUE TITLE
Wyze Door Lock

### ISSUE THREAD

**Issue by junalmeida** [dresden-elektronik/deconz-rest-plugin#4819]
## Device

- Product name: Wyze Door Lock
- Manufacturer: Yunding.
- Model identifier: Ford.
- Device type : Lock

## Screenshots

![image](https://user-images.githubusercontent.com/991675/116248359-6d110480-a731-11eb-856e-424c2fe684fd.png)

### Basic
![image](https://user-images.githubusercontent.com/991675/116248426-7b5f2080-a731-11eb-8e55-dbcad5f7d1fc.png)

### Identify
![image](https://user-images.githubusercontent.com/991675/116248464-844ff200-a731-11eb-9351-0be8849620cc.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/991675/116248670-aba6bf00-a731-11eb-8123-4a86b013b9fe.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/991675/116248577-95006800-a731-11eb-891a-868c6f06cd9f.png)

![image](https://user-images.githubusercontent.com/991675/116248627-9fbafd00-a731-11eb-9986-c10750044867.png)

![image](https://user-images.githubusercontent.com/991675/116248744-b9f4db00-a731-11eb-924a-971176b0e901.png)

![image](https://user-images.githubusercontent.com/991675/116248849-d0029b80-a731-11eb-9086-0832be8ef609.png)

**Comment by Smanar** [comment]
Hello, I m on a PR just for doorlock, are you able to test it ? You need a linux machine with a complete OS.

**Comment by junalmeida** [comment]
Currently my setup runs on the docker image in a openhabian (openhab image for raspberry).  I don't have a x64 full machine with linux running. If you could add a dev tag to the docker image I can pull it and give try.

**Comment by Smanar** [comment]
Docker are not realy "full OS", I m not skilled enought to do it on docker, perhaps the openhab docker is more complete than the HA one, but seriously I prefer avoid.
If you realy don't have other linux machine (even x32), just for tests, I can add the device in blind mode, but without guarantees.

**Comment by junalmeida** [comment]
Yeah, I really don't have other linux boxes, only this ARM openhabian image (which is a debian distro that runs the docker I mentioned).

I'm ok to try your blind mode version :)

**Comment by Smanar** [comment]
Have added it on the future doorlock PR.

**Comment by junalmeida** [comment]
Ah, I forgot to mention, this lock has also a door sensor that  indicates if the door is open or closed. I believe this comes from the FC00 cluster, is there any log messages I can send you to implement this cluster?

![image](https://user-images.githubusercontent.com/991675/116616158-f6773100-a901-11eb-8dd9-1d2ea2398f32.png)

**Comment by Smanar** [comment]
I have already added a "door state" but I read it from the cluster 0x0101. IDK if it s the same ...

**Comment by junalmeida** [comment]
hmmm interesting, I will test then when it is available. 
thanks :)

**Comment by Smanar** [comment]
Yep it s this one
```
                                    if (ia->numericValue().u8 == 0)
                                    {
                                        str = QLatin1String("open");
                                    }
                                    else if (ia->numericValue().u8 == 1)
                                    {
                                        str = QLatin1String("closed");
                                    }
                                    else if (ia->numericValue().u8 == 2)
                                    {
                                        str = QLatin1String("error jammed");
                                    }
                                    else if (ia->numericValue().u8 == 3)
                                    {
                                        str = QLatin1String("error forced open");
                                    }
                                    else if (ia->numericValue().u8 == 4)
                                    {
                                        str = QLatin1String("error unspecified");
                                    }
                                    else
                                    {
                                        str = QLatin1String("undefined");
                                    }
```

**Comment by junalmeida** [comment]
wow that's perfect :D

**Comment by junalmeida** [comment]
Just checking in to ask if this is supposed to be in v2.11.2-beta (Apr 30th) or in the next release. Thank you.

**Comment by Smanar** [comment]
The PR is not submitted at all yet, we are finishing the pin management first https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3750

**Comment by villasenor** [comment]
@Smanar any updates on this? What is the current state of Wyze Lock support in deconz?

**Comment by Smanar** [comment]
Hello, if you can try this DDF

{
```
  "schema": "devcap1.schema.json",
  "manufacturername": "Yunding",
  "modelid": "Ford",
  "vendor": "Wyze",
  "product": "YWyze Door Lock",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_DOOR_LOCK",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val != 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    }
  ]
}
```

I m not sure it's the last version for doorlock, if you can tell me what is working or not ?
