### ISSUE TITLE
SM0201 - _TYZB01_cbiezpds - Tuya Zigbee Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by easybeat** [dresden-elektronik/deconz-rest-plugin#4823]
## Device

- Product name: Tuya Zigbee Temperature and Humidity Sensor
- Manufacturer: _TYZB01_cbiezpds
- Model identifier: SM0201
- Device type : 
  - Sensor

![image](https://user-images.githubusercontent.com/37217887/116409492-2fe16b00-a834-11eb-8be5-e3fde1936366.png)

## Screenshots
![image](https://user-images.githubusercontent.com/37217887/116409045-c1041200-a833-11eb-9ff3-cb39b5bb5f85.png)

### Basic
![image](https://user-images.githubusercontent.com/37217887/116409147-daa55980-a833-11eb-8506-074215ec9123.png)
![image](https://user-images.githubusercontent.com/37217887/116408997-b3e72300-a833-11eb-9018-2a26ce920fc7.png)
### Device Temperature
![image](https://user-images.githubusercontent.com/37217887/116409329-09233480-a834-11eb-9b1f-db07a13be40e.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/37217887/116409269-f90b5500-a833-11eb-8d85-3c3412dc353f.png)

![image](https://user-images.githubusercontent.com/37217887/116409401-18a27d80-a834-11eb-8bfb-402fb9661b5b.png)

**Comment by G0sch** [comment]
sorry for opening a duplicate ...didn't checked the close requests
