### ISSUE TITLE
Moes 4-gang switch

### ISSUE THREAD

**Issue by marithpl** [dresden-elektronik/deconz-rest-plugin#4826]
## Device

- Product name: Moes 4-gang Switch
- Manufacturer: Moes _TZ3000_vp6clf9d
- Model identifier: TS0044
- Device type : Switch
- Link to device: https://www.aliexpress.com/i/1005001504861368.html?spm=a2g17.12057483.1000001.8.22893bdeP2K6OL

Device paired with phoscon with success but in HA it show as a normal 4 plug switch.
So I'm not able to make any automations in Home Assistant.
In Phoscon it also not showing on group linking with switch.

I have other Aqara Wall Switch and not present toggles in HA and is visible in Phoscon group linking.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/25366097/116522758-d6ca1380-a8d5-11eb-9568-fadf83fbe051.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/25366097/116523559-a6cf4000-a8d6-11eb-8d21-ff44b04874ca.png">

## Screenshots
<img width="320" alt="image" src="https://user-images.githubusercontent.com/25366097/116522124-1b08e400-a8d5-11eb-9ff8-099ea8c40c3d.png">

### Basic
<img width="410" alt="image" src="https://user-images.githubusercontent.com/25366097/116521897-d4b38500-a8d4-11eb-9ac0-db7d4e0986fe.png">
### Power Configuration
<img width="463" alt="image" src="https://user-images.githubusercontent.com/25366097/116522286-51466380-a8d5-11eb-8d2d-66166b6b8277.png">

### On/Off
<img width="446" alt="image" src="https://user-images.githubusercontent.com/25366097/116522223-3aa00c80-a8d5-11eb-89f9-1c1a487b5f6c.png">

**Comment by Mimiix** [comment]
Hi! 

there's already a issue on this switch https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3611

I think it's the same (at least the model ID is).

**Comment by Mimiix** [comment]
Is it the same? if so, i suggest we close this issue and proceed there :)

**Comment by marithpl** [comment]
Seems to be the same
