### ISSUE TITLE
--http-listen command line option does only tie the webserver to an IP address, but not the websocket server

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#4827]
## Describe the bug
In order to limit deCONZ' communication to a particular interface/IP address, command line parameter `--http-listen` can be used. However, only the webserver component is affected by this. The websocket server is still listening on any IP address.

## Steps to reproduce the behavior
Start deconz from command line and specify loopback interface as IP address, e.g.: `/usr/bin/deCONZ --http-listen=127.0.0.1` and check the open ports via `netstat -tulpn | grep -i deconz`

## Expected behavior
Webserver and websocket server should both be only accessible via the IP address specified via `--http-listen`. Alternatively, an additional command line parameter for taking care of the websocket server should be made available.

## Screenshots
![grafik](https://user-images.githubusercontent.com/4005212/116622666-5ba04600-a945-11eb-8f48-a2492585233a.png)

![grafik](https://user-images.githubusercontent.com/4005212/116622720-6e1a7f80-a945-11eb-8ee2-7f2a1f31c659.png)

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: not relevant
 - deCONZ version: <=2.11.01
 - Device: not relevant
 - Do you use an USB extension cable: not relevant
 - Is there any other USB or serial devices connected to the host system? If so: Which? not relevant

## deCONZ Logs
N/A

## Additional context
See also #3948

**Comment by Netfreak25** [comment]
I have the same issue with my deconz setup
