### ISSUE TITLE
Do all the routers forward to the coordinator correctly ?

### ISSUE THREAD

**Issue by LeoeLeoeL** [dresden-elektronik/deconz-rest-plugin#4829]
## Describe the question or issue you are having
 I have 2 Vimar Covering Windows.
They are at the same floor.
One works perfectly; For the other one it's almost impossible to read the clusters.
When I open both windows, the first one shows me the % of opening while the second says it's still closed. After hours, it tells me the %.
They have different links in the mesh of course.

## Environment
 v2.11.1-beta
Qt: 5.7.1
GCC: 6.3.0 (C++ 201402)
Commit: 51086e
Firmware: 0x26680700

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26680700)
 - deCONZ version: (2.11.1-beta)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? APC ups

## Additional context
For info, the working Vimar has a direct link to Conbee.
Could be a problem Vimar is Zigbee HA and often the strongest link is a ZLL device?
Is there a way to force the device to connect to Conbee directly ?

**Comment by Smanar** [comment]
You don't have the mesh picture from the GUI ?

**Comment by LeoeLeoeL** [comment]
![Immagine 2021-05-01 190549](https://user-images.githubusercontent.com/65825223/116789798-0123f880-aab1-11eb-8cb4-09e4614b0136.png)

**Comment by Smanar** [comment]
Effectively, realy strange, you have realy good mesh, and the device "Finestra centrale" seem have lower quality connexion than the problematic one ....

>Is there a way to force the device to connect to Conbee directly ?

No, but there is perhaps something to help you, never tried (and I realy don't understand what is it) but take a look at that https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Source-Routing.

Perhaps on logs you can find a device with connexion or firmware issue ? (With error and error_l2)

**Comment by LeoeLeoeL** [comment]
Same routers are offline because they are under physical switch.
I tried source routing but it didn't solve the problem.A strange thing I saw in Phoscon are the name Deconz gave to the device:
Finestra Centrale was "cover.window_covering_device_26"
Finestra Dispensa was "cover.window_covering_device_26_2"
As the same device has been re-paired.

One question. What are Max buffer size and Max incoming/outcoming Transfer Size ? Vimar devices have higher values (107/128) than the others. Osram plugs have (64/0).

The only errors are:
19:50:41:680 command queue EVENT_TIMEOUT, cmd: CMD_APS_DATA_INDICATION2, seq: 123
19:55:42:720 command queue EVENT_TIMEOUT, cmd: CMD_APS_DATA_INDICATION2, seq: 168
20:00:43:716 command queue EVENT_TIMEOUT, cmd: CMD_APS_DATA_INDICATION2, seq: 239
20:05:41:288 command queue EVENT_TIMEOUT, cmd: CMD_APS_DATA_INDICATION2, seq: 16

**Comment by LeoeLeoeL** [comment]
I forgot to write that before the 2nd covering window device I had a Vimar switch. It had the same problem. I believed it was faulty so that I gave back and bought a 2nd covering window switch.
It seems Deconz doesn't like more than a Vimar device. :-)

**Comment by Smanar** [comment]
>Some routers are offline because they are under physical switch.

Can be a possible issue too, the mesh is dynamic, but it s not something recommanded.

For the "magic numbers" https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/LQI-explained

For the error message, I will ask to other devs, before saying craps.

>It seems Deconz doesn't like more than a Vimar device. :-)

Yeah, but I don't see why a device will not work like the second one ...

**Comment by LeoeLeoeL** [comment]
The values I wrote are in Node Info window and are "steady".
Max Buffer Size for:
Vimar 108
Osram 64
Lidl 82
Sonoff 82
Conbee 71

**Comment by Smanar** [comment]
>I know but I have to choose between a good mesh and my wife.

Lol, the WAF problem.

Values, like color, are just an indication, and they not look bad, about the error log, manup have answered

> I think this is an timing /race condition  issue in core when the indication is received at the same time it is queried.
> Have this on the todo list to check, shouldn't cause any harm other then the misleading debug message

So bad luck, not realy usefull too to explain the issue.

Same values for reporting value ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2196#issuecomment-695843587

**Comment by LeoeLeoeL** [comment]
Do you know what MAC Capabilities means in Node Info?
Beacause I found something strange.
The coordinator has 0x0f.
All the end devices (sensors and Tradfri ON/OFF switches) have 0x80.
All the routers have 0x8e except Vimar Finestra Centrale that has 0x0e.

This week, if I have time, I disconnect Finestra Centrale in order to realize if Deconz doesn't like 2 Vimar devices.

**Comment by SwoopX** [comment]
Oh, if you got 0x0E in mac capabilities, than this is most likely the reason for you trouble. In those cases, deconz considers the node descriptor to be invalid, which impacts cluster bindings and attribute reporting and pretty much explains why you don't get anything. The issue here is that the allocate short address bit is set to 0.

I, personally, consider this a bug in deconz core as the specs do not demand it to be set to 1 in the node descriptor, but it's a must on IEEE 802.15.4 level.

As I see it, a potential fix would require 2 whitelisting entries in `bindings.cpp`. However, the root cause of this should be eliminated once and for all.

**Comment by Smanar** [comment]
Ha nice, ths a lot, realy usefull, to put on a post-it.

It s not possible to solve this problem using GUI command ? re-ask the node descriptor up to have good values ?

**Comment by LeoeLeoeL** [comment]
I clicked on READ NODE DESCRIPTOR  and now I have 0x8e.

**Comment by SwoopX** [comment]
I'd assume now the troublesome device works as expected (again)?

**Comment by LeoeLeoeL** [comment]
The device with the wrong MAC Capability was the working one (Finestra Centrale) . Before fixing it, I tried to read something in the other device (Finestra Dispensa) and was OK.
Perhaps because yesterday night I put an IKEA range extender very close to it (70 cm) and now this one links Vimar to Conbee correcly.

**Comment by Smanar** [comment]
So the working one was the one with  0x0E, and the good reconized  not working ?

**Comment by LeoeLeoeL** [comment]
Affirmative.

**Comment by LeoeLeoeL** [comment]
The trick of Ikea range extender worked until I changed 2 Osram plugs (ZLL) with 2 Lidl plugs (HA).
Then I deleted FINESTRA CENTRALE (the working one) in order to verify if Deconz doesn't like more than 1 Vimar. No difference.
Then I deleted FINESTRA DISPENSA too and re-paired both.
It happened:
![image](https://user-images.githubusercontent.com/65825223/117122932-b0551e00-ad96-11eb-961e-615b22ee722b.png)
The working device paired correctly (even if with another name) but the other one remained as 0x9C98

**Comment by Smanar** [comment]
>but the other one remained as 0x9C98

This one is grayed, not connnected, and badly included previously (have only 1 circle on node title)

**Comment by LeoeLeoeL** [comment]
At last, to have the device working, I had to:
1) Delete the dimmable actuator iCasa  ICZB-IW11D "Luce Sala Cinema" (is it the guilty ?)
2) Use an old installation in Windows where there were less devices.
3) Pair the Vimar
4) Come back to RPi3.
Now it works OK hoping there will not be another device with that problem.

I think zigbee is more a protocol than a standard.
Some devices fight with others.
But the main limitation is each brand claims its bridge to update firmwares.

**Comment by Smanar** [comment]
> I think zigbee is more a protocol than a standard.
> Some devices fight with others.

Big story ...

>But the main limitation is each brand claims its bridge to update firmwares.

No you can update all firmwares with deconz, ...., if you have the file.

**Comment by LeoeLeoeL** [comment]
... But almost nobody publishes them.
It's a lack in the zigbee alliance.

**Comment by LeoeLeoeL** [comment]
Damn, the issue again!

**Comment by LeoeLeoeL** [comment]
I made many other tests.
I also disconnected by wire the working vimar (Finestra Centrale) keeping in the mesh only the other one (Finestra Dispensa).
At first it worked but, when I add other devices, after some hours the problem reappears.
Only one attempt remains; Deleting all the mesh and starting again.
If I use RESET GATEWAY in Phoscon does Deconz forget everything?
Do devices remember "something" from the previous link?

**Comment by Smanar** [comment]
> If I use RESET GATEWAY in Phoscon does Deconz forget everything?

Useless for me. You can see the information if you have a sql editor.

> Do devices remember "something" from the previous link?

Not sure to understand what you are talking, perhaps about neighbour table ? but yes, some data are memorised.

>At first it worked but, when I add other devices, after some hours the problem reappears.

But it s realy kike the network can support only 1 vimar ...

**Comment by LeoeLeoeL** [comment]
And I should buy other 3 vimars for my windows!!!!!!

**Comment by LeoeLeoeL** [comment]
Unbelievable.
It worked for 24 hours flawlessy and now it doesn't read again.

Is it normal this number in the "read neighbor table"?
![image](https://user-images.githubusercontent.com/65825223/117857837-7fd91c80-b28d-11eb-8b1f-386b709959da.png)

**Comment by LeoeLeoeL** [comment]
At last, it seems to work properly only when linked straightly to the coordinator.

**Comment by Smanar** [comment]
I know some end device not compatible with some routers, but from my memory, no other situation with routers not compatible with other routers ...

**Comment by LeoeLeoeL** [comment]
I think I buy an extension cord USB to put the Conbee II in a better place for Vimar(s).
But it would be a better place for everyone.
How many links can Conbee II manage directly?

**Comment by Smanar** [comment]
>How many links can Conbee II manage directly?

32 if I m right.

**Comment by LeoeLeoeL** [comment]
> I know some end device not compatible with some routers, but from my memory, no other situation with routers not compatible with other routers ...

I just wrote to Vimar about the inability to communicate the position of the window if not connected directly to the coordinator.
I hope they don't reply Deconz is guilty.  :-)

**Comment by LeoeLeoeL** [comment]
Vimar didn't respond yet.
Anyway I observed since 2.11.3 more links than before generally and now also the 2nd Vimar is firmly connected to the coordinator.

**Comment by LeoeLeoeL** [comment]
Vimar answered the product is certified Zigbee 3.0 so the problem must be the coordinator.
I'm sure they didn't test anything.
