### ISSUE TITLE
v2.05.13

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#483]
Is the published v2.05.13 on http://www.dresden-elektronik.de/rpi/deconz/beta the correct one?  I installed it, but don't see `sunriseoffset` and `sunsetoffset` in the Daylight sensor's `config`.  When I compile the REST API myself, they do show.

**Comment by manup** [comment]
Nope it will be in 2.05.14 arriving later today :)

**Comment by ebaauw** [comment]
My bad.  Is there still time to sneak in a PR in 2.05.14 for CLIPConsumption and CLIPPower support?

**Comment by manup** [comment]
>My bad. Is there still time to sneak in a PR in 2.05.14 for CLIPConsumption and CLIPPower support?

Absolutely, will be merged for 2.05.14.
