### ISSUE TITLE
IKEA STYRBAR "Remote Control N2" Type E2001

### ISSUE THREAD

**Issue by zustellr** [dresden-elektronik/deconz-rest-plugin#4832]
## Device

- Product name: IKEA STYRBAR Remote Type E2001
- Manufacturer: IKEA of Sweden
- Model identifier: Remote Control N2
- Device type : Please remove all unrelated device types. 
  - Remote

## Screenshots

![image](https://user-images.githubusercontent.com/7841068/116809372-fcf1ec80-ab3d-11eb-9b7d-67e67397f1b8.png)
![image](https://user-images.githubusercontent.com/7841068/116809380-07ac8180-ab3e-11eb-90ea-ec2262e4c170.png)
![image](https://user-images.githubusercontent.com/7841068/116809389-17c46100-ab3e-11eb-8f66-ca2934013208.png)
![image](https://user-images.githubusercontent.com/7841068/116809405-2dd22180-ab3e-11eb-9d9d-e35c4128ecde.png)
![image](https://user-images.githubusercontent.com/7841068/116809440-565a1b80-ab3e-11eb-8836-f36680a1f3d7.png)
![image](https://user-images.githubusercontent.com/7841068/116809454-670a9180-ab3e-11eb-9902-2ea8d1e9a4e3.png)
![image](https://user-images.githubusercontent.com/7841068/116809465-74c01700-ab3e-11eb-8418-72914153c1a7.png)

**Comment by zustellr** [comment]
Also posted this to https://github.com/dresden-elektronik/phoscon-app-beta/issues/380 two days ago, probably in error. Sorry about that.

**Comment by SwoopX** [comment]
This device is already supported, check the release notes.
