### ISSUE TITLE
Add Button Map for lumi.switch.b1naus01

### ISSUE THREAD

**Issue by rexbron** [dresden-elektronik/deconz-rest-plugin#4834]
## Device

- Product name: Xiaomi Aqara Single Rocker In-Wall Switch 
- Manufacturer:  LUMI
- Model identifier: lumi.switch.b1naus01
- Device type : Please remove all unrelated device types. 
  - Light
  - Sensor
  - Switch

## Logs

`12:30:14:587 [INFO] - No button map for: lumi.switch.b1naus01, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0702, command: 0x0A, payload: 000025E01600000000, zclSeq: 28`

## Screenshots

![image](https://user-images.githubusercontent.com/587341/116820731-75f44280-ab44-11eb-8415-b77d3d871d7d.png)

![image](https://user-images.githubusercontent.com/587341/116820558-c919c580-ab43-11eb-85c6-6e913035d85f.png)

### Basic
![image](https://user-images.githubusercontent.com/587341/116820575-db93ff00-ab43-11eb-8917-86564b930c4d.png)

### Identify
![image](https://user-images.githubusercontent.com/587341/116820627-05e5bc80-ab44-11eb-98ee-a2295ae385a2.png)

### Alarms
![image](https://user-images.githubusercontent.com/587341/116820695-42191d00-ab44-11eb-8364-8e2220729a50.png)

### Device Temperature
![image](https://user-images.githubusercontent.com/587341/116820596-ed75a200-ab43-11eb-9f66-811211ecfadc.png)

### Groups
![image](https://user-images.githubusercontent.com/587341/116820639-19912300-ab44-11eb-9f2b-bbed44330087.png)

### Scenes
![image](https://user-images.githubusercontent.com/587341/116820649-26ae1200-ab44-11eb-8e2a-8ea47d8d5b5d.png)

### On/Off
![image](https://user-images.githubusercontent.com/587341/116820673-33cb0100-ab44-11eb-80e8-7ed8c8a56ecb.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/587341/116820708-53fac000-ab44-11eb-8f6b-0ecb085a61e1.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/587341/116820720-64129f80-ab44-11eb-9e01-4f4a03640695.png)

**Comment by Smanar** [comment]
But according to your capture, not sure you need it ?
It s a router, and I think it create only a "light" entry, no ?

**Comment by rexbron** [comment]
Perhaps this is a misunderstanding on my part, I saw it in the log and figured that deconz wouldn't emit the log entry unless it needed more information.

In an ideal world, It would be great to be able to use the physical button to also trigger other automations in Home Assistant. Perhaps you already can?

**Comment by Smanar** [comment]
IDK, Aqara davice that permit that have so much endpoint.

![vc](https://user-images.githubusercontent.com/20152487/116822166-8a086600-ab7d-11eb-836e-7d71ce75e20d.png)

1 endpoint can be used for light and another for switch hen they are "decoupled". But your device relay don't look same.
If you can't "decouple" the command from the relay, you can just use the light state to know if the device is on or off, no ?

> 12:30:14:587 [INFO] - No button map for: lumi.switch.b1naus01, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0702, command: 0x0A, payload: 000025E01600000000, zclSeq: 28

Cluster 0x0702 is the simple metring, for the light consumption, it s probably for that the sensor was ignored.
It s something coded in the API, I don't know the reason but there is something in code to ignore this cluster for this device.

**Comment by SwoopX** [comment]
The device would need to expose a ZHASwitch resource for the button presses to emit button events. I'm not aware it is currently whitelisted for creating any sensor resources. If it would, it would generate further such INFO messages for the other clusters which then could be used to define a button map.
