### ISSUE TITLE
Philips Hue: Motion sensor. Value for temperature and light level is always 0 and will not be updated.

### ISSUE THREAD

**Issue by xADDRx** [dresden-elektronik/deconz-rest-plugin#4836]
## Environment

 - Host system: (Nuc)
 - Running method: (Ubuntu / Home Assistent deCONZ Add-on / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (last)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by xADDRx** [comment]
![grafik](https://user-images.githubusercontent.com/64784940/117000573-8ee62a80-ace1-11eb-8344-37713687ada4.png)

**Comment by cllatser** [comment]
Hi, delete it and pair it again. Sometimes it doesn't work right the first time.

**Comment by xADDRx** [comment]
> Hi, delete it and pair it again. Sometimes it doesn't work right the first time. 

Hi, I tried so many times. Sometime without values and sometimes without Temp and light values. Doesn't work

**Comment by cllatser** [comment]
Okay, now leave it for a bit. Sometimes it takes a few minutes. from time to time you see passing in front to activate it.

**Comment by xADDRx** [comment]
I left it like that the day before yesterday, but the values ​​still apply today. I'll wait another day to see if something happens.

**Comment by xADDRx** [comment]
> Okay, now leave it for a bit. Sometimes it takes a few minutes. from time to time you see passing in front to activate it.

Unfortunately does not work. I have integrated over 100 devices, all without any problems. Only this sensor drives me crazy

**Comment by cllatser** [comment]
I understand you perfectly, I have 5 indoor and 3 outdoor and no problem. In some I had to test the link 5 times. Another thing you have to know is that it refreshes the temperature and the lux when it detects movement.

**Comment by bee-con** [comment]
Sounds familiar. Have you tried reading the temperature and illuminance values manually from within deConz? That's what usually helped me when I experienced that.

![deconz_read_cluster](https://user-images.githubusercontent.com/73778640/118766031-2d46c400-b87c-11eb-83a7-0ac7dbd64eae.png)
