### ISSUE TITLE
Aqara Wireless Remote Switch H1 (Double Rocker)

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/deconz-rest-plugin#4842]
## Device

- Product name: Aqara Wireless Remote Switch H1 (Double Rocker)
- Manufacturer: Lumi
- Model identifier: lumi.remote.b28ac1
- Device type : 
  - Switch

## Screenshots

![Bildschirmfoto 2021-05-06 um 12 26 51](https://user-images.githubusercontent.com/1507977/117284042-b87c8e80-ae66-11eb-95e8-35b1ace94096.png)

![Bildschirmfoto 2021-05-06 um 12 28 11](https://user-images.githubusercontent.com/1507977/117283874-89feb380-ae66-11eb-8edc-cee8be3ae8a1.png)

![Bildschirmfoto 2021-05-06 um 12 26 05](https://user-images.githubusercontent.com/1507977/117283616-3f7d3700-ae66-11eb-9821-f1f327192f39.png)

**Comment by tomillr** [comment]
Anything I can do to help getting this devices integrated? Can I send you one of those switches perhaps?

Aqara is about to release a bunch of new Zigbee 3.0-version of their popular switches and sensors btw.

**Comment by netnetaip** [comment]
I'm also intrested to see H1 switch integrated in ConBee II or RaspBee II devices

**Comment by SwoopX** [comment]
You guys might want to give the latest firmware a try (http://deconz.dresden-elektronik.de/deconz-firmware/beta), since it has some new builtin specialties for Xiaomi. We recently discovered that the latest Xiaomi's require the coodinator to have a Xiaomi manufacturer code to eventually reveal their full set of clusters, which I feel is the case here. This is too less for a dual rocker.

With the new FW, please also make sure to reset and re-pair the device and push all buttons a couple of times while device search is running.

**Comment by tomillr** [comment]
Ok, so I've updated my Conbee 2 stick to the latest beta firmware and I've setup a completely new and clean test system:

![Bildschirmfoto 2021-05-21 um 10 47 58](https://user-images.githubusercontent.com/1507977/119113024-f65fe200-ba24-11eb-9023-ebebf35ab84a.png)

![Bildschirmfoto 2021-05-21 um 11 10 26](https://user-images.githubusercontent.com/1507977/119113212-2909da80-ba25-11eb-8612-d2c9e49b7e4a.png)

However, I'm not able to pair the Aqara H1 Wireless Remote Switch anymore. It only shows up, when I first connect at least one additional Zigbee endpoint. 

Could it be that the new Aqara switch tries not to connect to the Conbee stick but instead acts like one of those light link remotes from Ikea that work without the hub?

**Comment by SwoopX** [comment]
Have you also pushed both buttons simultaneously? I'd expect to also have an endpoint 02.

**Comment by tomillr** [comment]
> Have you also pushed both buttons simultaneously? I'd expect to also have an endpoint 02.

Yes, I've pushed both buttons in different combinations and length. Where should I look for endpoint 02 in the Devons GUI btw?

**Comment by SwoopX** [comment]
ok, 2nd screenshot of your last post. Would you be able to compile the plugin for testing?

**Comment by tomillr** [comment]
> ok, 2nd screenshot of your last post. 
So basically every possible button (left, right, left+right) should show up as its own section like "01" and "03" shown here?

![Bildschirmfoto 2021-06-02 um 16 57 02](https://user-images.githubusercontent.com/1507977/120503447-9c1b3580-c3c3-11eb-9899-e5a37ccbc010.png)


> Would you be able to compile the plugin for testing?
Never done this before, but I'd gladly give it a try. Do you have some kind of guide I can work with?

**Comment by SwoopX** [comment]
Sure, can do. I just need 1-2 days more as I want to pass you a nice experimental gimmick to sniff the communication :wink:

**Comment by tomillr** [comment]
Played around with those switches a bit more and tried to connect them to a SmartThings Hub as well.

I've noticed, that the switch seems to automatically connect itself to a random Zigbee light or smart plug. This also happens when there's no Zigbee Hub connect at all and I've manually reset every device beforehand. 

Could it be, that the new Aqara H1 switches are by default configured to establish a direct connection to the light source. Similar to how those TRÅDFRI remotes from Ikea come pre-connected to the Zigbee light bulb and work without the need for a Zigbee hub?

**Comment by SwoopX** [comment]
Alright, so the first code to test is ready. Please find the instructions how to compile below

```
git clone --branch=h1 https://github.com/swoopx/deconz-rest-plugin.git h1       # Clone repository
cd ./h1
qmake && make -j2                                                               # Compile
sudo systemctl stop deconz                                                      # Stop deCONZ headless (in case it is running)
sudo systemctl stop deconz-gui                                                  # Stop deCONZ GUI (in case it is running)
sudo cp /usr/share/deCONZ/plugins/libde_rest_plugin.so /usr/share/deCONZ/plugins/bak_libde_rest_plugin.so  # Make plugin backup
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins/                      # Copy newly compiled plugin to deCONZ plugin folder
/usr/bin/deCONZ --dbg-info=2 --dbg-error=2 > h1_debug                           # Run deCONZ with GUI and debug output
```

**Please make sure to collect around 15 mins of debug data and reset and re-pair the device as very first action.** Also, be sure to try out all thinkable combination of presses (single, double, tripple, hold) for each button. When done, please share the created file `h1_debug` from the h1 folder.

If required, you can restore the original plugin after deCONZ has been closed:

```
sudo cp /usr/share/deCONZ/plugins/bak_libde_rest_plugin.so /usr/share/deCONZ/plugins/libde_rest_plugin.so
```
and start deCONZ again in ONE preferred mode
```
sudo systemctl start deconz              # Start deCONZ headless
sudo systemctl start deconz-gui          # Start deCONZ GUI
```

> Could it be, that the new Aqara H1 switches are by default configured to establish a direct connection to the light source. Similar to how those TRÅDFRI remotes from Ikea come pre-connected to the Zigbee light bulb and work without the need for a Zigbee hub?

Yes, kind of. If appropriately configured, switches can control lights, etc. directly without the need of a coordinator. Switches typically get predefined groups they send their commands to. If the to be controlled devices subscribes to that group, the coordinator is not required any more.

It could be that the switch has also an alternate mode of operation. Maybe the generated debug output gives some hints about that.

**Comment by tomillr** [comment]
Compiling the plugin has proved to be a bit difficult. Had to first install the missing components (QTCreator, libqt5websockets5-dev, libqt5serialport5-dev) on my system before I was able to run the compile command. But the compilation stops with an error message:

```
root@DietPi:~/h1# qmake && make -j2
make -f Makefile.Release
make[1]: Entering directory '/root/h1'
/usr/lib/qt5/bin/uic -no-stringliteral de_web_widget.ui -o ui_de_web_widget.h
g++ -c -pipe -Wno-attributes -Wno-psabi -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DDECONZ_DLLSPEC=Q_DECL_IMPORT -DSKIP_EMPTY_PARTS=QString::SkipEmptyParts -DUSE_WEBSOCKETS -DGW_SW_VERSION=\"2.12.00\" -DGW_SW_DATE=1622991386 -DGW_API_VERSION=\"1.16.0\" -DGIT_COMMMIT=\"716fbf13eb6f060f0a1e770f931bf84c321ce3c6\" -DGW_AUTO_UPDATE_AVR_FW_VERSION=0x260b0500 -DGW_AUTO_UPDATE_R21_FW_VERSION=0x26420700 -DGW_MIN_AVR_FW_VERSION=0x26390500 -DGW_MIN_R21_FW_VERSION=0x26660700 -DGW_MIN_DERFUSB23E0X_FW_VERSION=0x22030300 -DGW_DEFAULT_NAME=\"Phoscon-GW\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../.. -I../../common -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/air_quality.o air_quality.cpp
g++ -c -pipe -Wno-attributes -Wno-psabi -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DDECONZ_DLLSPEC=Q_DECL_IMPORT -DSKIP_EMPTY_PARTS=QString::SkipEmptyParts -DUSE_WEBSOCKETS -DGW_SW_VERSION=\"2.12.00\" -DGW_SW_DATE=1622991386 -DGW_API_VERSION=\"1.16.0\" -DGIT_COMMMIT=\"716fbf13eb6f060f0a1e770f931bf84c321ce3c6\" -DGW_AUTO_UPDATE_AVR_FW_VERSION=0x260b0500 -DGW_AUTO_UPDATE_R21_FW_VERSION=0x26420700 -DGW_MIN_AVR_FW_VERSION=0x26390500 -DGW_MIN_R21_FW_VERSION=0x26660700 -DGW_MIN_DERFUSB23E0X_FW_VERSION=0x22030300 -DGW_DEFAULT_NAME=\"Phoscon-GW\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../.. -I../../common -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/authorisation.o authorisation.cpp
In file included from air_quality.cpp:1:
de_web_plugin.h:16:10: fatal error: deconz.h: No such file or directory
 #include <deconz.h>
          ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:581: release/air_quality.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from authorisation.cpp:13:
de_web_plugin_private.h:23:10: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:601: release/authorisation.o] Error 1
make[1]: Leaving directory '/root/h1'
make: *** [Makefile:40: release] Error 2
```

**Comment by SwoopX** [comment]
Ah, you're missing the deconz dev package.

`sudo apt-get install deconz-dev` should do the trick.

Qtcreator is a bit too much, but ok 😄

**Comment by tomillr** [comment]
So, I've finally managed to setup a new Debian environment and try compiling you plugin. Provided I followed your instruction correctly, I wasn't able to have the switch join the the newly setup network. Maybe the log can provide some details:

https://pastebin.com/KJMZzGdV

First, I manually reset the H1 switch a couple of times and tried to pair it using the Phoscon webapp. After that didn't work, I tried to pair a INNR smart plug to check the connection with the Conbee 2 stick, which didn't show up also.

Maybe I can just have you send you one of the actually switches? Might that help?
https://www.amazon.de/WRS-R02-WIRELESS-REMOTE-SWITCH-version/dp/B094QL17GY/ref=sr_1_1?__mk_de_DE=ÅMÅŽÕÑ&dchild=1&keywords=Aqara+h1&qid=1623496859&sr=8-1

**Comment by SwoopX** [comment]
Lemme check what you shared. I recall we recently had quite some strange reports that devices "refuse" to join. Interestingly, a restart of deconz seems to let the device appear automagically.

**Comment by tomillr** [comment]
@SwoopX Thanks, let me know if you need any further data.

**Comment by tomillr** [comment]
I've done some more testing and even got out my old Smart Thing v3 hub. But no matter what I try, the switch always seems to only establish a connection to a Zigbee 3.0 light source and not the hub itself.

For example, when using the h1 switch with the SmartThings hub, the hub doesn't detect the presence of the switch at all. Instead it automatically pairs itself to all the Zigbee 3.0 lights. So basically same behavior as when using a setup with the Conbee stick.

**Comment by SwoopX** [comment]
Ping me on Discord if you quickly wanna send one over 😉

**Comment by MiAutomations** [comment]
Hello Team 

Any news about the support of this device in the deconz plugin available on the HA Home Assistant once the device is not yet supported deCONZ Current version: 6.9.0

![image](https://user-images.githubusercontent.com/47602733/124590516-21768780-de53-11eb-8e4a-9fafabe5927a.png)


Thank you and best regards

**Comment by SwoopX** [comment]
This question was more a joke, right? 😄

**Comment by MiAutomations** [comment]
> This question was more a joke, right? 😄

No, it's only to check if you have a ideia about when this is available on the deconz plugin on the HA ...

**Comment by SwoopX** [comment]
Support is now included in the code since 1 hour, so its generally usable if you compile the plugin yourself. I'd expect the next beta to be officially release within the next 7 days. I don't know when the next stable is planned. I guess HA just prefers to use stable versions in the addon (where we have no stakes in).

**Comment by MiAutomations** [comment]
> Support is now included in the code since 1 hour, so its generally usable if you compile the plugin yourself. I'd expect the next beta to be officially release within the next 7 days. I don't know when the next stable is planned. I guess HA just prefers to use stable versions in the addon (where we have no stakes in).

Ok thank you for the information and for your support !! But once all must the people is using the deconz conbee II over the HA and once the people is using the HassOS and it's not possible to "compile" over this OS ... I think it's the best decrease this time or create a alternative in order  to make this available for more users ... 

Thank you and best regards

**Comment by SwoopX** [comment]
Well, I agree that it will probably make ppl happier, but's that's absolutely not in our hands. You need to suggest that to HA folks maintaining the addon, I'm afraid.

**Comment by oudoulj** [comment]
I run Hassio with a **Conbee 2** stick and **Deconz**.
My Conbee gateway version : 2.19.03 / 19/09/2022
and its firmware : 26780700

![Screenshot - 14_01_2023 , 18_48_02](https://user-images.githubusercontent.com/6011092/212488136-e4dceb89-fc2d-49f1-a203-e48471236c25.png)

Pairing of the Aqara wireless double-rocker switch WRS-R02 aka H1 went smoothly.

I can catch the various `deconz_event` in the Developer Tools / Events of HA (single, double, long clicks on both buttons) but **the automation screen does not expose those events** for me to choose from.
Only the "Battery level changes" trigger 😢 
Am I missing something obvious here ?

![Screenshot - 14_01_2023 , 15_38_43](https://user-images.githubusercontent.com/6011092/212488159-64e7d98f-8c93-4324-972f-2456ef46ec7b.png)

More info and screenshots [on the HA community](https://community.home-assistant.io/t/aqara-h1-button-press-not-triggering-automation/389498/14?u=jeromeo).
Thanks in advance for your help ! 🙏

**Comment by Mimiix** [comment]
> I run Hassio with a **Conbee 2** stick and **Deconz**. My Conbee gateway version : 2.19.03 / 19/09/2022 and its firmware : 26780700
> 
> ![Screenshot - 14_01_2023 , 18_48_02](https://user-images.githubusercontent.com/6011092/212488136-e4dceb89-fc2d-49f1-a203-e48471236c25.png)
> 
> Pairing of the Aqara wireless double-rocker switch WRS-R02 aka H1 went smoothly.
> 
> I can catch the various `deconz_event` in the Developer Tools / Events of HA (single, double, long clicks on both buttons) but **the automation screen does not expose those events** for me to choose from. Only the "Battery level changes" trigger 😢 Am I missing something obvious here ?
> 
> ![Screenshot - 14_01_2023 , 15_38_43](https://user-images.githubusercontent.com/6011092/212488159-64e7d98f-8c93-4324-972f-2456ef46ec7b.png)
> 
> More info and screenshots [on the HA community](https://community.home-assistant.io/t/aqara-h1-button-press-not-triggering-automation/389498/14?u=jeromeo). Thanks in advance for your help ! 🙏

Please check the deCONZ integration documentation . It's explained there.

**Comment by oudoulj** [comment]
> Please check the deCONZ integration documentation . It's explained there.

Can you please point me to a specific link ?
Because I've been googling for a while and couldn't find anything relevant, thank you very much.
_(I was able to find a workaround using the deconz_event as a trigger but it's not super straightforward)_

**Comment by oudoulj** [comment]
> deCONZ integration documentation

Ok, thank you.
It's just that for such a popular and 2-year old switch, I thought it would have been fully supported already so I thought I was the one doing something wrong :wink:

**Comment by Mimiix** [comment]
As far as i know, not a lot of devices are supported that way in home assistant. Nevertheless: it's really something home assistant needs to do

**Comment by yungSven** [comment]
Same Issue here

**Comment by oudoulj** [comment]
> Same Issue here

I used this method. Not super straightforward but works fine.
https://community.home-assistant.io/t/aqara-h1-button-press-not-triggering-automation/389498/15?u=jeromeo
