### ISSUE TITLE
[Feature request] When adding a dimmer, add also associated lights

### ISSUE THREAD

**Issue by ooii** [dresden-elektronik/deconz-rest-plugin#485]
Hi,

One nice feature I discovered with the Philips Hue bridge and the dimmer is the ability, when adding a dimmer, to automatically add the lights that are **directly** associated[1] to this dimmer.
That's very convenient to migrate several lights from one bridge to another without having to switch them on close to the gateway.
[1] To associate directly a light to a dimmer, keep the dimmer close to the light and hold the `on` button for 10 seconds. You can associate up to 10 lights to a dimmer.

**Comment by ronaldvans** [comment]
Hi,

I would appreciate this to. At the moment I have 35+ lights and an increasing number of dimmers and motion sensors.
