### ISSUE TITLE
Is v2.11.3-beta only a minor change ?

### ISSUE THREAD

**Issue by LeoeLeoeL** [dresden-elektronik/deconz-rest-plugin#4863]
## Describe the question or issue you are having
 I make this question because, after the update, I saw a different way to build the mesh.
It seemed many devices paired again during the rebuilding (in previous releases all devices were present immediatly but without links) and there are many more links among the device. 

## Environment

 - Host system: Raspberry Pi
 -  - Running method: Raspbian
 - Firmware version: : 0x266b0700
 - deCONZ version: 2.11.3 beta
 - Device: ConBee II
 - Do you use an USB extension cable: yes -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Ups APC

**Comment by Smanar** [comment]
Hello, what is your previous version ?

**Comment by manup** [comment]
Hmm, between v2.11.2-beta and v2.11.3-beta there aren't changes which would cause this :thinking: 

The v2.11.x series however looks more deep into verifying that all required data from nodes is queried and placed in the database.
But after deCONZ startup everything should load instantly.

**Comment by LeoeLeoeL** [comment]
The same with 2.11.4
![image](https://user-images.githubusercontent.com/65825223/118397191-1ffac100-b653-11eb-9c75-f2c596100371.png)

**Comment by LeoeLeoeL** [comment]
I update to 2.11.5 beta and the strange "repopulation" of devices didn't happen as for 2.11.3 and 2.11.4.

**Comment by LeoeLeoeL** [comment]
Updated to 2.12 beta. No "strange repopulation" but meshing was slower.

**Comment by Smanar** [comment]
How much "slower" ?
It can take 30mn for all routers be polled in a big network.

**Comment by LeoeLeoeL** [comment]
Slower at first.
Normally it fills in 20/30 seconds.
This time, more than double. Starting from the coordinator only.
A question; If a device is physically off (no powered) why it receives links when deconz starts?

**Comment by Smanar** [comment]
Link don't mean "connected"
You can have some device connected but without the "green line".
Some data are memorised on device theirself, perhaps is caused by some old neigboard table.
