### ISSUE TITLE
SINOPE RM3250ZB SMART CONTROLLER

### ISSUE THREAD

**Issue by joelwener** [dresden-elektronik/deconz-rest-plugin#4870]
## Device

- Product name: SINOPE smart controller
- Manufacturer: Sinope.
- Model identifier: RM3250ZB
- Device type :
  - Other: Smart Plug-Controller
![1620991926150963734368524407560](https://user-images.githubusercontent.com/84113418/118264954-85e61d80-b486-11eb-8a27-d69ca050df20.jpg)

![16209925858696675223902714278959](https://user-images.githubusercontent.com/84113418/118266049-107b4c80-b488-11eb-8909-fc850c3388c1.jpg)

### Basic
![PXL_20210513_024620142](https://user-images.githubusercontent.com/84113418/118264852-56cfac00-b486-11eb-8b7a-7e03c8ac83e5.jpg)

### Identify
![PXL_20210514_110144708](https://user-images.githubusercontent.com/84113418/118263183-ef186180-b483-11eb-8d82-fcf31585fdec.jpg)

### Device Temperature
![PXL_20210513_024637796](https://user-images.githubusercontent.com/84113418/118263234-01929b00-b484-11eb-94b1-f36837cbfd5f.jpg)

### Groups
![PXL_20210514_110202567](https://user-images.githubusercontent.com/84113418/118263391-30a90c80-b484-11eb-8aae-2dc291225ddb.jpg)

### Scenes
![PXL_20210514_110220459](https://user-images.githubusercontent.com/84113418/118264244-6995b100-b485-11eb-8ba3-a80b470ac396.jpg)

### On/Off
![16209920263115424649316011022804](https://user-images.githubusercontent.com/84113418/118265162-c6459b80-b486-11eb-9e57-3f4f391b95b0.jpg)

### Level Control
NA
### Color Control
NA

### Simple Metering
![PXL_20210513_024705078](https://user-images.githubusercontent.com/84113418/118263743-ab722780-b484-11eb-8483-40be042f8bf6.jpg)

### Diagnostics
![PXL_20210514_110235675](https://user-images.githubusercontent.com/84113418/118263853-d0ff3100-b484-11eb-8e59-63cb91facdab.jpg)

### Other clusters that are not mentioned above
![PXL_20210513_024716823](https://user-images.githubusercontent.com/84113418/118263929-f0965980-b484-11eb-82ad-7e385488f547.jpg)

![PXL_20210514_110251526](https://user-images.githubusercontent.com/84113418/118264093-2f2c1400-b485-11eb-8cb3-3f9be059521a.jpg)

![16209915847903388437361270611629](https://user-images.githubusercontent.com/84113418/118264466-bb3e3b80-b485-11eb-9771-8a345e1a06ad.jpg)

**Comment by joelwener** [comment]
Missing on/off
![PXL_20210513_030422637](https://user-images.githubusercontent.com/84113418/118071883-af178880-b376-11eb-9871-ee89fff6fca8.jpg)

**Comment by Mimiix** [comment]
Is this a double post of #4871 ?

**Comment by joelwener** [comment]
> Is this a double post of #4871 ?

No, two separate devices.  One is a smart plug, one is a smart controller (load)

**Comment by Mimiix** [comment]
@joelwener  the one in #4871 has the same model ID as this one (according to the screenshots)... 

Can you make them both complete with all cluster screenshots?

**Comment by joelwener** [comment]
Here are other cluster screen shots which I left out as I didn't consider them relevant at the time.
![PXL_20210514_110202567](https://user-images.githubusercontent.com/84113418/118262717-4d911000-b483-11eb-9b01-f22d2a3dc566.jpg)

**Comment by joelwener** [comment]
Sorry about that, I chose all the photos when I made the request, but I just realized it only posted one.  The post has been edited to include missing screenshots.
