### ISSUE TITLE
SINOPE sp2600ZB Smart Plug 

### ISSUE THREAD

**Issue by joelwener** [dresden-elektronik/deconz-rest-plugin#4871]
## Device

- Product name: Sinope smart plug
- Manufacturer: Sinope
- Model identifier: SP2600ZB
- Device type :
  - Other: Smart Plug
![16209922419165701589213238983235](https://user-images.githubusercontent.com/84113418/118265480-3e13c600-b487-11eb-926e-511fdba63c49.jpg)

![16209924844925179654626174079037](https://user-images.githubusercontent.com/84113418/118265878-cdb97480-b487-11eb-9927-1926202612c2.jpg)

### Basic
![16209922653184901393567160361820](https://user-images.githubusercontent.com/84113418/118265554-584da400-b487-11eb-8c5f-11782d0b46bf.jpg)

### Identify
![16209923126711544619292872252917](https://user-images.githubusercontent.com/84113418/118265606-68fe1a00-b487-11eb-980f-fed9f7fe832e.jpg)

### Alarms
NA
### Device Temperature
NA
### Groups
NA
### Scenes
NA
### On/Off
![16209923484767793678412355579444](https://user-images.githubusercontent.com/84113418/118265659-803d0780-b487-11eb-8056-4f07d0acb773.jpg)

### Level Control
NA
### Color Control
NA
### Simple Metering
![16209923848238655894612709316820](https://user-images.githubusercontent.com/84113418/118265707-934fd780-b487-11eb-9228-1332b4d7a75a.jpg)

### Diagnostics
NA
### Other clusters that are not mentioned above
![16209924133047843580763105881120](https://user-images.githubusercontent.com/84113418/118265768-a662a780-b487-11eb-854e-ca4a3bcc4c15.jpg)

![16209924494283130900143423690824](https://user-images.githubusercontent.com/84113418/118265809-b9757780-b487-11eb-8cb7-e4dbd1a7ad85.jpg)

**Comment by joelwener** [comment]
Missing on/off
![PXL_20210513_030444862](https://user-images.githubusercontent.com/84113418/118071836-927b5080-b376-11eb-9373-29b7dbe1382a.jpg)

**Comment by joelwener** [comment]
Smart plug / controller may qualify as sensor as well.

**Comment by joelwener** [comment]
To be clear, I would like the Phoscon I/f to recognize the following cluster points (as either sensors or readable points of the smart plug/controller)

Current Temperature

Electrical Measurement Cluster
RMS Current
RMS Voltage
Active Power
AC Frequency

Simple Metering Cluster :
Current Summation Delivered (kW)

On/Off (is already recognized)

Currently recognized as a light in Phoscon

**Comment by Mimiix** [comment]
@joelwener Can you add all screenshots in this issue?

**Comment by joelwener** [comment]
Corrected issue, included all missing screenshots.  Sorry about that.

**Comment by Mimiix** [comment]
@joelwener No problem at all! :)
