### ISSUE TITLE
Xiaomi sensors (door/motion) show 0° temperature in Phoscon

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#488]
![image](https://user-images.githubusercontent.com/10351272/37558929-598f79e0-2a1c-11e8-804f-15beca87234d.png)

Version 2.05.13 / 15.3.2018
Firmware 261E0500

**Comment by manup** [comment]
After a while (once per hour) all Xiaomi devices do send the temperature to the gateway and it should be visible.

**Comment by to0b** [comment]
Does the motion and door/window sensors have a temperature sensor onboard?

**Comment by manup** [comment]
Have a look here, the ones marked with `T` also have a temperature sensor:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices

Be aware they only update temperature once per hour.

**Comment by zladukas** [comment]
@manup Ikea Tradfri motion sensor battery is supportes, but there is no B near it.

**Comment by jo-me** [comment]
Cool, I did not know that the Aquara sensors had a temperature sensor in them..
This morning, the aquara door sensor had a reasonable value instead of the 0° from yesterday right after the deconz update.

But for the Xiaomi Mi sensors it is still a bug, though. According to your list, they don't have temperature sensor but are still displayed in Phoscon as if they had one. (the sensors in the screenshot above are all Xiaomi Mi ones).

**Comment by tleegaard** [comment]
My Aqara door sensor reports 27°C while the Hue motion sensor in the same room reports 22 °C - so I wouldn't trust the readings :-)

**Comment by ebaauw** [comment]
I wouldn't trust either of them.  The temperature sensor in the Xiaomi devices (other than the Aqara weather and Mi temperature/humidity) is rather crude.  I find that multiple Hue motion sensors, when placed next to each other, cannot agree on the current temperature either.  "With one watch a man knows what time it is, with two he's never sure..."

I find the Aqara weather sensors are fairly accurate, but sometimes take a long time to send a new attribute report, causing the temperature in deCONZ to lag behind.  The Heiman temperature/humidity sensor seems to do the best job, at least for temperature.

I introduced `config.offset` mainly to calibrate my Hue motion sensors, but the deviations don't seem to be constant over different temperatures.  When I set the offset, so the motion sensor shows the correct temperature at 22˚C, it will still show an incorrect temperature at 17˚C.  Maybe there's a reason Philips doesn't advertise that the motion sensor includes a temperature sensor...

Note that I don't have any professionally calibrated thermometer to compare the sensors to.  I compare against the old-fashed room thermostat of my central heating and a consumer-grade thermo/hygrometer, that came with my wooden floors.

**Comment by ACrazyConcept** [comment]
Hello
I got a Xiaomi motion sensor yesterday. It still shows 0˚C.
Is there a way I can verify if it has been connected properly?
In deCONZ it only show two clusters, Basic and Occupancy. No temp attributes in either.

**Comment by manup** [comment]
The temperature for the motion sensor is not transferred via temperature cluster but a Xiaomi specific command not visible in the deCONZ gui. The sensor reports the command once per hour.

Is it the Aqara version — which model id has the sensor?

**Comment by ACrazyConcept** [comment]
Oh ok.
Actually it is a Mijia. I was not aware there were two version when I ordered. It says RTCGQ01LM and CMIT ID: 2015DP0292

**Comment by ACrazyConcept** [comment]
Ok I got myself an Aqara version now as well. It reports a temperature.
Is there a way to get that temperature into Home Assistant when it does not have a cluster in deCONZ?

**Comment by ebaauw** [comment]
You’ll have to take that up with the developers of the Home Assistant plugin.  The internal temperature is exposed as `config.temperature`, contrary to the `state.temperature` for the “real” temperature clusters.

**Comment by ACrazyConcept** [comment]
Of course. Thanks for the feedback :)

**Comment by sealjo** [comment]
> Of course. Thanks for the feedback :)
> Edit: I figured it out. Thanks for pointing me in the right direction.

How did you do it? Have the same issue, I want the temperature I see in phoscon to be shown in HA but it isn't imported by the deconz config.

**Comment by mcka-dev** [comment]
My Aqara door sensor reports 34°C  (((
![изображение](https://user-images.githubusercontent.com/16173503/74468771-72778b80-4eac-11ea-90f6-24e2ffd60540.png)

**Comment by soundylinz** [comment]
My sensor reports 35°C without changes for a few hours:

![kontakt_sensor](https://user-images.githubusercontent.com/70177555/91103175-241d2380-e66b-11ea-83e0-d723fd6fedc0.png)
