### ISSUE TITLE
Conbee II NOT connect

### ISSUE THREAD

**Issue by RitaSghe** [dresden-elektronik/deconz-rest-plugin#4884]
## Describe the bug
I installed Conbee II and Deconz software on my Raspberry Pi4 (SO Raspberry).
I have 3 Aqara button and they're connected without problem but in deconz, Conbee turns out NOT connect and can't I see the advanced interface for visualization of network ....

Help us understand the issue by providing valuable context.

## Screenshots
![deconz](https://user-images.githubusercontent.com/81916825/118450367-69e7b380-b6f4-11eb-9b4c-f58f120248cf.png)

## Environment

 - Host system: (Raspberry Pi)
 - Running method: (Raspbian)
 - Firmware version: (26660700)
 - deCONZ version: (2.10.04)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: usb pen

## deCONZ Logs
09:58:16:088 wait reconnect 12 seconds
09:58:17:089 wait reconnect 11 seconds
09:58:18:088 wait reconnect 10 seconds
09:58:19:088 wait reconnect 9 seconds
09:58:19:588 failed to reconnect to network try=9
09:58:20:088 wait reconnect 8 seconds
09:58:21:089 wait reconnect 7 seconds
09:58:22:088 wait reconnect 6 seconds
09:58:23:088 wait reconnect 5 seconds
09:58:24:088 wait reconnect 4 seconds
09:58:24:588 failed to reconnect to network try=10
09:58:25:088 wait reconnect 3 seconds
09:58:26:088 wait reconnect 2 seconds
09:58:27:088 wait reconnect 1 seconds
09:58:27:170 dev /dev/ttyAMA0 (/dev/ttyAMA0)
09:58:27:182 device disconnected reason: 4, index: 0
09:58:28:088 wait reconnect 15 seconds
09:58:28:172 dev /dev/ttyAMA0 (/dev/ttyAMA0)
09:58:29:088 wait reconnect 14 seconds
09:58:29:588 reconnect network failed, try later
09:58:30:088 start reconnect to network
09:58:30:088 wait reconnect 13 seconds
09:58:31:088 wait reconnect 12 seconds
09:58:32:088 wait reconnect 11 seconds
09:58:33:088 wait reconnect 10 seconds
09:58:34:088 wait reconnect 9 seconds
09:58:35:088 wait reconnect 8 seconds
09:58:35:338 failed to reconnect to network try=1
09:58:36:088 wait reconnect 7 seconds
09:58:37:088 wait reconnect 6 seconds
09:58:38:088 wait reconnect 5 seconds
09:58:39:088 wait reconnect 4 seconds
09:58:40:088 wait reconnect 3 seconds
09:58:40:588 failed to reconnect to network try=2
09:58:40:637 dev /dev/ttyAMA0 (/dev/ttyAMA0)
09:58:41:088 wait reconnect 2 seconds
09:58:42:088 wait reconnect 1 seconds
09:58:42:130 dev /dev/ttyAMA0 (/dev/ttyAMA0)
09:58:42:136 device disconnected reason: 4, index: 1

## Additional context
With a script to scan the port I notice that I have /dev/ttyACM0 and not /dev/ttyAMA0 like in the log .....

**Comment by Mimiix** [comment]
So you connected them with Phoscon?

**Comment by RitaSghe** [comment]
Yes .....

**Comment by RitaSghe** [comment]
I tried this istruction:
$ deCONZ --dbg-error=2 --dbg-info=1 -platform minimal

and I have this error ...
COM failed to open /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2431343-if00: 
Permission error while locking the device

**Comment by Mimiix** [comment]
Aah. That's because you have the deconz service running.

You are trying to start another deconz. But you can't because deCONZ is already running and that deconz is using the stick.

Sudo systemctl deconz stop
sudo systemctl deconz-gui start

**Comment by RitaSghe** [comment]
With ..
sudo systemctl deconz stop

I have ...
Unknown operation deCONZ

**Comment by RitaSghe** [comment]
But I have two different port for deconz 40849 and 40850 ...
I shouldn't I have this problem ....

**Comment by Mimiix** [comment]
My mistake:
sudo systemctl stop deconz
sudo systemctl start deconz-gui

deCONZ is the Headless version.

If you want to run the map you need to run deconz-gui instead of deconz.

**Comment by RitaSghe** [comment]
OK, thank you ...

**Comment by Mimiix** [comment]
YOu can, but it can't use the same stick.

**Comment by RitaSghe** [comment]
When the last week I had installed Conbee II on my pc with kubuntu 20.04, I had configured one port for deconz and another port for deconz-gui and worked perfectly both ....
Ok, it's not a problem but it's weird .....

**Comment by Mimiix** [comment]
I am not sure what you mean.

If you run deconz-gui, you get both deconz and Phoscon.

**Comment by RitaSghe** [comment]
In Raspberry I have the Conbee II not connected (img.1)

![img1](https://user-images.githubusercontent.com/81916825/118643163-7f380d00-b7dc-11eb-821f-c990f6c64890.png)

and so I cannot see the network (img. 2)

![img2](https://user-images.githubusercontent.com/81916825/118643319-aee71500-b7dc-11eb-8943-b8a7fa4723c1.png).

To see the network form I have to stop deconz service .....

Well, in kubuntu I had not this problem; I had deconz service and deconz-ui service start both ....

**Comment by Mimiix** [comment]
Deconz and deconz-gui are exactly the same. You can run deconz-gui and have the same functionality as deconz service + the gui....

You can not have 2 deconz running on 1 stick. that is impossible.

**Comment by Smanar** [comment]
When an application use this kind of usb device, it use an exclusive connexion, so it s not possible to another app to use the same USB key.

**Comment by RitaSghe** [comment]
Ok, I understand, but why you not responding to my question?
In kubuntu 20.04 I had Conbee connected and I saw network both and now with Raspberry I cannot do that?
In this guide:
https://indomus.it/guide/come-installare-e-configurare-deconz-su-raspbian-di-raspberry-pi/
is written as how set two different port to use both and (I repeat) in kubuntu it's work fine ......

**Comment by RitaSghe** [comment]
UPDATE:
My Raspberry has two ip address:
lan 192.168.1.28
wifi 192.168.1.29
Today I realized that Conbee II is connected on 192.168.1.29 (wifi).
Can't be the reason of my problem?
Can I change the ip?

**Comment by Smanar** [comment]
But you still have problem ?
Which one deconz version you want to use ?

**Comment by RitaSghe** [comment]
Yes, I still have problem!!!!
I cannot see the network because I have the conbee disconnect, How am I going to explain?

![ddddd](https://user-images.githubusercontent.com/81916825/119444390-73dc6880-bd2b-11eb-9102-34938c85eece.png)

**Comment by RitaSghe** [comment]
The problem is :
Raspberry (Pi4) at start, started deconz and I cannot see the deconz-gui.
To see the network I got to stop deconz and start deconz-gui manually.
How can I start deconz-gui (at start of raspberry) in the place of deconz?

**Comment by Mimiix** [comment]
@RitaSghe Deconz-gui = Deconz. IT is the same,.but then also adding the gui.

**Comment by RitaSghe** [comment]
I don't understand if you make fun of me or what is the problem ....

**Comment by Mimiix** [comment]
...?

As i said. you can run deconz-gui. It is the same as deconz but without the gui. If you have deconz-gui running, you dont need to have deconz running.

**Comment by RitaSghe** [comment]
Evidently, we have communication problems, I give up, I'll try and get help elsewhere ....
