### ISSUE TITLE
Vimar 19592.0

### ISSUE THREAD

**Issue by RitaSghe** [dresden-elektronik/deconz-rest-plugin#4887]
## Device

- Product name: Meccanismo deviatore connesso IoT
- Manufacturer: Vimar
- Model identifier: 19592.0
- Device type : Switch
 
## Screenshots
![Vimar 19592 0](https://user-images.githubusercontent.com/81916825/118530450-f8842100-b744-11eb-8607-dd684c9b5198.png)

**Comment by Mimiix** [comment]
Missing all screenshots.

Please provide those in a new issue.
