### ISSUE TITLE
Konke button

### ISSUE THREAD

**Issue by RitaSghe** [dresden-elektronik/deconz-rest-plugin#4888]
## Device

- Product name: Konke smart
- Manufacturer: Konke
- Model identifier: Konke ZigBee
- Device type : Switch (Button)
  
## Screenshots
![ddddddd](https://user-images.githubusercontent.com/81916825/118534001-0b005980-b749-11eb-82c3-d0db59ac92eb.png)

**Comment by Mimiix** [comment]
Missing all screenshots of all clusters.

Please open a issue with all requested information.
