### ISSUE TITLE
CC2652RB stick with Konkee Firmware (used as router)

### ISSUE THREAD

**Issue by samsam-rolon** [dresden-elektronik/deconz-rest-plugin#4894]
## Device

- Product name: https://slae.sh/projects/cc2652/#the-stick
- Manufacturer: TI CC2652RB 
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Other: Dev stick as router or coordinator
https://github.com/Koenkk/Z-Stack-firmware/

## Screenshots

![image](https://user-images.githubusercontent.com/25209236/118772374-f5dc1580-b883-11eb-8166-4a9005a1c68d.png)
![image](https://user-images.githubusercontent.com/25209236/118772401-ff657d80-b883-11eb-9d2c-fe28e8bf753b.png)
![image](https://user-images.githubusercontent.com/25209236/118772439-09877c00-b884-11eb-971a-ffd237f4402f.png)
![image](https://user-images.githubusercontent.com/25209236/118772476-13a97a80-b884-11eb-8c5a-1454bb24fe4c.png)

**Comment by Smanar** [comment]
And what do you want to do with it ? Display it as entry in the API ?

**Comment by Mimiix** [comment]
IT is already repeating right?

You can't use it as coordinator as deCONZ only works with Conbee/Raspbee.

**Comment by samsam-rolon** [comment]
Yeah ! I'm using it as repeater. Yeah It would be nice to see it in api (and GUI) to facilitate pairing first, then to track it (alive or not) and finally for any evolution regarding issue concerning the network map readable through API ?

**Comment by Smanar** [comment]
>any evolution regarding issue concerning the network map readable through API

There is 2 Pr about that in waiting list, go make notification ^^

For your device, I have a problem, the device type = 0x00FF.
There is realy no way to chnage it for exemple in 0x0008 for "Range extender"

0x00FF mean "reserved", not fantastic to make something generic.

**Comment by samsam-rolon** [comment]
> 
> 
> > any evolution regarding issue concerning the network map readable through API
> 
> There is 2 Pr about that in waiting list, go make notification ^^
> 
> For your device, I have a problem, the device type = 0x00FF.
> There is realy no way to change it for exemple in 0x0008 for "Range extender" as the code is editable no ?
> 
> 0x00FF mean "reserved", not fantastic to make something generic.

I didn't see stuff like that in firmware ... :-(
I used this firmware : https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin

No matter, deCONZ GUI show it correctly so let's keep it like this !
