### ISSUE TITLE
Add firmware 266b0700 to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog

### ISSUE THREAD

**Issue by Bascht74** [dresden-elektronik/deconz-rest-plugin#4905]
## Describe the question or issue you are having
The information for firmware 266b0700 ist missing at https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog
Can you add the relevant information of the last stable release?

## Screenshots
![image](https://user-images.githubusercontent.com/66269310/119215714-d1747900-bacf-11eb-9612-158acca4d613.png)

## Environment
./.

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## deCONZ Logs
./.

## Additional context
Thx

**Comment by manup** [comment]
Done, added the missing entry was mixed up with 0x266c0700.

**Comment by Bascht74** [comment]
@manup Thx!

According to 
![image](https://user-images.githubusercontent.com/66269310/119224822-a5bdb700-bb00-11eb-8eff-ee0c2854a266.png)

...it is not a Beta-Version, but a stable one !?

Regards, 

Sebastian
