### ISSUE TITLE
All sensors with ID higher as the Daylight sensor not visible in the Phoscon app

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-rest-plugin#491]
The new Daylight sensor has the ID 14 for me. All sensor with ID higher then 14 are no longer visible in the Phoscon app.

**Comment by ebaauw** [comment]
I put the Daylight sensor on `/sensors/1` (just as the Hue bridge) and all my other sensors and switches show in Phoscon.  deCONZ v2.5.13.

**Comment by Krocko** [comment]
Strange. I am on deCONZ v2.5.14. 
First all sensors there visible in Phoscon, but after some seconds all sensors with ID higher 14 are gone.

**Comment by manup** [comment]
Indeed strange, I recon they are visible in REST-API?

Might be an Javascript exception thrown in Phoscon App during build of the sensors list.
Which browser do you using — if possible you can check the browser Javascript console if there is an exception error displayed?

**Comment by Krocko** [comment]
Yes, the sensors are all in the REST-API and in the GUI.
I use only the Safari browser on all my devices.
![phoscon fehler](https://user-images.githubusercontent.com/29394115/37565386-d47f7d44-2aa8-11e8-9a31-0dc8e0e1d59f.jpeg)

**Comment by manup** [comment]
Found the bug, I've updated the packages and http://dresden-elektronik.de/pwa may take a bit until browser does refresh the cache.

**Comment by Krocko** [comment]
Thank you Manuel. Problem solved.
