### ISSUE TITLE
Profalux roller shutters remotes not working if deCONZ is not running

### ISSUE THREAD

**Issue by codyzu** [dresden-elektronik/deconz-rest-plugin#4910]
## Describe the question or issue you are having

I successfully connected my Profalux roller shutters to deCONZ with a ConBee II. I'm still learning about zigbee, but I now understand that deCONZ with my ConBee II is now the "controller" for all of my shutter (screenshot below).

When I turn off my raspberry pi running deCONZ, the original remotes that came with the shutters don't work. Once I restart the raspberry pi and deCONZ, after some delay, they start working again.

After reading some of the Profalux documentation, they state that one of the shutters should be the controller.

My question is, does deCONZ (or the ConBee II) have to be the controller? Is it possible to re-program my network and make one of the shutters the controller and then have deCONZ (ConBee II) join the existing controller? Or is it possible to have 2 controllers (I'm guessing no)?

My motivation is that I would like the shutters to work even if I power down my raspberry pi. More specifically, if one day I move and disconnect the raspberry pi, I would like the existing remotes to still work.

## Screenshots

![image](https://user-images.githubusercontent.com/1464753/119313651-176a4200-bc74-11eb-8c98-9bc721787ff2.png)

## Environment

 - Host system: Raspberry Pi 3+
 - Running method: Raspbian (homebridge raspbian image + deCONZ)
 - Firmware version: 266e0700
 - deCONZ version: 2.11.5-beta
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## Additional context

* 2 Profalux roller shutters
* 3 Profalux remotes (1 dedicated to each shutter + 1 "global" remote that operates both shutters simultaneously)
* shutters -> ConBee II -> deCONZ -> homebridge -> homekit

**Comment by Smanar** [comment]
Hello, first you are right, you can't have 2 coordinators, and the conbee need to be the coordinator.

BTW, the working mode is strange for profalux, but something you can try, is set a direct bind with a remote and a shutters.
It s the "offline" working mode, the remote can send command direclty to the shutter.

You have a procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2077#issuecomment-554640916

Try to bind on/off and setlevel cluster

But idk how it will react.
- the remote is not supported by the API yet.
- the working mode for profalux is a little special.
