### ISSUE TITLE
Aqara E27 bulb ZNLDP12LM update firmware

### ISSUE THREAD

**Issue by SAOPP** [dresden-elektronik/deconz-rest-plugin#4919]
Hi! Guys, Aqara is released a new firmware for this bulbs, so several question about:

1. It's possible to update firmware of aqara via deconz?

2. Aqara added support for on/off for outage, like plugs, bulbs can no turn on when power is back.

So it's great news for owners, any comments about it?

At z2m side all of this steps is realized and support new feature for bulbs.

**Comment by Mimiix** [comment]
Hi,

As long as we have the firmware files, that would be doable afaik.
