### ISSUE TITLE
DeConz for Windows IoT

### ISSUE THREAD

**Issue by JAB33699** [dresden-elektronik/deconz-rest-plugin#492]
Hi,
does anyone feel like programming the deconz for windows iot on a Raspberry Pi?
I develop all my apps with C# and I would be happy to hear positives
Cheers  Jürgen

**Comment by MadMonkey87** [comment]
yes I do! I've provided a library that should support pretty much all features of DeConz, get it over here: https://github.com/MadMonkey87/InnerCore.Api.DeConz
