### ISSUE TITLE
unable to set a group to hidden

### ISSUE THREAD

**Issue by mistljo** [dresden-elektronik/deconz-rest-plugin#4927]
## Describe the bug
I'm not able to set a group to hidden.

## Steps to reproduce the behavior
create new group:
 
![image](https://user-images.githubusercontent.com/17146067/119558918-4da5df80-bda2-11eb-8584-81d726eecdaf.png)

read group:
![image](https://user-images.githubusercontent.com/17146067/119558953-572f4780-bda2-11eb-9710-677f96225d2d.png)

 
set hidden to group:
 
![image](https://user-images.githubusercontent.com/17146067/119558983-5eeeec00-bda2-11eb-9104-e55c598e99b3.png)

result:
 
![image](https://user-images.githubusercontent.com/17146067/119559062-77f79d00-bda2-11eb-9e79-3e346a39d32d.png)

## Expected behavior

the group should be hidden

## Environment
![image](https://user-images.githubusercontent.com/17146067/119559174-9eb5d380-bda2-11eb-82bd-ca61f0a845a3.png)

**Comment by SwoopX** [comment]
If I read the corresponding code correctly, this capability is reserved to Phoscon or requires a certain header been sent by the API client. Not sure if that is intended as it is...
