### ISSUE TITLE
Xiaomi Aqara D1 1-gang (neutral wire) - model: QBKG23LM

### ISSUE THREAD

**Issue by DBaker85** [dresden-elektronik/deconz-rest-plugin#4929]
## Device

- Product name: Xiaomi Aqara D1 1-gang neutral wire (2020 version)
- Manufacturer: Lumi
- Model identifier: lumi.switch.b1nacn02
- Device type : 
  - Light
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/11611885/119668748-bab78480-be37-11eb-8085-a2dfe187da99.png)

### Node clusters

![image](https://user-images.githubusercontent.com/11611885/119788017-0fa7d900-bed2-11eb-9585-199f9f28e197.png)

### Basic

![image](https://user-images.githubusercontent.com/11611885/119668823-cacf6400-be37-11eb-9f78-0616dc4b6d19.png)

### Identify

![image](https://user-images.githubusercontent.com/11611885/119668964-ec305000-be37-11eb-8322-5416cf322001.png)

### Device Temperature

![image](https://user-images.githubusercontent.com/11611885/119669072-05390100-be38-11eb-82ab-fe682c3e28a8.png)

### Groups

![image](https://user-images.githubusercontent.com/11611885/119669134-1550e080-be38-11eb-89e8-138619a07a78.png)

### Scenes

![image](https://user-images.githubusercontent.com/11611885/119669190-2568c000-be38-11eb-882c-d3a12d81d99f.png)

### On/Off

![image](https://user-images.githubusercontent.com/11611885/119669259-35809f80-be38-11eb-9e89-6607cb6c38ef.png)

### Mains Power outlet Analog input

![image](https://user-images.githubusercontent.com/11611885/119669558-711b6980-be38-11eb-870e-cc60e9018668.png)

### Meter Interface

![image](https://user-images.githubusercontent.com/11611885/119669741-960fdc80-be38-11eb-84f0-6a29bb17b779.png)

### on/off multistate input

![image](https://user-images.githubusercontent.com/11611885/119669862-af188d80-be38-11eb-948d-3cb6b316c98a.png)

**Comment by SwoopX** [comment]
Can you please add the screenshot of the node's clusters?

**Comment by DBaker85** [comment]
@SwoopX Update the request with the requested image. If there is anything else let me know. I wonder if the non neutral type would work...

**Comment by SwoopX** [comment]
@DBaker85 Sorry, this one seemed to have drowned... I prepared something, but I need some updated info to see if that's adequate or not. The screenshot of the analog input (basic) cluster for endpoint 03 is a duplicate. Can you please add a new one while the switch is turned on? I'd expect so have some power values there. Though probably negligible, please also add a screenshot from bionary output (basic) cluster of endpoint 05.

Would you be able to compile and test the code?

**Comment by DBaker85** [comment]
@SwoopX 
endpoint 3:
![image](https://user-images.githubusercontent.com/11611885/122893003-3547c700-d346-11eb-865a-97de8376cbed.png)


endpoint 5: 
![image](https://user-images.githubusercontent.com/11611885/122892725-edc13b00-d345-11eb-9b43-10ba03b838a7.png)

I should mention that the switch is not actually connected to a lamp. I am using it as a standalone control with no lights attached.
I have another laying around that I could jerry rig to a light if you need the values. 
I can also give it a shot at compiling and testing the code sure :)

**Comment by SwoopX** [comment]
You find the instructions how to compile here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4842#issuecomment-855288853

However, please use the following as the first 2 commands instead

```
git clone --branch=QBKG12LM https://github.com/swoopx/deconz-rest-plugin.git QBKG12LM       # Clone repository
cd ./QBKG12LM
```

**Comment by DBaker85** [comment]
Okay i'll give it try later today. Thanks for the build!

**Comment by DBaker85** [comment]
@SwoopX I tried to clone this branch, but the branch `QBKG12LM ` does not exist. 
Is this the correct branch name?
if yes, did you push your branch to git?

**Comment by SwoopX** [comment]
Oops, typo. Corrected the post.

**Comment by DBaker85** [comment]
Ok im running into some issues (I am not very well versed in linux)
So first of all I am running the os version of home assistant on an odroid xu4 (This seems to be based on alpine linux).
I tried installing deconz-dev or even getting a package for qmake to compile the code, but I cannot find them using apk and installs fail.

**Comment by SwoopX** [comment]
Ah, that makes thing rather complicated. I got no clue about HA, HASS and to get everything set up for compilation I'm afraid.

I can make the PR without having it tested, but that of course involves some uncertainty...

**Comment by DBaker85** [comment]
@SwoopX well if we have no other alternative (Other people that can help) that's fine I guess. It is working as a standard on/off switch right now (which is fine for me right now).
I can test with the released version

**Comment by SwoopX** [comment]
Keepalive
