### ISSUE TITLE
Smart switch in light group

### ISSUE THREAD

**Issue by RitaSghe** [dresden-elektronik/deconz-rest-plugin#4931]
## Describe the question or issue you are having

In my house I have 4 Vimar smart switch (19592.0).

https://faidate.vimar.com/it/it/catalog/product/index/code/19592

I couldn't find this switch in list supported devices and so I tried the pairing to send you the information, but the switch has been linked without problem.
The switch works fine, but is in the light group and not in the switch group.
It's a problem?

## Screenshots

![vimar](https://user-images.githubusercontent.com/81916825/119846364-5d403800-bf0a-11eb-813c-ba9072102d95.png)

## Environment
Host system: (Raspberry Pi)
Running method: (Raspbian)
Firmware version: (26660700)
deCONZ version: (2.11.05)
Device: (ConBee II)
Do you use an USB extension cable: (yes)
Is there any other USB or serial devices connected to the host system? If so: usb pen

**Comment by cllatser** [comment]
The switches connected to the electric light are in the lights group. It is right. Battery-powered buttons and controls will appear in the switch group.

**Comment by RitaSghe** [comment]
So, the switch are light and the button are switch ...
Funny way to subdivide the devices .....

**Comment by Smanar** [comment]
Lol, no it s logic it fact, it s based on how device react on zigbee network (router or end device) or their action on group.
Battery switches send command > sensor (or switch, switch is a subtype of sensor)
Wired switches receive command > light.
