### ISSUE TITLE
3 in 1 Remote Control - SUNRICHER - SR-ZG2858A

### ISSUE THREAD

**Issue by Hector47** [dresden-elektronik/deconz-rest-plugin#4936]
## Device

- Product name: SR-ZG2858A  [Product page](https://www.domadoo.fr/fr/peripheriques/5247-sunricher-telecommande-3-en-1-zigbee-30.html)

- Manufacturer: Sunricher
- Model identifier: ZG2858A
- Device type : 
  - Remote

## Screenshots

![endpoints](https://user-images.githubusercontent.com/394671/119973151-6afdc800-bfb3-11eb-900c-55ddbf51931a.PNG)
![node](https://user-images.githubusercontent.com/394671/119973326-a13b4780-bfb3-11eb-8f51-c160a90670b2.PNG)

### Basic
![Basic1](https://user-images.githubusercontent.com/394671/119973205-7d780180-bfb3-11eb-9c4a-e48dfaf26a40.PNG)
### Diagnostics
![diag1](https://user-images.githubusercontent.com/394671/119973469-d0ea4f80-bfb3-11eb-8368-5d55037bf111.PNG)
### Power Configuration
![powerconfiguration1](https://user-images.githubusercontent.com/394671/119973681-127afa80-bfb4-11eb-931e-41b5d0f48915.PNG)

### OTAU
![otau](https://user-images.githubusercontent.com/394671/119973797-35a5aa00-bfb4-11eb-983a-5629b08cd5eb.PNG)

**Comment by Hector47** [comment]
@SwoopX Can I use the same modification as #4995

**Comment by Hector47** [comment]
@SwoopX @manup is somethings missing?

**Comment by Mimiix** [comment]
@Hector47 Not in my view. However, devs need to implement this and  they rather have their hands on them. So it's a waiting game unfortunately.

**Comment by Hector47** [comment]
Hello

**Comment by Hector47** [comment]
Hello again

**Comment by Hector47** [comment]
Will I be able to add it with json Device Descriptor Files?

**Comment by Hector47** [comment]
Please Reopen

**Comment by Mimiix** [comment]
@Smanar

**Comment by Smanar** [comment]
But new devices are not blocked, waiting for DDF ?

**Comment by 35gh** [comment]
Hello - would it be possible to re-open this ticket? I'll be able to support with any information if needed. Thanks!

**Comment by Mimiix** [comment]
Sure

**Comment by Hector47** [comment]
Hello

**Comment by Smanar** [comment]
It seem battery switch can works with DDF, but I haven't succed yet.
Can make a try with this one. 

- Just drag and drop a ZHAswitch without config
- press a button, check in logs with "info" if you see an error message
- if not bind the cluster 0x0006, and remake a try (can need some time for the bind will be set, lazy device)

**Comment by Hector47** [comment]
Does someone has an exemple of DDF file I can use as a base?

**Comment by Smanar** [comment]
Haven't found one, and on my side I never suceed yet for battery switch.

Can start from scratch https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4936#issuecomment-1072592629
And share the DDF for someone can edit it.

And BTW you have an idea for the reason this device use 3 endpoint ?

**Comment by Hector47** [comment]
@Smanar i thinks it because you can create up to three light groups with the remote: the 1 2 and 3 button in the last row

**Comment by Hector47** [comment]
Hello - would it be possible to re-open this ticket? Thanks!

cc @Mimiix @Smanar

**Comment by Mimiix** [comment]
Sure!

**Comment by Smanar** [comment]
No one is able to start a DDF ? At least for some tests ?

**Comment by Hector47** [comment]
Hello - would it be possible to re-open this ticket? Thanks!

cc @Mimiix @Smanar

**Comment by Mimiix** [comment]
@Hector47 are you able to proceed on what @smanar asked?
