### ISSUE TITLE
PARKSIDE Smart Watering Timer PSBZS A1(LIDL)

### ISSUE THREAD

**Issue by ojcalvo** [dresden-elektronik/deconz-rest-plugin#4938]
## Device

- Product name: PARKSIDE Smart Watering Timer PSBZS A1
- Manufacturer: _TZE200_htnnfasr
- Model identifier: TS0601.
- Device type :  
   - Other: Smart watering timer

**Comment by Mimiix** [comment]
Missing screenshots.

Closing.

**Comment by ojcalvo** [comment]
![imagen](https://user-images.githubusercontent.com/71663670/120035012-32cfa700-bffe-11eb-86ad-9ae46dc4353d.png)
![imagen](https://user-images.githubusercontent.com/71663670/120035082-4f6bdf00-bffe-11eb-900e-961c5a2d72ab.png)

**Comment by Mimiix** [comment]
As the template suggests, please add all screenshots of all clusters.

This one remains closed. Please open another issue with all requested information.
