### ISSUE TITLE
Iris il021 keypad 

### ISSUE THREAD

**Issue by Abandonado** [dresden-elektronik/deconz-rest-plugin#4941]
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other:

**Comment by Mimiix** [comment]
Missing information.

Closing
