### ISSUE TITLE
Samotech temperature sensor (SM313)

### ISSUE THREAD

**Issue by RitaSghe** [dresden-elektronik/deconz-rest-plugin#4948]
## Describe the question or issue you are having
Today I connect one Samotech temperature sensor (SM313).
I have the device in the list of sensor (Multipurpose Sensor) but if I click on the device to change the name nothing's happening, it's is blocked and the temperature is integer and not decimal .....
What is the problem?

## Screenshots
![samotech](https://user-images.githubusercontent.com/81916825/120108110-fb7b0a80-c163-11eb-92fa-b7b080fc800f.png)

## Environment
Host system: (Raspberry Pi)
Running method: (Raspbian)
Firmware version: (26660700)
deCONZ version: (2.11.05)
Device: (ConBee II)
Do you use an USB extension cable: (yes)
Is there any other USB or serial devices connected to the host system? If so: usb pen

**Comment by cooper2k4** [comment]
I have the same sensor (SAMOTECH SM313 ZigBee-Sensor für Temperatur und Luftfeuchtigkeit from Amazon: https://www.amazon.de/dp/B08GZPJYYR/) and can confirm this.

No floating point output of temperature through Phoscon App but through API. I can see the exact temperature in ioBroker.

My problem ist that the battery status is not read correctly though.  It is on 0% right from the beginning. I could take the following screenshots (couldn't do the cluster info yet).

![grafik](https://user-images.githubusercontent.com/14296001/120830395-bd645900-c55e-11eb-9c96-ceb36960c927.png)

![grafik](https://user-images.githubusercontent.com/14296001/120830414-c2290d00-c55e-11eb-82a0-83df1d61674d.png)

**Comment by Smanar** [comment]
Hello, can you show the attribute table of the cluster 0x0001, the table on the bottom (need to press the read button, and making the device awake to fill it)

**Comment by cooper2k4** [comment]
Sorry for the delayed answer. I could only now get to the device to press the button. It's just a bit more of information. I hope that helps?

![grafik](https://user-images.githubusercontent.com/14296001/123542080-f5b71b80-d747-11eb-99b3-5e1c2ce3b5f6.png)

# Cluster 0000 Basic
![grafik](https://user-images.githubusercontent.com/14296001/123542108-0f586300-d748-11eb-986e-aea25a6c15ce.png)

# Cluster 0001 Power Configuration
![grafik](https://user-images.githubusercontent.com/14296001/123542136-28611400-d748-11eb-9896-f5b88b04986e.png)

# Cluster 0402 Temperature Measurement
![grafik](https://user-images.githubusercontent.com/14296001/123542191-842b9d00-d748-11eb-8aef-71bf28bd075c.png)

**Comment by Smanar** [comment]
IDK, all seem fine, the values was not updated when you have read thoses values ?
From the code, we are using the attribute 0x0021 by defaut.

By curisosity can you check if the reporting is working ?
Cluster 0x0001, attribute 0x0021, double clic on it, and "read config" on the new popup (but you will probably need to ake up the device in same time again)

Defaut values are
```
            rq.minInterval = 300;
            rq.maxInterval = 2700;
            rq.reportableChange8bit = 1;
```

**Comment by cooper2k4** [comment]
Attribute 0x0021 seems to be right, but the value only gets read while pressing the button on the sensor. After manually reading the attribute it also gets displayed in Hue Essentials App.

Reading and writing config says `UNSUP_GENERAL_COMMAND`

![grafik](https://user-images.githubusercontent.com/14296001/123543468-eab3b980-d74e-11eb-8dda-bde232329de8.png)

**Comment by Smanar** [comment]
Bad luck, I m sorry but I don't see how to retreive value if it don't support the command ?
Have tried to check on gooel to find information about "_TZ3000_1x1vtalf" nothing too.

Can you try to make a bind, without the reporting ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2077#issuecomment-554640916

**Comment by cooper2k4** [comment]
I wasn't able to do the bind. I'm confident with the current situation now. Humidity and temperature get read automatically and battery status if I press the button. It's just like with a Hue remote.

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?

**Comment by RitaSghe** [comment]
Do you have fix the problem of my first post?
