### ISSUE TITLE
GUI Restore 2.12.00 failed

### ISSUE THREAD

**Issue by funbirdcas** [dresden-elektronik/deconz-rest-plugin#4962]
## Describe the bug
I created a backup with Phoscon Web App and tried to restore it on another Windows System.
Everytime I got an error.

But when I install a previor deCONZ Version 2.11.5 on the second System the Restore works fine.
Is there a bug in 2.12.00 ?

## Screenshots

![fail](https://user-images.githubusercontent.com/79358006/120378758-1e9de980-c31f-11eb-9561-0c2260379a90.jpg)

## Environment

 - Host system: (Mini PC)
 - Running method: ((Windows 10 pro 21H1)
 - Firmware version: (266e0700)
 - deCONZ version: (2.12.00)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (no)
 - Is there any other USB or serial devices connected to the host system? (no)

## deCONZ Logs

19:52:32:879 HTTP API POST /api/fileupload - 192.168.178.40
19:52:32:880 form data
19:52:32:881 Failed to detect file upload end boundary
19:52:34:020 DB save zll database items 0x00000084
19:52:34:021 DB sql exec REPLACE INTO auth (apikey, devicetype, createdate, lastusedate, useragent) VALUES ('960ECFC235', 'Phoscon#B1920x969', '2021-06-01T17:52:17', '2021-06-01T17:52:33', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36')

19:52:34:026 DB sql exec REPLACE INTO sensors (sid, name, type, modelid, manufacturername, uniqueid, swversion, state, config, fingerprint, deletedState, mode) VALUES ('1', 'Daylight', 'Daylight', 'PHDL00', 'Philips', '00:00:00:00:00:00:00:00-01', '1.0', '{"dark":false,"daylight":true,"lastupdated":"2021-06-01T17:51:37.838","status":170,"sunrise":"2021-06-01T03:20:35","sunset":"2021-06-01T19:39:19"}', '{"configured":true,"lat":"51.501","long":"7.3371","on":true,"sunriseoffset":30,"sunsetoffset":-30}', '', 'normal', '1')

19:52:34:090 DB saved in 69 ms

**Comment by Smanar** [comment]
Can you try to run it in debug mode to have error ?
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags

**Comment by funbirdcas** [comment]
@Smanar 

I added debug logs

**Comment by Smanar** [comment]
And no more, it have stopped here ?
Try with
`deCONZ --dbg-info=2 --dbg-error=2`

**Comment by funbirdcas** [comment]
@Smanar 

OK, I've adjusted the debug level (--dbg-info=2 --dbg-error=2)



21:17:51:380 enqueue event config/localtime for /config/
21:17:52:384 enqueue event config/localtime for /config/
21:17:53:383 enqueue event config/localtime for /config/
21:17:54:379 enqueue event config/localtime for /config/
21:17:55:381 enqueue event config/localtime for /config/
21:17:56:380 enqueue event config/localtime for /config/
21:17:57:371 DB save zll database items 0x0000008E
21:17:57:371 DB sql exec REPLACE INTO auth (apikey, devicetype, createdate, lastusedate, useragent) VALUES ('060A0F019C', 'Phoscon#B1920x969', '2021-06-01T19:17:17', '2021-06-01T19:17:55', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36')
21:17:57:376 DB sql exec UPDATE config2 SET value = '2021-06-01T19:16:57' WHERE key = 'UTC';INSERT INTO config2 (key, value) SELECT 'UTC', '2021-06-01T19:16:57' WHERE (SELECT changes() = 0);
21:17:57:380 DB sql exec UPDATE config2 SET value = '45' WHERE key = 'announceinterval';INSERT INTO config2 (key, value) SELECT 'announceinterval', '45' WHERE (SELECT changes() = 0);
21:17:57:382 DB sql exec UPDATE config2 SET value = 'https://phoscon.de/discover' WHERE key = 'announceurl';INSERT INTO config2 (key, value) SELECT 'announceurl', 'https://phoscon.de/discover' WHERE (SELECT changes() = 0);
21:17:57:384 DB sql exec UPDATE config2 SET value = '2.12.00' WHERE key = 'apiversion';INSERT INTO config2 (key, value) SELECT 'apiversion', '2.12.00' WHERE (SELECT changes() = 0);
21:17:57:387 DB sql exec UPDATE config2 SET value = '0000000000000000' WHERE key = 'bridgeid';INSERT INTO config2 (key, value) SELECT 'bridgeid', '0000000000000000' WHERE (SELECT changes() = 0);
21:17:57:389 DB sql exec UPDATE config2 SET value = '93' WHERE key = 'datastoreversion';INSERT INTO config2 (key, value) SELECT 'datastoreversion', '93' WHERE (SELECT changes() = 0);
21:17:57:391 DB sql exec UPDATE config2 SET value = 'true' WHERE key = 'dhcp';INSERT INTO config2 (key, value) SELECT 'dhcp', 'true' WHERE (SELECT changes() = 0);
21:17:57:393 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'disablePermitJoinAutoOff';INSERT INTO config2 (key, value) SELECT 'disablePermitJoinAutoOff', 'false' WHERE (SELECT changes() = 0);
21:17:57:395 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'discovery';INSERT INTO config2 (key, value) SELECT 'discovery', 'false' WHERE (SELECT changes() = 0);
21:17:57:397 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'factorynew';INSERT INTO config2 (key, value) SELECT 'factorynew', 'false' WHERE (SELECT changes() = 0);
21:17:57:399 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'fwneedupdate';INSERT INTO config2 (key, value) SELECT 'fwneedupdate', 'false' WHERE (SELECT changes() = 0);
21:17:57:401 DB sql exec UPDATE config2 SET value = 'idle' WHERE key = 'fwupdatestate';INSERT INTO config2 (key, value) SELECT 'fwupdatestate', 'idle' WHERE (SELECT changes() = 0);
21:17:57:403 DB sql exec UPDATE config2 SET value = '0x00000000' WHERE key = 'fwversion';INSERT INTO config2 (key, value) SELECT 'fwversion', '0x00000000' WHERE (SELECT changes() = 0);
21:17:57:405 DB sql exec UPDATE config2 SET value = '127.0.0.1' WHERE key = 'gateway';INSERT INTO config2 (key, value) SELECT 'gateway', '127.0.0.1' WHERE (SELECT changes() = 0);
21:17:57:407 DB sql exec UPDATE config2 SET value = '65520' WHERE key = 'group0';INSERT INTO config2 (key, value) SELECT 'group0', '65520' WHERE (SELECT changes() = 0);
21:17:57:409 DB sql exec UPDATE config2 SET value = '50' WHERE key = 'groupdelay';INSERT INTO config2 (key, value) SELECT 'groupdelay', '50' WHERE (SELECT changes() = 0);
21:17:57:410 DB sql exec UPDATE config2 SET value = 'ZGVsaWdodDprYWk0ZXZlcg==' WHERE key = 'gwpassword';INSERT INTO config2 (key, value) SELECT 'gwpassword', 'ZGVsaWdodDprYWk0ZXZlcg==' WHERE (SELECT changes() = 0);
21:17:57:412 DB sql exec UPDATE config2 SET value = 'delight' WHERE key = 'gwusername';INSERT INTO config2 (key, value) SELECT 'gwusername', 'delight' WHERE (SELECT changes() = 0);
21:17:57:412 DB sql exec UPDATE config2 SET value = 'not-managed' WHERE key = 'homebridge';INSERT INTO config2 (key, value) SELECT 'homebridge', 'not-managed' WHERE (SELECT changes() = 0);
21:17:57:414 DB sql exec UPDATE config2 SET value = '' WHERE key = 'homebridge-pin';INSERT INTO config2 (key, value) SELECT 'homebridge-pin', '' WHERE (SELECT changes() = 0);
21:17:57:415 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'homebridgeupdate';INSERT INTO config2 (key, value) SELECT 'homebridgeupdate', 'false' WHERE (SELECT changes() = 0);
21:17:57:417 DB sql exec UPDATE config2 SET value = '' WHERE key = 'homebridgeupdateversion';INSERT INTO config2 (key, value) SELECT 'homebridgeupdateversion', '' WHERE (SELECT changes() = 0);
21:17:57:418 DB sql exec UPDATE config2 SET value = '' WHERE key = 'homebridgeversion';INSERT INTO config2 (key, value) SELECT 'homebridgeversion', '' WHERE (SELECT changes() = 0);
21:17:57:419 DB sql exec UPDATE config2 SET value = '192.168.178.40' WHERE key = 'ipaddress';INSERT INTO config2 (key, value) SELECT 'ipaddress', '192.168.178.40' WHERE (SELECT changes() = 0);
21:17:57:420 DB sql exec UPDATE config2 SET value = '60' WHERE key = 'lightlastseeninterval';INSERT INTO config2 (key, value) SELECT 'lightlastseeninterval', '60' WHERE (SELECT changes() = 0);
21:17:57:421 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'linkbutton';INSERT INTO config2 (key, value) SELECT 'linkbutton', 'false' WHERE (SELECT changes() = 0);
21:17:57:423 DB sql exec UPDATE config2 SET value = '2021-06-01T21:16:57' WHERE key = 'localtime';INSERT INTO config2 (key, value) SELECT 'localtime', '2021-06-01T21:16:57' WHERE (SELECT changes() = 0);
21:17:57:424 DB sql exec UPDATE config2 SET value = '38:60:77:7c:53:18' WHERE key = 'mac';INSERT INTO config2 (key, value) SELECT 'mac', '38:60:77:7c:53:18' WHERE (SELECT changes() = 0);
21:17:57:425 DB sql exec UPDATE config2 SET value = 'deCONZ' WHERE key = 'modelid';INSERT INTO config2 (key, value) SELECT 'modelid', 'deCONZ' WHERE (SELECT changes() = 0);
21:17:57:426 DB sql exec UPDATE config2 SET value = 'Phoscon-GW' WHERE key = 'name';INSERT INTO config2 (key, value) SELECT 'name', 'Phoscon-GW' WHERE (SELECT changes() = 0);
21:17:57:427 DB sql exec UPDATE config2 SET value = '255.0.0.0' WHERE key = 'netmask';INSERT INTO config2 (key, value) SELECT 'netmask', '255.0.0.0' WHERE (SELECT changes() = 0);
21:17:57:428 DB sql exec UPDATE config2 SET value = '180' WHERE key = 'networkopenduration';INSERT INTO config2 (key, value) SELECT 'networkopenduration', '180' WHERE (SELECT changes() = 0);
21:17:57:429 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'otauactive';INSERT INTO config2 (key, value) SELECT 'otauactive', 'false' WHERE (SELECT changes() = 0);
21:17:57:430 DB sql exec UPDATE config2 SET value = 'off' WHERE key = 'otaustate';INSERT INTO config2 (key, value) SELECT 'otaustate', 'off' WHERE (SELECT changes() = 0);
21:17:57:431 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'panid';INSERT INTO config2 (key, value) SELECT 'panid', '0' WHERE (SELECT changes() = 0);
21:17:57:432 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'permitjoin';INSERT INTO config2 (key, value) SELECT 'permitjoin', '0' WHERE (SELECT changes() = 0);
21:17:57:433 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'permitjoinfull';INSERT INTO config2 (key, value) SELECT 'permitjoinfull', '0' WHERE (SELECT changes() = 0);
21:17:57:434 DB sql exec UPDATE config2 SET value = '80' WHERE key = 'port';INSERT INTO config2 (key, value) SELECT 'port', '80' WHERE (SELECT changes() = 0);
21:17:57:434 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'portalservices';INSERT INTO config2 (key, value) SELECT 'portalservices', 'false' WHERE (SELECT changes() = 0);
21:17:57:435 DB sql exec UPDATE config2 SET value = 'none' WHERE key = 'proxyaddress';INSERT INTO config2 (key, value) SELECT 'proxyaddress', 'none' WHERE (SELECT changes() = 0);
21:17:57:436 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'proxyport';INSERT INTO config2 (key, value) SELECT 'proxyport', '0' WHERE (SELECT changes() = 0);
21:17:57:437 DB sql exec UPDATE config2 SET value = '1' WHERE key = 'rfconnect';INSERT INTO config2 (key, value) SELECT 'rfconnect', '1' WHERE (SELECT changes() = 0);
21:17:57:438 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'rfconnected';INSERT INTO config2 (key, value) SELECT 'rfconnected', 'false' WHERE (SELECT changes() = 0);
21:17:57:439 DB sql exec UPDATE config2 SET value = '1' WHERE key = 'rgbwdisplay';INSERT INTO config2 (key, value) SELECT 'rgbwdisplay', '1' WHERE (SELECT changes() = 0);
21:17:57:439 DB sql exec UPDATE config2 SET value = 'normal' WHERE key = 'runmode';INSERT INTO config2 (key, value) SELECT 'runmode', 'normal' WHERE (SELECT changes() = 0);
21:17:57:440 DB sql exec UPDATE config2 SET value = '' WHERE key = 'starterkitid';INSERT INTO config2 (key, value) SELECT 'starterkitid', '' WHERE (SELECT changes() = 0);
21:17:57:440 DB sql exec UPDATE config2 SET value = '6c3aa39b99a34f03ea6651191abfc93916fe7bbd' WHERE key = 'swcommit';INSERT INTO config2 (key, value) SELECT 'swcommit', '6c3aa39b99a34f03ea6651191abfc93916fe7bbd' WHERE (SELECT changes() = 0);
21:17:57:441 DB sql exec UPDATE config2 SET value = 'noupdates' WHERE key = 'swupdatestate';INSERT INTO config2 (key, value) SELECT 'swupdatestate', 'noupdates' WHERE (SELECT changes() = 0);
21:17:57:441 DB sql exec UPDATE config2 SET value = '2.12.00' WHERE key = 'swversion';INSERT INTO config2 (key, value) SELECT 'swversion', '2.12.00' WHERE (SELECT changes() = 0);
21:17:57:442 DB sql exec UPDATE config2 SET value = 'other' WHERE key = 'system';INSERT INTO config2 (key, value) SELECT 'system', 'other' WHERE (SELECT changes() = 0);
21:17:57:442 DB sql exec UPDATE config2 SET value = '24h' WHERE key = 'timeformat';INSERT INTO config2 (key, value) SELECT 'timeformat', '24h' WHERE (SELECT changes() = 0);
21:17:57:443 DB sql exec UPDATE config2 SET value = '' WHERE key = 'timezone';INSERT INTO config2 (key, value) SELECT 'timezone', '' WHERE (SELECT changes() = 0);
21:17:57:443 DB sql exec UPDATE config2 SET value = 'stable' WHERE key = 'updatechannel';INSERT INTO config2 (key, value) SELECT 'updatechannel', 'stable' WHERE (SELECT changes() = 0);
21:17:57:444 DB sql exec UPDATE config2 SET value = '{4c986425-8431-4a08-8a8a-4e7fe8fe1972}' WHERE key = 'uuid';INSERT INTO config2 (key, value) SELECT 'uuid', '{4c986425-8431-4a08-8a8a-4e7fe8fe1972}' WHERE (SELECT changes() = 0);
21:17:57:444 DB sql exec UPDATE config2 SET value = 'true' WHERE key = 'websocketnotifyall';INSERT INTO config2 (key, value) SELECT 'websocketnotifyall', 'true' WHERE (SELECT changes() = 0);
21:17:57:445 DB sql exec UPDATE config2 SET value = '443' WHERE key = 'websocketport';INSERT INTO config2 (key, value) SELECT 'websocketport', '443' WHERE (SELECT changes() = 0);
21:17:57:445 DB sql exec UPDATE config2 SET value = 'not-available' WHERE key = 'wifi';INSERT INTO config2 (key, value) SELECT 'wifi', 'not-available' WHERE (SELECT changes() = 0);
21:17:57:446 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wifibackupname';INSERT INTO config2 (key, value) SELECT 'wifibackupname', '' WHERE (SELECT changes() = 0);
21:17:57:447 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wifibackuppw';INSERT INTO config2 (key, value) SELECT 'wifibackuppw', '' WHERE (SELECT changes() = 0);
21:17:57:447 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wifibackuppwenc';INSERT INTO config2 (key, value) SELECT 'wifibackuppwenc', '' WHERE (SELECT changes() = 0);
21:17:57:448 DB sql exec UPDATE config2 SET value = '1' WHERE key = 'wifichannel';INSERT INTO config2 (key, value) SELECT 'wifichannel', '1' WHERE (SELECT changes() = 0);
21:17:57:448 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wificlientname';INSERT INTO config2 (key, value) SELECT 'wificlientname', '' WHERE (SELECT changes() = 0);
21:17:57:449 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wificlientpw';INSERT INTO config2 (key, value) SELECT 'wificlientpw', '' WHERE (SELECT changes() = 0);
21:17:57:449 DB sql exec UPDATE config2 SET value = '192.168.8.1' WHERE key = 'wifiip';INSERT INTO config2 (key, value) SELECT 'wifiip', '192.168.8.1' WHERE (SELECT changes() = 0);
21:17:57:450 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'wifilastupdated';INSERT INTO config2 (key, value) SELECT 'wifilastupdated', '0' WHERE (SELECT changes() = 0);
21:17:57:450 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'wifimgmt';INSERT INTO config2 (key, value) SELECT 'wifimgmt', '0' WHERE (SELECT changes() = 0);
21:17:57:451 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wifiname';INSERT INTO config2 (key, value) SELECT 'wifiname', '' WHERE (SELECT changes() = 0);
21:17:57:451 DB sql exec UPDATE config2 SET value = 'false' WHERE key = 'wifipageactive';INSERT INTO config2 (key, value) SELECT 'wifipageactive', 'false' WHERE (SELECT changes() = 0);
21:17:57:451 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wifipw';INSERT INTO config2 (key, value) SELECT 'wifipw', '' WHERE (SELECT changes() = 0);
21:17:57:452 DB sql exec UPDATE config2 SET value = '' WHERE key = 'wifipwenc';INSERT INTO config2 (key, value) SELECT 'wifipwenc', '' WHERE (SELECT changes() = 0);
21:17:57:452 DB sql exec UPDATE config2 SET value = 'accesspoint' WHERE key = 'wifitype';INSERT INTO config2 (key, value) SELECT 'wifitype', 'accesspoint' WHERE (SELECT changes() = 0);
21:17:57:453 DB sql exec UPDATE config2 SET value = '' WHERE key = 'workingname';INSERT INTO config2 (key, value) SELECT 'workingname', '' WHERE (SELECT changes() = 0);
21:17:57:453 DB sql exec UPDATE config2 SET value = '' WHERE key = 'workingpw';INSERT INTO config2 (key, value) SELECT 'workingpw', '' WHERE (SELECT changes() = 0);
21:17:57:454 DB sql exec UPDATE config2 SET value = '' WHERE key = 'workingpwenc';INSERT INTO config2 (key, value) SELECT 'workingpwenc', '' WHERE (SELECT changes() = 0);
21:17:57:454 DB sql exec UPDATE config2 SET value = '' WHERE key = 'workingtype';INSERT INTO config2 (key, value) SELECT 'workingtype', '' WHERE (SELECT changes() = 0);
21:17:57:455 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'zclvaluemaxage';INSERT INTO config2 (key, value) SELECT 'zclvaluemaxage', '0' WHERE (SELECT changes() = 0);
21:17:57:455 DB sql exec UPDATE config2 SET value = '0' WHERE key = 'zigbeechannel';INSERT INTO config2 (key, value) SELECT 'zigbeechannel', '0' WHERE (SELECT changes() = 0);
21:17:57:456 DB sql exec REPLACE INTO groups (gid, name, state, mids, devicemembership, lightsequence, hidden, type, class, uniqueid) VALUES ('0xFFF0', 'All', 'normal', '', '', '', 'false', 'LightGroup', 'Other', '')
21:17:57:457 DB sql exec REPLACE INTO sensors (sid, name, type, modelid, manufacturername, uniqueid, swversion, state, config, fingerprint, deletedState, mode) VALUES ('1', 'Daylight', 'Daylight', 'PHDL00', 'Philips', '00:00:00:00:00:00:00:00-01', '1.0', '{"dark":null,"daylight":null,"lastupdated":null,"status":null}', '{"configured":false,"on":true,"sunriseoffset":30,"sunsetoffset":-30}', '', 'normal', '2')
21:17:57:462 DB saved in 91 ms
21:17:57:474 enqueue event config/localtime for /config/
21:17:59:383 enqueue event config/localtime for /config/

**Comment by Smanar** [comment]
Oups sorry, I misunderstood, I need to use google translate for your error message.

**Comment by funbirdcas** [comment]
@Smanar 

> So ATM you can't restore an old backup on the last deconz version but it work on older.

=> exactly, the old Backup was created with 2.12.0

the attached log is generated while I'm trying to restore the file
Inside the Windows Application, Menu Bar -> Help -> Debugview.

Should I select more different debug Level ?

**Comment by SwoopX** [comment]
https://github.com/dresden-elektronik/phoscon-app-beta/issues/391
