### ISSUE TITLE
Swann Motion Sensor SWO-MOS1PA

### ISSUE THREAD

**Issue by 6c4491** [dresden-elektronik/deconz-rest-plugin#4971]
## Device

- Product name: Swann One Motion Sensor
- Manufacturer: SwannONe
- Model identifier: SWO-MOS1PA
- Device type: 
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/72370064/120575602-4d988600-c419-11eb-96cf-1bb1c9b06a68.png)

### Basic
![image](https://user-images.githubusercontent.com/72370064/120575386-e5e23b00-c418-11eb-9a40-ecd0e201d349.png)

### Identify
![image](https://user-images.githubusercontent.com/72370064/120575090-589ee680-c418-11eb-8a3a-f374024fefef.png)

### Device Temperature
![image](https://user-images.githubusercontent.com/72370064/120575168-74a28800-c418-11eb-8370-37d3bc565eeb.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/72370064/122126739-161ed600-ce2a-11eb-89f9-9231bbd27830.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/72370064/122126707-0901e700-ce2a-11eb-831d-16a877465dcb.png)

**Comment by SwoopX** [comment]
IAS Zone cluster is missing and the attributes for the power configuration cluster have not been read. Can you please update the screenshots accordingly?

**Comment by 6c4491** [comment]
Updated, hopefully that's right

**Comment by SwoopX** [comment]
Yes, it is, thanks but similarly unexpected.

Would you be able to compile a test version of the plugin?

**Comment by 6c4491** [comment]
I can definitely try work out how to do so

**Comment by 6c4491** [comment]
I think I have the test version set up correctly, what do I need to do next?

**Comment by SwoopX** [comment]
If that's a version containing my code changes, just reset and re-pair the device. Afterwards, the device should work.
