### ISSUE TITLE
Iris il02_1

### ISSUE THREAD

**Issue by Abandonado** [dresden-elektronik/deconz-rest-plugin#4974]
## Device

-Product name: Iris il02_1 keypad
Manufacturer: Imagic by GreatStar
Model identifier: 1112-S
Device type :
Lock
Remote
Other: 
![20210604_192440](https://user-images.githubusercontent.com/70747895/120846006-d9bdc100-c571-11eb-9ae9-c472e02c20d2.jpg)
![20210604_192550](https://user-images.githubusercontent.com/70747895/120846012-db878480-c571-11eb-9248-f7220b373301.jpg)
![20210604_193014](https://user-images.githubusercontent.com/70747895/120846015-dcb8b180-c571-11eb-9621-934e3b266c72.jpg)

**Comment by Smanar** [comment]
Hello, have you a linux machine to test code modification ?

**Comment by Abandonado** [comment]
First sorry for my incomplete previous posts. I do not have much experience. What I use is Hassio in a nuc. Thanks

**Comment by Smanar** [comment]
If you can add the device node picture ? (It's the naode with the cluster list)
After I have enought information to make something, but 
- the first keypad support is still in waiting list.
- If you can't compile the code, there is no way to test it ATM.

You don't have a small raspberry or a good VM ?
It s possible on docker, but I prefer let this method for user with more experience.

**Comment by Abandonado** [comment]
Tomorrow I send the capture that you request. I have no access but the nuc, sorry. And little experience since I just started in this world. Thanks for your help beforehand

**Comment by Abandonado** [comment]
![20210604_221853](https://user-images.githubusercontent.com/70747895/120858372-fdd5ce00-c582-11eb-9edf-719a47e57519.jpg)
Is this?

**Comment by Smanar** [comment]
Yep exactly, thx.
Will take a look tomorow if I can add it in blind mode, but without guarranty.

**Comment by Abandonado** [comment]
Ok very thanks

**Comment by Smanar** [comment]
Bad luck, have started to include it https://github.com/Smanar/deconz-rest-plugin/tree/keypad_1112-S
But this device have some extra features, no in code yet, so I relay need to test it first.

For the moment, I can explain how to compile it, but I realy need someone that can compile code.

There is a procedure for docker, but I can help you for this one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4841#issuecomment-852157541

**Comment by Abandonado** [comment]
Okay. Thank you very much for your interest. I'm really very new to this. I'll find someone who has docker to see if they help me with this, since I don't know how it works.
