### ISSUE TITLE
Lights: Setting brightness to zero falsely sets "on" to false

### ISSUE THREAD

**Issue by jonatanolofsson** [dresden-elektronik/deconz-rest-plugin#498]
Setting my (tradfri) light to brightness zero yields the following result on the websocket (2.05.12): 

```
{"e":"changed","id":"1","r":"lights","state":{"on":false},"t":"event"}
{"e":"changed","id":"1","r":"lights","state":{"bri":0},"t":"event"}
{"e":"changed","id":"1","r":"lights","state":{"bri":1},"t":"event"}
```

The light remains on, at the lowest brightness as expected*.

\* Well, at least if anything except being actually off.

**Comment by GregWoods** [comment]
I think is a problem with the Tradfri gateway API. Setting the brightness should set the persisted brightness value, and not affect the lamp on/off state. But instead setting brightness to 0 turns the map off, and non-zero turns it on.
The behaviour would only make sense if there were no "on" property. The fact the API has "on" (boolean) implies that on/off is independent to brightness. Unfortunately this doesn't seem to be the case.
Note: my experiments have centred around node-red and tradfri, but the results are the same.
