### ISSUE TITLE
Atmos Edition- Xiaomi Aqara Temperature Humidity

### ISSUE THREAD

**Issue by ThomasWelzel** [dresden-elektronik/deconz-rest-plugin#499]
Hello,

I installed the Xiaomi sensors today and the temperature and pressure values seem to be correct. 

But I don't know exactly what the humidity value is.

<img width="267" alt="bildschirmfoto 2018-03-21 um 14 28 01" src="https://user-images.githubusercontent.com/5394007/37712572-9410a62a-2d14-11e8-9a62-e710e7a278f4.png">
<img width="261" alt="bildschirmfoto 2018-03-21 um 14 28 14" src="https://user-images.githubusercontent.com/5394007/37712573-94342186-2d14-11e8-8723-f3090fbdd88e.png">
<img width="251" alt="bildschirmfoto 2018-03-21 um 14 28 23" src="https://user-images.githubusercontent.com/5394007/37712574-946de830-2d14-11e8-9be7-45ca242fa441.png">
<img width="265" alt="bildschirmfoto 2018-03-21 um 14 31 52" src="https://user-images.githubusercontent.com/5394007/37712596-a2be8d54-2d14-11e8-9d6e-0f843e6f5ac4.png">

**Comment by ThomasWelzel** [comment]
also the battery value is not there

**Comment by ThomasWelzel** [comment]
<img width="629" alt="bildschirmfoto 2018-03-21 um 14 57 35" src="https://user-images.githubusercontent.com/5394007/37713797-460e68c8-2d18-11e8-972d-3696c9fbd032.png">

**Comment by ebaauw** [comment]
As per ZCL spec, humidity is in 0.01% (temperature in 0.01 degrees Celsius and pressure in hPa).  It might take up to an hour for the sensor reports its battery state.

**Comment by ThomasWelzel** [comment]
But for boath sensors the 1 - x% is better than the  value for the humidity. The sended values are too Low.
