### ISSUE TITLE
Tuya _TZ3000_vp6clf9d TS0044 4 buttons scene switch

### ISSUE THREAD

**Issue by kurcsics** [dresden-elektronik/deconz-rest-plugin#4994]
## Device

- Product name: Tuya 4 buttons scene switch
- Manufacturer: _TZ3000_vp6clf9d
- Model identifier: TS0044
- Device type :   - Switch

## Screenshots
![Képernyőkép 2021-06-06 090240](https://user-images.githubusercontent.com/46639875/121561766-1594d280-ca19-11eb-8d69-7aa94635013b.png)
![Képernyőkép 2021-06-06 090352](https://user-images.githubusercontent.com/46639875/121561777-175e9600-ca19-11eb-9aa9-75fe2b5217e1.png)

### Basic
try with 12.0
Switch not present in switch editor.

**Comment by Smanar** [comment]
He is not present in switch editor, but he is not visible in the API ?
Try with looking in http://phoscon.de/pwabeta in help/api Information.

Tuya device can need 2 inclusions without deleting the previous entry.

**Comment by kurcsics** [comment]
![4](https://user-images.githubusercontent.com/46639875/121565677-fb5cf380-ca1c-11eb-8864-c339d50f2cd5.png)
![5](https://user-images.githubusercontent.com/46639875/121565684-fc8e2080-ca1c-11eb-860c-b0981b8c9853.png)
![6](https://user-images.githubusercontent.com/46639875/121565694-0021a780-ca1d-11eb-95d8-7a1b579755e6.png)
![7](https://user-images.githubusercontent.com/46639875/121565701-01eb6b00-ca1d-11eb-9beb-3b81b28819ae.png)
![8](https://user-images.githubusercontent.com/46639875/121565709-031c9800-ca1d-11eb-9475-d6e004f60925.png)

**Comment by Smanar** [comment]
So the device is working, "buttonevent" change, the problem is more from phoscon side https://github.com/dresden-elektronik/phoscon-app-beta/issues
