### ISSUE TITLE
Sunrichter CCT Zigbee Touch Remote Controller

### ISSUE THREAD

**Issue by kurcsics** [dresden-elektronik/deconz-rest-plugin#4995]
## Device

- Product name: CCT Zigbee Touch Remote Controller
- Manufacturer: Sunrichter
- Model identifier: ZGRC-TEUR-004
- Device type :   - Switch

## Screenshots
![1](https://user-images.githubusercontent.com/46639875/121562813-1c701500-ca1a-11eb-9280-d7cdd789610d.png)
![2](https://user-images.githubusercontent.com/46639875/121562821-1e39d880-ca1a-11eb-8078-98c4b4b85170.png)
![3](https://user-images.githubusercontent.com/46639875/121563556-cea7dc80-ca1a-11eb-8afe-184578276624.png)

### Basic
try with 12.0
Switch not present in switch editor.

**Comment by Mimiix** [comment]
Is it working with deconz rest api tho?

**Comment by kurcsics** [comment]
Hi,
Its not working in Api, no buttonevent. 
![42D69A3F-2343-42E1-99EB-D625D7DCD4DC](https://user-images.githubusercontent.com/46639875/121625662-2de60b00-ca74-11eb-8a8b-80c784b9a94b.png)

**Comment by Mimiix** [comment]
Can you check "event"?

**Comment by kurcsics** [comment]
I have checked it, No event…

**Comment by SwoopX** [comment]
For the button events, you could try adding your model ID to the `iluminizeMap` button map in file `button_maps.json`. The line should then look like this:

`"modelids": ["ZGRC-TEUR-003", "ZGRC-TEUR-004"],`

For the switch editor, you need to move over to phoscon beta repository.

**Comment by kurcsics** [comment]
Thanks, its Work in API
