### ISSUE TITLE
Extending to full HA profile

### ISSUE THREAD

**Issue by sjlb197** [dresden-elektronik/deconz-rest-plugin#5]
This isn't an issue, so my apologies if this isn't the correct place to raise this question.

I would like to use my RaspBee module to control HA profile thermostatic radiator valves (thermostat and temperature measurement clusters).  I'm using OpenRemote at the moment to communicate over the REST API to deCONZ, and so I have a question about how best to communicate with my radiator valves.

Am I going to be able to extend the REST API to support my devices, or might I be better off using the C++ API to deCONZ?

Many thanks in advance for any assistance.

**Comment by ktching** [comment]
Hi Steve & Manuel,

I'm reading your convo with much interest as I just got my Raspbee. Works with deCONZ REST API plugin nicely. 

However, I am also looking to extend the API beyond just lights to switches, motion sensors and door sensors. 

I have to admit it felt hopeless until I chanced upon this thread. Looks like it's possible! 

Was wondering if there is some documentation available somewhere with step-by-step guide? Many thanks in advance!

Regards,
Keith

**Comment by danieljkemp** [comment]
Hi Steve,

Your last update made it look like you were just one step away from a functional addition. any chance you could submit a pull request? Even if it wasn't accepted the changes would be listed and it would be a great help to people looking to add functionality!

**Comment by sjlb197** [comment]
I'm afraid I'm very much further away than that ... Work and life have prevented me from making any progress ... The issues I was having were initial issues trying to get anything working, so whatever I had was in the very early stages.

Apologies,

Steve

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
