### ISSUE TITLE
Aqara high precision motion sensor (RTCGQ13LM)

### ISSUE THREAD

**Issue by vinhthaipham** [dresden-elektronik/deconz-rest-plugin#5003]
Hi,
i am running deconz with RPI 3.
i manage to buy one from internet, 
https://www.reddit.com/r/Aqara/comments/kksfnw/quick_test_aqara_high_precision_motion_sensor/
but couldnt add it to deconz as it has not been there.
need some help to guideon how to manual add (source code) then recompile.
Thanks !!!

## Device

- Product name: aqara high precision motion sensor.
- Manufacturer: Aqara (Lumi)
- Model identifier: RTCGQ13LM or  lumi.motion.agl04
- Device type : 

  - Sensor

### Basic
![image](https://user-images.githubusercontent.com/30033935/122154045-5879fe80-ce8e-11eb-9230-2bd4661be427.png)

### Identify
![image](https://user-images.githubusercontent.com/30033935/122153689-af330880-ce8d-11eb-83db-5c889ee289c8.png)

### Power Config
![image](https://user-images.githubusercontent.com/30033935/122153658-9e829280-ce8d-11eb-98b2-65a012103ad8.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/30033935/122153586-80b52d80-ce8d-11eb-9dd4-a111e0a2c1a5.png)
### Atributes
![image](https://user-images.githubusercontent.com/30033935/122153803-e9040f00-ce8d-11eb-9edc-b030e58152ec.png)
![image](https://user-images.githubusercontent.com/30033935/122153849-ff11cf80-ce8d-11eb-9e43-084f635a2f46.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/30033935/122153532-69764000-ce8d-11eb-804e-7bb6a67ba8ea.png)

**Comment by Mimiix** [comment]
You need to have it added to deconz and have the screenshots to get it supported.

**Comment by vinhthaipham** [comment]
thanks! I will do so

**Comment by vinhthaipham** [comment]
any help please!

**Comment by SwoopX** [comment]
The attributes are all on their defaults. you must read them while the device is awake. You can wake it up by pressing the physical button on it while hitting read within the following 1 - 3 secs.

**Comment by SwoopX** [comment]
See #5109
