### ISSUE TITLE
Loading backup failed

### ISSUE THREAD

**Issue by chris58008** [dresden-elektronik/deconz-rest-plugin#5016]
## Describe the bug

When trying to restore a backup from a raspbee (2.05.64 / 4/22/2019)  (Firmware 26330500)
to a fresh install on windows (2.12.00 / 5/9/2021) (Firmware 26580700)

I get the error message 

Loading backup failed
! 

## Screenshots

![image](https://user-images.githubusercontent.com/85893534/121925398-2ad17000-cd3d-11eb-84a3-6c4ade42431c.png)

## Environment

 - Host system: (PC)
 - Running method: (Windows 10 21H1)
 - Firmware version: (26580700)
 - deCONZ version: 2.12.00 )
 - Device: (ConBee II)
 - Do you use an USB extension cable: (no) 
 - Is there any other USB or serial devices connected to the host system? no

**Comment by SwoopX** [comment]
Duplicate #4962

**Comment by SwoopX** [comment]
Duplicate #4962
