### ISSUE TITLE
Remote Hue API open for registration

### ISSUE THREAD

**Issue by mysteryan** [dresden-elektronik/deconz-rest-plugin#503]
How difficult would it be to forward requests/responses natively to Phillips remote hue api (provides broader cross compatibility) now that they have opened up registration? https://developers.meethue.com/documentation/remote-hue-api

**Comment by manup** [comment]
Not possible since the Philips remote hue API does very likely only work with hue bridges. There is a point on the roadmap that a remote API for deCONZ will be available via WebRTC sometime.
