### ISSUE TITLE
Immax Magnetic Window and Door Sensor

### ISSUE THREAD

**Issue by Thoky81** [dresden-elektronik/deconz-rest-plugin#5034]
## Device

- Product name: Magnetic Window and Door Sensor
- Manufacturer: Immax
- Model identifier: DoorWindow-Sensor-ZB3.0
- Device type :
  - Sensor

### Basic

![Screenshot 2021-06-20 at 21 34 45](https://user-images.githubusercontent.com/27979225/122686134-fd3e6800-d20f-11eb-834c-a98e01f7ed8c.jpg)

### Node Info

![Screenshot 2021-06-20 at 21 38 20](https://user-images.githubusercontent.com/27979225/122686146-0deede00-d210-11eb-9d8e-e1d79ad87790.jpg)

### Power Configuration

![Screenshot 2021-06-20 at 21 34 54](https://user-images.githubusercontent.com/27979225/122686150-1515ec00-d210-11eb-8e97-80bf5080bd62.jpg)

### Identify

![Screenshot 2021-06-20 at 21 35 11](https://user-images.githubusercontent.com/27979225/122686156-1ba46380-d210-11eb-9139-2fbd0e3f453a.jpg)

### Pool Control

![Screenshot 2021-06-20 at 21 35 24](https://user-images.githubusercontent.com/27979225/122686163-23640800-d210-11eb-97bf-29630a55fcad.jpg)

### IAS Zone

![Screenshot 2021-06-20 at 21 37 54](https://user-images.githubusercontent.com/27979225/122686168-2959e900-d210-11eb-8344-52591e6e4a4e.jpg)

### Diagnostics

![Screenshot 2021-06-20 at 21 38 05](https://user-images.githubusercontent.com/27979225/122686171-31b22400-d210-11eb-8e44-bef29ac9bcb2.jpg)

### OTAU

![Screenshot 2021-06-20 at 21 41 21](https://user-images.githubusercontent.com/27979225/122686205-4989a800-d210-11eb-909b-8275775d63f9.jpg)

### Other

![Screenshot 2021-06-20 at 21 42 04](https://user-images.githubusercontent.com/27979225/122686241-602fff00-d210-11eb-8005-e1e02f52c14e.jpg)

### Note

I found this device also here: https://zigbee.blakadder.com/Immax_07045L.html

**Comment by SwoopX** [comment]
The attributes must have been read for all clusters, otherwise the screenshots are useless I'm afraid. Can you please update?

**Comment by Thoky81** [comment]
I tried to do it but no success. I have also tried to wake up sensor by moving the magnet.

**Comment by Thoky81** [comment]
So I have removed the battery and added the sensor again and looks like success. Please find above updated pictures. The sensor is not visible in phoscon app but this time I can see it also in Home Assistant.

**Comment by SwoopX** [comment]
You see me positively suprised as the device is not explicitly supported, but benefits from a fallback mechanism 😄 

Should be fully functional though, except for battery reporting.

**Comment by Thoky81** [comment]
Looks like the battery is reporting in HA but is strangely low. I will try to change it later just to see if report will change too.

![image](https://user-images.githubusercontent.com/27979225/122688935-a93b7f80-d21f-11eb-8c12-b62ff03cda4e.jpeg)

**Comment by Thoky81** [comment]
I tried to change the battery but in fact the sensor is not changing any of the states in HA anymore. Can you include the support for the sensor in next beta pls?

**Comment by Thoky81** [comment]
I have updated to version beta 2.12.3 where the sensors should have support according to release notes but its not showing up in Phoscon. Any idea pls?

**Comment by Mimiix** [comment]
If you see devices within deCONZ but not in Phoscon, that is most of the time perfectly normal. Phoscon is closed source and needs devices to be added manually by their developer. However, the device will still be usable with the API/Home-Assistant/OpenHAB etc. You may want to go ahead and request support for your device at the Phoscon repo

**Comment by Thoky81** [comment]
Thanks. 
I found another problem. When I removed the device from deconz I am unable to pair it again and that is strange since it should be already supported in 2.12.3.

**Comment by Thoky81** [comment]
.. The device is showing as some unknown item.
