### ISSUE TITLE
Anyway to set outdoor temp for Sinope Thermostat ?

### ISSUE THREAD

**Issue by matlafqc** [dresden-elektronik/deconz-rest-plugin#5036]
## Describe the question or issue you are having
I use Sinope TH1123ZB and I want to set the outdoor temperature value of the thermostat. I don't see any entity in HA to set the value. If I check deconz, I see the value but it's readonly. Can this be supported by deconz and HA integration ? Thanks.

## Screenshots
![image](https://user-images.githubusercontent.com/23243794/122653924-0814d200-d116-11eb-8d1a-427cd4be407b.png)

## Environment
 - Host system: Synology 
 - Running method: Marthoc Docker container
 - Firmware version: 266b0700
 - deCONZ version: 2.11.5
 - Device: ConBee II
 - Do you use an USB extension cable:  Yes
 - Is there any other USB or serial devices connected to the host system? If so: No

**Comment by SwoopX** [comment]
I assume you're looking at the wrong place. You're trying to change a general attribute on the thermostat cluster which is not changeable. Try the `Sinope specific` cluster.

**Comment by matlafqc** [comment]
Thanks ! I see the attribute and it's settable. How this king of attribute is exposed outside deconz, like to HA ?

**Comment by BabaIsYou** [comment]
This cluster seems not accessible thru rest API.
