### ISSUE TITLE
deconz on Debian bullseye amd64

### ISSUE THREAD

**Issue by matthiasklein** [dresden-elektronik/deconz-rest-plugin#5040]
## Describe the question or issue you are having

I am currently trying to install the ConBee2 stick under Debian bullseye amd64.

Apparently there are no packages for bullseye.
Is there a way to use the ConBee2 stick natively (without Docker) under Debian bullseye anyway?

## Environment

Debian GNU/Linux 11 (bullseye)
Linux 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux

**Comment by SwoopX** [comment]
https://deconz.dresden-elektronik.de/debian/

**Comment by matthiasklein** [comment]
@SwoopX Thank you for the link. But there are only arm64 packages, and no amd64 packages.

But from there I found the ubuntu downloads: https://deconz.dresden-elektronik.de/ubuntu/stable/
It looks like they are working on Debian bullseye too.

**Comment by SwoopX** [comment]
Ah, my bad. If you do it "in a rush", you don't catch the subtle differences between the archs 😄 Glad it worked out. Mind closing this one?

**Comment by matthiasklein** [comment]
I think using the Ubuntu packages under Debian is not a permanent solution. As a workaround to test deconz OK, but in the long run it rather leads to a FrankenDebian.

So I would like to leave this issue open to encourage building amd64 packages for Debian besides arm64 packages.

**Comment by Red-M** [comment]
I've run into this too, I should be able to use those packages under debian, but they're all arm64. Can't even use them on a RPi either because they're armhf and not arm64 so the inclusion of the amd64 arch would be appreciated

**Comment by Siggi0904** [comment]
Hi, here the same.

Upgraded my system from buster to bullseye and got the same error.
Please release a bullseye target for Debian.

With Ubuntu is this a seperate port und should be released seperately.

As far rpi will release debian bullseye port, it is needed too,

Thanks.

**Comment by olicooper** [comment]
+1 for bullseye port on rpi 👍 🙏 .. 

```log
pi@rpi4:~ $ sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Ign:2 http://phoscon.de/apt/deconz bullseye-beta InRelease
Err:3 http://phoscon.de/apt/deconz bullseye-beta Release
  404  Not Found [IP: 144.76.96.194 80]
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
E: The repository 'http://phoscon.de/apt/deconz bullseye-beta Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by pdelrot-samea** [comment]
Hello. I just have the same needs as the others, and the same result as olicooper.
bullseye support will be appreciated !
BR,
Pascal

**Comment by trevon88** [comment]
Still no workaround? ....

Also would like to have a Bullseye edition, please!

Thank you!

**Comment by shinepixel** [comment]
The current beta now supports Bullseye:

```
deb http://phoscon.de/apt/deconz bullseye-beta main
```

Thank you *deCONZ* team!

**Comment by Bias313** [comment]
Is bullseye still not in stable?

**Comment by pdelrot-samea** [comment]
Hello,
WIth (or without trusted) this line I got a "no public signature error".

```
pi@raspberrypi-pascal:~ $ more /etc/apt/sources.list.d/deconz.list 
deb [trusted=yes] http://phoscon.de/apt/deconz bullseye main
```

```
pi@raspberrypi-pascal:~ $ sudo apt update
Atteint :1 http://security.debian.org/debian-security bullseye-security InRelease
Atteint :2 http://deb.debian.org/debian bullseye InRelease                                              
Atteint :3 http://deb.debian.org/debian bullseye-updates InRelease                                      
Réception de :4 http://phoscon.de/apt/deconz bullseye InRelease [2 873 B]                               
Atteint :5 http://archive.raspberrypi.org/debian bullseye InRelease                                     
Ign :4 http://phoscon.de/apt/deconz bullseye InRelease                                                  
2 873 o réceptionnés en 1s (2 068 o/s)
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Tous les paquets sont à jour.
W: Erreur de GPG : http://phoscon.de/apt/deconz bullseye InRelease : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY C9A78F8C43D8720A
```

It's a fresh RPi OS 64 bits, on a RPi4. Few weeks ago a RPi OS / Debian buster with deconz and HomeAutomation where installed on it since months.

Do someone has been able to install deconz on bullseye ?

Thanks,
Pascal

**Comment by night-gold** [comment]
Just living a comment here to say that this is still not fixed... There is still no packages for debian and the repo configuration working on older version of debian (buster) does not work anymore. Still no amd64 files in the debian repo.

**Comment by Mimiix** [comment]
@manup can you leave a response?

**Comment by manup** [comment]
The Debian/Bullseye APT repository is not yet referenced, you can install manually by using the Ubuntu package package:

```
wget http://deconz.dresden-elektronik.de/ubuntu/beta/deconz-2.22.00-qt5.deb
sudo dpkg -i deconz-2.22.00-qt5.deb
```

**Comment by jvarrone** [comment]
> 

This doesn't work on debian. the .sh files for setup and running still reference the ubuntu o/s.
