### ISSUE TITLE
Current Products Corp E-Wand WIndow Covering

### ISSUE THREAD

**Issue by RMCob** [dresden-elektronik/deconz-rest-plugin#5041]
## Device

- Product name: E-Wand Gen II
- Manufacturer: Current Products Corp
- Model identifier: E-Wand
- Device type : Window Covering
 
### Node
![NodeInfo](https://user-images.githubusercontent.com/49130485/122816893-455b9a00-d2a5-11eb-926a-fa03f195f57a.png)

### Endpoint
![EndpointInfo](https://user-images.githubusercontent.com/49130485/123559733-dcc06180-d76b-11eb-9ee4-f93f545cb22c.png)

### Basic
![BasicCluster](https://user-images.githubusercontent.com/49130485/122816945-52788900-d2a5-11eb-8d53-c1df418f7b98.png)

### Power Config
![PowerConfigCluster](https://user-images.githubusercontent.com/49130485/122817158-966b8e00-d2a5-11eb-896f-d7e576dc5243.png)

### Identify
![IdentifyCluster](https://user-images.githubusercontent.com/49130485/123559746-f82b6c80-d76b-11eb-8b55-f3066d44a6a5.png)

### Groups
![GroupsCluster](https://user-images.githubusercontent.com/49130485/123559759-09747900-d76c-11eb-8fe0-2d9ff7ce009b.png)

### On/Off
![OnOffCluster](https://user-images.githubusercontent.com/49130485/122817033-7045ee00-d2a5-11eb-922f-b1d809374533.png)

### Level Control
![LevelControl](https://user-images.githubusercontent.com/49130485/123559775-2741de00-d76c-11eb-8e47-73a45d7b4c8f.png)

### Poll Control
![PollControlCluster](https://user-images.githubusercontent.com/49130485/122817285-b733e380-d2a5-11eb-9ef4-9b216571fbf2.png)

### Window Covering
![WindowCoveringCluster](https://user-images.githubusercontent.com/49130485/122817331-c61a9600-d2a5-11eb-99e5-422b2766defb.png)

### Diagnostics
![Diagnostics pt1](https://user-images.githubusercontent.com/49130485/123559791-39bc1780-d76c-11eb-90e5-dd6738a86041.png)
![Diagnostics pt2](https://user-images.githubusercontent.com/49130485/123559794-40e32580-d76c-11eb-8053-24fc3e8113c6.png)

#### OTAU
![OTAUcluster](https://user-images.githubusercontent.com/49130485/122817388-d763a280-d2a5-11eb-8f3d-030c08129421.png)

**Comment by manup** [comment]
Related PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5068

**Comment by RMCob** [comment]
Keep active

**Comment by RMCob** [comment]
Keep active

**Comment by RMCob** [comment]
Keep active

**Comment by RMCob** [comment]
Keep active
