### ISSUE TITLE
EasyAccess door lock

### ISSUE THREAD

**Issue by troelde** [dresden-elektronik/deconz-rest-plugin#5042]
## Device

- Product name: EasyCodeTouch
- Manufacturer: Onesti Products AS
- Model identifier: easyCodeTouch_v1
- Device type : 
  - Lock

## Screenshots
![image](https://user-images.githubusercontent.com/2117565/122817641-73a69d00-d2d8-11eb-841a-56ef75b29570.png)

![image](https://user-images.githubusercontent.com/2117565/122817866-c1230a00-d2d8-11eb-8ee6-6f2e8396d79f.png)

![image](https://user-images.githubusercontent.com/2117565/122817913-d39d4380-d2d8-11eb-9909-a90c638564a9.png)

### Basic
![image](https://user-images.githubusercontent.com/2117565/122818161-22e37400-d2d9-11eb-9285-a36aa09c7c35.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/2117565/122818242-3db5e880-d2d9-11eb-8a6f-c1954eee4543.png)

### Identity
![image](https://user-images.githubusercontent.com/2117565/122818376-6342f200-d2d9-11eb-8b6e-1f9ab64d7b8e.png)

### Groups
![image](https://user-images.githubusercontent.com/2117565/122818634-c03ea800-d2d9-11eb-9916-337c78dca616.png)

### Scenes
![image](https://user-images.githubusercontent.com/2117565/122818541-a309d980-d2d9-11eb-9243-2cc3ee574997.png)

### Door Lock
![image](https://user-images.githubusercontent.com/2117565/122818832-f5e39100-d2d9-11eb-9914-75384f7495ac.png)
![image](https://user-images.githubusercontent.com/2117565/122818977-1ad80400-d2da-11eb-98c4-59333b690faa.png)
![image](https://user-images.githubusercontent.com/2117565/122819018-2a574d00-d2da-11eb-8937-3b67ceb46ee5.png)
![image](https://user-images.githubusercontent.com/2117565/122819080-3f33e080-d2da-11eb-86db-d8374e67f5aa.png)
![image](https://user-images.githubusercontent.com/2117565/122819112-4a870c00-d2da-11eb-936d-52e3c3302b05.png)

### OTAU
![image](https://user-images.githubusercontent.com/2117565/122819169-625e9000-d2da-11eb-83ce-5105d97a372d.png)

**Comment by Smanar** [comment]
This device is already on deconz, you have problem with it ?
