### ISSUE TITLE
Yagusmart Zigbee ZW-EU-02, 2 Gang smart switch

### ISSUE THREAD

**Issue by talksocke** [dresden-elektronik/deconz-rest-plugin#5046]
## Device

- Product name: ZW-EU-02
- Manufacturer: 0x117e
- Model identifier: unknown
- Device type : Please remove all unrelated device types. 
  - Switch

https://www.amazon.de/gp/product/B089LWGNJ5
 

## Screenshots
![grafik](https://user-images.githubusercontent.com/68250322/123070723-49f29080-d414-11eb-81a3-90c4e47caa35.png)

**Comment by Smanar** [comment]
I think this device can work natively.
But it s not correclty included on the capture, you miss the second circle on the node title.
You can get it using commands available in the first circle. This issue happen too on sonoff device, they need to be included with the coordinator, it s not working using a router and the mesh.

**Comment by talksocke** [comment]
> 
> 
> I think this device can work natively.
> But it s not correclty included on the capture, you miss the second circle on the node title.
> You can get it using commands available in the first circle. This issue happen too on sonoff device, they need to be included with the coordinator, it s not working using a router and the mesh.

**Comment by talksocke** [comment]
I had already pressed the commands of the first circle several times, but the second one was not displayed. Hours later I looked again and suddenly it was there. :-) Then I searched again via Phoscon for new lights and the two relays were found. 

![grafik](https://user-images.githubusercontent.com/68250322/123117048-b637b900-d441-11eb-8825-4283efb55cae.png)

**Comment by talksocke** [comment]
> 
> 
> I think this device can work natively.
> But it s not correclty included on the capture, you miss the second circle on the node title.
> You can get it using commands available in the first circle. This issue happen too on sonoff device, they need to be included with the coordinator, it s not working using a router and the mesh.

Thank you for this hint. :-)
