### ISSUE TITLE
CONBEE 2 loses connections with XIAOMI WINDOWS DOOR SENSORS

### ISSUE THREAD

**Issue by sajikur** [dresden-elektronik/deconz-rest-plugin#5047]
## Describe the bug

DECONZ app (on HOME ASSISTANT) looses connection with XIAOMI windows doors sensors and not report firmware version on PHOSCON. Other sensors, aqara version, (like hum/temp or vibrations) seems keep connections with gateway on reboot and report firmware version.
## Steps to reproduce the behavior

not a sporadic problem. CONBEE 2 looses connection on every reboot. Doesn't loose connection with multisensor temp/hum (xiaomi and aqara) and other sensor zigbee same brand
## Environment

 - Host system: INTEL NUC
 - Running method: DECONZ/PHOSCON on HOME ASSISTANT
 - Firmware version: 26660700
 - deCONZ version: 26660700
 - Device: ConBee II 
 - Do you use an USB extension cable: YES
 - Is there any other USB or serial devices connected to the host system? If so: UPS

## Additional context

THANX

**Comment by Mimiix** [comment]
Without any information, we can't help with anything.

Either way, please check other issues that hjave been submitted before. The wiki also contains information.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by sajikur** [comment]
Hi. Sorry for strange post but for some reason the description is 
incomplete. In your answer there is my problem. So I am following the 
solution described there. On reboot my window/door sensors going dead but 
every temp/hum sensors stay alive.
I'll update the result.
Thanx

In data 23 giugno 2021 14:15:55 Dennis D ***@***.***> ha scritto:

**Comment by sajikur** [comment]
Issue updated, thank you

In data 23 giugno 2021 14:15:55 Dennis D ***@***.***> ha scritto:

**Comment by Mimiix** [comment]
> Issue updated, thank you In data 23 giugno 2021 14:15:55 Dennis D ***@***.***> ha scritto:
> […](#)
> Without any information, we can't help with anything. Either way, please check other issues that hjave been submitted before. The wiki also contains information. https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I am not sure what you mean. Can you provide logs and also add a screen of the deconz map?
