### ISSUE TITLE
Osram motion sensor Smart+

### ISSUE THREAD

**Issue by RitaSghe** [dresden-elektronik/deconz-rest-plugin#5051]
## Describe the question or issue you are having
I connected my new Osram motion sensor Smart+ to Conbee II and does not appear in the list of device, why?

## Screenshots
![osram](https://user-images.githubusercontent.com/81916825/123249304-19305b00-d4e9-11eb-9bff-e0792b84809f.png)

![osram2](https://user-images.githubusercontent.com/81916825/123249316-1d5c7880-d4e9-11eb-9a0d-cb8b3b0f3878.png)

## Environment
Host system: (Raspberry Pi)
Running method: (Raspbian)
Firmware version: (26660700)
deCONZ version: (2.11.05)
Device: (ConBee II)
Do you use an USB extension cable: (yes)
Is there any other USB or serial devices connected to the host system? If so: usb pen

**Comment by Mimiix** [comment]
Seems to be not paired correctly.

**Comment by RitaSghe** [comment]
Ok
