### ISSUE TITLE
Yagusmart Tuya ZigBee Smart Light Switch with Touch Panel 2-Gang

### ISSUE THREAD

**Issue by erkikoiv** [dresden-elektronik/deconz-rest-plugin#5053]
## Device

- Product name: Yagusmart Tuya ZigBee Smart Light Switch with Touch Panel 2-Gang
- Manufacturer: _TZ3000_lupfd8zu
- Model identifier: TS0012
- Device type : Switch
  
## Screenshots

![image](https://user-images.githubusercontent.com/86436879/123328964-e9af3c00-d544-11eb-9e4b-1d15b2e93ee8.png)

This image shows the two lights that are created after pairing:
![image](https://user-images.githubusercontent.com/86436879/123329225-3e52b700-d545-11eb-9b36-c52976331806.png)

The product is found here: https://www.aliexpress.com/item/1005002116676502.html?spm=a2g0s.9042311.0.0.3da24c4dselHuV

It pairs as a light not as a switch (creates 2 lights as 2-gang switch). It should support three functions: one tap, two taps and long press. These other two are of course not working as it is registered as light. I am actually using it via Domoticz but it is registered there the same way it appears in Phoscon.

Can you help on how to indentify these correctly?

**Comment by Mimiix** [comment]
Can you please add deconz gui screenshots and not phoscon?

**Comment by erkikoiv** [comment]
Would this be the right one (I am quite new to deconz):
![image](https://user-images.githubusercontent.com/86436879/123336866-1d8f5f00-d54f-11eb-972b-7cdaddd59331.png)

**Comment by erkikoiv** [comment]
And somehow this is not showing up as a repeater.

**Comment by Mimiix** [comment]
> And somehow this is not showing up as a router.

I want to see all clusters and cluster info as asked in the template.

**Comment by erkikoiv** [comment]
Did I get the right info (Basic)?
![image](https://user-images.githubusercontent.com/86436879/123431587-152c3800-d5d2-11eb-94f5-6e2e09175a40.png)

**Comment by erkikoiv** [comment]
I have also another Tuya ZigBee 3.0 Smart Light Switch Module Relay from https://www.aliexpress.com/item/1005002096875229.html?spm=a2g0s.9042311.0.0.3da24c4dariOoh that I would need to get right config as well. I don't care that it is defined as well as light, but I would need this to act as a router (to get the Esik good signal). How can it be changed from End device to Router?
![image](https://user-images.githubusercontent.com/86436879/123440598-a227bf00-d5db-11eb-8caf-5fba5285faa6.png)
![image](https://user-images.githubusercontent.com/86436879/123440671-b53a8f00-d5db-11eb-8ad7-d48fd7f9fc20.png)

**Comment by Smanar** [comment]
But it s a wired switch ?
Wired switch are light because they receive order.
Battery switch are sensor because they send order.

Your device is wired, so it can turn on the light or turn it off. How it can have double/long press ?

**Comment by erkikoiv** [comment]
You are right, it is a wired switch and I think there was some misleading info about 3 function buttons. Sad, it is not a router switch. Then I think it works already OK, nothing else really needed. Thanks!
