### ISSUE TITLE
ghost automation

### ISSUE THREAD

**Issue by jegow** [dresden-elektronik/deconz-rest-plugin#5055]
## Describe the bug
I have installed a new wall switch "aquara opple" (triple switch). When I toggle the first switch, all sockets already installed in the house (3 OSRAM) are toggled too. I have not installed any scenes or rules or anything like that. IOBroker is switched off.
How can I switch off this automatic or where does it come from?

## Environment
Conbee 2
Version 2.11.05
Firmware 9.5.202126680700

**Comment by Mimiix** [comment]
Please check this issue:https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3670#issuecomment-743732232

It's a common problem with this switches. clicking the C solved it.

**Comment by jegow** [comment]
What does "clicking the C" mean? I use the Phoscon app in the firefox browser.

**Comment by Mimiix** [comment]
@jegow On the back of the switch itself.
