### ISSUE TITLE
Can't connect after update

### ISSUE THREAD

**Issue by Tomkee** [dresden-elektronik/deconz-rest-plugin#5061]
## Describe the bug
Can't connect after update

  Help us understand the issue by providing valuable context.
Beelink HA on VM oprxmox

## Steps to reproduce the behavior
After update, there is no connection. I also wanted to updated manually in Windows but after GCFFlasher -l  I am getting no FTDI devices found.
I made sure to add this USB to VM.

-->

## Expected behavior
connect

## Screenshots
![Capture](https://user-images.githubusercontent.com/55411790/123541297-11202780-d744-11eb-90b1-d7fc3c9744bf.JPG)
![Capture2](https://user-images.githubusercontent.com/55411790/123541318-27c67e80-d744-11eb-80b6-c7e5b025d3aa.JPG)

## Environment
Proxmox VM

 - Host system: Beelink
 - Running method: Home Assistent deCONZ Add-on 
 - Firmware version: core-2021.6.6
 - deCONZ version: Current version: 6.9.0
 - Device: ConBee II 
 - Do you use an USB extension cable: (yes
 - Is there any other USB or serial devices connected to the host system? If so: Which?

## deCONZ Logs
12:32:30:657 failed to reconnect to network try=8
12:32:35:657 failed to reconnect to network try=9
12:32:40:660 failed to reconnect to network try=10
12:32:45:657 reconnect network failed, try later
12:32:45:731 start reconnect to network
12:32:50:657 failed to reconnect to network try=1
12:32:55:656 failed to reconnect to network try=2
12:33:00:656 failed to reconnect to network try=3
12:33:05:657 failed to reconnect to network try=4
12:33:10:657 failed to reconnect to network try=5
12:33:15:657 failed to reconnect to network try=6
12:33:20:657 failed to reconnect to network try=7
12:33:25:656 failed to reconnect to network try=8
12:33:30:656 failed to reconnect to network try=9
12:33:35:656 failed to reconnect to network try=10
12:33:40:657 reconnect network failed, try later
12:33:40:726 start reconnect to network
12:33:45:657 failed to reconnect to network try=1
12:33:50:658 failed to reconnect to network try=2
12:33:55:657 failed to reconnect to network try=3
12:34:00:657 failed to reconnect to network try=4
12:34:05:657 failed to reconnect to network try=5
12:34:10:656 failed to reconnect to network try=6
12:34:15:657 failed to reconnect to network try=7
12:34:20:657 failed to reconnect to network try=8
12:34:25:661 failed to reconnect to network try=9
12:34:30:656 failed to reconnect to network try=10
12:34:35:656 reconnect network failed, try later
12:34:35:728 start reconnect to network
12:34:40:657 failed to reconnect to network try=1
12:34:45:657 failed to reconnect to network try=2
12:34:50:657 failed to reconnect to network try=3
172.30.32.2 - - [27/Jun/2021:12:34:54 +0200] "GET /api/7F236FAB4D/config?_=1624789044946 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:54 +0200] "GET /websocket HTTP/1.1" 101 4 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:34:54:591 Websocket disconnected 127.0.0.1:43328, state: 0, close-code: 1000, reason: 
12:34:55:656 failed to reconnect to network try=4
172.30.32.2 - - [27/Jun/2021:12:34:56 +0200] "GET /pwa/index.html HTTP/1.1" 200 113153 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:57 +0200] "GET /api/7F236FAB4D/config?_=1624790102061 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:57 +0200] "GET /api/7F236FAB4D/config?_=1624790102062 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:57 +0200] "GET /api/7F236FAB4D/groups?_=1624790102063 HTTP/1.1" 200 379 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:57 +0200] "GET /api/7F236FAB4D/lights?_=1624790102064 HTTP/1.1" 200 12 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:57 +0200] "GET /api/7F236FAB4D/sensors?_=1624790102065 HTTP/1.1" 200 440 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:57 +0200] "GET /api/7F236FAB4D/config?_=1624790102066 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:34:58:150 New websocket 127.0.0.1:44956 (state: 3) 
172.30.32.2 - - [27/Jun/2021:12:34:59 +0200] "GET /pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4 HTTP/1.1" 200 54362 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:59 +0200] "GET /websocket HTTP/1.1" 101 4 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:34:59:043 Websocket disconnected 127.0.0.1:44956, state: 0, close-code: 1000, reason: 
172.30.32.2 - - [27/Jun/2021:12:34:59 +0200] "GET /api/7F236FAB4D/config?_=1624790104108 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:59 +0200] "GET /api/7F236FAB4D/config?_=1624790104109 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:34:59 +0200] "GET /api/7F236FAB4D/config?_=1624790104110 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:35:00:273 New websocket 127.0.0.1:44976 (state: 3) 
12:35:00:656 failed to reconnect to network try=5
172.30.32.2 - - [27/Jun/2021:12:35:04 +0200] "GET /api/7F236FAB4D/config?_=1624790104111 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:35:04 +0200] "GET /api/7F236FAB4D/config?_=1624790104112 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:35:05:656 failed to reconnect to network try=6
172.30.32.2 - - [27/Jun/2021:12:35:09 +0200] "GET /api/7F236FAB4D/config?_=1624790104113 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:35:10:657 failed to reconnect to network try=7
172.30.32.2 - - [27/Jun/2021:12:35:14 +0200] "GET /api/7F236FAB4D/config?_=1624790104114 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:35:15:658 failed to reconnect to network try=8
172.30.32.2 - - [27/Jun/2021:12:35:20 +0200] "GET /api/7F236FAB4D/config?_=1624790104115 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:35:20:657 failed to reconnect to network try=9
172.30.32.2 - - [27/Jun/2021:12:35:25 +0200] "GET /api/7F236FAB4D/config?_=1624790104116 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:35:25:657 failed to reconnect to network try=10
12:35:30:656 reconnect network failed, try later
12:35:30:727 start reconnect to network
12:35:35:656 failed to reconnect to network try=1
12:35:40:657 failed to reconnect to network try=2
12:35:45:657 failed to reconnect to network try=3
12:35:50:657 failed to reconnect to network try=4
12:35:55:656 failed to reconnect to network try=5
12:36:00:656 failed to reconnect to network try=6
12:36:05:657 failed to reconnect to network try=7
172.30.32.2 - - [27/Jun/2021:12:36:06 +0200] "GET /api/7F236FAB4D/config?_=1624790104117 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:36:07 +0200] "GET /api/A90329328F/config?_=1624788678851 HTTP/1.1" 200 2193 "https://192.168.1.100:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:36:07 +0200] "GET /websocket HTTP/1.1" 101 4 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:36:07:285 Websocket disconnected 127.0.0.1:44602, state: 0, close-code: 1000, reason: 
172.30.32.2 - - [27/Jun/2021:12:36:07 +0200] "GET /ingress.html HTTP/1.1" 200 2018 "https://192.168.1.100:8123/core_deconz/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
172.30.32.2 - - [27/Jun/2021:12:36:09 +0200] "GET /api/7F236FAB4D/config?_=1624790104118 HTTP/1.1" 200 2193 "https://haswiat.duckdns.org:8123/api/hassio_ingress/tzcrjiaMXWGOxHk_H0dz1p_NgJTYX68JpRmN6gUI4vg/pwa/settings-gateway2.html?_v=ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0,5,0,12&gwid=00212EFFFF06C4B4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:36:10:657 failed to reconnect to network try=8
172.30.32.2 - - [27/Jun/2021:12:36:11 +0200] "GET /websocket HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
12:36:11:076 Websocket disconnected 127.0.0.1:44976, state: 0, close-code: 1000, reason: 
12:36:15:661 failed to reconnect to network try=9
12:36:20:658 failed to reconnect to network try=10
12:36:25:656 reconnect network failed, try later
12:36:25:735 start reconnect to network
12:36:30:656 failed to reconnect to network try=1
12:36:35:656 failed to reconnect to network try=2
12:36:40:658 failed to reconnect to network try=3
12:36:45:657 failed to reconnect to network try=4
12:36:50:656 failed to reconnect to network try=5
12:36:55:656 failed to reconnect to network try=6
12:37:00:658 failed to reconnect to network try=7
12:37:05:658 failed to reconnect to network try=8
12:37:10:656 failed to reconnect to network try=9
12:37:15:656 failed to reconnect to network try=10
12:37:20:658 reconnect network failed, try later
12:37:20:730 start reconnect to network
12:37:25:656 failed to reconnect to network try=1
12:37:30:656 failed to reconnect to network try=2
12:37:35:656 failed to reconnect to network try=3

-->

## Additional context

I manage to install CC2531 with no problem. 
-->

**Comment by Smanar** [comment]
Hello, yes, you can first update the device using windows :
- But never use VM
- the device is reconised on windows ? (even you have USB disconnection)
- can nee to make the command many time, because of deconnexions.
