### ISSUE TITLE
Exposing SNZB 01 actions

### ISSUE THREAD

**Issue by gio261198** [dresden-elektronik/deconz-rest-plugin#5072]
## Describe the question or issue you are having
  Hello, I can't see the entity which provides SNZB 01 Switch Mini status (ON/OFF) even though I can see the data coming in the debug view.

Can anyone help me?

## Screenshots
 DEBUG VIEW
 
![image](https://user-images.githubusercontent.com/35524413/123844351-36af5b80-d913-11eb-9849-bdb9a84385ba.png)

## Environment
  Coordinator Used: Conbee II
  Coordinator Firmware: 26660700
  DeCONZ version: 6.9.0

 - Host system: Raspberry Pi - HASSIO
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: (26660700)
 - deCONZ version: (2.11.05)
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment]
You need to listen to the deconz_event and trigger from the events. 

Either way, this is a question for home assistant and not this repository.

Closing this issue.
