### ISSUE TITLE
MCT-350 SMA

### ISSUE THREAD

**Issue by luisgarcia87** [dresden-elektronik/deconz-rest-plugin#5073]
## Device

- Product name: MCT-350 SMA
- Manufacturer: Visonic
- Model identifier: MCT-350 SMA
- Device type : Please remove all unrelated device types. 
  - Sensor
  
## Screenshots

<img width="336" alt="Screen Shot 2021-06-29 at 6 46 28 PM" src="https://user-images.githubusercontent.com/561436/123881602-af5dea00-d90a-11eb-8ecd-88f012812682.png">
<img width="358" alt="Screen Shot 2021-06-29 at 6 46 59 PM" src="https://user-images.githubusercontent.com/561436/123881610-b1c04400-d90a-11eb-85aa-21c07ae93ce9.png">
<img width="358" alt="Screen Shot 2021-06-29 at 6 47 16 PM" src="https://user-images.githubusercontent.com/561436/123881612-b258da80-d90a-11eb-9b16-16b281821407.png">
<img width="357" alt="Screen Shot 2021-06-29 at 6 47 34 PM" src="https://user-images.githubusercontent.com/561436/123881616-b38a0780-d90a-11eb-9412-dc1c9e8296a4.png">
<img width="354" alt="Screen Shot 2021-06-29 at 6 47 45 PM" src="https://user-images.githubusercontent.com/561436/123881617-b4229e00-d90a-11eb-8e64-49143ea8a40e.png">
<img width="351" alt="Screen Shot 2021-06-29 at 6 48 01 PM" src="https://user-images.githubusercontent.com/561436/123881620-b4bb3480-d90a-11eb-97af-f937df529a17.png">
<img width="351" alt="Screen Shot 2021-06-29 at 6 48 21 PM" src="https://user-images.githubusercontent.com/561436/123881621-b553cb00-d90a-11eb-864b-ccde07f8b50e.png">
<img width="355" alt="Screen Shot 2021-06-29 at 6 48 32 PM" src="https://user-images.githubusercontent.com/561436/123881623-b5ec6180-d90a-11eb-8b67-b02d987dcaf1.png">
<img width="356" alt="Screen Shot 2021-06-29 at 6 48 44 PM" src="https://user-images.githubusercontent.com/561436/123881625-b684f800-d90a-11eb-8c9a-63617cccee66.png">

The device did not enroll by itself and it kept blinking 3 times every 5 seconds indicating that it is in pairing mode. And the IAS Zone was like this:
<img width="351" alt="Screen Shot 2021-06-29 at 6 48 21 PM" src="https://i.postimg.cc/vHk4nGmy/Screen-Shot-2021-06-29-at-6-59-09-PM.png">

Then I added to the IAS_CIE_Address the mac of my zigbee gateway and wrote that info into the device
<img width="351" src="https://i.postimg.cc/rsYKQkCS/Screen-Shot-2021-06-29-at-6-57-56-PM.png">

 and after that I executed the zone enroll response, the Zone State on the attributes in the IAS Zone changed from not enrolled to enrolled:
<img width="351" src="https://i.postimg.cc/J7TD1NVG/Screen-Shot-2021-06-29-at-6-58-34-PM.png">

also then zone status changes from 0x0025 (sensor open) to 0x0024 when I close the sensor, meaning that it is reading the status of it, but I can't see the sensor on the Phoscon App and I am unable to pair it using the Phoscon App. Is there a way to add that sensor from deconz app to Home Assistant?

Any help is appreciated.

**Comment by Mimiix** [comment]
Can you add a screenshot of the node in deconz and the cluster list?

The reason you wont see it in phoscon is because Phoscon needs to add support themselves. However, Home assistant should see it if the device is supported. The name of the device suggest it isn't .

**Comment by Smanar** [comment]
It s a door sensor ? (not sure as like said Mimix, it miss the cluster list)
Do you have a linux machine to test code modification ?
