### ISSUE TITLE
MOES - smart brightness thermometer

### ISSUE THREAD

**Issue by jleeca** [dresden-elektronik/deconz-rest-plugin#5088]
Hi Guys,

Can you please add a new MOES device:

[Moes ZigBee Smart Brightness Thermometer Sensor](https://www.aliexpress.com/item/1005002524376481.html?spm=a2g0s.9042311.0.0.28904c4dUdVsiP)

I tried to add the device in Phoscon but it is not detected. Please let me know if more information.

Thanks,

**Device**
- Product name: Moes Smart Brightness Thermometer Sensor
- Manufacturer: _TYZB01_kvwjujy9
- Model identifier: TS0222

**Screenshots**
![image](https://user-images.githubusercontent.com/20133784/124369521-81deac80-dc3a-11eb-8126-f155ee9e3b0e.png)
![image](https://user-images.githubusercontent.com/20133784/124369526-8c00ab00-dc3a-11eb-9fb3-acd88eabcefc.png)
![image](https://user-images.githubusercontent.com/20133784/124369527-902cc880-dc3a-11eb-9d9f-cd3eaf4af0e1.png)
![image](https://user-images.githubusercontent.com/20133784/124369528-9327b900-dc3a-11eb-8db5-9256a9e9cfde.png)
![image](https://user-images.githubusercontent.com/20133784/124369530-96bb4000-dc3a-11eb-9557-e01e340d03d8.png)
![image](https://user-images.githubusercontent.com/20133784/124369532-99b63080-dc3a-11eb-9053-a9610083478e.png)
![image](https://user-images.githubusercontent.com/20133784/124369534-9d49b780-dc3a-11eb-8563-7a810f69517b.png)
![image](https://user-images.githubusercontent.com/20133784/124369536-9fac1180-dc3a-11eb-81b4-14845978115e.png)

**Comment by Mimiix** [comment]
If you see devices within deCONZ but not in Phoscon, that is most of the time perfectly normal. Phoscon is closed source and needs devices to be added manually by their developer. However, the device will still be usable with the API/Home-Assistant/OpenHAB etc. You may want to go ahead and request support for your device at the Phoscon repo

**Comment by Mimiix** [comment]
If you see devices within deCONZ but not in Phoscon, that is most of the time perfectly normal. Phoscon is closed source and needs devices to be added manually by their developer. However, the device will still be usable with the API/Home-Assistant/OpenHAB etc. You may want to go ahead and request support for your device at the Phoscon repo.

Closing

**Comment by jleeca** [comment]
As explained by @Mimiix, I can confirm that the device is available in Home Assistant and usable so I'm closing the case.
