### ISSUE TITLE
Sensors are not displayed correctly in Phoscon (Home Assistant)

### ISSUE THREAD

**Issue by Treyfane** [dresden-elektronik/deconz-rest-plugin#5095]
Hey there,

I'm currently using the following setup:

Home Assistant OS 6.1 on a Raspi 4
Supervisor: supervisor-2021.06.6
Core: core-2021.6.6
deCONZ: 6.9.0

I've got some 7 pcs. SILVERCREST / LIDL Silvercrest motion detectors, all bought from the same store out of the same batch of which I connected 4 pcs. some months ago using the Phoscon App, they're working without a problem.

Now I wanted to connect the remaining 3 and here's the problem:

Upon connecting the motion detectors via the Phoscon App (Sensors / Add Sensor / ...) the sensors are found, but will not be displayed in the Phoscon App. 

<img width="600" alt="Screenshot1" src="https://user-images.githubusercontent.com/30451249/124507326-dd8d6f00-ddcd-11eb-858c-38b8a4da3f4a.png">

However, the sensors are correctly displayed in the deCONZ App (Presence 11, Presence 12 and Presence 13). 

<img width="600" alt="Screenshot2" src="https://user-images.githubusercontent.com/30451249/124507378-fb5ad400-ddcd-11eb-972c-4a9270b064a1.png">

They are also available as Devices / Entities in Home Assistant.

From what I can see when checking the network requests/response in the Phoscon App, it seems as if the API request "sensors?_=<number>" actually does return a JSON with all the sensors in it, the page is just not displaying it (correctly):

`{

    "1":{
        "config":{
            "configured":true,
            "on":true,
            "sunriseoffset":30,
            "sunsetoffset":-30
        },
        "etag":"<long etag here>",
        "manufacturername":"Philips",
        "modelid":"PHDL00",
        "name":"Daylight",
        "state":{
            "dark":false,
            "daylight":true,
            "lastupdated":"2021-07-05T17:38:01.359",
            "status":170,
            "sunrise":"2021-07-05T03:35:23",
            "sunset":"2021-07-05T19:33:02"
        },
        "swversion":"1.0",
        "type":"Daylight",
        "uniqueid":"<long uniqueid here>",
    },
    "11":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":1,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:57Z",
        "manufacturername":"LIDL Silvercrest",
        "modelid":"HG06335",
        "name":"Presence 11",
        "state":{
            "lastupdated":"2021-07-05T17:57:43.452",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    },
    "12":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":1,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:57Z",
        "manufacturername":"LIDL Silvercrest",
        "modelid":"HG06335",
        "name":"Presence 12",
        "state":{
            "lastupdated":"2021-07-05T17:57:51.264",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    },
    "13":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":1,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:57Z",
        "manufacturername":"LIDL Silvercrest",
        "modelid":"HG06335",
        "name":"Presence 13",
        "state":{
            "lastupdated":"2021-07-05T17:57:48.828",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    },
    "2":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":1,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:57Z",
        "manufacturername":"SILVERCREST",
        "modelid":"TY0202",
        "name":"BM EG Flur 1",
        "state":{
            "lastupdated":"2021-06-27T15:47:12.211",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "swversion":"2019.12.12",
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    },
    "3":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":3,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:39Z",
        "manufacturername":"SILVERCREST",
        "modelid":"TY0202",
        "name":"BM EG Flur 2",
        "state":{
            "lastupdated":"2021-07-05T17:25:02.371",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "swversion":"2019.12.12",
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    },
    "4":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":3,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:39Z",
        "manufacturername":"SILVERCREST",
        "modelid":"TY0202",
        "name":"BM EG Bad 1",
        "state":{
            "lastupdated":"2021-07-05T14:35:42.016",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "swversion":"2019.12.12",
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    },
    "6":{
        "config":{
            "heatsetpoint":1200,
            "locked":true,
            "mode":"auto",
            "offset":0,
            "on":true,
            "preset":"auto",
            "reachable":false,
            "schedule":{
            },
            "schedule_on":false,
            "setvalve":false,
            "windowopen_set":false
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":null,
        "manufacturername":"_TZE200_c88teujp",
        "modelid":"TS0601",
        "name":"Thermostat 6",
        "state":{
            "lastupdated":"none",
            "lowbattery":null,
            "on":null,
            "temperature":null,
            "valve":null
        },
        "type":"ZHAThermostat",
        "uniqueid":"<long uniqueid here>",
    },
    "7":{
        "config":{
            "battery":100,
            "duration":60,
            "enrolled":0,
            "on":true,
            "pending":[
            ],
            "reachable":true
        },
        "ep":1,
        "etag":"<long etag here>",
        "lastseen":"2021-07-05T17:38Z",
        "manufacturername":"SILVERCREST",
        "modelid":"TY0202",
        "name":"BM EG Küche 1",
        "state":{
            "lastupdated":"2021-07-05T17:24:44.898",
            "lowbattery":false,
            "presence":false,
            "tampered":false
        },
        "swversion":"2019.12.12",
        "type":"ZHAPresence",
        "uniqueid":"<long uniqueid here>",
    }

}`

I also see, that the manufacturer and modelid is different in between the sensors aded via Phoscon some month ago and the ones added recently (today). The sensors are in fact all the same model (HG06335 according to what#s written on them).

Maybe someone has a bright idea how to address this problem? 😸

Greetings,

          ^.^ Dingo

--

**Comment by LudwigErr** [comment]
@Treyfane : ich habe das selbe Problem, auch hier wurde es schon geschildert: https://github.com/dresden-elektronik/phoscon-app-beta/issues/409. Dort wurde der User aufgefordert, das Problem nicht auf Github zu melden, sondern hier: https://forum.phoscon.de/
Daher habe ich heute dort meinen Bugreport abgesetzt: https://forum.phoscon.de/t/silvercrest-lidl-motion-sensor-not-visible-in-phoscon-app/362
Vielleicht kommen wir da weiter. Viele Grüsse, Ludwig.
-----
@Treyfane : I have the same problem, also it was already described here: https://github.com/dresden-elektronik/phoscon-app-beta/issues/409 There the user was asked not to report the problem on Github, but here: https://forum.phoscon.de/
So I filed my bug report there today: https://forum.phoscon.de/t/silvercrest-lidl-motion-sensor-not-visible-in-phoscon-app/362
Maybe we can get further there. Best regards, Ludwig.

Translated with www.DeepL.com/Translator (free version)
