### ISSUE TITLE
ADEO - Animal compatible motion sensor

### ISSUE THREAD

**Issue by jwestelynck** [dresden-elektronik/deconz-rest-plugin#5097]
## Device

- Product name: Animal compatible motion sensor
- Manufacturer: ADEO
- Model identifier: LDSENK10
- Device type :
  - Sensor

- Product information : https://www.leroymerlin.fr/produits/electricite-domotique/domotique-et-objets-connectes/domotique/accessoires-de-gestion-des-motorisations-et-automatismes/detecteur-de-mouvement-animaux-lexman-82428878.html

### Node info
![image](https://user-images.githubusercontent.com/40762536/124519981-53ec9a00-ddeb-11eb-92a4-5bfde53d45e6.png)

### Basic
![image](https://user-images.githubusercontent.com/40762536/124519621-24895d80-ddea-11eb-97db-b619a7d5a5e4.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/40762536/124519711-5f8b9100-ddea-11eb-8c8f-19a94034418a.png)

### Identify
![image](https://user-images.githubusercontent.com/40762536/124519668-44b91c80-ddea-11eb-8059-416cda328cc6.png)

### Poll Control
![image](https://user-images.githubusercontent.com/40762536/124519746-792cd880-ddea-11eb-8099-10b57f42f11d.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/40762536/124519773-9366b680-ddea-11eb-9d1b-d1110bca1ea1.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/40762536/124519858-eb9db880-ddea-11eb-8e46-872ecc4f6012.png)

**Comment by Smanar** [comment]
Hello, do you have a linux machine with full OS to test code modification ?
Can you show the cluster list fom deconz too, it s the picture, with the node title and all clusters visibles with endpoint ?

**Comment by jwestelynck** [comment]
Hello, for sure i can test code modification

please fin the requested screenshot :

![image](https://user-images.githubusercontent.com/40762536/124660617-bbb3eb00-dea6-11eb-9075-d6289a3a2afa.png)

**Comment by Smanar** [comment]
Ok so first try

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch adeo_sensor https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

The code is untested on my side, If I m right you will have a presence sensor, not checked for battery.

**Comment by jwestelynck** [comment]
Great !

Sensor are now found by Phoscon !

![image](https://user-images.githubusercontent.com/40762536/124796514-8adcc000-df51-11eb-9385-d59361ad558a.png)

But don't appear in sensor list.

![image](https://user-images.githubusercontent.com/40762536/124796571-9b8d3600-df51-11eb-82b0-c013fbfbde74.png)

In deconz it appear as a motion sensor (presence)

![image](https://user-images.githubusercontent.com/40762536/124796903-f58dfb80-df51-11eb-8abe-5d10ed200793.png)

**Comment by Smanar** [comment]
On first try lol
No problem, batery is good too ?

Can make the PR ?

**Comment by jwestelynck** [comment]
Ok :)
I can find it on Jeedom. How to check battery ?

![image](https://user-images.githubusercontent.com/40762536/124799775-30ddf980-df55-11eb-9cd4-ccc46dde1959.png)

**Comment by Smanar** [comment]
And it works fine ?
You haven't "a place" for battery on jeedom ? else I known you have somewhere "informations brutes"

**Comment by jwestelynck** [comment]
looks good !

![image](https://user-images.githubusercontent.com/40762536/124903482-4cdcac00-dfe4-11eb-8469-49652914feac.png)

tampered sensor is also working.

**Comment by Smanar** [comment]
Thx, making the PR
