### ISSUE TITLE
ZM-RT201 Zigbee motion sensor

### ISSUE THREAD

**Issue by Cassiopea1** [dresden-elektronik/deconz-rest-plugin#5099]
## Device

- Product name: Zigbee motion sensor
- Manufacturer: no idea
- Model identifier: ZM-RT201
- Device type : 
  - Sensor

## Screenshots
![image](https://user-images.githubusercontent.com/84228832/124603888-af11a180-de6a-11eb-9c1b-45492134efdd.png)
![image](https://user-images.githubusercontent.com/84228832/124604040-d1a3ba80-de6a-11eb-9dff-7004a79f94e1.png)
![image](https://user-images.githubusercontent.com/84228832/124604141-f0a24c80-de6a-11eb-96bc-25169fe8e0cd.png)
![image](https://user-images.githubusercontent.com/84228832/124604241-0748a380-de6b-11eb-8069-068f8a72c36e.png)

**Comment by Mimiix** [comment]
Can you try to pair it a few times? There seem to be some clusters missing. The Basic cluster should always be there, so maybe after a re-pair it should show up.

**Comment by Cassiopea1** [comment]
I tried several times to pair it, but I always get the same result.

**Comment by RangeMethod** [comment]
I have the exact same Issue, 
what can we do to get this done?

**Comment by erkikoiv** [comment]
I have the same issue, it is visible in deConz but not in Phoscon and doesn't show the Basic cluster. What is missing?

**Comment by dvdfrancos** [comment]
+1 with the exact same Issue

**Comment by mactoolz** [comment]
Hi there,

I have a PIR motion sensor from Tuya.

ZM-RT201. I've already found a post on GitHub. Unfortunately, the subject was not pursued any further. I would like to start that again or ask how you can solve this problem with the sensor.

The topic is still the same as the one that can be seen in the DeConz but not in the Phoscon APP.

Now I'm not sure how far the sensor is supported or not.

Regards

**Comment by Cassiopea1** [comment]
Hi,

 

My solution was to buy a Tuya zigbee hub. I can not wait for Dresden elektronik to get in the mood to support it.

 

Regards

**Comment by mtressl** [comment]
bump - same issue here

**Comment by Malle355** [comment]
Same to me. My Bad that I didn't found this before I bought those devices...

**Comment by mtressl** [comment]
But now with so many pieces of the PIR available, can we re-try and get them working?
@Mimiix anything we can do or help to get you the right information?

**Comment by Marcello2022** [comment]
Same issue here - would much appreciate if dresden elektronik looked into this in order to get support for the sensor

**Comment by Mimiix** [comment]
> But now with so many pieces of the PIR available, can we re-try and get them working? @Mimiix anything we can do or help to get you the right information?

Nope, we need a dev to look into it. But due to ddfs, we are kinda on hold.

**Comment by DayRunner131** [comment]
Bump. Same issue. No Phoscon support but see it connected in deConz.

**Comment by Mimiix** [comment]
@Smanar

**Comment by Smanar** [comment]
Basic cluster are still invisible ?

**Comment by marvin743** [comment]
Same issue for me. Too sad, that I already bought the devices. What’s about the support? :-(

**Comment by Smanar** [comment]
We need the basic cluster information to know what is the device.
At least the manufacture name / model id.

**Comment by marvin743** [comment]
> We need the basic cluster information to know what is the device. At least the manufacture name / model id.

Device: Tuya Mini Zigbee PIR Sensor [https://de.aliexpress.com/item/1005004295765145.html?spm=a2g0o.productlist.0.0.7db430d8c3iigl&algo_pvid=4787d341-485d-4df1-8752-e432db178861&algo_exp_id=4787d341-485d-4df1-8752-e432db178861-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000028665580362%22%7D&pdp_npi=2%40dis%21EUR%21%2113.0%21%21%21%21%21%400b0a01f816575525324815854e7853%2112000028665580362%21sea](url)

Should be this device:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/87813401/178298115-e672d8a1-de08-4f2f-80ba-fe79db6728bb.png">

**Comment by DayRunner131** [comment]
I am unfortunately not seeing a manufacturer name / model identifier.

![image](https://user-images.githubusercontent.com/77282262/178309491-788fa23b-d81d-413a-8846-4cccf325736e.png)

**Comment by Smanar** [comment]
@DayRunner131 can try the same DDF if you think you have the same device, else you can
- select the basic cluster 0x0000 to open the cluster information
- press the "read" button adn in same time awake the device with pressing shortly the button.
- It will fill the attribute table on the same panel.

**Comment by DayRunner131** [comment]
@Smanar I am not seeing a basic cluster information tab... It's consistent with all of these that I connect.

![image](https://user-images.githubusercontent.com/77282262/178317619-2c417216-936a-4154-bc9a-3e3812d485d6.png)

**Comment by marvin743** [comment]
> Hello, can try this DDF
> 
> ```
> {
>    "schema":"devcap1.schema.json",
>    "manufacturername":"_TZ3000_mcxw5ehu",
>    "modelid":"TS0202",
>    "product":"Presence sensor (without Tuya cluster)",
>    "sleeper":true,
>    "status":"Gold",
>    "subdevices":[
>       {
>          "type":"$TYPE_PRESENCE_SENSOR",
>          "restapi":"/sensors",
>          "uuid":[
>             "$address.ext",
>             "0x01",
>             "0x0500"
>          ],
>          "items":[
>             {
>                "name":"attr/id"
>             },
>             {
>                "name":"attr/lastannounced"
>             },
>             {
>                "name":"attr/lastseen"
>             },
>             {
>                "name":"attr/manufacturername"
>             },
>             {
>                "name":"attr/modelid"
>             },
>             {
>                "name":"attr/name"
>             },
>             {
>                "name":"attr/swversion"
>             },
>             {
>                "name":"attr/type"
>             },
>             {
>                "name":"attr/uniqueid"
>             },
>             {
>                "name":"config/duration"
>             },
>             {
>                "name":"config/enrolled",
>                "public":false
>             },
>             {
>                "name":"config/on"
>             },
>             {
>                "name":"config/pending"
>             },
>             {
>                "name":"config/reachable"
>             },
>             {
>                "name":"state/lastupdated"
>             },
>             {
>                "name":"state/lowbattery"
>             },
>             {
>                "name":"state/presence",
>                "awake":true,
>                "parse":{
>                   "fn":"ias:zonestatus",
>                   "mask":"alarm1"
>                }
>             }
>          ]
>       }
>    ],
>    "bindings":[
>       {
>          "bind":"unicast",
>          "src.ep":1,
>          "cl":"0x0500"
>       },
>       {
>          "bind":"unicast",
>          "src.ep":1,
>          "cl":"0x0001",
>          "report":[
>             {
>                "at":"0x0021",
>                "dt":"0x20",
>                "min":60,
>                "max":3600,
>                "change":"0x00000001"
>             }
>          ]
>       }
>    ]
> }
> ```

How can i do this? Is there any manual available?

Thanks!

**Comment by Smanar** [comment]
@DayRunner131 your device is not completely included https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues
Without modelid and manufacture name, can do nothing.

@marvin743 https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
You just need to put a text file called what_youwant.json in the "devices" folder with this content.
And if you are using HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by WhimsySpoon** [comment]
I've just tried adding this device and the Edit DDF button on the drop down does nothing. For other devices it works fine.

**Comment by Smanar** [comment]
The "edit DDF" doesn't open the editor ? Or it is empty ?
