### ISSUE TITLE
On 2.05.16 but can't upgrade to latest firmware

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#510]
So I tried to upgrade conbee to the new firmware

First I tried upgrading through Deconz left it alone for 20 min, and the second time I tried using Phoscon for 50 min. But it just continued to spam upgrading fw in terminal.

Suggestions?

**Comment by marthoc** [comment]
You can use my docker image to flash the stick (even if you aren’t currently using deconz in docker). The 2.05.16 image contains the latest firmware and my firmware script - you can find instructions in the README in my repo.

**Comment by Kane610** [comment]
I will try that @marthoc

**Comment by Kane610** [comment]
@marthoc that worked great! Closing this issue.
