### ISSUE TITLE
Going crazy, entire zigbee network gone bonkers, loosing lights left and right for several days now

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/deconz-rest-plugin#5100]
## Describe the bug

I've previously had a light drop off here and there, no big deal, a power cycle and things are back to normal. But lately it's gone completely crazy.
I'm loosing half the lights every day, making the WAF plummet.
## Steps to reproduce the behavior

  1. Have all lights signed into the network
  2. Leave it overnight
  3. Chaos

The problems seems to be sporadic, and illogical, the lights don't loose power, but something is disturbing them from operating.
## Screenshots

![image](https://user-images.githubusercontent.com/13660621/124618804-63fe8b00-de78-11eb-8d3b-57a7a14fdbca.png)
![image](https://user-images.githubusercontent.com/13660621/124618752-5812c900-de78-11eb-86cd-145066b38cb0.png)
![image](https://user-images.githubusercontent.com/13660621/124618647-40d3db80-de78-11eb-87d5-a04cd5ebb051.png)
## Environment

 - Host system: PC
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26670700)
 - deCONZ version: (2.11.05)
 - Device:ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? AEOTEC Z-WAVE stick

**Comment by Smanar** [comment]
And not only ikea ?
Something special on the mesh ? can be a special zone ?

Have you tried to check logs for a clue ?

**Comment by manup** [comment]
Could it be that some other 2.4GHz devices are interfering on the same channel? WiFi and Bluetooth are often good candidates.
Usually when this happens you might see some 0xE1 errors in the logs (see https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log).

**Comment by fribse** [comment]
I have end devices (sensors) from heiman and aqara, they've played well for a very long time. I then tried adding some heiman zigbee sirens, and that made it go to hell. I've since removed the heiman sirens again, but the network doesn't settle, it keeps kicking stuff out, so both me and (more importantly) my wife, are going bat crazy over this.
I would love to provide some logfiles, any idea on how I can get logfiles out from within the home assistant addon?

**Comment by fribse** [comment]
@manup I have 2.4 GHz at channel 1 and 11, the zigbee says channel 15, but I don't know if it's the same 'numbers' for the channel they use.
I've done some wifi scanning, and the neighbours doesn't seem to interfere that much, but my wifi scanner does not show the zigbee as far as I know.
If I change the channel, I guess I have to redo all devices, right?

**Comment by AutoHass8** [comment]
Your ZigBee channel 15 is in the sidelobe of WiFi channel 1. Try setting your WiFi channels to 1 & 6 and your ZigBee channel to 25, so they are as well separated as possible. ZigBee channel 25 will then be in the sidelobe of WiFi channel 11, in case of pesky neighbours...

I had some issues early on using ZigBee channel 15 on my ConBee I, so I made the above move right away. Don't remember if I had to redo any devices, but I've never had a network issue since.

**Comment by Mimiix** [comment]
@manup @Smanar Would this be a possible bug in deCONZ or is this a user question?

@fribse We've got a forum since yesterday, feel free to take a look :) 
https://www.phoscon.de/forum

**Comment by Smanar** [comment]
I don't think it s from a deCONZ bug, else we will have more users with the problem.

I don't remember how to get log on HA, but now you have access on the deconz GUI inside HA itself no ?

**Comment by fribse** [comment]
@Mimiix , ok, I'll use that as well :-)

@Autohass8, darned, I feared that, I can see that out new neighbour is using channel 11, but there is nothing above 13, typical. for now I will move my ap with channel 1 to use channel 11, and the channel 11 to use channel 6 (my site survey says that it's better this way towards neighbours :-)
So the zigbee is now still on 15, where there is not much trafic now, and the background noise are a bit lower.

**Comment by AutoHass8** [comment]
In that case you might consider moving ZigBee to channel 11, to get out of the WiFi channel 6 sidelobe. 
Have a look at this: https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html

**Comment by fribse** [comment]
I've moved it to 11 in the deconz, so far it is more stable. I did loose connection to all the lights etc. but as far as I can see, they are coming back...
Now I just have to wait to see if it has helped

**Comment by fribse** [comment]
It didn't help enough, so now I've reset the entire deconz, uninstalled it from HA, reinstalled it, and I'm starting over, darned what a job... But for now the zigbee network has been rocksolid...

**Comment by Smanar** [comment]
> It didn't help enough, so now I've reset the entire deconz, uninstalled it from HA, reinstalled it, and I'm starting over, darned what a job... But for now the zigbee network has been rocksolid...

So it mean, the problem was from something in the database ?

**Comment by fribse** [comment]
@Smanar It would seem so yes. First of the channel clashing has been resolved, secondly the entire system is reset.
While enlisting all the sensors and switches again, I do have some problems with items appearing without me resetting anything, and leaving small odd items with invalid 4-hexcode names.

**Comment by fribse** [comment]
Looking in deconz, after doing the reset, the network seems cleaner as well, most sensors, even if being xiaomi, or the spirit thermostat has attached to a 'local' router?
