### ISSUE TITLE
Loosing Connection to CONBEE while using another  Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller

### ISSUE THREAD

**Issue by basty2** [dresden-elektronik/deconz-rest-plugin#511]
I'm using Conbee and it works. But if I connect a CP2102 deconz program is loosing the connection to the usb stick. 
`usb-FTDI_FT230X_Basic_UART_DO00KCJP-if00-port0 -> ../../ttyUSB0
usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -> ../../ttyUSB1`
The CP2102 works fine. If I disconnect the cp2102, deconz works again. Is it possible to use both sticks?

Additionaly, deconz shows me, that i have to update the firmware. After updating, It shows the update again... 

Update2: Maybe that's because I using with CP2102 with a homematic uart connector and deconz is thinking, that this is a raspbee? Is it possible to define that I'm using conbee with fixed usb device?

**Comment by manup** [comment]
Hm strange once deCONZ has a connection to ConBee it should keep it open, so normally if you connect the other dongle after connection is established it should still work.

Can you please provide the output of `$ lsusb`?

**Comment by basty2** [comment]
only conbee stick: 
`~$ lsusb
Bus 002 Device 003: ID 174c:5106 ASMedia Technology Inc. ASM1051 SATA 3Gb/s bridge
Bus 002 Device 005: ID 174c:55aa ASMedia Technology Inc. ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge
Bus 002 Device 004: ID 05e3:0743 Genesys Logic, Inc. SDXC and microSDXC CardReader
Bus 002 Device 002: ID 05e3:0612 Genesys Logic, Inc.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 107: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 114: ID 0bda:0153 Realtek Semiconductor Corp. Mass Storage Device
Bus 001 Device 003: ID 8087:0a2a Intel Corp.
Bus 001 Device 078: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
with cp2102 

`~$ lsusb
Bus 002 Device 003: ID 174c:5106 ASMedia Technology Inc. ASM1051 SATA 3Gb/s bridge
Bus 002 Device 005: ID 174c:55aa ASMedia Technology Inc. ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge
Bus 002 Device 004: ID 05e3:0743 Genesys Logic, Inc. SDXC and microSDXC CardReader
Bus 002 Device 002: ID 05e3:0612 Genesys Logic, Inc.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 107: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 118: ID 0403:6015 Future Technology Devices International, Ltd Bridge(I2C/SPI/UART/FIFO)
Bus 001 Device 117: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 003: ID 8087:0a2a Intel Corp.
Bus 001 Device 078: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`

**Comment by manup** [comment]
Sorry I don't know what is causing the problem I thought both devices where FTDI based with IDs 0403:6015 which could confuse deCONZ but this doesn't seem to be the case here.

**Comment by basty2** [comment]
Maybe this helps. at 08:37 I connected the cp2102 and got errors.

![30](https://user-images.githubusercontent.com/33844675/38059151-ae4312e0-32e5-11e8-9324-4ecffb281287.JPG)

**Comment by manup** [comment]
It looks that the connection drops out, maybe there is some udev rules script which triggers then the other dongle is attached.

**Comment by basty2** [comment]
thank you. it seems a problem with fhem, steering the homematic stick and conbee. I have to take a look tomorrow.

**Comment by basty2** [comment]
Hi. I don't really know what is the reason. after flashing the firmware on both sticks it seems to be working again...
