### ISSUE TITLE
Aqara Mini Switch / Button Automations broken with v2.12.2-beta

### ISSUE THREAD

**Issue by peer69** [dresden-elektronik/deconz-rest-plugin#5114]
## Describe the bug

Updating to v2.12.2-beta broke automations for Aqara Mini Buttons / Switches (maybe even other automations but atm I only use these via Phoscon). 

## Steps to reproduce the behavior

Automations (lights on/off, calling scenes) do not work via Aqara Switches when running v2.12.2-beta. Reverting to .1-beta fixes this. 
## Environment

 - Host system: ESXi Host
 - Running method: (Ubuntu 18.04)
 - Firmware version: (266E0700)
 - deCONZ version: (2.12.2-beta)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes)
 - Is there any other USB or serial devices connected to the host system? No.

**Comment by Mimiix** [comment]
Can you please provide logs?

**Comment by peer69** [comment]
Not yet. As this breaks my wife's current work environment I'll have to wait for updating again to not cause any serious real world issues.

**Comment by Mimiix** [comment]
Without any logs or pointers, we can't do anything in this case to fix it.

For anyone facing the same issue and ending up here:  Please open a new issue with corresponding logs.

I'll close this issue.
