### ISSUE TITLE
CASA.IA - Sonde de température déportée sur câble Zigbee  Référence CTHS-317-ET

### ISSUE THREAD

**Issue by oisif5324** [dresden-elektronik/deconz-rest-plugin#5116]
link
https://www.domadoo.fr/fr/peripheriques/5572-casaia-sonde-de-temperature-deportee-sur-cable-zigbee-3770021021052.html

## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other:

**Comment by Mimiix** [comment]
No information provided at all.

Please submit all required information
