### ISSUE TITLE
IKEA Trådfri motion sensor battery drain

### ISSUE THREAD

**Issue by sveip** [dresden-elektronik/deconz-rest-plugin#512]
After some unscientific measurements it seems that the motion sensor is loosing battery faster when connected to Deconz compared to the IKEA hub.

Might there be some polling going on that can cause this and preventing it to sleep?

**Comment by manup** [comment]
Nope, the sensor works on its own and sends out just the motion sensed commands and battery level reports. Do you have the latest firmware of the sensor?

**Comment by sveip** [comment]
Thanks for the fast replay. Ok, was probably difference in the batteries (poorer batteries when on Deconz.)

Is there a way to update the firmware from deconz, or do I have to move it back to the IKEA hub?

**Comment by sveip** [comment]
@manup, is the update feature just present in the Qt UI, or also web? Can't seem to find it in webui, and I run headless.

**Comment by manup** [comment]
For battery powered end-devices, currently it can only be activated via gui.
