### ISSUE TITLE
Deconz package not found on raspberry debian

### ISSUE THREAD

**Issue by xiki808** [dresden-elektronik/deconz-rest-plugin#5129]
## Describe the question or issue you are having
I have debian buster on raspberry pi 4 and I cannot install deconz apt package on the system, it gives me: E: Unable to locate package deconz

I am following the Raspbian steps as per the Installation steps. I have tried same steps on raspbian and I had no problems.

What can I do to install deconz on debian on raspberry pi?

## Environment
 - Host system: Raspberry Pi
 - Running method: on raspberry Debian
 - Device: ConBee II

**Comment by Smanar** [comment]
In waiting for an update, can try this link perhaps https://deconz.dresden-elektronik.de/debian/ ?

**Comment by xiki808** [comment]
Thank you this worked!
