### ISSUE TITLE
CASA.ia Temperature probe CTHS-317-ET

### ISSUE THREAD

**Issue by arenoux** [dresden-elektronik/deconz-rest-plugin#5138]
## Device

- Product name: Temperature Probe CTHS-317-ET
- Manufacturer: CASAIA
- Model identifier: CTHS317ET
- Device type :
  - Sensor

### Node INFO

![image](https://user-images.githubusercontent.com/9109753/126156132-c3d1af27-8979-4746-8f84-67d83e23a251.png)

### Basic
![image](https://user-images.githubusercontent.com/9109753/126155738-916d1691-660a-4a3a-9afa-69ce2c105046.png)

### Identify

![image](https://user-images.githubusercontent.com/9109753/126155985-50f29597-4c87-4a39-ad4b-4b09d32b9a3b.png)

### Device Temperature

![image](https://user-images.githubusercontent.com/9109753/126333570-890aba4d-fbfe-4d3b-b206-d208c042e360.png)

###### Power configuration
![image](https://user-images.githubusercontent.com/9109753/126333517-3e47f14a-4d4a-48ff-91e0-a44b5ee7e55b.png)

**Comment by SwoopX** [comment]
Please read the attributes of the power configuration cluster and update the screenshot accordingly, as this is required  to process the battery values appropriately.

**Comment by arenoux** [comment]
Hello @SwoopX.
I've just updated the Power Configuration and Temperatur Measurement clusters section with a screenshot (after reading the values)

**Comment by Smanar** [comment]
Hello.

@SwoopX have you started something ?
@arenoux have you a linux machine with full OS to test code modification ?

**Comment by SwoopX** [comment]
Nope

**Comment by delphiki** [comment]
I'd love to see this device integrated as well! :)

**Comment by arenoux** [comment]
Thanks for your job @Smanar .

I'm on holidays right now (not at home) it tried to launch a build (with docker procedure) on my raspi3 remotely but seems my raspi froze and does not respond right now... Will try again once back home beginning of September

**Comment by Smanar** [comment]
Yep same for me, my raspberry 3 freeze, I need to remove "-j2" on my side.
But even with that the first compilation need so much time.

**Comment by delphiki** [comment]
I can confirm that it's working with Home Assistant :+1: 

![Capture d’écran de 2021-08-28 13-22-49](https://user-images.githubusercontent.com/303778/131216368-4fbc2631-f895-4b71-bede-a95c49313ce9.png)

**Comment by Smanar** [comment]
Thx, PR submited

**Comment by arenoux** [comment]
Thank you so much all for this work :+1:
