### ISSUE TITLE
Error upgrading Conbee II Firmware 0x266f0700

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#5139]
## Describe the question or issue you are having
Error trying to upgrade firmware conbee II to 0x266f0700
See screenshot for error message.
cmd run as admin.

Any idea what I'm doing wrong here?

## Screenshots

![ConbeeII_01](https://user-images.githubusercontent.com/45151934/126176826-4473610b-f15f-4ea7-836c-1862ce576593.PNG)

![ConbeeII_02](https://user-images.githubusercontent.com/45151934/126177564-cbb285ae-a2f5-4866-8af1-e769eee4fdf5.PNG)

## Environment
DeConz Version v2.13.03
Firmware version 26580700

 - Host system: PC
 - Running method:  Windows / Virtual Machine (vSphere 7)
 - Firmware version: 26580700
 - deCONZ version: 2.13.03
 - Device: ConBee II
 - Do you use an USB extension cable:  yes
 - Is there any other USB or serial devices connected to the host system? Yes: rfx433Mhz, Sigma Z-wave, see screenshot, Note!! rfx433 usb device removed during upgrade.

**Comment by Mimiix** [comment]
You are using a vm. 

Try it on a native machine :)

**Comment by PrimaryInc** [comment]
@Mimiix, thanks for your reply. Upgrade has always worked on vm using conbee stick, (gen 1) So I could move it to another pc, that is possible, biut stil the question is why this is happening on conbee II, is it vSphere 7 that is a problem, something else? DeConz been runing on windows server from day 1 and for a few years without seeing this issue. Would be great to understand why this is happening, and make a note of it in the upgrade guide if it cannot be done.

**Comment by Mimiix** [comment]
Probably because of the Disconnect thats caused by the update. The VM software is not able to properly re-attach it again. I am not knowledgeable on the deeper knowledge on this.

**Comment by Smanar** [comment]
I don't know what is vSphere but there is that in the upgrade guide

> Warning: It is strongly advised to use a native installation of one of the update methods. Virtual Machines may work but are not supported, using a VM while trying to update firmware is on your own risk.

**Comment by PrimaryInc** [comment]
@Mimiix, ok then upgrade of host it is. Thanks again.

@Smanar, vSphere is VMware. As stated worked for years but no longer. But yeah, your point is taken :) Thanks!

**Comment by Mimiix** [comment]
@PrimaryInc Perhaps something changed in how vspehere does USB mounting. Or how the GCFlasher works. I have really no clue. _Something_ must have changed _Somewhere_.

**Comment by PrimaryInc** [comment]
@Mimiix, for sure :) Non the less, updatet usin an pc, works just fine.
