### ISSUE TITLE
Unique id  for groups

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#514]
Would it be possible to generate a unique id for groups (all virtual devices) on creation? This would help with keeping in line with other devices and would help improve the integration with home assistant.

**Comment by marthoc** [comment]
Hi @manup - it would also be helpful for the Home Assistant integration if the Daylight sensor had a uniqueid generated for it. All other sensors should have a uniqueid (I think all hardware-based devices would and CLIP sensors should since the uniqueid field is required when creating a sensor over the api). But since Daylight is an automatically created sensor, there is no opportunity to specify a uniqueid and that field can't be added via a REST call. I do realize that the Hue API (on which the Daylight sensor seems to be based) does not generate a uniqueid for that sensor either (an issue I have raised on the Hue developer forums too).

**Comment by manup** [comment]
Sure I'm fine with giving it a uniqueid, any suggestions? — something mac address like *00:00:00:00:00:00:00::01*?

**Comment by marthoc** [comment]
Yes a MAC address would be fine, that would make it similar to other devices. Since it's unique to the bridge (I would think there is only one of these since it's created automatically) it's uniqueid could also be based on the bridge's UUID or something similar?

**Comment by manup** [comment]
Yes it could be derived from the bridge mac address: *00:21:2e:ff:ff:xx:yy:zz-01*

**Comment by marthoc** [comment]
That sounds like it would work well! Thanks.

**Comment by Kane610** [comment]
@manup I don't get any uniqueid reported when requesting /api/**key**

**Comment by marthoc** [comment]
@kane610 I think you may have to delete and recreate the group?

**Comment by Kane610** [comment]
@marthoc did they add uniqueid for groups recently? I moved everything over just over a month ago.

**Comment by Kane610** [comment]
@marthoc then disregard previous comment since I haven't upgraded, didn't know it was fixed.

**Comment by Kane610** [comment]
Hi!

As far as I can tell I still don't get unique ids for groups. Even though I've added new devices and created new groups.

/R

**Comment by Kane610** [comment]
I have tried and played around and I still don't get unique ids for groups. Am I doing something wrong?

**Comment by helto4real** [comment]
I tried to add new group to deconz and I did not get id of the group. If so Home Assistant would pick it up as new device. If it not show as device I cant use it in areas and have to manage individual lights in my automations. Is it OK if someone check this one out again? @Kane610 Is this not correct?

**Comment by Kane610** [comment]
@manup this issue is still relevant I believe

**Comment by manup** [comment]
Just checked the code, currently a `uniqueid` attribute in form of  `AA:BB:CC:DD` or `AA:BB:CC:DD-XX` can only be specified when a group is created.

Otherwise the normal `id` attribute should be used, since it already *is* a uniqueid within the Zigbee space.

**Comment by helto4real** [comment]
Yea strange that I don't seem to get unique id when I create new group. You think it can have to do with that there are older groups there too?

**Comment by justme-1968** [comment]
please make sure uniqueid is unique or empty. never have more than one device with the same id.
