### ISSUE TITLE
CASA.IA - Sonde de température déportée sur câble Zigbee

### ISSUE THREAD

**Issue by oisif5324** [dresden-elektronik/deconz-rest-plugin#5140]
## Device

- Product name: Sonde de température déportée sur câble Zigbee.
- Manufacturer: CASA.IA
- Model identifier: CTHS-317-ET
- Device type : sensor
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other: 

## Screenshots
![image](https://user-images.githubusercontent.com/25404484/126206959-4bf8e991-81d9-41e8-ac21-71097dec3650.png)

### Device Temperature
https://www.domadoo.fr/fr/peripheriques/5572-casaia-sonde-de-temperature-deportee-sur-cable-zigbee-3770021021052.html

**Comment by Mimiix** [comment]
There is not any screenshots attached.
