### ISSUE TITLE
ikea tradfi Remote - no 1002 event on button press

### ISSUE THREAD

**Issue by erazorv** [dresden-elektronik/deconz-rest-plugin#5144]
## Describe the bug
if I press the button in the middle of the switch there are no 1002 event only 1001 after long press
Other buttons are without issue

## Steps to reproduce the behavior
I check the home assistant event from deconz but also no affect in deconz interface after configuration
i pressed the button multiple times, also checked a second device
## Environment

 - Host system: Raspberry Pi 4
 - Running method:Home Assistent deCONZ Add-on
 - Firmware version: 26390500
 - deCONZ version: 2.11.5
 - Device: RaspBee II
 - Is there any other USB or serial devices connected to the host system? If so: Which? NO

**Comment by SwoopX** [comment]
See #4900
