### ISSUE TITLE
Firmware 0x266f0700 in the wrong online folder

### ISSUE THREAD

**Issue by JornDL** [dresden-elektronik/deconz-rest-plugin#5145]
Hi

Just to let you know – the firmware for the
ConBee II and RaspBee II 0x266f0700 2021-07-13

Which according to the Firmware Changelog is a beta version, is actually put in the stable folder
https://deconz.dresden-elektronik.de/deconz-firmware/ and not in the beta folder
https://deconz.dresden-elektronik.de/deconz-firmware/beta/

**Comment by Mimiix** [comment]
@JornDL I've forwarded it to Manup. Thanks for the headsup!
Feel free to ignroe the bot ;)
