### ISSUE TITLE
Aqara/Xiaomi devices are reported as "unknown" or of the wrong type

### ISSUE THREAD

**Issue by leonardpitzu** [dresden-elektronik/deconz-rest-plugin#5147]
## Describe the bug
I have fitted my entire house with aqara relays (https://www.aliexpress.com/i/33002564031.html) - all from the same batch.
They work great with some minor problems.
The relays are reported as LUMI devices but some are "unknown"

## Steps to reproduce the behavior
open Phoscon and look at the device manufacturer, name and category (sensor, light, etc.)

## Expected behavior
both channels of the aqara relays shall have the same manufacturer (Lumi) and the (Smart Relay)
Aqara motion sensors shall all have displayed the temperature and light intensity (some are mossing the temperature and lux)

## Screenshots
![Screenshot 2021-07-21 141107](https://user-images.githubusercontent.com/4321813/126480833-ff9fe94f-59f4-44c0-9372-f5d8c04cffce.png)

## Environment
ver: 2.12.02 / 5/9/2021
fw: 26660700
tried it with the latest stable and beta with the same result
host: Raspberry Pi
running method: raspbian, native install
device: conbee II

**Comment by Mimiix** [comment]
Hi,

This repository only contains bugs for deCONZ and not for Phoscon. Please report them in either https://github.com/dresden-elektronik/phoscon-app-beta/issues or on the forums: https://forum.phoscon.de/c/phoscon/general-support/19

Closing this issue.
