### ISSUE TITLE
Mi Motion Sensor not working as expected

### ISSUE THREAD

**Issue by leonardpitzu** [dresden-elektronik/deconz-rest-plugin#5149]
## Describe the bug
I have 5 motion sensors from Xiaomi (Mi Motion Sensor). Sensor #1 work as expected (see screenshot below) - it detects motion and reports temperature and light intensity as well. The next 4 sensors only report motion - temperature and light intensity are always 0. Also these 4 sensors become unavailable after some time and need to be re-paired.

## Steps to reproduce the behavior
open deconz/phoscon -> the sensors and their data should be visible and one can easily see what's missing.

## Expected behavior
all motion sensors should report the same data and stay connected (e.g. should not need re-pairing every now and then)

## Screenshots
first sensor is, the next are working strange
![Screenshot 2021-07-21 145542](https://user-images.githubusercontent.com/4321813/126490144-b2aa2121-2bc1-4ea5-b32f-5b47ce74f24c.png)
this is the good sensor
![good](https://user-images.githubusercontent.com/4321813/126490150-1c05287a-2f3b-4bbb-863d-ccfd4bb03901.png)
these are working bad
![bad](https://user-images.githubusercontent.com/4321813/126490159-cc72e97c-ac11-464d-aa50-943d2f7a96fb.png)

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.12.02 (tested with beta and stable)
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment]
Can you check the Basic clusters and provide the model ID and manufacturer ID?

**Comment by leonardpitzu** [comment]
i can only read the Basic cluster for the first sensor, for the next 4 it's not working. I tried rebooting and doing the basic stuff. Any hints how to "get this going"?

**Comment by SwoopX** [comment]
Neither the node descriptor nor the clusters are read correctly. Those devices are known to be shi**y. Try reset and re-pair until it works

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by leonardpitzu** [comment]
@Mimiix - thanks for the link, i was able to read the damn thing.
![Screenshot 2021-07-21 160438](https://user-images.githubusercontent.com/4321813/126493213-f14f4ec2-4cf6-49d9-a2bb-364fbfc04b61.png)

**Comment by Mimiix** [comment]
Can you also read the others?

**Comment by leonardpitzu** [comment]
all other 4 sensors are the same as this one

![Screenshot 2021-07-21 162123](https://user-images.githubusercontent.com/4321813/126495735-812cf4bb-0ead-469a-a351-c0d02f207830.png)
![Screenshot 2021-07-21 162147](https://user-images.githubusercontent.com/4321813/126495738-85cdaea8-95a8-4047-b1b0-9093ef2f0b55.png)
![Screenshot 2021-07-21 162206](https://user-images.githubusercontent.com/4321813/126495742-abc4577b-1144-4bd0-bb32-53ead01f2b70.png)
![Screenshot 2021-07-21 162238](https://user-images.githubusercontent.com/4321813/126495745-f577c669-bfcf-4e09-8100-f2efce1c712e.png)

**Comment by Mimiix** [comment]
No, i mean the Basic clusters of the devices that show "correct:" info and whioch do not.

I want to compare the modelID and Manuf ID with all your working and non working motion sensors

**Comment by leonardpitzu** [comment]
you already have it:
Storage Room Motion Sensor -> correct
Bedroom Motion Sensor -> bad

**Comment by leonardpitzu** [comment]
good
![good](https://user-images.githubusercontent.com/4321813/126498099-0e5a90cd-2975-43a5-82fe-58e3fcb0a13a.png)



bad
![bad](https://user-images.githubusercontent.com/4321813/126498111-4ae45fc5-989d-4b6f-8361-74b8eb06b589.png)

**Comment by Mimiix** [comment]
Thats my point :)

Theres 2 types. The one with lux etc and without. They have different Model numbers on the bottom as well.

Obviously, the software cant report what it doesn't "sense" 😢.

**Comment by leonardpitzu** [comment]
The are the same for me - same box, case, code/label, etc. I ordered 5 and i got 1 + 4. What can i say except for "crap"...

**Comment by leonardpitzu** [comment]
yeap... long live aliexpress

**Comment by Mimiix** [comment]
Sorry to hear that :(

Perhaps you can reach out to the seller.

Either way, closing this issue
