### ISSUE TITLE
Correct Attributes for sensors that provide energy consumption

### ISSUE THREAD

**Issue by drthanwho** [dresden-elektronik/deconz-rest-plugin#5163]
## Describe the bug

With the upcoming HA Core release (2021.8) [Energy ](https://rc.home-assistant.io/docs/energy/) is introduced, part of which enables logging and viewing of individual device's energy consumption. In order for this to work the devices are filtered and only the ones that have entities that are in KWh with `device_class: energy` , `state_class: measurement` and  `last_reset` value for attributes can be used. Therefore, for plugs that support and created sensors for overall energy consumption (not power) should include these attributes.  

For now the alternative is to manually customise entities to add these attributes but that is merely a workaround not a solution.
## Screenshots

![image](https://user-images.githubusercontent.com/22405505/127525081-eaad2d02-e6d5-4b66-b333-80b1a9ba058f.png)

## Environment

N/A

**Comment by Mimiix** [comment]
Hi there.

This is not the correct repository. You should report to the home assistant repository.

Kind regards,
