### ISSUE TITLE
Sensors disappear after deCONZ restart

### ISSUE THREAD

**Issue by previn1980** [dresden-elektronik/deconz-rest-plugin#5166]
## Describe the bug
Hello. Everything works perfectly with my ConBee II and Xiaomi Sensors, but every time I restart deCONZ (gently with File>QUIT, or brutally killing application, or restarting raspberry) one or more sensors disappear. They are visible in the web app, but they don't update their state. Watching the log I noticed that they are stored in the deCONZ DB.
I've tried to follow the workaround I've found here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2273. 
I've also tried resetting sensor twice immediately, but with no luck (after this operation, I noticed that it disappeared from the log the warning "Missing cluster in sensor fingerprint").

When I reset missing sensors, their state returns online and they continue to work without troubles.
I've tried running deCONZ in all the alternative ways: as a service, directly with the sh, platform minimal, with the GUI...

I've shared a log where you can find only one sensor survived and its name is "Studio". All the sensors have new batteries and are quite close (in the range of 4-5 meters) to ConBee and with no obstacles.

This problem is extremely ennoying and I appreciate any help. 
Can I help you with more information?

Thank you very much!

Andrea

## Steps to reproduce the behavior
I tried a lot before opening this bug and I noticed that the problem affects a larger number of sensors, proportionally to the running time of deCONZ. If I start deCONZ, I reset sensors and then I immediately restart deCONZ, more o less all the sensors survive, but if I restart deCONZ after a few days, every sensor disappear. I don't know if it's only my suggestion...

## Expected behavior
Sensors should be available after deCONZ restart.

## Screenshots
None

## Environment

 - Host system: Raspbery
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: (2.11.5)
 - Device:  ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
[debug.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/6907805/debug.txt)

## Additional context
None

**Comment by Mimiix** [comment]
Hi there!

As mentioned in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5113 , Any issues that aren't clearly bugs are forwarded to the forums https://forum.phoscon.de

I've clarified this in the 5113 issue.

Closing.
