### ISSUE TITLE
No adding/pairing an Aqara Water Leak Sensor 

### ISSUE THREAD

**Issue by drheck** [dresden-elektronik/deconz-rest-plugin#5167]
## Describe the bug

  I have bought the conbee II stick and i have paired Aqara motion sensor. 
  But i can not pair my aqara water leak sensors.
  With the aqara app and aqara hub it works.

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:
  I try to pair and nothing happens.

## Expected behavior
  Pairing

## Environment

 - Host system: Raspberry Pi 4 B
 - Running method: Deconz Image with homebridge-hue
 - Raspbian GNU/Linux Buster (10)
 - Firmware version:  26660700
 - deCONZ version: (2.12.01 / 14.6.2021)
 - Device: ConBee II
 - Do you use an USB extension cable: no -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? NO

**Comment by Mimiix** [comment]
Hi there!

As mentioned in #5113 , Any issues that aren't clearly bugs are forwarded to the forums https://forum.phoscon.de

I've clarified this in the 5113 issue.

Closing.
