### ISSUE TITLE
Tuya ZigBee 4 Gang Wireless 12 Scene Switch Push Button Controller Device

### ISSUE THREAD

**Issue by igorrotxategi** [dresden-elektronik/deconz-rest-plugin#5172]
## Device

- Product name: Scene switch
- Manufacturer: TZ3000_xabcloclv
- Model identifier: TS004F
- Device type : Please remove all unrelated device types. 
  

  - Switch
 

## Screenshots

![photo_2021-06-06_15-39-35](https://user-images.githubusercontent.com/78226326/127851468-44ce0f30-9a03-4f36-815d-e9ed67ebca0c.jpg)
![photo_2021-08-02_12-39-52](https://user-images.githubusercontent.com/78226326/127851471-a4ede852-981a-45d9-b726-dd8fd7517291.jpg)
![photo_2021-08-02_12-39-55](https://user-images.githubusercontent.com/78226326/127851473-6e2b2046-e9ea-404e-91ad-612b286204ab.jpg)
![BASIC CLUSTER](https://user-images.githubusercontent.com/78226326/127851474-c0081147-d5c1-4479-b3af-a60eaffb52d2.PNG)

  Screenshots help to identify the device and its capabilities. Please refer to:
  https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support
  for examples of the required screenshots.

  Required screenshots:
  - Endpoints and clusters of the node
  - Node Info panel

  In the Cluster Info panel press "read" button to retreive the values. Please note that at least "Manufacturer Name" and "Model Identifier" must be populated with data (therefore, must not be empty), otherwise that information will not be usable. For battery powered devices, after pressing read it is required to wake-up the device by pressing a button or any other means of interaction.
-->

**Comment by Smanar** [comment]
I think it s a clone of this one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4810

Do you have a linux machine with full os to test code changes ?

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by igorrotxategi** [comment]
> I think it s a clone of this one #4810
> 
> Do you have a linux machine with full os to test code changes ?

Thank you very much for your response. 
I readed the post you have said and is the same product that i have. 
I am using a raspberry pi with hassio, so i don´t have linux machine to test code changes

**Comment by Mimiix** [comment]
As it's the same, i'm closing this one. @Smanar please continue in the other one.
