### ISSUE TITLE
After Power outage certain lights no longer respond (but bulbs are on)

### ISSUE THREAD

**Issue by mruepp** [dresden-elektronik/deconz-rest-plugin#5184]
## Describe the bug

So I had a power outage recently. Since then, two bulbs (osram lightify) are not responding anymore. The corresponding icons in the deconz gui are greyed out and the bulbs are lit). This is the second time this happened. The first time I tried to reconfigure the light but it continued to get lost. Restarted the pi, did everything.

## Environment

 - Host system: (Raspberry Pi / PC / NAS)
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

**Comment by Mimiix** [comment]
Hi there!

As mentioned in #5113 , Any issues that aren't clearly bugs are forwarded to the forums https://forum.phoscon.de

Closing.
