### ISSUE TITLE
Tuya Zigbee Curtain module QS-Zigbee-C01

### ISSUE THREAD

**Issue by incognitomailincognitomail** [dresden-elektronik/deconz-rest-plugin#5189]
Following the discussion https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3939 (already closed)
Someone cab explain how to connect to curtain module, I didn't find calibration dialogs in deCONZ plugin
And how I can edit general.xml file.

![](https://user-images.githubusercontent.com/88643642/128659867-ebd78caf-e6f8-4153-aa2e-a0434affbd3a.PNG)

![](https://user-images.githubusercontent.com/88643642/128659869-87fe1f0d-8dcb-4f12-8c20-e06da18962ac.PNG)

![](https://user-images.githubusercontent.com/88643642/128659867-ebd78caf-e6f8-4153-aa2e-a0434affbd3a.PNG)

**Comment by incognitomailincognitomail** [comment]
Which template? 
I see only 2 templates 
![image](https://user-images.githubusercontent.com/88643642/128674894-d5c75a20-719a-4622-bf88-c03662a6490a.png)

**Comment by Mimiix** [comment]
@incognitomailincognitomail I suggest to use the forums for this question :)
