### ISSUE TITLE
Tannhäuser Gate ⋅ v2.12.4 beta kein anlernen möglich

### ISSUE THREAD

**Issue by sansonifabio** [dresden-elektronik/deconz-rest-plugin#5204]
## Describe the bug

Hallo seit dem Update auf Tannhäuser Gate ⋅ v2.12.4 beta können keine Lichter, Schalter oder Sensoren angelernt werden. 

## Steps to reproduce the behavior
Geräte
Sensoren
Sensor hinzufügen
 

 If the problem is reproducable, list the steps here:

  Beim Downgrade auf die 2.12.03 funktioniert es wieder.

## Environment

 - Host system: (Raspberry Pi )
 - Running method: (Raspbian)
 - Firmware version: (26690700)
 - deCONZ version: (v2.12.4)
 - Device: ( RaspBee II)
 - Do you use an USB extension cable: ( no) -- only relevant for ConBee I/II
 

## Additional context
Beim Downgrade auf die 2.12.03 funktioniert es wieder.

**Comment by Mimiix** [comment]
Hi,

In the future, please:
- check the existing issues. This report already exists. A fix is in there too: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5197
- Write in English.
Closing this issue.

**Comment by sansonifabio** [comment]
Hi,
ich kann kein Englisch, dann halt gar nicht mehr.

**Comment by Mimiix** [comment]
I suggest using Google translate :)

**Comment by sansonifabio** [comment]
Okay how complicated most users are German. But okay
