### ISSUE TITLE
TS0504B Tuya Zigbee DC5V 12V 24V 5050 RGBW Smart LED Strip Controller

### ISSUE THREAD

**Issue by majorsl** [dresden-elektronik/deconz-rest-plugin#5220]
## Device

- Product name: TS0504B Tuya Zigbee DC5V 12V 24V 5050 RGBW Smart LED Strip Controller
- Manufacturer: _TZ3000_ukuvyhaa
- Model identifier: TS0504B
- Device type : Please remove all unrelated device types. 
  - Light

## Screenshots

![image](https://user-images.githubusercontent.com/3105401/129976285-e1b2c521-3284-4150-9829-2db32b610eda.png)
![image](https://user-images.githubusercontent.com/3105401/129976347-d8643e48-2194-4d2a-ae9e-503a27c9134b.png)
![image](https://user-images.githubusercontent.com/3105401/129976381-742420e7-87c0-49f5-814c-66a96cbd3024.png)

### Basic
![image](https://user-images.githubusercontent.com/3105401/129978110-10de3c90-34c4-4266-a294-4100be8f5400.png)

### Identify
![image](https://user-images.githubusercontent.com/3105401/129978206-1dab8ed4-634d-457f-983e-3ddb9c917dda.png)
![image](https://user-images.githubusercontent.com/3105401/129978237-47bbfb77-8805-4121-b77f-425a50034600.png)

### Groups
![image](https://user-images.githubusercontent.com/3105401/129978283-464761fa-ce14-4086-82fa-4ffa92796f39.png)
![image](https://user-images.githubusercontent.com/3105401/129978294-4e44ceb0-3459-49b6-b31f-26a544f276a8.png)

### Scenes
![image](https://user-images.githubusercontent.com/3105401/129978333-c5daabc2-bb6d-4546-8593-89899c7fe75b.png)
![image](https://user-images.githubusercontent.com/3105401/129978343-9bbc7523-0ce8-44ab-a753-7ece69dca9ff.png)

### On/Off
![image](https://user-images.githubusercontent.com/3105401/129978377-8512a70f-2d5f-4726-8c1b-8485f15bb5a6.png)
![image](https://user-images.githubusercontent.com/3105401/129978389-3ca35bed-f502-4e24-b17b-9017391486cc.png)

### Level Control
![image](https://user-images.githubusercontent.com/3105401/129978434-3f4dbb7d-ad29-493b-847d-dfc9559bda18.png)
![image](https://user-images.githubusercontent.com/3105401/129978446-326524f1-aaf0-41db-b023-3ebcb0eeeb44.png)

### Color Control
![image](https://user-images.githubusercontent.com/3105401/129978469-c8b4fbce-c099-4b45-9e25-95ba02eae9eb.png)
![image](https://user-images.githubusercontent.com/3105401/129978482-09acc2a7-294a-45b1-bff2-a234f0e09d9f.png)
![image](https://user-images.githubusercontent.com/3105401/129978493-a153fb40-a8a5-49d7-b745-7ba3dee4fe5c.png)
![image](https://user-images.githubusercontent.com/3105401/129978504-8b0165cb-ce24-471e-886e-7abc2f1bfbc7.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/3105401/129978547-fca97200-79fa-4a91-bc1c-080116994f8a.png)
![image](https://user-images.githubusercontent.com/3105401/129978561-7efcbe96-b987-4f6c-a4ae-79e9ff3213ea.png)

### Notes
Device is seen by Phoscon.  Red and Green channels appear to be reversed, but RGB does work.  On my 5050 strips there are "white" separate LEDs but no color temp on them (just cool white). Phoscon show a white color temp slider when there shouldn't be one (brightness only) AND currently it doesn't do anything to activate the white LEDs.

Took a chance on this for $6US on AliExpress as they are the same as the WiFi versions I'd like to replace with Zigbee and these would be drop in replacements in tight spaces. I hope I got all the requested info, I only ever did one other device request here.  This model is supported with zigbee2mqtt if anything in their database helps.

**Comment by majorsl** [comment]
GAH, apparently pasting from a Mac fails HORRIBLY with GitHub.  I'll try to edit.

**Comment by thomy3k** [comment]
Hello, i'm even very interested in this topic.  May I help with any Screenshots, sonething else....?. Sorry for my poor englisch und programming abilities..... Greetings

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping.

**Comment by Smanar** [comment]
IDK, need to hack some values.
Perhaps possible using an external JS file, but seriously too much complicated for me.

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping.

**Comment by majorsl** [comment]
Ping

**Comment by majorsl** [comment]
Ping

**Comment by majorsl** [comment]
Ping

**Comment by majorsl** [comment]
Ping

**Comment by majorsl** [comment]
Ping

**Comment by majorsl** [comment]
Ping

**Comment by Mimiix** [comment]
@Smanar  can this be done with DDF?

**Comment by Smanar** [comment]
Not simple with DDF https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5220#issuecomment-1061950218
This device is realy not standard
