### ISSUE TITLE
Xiaomi Aqara D1 2-gang QBKG22LM (no neutral wire) - Xiaomi Disconnect 1/2 attributes in Basic cluster missing

### ISSUE THREAD

**Issue by 7leman7** [dresden-elektronik/deconz-rest-plugin#5223]
**Describe the bug**
Xiaomi Disconnect 1/2 attributes missing in Xiaomi Aqara QBKG22LM node Basic cluster, hence switching the device in decoupled mode is not possible.

**Steps to reproduce the behaviour**
Connect Xiaomi Aqara QBKG22LM via "Add new switch" button in Phoscon (device becomes visible as 2 plugs + 2 lights). Check the available attributes of the node in deConz.

**Expected behavior**
Xiaomi Disconnect 1/2 attributes are expected in Xiaomi Aqara QBKG22LM node Basic cluster to enable switching the device in decoupled mode (as described here: [link](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1816#issuecomment-674511033.)) A.m. method confirmed to be working on QBKG22LM previously here: [link](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4199)

**Screenshots**
![129810106-fa433c8d-408c-4191-ab9f-9ff391a21196](https://user-images.githubusercontent.com/80063876/130097442-d1ca1c3e-a708-438e-ba0b-d677bfdbef50.png)

**Environment**
Host system: Intel NUC
Running method: Home Assistant deCONZ Add-on
Firmware version: (26680700)
deCONZ version: (2.11.5)
Device: ConBee II
Do you use an USB extension cable: no
Is there any other USB or serial devices connected to the host system? If so: Aeotec Z-Stick 7

**Comment by SwoopX** [comment]
This is no bug as deconz exposes some attributes based on the node descriptor it receives from the device. Is I know the device should have a manufacturer code of 0x1037 and also other attributes depending on that are missing in your screenshot, the conclusion is that the device either hasn't sent or incompletely sent the node descriptor.

I'd suggest to re-pair the device If you, however, still feel something needs to be addressed, please head over to the forum (https://forum.phoscon.de/). Thanks!
