### ISSUE TITLE
Sengled Smart Plug E1C-NB7

### ISSUE THREAD

**Issue by emnclarke** [dresden-elektronik/deconz-rest-plugin#5225]
## Device

- Product name: Smart Plug
- Manufacturer: sengled
- Model identifier: E1C-NB7
- Device type : Please remove all unrelated device types. 
  - Sensor (power monitoring)
  - Switch

## Screenshots

<img width="377" alt="image" src="https://user-images.githubusercontent.com/33589126/130162455-d0814b51-f92a-4a81-952b-dff5ef981002.png">

<img width="178" alt="image" src="https://user-images.githubusercontent.com/33589126/130162472-7c9c6ff0-707a-4cbd-b927-bf076077a749.png">

### Basic
<img width="412" alt="image" src="https://user-images.githubusercontent.com/33589126/130248263-b1b4b262-ad41-4956-9e40-299e933bc28a.png">

### Identify
<img width="355" alt="image" src="https://user-images.githubusercontent.com/33589126/130162587-55d3cb4a-77b2-452f-9a60-affd49d28059.png">

### Groups
<img width="358" alt="image" src="https://user-images.githubusercontent.com/33589126/130162690-937306cc-8e31-4aed-adbf-ef331bf4a0d4.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/33589126/130162705-22696195-fe36-4537-badc-20f5b427ae63.png">

### Scenes
<img width="359" alt="image" src="https://user-images.githubusercontent.com/33589126/130162733-4e8e22ad-80ee-40b4-9d55-678f76595514.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/33589126/130162916-a7e68a0b-aabb-4f7e-b84e-0db842fcd8e6.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/33589126/130163050-31d0ad44-6680-417b-8d7c-c5c8c2be561b.png">

### On/Off
<img width="473" alt="image" src="https://user-images.githubusercontent.com/33589126/130163092-c63abd3f-5f5c-422b-893d-4a7f6737d4aa.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/33589126/130248657-4e01e92a-3216-4239-a880-27e47b126acf.png">

### Simple Metering
<img width="419" alt="image" src="https://user-images.githubusercontent.com/33589126/130248889-aa5d2608-b19a-4476-8097-c4d43f5ffaf2.png">

### Diagnostics
<img width="413" alt="image" src="https://user-images.githubusercontent.com/33589126/130248979-02ed4b83-62a5-49b3-ac16-8c848470946f.png">

### OTAU
<img width="408" alt="image" src="https://user-images.githubusercontent.com/33589126/130249034-54826c0a-73a3-4918-b54b-1a70871e9587.png">

**Comment by emnclarke** [comment]
Updated screenshots, not all had "read" clicked beforehand.

**Comment by emnclarke** [comment]
Some additional info:
Gets added as a light and works as an on/off switch. Power monitoring info is not properly recognized by phoscon or via the restapi.

**Comment by asg8198** [comment]
Same here, eagerly awaiting fix.

**Comment by emnclarke** [comment]
bump

**Comment by KeeganCarter11** [comment]
I was also looking forward to seeing if these worked but sad to see this thread open for them.

**Comment by asg8198** [comment]
Please...

**Comment by Mimiix** [comment]
Thwy will come in 2.14

**Comment by emnclarke** [comment]
bump

**Comment by deviantintegral** [comment]
bump

**Comment by Mimiix** [comment]
@Smanar this can be done with a DDF?

**Comment by Smanar** [comment]
Hu ... I think 50%
The only cluster usable is the 0x0702, and from the capture, the only value we have are 0x0000 and  0x0400 "instantaneous demand"

I think tension/voltage/current are on unknow cluster.

For the first cluster ofc it s possible, but only for value 0x0000 and 0x0400.

**Comment by xconverge** [comment]
Is support for this device still slated for the next major release?

**Comment by Mimiix** [comment]
I was wondering if we cando it with a DDF. Would be easier.

**Comment by Smanar** [comment]
I can help you to make a DDF if you want, but you will have only power and consumption.

**Comment by xconverge** [comment]
@Smanar I have not successfully made a DDF yet and had data come out the other end. In my Control, I have it set to gold only currently, and just made my DDF "Gold", then I save it and hot-reload. I tried restarting deconz but still dont see anything over the REST API. Do I need to repair the device to have it use the DDF?

Also, I can run a debug build, is there anything to be gained by modifying the source code vs just using a DDF for this device?

I am willing to put in the legwork/testing work once again but would need some guidance

**Comment by xconverge** [comment]
@SwoopX helped me out, I will be opening a PR shortly

**Comment by xconverge** [comment]
Since this plug doesnt have electrical endpoints, just simple metering, I got power/consumption working, and to use power in home assistant I had to make a templated sensor that extracts the attribute from the consumption sensor

```
- platform: template
  sensors:
    power_1:
      unit_of_measurement: 'W'
      value_template: "{{state_attr('sensor.consumption_41', 'power') | float | round(0)}}"
      friendly_name: "Power 1"
```

I verified the value/conversion with a kill-a-watt and it is pretty accurate and responsive for obtaining watts

If anyone wants to test it, you can try the DDF I have in the referenced PR (And please comment here or there if you used it with luck or no luck)
