### ISSUE TITLE
crash after deconz update from 2.11.5 to 2.12.06

### ISSUE THREAD

**Issue by vantino** [dresden-elektronik/deconz-rest-plugin#5226]
## Steps to reproduce the behavior

on every reboot
## Environment

 - Host system: (Raspberry Pi3)
 - Running method: (Raspbian 
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.12.06)
 - Device: RaspBee II)
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? USB 64GB Stick

## deCONZ Logs

Aug 20 07:51:08 fhem systemd[1]: Started deCONZ: ZigBee gateway -- REST API.
Aug 20 07:51:08 fhem deCONZ[10198]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pi'
Aug 20 07:51:09 fhem deCONZ[10198]: libpng warning: iCCP: known incorrect sRGB profile
Aug 20 07:51:10 fhem deCONZ[10198]: This plugin does not support propagateSizeHints()
Aug 20 07:51:10 fhem deCONZ[10198]: This plugin does not support propagateSizeHints()
Aug 20 07:51:13 fhem deCONZ[10198]: This plugin does not support propagateSizeHints()
Aug 20 07:51:13 fhem systemd[1]: deconz.service: Main process exited, code=killed, status=7/BUS
Aug 20 07:51:13 fhem systemd[1]: deconz.service: Failed with result 'signal'.
Aug 20 07:51:13 fhem systemd[1]: deconz-init.service: Start request repeated too quickly.
Aug 20 07:51:13 fhem systemd[1]: deconz-init.service: Failed with result 'start-limit-hit'.

**Comment by Mimiix** [comment]
Not sure what the bug is. Please use the forum for support.

**Comment by vantino** [comment]
What forum you're talking?
Pls provide the link to 

thx
