### ISSUE TITLE
Multiple API requests handle

### ISSUE THREAD

**Issue by 0rsa** [dresden-elektronik/deconz-rest-plugin#5230]
Hi,
I have a lot of lights, about 100. My biggest group has about 25 lights.
I automated all my lights individually (auto brightness adjustment based on outdoor sensors lumens, colors defined for each moment of the day and so on).
I noticed that some requests are lost when I send a lot of requests at the same time.

I found a workaround adding a 200ms delay between queries and it looks like reliable now.

My question is quite simple: it is possible to improve queries management to avoid this use of workaround on client side?

Thank you.

**Comment by Mimiix** [comment]
For feature requests, please use the forum.

**Comment by 0rsa** [comment]
Noted, thank you.
