### ISSUE TITLE
Legrand Netatmo cable outlet implementation not compliant with deconz API

### ISSUE THREAD

**Issue by MV1908** [dresden-elektronik/deconz-rest-plugin#5250]
## Describe the bug
I am trying to use a Legrand Netatmo cable outlet (0 648 79) in Home Assistant via the deCONZ integration.
I have successfully paired the cable outlet with the conbee ii gateway via the phoscon app.
I have configured it in "fil pilote" mode via the deCONZ app (through VNC since I use the docker marthoc container).
I am able to control the outlet and the heater plugged on it by sending API requests via the deCONZ REST API (PUT /sensor/xx/config ; {"mode" : "confort"} for example).

However I cant make it working in Home Assistant.

I figured out that the implementation is not compliant with the API specification (https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#supported-config-attributes_1). According to the doc, the "mode" config attribute should be one of the supported values for a "ZHAThermostat" ("off", "heat", "cool", ...), but to control the Legrand outlet you have to define the "mode" config attribute to "confort", "confort-1", "confort-2", "eco", "hors gel", or "off".

The consequence is that it could not work in Home Assistant as HA restrict the value used for "hvac_mode" (which seems to be mapped to the "mode" config attribute of the deCONZ API) to the values allowed by the API specification (using the climate component).

## Steps to reproduce the behavior
- Pair a Legrand Netatmo Outlet to the conbee 2
- Switch it in "fil pilote" mode
- Enable the "deCONZ" integration which will detect the outlet as a climate device
- try to call the "climate.set_hvac_mode" on the entity which point to the Legrand Outlet. You can only pick one of the supported attributes. If you specify manually an other attribute in yaml mode (such as "confort"), you get an error message.

## Expected behavior
I think that the implementation should only allow to use the "heat" or "off" modes (the Legrand outlet is only designed to control a heater), and should allow to specify a "preset" attribute which is one of the 6 supported "fil pilote" orders ("confort", "confort -1", "confort -2", "eco", "hors gel", "off"). In HA the preset can be defined freely.

## Screenshots
![ha_deconz_zhathermostat_error_2](https://user-images.githubusercontent.com/45565314/130973184-5d0be28c-e7df-4bb0-a02e-c5d303fc84f0.PNG)
![ha_deconz_zhathermostat_error_1](https://user-images.githubusercontent.com/45565314/130973188-55c959c5-6d4b-4d17-9c1e-6e13835b818f.PNG)

## Environment
 - Host system: PC
 - Running method: Marthoc Docker container
 - Firmware version: 264A0700
 - deCONZ version: 2.12.06 
 - Device: ConBee II 
 - Do you use an USB extension cable: No
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
No log is relevant as you can make it work with deCONZ (but using an illegal "mode" attribute)

**Comment by Smanar** [comment]
>He can use the deConz configure service in hass and send whatever commands he wants. It can do all rest api commands

For me it s the better solution.

>I meant standardized values of deconz thermostat implementation

It mean, all users will need to use a convertion table

> "off" > "off"
> "cool" > "hors_gel"
> "auto" > "confort -1"
> "fan_only" > "confort -2"

Not something intuitive for me.

It s not possible make a plugin support all exotics devices, for me a link with a "how to do" is the better solution.

**Comment by manup** [comment]
I have only little experience with thermostats. Do these custom modes represent the same as the documented thermostat modes, or do they implement a different behavior?

**Comment by Smanar** [comment]
Totaly different.

"confort -1" is the comfort temperature minus 1 °C
"confort -2" is the comfort temperature minus 2 °C
"hors gel" trigger only if temperature go under 0 °C
"eco ou redsuit" is the comfort  temperature minus 4 °C

It s realy specific, few chance to find the same feature on other thermostats.

**Comment by MV1908** [comment]
I don't understand why the different modes of operation of the Fil Pilote device could not be mapped to different presets.
It seems obvious for a thermostat to only be able to order heat or cool or vent (real world modes) so this why the "mode" attribute is restricted to some values (at least in HA).
For me it is a  device attached to a heater so it makes sense that it should have only two modes : "heat" and "off". Then you can ask it for presets like "confort" or "eco" or whatever that makes sense to the device.
It seems semantically correct.

In my understanding a request for the fil pilote thermostat should be something like : 

```
PUT /sensor/xx/config
{
"mode" : "heat",
"preset" : "confort"
}
```
or 
```
PUT /sensor/xx/config
{
"mode" : "heat",
"preset" : "eco"
}
```
or 
```
PUT /sensor/xx/config
{
"mode" : "off",
"preset" : "off"
}
```

It seems to be the way it is done with the Tuya devices in the code of `thermostat.cpp` : 

Modes (sticks with the standard values for a ZHAThermostat)
```
const std::array<KeyValMapTuyaSingle, 3> RConfigModeValuesTuya1 = { { {QLatin1String("auto"), {0x00}}, {QLatin1String("heat"), {0x01}}, {QLatin1String("off"), {0x02}} } };

const std::array<KeyValMapTuyaSingle, 2> RConfigModeValuesTuya2 = { { {QLatin1String("off"), {0x00}}, {QLatin1String("heat"), {0x01}} } };
```

Presets (can be defined freely)
```
const std::array<KeyValMapTuyaSingle, 7> RConfigPresetValuesTuya = { { {QLatin1String("holiday"), {0x00}}, {QLatin1String("auto"), {0x01}}, {QLatin1String("manual"), {0x02}}, {QLatin1String("comfort"), {0x04}}, {QLatin1String("eco"), {0x05}}, {QLatin1String("boost"), {0x06}}, {QLatin1String("complex"), {0x07}} } };

const std::array<KeyMap, 2> RConfigPresetValuesTuya2 = { { {QLatin1String("auto")}, {QLatin1String("program")} } };

const std::array<KeyMap, 4> RConfigPresetValuesTuya3 = { { {QLatin1String("both")}, {QLatin1String("humidity")}, {QLatin1String("temperature")}, {QLatin1String("off")} } };
```
I am trying to make those modifications in the code and will test on my side. I will make a PR if it is successful (but as I said I am not comfortable at all with c++).

After all, maybe am i influenced by that fact that HA is strict only on "mode" values and not on "preset" values but it makes sense to me as stated above.

Thanks for your time anyway and for all the previous work on supporting this device @Smanar .

**Comment by Smanar** [comment]
>For me it is a device attached to a heater so it makes sense that it should have only two modes : "heat" and "off"

Precisely no, if you want to use the "heat" / "off" disable the "fil pilote" mode, you will have a on/off working mode.
I m not the "fil pilote" creator, but this device is made to work with this mode (or preset). I can disable "mode" and use "preset" if you prefer, but will be the same.

**Comment by Kane610** [comment]
I just got the urge to revisit the dev docs for hass and apparently I can expose custom presets https://developers.home-assistant.io/docs/core/entity/climate#presets. I will investigate this next week

**Comment by Pirionfr** [comment]
any new ?

**Comment by Smanar** [comment]
Yes, surely with DDF, I have started to do one, but for the moment it's not possible to mimic the needed request to change the "fil pilote mode".
We can use onlyy predefined request, need a better DDF core.

**Comment by Idaho947** [comment]
Hello, zwave qubino for wire pilot are not more avalable and this cable outlet is the only way to manage it... Any news about this ?

**Comment by Smanar** [comment]
The device is working fine with the DDF, I m using it ATM.

**Comment by Idaho947** [comment]
With wire pilot ? You have the commande ? You use HA ? I've just have on off and in pilot mode it doesn't work

**Comment by Smanar** [comment]
This device create 3 entries, 1 "light" entry used for on/off, and 2 sensor, a ZHAPower for power and a ZHAthermostat.
You can send "mode" to the ZHAThermostat sensor, but this mode need to be enabled on the device, with the GUI on the Legrand cluster.

**Comment by Idaho947** [comment]
Yes I've activate it. I'll try to exclude it (i've done it a long time ago when I was on jeedom).

**Comment by Idaho947** [comment]
I reinclude it but the thermostat is unvaliable :
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/0239efb8-c1ed-4c5c-a344-2f54d627bde6)

**Comment by Smanar** [comment]
The HA plugin have problem to support this device.
Can try the REST request

`curl -H 'Content-Type: application/json' -X PUT -d '{"mode":"confort"}' http://IP:PORT/api/KEY/sensors/ID/config`

IP and PORT are the same used to access phoscon, KEY is an ApiKey, can use the same used by HA, and ID is the ID of the ZHAThermostat entry.

**Comment by Idaho947** [comment]
Ok I ll try but who can fix the plugin ? I think it s a better solution for eveyone no ?

**Comment by Smanar** [comment]
Sure you can ask on deconz plugin github, perhaps @Kane610 can make something ?

**Comment by Kane610** [comment]
It would be much preferable that it is documented here what the changes related to this device is in this thread, what data can be expected from the device and some example data, that will benefit other clients as well.

**Comment by Idaho947** [comment]
Ok. @Smanar do you have something for it ?

**Comment by Smanar** [comment]
This device create 3 entries

```
    "etag": "dcda6928730bd3b345c742bdfab8a997",
    "hascolor": false,
    "lastannounced": "2023-11-06T10:56:00Z",
    "lastseen": "2023-11-06T16:03Z",
    "manufacturername": "Legrand",
    "modelid": "Cable outlet",
    "name": "Seche serviette",
    "state": {
      "on": true,
      "reachable": true
    },
    "swversion": "000a",
    "type": "Level control switch",
    "uniqueid": "00:04:74:00:00:71:13:55-01"
  },
  "3": {
    "capabilities": {
      "alerts": [
        "none",
        "select",
        "lselect"
      ]
    },
    "config": {
      "groups": [
        "0"
      ]
    },

    "ep": 1,
    "etag": "75c7753f4946ef2b0fc9eea20148efbe",
    "lastannounced": "2023-11-06T10:56:00Z",
    "lastseen": "2023-11-06T16:05Z",
    "manufacturername": "Legrand",
    "modelid": "Cable outlet",
    "name": "Power 5",
    "state": {
      "lastupdated": "2023-11-06T16:00:01.254",
      "power": 743
    },
    "swversion": "000a",
    "type": "ZHAPower",
    "uniqueid": "00:04:74:00:00:71:13:55-01-0b04"
  },

    "ep": 1,
    "etag": "75c7753f4946ef2b0fc9eea20148efbe",
    "lastannounced": "2023-11-06T10:56:00Z",
    "lastseen": "2023-11-06T16:05Z",
    "manufacturername": "Legrand",
    "modelid": "Cable outlet",
    "name": "Thermostat 6",
    "state": {
      "lastupdated": "2023-01-29T16:24:41.072"
    },
    "swversion": "000a",
    "type": "ZHAThermostat",
    "uniqueid": "00:04:74:00:00:71:13:55-01-0201"
  },
```

The first one is "light" entry, that permit to turn the device on/off id this mode is enabled
The ZHAPower is just a Powermeter
The ZHAThermostat is used to change the "fil pilote" mode, if this mode is enabled.

Possibles mode are :
- confort
- confort-1
- confort-2
-  eco
- hors gel
- off

**Comment by Idaho947** [comment]
Hello, any news about that ?

**Comment by Idaho947** [comment]
Yes I use rest command too.
