### ISSUE TITLE
Support for IAS Zone device:  Heiman HS1RC Smart Remote Control

### ISSUE THREAD

**Issue by oleg77s** [dresden-elektronik/deconz-rest-plugin#526]
Heiman HS1RC Smart Remote Control and Heiman HS1EB Smart Emergency Button support?
@ebaauw: I'd expect these to be IAS Zone devices, just like most of the other Heiman sensors. If you can provide me screenshots, adding support shouldn't be too difficult. Probably best to expose them as ZHASwitch and issue appropriate buttonevents for press/release of each/the button.

![node info](https://user-images.githubusercontent.com/23496372/38438718-fa31c0a2-39e3-11e8-9c66-28059fa6c7da.png)
![basic](https://user-images.githubusercontent.com/23496372/38438723-fce900bc-39e3-11e8-8e98-7b8f0acb2af3.png)
![identify](https://user-images.githubusercontent.com/23496372/38438731-00b57afe-39e4-11e8-9540-13419cef14a8.png)
![alarm](https://user-images.githubusercontent.com/23496372/38438735-031f8dac-39e4-11e8-8934-64647dfc3183.png)
![power](https://user-images.githubusercontent.com/23496372/38438739-05287f50-39e4-11e8-8965-fb2f64f8b04d.png)

**Comment by accelle17** [comment]
@oleg77 Were you able to integrate the HS1RC on deconz, particularly on homeassistant?

**Comment by olix74** [comment]
I would also love to see support for the Heiman Smart Remote Control!
Thank you,
Oliver
