### ISSUE TITLE
No HS Value for Model SRP-ZG9105-CC manufactured by Sunricher.

### ISSUE THREAD

**Issue by slusken** [dresden-elektronik/deconz-rest-plugin#5261]
## Describe the bug

After updating Home Assistant to the latest version my Sunricher Model SRP-ZG9105-CC don't work properly.
For what I understand from the HA github thats because that Deconz reports the color mode in HS but it doesn't report the HS     value. 
Phoscon see this device as:
Vendor: Philips
Model: HK-ZD-DIM-A
Version: 2.5.3_r55
## Steps to reproduce the behavior

The problem arrive when I updated HA to 2021.8.8 but its not there in 2021.6.6
## Environment

 - Host system: Server Debian
 - Running method: Marthoc Docker container
 - Firmware version: (26390500)
 - deCONZ version: (2.12.06)
 - Device: ConBee I
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? If so: No

## deCONZ Logs

{'etag': 'd991288496aee8d93fb716002ad3cd9c',
'hascolor': True,
'lastannounced': '2021-08-11T14:44:03Z',
'lastseen': '2021-08-28T12:39Z',
'manufacturername': 'Philips',
'modelid': 'HK-ZD-DIM-A',
'name': 'bedroom_window_light',
'state': {'alert': 'none',
'bri': 200,
'colormode': 'hs',
'on': False,
'reachable': True},
'swversion': '2.5.3_r55',
'type': 'Dimmable light',
'uniqueid': '80:4b:50:ff:fe:2d:8a:35-01'}
## Additional context

Original report on HA github.
https://github.com/home-assistant/core/issues/55377

**Comment by mattiasottosson** [comment]
@slusken had the same problem and managed to solve it by manually setting the colormode to "xz" as described here:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5536

This youtube guide was really helpful as well:
https://www.youtube.com/watch?v=rgTQpOVg8w0
