### ISSUE TITLE
Bosch RFMS-ZBMS multi-sensor

### ISSUE THREAD

**Issue by fresnoboy** [dresden-elektronik/deconz-rest-plugin#5262]
## Device

- Product name: RADION Multi-sensor
- Manufacturer:  Bosch
- Model identifier: RFMS-ZBMS
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

Not available because device refused to pair.  
### Other clusters that are not mentioned above

Here is the info on the device from the Hubitat hub:

endpointId: 01
model: RFMS-ZBMS
application: 0E
firmwareMT: 1133-002A-12005704
softwareBuild: 12005704
manufacturer: Bosch

Device Network ID is 5561, and reads like a generic Zigbee Contact sensor

**Comment by Mimiix** [comment]
Missing all screenshots.

Closing
