### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by Nusssschnipser** [dresden-elektronik/deconz-rest-plugin#5264]
Hi,
I don't get this device working in the Phoscon App.
I saw a similar device ( 3 Buttons i have 2 ) on request (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3761), but i get diffrent informations.

Thank you for your help!

## Device

- Product name: MoesGo ZigBee Smart Lichtschalter 2 Gang ohne Neutralleiter
- More Info on: https://www.amazon.de/dp/B096X892K5/ref=twister_B096X91Z2G?_encoding=UTF8&psc=1

- Manufacturer: TZE200_glib5ldv
- Model identifier: 
- Device type : 
  - Light

### Basic
<img width="423" alt="Bildschirmfoto 2021-08-29 um 10 28 15" src="https://user-images.githubusercontent.com/79045549/131244786-415107a9-e8ac-46e7-8f65-4964b61d76bf.png">

### Groups
<img width="426" alt="Bildschirmfoto 2021-08-29 um 10 31 02" src="https://user-images.githubusercontent.com/79045549/131244814-b08a2d4a-431a-4344-bc00-31733e87cbc1.png">
<img width="414" alt="Bildschirmfoto 2021-08-29 um 10 31 17" src="https://user-images.githubusercontent.com/79045549/131244819-db36b777-1b02-4d22-940c-b6b2fda3f834.png">
<img width="631" alt="Bildschirmfoto 2021-08-29 um 10 32 41" src="https://user-images.githubusercontent.com/79045549/131244831-f4599144-04d1-4a31-8fb5-0645cb5057f9.png">

### Other clusters that are not mentioned above
<img width="424" alt="Bildschirmfoto 2021-08-29 um 10 33 39" src="https://user-images.githubusercontent.com/79045549/131244859-2c492dd1-e35c-44b8-b301-8663bc4da0e6.png">

**Comment by Smanar** [comment]
Hello, It miss the node info panel, (I need too the mac adress and the manufacture number)
It s a wired device ?

**Comment by Nusssschnipser** [comment]
Hi, thank you for the quick response. 
Yes it's a wired device . Wall switch  ( without neutral wire, maybe this is becauce of the batterie state? ) which is directly wired to two light.
Here is the node Info:

<img width="623" alt="Bildschirmfoto 2021-08-29 um 11 38 00" src="https://user-images.githubusercontent.com/79045549/131245946-6cfcd0c2-5b29-474f-b41d-423a6f6f204f.png">

Best regards !

**Comment by Smanar** [comment]
Ok so I have bad news for you https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3204#issuecomment-902038001

So ATM, you need to compile the code yourself for your use or wait for future deconz version.
