### ISSUE TITLE
Aqara H1 EU Wall Switch (No Neutral, Double Rocker)

### ISSUE THREAD

**Issue by InteNs** [dresden-elektronik/deconz-rest-plugin#5267]
## Device

- Product name: H1 EU Wall Switch (No Neutral, Double Rocker)
- Manufacturer: LUMI
- Model identifier: lumi.switch.l2aeu1
- Device type :
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/6474105/131391097-9b1da52d-b525-4bc5-9dbe-2427070ca079.png)

### Basic
![image](https://user-images.githubusercontent.com/6474105/131389888-1bcc4d35-90b6-4edd-9b67-1d1dd5c91642.png)

### Identify
![image](https://user-images.githubusercontent.com/6474105/131390051-fa3af58d-970e-4ae1-9379-c37b08afa054.png)

### Alarms
![image](https://user-images.githubusercontent.com/6474105/131390093-fa666a4c-f5a4-4c38-a1e7-464f72daefc7.png)

### Device Temperature
![image](https://user-images.githubusercontent.com/6474105/131390233-aec6037b-78c4-412b-a92b-d1b7abd93a41.png)

### Groups
![image](https://user-images.githubusercontent.com/6474105/131390295-9bb6907f-fd72-4d42-be48-5f3ff84c2c51.png)

### Scenes
![image](https://user-images.githubusercontent.com/6474105/131390353-cdc861aa-d5bf-4f0c-996b-9ac87a4df878.png)

### On/Off
![image](https://user-images.githubusercontent.com/6474105/131390497-ad056203-ea27-4b96-986e-7605997b4ddc.png)

**Comment by SwoopX** [comment]
#5104
