### ISSUE TITLE
Raspbee 2 not working in deconz

### ISSUE THREAD

**Issue by Staxen** [dresden-elektronik/deconz-rest-plugin#5269]
## Describe the bug
- Cannot find devices to pair when using in homeassistant.
- It looks like it's a raspbee and not raspbee 2 in GCFflasher -1
- I cannot firmware update it manually, retry failed

## Steps to reproduce the behavior
Followed the manually update guide on both regular rasbian image and the premade with deconz installed

## Expected behavior
Not updating firmare, retry failed.
pi@phoscon:~ $ sudo GCFFlasher_internal -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
wiringPi 2.52 initialized
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x93C2CD88
flashing 164180 bytes: |=Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x93C2CD88
flashing 164180 bytes: |=Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Reboot device /dev/ttyS0 (RaspBee)
action: reset device RaspBee
Bootloader version 0x00030003, app crc: 0x93C2CD88
flashing 164180 bytes: |=retry, failed

## Environment
2.12.01 / 14.6.2021
Raspberry pi3
Raspbee2

## deCONZ Logs

_pi@phoscon:~ $ GCFFlasher_internal -l_
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path | Vendor | Product | Serial | Type
-----------------+--------+---------+------------+-------
/dev/ttyS0 | 0x0000 | 0x0000 | | RaspBee

_pi@phoscon:~ $ sudo GCFFlasher_internal -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3_
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
09:52:55:795 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:52:55:946 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:52:55:946 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:52:55:946 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:52:55:949 query bootloader v1 ID after 0 ms
09:52:57:452 query bootloader v1 ID after 1502 ms
09:52:57:953 query deCONZ firmware version
09:53:00:101 uart reset failed, try RaspBee reset
action: reset device RaspBee
wiringPi 2.52 initialized
09:53:00:306 query bootloader v1 ID after 1 ms
09:53:00:794 RX 14 bytes ASCII ▒▒ after 489 ms
09:53:00:794 RX c081820300030088cdc2934dfcc0 after 489 ms
09:53:00:794 SLIP RX frame length: 10
09:53:00:794 check magic: 0x81 cmd: 0x82 after 489 ms
Bootloader version 0x00030003, app crc: 0x93C2CD88
09:53:00:796 GCF_ResetDeviceDone
09:53:00:797 bootloader v3 update firmware request size: 164180, addr: 0x00005000, type: 31, crc-32: 0xAAAAAAAA
09:53:00:797 TX c0810354810200005000001faaaaaaaa8efbc0
09:53:00:804 SLIP RX frame length: 3
flashing 164180 bytes: |=09:53:00:809 SLIP RX frame length: 8
09:53:00:809 updateFirmwareV3DataRsp()
09:53:00:809 bootloader v3 data request, offset: 0, length: 256
09:53:00:809 bootloader v3 send data response, status: 0, offset: 0, length: 256
09:53:00:810 TX c08184000000000000017e1b800892caa2413fe59bd4827360627b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af1065c0
09:53:00:889 SLIP RX frame length: 8
09:53:00:889 updateFirmwareV3DataRsp()
09:53:00:889 bootloader v3 data request, offset: 256, length: 256
09:53:00:889 bootloader v3 send data response, status: 0, offset: 256, length: 256
09:53:00:890 TX c08184000001000000017b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6aff962c0
09:53:20:891 retry, elapsed 25 seconds
09:53:20:997 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:53:20:998 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:53:21:131 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:53:21:131 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:53:21:131 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:53:21:133 query bootloader v1 ID after 0 ms
09:53:22:635 query bootloader v1 ID after 1502 ms
09:53:23:136 query deCONZ firmware version
09:53:25:140 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:53:25:342 query bootloader v1 ID after 1 ms
09:53:25:830 RX 14 bytes ASCII ▒▒ after 489 ms
09:53:25:830 RX c081820300030088cdc2934dfcc0 after 489 ms
09:53:25:830 SLIP RX frame length: 10
09:53:25:830 check magic: 0x81 cmd: 0x82 after 489 ms
Bootloader version 0x00030003, app crc: 0x93C2CD88
09:53:25:832 GCF_ResetDeviceDone
09:53:25:834 bootloader v3 update firmware request size: 164180, addr: 0x00005000, type: 31, crc-32: 0xAAAAAAAA
09:53:25:835 TX c0810354810200005000001faaaaaaaa8efbc0
09:53:25:843 SLIP RX frame length: 3
flashing 164180 bytes: |=09:53:25:848 SLIP RX frame length: 8
09:53:25:849 updateFirmwareV3DataRsp()
09:53:25:849 bootloader v3 data request, offset: 0, length: 256
09:53:25:850 bootloader v3 send data response, status: 0, offset: 0, length: 256
09:53:25:851 TX c08184000000000000017e1b800892caa2413fe59bd4827360627b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af1065c0
09:53:25:932 SLIP RX frame length: 8
09:53:25:933 updateFirmwareV3DataRsp()
09:53:25:934 bootloader v3 data request, offset: 256, length: 256
09:53:25:935 bootloader v3 send data response, status: 0, offset: 256, length: 256
09:53:25:936 TX c08184000001000000017b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6aff962c0
09:53:26:017 SLIP RX frame length: 8
09:53:26:017 updateFirmwareV3DataRsp()
09:53:26:017 bootloader v3 data request, offset: 512, length: 256
09:53:26:017 bootloader v3 send data response, status: 0, offset: 512, length: 256
09:53:26:017 TX c08184000002000000017b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6aff862c0
09:53:46:034 retry, elapsed 50 seconds
09:53:46:139 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:53:46:139 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:53:46:254 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:53:46:254 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:53:46:255 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:53:46:256 query bootloader v1 ID after 0 ms
09:53:47:758 query bootloader v1 ID after 1501 ms
09:53:48:259 query deCONZ firmware version
09:53:50:262 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:53:50:464 query bootloader v1 ID after 1 ms
09:53:50:953 RX 9 bytes ASCII ▒ after 489 ms
09:53:50:953 RX 188a0001922dd5f3f8 after 489 ms
09:53:51:955 query bootloader v1 ID after 1491 ms
09:53:53:457 query bootloader v3 ID after 2993 ms
09:53:53:457 TX c081027dffc0
09:53:53:958 retry, elapsed 58 seconds
09:53:54:053 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:53:54:054 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:53:54:169 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:53:54:169 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:53:54:169 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:53:54:170 query bootloader v1 ID after 0 ms
09:53:55:672 query bootloader v1 ID after 1501 ms
09:53:56:173 query deCONZ firmware version
09:53:58:177 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:53:58:379 query bootloader v1 ID after 1 ms
09:53:58:867 RX 9 bytes ASCII ▒ after 489 ms
09:53:58:867 RX 188a0001922d95f3f8 after 489 ms
09:53:59:869 query bootloader v1 ID after 1490 ms
09:54:01:371 query bootloader v3 ID after 2992 ms
09:54:01:371 TX c081027dffc0
09:54:01:872 retry, elapsed 66 seconds
09:54:01:968 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:54:01:969 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:54:02:114 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:54:02:114 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:54:02:114 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:54:02:116 query bootloader v1 ID after 0 ms
09:54:03:618 query bootloader v1 ID after 1502 ms
09:54:04:119 query deCONZ firmware version
09:54:06:122 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:54:06:324 query bootloader v1 ID after 1 ms
09:54:06:813 RX 9 bytes ASCII ▒ after 489 ms
09:54:06:813 RX 188a0001922d95f3f8 after 489 ms
09:54:07:814 query bootloader v1 ID after 1490 ms
09:54:09:316 query bootloader v3 ID after 2992 ms
09:54:09:316 TX c081027dffc0
09:54:09:818 retry, elapsed 74 seconds
09:54:09:924 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:54:09:924 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:54:10:047 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:54:10:050 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:54:10:051 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:54:10:054 query bootloader v1 ID after 0 ms
09:54:11:558 query bootloader v1 ID after 1503 ms
09:54:12:059 query deCONZ firmware version
09:54:14:062 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:54:14:264 query bootloader v1 ID after 1 ms
09:54:14:752 RX 9 bytes ASCII ▒ after 489 ms
09:54:14:753 RX 188a0001922dd5f3f8 after 489 ms
09:54:15:755 query bootloader v1 ID after 1491 ms
09:54:17:257 query bootloader v3 ID after 2993 ms
09:54:17:257 TX c081027dffc0
09:54:17:759 retry, elapsed 81 seconds
09:54:17:855 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:54:17:855 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:54:17:973 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:54:17:974 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:54:17:975 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:54:17:977 query bootloader v1 ID after 0 ms
09:54:19:480 query bootloader v1 ID after 1502 ms
09:54:19:981 query deCONZ firmware version
09:54:21:984 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:54:22:186 query bootloader v1 ID after 1 ms
09:54:22:676 RX 9 bytes ASCII X▒ after 491 ms
09:54:22:676 RX 588a0001922dd5f3f8 after 491 ms
09:54:23:678 query bootloader v1 ID after 1492 ms
09:54:25:180 query bootloader v3 ID after 2994 ms
09:54:25:180 TX c081027dffc0
09:54:25:681 retry, elapsed 89 seconds
09:54:25:777 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:54:25:778 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:54:25:893 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:54:25:893 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:54:25:893 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:54:25:895 query bootloader v1 ID after 0 ms
09:54:27:397 query bootloader v1 ID after 1501 ms
09:54:27:898 query deCONZ firmware version
09:54:29:901 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:54:30:103 query bootloader v1 ID after 1 ms
09:54:30:592 RX 9 bytes ASCII X▒ after 489 ms
09:54:30:592 RX 588a0001922d95f3f8 after 489 ms
09:54:31:593 query bootloader v1 ID after 1491 ms
09:54:33:095 query bootloader v3 ID after 2993 ms
09:54:33:095 TX c081027dffc0
09:54:33:597 retry, elapsed 97 seconds
09:54:33:703 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:54:33:703 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:54:33:816 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:54:33:817 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:54:33:817 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:54:33:820 query bootloader v1 ID after 0 ms
09:54:35:323 query bootloader v1 ID after 1502 ms
09:54:35:823 query deCONZ firmware version
09:54:37:827 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:54:38:029 query bootloader v1 ID after 1 ms
09:54:38:517 RX 9 bytes ASCII X▒ after 489 ms
09:54:38:518 RX 588a0001922dd5f3f8 after 489 ms
09:54:39:519 query bootloader v1 ID after 1490 ms
09:54:41:021 query bootloader v3 ID after 2993 ms
09:54:41:021 TX c081027dffc0
09:54:41:523 retry, elapsed 105 seconds
09:54:41:629 parse commands: /usr/bin/GCFFlasher_internal.bin -d /dev/ttyS0 -t 120 -f deCONZ_RaspBeeII_0x26710700.bin.GCF -x 3

09:54:41:629 using firmware file: deCONZ_RaspBeeII_0x26710700.bin.GCF
09:54:41:777 ls dev: /dev/ttyAMA0 (0x0000/0x0000) sn:
09:54:41:777 ls dev: /dev/ttyS0 (0x0000/0x0000) sn:
09:54:41:777 dev /dev/ttyS0
Reboot device /dev/ttyS0 (RaspBee)
09:54:41:779 query bootloader v1 ID after 0 ms
09:54:43:281 query bootloader v1 ID after 1502 ms
09:54:43:782 query deCONZ firmware version
09:54:45:786 uart reset failed, try RaspBee reset
action: reset device RaspBee
09:54:45:988 query bootloader v1 ID after 1 ms
09:54:46:476 RX 9 bytes ASCII X▒ after 489 ms
09:54:46:476 RX 588a0001922d95f3f8 after 489 ms
09:54:47:477 query bootloader v1 ID after 1490 ms
09:54:48:980 query bootloader v3 ID after 2992 ms
09:54:48:980 TX c081027dffc0
09:54:48:992 RX 14 bytes ASCII ▒▒ after 3005 ms
09:54:48:992 RX c081820300030088cdc2934dfcc0 after 3005 ms
09:54:48:992 SLIP RX frame length: 10
09:54:48:992 check magic: 0x81 cmd: 0x82 after 3005 ms
Bootloader version 0x00030003, app crc: 0x93C2CD88
09:54:48:994 GCF_ResetDeviceDone
09:54:48:995 bootloader v3 update firmware request size: 164180, addr: 0x00005000, type: 31, crc-32: 0xAAAAAAAA
09:54:48:996 TX c0810354810200005000001faaaaaaaa8efbc0
09:54:49:003 SLIP RX frame length: 3
flashing 164180 bytes: |=09:54:49:008 SLIP RX frame length: 8
09:54:49:009 updateFirmwareV3DataRsp()
09:54:49:009 bootloader v3 data request, offset: 0, length: 256
09:54:49:010 bootloader v3 send data response, status: 0, offset: 0, length: 256
09:54:49:011 TX c08184000000000000017e1b800892caa2413fe59bd4827360627b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af1065c0
09:54:49:091 SLIP RX frame length: 8
09:54:49:092 updateFirmwareV3DataRsp()
09:54:49:093 bootloader v3 data request, offset: 256, length: 256
09:54:49:094 bootloader v3 send data response, status: 0, offset: 256, length: 256
09:54:49:095 TX c08184000001000000017b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6af7b7ad7c401eab6aff962c0
uart reset failed, try RaspBee reset
retry, failed

**Comment by Mimiix** [comment]
As described in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5113 All reports that aren't clearly bugs or pointing to bugs in the current codebase are moved to the forum.

Please use the forum.

closing.
