### ISSUE TITLE
POPP Smart Thermostat (Produktcode: 701721)

### ISSUE THREAD

**Issue by Pe-MaKer** [dresden-elektronik/deconz-rest-plugin#5278]
## Device

- Product name: POPP Smart Thermostat (Produktcode: 701721)
- Manufacturer Link: [https://www.popp.eu/de/portfolio/smart-thermostat/](https://www.popp.eu/de/portfolio/smart-thermostat/)
- Manufacturer: DSX84YU
- Model identifier: eT093WRO
- Device type: 
  - Thermostat

### Basic
![2021-09-03 16_15_53-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132020394-4c1aa2f8-259f-4420-ba3a-ee533f15ab15.png)

### Identify
![2021-09-03 16_22_43-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132021040-82a44efb-9822-4abe-8489-b7eb54311c3c.png)

### OTAU
![2021-09-03 16_35_36-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132023007-909b8670-a48e-4215-9599-9f6f06be15b5.png)

### Diagnostics
![2021-09-03 16_33_54-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022698-9f405688-217a-41ab-99b0-7f5839248776.png)

### Thermostat
![2021-09-03 16_26_47-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022282-5ecfeeaf-6714-4e49-9ca3-08f8eacc517f.png)
![2021-09-03 16_28_56-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022285-ca421e04-3c58-4631-919b-8c2c66b69977.png)
![2021-09-03 16_28_42-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022288-65463051-947f-4940-8077-a0a2595c5973.png)
![2021-09-03 16_28_28-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022289-686457bf-1a6d-48fc-8cf9-7cb9483628a7.png)
![2021-09-03 16_28_14-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022290-a724ed72-b728-427d-ab46-c1a63794118e.png)
![2021-09-03 16_28_00-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022291-19a9361b-b83e-48ce-9fcd-63a31d889bad.png)
![2021-09-03 16_27_46-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022292-f0c996da-310b-4c76-898f-c50db66e320b.png)
![2021-09-03 16_27_30-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022295-294b7c01-9fdf-4c25-9303-e055a6747a9f.png)
![2021-09-03 16_27_08-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022298-4455e7cf-78ec-44cc-8ca5-a6906ee67fda.png)

### Thermostat User Interface Configuration
![2021-09-03 16_32_04-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132022518-234932f1-a49a-4fdd-9bab-1d37c8603727.png)

### Poll count
![2021-09-03 16_24_42-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132021357-968a7d8e-57a0-4171-ad0d-a9e5f15e94ea.png)

### Time
![2021-09-03 16_23_27-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132021251-7b31b7e2-f9a1-4383-889a-14e9b33713c4.png)

### Power
![2021-09-03 16_20_10-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132020738-82b5aba0-0d7c-4a81-84be-59f52309a768.png)

### Node Info
![2021-09-03 16_39_12-Übersicht - Home Assistant](https://user-images.githubusercontent.com/44093812/132023578-8336a4b9-9396-4a6c-a9f5-84decff7e8e1.png)

**Comment by SwoopX** [comment]
That's a Danfoss Ally, so really easy to add. Interestingly, you got a newer firmware than the one available at Danfoss.

**Comment by Pe-MaKer** [comment]
Sounds promising.
Seems to be the first Zigbee device under the "Popp" brand. Popp was aquired by Z-Wave Europe GmbH some years ago an all of their smart devices were Z-Wave based - for obvious reasons.
If they partner with Danfoss for their first Zigbee Thermostat, it might be better then going to the learning curve by themselves.

Looking forward to further good news from you. I assume I have to wait for the next release.

**Comment by SwoopX** [comment]
Well, you can basically compile the plugin based on my branch yourself any time.

**Comment by Pe-MaKer** [comment]
@SwoopX you are awesome!
Thanks!

**Comment by Pe-MaKer** [comment]
> Well, you can basically compile the plugin based on my branch yourself any time.

Since I'm still waiting for your commit to be merged, I would follow your offer to compile the plugin from your branch.

I switched over to a dedicated Pi and used the prebuilt deconz image. I managed to install the current beta but I have no clue about the required commands to pull your branch and to compile and install.
Could you please help me out here? @SwoopX

**Comment by Smanar** [comment]
You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch popp https://github.com/SwoopX/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by Pe-MaKer** [comment]
> You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing So for you, after having installed deconz :
> 
Thanks, that worked.
But I realized that the branch is about 500 commits behind the master. 
And even worse for me: the thermostate is not being recognized correctly and I can't open the DDF Editor.

I have no clue how to proceed from here.

![2021-11-25 10_00_22-phoscon - VNC® Viewer for Google Chrome™](https://user-images.githubusercontent.com/44093812/143411471-f636f437-2847-4f2e-90c5-d029dbbfe81c.png)
![2021-11-25 09_47_53-Phoscon App](https://user-images.githubusercontent.com/44093812/143411487-b2e6a684-3561-434d-b96b-9c4bdad39c86.png)
![2021-11-25 09_47_31-Phoscon App](https://user-images.githubusercontent.com/44093812/143411492-aeb2ba7e-7a68-40d7-acfa-f1617fbd19d3.png)

**Comment by Smanar** [comment]
Don't take care at phoson, it can't expose correclty thermostat.
Better to check direclty the API http://phoscon.de/pwabeta in help / api information or use third app.

To update code, I think it s better if SwoopX can update his PR.

**Comment by mantaalex** [comment]
> > Well, you can basically compile the plugin based on my branch yourself any time.
> 
> Since I'm still waiting for your commit to be merged, I would follow your offer to compile the plugin from your branch.
> 
> I switched over to a dedicated Pi and used the prebuilt deconz image. I managed to install the current beta but I have no clue about the required commands to pull your branch and to compile and install. Could you please help me out here? @SwoopX

you like the popp thermostat? what does it show in HA? i will buy them to

**Comment by Mimiix** [comment]
@mantaalex This is not the place to ask for advice. Please use Discord or the forums for that :)
