### ISSUE TITLE
Tradfri Light: Not remember PowerOn options

### ISSUE THREAD

**Issue by jasimancas** [dresden-elektronik/deconz-rest-plugin#5289]
## Describe the bug
I have 10 bulbs of various models within the Tradfri range and although I have set that when the power returns they do NOT turn on, and that when the Color returns is 255, it does not work, if I read the parameters they appear correct, but when I cut the power a couple of times it seems to lose them (although when I read them they still appear correct), and out of 10 bulbs 3 or 4 turn on, and in random color temperature.

## Steps to reproduce the behavior

  1. Go to attributes
  2. Change PowerOn OnOff to OFF
  3. Cut off supply
  4. Reactivates supply

## Expected behavior

  To execute the settings that are set in the bulb properties.

## Screenshots

![image](https://user-images.githubusercontent.com/15717847/132399134-9f94be5d-bddb-42af-881c-ecceb926847e.png)-->

## Environment

 - Host system: PC
 - Running method: Marthoc Docker container
 - Firmware version: 0X26720700
 - deCONZ version: 2.12.6
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

**Comment by manup** [comment]
I did a test with a GU10 with same settings, here it works. Could it be that the lights aren't having the latest Ikea firmware?

My GU10 has version 2.3.050 in the Basic Cluster.

**Comment by Mimiix** [comment]
@manup could this be a bug in deconz or something else? If it's the latter, I close this issue and ask the user to move to discord / the forum.

**Comment by manup** [comment]
Not sure, I think this is more an Ikea firmware issue since from deCONZ side only the attribute gets written (which according to the screenshot works) and the light has to handle the rest.

**Comment by Mimiix** [comment]
With that information I'm closing this issue.

Feel free to open an topic on the forum @jasimancas
