### ISSUE TITLE
Heiman HS3SA-E

### ISSUE THREAD

**Issue by saxn-paule** [dresden-elektronik/deconz-rest-plugin#5296]
## Device

- Product name: Heiman HS3SA-E
- Manufacturer: 0x120b
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Sensor
  - Siren

## Screenshots

I got two of the HS3SA-E smoke detectors. Pairing via Phoscon was possible, but it's always shown as not reachable:
![image](https://user-images.githubusercontent.com/8352690/133047763-9c883679-8393-4956-8074-dda8c9c0a500.png)

Via Home-Assistant three entities are detected:
![image](https://user-images.githubusercontent.com/8352690/133048028-6b03ddfe-156e-414e-9c32-79ea85ae1801.png)

But they don't provide a status. In case of testing the alarm function nothing happens in Phoscon/HA.

It also doesn't show a green line:
![image](https://user-images.githubusercontent.com/8352690/133049044-96dd23ef-4a66-48a5-8d98-c8d7cbf4bcc3.png)

**Comment by Mimiix** [comment]
Hi,

This is not a device request nor a bug but a user question.

All of these are redirect to the forums as noted in #5113 :

https://forum.phoscon.de

**Comment by saxn-paule** [comment]
@Mimiix This device is not part of the supported devices List and also doesn't work properly, so in my opinion it is a device request.

**Comment by Mimiix** [comment]
It showing "Not reachable" has nothing to do with it being supported or not and often points to user questions.

Secondly, if it wasn't supoorted, it wouldn't show in Phoscon or deconz at all: Devices need to be whitelisted.

On an ending note: The correct way would use the original issue , which you did: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1021#issuecomment-917950402
