### ISSUE TITLE
 _TZ3000_402jjyro tuya door windows sensor TS0203 (ZD06)

### ISSUE THREAD

**Issue by Onshuis** [dresden-elektronik/deconz-rest-plugin#5301]
## Device

- Product name: Door Window Sensor Smartlife Zigbee 3.0 Model: ZD06 (AVATOO)
- Manufacturer:  _TZ3000_402jjyro
- Model identifier: TS0203
- Device type : Sensor
 <strike> - Light
  - Lock
  - Remote</strike>
  - Sensor
<strike>  - Siren
  - Switch
  - Thermostat
  - Other: 
</strike>

### Basic
![basic_info_cluster](https://user-images.githubusercontent.com/90712132/133402911-21101044-462b-4221-8b47-086fdba47d5f.png)
### Identify
![ident_cluster](https://user-images.githubusercontent.com/90712132/133402948-6891ec43-b3cf-444d-b5f2-15031207d6b4.png)
### Alarms
![ias_cluster](https://user-images.githubusercontent.com/90712132/133403077-44278340-0ab2-470c-89a2-a20abdc8a6e1.png)

--- Removed sections not on device ---
### Power Configuration
![power_cluster](https://user-images.githubusercontent.com/90712132/133403681-fd303d78-8487-4e99-a9fe-c2518512c489.png)
### OTAU (grayed out no read possible)
![OTAU_cluster](https://user-images.githubusercontent.com/90712132/133403589-8eb5e204-9d0b-486e-9f7f-819eed8c130e.png)

**Comment by Mimiix** [comment]
@Smanar

**Comment by Smanar** [comment]
Hello, can you show the node info panel, or just confirm me the manufacture number ?

**Comment by Onshuis** [comment]
Sure I made a screenshot of it, but i misread the template i think...
Here it is:

![node_info](https://user-images.githubusercontent.com/90712132/133510376-8ef25e1b-bba1-4680-824a-8fc45226cd54.png)

**Comment by Smanar** [comment]
Ok so first try

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch tuya_door_7 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by Onshuis** [comment]
You done it! for a part that is.
- I paired it with phoscon, it said ready, but not showing up in phoscon.
- It shows up as OpenClose73 in deCONZ and in my domotica program.

I must say, i have to make the contact with the magnet, otherwise it does nothing, so while pairing, or reading info, i need to open and close it.

Man im so happy, amazing work thank you :-)

**Comment by Onshuis** [comment]
Yes it is perfect like this. And battery also works fine 😀

**Comment by Smanar** [comment]
K I making the PR

**Comment by Onshuis** [comment]
Thanks for helping 👍

**Comment by Telk0** [comment]
When Will this be added to deconz @Smanar

**Comment by Smanar** [comment]
Hu ?
Long time it was added. Are you sure you have the same model, can you compare with the capture from the first post ?
