### ISSUE TITLE
Network down with latest deCONZ stable

### ISSUE THREAD

**Issue by andersthomas** [dresden-elektronik/deconz-rest-plugin#5305]
## Describe the bug

With latest stable deCONZ 2.12.06, the network suddenly went down and none of the ~20 Zigbee devices is available from deCONZ.

## Steps to reproduce the behavior

Unknown. First occurence of the problem.

## Expected behavior

deCONZ should run stable with all Zigbee devices being available.

## Environment

 - Host system: Raspberry Pi 4B
 - Running method: Raspbian 10.10
 - Firmware version: 26720700
 - deCONZ version: 2.12.06 / 19.8.2021
 - Device:ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs

Initial log attached. Please advise on suitable log options and conditions for further troubleshooting.
[deconz.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7180983/deconz.log)

**Comment by Mimiix** [comment]
Hi,

As this is not adirect bug report (according to #5113 ) I'm closing this issue. Feel free to open a topic on the forums.

closing this issue.
