### ISSUE TITLE
Light switch disappears

### ISSUE THREAD

**Issue by tempacgitac** [dresden-elektronik/deconz-rest-plugin#5309]
## Describe the bug
Hello

I have a CONBEE II USB gateway running in a deCONZ container in Ubuntu. I had it all working, but after a while my light switch disappears from the CONBEE web interface.

I then try to pair the light switch again but it will not recognize it on a scan.

I tried the firmware update and it seemed to reset everything and I was able to find the light. But again after few hours, the light switch disappears and the problem repeats.

Can you please advise what is going on?

## Environment

 - Host system: Ubuntu server 20.04
 - Running method: Ubuntu
 - Firmware version: 26660700 2.16.06 19/08/21
 - deCONZ version: Latest - downloaded yesterday
 - Device: ConBee II 
 - Do you use an USB extension cable: (yes / no) -- No - USB plugs straight into PC
 - Is there any other USB or serial devices connected to the host system? Yes - A wireless keyboard

**Comment by Mimiix** [comment]
Hi,

As this is more a user question than a bug. I close this issue.

Feel free to open a post on the forums.
