### ISSUE TITLE
CONBEE II Stops working after a while with deCONZ

### ISSUE THREAD

**Issue by tempacgitac** [dresden-elektronik/deconz-rest-plugin#5313]
## Describe the bug

Hello

I have an Ubuntu server running node red which connects to my CONBEE II gateway via deCONZ. The deCONZ is running in a marthoc/docker container.

It all works fine, then after a few hours node red and my PC lose connection with the CONBEE gateway. On the gateway home page I see "Not connected" next to Firmware.

This has happened a few times. I have to reboot the computer for it to come back.

Below is the docker log.

## Screenshots

![image](https://user-images.githubusercontent.com/90699443/133952959-bdc4f881-d6e1-43e1-8c65-774bbe012288.png)

## Environment

 - Host system: PC
 - Running method: Ubuntu / Marthoc Docker container 
 - Firmware version: (26660700)
 - deCONZ version: (2.12.06)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes / no) -- no
 - Is there any other USB or serial devices connected to the host system? If so: Which? Wireless keyboard

## deCONZ Logs

11:13:49:052 Skip idle timer callback, too early: elapsed 896 msec
11:13:57:058 Device TTL 6960 s flags: 0x7
11:14:00:512 Bind response success for 0x5c0272fffece41b2 ep: 0x01 cluster: 0x0006
11:14:49:052 Skip idle timer callback, too early: elapsed 898 msec
11:14:57:058 Device TTL 6900 s flags: 0x7
11:15:50:052 Skip idle timer callback, too early: elapsed 941 msec
11:15:57:058 Device TTL 6840 s flags: 0x7
11:16:04:051 GW firmware version: 0x26660700
11:16:04:051 GW firmware version is up to date: 0x26660700
11:16:50:051 Skip idle timer callback, too early: elapsed 884 msec
11:16:57:058 Device TTL 6780 s flags: 0x7
11:17:51:051 Skip idle timer callback, too early: elapsed 927 msec
11:17:57:058 Device TTL 541 s flags: 0x7
11:17:57:058 Device reset watchdog 7200 s
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.12.06
[marthoc/deconz] Web UI port: 80
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC Disabled
11:18:04:671 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
11:18:04:776 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:04:776 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
11:18:04:824 parent process /bin/sh
11:18:04:824 gw run mode: docker
11:18:04:824 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
11:18:04:824 DB sqlite version 3.27.2
11:18:04:825 DB PRAGMA page_count: 42
11:18:04:825 DB PRAGMA page_size: 4096
11:18:04:825 DB PRAGMA freelist_count: 0
11:18:04:825 DB file size 172032 bytes, free pages 0
11:18:04:825 DB PRAGMA user_version: 8
11:18:04:825 DB cleanup
11:18:04:825 DB create temporary views
11:18:04:828 started websocket server at port 443
11:18:04:829 [INFO] - Found file containing button maps. Parsing data...
11:18:04:831 [INFO] - Button maps loaded.
11:18:04:832 dlg action: Read binding table
11:18:04:832 found node plugin: libde_rest_plugin.so - REST API Plugin
11:18:04:832 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
11:18:04:837 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
11:18:04:839 LightNode 1: Configuration tool 1 added
11:18:05:973 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:06:002 wait reconnect 5 seconds
11:18:07:025 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:08:051 wait reconnect 4 seconds
11:18:09:051 wait reconnect 3 seconds
11:18:10:061 wait reconnect 2 seconds
11:18:11:052 wait reconnect 1 seconds
11:18:11:074 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:12:051 wait reconnect 5 seconds
11:18:12:073 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:12:134 Announced to internet https://phoscon.de/discover
11:18:13:052 wait reconnect 4 seconds
11:18:13:653 New websocket 192.168.0.3:56210 (state: 3) 
11:18:14:052 wait reconnect 3 seconds
11:18:15:052 wait reconnect 2 seconds
11:18:16:052 wait reconnect 1 seconds
11:18:16:073 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:17:051 wait reconnect 5 seconds
11:18:17:073 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:18:052 wait reconnect 4 seconds
11:18:19:052 wait reconnect 3 seconds
11:18:20:051 wait reconnect 2 seconds
11:18:20:073 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
11:18:21:052 wait reconnect 1 seconds
11:18:21:075 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:22:052 wait reconnect 5 seconds
11:18:22:073 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:23:051 wait reconnect 4 seconds
11:18:24:051 wait reconnect 3 seconds
11:18:25:052 start reconnect to network
11:18:25:052 wait reconnect 2 seconds
11:18:26:052 wait reconnect 1 seconds
11:18:26:073 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:27:052 wait reconnect 5 seconds
11:18:27:074 COM: /dev/ttyACM0 / serialno: , ConBee II
11:18:28:052 wait reconnect 4 seconds
11:18:29:052 wait reconnect 3 seconds
11:18:30:052 failed to reconnect to network try=1
11:18:30:052 wait reconnect 2 seconds

And another time:

03:12:34:126 Device TTL 7080 s flags: 0x7
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.12.06
[marthoc/deconz] Web UI port: 80
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC Disabled
03:12:39:852 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
03:12:40:005 COM: /dev/ttyACM0 / serialno: , ConBee II
03:12:40:006 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
03:12:40:054 parent process /bin/sh
03:12:40:054 gw run mode: docker
03:12:40:054 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
03:12:40:054 DB sqlite version 3.27.2
03:12:40:054 DB PRAGMA page_count: 42
03:12:40:054 DB PRAGMA page_size: 4096
03:12:40:054 DB PRAGMA freelist_count: 0
03:12:40:054 DB file size 172032 bytes, free pages 0
03:12:40:054 DB PRAGMA user_version: 8
03:12:40:054 DB cleanup
03:12:40:055 DB create temporary views
03:12:40:058 started websocket server at port 443
03:12:40:058 [INFO] - Found file containing button maps. Parsing data...
03:12:40:061 [INFO] - Button maps loaded.
03:12:40:062 dlg action: Read binding table
03:12:40:062 found node plugin: libde_rest_plugin.so - REST API Plugin
03:12:40:062 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
03:12:40:066 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
03:12:40:069 LightNode 1: Configuration tool 1 added
03:12:40:142 DB SELECT manufacturername FROM nodes WHERE mac LIKE '5c:02:72:ff:fe:ce:41:b2%' COLLATE NOCASE: _TYZB01_8ppvdbpz
03:12:40:145 LightNode 3: On/Off light 3 added
03:12:41:231 COM: /dev/ttyACM0 / serialno: , ConBee II
03:12:42:160 wait reconnect 5 seconds
03:12:42:183 COM: /dev/ttyACM0 / serialno: , ConBee II
03:12:43:119 wait reconnect 4 seconds
03:12:44:118 wait reconnect 3 seconds
03:12:45:127 wait reconnect 2 seconds
03:12:46:119 wait reconnect 1 seconds
03:12:46:140 COM: /dev/ttyACM0 / serialno: , ConBee II

**Comment by Mimiix** [comment]
Hi,

As this is not directly a bug as described in #5113 , i am closing this issue.

Any User/support/help requests are moved to the https://forum.phoscon.de

Closing this issue.
