### ISSUE TITLE
Failed to flash CONBEE II firmware

### ISSUE THREAD

**Issue by tempacgitac** [dresden-elektronik/deconz-rest-plugin#5314]
## Describe the bug

My Conbee II has lost connection to my zigbee device and now when I enter the light switch into pairing mode, it will not recognize anything. I've tried to flash the firmware using the instructions on this site

and I get the following error:

Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
Reboot device /dev/ttyACM0 (ConBee II)
retry, failed

952: Error: failed to open device, status: Is a directory (11)

Flashing Error! Please re-run this script...

## Environment

 - Host system: PC
 - Running method: Ubuntu
 - Firmware version: (0x26660700)
 - deCONZ version: (2.xx.yy)
 - Device: Conbee II
 - Do you use an USB extension cable: (yes / no) -- no (but will try it now when I can actually find the device)
 - Is there any other USB or serial devices connected to the host system? If so: Which? No

**Comment by Mimiix** [comment]
This is once again not a bug but a user question. The error in question is clear.

You have a forum topic opened, please use that one for support.
