### ISSUE TITLE
issue with RH3052

### ISSUE THREAD

**Issue by luka6000** [dresden-elektronik/deconz-rest-plugin#5316]
## Describe the bug

I have issue with RH3052 temperature and humidity sensor https://zigbee.blakadder.com/Rehent_RH-ZTH1.html
I have a few of those and they eat batteries like crazy.
![image](https://user-images.githubusercontent.com/1110994/134217686-98f2160e-2488-4188-ae40-61619331d47c.png)
This example is pretty extreme but it was a shitty CR2032. Good battery like Energizer or Duracell lasts no longer than 1-2months. And after falling below 50% it dies in a few days.
I think the reason for this could be that this sensor is forced to push measurements at least every 5minutes while I would happily use 20 minutes or even every 60 minutes and 0.2K change.
![image](https://user-images.githubusercontent.com/1110994/134218297-1af656ce-de4c-47fa-8a0d-335b773d237c.png)
I can change this setting and sensor takes new values and is pushing measurements with much longer periods. But this last for half a day or so. Then, with no action on my side, Max Report Interval goes back to 300.
Does it suppose to work like that?

## Expected behavior

Reporting Configuration should last till sensor reset.
## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: 26680700
 - deCONZ version: 2.12.6 (latest stable)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment]
As far as i know, this is in the device. If it doesn't support this feature/saves properly, than its a device issue.

**Comment by luka6000** [comment]
> The reset you mentioned is an actual safeguard mechanism to reconfigure devices, 

Ok, so basically you confirm this is by design. Good we'll be able to change it with new configs. 



> As a side note, I wouldn't consider temp/hum devices using a CR2032 as reasonable players for that purpose.

Well, what would you recommend? I use those sensors as external room sensors for my TRVs
