### ISSUE TITLE
Device Request - Linkind Zigbee Water Leak Sensor

### ISSUE THREAD

**Issue by crazifyngers** [dresden-elektronik/deconz-rest-plugin#5317]
Requesting support for this device.  thanks!

Device
Product name: Linkind zigbee water leak sensor
Manufacturer: LK
Model identifier: A001082

Device type :
Sensor: Leak sensor

Screenshots
Basic
![image](https://user-images.githubusercontent.com/3136615/134370727-109bc232-1ce5-4ae0-bd84-c274de67df1f.png)

Identify
![image](https://user-images.githubusercontent.com/3136615/134370836-fecd2c07-a282-4448-a13f-833f77bee7ce.png)

Alarms
NA

Device Temperature
NA

Groups
na

Scenes
na

On/Off
na

Level Control
na

Color Control
na

Simple Metering
na

Diagnostics
![image](https://user-images.githubusercontent.com/3136615/134372234-068a51a1-9ab6-4de7-bcdb-0188dc0659d9.png)

Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/3136615/134371447-1cacf4de-a1ae-4b28-87b2-bb430c7d3e6f.png)

![image](https://user-images.githubusercontent.com/3136615/134371840-291144e5-6ce5-4399-9c5c-b33f5422f58b.png)

![image](https://user-images.githubusercontent.com/3136615/134371986-ec13009c-d741-4d2a-8483-97d75e2d49a0.png)

![image](https://user-images.githubusercontent.com/3136615/134372080-067105d2-7e03-4baf-8dae-9f35cbf24d13.png)

![image](https://user-images.githubusercontent.com/3136615/134372564-409c9784-0e5c-48a7-97d4-2c009d292ae4.png)

**Comment by Mimiix** [comment]
If you want to have this reopened, just ask @nmr94 😅
