### ISSUE TITLE
Iluminize 511.344 (4 channel RGBW / RGB+CCT remote control)

### ISSUE THREAD

**Issue by Somebodyisnobody** [dresden-elektronik/deconz-rest-plugin#5319]
## Device

- Product name: Model `511.344` and `5130.54` on the packaging.
- Manufacturer: `iluminize`
- Model identifier: `ZG2819S-RGBW`
- Device type : Please remove all unrelated device types. 
  - Other: Remote RGB 4 channel

## Screenshots
![node_info](https://user-images.githubusercontent.com/35230554/134536316-da43eea3-876e-4075-b28f-1f3fcbe1a092.png)
![clusters](https://user-images.githubusercontent.com/35230554/134536252-d216076c-1ee6-4423-92e5-50d08992fd04.png)

### Basic
![cluster1_to_4_basic](https://user-images.githubusercontent.com/35230554/134536595-295a7bed-380a-4150-8fa8-a208d8d07b5e.png)
(same for all 4 clusters)
### Identify
![grafik](https://user-images.githubusercontent.com/35230554/134536773-463018e3-2010-41cf-8810-633e549f8b06.png)

### Scenes
no read option
### On/Off
no read option
### Level Control
no read option
### Color Control
no read option
### Other clusters that are not mentioned above
on request, seems not interesting

**Comment by Somebodyisnobody** [comment]
keep me open

**Comment by Somebodyisnobody** [comment]
Keep me open

**Comment by Somebodyisnobody** [comment]
keep me open

**Comment by Somebodyisnobody** [comment]
keep me open

**Comment by Mimiix** [comment]
@Smanar can this be done with ddf?

**Comment by Smanar** [comment]
Not yet, it's a battery remote.

**Comment by Somebodyisnobody** [comment]
Yeah it is. Both have 4 zones. The only difference should be that this one here has rgb-clusters

**Comment by Smanar** [comment]
Yep, I think it will be not so hard, but for the moment new device integration is possible only using DDF, and the core don't support yet battery remote.

**Comment by Somebodyisnobody** [comment]
Is there an issue open addressing the missing core-functionality. Then we can link it as dependency and don't forget this one.

**Comment by Smanar** [comment]
The Todo list is probalby huge ^^
But no one will close the issue, after a time a bot will make a comment, you just need to make another one to keep the issue open, or simplely ask to re-open it.

**Comment by Mimiix** [comment]
@smanar if it's a small addition and @Somebodyisnobody can test it, you can create a pr :)

**Comment by Somebodyisnobody** [comment]
I would test it

**Comment by Smanar** [comment]
You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch Iluminize https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

If you have a small raspberry, it can freeze during compilation, my pi 3 do, so remove "-j2"

and you need too replace the json file
/usr/share/deCONZ/devices/button_maps.json by this one https://github.com/Smanar/deconz-rest-plugin/blob/Iluminize/button_maps.json


Only one edition line 1406 

`"modelids": ["ZGRC-TEUR-003", "ZG2819S-RGBW"],`


If I m right :
- the device will be added in the API
- you will have only 1 sensor entry for all endpoint
- you will have some return for button, I have mimic the other remote, but I don't think all will work.

**Comment by Somebodyisnobody** [comment]
oh I have a todo here... will be done in the next days

**Comment by JayJay68** [comment]
I don't know, if this is the right place (or should I start a new request?):

I have such "switch" too => Iluminize 511.544 (ZGRC-TEUR-001). This device 511.544 is like "ZGRC-TEUR-003" (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3289)  with 4 zones, but controls RGB+CCT and not only CCT. 

My device can join the network and is listed in the list of switches (app). But I can't assign the switch to a group. Or is the device not supported yet (I have Version 2.12.06 => should I update to 2.14.xx?)

**Comment by Mimiix** [comment]
@JayJay68 Feel free to open a new issue :)

**Comment by Somebodyisnobody** [comment]
Now I was back in the appartment. I tried to compile and run it on WSL ubuntu, but i cannot find the services. I cannot use systemctl and `service --status-all` doesn't show the deconz-services. I'll give up here. In meantime I found a solution by connecting the remote with the lamps directly using the deconz-client application.
