### ISSUE TITLE
Tuya 2 Gang ZigBee Dimmer Module

### ISSUE THREAD

**Issue by vishivishy** [dresden-elektronik/deconz-rest-plugin#5320]
## Device

- Product name: MoesHouse 2 Gang ZigBee Dimmer Module MS-105BZ
- Manufacturer:  _TZE200_e3oitdyu
- Model identifier: TS0601
- Device type : Light

## Screenshots

<img width="694" alt="Screen Shot 2021-09-24 at 3 26 24 pm" src="https://user-images.githubusercontent.com/72184447/134622935-d5f7a14a-4770-43e1-8afd-ed39c7e4f6cb.png">

### Basic

<img width="682" alt="Screen Shot 2021-09-24 at 3 10 28 pm" src="https://user-images.githubusercontent.com/72184447/134623043-2afb6a4b-3aca-46cd-9158-ce04d770f295.png">

### Groups

<img width="300" alt="Screen Shot 2021-09-24 at 3 23 56 pm" src="https://user-images.githubusercontent.com/72184447/134623082-34f377b7-65c6-47f4-8ac5-1392f354ab9d.png">

<img width="294" alt="Screen Shot 2021-09-24 at 3 24 19 pm" src="https://user-images.githubusercontent.com/72184447/134623089-c51ea878-b450-4b2c-8900-0560bd77cf92.png">

### Scenes

<img width="295" alt="Screen Shot 2021-09-24 at 3 24 35 pm" src="https://user-images.githubusercontent.com/72184447/134623115-5ea06c75-8c4f-476a-863b-96f22cbbc37a.png">

<img width="295" alt="Screen Shot 2021-09-24 at 3 33 46 pm" src="https://user-images.githubusercontent.com/72184447/134623479-0a202a79-9d58-4f52-a148-42b382331e43.png">

<img width="297" alt="Screen Shot 2021-09-24 at 3 34 11 pm" src="https://user-images.githubusercontent.com/72184447/134623489-dd3b3003-8d26-4773-9c63-d1deecbacc55.png">

<img width="299" alt="Screen Shot 2021-09-24 at 3 25 00 pm" src="https://user-images.githubusercontent.com/72184447/134623128-8586c9f5-3e3a-421a-8df8-0b9ba1f5dbe1.png">

### Other clusters that are not mentioned above
<img width="300" alt="Screen Shot 2021-09-24 at 3 25 16 pm" src="https://user-images.githubusercontent.com/72184447/134623178-d01b6d1f-5cc2-4636-9b2f-65090dda5c7a.png">
<img width="685" alt="Screen Shot 2021-09-24 at 3 25 42 pm" src="https://user-images.githubusercontent.com/72184447/134623206-6d408bc5-7f5f-4e44-adb8-ebd019440455.png">

**Comment by Mimiix** [comment]
Can you please add all  screens?

**Comment by 01vova** [comment]
> Can you please add all screens?

Hi Mimiix, 👋  vishivishy here. Hope you've been well.
Sorry I couldn't figure out earlier how to get additional cluster info screens. I've added them now, do let me know if there's anything else needed.
Thanks!!

**Comment by Smanar** [comment]
It s perhaps a 1 line edit modification.

Do you have a linux machine with full OS to test a code modification ?

**Comment by vishivishy** [comment]
Hi @Smanar thanks for looking into this. So is it that 2 gang can not be supported by deconz or that I wont be able to test the new modified code?

**Comment by Smanar** [comment]
Can work, as you are not using common Mac adress, from the issue it seem the only one other device that use this mac adress is a covering.

You have a linux machine with full OS ?

**Comment by vishivishy** [comment]
I can setup a new linux vm if that works.. (if you can give me details of the setup)

**Comment by Smanar** [comment]
Yes it work on VM, so you need to set the VM, update the OS, install deconz using package method https://www.phoscon.de/en/conbee2/install

For the rest you have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch tuya_dimmer_test_1 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by vishivishy** [comment]
I already am able to use on/off for 1 gang on the current deconz (6.10.0) firmware(26660700). 
but do not have control over brightness or the second gang.

**Comment by vishivishy** [comment]
> Yes it work on VM, so you need to set the VM, update the OS, install deconz using package method https://www.phoscon.de/en/conbee2/install
> 
> For the rest you have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
> So for you, after having installed deconz :
> 
> ```
> sudo apt install deconz-dev
> git clone --branch tuya_dimmer_test_1 https://github.com/Smanar/deconz-rest-plugin.git
> cd deconz-rest-plugin
> qmake && make -j2
> sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
> ```
> 
> But from the code, you need to have at least the on/off working for one gang ?

@Smanar so I ran the updated plugin on the linux vm and I'm able to control brightness of the 1 gang that I was able to turn on and off earlier.
I do however see 2 additional lights in the Phoscon app but turning them on/off does not translate to actions on gang 2.

here are some screenshots from the test

<img width="670" alt="Screen Shot 2021-09-26 at 2 20 31 am" src="https://user-images.githubusercontent.com/72184447/134778705-b311b295-b15d-4f3c-b406-bb2178feb7f5.png">
<img width="544" alt="Screen Shot 2021-09-26 at 2 21 23 am" src="https://user-images.githubusercontent.com/72184447/134778716-8a9135a4-4ed1-4910-b53a-50c4880153b3.png">

## Basic
<img width="780" alt="Screen Shot 2021-09-26 at 2 24 12 am" src="https://user-images.githubusercontent.com/72184447/134778721-4261042c-e83a-4137-bd1c-8cb20c592f07.png">

## Groups
<img width="773" alt="Screen Shot 2021-09-26 at 2 24 52 am" src="https://user-images.githubusercontent.com/72184447/134778723-15507186-369a-475b-a7e3-5ef0eb49d2fe.png">

## Scenes
<img width="759" alt="Screen Shot 2021-09-26 at 2 25 31 am" src="https://user-images.githubusercontent.com/72184447/134778763-a3a9cda1-1b11-45f6-b765-038af359f567.png">

## Other
<img width="765" alt="Screen Shot 2021-09-26 at 2 25 47 am" src="https://user-images.githubusercontent.com/72184447/134778784-806fe852-b039-476c-bc26-a24726573185.png">
<img width="736" alt="Screen Shot 2021-09-26 at 2 26 53 am" src="https://user-images.githubusercontent.com/72184447/134778800-e34d91a1-85c2-45b5-8101-7d592c9fdcae.png">

**Comment by Smanar** [comment]
Yes the code create 3 "light", it s because this part is a hack used for 3 gangs devices.
Have modified the code again, to try to enable the second gang.

```
cd deconz-rest-plugin
git pull
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

**Comment by vishivishy** [comment]
Hi @Smanar! I've tested the new changes and here are the findings:
- I still have 3 lights visible in the phoscon and deconz webapp
- I am able to turn on/off and change brightness of gang 1 in Phoscon app as one would expect.
- I am able to "only turn on" and change the brightness of gang 2 in phoscon app (the light does not show if it is turned on, it always shows light is off. and sometime after setting the brightness, the brightness slider moves back to 0% brightness as it seems to not be able to read the status of the device) and because the phoscon app thinks the light is not turned on it does not let me turn off the light. I have tried showing this in the following screenshots.
<img width="1059" alt="Screen Shot 2021-09-26 at 6 42 27 pm" src="https://user-images.githubusercontent.com/72184447/134801247-028dd9a9-1601-4c0d-b256-98b1a85ce23e.png">
The light turned on and brightness was set correctly on the device but that does not reflect in the phoscon app later (problem only with gang 2)
<img width="1133" alt="Screen Shot 2021-09-26 at 6 44 10 pm" src="https://user-images.githubusercontent.com/72184447/134801263-34f8a80e-224e-4fc2-946f-5aae53d07e7a.png">

- The deconz webapp is not able to turn on any of the lights. so both gang 1 and gang 2 do not respond in the deconz webapp but other single gang relay based zigbee switches can be turned on/off from the app.
<img width="624" alt="Screen Shot 2021-09-26 at 7 04 49 pm" src="https://user-images.githubusercontent.com/72184447/134801276-a07a9095-c5f2-484b-9881-b2c2c17b9f3b.png">

## Node Info
<img width="1016" alt="Screen Shot 2021-09-26 at 6 43 02 pm" src="https://user-images.githubusercontent.com/72184447/134801348-8db247d8-1546-417b-8ace-7963bc054d22.png">


## Basic
<img width="1010" alt="Screen Shot 2021-09-26 at 6 43 27 pm" src="https://user-images.githubusercontent.com/72184447/134801334-d7257a52-e7c0-4fba-8110-0a855e000a76.png">

**Comment by Smanar** [comment]
>I still have 3 lights visible in the phoscon and deconz webapp

Yeap, this is normal for the moment, will be corrected in the future with ddf file, I need to remove this hack

And you was right for the rest, it s because the return state was bad. Have updated the code again.

But for the code is not working using the second Webapp, it s strange, are you able to find some logs somewhere ? using the dev console, deconz logs, or others ?

**Comment by vishivishy** [comment]
Hooray! Both the gang lights are working as expected in the Phoscon app! 
But as for the deconz webapp its the same outcome as before. I did however follow the step 9 from following guide to generate the attached log file. 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing

I could only see these errors in the logs but have attached the log file in case you need to check something else out. 

> 00:07:54:568 Erase task req-id: 11, type: 14 zcl seqno: 70 send time 1, profileId: 0x0104, clusterId: 0x0006
00:07:55:595 API error 6, /lights/4/state, parameter, id, not available
00:07:57:071 Daylight now: nadir, status: 100, daylight: 0, dark: 1
00:07:57:858 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x93F3
00:07:57:858 neigbor 0x00158d00067efd68 is unknown child
00:07:57:858 neigbor 0x00158d00023e8027 is unknown child
00:07:58:314 CTRL skip creating node 0x00158D00067EFD68 while permit join is disabled
00:07:58:771 API error 6, /lights/4/state, parameter, id, not available
00:07:58:790 CTRL skip creating node 0x00158D00023E8027 while permit join is disabled
00:08:00:180 API error 6, /lights/5/state, parameter, id, not available
00:08:02:272 API error 6, /lights/5/state, parameter, id, not available
00:08:02:656 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0xEC07

[test_debug.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7231517/test_debug.log)
I kept the test quick and short under 1 minute so there is not too much noise and log file stays small, hope this helps. Do let me know if you need me to get you any other logs. Thanks!

**Comment by Smanar** [comment]
Hu .., In fact I have some problem ATM, I have no internet connexion, and no deconz running to check ^^.
But I can't understand why it work on phoscon and not the old webapp.

>00:07:58:771 API error 6, /lights/4/state, parameter, id, not available

Something is bad on the request

Something you can try is enabling the developper console on your web browser to check http request or easier check for "http" logs on deconz.

Take care care thoses logs are realy talkative, so enable only "http", on thoses logs you will see incoming and outgoing requests from deconz, so you will see the request made by phoscon and the one made by the old webapp.
Perhaps you will see something different in them ?

**Comment by vishivishy** [comment]
Hi @Smanar, so I had a look at the requests being sent by Phoscon and deconz webapp, and seems like the two apps are sending different payload in the put request. 
Phoscon is sending this and getting response code 200
> 

and deconz webapp is sending this and getting response code 400
> 

it seemed like the api is not expecting the "id" parameter in the payload so I tested on postman and can confirm that when we send id param in payload the server sends a 400 response, but if I remove the id param the server responds with 200 and turns on the light.

An interesting thing I noted is that sending "id" parameter in payload for a device with single gang does not return a bad request 400 response and it turns on the light as shown in the screenshots below.
<img width="1595" alt="Screen Shot 2021-09-27 at 10 41 54 pm" src="https://user-images.githubusercontent.com/72184447/134916330-fe3e2216-1f57-4feb-825d-99d6f3d992da.png">
<img width="1517" alt="Screen Shot 2021-09-27 at 10 42 18 pm" src="https://user-images.githubusercontent.com/72184447/134916439-444ffca5-84fb-4a27-afc3-7eb6fbf594ef.png">
<img width="1571" alt="Screen Shot 2021-09-27 at 10 42 35 pm" src="https://user-images.githubusercontent.com/72184447/134916605-ce8bef45-51f2-4c64-9d15-09296be6ebc0.png">
<img width="1599" alt="Screen Shot 2021-09-27 at 10 43 02 pm" src="https://user-images.githubusercontent.com/72184447/134916641-fe36a44d-a7eb-40ef-9fc7-5359ea189bf5.png">
<img width="1585" alt="Screen Shot 2021-09-27 at 10 43 16 pm" src="https://user-images.githubusercontent.com/72184447/134916706-cd45d591-52f1-463e-936b-5db5b36df2d2.png">
<img width="1590" alt="Screen Shot 2021-09-27 at 10 43 31 pm" src="https://user-images.githubusercontent.com/72184447/134916763-e491ccee-d899-4792-8db3-44802d8d8cd9.png">

**Comment by Smanar** [comment]
Ok have added a code part to make the "id" skipable for the tuya part. (Same command to update your code)
But I have not understand why it work for simple gang ....

**Comment by vishivishy** [comment]
Thanks @Smanar everything seems to be working now!!

**Comment by Smanar** [comment]
Have just made the PR.
ATM we are waiting for DDF file, so lot of PR are locked in waiting list.

Next is waiting for validation, but it s possible I change the code to use DDF file ( to remove the useless "light" entry)

**Comment by vishivishy** [comment]
Cool, sounds good. I'll look forward to troubleshooting and fixing another tuya device with you someday.. :)

**Comment by vishivishy** [comment]
Hi @Mimiix! sorry for being a bother, but any luck asking manup?

**Comment by Mimiix** [comment]
No response on it. Just need to wait it out.

**Comment by christianmcardle** [comment]
I've been trying out the new driver, having bought a clutch of these devices on AliExpress, claiming they were real Zigbee 3!

I've currently got two of these devices in my setup (with another two along shortly). When I run the code from the branch above, one of them becomes dimmable, whilst the other one remains on/off only. Both have multiplied to 3 gang, as expected, although I'm currently only using one of the gangs. All the gangs on the first device are dimmable. None of the gangs on the second device are.

**Comment by vishivishy** [comment]
@christianmcardle I only had one device installed so I could only test on that. but this is interesting and super weird that the second device does not work as expected. I'll install the 2nd dimmer device soon and report after testing it myself.

**Comment by christianmcardle** [comment]
I've now connected the other two I had. Both of these worked (i.e. three working simultaneously with brightness support). So I think it is just one faulty device, rather than a driver issue. All have the same device type identifier. No amount of repowering or repairing fixes it. I'll probably just pop it in the trash.

**Comment by Smanar** [comment]
It's totaly random, there is new tuya every days, and all look same, need to compare according the manufacture name and MAC address.

**Comment by vishivishy** [comment]
not stale

**Comment by vishivishy** [comment]
not merged yet

**Comment by randysnel** [comment]
looking forward to buy one, so hope it will be merged soon!

**Comment by vishivishy** [comment]
not stale

**Comment by LongTimeUser77** [comment]
I have the phoscon II and de deconz software on my pi.
The moes 2 gang from ali express installed in my kitchen.
but in the software only getting a light bulb. No dimmer function of two dimmers shown.
I see that on the 2mqtt this _TZE200_e3oitdyu works as it should. 
When will this be available on the deconz?
I have a phonscon II on my pi 3
deconz firmware 26720700
version 2.14.00

**Comment by Smanar** [comment]
For the moment PR are locked to use only DDF https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5733

This device can't be added using DDF, so need to improve the DDF core to manage tuya cluster.

**Comment by vishivishy** [comment]
not stale
