### ISSUE TITLE
Conbee 2 just won't connect to devices, has it DIED after 2months of usage?

### ISSUE THREAD

**Issue by SeanHama** [dresden-elektronik/deconz-rest-plugin#5324]
## Describe the bug

One day Conbee 2 stop working, all the devices disconnected out of thin air. I have put in a new extension cable and its not working still. Its plugged into my USB 2 on my RPI4. It was working solid for 2months then died.

## Steps to reproduce the behavior

 
  1. Go to 'Deconz, or goto Phoscon app,
  2. Devices not connecting to conbee 2
 3. I have latest firmware or conbee2 and deconz

## Expected behavior

should be working

## Screenshots

![Screenshot (2)](https://user-images.githubusercontent.com/57736130/134794961-71cbea29-5dc3-482d-94c7-8c8439d231d9.png)

## Environment

  The deCONZ and firmware versions are found in the Phoscon App: Menu -> Settings -> Gateway,
  as well as in the deCONZ GUI: Menu > Help > About deCONZ.

 - Host system: Raspberry Pi 4
 - Running method: (Raspbian only, no docker
 - Firmware version: (latest 19/08/2021) 26720700
 - deCONZ version: (2.12.06
 - Device:  ConBee II 
 - Do you use an USB extension cable: -yes 
 - Is there any other USB or serial devices connected to the host system? yes, clipsal device

## deCONZ Logs

05:30:29:375 DB save zll database items 0x00000001
05:30:29:376 DB sql exec REPLACE INTO nodes (id, state, mac, name, groups, endpoint, modelid, manufacturername, swbuildid, ritems) VALUES ('2', 'normal', '00:21:2e:ff:ff:07:43:d3-01', 'Configuration tool 2', '65520', '1', 'ConBee II', 'dresden elektronik', '0x26720700', '{"attr/id":"2","attr/lastannounced":null,"attr/lastseen":"2021-09-26T05:29Z","attr/manufacturername":"dresden elektronik","attr/modelid":"ConBee II","attr/name":"Configuration tool 2","attr/swversion":"0x26720700","attr/type":"Configuration tool","attr/uniqueid":"00:21:2e:ff:ff:07:43:d3-01","state/reachable":true}')
05:30:29:387 DB saved in 12 ms
05:30:29:495 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:29:497 Websocket 192.168.0.69:51275 send message: {"attr":{"id":"2","lastannounced":null,"lastseen":"2021-09-26T05:30Z","manufacturername":"dresden elektronik","modelid":"ConBee II","name":"Configuration tool 2","swversion":"0x26720700","type":"Configuration tool","uniqueid":"00:21:2e:ff:ff:07:43:d3-01"},"e":"changed","id":"2","r":"lights","t":"event","uniqueid":"00:21:2e:ff:ff:07:43:d3-01"} (ret = 344)
05:30:29:498 Websocket 192.168.0.90:54288 send message: {"attr":{"id":"2","lastannounced":null,"lastseen":"2021-09-26T05:30Z","manufacturername":"dresden elektronik","modelid":"ConBee II","name":"Configuration tool 2","swversion":"0x26720700","type":"Configuration tool","uniqueid":"00:21:2e:ff:ff:07:43:d3-01"},"e":"changed","id":"2","r":"lights","t":"event","uniqueid":"00:21:2e:ff:ff:07:43:d3-01"} (ret = 344)
05:30:29:499 Websocket 192.168.0.160:60591 send message: {"attr":{"id":"2","lastannounced":null,"lastseen":"2021-09-26T05:30Z","manufacturername":"dresden elektronik","modelid":"ConBee II","name":"Configuration tool 2","swversion":"0x26720700","type":"Configuration tool","uniqueid":"00:21:2e:ff:ff:07:43:d3-01"},"e":"changed","id":"2","r":"lights","t":"event","uniqueid":"00:21:2e:ff:ff:07:43:d3-01"} (ret = 344)
05:30:30:375 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
05:30:30:376 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
05:30:30:376 tcAddress is 0x0000000000000000 but should be 0x00212EFFFF0743D3, start reconfiguration
05:30:30:376 Skip automatic channel change, TODO warn user
05:30:32:375 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:35:255 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:38:134 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:40:375 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
05:30:40:377 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
05:30:40:377 tcAddress is 0x0000000000000000 but should be 0x00212EFFFF0743D3, start reconfiguration
05:30:40:378 Skip automatic channel change, TODO warn user
05:30:41:015 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:43:895 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:46:775 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:46:875 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
05:30:46:877 Idle timer triggered
05:30:49:655 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:50:375 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
05:30:50:376 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
05:30:50:376 tcAddress is 0x0000000000000000 but should be 0x00212EFFFF0743D3, start reconfiguration
05:30:50:376 Skip automatic channel change, TODO warn user
05:30:50:408 Device TTL 3222 s flags: 0x3
05:30:52:535 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:55:415 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:30:58:295 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:00:375 Daylight now: solarNoon,
 status: 170, daylight: 1, dark: 0
05:31:00:376 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
05:31:00:377 tcAddress is 0x0000000000000000 but should be 0x00212EFFFF0743D3, start reconfiguration
05:31:00:378 Skip automatic channel change, TODO warn user
05:31:01:175 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:04:055 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:06:935 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:09:894 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:10:375 Daylight now: solarNoon, status: 170, daylight: 1, dark: 0
05:31:10:376 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
05:31:10:376 tcAddress is 0x0000000000000000 but should be 0x00212EFFFF0743D3, start reconfiguration
05:31:10:377 Skip automatic channel change, TODO warn user
05:31:12:694 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:15:575 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000
05:31:16:876 Idle timer triggered
05:31:18:454 void deCONZ::zmNode::setFetched(deCONZ::RequestId, bool) fetched item: 8, node: 0x0000  

Debug logs can help to investigate certain problems like device pairing and communication issues.
  Logging can be enabled on the command line as described in:
  https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags
  Secondly, for versions above 2.05.87: In the deCONZ GUI: click Help > debug view. Output of APS,ZDP, ZCL and INFO can be handy.

**Comment by Smanar** [comment]
05:30:30:376 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
05:30:30:376 tcAddress is 0x0000000000000000 but should be 0x00212EFFFF0743D3, start reconfiguration

You have setting issue
Try to restore an old backup

Or try
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Network-lost-issues

Can compare your setting with the capture from this link too
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Network-lost-and-configuration-restore-does-not-help

**Comment by SeanHama** [comment]
Ok, ive tried all your suggestions.
Ive reflashed firmware, Im on latest version of deconz.

Any other ideas pls, my house needs lights

**Comment by SeanHama** [comment]
The TC ADDRESS AND TC LINK MASTER KEY A ZERO? Is that the issue?

**Comment by Smanar** [comment]
You have tried an olad backup ?
Or use the hidden config to set an old connexion setting ?
And you still have the same error message ?

Have you tried to compare your setting with the last link and set them correctly manually ?

**Comment by SeanHama** [comment]
Yes Ive tried old backup, it doesnt work 

"Or use the hidden config to set an old connexion setting ?" this page is not working. How do I exactly getting this to appear. I followed the article but nothing.



"Have you tried to compare your setting with the last link and set them correctly manually ?" ---> how do I do that?

**Comment by SeanHama** [comment]
Can we jump on a screenshare. ??

**Comment by Smanar** [comment]
>this page is not working. How do I exactly getting this to appear. I followed the article but nothing.

You have used ALT + clic ?

>how do I do that?

On the GUI, on the menu, you have something like "network setting", just compare that you have with the capture on the link.

**Comment by SeanHama** [comment]
Alt + click does not work? Have you confirmed it still works in the latest release?

>

**Comment by SeanHama** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/57736130/134804789-8483a2e0-4b76-4e20-b6f3-807da828a6b1.png)
Alt+Click, look at what happens

**Comment by SeanHama** [comment]
This is my Deconz, any ideas or suggestions?
![Screenshot (4)](https://user-images.githubusercontent.com/57736130/134805002-22da0aa3-6c65-480b-8293-8f65f8dc97b5.png)

**Comment by SeanHama** [comment]
This is what is appearing now in my Network settings, its still not working?
![Screenshot (5)](https://user-images.githubusercontent.com/57736130/134805238-81e0ff46-f236-4428-829f-beae1862b16f.png)

**Comment by Mimiix** [comment]
Hi, 

As this is not a bug report as described in #5113, this issue gets closed. 

Feel free to use the forum for user questions.
