### ISSUE TITLE
Tuya Door Magnetic Sensor Model ZM-CG205

### ISSUE THREAD

**Issue by FHEMUser** [dresden-elektronik/deconz-rest-plugin#5331]
## Device

- Product name: Zigbee Door Sensor
- Manufacturer: Tuya ?
- Model identifier: ZM-CG206
- Device type : Sensor

## Screenshots

![IMG_20211005_093811](https://user-images.githubusercontent.com/25867912/135981039-2a16cd6d-4d79-40e1-a0a8-9ad187078728.jpg)

![Screenshot 2021-09-30 132450](https://user-images.githubusercontent.com/25867912/135454747-4bd48cdb-b7d1-47de-beda-572d16d5c191.jpg)
### Basic
![Cluster_Basic](https://user-images.githubusercontent.com/25867912/135454773-d4650971-3b2f-428f-859c-91943025a2cc.jpg)

### Identify
![Cluster_Ident](https://user-images.githubusercontent.com/25867912/135454798-7f9d009a-e4f8-4891-a914-5c4d374c3717.jpg)

### Other clusters that are not mentioned above
![Cluster_Power](https://user-images.githubusercontent.com/25867912/135454867-741fc7e9-d078-452f-a5e4-17d3a3880c26.jpg)

![Cluster_IAS](https://user-images.githubusercontent.com/25867912/135454897-629c2234-559d-4c07-9450-9e96406d5037.jpg)

**Comment by onebavarian** [comment]
Hello, is there any update on that or has anyone a working DDF file? 
With beta 2.13.01 it gets recognized as _TZ3000_cn58yln1 with Model ID TS0203. 
But somethings wrong, it doesn`t work.

**Comment by Smanar** [comment]
All the discution is here ^^

Can you make a try with DDF file ?

**Comment by onebavarian** [comment]
I have no idea what I am doing but I'm trying.

Right now the state open/closed is working with Phoscon and HomeAssistant and after 10 minutes battery state too.

I edited the DDF Phoscon showed me for device _TZ3000_cn58yln1.
Copied and pasted lines 9 to 129 from https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/wiser/contact_sensor_cct591011_as.json into "Preview", overwriting the original lines.
Changed under "state/open" the following values to:   
 "at": "0x0002",
 "cl": "0x0500",

Right now, I'm not sure if "Model ID" and "Product" should be "ZM-CG205" and what I should use for "Manufacturer Name"

I attached the DDF File as txt.

[contact_sensor_thi_tuya.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7492706/contact_sensor_thi_tuya.txt)

**Comment by Smanar** [comment]
Model id  : TS0203
manufacturername : _TYZ ..... (make drag and drop from the attribute 0x0004 on the 3th capture.

I m surprised it have worked with bad values ....

**Comment by onebavarian** [comment]
Changed:
"manufacturername": "_TYZB01_xph99wvr",
"modelid": "TS0203",
"product": "TS0203",

[contact_sensor_thi_tuya.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7492749/contact_sensor_thi_tuya.txt)
 
I am surprised too.

**Comment by Smanar** [comment]
The DDF seem fine, it s not working ?
The device still have 0xXXXX as name on the GUI ?

**Comment by onebavarian** [comment]
The DDF is working - added 2 more devices and it shows me "OpenClose" and a number. 

I'm happy right now.

**Comment by Smanar** [comment]
NP, thx for the DDF, will help other users.

**Comment by FHEMUser** [comment]
I load the DDF file to the device and a hit "hot reload".
But what is the next step ?
I do not see new devices in the phoscos app.

**Comment by Smanar** [comment]
The device can be invisible in phoscon.
If the name change 0xXXXX to "OpenClose X" it s ok.

**Comment by onebavarian** [comment]
With one device I had to pair it again, then it worked.

**Comment by FHEMUser** [comment]
I have 3 items of this.
At the start you see one device have Basic Cluster, now no device have this Basic info.
Manufacturer and Model Identifier always unknown.
I use FHEM as Homeautomation and the device must be visible on Phoscon to use it.

I don´t understand why all devices have no basic info.
I delete all, do a new pairing with long press (10 seconds) and i see the new device only with no basic info.

![Screenshot 2021-11-09 182442](https://user-images.githubusercontent.com/25867912/140974787-46954e59-2424-4088-9059-713eee5cef85.jpg)

**Comment by FHEMUser** [comment]
Hey it works !
I hit the rest pin long (10 seconds) and the LED flash. I think thats a reset
Then i hit the pin again until the LED flash (5 seconds) and the device will be created.
Now i have the basic info.

Then again reset an pair and the device will show on phoscon !
I think reset and pair must be do more than 1 time.

Now i am happy again. The aqara devices are more and more expensive. This tuya devices are some cheaper.
Ok, i add the other two and will test it !

Thanks !

**Comment by onebavarian** [comment]
Just wanted to write the same. :) 

With my third device I had to pair again without deleting it first. I think the first 2 worked because I paired them mutliple times. 

I'm glad it worked!

**Comment by FHEMUser** [comment]
> Just wanted to write the same. :)

Do you see the devices in phoscon app ?

**Comment by onebavarian** [comment]
Yes, I see the devices in Phoscon. (I edited the numbers)
![Screenshot_20211110-080830_Chrome](https://user-images.githubusercontent.com/35399319/141066379-2e0ab3b7-f091-4e90-9782-5d988d27e21a.jpg)

I have no idea about the refresh.interval. As I said, I just merged 2 files and it worked. 

> Right now the state open/closed is working with Phoscon and HomeAssistant and after 10 minutes battery state too.
> 
> I edited the DDF Phoscon showed me for device _TZ3000_cn58yln1. Copied and pasted lines 9 to 129 from https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/wiser/contact_sensor_cct591011_as.json into "Preview", overwriting the original lines. Changed under "state/open" the following values to: "at": "0x0002", "cl": "0x0500",
>

**Comment by lazarus72** [comment]
Hello FHEMUser
Hello onebavarian

i also try to get this sensor connected, but i don't know ?
but I do not know what this ddf file is and where I can find it?
I tried several times with longer press the pin and then again. i get nothing displayed.
My version is 2.13.02 / 10.11.2021
@Smanar : will this sensor maybe be implemented in the next version? Because I have 12 of these :-)

best regards

**Comment by FHEMUser** [comment]
You must set to normal mode:

“Panels → Control → Normal mode” needs to be enabled.

This must be set every restart.
Then right Klick on the devices and "edit DDF".
Open the file that's posted here in the new window. Then hit "hot reload" on files menu or something in this new window. Close the window.

Now learn again the devices. I must do learning 2 times. Then it will show. In the phoscon app I don't see the new devices. But I don't need this.

Take a look here
https://forum.phoscon.de/t/door-magnetic-sensor-zm-cg205-by-tuya-paired-but-not-work/546/10

**Comment by lazarus72** [comment]
:-( i only have headless mode and i can't get the gui to work after the installation.
is there another way? directly in the console?

**Comment by Smanar** [comment]
Nope, else you can recompile the code with some personnal change, but it s more work to do.

**Comment by lazarus72** [comment]
hmm, i can'T connect to the gui.
i try to disable and stop deconz
and the to enable and start deconz-gui
but when i start deconz-gui nothing works anymore, no phoscon, i get an connection error message inside my domoticz and no switch is working.
also the vnc connection didn't work

what can i do?

@Smanar: is it foreseeable when this sensor is implemented in deconz?

**Comment by Smanar** [comment]
>also the vnc connection didn't work

You need to have a desktop to use the GUi version, if not it s probably for that VNC don't work too.

>is it foreseeable when this sensor is implemented in deconz?

I have perhaps a workaround, I m asking to be sure, but it seem on last version, the v12.3.3-beta, even with all by defaut DDF will be enabled for gold status.
So in theory, you just need to set the status to "gold" and put the file in the good directory.

**Comment by lazarus72** [comment]
what does this mean:  set the status to "gold" and put the file in the good directory.?

**Comment by Smanar** [comment]
For the status https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
And if it not work there is a way to force DDF be nabled with command line https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-command-line-parameters#dev-test-managed

**Comment by lazarus72** [comment]
Hi Smanar, sorry for the late feedback. I hope you had some pleasant holidays.
Thanks for your support and tips. I got it working now thanks to your help.
I installed the xserver and the session manager, and after adjusting the resolution I finally had access via VNC.
After stopping deconz headless I started the interface with deconz-gui.
After that, with the tips from you, FHEMUser and onebavarian, I was able to learn the sensors quite easily.
Thanks again to all of you and a happy new year

**Comment by Smanar** [comment]
NP, and happy Holidays too :)

**Comment by crazykiwi2003** [comment]
Will that device be included in one of the next Deconz/Phoscon releases so it can be paired without the DFF-workarounds?

**Comment by crazykiwi2003** [comment]
I would like to try, but unfortunately I have no idea how I can… :-/

**Comment by Smanar** [comment]
What is your OS ?
You just need to create a text file in a "devices" folder and call it whatyouwant.json

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by crazykiwi2003** [comment]
Thanks for the explanation. I just tried - unfortunately it does not work. Sensor cannot be found...
