### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by boldiebold** [dresden-elektronik/deconz-rest-plugin#5333]
## Device
same as here. 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4401
Just another slightly different manufacture id

Same device & functions

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other: 

## Screenshots
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4401

### Other clusters that are not mentioned abov
![Bildschirmfoto 2021-09-30 um 17 19 10](https://user-images.githubusercontent.com/52777334/135485438-4fab3d56-5a3a-479a-8464-24bb2fb7d9ef.png)
![IMG_1932](https://user-images.githubusercontent.com/52777334/135485464-1720f13b-9b91-4e4b-8b26-912fd59e45b9.jpeg)
e

**Comment by Mimiix** [comment]
Missing all screenshots. Please add them.
