### ISSUE TITLE
Innopro S-LUX-SB Light sensor

### ISSUE THREAD

**Issue by AlphaDE** [dresden-elektronik/deconz-rest-plugin#5342]
## Device

- Product name: Innopro S-LUX-ZB.
- Manufacturer: unknown
- Model identifier: unknown
- Device type : RFD
  - Sensor

## Screenshots

![S-LUB-ZB-Nodeinfo](https://user-images.githubusercontent.com/24697458/135767750-6dbb0243-36ef-4d73-ba80-2efb506f72f7.png)

### Other clusters that are not mentioned above

https://githubmemory.com/repo/Koenkk/zigbee2mqtt/issues/8036

https://zigbee.blakadder.com/Tuya_S-LUX-ZB.html

https://de.aliexpress.com/item/1005002828041023.html

**Comment by Mimiix** [comment]
Missing all screens.

**Comment by AlphaDE** [comment]
@Mimiix I tried to get more screens but I found no way to reach those shown in the linked instructions.

**Comment by Mimiix** [comment]
Check the wiki on how to read clusters

**Comment by AlphaDE** [comment]
Thanks @Mimiix 
![S-LUB-ZB-Cluster III](https://user-images.githubusercontent.com/24697458/135806079-40d1c5d8-8081-4283-8114-893e69f9a07c.png)
![S-LUB-ZB-Cluster I](https://user-images.githubusercontent.com/24697458/135806082-c7237fb7-e778-4859-ad2b-b6f8e19b81b2.png)
![S-LUB-ZB-Cluster II](https://user-images.githubusercontent.com/24697458/135806083-e60bf08a-5e2c-479d-8b26-0ef6a4f56718.png)

![S-LUB-ZB-Cluster VI](https://user-images.githubusercontent.com/24697458/135807008-d2ae6a3e-09a1-4621-bc94-83e615952cc6.png)
![S-LUB-ZB-Cluster IV](https://user-images.githubusercontent.com/24697458/135807010-79e2a775-30fc-4d45-a0a7-85165418fabd.png)
![S-LUB-ZB-Cluster V](https://user-images.githubusercontent.com/24697458/135807012-57699ce1-0e3e-44fc-9e26-ad482a7faf81.png)
