### ISSUE TITLE
IKEA Symfonisk controller doesn't send events?

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/deconz-rest-plugin#5346]
## Describe the bug

I've had some issues with the zigbee network, half of it is suddenly unresponsive.
So I restarted the deconz to make it better, and I've now walked around the house and 'rebooted' lights (screw them out, and back in) and most of it is back alive.
The Symfonisk controller does however not send any events. I've tried removing it and readding it, and all looks good (as shown in the images).
But I simply do not see any events in deconz_event in home assistant.

## Steps to reproduce the behavior

  1. Remove Symfonisk controller
  2. Search for controller
  3. Reset the controller
  4. Controller appears in deconz, I read all the clusters, no problems.

  If the problem can't be reproduced and is sporadic, please provide some details
  on how often and when the issue happens.

I'm not sure if this is reproducable. It has been working for months, and suddenly this?

## Expected behavior

It should send events for presses and rotation.
## Screenshots

![image](https://user-images.githubusercontent.com/13660621/135884844-7549964f-8b78-4400-b11d-3352158cd46f.png)
![image](https://user-images.githubusercontent.com/13660621/135884916-bdf6eae5-ec9e-4458-b3b5-f908f2936997.png)
![image](https://user-images.githubusercontent.com/13660621/135885014-a49c7fe6-7633-471c-bb23-c83860ea972d.png)

## Environment

 - Host system: PC with Proxmox
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (266B0700)
 - deCONZ version: (2.12.06 )
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? Yes, aeotec z-wave

## Additional context

I can't seem to read these clusters:
![image](https://user-images.githubusercontent.com/13660621/135886169-4ff31a74-11cd-4a7c-9c37-eda4115788dd.png)

**Comment by TheNON75** [comment]
Hi @fribse 
I had a similar issue some weeks ago after a battery swap in one of my symfonisk controller.
I’ve added it at least twice until it started to work.
Can you do some more attempts? (And keep clicking with the knob until it is full read)

**Comment by Mimiix** [comment]
This seems like it's a user question as it's not reproducable and not pointing to code (as explained in #5113).

Please use the forum for this question.

**Comment by fribse** [comment]
I upgraded the firmware to the latest in the USB stick, and after doing that, it works again?

**Comment by TheNON75** [comment]
Dear @fribse 

please consider that this bug report is closed now due to the reasons referred to by Mimiix
I am kindly asking you to use the forum for this question.
Sorry for the inconvenience

**Comment by der-david** [comment]
@fribse If you still have problems using the Symfonisk, maybe my [comment on #3969](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3969#issuecomment-1007008377) can help.

**Comment by fribse** [comment]
No, it's solved, thanks!
