### ISSUE TITLE
Tuya TS0012  Switch (qs-zigbee-s04-2c-l)

### ISSUE THREAD

**Issue by igreg** [dresden-elektronik/deconz-rest-plugin#5347]
## Device

- Product name: qs-zigbee-s04-2c-l (made by Lonsonho)
- Manufacturer: _tz3000_llfaquvp
- Model identifier: TS0012
- Device type :
  - Light
  - Switch (2 Gang, no neutral, wired switch)

The device does not show in the Photoscon app. I used the app to make the node join the cluster; to be able to query the data with the DeCONZ application. There seem to be other manufacturer for this model (TS0012) so perhaps it is just a mapping that's missing somewhere?

## Screenshots

![lonsonho qs-zigbee-s04-2c-l](https://www-file.ifreeq.com/expo/media/QS-Zigbee-S04-2C-L-2.jpg)

![Node Info](https://i.ibb.co/Y8jFGL7/Screenshot-2021-10-05-at-00-05-15.png)

### Basic

![Basic Cluster](https://i.ibb.co/PQpKSS5/Screenshot-2021-10-05-at-00-10-41.png)

### Identify

![Identity Cluster](https://i.ibb.co/Vt06Jbd/Screenshot-2021-10-05-at-00-12-03.png)

### Alarms

n/a

### Device Temperature

n/a

### Groups

![Groups Attributes](https://i.ibb.co/0cDdp29/Screenshot-2021-10-05-at-00-14-41.png)

### Scenes

![Scenes Attributes](https://i.ibb.co/fMG6Pt8/Screenshot-2021-10-05-at-00-13-29.png)

### On/Off

01
![On/Off 01](https://i.ibb.co/gSsYKgC/Screenshot-2021-10-05-at-00-16-01.png)
02
![On/Off 02](https://i.ibb.co/3SbT9J2/Screenshot-2021-10-05-at-00-16-53.png)

**Comment by SwoopX** [comment]
Could you please change the title to something more talkative? 😉

**Comment by Smanar** [comment]
I think it s because your device is an end device and the other a router.
Have you a linux machine with full OS to test code modifications ?

**Comment by igreg** [comment]
I actually have the same exact problem with the 1-gang version of the switch.
 * Product name: 1CH Zigbee Switch Module-L (no neutral line)
 * Manufacturer: _TZ3000_jir4araar
 * Model identifier: TS0011
 * Device type :
     * Light
     * Switch (1 Gang, no neutral, wired switch)

Pretty much the same than above except it does not have the On/Off "Light mode 2"

**Comment by Smanar** [comment]
Ok so first try

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch tuya_switch_7 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

This code just add the manufacture 0x1141 in whitelist to permit "light" device creation for end device.

**Comment by blazejpawlak** [comment]
Is anyone planning on adding this switch to supported ones in the upcoming release?

**Comment by Smanar** [comment]
Nop, have not found someone to test the last change, and ATM adding new device using c++ code is disabled, waiting for DDF core.

**Comment by blazejpawlak** [comment]
I can do that. Is [this](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5347#issuecomment-936747855) enough to complete it?

**Comment by Smanar** [comment]
If you have a recent deconz version I can help you to make a DDF file to use this device (I think the core is advanced enought for this kind of device).

The problem is ATM all new device addition are blocked, to not add code that will be removed when ddf will be ready. So even If I finish the PR, not sure it will be validated.

**Comment by blazejpawlak** [comment]
That would be great. I'm running deconz v2.12.06 / 8/19/2021 with firmware 26680700. 

About adding the device to a releasable version — is it because some major deconz overhaul is coming?

**Comment by Smanar** [comment]
>About adding the device to a releasable version — is it because some major deconz overhaul is coming?

Yes https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/

Are you able to update your deconz version to the lasted beta to test DDF file ? (V v2.13.2)

**Comment by blazejpawlak** [comment]
I'll have to make a clone of my RPi's sdcard and try. Soonest I can try is after the 20th Dec. I'll keep you posted.

**Comment by koenheemskerk** [comment]
Have you made progress?

**Comment by blazejpawlak** [comment]
I can confirm that this switch now works with deconz in version 2.20.01 / 9/19/2022 with Conbee II running firmware in version 26780700.

One funny thing though, when I press both buttons of the physical "dumb" switch connected to this device via L1 and L2 only one of them turns on connected to L2. When I press only one switch (connected to either L1 or L2) and then another one both lights come up. 
So if I press both buttons of the switch (connected to L1 and L2), only L2 light comes up. Individually (pressing one button of the switch, waiting a second, then pressing the other button) both lights come up.

Ideas?

**Comment by Smanar** [comment]
Yep, an other issue was created here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6325

For your issue IDK, have made a search on z2m, it don't seem this device have something special (a tuya unlock sequence for exemple)
