### ISSUE TITLE
2.13.00 smart plugs changed display name in deCONZ-gui

### ISSUE THREAD

**Issue by ACrazyConcept** [dresden-elektronik/deconz-rest-plugin#5354]
## Describe the bug

I updated to 2.13.00 and now all my smart plugs, most of them are Innr SP120, changed the name in deCONZ gui.
Phoscon displays the correct names. I can also correct the names in Phoscon and it will reflect the change in deCONZ.

## Screenshots

![image](https://user-images.githubusercontent.com/36438756/136450835-9b71d921-ae27-4d72-8494-4b8fb29827f4.png)

## Environment

 - Host system: Raspberry Pi 4 Model B Rev 1.2
 - Running method: Official Phoscon image
 - Firmware version: 26720700
 - deCONZ version: 2.13.00
 - Device: ConBee II
 - Do you use an USB extension cable: 5 meter active USB extension.
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
This is probably due to the new DDFs.

**Comment by canedje** [comment]
After update to 2.13.1 still wrong names:
![image](https://user-images.githubusercontent.com/23150947/137000314-9f143e3f-1286-41b4-baa6-ae74e6061c3d.png)

**Comment by canedje** [comment]
I don't know if I did this the right way.
I did make this json file and added it into my docker appdata directory like:
![image](https://user-images.githubusercontent.com/23150947/137140696-36ee4b73-80f7-48f8-8f7b-1ef495124cc2.png)

Not giving the right solution. Names still wrong

**Comment by bastshoes** [comment]
Created file inside docker container on following path /usr/share/deCONZ/devices/generic/subdevices/smart_plug.json.
Proper names returned.

**Comment by manup** [comment]
Fixed a while ago via DDF order capabilities.
