### ISSUE TITLE
Add support for power monitoring _TZ3000_dpo1ysak Tuya/Zigbee powerplug

### ISSUE THREAD

**Issue by GitHubxtsnl** [dresden-elektronik/deconz-rest-plugin#5356]
## Device

- Product name: Unknown (from AliExpress)
- Manufacturer: _TZ3000_dpo1ysak
- Model identifier: TS011F
- Device type :  Switch

## Screenshots

![deconz attributes](https://user-images.githubusercontent.com/43134674/136540964-d32865a1-c56c-4932-914d-ce86bf0d3e20.PNG)

![deconz node info](https://user-images.githubusercontent.com/43134674/136540998-61a48d4c-6167-4228-92ab-83fb9012cb8a.PNG)

![ha powerplug not working](https://user-images.githubusercontent.com/43134674/136541145-cc4f73ef-ad09-442c-aafc-f83e5756687b.PNG)

![image](https://user-images.githubusercontent.com/43134674/136541632-c90c253b-0ffb-4d7a-a843-11ef72bd240d.png)

![image](https://user-images.githubusercontent.com/43134674/136541821-c48b964c-d1ed-41ba-80c9-d00679f5ddcb.png)

### Basic
running HomeAssistant 2021.10.1 on a Pi4 with deCONZ 6.10.0 and ConBeeII version 2.12.06 / 8/19/2021 and firmware 26660700

**Comment by Smanar** [comment]
It can perhaps be solved by this PR if you can make a try
It's a generic method for all TS011F

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5206
