### ISSUE TITLE
WZ1 2CH LED Controller

### ISSUE THREAD

**Issue by bastshoes** [dresden-elektronik/deconz-rest-plugin#5357]
## Device

- Product name: WZ1 ZigBee 2CH LED Controller.
- Manufacturer: Unknown.
- Model identifier: TS0601.
- Device type : Please remove all unrelated device types. 
  - Other:  2CH LED Controller (has two modes DIM (manufacture name: _TZE200_6qoazbre)  or CCT (manufacture name: _TZE200_gz3n0tzf))
  

## Screenshots

![image](https://user-images.githubusercontent.com/22978694/136576445-d6acb610-85bd-4a92-ad87-b94c9a223aa2.png)

### Basic
![image](https://user-images.githubusercontent.com/22978694/136576618-e99765e3-bbc1-4497-ad4d-2de2e91a90c2.png)
### Groups
![image](https://user-images.githubusercontent.com/22978694/136576746-fdd820b6-6bce-4704-92b5-7ddbb8b2b7f2.png)
### Scenes
![image](https://user-images.githubusercontent.com/22978694/136576897-d1582e11-a4dc-4ad0-a660-14f73c18b6f9.png)
### OTAU
![image](https://user-images.githubusercontent.com/22978694/136577029-8fc7e34b-4edc-4d16-a4cc-6a4c29cd3957.png)
### Time
No endpoints
### Tuya Specific cluster
No endpoints
### Comments
Device recognized in CCT mode as smart plug and can be turned off or on

**Comment by bastshoes** [comment]
Keeping active

**Comment by bastshoes** [comment]
Keeping active

**Comment by bastshoes** [comment]
Keeping active

**Comment by Mimiix** [comment]
This shouldbe doable with a DDF i think.

Is this a remote (something with buttons?)?

**Comment by bastshoes** [comment]
No, this is LED driver. Button only for pairing and config.

**Comment by Mimiix** [comment]
then a DDF would be able to fix this

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by bastshoes** [comment]
It's a TUYA device and it has this special tuya cluster. I don't have great js skills to decode it.

**Comment by Mimiix** [comment]
Aah. That complicates it.

@Smanar Can you help here or do we need tuya stuff in ddf?

**Comment by bastshoes** [comment]
Keeping active
