### ISSUE TITLE
Casa.ia Single relay VDC (CSAC-451-DC)

### ISSUE THREAD

**Issue by ksskogva** [dresden-elektronik/deconz-rest-plugin#5369]
## Device

- Product name: The device name as shown on the product or package. --> Single Relay VDC
- Manufacturer: As per deCONZ GUI Basic cluster. --> CASA.IA
- Model identifier: As per deCONZ GUI Basic cluster. --> CSAC-451-DC. (On product it says CSAC-451-WTC)
- Device type : Please remove all unrelated device types.  
  - Switch

### Node info panel
<img width="378" alt="Node Info" src="https://user-images.githubusercontent.com/77076198/137095946-d425555a-9358-42ed-85f6-1de4394b24be.png">
### Basic
<img width="379" alt="Basic Cluster" src="https://user-images.githubusercontent.com/77076198/137095994-935692ba-4ed6-4043-819a-4f57a8b17131.png">
### Identify
<img width="381" alt="Identify Cluster" src="https://user-images.githubusercontent.com/77076198/137096032-b49663d0-030a-4102-adf7-84037b2cb70a.png">
### Groups
<img width="379" alt="Groups Cluster 1:2" src="https://user-images.githubusercontent.com/77076198/137096126-98b9eff7-54d1-4d5c-93cd-ac6094d1bbcf.png">
<img width="382" alt="Groups Cluster 2:2" src="https://user-images.githubusercontent.com/77076198/137096175-7bdf47fc-7a51-4cbe-a26e-3dc82cde6333.png">
### Scenes
<img width="339" alt="Scences Cluster 1:3" src="https://user-images.githubusercontent.com/77076198/137096233-abfb1611-99ad-4802-a314-45d84b9332d3.png">
<img width="381" alt="Scenes Cluster 2:3" src="https://user-images.githubusercontent.com/77076198/137096304-70c819ae-bfc8-4714-8847-4bf67632a368.png">
<img width="379" alt="Scenes Cluster 3:3" src="https://user-images.githubusercontent.com/77076198/137096330-6267e2ac-93e6-4810-aa5f-521b3a173307.png">
### On/Off
<img width="382" alt="On:Off Cluster 1:2" src="https://user-images.githubusercontent.com/77076198/137096399-88d92f2c-8671-4edf-ab3a-c50467bc5f68.png">
<img width="376" alt="On:Off Cluster 2:2" src="https://user-images.githubusercontent.com/77076198/137096423-4c896435-0807-4e44-92e6-72fdca34af3b.png">
### Other clusters that are not mentioned above

<img width="404" alt="Overview" src="https://user-images.githubusercontent.com/77076198/137096475-119cd830-ae2a-4b32-a565-21df49483c8a.png">

Product page:
https://casaia.fr/product/module-relais-contact-sec-zigbee/
Pictures of product:
![Dos du produit](https://user-images.githubusercontent.com/77076198/137096895-2cad1600-17f7-4561-be24-f51e816f5d2f.jpg)
![Boite](https://user-images.githubusercontent.com/77076198/137096925-5a865376-8428-4ade-ad9e-db7bacf81f13.jpg)

**Comment by ksskogva** [comment]
Hi again,
Just to check if you have had any time to look at this request?
If there is some missing information or blocking points please let me know and I will try to help.

Regards,
Kristian

**Comment by ksskogva** [comment]
Hi again,

I understand that there are some difficulties keeping up with device implementation related to DDF etc. (Having read forum posts)
Just posting here to avoid getting the issue closed and forgotten.
Still available if you need anything from me to help accelerate the implentation / verification.

Regards,
Kristian

**Comment by ksskogva** [comment]
Hi again,

I understand that there are some difficulties keeping up with device implementation related to DDF etc. (Having read forum posts)
Just posting here to avoid getting the issue closed and forgotten.
Still available if you need anything from me to help accelerate the implentation / verification.

Regards,
Kristian

**Comment by ksskogva** [comment]
Could this be done with DDF you think? To me it is a standard "On/Off Output" device right?
If you think so, I will start to investigate for a DDF file.

Thanks,
Kristian

**Comment by ksskogva** [comment]
Keeping this alive.
Also interested in any response from anyone having some knowledge about this (Ref my questions in previous post)

Thanks in advance!

**Comment by ksskogva** [comment]
Hi again,
I still have got no feedback on any of my posts on this thread. Can you re-open the issue please? I understand that you have a lot on your plate, so no worries, I just don't want the request to be closed and forgotten as I still have the need.

**Comment by ksskogva** [comment]
Thank you @Smanar for the feedback!
I will try this out asap and get back to you.
Fyi it is 1 single relay yes.

Kristian

**Comment by ksskogva** [comment]
Hi again @Smanar.
I did as you say, and I have successfully gotten this device paired now. You were right, the cluster used by default is 0x0006.
Can you explain to me now how I can get the return state please?

Thank you so much for your help so far, it was way easier than I thought!

Kristian

**Comment by Smanar** [comment]
Yeah, users are affraid, but the editor is realy intuitive, just need some zigbee knowledge.
You can too copy/paste the DDF to see where you are ATM.

But If I m right, the return is working when you read the attribute 0x0000 in the cluster 0x0006, every time you read it , it update the value.
If yes you just miss the bind and the report. The bind is to "link" a cluster/attribute from the device to other thing (here the gateway) and the reporting is the report setting

Second tab https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel
- drag and drop the cluster 0x0006 on the left panel
- drag and drop the attribute 0x0000 on the right panel
- configure the reporting with thoses values (was the standards one, can use other)
```
min 1
max 300
```

Min is the minimum delay without reporting
Max if the maximum delay without reporting

**Comment by ksskogva** [comment]
Hmm,
When accessing deconz ui through home assistant os I can't figure out how I can have multiple windows open side by side... At the moment each window opens in full screen. (DDF Editor and Main screen)
If I have understood correctly I would need to drag the cluster/attribute from main screen over to the DDF editor bindings pane right?
Currently stuck at this point.

**Comment by ksskogva** [comment]
DDF file at the moment:

  - type: custom:slider-entity-row
    entity: light.living_room
    name: Salle à manger
    toggle: true

**Comment by Smanar** [comment]
Yep, you have a video too on the link.

- drag and drop the cluster 0x0006 on the left panel > drag an drop the blue number 0x0006 (on the main screen) on the left panel (on the ddf editor)
- drag and drop the attribute 0x0000 on the right panel > drag and drop the 0x0000 number on the attribute panel, that appear when you select the cluster 0x0006 (on the main screen, tab cluster information)
