### ISSUE TITLE
since 2.05.20 deconz stops working after some hours on my x64 box

### ISSUE THREAD

**Issue by holli73** [dresden-elektronik/deconz-rest-plugin#537]
hello,

since the latest release i put in place the deconz stops working and can not be killed!
that leads into a complete system reboot on my host (hosting lots of VM's,...)

```
holli@obelix:~/BUILD/deconz$ ps -ef|grep deC
holli    22375  7157  0 07:38 pts/0    00:00:00 grep --color=auto deC
holli    30906     1  2 Apr13 ?        00:15:24 deCONZ --auto-connect=1 --dbg-error=1 --http-port=8080 --ws-port=20877 --upnp=0 --pid-file=/run/user/1000/deconz/deconz.pid
holli@obelix:~/BUILD/deconz$ sudo kill -9 30906
holli@obelix:~/BUILD/deconz$ ps -ef|grep deC
holli    22872  7157  0 07:40 pts/0    00:00:00 grep --color=auto deC
holli    30906     1  2 Apr13 ?        00:15:24 deCONZ --auto-connect=1 --dbg-error=1 --http-port=8080 --ws-port=20877 --upnp=0 --pid-file=/run/user/1000/deconz/deconz.pid
holli@obelix:~/BUILD/deconz$
holli@obelix:~/BUILD/deconz$ sudo strace -p 30906
strace: Process 30906 attached

```

i have the same version on my raspbee working without issue - it looks like only the x64 is effected.
any idea?

thanks
holli

**Comment by manup** [comment]
Hi Holli,

the next version should help on this problem, I've integrated a device watchdog so that the ConBee can be restarted from deCONZ GUI, and also does that if deCONZ detects something isn't working for several minutes.
