### ISSUE TITLE
essentials Smart Home Heizkörperthermostat 

### ISSUE THREAD

**Issue by r4nc0r** [dresden-elektronik/deconz-rest-plugin#5370]
Hi,

I found this cheap thermostat and it would be really great if deconz would support it, the Premium is already [supported](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3381),):
https://www.wesmartify.de/heizung/heizkoerperradiator/333/essentials-smart-home-heizkoerperthermostat/

## Device

- Product name: essentials Smart Home Heizkörperthermostat 
- Manufacturer: _TZE200_i48qyn9s
- Model identifier: TS0601
- Device type : Please remove all unrelated device types. 
  - Thermostat

### Basic
![1](https://user-images.githubusercontent.com/15196129/137169035-f465eed4-ae7f-45a9-aa90-149f4e7de6f6.PNG)
### Time
![2](https://user-images.githubusercontent.com/15196129/137169172-b2f77990-a4c2-4028-8c8b-a0b9a7aedff3.PNG)
### Tuya specific Cluster
![3](https://user-images.githubusercontent.com/15196129/137169181-5d4d5afd-568b-4292-b3be-e7ba86aa2364.PNG)

### Groups
![group1](https://user-images.githubusercontent.com/15196129/137171397-ad29206a-f0a8-4120-aab4-8b12c1ae3f00.PNG)

![group2](https://user-images.githubusercontent.com/15196129/137171446-13b267d2-70dd-4b9d-8e04-41910588cc45.PNG)
### Scenes
![scenes](https://user-images.githubusercontent.com/15196129/137171498-986e93e8-bff2-4c05-97dd-04e8065fa244.PNG)
![scenes2](https://user-images.githubusercontent.com/15196129/137171501-763a0f82-c25e-4a93-b20f-47849e33e69e.PNG)
![scenes3](https://user-images.githubusercontent.com/15196129/137171506-978cb89c-1ac1-4f21-8c8e-283eb797ea6c.PNG)
![scenes4](https://user-images.githubusercontent.com/15196129/137171515-ce382182-1738-4122-93b9-ae20ae77121b.PNG)

### OTAU
![ota](https://user-images.githubusercontent.com/15196129/137171573-8534a90e-2488-4afc-bf17-3140f3ee2586.PNG)

**Comment by Mimiix** [comment]
@Smanar

**Comment by r4nc0r** [comment]
Any update on this?

**Comment by Smanar** [comment]
Have some problem on the lidl one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5349

**Comment by r4nc0r** [comment]
Ping :)

**Comment by r4nc0r** [comment]
Anything new?

**Comment by Smanar** [comment]
Not realy, all new devices are blocked for the moment, I think we need to wait for tuya cluster integration in DDF core.

**Comment by r4nc0r** [comment]
Can someone reopen this? I still thinks this would be a great addition to deconz, because this is a really cheap and good thermostat.

**Comment by r4nc0r** [comment]
Thanks, can I help in any way?

**Comment by Smanar** [comment]
No, sorry thx for help, we will need it later, but for the moment still waiting for a PR be merged to have a "base"

**Comment by mat-l** [comment]
Hey @Smanar, are there update about the Hama thermostat? 🔥

**Comment by Smanar** [comment]
I think it will be possible soon https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6674
The PR will be in the 2.21.1 version (if no problem) so will be possible to add it using DDF.

**Comment by mat-l** [comment]
Ping ✌🏽

**Comment by Smanar** [comment]
Ha yes its now possible, which one deconz version are you using ?

Can you try this DDF, it's the same used than for the _TZE200_thbr5z34, some dp are same, so probably the whole device ...


```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_i48qyn9s",
  "modelid": "TS0601",
  "vendor": "Tuya",
  "product": "essentials TRV",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "meta": {
        "values": {
          "config/mode": {"auto": 0, "heat": 1, "off": 2}
        }
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {"fn": "tuya", "dpid": 34, "eval": "Item.val = Attr.val * 20;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/heatsetpoint",
          "parse": {"fn": "tuya", "dpid": 16, "eval": "Item.val = Attr.val * 50;"},
          "write": {"fn": "tuya", "dpid": 16, "dt": "0x2b", "eval": "Item.val / 50;"},
          "read": {"fn": "tuya"}
        },
        {
          "name": "config/locked",
          "parse": {"fn": "tuya", "dpid": 30, "eval": "Item.val = Attr.val;"},
          "write": {"fn": "tuya", "dpid": 30, "dt": "0x10", "eval": "Item.val;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/mode",
          "values": [
              ["auto", 0], ["heat", 1], ["off", 2]
          ],
          "parse": {"fn": "tuya", "dpid": 2, "eval": "if (Attr.val == 0) { Item.val = 'auto' } else if (Attr.val == 1) { Item.val = 'heat' } else { Item.val = 'off' }"},
          "write": {"fn": "tuya", "dpid": 2, "dt": "0x30", "eval": "if (Item.val == 'auto') { 0 } else if (Item.val == 'heat') { 1 } else { 2 }"},
          "read": {"fn": "none"}
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 24, "eval": "Item.val = Attr.val * 10;"},
          "read": {"fn": "none"}
        }
      ]
    }
  ]
}
```
