### ISSUE TITLE
v2.13.1 - Invalid password and disappearing device names after install

### ISSUE THREAD

**Issue by jurriaan** [dresden-elektronik/deconz-rest-plugin#5371]
## Describe the bug
Tried to switch to v2.13.1 but I run into a few issues.

In the GUI all device names are gone (I see 0xABCD hex names instead of the actual device names) but lines start to appear between the coordinator and routers, so it seems that there is some sort of connectivity (the logs also indicated this).

Also tried to login to Phoscon, but Phoscon reported incorrect password (and does show a different generic icon), so I couldn't log in.

Switching back to v2.12.6 both issues are gone.

Did something change relating to configuration storage that can cause this issue?

## Steps to reproduce the behavior

1. Make backup
2. Install v2.13.1
3. Observe issue
4. Install v2.12.6
5. Observe that issue is gone and all devices have names again

## Expected behavior

deCONZ continues functioning with all device names kept and password authentication on Phoscon working.

## Screenshots
![image](https://user-images.githubusercontent.com/345809/137173881-20eec1ec-f11b-480d-bb88-1c58846b7847.png)

## Environment

 - Host system: PC
 - Running method: 'Ubuntu' (installed the .deb package)
 - Firmware version: (26700700)
 - deCONZ version: (2.13.1)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs

No weird errors in logs, and it seems to connect fine to the devices. Can provide more details (logs and screenshots) if requested (but won't share all details publicly).

## Additional context

Mixture of all sorts of routers and devices (Xiaomi / IKEA / INNR / Bitron)

**Comment by jurriaan** [comment]
@manup Why isn't this considered a bug report? The latest beta (v2.13.1) doesn't work since it doesn't load the configuration from zll.db on my system. If there's anything I can do to debug the issue please let me know.

**Comment by Mimiix** [comment]
Please continue the discussion on the forums.
