### ISSUE TITLE
SALUS SQ610RF

### ISSUE THREAD

**Issue by alexskra** [dresden-elektronik/deconz-rest-plugin#5372]
## Device

- Product name: SQ610RF (AJSQ610RF)
- Manufacturer: SALUS
- Model identifier: SQ610RF
- Device type: 
  - Thermostat

### Node info
![Node info](https://user-images.githubusercontent.com/5163300/137314108-c9d1ba27-d7b5-4145-8a27-f9e0c36a090e.png)

### Basic
![Basic](https://user-images.githubusercontent.com/5163300/137314139-9c7ae450-7be6-47fd-be24-229fa6170496.png)

### Power Configuration
![Power config](https://user-images.githubusercontent.com/5163300/137314351-9cf3c9ec-bda3-4724-9d85-b2bfaa576975.png)

### Thermostat
![ThermoGUI1](https://user-images.githubusercontent.com/5163300/137315091-ae5c6fb5-b257-4bf9-8e02-b7e4f932bcd6.png)
![ThermoGUI2](https://user-images.githubusercontent.com/5163300/137315097-8c9a1afa-6133-409f-8d5f-9213624c3c3b.png)
![ThermoGUI3](https://user-images.githubusercontent.com/5163300/137315103-9b4b6b7e-b579-45a4-819b-11fdaa593723.png)
![ThermoGUI4](https://user-images.githubusercontent.com/5163300/137315107-4cd86e3a-636e-43d7-83e7-d9f88094ec68.png)

![Thermo1](https://user-images.githubusercontent.com/5163300/137314452-7c1ae2f6-57c4-461e-a5c1-7a933d38c042.png)
![Thermo2](https://user-images.githubusercontent.com/5163300/137314455-b2eecb2f-656e-4bf6-a0bc-67250b7d063a.png)
![Thermo3](https://user-images.githubusercontent.com/5163300/137314461-d4cbf23a-5763-40df-9d80-6149ca35ac37.png)
![Thermo4](https://user-images.githubusercontent.com/5163300/137314464-facd467e-168a-4e89-8aa3-02af4b6aaf9e.png)
![Thermo5](https://user-images.githubusercontent.com/5163300/137314468-49914106-183f-438e-86e6-ab2688d06ae4.png)
![Thermo6](https://user-images.githubusercontent.com/5163300/137314437-c244f8a9-e157-4e8e-acf2-4c3db158958d.png)

### Diagnostics
![Diagnostics](https://user-images.githubusercontent.com/5163300/137314405-401f99a2-35fb-4e45-b7ea-73563cc681cc.png)

**Comment by Mimiix** [comment]
@Smanar something for you?>

**Comment by Smanar** [comment]
IDK.
Not sure DDF can support thermostat, and it seem there is some "specialities" on this device https://github.com/Koenkk/zigbee-herdsman-converters/issues/1524#issuecomment-963996011

A special action suite to make a perfect inclusion, but from the capture it seem @alexskra have done it. Have you tried to send some command using the cluster 0x0201 ? Do you have a recent deconz version that support DDF ?

**Comment by xyz4tech** [comment]
Any update on this?

**Comment by bimusiek** [comment]
Would be amazing to crack it, this is one of the best thermostats in Poland

**Comment by Smanar** [comment]
Can you test id the device need special inclusion or not, with testing directly the device on the Cluster 0x0201 ?

**Comment by Smanar** [comment]
There is some starting way on z2m issue, but I don't think generic zigbee projects are supporting thoses devices yet.

**Comment by bimusiek** [comment]
I have used now the API of Salus and currently using their gate. If someone is interested, the homebridge plugin is available here: https://github.com/Hernas/homebridge-salus-sq610
