### ISSUE TITLE
Add support for power monitoring deconz _TZ3000_nfnmi125 Zigbee powerplug

### ISSUE THREAD

**Issue by joggs** [dresden-elektronik/deconz-rest-plugin#5373]
## Device

- Product name: sparkle IoT
- Manufacturer: _TZ3000_nfnmi125
- Model identifier: TS011F
- Device type : 
  - Switch  

## Screenshots

![1](https://user-images.githubusercontent.com/308445/137508602-a4be4309-5200-41db-b28b-f434abc5df48.png)
![2](https://user-images.githubusercontent.com/308445/137508967-35f7f9df-2c1d-412e-b11d-78e1b303c340.png)
![3](https://user-images.githubusercontent.com/308445/137508610-f72c9f7f-c671-4fca-8807-bd2bfd814adc.png)

![a](https://user-images.githubusercontent.com/308445/137513621-9b3da0d4-f71e-4957-9020-f2b2d2df1862.png)
![b1](https://user-images.githubusercontent.com/308445/137513624-ed4f7ba8-6767-44e5-a15c-8cdeb9744c38.png)
![b2](https://user-images.githubusercontent.com/308445/137513628-0ac5b72c-cdaf-489a-b130-95ce531125d4.png)
![c1](https://user-images.githubusercontent.com/308445/137513629-ae25371f-ca03-4dd9-8512-20cd0587101c.png)
![c2](https://user-images.githubusercontent.com/308445/137513631-9327d862-c53d-4922-b45e-a6c3167188f8.png)
![c3](https://user-images.githubusercontent.com/308445/137513632-4c20113c-6833-497f-a9b8-18bc1c8ae441.png)
![d1](https://user-images.githubusercontent.com/308445/137513633-840aab5f-3e05-4ee5-845b-4ab778f28d53.png)
![d2](https://user-images.githubusercontent.com/308445/137513634-aad973d2-4d2c-4870-be84-202179f9f186.png)
![E000](https://user-images.githubusercontent.com/308445/137513637-f09deb54-298e-4d79-947d-4dd97afa72fa.png)
![E0001](https://user-images.githubusercontent.com/308445/137513639-d937aaa4-0a90-4d21-a3da-c9056f192fea.png)
![f](https://user-images.githubusercontent.com/308445/137513640-3084ed35-c2e3-4572-ac96-8012548cc5fa.png)

### Basic
Running HomeAssistant 2021.10.1 on VM with deCONZ 6.10.0 and ConBee II version 2.13.01 / 10/6/2021 and firmware 26720700
Switch works, but energy metering is missing

**Comment by Smanar** [comment]
It's s possible the version v2.13.1-beta  solve the issue with this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5206

**Comment by Mimiix** [comment]
> It's s possible the version v2.13.1-beta solve the issue with this PR #5206


I am not sure if this is the same, because there's no electrical measurement cluster.

**Comment by Smanar** [comment]
Nope, sorry, and no one have sniffed it yet to get command.

**Comment by joggs** [comment]
Could i give it a shot? Is there a link to how to do that?

Den lör 30 okt. 2021 09:26Smanar ***@***.***> skrev:

**Comment by Smanar** [comment]
Depend on the sniffer you want to use, for exemple with the cheaper https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

But you need too the official gateway.

**Comment by simie7** [comment]
It's actual for me as well. I use this device with zigbee2mqtt, but there is the same situation, that cluster is unknown. There is [related](https://github.com/Koenkk/zigbee2mqtt/issues/9493) issue, so we could share findings, if any.

**Comment by joggs** [comment]
> It's actual for me as well. I use this device with zigbee2mqtt, but there is the same situation, that cluster is unknown. There is [related](https://github.com/Koenkk/zigbee2mqtt/issues/9493) issue, so we could share findings, if any.

@Smanar It looks like they now can get power info when you read simie7's post above. Is that something you can use to get the power info part working in deconz as well?

**Comment by Smanar** [comment]
IDK on last news I have thoses plugs don't support measurement.
Else if you can find wich one value they use I can make a DDF.
