### ISSUE TITLE
Add Support for LIVARNO LUX FB20-002 Remote Control

### ISSUE THREAD

**Issue by thommycgn** [dresden-elektronik/deconz-rest-plugin#5375]
## Device

- Product name: Livaro Lux FB20-002 remote
- Manufacturer: LIVARNO LUX
- Model identifier: FB20-002, 328031_2001
- Device type : 
  - Remote
- Date: 06/2020

I was using it already with zigbee2mqtt. Now I changed over to deconz and the remote is not supported here. :(
Can you please support it? Maybe you can use this?
https://github.com/Koenkk/zigbee-herdsman-converters/blob/ffc473f3a790dbf950d83791d6b135a3eb267802/devices.js#L15630

## Screenshots

![deCONZ-Home-Assistant](https://user-images.githubusercontent.com/8251797/137567780-d1a60810-1378-4ac8-b548-ee3fedafa84a.jpg)

![FB20-002](https://user-images.githubusercontent.com/8251797/137568039-783e0ce0-a717-44c5-bca6-439eaacaf99e.jpg)

**Comment by frontibit** [comment]
I'm not the origilan owner but here are some more screenshots. Can we reopen the ticket as this Wireless controll is still not supported. I can only read the battery information but no switches are possible.

![image](https://user-images.githubusercontent.com/6206894/157002851-2e7ddb75-5472-459b-99dd-85614837eef7.png)

![image](https://user-images.githubusercontent.com/6206894/157002951-73ffdd82-9417-4021-a88c-d0ce3242c1a8.png)

**Comment by Mimiix** [comment]
@frontibit I'd rather have you create a new request and add all screenshots in there.
