### ISSUE TITLE
Zemismart Tuya Zigbee 6 Gang Wireless Switch Zigbee 3.0 Sticker Battery Power Remote Control

### ISSUE THREAD

**Issue by johncollaros** [dresden-elektronik/deconz-rest-plugin#5379]
## Device

- Product name: ZM-RM02
- Manufacturer: _TZE200_zqtiam4u
- Model identifier: TS0601
- Device type : 
  - Remote

## Screenshots

![Screenshot_20211016_193016](https://user-images.githubusercontent.com/5443190/137581668-6b1bfecb-ee8f-4e75-b73c-99939869d7cf.png)
![image](https://user-images.githubusercontent.com/5443190/137683726-467f0d4f-45b4-40ad-9843-2a4fcc9f7130.png)

### Basic
![Screenshot_20211016_193319](https://user-images.githubusercontent.com/5443190/137581688-1e1a2e9f-14ee-45bb-a2f5-baf1cdb46a5a.png)

### Groups
![Screenshot_20211018_175818](https://user-images.githubusercontent.com/5443190/137683877-72be530f-6997-4076-b5d3-01499fb726fd.png)

### Scenes
![Screenshot_20211018_175757](https://user-images.githubusercontent.com/5443190/137683903-3065b042-4865-4951-b319-57d72caa0109.png)

#### Tuya Specific
![Screenshot_20211018_175836](https://user-images.githubusercontent.com/5443190/137683847-4f4815c5-34f7-483c-a4b3-2b6c401250d9.png)

#### OTAU
![Screenshot_20211018_175911](https://user-images.githubusercontent.com/5443190/137683955-c1463792-4dae-4dff-abb5-427d26fa2c97.png)

Notes:
Each of the 6 buttons supports 3 actions:
1. Single Click
2. Double Click
3. Long Press

**Comment by Mimiix** [comment]
Missing screenshots and forum post

**Comment by Smanar** [comment]
And we need the start of the MAC adress ^^, you can hide the end if you want, but we need the first 6 characters.

**Comment by johncollaros** [comment]
@Smanar  Apologies, I have fixed up the Node Info revealing the first 6 chars of the MAC address.
@Mimiix I added all the screenshots for the clusters (except time). Can you elaborate on forum post required?

**Comment by DavidFFerreira** [comment]
no update on that?

**Comment by Smanar** [comment]
Oups sorry, I m asking if we need to edit c++ code or if we can use DDF file.
I will make something tommorow.

**Comment by Smanar** [comment]
Ok so bad news for the moment.
The new device integration is in stand by for the moment, can only using DDF, but the part for battery switches is not finished yet.

If you realy need it, I can give you a modification to use to compile your own API version, else will be not possible before the version v2.13.3

**Comment by johncollaros** [comment]
Just keeping this open. I know the new device descriptor is coming into being so it will happen at that point. Happy to contribute to creating it. :-)

**Comment by DavidFFerreira** [comment]
up open
