### ISSUE TITLE
Futurehome HAN-Sensor

### ISSUE THREAD

**Issue by infected-sith** [dresden-elektronik/deconz-rest-plugin#5382]
## Device

- Product name: Futurehome HAN-Sensor
- Manufacturer: Futurehome
- Model identifier: HAN-Sensor
- Device type : 
  - Sensor

## Screenshots
![Basic info](https://user-images.githubusercontent.com/5661472/137586665-9c4fb774-5a7e-457a-9e7f-f96c11f70d84.png)

### Basic
![0000-Basic](https://user-images.githubusercontent.com/5661472/137586696-443f8f53-576d-4465-aa0c-43f64407df48.png)

### Identify
![0003-Identify](https://user-images.githubusercontent.com/5661472/137586744-393cf3fc-c9ee-4934-802f-cfe9ad4d1a52.png)

### Temperature Management (0402)
![0402-Temperature-Management](https://user-images.githubusercontent.com/5661472/137586768-4c1a9dc5-4e63-42ce-a5d5-9b9e11d092ea.png)

### Simple Metering
![0702-Simple-Metering](https://user-images.githubusercontent.com/5661472/137586775-02dedfbe-66d9-44aa-bcc2-844ab8331437.png)

### Diagnostics
![FEED-Datek-diagnostics](https://user-images.githubusercontent.com/5661472/137586786-c2dc4d48-5964-4791-8f33-379f3e8a70c9.png)

### Electrical Measurement (0B04)
![0B04-Electrical-Measurement](https://user-images.githubusercontent.com/5661472/137586809-45720b4c-9887-4572-a6ba-7c7d547cc9e1.png)

**Comment by infected-sith** [comment]
bump

**Comment by sliann** [comment]
Would be great if this could be added :)
