### ISSUE TITLE
Zigbee Smart Thermostatic Radiator Valve

### ISSUE THREAD

**Issue by laurius** [dresden-elektronik/deconz-rest-plugin#5401]
## Device

- Product name: Zigbee Smart Thermostatic Radiator Valve
- Manufacturer: _TZE200_a4bpgplm
- Model identifier: TS0601
- Device type : Please remove all unrelated device types. 
  - Thermostat

## Screenshots

![](https://user-images.githubusercontent.com/35629808/138148080-94e43225-e6d5-4a36-a52a-26a5d858261b.png)
![](https://user-images.githubusercontent.com/35629808/138147956-14aaf21d-e013-442c-981b-29e8218b33fa.png)
![](https://user-images.githubusercontent.com/35629808/138147998-8e6ef048-9b60-4ede-ad15-0e7f586ac831.png)

**Comment by laurius** [comment]
sorry didn't see how to view the other clusters

### Basic
![image](https://user-images.githubusercontent.com/35629808/138153095-823178d3-2c19-442b-8cd6-d9442d846cfb.png)


### Identify

### Alarms

### Device Temperature

### Groups
![image](https://user-images.githubusercontent.com/35629808/138152121-9162bf56-7b0e-4df0-9b72-a21610649f41.png)
![image](https://user-images.githubusercontent.com/35629808/138152192-9396a27a-6252-41cd-a64e-bc89947c7e38.png)

### Scenes
![image](https://user-images.githubusercontent.com/35629808/138152251-5a8fa24b-a92e-485f-9525-50e4da4ccce3.png)
![image](https://user-images.githubusercontent.com/35629808/138152371-91883f2a-e6b0-4675-9856-246458bbb519.png)
![image](https://user-images.githubusercontent.com/35629808/138152473-5d594bf5-a99a-4ad5-8c5d-2fc8ca0b80fc.png)
![image](https://user-images.githubusercontent.com/35629808/138152550-6d587a19-5ba5-4130-a3fe-7b0422cd36ae.png)


### On/Off

### Level Control

### Color Control

### Simple Metering

### Diagnostics

### Other clusters that are not mentioned above
Tuya Specific:
![image](https://user-images.githubusercontent.com/35629808/138152672-f6d71a01-ba2b-4ba0-9bc2-937cff1e50a9.png)

OTAU:
![image](https://user-images.githubusercontent.com/35629808/138152753-acd9ef28-8b24-4086-9cbd-49f5ff4a3ae3.png)

**Comment by johnthackers** [comment]
Is this for the Tuya TRV ?

**Comment by csteinmueller** [comment]
Is there any way to recycle this request?

**Comment by Mimiix** [comment]
reopened :)

**Comment by laurius** [comment]
I don't know if this helps, but there is a request for the same TRV on ZHA that has many things working:
https://github.com/zigpy/zha-device-handlers/issues/1159

If there is anything to test with the actual device let me know :)

**Comment by OhneSchuhe** [comment]
Hey all, any way of this getting traction again?

I recently bought [the same devices from Salcar](https://www.amazon.de/SALCAR-Heizk%C3%B6rperthermostat-OLED-Display-Programmierbarem-Thermostat/dp/B09BMYF2WC).

- Product name: SALCAR Smart Home TRV602
- Manufacturer: _TZE200_zltyspqw
- Model identifier: TS0601
- Device type : 
  - Thermostat

I found some minor differences regarding manufacturer Name.

###Node
![image](https://user-images.githubusercontent.com/50061610/204392447-91d0ba6a-7951-4ac1-b9da-0f5ee7bb8733.png)


###Node Info
![image](https://user-images.githubusercontent.com/50061610/204392416-3965e6e8-2592-42ca-b5ea-7e1cf557abf8.png)


### Basic
![image](https://user-images.githubusercontent.com/50061610/204390826-fa0796e1-3000-46b8-ab90-8058929d8913.png)

### Groups
Same as pictured above.

![image](https://user-images.githubusercontent.com/50061610/204391729-18468c9d-b866-4119-8978-b846745b9ad8.png)

![image](https://user-images.githubusercontent.com/50061610/204391719-ed902f39-5358-4ef2-97b7-cf4e2e1bc6fb.png)

### Scenes
Same as pictured above.
![image](https://user-images.githubusercontent.com/50061610/204391856-7627c1f1-3de9-4196-b9e9-1384c5d4d3e3.png)

![image](https://user-images.githubusercontent.com/50061610/204391841-81a8c356-a82e-4bf6-ae0b-89b6fc0ec5d3.png)

![image](https://user-images.githubusercontent.com/50061610/204391826-d750a6b8-117a-4f1a-90bd-be72acefefed.png)

### Other clusters that are not mentioned above

##Tuya Specific
Same as pictured above.
![image](https://user-images.githubusercontent.com/50061610/204392171-3397d67b-420d-4d6b-9bf5-aba324b621f7.png)

##OTAU
Same as pictured above.
![image](https://user-images.githubusercontent.com/50061610/204392320-369c3a3a-e46f-4f25-b62b-5b724f4c8324.png)


If you need further info just hit me up and I shall provide what I can.

Thanks in advance.

**Comment by Mimiix** [comment]
> Hey all, any way of this getting traction again?
> 
> I recently bought [the same devices from Salcar](https://www.amazon.de/SALCAR-Heizk%C3%B6rperthermostat-OLED-Display-Programmierbarem-Thermostat/dp/B09BMYF2WC).
> 
> * Product name: SALCAR Smart Home TRV602
> * Manufacturer: _TZE200_zltyspqw
> * Model identifier: TS0601
> * Device type :
>   
>   * Thermostat
> 
> I found some minor differences regarding manufacturer Name.
> 
> ### Node
> ![image](https://user-images.githubusercontent.com/50061610/204392447-91d0ba6a-7951-4ac1-b9da-0f5ee7bb8733.png)
> 
> ### Node Info
> ![image](https://user-images.githubusercontent.com/50061610/204392416-3965e6e8-2592-42ca-b5ea-7e1cf557abf8.png)
> 
> ### Basic
> ![image](https://user-images.githubusercontent.com/50061610/204390826-fa0796e1-3000-46b8-ab90-8058929d8913.png)
> 
> ### Groups
> Same as pictured above.
> 
> ![image](https://user-images.githubusercontent.com/50061610/204391729-18468c9d-b866-4119-8978-b846745b9ad8.png)
> 
> ![image](https://user-images.githubusercontent.com/50061610/204391719-ed902f39-5358-4ef2-97b7-cf4e2e1bc6fb.png)
> 
> ### Scenes
> Same as pictured above. ![image](https://user-images.githubusercontent.com/50061610/204391856-7627c1f1-3de9-4196-b9e9-1384c5d4d3e3.png)
> 
> ![image](https://user-images.githubusercontent.com/50061610/204391841-81a8c356-a82e-4bf6-ae0b-89b6fc0ec5d3.png)
> 
> ![image](https://user-images.githubusercontent.com/50061610/204391826-d750a6b8-117a-4f1a-90bd-be72acefefed.png)
> 
> ### Other clusters that are not mentioned above
> ## Tuya Specific
> Same as pictured above. ![image](https://user-images.githubusercontent.com/50061610/204392171-3397d67b-420d-4d6b-9bf5-aba324b621f7.png)
> 
> ## OTAU
> Same as pictured above. ![image](https://user-images.githubusercontent.com/50061610/204392320-369c3a3a-e46f-4f25-b62b-5b724f4c8324.png)
> 
> If you need further info just hit me up and I shall provide what I can.
> 
> Thanks in advance.

Hi,

Please open an new request.

**Comment by OhneSchuhe** [comment]
Ah alright I thought to try here first. Thanks.

**Comment by e9henrik** [comment]
I'm also struggling with getting this device up and running. Could it be made to work with the other _TSE_200_* DDF-files?
