### ISSUE TITLE
Tuya ZigBee 3.0 Signal Repeater USB Extender

### ISSUE THREAD

**Issue by sajikur** [dresden-elektronik/deconz-rest-plugin#5408]
## Tuya ZigBee 3.0 Signal Repeater USB Extender

- Product name: Tuya ZigBee 3.0 Signal Repeater USB Extender for Smart Life ZigBee Devices Sensors Expand 20-30M Smart Home Automation Module
- Manufacturer: Tuya
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : 

  - Other: zigbee repeater

## Screenshots

![6](https://user-images.githubusercontent.com/6140894/138410079-6ac6ecc0-d453-41a4-9e60-8835c2715533.jpg)

### Basic
![1](https://user-images.githubusercontent.com/6140894/138410084-23e75f02-7101-48db-9bd7-a4c5a7819ea0.jpg)
### Identify
![3](https://user-images.githubusercontent.com/6140894/138410089-ffe37ff4-6992-4ba0-8ada-3676ee72162c.jpg)
### Other clusters that are not mentioned above
![2](https://user-images.githubusercontent.com/6140894/138410086-5670b12f-802f-4a5f-a47c-8084b7bd6e98.jpg)

![4](https://user-images.githubusercontent.com/6140894/138410093-0da64093-7e7e-4e0b-a093-a1dbaeb8506f.jpg)

![5](https://user-images.githubusercontent.com/6140894/138410097-3fe8ee48-d0fd-4554-a42b-9515a3420d2a.jpg)

**Comment by sajikur** [comment]
> 
> 
> ## Tuya ZigBee 3.0 Signal Repeater USB Extender
> 
> - Product name: Tuya ZigBee 3.0 Signal Repeater USB Extender for Smart Life ZigBee Devices Sensors Expand 20-30M Smart Home Automation Module
> - Manufacturer: Tuya
> - Model identifier: As per deCONZ GUI Basic cluster.
> - Device type : 
> 
>   - Other: zigbee repeater
> 
> 
> 
> ## Screenshots
> 
> ![6](https://user-images.githubusercontent.com/6140894/138410079-6ac6ecc0-d453-41a4-9e60-8835c2715533.jpg)
> 
> 
> 
> 
> 
> 
> 
> ### Basic
> ![1](https://user-images.githubusercontent.com/6140894/138410084-23e75f02-7101-48db-9bd7-a4c5a7819ea0.jpg)
> ### Identify
> ![3](https://user-images.githubusercontent.com/6140894/138410089-ffe37ff4-6992-4ba0-8ada-3676ee72162c.jpg)
> ### Alarms
> 
> ### Device Temperature
> 
> ### Groups
> 
> ### Scenes
> 
> ### On/Off
> 
> ### Level Control
> 
> ### Color Control
> 
> ### Simple Metering
> 
> ### Diagnostics
> 
> ### Other clusters that are not mentioned above
> ![2](https://user-images.githubusercontent.com/6140894/138410086-5670b12f-802f-4a5f-a47c-8084b7bd6e98.jpg)
> 
> ![4](https://user-images.githubusercontent.com/6140894/138410093-0da64093-7e7e-4e0b-a093-a1dbaeb8506f.jpg)
> 
> ![5](https://user-images.githubusercontent.com/6140894/138410097-3fe8ee48-d0fd-4554-a42b-9515a3420d2a.jpg)

?

**Comment by Smanar** [comment]
Hello can try like this issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5275
