### ISSUE TITLE
Sunricher ZG9092 thermostat

### ISSUE THREAD

**Issue by Maxcrouz73** [dresden-elektronik/deconz-rest-plugin#5409]
Hello all, i want to request adding this sunricher thermostat .

## Device

- Product name: Sunricher ZG9092 thermostat
- Manufacturer: Sunricher
- Model identifier: ZG9092.
- Device type : Thermostat

![Capture d’écran (85)](https://user-images.githubusercontent.com/89992328/138430459-2ab58060-4be9-4d2e-9975-105550995eca.png)

 
 
  - Endpoints and clusters of the node

![Capture d’écran (86)](https://user-images.githubusercontent.com/89992328/138430588-af8dc539-af1c-4656-a081-7d1122e9efc8.png)

  - Node Info panel

![Capture d’écran (87)](https://user-images.githubusercontent.com/89992328/138431479-b4ac29dd-bc7b-4b97-89ad-a25ff815ddbd.png)

![Capture d’écran (88)](https://user-images.githubusercontent.com/89992328/138431494-3065310c-9797-4256-842e-273267739359.png)

Manufacturer Name and Model Identifier are not display here don't know why but i can read this the basic cluster info

### Basic

![Basic](https://user-images.githubusercontent.com/89992328/138432178-4b191a5e-af44-4174-85cb-9ab1a95288ff.png)

### Identify

![identify](https://user-images.githubusercontent.com/89992328/138432285-2dc3866d-5977-4978-9d07-5806e9e6b0b1.png)

### Alarms

![Alarm](https://user-images.githubusercontent.com/89992328/138432411-f06d386f-fea8-48ac-94bb-b5f9d18da806.png)

### Groups

![Group1](https://user-images.githubusercontent.com/89992328/138432617-e0a20449-dfc2-4f22-a1db-dc06d5ec8ddb.png)

![Group2](https://user-images.githubusercontent.com/89992328/138432659-60dd86ce-82b4-4851-aa1f-4cfa923cb787.png)

### Scenes

![Scene1](https://user-images.githubusercontent.com/89992328/138432922-9aefcff2-506e-4682-9f66-c973151110ff.png)

![Scene2](https://user-images.githubusercontent.com/89992328/138432950-67efef5b-8244-43be-af6c-cabd5eba2a43.png)

### Simple Metering
![Simple metering](https://user-images.githubusercontent.com/89992328/138433072-6761fd0e-df39-4542-814e-100f2498cc9f.png)

### Electrical measurement
![Mesure](https://user-images.githubusercontent.com/89992328/138433294-bf99be04-c040-4dcb-aeed-640ebd65fe60.png)
t

### OTA
![OTA](https://user-images.githubusercontent.com/89992328/138433525-40a65930-3a8f-4acb-baaa-b67fd1167c36.png)

Screenshots

**Comment by Maxcrouz73** [comment]
Hello there,

A little up for my request 😁

**Comment by Mimiix** [comment]
You need to keep it open and bump it up :)

**Comment by Maxcrouz73** [comment]
![sunricher8](https://user-images.githubusercontent.com/89992328/149118835-60287964-2cae-4e2e-8a3c-02aa85ba35bb.png)
![sunricher7](https://user-images.githubusercontent.com/89992328/149118846-2ac5fe03-4f35-45e9-b0be-403917cc1487.png)
![sunricher6](https://user-images.githubusercontent.com/89992328/149118851-7e6cb824-ac8b-472c-b6bf-21ff184e0952.png)
![sunricher5](https://user-images.githubusercontent.com/89992328/149118858-6f93c509-24d5-4b3e-a249-a8a44b31a503.png)
![sunricher4](https://user-images.githubusercontent.com/89992328/149118864-c6b3bce7-6aa5-4a38-afca-2012c1f07640.png)
![sunricher3](https://user-images.githubusercontent.com/89992328/149118871-0437fac9-c5f6-4a23-be32-874f23f9c8bd.png)
![sunricher2](https://user-images.githubusercontent.c
![sunricher1](https://user-images.githubusercontent.com/89992328/149118877-8e4dca39-0753-4617-86b9-d361866532ab.png)
om/89992328/149118874-7e3e64f1-6b31-4ad2-929a-5899df26ddbf.png)

**Comment by Maxcrouz73** [comment]
Hello @Mimiix thanks for your help, do i need to add more thinks or reopen the request from scratch ?

**Comment by Mimiix** [comment]
I re-opened

**Comment by janneHalttu** [comment]
Im in need of this too

**Comment by Mimiix** [comment]
Unless this can be done with DDF (@Smanar ?) it's gonna take a while #5733

**Comment by janneHalttu** [comment]
I hope so. I also Contacted Dresden Electronics for this, because we are Conbee resellers

**Comment by Mimiix** [comment]
I would be amazed if that would help. Let me know the outcome :)

**Comment by Maxcrouz73** [comment]
Hi there,

Hope this could be integrated proprely soon…
I have no solutions for climat control in zigbee and this device is really great!


Envoyé de mon iPhone

**Comment by Smanar** [comment]
> Unless this can be done with DDF (@Smanar ?) it's gonna take a while #5733

Can make a try, will be the first DDF for thermostat, but this device is standard and use standard cluster so why not.

Some one here want to make a try with DDF ?
Short description : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
A video : https://www.youtube.com/watch?v=rgTQpOVg8w0

You just need a OS with desktop or VNC stuff.

**Comment by janneHalttu** [comment]
I opened that and thumb went to mouth...

**Comment by janneHalttu** [comment]
![image](https://user-images.githubusercontent.com/93947012/152565706-a011b412-de3f-49a0-988b-9aab3f7c93ff.png)
 Its in GOld mode, but does not show in Phoscon

**Comment by janneHalttu** [comment]
I dont understand this... I edited product DDF, saved FIle, hotloaded, averything... But When I return to main view and open DDF editor again... It empty again.. It does not save changes to device
![image](https://user-images.githubusercontent.com/93947012/152566136-b5b082d3-1c41-4adf-a6c0-053924374941.png)

**Comment by janneHalttu** [comment]
![image](https://user-images.githubusercontent.com/93947012/152566418-fdf86756-15f6-4073-b46c-0ebb71cc63ea.png)

**Comment by janneHalttu** [comment]
My Bindings are also empty, should there be something?
EDIT: I went back to Phoscon and now it appeared there! BUT state, etc all are wrong... how to edit this correct?
![image](https://user-images.githubusercontent.com/93947012/152567488-ea676b26-9519-422f-b50c-d17adab055d1.png)

**Comment by janneHalttu** [comment]
HOW? Its empty when edited, but SOmehow I need to add that data on right to here
![image](https://user-images.githubusercontent.com/93947012/152569570-fe781efb-5b05-4974-8fc7-4244a4921f45.png)

**Comment by Smanar** [comment]
Lol, not so fast ^^.
- Enable DDF , DONE
- Create one for this node, DONE
- Set basic information, DONE
- **Set "gold" status.**
- Create a ZHAthermostat, DONE
- As you have many cluster, use "01" as endpoint where you will see "Auto", for exemple when you select config/endpoint.
- Save the DDF
- On the menu make "Hot Reload"



BTW, why you have a "electrical mesurement cluster" and "simple metring", the device mesure something special ?

**Comment by janneHalttu** [comment]
Lol, not so fast ^^.

Enable DDF , DONE **DONE.**
Create one for this node, DONE **DONE**
Set basic information, DONE **What is this? Just name?**
Set "gold" status. **DONE**
Create a ZHAthermostat, **DONE**
As you have many cluster, use "01" as endpoint where you will see "Auto", for exemple when you select config/endpoint. **You lost me here... I can see 01, What is endpoint? I cannot see "auto"**
Save the DDF (now when you will make "edit DDF", you will see this path in the window title) **That is done**
On the menu make "Hot Reload"
The device will be reconized, but value will be updated in the API only when you read the value using deconz (for exemple when reading all attributes in the cluster 0x0201) **Yes recognized, but no values are showing yet.**
If Yes, it s normal, next step the binding/reporting. **How?**

BTW, why you have a "electrical mesurement cluster" and "simple metring", the device mesure something special ?
**Its electric usage.**

![image](https://user-images.githubusercontent.com/93947012/152586052-513cf922-5ec3-49cf-9760-14b9681b58e9.png)

**Comment by janneHalttu** [comment]
Wanna Teamviewer and do it? =)

**Comment by janneHalttu** [comment]
II found Bindings dropbox. I can drop BASIC to Destination box and BIND. But when I go back to DDF tab, it does not show anything there.
![image](https://user-images.githubusercontent.com/93947012/152588664-0624f26d-07ae-4b2c-885e-9f64d6ac6e20.png)
![image](https://user-images.githubusercontent.com/93947012/152588750-669495a3-9d58-4fc6-8ed5-5476b7f4d747.png)

**Comment by janneHalttu** [comment]
According to guide I should be able to drop items from 01 Insode DFF editor?? Not possible Windows is not supported,
![image](https://user-images.githubusercontent.com/93947012/152589180-a62292bf-fa85-48bb-a22f-7b7afb3fb40a.png)

**Comment by Smanar** [comment]
>Set basic information, DONE What is this? Just name?

It's fine was, the modelid, manufacture name.

>As you have many cluster, use "01" as endpoint where you will see "Auto", for exemple when you select config/endpoint. You lost me here... I can see 01, What is endpoint? I cannot see "auto"

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
The endpoint is the number on the top/right

The code is normally able to detect it, but in reality ... So better to fix it, avoid this kind of
![ep](https://user-images.githubusercontent.com/20152487/152636808-6cceac4f-db74-4768-8801-a01bff495df0.png)
And use instead 0x01 or 01.

> The device will be reconized, but value will be updated in the API only when you read the value using deconz (for exemple when reading all attributes in the cluster 0x0201) Yes recognized, but no values are showing yet.
> If Yes, it s normal, next step the binding/reporting. How?

It mean not ^^. There is something bad, you need first the DDF is able to change values, after setting the bind/report.
Try selecting for exemple config/heatpooint and make a capture pls ?

> BTW, why you have a "electrical mesurement cluster" and "simple metring", the device mesure something special ?
> Its electric usage.

But it's a thermostat ? It's the electric usage of the thermostat itself ?

Will see later, for you will need to drag and drop the cluster 0x0201 to the left panel them the attribute 0x0000 local temperature, 0x0012 the setpoint, and the mode, don't remember the issue.

Can you show the DDF (you have it a third tab) ?

**Comment by janneHalttu** [comment]
Heatsetpoint:
![image](https://user-images.githubusercontent.com/93947012/152654091-0539c28b-2d18-4be5-8186-f12068c51d29.png)

But it's a thermostat ? It's the electric usage of the thermostat itself ? Yes.

Will see later, for you will need to drag and drop the cluster 0x0201 to the left panel them the attribute 0x0000 local temperature, 0x0012 the setpoint, and the mode, don't remember the issue. 

DONE:
![image](https://user-images.githubusercontent.com/93947012/152654233-2741089c-635d-437c-8ac8-9ce8a900e899.png)
What is attribute 0x000 and 0x0012 Cannet see them?

Can you show the DDF (you have it a third tab) ?:
![image](https://user-images.githubusercontent.com/93947012/152654314-61c87529-f244-49da-b799-7d9c5252d897.png)

**Comment by Smanar** [comment]
You have not set the thermostat part.
Not your fault, pre-filled values are not set in the json.

So you will need to do  that for heatsetpoint, mode and temperature.
- where you see "parse" and read" select "zcl", you will have more option
- Fill values
- save DDF
- Hot reload.


Value to use:

**state/temperature**
Cluster 0x201
Attribute 0x0000
endpoint 01

**config/heatsetpoint**
Cluster 0x201
Attribute 0x0000
endpoint 01

**config mode*
Cluster 0x201
Attribute 0x001C
endpoint 01

**Comment by janneHalttu** [comment]
Got this far:
![image](https://user-images.githubusercontent.com/93947012/152685199-dc2b4941-b5d6-460e-a3ec-c342d164ed38.png)

and here:
![image](https://user-images.githubusercontent.com/93947012/152685221-c7c0587b-92f8-4261-b642-fabff791ec2d.png)


But its missing lots of items. It is Floorheater. SO it hase timetable I can edit, automatic heating when set temperature is too low. Manual control ON/OFF.. and yes, because it can handle 3600W floorheatercable, it has electric consumption meter..

ABove is PDF manual that has ALL this and datapoints. Im going here blindly with your guide and so far it has worked! Now rest !

**Comment by janneHalttu** [comment]
Im giving all info here:
![image](https://user-images.githubusercontent.com/93947012/152690782-8b44f5c1-f807-400d-8c7f-c877bfe2751d.png)
![image](https://user-images.githubusercontent.com/93947012/152690798-a9caba52-47e1-44ad-8eca-426f8bf52a81.png)
![image](https://user-images.githubusercontent.com/93947012/152690868-e0fd32f8-23bb-4c7b-bff5-47d1d10c672f.png)
![image](https://user-images.githubusercontent.com/93947012/152690992-f3ff1faa-5d33-426f-8489-00212652da44.png)
![image](https://user-images.githubusercontent.com/93947012/152691010-43d00d02-f47e-4334-88fa-c672bd7aec3b.png)
![image](https://user-images.githubusercontent.com/93947012/152691026-34a80c55-26ec-4931-a160-87bb913025b0.png)
![image](https://user-images.githubusercontent.com/93947012/152691035-fed8bba1-8f5f-4427-b596-393dfb827883.png)
![image](https://user-images.githubusercontent.com/93947012/152691079-794fc496-14be-486f-bb01-2da284223966.png)

**Comment by janneHalttu** [comment]
To make this Zigbee Thermostat, it should have at least:
- Current Temperature
- Set Temperature
- Heating ON/OFF
- energy consumption

What else is usually? Zigbee access to heater schedule?

**Comment by Smanar** [comment]
The thermostat cluster is not the 0x0204 but the 0x0201
Current Temperature is working I can see it in the capture on phoscon
Set Temperature and Heating ON/OFF, need to work too with the last changes.

Try to read values on the cluster 0x0201 to be sure there are updated in the api, then you can read them in phoscon / help / api information / sensor / (13 ??? )

If you still have nothing can you show the DDF ?

**Comment by janneHalttu** [comment]
The thermostat cluster is not the 0x0204 but the 0x0201 **I cannot find 0x0204 anywhere ??**

Current Temperature is working I can see it in the capture on phoscon **Yes, that is good.**

Set Temperature and Heating ON/OFF, need to work too with the last changes.

Try to read values on the cluster 0x0201 to be sure there are updated in the api, then you can read them in phoscon / help / api information / sensor / (13 ??? ) **I have read values, and added to Lovelace. But Heater or OFF buttons does not work.**

If you still have nothing can you show the DDF ? **I have no Idea how to get that file from inside my Qnap VM that is running this.** It wont allow me to even copy/paste this text... I mean I can select it, but If i open Notepad in my windows, nothing Paste
![image](https://user-images.githubusercontent.com/93947012/152861617-dc5b5232-cf5f-49ca-9acd-37c439ee1d81.png)

**Comment by janneHalttu** [comment]
I can see that file is there, but my Qnap fileexplorer cannot find that directory
![image](https://user-images.githubusercontent.com/93947012/152862630-d1c4dc77-576a-4669-8654-ab7a6b2265a9.png)

**Comment by janneHalttu** [comment]
This looks good, but nothing goes to thermostat from these buttons:
![image](https://user-images.githubusercontent.com/93947012/152863752-5af35aa2-583b-4aa2-8819-80edff043e1d.png)

**Comment by Smanar** [comment]
>I cannot find 0x0204 anywhere ??

You have find it here ^^
![image](https://user-images.githubusercontent.com/93947012/152691010-43d00d02-f47e-4334-88fa-c672bd7aec3b.png)

>I have read values, and added to Lovelace. But Heater or OFF buttons does not work.

Can you show the device json ? To check if the issue is from the API or HA, you can find it in phoscon / help / API information / sensors 

> I have no Idea how to get that file from inside my Qnap VM that is running this.

Yeah I know it s boring on dockers, and I can't help you for that.
But can use picture, I just need the  not working part, like config/heatsetpoint, at 2 place, 1 that look like 

```
          "name": "attr/swversion",
          "awake": true,
          "refresh.interval": 84000,
          "read": {
            "at": "0x8000",
            "cl": "0x0000",
            "ep": 38,
            "fn": "zcl"
```

And the bind part that look like

```
      "bind": "unicast",
      "src.ep": 38,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 600,
          "change": "0x0000000A"
        }
      ]
```

**Comment by janneHalttu** [comment]
Then thermostat IS correct: 
![image](https://user-images.githubusercontent.com/93947012/153052196-f8b85d91-6613-498f-9e08-03e6f57acba6.png)
![image](https://user-images.githubusercontent.com/93947012/153052360-f53c2de5-e306-4ceb-8cf1-3a03417366b7.png)
![image](https://user-images.githubusercontent.com/93947012/153052443-7035e85e-5da3-426f-bcd1-2b4583313123.png)

There is no Bind part ...

**Comment by Smanar** [comment]
>There is no Bind part ...

Ha yes, my bad, I prefer make them in last, when all is working, it mean you are forced to read value in the GUI to update value in the API.

But it work for temperature, so we are not far way the solution.
Try to force the expression to "Item.val = Attr.val", it s the only field you have in bonus for the temperature.

And can you check direclty the device JSON ? Phoscon / help / api information / sensor / (probably 13)

**Comment by janneHalttu** [comment]
From API
{
    "config": {
        "heatsetpoint": 2950,
        "mode": null,
        "offset": 0,
        "on": false,
        "reachable": true
    },
    "etag": "92e68dec362fdc2225788acdbeb704a2",
    "lastannounced": "2022-02-08T14:54:17Z",
    "lastseen": "2022-02-08T14:54Z",
    "manufacturername": "Sunricher",
    "modelid": "ZG9092",
    "name": "Thermostat 13",
    "state": {
        "lastupdated": "2022-02-08T18:38:07.315",
        "on": null,
        "temperature": 2448,
        "valve": null
    },
    "swversion": "6.9.1.0_r4",
    "type": "ZHAThermostat",
    "uniqueid": "1f:ff:00:00:00:00:00:17-01-0201"
}

**Comment by janneHalttu** [comment]
Try to force the expression to "Item.val = Attr.val", it s the only field you have in bonus for the temperature. ??

I do what here?:
![image](https://user-images.githubusercontent.com/93947012/153054364-7d58971a-bf98-4f97-9c64-68c759d22530.png)

**Comment by janneHalttu** [comment]
SO I edit this:
![image](https://user-images.githubusercontent.com/93947012/153054522-3836e2b1-d3a2-4796-a29a-df82bc371ae8.png)

**Comment by Smanar** [comment]
```
"heatsetpoint": 2950,
"mode": null,
```

Set it seem you can set the temperature too.
Only the mode seem missing.

Ok, will se later for the mode can be from the device, can check if the attribute is working in the attribute table for the cluster 0x0201

But now the bind

- Go on the "binding" tab
- Drag the cluster 0x0201 on the left panel
- Drag the attribute (from the same cluster) on the right panel : 0x0000 , 0x0012

Use as value for 0x0012
```
            rq2.minInterval = 1;
            rq2.maxInterval = 600;
            rq2.reportableChange16bit = 50;
```

And for 0x0000
```
            rq.minInterval = 1;
            rq.maxInterval = 600;
            rq.reportableChange16bit = 20;
```

And no for temperature the expression is good
- select config/heatsetpoint
- go on "Expression
- use `Item.val = Attr.val`

**Comment by janneHalttu** [comment]
You mean Drag from RIGHT to left?
![image](https://user-images.githubusercontent.com/93947012/153055415-0c12b120-8577-42b2-b7fb-130961fe9643.png)

This view has nothing to drag...
![image](https://user-images.githubusercontent.com/93947012/153055561-73746b33-b0c4-47ba-937d-43d05ac504e8.png)

**Comment by Mimiix** [comment]
https://forum.phoscon.de/t/ddf-editor-how-to-drag-bindings/1351?u=Mimiix here's someone who had the same issue.

**Comment by janneHalttu** [comment]
Yes. Managed to drad that view.. But it only allows me to drag 0x00000, evertyhing else is RED, not allowed.

**Comment by janneHalttu** [comment]
I think it seems best if I just add those Json lines... aargh.. This software is so 1980... =)

**Comment by janneHalttu** [comment]
You wanna access My HA ? =)

**Comment by Smanar** [comment]
>This software is so 1980... =)

Lol, IDK what happen, I have just made a try with an unknow cluster, and it have worked. The harder part is knowing how work zigbee, but the application is fine for me.

```
    "bindings": [
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0204",
            "report": [
                {"at": "0x0000", "dt": "0x29", "min": 1, "max": 600, "change": "0x14" },
                {"at": "0x0012", "dt": "0x29", "min": 1, "max": 600, "change": "0x32" },
                {"at": "0x001C", "dt": "0x30", "min": 5, "max": 600 }
            ]
        }
    ]
```

You have a sample here https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/philips/sml001_motion_sensor.json

```
0x0001 outdoor temperature: (floor temperature)
0x0011 Occupied cooling temp (current temp)
```

Are you sure thoses temperature are available in the cluster, there are rarely used on deconz for other devices.

**Comment by janneHalttu** [comment]
HI, That is motion sensor. How is that gonna help me?
Should I add that bindings code to my json?

**Comment by Smanar** [comment]
>HI, That is motion sensor. How is that gonna help me?

Was just a sample for synthax, as you can't make copy/paste, I can't correct you if you forget a "," or a "["

>Should I add that bindings code to my json?

Yep, it s binding for the cluster 0x0204 and 3 attributes (from thermostat cluster)

**Comment by Smanar** [comment]
Perhaps https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5459#issuecomment-1019501674 can help you ?

**Comment by janneHalttu** [comment]
I still havent got any help, about how to download and edit DDF in QNap Virtualization Station...

**Comment by janneHalttu** [comment]
Deconz should have "Donwload file" ja "upload" option..

**Comment by Smanar** [comment]
You have a desktop or headless OS on your machine ?

**Comment by janneHalttu** [comment]
I can download VNC too

**Comment by janneHalttu** [comment]
Sorry.. no VNC.. I mixed it with VLC.. HAHA.

**Comment by Smanar** [comment]
Lol.
So you are using the HA docker version, so it's same than others, some users can use a building VNC feature in HA, but I don't know where.
Else can do like the previous link to find the folder and use text editor.

**Comment by janneHalttu** [comment]
Yeah... I alreay posted there.. How to navigate on Command promt. 
In windows: CD "path" or DIR for directories to navigate.. I have no Idea about this operating system...
AND after finding it, how to then download and upload that file to my computer for file editing..

**Comment by Mimiix** [comment]
> Mayde Deconz need an update to edit DDF inside ... Because There isnt any way to find and locate those files..

That's the downside of the HA Addon. You can perfectly edit it on a native deCONZ installation.

**Comment by ebaauw** [comment]
Bump

**Comment by ebaauw** [comment]
Bump
