### ISSUE TITLE
Firmware Raspbee does not work with PI 3b+

### ISSUE THREAD

**Issue by QHose** [dresden-elektronik/deconz-rest-plugin#541]
hi,

I just tested and both the beta as well as the stable [firmware ](https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/raspbee-gw-sd-card-image/) don't work. When I download the image and write it to SD card. the PI flashes 4 times slow 4 times fast.

This raspbian does boot the machine https://www.raspberrypi.org/downloads/raspbian/
But now I can't make use of all the preinstalled software that the dresden image provides, any ideas?

**Comment by QempZor** [comment]
Im also trying to install DeCONZ on my new RPi3b+
However, im also running in some problems.
Able to boot and start DeCONZ, but only showing a Daylight node..

**Comment by willsy555** [comment]
I had the same issue. Only get the daylight node on a rpi3b+ and works on a rpi2. Is 3b+ support expected?

**Comment by jjlawren** [comment]
Is this still the case? I was about to deploy a new RaspBee on a 3B+ but now I’m worried it won’t work.

**Comment by jjlawren** [comment]
Works fine, just need these entries in the `config.txt`:
```
enable_uart=1
dtoverlay=pi3-miniuart-bt
```
I didn't see this in the documentation. Worth adding? And maybe update supported models here: https://www.dresden-elektronik.de/funktechnik/service/support/faq/wireless-light-control/?L=1

**Comment by kallipso** [comment]
Solved  rpi3+
i have the same problem i change  "/dev/ttyAMA0" to "/dev/ttyS0"

**Comment by manup** [comment]
>Solved rpi3+
>i have the same problem i change "/dev/ttyAMA0" to "/dev/ttyS0"

When the serial port is configured as in step 1) it right device will be /dev/ttyS0

https://phoscon.de/raspbee/install#raspbian

Can also be verified with:

    ls -l /dev/serial0

Which should be a symlink poining to `/dev/ttyS0`, before configuration it points to `/dev/ttyAMA0`.
