### ISSUE TITLE
Add support for power monitoring deconz TZ3000_cphmq0q7 Zigbee powerplug

### ISSUE THREAD

**Issue by elpablillo** [dresden-elektronik/deconz-rest-plugin#5427]
## Device

- Product name: VIKEFON
- Manufacturer: _TZ3000_cphmq0q7
- Model identifier: TS011F
- Device type : 
  - Switch

### Node info
![image](https://user-images.githubusercontent.com/68110358/139529877-3589ee01-f348-4216-81ac-0ccaf9c06878.png)

### Basic
![image](https://user-images.githubusercontent.com/68110358/139529952-33bdf426-c933-425a-8b07-27bddb50daa9.png)

### Identify
![image](https://user-images.githubusercontent.com/68110358/139529983-19f06bb3-3590-4ef9-b6ef-c1af33303716.png)

### Groups
![image](https://user-images.githubusercontent.com/68110358/139530017-0080d1c3-0b7e-42fc-89cf-59ba63398c88.png)

### Scenes
![image](https://user-images.githubusercontent.com/68110358/139530068-d9061ccb-7610-4630-8385-6be308a8d575.png)

### On/Off
![image](https://user-images.githubusercontent.com/68110358/139530045-47392a97-0a32-4f75-a387-a4c8346b2a16.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/68110358/139529899-d242286d-859e-444e-8214-3e8bc2e3bb6c.png)

### Electrical Measurement
![image](https://user-images.githubusercontent.com/68110358/139530087-39935810-bae3-4bc9-a2d7-2fee54ae9b36.png)

**Comment by Smanar** [comment]
Same strange cluster than https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5373

**Comment by elpablillo** [comment]
> Same strange cluster than #5373

So, any chance those power measure will appear in HA?

**Comment by Smanar** [comment]
Hu ... I think not ATM sorry.
We are converting legacy code to DDF, so I don't think we will add C++ code to support new cluster for the moment

**Comment by CarmeloSena** [comment]
Do you already know if there is a way to monitor the power of this socket?

**Comment by Smanar** [comment]
No more information on my side.
