### ISSUE TITLE
frient Smart Plug Mini

### ISSUE THREAD

**Issue by juliendragz** [dresden-elektronik/deconz-rest-plugin#5435]
## Device

- Product name: frient Smart Plug Mini
- Manufacturer: frient A/S
- Model identifier: SPLZB-132
- Device type : 
  - Other: smart plug on / off

## Screenshots

![Capture d’écran 2021-11-01 123645](https://user-images.githubusercontent.com/32529250/139674444-dd1141cf-c5da-4587-8aaa-ec3624c70262.png)

### Node Info panel
![Node Info panel 1](https://user-images.githubusercontent.com/32529250/139668639-f29f9eae-b41f-4155-8339-d62d3958c579.png)

### Basic
![basic 1](https://user-images.githubusercontent.com/32529250/139668688-2316b89e-0821-4c84-9ce1-ddd7dd5c81d9.png)
![basic 2](https://user-images.githubusercontent.com/32529250/139668700-15237a77-5df9-4314-bbc2-1dbec5c1873b.png)

### Identify
![Identify](https://user-images.githubusercontent.com/32529250/139668718-6a9e43bb-4174-4cc3-86ff-2e034c0160ca.png)

### Alarms
![Alarms](https://user-images.githubusercontent.com/32529250/139668727-5275ec2e-4d79-4c1d-a89b-6390816f51ca.png)

### Device Temperature
![Device Temperature](https://user-images.githubusercontent.com/32529250/139668737-27aac60d-8121-40b4-8fb9-ae00c228bb77.png)

### Electrical Measurement
![Electrical Measurement 1](https://user-images.githubusercontent.com/32529250/139668745-d389ad56-0c56-4483-8c25-9a80e00d8dbb.png)
![Electrical Measurement 2](https://user-images.githubusercontent.com/32529250/139668754-7bc60783-38aa-4e98-9dfe-41057ebbe852.png)

### On/Off
![on off 1](https://user-images.githubusercontent.com/32529250/139668787-ad6ab38b-b098-4207-9b4c-2de57c7f7762.png)
![on off 2](https://user-images.githubusercontent.com/32529250/139668796-07f2199e-fd74-4dd3-8fe9-534cd51f6ae7.png)

### Simple Metering
![Simple Metering 1](https://user-images.githubusercontent.com/32529250/139668819-ce0c4ea8-e949-4e60-b487-16705a840489.png)
![Simple Metering 2](https://user-images.githubusercontent.com/32529250/139668831-abbc98d2-f035-468d-a06c-5b3441afc9de.png)
![Simple Metering 3](https://user-images.githubusercontent.com/32529250/139668845-8437e527-5f22-4505-a35c-f06ac276e595.png)
![Simple Metering 4](https://user-images.githubusercontent.com/32529250/139668861-31490805-a913-4f76-8223-92070878bd96.png)
![Simple Metering 5](https://user-images.githubusercontent.com/32529250/139668876-80ccf197-0208-45b3-b39f-9923937660ab.png)
![Simple Metering 6](https://user-images.githubusercontent.com/32529250/139668881-3e7008e4-f8aa-431a-bd01-107dd12e3023.png)

## Infos
Hi,
I searched in if the device was not already added I found this model which is added in 2019 which looks like:
https://github.com/dresden-elektronik/deconz-rest-plugin/commit/efae9b2b134f4a5e824b45980baad9135537f606

I also tried to add the device with DDF, by adding the measurement data I have to get this information in the websocket but not in the rest api.
[ddf without edit.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7453367/ddf.without.edit.txt)
Api with ddf edited:
[On_off_smart_plug .txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7453216/On_off_smart_plug.txt)
![rest with ddf](https://user-images.githubusercontent.com/32529250/139674296-2e91d0a8-81c7-48be-81f6-dba993af3703.png)
![websocket with ddf](https://user-images.githubusercontent.com/32529250/139674317-a7a378c5-eab8-46d9-b8f9-404b0ad8114a.png)

And if I understood correctly the use of DDF I cannot activate it when starting deconz? Is it a tool that is used to verify the mapping of the device, to then integrate it into deconz?

**Comment by SwoopX** [comment]
Closing this one as it is already supported and 100% the same like the Develco smart plug (its even the same company).

**Comment by juliendragz** [comment]
My bad, I updated deconz without resetting the device. I convinced myself that it was not necessary 🤦‍♂️. Thank you
