### ISSUE TITLE
Aqara E1 Window And Door Sensor Zigbee 3.0

### ISSUE THREAD

**Issue by MiAutomations** [dresden-elektronik/deconz-rest-plugin#5441]
## Device
- Link : https://s.click.aliexpress.com/e/_ADEWgh
- Product name: Aqara E1 Window And Door Sensor Zigbee 3.0
- Manufacturer: LUMI
- Model identifier: lumi.magnet.acn001
- Device type : 
  - Sensor
 
## Screenshots

![image](https://user-images.githubusercontent.com/47602733/140043985-9b3c2d70-9a79-4ca4-90e4-53577118639a.png)
![image](https://user-images.githubusercontent.com/47602733/140044057-5f2583f9-a042-4d2b-b8eb-7f139a63882e.png)

Thank you

**Comment by SwoopX** [comment]
#5403 

Please use the search before raising duplicate requests.
