### ISSUE TITLE
Tuya Temperature & Humidity Sensor LH-331ZB

### ISSUE THREAD

**Issue by G0sch** [dresden-elektronik/deconz-rest-plugin#5442]
## Device

- Product name: TuYa Temperature & Humidity Sensor LH-331ZB
- Manufacturer: _TYZB01_cbiezpds
- Model identifier: SM0201
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

  - Endpoints and clusters of the node
<img width="532" alt="image" src="https://user-images.githubusercontent.com/51472553/140044367-f3832620-c280-4f75-8f4e-9c5a5f04c7c7.png">

  - Node Info panel
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/51472553/140044421-af010b75-f228-466f-ad67-cb81c9876f6d.png">

**Comment by Mimiix** [comment]
Missing all screens.

never the less, already a request open which got auto-closed:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4823

I'll re-open that one and close this one.
