### ISSUE TITLE
Aqara P1 Door and Window Sensor

### ISSUE THREAD

**Issue by MiAutomations** [dresden-elektronik/deconz-rest-plugin#5443]
## Device
-Link: https://s.click.aliexpress.com/e/_9AzK9T
- Product name: Aqara P1 Door and Window Sensor
- Manufacturer: LUMI
- Model identifier: lumi.magnet.ac01
- Device type :
  - Sensor
 

## Screenshots

![image](https://user-images.githubusercontent.com/47602733/140046180-42b5c4d2-68d8-476c-90ea-70382b2425f6.png)

![image](https://user-images.githubusercontent.com/47602733/140046222-2c990517-4f41-4130-8026-06f8c5a572b6.png)

**Comment by Mimiix** [comment]
Please add all screenshots.

**Comment by MiAutomations** [comment]
Please all the screen shots added Thank you

![image](https://user-images.githubusercontent.com/47602733/140048680-e9b92fb5-f82c-41ce-a128-444f8b92cbfe.png)
![image](https://user-images.githubusercontent.com/47602733/140048694-4457bc1f-b347-46cf-bc27-fcdb86b7f402.png)
![image](https://user-images.githubusercontent.com/47602733/140048729-72bc2fa6-fdc0-496c-b67c-4200eb4ded59.png)
![image](https://user-images.githubusercontent.com/47602733/140048749-b2fce112-e1f8-44ca-bb32-1a9f4e780875.png)

**Comment by SwoopX** [comment]
Sorry to say, but the screenshots are not usable as all the attributes aren't read. Push the physical button and then immediately press the read button.

**Comment by ads1230** [comment]
@SwoopX did my screenshots help?
