### ISSUE TITLE
YPHIX ZIGBEE LED DRIVER 350-1400MA 50W

### ISSUE THREAD

**Issue by megawubs** [dresden-elektronik/deconz-rest-plugin#5446]
## Device

- Product name: YPHIX ZIGBEE LED DRIVER 350-1400MA 50W
- Manufacturer: Philips.
- Model identifier: DIM Lightning.
- Device type : Please remove all unrelated device types. 
  - Light (LED DRIVER)

## Screenshots

 ![image](https://user-images.githubusercontent.com/2302867/140408454-d4235fab-d3fb-4837-9c84-692db0fd0826.png)
![image](https://user-images.githubusercontent.com/2302867/140408522-65347250-eac4-4115-b1c6-9a80cf31edf3.png)

### Basic
![image](https://user-images.githubusercontent.com/2302867/140409285-85d7f730-4a1e-46f8-8ee9-7454a58886aa.png)

### Identify
![image](https://user-images.githubusercontent.com/2302867/140409343-dfdd6d9d-2e37-4956-9535-c00f7abc3356.png)

### Groups
![image](https://user-images.githubusercontent.com/2302867/140409393-4c5ce33c-2bc2-42f2-b329-0dee2389edc4.png)

### Scenes
![image](https://user-images.githubusercontent.com/2302867/140409431-9b8f8597-3434-45b9-a458-36693fff0c54.png)

### On/Off
![image](https://user-images.githubusercontent.com/2302867/140409660-1e9866df-aeb7-4dc2-b715-9764784ce71c.png)

### Level Control
![image](https://user-images.githubusercontent.com/2302867/140409693-33814be8-f7ca-4c89-a84a-6a3c09b5724f.png)

### Color Control
![image](https://user-images.githubusercontent.com/2302867/140409806-26a2dc44-3fac-4e1d-b3ed-300fcb3e8fca.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/2302867/140409889-1e558e73-83a1-4079-91bb-a9b5198d38dd.png)

#### OATU
![image](https://user-images.githubusercontent.com/2302867/140409960-233a9e86-06bd-49b5-ad6b-eb8a3665ca4e.png)

#### Green Power
![image](https://user-images.githubusercontent.com/2302867/140410000-81bc20af-247a-4f7e-b202-982b75edd041.png)

This is my first device request issue. I've tried to do my best and keep to the issue template. Please let me know if something is missing or if more info is needed. Also, if someone is up to it, i would like to know how to add support for this device myself, but have no idea where to start. Some guidance would be nice!

**Comment by Mimiix** [comment]
Looks fine to me :)

What is not working currently? As it seems to be recognized correctly?

**Comment by megawubs** [comment]
I've described the problem here: https://github.com/home-assistant/core/issues/58174#issuecomment-956513886 and was told to open a device request. TLDR: The device reports values it doesn't typically support, causing Home-Assistant to crash and not display the correct device state.

**Comment by megawubs** [comment]
And, since a few weeks this device looses connection randomly.

**Comment by megawubs** [comment]
Is there anyone with more knowledge about the plugin that can look at this? From what I understand the plugin gives back values to Home-Assistant that the device does not support.

**Comment by tomdegoeij** [comment]
@megawubs Were you able to resolve your issues with this device? I'm planning on purchasing a few of those but want to be sure they are supported using Deconz through HA. Thanks!
