### ISSUE TITLE
Tuya ZigBee TM616EGBZTN Pull Bead Curtain Motor

### ISSUE THREAD

**Issue by P2W2** [dresden-elektronik/deconz-rest-plugin#5450]
## Device

- Product name: Tuya ZigBee TM616EGBZTN 
- Manufacturer: _TZE200_gubdgai2
- Model identifier: TS0601
- Device type : Please remove all unrelated device types. 
  - Other: Cover

## Screenshots
![grafik](https://user-images.githubusercontent.com/14575200/140544535-8556864a-230e-445f-8e04-39b2e9f43aa1.png)
![grafik](https://user-images.githubusercontent.com/14575200/140544999-c8599baf-cc56-4130-b99c-5abe6d80519e.png)

### Basic
![grafik](https://user-images.githubusercontent.com/14575200/140545194-be211896-9f66-4bea-a54f-89177e03ee0a.png)
### Groups
![grafik](https://user-images.githubusercontent.com/14575200/140546240-a7bc200d-6ff1-44bd-b4d1-b85d4dcbd8b2.png)

### Scenes
![grafik](https://user-images.githubusercontent.com/14575200/140546342-4192b70a-7eb4-4032-9b38-3e27bffd2ec8.png)

### Tuya Specific clusters:
![grafik](https://user-images.githubusercontent.com/14575200/140545261-25e00653-e45f-4f74-8534-cb3d3c40bf94.png)

### OTAU
![grafik](https://user-images.githubusercontent.com/14575200/140546487-f37dfa6a-b01c-4f48-8fa5-77186d7a96f2.png)

### Time
![grafik](https://user-images.githubusercontent.com/14575200/140547374-5edcb3dd-a13b-4ac2-947f-9d2f6da0aae7.png)

**Comment by P2W2** [comment]
The solution seems to be simple, since it is the same system as the following issues:  
[#5238](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5238) & https://github.com/dresden-elektronik/deconz-rest-plugin/issues?q=is%3Aissue+is%3Aclosed+M515EGB.
@Smanar maybe you can help since you have solved all issues related to curtain motors above?

I tried to solve it myself, but ran into a problem:
If I understood it correctly it is solved by adding following line:
`{"_TZE200_gubdgai2", "TS0601", "Tuya", "Tuya_COVD TM616EGBZTN"},`
to this [file](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/product_match.cpp).

However I tried to implement and test it but I get a `E: Unable to locate package deconz-dev` if I try to `sudo apt install deconz-dev`
I have tried the solutions that are written [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2811), but unfortunately did not work either

**Comment by Smanar** [comment]
Hello, what is your OS ?

You need to switch to beta package https://www.phoscon.de/en/conbee2/install

**Comment by P2W2** [comment]
So I installed the beta package with a new raspbian-buster image and i was able to install the deconz-dev package and build the project. Unfortunately, my above-mentioned change did not bring my hoped-for success. In fact nothing changed at all the device is still a smart plug and not shown in the phoscon app or HA.

**Comment by stevewull** [comment]
I have this cover and am having trouble getting deconz to recognize it properly

The cover is simliar to _TZE200_xuzcvlku. I have three of those. Phoscon displays them as fairy lights. They work for me with no problems.

seems like _TZE200_gubdgai2 is a new rev of their cover. I tried two cycles of adding a new light.


Screenshots:

![image](https://user-images.githubusercontent.com/46251961/185806896-0051440d-3b73-4a25-a7fd-00960c7bd5d8.png)
![image](https://user-images.githubusercontent.com/46251961/185806922-7f0fd2b9-cbe7-41e7-be98-d5e6c5cf580e.png)
![image](https://user-images.githubusercontent.com/46251961/185806957-07c7e96a-17cd-48a0-a92f-47d49f514ae4.png)

**Comment by Smanar** [comment]
Sorry but for the moment it's not possible adding new tuya covering.

**Comment by stevewull** [comment]
Thanks Smanar,  I'll check back later.

**Comment by mdcobra** [comment]
I also have this _TZE200_gubdgai2, but cannot bind it, is this solved?

**Comment by Smanar** [comment]
Nope, sorry, not possible adding tuya covering using DDF.
