### ISSUE TITLE
Tuya thermostat: "Tuya : Schedule data error"

### ISSUE THREAD

**Issue by valpo** [dresden-elektronik/deconz-rest-plugin#5461]
## Describe the bug

Pairing the device starts without problems, but always finishes with the message above: 

> 17:37:21:601                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:21:706 Tuya debug 4 : Address 0x84FD27FFFE2DEB6D Payload 00b17304000101
17:37:21:706 Tuya debug 5 : Status: 0 Transid: 177 Dp: 1139 (0x04,0x73) Fn: 0 Data 1
17:37:21:707 FP indication 0x0104 / 0xEF00 (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:21:708                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:21:852 Tuya debug 1 : Time sync request
17:37:21:854 Send Tuya command 0x24, data: 00986186af416186bd51
17:37:21:855 FP indication 0x0104 / 0xEF00 (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:21:855                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:29:743 DeviceAnnce of SensorNode: 0x84FD27FFFE2DEB6D [1]
17:37:29:748 FP indication 0x0000 / 0x0013 (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:29:749                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:29:749 device announce 0x84FD27FFFE2DEB6D (0x4C2B) mac capabilities 0x80
17:37:29:750 FP indication 0x0000 / 0x0013 (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:29:751                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:29:751 device announce 0x84FD27FFFE2DEB6D (0x4C2B) mac capabilities 0x80
17:37:35:059 FP indication 0x0104 / 0x000A (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:35:060                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
...
17:37:39:502 Tuya debug 4 : Address 0x84FD27FFFE2DEB6D Payload 00a72302000400000064
17:37:39:503 Tuya debug 5 : Status: 0 Transid: 167 Dp: 547 (0x02,0x23) Fn: 0 Data 100
17:37:39:504 FP indication 0x0104 / 0xEF00 (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:39:505                       ...     (0x84FD27FFFE2DEB6D / 0x4C2B)
17:37:39:629 Tuya : Schedule command
17:37:39:630 Tuya debug 4 : Address 0x84FD27FFFE2DEB6D Payload 00a82e030018323032313031303130313031323032313031303130313031
17:37:39:631 Tuya debug 5 : Status: 0 Transid: 168 Dp: 814 (0x03,0x2E) Fn: 0 Data 0
17:37:39:631 Tuya : Schedule data error

The device appears in deCONZ and I am able to add it to openhab, but I am not able to get data from the device or send data to it. In fact the antenna symbol on the device disappears immediately after the error message. 

## Steps to reproduce the behavior

This happens each time I am trying to pair the new device. 

## Screenshots

![Screenshot from 2021-11-07 09-50-46](https://user-images.githubusercontent.com/781378/140638687-077f63ce-73ce-4927-b8c9-22b3b6380851.png)

## Environment

 - Host system: (Raspberry Pi / 
 - Running method: Marthoc Docker container
 - Firmware version: 0x26680700
 - deCONZ version: 2.13.1-beta
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment]
@Smanar

**Comment by Smanar** [comment]
Yep, np.
Was due to a recent change, just mean the device can support schedule command.
The error message is corrected here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5410

But don't mean the schedule will work on the device, still depend of device.
But this message don't block the normal working mode for the device.

>but I am not able to get data from the device or send data to it

It's possible the device is not yet supported, I dont find your model id in the code. Nothing with _TZE200_e9ba97vf

**Comment by valpo** [comment]
So is there something I can do to add support for it? Just wait? Drop it into the trashbin?

**Comment by Smanar** [comment]
IDK, ATM I m already on another TRV (and with some problem)

If your device is just a clone, the modification can be fast (just one line to edit), if it use new command will take more time.
And ATM we can add new device only with DDF, so more complicated for tuya device that don't use standard command.
