### ISSUE TITLE
Danfoss Ally - Can not set negative offset, always results in 0

### ISSUE THREAD

**Issue by tatec22** [dresden-elektronik/deconz-rest-plugin#5462]
## Describe the bug
When setting a negative number for the offset of the Danfoss Ally, the value is accepted but isn't really set. 

## Steps to reproduce the behavior
  1. Set a negative value (e.g. -160) via Home Assistant and "deconz.configure" command
  2. Check Rest Api for correct value -> It is the correct value
  3. Open deconz and read "Regulation SetPoint Offset" (0x404B)
  4. The value read will be 0
  5. Check Rest Api again -> Value will also now be 0

## Expected behavior
It is expected that a negative value can be set via "deconz.configure" and can be read directly via the "Regulation SetPoint Offset" (0x404B)
Manually setting a negative value at "Regulation SetPoint Offset" (0x404B) is working without any problem and the value is reported correctly to the rest api.

## Screenshots
![Screenshot 2021-11-07 133150](https://user-images.githubusercontent.com/73723454/140645002-27d1e10a-3536-4152-87df-6da2370cb532.png)
![Screenshot 2021-11-07 131534](https://user-images.githubusercontent.com/73723454/140644537-e091db62-0653-46da-b7e7-17828c7c449d.png)
![Screenshot 2021-11-07 131558](https://user-images.githubusercontent.com/73723454/140644544-1c1167ee-58a1-44b6-98cc-c4e9bcbd2a02.png)
![Screenshot 2021-11-07 132019](https://user-images.githubusercontent.com/73723454/140644642-2bfcfabd-2ecb-43d8-9ce1-f191ba4c62aa.png)

## Environment
 - Host system: NAS
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26720700
 - deCONZ version: 2.12.06
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
When setting a negative value the following message appears in the deconz log:
![Screenshot 2021-11-07 130931](https://user-images.githubusercontent.com/73723454/140644555-e018e6f6-ea82-4ffb-a581-6be60744946b.png)

Maybe just a wrong type?

**Comment by SwoopX** [comment]
Lookslike this one is on me. Can you try omitting the trailing 0?

**Comment by tatec22** [comment]
If I got you right: There is no difference between -160 and -16. Both values cause the same error message
