### ISSUE TITLE
Deconz can't connect to conbee 2 stick

### ISSUE THREAD

**Issue by spooky82** [dresden-elektronik/deconz-rest-plugin#5466]
My Deconz gui can't connect to my running and operational Conbee 2 Stick.

Version: 2.11.05 / 19/08/2021
Firmware: 26660700

Deconz Version: 2.12.6

![Screenshot 2021-11-08 at 09 14 29](https://user-images.githubusercontent.com/69072419/140706702-cc4502f0-efd5-47fb-934c-32c4a3b09164.png)

The stick is running perfectly on Homebridge (connected to raspi).

Are there any known issues or any advices on how to get the connection established?

**Comment by Mimiix** [comment]
Please use the forum for this :)
