### ISSUE TITLE
Malformed default response on manufacturer specific clusters

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#5469]
## Describe the bug

When a ZCL request is received that is manufacturer specific, deconz apparently sends 2 default responses. The first one is malformed, as it has an incorrect frame control field, therefore showing up as `Discover Commands Received Response` (0x12) in the screenshot. MFC is 0x**12**46. The 2nd default response set is correct however.

## Steps to reproduce the behavior

Read any manufacturer specific attribute or wait for a respective attribute report.

## Expected behavior

Send only a single and correct default response.

## Screenshots

![grafik](https://user-images.githubusercontent.com/4005212/140825866-1903552e-e52d-4fc4-a9c4-75ca872bbc64.png)

## Environment

 - Host system: PC
 - Running method: Ubuntu Virtual Machine
 - Firmware version: 26720700
 - deCONZ version: 2.13.1
 - Device: ConBee II
 - Do you use an USB extension cable: Not relevant
 - Is there any other USB or serial devices connected to the host system? Not relevant

**Comment by manup** [comment]
Confirmed and fixed in firmware now, to be released with the v2.13.4.
