### ISSUE TITLE
Mercator Smart Zigbee Isaac AC Fan Speed Controller Switch

### ISSUE THREAD

**Issue by xdss** [dresden-elektronik/deconz-rest-plugin#5477]
Fan controls not exposed to Home Assistant, type is On/Off light
    "18": {
        "etag": "1c06ae14ed723c222e34cc2e39eb3f1a",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2021-11-14T03:59Z",
        "manufacturername": "_TZ3210_lzqq3u4r",
        "modelid": "TS0501",
        "name": "On/Off light 18",
        "state": {
            "alert": "none",
            "on": false,
            "reachable": false,
            "speed": 0
        },
        "swversion": null,
        "type": "On/Off light",
        "uniqueid": "bc:33:ac:ff:fe:0b:2d:93-01"
    },
## Device

- Product name: Mercator Smart Zigbee Isaac AC Fan Speed Controller Switch
- Manufacturer: _TZ3210_lzqq3u4r
- Model identifier: TS0501
- Device type : 
  - Light
  - Fan

## Screenshots

![image](https://user-images.githubusercontent.com/52729314/141290014-650fab99-6a80-40f0-9e87-3bee07b2ded8.png)

### Basic
![image](https://user-images.githubusercontent.com/52729314/141290054-1a3684b6-49bc-4d5a-a40d-cb6c42626ff2.png)
![image](https://user-images.githubusercontent.com/52729314/141289923-0d35fe20-1bfd-4bdc-9df0-a0b73774c78e.png)
### Identify
![image](https://user-images.githubusercontent.com/52729314/141290241-15402d42-328e-4908-8d10-201b45408c2c.png)

### Groups
![image](https://user-images.githubusercontent.com/52729314/141292131-7ffd3953-728d-4d2c-a8b4-31405d3c4713.png)

### Scenes
![image](https://user-images.githubusercontent.com/52729314/141292228-0fc8aad0-5e50-42b6-85d0-a9b8749d592b.png)

### On/Off
![image](https://user-images.githubusercontent.com/52729314/141290194-96fc9d88-cb67-4028-bb52-e157926c34a9.png)

### Fan Control
![image](https://user-images.githubusercontent.com/52729314/141290273-00ab66ab-8bd5-4feb-936e-8b20e6f7a86f.png)

### Other clusters that are not mentioned above

![image](https://user-images.githubusercontent.com/52729314/141667028-66f21e8c-8f5b-4198-8db2-3afe1248528c.png)

**Comment by Mimiix** [comment]
Some screens are missing .  Also: Make sure to make a forum post.

**Comment by Mimiix** [comment]
Also, does this work correctly when you control it with the rest api? https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#parameters_2

**Comment by xdss** [comment]
> Some screens are missing . Also: Make sure to make a forum post.

Sorry, first time, all other clusters appear to be zeros. 



> Also, does this work correctly when you control it with the rest api? https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#parameters_2

Yes rest api speed control works, 
Should the device type and class be grayed out in basic?

**Comment by Mimiix** [comment]
@xdss Ah okay. Than i think it's not a deCONZ issue but a HA issue.

@kane610 If the rest-api works, than this issue is solely for HA is suppose? Can you check allong?

**Comment by Kane610** [comment]
This issue originates from https://community.home-assistant.io/t/deconz-official-thread/100504/2752?u=robban

I would expect an endpoint with zhatype="fan" would be created, so in my opinion the implementation on deconz side is lacking.

**Comment by Mimiix** [comment]
@SwoopX @manup @ebaauw can you elaborate on this?

**Comment by xdss** [comment]
bump, screens all updated.

**Comment by xdss** [comment]
still awaiting response

**Comment by carryonrewardless** [comment]
Any movement on this?  I have the same device/issue.
Thnx

**Comment by xdss** [comment]
> Any movement on this? I have the same device/issue. Thnx

No updates from devs yet, still keen to get this integrated.

**Comment by carryonrewardless** [comment]
On this page https://github.com/Koenkk/zigbee2mqtt/issues/1357  some-one has posted 
"You should be able to control the fan by sending to zigbee2mqtt/0x0022a3000016d039/set payload:
{
"fan_mode": "medium"
}"

So we should at least have a work-around but zigbee2mqtt is a package I have not needed previously.

**Comment by carryonrewardless** [comment]
Still hoping for some dev work to resolve this.  Is there anything I can provide to help with this e.g. from logs etc.?

**Comment by carryonrewardless** [comment]
Still an issue pls keep open for investigation of fans.

**Comment by carryonrewardless** [comment]
Still hoping for some dev work to resolve this. Is there anything I can provide to help with this e.g. from logs etc.?

**Comment by Mimiix** [comment]
@Smanar Can you take a look here :)?

**Comment by Smanar** [comment]
There is state/speed to control the Fan speed, it don't work ?

**Comment by carryonrewardless** [comment]
So this is a multi-function device incorporating light on/off control and fan speed control.
Is the required dev work to be done in the HA Addon or in the Integration?

**Comment by Kane610** [comment]
> So this is a multi-function device incorporating light on/off control and fan speed control.
> Is the required dev work to be done in the HA Addon or in the Integration?

Theoretically it can be done in any of them. Though as the developer of the integration I would very much prefer a bit more clear cut rules than how it is now that any light could potentially have fan controls, thus this issue is not resolved yet.

Otoh it might be that I will add generic fan speed control to lights due to other refactorizations, but that does not mean I'd still not want a clear type to identify the support by.

**Comment by carryonrewardless** [comment]
The device is primarily a fan speed controller but it supports those ceiling fans that have an in-built light so the new type would be something like "fan controller with light".

**Comment by Kane610** [comment]
While waiting for any other improvement @carryonrewardless you can use the deconz.configure service in Home Assistant to control the fan speeds, check integration documentation for generic suggestions and just swap stuff out according to the deconz rest api documentation for setting fan speeds

**Comment by xdss** [comment]
> There is state/speed to control the Fan speed, it don't work ?
> 
> Edit: Ok , have see it s working using the API
> 
> Have see the Kane610 post too [#5477 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5477#issuecomment-966516617)
> 
> But I don't see what to do ... Make a new type ? There is not an ikea fan wip ATM ?
> 
> Edit2:
> 
> Find it #5351 And I don't think someone have planned a new device type.

Still hoping for a permanent solution, I see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5351 has been resolved.

**Comment by xdss** [comment]
@Kane610 thanks for your assistance!

**Comment by Kane610** [comment]
> @Kane610 thanks for your assistance!

I haven't yet published the change as there where quite some rework of the integration i want to get feedback that warrants patching the current release prior to me publishing breaking changes between dev and 2022.7. I do plan to publish it next week.

**Comment by Kane610** [comment]
> @Kane610 thanks for your assistance!

@xdss support has been merged to home assistant dev. You can try it out now

**Comment by carryonrewardless** [comment]
@Kane610 Thanks for your work on this!

**Comment by xdss** [comment]
> > @Kane610 thanks for your assistance!
> 
> @xdss support has been merged to home assistant dev. You can try it out now

Perfect, tested and working in 2022.8.2. Shows up as a light and fan with speed control.

**Comment by Kane610** [comment]
> > > @Kane610 thanks for your assistance!
> > 
> > 
> > @xdss support has been merged to home assistant dev. You can try it out now
> 
> Perfect, tested and working in 2022.8.2. Shows up as a light and fan with speed control.

Thanks for verifying!

**Comment by carryonrewardless** [comment]
@Kane610 You say everything is working? 
I only get 2 entities in HA. One for the light on-off and the other for the fan on-off.  There are three buttons so I have no control over fan speed Low/Med/High. What entities do you see?

**Comment by xdss** [comment]
I see the same entities, only need two for full functionality. The fan
entity contains state on/off with speed attributes % slider for speed
off/low/med/high

It corresponds to hardware button 1 toggle light on/off, button 2 toggle
fan on/off, button 3 cycle low/med/high

**Comment by carryonrewardless** [comment]
Thanks. I had started to work that out. Got it happening with an automation. A slider sounds like a good idea.

**Comment by carryonrewardless** [comment]
Thanks again @Kane610

**Comment by carryonrewardless** [comment]
3 years later I decided to add another exact same device. The reason for posting this is that the fan control entity was not created until I added the device to a group in Phoscon followed by a HA re-start.  Is this expected behaviour?
