### ISSUE TITLE
IKEA motion sensors are reporting twice with different uniqueid extension since v2.13.1

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#5478]
## Describe the bug

Since using 2.13.1 my IKEA motion sensors (both old and new models) are reported on an extension ‘-01-1000’ and ‘-01-0006’. This issue persists on deCONZ 2.13.2. I do remember that the -01-1000 extension was part of issues in the past for the rest-api? For my plugin this is an issue as it now creates a device with two motion sensors in it…

The webhook seems to be reporting motion only on the ‘-01-1000’ extensions. Here are the rest-api results coming from postman:

“119”: {
“config”: {
“alert”: null,
“battery”: 74,
“delay”: 60,
“duration”: null,
“on”: true,
“reachable”: true
},
“ep”: 1,
“etag”: “d19d9ac2e7833e9813cc3afbf3f64425”,
“lastannounced”: null,
“lastseen”: “2021-11-11T09:50Z”,
“manufacturername”: “IKEA of Sweden”,
“modelid”: “TRADFRI motion sensor”,
“name”: “Kelder sensor”,
“state”: {
“dark”: true,
“lastupdated”: “2021-11-11T15:04:19.953”,
“presence”: false
},
“type”: “ZHAPresence”,
“uniqueid”: “00:0b:57:ff:fe:38:1d:a3-01-0006”
},

“121”: {
“config”: {
“alert”: “none”,
“battery”: 74,
“delay”: 60,
“duration”: 60,
“group”: “41745”,
“on”: true,
“reachable”: true
},
“ep”: 1,
“etag”: “28590c9282bf9899507e424905551ced”,
“lastannounced”: “2021-11-06T19:52:24Z”,
“lastseen”: “2021-11-11T15:38Z”,
“manufacturername”: “IKEA of Sweden”,
“modelid”: “TRADFRI motion sensor”,
“name”: “Kelder sensor”,
“state”: {
“dark”: true,
“lastupdated”: “2021-11-11T15:04:19.152”,
“presence”: false
},
“type”: “ZHAPresence”,
“uniqueid”: “00:0b:57:ff:fe:38:1d:a3-01-1000”
},

## Steps to reproduce the behavior

Add a IKEA motion sensor to deCONZ and check the rest-api (this can take a bit of time, in my tests half an hour, before the double is showing. Make sure to trigger it now and then.

## Expected behavior

A single ZHAPresence entry for one device

## Environment

 - Host system:for me PC as well as raspberry PI
 - Running method: raspbian buster as well as windows 
 - Firmware version:26390500 Raspbee
 - deCONZ version: 2.13.01 as well as 2.13.02
 - Device: ConBee II / RaspBee I
 - Do you use an USB extension cable: not relevant
 - Is there any other USB or serial devices connected to the host system? not relevant

**Comment by Smanar** [comment]
So both sensor are not created during the inclusion, but the second one (01-0006) appear after a time ?

**Comment by wvuyk** [comment]
No, the other way around, the 01-0006 was the one present 0 also before the 2.13 beta's, the 01-1000 is created as extra device since 2.13. But I remember at the early start of development here on the github, there have been issue on IKEA motion sensor with this 01-1000 extension.... maybe some old code is surfacing here? Not sure

**Comment by Mimiix** [comment]
@manup Looks like what you had with the hue thing

**Comment by wvuyk** [comment]
This is still happening @manup Did you have a chance to look at this?
