### ISSUE TITLE
My dream i become a softwere developer but i have no leptop and computer please help me pls 

### ISSUE THREAD

**Issue by Piyush5949v** [dresden-elektronik/deconz-rest-plugin#5481]
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other: 

### Other clusters that are not mentioned above

**Comment by Mimiix** [comment]
Not sure what to make of this
