### ISSUE TITLE
NookBox AC Siren Indoor Zigbee

### ISSUE THREAD

**Issue by AIT-OLPE** [dresden-elektronik/deconz-rest-plugin#5485]
## Device

- Product name: NookBox AC Siren Indoor Zigbee
- Manufacturer: NookBox
- Model identifier: AC SIren Indoor
- Device type : Please remove all unrelated device types. 
  - Siren

## Screenshots

<img width="631" alt="Screenshot at Nov 14 11-32-23" src="https://user-images.githubusercontent.com/42861939/141677615-d908256b-4d97-4922-90f6-c50e449e2f99.png">

<img width="769" alt="Nodelist" src="https://user-images.githubusercontent.com/42861939/141677621-0d7580fb-bdaf-4a9e-a3b5-c724a20d0d3e.png">

### Other clusters that are not mentioned above
First device so no other clusters to show

**Comment by Mimiix** [comment]
Missing all screenshots
