### ISSUE TITLE
DIYRuz Flower Sensor in 2.13.2 no ZHAMoisture detected

### ISSUE THREAD

**Issue by guny74** [dresden-elektronik/deconz-rest-plugin#5498]
I user deconz 2.13.2 (Doker) with the new initial support of the DIYRUZ Flower sensor (Moisture Sensor).

After starting scanning for new sensor via gui, the sensor only detected as temprature sensor.

After getting device details via API no ZHAMoisture part ist found.
The Sesnor is the same which I used by helping developing the support for this sensor by @Smanar

Is scanning via Gui the right way ? I do not know exaclty how I did it during testing

Thank you

**Comment by Mimiix** [comment]
Please reply on the original request
