### ISSUE TITLE
_TZ3000_ogceypug TS0502B

### ISSUE THREAD

**Issue by filipkotian** [dresden-elektronik/deconz-rest-plugin#5499]
Hi,

would it be possible to add support for this light? also with mesh support? thank you.

## Device

- Product name: Immax neo (tuya)
- Manufacturer: Tuya _TZ3000_ogceypug
- Model identifier: TS0502B
- Device type :
  - Light

**Comment by Mimiix** [comment]
Missing all screenshots.

Closing

**Comment by filipkotian** [comment]
@Mimiix I am sorry, could I still add theme to this topis? It was my first request.

**Comment by Mimiix** [comment]
Feel free to do so.

**Comment by Smanar** [comment]
But it 's a light device ? Not supported natively ?
The mesh support is native for all router.

**Comment by filipkotian** [comment]
It is a light device. I can add it through phoscon, but always just few lights very close to conbee II stick. (I have around 20 of them in office)

**Comment by Smanar** [comment]
So you mean the device is supported, but you have problem to pair them ?
Or if the device is too far away from the conbee, the device disconnect ?

So yes, some capture will be fine. The device can have mesh issue.

**Comment by filipkotian** [comment]
Yes I can add it and also control it. But I am not able to connect devices which are too far away. I had it installed through hue gateway and it is working only when I use hue smart plugs as mesh repeaters.

**Comment by Smanar** [comment]
Can you add some captures pls to check device caracteristics ?

**Comment by filipkotian** [comment]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/28503762/142780703-fc1279b7-f379-4fa3-92da-6be84cce4aac.png">
I only could get this screenshot in deconz, would it be enough? everything else was empty.

**Comment by Mimiix** [comment]
The instructions are really clear how to read the clusters.

**Comment by filipkotian** [comment]
Sorry, please find them attached:

Basic
<img width="423" alt="image" src="https://user-images.githubusercontent.com/28503762/142781160-38cbc507-73b9-4099-aa98-5871e010f2df.png">
Identify
<img width="431" alt="image" src="https://user-images.githubusercontent.com/28503762/142781177-252c8f2e-e6d8-4b5a-8340-9130662bfe5c.png">
Groups
<img width="408" alt="image" src="https://user-images.githubusercontent.com/28503762/142781191-55e878bc-eed8-411f-9bd1-facd0ebfb32b.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/28503762/142781215-9ed84870-fada-4ba5-8fce-1d525bcd6bbf.png">
ON/OFF
<img width="412" alt="image" src="https://user-images.githubusercontent.com/28503762/142781253-970fee55-37e4-4da2-80c6-1cd176f0ae06.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/28503762/142781267-0dcfd2b1-0be8-47b9-bbe1-fa2c1f4e55ad.png">
Level control
<img width="425" alt="image" src="https://user-images.githubusercontent.com/28503762/142781320-d14cbc7b-0c24-4f17-8255-43819bec2968.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/28503762/142781324-a7d4d639-5847-4983-82f4-5ef9b3f05152.png">
ZLL
<img width="403" alt="image" src="https://user-images.githubusercontent.com/28503762/142781343-146b1400-738e-4f59-987c-e2a0dc69f526.png">

**Comment by Smanar** [comment]
I m sorry but all seem fine.
I don't see why the meshing is not working for this device, and I don't see similar issue elsewhere.
Perhaps a bug in the device firmware ?
