### ISSUE TITLE
Namron 4-channel switch problems when restarting deconz

### ISSUE THREAD

**Issue by silecotim** [dresden-elektronik/deconz-rest-plugin#5504]
## Describe the bug

I have two of [these](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2158) switches:

They are added successfully, and events are sent when buttons are pressed.
However, every time deCONZ restarts, the switches stop sending events, instead it broadcasts to all nearby ZigBee devices and random lights turns on and off. A few empty "Groups" are also added in PWA.

To fix, I have to delete said groups and restart deconz a few times. Someimes I even have to delete and re-add the switches.

## Steps to reproduce the behavior

1. Pair a switch
2. Observe that events are sent like they should
3. Restart deconz
4. Observe that empty groups are added and events arent sent anymore, but random broadcasts

## Expected behavior

Events should be sent like normal even though deconz is restarted after pairing the switches.

## Environment

 - Host system: Ubuntu VM
 - Running method: deconzcommunity/deconz Docker Image
 - Firmware version: 26720700
 - deCONZ version: 2.13.02
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

**Comment by manup** [comment]
This looks like the switch misses  certain responses and tried a fallback mode somehow via group casts.

I have an iCasa Pulse 4S here which is also a rebranded Sunricher, I'll check in the sniffer what the device does in case the the coordinator doesn't respond for a while.
