### ISSUE TITLE
Tuya Moes ZTS-EUB - 1 gang switch

### ISSUE THREAD

**Issue by orionevo14** [dresden-elektronik/deconz-rest-plugin#5505]
## Device

- Product name: Tuya Moes ZTS-EUB
- Manufacturer: _TZE200_amp6tsvy
- Model identifier: TS0601
- Device type : 
  - Switch

Seems to be similar to this one : 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2879

## Screenshots

![Capture1](https://user-images.githubusercontent.com/94693831/142770283-9069a015-e5fe-40a6-9910-9fb4130a6239.PNG)

![node_info](https://user-images.githubusercontent.com/94693831/142770294-9cd0ed4f-a221-4a79-9745-416068a630a8.PNG)

### Basic

![basic](https://user-images.githubusercontent.com/94693831/142770153-3bc18d28-e1e8-4827-8e9b-0ecd2484f403.PNG)

### Groups

![group](https://user-images.githubusercontent.com/94693831/142770207-c3964336-96dd-437d-976c-43b237fc12bf.PNG)

### Scenes

![scenes](https://user-images.githubusercontent.com/94693831/142770227-a32a091f-8e50-4533-a1f8-8e44d3dffbb0.PNG)

### Other clusters that are not mentioned above
Tuya specific cluster
![tuya](https://user-images.githubusercontent.com/94693831/142770259-1ee23053-a28a-4e01-bc40-e12fb8f5847e.PNG)

**Comment by Smanar** [comment]
Hello, it s a wired device ?

**Comment by orionevo14** [comment]
Hello, yes it is.
I'm running deCONZ on a RPi4 with Home Assistant integration so I don't have the latest version, only the 2.12.6 so no DDF I think

**Comment by chatainsim** [comment]
Hello, same here with a 2 gangs.
![image](https://user-images.githubusercontent.com/1167931/142859362-a132aac3-9497-4220-a08a-52fd506b807d.png)
Basic
![image](https://user-images.githubusercontent.com/1167931/142859446-ace014d7-249c-4fe8-bf17-864c7833528a.png)
Groups
![image](https://user-images.githubusercontent.com/1167931/142859509-d1d987e2-95ba-4649-b9e4-d5b0e5e916e9.png)
Scenes
![image](https://user-images.githubusercontent.com/1167931/142859593-d3771dc3-34e6-42d9-bb0e-332ddfa7fe4c.png)
Others Clusters
![image](https://user-images.githubusercontent.com/1167931/142859684-f9c00f90-611d-4b28-bafc-614b6fdedea3.png)

Same version, Deconz add-on on HA 2.16.6

Thanks

**Comment by Smanar** [comment]
I can explain a way to make it working in 5mn for almost all tuya switch (that use already supported tuya command) and without compiling the code, but you need at least a version that support DDF.

And this method will be beta (disabled at every restart for the moment, waiting for next deconz version)

**Comment by chatainsim** [comment]
> I can explain a way to make it working in 5mn for almost all tuya switch (that use already supported tuya command) and without compiling the code, but you need at least a version that support DDF.
> 
> And this method will be beta (disabled at every restart for the moment, waiting for next deconz version)

How can we check if there is DDF support ?

**Comment by orionevo14** [comment]
> I can explain a way to make it working in 5mn for almost all tuya switch (that use already supported tuya command) and without compiling the code, but you need at least a version that support DDF.
> 
> And this method will be beta (disabled at every restart for the moment, waiting for next deconz version)

Hello @Smanar 
I can wait. When the method you're talking about will be considered as stable ? In the next 2.13 stable version ?

**Comment by Smanar** [comment]
No sure, will take some time to have the DDF core full working. But if the autodisable at sartup is removed (it s for me the more boring) you can already start to use it.
But yes on the next stable DDF will be usable, even still beta. It will work for exemple for wired switch (already tested), but not battery one.

**Comment by orionevo14** [comment]
Ok thank you for the detailed information, and fast answers too.
Do you have a link or something to some documentation about the way to fix it ? Will surely test that when I'll be able to use 2.13.x

**Comment by chatainsim** [comment]
2.13 stable should be release soon I hope:

```
Current Beta: v2.13.2-beta
Current Stable: v2.12.6

Next Beta: v2.13.3-beta
Next Stable: v2.13.x expected in November.
```
We also have to wait the HA addon update then.

**Comment by Mimiix** [comment]
@chatainsim I shouldn't get my hopes up for november. I think december or perhaps january is a more appropriate timeframe.

**Comment by Smanar** [comment]
For the documentation about DDF (sorry the documentation is WIP too)
The hard part > https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/
The easy one > https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

You can find some device already done with capture on the forum or the github

**Comment by Mimiix** [comment]
@orionevo14 Missing a forum post aswell. Can you please make one?

**Comment by orionevo14** [comment]
> @orionevo14 Missing a forum post aswell. Can you please make one?

Of course !
[https://forum.phoscon.de/t/tuya-moes-zts-eub-1-gang-wired-switch/946](url)

**Comment by Der-WU** [comment]
Hat anyone the ddf Files ready dir the 1 and 2 was Switch?
Are they still in Progress?

Great

**Comment by Smanar** [comment]
If it s a wired device, it can be possible if you have a deconz version that support DDF.

Take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

As device type take on/off  light, and you can let all the rest empty, because the device don't use report, don't use bind, don't use classic cluster.

**Comment by Der-WU** [comment]
I do it. And add 2 on/off light.
But in phoscon it is shown as lightchain and only one light.

**Comment by Smanar** [comment]
Can you show your DDF ?
You need to use fake Endpoint if you have 2 gangs, because I think at the base you have only one.

**Comment by Der-WU** [comment]
My DDF looks :

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_g1ib5ldv",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/ts0601.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

The Cluster  are like the 4th Post.

**Comment by Smanar** [comment]
Ha nice DDF, I would have done the same 

>But in phoscon it is shown as lightchain and only one light.

I m not sure to understand but phoscon can "custom" display.
Can you checks the 2 devices json ? You can find them in phoscon / help / api information, the result will be more "raw" without phoscon interpretation.

**Comment by Der-WU** [comment]
I found some info about the state of ON/OFF.

https://www.zigbee2mqtt.io/devices/TS0601_switch_3_gang.html#tuya-ts0601_switch_3_gang

This is for the 3 way switch. 

The 2 way switch used Endpint 1 and 3.

**Comment by Smanar** [comment]
>The 2 way switch used Endpint 1 and 3.

But it's  virtual endpoint, your device have only one in reality.
It s easy to check, enable deconz log with "info", you will see line with "tuya debug", and press the 2 buttons, to mimic the request.

**Comment by chatainsim** [comment]
@Der-WU did you manage to make it work ?
I've tried to edit the DDF but it's not working.
To light appear in Phoscon but nothing in HA.
They appear in Phoscon, Help, API information.

**Comment by Smanar** [comment]
>To light appear in Phoscon but nothing in HA.

Not normal, HA use the same API than deconz

But BTW you have used the same DDF than him ?
How they are working in phoscon ?
Can you show the 2 device json as result of this DDF ?

**Comment by chatainsim** [comment]
> > To light appear in Phoscon but nothing in HA.
> 
> Not normal, HA use the same API than deconz
> 
> But BTW you have used the same DDF than him ? How they are working in phoscon ? Can you show the 2 device json as result of this DDF ?

Yes, i'ved used the same DDF has @Der-WU 
In Phoson, state is not changing.

json from Phoscon API?

If yes:
```
{
    "etag": "bda2f966ede11c8e1f2e6978eee55da8",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2022-01-04T12:08Z",
    "manufacturername": "_TZE200_g1ib5ldv",
    "modelid": "TS0601",
    "name": "On/Off light 36",
    "state": {
        "on": false,
        "reachable": true
    },
    "swversion": null,
    "type": "On/Off light",
    "uniqueid": "5c:02:72:ff:fe:22:90:fd-02"
}
```
```


                    
{
    "etag": "bda2f966ede11c8e1f2e6978eee55da8",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2022-01-04T12:08Z",
    "manufacturername": "_TZE200_g1ib5ldv",
    "modelid": "TS0601",
    "name": "On/Off light 37",
    "state": {
        "on": false,
        "reachable": true
    },
    "swversion": null,
    "type": "On/Off light",
    "uniqueid": "5c:02:72:ff:fe:22:90:fd-01"
}
```

**Comment by Smanar** [comment]
You have the 2 gangs version ?
Do you have the deconz application (with the GUI) to check logs when making the request (with flag "info") ?

**Comment by chatainsim** [comment]
Yes I have the 2 gangs version.
I have the deconz app with the GUI in home assistant. I don't know how can
I export logs with this version.

**Comment by Smanar** [comment]
No need to export, a screen capture can be enought (if logs are not too much talkative), take only the flag "info_l2".

**Comment by chatainsim** [comment]
Here are the logs.
![image](https://user-images.githubusercontent.com/1167931/149786323-ac9a5543-dc66-4ec3-a447-07f6f4ad7a35.png)
I hope the usefull infos are captured. There is a lot's of logs.
Thanks

**Comment by chatainsim** [comment]
Here is my DDF
![image](https://user-images.githubusercontent.com/1167931/149786785-2c7e3f96-26bf-4f68-a1ba-30530a6863b1.png)
![image](https://user-images.githubusercontent.com/1167931/149786798-fafe6e76-f3f7-4d74-9266-c40c0398e55f.png)
Maybe I made some mistake.

**Comment by Smanar** [comment]
You only have logs with "info" and not "infol2" so all is not complete but we can see the device sending report and the good one.
But nothing appear after ...
I think the DDF is good, but why the code don't proceed the data.

You are sure not having a sensor with same address ? If I add more debug line on code, are you able to recompile the code ? (not possible on HA)

**Comment by chatainsim** [comment]
> You are sure not having a sensor with same address ? If I add more debug line on code, are you able to recompile the code ? (not possible on HA)

Maybe this is my issue. I haven't checked that. How can I see address of the sensor ? Thanks

**Comment by Smanar** [comment]
Just go in phoscon / help / api information / sensors, and look if you have not one with the same uniqueid

`"uniqueid": "5c:02:72:ff:fe:22:90:fd-01"`

Need to check only for 5c:02:72:ff:fe:22:90:fd

**Comment by chatainsim** [comment]
I've found it two times:
```
        "36": {
            "etag": "9ec59053bdb0773ffe6ab39848108a56",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2022-01-18T06:24Z",
            "manufacturername": "_TZE200_g1ib5ldv",
            "modelid": "TS0601",
            "name": "On/Off light 36",
            "state": {
                "on": false,
                "reachable": true
            },
            "swversion": null,
            "type": "On/Off light",
            "uniqueid": "5c:02:72:ff:fe:22:90:fd-02"
        },
        "37": {
            "etag": "194121a36ea6fc29f66417a56f849d5c",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2022-01-18T06:24Z",
            "manufacturername": "_TZE200_g1ib5ldv",
            "modelid": "TS0601",
            "name": "On/Off light 37",
            "state": {
                "on": false,
                "reachable": true
            },
            "swversion": null,
            "type": "On/Off light",
            "uniqueid": "5c:02:72:ff:fe:22:90:fd-01"
        },
```
But it's what i've defined mylself.

**Comment by chatainsim** [comment]
Hello,
Sorry about the delay.
Here are some screenshots.
Logs:
![image](https://user-images.githubusercontent.com/1167931/154680606-d893f84a-90f1-4127-8c41-ebc26bb963f2.png)

DDF:
![image](https://user-images.githubusercontent.com/1167931/154680635-f33a55ed-2495-4c3f-a315-ccf965900502.png)
![image](https://user-images.githubusercontent.com/1167931/154680653-0578e246-bee9-4080-8cbc-ae194d300965.png)

Thank you.

**Comment by chatainsim** [comment]
ok, some news, it appear in HA now.

One of the switch is inverted.
It appear on in HA but it's off and viceversa.
And the other one is not working at all.

It's a good start :)

**Comment by Smanar** [comment]
>One of the switch is inverted.

Here it s bad luck, the DDF core don't support yet the tya cluster, so no way to rever it

>And the other one is not working at all.

Here we need the fake entry, on your DDF I m seing you are creating 2 entrie, one at the endpoint 0x01 (the real one) and one at the endpoint 0x02.
Both are created on the API ?

**Comment by chatainsim** [comment]
Yes both are created on the API.

**Comment by Smanar** [comment]
Can you show the device JSON of both entries ? (Visible for exemple in phoscon / help / API Information) please ?

**Comment by chatainsim** [comment]
Here is the device JSON:
```
"36": {
        "etag": "c8fee577534c3c751746b142cb5c15cc",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2022-02-18T23:01Z",
        "manufacturername": "_TZE200_g1ib5ldv",
        "modelid": "TS0601",
        "name": "On/Off light 36",
        "state": {
            "on": false,
            "reachable": true
        },
        "swversion": null,
        "type": "On/Off light",
        "uniqueid": "5c:02:72:ff:fe:22:90:fd-02"
    },
    "37": {
        "etag": "c8fee577534c3c751746b142cb5c15cc",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2022-02-18T23:01Z",
        "manufacturername": "_TZE200_g1ib5ldv",
        "modelid": "TS0601",
        "name": "On/Off light 37",
        "state": {
            "on": true,
            "reachable": true
        },
        "swversion": null,
        "type": "On/Off light",
        "uniqueid": "5c:02:72:ff:fe:22:90:fd-01"
    },
```

**Comment by Smanar** [comment]
Ok so on the debug line with command (0x01 0x02) with data = 1 you need to have a websocket notification too ...

`"uuid": [ "$address.ext", "0x02"],`

Perhaps this part is just cosmetic ... I will ask to manup.

**Comment by Smanar** [comment]
So I have answer, this part is realy just cosmetic.
So not possible to create fake entry with fake endpoint to support this kind of device yet.

**Comment by chatainsim** [comment]
Too bad. Thank you for your answer! I will store it in my closet and some day maybe I will able to use it. 😉

**Comment by TheAlphaLaw** [comment]
Is there any additional info on the above switch. Still not able to utilize in GUI or turn light off or on.

**Comment by Smanar** [comment]
Hello, just to try, can you try this DDF
```

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_g1ib5ldv",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {
            "fn": "tuya",
            "dpid": 1,
            "eval": "Item.val = Attr.val;"
          },
          "write": {
            "fn": "tuya",
            "dpid": 1,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;"
          },
          "read": {
            "fn": "tuya"
          },
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {
            "fn": "tuya",
            "dpid": 2,
            "eval": "Item.val = Attr.val;"
          },
          "write": {
            "fn": "tuya",
            "dpid": 2,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;"
          },
          "read": {
            "fn": "none"
          },
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by Mimiix** [comment]
Reopening.

**Comment by TheAlphaLaw** [comment]
> Hello, just to try, can you try this DDF ? (long time we haven't check with recent deconz version)
> 
> ```
> 
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TZE200_g1ib5ldv",
>   "modelid": "TS0601",
>   "product": "TS0601",
>   "sleeper": false,
>   "status": "Gold",
>   "subdevices": [
>     {
>       "type": "$TYPE_ON_OFF_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x01"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/on",
>           "parse": {
>             "fn": "tuya",
>             "dpid": 1,
>             "eval": "Item.val = Attr.val;"
>           },
>           "write": {
>             "fn": "tuya",
>             "dpid": 1,
>             "dt": "0x10",
>             "eval": "Item.val == 1 ? 1 : 0;"
>           },
>           "read": {
>             "fn": "tuya"
>           },
>           "refresh.interval": 300
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     },
>     {
>       "type": "$TYPE_ON_OFF_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x02"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/on",
>           "parse": {
>             "fn": "tuya",
>             "dpid": 2,
>             "eval": "Item.val = Attr.val;"
>           },
>           "write": {
>             "fn": "tuya",
>             "dpid": 2,
>             "dt": "0x10",
>             "eval": "Item.val == 1 ? 1 : 0;"
>           },
>           "read": {
>             "fn": "none"
>           },
>           "refresh.interval": 300
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     }
>   ]
> }
> ```

Is there a simple way to copy this info in? I see edit DDF. Thanks!

**Comment by TheAlphaLaw** [comment]
> Yep you can
> 
> * make "edit DDF"
> * Save the file, with looking for the name and the path
> * Edit the file with a text editor and paste this contain
> 
> Or can just create a json file in the "devices" folder, what is your OS ?

Win 11. I used visual basic to make a JSON files and edited DDF. No change.

**Comment by Smanar** [comment]
Deconz check all DDF only at start, so perhaps with restarting deconz.
If you make "edit DDF" now, you will have the edited DDF no ? If you use the editor to make so changes, you can use the "hot reload" fonction in the editor to not have to restart deconz.

**Comment by TheAlphaLaw** [comment]
> Deconz check all DDF only at start, so perhaps with restarting deconz. If you make "edit DDF" now, you will have the edited DDF no ? If you use the editor to make so changes, you can use the "hot reload" fonction in the editor to not have to restart deconz.
> 
> If the modified DDF is not used, create a json file in the "devices" folder, it s the defaut folder used by deconz.

Already done. Does not appear in Home Assistant or Phosconz.

**Comment by Smanar** [comment]
And if you make "Edit DDF" on the GUI on the node ?
It open the good file ? (the file and the name is visible on the editor title)

**Comment by TheAlphaLaw** [comment]
> And if you make "Edit DDF" on the GUI on the node with the right clic menu ? It open the good file ? (the file and the name is visible on the editor title)

Correct, but still not picked up by Phoscon or Home Assistant.

**Comment by Smanar** [comment]
Can you enable log in deconz with "DDF" and "info" ("info_l2 if possible) and on the DDF editor make "hot reload"

**Comment by TheAlphaLaw** [comment]
> Can you enable log in deconz with "DDF" and "info" ("info_l2 if possible) and on the DDF editor make "hot reload"

Nothing shows in either log for that device after hot reload...

**Comment by Smanar** [comment]
With "info" you need to see
```
12:35:47:792 update ddf TS0601 index 1
12:35:47:794 Hot reload device: 84:fd:27:ff:fe:89:ae:21
12:35:47:902 DEV found DDF for 0x84FD27FFFE892A21, path: /home/pi/.local/share/dresden-elektronik/deCONZ/devices/dimmer_module.json
```

Else it mean the DDF is not used, why why it's the one selected on the editor when you make "edit DDF", you are sure it's the same and path in the window title bar ?

Thoses value are good, visible in "node information" or cluster 0x0000 ?

```
  "manufacturername": "_TZE200_g1ib5ldv",
  "modelid": "TS0601",
```

**Comment by nixagit** [comment]
When I try this the json file doesn't load on restart. I can open the json from Edit DDF menu but node remains 0xXXXX even after hot reload. It's correctly named in the /devices folder. Hot reload isn't noted in the info debug. It just says:
`update ddf TS0601 index 0`
Nothing more than that.
I have a 1-gang switch so only included the first endpoint.

**Comment by Smanar** [comment]
For me it mean the DDF is not used at all.
- The DDF is not at the good place
- The device have different model id / manufacture name, perhaps a typo somewhere ...

**Comment by nixagit** [comment]
Deconz version is 2.17.1

I can't see any errors/typos.

**Comment by Smanar** [comment]
Ha ? Oups, yeah after reading there is 2 devices in this post, sorry.
`"modelid": "TS0601"` is good ?

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_amp6tsvy",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {
            "fn": "tuya",
            "dpid": 1,
            "eval": "Item.val = Attr.val;"
          },
          "write": {
            "fn": "tuya",
            "dpid": 1,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;"
          },
          "read": {
            "fn": "tuya"
          },
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {
            "fn": "tuya",
            "dpid": 2,
            "eval": "Item.val = Attr.val;"
          },
          "write": {
            "fn": "tuya",
            "dpid": 2,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;"
          },
          "read": {
            "fn": "none"
          },
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

**Comment by nixagit** [comment]
Sorry for ths confusion. I assumed the manufacturer name would be the same for all devices. Apparently not. Anyway, it now works. The switch shows up in the web gui as "fairy lights" but works as expected and I can control it through Home Assistant.

My switch is 1-gang so this is the json I used:

`{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_amp6tsvy",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": false,
  "status": "Gold",
  "path": "/home/pi/.local/share/dresden-elektronik/deCONZ/devices/ts0601.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 300,
          "read": {
            "fn": "tuya"
          },
          "write": {
            "dpid": 1,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}`

**Comment by Smanar** [comment]
Nice, thx, Pr submitted https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6366

**Comment by TheAlphaLaw** [comment]
Downloaded pre-release and this switch does not pickup new DDF, weird.

**Comment by Smanar** [comment]
Ha ?
Folder issue ?
It was not present on the good folder, the one you have added it ?

**Comment by TheAlphaLaw** [comment]
@Smanar 

I had to add it manually. Also, anytime I restart Deconz, it reverts and loses DDF profile.

**Comment by TheAlphaLaw** [comment]
Latest update working great, thank you!
