### ISSUE TITLE
loratap, tuya zigbee  4 gang remote

### ISSUE THREAD

**Issue by lars-t** [dresden-elektronik/deconz-rest-plugin#5508]
## Device

- Product name: Tuya zigbee 4 Gang Remote
- Manufacturer: _TZ3000_ufhtxr59.
- Model identifier: TS0044.
- Device type : Remote
![1637656890402](https://user-images.githubusercontent.com/7504335/142993689-d029ee9a-8d95-428c-a3e7-454f1c2fc83a.jpg)

## Screenshots

![Selectie_133](https://user-images.githubusercontent.com/7504335/142992549-d4246ee1-6085-431c-ad38-ba0bf2103af5.png)
![Selectie_134](https://user-images.githubusercontent.com/7504335/142995011-a9e8d6c1-e3b9-427b-a505-41fbfb440c0b.png)

**Comment by Mimiix** [comment]
Missing screenshots and forum post.
