### ISSUE TITLE
Philips Hue Outdoor Motion Sensor

### ISSUE THREAD

**Issue by mgrn0** [dresden-elektronik/deconz-rest-plugin#5512]
## Philips Hue Outdoor Motion Sensor

- Product name: Motion Sensor EU (SLR) | Philips Hue
- Manufacturer: Philips
- Model identifier: SML002
- Device type : 
  - Sensor
  
### Basic

![basic-Screenshot-2021-11-24-at-13 40 23](https://user-images.githubusercontent.com/3019226/143243417-a399ff74-0669-4d2b-87ba-9666cb8071bd.jpg)

![basic-Screenshot-2021-11-24-at-13 40 35](https://user-images.githubusercontent.com/3019226/143243435-1fa5af82-1e56-455a-819f-22adeaf26850.jpg)

### Identify
![identify-Untitled-2](https://user-images.githubusercontent.com/3019226/143243836-bff82a62-1ef8-46df-b56f-d31a9727c77a.jpg)

### Device Temperature

![temperature-Screenshot-2021-11-24-at-13 42 30](https://user-images.githubusercontent.com/3019226/143243906-618f1877-c8ad-446c-818c-c6d2b700c3b3.jpg)

### Illuminance

![illuminance-Screenshot-2021-11-24-at-13 42 20](https://user-images.githubusercontent.com/3019226/143244019-9feb3566-695e-4671-a62c-efaac966ddf5.jpg)

### Occupancy

![occupancy-Screenshot-2021-11-24-at-13 42 10](https://user-images.githubusercontent.com/3019226/143244127-db9cc15c-3867-4db2-b522-d2536127ea2c.jpg)

### OTAU

![otau-Screenshot-2021-11-24-at-13 42 49](https://user-images.githubusercontent.com/3019226/143244151-fc77c056-ac38-41aa-a4c4-ff129588fe9f.jpg)

### Power Configuration

![powerConfiguration-Screenshot-2021-11-24-at-13 42 00](https://user-images.githubusercontent.com/3019226/143244185-7937bfa5-a993-4d41-b5aa-1756dff2be5c.jpg)

### Node Info

![nodeInfo-Screenshot-2021-11-24-at-13 38 25](https://user-images.githubusercontent.com/3019226/143244099-91cfe3b4-cd3a-45b0-ad7e-beb883f00fed.jpg)

**Comment by mgrn0** [comment]
Ah, I forgot: this is what the API shows for that specific sensor with latest beta (2.13.02):

![web-Screenshot-2021-11-24-at-13 46 03](https://user-images.githubusercontent.com/3019226/143244726-e6a97999-1d0e-4e19-9517-46d7a09eb954.jpg)

**Comment by mgrn0** [comment]
And this is how the sensor looks like (just not to mismatch it with the philips indoor motion sensor):

![photo-IMG_20211124_141657](https://user-images.githubusercontent.com/3019226/143245915-a943ab36-7b45-4aa6-b58c-ed3b0188ed5a.jpg)

**Comment by Mimiix** [comment]
This device is already supported? 

Can you provide the macAdress please?

**Comment by mgrn0** [comment]
00:17:88:01:06:49:fa:48-02-0406 that should be.

I know that the 'compatibile devices list' states compatibility, I thought that mabye I received a new version of the sensor since it does not work..

**Comment by Mimiix** [comment]
00:17:88:01:06:49:fa:48-02-0406

In your edit, is this really what the rest api showed?

**Comment by mgrn0** [comment]
uh. Maybe I should have just waited. Sensor works now, maybe because I have manually read all values of all clusters one by one.. ? Sorry for the hassle. Will close this request now.

**Comment by Mimiix** [comment]
There people reporting issues with them. That's why I ask. Can you please share a rest api message again?

**Comment by bdickhaus** [comment]
I don't know if this helps, or not, but I have one working with this id 00:17:88:01:06:44:b6:45-02-0406
