### ISSUE TITLE
Centralite Temp and Humidity Sensor

### ISSUE THREAD

**Issue by colin-haber** [dresden-elektronik/deconz-rest-plugin#5515]
## Device

- Product name: Temp and Humidity Sensor
- Manufacturer: CentraLite
- Model identifier: 3310-G
- Device type:
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/500953/143381170-386dc690-d7c7-4b36-95d1-45bb9c86153b.png)

### Basic
![image](https://user-images.githubusercontent.com/500953/143380738-9afdd48a-83f6-4225-ae8b-27591f98cafe.png)

### Identify
![image](https://user-images.githubusercontent.com/500953/143381358-8ba6f036-bde7-4e30-b7ff-3b6e498177e8.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/500953/143381023-9ab543fd-37a5-4a61-89c6-18d174e8e23f.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/500953/143380830-4354f3be-1da2-4c1c-a22d-a35a0a853087.png)
![image](https://user-images.githubusercontent.com/500953/143380937-f6a6e235-d472-48ed-b1e8-a02b9d8666fe.png)
![image](https://user-images.githubusercontent.com/500953/143380987-626b6ed8-a3d6-4912-88c3-9a880e179b19.png)

**Comment by 633kd4d** [comment]
Looks like this was closed without any action...
Can I request support for this device as well?

**Comment by Mimiix** [comment]
Reopened

**Comment by Smanar** [comment]
I think it can be done using DDF.
Take a look here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5738

**Comment by 633kd4d** [comment]
I can get part of it working that way. There is an unknown cluster 0xfc45 that is probably the humidity sensor. No idea how to make that work through DDF.

**Comment by Stim04** [comment]
> I can get part of it working that way. There is an unknown cluster 0xfc45 that is probably the humidity sensor. No idea how to make that work through DDF.

@633kd4d If you can read the humidity value on a the cluster info and that you can see it fluctuating there is a big chance that you will find a way to get it work with DDF, otherwise you'd need a zigbee sniffer to look for cluster info and endpoints for this value. 

@Smanar I speak under your control as I'm just a noob in all that stuff.

**Comment by 633kd4d** [comment]
Yeah. The cluster doesn't show anything for the humidity. I also noticed that the DDF stuff I set up only returned one value and never updated after that. I've never messed with zigbee protocols, so I'm sure I just missed something in the setup.

**Comment by Stim04** [comment]
Maybe not, might have to reset and integrate it again while noot deleting the node. Worked for my sensor that i created my DDF. I had some issues to make it report temp at first pairings, but now i know the trick to reset without deleting the node on deconz. Hope it helps

**Comment by 633kd4d** [comment]
Still not responding. No idea why.
This is the only device I have with a Poll Control cluster. Maybe that has something to do with it?
The little blue/green indicator at the top left of the node seems to indicate that the device is constantly communicating.

**Comment by Stim04** [comment]
then you maybe messed up while creating the DDF, the part where you drag and drop can be a little tricky, and also don't forget to put some min and max req. intervals values.

Do you see the temperature fluctuating when you read the temperature cluster and press the refresh button on your end device?

**Comment by 633kd4d** [comment]
Yes. If I click the read button, the value shows up in the temperature measurement cluster, but that is the only time it changes.

Are you referring to the min max values in the polling cluster?
<img width="359" alt="Screen Shot 2022-02-05 at 10 05 08 PM" src="https://user-images.githubusercontent.com/7098622/152669662-ff778811-c25b-4bc1-8d6d-72e295bbc8f7.png">

**Comment by Stim04** [comment]
no i'm talking about the temperature cluster in the DDF, after you drag and drop. Look the last screenshot I posted you can see it for the battery voltage

**Comment by 633kd4d** [comment]
I think I'll have to move the hardware to a different system to do any of this. It is currently running under Home Assistant. Unfortunately that means it is running in VNC with a window manager that only allows ONE window to be visible at a time. So, no way to drag between windows. Annoying
<img width="1650" alt="Screen Shot 2022-02-05 at 10 35 01 PM" src="https://user-images.githubusercontent.com/7098622/152670299-cd901efa-3d95-484c-94d5-6f303673eeaa.png">
.

**Comment by Stim04** [comment]
No Draging = no Easy coding of the JSON

You can try your luck modifying my JSON with your manufacturer and stuff. I'm using same 402 cluster for temperature.

https://pastebin.com/EQF35gLk

**Comment by Stim04** [comment]
try this it might work

https://pastebin.com/qfegcwac

**Comment by Smanar** [comment]
> I can get part of it working that way. There is an unknown cluster 0xfc45 that is probably the humidity sensor. No idea how to make that work through DDF.

Ha yes, right sorry, this device Use the attribute 0x0000 on the cluster 0xFC45. IDK if it can work.
Drag and drop a ZHAhumidity, clic on it and edit the cluster to use this one instead.
