### ISSUE TITLE
deCONZ initial setup doesn't show coordinator node

### ISSUE THREAD

**Issue by manup** [dresden-elektronik/deconz-rest-plugin#5519]
## Describe the bug

In some installations during the initial setup the creation of the coordinator node fails.
When this occurs an empty node window is shown and no devices can be joined.

## Steps to reproduce the behavior

This can't always be reproduced, but one way to try trigger the bug is to delete config.ini, session.default and zll.db to fake a initial setup.

## Expected behavior

The blue coordinator node shows up and new devices can be joined.

## Environment
 - Host system: cases are confirmed on all platforms
 - Running method: independend
 - Firmware version: not relevant as the issue is in deCONZ core
 - deCONZ version: at least 2.12.6 – 2.13.2
 - Device: not relevant here
 - Do you use an USB extension cable:  yes
 - Is there any other USB or serial devices connected to the host system? not relevant here

## deCONZ Logs

There are no helpful messages visible in the logs for this bug.

## Additional context

Workarounds
1. Restart deCONZ.
2. As alternative search for lights or sensors in the Phoscon App to trigger the creation.

Both workarounds may need to be tried several times as they depend on internal timing while querying the coordinator parameters from the firmware.

**Comment by Se7enair** [comment]
Is the stick connected to a USB3 port? For me it worked to change it to a USB2 port.

**Comment by manup** [comment]
The issue was in deCONZ core :)
This is fixed now in v2.13.3-beta.
