### ISSUE TITLE
phoscon.de down?

### ISSUE THREAD

**Issue by gmitch64** [dresden-elektronik/deconz-rest-plugin#5522]
Was trying to update today, and It looks like phoscon.de is down.

Failed to fetch http://phoscon.de/apt/deconz/dists/buster-beta/InRelease  Could not connect to phoscon.de:80 (144.76.96.194), connection timed out

![image](https://user-images.githubusercontent.com/27970644/143661421-fa231050-a233-4f75-8bf3-3b7de9fd6770.png)

G

**Comment by Mimiix** [comment]
Yes it's down. I already pinged manup
