### ISSUE TITLE
01MINIZB deconz

### ISSUE THREAD

**Issue by matteos1** [dresden-elektronik/deconz-rest-plugin#5540]
## Environment

 - Host system: (Raspberry Pi / )
 - Running method: (RHome Assistent deCONZ Add-on / )
 - Firmware version: (26720700)
 - deCONZ version: (2.xx.yy)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes ) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system?No

**Comment by Mimiix** [comment]
I am not sure what you are trying to achieve here 😅  But this is an empty template....
