### ISSUE TITLE
eWeLink ZG-2001 2 Channel ZigBee Switch DC5-32v

### ISSUE THREAD

**Issue by DubbyMcDubs** [dresden-elektronik/deconz-rest-plugin#5541]
## Device

- Product name: 2 Channel ZigBee Switch DC5-32v
- Manufacturer: eWeLink
- Model identifier: ZG-2001 (Zigbee ID: "ZB-SW02")
- Device type : 
  - Other: Two channel relay module

- Links:
   - https://zigbee.blakadder.com/eWeLink_ZG-2001.html

   - https://www.aliexpress.com/item/1005002347566295.html?aff_fcid=838cd87b9730419a949bb351a9225daf-1635037251054-04238-_9gTCE1&tt=CPS_NORMAL&aff_fsk=_9gTCE1&aff_platform=shareComponent-detail&sk=_9gTCE1&aff_trace_key=838cd87b9730419a949bb351a9225daf-1635037251054-04238-_9gTCE1&terminal_id=c60aa1c2bd3d4f80907b0cc2716fb935

## Screenshots
![image](https://user-images.githubusercontent.com/1713044/144214158-6fee3ec1-ec34-4928-83cb-92049ff4c70b.png)

### Basic
01:
![image](https://user-images.githubusercontent.com/1713044/144214856-b39b53f3-da93-4b06-a359-9661a286e952.png)
02:
![image](https://user-images.githubusercontent.com/1713044/144217500-40e56ff4-adc4-4154-b7a5-78238d299050.png)

### Identify
![image](https://user-images.githubusercontent.com/1713044/144217637-c0340a53-436a-4988-85a1-34609443d941.png)

### Groups
![image](https://user-images.githubusercontent.com/1713044/144217827-79761b76-ef83-4ca6-a3c4-3a37183d1dce.png)

### Scenes
 - Deconz crashes when I hit the read button for Scenes

### ON/OFF
![image](https://user-images.githubusercontent.com/1713044/144217960-ca40fa70-621b-4c93-b313-6ce04882f90d.png)

**Comment by Mimiix** [comment]
Can you please add all screens?

**Comment by DubbyMcDubs** [comment]
> Can you please add all screens?

Which additional screens would you like?

**Comment by Smanar** [comment]
Hello, wich one deconz version are you using ? Can you use the last one (that support DDF) ?

**Comment by DubbyMcDubs** [comment]
v2.12.6

Qt: 5.11.3
GCC: 8.3.0 (C++ 201402)

Commit: d39d01
Firmware: 0x26660700

**Comment by Smanar** [comment]
So you are on HA too ? Can't use a recent one ?

**Comment by DubbyMcDubs** [comment]
I’m not sure what HA is, but if you have a link to download the version you
want me to run I will install.

**Comment by Smanar** [comment]
HA = home automation, they use docker so they always have older versions.
What is your OS and your installation method ?
You need to switch to beta branch and just update package, it will use the lastest version

**Comment by Mimiix** [comment]
Home assistant *

**Comment by DubbyMcDubs** [comment]
No I am not using that. I use homebridge. Rasbian.

**Comment by Smanar** [comment]
> Home assistant *

Oupssss, sorry.

So on pure raspian, no problem to use the beta version. You have the procedure here https://phoscon.de/en/conbee2/install#raspbian

A short description about the DDF here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

Try to start a DDF  and show the preview or say where you are blocked.

**Comment by DubbyMcDubs** [comment]
Thank you. 

I have updated it to the beta version and can see the DDF edidtor successfully.

I have made the changes but they dont appear to be taking effect in deCONZ. Are there any more steps?

Here is the preview:

{
  "schema": "devcap1.schema.json",
  "manufacturername": "eWeLink",
  "modelid": "ZB-SW02",
  "product": "ZB-SW02",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/eWeLink/zb-sw02.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

**Comment by DubbyMcDubs** [comment]
UPDATE:

It appears to only take effect when Control panel is set to "Strict". After that it seems to take effect even after restarting deConz and that setting reverting back to "Disabled". Is that expected?

**Comment by Smanar** [comment]
>It appears to only take effect when Control panel is set to "Strict". After that it seems to take effect even after restarting deConz and that setting reverting back to "Disabled". Is that expected?

IDK for the strict, it need to work with the "Normal", but yes it s disabled at every restart, the feature is still beta, it s a security to don't broke a network.

>Also had a number of crashes when removing sub-devices/units and then hot loading. Hot loading in DDF disabled mode also only seems to work when adding devices but crashes when removing. This again is once you have tricked it into use the DDF by running at least once in strict mode.

Crash ? deconz is closing with segmentation fault error ?

**Comment by DubbyMcDubs** [comment]
> > It appears to only take effect when Control panel is set to "Strict". After that it seems to take effect even after restarting deConz and that setting reverting back to "Disabled". Is that expected?
> 
> IDK for the strict, it need to work with the "Normal", but yes it s disabled at every restart, the feature is still beta, it s a security to don't broke a network.
> 
> > Also had a number of crashes when removing sub-devices/units and then hot loading. Hot loading in DDF disabled mode also only seems to work when adding devices but crashes when removing. This again is once you have tricked it into use the DDF by running at least once in strict mode.
> 
> Crash ? deconz is closing with segmentation fault error ?

I will give it another go using normal to make sure but I did try a few times with no result until I switched to strict.

Yes it is crashing without  presenting any errors.

**Comment by Smanar** [comment]
And BTW there is a command to force DDF be enabled "dev-test-managed" https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-command-line-parameters

**Comment by cobch** [comment]
Hi @DubbyMcDubs I was wondering if you managed to make working the relay with deconz? I will need one like that to make a project for my projector. Great to hear if I can order one soon. Thanks!

**Comment by DubbyMcDubs** [comment]
> Hi @DubbyMcDubs I was wondering if you managed to make working the relay with deconz? I will need one like that to make a project for my projector. Great to hear if I can order one soon. Thanks!

Hi @cobch, yes I did get it working using the recommendations above so that it appears as I wanted it to inside Homebridge. I ended up writing a custom plugin for Homebridge to make it appear as garage doors. I have not made it public yet, but may in the future.

While the modules are very good and work well, one thing to look out for is the double firing of the output when it is using its one shot mode. Sometimes it stops my doors when opening and closing. My fix is to control it myself in the code.

Are you going to use this to trigger your projector to turn on? Home theater is my main hobby so may be able to help you acheive that without using the device, as there are many options.

**Comment by cobch** [comment]
Great to hear. My plan is to use the interlock mode for running an linear actuator dc motor in order to drawn my UST projector from the wall to the desire distance. I will create a custom drawer so it does not need to be far from the wall when I am not looking a movie... I will order the same model and keep in touch with you in the futur if I have problem with deconz (-;
Thanks a lot for your answer!

**Comment by carryonrewardless** [comment]
Sorry. I don't understand how I can use the DDF editor when it has not established a connection by the pairing process. Are the some steps I need to know to do this when not paired? Thanks.
