### ISSUE TITLE
Tuya Temperature and humidity sensor

### ISSUE THREAD

**Issue by markusmauch** [dresden-elektronik/deconz-rest-plugin#5544]
## Device

- Product name: Temperature and humidity sensor
- Manufacturer: tuya _TZ3210_ttkgurpb
- Model identifier: ZC-W1
- Device type :
  - Sensor

## Screenshots
19:18:10:006 No Tuya productId entry found for manufacturername: _TZ3210_ttkgurpb

**Comment by Mimiix** [comment]
Missing all screenshots.

**Comment by markusmauch** [comment]
Screenshots of what? That the sensor is not discovered?? Of the sensor itself?

**Comment by Mimiix** [comment]
Ah, you have an issue with it pairing. 

In that case, it's something you need to ask on the forums. Devices in Zigbee always should be able to pair. If not, then there's nothing to do. In this case it might be useful to open an topic on the forums to figure out why that is. If it seems to be an issue with device support, we can open another issue.

I'm closing this one.

Kind regards,
