### ISSUE TITLE
Tuya LY-TAD-K616S-ZB || Zigbee ID: "TS0601"; "_TZE200_auin8mzr"

### ISSUE THREAD

**Issue by kiekerjan18** [dresden-elektronik/deconz-rest-plugin#5556]
## Device
- Product name: Ceiling Mounted Motion & Illuminance Sensor
- Manufacturer: Tuya
- Model identifier: TS0601
- Device type : 
  - Sensor
 
https://zigbee.blakadder.com/Tuya_LY-TAD-K616S-ZB.html

Screenshots:
![image](https://user-images.githubusercontent.com/63964079/144740575-b11f74aa-718e-4d72-8410-1360128d9d40.png)
![image](https://user-images.githubusercontent.com/63964079/144740618-b96e1ee0-6386-4e86-8020-4b61265c2f06.png)
![image](https://user-images.githubusercontent.com/63964079/144740661-3f98a7f9-655d-4a8e-be48-ec225a275771.png)
![image](https://user-images.githubusercontent.com/63964079/144748388-e8c61bd4-2995-4e2d-98de-6b0e88ce0db0.png)
![image](https://user-images.githubusercontent.com/63964079/144748412-c0b7691e-e14d-4a74-8d1c-204b82574d10.png)
![image](https://user-images.githubusercontent.com/63964079/144748457-bd8b9179-0924-4500-9ef1-abf050be9b16.png)
![image](https://user-images.githubusercontent.com/63964079/144748489-751f11dd-46a4-40af-92a5-8843eef97528.png)
![image](https://user-images.githubusercontent.com/63964079/144748516-04169bc2-7f6e-46c2-acf6-689ee62a3c3c.png)
![image](https://user-images.githubusercontent.com/63964079/144748531-731b79b9-af82-48b8-82ec-4507e0ef4f39.png)
![image](https://user-images.githubusercontent.com/63964079/144748567-e1560911-5a25-4580-8121-94807e6b8542.png)
![image](https://user-images.githubusercontent.com/63964079/144748580-6057103a-1658-41bd-a218-3495b6f59df4.png)

`{
    "etag": "a92bf3680e3d30786fbfc5c10917c1df",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2021-12-05T09:21Z",
    "manufacturername": "_TZE200_auin8mzr",
    "modelid": "TS0601",
    "name": "Smart plug 12",
    "state": {
        "alert": "none",
        "on": false,
        "reachable": false
    },
    "swversion": null,
    "type": "Smart plug",
    "uniqueid": "0c:43:14:ff:fe:6e:97:09-01"
}`

**Comment by Mimiix** [comment]
Missing some screens

**Comment by kiekerjan18** [comment]
> Missing some screens

added screens, still missing some? I think I made screens of everything I could.

**Comment by Mimiix** [comment]
Looks good
