### ISSUE TITLE
Sercomm XHS2-SE Door/Windows Sensor

### ISSUE THREAD

**Issue by CrispyPyro** [dresden-elektronik/deconz-rest-plugin#5575]
## Device

- Product name: Sercomm XHS2-SE Door/Window Sensor
- Manufacturer: Sercomm
- Model identifier: XHS2-SE
- Device type : Please remove all unrelated device types. 
  - Sensor

### Node Info
![image](https://user-images.githubusercontent.com/19698958/145693557-ff0abb96-3d20-4d93-8e47-a46759f706e9.png)

### Basic
![image](https://user-images.githubusercontent.com/19698958/145693305-be3aa449-50e5-4831-86e9-ad0fbf65f2d1.png)

### Identify
![image](https://user-images.githubusercontent.com/19698958/145693376-5848098d-c919-48f6-a7ba-44ca889d226c.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/19698958/145693483-d130468a-eb6e-44b6-b0a6-05b36f6fb0fb.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/19698958/145693337-0307ec63-281a-4c95-b016-12515b976479.png)

### Poll Control
![image](https://user-images.githubusercontent.com/19698958/145693398-5747fd0c-cf4f-462b-8751-9bf0fb284572.png)

### Temperature Control
![image](https://user-images.githubusercontent.com/19698958/145693419-7c0f70af-3c70-4fa4-8b1d-b5ce06a42da9.png)

### Zone Control
![image](https://user-images.githubusercontent.com/19698958/145693441-1e527dfe-4105-4f95-8cc0-f78dd39086de.png)
![image](https://user-images.githubusercontent.com/19698958/145693454-008be53f-7ab6-4540-a204-6ca1f76c5b9a.png)

### OTAU
![image](https://user-images.githubusercontent.com/19698958/145693527-d652dd76-3180-4a87-9eb4-db6b9d7ceba0.png)
![image](https://user-images.githubusercontent.com/19698958/145693536-98a10ebf-c76f-45c0-852f-ce0c344137b8.png)

**Comment by CrispyPyro** [comment]
Is this still the preferred method for submitting device requests?

**Comment by Mimiix** [comment]
@CrispyPyro perhaps you can make a ddf. @Smanar can this be done here?

**Comment by Smanar** [comment]
I think yes, the poll control cluster is something new on this kind of sensor but all the rest is same, this device use the IAS cluster 0x0500

Can take this one as sample https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5584
It's a motion sensor, but use same cluster.
