### ISSUE TITLE
Sandy Beach HY367 Thermostat

### ISSUE THREAD

**Issue by moridianmess** [dresden-elektronik/deconz-rest-plugin#5576]
## Device

- Product name: Sandy Beach HY367
- Manufacturer: unknown
- Model identifier: unkown
- Device type : 
  - Thermostat

https://www.amazon.co.uk/gp/product/B093B4SCBT/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

I bought this device as the zigbee device compatibility list, https://zigbee.blakadder.com/Tuya_HY367.html, said it was already compatible with deconz, but I can't get it to pair through phoscon. I updated my conbee II firmware and deconz to the latest stable release versions this morning, just to be sure.

## Screenshots

![Screenshot from 2021-12-12 13-40-27](https://user-images.githubusercontent.com/2845386/145715409-70ef4cfe-6818-4196-847f-e10d6af4ce3d.png)
![Screenshot from 2021-12-12 13-41-39](https://user-images.githubusercontent.com/2845386/145715420-e2166d26-594f-4076-a820-3f05db7b28f9.png)
![Screenshot from 2021-12-12 13-41-08](https://user-images.githubusercontent.com/2845386/145715429-1b4cc6e9-b0e2-4eb7-bcbd-64a565bf5bb2.png)

### Basic
![Screenshot from 2021-12-12 14-02-52](https://user-images.githubusercontent.com/2845386/145715644-3b7825db-a18a-404c-8934-cab7f9560ec8.png)

### Groups
![Screenshot from 2021-12-12 13-48-11](https://user-images.githubusercontent.com/2845386/145715890-c82a240c-07e2-47b8-8eca-4cd9c7361ee0.png)

### Scenes
![Screenshot from 2021-12-12 13-51-01](https://user-images.githubusercontent.com/2845386/145715446-d8a221ca-0065-4c6d-98a6-2a77bc3708cc.png)
![Screenshot from 2021-12-12 13-51-30](https://user-images.githubusercontent.com/2845386/145715900-44cf5477-2619-43c6-9845-c9f54ec798e0.png)

### Tuya
![Screenshot from 2021-12-12 13-49-26](https://user-images.githubusercontent.com/2845386/145715434-f72c5d1d-0829-47e3-aa09-303c8abec77c.png)

### OTAU
![Screenshot from 2021-12-12 13-49-45](https://user-images.githubusercontent.com/2845386/145715941-a41e0056-4570-49ae-9e10-b09097c2273b.png)

If you need anything else, please let me know and I'll do my best to supply anything you require. This is the first time that something I've bought hasn't just worked, so please bare in mind I have no experience in debugging deconz.

Thanks,

**Comment by craigueh** [comment]
I too have several of these TRVs and can't get them to work with deConz/Homeassistant.
Any help would be appreciated.

**Comment by Mimiix** [comment]
@craigueh Their not supported yet.

**Comment by Adzter** [comment]
Also bought this looking at the compatibility list as per OP. The Deconz compatibility links to #4675 (TS0601) which this device reports as. Is there some difference with this model? It seems to report as TS0601 in the screenshots?

**Comment by edgardavim** [comment]
I have also the Hy367, I managed to link to HA via zigbee2mqtt, but after connecting, just stops working. Showing a huge "1P" at the valve screen.

at Zigbee2mqtt I have this details:
Zigbee Model TS0601
Zigbee Manufacturer _TZE200_2atgpdho
Manufacturer TuYa
Model TS0601_thermostat

i already tried to remove and add, but back to same status error. 

Anyone had identical or know how to move from here?

The message at the TRV
https://live.staticflickr.com/65535/51722394114_d14a1f429a_c.jpg

**Comment by craigueh** [comment]
I just went with ZHA and everything was detected properly. Deconz/Z2MQTT
just didn’t have the necessary support.

**Comment by moridianmess** [comment]
@craigueh are you able to control the device with ZHA? or just read the sensors?

**Comment by craigueh** [comment]
Full control. Works as expected.

**Comment by craigueh** [comment]
Forgot to mention, if you install Z2MQTT Edge instead it will also work.
ZHA for me still seems a little “half baked” so either option should be
fine.

**Comment by Mimiix** [comment]
@Smanar

**Comment by Smanar** [comment]
But this device is not supported ?
As it s a tuya thermostat it's not possible using DDF.

**Comment by moridianmess** [comment]
I just tried DDF in basic mode -> bronze, silver and gold ticked and then went to pair window and enabled it. Put the trv into pair mode, it still appeared the same as before.

**Comment by edgardavim** [comment]
I finally was able to have it working, but still fighting to understand to have it not working 100% . When I set close valve, until now, keeps letting heat go to radiator.

**Comment by moridianmess** [comment]
@edgardavim just out of interest how did you manage to pair it?

With regards to letting heat in, you did let the TRV run through it's set up on that radiator? First boot and after removing batteries, it's suppose to go through a cycle to set itself up with that radiator. Maybe worth re-doing that anyway and trying some different adapters that came with it, as it sounds like the pin isn't being pushed in all the way on the radiator.

Yesterday I did some testing with ZHA, just to see how well the TRV actually works. I am facing a few issues, mainly with not getting sensor values until I physically interact with the device or write an automation to change the temperature every 2 minutes, and even then I don't always get an update. This may just be ZHA being awkward, as it did take four or five attempts to get it to pair successfully. Can anyone confirm whether this is a general issue and would happen in any Zigbee environment?

I will do some more tests over the next few days, I'm going to move the TRV closer to the zigbee gateway and do some more tests with both Deconz and ZHA to see whether these issues are device specific or ZHA specific. If this is a device specific issue, it does make it fairly unusable as I don't get updates about the current temperature and my plan was to never have to physically interact with a radiator valve, apart from changing the batteries.

I was going to try z2mqtt but I can't seem to find any instructions that appear to work when you are running HA in a VM on a linux machine.

**Comment by edgardavim** [comment]
hello @moridianmess 

I am using it with zigbee2mqtt, in hassio. I have a zigbee bulb just above it, so reception is OK (it works as a repeater).

Just took out batteries, did this cycle. Still figuring out how to tell it to close the radiator. This is the challenge, how to define the open, as from my side it shows by percentage.

turned it off to see if closes valve.

![image](https://user-images.githubusercontent.com/35406114/148188092-076e4eb1-4364-402b-92e9-bb1df64e85c3.png)
![image](https://user-images.githubusercontent.com/35406114/148189196-523c1c31-bd30-471c-b640-078090e96721.png)
![image](https://user-images.githubusercontent.com/35406114/148189291-2c0f5e55-528e-4383-880e-3fbfb0717b21.png)
![image](https://user-images.githubusercontent.com/35406114/148189403-4ae93a6a-f4ed-4198-9b04-552fd3d93d0a.png)

**Comment by OptimusGREEN** [comment]
I'm glad I found this issue, was just about to order some of these. I think I'll hold off and keep an eye on here...

**Comment by Adzter** [comment]
It looks like support may be implemented as part of #5603
