### ISSUE TITLE
Find no devices on Raspberry 4 with Conbee 2

### ISSUE THREAD

**Issue by McDin** [dresden-elektronik/deconz-rest-plugin#5578]
Hi there,

Every time I try to add an new device (light, plug, sensor) with Phoscon on Raspberry 4 I do not find any device. I have to backup my data, connect the stick to my laptop, restore the data from pi and have to add the device there, make an backup and restore it on the pi. Then the devices work perfectly.

I have no idea why it doesn't work directly with the pi. I had installed it, and made every single update in hope that would get fixed.

Are there any tips to solve this problem? It does not seem as this is an overall problem.

Thanks

**Comment by Mimiix** [comment]
I suggest using the forum for this :)
