### ISSUE TITLE
Firmware update selects wrong device

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#558]
I've got a Raspberry with both a RaspBee (for deCONZ) and a ConBee (for ZShark) connected.  When doing a firmware update from the web app, deCONZ updates the ConBee firmware instead of the RaspBee firmware.

Workaround is simple: disconnect the ConBee before doing the update.

**Comment by manup** [comment]
Currently the firmware update code is pretty basic and doesn't handle established connections, in the above case it automatically should detect that RaspBee is the actual current deCONZ device.

I'll put it on the list.

**Comment by ebaauw** [comment]
While I appreciate the effort to clean stale issues, I’d hate to see this fall off the “list”.

**Comment by manup** [comment]
Yeah a bit of stale storm.. I ll need to cherry pick the ones to be active again, feel free to remove the wontfix label
