### ISSUE TITLE
E1812 IKEA Shortcut Button unusable after OTA-Update to 2.3.080

### ISSUE THREAD

**Issue by chris83ms** [dresden-elektronik/deconz-rest-plugin#5580]
## Describe the bug

After OTA-Upgrading my IKEA Shortcut Button to the newest Software Version 2.3.080 it isn't sending any events. It's still in Deconz, but no Events show up in the Phoscon-API or in Home Assistant.

Has anything changed due to new click events?

## Steps to reproduce the behavior

  1. Go to 'Deconz and select E1812 in OTA-Update Panel'
  2. Click on 'Query'
  3. After Completion the Version should be 2.3.080
  4. Open Phoscon
  5. Change to Help
  6. Select API
  7. Listen to Events
  8. Click the Button
  9. No event appears

## Expected behavior
Events should be fired and listed in Phoscon API

## Screenshots
![Bildschirmfoto 2021-12-14 um 08 55 07](https://user-images.githubusercontent.com/54248289/145956131-f057cc6e-de5a-41d1-9eb7-976eaf0c672d.png)

![Bildschirmfoto 2021-12-14 um 08 52 00](https://user-images.githubusercontent.com/54248289/145956150-0fbc323a-0337-4925-8519-f1a40678ecb7.png)

![Bildschirmfoto 2021-12-14 um 08 51 51](https://user-images.githubusercontent.com/54248289/145956211-53f54d47-0401-43c0-8131-c66437aa83cc.png)

## Environment
Deconz 2.12.6
Firmware: 0x26720700

Host system: Intel NUC (ESX-Host) and HASS-OS VM
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (0x26720700)
 - deCONZ version: (2.12.6)
 - Device: (ConBee II)
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? Yes, Aeotec Z-Stick Gen5

**Comment by Mimiix** [comment]
Hi,

Please help yourself and us by searching github prior posting: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5449

It is fixed in the latest beta. 

Closing.
