### ISSUE TITLE
Ikea TRADFRI bulb E27 WS globe opal 1055lm

### ISSUE THREAD

**Issue by maxnumberone** [dresden-elektronik/deconz-rest-plugin#5593]
Hello,
could you please add the bulb IKEA TRADFRI LED 1055lm ?

- Product name: IKEA TRADFRI LED 1055lm
- Manufacturer: IKEA of Sweden
- Model identifier: TRADFRIbulbE27WSglobeopal1055lm
- Device type : Please remove all unrelated device types. 
  - Light

## Screenshots

![image](https://user-images.githubusercontent.com/1675540/146820482-76426b7f-0a2d-44e1-a014-a3fb1ea3b629.png)

![image](https://user-images.githubusercontent.com/1675540/146820515-1e91e82a-1634-4b45-8067-2aff9381425e.png)

Thank you in advance,
Max

**Comment by Mimiix** [comment]
Looks like it's already supported. What is not working?

**Comment by maxnumberone** [comment]
it is, but the color temperature is not working fine from the phoscon app: I've assigned a switch command to increase and another one to decrease the color temperature but both commands increases it for this bulb.
in the same group there's a philips hue white ambiance and this one works fine.

**Comment by Mimiix** [comment]
Does it work fine with the rest api? Or from something like home assistant?

**Comment by maxnumberone** [comment]
yes it's ok from jeedom

**Comment by Mimiix** [comment]
Then it's not a deconz bug. Please report it on the forums. There perhaps already are bugreports with scenes and ikea https://forum.phoscon.de
