### ISSUE TITLE
Full Support for Salus SP600 Smart Plug

### ISSUE THREAD

**Issue by incarvr6** [dresden-elektronik/deconz-rest-plugin#5600]
As on this inclusion request
#812

My last post is ignored.

Multiplier is wrong for current and total consumption.
Current consumption is as attribute and should be as entity.

**Comment by incarvr6** [comment]
As on this inclusion request
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/812

My last post is ignored.

Multiplier is wrong for current and total consumption.

**Comment by incarvr6** [comment]
![Screenshot_2021-12-22-21-15-40-50_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/49254419/147156079-809f4570-eb4d-40d2-acc4-5c816278e262.jpg)

**Comment by Mimiix** [comment]
Please fill the form instead of working around the template.

**Comment by incarvr6** [comment]
Why do same thing twice?
It is nearly impossible to do it on phone!!!

**Comment by Mimiix** [comment]
We need the screenshots regardless because those show how the device presents them in the clusters. That issue is ages old and could have a way different firmware then you do.

Working around the template is not appreciated and feels very disrespectful.

**Comment by incarvr6** [comment]
So tell me how I'm supposed to do screenshots on phone??!

**Comment by incarvr6** [comment]
![Screenshot_2021-12-22-21-26-48-57_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/49254419/147157116-e51d5f87-81b6-4f11-a6be-dc4ff9387549.jpg)
Can you read something in here?? Well I can't...

**Comment by Mimiix** [comment]
I can but it's not complete. But Frankly, it isn't our fault that you don't have access to a PC.

I'm locking this issue. Ether way, feel free to open another issue once you got access to a PC and the information.
