### ISSUE TITLE
Cant control Philips LLC010 as single device

### ISSUE THREAD

**Issue by yesnomaybewtf** [dresden-elektronik/deconz-rest-plugin#5614]
## Describe the bug

I added a Philips LLC010 (Iris) to my setup. 
Im not able to switch it on, change color etc pp, except when im switching on/off the whole group where the lamp is added.
Via Hue Essentials im able to change color etc, but also only when im doing this on the group.
## Steps to reproduce the behavior

Add LLC010 to deconz, try to change color on the single lamp.
## Expected behavior

Well, i expect to change color etc on this single lamp, not on the group
## Environment

 - Host system: (Raspberry Pi / PC / NAS): Rpi 4
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine): Docker Container
 - Firmware version: (26xxyy00): 26720700
 - deCONZ version: (2.xx.yy): 2.13.04 / 18.12.2021
 - Device: (ConBee I / ConBee II / RaspBee I / RaspBee II): Conbee 2
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which?: no

## deCONZ Logs

Trying to switch the light on via Home (iOS). 
`{
    "08:16:13:209": {
        "e": "changed",
        "id": "29",
        "r": "lights",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "effect": "none",
            "hue": 52457,
            "on": true,
            "reachable": true,
            "sat": 254,
            "xy": [
                0.1438,
                0.7997
            ]
        },
        "t": "event",
        "uniqueid": "00:17:88:01:00:0d:8e:70-0b"
    }
}`
Trying to switch the light on via Phoscon App:
`{
    "08:17:55:1": {
        "e": "changed",
        "id": "29",
        "r": "lights",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "effect": "none",
            "hue": 52457,
            "on": true,
            "reachable": true,
            "sat": 254,
            "xy": [
                0.1438,
                0.7997
            ]
        },
        "t": "event",
        "uniqueid": "00:17:88:01:00:0d:8e:70-0b"
    }
}`

**Comment by Mimiix** [comment]
Hi,

Can you provide screenshots of all clusters?

**Comment by yesnomaybewtf** [comment]
Hey Dennis,
is a screenshot from the vnc ok?

Von meinem iPhone gesendet

**Comment by Mimiix** [comment]
Sure, but make sure to have all clusters

**Comment by yesnomaybewtf** [comment]
Here we go.
The node Kugel ist the LLC010, strangly i dont see a link to another node, but im able to turn it on with the Phoscon App
<img width="1153" alt="deconz_vnc" src="https://user-images.githubusercontent.com/69599227/147582807-69045e2f-2007-470f-b637-50901c27f584.png">
.

**Comment by Mimiix** [comment]
We need all clusters read https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by yesnomaybewtf** [comment]
Sorry, the screenshots are attached
<img width="367" alt="Bildschirmfoto 2021-12-28 um 19 47 22" src="https://user-images.githubusercontent.com/69599227/147598100-06a3fe34-c70a-4a73-ae48-cfeb66052947.png">
<img width="367" alt="Bildschirmfoto 2021-12-28 um 19 47 37" src="https://user-images.githubusercontent.com/69599227/147598109-862d3224-2a1c-41c4-b945-09a5b72d5da6.png">
<img width="367" alt="Bildschirmfoto 2021-12-28 um 19 48 05" src="https://user-images.githubusercontent.com/69599227/147598111-36ef5f2a-2b4e-426c-9508-a25073dd4b04.png">
<img width="366" alt="Bildschirmfoto 2021-12-28 um 19 48 27" src="https://user-images.githubusercontent.com/69599227/147598113-574a5f0c-b385-41e6-8ea3-f90c48ef3b93.png">
<img width="424" alt="Bildschirmfoto 2021-12-28 um 19 48 51" src="https://user-images.githubusercontent.com/69599227/147598114-81e1fb91-a962-4467-a2eb-078ee5ce70bc.png">
<img width="423" alt="Bildschirmfoto 2021-12-28 um 19 49 09" src="https://user-images.githubusercontent.com/69599227/147598118-17b12e3c-dee7-491d-9a3a-c5abae65e07a.png">
<img width="407" alt="Bildschirmfoto 2021-12-28 um 19 49 37" src="https://user-images.githubusercontent.com/69599227/147598121-fcd7d596-0746-489f-b702-d88f36b4cf52.png">
<img width="407" alt="Bildschirmfoto 2021-12-28 um 19 50 23" src="https://user-images.githubusercontent.com/69599227/147598124-105a8fba-32b1-4dd1-8e2e-ece21cc641fe.png">
<img width="280" alt="Bildschirmfoto 2021-12-28 um 19 51 41" src="https://user-images.githubusercontent.com/69599227/147598129-14ca17ab-76b5-441a-9be7-f314f96c8e06.png">
.

**Comment by Mimiix** [comment]
@ebaauw is this one you can integrate?

**Comment by ebaauw** [comment]
OP didn't read the cluster values, or the _Read_ failed as well.

The LLC010 is a Hue Living Color Iris, a first-generation, gamut-A _Color Light_.  I don't have that model myself, but afaik it uses the same firmware as the Hue Bloom (LLC011) and original Hue light stripe (LST001).  These have been supported by deCONZ and by the REST API plugin for at least six years, even before my time.

If a light can be controlled through a group, but not directly, that usually indicates routing issues on the Zigbee network.  Do you see any Zigbee errors in the deCONZ log?  Did you try and power cycle the light?  Did you try to enable or disable source routing?

> The node Kugel ist the LLC010, strangly i dont see a link to another node, but im able to turn it on with the Phoscon App

That means the light hasn't been reported by any router in their neighbour table.  Could just be a timing issue; the routes are refreshed at low priority in background, but could also mean that indeed none of the other routers know of this light.  This would cause unicast commands to fail, as the gateway wouldn't know where to send them.  Again, power cycling the light (causing a _Device Announcement_) should probably fix this situation (at least temporarily).

**Comment by yesnomaybewtf** [comment]
Its very strange.
The lightstrip next to the iris works well, also the bloom, one floor above.
I placed the iris now in the room where my deconz stick is located.
The iris now has connections to other nodes, and changing color etc works well.
Its not the optimal solution, but the best for now.

Thanks for your help!

**Comment by Pindar** [comment]
@yesnomaybewtf I'm experiencing the exact same problem. Did you make any progress?

**Comment by yesnomaybewtf** [comment]
> @yesnomaybewtf I'm experiencing the exact same problem. Did you make any progress?

The only thing that helped was placing the bloom next to my deconz stick. So the bloom has a direct connection to deconz without any other device between.

**Comment by yesnomaybewtf** [comment]
Convinced my wife to buy another lightstrip, and now got the iris in my room :)
