### ISSUE TITLE
deCONZ for armv7l

### ISSUE THREAD

**Issue by alpintrekker** [dresden-elektronik/deconz-rest-plugin#562]
Hi Guys,

I'm pretty sure, that this question is a bit offtopic, however, you may know the answer:
who do I need to contact at Dresden Electronic to get deCONZ binaries cross compiled for armv7l architecture? RaspBerry is armhf...

Regards,
András

**Comment by alpintrekker** [comment]
@manup, maybe you could give me a hint about this question?

**Comment by manup** [comment]
Hello, sorry currently we only support the default Raspbian for ARM and there are no short term plans to support  and maintain armhf. This may change in future if the demand rises.

**Comment by alpintrekker** [comment]
@manup, are you open to the proposed cooperation?

> Hi, bad news. It is actually BeagleBoneBlack's architecture. Up to my understanding, it would be just a different cross-compilation.
However, I would happy to contribute with cross-compiling, even in the official way, under terms of an NDA

**Comment by manup** [comment]
>@manup, are you open to the proposed cooperation?

Hi, I'm afraid currently this isn't an option for us. However we are currently working more and more build automations in virtual environments, are there QEmu images for the BBB system?

**Comment by alpintrekker** [comment]
Actually, there are some, that claim, they are, but never tested.

**Comment by johanneswilm** [comment]
@manup This is actually quite an important point still. I was quite surprised when I discovered today that for some reason you guys are blocking this and so therefore my new conbee 2 is basically useless.
