### ISSUE TITLE
Aqara (Lumi) Smart Relay wrongly detected/published as dimmable light

### ISSUE THREAD

**Issue by gabrielcorneanu** [dresden-elektronik/deconz-rest-plugin#5624]
## Describe the bug
As the title says...
I have a few of those devices (2 channels each).
In Phoscon they seem to work fine (although it also shows sometime a Brightness control which is not working), but they caused problems in Openhab (plugin looking for brightness value). 

## Expected behavior
I expect them to show as smart plug or onoff light.
I have other devices which both work fine:
_TYZB01_iuepbmpv : smart plug
_TZ3000_npzfdcof : On/Off light

## Environment

 - Host system: NAS
 - Running method: Ubuntu / Virtual Machine
 - Firmware version: 26660700
 - deCONZ version: 2.13.4
 - Device: ConBee II 
 - Do you use an USB extension cable: yes / usbip

## deCONZ Logs

Relevant info (only 1 channel) from help/restapi:
{
    "hascolor": false,
    "manufacturername": "LUMI",
    "modelid": "lumi.relay.c2acn01",
    "name": "WZ Relay L1 a",
    "state": {
        "alert": "none",
        "on": false,
        "reachable": true
    },
    "swversion": "02-27-2019",
    "type": "**Dimmable light**",
 }

**Comment by Smanar** [comment]
I think it s possible to force the "type" using DDF file, it s easy for bulb and you can use the actual json to fill the editor
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
