### ISSUE TITLE
Conbee II detected such as RaspBee

### ISSUE THREAD

**Issue by mikycol** [dresden-elektronik/deconz-rest-plugin#5632]
## Device

ConBee II

### Other clusters that are not mentioned above

I have been using this key for a few months, I wanted to update it to improve the functioning with some devices I tried to run the command with GCFlasher and I found that it is detected as RaspBee instead of ConBee II, as well as from the command:
```
sudo GCFFlasher -l
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
RaspBee: /dev/ttyAMA0 (default)

no FTDI devices found
```
It is currently installed on a Raspberry pi3 with the latest official version of Raspbian (updated to date)

**Comment by Mimiix** [comment]
Hi,

As this is not a device request nor a bug report as described in #5113  I am closing this issue.

Feel free to ask on the forums :)

Kind regards,
