### ISSUE TITLE
TZ3000_gjnozsaz appears but only power and link quality - No power meter

### ISSUE THREAD

**Issue by waazdakka** [dresden-elektronik/deconz-rest-plugin#5633]
## Describe the bug
The plug appears in deCONZ with all its capabilities, but values stay by default in the electrical mesurement and the simple metering panels

## Steps to reproduce the behavior
- Pair Tuya TZ3000_gjnozsaz TS011F plug to deCONZ
- See them appear into deCONZ and succeed to use them (on / off)
- Go to Status panel
- See nothing changing in the electrical measurement and simple metering panels

## Expected behavior
- Obtain the consumption and other electrical values on deCONZ

## Screenshots
<img width="280" alt="image" src="https://user-images.githubusercontent.com/9380081/147949921-47f375e8-b7fb-4138-85e7-990c26461016.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/9380081/147949968-027aa5d7-0340-47a7-8dd2-71784733dac5.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/9380081/147949993-d5de8ad3-a9eb-4b5a-b549-15cd3af64b58.png">

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.13.04 / 18/12/2021
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment]
What if you click read?

If the values don't change, the device probsbly doesn't support it.

**Comment by waazdakka** [comment]
Hmm it's sold as power metering plug :'( 
https://fr.aliexpress.com/item/1005003523027932.html

**Comment by Mimiix** [comment]
If you click read on the clusters, does it show power consumption? Make sure something is plugged in.

**Comment by waazdakka** [comment]
Nothing, it stays at zero and I have a device plugged in. In found some similar issue on Z2MQTT, don't know if it could be a related-issue? https://github.com/Koenkk/zigbee2mqtt/issues/10487

**Comment by Mimiix** [comment]
That doesn't say anything about the device power metering

**Comment by akinek** [comment]
I have the same plug. 

![image](https://user-images.githubusercontent.com/97365264/148661180-b43d626c-f7c2-4da6-9d84-56d6bdee8081.png)
![image](https://user-images.githubusercontent.com/97365264/148661210-544659d9-6c86-4c8c-a1f8-2653c4cae728.png)
![image](https://user-images.githubusercontent.com/97365264/148661229-d786d719-e837-4bcd-9d52-b34757b4eeaf.png)
![image](https://user-images.githubusercontent.com/97365264/148661249-57e5084f-2f9d-4bc9-984d-865aaf79ae39.png)

**Comment by akinek** [comment]
I have the same plug. 

![image](https://user-images.githubusercontent.com/97365264/148661180-b43d626c-f7c2-4da6-9d84-56d6bdee8081.png)
![image](https://user-images.githubusercontent.com/97365264/148661210-544659d9-6c86-4c8c-a1f8-2653c4cae728.png)
![image](https://user-images.githubusercontent.com/97365264/148661229-d786d719-e837-4bcd-9d52-b34757b4eeaf.png)
![image](https://user-images.githubusercontent.com/97365264/148661249-57e5084f-2f9d-4bc9-984d-865aaf79ae39.png)

**Comment by Smanar** [comment]
Ok, so for you it seem working, can try with a DDF https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
you have a sample here, used for most of plugs https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5577

**Comment by raekmacka** [comment]
> Ok, so for you it seem working, can try with a DDF https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet you have a sample here, used for most of plugs #5577
> 
> With text editor, just need to edit thoses lines, the modelid is probably the same (visible on basic clsuter).
> 
> ```
>     "manufacturername": "_TZ3000_w0qqde0g",
>     "modelid": "TS011F",
>     "product": "NAS-WR01B",
>     "path": "/devices/neo/NAS-WR01B.json",
> ```

I am not that familiar to DDF (and kind of new to deconz). l don't get this to work. Ill changed the manufacturnam and got new entities in HA but with value unknown. Trying to understand what I am doing wrong but have no clue.

![image](https://user-images.githubusercontent.com/61554783/148827358-f5c73e28-eb74-4e32-b258-84f260e636ed.png)

![image](https://user-images.githubusercontent.com/61554783/148827459-75c85693-17e9-44b2-be6a-278018ac85bc.png)

![image](https://user-images.githubusercontent.com/61554783/148827879-16a973a8-26e5-4dce-b6de-3f5a65885a89.png)


![image](https://user-images.githubusercontent.com/61554783/148827706-6909675c-c5e9-44df-ad41-374b133363db.png)

**Comment by Smanar** [comment]
I don't understand whay you have 3 entities ?

All 3 are for the same device ? you can find the device JSON in phoscon / help / API Information.
The DDF don't look so bad
The status is other than "draft" ?
You have enabled DDF in the "control" tab ?
Can take "hot reload" in the menu of the DDF editor.
When you select "edit DDF" on the node, what is the path in the windows title ?
where have you saved the DDF ?

**Comment by raekmacka** [comment]
> I don't understand why you have 3 entities ?
> 
> All 3 are for the same device ? you can find the device JSON in phoscon / help / API Information. The DDF don't look so bad The status is other than "draft" ? You have enabled DDF in the "control" tab ? Can take "hot reload" in the menu of the DDF editor. When you select "edit DDF" on the node, what is the path in the windows title ? where have you saved the DDF ?

No it aint the same. Ill got five plugs so there is nothing wrong there. But somehow I manage to get double up of all of them like power_28_2 and so on when i changed in the DDF and hot reloaded.
 
Oh thanks, I was trying to find where I could find the API JSON on a easy way.

    "lastannounced": null,
        "lastseen": "2022-01-11T07:38Z",
        "manufacturername": "_TZ3000_gjnozsaz",
        "modelid": "TS011F",
        "name": "Consumption 27",
        "state": {
            "consumption": null,
            "lastupdated": "none"
     
I have been tested status draft and status silver.
DDF is enabled in control tab
Have tested hot reload

now its devices/smartplug.json
I am on a Windows machine and have tested to save the DDF in AppData/Local/Dresden..../deconz/devices~ and C:/Deconz/devices/...

Now I found something! In the API information I found that I have sensors named power 36,38,40,42 also and they got the power information! But I can't find the sensors in HA. Somehow they are doubled up and just the first one with no information Ill find in HA.

**Comment by Mimiix** [comment]
In the Control tab, is the Status you use for the DDF enabled? So if you have it set on "silver" , is silver also enabled in the control tab?

**Comment by raekmacka** [comment]
Hmm no clue on that one. In control I have set DDF to normal. DDF status is now draft.
How do I see if the status I have been chosen have DDF enabled in control tab?

**Comment by Mimiix** [comment]
![image](https://user-images.githubusercontent.com/43333120/148909063-3cdea2f9-0f96-4b31-aa3d-86e357e61b78.png)

If you have the DDF for the device set to "silver" make sure that "Silver" is also checked in the above screen.

**Comment by raekmacka** [comment]
Hmmm.. For me settings look like. Old version? Settings somewhere else?

![image](https://user-images.githubusercontent.com/61554783/148913301-72207330-2059-4fe4-8cdb-4f1c0780d01c.png)

**Comment by Mimiix** [comment]
Are you on the latest 2.13.4?

**Comment by raekmacka** [comment]
Nope. Im on 2.13.2. Now I updated and got the same setting as you. Still same problem.

I deleted the devices from deconz and connected them again. Now I only got one power and one consumption. Thanks for all the help.

**Comment by Mimiix** [comment]
So it's solved?

**Comment by raekmacka** [comment]
> So it's solved?

Yep, its solved. Got the right information in HA now.

**Comment by Mimiix** [comment]
Can you make a PR With the DDF in bronze? Just so others can benefit this?

**Comment by raekmacka** [comment]
> Can you make a PR With the DDF in bronze? Just so others can benefit this?

Ill can make a try later. Maybe I should rename it, Now its called smartplugtest.json :)
Is there any instruction how it should be set up to PR with DDf in bronze?

**Comment by Mimiix** [comment]
Just make sure the DDF is set to bronze. Then probably you should be able to go here:
https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices/tuya and click "Add file" and upload there ( i think).

Then it should make a PR.

**Comment by karsie1994** [comment]
> > Ok, so for you it seem working, can try with a DDF https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet you have a sample here, used for most of plugs #5577
> > With text editor, just need to edit thoses lines, the modelid is probably the same (visible on basic clsuter).
> > ```
> >     "manufacturername": "_TZ3000_w0qqde0g",
> >     "modelid": "TS011F",
> >     "product": "NAS-WR01B",
> >     "path": "/devices/neo/NAS-WR01B.json",
> > ```
> 
> I am not that familiar to DDF (and kind of new to deconz). l don't get this to work. Ill changed the manufacturnam and got new entities in HA but with value unknown. Trying to understand what I am doing wrong but have no clue.
> 
> ![image](https://user-images.githubusercontent.com/61554783/148827358-f5c73e28-eb74-4e32-b258-84f260e636ed.png)
> 
> ![image](https://user-images.githubusercontent.com/61554783/148827459-75c85693-17e9-44b2-be6a-278018ac85bc.png)
> 
> ![image](https://user-images.githubusercontent.com/61554783/148827879-16a973a8-26e5-4dce-b6de-3f5a65885a89.png)
> 
> ![image](https://user-images.githubusercontent.com/61554783/148827706-6909675c-c5e9-44df-ad41-374b133363db.png)

How did you fill the binding table? I have no idea how to fill the binding table or upload the DDF file to Deconz when running from within Hassio on a Rasp Pi 4.

**Comment by Smanar** [comment]
> How did you fill the binding table?
> I have no idea how to fill the binding table or upload the DDF file to Deconz when running from within Hassio on a Rasp Pi 4.

You can have an issue on HA for bind https://forum.phoscon.de/t/ddf-editor-how-to-drag-bindings/1351
But we can edit the file manualy for  that, will see later, without the bind, values will be updated in HA when you read them in deconz.

To manage file on HA with docker https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5459#issuecomment-1019496135

Else can use the editor and "pre-used" path.

**Comment by waazdakka** [comment]
Hello!
Coming back to the subject, I didn't understand all the edit suggestions in deConz, not sure of what to edit 🙄 But is there any chance to be corrected in the future to allow users to get power information without editing DDF-thing? 😅

**Comment by Smanar** [comment]
>But is there any chance to be corrected in the future to allow users to get power information without editing DDF-thing?

DDF will be added 1 by 1 on the deconz package. But for the moment only DDF submitted in PR have a chance to be in the deconz package.

**Comment by avrel-kb** [comment]
Hi I just installed a plug that is showing as “_TZ3000_gjnozsaz” and does not show the power consumption.
Reading the messages above it seems the solution was found but never finalised. 
what should be done to have the issue resolved?

**Comment by Smanar** [comment]
The DDF was not submitted ^^
@raekmacka can you make the PR or paste it here for someone make it ?

**Comment by avrel-kb** [comment]
Hi, so i did a few tests and tried to understand this DDF concept that was new to me.
I could get the power information in Home Assistant.
The power data is refreshed every 6 minutes, this is not ideal but fine for what I intend to do with it.

I created a DDF but it is in Deconz add-on in HomeAssistant and no idea How to export it... anyone knows ?

**Comment by Smanar** [comment]
I think it s better first to try to change the reporting setting, on the third tab (the min max / chnage).
The option in red is a poll, for device that don't support reporting

To export a DDF, you can copy it from the "preview" tab, but there is probably a magic trick to do for copy/paste, you can't use a simple text editor ?

**Comment by avrel-kb** [comment]
So copy / paste from the preview tab does not work when done from Home Assistant directly.
It did work when opening deconz directly from VNC (it must be activated in the options of the addon).
Please Note that the DDF was created on the basis of the existing device  neo/NAS-WR01B.json
I only changed the device manufacturer name, product ID, Vendor and Product + the read interval for the power (as screenshot above) to 30s. It seems to work.

[_TZ3000_gjnozsaz.json.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8311586/_TZ3000_gjnozsaz.json.zip)

Regarding the reporting setting, on the third tab (the min max), I tried and it had no effect. Setting to 30 s instead of 300 still give a refresh of the data every 6 minutes. 

<img width="967" alt="Screenshot 2022-03-20 at 16 13 12" src="https://user-images.githubusercontent.com/65617648/159170693-6b55e96f-fc03-4bf2-8a69-29f15e134361.png">

**Comment by Smanar** [comment]
Yes can be normal, there is a new tuya plug generation that don't support reporting.

**Comment by De-k** [comment]
I am using 2.14.01.
Path was /usr/share/deCONZ/devices/tuya/_TZ3000_gjnozsaz.json

Will try gold setting

Dek

**Comment by duepuntodue** [comment]
Hi everyone, I've done everything listed above because only on/off are displayed on Home Assistant.
Now, I can see the values...but they are not updated in real time.
Am I missing something?

**Comment by Smanar** [comment]
Yep, probably the missing binding, can you show or tell me wich one DDF you are using ?

**Comment by duepuntodue** [comment]
Thanks for the reply.
I'm using the one linked above by **avrel-kb** with the settings suggested by **De-k**

You can see my settings below, please let me know if you need more info, thanks a lot

<img width="308" alt="Schermata 2022-04-02 alle 17 14 18" src="https://user-images.githubusercontent.com/14820057/161389666-0e2984ca-7d02-47e9-ada1-7588a5f06816.png">
<img width="394" alt="Schermata 2022-04-02 alle 17 13 58" src="https://user-images.githubusercontent.com/14820057/161389668-bcede4ad-de28-4310-866a-e92f84f3892c.png">
<img width="383" alt="Schermata 2022-04-02 alle 17 13 42" src="https://user-images.githubusercontent.com/14820057/161389671-f4a67d85-45f7-4bae-8884-4dedfe3a9bc0.png">

**Comment by duepuntodue** [comment]
<img width="1397" alt="Schermata 2022-04-02 alle 17 26 14" src="https://user-images.githubusercontent.com/14820057/161390039-30da246e-813a-4b60-ae6c-1fa2ff4d2a8f.png">

**Comment by Smanar** [comment]
Can you check the application version in cluster 0x0000, old version don't support reporting (69 from my memory) so deconz use polling for them.

**Comment by duepuntodue** [comment]
<img width="379" alt="Schermata 2022-04-02 alle 18 08 20" src="https://user-images.githubusercontent.com/14820057/161391500-81a5c722-8604-45e4-9c7a-df46d3b8404f.png">

**Comment by duepuntodue** [comment]
am 68, is it a problematic one? in your experience is it a solvable problem?

**Comment by Smanar** [comment]
If you have time, take a look here https://forum.phoscon.de/t/new-tuya-smart-plug-nas-wr01b-or-tz3000-w0qqde0g/819

From my memory, some users have updated their plugs.

**Comment by duepuntodue** [comment]
tnx i'll let you know!

**Comment by duepuntodue** [comment]
So to my understanding I only need a  Tuya Hub to upgrade the plug version, am I correct? sorry but my english is not that good to fully understand the whole thread :-(

**Comment by Smanar** [comment]
Same for me ^^, and too much thing to read.

You can increase the refresh interval, to speed up the polling, but yes it seem lot of users have updated their plugs

Here it s the same than you, the TZ3000_gjnozsaz  https://forum.phoscon.de/t/new-tuya-smart-plug-nas-wr01b-or-tz3000-w0qqde0g/819/79

**Comment by duepuntodue** [comment]
The important thing is that I can make it work somehow
Thank you VERY much for your kind support.

**Comment by De-k** [comment]
Hi everybody,

i got it working. As mentioned before, I am using fhem as a smart home SW. One thing that bothers me is the frequency of the updates:
[power value]:
2022-04-04_16:57:15 6
2022-04-04_16:57:16 40
(...)
2022-04-04_16:57:36 6
2022-04-04_16:57:37 104
2022-04-04_16:57:38 41

I get a new value every second. I am struggling to find a specification of the json-content of the file. Is there something where this can be limited?

Dek

**Comment by Smanar** [comment]
Lol, one user have too much notification and the other too less, swap your devices ^^.

Seriously, are you using a DDF ?
If yes just go on the binding tab (the third) and at reporting you can change the setting (min / max / change), if it don't work your device use probably polling, try to increase the "interval value"

**Comment by duepuntodue** [comment]
> Hi everybody,
> 
> i got it working. As mentioned before, I am using fhem as a smart home SW. One thing that bothers me is the frequency of the updates: [power value]: 2022-04-04_16:57:15 6 2022-04-04_16:57:16 40 (...) 2022-04-04_16:57:36 6 2022-04-04_16:57:37 104 2022-04-04_16:57:38 41
> 
> I get a new value every second. I am struggling to find a specification of the json-content of the file. Is there something where this can be limited?
> 
> Dek

Can you please check the application version in cluster 0x0000? Are you using DDF?

**Comment by De-k** [comment]
Hi,

currently I am using
[_TZ3000_gjnozsaz.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8415841/_TZ3000_gjnozsaz.zip)

I copied the file to 
`~/.local/share/dresden-elektronik/deCONZ/devices/_TZ3000_gjnozsaz.json`
Of the user running deconz (default user pi on Raspberry)

I cannot use the gui, since my raspi is headless: only ssh terminal available. So i will try to adjust the json file according to your hints

Dek

**Comment by cobirnm** [comment]
Hello,

Have you been able to pair this plug to the Zigbee network? I have received 3 of these plugs and I'm unable to pair any of them. Well I'm able to pair but they get unreachable after the pairing procedure is over. 
When I press the plug for 5 seconds to initiate the pairing procedure, it stays in pairing mode for over 7 minutes. During that time it gets in to deconz and I can control on and off. When the pairing finishes the plug gets unreachable and can't control it.

Has anyone experienced this?

**Comment by lordCONAN** [comment]
I edited the json @De-k linked to match my plug (_TZ3000_kx0pris5), SSH'd into my HAOS machine, and placed the file in /mnt/data/supervisor/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices
This got power monitoring working for both the 16A and 20A version of the same plug I have.

**Comment by Smanar** [comment]
But I don't understand why some users have the good folder and other no ...
And I have perhaps something new too for HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-ha-using-text-editor/1839/2

**Comment by nukleuz80** [comment]
Hi there,
i tried the DDF file from @De-k and now i get the measurement sensors.
It seems to work fine but the power in Watt is 0.

Do you have any suggestions for it?

Here a screenshot from ioBroker objects and API - they are identical to each other...

![grafik](https://user-images.githubusercontent.com/43496030/168025810-0b833c0d-ca14-495d-8890-bf496b71f308.png)

`                  
{
    "config": {
        "on": true,
        "reachable": true
    },
    "etag": "0bbbdee622e75c565a02da42c91c5a43",
    "lastannounced": "2022-05-12T07:47:01Z",
    "lastseen": "2022-05-12T08:21Z",
    "manufacturername": "_TZ3000_gjnozsaz",
    "modelid": "TS011F",
    "name": "Power 125",
    "state": {
        "current": 17,
        "lastupdated": "2022-05-12T08:21:28.521",
        "power": 0,
        "voltage": 233
    },
    "type": "ZHAPower",
    "uniqueid": "a4:c1:38:81:56:ec:63:9a-01-0b04"
}
`

**Comment by Smanar** [comment]
So it work fine but every 90s you have a 0 zero value that overwrite the good one ?

I can't make test on my side but some device use a "filter" feature

```
        {
          "name": "state/power",
          "refresh.interval": 360,
          "read": {
            "at": "0x0400", 
            "cl": "0x0702", 
            "ep": 2,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0400",
            "cl": "0x0702",
            "ep": 1,
            "eval": "if (Attr.val != -16777215 && Attr.val != 16777215) { Item.val = Attr.val; }",
            "fn": "zcl"
          },
          "default": 0
        }
```

**Comment by nukleuz80** [comment]
Hi @Smanar,

there is no other value than 0 (zero). 
I have a light with 15Watt in the plug but the value is 0 when the light/plug is on.

So there is every 90 seconds a 0/zero value.

**Comment by Smanar** [comment]
Ha nope, I have bad understand.
You don't something with more consumption to test ? Because the tension is working, and they are working same in the DDF.

**Comment by phwagner82** [comment]
Hi everyone!
what is the current status on this topic? I have the same problems with this type of plugs...
Hope you can fix this problem!
Kind regards

**Comment by nukleuz80** [comment]
> > Hi @Smanar,
> 
> > 
> 
> > there is no other value than 0 (zero). I have a light with 15Watt in the plug but the value is 0 when the light/plug is on.
> 
> > 
> 
> > So there is every 90 seconds a 0/zero value.
> 
> > 
> 
> > EDIT: So i will check the logs for other values...
> 
> 
> 
> 
> 
> 
> 
> What does the deCONZ Gui show in the respective clusters and attributes?
> 
> 

Here is the cluster...

![image](https://user-images.githubusercontent.com/43496030/169364540-9af9abbe-a4e9-4e99-8601-8c5d62e5dcf9.jpeg)

**Comment by Smanar** [comment]
So the value is 0 too on your capture, you haven't a more powerfull device to test with your plug to have a bigger vlaue ?

**Comment by phwagner82** [comment]
@Smanar  thank you very much for the file and description. The power metering is working, but only once. 
the data will not be refreshed. 
can i support you with some logs to fix the issue? 
br
Philipp

**Comment by Smanar** [comment]
You have the issue on all return ? Power/ voltage / current/ consumption ?
Because the binding don't look so bad, and if the reporting don't working, the poll is enabled too in the DDF ...

**Comment by phwagner82** [comment]
yes, i have no data at all, only after restarting the deconz service or
rebooting the whole HAOS


Am Mi., 15. Juni 2022 um 20:11 Uhr schrieb Smanar ***@***.***

**Comment by nukleuz80** [comment]
> So the value is 0 too on your capture, you haven't a more powerfull device to test with your plug to have a bigger vlaue ?

Now i have values with a more powerful device. I did. not use the file you posted. I think this was my issue...

😎

**Comment by phwagner82** [comment]
For me its not working, the data will be not refreshed.

**Comment by phwagner82** [comment]
Hi Smanar!
thank you very much for your fast response!
Yes, i am using the DDF. If i click on "Edit DDF" the window shows me the DDF file name i used. 
I am using HomeAssistant OS and i cant use the file permanently. how can i find the right log files? 

kind regards 
Philipp

**Comment by Smanar** [comment]
Nothing is updated, consumption, power tension, current ...
Have you tried this modification https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5633#issuecomment-1156781179

You device look exactly same than the capture in the first post ?

**Comment by phwagner82** [comment]
device is A4C138A38E06BF64

15:42:09:474 DEV found DDF for 0xA4C138C10CC75188, path: /usr/share/deCONZ/devices/tuya/_TZ3000_gjnozsaz.json
15:42:09:561 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/id
15:42:09:562 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/lastannounced
15:42:09:563 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/lastseen
15:42:09:564 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/manufacturername
15:42:09:565 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/modelid
15:42:09:565 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/name
15:42:09:566 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/swversion
15:42:09:567 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/type
15:42:09:567 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: attr/uniqueid
15:42:09:568 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: state/alert
15:42:09:569 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: state/on
15:42:09:570 sub-device: a4:c1:38:a3:8e:06:bf:64-01, has item: state/reachable
15:42:09:573 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/id
15:42:09:574 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/lastannounced
15:42:09:574 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/lastseen
15:42:09:575 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/manufacturername
15:42:09:576 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/modelid
15:42:09:576 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/name
15:42:09:577 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/swversion
15:42:09:578 SQL exec failed: SELECT attr FROM sensors WHERE uniqueid = 'a4:c1:38:a3:8e:06:bf:64-01-0702' AND deletedState = 'normal', error: no such column: attr (1)
15:42:09:578 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/type
15:42:09:579 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: attr/uniqueid
15:42:09:580 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: config/on
15:42:09:581 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: config/reachable
15:42:09:581 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: state/consumption
15:42:09:582 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0702, has item: state/lastupdated
15:42:09:584 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/id
15:42:09:585 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/lastannounced
15:42:09:586 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/lastseen
15:42:09:586 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/manufacturername
15:42:09:587 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/modelid
15:42:09:588 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/name
15:42:09:588 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/swversion
15:42:09:589 SQL exec failed: SELECT attr FROM sensors WHERE uniqueid = 'a4:c1:38:a3:8e:06:bf:64-01-0b04' AND deletedState = 'normal', error: no such column: attr (1)
15:42:09:590 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/type
15:42:09:590 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: attr/uniqueid
15:42:09:591 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: config/on
15:42:09:592 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: config/reachable
15:42:09:592 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: state/current
15:42:09:593 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: state/lastupdated
15:42:09:594 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: state/power
15:42:09:594 sub-device: a4:c1:38:a3:8e:06:bf:64-01-0b04, has item: state/voltage
15:42:09:595 DEV add binding cluster: 0x0006,  0xA4C138A38E06BF64
15:42:09:596 DEV add binding cluster: 0x0702,  0xA4C138A38E06BF64
15:42:09:596 DEV add binding cluster: 0x0B04,  0xA4C138A38E06BF64
15:42:09:597 DEV found DDF for 0xA4C138A38E06BF64, path: /usr/share/deCONZ/devices/tuya/_TZ3000_gjnozsaz.json
15:42:09:598 Node 0x90FD9FFFFE86C3A9 is known by 3 neighbors, last seen 0 s
15:42:09:690 DEV Binding enter /devices/0xA4C1389DDE72113A
15:42:09:691 DEV Poll Idle enter /devices/0xA4C1389DDE72113A

**Comment by Smanar** [comment]
You are using the GUI to have logs ?

If yes, after some time, because atm there is the configuration part (busy error that are solved later), do you still have thoses lines

```
15:55:16:032 a4:c1:38:a3:8e:06:bf:64-01-0b04/state/power expression: if (Attr.val != -32768 && Attr.val != 32768) { Item.val = Attr.val; } --> 157
15:55:16:040 ZCL attribute report 0xA4C138A38E06BF64 for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x000
```0

**Comment by phwagner82** [comment]
yes, i am using the gui. 

can i filter the log to get better logs?
![image](https://user-images.githubusercontent.com/58769351/183498933-8e7f760f-2f39-4ab9-bea3-b641aeaf9be0.png)

**Comment by Smanar** [comment]
The 2 previous debug line are visible with "info" and "DDF"

The first one mean the device send the attribute value report or poll
The second one mean a report

And after some time, I don't think you still have this kind of error

>15:55:11:198 DEV: Poll Next failed to enqueue read item: state/current / 0xA4C138C10CC75188

Values are visible on the GUI ? For exemple on the cluster 0x0b04 ?
