### ISSUE TITLE
vibration detection part of the Samsung Multipurpose Sensor (Samjin) either doesnt register or is very slow/stuck

### ISSUE THREAD

**Issue by wifiuk** [dresden-elektronik/deconz-rest-plugin#5636]
## Describe the bug

  If the problem is reproducible, list the steps here:

  1. Go to 'Phoscon Pair the device'
  2. Click on 'Home assistant'
  3. Scroll down to 'the device and see its stuck on detection'
  4. Observed error
## Expected behavior

  Make vibration its detected, stop vibrations, marked as clear in Home Assistant and in Phoscon/DeConz etc.

## Screenshots

![image](https://user-images.githubusercontent.com/3785545/148264818-30faf6df-c456-4c11-9e3e-29efa8f5e7aa.png)
![image](https://user-images.githubusercontent.com/3785545/148264893-60abb2cf-e2f8-481e-8286-2237bc0e07f5.png)
![image](https://user-images.githubusercontent.com/3785545/148265159-08fadfcd-7ea6-4388-a040-71a2ea4cbbe6.png)
## Environment

 - Host system: Synology NAS 
 - Running method: Docker
 - Firmware version: 26660700
 - deCONZ version: 2.13.01 / 06/10/2021
 - Device:  ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? If so: Which? Z-Wave Dongle

## deCONZ Logs

                    {
    "config": {
        "battery": null,
        "on": true,
        "pending": [],
        "reachable": true
    },
    "ep": 1,
    "etag": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "lastannounced": null,
    "lastseen": "2022-01-05T17:54Z",
    "manufacturername": "Samjin",
    "modelid": "multi",
    "name": "Vibration 24",
    "state": {
        "lastupdated": "none",
        "vibration": false
    },
    "type": "ZHAVibration",
    "uniqueid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

                    {
    "17:55:45:870": {
        "attr": {
            "id": "24",
            "lastannounced": null,
            "lastseen": "2022-01-05T17:55Z",
            "manufacturername": "Samjin",
            "modelid": "multi",
            "name": "Vibration 24",
            "swversion": null,
            "type": "ZHAVibration",
            "uniqueid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        },
        "e": "changed",
        "id": "24",
        "r": "sensors",
        "t": "event",
        "uniqueid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "17:56:52:6": {
        "attr": {
            "id": "24",
            "lastannounced": null,
            "lastseen": "2022-01-05T17:56Z",
            "manufacturername": "Samjin",
            "modelid": "multi",
            "name": "Vibration 24",
            "swversion": null,
            "type": "ZHAVibration",
            "uniqueid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        },
        "e": "changed",
        "id": "24",
        "r": "sensors",
        "t": "event",
        "uniqueid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
}

**Comment by Mimiix** [comment]
Can you first make sure to run the latest version and try again?.

**Comment by wifiuk** [comment]
my docker is set to pull the latest automatically, guessing this isn't the latest version then.

**Comment by wifiuk** [comment]
seems something got stuck, any way, now on version:

2.13.04 / 18/12/2021

still got similar issue

**Comment by Mimiix** [comment]
How long does it stay that way?

**Comment by wifiuk** [comment]
i deleted the device since the upgrade, and removed integrations with home assistant it now seems to be working as expected.

**Comment by Mimiix** [comment]
Could be sometimes.

Case closed?

**Comment by Mimiix** [comment]
I suppose case closed
