### ISSUE TITLE
eMylo Zigbee Smart Temp/Hum Sensor

### ISSUE THREAD

**Issue by Dominik-1980** [dresden-elektronik/deconz-rest-plugin#5644]
## Device

- Product name: eMylo Zigbee Smart Temp/Hum Sensor
- Manufacturer: _TZ2000_a476raq2
- Model identifier: TS0201
- Device type : Sensor

## Screenshots

![Bildschirmfoto 2022-01-07 um 15 22 35](https://user-images.githubusercontent.com/32244806/148557928-01bb2383-0682-4383-b035-2a395eaeabe3.png)

![Bildschirmfoto 2022-01-07 um 15 23 45](https://user-images.githubusercontent.com/32244806/148557937-32ae8e36-ec71-47dd-aa6b-caf9b61244e7.png)

The sensor shows up in deconz but not in phoscon.
In Home Assistant it shows up but delivers no data except of battery.

**Comment by Dominik-1980** [comment]
Okay. Sorry. It works now. Just had to wait a moment...
Only in Phoscon the sensor doesn't show up...

**Comment by Mimiix** [comment]
Does it show In ha?

**Comment by Dominik-1980** [comment]
> Does it show In ha? 

Yes.

**Comment by Mimiix** [comment]
In that case you need to open a bug report on the phoscon forum. They add support different there
