### ISSUE TITLE
schneider S520567W

### ISSUE THREAD

**Issue by lepeno82** [dresden-elektronik/deconz-rest-plugin#5648]
## Device

- Product name: wiser odace
- Manufacturer: Schneider
- Model identifier: S520567W
- Device type : Please remove all unrelated device types. 
  - shutter switch

**Comment by Smanar** [comment]
Hello, we need more information, check https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by Mimiix** [comment]
Missing all screens.

Closing.
