### ISSUE TITLE
Offset not shown in temperature value

### ISSUE THREAD

**Issue by boehser-enkel** [dresden-elektronik/deconz-rest-plugin#5657]
## Describe the bug

I added an offset to my hama thermostat but the shown temperature does not change.

## Steps to reproduce the behavior

Add an offset
Look at the temp

## Expected behavior

Temperature should change

## Screenshots

```
{
    "config": {
        "heatsetpoint": 2000,
        "locked": true,
        "mode": "auto",
        "offset": -100,
        "on": true,
        "preset": null,
        "reachable": true,
        "schedule": {},
        "schedule_on": false,
        "setvalve": false,
        "windowopen_set": false
    },
    "ep": 1,
    "etag": "c372c7b0657d07b56d55c394c3c8234d",
    "lastannounced": "2022-01-11T10:13:21Z",
    "lastseen": "2022-01-12T06:31Z",
    "manufacturername": "_TZE200_yw7cahqs",
    "modelid": "TS0601",
    "name": "Thermostat 66",
    "state": {
        "lastupdated": "none",
        "lowbattery": false,
        "on": false,
        "temperature": 2260,
        "valve": null
    },
    "type": "ZHAThermostat",
    "uniqueid": "80:4b:50:ff:fe:21:97:7f-01-0201"
}
```

## Environment

Raspbee
Version: 2.12.06 / 19.8.2021
FW: 26400500

 - Host system: Raspberry Pi
 - Running method: Raspbian 
 - Firmware version: 26400500
 - deCONZ version: (2.12.06
 - Device: RaspBee I 
 - Do you use an USB extension cable: (yes / no) -- only relevant for ConBee I/II - 
 - Is there any other USB or serial devices connected to the host system? If so: Which? No

**Comment by Smanar** [comment]
There is a comment about offset and your device _TZE200_yw7cahqs

I don't remember all the story, but on some device it impact the termostat, not the measured value.
No impact on the device itself ?

Can be the deconz version too ? (the last PR about offset was validated in december)

**Comment by boehser-enkel** [comment]
Using Phoscon on an RPI this is the latest stable version

**Comment by boehser-enkel** [comment]
Same with 2.13.04 / 18.12.2021 and repairing

**Comment by boehser-enkel** [comment]
Now temp got updated and the offset is shown correctly
