### ISSUE TITLE
Tuya SML-01Z-L

### ISSUE THREAD

**Issue by vmercep** [dresden-elektronik/deconz-rest-plugin#5658]
## Device

- Product name: Tuya SML-01Z-L
- Manufacturer: _TZ3000_ji4araar
- Model identifier: TS0011
- Device type :  Switch

## Screenshots

![image](https://user-images.githubusercontent.com/1471213/149128005-925cbab1-7384-4f87-bc75-d468f146e631.png)

![image](https://user-images.githubusercontent.com/1471213/149128119-92c5501e-4deb-4cb5-9dcb-d631fa47f3fa.png)

Device is not recognized, I have managed to setup device with DDF script but when deconz is restarted I loose it.

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_ji4araar",
  "modelid": "TS0011",
  "vendor": "TestSwitch",
  "product": "TS0011",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/ts0011.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername",
          "parse": {
            "at": "0x0004",
            "cl": "0x0000",
            "ep": 255,
            "eval": "Item.val = Attr.val",
            "fn": "zcl",
            "mf": "0x1141"
          }
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

**Comment by Smanar** [comment]
Hello, it s a wired switch ?

I think some thing can be missing in the DDF, like reporting but first

>I have managed to setup device with DDF script but when deconz is restarted I loose it.

You have checked direclty in the API ? if you have not a bad entry (with FF as endpoint) ?
It's strange, one time a device is in the API, it stay inside, and with "gold" status I don't think you have a problem with DDF disabled on start.
