### ISSUE TITLE
Kaipule Smoke Detector ES63 (_TZE200_oapmkvnc / TS0601)

### ISSUE THREAD

**Issue by GoaMind** [dresden-elektronik/deconz-rest-plugin#5660]
## Device

- Product name: [Kaipule Smoke Detector ES63](http://www.kaipule.net/product/detail/l/en/id/53.html)  -  model no: ES63-D5Z
- Manufacturer: _TZE200_oapmkvnc
- Model identifier: TS0601
- Device type :
  - Sensor
  - Siren (not sure if it is applicable here, but device has integrated buzzer)

## Screenshots

  - Endpoints and clusters of the node
  
![image](https://user-images.githubusercontent.com/1936252/149212834-b3abb8a0-30fd-474b-86b5-0c3afefbab46.png)

  - Node Info panel
  
![image](https://user-images.githubusercontent.com/1936252/149206126-32aca1e0-5d89-4b90-af4f-5b2ba5d35f57.png)

Gateway version
![image](https://user-images.githubusercontent.com/1936252/149209267-d2cb6cba-598a-4035-b46f-0bdf88ba8116.png)

### Groups
![image](https://user-images.githubusercontent.com/1936252/149208637-382255ba-48aa-4b5d-9a60-c0e24427ec14.png)
![image](https://user-images.githubusercontent.com/1936252/149208696-e9e1543a-2020-41fa-bce4-6aa0669d031e.png)

### Scenes
![image](https://user-images.githubusercontent.com/1936252/149208760-a74a2bc6-89eb-4775-96ae-92dcf52c6a00.png)
![image](https://user-images.githubusercontent.com/1936252/149208827-0e388b18-2f49-4964-a1b6-fbaa1829dc40.png)
![image](https://user-images.githubusercontent.com/1936252/149208921-bfdb5980-a059-4d33-bb4d-e38c3c5e0b7a.png)

#### Tuya specific Cluster
![image](https://user-images.githubusercontent.com/1936252/149211527-972a9d42-7389-433a-bd8f-e2fe8d06b1bf.png)

#### OTAU
![image](https://user-images.githubusercontent.com/1936252/149209035-6bdca804-ef3d-4dd9-ac8e-d3e4a52f7437.png)

#### Time

***

Please let me know if any further information is needed.

**Comment by GoaMind** [comment]
Do I need to provide some more info or how can I help with this?

**Comment by Mimiix** [comment]
As it's a tuya device and ddf prolly don't work (@Smanar?) and #5733 being in place. You can't.

**Comment by Smanar** [comment]
Yes as it use the tuya cluster and not the IAS one, will be not possible for the moment, sorry.
