### ISSUE TITLE
Tuya door magnetic sensor (iH-F001)

### ISSUE THREAD

**Issue by fmacmahon** [dresden-elektronik/deconz-rest-plugin#5665]
## Device

- Product name: Door magnetic sensor
- Manufacturer: Tuya (E-CrossStu GmbH)
- Model identifier: iH-F001
- Device type : 
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/56723302/149510037-3354d0bc-8ada-4696-b100-0bed193d399a.png)

![image](https://user-images.githubusercontent.com/56723302/149510083-541c8582-3ac8-484a-888e-ffa2d0208627.png)

![image](https://user-images.githubusercontent.com/56723302/149510170-9b8d407a-def1-4553-89fb-02083c33422a.png)

![image](https://user-images.githubusercontent.com/56723302/149510261-d54f0ee3-0e29-41b2-b794-c77cff2baad9.png)

![image](https://user-images.githubusercontent.com/56723302/149510305-5453555a-9fc4-49b5-974d-8549799f9da2.png)

![image](https://user-images.githubusercontent.com/56723302/149510356-05fbb5eb-9e02-4c90-861c-ba7844b1b5f9.png)

![image](https://user-images.githubusercontent.com/56723302/149510386-835201dc-b667-4f82-a74e-d963f0b35bb2.png)

![image](https://user-images.githubusercontent.com/56723302/149510419-a23e741d-172d-45d8-ac6c-eca6fd47908c.png)

![image](https://user-images.githubusercontent.com/56723302/149510502-39b4b156-a1fe-422d-ae94-ad5bca90ec31.png)

**Comment by Mimiix** [comment]
Missing screenshots

**Comment by fmacmahon** [comment]
Which screenshots are missing?

**Comment by Mimiix** [comment]
All clusters.

**Comment by fmacmahon** [comment]
![image](https://user-images.githubusercontent.com/56723302/149498769-7b3e03f5-02c3-471c-9612-ee163efc64a0.png)

**Comment by fmacmahon** [comment]
Can you please check if there is anything missing now?

**Comment by Mimiix** [comment]
These aren't the clusters of the device. Please read:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by fmacmahon** [comment]
Updated! Thanks!

**Comment by powermarcel10** [comment]
Can this one be added?? I have 3 of them.. I thought that they where allready compatible with deconz, but there are not..

Anything that I can do to help?

**Comment by Smanar** [comment]
Sure can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_oxslv1c9",
  "modelid": "TS0203",
  "vendor": "Tuya",
  "product": "iH-F001 Door Window Contact",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/battery",
          "awake": true
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by powermarcel10** [comment]
Allright thanks, but what do I have to do with this code?

**Comment by Smanar** [comment]
It's a DDF https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
Just create a text file with this contain in the "devices" folder and rename it thatyouwant.json

**Comment by powermarcel10** [comment]
Allright thanks! I'm trying it now but when creating a folder and/or try to save the file I'm getting an error; access denied. Any idea what to do?

**Comment by Smanar** [comment]
Yep depend of OS, but on linux 

`sudo chmod -R 777 folder_name`

**Comment by powermarcel10** [comment]
Wow, you're so helpful. Thanks! I'm using a raspberry pi so I think Linux indeed. I wil try it out later!

**Comment by Smanar** [comment]
If you can test it and confirm it work, yes, I can purpose it.

**Comment by powermarcel10** [comment]
I can confirm that they are working great! :D Thanks a lot for your help.

**Comment by Smanar** [comment]
Thss, device added https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6125
