### ISSUE TITLE
Avatto Light Switch

### ISSUE THREAD

**Issue by Larry661** [dresden-elektronik/deconz-rest-plugin#5666]
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: Avatto / Tuya Zigbee
- Model identifier: TS0011
- Device type : 
    - Switch

### List
![image](https://user-images.githubusercontent.com/97727900/149485815-4321dcdc-815c-46fa-9001-e115da46fbd6.png)
### Identify 0003
![image](https://user-images.githubusercontent.com/97727900/149549715-04491660-e06b-41ae-96c6-7a4f00f2ca54.png)

### Groups 0004
![image](https://user-images.githubusercontent.com/97727900/149549887-3b597399-72b6-4ff4-95c6-a8c905546705.png)
![image](https://user-images.githubusercontent.com/97727900/149550131-05c0716b-3177-4694-9649-beab4847c706.png)

### Scenes 0005
![image](https://user-images.githubusercontent.com/97727900/149550261-3d2cd30a-771c-4094-acc3-af77d3d96ceb.png)
![image](https://user-images.githubusercontent.com/97727900/149550444-84be3829-d530-4d15-9048-c555f40fd060.png)
![image](https://user-images.githubusercontent.com/97727900/149550616-b7258bcb-4f2b-4d42-b8b1-c33269502d49.png)
![image](https://user-images.githubusercontent.com/97727900/149550741-04c8d7ff-934e-48a6-ad65-22de4587124c.png)

### On/Off 0006
![image](https://user-images.githubusercontent.com/97727900/149486268-e7b0fc70-8655-4137-9952-2cb8a673392b.png)
![image](https://user-images.githubusercontent.com/97727900/149496675-08e71d55-8bb5-47e6-80c8-79d0980a75b8.png)
![image](https://user-images.githubusercontent.com/97727900/149497204-d0c9990c-2748-4949-9d04-e9cfb5ac99a4.png)
![image](https://user-images.githubusercontent.com/97727900/149497265-951f5829-89d3-4579-8c52-29118630556e.png)

### Unknown E000
nothing

### Unknown E001
nothing

### Basic 0000
![image](https://user-images.githubusercontent.com/97727900/149553968-a7cdea26-d741-457e-94d1-8701c1e753e3.png)

### OTAU 0019
![image](https://user-images.githubusercontent.com/97727900/149551443-51fa27b7-af14-4919-9956-a05cf7192f00.png)
![image](https://user-images.githubusercontent.com/97727900/149551576-f9454563-2cf6-4581-9b70-43782cdfaecc.png)

### Time 000A
![image](https://user-images.githubusercontent.com/97727900/149551662-8c2babf8-4295-4f2d-913a-debf28f766f4.png)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by Larry661** [comment]
hi @Mimiix , 
do you need more screenshots ?

**Comment by Mimiix** [comment]
As written in the template: We need all cluster screenshots.

**Comment by Larry661** [comment]
updated @Mimiix, it is ok for you ?

**Comment by Mimiix** [comment]
This aren't all clusters but just the on/off.

We need all of them.

**Comment by Larry661** [comment]
ok sorry for that, i didn't unterstand.
I hope now it is good.

**Comment by Mimiix** [comment]
Still missing basic

**Comment by Larry661** [comment]
hi @Mimiix, there is basic info just above OTAU info, tell me if it is right ? and i saw #5663 it is look like mine, but not the same manufacturer.

**Comment by Mimiix** [comment]
Looks good now :) 

@Smanar Are #5663 and this one the same? Or different?

**Comment by Smanar** [comment]
Sorry for late answer, no, sot the same device, but will use same hardware I think.
And have same problem, they use a new cluster insteaod of the classic tuya one.

**Comment by Smanar** [comment]
From that I m reading it use the Cluster 0xE001 instead of the Cluster 0xEF00, but works same.
So can try with a recent deconz version > = 2.15.0 and mimic this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5869

Edit:
Ok so not possible for the moment, the tuya write fonction use only one cluster. So need to edit the code first.
Are you able to compile the code to make a test ? You need a linux machine with full OS.

**Comment by Mimiix** [comment]
Reopened on request.

**Comment by Smanar** [comment]
The code can be more critic that I thought, will be nice if someone can test it.

**Comment by pgoujon** [comment]
Hello I have this device in my home, but it doesn't work in Home Assistant (driver)
I can test something if you want but I am newbee so you should explain what to do.
I am under Windows 10 and Home Assistant is on a Raspberry Pi3 in docker.

**Comment by Smanar** [comment]
Thx, but I need someone with a real/full OS, it's possible too on docker, but I can't help you for that.
I think if it don't break something we will try in blind mode, because will be hard to find someone with a full OS AND the device.
