### ISSUE TITLE
AXIS GEAR zigbee HA

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#567]
Will deconz be able to control this soon? 

https://shop.helloaxis.com/products/axis-gear?utm_source=facebook&utm_medium=acquireagency&utm_campaign=retarget-20-off-WT

**Comment by snjoetw** [comment]
@MattL0 were you able to pair GEAR with deconz?

**Comment by MattL0** [comment]
Didnt try :(.


To pricey . Need a confirmstion

**Comment by ebaauw** [comment]
Still looking for an affordable way to control my four blinds.  They use draw strings, so the Gear won't be it, even if I win the lottery.

**Comment by Aepx** [comment]
Any chance these will be supported soon?

**Comment by clement-chung** [comment]
Hi,

I have got issue to pair the Axis gear and unable to discover the device via lights or switches discovery. anyone can help before confirm if the issue should be reopened?
