### ISSUE TITLE
Aqara Wireless mini switch (wxkg11lm)

### ISSUE THREAD

**Issue by Jinguba** [dresden-elektronik/deconz-rest-plugin#5670]
I'm trying to pair Aqara Wireless mini switch (wxkg11lm) but pair is not sucessfull.
I have successfully paired aqara remote switch (h1 double rocker) and this is working fine.
I can see the device in deconz but I dont get any events from it

![image](https://user-images.githubusercontent.com/69633498/149565754-536be09a-e427-4b63-9f15-bf7d81d2bff3.png)

 - Host system: (NAS)
 - Running method: ( Home Assistent deCONZ Add-on)
 - Firmware version: (26700700)
 - deCONZ version: (2.13.4)
 - Device: (ConBee II )
 - Do you use an USB extension cable: ( no) 
 - Is there any other USB or serial devices connected to the host system? Yes
 - If so: Which? Bluethooth dongle

**Comment by Mimiix** [comment]
Please don't make another post but search the issues. It's a known issue and fixed in next release
