### ISSUE TITLE
ThirdReality Water Leak Sensor - 3RWS18BZ

### ISSUE THREAD

**Issue by devWaves** [dresden-elektronik/deconz-rest-plugin#5682]
## Device

- Product name: THIRDREALITY Zigbee Water Leak Sensor
- Manufacturer: Third Reality, Inc
- Model identifier: 3RWS18BZ
- Device type : Please remove all unrelated device types. 
  - Sensor
  - Switch ?

## Screenshots
![IASZoneCLuster](https://user-images.githubusercontent.com/79881052/150061723-0fa40714-1380-43ea-803c-ce3fec41e115.png)
![PowerConfigCluster](https://user-images.githubusercontent.com/79881052/150061724-5b0a010f-d2dd-437d-9204-16e2fdb9b125.png)
![DDFItems](https://user-images.githubusercontent.com/79881052/150061725-53ed758c-0c8d-451b-8005-d533e8d76990.png)
![NodeInfo](https://user-images.githubusercontent.com/79881052/150061726-2a85064d-aa7a-44dc-9a83-d93e11379b7a.png)
![Bindings](https://user-images.githubusercontent.com/79881052/150061729-6260c35a-dc9c-4772-b9b3-943f787176cb.png)
![OTAUCluster](https://user-images.githubusercontent.com/79881052/150061731-3168f955-65d2-42f8-9de2-dc0677d7612f.png)
![BasicCluster](https://user-images.githubusercontent.com/79881052/150061733-a9c0130c-6079-442f-baf6-da70631f1497.png)

### IAS Zone
   ### OTAU

**Comment by devWaves** [comment]
I was able to get the water leak sensor detected by the rest api using the following files and rebuilding the rest api

I referenced this PR to build the files https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5518

de_web_plugin_private.h , de_web_plugin.cpp , bindings.cpp

[de_web_plugin.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7893985/de_web_plugin.txt)
[de_web_plugin_private.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7893986/de_web_plugin_private.txt)
[bindings.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7893987/bindings.txt)


I have also attached the DDF before and after rebuilding the rest api
[ddfBeforePRChange.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7893995/ddfBeforePRChange.txt)
[ddfAfterPRChange.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7893996/ddfAfterPRChange.txt)

**Comment by Smanar** [comment]
Hello, but there is a problem, ATM c++ code edition are locked, we need to make only with DDF (if it's possible)
So without editing the 3 files (it's for that the PR was not merged)

**Comment by devWaves** [comment]
hey @Smanar . I included the ddf file after the PR was made. ddfAfterPRChange.txt . I was under the assumption that was the file that would be needed. Sorry I just started looking at this yesterday and havent had a chance to look at ddf docs and how all this stuff works

**Comment by Smanar** [comment]
No problem, you have a short description here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
But yes for this kind os sensor (that use the cluster IAS) better to start from another DDF sensor.

To test it, you just need a deconz versioin that support DDF without file compilation.

And BTW, there is probably an issue for this maufacture https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5681#issuecomment-1017526763

**Comment by devWaves** [comment]
I created a pull request. https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5728

The DDF is working for me and reporting when water is detected. It is also reporting battery level but is it divided by 2. Not sure why as the DDF configured value is not divided by 2. Eitherway it works good enough. I just have to multiple battery percentage by 2 to get real value

**Comment by Smanar** [comment]
On config/battery on expression try to replace
`Item.val = Attr.val`

by

`Item.val = 2* Attr.val`

**Comment by devWaves** [comment]
using ```Item.val = 2* Attr.val``` doesn't seem to change anything

the battery value is correct when I look at the node in deconz, but through the rest api it is halfed

**Comment by Smanar** [comment]
It's the cluster 0x0001, attribute 0x0021 ?
Try with the "strict mode", it 's probably due to legacy code.

**Comment by devWaves** [comment]
![image](https://user-images.githubusercontent.com/79881052/151883883-60ef3c24-79ef-4596-b822-eefe2fd2cfb3.png)

![image](https://user-images.githubusercontent.com/79881052/151884161-54d2dd44-c2fc-4350-b573-057fe00cc20e.png)

shows correctly in deconz. not in phoscon

I will try the strict mode etc later

**Comment by Mimiix** [comment]
@Smanar what's the status of this one?

**Comment by zahti** [comment]
I just bought 2 of these sensors, and would like to start using them. Please let me know how I can help!

**Comment by Smanar** [comment]
Ha, manup have skipped this one, there is a PR, working, only the battery can missing, but since the time, perhaps it work better now.

@zahti can you try the DDF on the PR ? https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5728
