### ISSUE TITLE
Switch Module 1 Channel No Neutral - SML-01Z-L by Tuya - _TZ3000_ji4araar

### ISSUE THREAD

**Issue by andgest** [dresden-elektronik/deconz-rest-plugin#5684]
## Device

- Product name: Switch Module 1 Channel No Neutral - SML-01Z-L by Tuya.
- Manufacturer: _TZ3000_ji4araar
- Model identifier: TS0011
- Device type : Light On/Off

https://zigbee.blakadder.com/Tuya_SML-01Z-L.html

### Node Info
![image](https://user-images.githubusercontent.com/7107471/150514848-05c65f45-5b87-405c-840a-95e29580d77d.png)

### Basic
![image](https://user-images.githubusercontent.com/7107471/150514749-e7155980-b087-482f-8a2c-cb2a6f1ed3d3.png)

### Identify
![image](https://user-images.githubusercontent.com/7107471/150515581-70903de2-efcb-4eac-96fd-20e470140d53.png)

### Groups
![image](https://user-images.githubusercontent.com/7107471/150515650-5aaf8110-eac2-425f-b1b0-72dba74372fd.png)
![image](https://user-images.githubusercontent.com/7107471/150515675-c9fa37c3-013a-46ad-9099-5e59c5d9a0ae.png)

### Scenes
![image](https://user-images.githubusercontent.com/7107471/150515716-22fe5834-70ba-411b-907a-8300ea3292e9.png)
![image](https://user-images.githubusercontent.com/7107471/150515744-989cc610-3cfe-4399-ad6b-8d0ebcae52cc.png)
![image](https://user-images.githubusercontent.com/7107471/150515785-f1bad77f-3dec-4979-9777-3e072f7f21ab.png)
![image](https://user-images.githubusercontent.com/7107471/150515815-f15191a7-c67a-4b71-8b07-40e19a6533db.png)

### On/Off
![image](https://user-images.githubusercontent.com/7107471/150515841-f1f1a4c7-e844-4161-b37b-77bdfd4af0d9.png)
![image](https://user-images.githubusercontent.com/7107471/150515871-18c13c0a-6e83-422b-aa5b-3b248aba04bf.png)

### OTAU
![image](https://user-images.githubusercontent.com/7107471/150515965-a3cbd735-d724-4a49-888d-4cb45c3fefa8.png)

### Time
![image](https://user-images.githubusercontent.com/7107471/150516025-aa3b3bc9-72e2-4601-9d31-83e29fc863ed.png)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by andgest** [comment]
![image](https://user-images.githubusercontent.com/7107471/150514749-e7155980-b087-482f-8a2c-cb2a6f1ed3d3.png)

![image](https://user-images.githubusercontent.com/7107471/150514848-05c65f45-5b87-405c-840a-95e29580d77d.png)

**Comment by Mimiix** [comment]
Can you please add the screenshots in the opening post, per template? Read carefully.

**Comment by andgest** [comment]
Sorry for the poor quality of the post
I discover DeConz (I usually use only the Phoscon part)

Is it good now?

**Comment by Mimiix** [comment]
Looks good :)!

Thank you

**Comment by andgest** [comment]
For your information, the device does not appear on Phoscon.
However, I can control it remotely from the DeConz interface (turn on, turn off, toggle).

**Comment by Mimiix** [comment]
As it's unsupported, that's indeed how it goes.

We need to wait for a dev to integrate it

**Comment by Smanar** [comment]
So this device is already working ?

**Comment by andgest** [comment]
This work through DeConz with the buttons below.

![150515841-f1f1a4c7-e844-4161-b37b-77bdfd4af0d9__01](https://user-images.githubusercontent.com/7107471/150853461-4468271e-dd5d-44a1-9dcf-9ae0bbcd0350.png)

However, I don't see it appearing on Phoscon, so can't control the device on HomeAssistant

**Comment by mielikki33** [comment]
I have the same problem with this post : 
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5705

I don't see switch on/off on Phoscon with Home Assistant. But i can control the switch with Deconz buttons.

**Comment by Mimiix** [comment]
@mielikki33 because it's not supported. Deconz is raw access and the support needs to be added in the api. That's why it doesn't show up :)

**Comment by Smanar** [comment]
Ha ok so this one is easy to add with DDF.
Just complete the basic information, drag and drop a "On/Off light" device, make a test, if you have no return add the binds.

**Comment by andgest** [comment]
Thank you very much!
It works now :)
I had tried to do this, but I had not changed the status Draft => Gold, so I could not see anything on Phoscon
This video helped me to understand

https://www.youtube.com/watch?v=rgTQpOVg8w0

**Comment by Smanar** [comment]
Hein ?
Lol, so there is a video on DDF on youtube ? seriously ? you are the first one that give the link.

**Comment by mielikki33** [comment]
great you just solved my problem too 

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5705

top the video DDF on youtube.

**Comment by Smanar** [comment]
And BTW pls share your DDF for other.

**Comment by andgest** [comment]
I'm on HomeAssistant and I can't find the json file in the file system or copy and paste it...
Sorry, you'll have to make do with a capture :/

![image](https://user-images.githubusercontent.com/7107471/151029206-b5f79134-a6e0-41bd-a7c6-78fb417fb566.png)
