### ISSUE TITLE
Tuya ZigBee Garage Door Opener

### ISSUE THREAD

**Issue by 0rsa** [dresden-elektronik/deconz-rest-plugin#5685]
## Device

![H3c695045c9e340878439fea02d29c899A](https://user-images.githubusercontent.com/769750/150367776-7a0e2b18-2838-4b13-97fa-e00a76f0137a.jpg)
https://fr.aliexpress.com/item/1005003532414239.html

- Product name: ZigBee Garage Door Opener
- Manufacturer: _TZE200_wfxuhoea
- Model identifier: TS0601
- Device type:
  - Lock (it comes with a radio submodule which communicates with main module, I can see network activity in deconz GUI when I open/close submodule)
  - Other: dry contact

## Screenshots

![basiccluster](https://user-images.githubusercontent.com/769750/150367555-ea470981-8d7d-4c07-871f-8a188ce08003.png)
![clusterota](https://user-images.githubusercontent.com/769750/150367563-bf051a87-031d-4708-9ee0-7b67316c4178.png)
![clustertuyaspecific](https://user-images.githubusercontent.com/769750/150367564-e5f6bb69-5f63-4c3a-85f9-2051776d102c.png)
![details](https://user-images.githubusercontent.com/769750/150367568-c3921d1b-a38a-4ebf-ab50-2043ac406d56.png)
![nodeinfo](https://user-images.githubusercontent.com/769750/150367571-0dff78a5-83c3-40e9-9466-fcd446ecf74c.png)

Thank you

**Comment by dustnipe** [comment]
I'm stuck with the same problem. (_TZE200_wfxuhoea) Is there any activity on this?

**Comment by Mimiix** [comment]
@Smanar  can this be done with DDF?

**Comment by dustnipe** [comment]
The switch itself is recognized but doesn't work when triggered. I can switch the on-state between false and true but the contact wires at the device stay always open.

"10": {
    "etag": "5ce99a67334d7cb2fe41f6a0463094c0",
    "hascolor": false,
    "lastannounced": "2022-05-03T08:39:16Z",
    "lastseen": "2022-05-03T08:39Z",
    "manufacturername": "_TZE200_wfxuhoea",
    "modelid": "TS0601",
    "name": "Garagenoeffner",
    "state": {
      "alert": "none",
      "on": false,
      "reachable": true
    },
    "swversion": null,
    "type": "Smart plug",
    "uniqueid": "a4:c1:38:be:ee:b3:f2:a1-01"
  },

The sensor is not recognized but there is activity in the debug log:

when opened:
14:15:37:629 Tuya debug 4 : Address 0xA4C138BEEEB3F2A1 Payload 00a00301000101
14:15:37:629 Tuya debug 5 : Status: 0 Transid: 160 Dp: 259 (0x01,0x03) Fn: 0 Data 1

when closed:
14:15:39:540 Tuya debug 4 : Address 0xA4C138BEEEB3F2A1 Payload 00a30301000100
14:15:39:540 Tuya debug 5 : Status: 0 Transid: 163 Dp: 259 (0x01,0x03) Fn: 0 Data 0
14:15:39:612 Tuya debug 4 : Address 0xA4C138BEEEB3F2A1 Payload 00a40c04000102
14:15:39:613 Tuya debug 5 : Status: 0 Transid: 164 Dp: 1036 (0x04,0x0C) Fn: 0 Data 2

**Comment by Smanar** [comment]
0x01 0x03 is probably the on/off

>I can switch the on-state between false and true but the contact wires at the device stay always open.

This is not normal ... You switch the device manualy, but the wire stay open ?

This device used the tuya cluster need to try something like for this one https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5869 
Explanation here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5868

The dpid to use for config/on is 3

**Comment by rafaelcorvalan** [comment]
I'm having issues with this device too. I have 1 device, 2 entities which are sensors, no switch. Any idea ?

```
    "entities": [
      {
        "entity_id": "sensor.tze200_wfxuhoea_ts0601_0f1e399a_basic_rssi",
        "name": "_TZE200_wfxuhoea TS0601"
      },
      {
        "entity_id": "sensor.tze200_wfxuhoea_ts0601_0f1e399a_basic_lqi",
        "name": "_TZE200_wfxuhoea TS0601"
      }
    ],

```

**Comment by Smanar** [comment]
Hello, can you give at least a DDF skeleton ?
- Configure the basic cluster identification (if not auto filled)
- Drag and drop a "on off light"
- Drag and drop a ZHAdoorsensor
- save the file, and remeber the path to edit it later
- share the DDF.

**Comment by dustnipe** [comment]
Thanks to your comment @Smanar, I managed to get the sensor to work. (Even though I don't really understand what I do :P)

I added the ZHAOpenClose template in DDF to the device with the following parameters
`        {
          "name": "state/open",
          "refresh.interval": 3,
          "parse": {
            "dpid": 3,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          }`
DPID 3 is showing the status of the magnetic door sensor and does work now. Which is great!

But I still have no clue on how to really switch the device to open/close the garagedoor. Any further suggestions?

**Comment by Smanar** [comment]
>DPID 12 (0x0C) is the right one to control the door signal.

I m not sure, because 0x04 mean the value is a number not a bool, from other project they are using 0x01 but as toggle command not on/off, so will see the result

>But now I have an on/off switch and when I trigger it (no matter if on or off) the device will send the door signal which is 3s on and then off

Else I don't realy understand what happen with the dpid = 12

Make a try with the 0x01 to check if it s better.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_wfxuhoea",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/open",
          "refresh.interval": 7200,
          "parse": {
            "dpid": 3,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          }
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 1, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "tuya"},
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```
