### ISSUE TITLE
Add 3A Nue Smart Door Sensor (Feibit FB56-DOS06HM1.1)

### ISSUE THREAD

**Issue by paulharken** [dresden-elektronik/deconz-rest-plugin#5688]
Hello

First time request here! Just want to say thank you dresden for all the hard work you do. I've been able to setup our home the way we want with a lot of different devices and this is the first time I've encountered any issues. Closed Issue #4400 seems very close to it however the device I have is model "FB56-DOS06HM1.1", whereas issue 4400 has it listed as "FB56-DOS06HM1.3"

Device is branded as a "3A/Nue ZigBee Smart Door Sensor", model "HGZB-13A". Paired it using Phoscon GW web interface via the sensor panel and it didn't show up as a sensor; it shows up as a "warning device" under lights. It gets sent over to HomeAssistant as well but shows up as a siren, not a door sensor (assuming because deconz is reading it as part of an intrusion alarm system?).

Screenshots below of what information I can gather. If I can gather any more information for you, please do let me know! 

**Node info**
<img width="766" alt="Node" src="https://user-images.githubusercontent.com/97880218/150485851-f76f6ea8-201b-4811-b823-0678a31b77ac.png">

**Basic Cluster**
<img width="397" alt="Basic Cluster" src="https://user-images.githubusercontent.com/97880218/150485913-79d730ee-da63-4e9e-9f97-0c3ba36c60da.png">

**Identify Cluster**
<img width="856" alt="Identify Cluster" src="https://user-images.githubusercontent.com/97880218/150485926-15aeb4b7-5bfc-4097-a113-61b3ca8a09b2.png">

**IAS WD Cluster**
<img width="453" alt="IASWD Cluster" src="https://user-images.githubusercontent.com/97880218/150485937-99581f74-b38b-44b6-b891-ace83b85d4d4.png">

**IAS Zone Cluster**
<img width="466" alt="IAS Zone Cluster" src="https://user-images.githubusercontent.com/97880218/150485962-46a6c4d6-5e46-4f58-9fb1-d78a225c2e78.png">

**Comment by paulharken** [comment]
Not stale.

**Comment by paulharken** [comment]
Still open

**Comment by Mimiix** [comment]
Sure

**Comment by paulharken** [comment]
Still open

**Comment by paulharken** [comment]
Still open

**Comment by paulharken** [comment]
Still waiting

**Comment by Mimiix** [comment]
@Smanar  can this be done with ddf?

**Comment by Smanar** [comment]
I think yes, can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Feibit,co.ltd",
  "modelid": "FB56-DOS06HM1.1",
  "vendor": "3A/Nue",
  "product": "Smart Door Sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open"
        }
      ]
    },
    {
      "type": "Warning device",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```
