### ISSUE TITLE
Get 'added' signals for all types in deconz over web socket

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#569]
Hi @manup !

I'd like to support live additions of new devices, groups, etc. in home assistant. But there seems to be many cases that aren't supported today to signal the 'added' or 'deleted' key over web sockets. Do you think this could be possible to support?

**Comment by manup** [comment]
Yes I also think this is very useful, currently sensors do emit this added event, not sure about lights. I put it on the todo list.

**Comment by Kane610** [comment]
I'm about to get initial support for sensors integrated to HASS.
Just need lights, groups and scenes now 👍🏻

**Comment by Kane610** [comment]
Oh! Also: I noticed that sensors with battery doesn't report battery on added, IA that device dependent or is that something that gets reported later?

**Comment by manup** [comment]
In case of the Xiaomi sensors I think either they don't send this report early on or also likely it it received before the sensor resource is initially created, hence the delay of up to one hour until next report is received.

**Comment by Kane610** [comment]
@manup any eta on this? From an outside perspective it shouldn't be that extensive to add lights and groups to do this signalling.

**Comment by manup** [comment]
Hmm I thought lights already announce this via websocket &mdash; state/reachable?
I need to check it :)

**Comment by manup** [comment]
Also as a side note, deCONZ 2.05.37 will load all lights directly after start not waiting for them to be discovered.

**Comment by Kane610** [comment]
@manup thats a good improvement for deconz with loading all lights directly!

I haven't seen any notification for new lights over websocket
