### ISSUE TITLE
MOES BHT-002GBLZB Thermostat

### ISSUE THREAD

**Issue by MrTh0m** [dresden-elektronik/deconz-rest-plugin#5693]
## Device
- Product name: MOES BHT-002GBLZB 
- Manufacturer: _TZE200_aoclfnxz
- Model identifier: TS0601
- Device type : router

## Screenshots
![image](https://user-images.githubusercontent.com/20833022/150633919-93efc268-8d57-4780-968c-4cb23e11a2e4.png)
![image](https://user-images.githubusercontent.com/20833022/150633911-7ee7ced9-827b-47ae-a2db-d6a1593b67d6.png)

### Basic
![image](https://user-images.githubusercontent.com/20833022/150633902-db678255-9f84-4eb4-8d37-b65081f39483.png)
### Groups
![image](https://user-images.githubusercontent.com/20833022/150633705-4cc16b2b-454e-464c-b280-8fa29e445f2a.png)
### Scenes
![image](https://user-images.githubusercontent.com/20833022/150633712-a7af7f8d-f6bc-4204-ab3d-0f319160c72a.png)
### Tuya specific Cluster
no attributes
### OTAU
![image](https://user-images.githubusercontent.com/20833022/150633841-aedde2e4-02f0-4e84-9937-046e80057fcc.png)
### TIME
no attributes

**Comment by Smanar** [comment]
It's not this one ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5468

**Comment by MrTh0m** [comment]
> It's not this one ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5468

It seem, yes. I've looking for but not found. 
So is that mean is already supported ?

**Comment by Smanar** [comment]
Yeap, but with tuya all is possible (they changes lot of thing regulary), so you can have issue.
The device can need 2 inclusions and can be invisible on phoscon, you need to check direclty the API (phoscon/help/API information) or use a third app.

**Comment by MrTh0m** [comment]
Exactly,
At 1st pairing  the thermostat was seen but cannot do lot on Home Assistant. 
At 2nd pairing, after deleting the object. thermostat is seen, i've perform a reboot of deconz and then i don't see it anymore.
It is remain on HA. I can 
- Up or down the degrees 
- Shutdown completly the thermostat
- Switch on screen light
but that is all

**Comment by MrTh0m** [comment]
Thanks you for the API's page, never going here before. 
So for my thermostat, i see that :

       "22": {
            "config": {
                "heatsetpoint": 1900,
                "locked": false,
                "mode": "heat",
                "offset": -300,
                "on": true,
                "preset": "program",
                "reachable": true,
                "schedule": {},
                "schedule_on": false,
                "setvalve": false
            },
            "ep": 1,
            "etag": "7c32a10f3bb08bf413be2e2926023b4a",
            "lastannounced": "2022-01-22T14:30:44Z",
            "lastseen": "2022-01-23T09:23Z",
            "manufacturername": "_TZE200_aoclfnxz",
            "modelid": "TS0601",
            "name": "Thermostat 22",
            "state": {
                "lastupdated": "2022-01-23T08:58:43.219",
                "on": false,
                "temperature": 1650
            },
            "type": "ZHAThermostat",
            "uniqueid": "8c:f6:81:ff:fe:56:74:63-01-0201"
        }

**Comment by Smanar** [comment]
You can use config/preset with "auto" and "program"
You have the childlock config/locked
You have the config/mode with "off" and "heat"

**Comment by MrTh0m** [comment]
You mean, i need to append some values ?

**Comment by Smanar** [comment]
Heu not append, edit, you need to use thoses fields to control the device, if I m right you have a combo somewhere in HA to control the preset for exemple, for mode it's on widget bottom. For childlock  IDK where you can see it in HA, but the device have it.

**Comment by MrTh0m** [comment]
Yes, i've widget to control HAVC but goes wrong. Only 
- up or down temperature work
- and shutdown or turn on thermostat.
The others function fail.

HA discover well the thermostat from Deconz but all funtion or preset don't work.

Below, what HA know from thermostat :

> hvac_modes:
>   - auto
>   - heat
>   - 'off'
> min_temp: 7
> max_temp: 35
> preset_modes:
>   - auto
>   - boost
>   - comfort
>   - complex
>   - eco
>   - holiday
>   - manual
> current_temperature: 17.5
> temperature: 18
> preset_mode: null
> offset: -300
> locked: false
> friendly_name: Thermostat 22
> supported_features: 17

For eg, below when i hit "confort" preset, i've issue :

![image](https://user-images.githubusercontent.com/20833022/151653322-3e62b60f-52c6-4ec5-ad1b-bdf9af9b474f.png)

**Comment by Smanar** [comment]
>You can use config/preset with "auto" and "program"

You have not the "program" preset somewhere ? or can use custom one ?

>You have the config/mode with "off" and "heat"

Here I think "desactivé" and "marche forcée" will work.

Yo have the childlock in HA
>locked: false


Sorry, but all tuya TRV/thermostat are differents, and they have all differents features, it s hard for the HA plugin to make a widget compatible for all possible stuff.
