### ISSUE TITLE
MOES - TV01 Zigbee Thermostat Radiator Valve

### ISSUE THREAD

**Issue by nukleuz80** [dresden-elektronik/deconz-rest-plugin#5697]
Hello,

can you please add the following device?
After pairing as sensor i get three new sensors (temperature, humidity and alarm)

## Device

- Product name: MOES - TV01 Zigbee Thermostat Radiator Valve
- Manufacturer: _TZE200_e9ba97vf
- Model identifier: TS0601
- Device type : 
  - Thermostat

## Screenshots

  Required screenshots:
  - Endpoints and clusters of the node
  
![image](https://user-images.githubusercontent.com/43496030/150655739-83b00b62-cf06-4464-8379-b8cd874554a8.png)

  - Node Info panel
  
![image](https://user-images.githubusercontent.com/43496030/150655760-10650a67-41cf-4ac3-96d5-787babc763a3.png)

### Basic
![image](https://user-images.githubusercontent.com/43496030/150655823-768a5d40-0b07-430c-a528-0fe74fa6584b.png)

### Groups
![image](https://user-images.githubusercontent.com/43496030/150655877-824e3e87-eced-48eb-9c0e-56095c75718b.png)
![image](https://user-images.githubusercontent.com/43496030/150655892-6a4a0fd9-fff2-4013-9460-fcbc636c038c.png)

### Scenes
![image](https://user-images.githubusercontent.com/43496030/150655908-25320fc6-1371-499d-b398-0d05e6078123.png)
![image](https://user-images.githubusercontent.com/43496030/150655926-12a785d0-a7b8-4c92-9ef7-7ce00734f958.png)
![image](https://user-images.githubusercontent.com/43496030/150655938-bc5203c1-e8f8-439e-b00b-ee7782766370.png)
![image](https://user-images.githubusercontent.com/43496030/150655951-1e8a2a2c-0481-4837-83b7-166325e29118.png)

### Tuya Specific Cluster
![image](https://user-images.githubusercontent.com/43496030/150655972-0abf0192-dab6-4a11-a222-19f22b905a8a.png)

The three sensors from the API after pairing:

`{
    "config": {
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "aa0bbe17dbde1c62bb33e00ddd90250e",
    "lastannounced": "2022-01-22T17:00:17Z",
    "lastseen": "2022-01-22T21:21Z",
    "manufacturername": "_TZE200_e9ba97vf",
    "modelid": "TS0601",
    "name": "Temperature 112",
    "state": {
        "lastupdated": "none",
        "temperature": null
    },
    "type": "ZHATemperature",
    "uniqueid": "2c:11:65:ff:fe:c6:1c:47-01-0402"
}`

`{
    "config": {
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "edf815f1d0438673e184b987706adaf3",
    "lastannounced": "2022-01-22T17:00:17Z",
    "lastseen": "2022-01-22T21:21Z",
    "manufacturername": "_TZE200_e9ba97vf",
    "modelid": "TS0601",
    "name": "Humidity 113",
    "state": {
        "humidity": null,
        "lastupdated": "none"
    },
    "type": "ZHAHumidity",
    "uniqueid": "2c:11:65:ff:fe:c6:1c:47-01-0405"
}`

`{
    "config": {
        "enrolled": 0,
        "humiditymaxthreshold": null,
        "humidityminthreshold": null,
        "melody": null,
        "on": true,
        "pending": [],
        "preset": null,
        "reachable": true,
        "temperaturemaxthreshold": null,
        "temperatureminthreshold": null,
        "volume": null
    },
    "ep": 1,
    "etag": "2d7824e88ceba17184533a1493c70484",
    "lastannounced": "2022-01-22T17:00:17Z",
    "lastseen": "2022-01-22T21:21Z",
    "manufacturername": "_TZE200_e9ba97vf",
    "modelid": "TS0601",
    "name": "Alarm 114",
    "state": {
        "alarm": null,
        "lastupdated": "none"
    },
    "type": "ZHAAlarm",
    "uniqueid": "2c:11:65:ff:fe:c6:1c:47-01-0500"
}`

**Comment by Smanar** [comment]
This is not in the code at all, no clones, nothing, and as the moment lot of thing are locked, I think this device will be not included before some time, sorry.

**Comment by PastCoder** [comment]
@nukleuz80 Did you find meanwhile any way to make the _TZE200_e9ba97vf work? I am asking because I am as well trying to figure out how to make it work in deconz (and iobroker). I see it in the deconz GUI but nowhere else. 
Maybe there are now more people interested so that I could make sense to raise the request again!?

**Comment by Smanar** [comment]
Nothing will move before this PR will be merged https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054
The next step in deconz will be propably TRV.

**Comment by nukleuz80** [comment]
> @nukleuz80 Did you find meanwhile any way to make the _TZE200_e9ba97vf work? I am asking because I am as well trying to figure out how to make it work in deconz (and iobroker). I see it in the deconz GUI but nowhere else. 
> 
> Maybe there are now more people interested so that I could make sense to raise the request again!?

No, i sent it back and baught a new one which is compatible...
