### ISSUE TITLE
How do I get the straight lines between nodes?

### ISSUE THREAD

**Issue by Einar-S** [dresden-elektronik/deconz-rest-plugin#570]
After a recent update of deCONZ the lines became arcs that converge into a single thick line entry to the nodes. It is not possible anymore to see how they connect! Is there a setting to get back the old "ratsnest" look? I am used to the utility of ratsnests from PCB layout and prefer this.

Thank you.
Einar

**Comment by manup** [comment]
The code is still there, I'll put a config option to enable it on the todo list.
