### ISSUE TITLE
Aeotec Smart Plug (AU)

### ISSUE THREAD

**Issue by rohrsh** [dresden-elektronik/deconz-rest-plugin#5700]
## Device

- Product name: Aeotec Smart Plug
- Manufacturer: LDS
- Model identifier: ZB-ONOFFPlug-D0005
- Device type: Switch (with power monitoring)

This is an Australian 240v smart plug. 
https://www.smarthome.com.au/smartthings-smart-plug.html

I have the same situation as this query from 2019: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2121
The device registers just fine as an on/off plug, **but no power monitoring.** 

I thought the device was identical to the "Samsung SmartPlug 2019 Model ID: 7A-PL-Z-J3" but I don't see the power measurements coming through to Home Assistant. 

Thanks for any help. Happy to provide more information. 

## Screenshots

Node:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/38928979/150673968-16fc360b-7f25-40c2-9299-e26e8536362f.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/38928979/150673887-639e43e5-e705-435e-8ffd-3a11926d8ecd.png">

Basic cluster:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/38928979/150711455-cbe5ffd0-4e78-45bb-8f91-dd3553895d5e.png">

Identify:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/38928979/150711526-063c4abe-7daf-45e5-82fe-2dd849fc878a.png">

On/off:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/38928979/150711611-c9106ff7-14c7-493f-be20-9dc0a6d0315f.png">

Simple metering:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/38928979/150712060-f12b0d4e-7d67-4e7a-97f7-c88dd088e50a.png">

Electrical measurement: 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/38928979/150711704-04b0f40a-7e41-4677-acc9-4142bf689ffe.png">

OTAU: 

<img width="646" alt="image" src="https://user-images.githubusercontent.com/38928979/150711756-2fd920c4-3ab3-411d-adeb-297e051c187d.png">

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by rohrsh** [comment]
Screenshots updated. Please let me know if any information is still missing. My apologies for any errors, this is my first device submission. Thank you!

**Comment by Mimiix** [comment]
Looks good, thanks :)

**Comment by cammurray** [comment]
@rohrsh by rebooting, do you mean rebooting the device, deconz, or hass? My device is stuck showing the on/off but no power monitoring. Have reset deconz and hass a couple of times but don’t get the sensor showing.

**Comment by rohrsh** [comment]
Actually I'm not sure. All I know is that I didn't change any part of the Aeotec device config and a couple of days later I started getting power reports in Home Assistant. During that time I did work on other items and reboot my Home Assistant. 

In a troubling turn of events, I did Zigbee remove and then re-add my device in another part of my house and after 24 hrs still hasn't started any power monitoring. 

So there's room for improvement with this device

**Comment by cammurray** [comment]
Interesting, mine has been up for about 3-4 days now, but I'm not getting anything in home assistant yet. deCONZ GUI seems to be able to read the data if I click the read button.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/26195772/154403207-76e6cac9-43d7-4622-a4b0-099ddaecd5c7.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/26195772/154403287-b97d3134-f93d-4d88-9d01-4eec78ca7b2b.png">

**Comment by SwoopX** [comment]
I would normally close this one, as it is indeed 100% identical to the Samsung but I also recall it was painful to have it working back in the days...

I'd recommend to quickly generate a DDF for it, as a fully working one should be generated out of the box. It should be stored at the same location where the other files are residing. Just ensure the status is set to `Gold` instead of `Draft`.

You can also share it here for some tweaking and for it to be integrated in future releases.

**Comment by cammurray** [comment]
Ok. I seem to have found the 'magic sauce' for this one while going through the ~hundred comments on the Samsung equivelant for this device.

When pairing this device, the device adds a 'light' type sensor in deconz but this sensor doesn't expose any power metering through. If you -wait- for the device to go out of pairing mode, and then go to add a new device in deconz, deconz finds another device somehow - it's this second pairing that gives you the power monitoring capabilities. This is.. weird..?

@SwoopX let me know if I can do anything to assist make this a bit easier. I'd be happy to 'generate a DDF' for it, but I don't know what that is :)

**Comment by reg98643t** [comment]
> Ok. I seem to have found the 'magic sauce' for this one while going through the ~hundred comments on the Samsung equivelant for this device.
> 
> When pairing this device, the device adds a 'light' type sensor in deconz but this sensor doesn't expose any power metering through. If you -wait- for the device to go out of pairing mode, and then go to add a new device in deconz, deconz finds another device somehow - it's this second pairing that gives you the power monitoring capabilities. This is.. weird..?
> 
> @SwoopX let me know if I can do anything to assist make this a bit easier. I'd be happy to 'generate a DDF' for it, but I don't know what that is :)

Could you elaborate on what exactly you did to get it to work?

**Comment by cammurray** [comment]
@reg98643t what I did is actually in my comment..

"When pairing this device, the device adds a 'light' type sensor in deconz but this sensor doesn't expose any power metering through. If you -wait- for the device to go out of pairing mode, and then go to add a new device in deconz, deconz finds another device somehow - it's this second pairing that gives you the power monitoring capabilities"

Let me know how that's not clear and I'll try rephrase.

**Comment by reg98643t** [comment]
@cammurray 

For the second device addition, in Deconz did you try to add a light, sensor or switch? How long did you wait after pairing? Did you have anything plugged into the plug and was it drawing power?

Essentially I've tried what you said and it didn't work and I'm wondering if there are some important factors not mentioned.

**Comment by reg98643t** [comment]
I think I might have worked it out, I plugged a light in and left it going then redid the process and it seems to have been the missing link.

**Comment by reg98643t** [comment]
Trying a second one and it hasn't worked, might need to be drawing power for some time before it works?

**Comment by reg98643t** [comment]
Yeah I have not been able to replicate the process for any further plugs.

**Comment by reg98643t** [comment]
@SwoopX how can @cammurray do the DDF thing?

**Comment by reg98643t** [comment]
@SwoopX @cammurray 

I have got it working and I have a working DDF, any idea how I can get the DDF out of the Deconz VM?

**Comment by SwoopX** [comment]
You get a DDF when richt clicking on the respective node (must have been previously selected) and then choose `Edit DDF`. That can be saved at a location of your choice. It should already contain pretty much everything which is required, but the bindings might be an exception (they previously must have been triggered to show up).

I, personally, can always copy and text from/to a VM, be it via ssh, vnc, or just vmware workstation 🤷‍♂️ 

Would be great to share it here upfront to check it for completeness.

**Comment by SwoopX** [comment]
Hm, from what I can tell, the DDF should more look like the innr SP 120, except for the first few lines of course
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/innr/sp_120.json

**Comment by rohrsh** [comment]
Still unresolved as far as I am aware

**Comment by reg98643t** [comment]
Sorry guys, I have it working perfectly for myself but I have no way to share it yet.

**Comment by rohrsh** [comment]
Zzzzzzzzz

**Comment by reg98643t** [comment]
Sorry all haven't had time to try and work out how to share it yet

**Comment by nemccarthy** [comment]
Any luck on this?

**Comment by Smanar** [comment]
Try this DDF
```

{
  "schema": "devcap1.schema.json",
  "manufacturername": "LDS",
  "modelid": "ZB-ONOFFPlug-D0005",
  "vendor": "Aeotec",
  "product": "Aeotec Smart Plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "refresh.interval": 360,
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "eval": "Item.val = Attr.val * 10;"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "refresh.interval": 360
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by Man-Grove** [comment]
This worked for me, including power metering, at the second pairing (the initial didn't work). However, it's identified as a light and not as a plug, which is very weird (and wrong?). It's the only plug I have that's identified as a light.

**Comment by Man-Grove** [comment]
Disregard that -- I don't have the same version...
