### ISSUE TITLE
Aqara P1 Door & Window Sensor

### ISSUE THREAD

**Issue by ads1230** [dresden-elektronik/deconz-rest-plugin#5703]
## Device

- Product name: Aqara P1 Door & Window Sensor
- Manufacturer: Aqara
- Model identifier: MCCGQ13LM (lumi.magnet.ac01)
- Device type : Sensor

## Screenshots
<img width="296" alt="Screenshot 2022-01-15 at 17 07 33" src="https://user-images.githubusercontent.com/53495346/150684924-b3dcdb9a-c647-41b1-9906-ca30a65d5e60.png">

### Basic
<img width="401" alt="Basic CLuster" src="https://user-images.githubusercontent.com/53495346/150684938-aeca5f29-2b1d-455c-aee5-26addb290713.png">

### Identify
<img width="401" alt="Indent cluster" src="https://user-images.githubusercontent.com/53495346/150684945-2791c21d-ca1e-49a4-9022-8aeba57d015e.png">

### IAS Zone
<img width="401" alt="IAS Zone Cluster 2" src="https://user-images.githubusercontent.com/53495346/150684975-97ae97ee-7092-4afb-a022-7def5981cddc.png">
<img width="401" alt="IAS Zone Cluster" src="https://user-images.githubusercontent.com/53495346/150684977-5017d043-2c0f-448a-8e45-fab0db925dfd.png">

### Power Configuration
<img width="401" alt="power config" src="https://user-images.githubusercontent.com/53495346/150684996-092cc473-ea92-4fc9-a500-e78b012b3cc0.png">

### OTAU
<img width="393" alt="otau" src="https://user-images.githubusercontent.com/53495346/150685007-8c898ad8-b9c8-40fe-a2d3-6f83878fa9fc.png">

### Node info
<img width="393" alt="node info" src="https://user-images.githubusercontent.com/53495346/150685019-84ef282e-1041-4d1d-9484-021e18122503.png">

**Comment by ads1230** [comment]
Hey! Just updated my Conbee II fw and its showing different clusters

### On/Off
<img width="852" alt="Screenshot 2022-01-26 at 14 51 02" src="https://user-images.githubusercontent.com/53495346/151189818-502c2764-c02f-47bd-9372-3294d2a5f629.png">

### Lumi Specific Cluster 
<img width="424" alt="Screenshot 2022-01-26 at 14 51 33" src="https://user-images.githubusercontent.com/53495346/151189815-60f89f22-08aa-4364-9eb4-b1492f6db6bd.png">

### Node Info
<img width="372" alt="Screenshot 2022-01-26 at 14 53 40" src="https://user-images.githubusercontent.com/53495346/151189799-fa5983ac-b26b-4d23-a823-f99db879635f.png">

### Basic Cluster
<img width="462" alt="Screenshot 2022-01-26 at 14 53 20" src="https://user-images.githubusercontent.com/53495346/151189806-e200c51f-e610-40ac-810c-a416348c44dc.png">

### Identify
<img width="400" alt="Screenshot 2022-01-26 at 14 52 53" src="https://user-images.githubusercontent.com/53495346/151189809-5167c058-f5e4-4bfa-b1fc-5e428514f2f1.png">

### IAS Zone
<img width="463" alt="Screenshot 2022-01-26 at 14 52 36" src="https://user-images.githubusercontent.com/53495346/151189811-1712d5a4-54df-4f31-8725-556b1be7712e.png">

### Power Configuration
<img width="394" alt="Screenshot 2022-01-26 at 14 52 13" src="https://user-images.githubusercontent.com/53495346/151189813-2ab6cd6d-9ed1-4b1b-a529-53ebd64c548c.png">

### OTAU
<img width="455" alt="Screenshot 2022-01-26 at 14 56 06" src="https://user-images.githubusercontent.com/53495346/151189793-de47da65-1e84-49f2-ba55-03d5b695c600.png">

**Comment by SwoopX** [comment]
Please try the DDF approach:

- take the file from this repo: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json
- Change the modelID in line 4 to lumi.magnet.ac01
- Change the product ID in line 6 to MCCGQ13LM
- Save the file as xiaomi_mccgq13lm_openclose_sensor.json locally
- Find the file referenced in the first bullet on your system and copy the just created file for your device to the exact same folder
- Restart deconz, reset the device and re-pair

**Comment by ads1230** [comment]
> Please try the DDF approach:
> 
> * take the file from this repo: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json
> * Change the modelID in line 4 to lumi.magnet.ac01
> * Change the product ID in line 6 to MCCGQ13LM
> * Save the file as xiaomi_mccgq13lm_openclose_sensor.json locally
> * Find the file referenced in the first bullet on your system and copy the just created file for your device to the exact same folder
> * Restart deconz, reset the device and re-pair
> * If it works, please share the file for integration

Thanks. Added the DDF (and updated to latest docker version).
Appears as an open/close sensor now but the state does not change when opened/closed.
Also seems to now appear as a "smart plug" which powers off when the sensor is closed (and on when open).
Tried resetting multiple times but has the same effect.

<img width="231" alt="Screenshot 2022-01-29 at 17 05 00" src="https://user-images.githubusercontent.com/53495346/151670225-0b39f010-32ca-4945-b648-543d68245d89.png">
<img width="821" alt="Screenshot 2022-01-29 at 17 05 26" src="https://user-images.githubusercontent.com/53495346/151670234-2609584d-cd38-4054-bbbf-7f0285584561.png">
<img width="710" alt="Screenshot 2022-01-29 at 17 05 49" src="https://user-images.githubusercontent.com/53495346/151670237-bd0864c6-a5dd-488a-a57d-bb8055bcf746.png">
<img width="992" alt="Screenshot 2022-01-29 at 17 06 15" src="https://user-images.githubusercontent.com/53495346/151670246-3c66accc-1f89-4c0b-b784-b591ea666d41.png">

**Comment by SwoopX** [comment]
Oh man... A typical Xiaomi again...

Can you please check if the IAS Zone clusters Alarm 1 box changes upon open/close?

**Comment by ads1230** [comment]
> Oh man... A typical Xiaomi again...
> 
> Can you please check if the IAS Zone clusters Alarm 1 box changes upon open/close? Eventually, it helps to restart deconz once more (some folks reported the LM14 then started to work).

No luck even after reboot, only value which changes is the onoff state from false (closed) to true

<img width="447" alt="Screenshot 2022-01-29 at 23 04 20" src="https://user-images.githubusercontent.com/53495346/151680409-e26fa7bc-bc30-4110-baba-242d1c6f7115.png">

![ezgif-6-f3c5520422](https://user-images.githubusercontent.com/53495346/151680414-53b455bf-14dc-45cd-baf8-29592e8f3373.gif)

**Comment by SwoopX** [comment]
Hm, next option to try would be in the lluni specific cluter (0xfcc0) to set attribute 0x0009 from (presumably) 0 to 2. As to my experience, this sets devices into some sort of "more zigbee comliant" mode, but it doesn't necessarily work for all devices (e.g. the LM14). Eventually, you need to re-read the simple descriptors are having done so (right click on the node).

**Comment by ads1230** [comment]
> Hm, next option to try would be in the lluni specific cluter (0xfcc0) to set attribute 0x0009 from (presumably) 0 to 2. As to my experience, this sets devices into some sort of "more zigbee comliant" mode, but it doesn't necessarily work for all devices (e.g. the LM14). Eventually, you need to re-read the simple descriptors are having done so (right click on the node).

Changing the value to 2 removed the onoff, Lumi specific and groups clusters.
the IAS Zone Status changes from 0x0020 to 0x0021 when open, but not automatically (has to be read).

<img width="303" alt="Screenshot 2022-01-30 at 10 26 49" src="https://user-images.githubusercontent.com/53495346/151696041-de87349a-a3b3-4ef2-bbc5-c537c1f5cd21.png">

![ezgif-3-97a20bd239](https://user-images.githubusercontent.com/53495346/151696070-ef012ebb-26ff-4384-b141-12568ca9bafb.gif)

**Comment by SwoopX** [comment]
Ok, looks like it's getting warmer and just the IAS Zone cluster binding is missing. Please follow https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel , but only step 1 (so spare the attribute report configuration).

**Comment by ads1230** [comment]
Not much going on after dragging the cluster to the binding panel.

<img width="1149" alt="Screenshot 2022-01-30 at 16 39 17" src="https://user-images.githubusercontent.com/53495346/151708543-afd21f3e-43ab-411e-996d-e217be3e8dd0.png">

**Comment by SwoopX** [comment]
Hm, do you run Conbee/Raspbee II firmware version 0x26720700?

Eventually, it would help if you'd write instead of 2 here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5703#issuecomment-1025014334 otherwise I wouldn't really know how to get it to work properly.

**Comment by ads1230** [comment]
> Hm, do you run Conbee/Raspbee II firmware version 0x26720700?

Hey, yes my Conbee II stick is on 0x26720700
I've tried numerous resets/re-pairing but no luck.

> Eventually, it would help if you'd write instead of 2 here [#5703 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5703#issuecomment-1025014334) otherwise I wouldn't really know how to get it to work properly.

Hmm is there a different value to 2 that could work?
When opening / closing the sensor the only value which seems to change from false to true is the onoff attribute of the onoff cluster. Would it be possible to use this for open close?

**Comment by ads1230** [comment]
> Argh, doesn't really help to mention to do something without telling what... Known valid values for attribute 0x0009 are:
> 
> * 1: Let's call that compatibility mode
> * 2: Let's call it (more) zigbee mode
> * 3: Apparently some very Xiaomi specific behavior, if you can call it like that at all
> 
> It's interesting that quite some folks mentioned lately that also the E1 open/close sensor shows a similar behavior, which is remarkable since I had it in hands for intergration and it simply worked out of the box with the DDF. Apparently, there's more to explore/investigate.

Ahh makes sense, thanks. 
1 didn't do much, the IAS zone didn't change with open close. 
3 had similar behaviour to 2 - the IAS zone changed but not automatically - only on read.
It seems we're at a dead end, unless you'd be willing to let me post you a device?

**Comment by ads1230** [comment]
> Ok. Well, then please set it back to 2.
> 
> Looks like we are getting somewhere on the E1... Check out https://forum.phoscon.de/t/can-not-add-aqara-window-and-door-sensor-to-phoscon/1423/27?u=swoop
> 
> Can you please follow Smanar's advice a little down below?

Thanks.

Finding similar results to wosch

**Open**
21:34:40:699 [IAS ZONE] - Address 0x54EF44100018AA90, Payload 0000003000010000311500020000192100100000f00000000000000000, Command 0x01
21:34:40:700 [IAS ZONE] - 0x54EF44100018AA90 No IAS sensor found for endpoint: 0x01
21:34:41:692 [IAS ZONE] - Address 0x54EF44100018AA90, Payload 11000020ff, Command 0x01
21:34:41:694 [IAS ZONE] - 0x54EF44100018AA90 No IAS sensor found for endpoint: 0x01

**Closed**
21:35:31:559 [IAS ZONE] - Address 0x54EF44100018AA90, Payload 0000003000010000311500020000192000100000f00000000000000000, Command 0x01
21:35:31:561 [IAS ZONE] - 0x54EF44100018AA90 No IAS sensor found for endpoint: 0x01
21:35:32:557 [IAS ZONE] - Address 0x54EF44100018AA90, Payload 11000020ff, Command 0x01
21:35:32:559 [IAS ZONE] - 0x54EF44100018AA90 No IAS sensor found for endpoint: 0x01

**Comment by SwoopX** [comment]
HAve you run a new sensor search while opening and closing the device? If not, please do so. Curious to learn if this already does the trick.

**Comment by SwoopX** [comment]
Got it and that's really odd. I'd assume you have a sensor automatically created? Should look like this: https://forum.phoscon.de/t/can-not-add-aqara-window-and-door-sensor-to-phoscon/1423/22?u=swoop (1st screenshot).

**Comment by ads1230** [comment]
> Got it and that's really odd. I'd assume you have a sensor automatically created? Should look like this: https://forum.phoscon.de/t/can-not-add-aqara-window-and-door-sensor-to-phoscon/1423/22?u=swoop (1st screenshot).
> 
> **EDIT:** Could you give this a try? https://forum.phoscon.de/t/can-not-add-aqara-window-and-door-sensor-to-phoscon/1423/34?u=swoop

DING DING WINNER!

So attribute 0x0009 = 2
Added
```
{
          "name": "config/enrolled",
          "public": false,
          "description": "State of IAS enrollment process.",
          "default": 1
        },
```
The attribute doesn't change automatically but the Zone Status updates.

Only things left are to get the correct battery status and to make it an Open/Close sensor only with no smart plug.
Currently when I pair the device it appears as a smart plug, then when I pair it a second time (without deleting) updates to an Open/Close sensor but doesn't delete the smart plug entry.

![ezgif-2-454eb736a7](https://user-images.githubusercontent.com/53495346/153732472-08ff7a81-387c-4f7b-9a0f-dcc7b0a0e4d7.gif)
![ezgif-2-0832015fa9](https://user-images.githubusercontent.com/53495346/153732473-d9d8adf4-bafa-4bd6-ac17-43d3de9baf3c.gif)

**Comment by SwoopX** [comment]
Nice.

So with the battery, you could also try to make a binding (the E1 just ignores it and sends without it) on 0x0020 attribute (should be voltage). I'd recommend to set something like min 60, max 60, change 1 for testing, so this should result in battery reports coming in every minute.

I guess the light should be deletable via API, gotta check if it requires any special parameters...

**Comment by joshefin** [comment]
I would like for this sensor to be supported. Can I do something to help?

**Comment by Mimiix** [comment]
> I would like for this sensor to be supported. Can I do something to help?

You can use the DDF shared here, or perhaps @ads1230 can share his and we can get a PR.
