### ISSUE TITLE
Request to add Mini Zigbee Switch TMZ02

### ISSUE THREAD

**Issue by mielikki33** [dresden-elektronik/deconz-rest-plugin#5709]
## Device

- Product name: Tuya_TMZ02L
- Manufacturer: _TZ3000_txpirhfq
- Model identifier: TS0011
- Device type : 
  - Switch (2 gangs)

Reference : https://zigbee.blakadder.com/Tuya_TMZ02L.html

### Basic
![TMZ02](https://user-images.githubusercontent.com/81194364/150929076-8e6efea1-4023-47e3-8063-eb029eac667d.PNG)
![basic](https://user-images.githubusercontent.com/81194364/150929096-6abc057b-5a05-4635-9513-4fe0e5811ab9.PNG)
![node_info](https://user-images.githubusercontent.com/81194364/150929375-329e11e2-0ba0-426c-a880-cea48c8ae9e7.PNG)

### Identify
![identity](https://user-images.githubusercontent.com/81194364/150929117-6fcb32bf-8504-4800-b02d-71156b33a0d6.PNG)

### Groups
![Groups](https://user-images.githubusercontent.com/81194364/150929198-389b7987-8db5-4a86-8971-58157d4ba6aa.PNG)
![Group2](https://user-images.githubusercontent.com/81194364/150929208-27f2e110-6b4a-4d34-bace-f2b1aadeadd7.PNG)

### Scenes
![scene1](https://user-images.githubusercontent.com/81194364/150929233-865eebf0-8989-4bed-9f4a-f0b33429188a.PNG)
![scene2](https://user-images.githubusercontent.com/81194364/150929239-1480035c-d870-4aa8-afb7-e46e06fa0a4c.PNG)
![scene3](https://user-images.githubusercontent.com/81194364/150929240-9c25ec26-a161-44fe-8293-50e6ab70e697.PNG)

### On/Off
![on-off-1](https://user-images.githubusercontent.com/81194364/150929257-5cc5bd65-eddb-4310-87c8-2cfc7efb45bf.PNG)
![on-off-2](https://user-images.githubusercontent.com/81194364/150929261-92e3a1f8-2bf6-4e95-8abb-1977ae10aa46.PNG)

### Otau
![otau](https://user-images.githubusercontent.com/81194364/150929445-9e8bbf94-00be-423b-a598-fd831b672bfb.PNG)

**Comment by Mimiix** [comment]
Can you please update the post with the Model id / manu name? Its in your secondscreen:
![image](https://user-images.githubusercontent.com/43333120/150929698-ae2fe6f0-6d0e-4088-a98a-c0c055bcfcf2.png)

**Comment by mielikki33** [comment]
Thank you, I just updated the post.

**Comment by mielikki33** [comment]
I hope the information is complete for you. I have 11 modules to install in my home, but I cannot pair them in Phoscon with Home Assistant.

thanks in advance

**Comment by Mimiix** [comment]
We need to wait for a dev. But be adviced: It could take a while to be integrated as DDF's aren't yet useable for Switches / Tuya. Even more so: If a dev can help integrate it, you need the possibility to compile yourself (with help of the dev ofc) on a native installation. That being said: You can't do that with the Home Assistant Addon or Docker version.

**Comment by mielikki33** [comment]
OK thanks for your answer. I'm on Raspberry Pi 4 with a Conbee 2 key.

**Comment by ContraNL** [comment]
If there is more information needed for the devs please let us know. I too have multiple units and want to integrate them in Home Assistant.

**Comment by Smanar** [comment]
Hello,
The problem is this device use a new tuya cluster, the 0xe001
We are waiting for the "classic one" the 0xEF00 is supported in the DDF core, so I think this new one will not be supported since long time.

**Comment by ContraNL** [comment]
Do you mean it won’t be supported for a long time or you think it will be supported soon?

**Comment by Smanar** [comment]
It will need more time to be supported (than devices using the classic tuya cluster)

**Comment by ContraNL** [comment]
@Smanar do you know of a similar switch that is supported?

**Comment by Smanar** [comment]
What are you searching ? A module without neutral for 16A ? (16A is a lot for light)

**Comment by ContraNL** [comment]
@Smanar no, with neutral and just for lighting.

**Comment by Smanar** [comment]
So just a module, with neutral, for lightning ? no dimmer ?
You can find some of them in Legrand, Tuya, Aqara, Philips, Sonoff, Loratap, ect ...

**Comment by ContraNL** [comment]
@Smanar, do you have a tuya example that works? I now have multiple units of this device (40 euro’s worth) and they are not working. I don’t want the same to happen seeing I often have to wait 4 weeks to receive them from e.g. aliexpress to find out they are not supported o Phoscon/Home Assistant.

**Comment by ContraNL** [comment]
![E30B22CD-784B-454A-B967-45F7ED56E1AB](https://user-images.githubusercontent.com/74593331/158031486-32c3c18f-2b4a-4bad-8da1-71262841273e.jpeg)

I know this will probably work seeing the dimmers are supported. But I don’t want RF :S

**Comment by Smanar** [comment]
You have for exemple this one with neutral [_TYZB01_iuepbmpv](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3595)

This one with DDF without neutral https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5839

But tuya are cheaper, if you want to paid so much take the philips one, I can see it at 43 euros on amazon.

**Comment by ContraNL** [comment]
@Smanar, [#3595](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3595) is the Moes I was talking about. Even though I don’t want RF, I ordered these now. I rather have support, then not have RF as an option.
I will use these until there is support for the above mentioned units.

Thanks for the information.

**Comment by Smanar** [comment]
I don't see something about RF on the device,, but there is so much tuya clone .....

**Comment by ContraNL** [comment]
![464402EA-FFCB-495E-A93E-4731A9B0C3D9](https://user-images.githubusercontent.com/74593331/158062199-af4d9a5b-4709-44d0-ad6c-54fa0c557dfc.jpeg)
See image, this is the unit mentioned in your first link and mine. These units have zigbee as well as RF and on Aliexpress there is mention of support on Home Assistant, so I hope they will work.

**Comment by Smanar** [comment]
On my first link, I haven't the same https://zigbee.blakadder.com/Moes_MS-104Z-1.html for the _TYZB01_iuepbmpv
It s a classic problem with tuya, even on the same order, you can have different model, visualy same, but not reconized by the same manaufacture name.

**Comment by ContraNL** [comment]
@Smanar, mmm then I hope they will work seeing some people are reporting they do in de comments of the product on aliexpress.

**Comment by Smanar** [comment]
Ha yes, right, I m just seing "wifi" on it.
If you have the manufacture name, I can say if deconz is able to support it or not (if it don't work natively, for exemple if you have one without the tuya cluster), but the problem is you have it only when you connect the device ...

**Comment by ContraNL** [comment]
@Smanar I know… that’s the problem. They should that it on the aliexpress product pages. But we’ll see, I just hope it had thr “classic” cluster so you can help me if it’s not supported 😉
