### ISSUE TITLE
RaspBee firmware upgrade issue

### ISSUE THREAD

**Issue by ausfas** [dresden-elektronik/deconz-rest-plugin#5711]
## Describe the bug
I'm running RaspBee on homeassistant. However, on the Phonscon Web App under decCONZ It says upgrade to firmware version 26390500. After selecting the upgrade success message it still shows the same message that upgrade is available. 
I tried manual upgrade after logging into homeassistant SSH 22222 running following command
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz

It gives me the list of latest firmware and I select deCONZ_Rpi_0x26390500.bin.GCF When it starts flashing it goes in a loop writing:

Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500

and then terminate with this:
retry, failed

2408: Error: uart reset failed, check retry

Flashing Error! Please re-run this script... 

## Steps to reproduce the behavior
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz

-------------------------------------------------------------------

             marthoc/deconz Firmware Flashing Script

                       Version: 0.8

-------------------------------------------------------------------

Listing attached devices...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee

Enter the full device path, or press Enter now to exit.

Device path .: /dev/ttyAMA0

-------------------------------------------------------------------

Firmware available for flashing:
deCONZ_ConBeeII_0x26660700.bin.GCF
deCONZ_ConBeeII_0x26680700.bin.GCF
deCONZ_RaspBeeII_0x26690700.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF
deCONZ_Rpi_0x26390500.bin.GCF

Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from any of the following sources:
 - http://deconz.dresden-elektronik.de/deconz-firmware/         (stable)
 - http://deconz.dresden-elektronik.de/deconz-firmware/beta/    (beta)

If you wish to exit, just hit Enter.

Firmware file: deCONZ_Rpi_0x26390500.bin.GCF

-------------------------------------------------------------------

Device path .: /dev/ttyAMA0
Firmware file: deCONZ_Rpi_0x26390500.bin.GCF
Timeout .....: 60

Are the above values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
retry, failed

2408: Error: uart reset failed, check retry

Flashing Error! Please re-run this script...

## Screenshots
  ![Screenshot 2022-01-26 192555](https://user-images.githubusercontent.com/89455774/151128507-3766db43-f3dd-43e1-a79c-70cd7bee6fb0.png)

## Environment
Version 2.13.04

 - Host system: (Raspberry Pi)
 - Running method: ( Home Assistent deCONZ Add-on )
 - Firmware version: (26xxyy00)
 - deCONZ version:  6.11.1
 - Device: (RaspBee I )

## deCONZ Logs
19:40:16:139 [INFO] - Button maps loaded.
19:40:16:140 found node plugin: libde_rest_plugin.so - REST API Plugin
19:40:16:141 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
19:40:21:469 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
19:40:21:484 LightNode 1: Configuration tool 1 added
19:40:21:493 SensorNode 2 set node 0x90fd9ffffefae888
19:40:21:740 DEV no DDF for 0x90FD9FFFFEFAE888, modelId: TRADFRI remote control
19:40:21:741 DEV create on-the-fly DDF for 0x90FD9FFFFEFAE888
19:40:21:792 dlg action: Read binding table
19:40:21:901 dev /dev/ttyAMA0
19:40:22:563 dev /dev/ttyAMA0
19:40:22:564 COM: /dev/ttyAMA0 / serialno: , RaspBee
19:40:23:591 Announced to internet https://phoscon.de/discover
19:40:23:592 discovery server date: Wed, 26 Jan 2022 08:40:23 GMT
19:40:23:592 	 local time seems to be ok
19:40:23:931 DEV Tick.Init: booted after 8000 seconds
19:40:24:060 Device firmware version 0x26050500 RaspBee
19:40:24:070 unlocked max nodes: 512
19:40:24:214 Device protocol version: 0x0103
19:40:24:366 Current channel 11
19:40:24:391 CTRL got nwk update id 1
19:40:24:399 CTRL ANT_CTRL 0x03
19:40:24:476 Device protocol version: 0x0103
19:40:24:627 CTRL ANT_CTRL 0x03
19:40:31:931 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x26390500.bin.GCF
19:40:31:932 GW firmware version shall be updated to: 0x26390500

## Additional context
I also stopped dCONZ while flashing.
 I have tried this firmware too but same error:
deCONZ_Rpi_0x26400500.bin.GCF

**Comment by ausfas** [comment]
![Screenshot 2022-01-26 192555](https://user-images.githubusercontent.com/89455774/151128815-0da88347-2405-4a1d-b73a-680fd9edc600.png)

**Comment by Mimiix** [comment]
Hi There,


This is a long issue with the addon not able to update the firmware. As we don't maintain the addon, we can't fix it.

The recommended way is to use an native OS and follow this guide: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

Closing this issue.

Kind regards,
Dennis

**Comment by ausfas** [comment]
dCONZ has listed homeassistant  on https://phoscon.de/en/raspbee, however the manual solution is what I tired and has not worked for me so I have raised this issue.

**Comment by Mimiix** [comment]
If it's a user question, you should use the forum as described in #5113
