### ISSUE TITLE
Aqara E1 Water Leak Sensor SJCGQ13LM

### ISSUE THREAD

**Issue by cwm77** [dresden-elektronik/deconz-rest-plugin#5725]
## Device

- Product name: E1 Water Leak Sensor
- Manufacturer: LUMI
- Model identifier: lumi.flood.acn001
- Device type :
  - Sensor

### Basic
<img width="848" alt="Bildschirmfoto 2022-01-29 um 16 19 06" src="https://user-images.githubusercontent.com/9320205/151666503-36a56d84-32a2-4264-8883-ae47db5df4a1.png">
<img width="562" alt="Bildschirmfoto 2022-01-29 um 16 19 46" src="https://user-images.githubusercontent.com/9320205/151666507-8a5655e9-2398-4a85-9ec0-68ca97f888cc.png">

<img width="562" alt="Bildschirmfoto 2022-01-29 um 15 10 03" src="https://user-images.githubusercontent.com/9320205/151664241-62b3e1b1-902b-4319-81a1-897e21c16ac5.png">

### Identify
<img width="567" alt="Bildschirmfoto 2022-01-29 um 15 15 07" src="https://user-images.githubusercontent.com/9320205/151664309-da1e7f92-57e5-4ee8-8b4f-efa75bf69f52.png">

### Alarms
N/A

### Device Temperature
N/A

### Groups
N/A

### Scenes
N/A

### On/Off
N/A

### Level Control
N/A

### Color Control
N/A

### Simple Metering
N/A

### Diagnostics
N/A

### Power Configuration
<img width="524" alt="Bildschirmfoto 2022-01-29 um 16 24 11" src="https://user-images.githubusercontent.com/9320205/151666633-9f385d03-389c-4503-8369-a254b9901ba9.png">

### IAS Zone
<img width="567" alt="Bildschirmfoto 2022-01-29 um 15 20 41" src="https://user-images.githubusercontent.com/9320205/151664678-8c1b96e5-9c5e-4420-97a2-9016295de906.png">

![Bildschirmfoto 2022-02-11 um 17 07 21](https://user-images.githubusercontent.com/9320205/153628048-479cf7fa-5785-42b5-8d75-f4b8e5cc5c35.png)

### Lumi specific
![Bildschirmfoto 2022-02-11 um 17 20 34](https://user-images.githubusercontent.com/9320205/153629212-1fff87ee-0b34-4812-880e-4d0c7e95daa1.png)

![Bildschirmfoto 2022-02-11 um 17 21 03](https://user-images.githubusercontent.com/9320205/153629277-1490a631-9413-40b0-9c74-6c650b39f393.png)

![Bildschirmfoto 2022-02-11 um 17 21 20](https://user-images.githubusercontent.com/9320205/153629297-50312f3e-75dd-42c8-8c48-3075ef42f23d.png)

![Bildschirmfoto 2022-02-11 um 17 21 38](https://user-images.githubusercontent.com/9320205/153629317-c3f4f450-cc89-43d9-9503-30c858417b05.png)

![Bildschirmfoto 2022-02-11 um 17 21 55](https://user-images.githubusercontent.com/9320205/153629329-05367f4f-e727-4ef1-9bc5-87915dff8e37.png)

![Bildschirmfoto 2022-02-11 um 17 22 16](https://user-images.githubusercontent.com/9320205/153629347-fb6d77ce-749b-49f0-8cf3-5559c9c73279.png)

### Identify
<img width="567" alt="Bildschirmfoto 2022-01-29 um 15 22 49" src="https://user-images.githubusercontent.com/9320205/151664745-040d6e59-8175-4b78-910e-a04cd3d08af8.png">

### OTAU
<img width="567" alt="Bildschirmfoto 2022-01-29 um 15 23 02" src="https://user-images.githubusercontent.com/9320205/151664874-796382e3-b505-4fad-9673-50276f1115b3.png">
<img width="567" alt="Bildschirmfoto 2022-01-29 um 15 23 18" src="https://user-images.githubusercontent.com/9320205/151664903-a3ea6104-9bef-4f49-b3cf-4de05c0b9652.png">
<img width="567" alt="Bildschirmfoto 2022-01-29 um 15 41 16" src="https://user-images.githubusercontent.com/9320205/151665224-ed3bf3af-ec1d-4ec6-9970-e8fe2176ef48.png">

**Comment by Mimiix** [comment]
Manufacturer name and model Id in the template are wrong. Please adjust it so it matches the basic cluster.

**Comment by cwm77** [comment]
> Manufacturer name and model Id in the template are wrong. Please adjust it so it matches the basic cluster.

Done

**Comment by SwoopX** [comment]
All screenshots are only showing the default values, so I'm afraid this is not helpful. Please exchange the screenshots with some where all the attributes have been read.

**Comment by cwm77** [comment]
> All screenshots are only showing the default values, so I'm afraid this is not helpful. Please exchange the screenshots with some where all the attributes have been read.

Ok, I updated the screenshots. The clue was to push the button of the sensor while reading. Not every screenshot got changed, but I checked everyone. Please let me know if something is missing.

**Comment by cwm77** [comment]
I wanted to ask if it is already possible to foresee if the integration of this sensor into the software will take a lot of effort and time? According to zigbee.blakadder.com, the two previous models are already supported by Deconz.

https://zigbee.blakadder.com/Aqara_SJCGQ11LM.html
https://zigbee.blakadder.com/Aqara_SJCGQ12LM.html

For this sensor, here is the link, by the way:

https://zigbee.blakadder.com/Aqara_SJCGQ13LM.html

**Comment by SwoopX** [comment]
> ... 100% Zigbee 3.0 compatible
That's the best joke I read since a long time (I'm afraid)

No, the links unfortunately do no help.

**Comment by Mimiix** [comment]
@SwoopX what's missing?

**Comment by SwoopX** [comment]
@Mimiix Read attributes

**Comment by cwm77** [comment]
I would also be interested to know exactly which attributes are the problem now?  I am not a dev, but if I can help in any way, for example testing, please let me know. Hope the laugh I generated didn't knock you off your chair ;) .

**Comment by cwm77** [comment]
> @Mimiix Read attributes

I would also be interested to know exactly which attributes are the problem now? I am not a dev, but if I can help in any way, for example testing, please let me know. Hope the laugh I generated didn't knock you off your chair ;-).

**Comment by Mimiix** [comment]
@SwoopX Which ones?

**Comment by Smanar** [comment]
>What exactly is wrong with it now?

IDK, waiting for SwoopX answer.
But not possible using code for next devices, can use only DDF, so this device will be not included in deconz like the previous one.
And honnestly I have never used the lumi cluster in DDF, so not sure if this device can be added as it ?

**Comment by cwm77** [comment]
> 

Has this something to do with this https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5733 ?

**Comment by Mimiix** [comment]
Yes.

**Comment by cwm77** [comment]
> As already mentioned twice, the attributes from all but 2 clusters have NOT been read.

After Update deCONZ to v2.14.1 read Attributes again. Something changed, HAppy now?

**Comment by 4val0v** [comment]
Is there currently support for this sensor ?

**Comment by SwoopX** [comment]
No, it isn't. However, the subsequently added screenshots appear to be complete now and drafting should be doable. Anybody able to test an initial DDF once ready?
