### ISSUE TITLE
Aqara Wireless Mini Switch WXKG11LM (newest Version) not working (over Phoscon App)

### ISSUE THREAD

**Issue by medicus07** [dresden-elektronik/deconz-rest-plugin#5727]
-->

## Describe the bug
-->
The WXKG11LM switch (I have two of them) is not recognized in Phoscon app neither as switch nor as sensor. The teach-in ends in a timeout. But in deconz web app over VNC appeared the devices as nodes...

## Steps to reproduce the behavior
-->
I tried both switches several times

## Expected behavior
-->
Switch appears as a switch in Phoscon app

## Screenshots
-->
<img width="353" alt="Bildschirmfoto 2022-01-29 um 20 11 09" src="https://user-images.githubusercontent.com/24975901/151674549-f8dca560-4ac2-4cc7-be60-f21baa3752e9.png">
<img width="282" alt="Bildschirmfoto 2022-01-29 um 20 11 49" src="https://user-images.githubusercontent.com/24975901/151674556-a30cc180-1b5b-447d-ba84-6af7f0bc04bc.png">

## Environment
-->
 - Host system: Raspberry Pi 4
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26580700
 - deCONZ version: 2.13.04 / 18.12.2021
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
-->
-

## Additional context
-->
-

**Comment by SwoopX** [comment]
Fixed in 2.14.0 beta
