### ISSUE TITLE
Dresden windows release site

### ISSUE THREAD

**Issue by theendisnye** [dresden-elektronik/deconz-rest-plugin#573]
Is anyone else having problems getting to the Dresden windows release site https://www.dresden-elektronik.de/deconz/win/ or has it moved?

Steve

**Comment by saurabh984** [comment]
Having problems connecting to all of https://www.dresden-elektronik.de

**Comment by alexvandervegt** [comment]
Same here

**Comment by manup** [comment]
Looks like the server has crashed, today is holiday, it should be online again tomorrow morning.

**Comment by manup** [comment]
Short note: the problem still remains, we are working on it..

**Comment by ghdbwise** [comment]
Is it possible to find the .deb-files on another server?

**Comment by ImEmJay** [comment]
Their server is back online. 

I also searched for a mirror for the last days but didn't find any other source.

**Comment by alexvandervegt** [comment]
@manup nice work, can you also post the .deb file for version 25?

**Comment by manup** [comment]
> @manup nice work, can you also post the .deb file for version 25?

Yes will be up till tomorrow :)

**Comment by Fl0ca** [comment]
Is it possible to update the Ubuntu Releases to 25, too?

Thanks :)

**Comment by manup** [comment]
Yes should arrive in a few hours.

**Comment by manup** [comment]
>Is it possible to update the Ubuntu Releases to 25, too?

Took a while, it's online now :)

**Comment by jonathanweinberg** [comment]
This should probably be closed?
