### ISSUE TITLE
Aqara Cube Controller T1 Pro

### ISSUE THREAD

**Issue by ads1230** [dresden-elektronik/deconz-rest-plugin#5732]
## Device
- Product name: Aqara Cube Controller T1 Pro
- Manufacturer: LUMI
- Model identifier: lumi.remote.cagl02 / MFCZQ12LM
- Device type : Magic Cube

## Screenshots
<img width="214" alt="Screenshot 2022-01-30 at 17 12 30" src="https://user-images.githubusercontent.com/53495346/151709954-8a7eedbd-d374-4a89-88a0-04a09cd6cd63.png">

### Basic
<img width="435" alt="Screenshot 2022-01-30 at 17 12 49" src="https://user-images.githubusercontent.com/53495346/151709981-40919f3f-2acb-46d7-b645-849737127e0b.png">

### Identify
<img width="435" alt="Screenshot 2022-01-30 at 17 12 57" src="https://user-images.githubusercontent.com/53495346/151709992-8f417bff-4863-4bdf-acd1-638f9f2b4520.png">

### Power configuration
<img width="435" alt="Screenshot 2022-01-30 at 17 13 13" src="https://user-images.githubusercontent.com/53495346/151710023-2a2f1642-bd0e-4400-b074-63e450a4e6bf.png">

### 01x0012 Multistate Input (Basic)
<img width="435" alt="Screenshot 2022-01-30 at 17 13 24" src="https://user-images.githubusercontent.com/53495346/151710037-0c85175b-23b4-40e3-82e9-98cc8bc0eb2b.png">

### On/Off
<img width="435" alt="Screenshot 2022-01-30 at 17 13 40" src="https://user-images.githubusercontent.com/53495346/151710049-e0d71304-a8e4-417c-b7ac-3861e43525e9.png">

### Lumi Specific
<img width="435" alt="Screenshot 2022-01-30 at 17 14 20" src="https://user-images.githubusercontent.com/53495346/151710062-9f876b4b-ed7f-4588-a6b4-2cdc887420f7.png">
<img width="435" alt="Screenshot 2022-01-30 at 17 14 25" src="https://user-images.githubusercontent.com/53495346/151710057-14c47eff-a685-4715-bffc-3b39b42cd3d3.png">

### 02x0012 Multistate Input (Basic)
![Hnet-image](https://user-images.githubusercontent.com/53495346/151710104-452420e4-78d2-43a5-879e-fe27a3150334.gif)

### 03x0012 Multistate Input (Basic)
![ezgif-7-89e853c834](https://user-images.githubusercontent.com/53495346/151710190-f6ffd524-8af1-4d6d-ba20-57e362337fed.gif)

**Comment by ads1230** [comment]
Apologies for bumping the issue, don’t want it to close.

**Comment by B1n00** [comment]
I observe the same issue with the device

**Comment by mkcologne** [comment]
Put me on the List!

**Comment by SwoopX** [comment]
This PR probably already holds everything for the device https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5838

Testing it would be ideal, which hopefully wouldn't involve any HA and mainly requires placement of the files.

**Comment by B1n00** [comment]
> This PR probably already holds everything for the device #5838
> 
> Testing it would be ideal, which hopefully wouldn't involve any HA and mainly requires placement of the files.

It seems the Model specific to the PRO version is not include in the code: lumi.remote.cagl02 / MFCZQ12LM
Could you update so I can test?

**Comment by fhinder** [comment]
I'm interested as well. 
The old "aqara magic cube" is working, the new one "aqara cube T1Pro"  is not recognised .

**Comment by Doener92** [comment]
Hallo Zusammen, ich habe auch den neue Aqara Cube T1 Pro. Dieser wird leider auch nicht erkannt bzw. ist nicht nutzbar. Hilfe wäre nett.

**Comment by Doener92** [comment]
Is there any update. Can someone help with the problem?

**Comment by SwoopX** [comment]
As said before, the files from the mentioned PR are expected to work if the cube DDF is extended by the T1 Pro manufacturer and modelID. This should be tested please.

**Comment by fhinder** [comment]
> Is there any update. Can someone help with the problem?

Pleas check #6608, if this is a solution for you. My setup is working.

**Comment by stefanmechelen** [comment]
I don't know much about github, but I do understand it's possible to add the Cube T1 pro, I updated deconz (add on in HA) to 2.20.01). I can add my old first gen magic cube but I still can't add the T1 pro. Is that normal since this says it's solved. I'm confused about that.
