### ISSUE TITLE
IDlock 150 - No binding for door state

### ISSUE THREAD

**Issue by brujoand** [dresden-elektronik/deconz-rest-plugin#5739]
## Describe the bug
According to this specification https://github.com/dresden-elektronik/deconz-rest-plugin/blob/2b71bd9604c85430d39814c252dff5ac7f746d78/general.xml#L1541 we should be reading the attribute 0x0003 from cluster 0x1010 which shows the door state. However when adding the IDlock there are only bindings for battery status and lockstate (locked unlocked). 

## Steps to reproduce the behavior
Add the lock using the deconz webapp
curl the api to see that only data for battery and lock state are presented
-->

## Expected behavior
There should afaik be a binding of the door state aswell to say wether it is closed, open, jammed etc..

## Screenshots
N/A

## Environment
Phoscon: 2.14.00 / 18/12/2021
Deconz: v2.14.0-beta

 - Host system: PC
 - Running method: Kubernetes / Docker
 - Firmware version: 26660700
 - deCONZ version: v2.14.0-beta
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? No

## deCONZ Logs
Nothing that looks interesting

## Additional context
N/A

**Comment by Mimiix** [comment]
Whats the model ID / Manufacturer name of this device?

**Comment by brujoand** [comment]
It's this one: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3827
https://idlock.no/wp-content/uploads/2020/11/User-Manual-Zigbee-module_EN_v0.4.pdf

Product name: ID-Lock
Manufacturer: Id-lock
Model identifier: 150

**Comment by brujoand** [comment]
I guess Datek is technically the manufacturer id, as they produce the zigbee module for the lock.

**Comment by Mimiix** [comment]
Please read the Basic cluster for it on your device if you can.

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by brujoand** [comment]
<img width="489" alt="Screenshot 2022-02-01 at 15 37 28" src="https://user-images.githubusercontent.com/124421/151988545-7a7d859d-9e05-4982-8d7f-e013fec90d55.png">
Sure, that should be this one right?

**Comment by Mimiix** [comment]
No, i want the basic cluster :)

**Comment by brujoand** [comment]
<img width="686" alt="Screenshot 2022-02-01 at 15 40 21" src="https://user-images.githubusercontent.com/124421/151989100-642d7790-5d51-44a3-9e9a-6c5bd40ad38f.png">
Ah right, that was the door lock cluster. Gotcha.

**Comment by Mimiix** [comment]
Almost there :) Can you please click " read" ?

We need those Manu name and model ID to show up.

**Comment by brujoand** [comment]
haha... I was a facepalming as I posted it.. I need more coffee.
<img width="671" alt="Screenshot 2022-02-01 at 15 42 13" src="https://user-images.githubusercontent.com/124421/151989394-7d4694e9-1f04-4cfa-a9ae-a85c67eb9c5c.png">
.

**Comment by Mimiix** [comment]
@Smanar Is the above device implemented by you already? If so, i have to forward @brujoand to the forums. Not sure if this is a newer version or not.

**Comment by Smanar** [comment]
The PR is here since May 2021 https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4876
So If I m right ATM the API don't support the doorlock state.

You have it on your device JSON ?

**Comment by brujoand** [comment]
Nope, I can only find the value in the phoscon app,

`{
  "config": {
    "battery": 90,
    "lock": false,
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "e6de70ee105a141b51a1ad82dbc90d81",
  "lastannounced": "2022-02-01T13:03:33Z",
  "lastseen": "2022-02-01T14:07Z",
  "manufacturername": "Datek",
  "modelid": "ID Lock 150",
  "name": "Hoveddøra",
  "state": {
    "lastupdated": "2022-02-01T13:07:09.197",
    "lockstate": "unlocked"
  },
  "swversion": "0.7",
  "type": "ZHADoorLock",
  "uniqueid": "68:0a:e2:ff:fe:6b:b8:26-01-0101"
}`

**Comment by brujoand** [comment]
@Smanar seems like your PR would solve my problem perfectly. Is there any reason why it hasn't been merged?

**Comment by Mimiix** [comment]
@brujoand #5733

**Comment by brujoand** [comment]
Oh, just read the [ddf](https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/) proposal. Looks like a good approach 👍
