### ISSUE TITLE
ROB_200-007-0 only battery entity

### ISSUE THREAD

**Issue by besiktas97** [dresden-elektronik/deconz-rest-plugin#5740]
I have a 8 button switch:

https://www.robbshop.nl/robb-smarrt-draadloze-schakelaar-wit-8knops-zigbee

The only thing is that I can see the battery information and no other information nor entity's.
When I check Phoscon I can see that the switch is added. When I check deconz, I can see the following:

![image](https://user-images.githubusercontent.com/76499056/151988693-a89be1fb-6af9-49cb-9af1-94e8ed64679f.png)

![image](https://user-images.githubusercontent.com/76499056/151988782-f71be781-2720-45dd-b955-e00ac03ec555.png)

I already try to reset the device and pair it again -> No luck
Already added without resetting -> No Luck

![image](https://user-images.githubusercontent.com/76499056/151989238-7a728cf2-6706-475b-8540-68663da998dd.png)

**Comment by Mimiix** [comment]
@besiktas97 You need to use the template.

**Comment by Mimiix** [comment]
To add to that: I think its best to open an topic on the forum as your post probably doesn't comply with #5113.

**Comment by besiktas97** [comment]
Where can I find the forum section so I can do that ? Thanks Mimmix

**Comment by Mimiix** [comment]
I just replied to your issue @besiktas97
