### ISSUE TITLE
ROB_200-007-0 only battery entity

### ISSUE THREAD

**Issue by besiktas97** [dresden-elektronik/deconz-rest-plugin#5741]
## Describe the bug

 I am having issue's that I can pair the ROB_200-007-0 device:

https://www.robbshop.nl/robb-smarrt-draadloze-schakelaar-wit-8knops-zigbee

## Expected behavior

  Its a 8 button switch and the expected behavior must be to use all of the buttons to create automations for lights and other stuff.

## Screenshots
 
This is in Phoscon:

![image](https://user-images.githubusercontent.com/76499056/151991771-9aad19bd-3a9f-4627-b6a5-7ace745c9e8f.png)

This is in Deconz:

![image](https://user-images.githubusercontent.com/76499056/151991907-c3c59d29-0eb2-4a4c-9a01-e50b6d6c2b96.png)

![image](https://user-images.githubusercontent.com/76499056/151991994-62e58ca3-67b2-4079-a8ef-7d90f2a7ac4e.png)

## Environment

deCONZ firmware: 

![image](https://user-images.githubusercontent.com/76499056/151992177-2696a672-1582-40a5-b370-5362eebc41dd.png)

 - Host system: Respberry Pi 4
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: (2.13.04 / 18-12-2021
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system?: No

**Comment by Mimiix** [comment]
In HA if you go to Developer tools, Events and then listen for deconz_event.

If you click buttons, do they show? 

![image](https://user-images.githubusercontent.com/43333120/151993451-729b8b9b-d37a-42e4-bdca-bb4240d8401e.png)

**Comment by besiktas97** [comment]
Nothing is showing up when I do what you ask to me.

**Comment by Mimiix** [comment]
Ah wait. This is fixed in the last beta (2.14.0).

You need to update to that.  The HA Addon is updated one stable releases. So you probably have to wait a while for that (expecting at least 1 week possibly longer).


Closing.,

**Comment by Mimiix** [comment]
The new Version of deconz is what you need. If you install deconz on your machine (beta) natively, you can use it already.

The ADdon needs to be updated to the new version. You have to wait for HA to do that for you and then you can update it there.

**Comment by besiktas97** [comment]
Ok thank you very much.
Will wait for it ( hope that they will bring out soon the new update :D )

**Comment by besiktas97** [comment]
I have installed the new update but I can't see entities of the buttons? I can see events from deconz when I push on the buttons.
How can I make automations so it can trigger for example the lights on/off for each button ?

**Comment by Mimiix** [comment]
@besiktas97 That's something you need to ask at HA.
