### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by gmitch64** [dresden-elektronik/deconz-rest-plugin#5746]
## Device
•	Product name: Neo Temperature & Humidity Sensor (also Lux)
•	Manufacturer: _TZ3000_qaaysllp
•	Model identifier: TS0201
•	Device type :
	Multipurpose Sensor (Light, Temperature, Humidity)

## Screenshots

![image](https://user-images.githubusercontent.com/27970644/152226090-8f9ed15a-4b36-4991-87da-482da0fa2b36.png)

![image](https://user-images.githubusercontent.com/27970644/152226129-0e0914e4-8f6c-4145-8610-f8517cf12020.png)

![image](https://user-images.githubusercontent.com/27970644/152226168-1505c640-3455-42fe-9ea0-4a8a71b3c1e0.png)

![image](https://user-images.githubusercontent.com/27970644/152226191-546a7f95-2e83-47e7-9228-d10b08b4e489.png)

**Comment by gmitch64** [comment]
I'm not 100% sure if this should be a new device, or a bug. The device IS being recognized, but it's only returning the Lux info in the JSON packet - there's no Temperature, Humidity or Battery Level being returned.

Currently running 2.13.04 on a Pi 3B+
deconz-dev/unknown,now 2.13.04-raspbian-buster-stable armhf [installed]
deconz/unknown,now 2.13.04-raspbian-buster-stable armhf [installed]

I have the dev tools installed, so I can compile test code for testing if needed.


If there's any other info that the devs need, please let me know.


G

**Comment by Mimiix** [comment]
Hi,

Seems to be a double post. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4790#issue-864100128

Please use the search next time.

Ill reopen the other issue.
