### ISSUE TITLE
Sonoff ZBMINI-L

### ISSUE THREAD

**Issue by SarcasticShrimp** [dresden-elektronik/deconz-rest-plugin#5763]
## Device

- Product name: SONOFF ZBMINI-L Zigbee 3.0 Smart Switch
- Manufacturer: SONOOF
- Model identifier: ZBMINI-L
- Device type : Please remove all unrelated device types. 
  - Light
  - Switch
  

### Basic
![image](https://user-images.githubusercontent.com/12154878/152699104-077e0d26-1afd-4851-b513-64b110eabd0e.png)
![image](https://user-images.githubusercontent.com/12154878/152699125-5604ccf1-c2f6-4911-b1ff-48e6debf985a.png)
### Identify
![image](https://user-images.githubusercontent.com/12154878/152699178-87dcdacb-3b8b-42a2-abd1-bbc6dcc6060b.png)

### Groups
![image](https://user-images.githubusercontent.com/12154878/152699210-348fb477-7d5d-44d1-9fc5-8bf672291076.png)

### Scenes
![image](https://user-images.githubusercontent.com/12154878/152699228-f4f3320c-a2d2-48b1-89ef-21089e372499.png)

### On/Off
![image](https://user-images.githubusercontent.com/12154878/152699243-2eea930b-06c3-4205-b4b7-5b2b5d1ac529.png)
![image](https://user-images.githubusercontent.com/12154878/152699255-0c03f532-11c6-4311-9a4e-0eae119cb98b.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/12154878/152699272-f8c44817-4795-454e-92aa-00477227e55f.png)

![image](https://user-images.githubusercontent.com/12154878/152699302-0b93d507-1efc-4152-9878-57733a099b84.png)

**Comment by pyrech** [comment]
I guess this issue should be kept open until support is added even if we have to wait a bit until #5733 is done?

In the meantime I created https://forum.phoscon.de/t/sonoff-zbmini-l/1686 as requested in #5113

**Comment by Mimiix** [comment]
Yes  but you need to keep bumping this open once in a while.

**Comment by pyrech** [comment]
Doh, not the OP here but still need this feature request to be kept open 😅

**Comment by Mimiix** [comment]
Sure!
@Smanar  Can  we make a DDF?

**Comment by sir-Unknown** [comment]
Not the OP. Got the device working by adjusting the DDF. However would like to have the possibility to receive the toggle of the power on/off from the wire. I don't have the skills to add that.

**Comment by Smanar** [comment]
>However would like to have the possibility to receive the toggle of the power on/off from the wire. I don't have the skills to add that.

You mean the return when using the device manualy ? It's the binding part https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel
Else if you can copy/paste the DDF I can complete it.

**Comment by moecre** [comment]
> Not the OP. Got the device working by adjusting the DDF. However would like to have the possibility to receive the toggle of the power on/off from the wire. I don't have the skills to add that.

I'm confused right now. Does this mean the device is compatible/partly compatible? These devices are the missing link for my smart home and I'd like to know if I can start buying them. Thanks.

**Comment by felixnurse** [comment]
I have both devices (zbmini and zbmini-l) if that helps. 
Let me know what I need to share from deconz and illlpaste here for you.thanks

**Comment by Smanar** [comment]
Depend of device but for exemple for the ZBMINI-L, you can start a DDF 
- fill the basic cluster indentification
- drag and drop a "on off light"
- save the file, llok the name and path on the editor
- share the contain

Some part can be auti filled
The device can work direclty if you take "hot relaod" in the editor menu. You will just miss the binding, but you can try to set them too.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by ads1230** [comment]
`
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "ZBMINI-L",
  "product": "ZBMINI-L",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/zbmini-l.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
`

**Comment by Smanar** [comment]
You miss the binding/reporting but not sure you need it ?

Without it the device don't make state report, not sure it usefull for this kind of device but it prevent having different state on the api and on the reality.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "ZBMINI-L",
  "product": "ZBMINI-L",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    }
  ]
}
```

Have added the bind/report for the on/off cluster.

If it still working can make a PR to add it ?

**Comment by Smanar** [comment]
You miss the binding/reporting but not sure you need it ?

Without it the device don't make state report, not sure it usefull for this kind of device but it prevent having different state on the api and on the reality.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "ZBMINI-L",
  "product": "ZBMINI-L",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    }
  ]
}
```

Have added the bind/report for the on/off cluster.

If it still working can make a PR to add it ?

**Comment by Smanar** [comment]
You miss the binding/reporting but not sure you need it ?

Without it the device don't make state report, not sure it usefull for this kind of device but it prevent having different state on the api and on the reality.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "ZBMINI-L",
  "product": "ZBMINI-L",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    }
  ]
}
```

Have added the bind/report for the on/off cluster.

If it still working can make a PR to add it ?

**Comment by ads1230** [comment]
> You miss the binding/reporting but not sure you need it ?
> 
> Without it the device don't make state report, not sure it usefull for this kind of device but it prevent having different state on the api and on the reality.
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "SONOFF",
>   "modelid": "ZBMINI-L",
>   "product": "ZBMINI-L",
>   "sleeper": false,
>   "status": "Gold",
>   "subdevices": [
>     {
>       "type": "$TYPE_ON_OFF_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x01"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/on",
>           "description": "True when device is on; false when off.",
>           "refresh.interval": 5
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     }
>   ],
>   "bindings": [
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0006",
>       "report": [
>         {
>           "at": "0x0000",
>           "dt": "0x10",
>           "min": 5,
>           "max": 1800
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> Have added the bind/report for the on/off cluster.
> 
> If it still working can make a PR to add it ?

Working with your edits. Set up 3 devices today all working fine even after reboot.

**Comment by Smanar** [comment]
Nice, do you want tio make a PR or wana I make it ? (to add it officialy)

**Comment by ads1230** [comment]
> Nice, do you want to make a PR or wana I make it ? (to add it officialy)

Could you do it please. I'm not too savvy on these things.

**Comment by Smanar** [comment]
Done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6095
Thx Again
