### ISSUE TITLE
Wiki to install Firmware needs a update

### ISSUE THREAD

**Issue by ninadpchaudhari** [dresden-elektronik/deconz-rest-plugin#5767]
[Update-deCONZ-manually](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually) Needs to be updated 
The section on [Updating when deconz is already installed](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-on-a-system-where-deconz-is-already-installed) specifies that `GCFFlasher.exe` exists in `deCONZ/bin` directory, which it does not. I think the recent deConz installation does not contain the binary?  We have to download the  `GCFFlasher` separately instead.  

i downloaded the `GCFFlasher.zip` and was able to install required firmware, but the above mentioned section needs to be updated if the deCONZ installation does not come with the flashing utility anymore

Screenshot of deCONZ installation
![Screen Shot 2022-02-06 at 9 51 07 PM](https://user-images.githubusercontent.com/1305825/152718426-42003692-5f52-403a-9000-a3f2678f1c82.png)

**Comment by Mimiix** [comment]
Feel free to edit the wiki yourself with this knowledge :)
