### ISSUE TITLE
Ikea KADRILJ status not updated - using Home assistant OS + latest Deconz 6.12.0

### ISSUE THREAD

**Issue by andys73** [dresden-elektronik/deconz-rest-plugin#5768]
## Describe the bug

The status of the Shade is not reflected in either VNC or Home Assistant. 

## Steps to reproduce the behavior

1. Shade is up . Status in VNC is 0
![image](https://user-images.githubusercontent.com/77861753/153028486-da385127-4295-4aa8-8249-c8961cffa142.png)
2. Execute in Home assistant cover.close. The action works and cover is closed 
![image](https://user-images.githubusercontent.com/77861753/153028749-c67e8b7b-52d3-4b26-847c-ef13ec903e47.png)
3. Status in Home assistant  
![image](https://user-images.githubusercontent.com/77861753/153029083-58652c8f-7467-4dc7-a9c0-f3f51fe33ebe.png)
4. Status in VNC 
![image](https://user-images.githubusercontent.com/77861753/153029185-fc2013ee-feaa-4db5-87f2-ed81b56f85e3.png)
5. Click on the read button in VNC 
![image](https://user-images.githubusercontent.com/77861753/153029284-14954854-2b4f-4da7-b195-12652a3bd133.png)
6. Status in Home assistant is updated as well 
![image](https://user-images.githubusercontent.com/77861753/153029435-25cc3690-988c-4ad1-ae14-b5b34d28b8d4.png)
Also at the time of Raspbery pi reboot I have to read first the Basic parameters from VNC for the Ikea cover device otherwise the Homeassistant is not executing the cover.close and cover.open

## Screenshots

Screenshots in the described steps 

## Environment

 Latest Deconz 6.12.0, Combee 2 latest firmware 26720700

 - Host system: Raspberry Pi 4B Home assistant OS latest 7.3
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: 26720700
 - deCONZ version: 2.14.1
 - Device: ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? Yes  If so: USB SSD drive

## deCONZ Logs

No logs collected. If relevant please let me know and I will collect.

## Additional context

Large network ~ 150 devices. The status worked a couple of deconz versions ago and I have not added to many devices since then.

**Comment by ebaauw** [comment]
Did you try and power cycle the blind?  Just remove the battery for 5 seconds or so.

I've had issues with my FYRTUR sometimes becoming unresponsive or stopping reporting on my network (~50 routers, mostly Hue), for no apparent reason.  Power cycling the blind usually fixed it, but sometimes I needed to open the network while doing that.  I moved it to a separate network with only a TRADFRI repeater as router and it seems far more stable now.

**Comment by Mimiix** [comment]
I'm watching this issue closely as it im not sure if it complies with #5113 and that my fyrtur works as expected still.

**Comment by andys73** [comment]
taking off the battery for 10 seconds and putting the battery back solved the issue! I have not thought of that at all, thank you @ebaauw 
I can see now in home assistant the position scrolling as the shade is closing or opening 

![image](https://user-images.githubusercontent.com/77861753/153036900-37430637-77a5-493f-8d19-d5e4d6acf66c.png)
Closing the issue.

**Comment by andys73** [comment]
and many thanks @Mimiix  I have tagged https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5113 and indeed this should have been a question to the forum.

**Comment by Mimiix** [comment]
@andys73 no worries, happy its solved! :)
