### ISSUE TITLE
Aqara Smart Wall Switch H1 (With Neutral, Single Rocker/ Double Rocker)

### ISSUE THREAD

**Issue by JPOliveGit** [dresden-elektronik/deconz-rest-plugin#5769]
## Aqara Smart Wall Switch H1 (With Neutral, Single Rocker/ Double Rocker)

- Product name: H1 Wired
- Manufacturer: Aqara
- Model identifier: WS-EUK03 / WS-EUK04
- Device type :
  - Switch

**Comment by Mimiix** [comment]
Missing screenshots. Please open another issue with correct template usage.

**Comment by SwoopX** [comment]
No, already supported

**Comment by JPOliveGit** [comment]
> 

it can't find it... SwoopX the wireless ones work well but the wired do not...
