### ISSUE TITLE
Issue with Philips Dimmer Switch

### ISSUE THREAD

**Issue by Fl0ca** [dresden-elektronik/deconz-rest-plugin#577]
Hi,
is there a known issue with the Original Philips Dimmer Switch and the Webinterface? 

I have paired the switch several times and i always get the same Problem after about 30min. (can be less, don't know).
I can read the values like 1002 and 4002 from an external Program over the Api, but the device is freezed or something in the Webif.  I can't click on the Dimmer in the Main Menu, there is an icon without functionallity. In the first minutes it works and i can add lights to it , then it brokes after some time.

I had the same issue with the Tradfri Remote, but only once and when i pushed some buttons, it gets clickable again in the webif, since this point it works like a charm.

Hope you understand what i mean, i really love this project...

regards

**Comment by manup** [comment]
Which version of deCONZ are you running?
In recent versions normally once the dimmer is seen it stays active (not greyed out) for a long time.
