### ISSUE TITLE
Smart Siren

### ISSUE THREAD

**Issue by Foppen** [dresden-elektronik/deconz-rest-plugin#5779]
## Device

- Product name: Smart Siren
- Manufacturer: AduroSmart Eria
- Model identifier: Smart Siren
- Device type : Siren

## Screenshots

# Basic cluster configuration tool
![Basic cluster Conf tool part1](https://user-images.githubusercontent.com/14836562/154338451-9d97b59f-b06b-4c74-b3fd-6dcda8dcb703.JPG)
![Basic cluster Conf tool part2](https://user-images.githubusercontent.com/14836562/154338469-ff383d82-9005-42f5-b0ff-055ac9989299.JPG)

# Node Info Configuration tool
![Node Info Conf tool part1](https://user-images.githubusercontent.com/14836562/154338587-38ba9893-ae7f-49d1-903b-b1287a05da63.JPG)
![Node Info Conf tool part2](https://user-images.githubusercontent.com/14836562/154338601-1d2af0c5-d827-440b-bbe4-bff0d703f3c9.JPG)

# Clusters of the node
![Clusters of SmartSiren](https://user-images.githubusercontent.com/14836562/153551483-939171d3-4706-4e0c-9fe1-72c6f4ce761d.JPG)

# Node Info Panel
![Node Info - SmartSiren](https://user-images.githubusercontent.com/14836562/153555430-caac0d67-8af6-459b-9e1f-35cbde9eb149.JPG)

# Basic cluster's attributes as shown in the Cluster Info Panel, with the data returned by read. 
![Cluster Info - Basic part1](https://user-images.githubusercontent.com/14836562/153554859-88ef69b7-6406-4b0a-94aa-64946797e4b0.JPG)

![Cluster Info - Basic part2](https://user-images.githubusercontent.com/14836562/153554868-556f934b-f080-4f41-80fb-2ec0d0e2e65e.JPG)

# Screenshots Cluster Identify
![Cluster info - Identify](https://user-images.githubusercontent.com/14836562/153478999-053c0cda-2443-428f-9b30-6c0e77e0ed62.JPG)
![Cluster info - Trigger](https://user-images.githubusercontent.com/14836562/153479010-1feeb1d2-a889-4d8a-8cc0-a6cbcc8ca46d.JPG)
![Cluster info](https://user-images.githubusercontent.com/14836562/153445582-4511f3e1-733b-439b-a1fd-6352e86e0fe5.jpg)

# Screenshots Cluster Info IAS Zone
![Cluster info - IAS - Enroll](https://user-images.githubusercontent.com/14836562/153484428-623b36f7-c216-49b7-b83d-459869e25a0f.JPG)

![Cluster info - IAS - Status](https://user-images.githubusercontent.com/14836562/153484452-8f93fa8d-4ba2-44cc-b7a3-805973564955.JPG)

![Cluster info - IAS - Attribute](https://user-images.githubusercontent.com/14836562/153484472-8eaaa188-b874-45fd-8342-6636e83e19d2.JPG)

# Screenshots Cluster Info IAS WD
![Cluster info - IAS WD - Start](https://user-images.githubusercontent.com/14836562/153487003-c95a686c-0a56-42bc-b6ae-17a84d1d754a.JPG)

![Cluster info - IAS WD - Squawk](https://user-images.githubusercontent.com/14836562/153487018-f26b0143-f1aa-41b5-af5f-05f9c419ea7b.JPG)

# API get output for: http://a.b.c.d/api/KEY/lights/5/

   "5": {
        "etag": "3331b397123d4b5ae49a2b6468695f41",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2022-02-10T15:46Z",
        "manufacturername": "AduroSmart Eria",
        "modelid": "Smart Siren",
        "name": "Smart_Siren",
        "state": {
            "alert": "none",
            "reachable": true
        },
        "swversion": "01000003",
        "type": "Warning device",
        "uniqueid": "00:15:8d:00:05:4e:d6:c6-01"
    }

**Comment by Mimiix** [comment]
Missing screenshots

**Comment by Foppen** [comment]
Hi Mimiix,

I've added the cluster printscreens and node info for the configuration tool. Please let me know what printscreens you would like to see. From the "Request-Device-Support" I don't see what print screens I need to add, as there are no further clusters.

**Comment by Foppen** [comment]
Thanks for the help. I've just added the IAS Zone

**Comment by Mimiix** [comment]
And the ias wd?

**Comment by Foppen** [comment]
Just added the IAS WD

**Comment by Foppen** [comment]
Could you please let me know if there is still information missing for this device request?

**Comment by Mimiix** [comment]
Seem to be all fine. Not sure what you are expecting right now 😅

**Comment by Foppen** [comment]
Great thanks! good to know the shared info is complete now. 

I would expect the label "Incomplete issue" will be removed and hopefully the Eria Smart Siren will be supported in the near future :-)

**Comment by Mimiix** [comment]
Ah, i forgot about that.

I am not too sure about early support. Not sure if a DDF can work here. If not, #5733  is in place...
