### ISSUE TITLE
Setting a schedule's localtime returns a defect result

### ISSUE THREAD

**Issue by meandthemachine** [dresden-elektronik/deconz-rest-plugin#5787]
## Describe the bug

When calling the API for setting a schedule's `localtime` (only), on success, the corresponding route's handler always tries to return/reflect `time` which is `null` in such a case, as it hasn't been part of the request. 
Also, the returned slug contains `"time"` instead of `"localtime"`.

## Steps to reproduce the behavior

Send this body via PUT method:
```
{"localtime": "W127/T12:00:00"}
```
Current behaviour:
```
[{"success":{"/schedules/1/time":null}}]
```

## Expected behavior

```
[{"success":{"/schedules/1/localtime":"W127/T12:00:00"}}]
```

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian Buster
 - deCONZ version: 2.14.01
 - Python 3.7 REST client
 - Firefox developer tools HTTP client

## deCONZ Logs

/
## Screenshots 

/

## Additional context

I think the issue is caused by this line, that wrongly tries to reflect the `time` field of the request, even if it hasn't been given.
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/80952d6c5bfc5a12d3527176602b8423948897de/rest_schedules.cpp#L669

Thank you and cheers!

**Comment by meandthemachine** [comment]
I opened the issue via source code line context menu "reference in new issue". That one missed the template. I think I've provided enough information, though. Maybe someone reads this, despite the bot closing it...

**Comment by meandthemachine** [comment]
@manup Please consider reopening this issue. I had a look at your bug report template and I think I already gave all information that is applicable to and needed for this issue. It is a quite evident bug, I think. Thank you.

**Comment by Mimiix** [comment]
@meandthemachine I am not able to reopen at all as the bot will close it again. We ask to use the template so that all reports are the same. There's quiet some info missing. Please create a report with the template

**Comment by meandthemachine** [comment]
I apologize for that one sentence that I just removed from my previous comment. That was not OK at all. Please excuse me.

**Comment by meandthemachine** [comment]
@Mimiix I had a look at the bot's README and edited my issue accordingly. So now, maybe it won't be closed again if you try to reopen it...

**Comment by Mimiix** [comment]
@meandthemachine I understand your frustration, but it isn't doable for us to maintain all issues being differently. That's why we chose the template. Most of us are doing this in their free time (as we are not employed by DE). So anything the user can do to help us a bit is better for everyone in the end. 

In this example, the first thing we would ask is the current setup you run (and version) as that was missing from your first post. 

I'm happy to re-open  and apology accepted 🙂

**Comment by Mimiix** [comment]
I've edited your post manually to comply to the template :)

**Comment by meandthemachine** [comment]
Oh, thank you very much!
... yes, I somehow missed the screenshots heading...

You will see that setup and version are not relevant in this case, but I understand that you can't know that upfront.

**Comment by meandthemachine** [comment]
**Off topic:** Regarding the different entry points for opening an issue (and potentially missing the templates) and regarding your bot, maybe you could (or even should?) try setting `blank_issues_enabled` to `false` for your repo, as described in [GitHub Docs Configuring the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser), and see how that works out if somebody uses "reference in new issue", like I did.

This kind of bug that I faced [has already been reported to GitHub and been confirmed](https://github.community/t/how-to-use-issue-templates-with-reference-in-new-issue/2359) some years ago, but unfortunately it remains unclear, if or how it has been addressed and resolved.

Cheers!
