### ISSUE TITLE
TuYa ERS-10TZBVK-AA

### ISSUE THREAD

**Issue by HennigStein** [dresden-elektronik/deconz-rest-plugin#5790]
Hi, i dont andertsna dall this points. My English is very bad.
Can you please help me too.

I hav ask her:
https://forum.iobroker.net/topic/52505/kennt-jemand-diesen-knopf-drehschalter

And now they say, it can be working. Its this product:
https://www.zigbee2mqtt.io/devices/ERS-10TZBVK-AA.html

Can i buy this and connect with conbee 2 on my Rasbee with ioBroker? Thsi will be grate. Please sorry for my bad english and i dont can answer all points so corectly. This is only i can make. :-(

  !!!!! READ THIS FIRST: https://forum.phoscon.de/t/read-me-device-request-read-me/23/2 !!!!!!
  - Before requesting a device, please make sure to search the open and closed issues for any requests in the past.
  - Make sure not to remove any headers and fill the template completely. If you remove the headers, the issue will be auto-closed.
  - Sometimes devices have been requested before but are not implemented yet due to various reasons.
  - If there are no hits for your device, please proceed.
  - If you're unsure whether device support was already requested, please ask for advise in our Discord chat: https://discord.gg/QFhTxqN

## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other:

**Comment by Mimiix** [comment]
This is not how this works. You need to own the device to get this supported.

@Smanar you know this.
