### ISSUE TITLE
Tuya Smart Thermostat Radiator Valve TS0601

### ISSUE THREAD

**Issue by dnldsign** [dresden-elektronik/deconz-rest-plugin#5796]
## Device

- Product name: Tuya Smart Thermostat Radiator Valve (https://zigbee.blakadder.com/Tuya_TV02.html)
- Manufacturer: _TZE200_hue3yfsn
- Model identifier: TS0601
- Device type :
  - Thermostat (TRV)

Should be almost identical to device https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4675 (https://zigbee.blakadder.com/Haozee_TRV601.html)

### Basic Cluster
![Basic cluster](https://user-images.githubusercontent.com/99689518/153948563-3d2a0a60-48a0-442a-a62f-8479306f583b.JPG)

### Node info
![Node info](https://user-images.githubusercontent.com/99689518/153948697-9fd319ff-a2d4-4325-8ffe-56c3e9792d1b.JPG)

### Groups
![group1](https://user-images.githubusercontent.com/99689518/153948759-7888c7ee-e940-4685-b6e1-ea6e5f227725.JPG)
![group2](https://user-images.githubusercontent.com/99689518/153948768-3c417b73-877f-4846-bc8b-e82dde534e83.JPG)

### Scenes
![scene1](https://user-images.githubusercontent.com/99689518/153948779-cca9210c-5c73-4f9b-a65d-19b80d0ec9b8.JPG)
![scene2](https://user-images.githubusercontent.com/99689518/153948784-6837842b-b7c4-40fc-abe3-5387c311b517.JPG)
![scene3](https://user-images.githubusercontent.com/99689518/153948795-feac5d52-7fe4-4c3e-9e21-4b30da32d833.JPG)
![scene4](https://user-images.githubusercontent.com/99689518/153948799-be071703-4502-4db0-8f82-a19c30609d7b.JPG)

### OTAU
![otau](https://user-images.githubusercontent.com/99689518/153948870-2ea2cb88-9f2d-4920-a360-f14646ffa37d.JPG)

### Tuya cluster
![tuya](https://user-images.githubusercontent.com/99689518/153948877-8f2f13f3-24f5-401c-8895-d0587825618e.JPG)

**Comment by dnldsign** [comment]
Switched to zigbee2mqtt

**Comment by danli003** [comment]
I bought a number of these things. Is it possible to get support in deconz? I'd rather not switch to zigbee2mqtt due to the effort involved.

**Comment by Asuanin** [comment]
Same as https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5844
