### ISSUE TITLE
Gledopto GL-C-002P 5in1 Zigbee Mini Ultra Thin LED Controller

### ISSUE THREAD

**Issue by chris-nite** [dresden-elektronik/deconz-rest-plugin#5798]
## Device

- Product name: Gledopto GL-C-002P 5in1 Zigbee Mini Ultra Thin LED Controller
- Manufacturer: Gledopto 
- Model identifier: GL-C-002P (currently falsely reported as GL-C-009P after binding)
- Device type : 
  - Light

### Basic
![1basecluster](https://user-images.githubusercontent.com/65537552/154131534-dd26ccbb-2f1d-4b6c-a5bc-e517af28edea.png)
![2node](https://user-images.githubusercontent.com/65537552/154131538-fb4e5ae3-b213-45b2-904b-3fd85d4b4f80.png)

**Comment by chris-nite** [comment]
The current status is, that the device properly is binded to the mesh in phoscon, but falsely identified as GL-C-009P. Technically so far it is not used as a repeater (it got Zigbee 3.0 onboard) as well as it doesn't correctly report the power state (is it on or off?) back to home assistant.

Additional info: This led-controller can be used for different kind of led-stripes (rgb/cct/dimming/etc.) through changing the opt-Setting on the controller itself. Based on this it is reported differently back to phoscon as colorextended or dimming light.

**Comment by Mimiix** [comment]
The manufacturer name and model Id are presented by the device.  So if that is wrong, it's in the device firmware...

**Comment by davidrustingha** [comment]
I have this device and it is working in home-assistant. However; the transition is off. It seems I am not able to set a transition lower than 1 second, so the device is always fading in and out.
Is there a way to change this?
