### ISSUE TITLE
RTX/Tuya 1 Gang Zigbee Dimmer Module (QS-Zigbee-D02-TRIAC-LN)

### ISSUE THREAD

**Issue by Loonmor** [dresden-elektronik/deconz-rest-plugin#5803]
## Device

- Product name: RTX 1 Gang Zigbee Dimmer Module QS-Zigbee-D02-TRIAC-LN
- Manufacturer: _TZ3210_ngqk6jia
- Model identifier: TS110E
- Device type : Please remove all unrelated device types. 
  - Light
  - Switch
  - Other: Dimmer

Issue: Dimming via deConz is not possible.
## Screenshots
 
![image](https://user-images.githubusercontent.com/99427619/154339058-6a081673-a1cb-4fd3-94d6-2bc66dd80fba.png)
![image](https://user-images.githubusercontent.com/99427619/154339767-86619c4a-349a-4cb0-b60b-0bca2e744f41.png)

### Basic
![image](https://user-images.githubusercontent.com/99427619/154340198-44dbd4a3-557b-473a-853e-5a4cfac5a46b.png)
### Groups
![image](https://user-images.githubusercontent.com/99427619/154339914-6c5102b5-780c-4452-b185-256245e992dd.png)
### Scenes
![image](https://user-images.githubusercontent.com/99427619/154339833-c2367761-dabd-4351-bf1f-c52a6dc61646.png)
### On/Off
![image](https://user-images.githubusercontent.com/99427619/154340020-ab1844e1-5895-4acd-b105-9c75eab6726a.png)
### Level Control
![image](https://user-images.githubusercontent.com/99427619/154340122-8e07f42e-f848-46f1-bc91-456fde776cd6.png)

**Comment by mpetro89** [comment]
Please also support 2 gang device:

Manufacturer Name: _TZ3210_wdexaypg
Model identifier: TS110E

Device also support led_type, minimum & maximum brightness set.
I found this topic:
https://github.com/Koenkk/zigbee2mqtt/issues/9878

My 2 gang device:

![deconz_v1](https://user-images.githubusercontent.com/67239997/154911075-8fd8bb5f-49b6-43d9-922d-3873c51ced1c.PNG)


![deconz](https://user-images.githubusercontent.com/67239997/154910869-5ae5e513-12bd-49f5-af74-fcf66abee7ee.PNG)

Basic:
![deconz_basic](https://user-images.githubusercontent.com/67239997/154910925-af126b8d-accb-4a3e-8169-af68189e3df2.PNG)

ON/OFF:
![deconz_on_off](https://user-images.githubusercontent.com/67239997/154910956-e5e0d0a1-9efb-4a5a-bf92-34c842a6dd31.PNG)

Level Control:
![deconz_level_control](https://user-images.githubusercontent.com/67239997/154911009-8f83cb2f-3d7c-49d0-8d4d-fb257a30af17.PNG)

**Comment by spekkie3** [comment]
I get the : unsupported issue in mqtt 

I use mqtt addon with home assistant 

Can someone please help ?

**Comment by SkyByte** [comment]
See issue #9878
