### ISSUE TITLE
Hue Dimmer Switch -> long press issue

### ISSUE THREAD

**Issue by elpaso666** [dresden-elektronik/deconz-rest-plugin#5804]
## Describe the bug
I have integrated the new 2021 Hue Dimmer switch and there is an issue with long-press action on all 4 buttons.

Every time long press event (1001) is executed, 1000 (single press) is also executed before the actually 1001.

This behavior makes long-press unusable. However implementation of long press (if issue above is fixed) has serious benefit with duration which makes it fully customizable...

## Steps to reproduce the behavior
button clicking

## Expected behavior
when long press is executed 1000 is not send, only repetitive 1001 with duration attribute

## Screenshots
N/A

## Environment
latest version, latest FW
ConBee II
NodeDred Deconz plugin

## deCONZ Logs
N/A

## Additional context
N/A

**Comment by elpaso666** [comment]
hello,

no comments? closed? What next shall I do to help to clear this out?

thx
Jakub

**Comment by Mimiix** [comment]
Hi Jakub,

You need to keep the report active.

I'll ask devs to check out.

Reopening.

**Comment by elpaso666** [comment]
> Hi Jakub,
> 
> You need to keep the report active.
> 
> I'll ask devs to check out.
> 
> Reopening.

thank you

**Comment by ebaauw** [comment]
The bug is in your expectation; there are no button event values corresponding to a single press nor long press action.  The correct values are:

value | meaning
-- | --
x000 | initial press
x001 | hold (issued every 800ms while holding)
x002 | release (after initial press)
x003 | release (after hold)

A single press action results in a series of `buttonevent` values: x000, x002;
A long press action results in a series of `buttonevent` values: x000, x001, x001, ..., x001, x003

**Comment by elpaso666** [comment]
Hello,

this confirms what I wrote.

Issue is that if x000 is sent initially also for long-press it cant't be used for dedicated action, because everytime I want to do long-press I receive also press.

Example:
Single Press = Blinds down for (5 cm)
Long Press = Blinds fully down
But as I receive for long press x000 it triggers down for 5cm and then immediately reveices x001 consider as another action and stops the blinds

Example 2:
Single Press = Light 100%
Long Press = light 80%
After long press I go to 100% and then to 80% because x000 is again sent without any reason.

This works comepletely correct on Xiaomi buttons, Opple buttons, Ikea buttons.

Is there a way to change this? even if x000 would need to wait for x001 and then discard first x000?

thx
Jakub

**Comment by ebaauw** [comment]
No, there’s no way to change this, as this is how it’s supposed to work.  Use x002 to recognise single press.

**Comment by elpaso666** [comment]
thx, fair point. still sad that philips has such implementation which is by design wrong

**Comment by Mimiix** [comment]
Case closed?
