### ISSUE TITLE
Consumption not reported?

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#581]
Hi!

Are there any situations where consumption is not reported? Or will it always be populated as an int?

https://community.home-assistant.io/t/error-in-pydeconz-sensor-py-line-128/52965/2

**Comment by ebaauw** [comment]
As for most sensor state attributes, `state.consumption` is assigned a value only when the corresponding attribute is read (by deCONZ) or reported (to deCONZ by the sensor).    Between the time of the sensor creation and the first read or report `state.consumption` might be missing when GETting the sensor's `state` through the REST API (and `state.lastupdated` is probably `null`).

After restarting deCONZ, `state.consumption` is restored from the database.

**Comment by Kane610** [comment]
Allright, thanks.

I will need to cover that scenario then.
