### ISSUE TITLE
Aquara Smart Knob Switch H1

### ISSUE THREAD

**Issue by Adam-Langley** [dresden-elektronik/deconz-rest-plugin#5815]
## Device

- Product name: Aquara Smart Knob Switch H1 (wireless version).
- Manufacturer: LUMI
- Model identifier: lumi.remote.rkba01
- SKU: ZNXNKG02LM
- Device type : Please remove all unrelated device types. 
  - Basic
  - Identify
  - Power Configuration
  - Lumi Specific
  - Multistate Input (Basic)
  - Identify

## Screenshots

<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825029-42d68c03-18e6-4268-a261-a3818fbad6ea.png">

### Basic
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825046-05bb7ea0-3af6-4995-acd8-a79c6a29a1d6.png">

### Identify
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825081-903ea76b-af6d-4d96-aa57-59d094634954.png">

### Power Configuration
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825100-2709e1e9-64e8-4676-8819-f6e8c62e8779.png">

### Lumi Specific
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825134-da7af4e7-6099-49a1-889a-4d94d701928c.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825141-93070306-abb0-4556-bd9e-5309109da363.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825145-329c644c-d2a3-45a0-84ab-d0a9cf91c502.png">

### Multistate Input (Basic)
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825156-0c773cab-30e1-4c9b-b63b-f5a33e10e19e.png">

### OTAU
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16373742/154825182-456f61e2-9673-4f86-8500-3b6a6824fc1c.png">

![aqarah1](https://user-images.githubusercontent.com/16373742/154825244-f7f8023c-ec49-4457-9bf3-2a1f1e44d672.jpg)

**Comment by Adam-Langley** [comment]
Ping - still relevant

**Comment by Adam-Langley** [comment]
Ping - still relevant

**Comment by theboxer** [comment]
@Adam-Langley does this switch work with deconz/phoscon? I'm about to purchase one...

**Comment by theboxer** [comment]
@Adam-Langley I'm actually not using home assistant, but a homebridge and exposing it to the home app (apple). By z2m you mean this: https://www.zigbee2mqtt.io/?

**Comment by theboxer** [comment]
@Adam-Langley I have Rpi4 + Conbee2. I'm just configuring the docker container and going to try it :) Thank you for the hint! btw. I'm on deCONZ's discord if you wanna chat more about the setup.

**Comment by Mimiix** [comment]
> Hi @theboxer - yes that's right.
> 
> When you first look into it, you'll think - "this is a lot of different components, for what I used to do with 1, or 2... too much hassle?" I urge you to give it a try, and you'll see, once you've installed it, you're done. It works like a dream. HomeAssistant ("HA") releases updates (applied automatically if you like), almost every few days - so, they're so incredibly active, it's awesome. Just follow the instructions. You'll be installing
> 
> 1. Home Assistant (the environment)
> 2. Zigbee2Mqttt (the add on which talks to your zigbee hardware, and then passes the zigbee messages to/from the next component...)
> 3. An MQTT broker - probably just the built-in one called "Mosquitto". MQTT is a messaging system - think of it like a highway system, it connects things which publish messages, to things which want to listen to messages... It's how your zigbee events will eventually find their way into HomeAssistant
> 
> Looking at the list above... where's the Phoscon components?? Yep - they're gone. No need for them. Zigbee2Mqtt is compatible with the dresden devices.
> 
> Can I ask, what is your installation platform? For example, I'm doing everything above with a Pi4 + RaspBee II. But you could equally be running on a workstation+Conbee or such...

Hey guys, I'm all for helping each other, but we are going a bit off topic now. May i suggest you reach out to each other through discord or forums?

**Comment by Adam-Langley** [comment]
Hey @Mimiix - sure thing no prob - was just about to do that just didnt want to jump the gun.
@theboxer sure thing - I'll look for you now.

**Comment by Smanar** [comment]
> In fact, an unrelated thing - but huge reason to move… In Phoscon, if a connection to a device ever failed, and the only way to get it to respond is to re/add it, you lose everything related to that device. Z2m is HEAPS better here. got an unresponsive device? Hit the “add device” button in Z2m, force the device into discovery mode, and the connection is healed… no settings lost.


It's same in phoscon, you just need to DON'T delete the device, and make the same procedure, all will be invisible.

**Comment by saxn-paule** [comment]
I bought two of those devices but I'm not able to pair them via Phoscon. What has to be done to make it work?

**Comment by xADDRx** [comment]
HI,
any Solution here? Have the Same Problem

**Comment by xADDRx** [comment]
Has anyone got it working yet?

**Comment by sadpixel** [comment]
I also have this device and would love for it to work with DeCONZ. Happy to provide any information that may be needed, though it looks like the OP already added the required screenshots...

**Comment by sadpixel** [comment]
Dear @Mimiix, can we please get this re-opened? I'll try to put together a test DDF based on the one for the standard Aqara H1-series wireless switch (lumi.remote.b28ac1 aka WRS-R02), but I'll probably need some help with the Multistage Input cluster (0012)...

**Comment by Mimiix** [comment]
Happy to re open. @smanar would this be possible with DDF ?

**Comment by Smanar** [comment]
Honnestly IDK, this device need lot of work.
- It seem it need a special request on inclusion.
- The Lumi specific cluster give a payload with angle/vitesse/speed, like for all rotating switch, not easy to convert in X00Y event. Need to use special field.

The problem will be not the 0x0012 cluster, on this one you will just have some value according to action.

Can make try, make a basic DDF, without buttonmap part. use the device and look at return on logs to make the buttonmap file.

And I m not sure the "special request" can be automatic, on other Xiaomi device, it's just an option.

```
        {
          "name": "config/devicemode",
          "refresh.interval": 3000,
          "parse": {
            "at": "0x0009",
            "cl": "0xfcc0",
            "ep": 1,
            "eval": "if (Attr.val == 1) { Item.val = 'compatibility' } else if (Attr.val == 2) { Item.val = 'zigbee' } else { Item.val = 'unknown' }",
            "fn": "zcl:attr",
            "mf": "0x115f"
          },
          "read": {
            "at": "0x0009",
            "cl": "0xfcc0",
            "ep": 1,
            "fn": "zcl:attr",
            "mf": "0x115f"
          },
          "write": {
            "at": "0x0009",
            "cl": "0xfcc0",
            "dt": "0x20",
            "ep": 1,
            "eval": "if (Item.val == 'compatibility') { 1 } else if (Item.val == 'zigbee') { 2 }",
            "fn": "zcl:attr",
            "mf": "0x115f",
            "state.timeout": 2
          },
          "values": [
            ["\"compatibility\"", "Default mode for Xiaomi devices"],
            ["\"zigbee\"", "Closer to zigbee standard"] 
          ],
          "default": "compatibility"
        },
```
