### ISSUE TITLE
libde_rest_plugin depends on libcrypt.so.1 which is removed in glibc 2.35

### ISSUE THREAD

**Issue by nougad** [dresden-elektronik/deconz-rest-plugin#5817]
## Describe the bug

Loading `libde_rest_plugin.so` fails:

```
deCONZ[1582]: 15:28:44:032 error loading plugin: Cannot load library /usr/share/deCONZ/plugins/libde_rest_plugin.so: (libcrypt.so.1: cannot open shared object file: No such file or directory)
```

Device discovery does not work and of course everything related to the rest plugin. ( https://phoscon.de/discover or http://$IP/api/config ).

## Steps to reproduce the behavior

Update to latest glibc 2.35 and restart deconz software.

## Expected behavior

The plugin loads.

## Environment

 - Host system: Raspberry Pi (aarch64)
 - Running method: arch-linux
 - Firmware version: 26680700
 - deCONZ version: 2.14.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? no

## deCONZ Logs

```
deCONZ[1582]: 15:28:44:032 error loading plugin: Cannot load library /usr/share/deCONZ/plugins/libde_rest_plugin.so: (libcrypt.so.1: cannot open shared object file: No such file or directory)
```

## Additional context

```
$ ldd /usr/share/deCONZ/plugins/lib*
/usr/share/deCONZ/plugins/libde_rest_plugin.so:
	linux-vdso.so.1 (0x0000ffffa16ab000)
	libdeCONZ.so.1 => /usr/lib/libdeCONZ.so.1 (0x0000ffffa1290000)
	libcrypt.so.1 => not found

```

**Comment by quaec** [comment]
I think this issue still persists. I ran into it yesterday when upgrading glibc on Arch Linux.
