### ISSUE TITLE
GLEDOPTO GL-SD-002 Switch Modul

### ISSUE THREAD

**Issue by bruesche** [dresden-elektronik/deconz-rest-plugin#5820]
## Device

- Product name: GLEDOPTO Zigbee Mini Switch Modul
- Manufacturer: GLEDOPTO
- Model identifier: GL-SD-002
- Device type : Switch
 

## Screenshots

<img width="1019" alt="Bildschirmfoto 2022-02-18 um 15 33 03" src="https://user-images.githubusercontent.com/62746518/154914227-9ee46fdb-2768-4397-8a72-8e089d5c9456.png">
<img width="1022" alt="Bildschirmfoto 2022-02-18 um 15 34 07" src="https://user-images.githubusercontent.com/62746518/154914246-73aa042d-13ce-41cf-a0f8-e6a9a2b3c34d.png">
<img width="1025" alt="Bildschirmfoto 2022-02-18 um 15 34 48" src="https://user-images.githubusercontent.com/62746518/154914270-ffcc12fb-3a7d-4448-95ea-3d5745211795.png">

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by bruesche** [comment]
Sorry for that. I will take the screenshots. But I can do that in the next 14 days.. Sorry for that.

**Comment by bruesche** [comment]
so, back again. Hope I get all the screenshots. I try:
<img width="454" alt="Bildschirmfoto 2022-03-04 um 14 57 58" src="https://user-images.githubusercontent.com/62746518/156778489-f5b8189d-fa2e-44e4-9321-159a6ceb5740.png">
<img width="455" alt="Bildschirmfoto 2022-03-04 um 14 58 18" src="https://user-images.githubusercontent.com/62746518/156778534-3ea1bbc9-6181-4c25-b01f-6328e75b0178.png">
<img width="481" alt="Bildschirmfoto 2022-03-04 um 14 58 53" src="https://user-images.githubusercontent.com/62746518/156778545-c856579b-f99c-4707-9944-ac5d3456d606.png">
<img width="391" alt="Bildschirmfoto 2022-03-04 um 14 59 29" src="https://user-images.githubusercontent.com/62746518/156778547-d509e7fa-0f42-43e3-b242-b6c1066f1518.png">
<img width="450" alt="Bildschirmfoto 2022-03-04 um 15 02 32" src="https://user-images.githubusercontent.com/62746518/156778553-0833a572-ed4b-4741-b08c-4f8fc0ab50c7.png">

**Comment by bruesche** [comment]
Please give me advice if something is missing. Thx :)
