### ISSUE TITLE
Tuya Zigbee 3.0 PIR Motion Sensor; _TZ3000_msl6wxk9; TS0202

### ISSUE THREAD

**Issue by J3susC** [dresden-elektronik/deconz-rest-plugin#5823]
## Device

- Product name: ZM-35ZH-Q
- Manufacturer: _TZ3000_msl6wxk9
- Model identifier: TS0202
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

![grafik](https://user-images.githubusercontent.com/80172786/155086240-cc471af8-4594-4d27-b30d-b540349bc15e.png)
![grafik](https://user-images.githubusercontent.com/80172786/155086970-7756be9c-ebe2-4167-9030-1fc694a5c75a.png)

### Basic

![grafik](https://user-images.githubusercontent.com/80172786/155086309-be340df2-d208-4111-bd42-e5f352336f05.png)
![grafik](https://user-images.githubusercontent.com/80172786/155086326-035792f8-b7ce-4af4-866b-5c0907146908.png)

### Identify
![grafik](https://user-images.githubusercontent.com/80172786/155086547-658a8151-3a57-4aa1-9d02-ff40a483dc73.png)
![grafik](https://user-images.githubusercontent.com/80172786/155086564-47b2bd68-bf31-4ee3-8bdf-2ff03b77070a.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/80172786/155087063-498edcb6-2ac5-4f83-af74-014b421e633a.png)

### Other clusters that are not mentioned above
Power
![grafik](https://user-images.githubusercontent.com/80172786/155086714-878ec3ad-0b57-44bb-a935-58b8053a8e16.png)
![grafik](https://user-images.githubusercontent.com/80172786/155086734-eda79fbe-06b5-49ec-9743-9ffffe1675a3.png)

IAS
![grafik](https://user-images.githubusercontent.com/80172786/155086742-e9768785-86a3-4e87-978e-0e4ade3a5564.png)
![grafik](https://user-images.githubusercontent.com/80172786/155086753-02edddc9-1778-4e2f-a73f-3ba65dd65887.png)

**Comment by Mimiix** [comment]
Hi,

There's already a request for this device:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5584

Closing this one.

**Comment by zafnz** [comment]
Can confirm that the provided settings (almost) work, I had to fix some json (missing comma). My device is basically the same sensor, but a slightly different ID. (_TZ3000_otvn3lne)

Otherwise everything I'd expect to work, works.

[otvn3lne.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8492980/otvn3lne.txt)
