### ISSUE TITLE
Issue which deny 65535 transition time

### ISSUE THREAD

**Issue by aryelevin** [dresden-elektronik/deconz-rest-plugin#583]
in the rest_light.ccp, the function which checks transition time checks that its less than 65535 (if (ok && tt < 0xFFFFUL)).

This is a problem, since on ubisys for example, 65535 means "No Fade Effect", so it should be "if (ok && tt <**=** 0xFFFFUL)".

Thanks a lot for the plug in.

**Comment by manup** [comment]
Shouldn't a transition time of 0 also have the "no fade effect"? The lower than 65535 might come from the ZigBee spec, but I'm not sure.
