### ISSUE TITLE
Vikefon temperature & humidity sensor

### ISSUE THREAD

**Issue by superMoYoX** [dresden-elektronik/deconz-rest-plugin#5835]
## Device

- Product name: Vikefon temperature & humidity sensor
- Manufacturer: _TZ3000_fllyghyj
- Model identifier: TS0201
- Device type : 
  - Sensor
Seems to be a bit different that this one : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5613

## Screenshots
![capture1](https://user-images.githubusercontent.com/92474642/155880389-8acc12a2-ccf7-4a6a-97df-e8a4f987f630.PNG)

### Basic : 
![image](https://user-images.githubusercontent.com/92474642/155880233-95148ed9-54ae-4054-9fa3-d7a54afeca7b.png)

Screenshot of Node Info Panel : 
![image](https://user-images.githubusercontent.com/92474642/155879976-57c8f39c-0932-43cd-a463-639a9d835088.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/92474642/155879924-f522b4e0-7fd3-4108-b869-4949dfa542dd.png)

### Identify
![image](https://user-images.githubusercontent.com/92474642/155880080-1a08cb18-03d1-4cdc-b224-e9ed751b7d73.png)

### Temperature Measurement
![image](https://user-images.githubusercontent.com/92474642/155880135-229a5cc6-2830-4cff-9567-df30e73bcddb.png)

### Relative Humidity measurement
![image](https://user-images.githubusercontent.com/92474642/155880155-3fd86922-0522-4fd4-b348-2dca183f5e74.png)

### OTAU
![image](https://user-images.githubusercontent.com/92474642/155880252-3a0cebda-7f21-4a56-a584-51967d094f93.png)

**Comment by Smanar** [comment]
Hello, this device realy look standard I think it can be added using DDF https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

Can start from scratch or just take a working sensor with temperature and humidity and change the usefull part 
Here there is one that make only temperature but I can help you to finish it https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5777/files

Need to update.
```
 "manufacturername": "OWON",
  "modelid": "THS317-ET",
  "product": "THS317-ET",
  "path": "/devices/ths317-et.json",
```

**Comment by superMoYoX** [comment]
Okay thanks !

I promise I'll take some time to understand all of those things.
I'll tell you !

**Comment by leo-beltrao** [comment]
I have the same issue with this device. I will test the proposed solution. Tks

**Comment by leo-beltrao** [comment]
Good news! 
It took me a while to figure out why the Edit DDF was not opening (topic for another question). Anyway,  after restarting deconz,  it worked, and I could create the DDF file with the temperature and humidity using the standard settings. Voilà! It recognized the device. It automatically labels the device as Humidity 52. I could confirm the operation by opening the sensors in Phoscon. It is giving me the two measurements.  See screenshot below.
Thanks for providing the link to DDF Cheat Sheet.

**Comment by leo-beltrao** [comment]
![Screenshots_2022-04-02-10-25-32](https://user-images.githubusercontent.com/92334852/161390631-d848ee33-1585-4807-80a6-23c73aeff0e8.png)
![Screenshots_2022-04-02-10-26-31](https://user-images.githubusercontent.com/92334852/161390632-4d986f38-1ddd-48d8-8821-b308087216ba.png)
![Screenshots_2022-04-02-10-27-05](https://user-images.githubusercontent.com/92334852/161390633-1f61592f-389c-4b72-ae5a-8636e803afa5.png)
![Screenshots_2022-04-02-10-27-45](https://user-images.githubusercontent.com/92334852/161390634-24883b8a-cdc5-4e1b-9c14-e093ad484008.png)
![Screenshots_2022-04-02-10-28-38](https://user-images.githubusercontent.com/92334852/161390635-6bf93425-8257-4a19-9d25-e855df3b806a.png)
![Screenshots_2022-04-02-10-31-39](https://user-images.githubusercontent.com/92334852/161390636-d77af601-af6b-4b82-a056-8875ee986e45.png)
![20220328_223413](https://user-images.githubusercontent.com/92334852/161390637-187128ea-7f84-47cb-8996-ea14d4fa7f5a.jpg)
![20220328_223429](https://user-images.githubusercontent.com/92334852/161390638-2c3aa0e8-6ae0-416b-aa45-f3002079840b.jpg)

**Comment by leo-beltrao** [comment]
I'm not sure if I have a way to apply an offset on top of measurement for humidity. It looks like the values are a bit higher than other sensors. Tks

**Comment by Smanar** [comment]
You have.
If you are sing defaut value, it s managed by the legacy code.
Else you can use as "expression" something like `Item.val = Attr.val + R.item('config/offset').val`

And if you can make a PR to submit your DDF for others ?

**Comment by leo-beltrao** [comment]
@Smanar, I'll need your help. Could you send me instructions on how to send PR? In addition, could you send me further details on how I could create that expression for the offset? I don't know if this needs to be done in deConz or Home Assistance? Tks

**Comment by Smanar** [comment]
Depend of you DDF
If you are just using

```
       {
          "name": "state/temperature"
        },
```


I will be done by legacy code, else if you have forced some value, you can add this expression using the DDF editor (just select state/temperature), you will all field to fill.

To send a PR just go on the folder you want to put your device. I know it's vikefon, but for me its tuya stuff so for exemple here 
https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices/tuya
Choose "add a file" choose a name according to other __TZ3000_fllyghyj_temp_hum_sensor.json for exemple.

Github will say you have not the right on this github, and will create a fork under you name, and at the end you can submit the PR
Don't worry, you can't break something, and all is deletable/editable, so you can retry many time.

If later you want to edit the file (and if no one have already valided it), just go on your fork and edit the file again, all will be synchronised.
