### ISSUE TITLE
BSEED 2 Way Switch _TZ3000_e98krvvk

### ISSUE THREAD

**Issue by h3llh0und** [dresden-elektronik/deconz-rest-plugin#5837]
## Device

- Product name: BSEED Zigbee 2 Way Switch
- Manufacturer: _TZ3000_e98krvvk
- Model identifier: TS0012
- Device type : 
  - Switch

## Screenshots
![image](https://user-images.githubusercontent.com/6917818/156018271-10ed9775-5620-4b64-ab04-6ea90fad6072.png)
![image](https://user-images.githubusercontent.com/6917818/156018341-86ce7194-b3ac-4438-a4ff-8dfc21229588.png)

### Basic
![image](https://user-images.githubusercontent.com/6917818/156018417-2f828d22-2cc2-4a8a-99fd-2536a68b8960.png)

### Identify
![image](https://user-images.githubusercontent.com/6917818/156018718-92f56ff1-53f0-4d9c-b6ff-4f739aeff711.png)

### On/Off
First
![image](https://user-images.githubusercontent.com/6917818/156018946-c28dfcf2-bc1c-4990-b6a0-231b34357b12.png)
Second
![image](https://user-images.githubusercontent.com/6917818/156018991-4793e591-d214-4e59-a70a-18a038215e15.png)

I can turn the switches on and off with the exec Buttons.
If you need more Input just let me know.

**Comment by h3llh0und** [comment]
Ok, i found a quick and dirty solution for me. I created my own DDF File and managed it to get both Switches running. Dont know if this is the best way but it works and i am fine with it.

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_e98krvvk",
  "modelid": "TS0012",
  "product": "TS0012",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/ts0012.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

**Comment by Mimiix** [comment]
Re opening

**Comment by xADDRx** [comment]
> Ok, i found a quick and dirty solution for me. I created my own DDF File and managed it to get both Switches running. Dont know if this is the best way but it works and i am fine with it.
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TZ3000_e98krvvk",
>   "modelid": "TS0012",
>   "product": "TS0012",
>   "sleeper": false,
>   "status": "Gold",
>   "path": "/devices/ts0012.json",
>   "subdevices": [
>     {
>       "type": "$TYPE_ON_OFF_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x01"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/on",
>           "refresh.interval": 5
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     },
>     {
>       "type": "$TYPE_ON_OFF_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x02"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/on",
>           "refresh.interval": 5
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     }
>   ]
> }
> ```

Hi h3llh0und, 

When I use your code both switches toggle on and off together via deconz. No matter which of the two I press. Do you have any idea?

**Comment by di-iode** [comment]
I use your code, I can see the status of the lamps in phoscon but I can't turn them on or off
