### ISSUE TITLE
 XUELILI 16A UK Standards Smart OutletDevice - TS011F - _TZ3000_5f43h46b

### ISSUE THREAD

**Issue by jasonwragg** [dresden-elektronik/deconz-rest-plugin#5840]
## Device

- Product name: XUELILI 16A UK Standards Smart Outlet
- Manufacturer: _TZ3000_5f43h46b
- Model identifier: TS011F
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots

![Screenshot 2022-03-03 091134](https://user-images.githubusercontent.com/53080867/156534150-0c9d6013-b53f-497d-a73a-5139e40659e3.png)
![Screenshot 2022-03-03 091501](https://user-images.githubusercontent.com/53080867/156534165-34953525-e425-436a-a645-17ade5c2c6ac.png)

### Basic
![Screenshot 2022-03-03 091501](https://user-images.githubusercontent.com/53080867/156534944-1d662917-d70e-4cf3-a98d-1c176ddb03bc.png)

### Identify
![Screenshot 2022-03-03 091851](https://user-images.githubusercontent.com/53080867/156534799-a583fd9b-a484-4060-a211-beb196e02255.png)

### On/Off
![Screenshot 2022-03-03 091923](https://user-images.githubusercontent.com/53080867/156534829-5d4206a0-59d5-4683-93ab-23b6b7217c1d.png)

### Simple Metering
![Screenshot 2022-03-03 091739](https://user-images.githubusercontent.com/53080867/156534699-7aa1cb07-c9c8-4844-9973-10623ea968e0.png)

### Electrical Measurement 
![Screenshot 2022-03-03 091754](https://user-images.githubusercontent.com/53080867/156534744-290ece32-83a6-4fa0-86fe-f14958d5dbe5.png)

**Comment by jasonwragg** [comment]
Yes thats correct.

On 3 Mar 2022, at 15:51, Smanar ***@***.***> wrote:

﻿

Hello, this device is working, but you miss the power consumption and ect ?

**Comment by Smanar** [comment]
OK, so ATM DDF are working fine for plug.
Can start from scratch https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
Or just editing a working one https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5475

Change the first lines, take care manufacturername and modelid need to be the same than on deconz.
```
  "manufacturername": "Immax",
  "modelid": "Plug-230V-ZB3.0",
  "vendor": "Immax Neo",
  "product": "07048L",
```

**Comment by ping-localhost** [comment]
This also applies for the EU version of the device. It reports the same items.

**Comment by ping-localhost** [comment]
I would like to get this resolved. Anything I can do to help? :)

**Comment by Smanar** [comment]
Yep https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5840#issuecomment-1059346046

**Comment by proggprod** [comment]
I just got some of these. They get discovered, but I can't turn them on.
They work by pressing the button on the side if I do it before pairing them, but once paired, they wont turn on.
In the phoscon UI if I try to turn them on, they turn on for a moment then go back to off.

Any ideas?

**Comment by proggprod** [comment]
Not sure what I did, but after some clicking around in deCONZ, these now turn on and off. But I'm not getting any energy readings. It's just stuck at 0W.
I'm using OpenHAB with my Raspbee II Pi HAT to control and monitor these items.

**Comment by ping-localhost** [comment]
@proggprod I, personally, have switched to Zigbee2MQTT (using a SONOFF Zigbee 3.0 USB Dongle Plus). It found the device, I was able to update the firmware and now it works perfectly.

**Comment by proggprod** [comment]
> @proggprod I, personally, have switched to Zigbee2MQTT (using a SONOFF Zigbee 3.0 USB Dongle Plus). It found the device, I was able to update the firmware and now it works perfectly.

So you think it needs new firmware?

**Comment by proggprod** [comment]
![image](https://user-images.githubusercontent.com/81530084/184618209-6bf96fd3-c604-4a68-9082-79ae49a37901.png)
It seems to get the readings in deCONZ, but it doesn't come out the other end (OpenHAB)

**Comment by Mimiix** [comment]
Please guys, read smanars comment: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5840#issuecomment-1086803585

**Comment by proggprod** [comment]
> Please guys, read smanars comment: [#5840 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5840#issuecomment-1086803585)

Thank you. I read this but maybe I don't understand. Is this suggesting that I just populate those four fields? : "manufacturername": "_TZ3000_5f43h46b",
  "modelid": "TS011F",
  "vendor": "Tuya",
  "product": "XXXXX",

And does this actually mean XXXXX or am I supposed to change this to something?

**Comment by Smanar** [comment]
Try this DDF


```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_5f43h46b",
  "modelid": "TS011F",
  "product": "XUELILI 16A UK Standards Smart OutletDevice",
  "vendor": "XUELILI ",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0B04"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 300
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 300
        },
        {
          "name": "state/voltage",
          "refresh.interval": 300
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0702"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "read": {"at": "0x0000", "cl": "0x0702", "ep": 0, "fn": "zcl" },
          "parse": {"at": "0x0000", "cl": "0x0702", "ep": 0, "eval": "Item.val = Attr.val * 10"},
          "refresh.interval": 300
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by proggprod** [comment]
Thanks for that. I managed to make this DDF file and the nodes load it up properly and it looks normal, but they have now gone back to not turning on, or turning on for 1 - 4 seconds then turning off again. They also don't respond to pressing the button on the  side.
I'm sure it's not a dud one because I have a few of them here and they all do the same.

**Comment by proggprod** [comment]
I can confirm that this DDF works. I managed to get a plug to stay on for long enough to verify I was getting energy readings in OpenHAB.
They still usually turn off after a few seconds though. Even without anything plugged in. Sometimes it will stay on for a few mins with a battery charger plugged in drawing 75W. ???

**Comment by Smanar** [comment]
There is a post on z2m abut this issue https://github.com/Koenkk/zigbee2mqtt/issues/11648

**Comment by proggprod** [comment]
Thanks, I already saw this.
I think it's over voltage protection. My voltage varies between 238 and 241, which is why is was working sometimes and not at all sometimes. The product page says 90 - 250V, but it is very repeatable now that I'm looking for it. It would also explain why it happens whether paired to a hub or not. Then again, I've been wrong before...
