### ISSUE TITLE
Add Support for LIVARNO LUX FB20-002 Remote ControlDevice name

### ISSUE THREAD

**Issue by frontibit** [dresden-elektronik/deconz-rest-plugin#5847]
i want to reopen https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5375
as a request to have this device added.
The buttons on the device are not visible or functional. 

## Device

- Product name: Livaro Lux FB20-002 remote
- Manufacturer: ALIVARNO LUX
- Model identifier:  FB20-002
- Device type : 
  - Remote
  - Switch (?)

## Screenshots

![image](https://user-images.githubusercontent.com/6206894/157049686-a89c70b6-7aa3-466b-bac3-eb27114ae00e.png)

![image](https://user-images.githubusercontent.com/6206894/157049531-57e8163a-1817-42b1-ada5-5f114993f9d0.png)

![image](https://user-images.githubusercontent.com/6206894/157049451-28a002cc-2f2d-4e45-a12b-53136a86ef35.png)

### Basic
![image](https://user-images.githubusercontent.com/6206894/157049821-39c67b3c-ea61-4012-9333-f77deab65a4b.png)

### Identify
![image](https://user-images.githubusercontent.com/6206894/157049857-ac2715b3-0be4-4710-ac83-0a3ec84a96d6.png)

### Groups
![image](https://user-images.githubusercontent.com/6206894/157049917-6bacbc0d-41c6-4c26-9730-773241d5591b.png)

### On/Off

![image](https://user-images.githubusercontent.com/6206894/157050100-f3dbbe60-49b7-414a-b2bd-ef0f7510147d.png)

### Level Control
![image](https://user-images.githubusercontent.com/6206894/157050051-0562ce79-a7c9-4488-8e3d-21a5995f9acf.png)

**Comment by Mimiix** [comment]
The basic cluster screenshot is a bit unclear, as it hides the manufacturer name. Can you please make sure all info is visible?

**Comment by Pe-MaKer** [comment]
After two years, I kindly ask to reopen this issue.

**Comment by Mimiix** [comment]
@Smanar can you help out?

**Comment by Smanar** [comment]
This device is already in the code 

`    { "_TYZB01_bngwdjsr", "TS1001",  "LIDL Livarno Lux", "HG06323" }, // Remote Control``

Are you sure your device is not reconised ? it's possible the lidl code is broked, but it can work for someone.

Need to make some checks first to see.

The name is not on form 0xXXXX, it's you that have changed it or the API ?
Can you check if you have something in the API about this device ? Using phoscon/help/API information/sensor, take care lidl stuff can be renamed according to planet alignement by code.
It's possible the device is present in the API but button event are not reconised

On button_maps.json

```
        "lidlMap": {
            "vendor": "LIDL Livarno Lux",
            "doc": "LIDL / Livarno Lux Remote Control (_TYZB01_bngwdjsr)",
            "modelids": ["HG06323"],
            "buttons": [
              {"S_BUTTON_1": "On"},
              {"S_BUTTON_2": "Dim Up"},
              {"S_BUTTON_3": "Dim Down"},
              {"S_BUTTON_4": "Off"}
            ],
```



Replace 
`"modelids": ["HG06323"],`

By

"modelids": ["_TYZB01_bngwdjsr"],
