### ISSUE TITLE
GLEDOPTO Zigbee Mini Switch Modul

### ISSUE THREAD

**Issue by bruesche** [dresden-elektronik/deconz-rest-plugin#5849]
## Device

Product name: GLEDOPTO Zigbee Mini Switch Modul
Manufacturer: GLEDOPTO
Model identifier: GL-SD-002
Device type : Switch

## Screenshots
<img width="391" alt="Bildschirmfoto 2022-03-04 um 14 59 29" src="https://user-images.githubusercontent.com/62746518/157453725-72a4cc50-8522-438b-be7d-ea20211de709.png">

<img width="454" alt="Bildschirmfoto 2022-03-04 um 14 57 58" src="https://user-images.githubusercontent.com/62746518/157453855-582a2ac8-b1aa-42a0-921e-204deff36eb4.png">

<img width="455" alt="Bildschirmfoto 2022-03-04 um 14 58 18" src="https://user-images.githubusercontent.com/62746518/157453889-910b9ce3-3d1f-49e1-872f-9cfe95fbc71a.png">

<img width="455" alt="Bildschirmfoto 2022-03-04 um 15 01 38" src="https://user-images.githubusercontent.com/62746518/157454041-c6f87eb8-6c95-43fd-afeb-72ecb2adb5cd.png">
<img width="457" alt="Bildschirmfoto 2022-03-04 um 15 01 06" src="https://user-images.githubusercontent.com/62746518/157454052-33bea70d-6045-4645-b7b6-cde2b2a2f9fd.png">
<img width="459" alt="Bildschirmfoto 2022-03-04 um 15 00 41" src="https://user-images.githubusercontent.com/62746518/157454054-4f4f02ed-27ec-4b6d-88aa-11c6e8652c10.png">

<img width="450" alt="Bildschirmfoto 2022-03-04 um 15 02 32" src="https://user-images.githubusercontent.com/62746518/157454126-dd5768c2-9bc3-44d6-a6b6-4aa10636eb71.png">

**Comment by bruesche** [comment]
Sorry that last time screenshots missing. Hope everything is now fine.

**Comment by bruesche** [comment]
Only a comment to clear the stale lable.

**Comment by Mimiix** [comment]
@Smanar can this be done with ddf?

**Comment by bruesche** [comment]
I don‘t know

**Comment by bruesche** [comment]
I will try it. After eastern is the next Test Slot. Sorry for the delay. I give a comment, if it works or if need help

**Comment by bruesche** [comment]
While quarantine of Family and Friends I can‘t try. I try it next Time i can See my friend. Sorry for the delay

**Comment by bruesche** [comment]
Must be tested. Hope next week. Sorry für delay.

**Comment by bruesche** [comment]
To be continued

**Comment by bruesche** [comment]
Worked for me. Very easy, very simple. Thanks a lot

**Comment by Mimiix** [comment]
Can you perhaps create a PR for this device so others can benefit it as well?

**Comment by bruesche** [comment]
How can I do this? Need advice. And it’s Not my device. It is from a friend. Holidays and so. 

If I have advice what to do, i can Open the issue to give the PR (???) to you. Think this is in some weeks. Summer and so

**Comment by Smanar** [comment]
You can share the DDF using this post I will make the PR.
Else can just create a file (and a folder GLEDOPTO ) here https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices using "add file", it will create a fork under your name, create the file and prepare the PR.

**Comment by bruesche** [comment]
Hi, ok, Hope i can do this after holidays. I held this Thread open.

**Comment by Smanar** [comment]
Depend of OS, if you select the node than "edit DDF", you will see the folder and path on editor title.
Else on linux 

> 
All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

**Comment by bruesche** [comment]
[gl-sd-002.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9121428/gl-sd-002.txt)
 
Here is the file that worked for me. Have renamed it to txt. You musst only change to json.
Hope everything is correct.

Thanks a lot for your help.
