### ISSUE TITLE
Is the power consuming sensor of Osram Smart+ plug working?

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#586]
I get either 0 watts when it's off, or 40 watts when it's on, no matter if the appliance powered by it is on or off.

Do I have to configure it somehow?

**Comment by dergreg** [comment]
It's a known issue with the Osram Smart Plugs. They don't report anything useful, even though they claim to support the appropriate ZHA cluster.

**Comment by FezVrasta** [comment]
thanks @dergreg does it mean that the hardware itself is not reporting the correct value or is just a DeCONZ limitation?

**Comment by dergreg** [comment]
Yeah unfortunately it‘s a fault of the hardware (or firmware) of the plug itself.

**Comment by FezVrasta** [comment]
Oh that sucks.. thanks for the info!
