### ISSUE TITLE
1CH Zigbee Switch Module-L

### ISSUE THREAD

**Issue by optikkore** [dresden-elektronik/deconz-rest-plugin#5861]
## Device

- Product name: 1CH Zigbee Switch Module-L
- Manufacturer: _TZ3000_ji4araar
- Model identifier: TS0011
- Device type : 
  - Switch

## Screenshots
![image](https://user-images.githubusercontent.com/10768026/158005681-2ea468db-3fa8-4b88-ba5f-8d4c50481c8f.png)
![image](https://user-images.githubusercontent.com/10768026/158005700-422a9d82-d58d-4a10-bb63-f075fefdfed8.png)
![image](https://user-images.githubusercontent.com/10768026/158005787-7215f66d-c531-48fc-a89f-f37552b343fb.png)

**Comment by Mimiix** [comment]
Not all screens are there, but there's a ddf in the pr list.

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5839

So if you import that, you can use it :)

**Comment by optikkore** [comment]
@Mimiix Pardon my ignorance do since I am in an HA addon I assume I need to add the file to the docker container?

**Comment by Mimiix** [comment]
I think so, yes :)
