### ISSUE TITLE
EasyAccess EasyFingerTouch

### ISSUE THREAD

**Issue by ZeppDK** [dresden-elektronik/deconz-rest-plugin#5870]
## Device

    Product name: EasyAccess EasyFingerTouch
    Manufacturer: Onesti Products AS
    Model identifier: EasyFingerTouch
    Device type :
        Lock

## Screenshots
![billede](https://user-images.githubusercontent.com/7306325/158344462-01f1f3ad-0c00-4d1a-a73f-4477738429f7.png)

### Basic
![billede](https://user-images.githubusercontent.com/7306325/158344621-71f9b05e-5beb-4258-b4ac-bd3d74b5786a.png)

### Identify
![billede](https://user-images.githubusercontent.com/7306325/158344765-017ae943-e6a3-45fc-839c-5aafa1278139.png)

### Groups
![billede](https://user-images.githubusercontent.com/7306325/158344904-a903148c-b4ee-470a-abc3-87bc904b863e.png)
![billede](https://user-images.githubusercontent.com/7306325/158344982-863f9774-156b-4e9a-ba11-55ed235e4228.png)

### Door Lock
![billede](https://user-images.githubusercontent.com/7306325/158345372-4967b9eb-97db-47ed-8c77-1c3d88136f83.png)
![billede](https://user-images.githubusercontent.com/7306325/158345454-e98f83ac-b035-4756-8d0d-ffa1710499fa.png)
![billede](https://user-images.githubusercontent.com/7306325/158345555-96dbac0b-626d-4cb3-b331-a0e69cd79156.png)
![billede](https://user-images.githubusercontent.com/7306325/158345632-2c9c257d-13f5-4bdb-aa36-5ebe956eb454.png)
![billede](https://user-images.githubusercontent.com/7306325/158345903-644dcce1-936a-4853-ac83-c4c96488ca80.png)
![billede](https://user-images.githubusercontent.com/7306325/158346017-e19caa16-f521-4184-9183-7598aa5909a8.png)
![billede](https://user-images.githubusercontent.com/7306325/158346101-2193c2f9-d07f-4c88-91fb-67d7a9ee1d84.png)
![billede](https://user-images.githubusercontent.com/7306325/158346166-c46127e5-bb79-4fd1-a820-f7505a7d3d52.png)

### OTAU
![billede](https://user-images.githubusercontent.com/7306325/158346525-7ae60dab-10ce-49e2-aa5a-adc53aed1652.png)
![billede](https://user-images.githubusercontent.com/7306325/158346723-163a8a45-f499-4f54-8769-c84939c05a4d.png)

**Comment by ZeppDK** [comment]
there seems to be an older version of the lock already added, so i hope this one will be straight forward :-)
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4253

**Comment by Smanar** [comment]
Hello, but the problem is now we need to use DDF to add device.
Someone have started for a doorlock too, but have give up if you want to test on your side ? https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5775

**Comment by Smanar** [comment]
Hello, if you want to start from scratch, I have made a PR for some missing file https://github.com/Smanar/deconz-rest-plugin/commit/770b4e0ea9b65d931591c544aa9778fd11a02e8b
And an error here https://github.com/Smanar/deconz-rest-plugin/commit/db05ea518b2caf4bb1bd783213577e22bd50a517

You need to restart deconz after adding the files

After that

-    delete all previous DDF for this device
-    right clic on the node, "edit DDF"
-    if not automatically filled, fill manufacture name and model id (using drag and drop)
-    set the status to "gold"
-    if not made automatically, drag and drop a Door Lock device
-    Save file
-    Make hot reload,
-    Check the result in the API using third app or phoscon (help / API information)

**Comment by Smanar** [comment]
@ZeppDK do you need some help ?
You don't need to compile code, just add/edit file, will be easier on docker install ?

**Comment by ZeppDK** [comment]
> @ZeppDK do you need some help ?
> You don't need to compile code, just add/edit file, will be easier on docker install ?

I have added the files, restartet, and gotten a  new DDF file with the new lock type..
But still needs to find out how to get it to use the actual info from the lock shown in the pictures under “door lock”

**Comment by Smanar** [comment]
I m not sure to understand ?
Wich one picture ?
The device is reconised ?

**Comment by ZeppDK** [comment]
after i added your new files, i made a DDF, and added this from the list manually... 
![billede](https://user-images.githubusercontent.com/7306325/159232739-dfea4ca3-b2de-4bba-8a72-ada603c29af4.png)

**Comment by ZeppDK** [comment]
here is the API
![billede](https://user-images.githubusercontent.com/7306325/159233170-6879da26-fe5f-479b-b4dc-6ed536d43296.png)

**Comment by ZeppDK** [comment]
so like this?

> {
  "schema": "devcap1.schema.json",
  "manufacturername": "Onesti Products AS",
  "modelid": "EasyFingerTouch",
  "vendor": "EasyAccess",
  "product": "EasyFingerTouch",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/easyfingertouch.json",
  "subdevices": [
    {
      "type": "$TYPE_DOOR_LOCK",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate"
        },
        {
          "name": "state/open"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    }
  ]
}

**Comment by ZeppDK** [comment]
![billede](https://user-images.githubusercontent.com/7306325/159420030-adb91c86-4b18-4b7f-aa12-43b5d3ace5c7.png)
![billede](https://user-images.githubusercontent.com/7306325/159420115-88d7e129-2088-49d9-a1bd-baf2a622f3ac.png)

that works for lock/unlock of the outside of the lock :)

**Comment by Smanar** [comment]
Nice, next step the battery
- add a "config/battery" to the DDF
- configure the battery bind, Cluster 0x0001 on right panel, and attribute 0x20 on left panel
- Values for reporting min 300, max 2700, change 1

Make state/lockstate working
- select state/lockstate
- fill the "read" and "parse" part using as value (ZCL)

Cluster 0x0101
Attribute 0x0000
endpoint 0x0B or 11 (I don't remember if it's hexa or not
Expression : if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }

**Comment by Smanar** [comment]
@ZeppDK need more guidance ?

**Comment by ZeppDK** [comment]
Maybe.. but have not had time to test yet

**Comment by Smanar** [comment]
NP, just ask, I will make a PR to be sure don't forget missing file on future deconz version

**Comment by ZeppDK** [comment]
this is after adding the config you provided:
![image](https://user-images.githubusercontent.com/7306325/160598310-238fa224-a1a9-430d-a2c3-22cd4cf033a7.png)

**Comment by ZeppDK** [comment]
the lock state looks weird, as it says open, even though the door is locked...
so maybee i should switch the open/closed like this?
if (Attr.val == 1) { Item.val = 'closed' } else if (Attr.val == 2) { Item.val = 'open' } else { Item.val = 'error' }

i'll double check when i get home.

**Comment by ZeppDK** [comment]
![image](https://user-images.githubusercontent.com/7306325/160658807-5504a773-2480-44ad-96c5-42c6e0d36de7.png)

**Comment by ZeppDK** [comment]
this is how it looks at the moment

`{
  "schema": "devcap1.schema.json",
  "manufacturername": "Onesti Products AS",
  "modelid": "EasyFingerTouch",
  "vendor": "EasyAccess",
  "product": "EasyFingerTouch",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/easyfingertouch.json",
  "subdevices": [
    {
      "type": "$TYPE_DOOR_LOCK",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 0) { Item.val = 'open' } else if (Attr.val == 1) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}`

**Comment by Smanar** [comment]
You can remove state/reachable
For state/open as it's a bool I think it s better to use "Item.val = Attr.val != 1" whith that you will have open= false only if the door is closed, if you have error you will have open = true.
For state/locked I would try "if (Attr.val == 1) { Item.val = 'locked' } else if (Attr.val == 2) { Item.val = 'unlocked' } else { Item.val = 'error' }",

I don't understanbd why battery is not working.
Can you try to read the attribute 0x0020 in the cluster 0x0001 in deconz ?

**Comment by ZeppDK** [comment]
![billede](https://user-images.githubusercontent.com/7306325/161568652-ebf9b35c-45fc-4b2e-b4b6-66c5ff965673.png)

**Comment by ZeppDK** [comment]
battery not showing much in deconz either :-)

![billede](https://user-images.githubusercontent.com/7306325/161569100-9754b2b7-777f-4be6-af70-74ccb5b7ac86.png)

**Comment by ZeppDK** [comment]
lockstate is showing the correct state now.
thats the most important feature :D

**Comment by Smanar** [comment]
Ha ?
State/lockstate  is something new but from my memory it can expose config/lock (so only a bool value) but it s same than State/lockstate

And for state/open ? Need to expose a bool value too (true/false) for the door state.

```

{
  "name": "state/open",
  "read": {
    "at": "0x0003",
    "cl": "0x0101",
    "ep": 11,
    "fn": "zcl"
  },
  "parse": {
    "at": "0x0003",
    "cl": "0x0101",
    "ep": 11,
    "eval": "Item.val = Attr.val != 1",
    "fn": "zcl"
  }
}
```

```
{
  "bind": "unicast",
  "src.ep": 11,
  "cl": "0x0101",
  "report": [
    {
      "at": "0x0003",
      "dt": "0x30",
      "min": 1,
      "max": 300
    }
  ]
}
```

**Comment by Smanar** [comment]
@ZeppDK Do you want I remake the full DDF ?

**Comment by ZeppDK** [comment]
Not yet, havent had time 😊

**Comment by oskretc** [comment]
Anyway we can reopen this and move forward to support the device?

**Comment by Mimiix** [comment]
@oskretc  Are you able to test the DDF :)?

**Comment by oskretc** [comment]
@Mimiix I can give it a try, 
I'm running docker deconzcommunity/deconz 
I'm not sure where the DDF should go?
Any docs on how to test/debug the DDF?

**Comment by Smanar** [comment]
Yes It's easier on docker than on the "HA docker", but you can find usefull information here https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

If I m right on docker you have a mounter folder for the /usr/share/deCONZ/ folder, so you will find the "devices" folder in it

The theory : you just need to create a what_you_want.json file with this contain in the deconz "devices" folder, then just re-include the device, if you have the GUI can use the "Hot reload" command in the editor.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by oskretc** [comment]
Yeap, I find all the info, tested the latest DDF and it seems to be working with a few details, 
1. I can see the sensor in the API, but it doesnt show up in the Phoscon app or a third party (HomeAssistant), is something missing from the image below that will prevent it from showing in the UI
2. battery Voltage is readout is 45 (cl 0x0001 at 0x0020) which seems to be the voltage x 10 as in 3 1.5 volts battery
3. battery percentage (cl 0x0001 at 0x0021) readout is 200 maybe we can use that by just dividing by 2, not sure what are the Min interval and Max interval doing.
4.

![image](https://user-images.githubusercontent.com/4963991/189758647-4da007ce-9a48-4f1e-adf8-68e66d735fec.png)

**Comment by oskretc** [comment]
The image above is using attribute 0x0021 so I have sorted it out. only last thing to verify is when battery percentage decreases, works as expected. I'll keep an eye on it

Yes, I'm sure HA cant see it, I have reloaded both the phosco docker (in a separate rpi) and HA just to  be sure and nothing. 

Any ideas?

**Comment by Smanar** [comment]
Heee, I don't use HA, so I can't help you so much, but I m sure it's suported.

I use my joker, @Kane610 have you an idea ^^ ?

**Comment by Smanar** [comment]
Har, I think I have see the problem
The type is "Door lock", it s the type for "light", for sensor the type need to be "ZHADoorLock"

**Comment by oskretc** [comment]
I guess you meant changing the Doo Lock (1) on the left panel for a ZHADoorLock, but that item is not available in the "Available items" panel. 
If I try to manually change th Type: Door Lock in the middle panel, it turns blue and nothing happens
Also, the file "devices/generic/constants.json" doesnt have an entry for ZHADoorLock not sure if it matters though

**Comment by Smanar** [comment]
Yeah, if I m right I will make a PR to correct that, for the moment can you edit direclty the DDF file ?

**Comment by oskretc** [comment]
I did, and yes, the sensor is shown in HA, but the lock is unavailable
![image](https://user-images.githubusercontent.com/4963991/190000239-32eafc87-9464-465a-8eba-13414d5cfbf9.png)

**Comment by Smanar** [comment]
Does it mean config/recheable  = false ?
Can you check the device json now ?

**Comment by oskretc** [comment]
Added reachable and nothing changed

looking at the HA logs it seems that the lock code in deconz plugin for HA is not aligned with this DDF

> `Logger: homeassistant.components.lock
Source: components/deconz/lock.py:61
Integration: Lock (documentation, issues)
First occurred: 22:44:24 (2 occurrences)
Last logged: 22:44:24

Error adding entities for domain lock with platform deconz
Error while setting up deconz platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 188, in state
    if (locked := self.is_locked) is None:
  File "/usr/src/homeassistant/homeassistant/components/deconz/lock.py", line 61, in is_locked
    return self._device.is_locked
  File "/usr/local/lib/python3.10/site-packages/pydeconz/models/sensor/door_lock.py", line 45, in is_locked
    return self.lock_state == DoorLockLockState.LOCKED
  File "/usr/local/lib/python3.10/site-packages/pydeconz/models/sensor/door_lock.py", line 50, in lock_state
    return DoorLockLockState(self.raw["state"]["lockstate"])
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'open' is not a valid DoorLockLockState
`

**Comment by Kane610** [comment]
The door lock state are expected to be one of four values and open is not one of them https://github.com/Kane610/deconz/blob/0b5b0b5cfa5d31ac12f121aee2f99c234ad9c426/pydeconz/models/sensor/door_lock.py#L9

**Comment by Smanar** [comment]
Arf right.

It's from the DDF

```
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
```

But it can be native, it s in the code, IDK why in the old version it s used direclty in the DDF ....
I have updated the DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Onesti Products AS",
  "modelid": "EasyFingerTouch",
  "vendor": "EasyAccess",
  "product": "EasyFingerTouch",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_DOOR_LOCK",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0101"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 0) { Item.val = 'not fully locked' } else if (Attr.val == 1) { Item.val = 'locked' } else if (Attr.val == 2) { Item.val = 'unlocked' } else { Item.val = 'undefined' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val != 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    }
  ]
}
```

Take care this DDF will generate a new unique ID, I forget to add the cluster on the previous one.

**Comment by oskretc** [comment]
That definitly did the trick, No I can lock and unlock from HA, and see the changes on HA when the door is unlocked.

this is the DDF I end up using, Notice the battery part as well as the type.

`{
  "schema": "devcap1.schema.json",
  "manufacturername": "Onesti Products AS",
  "modelid": "EasyFingerTouch",
  "vendor": "EasyAccess",
  "product": "EasyFingerTouch",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/easyfingertouch.json",
  "subdevices": [
    {
      "type": "ZHADoorLock",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x0b"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 11,
            "eval": "Item.val = Attr.val/2",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val ==1",
            "fn": "zcl"
          }
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 0) { Item.val = 'not fully locked' } else if (Attr.val == 1) { Item.val = 'locked' } else if (Attr.val == 2) { Item.val = 'unlocked' } else { Item.val = 'undefined' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val !=1",
            "fn": "zcl"
          }
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}`

**Comment by Smanar** [comment]
>Next thing I will like to have is report back the last user operating the lock, any ideas?

You mean according to the pin code used ? Because your doorlock have a keypad ?
There is something started here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4876 but never valided
