### ISSUE TITLE
ERIA Smart Wireless Dimming Switch Remote 81825 doesn't work as advertised

### ISSUE THREAD

**Issue by RudolfRendier** [dresden-elektronik/deconz-rest-plugin#5876]
## Describe the bug

Device doesn't work. Can be paired. Shows up in deCONZ, with hex-name. No events visible in Home Assistant.

Product name: ERIA Smart Wireless Dimming Switch Remote
Manufacturer: ADUROLIGHT
Model identifier: Adurolight_NCC
Device type: Switch
https://adurosmart.com/product/eria-smart-wireless-dimming-switch-remote/

There are existing issues for this device, and it should work, but it doesn't:
dresden-elektronik/deconz-rest-plugin#4495
dresden-elektronik/deconz-rest-plugin#3383

## Steps to reproduce the behavior

1. Reset the device by holding both arrow-buttons, until it flashes
1. Enable searching for switches in Phoscon
1. Hold the off button until the remote blinks
1. Watch in deCONZ for the device to show up
1. Check HA for deconz_events when pressing a button

## Expected behavior

No events shown.

## Screenshots
https://i.postimg.cc/HV5ChJxS/audrolight.png

## Environment

- Intel NUC i3, running proxmox OS and Home Assistant OS with the core_deconz addon
- Firmware version: (26720700)
- deCONZ version: (2.14.01 / 06/02/2022)
- ConBee II
- extension cable: yes
- other devices: yes, rfxcom

Recently migrated from RPi3 HASSOS with Raspbee, didn't work on that hardware either.

## deCONZ Logs

This line must mean something, it appears once every time I press a button
(every button, twice)
Line 87: 10:58:02:728 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 96: 10:58:03:542 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 98: 10:58:04:350 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 100: 10:58:05:177 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 102: 10:58:06:113 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 110: 10:58:06:855 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 118: 10:58:07:622 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
Line 120: 10:58:08:309 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01

Here's the full log, for context:
10:57:43:502 ZDP Mgmt_Lqi_rsp zdpSeq: 166 from 0x000B57FFFEB16C20 total: 12, startIndex: 3, listCount: 3
10:57:43:503 * neighbor: 0x00158D0006E124F8 (0x4522), LQI: 63, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:57:43:504 * neighbor: 0x0C4314FFFEFC122E (0x4F9F), LQI: 95, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:57:43:506 * neighbor: 0x00178801067DF434 (0x66F3), LQI: 123, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:57:44:041 APS-DATA.request id: 65, addrmode: 0x03, addr: 0x0017880104a0c7cd, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
10:57:44:066 APS-DATA.confirm id: 65, status: 0x00 SUCCESS
10:57:44:068 APS-DATA.confirm request id: 65 -> erase from queue
10:57:44:123 APS-DATA.indication srcAddr: 0xf794, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -70
10:57:44:125 APS-DATA.request id: 65 erase from queue
10:57:44:127 ZCL got data for node=0xF794, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:57:47:440 Skip idle timer callback, too early: elapsed 923 msec
10:57:48:341 APS-DATA.request id: 86, addrmode: 0x03, addr: 0x588e81fffed3979d, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:57:48:384 APS-DATA.confirm id: 86, status: 0x00 SUCCESS
10:57:48:386 APS-DATA.confirm request id: 86 -> erase from queue
10:57:48:426 APS-DATA.indication srcAddr: 0xcd84, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -76
10:57:48:427 APS-DATA.request id: 86 erase from queue
10:57:48:428 ZCL got data for node=0xCD84, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:57:48:429 ZCL got data for node=0xCD84, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:57:48:430 ZCL got data for node=0xCD84, cl=0x0B04, at=0x050B, status=0x00, type=0x29
10:57:48:741 APS-DATA.request id: 90, addrmode: 0x03, addr: 0x588e81fffed3a0e5, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:57:48:766 APS-DATA.confirm id: 90, status: 0x00 SUCCESS
10:57:48:769 APS-DATA.confirm request id: 90 -> erase from queue
10:57:48:832 APS-DATA.indication srcAddr: 0xbdec, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -74
10:57:48:833 APS-DATA.request id: 90 erase from queue
10:57:48:834 ZCL got data for node=0xBDEC, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:57:48:835 ZCL got data for node=0xBDEC, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:57:48:836 ZCL got data for node=0xBDEC, cl=0x0B04, at=0x050B, status=0x00, type=0x29
10:57:49:740 APS-DATA.request id: 96, addrmode: 0x03, addr: 0x588e81fffed4aed0, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:57:49:764 APS-DATA.confirm id: 96, status: 0x00 SUCCESS
10:57:49:766 APS-DATA.confirm request id: 96 -> erase from queue
10:57:49:827 aps request id: 96 finished, erase from queue
10:57:49:840 APS-DATA.indication srcAddr: 0xf801, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -76
10:57:49:842 ZCL got data for node=0xF801, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:57:49:843 ZCL got data for node=0xF801, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:57:49:845 ZCL got data for node=0xF801, cl=0x0B04, at=0x050B, status=0x00, type=0x29
10:57:51:740 APS-DATA.request id: 106, addrmode: 0x03, addr: 0x588e81fffed3a0b8, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:57:51:761 APS-DATA.confirm id: 106, status: 0x00 SUCCESS
10:57:51:762 APS-DATA.confirm request id: 106 -> erase from queue
10:57:51:785 aps request id: 106 finished, erase from queue
10:57:51:823 APS-DATA.indication srcAddr: 0xd792, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -76
10:57:51:824 ZCL got data for node=0xD792, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:57:51:826 ZCL got data for node=0xD792, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:57:51:826 ZCL got data for node=0xD792, cl=0x0B04, at=0x050B, status=0x00, type=0x29
10:57:53:447 GW firmware version is up to date: 0x26720700
10:57:53:540 APS-DATA.request id: 115, addrmode: 0x03, addr: 0x0017880104d37752, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
10:57:53:585 APS-DATA.confirm id: 115, status: 0x00 SUCCESS
10:57:53:587 APS-DATA.confirm request id: 115 -> erase from queue
10:57:53:610 APS-DATA.indication srcAddr: 0x1211, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -55
10:57:53:611 APS-DATA.request id: 115 erase from queue
10:57:53:613 ZCL got data for node=0x1211, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:57:57:841 APS-DATA.request id: 135, addrmode: 0x03, addr: 0x00158d0006e124f8, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
10:57:57:873 APS-DATA.confirm id: 135, status: 0x00 SUCCESS
10:57:57:875 APS-DATA.confirm request id: 135 -> erase from queue
10:57:57:926 APS-DATA.indication srcAddr: 0x4522, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -34
10:57:57:928 APS-DATA.request id: 135 erase from queue
10:57:57:929 ZCL got data for node=0x4522, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:57:57:930 APS-DATA.request id: 137, addrmode: 0x02, addr: 0x4522, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x04
10:57:57:945 APS-DATA.confirm id: 137, status: 0x00 SUCCESS
10:57:57:947 APS-DATA.confirm request id: 137 -> erase from queue
10:57:57:990 aps request id: 137 finished, erase from queue
10:57:58:441 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
10:57:58:884 Mgmt_Lqi_req zdpSeq: 170 to 0x000B57FFFEB16C20 start index 6
10:57:58:885 APS-DATA.request id: 142, addrmode: 0x03, addr: 0x000b57fffeb16c20, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
10:57:58:907 APS-DATA.confirm id: 142, status: 0x00 SUCCESS
10:57:58:909 APS-DATA.confirm request id: 142 -> confirmed, timeout 161690446
10:57:58:974 APS-DATA.indication srcAddr: 0xf697, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -64
10:57:58:975 APS-DATA.indication request id: 142 -> finished
10:57:58:976 APS-DATA.request id: 142 erase from queue
10:57:58:977 ZDP status = 0x00 -> SUCCESS
10:57:58:978 ZDP Mgmt_Lqi_rsp zdpSeq: 170 from 0x000B57FFFEB16C20 total: 12, startIndex: 6, listCount: 3
10:57:58:981 * neighbor: 0x0017880104E3DF55 (0xB84C), LQI: 55, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:57:58:983 * neighbor: 0x588E81FFFED3A0E5 (0xBDEC), LQI: 39, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:57:58:984 * neighbor: 0x000D6FFFFE9D52A3 (0xC2D0), LQI: 111, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:58:01:040 APS-DATA.request id: 155, addrmode: 0x03, addr: 0x00178801067df434, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
10:58:01:064 APS-DATA.confirm id: 155, status: 0x00 SUCCESS
10:58:01:065 APS-DATA.confirm request id: 155 -> erase from queue
10:58:01:113 APS-DATA.indication srcAddr: 0x66f3, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -54
10:58:01:114 APS-DATA.request id: 155 erase from queue
10:58:01:114 ZCL got data for node=0x66F3, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:02:140 APS-DATA.request id: 161, addrmode: 0x03, addr: 0x0017880104e3df55, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
10:58:02:158 APS-DATA.confirm id: 161, status: 0x00 SUCCESS
10:58:02:160 APS-DATA.confirm request id: 161 -> erase from queue
10:58:02:196 aps request id: 161 finished, erase from queue
10:58:02:205 APS-DATA.indication srcAddr: 0xb84c, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -65
10:58:02:206 ZCL got data for node=0xB84C, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:02:723 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:02:728 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:03:341 APS-DATA.request id: 169, addrmode: 0x03, addr: 0x588e81fffed3a0e5, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
10:58:03:362 APS-DATA.confirm id: 169, status: 0x00 SUCCESS
10:58:03:365 APS-DATA.confirm request id: 169 -> erase from queue
10:58:03:420 aps request id: 169 finished, erase from queue
10:58:03:431 APS-DATA.indication srcAddr: 0xbdec, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -73
10:58:03:433 ZCL got data for node=0xBDEC, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:03:488 skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
10:58:03:537 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:03:542 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:04:345 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:04:350 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:05:172 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:05:177 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:06:082 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:06:113 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:06:140 APS-DATA.request id: 185, addrmode: 0x03, addr: 0x588e81fffed3979d, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
10:58:06:188 APS-DATA.confirm id: 185, status: 0x00 SUCCESS
10:58:06:190 APS-DATA.confirm request id: 185 -> erase from queue
10:58:06:271 APS-DATA.indication srcAddr: 0xcd84, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -76
10:58:06:273 APS-DATA.request id: 185 erase from queue
10:58:06:274 ZCL got data for node=0xCD84, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:06:850 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:06:855 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:07:140 APS-DATA.request id: 194, addrmode: 0x03, addr: 0x588e81fffed3a0b8, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
10:58:07:162 APS-DATA.confirm id: 194, status: 0x00 SUCCESS
10:58:07:164 APS-DATA.confirm request id: 194 -> erase from queue
10:58:07:224 aps request id: 194 finished, erase from queue
10:58:07:235 APS-DATA.indication srcAddr: 0xd792, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -76
10:58:07:237 ZCL got data for node=0xD792, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:07:616 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 236, rssi: -76
10:58:07:622 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:08:304 APS-DATA.indication srcAddr: 0xdaf3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0xFCCC, lqi: 255, rssi: -76
10:58:08:309 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01
10:58:08:941 APS-DATA.request id: 205, addrmode: 0x03, addr: 0x0017880104a0c7cd, profile: 0x0104, cluster: 0x0004, ep: 0x01 -> 0x0B queue: 0 len: 4 tx.options 0x00
10:58:08:989 APS-DATA.confirm id: 205, status: 0x00 SUCCESS
10:58:08:991 APS-DATA.confirm request id: 205 -> erase from queue
10:58:09:029 APS-DATA.indication srcAddr: 0xf794, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0004, lqi: 255, rssi: -51
10:58:09:030 APS-DATA.request id: 205 erase from queue
10:58:09:032 0x0017880104a0c7cd found group 0xFFF0
10:58:09:033 0x0017880104a0c7cd found group 0x0026
10:58:10:140 APS-DATA.request id: 212, addrmode: 0x03, addr: 0x588e81fffed4aed0, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x01 queue: 0 len: 5 tx.options 0x00
10:58:10:216 APS-DATA.confirm id: 212, status: 0x00 SUCCESS
10:58:10:217 APS-DATA.confirm request id: 212 -> erase from queue
10:58:10:246 aps request id: 212 finished, erase from queue
10:58:10:258 APS-DATA.indication srcAddr: 0xf801, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -76
10:58:10:260 ZCL got data for node=0xF801, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:11:144 APS-DATA.request id: 218, addrmode: 0x03, addr: 0x0017880104a0c7cd, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
10:58:11:263 APS-DATA.confirm id: 218, status: 0x00 SUCCESS
10:58:11:264 APS-DATA.confirm request id: 218 -> erase from queue
10:58:11:298 APS-DATA.indication srcAddr: 0xf794, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -51
10:58:11:299 APS-DATA.request id: 218 erase from queue
10:58:11:301 ZCL got data for node=0xF794, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:12:641 APS-DATA.request id: 226, addrmode: 0x03, addr: 0x588e81fffed3979d, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:58:12:664 APS-DATA.confirm id: 226, status: 0x00 SUCCESS
10:58:12:666 APS-DATA.confirm request id: 226 -> erase from queue
10:58:12:674 APS-DATA.indication srcAddr: 0xcd84, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -76
10:58:12:675 APS-DATA.request id: 226 erase from queue
10:58:12:677 ZCL got data for node=0xCD84, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:58:12:678 ZCL got data for node=0xCD84, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:58:12:679 ZCL got data for node=0xCD84, cl=0x0B04, at=0x050B, status=0x00, type=0x29
10:58:13:641 APS-DATA.request id: 234, addrmode: 0x03, addr: 0x588e81fffed3a0e5, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:58:13:659 APS-DATA.confirm id: 234, status: 0x00 SUCCESS
10:58:13:661 APS-DATA.confirm request id: 234 -> erase from queue
10:58:13:668 APS-DATA.indication srcAddr: 0xbdec, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -74
10:58:13:670 APS-DATA.request id: 234 erase from queue
10:58:13:672 ZCL got data for node=0xBDEC, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:58:13:673 ZCL got data for node=0xBDEC, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:58:13:674 ZCL got data for node=0xBDEC, cl=0x0B04, at=0x050B, status=0x00, type=0x29
10:58:14:246 Mgmt_Lqi_req zdpSeq: 176 to 0x000B57FFFEB16C20 start index 9
10:58:14:251 APS-DATA.request id: 239, addrmode: 0x03, addr: 0x000b57fffeb16c20, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
10:58:14:283 APS-DATA.confirm id: 239, status: 0x00 SUCCESS
10:58:14:284 APS-DATA.confirm request id: 239 -> confirmed, timeout 161705813
10:58:14:349 APS-DATA.indication srcAddr: 0xf697, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -65
10:58:14:350 APS-DATA.indication request id: 239 -> finished
10:58:14:352 APS-DATA.request id: 239 erase from queue
10:58:14:353 ZDP status = 0x00 -> SUCCESS
10:58:14:354 ZDP Mgmt_Lqi_rsp zdpSeq: 176 from 0x000B57FFFEB16C20 total: 12, startIndex: 9, listCount: 3
10:58:14:357 * neighbor: 0x588E81FFFED3979D (0xCD84), LQI: 63, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:58:14:358 * neighbor: 0x588E81FFFED3A0B8 (0xD792), LQI: 42, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:58:14:359 * neighbor: 0x000B57FFFE9E9305 (0xD93E), LQI: 33, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:58:15:442 APS-DATA.request id: 245, addrmode: 0x03, addr: 0x0017880104d37752, profile: 0x0104, cluster: 0x0006, ep: 0x01 -> 0x0B queue: 0 len: 5 tx.options 0x00
10:58:15:464 APS-DATA.confirm id: 245, status: 0x00 SUCCESS
10:58:15:465 APS-DATA.confirm request id: 245 -> erase from queue
10:58:15:484 APS-DATA.indication srcAddr: 0x1211, srcEp: 0x0B dstAddrMode: 2, profile: 0x0104, cluster: 0x0006, lqi: 255, rssi: -54
10:58:15:485 APS-DATA.request id: 245 erase from queue
10:58:15:486 ZCL got data for node=0x1211, cl=0x0006, at=0x0000, status=0x00, type=0x10
10:58:16:842 APS-DATA.request id: 253, addrmode: 0x03, addr: 0x588e81fffed3a0b8, profile: 0x0104, cluster: 0x0B04, ep: 0x01 -> 0x01 queue: 0 len: 9 tx.options 0x00
10:58:16:872 APS-DATA.confirm id: 253, status: 0x00 SUCCESS
10:58:16:874 APS-DATA.confirm request id: 253 -> erase from queue
10:58:16:886 aps request id: 253 finished, erase from queue
10:58:16:895 APS-DATA.indication srcAddr: 0xd792, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 255, rssi: -76
10:58:16:896 ZCL got data for node=0xD792, cl=0x0B04, at=0x0505, status=0x00, type=0x21
10:58:16:898 ZCL got data for node=0xD792, cl=0x0B04, at=0x0508, status=0x00, type=0x21
10:58:16:898 ZCL got data for node=0xD792, cl=0x0B04, at=0x050B, status=0x00, type=0x29

## Additional context
Different brands: IKEA, Philips, Xiaomi, Blitzwolf, AduroSmart

**Comment by manup** [comment]
>This line must mean something, it appears once every time I press a button
(every button, twice)
>Line 87: 10:58:02:728 No matching sensor found for 0x00158D0001CCB407, endpoint: 0x01

The message comes from this part of the code, I've checked the integration and button_maps.json there the code for integration looks ok on a quick look.

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/mfspecific_cluster_xiaoyan.cpp#L16-L22

Is the switch showing up in the Phoscon App? It looks like the sensor resource isn't created.

**Comment by Mimiix** [comment]
Seems to be a whitelist issue. Hexname

**Comment by manup** [comment]
Yeah thought that too, but from the source code the device is already listed in respective places :thinking:

**Comment by RudolfRendier** [comment]
> Is the switch showing up in the Phoscon App? It looks like the sensor resource isn't created.

No, device cannot be seen in Phoscon App.
I looked into the result of the REST endpoint for sensors, but I couldn't find anything related, i.e. no matches for its 'uniqueid'.

**Comment by mdolnik** [comment]
I know this is an old thread, but I have this remote and I can confirm as of Deconz `2.21.2` (and earlier) that it works for me in deConz, Phoscon, and Home Assistant.

Here's what works for me:

1. In Phoscon Add new switch
2. Choose `Other`
3. Pair the switch:
    - Factory reset Eria switch by holding up + down buttons for 3-5 seconds until light flashes green.
    - Try holding Off button for 3-10 seconds:
        - If it flashes green it's successful.
        - If it flashes red, repeat all the steps again.
        - If repeating steps doesn't work, try hold the remote closer to the gateway
        - If this doesn't work try the next step.
    - Try holding On button for 3-10 seconds:
        - If it flashes green it's successful.
        - If it flashes red, repeat all the steps again.
        - If repeating steps doesn't work, try hold the remote closer to the gateway.
        - If this doesn't work... I'm not sure, try removing/re-inserting battery and trying all steps again?
4. If the light flashes green during pairing, then it is successful:
    - Phoscon will take 5-15 seconds to recognize it:
        - When it first recognizes it, the Back button will disappear.
        - After another 5-10 seconds a success message will appear.
    - The switch will have the Vendor name `Trust` and Product `Dimming switch` in Phoscon.
    - Any button press on the switch should be indicated by the left status circle on the deCONZ node.
5. Identify in Home Assistant:
    1. Go to `Developer Tools` > `Events`
    2. Set `Listen to Events` to `deconz_events`
    3. Click `Start Listening`
    4. Click any button on the remote
    5. An event should appear with the corresponding data / ID
6. Note: This remote appears in Home Assistant as a Device, but not an Entity

![2023-05-03_18h11_58](https://user-images.githubusercontent.com/22206300/236087367-9e214e0a-5c02-4c90-8f78-08156537bb61.png)
![2023-05-03_18h12_06](https://user-images.githubusercontent.com/22206300/236087373-a9ff9ab8-5515-4589-87db-d1b12e79507f.png)
![2023-05-03_18h13_07](https://user-images.githubusercontent.com/22206300/236087377-d14c1b6f-5d44-4189-9378-65b1a93ed7aa.png)
