### ISSUE TITLE
Temperature=0 In Phoscon with 2.15.0

### ISSUE THREAD

**Issue by LeoeLeoeL** [dresden-elektronik/deconz-rest-plugin#5884]
## Describe the bug
Temperature is 0 in Phoscon for Xiaomi Aqara temperature/humidity/pressure sensor

## Steps to reproduce the behavior
Go to Phoscon --> Sensors --> Aqara Sensor
## Expected behavior
 The correct temperature

## Screenshots

![image](https://user-images.githubusercontent.com/65825223/159020839-d6fd9c4f-7b3f-4934-9cfb-9c4edb98d997.png)
![image](https://user-images.githubusercontent.com/65825223/159020957-f5023e33-4469-438a-ac2f-ae3cd744cd62.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 0x26770700
 - deCONZ version: v2.15.0-beta
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? APC UPS

## Additional context
 Temperature was correct with 2.14.x
Temperature is correct in the summary page of sensors.
Other Aqara sensors (contact and motion) are OK.

**Comment by Mimiix** [comment]
What does the RestAPI report?

**Comment by SwoopX** [comment]
In my view, the device stopped reporting temperature values for whatever reason. The one I have in my production environment also defaults to 0 right after upgrade, but then moves on

![grafik](https://user-images.githubusercontent.com/4005212/159039463-6b695042-aceb-420c-8fb2-911ceba5b266.png)

**Comment by canedje** [comment]
I do have the same issue in my sensors used in freezers.
So it is not showing negative values anymore:
![image](https://user-images.githubusercontent.com/23150947/159116010-f5e2aa80-08a3-4730-898c-49e04b4c50ec.png)

**Comment by Erikgj65** [comment]
I have the same problem.
I test my sensor and it  work above 0 and not below 0.

**Comment by ACrazyConcept** [comment]
lol I have like 1/3 of my 16 Xiaomi Aqara sensors show any combination of 0 temp, 0 humidity and 0 pressure.

**Comment by LeoeLeoeL** [comment]
I have this problem in Phoscon only.
Data in Home Assistant are ok.

**Comment by Langelus** [comment]
Can confirm that I have the same problem, both my sensors in the freezer stops reporting at 0 in gui and what's reported to HomeAssistant. Sensordata if I check in Deconz app seems to report correctly at 0402 temperature measurement 0x0000 though

**Comment by Rolf56** [comment]
Had the same problem too in my Windows Environment. After reset and new connecting in Phoscon App everithing works fine again.

**Comment by Langelus** [comment]
Tried resetting one of my sensors, not any difference unfortunately. Still not reporting sub 0 temperatures

**Comment by iisworks** [comment]
Same here on 2 sensors. Both in fridge and reporting around 0 C. Values look fine in deconz on cluster 402, just not in the api.
I just deleted both sensors and paired them again, but the issue persists.
