### ISSUE TITLE
deConz Gui not working after reboot

### ISSUE THREAD

**Issue by tomsteenbakkers** [dresden-elektronik/deconz-rest-plugin#589]
Yesterday I received the Raspbee. Have installed it and installed the software using the instructions at GitHub. After installing the deConz GUI shows the Raspbee. 

After I reboot the PI the deConz GUI is not working. I can start the deConz GUI software and I can not connect to the Raspbee. If I reboot the GUI is showing the raspbee , but when pressing Connect nothing happens. Closing the GUI, I cannot start it, nothing happens when pressing the icon in the menu. 

 I get the following log from deConz.

**Comment by fincha** [comment]
same for me, I am connected via remote desktop

**Comment by tomsteenbakkers** [comment]
I’m using VNC

**Comment by manup** [comment]
You may check if there is already a deCONZ version running.

    $ ps ax | grep deCONZ

**Comment by tomsteenbakkers** [comment]
Check, this was the issue. I will connect a monitor 🤗

**Comment by manup** [comment]
Depending on the VNC server it should also work remotely. The one installed in our sd-card image does always open the current display session so remote logging into it just works fine.

**Comment by ebaauw** [comment]
I'm using the Raspbian built-in VNC server, with authentication set to VNC password, so it works with macOS screen sharing.  Better copy/paste integration than VNC Viewer.  I created a Bonjour announcement on the pi, so the mac shows it in the Finder, see http://4dc5.com/2012/06/12/setting-up-vnc-on-raspberry-pi-for-mac-access/.  Needed Avahi for homebridge anyways.
