### ISSUE TITLE
Legrand Netatmo Remote Switch Wake up / Sleep 064884

### ISSUE THREAD

**Issue by NicoLeOca** [dresden-elektronik/deconz-rest-plugin#5902]
## Device

- Product name: Commande sans fils 2 scénarios Lever/Coucher Céliane with Netatmo 
https://www.legrand.fr/pro/catalogue/42575-version-celiane-with-netatmo/commande-sans-fils-2-scenarios-levercoucher-pour-installation-connectee-celiane-with-netatmo-blanc-sans-plaque
- Manufacturer: Legrand
- Model identifier: Remote Switch Wake up / Sleep
- Device type : Switch

## Screenshots
<img width="724" alt="Capture d’écran 2022-03-24 à 18 13 19" src="https://user-images.githubusercontent.com/9487685/159973977-6f3be799-84e7-4cda-8097-84c145066617.png">
<img width="708" alt="Capture d’écran 2022-03-24 à 18 13 59" src="https://user-images.githubusercontent.com/9487685/159974069-54a7615e-9d22-4428-b829-b996c285eb9d.png">

### Identify
![image](https://user-images.githubusercontent.com/9487685/159992244-c353e388-8d27-473b-a9f8-2b39d8101f9c.png)

### Poll Control
![image](https://user-images.githubusercontent.com/9487685/159992370-32cd9838-d805-48c8-aedc-b4281d0216cd.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/9487685/159992520-27f7cd69-a3d6-48f1-9b06-987e367d3ad7.png)

**Comment by NicoLeOca** [comment]
> Please add all cluster screenshots.

Done
Sorry I did understand what was required and how to get it

**Comment by Smanar** [comment]
Probably the "Binary Input (Basic) cluster.

But something special, the device is partially reconized, because of his name "Remote Switch Wake up / Sleep", the code already have a device called "Remote Switch"

Unfortunately the code make bind using the cluster 0x0006 and 0x0008 for the "Remote Switch" and this device don't have them, so idk what can be the result. From my memory this device use the Scene cluster.

You can see something in logs when using it ? an error message about a button map ? with "info" and "info_l2"

Else we can try to make a DDF for this device, but honnestly I don't havee succed yet with battery switches.

**Comment by Mimiix** [comment]
> 

No worries :)

**Comment by NicoLeOca** [comment]
> 

```
[INFO] - No button map for: Remote switch Wake up / Sleep, broadcast to: 0xFFF4, endpoint: 0x01, cluster: SCENES (0x0005), command: RECALL_SCENE (0x05), payload: F4FF01, zclSeq: 6
```
Does this help?

**Comment by Smanar** [comment]
A lot.
Try the 2 positions, on the code we are checking the 3 th bytes

>payload: F4FF01

So if you have XXXX01 and XXXX02 for exemple we can just edit the json file, but unfortunately from my memory Legrand change the first one.
If not, it's bad luck, not possible to do that without code modification.

**Comment by NicoLeOca** [comment]
@Smanar 
Here is the other log I get when I press the other button
```
[INFO] - No button map for: Remote switch Wake up / Sleep, broadcast to: 0xFFF5, endpoint: 0x01, cluster: SCENES (0x0005), command: RECALL_SCENE (0x05), payload: F5FF01, zclSeq: 3
```
I don't know what you mean by editing the json; my experience with Deconz started yesterday

**Comment by Smanar** [comment]
Ok so bad luck, the easy way is not possible.
I m asking if I can make a change on code, before trying something.

**Comment by Smanar** [comment]
Ok so I have perhaps another way without editing code.
As you device have only 2 events, we can try with a JS script in the DDF.

First we need to check if this device can be used with DDF
Here you can find some explanation and a video https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

So make right clic on the device then edit DDF, if we are lucky you have already a filled DDF, else try to fill at least the "basic cluster identification"
Set the status to "Gold"
Save the file, remember the path on the DDF editor window title (to edit it with text editor, or make a c/c later)
Then if you can make a copy/paste of the DDF (on the last tab)
And show me the result.

**Comment by NicoLeOca** [comment]
Hi @Smanar 
sorry for the late reply I have been away for a while.

I can edit the ddf but there is no way I can have access to it wherever I save it.
I ssh into HA, into the home directory for instance, and it's just empty.
I tried a few different places; no luck.
Where would you save the ddf json and which software would you use to get access to it?

Thanks

**Comment by Smanar** [comment]
You can save the file on defaut path, choose by deconz ?
You have the path on the windows title of the editor.

I don't use docker on my side, too much complicated, but I know some user make a save on a "special folder" not "dockerised".

But was just to test if it can work. If your DDF is fine, the device will be reconised (the name will change from 0xXXXX), and you will have a new ZHASwitch in the API.
If this don't work, you can just make a screen capture of the third tab (with the DDF) to check what is missing.

**Comment by NicoLeOca** [comment]
I still have no event firing in HA.
Is there another way to check if it works?

Here is a screen shot anyway
<img width="432" alt="Capture d’écran 2022-04-08 à 18 55 03" src="https://user-images.githubusercontent.com/9487685/162487578-1ebf93d0-c9cc-4d27-9b3e-c449965cbd45.png">

**Comment by Smanar** [comment]
It don't look so bad.
You can see the sensor in HA ? even not working ?

Check on logs when pressing a button if you don't have log like "with "info" and "info_l2"
>[INFO] - No button map for ...

**Comment by NicoLeOca** [comment]
Something like this?
<img width="673" alt="Capture d’écran 2022-04-08 à 20 01 43" src="https://user-images.githubusercontent.com/9487685/162496828-cb3de626-cfb8-4799-819b-bc890feff81b.png">

**Comment by Smanar** [comment]
Nice so all is still working.
So first, problem,  I haven't find how to set the "cmd" using the DDF editor. So realy need to use a text editor to edit the file.
You need to edit the state/buttonevent part.

```
{
  "name": "state/buttonevent",
  "parse": {
    "cl": "0x0005",
    "cmd": "0x05",
    "eval": "Item.val = ZclFrame.at(0) * 10 + ZclFrame.at(1)"
  },
  "awake": true
}
```

The formula is random, you will have strange number, but if you have them it's a good new.

Now how to edit the file ? Perhaps this link can help you ? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5459#issuecomment-1018984004

**Comment by NicoLeOca** [comment]
Merci encore @Smanar 
I just can't get access to the ddf file.
There is a feature request here:
https://community.home-assistant.io/t/deconz-support-management-of-ddf-files-through-ha-config/370331
but not many votes yet...

**Comment by Smanar** [comment]
I think it s a feature that can be added in phoscon too.
But our problem is to edit this file ...

It don't work using SSH ?

> if you've acces on the core system from SSH in HA, you can search in your files directory here (/mnt/data/supervisor/addons/data/core_deconz/), if you've the deconz addon ;) You can push xml files in this directory

On the HA OS console, type "login" and find:
/mnt/data/supervisor/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices/

There is necessarily a way to edit a simple text file on thoses fu**ing docker ?

**Comment by NicoLeOca** [comment]
I don't see the ddf file
I suppose the folder is not mapped by docker, it is not just a right issue.

**Comment by Smanar** [comment]
Sorry, I m asking is someone know a way to edit a file on docker.
Still no answer.

**Comment by Smanar** [comment]
Oups, sorry totally forgot you
I have perhaps a way to access the DDF https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839/2

**Comment by NicoLeOca** [comment]
@Smanar 
sorry for the lack of news, I have been travelling a lot lately

Thank you for trying to fix my issue
To be honest with you, I moved to Z2M and everything works as expected

**Comment by Mimiix** [comment]
Hi,

Please post in English.

**Comment by Smanar** [comment]
`19:42:08:507 [INFO] - No button map for: Remote switch Wake up / Sleep, broadcast to: 0xFFF5, endpoint: 0x01, cluster: SCENES (0x0005), command: RECALL_SCENE (0x05), payload: F5FF010000`

```
{
  "name": "state/buttonevent",
  "parse": {
    "cl": "0x0005",
    "cmd": "0x05",
    "ep": 1,
    "eval": "Item.val = ZclFrame.at(0) * 10 + ZclFrame.at(1)"
  },
  "awake": true
}
```

Wich one DDF are you using for this device ?

**Comment by Didier3L** [comment]
I created a new DDF file
I modified config/battery and state/buttonevent
I have a status return with -111 or -121

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/23530136/90f7606f-605d-4a51-b785-d2da4767d883)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/23530136/4d0a2364-2bf2-44ea-9fc0-89ca2139efac)

``` 
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Legrand",
  "modelid": "Remote switch Wake up / Sleep",
  "product": "Remote switch Wake up / Sleep",
  "sleeper": true,
  "status": "Gold",
  "path": "/devices/Legrand_064884.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0005"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0006",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001"
        ],
        "out": [
          "0x0005"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0020",
            "cl": "0x0001",
            "eval": "const vmin = 20; const vmax = 30; var bat = Attr.val; if (bat > vmax) { bat = vmax; } else if (bat < vmin) { bat = vmin; } bat = ((bat - vmin) / (vmax - vmin)) * 100; if (bat > 100) { bat = 100; } else if (bat <= 0)  { bat = 1; } Item.val = bat;"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0x0005",
            "cmd": "0x05",
            "ep": 1,
            "eval": "Item.val = ZclFrame.at(0) * 10 + ZclFrame.at(1)"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

**Comment by Didier3L** [comment]
For "eval": "Item.val = ZclFrame.at(0)" = -11/-12

I make the direction changes in Deconz
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/23530136/819b3003-cbf7-4fc5-8879-38ba90ac5f7b)

When I modify the json file, save the file and Hot reload, my modifications are not taken into account!

**Comment by Didier3L** [comment]
``` 
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0x0005",
            "cmd": "0x05",
            "ep": 1,
            "eval": "const t={'245':1002,'246':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"
``` 
**it returns nothing**

**Comment by Smanar** [comment]
>edit; when you modify the json file you have to restart the DeConz server

Yes, or if you have the GUI, can use the "hot reload" feature on the DDF editor.

>it returns nothing

Yes, was just a sample, I need the 2 values to use.
So -11 and - 12 (0xF5 and 0xF4)

If the code don't make hexa convertion, I think the working code is

`"eval": "const t={'-11':1002,'-12':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"`

Just to be sure can use too 

`"eval": "const t={'-11':1002,'-12':2002,'244':1002,'245':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"`

**Comment by Didier3L** [comment]
Bonjour @Smanar 

`"eval": "const t={'-11':1002,'-12':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"`
ou
`"const t={'-11':1002,'-12':2002,'244':1002,'245':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"`

Works correctly **1002/2002** 😉

Here is the complete code
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Legrand",
  "modelid": "Remote switch Wake up / Sleep",
  "product": "Remote switch Wake up / Sleep",
  "sleeper": true,
  "status": "Gold",
  "path": "/devices/Legrand_064884.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0005"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0006",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001"
        ],
        "out": [
          "0x0005"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0020",
            "cl": "0x0001",
            "eval": "const vmin = 20; const vmax = 30; var bat = Attr.val; if (bat > vmax) { bat = vmax; } else if (bat < vmin) { bat = vmin; } bat = ((bat - vmin) / (vmax - vmin)) * 100; if (bat > 100) { bat = 100; } else if (bat <= 0)  { bat = 1; } Item.val = bat;"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0x0005",
            "cmd": "0x05",
            "ep": 1,
            "eval": "const t={'-11':1002,'-12':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
``` 

What's its use `sleeper` ?

**Comment by Smanar** [comment]
>What's its use sleeper ?

Some device are slepper, like sensor (generaly battery device to save battery life), if you send them request, most of them are ignored because the device is sleeping.
Other make maximum 6/7s to answer.

There is no DDF for this device, do you want to make or do you you want I make it ?

**Comment by Didier3L** [comment]
Yes I want you to do the PR because I don't know how to do that 😉

Here is the modified code
I also modified `"product": "Remote switch Sleep / Wake - 064884",`
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Legrand",
  "modelid": "Remote switch Wake up / Sleep",
  "product": "Remote switch Sleep / Wake - 064884",
  "sleeper": true,
  "status": "Gold",
  "path": "/devices/Legrand_064884.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0005"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0006",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001"
        ],
        "out": [
          "0x0005"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0020",
            "cl": "0x0001",
            "eval": "const vmin = 20; const vmax = 30; var bat = Attr.val; if (bat > vmax) { bat = vmax; } else if (bat < vmin) { bat = vmin; } bat = ((bat - vmin) / (vmax - vmin)) * 100; if (bat > 100) { bat = 100; } else if (bat <= 0)  { bat = 1; } Item.val = bat;"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0x0005",
            "cmd": "0x05",
            "ep": 1,
            "eval": "const t={'-11':1002,'-12':2002,'244':1002,'245':2002};if(ZclFrame.at(0) in t){Item.val=t[ZclFrame.at(0)]}"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

**Comment by Smanar** [comment]
PR done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6970
