### ISSUE TITLE
Namron termostat touch ZigBee 16A - Get power consumption?

### ISSUE THREAD

**Issue by jarlesb** [dresden-elektronik/deconz-rest-plugin#5905]
![image](https://user-images.githubusercontent.com/34880506/160212000-791ffef6-5e98-4061-bd68-44cb240b39a6.png)

## Device

- Product name: Namron termostat touch ZigBee 16A
- Manufacturer: Namron AS
- Model identifier: 4512737
- Device type : 
  - Thermostat

### Basic
![image](https://user-images.githubusercontent.com/34880506/160212158-7f8642c4-fb5f-4843-9dd6-eb923e82deaf.png)

### Identify
![image](https://user-images.githubusercontent.com/34880506/160212191-04970e65-9093-4ea1-ab16-41b02d32389a.png)

### Groups
![image](https://user-images.githubusercontent.com/34880506/160212245-fd393e82-fe6d-4fbe-ad6b-fda797de1da3.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/34880506/160212453-f94fd1a5-25fb-4143-b28f-d462ba2d8f60.png)

### Electrical measurements
![image](https://user-images.githubusercontent.com/34880506/160212514-91ec4a28-187e-404b-ba86-c25aada50187.png)

Is it possible to get kWh consumption on this devices? Is identified in Home Assistant as Thermostat with Climate entity. I am running Home assistant 2022.3.7 with Conbee 2 on Odroid N2+/Home Assistant Blue

**Comment by jreidel** [comment]
@jarlesb did you solve the power consumption issue?

**Comment by Smanar** [comment]
It's a thermostat ? with power comsumption ?

Can take this one as sample to make a DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/sinope/th1124zb.json

**Comment by jarlesb** [comment]
I do not get any power or consumption readings...

![image](https://user-images.githubusercontent.com/34880506/166688883-a13a87c3-ab6c-4ba7-9a9f-55a86bd09f03.png)

Just says unavailable...

**Comment by Smanar** [comment]
But you are using a DDF ?
The device don't seem tobe n whitelist, so not logic you already have thoses sensor by defaut.
Can you show the sensors json ? visible in phoscon / help / API Information / sensors

Do you have access to the GUI ? If you read the value in deconz, it update the value in HA ?

**Comment by jarlesb** [comment]
I have not worked with DDF... I am using Home Assistant with Conbee2. and just added via Phoscon.

I phoscon I see the Thermostat as a sensor
![image](https://user-images.githubusercontent.com/34880506/166701685-79ba34cf-e910-45c4-a98c-cc54ca1d63ce.png)

    "113": {
        "config": {
            "heatsetpoint": 1950,
            "offset": 0,
            "on": true,
            "reachable": true,
            "schedule": {},
            "schedule_on": false
        },
        "ep": 1,
        "etag": "xxx",
        "lastannounced": null,
        "lastseen": "2022-05-04T14:21Z",
        "manufacturername": "NAMRON AS",
        "modelid": "4512737",
        "name": "Outlet",
        "state": {
            "lastupdated": "2022-05-04T14:17:34.724",
            "on": false,
            "temperature": 2073
        },
        "swversion": "6.9.1.0_r4",
        "type": "ZHAThermostat",
        "uniqueid": "xxx"
    }
}

**Comment by Smanar** [comment]
This one is a ZHAThermostat, you haven't a ZHAConsumption or ZHAPower ?

**Comment by jarlesb** [comment]
Sorry, I missed those elements. Here they are:

    "111": {
        "config": {
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "xxx",
        "lastannounced": null,
        "lastseen": "2022-05-04T13:22Z",
        "manufacturername": "NAMRON AS",
        "modelid": "4512737",
        "name": "Consumption 111",
        "state": {
            "consumption": 1189,
            "lastupdated": "2022-05-04T19:25:55.884",
            "power": 0
        },
        "swversion": "6.9.1.0_r4",
        "type": "ZHAConsumption",
        "uniqueid": "xxx"
    },
    "112": {
        "config": {
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "xxx",
        "lastannounced": null,
        "lastseen": "2022-05-04T13:22Z",
        "manufacturername": "NAMRON AS",
        "modelid": "4512737",
        "name": "Power 112",
        "state": {
            "current": 0,
            "lastupdated": "2022-05-04T19:28:55.355",
            "power": 0,
            "voltage": 0
        },
        "swversion": "6.9.1.0_r4",
        "type": "ZHAPower",
        "uniqueid": "xxx"
    },
    "113": {
        "config": {
            "heatsetpoint": 2150,
            "offset": 0,
            "on": true,
            "reachable": true,
            "schedule": {},
            "schedule_on": false
        },
        "ep": 1,
        "etag": "xxx",
        "lastannounced": null,
        "lastseen": "2022-05-04T19:29Z",
        "manufacturername": "NAMRON AS",
        "modelid": "4512737",
        "name": "Outlet",
        "state": {
            "lastupdated": "2022-05-04T19:29:18.956",
            "on": false,
            "temperature": 2134
        },
        "swversion": "6.9.1.0_r4",
        "type": "ZHAThermostat",
        "uniqueid": "xxx"
    }

**Comment by Smanar** [comment]
It seem the ZHAConsumption is woking.
The ZHAPower have 0 values, you have consumption at this moment ? You haven't the GUI to compare ?

**Comment by aspic** [comment]
I have very similar setup (Namron 4512737, RaspBee 2 and Home Assistant) and do get power consumption:
![Screenshot from 2022-05-05 09-43-50](https://user-images.githubusercontent.com/788059/166881471-a409b153-dc92-42ed-9565-dc92c7704f5b.png)

**Comment by Smanar** [comment]
And only consumption is working ? You have 0 value like him.

**Comment by sliann** [comment]
I'm using this DDF with a Conbee II, Deconz and Home Assistant.

```
,
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0400",
          "dt": "0x2A",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
```

**Comment by sliann** [comment]
I have a DDF for this. Tried to post it but the clip board on my phone cut some of the text. Will try again later tonight.

**Comment by sliann** [comment]
> I have very similar setup (Namron 4512737, RaspBee 2 and Home Assistant) and do get power consumption:
> 
> ![Screenshot from 2022-05-05 09-43-50](https://user-images.githubusercontent.com/788059/166881471-a409b153-dc92-42ed-9565-dc92c7704f5b.png)

Do you get temperature readings from the floor sensor? I get it myself, but it's reporting the air sensor at varying points so the graph is very confusing..
![image](https://user-images.githubusercontent.com/79062704/166968358-2ecd4c18-69ef-4058-8cc2-6bfc6896b87c.jpeg)

**Comment by aspic** [comment]
> And only consumption is working ? You have 0 value like him for others

This was a bad snapshot, it was idling at the time. Yeah, consumption working :-)

@sliann: No, I only get temperature from the room sensor (at least that's what I thought). Would defenitely love floor sensor as well. Here's a more historic graph:

![Screenshot from 2022-05-05 19-07-01](https://user-images.githubusercontent.com/788059/166976444-d5640ed7-d03d-4feb-9ca0-b41104b8c27b.png)

**Comment by jreidel** [comment]
> I have very similar setup (Namron 4512737, RaspBee 2 and Home Assistant) and do get power consumption: 

How did you add it to Deconz? Via Phoscon (sensor)? I just got one Namron unit installed, but I'm not able to pair (RPi, Conbee2, Home Assistant). @aspic

**Comment by aspic** [comment]
@jreidel On the namron device → go into menu → network → reset
Afterwards in Home Assistant → Add integration → Add zigbee device (with ZHA) → it should turn up in search

**Comment by jreidel** [comment]
Ah, thanks. I'm currently not using ZHA, just Deconz. Will try some more with deconz, might have to create a DDF.

**Comment by Smanar** [comment]
You can't include it at all ?
It need to work natively, without DDF you miss only the measurement.

Select "Add new light"on phoscon and make the reset procedure on the device.

**Comment by jarlesb** [comment]
I just removed it and added again via Phoscon and now works with power and
consumption 👍



fre. 6. mai 2022, 18:40 skrev Smanar ***@***.***>:

**Comment by aspic** [comment]
Nice! Did you get floor temperatur working as well?

**Comment by marhoy** [comment]
I'm also interested in learning how to change the temperature reading from the wall sensor to the floor sensor. I've just added it as a sensor in Phoscon, and I'm able to control it from HomeAssistant. But the reported temperature is the wall sensor.

**Comment by Smanar** [comment]
This device have 2 temperatures ? can you give more information where to read them on deconz ?
Need the cluster / attribute.

The actual value is
```

          "description": "The current floor temperature",
          "read": {
            "at": "0x0001",
            "cl": "0x0201",
```

**Comment by marhoy** [comment]
Not sure what you need, but there's quite a lot on Zigbee in the manual:

https://www.elektroimportoren.no/docs/lib/4512737-Brukerveiledning-5.pdf

**Comment by sliann** [comment]
I have the same device. Please see attached screen shots.
Local temperature is the room temperature and outdoor is the floor temperature.

![image](https://user-images.githubusercontent.com/79062704/189981453-5d77fc67-f993-45cb-be4c-dde1c862c519.jpeg)

![image](https://user-images.githubusercontent.com/79062704/189981482-01171669-9587-4734-9406-1012f1ad5b10.jpeg)

**Comment by Smanar** [comment]
Ok so it s easy to add it, but there is a problem ^^
On the field list I have only state/floortemperature available. We are making new one https://github.com/dresden-elektronik/deconz-rest-plugin-v2/issues/13 but they are not available yet.

What is your third app ? If you are using nodered, I can use this one as workaround, else better to wait for new fields.

**Comment by sliann** [comment]
From what I can see a lot of things with this thermostat will be fix with the new fields 😊

It will probably fix the state/on problem as well. This is not available from the device, just a list of different states:
![image](https://user-images.githubusercontent.com/79062704/190205146-162b9b53-0f9e-4e70-a541-f1d9908d0de5.png)

Not sure what you mean by third app?
I have fixed the sensor issue by changing my DDF file.

**Comment by Smanar** [comment]
>Not sure what you mean by third app?

Phoscon/ OpenHab/ NodeRed, ect ...

>I have fixed the sensor issue by changing my DDF file.

So you have now the value in 0x0001 but not the one in 0x0000 ?

State/on is not by defaut on this device ? You have it in the DDF
```
        {
          "name": "state/on",
          "refresh.interval": 5
        },
```

The legacy code is able to handle it, perhaps you just miss the binding ?

**Comment by jarlesb** [comment]
That is strange. I can try to remove and add the thermostat again and see
if it fixes the issue.

Which FW do you have?

tor. 5. mai 2022, 09:50 skrev Kjetil Mehl ***@***.***>:

**Comment by jreidel** [comment]
I'm not sure deConz DDF settings for this termostat is correct out of the box - or mayby I just don't know how this thing is working. I have notised that voltage and power consumption seems to be wrong by default, and I have adjustet how i _think_ it should be.

Voltage - had to devide by 10:
![image](https://user-images.githubusercontent.com/15332387/196270210-3e54f287-1475-4b02-9119-99a44bb68e03.png)

Power consumption - had to multiply by 100:
![image](https://user-images.githubusercontent.com/15332387/196270345-16dcdca4-f7db-4b4e-b927-026661635399.png)

It seems to be correct now, whey I inspect the data. Can anyone confirm their own settings?
