### ISSUE TITLE
Blitzwolf SHP-15 Power and Consumption not updated in REST API after update to 2.15

### ISSUE THREAD

**Issue by LukasA83** [dresden-elektronik/deconz-rest-plugin#5909]
## Describe the bug
After upgrading to 2.15 my Blitzwolf SHP-15 are not reporting updates to the REST API. While, via VNC, I can retrieve the latest values, in REST API calls the sensor indicate lastupdate before upgrading to 2.15, around 10 days ago, see screenshots.

## Steps to reproduce the behavior
1. Call REST API to sensor, e.g. 92
2. Check last update
3. Open VNC
4. Navigate to corresponding cluster 
5. Click "Read" and see updated values
6. Re-run 1. & 2. and see no updates in REST API

## Expected behavior
Devices is reporting updates and manual update should be visible in REST API calls

## Screenshots
![grafik](https://user-images.githubusercontent.com/58861945/160281112-f40aae28-15e3-403e-ab66-f87305d8f829.png)
![grafik](https://user-images.githubusercontent.com/58861945/160281122-07a8ea65-3ea8-4319-868e-c7efdd22e2d2.png)
![grafik](https://user-images.githubusercontent.com/58861945/160281129-f44dc0cb-79cf-4a47-b00f-8a7a089900fa.png)

## Environment
 - Host system: Raspi 4b - Docker setup
 - Running method: Docker community deconz
 - Firmware version: 26720700
 - deCONZ version: 2.15.00
 - Device: RaspBee II

## Other Info
Resetting the device does not solve the issue. But, after deletion of node in deconz via VNC - delete node and re-pairing of the device it starts to work again.

**Comment by iisworks** [comment]
@Smanar I see these new Blitzwolf DDF files reference a Tuya file:
"script": "../tuya/tuya_swversion.js"

What happens if we create a custom DDF from a copy of this json in the Docker Mount (/docker/deconz/data/devices? This folder does not contain that file in the relative patch ? Will it automatically try to find the file in the installed deconz instance as well?

**Comment by manup** [comment]
Hi note that the Blitzwolf SHP-15 has now a DDF in v2.15.1-beta https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5945

**Comment by manup** [comment]
Closing for now, should be fixed with v2.15.1-beta.
