### ISSUE TITLE
Water Leak Detecor

### ISSUE THREAD

**Issue by stappel** [dresden-elektronik/deconz-rest-plugin#5911]
## Device

- Product name: "ZigBee" Water Leak/Food Detector
- Manufacturer: _TZ3000_d16y6col
- Model identifier: TS0207
- Device type : 
  - Sensor
  - Other: Leak Detector

Item: https://www.aliexpress.com/item/4000785145353.html?gatewayAdapt=glo2nld&gatewayAdapt=glo2nld&spm=a2g0o.order_list.0.0.21ef79d2KEv077 

### Basic
![2022-03-27_164006](https://user-images.githubusercontent.com/13430384/160287081-c4899b29-054a-48e4-bba1-3fef205135bc.png)

### Identify

![2022-03-27_164023](https://user-images.githubusercontent.com/13430384/160287090-7f6aa446-1ded-43b9-bb3d-50c1688a926a.png)

### Other clusters that are not mentioned above
![2022-03-27_164053](https://user-images.githubusercontent.com/13430384/160287101-f5b2bec8-9515-4a88-a6b2-faa15c6b7617.png)
![2022-03-27_164127](https://user-images.githubusercontent.com/13430384/160287107-c279fe05-1fcb-4145-a9e3-4409cdc9d9d3.png)

![2022-03-27_164208](https://user-images.githubusercontent.com/13430384/160287122-9463e7a2-ee1b-4630-8c47-fa9c6015d952.png)

**Comment by Smanar** [comment]
Hello, this device realy look standards.
Can try with DDF editor, or just with editing this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/bosch/bwa-1_water_sensor.json

It's almost the same, just need to edit 

```
  "manufacturername": "_TZ3000_d16y6col",
  "modelid": "TS0207",
  "vendor": "Tuya",
  "product": "Tuya water sensor",
```

**Comment by stappel** [comment]
Confirmed. Added json file and It shows a water sensor.
![Screenshot 2022-03-29 121853](https://user-images.githubusercontent.com/13430384/160590460-980877d6-387a-49a2-b938-8435ce079d8d.png)

**Comment by Smanar** [comment]
If it work, can you make a PR to submit it ?
Or I can add it myself if needed.

**Comment by Smanar** [comment]
np, just if you can confirm the DDF ?

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_d16y6col",
  "modelid": "TS0207",
  "vendor": "Tuya",
  "product": "Tuya water sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "ZHAWater",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "config/enrolled"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery",
          "awake": true
        },
        {
          "name": "state/tampered",
          "awake": true
        },
        {
          "name": "state/water",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```
