### ISSUE TITLE
Missing temperature and pressure from Keen Smart vents with ID of SV01-612-MP-1.0

### ISSUE THREAD

**Issue by notoriousbdg** [dresden-elektronik/deconz-rest-plugin#592]
I just added several Keen smart vents.  I noticed that most of them have temperature and pressure, but there are 2 that don't.  The ones that are working have show product ID of `SV01-610-MP-1.0` and the ones that aren't working show product ID of `SV01-612-MP-1.0`.  Is the fix as simple as adding `SV01-612-MP-1.0` like was done in #504?

**Comment by ebaauw** [comment]
Probably.  Or just check for prefix “SV01-61”.

**Comment by notoriousbdg** [comment]
Good point.  Submitted PR #595 to implement that change.
