### ISSUE TITLE
Color change not working

### ISSUE THREAD

**Issue by OUARZA** [dresden-elektronik/deconz-rest-plugin#5922]
## Describe the bug
Hello,
I have a problem with my LEDVANCE - Gardenpole RGBW Z3 lamps. Since Phoscon, Hue Essential, Jeedom, when I put the color red, the lamp displays blue, when I put blue, it displays white...
I tested from Deconz app, it doesn't work if I put values ​​in "X" and "Y". It only works if I put a value in "Hue"

## Steps to reproduce the behavior
I go to my light and change the color with the slider.

## Expected behavior
The color must match the one chosen.

## Screenshots
![image](https://user-images.githubusercontent.com/34892335/160905466-6f6c2578-297d-447e-8a2f-39cbbec6ac7e.png)

![image](https://user-images.githubusercontent.com/34892335/160905682-196fbbde-6574-42f7-8917-3167f5c40b71.png)

## Environment
 - Host system: Raspberry Pi & PC
 - Running method: Raspbian & Jeedom & Deconz & Phoscon
 - Firmware version: (26720700)
 - deCONZ version: (2.14.1)
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? yes, zwave

## deCONZ Logs
No

## Additional context
{
    "9": {
        "colorcapabilities": 31,
        "ctmax": 526,
        "ctmin": 153,
        "etag": "af27318b1787094ed8dddf1443cd72ad",
        "hascolor": true,
        "lastannounced": "2022-03-30T16:43:15Z",
        "lastseen": "2022-03-30T16:45Z",
        "manufacturername": "LEDVANCE",
        "modelid": "Gardenpole RGBW Z3",
        "name": "Extended color light 9",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "ct",
            "ct": 489,
            "effect": "none",
            "hue": 8448,
            "on": true,
            "reachable": true,
            "sat": 208,
            "xy": [
                0.437,
                0.5226
            ]
        },
        "swversion": "00103103",
        "type": "Extended color light",
        "uniqueid": "f0:d1:b8:00:00:1a:1e:26-01"
    }
}

**Comment by Mimiix** [comment]
What happens if you use the rest api to set the color?

**Comment by OUARZA** [comment]
![image](https://user-images.githubusercontent.com/34892335/160913427-87c6736d-820a-4561-9f15-2bab95bbe6eb.png)

It gives red

**Comment by Mimiix** [comment]
@manup can you check!

**Comment by OUARZA** [comment]
Here are 2 sets of identical lamps, but one recognized as LEDVANCE and the other as OSRAM.
Here is the result when I ask for color #0000FF.
The problematic one is LEDVANCE.

![image](https://user-images.githubusercontent.com/34892335/160915911-58eb67b5-51d3-4f15-8a00-505462802069.png)

```
{
    "colorcapabilities": 31,
    "ctmax": 526,
    "ctmin": 153,
    "etag": "8e845296eb46d06b17e9a3ec65ea871f",
    "hascolor": true,
    "lastannounced": "2022-03-30T19:11:15Z",
    "lastseen": "2022-03-30T19:33Z",
    "manufacturername": "LEDVANCE",
    "modelid": "Gardenpole RGBW Z3",
    "name": "Extended color light 9",
    "state": {
        "alert": "none",
        "bri": 254,
        "colormode": "xy",
        "ct": 153,
        "effect": "none",
        "hue": 0,
        "on": true,
        "reachable": true,
        "sat": 0,
        "xy": [
            0.14,
            0.4
        ]
    },
    "swversion": "00103103",
    "type": "Extended color light",
    "uniqueid": "f0:d1:b8:00:00:1a:1e:26-01"
}


{
    "colorcapabilities": 31,
    "ctmax": 666,
    "ctmin": 125,
    "etag": "3395c9535983de92fa2011573d0998e5",
    "hascolor": true,
    "lastannounced": null,
    "lastseen": "2022-03-30T19:22Z",
    "manufacturername": "OSRAM",
    "modelid": "Gardenpole RGBW-Lightify",
    "name": "Extended color light 10",
    "state": {
        "alert": "none",
        "bri": 254,
        "colormode": "xy",
        "ct": 526,
        "effect": "none",
        "hue": 21504,
        "on": true,
        "reachable": true,
        "sat": 254,
        "xy": [
            0.1672,
            0.6476
        ]
    },
    "swversion": "V1.04.93",
    "type": "Extended color light",
    "uniqueid": "7c:b0:3e:aa:0a:07:81:ee-03"
}
```

**Comment by manup** [comment]
There are several Ledvance lights where we manually had to remove the xy values, but these appear to be tunable white lights. The code for this light should be the generic one assuming the firmware correctly interprets the color mode commands.

Can you try in the Cluster Info Panel for the *Color Control Cluster* &rarr; **Enhanced  move to hue and saturation** command with following values if they set the appropriate colors:

Saturation: 254
Enhanced hue:

  3000 &rarr; red
  14000 &rarr; green
  42500 &rarr; blue

If this works we can make a DDF and strip out xy color mode, so API clients only use hue and saturation.

**Comment by OUARZA** [comment]
Hello,
I just did the test on the 2 sets. The colors are identical for the 3 tests.
The red is a little orange (see photo).
The green is a pale green.
Blue is blue.

Mathieu

![image](https://user-images.githubusercontent.com/34892335/161136954-66faafbf-b589-4aac-a733-e6eb976cde2a.png)

**Comment by OUARZA** [comment]
Hello @manup ,
I don't understand why when I run the command below
![image](https://user-images.githubusercontent.com/34892335/161297830-93ab3db2-7b71-4643-966c-0664ad76ec78.png)

 I have the following result?
![image](https://user-images.githubusercontent.com/34892335/161297941-1298341a-242f-4400-8d95-4f149a0eca84.png)

Mathieu

**Comment by manup** [comment]
After commands are send to a device, values are queried again. Here I'd assume that the light converted to a actual used value. The extended hue is a bit complex, it's not a continuous range but has steps which may not be evenly distributed.
