### ISSUE TITLE
Philips Hue Enrave (small)

### ISSUE THREAD

**Issue by Je-sse** [dresden-elektronik/deconz-rest-plugin#5923]
## Device

- Product name: Philips Hue Enrave (small)
- Manufacturer: Philips
- Model identifier: 915005996501
- Device type : 
  - Light

### Basic
![Cluster info](https://user-images.githubusercontent.com/61166497/160921334-b28e10e6-9f17-4273-877c-8083647b9b85.PNG)

### Identify
![image](https://user-images.githubusercontent.com/61166497/160921430-63bde537-8715-46aa-bd6c-17badfe5efa3.png)

### Groups
![image](https://user-images.githubusercontent.com/61166497/160921772-b7f1f3e8-360a-4ba7-9e94-62bdf3c0b75b.png)

### Scenes
![image](https://user-images.githubusercontent.com/61166497/160922418-f679ceba-a8a6-4ec6-b70b-3b2873018d29.png)

### On/Off
![image](https://user-images.githubusercontent.com/61166497/160922765-817dbfa5-6eee-4f7e-8060-926928c35c76.png)

### Level Control
![image](https://user-images.githubusercontent.com/61166497/160923078-476ad514-3ade-401a-8b14-7e28d314e824.png)

### Color Control
![image](https://user-images.githubusercontent.com/61166497/160923832-39d151f0-f401-421a-b24c-404df576c62f.png)

### Other clusters that are not mentioned above
ZLL commissioning
![image](https://user-images.githubusercontent.com/61166497/160924260-e6e4641f-3afd-4a23-9911-15ffca0fbdf6.png)

**Comment by Mimiix** [comment]
Can you also provide the cluster list?

**Comment by Je-sse** [comment]
Something went wrong, here it is:
![image](https://user-images.githubusercontent.com/61166497/161148969-ba8d8e67-8b53-4eff-8068-ae3100178f8a.png)

**Comment by Smanar** [comment]
Hello, this device don't work natively ?

**Comment by Je-sse** [comment]
Hi, I was not able to connect the device via the search light functionality of Phoscon, I had to use deCONZ and enable the Hybrid option in de DDF tab. I have a second light that I didn't connect yet. I will change the setting back to Basic - Gold and I will test it again with the second light (after a reset) tonight or tomorrow to be sure..

**Comment by Smanar** [comment]
But there is no DDF for this device, so I don't think changing something in DDF can do something.

This device can have issue because the missing manufacture name.

**Comment by Je-sse** [comment]
I wasn't able to connect the new light out of the box also. I did the same with the first one; connect it with the Hue app on my mobile phone via bluetooth, updated the firmware and did a reset. After that I was able to connect to deCONZ with de default DDF mode (basic - gold only).
So of the firmware update or the reset did the trick

My bad! I will close this request.

**Comment by bilak** [comment]
Sorry to hijack this issue, but is it possible to include any of Hue Enrave through Phoscon?
