### ISSUE TITLE
Tuya Humidity Sensor can't be added and is recognized as smart plug

### ISSUE THREAD

**Issue by Piccar** [dresden-elektronik/deconz-rest-plugin#5925]
## Describe the bug

I added the the Humidity Sensor via Phoscon but the device won't show up. In deconz the Device is recognized as a Smart Plug.

## Expected behavior
Show up as Sensor and tell Temperature Humidity and Batterylevel.

## Screenshots
![2022-04-01-202920_1920x1080_scrot](https://user-images.githubusercontent.com/39131992/161322315-e9ae8639-55b5-4bd9-908d-d12383458831.png)

## Environment
Phoscon: 2.14.01 / 6.2.2022
Conbee2: 26720700
deconz: 2.14.1
Raspberry 2B running Raspian
Extension cabel: YES
No other devices connected

**Comment by Mimiix** [comment]
Hi, the device isn't supported yet. Please check if there's already an issue on it ( read the basic cluster and check the github for the model identifier / manufacturer name).

As this isn't a bug, I am closing this issue.
