### ISSUE TITLE
Firmware flashed successfully but reports failure

### ISSUE THREAD

**Issue by Redsandro** [dresden-elektronik/deconz-rest-plugin#5930]
## Describe the bug

Flash ended with the word _'failed'_ but to my surprise the flash went successfully, as seen on the Phoscon-GW Gateway page:

![image](https://user-images.githubusercontent.com/1702193/161394595-c9291bc8-4a8a-4fcd-91b8-756be64d4683.png)

I wonder if the flash went fine, or if there is some corruption that warranted the failure message.

## Steps to reproduce the behavior

```bash
$ wget https://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_RaspBeeII_0x26720700.bin.GCF
$ wget https://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_RaspBeeII_0x26720700.bin.GCF.md5
$ md5sum -c deCONZ_RaspBeeII_0x26720700.bin.GCF.md5 
deCONZ_RaspBeeII_0x26720700.bin.GCF: OK
$ sudo systemctl stop deconz-gui
$ sudo systemctl stop deconz
$ sudo GCFFlasher_internal -t 60 -f deCONZ_RaspBeeII_0x26720700.bin.GCF
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26610700
Bootloader version 0x00030003, app crc: 0x769F0F78
Reboot device RaspBee (RaspBee)
action: reset device RaspBee
wiringPi 2.52 initialized
Bootloader version 0x00030003, app crc: 0x769F0F78
flashing 164227 bytes: |================|retry, failed
```

## Expected behavior

A _'SUCCESS'_ message as described in the [manual update guide](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually).

## Environment

 - Host system: Pi 3
 - Raspbian dedicated image
 - Firmware version: 26720700
 - deCONZ version: (2.15.00)
 - Device: RaspBee II
 - No other USB or serial devices

## Additional context

This is not a big problem because so far everything seems to work, but I thought I'd report it anyway. Perhaps there's a failure testing mechanism handing out false positives, giving people a good scare. I don't feel 100% confident there is no flipped bits waiting to be executed, and I'll probably postpone another firmware update as long as possible.

**Comment by Mimiix** [comment]
Hi,

Thanks for the report!

Can you please post the report here? https://github.com/dresden-elektronik/gcfflasher. As that is the repository for the flashing tool. 


Thanks!

Kind regards, 
Dennis
