### ISSUE TITLE
Namron 4 in 1 dimmer

### ISSUE THREAD

**Issue by jarlesb** [dresden-elektronik/deconz-rest-plugin#5955]
Can you please add the battery wireless Namron 4 in 1 Dimmer? In the manual name is given as:
"RGB+CCT RGB CCT Mono 4 in 1 Zigbee Rotary Switch". I guess it is a rebranded product.

I would like to be able to turn it on/off and dim it.

Thanks & best regars,
Jarle

Product page: https://www.namron.com/products/namron-zigbee-4-i-1-vridimmer/
User manual: https://www.elektroimportoren.no/docs/lib/4512726-Brukerveiledning-5.pdf

## Device

- Product name: Namron 4 in 1 Dimmer
- Manufacturer: Namron AS
- Model identifier: 4512726
- Device type : 
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/34880506/163055837-ba4cc701-816d-41e4-9561-79160fba1a3e.png)
![image](https://user-images.githubusercontent.com/34880506/163055474-c8894a62-479a-472c-b24b-12bb19cefc52.png)

### Basic
![image](https://user-images.githubusercontent.com/34880506/163055290-b8e5a4fe-0800-4064-b5e0-a3abe9605f2e.png)

### Identify
![image](https://user-images.githubusercontent.com/34880506/163055366-20e065ba-24c6-43a2-9494-59497983d982.png)

### Groups
![image](https://user-images.githubusercontent.com/34880506/163055651-c1c7a1d7-1db2-405b-89e1-2aee17465274.png)

### Scenes
![image](https://user-images.githubusercontent.com/34880506/163055628-237b7ae3-9cbb-445d-b933-439f66b11b4d.png)

### On/Off
![image](https://user-images.githubusercontent.com/34880506/163055581-76c2c1b0-e091-45a2-99ae-2dd35b669bd4.png)

### Level Control
![image](https://user-images.githubusercontent.com/34880506/163055528-d0617a50-93d2-4616-a355-0a06339e3f82.png)

### Color Control
![image](https://user-images.githubusercontent.com/34880506/163055550-89c24343-4da5-450f-ae19-296594bbf998.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/34880506/163055735-e2240d6f-10b5-4810-948c-f388653d38c0.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/34880506/163055418-22f2aaa1-eb78-4e68-8009-c188b9664ccf.png)

**Comment by joggs** [comment]
@jarlesb , has this device been added or are these kinds of requests sometimes missed even if they are open for a whole month?
