### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by JayJay68** [dresden-elektronik/deconz-rest-plugin#5956]
## Device
- Product name: 511.544 Zigbee 3.0 Wand-Dimmer für RGB / RGB+W / RGBW / RGB+Duo LEDs, Touch R, 4 Lichtzonen | weißes Glas
- Manufacturer: iluminize
- Model identifier: ZGRC-TEUR-001
- Device type : Please remove all unrelated device types. 
    - Switch
 - Remote
 - Iluminize has branded this device. About 15 month ago I bought the same one (511.544) from the iluminize-shop. The manufacturer (Basic Cluster) is not iluminize but sunricher.
- not battery powered
- product page: https://www.iluminize.com/de/shop/led-steuerung/wand-dimmer/product/499-511-544-zigbee-wand-dimmer-schalter-rgb-rgbw-rgbws-led-4z.html
- picture:
![grafik](https://user-images.githubusercontent.com/34628456/163240574-67bfcbbb-e5c2-4c98-8fd1-346ce7de7200.png)

If you need further information, please let me know.

### Node-Info:
![grafik](https://user-images.githubusercontent.com/34628456/163237744-c1944424-0a19-4491-86d8-8f3c054185aa.png)

![grafik](https://user-images.githubusercontent.com/34628456/163238033-8585485c-0931-4210-aac8-afc64c6ae37f.png)

### Basic
![grafik](https://user-images.githubusercontent.com/34628456/163238297-77dc1c5c-d169-4f5a-93f5-27e9963e0067.png)

### Identify
![grafik](https://user-images.githubusercontent.com/34628456/163238570-3797cb08-eccb-4734-8a25-1aa00d244a0e.png)

### Diagnostics
![grafik](https://user-images.githubusercontent.com/34628456/163238721-33a2ada7-02a2-4b29-995c-bb83cb7f04da.png)
![grafik](https://user-images.githubusercontent.com/34628456/163238799-fd6d71e7-cf73-49a6-a79c-76c33334a945.png)

### Groups
![grafik](https://user-images.githubusercontent.com/34628456/163254390-5b8d7175-f268-400a-9857-735e74e98cf1.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/34628456/163254492-2e0773c4-b348-4ce2-8d56-47e36386ad64.png)

### Level Control
![grafik](https://user-images.githubusercontent.com/34628456/163254598-8dcfd2a0-b3cb-485d-ab0f-6c986dc147de.png)

### Color Control
![grafik](https://user-images.githubusercontent.com/34628456/163255029-98b2e133-8638-45fb-b5f1-1d1871534f35.png)

### ZLL commissioning
![grafik](https://user-images.githubusercontent.com/34628456/163254064-78068eb5-403a-41c3-8a9d-06ca12556f12.png)
![grafik](https://user-images.githubusercontent.com/34628456/163254183-73640092-45b7-412f-bcc2-a87671914c9e.png)

### OTAU
![grafik](https://user-images.githubusercontent.com/34628456/163254804-d5e08237-6b3c-43d6-b4bb-29b1d445e080.png)
![grafik](https://user-images.githubusercontent.com/34628456/163254940-6a1f0f75-86e0-4ae2-ba12-0a6029f2c699.png)

The other channels 02 HA
![grafik](https://user-images.githubusercontent.com/34628456/163241976-30e95e21-2c7f-4062-99ec-a3ee9014c573.png)

, 03 HA and 04 HA have all the same values as 01 HA (screenshots above)

**Comment by Mimiix** [comment]
Please add all screenshots.

**Comment by JayJay68** [comment]
I have edit my first post with all screenshots for 
![grafik](https://user-images.githubusercontent.com/34628456/163255414-d82085cf-094b-43c1-8869-45a587aedd59.png)

Do you need all screnshots for "02 HA", "03 HA" and "04 HA", too (they have all the same values)?

And I found at last this one:
![grafik](https://user-images.githubusercontent.com/34628456/163255974-de105310-fdfe-4803-81d0-e880944b1cb2.png)

### Green Power
![grafik](https://user-images.githubusercontent.com/34628456/163256249-826189bd-c7d9-4b80-8548-c807f2eef968.png)

**Comment by JayJay68** [comment]
Do you have all information to integrate the device, now?

**Comment by Mimiix** [comment]
Looks okay now :)

@Smanar is this doable with ddf?

**Comment by Smanar** [comment]
IDK, on m y side I have never succed with switch yet.

**Comment by SwoopX** [comment]
That one should already do the trick

[4grp_dimmer_switch.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8548621/4grp_dimmer_switch.zip)

**Comment by JayJay68** [comment]
Thank you - But what do I have to do with the JSON-file that is in the ZIP file? Copy somewhere?

**Comment by Smanar** [comment]
Yep it's a DDF file. https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

Just need to copy it in a "devices" folder.

**Comment by JayJay68** [comment]
OK, I think that this file could work. What version of deCONZ do you recommend for using the DDF-File (above)? I have currently 2.12.06? If I have to update to a newer version, please recommend only a version that is stable enough for production (using at home from the family)?
Thank you very much for your help.

**Comment by Smanar** [comment]
This stable https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.14.1 is 2 months old, so I think now all issues on it are corrected.

BTW, don't forget to make a backup of zigbee network using phoscon, will help if you want to rollback.

Its the version used in HA (they are using only stable)

**Comment by JayJay68** [comment]
I have to solve other issues first.

github-actions[bot] ***@***.***> schrieb am Sa., 21. Mai
2022, 04:00:

**Comment by JayJay68** [comment]
Please let it opened. I need much more time to solve other problems with higher priority.
