### ISSUE TITLE
Wattle D Pro Multipunkt

### ISSUE THREAD

**Issue by jokerejoker** [dresden-elektronik/deconz-rest-plugin#5959]
## Device

- Product name: Wattle D Pro Multipunkt
- Manufacturer: Home Control AS
- Model identifier: HC-SLM-1
- Device type:
  - Lock

### Basic

![image](https://user-images.githubusercontent.com/1307272/163420758-47dc2f39-dbf9-4213-9e91-28388216056f.png)

### Power Configuration

![image](https://user-images.githubusercontent.com/1307272/163421260-ef188233-3612-435f-be75-044482728dd7.png)

### Identify

![image](https://user-images.githubusercontent.com/1307272/163420824-669b8480-02a0-4cc1-af9b-808d2b9821bc.png)

### Groups

![image](https://user-images.githubusercontent.com/1307272/163420936-8761bf47-51d0-4d89-a37a-de4290d26daf.png)

### Scenes

![image](https://user-images.githubusercontent.com/1307272/163421018-1f4fad75-e97f-4b22-8e6c-a2ffe01bcd46.png)

### Power Configuration

![image](https://user-images.githubusercontent.com/1307272/163421260-ef188233-3612-435f-be75-044482728dd7.png)

### Door Lock

![image](https://user-images.githubusercontent.com/1307272/163421389-a7b67785-84c0-484c-9b28-0a4084d58d4a.png)

### OTAU

![image](https://user-images.githubusercontent.com/1307272/163422026-57f25c14-e714-462a-9df7-e17232a99cef.png)

**Comment by Smanar** [comment]
Hello.
The support for doorlock is not yet official, making one here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5870

can try this DDF to make tries.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Home Control AS",
  "modelid": "HC-SLM-1",
  "vendor": "Wattle",
  "product": "Wattle D Pro Multipunkt",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_DOOR_LOCK",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 0) { Item.val = 'open' } else if (Attr.val == 1) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 11,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}


```

**Comment by jokerejoker** [comment]
Thanks, will try it out.

My previous danalock was just recognized as a light bulb and that work fine. Any chance that could be a temporary solution, until the door lock support is implemented?

Anything i can do to help on the door lock support?

**Comment by Smanar** [comment]
Long time door lock are no more reconized as bulbs (even the code is already here for old device like the danalock)
They are now sensor, ZHADoorlock, what is your third app ? They support probably this sensor.

>Anything i can do to help on the door lock support?

Yep sure, testing the DDF ^^. DDF is the future, I can make change on the core but only to help for DDF support.

**Comment by jokerejoker** [comment]
What do you mean by my third app? Is it home assistant you are referring to?

**Comment by Smanar** [comment]
Yep, for exemple.
And I can confirm, The HA plugin support ZHADoorlock https://github.com/home-assistant/core/pull/48516

**Comment by jokerejoker** [comment]
After adding the DDF to the devices folder, the "Add new sensor" wizard reacted by "New sensor ready", but the lock does not appear afterward in the list of sensors, in Phoscon.

This is the result when pulling the /sensors API:

```
{
    "5": {
        "config": {
            "battery": null,
            "on": true,
            "reachable": true
        },
        "etag": "c8e8698169d827b5044498cb7cc54911",
        "lastannounced": "2022-04-16T16:03:01Z",
        "lastseen": "2022-04-16T16:07Z",
        "manufacturername": "Home Control AS",
        "modelid": "HC-SLM-1",
        "name": "$TYPE_DOOR_LOCK 5",
        "state": {
            "lastupdated": "none",
            "open": null,
            "reachable": null
        },
        "type": "$TYPE_DOOR_LOCK",
        "uniqueid": "68:0a:e2:ff:fe:7b:49:40-01"
    }
}
```

![image](https://user-images.githubusercontent.com/1307272/163682647-f2e29c7f-a3fa-4f1b-8495-a84c234246f6.png)

I think we are close, but I am not too familiar with the DDF declarations yet, so please advice on what is wrong and what should be corrected.

**Comment by Mimiix** [comment]
It wont show in phoscon as they need to add support for it.

**Comment by jokerejoker** [comment]
Okay, and that is what is going on at issue #5870 ?

**Comment by Smanar** [comment]
>"type": "$TYPE_DOOR_LOCK",

Wich one deconz version are you using ? There is so much things missing.

>Okay, and that is what is going on at issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5870 ?

Nothing special, just he don't have so much time for test.

**Comment by jokerejoker** [comment]
I just quickly tested it with the deconz packaged with the hassio (home assistant) core add-on for deconz. It is version 2.14.1

**Comment by jokerejoker** [comment]
@Smanar any thoughts ?

**Comment by Smanar** [comment]
Yep you need this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5906, so at least the version v2.15.1

**Comment by jokerejoker** [comment]
I will build and test a version, of the HA deCONZ Add-on, with the 2.15.1-beta as soon as possible

**Comment by Smanar** [comment]
You don't need to build/recompile the library, the 2.15.1 is available, but not sure how to update it on HA.

**Comment by jokerejoker** [comment]
Yes, it was also for the HA plugin that I ment :)

I any ETA on the 2.15.1 stable ?

**Comment by Smanar** [comment]
New stable out https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.15.3

Tell me if the DDF is working ?

**Comment by jokerejoker** [comment]
Awesome! I will test it with in the next days.

FYI - HA addon has been officially updated with the new version

**Comment by jokerejoker** [comment]
This appear to be the result from the API.

![image](https://user-images.githubusercontent.com/1307272/168486435-0c7fc4a1-5f30-4ed4-8466-6b04c274d6d4.png)

Execution of lock/unlock command does not appear, lock state does not seam to come through and to be working and battery state is not available. This is properbly due to the DDF being configured wrong?

Also the lock is not recognized correctly by the HA plugin, but is might not be you who need to take a look at that :)

![image](https://user-images.githubusercontent.com/1307272/168486669-ffccd32e-ee72-4986-b810-8ab9e2498c88.png)

I well get back to about if the lock disconnects it self. How long would you expect for to do so ?

**Comment by Smanar** [comment]
Oups sorry m y bad, I m using bad endpoint on the DDF (you need the 0x01 and I m using "11"
Can you try this one

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Home Control AS",
  "modelid": "HC-SLM-1",
  "vendor": "Wattle",
  "product": "Wattle D Pro Multipunkt",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_DOOR_LOCK",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 0) { Item.val = 'open' } else if (Attr.val == 1) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

>I will get back to about if the lock disconnects it self. How long would you expect for to do so ?

The previous user that have the issue have a DC after somes days, but there is some improvement ATM for this issue on the Danalock one.

**Comment by micv83** [comment]
When will this DDF be included in the officiel release ?

**Comment by Mimiix** [comment]
@micv83 once we know it works :)

**Comment by micv83** [comment]
Would love to test the DDF, but running the official deconz addon there is no easy way, as far as I know ?

**Comment by Smanar** [comment]
Hello, what is your OS, I think the " official deconz addon" mean HA ? https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by micv83** [comment]
Sorry, yes it's HA :-) That is actually a pretty good guide. Managed to edit the DDF, so i'll try testing the device later today or tomorrow.

**Comment by micv83** [comment]
Uploaded your DDF @Smanar, and the lock is now recognized as a lock, but it is not exposed to HA. 

![image](https://user-images.githubusercontent.com/46919148/189960100-bd1897b2-af6d-4d45-b905-241fa14629c9.png)

**Comment by Smanar** [comment]
Ha I have exactly the same problem here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5870#issuecomment-1245631892

**Comment by micv83** [comment]
Okay 😝 Hope somebody figure out the problem. It’s supported in zigbee2mqtt, so I might have to give that a try😊

**Comment by Smanar** [comment]
Ok, so can you try this new DDF pls ?

{
  "schema": "devcap1.schema.json",
  "manufacturername": "Home Control AS",
  "modelid": "HC-SLM-1",
  "vendor": "Wattle",
  "product": "Wattle D Pro Multipunkt",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "ZHADoorLock",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 1) { Item.val = 'open' } else if (Attr.val == 2) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 0) { Item.val = 'open' } else if (Attr.val == 1) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}

**Comment by micv83** [comment]
A bit better, the lock is now partially presented to HA. But the lock item is unavailable and battery status shows 0%...

![image](https://user-images.githubusercontent.com/46919148/190137060-2a86e98a-36fe-4531-9e2d-b781f689c924.png)

**Comment by Smanar** [comment]
I m making the correction on the other issue, but for the battery, can you check in deconz where I can find it ?
On the capture on the first post, on the power configuration cluster, both values are 0.

**Comment by micv83** [comment]
After pushing read i deconz Power Configuration Cluster i get this:

![image](https://user-images.githubusercontent.com/46919148/190336584-f6ec7f14-1d25-48cb-9353-78a5f3f6b4cb.png)

**Comment by Smanar** [comment]
Ok so let's try with the attribute 0x0021

Take care this new DDF will generate a new unique ID.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Home Control AS",
  "modelid": "HC-SLM-1",
  "vendor": "Wattle",
  "product": "Wattle D Pro Multipunkt",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "ZHADoorLock",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0101"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 11,
            "eval": "if (Attr.val == 0) { Item.val = 'not fully locked' } else if (Attr.val == 1) { Item.val = 'locked' } else if (Attr.val == 2) { Item.val = 'unlocked' } else { Item.val = 'undefined' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 0) { Item.val = 'open' } else if (Attr.val == 1) { Item.val = 'closed' } else { Item.val = 'error' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by micv83** [comment]
Result:

![image](https://user-images.githubusercontent.com/46919148/190483747-81181a03-18fb-4a9f-8535-0c0445359b16.png)

**Comment by Smanar** [comment]
And it works or not ?

**Comment by micv83** [comment]
I've tried changing to:

 {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },

Still shows 0%, but will wait 24h.

**Comment by micv83** [comment]
Okay, after pressing read again in Deconz so 0x0021 shows 199 again, battery status updates in HA to 100% :-)

**Comment by micv83** [comment]
Any news @Smanar ?

**Comment by Mimiix** [comment]
@micv83  Just to let you know: Smanar is on Holiday. I think he will be back in a few days.

**Comment by micv83** [comment]
Okay, and in a few days i will be on holiday :-)

**Comment by micv83** [comment]
Only the batterystatus worked with the last changes. Did you make any changes to the lock part, in the latest DDF ?

**Comment by Smanar** [comment]
Oups my bad, sorry it s the new DDF (working on another device)

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Home Control AS",
  "modelid": "HC-SLM-1",
  "vendor": "Wattle",
  "product": "Wattle D Pro Multipunkt",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "ZHADoorLock",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0101"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 0) { Item.val = 'not fully locked' } else if (Attr.val == 1) { Item.val = 'locked' } else if (Attr.val == 2) { Item.val = 'unlocked' } else { Item.val = 'undefined' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val !=1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by micv83** [comment]
Still no luck, with the lock part. 

Changed DDF, did hot reload, also complete restart of Deconz and reinitialize Deconz plugin in HA. 

![image](https://user-images.githubusercontent.com/46919148/192580846-1a554fec-cb1e-482c-b8f3-5b8d37308a2f.png)

**Comment by Smanar** [comment]
Have you tried to delete the device in HA and resynchronise it ?
Perhaps an error on HA logs ?

Can you share how look the device json ? you can see it in phoscon / help / API Information / sensor

**Comment by micv83** [comment]
Tried removing the batteries from the lock an insert again. Now the lock status is shown when unlocking directly on the lock. 😄 But Pushing lock or unlock in HA does nothing.

**Comment by Smanar** [comment]
```
"state": {
  "lastupdated": "none",
  "lockstate": null,
  "open": null,
  "reachable": null
},
```

I think here, you have new values now ? reachable is now true ?
It's the only field that can prevent HA to make the request. So if the value is true, you have something in log.

Can try too direclty with the API.

`curl -H 'Content-Type: application/json' -X PUT -d '{"lock": true}' http://IP:PORT/api/KEY/sensors/ID/config`

IP and PORT are the same you can see when using phoscon
KEY is an API key, can use the same used by HA
ID is the device id, probably 65 from your last capture.

**Comment by micv83** [comment]
Reachable is still null:

{
    "config": {
        "battery": 100,
        "lock": true,
        "on": true,
        "reachable": true
    },
    "etag": "08487aa99b30bfa47f94a3e59b86717b",
    "lastannounced": "2022-09-27T23:20:29Z",
    "lastseen": "2022-09-28T12:04Z",
    "manufacturername": "Home Control AS",
    "modelid": "HC-SLM-1",
    "name": "DoorLock 65",
    "state": {
        "lastupdated": "2022-09-28T12:04:32.359",
        "lockstate": "locked",
        "open": null,
        "reachable": null
    },
    "type": "ZHADoorLock",
    "uniqueid": "68:0a:e2:ff:fe:7b:60:cc-01-0101"
}

**Comment by Smanar** [comment]
```
"state": {
   "lastupdated": "2022-09-28T12:04:32.359",
   "reachable": null
},
```

Ok so new issue ....
But you are on HA ? so you are using the last stable version for deconz available for it ?

**Comment by Smanar** [comment]
@micv83 and if you use 

`"sleeper": true,`

**Comment by micv83** [comment]
I’m on deconz version 2.17.1 I have 2.18.2 available, but don’t know if an update will wipe the custom ddf, I’m away at the moment so won’t be able to upload the ddf again.

**Comment by Smanar** [comment]
ok, I m asking some tips to other devs, I will give you a new DDF "last hope" soon.

**Comment by Smanar** [comment]
Ok so ebaauw have found the probleml, the DDF was made with the first one (from may), It was totally out. I m using state/reachable, and for sensor It's config/reachable.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Home Control AS",
  "modelid": "HC-SLM-1",
  "vendor": "Wattle",
  "product": "Wattle D Pro Multipunkt",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "ZHADoorLock",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0101"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "config/lock",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val == 1",
            "fn": "zcl"
          }
        },
        {
          "name": "state/lockstate",
          "read": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0101",
            "ep": 1,
            "eval": "if (Attr.val == 0) { Item.val = 'not fully locked' } else if (Attr.val == 1) { Item.val = 'locked' } else if (Attr.val == 2) { Item.val = 'unlocked' } else { Item.val = 'undefined' }",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "read": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0101",
            "ep": 1,
            "eval": "Item.val = Attr.val != 1",
            "fn": "zcl"
          }
        },
        {
          "name": "config/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0101",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x30",
          "min": 1,
          "max": 300
        },
        {
          "at": "0x0003",
          "dt": "0x30",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by micv83** [comment]
Super! I’ll test it as soon as I have returned from holiday. 😊

**Comment by micv83** [comment]
State in now correcly displayed when locked/unlocked from the lock, but i'm still not able to lock/unlock from HA.

But it shows reachable in API now.
{
    "config": {
        "battery": 100,
        "lock": false,
        "on": true,
        "reachable": true
    },
    "etag": "65fa13a7527403ed7852311da07c1ec0",
    "lastannounced": "2022-10-08T17:22:58Z",
    "lastseen": "2022-10-08T17:23Z",
    "manufacturername": "Home Control AS",
    "modelid": "HC-SLM-1",
    "name": "DoorLock 65",
    "state": {
        "lastupdated": "2022-10-08T17:23:59.541",
        "lockstate": "locked",
        "open": null
    },
    "type": "ZHADoorLock",
    "uniqueid": "68:0a:e2:ff:fe:7b:60:cc-01-0101"
}

**Comment by Smanar** [comment]
All seem fine, even the lastupdated have worked, except the state/open=null, perhaps a bind problem, canbe solved later by deconz.
You don't have error message in HA ?

Can you try direclty with API


`curl -H 'Content-Type: application/json' -X PUT -d '{"lock": true}' http://IP:PORT/api/KEY/sensors/ID/config`

IP and PORT are the same used than phoscon
KEY is an apikey, can use the same one than the one used by HA
ID is the device id.

**Comment by micv83** [comment]
Tried the 2 changes, but then i was unable to even get the status from the lock, so went back to the DDF from before and got the status working again. Hope I wasn’t to impatient, as the lock sometimes takes a bit to update correctly after a deconz restart. If the changes should work, I can try them again.

Don’t know how to extract the apikey from HA or deconz, to do the api call manually?

**Comment by Smanar** [comment]
Next here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/8073
