### ISSUE TITLE
Sensors do not get loaded or assume a different ID than in the DB

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/deconz-rest-plugin#5965]
## Describe the bug

To be updated, as this is complex to describe. However, the consequences are easy to describe, as sensor IDs get assigned more than once. This could lead to sensors not being shown in REST API or sensors getting stored with wrong IDs.

Note that in the screenshots below, sensor ID 154 is used twice. First occurance of 154 would be correct (see database screenshots)

Root cause is that when using DDFs, "legacy" sensors are not loaded via `sqliteLoadAllSensorsCallback()`, but skipped. Therefore, vector `plugin->sensors` has an inadequate size, which should reflect all sensors, not just a few. 

Interestingly, the DDF code tries to load the subdevices a little later and to determine if a new sensor ID is required or not and this is where it gets bad. Due to that wrong size, `getFreeSensorId()` assumes any left out sensor ID is free and available, although this is not (necessarily) the case. Once the subdevice is loaded/created, the sensor gets pushed to the `sensors` vector via `DEV_AddResource()`, which is too late to have been previously considered as it should be.

## Steps to reproduce the behavior

Conditions to reproduce are not fully clear However, it requires 2 DDF devices having valid sensors in the `sensors` DB table. One of those devices must have the correct amount of subdevices in table `sub_devices`, the oser one must have more than 1 sub device according to DDF, *where one of the subdevices is non-existent in table `sensors`*. It is important for that missing sensor, a new "free" sensor ID will get selected. Additionally, some further debug output is required, otherwise it is very hard to implicitly spot the issue.

## Expected behavior

- deconz loads all sensors with their respective IDs as they are stored in the DB
- deconz does expose all available sensors
- deconz gets enabled to determine the true next free sensor ID

## Screenshots

![grafik](https://user-images.githubusercontent.com/4005212/163790976-f4dad0ad-2ed5-4d9f-864e-34b07958a43a.png)

![grafik](https://user-images.githubusercontent.com/4005212/163790997-dcdbe8ec-d519-4a09-ab29-8806888c941c.png)

Respective DB entries:

![grafik](https://user-images.githubusercontent.com/4005212/163791779-c91b94d7-e729-4603-bf4d-1ff3b995e750.png)

Overall DB entries in `sensors`, illustrating `sensors` vector is populated too late:

![grafik](https://user-images.githubusercontent.com/4005212/163791993-cd59342a-bb09-4988-a97f-8fd3c1562c33.png)

Sensors getting overwritten by each other:

![grafik](https://user-images.githubusercontent.com/4005212/163863289-c923563f-c735-45e7-bde0-6010e1292053.png)

## Environment

 - Host system: irrelevant
 - Running method: irrelevant
 - Firmware version: irrelevant
 - deCONZ version: 2.15.1 (and presumably down to 2.13.0)
 - Device: irrelevant
 - Do you use an USB extension cable: irrelevant
 - Is there any other USB or serial devices connected to the host system? irrelevant

## Additional context

The same issue or something similar might eventually apply for light resources as well (hasn't been checked from my end).

**Comment by manup** [comment]
PR is updated and should fix the issue. It also removes duplicated sensors and keeps the one with the lowest `id`.

**Comment by SwoopX** [comment]
Indeed. As far as I can tell, that resolves the issue

![grafik](https://user-images.githubusercontent.com/4005212/164105592-227d69d6-4fb4-4363-81d8-6c11c0fe80fe.png)

![grafik](https://user-images.githubusercontent.com/4005212/164105770-f8eb07b7-f888-4ad2-8ce3-c4653ba9ba36.png)

![grafik](https://user-images.githubusercontent.com/4005212/164105952-b34a7cbb-275a-4632-8ddb-01655cec5e14.png)

The missing sensor got the true first free ID

![grafik](https://user-images.githubusercontent.com/4005212/164106280-49a611b8-88f6-49be-a602-c97fffa3c7db.png)

**Comment by manup** [comment]
Nice so remaining todo is only the case insensitive checks for manufacturer name.
We might also ditch the 0006/1000 separation of Sunricher DDFs in favor of 0006, if a ZHASwitch exists with 1000 in the db it will be picked up automatically.

**Comment by SwoopX** [comment]
Yeah, I guess that would aid in keeping things clean(er).
