### ISSUE TITLE
ubisys J1 returns pct = 0 since update to version v2.15.1-beta

### ISSUE THREAD

**Issue by Rolf56** [dresden-elektronik/deconz-rest-plugin#5966]
## Describe the bug

ubisys J1 returns pct = 0 when covering device is not fully open and pct = 100 when covering device is open. There is no other value between returned. The only value returning is "bri".  This happens since update to version v2.15.1-beta. When sending a pct value to the covering device, it moves to the right position.

## Steps to reproduce the behavior

The problem occures all the time, also on a second device installed.

## Screenshots

![image](https://user-images.githubusercontent.com/44340206/164888069-04b6c05c-a23b-41c1-a079-484ea66ceae6.png)
In Postman there is an attribut 'lift' what coresponds with 'Current Position Lift Percentage' (pct) in the cluster info!

![image](https://user-images.githubusercontent.com/44340206/164888102-90cee946-2b30-4ea2-88c6-5289fc1b721e.png)
![image](https://user-images.githubusercontent.com/44340206/164888124-da90108c-6dca-4ff3-8d1d-ee07af109bbc.png)
![image](https://user-images.githubusercontent.com/44340206/164888138-0427200e-6c1b-4f69-8705-1430eae170fe.png)
![image](https://user-images.githubusercontent.com/44340206/164888166-37be3d71-9a25-4bdf-9e22-b982f4615749.png)

![Bild_2022-04-19_161650013](https://user-images.githubusercontent.com/44340206/164024801-091166c7-fc6b-4aad-8745-3bd579b2e61b.png)

## Environment

 - Host system: PC
 - Running method:  Windows
 - Firmware version: 26400500
 - deCONZ version: 2.15.01
 - Device: ConBee I
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so: Which? non

**Comment by SwoopX** [comment]
This is not a bug and has nothing to do with deconz. Rubbing my crystal ball, your device has lost position awareness either by a power loss or by rebooting itself for whatever reason (see ubisys technical reference).

When cover is opened, move it down and then immediately up, that should restore it.

**Comment by Rolf56** [comment]
Hi SwoopX
Thank you for your answer. I do not agree with you. The value 'Current Position Lift Percentage', what I think is the pct value, corresponds with the cover position in deCONZ UI.

![image](https://user-images.githubusercontent.com/44340206/167121441-bedd4366-bca5-41e3-99bc-3ff021f3d0c6.png)

But the pct value is missing in the REST interface! It is also not defined in the file **j1_5502.json**!
The DDF for J1 was changed in version [v2.15.1-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/tree/v2.15.1-beta) and exact since then it does not work anymore correctly!

![image](https://user-images.githubusercontent.com/44340206/167122018-c6defa40-0a2d-43f1-bfbd-b08a9758460b.png)

Yes, I moved the cover down and up, also in configuration mode. This changed nothing.
Maybee you can rubbing your crystal ball again, to find out what happen with this release [v2.15.1-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/tree/v2.15.1-beta) https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5894

**Comment by SwoopX** [comment]
Well, apparently, rubbing the crystal ball is not such a good fortune teller after all, q.e.d.

Now back to the topic and allow me to set your expectations right.

> But the pct value is missing in the REST interface! It is also not defined in the file j1_5502.json!

Deconz does not expose a `pct` parameter and never has, however, your perception of `Current position lift percentage` is correct, but it maps to `lift` (raw value) and `bri` (with a calculation behind it). Now I know the HUE device perl module never picked up the `lift` values (at least not with the version I checked last time about 9 months ago), but is doing some magic on `bri` to deduce the pct value you mean. Will have a look if the `bri` calculation remained identical while purging it from the code (and moving it to the DDF).

In Phoscon, when you go to _Help -> API Information_, then select lights and choose your cover and finally click on events, you see what deconz sends towards FHEM.

That's what my cover sends over:

```
{
    "10:27:37:779": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 13,
            "lift": 5
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:39:311": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 20,
            "lift": 8
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:40:307": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 0,
            "lift": 0
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:42:990": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 13,
            "lift": 5
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:44:43": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 28,
            "lift": 11
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:45:197": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 43,
            "lift": 17
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:46:66": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 58,
            "lift": 23
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:27:47:596": {
        "e": "changed",
        "id": "12",
        "r": "lights",
        "state": {
            "bri": 71,
            "lift": 28
        },
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    },
    "10:28:01:839": {
        "attr": {
            "lastseen": "2022-05-07T08:27Z"
        },
        "e": "changed",
        "id": "12",
        "r": "lights",
        "t": "event",
        "uniqueid": "00:1f:ee:00:00:xx:xx:xx-01"
    }
}
```

And FHEM updates fine:

![grafik](https://user-images.githubusercontent.com/4005212/167266932-bdb097fa-0929-4e58-ae28-700b93e5e4fe.png)

Now, to be fair, I'm using a completely self written perl module here which is tailored just for deconz' REST API, only processing `lift` for cover position. A bit like comparing apples and pears. Regardless, I'll double check the bri calculation.

**Comment by SwoopX** [comment]
I assume the subtype in the attributes is (still) `blind`?

From a code perspective, I cannot see any difference (DDF left, legacy code right)

![grafik](https://user-images.githubusercontent.com/4005212/167268931-73a271a1-5acc-4228-8cbb-088f633cd7ab.png)

**Comment by Rolf56** [comment]
Hallo SwoopX

Dank für die Angaben. Schade dass pct nicht mehr geht. Somit werde ich meine Abfragen von pct auf bri umstellen müssen.

Grüsse, Rolf


Von: SwoopX
Gesendet: Samstag, 7. Mai 2022 21:25
An: dresden-elektronik/deconz-rest-plugin
Cc: Rolf56; Author
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] ubisys J1 returns pct = 0since update to version v2.15.1-beta (Issue #5966)

I assume the subtype in the attributes is (still) blind?
From a code perspective, I cannot see any difference (DDF left, legacy code right)

**Comment by Mimiix** [comment]
Hi there, Can you please translate to English? Thanks :)!
