### ISSUE TITLE
Zemismart Curtain Motor Robot ZM85EL-2Z

### ISSUE THREAD

**Issue by gmitch64** [dresden-elektronik/deconz-rest-plugin#5977]
## Device

- Product name: ZM85EL-2Z
- Manufacturer: _TZE200_cf1sl3tj
- Model identifier: TS0601
- Device type : Please remove all unrelated device types. 

  - Other:  Smart Curtain Robot Motor - So I guess a light?

https://www.zemismart.com/products/zm85el-2z

## Screenshots

![image](https://user-images.githubusercontent.com/27970644/164956925-2b740ca8-0ee3-4e6c-b0ab-edb5b449a365.png)

### Basic
![image](https://user-images.githubusercontent.com/27970644/164956890-c8521571-890e-4bce-a6a9-59edb801ca31.png)

### Groups
![image](https://user-images.githubusercontent.com/27970644/164956939-89559d09-19c9-4402-b577-b5bab62e4656.png)
![image](https://user-images.githubusercontent.com/27970644/164956978-7036daf8-c08b-4eb9-b9ed-f43769539995.png)

### Scenes
![image](https://user-images.githubusercontent.com/27970644/164956994-ae26e22f-25b6-40b7-9188-6b8f0c88dec4.png)
![image](https://user-images.githubusercontent.com/27970644/164957004-5bf4b54c-f971-4b28-ba6f-a883b7b2ade8.png)
![image](https://user-images.githubusercontent.com/27970644/164957056-15b81e16-3833-4b6b-907a-f8f45182c381.png)
![image](https://user-images.githubusercontent.com/27970644/164957060-2e3aeff9-5755-4da6-9d98-f9aa3ca683d4.png)

### Tuya Specific
![image](https://user-images.githubusercontent.com/27970644/164957083-cde8e7d7-0344-4a5f-9ee7-ce2d27b9484b.png)

Currently running v2.15.2-beta

If there's any other info that's needed, please let me know.

G

**Comment by gmitch64** [comment]
Is there any other info needed from me?

**Comment by gmitch64** [comment]
Do you have an idea of a timescale? Just to set expectations for folks finding this thread?
Should we keep this issue open in the meantime?

**Comment by Smanar** [comment]
Not realy, manup want to make some tries on his side before validating the PR.

**Comment by gmitch64** [comment]
Just wondering how things are progressing?

**Comment by samcourt** [comment]
Any progress? Would love to integrate my blind with the rest of my Home

**Comment by Shuttleu** [comment]
Just got a couple of these, any updates?

**Comment by gmitch64** [comment]
I still have a few of these as well.
It looks like they're supported in zigbee2mqtt, so as soon as I get some time, I'm planning on setting up an mqtt broker and checking that out.

**Comment by Mimiix** [comment]
@Smanar can this be done ?

**Comment by Smanar** [comment]
Nope, nothing have moved for covering.
