### ISSUE TITLE
Upgrade from 2.15.1 to 2.15.2 breaks Icasa Pulse 4S

### ISSUE THREAD

**Issue by wollew** [dresden-elektronik/deconz-rest-plugin#5981]
## Describe the bug

After upgrading my docker container (https://github.com/deconz-community/deconz-docker) from 2.15.1 to 2.15.2 one of my switches fails, it is a "Icasa Pulse 4S" wall switch. I am attaching a log, I also factory reset the switch and tried to repair while the log was running. 

## Steps to reproduce the behavior

Upgrade docker container from 2.15.1 to 2.15.2 with a paired "Icasa Pulse 4S" wall switch 

## Expected behavior

Switch still works.

## Environment

 - Host system: Raspberry Pi 
 - Running method: [Marthoc Docker container](https://github.com/deconz-community/deconz-docker)
 - Firmware version: 26660700
 - deCONZ version: 2.15.02
 - Device: ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? Yes, USB SSD drive
 
## deCONZ Logs

see attachment

**Comment by wollew** [comment]
[deconz.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8565889/deconz.txt)

**Comment by minke890** [comment]
I had the same problem with my Icasa Pulse 4S" wall switch. Also see #5987
