### ISSUE TITLE
Farbwechsel/Color Change

### ISSUE THREAD

**Issue by joecas1** [dresden-elektronik/deconz-rest-plugin#599]
Ich vermisse die Option Farbwechsel in Verbindung mit Phoscon und FLS-PP! Gibts das noch nicht, oder finde ich es nur nicht?

I‘m missing the option to enable the color change in Phoscon together with FLS-PP! Is there nothing like this, or I‘m not able to find it?

**Comment by manup** [comment]
The colorloop is currently not integrated in the Phoscon App. It will first reappear in the generic switch editor. Maybe later on also in the light controls.

Heres a internal screenshots how it may look like in the switch editor.

![colorloop_2](https://user-images.githubusercontent.com/383386/40365839-d5986906-5dd5-11e8-811c-3b870554ddbc.png)

**Comment by davidreher** [comment]
@manup any updates on this?

**Comment by manup** [comment]
>@manup any updates on this?

Enabling color loop can be done with help of a switch as mentioned above. This is part of recent versions.

**Comment by bubffm** [comment]
I don't have a switch and dont intend ti buy one. Is there any chance to trigger such color change / color loop feature using fake switches aka in homebridge?  Thanks
