### ISSUE TITLE
SMaBiT AV2010/21C Flat Magnetic Contact

### ISSUE THREAD

**Issue by WhistleMaster** [dresden-elektronik/deconz-rest-plugin#5992]
## Device

- Product name: SMaBiT AV2010/21C Flat Magnetic Contact
- Manufacturer: SMaBiT
- Model identifier: AV2010/21C
- Device type : Sensor

https://manuals.smabit.eu/len/av2010_21c.html

## Screenshots

<img width="508" alt="Screenshot 2022-04-30 at 10 03 07" src="https://user-images.githubusercontent.com/1544568/166097519-96e08072-9e9a-4ed4-b612-7630ba6d98d9.png">
<img width="569" alt="Screenshot 2022-04-30 at 10 03 20" src="https://user-images.githubusercontent.com/1544568/166097521-47d807b6-e206-4821-a8a6-9024f4a4f835.png">

### Basic
<img width="516" alt="Screenshot 2022-04-30 at 10 03 32" src="https://user-images.githubusercontent.com/1544568/166097527-fff7b07e-6e7a-45fb-a54d-8b32046e7100.png">

### Power Configuration
<img width="514" alt="Screenshot 2022-04-30 at 10 03 42" src="https://user-images.githubusercontent.com/1544568/166097615-f11ec421-d12e-47d3-a493-8a78ad332e1b.png">

### Identify
<img width="516" alt="Screenshot 2022-04-30 at 10 04 00" src="https://user-images.githubusercontent.com/1544568/166097533-529bfdcc-b068-4ecd-87c3-92e811b05536.png">

### IAS Zone
<img width="592" alt="Screenshot 2022-04-30 at 10 09 43" src="https://user-images.githubusercontent.com/1544568/166097575-e3c2aa02-978b-423f-8555-5056aed8d1a4.png">

### Poll Control
<img width="514" alt="Screenshot 2022-04-30 at 10 04 09" src="https://user-images.githubusercontent.com/1544568/166097599-0fe5c609-41a5-4bda-b469-7f86a9bd04ee.png">

### Others
<img width="514" alt="Screenshot 2022-04-30 at 10 04 23" src="https://user-images.githubusercontent.com/1544568/166097636-ef6e0c69-18a6-46d1-8510-7a4909c3b499.png">
<img width="519" alt="Screenshot 2022-04-30 at 10 06 02" src="https://user-images.githubusercontent.com/1544568/166097637-1eb88c45-5bd4-4235-a4db-cf03ed5cdacc.png">

**Comment by Mimiix** [comment]
@Smanar Can this be done with ddf?

**Comment by Smanar** [comment]
Sure, can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SMaBiT",
  "modelid": "AV2010/21C",
  "vendor": "SMaBiT",
  "product": "SMaBiT AV2010/21C Flat Magnetic Contact",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open",
          "awake": true,
          "parse": {
            "at": "0x0002",
            "cl": "0x0500",
            "ep": 1,
            "eval": "Item.val = (Attr.val & 0x3) != 0"
          }
        }
      ]
    }
  ]
}
```


If the value is updated when reading it in deconz but not automatically.
Add a binding from the cluster 0x0500 https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel
Retry (save the file and make "hot relaod" on the menu)
If It don't work add a report for the attribute 0x0021
To have something like
```
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    }
  ]
```

**Comment by WhistleMaster** [comment]
Thanks for the DDF file ! I've tried but unfortunately, I don't get any values, manually or automatically.

In the API, I get:

```
    "196": {
        "config": {
            "on": true,
            "pending": [],
            "reachable": null
        },
        "ep": 1,
        "etag": "<<REDACTED>>",
        "lastannounced": null,
        "lastseen": "2022-05-01T06:53Z",
        "manufacturername": "SMaBiT",
        "modelid": "AV2010/21C",
        "name": "OpenClose 196",
        "state": {
            "lastupdated": "none",
            "lowbattery": null,
            "open": null
        },
        "type": "ZHAOpenClose",
        "uniqueid": "<<REDACTED>>"
```

The 0x0500 cluster is still like that:

<img width="588" alt="Screenshot 2022-05-01 at 09 09 28" src="https://user-images.githubusercontent.com/1544568/166135999-afead405-8c94-4218-a18b-d4cb9ac3eb05.png">

This is the result I got after following your indications:

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SMaBiT",
  "modelid": "AV2010/21C",
  "vendor": "SMaBiT",
  "product": "SMaBiT AV2010/21C Flat Magnetic Contact",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin",
          "public": false,
          "refresh.interval": 3600,
          "default": 14400
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open",
          "awake": true,
          "parse": {
            "at": "0x0002",
            "cl": "0x0500",
            "ep": 1,
            "eval": "Item.val = (Attr.val & 0x3) != 0"
          }
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by WhistleMaster** [comment]
A quick update, after re-pairing the sensor, it worked ! I've updated my previous comment.

**Comment by Smanar** [comment]
So you need all the binding part ?

```
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    }
  ]
```

I m asking because not all device support it, if you can confirm I will make the PR if you don't want to make it yourself ?

**Comment by SwoopX** [comment]
I'm afraid the DDF needs to be updated in several ways:

- The reporting of the respective bindings goes against a non-existent attribute. You don't do any reporting configuration on the IAS zone cluster
- There is no `config/battery` resource item
- Please use the default implementation for `state/open`, so remove the `parse` stanza
- There is no binding and reporting against the power configuration cluster
- Please remove "SMaBiT" in the `product` item
- Please read the device request template carefully. It said to **read** all clusters prior to posting screenshots. All screenshots do not have them read and show defaults

**Comment by Smanar** [comment]
>The reporting of the respective bindings goes against a non-existent attribute. You don't do any reporting configuration on the IAS zone cluster

Right, so if it work you, mean you can remove the reporting part

>There is no config/battery resource item

There is no vlaue on the capture, so I use state/lowbattery instead

>There is no binding and reporting against the power configuration cluster

Some explanation than before

>Please read the device request template carefully. It said to read all clusters prior to posting screenshots. All screenshots do not have them read and show defaults

Can change the DDF I have value


```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SMaBiT",
  "modelid": "AV2010/21C",
  "vendor": "SMaBiT",
  "product": "AV2010/21C Flat Magnetic Contact",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by WhistleMaster** [comment]
>  Please read the device request template carefully. It said to **read** all clusters prior to posting screenshots. All screenshots do not have them read and show defaults

Thanks for the reply ! I've read all clusters now:

### Basic
<img width="600" alt="Screenshot 2022-05-01 at 19 36 41" src="https://user-images.githubusercontent.com/1544568/166157640-3b6f53f0-05a7-4760-9c7c-842b11134c79.png">

### Power Configuration
<img width="604" alt="Screenshot 2022-05-01 at 19 36 55" src="https://user-images.githubusercontent.com/1544568/166157641-f8f1faa0-1a63-4b75-a1e0-37532896369d.png">

### Identify
<img width="604" alt="Screenshot 2022-05-01 at 19 37 03" src="https://user-images.githubusercontent.com/1544568/166157642-6279d9cd-8d86-46da-9b80-86f2cd809739.png">

### IAS Zone
<img width="618" alt="Screenshot 2022-05-01 at 19 37 42" src="https://user-images.githubusercontent.com/1544568/166157643-55c0b2f6-4465-4d8c-8c21-9a4bd5e5afa9.png">

### Poll Control
<img width="630" alt="Screenshot 2022-05-01 at 19 41 05" src="https://user-images.githubusercontent.com/1544568/166157786-922e2e06-0d6b-4c9d-9a6d-a8476c3779e5.png">

**Comment by Smanar** [comment]
Ok, so no more changes on my side, It seem your device don't use the cluster power configuration so you will have only the the state/lowbattery.

You can test the last one on my last post.

**Comment by WhistleMaster** [comment]
I've updated the DDF+hot-reload and it's still working fine ! Thanks !
