### ISSUE TITLE
Harmony Hub - Groups dont work / are Empty

### ISSUE THREAD

**Issue by almostserious** [dresden-elektronik/deconz-rest-plugin#5996]
## Describe the bug
When adding deconz to Harmany Hub I am able to controll each individual light.
As soon as I create a Group within the Harmony Hub though, the lights dont react anymore to group calls.
They still reflect and behave fine if called individually.

This is because the groups that are created do not contain any lights within Deconz.

## Steps to reproduce the behavior
  Create new Group with 2 Lights within Harmony
  Toggle Group

Lights will not be toggled.
If Individual Light of the group is toggled it will work fine.

Check the Groups within Phoscon. New Light Group with Naming Scheme:
hgrp-0000XXXXX will be there, but it will not contain any lights.

## Expected behavior
All Groups should work. 

## Environment
2.14.01 / 6.2.2022
26390500

 - Host system: Proxmox LXC - Debian
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26390500)
 - deCONZ version: (2.14.01)
 - Device: (ConBee I)
 - Do you use an USB extension cable: (yes )
 - Is there any other USB or serial devices connected to the host system? If so:  ZWAVE

**Comment by Mimiix** [comment]
What if you make the groups in phoscon? Do they work then?

**Comment by almostserious** [comment]
Groups in Phoscon are not synced to Harmony.
After first toggle of the Harmony created Group an empty Group popsup.
 This can be edited in Phoscon to make it work.
