### ISSUE TITLE
Hue Tap (Switch) support

### ISSUE THREAD

**Issue by mtvg** [dresden-elektronik/deconz-rest-plugin#6]
Hi, 
I was wondering if the support of the Hue Tap is coming, do you have any ETA for it?
Thank you!

**Comment by manup** [comment]
Yes the support for Hue Tap and ZigBee Green Power Receive Mode will be part of the next release.

**Comment by jonesg5** [comment]
Was this implemented? What is the procedure for joining a Hue Tap to the deCONZ network?
