### ISSUE TITLE
Reach old web app

### ISSUE THREAD

**Issue by Snailboy2** [dresden-elektronik/deconz-rest-plugin#600]
How do i reach the old web app?
When i go to http://ip:8080 it redirects me to http://ip:8080/pwa for some reason.

I need it because for some reason i couldn't find my Ikea lights in pwa but in old web app it works.

**Comment by Snailboy2** [comment]
After a reset i now can add lights. Yey

**Comment by manup** [comment]
The old webapp is also reachable via *Phoscon > Help > Open Old WebApp*.

**Comment by johansvenson** [comment]
I am afraid that in 2.05.34 you are simply redirected to the PWA application - also tried by specifing index.html as well as index.html?v=2.05.34 to no avail.

**Comment by manup** [comment]
Did you try it with the link from the *Phoscon App > help > Open Old WebApp*?
Works here.

You can also open the old WebApp via `http://<ip-address>/login.html`

**Comment by johansvenson** [comment]
Yeps i did... got redirected in all cases... but updated from .20 to .34  and now that part is fine (needed to enable OTAU for which i could not find the checkbox in the pwa app)

**Comment by OrbitingOcelot** [comment]
I think this should be reopened, the "old web app" link does not work thru ingress.

**Comment by Mimiix** [comment]
@OrbitingOcelot this is something that the HA addon should fix, we can't fix it.
