### ISSUE TITLE
How to setup scene switch buttons on Ikea Tradfri remote?

### ISSUE THREAD

**Issue by stan23** [dresden-elektronik/deconz-rest-plugin#601]
Hi,
I have 2 Ikea Tradfri remotes working in deCONZ 2.05.27.
They are in the generated dedicated groups with Hue color bulbs and Hue downlights.

How can I setup the _left_ and _right_ button on the remote? Are the supposed to toggle through the scenes? But I cannot create scenes in these dedicated groups.

I've read about pressing the large on/off button for 10 seconds, but that doesn's seem to do anything.

The remotes are on the latest firmware (1.2.214).

**Comment by manup** [comment]
There is a switch editor in the pipeline which will provide this very function (no ETA yet).

Here is a wip screenshot (sorry no english translation yet).

![3](https://user-images.githubusercontent.com/383386/40277531-93fc1a94-5c20-11e8-9682-90728841b217.PNG)

>I've read about pressing the large on/off button for 10 seconds, but that doesn's seem to do anything.

This will setup a color temperature control, however we discovered due different remote firmware versions that it doesn't work well with latest firmware, here again the switch editor will fix that.

So currently to setup scenes you need to setup rules manually. The groups/scenes REST-API has a new methods to allow cycling through scenes:

```
    PUT /api/<apikey>/groups/<group_id>/scenes/next/recall
    PUT /api/<apikey>/groups/<group_id>/scenes/prev/recall
```

**Comment by stan23** [comment]
Thanks for the feedback.
The editor looks nice, German is my primary language :)
It's not a problem to wait. I was wondering if I'm doing sth wrong...

**Comment by markuswebert** [comment]
@manup Are there any news on the new switch editor that supports the TRADFRI remote? Thanks

**Comment by stan23** [comment]
The switch editor is part of the latest beta, and it works quite well.
One difference to the original behaviour of the remote is the dim action: from the editor the short press is always on resp. off, while long press is brighter resp. darker.

**Comment by manup** [comment]
@markuswebert it was added in 2.05.34

Here is a quick overview.
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_34

2.05.35 fixed some related bugs, with more polishing in coming 2.05.36. But it should work quite well especially with IKEA remote :)

**Comment by FearlessSpiff** [comment]
That's great news! Thanks!

**Comment by FearlessSpiff** [comment]
Just had the time to look into it. Now I wanted to ask if you know when the next official release will happen as I have installed it from the repo. Or if I should go through the trouble of removing  the official package and installing the beta one.  I guess that would be the way to do it, correct? Config would work the same, correct? Already made a backup just in case...

**Comment by manup** [comment]
The next stable release is in the pipeline but will take a few weeks.

Anyway you can just install the beta package since both stable and beta releases share the same configuration. Doing a backup prior is still recommended.

**Comment by georgbachmann** [comment]
Hey @manup .
Did this update ever make it live? Cause I can at least not see those options for my tradfri remote?!?
I have a `ConBee II` stick with Version 2.05.64 / 22/04/2019 and Firmware 26490700 (which the web-app says is up-to-date)
I don't know my web-app version, but I installed it not that long ago (1 month ago or so) so it should be quite up to date? Didn't find out where to check the version though...

If the feature is already live, can you tell me how to find it?

**Comment by manup** [comment]
Yes the switch editor is available since quite some time and the IKEA remote can be configured with it.
Here is a basic overview where and how the editor can be used:

https://phoscon.de/en/app/doc#group-edit-switches-en

**Comment by georgbachmann** [comment]
Wow... thank you for your fast response! Cool! I guess I tried it the wrong way... 
I tried setting it up via the Switch-Tab and not via the Light Tab. Now I see a UI that look like the one above. Awesome! Thank you!

**Comment by rehmosch** [comment]
> 
> 
> There is a switch editor in the pipeline which will provide this very function (no ETA yet).
> 
> Here is a wip screenshot (sorry no english translation yet).
> 
> ![3](https://user-images.githubusercontent.com/383386/40277531-93fc1a94-5c20-11e8-9682-90728841b217.PNG)
> 
> > I've read about pressing the large on/off button for 10 seconds, but that doesn's seem to do anything.
> 
> This will setup a color temperature control, however we discovered due different remote firmware versions that it doesn't work well with latest firmware, here again the switch editor will fix that.
> 
> So currently to setup scenes you need to setup rules manually. The groups/scenes REST-API has a new methods to allow cycling through scenes:
> 
> ```
>     PUT /api/<apikey>/groups/<group_id>/scenes/next/recall
>     PUT /api/<apikey>/groups/<group_id>/scenes/prev/recall
> ```

dear manup, i installed conbee II on my raspberry pi 4. But i cant see the options to configurate my Buttony on  my Tradfri remote.

How i can get this rest api options? Only to install the rest api github adresses to my ioBroker adapter?

Thank you so much

Jutta from Munich
