### ISSUE TITLE
_TZ3000_n2egfsli - TS0203 - Tuya Smart Zigbee Door Window Contact Sensor

### ISSUE THREAD

**Issue by isaaccs** [dresden-elektronik/deconz-rest-plugin#6015]
## Device

- Product name: Zigbee Door sensor
- Manufacturer: _TZ3000_n2egfsli
- Model identifier: TS0203
- Device type : 
  - Sensor

### Basic
![Capture d’écran 2022-05-04 à 07 54 06](https://user-images.githubusercontent.com/16362659/166629221-33335da1-1dd7-4148-9a99-d142184a2277.png)

### Identify
![Capture d’écran 2022-05-04 à 07 54 37](https://user-images.githubusercontent.com/16362659/166629232-fd5cb4f8-75ae-4b82-9d65-5cf4144f6327.png)

### Other clusters that are not mentioned above
![Capture d’écran 2022-05-04 à 07 55 05](https://user-images.githubusercontent.com/16362659/166629252-8c6e86ab-6e0b-4904-a916-cb25f30e6a44.png)
![Capture d’écran 2022-05-04 à 07 54 58](https://user-images.githubusercontent.com/16362659/166629256-79c523ef-5df8-4472-8b1c-30ac01da7d53.png)

**Comment by Smanar** [comment]
Hello, can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_n2egfsli",
  "modelid": "TS0203",
  "vendor": "Tuya",
  "product": "Smart Zigbee Door Window Contact",
  "sleeper": true,
  "status": "Silver",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by isaaccs** [comment]
where should I put it ?

**Comment by Smanar** [comment]
> All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/deconzuser/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

If you have HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839/2

**Comment by isaaccs** [comment]
I use a docker version on my Unraid system

**Comment by majorsl** [comment]
> where should I put it ?

Where ever you mapped /opt/deCONZ to, they'll be a devices directory in there.  Just put the DDF in that.

**Comment by Smanar** [comment]
Ha ?
It's a new procedure again ? In my mind the HA plugin use docker so was the same procedure ? it's not the same docker image ?

**Comment by majorsl** [comment]
> Ha ?
> It's a new procedure again ? In my mind the HA plugin use docker so was the same procedure ? it's not the same docker image ?

I'm don't know about HA and how they do it.  I run just the version on my RPi with the standard Docker package from deconzcommunity/deconz:latest, my HA is on a different system so I can update deconz or HA and not bring down the entire system for one or the other.  It should be the same for @isaaccs with Unraid assuming he's doing the same as me, which it sounds like.

With that path mapped to the host system, as it should be, all your settings are there so when you update deconz it won't wipe everything out.  To edit, you'll use the text editor of your choice on your docker host system: vim, nano, pico, whatever.  When you and I were testing the DDF for me, I just open a new file in that directory with sim, copy/pasted your excellent DDF and saved with the name you gave.  Worked perfectly and no need to enter the container like on HA.

I could be mistaken, but it seems no other DDFs that are included with deconz are in that directory, it is simply another place that deconz looks for user created ones - which is handy and good design.

**Comment by isaaccs** [comment]
`/root/.local/share/dresden-elektronik/deCONZ` is mapped to `/mnt/user/appdata/deconz`
But i dont have a device folder inside, so I'll create it and add my DDF

**Comment by isaaccs** [comment]
![Capture d’écran 2022-05-10 à 11 30 08](https://user-images.githubusercontent.com/16362659/167597149-57c75d2a-b4ce-4b1f-9b9d-a3f72af81ba6.png)
![Capture d’écran 2022-05-10 à 11 29 56](https://user-images.githubusercontent.com/16362659/167597154-4f61efda-c4b2-452d-8d34-939c4650aee8.png)

**Comment by isaaccs** [comment]
> Hello, can you try this DDF
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TZ3000_n2egfsli",
>   "modelid": "TS0203",
>   "vendor": "Tuya",
>   "product": "Smart Zigbee Door Window Contact",
>   "sleeper": true,
>   "status": "Silver",
>   "subdevices": [
>     {
>       "type": "$TYPE_OPEN_CLOSE_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0500"
>       ],
>       "fingerprint": {
>         "profile": "0x0104",
>         "device": "0x0402",
>         "endpoint": "0x01",
>         "in": [
>           "0x0000",
>           "0x0001",
>           "0x0500"
>         ]
>       },
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/checkin"
>         },
>         {
>           "name": "config/enrolled",
>           "public": false
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/pending"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "config/battery",
>           "awake": true,
>           "parse": {
>             "at": "0x0021",
>             "cl": "0x0001",
>             "ep": 1,
>             "eval": "Item.val = Attr.val / 2"
>           }
>         },
>         {
>           "name": "state/lastupdated"
>         },
>         {
>           "name": "state/lowbattery"
>         },
>         {
>           "name": "state/open"
>         }
>       ]
>     }
>   ],
>   "bindings": [
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "dst.ep": 1,
>       "cl": "0x0001",
>       "report": [
>         {
>           "at": "0x0021",
>           "dt": "0x20",
>           "min": 60,
>           "max": 3600,
>           "change": "0x00000001"
>         }
>       ]
>     },
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "dst.ep": 1,
>       "cl": "0x0500"
>     }
>   ]
> }
> ```

seems it not works :/

**Comment by majorsl** [comment]
https://github.com/deconz-community/deconz-docker

Go down to the command line example section. You should be mapping /opt/deCONZ to a directory on your host. When you do, you should find devices as one of the directories. It should also be the only directory you need to map.

**Comment by Mimiix** [comment]
> > Hello, can you try this DDF
> > ```
> > {
> >   "schema": "devcap1.schema.json",
> >   "manufacturername": "_TZ3000_n2egfsli",
> >   "modelid": "TS0203",
> >   "vendor": "Tuya",
> >   "product": "Smart Zigbee Door Window Contact",
> >   "sleeper": true,
> >   "status": "Silver",
> >   "subdevices": [
> >     {
> >       "type": "$TYPE_OPEN_CLOSE_SENSOR",
> >       "restapi": "/sensors",
> >       "uuid": [
> >         "$address.ext",
> >         "0x01",
> >         "0x0500"
> >       ],
> >       "fingerprint": {
> >         "profile": "0x0104",
> >         "device": "0x0402",
> >         "endpoint": "0x01",
> >         "in": [
> >           "0x0000",
> >           "0x0001",
> >           "0x0500"
> >         ]
> >       },
> >       "items": [
> >         {
> >           "name": "attr/id"
> >         },
> >         {
> >           "name": "attr/lastannounced"
> >         },
> >         {
> >           "name": "attr/lastseen"
> >         },
> >         {
> >           "name": "attr/manufacturername"
> >         },
> >         {
> >           "name": "attr/modelid"
> >         },
> >         {
> >           "name": "attr/name"
> >         },
> >         {
> >           "name": "attr/swversion"
> >         },
> >         {
> >           "name": "attr/type"
> >         },
> >         {
> >           "name": "attr/uniqueid"
> >         },
> >         {
> >           "name": "config/checkin"
> >         },
> >         {
> >           "name": "config/enrolled",
> >           "public": false
> >         },
> >         {
> >           "name": "config/on"
> >         },
> >         {
> >           "name": "config/pending"
> >         },
> >         {
> >           "name": "config/reachable"
> >         },
> >         {
> >           "name": "config/battery",
> >           "awake": true,
> >           "parse": {
> >             "at": "0x0021",
> >             "cl": "0x0001",
> >             "ep": 1,
> >             "eval": "Item.val = Attr.val / 2"
> >           }
> >         },
> >         {
> >           "name": "state/lastupdated"
> >         },
> >         {
> >           "name": "state/lowbattery"
> >         },
> >         {
> >           "name": "state/open"
> >         }
> >       ]
> >     }
> >   ],
> >   "bindings": [
> >     {
> >       "bind": "unicast",
> >       "src.ep": 1,
> >       "dst.ep": 1,
> >       "cl": "0x0001",
> >       "report": [
> >         {
> >           "at": "0x0021",
> >           "dt": "0x20",
> >           "min": 60,
> >           "max": 3600,
> >           "change": "0x00000001"
> >         }
> >       ]
> >     },
> >     {
> >       "bind": "unicast",
> >       "src.ep": 1,
> >       "dst.ep": 1,
> >       "cl": "0x0500"
> >     }
> >   ]
> > }
> > ```
> 
> seems it not works :/

Did you enable Silver ?

**Comment by Mimiix** [comment]
I just wrote a little guide:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-change-DDF-modes-and-enable-or-disable-DDF-levels

**Comment by isaaccs** [comment]
control is not available in my panel

**Comment by Mimiix** [comment]
What deCONZ version are you on?

**Comment by isaaccs** [comment]
2.05.77

**Comment by Smanar** [comment]
lol, ha yes 2.05, I think you are the user with the older version I have see ^^.

And yes, you need to enable silver, or edit the DDF and put "Gold" as status. "Gold" DDF are always used.

**Comment by isaaccs** [comment]
thanks it works !!
