### ISSUE TITLE
Aqara temperature sensor (v2.15.3)

### ISSUE THREAD

**Issue by Arjan-21** [dresden-elektronik/deconz-rest-plugin#6017]
**## Describe the bug**

I work with deconz in Home Assistant. Just updated to [v2.15.3] and after the update my temperature is 0 °C. 

**## Steps to reproduce the behavior**

Update to 2.15.3 and after that the first update of temperature its off.

**## Expected behavior**

Hopefully to get the right temperature

**## Screenshots**
In the first picture you see (Sensor Temp KK) the right temperature, but when I click the button I see 0 °C
<img width="979" alt="Schermafbeelding 2022-05-04 om 16 13 23" src="https://user-images.githubusercontent.com/75159756/166708207-64791fa9-3313-4d04-ad7e-97fe6c1fc502.png">

<img width="986" alt="Schermafbeelding 2022-05-04 om 16 13 50" src="https://user-images.githubusercontent.com/75159756/166708227-d245affa-f4c7-4e90-8355-13a204b3424d.png">

**## Environment**

Version:  2.15.03 / 21-4-2022
Firmware:   26700700

 - Host system: Raspberry Pi 4
 - Running method: Home assistant with deconz add-on
 - Firmware version: 26720700
 - deCONZ version: 2.15.03 / 21-4-2022
 - Device: ConBee II
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? Yes, SSD disk

**Comment by LeoeLeoeL** [comment]
Which was your previous version of firmware?

**Comment by beaulebens** [comment]
I'm seeing something similar, [reported over here](https://github.com/home-assistant/addons/issues/2476) originally with additional details. In my case, temperature is dropping to -148F, which happens to be -100C (maybe some kind of hardcoded lower bound?). It's not affecting all sensors -- as far as I can tell only 2 of about 8 in my network.

**Comment by Mimiix** [comment]
Closing this issue as it's a duplicatie of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5974
