### ISSUE TITLE
Nous Smart Zigbee Socket A1Z

### ISSUE THREAD

**Issue by TheNice4GH** [dresden-elektronik/deconz-rest-plugin#6018]
## Device

- Product name: Smart Zigbee Socket
- Manufacturer: _TZ3000_ksw8qtmt
- Model identifier: Adapter plug
- Device type : Please remove all unrelated device types. 
  - Sensor
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/104937862/166817236-be1d50b4-2b11-4eba-b602-2490eebb62b0.png)

### Basic
![image](https://user-images.githubusercontent.com/104937862/166818885-1549bb9d-b80a-4f63-92bc-9a159e201227.png)

### On/Off
![image](https://user-images.githubusercontent.com/104937862/166820520-a550ff24-e581-4683-b87b-91fdd8741c87.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/104937862/166821295-f66f8949-022f-4337-8d4f-9bf45c464118.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/104937862/166821413-887f9db8-9a07-4427-8d94-4a05c9d34640.png)

**Comment by Mimiix** [comment]
Closing as it's a duplicatie of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6018

**Comment by TheNice4GH** [comment]
Sorry my bad... I thought I searched correctly

**Comment by Mimiix** [comment]
No worries :) I saw you have it working already so that's an amazing outcome! pro tip: search for the manufacturer name in the git next time
