### ISSUE TITLE
MOES Smart Brightness Thermometer

### ISSUE THREAD

**Issue by TheRealElgardo** [dresden-elektronik/deconz-rest-plugin#6032]
## Device

- Product name: Smart Brightness Thermometer
- Manufacturer: _TYZB01 ftdkanlj
- Model identifier: TS0222
- Device type : Please remove all unrelated device types. 
   - Sensor
    - Other: Sensor for Light, Humidity, Temperature

### Basic
![image](https://user-images.githubusercontent.com/105162161/167303167-c82efc15-6efb-4785-9469-d56c0c9f6c8b.png)

### Identify
![image](https://user-images.githubusercontent.com/105162161/167303217-3f9f5889-a2bd-45dc-96bf-93d43e02d72d.png)
![image](https://user-images.githubusercontent.com/105162161/167303307-309c1bb4-8127-4d56-bd65-abfd6615f136.png)
![image](https://user-images.githubusercontent.com/105162161/167303249-4d796083-79a4-42fa-843d-58239a5fa7c9.png)
### Simple Metering
![image](https://user-images.githubusercontent.com/105162161/167303332-65d861b6-2c9d-441b-9a98-911beffb1b72.png)
![image](https://user-images.githubusercontent.com/105162161/167303346-8bf57edd-bffd-4a23-8d92-2545fe01fde6.png)
![image](https://user-images.githubusercontent.com/105162161/167303355-49a017c8-6e3a-4a94-9591-8ffe369ce344.png)

**Comment by Mimiix** [comment]
Can you make sure the basic cluster is read?

**Comment by Smanar** [comment]
In fact need to press the "read" button for all cluser ^^
The more important for me it s the power configuration Cluster, the device is probably sleeping and you need to wake it in same time.

Another question is why 2 cluster for illuminance measurement ? all are used ?

Else this device realy look classic, can you at least start a DDF to have a squeletton ?

**Comment by TheRealElgardo** [comment]
The conbee is connected.
I pressed the button several times. There were no changes in either the power or the basic cluster compared to the hardcopy above.
Do you have a link to a description for executing a DDF?
