### ISSUE TITLE
SML001 Lux=0 in API broken since v2.15.3

### ISSUE THREAD

**Issue by Markkuuss** [dresden-elektronik/deconz-rest-plugin#6041]
## Describe the bug
Since the update from v2.14.1 to v2.15.3, the lux value of the "1 Gen Hue motion sensor (SML001)" no longer works in complete darkness.

All lux values >0 work.

When it is completely dark, the web interface displays correctly with lux=0, but in the API the lux value remains at the previous value; only the lightlevel value is displayed correctly with 0.

## Steps to reproduce the behavior
Detect movement in absolute dark room with SML001 and check lux value in API.

## Expected behavior
`lux=0`

## Screenshots
![image](https://user-images.githubusercontent.com/10926460/167709077-455c69fd-0afa-410f-b784-3df63ab36241.png)

## Environment
![image](https://user-images.githubusercontent.com/10926460/167894977-85f98a5f-39b6-42a0-8d06-e468c80058fe.png)

 - Host system: Raspberry Pi
 - Running method: Raspbian
  - Device: RaspBee I

**Comment by ebaauw** [comment]
The sensor only reports `lightlevel`; `lux` is computed from that.  Likely a division by 0 in the DDF?

**Comment by Markkuuss** [comment]
I think I have found the problem. `lux` is only set when `lightlevel` is greater than 0:

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/46ccf39a17723bdc7db950e6df1e3a6280565cbb/devices/philips/sml_light_level.js#L7-L10

When it is completely dark, `lightlevel = 0`, but `lux` is no longer set.
