### ISSUE TITLE
Change web route?

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#605]
Hi, I'm trying to proxy my deconz to make it accessible as a sub-route of my "home domain".

Would it be possible to allow the web app to be served from a sub route? For instance `localhost:8080/deconz` instead of `localhost:8080/`

**Comment by manup** [comment]
No easy way, you may copy or symlink the webapp to another directory and use the commandline parameter `--http-root=<absolute path>`.

The default points to */usr/share/deCONZ/webapp*.

**Comment by FezVrasta** [comment]
I see, thanks for the answer!
