### ISSUE TITLE
Royal Gardineer - ZX-7155-675 - Bewässerungsventil

### ISSUE THREAD

**Issue by adx-git** [dresden-elektronik/deconz-rest-plugin#6058]
## Device

- Product name: ZigBee Bewässerungsventil (ZX-7155-675)
- Manufacturer: _TZE200_2wg5qrjy
- Model identifier: TS0601
- Device type : 
  - Switch
  - Other: sprinkler valve

## Screenshots

![image](https://user-images.githubusercontent.com/42860828/168552341-63d6ae64-9c35-4175-a1b8-3657dd2f16aa.png)

![image](https://user-images.githubusercontent.com/42860828/168550555-c3c97be5-7f50-41e6-bc26-75ba753542c3.png)

### Basic
![image](https://user-images.githubusercontent.com/42860828/168550244-3f43c511-9349-4b07-96fa-5bc49285ce66.png)
![image](https://user-images.githubusercontent.com/42860828/168551257-a9a36386-ef46-41d9-8d6a-86cb4a61fae6.png)

The other clusters, even after reading, do not contain any data and just zero values.

### Groups
![image](https://user-images.githubusercontent.com/42860828/168553179-7ce1f5fc-2fc6-4892-b073-1eafc7a4d01b.png)
![image](https://user-images.githubusercontent.com/42860828/168553329-ff9d4343-14a6-475f-8e54-e82ad2a74bca.png)
![image](https://user-images.githubusercontent.com/42860828/168553373-a299057d-8ae7-4ab6-b855-b2bac3d89bfe.png)

### Scenes
![image](https://user-images.githubusercontent.com/42860828/168553502-a776a0e5-af09-4188-b137-9b1eb6186b78.png)
![image](https://user-images.githubusercontent.com/42860828/168553606-8e925e28-03e9-4484-b009-f7c38c13238b.png)
![image](https://user-images.githubusercontent.com/42860828/168553685-ec3c6c99-a1fe-4922-85cf-0961d72a976d.png)
![image](https://user-images.githubusercontent.com/42860828/168553779-64fe4598-c8f3-4163-aeb5-9f4745261f24.png)
![image](https://user-images.githubusercontent.com/42860828/168553818-8a7be0e9-d6a8-4c7b-834e-8ac1fe86f8ac.png)

### Tuya specific
![image](https://user-images.githubusercontent.com/42860828/168553952-4ce69c14-8b19-430d-b569-5d842da58994.png)

### OTAU
![image](https://user-images.githubusercontent.com/42860828/168554074-4792b85b-fd64-4313-852b-cb12fb622e7f.png)
![image](https://user-images.githubusercontent.com/42860828/168554135-75f28e27-970f-4f5d-a5fd-168fa2f9706f.png)

### Time
![image](https://user-images.githubusercontent.com/42860828/168554190-00afebb1-f42e-46fc-aa77-2f30a6991f52.png)

**Comment by Mimiix** [comment]
Hi, Please add all screens, even if they have zero's or other data.

**Comment by Smanar** [comment]
Hello can you try this DDF, If I m right it will enable the on/off

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_9cxuhakf",
  "modelid": "TS0601",
  "vendor": "Mercator",
  "product": "Mercator SSWM-DIMZ",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none",
          "public": false
        },
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 1, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "tuya"},
          "refresh.interval": 300
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

I m using the command 0x01 0x01, If I m wrong, can you check log (help/debug view with "info" and "info_l2), use the device manualy to check in log the good request ?

**Comment by adx-git** [comment]
Hi @Smanar, thanks a lot, it is working, I can open  and close the the valve.

Though, I am not sure about the manufacturername, my readings are saying that it should be "_TZE200_2wg5qrjy", from the json it is "_TZE200_9cxuhakf", which one is the correct one, or does it matter at all?

**Comment by Smanar** [comment]
It realy matter, it s like that deconz reconise the device ....
The _TZE200_9cxuhakf is a dimmer, have make mistake with DDF ^^. I have updated the DDF, but you are sure the value in deconz is _TZE200_2wg5qrjy ?
It mean if we use a bad manufacture name, deconz still can choose a bad DDF and change the manufacture name in the device json ?

**Comment by adx-git** [comment]
> It realy matter, it s like that deconz reconise the device .... The _TZE200_9cxuhakf is a dimmer, have make mistake with DDF ^^. I have updated the DDF, but you are sure the value in deconz is _TZE200_2wg5qrjy ?

Yea, I am sure about "_TZE200_2wg5qrjy", at least it is working after I used this as manufacturer name 

 > It mean if we use a bad manufacture name, deconz still can choose a bad DDF and change the manufacture name in the device json ?
I changed the DDF content before loading it into deconz, I haven't tried to change the manufacturer name after loading the file.

**Comment by Smanar** [comment]
>I changed the DDF content before loading it into deconz, I haven't tried to change the manufacturer name after loading the file.

Ha ok, so it s fine, was my fault, I think if you hadn't changed the DDF it will have not worked.

**Comment by adx-git** [comment]
In which version was the supported added?

**Comment by Smanar** [comment]
The DDF is not in code, no one have made the PR
So you just need a version that support DDF and add the previous DDF

**Comment by ANierbeck** [comment]
Hope that pull-request helps :)

**Comment by vwegert** [comment]
The DDF that is currently shipped (https://deconz-community.github.io/ddf-tools/#/store/bundle/01604e0f83e273149071c0b5c771c0a8f70fd5328e56d954de1d5034b8733448) does not appear to expose the battery state information - which really would come in handy for a device like this. Would it be possible to add the "usual" battery_level and battery_low channels?

**Comment by Smanar** [comment]
Hello, if you can try this DDF 

```
{
  "schema": "devcap1.schema.json",
  "uuid": "1d0e1b23-c414-4ad4-bb8a-1736cb9f977e",
  "manufacturername": ["_TZE200_2wg5qrjy", "_TZE200_akjefhj5", "_TZE200_81isopgh"]
  "modelid": ["TS0601", "TS0601", "TS0601"]
  "vendor": "Royal Gardineer",
  "product": "Water valve (ZX-7155-675)",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none",
          "public": false
        },
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 1, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/battery",
          "parse": {"fn": "tuya", "dpid": 7, "eval": "Item.val = Attr.val;"},
          "read": {"fn": "none"}
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

Have (try to) added the battery level, 2 clones and removed a 300s forced poll, so it can have break something.

To add again the poll

```
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 1, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "tuya"},
          "refresh.interval": 300
        },
```
