### ISSUE TITLE
Support for EJLINK EK02 Wireless Switches

### ISSUE THREAD

**Issue by isamaru** [dresden-elektronik/deconz-rest-plugin#6067]
## Device
(3 devices)
- Product name: EK02 (86/1CH, 86/2CH, 86/3CH) Zigbee Push Button Remote Panel White
- Manufacturer: _TZ3000_tk3s5tyg, _TZ3000_adkvzooy, _TZ3000_qzjcsmar
- Model identifier: TS0041, TS0042, TS0043
- Device type:
  - Switch

## Screenshots
Endpoints and clusters:
![image](https://user-images.githubusercontent.com/1941357/169689745-e8087d11-a2d4-4a04-b464-db8d327069e4.png)

1-gang:
![image](https://user-images.githubusercontent.com/1941357/169689379-559e5239-9d61-450d-b178-d9172eb64d9e.png)

2-gang:
![image](https://user-images.githubusercontent.com/1941357/169689396-7c00c057-5427-4162-95ee-b9328d558c45.png)

3-gang:
![image](https://user-images.githubusercontent.com/1941357/169690087-cc0456db-d6b8-45e0-a031-07179f39389f.png)

### Basic
Read cluster does not work very well, it's only available after pairing. Later it returns blank values.
1-gang:
![image](https://user-images.githubusercontent.com/1941357/169690138-f5767cd3-5a7c-478d-818a-7d8e63281272.png)

2-gang:
![image](https://user-images.githubusercontent.com/1941357/169690151-765ceb58-e4a5-4813-a99a-f6a6a875388b.png)

3-gang:
![image](https://user-images.githubusercontent.com/1941357/169689766-8971164e-f651-453d-bee8-026628593270.png)

### Power Configuration
Same for all 3 devices, only empty data is being returned:
![image](https://user-images.githubusercontent.com/1941357/169689893-c482b314-b368-45f6-a52f-dc958d6e6c3b.png)

### Groups
Strange that the group cluster sometimes appears and sometimes not after pairing, even for same device.

### On/Off
Same for all on/off clusters:
![image](https://user-images.githubusercontent.com/1941357/169689982-408d8005-5c71-44cd-bc92-68996dcf06ba.png)

## Description
![zigbee_switches](https://user-images.githubusercontent.com/1941357/169691274-4323bfaf-5c13-47a8-9f19-8d84e9781d01.JPG)

A family of wireless switches from EJLINK, 1-gang, 2-gang, and 3-gang. They are all based on the same board (YC-ZS-L04C V1.0)

They can be paired to gateway but work very poorly, especially in the Phoscon app:
- read cluster works strange, I am not getting any useful information from that after pairing
- 1-gang switch does not send button events at all, and can't be linked as a switch in the Phoscon app
- 2-gang and 3-gang switches are somewhat usable: they do send button events (1002, 1003, 1004, 2002, 2003, 2004 for both, plus 3002, 3003, 3004 for the 3-gang), but only the single-press can be associated with light groups in the phoscon app. 
- the switches sometimes "fall asleep", then after pressing a button rejoin the network in a couple of seconds, only after that they send events again
- they drain battery very fast (couple of days). I found this was also reported with a CC2531 gateway, but does not manifest with a Tuya gateway. The seller recommends disabling reporting of battery status to address this problem. 
- 1-gang and 2-gang show up in the phoscon app as lights:

![image](https://user-images.githubusercontent.com/1941357/169690963-9c2d48f0-e723-453f-8a92-b29c300e91ba.png)

**Comment by Mimiix** [comment]
Normally  we ask users to create a device request per device as they might differ. 

@Smanar can you tell that these devices are different from each other or are they the same?

@isamaru If they are different, I'm going to ask you to create a device request per device.

**Comment by Smanar** [comment]
Only _TZ3000_adkvzooy and _TZ3000_qzjcsmar are supported by code ATM (without DDF).
Need to use DDF for the 1 gang

And they create useless "light" entries.
Need to use DDF to prevent that, but last time I have tried was some versions ago, and not working.

Need to use too DDF to set the reporting.

So to resume, choose a device and I can give you a DDF to test, for for information there is so much issue for battery switches on DDF.

**Comment by Mimiix** [comment]
@Smanar so it would be better to have 3 separate issues?

**Comment by Smanar** [comment]
Can make all on same PR.
In the better situation will have 3 new DDF and a change on the button json file for all 3.

Only the tuya scene button is special, all other are same.

**Comment by Mimiix** [comment]
@Smanar I want to know what's best for the process, not what's possible 😅

**Comment by Smanar** [comment]
lol, for me it s same.
All will works or none of them, so can group them in the issue.

**Comment by isamaru** [comment]
Hi, do you need any more information from me?

Update about the switches: the 3-gang burned through 2 additional batteries in the last 2 weeks, but is working OK while the battery is fresh, I can toggle lights with all 3 buttons. Other than battery drain, the remaining problems are that I can't bind any events other than single-push in the phoscon UI, and that the I see it incorrectly as lights (minor).
The 2-gang doesn't suffer from battery drain so far, otherwise has same minor issues.
The 1-gang doesn't work at all.

**Comment by Smanar** [comment]
You have a sample here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6068

For exemple for the 1 Gang, use this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_tk3s5tyg",
  "modelid": "TS0041",
  "vendor": "EJLINK",
  "product": "EK02 86",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0x0006"
    }
  ]
}
```

But you need too edit the button_maps.json file, to add the device. like on the sample.

**Comment by isamaru** [comment]
I tried to find a way to test this, but could not find any process for deploying my own build as an HA addon.
@Mimiix said on discord that it was not possible as far as he knows.

**Comment by Smanar** [comment]
This link can't help you ? https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839/2

**Comment by isamaru** [comment]
I managed to upload the files (the new DDF + button_maps.json update) inside the docker, then restarted the container from the host system (`docker restard [id]`), but it doesn't seem to be enough - removing and pairing the switch looks exactly the same = no button events.
Not sure if the file changes are picked up properly, is there a way to check?

**Comment by Smanar** [comment]
Yes on deconz logs.
On deconz/help/debug view with "info" and "info_l2"

Or can just check the file to see if the changes are still here.

**Comment by isamaru** [comment]
It works weird. The DDF is there, and it's picked up:
![image](https://user-images.githubusercontent.com/1941357/173258007-320cc56f-a8e4-4be8-af76-d732fb820aa9.png)

But no matter what I do, there is still the light subdevice and it doesn't work. When I push the button and the device wakes I can see this:
![image](https://user-images.githubusercontent.com/1941357/173258063-fae66b69-a9b9-4880-a885-5732ecacdeea.png)

BUT when I retried this for the first time today, it was working fine for a while, registering events. But never managed to repeat that.

**Comment by Smanar** [comment]
Ok so same issue than here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5889

You need to have ONLY the sensor entry, and I don't understand why you have too the "light" entry, this issue was corrected 2/3 version ago ....

You have correclty deleted the previous entry before making again a new inclusion ?

If I m right you will see the device in "light" and "sensor" ATM.

**Comment by isamaru** [comment]
I'm on addon version 6.14.1 (using deconz 2.16.1)
I watched this [video](https://www.youtube.com/watch?v=rgTQpOVg8w0) and it's not behaving like that for me. Even though the log says that the ddf has been found for this device, I'm still stuck with incorrect vendor on the subdevice, unlike in the video:
![image](https://user-images.githubusercontent.com/1941357/173665495-242dd40e-1ba9-491a-9f19-6fc6fa411847.png)

Yes, I still see both light and sensor in the phoscon app, and with the REST API as well. Here's the current REST API response for the light (at `http://homeassistant.local:40850/api/{{API_KEY}}/lights/27`):
`{
    "etag": "3249c39c18b227609daf043625ddb0c5",
    "hascolor": false,
    "lastannounced": "2022-06-14T18:38:22Z",
    "lastseen": "2022-06-14T18:39Z",
    "manufacturername": "_TZ3000_tk3s5tyg",
    "modelid": "TS0041",
    "name": "On/Off light 27",
    "state": {
        "alert": "none",
        "on": false,
        "reachable": false
    },
    "swversion": null,
    "type": "On/Off light",
    "uniqueid": "0c:43:14:ff:fe:31:48:71-01"
}`


It is possible that I did not delete the old entries correctly, but not sure how I can do that. I do not think so, though, because the light subdevice (which should not be there) gets a fresh light ID each time it is deleted and paired again (checked via rest API), and so does the sensor.

**Comment by Smanar** [comment]
>I'm still stuck with incorrect vendor

It's fine, Phoscon say "Vendor" but it's the manufacture name, so we are fine.

But we are fine for the "vendor", as this device is a battery one, you need to don't have a light entry, so if you have this one, there is a problem.

```
{
  "etag": "3249c39c18b227609daf043625ddb0c5",
  "hascolor": false,
  "lastannounced": "2022-06-14T18:38:22Z",
  "lastseen": "2022-06-14T18:39Z",
  "manufacturername": "_TZ3000_tk3s5tyg",
  "modelid": "TS0041",
  "name": "On/Off light 27",
  "state": {
    "alert": "none",
    "on": false,
    "reachable": false
  },
  "swversion": null,
  "type": "On/Off light",
  "uniqueid": "0c:43:14:ff:fe:31:48:71-01"
}
```

You need to have only the sensor entry, we had previosuly issue with that, but they was corrected by this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6021 and you have it in the deconz version 2.16.1

And It work for some users, so I can't be sure where the issue is from.
I will ask for Manup take a look, but just to be sure you have deleted the device entry before ? (Just to be sure the "light" entry was already here before the inclusion)

**Comment by isamaru** [comment]
I've been deleting and re-pairing the switch for some time now. Most of the time it doesn't work at all and ddf isn't registered. But I've had some random successes (2 times out of maybe 50) where after the pairing the device was sending button press events correctly. No idea what was different about those 2 pairings, but they were both associated to a hot reload.

As for deleting, there are 3 ways to delete it, I've been alternating them but couldn't find any way in which they differ: delete light in phoscon, delete switch in phoscon, delete node in deconz. All 3 appear to have the same result: light, switch, and node all disappear.

**Comment by Smanar** [comment]
>All 3 appear to have the same result: light, switch, and node all disappear

Yeah, some version ago you can can delete a specific entry, but no more possible.

>No idea what was different about those 2 pairings

I think on thoses one, you don't have the "light" entry created.

But from that @manup say to me, it can be random, can be provoked because the device "start to present itlsef", before the DDF engine bypass the legacy code.
He will check if it's possible to put some securities in the code to prevent that.
But as it will need c++ code modification, it will take more time.
