### ISSUE TITLE
Cannot find "Open network" in phoscon

### ISSUE THREAD

**Issue by jonatanolofsson** [dresden-elektronik/deconz-rest-plugin#607]
Having just had a power loss, all lights in the house are now disconnected for some reaseon. Fine. In the old app (and in pure zigbee) this meant opening the network and walking aroung the house, resetting all connections. In phoscon however, I have been unable to find such a button, as the lower level zigbee controls seem to be missing.

**Comment by manup** [comment]
In the Phoscon App you can use the *Group > Edit > Manage Lights > Add new lights* for that purpose. It will open the network (permit join in ZigBee language) in the background.

**Comment by jonatanolofsson** [comment]
Thank you @manup . Is the detection of new and/or previously connected switches dependent on running the respective setup procedure, or is a permit join (e.g. via "Add new lights") sufficient? I have a multitude of devices, and I would rather not be adding them one by one in the case (which I just went through) that all of them gets disconnected.. It seems to me all previously known devices were able to connect alright by just opening the network and retriggering joining for each device.

Perhaps I should open a new question for this, but I'm looking through the API documentation for permit join/networkopenduration and it is somewhat incomplete I think. From what I gather, the permitjoin PUT command takes a range of 0-255 seconds which it will open, but when will it use the setting in networkopenduration?
