### ISSUE TITLE
Door sensor history

### ISSUE THREAD

**Issue by ooii** [dresden-elektronik/deconz-rest-plugin#608]
Hi,

I just figured out that Eve has a history of my door/window sensors. But some data are missing.
I'm using `homebridge-hue` but did not specify anything specific for that purpose in my `config` file.
Where this data is coming from and how can I disable it if needed? 
Thanks.

**Comment by ooii** [comment]
>> There’s no option to disable only the history

Nothing like `hueMotionTemperatureHistory` for door/window sensor. That's right?

**Comment by ebaauw** [comment]
Right.  The setting for Hue motion sensor temperature history is there, because homebridge-hue needs to create an additional HomeKit accessory for each sensor, when providing history for both motion and temperature.

**Comment by ooii** [comment]
OK, thanks @ebaauw.

**Comment by ooii** [comment]
Yes, running v0.9.3. Restarted my iPhone yesterday (for other reasons).
I'll test again later this evening.
Thanks.

**Comment by ooii** [comment]
You were right, restarting few things fixed the issue. Thanks.
