### ISSUE TITLE
Remote TUYA

### ISSUE THREAD

**Issue by sebsteph51** [dresden-elektronik/deconz-rest-plugin#6080]
## Device

- Product name: Remote TUYA.
- Manufacturer: _TZ3000_ygvf9xzp
- Model identifier: TS0044
- Device type : Please remove all unrelated device types. 
   - Switch
 

## Screenshots
![IMG_20220527_065648](https://user-images.githubusercontent.com/106368004/170639507-13b5d77f-c3a7-4d34-bf17-81f4de4dd502.jpg)
![IMG_20220527_065658](https://user-images.githubusercontent.com/106368004/170639529-6a6b4543-123b-4b35-ae01-70d89adeacb4.jpg)
![IMG_20220527_074348](https://user-images.githubusercontent.com/106368004/170639531-e09cedcd-9565-4c3a-aef2-6213477b43a5.jpg)
![IMG_20220527_074436](https://user-images.githubusercontent.com/106368004/170639534-a3dc4077-ba34-49ff-8e54-489f1ea99fc3.jpg)

**Comment by Mimiix** [comment]
Missing screenshots of all clusters.

**Comment by sebsteph51** [comment]
![01 - 0000 -  Basic](https://user-images.githubusercontent.com/106368004/170651213-e59c240d-3b94-4558-9a3e-cc1e03a3f1f1.jpg)
![01 - 000A - Time](https://user-images.githubusercontent.com/106368004/170651226-cb656e5b-c8b9-46a3-8b1c-99c90390afe2.jpg)
![01 - 0001 - Power Configuration](https://user-images.githubusercontent.com/106368004/170651228-0d4b361c-21c4-4b73-a21f-5888ef72a9a9.jpg)
![01 - 0006 - ON OFF (2)](https://user-images.githubusercontent.com/106368004/170651234-799b57f0-5336-481f-b505-bcc45e80a23c.jpg)
![01 - 0006 - ON OFF](https://user-images.githubusercontent.com/106368004/170651237-543078c0-e942-49c0-8b41-93551e30109a.jpg)
![01 - 0019 - OTAU](https://user-images.githubusercontent.com/106368004/170651242-5c20eb89-a2c9-4e27-8f02-dd359e8a5e41.jpg)
![01 - E000 - Unknown](https://user-images.githubusercontent.com/106368004/170651247-e54068f3-2abb-4ccb-b16a-d6725902a248.jpg)
![02 - 0001 - Power Configuration](https://user-images.githubusercontent.com/106368004/170651253-504ec6e3-6b0e-4f3f-b27f-4113736831a1.jpg)
![02 - 0006 - ON OFF (2)](https://user-images.githubusercontent.com/106368004/170651256-f992dd48-0b43-4368-8393-4e0993036c52.jpg)
![02 - 0006 - ON OFF](https://user-images.githubusercontent.com/106368004/170651266-3eb1b363-fa24-4bd5-84c1-c3d98c3d185e.jpg)
![03 - 0001 - Power Configuration](https://user-images.githubusercontent.com/106368004/170651282-d9074b0c-a40f-49b4-8828-33105bf437a7.jpg)
![03 - 0006 - ON OFF (2)](https://user-images.githubusercontent.com/106368004/170651293-5a56e0cc-04d3-4127-978c-0835eb0f2159.jpg)
![03 - 0006 - ON OFF](https://user-images.githubusercontent.com/106368004/170651312-d001c533-6400-4bcf-98c0-8aac8dc9b685.jpg)
![04 - 0001 - Power Configuration](https://user-images.githubusercontent.com/106368004/170651347-627a48d5-a6ee-4465-9c0a-3b319eb6431a.jpg)
![04 - 0006 - ON OFF (2)](https://user-images.githubusercontent.com/106368004/170651385-05ce5287-cb7a-4e27-a9aa-d754d725d403.jpg)
![04 - 0006 - ON OFF](https://user-images.githubusercontent.com/106368004/170651396-31163be7-1ca2-4fb8-918d-dd48d0859479.jpg)
![ALL Switch](https://user-images.githubusercontent.com/106368004/170651410-2795d504-0b2f-44a0-803c-6bc2b173c52e.jpg)


Sorry, I have take a picture of all cluster, the name of picture explain the cluster of device.

**Comment by Smanar** [comment]
Lol, you make same screenshoot than my boss at work ^^

Can try this DDF 

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_ygvf9xzp",
  "modelid": "TS0044",
  "product": "Tuya remote 4 gangs",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 4,
      "dst.ep": 1,
      "cl": "0x0006"
    }
  ]
} 
```

And you need too edit the button_maps.json file (in the "devices" folder too)

```
       "Tuya3gangMap": {
            "vendor": "Tuya",
            "doc": "3-gang remote",
            "modelids": ["_TZ3000_t8hzpgnd", "_TZ3000_wkai4ga5", "_TZ3000_bi6lpsew", "_TZ3400_keyjhapk", "_TYZB02_key8kk7r", "_TZ3400_keyjqthh", "_TZ3400_key8kk7r", "_TZ3000_vp6clf9d", "_TYZB02_keyjqthh", "_TZ3000_peszejy7", "_TZ3000_qzjcsmar", "_TZ3000_owgcnkrh", "_TZ3000_adkvzooy", "_TZ3000_arfwfgoa", "_TZ3000_a7ouggvs", "_TZ3000_rrjr1q0u", "_TZ3000_abci1hiu", "_TZ3000_dfgbtub0"],
```

Just add your model in the list "_TZ3000_ygvf9xzp"

You will miss the battery, but it s a test because I m not sure it s possible only with DDF

**Comment by sebsteph51** [comment]
Lol I haven't visual access on my odroid. 

Thanks a lot the remote is pair.

Thanks Thanks Thanks.

**Comment by Smanar** [comment]
Seriously on first try ?
All is working ? Can make a PR ?

**Comment by sebsteph51** [comment]
a simple click it's ok
a double click it's ok
a long click isn't ok
i haven't battery but i don't now if i can obtain it.

**Comment by Smanar** [comment]
You haven't pressed the "read" button on your capture, so I m not sure for battery and have used defaut code

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_ygvf9xzp",
  "modelid": "TS0044",
  "product": "Tuya remote 4 gangs",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl"
          }
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 4,
      "dst.ep": 1,
      "cl": "0x0006"
    }
  ]
}
```


For the long press, can you go in deconz / help / debug view, enable flags "info" and "info_l2" and make a long press.
You probably will see an error message, if you can share it ?

**Comment by sebsteph51** [comment]
I have change json for the battery, but i haven't the battery in domoticz. I have look info and info L2 and action = B4 short or B4 long but in domoticz Bx = simple click, Lx = long click, Dx = double click.


![battery](https://user-images.githubusercontent.com/106368004/170924962-822d66ac-dfd8-4011-80c6-8701a96c7e9c.jpg)
![info](https://user-images.githubusercontent.com/106368004/170924975-881f831e-acd4-4b82-9b42-24941ab1bef6.jpg)
![info L2](https://user-images.githubusercontent.com/106368004/170924978-cf6dfaea-eba0-4ecb-b55c-174a4eaf3eed.jpg)

Thanks a lot for your kelp.

**Comment by Smanar** [comment]
The problem can be from domoticz too (I can make correction too)
Just to be sure, button event from deconz are X00Y with X is the button number and Y the button state (2 = release after short press, 3 = release after long press, 4 release after double press)

Can you check values send by deconz by the websocket ?

You can see them too in domoticz with enabling "debug log only" in the plugin tab.

Still no battery (I m seing 0 value on your previous capture) ?

**Comment by sebsteph51** [comment]
Sorry for this long time but i was in work. I have test with web socket and i have :
	print(str(data["sensors"]["28"]["state"]["buttonevent"]))
3002 for simple click on button 3 and 3004 for double click on bouton 3, 
4002 for simple click on button 4 and 4004 for double click on bouton 4, ...

![image](https://user-images.githubusercontent.com/106368004/172307980-f582bbf8-447e-449a-8168-3bba77768c59.png)

long press is not detect.

**Comment by sebsteph51** [comment]
Sorry, but it's ok for a long press. it was me the problem. The time for a long press is 4 or 5s but i not click long enough. Sorry

**Comment by sebsteph51** [comment]
I has 0 % battery for websocket. I have click on all button for test if the battery is send with info buttton. The battery is stay at 0% for web socket

On Deconz i have click on power configuration, Read cluster and value of battery 0x0020 = 30 and 0x0021 = 200.

![IMG_20220610_063818](https://user-images.githubusercontent.com/106368004/172992259-2ea95763-a2e2-4661-9ce2-cefd8f0bbdbc.jpg)

i have test after manipulation on deconz and i have 100 on websocket

![image](https://user-images.githubusercontent.com/106368004/172991662-5e8efa2d-c622-4783-aa84-073dae40584f.png)

**Comment by Smanar** [comment]
Perhaps a binding issue, but all is almost working.
PR done, thx https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6125

**Comment by Mimiix** [comment]
I'd prefer to keep it open until it's merged.
