### ISSUE TITLE
ZM79E-DT

### ISSUE THREAD

**Issue by vlude** [dresden-elektronik/deconz-rest-plugin#6090]
## Device

- Product name: Zemismart ZM79E-DT
- Manufacturer:  _TZE200_3i3exuay
- Model identifier: TS0601
- Device type : 
  - Curtain

### Basic
![basic cluster](https://user-images.githubusercontent.com/12392970/170888799-535df603-6fb3-409f-b06d-f5e9f73e30f5.png)

### Node info
![node info](https://user-images.githubusercontent.com/12392970/170888794-0ac61f37-23b1-475a-92eb-e244f3907d3e.png)

### Groups
![groups cluster](https://user-images.githubusercontent.com/12392970/170888804-25bc30f3-19cc-44a0-beb7-4c609922d5d7.png)

### Scenes
![scene cluster](https://user-images.githubusercontent.com/12392970/170888807-d8adc3ec-2c36-4ffb-b038-af932d0c9860.png)

**Comment by vlude** [comment]
Hi, is there any update on this one?

**Comment by Mimiix** [comment]
Nope, a Dev needs to pick it up. They do that when they please. Perhaps @Smanar wants to help you out.

**Comment by vlude** [comment]
Ok, no problem at all. But after 7 days of inactivity, this issue will be closed. Is that a problem or can it remain on the radar of the devs (when they have the time)?

**Comment by Mimiix** [comment]
It gets unstaled tonight :)

**Comment by Smanar** [comment]
Bad news for you.
ATM there is a blocked PR to add tuya cluster to be used with DDF for TRV.
I m waiting for this one was validated before making same for covering.

So for the moment not possible adding new tuya covering.

**Comment by vlude** [comment]
Thanks for the information, I will follow that one
