### ISSUE TITLE
IKEA TREDANSEN shutter

### ISSUE THREAD

**Issue by L3nny5** [dresden-elektronik/deconz-rest-plugin#6097]
## Device

Shutter is working in general but i.e. battery info is missing. 

- Product name: IKEA TREDANSEN
- Manufacturer: IKEA of Sweden
- Model identifier: TREDANSEN block-out cellul blind
- Device type :  
  - Other: shutter / blind / jalousie 

## Screenshots

<img width="400" alt="image" src="https://user-images.githubusercontent.com/16922521/171064188-9b995872-00d6-4820-8750-45d0b5b6cb1c.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/16922521/171064077-f5121e3b-f3eb-4ea5-af6a-fa844184eea7.png">

### Basic
<img width="519" alt="image" src="https://user-images.githubusercontent.com/16922521/171063289-3bc29b58-5623-4f91-8542-122465629684.png">

### Power Configuration
<img width="524" alt="image" src="https://user-images.githubusercontent.com/16922521/171064253-4b4e93ff-e94f-433c-b9a5-9dafddf8af09.png">

### Identify
<img width="526" alt="image" src="https://user-images.githubusercontent.com/16922521/171063515-db1a8402-9fbe-4f4d-b6f9-79dab2aebb2c.png">

### Groups
<img width="517" alt="image" src="https://user-images.githubusercontent.com/16922521/171063541-322fac9f-986c-455c-b20e-f9ad920b5e25.png">

### Scenes
<img width="514" alt="image" src="https://user-images.githubusercontent.com/16922521/171063576-ad54f2a1-e2a8-4320-bdbf-296d2dd7f825.png">

### Poll Control
<img width="514" alt="image" src="https://user-images.githubusercontent.com/16922521/171063646-aee28f1f-0f48-4df1-b4f0-9e86cf772bd0.png">

### Window Covering
<img width="512" alt="image" src="https://user-images.githubusercontent.com/16922521/171063823-fd4ceef0-14d2-4eb6-a58d-9927924f4a04.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/16922521/171063844-23027f0f-c14a-418d-a8fc-b6bf723274ed.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/16922521/171063859-6984db93-3246-4aca-897a-148a9ce4d6b5.png">

### IKEA specific
<img width="521" alt="image" src="https://user-images.githubusercontent.com/16922521/171063929-c807a268-ced1-462a-b51e-74f2d72c4253.png">

### OTAU
<img width="518" alt="image" src="https://user-images.githubusercontent.com/16922521/171063961-40eb5bde-b919-4290-8b28-6886dc45f683.png">

**Comment by Mimiix** [comment]
> Any idea how I can get the DDF into deconz which is running as an add on in Home Assistant?

The same as others: There should be an option to edit the JSON and paste it in. You need a VNC client to be able to paste i think.
