### ISSUE TITLE
Paulmann Zigbee Switch 501.34

### ISSUE THREAD

**Issue by carstenph1** [dresden-elektronik/deconz-rest-plugin#6102]
## Device

- Product name:  Zigbee Wandschalter On/Off/Dimm 
- Manufacturer: Paulman LichtGmbH
- Model identifier: 501.34
- Device type : Switch

### Basic

![grafik](https://user-images.githubusercontent.com/106767126/171694637-46412a1d-45f9-4d19-aff2-aa7ceef7e65c.png)

### Power Configuration

![grafik](https://user-images.githubusercontent.com/106767126/171938764-a0aebe07-be9b-49d3-a3dd-3bc4d9f41736.png)

### Identify

![grafik](https://user-images.githubusercontent.com/106767126/171938292-b83752e9-6359-4315-a952-bc0ce2e1a014.png)

### Diagnostics

![grafik](https://user-images.githubusercontent.com/106767126/171938659-cfbbdc61-507a-41de-b5bb-91ecd89caef9.png)

### ZLL Commissioning

![grafik](https://user-images.githubusercontent.com/106767126/171938569-57a7a161-927e-4935-924c-c8d2a93c94d7.png)

### Node Info

![grafik](https://user-images.githubusercontent.com/106767126/171695283-b0617451-acd0-4692-a550-ddb824ea8490.png)

**Comment by Mimiix** [comment]
Missing screenshots.

**Comment by carstenph1** [comment]
I added the complete available information on cluster information.

**Comment by carstenph1** [comment]
@Mimiix are you missing any further details?

**Comment by Mimiix** [comment]
Woops, sorry! Missed your comment. Looks good :)

**Comment by LilYea** [comment]
Is there progress yet?

**Comment by carstenph1** [comment]
it would be awesome to see this feature in one of the next releases :-)

**Comment by carstenph1** [comment]
pushing it again!

**Comment by Artur-Fedjukevits** [comment]
I have the same switch. I would also be very grateful to see this device as supported.

**Comment by carstenph1** [comment]
@Mimiix is it still planned to include this switch compatibility in one of the next releases?

**Comment by Mimiix** [comment]
A dev needs to pick it up. Perhaps @smanar or @SwoopX  wants to help out. Otherwise, we are kinda stuck...

**Comment by Smanar** [comment]
>Product name: Zigbee Wandschalter On/Off/Dimm

So this device don't have color ?

**Comment by carstenph1** [comment]
no. its a switch to turn on/off/dim the light bulbs. there is nothing available to control the color.

**Comment by Smanar** [comment]
So can try with this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Paulman LichtGmbH",
  "modelid": "501.34",
  "product": "Paulmann Zigbee Switch",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0008"
    },
  ]
}
```

With it the device will be reconized but not working.
Just enable deconz log with "info_l2" in the application / help / debug view
Press all buttons and pls share the result, you will error like

```
	Line 4570:         DBG_Printf(DBG_INFO_L2, "[INFO] - No button map for: %s%s, endpoint: 0x%02X, cluster: %s, command: %s, payload: %s, zclSeq: %u\n",
	Line 5607:         DBG_Printf(DBG_INFO_L2, "[INFO] - No button handler for: %s%s, endpoint: 0x%02X, cluster: %s, command: %s, payload: %s, zclSeq: %u\n",
```

We will use them to edit another json file.

**Comment by carstenph1** [comment]
thanks Smanar. 
I hope I made the import correct. I had to remove a comma in the json, otherwise it did not load.
I imported the json in the DDF Editor of Deconz and ran the debug view with info_l2. but I cant see any output of "no button ...". just "APS-DATA.indication from child 0x32E3" every time I clicked the switch buttons.

here you can find the full debug log
https://pastebin.com/Z9ayZkyy

**Comment by Smanar** [comment]
Ha yes, have removed the comma too.

But it s strange there is still nothing. The node have changed from 0xXXXX to a better name ? To check if the device is now in the API.
You have made a "hot reload" (in the editor menu) after having modified the DDF ?

Else can enable log "aps" to see what is this aps request.

**Comment by carstenph1** [comment]
well I was playing around in the Editor and did a hot reload without knowing what it does.
the device ID is still the same like at the beginngin 0x32E3.

enabling the API logs while pressing the switch, dont seem to bring more light in the dark....
https://pastebin.com/ZubC12R1

**Comment by carstenph1** [comment]
mhh you are right, there was a typo in the manufacturername. but nothing changed right now...
https://pastebin.com/nDdZYCUx

**Comment by carstenph1** [comment]
ok. good news, I restarted deconz as the DDF editor still had the manufacterer Description still wrong even after correcting it.
now I see the name "Switch 4" as a DB entry. please have a look

https://pastebin.com/yL7EPR2A

**Comment by Smanar** [comment]
```
18:20:26:992 [INFO] - No button map for: 501.34, broadcast to: 0xE311, endpoint: 0x02, cluster: ONOFF (0x0006), command: OFF (0x00), payload: None, zclSeq: 74
18:20:27:598 [INFO] - No button map for: 501.34, broadcast to: 0xE311, endpoint: 0x02, cluster: ONOFF (0x0006), command: ON (0x01), payload: None, zclSeq: 75
18:22:29:825 [INFO] - No button map for: 501.34, unicast to: 0x0000, endpoint: 0x01, cluster: ONOFF (0x0006), command: OFF (0x00), payload: None, zclSeq: 77
```

So with thoses logs, in the folder "devices" (probably where you have found the DDF) , you can found a file button_maps.json.
Just edit it to add

```
        "PaulmannMap": {
            "vendor": "Paulmann LichtGmbH",
            "doc": "On off remote",
            "modelids": ["501.34"],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", " B1 On"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "B1 Off"],
                [1, "0x02", "ONOFF", "ON", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "B2 On"],
                [1, "0x02", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "B2O ff"]
            ]
        },
```

If you have more logs (with long press for exemple), pls share them too.

**Comment by carstenph1** [comment]
ok I see the switch in the phoscon web gui. but I cant edit the switch or connect it to a group of lights. I added the lines you mentioned in the /usr/share/deCONZ/devices/button_maps.json
is this intended?

I will share more logs (long press for dimm) tomorrow.

**Comment by Smanar** [comment]
>I cant edit the switch

You mean in phoscon ? So I can't do something, I haven't impact on phoscon. But you can use it in third app, every time you use the device you will have a new notification with state/buttonevent.

>connect it to a group of lights

You mean using the old web app ? To use "direct bind" without automation, using groupcast features ? For this I can do something, need to add the config/group to the DDF

>is this intended?

Yep it s the good one, you will, you will have another message in log now, visible with "info" or "info_l2", not an error one.

**Comment by carstenph1** [comment]
Good Morning, 
I have new logs from today using long press button.
https://pastebin.com/kmFNvJtB

do you have any clue why I cant discover the second Paulmann Switch (same model)?

thanks
Carsten

**Comment by Smanar** [comment]
So new button map to try

```
        "PaulmannMap": {
            "vendor": "Paulmann LichtGmbH",
            "doc": "On off remote",
            "modelids": ["501.34"],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", " B1"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "B2"],
                [1, "0x02", "ONOFF", "ON", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "B3"],
                [1, "0x02", "ONOFF", "OFF", "0", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "B4"],
                [1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_5", "S_BUTTON_ACTION_SHORT_RELEASED", "B5"],
                [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_6", "S_BUTTON_ACTION_SHORT_RELEASED", "B6"]
            ]
        },
```

But I have some question.
- On your logs you have a second endpoint, but on your capture you have only the endpoint "01" (it's the number on the node title)
- I don't know how look visualy your device, so I m using B1 > B6, but you can have B6 = B1 long press, if you can correct me ?
- I m not sure you will have all action, only 1 endpoint used, will found the missing by elimination.

**Comment by baaaron** [comment]
Bought the same switch, just now I realized it isn‘t supported yet :( 
Let me know if anything’s still needed to get it supported

**Comment by Smanar** [comment]
Sure can use the same DDF and the button map from the previous post.
Press button and tell me the result.

And BTW if you can confirm me how many endpoint have this device ?

**Comment by carstenph1** [comment]
Hello Smanar,
the switch can control two separate endpoints/devices. each side on/off (short press) or dimm brighter/darker (long press). with your current configuration the button map.json I have 6 buttons visible in phoscon html gui.

is this the information you required?

![grafik](https://user-images.githubusercontent.com/106767126/199598169-5a274cab-f677-455f-b179-3e44fb32850c.png)

**Comment by Smanar** [comment]
>I have 6 buttons visible in phoscon html gui.

This is "phoscon magic" I haven't impact on it ^^

But I think I miss at least 2 buttons return, as only the on/off use the 2 endpoint

```
        "PaulmannMap": {
            "vendor": "Paulmann LichtGmbH",
            "doc": "On off remote",
            "modelids": ["501.34"],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", " B1"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "B2"],
                [1, "0x02", "ONOFF", "ON", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "B3"],
                [1, "0x02", "ONOFF", "OFF", "0", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "B4"],
                [1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_5", "S_BUTTON_ACTION_SHORT_RELEASED", "B5"],
                [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_6", "S_BUTTON_ACTION_SHORT_RELEASED", "B6"]
            ]
        }
```

You can see button return in Phoscon/help/API Information/events, and I think you will miss 2 of them.

**Comment by Millhouse273** [comment]
Hi,
I call this button my own and are very thankful for your great work here. After some problems I got it working and can link the buttons to my lights. There is only one thing missing and I didn't figured out fixing it by working me through the button_maps.json. I tried to adopt the dim function, but haven't enough skills to transfer it to the paulmann button.

Now the missing function: I'd like to dimm down with the off-button. dim up is possible with the posted map and the on buttons. Thanks for any response

**Comment by Millhouse273** [comment]
Is it possible to get a real dim button? Like the Ikea on/off button with long press controlling the level constantly? Like mentioned before I have no idea off programming all the stuff...

**Comment by Smanar** [comment]
Hello, first you are asking with phoscon or third app ?
From that you are saying you are using direct link with remote and light ?

You can make a long press on a button and check logs if the device support this action, with info_l2

```
	Line 4570:         DBG_Printf(DBG_INFO_L2, "[INFO] - No button map for: %s%s, endpoint: 0x%02X, cluster: %s, command: %s, payload: %s, zclSeq: %u\n",
	Line 5607:         DBG_Printf(DBG_INFO_L2, "[INFO] - No button handler for: %s%s, endpoint: 0x%02X, cluster: %s, command: %s, payload: %s, zclSeq: %u\n",
```

**Comment by Millhouse273** [comment]
Hi, thx for your answer.

I'm using the web interface of phoscon. The light is grouped in phoscon an the switch is grouped within this group. I can set an action like on or off to the buttons.
Their is no automation in any other app or phoscon.

I check, if the switch supports long press. In the description is mentioned on/off/dimm...

Thanks a lot for your help so far

**Comment by Smanar** [comment]
Ok so you are not using automation but direct zigbee connexion.

Nothing to programme, the device support it or not ^^. Ha have the good cluster and support group feature

Just try this DDF to enable the group feature on the DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Paulman LichtGmbH",
  "modelid": "501.34",
  "product": "Paulmann Zigbee Switch",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "config/battery"
        },
        {
            "name": "config/group",
            "default": "auto"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
        "bind": "groupcast",
        "src.ep": 1,
        "cl": "0x0006",
        "config.group": 0
    },
    {
        "bind": "groupcast",
        "src.ep": 1,
        "cl": "0x0008",
        "config.group": 0
    }
  ]
}
```

IDK if phoscon will support it natively but the old webapp (in phoscon /help ) will support it.

**Comment by Millhouse273** [comment]
Hi,

this is the log from l2.

{"id":"106","lastannounced":"2022-12-31T14:13:04Z","lastseen":"2023-01-04T19:07Z","manufacturername":"Paulmann LichtGmbH","modelid":"501.34","name":"Switch 106","swversion":"2.7.6_r25","type":"ZHASwitch","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"},"e":"changed","id":"106","r":"sensors","t":"event","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"} (ret = 2125021208)
20:07:36:681 Websocket 192.168.: send message: {"e":"changed","id":"106","r":"sensors","state":{"buttonevent":7002,"lastupdated":"2023-01-04T19:07:36.676"},"t":"event","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"} (ret = 2125021208)
20:07:36:682 Websocket 192.168.: send message: {"e":"changed","id":"106","r":"sensors","state":{"buttonevent":7002,"lastupdated":"2023-01-04T19:07:36.676"},"t":"event","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"} (ret = 2125021208)
20:07:36:686 Websocket 192.168.: send message: {"e":"changed","id":"16","r":"lights","state":{"alert":null,"bri":254,"on":true,"reachable":true},"t":"event","uniqueid":"00:17:88:01:08:a4:01:8d-0b"} (ret = 150)
______________

{"id":"106","lastannounced":"2022-12-31T14:13:04Z","lastseen":"2023-01-04T19:09Z","manufacturername":"Paulmann LichtGmbH","modelid":"501.34","name":"Switch 106","swversion":"2.7.6_r25","type":"ZHASwitch","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"},"e":"changed","id":"106","r":"sensors","t":"event","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"} (ret = 2125021208)
20:09:22:369 Websocket 192.168.: send message: {"attr":{"id":"106","lastannounced":"2022-12-31T14:13:04Z","lastseen":"2023-01-04T19:09Z","manufacturername":"Paulmann LichtGmbH","modelid":"501.34","name":"Switch 106","swversion":"2.7.6_r25","type":"ZHASwitch","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"},"e":"changed","id":"106","r":"sensors","t":"event","uniqueid":"b4:e3:f9:ff:fe:14:0d:a5-01-0006"} (ret = 2125021208)

Long press on the off Button did no log. Don't know why...

**Comment by Smanar** [comment]
`{"buttonevent":7002`

??? The button map go only to button 6 maximum

```
        "PaulmannMap": {
            "vendor": "Paulmann LichtGmbH",
            "doc": "On off remote",
            "modelids": ["501.34"],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", " B1"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "B2"],
                [1, "0x02", "ONOFF", "ON", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "B3"],
                [1, "0x02", "ONOFF", "OFF", "0", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "B4"],
                [1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_5", "S_BUTTON_ACTION_SHORT_RELEASED", "B5"],
                [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_6", "S_BUTTON_ACTION_SHORT_RELEASED", "B6"]
            ]
```

>Long press on the off Button did no log. Don't know why...

Generaly this button don't have long press, its on or off, no utility to use a long press.

But on your side you want to use direct link, so you will not need buttonevent return, just need to check if the device create a "switch group" to be able to put light on it.

**Comment by NurNano** [comment]
Hey, 
thank you for your work. I looked over it with my new Switch and found out, some Keybindings were missing. 
I did some try/error and optimized the button_maps.

Here for you to test:

`"PaulmannMap": {
            "vendor": "Paulmann LichtGmbH",
            "doc": "On off remote",
            "modelids": ["501.34"],
			"buttons": [
              {"S_BUTTON_1": "ON Links"},
              {"S_BUTTON_2": "OFF Links"},
			  {"S_BUTTON_3": "ON Rechts"},
              {"S_BUTTON_4": "OFF Rechts"}
            ],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "ON Links"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "OFF Links"],
                [1, "0x02", "ONOFF", "ON", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "ON Rechts"],
                [1, "0x02", "ONOFF", "OFF", "0", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "OFF Rechts"],
				[1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Dim Up Links"],
		        [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Stop Dim"],
				[1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "1", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Dim Down Links"],
		        [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "1", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Stop Dim"],
				[1, "0x02", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "Dim Up Rechts"],
				[1, "0x02", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "Stop Dim"],
				[1, "0x02", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "1", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "Dim Down Rechts"],
                [1, "0x02", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "1", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "Stop Dim"]
			]
		}`

With this i got all Keys recognized.

**Comment by Smanar** [comment]
>After some testing i got stuck in my openhab and it seems to be needed to add some more Buttons to access all of the Keys in Openhab due to only get the Pressed Button ID delivered.

Ha nice to know, I never use the field "buttons" on my side.

So you have finished the device inclusion ? do you want to make the PR to add it ?

**Comment by NurNano** [comment]
I really don't know how this things work. Just made the ddf working and liked to share the results with the community. If anyone is able to make the PR so i really would like it.

**Comment by Smanar** [comment]
I have made it here  https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7087

If you can confirm all is fine ? (long time we have started this device)

**Comment by Smanar** [comment]
Nice, i's same DDF (except you still have the typo in the manufacture name, you still missing the "n".

I remove the draft state on the PR

**Comment by NurNano** [comment]
Wait a sec....I was going to change the typo and opened the DDF, finding out my DDF looks different.

Here is my DDF. 
Seems like I changed something while testing with my Windows PC and switching to Linux headless.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Paulmann LichtGmbH",
  "modelid": "501.34",
  "product": "501.34",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0008"
    }
  ]
}
```

**Comment by Smanar** [comment]
So there is no big change.
The only one is the "slepper" state, you have changed it to "false", but I m sure at 99% all battery remote are sleeper.

**Comment by AndreasHauber** [comment]
Hello,
I bought some new 501.34 as the old one was working perfectly. The new ones have a different firmware version and are not shown after pairing. Here are my readings:

Basic 
![image](https://github.com/user-attachments/assets/b25c2714-9719-4552-8297-61977c72438e)
Power Configuration
![image](https://github.com/user-attachments/assets/30d30533-83b0-48c8-a775-5a5919d99f1b)
Node Info
![image](https://github.com/user-attachments/assets/3fd7dd63-2df3-4d86-8e10-b546bbff538d)

**Comment by NurNano** [comment]
Seems like they just added a space in the manufacturer filed between the Licht and GmbH.
Can you try to copy the 501_34_battery_switch.json to 501_34_battery_switch_new.json and add the space in the "manufacturername" field?
Then reload the Deconz and try to add it again. It should now be there like the old switches.
If it works the button_maps.json has to be edited too.

**Comment by NurNano** [comment]
@Smanar can u do an other commit and add a second json and change the button_maps.json by just copy and pasting and adding the space?
That would help all future users of the new Buttons :)

**Comment by Smanar** [comment]
Sure https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7952
I haven't modified the buttonmap file as deconz use only the ModelID for it.
