### ISSUE TITLE
AngelEye FireAngel Zigbee Module

### ISSUE THREAD

**Issue by peterjank** [dresden-elektronik/deconz-rest-plugin#6111]
## Device

- Product name: FireAngel Zigbee Module
- Manufacturer: AngelEye
- Model identifier: Zigbee Module P Line
- Device type : Please remove all unrelated device types. 

  - Sensor SmokeAlarm

### Bas
![screendump basic deconz](https://user-images.githubusercontent.com/39620539/172019554-d0885623-bbf0-4070-a3bb-67b32e7da3a6.jpg)
ic

### Diagn
[zigbee_capture.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8843663/zigbee_capture.zip)
ostics
sniffed zigbee traffic with another conbee 2
0x75c4			pan id
0x00212effff0426e7	mac address
0x00212effff0426e7	tc address
0x1136e241492dfa82a1b2120183801456	network key

### Other clusters that are not mentioned above
[phoscon search for smoke sensor FireAngel zigbee module.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/8838364/phoscon.search.for.smoke.sensor.FireAngel.zigbee.module.txt)

the new sensor is not found so it can not be seen in the node screen

**Comment by Mimiix** [comment]
Missing all screenshots.
