### ISSUE TITLE
zigbee smart curtain motor _TZE200_r0jdjrvi TS0601

### ISSUE THREAD

**Issue by danidask** [dresden-elektronik/deconz-rest-plugin#6113]
## Device

- Product name: zigbee smart curtain motor
- Manufacturer: _TZE200_r0jdjrvi
- Model identifier: TS0601
- Device type : 
  - Other: curtain motor

## Screenshots

![imagen](https://user-images.githubusercontent.com/9405129/172058788-9ee73eec-592c-4dd5-9a80-b60622d8c7bf.png)

![imagen](https://user-images.githubusercontent.com/9405129/172059123-148e493a-ad43-4c9b-af4b-18958776f3c9.png)

### Basic

![imagen](https://user-images.githubusercontent.com/9405129/172058301-a85daba3-599f-4f34-b1c4-89151ed8a184.png)

### Identify

![imagen](https://user-images.githubusercontent.com/9405129/172058400-5795fbd2-ee13-4f37-bb4b-5ff1f989132a.png)

### Groups

![imagen](https://user-images.githubusercontent.com/9405129/172062745-4bb90fea-db28-4d52-aee3-8012b8432aec.png)
![imagen](https://user-images.githubusercontent.com/9405129/172062758-26e9ebdf-0a7c-40f7-991f-d7376f526747.png)

### Scenes

![imagen](https://user-images.githubusercontent.com/9405129/172062780-eb1925f6-8c93-4ad2-8aec-b0f4b980315e.png)
![imagen](https://user-images.githubusercontent.com/9405129/172062794-a6b6f060-890b-416b-8b56-990c4ec9ceec.png)
![imagen](https://user-images.githubusercontent.com/9405129/172062807-e4c13980-388e-4fdb-867a-c67ce4993b56.png)
![imagen](https://user-images.githubusercontent.com/9405129/172062811-9bfa13a8-f121-43df-9944-222dc8a8b951.png)

not relevant, all zeros

### Other clusters that are not mentioned above
![imagen](https://user-images.githubusercontent.com/9405129/172062827-d7b03c8d-c4a2-4470-9e3d-117fab91337c.png)

**Comment by Mimiix** [comment]
Can you please add a screen of the cluster list and also the other clusters if applicable.

**Comment by danidask** [comment]
> Can you please add a screen of the cluster list and also the other clusters if applicable.

I added that info. Thanks for the quick reply!

**Comment by Mimiix** [comment]
Please add all screens, even if they are zero.

**Comment by danidask** [comment]
Done! BTW an "export data" option in deCONZ will save a lot of time, and github storage space IMO

**Comment by danidask** [comment]
Please remove the "imcomplete issue" tag, or let me know if you need more information

**Comment by Mimiix** [comment]
I'll reopen.

**Comment by Mimiix** [comment]
@Smanar can you help?

**Comment by Smanar** [comment]
Nope sorry, I m still waiting for PR for TRV using tuya cluster was merged to start Covering using the same cluster.

**Comment by omegasxxi** [comment]
Will Thais decide be Support ex?

**Comment by Smanar** [comment]
IDK, will be a surpise, we will perhaps a new code version for DDF, but I can't say when and if this version will be able tu support this device.
