### ISSUE TITLE
IKEA ÅSKVÄDER / ASKVADER on/off switch

### ISSUE THREAD

**Issue by CapitalT** [dresden-elektronik/deconz-rest-plugin#6119]
## Device

- Product name: ÅSKVÄDER
- Manufacturer: IKEA of Sweden
- Model identifier: ASKVADER on/off switch
- Device type :
  - Switch (added under lights)
  - Router
- Site: https://www.ikea.com/nl/en/p/askvaeder-on-off-switch-50463880/

This 10 euro IKEA switch seems to work flawlessly. Tested on gateway version: 2.14.01 / 2/6/2022. However it is not added to the supported devices.

**Comment by Mimiix** [comment]
Feel free to add it to the list :)
