### ISSUE TITLE
RTX ZTH1

### ISSUE THREAD

**Issue by kozga** [dresden-elektronik/deconz-rest-plugin#6123]
## Device
- Product name: ZTH1
- Manufacturer: RTX
- Model identifier: TS0201
- Device type:  Sensor

It's a strange device,  on the sensor packaging it is described as RTX ZTH1, while in the manual the model is ZC-W1.

## Screenshots
* packaging
![packaging](https://user-images.githubusercontent.com/22498983/172612076-2a542f45-81e5-4da5-9009-b9cec0ab00c4.jpg)

* manual
![manual](https://user-images.githubusercontent.com/22498983/172612135-d9063cfd-34a5-4899-81c9-b45c8bc66936.jpg)

### Basic
* attributes
![attrib](https://user-images.githubusercontent.com/22498983/172605482-4de717aa-8cdb-4ced-8fb6-a98a41d05772.png)

* node info
![node_info](https://user-images.githubusercontent.com/22498983/172605528-ee8bb759-e4fa-4767-a6bf-e2a987976a76.png)

![temp_other_nodes](https://user-images.githubusercontent.com/22498983/172790720-1212a294-d970-4d4f-b6ce-7d86b3df9764.png)

### Identify
![temp_ident](https://user-images.githubusercontent.com/22498983/172782021-00998691-5df8-4f2a-9005-2b7848f5e97f.png)

### Level Control
![temp_power](https://user-images.githubusercontent.com/22498983/172789337-96cc2bc7-8754-4ebf-ac21-88075fba787a.png)

### Simple Metering
* temperature
![temp_temp_measure](https://user-images.githubusercontent.com/22498983/172782167-b2366652-2528-46d3-ab27-1aa5636203b1.png)

* humidity
![temp_humiti](https://user-images.githubusercontent.com/22498983/172788881-9fca111a-167f-4ede-b958-8bf225ca6aad.png)

### Other clusters that are not  mentioned above
![temp_otau](https://user-images.githubusercontent.com/22498983/172789101-4a027f82-1016-4c6c-be65-a66906242fe4.png)

**Comment by Smanar** [comment]
Hello so first the manufacture name is "_tz3000_i8jfiezr"

There is a PR to support it with c++ code here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5299
But as this one will be never merged can you try this DDF ?

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_i8jfiezr",
  "modelid": "TS0201",
  "vendor": "RTX",
  "product": "TS0201",
  "sleeper": true,
  "status": "Bronze",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/battery"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "awake": true
        },
        {
          "name": "state/battery"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 1,
          "max": 6000,
          "change": "0x00000014"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 10,
          "max": 300,
          "change": "0x00000014"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 10,
          "max": 9999,
          "change": "0x00000014"
        }
      ]
    }
  ]
}
```

**Comment by LukaszGaraKrk** [comment]
Here are the screenshots that were missing:
![temp_humiti](https://user-images.githubusercontent.com/103513454/172647346-3405328d-54e6-4948-99f5-90d8e6f025bd.png)
![temp_ident](https://user-images.githubusercontent.com/103513454/172647351-aec3eba4-fe2b-4e0b-8aa6-9cfd3535e46c.png)
![temp_power](https://user-images.githubusercontent.com/103513454/172647353-882073d9-f26a-4df0-a836-bb2c3af87277.png)
![temp_temp_measure](https://user-images.githubusercontent.com/103513454/172647355-b1073138-0315-4b63-87a6-9670210f81b4.png)

**Comment by Mimiix** [comment]
Please add them to the original post.

Also missing the full list.

**Comment by kozga** [comment]
We moved the screenshots to original post. After adding the DDF file, the sensor was detected correctly. Thanks for your help.

**Comment by Smanar** [comment]
So all is working (battery too ?), I can make a PR for it ?

**Comment by kozga** [comment]
It looks like the battery is working, response from api:

```
{
      "etag" : "d4953035b71b93321ccd0a724a581e8d",
      "modelid" : "TS0201",
      "manufacturername" : "_TZ3000_i8jfiezr",
      "type" : "ZHATemperature",
      "uniqueid" : "a4:c1:38:b5:b9:25:27:d0-01-0402",
      "name" : "Temperature 10",
      "config" : {
         "on" : true,
         "reachable" : true,
         "offset" : 0
      },
      "lastannounced" : null,
      "state" : {
         "temperature" : 2485,
         "battery" : 79,
         "lastupdated" : "2022-06-10T06:37:46.048"
      },
      "lastseen" : "2022-06-10T06:37Z"
}
```

```
{
      "manufacturername" : "_TZ3000_i8jfiezr",
      "modelid" : "TS0201",
      "etag" : "d1372e04179b092345fa3d7fb5ff50ff",
      "name" : "Humidity 11",
      "uniqueid" : "a4:c1:38:b5:b9:25:27:d0-01-0405",
      "type" : "ZHAHumidity",
      "lastseen" : "2022-06-10T06:37Z",
      "state" : {
         "humidity" : 4882,
         "lastupdated" : "2022-06-10T06:37:46.302",
         "battery" : 79
      },
      "lastannounced" : null,
      "config" : {
         "on" : true,
         "offset" : 0,
         "reachable" : true
      }
}
```

**Comment by Smanar** [comment]
Thx, PR done.
