### ISSUE TITLE
Frient/Develco WISZB-121 open/close sensor

### ISSUE THREAD

**Issue by paddyobrien** [dresden-elektronik/deconz-rest-plugin#6136]
## WISZB-121 open/close sensor

- Product name: Frient/Develco Entry Sensor
- Manufacturer: friend A/S
- Model identifier: WISZB-121
- Device type: 
  - Sensor

This appears to be a chopped down version of https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/frient/wiszb-120_open_close_sensor.json, without the temperature sensor.

## Screenshots

<img width="592" alt="Screenshot 2022-06-16 at 16 49 09" src="https://user-images.githubusercontent.com/846372/174112453-fcc8f8c6-bc72-4626-8e53-3ea88724f46e.png">

<img width="365" alt="Screenshot 2022-06-16 at 16 47 39" src="https://user-images.githubusercontent.com/846372/174112195-89b58bfc-3131-40c8-bbfa-01e4151cbd5b.png">
/Devel

### Basic

<img width="587" alt="Screenshot 2022-06-16 at 16 48 56" src="https://user-images.githubusercontent.com/846372/174112498-e63bb3b8-71a6-4dfa-a8f3-14dece503ecf.png">

### Identify
<img width="586" alt="Screenshot 2022-06-16 at 16 50 26" src="https://user-images.githubusercontent.com/846372/174112933-7623cc81-1390-434a-822a-7b14d991de76.png">

### Power configuration

<img width="580" alt="Screenshot 2022-06-16 at 16 50 34" src="https://user-images.githubusercontent.com/846372/174113067-8d380f58-e5e7-4d66-82a2-727fcc3704e1.png">

### Binary Input (Basic)

<img width="586" alt="Screenshot 2022-06-16 at 16 50 50" src="https://user-images.githubusercontent.com/846372/174113150-3d923b95-9669-4bac-97ac-f9f2793ad0e7.png">

### Poll Control

<img width="570" alt="Screenshot 2022-06-16 at 16 51 02" src="https://user-images.githubusercontent.com/846372/174113221-66ca9c09-5508-4672-a00e-49afe49c2c65.png">

### IAS Zone

<img width="573" alt="Screenshot 2022-06-16 at 16 51 31" src="https://user-images.githubusercontent.com/846372/174113284-3f31bb45-eb29-4656-82b3-494bb602233a.png">

<img width="573" alt="Screenshot 2022-06-16 at 16 51 39" src="https://user-images.githubusercontent.com/846372/174113333-8738663f-95b2-495f-a934-e92148f5f622.png">

**Comment by SwoopX** [comment]
If you take the fitting file from the referenced PR and place it according to guidance from [here](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#precedence-of-ddf-files), you can start using it after a deconz restart.

**Comment by paddyobrien** [comment]
Thank you, I figured that out eventually myself (using Docker so it was a bit of mess to get there). I have a couple more unsupported devices to add, so that DDF cheat sheet should be quite helpful.
