### ISSUE TITLE
Possible to treat router as a battery-powered device?

### ISSUE THREAD

**Issue by Shurov** [dresden-elektronik/deconz-rest-plugin#6144]
I have a Tuya water valve that is 12V powered (power supply is provided in the box). But I power it from 12V accu, since there is no power socket in the valves. The accu is drained in a few days - I suppose because the router approach, plus maybe more frequent queries due to thinking of constant and unlimited power supply. 

So my question as in title - can I change treatment of the device from being a router\with constant power supply to a battery one?

P.S. Sorry if I ask this in the wrong place. It's not technically a bug or new device request....

**Comment by Mimiix** [comment]
Please ask this on the forums
