### ISSUE TITLE
Perenio Power Link

### ISSUE THREAD

**Issue by inamesh** [dresden-elektronik/deconz-rest-plugin#6146]
## Device

- Product name: Perenio Power Link
- Manufacturer: Perenio
- Model identifier: PEHPL0X
- Device type : 
  ~~- Switch~~
  - Plug
(Edited Device Type)

### Node Info
![image](https://user-images.githubusercontent.com/22492259/174554513-1056d717-09a1-4a86-856c-04599b2621f0.png)

### All Clusters
![image](https://user-images.githubusercontent.com/22492259/174555943-f0ce0b3a-0ce5-478b-87e3-bdb16e6b5af4.png)

### Basic
![image](https://user-images.githubusercontent.com/22492259/174554229-6e407288-7b9a-40da-8da4-d876866d4353.png)

### Identify
![image](https://user-images.githubusercontent.com/22492259/174554626-73e487e3-79c6-4801-9fa8-a6cf88e2f079.png)

### Groups
![image](https://user-images.githubusercontent.com/22492259/174555281-62750afe-3164-4bb5-b45d-8b642cbeed78.png)

### On/Off
![image](https://user-images.githubusercontent.com/22492259/174554796-9c428f8b-f0b8-4184-adde-f284af81457d.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/22492259/174555177-2d9489db-2407-49c8-a5ab-7196c5e547f0.png)
![image](https://user-images.githubusercontent.com/22492259/174555222-5bdffd5a-cea6-49af-aff2-4b0e5fc6a0c8.png)

### OTAU
![image](https://user-images.githubusercontent.com/22492259/174555459-73dfffaf-675c-4bb1-ab12-f169514cd27a.png)

**Comment by Smanar** [comment]
> Device type :
>     Switch

Sure it's not a plug ?

Can try this DDF, made for plug

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Perenio",
  "modelid": "PEHPL0X",
  "vendor": "Perenio",
  "product": "Power Link Plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power"
        },
        {
          "name": "state/voltage"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by Smanar** [comment]
Can you take a look direclty in the API, for exemple using Phoscon, help / API iInformation / sensor ?
Because there is no reason for the DDF create only the ZHAConsumption and not the ZHAPower.

On your captuere the value for consumption is 0 too
And for electrical measurement cluster, you forget to press the "read" button, so not possible to check working value or not.

You have see others DDF in the folder you have put the DDF ? (or have used custom/user folder ?)

**Comment by inamesh** [comment]
Hi!
After a couple of restarts I now have 2 sensors in this device, but the values are still strange - 
![image](https://user-images.githubusercontent.com/22492259/175297786-43bc3dbd-a6fa-4924-adc4-66e13c770875.png)

I checked with API and below are the responses for each of these sensors -

**ZHAPower**

{
    "config": {
        "on": true,
        "reachable": true
    },
    "etag": "a550f90994314909ab9c0767c2ed99ab",
    "lastannounced": null,
    "lastseen": "2022-06-23T12:19Z",
    "manufacturername": "Perenio",
    "modelid": "PEHPL0X",
    "name": "Power 47",
    "state": {
        "current": 0,
        "lastupdated": "none",
        "power": 0,
        "voltage": 0
    },
    "swversion": "1.3.11",
    "type": "ZHAPower",
    "uniqueid": "f4:ce:36:ce:42:ab:fc:55-01-0b04"
}



**ZHAConsumption**


{
    "config": {
        "on": true,
        "reachable": true
    },
    "etag": "e24b3c5071493b3ac2a52d75ee2cf318",
    "lastannounced": null,
    "lastseen": "2022-06-23T12:24Z",
    "manufacturername": "Perenio",
    "modelid": "PEHPL0X",
    "name": "Consumption 46",
    "state": {
        "consumption": 18,
        "lastupdated": "2022-06-23T12:25:04.446"
    },
    "swversion": "1.3.11",
    "type": "ZHAConsumption",
    "uniqueid": "f4:ce:36:ce:42:ab:fc:55-01-0702"
}



The values on the cluster do not change on pressing "read" -

![image](https://user-images.githubusercontent.com/22492259/175298416-437d0d2f-6895-48cf-8180-9c2f3243a721.png)



Finally, I don't have any other ddfs in the folder. I'm using the below folder (which the deCONZ GUI opens by default) - /usr/share/hassio/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices

Thank you once again, and do let me know if I can help troubleshoot further!

**Comment by Smanar** [comment]
>The values on the cluster do not change on pressing "read" -

Seem realy bad, it s like your device don't support them.
As it's a powered device, no need to wake it, the "read" button worj immediatly.

For the consumption, I can't be sure, I can use a convertor, but from your capture, the value need to be as it, no divisor, no multiplicator
