### ISSUE TITLE
No websocket events for sensor state changes

### ISSUE THREAD

**Issue by sberryman** [dresden-elektronik/deconz-rest-plugin#615]
# Problem
No websocket events are created for sensor resource type. This used to work for me for at least the past 60 days. I expect state changes for presence otherwise I would have to rely on polling. I also know polling is working as expected as the Phoscon App shows changes when triggering the motion sensors.

Note: This is a headless install

#### OS
Linux hassbian 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

#### Vendor
dresden elektronik

#### Product
RaspBee

#### Version
2.05.28 / 5/3/2018

#### Firmware
26210500

#### deconz-rest-plugin version
HEAD detached at fc1d22d

## Sensor
Example sensor result from API
```json
    "36": {
        "config": {
            "alert": "none",
            "battery": 100,
            "delay": 0,
            "ledindication": false,
            "on": true,
            "pending": [],
            "reachable": true,
            "sensitivity": 0,
            "sensitivitymax": 2,
            "usertest": false
        },
        "ep": 2,
        "etag": "20fd9ba4fc016a79ef689cc0570cc7b1",
        "manufacturername": "Philips",
        "modelid": "SML001",
        "name": "Livingroom Sensor",
        "state": {
            "lastupdated": "2018-05-30T01:42:00",
            "presence": false
        },
        "swversion": "6.1.0.18912",
        "type": "ZHAPresence",
        "uniqueid": "[Removed]"
    },
```

## Test
Using [nodejs-websocket](https://www.npmjs.com/package/nodejs-websocket), and the following script
```js
var ws = require("nodejs-websocket")
var socket = ws.connect('ws://{ip-address}:{port}')
socket.on('text', function (str) {
    console.log('Received ', str)
})
```

## Example output
```shell
Received {"e":"changed","id":"4","r":"lights","state":{"on":false},"t":"event"}
Received {"e":"changed","id":"3","r":"lights","state":{"on":false},"t":"event"}
Received {"e":"changed","id":"2","r":"lights","state":{"on":false},"t":"event"}
Received {"e":"changed","id":"4","r":"lights","state":{"on":true},"t":"event"}
Received {"e":"changed","id":"3","r":"lights","state":{"on":true},"t":"event"}
Received {"e":"changed","id":"2","r":"lights","state":{"on":true},"t":"event"}
```

**Comment by ebaauw** [comment]
Did you check that the sensor state has changes when polling the sensor?  I do receive websocket events for sensors in v2.05.28 and firmware 26210500.

I think the problem is likely in the communication between the sensor and the RaspBee, not in deCONZ issuing websocket events.  My Hue motion sensors blink red all the time when detecting motion.  See #610.

**Comment by manup** [comment]
@ebaauw  to which parent node is the sensor sensor connected, via RaspBee directly?
There might be a routing issue might be in place, sensor has a route to gateway but the way back doesn't work somehow and the sensor receives no ack/default zcl response (would cause red blinking).

**Comment by sberryman** [comment]
Okay, this is really weird. I went to bed and woke up and the sensors are posting state changes. I seriously didn't change a thing.

@ebaauw Yes, the state changed when polling the sensor but didn't post to the websocket.

@manup how would I check that? I don't recall seeing a red blinking light on the sensor when the state changed (and it wasn't posting to the websocket) but they are showing a blinking red light now.

```shell
Received {"e":"changed","id":"14","r":"sensors","state":{"dark":true,"daylight":false,"lastupdated":"2018-05-30T08:58:26","lightlevel":0,"lux":0},"t":"event"}
Received {"e":"changed","id":"37","r":"sensors","state":{"lastupdated":"2018-05-30T08:58:31","temperature":1933},"t":"event"}
Received {"e":"changed","id":"25","r":"sensors","state":{"lastupdated":"2018-05-30T08:58:36","temperature":1962},"t":"event"}
Received {"config":{"alert":"none","battery":100,"ledindication":false,"on":true,"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"e":"changed","id":"35","r":"sensors","t":"event"}
Received {"config":{"alert":"none","battery":100,"delay":0,"ledindication":false,"on":true,"reachable":true,"sensitivity":0,"sensitivitymax":2,"usertest":false},"e":"changed","id":"36","r":"sensors","t":"event"}
Received {"config":{"alert":"none","battery":100,"ledindication":false,"offset":0,"on":true,"reachable":true,"usertest":false},"e":"changed","id":"37","r":"sensors","t":"event"}
```

**Comment by sberryman** [comment]
@ebaauw What would you suggest I try? I'm a bit scared to restart the Pi right now as it is working again. Not so keen on wasting another day, although, at this point I suppose I can count it working after a period of time.

**Comment by ebaauw** [comment]
> What would you suggest I try?

Downgrade the RaspBee firmware, see #610.  Stop deCONZ, issue:
```
$ sudo GCFFlasher_internal -f /usr/share/deCONZ/firmware/deCONZ_Rpi_0x261f0500.bin.GCF
```
and start deCONZ.

> On a side note I would also like to help add support for the Lowes iris door sensor

Please open a new issue and post deCONZ GUI screenshots of the node, including endpoints and clusters; of the _Node Info_ panel; and of the _Cluster Info_ panel of the _Basic_ cluster.

**Comment by noyc** [comment]
Hi

I have experienced the same behaviour as you described some time ago where the sensors suddenly started working after a few hours. I never figured out why

However, I don't know if this is related at all, but I had trouble getting my sensors working after restarting my Raspberry Pi today

After some fiddling around, I noticed that I had the wrong timezone configured in deconz. Changing it to my timezone(matching the time of the Raspberry Pi) I immediately started receiving data through websocket. As soon as I switch back to the old timezone(which was GMT), I stop receiving websocket-data

I tried to restart my Raspberry Pi again to recreate the scenario, but each time I reboot, the timezone is saved.

**Comment by sberryman** [comment]
I finally looked at this again as I was forced to restart today. I upgraded to the latest versions and had the same issue of no motion sensor updates. So I checked timezones and sure enough the system was set to UTC and deconz to my local timezone. I switched deconz to UTC and motion sensors started working immediately.

**Comment by manup** [comment]
The issue is now on the todo list and should be fixed in the next releases.

**Comment by phobozad** [comment]
Last I checked this is still an issue and hadn't been fixed in any release.  Has this been fixed in a recent commit?

**Comment by manup** [comment]
>Has this been fixed in a recent commit?

Nope unfortunately not. We are working of a refactor of the Phoscon App settings page which also includes time handling to properly detect/set timezone.
