### ISSUE TITLE
LoraTap Tuya ZigBee 3.0 Wireless 4 Gang Remote Control Switch

### ISSUE THREAD

**Issue by sinus61** [dresden-elektronik/deconz-rest-plugin#6156]
## Device

- Product name: LoraTap Tuya ZigBee 3.0 Wireless 4 Gang Remote Control Switch 
- Manufacturer: _TZ3000_ufhtxr59
- Model identifier: TS0044
- Device type : 

  - Remote
https://www.loratap.com/products/ss6400zb-v2

## Screenshots
![grafik](https://user-images.githubusercontent.com/86767296/176631096-1e83ff6c-0d63-4ea3-a10c-19707ed6f5e6.png)

### Basic
![grafik](https://user-images.githubusercontent.com/86767296/176630114-284ffb43-2ebc-4e54-bbe5-1acf75f6c3ba.png)

### Power Configuration
![grafik](https://user-images.githubusercontent.com/86767296/176630375-b375c599-4db7-40a7-b3d9-70896ac12128.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/86767296/176630556-96a93043-820a-4a42-a521-234c9d9a9628.png)

The device is similar to _TZ3000_t8hzpgnd, https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5731
only this has 4 buttons.

So I've added _TZ3000_ufhtxr59 to the button_maps.json and made a DDF:

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_ufhtxr59",
  "modelid": "TS0044",
  "product": "TS0044",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/_TZ3000_ufhtxr59_4gang_bat_switch.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "refresh.interval": 4000,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 4,
      "dst.ep": 1,
      "cl": "0x0006"
    }
  ]
}

But only the battary event is working, not the button events. And there are 4 lights created.

**Comment by sinus61** [comment]
> > So I've added _TZ3000_ufhtxr59 to the button_maps.json
> 
> It's the one in the "devices" folder ?

Yes, in /usr/share/deCONZ/devices/

And I've placed the DDF in /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices

**Comment by Smanar** [comment]
So I m almost sure it s the problem with the legacy code too fast.
And If I m right It's no more possible to delete only a "device part" in the API.

**Comment by Smanar** [comment]
For information on the next deconz version, this issue will be probably solved https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6196
