### ISSUE TITLE
Rules not always triggered

### ISSUE THREAD

**Issue by ooii** [dresden-elektronik/deconz-rest-plugin#618]
Hi,

I have few Hue motion sensors that I have configured through the rest API. They used to work well until `v2.05.25` (I'm running `v2.05.28` now).
Since then, rules are not always triggered. For instance, I have the following rule that changes the status of a `ClipGenericStatus` from `0` to `1` if it detects presence, if it is dark, and if its status is `0`.

```
{
  "actions": [
    {
      "address": "/sensors/27/state",
      "body": {
        "status": 1
      },
      "method": "PUT"
    }
  ],
  "conditions": [
    {
      "address": "/groups/7/state/any_on",
      "operator": "eq",
      "value": "false"
    },
    {
      "address": "/sensors/15/state/presence",
      "operator": "eq",
      "value": "true"
    },
    {
      "address": "/sensors/15/state/presence",
      "operator": "dx"
    },
    {
      "address": "/sensors/27/state/status",
      "operator": "eq",
      "value": "0"
    },
    {
      "address": "/sensors/14/state/dark",
      "operator": "eq",
      "value": "true"
    }
  ],
  "created": "2018-04-25T00:10:29",
  "etag": "3099bcbc974b119a06d58d57ee83e2f5",
  "lasttriggered": "none",
  "name": "Chaufferie.Motion-on",
  "owner": "me",
  "periodic": 0,
  "status": "enabled",
  "timestriggered": 0
}
```

When the motion sensors detects presence and conditions are met, it does not trigger the associated action. But, if I turn `on` the associated group then turn it `off`, then it starts triggering the rule normally for few minutes.

I have this behaviour happening with 6 sensors.

Any idea what it is misbehaving? 
PS: `lasttriggered ` and `timestriggered` are, respectively, set to `None` and `0` because I restarted the daemon right before getting the info.

**Comment by ooii** [comment]
HI @manup,

I'm afraid my issue is not related to #619 and others related issues.
In my case, rules (created through the API and not through Phoscon), are sometimes triggered and sometimes not, which is not the case of #619.

**Comment by ebaauw** [comment]
Are you sure the issue is with the sensor?  I found the light and group states are no longer updated when issuing scene commands.  Did you check `/groups/7/state/any_on`?

**Comment by ooii** [comment]
I don’t think the issue is with the sensor since it reports motion and darkness. If I remember well, I checked all the conditions. 
The  problem does not occur currently so I cannot check. I’ll report later if it happens again.

**Comment by ooii** [comment]
So here I'm back with this issue happening again.
So here is the rule

```
$ ph get /rules/83
{
  "actions": [
    {
      "address": "/sensors/28/state",
      "body": {
        "status": 1
      },
      "method": "PUT"
    }
  ],
  "conditions": [
    {
      "address": "/groups/9/state/any_on",
      "operator": "eq",
      "value": "false"
    },
    {
      "address": "/sensors/18/state/presence",
      "operator": "eq",
      "value": "true"
    },
    {
      "address": "/sensors/18/state/presence",
      "operator": "dx"
    },
    {
      "address": "/sensors/28/state/status",
      "operator": "eq",
      "value": "0"
    },
    {
      "address": "/sensors/17/state/dark",
      "operator": "eq",
      "value": "true"
    }
  ],
  "created": "2018-04-25T00:10:30",
  "etag": "fbb018856be1c89f62704a158714ca3b",
  "lasttriggered": "none",
  "name": "EscalierGarage.Motion-on",
  "periodic": 0,
  "status": "enabled",
  "timestriggered": 0
}
```

And here is the status of the different sensors and group involved in the rule:

```
$ ph get /groups/9
{
  "action": {
    "bri": 127,
    "colormode": "hs",
    "ct": 0,
    "effect": "none",
    "hue": 0,
    "on": false,
    "sat": 127,
    "scene": null,
    "xy": [
      0,
      0
    ]
  },
  "class": "Other",
  "devicemembership": [],
  "etag": "fbb018856be1c89f62704a158714ca3b",
  "hidden": false,
  "id": "9",
  "lights": [
    "7"
  ],
  "lightsequence": [],
  "multideviceids": [],
  "name": "Escalier Garage",
  "scenes": [],
  "state": {
    "all_on": false,
    "any_on": false
  },
  "type": "LightGroup"
}
```

```
ph get /sensors/28
{
  "config": {
    "on": true,
    "reachable": true
  },
  "etag": "fbb018856be1c89f62704a158714ca3b",
  "manufacturername": "_dummy",
  "modelid": "_dummy",
  "name": "CGS.Esc.Garage",
  "state": {
    "lastupdated": "none",
    "status": 0
  },
  "swversion": "0",
  "type": "CLIPGenericStatus",
  "uniqueid": "_dummy"
}
```

```
$ ph get /sensors/18
{
  "config": {
    "alert": "select",
    "battery": 100,
    "delay": 0,
    "ledindication": false,
    "on": true,
    "pending": [],
    "reachable": true,
    "sensitivity": 0,
    "sensitivitymax": 2,
    "usertest": false
  },
  "ep": 2,
  "etag": "fdb0880022bb4a9fbfe0541e7c05ebd9",
  "manufacturername": "Philips",
  "modelid": "SML001",
  "name": "Hue Sensor Escalier Garage",
  "state": {
    "lastupdated": "2018-06-16T20:30:25",
    "presence": false
  },
  "swversion": "6.1.0.18912",
  "type": "ZHAPresence",
  "uniqueid": "00:17:88:01:02:01:dc:32-02-0406"
}
```

```
$ ph get /sensors/17
{
  "config": {
    "alert": "none",
    "battery": 100,
    "ledindication": false,
    "on": true,
    "pending": [],
    "reachable": true,
    "tholddark": 9000,
    "tholdoffset": 7000,
    "usertest": false
  },
  "ep": 2,
  "etag": "706d43ff9d54f53f14ebf9b7eec77a94",
  "manufacturername": "Philips",
  "modelid": "SML001",
  "name": "Hue Sensor Escalier Garage",
  "state": {
    "dark": true,
    "daylight": false,
    "lastupdated": "2018-06-16T20:26:06",
    "lightlevel": 0,
    "lux": 0
  },
  "swversion": "6.1.0.18912",
  "type": "ZHALightLevel",
  "uniqueid": "00:17:88:01:02:01:dc:32-02-0400"
}
```

While getting the status of these sensors and group, I was running the following command in order to check that the status does not change while I'm copying it here and nothing was reported.
`journalctl -au dc_eventlog --follow | grep -i "/sensors/28\|/sensors/17\|/sensors/18\|/groups/9"`

When I moved close to the sensor, the following log reported the motion detection
`22:31:23 Proliant dc_eventlog[23990]: /sensors/18/state: {"lastupdated":"2018-06-16T20:31:23","presence":true}`

but `/sensors/28`'s status did not change to 1 as it is supposed to do. 

I ran the test several times, the motion is always detected but the rule is never triggered. However, when I switched on the associated light (with this command `ph put /groups/9/action '{"on":true}'`), then the rule started being triggered normally.

**Comment by ooii** [comment]
I'll do that the next time but the rule started working when I switched on then off the associated light, without touching the CLIPGenericStatus.

**Comment by ebaauw** [comment]
That would suggest that `state.any_on` from `/groups/9` isn't initialised properly after restarting deCONZ.  It shows `false` in the REST API, but still fails the rule condition `eq` `"false"`.  I'll need to add some debug messages and do extensive testing to confirm - this will have to wait until next weekend.

Out of interest, why do you want the condition on the group state?  As I said above, it might not be reliable.  You're keeping your own state in the CLIPGenericStatus sensor anyways.

**Comment by ooii** [comment]
I want this condition to make the sensor "disabled" if I switch on the light manually.

By the way, any idea if it is possible to log which rule has been triggered? That will make my debugging easier.

**Comment by ebaauw** [comment]
> By the way, any idea if it is possible to log which rule has been triggered?

Change the service to start deCONZ with `--dbg-info=2` and monitor the log by:
```
$ sudo journalctl -afn 1000 -u deconz-gui | grep rule | grep -v sql
Jun 18 21:49:45 pi2 deCONZ[15387]: 21:49:41:289 rule event: /sensors/266 state/open num (0 -> 0)
Jun 18 21:49:46 pi2 deCONZ[15387]: 21:49:46:074 rule event: /sensors/224 state/temperature num (2234 -> 2234)
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:756 rule event: /sensors/226 state/lastupdated num (0 -> 0)
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:756 trigger rule 54 - Living Room Switch On/Off Press (1/2)
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:759 rule event: /sensors/221 state/status num (1 -> 0)
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:759 trigger rule 39 - Living Room Status <1
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:765 rule event: /sensors/220 state/flag num (1 -> 0)
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:766 trigger rule 56 - Living Room Off
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:768 trigger rule 61 - Living Room Off
Jun 18 21:50:43 pi2 deCONZ[15387]: 21:50:43:774 rule event: /sensors/220 state/lastupdated num (0 -> 0)
```
You'll see the events (the same as pushed to the web socket) that might cause a rule to fire and the rules actually being fired.  You don't see the conditions being evaluated, though - that's what I need the additional debug messages for...

If you run `dc_eventlog` at the same time, you'll get a pretty good idea what's happening.

**Comment by ebaauw** [comment]
> I want this condition to make the sensor "disabled" if I switch on the light manually.

I use a slightly different approach for this: I set the room's CLIPGenericStatus sensor to -1 to disable all automations for the room, and I check for this status in every rule related to the room.  I programmed my Hue dimmer switches to set the status to -1 when holding the _Off_ button.  Also I set this status in my HomeKit _Goodnight_ scene, so my bedroom lights don't switch on when I'm turning in my sleep.

> > It shows false in the REST API, but still fails the rule condition eq "false".

> Is that specific to my case or a known issue?

I suspect it might be an issue - I need to do some testing before I know more.

**Comment by ooii** [comment]
>Change the service to start deCONZ with --dbg-info=2 and monitor the log by:

Thank you very much.

>I use a slightly different approach for this: I set the room's CLIPGenericStatus sensor to -1 to disable all automations for the room, and I check for this status in every rule related to the room. 

In my case, I check in all my rules that `any_on` is `false`. And I'm already setting a CLIPGenericStatus sensor to -1 when I switch off manually a light. It is set back to 0 after 2 minutes. I could set it to -1 each time I fire an action from the switch.

Do you set this CLIPGenericStatus sensor automatically to another value after setting it to -1?

**Comment by ooii** [comment]
Hi all,

I come back to this issue since I cannot have a working configuration. I tried to use the `phoscon app` but I was not able to have something working. First, I had this time intervals for dimming and switching off which are not well reflected in the api (see [here](https://github.com/dresden-elektronik/phoscon-app-beta/issues/11)) then, I had my lights that remain on while I'm moving in a room up to a certain duration before turning off without the ability to switch them on by moving in front of the sensor. So i came back to putting my own rules in the api but I faced some issues that I enumerate here.

I want the following scenario, seen [in `Hue` dev forums](https://developers.meethue.com/content/better-rules-motion-sensor), detailed with a diagram:

![](https://i.snag.gy/e7tiYB.jpg)
and explained in the following: 

1. I have a `_ClipGenericStatus` (noted `CGS`) which initial state is `0`. When this `CGS` is set to 0, the lights are switched off. 
2. If a presence is detected while it is dark (or dark is detected with a presence), then `CGS` is set to `1`. Setting `CGS` to `1` sets it immediately to `2` with no other action.
3. If `CGS` is set to `2`, then lights are turned on `100%`.
4. When `CGS` is equal to `2` and a presence is detected, it is back to `1` (and then immediately after to `2` and switches on the lights). 
5. If `CGS` is set to `2` and no presence is detected for a minute, `CGS` is set to `3` (which dims the lights).
6. If `CGS` is set to `3` and motion is detected, `CGS` is set back to `1` (and then to `2` which puts the lights at `100%`).
7. If `CGS` is set to `3` for 30 seconds and no motion is detected in the meanwhile, then `CGS` is put to `0` which switches off the lignts.

When `presence` is already `true`, I don't receive any notification about the `presence` sensor until it turns to `false`. This generates at least the following three identified issues:

1. First, at `CGS=0`, if a presence is detected, I receive a `presence` set to `true` which ends with `CGS` set to `1` then to `2` and lights to `on` at `100%`. If no motion is detected after that, then I receive a `presence` set to `false` about 1 min and 6 seconds later. In that case, transition from `CGS=2` to `CGS=3` (the green arrow) never happens. I changed the `ddx` value to `00:01:10` and it fixed the issue.
2. Still when `CGS` is set to `2`, if motion is detected for more than a minute and 10 seconds, the green arrow becomes useless. If I have well understood, the condition in the associated box means "if CGS changed 1 min and 10 seconds ago and if `presence` is `false` then...". While in my case, something that works would be like "if `presence` has changed to `false` and `CGS` is set to `2` since 1 min and 10 seconds at least, then...", but I can't figure out how to write this final condition.
3. The red arrow is never triggered, since no `presence` set to `true` is received while `CGS` is equal to `2`.

So I need your help, please, to have the motion sensors useful. 
Thank you very much for reading all this message.

**Comment by ebaauw** [comment]
Hard to figure out exactly what you're trying to achieve, but it looks way too complicated to me.

- I would ditch the `dx` conditions and combine the two rules from status 0 to status 1 into one.
- I would combine status 1 and status 2 - I don't understand why you need two of these.
- The condition from state 1/2 to state 3 should be on presence false and lastupdated (of the presence sensor) ddx.
- The condition from state 3 to state 0 should be on status with ddx (on lastupdated of the status sensor) of 30 seconds, or on presence with a ddx (of lastupdated of the presence sensor) of 1:30.

> If no motion is detected after that, then I receive a presence set to false about 1 min and 6 seconds later.

That's odd, typically the Hue motion sensor sends the message 15 seconds after the last motion was detected.  Or did you set `config.delay`?

**Comment by ooii** [comment]
> Hard to figure out exactly what you're trying to achieve, but it looks way too complicated to me.
> 
> I would ditch the dx conditions and combine the two rules from status 0 to status 1 into one.
> I would combine status 1 and status 2 - I don't understand why you need two of these.
> The condition from state 1/2 to state 3 should be on presence false and lastupdated (of the presence sensor) ddx.
> The condition from state 3 to state 0 should be on status with ddx (on lastupdated of the status sensor) of 30 seconds, or on presence with a ddx (of lastupdated of the presence sensor) of 1:30.

I'll try that tomorrow. Thanks.

> That's odd, typically the Hue motion sensor sends the message 15 seconds after the last motion was detected. Or did you set config.delay?

I don't remember touching that. Anyway, `config.delay` was set to 62. I changed it to 15 but the sensor reports as follows:

- If `presence` is `true` nothing is reported while motion (neither in the `journal` nor in the `lastupdated`)
- If `presence` is `true` and no motion for 15 seconds then status changes to `false`. That is reflected in the `journal` as well as in `lastupdated`
- If `presence` is `false` nothing is reported while no motion (neither in the `journal` nor in the `lastupdated`)
- If `presence` is `false` and motion is detected then status changes to `true`. That is reflected in the `journal` as well as in `lastupdated`

Sorry if that statement is different from what I said before (about reporting every 1min and 6 seconds) but that's what I observed today vs what I observed yesterday.

**Comment by ooii** [comment]
Thanks for the explanation. So the behavior I have described is not wrong. 
But I understand that the rules I was applying are not correct, especially the one based on detection of motion while `presence`is `true`, which cannot happen.

**Comment by ooii** [comment]
> - I would ditch the dx conditions and combine the two rules from status 0 to status 1 into one.

Agreed.
> - I would combine status 1 and status 2 - I don't understand why you need two of these.

Actually, the transition from 1 to 2 is done with different `bri` values depending on the time of the day. It's only for ease of maintenance and more clarity.

> - The condition from state 1/2 to state 3 should be on presence false and lastupdated (of the presence sensor) ddx.

Absolutely and that's the reason of my issues I think. I modified that and will check all that this evening.

**Comment by ooii** [comment]
Since the last update 2.05.39, I'm satisfied by rule execution. So I close this issue.
Thanks all for your help.
