### ISSUE TITLE
Connecte Smart Thermostat

### ISSUE THREAD

**Issue by joernnilsson** [dresden-elektronik/deconz-rest-plugin#6198]
## Device

- Product name: Connecte Smart Thermostat
- Manufacturer: _TZE200_4hbx5cvx
- Model identifier: TS0601
- Device type:
  - Thermostat

Manufacturer web page: https://en.connecte.no/termostat

I do have a contact to the manufacturer, and can probably request any missing/useful documentation.

### Basic
![image](https://user-images.githubusercontent.com/521757/179344224-74d17831-1ca6-413e-8477-384c715e4061.png)

### Identify
![image](https://user-images.githubusercontent.com/521757/179344264-25599563-7525-44b6-b34c-2ca32b7783bb.png)

### Thermostat
Multiple screenshots to see whole attribute list
![image](https://user-images.githubusercontent.com/521757/179344314-08435472-8c39-42c1-ba39-d191b469f96e.png)
![image](https://user-images.githubusercontent.com/521757/179344331-5257ffc8-d7cf-4060-a4f2-740248e91724.png)
![image](https://user-images.githubusercontent.com/521757/179344352-996876db-a147-4db0-8899-56bd23a03206.png)
![image](https://user-images.githubusercontent.com/521757/179344366-62ff069d-3520-4836-ac9c-852994d106bc.png)
![image](https://user-images.githubusercontent.com/521757/179344382-109a5346-ddbc-4aff-8c7a-52900d486436.png)
![image](https://user-images.githubusercontent.com/521757/179344390-c7145962-4c17-45a3-aa1e-31fe0fed87a5.png)
![image](https://user-images.githubusercontent.com/521757/179344407-bdc9e66f-b70a-4619-908d-4f0d298fca65.png)
![image](https://user-images.githubusercontent.com/521757/179344422-b0aeb4ae-5d44-40d8-b248-e8a84edae75e.png)
![image](https://user-images.githubusercontent.com/521757/179344447-b597226a-4ab6-4ff9-80f9-69aac116c2a7.png)

### Tuya Specific
![image](https://user-images.githubusercontent.com/521757/179344484-78909339-06a3-40f6-a33a-8213c70e43bd.png)

**Comment by joernnilsson** [comment]
I have received documentation/app note from the manufacturer, please see attached pdf

It seems that most functions are reachable through the Tuya specific cluster
[App note.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9179958/App.note.pdf)
. Is this outside the scope of deconz?

**Comment by Smanar** [comment]
For the moment tuya TRV are not possible usinf DDF waiting for this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054

**Comment by joernnilsson** [comment]
Ok, thanks :+1:

**Comment by joernnilsson** [comment]
Please keep this issue open. It is waiting for [#6054 ](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054) to be merged.

**Comment by joernnilsson** [comment]
Bumping, as we're still waiting for https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054 to be merged

**Comment by joernnilsson** [comment]
Bumping to avoid auto close, as we're still waiting for https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054 to be merged.

**Comment by joernnilsson** [comment]
Bumping to avoid auto close. Still waiting for https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054 to be merged.
