### ISSUE TITLE
MOES 2 Gang Switch _TZE200_g1ib5ldv

### ISSUE THREAD

**Issue by sn0wf4ke** [dresden-elektronik/deconz-rest-plugin#6199]
## Device

- Product name: MOES 2 Gang Switch (https://www.moeshouse.com/collections/smart-switch/products/zigbee-smart-wall-light-switch-with-neutral-wire-or-no-neutral-wire-wiring-no-capacitor-needed-smart-life-tuya-2-3-way-muilti-control-association-works-with-alexa-google-home-hub-required?variant=39357460578385)
- Manufacturer: _TZE200_g1ib5ldv
- Model identifier: TS0601
- Device type : Please remove all unrelated device types. 
   - Switch

## Screenshots
<img width="721" alt="image" src="https://user-images.githubusercontent.com/41108920/179349310-c38edb15-03f4-496c-a6d7-e7aee181defe.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/41108920/179349406-a9ad925a-dcf2-4f1e-946b-c00d6635a954.png">

### Basic
<img width="716" alt="image" src="https://user-images.githubusercontent.com/41108920/179349475-1755cf50-60f8-4445-b74c-7901960e2976.png">

### Groups
<img width="745" alt="image" src="https://user-images.githubusercontent.com/41108920/179349497-9b377ed4-ae38-48cc-a902-561e3f7315ef.png">
<img width="713" alt="image" src="https://user-images.githubusercontent.com/41108920/179349500-823bec31-22c1-4ff1-99cb-b2e214f07547.png">

### Scenes
<img width="752" alt="image" src="https://user-images.githubusercontent.com/41108920/179349511-79d981f8-d1b3-415d-85c2-5287e70eaf38.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/41108920/179349523-5d6bde45-76d6-4966-a397-717b40b71ac2.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/41108920/179349533-e480c60a-1be3-4187-8838-78b605c9dc9c.png">

### Tuya specific
<img width="728" alt="image" src="https://user-images.githubusercontent.com/41108920/179349552-b30a350d-8ef6-41ab-9c69-73a2dcec32b0.png">

### OTAU
<img width="718" alt="image" src="https://user-images.githubusercontent.com/41108920/179349574-50a77a51-2062-4e2f-9aa4-0c3b6513e906.png">

### Time
<img width="724" alt="image" src="https://user-images.githubusercontent.com/41108920/179349585-2f1001e6-22b1-47f2-83c6-56928fb852e1.png">

**Comment by sn0wf4ke** [comment]
ok I figured out how to bring one gang up inspired by #5869. 
My DDF now looks this way:
```json
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_g1ib5ldv",
  "modelid": "TS0601",
  "vendor": "$MF_TUYA",
  "product": "Smart Switch Module",
  "sleeper": false,
  "status": "Bronze",
  "path": "/devices/ts0601.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "public": false,
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 84000,
          "read": {
            "fn": "none"
          },
          "write": {
            "dpid": 1,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```
But how to control the second gang?

**Comment by forast3r** [comment]
> ok I figured out how to bring one gang up inspired by #5869. My DDF now looks this way:
> 
> ```json
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TZE200_g1ib5ldv",
>   "modelid": "TS0601",
>   "vendor": "$MF_TUYA",
>   "product": "Smart Switch Module",
>   "sleeper": false,
>   "status": "Bronze",
>   "path": "/devices/ts0601.json",
>   "subdevices": [
>     {
>       "type": "$TYPE_ON_OFF_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x02"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/alert",
>           "public": false,
>           "default": "none"
>         },
>         {
>           "name": "state/on",
>           "refresh.interval": 84000,
>           "read": {
>             "fn": "none"
>           },
>           "write": {
>             "dpid": 1,
>             "dt": "0x10",
>             "eval": "Item.val == 1 ? 1 : 0;",
>             "fn": "tuya"
>           },
>           "parse": {
>             "dpid": 1,
>             "eval": "Item.val = Attr.val;",
>             "fn": "tuya"
>           }
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> But how to control the second gang?

Did you manage to get the 2nd gang working? (I have received a similar one but 3-Gang)

**Comment by mweedon** [comment]
Any news on the 2 or 3-gang DDF?

I'm thinking it's time to migrate to zigbee2mqtt. :-(
