### ISSUE TITLE
3 button scene switch TS0043 _TZ3000_sj7jbgks

### ISSUE THREAD

**Issue by jostie123** [dresden-elektronik/deconz-rest-plugin#6213]
## Device

- Product name: 3 Button Scene Switch
- Manufacturer: _TZ3000_sj7jbgks
- Model identifier: TS0043
- Device type : 
  - Switch

[https://nl.aliexpress.com/item/1005004248050569.html](https://nl.aliexpress.com/item/1005004248050569.html)

![20220722_132108184_iOS](https://user-images.githubusercontent.com/8819339/180448151-e4d71c44-83e2-44d8-86ca-15ce9ca7df72.jpg)
![20220722_132120422_iOS](https://user-images.githubusercontent.com/8819339/180448159-62424762-c8be-46e9-a580-cc202e44d207.jpg)
![20220722_132141169_iOS](https://user-images.githubusercontent.com/8819339/180448166-f4de54e3-046e-4611-9c9f-487ac8d700f0.jpg)

## Screenshots
![image](https://user-images.githubusercontent.com/8819339/180447577-d7d2bfeb-cad1-4b52-9850-310db41dd316.png)
### Basic
![image](https://user-images.githubusercontent.com/8819339/180446603-8252f593-dd84-4ca7-aae0-d29f943095bd.png)
![image](https://user-images.githubusercontent.com/8819339/180450175-6aa79324-0982-4a1d-bf97-d36f1951787f.png)

### On/Off
![image](https://user-images.githubusercontent.com/8819339/180446743-2eb8e3c2-1f79-4b3c-9956-afed82593af9.png)
### Other clusters that are not mentioned above
power configuration
![image](https://user-images.githubusercontent.com/8819339/180446682-6d05e4f9-bb56-4727-ad33-ee787c9b37dc.png)

i did not make screenshots from the other clusters since they are al the same.

**Comment by Smanar** [comment]
Hello here you have a sample for a tuya 3 gangs https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6068
