### ISSUE TITLE
Paulmann ZB Spot Adapter 968.93, 955.23, 955.24

### ISSUE THREAD

**Issue by bwatconbee** [dresden-elektronik/deconz-rest-plugin#6215]
## Device

- Product name: Urail ZB Spot Adapter
- Manufacturer: Paulmann
- Model identifier: 968.93 (silver), 955.23 (white), 955.24 (black)
- Device type : 
  - Light

The adapter is available in 3 different colors, each with different identification numbers! 
Adapter is found on deConz but not switched. Only the slider for dimming is displayed. (see screenshot 6!)

## Screenshots
![image](https://user-images.githubusercontent.com/109853940/180604174-337a0a4e-148a-4984-ae30-5dcce28f4844.png)

![image](https://user-images.githubusercontent.com/109853940/180604133-3483c977-bd6f-4ab0-88d7-38a33668eafb.png)

![image](https://user-images.githubusercontent.com/109853940/180602161-b2a668e4-3df7-4013-a793-0ca1a05104e2.png)

![image](https://user-images.githubusercontent.com/109853940/180602216-a8dc2803-920e-4abf-aac0-72061678c771.png)

![image](https://user-images.githubusercontent.com/109853940/180605146-24fd76a5-bcd5-41d7-a9d2-c58aa3770dc2.png)

![image](https://user-images.githubusercontent.com/109853940/180602425-227426b1-0350-4623-b7f6-5e1fb73c74d7.png)

**Comment by Mimiix** [comment]
Can you please post om English and provide all screens?

Thanks!

**Comment by bwatconbee** [comment]
Is it better that way? Which screens are missing exactly?

**Comment by Mimiix** [comment]
Of all clusters. Either way, can you see if the rest api works correctly? I want to know if it's a phoscon or deconz issue.

**Comment by bwatconbee** [comment]
What do you mean by all clusters? The screenshot with the cluster info is there! My setup consists only of the Conbee Stick and an adapter, which I got for testing! The Rest-Api only makes sense when a device is found or is responsive! What exactly can I deliver now?

**Comment by bwatconbee** [comment]
OK! I think I found that with the API! The adapter is also visible via the API! See screenshot 5!

**Comment by Mimiix** [comment]
If you use the api, can you control using that?

The documentation on the REST API can be found here : https://dresden-elektronik.github.io/deconz-rest-doc/getting_started/

**Comment by bwatconbee** [comment]
The way I see it, there is the same result with the API! Please see the last Screenshots! 
The put commands are successfully issued but there is no reaction on the Paulmann adapter!
What else can I do?

**Comment by Mimiix** [comment]
So for whatever reason this device doesn't play by the rules of Zigbee. In that case we need all. Screenshots from each cluster in the device ( see the wiki, how to read clusters) if you don't know how.

Once you've done that, a Dev needs to look into it..

**Comment by bwatconbee** [comment]
Sorry, but it seems to work with the API! My mistake was that switching on is immediate (parameter true), but switching off takes about 2 seconds". The API feedback is immediate, the reaction on the adapter is greatly delayed!

**Comment by Mimiix** [comment]
> Sorry, but it seems to work with the API! My mistake was that switching on is immediate (parameter true), but switching off takes about 2 seconds". The API feedback is immediate, the reaction on the adapter is greatly delayed!

In that case, the bug is with phoscon.

You need to open an topic on the forums. Https://forum.phoscon.de
