### ISSUE TITLE
Xiaomi HoneyWell smoke sensors low battery

### ISSUE THREAD

**Issue by QempZor** [dresden-elektronik/deconz-rest-plugin#622]
Xiaomi Smoke detectors are reporting Battery 0% (Low battery in Homekit)
However, in the REST API config:battery is null;
![image](https://user-images.githubusercontent.com/35775426/40969527-6937ab94-68b8-11e8-8563-72f46c770c57.png)

and DeCONZ reports Power Level 100%
![image](https://user-images.githubusercontent.com/35775426/40969395-128f17e6-68b8-11e8-95dc-0df087c293b4.png)

**Comment by ebaauw** [comment]
The battery percentage in `config.battery` is read from the _Power Configuration_ cluster, not from the _Power Descriptor_ (which, I think, isn't even read at all - the sensor sure isn't mains powered).

**Comment by QempZor** [comment]
That is kinda weird, it's battery powered, indeaad. So the Power Descriptor would not be read I guess.
My other Xiaomi sensors, like the door/windows, floodsensors, and buttons are reporting 100%
Wich I also can't bbelieve, because the running for over 6 months.. and didn't lose any %

**Comment by wvuyk** [comment]
Could be possible though. Xiaomi states two years for most battery devices. Here I have had Philips motion sensors reporting 100% for over an year. Only now the Philips motion sensors start reporting 53% after more then 1 1/2 year of usage. Would not be surpirsed if Xiaomi will report 100% for some time more?

**Comment by BigWumpus** [comment]
Wait some days for a readout
