### ISSUE TITLE
Tuya TS0601 device not adding properly to deConz & not showing in Phoscon at all.

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#6248]
## Describe the bug
 Sensor not pairing fully

## Steps to reproduce the behavior
pair device

## Expected behavior
proper identification in deConz and shows up in Phoscon

## Screenshots
attached
![Tuya_deConz_TS0601](https://user-images.githubusercontent.com/1626802/183317295-b51f16ea-5438-49b1-b7ba-b655a2063218.JPG)

## Environment
 - Host system: PC
 - Running method: Windows
 - Firmware version: 26400500
 - deCONZ version: 2.18.0
 - Device: ConBee I
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
attached
[Tuya_deConzDebug_TS0601.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9277862/Tuya_deConzDebug_TS0601.txt)

**Comment by Mimiix** [comment]
Is this device supported?

**Comment by Mimiix** [comment]
Hi there,

It seems the device is not fully supported, working yet as your other device request is still open:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6063

Opening this issue as a bug, is not needed at this point as the device is not supported yet.

Closing.

Kind regards,

**Comment by Ltek** [comment]
I opened the bug because the device is recognized but doesn't work.

 I spent a lot of time working with manup on this issue and I'd like to
have it resolved. Its been ignored  over a month since any he remoted into
my system to work on it

**Comment by Mimiix** [comment]
I pinged him to check the original issue :)
