### ISSUE TITLE
Lumi Plug maeu01 - Wrong metering

### ISSUE THREAD

**Issue by basty2** [dresden-elektronik/deconz-rest-plugin#6251]
## Describe the bug
Since the update to 18.0, my aqara plug delivers the wrong active power. I am accessing the data via rest api in iobroker deconz adapter. The delivered value is 10x higher than in version 2.17 before. 
 
## Steps to reproduce the behavior
all values supplied are 10x too high. 
 
## Expected behavior
the delivered value should be 1/10 of it
 
## Screenshots
see attached. the right value should be 129W. At rest api it delivers 1292.
 
## Environment
 Host system: (PC)
 - Running method: Ubuntu
 - Firmware version: 26720700
 - deCONZ version: 2.18.00
 - Device: ConBee II
 - Do you use an USB extension cable: yes

 - model: lumi.plug.maeu01

## deCONZ Logs
not necessary
 
## Additional context
up to v.2.17 it worked fine.

here ist the rest api

  "ep": 1,
    "etag": "xxx",
    "lastannounced": "2022-08-08T07:53:35Z",
    "lastseen": "2022-08-09T07:18Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.plug.maeu01",
    "name": "OpenClose 63",
    "state": {
        "current": 0,
        "lastupdated": "2022-08-09T07:19:00.345",
        "power": 1292,
        "voltage": 0
    },
    "swversion": "09-10-2019",
    "type": "ZHAPower",
    "uniqueid": "xxx"

<img width="278" alt="image" src="https://user-images.githubusercontent.com/33844675/183589178-e54f49cc-1f74-436d-a46e-8e36d3004c8c.png">

**Comment by Mimiix** [comment]
@basty2 Can you please fill in the report as intended?

**Comment by basty2** [comment]
@Mimiix Is it so ok or do you need more information?

**Comment by Mimiix** [comment]
Is good :)

Thanks :)

**Comment by Smanar** [comment]
Hello, can you edit the file `devices\xiaomi\xiaomi_sp-euc01_smart_plug.json`

At this part

```
          "name": "state/power",
          "refresh.interval": 10,
          "read": {
            "at": "0x0055",
            "cl": "0x000C",
            "ep": 21,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0055",
            "cl": "0x000C",
            "ep": 21,
            "eval": "Item.val = Math.round(Attr.val);"
          }
```

try 

` "eval": "Item.val = Math.round(Attr.val / 10);"`

**Comment by basty2** [comment]
@Smanar  I changed the data, restarted deconz, but it is not working. Values are 10x too high.

**Comment by Smanar** [comment]
The bad value is state/power ?
Can you check if you have something in logs with the flag "DDF" ?

Can you check in the file if the modification is "persistent" ?

**Comment by basty2** [comment]
Hi @Smanar,

the bad value is state/power. I have activated the debug mode, there are some entries at DDF, but none from the affected device. The modification should be persistent, if i open the file again, the new entry still exists.

**Comment by Smanar** [comment]
>there are some entries at DDF, but none from the affected device

Ha ? The DDF status is "Gold" so I don't see why the DDF is not used for this device ...

Edit :
Ok I have found a "check line" in the DDF

```
  "comment": "DDF for device firmwares at least above 0.0.0_0022, paired with xBee I fw 0x26400500 / xBee II fw 0x266f0700 and above",
  "matchexpr": "R.endpoints.includes(0x15) && R.endpoints.includes(0x1F)",
```

I think your device don't have Endpoint 0x15 and 0x1F ?

You can remove the line "matchexpr" to remove the check, but idk what will happen an other plug with different firmware (but same model)

**Comment by basty2** [comment]
I used "//" before the line matchexpr. But it doesn't work.
the ID of the active power is 0x050B as you can see in the screenshot.

**Comment by basty2** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/33844675/184661223-8c6a1c8c-ecae-4fca-956d-1f56ac2b155e.png">
maybe this helps. 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/33844675/184661313-87c24312-1a24-43be-8cd1-582437fe752b.png">

**Comment by Smanar** [comment]
You can direclty remove the line to test.
From the log I think it explain why the DDF is not used for you.

**Comment by basty2** [comment]
ok, now it is shown at ddf. But the value is still to high. 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/33844675/184695797-55a43be0-6558-4635-a362-b067f1e1d609.png">

**Comment by Smanar** [comment]
Nice.
Change the line

`"eval": "Item.val = Math.round(Attr.val / 10);"`

And you will see difference on the same debug line.
If it work can you show all the device endpint ? It's the number on the node title (can have more than one part)

To make a better "matchexpr"

**Comment by basty2** [comment]
Hi @Smanar , 
it is still not working. here ist my data 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/33844675/185052287-c19665c0-1807-4cc2-83e9-c342dab8b97f.png">

Is this the node title? 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/33844675/185052604-76dad759-be25-42b4-988d-ca60cc0e8bf1.png">

<img width="189" alt="image" src="https://user-images.githubusercontent.com/33844675/185053421-a68574b4-5199-4077-b129-3242ae5d2256.png">

**Comment by Smanar** [comment]
Ok so you have the endpoint 0x01 and 0xF2 on yours.
If you take a look in your log

<img width="854" alt="image" src="https://user-images.githubusercontent.com/33844675/184695797-55a43be0-6558-4635-a362-b067f1e1d609.png">

Edit:
Ok so I have look better your log, and we can see `"eval": "if (Attr.val != -32768 && Attr.val != 32768) { Item.val = Attr.val; }",` but in the DDF we have `"Item.val = Math.round(Attr.val);"` it mean the device is using another DDF

The only DDF where I can see `"eval": "if (Attr.val != -32768 && Attr.val != 32768) { Item.val = Attr.val; }",` is a Sinope device.

You are sure there isn't a mistake somewhere ? with comparing the mac adress.

**Comment by basty2** [comment]
@Smanar I renamed the devices folder and copied a completly new downloaded device from the github. But also this doesnt work. What kind of mistake could it be?
I renamed the th1124zb.json to th1124zb.json.old but also this doesn't work. I dont have a sinope device. How could I campare the Mac adress? the mac adress ends with 46-58.

**Comment by Smanar** [comment]
If I m right with the flag "DDF" on debug you will see files used by devices, but as this one have a "matchexpr" field idk how it will react.

You can too on the GUI select the device (the node title) and choose "edit DDF" you will see the file used by deconz for the device.

Can be too a generic DDF (it's the defaut value), but how you have created it .... You haven't tried to edit the DDF using the editor ? https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/items/state_power_item.json

**Comment by basty2** [comment]
Hi @Smanar  . I tried edit ddf. it should be correct. 
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/33844675/185186524-913af8d5-9b92-4e17-87b1-8b43fc8b6852.png">

Here are all entries of ddf debug: 
`17:52:18:574 04:cf:8c:df:3c:76:46:58-01/attr/manufacturername expression: Item.val = Attr.val --> LUMI
17:52:18:575 04:cf:8c:df:3c:76:46:58-01-0b04/attr/manufacturername expression: Item.val = Attr.val --> LUMI
17:52:18:576 04:cf:8c:df:3c:76:46:58-15-000c/attr/manufacturername expression: Item.val = Attr.val --> LUMI
17:52:18:576 04:cf:8c:df:3c:76:46:58-01-0702/attr/manufacturername expression: Item.val = Attr.val --> LUMI
17:52:18:577 04:cf:8c:df:3c:76:46:58-1f-000c/attr/manufacturername expression: Item.val = Attr.val --> LUMI
17:52:18:578 04:cf:8c:df:3c:76:46:58/attr/manufacturername expression: Item.val = Attr.val --> LUMI
17:52:18:608 04:cf:8c:df:3c:76:46:58-01/attr/modelid expression: Item.val = Attr.val --> lumi.plug.maeu01
17:52:18:608 04:cf:8c:df:3c:76:46:58-01-0b04/attr/modelid expression: Item.val = Attr.val --> lumi.plug.maeu01
17:52:18:609 04:cf:8c:df:3c:76:46:58-15-000c/attr/modelid expression: Item.val = Attr.val --> lumi.plug.maeu01
17:52:18:609 04:cf:8c:df:3c:76:46:58-01-0702/attr/modelid expression: Item.val = Attr.val --> lumi.plug.maeu01
17:52:18:609 04:cf:8c:df:3c:76:46:58-1f-000c/attr/modelid expression: Item.val = Attr.val --> lumi.plug.maeu01
17:52:18:609 04:cf:8c:df:3c:76:46:58/attr/modelid expression: Item.val = Attr.val --> lumi.plug.maeu01
17:52:21:264 04:cf:8c:df:3c:76:46:58-01/state/on expression: Item.val = Attr.val --> true
17:52:21:563 04:cf:8c:df:3c:76:46:58-01-0b04/state/power expression: if (Attr.val != -32768 && Attr.val != 32768) { Item.val = Attr.val; } --> 1467
17:52:44:402 04:cf:8c:df:3c:76:46:58-01-0702/state/consumption expression: Item.val = Attr.val --> 1448266
`

**Comment by basty2** [comment]
there is also no change, if i change to (Attr.val / 100). 
Is this a problem only for me or is it a problem for several people?

**Comment by Smanar** [comment]
Ok, so there is something strange.
I will ask for tips to others devs.

If you make a "hot reload" with same log enabled "DDF" (or perhaps "info" "info_l2"), you will see the file used used by deconz for this device, not possible it use the same ....

**Comment by SwoopX** [comment]
Please delete any modified DDF, restart deconz and re-pair the device. The device exposes incorrect clusters when a response is not properly received during pairing.

**Comment by basty2** [comment]
Hi @SwoopX. I deleted and reinstalled the complete devices folder. I tried to repair the device more than 20 times. I have now a new problem. The power value is not shown in electric metering, but In a new area. 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/33844675/185505861-9800f064-62bb-4b7d-9c72-3a3296cd20b8.png">
7 Watt should be the right Power Value at Analog Input Cluster: 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/33844675/185505966-6e4c2667-26de-4610-8d4e-0882b3c1bb28.png">

**Comment by SwoopX** [comment]
The "problem" is a works as designed. Regardless, the device still doesn't look right and my gut feeling says it runs on a rather old firmware. It should look like this:

![grafik](https://user-images.githubusercontent.com/4005212/185507692-14743964-8b1c-4613-ad22-6df4cdcee9e5.png)

Please activate the OTA update plugin under plugins (in the menu bar), select the device and then select OTA update pane (bottom left). Then press the query button until you get some result.

**Comment by SwoopX** [comment]
Firmware can be found here and must be placed in the otau folder to update
https://github.com/Koenkk/zigbee-OTA/raw/master/images/Xiaomi/20211209165104_OTA_lumi.plug.maeu01_0.0.0_0041_20211206_0C22EC.ota

**Comment by basty2** [comment]
@SwoopX Very strange. Because everythings worked until 2.17. But this was the solution. I got all the values. Thanks.

**Comment by softwerker64** [comment]
Looks like I'm vacing the same problem :-(
I updated the "lumi.plug.maeu01" with the [new firmware referenced above](https://github.com/Koenkk/zigbee-OTA/raw/master/images/Xiaomi/20211209165104_OTA_lumi.plug.maeu01_0.0.0_0041_20211206_0C22EC.ota) and the device reports "09-10-2019" as SW-Version in Hue-Essentials.
However, the value "state.power" still seems to be ten times too high. In Hue-Essentials and via REST.

Any ideas? Thanks in advance!

**Comment by softwerker64** [comment]
Installed newest update of deconz on my Raspberry with no luck, REST still reports these values (where power is ten times too high):
current: 0
power: 10
voltage: 0

"apt" reports this package: "deconz/unknown,now 2.19.03-raspbian-buster-stable armhf"

**Comment by grimmaldus** [comment]
I have been experiencing the same issue for several years and have been stuck using version 2.17.1 since then. Could someone please explain what has changed in the newer versions? Is there any specific reason for this issue? Are there any known solutions or workarounds available?

Any help would be greatly appreciated. Thank you!

**Comment by Smanar** [comment]
Hello, are you using the new firmware ? (for the device, not for the Gateway)

**Comment by grimmaldus** [comment]
I’m using the file OTA_lumi.plug.maeu01_V32_20200922_C11F8A.20200924102946.ota in deCONZ, but it shows as 0x00000020. I couldn’t find a newer version. When I want to use the latest version, 2.28.1 deCONZ, the only way to get the correct values is by changing the DDF.

**Comment by Smanar** [comment]
Have checked the OTA file and yes this version is the 0x20.
Do you have access to the GUI to compare how look your device in deconz ?

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-smart-plugs-not-working-correctly

Perhaps need to delete it and re-include it (as the old one is managed by legacy code, and the new one by DDF, perhaps a conflict)

**Comment by grimmaldus** [comment]
> Have checked the OTA file and yes this version is the 0x20. Do you have access to the GUI to compare how look your device in deconz ?

![image](https://github.com/user-attachments/assets/9c361d9a-3969-4e67-bf4b-c7eb9bf6e06b) 

> 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-smart-plugs-not-working-correctly

Oh nice I'm gonna try this file I couldn't get to it before. And let you know. 

> 
> Perhaps need to delete it and re-include it.

Yea I did it before after I updated.

**Comment by Smanar** [comment]
Nope, you need to compare the clusters, the first image on the wiki page.
And from that I  have checked you have the last one, the 0x20.

You have "DDF" written on the node corner ?

**Comment by grimmaldus** [comment]
> Nope, you need to compare the clusters, the first image on the wiki page. And from that I have checked you have the last one, the 0x20.
Thanks for your response. I’ve checked the clusters, and unfortunately, they don’t match. Regarding the DDF, I’m not entirely sure where I should be looking for it in the GUI since I couldn’t find any reference to it in the wiki. If by any chance you are referring to the "Edit DDF" option in the right-click node menu, then yes, I do have that, and that’s actually how I managed to edit the DDF and fix the initial issue.
> You have "DDF" written on the node corner ?
Additionally, I noticed that the file that led me to the 0x00000020 cluster has a different hash compared to the one on the wiki page. I wasn’t able to locate it earlier due to the broken link, but I will now try updating the firmware for the lumi.plug.maeu01 following the wiki page's firmware guide.

**Comment by Smanar** [comment]
![192047220-afac610d-f814-41bc-8a7d-7f2f9ce90908](https://github.com/user-attachments/assets/37bd9d74-fea0-404b-98fe-28a85cfef082)

On this picture you can see Endpoint 01/15/1F/F2 and on the Endpoint 0x15 and 0x1F, you can see the cluster 0x000C
You need them, for the DDF can work.

`  "matchexpr": "(R.endpoints.indexOf(0x15) !== -1) && (R.endpoints.indexOf(0x1F) !== -1);",`

Else can you show how look your device ?

**Comment by grimmaldus** [comment]
> Else can you show how look your device ?

![image](https://github.com/user-attachments/assets/0aad38da-ff2a-4c3c-ad2a-4be0f32a91a0)

**Comment by Smanar** [comment]
So yes I can confirm, the DDF will never work, you have an old version.
But how you can have a version = 0x20 ? Or there is a OTA version above, but I don't see it on the github.

`DDF for device firmwares at least above 0.0.0_0022, paired with xBee I fw 0x26400500 / xBee II fw 0x266f0700 and above`

Can you check the swbuild on the cluster 0x0000 'basic" ?

**Comment by grimmaldus** [comment]
> Can you check the swbuild on the cluster 0x0000 'basic" ?

![image](https://github.com/user-attachments/assets/7e275f75-fc31-49d7-a8ab-5592f99804ea)

> And BTW why you have "DDF" writted on the node corner ? Can you make "edit DDF" to see wich one DDF is used by the editor ? (It's written on the titlebar")

I'm not very familiar with the deCONZ GUI, to be honest, so I'm not sure why it shows up there, but I have edited the DDF for these devices.

![image](https://github.com/user-attachments/assets/825a3813-b8a4-45aa-95fd-d10de8078468)

**Comment by bluemoehre** [comment]
I just upgraded some plugs from v41 to the new v45 of Aqara / Xiaomi and ran again into this annoying problem. I don't remember how I solved that in the past =/

Would be absolutely happy if we can fix this once for the future.

**Comment by Smanar** [comment]
>I'm not very familiar with the deCONZ GUI, to be honest, so I'm not sure why it shows up there, but I have edited the DDF for these devices.

Yes, I m seing, idk how is the rest of the DDF, but your device can't work at all like the existing DDF (he don't use same cluster), so if you remove some line to force deconz use the DDF, it will not work.
Need to create a full DDF, but ATM, users just update their device with more recent firmware to use the last DDF, Idk why on your device you have a version 0x20 but an old firmware running.

>Deconz always should respect the multiplier properties (eg. 0x0605 - AC Power Divisor) to render the value.

If it can be respected by brand, and for information this device use now the cluster 0x000C, so no multiplier/diviser.

**Comment by bluemoehre** [comment]
> If it can be respected by brand, and for information this device use now the cluster 0x000C, so no multiplier/diviser.

Based on what I see, that's not true. I already deleted and reconnected the plug from the network including a full device reset. Still I can confirm my product `lumi.plug.maeu01` @ firmware `v45` still uses divisors / multipliers. 

Do I miss something?

**Comment by Smanar** [comment]
Last version is this one

![192047220-afac610d-f814-41bc-8a7d-7f2f9ce90908](https://github.com/user-attachments/assets/37bd9d74-fea0-404b-98fe-28a85cfef082)

**Comment by bluemoehre** [comment]
> Last version is this one

this looks like < v43 to me.

v45:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/e9e89cff-e9bc-4681-bd9c-411f8d37aefb">

**Comment by Smanar** [comment]
To compare with others, can you share the device swbuild (attribute 0x4000 on cluster 0x0000) and the firmware version from ota cluster if you can ?

**Comment by bluemoehre** [comment]
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5dba5367-db99-4134-b810-a1312f3358bd">

(Don't see any 0x4000 in 0x0000)

**Comment by bluemoehre** [comment]
Tried to go down the rabbit hole and looks like the DDF here:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/xiaomi/xiaomi_sp-euc01_smart_plug.json

is causing issues with v45 and needs to be modified to match < v45 only. 

A new DDF is required for v45(+), also respecting Divisors, Multipliers, and fixing SW Version field.

**Comment by Smanar** [comment]
Ok, so idk what happen and what is the last version we need to use but can try this DDF

```
{
    "schema": "devcap1.schema.json",
    "manufacturername": "$MF_LUMI",
    "modelid": "lumi.plug.mmeu01",
    "vendor": "Xiaomi",
    "product": "Smart plug",
    "sleeper": false,
    "status": "Gold",
    "matchexpr": "(R.endpoints.indexOf(0x15) == -1) && (R.endpoints.indexOf(0x16) == -1);",
    "subdevices": [
        {
            "type": "$TYPE_SMART_PLUG",
            "restapi": "/lights",
            "uuid": [
                "$address.ext",
                "0x01"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "at": "0x00f7",
                        "ep": 1,
                        "fn": "xiaomi:special",
                        "idx": "0x08",
                        "script": "xiaomi_swversion.js"
                    },
                    "read": {
                        "fn": "none"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "state/alert",
                    "description": "The currently active alert effect.",
                    "default": "none"
                },
                {
                    "name": "state/on"
                },
                {
                    "name": "state/reachable"
                }
            ]
        },
        {
            "type": "$TYPE_POWER_SENSOR",
            "restapi": "/sensors",
            "uuid": [
                "$address.ext",
                "0x01",
                "0x0B04"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "at": "0x00f7",
                        "ep": 1,
                        "fn": "xiaomi:special",
                        "idx": "0x08",
                        "script": "xiaomi_swversion.js"
                    },
                    "read": {
                        "fn": "none"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "config/temperature"
                },
                {
                    "name": "state/current"
                },
                {
                    "name": "state/lastupdated"
                },
                {
                    "name": "state/power"
                },
                {
                    "name": "state/voltage"
                }
            ]
        },
        {
            "type": "$TYPE_CONSUMPTION_SENSOR",
            "restapi": "/sensors",
            "uuid": [
                "$address.ext",
                "0x01",
                "0x0702"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "at": "0x00f7",
                        "ep": 1,
                        "fn": "xiaomi:special",
                        "idx": "0x08",
                        "script": "xiaomi_swversion.js"
                    },
                    "read": {
                        "fn": "none"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "config/temperature"
                },
                {
                    "name": "state/consumption"
                },
                {
                    "name": "state/lastupdated"
                }
            ]
        }
    ],
    "bindings": [
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0006",
            "report": [
                {
                    "at": "0x0000",
                    "dt": "0x10",
                    "min": 1,
                    "max": 300
                }
            ]
        },
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0702",
            "report": [
                {
                    "at": "0x0000",
                    "dt": "0x25",
                    "min": 1,
                    "max": 300,
                    "change": "0x00000001"
                }
            ]
        },
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0B04",
            "report": [
                {
                    "at": "0x050B",
                    "dt": "0x29",
                    "min": 1,
                    "max": 300,
                    "change": "0x00000001"
                },
                {
                    "at": "0x0505",
                    "dt": "0x21",
                    "min": 1,
                    "max": 300,
                    "change": "0x00000064"
                },
                {
                    "at": "0x0508",
                    "dt": "0x21",
                    "min": 1,
                    "max": 300,
                    "change": "0x00000064"
                }
            ]
        }
    ]
}
```

It will work with old cluster, all is by defaut because I realy don't have idea of what is working or not on this version.
So vlaues will probably need to be adapted.

**Comment by bluemoehre** [comment]
For some reason I cannot get the DDF working properly. Already build my own one, and can see in deCONZ it's there and assigned. But in API output is no change at all. Already tried to set static values to power attributes etc. But again, no effect. 

So, first I have to find out what's wrong with the DDF / JSON files.

**Comment by Smanar** [comment]
Perhaps you miss the bind/report ?

**Comment by bluemoehre** [comment]
What exactly do you mean with "bind/report"? I change the JSON and then restart the service - which I assume should load the newest version. 
I can see changes in the DDF Editor but not in the API response.

**Comment by Smanar** [comment]
The last part on DDF

```
                {
                    "at": "0x0508",
                    "dt": "0x21",
                    "min": 1,
                    "max": 300,
                    "change": "0x00000064"
                }
```

Or you mean it's not an update issue, but they are not present at all in the API ?

Deconz create new entries only if the gateway is in permit join, so can need to delete and re-include the device if there is too much difference beetween the 2 versions.

**Comment by bluemoehre** [comment]
Just for safety I already re-added the device after upgrading the firmware. So I guess these prominent changes shown in my screenshots are by firmware. 
Still the issue is, that changing the DDF expressions to calculate values correctly are not reflected in API output, while at the same time I can see DDF changes in deCONZ UI / editor. I have no clue what's wrong this time. Neither restarting the service or hot-reloading the DDF does help.

**Comment by Smanar** [comment]
Have you tried the logs ? In deconz/help/debug view ? with flag "DDF", and if needed "info" + "info_l2"

**Comment by bluemoehre** [comment]
Yes, the correct file is assigned, as far as I see it in the logs. 

To make the problem more interesting: 
I upgraded a second Plug to v45 and can clearly see some bug in Phoscon / API, because the UI still shows old firmware version for that one, also some Ampere + Voltage values, which are not available in deCONZ itself. Tried to clear the cache of the browser, but no effect as well. Using Postman these values including wrong version number are still provided by the API. 

Without being able to rely on the API output, it will be hard to fix a value, since I do not know atm where data got stucked in the whole chain.

**Comment by Smanar** [comment]
> in Phoscon / API, because the UI still shows old firmware version for that one

Yes deconz don't ask for swbuildID every time, so it can have memorised an old one.


>EDIT2: seems like deCONZ assigned different DDFs to each of the plugs. My one in /opt/deconz/devices to the first, and another one from /usr/share/deconz/devices/xiaomi to the second.

And it's same plugs ? Same clusters used ? there is no differences ? And yes there is a problem in deconz, you need to have only 1 DDF for a couple manufacturename/Modelid else deconz can pick a random one, even with a flag status=draft.

**Comment by bluemoehre** [comment]
I removed my custom file, then used grep to search everywhere in deCONZ for a conflict, which was not the case. Re-adding all Plugs, same HW, same SW... but now it's like this:

<img width="269" alt="image" src="https://github.com/user-attachments/assets/077fdb1d-381b-4d76-ba99-477049172fdf">

I don't see how this can not be an internal bug in deCONZ. Debug log says that single plug does NOT match any DDF, while the other two do match.

**Comment by Smanar** [comment]
It mean they are not same device.
One have endpoints 0x15 / 0x1F and not the other (false = not present DDF not used).
If they have them, can be a timing issue, deconz check for endpoint before having asked for them.

**Comment by bluemoehre** [comment]
@Smanar in the meanwhile I found this is actually some (cahcing) bug in deCONZ.

**Comment by Smanar** [comment]
Ha yes, and this issue is realy not good for yours problems ....

**Comment by francescopeloi** [comment]
@bluemoehre did you fix it somehow? I've got 5 `lumi.plug.maeu01` all bought together, 3 are shown as `DDF` and they are working well, 2 are not and they misbehave (not showing all entities, losing entities after a restart, and things like that). I am on the last available firmware (45) with all of them. I tried to re-pair it multiple times but nothing. Also the other 3 that are working I had to re-pair multiple times to get them to work, but with these last 2 it's not working.

<img width="1201" height="215" alt="Image" src="https://github.com/user-attachments/assets/0c8fe34b-64a2-4f77-a240-08d8327d0065" />

If I right click on the 2 that have no `DDF` label, I can actually see "Edit DDF" 🤷‍♂️ 

when pairing I see:

<img width="1156" height="92" alt="Image" src="https://github.com/user-attachments/assets/6053e4c7-cb50-45cc-8470-0726721974c0" />
<img width="1134" height="67" alt="Image" src="https://github.com/user-attachments/assets/5a8d4e5c-c402-49b1-ab7d-f4556d91b109" />

**Comment by Smanar** [comment]
Try updating them https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-smart-plugs-not-working-correctly

**Comment by francescopeloi** [comment]
> Try updating them https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-smart-plugs-not-working-correctly

thanks @SwoopX but update what? As said I am on the latest firmware. I did read that document before posting but I think I've done all what's suggested in there.

**Comment by bluemoehre** [comment]
@francescopeloi  I first started replacing them with IKEA plugs because they never became stable. 
However, since I also experienced other problems with deCONZ (it began hanging regularly for over a year), I was very frustrated that all these issues remained unresolved for so long. In the end, I took the hard route and fully migrated to Z2M, also swapping the coordinator for a different brand. 
I can't tell whether my setup became buggy - it worked fine for many years - but it felt like there have been too many issues with deCONZ at that time. 
Now everything runs like a breeze on Z2M - including the Aqara/Lumi plugs. I even returned most of the IKEA plugs (you can do within 365 days ;)

I know that's not the answer you were hoping for, but this way I could solve the problem.

EDIT:
Don't get me wrong: I'm not recommending to buy more of the Aqara/Lumi plugs - I just couldn't return the ones I had =)

**Comment by francescopeloi** [comment]
> [@francescopeloi](https://github.com/francescopeloi) I first started replacing them with IKEA plugs because they never became stable. However, since I also experienced other problems with deCONZ (it began hanging regularly for over a year), I was very frustrated that all these issues remained unresolved for so long. In the end, I took the hard route and fully migrated to Z2M, also swapping the coordinator for a different brand. I can't tell whether my setup became buggy - it worked fine for many years - but it felt like there have been too many issues with deCONZ at that time. Now everything runs like a breeze on Z2M - including the Aqara/Lumi plugs. I even returned most of the IKEA plugs (you can do within 365 days ;)
> 
> I know that's not the answer you were hoping for, but this way I could solve the problem.
> 
> EDIT: Don't get me wrong: I'm not recommending to buy more of the Aqara/Lumi plugs - I just couldn't return the ones I had =)

Thank you for your honest answer @bluemoehre

**Comment by Smanar** [comment]
Deconz reconise device using the manufacture name and the model ID, if they are same device and the DDF is not used the problem is from the firmware.
There is a check in the DDF to see if it's a new or old version.

`  "matchexpr": "(R.endpoints.indexOf(0x15) !== -1) && (R.endpoints.indexOf(0x1F) !== -1);",`

The DDF is only used if the device have endpoint 0x15 and 0x1F

**Comment by francescopeloi** [comment]
Where can I check those endpoints?

All the devices (3 working, 2 broken) have the same firmware:
<img width="1113" height="307" alt="Image" src="https://github.com/user-attachments/assets/fa03f4e2-410b-4756-9e01-b39a15961603" />

the firmware is: https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/images/Lumi/20240719174937_OTA_lumi.plug.maeu01_0.0.0_0045_20240719_958E71.ota

**Comment by Smanar** [comment]
Just clic on the "+" on the node, it's numbers on "title bar".
You have try to restarted deconz ? perhaps something it's not taken into account, for me same firmware mean devices need to have same endpoint

I m seing  a remark about the coordinator firmware too

`  "comment": "DDF for device firmwares at least above 0.0.0_0022, paired with xBee I fw 0x26400500 / xBee II fw 0x266f0700 and above",`

**Comment by francescopeloi** [comment]
I've got a RaspBee 2 on the latest firmware version.
I've restarted deconz many times.

I clicked on the `+` on the nodes (left one not working (no DDF label), right one working (with DFF label)), sorry I am not getting where I should look at for endpoints

<img width="737" height="798" alt="Image" src="https://github.com/user-attachments/assets/0d06384a-82d8-4c88-af94-2b7e81f38acb" />

**Comment by Smanar** [comment]
So they are definitively same (and both need to be managed by DDF)
Just to be sure can you check if the manufacture name and the model id are same ?

If I m right a device included using legacy code will use the DDF when the DDF exist, even the DDF was not present at start, but you can try to remove one of device that don't use the DDF and re-include it.

**Comment by francescopeloi** [comment]
> So they are definitively same (and both need to be managed by DDF) Just to be sure can you check if the manufacture name and the model id are same ?

yes, both have manufacturer name `LUMI` and model id `lumi.plug.maeu01`

> If I m right a device included using legacy code will use the DDF when the DDF exist, even the DDF was not present at start, but you can try to remove one of device that don't use the DDF and re-include it.

I've done this tens of times unfortunately, but when I re-pair one of the devices that don't have the DDF label, they always come up again without the DDF label

**Comment by Smanar** [comment]
The device can make too long time to expose the neeeded cluster, and the DDF check fail ?

I m seing 2 workaround to test.
- Edit the file devices\xiaomi\xiaomi_sp-euc01_smart_plug.json and remove the check line
`  "matchexpr": "(R.endpoints.indexOf(0x15) !== -1) && (R.endpoints.indexOf(0x1F) !== -1);",`
- Put again the networw in permit join, using Phoscon / add new device, without deleting the device (like that Deconz already have some information about the device) and ask for descriptor/endpoind (using right clic on the node title, you will have a menu), this will trigger a new inclusion.

**Comment by francescopeloi** [comment]
@Smanar during this weekend, due to electricity work, I had to restart many times the rpi running deconz. With my surprise after I checked this evening, now all the devices come up with the DDF label 🤷‍♂️  

Thanks for your help with this @Smanar , maybe the fix is to restart tens of times 🤷‍♂️ 

I also had a new aqara smart plug hanging, that I wanted to pair after I fixed the ones I had paired already. Tried to pair the new one now and it came up with the DDF label straightaway 🤷‍♂️ 

I don't know what to say, but now everything seems to work.

**Comment by Smanar** [comment]
The procedure is "event based", so a reboot can change the event order and make magic ...

**Comment by francescopeloi** [comment]
I bought another one as I need to measure more things but... I was back to the same problem, never recognizing DDF. Re-paired 5 times and nothing.  With the previous experience, I restarded deconz a few times, and it got recognised at the third restart. Writing just to help if anyone else has this problem.

**Comment by francescopeloi** [comment]
@Smanar now after some more reboots due to other causes, some other aqara smart plugs have disappeared from deconz (a problem that I used to have also before). When looked for new devices they re-appear with their old name, but now they lost the DDF label (they had it before) and also all the energy report fields. The device is there but the reporting entity are missing.

These aqara plugs are a mess in deconz. I've bought some Nous A7Z and they are working much better (for the reader: they are recognised straightaway with DDF by deconz, they are cheaper and they work at 16A too).

Is there anything that can be done to fix the aqara smart plugs? They clearly have some weird issues that needs to be investigated further.

**Comment by Smanar** [comment]
@francescopeloi try to remove the version check in the DDF. (as all your devices have same firmwares)

**Comment by francescopeloi** [comment]
@Smanar I can do that but is that a real fix? The DDF was recognised, and then it's not, and then it's recognised again, and then not again. Something is going really wrong here.

**Comment by Smanar** [comment]
The detection is event based, if I m right sometime the device show all endpoint, sometime it don't have time.
With this "hack" (will work only for you as you have all same devices) the DDF will we used all the time, as deconz will check only with modelID and Manufacture name.

If I m wrong there is another problem, but I don't see it.
