### ISSUE TITLE
Wall switch - zigfred uno (ZFU-1D-CH)

### ISSUE THREAD

**Issue by WhistleMaster** [dresden-elektronik/deconz-rest-plugin#6258]
## Device

- Product name: zigfred uno
- Manufacturer: Siglis
- Model identifier: zigfred uno
- Device type : Switch

## Screenshots

<img width="642" alt="Screenshot 2022-08-11 at 16 51 31" src="https://user-images.githubusercontent.com/1544568/184162663-fb1bfd33-7813-4655-882b-7fab01d71370.png">

### (Firmware < 26)
<img width="320" alt="Screenshot 2022-08-11 at 16 51 37" src="https://user-images.githubusercontent.com/1544568/184162673-c4d2d586-12cd-45d0-96b1-dcac338e33f2.png">

### (Firmware >= 26)
<img width="318" alt="Screenshot 2022-08-14 at 12 32 45" src="https://user-images.githubusercontent.com/1544568/184532949-aca82397-a187-460b-b67c-23bb13fe9015.png">

### Basic
<img width="607" alt="Screenshot 2022-08-11 at 16 52 40" src="https://user-images.githubusercontent.com/1544568/184162945-b7a03619-739e-41e3-bf62-1debd49f5344.png">

### Identify
<img width="624" alt="Screenshot 2022-08-11 at 16 53 26" src="https://user-images.githubusercontent.com/1544568/184163090-5948b1fd-0617-4b29-804c-e66f748d6645.png">

### Alarms
N/A

### Device Temperature
N/A

### Groups
<img width="611" alt="Screenshot 2022-08-11 at 16 54 09" src="https://user-images.githubusercontent.com/1544568/184163260-9b5b22a1-102d-4bdc-9f19-7646fc531161.png">

### Scenes
<img width="618" alt="Screenshot 2022-08-11 at 16 54 34" src="https://user-images.githubusercontent.com/1544568/184163376-fe7d7d97-15d0-4994-a290-3318b397a1de.png">

### On/Off
<img width="619" alt="Screenshot 2022-08-11 at 16 54 57" src="https://user-images.githubusercontent.com/1544568/184163638-c5315cc5-6604-4652-a8cf-283cd327f88d.png">
<img width="620" alt="Screenshot 2022-08-11 at 16 55 12" src="https://user-images.githubusercontent.com/1544568/184163643-c65a02c0-f754-40c8-ada2-0582096ff941.png">

### Level Control
<img width="611" alt="Screenshot 2022-08-11 at 16 55 41" src="https://user-images.githubusercontent.com/1544568/184163740-6132f79d-a28e-4517-88fb-a7b2715d9e1e.png">

### Color Control
<img width="618" alt="Screenshot 2022-08-11 at 16 56 24" src="https://user-images.githubusercontent.com/1544568/184164124-83be6b9f-a1f0-4e66-afa2-93d560040020.png">
<img width="614" alt="Screenshot 2022-08-11 at 16 56 33" src="https://user-images.githubusercontent.com/1544568/184164131-8df7057d-0461-40e3-9a7a-68d5baab66a9.png">
<img width="614" alt="Screenshot 2022-08-11 at 16 56 43" src="https://user-images.githubusercontent.com/1544568/184164133-889cd455-e8ce-4628-9439-f838380ffd80.png">
<img width="617" alt="Screenshot 2022-08-11 at 16 56 53" src="https://user-images.githubusercontent.com/1544568/184164136-51c78d2a-ca1f-4c68-91fc-aec904ea8901.png">
<img width="611" alt="Screenshot 2022-08-11 at 16 57 06" src="https://user-images.githubusercontent.com/1544568/184164139-65d66104-ae63-4653-a6c2-9ebc575c9511.png">
<img width="612" alt="Screenshot 2022-08-11 at 16 57 16" src="https://user-images.githubusercontent.com/1544568/184164143-259d5919-8f76-44a0-8fc0-d346b2baecbf.png">

### Simple Metering
N/A

### Diagnostics
N/A

### Other clusters that are not mentioned above
0x0345 Unknown (Firmware < 26)
0xFC42 Unknown (Firmware >= 26)
<img width="643" alt="Screenshot 2022-08-11 at 16 58 31" src="https://user-images.githubusercontent.com/1544568/184164407-7fa91906-4f32-4c2e-a06e-fbaca6269ea0.png">

### Basic
<img width="630" alt="Screenshot 2022-08-11 at 17 00 02" src="https://user-images.githubusercontent.com/1544568/184164754-36bba69f-b942-423d-a04c-f3f8aef0e6c4.png">

### Identify
<img width="628" alt="Screenshot 2022-08-11 at 17 00 20" src="https://user-images.githubusercontent.com/1544568/184164810-2750cf67-b25d-48fe-a0d7-0aedd5b427f5.png">

### Alarms
N/A

### Device Temperature
N/A

### Groups
<img width="616" alt="Screenshot 2022-08-11 at 17 00 43" src="https://user-images.githubusercontent.com/1544568/184164898-c06987d6-db84-45e9-bcd8-c29f389a9e34.png">

### Scenes
<img width="611" alt="Screenshot 2022-08-11 at 17 01 04" src="https://user-images.githubusercontent.com/1544568/184164958-6735fca1-eda0-4471-8be1-915d987ec875.png">

### On/Off
<img width="617" alt="Screenshot 2022-08-11 at 17 01 25" src="https://user-images.githubusercontent.com/1544568/184165073-bf6b9db4-b954-48cd-8760-deb84fef787c.png">
<img width="610" alt="Screenshot 2022-08-11 at 17 01 35" src="https://user-images.githubusercontent.com/1544568/184165078-84d36a52-1016-4d2a-8733-972b30b3c2fe.png">

### Level Control
N/A

### Color Control
N/A

### Simple Metering
N/A

### Diagnostics
N/A

### Other clusters that are not mentioned above
N/A

### Basic
<img width="635" alt="Screenshot 2022-08-11 at 17 02 21" src="https://user-images.githubusercontent.com/1544568/184165258-40ab5e74-2756-4550-8a88-68ce60392aa5.png">

### Identify
<img width="633" alt="Screenshot 2022-08-11 at 17 02 40" src="https://user-images.githubusercontent.com/1544568/184165320-8c65dfc3-683a-462c-a173-4e30ce7cf5c1.png">

### Alarms
N/A

### Device Temperature
N/A

### Groups
<img width="633" alt="Screenshot 2022-08-11 at 17 02 40" src="https://user-images.githubusercontent.com/1544568/184165512-8db8a62a-3fc8-4c9e-a67d-c0931b9cc1b5.png">

### Scenes
<img width="617" alt="Screenshot 2022-08-11 at 17 03 05" src="https://user-images.githubusercontent.com/1544568/184165427-57e41f0a-90c8-465d-9106-98e232d8a094.png">

### On/Off
<img width="614" alt="Screenshot 2022-08-11 at 17 04 00" src="https://user-images.githubusercontent.com/1544568/184165610-6dcdb0ef-7b6c-459e-abe7-f1cd6c6b22bd.png">
<img width="606" alt="Screenshot 2022-08-11 at 17 04 05" src="https://user-images.githubusercontent.com/1544568/184165613-dc397750-f717-49b4-b63c-020318fba5ca.png">

### Level Control
<img width="616" alt="Screenshot 2022-08-11 at 17 04 26" src="https://user-images.githubusercontent.com/1544568/184165697-e1479074-c4f1-48a7-80d2-f4eb8d507b0f.png">

### Color Control
N/A

### Simple Metering
N/A

### Diagnostics
N/A

### Other clusters that are not mentioned above
N/A

--- 

Device documentation (in German only): https://docs.zigfred.ch/uno/

According to https://www.zigbee2mqtt.io/devices/ZFU-1D-CH.html, it should be able to get additional information, such as:
- button_1_single
- button_1_double
- button_1_hold
- button_1_release
- button_2_single
- button_2_double
- button_2_hold
- button_2_release
- button_3_single
- button_3_double
- button_3_hold
- button_3_release
- button_4_single
- button_4_double
- button_4_hold
- button_4_release

The device developer, @Atokulus, has provided what's needed for Z2M:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/siglis.js
https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts

**Comment by WhistleMaster** [comment]
Seems like the button event are in this unknown cluster **0xFC42**. According to Z2M:

```
    manuSpecificSiglisZigfred: {
        ID: 0xFC42,
        manufacturerCode: 0x129C,
        attributes: {
            buttonEvent: {ID: 0x0008, type: DataType.uint32},
        },
        commands: {},
        commandsResponse: {},
    },
```

Is that something that could be done through DDF ?

**Comment by Smanar** [comment]
So from that I m reading :
- It use the endpoint 0x06 for the realy
- It use the endpoint 0x07 for the dimmer
- It use the endpoint 0x05 for the buttonevent

The problem is wich one cluster are used for the buttonevent ?

On Z2M they are binding the onoff, the setlevel and the manufacture one, but from here it seem all event are using only the manufacture cluster https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/siglis.js#L11

To make short, for me, for buttonevent you need to use the legacy code OR a DDF script.
The legacy code use the xml file, for exemple

`[1, "0x01", "SENGLED", "COMMAND_0", "1", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "On (single press)"],`

And the code check for mode, endpoint, cluster and ZCL command
So if you have a different ZCL command for each buttonpress, you can use the legacy code.
Else it s possible to make a short JS code (can take the same used in z2m project with some adapation) to make the state/buttonevent managed by DDF for exemple like this switch https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/legrand/wireless_scenes_command.json

To check if it possible the easier way for me, is starting a basic DDF, enable log in deconz with "info" and "info_l2' make all action on button and see the result in logs.
You will see error message but with usefull informations.

**Comment by WhistleMaster** [comment]
Thanks for your jumping here ! 

Just to add a point: the endpoint 0x05 is controlling a little LED on the device itself:
![Zigfred-Uno-3](https://user-images.githubusercontent.com/1544568/184946740-30fc179e-86ca-46bd-b0ba-4efda79063e6.jpg)

> The problem is wich one cluster are used for the buttonevent ?

From what I understand, the unknown cluster **0xFC42** is the one used for the events. See [from Z2M:](https://github.com/Koenkk/zigbee-herdsman/blob/6d43a67eefc5dd97641014c11a5295c3b6e518be/src/zcl/definition/cluster.ts#L4780):

```
    manuSpecificSiglisZigfred: {
        ID: 0xFC42,
        manufacturerCode: 0x129C,
        attributes: {
            buttonEvent: {ID: 0x0008, type: DataType.uint32},
        },
        commands: {},
        commandsResponse: {},
    },
```

Seems that there is an attribute (0x0008) which give then:

```
const button = buttonEvent & 0xff;
const state = (buttonEvent >> 8) & 0xff; 
```

**Comment by WhistleMaster** [comment]
Could it be something like that, with DDF:

```
        {
          "name": "state/buttonevent",
          "parse": {
            "at": "0x0008",
            "cl": "0xfc43",
            "ep": 5,
            "eval": "Item.eval",
            "fn": "zcl",
            "mf": "0x129c"
          }
        }
```

And the eval part would be something like Z2M ?

**Comment by Smanar** [comment]
Will be better to use an external script

`"script": "zigfrede.js"`

And yes Z2m use JS in their code, so we can mimic it, I can help you for that, but not sure we need it.
Perhaps it s not usefull and can use the legacy code with just editing the XML file.
Z2m use this script but if all actions are done only with the manufacture name, why they have bind the other cluster, so I prefer test before.

Make a basic DDF just with the ZHASwitch and check logs to be sure.

```
{
    "schema": "devcap1.schema.json",
    "manufacturername": "Siglis",
    "modelid": "zigfred uno",
    "product": "xxxxxxxxx",
    "status": "Gold",
    "subdevices": [
        {
            "type": "$TYPE_SWITCH",
            "restapi": "/sensors",
            "uuid": [ "$address.ext", "0x05", "0x0006"],
            "items": [
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion"
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/battery",
                    "awake": true
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "state/lastupdated"
                },
                {
                    "name": "state/buttonevent"
                }
            ]
        }
    ]
}
```

(There is no bind yet in this json, probably need them)

**Comment by WhistleMaster** [comment]
Thanks for the reply ! I've tried the DDF with the correct log options, unfortunately, there is nothing in the log about the events when the buttons are pressed, see attached file (I've filtered on the node id):

[_deconz_logs.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9367981/_deconz_logs.txt)

**Comment by Smanar** [comment]
It's not deconz logs.

On deconz take a look in deconz / help / debug view, with enabling flags "info" and "info_l2", then press a button.

BTW the device is reconized in deconz with the DDF ? You have a new sensor visible (for exemple in phoscon / help/ api information / sensor (I haven't see it in your log, can just load the DDF and make a "hot reload" in the DDF editor menu)

**Comment by Smanar** [comment]
As eval try

`"Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(1)"`

`payload: 03020000`

I take the first byte so "03" * 1000 + second byte so "02".
Its not perfect but you will have something using "deconz rules" X00Y

PS : You can remove manufacture code


Edit :
Not possible use the editor you miss the "cmd" field edit the file to have something like

        {
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0xFC42",
            "cmd": "0x02",
            "Item.val = ZclFrame.at(0) * 1000 + ZclFrame.at(1)"
          }
        },

**Comment by WhistleMaster** [comment]
Thanks ! 

I've updated a little bit, it was missing the "eval" in front of the formula and also +1 to the first byte as the payloads are starting at 0. This gives:

```
    {
      "name": "state/buttonevent",
      "awake": true,
      "parse": {
        "cl": "0xFC42",
        "cmd": "0x02",
        "eval": "Item.val = (ZclFrame.at(0)+1) * 1000 + ZclFrame.at(1)"
      }
    },
```

I'm putting everything together to also have the other functions working with that and I will post the DDF.

**Comment by WhistleMaster** [comment]
Done ! Everything is working with the following DDF. I also get the events in HA, perfect ! Thank you very much @Smanar for the help !

**Note**: in order to get the "double" press event, you have to enable it in the Zigfred app for each button. The app configures the device through Bluetooth.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Siglis",
  "modelid": "zigfred uno",
  "product": "zigfred uno",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/zigfred_uno.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x05",
        "0x0006"
      ],
      "items": [
        {
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0xFC42",
            "cmd": "0x02",
            "eval": "Item.val = (ZclFrame.at(0)+1) * 1000 + ZclFrame.at(1)"
          }
        }
      ]
    },
    {
      "type": "$TYPE_COLOR_DIMMABLE_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x05"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/bri",
          "refresh.interval": 5
        },
        {
          "name": "state/colormode",
          "description": "The currently active color mode."
        },
        {
          "name": "state/effect",
          "description": "The currently active effect.",
          "default": "none"
        },
        {
          "name": "state/hue",
          "description": "The current color hue."
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "state/sat",
          "description": "The current color saturation.",
          "refresh.interval": 5
        },
        {
          "name": "state/x",
          "description": "The current color x coordinate.",
          "refresh.interval": 5
        },
        {
          "name": "state/y",
          "description": "The current color y coordinate."
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x06"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_DIMMABLE_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x07"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/bri",
          "description": "The current brightness.",
          "refresh.interval": 5
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by Smanar** [comment]
So the device is compatible in HA ?
Haven't checked the value returned, but they need to be X00Y, X is the button number and Y the event.

If all is fine I will make the PR.

**Comment by WhistleMaster** [comment]
> So the device is compatible in HA ? Haven't checked the value returned, but they need to be X00Y, X is the button number and Y the event.

Yes, it is !

<img width="1072" alt="Screenshot 2022-08-21 at 09 20 19" src="https://user-images.githubusercontent.com/1544568/185780254-f8379d05-9428-4a9c-a07e-d975781640ef.png">

> If all is fine I will make the PR, or you want to make it ? (just remember to remove all "description" lines and the "path" from the DDF) 

I can make the PR, that would be my first one :)

> BTW you miss too principal items in the ZHAswitch like model id, manufacture name and ect ....

I can add it, what are the one required ?

**Comment by Smanar** [comment]
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Siglis",
  "modelid": "zigfred uno",
  "product": "zigfred uno",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x05",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/buttonevent",
          "awake": true,
          "parse": {
            "cl": "0xFC42",
            "cmd": "0x02",
            "eval": "Item.val = (ZclFrame.at(0)+1) * 1000 + ZclFrame.at(1)"
          }
        }
      ]
    },
    {
      "type": "$TYPE_COLOR_DIMMABLE_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x05"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/bri",
          "refresh.interval": 5
        },
        {
          "name": "state/colormode"
        },
        {
          "name": "state/effect",
          "default": "none"
        },
        {
          "name": "state/hue",
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "state/sat",
          "refresh.interval": 5
        },
        {
          "name": "state/x",
          "refresh.interval": 5
        },
        {
          "name": "state/y",
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x06"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_DIMMABLE_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x07"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/bri",
          "refresh.interval": 5
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

Can compare with this one, and test it.

To make a PR it's easy, mostly for only one file.
- go https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices
- create a new folder+file (it's the same thing) like siglis/zigfred_uno_wired_switch.json
- copy paste the contain (you will be able to edit it later)
- submbit a PR

You will be helped by the site, as you don't have right on the officiel github, it will create a fork under you github account, make your change inside and prepare the PR.
There is no danger you can't edit the official github, all changes will be on your fork, and after the PR will be submitted they will be synchronised, so if you want to edit something in your fork, the change will be too in the PR.

The PR list is here https://github.com/dresden-elektronik/deconz-rest-plugin/pulls if you want to see example.

**Comment by WhistleMaster** [comment]
Thanks ! Mine almost looks like your latest one, except with the following. Are those needed ?

- "name": "config/on"
- "name": "config/reachable"

This switch is "virtual" as there is no physical switch behind, it's only to handle the events.

**Comment by Smanar** [comment]
I m seing somethinf strange the endpoint 0x05 is used for the ZHAswitch  and the TYPE_COLOR_DIMMABLE_LIGHT

**Comment by WhistleMaster** [comment]
> I m seing something strange the endpoint 0x05 is used for the ZHAswitch and the TYPE_COLOR_DIMMABLE_LIGHT

Indeed. The events are defined in the endpoint 0x05, which is also the COLOR_DIMMABLE_LIGHT physically, and the cluster 0xFC42 handles the events. I've tried to add the buttoneven in the COLOR_DIMMABLE_LIGHT but it does not work.

> Yep, they are needed, all third app use it, config/on is used for rules, config/reacheable trigger an error if set to false.
Makes sense !

> I think you have too much dimmmable light.

I don't think so :) There is two dimmmable lights on the switch: one little led which is controllable as well on the switch (to make fancy lights effect on the switch) and the second on can be connected on the switch.

**Comment by WhistleMaster** [comment]
> Edit: I think the useless one is this one
> 
> ```
>     {
>       "type": "$TYPE_COLOR_DIMMABLE_LIGHT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x05"
>       ],
> ```

This is what I wrote [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6258#issuecomment-1216972114), it's a small led on the device itself which can be controllable as well. You can change the color and so on. It's also working in HA, you can control it there.

**Comment by Smanar** [comment]
ok, so all is fine ^^

You will have the cluster in the uniqueid "0x0006" so will be not the same uniqueid. Can use the Cluster 0xFC42 is you want instead of 0x0006

**Comment by WhistleMaster** [comment]
You mean here:

```
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x05",
        "0x0006"
```

would become:

```
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x05",
        "0xFC42"
```

**Comment by Smanar** [comment]
Yep, but it's like you want, as the device will use only the cluster 0xFC42 and not the 0x0006, will be better for me, but it's just cosmetic, and as HA have already memorised the one with 0x0006, you will need to remove it.

**Comment by WhistleMaster** [comment]
Sure, I'll do it now to test.

**Comment by WhistleMaster** [comment]
Done #6280 ! Thank you very much for the help !

**Comment by Smanar** [comment]
Perfect, thx for the new DDF ^^

BTW, if you can remove the "path" line, you can just edit it here https://github.com/WhistleMaster/deconz-rest-plugin/blob/patch-1/devices/siglis/zigfred_uno_wired_switch.json all will be synchronised.

`"path": "/devices/zigfred_uno.json",`

But in reality, I don't think deconz use this field.

**Comment by WhistleMaster** [comment]
Done :)

**Comment by Atokulus** [comment]
Dear all

I am dearly sorry, that I have not yet been able to respond to your integration request. It is quite nice, you took initiative in integrating the device 😄 Great job and kudos to @WhistleMaster and @Smanar 😁

I just wrote an extensive comment in your pull request. Looks quite promising!

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6280#issuecomment-1222110594

**Comment by WhistleMaster** [comment]
Thank you very much @Atokulus, your help will be gladly appreciated on this matter ! So let's continue the discussion in the PR then.
