### ISSUE TITLE
SOLVED - LK Wiser (FLS/AIRLINK/4)

### ISSUE THREAD

**Issue by Hassefar** [dresden-elektronik/deconz-rest-plugin#6259]
## Describe the bug

  The LK Wiser (FLS/AIRLINK/4) is a 4 button switch. The newest devices does not register the press on button 3 and 4 correctly. Consequently, a press on button 3 is registered as a press on button 1 and a press on button 4 is registered as a press on button 2. 

## Steps to reproduce the behavior

  If the problem is reproducable, list the steps here:

Assign different actions to each button i Deconz. Press button 3 and 4 and this will trigger action 1 or 2 respectively. 

## Expected behavior

Button 3 and 4 should be registered as individual buttons. 

## Screenshots

  ![image](https://user-images.githubusercontent.com/62770636/184169342-9bf1f9c0-2c59-47ea-935e-e3b2b30a2c3c.png)

## Environment

Version: 2.17.01 / 1.7.2022

 - Host system: (Raspberry Pi)
 - Running method: (Raspbian)
 - Firmware version: (26720700)
 - deCONZ version: (2.17.01 / 1.7.2022)
 - Device: (ConBee II)
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? If so: SSD

**Comment by Hassefar** [comment]
SOLVED

**Comment by Mimiix** [comment]
What did you change :)?

**Comment by Hassefar** [comment]
Pressed button 1 and 4 for about 5 seconds to enable individual buttons. :-)
