### ISSUE TITLE
Door Sensor _TZ3000_7tbsruql

### ISSUE THREAD

**Issue by jleeca** [dresden-elektronik/deconz-rest-plugin#6265]
## Device

- Product name: Door Window Sensor (https://www.aliexpress.com/item/1005002683267117.html?spm=a2g0o.order_list.0.0.2dc51802lQxIR6)
- Manufacturer: _TZ3000_7tbsruql
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/20133784/184496066-20898c43-5d55-43ba-818f-943d32130e44.png)
![image](https://user-images.githubusercontent.com/20133784/184496378-4952cf8d-4aa7-4e31-a1dc-a049986f4d25.png)

### Basic
![image](https://user-images.githubusercontent.com/20133784/184496138-8ea3baa1-fbf7-4f0c-8391-3685a86693ea.png)

### Identify
![image](https://user-images.githubusercontent.com/20133784/184496245-6d8ec732-c50a-42d2-bf63-dc6675ddd328.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/20133784/184496391-bb47c22b-5e33-4d95-96a1-faa6e06927a7.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/20133784/184496430-9137017b-447d-4b27-b6af-43a0e9a4f373.png)

**Comment by Smanar** [comment]
Hello can you try this DDF just with adding your device to the list ? https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6257

**Comment by jleeca** [comment]
I can confirm that the device works now when the DDF file you mentioned is used with the Manufacturer replaced to _TZ3000_7tbsruql.

**Comment by Smanar** [comment]
Ok, I will ask to the guys that make the PR to add it too.

**Comment by Middendorf** [comment]
Hallo 

Ich habe mit dem Hersteller geschrieben. Er hat mir diesen Link gegeben. Leider wird bei mir nur der Conbee2 Stick angezeigt. wie kann ich ein gerät in deconz app suchen? 

Über die PhosconApp blinkt mein Gerät so als ob er sich verbinden möchte, dann suche ich sensoren (andere Geräte) kurz darauf hört er auf zu blinken aber mein Türsensor wird nicht angezeigt. 

Ist der sensor defekt oder nur noch nicht in der APP (Software) hinterlegt?? 

Danke für eure Hilfe.

**Comment by Mimiix** [comment]
@Middendorf Can you please post in english?

**Comment by Middendorf** [comment]
Hi

Apologies for my bad English first.

I have written to the manufacturer. He gave me this link. Unfortunately, only the Conbee2 Stick is displayed for me. how can i search for a device in the deconz app?

My device flashes via the PhosconApp as if it wants to connect, then I search for sensors (other devices) shortly after it stops flashing but my door sensor is not displayed.

Is the sensor defective or just not stored in the APP (software)??

Thank you for your help.

**Comment by Smanar** [comment]
If your device is the _TZ3000_7tbsruql , the PR is not yet merged, check https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6257

If you want to use it now, you need to create yourself the DDF on your OS.

Better to use phoscon than deconz for inclusion.

**Comment by Middendorf** [comment]
Hi,

unfortunately I can't get it to run at all under Phoscon (displayed). If I go under sensors, set it to sync (flashes), then under look for new sensor, other devices. The search begins, the sensor flashes quickly, shortly afterwards it flashes briefly and then off. Unfortunately, no new sensor is displayed under Devices.
Is there another way to integrate the sensor?

Thanks Stefan

**Comment by Mimiix** [comment]
@Middendorf  Is it shown in the RestAPI?

Phoscon needs to add support on their own.

**Comment by Smanar** [comment]
@Middendorf you have added the DDF ?
