### ISSUE TITLE
moving to a new WIN10 PC

### ISSUE THREAD

**Issue by theendisnye** [dresden-elektronik/deconz-rest-plugin#627]
I have decided to move from my existing PC to a new one. I installed Deconz 2.05.25 and then swapped the Conbee USB device from the old PC into the new one. However it didn't automatically install any drivers despite my settings being correct. So a visit to FTDI site and it is a bit confusing is it the D2XX drivers I need?

Steve

**Comment by theendisnye** [comment]
Now fixed as the drivers hadn't installed correctly an update driver fixed.

Steve

**Comment by manup** [comment]
For reference on manual install it should be the VCP driver from the FTDI website.
