### ISSUE TITLE
Develco Products A/S	IOMZB-110

### ISSUE THREAD

**Issue by Patricen1** [dresden-elektronik/deconz-rest-plugin#6271]
## Device

- Product name: <html>
<body>

Develco Products IOMZB-110 IO Module
-- | --

</body>
</html>
- Manufacturer: Develco Products A/S
- Model identifier: IOZMB-110
- Device type : Please remove all unrelated device types. 
  - Light
  - Switch
   - Other: 2 relay NO/NC outputs, 4 inputs with internal pull-up

## Screenshots

([url](url))
![Capture2](https://user-images.githubusercontent.com/34392672/185305736-adb241ba-4e99-4372-bb02-fa00faa1e878.PNG)
![Capture1](https://user-images.githubusercontent.com/34392672/185305675-427161e8-d05f-4e67-b810-d4e0cb384d67.PNG)

**Comment by Mimiix** [comment]
Hi,

There's a lot of info missing and the template is not used correctly. Please create a new issue with all requested screenshots.

closing this one.

**Comment by zephyr2206** [comment]
Already requested here: [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5258](url)

**Comment by Mimiix** [comment]
I'll re-open that one :)

**Comment by zephyr2206** [comment]
Thanks :D
