### ISSUE TITLE
Aqara multi sensor not refreshing values regularly anymore after update to deconz 2.17.01

### ISSUE THREAD

**Issue by centrofly** [dresden-elektronik/deconz-rest-plugin#6276]
## Describe the bug
After updating to Deconz 2.17.01 and firmware 26720700 the update interval of my Aqara temperature/humidity/pressure sensors dropped significantly.

Usually the sensors should update when temperature changes for at least 0.5 degree Celsius or after 1 hour. Before the update this worked fine.

Now the sensors often do not update for several hours. You can see this when looking at attached CSV file which shows the logged temperatures. Beginning at 2022-08-09 in the evening (when I updated the deconz firmware package), the readings are coming in a lot less frequent, sometimes several hours apart.

[TEMPERATURE 07 temperature.csv](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9373744/TEMPERATURE.07.temperature.csv)

As you can see in the file, before the update the was at least an update every hour. 

Please note, I logged the values using iobroker for better visibility, but the problem is present in Deconz GUI as well, where the values not updating as well. So this is not a iobroker/adapter issue.

## Steps to reproduce the behavior
Update to Deconz 2.17.01 and monitor update frequency of Aqara temperature sensors.

## Expected behavior
Values should at least update once every hour, or when temperature changes 0.5 degree Celsius

## Environment
Deconz Version: 2.17.01 / 1.7.2022
Firmware Version: 26720700

 - Host system: Raspberry Pi 4
 - Running method: Raspbian
 - Firmware version: (26720700)
 - deCONZ version: (2.17.01)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
See attached file for couple of minutes of deconz log, donot know if it contains anything useful. Let me know if you need something specific.

[deconz_log.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9373743/deconz_log.txt)

Note: The sensor that corresponds to the value readings in the csv file is named named MULTI_07

**Comment by SwoopX** [comment]
This is not a bug, just to be clear on that right away 🙂 

I assume you upgraded from a version prior to 2.15.0? This PR is intended to bring back what you interpret as bug https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6268

**Comment by centrofly** [comment]
Thanks for the info, but I must admit I do not fully understand what you described in the PR.

Why would you not classify the behavior I found as a bug, if the quality of data received is not as good (up to date) as before?

**Comment by SwoopX** [comment]
Well, what the device does is sending the reports for the 3 values in a non-configurable way, more or less zigbee compliant, in more randomly chosen intervals. Deconz receives and processes them, so everything works as expected.

Now Xiaomi has some, not exactly zigbee compliant "special" reports, which are sent in a roughly 50 mins interval, content-wise different for every device. Those are what you perceive as reduced readings.

With the new code base, it had to be chosen what will be taken to give you updated values, which was the regular reports, as they occur more often (and you cannot have both). The PR is intended to bring back leveraging the special report in addition.

**Comment by LeoeLeoeL** [comment]
I can say, since Aqara TVOC DDF went to GOLD (the latest beta) air quality entity updates often while humidity not.
In previous release it was the opposite.

**Comment by tamtam1111** [comment]
> This is not a bug, just to be clear on that right away 🙂
> 
> I assume you upgraded from a version prior to 2.15.0? This PR is intended to bring back what you interpret as bug #6268

The "fix“ would be very welcome

**Comment by MaxCere** [comment]
Any workaround or ETA on when we will see the changes here? https://github.com/deconz-community/deconz-docker

**Comment by MaxCere** [comment]
> Any workaround

Rolled back to 2.14.01 as a temporary workaround works, waiting for the improvement for a stable solution.

**Comment by Hakko31** [comment]
I have the same error pattern. The sensors no longer update for hours.

**Comment by MaxCere** [comment]
I upgraded to 2.18.1 but still, sensors are refreshing less frequently.

**Comment by Smanar** [comment]
```
Expected behavior

Values should at least update once every hour, or when temperature changes 0.5 degree Celsius
```

what is your reporting interval ?

**Comment by MaxCere** [comment]
It's 0.5 degrees like you said but on 2.14.01 and using other Zigbee dongle updates are much more frequent....how can you tell that this is expected behavior? Take a look at the below graph, flat line is with 2.18.01 and the more frequent is with 2.14.01

User experience it's a lot better with more updates, I will migrate to another dongle if it remains the expected behavior.

![image](https://user-images.githubusercontent.com/58367631/190688176-6889ac40-1136-461b-9009-d7dbb33f7d8b.png)

**Comment by Smanar** [comment]
Your device is the "lumi.weather" ?
Strange I haven't the same result on my side, I have 0.1 °C variation.

**Comment by MaxCere** [comment]
Device is "lumi.sensor_ht", didn't touch any DDF. 

I will try again run 2.18.01 to avoid my errors

**Comment by Smanar** [comment]
Ok So I don't known at all this device but from the Z2M project it seem this device use the both cluster for temperature report, the temperature one and the Xiaomi one.

The second one is broken or WIP https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6268

Can you try like in this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6309

With replacing 

```
        {
          "name": "state/temperature",
          "public": false
        },
```

by

```
        {
          "name": "state/temperature",
          "awake": true,
          "parse": {
            "at": "0xff01",
            "ep": 1,
            "eval": "Item.val = Attr.val * 100",
            "fn": "xiaomi:special",
            "idx": "0x03"
          }
        },
```

**Comment by grandyann** [comment]
I've got the exact same behavior here with a lumi.sensor_ht:
- it was sending frequent updates (more or less every hour or 0.5° change) before I updated to 2.17.01
- Not better once updated to 2.18.01
- I tried the change suggested above ( https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6276#issuecomment-1250062618 ) but it didn't improve anything

**Comment by Smanar** [comment]
If I m right the "idx" to try for light level is 0x0b not 0x03 like on the sample.

**Comment by grandyann** [comment]
Note that my device is a xiaomi temperature and humidity sensor (not a light).

So I tried with 0x03, and also 0x0b, but nothing did really work.
Note that I also tried with 0x02 because I found some info here: https://zigate.fr/xiaomi-capteur-temperature-humidite-clusters/ (sorry, in french), but I'm really not sure which value I should take.
Is there any place with the datasheet for each device ?

**Comment by xavax59** [comment]
Hello, i've the same problem. To solve the problem, I change the status DDF xiaomi_wsdcgq11lm_temp_hum_press_sensor.json  (here /usr/share/deCONZ/devices/xiaomi/). I change Gold to Bronze

**Comment by stigvi** [comment]
> Hello, i've the same problem. To solve the problem, I change the status DDF xiaomi_wsdcgq11lm_temp_hum_press_sensor.json (here /usr/share/deCONZ/devices/xiaomi/). I change Gold to Bronze

Yes, this is what I did, too. IMO, these sensors should still be in a state other than gold "officially"

**Comment by Smanar** [comment]
Ha right, you can disable the "Gold" status.
Better to correct the report, but yes you are right, better to set the status "Bronze" than "Gold" officialy.

**Comment by glm-ypinczon** [comment]
Thx a lot for the tip @stigvi , it made a huge difference, and now everything seems to work the way it used to before updating 👍

**Comment by grandyann** [comment]
Thx a lot for the tip @xavax59 and @stigvi , it made a huge difference, and now everything seems to work the way it used to before updating 👍

**Comment by BabaIsYou** [comment]
> IMO, these sensors should still be in a state other than gold "officially"

Agree, more and more often the DFF seems published in "Gold" without having been completely validated, for convenience. I think they should be released in "Silver" when first included in a release, then set to "Gold" on the next release if no issue has been reported.

**Comment by Smanar** [comment]
Right, but I think you are the only one that doing that.
Even me I put always "Gold" out of laziness. But always for new devices, because the DDF can't broke an old one.

**Comment by BabaIsYou** [comment]
> Right, but I think you are the only one that doing that. Even me I put always "Gold" out of laziness. 

lol ! I'm just following this documentation : [DDF levels](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-change-DDF-modes-and-enable-or-disable-DDF-levels)

> But always for new devices, because the DDF can't broke an old one.
Not quite sure about that ... The new DDF will superseed the old one or legacy code auto generated one.

**Comment by Smanar** [comment]
>lol ! I'm just following this documentation

And I m sure no one can say you are wrong, but set the "Glod" state is easier and faster, the"least effort syndrome"

>Not quite sure about that ... The new DDF will superseed the old one or legacy code auto generated one.

It's new device, so there is no legacy code, no previous DDF. It can be a broken DDF or nothing ^^.
I have only /2 devices that are not in "Gold", but return are too much random for the moment ....

**Comment by niawag** [comment]
Hi all, I'm having connection problems with a xiaomi sensor (Xiaomi Mi Smart Temperature and Humidity Sensor - v 20160516 in phoscon), I'm not sure my problem are related to this issue but it may be. The sensor is really close to the conbee2 (less than 2m with a soft wall between eachother).
How can I troubleshoot it ?
Should I try to change the DDF inside the docker container? Or should I get back to a prior deconz version, if so, which one?

**Comment by centrofly** [comment]
> Thx a lot for the tip @xavax59 and @stigvi , it made a huge difference, and now everything seems to work the way it used to before updating 👍

@grandyann: What exactly did you change? I don not understand how/where to change DDF status from gold to bronze.

**Comment by Smanar** [comment]
Hello, use a text editor to edit the file with this path. You will see in the file "Status" in the first 10 line.

**Comment by rasssta** [comment]
Is there any work going on for this bug? Because we are many that consider it to be a bug... I thought some of my sensors were broken recently because of this issue. Applying the workaround did magic for me. 

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/4455235/207112683-237339e4-48fa-4df4-bb54-8f06e4a54562.png">

Take a guess when I applied the workaround...

**Comment by stigvi** [comment]
> Is there any work going on for this bug? Because we are many that consider it to be a bug... I thought some of my sensors were broken recently because of this issue. Applying the workaround did magic for me.
> 
> <img alt="image" width="1319" src="https://user-images.githubusercontent.com/4455235/207112683-237339e4-48fa-4df4-bb54-8f06e4a54562.png">
> 
> Take a guess when I applied the workaround...

I got tired of this and the Philips Hue Dimmer bug not fixed for months. So I decided to switch over to zigbee2mqtt with a Sonoff coordinator and that was a positive experience.

**Comment by rasssta** [comment]
Yeah, I'm leaning towards doing the same (again, sigh). I moved away from Homey as I got tired of the crappy update interval/0.5c increments for my temp sensors, so if this is going to stay as a "feature" I'm off to the next one.

**Comment by sceiler** [comment]
@rasssta can you please point me to a step-by-step guide or tell me yourself how to apply this workaround? I have got 2 different Aqara sensors with the same issue

**Comment by rasssta** [comment]
> @rasssta can you please point me to a step-by-step guide or tell me yourself how to apply this workaround? I have got 2 different Aqara sensors with the same issue

You have one above: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6276#issuecomment-1261927464

**Comment by sceiler** [comment]
Yeah I saw this but where do I find these JSON files? How do I apply it to my Conbee II/deConz?

**Comment by stigvi** [comment]
> 

I have switched over to zigbee2mqtt and dont have deconz anymore, so I have to write this out of memory. But if you open or go into the user interface for deconz, you will find severeal small strips at the top or bottom of the sceen. That is more sections or screens at the VNC session. One of those small strips is the DDF editor.

So you start with clicking on the node in the network map so that the node is the active one. Then select something like "edit DDF" in the menu. Then you open the DDF editor with clicking on the smal strip at the top or bottom. Select silver for that DDF and save and finally hot reload.

If you have this as a docker in Home Assistant, you have to do this at every restart as the changes you do are reset when the docker is restarted.

**Comment by sceiler** [comment]
> > 
> 
> I have switched over to zigbee2mqtt and dont have deconz anymore, so I have to write this out of memory. But if you open or go into the user interface for deconz, you will find several small strips at the top or bottom of the screen. That is more sections or screens on the VNC session. One of those small strips is the DDF editor.
> 
> So you start with clicking on the node in the network map so that the node is the active one. Then select something like "edit DDF" in the menu. Then you open the DDF editor with clicking on the smal strip at the top or bottom. Select silver for that DDF and save and finally hot reload.
> 
> If you have this as an addon in Home Assistant, you have to do this at every restart as the changes you do are reset when the docker is restarted.

thanks a lot. I got it working with your instructions. unfortunately it doesn't seem to help in my case. might be because it is a different sensor than the above mentioned or something else. I ordered a new Sonoff gateway and will replace my conbee ii with it. hopefully that will help long-term

**Comment by Mimiix** [comment]
> > > 
> > 
> > 
> > I have switched over to zigbee2mqtt and dont have deconz anymore, so I have to write this out of memory. But if you open or go into the user interface for deconz, you will find several small strips at the top or bottom of the screen. That is more sections or screens on the VNC session. One of those small strips is the DDF editor.
> > So you start with clicking on the node in the network map so that the node is the active one. Then select something like "edit DDF" in the menu. Then you open the DDF editor with clicking on the smal strip at the top or bottom. Select silver for that DDF and save and finally hot reload.
> > If you have this as an addon in Home Assistant, you have to do this at every restart as the changes you do are reset when the docker is restarted.
> 
> thanks a lot. I got it working with your instructions. unfortunately it doesn't seem to help in my case. might be because it is a different sensor than the above mentioned or something else. I ordered a new Sonoff gateway and will replace my conbee ii with it. hopefully that will help long-term

You can use the conbee with Z2m :)

**Comment by sceiler** [comment]
tbh I was considering a lot if I should change at all with all the migration work required but after researching around the internet it seems the conbee ii is a bit outdated from a hardware perspective. even though it should not matter at all with my rather basic setup I need to / want to redo most of my zigbee stuff anyway so I might as well switch to the latest zigbee hardware available.

**Comment by Smanar** [comment]
>it seems the conbee ii is a bit outdated from a hardware perspective

From memory ? The microcontroller speed ?

I still have a conbee 1

**Comment by cputoaster** [comment]
Just a me-too comment: I cannot pair the lumi.weather sensors anymore with latest stable docker. And I don't know how to change it easily (just copying the json to the docker mounted devices folder and changing to bronze did not work, its probably still taking the one from the image). Maybe reverting it to Bronze for the next release would be a good intermediary fix?

**Comment by Smanar** [comment]
There is soon a new deconz version, without all bugs on 2.19.X branch
To disable a DDF you can set in to "Bronze" yes, but you can too delete it.

But no, for me the solution is correcting the DDF.

**Comment by deluxestyle** [comment]
Can this be opened again? I still face this issue

**Comment by deluxestyle** [comment]
> Have you tried to disable the DDF ?

Means to set the DDF to Bronze?
Yes, but everytime a new version comes I have to do it again

**Comment by Smanar** [comment]
>Yes, but everytime a new version comes I have to do it again

Ha ok, what is your OS ? you can put it in an "devices" user folder, but if the user folder is prioritary on the "deconz" folder I m not sure if it still same if the deconz one have an highter status.

**Comment by pergolafabio** [comment]
> Perhaps https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues
> 
> DDF don't help for connection issue, only recognition. Can be the router if the sensor use one.

Hi, your reply is interesting... I have 3 multi sensors..

1 connected to conbee, the 2 others connected to Ikea plugs... When I do a cold boot, all sensors are connected.. hit after a while/hours, the 2 connected to Ikea are gone, not connecting anymore.... Untill I do a cold boot again...

What can I do to troubleshoot this? Running Deconz as addon in HA

**Comment by Smanar** [comment]
Xiaomi / Aqara have this issue with some routers https://community.hubitat.com/t/xiaomi-aqara-devices-pairing-keeping-them-connected/623

But was fine with ikea ... A cold boot is a device reset for you ? or you reboot the host ?

You have take a look on the network picture on the GUI ?

**Comment by pergolafabio** [comment]
Ok I have a look later, yes when I do a complete host reboot...

**Comment by pergolafabio** [comment]
Had a look indeed, ths is how it shows now
accordint to this link, stuff should be missing, but in my case its all there...
the 2 multi sensors are just gone from network

![image](https://user-images.githubusercontent.com/43251136/219405103-50840f00-6efc-4c0a-b690-f9da742a6288.png)

**Comment by Smanar** [comment]
Just for test can you try to put the sensor closer an ikea switch ?

**Comment by pergolafabio** [comment]
ok, will do that...
I did a coldboot , and they are reporting back as you can see below
But still i dont see any lines of those 2 that are giving issues? What could explain that?

![image](https://user-images.githubusercontent.com/43251136/219444760-e72194e1-7bd2-48f0-994e-b65fd0d12748.png)
![image](https://user-images.githubusercontent.com/43251136/219444956-e195e3bc-6968-4220-bf8b-6f15be33c1ca.png)

**Comment by pergolafabio** [comment]
i also now noticed, the ones thats connected "multi_onder" seems it now also took an ikea as a repeater, while it was first direct connected to the conbee stick
And even the "multi_onder" that always worked , the one with the line , is the one with the biggest distance, even another floot
So i dont think distance is an issue
multi_boven, and multi_zolder are quite close to ikea repeaters

**Comment by Smanar** [comment]
But what are you calling a "coldboot", a deconz restart ?
In phoscon you can select the device and look for "last seen" if it s > 1h, lot of chances for the device have DC (even they are not already marked as unrechable)

What is the model id of ikea switch ?

**Comment by pergolafabio** [comment]
Ok, will have a look later...

I mean a cold boot, shutdown the host, no power...
After the coldboot, they are reporting back for a few hours...

Restarting the addon/deconz, doesn't 

Not sure if there is a difference in just restarting or power down/coldboot

**Comment by Smanar** [comment]
Ok so realy something strange, I don't see how a cold boot can have a different reaction than a deconz restart, and on a sleepig device ...

The gateway is still powered if you just restart the Host, so to restart it you need to cut the power (or unplug/replug it) and some machine still power the USB port even on power off mode.

A xiaomi/aqara that have left the network never come back.

**Comment by pergolafabio** [comment]
Ok will have a look later...
Yeah I'm aware of Xiaomi, once paired , they don't change route indeed...
It's indeed strange that only after cold boot they come back, I check again tomorrow and will provide the firmware info later

**Comment by pergolafabio** [comment]
deconz: 20.20.01
gw: 26390500
conbee first model
below is the ikea plug info, allthough dont think its related anymore, since the working sensos is also connected to it... i tought at first it was connected to conbee stick itself

![image](https://user-images.githubusercontent.com/43251136/219455260-ac9be48f-b55f-4a8d-8808-295dea48c34b.png)

**Comment by pergolafabio** [comment]
gonna repair them again, maybe it will solve the issue anway

**Comment by Smanar** [comment]
IDK, I have take a look fastly on google, haven't see special issue about the ikea device ....

**Comment by pergolafabio** [comment]
Yeah indeed , gonna buy some new batts and repair them again, thx for all info

**Comment by mangoschorle** [comment]
November 23 and I can confirm that under v2.24.1 with Gold enabled, the sensor still isn't working ...

**Comment by NurNano** [comment]
I'm facing the same problem since months.
Now its June 2024 and under v2.26.3 the problem still exists.
Is anyone able to help solving this? I would love to help, but have no clue what the initial change effecting an how to improve the ddf.

**Comment by NurNano** [comment]
Its about the xiaomi_wsdcgq01lm_temp_hum_sensor.
Interval of new values coming is much higher when the json is in Gold status than in Bronze status.
When Bronze the interval is about 50-60 minutes, or a rapid change in temp or humidity. With Gold status the sensor partially updates temperature and humidity after hours or days. I got the feeling that there even multiple temp changes are missing.

**Comment by Smanar** [comment]
Ha yes I remember now, this device use the lumi cluster instead of classic cluster, the DDF probably use the bad one.
