### ISSUE TITLE
Downgrading firmware Deconz Raspbee

### ISSUE THREAD

**Issue by jelmert24** [dresden-elektronik/deconz-rest-plugin#628]
Hi, I installed the 2.05.28 version with the 26210500 firmware. As related to these version there are some issues with de ikea bulbs, sensors, etc.. So i want downgrade to the stable 2.05.25 and the 261f0500 firmware. 

Downgrading of deconz goes very well. When i try to downgrade the firmware with the following comand
` sudo /usr/bin/GCFFlasher_internal -d 0 -f /usr/share/deCONZ/firmware/deCONZ_Rpi_0x261f0500.bin.GCF`

I received the following error.

`pi@hassbian:/usr/share/deCONZ/firmware $ sudo /usr/bin/GCFFlasher_internal -d 0 -f /usr/share/deCONZ/firmware/deCONZ_Rpi_0x261f0500.bin.GCF
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
using firmware file: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x261f0500.bin.GCF reset via FTDI 
FTDI can't open device 0, status = 2`
I'l tried also the list command but i can't see the Raspbee. See here below

`pi@hassbian:/usr/share/deCONZ/firmware $ sudo GCFFlasher_internal -l
rmmod: ERROR: Module ftdi_sio is not currently loaded
rmmod: ERROR: Module usbserial is not currently loaded
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
RaspBee: /dev/ttyAMA0 (default)
no FTDI devices found`

The Raspbee is visible in the PWA interface and i can control some lights. So the Raspberry can find the Raspbee. 

Can anyone tell me what i'm doing wrong? Before i do the commands i stops the deconz service
`sudo service deconz stop`

Thanks!

**Comment by Webserve** [comment]
Device 0 doesnt exists. Please try "sudo /usr/bin/GCFFlasher_internal -f ...."
