### ISSUE TITLE
ROB_200-029-0 - Roller Shutter Switch

### ISSUE THREAD

**Issue by patvdleer** [dresden-elektronik/deconz-rest-plugin#6283]
## Device

- Product name: `ROB_200-029-0`
- Manufacturer: `ROBB smarrt`
- Model identifier: `ROB_200-029-0`
- Device type:
  - Other: Window Covering Controller (shutter)

Product link:
  - NL: https://www.robbshop.nl/robb-smarrt-zigbee-rolluikschakelaar
  - EN: https://www.robbshop.nl/en/robb-smarrt-zigbee-roller-shutter-switch 

Currently shows up as a dimmable light.

## Screenshots

![image](https://user-images.githubusercontent.com/1138136/186251751-7c372779-d02c-4eba-8e59-a3d8d147d120.png)

### Basic

![image](https://user-images.githubusercontent.com/1138136/186252282-813aa744-d754-4db9-adfe-e9f306b4a76c.png)

### Identify

![image](https://user-images.githubusercontent.com/1138136/186252330-04f714c7-8609-4ec7-8b8c-4c0b13a1789d.png)

### Alarms

N.a.

### Device Temperature

N.a.

### Groups

![image](https://user-images.githubusercontent.com/1138136/186252673-6e716eaf-4868-48cf-b596-60ce76b6fc46.png)

![image](https://user-images.githubusercontent.com/1138136/186252708-f8588cce-17fa-489d-b6e5-1607d7a713f0.png)

### Scenes

![image](https://user-images.githubusercontent.com/1138136/186252770-e05d7e1f-5cd5-4310-97c6-c08bd4428f03.png)

![image](https://user-images.githubusercontent.com/1138136/186252799-2e18829b-d405-4b87-93d1-fe840186e3b4.png)

![image](https://user-images.githubusercontent.com/1138136/186252832-1fa56eb8-0066-41ac-9b75-ca1f9c37b272.png)

![image](https://user-images.githubusercontent.com/1138136/186252872-99ed15f0-16d8-4477-9afd-4b6546ea3ce0.png)

### On/Off

![image](https://user-images.githubusercontent.com/1138136/186252990-29a2c50b-4413-4449-b953-b2668844d2f0.png)

![image](https://user-images.githubusercontent.com/1138136/186253014-83f23524-34a1-4b06-a8f5-aaf332cee09b.png)

### Level Control

![image](https://user-images.githubusercontent.com/1138136/186253052-6b5c716d-e25d-496b-86de-67e37964619e.png)

![image](https://user-images.githubusercontent.com/1138136/186253142-5f1f3d5b-2579-4c8e-980a-4b2b26b2b20a.png)

### Color Control

N.a.

### Simple Metering

N.a.

### Diagnostics

![image](https://user-images.githubusercontent.com/1138136/186253445-f1afc49d-2eff-4679-badb-3d78597ec104.png)

### 0102 Window Covering

![image](https://user-images.githubusercontent.com/1138136/186253303-52a1d08d-3317-4730-b5b6-d9cc0bc275fb.png)
![image](https://user-images.githubusercontent.com/1138136/186253338-26b312fa-9528-4566-87fa-ed6e4b4c6d90.png)
![image](https://user-images.githubusercontent.com/1138136/186253375-11059cdb-533b-4264-8d3f-dca97eab4647.png)

### 1000 ZLL commisioning

![image](https://user-images.githubusercontent.com/1138136/186253679-6a1fcb85-4512-4ce1-bf16-4b2544ef5b7c.png)

### F2 - 0021 Green power

![image](https://user-images.githubusercontent.com/1138136/186253636-efa6c397-4298-4c86-88ab-32da72bdc3cb.png)

**Comment by Smanar** [comment]
Ha yes it s because your device have light cluster and covering cluster.
Easy to correct using DDF, 2 solutions, can make change yourself or share your actual DDF for I edit it.

In deconz, right clic, edit DDF, save the file and share it.

If you want to make the change yourself (I don't know your DDF so I can be wrong)

Remove state/bri, state/on
Chnage the type from "dimmable light" to `"type": "$TYPE_WINDOW_COVERING_DEVICE",`
Make hot reload in the menu

**Comment by patvdleer** [comment]
![image](https://user-images.githubusercontent.com/1138136/186670141-9aaa489a-d5bb-46f2-9a91-b7bb82455eed.png)

I did get to remove the state/bri and state/on by I dont seem to be able to change the state.

**Comment by Smanar** [comment]
Can you try with replacing your DDf by this one

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "ROBB smarrt",
  "modelid": "ROB_200-029-0",
  "product": "ROB_200-029-0",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lift"
        },
        {
          "name": "state/open"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0102",
      "report": [
        {
          "at": "0x0008",
          "dt": "0x20",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

Take care at path choosed by deconz, or you put it direclty in the DDF folder (in "devices)
If they are in the good folder, deconz select them automatically, else you probably need to load them using the editor.

**Comment by patvdleer** [comment]
I placed it in the folder, `/usr/share/hassio/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices`,  next to the file created by deCONZ originally. I loaded it and the path is confirmed in the DDF preview. Hot reloaded, but there doesn't seem to change anything. Phoscon and HASS still see it as a dimmable light.

**Comment by Smanar** [comment]
It's not my DDF, I don't use the "path" filed.

**Comment by patvdleer** [comment]
I didn't remove or clean it, -> `Dimmable light 20`

---

I unpaired it again, fixed the files 
- `rob_200-029-0.json` (your version)
- `rob_200-029-0.orig.json` (original)

Added again -> `Dimmable light 21`

---

Deleted `rob_200-029-0.orig.json`, unpaired, -> `Dimmable light 22`

**Comment by Smanar** [comment]
Ok.
What is your deconz version, on lastest version the legacy code is slowed down compared to DDF code.

Can you try to enable deconz log in deconz / help / debug view just with the flag "DDF" and make a hot reload ?

**Comment by patvdleer** [comment]
Hass: 2022.8.6 
deconz: 2.17.1

![image](https://user-images.githubusercontent.com/1138136/186992688-5841c565-a372-49f1-a55e-3a863879fbf5.png)

**Comment by Smanar** [comment]
And from logs we can't see the used type but the code create only lift and open, wo seem not so bad.
Can you check direclty in the API using phoscon / help / API Information / light / ID

I think the issue is because the legacy code that create a device json before the DDF core.

**Comment by patvdleer** [comment]
I now can control it via Hass!

```json
{
    "etag": "c697919f10fe0b860ddf53ec1d7ac3c3",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2022-08-27T10:13Z",
    "manufacturername": "ROBB smarrt",
    "modelid": "ROB_200-029-0",
    "name": "Shutters 1",
    "state": {
        "lift": 100,
        "open": false,
        "reachable": true
    },
    "swversion": "2.5.3_r47",
    "type": "Window covering device",
    "uniqueid": "94:de:b8:ff:fe:8a:21:0d-01"
}
```

Phoscon settings view:
![image](https://user-images.githubusercontent.com/1138136/187025824-df467ec1-3a67-42f9-910d-7b0581ee9b56.png)

Phoscon regular view: (unable to control it via Phoscon)
![image](https://user-images.githubusercontent.com/1138136/187025901-dade81eb-d256-4415-b78d-e0d13c3e4b5e.png)

Hass:
![image](https://user-images.githubusercontent.com/1138136/187025878-137ece74-99d8-42b2-9f64-60f1512bb787.png)

**Comment by Smanar** [comment]
So it work now ?
What was the trick ? use "hot reload" ?

**Comment by patvdleer** [comment]
I have no clue... I restarted home assistant, reloaded the addon not the new setting did how up.

**Comment by Smanar** [comment]
Lol, ok, I will submit the PR as without it the device can never be reconised as covering.

**Comment by patvdleer** [comment]
There seems to be one remaining issue, Home assistant disables the button to go down if they're fully up and vice versa. I can control them just fine via deconz vnc. If I let them go up or down just a bid and stop them I then can control them via HA.
Since I have no clue where this issue might originate I'm posting this issue here, please let me know if I should address this with the HA devs.

Shutter 1 and 2 are closed, shutter 3 is open.  

![image](https://user-images.githubusercontent.com/1138136/187277396-daa2dd62-d1af-4665-8b9b-6c814a5d9f41.png)

**Comment by patvdleer** [comment]
@Smanar 

![image](https://user-images.githubusercontent.com/1138136/187299445-996951a6-a8d5-4545-a55e-628d65e1853c.png)

**Comment by patvdleer** [comment]
Is this what you're looking for? 

The shutters are now fully open.

![image](https://user-images.githubusercontent.com/1138136/187612999-32e5c231-a62f-4ff5-aba1-97e841dd37aa.png)


![image](https://user-images.githubusercontent.com/1138136/187613095-49cde45c-3f5d-461e-8cc4-5d3060d6e644.png)

![image](https://user-images.githubusercontent.com/1138136/187613152-6059a4bd-015e-46c4-a6ea-fd9b2bd97564.png)

![image](https://user-images.githubusercontent.com/1138136/187613183-f93a8aef-9333-42cb-9765-aeb3c084e8bb.png)

![image](https://user-images.githubusercontent.com/1138136/187613217-6d4dd32a-8b61-4d80-affd-31150154ba10.png)

**Comment by Smanar** [comment]
Nope the device json, the value returned by the api for it (and used by HA)
You can see them in phoscon / help / API Information / light / "device ID"

somethinh like that
```

{
    "manufacturername": "_TZE200_zah67ekd",
    "modelid": "TS0601",
    "state": {
        "lift": 0,
        "open": true
    },
    "swversion": null,
    "type": "Window covering device"
}
```

And I think thoses value are reversed for you.

**Comment by patvdleer** [comment]
these values dont change, even after reloading, on and open stay on false.

# rest api

```json
                    {
    "etag": "e64177b6deddedc6ed820081b14ffca0",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2022-08-31T15:57Z",
    "manufacturername": "ROBB smarrt",
    "modelid": "ROB_200-029-0",
    "name": "Shutters 2",
    "state": {
        "bri": 127,
        "lift": 100,
        "on": false,
        "open": false,
        "reachable": true
    },
    "swversion": "2.5.3_r47",
    "type": "Window covering device",
    "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
}
```

# web socket 
```json
{
    "18:03:07:117": {
        "e": "changed",
        "id": "19",
        "r": "lights",
        "state": {
            "bri": 127,
            "lift": 0,
            "on": false,
            "open": null,
            "reachable": true
        },
        "t": "event",
        "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
    }
}
```

**Comment by Smanar** [comment]
But there is something changed ? You don't use the DDF ? On your previous post you have that as json https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6283#issuecomment-1229165639

No state/bri and state/on (as they was removed on the DDF)

For a closed shutter you need to have
```
open = false
lift = 100%
```

and yes on your capture only lift is moving.

**Comment by patvdleer** [comment]
ow my bad, I overlooked that one, here's a fresh websocket log from open to close. 

```json
{
    "21:14:37:8": {
        "e": "changed",
        "id": "19",
        "r": "lights",
        "state": {
            "bri": 127,
            "lift": 100,
            "on": false,
            "open": null,
            "reachable": true
        },
        "t": "event",
        "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
    },
    "21:14:37:83": {
        "e": "changed",
        "id": "19",
        "r": "lights",
        "state": {
            "bri": 127,
            "lift": 100,
            "on": false,
            "open": null,
            "reachable": true
        },
        "t": "event",
        "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
    },
    "21:15:19:512": {
        "attr": {
            "id": "19",
            "lastannounced": null,
            "lastseen": "2022-08-31T19:15Z",
            "manufacturername": "ROBB smarrt",
            "modelid": "ROB_200-029-0",
            "name": "Shutters 2",
            "swversion": "2.5.3_r47",
            "type": "Window covering device",
            "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
        },
        "e": "changed",
        "id": "19",
        "r": "lights",
        "t": "event",
        "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
    },
    "21:15:19:517": {
        "e": "changed",
        "id": "19",
        "r": "lights",
        "state": {
            "bri": 127,
            "lift": 0,
            "on": false,
            "open": null,
            "reachable": true
        },
        "t": "event",
        "uniqueid": "94:de:b8:ff:fe:8a:21:32-01"
    }
}
```

**Comment by Smanar** [comment]
Ok so lift value seem good, you miss the state/open, I will add it on  the DDF
But I don't understand why you have bri and on ?

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "ROBB smarrt",
  "modelid": "ROB_200-029-0",
  "product": "ROB_200-029-0",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lift",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 1,
            "eval": "Item.val = Attr.val < 100",
            "fn": "zcl"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0102",
      "report": [
        {
          "at": "0x0008",
          "dt": "0x20",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by patvdleer** [comment]
> But I don't understand why you have bri and on ? 
Bri and on?

Sadly the new DDF doesn't fix it...

**Comment by patvdleer** [comment]
I've updated the DDF to 

```json
{
          "name": "state/open",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 1,
            "eval": "Item.val = Attr.val == 100",
            "fn": "zcl"
          }
```

Check the icons:

The woonkamer (livingroom) is half closed, the other 2 are open.

![image](https://user-images.githubusercontent.com/1138136/187980085-2825caf1-8c6d-4a8b-84cf-7063e9d84fc0.png)

**Comment by Smanar** [comment]
>Bri and on?

Yeah on a previous DDF you have 

```
        "state": {
            "bri": 127,
            "lift": 0,
            "on": false,
            "open": null,
            "reachable": true
        },
```

And now you have again just

```
        "state": {
            "lift": 0,
            "open": null,
            "reachable": true
        },
```

Ok so your device is reversed

>From fully open to fully closed
```
            "lift": 0,
            "open": true,
```

And you need to reverse both
So in the DDF you can use
```

        {
          "name": "state/lift",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 1,
            "eval": "Item.val = 100 - Attr.val;",
            "fn": "zcl"
          }
        },
        {
          "name": "state/open",
          "parse": {
            "at": "0x0008",
            "cl": "0x0102",
            "ep": 1,
            "eval": "Item.val = Attr.val > 0",
            "fn": "zcl"
          }
        },
```

**Comment by patvdleer** [comment]
Awesome this fixes it!

**Comment by Smanar** [comment]
So I update the previous PR with the new changes ?

**Comment by patvdleer** [comment]
yes please

**Comment by patvdleer** [comment]
Crap..... I found a bug, I can't set the position to 0 anymore, it sets it back to 100. I can still close it via the buttons but not the slider

**Comment by Smanar** [comment]
So it work with value from 100 to 1, but not the 0 values ?
It was working before the last DDF modification ? Can you try "patching" only state/lift or state/open to check the guilty ?

**Comment by patvdleer** [comment]
my apologies for the delay, have been swamped with work, will try to debug asap
