### ISSUE TITLE
MOES ZigBee wired touch switch 3 gang

### ISSUE THREAD

**Issue by ipmad** [dresden-elektronik/deconz-rest-plugin#6284]
## Device

- Product name: MOES ZigBee wired touch switch 3 gang ZTS-EU
- Manufacturer: _TZE200_tz32mtza
- Model identifier: TS0601
- Device type : Please remove all unrelated device types. 
  - Switch

### Basic
![3gang_1](https://user-images.githubusercontent.com/111777726/186392613-3d1e5ffb-bcbe-466a-a1bc-6093f225d101.PNG)

### Groups
![3gang_2](https://user-images.githubusercontent.com/111777726/186392794-f5adf55d-64f5-415f-b4e1-a00d34f6593a.PNG)

### Scenes
![3gang_3](https://user-images.githubusercontent.com/111777726/186392768-92df3e35-0da6-4e78-bf57-2bb4ed7afef5.PNG)

### Other clusters that are not mentioned above
![3gang_4](https://user-images.githubusercontent.com/111777726/186392870-316019f9-01b5-487f-b0c7-54c5646b3c14.PNG)
![3gang_0](https://user-images.githubusercontent.com/111777726/186392965-409ff1de-dae0-4050-ac17-6fcd498f5bda.PNG)

**Comment by Mimiix** [comment]
Re-opened: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4590

CLosing this one as its duplicate.
