### ISSUE TITLE
Door/Window Sensor ZD08

### ISSUE THREAD

**Issue by matze20211** [dresden-elektronik/deconz-rest-plugin#6292]
## Device

- Product name: Door Window Sensor Model ZD08 (with anti-tamper button)
- Manufacturer: _TZ3000_7d8yme6f
- Model identifier: TS0203
- Device type : 
  - Sensor
  
## Screenshots

![grafik](https://user-images.githubusercontent.com/87879362/186901344-4c60ef94-8e4e-41a8-93ce-cb545d02c5d4.png)
![grafik](https://user-images.githubusercontent.com/87879362/186901578-a753ffbf-72ab-4aff-b1dc-cc153785c38f.png)
![grafik](https://user-images.githubusercontent.com/87879362/186901686-4aefd937-e513-4aea-ab4f-a5e2846f7ad4.png)
![grafik](https://user-images.githubusercontent.com/87879362/186901978-dfd8c394-ade3-40ad-bcdc-81f9aa0140b9.png)
![grafik](https://user-images.githubusercontent.com/87879362/186902137-1406d92c-8ebb-443b-a1eb-912d9f93a687.png)
![grafik](https://user-images.githubusercontent.com/87879362/186902240-e0aaa99f-9f3c-4ca2-ab4c-ba2a6c289168.png)
![grafik](https://user-images.githubusercontent.com/87879362/186902306-13ec1a0f-1606-42b9-9dd9-94c63ae0577d.png)
![grafik](https://user-images.githubusercontent.com/87879362/186902473-6df0a161-47f0-4394-a732-0370fef65031.png)
after read
![grafik](https://user-images.githubusercontent.com/87879362/186904092-dec7b9dc-9b9f-47b8-8476-ca292a2009d0.png)

**Comment by Smanar** [comment]
Hello can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_n2egfsli", "_TZ3000_oxslv1c9", "_TZ3000_7tbsruql", "_TZ3000_7d8yme6f"],
  "modelid": ["TS0203", "TS0203", "TS0203", "TS0203"],
  "vendor": "Tuya",
  "product": "Smart Zigbee Door Window Contact",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by matze20211** [comment]
Hi, thank you, it is mainly working, but the tamper button isn't recognized. and is shown with motion detector symbol in phoscon:
![grafik](https://user-images.githubusercontent.com/87879362/188688528-fce82a9c-0d3e-4fe3-b7c0-1a907252393e.png)

**Comment by Smanar** [comment]
Oups I forget the tamper.
Can you add in the DDF

```
            {
               "name":"state/tampered"
            }
```

The second problem can come from phoscon, you can see the device json in phoscon / help / API information / sensors
Or in third app.

**Comment by matze20211** [comment]
Super, now all is working fine.

**Comment by Smanar** [comment]
Nice, thx, PR submitted https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6307
