### ISSUE TITLE
Compile error with latest commit (ubisys C4 config)

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#631]
I get a compile error with the latest commit:
```
bindings.cpp: In member function ‘void DeRestPluginPrivate::processUbisysC4Configuration(Sensor*)’:
bindings.cpp:2084:27: error: ‘ZclWriteAttributesStructuredId’ is not a member of ‘deCONZ’
     zclFrame.setCommandId(deCONZ::ZclWriteAttributesStructuredId);
```
I assume it needs a newer version of deconz-dev.2.05.xx.deb ?

**EDIT** Just commenting out the offending line seems to work around this issue for me.  I don't have a C4, so this code will probably never run in my configuration...

**Comment by manup** [comment]
Sorry, forgot to upload. The -dev file is now updated and should work with latest commits.

**Comment by holli73** [comment]
hello,

i have same issue un x64 linux but no new -dev file?

thanks
holli

**Comment by manup** [comment]
Hey Holli,
version 2.05.29 is online now with updated -dev package.
