### ISSUE TITLE
MYUET ME167 - Tuya Thermostat - Clone Derivat 

### ISSUE THREAD

**Issue by Miraculix666** [dresden-elektronik/deconz-rest-plugin#6318]
## Device

- Product name: MYUET ME167
- Manufacturer: _TZE200_bvu2wnxz
- Model identifier: TS0601

One of many places to order:
https://de.aliexpress.com/item/1005003952150617.html?spm=a2g0o.productlist.0.0.6036199bHV4yKu&algo_pvid=8f5681bd-f635-4e7a-9704-7c2681383b62&algo_exp_id=8f5681bd-f635-4e7a-9704-7c2681383b62-8&pdp_ext_f=%7B%22sku_id%22%3A%2212000027550116432%22%7D&pdp_npi=2%40dis%21EUR%2147.94%2128.29%21%21%21%21%21%402100bb4a16628399681366003e742e%2112000027550116432%21sea&curPageLogUid=76pPMqvayuTP

- Device type : 
  - Sensor
  - Thermostat

## photos

![PXL_20220910_220524655.jpg](https://user-images.githubusercontent.com/57354802/189500208-ca9a77be-00e5-49a2-924c-ba63437d037b.jpg)
![PXL_20220910_220504783.jpg](https://user-images.githubusercontent.com/57354802/189500213-bb4d1e2f-bb12-48a3-bd87-566a4682a723.jpg)
![PXL_20220910_220443640.jpg](https://user-images.githubusercontent.com/57354802/189500217-bc45677a-5469-41a5-80c3-f85ee0efa1d8.jpg)

##Screenshots

![2022-09-10_20h57_44](https://user-images.githubusercontent.com/57354802/189499983-8a68f9a6-10f8-415d-ace9-942a427c0952.png)

![2022-09-10_20h55_21](https://user-images.githubusercontent.com/57354802/189499984-5c62bd3f-f2a1-4b3a-a944-da5f597a4eb4.png)

![2022-09-10_20h55_44](https://user-images.githubusercontent.com/57354802/189499985-880a8170-1313-4ae7-99b6-5917f26f0f53.png)

![2022-09-10_20h56_22](https://user-images.githubusercontent.com/57354802/189499986-60bbc8c0-a457-4ff8-9c8a-f0a7367337ff.png)

![2022-09-10_20h56_45](https://user-images.githubusercontent.com/57354802/189499989-6b0f03b9-5e9f-442d-ac67-deab6605ad5c.png)

![2022-09-10_20h56_57](https://user-images.githubusercontent.com/57354802/189499990-3dd26c8c-320a-48e6-b9d4-0cbb7014b309.png)

![2022-09-10_20h57_07](https://user-images.githubusercontent.com/57354802/189499991-17e734b0-18bc-4813-a7f5-ade7ff3d1e8d.png)

Debug log is following next days, my normal setup has too much nodes. 
There should be clones, but I don't know how to create a propper ddf.

THX for help

Edit:
I found of thread at ZigBee2mqtt:

https://github.com/Koenkk/zigbee2mqtt/issues/12315

If it helps, I can also send a device to a dev

**Comment by Smanar** [comment]
Hello, sorry, but for the moment it's not possible to add Tuya TRV using DDF.

**Comment by Miraculix666** [comment]
> Hello, sorry, but for the moment it's not possible to add Tuya TRV using DDF.

:-(

Okay, what is the best way to go further?
It seems to be very similar to this one.

https://zigbee.blakadder.com/Hama_00176592.html
https://www.zigbee2mqtt.io/devices/SEA801-Zigbee_SEA802-Zigbee.html

**Comment by Smanar** [comment]
There is a PR tu support them, but still in waiting list.

**Comment by Miraculix666** [comment]
After this video, I am sure that it is a SEA802

https://youtu.be/0mE70FTBQG0

Since i only have one raspbee, I have to change my setup for the debugging,
My idea is to good up on straight deconz image, ein directly change my network channel, in that way I should only have that one device in my network that we investigate, is that correct?

What tests should I do to provide helpful output?

Is the above mentioned Thermostat supported by now?

If it is, it should be possible to add line to the device list and compile, correct? (I read something like this in another thread...)

I would try this.

Testing in this context should be possible with Rest client, I think.

**Comment by Smanar** [comment]
The model mean nothing, there is new tuya clone every day.
This model is not supported by the legacy code, and not possible to add it using DDF yet.

**Comment by Miraculix666** [comment]
:-(

Seemd to me from the other threads that basic functions are available.

Bad buy...

Is there anything that I can provide to get it up and running?

Smanar ***@***.***> schrieb am Di., 13. Sept. 2022, 17:55:

**Comment by Smanar** [comment]
For the moment, need to wait for the core be in place, to add new devices.

**Comment by Miraculix666** [comment]
> For the moment, need to wait for the core be in place, to add new devices.

Is there a est. timeline for this? If not, I need to buy also a tuya base (is there one device preferred?).

Maybe I could help then, similar to this procedure:

https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_5-create-a-cloud-project

**Comment by Smanar** [comment]
Lol, I m seing you are realy motivated, but the problem is this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054
On my side I m waiting for this PR is valided before adding more tuya TRV, because if something is not accepted need to remake all for all devices added.

**Comment by Miraculix666** [comment]
> Lol, I m seing you are realy motivated, but the problem is this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6054
> On my side I m waiting for this PR is valided before adding more tuya TRV, because if something is not accepted need to remake all for all devices added.

Winter is coming,... 
And it's maybe getting (more) nasty in Europe this year.

I had to dump my old fs20 thermostat system. 

Ok,

I'm trying to getting an overview of this vast and crumbled theme. 
I also have another tuya thermostat that I could test (working fine till now, but I'm only using the basic functions. It is this one, labeled my Moe's https://zigbee.blakadder.com/Hysen_HY368.html)

It seems that with a little luck it could be done in the near future.
🤞

Would debug be helpfull and a Szenario as i described be good for that?

**Comment by Miraculix666** [comment]
I couldn't wait any longer, got now a cheap tuya ZigBee hub for the thermostats. I also connected with my to tuya dev account. Just let me know if I can help out with some logs or something else...

**Comment by GaWr26** [comment]
I also just got two of these so would be great if I could get them to work in Deconz

**Comment by DoraDeu** [comment]
Could this topic be re-opened? This model has not included into the converter yet and there is still just an external converter as a workaround.

**Comment by Stooovie** [comment]
Still nothing? The external converter doesn't work for me either

**Comment by Smanar** [comment]
Nope sorry, still waiting for support for tuya TRV using DDF.

**Comment by Miraculix666** [comment]
since there's no action I'll probably change my ZigBee system to ZHA or
z2m. Skyconnect is already delivered...

github-actions[bot] ***@***.***> schrieb am Do., 12. Jan.
2023, 03:00:

**Comment by Miraculix666** [comment]
Still pending....
