### ISSUE TITLE
Aqara Vibration Sensor identified as a Door Lock in GUI. (2.18.1)

### ISSUE THREAD

**Issue by olemr** [dresden-elektronik/deconz-rest-plugin#6319]
## Describe the bug
The Aqara Vibration Sensor appear with just a Door Lock cluster besides the Basic one.

![image](https://user-images.githubusercontent.com/28068256/189500369-84afa8f2-ac0c-49ab-992c-86ccba593372.png)
![image](https://user-images.githubusercontent.com/28068256/189500406-9ce90a5f-176a-4575-919c-1f29b143a6d2.png)
I'm fairly certain this was not the case in 2.16.1

## Steps to reproduce the behavior

On 2.18.1 (and probably other versions using DDFs?):
Open the cluster list for the Vibration Sensor.
When coming from 2.16.1 it looked like there was a mix of old and new clusters.
After deleting and re-including the sensor, cluster list becomes as in description above.
Tried 2 times, same result.

## Expected behavior

Was not expecting the Door Lock cluster? 
Did expect a cluster where I could configure the sensitivity?

## Screenshots
See description

## Environment

 - Host system: PC
 - Running method: Ubuntu
 - Firmware version: (26400500)
 - deCONZ version: (2.18.01)
 - Device: (ConBee I
 - Do you use an USB extension cable: (yes)
 - Is there any other USB or serial devices connected to the host system? If so: Which? A Z-Wave stick

## deCONZ Logs

Not sure what to log here?

## Additional context

REST API is OK:
```
{
  "config": {
    "battery": 100,
    "on": true,
    "pending": [],
    "reachable": true,
    "sensitivity": 11,
    "sensitivitymax": 21,
    "temperature": 2600
  },
  "ep": 1,
  "etag": "2501ec1f4eab8781902b4c5c64ea19eb",
  "lastannounced": null,
  "lastseen": "2022-09-10T20:22Z",
  "manufacturername": "LUMI",
  "modelid": "lumi.vibration.aq1",
  "name": "Vibration Sensor",
  "state": {
    "lastupdated": "2022-09-10T20:22:06.456",
    "orientation": [
      -2,
      0,
      88
    ],
    "tiltangle": 20,
    "vibration": true,
    "vibrationstrength": 15
  },
  "swversion": "20180130",
  "type": "ZHAVibration",
  "uniqueid": "00:15:8d:00:08:52:a6:2c-01-0101"
}

```

**Comment by SwoopX** [comment]
You need to discuss that with Xiaomi 🙂
