### ISSUE TITLE
Immax NEO Smart kontroler (L) V4 (_TZ3000_llfaquvp)

### ISSUE THREAD

**Issue by Asuanin** [dresden-elektronik/deconz-rest-plugin#6325]
## Device

- Product name: Immax NEO Smart kontroler (L) V4 2-Button
- Manufacturer: _TZ3000_llfaquvp
- Model identifier: TS0012
- Device type : Light (Dimmer)

![image](https://user-images.githubusercontent.com/28214903/189712702-e3f6aedf-2672-4464-b9a5-1575c68b46c9.png)

### Basic
![image](https://user-images.githubusercontent.com/28214903/189713397-a414eaee-9d80-486f-b24f-034568e57bea.png)

![image](https://user-images.githubusercontent.com/28214903/189713464-d4badfa8-113d-475f-b238-5e643e45f468.png)

![image](https://user-images.githubusercontent.com/28214903/189713641-fa0582ad-a70d-497f-809a-62c9f050bf93.png)

### Identify
![image](https://user-images.githubusercontent.com/28214903/189714000-e3fd326b-24c5-48cb-88f1-cdc660914e95.png)

### Groups
![image](https://user-images.githubusercontent.com/28214903/189714157-4ece0ad3-905d-4eca-b5e5-bc180ef716b0.png)
![image](https://user-images.githubusercontent.com/28214903/189714157-4ece0ad3-905d-4eca-b5e5-bc180ef716b0.png)

### Scenes
![image](https://user-images.githubusercontent.com/28214903/189714255-6c0d50b7-66c8-433b-8c31-fd16a0b228be.png)
![image](https://user-images.githubusercontent.com/28214903/189714755-704506fc-48a9-4d91-9cfe-f85049c7ef6c.png)

### On/Off
![image](https://user-images.githubusercontent.com/28214903/189714434-f50b09d2-4891-4a86-a727-c2effd79bd5c.png)
![image](https://user-images.githubusercontent.com/28214903/189714861-c492a0b4-908d-47fb-9054-e0615c0d00a6.png)

**Comment by Smanar** [comment]
Hello, can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_llfaquvp",
  "modelid": "TS0012",
  "vendor": "NEO,
  "product": "Immax NEO Smart kontroler",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by Asuanin** [comment]
@Smanar 
Thanks, this works fine, i'll try it with a dimmable bulb tomorrow.

**Comment by Asuanin** [comment]
Information about dimmable feature is from manufacturer (Immax)

**Comment by Asuanin** [comment]
Ok, the manufacturer is lying, even the official app over Lidl gateway does not support dimming

Test OK, Smanar's DDF works

It can be closed

**Comment by Smanar** [comment]
Ok , have added the device here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6244

**Comment by Asuanin** [comment]
Thank you and have a nice day
