### ISSUE TITLE
Edit Node Name not working

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#6329]
## Describe the bug
Cannot Edit Node name
Set node name, as shown in the user manual, does not work. 

## Steps to reproduce the behavior
Open Deconz
Select Any Node
Try to select the text under Node Info -> Common Info -> Name
notice you cannot select anything, no text box appears, and any keyboard entries just jumps to another cell in the table - no way seemingly to edit the Name

## Expected behavior
Node Info -> Common Info -> Name should be editable directly in deConz
user manual supports this (see screenshot)

## Screenshots
attached

## Environment
2.18.1
Windows 10

## deCONZ Logs
not relevant

## Additional context
assuming its a bug since deConz is often used to provide data to other system. Thus, having 5, 10, 100, etc devices named the default name of say "Multisensor" with a number after it does not allow for unique identification methods.

**Comment by Mimiix** [comment]
Can you please fill in the template as intended?

**Comment by Ltek** [comment]
Sorry, thought it was pretty straightforward. The docs show we can, and we cant. I dont think its dependent on OS or such. I'll update the first post

**Comment by BabaIsYou** [comment]
> I dont think its dependent on OS or such

I can confirm that it doesn't work that way too on RPi with v2.15.2-beta

**Comment by SwoopX** [comment]
Node names cannot be edited via deconz GUI, it's recommended to do it via REST API.

**Comment by Ltek** [comment]
@SwoopX  You have not provided a justification for not allowing Node Names to be edited when it can do EVERYTHING ELSE to a node. Its nonsensical to disallow a name change. 
According to @Smanar ...
"Deconz manage the zigbee network
The API plugin is just a part of deconz
You can have a device in deconz but not in the API"

.. thus deConz and the API are separate entities. Thus, deConz would be using the REST API to make the Node Name change, yes?

your answer was basically saying something like, "see this fantastic file system management app we have! You can copy files, add new ones, delete them, move them around, view and edit the contents... but you cannot change a file name. You'll need to use a different app for that. We dont want you to do 'everything' in one place... that would be too convenient."

**Comment by Smanar** [comment]
Lol, it s more a "working issue".
In deconz you have only 1 node displayed, but in the API you can have 5/6 entries for the same device.
So there is problem wich one deconz need to use as name for the node name is deconz (and can make a new debate on this problem too)
And worse, If I change the node name is deconz ? Wich one entry in the API I need to rename too ?

Previously this feature was to change a setting in the device, but not supported by all devices, so was deprecated.

**Comment by Ltek** [comment]
The ask is to edit "Name" (screenshot attached). Seems like about the most simple ask possible?
This field is used to name the device in Deconz's UI and JowiHue/Homseer - and I'd assume ALL other apps accessing the REST API.

![Capture](https://user-images.githubusercontent.com/1626802/193899353-7b21031f-3df8-4159-ad77-f0616dbf4c02.JPG)

**Comment by Mimiix** [comment]
As the issue has been closed by a dev and a answer is given, proceeding the discussion doesn't have any use at this moment.
