### ISSUE TITLE
Hue Motion Sensor darkness threshold and offset

### ISSUE THREAD

**Issue by saurabh984** [dresden-elektronik/deconz-rest-plugin#634]
I'm getting a response saying the following for both `tholdoffset` and `tholddark`

```
[
    {
        "error": {
            "address": "/sensors/16/config/tholdoffset",
            "description": "parameter, tholdoffset, not available",
            "type": 6
        }
    }
]
```

How do I set darkness level and threshold for Hue Motion Sensor?

**Comment by manup** [comment]
The configuration should be set for the light sensor resource, it is separated from the motion sensor.

**Comment by saurabh984** [comment]
@manup That’s the response I got from ZHALightLevel sensor :-(

**Comment by ebaauw** [comment]
Very odd, the `config` object should contain `tholddark` and `tholdoffset`.  I don't know how they can be missing.  What version of deCONZ are you running?  How long ago (and with what version) did you pair the sensor?

Can you please check:
- Does the `uniqueid` end with `-02-0400`?
- Do you see ZHAPresence and ZHATemperature resources for same Hue motion sensor?  Their `uniqueid` should start with the same MAC address.
- What does the database record for this sensor resource look like?  Are the threshold attributes missing from the `config` there as well?

I think it's best to delete the sensor resources though the REST API, and the node from the deCONZ GUI (no need to reset the sensor).  Then exit deCONZ and physically delete the corresponding records from the database.  Then restart deCONZ and re-pair the sensor.

Alternatively, if you're comfortable changing the database manually, add the attributes there (make sure to exit deCONZ first).

**Comment by saurabh984** [comment]
Hi Erik,

Running v2.05.28 with firmware 0x261f0500. Paired couple of days ago with v2.05.28 and 0x261f0500

- `uniqueid` ends with `ba-02-0400`
- Yes both are present with same MAC address ending with `uniqueid` `ba-02-0406` and `ba-02-0402`
- They are missing in DB. Config column only had the attributes as the API response.

Added them manually to DB now testing.

Thanks

**Comment by ebaauw** [comment]
Have you restarted deCONZ since you paired the sensor?  Looking at the code, it would seem that `config.tholddark` and `config.tholdoffset` are only created upon restoring the sensor from the database, but not on pairing.

**Comment by saurabh984** [comment]
Nope. Just restarted after editing the DB

**Comment by ebaauw** [comment]
That might explain it.  Also, it would seem that `state.lux`, `state.dark`, and `state.daylight` might be missing right after the sensor has been paired, until the first time the value of `state.lightlevel` is set.

**Comment by saurabh984** [comment]
Thanks Erik. That seems to have fixed it!
