### ISSUE TITLE
EVA Han Powermeter

### ISSUE THREAD

**Issue by sevrinrobstad** [dresden-elektronik/deconz-rest-plugin#6343]
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: EVA
- Model identifier: Meter REader
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/23063479/191747963-044dfa3b-86c5-4bf1-b90a-fde72f6217b1.png)
![image](https://user-images.githubusercontent.com/23063479/191748254-a359e7a4-00eb-4970-8ab3-459cf080d9f1.png)
![image](https://user-images.githubusercontent.com/23063479/191748850-be1382d7-40dc-404d-8df5-67d70547c816.png)
![image](https://user-images.githubusercontent.com/23063479/191748920-2d18d0ae-392a-4472-9ed1-1ee60909a856.png)
![image](https://user-images.githubusercontent.com/23063479/191749009-84c5b827-0efa-4340-9549-832dcb1e46f1.png)
![image](https://user-images.githubusercontent.com/23063479/191749088-3a6e8aa2-68ce-4683-96ac-52b2fd5698b7.png)

Another user posted a request for this device here
https://forum.phoscon.de/t/eva-metering-han-powermeeter/1941

Link to device:
https://shop.evasmart.no/produkt/smarthus/maleravleser

**Comment by sevrinrobstad** [comment]
I hope someone can add this at some point..

**Comment by sevrinrobstad** [comment]
bump?

**Comment by Smanar** [comment]
Hello can you share the cluster list pls ? to see wich one cluster are used by the device ?

**Comment by sevrinrobstad** [comment]
Hi, and thank you. Yes - this seems to works. I had to change the "power" sensor from attribute 0x0508 to 0x0304, then it turned up with usage in WATT as of right now.

**Comment by Smanar** [comment]
>I had to change the "power" sensor from attribute 0x0508 to 0x0304, then it turned up with usage in WATT as of right now.

Hu ?
You have changed it just in the bind part ? and 0x0508 is the current, I have used 0x050B for the power. But It can't work as it, as I have set all the DDF by defaut, and legacy code don't use 0x0304.

To have it working need to correct it in the bind part and make

```
        {
          "name": "state/power",
          "refresh.interval": 360,
          "parse": {
            "at": "0x0304",
            "cl": "0x0b04",
            "ep": 2,
            "eval": "Item.val = Attr.val",
            "fn": "zcl"
          },
          "read": {
            "at": "0x0304",
            "cl": "0x0b04",
            "ep": 2,
            "fn": "zcl"
          }
        }
```

**Comment by sevrinrobstad** [comment]
Yea, I did the change in the code as you describe over.
The Phoscon/help/API Info/sensors trick was good , 
It looks like more info is coming through coming through to phoscon, so that make's it HA's fault.
But the most important one was power, so I'm quite happy :)

```
  {
    "config": {
        "on": true,
        "reachable": true
    },
    "etag": "xxxxxx",
    "lastannounced": null,
    "lastseen": "2022-11-08T19:20Z",
    "manufacturername": "Eva",
    "modelid": "Meter Reader",
    "name": "Power 58",
    "state": {
        "current": 4700,
        "lastupdated": "2022-11-08T19:20:54.598",
        "power": 1613,
        "voltage": 2370
    },
    "swversion": "2.0",
    "type": "ZHAPower",
    "uniqueid": "xxxxx"
}
```

**Comment by Smanar** [comment]
>so that make's it HA's fault.

Can be just a synchronisation issue.
It's for that I m asking if the sensor is not working (real issue) or not present, probably a synchronisation problem (can happen if HA have included the device before the DDF was finished, so the device not completely in the API, and HA scan entries only 1 time)

Need some convertion too, like need voltage / 10, you know how to do that using DDF ? `Item.val = Attr.val / 10`
