### ISSUE TITLE
Tuya Remote 4 switch

### ISSUE THREAD

**Issue by Remc000tje** [dresden-elektronik/deconz-rest-plugin#6344]
## Device

- Product name: Remote 4 Keys 12 Scenes.
- Manufacturer: _TZ3000_dziaict4
- Model identifier: TS0044
- Device type : 
  - Remote
  - Switch (4x)

optical it is exactly the same as: Remote 4 Keys 12 Scenes Zigbee ID: TS0044 | _TZ3000_ygvf9xzp

## Screenshots
![image](https://user-images.githubusercontent.com/87435319/191771255-3dc4ed49-3d94-4f77-bf28-f7fd840b8bed.png)
![image](https://user-images.githubusercontent.com/87435319/191771433-86cdd01c-0572-4399-9cf9-ee42266b0dc1.png)
![image](https://user-images.githubusercontent.com/87435319/191771524-c202ccbb-bdd8-4f27-ad0c-05ff8f2b1be9.png)
![image](https://user-images.githubusercontent.com/87435319/191772089-b69eca43-b53c-4fe8-92d6-991c6f7e8ba7.png)
![image](https://user-images.githubusercontent.com/87435319/191772282-eab836e2-3b39-4213-948a-9c64c2c5d778.png)
![image](https://user-images.githubusercontent.com/87435319/191772905-00f082f0-6132-42e5-a2e1-dd007651e5ff.png)
![image](https://user-images.githubusercontent.com/87435319/191773320-1d01c149-91d3-498e-932a-0ecc7a79fd54.png)

**Comment by Smanar** [comment]
Hello, can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_ygvf9xzp", "_TZ3000_ee8nrt2l", "_TZ3000_dziaict4"],
  "modelid": ["TS0044", "TS0044", "TS0044"],
  "product": "Tuya remote 4 gangs",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl"
          }
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 4,
      "dst.ep": 1,
      "cl": "0x0006"
    }
  ]
}
```

**Comment by Remc000tje** [comment]
It will proabably work, but I have no option to put enter the map where the DDF file is located or where one can edit. 

I am working on a synology VM , with HA Home Assistant 2022.9.4 , Supervisor 2022.09.1 , Operating System 8.2 , Frontend-versie: 20220907.2 - latest.

I tried to SSH into the NAS, but there I cannot find the Deconz location..

gr. Remco

**Comment by Remc000tje** [comment]
it will work, saw it working on other HA. I am not able to edit in my VM, searched for help on many fora.
I can edit the DDF in Deconz itself, but cannot edit "Bindings".

gr. Remco

**Comment by Smanar** [comment]
>it will work, saw it working on other HA

If you can confirm it's working I can make a PR.

>but cannot edit "Bindings".

You can do it with drag and drop https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel (there is a video too)

**Comment by Remc000tje** [comment]
Confirmed working status! please make a PR.

![de4c27eb-02f9-4843-8126-c91c140ab77a](https://user-images.githubusercontent.com/87435319/195994986-18d08438-27f0-42af-a9a6-e96e494f7f64.jpg)
![89d0c526-54b3-4b63-8041-ffb6316ed9cd](https://user-images.githubusercontent.com/87435319/195994990-550eef54-3cef-4708-b5d4-eec42bb3043c.jpg)

**Comment by Smanar** [comment]
Added here  https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6244

**Comment by Remc000tje** [comment]
Thanks Smanar, so in the next update it will work fine.

kind regads, Remco
