### ISSUE TITLE
Tropernic Intelligent Lock TY0A01 

### ISSUE THREAD

**Issue by proggprod** [dresden-elektronik/deconz-rest-plugin#6349]
## Device

- Product name: Tropernic Intelligent Lock, zigbee version
- Manufacturer: _TYST12_bfejtdig
- Model identifier: TY0A01 
- Device type : Please remove all unrelated device types. 
  - Lock
  
- Product link with pictures https://www.aliexpress.com/item/1005004243881094.html

## Screenshots

![image](https://user-images.githubusercontent.com/81530084/192091801-b04bdb99-83ef-41bb-9d77-97575236d6c7.png)

![image](https://user-images.githubusercontent.com/81530084/192091635-43967c00-28fe-4bf9-88c2-283aa5a0f12c.png)
### Basic
![image](https://user-images.githubusercontent.com/81530084/192091667-8440fd79-15b2-4c21-bd65-897de5435453.png)

### Time
![image](https://user-images.githubusercontent.com/81530084/192091687-f5f5ef34-19eb-4f16-816b-093f1e9b6d90.png)

### Groups
![image](https://user-images.githubusercontent.com/81530084/192091714-1f144f33-9d1a-4d14-b9ac-b133d5380f22.png)
![image](https://user-images.githubusercontent.com/81530084/192091719-4a735a2e-030c-42f6-a272-644d227a72b7.png)

### Scenes
![image](https://user-images.githubusercontent.com/81530084/192092008-bf876109-ebb8-4661-a6e2-3e6cfa639ab1.png)
![image](https://user-images.githubusercontent.com/81530084/192091994-85072f41-622d-4995-8fcd-06c26e44095b.png)
![image](https://user-images.githubusercontent.com/81530084/192091748-fda8d107-0174-44fd-ad96-b03ae835ba50.png)

### Tuya specific
![image](https://user-images.githubusercontent.com/81530084/192091755-e851a59f-a24e-4c92-96c8-a899d77f5369.png)

### OTAU
![image](https://user-images.githubusercontent.com/81530084/192091772-31f9b4c5-c417-4ab5-a195-730a16fa6c64.png)

### Time
![image](https://user-images.githubusercontent.com/81530084/192091785-3c24cb19-49c5-4db9-93be-deb0982dcb09.png)

**Comment by proggprod** [comment]
Not solved

**Comment by Mimiix** [comment]
@Smanar Can this be added?

**Comment by Smanar** [comment]
I don't found on google information about DP used by this device "_TYST12_bfejtdig".
And it use the tuya cluster.

**Comment by Tomasz45** [comment]
Ktoś rozwiązał problem ?

**Comment by Smanar** [comment]
I haven't found someone that have find the dpid used by this device
I have found this information https://developer.tuya.com/en/docs/iot/zigbee-doorlock-dp?id=K9fembhbeab0p
But no warranty this devices use the same one, Tuya shit on rules/standard even when they are from them.
