### ISSUE TITLE
Aqara Single Switch Module T1 (No Neutral)

### ISSUE THREAD

**Issue by hermsi94** [dresden-elektronik/deconz-rest-plugin#6350]
## Device

- Product name: Aqara Single Switch Module T1 (No Neutral)
- Manufacturer: LUMI
- Model identifier: lumi.switch.l0agl1
- Device type :
  - Switch 
  
## Screenshots
![image](https://user-images.githubusercontent.com/54680250/192101204-8c38b71f-3493-4ce8-a8a2-42a0064cbda5.png)
![image](https://user-images.githubusercontent.com/54680250/192101296-b66f5d3a-707f-49b4-bb11-55753df4e0d8.png)
![image](https://user-images.githubusercontent.com/54680250/192101374-294602ba-b7b9-4d9e-8410-3b5489f02751.png)

### Basic
![image](https://user-images.githubusercontent.com/54680250/192101720-38083a04-a514-41e8-96ac-679f2e8feaba.png)

### Device Temperature
![image](https://user-images.githubusercontent.com/54680250/192101967-12920622-f61f-4e83-afaf-27ea38f50203.png)

### On/Off
![image](https://user-images.githubusercontent.com/54680250/192101938-b20d9fdf-bddf-4f7f-8a0d-ef3666999021.png)

### Multistate Input (Basic)
![image](https://user-images.githubusercontent.com/54680250/192101909-a7a8b413-004e-41fe-93c1-7aed8cfea943.png)

### Lumi specific
![image](https://user-images.githubusercontent.com/54680250/192102118-72b32cbe-49dc-4ec3-a2e7-7fe9831b00b6.png)
![image](https://user-images.githubusercontent.com/54680250/192102168-8d2c7029-8d0c-4cb3-8f67-4499c32fc905.png)

### OTAU
![image](https://user-images.githubusercontent.com/54680250/192102234-6a7c9265-3662-40b4-bc99-b6db44897f99.png)

**Comment by SwoopX** [comment]
Could you please test the referenced DDF to verify the exposed features are working? Admittedly, some are assumptions based on your screenshots.
