### ISSUE TITLE
New XIAOMI motion detector Aqara 2018 mit Illuminance sensor

### ISSUE THREAD

**Issue by BigWumpus** [dresden-elektronik/deconz-rest-plugin#636]
Hello,
i got a new human motion-detector from XIAOMI, now labeled with Aqara and from 2018.
New ist the illuminance-sensor.
It works with Deconz, but the measurement ist never updated. On an original XIAOMI-Gateway it is running and updating.
![0000 basic](https://user-images.githubusercontent.com/38441066/41201132-79f0d1f6-6cb2-11e8-954c-f7e86b6e84a7.JPG)
![0400 illuminance measurement](https://user-images.githubusercontent.com/38441066/41201133-7a127e00-6cb2-11e8-8961-4ddfd6d7c6a6.JPG)
![0406 occupancy sensing](https://user-images.githubusercontent.com/38441066/41201134-7a345b92-6cb2-11e8-8b06-f762d6c56741.JPG)
![device](https://user-images.githubusercontent.com/38441066/41201135-7a5420bc-6cb2-11e8-9abf-9674081afdbb.JPG)

Maybe you can fix this.

**Comment by GatoPharaoh** [comment]
does the motion part work for you?
I got the exact same sensor - the illuminance value does update for me but  it doesn't detect motion - in the phoscon app it presented as motion sensor - but only shows LUX and temperature(don't know why?)

**Comment by GatoPharaoh** [comment]
this is what it looks like on the web app - as the motion sensor doesn't have a temperature module, I assume deconz just doens't know the (new) sensor model?
![bildschirmfoto 2018-06-16 um 11 56 14](https://user-images.githubusercontent.com/12106737/41497764-5a7e0a42-715c-11e8-9b19-0a7a06905e03.png)

**Comment by GatoPharaoh** [comment]
had some similar trouble with the exact same sensor - what helped for me:

- delete the node
- delete it on the web app
- reset the motion sensor
- restart deconz 
- re-pair it with deconz

**Comment by manup** [comment]
Looks like the ZHAPresence resource wasn't created for some reason. Easiest way to fix this is to start sensor search and reset the sensor with the small button, it should then rejoin and the missing resource should be created.

**Comment by manup** [comment]
All known versions of this sensor should work with recent deCONZ versions.
