### ISSUE TITLE
Tuya Smart Zigbee Temperature And Humidity Sensor, with LCD Display

### ISSUE THREAD

**Issue by bellerG** [dresden-elektronik/deconz-rest-plugin#6362]
Hi,
is there a way to create a DDF for this device?

![image](https://user-images.githubusercontent.com/44829788/192745364-6161f1c7-74e2-4308-a491-27c35e61d5cd.png)

---

Product name: Tuya Zigbee Temperature And Humidity Sensor
Manufacturer: _TZE200_locansqn
Model identifier: TS0601
Device type : Sensor
[Shop Link](https://www.aliexpress.com/item/1005003634353180.html)

## Screenshots

![image](https://user-images.githubusercontent.com/44829788/192744331-de7b6879-3d2b-49d4-a964-7792730d3151.png)
![image](https://user-images.githubusercontent.com/44829788/192744419-3f66da84-5cef-46ad-99f3-21d8baa02735.png)
![image](https://user-images.githubusercontent.com/44829788/192744514-4399cedc-e58d-429e-9e2d-7d91a09cbbfc.png)

**Comment by Mimiix** [comment]
Hi,

Can you please provide all requested screenshots?

**Comment by bellerG** [comment]
> Hi,
> 
> Can you please provide all requested screenshots?

Sorry, here are the remaining cluster attributes:

![image](https://user-images.githubusercontent.com/44829788/192996421-a60194cf-c1fc-47a5-b343-ae1d510f3dbe.png)
![image](https://user-images.githubusercontent.com/44829788/192996481-0b876266-aa73-4131-837f-a45de019ad0c.png)
![image](https://user-images.githubusercontent.com/44829788/192996109-f7fc3c29-13de-45d3-9103-d3c0cbf73d4e.png)
![image](https://user-images.githubusercontent.com/44829788/192996177-65302664-4658-4096-82ae-a783516f53b6.png)
![image](https://user-images.githubusercontent.com/44829788/192996246-8c3aa504-efc2-4cf5-af97-eaff848a0160.png)
![image](https://user-images.githubusercontent.com/44829788/192996682-f1236e1a-eeb4-4c17-94fa-606064d22220.png)
![image](https://user-images.githubusercontent.com/44829788/192996302-c2b3b7dc-bf83-4d3e-975b-7402eada6433.png)

![image](https://user-images.githubusercontent.com/44829788/192997139-73f8b6c6-ddaa-4b3e-b117-034ae337ee55.png)

**Comment by Smanar** [comment]
Can try this one

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_locansqn",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "parse": {"fn": "tuya", "dpid": 2, "eval": "Item.val = 10 * Attr.val;" },
          "read": {"fn": "tuya"},
          "default": 0
        },
        {
          "name": "config/battery",
          "parse": {"fn": "tuya", "dpid": 4, "eval": "Item.val = Attr.val;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/battery",
          "parse": {"fn": "tuya", "dpid": 4, "eval": "Item.val = Attr.val;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = 10 * Attr.val;" },
          "read": {"fn": "none"},
          "default": 0
        }
      ]
    }
  ]
}
```

I have cloned this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/ih-k009_temp_hum_sensor.json

But I don't find the dpid used by this device on other zigbee project, so I m using the same one, if it doesn't work, can you enable deconz log (with "info" and "info_l2") and check for logs with "tuya" when heating the device for exemple.

**Comment by bellerG** [comment]
> Can try this one
> 

Hi Smanar,

Thanks a lot for this. I created the json and restarted the server.

It has now renamed the device (Humidity) and there is a battery indicator.
But the clusters are still the old ones and it still says "Smart Plug" as the device type:

![image](https://user-images.githubusercontent.com/44829788/193205390-3e2cc67f-a1bd-4ab5-972c-1d6f609d86bd.png)

![image](https://user-images.githubusercontent.com/44829788/193204794-83faa208-4d1a-4af1-b631-48a2bb02bfc1.png)

--

This is what I found in the logs:

```
	Zeile  587: 08:29:46:875 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"61","lastannounced":null,"lastseen":"2022-09-30T06:29Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Humidity 61","swversion":null,"type":"ZHAHumidity","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"},"e":"changed","id":"61","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"} (ret = 328)
	Zeile  589: 08:29:46:877 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"62","lastannounced":null,"lastseen":"2022-09-30T06:29Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Temperature 62","swversion":null,"type":"ZHATemperature","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"},"e":"changed","id":"62","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"} (ret = 334)
	Zeile  591: 08:29:46:914 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"61","lastannounced":null,"lastseen":"2022-09-30T06:29Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Humidity 61","swversion":null,"type":"ZHAHumidity","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"},"e":"changed","id":"61","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"} (ret = 328)
	Zeile  592: 08:29:46:916 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"62","lastannounced":null,"lastseen":"2022-09-30T06:29Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Temperature 62","swversion":null,"type":"ZHATemperature","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"},"e":"changed","id":"62","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"} (ret = 334)
	Zeile  593: 08:29:46:955 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"61","lastannounced":null,"lastseen":"2022-09-30T06:29Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Humidity 61","swversion":null,"type":"ZHAHumidity","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"},"e":"changed","id":"61","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"} (ret = 328)
	Zeile  594: 08:29:46:957 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"62","lastannounced":null,"lastseen":"2022-09-30T06:29Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Temperature 62","swversion":null,"type":"ZHATemperature","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"},"e":"changed","id":"62","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"} (ret = 334)
	Zeile 3956: 08:36:43:338 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"61","lastannounced":null,"lastseen":"2022-09-30T06:36Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Humidity 61","swversion":null,"type":"ZHAHumidity","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"},"e":"changed","id":"61","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"} (ret = 328)
	Zeile 3957: 08:36:43:339 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"62","lastannounced":null,"lastseen":"2022-09-30T06:36Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Temperature 62","swversion":null,"type":"ZHATemperature","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"},"e":"changed","id":"62","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"} (ret = 334)
	Zeile 4115: 08:36:58:742 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"61","lastannounced":null,"lastseen":"2022-09-30T06:36Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Humidity 61","swversion":null,"type":"ZHAHumidity","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"},"e":"changed","id":"61","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"} (ret = 328)
	Zeile 4116: 08:36:58:743 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"62","lastannounced":null,"lastseen":"2022-09-30T06:36Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Temperature 62","swversion":null,"type":"ZHATemperature","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"},"e":"changed","id":"62","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"} (ret = 334)
	Zeile 4117: 08:36:58:769 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"61","lastannounced":null,"lastseen":"2022-09-30T06:36Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Humidity 61","swversion":null,"type":"ZHAHumidity","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"},"e":"changed","id":"61","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405"} (ret = 328)
	Zeile 4118: 08:36:58:771 Websocket 172.16.0.11:48046 send message: {"attr":{"id":"62","lastannounced":null,"lastseen":"2022-09-30T06:36Z","manufacturername":"_TZE200_locansqn","modelid":"TS0601","name":"Temperature 62","swversion":null,"type":"ZHATemperature","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"},"e":"changed","id":"62","r":"sensors","t":"event","uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0402"} (ret = 334)

```

**Comment by Smanar** [comment]
That you see in deconz will not change, it's the reality, the type is Smart plug and will stay stay like that.
But it will be updated in the API, can take a look in phoscon / help / API Information / sensors / (61 and 62)
You will be able to see the device json, and I think thoses one will be good, except the temperature/humidity values.

for tuya device handled by DDF core, debug are visible with "info"

```
DBG_Printf(DBG_INFO, "TY_DATA_%s: seq %u, dpid: 0x%02X, type: 0x%02X, length: %u, val: %d\n",
                   rt, seq, dpid, dataType, dataLength, num.s32);
```

And my bad no "tuya" inside but "TY_DATA_"

**Comment by bellerG** [comment]
I will send new dates tomorrow, please don't close yet.

**Comment by bellerG** [comment]
Hi Smanar,

- **the sensor with the values ​​is now displayed over API.**
- the sensor is not yet displayed in Phoscon.
- in DeConz-GUI the clusters for temperature/humidity are not displayed.
- the cluster battery does not exist either (but the icon is displayed)

![image](https://user-images.githubusercontent.com/44829788/194554517-f342e2d0-9f2b-4f84-ac6e-7cb6d3204586.png)

I can find the sensor under "uniqueid":"a4:c1:38:15:c6:80:c2:f2-01-0405" and "uniqueid":"a4:c1:38:15:c6:80:c2: f2-01-0402"
Unfortunately I can't find "TY_DATA_", here's an excerpt:
[debug_INFO+INFO_L2.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/9733931/debug_INFO%2BINFO_L2.txt)

**Comment by bellerG** [comment]
Hi Smanar, 
thx you for your answer.

> > the sensor is not yet displayed in Phoscon.
> 
> f the device json is good I can do nothing for that, can you share one of them from phoscon/help/apiInformation/sensor/X ? You don't have other third app to test ? But if you have value over API, it s probably phoscon that block it.

![image](https://user-images.githubusercontent.com/44829788/194824143-50bce3b2-884e-4a1f-926c-bafa5ec3f3f0.png)
![image](https://user-images.githubusercontent.com/44829788/194824178-6374b9d0-77b2-4ee0-877d-e5d91e25b01d.png)

Does that have to be done directly by Dresden-Elektronik, because the device pushes data, but unfortunately the clusters and settings are not available. e.g. Temperature correction so that the display on the device is also correct. 

> > in DeConz-GUI the clusters for temperature/humidity are not displayed.
> 
> And it will be never displayed, this device don't have them
> 
> > the cluster battery does not exist either (but the icon is displayed)
> 
> Lol, yes, and with red status, good question, I don't see where it is from.

I changed the batteries for the test. It updated immediately even though there is no cluster for it.
![image](https://user-images.githubusercontent.com/44829788/194823333-35b2aab5-0f37-46ab-bd8f-b2b12dbe04cf.png)
**->** 
![image](https://user-images.githubusercontent.com/44829788/194823359-5cc15912-87f5-4422-8c72-ffee81736900.png)

> Same for logs, if it's working, we can forget them.
> 
> So the device is working ATM ? (I mean over API)
Yes exactly, in Phoscon it is not but via the API (ioBroker/Deconz) I have the values.
![image](https://user-images.githubusercontent.com/44829788/194823904-cbb6c002-24f1-4551-bc8c-8adcd4b9a1a3.png)

**Comment by Smanar** [comment]
>Does that have to be done directly by Dresden-Elektronik, because the device pushes data, but unfortunately the clusters and settings are not available. e.g. Temperature correction so that the display on the device is also correct.

You mean the "config/offset" value ? We can use fake cluster in the API, but deconz is the reality.

>I changed the batteries for the test. It updated immediately even though there is no cluster for it.

**Comment by bellerG** [comment]
> > Does that have to be done directly by Dresden-Elektronik, because the device pushes data, but unfortunately the clusters and settings are not available. e.g. Temperature correction so that the display on the device is also correct.
> 
> You mean the "config/offset" value ? We can use fake cluster in the API, but deconz is the reality.

OK, that's a pity, because you can probably set a lot more setttings on the device over the Tuya app/gateway. e.g. also the push intervals from the device. See the video at 0:50 https://www.aliexpress.com/item/1005003634353180.html 

> > I changed the batteries for the test. It updated immediately even though there is no cluster for it.
> 
> Ok, I will ask immedialty how it's possible lol, serioulsy deconz is able to read device json to display icon ?

I found the values ​​for this in the node info:
![image](https://user-images.githubusercontent.com/44829788/195010026-3f2215e4-f94d-4bdd-af2c-07d62979d68f.png)


> BTW if all is working, if the device is full working on third app, tell me if you want to make the PR or if I need to make it ?

Can you do that, I'm not familiar with it. The basic functions battery/temperature/humidity are transferred.

**Comment by Smanar** [comment]
Ha yes there is a setting for the report interval.
But this one is not in the temperature cluster but the tuya one.

DP = 17 = 0x11

I don't have tuya device, but it's perhaps posible using the GUI

**Comment by Smanar** [comment]
Try adding in the DDF

```
        {
          "name": "config/sensitivity",
          "parse": {"fn": "tuya", "dpid": 17, "eval": "Item.val = Attr.val;" },
          "read": {"fn": "none"},
          "write": {"fn": "tuya", "dpid": 17, "dt": "0x2b", "eval": "Item.val"},
          "default": 0
        },
```

**Comment by HahnBenjamin** [comment]
You can try to pick some datapoints from my [ddf](https://github.com/HahnBenjamin/deconz-rest-plugin/blob/tuya_ts0601/devices/tuya/_TZE200_locansqn_temperature_humidity_sensor.json) for this device. I never finished up adding all the datapoints the device due to missing possibilities to map those to the existing attributes available in the DDF editor. Writing DPs to the device used to be a hit and miss, not sure if that was improved in the meanwhile. The latest release of the rest-plugin also enabled the device to successfully perform a time sync.

**Comment by bellerG** [comment]
> Try adding in the DDF
> 
> ```
>         {
>           "name": "config/sensitivity",
>           "parse": {"fn": "tuya", "dpid": 17, "eval": "Item.val = Attr.val;" },
>           "read": {"fn": "none"},
>           "write": {"fn": "tuya", "dpid": 17, "dt": "0x2b", "eval": "Item.val"},
>           "default": 0
>         },
> ```

Ingenious, after a neutart it goes through the API. Not in DeConz, though.

**Comment by Smanar** [comment]
@HahnBenjamin perhaps this PR can help for your problem https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6323

**Comment by bellerG** [comment]
You're gonna have to adjust that:

```
          "name": "state/humidity",
          "parse": {"fn": "tuya", "dpid": 2, "eval": "Item.val = 100 * Attr.val;" },
```

**Comment by bellerG** [comment]
> You can try to pick some datapoints from my [ddf](https://github.com/HahnBenjamin/deconz-rest-plugin/blob/tuya_ts0601/devices/tuya/_TZE200_locansqn_temperature_humidity_sensor.json) for this device. I never finished up adding all the datapoints the device due to missing possibilities to map those to the existing attributes available in the DDF editor. Writing DPs to the device used to be a hit and miss, not sure if that was improved in the meanwhile. The latest release of the rest-plugin also enabled the device to successfully perform a time sync.

The date and time on the LCD was displayed correctly from the beginning. I didn't have to do anything here.

**Comment by Smanar** [comment]
Ok so i just need to correct the humidity ?
But the config/sensitivity is working or not ?

**Comment by bellerG** [comment]
> Ok so i just need to correct the humidity?
 
Yes exactly, only here I had to adjust it.


> But the config/sensitivity is working or not ?

Half like?! The value is displayed in the API and I can change it - it is confirmed. However, the value is reset to the default value of 120 when a temperature change occurs. 

I'll have to keep an eye on it.

**Comment by Smanar** [comment]
Ok so perhaps it's the problem described by @HahnBenjamin , but the swoop PR is still in waiting list.

BTW your DDF is relay more advanced than mine @HahnBenjamin, do you want to make a PR for it ?

**Comment by bellerG** [comment]
> Ok so perhaps it's the problem described by @HahnBenjamin , but the swoop PR is still in waiting list.
> 
> BTW your DDF is relay more advanced than mine @HahnBenjamin, do you want to make a PR for it ?

BTW.: The battery display in DeConZ only works with the DDF from @Smanar, with the DDF from @HahnBenjamin it is not displayed.

**Comment by Smanar** [comment]
It's because he use
` "name": "state/battery",`

And need to use `config/battery` for sensor

**Comment by HahnBenjamin** [comment]
I'll adjust the config for the device, try to add the missing data points and file a PR when done

**Comment by bellerG** [comment]
> I'll adjust the config for the device, try to add the missing data points and file a PR when done

I can then test it when you have adjusted it.
