### ISSUE TITLE
Feature Request: Trigger adding of new devices via API

### ISSUE THREAD

**Issue by Owlbertz** [dresden-elektronik/deconz-rest-plugin#6365]
Hi,

I would like to have the possibility to trigger the adding of new devices via a REST-API endpoint.
When installing new devices I need to log into my laptop in order to trigger this manually because the mobile version does not have the button due to the responsive design.

**Comment by Mimiix** [comment]
Hi,

It doesn't belong here, but this is already possible with rest api:

https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/configuration/#modify-configuration

Permit Join.

Further questions, please ask on the forums :)

**Comment by Owlbertz** [comment]
Thanks a lot. Seems to be exactly what I was looking for.
