### ISSUE TITLE
Namron ZigBee RGB Remote 4512706

### ISSUE THREAD

**Issue by olemr** [dresden-elektronik/deconz-rest-plugin#6371]
## Device
![image](https://user-images.githubusercontent.com/28068256/193347397-5f3d9b80-3978-47f4-bcb9-add03b9187a4.png)

- Product name: Namron ZigBee RGB Remote 4512706
https://www.elektroimportoren.no/namron-zigbee-rgb-fjernkontroll/4512706/Product.html
- Manufacturer: 
- Model identifier: 
![image](https://user-images.githubusercontent.com/28068256/193347365-af83709b-94f7-498a-97bf-9e33d2ac0b49.png)
- Device type : 
  - Remote

## Screenshots

  - Endpoints and clusters of the node 
![image](https://user-images.githubusercontent.com/28068256/193349706-5c539a66-c4dd-40f8-a06c-cec3431a6af6.png)

  - Node Info panel
![image](https://user-images.githubusercontent.com/28068256/193348314-6e14d888-14c8-4d97-ad8c-b081e0414316.png)

### Basic
![image](https://user-images.githubusercontent.com/28068256/193348901-6731c4b7-2154-4148-8311-07048f467ddf.png)
Same for all 4 channels:

### Identify
![image](https://user-images.githubusercontent.com/28068256/193350151-f4b7acd3-76eb-4323-ac41-73a65a173361.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/28068256/193350332-1ca4ce0c-6855-453c-b900-09348c7e30c1.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/28068256/193350247-f1f5e50a-1311-412d-8789-973709f2c649.png)
![image](https://user-images.githubusercontent.com/28068256/193350408-50405b1f-4529-44bc-a556-7d4e59a98d70.png)

![image](https://user-images.githubusercontent.com/28068256/193412943-2b5553e1-0727-4345-90be-e64b06c6620f.png)

https://forum.phoscon.de/t/namron-zigbee-rgb-remote-4512706/2538?u=omr

**Comment by Mimiix** [comment]
Reoepend on request by the user.

**Comment by steinis123** [comment]
Status?

**Comment by Mimiix** [comment]
Reopened on request.

@Smanar or @BabaIsYou , are you able to help out?

**Comment by Smanar** [comment]
Aouch, lol, yeah, not a basic device ^^
I hope all bind/report are not used ....

**Comment by olemr** [comment]
Thanks for chiming in ....
Away for the weekend.
Will report back later next week with logs.
