### ISSUE TITLE
_TZE200_cpmgn2cf

### ISSUE THREAD

**Issue by flowerbob** [dresden-elektronik/deconz-rest-plugin#6381]
## Device

- Product name: Zigbee Radiator Actuator
- Manufacturer: _TZE200_cpmgn2cf
- Model identifier: TS0601
- Device type : 
  - Thermostat

([aliexpress.com/item/1005003033044081.html](url))

## Screenshots
![image](https://user-images.githubusercontent.com/53487904/193469997-1dc0791e-5019-4b25-9b48-16c0e7cbc23a.png)
![image](https://user-images.githubusercontent.com/53487904/193470111-5e82f014-f373-4d89-b65a-0dd293346445.png)
![image](https://user-images.githubusercontent.com/53487904/193470137-2bce48f8-55bc-45ba-9214-da85c3a5aec1.png)
![image](https://user-images.githubusercontent.com/53487904/193470151-c9a6d6a1-aaf3-4b07-ba8d-21dd794a98b8.png)

**Comment by Piorko** [comment]
I've exactly the same issue with _TZE200_cpmgn2cf. HA deconz plugin: 6.17.0, deconz: 2.19.1.

**Comment by p-git1** [comment]
The reason is an incomplete implementation in the API code. See [this thread in the phoscon forum](https://forum.phoscon.de/t/tuya-trv-tze200-cpmgn2cf-not-pairing-correctly/2698/4)

After adding the mentioned mapping line in the code and a recompile it works for me now.
