### ISSUE TITLE
Hue Motion Sensor | new HW release / revision 

### ISSUE THREAD

**Issue by andi-bar157** [dresden-elektronik/deconz-rest-plugin#6382]
## Describe the bug

There seems to be a new hardware revision of the Hue Motion Sensor (SML004) which seems to be creating a lot of APS delays - at least in my case. I am running a network of about 92 with about 50 routers, so my mesh is pretty stable and good.

I am running two old revisions (SML002) and two of the new one. Swapping the installation spots / sensor inbetween did not fix the issue. So i feel like this is related to the hardware revision and not

## Screenshots

Clusters of the SML004 - hew hardware revision:

![grafik](https://user-images.githubusercontent.com/28999192/193470635-722fe0d8-a0fe-4436-8f79-318231aaa3b3.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470643-a9f42b6d-7011-4952-9edb-12489732c062.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470652-1eb63e90-141c-4a02-a9c5-5cb7e2f56b71.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470661-387c364d-4c53-4a9e-8b16-b30f6cd7a7a3.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470673-257e60cf-5a5b-4b9b-ab9e-1a1d9429bac1.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470681-ce59d013-eb52-4fd5-b486-8040c9e3f678.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470732-362874a1-ec8d-435c-9bed-b2a33ab758a8.png)

Clusters of the the SML002 - old hardware revision:

![grafik](https://user-images.githubusercontent.com/28999192/193470766-11c9f6a5-c4a7-4f45-bf78-525093da60e8.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470776-a368de44-0e75-4c1d-ba8b-b845693208f7.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470782-9e3f5b7b-816b-42c3-9f12-95e995ad535a.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470787-fd5027f7-7b5b-4183-8780-c1ed5a077d38.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470797-79dc6aa3-23e2-4f13-8dd9-b10b660135e3.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470828-769953f0-0023-4901-aff2-d05d31ef6a68.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470836-30b82f69-65d4-4809-9288-4f07764a7604.png)
![grafik](https://user-images.githubusercontent.com/28999192/193470841-26742909-f8e7-4183-aec9-a29d24c17ca1.png)

## Environment

![grafik](https://user-images.githubusercontent.com/28999192/193470883-15f5142d-5fd7-490d-93ae-d1de116fd7e2.png)

-->

 - Raspberry Pi 4B  - 2GB 
 - Home Assistent deCONZ Add-on
 - Firmware version: 26780700
 - deCONZ version: 2.18.02 / 19.9.2022
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: no

## deCONZ Logs

Will be provided as needed!

**Comment by andi-bar157** [comment]
dear @close-issue-app

fixxed as requested :)

**Comment by ebaauw** [comment]
The 2022 revision of the Hue outdoor motion sensor has been around for quite some time.  I think support was added in May.  I refactored that to use DDF in July in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6164.  I have exactly the same model (same _Date Code_ and same _SW Build ID_) as you, and it's working just fine.

**Comment by Mimiix** [comment]
@andi-bar157 I think it would be best to ask this on discord or the forus. As @ebaauw mentions it works for him and he added support himself.
