### ISSUE TITLE
Can't unbind / properly delete philips hue wall module

### ISSUE THREAD

**Issue by tamueller** [dresden-elektronik/deconz-rest-plugin#6388]
## Describe the bug
When I delete a philips wall module device using phoscon or deconz it does not go into pairing mode again. This works, when I delete a wall module from the philips hue or from zigbee2mqtt

This is a huge problem, since I want to move 8 wall modules from conbee II / deconz to zigbee2mqtt and reaching the reset-button requires a lot of work, since they are hard to reach/install.

## Steps to reproduce the behavior

1. connect a Philips hue wall module
2. remove a Philips hue wall module
3. try to connect it again without using the reset button.

The problem appears with deconz as well as with phoscon.

## Expected behavior

After removing the device, it should go into pairing mode (LED should be blinking every few seconds)

## Environment

 - Host system: (Raspberry Pi / PC / NAS): 
 - Running method: (Raspbian / Ubuntu / Home Assistent deCONZ Add-on / Marthoc Docker container / Windows / Virtual Machine)
 - Firmware version: (26720700)
 - deCONZ version: 2.18.2
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? no

**Comment by tamueller** [comment]
I can only find "delete" in deconz app, and no way to add any options. If anyone knows of a way to do this using phsocon or deconz, that would be nice.

**Comment by tamueller** [comment]
@Smanar I just tried deleting with the Rest-API, and the problem still remains. I tried: 
curl --location --request DELETE '172.30.33.3:40850/api/*********/sensors/50?reset=true'
I got a "success", and the wall module was removed from descon, but it's still not in pairing mode.

**Comment by Smanar** [comment]
Try with

`curl -H 'Content-Type: application/json' -X DELETE -d '{"reset": true}' http://172.30.33.3:40850/api/*****/sensors/50`

**Comment by tamueller** [comment]
I get:
`[{"success":{"/sensors/53/reset":true}}]`
but the device is still not set back to pairing mode.

**Comment by tamueller** [comment]
Some further information: I just used an old backup to restore my homeassistant - and suddenly all the devices that I have removed in deconz are showing up again, and are still paired. I deleted them before the backup was made, so it's natural that they still show up in the deconz DB, but the device also seems to think it's still paired.

**Comment by Smanar** [comment]
>but the device also seems to think it's still paired

If they are still working, yes, miss a "leave" zigbee request somewhere ....

**Comment by tamueller** [comment]
@Smanar 
Is there anything I can do to help you debug this?
I reproduced it with another philips hue wall module, so it's not a quirk in that specific unit.

**Comment by Smanar** [comment]
Honneslty IDK if this feature have already worked or not,, never tried on my side.
There is a "leave" request with a shortcut, but it's a "leave with rejoin".

Perhaps @ebaauw or @manup  know if there is a way to make a device leave the network using deconz ?

**Comment by tamueller** [comment]
@ebaauw / @manup ping? Do you have any ideas how to leave the network and bring the device back to pairing mode?

**Comment by ebaauw** [comment]
Leaving the network basically means that the device forgets the network key and no longer communicates with other devices on the network.  Typically there’s two ways this can be made to happen: someone (the gateway) asks the device to leave, without rejoining; or the device is factory reset.  There’s also some documented cases where devices spontaneously decide to leave the network if they don’t get an expected response.

When you delete a node from the GUI, deCONZ asks (should ask?) the device to leave the network.  Most of the times this works for devices with _Receiver on when idle_, but fails for sleepy devices (like the hue wall module).  If you delete a resource through the API, you need to specify a body to the DELETE  to make the API plugin tell the device to leave.  Not sure by heart what that body is, but should be documented somewhere (probably in a closed GitHub issue).  I don’t know if Phoscon actually does this (I don’t use Phoscon).  If the leave request isn’t sent or received, you end up in a situation where the API plugin no longer knows the device, but the device is still part of the network, reacting to group commands, or sending commands to bound groups or lights.  Typically the node with re-appear in the GUI when deCONZ sees any traffic from it, but you need to put deCONZ in pairing mode to re-create the resources.

When you bluntly factory-reset a device, the node in the GUI and the API resources remain, but are no longer able to interact with the device.  Upon re-pairing, the resources are “re-connected” to the device.

I think in your case, you need to factory-reset the hue wall module, using the physical reset button on the device.  Check the manual whether you need to hold it or press it several times in succession or something, I always forget which device wants what.  If it is still part of the network, you might be able to make it re-appear by putting deCONZ in pairing mode and pressing a push button or flipping a rocker.  Then try and send a _Factory Reset_ from the GUI (in the _Basic_ cluster, while pressing/flipping to make sure the module is awake.

**Comment by tamueller** [comment]
> I think in your case, you need to factory-reset the hue wall module, using the physical reset button on the device.
> If it is still part of the network, you might be able to make it re-appear by putting deCONZ in pairing mode and pressing a push button or flipping a rocker. Then try and send a _Factory Reset_ from the GUI (in the _Basic_ cluster, while pressing/flipping to make sure the module is awake.

Hi, thanks for your answer. I tred the {"reset":true}, but it did not put the device into factory reset.
Also if the device is working normally in the deconz network, sending the factory reset doesn't seem to work. When I go into the basic cluster, and press the "exec" button beneath "Reset to factory Defaults" it goes to "executing" and then goes back to no text, but the device is still in the network.

**Comment by ebaauw** [comment]
It can only receive the request when its radio is on.  Make sure to keep flipping it to force it to be awake.  Maybe try reading attributes in the GUI to get a feel for when the device wakes.  It usually takes me a couple of attempts.
