### ISSUE TITLE
[Device request] YNOA smart Plug zigbee 3.0

### ISSUE THREAD

**Issue by Delusional112** [dresden-elektronik/deconz-rest-plugin#6390]
## Device

- Product name: YNOA smart Plug zigbee 3.0
- Manufacturer: LDS
- Model identifier: ZBT-ONOFFPlug-D0009
- Device type : Please remove all unrelated device types. 
  - Switch
  - Other: Power metering

## Screenshots

<img width="445" alt="image" src="https://user-images.githubusercontent.com/79289457/193664472-0b43dae7-747d-4acb-9728-d4dc379ad248.png">

<img width="379" alt="image" src="https://user-images.githubusercontent.com/79289457/193647842-38554e89-4be5-4370-8fb1-d46f21fa6df9.png">

<img width="263" alt="Schermafbeelding 2022-10-03 om 22 03 54" src="https://user-images.githubusercontent.com/79289457/193668753-29d0bcac-c5b1-41c3-a192-3407f82e5b83.png">

### Basic

<img width="379" alt="image" src="https://user-images.githubusercontent.com/79289457/193647997-80359314-ba75-4863-ad3a-e736c7cae43d.png">

### Identify

<img width="386" alt="image" src="https://user-images.githubusercontent.com/79289457/193648098-cdcbc7ac-38f1-4c25-9801-07add6f4ec0b.png">

### Groups

<img width="381" alt="image" src="https://user-images.githubusercontent.com/79289457/193648416-c00e3091-0d17-43df-957f-9a2c490cf1b1.png">

### Scenes

<img width="386" alt="image" src="https://user-images.githubusercontent.com/79289457/193648484-5efcb906-5c0f-4aa5-9484-11c161f59cd1.png">

### On/Off

<img width="387" alt="image" src="https://user-images.githubusercontent.com/79289457/193648540-6954a229-b9a5-4245-b8c2-928261b7fc94.png">

### Level Control

<img width="382" alt="image" src="https://user-images.githubusercontent.com/79289457/193649615-26a2187e-42cb-4581-9e96-863b36c83930.png">

### Simple Metering

<img width="386" alt="image" src="https://user-images.githubusercontent.com/79289457/193649767-64f68be3-6bcd-408b-982d-b70a1a50825b.png">

### Diagnostics

<img width="380" alt="image" src="https://user-images.githubusercontent.com/79289457/193649870-bda7232d-bbc7-4d7d-9d20-2e383b40b488.png">

### Other clusters that are not mentioned above

<img width="389" alt="image" src="https://user-images.githubusercontent.com/79289457/193649990-5a4fcd65-fd7a-4be7-9448-59e3662947ce.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/79289457/193650133-ee04e4bd-be2a-457a-9e71-16f3abd10f16.png">

**Comment by SwoopX** [comment]
Can you please:
- update the issue name
- Correct the model identifier typo at the top
- Add the requested screenshot of the available clusters

Thanks!

**Comment by Smanar** [comment]
Hello still missing the cluster list (the node picture), to see for exemple the Endpoint used by the device
But I think like all plug the on/off is working but not the power measurement ?

So generaly you can take a lambda DDF and just edit the model ID and the manufacture name, for exemple this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_ksw8qtmt_plug_nous_a1z.json

**Comment by Delusional112** [comment]
> Can you please:
> 
> * update the issue name
> * Correct the model identifier typo at the top
> * Add the requested screenshot of the available clusters
> 
> Thanks!

Ok, did what you asked.

**Comment by Delusional112** [comment]
> Hello still missing the cluster list (the node picture), to see for exemple the Endpoint used by the device But I think like all plug the on/off is working but not the power measurement ?
> 
> So generaly you can take a lambda DDF and just edit the model ID and the manufacture name, for exemple this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_ksw8qtmt_plug_nous_a1z.json

I'm sorry, just added it to the post. I tried something myself with de DDF editor, but it didn't work out. This is the first time a have a device that is not supported.

**Comment by Smanar** [comment]
Still missing the cluster list ^^, it s the more important capture, it s the same than the first one here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

I can't help on incomplete issue, but to make fast, you just need to create a json file with the name you want in the "devices" folder with the same contain than the previous link but with replacing

```
  "manufacturername": "_TZ3000_ksw8qtmt",
  "modelid": "TS011F",
```

By the one from your devices.

The problem is creating the json file, it depend on OS.

**Comment by SwoopX** [comment]
@Delusional112 Please test this one thoroughly

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "LDS",
  "modelid": "ZBT-ONOFFPlug-D0009",
  "vendor": "YNOA",
  "product": "Smart Plug zigbee 3.0",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0B04"
        ],
        "out": [
          "0x000A"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "refresh.interval": 360
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0702"
        ],
        "out": [
          "0x000A"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "refresh.interval": 360,
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "eval": "Item.val = Attr.val * 10;"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x0000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by Delusional112** [comment]
Thanks @SwoopX . I just made a JSON file. Where should I upload it? I have a samba share to the config folder of HA.

**Comment by Smanar** [comment]
It' a little complicated on HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by Delusional112** [comment]
> It' a little complicated on HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

Ok, I read it. This is not something I have the skills for. I'm a man of GUI's and drag & drop :) 

So, I'll have to wait till it's implemented in the next Deconz version.

**Comment by Smanar** [comment]
The problem is we need at least one user test it before adding the device :(

You don't have a way to create a file somewhere and load it using the DDF editor (with the GUI) ?

**Comment by Delusional112** [comment]
@Smanar In the DDF editor you can open and save files. But the paths are in the container as far as I can see. But the problem is that I can't reach the json file that is outside of the container

**Comment by Smanar** [comment]
Was one of my interrogation about the HA docker system.
I know the folder "data" is persistent, but nothing inside, and idk how to access it from inside the docker.
