### ISSUE TITLE
Nedis Zigbee Door / Window Sensor ZBSD10WT

### ISSUE THREAD

**Issue by CaptainFuture78** [dresden-elektronik/deconz-rest-plugin#6408]
## Device

- Product name: Nedis Zigbee door sensor ZBSD10WT
- Manufacturer: _TZ3000_bzxlofth
- Model identifier: TS0203
- Device type :
  - Sensor

### Basic
![grafik](https://user-images.githubusercontent.com/115424623/194908766-82c33e0c-f886-4442-b9e1-29be30108e1a.png)

### Identify
![grafik](https://user-images.githubusercontent.com/115424623/194908900-9ffc2992-02e6-43a3-9678-ff67b37af8bc.png)

### IAS Zone
![grafik](https://user-images.githubusercontent.com/115424623/194909125-e30164c1-722e-4664-a84a-b9191dc825a3.png)

### Power Configuration
![grafik](https://user-images.githubusercontent.com/115424623/194909298-529eac25-7c98-4171-bd58-8764fcf47e0f.png)

### Node Info
![grafik](https://user-images.githubusercontent.com/115424623/194909442-554da4c4-f3b3-471f-94ca-0f402befd633.png)

**Comment by CaptainFuture78** [comment]
I adapted the DDF file for the tuya device here [https://github.com/dresden-elektronik/deconz-rest-plugin/blob/fb9b322a2aa09317bb5123c7d7776e335646640d/devices/tuya/_TZ3000_n2egfsli_door_sensor.json](url).
I added manufacture and model identifier to the file. This solved the issue.

**Comment by Smanar** [comment]
Nice, thx, I will add it too.
