### ISSUE TITLE
deconz IKEA firmware OTAU update loop

### ISSUE THREAD

**Issue by niklerus** [dresden-elektronik/deconz-rest-plugin#6410]
## Describe the bug
Trying to update a number of IKEA bulbs from the Deconz OTAU update panel.
After completed update the update starts over and firmware version is the same as before update attempt.
This repeats over and over.
Deleted a few of them from phoscon, made a factory reset (6x on/off) and started up my old IKEA gateway, added them there, updates were succesful.

## Steps to reproduce the behavior
  1. Open OTAU update panel in Deconz
  2. Select the correct file (verified as working since similar bulb could be updated in IKEA gateway). In this case 
  10046695-1.1-TRADFRI-light-unified-w-2.3.093.ota.ota.signed
  3. Mark the bulb in the node lista and press Update
  4. After completed as Done, after a while it starts over by itself again, indefinitely.
  5. Checking firmware version on Cluster info and pressing Read shows old firmware.

## Expected behavior
Firmware updated to new version according to update file.

## Screenshots

<img width="784" alt="deconz_screenshot" src="https://user-images.githubusercontent.com/1211494/194941816-7b3ee854-fe49-4402-97f4-dcb77b713d69.png">

## Environment

 - Host system: PC
 - Running method: Debian 11, Supervised, Home Assistent deCONZ Add-on
 - Firmware version: 26780700
 - deCONZ version: 2.18.12
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? Yes, ESP32

## deCONZ Logs
21:22:19:611 OTAU: send img block rsp seq: 117 offset: 0x00033C06 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:22:19:685 OTAU: img block req fwVersion:0x23093631, offset: 0x00033C37, maxsize: 63
21:22:19:686 OTAU: send img block rsp seq: 118 offset: 0x00033C37 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
172.30.32.2 - - [10/Oct/2022:21:22:21 +0200] "GET /api/1CAF4EDA19/lights/30?_=1665423714301 HTTP/1.1" 200 400 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
21:22:22:660 OTAU: img block req fwVersion:0x23093631, offset: 0x00033C37, maxsize: 63
21:22:22:661 OTAU: send img block rsp seq: 119 offset: 0x00033C37 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:22:22:727 OTAU: img block req fwVersion:0x23093631, offset: 0x00033C68, maxsize: 63
21:22:22:728 OTAU: send img block rsp seq: 120 offset: 0x00033C68 dataSize 12 status: 0x00 0xEC1BBDFFFE3BD3E8
**21:22:22:794 OTAU: upgrade end req: status: 0x00, fwVersion:0x23093631, imgType: 0x4103**
21:22:26:602 OTAU: query next img req: 0xccccccfffe8b59fb mfCode: 0x1224, img type: 0x138E, sw version: 0x00000028
21:22:26:606 OTAU: send query next image response: OTAU_NO_IMAGE_AVAILABLE
172.30.32.2 - - [10/Oct/2022:21:22:26 +0200] "GET /api/1CAF4EDA19/sensors/new HTTP/1.1" 200 50 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:22:30 +0200] "GET /api/1CAF4EDA19/lights/10?_=1665423714302 HTTP/1.1" 200 401 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:22:32 +0200] "GET /api/1CAF4EDA19/lights/10?_=1665423714303 HTTP/1.1" 200 401 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:22:43 +0200] "GET /api/1CAF4EDA19/lights/27?_=1665423714304 HTTP/1.1" 200 357 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:22:48 +0200] "GET /api/1CAF4EDA19/lights/24?_=1665423714305 HTTP/1.1" 200 393 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
21:22:49:789 aps request id: 82 prf: 0x0104 cl: 0x0019 timeout NOT confirmed to 0xEC1BBDFFFE3BD3E8 (0xDDF6)
172.30.32.2 - - [10/Oct/2022:21:22:50 +0200] "GET /api/1CAF4EDA19/lights/13?_=1665423714306 HTTP/1.1" 200 476 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:22:53 +0200] "GET /api/1CAF4EDA19/lights/11?_=1665423714307 HTTP/1.1" 200 383 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:17 +0200] "GET /api/1CAF4EDA19/lights/3?_=1665423714308 HTTP/1.1" 200 394 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:22 +0200] "GET /api/1CAF4EDA19/lights/19?_=1665423714309 HTTP/1.1" 200 397 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:26 +0200] "GET /api/1CAF4EDA19/sensors/new HTTP/1.1" 200 50 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:28 +0200] "GET /api/1CAF4EDA19/lights/15?_=1665423714310 HTTP/1.1" 200 388 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:29 +0200] "GET /api/1CAF4EDA19/lights/15?_=1665423714311 HTTP/1.1" 200 388 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:30 +0200] "GET /api/1CAF4EDA19/lights/15?_=1665423714312 HTTP/1.1" 200 388 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:37 +0200] "GET /api/1CAF4EDA19/lights/2?_=1665423714313 HTTP/1.1" 200 395 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:42 +0200] "GET /api/1CAF4EDA19/lights/22?_=1665423714314 HTTP/1.1" 200 397 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:52 +0200] "GET /api/1CAF4EDA19/lights/30?_=1665423714315 HTTP/1.1" 200 400 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:23:59 +0200] "GET /api/1CAF4EDA19/lights/23?_=1665423714316 HTTP/1.1" 200 356 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:02 +0200] "GET /api/1CAF4EDA19/lights/11?_=1665423714317 HTTP/1.1" 200 383 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:03 +0200] "GET /api/1CAF4EDA19/lights/13?_=1665423714318 HTTP/1.1" 200 476 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:17 +0200] "GET /api/1CAF4EDA19/lights/15?_=1665423714319 HTTP/1.1" 200 388 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:18 +0200] "GET /api/1CAF4EDA19/lights/15?_=1665423714320 HTTP/1.1" 200 388 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:26 +0200] "GET /api/1CAF4EDA19/sensors/new HTTP/1.1" 200 50 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:41 +0200] "GET /api/1CAF4EDA19/lights/12?_=1665423714321 HTTP/1.1" 200 396 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:41 +0200] "GET /api/1CAF4EDA19/lights/21?_=1665423714322 HTTP/1.1" 200 396 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:42 +0200] "GET /api/1CAF4EDA19/lights/29?_=1665423714323 HTTP/1.1" 200 396 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
172.30.32.2 - - [10/Oct/2022:21:24:45 +0200] "GET /api/1CAF4EDA19/lights/3?_=1665423714324 HTTP/1.1" 200 394 "https://replaced_host_name.duckdns.org/api/hassio_ingress/gwsMBmI8GNAkz4Sg3fCvBJ7ZhVLwPlyqQ1RIrP8t3uI/pwa/devices-lights.html?_v=4999fcacf1bb9743db2a28283e96838be803f9e5,9,1,19&gwid=00212EFFFF0485BF" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
**21:24:57:710 OTAU: invalid update end request for node 0xec1bbdfffe3bd3e8**
21:24:57:710 OTAU: query next img req: 0xec1bbdfffe3bd3e8 mfCode: 0x117C, img type: 0x4103, sw version: 0x23086631
21:24:57:714 OTAU: Match otau version 0x23093631 image type 0x4103
21:24:57:715 OTAU: /data/otau/117C-4103-23093631.zigbee: 212540 bytes
21:24:57:715 OTAU:   offset    456: ota header (56 bytes)
21:24:57:740 OTAU:   offset    512: tag 0x0000, length 0x00030E48 (200270 bytes)
21:24:57:740 OTAU:   offset 200782: tag 0xFFBF, length 0x00000040 (70 bytes)
21:24:57:741 OTAU:   offset 200852: tag 0xFFBE, length 0x00002BA2 (11176 bytes)
21:24:57:742 OTAU:   offset 212028: tag 0xAC1B, length 0x2EC7403B (512 bytes)
21:24:57:742 OTAU: found update file /data/otau/117C-4103-23093631.zigbee
21:24:57:742 OTAU: /data/otau/117C-4103-23093631.zigbee: 212084 bytes
21:24:57:743 OTAU:   ota header (56 bytes)
21:24:57:743 OTAU:   tag 0x0000, length 0x00030E48 (200270 bytes)
21:24:57:750 OTAU:   tag 0xFFBF, length 0x00000040 (70 bytes)
21:24:57:750 OTAU:   tag 0xFFBE, length 0x00002BA2 (11176 bytes)
21:24:57:751 OTAU:   tag 0xAC1B, length 0x2EC7403B (512 bytes)
21:24:57:751 OTAU:   packed 212084 bytes
21:25:05:868 OTAU: img block req fwVersion:0x23093631, offset: 0x00000000, maxsize: 63
21:25:05:868 OTAU: send img block rsp seq: 5 offset: 0x00000000 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:25:05:997 OTAU: img block req fwVersion:0x23093631, offset: 0x00000031, maxsize: 63
21:25:05:997 OTAU: send img block rsp seq: 6 offset: 0x00000031 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:25:06:091 OTAU: img block req fwVersion:0x23093631, offset: 0x00000062, maxsize: 63
21:25:06:091 OTAU: send img block rsp seq: 7 offset: 0x00000062 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:25:06:202 OTAU: img block req fwVersion:0x23093631, offset: 0x00000093, maxsize: 63
21:25:06:202 OTAU: send img block rsp seq: 8 offset: 0x00000093 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:25:06:305 OTAU: img block req fwVersion:0x23093631, offset: 0x000000C4, maxsize: 63
21:25:06:305 OTAU: send img block rsp seq: 9 offset: 0x000000C4 dataSize 49 status: 0x00 0xEC1BBDFFFE3BD3E8
21:25:06:423 OTAU: img block req fwVersion:0x23093631, offset: 0x000000F5, maxsize: 63

**Comment by Mimiix** [comment]
Hi,

Ota bugs are reported here https://github.com/dresden-elektronik/deconz-ota-plugin

I think theres a fix incoming.

As it doesn't belong here, I'm closing it.

Kind regards,

Dennis
