### ISSUE TITLE
Moes Zigbee Temperature Humidity Sensor (KCTW1Z-02)

### ISSUE THREAD

**Issue by xmeir** [dresden-elektronik/deconz-rest-plugin#6419]
## Device
- Product name: Moes Zigbee Temperature Humidity Sensor
- Manufacturer: _TZ3000_ywagc4rj
- Model identifier: TS0201
- Device type :
  - Sensor

## Screenshots
<img width="309" alt="image" src="https://user-images.githubusercontent.com/75183423/195578708-d3eacd77-fac3-4cba-a7c6-c15b0de77cbb.png">

<img width="126" alt="image" src="https://user-images.githubusercontent.com/75183423/195578932-82162eae-cd5e-415b-a591-914ae39b3346.png">

<img width="199" alt="image" src="https://user-images.githubusercontent.com/75183423/195577938-83e1d5ea-2d22-47ac-80f4-77105bca9293.png">

### Basic
<img width="251" alt="image" src="https://user-images.githubusercontent.com/75183423/195582284-c67e3a87-1153-4a38-9ed6-baf6aa65201f.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/75183423/195582357-4ee1ae22-f790-4e47-b0b2-980518f06bca.png">

### Identify
<img width="217" alt="image" src="https://user-images.githubusercontent.com/75183423/195582512-f3823625-f8b9-43f5-8d0a-23b19f4a4c27.png">

### Power Configuration
<img width="224" alt="image" src="https://user-images.githubusercontent.com/75183423/195582090-d35eacab-32da-49be-87cc-dd1e6fe52328.png">
<img width="236" alt="image" src="https://user-images.githubusercontent.com/75183423/195582176-27ce59ca-b333-4c82-b7b7-b0607978646d.png">

### Relative humidity measurement
<img width="249" alt="image" src="https://user-images.githubusercontent.com/75183423/195581827-8929b0e8-ecda-4080-ab8b-95f1d2a9dd53.png">

### Temperature measurement
<img width="231" alt="image" src="https://user-images.githubusercontent.com/75183423/195581700-72776735-f765-4be8-9d2d-a570bd6910a8.png">

**Comment by Smanar** [comment]
This device haven't display ?
Its just a basic sensor ? Can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_ywagc4rj",
  "modelid": "TS0201",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/battery"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "awake": true
        },
        {
          "name": "state/battery"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 600,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 60,
          "max": 600,
          "change": "0x00000064"
        }
      ]
    }
  ]
}
```

**Comment by xmeir** [comment]
Hello Smanar, it worked. Device is now exposed to HA, however HUMIDITY is shown devided by 10 in both Phoscon and HA, and BATTERY state is properly shown in Phoscon, but not exposed at all to HA.

<img width="169" alt="image" src="https://user-images.githubusercontent.com/75183423/195991844-df4c7617-ebbe-42fe-b9df-dc5895343579.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/75183423/195991920-cbe4e3b6-f3b3-4370-a11b-93d16b2ff129.png">

**Comment by Smanar** [comment]
Oups, my bad for battery, can you try this new DDF
And for information, this device is bugged, it use bad value for humidity


```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_ywagc4rj",
  "modelid": "TS0201",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "awake": true,
          "read": {
            "at": "0x0000",
            "cl": "0x0405",
            "ep": 3,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0405",
            "ep": 3,
            "eval": "Item.val = Attr.val * 10",
            "fn": "zcl"
          }
        },
        {
          "name": "config/battery"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 600,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 300,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 60,
          "max": 600,
          "change": "0x00000064"
        }
      ]
    }
  ]
}
```

**Comment by faniskou** [comment]
Yes **verified** 0x01 is working as well
Is better if you do it ( the RP ) ,  is the first time i am reading any code of this project 

the reader i mean this line i am not sure what it does but i do not have it , you now better for sure in this topic       
 "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
     **--->      "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}**

**Comment by Smanar** [comment]
It's just disable the reading, used for poll, not a problem, better to use the "parse" with a good report/binding.

The Pr is here, if you want to test the cleaned DDF https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6602

(Have just removed config/battery as you have said they are not working, and set the EP = 1.

**Comment by faniskou** [comment]
![Screenshot from 2022-12-12 20-35-33](https://user-images.githubusercontent.com/13019563/207126661-9191e25c-ea7b-4bf2-ab38-51293880f281.png)
Yes it is ok

**Comment by faniskou** [comment]
Of course  , because we use only the report function and not the read function, after the change of the ddf the deconz is reporting unreachable until the temp changes or the owner click the device's C / F  button once

**Comment by faniskou** [comment]
@Smanar  I seen this as well https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6577 may it is a duplication

**Comment by Smanar** [comment]
> @Smanar I seen this as well #6577 may it is a duplication

Almost ^^.
This device have some difference, for exemple the humidity don't use the same convertion.

>Of course after the change of the ddf the deconz is reporting unreachable for a while , the owner can click the device's C / F button once to get the correct state sooner

So the device is marked as unreachable ?
But to happen you need to have no temperature / humidity return during 24 h, so there is a problem ?

**Comment by faniskou** [comment]
It is ok . my 4 devices is marked as unreachable when i hot reload the ddf for a few minutes , after that all reporting  temp and humidity as expected .  I just find a way to make them report immediatly be clicking the c/f button .

**Comment by Smanar** [comment]
Ha yes, so it's probably normal, it's battery device, they are lazy, can need time for the first report. 
`"name": "config/reachable"` is probably set a "False" by defaut.

**Comment by faniskou** [comment]
@Smanar Naaaa Sorry,   it is a duplication. They started after us https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6577/commits/13e99c111aa8b2a66919acb8f5daeeeb73746166  but they do it faster, sorry. And they have the battery fixed as well . I just used their Json and is working ok as well . 
![image](https://user-images.githubusercontent.com/13019563/207422917-b29e27b8-7e52-4157-b3ec-f8c509a32beb.png)

**Comment by Smanar** [comment]
lol.
Ha yes right, this one is the same device.

NP, I will close the PR
