### ISSUE TITLE
ADUROSMART ERIA LIGHT BULB

### ISSUE THREAD

**Issue by wifiuk** [dresden-elektronik/deconz-rest-plugin#6426]
# Device

- Product name: ERIA
- Manufacturer: ADUROSMART
- Model identifier: doesn't show in deconz
- Device type : 
  - Light
  

### Other clusters that are not mentioned above

The product says ZIGBEE CERTIFIED PRODUCT, but when it is in pairing mode its not detected at all with deconz/phoscon.

https://www.vesternet.com/products/zigbee-aduro-b22-bulb-warm-white

**Comment by Mimiix** [comment]
Hi,

As this template is basically empty ,I am closing this issue.

Feel free to open a new one with the required screenshots.

Kind regards,

**Comment by wifiuk** [comment]
I moved over to zigbee2mqtt instead
