### ISSUE TITLE
Aqara Curtain Driver E1 

### ISSUE THREAD

**Issue by dxa13** [dresden-elektronik/deconz-rest-plugin#6427]
## Device

- Product name: Aqara Curtain Driver E1
- Manufacturer: LUMI
- Model identifier: lumi.curtain.agl001
- Device type : Please remove all unrelated device types. 
  - Other: Battery Powered curtain driver with light sensor

## Screenshots

![image](https://user-images.githubusercontent.com/34013399/196043994-c38cc421-93c0-4e56-96d7-93c6cc141184.png)
![image](https://user-images.githubusercontent.com/34013399/196044022-a3d782dc-d344-46af-b6dc-d9a63da59c97.png)

### Basic
![image](https://user-images.githubusercontent.com/34013399/196044087-5295f199-5ed3-4a58-b58d-11ae9c13933e.png)

### Identify
![image](https://user-images.githubusercontent.com/34013399/196044122-89b4736b-72e9-4d12-b8c0-1354d4794a2d.png)

### On/Off
![image](https://user-images.githubusercontent.com/34013399/196044153-821a2414-8b69-4273-b773-d95df543427e.png)

### Other clusters that are not mentioned above

Window Covering:
![image](https://user-images.githubusercontent.com/34013399/196044197-9602cac5-6d7d-435a-906c-dd6172f4a3ea.png)
![image](https://user-images.githubusercontent.com/34013399/196044240-f6d4e39d-e448-4eac-baed-abe9effe369a.png)
![image](https://user-images.githubusercontent.com/34013399/196044249-882b3fc2-49c9-4c7c-881a-e18394747396.png)
![image](https://user-images.githubusercontent.com/34013399/196044269-99fa68c6-0485-49c2-baf2-d6236abe8a07.png)

**Comment by dxa13** [comment]
Addendum to the above:  I tried adding the device repeatedly but ultimately does not show up in the Phoscon App.  If it helps, this new device may be a close relative to the Aqara Roller Shade Driver E1 device described on the following issue, except it adds a light sensor:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5330

**Comment by Smanar** [comment]
>If it helps, this new device may be a close relative to the Aqara Roller Shade Driver E1 device described on the following issue, except it adds a light sensor:

Yes, it seem, it's the issue.
The device is an enddevice, but covering are router by defaut.

I think it can solved with mimic a DDF for another covering with the same issue, like the `devices\robb_smarrt\rob_200-029-0_covering.json`

**Comment by Smanar** [comment]
cf https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6469
