### ISSUE TITLE
Aqara Roller Shade Driver E1 - Shows up as Light and does not update cover position.

### ISSUE THREAD

**Issue by oneseventhree** [dresden-elektronik/deconz-rest-plugin#6436]
## Describe the bug

I just purchased the Aqara Roller Shade Driver E1 and I got it working in deconz windows version and Home Assistant but the cover position takes 3-5 minutes to update the cover position.
![image](https://user-images.githubusercontent.com/15043282/196581749-2eb162fa-99a6-4de6-aa09-4fa43444fa1f.png)

The cover moves almost instantly but the cover position in HA stays the same until about 5 minutes then it finally changes.

The device is also showing up as a Light in Phoscon: 

![image](https://user-images.githubusercontent.com/15043282/196581641-0b24f4d7-8cd4-4290-8d76-18c0873759ef.png)

![image](https://user-images.githubusercontent.com/15043282/196581680-34963e09-4bed-4838-90d0-43e885707f96.png)

Is there also a way to show the battery level as well?

All I see is:
![image](https://user-images.githubusercontent.com/15043282/196581900-fd166213-e6b0-45e7-a54a-67704bb434be.png)

## Steps to reproduce the behavior

  1. Set blind in HomeAssistant to 40%
  2. Blind moves into position almost instantly 
  3. cover_positon does not change for 3-5 minutes
  4. Cover position finally updates.

As for the Phoscon it should show up as maybe a Switch instead of a light? It should also show cover position and battery level

## Expected behavior

1. Set blind in HomeAssistant to 40%
  2. Blind moves into position  
  3. cover_positon changes to '40'

## Screenshots

Screenshots above

## Environment

 - Host system: PC
 - Running method: Windows
 - Firmware version: 26660700
 - deCONZ version: 2.19.00 / 19/09/2022
 - Device: ConBee II 
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
N/A

**Comment by Mimiix** [comment]
Hi,

can you show what it shows in the RestAPI when you moved it?

**Comment by oneseventhree** [comment]
> Hi,
> 
> can you show what it shows in the RestAPI when you moved it?

Do you mean this:
```
    "5": {
        "etag": "d5a9e68292a8055a84dcaf324515629c",
        "hascolor": false,
        "lastannounced": "2022-10-20T23:21:27Z",
        "lastseen": "2022-10-21T10:04Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.curtain.acn002",
        "name": "Living Room Blinds",
        "state": {
            "alert": "none",
            "bri": 38,
            "lift": 15,
            "on": true,
            "open": true,
            "reachable": true,
            "speed": 2
        },
        "swversion": "0x00000E1B",
        "type": "Window covering device",
        "uniqueid": "54:ef:44:10:00:44:ee:85-01"
    }
}
                    
                ```

**Comment by Mimiix** [comment]
Did you try to re-pair already? In the original topic i dont see anyone mentioning this.

**Comment by oneseventhree** [comment]
> Did you try to re-pair already? In the original topic i dont see anyone mentioning this.

I've repaired it 3 times

**Comment by Mimiix** [comment]
I'm pinging you on discord :)

**Comment by Mimiix** [comment]
Got it working, in the end, the Firmware update on the Conbee made it work. 

For future reference:

- Reset device.
- Remove from Phoscon.
- Stop deCONZ
- Update Conbee firmware to latest version
- Start deCONZ
- Pair Blind again.
- ???
- Profit!
