### ISSUE TITLE
Nous Termperature and Humidity Sensor E5

### ISSUE THREAD

**Issue by cornim** [dresden-elektronik/deconz-rest-plugin#6438]
## Device

- Product name: Nous Termperature and Humidity Sensor E5
- Manufacturer: _TZ3000_lbtpiody
- Model identifier: TS0201
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots
![image](https://user-images.githubusercontent.com/4417017/196680647-7562a7d0-27f7-4228-9061-7d51b4b3fc50.png)
![image](https://user-images.githubusercontent.com/4417017/196680705-448c3a7b-95ec-45fe-9af0-43e0001d040a.png)
![image](https://user-images.githubusercontent.com/4417017/196680556-bcd79a8b-d1f2-4727-9988-ce71554634c9.png)
![image](https://user-images.githubusercontent.com/4417017/196680928-3b9c76f0-f371-4ab2-8b2c-8b107059fade.png)
![image](https://user-images.githubusercontent.com/4417017/196681079-df77a750-77b5-4eb3-b10b-b82b9a142636.png)
![image](https://user-images.githubusercontent.com/4417017/196681216-c0ae6d2e-063d-43b4-bbc2-b5ddd6ad6df0.png)

**Comment by cornim** [comment]
I wasn't sure what to do with all the headings at the bottom of the ticket, as it said in the ticket not to delete any headings but lots of them don't really relate to my device.
Also the forum seems to be offline so I couldn't read the relevant post there.
If I need to fix something, please let me know.

**Comment by Smanar** [comment]
No if all is working for you I will make the PR.
So all is fine ?

**Comment by cornim** [comment]
The connection seems to work fine.
Temp readings are fine as well but the humidity is way to high. 74% where all other sensors show 55-60%.
Might be that the sensor is broken. I bought a second one and will try it out. Should take only a couple of minutes.

**Comment by Smanar** [comment]
It s from the device, I m just reading value.
There is a config/offset to correct the value but 74 % to 55 % it s realy hugde, I don't think it will be reliable using an offset.

**Comment by cornim** [comment]
Yes, so in summary, the deconz integration works fine but the humidity sensor seems broken.
I also tested it in a really humid environment and there it shows 100%. So the max value is not somewhere else but the measured values are just wrong.

**Comment by cornim** [comment]
yeah, offset won't work because the error isn't linear
58% -> 74%
but 100% -> 100%
I'll just send those back.

But yes, go ahead and make the PR. Reading out the values via deConz works just fine.
And thanks again for the quick response.

**Comment by Smanar** [comment]
>I put it in a large pot with a small pot of boiling hot water next to it. :)

Lol pro tester.
