### ISSUE TITLE
Missing option in Switch Editor

### ISSUE THREAD

**Issue by arjannv** [dresden-elektronik/deconz-rest-plugin#6439]
## Describe the bug

Cannot set the long-press behavior to "Change Brightness" without setting short-press toggle as well.

## Steps to reproduce the behavior

When setting the button behavior of a switch in the Switch Editor, it is not possible to select only dimming up/down _without_ setting short-press toggle as well. 

## Expected behavior

I would like to set the behavior of a button in the Switch Editor to dimming up/down without setting toggle on/off as well.
This will enable me to combine the long-press dimming of Deconz/Phoscon and a toggle automation in Domoticz where I can set different levels of brightness based on the time of day. And thus, not blinding my baby while changing in the middle of the night. :)

## Screenshots

![button](https://user-images.githubusercontent.com/43266823/196709535-f279fe6d-537e-48b5-9aab-11f6236b10ad.jpg)

## Environment

 - Host system: VM
 - Running method: Ubuntu 20.04 LTS
 - Firmware version: 26720700
 - deCONZ version: 2.19.0-beta
 - Device: ConBee II
 - Do you use an USB extension cable: Yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
Hi,

Phoscon bugs / feature requests are collected on the forums. Https://forum.phoscon.de

As this doesn't belong here I'm closing the issue.

Kind regards,
Dennis

**Comment by arjannv** [comment]
Hi @Mimiix, 

Thanks for the reply. 
And you are right, this should be done on the forum. 

But, [that's what I did](https://forum.phoscon.de/t/feature-request-switch-editor-option-for-long-press-only/2057/2), about 4 months ago, but there was no response, so I tried it here on Github. 

Please let me know if there's anything I can do to help this process. 

With kind regards, 
Arjan

**Comment by Mimiix** [comment]
Let me bump that post and see if i can get some attention by DE staff. As phoscon is closed source , nobody can really develop for it.
