### ISSUE TITLE
Can't find devices on Ubuntu

### ISSUE THREAD

**Issue by isabellaalstrom** [dresden-elektronik/deconz-rest-plugin#644]
I downloaded deconz and it finds my Conbee but the Conbee doesn't find anything else. Downloaded deconz on windows too and the problem is not there, I can add everything. Is there some step I've missed on Ubuntu to get it running alright or is this a bug?

**Comment by manup** [comment]
If the same ConBee already works on Windows it should show the there connected devices also on Ubuntu. Is the blue node shown on Ubuntu too &dash; meaning deCONZ is connected to ConBee?

>Is there some step I've missed on Ubuntu to get it running alright or is this a bug?

It might be a permission problem. The local user needs to be part of the `dialout` group so deCONZ can connect to the ConBee USB device. This can be fixed by:

`$ sudo gpasswd -a <username> dialout`

Might require a reboot afterwards, to work.

**Comment by manup** [comment]
In the Phoscon App under *Menu > Settings > Gateway* you can see if it is connected properly. If it is connetced the firmware version should be visible like this:

![image](https://user-images.githubusercontent.com/383386/41500822-1b265d4e-7199-11e8-822e-77918beee5d3.png)

**Comment by isabellaalstrom** [comment]
Yes, that shows up just like that. I also checked and the user already is in dialout group!

**Comment by manup** [comment]
Good so the device connection is working. If the on windows connected devices are sensors or switches they won't show up on Ubuntu. You can create a backup file on Windows with connected Conbee (Phoscon App > Settings) and restore that file on Ubuntu, it should bring back the devices.

**Comment by isabellaalstrom** [comment]
I'm actually not seeing the firmware version I just realized. But that seems to be a known problem on the docker version. Will try to add some other things and do the backup thing tomorrow!

**Comment by isabellaalstrom** [comment]
Okey, so I paired a few things on the windows pc, did the backup, changed to the nuc and restored backup there. I paired one xiaomi button/switch, one xiaomi motion sensor, one trådfri dimmer (the ones without buttons) and one trådfri bulb. In the api I can now see all entities, except the light. But only the xiaomi switch registers state changes, the others keep being what they were when on the windows pc. I cannot pair new things either.

**Comment by isabellaalstrom** [comment]
I would be happy to help debug with logs etc if I get some guidance, since more ppl seem to be having problems.

**Comment by manup** [comment]
> I'm actually not seeing the firmware version I just realized. But that seems to be a known problem on the docker version. Will try to add some other things and do the backup thing tomorrow!

Hmm, I have no experience with the docker image but the version should also be visible there.

Maybe @marthoc can help out here?

https://hub.docker.com/r/marthoc/deconz/
https://github.com/marthoc/docker-deconz

**Comment by Nicxe** [comment]
I got the same issue on my rPi. I run deconz and it identifi the gateway and gives it a chanel and ID. But I can´t add any device.

**Comment by isabellaalstrom** [comment]
@marthoc Yes, I hadn't gotten around to writing here yet, thank you.
