### ISSUE TITLE
No update available

### ISSUE THREAD

**Issue by SergiSuarez** [dresden-elektronik/deconz-rest-plugin#646]
Dears,

I'm having issues with Ikea bulbs and I think they should be sorted in current version but my system is unable to find new software and states it's up to date. It's in 2.05.23 Firmware 261F0500 with a RaspBee hat.

It has direct internet connection.

Any ideas?

Thanks

**Comment by manup** [comment]
The newer versions are not yet in the public update channel. For manual installation please follow steps 1&ndash;3 from:
https://github.com/dresden-elektronik/deconz-rest-plugin#installation
