### ISSUE TITLE
Unexpected light effect type 0

### ISSUE THREAD

**Issue by hanskroner** [dresden-elektronik/deconz-rest-plugin#6460]
## Describe the bug

```
Logger: pydeconz.models.light.light
Source: components/deconz/light.py:160 
First occurred: October 19, 2022, 21:15:50 (20 occurrences) 
Last logged: October 19, 2022, 21:15:50

Unexpected light effect type 0
```
```
'63': {"colorcapabilities":0,
       "ctmax":65279,
       "ctmin":0,
       "etag":"00586fd4612bec13237a62127a64b816",
       "hascolor":true,
       "lastannounced":"2022-10-18T04:44:35Z",
       "lastseen":"2022-10-24T06:48Z",
       "manufacturername":"Philips",
       "modelid":"LCA006",
       "name":"Hue color bulb 24",
       "state":{"alert":"none",
                "bri":140,
                "colormode":"xy",
                "ct":343,
                "effect":"none",
                "hue":8514,
                "on":true,
                "reachable":true,
                "sat":120,
                "xy":[0.4445,0.4067]},
       "swversion":"1.93.11",
       "type":"Extended color light",
       "uniqueid":"00:17:88:01:0b:a9:bc:7d-0b"}
```

Similar to #6415. 

It seems that #6320 updated item definitions and now `int` values need to be mapped to `strings`. @ebaauw has fixed the related issue in #6457 by updating _'generic/items/state_colormode_item.json'_ to use the incoming `int` value as an index into an array of `string` values - which works just fine. The same could be done for _'generic/items/state_effect_item.json'_, however @ebaauw is introducing a lot of new functionality in #6316 which will add, amongst many other things, additional effects (or Dynamic Scenes, as they're apparently being called) like 'candle' or 'fireplace' - at least for Hue products capable of supporting them. It's probably better that he has a look at this before I venture to propose a "fix".

## Environment

 - Host system: Mac mini
 - Running method: deCONZ Community Docker Container on Debian host
 - Firmware version: 26660700
 - deCONZ version: 2.19.1
 - Device: ConBee II
 - Do you use an USB extension cable: yes -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? no If so: Which?

**Comment by ebaauw** [comment]
Sorry, I don’t see any bug in deCONZ, regarding this issue.  The resource correctly shows`"effect": "none"`.  The referred PR doesn’t seem to have touched `state/effect`.  And `generic/items/state_effect_item.json` uses string, and doesn’t even parse, let alone read, any attribute.  I am updating that in my PR, though.

Note that the resource incorrectly lists `manufacturername` as `"Philips"`, suggesting the _Basic_ cluster hasn’t been read.  Also, the _Color Cluster_ might not have been read, given the wrong values of `colorcapabilities`, `ctmax`, and `ctmin`.  You might want to force-read the cluster attributes in the GUI or re-pair the light.

**Comment by Kane610** [comment]
> Sorry, I don’t see any bug in deCONZ, regarding this issue. The resource correctly shows`"effect": "none"`. The referred PR doesn’t seem to have touched `state/effect`. And `generic/items/state_effect_item.json` uses string, and doesn’t even parse, let alone read, any attribute. I am updating that in my PR, though.
> 
> Note that the resource incorrectly lists `manufacturername` as `"Philips"`, suggesting the _Basic_ cluster hasn’t been read. Also, the _Color Cluster_ might not have been read, given the wrong values of `colorcapabilities`, `ctmax`, and `ctmin`. You might want to force-read the cluster attributes in the GUI or re-pair the light.

It is probably the wrong device in the in the description, a few people have said that they get `"effect": "0"`

**Comment by ebaauw** [comment]
> I also went around and checked most of my bulbs and indeed most of their manufacturername updated to `"Signify Netherlands B.V."` when I forced a read of the Basic cluster manually. Some of them, including my Fugato Spots, retained `"Philips"` though. Should I be forcing these kinds of updates manually, say after firmware upgrades? It doesn't seem to be done by deCONZ.

deCONZ still sets the `manufacturername` for (new?) `lights` resources from the _Manufacturer Code_ in the _Device Descriptor_, before the _Basic_ cluster has been read.  This is updated / corrected on reading the cluster.  Note that some Hue lights still report `"Philips"` in the _Basic_ cluster, even some of the Zigbee 3 lights with 1.93.11, like my Hue Ensis.  I think the Hue bridge reports `manufacturername` as `"Signify Netherlands B.V."` for these, overwriting the Zigbee value.

> After manually forcing a read of all the bulb's clusters, the API now correctly reports `"effect"` as `"none"`. Additionally, `ctmax` and `ctmin` have been updated as well. For posterity, here's the same bulb after forcing a read of all the clusters:

I suppose you haven't yet defined a DDF for this light?  I think this is a bug in the C++ code, where it only initialises `state/alert` when additional data is read.  Rather than fixing that, I'd rather focus on providing DDFs for "all" lights, preventing these kind of issues from happening altogether.  Once read, the value should be persisted in the database and you shouldn't see the `0` for that light again.

**Comment by hanskroner** [comment]
> I suppose you haven't yet defined a DDF for this light? I think this is a bug in the C++ code, where it only initialises `state/alert` when additional data is read. Rather than fixing that, I'd rather focus on providing DDFs for "all" lights, preventing these kind of issues from happening altogether. Once read, the value should be persisted in the database and you shouldn't see the `0` for that light again.

Thanks again, Erik. I haven't defined DDFs for the lights, so I believe they're working off of the C++ code. I'll try to keep an eye on how they behave when using the DDFs you've made.
