### ISSUE TITLE
Aqara Single Switch module not working since update to 2.19.01

### ISSUE THREAD

**Issue by evan-shaw** [dresden-elektronik/deconz-rest-plugin#6464]
## Describe the bug

After updating from 2.18.2 to 2.19.1 my Aqara T1 Switch doesn't work. https://www.aqara.com/en/single_switch_T1_no-neutral.html
In 2.18.2, and before, the switch was recognised as a light, I think this is correct.
But since the upgrade to 2.19.1, the switch appears as both a light and a switch, i.e. 2 entities are created. If you delete either one, the other is also removed. One of these entities is being exposed to home assistant, but it doesn't work. When attempting to switch it on/off in home assistant, I get the error message: -

 _[545860309824] 3 /lights/3 resource, /lights/3, not available_

## Steps to reproduce the behavior

  1. Go to 'Phoscon HTTP GUI'
  2. Click on 'Lights'
  3. Scroll down to 'MasterBedroom Light | LUMI | lumi.switch.l0agl1'
  4. Click on 'Switches'
  5. Scroll down to 'lumi.switch.l0agl1 | LUMI | lumi.switch.l0agl1'

## Expected behavior

 I would expect to only see this exposed as a light, I think with two entities available, there is a clash somewhere.

## Screenshots

  ![Selection_999(140)](https://user-images.githubusercontent.com/34520506/197755146-7604e990-3dd6-47a3-a688-317aefacd00a.png)

![Selection_999(139)](https://user-images.githubusercontent.com/34520506/197755126-c7e1d477-512e-4ede-81fe-494f4439628f.png)

## Environment

 - Host system: Raspberry Pi 4 (8GB)
 - Running method: Raspbian
 - Firmware version: 26720700
 - deCONZ version: 2.19.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? If so: Which? No

## deCONZ Logs

API Info: -
`
"8": {
        "etag": "a16e0dcf3996a01210406c742d36c5df",
        "hascolor": false,
        "lastannounced": null,
        "lastseen": "2022-10-25T10:57Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.switch.l0agl1",
        "name": "MasterBedroom Light",
        "state": {
            "alert": "none",
            "on": false,
            "reachable": true
        },
        "swversion": "0.0.0_0022",
        "type": "On/Off light",
        "uniqueid": "54:ef:44:10:00:07:62:80-01"
    },

"ep": 41,
        "etag": "9dcdf4cc905be1ee02ff03f24af4ebdb",
        "lastannounced": null,
        "lastseen": "2022-10-25T10:57Z",
        "manufacturername": "LUMI",
        "mode": 1,
        "modelid": "lumi.switch.l0agl1",
        "name": "lumi.switch.l0agl1",
        "state": {
            "buttonevent": null,
            "lastupdated": "none"
        },
        "swversion": "0.0.0_0022",
        "type": "ZHASwitch",
        "uniqueid": "54:ef:44:10:00:07:62:80-29-0012"
    }
`

**Comment by Smanar** [comment]
Unfortunately a DDf for this device was valided just 3 days ago https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6363

I don't think you have it on your deconz version so can you instal it manualy to test it ?

**Comment by evan-shaw** [comment]
Hi Smanar, just checked out that link   "Add DDF for Aqara T1 single rocker switch (no neutral wire) SSM-U02"
That device is different, mine doesn't have a rocker switch, it's more a sort of relay that is placed in the wall behind an existing dumb rocker switch.

**Comment by Mimiix** [comment]
It's in. but as the or said it's untested.

**Comment by evan-shaw** [comment]
Ah OK, so seems not to be working at the moment then if #6363 is a similar issue to mine. Thanks

**Comment by Mimiix** [comment]
@SwoopX you might be interested in testing with this user ?

**Comment by Smanar** [comment]
@evan-shaw you have tested the swoopX DDF ?

**Comment by evan-shaw** [comment]
Er no, I haven't seen it?

**Comment by Smanar** [comment]
Here you have a DDF for "lumi.switch.l0agl1" https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6363

**Comment by evan-shaw** [comment]
I would need  some instructions....

**Comment by Smanar** [comment]
You have the theory here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet.

You have 2 folder used for DDF, one is used by deconz and will be reseted at every deconz uptade, the other is for "user"
You just need to create a text file inside, with this contain, name the file that_you_want.json and restart deconz.

If you have HA, have fun https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by evan-shaw** [comment]
@Smanar & @SwoopX  Hi Both, I tested the json from #6363 as suggested, it's currently in my deconz user directory. It worked. The "light" entity now works correctly in Home Assistant. Not sure if it's a problem, but the "switch" entity for the same device is still present in the phoscon web ui?

**Comment by Smanar** [comment]
I think it's normal, I m reading the DDF and there is still the ZHASwitch probably to be used with decoupled mode.

**Comment by Smanar** [comment]
From the comment the corrective is in the version 2.19.1 https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.19.1

**Comment by samhed** [comment]
Do you have any idea when we can expect 2.19.1 to hit the repos?

This page only lists 2.19.0:
https://www.phoscon.de/en/changelog

And in raspbian repos I can only find 2.19.03.

**Comment by Smanar** [comment]
http://deconz.dresden-elektronik.de/raspbian/beta/

I think there was a typo the 2.19.1 is the 2.19.01

**Comment by samhed** [comment]
Hm, in that case, something is still amiss. I have deconz version `2.19.03-raspbian-buster-beta` and my Aqara T1 switches are still missing from phoscon. They disappear after deconz upgrade, and if I downgrade to 2.18.02 they reappear.

**Comment by Smanar** [comment]
It's a "lumi.switch.l0agl1" ?
I can see the DDF in the folder `devices\xiaomi\xiaomi_ssm-u02_t1_switch.json`

The manufacture name is "LUMI" ?

**Comment by samhed** [comment]
Yes, it is a `lumi.switch.l0agl1` and with version 2.19.03 I can also see the DDF here:
`/usr/share/deCONZ/devices/xiaomi\xiaomi_ssm-u02_t1_switch.json`

After downgrading to 2.18.02 I can see it in Phoscon:

![image](https://user-images.githubusercontent.com/4117162/209108517-133e9245-0601-42a7-bafc-8f59fe8b75e8.png)

As you can see, it lists "Vendor" as LUMI.

**Comment by Smanar** [comment]
I don't see problem on, the DDF, deconz check onlu this to use the DDF

```
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.switch.l0agl1",
```

$MF_LUMI = LUMI

And if you try to re-include the device ?

**Comment by samhed** [comment]
Do you mean removing it from the ZigBee network and then re-pairing it?

In that case, I'd remove it when on version 2.18.02, then upgrade to 2.19.03, and lastly attempt to re-pair it.

**Comment by Smanar** [comment]
Yes, sorry if it's not a problem for you, because I don't see see what can be wrong on the DDF.

The manufacture name is good  "LUMI"
The model id is good "lumi.switch.l0agl1"
No special check in the DDF
The status is "Gold"
And no typo in the DDF

I can understand if the device is not working, but no it can't be included.

**Comment by hermsi94** [comment]
The switch without neutral is actually just like the one with only without voltage, current and power measurement, if that helps. I have adjusted my DFF here and it is now recognized as a light and also displayed in Phoscon. Also it can now be controlled with NodeRed. Here is the DFF:
`{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.switch.l0agl1",
  "product": "Aqara Single Switch Module T1 without neutral",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}`

**Comment by hermsi94** [comment]
The switch without neutral is actually just like the one with neutral only without voltage, current and power measurement. It is also an end device and not a router like the one with neutral, if that makes a difference ':D. 

I have adjusted my DFF here and it is now recognized as a light and also displayed in Phoscon. Also it can now be controlled with NodeRed. Here is the DFF if that helps:
```{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.switch.l0agl1",
  "product": "Aqara Single Switch Module T1 without neutral",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/54680250/210121671-bb9fb02a-367b-4965-9c1f-9b99254fd9ab.png)

**Comment by hermsi94** [comment]
With the rest of the things I know unfortunately not so from :sweat_smile: . It must be because of the things that are different in the two versions like Type Switch or Clickmode or something.

It is actually like the working one with neutral only without all these measurement functions or not? :
[https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/xiaomi/xiaomi_lumi.switch.n0agl1_switch.json](url)

**Comment by Smanar** [comment]
IDK, I don't know this device.

**Comment by samhed** [comment]
@Smanar it's working now! I downgraded to the older version, removed my switches, then upgraded to the most recent version of Deconz. I then successfully could re-add them to the Zigbee network. Things work great now.

One difference that I noticed is that these devices have now started appearing both under "lights" and under "switches" in phoscon.

**Comment by samhed** [comment]
@Smanar it's working now! I downgraded to the older version, removed my switches, then upgraded to the most recent version of Deconz. I then successfully could re-add them to the Zigbee network. Things work great now.

One difference that I noticed is that these devices have now started appearing both under "lights" and under "switches" in phoscon.

Anyway, thanks for the help!

**Comment by Smanar** [comment]
>One difference that I noticed is that these devices have now started appearing both under "lights" and under "switches" in phoscon

Yep, it's from the Swoops's DDF, probably because you can "decouple' them.
