### ISSUE TITLE
Universal Remote Control, UFO-R11, IR remote

### ISSUE THREAD

**Issue by DieuwerH** [dresden-elektronik/deconz-rest-plugin#6470]
## Device

- Product name: Universal Remote Control
- Manufacturer: _TZ3290_j37rooaxrcdcqosn
- Model identifier: TS1201
- Device type : Please remove all unrelated device types. 
  - Remote
  - Sensor

It is an IR remote that can learn from an existing remote and later transmit those signals.

Zigbee2mqtt page on this device: https://www.zigbee2mqtt.io/devices/UFO-R11.html

### Basic

![image](https://user-images.githubusercontent.com/6793140/197995276-e5682b67-4889-4968-bf79-5a2b92bdd2f0.png)

![image](https://user-images.githubusercontent.com/6793140/197995603-cd5f94f2-d4e8-4060-8d74-59646854ced5.png)

### Identify
![image](https://user-images.githubusercontent.com/6793140/197995969-c390cef2-8ed2-485c-b5e7-333f6266f6c4.png)

### Groups
![image](https://user-images.githubusercontent.com/6793140/197996108-94479279-f0d4-4d4e-ae09-1db1207db0df.png)

### Scenes
![image](https://user-images.githubusercontent.com/6793140/197996170-d9b4a37d-53e7-414f-94fe-328f3cf0f6e1.png)

### On/Off
![image](https://user-images.githubusercontent.com/6793140/197996384-13341d32-c40c-4541-9e8c-af49a141575f.png)

![image](https://user-images.githubusercontent.com/6793140/197996347-fa98118f-4424-4047-98df-4ad16e94849e.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/6793140/197996570-e220ffe1-5eab-4c42-9469-17bf926338d7.png)

**Comment by Xyaren** [comment]
I bought a similar Device Called "Zigbee IR Remote Control"
Model **ZS-06** / **TS1201** / `_TZ3290_7v1k4vufotpowp9z`

Bought at https://www.aliexpress.com/item/1005003878194474.html
Zigbee2mqtt device link: https://www.zigbee2mqtt.io/devices/ZS06.html

### Device
![image](https://user-images.githubusercontent.com/5864045/216371073-ef9e9f83-ae12-47cd-b1f8-53aea80b329b.png)
### Basic
![image](https://user-images.githubusercontent.com/5864045/216371614-850a6dfb-e287-42b3-8834-24bc9d5b7174.png)
### On/OFF
![image](https://user-images.githubusercontent.com/5864045/216371857-09fc1761-ec16-4fac-aaf3-738207d5b37e.png)
### 
Node Info
![image](https://user-images.githubusercontent.com/5864045/216371980-0d2ed839-4450-47c6-a3d0-cb59b50626a1.png)

I tested the device using zigbee2mqtt and it works.
But I prefer to use deconz :)

I don't see any other IR Blaster devices in the supported devices, so is this a first ?
How is the procedure? 
I would like to help, bringing IR Blasters to Deconz/Homeassistant.

**Comment by Xyaren** [comment]
@Smanar you've been my savior in this project so far :D
I would like to help but I have no starting point.

**Comment by Smanar** [comment]
Hu ... good question.
I don't think it will be possible yet, need a custom request to send code, and DDF can only use predefined one for the moment, (need a complete zigbee request, not just a n attribute read/write).
Have already the problem for that for covering request, so for completely new request ....

**Comment by Xyaren** [comment]
The Zug we request seems proprietary.
Would this be accepted as code with an additional DDF?

**Comment by Smanar** [comment]
>The Zigbee equest seems very proprietary.

I haven't say they don't respect zigbee rules, the problem is more on deconz side.

>Would this be accepted as code with an additional DDF?

"One day" the DDF core will be able to use custom request, but honnestly it can take so long time, and even you make all the c++ code yourself, no sure it will be merged as the c++ code need to move a lot for future version.
