### ISSUE TITLE
Samotech SM313Z Temperature & Humidity Sensor

### ISSUE THREAD

**Issue by TheStork239** [dresden-elektronik/deconz-rest-plugin#6471]
## Device

- Product name: Samotech SM313Z temperature & humidity sensor
- Manufacturer: _TZ3000_5nrcorgu
- Model identifier: TS0201
- Device type :
  - Sensor

### Basic
![image](https://user-images.githubusercontent.com/80922293/198131718-d489c981-75b0-42e5-aee3-d27af2d13daf.png)

### Identify
![image](https://user-images.githubusercontent.com/80922293/198131980-17019508-114e-4ac1-81b6-3daaf149a465.png)

### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/80922293/198132342-4ceff310-bf4f-49b2-9d63-8ad7b1ac223f.png)
![image](https://user-images.githubusercontent.com/80922293/198132515-4c4c3c36-1ca9-46e3-acbb-64a40a1ee6c5.png)
![image](https://user-images.githubusercontent.com/80922293/198132582-3305cf0e-4e39-4d2b-9dc3-e51acb2eb3c5.png)
![image](https://user-images.githubusercontent.com/80922293/198132849-944a2268-0601-4e15-9313-febed7984df3.png)

**Comment by Smanar** [comment]
Hello can you try adding your model in this DDF to test it ? https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_yd2e749y_temp_hum_sensor.json

**Comment by TheStork239** [comment]
> Hello can you try adding your model in this DDF to test it ? https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_yd2e749y_temp_hum_sensor.json

Thanks.  Not sure how I do that / what exactly you want me to do.  I run deConz via HomeAssistant add-on, and I don't seem to find a way to get to edit the relevant DDF file to try the edit.

And do you mean that in that file (if there is a way for me to get to it) I should simply edit lines 3 and 4 of the file to include a third item in the list, i.e.:  
"manufacturername": ["_TZ3000_yd2e749y", "_TZ3000_fllyghyj", "_TZ3000_5nrcorgu],
  "modelid": ["TS0201", "TS0201", "TS0201"],

But how do I get to the DDF file on a HomeAssistant install to do that?

**Comment by Smanar** [comment]
Yep, it's exaclty that.
But not easy on HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by TheStork239** [comment]
Thanks.  I managed to make the edits to the required json file, but when I join the the device via deConz, it does not appear to be picking up the relevant DDF file for that device, and it is paired with no DDF file if I right click into the "edit DDF" after the pairing completes (picture attached).  And if I restart the deConz add-on, then all the edits to the suggested json doc are lost as the docker starts clean, so can't really test the usual "please see if a reboot helps"...
![image](https://user-images.githubusercontent.com/80922293/198727476-dceadca0-c0ab-47c0-afa6-2e64f4a839bb.png)

**Comment by Smanar** [comment]
As it's just an edit, you can try that :
- select the node
- select "edit DDF"
- select file/load
- select the "devices/tuya/_TZ3000_yd2e749y_temp_hum_sensor.json"
- edit the string to add your device, need to edit manufacture and model id.
- try to save the file (idk what will happen here)
- make "file / hot relaod"


I think it will be enought to test the device, but the change will be not persisitent.

**Comment by TheStork239** [comment]
Thanks.  That seems to work.  After the hot reload the device picks up a new name automatically e.g. "Temperature 27", and I can see the device also in the Phoscon app (see pic below).  
I haven't seen the device or its entities pop up in HomeAssistant yet, but that may require a restart of deConz or reboot of HA, which will make it lose the changes given they are not yet persistent.

![image](https://user-images.githubusercontent.com/80922293/198824668-a61ddfd9-011d-4bb0-a5e0-45d2a14d3dba.png)

![image](https://user-images.githubusercontent.com/80922293/198824599-d38c0ff1-a879-4c73-a83d-936a06eb5e2b.png)

**Comment by Smanar** [comment]
>but that may require a restart of deConz or reboot of HA, which will make it lose the changes given they are not yet persistent.

Yeah, but if I m right there is a way in the HA plugin to resynchronise the plugin with deconz.

Just tell me if in 24h the battery is working or not ? And I will make the PR to add the device.

**Comment by TheStork239** [comment]
Great - I managed to get the entities to appear in HA using the deConz device refresh service.
The battery reporting already started to work, showing 100% for one device, and 98% for another I also paired.
So it all seems to work using that DDF edit, and probably ready for the PR to add the device.
Thank you very much for your help!

![image](https://user-images.githubusercontent.com/80922293/198830874-175a6333-2784-4cd3-a512-75cc6cf16122.png)

**Comment by Smanar** [comment]
Have added the device on this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6244

**Comment by audiocrush** [comment]
Hi,

I'd also like to add the ID _TZ3000_ena8vgqb for this json file 
I have a Luminea Home Control Temperature and Humidity sensor that seems to be just a oem version of the same.
It worked fine for me when I added this ID to the json file you mentioned.

**Comment by Smanar** [comment]
Thx, just added to the same PR

**Comment by non092** [comment]
Hi,
Can you add _TZ3000_xr3htd96 as well ?
Seems to be a clone of the same device, I've edited the DDF yesterday and everything is reporting properly 👍 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/729962/203310129-d6fbf88d-394f-466d-86c8-fb402deb6cb6.png">

**Comment by Smanar** [comment]
Thx, just added (on same PR too)

**Comment by TheStork239** [comment]
I guess this could be closed as soon as the PR mentioned above gets merged.  @Smanar do you know what the timelines for that merge might be?

**Comment by Smanar** [comment]
Don't worry, the issu will be closed immediatly when the PR will be valided.

And no I don't have timeline, and somes devs are on holidays atm. I hope for a massive PR merge before Christmas

**Comment by manuel-mauky** [comment]
Hi, I have a _TZ3000_ena8vgqb (Luminea Temperature sensor) and tested with the DDF file from the PR.
It seems to work. In DeConz I can see the newest measurement values (in Cluster Info) and they are updated every few minutes as expected.
However, in the Phoscon app, Home-Assistant and in the Rest-API these values aren't updated. There I can only see the value that was first read when I started DeConz but no following updates.

This whole zigbee topic is new for me so I'm not sure if this is related to the DDF file or is it a separate/unrelated issue?

**Comment by Smanar** [comment]
I don't found special information about this device.
It don't have the tuya cluster ?
Can try to re include the device, without deleting it, the inclusion procedure can have failed and the bind/report was skipped.

**Comment by manuel-mauky** [comment]
> It don't have the tuya cluster ?
I'm not sure what this means. Where can I see this?

Here are the screenshots, I hope this helps.

## Basic
![basic](https://user-images.githubusercontent.com/328387/209881232-2083b261-15f5-4c6c-936e-1362bb926c6b.png)

## Node Info
![node_info](https://user-images.githubusercontent.com/328387/209881325-94e2aafe-488f-46ca-927a-6fe77f8b947d.png)

## Identity
![identity](https://user-images.githubusercontent.com/328387/209881527-e9cb001c-1a21-4adf-97ca-7c637cb77424.png)

## Power
![power](https://user-images.githubusercontent.com/328387/209881573-d646de30-0716-4ca2-8a16-281e0b137130.png)

## Temperature
![temperature](https://user-images.githubusercontent.com/328387/209881581-fa5bf29a-6703-4c70-b401-15dae42005de.png)

## Humidity
![humidity](https://user-images.githubusercontent.com/328387/209881589-e09e70c4-195e-40aa-94f4-f93a588cbc53.png)

**Comment by Smanar** [comment]
So your device look standard.

Perhaps it need the tuya unlock sequence (and this is not possible yet using deconz), but I can't find information about it on google.

And binds/report are fine in the DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/b2761cd529982fa13eaf4b56059221220a7f3237/devices/tuya/_TZ3000_yd2e749y_temp_hum_sensor.json (and work for other devices)

Have you tried to re-include the device without deleting it ?

@audiocrush you don't have problem on your side ?

**Comment by manuel-mauky** [comment]
What do you mean with "re-include the device without deleting it"?
What should I do?

**Comment by Smanar** [comment]
Just re pair it, in phoscon "add new sensor"

**Comment by manuel-mauky** [comment]
Ok. I've tried this and it doesn't work either.
