### ISSUE TITLE
Tuya ZigBee door and window magentic sensor _TZ3000

### ISSUE THREAD

**Issue by mikeg-de** [dresden-elektronik/deconz-rest-plugin#6473]
## Device

- Product name: Tuya ZigBee door and window magentic sensor
- Manufacturer: _TZ3000_osu834un
- Model identifier: TS0203
- Device type:
  - Sensor

### Basic
![Bildschirmfoto 2022-10-27 um 09 11 10](https://user-images.githubusercontent.com/604842/198215484-604ba19b-7a4d-413d-9686-037e21148623.jpg)

### Identify
![Bildschirmfoto 2022-10-27 um 09 11 31](https://user-images.githubusercontent.com/604842/198215543-e9b5b4c7-1dbe-42c5-b7d3-891edf2cca0d.jpg)

### Other clusters that are not mentioned above
Power Configuration
![Bildschirmfoto 2022-10-27 um 09 12 59](https://user-images.githubusercontent.com/604842/198215816-da9de922-200c-4e15-813c-99a8550e64d5.jpg)

IAS Zone
![Bildschirmfoto 2022-10-27 um 09 13 51](https://user-images.githubusercontent.com/604842/198215963-a313785e-5075-4503-9e92-598d334f9022.jpg)

Node Info
![Bildschirmfoto 2022-10-27 um 14 20 23](https://user-images.githubusercontent.com/604842/198282602-1b5614f9-6ae1-4c8c-9572-322c6c6cbb11.jpg)

**Comment by Smanar** [comment]
Hello can you try to add your model this DDF to test it ? https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_n2egfsli_door_sensor.json

**Comment by mikeg-de** [comment]
When trying to load a DDF via VNC I am getting an error stating the file could not get opened.

![Bildschirmfoto 2022-10-27 um 17 04 23](https://user-images.githubusercontent.com/604842/198326665-3976df4f-30f3-4cd6-9370-ed18534e2d4f.jpg)

For testing and learning purposes I saved the json generated by deCONZ and by inspecitng in via vi I noticed the line breaks are "quite interesting"
![Bildschirmfoto 2022-10-27 um 17 05 43](https://user-images.githubusercontent.com/604842/198326991-f5690a1a-0ee4-4a9a-bcda-a741640b366e.jpg)

Here is the file I created myself:
![Bildschirmfoto 2022-10-27 um 17 06 04](https://user-images.githubusercontent.com/604842/198327090-d6b90e89-13b9-4f3d-b071-03b149508278.jpg)

Any ideas?

**Comment by Smanar** [comment]
>Here is the file I created myself:

But this one is the orignal one ? I don't see your device inside

```
  "manufacturername": ["_TZ3000_n2egfsli", "_TZ3000_oxslv1c9", "_TZ3000_7tbsruql", "_TZ3000_7d8yme6f", "_TZ3000_osu834un"],
  "modelid": ["TS0203", "TS0203", "TS0203", "TS0203", "TS0203"],
```

**Comment by mikeg-de** [comment]
Thanks for the confirmation of the path. Just one note, though. Per the [DDF Cheat Sheet](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet) the paths can't be found:

![Bildschirmfoto 2022-10-27 um 18 33 12](https://user-images.githubusercontent.com/604842/198348628-64f7383a-65cf-4e46-91e8-379ede6d8711.jpg)

The file you linked doesn't contain the manufacturer: https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_n2egfsli_door_sensor.json

I added the recently shared code manually and will re-add the node soon. (taking care of my kids now). Will let you know once done.

**Comment by Smanar** [comment]
>the paths can't be found:

What if your OS ?

```
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ cd /usr/share/
pi@raspberrypi:/usr/share $ dir
accountsservice          glib-2.0                     perl
aclocal                  glvnd                        perl5
adduser                  gnome                        piclone
agnostics                gnome-background-properties  pi-greeter
alacarte                 gnome-control-center         pi-language-selector
alsa                     gnupg                        pi-package
.........
...........

```

>The file you linked doesn't contain the manufacture

? line 3 !

**Comment by mikeg-de** [comment]
```# cat /etc/os-release
NAME="Home Assistant OS"
VERSION="9.3 (RaspberryPi 4 64bit)"
ID=haos
VERSION_ID=9.3
PRETTY_NAME="Home Assistant OS 9.3"
CPE_NAME=cpe:2.3:o:home-assistant:haos:9.3:*:production:*:*:*:rpi4-64:*
HOME_URL=https://hass.io/
VARIANT="Home Assistant OS RaspberryPi 4 64bit"
VARIANT_ID=rpi4-64
SUPERVISOR_MACHINE=raspberrypi4-64
SUPERVISOR_ARCH=aarch64

# cd /usr/share/
# /usr/share $ dir
-sh: /usr/share: Permission denied 
```

The device is still not recognized
![Bildschirmfoto 2022-10-27 um 20 31 26](https://user-images.githubusercontent.com/604842/198370534-c8cbdc6b-21bc-427d-88ef-249ef67ea9a6.jpg)

**Comment by Smanar** [comment]
Ha it s not the "Home Assistant Operating System" ?
But one other installation ? Still using docker ?
Because you are the first one I see making like that with an HA OS ....

>Quick question is there a documentation available which would guide someone crating a DDF and then proposing it to cut a corner for you?

For the moment the better link is this one (there is a video too) https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
And the better way is using an existing DDF used for a similar device.

After that you just need to make a PR https://github.com/dresden-elektronik/deconz-rest-plugin/pulls

BTW wana make the PR or wana I make it ? (to submit officialy, because i don't think your file will be persistant on your OS)
