### ISSUE TITLE
Bosch Radiator Thermostat II

### ISSUE THREAD

**Issue by h1k3r** [dresden-elektronik/deconz-rest-plugin#6476]
## Device

- Product name: Bosch Radiator Thermostat II.
- Manufacturer: BOSCH
- Model identifier: RBSH-TRV0-ZB-EU
- Device type : Please remove all unrelated device types. 
  - Sensor
  - Thermostat

## Screenshots

![grafik](https://user-images.githubusercontent.com/4005212/201473590-c14880ec-5e27-417d-a35a-8b7fcf9445af.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473106-bc6f609f-f1c0-49f2-8156-0779e2d069ad.png)

## Basic

![grafik](https://user-images.githubusercontent.com/4005212/201473115-dc49792a-3132-4f6c-a3d8-ab4b5da8354a.png)

## Power Configuration

![grafik](https://user-images.githubusercontent.com/4005212/201473121-302176d0-cdb1-4824-8ca1-b54a6e70e1e6.png)

## Thermostat User Interface Configuration

![grafik](https://user-images.githubusercontent.com/4005212/201473131-33f29c20-2929-4bd8-8783-2d77a16c5353.png)

## Thermostat

![grafik](https://user-images.githubusercontent.com/4005212/201473138-26b3e037-ffb8-4fc0-83b7-57369eaffed9.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473143-eaead52a-0cf7-4d6a-90b5-243f608462a7.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473149-95c48351-ec19-4ad9-afbf-d6d80cad1ba8.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473153-ca0309b3-410e-4709-a800-0786252051d0.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473163-2c981a56-e078-464d-a41e-087f0d58f54e.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473437-f42e78b9-d47b-42f4-be68-c87ff8740465.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473442-4d665492-0221-4597-9a4b-f2b3089b344e.png)

![grafik](https://user-images.githubusercontent.com/4005212/201473447-58944329-9ae4-4bd2-8e5c-6ae25fcf1290.png)

## Problem

This is the new Bosch Radiator thermostat II. Unfortunately deCONZ can not retrieve clusters of the ZigBee device. Probably for the proper paring ZigBee Install Code has to be used (it can be found on the device battery cover).

There is similar issue for another Bosch Smart Home ZigBee-based device: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6421.

**Comment by SwoopX** [comment]
I should get the device in a couple of days, than I can see what I can do

**Comment by h1k3r** [comment]
There is a new device request in zigbee2mqtt for the same model: https://github.com/Koenkk/zigbee2mqtt/issues/14005. Maybe it can be useful to get more information on device specification.

**Comment by mmattel** [comment]
Also see: https://github.com/Koenkk/zigbee2mqtt/issues/14926 ([New device support]: Bosch Radiator Thermostat II) which includes references to integration PR's

**Comment by besanur** [comment]
Did the DDF file working in your PR?

is the problem here with the install code?

**Comment by loefchen** [comment]
I'm looking for a solution too. Anyone got this working with deCONZ?

**Comment by jensflorian** [comment]
@h1k3r How did you pair the device in phoscon (as a light)?

**Comment by h1k3r** [comment]
@jensflorian unfortunately I was not able to pair the device yet (also with the version 2.21.00).

**Comment by SwoopX** [comment]
I just finished some working code to use install codes, which hopefully can be released to public without any issues. Probably not pretty, but gives the expected results. Hope we can internally discuss this and push it out real fast...

**Comment by besanur** [comment]
Maybe the best option is to switch to zigbee2mqtt

**Comment by besanur** [comment]
No Battery State is shown
Phoscon:
<img width="879" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7067485/2d3dc468-8bbe-4a59-8d3a-1a4d3e559b81">
deCONZ:
<img width="528" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7067485/aca5febd-82b8-4ff8-a621-1b59b36d6a28">
