### ISSUE TITLE
Device firmware upgrades

### ISSUE THREAD

**Issue by ACrazyConcept** [dresden-elektronik/deconz-rest-plugin#648]
Excuse my ignorance but I can't seem to find the answer.

Are any devices automatically firmware upgraded via deconz? If not can it be done manually?

**Comment by ebaauw** [comment]
In principle, deCONZ should be able to upgrade any connected devices, as long as it supports over-the-air firmware upgrades (through the _OTAU_ cluster), and as long as you can get your hands on the unencrypted firmware files.  See #96.

**Comment by ACrazyConcept** [comment]
Thanks I'll look into that thread.
