### ISSUE TITLE
Aqara Curtain Driver E1

### ISSUE THREAD

**Issue by samuele2723** [dresden-elektronik/deconz-rest-plugin#6480]
Device

- Product name: Curtain Driver E1
- Manufacturer: Aqara Lumi
- Model identifier: lumi.curtain.agl001
- Device type : Windows Covering
Other: Battery Powered roller shade driver

## Screenshots
![Schermata 2022-10-29 alle 12 06 58](https://user-images.githubusercontent.com/66970905/198825684-f2349b4a-3839-4203-a56c-fdd83a0a0945.png)
![Schermata 2022-10-29 alle 12 07 03](https://user-images.githubusercontent.com/66970905/198825685-f466a931-b853-497a-af65-1394c89df4ac.png)
![Schermata 2022-10-29 alle 12 07 10](https://user-images.githubusercontent.com/66970905/198825687-aa82f10d-82ed-4b01-b691-a4ae59dd9072.png)
![Schermata 2022-10-29 alle 12 07 17](https://user-images.githubusercontent.com/66970905/198825689-a4e54b2d-9a08-46df-be19-667239d50fc8.png)
![Schermata 2022-10-29 alle 12 07 24](https://user-images.githubusercontent.com/66970905/198825690-36f83852-9c0b-4377-baa4-42f69eeee9aa.png)
![Schermata 2022-10-29 alle 12 06 44](https://user-images.githubusercontent.com/66970905/198825692-8d6f2eeb-416b-4045-82b8-cfe6265a5436.png)
![Schermata 2022-10-29 alle 12 06 52](https://user-images.githubusercontent.com/66970905/198825693-9e3cb3e3-6107-4574-adef-2d7e30c0d227.png)

**Comment by Smanar** [comment]
Cf https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6469

**Comment by Mimiix** [comment]
Closing as this is a duplicate.
