### ISSUE TITLE
Philips Hue Dimmer

### ISSUE THREAD

**Issue by andreibanaru** [dresden-elektronik/deconz-rest-plugin#649]
Hello,

Even though my three dimmers appears in the Switches category in the Phoscon app and I've added lights to the switch groups, the dimmers are unable to control my Tradfri lights.
I see button press events though the API but the light state in Phoscon doesn't change and neither the actual lights.

I've tried deleting and re-adding them but that didn't help.
I've also tried adding them without first deleting the dimmer from Phoscon.
Cleaning up the entries from the sqlite3 database didn't help either.

One time I've managed to control the switch group with the ON/OFF buttons but the brighten/dim buttons didn't do anything.

PS: My Tradfri remote successfully controls my kitchen light thought a switch group. Only issue here is with the Philips Dimmers.

Thanks!
Andrei

**Comment by manup** [comment]
Can you please try to Touchlink the joined dimmer to a light by pressing the On button for a few seconds (5–10?) while holding the remote close to a light.

It is important that both, the light and the dimmer, is already part of the network which seems to be the case in your setup.

**Comment by ebaauw** [comment]
@manup, see my remark, https://github.com/dresden-elektronik/deconz-rest-plugin/issues/431#issuecomment-400060455: I think we told the dimmer not to touchlink.

> One time I've managed to control the switch group with the ON/OFF buttons but the brighten/dim buttons didn't do anything.

That would suggest the binding for the _OnOff_ cluster has been created, but the binding for the _Level_ cluster hasn't (yet).  @manup, I've asked this before, but failed to understand: who assigns the group ID: the deCONZ REST API or the Hue dimmer switch?

@andreibanaru, what's the firmware version of your Hue dimmer switches?

**Comment by manup** [comment]
>@manup, I've asked this before, but failed to understand: who assigns the group ID: the deCONZ REST API or the Hue dimmer switch?

The group id is assigned randomly by the switch itself and queried via the ZLL commissioning cluster (0x1000).

**Comment by ebaauw** [comment]
There’s no such cluster on the Hue dimmer switch?  Not on the Hue motion sensor either, only on Hue lights.

**Comment by manup** [comment]
It's there but not visible in the simple descriptors, not sure if it is intentional. The get group identifiers command should be issued by deCONZ when pairing the switch.

**Comment by andreibanaru** [comment]
@manup Touchlink between dimmer and light didn't work. The LED on the dimmer was just blinking as soon as I pressed the ON button.
@ebaauw firmware version on all 3 dimmers is 5.45.1.17846

In the end I've managed to make it work by re-adding the switch while it was already present in the database. Had to do it 2-3 times till the lights reacted to the button presses.

**Comment by AndreKoepke** [comment]
Same here. I have to re-adding the multiple times (3 times), before the switch is able to control the lights.

**Comment by manup** [comment]
> I have to re-adding the switch multiple times (3 times), before the switch is able to control the lights.

Which deCONZ version did you use? With recent versions 2.05.57 and up, the integration should work without such hassle.

**Comment by ajin** [comment]
@manup I can confirm that it took multiple attempts (also 3 times) to be able to control the lights. I am on 2.05.59 version.

**Comment by Davst** [comment]
I'm having this issue as well. trådfri lights won't react to philips switches.

**Comment by martinsteiger** [comment]
Same problem here although only with one Philips dimmer / switch. Any ideas?
