### ISSUE TITLE
Aubess 20A TS011F _TZ3000_hdopuwv6

### ISSUE THREAD

**Issue by mcormick** [dresden-elektronik/deconz-rest-plugin#6499]
## Device
- Product name: Aubess 20A Smart Socket
- Manufacturer: _TZ3000_hdopuwv6
- Model identifier: TS011F
- Device type : Smart Plug

Its another generic TUYA smart plug, but 20A and comes in a Aubess box. Only WiFi variant is linked: https://www.aubess.net/products/aubess-tuya-wifi-smart-socket-16a-work-with-alexa-google-home-yandex
Purchased here: https://nl.aliexpress.com/item/1005004753581287.html

Clusters seems to contain all relevant sensory data, but they seem not to be exposed, hence this device request.

Forum device request: https://forum.phoscon.de/t/aubess-20a-ts011f-tz3000-hdopuwv6-smart-plug/2715

## Screenshots
![clusters](https://user-images.githubusercontent.com/18458852/200136458-613428d9-06af-42c0-a15d-3735b2bd8a52.png)
![node-info](https://user-images.githubusercontent.com/18458852/200136494-48008ca0-76bc-49ad-8939-9493eb43630d.png)

### Basic
![cluster-0000-basic](https://user-images.githubusercontent.com/18458852/200136466-74d0b568-c11c-4854-a0bb-95130bbc47be.png)

### On/Off
![cluster-0006-onoff](https://user-images.githubusercontent.com/18458852/200136507-33de61cb-7a2c-4c61-b355-de17bbdf6b39.png)

### Simple Metering
![cluster-0702-simple-metering](https://user-images.githubusercontent.com/18458852/200136519-21541bb2-bb2e-493f-9da2-28e31648defb.png)

### Electrical Measurement
![cluster-0B04-electrical-measurement](https://user-images.githubusercontent.com/18458852/200136559-433f94e9-4534-42e2-9662-085403500289.png)

Light is exposed in Phoscon, Sensors not.
`{
    "etag": "e9962dd0d7aaf62cf1ad9ab548bdc36c",
    "hascolor": false,
    "lastannounced": null,
    "lastseen": "2022-11-05T19:03Z",
    "manufacturername": "_TZ3000_hdopuwv6",
    "modelid": "TS011F",
    "name": "Plug - Lounge - Multimedia",
    "state": {
        "alert": "none",
        "on": true,
        "reachable": true
    },
    "swversion": "77",
    "type": "On/Off plug-in unit",
    "uniqueid": "a4:c1:38:af:83:7d:93:df-01"
}`

**Comment by Smanar** [comment]
I think you can have some information here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6423

Make a try with this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_hdopuwv6",
  "modelid": "TS011F",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0B04"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "read": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val"
          },
          "refresh.interval": 100
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "read": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val"
          },
          "refresh.interval": 100
        },
        {
          "name": "state/voltage",
          "read": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val"
          },
          "refresh.interval": 100
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0702"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "read": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "eval": "Item.val = Attr.val * 10"
          },
          "refresh.interval": 10
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

**Comment by rejoe2** [comment]
This json basically seems to work, but the current value is a bit strange. This is how the measurement is interpreted in FHEM (power with 6W is realistic): 

current | 40 | 2022-11-14 20:21:37
lastseen | 2022-11-14T19:21Z | 2022-11-14 20:21:37
power | 6 | 2022-11-14 20:21:37
reachable | 1 | 2022-11-14 20:21:37
voltage | 232 | 2022-11-14 20:21:37

**Comment by Smanar** [comment]
6W is a little, it s like a LED bulb, agree with that ?
For the current you need to have something around 0.02  A

So we can divide tha vlaue by  1000 to have 0.04 but not realy precise.

Perhaps with a device wiht more consumption ?

To divide the value by 1000

```
        {
          "name": "state/current",
          "read": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 1000"
          },
          "refresh.interval": 100
        },
```

Can make direclty with the editor in the GUI.

**Comment by rejoe2** [comment]
I'm deconz running headless on a non standard port...
Changed it by editing the json directly and restart the service. Wattage now shows 61 (different bulb, now classical 60W instead of the LED bulb from my first post, so both values should be correct).

Now current is shown as "0", so there's some problem in the calculation (didn't look into the log until now). Typo?

**Comment by Smanar** [comment]
Yep, it's for compatibilities, It only report integer, so you need to have at least 1 A

**Comment by rejoe2** [comment]
OK, so the last proposal with the 1000 division seems to be ok.

Do you need any additional info from my side or is it sufficient what we know by now?

**Comment by rejoe2** [comment]
Or might that be integrated in some similar device? (didn't check if there's already a suitable one)

**Comment by Smanar** [comment]
Ok so my bad, have take a look in the API and current is in mA

<html><body>


current | UInt16 | The measured current (in mA). | RW
-- | -- | -- | --



</body>
</html>

So I will remove the / 1000

https://dresden-elektronik.github.io/deconz-rest-doc/devices/innr/sp_120_plug/#state-attributes_1

And there is a Aubess folder, So I will make a PR just for this device https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6537
