### ISSUE TITLE
Gateway failover / high availability

### ISSUE THREAD

**Issue by christmasjumper** [dresden-elektronik/deconz-rest-plugin#650]
Hi,

This isn't an issue, more of a question / idea.

Are there any options for high availability with deconz? Obviously the zigbee devices will have a mesh, so the gateway going down doesn't always impact lights etc - but I also have all of my motion and door sensors which report back to homebridge running on a mac, where I've configured a kind of alarm system.

In general things are pretty reliable with deconz, but there have been occasions where a random reboot of the RPI has been required - to that end I'm trying to ensure that there's redundancy in the system and just wondered if there was any way of connecting two gateways together so that one can take over from the other if one goes down.

Just a thought really, it's probably an edge case and I'm sure there's plenty else on the list, but it would be a great feature!

Cheers

**Comment by ebaauw** [comment]
I don’t think it’s feasible to run multiple deCONZ instances on the same ZigBee network in an active/active setup.  While you can join multiple RaspBees and/or ConBees to the same network, only one can be the coordinator; the others are regular routers.  You can have multiple gateways, but most sensors will only send reports to one, and you don’t want multiple gateways polling your lights in a larger ZigBee network (which I assume you have, or you wouldn’t be worrying about high availability).

So indeed, your best strategy is to configure your switches (and sensors) to control your lights directly as fallback (not all switches and only a few sensors support this), and to have a standby gateway ready (use deCONZ backup/restore to keep the standby gateway in sync, or boot your test Raspberry from (a backup copy of) the production uSD card).

I find that, in production, I hardly need to reboot the Raspberry Pi, and that I restart deCONZ only when I update the version, RaspBee firmware, or configuration.

I did create a UPS solution for my production Raspberry using a USB power bank that supports pass-throught charging.  Of course the lights don’t work during a power outage, but this does enable me to turn them off quickly, after power has been restored (and the lights come on at their unholy factory default setting).

You can run multiple instances of homebridge and homebridge-hue (on different servers, or using a different user directory) connected to the same deCONZ instance.  You could create two homes in HomeKit, each with their own instance of homebridge.  Then again, I find, in production, I only restart homebridge when upgrading one of my plugins or homebridge itself.
