### ISSUE TITLE
ZHAThermostat change schedule is using wrong http method

### ISSUE THREAD

**Issue by luka6000** [dresden-elektronik/deconz-rest-plugin#6501]
## Describe the bug

ZHAThermostat sensor is using method POST to configure schedule but the docs says it should be PUT as described here https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/sensors/#change-sensor-config
Method POST is not documented at all.

## Steps to reproduce the behavior

I'm trying to update Danfoss Ally thermostats schedule with HA deconz.configure service. This service is using PUT method to update sensor config. And I get error from deconz
```
pydeconz.errors.RequestError: 4 /sensors/86/config/schedule/W124 method, PUT, not available for resource, /sensors/86/config/schedule/W124
```

This can also be replicated with POSTMAN
![image](https://user-images.githubusercontent.com/1110994/200172050-12e5dce6-4c0f-4edf-a496-904ed91204ab.png)

Works ok with POST but this is not documented so not implemented in HA service
![image](https://user-images.githubusercontent.com/1110994/200172150-6cf8285d-ce50-451e-8482-67a3ff217816.png)

## Expected behavior

Sensor schedule configuration (and all configurations) should be possible with PUT method

## Environment

 - Host system: Raspberry Pi4 32bit
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26720700
 - deCONZ version: 2.19.1
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? esphome board

**Comment by Smanar** [comment]
Ha right and it's alone

```
    // POST, DELETE /api/<apikey>/sensors/<id>/config/schedule/Wbbb
    else if ((req.path.size() == 7) && (req.hdr.method() == QLatin1String("POST") || req.hdr.method() == QLatin1String("DELETE")) && (req.path[4] == QLatin1String("config")) && (req.path[5] == QLatin1String("schedule")))
    {
        return changeThermostatSchedule(req, rsp);
    }
```

**Comment by luka6000** [comment]
@Smanar would you allow something non breaking, like
```
    // PUT, POST, DELETE /api/<apikey>/sensors/<id>/config/schedule/Wbbb
    else if ((req.path.size() == 7) && (req.hdr.method() == QLatin1String("PUT") || req.hdr.method() == QLatin1String("POST") || req.hdr.method() == QLatin1String("DELETE")) && (req.path[4] == QLatin1String("config")) && (req.path[5] == QLatin1String("schedule")))
    {
        return changeThermostatSchedule(req, rsp);
    }
```
?

**Comment by Smanar** [comment]
Long story, but for the moment it will not move.
From @ebaauw this request is used only to add or remove a day, not to change it, so for him it's POST or DELETE but not PUT
