### ISSUE TITLE
Niko Connectable Motor Control 3A (552-72311)

### ISSUE THREAD

**Issue by jecako** [dresden-elektronik/deconz-rest-plugin#6504]
## Device

- Product name: Niko Connectable Motor Control 3A (552-72311)
- Manufacturer: NIKO NV
- Model identifier: Connectable Motor Control,3A 
- Device type : 
  - Switch (see: https://www.niko.eu/en/article/552-72311)

## Screenshots

- Endpoints and clusters of the node
![image](https://user-images.githubusercontent.com/117580812/200175297-3e803110-2bab-46a1-8ff1-392d251e17ba.png)

- Node Info panel
![image](https://user-images.githubusercontent.com/117580812/200175325-70be395b-c56f-4d0a-8248-103700f0ca7d.png)

### Basic
![image](https://user-images.githubusercontent.com/117580812/200177839-269452b3-abfe-41b6-91f7-b2b3342fc6f8.png)

### Identify
![image](https://user-images.githubusercontent.com/117580812/200177863-d526c4b1-fbb4-4eed-9f66-5744d4a0961a.png)

### Window Covering Cluster
![image](https://user-images.githubusercontent.com/117580812/200177985-99a1adba-9221-4977-b50f-82a03a4fb1e1.png)

### Niko specific
![image](https://user-images.githubusercontent.com/117580812/200178109-24e4dca7-5e76-40f5-bd11-8ed107ad799f.png)

### Groups
![image](https://user-images.githubusercontent.com/117580812/200177902-8b0dcfae-adb6-452f-9b78-b323e6a4c6c9.png)

### Scenes
![image](https://user-images.githubusercontent.com/117580812/200177921-0ea979cf-900b-4dc7-9c61-2f5bba82bef5.png)

### OTAU
![image](https://user-images.githubusercontent.com/117580812/200178139-9efee8bd-41d8-4cbd-8f7e-db0a80468109.png)

### Diagnostics
![image](https://user-images.githubusercontent.com/117580812/200178075-138630b7-a272-4f16-90c0-aeb752338fd6.png)

**Comment by Mimiix** [comment]
Please add all screenshots.

**Comment by jecako** [comment]
> Please add all screenshots.

Done!

**Comment by Mimiix** [comment]
Please make sure all attributes are showing . That's at least not the case for the window covering cluster.

Can you also provide a overview of all clusters ?

**Comment by Smanar** [comment]
But the device don't work natively ? all seem fine with this device.
