### ISSUE TITLE
Girier Tuya Zigbee 3.0 Switch Module 2CH no neutral

### ISSUE THREAD

**Issue by Marzmarz1** [dresden-elektronik/deconz-rest-plugin#6505]
## Device

- Product name: Girier Tuya Zigbee 3.0 Switch Module 2CH
- Manufacturer: _TZ3000_jl7qyupf
- Model identifier: TS0012
- Device type : 
    - Switch
  

## Screenshots
![image](https://user-images.githubusercontent.com/26327659/200175774-f876782f-e72a-4635-8041-11980b439d6f.png)

### Basic
![image](https://user-images.githubusercontent.com/26327659/200175250-faed321d-ca83-402c-b90c-63af01d9670f.png)
![image](https://user-images.githubusercontent.com/26327659/200175582-8ecd9e51-e6a9-47ca-9fa5-6714ba3ff58c.png)

### Identify
![image](https://user-images.githubusercontent.com/26327659/200175285-3ce466b9-35d7-4f5e-bcab-3b022423580e.png)

### Groups
![image](https://user-images.githubusercontent.com/26327659/200175319-8c6b4a91-2eeb-43a6-8ead-2d36028390ad.png)
![image](https://user-images.githubusercontent.com/26327659/200175352-e7851759-02ed-4348-b954-0ad0ad1b975b.png)
### Scenes
![image](https://user-images.githubusercontent.com/26327659/200175405-f9918209-ab3f-4e4a-b90e-a712df620e2b.png)
![image](https://user-images.githubusercontent.com/26327659/200175426-de8d84a9-b26b-481c-a6e1-e57bb2ad102a.png)
![image](https://user-images.githubusercontent.com/26327659/200175457-eaa79b08-1ad5-4a01-b25e-084da53d7b40.png)
![image](https://user-images.githubusercontent.com/26327659/200175492-e253c7c6-d456-4285-b3a3-96e76448c882.png)

### On/Off
01
![image](https://user-images.githubusercontent.com/26327659/200175508-7937d20f-33d3-4220-a762-d24a1ff407e2.png)
![image](https://user-images.githubusercontent.com/26327659/200175534-8ee0b209-d443-4cb4-bc1e-9d49a268d749.png)

02
![image](https://user-images.githubusercontent.com/26327659/200175611-21aa5133-b72c-43da-8f16-23c6b7a8a5a1.png)
![image](https://user-images.githubusercontent.com/26327659/200175633-b21fe8f3-1adf-47c7-a382-b313300e99f5.png)

**Comment by Smanar** [comment]
Hello can try this DDF

```
{
   "schema":"devcap1.schema.json",
   "manufacturername":"_TZ3000_jl7qyupf",
   "modelid":"TS0012",
   "product":"Girier Tuya Zigbee 3.0 Switch Module 2CH no neutral",
   "sleeper":false,
   "status":"Gold",
   "subdevices":[
      {
         "type":"$TYPE_ON_OFF_LIGHT",
         "restapi":"/lights",
         "uuid":[
            "$address.ext",
            "0x01"
         ],
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"state/on",
               "refresh.interval":5
            },
            {
               "name":"state/reachable"
            }
         ]
      },
      {
         "type":"$TYPE_ON_OFF_OUTPUT",
         "restapi":"/lights",
         "uuid":[
            "$address.ext",
            "0x02"
         ],
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"state/on",
               "refresh.interval":5
            },
            {
               "name":"state/reachable"
            }
         ]
      }
   ],
   "bindings":[
      {
         "bind":"unicast",
         "src.ep":1,
         "dst.ep":1,
         "cl":"0x0006",
         "report":[
            {
               "at":"0x0000",
               "dt":"0x10",
               "min":1,
               "max":300
            }
         ]
      },
      {
         "bind":"unicast",
         "src.ep":2,
         "dst.ep":1,
         "cl":"0x0006",
         "report":[
            {
               "at":"0x0000",
               "dt":"0x10",
               "min":1,
               "max":300
            }
         ]
      }
   ]
}
```

If it don't work can try direclty with the API to see if the device use the cluster 0x0006, just test the "on" and "off" command.

**Comment by Marzmarz1** [comment]
Hello, 
I don't how I get this DDF file direct in the node, so tried to compile the file my self.  I dragged the on off lights under the device tab (2 times; for switch 1 and switch 2). and I gave switch 2 another number (0x02)
Here are some screenshots:
![image](https://user-images.githubusercontent.com/26327659/200190339-ad1f26c7-7717-4226-a17b-fbcf7e097413.png)

![image](https://user-images.githubusercontent.com/26327659/200190356-e89d646d-639d-4e12-8eae-00cd897023b3.png)

![image](https://user-images.githubusercontent.com/26327659/200190370-57e6a908-5dbb-4a0e-b1c1-06f8b382c59c.png)

So far so good. But i'm missing the last part of your DDF. The text with "bindings". 
![image](https://user-images.githubusercontent.com/26327659/200191236-0574ea11-92b1-405b-9963-76b84fe3481d.png)

Here is my json text:
![image](https://user-images.githubusercontent.com/26327659/200190414-a20bb90c-3526-4691-9566-2387b2c04686.png)
![image](https://user-images.githubusercontent.com/26327659/200190435-affd1753-1172-4928-820f-baf70ee683fa.png)

In Phoncon I see 2 lights : 
![image](https://user-images.githubusercontent.com/26327659/200190485-d705beec-7ec1-46c3-af18-bbb9cfb344fc.png)
(don't mind the names)
but in HA, I only see one light: 
![image](https://user-images.githubusercontent.com/26327659/200190566-820e5a98-fe07-457d-bd27-3151943c7335.png)
But when I open this light, I see 2 controls. 
![image](https://user-images.githubusercontent.com/26327659/200190610-492ff6b8-2d44-4e59-8118-48f96e35cab1.png)
And now the strange part, when I switch plug 1, in no time plug 2 is automatically also switched on. And when I switch plug 1 off, switch 2 automatically switches off.
Can somebody give me some help to solve this? I would like to get 2 seperate switches, so I can make some automations.

**Comment by Smanar** [comment]
Yep, you miss the binding, but will see this part after, without it you will just miss state return, but you need to be able to send request.

In fact your device is special, it have too 2 manufacture clusters, and perhaps it use them instead of using the cluster we are using in the DDF (the 0x0006)

So to be sure, can you use the GUI, select the node, select the endpoint 01(it's the big number), select the cluster "on/off" the 0x0006, then in the cluster panel try the "on" and "off" request ?

To see if using the GUI you have the same issue ?

**Comment by Marzmarz1** [comment]
I've used the GUI and on both endpoints (01 & 02) and the on/off requests working separetely. In the GUI i don't have the issue that both lights are switching on and off together.
On/off properties01:
![image](https://user-images.githubusercontent.com/26327659/200373180-4ec2147b-ff56-47fc-8eae-c4de8b2cba8f.png)

On/off properties 02:
![image](https://user-images.githubusercontent.com/26327659/200373036-4a73f056-816e-444c-b4f5-f76c25910a5f.png)
As you can see, they are exactly the same.

**Comment by Smanar** [comment]
So if it work with GUI it's a good news.

Try to make the DDF more selective
- select the state/on
- fill value in "parse" and read", with the good endpoint (1 for the first one and 2 for the second one) instead of "auto"
- save the DDF
- make hot reload

**Comment by Marzmarz1** [comment]
> I've used the GUI and on both endpoints (01 & 02) and the on/off requests working separetely. In the GUI i don't have the issue that both lights are switching on and off together. On/off properties01: ![image](https://user-images.githubusercontent.com/26327659/200373180-4ec2147b-ff56-47fc-8eae-c4de8b2cba8f.png)
> 
> On/off properties 02: ![image](https://user-images.githubusercontent.com/26327659/200373036-4a73f056-816e-444c-b4f5-f76c25910a5f.png) As you can see, they are exactly the same.

I was wrong. the 2 seprate connections are working as one. Your solution is not working. I can't switch them separately.  I'm back at quare one...

**Comment by Smanar** [comment]
Have found some information.

And unfortunately this device need a special sequence to be unlocked.
So not possible using only DDF.
