### ISSUE TITLE
ZigBee water leakage sensor

### ISSUE THREAD

**Issue by Chris-126** [dresden-elektronik/deconz-rest-plugin#6522]
## Device

- Product name: ZigBee water leakage sensor
- Manufacturer: _TZ3000_qhozxs2b
- Model identifier: TS0207
- Device type : 
  - Sensor

### Basic
![image](https://user-images.githubusercontent.com/45980710/201054642-eb49a0bc-f458-4812-94ac-9bd4de2b05c0.png)

### Identify
![image](https://user-images.githubusercontent.com/45980710/201054709-a14c4b84-a4c6-4198-8a28-2385427b23ff.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/45980710/201055220-d5b4d823-7670-4b98-8d39-9efcd4665689.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/45980710/201055608-06055814-ece6-43c4-9f5e-95c8aa6feb5b.png)
![image](https://user-images.githubusercontent.com/45980710/201055686-347066b2-eed6-4240-a67f-c180fad4f661.png)

**Comment by Smanar** [comment]
Hello can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_d16y6col", "_TZ3000_ww9i3e0y", "_TZ3000_qhozxs2b"],
  "modelid": ["TS0207", "TS0207", "TS0207"],
  "vendor": "Tuya",
  "product": "Tuya water sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "ZHAWater",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "config/enrolled"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery",
          "awake": true
        },
        {
          "name": "state/tampered",
          "awake": true
        },
        {
          "name": "state/water",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by Chris-126** [comment]
@Smanar actually, I stumbled upon this DDF option ... wasn't aware of it until this day.
This works like a charm!! Thank you very much!!!!!!!

**Comment by Chris-126** [comment]
Actually, one issue. The battery shows 0%.

**Comment by Smanar** [comment]
Lol, I think I have issue on battery on my 4 / 5 last DDF ^^

Pls wait some hours, then if the value is still 0, read the attribute 0x0021 in the cluster 0x0001 with the GUI, it need to force an update, if yes bind issue, else DDF issue or the device don't support it.

**Comment by Chris-126** [comment]
Hmm, for whatever reason the battery is now showing correct without any change? Great! Thanks alot! 

Now let's see how long the sensors battery is doing in the fridge ;) We had some issues with water there... kids being careless etc. and we didn't notice the amount of water behind the drawers. Sometime I have funny ideas :P
