### ISSUE TITLE
New Device  Tuya Smoke Alarm YG400A

### ISSUE THREAD

**Issue by FelixHaimmerer** [dresden-elektronik/deconz-rest-plugin#6532]
## Device
https://zigbee.blakadder.com/Tuya_YG400A.html

- Product name: Smoke Alarm YG400A
- Manufacturer: Tuya
- Model identifier: _TZE200_ntcy3xu1
- Device type :
  - Sensor
  - Siren

## Screenshots
![grafik](https://user-images.githubusercontent.com/35505313/201704940-041aadb4-0bd1-48e1-ac16-430c7769567b.png)

### Basic
- detect smoke
- show batterie state

### Alarms
- ring smoke alarm

**Comment by FelixHaimmerer** [comment]
Sorry for the late response. 

here are the requested screenshots:

![Screenshot 2022-12-09 115852](https://user-images.githubusercontent.com/35505313/206687681-a7a3c939-1c2e-431b-ad94-31d0f6bd609d.png)
![Screenshot 2022-12-09 115821](https://user-images.githubusercontent.com/35505313/206687686-be55b644-8350-4aff-807c-09443f76f881.png)
![Screenshot 2022-12-09 115907](https://user-images.githubusercontent.com/35505313/206687687-cc8507bd-a960-4598-aea5-6b37f50782bb.png)


Thanks!

**Comment by Mimiix** [comment]
Please add all screenshots.

**Comment by FelixHaimmerer** [comment]
![image](https://user-images.githubusercontent.com/35505313/206713569-92368858-02ae-45de-85b8-5bf4b27ff24f.png)

Sorry I have never done that bevore. Ist this what you meant? Thanks! :)

**Comment by Mimiix** [comment]
> ![image](https://user-images.githubusercontent.com/35505313/206713569-92368858-02ae-45de-85b8-5bf4b27ff24f.png)
> 
> Sorry I have never done that bevore. Ist this what you meant? Thanks! :)

We need to have a screenshot of every cluster. https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by Mimiix** [comment]
Nevermind, i'll close this issue and re-open : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6236
