### ISSUE TITLE
Aubess Temperature & Humidity Sensor TS0601 (_TZE200_znbl8dj5) with LCD display

### ISSUE THREAD

**Issue by Finne75** [dresden-elektronik/deconz-rest-plugin#6535]
## Device

- Product name: Multi-function Electronic Hygrometer ([link](https://www.aliexpress.com/item/1005004116638127.html))
- Manufacturer: _TZE200_znbl8dj5
- Model identifier: TS0601
- Device type : 
  - Sensor

## Screenshots

![image](https://user-images.githubusercontent.com/76888443/201873863-af602a73-0df6-46f5-ba05-4d421b0071a4.png)

![image](https://user-images.githubusercontent.com/76888443/201873949-0fde0f35-3813-4a3f-b903-3c060ba7908a.png)

### Basic
![image](https://user-images.githubusercontent.com/76888443/201873232-974dfd2e-cdb8-40c7-b777-1c07c27fff22.png)

### Temperature
![image](https://user-images.githubusercontent.com/76888443/201873499-8c801ea1-0f2f-4c71-99d7-10f574c66ea4.png)

### Humidity
![image](https://user-images.githubusercontent.com/76888443/201873581-4b4861ca-fac0-4ea1-ad6f-c1c28c479657.png)

### Power
![image](https://user-images.githubusercontent.com/76888443/201873402-f43a9696-d370-46e4-a5b5-c9beb5f7b8ca.png)

### Tuya specific
![image](https://user-images.githubusercontent.com/76888443/201873674-300c81c4-8e24-4e43-94c5-5915ecaee35e.png)

[Link](https://forum.phoscon.de/t/aubess-temperature-humidity-sensor-ts0601-tze200-znbl8dj5-with-lcd-display/2785) to forum discussion. I created a DDF, and the device is visible in the API, but the values do not update:

API entry for temperature sensor:
~~~
{
    "config": {
        "battery": 0,
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "etag": "5e7e1d5f788b1c6fadb0b0405562dbbb",
    "lastannounced": null,
    "lastseen": "2022-11-14T08:34Z",
    "manufacturername": "_TZE200_znbl8dj5",
    "modelid": "TS0601",
    "name": "Temperature 455",
    "state": {
        "lastupdated": "2022-11-14T08:19:27.523",
        "temperature": 0
    },
    "type": "ZHATemperature",
    "uniqueid": "a4:c1:38:78:9b:8d:42:71-01-0402"
}
~~~

Draft DDF:
~~~
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_znbl8dj5",
  "modelid": "TS0601",
  "vendor": "Aubess",
  "product": "TS0601",
  "sleeper": true,
  "status": "Gold",
  "path": "/devices/aubess_temp_hum_ts0601_local.json",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {
            "at": "0x0000",
            "cl": "0x0402",
            "ep": 1,
            "eval": "Item.val = Attr.val + R.item('config/offset').val",
            "fn": "zcl"
          },
          "default": 0
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {
            "at": "0x0015",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "config/offset",
          "description": "Relative offset to the main measured value.",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "parse": {
            "at": "0x0000",
            "cl": "0x0405",
            "ep": 1,
            "eval": "Item.val = Attr.val + R.item('config/offset').val",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 3600,
          "change": "0x00000032"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 60,
          "max": 3600,
          "change": "0x00000064"
        }
      ]
    }
  ]
}

~~~

**Comment by Finne75** [comment]
It works, including battery. Only thing was that the multiplier for humidity needs to be 100 instead of 10 (maybe typo?). I will create a PR. Thanks!

**Comment by Smanar** [comment]
>including battery

Ha yesss ^^

>Only thing was that the multiplier for humidity needs to be 100 instead of 10 (maybe typo?)

No was just untested.

On your PR can you include the clone with using

```
  "manufacturername": ["_TZE200_znbl8dj5", "_TZE200_qoy0ekbd"],
  "modelid": ["TS0601", "TS0601"],
```

**Comment by Finne75** [comment]
I found two DDFs in the devices/tuya folder which seem to be for the same type of device, [nous_hum_temp_e6.json](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/nous_hum_temp_e6.json) (#6306) and [_TZE200_bjawzodf_hum_temp.json](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZE200_bjawzodf_hum_temp.json) (#6094). Interestingly, I did not find a DDF for _TZE200_qoy0ekbd (#6063). The Nous one has the right multiplier for for humidity. 

Should we merge all into one DDF or add this clone e.g. to #6306?

**Comment by Smanar** [comment]
Tuya and their fuc*ing clone.

The nous is the same but it was already in a dedicated folder.
For the _TZE200_bjawzodf I have checked and right it's a temperature/humidity with display but bad luck he don't have the same multiplier for for humidity, and on Z2m, the device is alone with this multiplier ....

So for me the better solution is making a DDF only for _TZE200_znbl8dj5 and _TZE200_qoy0ekbd (and yes the DDF was never submitted, but it's same device for sure)

**Comment by Smanar** [comment]
Just for information (for your future PR) there is an option to auto close issue when the Pr is merged.
On the PR page on the right you have a panel with "developpement" here you can select this topic, that will be closed in same time the PR is merged.
