### ISSUE TITLE
[Sensor] SOLE HOME Smart Wireless Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by Mephisto090** [dresden-elektronik/deconz-rest-plugin#6539]
## Device

- Product name: SOLE HOME Smart Wireless Temperature and Humidity Sensor
- Manufacturer: _TZ3000_bguser20
- Model identifier: TS0201
- Device type : Sensor

## Product Parameters
Quiescent current: <= 10uA
Alarm current: <= 15mA
Low voltage and undervoltage <=2,6V
Zigbee working Frequency: 2.400GHz - 2.484GHz
Detection Temp: -10°C - +60°C
Detection Hum.: 0 - 100% RH
Working Temp: -10°C - +50°C
Working Hum.: max. 95% RH

Amazon Link: [SOLE HOME Smart Wireless Temperature and Humidity Sensor](https://www.amazon.de/gp/product/B09K3QM8PV/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

## Screenshots

![image](https://user-images.githubusercontent.com/85995176/202180796-6cd9f339-a48f-4a3f-aa39-7e48381a0cb2.png)

### Basic
![image](https://user-images.githubusercontent.com/85995176/202180598-908c2ca0-c238-46a5-bb3f-b09da0dc4357.png)

### Identify
![image](https://user-images.githubusercontent.com/85995176/202180662-0e92af83-460f-4952-bc20-7f92f6e8860f.png)

### Device Temperature
![image](https://user-images.githubusercontent.com/85995176/202180762-d5ded951-0fbd-441b-b0d5-bb2c0de8ca2e.png)
![image](https://user-images.githubusercontent.com/85995176/202180875-184462a0-41cd-4294-956b-6d20510bb9c5.png)

### On/Off
![image](https://user-images.githubusercontent.com/85995176/202180957-43108a3b-92bc-4480-bebe-d5e4a43da8f2.png)

**Comment by Smanar** [comment]
Hello, can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_yd2e749y", "_TZ3000_fllyghyj", "_TZ3000_lbtpiody", "_TZ3000_5nrcorgu", "_TZ3000_ena8vgqb", "_TZ3000_bguser20"],
  "modelid": ["TS0201", "TS0201", "TS0201", "TS0201", "TS0201", "TS0201"],
  "vendor": "Tuya",
  "product": "Temperature and humidity sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl"
          }
        },
        {
          "name": "config/offset"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl"
          }
        },
        {
          "name": "config/offset"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "awake": true
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 300,
          "change": "0x00000064"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 60,
          "max": 300,
          "change": "0x00000064"
        }
      ]
    }
  ]
}
```

**Comment by Mephisto090** [comment]
Where can I find instructions on how to test it?

**Comment by Smanar** [comment]
Depend of OS

> All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

If you have HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

You just need to create a text file caled what_you_want_.json in the "devices" folder.
Then restart deconz and include the device.

**Comment by Mephisto090** [comment]
The manufacturer still looks wrong. I'll see if the temperature and humidity update automatically

![image](https://user-images.githubusercontent.com/85995176/202240263-9b5f13db-872b-41ad-96be-fe48d443783e.png)
![image](https://user-images.githubusercontent.com/85995176/202240309-5f660e16-2dd6-48dc-9b07-7387ce748124.png)

**Comment by Smanar** [comment]
>The manufacturer still looks wrong


Nono, it's the good one ^^

But idk why the picture is a motion sensor ....

Have added your device here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6244

**Comment by Mephisto090** [comment]
All my Multisensors are motion sensor

![image](https://user-images.githubusercontent.com/85995176/202241752-82c42009-84a5-47a4-8758-35646a63705e.png)

**Comment by Mephisto090** [comment]
> All my Multisensors are motion sensor. The Other one all Sonoff
> 
> ![image](https://user-images.githubusercontent.com/85995176/202241752-82c42009-84a5-47a4-8758-35646a63705e.png)

Should I create a new issues for this?

**Comment by Smanar** [comment]
For the picture error ?
It's from phoscon, we haven't impact on this application, there is another github for it.

If it's not a problem for you, you can let it as it.

**Comment by Mephisto090** [comment]
It looks like it doesn't automatically read the temperature. Even a manual "read" does not work. See screenshot. I'll wait 10 minutes to see if the Phoscon app shows an update

![image](https://user-images.githubusercontent.com/85995176/202242873-40899d39-7ef8-4171-824d-16e430d5f76d.png)

**Comment by Mephisto090** [comment]
> For the picture error ? It's from phoscon, we haven't impact on this application, there is another github for it.
> 
> If it's not a problem for you, you can let it as it.

Do you have a link, so I can open a ticket there?

**Comment by Smanar** [comment]
This device is sleeping like all sensors, you need to awake it in same time you press the "read" button (with using the reset button generaly)

So the phoscon github is closed https://github.com/dresden-elektronik/phoscon-app-beta and they say to use now https://forum.phoscon.de/c/phoscon/17

And yes 15mn is a lot, if the temperature move. Have you tried to heat the sensor with your hands ?

I m seing this device need the tuya unlock sequence, so if the values don't move, I will be not possible to add it to deconz.

**Comment by Mephisto090** [comment]
> And yes 15mn is a lot, if the temperature move. Have you tried to heat the sensor with your hands ?

Yes that didn't work

![image](https://user-images.githubusercontent.com/85995176/202257967-3439b7e2-df40-4626-8ddb-23a8f26d2161.png)

**Comment by Smanar** [comment]
Ok, so was the missing "tuya unlock sequence".
Sorry but this device can't be added for the moment.

**Comment by Mephisto090** [comment]
What do you mean?

**Comment by Smanar** [comment]
This device need the coordinator ask for 5/6 attributes in a good order to unlock all feature on it.
