### ISSUE TITLE
"ConBee II" light appearing with "Unknown" type instead of "Configuration tool"

### ISSUE THREAD

**Issue by Thomas-Vos** [dresden-elektronik/deconz-rest-plugin#6552]
## Describe the bug
For some users the "Conbee II" light is appearing with type "Unknown". Should this not be "Configuration tool"? On my setup it is.

Report from a user:
```
    "manufacturername": "dresden elektronik",
    "modelid": "ConBee II",
    "name": "Unknown 13",
    "state": {
      "reachable": true
    },
    "swversion": "0x26780700",
    "type": "Unknown",
```

## Steps to reproduce the behavior
None

## Expected behavior
Type equals `Configuration tool`

## Screenshots
None

## Environment

 - Host system: Raspberry Pi, maybe others.
 - Running method: Unsure
 - Firmware version: Unsure
 - deCONZ version: Unsure
 - Device: The following were reported to me so far: ConBee I / ConBee II / RaspBee I
 - Do you use an USB extension cable: not relevant
 - Is there any other USB or serial devices connected to the host system? If so: Which? Unsure

## deCONZ Logs

None

## Additional context

None

**Comment by Mimiix** [comment]
It's like that on mine . Can confirm this happens.

**Comment by popy2k14** [comment]
I can also confirm this.
(I think i reported to @Thomas-Vos 😅 )

**Comment by ebaauw** [comment]
As I mentioned on Discord, please double-check the _Endpoints_ tab of the _deCONZ Network Settings_ in the GUI.

**Comment by Smanar** [comment]
Yep, but lot of users, haven't the GUI, and this issue can causes problem on third app that check for "Configuration tool"

**Comment by popy2k14** [comment]
CHecked the Endpoints tab of the deCONZ Network Settings in the GUI.
There are just hex numbers and no string indicating "unknown" or anything else.

What to look for?

**Comment by ebaauw** [comment]
Please post a screenshot.  Basically these numbers define how the device advertises itself on the Zigbee network: what endpoints with what profile, device type, input (server) and output (client) clusters.  The definitions of these numbers (translating them to text) is in `general.xml`.

**Comment by ebaauw** [comment]
I should like this:
![Screenshot_2022-11-20_at_22 10 54](https://user-images.githubusercontent.com/22179355/203537409-bf4e6f08-5439-4335-83fc-e82f72aed215.png)

As I posted on Discord: _Device ID_ 0x0005 in the Home Automation profile (0x0104) is the Configuration Tool.  If memory serves, you might need to Save and then leave and rejoin the network before the settings take.  It's a bit messy.  Haven't touched this in years and would advise anyone to stay away from it.

**Comment by popy2k14** [comment]
It's exactly the same on my system like in @ebaauw screenshot.
Here is the info from the api (removed unessasary things):

```
{
   "manufacturername":"dresden elektronik",
   "modelid":"ConBee II",
   "name":"Configuration tool",
   "state":{
      "reachable":true
   },
   "swversion":"0x26780700",
   "type":"Unknown",
}
```

In my case, name is correct but type is unknown.

**Comment by ebaauw** [comment]
And it shows as _Configuration Tool_ in the GUI?

**Comment by Mimiix** [comment]
@ebaauw  My screen:
![image](https://user-images.githubusercontent.com/43333120/203633356-352553c2-a95d-4d31-a780-5de732903a8d.png)

        "13": {
            "etag": "8beb967da3792b291ecec206862dee42",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2022-11-23T19:00Z",
            "manufacturername": "dresden elektronik",
            "modelid": "ConBee II",
            "name": "Unknown 13",
            "state": {
                "reachable": true
            },
            "swversion": "0x26780700",
            "type": "Unknown",
            "uniqueid": "00:21:2e:ff:ff:04:d7:94-01"
        }

**Comment by SwoopX** [comment]
Got the same as Dennis

**Comment by ebaauw** [comment]
I’m at a loss.  The GUI, `uniqueid`, and absence of `state/on` and `state/alert` all indicate that the API plugin recognises the Configuration tool on startup.  But `type` doesn’t seem to be updated by `setHaEndpoint()` for previously existing `lights` resources.  I suspect it’s wrong in the database.  Normally I’d suggest deleting the node and repairing the device, but the node for the coordinator cannot be deleted.  Force-reading the descriptors from the GUI won’t update the `type` either.  The only possible action seems to be patching the database, not something I’d normally recommend.

Even more elusive is how the type came to be Unknown in the first place.  Had it always been that?  Or did it change with an upgrade, backup/restore, replacement of the coordinator device, move deCONZ to another server, or something?  Start of deCONZ without it finding ConBee maybe?  Has anyone seen this on a RaspBee?

**Comment by Mimiix** [comment]
> Even more elusive is how the type came to be Unknown in the first place. Had it always been that? Or did it change with an upgrade, backup/restore, replacement of the coordinator device, move deCONZ to another server, or something? Start of deCONZ without it finding ConBee maybe? Has anyone seen this on a RaspBee?

Sometime it changed i suppose. However, it might have happened when my groups also went apeshit.  This was between 12.6 and 13.4. My groups numbers out of the sudden: 
![image](https://user-images.githubusercontent.com/43333120/203722922-be1a4f14-0c25-4407-b6a4-1f49f9cf6053.png)

That's the only time something major changed in my network.

Nevertheless: I am not going to patch my database.

**Comment by ebaauw** [comment]
> But type doesn’t seem to be updated by setHaEndpoint() for previously existing lights resources. I suspect it’s wrong in the database.

I think it's actually set alright, but it's overwritten by `LightNode::jsonToResourceItems()`, which is called from `sqliteLoadLightNodeCallback()`.

**Comment by ebaauw** [comment]
PR should resolve the symptoms, in that the value for `type` is no longer restored from the database, so the type will be set from the _Device Type_ when (re-) creating the `lights` resource on startup.  Still no clue how it came to be "Unknown" in the first place.

**Comment by Thomas-Vos** [comment]
Great, thanks for fixing this Erik.

**Comment by Thomas-Vos** [comment]
Not fixed
