### ISSUE TITLE
VNC Node Info Wrong Name

### ISSUE THREAD

**Issue by sansonifabio** [dresden-elektronik/deconz-rest-plugin#6554]
## Describe the bug
 Hello, I noticed that the name that was created in the Phoscon app is not displayed in the view under VNC Source Routing.

## Steps to reproduce the behavior
1. Add new light under version 2.19.02
2. Give it for example the living room light and save
3. Then the VNC source routing contains for example Smart Plug 6 instead of courtyard lighting.
4. The name is correct in the API information.

## Screenshots
![IMG_0313](https://user-images.githubusercontent.com/88761140/202912375-6c34a5c9-0402-4512-ab29-ee738baa3a8d.jpg)

## Environment

Host system: Raspberry Pi
Running method: Raspbian
deCONZ version: 2.19.02
Device: RaspBee Gateway

**Comment by ebaauw** [comment]
Yeah, noticed this too under v2.19.2.  Changing the `name` in the API will no longer update the node label in the GUI.  It will be updated after you restart deCONZ, though.  It's on Manu's todo list.
