### ISSUE TITLE
Climax technology Vibration sensor SVGS-1ZBS

### ISSUE THREAD

**Issue by Idaho947** [dresden-elektronik/deconz-rest-plugin#6561]
## Device

- Product name: Climax technology Vibration sensor SVGS-1ZBS
- Manufacturer: Climax technology
- Model identifier: SVGS_00.00.03.08TC
- Device type : Sensor

### Basic
![BASIC](https://user-images.githubusercontent.com/45599888/203059880-757c778e-5580-4177-9b71-0a337cd9c2d8.PNG)

### Identify
![Identify](https://user-images.githubusercontent.com/45599888/203059352-e161751a-e6fc-4de6-8729-4db557b16523.PNG)

### Alarms
![IASZONE](https://user-images.githubusercontent.com/45599888/203059919-22b25bab-89a5-4a60-9bd9-0ce02278d61c.PNG)

**Comment by Mimiix** [comment]
Can you please  add a screenshot of the total cluster list?

**Comment by Idaho947** [comment]
Ah yes. Just this line is missing :
![basic2](https://user-images.githubusercontent.com/45599888/203072660-bcf14c40-daa8-41da-ac2c-a0cef51e7f88.JPG)

**Comment by Idaho947** [comment]
Ah ok sorry.
![global](https://user-images.githubusercontent.com/45599888/203092646-473b06a3-b196-430c-aed9-eb635b5c5684.JPG)

**Comment by Mimiix** [comment]
Thanks :)

**Comment by Idaho947** [comment]
Hello, any news about this intégration ?

**Comment by Smanar** [comment]
Can try  this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "ClimaxTechnology",
  "modelid": "SVGS_00.00.03.08TC",
  "vendor": "Tuya",
  "product": "Vibration sensor SVGS-1ZBS",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_VIBRATION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/vibration"
        }
      ]
    }
  ]
}
```

But I haven't similar device to compare, will be a test.

**Comment by Idaho947** [comment]
In phoscon it's stay like this :
![phoscon](https://user-images.githubusercontent.com/45599888/205987236-93d234c5-9aa9-4fb6-b355-07cea45b5cb9.JPG)

That in pullcontrol :
![pullcontrol](https://user-images.githubusercontent.com/45599888/205987514-344821e7-0fa8-478e-bf56-340a3af27ad9.JPG)

**Comment by Smanar** [comment]
Ha ?
The poll cluster is not visible on your capture here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6561#issuecomment-1322230331
You have more cluster ATM ?

BTW you have nothing in logs with the flag "IAS" (on deconz/help/debug view) when you try to trigger a vibration ?

In the cluster 0x0500, attribute 0x0002 you can see something change ?

Perhaps you need the bind with the cluster 0x0500

```
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by Idaho947** [comment]
No I juste have the first notification. It stay at true.

**Comment by SwoopX** [comment]
This device could eventually work with configured attribute reporting on the status 0x0002 (if the device supports it). I guess we have like a handful of devices around where that works.

**Comment by Idaho947** [comment]
With the new ddf, the senser is not see by phoson.

**Comment by Smanar** [comment]
```
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
      "report": [
        {
          "at": "0x0002",
          "dt": "0x19",
          "min": 300,
          "max": 3600,
        }
      ]
    }
```

**Comment by Idaho947** [comment]
It doesn't work. It's stay at true more than five minutes

**Comment by Smanar** [comment]
Not a surprise for me.
You have made a "hot relaod" or a new inclusion ? because the bind setting can take time on battery powered device.

You third app can't just handle notification.

As workaround I know some users have cheated with changing the type to ZHAPresence (because this kind of device have support for the "auto return" to false.

**Comment by Smanar** [comment]
I don't think phoscon is able to manage alarm sensor ?

**Comment by Idaho947** [comment]
In phoscon a see in "Vibration detected" in the sensor menu like my picture higher

**Comment by Smanar** [comment]
Ha yes right, but you can do something with the detection ?
I never used phoscon for automation so idk if you can use this king of sensor for event.
