### ISSUE TITLE
Luminea Home Control Wassermelder mit externem Sensor _TZ3000_4uvovz4r Model TS0207

### ISSUE THREAD

**Issue by riegelbrau** [dresden-elektronik/deconz-rest-plugin#6568]
## Device

- Product name: Luminea Home Control Wassermelder mit externem Sensor
- Manufacturer: unknown
- Model identifier: unknown
- Device type : Please remove all unrelated device types. 
  - Sensor (Water Leak)

### Basic
![grafik](https://user-images.githubusercontent.com/73437730/203533788-5691d0bc-468b-479d-99e7-4239d9ef3d3e.png)

### Identify
![grafik](https://user-images.githubusercontent.com/73437730/203534249-1517e506-47ff-4492-85d5-f9c5296dccdb.png)

### IAS Zone
![grafik](https://user-images.githubusercontent.com/73437730/203534195-33835a04-ab38-4ede-af96-2efdc373033e.png)
### Power Configuration
![grafik](https://user-images.githubusercontent.com/73437730/203534343-72b56f4d-3923-489d-a6dc-f10eb40292af.png)

### Node Info
![grafik](https://user-images.githubusercontent.com/73437730/203533597-fed69a93-c31e-4d25-957a-c29549906daf.png)

**Comment by riegelbrau** [comment]
Here I add some photos of the device itself:
![grafik](https://user-images.githubusercontent.com/73437730/203627722-ddba6fc4-c073-4061-827a-5afda61624cf.png)
![grafik](https://user-images.githubusercontent.com/73437730/203627772-5471f1aa-aef9-4215-b5b5-0e093e1c3841.png)

**Comment by riegelbrau** [comment]
I don't know what to do to keep this issue open!

**Comment by flopp999** [comment]
On what system are you running on? Windows, Linux, HA?
I can help you to add a DDF that might work

**Comment by riegelbrau** [comment]
This would be great. I was looking for some Getting Started with DDF instructions, but don't find them.
I am running deConz in Docker on a Raspberry Pi.

**Comment by flopp999** [comment]
OK. You need to access the docker SSH.
SSH to RPi then run
"docker container ls"
"docker exec -it xxxxxx /bin/bash"  xxxx is the container ID
"cd data/.local/share/dresden-elektronik/deCONZ/devices/"

**Comment by flopp999** [comment]
open deCONZ, the software that look like this 
![image](https://user-images.githubusercontent.com/21694965/209017345-e6d99699-81c1-4aa9-ab9f-2cfd6980fcac.png)
select your device and right click and select Edit DDF
It might be empty thats OK.
File-Open, from root folder open _TZ3000_d16...
![image](https://user-images.githubusercontent.com/21694965/209017592-6cd00563-28a9-4699-a703-d4b58453e153.png)

**Comment by flopp999** [comment]
When you opened that file, File-Save as and go to "cd data/.local/share/dresden-elektronik/deCONZ/devices/"
Save the file as "_TZ3000_water_sensor.json"
restart deconz, remove your device and add it again from Phoscon(webpage)

**Comment by riegelbrau** [comment]
Hello, 
when I do File->Open in deCONZ, I see this emoty directory:
![grafik](https://user-images.githubusercontent.com/73437730/209376147-3b4e3401-0286-4f09-862a-398501b38ffc.png)

I don't have this path "cd data/.local/share/dresden-elektronik/deCONZ/devices/" inside my docker container.

**Comment by riegelbrau** [comment]
OK, found it in /usr/share/deCONZ. But it seems I cannot "save as" the DDF, I cannot see the new file after save as.
Neverthelesse I deleted the cluster and restarted the deconz docker container. After that I see my device again:
![grafik](https://user-images.githubusercontent.com/73437730/209383367-8366cd85-66e1-4bfc-b6a6-d4d6989f634d.png)
When I open the DDF, now it shows:
![grafik](https://user-images.githubusercontent.com/73437730/209383484-a9c4ca7f-cc87-48dc-8310-77ff1aef1f76.png)
and under Preview this:
![grafik](https://user-images.githubusercontent.com/73437730/209383689-7a243e41-01ae-475f-b677-b6a419db8008.png)
Could it be that some file system security settings are incorrect?

Thanks and regards
Christoph

**Comment by riegelbrau** [comment]
Additional info: I run this deCONZ image: deconzcommunity/deconz.

**Comment by flopp999** [comment]
Can you try to open "Computer" and then usr/....

**Comment by riegelbrau** [comment]
I've got it running!
These were the steps:
1. I opened the file _TZ3000_d16... again.
2. Added the manufacturer as _TZ300_4uvovz4r and the Model ID as TS0207.
3. This time I saved the DDF file successfully as "_TZ3000_water_sensor.json" in /opt/deCONZ/devices.
4. After restart of deconz I still could not pair the new sensor from the Phoscon web page.
5. I opened the DDF of the unknown device again and removed the Manufacturer entry for _TZ3000_d16... and the corresponding Model ID. In addition I changed the status to GOLD.
6. After restart of deconz I could pair the sensor successfully.
![grafik](https://user-images.githubusercontent.com/73437730/209391375-0f18234e-d8eb-482d-8ded-60f703f9a832.png)
and
![grafik](https://user-images.githubusercontent.com/73437730/209391405-83aa4c8d-00b9-4b70-aed4-b648fb7f9d0f.png)
It's a bit strange that the deCONZ app shows a partially red battery symbol, while the Web App shows "Batterie Zustand ok"

**Comment by riegelbrau** [comment]
Thanks for your assistance!

**Comment by flopp999** [comment]
Great that you got it working

**Comment by gforums** [comment]
Thanks to all of you. Bought the same device and received it today. Can confirm it's working with that DDF. If you could add it to a further update, that works be great. Best, Christian

**Comment by Kayinwonderland** [comment]
Can someone here help me to get it working? I am a noob with all this deconz stuff. I have no idea what to access to do the steps. i can only login to Deconz from my HA

**Comment by Mimiix** [comment]
> Can someone here help me to get it working? I am a noob with all this deconz stuff. I have no idea what to access to do the steps. i can only login to Deconz from my HA

This si something to ask on the forums.
