### ISSUE TITLE
Sonoff Disconnect

### ISSUE THREAD

**Issue by Mephisto090** [dresden-elektronik/deconz-rest-plugin#6576]
## Describe the bug

hello,

I've had a lot to do lately with keeping the sensors "alive". I have to reconnect the sensors every day. I press on Phoscon on reconnect and press the button on the sensor. So deconz gets a sign of life and everything works normally.

## Expected behavior

Automatic reconnect or no regular crashes

## Screenshots

PhosconApp:
![image](https://user-images.githubusercontent.com/85995176/204130234-7aa4d953-ac52-4123-8fd1-f7f2a46413f5.png)

Jarvis (iobroker)
![image](https://user-images.githubusercontent.com/85995176/204130245-7ea4efd0-d4b4-4a38-b46d-e5e6085f07fa.png)

## Environment

 - Host system: Windows-PC
 - Running method: Windows
 - Firmware version: 26780700
 - deCONZ version: 2.19.00 / 19.9.2022
 - Device: ConBee II
 - Do you use an USB extension cable: Yes (2m)
 - Is there any other USB or serial devices connected to the host system? If so: Which?: USB Hard Drive

## deCONZ Logs

```
11:35:23:245 Remove websocket 192.168.178.70:64080 after error Unknown error, close-code: 1000, reason: 
11:35:23:254 New websocket 192.168.178.70:64139 (state: 3) 
11:36:23:262 Remove websocket 192.168.178.70:64139 after error Unknown error, close-code: 1000, reason: 
11:36:23:276 New websocket 192.168.178.70:64187 (state: 3) 
11:37:23:290 Remove websocket 192.168.178.70:64187 after error Unknown error, close-code: 1000, reason: 
11:37:23:315 New websocket 192.168.178.70:64232 (state: 3) 
```

**Comment by Mimiix** [comment]
Hi

As this is not a issue as described in #5113 i am closing this issue.

Feel free to open a topic in the forums.

Kind regards,
Dennis

**Comment by lupa18** [comment]
@Mephisto090 did you get them working?

**Comment by Mimiix** [comment]
> @Mephisto090 did you get them working? (same here). And I am editing some articles here:
> 
> * https://zigbee.blakadder.com/Sonoff_SNZB-01.html
> * will try to edit the others
> 
> and prevent users to get trapped with those devices.

This is not the place to ask.

I have sonoff that I'm happy with. So basing it on this guy with a issue is plain wrong(especially when his issue has nothing to do with the sonoff).
