### ISSUE TITLE
AIXI-SHS Zigbee Radiator Actuator

### ISSUE THREAD

**Issue by Joska59** [dresden-elektronik/deconz-rest-plugin#6593]
## Device

- Product name: AIXI-SHS Zigbee Radiator Actuator.
- Manufacturer: TZE200 cwnjrr72
- Model identifier: TS0601
- Device type : 
  - Thermostat

## Screenshots
![image](https://user-images.githubusercontent.com/115286175/205511605-bdb004b1-64b6-43e7-ab91-3c96165fa7f8.png)
Basic Cluster: 
![image](https://user-images.githubusercontent.com/115286175/205676928-a0a95a84-b30c-436c-9551-3a471351742d.png)
Groups cluster
![image](https://user-images.githubusercontent.com/115286175/205677262-e06ca30b-a542-42ff-8afe-7de0fedcbb0e.png)
Scenes cluster
![image](https://user-images.githubusercontent.com/115286175/205677489-4fd4c452-e45b-4398-a3fb-58b5c8bdb32d.png)
Tuya cluster
![image](https://user-images.githubusercontent.com/115286175/205677671-e44709b2-779a-449d-8a09-0a49221d5321.png)
OTAU cluster
![image](https://user-images.githubusercontent.com/115286175/205677877-6852a120-91af-4ca7-9311-ca284178a4af.png)
time cluster: empty

**Comment by Mimiix** [comment]
Hi, can you please add all cluster screenshots?

**Comment by Joska59** [comment]
Hi Mimiix
Bag your pardon, but can you explain, what's meant with cluster-screenshots. I'll do my best, but haven't found that. 
ah, I see this tab is part of the deconz-app, but the tab is empty. Okay, I'll try to get it work and fill up the lost information.

If you can give me some hints, why the tab is empty, that you!

Regards, Joska

**Comment by Mimiix** [comment]
Hi,

Sure no problem :) 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

This should be covering.

Kind regards,

**Comment by Joska59** [comment]
Hi Mimiix

Hope so, it is correct now. Screenshot not show all inforemation, but as I've seen, the missing part is filled with 0 (null)

**Comment by Joska59** [comment]
Hi

Found this:
![image](https://user-images.githubusercontent.com/115286175/205716342-a982155d-dd16-4a00-b398-68b8736d95e0.png)

Does that mean, this device has been configure for deconz? I've searched for manufactor name, as written on another page of github.

If I search for model name, I can dind this:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4401

So, I'm in doubt, if there is a solution for my device too?

**Comment by Joska59** [comment]
Found this: 
![image](https://user-images.githubusercontent.com/115286175/205724117-2a86c214-b126-4ed8-9569-eae590b7ec68.png)

It is the same, I used for the model above.

**Comment by Joska59** [comment]
Allthough there is a big volume of information, I'm confused. Found this https://channelstore.roku.com/ and it looks like very similar to my device. One question about the manufatur name: does TZE200 cwnjrr72 mean, it is in in doubt different  from _TZE200_bjawzodf, allthough the modelid is the same?

**Comment by Joska59** [comment]
Hello Mimiix
Does the fact , the device is listened here, mean, somebody is able to interpret the cluster info? Or is there a manual how to use these information by myself? Does dresden-eletronik collect these information?

**Comment by Joska59** [comment]
Can someone tell me, or give me an example link, how thermostats are represented in phoscon?
I've seen some more types auf the same modelid and the same manufature-ID, so I think, it could be possible to start some configuration with these information.

**Comment by Mimiix** [comment]
Hi,

A dev needs to look into it and help out. @Smanar perhaps. If they don't, your a bit out lof luck as the documentation is lacking and they are volunteers just like myself.

Sometimes Dresden does it, but they hardly do anymore.

**Comment by Smanar** [comment]
It's a tuya TRV, so same problem, without support using DDF, still not possible.
The solution is WIP but still in waiting list.

**Comment by Joska59** [comment]
As I remember, one tuya TRV has been supported, but can't find it yet. Please give me a hint, what it means _support of DDF_.
For now, it seems to be of no worth, waiting for a solution in nearer future. Right?

I'd asked Dresden-Elektronik in an further mail.

**Comment by Smanar** [comment]
Now new device need to be added using DDF.
But the support for tuya TRV is not finished.

**Comment by Joska59** [comment]
Hi smanar. Don't understand, what you say with this.

**Comment by Joska59** [comment]
> But it's not possible yet for tuya TRV.

What is the reason for this? Does nobody knows the correct parameters, or is there another reason?

**Comment by Smanar** [comment]
No there is a already a working PR, just need to wait for validation.

**Comment by Joska59** [comment]
> No there is a already a working PR,

What does "PR" mean?

**Comment by Smanar** [comment]
Pull Request https://github.com/dresden-elektronik/deconz-rest-plugin/pulls

**Comment by Joska59** [comment]
Thank you

**Comment by technodrome** [comment]
Sorry if this is slightly offtopic, couldn't find any appropriate PR:
What's the state of support for ZigBeeMoesHY368-ZB (HY368-ZB - Tuya Smart) radiator actuator (valve)? I've seen there's a problem with different manufacturers so even though it is always the same model and there's support for this valve according to PR's, [this comment](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4401#issuecomment-1287220836) says support is not coming.

**Comment by Smanar** [comment]
Need the manufacture name to be sure, but no new TRV since long time, waiting for the DDF core support Tuya TRV.

**Comment by majo-sc** [comment]
Hello. Can the thermostat be used in the meantime? Visually, I like them very much. I would like to use some with deconz.

**Comment by Smanar** [comment]
There is a PR in waiting list to support Tuya TRV.
If you can compile it I can try to make a DDF for this device.

**Comment by majo-sc** [comment]
> There is a PR in waiting list to support Tuya TRV #6674
> If you can compile it I can try to make a DDF for this device.

Sorry, but my programming skills are not good enough for that:-(
