### ISSUE TITLE
Nous Smart ZigBee Socket A1Z (_TZ3000_2putqrmw)

### ISSUE THREAD

**Issue by nWRqenkF** [dresden-elektronik/deconz-rest-plugin#6594]
## Device

- Product name: Nous Smart ZigBee Socket A1Z
- Manufacturer: _TZ3000_2putqrmw
- Model identifier: TS011F
- Device type : 
  - Light
  - Sensor

## Screenshots
![grafik](https://user-images.githubusercontent.com/12986539/205708446-4b4723f4-8af8-44e1-9e12-58409320cf0d.png)
![grafik](https://user-images.githubusercontent.com/12986539/205912864-dba1057c-48e1-4054-b624-32304885ab37.png)

### Basic
![grafik](https://user-images.githubusercontent.com/12986539/205708684-2d3aaacc-7afb-448e-a23d-016faed3076f.png)

### Identify
![grafik](https://user-images.githubusercontent.com/12986539/205708812-76ae6016-f282-4740-acf3-af054bb0ae46.png)

### Groups
![grafik](https://user-images.githubusercontent.com/12986539/205709546-b3dd4b8b-927b-48db-9795-fbfd038c82da.png)

### Scenes
![grafik](https://user-images.githubusercontent.com/12986539/205709263-e9a4fffc-2d9d-4ca1-9c9d-e727c2836a18.png)
![grafik](https://user-images.githubusercontent.com/12986539/205709324-962be769-788a-43eb-af43-39c228206c05.png)
![grafik](https://user-images.githubusercontent.com/12986539/205709372-f7cd043e-cd71-4a15-b233-1b95e0ba5923.png)
![grafik](https://user-images.githubusercontent.com/12986539/205709441-440e294e-b1b5-4b43-b743-5cfe3ec5c1a3.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/12986539/205709059-11d919bc-4a92-416a-b4ff-ca3b66015e22.png)
![grafik](https://user-images.githubusercontent.com/12986539/205709149-d80ce1ed-7375-4e7a-91dd-cbfc5f661553.png)

### Simple Metering
![grafik](https://user-images.githubusercontent.com/12986539/205709690-119ef4df-3d0c-45f1-97ed-d66792fe7945.png)
![grafik](https://user-images.githubusercontent.com/12986539/205709756-e66607de-cf57-4fb7-93d6-3b127501755c.png)

### Electrical Measurement
![grafik](https://user-images.githubusercontent.com/12986539/205709897-30d130c8-0fa2-46ff-9e9e-06d26aa9914a.png)
![grafik](https://user-images.githubusercontent.com/12986539/205709968-51cd677b-f36e-4feb-a93b-90b8189c51a8.png)

### OTAU
![grafik](https://user-images.githubusercontent.com/12986539/205710143-08ca0f22-534d-47e0-bfd0-d2a86875f51f.png)

**Comment by nWRqenkF** [comment]
I'm aware of the issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5917 but the alphanumeric part of the manufacturer part is different (here "_TZ3000_2putqrmw" vs "_TZ3000_ksw8qtmt" in issue 5917).

Anyhow: the device is recognized in phoscon, but in openhab3 via deconz-REST-API only the On/Off-Channel is available, the electric measurement is missing.

**Comment by nWRqenkF** [comment]
Current DDF from deCONZ application:

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_2putqrmw",
  "modelid": "TS011F",
  "product": "TS011F",
  "sleeper": false,
  "status": "Draft",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by Smanar** [comment]
Can test if it's just a clone.
You already have the DDF for the Nous A1z here https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_ksw8qtmt_plug_nous_a1z.json

You just need to edit 

```
  "manufacturername": "_TZ3000_2putqrmw",
  "modelid": "TS011F",
```

and replace them with 

```
  "manufacturername": ["_TZ3000_2putqrmw", "_TZ3000_2putqrmw"]
  "modelid": ["TS011F", "TS011F"],
```

Them you can restart deconz and re-include your device.

**Comment by nWRqenkF** [comment]
Thanks worked for me!

Minor correction (missing comma in 1st line):
````
"manufacturername": ["_TZ3000_2putqrmw", "_TZ3000_2putqrmw"],
"modelid": ["TS011F", "TS011F"],
````

**Comment by Smanar** [comment]
It's the deconz working mode ^^.
Look at the uniqueID, it's composed by the MAC adress - the endpoint - The cluster.

Deconz make a part for "light" + a part for "sensor"
And you have 1 sensor by used cluster.

So it depend of device, some device have consumption and power on the same cluster, not this one.

**Comment by SvenMartin81** [comment]
Hi, i have the Same device with the Same situation. Only the Switch is there.

**Comment by Smanar** [comment]
The switch ? Not a plug ?

You have too  the _TZ3000_2putqrmw ? You can use this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6589

**Comment by SvenMartin81** [comment]
Hi,

Yes i will Check this. Can i Upload from Deconz with any doubt? Or Simi Need my Special Write access on and Folders?


Mit freundlichen Grüßen

Sven Martin
Mühlenring 63
23923 Selmsdorf

Tel.: +49 (0)172 5180261

________________________________
Von: Smanar ***@***.***>
Gesendet: Wednesday, December 14, 2022 6:53:02 PM
An: dresden-elektronik/deconz-rest-plugin ***@***.***>
Cc: SvenMartin81 ***@***.***>; Comment ***@***.***>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Nous Smart ZigBee Socket A1Z (_TZ3000_2putqrmw) (Issue #6594)


The switch ? Not a plug ?

You have too the _TZ3000_2putqrmw ? You can use this DDF #6589<https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6589>

**Comment by SvenMartin81** [comment]
Do you know when this will be integrales in the next Deconz Update?

Or can I add a new file in the Tuya Finder with These changes and the System will recognice this.

In the actuall Deconz-2.19.03-qt5.deb was this Not changed.

Please, leg ne know.

Mit freundlichen Grüßen

Sven Martin
Mühlenring 63
23923 Selmsdorf

Tel.: +49 (0)172 5180261

________________________________
Von: Smanar ***@***.***>
Gesendet: Wednesday, December 14, 2022 6:53:02 PM
An: dresden-elektronik/deconz-rest-plugin ***@***.***>
Cc: SvenMartin81 ***@***.***>; Comment ***@***.***>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Nous Smart ZigBee Socket A1Z (_TZ3000_2putqrmw) (Issue #6594)


The switch ? Not a plug ?

You have too the _TZ3000_2putqrmw ? You can use this DDF #6589<https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6589>

**Comment by SvenMartin81** [comment]
Hi,
I am Running raspi on a Pi4B with Raspbee on it.
But i cannot overwrite the files because I have No write Access with the User „Pi“.
What can i do?


Mit freundlichen Grüßen

Sven Martin
Mühlenring 63
23923 Selmsdorf

Tel.: +49 (0)172 5180261

________________________________
Von: Smanar ***@***.***>
Gesendet: Thursday, December 15, 2022 6:47:04 PM
An: dresden-elektronik/deconz-rest-plugin ***@***.***>
Cc: SvenMartin81 ***@***.***>; Comment ***@***.***>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Nous Smart ZigBee Socket A1Z (_TZ3000_2putqrmw) (Issue #6594)


What is your OS ?

On normal one

All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

On HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

I hope we will have the file officialy in next version.

**Comment by SvenMartin81** [comment]
Hi,

I got it but the only missing Sensor in Home Assistant is the voltage Sensor. The „power“ and „consumption“ Sensor is Running fine.

What can i so to have the „voltage“ Sensor?

Mit freundlichen Grüßen

Sven Martin
Mühlenring 63
23923 Selmsdorf

Tel.: +49 (0)172 5180261

________________________________
Von: Sven Martin ***@***.***>
Gesendet: Thursday, December 15, 2022 7:03:14 PM
An: dresden-elektronik/deconz-rest-plugin ***@***.***>; dresden-elektronik/deconz-rest-plugin ***@***.***>
Cc: Comment ***@***.***>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Nous Smart ZigBee Socket A1Z (_TZ3000_2putqrmw) (Issue #6594)

Hi,
I am Running raspi on a Pi4B with Raspbee on it.
But i cannot overwrite the files because I have No write Access with the User „Pi“.
What can i do?


Mit freundlichen Grüßen

Sven Martin
Mühlenring 63
23923 Selmsdorf

Tel.: +49 (0)172 5180261

________________________________
Von: Smanar ***@***.***>
Gesendet: Thursday, December 15, 2022 6:47:04 PM
An: dresden-elektronik/deconz-rest-plugin ***@***.***>
Cc: SvenMartin81 ***@***.***>; Comment ***@***.***>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] Nous Smart ZigBee Socket A1Z (_TZ3000_2putqrmw) (Issue #6594)


What is your OS ?

On normal one

All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

On HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

I hope we will have the file officialy in next version.

**Comment by Mimiix** [comment]
@SvenMartin81  Voltage is a attribute of the Power entity in HA. You need to create a template sensor for taht to become a seperate sensor.

**Comment by Alex-joomla** [comment]
I' ve managed to edit the ddf and so I'm able to display power and consumption. Consumption is running fine but power is displayed as 0 as in deconz. But power is a calculated value of current and voltage, should it been calculated by the device or by deconz?

<img width="442" alt="Bildschirmfoto 2022-12-17 um 23 16 26" src="https://user-images.githubusercontent.com/32268233/208267925-d3686713-cc34-45f1-8ca4-0e5ea6addb8a.png">
<img width="1188" alt="Bildschirmfoto 2022-12-17 um 23 16 41" src="https://user-images.githubusercontent.com/32268233/208267926-7d692a90-aec1-4fa3-bf2b-68a4452b665b.png">

**Comment by Alex-joomla** [comment]
> The „power“ and „consumption“ Sensor is Running fine. 
> […](#)

Really, your power sensor is running fine? Mine shows nothing

**Comment by Smanar** [comment]
Perhaps you don't have enought consumption ?
But if the value is 0 in deconz, you will have 0 in the API, the value is gived by the device.

**Comment by Alex-joomla** [comment]
> Perhaps you don't have enought consumption ?
> But if the value is 0 in deconz, you will have 0 in the API, the value is gived by the device.

Thats exactly the case. Power draw was too low, had fairy lights in it. Tested it with a water boiler and it worked.

Although I cannot understand it. Current is measured, why doesn't it calculate it to power? Consumption rises anyway.

**Comment by karsten-eger** [comment]
hmm, got two of those as well and they are detected just fine as a plug. All other parts are missing. I upgraded deconz and phoscon and edited the files as mentioned in #6589 but it's still detected as _TZ3000_2putqrmw and not nous at all.

restarted deconz and the raspi several times, no change.
there are no files in the users local folder either.

**Comment by Smanar** [comment]
>Although I cannot understand it. Current is measured, why doesn't it calculate it to power? Consumption rises anyway.

Need to ask that to tuya devs ^^

>but it's still detected as _TZ3000_2putqrmw and not nous at all.

It is and will stay a _TZ3000_2putqrmw , the only difference is with the DDF you will have 2 more sensors

**Comment by karsten-eger** [comment]
> It is and will stay a _TZ3000_2putqrmw , the only difference is with the DDF you will have 2 more sensors
I thought the device manufacturer is named nous after the change in the phoscon ui

But anyways, no, no new sensors detected. Only the plugs so far.

**Comment by Smanar** [comment]
You have the GUI ? you can check if the DDF is used by deconz with making a right clic and "edit DDF", it will open the editor and you will see the used DDF.

After adding the DDF you need to re-include the device, for new entries will be created.

**Comment by Smanar** [comment]
You can run deconz with command line with debug enabled, but will be a little overkill just for that.

You have edited the old file ? perhaps  a typo inside ? You are not using docker ?

**Comment by karsten-eger** [comment]
Ah they are reachable via the API but they are not listed as sensors in the sensor list.
`{
    "config": {
        "on": true,
        "reachable": true
    },
    "etag": "[...]",
    "lastannounced": null,
    "lastseen": "2022-12-22T14:08Z",
    "manufacturername": "_TZ3000_2putqrmw",
    "modelid": "TS011F",
    "name": "Consumption 35",
    "state": {
        "consumption": 0,
        "lastupdated": "2022-12-22T14:04:56.880"
    },
    "swversion": "1.0.13",
    "type": "ZHAConsumption",
    "uniqueid": "a4:c1:38:0d:7e:b9:71:38-01-0702"
}`

The rest is not a deconz problem I guess.

**Comment by Smanar** [comment]
But this JSON is from the sensors list ?
You mean in the phoscon sensors list ?

**Comment by karsten-eger** [comment]
yep, Phoscon Webapp API client sensor information. Each of those two plugs exposes two sensors - consumtion and power respectively

**Comment by Smanar** [comment]
So it's working now ?

**Comment by karsten-eger** [comment]
I guess this counts as working regarding deconz. Thought it will use the given manufacturer name though.

Now it's a phoscon issue.

Thx for your help and patience. 😄

**Comment by bankhans** [comment]
>   "manufacturername": ["_TZ3000_2putqrmw", "_TZ3000_2putqrmw"]
>   "modelid": ["TS011F", "TS011F"],


Thank You,
i can see now power and consumption in openhab.
![grafik](https://user-images.githubusercontent.com/28827836/209986635-eaaf5d88-413d-43cc-8868-39761747b736.png)

**Comment by RezzZ** [comment]
@karsten-eger did you just press the plug button for 10 seconds for the new sensors to show up while looking for new lights in phoscon app?
I'm trying to get the plugs working with power consumption but API and homeassistant only show on/off switch for me.
I'm running deconz in docker and I updated the file inside my docker container to reflect the recommended changes..

**Comment by Kenny-BC** [comment]
Hey Guys,
i can add my Nous 2putqrmw and after i edit the ddf and save it under:
/home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices
Now i´ve the consumption and power values in homeassistant. 

I don´t know but when i open the phoscon gui sometimes there are 3 plugins online and sometimes 1 and 5 minutes later 5.

Can someone explain why they hopping? Normally they run as repeater and at the moment i´ve 68 devices listed in deconz.

**Comment by Mimiix** [comment]
> Hey Guys, i can add my Nous 2putqrmw and after i edit the ddf and save it under: /home//.local/share/dresden-elektronik/deCONZ/devices Now i´ve the consumption and power values in homeassistant.
> 
> I don´t know but when i open the phoscon gui sometimes there are 3 plugins online and sometimes 1 and 5 minutes later 5.
> 
> Can someone explain why they hopping? Normally they run as repeater and at the moment i´ve 68 devices listed in deconz.

The above is unrelated to this issue or device(interference issues). Please ask on Discord or Forums.
