### ISSUE TITLE
Add DDF for Xiaomi Aqara Smart Pet Feeder C1 (PETC1-M01/aqara.feeder.acn001)

### ISSUE THREAD

**Issue by lboue** [dresden-elektronik/deconz-rest-plugin#6595]
## Xiaomi Aqara Aqara Smart Pet Feeder C1

- Product name: Smart Pet Feeder C1
- Manufacturer: Xiaomi Aqara
- Model identifier: aqara.feeder.acn001
- Device type : Pet Feeder
- Product page: https://www.aqara.com/us/product/smart-pet-feeder-c1

### Basic
![image](https://user-images.githubusercontent.com/938089/205918935-d196ffe1-632c-4179-9bf3-97109f1250ed.png)

### Identify
![image](https://user-images.githubusercontent.com/938089/205918409-58e8abfb-1a8f-42c0-a80d-ca3fa43ed754.png)

### Groups
![image](https://user-images.githubusercontent.com/938089/205918602-321c25ad-40de-4bd3-845c-1166caa57868.png)

### Scenes
![image](https://user-images.githubusercontent.com/938089/205918805-07706f3c-4a02-4b60-949a-6ae0fe40408a.png)

### On/Off
![image](https://user-images.githubusercontent.com/938089/205919192-902a7d0b-957c-4342-8961-1a2d7bfc25fb.png)

### Other clusters that are not mentioned above
FCC0 Lumi specific
![image](https://user-images.githubusercontent.com/938089/205919294-ada8a639-176a-419b-8030-d5c1ff4741b8.png)

Support has been add for :
1. zigbee-herdsman with this [PR #4775: Aqara Pet Feeder C1 aqara.feeder.acn001 ](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4775) and [Aqara Pet Feeder C1 aqara.feeder.acn001 #4988](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4988).
2. zigbee2mqtt with [New device support: Aqara pet feed c1 #13583](https://github.com/Koenkk/zigbee2mqtt)

Will we be able to resume these elements to avoid starting from scratch?

Regards

**Comment by rdbtn-no** [comment]
Would like support for this device as well.

**Comment by frnsth** [comment]
I'd appreciate support for this device as well. Thanks in advance.

**Comment by Idaho947** [comment]
Hello,

Any news about this intégration ?

**Comment by Mimiix** [comment]
Happy to reopen but without dev interest it's not proceeding.

@Smanar or @BabaIsYou anything for you?

**Comment by Smanar** [comment]
The problem is deconz is not made at all for this kind of device.
We can make a on/off but after .....

**Comment by BabaIsYou** [comment]
> but without dev interest it's not proceeding.

AS @Smanar mentionned, It's more a question of feasibility than interest in this case. 

We have already tried to integrate some dedicated devices (valve, IR transmitter, air quality sensor) and the discussions that followed are still ongoing or the integration is still not functional.

To report some specific information like portios_weight, weight_per_day, serving_size ... we need to finish integration of something like generic ZHAMeasurement ...

**Comment by Piksimou** [comment]
> The problem is deconz is not made at all for this kind of device. We can make a on/off, a "mode" setting , but after .....

I understand but on/off or "mode" setting, It's already good. the rest can be managed with scenarios on the home automation box.

**Comment by Smanar** [comment]
BTW this device don't have 0x0004 attribute on the basic cluster 0x0000 ? (the manufacture name).
It's grayed on your capture, it's normal, or it have failed when you have made the capture ?

**Comment by Piksimou** [comment]
I don't knwon. It's Iboue who made capture. I think i have failed when he make capture.

**Comment by Piksimou** [comment]
I try tomorrow and i tell you.

**Comment by Piksimou** [comment]
> No, I think it's from the device
> 
> > warn 2022-08-16 10:49:37: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
> 
> From Z2M. But the problem is deconz use this field to reconise the device ....
> 
> If you make a right clic on the node and "edit DDF" what is there in the field "manufacture name" ?

I try edit ddf and there are nothing in field "manufacure name".
 0x0004 attribute on the basic cluster 0x0000 ? (the manufacture name), he is gray also.

But in my network zigbee, device work fine in router.

**Comment by Smanar** [comment]
Yeah but the zigbee working mode have nothing to see with the API working mode.

From my memory deconz use the model ID AND the manufacture name to reconise device.

```
    if (ddf.manufacturerNames.last().isEmpty() || ddf.modelIds.isEmpty() || ddf.modelIds.front().isEmpty())
    {
        return false;
    }
```

So I don't think it's possible to do something for it.

**Comment by meetyourlaser** [comment]
Do I understand correctly: we will never see support for the Xiaomi Aqara Smart Pet Feeder C1 in DeCONZ? :'-(

**Comment by Smanar** [comment]
Not if the manufacture name is empty.
