### ISSUE TITLE
NAS-AB02B0-V3 (tuya alarm siren with temperature and humidity sensor) missing sensor data and broken alarm

### ISSUE THREAD

**Issue by UweDoe** [dresden-elektronik/deconz-rest-plugin#6596]
## Describe the bug

- Product name: NAS-AB02B0-V3 /20190910 (Tamkyo Tuya Zigbee Smart Siren Alarm mit Temperatur- und Feuchtigkeits Sensor)
- Manufacturer: _TZE200_d0yu2xgi
- Model identifier: TS0601

The device contains a siren, a temperature sensor and a humidity sensor. The pairing without batteries in the device but powered via an USB connection is reported as sucessfull by the phoscon app. Nevertheless the device does not stop blinking as signal for not finished pairing? With batteries blinking stops a while after pairing. The resulting rest api is the same. It contains elements for all three entities, but they are never updated.
Only the siren is seen by home assistant using the deconz integration. But it can not be triggered via home assistant to give a sound.

## Steps to reproduce the behavior

  The problem can be reproduced, after deleting the created smart light in phoscon app.
<img width="562" alt="Screenshot 2022-12-06 195322" src="https://user-images.githubusercontent.com/55703968/205997444-0c5548ad-e221-4b4a-b1f1-1cd35abfa9c6.png">

## Expected behavior

I would expect:
-  a temperature sensor, showing the device temperature
- a humidity sensor, showing the humidity
- a siren, with controllable parameters for the volume, duration and alarm sound

## Screenshots

![20221206_194013](https://user-images.githubusercontent.com/55703968/205996636-c618d439-1320-4394-bf70-df7def4fa39d.jpg)
device
![clusterinfo](https://user-images.githubusercontent.com/55703968/205899852-a2aa2af9-3b59-4a2e-a518-4e9005e7bbad.png)

Clusterinfo

![nodeinfo](https://user-images.githubusercontent.com/55703968/205899882-64eae4ab-b1cd-4e1c-a594-88548fe8b837.png)

Nodeinfo
<img width="502" alt="Home Assistant" src="https://user-images.githubusercontent.com/55703968/205900707-92987bc2-0421-4a5b-8880-bacbbbb2642e.png">

Apearance in Home Assistant

## Environment

 - Host system: (Raspberry Pi )
 - Running method: (Home Assistent deCONZ Add-on )
 - Firmware version: (26780700)
 - deCONZ version: (2.19.03)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? Mouse and Keypad

## deCONZ Logs
[](url)

[deconz_trace_add_siren.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10165743/deconz_trace_add_siren.txt)
[rest_api_before_pairing.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10165783/rest_api_before_pairing.txt)
[rest_api_after_pairing.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10165784/rest_api_after_pairing.txt)

## Additional context
link to the device: https://www.amazon.de/gp/product/B08F4ZT34D/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

**Comment by BabaIsYou** [comment]
Hello. Can you add screenshots for all listed clusters please ?

**Comment by UweDoe** [comment]
Is that, what you are asking for?
![2022-12-10-185513_1920x1080_scrot](https://user-images.githubusercontent.com/55703968/206870898-c610ed99-6f51-483f-a4d8-5226db005775.png)

**Comment by UweDoe** [comment]
Is that, what you are asking for?
![2022-12-10-185513_1920x1080_scrot](https://user-images.githubusercontent.com/55703968/206871018-1aa86c11-0a9b-4100-9cf9-e0e406c13552.png)

**Comment by BabaIsYou** [comment]
Yes but also for other clusters (just to be sure of what attributes they are supported) specially IAS Zone … For humidity and temp I’m already quite sure it use Tuya cluster because other Zigbee standard clusters are not present.

**Comment by UweDoe** [comment]
In this picture I have opened all different type of hardware devices. 
![2022-12-10-205546_1920x1080_scrot](https://user-images.githubusercontent.com/55703968/206873227-d0d08852-aaaa-48c9-8a77-1d9550dcb057.png)


Yes in the API I see the sensors, but temperature and humidity stays 'null' forever...

**Comment by UweDoe** [comment]
I have the impresseion, that for the phoscon app the pairing is finished, but it is not for the device, since it keeps flashing all the time...

**Comment by BabaIsYou** [comment]
Flashing means that pairing process didn’t finish properly. And looking around I found some discussions about this kind of device but don’t know about Deconz: [Here](https://github.com/Koenkk/zigbee2mqtt/issues/7051)

**Comment by UweDoe** [comment]
Is anybody willing to work on this problem?

**Comment by BabaIsYou** [comment]
It seems that this device need a specific sequence from Tuya gateway to finish pairing correctly. 

I don’t have stuff (and knowledge) to go further with it. May be someone else.
