### ISSUE TITLE
CoRui Tuya Door Window Sensor // TZ3000_au1rjicn // TS0203

### ISSUE THREAD

**Issue by Burn-In** [dresden-elektronik/deconz-rest-plugin#6598]
## Device

- Product name: CoRui Tuya Door Window Sensor
- Manufacturer: TZ3000_au1rjicn
- Model identifier: TS0203
- Device type : Sensor
  
## Screenshots

![Door_info](https://user-images.githubusercontent.com/33746005/206108867-0ccab1df-73ea-4a44-b781-b182c561600b.png)
![door_Basic](https://user-images.githubusercontent.com/33746005/206108875-0429ad0e-7552-45e2-8f88-a5f3bb79036e.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/33746005/206109350-8217c9ab-2842-4fff-8199-8c4703aa3ac5.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/33746005/207239617-f026edf3-ddc0-424f-9aa1-2c79f6951fab.png)

![image](https://user-images.githubusercontent.com/33746005/207239881-0b6fea0a-6b7b-4afe-bb63-fe6e7ff6eee7.png)

**Comment by Smanar** [comment]
You have a little typo to edit before testing the DDF

`"modelid": ["TS0203", "TS0203",, "TS0203"],`

**Comment by BabaIsYou** [comment]
My bad … sorry

**Comment by Burn-In** [comment]
I don't know how to use a DDF for the device. Because I'm using the HA-Deconz-Addon i have no external access to the deconz folder where the *.json is saved.

I edited the current DDF with the editor but without could adding bindings because i cannot control the windows in the in the Addons Deconz interface. So, drag-n-drop of bindings is not possible.

After using that edited one, the device will be found in Phoscon but without status updates.
![image](https://user-images.githubusercontent.com/33746005/207246663-b08e6083-0333-4a6c-a713-1b1ccd9849a8.png)

**Comment by BabaIsYou** [comment]
Good beginning ;-)

You also miss the battery parsing that tou can also ass using DDF editor.

BTW without bindings there is chance it won’t work either.

i’m not using HA, but I saw some threads in HA forum that could help to access devices json folder, like that [one](https://community.home-assistant.io/t/how-to-install-a-new-deconz-ddf-file/390455) 

Hope this help ;-)

**Comment by Smanar** [comment]
Yep, I think too you can do all the stuff with the editor, you have understant how it work.

Bonus:
Drag and drop on HA https://forum.phoscon.de/t/ddf-editor-how-to-drag-bindings/1351
To manage DDF you have too this link https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

Short story, the persistent file for DDF is hidden and is `/data/.local/share/dresden-elektronik/deCONZ/devices/`

**Comment by Burn-In** [comment]
> Bonus: Drag and drop on HA https://forum.phoscon.de/t/ddf-editor-how-to-drag-bindings/1351 

Sure i had read this already, but in the Deconz GUI, when started from inside the HA addon, the DDF Editor screen is not floating. It is always fullscreen over the device screen. So, the only existing method to add bindings by drag-and-drop is not possible.

![image](https://user-images.githubusercontent.com/33746005/207523794-86226aca-8494-4125-888e-f20be7d02388.png)

> To manage DDF you have too this link https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

It seems to be there no working simple method to enter an addon container from HA OS through the Terminal or Editor.

**Comment by Smanar** [comment]
> Undocking the “Cluster Info-Tab” into a floating panel, as shown, using the icons in the top right corner of the Tab works when using the noVNC view in home assistant using the deconz plugin/addon.

>It seems to be there no working simple method to enter an addon container from HA OS through the Terminal or Editor.

```
docker container ls
docker exec -it {id} /bin/bash
cd /data/.local/share/dresden-elektronik/deCONZ/devices/
```

**Comment by Burn-In** [comment]
Regarding “Cluster Info-Tab”, that's what I was thinking and looking for the whole time. Unfortunately, all windows don't have control icons on the right, running always fullscreen. Refer to the picture above.

`ssh root@{localIP} -p 22222` returns only `Connection refused`

**Comment by Smanar** [comment]
You have put the good local ip ?
Perhaps HA need an addon to use ssh ?

**Comment by Burn-In** [comment]
The IP is correct but I don't know if the port is so.

**Comment by Burn-In** [comment]
I also connected with the noVPN addon to Deconz GUI, it looks the same. It seems the title bars are not cut on the right but they don't have icons there at all.

**Comment by Smanar** [comment]
> Ssh to the hassio on Raspberry. You need to use a ADDON or something for this
> Either SSH & Web Terminal or some similar plugin, or just ssh root@{ip_address} -p 22222

Can try one of the 2 plugin ?

**Comment by Xyaren** [comment]
I now also am an owner of said device.
I can confirm the DDL from above works (after fixing the dublicate `,` in the modelids).

@Smanar do you need me to do any testing ?

**Comment by BabaIsYou** [comment]
Good News. Does your DDF also includes         {
          "name": "config/pending"
        },
        {
          "name": "config/enrolled",
          "public": false
        },

could you paste it and/or create a PR if already complete ?

**Comment by BabaIsYou** [comment]
> What do I need to check ?

If device is recognized with a name and not an hexdecimal denomination and that you can check that it returns information in HA as you expected them (open/close/battery ...) then it's fine.

**Comment by Checkdat** [comment]
Hi,
I have paired some TZ3000 (_TZ3000_n2egfsli) with the modelid SNZB-04 (change in DDF-file)

**Comment by Smanar** [comment]
But there is already something for the "_TZ3000_n2egfsli", here https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0203_door_sensor.json

**Comment by Checkdat** [comment]
Hi,I bought these from AliExpress:and just editedt the TZ3000 DDF with Model-ID part with SNZB-04Why is se Sonoff DDF the smarter choice?Cause the Manufacture is _TZ3000_n2egfsliAnd now it works very fine for me.Mit freundlichen Grüßen Marco BraunbeckAm 11.02.2025 um 18:10 schrieb Smanar ***@***.***>:﻿
Ha ?
So you mean the maufacture name is "_TZ3000_n2egfsli but the model id not "TS0203" but "SNZB-04" ?
So yes impossible to guess it, and honestly, i didn't think it was possible, it mean Tuya sell some hardware, so with the same manufacture name, to other brands, and thoses one just change the model id  ?
And if it's that, you are right, better to edit the \sonoff\snzb-04_open_close_sensor.json

**Comment by Smanar** [comment]
No problem, you are right, have found another topic with the same discover > https://github.com/JohanBendz/com.tuya.zigbee/issues/998
And have check the link, nothing about "Sonoff", or about "SNZB-04", I think they have a problem here ^^.

So do you want to make a PR to submit the device (explain the model id else others devs will react like me) or Want I make it ?

**Comment by Checkdat** [comment]
Please go for it !Think your Post will have a biger benefit for the Cumounity ;-).Im glad when i my telling has helped Mit freundlichen Grüßen Marco BraunbeckAm 11.02.2025 um 18:44 schrieb Smanar ***@***.***>:﻿
No problem, you are right, have found another topic with the same discover > JohanBendz/com.tuya.zigbee#998
And have check the link, nothing about "Sonoff", or about "SNZB-04", I think they have a problem here ^^.
So do you want to make a PR to submit the device (explain the model id else others devs will react like me) or Want I make it ?

**Comment by Smanar** [comment]
Thx, done > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8121
