### ISSUE TITLE
Preconfigure Gateways fo WebApp?

### ISSUE THREAD

**Issue by markuspf** [dresden-elektronik/deconz-rest-plugin#660]
I'd quite like to be able to pre-configure a gateway that the Phoscon WebApp accesses, and stop it from scanning for gateways.

I am working around the scanning issue by adding `#host/hostname` to the URL.

**Comment by manup** [comment]
> I am working around the scanning issue by adding #host/hostname to the URL.

Currently this is the only way. Once gateways are located scanning shouldn't start the next time the site is opened and cached results from localStorage will be used.
