### ISSUE TITLE
Aqara light sensor t1 (GZCGQ11LM)

### ISSUE THREAD

**Issue by Ragnar1985** [dresden-elektronik/deconz-rest-plugin#6600]
## Device

- Product name: Aqara light sensor t1
- Manufacturer: LUMI
- Model identifier: lumi.sen_ill.agl01
- Device type : 
  - Other: light sensor 

### Basic
![Screenshot_20221207_121143](https://user-images.githubusercontent.com/40439263/206164522-66dbf124-f106-427a-a3af-5724fc1e9758.jpg)

![basic](https://user-images.githubusercontent.com/40439263/206163671-04d60620-cdc5-499a-92f8-4312ee899f9e.jpg)
### Illuminance measurement
![Screenshot_20221207_122212](https://user-images.githubusercontent.com/40439263/206167936-5d7d5a9d-0416-4f95-94cc-813e185571bc.jpg)

### Identify
![Screenshot_20221207_120202_com realvnc viewer android_edit_4706415871477165](https://user-images.githubusercontent.com/40439263/206163141-102f5ca9-702f-4ad5-a941-1268f569bab3.jpg)
### Power Configuration
![Screenshot_20221207_122622](https://user-images.githubusercontent.com/40439263/206167501-4a3dd745-d062-4444-be74-55ab0dd1f307.jpg)

### Other clusters that are not mentioned above
![Screenshot_20221207_121340](https://user-images.githubusercontent.com/40439263/206164918-13b59b21-9c24-40f6-98d2-4b5eef653bda.jpg)

**Comment by Mimiix** [comment]
Hi,

There's missing a lot of information. Please add correct screenshots.

**Comment by Ragnar1985** [comment]
Is that enough information?

**Comment by SwoopX** [comment]
I'd expect the device to work if you extend your local `xiaomi_gzcgq01lm_light_sensor.json` with lumi manufacturer code and your model ID at the top of the file. You might wanna give that a go.

**Comment by Ragnar1985** [comment]
I'm a newbie, how do I do that?

**Comment by SwoopX** [comment]
Find the file mentioned above on your system, open it with an editor, find the respective lines and replace them with the below. Then save, restart deconz and reset and re-pair your light sensor.

```
  "manufacturername": ["$MF_XIAOMI", "$MF_LUMI", "$MF_LUMI"],
  "modelid": ["lumi.sen_ill.mgl01", "lumi.sen_ill.mgl01", "lumi.sen_ill.agl01"],
```

**Comment by Ragnar1985** [comment]
It works with this lines
"manufacturername": ["$MF_XIAOMI", "$MF_LUMI", "$MF_LUMI"],
  "modelid": ["lumi.sen_ill.mgl01", "lumi.sen_ill.mgl01", "lumi.sen_ill.agl01"],

**Comment by Mimiix** [comment]
Please wait until its merged
