### ISSUE TITLE
Tuya temperature senor

### ISSUE THREAD

**Issue by quikfast** [dresden-elektronik/deconz-rest-plugin#6614]
I have a Tuya temperature sensor for testing, however I'm not able to connect this to Home Assistant/Deconz.

## Describe the bug
device visible as manufacturer and model identifier as unknown, visible from deconz but not detected in Phoscon

![Deconz](https://user-images.githubusercontent.com/36920809/208107367-e3561237-03fa-46c9-b6f6-79e2cdcc761d.png)

## Environment
Home Assistant/Deconz

 Raspberry Pi 4 

I see that other users are also facing this issue, but these is really new for me and I do not know how to modify the DDF..

**Comment by Mimiix** [comment]
Hi,

this is not a bug, device is simply not supported.

Please file a device request if none is already in place. Make sure to carefully read the template to avoid issue closing. All information is in the template.

Closing this issue.

Kind regards,

**Comment by Mimiix** [comment]
Reading you already found  the request that was opened by another user.
