### ISSUE TITLE
Schneider Electric, W599001, Wiser Smoke Alarm – Battery

### ISSUE THREAD

**Issue by capristig** [dresden-elektronik/deconz-rest-plugin#6617]
## Device

- Product name: Smoke Alarm, Wiser, Battery, 10 years lifetime, white, IP20, CCT599001
- Manufacturer: Schneider Electric
- Model identifier: W599001
- Device type : Please remove all unrelated device types. 
  - Sensor
  - 
![CCT599001_IOP-def_WD_1500x1500](https://user-images.githubusercontent.com/120744944/208235412-c2eb5d3d-7e03-49bb-9482-e761b50abd3b.JPG)

### Basic
![basic](https://user-images.githubusercontent.com/120744944/208202312-dc1ab5d9-19ef-44e6-8af7-f092eea5ad53.PNG)

### Identify
![identify](https://user-images.githubusercontent.com/120744944/208202335-dee546d2-6d8c-458a-a6b9-81bf6414f0a3.PNG)

### Diagnostics
![diag1](https://user-images.githubusercontent.com/120744944/208202358-73f75554-278f-44ce-bbcb-179cab159cac.PNG)

![diag2](https://user-images.githubusercontent.com/120744944/208202363-6a4772d8-2128-4bd5-9ec3-60cfe7b09291.PNG)

### Other clusters that are not mentioned above

![IAS zone](https://user-images.githubusercontent.com/120744944/208202383-37a68c4c-1dfc-43f6-8d79-81a096f0d41c.PNG)
![poll](https://user-images.githubusercontent.com/120744944/208202402-4a273938-20f2-4c28-94d9-8d6767406400.PNG)
![power-config](https://user-images.githubusercontent.com/120744944/208202417-1c8619a9-bcfb-4d3e-bdfd-f2cf118a0540.PNG)

**Comment by BabaIsYou** [comment]
Hi. Have your screenshots been captured after clic on read button for each cluster ?

**Comment by capristig** [comment]
> 

Hi. I cannot remember 100%, but I migh have read only once. Does that influence the results?
