### ISSUE TITLE
Smart Plug - SilverCrest - _TZ3000_ynmowqk2 - TS011F

### ISSUE THREAD

**Issue by maillen** [dresden-elektronik/deconz-rest-plugin#6624]
## Device

- Product name: Smart Plug - SilverCrest - On/Off plug-in unit
- Manufacturer: _TZ3000_ynmowqk2
- Model identifier: TS011F
- Device type : 
  - Other: Energy meter with switch button

https://www.lidl.cz/p/silvercrest-zigbee-3-0-smart-home-inteligentni-zasuvka/p100355084
![image](https://user-images.githubusercontent.com/3392124/209231860-8aa75a52-3883-4018-8886-c6c57105b4a3.png)

## Screenshots

![image](https://user-images.githubusercontent.com/3392124/209231547-d91fb02e-5c95-4ddb-8edb-ae8b941efcc6.png)

### Basic

![image](https://user-images.githubusercontent.com/3392124/209233508-052436a4-c6a5-4707-bdde-e40b604ead0a.png)

### Identify

![image](https://user-images.githubusercontent.com/3392124/209233553-44ac606e-49e1-482e-bfa3-af62b63c5cd2.png)

### Groups

![image](https://user-images.githubusercontent.com/3392124/209232386-4bd8aa09-6521-43b8-9752-fd6d8e107cd1.png)

![image](https://user-images.githubusercontent.com/3392124/209232574-26d57cd5-0f72-4572-acd9-8bfe51098454.png)

### Scenes

![image](https://user-images.githubusercontent.com/3392124/209232739-45b06f4b-bb38-44cc-9aa8-723a90dc94b8.png)

![image](https://user-images.githubusercontent.com/3392124/209232785-09b03e98-55f5-48ac-9392-cc67924b70a9.png)

![image](https://user-images.githubusercontent.com/3392124/209232931-8a0b1dcb-a9ab-4468-9f6e-42c3bf16b419.png)

![image](https://user-images.githubusercontent.com/3392124/209232957-28b49352-f7ef-4eb9-a828-876a917833b1.png)

### On/Off

![image](https://user-images.githubusercontent.com/3392124/209233053-13418bbf-41ab-4cd5-b98b-db9cab8b747e.png)

![image](https://user-images.githubusercontent.com/3392124/209233121-09614b10-8688-4615-82e5-4d7d162003cd.png)

### Simple Metering

![image](https://user-images.githubusercontent.com/3392124/209233233-bedc35c1-36c6-4b4d-93d9-b30c5b2aee44.png)

### Electrical Measurement

![image](https://user-images.githubusercontent.com/3392124/209233304-d44e4b07-30fe-47b3-a2f0-c6c80ef66aa1.png)

**Comment by BabaIsYou** [comment]
Please van you update the screenshots after clic on read button for each cluster ?

Thx
