### ISSUE TITLE
Hue app with deCONZ

### ISSUE THREAD

**Issue by KodeCR** [dresden-elektronik/deconz-rest-plugin#663]
I'm trying to improve the compatibility of the deCONZ REST api with the Hue app (using the latest version on iOS). This is currently somewhat working but there are several submitted issues already, some quite old, so I'm trying to gather where we are at.

This is my attempt to list the currently known issues, and hopefully progress some of them:  
1. ~Xiaomi sensors seem to crash the Hue app~ done, #1046 
2. ~Searching for lights doesn't work #28 (I have implemented this now, will create a pull request)~ done, #664 
3. Scenes api is not implemented #29
4. Can't update deCONZ through the Hue app, it does show updates
5. Light api differences #30 (this might be sorted now, but issue is still open)
6. Philips Ambilight TVs might not work #440
7. Routines / capabilities api is missing  #584 (**partially in #1005**)
8. Rooms are implemented differently #596

~Any more?~
9. ~Update upnp and hue-bridge v2 description~, done #818 
10. https support, #769 
11. creating a group/room only works without lights, and then add them after creation

**Comment by Seaha4487** [comment]
Hey and how get i to work the part with the hue app?
The app finds my raspbee but wants me to create a room and this seems not to work cause i always get an error message if i try to save the room with my hue bulb in it
