### ISSUE TITLE
New clusters for Tuya LCD Multipurpose sensor (_TZ3000_qaaysllp)

### ISSUE THREAD

**Issue by rugarci** [dresden-elektronik/deconz-rest-plugin#6631]
Hi, 

This device was already partially supported but only for the lux measurements

![image](https://user-images.githubusercontent.com/26824640/209989372-f8ac20c0-2bdc-4775-8b38-1b2aa7b0803c.png)

After connecting the sensor to a Tuya gateway and coming back to deconz, new clusters for temperature and humidity appeared. However they are not displayed in web interface nor REST API

![image](https://user-images.githubusercontent.com/26824640/209989400-db95293e-fc6d-4fff-8a9f-9a19ee8b96e4.png)

## Device

- Product name: Tuya  Zigbee Temperature Humidity Sensor And Lux Detector With LCD Screen
- Manufacturer: _TZ3000_qaaysllp
- Model identifier:  TS0201
- Device type:
  - Sensor

### Device Temperature

![image](https://user-images.githubusercontent.com/26824640/209989529-50eda315-6523-4980-8998-1ea4554cd67e.png)

### Device Humidity

![image](https://user-images.githubusercontent.com/26824640/209989623-6a636ef6-2928-4c95-93a0-dccd01740847.png)

Thanks!

**Comment by Smanar** [comment]
Heeeee ???

I m searching the device _TZ3000_qaaysllp And I found nothing, in code and in DDF, how it can be reconised ......

**Comment by rugarci** [comment]
No custom DDF, just using latest deconzcommunity/deconz:beta docker image

The temperature and humidity are correctly updated and reflects the same values as in the LCD

**Comment by rugarci** [comment]
Other users were able to recognize it: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4790

**Comment by Smanar** [comment]
Ok so from this link it seem we need to use the tuya unlock sequence to use this device, ad this is not possible yet with deconz.
