### ISSUE TITLE
Hama Smart Radiator _TZE200_h4cgnbzg

### ISSUE THREAD

**Issue by Timo-Weike** [dresden-elektronik/deconz-rest-plugin#6635]
## Device

- Product name: Hama Smart Radiator Thermostat
- Manufacturer: _TZE200_h4cgnbzg
- Model identifier: TS0601
- Device type :
  - Thermostat

## Screenshots

![image](https://user-images.githubusercontent.com/25256020/210045327-7f963d94-e2c4-48d3-87fb-874b86e88015.png)

### Basic
![image](https://user-images.githubusercontent.com/25256020/210045405-c88df5bd-1ba5-48cf-a674-cbe98a456d9c.png)

### Groups
![image](https://user-images.githubusercontent.com/25256020/210045477-d67b1d41-ce1a-430e-9e8f-389c193a1d86.png)

### Scenes
![image](https://user-images.githubusercontent.com/25256020/210045516-fa416a5e-551b-412a-8716-f83de7bf3b79.png)

#### Tuya specific
![image](https://user-images.githubusercontent.com/25256020/210045678-47b150f2-a6d9-419c-94ad-c3b3ee7dcc45.png)

#### OTAU
![image](https://user-images.githubusercontent.com/25256020/210045740-c464684e-6901-4253-b36c-e660c0008d03.png)
![image](https://user-images.githubusercontent.com/25256020/210045755-f81a8aae-ee2d-47da-9f8d-43105d3ae27a.png)

#### Time
![image](https://user-images.githubusercontent.com/25256020/210045804-10009ed8-032d-4ea6-bc18-3242a14f8b67.png)

**Comment by Timo-Weike** [comment]
[Someone](https://github.com/zigpy/zha-device-handlers/issues/1901#issuecomment-1374482799) found a solution to get this working with ZHA. Maybe this is also the problem with deconz.

**Comment by CaptainFuture78** [comment]
Hello,
I have the same problem with the HAMA Radiator Thermostat.
If there is a soulution for this issue, does anybody know where I can find it?
More information on this issue would be very helpful.

**Comment by ralfhille** [comment]
Hello,
I have the same problem with the HAMA Radiator Thermostat.

Have unfortunately seen too late that there is a problem with the Hama radiator thermostats in version 3. My purchase decision was based on some articles with Home Assistant and deconz that the devices can be recognized and controlled.

Is then planned on the part of Dresden Elektonik here still offer support for the devices?

More information on this issue would be very helpful.

**Comment by Mimiix** [comment]
More often then not, its the community adding support for devices 😅. @Smanar are you able to help out ?

**Comment by Smanar** [comment]
There is a new Pr for this devices https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6859
