### ISSUE TITLE
Hue Dimmer Switch does not trigger event

### ISSUE THREAD

**Issue by tnt1735** [dresden-elektronik/deconz-rest-plugin#6636]
## Describe the bug
After a while the Hue Dimmer Switch appears still in the phoscon app but events do not trigger actions like switch light on/off ets. Somtimes the key-bindig are still there, somtimes the are disrupted o gone.

## Steps to reproduce the behavior
Add  Hue Dimmer Switch key-binding once again it will work but after a while they do not work any more

## Expected behavior
The key-binding should still work

## Screenshots
![grafik](https://user-images.githubusercontent.com/60882236/210082167-0e8be1f9-70f4-4571-af54-a694ddf14542.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - 
 - Firmware version: 26720700
 - deCONZ version: 2.19.03 / 19.9.2022
 - Device: ConBee II
 - Do you use an USB extension cable: yes, but only a short one
 - Is there any other USB or serial devices connected to the host system? YES
     - If so: Keyboard

**Comment by Mimiix** [comment]
Hi,

This seems to be an issue with Phoscon and not deCONZ. Please report Phoscon bugs on the forums: https://forum.phoscon.de/c/phoscon/bug-reports/20

Kind regards,
