### ISSUE TITLE
Aqara smart plug (EU) not reporting kWh and W through deCONZ

### ISSUE THREAD

**Issue by gvssr** [dresden-elektronik/deconz-rest-plugin#6637]
## Describe the bug

Aqara smart plug (EU) version with power metering is not reporting kWh and W sensors, even though you can see the stats being updated in deCONZ REST API. This issue is forwarded from https://github.com/home-assistant/core/issues/84867 by request due to https://github.com/home-assistant/core/issues/84867#issuecomment-1368066490

## Steps to reproduce the behavior

1. Add Aqara smart plug in deCONZ
2. Read all required attributes
3. Add to Home Assistant through official integration
4. Plug in device that draws power

## Expected behavior

Current W draw is reported, like it used to before the introduction of DDF
## Screenshots

![5B3E3390-78F2-4904-8F14-0E4CFBD50103](https://user-images.githubusercontent.com/61377476/210108315-1a12b7b2-0fac-4938-adea-1da436cfb2b6.jpeg)
![2FF4E3A0-6859-4F53-A777-E8E0BE274A8B](https://user-images.githubusercontent.com/61377476/210108318-82ad8ffd-c609-4b6a-b68e-ec43da4fcba5.jpeg)

## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26720700
 - deCONZ version: 2.19.03 / 9/19/2022
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

**Comment by Mimiix** [comment]
What's the manufacturer I'd and model id? I believe this is a duplicate.

**Comment by gvssr** [comment]
> What's the manufacturer I'd and model id? I believe this is a duplicate.

![55627163-818C-4C30-8FC1-A9583A762776](https://user-images.githubusercontent.com/61377476/210120050-26df11dd-003c-4d97-8215-c6f98baa5c76.jpeg)

**Comment by Mimiix** [comment]
Seems that this should be fixed before by a pr by @SwoopX .

**Comment by cappadanna** [comment]
Same issue here with same plug and firmware

**Comment by gvssr** [comment]
@ondrackajan I've noticed for me while trying to add / remove / add the plug there's a huge delay in reported Wattage in deCONZ API vs. what shows up in the Home Assistant frontend.

Through DDF: 5-10 minute delay before changed values show up
Without DDF: Updated every 1-5 seconds

**Comment by BabaIsYou** [comment]
> Through DDF: 5-10 minute delay before changed values show up

With  `"refresh.interval": 300` in DDF it seems normal tome to have a refresh at 5mn

**Comment by Rob787** [comment]
Same issue here with 0w and 0 kwH readings

**Comment by Mimiix** [comment]
Did all of you check https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-smart-plugs-not-working-correctly

**Comment by Rob787** [comment]
@Mimiix Yep, I'm on latest version already and resetted multiple times:

![image](https://user-images.githubusercontent.com/82140237/215127708-a0e201ce-c830-48f0-aadf-cc21c152b476.png)

**Comment by Rob787** [comment]
I did notice following behaviour:

Initially HASS only get the Temp and Power (wattage) entity. Then the Power seems to get updated. After a while, and a HASS restart, the Consumption entity also returns, and then Power and Consumption remain on 0.

**Comment by Mimiix** [comment]
> @Mimiix Yep, I'm on latest version already and resetted multiple times:
> 
> ![image](https://user-images.githubusercontent.com/82140237/215127708-a0e201ce-c830-48f0-aadf-cc21c152b476.png)

Also the conbee / raspbee ?

**Comment by Rob787** [comment]
> > @Mimiix Yep, I'm on latest version already and resetted multiple times:
> > ![image](https://user-images.githubusercontent.com/82140237/215127708-a0e201ce-c830-48f0-aadf-cc21c152b476.png)
> 
> Also the conbee / raspbee ?

Yep Conbee II:

![image](https://user-images.githubusercontent.com/82140237/215131871-2e9fba9a-d9bd-4224-bb25-9d559aea860a.png)

**Comment by Mimiix** [comment]
> > > @Mimiix Yep, I'm on latest version already and resetted multiple times:
> > > ![image](https://user-images.githubusercontent.com/82140237/215127708-a0e201ce-c830-48f0-aadf-cc21c152b476.png)
> > 
> > 
> > Also the conbee / raspbee ?
> 
> Yep Conbee II:
> 
> ![image](https://user-images.githubusercontent.com/82140237/215131871-2e9fba9a-d9bd-4224-bb25-9d559aea860a.png)

In that case I'm out of options 😅

**Comment by Smanar** [comment]
Can you check using the flag "DDF" in logs if the device use the DDF or not for power ?

Some device use native cluster/attribute, some others use the Xiaomi one.

On the actual DDF for "lumi.plug.maeu01" , the DDF chek for the presence of cluster 0x1f and 0x15 to be used
It use the Xiaomi cluster for current, voltage, and cluster 0x000C /attribute 0x0055 (from cluister 0x1F) for power and consumption (with the same value).

So first what is working ?

**Comment by gvssr** [comment]
This issue actually pushed me over to migrating to Zigbee2Mqtt, solving my problem. I'll keep this issue open for others, but am unsubscribing as it's no longer applicable for me.
