### ISSUE TITLE
TMZ-02 mini a.k.a Tmz02L-16A-W ( Manu: _TZ3000_v7sopte0, Model: TS0011 )

### ISSUE THREAD

**Issue by abrakhim** [dresden-elektronik/deconz-rest-plugin#6644]
I searched previous Device Request and found some similar ones but with different Manufacturer-Id, starting _TZ3000_ but different Suffix. 
![image](https://user-images.githubusercontent.com/40267667/210660300-8367e434-bd2c-4a8c-a35d-673b080fd031.png)

## Device

- Product name: TMZ-02 Mini / Tmz02L-16A-W
- Manufacturer: _TZ3000_v7sopte0
- Model identifier: TS0011
- Device type : Please remove all unrelated device types. 
  - Switch

## Screenshots

Node Info panel
![image](https://user-images.githubusercontent.com/40267667/210655416-061f8b91-8c39-4e94-a2eb-bf5e4a5ee1a8.png)

Note that it states 'Battery' as Power Source but it is connected to Mains! 
### Basic
![image](https://user-images.githubusercontent.com/40267667/210654687-0611e4d9-3f74-492e-8eec-af9861a51c40.png)
### Identify
![image](https://user-images.githubusercontent.com/40267667/210655756-f598f522-51ea-4679-ab46-920f14d1a47a.png)
### Groups
![image](https://user-images.githubusercontent.com/40267667/210655891-6671237d-cd6f-4325-a489-dd3b846179df.png)
### Scenes
![image](https://user-images.githubusercontent.com/40267667/210655987-154d24b0-cc74-4005-9221-266bb7a1e75d.png)
### On/Off
![image](https://user-images.githubusercontent.com/40267667/210656159-33a125a6-d8e2-4f07-9cb8-c2b7168b77cd.png)

**Comment by BabaIsYou** [comment]
I don't really know if state/on is based on Tuya cluster on not then I suggest to try this DDF that could be adapted if On/Off state doesn't respond.

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_v7sopte0",
  "modelid": "TS0011",
  "product": "TMZ-02 Mini",
  "sleeper": false,
  "status": "Silver",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 300,
          "read": {
            "fn": "tuya"
          },
          "write": {
            "dpid": 1,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 1,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

**Comment by abrakhim** [comment]
@BabaIsYou Thanks for your reply, i edited the ddl, the light shows up in phoscon, but i can't toggle it, nor does it show the current state. Any other ideas?

**Comment by BabaIsYou** [comment]
It will be easier than I initialy thought because there is already a DDF file for this kind of device (#6764 )
Then could you try this one ? 
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_txpirhfq","_TZ3000_qmi1cfuq", "_TZ3000_ji4araar","_TZ3000_v7sopte0"],
  "modelid": ["TS0011", "TS0011", "TS0011", "TS0011"],
  "product": "1 gang switch module ",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "refresh.interval": 86400,
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by abrakhim** [comment]
Hahaha, i just read through https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/#ddf-file-content
and figured it out myself (without the sw-version-script... ), come back to report here and find your reply...

So, dunno about your attr/swversion-Part, i went with state/on -> looks like this and works:
`{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_v7sopte0",
  "modelid": "TS0011",
  "vendor": "Tuya Industries",
  "product": "TS0011",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/ts0011.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 1,
            "eval": "Item.val = Attr.val",
            "fn": "zcl"
          }
        }
      ]
    }
  ]
}`

Thanks!

**Comment by BabaIsYou** [comment]
Fine !
Information you added to `state/on` are useless because they are already included in the generic definition of that attribute : https://github.com/dresden-elektronik/deconz-rest-plugin/blob/6c7ce32e403641e91e5746a18734651d73868881/devices/generic/items/state_on_item.json . That's why they are not in mine.

For indentation, I pass my json thru an online free json validator that do the trick (prettyu sure you can find one by yourself).

**Comment by abrakhim** [comment]
Thanks again, i feel a bit more enlightened now, escpecially in my kitchen, when the ceiling lights turn on as if by magic ;-)
Will format my code snippet properly and incorporate your suggested changes.

**Comment by BabaIsYou** [comment]
> Indentation was just the markdown, i used the button <> instead of writing three ticks. That removed the correct indentation like this:

Just do a "return" after the ''' won't do the trick ?
