### ISSUE TITLE
Tuya ZigBee Smart Wireless Control Gas Water Valve

### ISSUE THREAD

**Issue by dsimop** [dresden-elektronik/deconz-rest-plugin#6646]
## Device

- Product name: Tuya ZigBee Smart Wireless Control Gas Water Valve
- Manufacturer: _TZ3000_iedbgyxt
- Model identifier: TS0001
- Device type : Please remove all unrelated device types. 
  - Other: Water / Gas Valve

Link: www.aliexpress.com/item/1005002633228786.html

## Screenshots

  - <img width="233" alt="image" src="https://user-images.githubusercontent.com/8091329/210773444-5a96786d-3561-4164-9b92-fe89fe467254.png">
  - <img width="349" alt="image" src="https://user-images.githubusercontent.com/8091329/210773575-f1e9f47f-27e1-4919-90d6-c35fe091fc1d.png">

### Basic
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8091329/210773991-36dcb196-2c0b-4f6f-8ae2-d5f27489e88f.png">

### Identify
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8091329/210774252-495e824b-3b6e-473d-ad23-251a5bfc5645.png">

### Groups
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8091329/210774408-e4375139-6035-499a-884b-b0e5eb86921a.png">

### Scenes
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8091329/210774520-37100492-9708-45a7-b046-645fd4150111.png">

### On/Off
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8091329/210774609-805778b7-3bb8-4773-9674-a2aba0bbd128.png">

**Comment by dsimop** [comment]
After several minutes, the blue blinking light stops and the device gets unavailable.
If you press manually the button on the device in order to turn the valve on/off, the device gets re-paired - but after several minutes it gets disconnected as well.

**Comment by dsimop** [comment]
Request to be reopened.

**Comment by Mimiix** [comment]
Sure :)

@smanar this one can be added ?

**Comment by Smanar** [comment]
Sure, can try this DDF to test ?

```
{
	"schema": "devcap1.schema.json",
	"manufacturername": ["_TZ3000_o4cjetlm", "_TZ3000_iedbgyxt", "_TYZB01_4tlksk8a"],
	"modelid": ["TS0001", "TS0001", "TS0001"],
	"product": "Tuya Smart water/gas valve",
	"sleeper": false,
	"status": "Gold",
	"subdevices": [{
		"type": "$TYPE_ON_OFF_OUTPUT",
		"restapi": "/lights",
		"uuid": [
			"$address.ext",
			"0x01"
		],
		"items": [{
				"name": "attr/id"
			},
			{
				"name": "attr/lastannounced"
			},
			{
				"name": "attr/lastseen"
			},
			{
				"name": "attr/manufacturername"
			},
			{
				"name": "attr/modelid"
			},
			{
				"name": "attr/name"
			},
			{
				"name": "attr/swversion",
				"parse": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0x0001",
					"script": "tuya_swversion.js"
				},
				"read": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0x0001"
				}
			},
			{
				"name": "attr/type"
			},
			{
				"name": "attr/uniqueid"
			},
			{
				"name": "state/on",
                                "refresh.interval": 500
			},
			{
				"name": "state/reachable"
			},
			{
				"name": "config/interfacemode",
				"refresh.interval": 86400,
				"read": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": [
						"0x0004",
						"0x0000",
						"0x0001",
						"0x0005",
						"0x0007",
						"0xfffe"
					]
				},
				"parse": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0xfffe",
					"eval": "Item.val = Attr.val"
				},
				"public": false,
				"default": 0
			}
		]
	}]
}
```

Perhaps this device need binding but I m not sure.

**Comment by dsimop** [comment]
Could you please indicate a source of instructions on how to manually upload a DDF (Could not find concrete guidelines so far)? I am currently using the deCONZ add-on on Home Assistant (HassIO).
* Maybe @Mimiix you could re-direct me to the respective resources?

**Comment by Mimiix** [comment]
@Smanar should be able to. Nevertheless, roaming around this GitHub and seeing other requests might give you some guidance too.

**Comment by Smanar** [comment]
On home assitant, the short answer, you need to put the file in `/data/.local/share/dresden-elektronik/deCONZ/devices/` 
The long answer https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839/20

**Comment by dsimop** [comment]
Thank you both.
