### ISSUE TITLE
[Device Support Request] Aqara QBKG38LM - Smart Switch without neutral

### ISSUE THREAD

**Issue by xADDRx** [dresden-elektronik/deconz-rest-plugin#6657]
Hello there,
I recently ordered from AliExpress  AQARA QBKG38LM . Smart switch without neutral wire.

When attempting to join them using Phoscon, the "Add Switch" function does not detect them under Phoscon.

Using Deconz view, the following node and cluster info are available:

![grafik](https://user-images.githubusercontent.com/64784940/211289483-01cfbc1f-31f2-4a9f-8a51-13771545a327.png)

## Device

- Product name: QBKG38LM 
- Manufacturer: LUMI.
- Model identifier: lumi.switch.b1lc04.
- Device type :  Switch

### Basic
![grafik](https://user-images.githubusercontent.com/64784940/211288341-039c304c-10d7-4352-8087-36e284985ec2.png)

### Identify
![grafik](https://user-images.githubusercontent.com/64784940/211288427-61c02594-8021-4696-a4b0-34df1bccef12.png)

### Groups
![grafik](https://user-images.githubusercontent.com/64784940/211288553-d5c9ecbb-7c00-49c1-b029-8c2e8fe8237b.png)
![grafik](https://user-images.githubusercontent.com/64784940/211288635-00e01179-bc34-4635-b4e2-b32205d6e746.png)

### Scenes
![grafik](https://user-images.githubusercontent.com/64784940/211288680-fd289e2e-ee34-4fe2-8e2b-45720b909504.png)
![grafik](https://user-images.githubusercontent.com/64784940/211288747-a534abc0-2d0d-43c8-98d3-cc8e9bed4ef5.png)
![grafik](https://user-images.githubusercontent.com/64784940/211288816-d5237455-2067-4272-bec0-81fec5905d13.png)
![grafik](https://user-images.githubusercontent.com/64784940/211288853-1219f206-ca8d-41e2-98ac-8c1609338ebf.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/64784940/211288982-04b2f0c7-7e00-474d-a116-f204194f96f2.png)
![grafik](https://user-images.githubusercontent.com/64784940/211289025-3993a860-f3bc-4f34-a33b-3bb216397a2e.png)

**Comment by xADDRx** [comment]
Hi

Now the switches are displayed as lights, so I can already control the switches. I'll add your example when I get a chance to display it correctly as a switch.

Thank you for your help!

**Comment by Smanar** [comment]
It's more complicated ^^
Wired switch are light not switch, you send order to them like for light, you can't send information to a battery switch. The difference is an zigbee side too, for group use for exemple.

In reality your device can have both mode, if you use for exemple the "decoupled" mode. But not usefull for me.

**Comment by xADDRx** [comment]
Yes, it's also the first time that I'm playing around in the DDF :).

So can I leave it like this or what you mean?

**Comment by Smanar** [comment]
>So can I leave it like this or what you mean?

As you want, it's for you, not for me ^^.
If you like it as it, you can too make a PR for others users.
