### ISSUE TITLE
Sending turn_off + transition via Home Assistant does not turn off light.

### ISSUE THREAD

**Issue by vandalon** [dresden-elektronik/deconz-rest-plugin#666]
When sending a `"entity_id": "light.keuken_3","transition":"10"` in home assistant the light dims to 1% but does not turn off. This does work on hue bridge connected lights.

**Comment by Kane610** [comment]
This is probably an issue with the component and not with deconz. I'll have a look in a day or two

**Comment by vandalon** [comment]
What component exactly? Can I check something for you?

**Comment by Kane610** [comment]
Well... The DeConz component :). You have already stated that transition doesn't work with this specific implementation

**Comment by vandalon** [comment]
Ah within Home Assistant you mean :)

**Comment by Kane610** [comment]
Yes

**Comment by jamesking420** [comment]
I've just come to report this bug too! Coincidence!

**Comment by Kane610** [comment]
A really weird coincidence that a third party submitted a fix for it just now. https://github.com/home-assistant/home-assistant/pull/15222

**Comment by lbschenkel** [comment]
Since this was a bug in HASS that got fixed, I suppose this should be closed?

**Comment by Kane610** [comment]
Yes it can. @vandalon can you close this issue?

**Comment by vandalon** [comment]
Fixed in home assistant https://github.com/home-assistant/home-assistant/pull/15222

**Comment by vandalon** [comment]
It was an evil issue anyway 😊

**Comment by Kane610** [comment]
Rofl!

**Comment by jamesking420** [comment]
This is still broken in 0.73

**Comment by Kane610** [comment]
That is true @jamesking420 it will come with the 74 release in two weeks
