### ISSUE TITLE
Ikea STOFTMOLN

### ISSUE THREAD

**Issue by ThomasBDomo** [dresden-elektronik/deconz-rest-plugin#6669]
## Device

- Product name: IKEA STOFTMOLN
- Manufacturer: IKEA
- Model identifier: STOFTMOLN ceiling/wall lamp WW37
- Device type : Light

## Screenshots

{
  "etag": "d83c7fd0c270e6b482447ab3c649ac8b",
  "hascolor": false,
  "lastannounced": "2023-01-12T10:34:09Z",
  "lastseen": "2023-01-12T10:33Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "STOFTMOLN ceiling/wall lamp WW37",
  "name": "Lamp slaapkamer",
  "state": {
    "alert": "none",
    "bri": 0,
    "on": false,
    "reachable": false
  },
  "swversion": "1.0.006",
  "type": "Dimmable light",
  "uniqueid": "####",
  "id": "23",
  "deviceclass": "lights"
}

**Comment by BabaIsYou** [comment]
Hi,

Can you please complete this request using the template ?

Thx

**Comment by wvuyk** [comment]
? And does this not work? Seems fnctional here. Nothing needed
