### ISSUE TITLE
Sonoff Zbminil2 extreme zigbee

### ISSUE THREAD

**Issue by MiAutomations** [dresden-elektronik/deconz-rest-plugin#6671]
- Product name: sonoff zbminil2 extreme zigbee
- Manufacturer: Sonoff
- Model identifier: ZBMINIL2
- Device type : Switch

[https://itead.cc/product/sonoff-zbminil2-extreme-zigbee-smart-switch-no-neutral-required/](url)

![image](https://user-images.githubusercontent.com/47602733/212362468-c1a9cdf2-ba01-49e4-8e90-693ef9ad74ba.png)
![image](https://user-images.githubusercontent.com/47602733/212362495-d40d2459-399f-42d5-a028-aee41a7e1e0c.png)
![image](https://user-images.githubusercontent.com/47602733/212362544-f012622e-b452-4c7c-89a1-d0741badd093.png)
![image](https://user-images.githubusercontent.com/47602733/212362577-89b78093-b0f6-4682-95d1-08af70f77fe0.png)
![image](https://user-images.githubusercontent.com/47602733/212362600-d00dbf91-9714-49fa-8bf6-d979b658f466.png)
![image](https://user-images.githubusercontent.com/47602733/212362631-98fd2154-6983-443f-a102-6815949b33b5.png)
![image](https://user-images.githubusercontent.com/47602733/212362648-732250c8-ebd0-4d94-9a3c-14c7edc6001c.png)

Can you please add this new device to be supported ? 

Thank you and best regards

**Comment by Mimiix** [comment]
Hi,
Please add all requestes screenshots.

K

**Comment by MiAutomations** [comment]
> l requestes screens

Sorry please the node Info also as requested 

![image](https://user-images.githubusercontent.com/47602733/212342140-5322556e-ecc2-4539-b3ff-090d54789374.png)

**Comment by Mimiix** [comment]
We need screenshots for every cluster.

**Comment by MiAutomations** [comment]
> We need screenshots for every cluster.

Ok

![image](https://user-images.githubusercontent.com/47602733/212360975-5f838b13-7d7f-4eae-93e5-c4945b2c1b9c.png)
![image](https://user-images.githubusercontent.com/47602733/212361008-e4207c85-2963-4a4b-92e7-1375c6f21c21.png)
![image](https://user-images.githubusercontent.com/47602733/212361031-e6820fdf-32e7-4756-ac52-d778bfe07602.png)
![image](https://user-images.githubusercontent.com/47602733/212361067-e6ec3b6e-3915-4ca2-a66b-726ac0e97d4c.png)
![image](https://user-images.githubusercontent.com/47602733/212361088-0327d569-e20e-43cd-86ff-ad5b638540b1.png)
![image](https://user-images.githubusercontent.com/47602733/212361108-41732a41-69b6-4066-bdab-9bc5d3a7e869.png)
![image](https://user-images.githubusercontent.com/47602733/212361126-a695cc27-2b7b-4732-8920-9f05db3400f1.png)


Please let me know if you need any further info 

Thank you

**Comment by Mimiix** [comment]
Please put them in the Original Post as we ask in the template.

Also make sure all attributes are read and have populated values.

**Comment by MiAutomations** [comment]
> Please put them in the Original Post as we ask in the template.
> 
> Also make sure all attributes are read and have populated values.

Done 

Thank you

**Comment by Mimiix** [comment]
Thanks!

**Comment by Smanar** [comment]
Hello, What this device have more than the model "ZBMINI-L" ?

Here it's the same DDF but adapted for your device

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "ZBMINIL2",
  "product": "ZBMINIL2",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    }
  ]
}
```

**Comment by MiAutomations** [comment]
> his device have more than the model "ZBMINI-L" ?

Sorry I don't know the diferences

Regarding the DDF 

Where I can use it? 

Thank you

**Comment by Smanar** [comment]
Depend of your OS.
If you have HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839 (the site is out ATM)
Else https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet (to resume you just need to create a file called what_you_want.json with this contain in a "devices" folder.

**Comment by ge8020** [comment]
also would like to have the zbmini-l2 working

**Comment by Smanar** [comment]
Can test the DDF and give return.

**Comment by tbrausch** [comment]
I copied the ddf for the Sonoff ZMMINIL and modified the model number to ZMMINIL2 and it worked perfectly.

**Comment by Smanar** [comment]
@tbrausch ok, thx, so have made a change to uspport both device with the same DDF https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6726

**Comment by Tjchispas** [comment]
![2023-04-01_12h05_37](https://user-images.githubusercontent.com/21312679/229279776-2e973621-dba0-43b2-85ea-8bc4774215e0.png)
this works for me

**Comment by djgreko** [comment]
I have been waiting for the new release but this device is not supported yet. Moreover, it is not easy for an average user to be able to load DDF for unsupported devices. Are you saying there is any hope? I have had these devices for months and cannot use them.
Thank you

**Comment by Smanar** [comment]
On the PR was marked for v2.22.0-beta.
But yes, you can create yourself the DDF, it's just a text file https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6726
