### ISSUE TITLE
Hama _TZE200_h4cgnbzg Target value is not transmitted to TRV

### ISSUE THREAD

**Issue by TobiSchroedel** [dresden-elektronik/deconz-rest-plugin#6680]
good day everybody,
I'm using Hama _TZE200_h4cgnbzg. The connection via Zigbee worked without any problems. The values ​​that I set manually on the TRV are sent to the ZHA. Also the battery status.
But it is not possible to set the target temperatures from Home Assistant.
I tested the entities, better thermostat and the original thermostat dashboard from HM. The value that was set manually on the TRV always remains.

Anyone an idea?

{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0004",
        "0x0005",
        "0x0201",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_h4cgnbzg",
  "model": "TS0601",
  "class": "zhaquirks.tuya.ts0601_trv_sas.Thermostat_TZE200_c88teujp"
}

**Comment by Mimiix** [comment]
Hi,

This seems not to be deCONZ so this is not the correct repository.

Closing this issue.
