### ISSUE TITLE
Moes Smart Switch Module 3 Gang MS-104CZ / _TZE3000_pfc7i3kt

### ISSUE THREAD

**Issue by BoBiene** [dresden-elektronik/deconz-rest-plugin#6682]
## Device

- Product name: Moes Smart Switch Module 3 Gang MS-104CZ
- Manufacturer: _TZE3000_pfc7i3kt
- Model identifier: TS0003
- Device type : 
  - Switch

## Screenshots
![image](https://user-images.githubusercontent.com/23037659/213690964-09de6b69-5e8b-4474-8f92-313de8eda9be.png)
![image](https://user-images.githubusercontent.com/23037659/213690986-88b6216c-f121-4f62-9feb-356539793e9c.png)

### Basic
![image](https://user-images.githubusercontent.com/23037659/213692153-8ecd6899-08e6-41ec-8428-f6a8955106b6.png)

### Identify
![image](https://user-images.githubusercontent.com/23037659/213692190-adfc7407-94ca-46f9-8411-b840d983d0dc.png)

### Groups
![image](https://user-images.githubusercontent.com/23037659/213692367-cd0d37dd-f211-460d-938a-43a260aa5f1f.png)

### Scenes
![image](https://user-images.githubusercontent.com/23037659/213692446-829641ba-a22d-46a4-ae00-89a207d69bd9.png)

### On/Off
![image](https://user-images.githubusercontent.com/23037659/213692533-11663144-c70c-4da9-b6c6-cdad6b0d9169.png)

### Simple Metering
![image](https://user-images.githubusercontent.com/23037659/213692606-47456612-487a-412a-843d-986d57f384bd.png)

### Electrical Measurement
![image](https://user-images.githubusercontent.com/23037659/213692689-44a4c00c-88b9-4e7e-ad76-83137417fd49.png)

**Comment by Smanar** [comment]
Just for information, this device need too the "tuya unlock sequence".

**Comment by BoBiene** [comment]
Is there anything i can do?

**Comment by Smanar** [comment]
If someone can test the new DDF with the tuya unlock sequence ? 

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE3000_pfc7i3kt",
  "modelid": "TS0003",
  "product": "Wired Switch 3 gangs (locked)",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "config/interfacemode",
          "refresh.interval": 86400,
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": [
              "0x0004",
              "0x0000",
              "0x0001",
              "0x0005",
              "0x0007",
              "0xfffe"
            ]
          },
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0xfffe",
            "eval": "Item.val = Attr.val"
          },
          "public": false,
          "default": 0
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x03"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    }
  ]
}

**Comment by BoBiene** [comment]
@Smanar thank you. I can test this, do you have a link to the docs where i can read how to use the ddf?

**Comment by Smanar** [comment]
Depend of OS

On normal OS https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
On HA https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

To resume you just need to create a test file in a "devices" folder with this contain, call the file whatyouwant.json and restart deconz.

**Comment by BoBiene** [comment]
Hi, 

i had a typo in my initial request. It should be ``_TZ3000_pfc7i3kt`` instead of ``_TZE3000_pfc7i3kt`` (removing the **``E``**).
After changing the DDF it worked for all three output - thank you very much :)

**Comment by Smanar** [comment]
Thx, have created the DDF here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6902

Have modified the unlock part.

**Comment by sciorty** [comment]
Since i cannot update the HA add-on with a beta, i manually created the ddf as the one introduced with the pull https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6902.
I loaded the ddf on the device and did both an hot reload and complete system reboot, but my problem reported on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6886 is still there.
Am I missing something?

**Comment by Mimiix** [comment]
@sciorty Perhaps a re-pair?

**Comment by sciorty** [comment]
@Mimiix Will try too repair once i get home.
@Smanar i put it on `/usr/share/hassio/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices` . If i right click on the node->edit DDF, this is what appears, so it should have been loaded
![image](https://user-images.githubusercontent.com/6460914/233407244-8cacf756-ac09-4bf3-b15d-2af5696d81b9.png)

this is instead the DDF control
![image](https://user-images.githubusercontent.com/6460914/233407539-0a0a264c-a703-4ef3-9d05-cd74882498b9.png)

**Comment by Smanar** [comment]
On the DDF preview you can see this part ?

```
        {
          "name": "config/interfacemode",
          "refresh.interval": 86400,
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": [
              "0x0004",
              "0x0000",
              "0x0001",
              "0x0005",
              "0x0007",
              "0xfffe"
            ]
          },
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0xfffe",
            "eval": "Item.val = Attr.val"
          },
          "public": false,
          "default": 0
        }
```

If yes, the re-inclusion can help, else the tuya unlock sequence is done every 24h

**Comment by sciorty** [comment]
No, i copied the file inside the directory as it is, then loaded it. But once I show the DDF, it lacks of the rows you are mentioning, Why?
<img width="340" alt="Schermata 2023-04-20 alle 18 58 41" src="https://user-images.githubusercontent.com/6460914/233436810-ac85eb04-8dc1-4567-9d7c-a360e33faea7.png">

Re-pairing did not help.

**Comment by Smanar** [comment]
On the HA deconz plugin , need to put the file in `/data/.local/share/dresden-elektronik/deCONZ/devices/`

https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by sciorty** [comment]
uhmm i don't have that path, should it start from my raspberry root? 
`/usr/share/hassio/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices` starts from the raspberry root and is the path where i already put another DDF for another device that was not working and it did the trick (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6517#issuecomment-1446293557)

**Comment by Smanar** [comment]
It's an hidden folder, just check if it exist.

**Comment by sciorty** [comment]
It does not exist, I only have these:
<img width="406" alt="Schermata 2023-04-21 alle 19 34 09" src="https://user-images.githubusercontent.com/6460914/233700822-70757f1a-1752-4b89-a2e8-edf94d94ba66.png">
<img width="432" alt="Schermata 2023-04-21 alle 19 35 07" src="https://user-images.githubusercontent.com/6460914/233700825-634e715f-4f42-4c99-bd70-82edbea5f0c4.png">
<img width="566" alt="Schermata 2023-04-21 alle 19 41 58" src="https://user-images.githubusercontent.com/6460914/233700830-48e27a76-94c0-4652-97eb-435b9cbf1ce6.png">

**Comment by Smanar** [comment]
But you are not on HA ?
They are using docker, it's not as easy as you are doing ^^, it's a realy complicated sytem, take a look on https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by sciorty** [comment]
I opened the docker container as you said in https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839/2.
Then went to `/data/.local/share/dresden-elektronik/deCONZ/devices` and this is what appears, it's the same as from HA in `/usr/share/hassio/addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices`:
<img width="569" alt="Schermata 2023-04-22 alle 14 53 39" src="https://user-images.githubusercontent.com/6460914/233785863-c9fa4a3f-d3b8-4531-a583-3570b87b823e.png">

At this point I suppose my DDF has been loaded correctly, even if I don't see the part @Smanar is looking for on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6682#issuecomment-1516523420 ?
Anyway I'm here because @Mimiix closed https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6886, i.e. my problem about the switches going all on/off in group. So I can control the device but all the switches are somehow grouped together!

**Comment by Smanar** [comment]
If you don't see the code part, mean something have failed. Docker are something virtual, it's don't work like normal OS, you can see something and after a reboot see other thing.

You need this code part to be able to manage switch independently.

**Comment by sciorty** [comment]
Ok but what am i doing wrong, isn’t the folder that one? 😭

**Comment by Smanar** [comment]
The folder is good, but you need to go in the docker and copy/paste the code in the created file in `/data/.local/share/dresden-elektronik/deCONZ/devices/`

**Comment by sciorty** [comment]
I really don't know what to say:
- deleted the files from both paths
- deleted the node from the deCONZ nodes graph
- factory resetted the device
- rebooted the entire raspberry
- created the DDF .json file inside the deCONZ container `/data/.local/share/dresden-elektronik/deCONZ/devices/`
- paired the device via phoscon
- when entering the editor inside deCONZ, I can see the DDF has not been loaded (correctly):
<img width="764" alt="Schermata 2023-04-22 alle 21 22 32" src="https://user-images.githubusercontent.com/6460914/233803102-5134012b-d1a2-44c0-9d9b-3d1557237517.png">

- so I opened the new manually created DDF file:
<img width="480" alt="Schermata 2023-04-22 alle 21 32 44" src="https://user-images.githubusercontent.com/6460914/233803143-bb2d00dc-69cb-4091-9761-c463ad3429e5.png">

- to see it has been loaded:
<img width="1016" alt="Schermata 2023-04-22 alle 21 38 15" src="https://user-images.githubusercontent.com/6460914/233803388-5056d39e-b332-475b-bb98-14c3b13b29c0.png">


- but the informations you are saying should appear, do not appear:
<img width="770" alt="Schermata 2023-04-22 alle 21 23 25" src="https://user-images.githubusercontent.com/6460914/233803168-b0e0309e-0c99-47a6-9bec-2b12724add48.png">

- even if it's different from what I see with the nano editor:
<img width="632" alt="Schermata 2023-04-22 alle 21 27 21" src="https://user-images.githubusercontent.com/6460914/233803182-bdbc586b-7ee2-41c1-975d-9ab49513dde6.png">

- even did an hot reload, restart etc. but I'm still stuck.

...maybe it would be easier to erase everything again and install the plugin beta release somehow?

**Comment by Smanar** [comment]
4,28 kb size for the file ?
On my side it take 4.82 kio

Still problem on the text file creation.
