### ISSUE TITLE
Please update firmware in deCONZ package (specifically raspbian deconz-latest.deb)

### ISSUE THREAD

**Issue by raoulbhatia** [dresden-elektronik/deconz-rest-plugin#6688]
## Describe the bug

The latest RPi package downloaded via http://deconz.dresden-elektronik.de/raspbian/deconz-latest.deb contains old firmware (i.e. `deCONZ_ConBeeII_0x26720700.bin.GCF` from `2021-08-19` vs. `deCONZ_ConBeeII_0x26780700.bin.GCF` from `2022-05-15`, see https://deconz.dresden-elektronik.de/deconz-firmware/ )

## Steps to reproduce the behavior

  1. Download http://deconz.dresden-elektronik.de/raspbian/deconz-latest.deb
  2. Use `dpkg -c deconz-latest.deb | grep -i firmware/`
  3. Check packaged firmware versions against https://deconz.dresden-elektronik.de/deconz-firmware/ and https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog

## Expected behavior

Latest firmware is available

## Screenshots

Package:
<img width="906" alt="Screenshot 2023-01-22 at 11 43 28" src="https://user-images.githubusercontent.com/727412/213911776-52e245a7-ffed-4048-8b40-65f886d5feec.png">

Stable firmware download page https://deconz.dresden-elektronik.de/deconz-firmware/
<img width="761" alt="Screenshot 2023-01-22 at 11 45 15" src="https://user-images.githubusercontent.com/727412/213911851-9694f2d4-3ce9-4438-94ac-95bc06b085ba.png">

Current Stable Versions from https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Firmware-Changelog **NEWER** than packaged.

<img width="352" alt="Screenshot 2023-01-22 at 11 46 27" src="https://user-images.githubusercontent.com/727412/213911889-649609b2-ec3b-4d9f-b8e4-bf2eff794776.png">

## Environment

 - Host system: RPi
 - Running method: Latest docker image from https://github.com/deconz-community/deconz-docker/
 - Firmware version: 0x26720700
 - deCONZ version: 2.20.01 / 19/09/2022 installed via docker image; but issue observed in latest package downloaded, see above
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## Additional context

Related issue deconz-community/deconz-docker#153

**Comment by Spangen** [comment]
Did a new installation with the premade Raspberry image yesterday. Same older deCONZ_ConBeeII_0x26720700.bin.GCF firmware there.

**Comment by SwoopX** [comment]
While it is apparently true that the latest firmware is not contained in the packages, this is neither a bug nor is it an issue of the deconz REST API plugin, which this is the repository for. However, you're invited to post your request in the deconz forum.

**Comment by raoulbhatia** [comment]
Thanks, @SwoopX for your reply.

I wanted to report this issue and to make it discoverable for other surprised people.
This seemed like the most appropriate repository and being on Github, this made things easy.

However, I do not want to create yet-another account at a forum just for 1 post.
I hope you and everybody else will understand that I'll thus leave it with this report.
Happy if somebody else will take this up and drive it to a resolution.

Cheers,
Raoul
