### ISSUE TITLE
Mini Smart Plug _TZ3000_gznh2xla

### ISSUE THREAD

**Issue by KoljaHenckel** [dresden-elektronik/deconz-rest-plugin#6691]
Hi,
I ordered a Tuya smart Plug 'with smart metering' and was wondering that there is a new chip in it - again- .. :( 
According to https://zigbee.blakadder.com/Tuya_TS011F.html it is compatible with DeConz, and it is wound, but electric measurement is not working.
Hope it is correct to reqeust it here, haven't found the request yet.

## Device

- Product name: Mini Smart Plug 
- Manufacturer: _TZ3000_gznh2xla
- Model identifier: TS011F
- Device type : 
  - Light

## Screenshots
Basic:
![Bildschirm­foto 2023-01-23 um 16 19 17](https://user-images.githubusercontent.com/23027041/214082713-eb5e1ab9-fd22-4f44-8dbb-108358be9eb6.png)

Node Info:
![Bildschirm­foto 2023-01-23 um 16 42 33](https://user-images.githubusercontent.com/23027041/214082654-9de17cbd-5792-4f33-b76e-dcc10417be87.png)

On/off Attributes:
![Bildschirm­foto 2023-01-23 um 16 20 07](https://user-images.githubusercontent.com/23027041/214082910-0d0b2ef2-aab7-4868-9d34-2c410bba583d.png)

Simple Metering:
![Bildschirm­foto 2023-01-23 um 16 20 37](https://user-images.githubusercontent.com/23027041/214083011-fcb1aff3-1ac3-43f5-95d2-79b2d81a39cd.png)

Electric Measurement:
![Bildschirm­foto 2023-01-23 um 16 21 07](https://user-images.githubusercontent.com/23027041/214083168-da20796a-f2fd-47c3-9167-1debdd4239a5.png)

Not sure if this information is relevant:

## Environment
Host system: Raspberry Pi
Running method: HomeAssistant 
  Home Assistant 2023.1.7
  Supervisor 2022.12.1
  Operating System 9.4
  Frontend 20230110.0 - latest
  Firmware version: 266b0700
deCONZ version: 2.19.03 / 19.9.2022
Firmware: 26720700
Device: ConBee II
Do you use an USB extension cable: yes
Is there any other USB or serial devices connected to the host system? If so: no

**Comment by BabaIsYou** [comment]
Can you try this DDF to begin with it ? Got it from #6066 

```
{
    "schema": "devcap1.schema.json",
    "manufacturername": "_TZ3000_gznh2xla",
    "modelid": "TS011F",
    "product": "Random tuya plug",
    "sleeper": false,
    "status": "Gold",
    "subdevices": [
      {
        "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
        "restapi": "/lights",
        "uuid": [
          "$address.ext",
          "0x01"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "state/alert",
            "description": "The currently active alert effect.",
            "default": "none"
          },
          {
            "name": "state/on"
          },
          {
            "name": "state/reachable"
          }
        ]
      },
      {
        "type": "$TYPE_CONSUMPTION_SENSOR",
        "restapi": "/sensors",
        "uuid": [
          "$address.ext",
          "0x01",
          "0x0702"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "config/on"
          },
          {
            "name": "config/reachable"
          },
          {
            "name": "state/consumption",
            "read": {"at": "0x0000", "cl": "0x0702", "ep": 1, "fn": "zcl" },
            "parse": {"at": "0x0000", "cl": "0x0702", "ep": 1, "eval": "Item.val = Attr.val * 10"},
            "refresh.interval": 900
          },
          {
            "name": "state/lastupdated"
          }
        ]
      },
      {
        "type": "$TYPE_POWER_SENSOR",
        "restapi": "/sensors",
        "uuid": [
          "$address.ext",
          "0x01",
          "0x0b04"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "config/on"
          },
          {
            "name": "config/reachable"
          },
          {
            "name": "state/current"
          },
          {
            "name": "state/lastupdated"
          },
          {
            "name": "state/power"
          },
          {
            "name": "state/voltage"
          }
        ]
      }
    ],
    "bindings": [
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0006",
        "report": [
          {
            "at": "0x0000",
            "dt": "0x10",
            "min": 1,
            "max": 1800
          }
        ]
      },
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0702",
        "report": [
          {
            "at": "0x0000",
            "dt": "0x25",
            "min": 1,
            "max": 300,
            "change": "0x0000000A"
          }
        ]
      },
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0B04",
        "report": [
          {
            "at": "0x0505",
            "dt": "0x21",
            "min": 1,
            "max": 500,
            "change": "0x00000003"
          },
          {
            "at": "0x0508",
            "dt": "0x21",
            "min": 1,
            "max": 300,
            "change": "0x0000000F"
          },
          {
            "at": "0x050B",
            "dt": "0x29",
            "min": 1,
            "max": 300,
            "change": "0x00000003"
          }
        ]
      }
    ]
  }
```

**Comment by KoljaHenckel** [comment]
Thanks a lot.
I copied it over, removed the device and paired it again.
Now there is an power entity, updating every 6 minutes, and consumption entity, that updates every 20 minutes.
The consumption entry seems to be 10x less that it should be
(I have a 40W lamp as a test there for one hour now, according to the plug it consumes about 38-39 W.
The consumption entry now states after 1 hour 0,004 kWh, not 0,04 kWh as it should. Or do I have a misunderstanding?

**Comment by BabaIsYou** [comment]
Hi. It seems you’re right. Now that DDF is loaded you can directly change the eval compute from GUI inside DDF editor, (save and hit reload) or you can change the compute formula into the DDF and restart DeConz.

you can just try to replace the consomption formula from `Item.val = Attr.val * 10 ` to `Item.val = Attr.val*100`

**Comment by KoljaHenckel** [comment]
Hi,
Not sure why, but after a few reboots and problems with the DeConz container, but no change in the DDF, it seems to be working correct now.
Still wondering what went wrong, but it is ok for the moment.
