### ISSUE TITLE
switch 2 gang _TZ3000_t8hzpgnd the battery runs out

### ISSUE THREAD

**Issue by sanluca** [dresden-elektronik/deconz-rest-plugin#6696]
Hello everybody,

I'm using the loratap _TZ3000_t8hzpgnd remote controls
but I have some problems, they work for a day or two and then they start flashing until the battery runs out, I tried to change the battery several times but same problem, I tried on more remotes but the problem remains.
what can they have?

thank you

**Comment by Mimiix** [comment]
Hi,

As this is not following the template, i am closing this issue.

Please follow proper procedure.

Kind regards,
