### ISSUE TITLE
Most of sensors don't have "swversion" key

### ISSUE THREAD

**Issue by mariusmotea** [dresden-elektronik/deconz-rest-plugin#670]
Hi,

After i reset deconz configuration in order to fix previews issue with 3rd tradfri motion sensor not being detected i end errors during pairing of diyhue because some sensors don't have swversion key. I'm not the only one having this issue, other user report the same [here](https://github.com/mariusmotea/diyHue/issues/269)

My config is this:

`{"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":true,"daylight":false,"lastupdated":"2018-07-02T20:03:24","status":220},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:01:3e:34-01"},"10":{"config":{"alert":"none","battery":60,"group":"41841","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Geam Dormitor","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:53:50"},"swversion":"1.2.214","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:4b:c9:e3-01-1000"},"11":{"config":{"alert":"none","battery":60,"group":"55217","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Dulap Dormitor","state":{"buttonevent":1002,"lastupdated":"2018-07-02T19:12:48"},"swversion":"1.2.214","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:0e:d2:7d-01-1000"},"12":{"config":{"alert":"none","battery":60,"delay":60,"duration":60,"group":"55197","on":true,"reachable":true},"ep":1,"etag":"98b6062e44dc25657f038f5e95e56af8","manufacturername":"IKEA of Sweden","modelid":"TRADFRI motion sensor","name":"Senzor Baia Mica","state":{"dark":true,"lastupdated":"2018-07-02T20:11:15","presence":false},"swversion":"1.2.214","type":"ZHAPresence","uniqueid":"00:0b:57:ff:fe:8e:db:77-01-1000"},"13":{"config":{"alert":"none","battery":100,"duration":60,"on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","modelid":"TRADFRI motion sensor","name":"Senzor Living","state":{"lastupdated":"2018-07-02T18:42:59","presence":true},"swversion":"1.2.214","type":"ZHAPresence","uniqueid":"00:0b:57:ff:fe:2e:eb:18-01-1000"},"14":{"config":{"battery":100,"on":true,"reachable":true,"temperature":2800,"tholddark":12000,"tholdoffset":7000},"ep":1,"etag":"ee713dd09f008de672c23f6e5c35f44b","manufacturername":"LUMI","modelid":"lumi.sensor_motion.aq2","name":"Senzor Hol","state":{"dark":false,"daylight":false,"lastupdated":"2018-07-02T20:14:08","lightlevel":17709,"lux":59},"type":"ZHALightLevel","uniqueid":"00:15:8d:00:01:e5:28:27-01-0400"},"15":{"config":{"battery":100,"duration":60,"on":true,"reachable":true,"temperature":2800},"ep":1,"etag":"ee713dd09f008de672c23f6e5c35f44b","manufacturername":"LUMI","modelid":"lumi.sensor_motion.aq2","name":"Senzor Hol","state":{"lastupdated":"2018-07-02T20:15:08","presence":false},"type":"ZHAPresence","uniqueid":"00:15:8d:00:01:e5:28:27-01-0406"},"16":{"config":{"battery":null,"duration":60,"on":true,"reachable":true,"temperature":0},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"LUMI","modelid":"lumi.sensor_motion","name":"Motion Sensor","state":{"lastupdated":"2018-07-02T18:54:49","presence":false},"type":"ZHAPresence","uniqueid":"00:15:8d:00:01:e1:84:47-01-0406"},"17":{"config":{"alert":"none","battery":16,"group":"21955","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":4,"modelid":"TRADFRI wireless dimmer","name":"Wireless Dimmer Hol","state":{"buttonevent":3002,"lastupdated":"2018-07-02T18:54:10"},"swversion":"1.1.1.1-5.7.2.0","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:2d:30:09-01-1000"},"2":{"config":{"alert":"none","battery":74,"delay":60,"duration":60,"group":"49299","on":true,"reachable":true},"ep":1,"etag":"16f79d4c03064576edb7a3cf44ee6371","manufacturername":"IKEA of Sweden","modelid":"TRADFRI motion sensor","name":"Sensor Bucatarie","state":{"dark":false,"lastupdated":"2018-07-02T20:08:12","presence":false},"swversion":"1.2.214","type":"ZHAPresence","uniqueid":"00:0b:57:ff:fe:95:29:5c-01-1000"},"3":{"config":{"alert":"none","battery":34,"group":"34636","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Living","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:56:16"},"type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:4f:30:a6-01-1000"},"4":{"config":{"alert":"none","battery":47,"group":"59297","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":4,"modelid":"TRADFRI wireless dimmer","name":"TRÅDFRI wireless dimmer","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:31:35"},"swversion":"1.2.248","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:24:27:c7-01-1000"},"5":{"config":{"alert":"none","battery":47,"group":"18143","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Bucatarie","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:54:26"},"swversion":"1.2.214","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:49:66:4b-01-1000"},"6":{"config":{"alert":"none","battery":47,"group":"65532","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Hol","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:54:22"},"type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:9d:cd:8d-01-1000"},"7":{"config":{"alert":"none","battery":34,"group":"26290","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Dormitor Mic","state":{"buttonevent":1002,"lastupdated":"2018-07-02T19:12:54"},"swversion":"1.2.214","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:c0:76:45-01-1000"},"8":{"config":{"alert":"none","battery":60,"group":"26926","on":true,"reachable":true},"ep":1,"etag":"f12988d7dbf701180506dc67bb5ce035","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Baia Mica","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:57:28"},"swversion":"1.2.214","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:b2:cd:f4-01-1000"},"9":{"config":{"alert":"none","battery":47,"group":"3239","on":true,"reachable":true},"ep":1,"etag":"7433817b0db10533f3d2d031ca760462","manufacturername":"IKEA of Sweden","mode":3,"modelid":"TRADFRI remote control","name":"Telecomanda Intrare Dormitor","state":{"buttonevent":1002,"lastupdated":"2018-07-02T18:57:22"},"swversion":"1.2.214","type":"ZHASwitch","uniqueid":"00:0b:57:ff:fe:bf:2c:71-01-1000"}}`

**Comment by mariusmotea** [comment]
i discover that with the two remotes that miss the swversion attribute i'm not able to pair them if i don't press a button. During the pair process the ready button get green only if i interact with the remote, otherwise it will timeout and receive the pair fail message. I see the same behaviour on raspbee green led, it blink constant every 1-2 seconds so i believe it can be the same issue with deconz configuration.

**Comment by manup** [comment]
Remotes (and sensors) are tricky since they are sleeping devices, to communicate with them they need to be aware. Normally they should stay awake a bit during setup phase. Pressing the buttons will also wake them so that few commands can slip through.

In our tests with Phoscon App the process worked as described in the wizard, but there might be differences in setup or device firmware which requires to wake-up the remote manually during setup like you did.

**Comment by mariusmotea** [comment]
I have same firmware on all remotes (1.2.214 - last one) and as you can see in attached config the lack of swversion attibute is also with XIAOMI sensors.

**Comment by manup** [comment]
The swversion attribute should be queried at least for the IKEA remote, for Xiaomi sensors we don't do this since they rarely respond to requests. The swversion shown for some Xiaomi sensors is absed on attribute reports send on their own.

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/de_web_plugin.cpp#L11141
