### ISSUE TITLE
Aqara original motion sensor lumi.sensor_motion.aq2 not reporting correctly illuminance in some sensors

### ISSUE THREAD

**Issue by andys73** [dresden-elektronik/deconz-rest-plugin#6700]
## Describe the bug
The aqara original motion sensor does not seems to report illuminance level correctly, reporting 0 or very low values. Some of the same sensor do report correct values which is quite odd.

## Steps to reproduce the behavior
1. Remove and repair motion sensor that showed 0 all day in phoscon. It still reports 0lux.
2. Repair the same motion sensor in an aqara hub ( I used a G2H camera). It reports correctly 

## Expected behavior
Consistent reporting of lux level as is used in automations.

## Screenshots
Phoscon reporting
![aqara-phoscon](https://user-images.githubusercontent.com/77861753/215056326-c5a8e341-9290-4121-8163-5d0ddacf88c7.png)
Home assistant reporting
![aqara-HA](https://user-images.githubusercontent.com/77861753/215056342-49ebbcb4-5f00-48e9-9091-1c0e5a07a42c.jpeg)
Aqara hub reporting
![aqara-aqara-hub](https://user-images.githubusercontent.com/77861753/215056579-079103a5-3916-44b9-8b4d-103b14c46d75.png)
## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: (26780700)
 - deCONZ version: (2.20.01)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? USB SSD, Bluetooth dongle (extension away from conbee 2), UPS USB interface

## Additional context
Large network a combination of Aqara (motion and temperature), Lidl (plugs and extensions), Osram (plugs), Sonos ZBMINI, Heiman (plugs and smoke sensors),  Philips Hue (One motion sensor)

**Comment by BabaIsYou** [comment]
Hmmm ... difficult to make the slightest diagnosis if we don't even know what equipment it is ... model Identifier, manufacturer anme ... some more precise information than just "Aquara Sensor" ;-)

**Comment by andys73** [comment]
![image](https://user-images.githubusercontent.com/77861753/215090984-b5479bea-cdd4-46ef-85f0-78c8974f83c9.png)

**Comment by Smanar** [comment]
I m making tries on my side ATM, same model "lumi.sensor_motion.aq2" , no problem for the moment, still on 2.19 version.
Will try tommorow on 2.20

**Comment by andys73** [comment]
I just cannot figure out why only some sensors are not reporting illuminance or very low, 1 lx. 
I thought that maybe is the one that I had to re-pair over the months but I have re-paired one that reports correctly and it still does after re-pairing... 
Maybe the ddf is shared between the two variants of this sensors, the one that has illuminance sensor and the one who does not and at re-pairing some sensors do not detect that they have the photodiode..

There is nothing wrong with the sensor that I have tested as it reported in the aqara app..

**Comment by andys73** [comment]
I am trying to find a pattern and all I can say that on all sensors the reporting is erratic with some that reported some light now is 1lx despite the light in the room.
![image](https://user-images.githubusercontent.com/77861753/215259075-d1620bad-619a-439a-8191-4d20a03a3df6.png)

**Comment by BabaIsYou** [comment]
Just to be sure. Do they all already report correctly in your environnement by the past ?

**Comment by Smanar** [comment]
Still no issue on side for lightlevel, even with 2.20 version and the "lumi.sensor_motion.aq2"

**Comment by andys73** [comment]
@BabaIsYou I have automations based on these motion sensors based also on contion on lux levels for 2 years now and used to be spot on. For a while I have noticed that the automations are not as reliable as before, i.e. light on the hallway will turn on even if is quite a lot of light or light will not turn on at night ... I thought is something wrong in HA but in fact the automation is not firing as the condition on above lux level is not met.

@MrSolo570  reported the same thing in this thread https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6692#issuecomment-1406339763

I am not sure what to provide or do to help.

**Comment by andys73** [comment]
[https://pastebin.com/reHm4MBg](url)
the motion sensor that has a problem is Motion Sensor 10 Kitchen 2 maybe someone can read better than me on what is going on. I set the debug to info / info 2 and error and expose the sensor to a higher light level .. It still shows as 0 everywhere.

**Comment by andys73** [comment]
ok I have done extensive testing and I can confirm that is all in my mind...
All works as expected, just the place where the sensor I was testing with it reports 0 lux and the same is in the aqara light.
I just need to tune a bit the automation light levels as in the winter is darker in the house.. 
thank you all for your help and support

**Comment by andys73** [comment]
for other interested I used the following condition on the sensor that is relevant i.e. not in a dark corner... for Home Assistant.
`condition:
  - condition: state
    entity_id: sensor.lightlevel_87
    attribute: dark
    state: "true"`

**Comment by MrSolo570** [comment]
Can you elaborate on that?
I am using the same aqara motion sensor and it should turn on the lights only if the condition is met that the light level is below the value of 3. Are you saying I should just use the condition "dark"?

**Comment by andys73** [comment]
yes, experimenting with the  conditions when lights should turn on I found it best to cover all cases below and I used dark attribute rather than playing with lux values.. and added the sun condition as a fail-over in case that attribute remains true at night for whatever reason.. Seems to work fine by now, I am sure I will fine tune it in the future :)
`  - condition: or
    conditions:
      - condition: sun
        before: sunrise
        after: sunset
      - condition: state
        entity_id: sensor.lightlevel_39
        attribute: dark
        state: true`

**Comment by ebaauw** [comment]
Best practice is to base automations on `state/dark` and `state/daylight`, and calibrate the light level sensors though `config/tholddark` and `config/tholdoffset`.  Note that the sensor only reports the light level, dark and daylight are derived by the REST API plugin.

Also note that either `dark` or `daylight` can be `true` are any given time, but both can be `false` at the same time.  This leads to a kind of twilight state, where you don’t want to change the lights, or they keep flipping on and off.  So, you want to turn lights on when `dark` becomes `true` and turn them off when `daylight` becomes `true`.

For my Hue motion sensors (all models), I use `tholdark` of 12000.  Depending on the light level the sensor reports with only artificial light, `tholdoffset` is between 4000 and 12000.  I find it’s not always possible to position a combined sensor, so it doesn’t look directly into a light, as it also needs to see motion.

**Comment by andys73** [comment]
excellent information. Thanks!
Not sure if aqara supports config/tholddark but for hallway & kitchen the previous code that I posted seems to hold ok for now.

**Comment by MrSolo570** [comment]
Thank you for this information. I will try that approach too and report back.

Can anyone explain what is meant by "through config/tholddark and config/tholdoffset"? I am running home assistant and deconz via plugin... Thank you all
