### ISSUE TITLE
No version information, firmware and plugin visible, ConBee II

### ISSUE THREAD

**Issue by auchda** [dresden-elektronik/deconz-rest-plugin#6703]
## Describe the bug
After firmware Update to 0x26780700, Rest-Plugin v2.20.1 I cannot see the version information anymore in the Phoscon app screen. Buttons Allgemein, Erweitert and Power are not clickable/enabled. Functionality via Android: all4Hue and Hue Essential still available.

## Steps to reproduce the behavior
  1. Go to Settings - Gateway

## Expected behavior
Show version information eg. allow backup, be able to use the buttons.

## Environment
 - Host system: Raspberry Pi 3B
 - Running method: Raspbian Buster
 - Firmware version: (26780700)
 - deCONZ version: (2.20.1)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No.

## Additional context

![image](https://user-images.githubusercontent.com/103569384/215122702-a7bf264a-b638-4d6a-a0cf-d50ba992260a.png)

**Comment by auchda** [comment]
Is s/o taking care of issues or is just waited until the BOT closes the bug report?

**Comment by Smanar** [comment]
Hello, have you tried on other browser or in private mode ?

**Comment by Mimiix** [comment]
I missed this one, my appologies. 
The Bot is here to remind of issues that are open. 

This is a bug report for Phoscon, not deCONZ. Phoscon bugs are collected on the forums, this repo is collecting bugs for deCONZ. 
 
Closing this issue, please report on the forums.
