### ISSUE TITLE
[Device Support Request] BSEED 2 Way Switch _TZ3000_e98krvvk

### ISSUE THREAD

**Issue by xADDRx** [dresden-elektronik/deconz-rest-plugin#6721]
## Device

- Product name: BSEED Zigbee 2 Way Switch
- Manufacturer: _TZ3000_e98krvvk
- Model identifier: TS0012
- Device type : Switch

## Screenshots
![grafik](https://user-images.githubusercontent.com/64784940/216084623-4d1499b0-c002-4b19-b412-efcea2b398e7.png)
![grafik](https://user-images.githubusercontent.com/64784940/216084876-0a9c2d38-9b5c-4deb-b702-18c90fa881f5.png)
![grafik](https://user-images.githubusercontent.com/64784940/216084948-7130c15b-ade8-4e8e-8cf0-5af394766663.png)

### Basic
![grafik](https://user-images.githubusercontent.com/64784940/216083498-f4df12c3-2900-4bf3-a02f-5098fbf251a6.png)

### Identify
![grafik](https://user-images.githubusercontent.com/64784940/216083575-128ae1e5-5d7f-4a2d-a286-17bfdd417496.png)

### Groups
![grafik](https://user-images.githubusercontent.com/64784940/216083663-2d236fc9-e9ce-4dbf-b671-a1d28b04688c.png)
![grafik](https://user-images.githubusercontent.com/64784940/216083738-c64f5a2d-4a0c-4c9b-8304-c339e8a11578.png)

### Scenes
![grafik](https://user-images.githubusercontent.com/64784940/216083805-5c483053-c2cd-4506-be1a-37c87c9283ec.png)
![grafik](https://user-images.githubusercontent.com/64784940/216083881-09c34d0f-792f-4f5b-bcef-e51d235f20f9.png)
![grafik](https://user-images.githubusercontent.com/64784940/216083957-f00c4156-5c09-4d76-a1f0-a7c9a1c37ac0.png)
![grafik](https://user-images.githubusercontent.com/64784940/216084016-0de96f4b-7498-47cb-989f-4c6e8d512270.png)

### On/Off
![grafik](https://user-images.githubusercontent.com/64784940/216084108-ec9af70e-370d-4ddc-adac-706b765e2f2a.png)
![grafik](https://user-images.githubusercontent.com/64784940/216084166-e26d1b4e-9718-4a91-87df-9df1c2e46da2.png)

That from here didn't help me, because both switches switch no matter which one I press:
(https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5837)

**Comment by BabaIsYou** [comment]
Please can you redo the clusters screenshots after clicking on "read" button to have attributes values updated from the device ?

**Comment by xADDRx** [comment]
> Please can you redo the clusters screenshots after clicking on "read" button to have attributes values updated from the device ?

Hi, 
sorry yes of course:
![grafik](https://user-images.githubusercontent.com/64784940/216113775-7efa0bd8-5968-4dab-a7b9-9b4776cb8ae4.png)

**Comment by BabaIsYou** [comment]
As I can see there is already a DDF for this device in #5837 but as I understand you can't manage each of the switch separatly with it ?

**Comment by xADDRx** [comment]
> 

As I can see there is already a DDF for this device in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5837 but as I understand you can't manage each of the switch separatly with it ?  **Yes right**

**Comment by BabaIsYou** [comment]
If it requires Tuya magic sequence it's not supported yet :  [here](https://forum.phoscon.de/t/including-standard-tuya-magic-spell-sequence-during-joining/2916/13)

**Comment by BabaIsYou** [comment]
Good news,

@Smanar did a great job in doing this Tuya Magic sequence to be integrated in a [DDF](https://forum.phoscon.de/t/including-standard-tuya-magic-spell-sequence-during-joining/2916/15). That's perhaps just a workaround waiting for something more optimized but can try to add the part in the referenced issue in the existing DDF ?
