### ISSUE TITLE
DDF support for Hama Thermostat TZE200_h4cgnbzg

### ISSUE THREAD

**Issue by phwagner82** [dresden-elektronik/deconz-rest-plugin#6722]
## Device

- Product name: Hama smart thermostat
- Manufacturer: _TZE200_h4cgnbzg
- Model identifier: TS0601
- Device type : Thermostat

## Screenshots
![image](https://user-images.githubusercontent.com/58769351/216445107-3489f634-93ad-4839-b358-9ad8dd0d8fb1.png)

![image](https://user-images.githubusercontent.com/58769351/216444657-32a02d1f-852d-42a6-85f5-cd492bd2b30b.png)

**Comment by Mimiix** [comment]
Already supported with a merge yesterday.

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6690


Please search the manufacturer name first before posting.
