### ISSUE TITLE
Toyu TS011F no power management reported.

### ISSUE THREAD

**Issue by pocipocster** [dresden-elektronik/deconz-rest-plugin#6725]
Tz3000_yujkchbz

 Not sure that's enough info???

**Comment by Mimiix** [comment]
Hi.

Please open a device request with all requested info.

Closing.

**Comment by pocipocster** [comment]
Hi

Sorry ; new to all this zigbee stuff .
Afaik this plug is supported .
What other info do you need ???

Cheers
Mark

Sent from my iPhone

On 4 Feb 2023, at 16:42, Dennis D ***@***.***> wrote:

﻿

Closed #6725<https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6725> as completed.

**Comment by Mimiix** [comment]
Screenshots of all clusters. See the template you had presented when creating the issue.
