### ISSUE TITLE
MOES Tuya Zigbee BHT-002 wall thermostat TZE200_aoclfnxz

### ISSUE THREAD

**Issue by ltspicer** [dresden-elektronik/deconz-rest-plugin#6733]
Moes Tuya Thermostat BTH-002

-     Product name: Moes thermostat BHT-002
-     Manufacturer: _TZE200_aoclfnxz
-     Model identifier: TS0601
-     Device type :
        Thermostat

![Auswahl_006](https://user-images.githubusercontent.com/11616336/217617371-3b9fc6b8-9f80-4928-bd4f-9da4c82f206c.png)

![Auswahl_007](https://user-images.githubusercontent.com/11616336/217617806-64873338-81d1-4ba6-a29d-12675b708f59.png)

### Basic
![Auswahl_004](https://user-images.githubusercontent.com/11616336/217616380-0b147ce5-6e37-45d3-84d2-410828a1004f.png)

![Auswahl_003](https://user-images.githubusercontent.com/11616336/217631119-c1b13840-8dc1-4665-961c-76dc7b3d777b.png)

### DDF editor
![Auswahl_005](https://user-images.githubusercontent.com/11616336/217616682-422e4511-d627-44dd-8856-efd07c112488.png)

I can't find this device in the compatibility list.

Pairing with Phoscon app works and the device is displayed in the deCONZ GUI.
The device works.
In the ioBroker adapter I see it as a sensor named “Thermostat 11”.
**But the device is not listed in the Phoscon app.**

I use RaspBee2 on RPI3 with Bullseye.

DDF:
`{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_aoclfnxz",
  "modelid": "TS0601",
  "product": "Tuya_THD BTH-002 Thermostat",
  "sleeper": false,
  "status": "Draft",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0201"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0xEF00",
          "0x0000",
          "0xEF00"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/productid",
          "public": false,
          "description": "Product identifier of the device.",
          "refresh.interval": 86400
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/heatsetpoint",
          "description": "Target temperature of a thermostat.",
          "default": 0
        },
        {
          "name": "config/locked",
          "description": "Locks or unlocks the device. This item has to be understood as child-lock.",
          "default": false
        },
        {
          "name": "config/offset",
          "description": "Relative offset to the main measured value.",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/preset",
          "description": "Sets the operating mode for Tuya thermostats."
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/schedule",
          "description": "On-device heating schedules."
        },
        {
          "name": "config/schedule_on",
          "description": "Determines if on-device schedules for setting the heatsetpoint are currently used or if the thermostat is operated manually.",
          "default": false
        },
        {
          "name": "config/setvalve"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/temperature",
          "description": "The current temperature in °C &times; 100.",
          "default": 0
        }
      ]
    }
  ]
}`

**Comment by Mimiix** [comment]
Missing screenshots from all clusters.

**Comment by Mimiix** [comment]
> Missing screenshots from all clusters.

Additionaly, make sure to add the first paragraph containing the model id , manufacturer name and other info

**Comment by ltspicer** [comment]
Now I find the device there:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3304
