### ISSUE TITLE
Tuya Photoelectric Smoke Detector _TZE200_m9skfctm

### ISSUE THREAD

**Issue by BabaIsYou** [dresden-elektronik/deconz-rest-plugin#6734]
## Device

- Product name: Tuya Photoelectric Smoke Detector [Link](https://www.aliexpress.com/item/1005003970944017.html?spm=a2g0o.order_list.order_list_main.10.747f1802aTUNEp)
- Manufacturer:  _TZE200_m9skfctm
- Model identifier:TS0601
- Device type 
  - Sensor
![image](https://user-images.githubusercontent.com/85300265/217686865-73353c50-f412-4cea-b605-d0c7686c4f08.png)

## Screenshots

![image](https://user-images.githubusercontent.com/85300265/217685546-d8c6811a-66b4-4817-a989-8b621ac9a007.png)

### Basic
![image](https://user-images.githubusercontent.com/85300265/217685684-4e18025a-9e95-438a-8624-006105be45e0.png)

### Groups
![image](https://user-images.githubusercontent.com/85300265/217685773-0a5a1dbf-906e-4d10-af95-280eeeb86db0.png)
![image](https://user-images.githubusercontent.com/85300265/217685892-c57fd54d-8064-4541-bcf0-e2a3f7de138e.png)
![image](https://user-images.githubusercontent.com/85300265/217685959-922f3d23-bb83-4f95-ab16-beebe1aae4e6.png)

### Scenes
![image](https://user-images.githubusercontent.com/85300265/217686044-2a45183b-7a06-4621-a8f1-f42be7513f06.png)

Information found [here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/bcdb6b3c593cac61741cbe9f5254606de73f67f7/devices/tuya.js#L2660) and [here](https://github.com/Koenkk/zigbee2mqtt/issues/15349)

**Comment by BabaIsYou** [comment]
Testing following DDF

```
{
	"schema": "devcap1.schema.json",
	"manufacturername": "_TZE200_m9skfctm",
	"modelid": "TS0601",
	"vendor": "Tuya",
	"product": "Photoelectric Smoke sensor",
	"sleeper": true,
	"status": "Silver",
	"subdevices": [{
		"type": "$TYPE_FIRE_SENSOR",
		"restapi": "/sensors",
		"uuid": [
			"$address.ext",
			"0x01",
			"0xef00"
		],
		"items": [{
				"name": "attr/id"
			},
			{
				"name": "attr/lastannounced"
			},
			{
				"name": "attr/lastseen"
			},
			{
				"name": "attr/manufacturername"
			},
			{
				"name": "attr/modelid"
			},
			{
				"name": "attr/name"
			},
			{
				"name": "attr/swversion",
				"refresh.interval": 86400,
				"parse": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0x0001",
					"script": "tuya_swversion.js"
				},
				"read": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0x0001"
				}
			},
			{
				"name": "attr/type"
			},
			{
				"name": "attr/uniqueid"
			},
			{
				"name": "config/battery",
				"awake": true,
				"read": {
					"fn": "none"
				},
				"parse": {
					"dpid": 15,
					"eval": "Item.val = Attr.val / 2;",
					"fn": "tuya"
				},
				"default": 0
			},
			{
				"name": "config/enrolled",
				"public": false
			},
			{
				"name": "config/on"
			},
			{
				"name": "config/pending"
			},
			{
				"name": "config/reachable"
			},
			{
				"name": "state/fire",
				"awake": true,
				"read": {
					"fn": "none"
				},
				"parse": {
					"dpid": 1,
					"eval": "Item.val = (Attr.val == 1);",
					"fn": "tuya"
				},
				"default": false
			},
			{
				"name": "state/test",
				"read": {
					"fn": "none"
				},
				"parse": {
					"dpid": 101,
					"eval": "Item.val = Attr.val;",
					"fn": "tuya"
				},
				"default": 0
			},
			{
				"name": "state/errorcode",
				"read": {
					"fn": "none"
				},
				"parse": {
					"dpid": 11,
					"eval": "Item.val = String(Attr.val);",
					"fn": "tuya"
				},
				"default": "0"
			},
			{
				"name": "state/lastupdated"
			}
		]
	}]
}
```

**Comment by BabaIsYou** [comment]
Will be able to add another attribute regarding smoke ppm when PR [#6673](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6673 ) will be merged

        {
          "name": "state/airqualityco2",
          "awake": true,
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "eval": "Item.val = Attr.val ;",
            "fn": "tuya"
          },
          "default": 0
        },

**Comment by BabaIsYou** [comment]
Hi. A bit weird because mine is fully functional with that DDF and a test return an event with test:true.

Do you mean that you have a fire alarm but the device does not make a at noise ?

I don’t see any version information in your request. Then I suppose that you don’t have the tuya_version.js under your local directory. Can you make a screenshot from DeConz GUI basic cluster to show the version please (may be a new firmware ?)

**Comment by Bernhard-Bodensee** [comment]
![Bildschirmfoto 2023-02-14 um 12 56 47](https://user-images.githubusercontent.com/66668964/218731770-13be2653-d164-4ba3-9283-fc5309fc81fe.jpg)
 
When I press the butten the device make the beep beep beep... until I press again. Looks normal.
I never installed any tuya stuff, how can I check that?
The versions of conbee/phoscon and homebridge are the latest.
I also tried to remove everything, strange to me: the sensor still exists. Can there be some caching problem, some old stuff is used somewhere?
I am using a browser w/o caching and I have cleared the homebridge cache already. But I dont know how to clear caches in deconz or phoscon???

**Comment by Bernhard-Bodensee** [comment]
My  configuration:
raspberry 3B mit Linux raspberrypi 5.10.60-v7+ #1449 SMP Wed Aug 25 15:00:01 BST 2021 armv7l GNU/Linux
Homebridge [v1.6.0]
homebridge-hue v0.13.51
deCONZ_ConBeeII_0x26780700.bin.GCF
phoscon/deconz:
![Bildschirmfoto 2023-02-14 um 15 28 56](https://user-images.githubusercontent.com/66668964/218767291-306c2718-298a-4e07-9514-d8947db9cc13.jpg)

**Comment by BabaIsYou** [comment]
> When I press the butten the device make the beep beep beep... until I press again. Looks normal.

Yes that's the test button. Then you should have an event in Phoscon with `"test": true`

> I also tried to remove everything, strange to me: the sensor still exists.

Where is it still present ? In Deconz, Phoscon, Homebridge ? Everywhere ? How did you delete it ?

**Comment by Bernhard-Bodensee** [comment]
![Bildschirmfoto 2023-02-14 um 18 21 37](https://user-images.githubusercontent.com/66668964/218811413-bd6c5847-8792-4c22-bf5d-cc65d28ad698.jpg)

still the same, when I hit the test button, "test": true.
but in every record it shows "fire":true , this is probably the reason for showing the alarm in homekit and eve permanently.
I have not found any info how to factory reset the device, when I hit the button for longer it seems to go into pairing mode only.

Regarding "removal" and start all over: This is how I did it:
I removed battery from device, deleted the node in deconz, deleted the DDF-File (local), stopped deconz, restarted deconz and homebridge and homekit - then the device was still in all of them with alarm on!

BTW: The device has never been visible in Phoscon but I learned that that is normal for temporary DDFs.

What would be the correct way/sequence of actions to remove the 2 smoke devices currently paired and start all over ?

**Comment by BabaIsYou** [comment]
> "phoscon-GW: /sensors/19: warning: unknown ZHAFire sensor etc..."

Got exactly the same ... I don't really care about Phoscon for this device... I sometimes used it just to have a friendly gui to access some information like json ;-)

It's weird that your device present `"fire": true ` because the default in DDF is false. Than perhaps means that your device seems to present really an alarm and it's may be faulty ?

To delete a device, it's seems you did it like it could be done. Perhaps you could try to delete the device before remove battery and restart deconz bfore putting the battery back and repairing the device.

It's strange that the device stay after delete. You say that you have two of them, is it the previous "deleted" one and the second the device after rejoining ? Do they have different sensor id ? And how could Deconz handle the same `uniqueid` on two difference sensor ?

Could you provide for both what you called API-Info [previously](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6734#issuecomment-1429523314) ?

**Comment by Bernhard-Bodensee** [comment]
![Bildschirmfoto 2023-02-14 um 22 59 46](https://user-images.githubusercontent.com/66668964/218873511-38a3e5d1-28b1-4ea7-93f1-76155a9e887b.jpg)
![Bildschirmfoto 2023-02-14 um 23 01 39](https://user-images.githubusercontent.com/66668964/218873544-c829573a-8b78-4894-abed-f4ca6499d95c.jpg)
![Bildschirmfoto 2023-02-14 um 23 01 58](https://user-images.githubusercontent.com/66668964/218873564-012799b4-1d64-45ea-98ac-78598f2f1833.jpg)

The 2 devices are different, got different Mac/NWK, there is no mix, deconz and all other components process that correctly. I paired fire-20 this morning for the first time just to see if it behaves the same as fire-19.
I would assume that it is unlikely that 2 devices got the same fault, but still possible. I will try more things tomorrow - I would hate my neighbors calling fire brigade caused by my test alarms...

**Comment by BabaIsYou** [comment]
Ok I understand. And you’re right, chances to get two faulty devices at the same time … hmmm 🤔

**Comment by Bernhard-Bodensee** [comment]
![Bildschirmfoto 2023-02-15 um 17 55 53](https://user-images.githubusercontent.com/66668964/219099158-f2c55be1-192c-4b5d-a448-ab828d16f171.jpg)

I could not reproduce that the device is still visible somewhere after removal in deconz. Maybe I fell into a trap with data from cache.
Every removal and repairing of the same device results in a new sequence number fire-19, fire-20, fire 21 etc- with the same uniqueid - that looks normal.
However, Result in API-Info/events  is always the same:
fire = true
If I hit the test button that is shown inaddition to fire = true.

I played around a bit in the DDF setting the default to different values like "0" and "false" or empty etc - no change.
I am lost now, I hope you got some idea on how to proceed.

**Comment by BabaIsYou** [comment]
> Every removal and repairing of the same device results in a new sequence number fire-19, fire-20, fire 21 etc- with the same uniqueid - that looks normal.

Yes, it is !

> I hope you got some idea on how to proceed.

Not he idea of the century for sure : did you try to click in basic cluster on exec button to reset to factory default ? In the mean time could you get some log with just INFO and DDF checked ? it's sufficient to get DDF evals and Tuya request/response ?

**Comment by Bernhard-Bodensee** [comment]
I hit the exec button. But nothing really happened. I would expect that the device would require repairing after factory reset but it just continued working and spreading "fire: true".
How do I get the log info you requested :"get some log with just INFO and DDF checked ? it's sufficient to get DDF evals and Tuya request/response ?"

BTW: swversion is null or that line is missing in event records. 
```
   "22:51:39:526": {
        "attr": {
            "id": "22",
            "lastannounced": "2023-02-15T21:43:28Z",
            "lastseen": "2023-02-15T21:51Z",
            "manufacturername": "_TZE200_m9skfctm",
            "modelid": "TS0601",
            "name": "Fire 22",
            "swversion": null,
            "type": "ZHAFire",
            "uniqueid": "a4:c1:38:b3:eb:2a:c7:e9-01-ef00"
        },
        "e": "changed",
        "id": "22",
        "r": "sensors",
        "t": "event",
        "uniqueid": "a4:c1:38:b3:eb:2a:c7:e9-01-ef00"
    }
}
```
                   
In the DDF it shows:
```
name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
```
I don´t see a script file "tuya_swversion.js" in my Home dir. Could that be a problem?

**Comment by BabaIsYou** [comment]
> Could that be a problem?

It shouldn't. You can make a copy of /usr/share/deCONZ/devices/tuya/tuya_swversion.js to the same folder of your DDF if you want to be sure, but IFIAK it doesn't really matter.

> How do I get the log info you requested :"get some log with just INFO and DDF checked ? it's sufficient to get DDF evals and Tuya request/response ?"

In fact you already gave it previously [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6734#issuecomment-1429523314). Can you propuce it again with just INFO and DDF checked ?
![image](https://user-images.githubusercontent.com/85300265/219395485-e1c7c6f3-1baf-49e5-b844-3873bd27c311.png)

**Comment by BabaIsYou** [comment]
To be very honest, I based my DDF on other plateform information (ie : https://github.com/Koenkk/zigbee-herdsman-converters/commit/1ca479c45e804eb6827cc2bac912ec0091be71d2) but I have some doubt about what does `tuya.valueConverter.true0ElseFalse` function means. 
Could it be that it is mine that is faulty and that the default correct value would be 1 instaed of 0 ?

**Comment by Bernhard-Bodensee** [comment]
Thanks a lot for your great support and fast replies - and the patience with me...

Step by step - I hope I am not presenting this in a too confusing way. My simple observation:

1. Tuya version still wrong even after copying tuya_swversion.js into $HOME and .local...device where the DDF resides. But that is not the main problem. Lets forget about that.

2. This is the debug view with "eval": "Item.val = (Attr.val == 1);",like in the master DDF-file,  after insertion of battery (shows the dpid 0x01 =1 for true)
```
18:58:28:184 Bind response success for 0x60a423fffe118350 ep: 0x0B cluster: 0x0006
18:58:28:239 ZCL configure reporting rsp seq: 64 0x60A423FFFE118350 for ep: 0x0B cluster: 0x0006 attr: 0x0000 status: 0x00
18:58:47:491 DeviceAnnce of SensorNode: 0xA4C138B3EB2AC7E9 [1]
18:58:49:179 Bind response success for 0x60a423fffe118350 ep: 0x0B cluster: 0x0006
18:58:49:180 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x60A423FFFE118350 (seems to be active)
18:58:52:142 TY_DATA_REPORT: seq 93, dpid: 0x65, type: 0x01, length: 1, val: 0
18:58:52:143 TY_DATA_REPORT: seq 93, dpid: 0x65, type: 0x01, length: 1, val: 0
18:58:52:143 TY_DATA_REPORT: seq 93, dpid: 0x65, type: 0x01, length: 1, val: 0
18:58:52:144 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> false
18:58:52:145 TY_DATA_REPORT: seq 93, dpid: 0x65, type: 0x01, length: 1, val: 0
18:58:52:286 TY_DATA_REPORT: seq 94, dpid: 0x01, type: 0x04, length: 1, val: 1
18:58:52:287 TY_DATA_REPORT: seq 94, dpid: 0x01, type: 0x04, length: 1, val: 1
18:58:52:288 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/fire expression: Item.val = (Attr.val == 1); --> true
18:58:52:289 TY_DATA_REPORT: seq 94, dpid: 0x01, type: 0x04, length: 1, val: 1
18:58:52:290 TY_DATA_REPORT: seq 94, dpid: 0x01, type: 0x04, length: 1, val: 1
18:58:52:410 TY_DATA_REPORT: seq 95, dpid: 0x02, type: 0x02, length: 4, val: 0
18:58:52:411 TY_DATA_REPORT: seq 95, dpid: 0x02, type: 0x02, length: 4, val: 0
18:58:52:411 TY_DATA_REPORT: seq 95, dpid: 0x02, type: 0x02, length: 4, val: 0
18:58:52:412 TY_DATA_REPORT: seq 95, dpid: 0x02, type: 0x02, length: 4, val: 0
18:58:52:553 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 84
18:58:52:553 TY_DATA_REPORT: seq 96, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:58:52:554 TY_DATA_REPORT: seq 96, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:58:52:555 TY_DATA_REPORT: seq 96, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:58:52:555 TY_DATA_REPORT: seq 96, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:58:52:676 TY_DATA_REPORT: seq 97, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:58:52:677 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/errorcode expression: Item.val = String(Attr.val); --> false
18:58:52:678 TY_DATA_REPORT: seq 97, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:58:52:678 TY_DATA_REPORT: seq 97, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:58:52:679 TY_DATA_REPORT: seq 97, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:58:52:830 ZCL attribute report 0xA4C138B3EB2AC7E9 for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
18:58:52:849 ZCL attribute report 0x60A423FFFE118350 for cluster: 0x0006, ep: 0x0B, frame control: 0x18, mfcode: 0x0000 
18:59:57:707 0x60a423fffe118350 found group 0xFFF0
18:59:57:708 0x60a423fffe118350 found group 0x0001
18:59:58:454 0xec1bbdfffeaed1f8 found group 0xFFF0
18:59:58:455 0xec1bbdfffeaed1f8 found group 0x0001
```
3. This is the debug view with "eval": "Item.val = (Attr.val == 0);",  as you recommended in your last posting, after insertion of battery (shows the dpid 0x01 =1 for true), same as above. Dont be confused by the system time shown, I tried that first
```
18:52:36:267 DeviceAnnce of SensorNode: 0xA4C138B3EB2AC7E9 [1]
18:52:40:944 TY_DATA_REPORT: seq 119, dpid: 0x65, type: 0x01, length: 1, val: 0
18:52:40:945 TY_DATA_REPORT: seq 119, dpid: 0x65, type: 0x01, length: 1, val: 0
18:52:40:946 TY_DATA_REPORT: seq 119, dpid: 0x65, type: 0x01, length: 1, val: 0
18:52:40:947 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> false
18:52:40:948 TY_DATA_REPORT: seq 119, dpid: 0x65, type: 0x01, length: 1, val: 0
18:52:41:088 TY_DATA_REPORT: seq 120, dpid: 0x01, type: 0x04, length: 1, val: 1
18:52:41:090 TY_DATA_REPORT: seq 120, dpid: 0x01, type: 0x04, length: 1, val: 1
18:52:41:092 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/fire expression: Item.val = (Attr.val == 0); --> false
18:52:41:093 TY_DATA_REPORT: seq 120, dpid: 0x01, type: 0x04, length: 1, val: 1
18:52:41:094 TY_DATA_REPORT: seq 120, dpid: 0x01, type: 0x04, length: 1, val: 1
18:52:41:219 TY_DATA_REPORT: seq 121, dpid: 0x02, type: 0x02, length: 4, val: 0
18:52:41:220 TY_DATA_REPORT: seq 121, dpid: 0x02, type: 0x02, length: 4, val: 0
18:52:41:221 TY_DATA_REPORT: seq 121, dpid: 0x02, type: 0x02, length: 4, val: 0
18:52:41:221 TY_DATA_REPORT: seq 121, dpid: 0x02, type: 0x02, length: 4, val: 0
18:52:41:349 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 84
18:52:41:350 TY_DATA_REPORT: seq 122, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:52:41:351 TY_DATA_REPORT: seq 122, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:52:41:353 TY_DATA_REPORT: seq 122, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:52:41:354 TY_DATA_REPORT: seq 122, dpid: 0x0F, type: 0x02, length: 4, val: 84
18:52:41:583 TY_DATA_REPORT: seq 123, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:52:41:584 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/errorcode expression: Item.val = String(Attr.val); --> false
18:52:41:584 TY_DATA_REPORT: seq 123, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:52:41:585 TY_DATA_REPORT: seq 123, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:52:41:585 TY_DATA_REPORT: seq 123, dpid: 0x0B, type: 0x01, length: 1, val: 0
18:52:41:710 ZCL attribute report 0xA4C138B3EB2AC7E9 for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
18:53:04:640 GW firmware version is up to date: 0x26780700
18:53:15:136 00:15:8d:00:07:df:92:f1-01-0405/config/battery expression: const vmin = 2700;
const vmax = 3000;
var bat = Attr.val;

if      (bat > vmax) { bat = vmax; }
else if (bat < vmin) { bat = vmin; }

bat = ((bat - vmin) /(vmax - vmin)) * 100;
```

4. debug-view when test button is pressed does not show any dpi 0x01 items
```
18:33:23:901 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 92
18:33:23:902 TY_DATA_REPORT: seq 98, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:23:903 TY_DATA_REPORT: seq 98, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:23:904 TY_DATA_REPORT: seq 98, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:23:905 TY_DATA_REPORT: seq 98, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:24:137 TY_DATA_REPORT: seq 99, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:24:137 TY_DATA_REPORT: seq 99, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:24:138 TY_DATA_REPORT: seq 99, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:24:139 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> true
18:33:24:140 TY_DATA_REPORT: seq 99, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:25:590 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 92
18:33:25:591 TY_DATA_REPORT: seq 100, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:25:592 TY_DATA_REPORT: seq 100, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:25:593 TY_DATA_REPORT: seq 100, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:25:594 TY_DATA_REPORT: seq 100, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:25:723 TY_DATA_REPORT: seq 101, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:25:725 TY_DATA_REPORT: seq 101, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:25:725 TY_DATA_REPORT: seq 101, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:25:727 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> true
18:33:25:727 TY_DATA_REPORT: seq 101, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:27:145 ZCL attribute report 0xEC1BBDFFFEAED1F8 for cluster: 0x0006, ep: 0x0B, frame control: 0x18, mfcode: 0x0000 
18:33:28:478 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 92
18:33:28:479 TY_DATA_REPORT: seq 102, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:28:480 TY_DATA_REPORT: seq 102, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:28:481 TY_DATA_REPORT: seq 102, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:28:482 TY_DATA_REPORT: seq 102, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:28:603 TY_DATA_REPORT: seq 103, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:28:604 TY_DATA_REPORT: seq 103, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:28:605 TY_DATA_REPORT: seq 103, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:28:605 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> true
18:33:28:606 TY_DATA_REPORT: seq 103, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:31:358 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 92
18:33:31:359 TY_DATA_REPORT: seq 104, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:31:359 TY_DATA_REPORT: seq 104, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:31:360 TY_DATA_REPORT: seq 104, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:31:360 TY_DATA_REPORT: seq 104, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:31:489 TY_DATA_REPORT: seq 105, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:31:491 TY_DATA_REPORT: seq 105, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:31:492 TY_DATA_REPORT: seq 105, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:31:494 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> true
18:33:31:496 TY_DATA_REPORT: seq 105, dpid: 0x65, type: 0x01, length: 1, val: 1
18:33:34:242 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/config/battery expression: Item.val = Attr.val; --> 92
18:33:34:243 TY_DATA_REPORT: seq 106, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:34:245 TY_DATA_REPORT: seq 106, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:34:246 TY_DATA_REPORT: seq 106, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:34:248 TY_DATA_REPORT: seq 106, dpid: 0x0F, type: 0x02, length: 4, val: 92
18:33:34:595 TY_DATA_REPORT: seq 107, dpid: 0x65, type: 0x01, length: 1, val: 0
18:33:34:596 TY_DATA_REPORT: seq 107, dpid: 0x65, type: 0x01, length: 1, val: 0
18:33:34:597 TY_DATA_REPORT: seq 107, dpid: 0x65, type: 0x01, length: 1, val: 0
18:33:34:598 a4:c1:38:b3:eb:2a:c7:e9-01-ef00/state/test expression: Item.val = Attr.val; --> false
18:33:34:599 TY_DATA_REPORT: seq 107, dpid: 0x65, type: 0x01, length: 1, val: 0
18:33:38:451 ZCL attribute report 0x60A423FFFE118350 for cluster: 0x0006, ep: 0x0B, frame control: 0x18, mfcode: 0x0000 
18:34:59:640 GW firmware version is up to date: 0x26780700
18:36:28:690 ZCL attribute report 0xEC1BBDFFFEAED1F8 for cluster: 0x0006, ep: 0x0B, frame control: 0x18, mfcode: 0x0000 
18:38:41:322 ZCL attribute report 0x60A423FFFE118350 for cluster: 0x0006, ep: 0x0B, frame control: 0x18, mfcode: 0x0000 
18:38:59:637 GW firmware version is up to date: 0x26780700
18:39:30:248 ZCL attribute report 0xEC1BBDFFFEAED1F8 for cluster: 0x0006, ep: 0x0B, frame control: 0x18, mfcode: 0x0000 
```

**Comment by Bernhard-Bodensee** [comment]
I did the above without pairing again - just restarted deconz. Is that sufficient?
From my understanding a DDF change is active when either "Hot reload" is pressed or after restart of deconz.
I hate to run into problems of many renumberings and running out of numbers - if that is a real problem?

**Comment by Bernhard-Bodensee** [comment]
I think I got the solution, in addition to setting value you need to change default to 1 - then it works.
I am testing now... found no problem so far.

```
          "name": "state/fire",
          "awake": true,
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 1,
            "eval": "Item.val = (Attr.val == 0);",
            "fn": "tuya"
          },
          "default": true
        },
```

**Comment by Bernhard-Bodensee** [comment]
I think we entered our comments at the same time. 
Problem solved as I mentioned above with
Attr.val == 0
and
default": true

Strange, normal people would think 1 if fire - but in fact for tuya 0 seems to be fie alarm.
Regardsless of my understanding:
I tested that solution with the 2 devices I got. 
When I hit test, alarm goes on and is displayed on all Home Apps as Notification (iPhone, iPad, Mac).
Homebridge still has that warning as mentioned but that can be disregarded.
Phoscon shows the correct values in API-Info and alerts - when test is pressed it shows both, fire and test are true.
When the device is ling it shows both as false.

Thanks a lot for your great support. Greetings from the Lake of Constance

**Comment by BabaIsYou** [comment]
> in fact for tuya 0 seems to be fie alarm.

Yes for this kind of device it seems to be that way internaly, but for HA systems,  fire race is when fire attribute is true. That's why I think that default to true seems very weird.

**Comment by Bernhard-Bodensee** [comment]
I will try your settings tomorrow and get back to you.
```
Could you try this other formula and keep "default": false ?
"eval": "Item.val = (Attr.val == 0 ? true : false);",
```

**Comment by Bernhard-Bodensee** [comment]
works. No problems found. Tested essential funktions (idle, alarm, battery change), everything fine.

Looks probably better than default =true
If I understand your fix it looks like a workaround for the stupid device reaction ? if Attr.val is false set to true!
Let me know if you need any more analysis data.

**Comment by BabaIsYou** [comment]
Many thx 🙏 
PR updated
