### ISSUE TITLE
Lidl HG06338 still switches all plugs on at once

### ISSUE THREAD

**Issue by programmieramt** [dresden-elektronik/deconz-rest-plugin#6737]
## Describe the bug
When adding the Lidl HG06338 device is added it is only discovered as one plug and every plug is controlled together

## Steps to reproduce the behavior
 I have two new devices here and both have the same behaviour. All 3 plugs are controlled together

## Expected behavior
  Every plug outlet should be controlled individually 

## Environment
2.20.01 / 19.9.2022
26780700

## Additional context
it is this device:
https://www.zigbee2mqtt.io/devices/HG06338.html
-->
It is also covered by this bug: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5493 but it was closed

**Comment by BabaIsYou** [comment]
And what more do you expect by opening this query than what is already covered by #5493 ?

**Comment by programmieramt** [comment]
> And what more do you expect by opening this query than what is already covered by #5493 ?

mmmh the other one is closed and I found no way to reopen it. So I assume no one will work on it.

**Comment by Mimiix** [comment]
> > And what more do you expect by opening this query than what is already covered by #5493 ?
> 
> mmmh the other one is closed and I found no way to reopen it. So I assume no one will work on it. We can close this one if you offer a way to reopen the old one.

You did what we always ask users to do: Ping in there and ask for a reopen.

However, you can't expect that we reply within 3 hours.

Closing.

**Comment by Mimiix** [comment]
> thank for the answer. I was not aware that I post in a closed issue someone will be notified. Sorry for that.
> 
> Thanks for the quick answer anyway.

No worries :)

I get emails of everything. I normally check a few times a day.
