### ISSUE TITLE
Lonsonho 16A plug  _TZ3000_dksbtrzs

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#6743]
## Device

- Product name: Lonsonho 16A plug
- Manufacturer:  _TZ3000_dksbtrzs
- Model identifier: TS011F
- Device type : Please remove all unrelated device types. 
  - Light (plug)
  - Sensor (power/consumption/voltage)
 
Light/Plug infor is in the JSON. The sensor information for power is missing.

## Screenshots

![image](https://user-images.githubusercontent.com/30700296/218278603-de8fb5f2-6d4b-4a7d-b17c-8c9f02c7ab95.png)

![image](https://user-images.githubusercontent.com/30700296/218278631-00b85f4f-8d30-4706-adb0-47ffb12dadbd.png)

Basic info part 1
![image](https://user-images.githubusercontent.com/30700296/218278680-052f442c-54b9-44f0-883c-398ef791cdcc.png)
Basic info part 2
![image](https://user-images.githubusercontent.com/30700296/218278776-a2daa29e-b287-4a56-b517-8911abd26e1d.png)

Identify
![image](https://user-images.githubusercontent.com/30700296/218278802-1328d412-14aa-4f6f-adc8-7664a231f13a.png)

Groups
![image](https://user-images.githubusercontent.com/30700296/218278827-7f187f7a-ccf3-4e44-824f-cff046b4be58.png)

Scenes
![image](https://user-images.githubusercontent.com/30700296/218278862-8864e77d-b6ba-4121-9108-c09e54200353.png)

On/Off
![image](https://user-images.githubusercontent.com/30700296/218278883-6219e899-8df6-4ce2-b4c1-0865e9f2c781.png)

Simple Metering 
![image](https://user-images.githubusercontent.com/30700296/218278932-0b4855c7-ff0c-4bc6-9832-c007d1e9710e.png)

Electrical Measurement part 1
![image](https://user-images.githubusercontent.com/30700296/218278993-84048790-0b55-45a6-8783-aeda2a50650f.png)

Electrical Measurement part 2
![image](https://user-images.githubusercontent.com/30700296/218279036-c09b96bc-3419-4ad1-84c0-f22f65aba6e4.png)

E000 Unknown and empty
E001 Unknown and empty

OTAU
![image](https://user-images.githubusercontent.com/30700296/218279100-2fd2ac59-4d07-46ce-b1d0-bc77a4f5b0d4.png)

**Comment by BabaIsYou** [comment]
Try to create a DDF file from this [DDF](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/lonsonho/_TZ3000_okaz9tjs_plug.json) one after changing theses lines 
```
  "manufacturername": "_TZ3000_okaz9tjs",
  "modelid": "TS011F",
  "product": "Smart US Plug 20A Power Monitor",
```
By these : 

```
  "manufacturername": ["_TZ3000_okaz9tjs", " _TZ3000_dksbtrzs "],
  "modelid": ["TS011F", "TS011F"],
  "product": "Smart US Plug Power Monitor",
```

**Comment by wvuyk** [comment]
I tested it and could not get it at work first. Once I replaced the existing file in the devices\lonsonho directory it started working for me. This was on a Windows installation, does the temporary install not work for Windows?  Net very importatn, the file works!

This what I am having at this moment (also changed the product name as this plug is for the EU:

`{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_okaz9tjs", " _TZ3000_dksbtrzs "],
  "modelid": ["TS011F", "TS011F"],
  "product": "Smart Plug Power Monitor",
  "vendor": "Lonsonho",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0B04"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "read": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val"
          },
          "refresh.interval": 100
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "read": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val"
          },
          "refresh.interval": 100
        },
        {
          "name": "state/voltage",
          "read": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val"
          },
          "refresh.interval": 100
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0702"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "read": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "eval": "Item.val = Attr.val * 10"
          },
          "refresh.interval": 10
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}`

**Comment by BabaIsYou** [comment]
> This was on a Windows installation, does the temporary install not work for Windows?
It’s supposed to work also… may be not in the right directory ?

BTW if the DDF works could you do a PR to be included in a next release ? Also I can do it for you.

**Comment by wvuyk** [comment]
If you could do this, it would be a great help... I do not really know mucht about the PR's I have to confess :-)

Thanks,
Wim

**Comment by BabaIsYou** [comment]
I’ll do it in a few hours ;-)

Le 12 févr. 2023 à 15:38, Wim ***@***.***> a écrit :

﻿

If you could do this, it would be a great help... I do not really know mucht about the PR's I have to confess :-)

Thanks,
Wim

**Comment by BabaIsYou** [comment]
Done !
