### ISSUE TITLE
Smart Plug Gen2

### ISSUE THREAD

**Issue by Jacksonbm1** [dresden-elektronik/deconz-rest-plugin#6747]
## Device

I'm specifically trying to get power monitoring values

- Product name: Smart Plug Gen2
- Manufacturer: Third Reality, Inc
- Model identifier: 3RSP02028BZ
- Device type : Please remove all unrelated device types. 
  - Light
  - Other:  Not fully sure, I didn't see instructions on where to get this, but it's a smart plug

## Screenshots

  Required screenshots:
![image](https://user-images.githubusercontent.com/39594156/218881505-10558ec2-7844-4ef5-a637-b550da0bd5f5.png)

### Basic

![image](https://user-images.githubusercontent.com/39594156/218881780-0d9882e3-864f-41d3-b86f-e9f018573323.png)

### Identify

![image](https://user-images.githubusercontent.com/39594156/218882234-43f1e258-4b43-424d-8d79-f8f91760730d.png)

### Groups

![image](https://user-images.githubusercontent.com/39594156/218882312-28f1a643-8917-4755-acf3-11982c3e98d1.png)

![image](https://user-images.githubusercontent.com/39594156/218882338-a75f9f0a-d2d0-4f0e-a0c2-cee5116d52a9.png)

### Scenes

![image](https://user-images.githubusercontent.com/39594156/218882464-bf86f593-acda-4770-91fa-d483cdb6a04e.png)
![image](https://user-images.githubusercontent.com/39594156/218882499-2d67fb09-e6e7-438a-94ec-a389ce78694c.png)
![image](https://user-images.githubusercontent.com/39594156/218882538-d8bd734d-d2eb-4a12-b1ff-febd330d3a7e.png)
![image](https://user-images.githubusercontent.com/39594156/218882574-f8baff92-1279-4579-a795-e913afc309f2.png)

### On/Off

![image](https://user-images.githubusercontent.com/39594156/218882606-c72ac8ed-703e-4c66-a94c-edb01e98cfe1.png)

![image](https://user-images.githubusercontent.com/39594156/218882633-8e3241b5-f471-4188-b1e3-bf71edfbaf3d.png)

### Other clusters that are not mentioned above

![image](https://user-images.githubusercontent.com/39594156/218881528-90ace94c-b827-47eb-9dc5-e49d76f9bc00.png)

![image](https://user-images.githubusercontent.com/39594156/218882688-b3f3c831-2715-4341-a541-94eafee7b4b3.png)

![image](https://user-images.githubusercontent.com/39594156/218882714-758162ac-f28e-4383-9dc9-2bf570e12640.png)

**Comment by BabaIsYou** [comment]
Could you please redo the screenshots after clicking on [read] button on each to gather values and supported attributes ?

**Comment by Jacksonbm1** [comment]
oops:

Basic
![image](https://user-images.githubusercontent.com/39594156/219034642-8e412592-0d02-405b-bdda-ee0578710d26.png)

Identify:

![image](https://user-images.githubusercontent.com/39594156/219034726-1df76662-3dd2-4a18-ab25-29fe02483fa9.png)

Groups:

![image](https://user-images.githubusercontent.com/39594156/219034826-c45c92f8-983b-4cd9-845c-af580b7ccf68.png)

Scenes:

![image](https://user-images.githubusercontent.com/39594156/219034895-b98b350c-c981-4023-a906-da7a661c19ba.png)

On/Off

![image](https://user-images.githubusercontent.com/39594156/219034996-fd053575-cbff-4201-9f38-c7175c9a25ff.png)

(Rest of image)
![image](https://user-images.githubusercontent.com/39594156/219035062-ac4b8178-a83e-434f-a1a4-21eac5bcba8c.png)

Electrical Measurement:

![image](https://user-images.githubusercontent.com/39594156/219035248-0719f2fb-52e7-4a76-8e1a-427a37b7065f.png)
(rest of image)
![image](https://user-images.githubusercontent.com/39594156/219035299-0dee49aa-a2ef-47ce-b940-4fb81117f48f.png)

OTAU
![image](https://user-images.githubusercontent.com/39594156/219035370-4087abaf-7819-4d8d-889b-4a4a3aea1c01.png)
(Rest of image)
![image](https://user-images.githubusercontent.com/39594156/219035455-f0b2828c-af51-4676-83b2-328dc6f4f3e7.png)

**Comment by Smanar** [comment]
Hello can you try this DDF ? Di you know how to use them ?

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Third Reality, Inc",
  "modelid": "3RSP02028BZ",
  "vendor": "Third Reality",
  "product": "Smart plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "read": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "read": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 360
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 10,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

The tension is strange 124 V ?
It seem this device don't support consumption ?

**Comment by BabaIsYou** [comment]
I guess that voltage is more 1204 / 10 (attr 0x0601) then 120.4 ;-)

**Comment by SwoopX** [comment]
Haven't we had the issue here that the comma in the manufacturer name wasn't playing nicely (data is read into a string list with comma as separator)? Could be that the `, Inc` must be skipped?

**Comment by BabaIsYou** [comment]
> Could be that the `, Inc` must be skipped?

We already have it an already existing DDF from this manufacturer : [https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/third_reality/3RMS16BZ_motion_sensor.json](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/third_reality/3RMS16BZ_motion_sensor.json)

**Comment by Jacksonbm1** [comment]
"Hello can you try this DDF ? Di you know how to use them ?"

Sorry, I don't! Could you link documentation on what to do here?

**Comment by Smanar** [comment]
> Haven't we had the issue here that the comma in the manufacturer name wasn't playing nicely (data is read into a string list with comma as separator)? Could be that the `, Inc` must be skipped?

It happen if you use the editor if you set "Third Reality, Inc" as manufacture name you will in DDF ["Third Reality", "Inc"], but no problem if you use a text editor.

>Sorry, I don't! Could you link documentation on what to do here?

What if your OS ? To resume you just need to create a text file called what_youy_want.json in a "devices" folder.

> All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

For classic OS
If you have HA > https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839
If you have the offical docker, there is too a persistant folder.

**Comment by Jacksonbm1** [comment]
Ok I think I understand, so Just create a json file in my the deconz/devices directory? Does it have to have any special naming convention? What do I do after that? I haven't noticed any changes to the device.

**Comment by BabaIsYou** [comment]
> For the tension 120 V is still strange

It's a US plug then voltage is 120V ;-)

**Comment by BabaIsYou** [comment]
> Ok I think I understand, so Just create a json file in my the deconz/devices directory? Does it have to have any special naming convention? What do I do after that? I haven't noticed any changes to the device.

Under `/home//.local/share/dresden-elektronik/deCONZ/devices` or under `/usr/share/deCONZ/devices/` then delete and re-pair the device or restart DeCONZ. If DDF is correctly loaded values will be populated accordingly, and you could see modify DDF from DDF editor

**Comment by sadpixel** [comment]
I own several of these new devices, and can confirm that the DDF above is working! =D

What's the process for getting it included by default in future releases of Deconz?

**Comment by Smanar** [comment]
So convertion are fine ?
You can make a PR with the DDF or ask for someone make it (here) if you can't.

**Comment by Jacksonbm1** [comment]
I've been trying to make sure my network is stable rn, but thanks for doing that @sadpixel. If the PR makes it through, does it automatically get updated on our end or do we need to get a software update pushed through?

**Comment by Smanar** [comment]
If the PR is done (and valided) it will be in official version so nothing more to do.
I just need to know if you want to make the PR yourself or if you want I make it ^^ ?

**Comment by Jacksonbm1** [comment]
Interestingly, it looks like the values are being populated already. Does that mean it's been submitted as a PR already? if not, it would be super helpful if you could!

**Comment by Smanar** [comment]
>Interestingly, it looks like the values are being populated already

It's because you are using the DDF ?

PR done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6768
