### ISSUE TITLE
Wattle Door Lock SPL Smart

### ISSUE THREAD

**Issue by Gyldenlow** [dresden-elektronik/deconz-rest-plugin#6749]
- Product name: Wattle Door Lock SPL Smart
- Manufacturer: Home Control AS
- Model identifier: HC-SLM-1
- Device type :
  - Lock

### Basic

![image](https://user-images.githubusercontent.com/82686261/219127849-b81a7a4f-9e6a-475b-b19b-b8558f8495ee.png)

### Power Configuration

![image](https://user-images.githubusercontent.com/82686261/219127916-1118bdea-0f5e-4108-be8d-93c5ff06aeec.png)

### Identify 

![image](https://user-images.githubusercontent.com/82686261/219128092-3eb425fe-c879-4123-9aab-d19547bb6700.png)

### Door lock 
![image](https://user-images.githubusercontent.com/82686261/219128683-796a4051-5fbd-40a4-90d7-9318d3bff1bf.png)

### Node Info 

![image](https://user-images.githubusercontent.com/82686261/219128897-31bdc107-0e07-46aa-a547-eb287474438d.png)

**Comment by Gyldenlow** [comment]
@Smanar This is funny, I found that exact code you posted on another issue only 10 mins ago, and got my lock working 2 mins before reading this! Happy to report that it works :) For any future readers - after hot reloading you need to remove and re-insert the batteries for it to update in Home Assistant.

**Comment by Smanar** [comment]
Lol, so the working mode is ok, can make a PR ? (or if you want to make it ?)

**Comment by Gyldenlow** [comment]
Yes, you can make a PR. I am very new to this (and I dont know how to do it)

**Comment by Smanar** [comment]
Done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6754
