### ISSUE TITLE
3A Smart Home LXN-2S27LX1.0 Shutter Control

### ISSUE THREAD

**Issue by Febus123** [dresden-elektronik/deconz-rest-plugin#6750]
## Device

- Product name: 3A Shutter Control
- Manufacturer: 3A Smart Home DE
- Model identifier: LXN-2S27LX1.0
- Device type : Please remove all unrelated device types. 
  - Other: Window Covering Device (Generic Device Type "Unspecified")

## Screenshots

![image](https://user-images.githubusercontent.com/7365097/219148900-a90b7634-2e9f-48b5-b78b-cedac2d8d5a3.png)
![image](https://user-images.githubusercontent.com/7365097/219149130-09caede2-2630-48b9-ba8f-dbe8edc9d5fa.png)

### Basic
![image](https://user-images.githubusercontent.com/7365097/219149644-7fc72c17-f219-4ad2-bfcb-b1689ce18f5d.png)
![image](https://user-images.githubusercontent.com/7365097/219149757-d77e26b7-553a-443b-9363-e5dc7322b315.png)

### Identify
![image](https://user-images.githubusercontent.com/7365097/219153181-b889016b-32b7-42e1-82af-478a0b8e7a13.png)

### Alarms
./.
### Device Temperature
./.
### Groups
![image](https://user-images.githubusercontent.com/7365097/219153490-f10bb38a-e15d-4db3-adaa-5d287b328863.png)
![image](https://user-images.githubusercontent.com/7365097/219153567-e03e090a-694b-431e-8b85-48b4566d4e3e.png)
![image](https://user-images.githubusercontent.com/7365097/219153638-1a45cffc-6a1d-4114-90e5-281ae8c96061.png)

### Scenes
![image](https://user-images.githubusercontent.com/7365097/219154753-bc9224fc-d382-41d6-bf16-e6ef9c4cbdb5.png)
![image](https://user-images.githubusercontent.com/7365097/219154863-2a699299-6b44-461e-943a-bd06efc53dbf.png)
![image](https://user-images.githubusercontent.com/7365097/219155007-8690cafd-551b-411a-8af2-8b1bdbdab850.png)
![image](https://user-images.githubusercontent.com/7365097/219155169-d2b2c1e8-243b-448b-8c2f-1700de8afeb5.png)

### On/Off
![image](https://user-images.githubusercontent.com/7365097/219154062-34116697-101f-4f1c-a70b-6bfca0561a3c.png)
![image](https://user-images.githubusercontent.com/7365097/219154304-a3ad4553-00af-4123-83ec-f675470bf7a6.png)
![image](https://user-images.githubusercontent.com/7365097/219154436-a43bbb98-889d-4bc3-aff9-1476a005dc6a.png)

### Level Control
![image](https://user-images.githubusercontent.com/7365097/219151248-da295441-bc53-4b07-b62a-ef808d40d2bf.png)
![image](https://user-images.githubusercontent.com/7365097/219151509-e13e5596-39b6-4a98-ba80-8c388887c3c0.png)

### Color Control
./.
### Simple Metering
./.
### Diagnostics
./.
### Other clusters that are not mentioned above
![image](https://user-images.githubusercontent.com/7365097/219155416-38c9da3a-5268-4464-b006-555c28a89a36.png)
![image](https://user-images.githubusercontent.com/7365097/219155531-0e1536cc-7d85-4d3e-8143-373bbabc1a97.png)

### OTAU
![image](https://user-images.githubusercontent.com/7365097/219157560-54f4209c-40e6-44d7-b730-ae618ceb1729.png)
![image](https://user-images.githubusercontent.com/7365097/219157648-5dbdf7b5-a9ac-4204-87f1-96ef8adf2708.png)

**Comment by ebaauw** [comment]
It’s a controller, not a window covering device.  It looks like a wired switch with two outputs (presumably for up and down).  Since the device types on the endpoints are _On/Off Light_, I assume the _Level Control_ clusters are there merely to support _Move to Level (with On/Off)_, and they probably only report _Current Level_ at 0 or 254.  If so, it should be exposed as two on /off light `/lights` resources, without `state/bri`, rather than as two dimmable lights.

You cannot expose this as a window covering device, as it doesn’t seem to report the current position of the shutter.

**Comment by Smanar** [comment]
But it s not working natively, used a dimmable light ?

**Comment by Febus123** [comment]
It works when using the dimmable lights (as soon as one is above 0% it goes either up or down). I was hoping to get this somehow converted into a shadowing device. I managed to do this via FHEM (which calculates positions via timing) but would prefer to do this directly via deCONZ…
________________________________
Von: Smanar ***@***.***>
Gesendet: Thursday, February 16, 2023 6:09:35 PM
An: dresden-elektronik/deconz-rest-plugin ***@***.***>
Cc: Febus123 ***@***.***>; Author ***@***.***>
Betreff: Re: [dresden-elektronik/deconz-rest-plugin] 3A Smart Home LXN-2S27LX1.0 Shutter Control (Issue #6750)


But it s not working natively, used a dimmable light ?
