### ISSUE TITLE
Müller-Licht tint Remote control

### ISSUE THREAD

**Issue by twobeass** [dresden-elektronik/deconz-rest-plugin#6755]
## Device

- Product name: Müller-Licht tint Remote control (ArtNr 404011)
- Manufacturer: _TZ3000_bdbb0fon
- Model identifier: TS1001
- Device type :  Remote
 

## Screenshots
![image](https://user-images.githubusercontent.com/4639195/220474290-8f43bf07-8fb4-43b5-8c17-4ba1cf82b2a6.png)

### Basic
![image](https://user-images.githubusercontent.com/4639195/220474362-64d3b26c-6273-4c28-a473-dc8c9845d57a.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/4639195/220474398-02f5b50d-c66c-420f-ab78-acb0dd7777dd.png)

### Identify
![image](https://user-images.githubusercontent.com/4639195/220474565-fb0e9614-4c3a-41dd-ba3d-49951deece5a.png)

### Groups
![image](https://user-images.githubusercontent.com/4639195/220474638-9672a842-bad2-4703-bd1b-7d04ee8c831b.png)

### ZLL Commisioning
![image](https://user-images.githubusercontent.com/4639195/220474716-7ca4666a-ab4d-49d3-8360-f2f0efa5bc32.png)

### TUYA specific
![image](https://user-images.githubusercontent.com/4639195/220474795-e3c8c50a-71f9-46fb-882a-56710c09eaa9.png)

### Color Control
![image](https://user-images.githubusercontent.com/4639195/220476156-8160bc10-a569-4ca3-80c8-04ce2cd67ec6.png)
![image](https://user-images.githubusercontent.com/4639195/220475028-7ec5edb1-444c-415a-9ee8-2515131ae7e5.png)
![image](https://user-images.githubusercontent.com/4639195/220475113-a335ac65-cbae-4e17-921e-1582dddf71f6.png)
![image](https://user-images.githubusercontent.com/4639195/220475184-e9506b9b-9d28-4b31-a384-9431d0876016.png)
![image](https://user-images.githubusercontent.com/4639195/220475243-aceba308-7207-4101-a08b-2deae14bdd17.png)
![image](https://user-images.githubusercontent.com/4639195/220475281-af5b613a-a71a-4b68-8e7e-7ab71d989b7a.png)

### OTAU
![image](https://user-images.githubusercontent.com/4639195/220475397-1e40be0a-37e4-4e94-861c-855713c4d81a.png)

**Comment by BabaIsYou** [comment]
Just to be sure ... Did you click on "read" before Power Configuration screenshot ?

**Comment by twobeass** [comment]
I just double checked it and pressed „read power descriptor“ again! Still the same values… can i somehow provide more information ??

**Comment by twobeass** [comment]
Unwanted close on mobile device, sorry…

**Comment by BabaIsYou** [comment]
Screenshots seems more "normal" now ! It's normal that for a battery device you could have to read several time or play with buttons while you read to awake the device reporting.
Can you add also ZLL commissioning cluster screenshot ? I don't see it.
Thx

**Comment by twobeass** [comment]
![image](https://user-images.githubusercontent.com/4639195/220454809-0360ae97-fc74-4e7b-917f-873b480d9181.png)

sure i thought these informations are not necessary as there is a count of 0 in that cluster...

**Comment by twobeass** [comment]
I just updated my first post, as i recognized that there were a lot of values not written properly.. Thanks @BabaIsYou for pointing me in the right direction...

As i searched the logs i found out that there were missing button mappings:
`22:27:43:526 [INFO] - No button map for: TS1001, broadcast to: 0x0000, endpoint: 0x01, cluster: BASIC (0x0000), command: 0x02, payload: 05402001, zclSeq: 72`
i am hoping that this makes it easier to create a proper ddf.. if i could provide more information to you devs, just let me know...
