### ISSUE TITLE
Xiaomi Aqara relay controller lumi.relay.c2acn01 stopped working

### ISSUE THREAD

**Issue by monpelaud** [dresden-elektronik/deconz-rest-plugin#6757]
## Describe the bug

Hi,
For months I have been using an aqara llkzmk11lm wireless relay with the deCONZ plugin for HA.
Everything was working fine until deCONZ restarted after an HA core update.
Now this device appears in deCONZ but not in Phoscon and is no longer visible in HA.
In deCONZ UI the device is connected and everything works fine. No errors in deCONZ logs, communication with the RaspBee II module seems to work well.
But I no longer see the device in Phoscon and HA.
## Steps to reproduce the behavior

See discussion with @Smanar on Phoscon forum:
https://forum.phoscon.de/t/device-appear-in-deconz-but-not-in-phoscon/3298
## Expected behavior

DDF file proposed by @Smanar in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6512#issuecomment-1426980875 fixe this issue.
## Screenshots

![Capture1](https://user-images.githubusercontent.com/16806004/219963276-be492401-6ee0-4e3b-a184-bfb5a4ffa9c1.jpg)
![Capture2](https://user-images.githubusercontent.com/16806004/219963314-9bab7d5b-3eea-49a8-b341-a2b5323afc1e.jpg)
## Environment

 - Host system: Raspberry Pi
 - Running method: Home Assistant deCONZ Add-on
 - Firmware version: 26780700
 - deCONZ version: 2.20.1
 - Device: RaspBee II
 - Do you use an USB extension cable: No
 - Is there any other USB or serial devices connected to the host system?: No

**Comment by Smanar** [comment]
From the last logs from the phoscon forum, all seem working except current and power, perhaps you haven't load during your tests ?

And as you are seing event, it mean you have it in the API, so the device need to be visible on HA (Phoscon it's random).

**Comment by monpelaud** [comment]
The device is visible in Phoscon:
![Phoscon](https://user-images.githubusercontent.com/16806004/219968610-13b60e0a-6795-4477-bf35-81e19cea9b8d.JPG)
deCONZ Electrical_Measurement without load:
![Pompe_eteinte](https://user-images.githubusercontent.com/16806004/219968639-413c0467-fd90-4d02-b050-27cd98f1ccf0.JPG)
deconZ Electrical_Measurement in load:
![Pompe_allumee](https://user-images.githubusercontent.com/16806004/219968663-bb2f8076-0557-40f4-9832-6584d01c0c87.JPG)
It's the same !!!!

**Comment by SwoopX** [comment]
As this is obviously unrelated to the REST API, I'll close this issue. Feel free to debate any Phoscon or 3rd party related topics/issues in the forum.

**Comment by monpelaud** [comment]
@SwoopX, I don't understand why you closed my issue, if it's not a REST API issue what is it? Phoscon stops working and it works again with a new DDF file!
It's no longer works because REST API seems to no longer show data to Phoscon or HA. With the new DDF file REST API show again data to Phoscon and it's work again.
Is DDF file not in the code of deconz-rest-plugin?
