### ISSUE TITLE
TMZ-02 Mini a.k.a Tmz02L-16A-W ( Manu: _TZ3000_txpirhfq, Model: TS0011 )

### ISSUE THREAD

**Issue by elpablillo** [dresden-elektronik/deconz-rest-plugin#6762]
## Device

- Product name: TMZ-02 Mini / Tmz02L-16A-W
- Manufacturer: _TZ3000_txpirhfq
- Model identifier: TS0011
- Device type :
  - Switch

### Node Info panel
![image](https://user-images.githubusercontent.com/68110358/221409364-15091a80-f2e7-4bd4-ae6d-c440a323b5c0.png)

### Basic
![image](https://user-images.githubusercontent.com/68110358/221409215-8d33f89b-2506-40c0-807d-e8cf0d989a41.png)

### Identify
![image](https://user-images.githubusercontent.com/68110358/221409435-20b026a3-163a-4581-949f-cbac6ec8f796.png)

### Groups
![image](https://user-images.githubusercontent.com/68110358/221409552-ef025f81-8d7f-463f-a807-d6022db438bd.png)
![image](https://user-images.githubusercontent.com/68110358/221409557-27d6efcf-8d05-4043-bf17-a2d442f82c96.png)

### Scenes
![image](https://user-images.githubusercontent.com/68110358/221409635-b8b70579-218c-4eb1-b656-8efa9b74c46d.png)
![image](https://user-images.githubusercontent.com/68110358/221409637-c97324c0-72b9-4890-be77-f12aa1437993.png)
![image](https://user-images.githubusercontent.com/68110358/221409638-dfa9b2b9-fb51-4f4c-b3b3-15029d9fd47e.png)

### On/Off
![image](https://user-images.githubusercontent.com/68110358/221409686-ae9ddc33-877d-4392-b336-ca6957abd542.png)
![image](https://user-images.githubusercontent.com/68110358/221409693-4f134f6d-f429-4fde-a733-c80ed18a1000.png)

**Comment by Smanar** [comment]
Hello, can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_txpirhfq","_TZ3000_qmi1cfuq", "_TZ3000_ji4araar"],
  "modelid": ["TS0011", "TS0011", "TS0011"],
  "product": "1 gang switch module without neutral",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "refresh.interval": 86400,
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by elpablillo** [comment]
Hi, I use HassOS... so that part to copy and paste it is complicated... but I was able to create using DDF aditor. 
![image](https://user-images.githubusercontent.com/68110358/221417617-ecc84742-f441-43af-9341-18e065de648b.png)
I have removed the other manufacturername "_TZ3000_qmi1cfuq", "_TZ3000_ji4araar", because in the preview, it didn't look same as you. 
![image](https://user-images.githubusercontent.com/68110358/221417942-c5648d6b-dcae-43ba-a60a-ac33498117e5.png)


After the "Hot reload" and reloading the integration... the device is shown into HA 
![image](https://user-images.githubusercontent.com/68110358/221417879-93ff46b3-9360-4d89-a98e-5b58457c968c.png)

**Comment by Smanar** [comment]
And all is working ? No need binding/report ?

(Just for information, you have a special folder to put DDF on deconz plugin docker on HA, but I m agree, not easy)

**Comment by elpablillo** [comment]
Yes, all is working... this kind of switch it is quite simple just on/off, no need binding. I've just done a hardware reboot of the Raspberry... it's still woking 😀 and taking the .json from the folder: 
![image](https://user-images.githubusercontent.com/68110358/221424679-f032c8c9-7826-44d6-9233-8840366d0ea6.png)

**Comment by Smanar** [comment]
Ok, have made a PR with the 2 clones https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6764
