### ISSUE TITLE
ShenZhen_Homa 0301 HMS823

### ISSUE THREAD

**Issue by crx-michi** [dresden-elektronik/deconz-rest-plugin#6765]
## Device

- Product name: HMS823-Z-XX-WP-OTA-3.0
- Manufacturer: ShenZhen_Homa
- Model identifier: HOMA0301
- Device type :
  - Sensor

### Basic
<img width="960" alt="Basic Cluster" src="https://user-images.githubusercontent.com/118632334/221430232-40e641ff-64a5-41fd-9397-0cbe39d15afa.png">

### Identify
<img width="960" alt="Identify Cluster" src="https://user-images.githubusercontent.com/118632334/221430262-b94184a9-4d18-49d7-ba3c-215d335ad03b.png">

### Scenes

<img width="960" alt="Scenes Cluster" src="https://user-images.githubusercontent.com/118632334/221430382-dd05b1c6-d7a7-4bd1-a853-e53257747f84.png">

### On/Off
<img width="960" alt="on off cluster" src="https://user-images.githubusercontent.com/118632334/221430399-d293710c-790b-4fac-9cd0-8f26160064d1.png">

### Other clusters that are not mentioned above
<img width="960" alt="Green Power Cluster" src="https://user-images.githubusercontent.com/118632334/221430416-a1b0bfba-3919-4ce8-9f4e-11c87ee0ade6.png">

[HMS823-Z-XX-WP-OTA-3 0 specification.pdf](https://github.com/dresden-elektronik/deconz-rest-plugin/files/10834469/HMS823-Z-XX-WP-OTA-3.0.specification.pdf)

**Comment by BabaIsYou** [comment]
Hi. Can you please complete cluster screenshots with Groups and Illuminance ? 
And be sure to click on "read" button before taking screenshots.

Thx

**Comment by crx-michi** [comment]
Hi,

thanks for your answer, her are the screenshots from group and illuminance, but its only a motion sensor without illuminance measurement.

hope this helps - Thanks a lot!
![Groups Cluster](https://user-images.githubusercontent.com/118632334/221955225-f3aeba37-0909-4066-962f-8e8f6477447a.png)
![Illuminance Cluster](https://user-images.githubusercontent.com/118632334/221955238-dd844aef-f406-4a15-9ae6-de34eebeede6.png)

**Comment by BabaIsYou** [comment]
Seems weird that a motion sensor doesn't contains relative cluster and that it contains illuminance measurement if it's not that type of sensor. In addition, hope that it's not using 0xFFEE specific cluster.

Can you try this DDF BTW, but would be surprise it works. May be we need some log after that.

{
  "schema": "devcap1.schema.json",
  "manufacturername": "ShenZhen_Homa",
  "modelid": "HOMA0301",
  "vendor": "ShenZhen HOMA Technology Co",
  "product": "HMS823",
  "status": "Silver",
  "sleeper": true,
  "subdevices": [
    {
      "type": "$TYPE_LIGHT_LEVEL_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0400"
      ],
      "items": [
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/tholddark"
        },
        {
          "name": "config/tholdoffset"
        },
        {
          "name": "state/lightlevel"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "state/dark"
        },
        {
          "name": "state/daylight"
        },
        {
          "name": "state/lux"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_PRESENCE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0406"
      ],
      "items": [
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/presence"
        },
        {
          "name": "config/battery"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
