### ISSUE TITLE
Associate Off and transitiontime

### ISSUE THREAD

**Issue by OUARZA** [dresden-elektronik/deconz-rest-plugin#6766]
Hello

## Describe the bug
I see that it is possible to associate an Off command with the transitiontime parameter on a group but not on a light directly.
Can you fix the problem so that we can use the Off command and the transitiontime parameter on light-only commands?
Thanks in advance.

Work:
![image](https://user-images.githubusercontent.com/34892335/221435403-8537f1c2-6a7f-4eb8-846c-2bca17bc91ce.png)

Don't work:
![image](https://user-images.githubusercontent.com/34892335/221435437-7bef26c1-5e8c-47cd-96d6-ab88bf140fdb.png)

## Environment
 - Host system: (Raspberry Pi)
 - Running method: (Jeedom)
 - Firmware version: (26780700)
 - deCONZ version: (2.20.01 / 19/09/2022)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (no) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which?

Mathieu

**Comment by OUARZA** [comment]
Not solved

**Comment by ebaauw** [comment]
Make sure the light is exposed using a DDF that includes the `cap/bri/move_with_onoff` item.  Note that this item is not visible in the REST API.

Background: The Zigbee _Off_ command doesn't take a _Transition Time_.  So you need to specify both `"on": false` and `"bri": 0`, to send _Move to Level (with On/Off)_ command, which does honour _Transition Time_.  However, not all lights implement this command correctly.  We used to whitelist the lights that do, hardcoded in C++, falling back to _Off_ for those that don't.  Recently the whitelist has changed to specifying the above mentioned capability in the DDF.  When that capability is present, the REST API plugin will send _Move to Level (with On/Off)_; when not, it will send a plain _Off_.

As we have no logic to analyse what types of lights are in a group, setting a group action of "on": false` and `"bri": 0` results in a _Move to Level (with On/Off)_ unconditionally, accepting the risk that some lights might not turn off.

**Comment by OUARZA** [comment]
Hello @ebaauw ,
I cannot find the reference of my Philips lamps under the file /usr/share/deCONZ/devices/philips
LST002 and LCT007
Mathieu

**Comment by ebaauw** [comment]
LST002 is in `light_zll_C.json` and LCT007 is in `light_zll_B.json`.  These should be included in v2.20.1, and should be used if you have _DDF Mode_ set to _Basic_ with _Gold_ enabled.  Select the light node in the GUI, right click and select _Edit DDF_: the popup window should show Status Gold.

**Comment by OUARZA** [comment]
@ebaauw 
I already have the correct version.
![image](https://user-images.githubusercontent.com/34892335/229288303-bb43b403-1bb9-4043-8e76-06c940f04cb5.png)

I looked in the 2 files, they have the right parameter
![image](https://user-images.githubusercontent.com/34892335/229288705-ce8e36db-db6d-4a8f-8825-4402d3f793a5.png)

Mathieu

**Comment by ebaauw** [comment]
Then they should turn off slowly over 20s when PUTting `{ "on": false, "bri": 0, "transitiontime" 200 }`.

What's your setting for _DDF_ in the _Control_ panel?

**Comment by OUARZA** [comment]
Where can I find this information?
I am under Jeedom with the Deconz / Phoscon plugin.

**Comment by ebaauw** [comment]
In the _Control_ panel in the deCONZ GUI.

**Comment by OUARZA** [comment]
I don't have deconz GUI

**Comment by OUARZA** [comment]
@ebaauw Can't check from command line?

**Comment by Mimiix** [comment]
> @ebaauw Can't check from command line?

Nope.
