### ISSUE TITLE
ZigBee Tuya Temperatur and humidity sensor 

### ISSUE THREAD

**Issue by Thanh-Binh** [dresden-elektronik/deconz-rest-plugin#6769]
I have the same Tuya sensor in ZigBee (as discussed in this forum 3year ago) but produced by Moes, but can not see it in HA.
Could you please help me by HA integration?
Thanks

**Comment by Mimiix** [comment]
Hi,

As this issue is not as described by #5113 i am closing this issue.

Please follow the device request template and carefully provide all information.

Kind regards 
Dennis
