### ISSUE TITLE
FOHSWITCH is not shown in deCONZ device map

### ISSUE THREAD

**Issue by Rolf56** [dresden-elektronik/deconz-rest-plugin#6778]
## Describe the bug

The FOHSWITCH can be added by the Phoscon App and it is also shown there as switch device, but it is not shown in the deCONZ device map.

![image](https://user-images.githubusercontent.com/44340206/222897019-5f38bb87-3386-4e23-98e8-8f7eb05d9fe3.png)
https://www.amazon.de/dp/B08K3C44J4

## Steps to reproduce the behavior
  1. Go to Phoscon App
  2. Click on 'Add new switch', power on the device
  3. New switch is found and displayed
  4. Device works fine
  5. Go to deCONZ UI, the switch device is not shown there

## Expected behavior
The FOHSWITCH switch device should be shown in deCONZ UI

## Screenshots

Device in Phoscon App
![image](https://user-images.githubusercontent.com/44340206/222896590-e12fdcd0-dc17-4479-b860-98c04a90b40b.png)

Device is shown by postman REST-Client

192.168.0.29:80/api/xxxxxxxxxx/sensors/
    "76": {
        "config": {
            "on": true
        },
        "ep": 242,
        "etag": "76387e5221513f8275dab6224708a6a2",
        "lastannounced": null,
        "lastseen": "2023-03-04T07:09Z",
        "manufacturername": "PhilipsFoH",
        "modelid": "FOHSWITCH",
        "name": "Esszimmer.Licht",
        "state": {
            "buttonevent": 4002,
            "lastupdated": "2023-03-04T07:09:46.412"
        },
        "type": "ZGPSwitch",
        "uniqueid": "00:00:00:00:01:71:e3:66-f2"
    }

## Environment

 - Host system: PC
 - Running method: Windows
 - Firmware version: 26400500
 - deCONZ version: v2.20.1
 - Device: ConBee I
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? no

## Additional context

This is the only device of "type": "ZGPSwitch". All other are "type": "ZHA...". Maybe there is some code missing for "type": "ZGPSwitch".

**Comment by SwoopX** [comment]
ZGPSwitch do not show up in deconz GUI due to their nature and way of operation.
