### ISSUE TITLE
Osram Smart+ plug won't route Xiaomi Aqara sensors

### ISSUE THREAD

**Issue by DeltaAngle** [dresden-elektronik/deconz-rest-plugin#679]
I got some Osram Smart+ plugs to increase the mesh of my network and cover more ground, but it seems the Osram plugs will not route the Xiaomi sensors. I'm not certain if this is a configuration issue or a limitation of the plug itself.

As a test, I added a Philips Hue Bloom to the network, and I was able to get some Xiaomi sensors to route through the Hue. The Osram plugs even started routing through the Hue and vice-versa, so it appears the plugs can route, they just won't route the Xiaomi sensors.

Any advice?

**Comment by manup** [comment]
This was more an display issue, lines not shown for some Osram devices, checked via sniffer the Osram plugs route fine also Xiaomi sensors.
