### ISSUE TITLE
Aquara E1-lumi.airrtc.agl001 not takeover of heatpoint Beta deconz-2.21.00

### ISSUE THREAD

**Issue by Ollilein** [dresden-elektronik/deconz-rest-plugin#6796]
Conbee II
Version 2.21.0ß
Firmware 26780700

NUC-PC with ProxMox
Iobroker running inside container with deconz adapter.

After installing the beta version 2.21.00 the Aqara Radiator Thermostate E1 does not take over any change of the heat point value.

Back to 2.20.01 no problem anymore.

**Comment by Mimiix** [comment]
Hi,

Please use the template. 

Closing this issue as it does not contains the template.

Kind regards,
Dennis
