### ISSUE TITLE
Moes Smart Zigbee Push Button Switch 2 Gang: _TZ3000_18ejxno0 / TS0012

### ISSUE THREAD

**Issue by MrMEScott** [dresden-elektronik/deconz-rest-plugin#6798]
## Device

- Product name: Moes Smart Zigbee Push Button Switch 2 Gang
- Manufacturer: _TZ3000_18ejxno0
- Model identifier: TS0012
- Device type : 
  - Switch

## Screenshots

![image](https://user-images.githubusercontent.com/30527614/224722120-0b098ba6-362c-42ec-a8c8-d6d66c574cd9.png)

### Basic
![Screenshot from 2023-03-13 13-05-01](https://user-images.githubusercontent.com/30527614/224716754-19cbbb5d-1db1-44c6-8469-c8ea662cb889.png)

### Identify
![image](https://user-images.githubusercontent.com/30527614/224716955-312e5ae3-07a9-44a3-8f30-ccadee6ce5a3.png)

### Groups
![image](https://user-images.githubusercontent.com/30527614/224719175-c9bd3c63-c81d-4e83-848d-5a88cb48cddd.png)

### Scenes
![image](https://user-images.githubusercontent.com/30527614/224719347-9f538323-8e7e-42fd-9392-1b829ae820a7.png)

### On/Off
![image](https://user-images.githubusercontent.com/30527614/224719466-3a68be21-aa2d-41b4-ae48-a298c9e27338.png)

**Comment by Mimiix** [comment]
Hi,

Please add all screenshots of all clusters in full. including the attributes section being read.

Kind regards,

**Comment by MrMEScott** [comment]
Sorry about that. The cluster info panels are longer than my screen, so these screengrabs come in sections.
The content seems to be the same for both switch 1 and switch 2, with the exception of the On/Off attributes.
### Identify 
#### 1 of 2
![Identify_1](https://user-images.githubusercontent.com/30527614/224740359-c30f9d3a-1099-4d93-a2c3-90ce98b9c8ee.png)
#### 2 of 2
![Identify_2](https://user-images.githubusercontent.com/30527614/224740517-e7731c25-6553-49aa-8123-a0abf5c5d6cc.png)
### Groups
#### 1 of 3
![Groups_1](https://user-images.githubusercontent.com/30527614/224740814-995f8615-a9a9-4bcc-887e-1ddc91edff77.png)
#### 2 of 3
![Groups_2](https://user-images.githubusercontent.com/30527614/224740861-b55e00a2-69c0-430a-8f5d-8d1506a17776.png)
#### 3 of 3
![Groups_3](https://user-images.githubusercontent.com/30527614/224740914-79c17b4a-7e1f-420a-a883-aa6ec2e4cd3a.png)
### Scenes
#### 1 of 5
![Scenes_1](https://user-images.githubusercontent.com/30527614/224741141-6f21af3d-8955-4761-8bf1-2d9af2a15112.png)
#### 2 of 5
![Scenes_2](https://user-images.githubusercontent.com/30527614/224741199-c7d4ccd8-c7a8-4bb8-b50f-91c68fa3d635.png)
#### 3 of 5
![Scenes_3](https://user-images.githubusercontent.com/30527614/224741251-c852bc65-91fd-4ecd-ad79-173fd605d322.png)
#### 4 of 5
![Scenes_4](https://user-images.githubusercontent.com/30527614/224741333-8b263ef3-7701-4f57-be81-8cc5740f31bb.png)
#### 5 of 5
![Scenes_5](https://user-images.githubusercontent.com/30527614/224741389-57daa2a2-3ca7-44be-8347-f5af6817da4b.png)
### On/Off
#### Switch 1, 1 of 2
![OnOff_1](https://user-images.githubusercontent.com/30527614/224741595-6d84439b-1a31-4365-ba4d-5ce2d40d1a8f.png)
#### Switch 1, 2 of 2
![OnOff_2](https://user-images.githubusercontent.com/30527614/224741657-480a8d5a-34ea-47c8-9c4f-dd330aed2634.png)
#### Switch 2, attribute section (the switch was on when I grabbed this)
![image](https://user-images.githubusercontent.com/30527614/224745288-10e08310-60fe-4733-9acc-43fc9d049fe8.png)

**Comment by BabaIsYou** [comment]
Could you try this DDF ?
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_fvh3pjaz","_TZ3000_18ejxno0"],
  "modelid": ["TS0012","TS0012"],
  "product": "Battery 2 gang switches",
  "sleeper": true,
  "status": "Silver",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0000",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001"
        ],
        "out": [
          "0x0006"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by MrMEScott** [comment]
I'd be happy to, if I knew how to! :)
Where do I put it / how do I install it?

**Comment by MrMEScott** [comment]
Suppose I copied the DDF @BabaIsYou  posted, then what? I restart deconz, then does the device become discoverable by Phoscon? Do I have to re-pair it? Or is there some other step I need to take to make it visible to the Home Assistant deconz integration?

**Comment by Mimiix** [comment]
> Suppose I copied the DDF @BabaIsYou posted, then what? I restart deconz, then does the device become discoverable by Phoscon? Do I have to re-pair it? Or is there some other step I need to take to make it visible to the Home Assistant deconz integration?

Restart deconz. Re pair might also work after that.

**Comment by Mimiix** [comment]
> > Suppose I copied the DDF @BabaIsYou posted, then what? I restart deconz, then does the device become discoverable by Phoscon? Do I have to re-pair it? Or is there some other step I need to take to make it visible to the Home Assistant deconz integration?
> 
Restart deconz. Should show up in the rest api.

You can see the events in Phoscon under help, then api information.

**Comment by Mimiix** [comment]
If it works, the hex name should be gone and has something like switch.

Additionally i am not sure if we need a button map?

**Comment by BabaIsYou** [comment]
If you gain access to DeConz gui then you can edit DDF and simulate a save as … just to get the path ;-)

**Comment by MrMEScott** [comment]
> If you gain access to DeConz gui then you can edit DDF and simulate a save as … just to get the path ;-)

I don't see any option to edit DDF in the deConz gui. I'm accessing it via VNC, and the only window on the desktop is `deCONZ - Conbee II (/dev/ttyACM0)`. I have no way to open other windows.
Unde deConz preferences I see an interface to add/remove ZCLDB XML files but I guess that's something different?

**Comment by BabaIsYou** [comment]
You should have this
![image](https://user-images.githubusercontent.com/85300265/224864500-7c311a9a-0ae6-4e66-87f5-e3b017ab97d4.png)
and then after selecting a device on the right map, you have to select the far right radio button to display the clusters list
![image](https://user-images.githubusercontent.com/85300265/224864702-650a6c66-7441-4c4d-bc5e-99d940d7d45c.png)
after that slect the basic cluster and do a click on "read" button above attributes list
![image](https://user-images.githubusercontent.com/85300265/224864919-30b93cf2-9500-4f82-904c-0fd35e988388.png)
Then with Control+E or in the Edit menu you gain access to the DDF Editor
![image](https://user-images.githubusercontent.com/85300265/224865026-754b893c-0d82-4969-9778-2462039c23fe.png)

Then perhaps could you load the previously copied DDF and save it the place Deconz offers you to to do with Save as option

![image](https://user-images.githubusercontent.com/85300265/224865180-29fadd92-4a40-452a-b82e-161e7b32dbc3.png)

Hope this help with the other indication given by Smanar and Mimiix

**Comment by BabaIsYou** [comment]
I also modified the DDF in the initial post because the fingerprint part was useless and false, then I propose a specific DDF for this device. Hope that it doesn't need buttonmap as Mimiix suggested.

**Comment by MrMEScott** [comment]
I don't see a Control entry in the menu. Here's what I have:
![image](https://user-images.githubusercontent.com/30527614/224929585-5edcc816-7686-45ac-b4dc-85ec36f1dcdf.png)

This has opened a whole new can of worms.

I'm running the `marthoc/deconz` Docker image, which I hadn'r realised is now deprecated in favour of `deconzcommunity/deconz`. 
Should I migrate to the new one? Or maybe there's some startup parameter I can use on the existing container to surface the Control panel?

**Comment by Mimiix** [comment]
> I don't see a Control entry in the menu. Here's what I have: ![image](https://user-images.githubusercontent.com/30527614/224929585-5edcc816-7686-45ac-b4dc-85ec36f1dcdf.png)
> 
> This has opened a whole new can of worms.
> 
> I'm running the `marthoc/deconz` Docker image, which I hadn'r realised is now deprecated in favour of `deconzcommunity/deconz`. Should I migrate to the new one? Or maybe there's some startup parameter I can use on the existing container to surface the Control panel?

Yes, you need to migrate. Your on a very old version of deCONZ.

**Comment by Smanar** [comment]
Just for information there is a shared folder in the official deconz docker, you can just put your DDF in the `opt/deCONZ/devices` folder.

**Comment by BabaIsYou** [comment]
Just to be sure, is it working each button individualy ?

**Comment by MrMEScott** [comment]
> Just for information there is a shared/persistent folder in the official deconz docker, you can just put your DDF in the `opt/deCONZ/devices` folder.
> 
> [deconz-community/deconz-docker#163](https://github.com/deconz-community/deconz-docker/issues/163)

I found it, and that's where I put the DDF.

**Comment by MrMEScott** [comment]
> Just to be sure, is it working each button individualy ?

Yes, I have two entities in Home Assistant and I can control them individually.
![image](https://user-images.githubusercontent.com/30527614/225086902-a60b6fe9-cba1-4890-a164-eebe5eae4a8f.png)

although it displays in deconz gui with only the name I gave to the #1 endpoint.
![image](https://user-images.githubusercontent.com/30527614/225086439-af2de812-d9df-4a1e-a827-1813463005de.png)

**Comment by MrMEScott** [comment]
I think this can close now?

**Comment by Mimiix** [comment]
No, don't close yet. I've linked the PR to this issue and if that one is merged this will auto close :)
