### ISSUE TITLE
Zigbee not responding - Error: aps request id xxx timeout NOT confirmed to xxx 

### ISSUE THREAD

**Issue by Einstein2150** [dresden-elektronik/deconz-rest-plugin#6800]
## Describe the bug
Zigbee is unreproducable sometimes not responding. There are a lot of timeouts In the deConz error log to see while this happens. Only a restart of deConz helps to get the network working again.

## Screenshots

![IMG_4158](https://user-images.githubusercontent.com/22019133/224983502-3df8502e-f9a3-4b32-a739-39d660024336.PNG)

## Environment
Version 2.19.03/19.9.2022
Firmware 26400500
RaspBee

 - Host system: Raspberry Pi 4
 - Running method: Raspbian 
 - Firmware version: 26400500
 - deCONZ version: 2.19.03/19.9.2022
 - Device: RaspBee I 

 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs
11:52:26:193 aps request id: 170 prf: 0x0104 cl: 0x0300 timeout NOT confirmed to 0x680AE2FFFE32F5AE (0x6FF2)
11:52:30:992 aps request id: 187 prf: 0x0000 cl: 0x0031 timeout NOT confirmed to 0x588E81FFFEFB82FF (0x8581)
11:52:31:953 aps request id: 171 prf: 0x0104 cl: 0x0004 timeout NOT confirmed to 0x680AE2FFFE32F5AE (0x6FF2)
11:52:37:713 aps request id: 210 prf: 0x0000 cl: 0x0004 timeout NOT confirmed to 0x00212EFFFF040F03 (0x0000)
11:52:47:313 aps request id: 211 prf: 0x0104 cl: 0x0004 timeout NOT confirmed to 0x842E14FFFE65B7DB (OxAA74)
11:53:22:352 aps request id: 213 prf: 0x0104 cl: 0x0008 timeout NOT confirmed to 0x0000000000000000 (0x0000)
11:53:27:153 aps request id: 214 prf: 0x0104 cl: 0x0300 timeout NOT confirmed to 0x842E14FFFESEF62E (OxB8BF)
11:53:31:472 aps request id: 215 prf: 0x0000 cl: 0x0031 timeout NOT confirmed to OxECIBBDFFFEA03AEB (0x8BAA)
11:53:33:392 aps request id: 217 prf-0x0104 cl: 0x0006 timeout NOT confirmed to 0x0000000000000000 0x0000)
11:53:51:152 aps request id: 3 prf: 0.0000 cl: 0x0004 timeout NOT confirmed to 0x00212EFFFF040F03 (0x0000)
11:53:53:553 aps request id: 10 prf: 0x0104 cl: 0x0004 timeout NOT confirmed to OxB4E3F9FFFEC6B5D6 (0xC6A6)
11:54:01:232 aps request id: 12 prf: 0x0104 cl: 0x0008 timeout NOT confirmed to 0x0000000000000000 (0x0000)
11:54:22:609 aps request id: 14 prf: 0x0104 cl: 0x0008 timeout NOT confirmed to 0x0000000000000000 (0x0000)
11:54:27:409 aps request id: 16 prf: 0x0104 cl: 0x0006 timeout NOT confirmed to 0x0000000000000000 (0x0000)
11:54:32:208 aps request id: 32 prf: 0x0000 cl: 0x0031 timeout NOT confirmed to 0x84D27FFFE2CBC53 (0x8BEA)

**Comment by Mimiix** [comment]
Hi

As this is not an issue as described in #5113 , i am closing this issue.

To help you further, check the zigbee error codes in the wiki and look for 0xE1.

Otherwise, we are happy to help on the forums.

Kind regards,
Dennis
