### ISSUE TITLE
Tuya / TONGOU TO-Q-SV1-ZT

### ISSUE THREAD

**Issue by GabeHH78** [dresden-elektronik/deconz-rest-plugin#6807]
## Device

- Product name: Tuya / TONGOU
- Manufacturer: unknown / Tongou  / _tz3000_gzvniqjb
- Model identifier: unknown / TO-Q-SY1-ZT / TS0011
- Device type : Rail Switch

![image](https://user-images.githubusercontent.com/78250680/226169123-ba02d4ec-d413-4505-8a32-bfc60104daef.png)

![image](https://user-images.githubusercontent.com/78250680/226169162-a4d968ed-7e63-4b5e-8501-03d642fedc97.png)

Addional cluster

Iddentify

![image](https://user-images.githubusercontent.com/78250680/226169288-207fa6cb-d2c8-4eb3-90d8-60af1abe6b77.png)

Groupes

![image](https://user-images.githubusercontent.com/78250680/226169327-136f18f7-22c9-4ea4-b0e7-263bff9736ce.png)

Scnees

![image](https://user-images.githubusercontent.com/78250680/226169355-a142ed71-8910-4b33-824d-55dc7dc4129e.png)

ON/OFF

![image](https://user-images.githubusercontent.com/78250680/226169382-366f35d1-03a2-48af-95d7-6bd67164f5ac.png)

OTAU

![image](https://user-images.githubusercontent.com/78250680/226169402-9a800b1c-fcee-4dc4-a7e6-89ae1a3547bf.png)

Basic

![image](https://user-images.githubusercontent.com/78250680/226363604-44ab49aa-c391-4552-90b1-1c74a9860d18.png)
![image](https://user-images.githubusercontent.com/78250680/226363709-dd14ab27-a255-467e-8783-2715b02673f6.png)

**Comment by Mimiix** [comment]
Hi,

please add all screenshots.

**Comment by Mimiix** [comment]
Please read the template when you created the issue. It is really clear on what is required.

Additionally, edit your opening post.

**Comment by GabeHH78** [comment]
I put now everything in, hope it is now ok? Or is anything missing?

**Comment by Mimiix** [comment]
Hi,

The attributes are not populated. You need to make sure that they are. To do this, click "read" on the cluster window and see if things change. If they don't, check if the device is not sleeping.

**Comment by GabeHH78** [comment]
Hi,

I put new scrrenshots in. I hope it is now ok.

I have the possibility in Deconz to siwtch it on and off, but I couldnt see it in the phoscon app.

Thanks for helping

**Comment by Mimiix** [comment]
Basic cluster is still missing

**Comment by GabeHH78** [comment]
Hi,

I put now Basic inside

Hope now ok

rgds

**Comment by GabeHH78** [comment]
I put a new screenshot in. Is it better?

**Comment by Mimiix** [comment]
looks good :)! Thank you

**Comment by GabeHH78** [comment]
great Thank you ;)

**Comment by BabaIsYou** [comment]
I suppose that this is the model without metering, then could give a try to this DDF :

```
{
	"schema": "devcap1.schema.json",
	"manufacturername": "_TZ3000_gzvniqjb",
	"modelid": "TS0011",
	"product": "TO-Q-SY1-ZT",
	"sleeper": true,
	"status": "Silver",
	"subdevices": [{
		"type": "$TYPE_ON_OFF_OUTPUT",
		"restapi": "/lights",
		"uuid": [
			"$address.ext",
			"0x01"
		],
		"items": [{
				"name": "attr/id"
			},
			{
				"name": "attr/lastannounced"
			},
			{
				"name": "attr/lastseen"
			},
			{
				"name": "attr/manufacturername"
			},
			{
				"name": "attr/modelid"
			},
			{
				"name": "attr/name"
			},
			{
				"name": "attr/swversion"
			},
			{
				"name": "attr/type"
			},
			{
				"name": "attr/uniqueid"
			},
			{
				"name": "state/on"
			},
			{
				"name": "state/reachable"
			}
		]
	}]
}
```

Don't know if bindings are nedded.

**Comment by BabaIsYou** [comment]
BTW could add  binding in the DDF : 
```
{
	"schema": "devcap1.schema.json",
	"manufacturername": "_TZ3000_gzvniqjb",
	"modelid": "TS0011",
	"product": "TO-Q-SY1-ZT",
	"sleeper": true,
	"status": "Silver",
	"subdevices": [{
		"type": "$TYPE_ON_OFF_OUTPUT",
		"restapi": "/lights",
		"uuid": [
			"$address.ext",
			"0x01"
		],
		"items": [{
				"name": "attr/id"
			},
			{
				"name": "attr/lastannounced"
			},
			{
				"name": "attr/lastseen"
			},
			{
				"name": "attr/manufacturername"
			},
			{
				"name": "attr/modelid"
			},
			{
				"name": "attr/name"
			},
			{
				"name": "attr/swversion",
				"parse": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0x0001",
					"script": "tuya_swversion.js"
				},
				"read": {
					"fn": "zcl",
					"ep": 1,
					"cl": "0x0000",
					"at": "0x0001"
				}
			},
			{
				"name": "attr/type"
			},
			{
				"name": "attr/uniqueid"
			},
			{
				"name": "state/on"
			},
			{
				"name": "state/reachable"
			}
		]
	}],
	"bindings": [{
		"bind": "unicast",
		"src.ep": 1,
		"cl": "0x0006",
		"report": [{
			"at": "0x0000",
			"dt": "0x10",
			"min": 1,
			"max": 300
		}]
	}]
}
```

**Comment by GabeHH78** [comment]
Great now everything work fine for me.

Many thanks for your helps!!!

**Comment by ValleBL** [comment]
Would this include TO-Q-SY1-JZT?
That’s the version with power metering
