### ISSUE TITLE
Aqara WXKG20LM

### ISSUE THREAD

**Issue by agramner** [dresden-elektronik/deconz-rest-plugin#6818]
## Device

- Product name: Aqara WXKG20LM.
- Manufacturer: LUMI.
- Model identifier: lumi.remote.acn007
- Device type :
  - Remote
  - Switch

![bild](https://user-images.githubusercontent.com/47948035/227028889-fd668264-5b87-4061-8e02-d1d1beed9b80.png)

## Screenshots

![bild](https://user-images.githubusercontent.com/47948035/227026841-c6fc395e-b432-46e8-986b-4080b576dc6a.png)

![bild](https://user-images.githubusercontent.com/47948035/227027048-2d9ccc4c-a708-45bd-9936-4d6fcd4b3e77.png)

### Basic
![bild](https://user-images.githubusercontent.com/47948035/227027245-46ee0221-09f8-4cab-bf8f-c8ff88786002.png)

### Identify
![bild](https://user-images.githubusercontent.com/47948035/227027356-ce31a68e-48a9-4177-a24f-502e9ca49044.png)

### Power Configuration
![image](https://user-images.githubusercontent.com/47948035/227544932-f0b74447-e525-4e48-9b91-d02dac1910ad.png)

### Multistate Input (Basic)
![bild](https://user-images.githubusercontent.com/47948035/227027685-73369072-8e3d-44de-96c0-549124adac4d.png)

### Lumi specific
![bild](https://user-images.githubusercontent.com/47948035/227027900-6f164cf6-f9bc-48f7-aaaa-99377391e2dc.png)
![bild](https://user-images.githubusercontent.com/47948035/227028032-15e92b9e-508f-432d-b583-e2be77b15c2c.png)
![bild](https://user-images.githubusercontent.com/47948035/227028089-2ab47e7b-7a90-420b-a3c2-2e2f7a77ddb9.png)

**Comment by BabaIsYou** [comment]
Hi,

Are you sure you clicked on "read" before taking screenshot of Power Configuration cluster ?

**Comment by agramner** [comment]
You're right! I updated the screenshot :)

**Comment by BabaIsYou** [comment]
Trying to make a @SwoopX of me ... ;-) adapting https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5862#issuecomment-1136459355

Could you give a try to this DDF ? But button mapping should also have to be made after that.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_LUMI",
  "modelid": "lumi.remote.acn007",
  "matchexpr": "R.endpoints.length === 1",
  "vendor": "Xiaomi",
  "product": "Aqara Single Wall Button E1 WXKG20LM",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0000",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0012",
          "0xFCC0"
        ],
        "out": [
          "0x0006",
          "0x0019"
        ]
      },
      "meta": {"group.endpoints": [1] },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid",
          "awake": true
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x00f7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x01",
            "script": "xiaomi_battery.js"
          }
        },
        {
          "name": "config/clickmode",
          "refresh.interval": 3000,
          "parse": {
            "at": "0x0125",
            "cl": "0xfcc0",
            "ep": 1,
            "eval": "if (Attr.val == 1) { Item.val = 'highspeed' } else if (Attr.val == 2) { Item.val = 'multiclick' } else { Item.val = 'unknown' }",
            "fn": "zcl",
            "mf": "0x115f"
          },
          "read": {
            "at": "0x0125",
            "cl": "0xfcc0",
            "ep": 1,
            "fn": "zcl",
            "mf": "0x115f"
          },
          "write": {
            "at": "0x0125",
            "cl": "0xfcc0",
            "dt": "0x20",
            "ep": 1,
            "eval": "if (Item.val == 'highspeed') { 1 } else if (Item.val == 'multiclick') { 2 }",
            "fn": "zcl",
            "mf": "0x115f"
          },
          "values": [
            ["\"highspeed\"", "Buttons emit only single click events, but fast"],
            ["\"multiclick\"", "Emits single, double and treble presses"] 
          ],
          "default": "multiclick"
        },
        {
          "name": "config/devicemode",
          "refresh.interval": 3000,
          "parse": {
            "at": "0x0009",
            "cl": "0xfcc0",
            "ep": 1,
            "eval": "if (Attr.val == 1) { Item.val = 'compatibility' } else if (Attr.val == 2) { Item.val = 'zigbee' } else { Item.val = 'unknown' }",
            "fn": "zcl",
            "mf": "0x115f"
          },
          "read": {
            "at": "0x0009",
            "cl": "0xfcc0",
            "ep": 1,
            "fn": "zcl",
            "mf": "0x115f"
          },
          "write": {
            "at": "0x0009",
            "cl": "0xfcc0",
            "dt": "0x20",
            "ep": 1,
            "eval": "if (Item.val == 'compatibility') { 1 } else if (Item.val == 'zigbee') { 2 }",
            "fn": "zcl",
            "mf": "0x115f"
          },
          "values": [
            ["\"compatibility\"", "Default mode for Xiaomi devices"],
            ["\"zigbee\"", "Closer to zigbee standard"] 
          ],
          "default": "compatibility"
        },
        {
          "name": "config/group",
          "default": "auto"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

**Comment by agramner** [comment]
Nice, will try later tonight. I guess there's no way to copy paste it into Deconz UI? Need to find a way to ssh into Home assistant OS otherwise

**Comment by agramner** [comment]
Great, I tested it and it got a name in deconz UI and battry entity appeared in Home Assistant.

![image](https://user-images.githubusercontent.com/47948035/227644819-525f7fa4-3218-4729-87f0-d5f894c3bc3a.png)
![image](https://user-images.githubusercontent.com/47948035/227644980-a9b60c87-f457-48ac-9145-376ff5bd982c.png)

**Comment by agramner** [comment]
I checked out `button_maps.json` and guess that something need to be added there?
If it is of any help the `Preset value` in the `Multistate input` cluster change value like this:
- Long hold - `0`
- Single click - `1`
- Double click - `2`

**Comment by BabaIsYou** [comment]
May be you could see what is in button_maps.json for lumi.remote.acn003 to get inspired … if there is something for it

**Comment by BabaIsYou** [comment]
Seems could just try to add modelid to the part `xiaomiSwitchB186acn01Map` in `button_maps.json` because seems to be the same mapping ;-)

**Comment by agramner** [comment]
Yes tried that yesterday and it worked 😊. Battery status doesn't seem to work though, will look in to that later

**Comment by BabaIsYou** [comment]
Did you try with my last proposition for battery ?

**Comment by agramner** [comment]
Oh didn't see your comment about battery. Will try that tonight 👍

**Comment by SwoopX** [comment]
Battery is not working as the required .js file is not in the same location as the DDF. Either you copy it from the current location on your system or create a new one with the content from the repo. Please stick with the Xiaomi special reporting here.

Additionally, the swversion item can be replaced with this, again the respective .js file needs to be available:

```
        {
          "name": "attr/swversion",
          "awake": true,
          "parse": {
            "at": "0x00f7",
            "ep": 1,
            "fn": "xiaomi:special",
            "idx": "0x08",
            "script": "xiaomi_swversion.js"
          },
          "read": {
            "fn": "none"
          }
        },
```

Other than that, the sensor uuid is currently wrong, as it uses the on/off cluster, but should use multistate input.

Regarding the groups, I somewhat doubt that the switch correctly supports it. That would imply it also sends something, which can be seen in the debug log and is usable.

**Comment by agramner** [comment]
Thanks! It seem to work fine now. Changed to use xaomi:special for battery and swversion. And changed the uuid as suggested (not sure how that matters).

Also, clickmode doesn't seem to be supported. The attribute is greyed out. Should i remove config/clickmode?
![image](https://user-images.githubusercontent.com/47948035/227747610-4d630961-3424-41fb-81e0-f36f89d2ce55.png)

And what about devicemode? It's 0. Should it be removed?

**Comment by BabaIsYou** [comment]
> Other than that, the sensor uuid is currently wrong, as it uses the on/off cluster, but should use multistate input.

Thanks @SwoopX, but why should this zone use multistate rather thaan on/off like the one in #5862 ?

**Comment by SwoopX** [comment]
Because that was a 1:1 copy from the H1 DDF, having just exchanged the model ID. And the H1 makes use of the on/off cluster.

**Comment by SwoopX** [comment]
> Thanks! It seem to work fine now. Changed to use xaomi:special for battery and swversion. And changed the uuid as suggested (not sure how that matters).
> 
> Also, clickmode doesn't seem to be supported. The attribute is greyed out. Should i remove config/clickmode? ![image](https://user-images.githubusercontent.com/47948035/227747610-4d630961-3424-41fb-81e0-f36f89d2ce55.png)
> 
> And what about devicemode? It's 0. Should it be removed?

Yes, clickmode can be removed. I'd keep devicemode for the time being, it should set itself to 1 (compatibility) after some time.

**Comment by agramner** [comment]
Ok great! I'll create a PR soon
