### ISSUE TITLE
Sengled light bulb showing as end device

### ISSUE THREAD

**Issue by xhemp** [dresden-elektronik/deconz-rest-plugin#682]
I have just bought a sengled zigbee light bulb to test and was able to pair with deCONZ just fine but it's being recognised as an end device instead of a gateway.
Is there anything I can grab from deCONZ so you can have a look?

<img width="468" alt="screen shot 2018-07-09 at 12 09 40" src="https://user-images.githubusercontent.com/13650956/42447418-b44c71a4-8371-11e8-9a90-8fe25717b638.png">

**Comment by manup** [comment]
Screenshot of the NodeInfo panel would be interesting, but I'm afraid it is just as it looks and the light might not act as a router (which is unusual but but totally allowed by the spec).

**Comment by xhemp** [comment]
I understand.
Here is the screenshot:

<img width="481" alt="screen shot 2018-07-09 at 13 00 50" src="https://user-images.githubusercontent.com/13650956/42449396-6d1281e6-8378-11e8-86a0-17c65fbfc7a1.png">

**Comment by manup** [comment]
From here it looks like the device is indeed not a router, device type RFD means reduced function device with no routing capabilities. Might be error in the node descriptor but only a sniffer log would tell.

**Comment by xhemp** [comment]
@manup Thanks for having a look at it, I had emailed Sengled and they confirmed it's an RFD, I am closing this one.
