### ISSUE TITLE
Meian Flooding detector SW02-ZB

### ISSUE THREAD

**Issue by alex-jung** [dresden-elektronik/deconz-rest-plugin#6823]
## Device

- Product name: Smart Flooding Detector SW02-ZB
- Manufacturer: _TZ3000_kyb656no
- Model identifier: TS0207
- Device type :
  - Sensor

### Endpoint
![image](https://user-images.githubusercontent.com/8005899/227477860-1b52cb51-df09-408c-8358-83dfb3bd327f.png)

### Node info
![image](https://user-images.githubusercontent.com/8005899/227478004-c6a35d3d-c471-468c-9cc1-5a1399f2efb0.png)

### Basic
![image](https://user-images.githubusercontent.com/8005899/227478237-6bc26d75-5fad-4c46-984e-e7e7a7060d79.png)

### Identify
![image](https://user-images.githubusercontent.com/8005899/227478370-5d4a926e-6647-410c-a335-69aa28142c6c.png)

## Power configuration
![image](https://user-images.githubusercontent.com/8005899/227478590-dd70e192-dee1-4404-8c4f-cef66aee759d.png)

### IAS Zone
![image](https://user-images.githubusercontent.com/8005899/227478740-66c17faa-e529-4dec-9176-efcd2d5e8993.png)

### OTAU
![image](https://user-images.githubusercontent.com/8005899/227478897-a7d5045a-ea33-4154-9bca-4e3ebe21b5b6.png)

**Comment by BabaIsYou** [comment]
Can you give a try to this DDF ?

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_kyb656no",
  "modelid": "TS0207",
  "vendor": "Meian",
  "product": "Flooding detector SW02-ZB",
  "sleeper": true,
  "status": "Silver",
  "subdevices": [
    {
      "type": "$TYPE_WATER_LEAK_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0003",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid",
          "awake": true
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl"
          }
        },
        {
          "name": "config/checkin",
          "awake": true
        },
        {
          "name": "config/enrolled",
          "public": true
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/water",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 14400,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}

**Comment by alex-jung** [comment]
Hi,

Unfortunately no changes :( But I'm not 100% if I'm doing the update correctly. Please let me know if I'm doing it wrong.

Following steps I did performed:
1. Store provided content in a JSON file inside the deCONZ docker image
2. Open "deCONZ" Webview
3. Right click on "problematic" node
4. Edit DDF
5. File -> Open created JSON file
6. Open Phoscon
7. Try to add a new sensor

![image](https://user-images.githubusercontent.com/8005899/228029076-549a6d1e-4273-4c5c-8a2d-b4a8999d2b78.png)

**Comment by BabaIsYou** [comment]
DDF has to be stored in a stecific folder (may be could find hints here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6798#issuecomment-1466483973). Then just rejoining the device may be sufficient.

**Comment by alex-jung** [comment]
Thank you for tips :) After I enabled Silver DDF level, sensor was updated in deCONZ:
![image](https://user-images.githubusercontent.com/8005899/228512010-a6d85c82-41cf-4716-843d-7c9ede9ec944.png)

in phoscon works sensor as expected too.

But in Home Assistant I see only Battery Entity:
![image](https://user-images.githubusercontent.com/8005899/228512391-63e30d13-3684-416a-bcea-6d065e7c00bf.png)

Do you know where I can address this issue?

**Comment by BabaIsYou** [comment]
Well done ! I'm not familiar with HA, but do you have some errors in log, in Deconz or HA part about this device ?

**Comment by BabaIsYou** [comment]
@alex-jung can you see the sensor thru Phoscon or REST-API ?

**Comment by alex-jung** [comment]
Hi,

Sorry for late answer, my HA was broken for some reason, I had to reinstall it.
Now after I installed Home Assistant OS, the sensor work as expected:
![image](https://user-images.githubusercontent.com/8005899/229371788-edb48470-1c59-475b-b157-8394601656a3.png)

Thank you a lot for providing a solution and have nice Easter :)

BR
Alex
