### ISSUE TITLE
2.05.32 package available

### ISSUE THREAD

**Issue by kylegordon** [dresden-elektronik/deconz-rest-plugin#685]
Will 2.05.32 be available in packaged form? It appears to be missing from https://www.dresden-elektronik.de/deconz/

**Comment by manup** [comment]
Yes it will arrive for Windows and Ubuntu later today.

**Comment by kylegordon** [comment]
Awesome, thank you. Sorry to be a pain :-)

**Comment by manup** [comment]
All good :) everything should be online now.

**Comment by ooii** [comment]
Hi,
Is there any release notes somewhere for these packages?
Thanks.

**Comment by manup** [comment]
Currently the Github relases contain most details.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases

**Comment by ooii** [comment]
Thanks.
