### ISSUE TITLE
Hama TRV

### ISSUE THREAD

**Issue by guiumb** [dresden-elektronik/deconz-rest-plugin#6856]
Request for support device Hama TRV (https://zigbee.blakadder.com/Hama_00176592.html)
DDF file suggested by @Smanar in issue #6806 permit device DeConz enablement.

- Product name: Hama Smart Radiator Thermostat
- Manufacturer: _TZE200_h4cgnbzg
- Model identifier: TS0601
- Device type : Thermostat

Node Info:

![image](https://user-images.githubusercontent.com/42201341/229457899-4fe7a29d-a4b8-4cdb-b5dc-37e61712a260.png)

Basic:

![image](https://user-images.githubusercontent.com/42201341/229458989-cbfcf994-0c0f-4ad3-9c98-7739b59e9fc6.png)

Groups:

![image](https://user-images.githubusercontent.com/42201341/229458775-93d7c1fc-55fb-42fe-b8b4-e3bec813fb12.png)
![image](https://user-images.githubusercontent.com/42201341/229458894-d6a57772-faf7-4e08-83e0-e6e0b0a5a90e.png)

Scenes

![image](https://user-images.githubusercontent.com/42201341/229459062-5c5e6b1b-de33-491d-8ddf-df9e358c8d49.png)
![image](https://user-images.githubusercontent.com/42201341/229459097-14c20e49-0f1a-4b23-87cf-83b82c20e734.png)
![image](https://user-images.githubusercontent.com/42201341/229459132-423aa0a5-41ff-4d30-a30e-8c65f3d30d19.png)
![image](https://user-images.githubusercontent.com/42201341/229459174-0d8b7614-0278-41f8-be93-220a119f44e6.png)

Tuya specific Cluster:

![image](https://user-images.githubusercontent.com/42201341/229459343-bdf9c1d3-6fca-4975-b6e7-735c180a1e07.png)

OTAU:

![image](https://user-images.githubusercontent.com/42201341/229459392-44836306-a734-4c37-874a-7346105b7b5f.png)
![image](https://user-images.githubusercontent.com/42201341/229459416-b70ad89b-f225-4f78-a264-8b69a755d5e0.png)

Time:

![image](https://user-images.githubusercontent.com/42201341/229460839-2e140223-4748-41e0-a2b5-c1a9d6ba076e.png)

**Comment by Smanar** [comment]
The used DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_h4cgnbzg",
  "modelid": "TS0601",
  "vendor": "Tuya",
  "product": "Saswell TRVs",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "meta": {
        "values": {
          "config/mode": {"off": 0, "heat": 1}
        }
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lowbattery",
          "parse": {"fn": "tuya", "dpid": 105, "eval": "Item.val = Attr.val;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/heatsetpoint",
          "parse": {"fn": "tuya", "dpid": 103, "eval": "Item.val = Attr.val * 10;"},
          "write": {"fn": "tuya", "dpid": 103, "dt": "0x2b", "eval": "Item.val / 10;"},
          "read": {"fn": "tuya"}
        },
        {
          "name": "config/locked",
          "parse": {"fn": "tuya", "dpid": 40, "eval": "Item.val = Attr.val;"},
          "write": {"fn": "tuya", "dpid": 40, "dt": "0x10", "eval": "Item.val;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/windowopen_set",
          "parse": {"fn": "tuya", "dpid": 8, "eval": "Item.val = Attr.val;"},
          "write": {"fn": "tuya", "dpid": 8, "dt": "0x10", "eval": "Item.val;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/mode",
          "values": [
              ["off", 0], ["heat", 1]
          ],
          "parse": {"fn": "tuya", "dpid": 101, "eval": "if (Attr.val == 0) { Item.val = 'off' } else { Item.val = 'heat' }"},
          "write": {"fn": "tuya", "dpid": 101, "dt": "0x10", "eval": "if (Item.val == 'off') { false } else { true }"},
          "read": {"fn": "none"}
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 102, "eval": "Item.val = Attr.val * 10;"},
          "read": {"fn": "none"}
        },
        {
          "name": "state/valve",
          "parse": {"fn": "tuya", "dpid": 104, "eval": "Item.val = Attr.val > 5;"},
          "read": {"fn": "none"}
        }
      ]
    }
  ]
}
```

If all is working just tell me if you want to make the PR (to submit the DDF officialy) or want I make it.

**Comment by guiumb** [comment]
DDF file works fine. If you could open a PR I would be very grateful, and I think that would also help future buyers of this device.
I am very grateful for your help and support.

**Comment by Smanar** [comment]
>that would also help future buyers of this device

And more, this device have so much clones
PR done, thx for help too.

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6859
