### ISSUE TITLE
After update using reverse proxy sensors page is not reachable

### ISSUE THREAD

**Issue by raidenlal** [dresden-elektronik/deconz-rest-plugin#6862]
## Describe the bug

I am accessing home assistant via reverse proxy. Everything was working just a few days ago - all of hass pages are accessible, Deconz page is accessible. When trying to access anything from the "Devices" menu - Lights, Switches, Sensor - I always get:
`The webpage at https://hostname/api/hassio_ingress/someid/pwa/devices-lights.html?_v=uuid,3,2,22&gwid=someid might be temporarily down or it may have moved permanently to a new web address.`
  1. Go to deCONZ plugin in hass
  2. Click on 'Phoscon'
  3. Click on hamburger menu: Devices->Lights
  4. Observed error

## Expected behavior
Devices get shown

## Environment

 - Host system: HASS OS
 - Running method: RPI
 - Firmware version: (26xxyy00)
 - deCONZ version: 6.19.0
 - Device: ConBee
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? If so: zwave dongle

**Comment by Mimiix** [comment]
Hi,

Phoscon bug reports are collected on the forums, as is described in #5113.

Closing this issue

**Comment by raidenlal** [comment]
Is this a joke?
