### ISSUE TITLE
Open-source of Raspbee commands

### ISSUE THREAD

**Issue by ezgicakirofficial** [dresden-elektronik/deconz-rest-plugin#687]
Hi,
Is there any open source that contains Raspbee commands as Conbee has? Since Conbee has a resoruce that shows its low-level commands , I was able to write a library that can be used for desired type of HA functionality. I want to do the same thing for Raspbee also. 
Or their commands are the same? Or all Zigbee devices' commands are the same?

**Comment by manup** [comment]
Both devices share the same firmware so if it already works with ConBee it should work with RaspBee too.

>Or all Zigbee devices' commands are the same?

Only RaspBee/ConBee other chips and devices use different protocols.

**Comment by ezgicakirofficial** [comment]
OK. Thank you
