### ISSUE TITLE
TS0012 Clone? _TZ3000_jl7qyupf

### ISSUE THREAD

**Issue by rweise** [dresden-elektronik/deconz-rest-plugin#6870]
## Device

- Product name: (Tuya) 2CH Zigbee Switch Modul-L  
- Manufacturer: _TZ3000_jl7qyupf
- Model identifier: TS0012
- Device type : 2-Way Switch without N  eVatmaster Consulting GmbH
 
<img width="512" alt="Bildschirm­foto 2023-04-07 um 11 52 24" src="https://user-images.githubusercontent.com/13751410/230590241-1f1fc8db-71e1-4915-83dc-fc359d2eea24.png">

## Screenshots

<img width="512" alt="Bildschirm­foto 2023-04-07 um 11 53 06" src="https://user-images.githubusercontent.com/13751410/230590222-229fba86-7c83-4a58-9971-4ad10a9a5068.png">
<img width="241" alt="Bildschirm­foto 2023-04-07 um 12 07 01" src="https://user-images.githubusercontent.com/13751410/230590581-55e41f11-0180-4105-bd34-5acac9463efa.png">

If there are more Information requested, i will do what i can :-) and sorry if it is not a new device. I do not found TZ3000_ji7qyupf in open requests

**Comment by Mimiix** [comment]
Please add all screenshots of all clusters being read( as the template explains).

**Comment by rweise** [comment]
I will do my best to add all screenshots, but it is not easy because that i only have VNC access. So i can not change resolution and deconz gives me only limited access to extend the window. For today i use the _TZ3000_...qew...tch_3gangs.json and modify it like the add on at the end of this post.
Now i can see it in Phoscon and in IOBroker. It works to switch both channels on/off equal witch one i use. It is not perfekt but enough for today. Like i say, i will post all screenshots the next days . 

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_jl7qyupf",
  "modelid": "TS0012",
  "product": "Wired Switch 2 gangs",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/_TZ3000_jl7qyupf_wired_2gangs.json",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 1800
        }
      ]
    }
  ]
}

**Comment by Mimiix** [comment]
> I will do my best to add all screenshots, but it is not easy because that i only have VNC access. So i can not change resolution and deconz gives me only limited access to extend the window. For today i use the _TZ3000_...qew...tch_3gangs.json and modify it like the add on at the end of this post. Now i can see it in Phoscon and in IOBroker. It works to switch both channels on/off equal witch one i use. It is not perfekt but enough for today. Like i say, i will post all screenshots the next days .
> 
> { "schema": "devcap1.schema.json", "manufacturername": "_TZ3000_jl7qyupf", "modelid": "TS0012", "product": "Wired Switch 2 gangs", "sleeper": false, "status": "Gold", "path": "/devices/_TZ3000_jl7qyupf_wired_2gangs.json", "subdevices": [ { "type": "$TYPE_ON_OFF_LIGHT", "restapi": "/lights", "uuid": [ "$address.ext", "0x01" ], "items": [ { "name": "attr/id" }, { "name": "attr/lastannounced" }, { "name": "attr/lastseen" }, { "name": "attr/manufacturername" }, { "name": "attr/modelid" }, { "name": "attr/name" }, { "name": "attr/swversion" }, { "name": "attr/type" }, { "name": "attr/uniqueid" }, { "name": "state/on", "refresh.interval": 5 }, { "name": "state/reachable" } ] }, { "type": "$TYPE_ON_OFF_LIGHT", "restapi": "/lights", "uuid": [ "$address.ext", "0x02" ], "items": [ { "name": "attr/id" }, { "name": "attr/lastannounced" }, { "name": "attr/lastseen" }, { "name": "attr/manufacturername" }, { "name": "attr/modelid" }, { "name": "attr/name" }, { "name": "attr/swversion" }, { "name": "attr/type" }, { "name": "attr/uniqueid" }, { "name": "state/on", "refresh.interval": 5 }, { "name": "state/reachable" } ] } ], "bindings": [ { "bind": "unicast", "src.ep": 1, "cl": "0x0006", "report": [ { "at": "0x0000", "dt": "0x10", "min": 5, "max": 1800 } ] }, { "bind": "unicast", "src.ep": 2, "cl": "0x0006", "report": [ { "at": "0x0000", "dt": "0x10", "min": 5, "max": 1800 } ] } ] }

Without the screenshots, we can't proceed and a dev can't help.

Please add the screenshots.

**Comment by Smanar** [comment]
>Now i can see it in Phoscon and in IOBroker. It works to switch both channels on/off equal witch one i use

You mean you can switch only both channel in same time ?

**Comment by rweise** [comment]
Hi Smanar, yes, if i switch one on in Phoscon or iobroker it takes both to on and vice versa. Only at the switch i can switch them separately.  
<img width="234" alt="Bildschirm­foto 2023-04-08 um 09 02 42" src="https://user-images.githubusercontent.com/13751410/230708528-ff6f1614-f65e-4512-9eb9-4115a4429b27.png">
<img width="658" alt="Bildschirm­foto 2023-04-08 um 09 04 11" src="https://user-images.githubusercontent.com/13751410/230708533-a6f96039-1fd6-438b-8e8e-2e68b9a47590.png">
Here are Identify:
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 13 02" src="https://user-images.githubusercontent.com/13751410/230708694-210af8ae-2709-4c1c-9c41-41a840a1f306.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 13 25" src="https://user-images.githubusercontent.com/13751410/230708696-2491a3a5-fb5f-45b8-99df-888ccf5b7757.png">
Groups :

<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 16 17" src="https://user-images.githubusercontent.com/13751410/230708828-f896456f-5572-4c30-b988-8205f86cf93c.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 16 50" src="https://user-images.githubusercontent.com/13751410/230708831-2cc742d7-a727-4ebd-9ec5-647d4460d160.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 17 20" src="https://user-images.githubusercontent.com/13751410/230708833-f0e8c9e0-5998-4be7-8c80-0dd45666057f.png">
Scenes :
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 20 20" src="https://user-images.githubusercontent.com/13751410/230709022-233941b2-a712-48c7-a405-7d7f3c4feffe.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 20 54" src="https://user-images.githubusercontent.com/13751410/230709035-e126cc1f-6e6d-4855-849e-b8e4e533d0af.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 21 23" src="https://user-images.githubusercontent.com/13751410/230709041-f0b4ef40-1549-4f56-9821-ab6888225e11.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 21 52" src="https://user-images.githubusercontent.com/13751410/230709051-b4dd0efe-2141-4762-8804-03e13f6c6d14.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 22 35" src="https://user-images.githubusercontent.com/13751410/230709057-468ffa20-b424-48cd-88b6-099b2851967f.png">
On/Off (first)
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 24 58" src="https://user-images.githubusercontent.com/13751410/230709261-843d20fe-76f3-4ba9-8dd1-ddc8cc113de7.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 26 04" src="https://user-images.githubusercontent.com/13751410/230709271-e18fe604-4c5e-434a-a9ef-2d62fe74d93e.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 26 33" src="https://user-images.githubusercontent.com/13751410/230709276-1fe61331-431e-4185-a301-9548fe616002.png">
Unknown  is empty
Tuya specific : 
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 30 55" src="https://user-images.githubusercontent.com/13751410/230709422-041a33a4-6fd0-4073-87f5-fe40bf19026f.png">
Basic: 
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 33 16" src="https://user-images.githubusercontent.com/13751410/230709507-37bae183-422e-4d8e-aaca-f9a91655a7a9.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 33 31" src="https://user-images.githubusercontent.com/13751410/230709517-dc964c14-7425-4f5f-ae3e-5b11c6599c0d.png">
Otau: 
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 34 55" src="https://user-images.githubusercontent.com/13751410/230709614-e0aaa521-4b69-4216-98c3-cbc4d941e99e.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 35 30" src="https://user-images.githubusercontent.com/13751410/230709622-dad0d6c4-f4fa-4e85-a15e-9980d8d8d269.png">
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 35 47" src="https://user-images.githubusercontent.com/13751410/230709630-aacabc01-2eaf-4c83-bc11-e02293ffb7eb.png">
Time is empty 
Groups and Scenes from part 2 are the same as the first ones 
And here is On/Off from part 2: 
<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 40 44" src="https://user-images.githubusercontent.com/13751410/230709908-81e61b23-0d95-49fa-aa11-76dfedb4d85b.png">

<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 41 06" src="https://user-images.githubusercontent.com/13751410/230709917-d1483ecd-86ea-47a8-a379-09f6cfc0cf95.png">

<img width="612" alt="Bildschirm­foto 2023-04-08 um 09 41 27" src="https://user-images.githubusercontent.com/13751410/230709921-f35981ef-56df-4818-85ec-034ac8950725.png">

**Comment by Smanar** [comment]
Try with this DDF, I have added the tuya unlock sequence

```
{
   "schema":"devcap1.schema.json",
   "manufacturername":"_TZ3000_jl7qyupf",
   "modelid":"TS0012",
   "product":"Wired Switch 2 gangs",
   "sleeper":false,
   "status":"Gold",
   "path":"/devices/_TZ3000_jl7qyupf_wired_2gangs.json",
   "subdevices":[
      {
         "type":"$TYPE_ON_OFF_LIGHT",
         "restapi":"/lights",
         "uuid":[
            "$address.ext",
            "0x01"
         ],
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"config/interfacemode",
               "refresh.interval":86400,
               "read":{
                  "fn":"zcl",
                  "ep":1,
                  "cl":"0x0000",
                  "at":[
                     "0x0004",
                     "0x0000",
                     "0x0001",
                     "0x0005",
                     "0x0007",
                     "0xfffe"
                  ]
               },
               "parse":{
                  "fn":"zcl",
                  "ep":1,
                  "cl":"0x0000",
                  "at":"0xfffe",
                  "eval":"Item.val = Attr.val"
               },
               "public":false,
               "default":0
            },
            {
               "name":"state/on",
               "refresh.interval":5
            },
            {
               "name":"state/reachable"
            }
         ]
      },
      {
         "type":"$TYPE_ON_OFF_LIGHT",
         "restapi":"/lights",
         "uuid":[
            "$address.ext",
            "0x02"
         ],
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"state/on",
               "refresh.interval":5
            },
            {
               "name":"state/reachable"
            }
         ]
      }
   ],
   "bindings":[
      {
         "bind":"unicast",
         "src.ep":1,
         "cl":"0x0006",
         "report":[
            {
               "at":"0x0000",
               "dt":"0x10",
               "min":5,
               "max":1800
            }
         ]
      },
      {
         "bind":"unicast",
         "src.ep":2,
         "cl":"0x0006",
         "report":[
            {
               "at":"0x0000",
               "dt":"0x10",
               "min":5,
               "max":1800
            }
         ]
      }
   ]
}
```


You can force it with re-including the device (no need to remove it before)

**Comment by BabaIsYou** [comment]
@Smanar , would have been a good candidate for your new specific attrib https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/items/config_tuya_unlock_item.json ? ;-)

**Comment by rweise** [comment]
@Smanar 
Thank you very much, now it works perfekt.
So the Request might be closed. 

Thanks to all at  dresden-elektronik for the phantastic work and also to all supporters and programmers 🥇

**Comment by Mimiix** [comment]
> @Smanar Thank you very much, now it works perfekt. So the Request might be closed.
> 
> Thanks to all at dresden-elektronik for the phantastic work and also to all supporters and programmers 🥇

No closing yet, now we make a PR :)

**Comment by Smanar** [comment]
> @Smanar , would have been a good candidate for your new specific attrib https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/generic/items/config_tuya_unlock_item.json ? ;-)

Lol, yes but it's new, not sure all users have it, I will ask on next one ^^
