### ISSUE TITLE
Salus PS600 Pipe Temperature Sensor

### ISSUE THREAD

**Issue by Carl-mgb66** [dresden-elektronik/deconz-rest-plugin#6871]
## Device

- Product name: Salus PS600 Temperature Sensor
- Manufacturer: Computime
- Model identifier: SS909ZB
- Device type :
  - Sensor

## Clusters of the Node

![image](https://user-images.githubusercontent.com/75570551/230605157-70617780-339f-4a13-ab2a-361fa7adb529.png)

## Node Info Panel

![image](https://user-images.githubusercontent.com/75570551/230606240-e7f6a658-379f-4801-9c53-2f7ea93923f0.png)

### Basic

![image](https://user-images.githubusercontent.com/75570551/230605003-5f68d167-2bf5-40f6-a6ee-20a1baf87b23.png)

### Identify

![image](https://user-images.githubusercontent.com/75570551/230605261-fdadfb75-8895-444a-8946-2a7ac7c94eb0.png)

### Diagnostics

![image](https://user-images.githubusercontent.com/75570551/230605433-64932828-cc6e-4e53-b2eb-7abba80f59d9.png)

### Power Configuration

![image](https://user-images.githubusercontent.com/75570551/230605590-b341505a-24db-4876-b0f0-e26f1018216f.png)

### Poll Control

![image](https://user-images.githubusercontent.com/75570551/230605779-b550a89e-e98a-4680-bf1a-0622487ca7a9.png)

### Temperature Measurement

![image](https://user-images.githubusercontent.com/75570551/230605875-30eaa654-40eb-4c32-ac6f-4a985fa15b19.png)

### IAS Zone

![image](https://user-images.githubusercontent.com/75570551/230605946-0c88820f-b93b-41b9-9017-15af840348b4.png)

**Comment by BabaIsYou** [comment]
Hi,

May be you have to create two files under the folder for DDF files on your system

The first one with a name like `ss909zb_temp_sensor.json `containing 

```

{
  "schema": "devcap1.schema.json",
  "manufacturername": "Computime",
  "modelid": "SS909ZB",
  "product": "Salus PS600 Temperature Sensor",
  "sleeper": true,
  "status": "Silver",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x09",
        "0x0402"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0302",
        "endpoint": "0x09",
        "in": [
          "0x0001",
          "0x0402",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername",
          "awake": true
        },
        {
          "name": "attr/modelid",
          "awake": true
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "awake": true,
          "read": {
            "at": "0x0006",
            "cl": "0x0000",
            "ep": 9,
            "fn": "zcl",
          },
          "parse": {
            "at": "0x0006",
            "cl": "0x0000",
            "ep": 9,
            "fn": "zcl",
            "eval": "Item.val = Attr.val;"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0020",
            "cl": "0x0001",
            "ep": 9,
            "script": "computime_battery.js"
          }
        },
        {
          "name": "config/offset"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 9,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0020",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 9,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 600,
          "change": "0x0000000A"
        }
      ]
    }
  ]
}

```

Then a second file in the same place named `computime_battery.js`
```
const vmax = 30;
let bat = Attr.val;

if      (bat > vmax) { bat = vmax; }
else if (bat < vmin) { bat = vmin; }

bat = ((bat - vmin) /(vmax - vmin)) * 100;

if      (bat > 100) { bat = 100; }
else if (bat <= 0)  { bat = 1; } // ?

Item.val = bat;
```

**Comment by Carl-mgb66** [comment]
Ok, thanks. I'm using deconz in Home Assistant so I'll have to work out where to put these.

**Comment by BabaIsYou** [comment]
You'll have to change DDF level https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-change-DDF-modes-and-enable-or-disable-DDF-levels

**Comment by Carl-mgb66** [comment]
Hi @BabaIsYou - thanks for the help. I've put your suggested files in the appropriate folder, but deconz doesn't seem to be picking them up and if I try to open in the DDF editor it give an error Failed to Open - any thoughts?

**Comment by Carl-mgb66** [comment]
@BabaIsYou - thanks very much - I've managed to get it working now. I found a couple of other typos in the file, I suspect from when I copied it across - all seems good now.

Thanks very much.

**Comment by BabaIsYou** [comment]
Good ! Do you want to make the pull request (PR) to have included in a next release ?

**Comment by Carl-mgb66** [comment]
I would do, just not sure how!

**Comment by BabaIsYou** [comment]
This time it’s not as simple as just adding a .json to a folder ;-)
The folder had to be created (under `devices`) and named `computime-pruse` (would serve for both because Pruse is a sub-brand of Computime and same device could have two different names as clones)  and then the files are to be created in it. 

Github will ask you to commit on master branch then add comments and something like fix #6871 to associate PR to this request.


And that’s it. Don’t worry PR will be reviewed and if something went wrong just delete the PR ;-)

**Comment by Carl-mgb66** [comment]
OK - think I've done that right - let's see, thanks for the help.

**Comment by BabaIsYou** [comment]
Looks Ok, bravo ! ;-)
Just perhaps change "See:" by "Fix" without ":", then github will be able to do the link between the PR and the issue and then close automaticaly the issue once the PR will be merge.

**Comment by Carl-mgb66** [comment]
> I see you did it and the issue is now linked to the PR. Thx

No problem. Thanks for the help.
