### ISSUE TITLE
Avatto Tuya TRV _TZE200_6rdj8dzm

### ISSUE THREAD

**Issue by marten19** [dresden-elektronik/deconz-rest-plugin#6883]
## Device

- Product name: Avatto Tuya Zigbee Radiator Actuator
- Manufacturer: _TZE200_6rdj8dzm
- Model identifier: TS0601
- Device type :
  - Other: TRV

## Device Image
![image](https://user-images.githubusercontent.com/78419356/231458201-b61ced08-ab5e-4519-8194-0cef1657798c.png)

### Basic
![image](https://user-images.githubusercontent.com/78419356/231455881-c8ab9b29-c50d-44c3-9d30-f8424ddf8132.png)

![image](https://user-images.githubusercontent.com/78419356/231456704-9dbfb44d-ed76-40a6-be66-080125050fdd.png)

![image](https://user-images.githubusercontent.com/78419356/231458396-374cd956-0552-40b0-9461-f144325bca38.png)

### Groups
![image](https://user-images.githubusercontent.com/78419356/231456942-a3ece101-f135-494d-a91d-3698ae8e7c0f.png)

### Tuya specific
![image](https://user-images.githubusercontent.com/78419356/231458843-55910917-c373-4e17-ba75-969b769c11e9.png)

### Scenes
![image](https://user-images.githubusercontent.com/78419356/231457220-8740c523-d29d-46ae-8217-b88f583cd6b5.png)

### OTAU
![image](https://user-images.githubusercontent.com/78419356/231461481-92549c8a-6a57-452c-a5e0-6fe2dd670213.png)

### Time
![image](https://user-images.githubusercontent.com/78419356/231458955-9c8fcbc2-df8e-43aa-9d5b-08ba34b04765.png)

**Comment by Mimiix** [comment]
@Smanar  Should be easy?

**Comment by Smanar** [comment]
Sure, can try this DDF to test

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_bvu2wnxz", "_TZE200_6rdj8dzm", "_TZE200_gd4rvykv"],
  "modelid": ["TS0601", "TS0601", "TS0601"],
  "vendor": "Tuya",
  "product": "Tuya TRV",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "meta": {
        "values": {
          "config/mode": {"auto": 0, "heat": 1, "off": 2}
        }
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lowbattery",
          "parse": {"fn": "tuya", "dpid": 35, "eval": "Item.val = Attr.val != 0"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/heatsetpoint",
          "parse": {"fn": "tuya", "dpid": 4, "eval": "Item.val = Attr.val * 10;"},
          "write": {"fn": "tuya", "dpid": 4, "dt": "0x2b", "eval": "Item.val / 10;"},
          "read": {"fn": "tuya"}
        },
        {
          "name": "config/locked",
          "parse": {"fn": "tuya", "dpid": 7, "eval": "Item.val = Attr.val;"},
          "write": {"fn": "tuya", "dpid": 7, "dt": "0x10", "eval": "Item.val;"},
          "read": {"fn": "none"}
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/mode",
          "values": [
              ["auto", 0], ["heat", 1], ["off", 2]
          ],
          "parse": {"fn": "tuya", "dpid": 2, "eval": "if (Attr.val == 0) { Item.val = 'auto' } else if (Attr.val == 1) { Item.val = 'heat' } else { Item.val = 'off' }"},
          "write": {"fn": "tuya", "dpid": 2, "dt": "0x30", "eval": "if (Item.val == 'auto') { 0 } else if (Item.val == 'heat') { 1 } else { 2 }"},
          "read": {"fn": "none"}
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 5, "eval": "Item.val = Attr.val * 10;"},
          "read": {"fn": "none"}
        }
      ]
    }
  ]
}
```

Value probably need to be converted /10 or *10, just give me the value you have and the value you need.

**Comment by marten19** [comment]
Neverminid, a simple reboot seemed to have done the job. 

> Value probably need to be converted /10 or *10, just give me the value you have and the value you need.

What do you mean by _Value_?

Everything seems to be working as expected. Thank you!

**Comment by Smanar** [comment]
>Everything seems to be working as expected. Thank you!

On first try ?

>What do you mean by Value?

You can have as temperature 2 °C instead of 20°C (need *10) or when you set 20°C the device is set to 2°C, for exemple.
But if all is working I can make the PR ?

**Comment by marten19** [comment]
No, I didn't change anything with the code, but at first I had some problems. I was able to read information from the device, but could not change it from the server. However after rebooting I had no issue. 

The temperatures are correctly displayed. So I think it's a go for the PR.

**Comment by e9henrik** [comment]
Hi, I am having challenges controlling and reading from a tuya device with manufacturer name _TZE200_bvu2wnxz which I believe is using this DDF. Attached is an image of this device and it's basic cluster attributes. 
I am expecting to also find a "Thermostat" cluster where I can read and set temperatures, or have I misunderstood?

Thanks! 

![bvu2wnxz](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7380859/e5af9014-d097-45e1-80c2-32bcf66c8446)

**Comment by Smanar** [comment]
No, it's tuya stuff, nothing standard, 
All happen in the tuya cluster.
But the DDF is not working for you ?

**Comment by jannisberry** [comment]
Hi, I have a similar Problem. Mine is from the Manufacturer _TZE200_rtrmfadk. The rest looks exactly like Mentioned by @e9henrik in the Post above. I've tried manually adding it to the DDF, it gets a Thermostat name but doesn't appear in the phoscon app despite the DDF saying it should be in Sensors. The thing is i can see it in the next application in my chain: Homebridge, but it doesn't report any temperature or wants to be set to anything.

**Comment by Smanar** [comment]
You have not same device, for exemple on your temperature is on dpid 3 and setpoint on dpid 2
