### ISSUE TITLE
TS0011 - BSeed Zigbee Smart Wall-Switch

### ISSUE THREAD

**Issue by dpozimski** [dresden-elektronik/deconz-rest-plugin#6885]
## Device

- Product name: BSEED Smart Zigbee Wall-Switch.
- Manufacturer: _TZ3000_hafsqare
- Model identifier: TS0011
- Device type:
- Other: Wall-Switch

### Basic
![image](https://user-images.githubusercontent.com/24246151/231700024-2ca583b6-f264-473e-86da-971af4364a28.png)
![node info](https://user-images.githubusercontent.com/24246151/231698497-b3a0971d-2422-4f48-971a-156b4cef3666.png)
![device](https://user-images.githubusercontent.com/24246151/231699268-6fc31c6c-d07e-439c-9457-e44d58daffaa.png)

### Identify
![identity](https://user-images.githubusercontent.com/24246151/231698530-b9b30bd4-5d9c-49e4-8393-4786dc470eb3.png)

### Groups
![groups](https://user-images.githubusercontent.com/24246151/231698581-29ec0d3d-0ce5-4325-98ae-90b752cdedbb.png)
![groups2](https://user-images.githubusercontent.com/24246151/231698589-52e00dd6-ea3e-4dbe-bc7a-6d6a7c6bff7d.png)

### Scenes
![scenes](https://user-images.githubusercontent.com/24246151/231698622-4d2ded14-db73-46e8-b24c-b64bea88c31f.png)
![scenes2](https://user-images.githubusercontent.com/24246151/231698639-4a418bb8-fb1d-4f8f-86ca-4c342f16e336.png)

### On/Off
![onoff](https://user-images.githubusercontent.com/24246151/231698988-b180cbff-317c-4828-8522-188c43ab2f6c.png)
![onoff2](https://user-images.githubusercontent.com/24246151/231699001-6035c1ee-0594-4f5c-8e25-d140a0939f24.png)

### OTAU
![otau](https://user-images.githubusercontent.com/24246151/231699195-14e55657-e465-4406-afdc-e35d80815c2e.png)

### Tuya Specific
![tuyaspecific](https://user-images.githubusercontent.com/24246151/231699333-57644d89-728c-4a50-bc54-f649d907387f.png)

**Comment by dpozimski** [comment]
### Basic
![basic](https://user-images.githubusercontent.com/24246151/231759787-d4fae924-e873-4e47-9583-6ccc1eb4c5bf.png)


### Identify

![identity](https://user-images.githubusercontent.com/24246151/231759824-075f6dae-1fe9-4e5d-b60e-6c0e853e6643.png)

### Alarms

### Device Temperature

### Groups

![groups](https://user-images.githubusercontent.com/24246151/231759849-2de04fa4-f3ca-40f4-b135-9860d6b7a998.png)

### Scenes
![scenes](https://user-images.githubusercontent.com/24246151/231759910-4fa142f4-0bbe-47ba-92ac-6562f677cc1e.png)


### On/Off
![onoff](https://user-images.githubusercontent.com/24246151/231759928-9523559e-a250-4fa5-a8a4-cd4ab3795123.png)


### Level Control

### Color Control

### Simple Metering

### Diagnostics

### Other clusters that are not mentioned above
![tuyaspecific](https://user-images.githubusercontent.com/24246151/231759964-d3ee7058-3c36-471c-ae30-93294934c322.png)
![nodeinfo](https://user-images.githubusercontent.com/24246151/231760036-3276b2a0-1dcc-4d60-8970-d478a6fd80e2.png)

@BabaIsYou

**Comment by BabaIsYou** [comment]
By the mean time, could perhaps try to adapt the DDF from #6422

**Comment by dpozimski** [comment]
It was not possible to paste it to deconz gui from home Assistant. The ddf json that i found was in preview tab and it could not be edited.

**Comment by BabaIsYou** [comment]
> t was not possible to paste it to deconz gui from home Assistant

It wasn't possible in Deconz GUI, from HA or whatever you use !



> The ddf json that i found was in preview tab and it could not be edited.

DDF has to be stored in a stecific folder (may be could find hints here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6798#issuecomment-1466483973). Then just rejoining the device may be sufficient.

**Comment by dpozimski** [comment]
hi, what is the status of the issue?

**Comment by BabaIsYou** [comment]
Did you have a look at my previous post to give a try to the DDF ? Without someone testing it we couldn’t add it to a version
