### ISSUE TITLE
DC 7-32v Ewelink ZigBee Relay Module (recognized as light should switch)

### ISSUE THREAD

**Issue by kampi9** [dresden-elektronik/deconz-rest-plugin#6888]
## Device

- Product name: DC 7-32v Ewelink ZigBee Relay Module
https://zigbee.blakadder.com/eWeLink_ZB-SW015.html
- Manufacturer: Ewelink
- Model identifier: ZB-SW01
- Device type : 
  - Switch / Relais

Issue is that device can be found in deconz, but is recognized as light. Should work as a switch/relais. which it's doing when you click the manual switch on device itself.

![image](https://user-images.githubusercontent.com/62567187/231790772-4cef1876-2e63-4f22-bff4-effe91a27a53.png)
![image](https://user-images.githubusercontent.com/62567187/231790857-b4679a8c-275b-4097-ab49-7d0a1eb3dd94.png)

### Basic
![image](https://user-images.githubusercontent.com/62567187/231797510-2e28b4bd-df8b-45eb-bced-913cd80cb2eb.png)

### Identify
![image](https://user-images.githubusercontent.com/62567187/231797574-80fb1470-3823-4814-b84b-4e84e25d6fb7.png)

### Groups
![image](https://user-images.githubusercontent.com/62567187/231797788-7a55f71a-96eb-4ee6-be75-e94414af45e1.png)
![image](https://user-images.githubusercontent.com/62567187/231797831-b8c227db-b179-4f4d-ac9b-eb5a71804e7f.png)

### Scenes
![image](https://user-images.githubusercontent.com/62567187/231797922-e358a9ee-e941-4c78-83b1-68d2d77dc4fb.png)
![image](https://user-images.githubusercontent.com/62567187/231797978-110921e7-47db-4f4d-a252-2ff2956dbdcb.png)
![image](https://user-images.githubusercontent.com/62567187/231798036-fdedd149-033c-4e6c-a97a-7bbe94656f1c.png)
![image](https://user-images.githubusercontent.com/62567187/231798087-f02aa468-7fbc-448b-9ffe-17a0aa7ee894.png)

### On/Off
![image](https://user-images.githubusercontent.com/62567187/231798172-37b930fb-49c2-4634-983f-929687531f62.png)
![image](https://user-images.githubusercontent.com/62567187/231798238-ed547813-abff-4269-a38a-4da13fd8dee3.png)
![image](https://user-images.githubusercontent.com/62567187/231798275-4f7172eb-2c3e-4298-96f5-1f038cb9769e.png)

**Comment by Mimiix** [comment]
Please add all requested screenshots.

**Comment by kamiel93** [comment]
Uploaded requested screenshots.

**Comment by BabaIsYou** [comment]
> Uploaded requested screenshots.

Clusters list screenshot is still missing.

**Comment by BabaIsYou** [comment]
In the referenced issue #4642, a reflexion made after the issue had been closed, lead me to do some verification about 0x006 "On/Off server cluster" in Zigbee cluster library.  Then it seems that we did not conform to this in Deconz implementaion : 
**Specification :** 
![image](https://user-images.githubusercontent.com/85300265/231858791-42efb4bc-b93b-445c-9e12-c2a2fd0b2cd9.png)
In **general.xml**  : 
```
    <cluster id="0x0006" name="On/Off">
      <description>Attributes and commands for switching devices between 'On' and 'Off' states.</description>
      <server>
        <attribute-set id="0x0000" description="OnOff state">
          <attribute id="0000" name="OnOff" type="bool" access="r" default="0" required="m">
            <value name="On" value="1"></value>
            <value name="Off" value="0"></value>
          </attribute>
          <attribute id="0x4000" name="GlobalSceneControl" type="bool" access="r" default="0" required="o"></attribute>
          <attribute id="0x4001" name="OnTime" type="u16" access="r" default="0" required="o"></attribute>
          <attribute id="0x4002" name="OffWaitTime" type="u16" access="r" default="0" required="o"></attribute>
          <attribute id="0x4003" name="StartUp OnOff" type="enum8" access="rw" default="0x01" required="o">
            <value name="Off" value="0x00"></value>
            <value name="On" value="0x01"></value>
            <value name="Previous" value="0xff"></value>
          </attribute>
        </attribute-set>
```
Then `GlobalSceneControl` attribute default value should be `0x01` and not `0`
        `OnTime` and `OffwaitTime` attributes should be `rw`

But don't know the consequences of changing these on code behaviour.

**Comment by Mimiix** [comment]
Beat to ask in discord.
