### ISSUE TITLE
Hive Smart Plug being recognised as Light

### ISSUE THREAD

**Issue by xhemp** [dresden-elektronik/deconz-rest-plugin#689]
Greetings!

Just got a Hive Smart Plug and it looks like it's being recognised as a Light.
Attached are some screenshots from the Cluster Node info:

<img width="464" alt="screen shot 2018-07-18 at 11 54 35" src="https://user-images.githubusercontent.com/13650956/42877405-6ae8cb68-8a81-11e8-9ae0-8bdfb05e49d9.png">
<img width="458" alt="screen shot 2018-07-18 at 11 54 08" src="https://user-images.githubusercontent.com/13650956/42877406-6ae8dc48-8a81-11e8-8540-83de7fa3fe2a.png">

Let me know if i can provide anything else.

**Comment by xhemp** [comment]
Cool, thanks for the explanation.
I have taken a screenshot of everything, let me know if there's anything else I can add.

<img width="683" alt="screen shot 2018-07-18 at 13 48 16" src="https://user-images.githubusercontent.com/13650956/42882809-aa9b121a-8a91-11e8-98ef-5d8214577213.png">
<img width="466" alt="screen shot 2018-07-18 at 13 48 30" src="https://user-images.githubusercontent.com/13650956/42882811-aab74598-8a91-11e8-9964-ccfaf15bea65.png">
<img width="453" alt="screen shot 2018-07-18 at 13 48 46" src="https://user-images.githubusercontent.com/13650956/42882812-aad5318e-8a91-11e8-95b4-f765876792a4.png">
<img width="468" alt="screen shot 2018-07-18 at 13 48 56" src="https://user-images.githubusercontent.com/13650956/42882813-aaf1e5a4-8a91-11e8-9e22-0a52db192b59.png">
<img width="468" alt="screen shot 2018-07-18 at 13 49 04" src="https://user-images.githubusercontent.com/13650956/42882816-ab21ce5e-8a91-11e8-9254-374926137b49.png">
<img width="466" alt="screen shot 2018-07-18 at 13 49 11" src="https://user-images.githubusercontent.com/13650956/42882817-ab3b467c-8a91-11e8-9518-007b7d60009c.png">
<img width="468" alt="screen shot 2018-07-18 at 13 52 24" src="https://user-images.githubusercontent.com/13650956/42882895-e988b57c-8a91-11e8-972e-0d1cf424ee28.png">

**Comment by GadgetUK** [comment]
I believe the Salus SP600 the same as the Hive Socket so getting support for this would be great. I'll try and post attributes to confirm
