### ISSUE TITLE
Pairing Broken - KEEN Smart Vent

### ISSUE THREAD

**Issue by mmiller7** [dresden-elektronik/deconz-rest-plugin#6901]
## Describe the bug

When pairing a KEEN smart-vent, the "level control output" is not created in the "lights" page anymore.  This means that it is not possible to finish setting up a new vent.

## Steps to reproduce the behavior

Enter pairing mode in deCONZ
Insert batteries in a factory-reset vent, attempt to connect to network
Wait for join timeout

## Expected behavior

The level-controllable output is created, and the multi-sensor is created

## Environment

 - Host system: PC
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26xxyy00)
 - deCONZ version: Last working: 06.11.1; First known broken: 06.16.0
 - Device: ConBee II
 - Do you use an USB extension cable: Yes-- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? Aeotec Z-Wave, RTL-SDR
 
## Additional context

Previously added smart-vents work fine, but new smart vents will not add correctly in newer deCONZ version.  Had to roll back all the way to 06.11.1 to get it working properly.

**Comment by Mimiix** [comment]
Can you please use deconz versions and not addon versions?

**Comment by mmiller7** [comment]
> Can you please use deconz versions and not addon versions?

I did not know there are different version numbers.  How would I find the correct version number?

**Comment by Mimiix** [comment]
Deconz versions can be found under gateway in Phoscon and under about or help in deconz.

Can you also provide the manufacturer name and model id from the basic cluster for this device?

In the wiki you can find how to read clusters

**Comment by mmiller7** [comment]
Found under Gateway, the last working version I have is 2.13.04 / 12/18/2021

![image](https://user-images.githubusercontent.com/606945/232363058-c4870108-ec08-4b03-a509-332ce39e6607.png)

![image](https://user-images.githubusercontent.com/606945/232362975-bc7b95d6-6179-44fc-9bdb-e0b2e233dac0.png)



Hopefully that is the info you needed?

Later this week if you need samples from a broken newer instance I can do a backup and then test that for you, but I don't know what additional details to capture.

I do know AFTER paired, the newer version continues to work fine...it seems to only be a failure DURING pairing the "light" adjustable level output cover portion is not created in newer versions during pairing

**Comment by Mimiix** [comment]
Seems like the legacy code is not used anymore/removed and there is no DDF yet. 

@ebaauw  I am not sure what to do here as there was never a request for this device(specifically), but i did find you integrating a similar one: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/269. 

Perhaps we just need a new DDF?

**Comment by manup** [comment]
Perhaps we should add a more generic `state/level` attribute similar like it is described in the ZCL Level Control Cluster, which isn't limited to brightness?

**Comment by mmiller7** [comment]
As far as I know this hasn't been fixed.

Anything I can do in the meantime other than sitting on the older version that works?

**Comment by mmiller7** [comment]
Uh, can this be kept open?

As far as I know this hasn't been fixed?

**Comment by Mimiix** [comment]
Hi, Need to respond in time when the bot pings.

**Comment by mmiller7** [comment]
> Hi, Need to respond in time when the bot pings.

Sorry - I thought I was, I didn't see the one between the last reply and when it suddenly said closed

**Comment by mmiller7** [comment]
bump to keep open

**Comment by mmiller7** [comment]
Still open

**Comment by mmiller7** [comment]
Still an issue
