### ISSUE TITLE
Tuya Water Leak Sensor TS0207 | _TZ3000_upgcbody

### ISSUE THREAD

**Issue by theflyer08** [dresden-elektronik/deconz-rest-plugin#6905]
- Product name: Zigbee Water Leak Detector
- Manufacturer: Tuya
- Model identifier: TS0207 _TZ3000_upgcbody
- Device type : Sensor

Unfortunately, I have no screenshots. I would be great if anybody can help with these.

**Comment by Mimiix** [comment]
Hi,

You need to add the screenshots as you own the device.

**Comment by BabaIsYou** [comment]
As soon as the request is completed, we will quickly see if it can still be included in the pending PR #6833 or if a new DDF is needed in case this device is specific and not only a clone.

**Comment by theflyer08** [comment]
> Hi,
> 
> You need to add the screenshots as you own the device.

Can you tell me how I can extract the Screenshots?

**Comment by Mimiix** [comment]
Please check the template that was presented to you during creation. That forwards you to this wiki page:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by theflyer08** [comment]
> You need deCONZ-Gui for this. It can't be achieved with Phoscon.

@Mimiix Thanks a lot for the explanation. Now I get it. Therefore, I need to install a deskop OS and install deCONZ-Gui.
