### ISSUE TITLE
deconz is blocking ttyAMA0

### ISSUE THREAD

**Issue by kami83** [dresden-elektronik/deconz-rest-plugin#691]
Hi,

i am using the ConBee with my raspberry pi. In my system there is a script working together with the /dev/ttyAMA0 port. But always when i start the deconz in the headless mode. My script is crashing. How can i fix this, the deconz is only working together with the Conbee and is not looking for the raspbee?

Thanks a lot.

cu kami

**Comment by manup** [comment]
With latest version you can specify the device also as command line parameter, so that deCONZ will only try to connect to this one.

`--dev=/dev/ttyUSB0`

**Comment by Kane610** [comment]
Pinging @marthoc great improvement for next deconz docker
