### ISSUE TITLE
Luminea Home Control Bewegungs-Melder: ZigBee-kompatibler Outdoor-PIR-Sensor mit Solarpanel, App, IP55 (Bewegungsmelder Solarpanel)

### ISSUE THREAD

**Issue by wunni1** [dresden-elektronik/deconz-rest-plugin#6912]
## Device

- Product name: Luminea Home Control Bewegungs-Melder: ZigBee-kompatibler Outdoor-PIR-Sensor mit Solarpanel, App, IP55 (Bewegungsmelder Solarpanel)
- Manufacturer: _TZ3000_jmrgyl7o
- Model identifier: TS0202
- Device type : Sensor
  

## Screenshots
<img width="682" alt="image" src="https://user-images.githubusercontent.com/73655452/233102059-8be1922d-9e20-4184-b9d3-37e2b056099d.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/73655452/233103902-420f0dea-7bf1-42a9-b873-83c076bb05c5.png">

<img width="599" alt="image" src="https://user-images.githubusercontent.com/73655452/233102726-63f9e4ff-ebda-436d-831a-6d0a79bb855a.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/73655452/233103017-7b04f777-9376-4a51-b4f2-1d21b1e3bdfe.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/73655452/233103232-d3f3f9ca-f6ce-4ba4-8da3-be701440e9ce.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/73655452/233103344-3e357a72-660c-4fc4-bc63-02e92dc3a187.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/73655452/233103470-50f2c0cf-77c2-4dd6-b9c9-4bf19eee35f6.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/73655452/233103625-3f834d47-00c3-4cc6-8335-de38f4deb370.png">

**Comment by BabaIsYou** [comment]
Can you redo screenshots after clicking on "read" button please ?

**Comment by wunni1** [comment]
Oh sorry, here are the new screenshots:

Basic

<img width="739" alt="image" src="https://user-images.githubusercontent.com/73655452/233400494-bebaecc7-00a6-4fc9-b891-5d9fd4c5bc54.png">


Identify

<img width="746" alt="image" src="https://user-images.githubusercontent.com/73655452/233400761-b7fce3fd-903f-4ea6-a985-a603c56f33f7.png">


IAS Zone 1/2

<img width="493" alt="image" src="https://user-images.githubusercontent.com/73655452/233402100-143a19dd-8733-437c-afeb-4ae198f5405a.png">

IAS Zone 2/2
<img width="546" alt="image" src="https://user-images.githubusercontent.com/73655452/233402266-b240064c-3931-49bc-a1af-2d549ac58794.png">

Node Info

<img width="535" alt="image" src="https://user-images.githubusercontent.com/73655452/233403004-8332d75b-017a-4504-ae10-c5d448cbe6a7.png">

OTAU Cluster 1/2

<img width="519" alt="image" src="https://user-images.githubusercontent.com/73655452/233404356-444747d2-d47e-46a2-b7d9-6c6aec5ef1e6.png">

OTAU Cluster 2/2

<img width="488" alt="image" src="https://user-images.githubusercontent.com/73655452/233404530-b7b2dce0-ae18-48e2-8872-449213a53d57.png">

Power Configuration Cluster

<img width="750" alt="image" src="https://user-images.githubusercontent.com/73655452/233405070-61a23d92-6d75-4577-b1ea-a0b357d15894.png">

**Comment by wunni1** [comment]
Thank you, I’ve tried it several times with an other sensor. But I didn’t match it. Run deconz under Home Assistant (no Docker). Can‘t found the path to the file we’re to save. So I‘ve to wait for the next update…

**Comment by BabaIsYou** [comment]
You’ll probably get some hints reading this https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6798#issuecomment-1466483973
