### ISSUE TITLE
Fantem ZB003-X

### ISSUE THREAD

**Issue by pocipocster** [dresden-elektronik/deconz-rest-plugin#6916]
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.
- Model identifier: As per deCONZ GUI Basic cluster.
- Device type : Please remove all unrelated device types. 
  - Light
  - Lock
  - Remote
  - Sensor
  - Siren
  - Switch
  - Thermostat
  - Other:

**Comment by Mimiix** [comment]
Hi, 

Looks like the template is empty.

Can you please make sure all info is added?

**Comment by pocipocster** [comment]
My mistake!. Selected Edit but can't seem too

**Comment by Mimiix** [comment]
Feel free to open a new one if you can't edit  :)

**Comment by Mimiix** [comment]
Closing this one.

**Comment by pocipocster** [comment]
So new one ok ?

Cheers

Sent from my iPhone

On 20 Apr 2023, at 19:32, Dennis D ***@***.***> wrote:

﻿

Closing this one.
