### ISSUE TITLE
TZ3000_w3c7ouru - Moes 3 gang Switch - Long press not recognized

### ISSUE THREAD

**Issue by Sjonnie2018** [dresden-elektronik/deconz-rest-plugin#6918]
EDIT: I inadvertently mislabeled this issue. It should be a bug report. Sorry!

Hi All,

Received the new deCONZ Beta V2.22.0 container today and tested the MOES 3 Gang Switch (TZ3000_w3c7ouru) within deCONZ and Domoticz. The good news is that the switch is seen as a 3 gang switch (4 gang icon in Phoscon but that is probably unrelated) and single click and double click works as expected. I only have a hard time to get the long click (press ;-) ) recognized.

I had the following results in Domoticz:

Left button:
Single click -> value 10
Double click -> value 30
Long click -> no response

Middle button:
Single click -> value 40
Double click -> value 60
Long click -> no response

Right button:
Single click -> value 70
Double click -> value 90
Long click -> no rsponse.

I was expecting values of 20, 50 and 80 respectively.

Is there something I can do to make long click functional?

Note that I am using deCONZ in a container and it seems to be impossible to create a button_maps.json for this device.

Any help appreciated!

## Device

- 
    Product name: MOES Wireless Remote Switch
    Manufacturer: _TZ3000_w3c7ouru
    Model identifier: TS0043
    Device type : 3 gang switch
    Remote: remote

## Screenshots
Sorry that I made screenshots that are not following guidelines but I think you will see the information required. All screenshots were made after pressing the appropriate button on the switch.

![2023-04-20_19-20](https://user-images.githubusercontent.com/41323431/233444742-0ca2614f-599a-45e3-bd68-23d5acb01179.png)
![2023-04-20_19-21](https://user-images.githubusercontent.com/41323431/233444750-1a9deee3-8aeb-4f5f-9aa6-404732f61c8f.png)
![2023-04-20_19-22](https://user-images.githubusercontent.com/41323431/233444754-f4c14ca0-7f93-49b2-a3a2-9bd40d5666cd.png)
![2023-04-20_19-22_1](https://user-images.githubusercontent.com/41323431/233444755-a91ab945-fa6b-4168-8862-727b915a03b5.png)
![2023-04-20_19-23](https://user-images.githubusercontent.com/41323431/233444757-b6548c1f-802a-41d8-95ba-00008df11094.png)
![2023-04-20_19-23_1](https://user-images.githubusercontent.com/41323431/233444758-c44b794a-b90a-4596-8766-b2af2403ebe8.png)
![2023-04-20_19-24](https://user-images.githubusercontent.com/41323431/233444761-66cf5560-04a0-4b18-a4ea-28c881c3151f.png)
![2023-04-20_19-26](https://user-images.githubusercontent.com/41323431/233444762-ac01dc62-31ae-4cc1-9d76-ca6e19692f84.png)
![2023-04-20_19-26_1](https://user-images.githubusercontent.com/41323431/233444766-0ece0a23-a2ef-47cf-af18-686b51cbb188.png)

**Comment by Mimiix** [comment]
Please proceed in the original issue. This scatters the info more.

Closing this.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6724

**Comment by Sjonnie2018** [comment]
I will transfer the information to the original thread tomorrow. Sorry for any inconvenience I caused.
