### ISSUE TITLE
Moes Dual Gang switch

### ISSUE THREAD

**Issue by pocipocster** [dresden-elektronik/deconz-rest-plugin#6921]
## Device

- Product name: Smart switch modules - Zigbee only ( not RF )
- Manufacturer: _TZ3000_pmz6mjyu
- Model identifier: TS011F
- Device type : Please remove all unrelated device types. 

  - Switch dual gang
 

### Other clusters that are not mentioned above
<img width="603" alt="Screenshot 2023-04-21 at 14 43 26" src="https://user-images.githubusercontent.com/67703825/233652244-2b4df854-a032-43db-9107-3aafe05cd1f3.png">
<img width="489" alt="Screenshot 2023-04-21 at 14 42 51" src="https://user-images.githubusercontent.com/67703825/233652256-9e6262b2-aea1-4d3a-b97e-e045d713ae50.png">
<img width="536" alt="Screenshot 2023-04-21 at 14 42 39" src="https://user-images.githubusercontent.com/67703825/233652259-c599678f-7085-4ee5-aa00-3040155cf27e.png">
<img width="568" alt="Screenshot 2023-04-21 at 14 42 19" src="https://user-images.githubusercontent.com/67703825/233652265-6f802fca-77a7-42b9-a3b6-5c598f643ef2.png">
<img width="292" alt="Screenshot 2023-04-21 at 14 42 04" src="https://user-images.githubusercontent.com/67703825/233652273-f51c82dd-47be-48d7-a4cc-5765955597aa.png">

**Comment by pocipocster** [comment]
Shows in Deconz but not found in Phoscon.

**Comment by pocipocster** [comment]
Correction! - this may work and shows up in Phoscon as a light rather than a switch.....

**Comment by pocipocster** [comment]
Phoscon shows it as 2 separate switches (is this correct for 2 gang?). Deconz just shows 1 switch.
What should it be?

**Comment by Smanar** [comment]
Yep, deconz show node, so only 1 by device
Phoson show API entry, so 1 by gangs (and more if you have too power measurement for exemple).

And wired switch are "light", they receive order like a bulb, battery switch can only send order.

**Comment by pocipocster** [comment]
Hi

The switch seems to work fine without this schema . Naming of zigbee modules in phoscon seems a bit strange . The name sometimes gets altered to “ on/off switch “ no matter what I named it .

Sent from my iPhone

On 24 Apr 2023, at 15:42, BabaIsYou ***@***.***> wrote:

﻿

Regarding to previews post is there still an issue with this switch ? Does it works, each switch separatly ?
If not could perhaps try this DDF

{
        "schema": "devcap1.schema.json",
        "manufacturername": ["_TZ3000_pmz6mjyu", "_TZ3000_zmy1waw6"],
        "modelid": ["TS011F", "TS011F"],
        "vendor": "Moes",
        "product": "MS-104BZ Wired Switch 2 gangs",
        "sleeper": false,
        "status": "Gold",
        "subdevices": [{
                        "type": "$TYPE_ON_OFF_LIGHT",
                        "restapi": "/lights",
                        "uuid": [
                                "$address.ext",
                                "0x01"
                        ],
                        "items": [{
                                        "name": "attr/id"
                                },
                                {
                                        "name": "attr/lastannounced"
                                },
                                {
                                        "name": "attr/lastseen"
                                },
                                {
                                        "name": "attr/manufacturername"
                                },
                                {
                                        "name": "attr/modelid"
                                },
                                {
                                        "name": "attr/name"
                                },
                                {
                                        "name": "attr/swversion",
                                        "parse": {
                                                "fn": "zcl",
                                                "ep": 1,
                                                "cl": "0x0000",
                                                "at": "0x0001",
                                                "script": "../tuya/tuya_swversion.js"
                                        },
                                        "read": {
                                                "fn": "zcl",
                                                "ep": 1,
                                                "cl": "0x0000",
                                                "at": "0x0001"
                                        }
                                },
                                {
                                        "name": "attr/type"
                                },
                                {
                                        "name": "attr/uniqueid"
                                },
                                {
                                        "name": "config/tuya_unlock"
                                },
                                {
                                        "name": "state/on"
                                },
                                {
                                        "name": "state/reachable"
                                }
                        ]
                },
                {
                        "type": "$TYPE_ON_OFF_LIGHT",
                        "restapi": "/lights",
                        "uuid": [
                                "$address.ext",
                                "0x02"
                        ],
                        "items": [{
                                        "name": "attr/id"
                                },
                                {
                                        "name": "attr/lastannounced"
                                },
                                {
                                        "name": "attr/lastseen"
                                },
                                {
                                        "name": "attr/manufacturername"
                                },
                                {
                                        "name": "attr/modelid"
                                },
                                {
                                        "name": "attr/name"
                                },
                                {
                                        "name": "attr/swversion",
                                        "parse": {
                                                "fn": "zcl",
                                                "ep": 1,
                                                "cl": "0x0000",
                                                "at": "0x0001",
                                                "script": "../tuya/tuya_swversion.js"
                                        },
                                        "read": {
                                                "fn": "zcl",
                                                "ep": 1,
                                                "cl": "0x0000",
                                                "at": "0x0001"
                                        }
                                },
                                {
                                        "name": "attr/type"
                                },
                                {
                                        "name": "attr/uniqueid"
                                },
                                {
                                        "name": "state/on"
                                },
                                {
                                        "name": "state/reachable"
                                }
                        ]
                }
        ],
        "bindings": [{
                        "bind": "unicast",
                        "src.ep": 1,
                        "cl": "0x0006",
                        "report": [{
                                "at": "0x0000",
                                "dt": "0x10",
                                "min": 5,
                                "max": 1800
                        }]
                },
                {
                        "bind": "unicast",
                        "src.ep": 2,
                        "cl": "0x0006",
                        "report": [{
                                "at": "0x0000",
                                "dt": "0x10",
                                "min": 5,
                                "max": 1800
                        }]
                }
        ]
}

**Comment by BabaIsYou** [comment]
Are you able to test the DDF anyway ? If not then just close the issue if all is ok for you. Thx.

**Comment by pocipocster** [comment]
I can test this if you wish.
Should i see any differences???

cheers

**Comment by pocipocster** [comment]
Ok. I will test this DDF later 👍🏻

**Comment by Tosko4** [comment]
+1 for me 👍🏻
