### ISSUE TITLE
Vendor_TZE204_cjbofhxw  ModelTS0601 - Ampermeter from Matsee

### ISSUE THREAD

**Issue by sajikur** [dresden-elektronik/deconz-rest-plugin#6934]
https://forum.phoscon.de/t/matsee-plus-smart-meter-with-ct/3453/4

https://zigbee.blakadder.com/QS-Zigbee-S05-EC.html
## 
Ampermeter from Matsee Model TS0601

- Product name: Ampermeter from Matsee.
- Manufacturer: Vendor_TZE204_cjbofhxw .
- Model identifier: ModelTS0601.
- Device type : Please remove all unrelated device types. 
  - Other: Amperometer

## Screenshots
![note3](https://user-images.githubusercontent.com/6140894/235131915-4b89bf0d-d895-41dd-92fd-8df5df4c5623.jpg)
![nota2](https://user-images.githubusercontent.com/6140894/235132082-e2fbfa99-c8b2-40c6-aedd-6f20f1b49025.jpg)
![nota1](https://user-images.githubusercontent.com/6140894/235132119-f83b83e4-86e8-48a3-aa42-0317b4d35fb6.jpg)
![nota6](https://user-images.githubusercontent.com/6140894/235142594-fd99fdb2-5f19-4b55-b6cb-85edd3fcdbe4.jpg)

### Groups
![nota7](https://user-images.githubusercontent.com/6140894/235145238-3c11ccbb-115a-438f-97ae-2df8a3941e8c.jpg)
![nota7a](https://user-images.githubusercontent.com/6140894/235145263-c0d28c9b-fde7-43b2-81c5-c91d30da56b1.jpg)

### Scenes
![nota8](https://user-images.githubusercontent.com/6140894/235145622-2c3b200d-e618-4d00-99ee-2a31ea73bcd2.jpg)
![nota8a](https://user-images.githubusercontent.com/6140894/235145642-dd050d39-c706-4848-83ce-72751d5c0378.jpg)

![nota8b](https://user-images.githubusercontent.com/6140894/235145658-364a3454-4d5e-4f53-9ebd-a325c07fd0a7.jpg)

**Comment by Mimiix** [comment]
Missing screeenshots. Please add all.

**Comment by sajikur** [comment]
Hi, thank you for answer. Could you tell me what is the panel you mean?

**Comment by Mimiix** [comment]
The list of clusters under the node on the gui.

**Comment by sajikur** [comment]
It's correct?

**Comment by Mimiix** [comment]
Now we are still missing screens for groups and scenes cluster

**Comment by sajikur** [comment]
well, It's all? Sorry for my little experience in this kind of request

**Comment by Mimiix** [comment]
All good , thanks :)

**Comment by sajikur** [comment]
> All good , thanks :)

Thank you!

**Comment by sajikur** [comment]
hi, any news?

**Comment by Mimiix** [comment]
No dev has picked it up, so no news

**Comment by BabaIsYou** [comment]
May be could try this DDF. Not quite sure about consumption BTW

```
{
	"schema": "devcap1.schema.json",
	"manufacturername": "_TZE204_cjbofhxw",
	"modelid": "TS0601",
	"product": "Ampermeter from Matsee plus",
	"sleeper": false,
	"status": "Gold",
	"subdevices": [{
			"type": "$TYPE_CONSUMPTION_SENSOR",
			"restapi": "/sensors",
			"uuid": [
				"$address.ext",
				"0x01",
				"0x0702"
			],
			"items": [{
					"name": "attr/id"
				},
				{
					"name": "attr/lastannounced"
				},
				{
					"name": "attr/lastseen"
				},
				{
					"name": "attr/manufacturername"
				},
				{
					"name": "attr/modelid"
				},
				{
					"name": "attr/name"
				},
				{
					"name": "attr/swversion",
					"parse": {
						"fn": "zcl",
						"ep": 1,
						"cl": "0x0000",
						"at": "0x0001",
						"script": "tuya_swversion.js"
					},
					"read": {
						"fn": "zcl",
						"ep": 1,
						"cl": "0x0000",
						"at": "0x0001"
					}
				},
				{
					"name": "attr/type"
				},
				{
					"name": "attr/uniqueid"
				},
				{
					"name": "config/offset",
					"default": 0
				},
				{
					"name": "config/on"
				},
				{
					"name": "config/tuya_unlock"
				},
				{
					"name": "config/reachable"
				},
				{
					"name": "state/consumption",
					"parse": {
						"fn": "tuya",
						"dpid": 101,
						"eval": "Item.val = Attr.val / 1000;"
					},
					"read": {
						"fn": "none"
					},
					"default": 0
				},
				{
					"name": "state/lastupdated"
				}
			]
		},
		{
			"type": "$TYPE_POWER_SENSOR",
			"restapi": "/sensors",
			"uuid": [
				"$address.ext",
				"0x01",
				"0x0b04"
			],
			"items": [{
					"name": "attr/id"
				},
				{
					"name": "attr/lastannounced"
				},
				{
					"name": "attr/lastseen"
				},
				{
					"name": "attr/manufacturername"
				},
				{
					"name": "attr/modelid"
				},
				{
					"name": "attr/name"
				},
				{
					"name": "attr/swversion",
					"parse": {
						"fn": "zcl",
						"ep": 1,
						"cl": "0x0000",
						"at": "0x0001",
						"script": "tuya_swversion.js"
					},
					"read": {
						"fn": "none"
					}
				},
				{
					"name": "attr/type"
				},
				{
					"name": "attr/uniqueid"
				},
				{
					"name": "config/offset",
					"default": 0
				},
				{
					"name": "config/on"
				},
				{
					"name": "config/reachable"
				},
				{
					"name": "state/lastupdated"
				},
				{
					"name": "state/current",
					"parse": {
						"fn": "tuya",
						"dpid": 18,
						"eval": "Item.val = Attr.val / 1000;"
					},
					"read": {
						"fn": "none"
					},
					"default": 0
				},
				{
					"name": "state/voltage",
					"parse": {
						"fn": "tuya",
						"dpid": 20,
						"eval": "Item.val = Attr.val / 10;"
					},
					"read": {
						"fn": "none"
					},
					"default": 0
				},
				{
					"name": "state/power",
					"parse": {
						"fn": "tuya",
						"dpid": 19,
						"eval": "Item.val = Attr.val / 10;"
					},
					"read": {
						"fn": "none"
					},
					"default": 0
				}
			]
		}
	]
}
```

**Comment by BabaIsYou** [comment]
> hi, any news?

@sajikur any news from your side ?

**Comment by sajikur** [comment]
> > hi, any news?
> 
> @sajikur any news from your side ?

Unfortunately no new news.  Too bad because the device is really very cheap compared to shelly and it's zigbee

**Comment by sajikur** [comment]
> Did you give a try to the provided DDF

sorry for my incompetence. Could you explain me your post?
thank you

**Comment by BabaIsYou** [comment]
I think you could begin with this : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by sajikur** [comment]
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

thank you, I'll try

**Comment by BabaIsYou** [comment]
Saw it already, but as sajikur has naver mentionned a pairing issue, nor tested the DDF ... issue was staled ...

**Comment by haegar33** [comment]
So the conclusion is: there is no solution for this device and no working deConz implementation? Its a wide spread energy meter on Aliexpress now. In my NodeRed/Deconz setup its quickly recognized, but only as power plug. I tried the DDF mentioned above but no differenz 
<img width="371" alt="basic_cluster" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/22793462/8be662b4-709a-48e6-8463-2cceb275e28d">

**Comment by pdcmoreira** [comment]
@haegar33 For now, I guess there is no working solution and I also stopped trying to make it work. Might try again soon.

**Comment by Mimiix** [comment]
> So the conclusion is: there is no solution for this device and no working deConz implementation? Its a wide spread energy meter on Aliexpress now. In my NodeRed/Deconz setup its quickly recognized, but only as power plug. I tried the DDF mentioned above but no differenz <img alt="basic_cluster" width="371" src="https://user-images.githubusercontent.com/22793462/259144124-8be662b4-709a-48e6-8463-2cceb275e28d.png">

The proposed DDF was never tested.

While testing the DDF, you should see things in the rest api .

**Comment by pdcmoreira** [comment]
Hey @Mimiix what do you mean by this?
>While testing the DDF, you should see things in the rest api .

**Comment by Mimiix** [comment]
The working of the DDF can only be determined by checking the rest api or websocket. Phoscon probably isn't showing anything as it needs to add support on its own.

**Comment by Mimiix** [comment]
This repo only provides support until the api itself .

**Comment by haegar33** [comment]
ok applying the DDF gets a modified REST-api response, but this does not imply that the device is providing values with the defined "attributes" I see that @pdcmoreira and others have tried without success. 
Looks like this is the first China device not working with my setup ;(
Thanks anyway! Haegar

**Comment by haegar33** [comment]
Looking at a similar(?) device discussed here #7151 I changed the DDF entry for ''state/voltage'' as suggested and I get at least a reasonable answer back via REST:
```
   "lastannounced": "2023-08-09T09:12:33Z",
    "lastseen": "2023-08-09T10:21Z",
    "manufacturername": "_TZE204_cjbofhxw",
    "modelid": "TS0601",
    "name": "Power 26",
    "state": {
        "current": 0,
        "lastupdated": "2023-08-09T09:14:29.603",
        "power": 0,
        "voltage": 234
    },
    "type": "ZHAPower",
    "uniqueid": "18:7a:3e:ff:fe:cb:0a:21-01-0b04"
}
```

**Comment by Smanar** [comment]
If you have the GUI, you can take a look in logs with flag "info" and "ddf", you will return from the device (even not managed by deconz)

**Comment by haegar33** [comment]
I have changed:
```
        {
          "name": "state/voltage",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "Item.val = (Attr.val[0] << 8) | Attr.val[1]) / 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
```
thus reading from dpid 6. As I am not an expert in javascript bitfield decodings I could not get current or power. I will try the deCONZ GUI log file

**Comment by Smanar** [comment]
Hu ?
I have checked again, and the model _TZE204_cjbofhxw don't use the dpid 6 but the 20 for voltage ....

Yeah pls, on deconz logs you will be able to see request from the device with "info", and the dpid used by it.

**Comment by pdcmoreira** [comment]
Please keep this open.
