### ISSUE TITLE
Tesla Valve TV100

### ISSUE THREAD

**Issue by ladislav-filip** [dresden-elektronik/deconz-rest-plugin#6938]
## Device

- Product name: Tesla Valve TV100
- Manufacturer: Tesla
- Model identifier: TSL-TVR100-TV01ZG
- Device type : 
  - Thermostat

## Screenshots

![image](https://user-images.githubusercontent.com/22433343/235417086-3ade3666-773a-4807-bdae-ce856809744f.png)

**Comment by Mimiix** [comment]
Hi,
Please add all screenshots.

**Comment by BabaIsYou** [comment]
Duplicate of #6324

**Comment by Mimiix** [comment]
Agree!
