### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by edwin-2023** [dresden-elektronik/deconz-rest-plugin#6939]
## Device

- Product name: The device name as shown on the product or package.
- Manufacturer: As per deCONZ GUI Basic cluster.  LDS
- Model identifier: As per deCONZ GUI Basic cluster.   ZBT-DIMSwitch-D0000
- Device type : Please remove all unrelated device types.   RFD
  - Switch
  - Dim

**Comment by edwin-2023** [comment]
Somehow the screenshots are not visible
![image](https://user-images.githubusercontent.com/132260195/235434357-ebf92a75-fc4b-49ef-8871-c87454196099.png)
![image](https://user-images.githubusercontent.com/132260195/235434382-24065764-2cc5-4756-937b-33b292855286.png)

**Comment by Mimiix** [comment]
Can you please add all screenshots? We need screens of all clusters.

**Comment by edwin-2023** [comment]
What do you mean with all clusters? Where can i find the info you need?

**Comment by edwin-2023** [comment]
Cluster info is empty
![image](https://user-images.githubusercontent.com/132260195/235440017-77a61a88-3cf8-45d1-a986-cf9caf353beb.png)

**Comment by Mimiix** [comment]
As mentioned in the issue template:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

and 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

**Comment by edwin-2023** [comment]
That helps :)
Basic
![image](https://user-images.githubusercontent.com/132260195/235451864-448c5abf-6ef4-4122-9f39-5dcd86d0977b.png)
Power Configuration
![image](https://user-images.githubusercontent.com/132260195/235451940-b8c70812-5d2f-4ec1-8271-1c8ef0992693.png)
Identify
![image](https://user-images.githubusercontent.com/132260195/235452040-a5c05534-b58a-4c04-b925-b99fc15e4648.png)
Diagnostics = all 0
ZLL commisioning
![image](https://user-images.githubusercontent.com/132260195/235452264-9fc7d912-6c5b-4bd8-b7d2-3c3cc676af59.png)
![image](https://user-images.githubusercontent.com/132260195/235452312-bf972031-cecb-403c-9a79-d083b5c20c9a.png)
Do you also need the grey clusters?

**Comment by Mimiix** [comment]
No need for the grey clusters. However ,i'd appreciate it if you put the above screens in the first post of this issue :)

**Comment by Smanar** [comment]
Hello I hope you haven't HA ?
Can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": " LDS",
  "modelid": "ZBT-DIMSwitch-D0000",
  "product": "LDS battery switch",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "refresh.interval": 86400,
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl"
          }
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0008"
    }
  ]
}
```

For the button map can try first to add the device in LDS part in the file button_maps.json
```
        "ZBT-DIMController-D0800Map": {
            "vendor": "LDS",
            "doc": "Mueller-Licht tint dimmer",
            "modelids": ["ZBT-DIMController-D0800", "ZBT-DIMSwitch-D0000"],
```

For missing one, just go in deconz log with flag "info" and "info_l2", and get log when pressing a button, something like
`
15:08:58:374 [INFO] - No button map for: 3AFE280100510001, unicast to: 0x0000, endpoint: 0x01, cluster: ONOFF (0x0006), command: ATTRIBUTE_REPORT (0x0A), payload: 00001080, zclSeq: 6`

**Comment by edwin-2023** [comment]
> No need for the grey clusters. However ,i'd appreciate it if you put the above screens in the first post of this issue :)

Will do, but need a bit of time

**Comment by Smanar** [comment]
It's the standard DDF for all battery remote.

>I'm using HomeSeer as domotic system.

So I think you are in this situation ? (no dockers ?)

> All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.

You just need to create a file called what_you_want.json with the DDF contain in a "devices" folder.
You will found the button_maps.json in /usr/share/deCONZ/devices 'can use a text editor to edit it.

**Comment by edwin-2023** [comment]
Alright i think i got it....
BTW homeseer is a windows based domotica software system but deconz is running on a raspberry pi with a zigbeeII module. So deconz is basiclly running on linux.

DDF is totally new for me. As i understand it i need to copy your post, past in a editor and save the file in /usr/share/deCONZ/devices/ as a file whatever_name.json
Right?

And if it's not working just remove the .json file i created and undo the changes in button-maps

I guess i have to shutdown deconz and phoscon on the raspberry pi, how do i do that? Which commandline to use in terminal?

**Comment by Smanar** [comment]
For exemples, you have 2 "devices" folder.

>And if it's not working just remove the .json file i created and undo the changes in button-maps

No need, if I m bad, it will just not work, no impact on others devices.

>I guess i have to shutdown deconz and phoscon on the raspberry pi, how do i do that? Which commandline to use in terminal?

` sudo reboot`

Agressive method, but working ^^, you have headless setup ? Can just restart the deconz service, but I never tried this command.

`sudo systemctl restart deconz`

**Comment by edwin-2023** [comment]
Making connection via VNC i'm unable to create a file in /usr/share/deCONZ/devices/ via the file explorer. Must be a rights issue. No rightclick sudo option or something like that. Any suggestion?

**Comment by edwin-2023** [comment]
got the file created.
Made a copy of button_maps.json but unable to edit (sudo nano button_maps.json) the original file. My guess is that some (deconz?) locks the file. tried  sudo systemctl stop deconz but no luck
Service -status-all does not show a service that i recognize as being deconz.

So Q. How to edit the button_maps.json file?

**Comment by BabaIsYou** [comment]
From inside terminal you can type `sudo pcmanfm`, will  launch file explorer with privs.
AFAIK `button_maps.json` is not locked by DeConz, then, after having made a copy, you can modify it directly.
`sudo systemctl status deconz `or `sudo systemctl status deconz-gui` will give you information about deconz anyway.

**Comment by edwin-2023** [comment]
Allright. Created the file, edited the button file. Still no luck.
Device does show in phoscon
![image](https://user-images.githubusercontent.com/132260195/235922338-83106c25-895c-499d-bdbc-808193a4a4ce.png)

But in deconz on/off and level are still greyed out
![image](https://user-images.githubusercontent.com/132260195/235922096-6a6580c4-6715-44fc-9e73-e3e340ab47d1.png)

**Comment by BabaIsYou** [comment]
> But in deconz on/off and level are still greyed out

And they will stay because that's the way that the device is exposing these clusters as server clusters.

**Comment by edwin-2023** [comment]
> Be advised it wont show anything in Phoscon. You need to check what the Websocket provides (in phoscon : under Help > Api Information > events). There you should see events when clicking buttons.

> 
> Phoscon needs to add support on its own later.

This is what a have now when pressing button;
![afbeelding](https://user-images.githubusercontent.com/132260195/235955124-0d45235c-31ff-430e-9e6a-c88faa18bd54.png)
Does this mean that for deconz everything is working like its supposed to be?

How do we get the support going in Phoscon?

**Comment by edwin-2023** [comment]
> > But in deconz on/off and level are still greyed out
> 
> And they will stay because that's the way that the device is exposing these clusters as client clusters.

Just looked at another device with dimming and switch capabilities and noticed the same. So all looks good.

**Comment by Smanar** [comment]
> For the button map can try first to add the device in LDS part in the file button_maps.json
> ```
> 
>         "ZBT-DIMController-D0800Map": {
>             "vendor": "LDS",
>             "doc": "Mueller-Licht tint dimmer",
>             "modelids": ["ZBT-DIMController-D0800", "ZBT-DIMSwitch-D0000"],
> ```
> 
> For missing one, just go in deconz log with flag "info" and "info_l2", and get log when pressing a button, something like  15:08:58:374 [INFO] - No button map for: 3AFE280100510001, unicast to: 0x0000, endpoint: 0x01, cluster: ONOFF (0x0006), command: ATTRIBUTE_REPORT (0x0A), payload: 00001080, zclSeq: 6

**Comment by edwin-2023** [comment]
i did edited the button_maps.json file (adding ZBT-DIMSwitch-D0000)

**Comment by edwin-2023** [comment]
this is center switch

16:07:53:611 Poll APS request to 0x385CFBFFFECBB96F cluster: 0x0006 dropped, values are fresh enough
16:07:54:238 [INFO] - No button map for: ZBT-DIMSwitch-D0000, broadcast to: 0x400A, endpoint: 0x01, cluster: ONOFF (0x0006), command: ON (0x01), payload: None, zclSeq: 84
16:07:54:240 Websocket 192.168.140.13:64617 send message: {"attr":{"id":"5","lastannounced":null,"lastseen":"2023-05-03T15:07Z","manufacturername":"LDS","modelid":"ZBT-DIMSwitch-D0000","name":"YNOA ZBT-DIMSwitch-D0000 5","swversion":"2.22","type":"ZHASwitch","uniqueid":"08:6b:d7:ff:fe:fc:a3:66-01-1000"},"e":"changed","id":"5","r":"sensors","t":"event","uniqueid":"08:6b:d7:ff:fe:fc:a3:66-01-1000"} (ret = 2125066264)
16:07:54:242 Websocket 192.168.140.236:50382 send message: {"attr":{"id":"5","lastannounced":null,"lastseen":"2023-05-03T15:07Z","manufacturername":"LDS","modelid":"ZBT-DIMSwitch-D0000","name":"YNOA ZBT-DIMSwitch-D0000 5","swversion":"2.22","type":"ZHASwitch","uniqueid":"08:6b:d7:ff:fe:fc:a3:66-01-1000"},"e":"changed","id":"5","r":"sensors","t":"event","uniqueid":"08:6b:d7:ff:fe:fc:a3:66-01-1000"} (ret = 2125066264)
16:07:54:558 poll node 00:15:8d:00:07:5b:47:f5-01

**Comment by edwin-2023** [comment]
need to go, continue  tomorrow. Sorry,.....

**Comment by edwin-2023** [comment]
i did a full reboot of the pi.
checked the button file, seems ok:
![afbeelding](https://user-images.githubusercontent.com/132260195/236115193-8476cf73-c847-4eb1-a49a-20b12c367aa3.png)

**Comment by edwin-2023** [comment]
Alright, i eddited the button file to add the "
![afbeelding](https://user-images.githubusercontent.com/132260195/236116358-844a08fa-633b-44fb-b5dd-a0c2df02e098.png)
Now i see this in API info when i press the button
![afbeelding](https://user-images.githubusercontent.com/132260195/236116416-d44e57fe-4c03-4a41-8093-f04a73073e62.png)
and in debug
![afbeelding](https://user-images.githubusercontent.com/132260195/236116471-22d455ee-ca52-4f3d-b86d-cf1fffee90ff.png)

**Comment by edwin-2023** [comment]
So, this is how it should be?
Is there a way to get the device supported in Phoscon?

**Comment by Mimiix** [comment]
In your screen, i see twice 1002, not sure if that is correct?

On Homeseer and HA you need to use the Events codes to map to buttons( i am sure for HA, not suire for Homeseer. For HA: https://www.home-assistant.io/integrations/deconz/#remote-control-devices)


For Phoscon, you need to request support on the forums.

**Comment by Mimiix** [comment]
forums.phoscon.de :)

**Comment by Smanar** [comment]
If you miss somes event, just give me the debug output message and the action/button used.

Just need to convert
`16:07:54:238 [INFO] - No button handler for for: ZBT-DIMSwitch-D0000, broadcast to: 0x400A, endpoint: 0x01, cluster: ONOFF (0x0006), command: ON (0x01), payload: None, zclSeq: 84`
in
`
 [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],`

**Comment by edwin-2023** [comment]
> If you miss somes event, just give me the debug output message and the action/button used.
> 
> Just need to convert `16:07:54:238 [INFO] - No button handler for for: ZBT-DIMSwitch-D0000, broadcast to: 0x400A, endpoint: 0x01, cluster: ONOFF (0x0006), command: ON (0x01), payload: None, zclSeq: 84` in ` [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],`

Sorry, missed the message.

Not sure what you mean. Which debug info do you need and where do I need to make a change?

**Comment by Smanar** [comment]
Do you miss somes events ?

**Comment by edwin-2023** [comment]
Not home at the moment. I think I missed long press but will check and come back

**Comment by edwin-2023** [comment]
Just got home and will pickup this later next week.

**Comment by edwin-2023** [comment]
Just tried, it get as status;
- on/off short
- dim up holding
- dim up released long
- dim down holding
- dim down released
So it would say, device is working!
What would be the next step?

**Comment by Smanar** [comment]
Making a PR for the change will be included officially.
I can do it if you have problem, but you can try first, you can't break something, so you can retry if you fail ^^.

**Comment by edwin-2023** [comment]
Hi. If you guide me how to improve will give it a try 😁

**Comment by Smanar** [comment]
I think it will be easier to find a tutorial in your language.
But to make it simple, you need to create a fork (this is automatic is you try to edit the button map file on the official branch).
Then you need to upload a new DDF
And make the PR.
After that your fork will be linked to the PR on this girhub, so you can update your fork, and the change will be automatic

You can do all just with a web browser.

**Comment by edwin-2023** [comment]
Alright, I'm afraid this is totally Spanish for me 🤣
Would appreciate it if you could do this.

**Comment by Smanar** [comment]
PR done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7027
If you can confirm all is ok, and don't need more code edition, Will remove the draft mode (sorry this issue is old, I don't remeber all change)

**Comment by edwin-2023** [comment]
@Smanar. All is ok. Device is operating like it should. Together with Homeseer and the JowiHue plugin I'm able use the button to control event's. Thnx for support and opening PR

**Comment by Smanar** [comment]
Ok thx, PR is ready, now need to wait.

**Comment by edwin-2023** [comment]
Great!

**Comment by edwin-2023** [comment]
Any news on this?

**Comment by Smanar** [comment]
The PR is merged.
It's not woking ATM ?

**Comment by edwin-2023** [comment]
It's absolutely working!

**Comment by Smanar** [comment]
Lol, so which one news do you want  ?

**Comment by edwin-2023** [comment]
Just afraid that when this thread got closed the PR part would stop.

**Comment by Mimiix** [comment]
The pr is done. @Smanar please link the issue to the pr next time so it auto closes :)

**Comment by Smanar** [comment]
Ha yep, sorry my bad.
