### ISSUE TITLE
Teekar Zigbee light switch

### ISSUE THREAD

**Issue by pimperator** [dresden-elektronik/deconz-rest-plugin#6940]
## Device

- Product name: ZigBee Alexa Light Switch
- Manufacturer: _TYZB01_qeqvmvti
- Model identifier: TS0011
- Device type : 
  - Switch

https://www.amazon.de/-/en/gp/product/B095LXWZS5/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

## Screenshots

<img width="384" alt="Bildschirmfoto 2023-05-01 um 19 05 12" src="https://user-images.githubusercontent.com/8807608/235496021-d483b127-8d4e-4345-a1e3-46fde5ae6da7.png">
<img width="243" alt="Bildschirmfoto 2023-05-01 um 19 08 44" src="https://user-images.githubusercontent.com/8807608/235496032-deefc455-11d8-40d5-925a-2389a5fa53a6.png">
<img width="367" alt="Bildschirmfoto 2023-05-01 um 19 19 41" src="https://user-images.githubusercontent.com/8807608/235496034-2cfb8ab7-304d-4b63-9439-96486c8e71fe.png">

<img width="620" alt="Bildschirmfoto 2023-05-01 um 22 40 10" src="https://user-images.githubusercontent.com/8807608/235529007-6f33fc28-03e2-4527-8e4a-9d9d5679705f.png">
<img width="376" alt="Bildschirmfoto 2023-05-01 um 22 41 31" src="https://user-images.githubusercontent.com/8807608/235528999-cac63647-f48c-47f0-ad8e-713eccb7b219.png">
<img width="862" alt="Bildschirmfoto 2023-05-01 um 22 46 53" src="https://user-images.githubusercontent.com/8807608/235529001-1b29fa41-2e0b-4c24-867d-beff8dec5e75.png">
<img width="862" alt="Bildschirmfoto 2023-05-01 um 22 47 19" src="https://user-images.githubusercontent.com/8807608/235529004-2edd0300-24d6-45a5-aa39-1c8658d929c1.png">
<img width="610" alt="Bildschirmfoto 2023-05-01 um 22 49 15" src="https://user-images.githubusercontent.com/8807608/235529011-e1b3719c-f15b-46ae-9e18-b5659b47cf2c.png">
<img width="605" alt="Bildschirmfoto 2023-05-01 um 22 49 33" src="https://user-images.githubusercontent.com/8807608/235529009-9e28776d-bbb3-4816-823d-929e8b51ece0.png">

### Basic
<img width="868" alt="Bildschirmfoto 2023-05-01 um 23 04 35" src="https://user-images.githubusercontent.com/8807608/235531392-41b31ad0-770a-4167-b100-b0ca16295374.png">

### Groups
<img width="625" alt="Bildschirmfoto 2023-05-01 um 23 07 54" src="https://user-images.githubusercontent.com/8807608/235531631-9dce76fd-0b5c-4f01-ab17-f7d1167d3c7b.png">
<img width="626" alt="Bildschirmfoto 2023-05-01 um 23 07 32" src="https://user-images.githubusercontent.com/8807608/235531636-cf272d9e-5840-48e4-b1bb-b73dda45fbb8.png">
<img width="633" alt="Bildschirmfoto 2023-05-01 um 23 07 08" src="https://user-images.githubusercontent.com/8807608/235531638-9f6acf95-4f59-4a57-a019-14dc1a242bcd.png">

### Scenes
<img width="632" alt="Bildschirmfoto 2023-05-01 um 23 09 49" src="https://user-images.githubusercontent.com/8807608/235531870-67f263d2-acb8-41d4-818f-3f64893e6926.png">
<img width="626" alt="Bildschirmfoto 2023-05-01 um 23 09 30" src="https://user-images.githubusercontent.com/8807608/235531872-76e5a189-f9a0-4fc8-9111-9dd97dd82a1a.png">
<img width="631" alt="Bildschirmfoto 2023-05-01 um 23 09 10" src="https://user-images.githubusercontent.com/8807608/235531873-43fb7c93-1092-44f4-b948-cd1db46d0521.png">
<img width="628" alt="Bildschirmfoto 2023-05-01 um 23 08 51" src="https://user-images.githubusercontent.com/8807608/235531879-dad1891e-3bd5-4a91-8c50-de8075639613.png">

### On/Off
<img width="624" alt="Bildschirmfoto 2023-05-01 um 23 10 49" src="https://user-images.githubusercontent.com/8807608/235532026-516e3bb3-9c74-4754-a4d1-130ee611461d.png">
<img width="622" alt="Bildschirmfoto 2023-05-01 um 23 10 32" src="https://user-images.githubusercontent.com/8807608/235532028-692d1d62-a554-4800-9b64-7a97a9f9a21b.png">

### OTAU
<img width="621" alt="Bildschirmfoto 2023-05-01 um 23 12 00" src="https://user-images.githubusercontent.com/8807608/235532262-3a7f6cdc-b1a9-4471-a4a1-6dfc13fdcb14.png">
<img width="622" alt="Bildschirmfoto 2023-05-01 um 23 11 41" src="https://user-images.githubusercontent.com/8807608/235532266-f1efcc9b-0748-4167-8673-aefe84c9c2c5.png">

### Time
<img width="624" alt="Bildschirmfoto 2023-05-01 um 23 12 53" src="https://user-images.githubusercontent.com/8807608/235532373-6de7f15d-4c4e-49b6-ab09-d24612662373.png">

**Comment by pimperator** [comment]
additionally I am not sure wether and how identical these devices are with mine:
https://zigbee.blakadder.com/Tuya_DS-112L-3.html
https://zigbee.blakadder.com/Moes_ZS-EU1-PNW.html

at least the exterior appearance seems to be the same

**Comment by Mimiix** [comment]
Can you please read the template properly and provide all screenshots and details as requested ?

**Comment by pimperator** [comment]
@Mimiix I've updated the data. I guess you miss manufacturer and model but no matter how often I push the 'read' button in 'Cluster info' the fields are not being provided.
Sadly only after messing around for a longer time I found those information:
<img width="864" alt="Bildschirmfoto 2023-05-01 um 22 58 58" src="https://user-images.githubusercontent.com/8807608/235530324-64c47e6d-a831-4eff-9733-11e28a587131.png">

I will adjust these above

**Comment by BabaIsYou** [comment]
Surprisingly this device was already recognized in 2021 #4896 ... and no more today ?

**Comment by pimperator** [comment]
@BabaIsYou it works! 
Indeed it seems like the same device is handled in #4896
At first when I created the ticket (note: this is my first one) I sadly was unaware where to gather the information and the manufacturer and model was shown as unknown. Also there are a bunch of other switches with different model id so I was not sure.

Additionally even when #4896 covered this device and I can see the device id by searching in two different [tickets](https://github.com/dresden-elektronik/deconz-rest-plugin/search?q=TS0011) the manufacturer is missing in the whole repo (see [here](https://github.com/dresden-elektronik/deconz-rest-plugin/search?q=_TYZB01_qeqvmvti))
