### ISSUE TITLE
Tuya ZTH01 not working

### ISSUE THREAD

**Issue by HellStorm666** [dresden-elektronik/deconz-rest-plugin#6942]
Hi all,

Bought 5 tuya ZTH01 temperature and humidity sensors to monitor the refrigerators and freezers.
But, I can't pair them to deconz conbee 2.
Can someone confirm if these are supported?
And if not, could it be added asap? (zigbee2mqtt does support it, but am already on the phoscon train and love it.).

**Comment by Mimiix** [comment]
Hi,

I am closing this as there is no template used. Questions like this belong to the forums.

Closing & locking.

Kind regards,
