### ISSUE TITLE
Heiman Smoke Sensor - no state updates - after upgrade from stable deconz 2.12 --> 2.21.2

### ISSUE THREAD

**Issue by BeamMeUpTo** [dresden-elektronik/deconz-rest-plugin#6952]
I upgraded my deCONZ version from deCONZ stable 2.12 to stable 2.21.2. 
Firmware of ConBeeII was upgraded to version 26780700.

My zigbee network has about 63 nodes with nodes/plugs from Ledvance/Osram, Innr, Nous, Ikea, Heiman
and with several endpoints: Aqara sensors, Eurotronic ZigBee Spirit, Tradfri Motion sensors - all working excellent with the new versions!!!

## Describe the bug

I start deCONZ gui-mode and can see deconz establishing drawn connections to all of my devices at startup - even to all of my smoke sensors with all states (battery,state,reachable,..) are getting updated once.

I have got a total of 15 Heiman smoke sensors in 3 groups of clones with different Problems:
- 7 Schwaiger ZHS20 (Heiman HS1SA-M - Model Identifier: SMOK_YDLV10 DateCode: 20150330)
==> Are all getting state updates in between 3-10 hours! BUT: Phoscon shows a few of them as "not reachable" although they were updated successfully before.

- 3 Orvibio SF21 smoke sensor swversion 1.1.1
==> Are reachable on deconz startup with all states getting updated, but after that, they never get updated again.
I can see the sensors talking to deconz from time to time - blue dot blinking. But no refreshing of the states. 

- 5 Heiman SmokeSensor-EF-3.0 DateCode: 2020.7.10
==> Are reachable on deconz startup with all states getting updated, but after that they never get updated again.
The same here - blue dot blinking. But no refreshing of the states.

## Steps to reproduce the behavior

Start deconz gui mode - every node and sensor found! 
Only effected Heimans get no status update at all, but are talking to the mesh from time to time. But (perhaps) nobody listens to them ...
Tested over 35 hours!!! No updates!

## Expected behavior

Like in deconz Version 2.12 before - every smoke sensor sends state updates (batteryPercent,batteryState,reachable,state) fire in within max 10 hours to deconz/phoscon. All kinds of Heiman clones did this before.

## Screenshots

Status update in between 3-10 hours - battery, reachable, 
## Environment

 - Host system: Raspberry Pi 4
 - Running method: Raspbian Buster
 - Firmware version: 26780700
 - deCONZ version: (2.21.02)
 - Device:  ConBee II
 - Do you use an USB extension cable: yes

## deCONZ Logs

Tell me whats needed - I will post them. Which debug levels are important???

**Comment by Mimiix** [comment]
Hi,

As this bug report is not as described in #5113, i am closing this issue.

Feel free to open a topic on the forums, with logs. Under the deCONZ category on the forums you can find out what logs we need and what log levels.

Kind regards,
Dennis
