### ISSUE TITLE
Adeo LDSENK09 Key FOB 4 buttons

### ISSUE THREAD

**Issue by didjoss** [dresden-elektronik/deconz-rest-plugin#6973]
Adeo LDSENK09
## Device

- Product name: smart remote control  Lexman Leroy Merlin
- Manufacturer: Adeo
- Model identifier: LDSENK09
- Device type :  
  - Switch  / Keyfob

With this buttons_map.json 

        "AdeoKeyfobMap": {
            "vendor": "Adeo",
            "doc": "4 buttons remotes from Adeo",
            "modelids": ["LDSENK09"],
            "map": [
                [1, "0x01", "IAS_ACE", "ARM", "1", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Arm day/home zones only"],
                [1, "0x01", "IAS_ACE", "ARM", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Disarm"],
                [1, "0x01", "IAS_ACE", "EMERGENCY", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "Emergency"],
                [1, "0x01", "IAS_ACE", "ARM", "3", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "Arm all zones"]
            ]
        }

AND With the DDF file at the end of this message,  and adapted from Immax 07046L_keyfob.json , the keyfob works but only with the keys disarm,arm all and arm day  :-). 

18:37:19:900 [INFO] - Button 4002 - LDSENK09, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ACE (0x0501), action: Arm all zones, payload: 030064, zclSeq: 13
18:38:20:861 [INFO] - Button 2002 - LDSENK09, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ACE (0x0501), action: Disarm, payload: 000064, zclSeq: 17
18:39:27:360 [INFO] - Button 1002 - LDSENK09, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ACE (0x0501), action: Arm day/home zones only, payload: 010064, zclSeq: 18

The keys SOS is not recognized : 

18:41:21:773 [INFO] - No button handler for: LDSENK09, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ACE (0x0501), command: 0x04, payload: None, zclSeq: 25
18:41:21:783 Warning duplicated zcl.cmd: 0x04, cluster: 0x0501 with zcl.seq: 25 for ADEO / LDSENK09
18:41:21:783 [INFO] - No button handler for: LDSENK09, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ACE (0x0501), command: 0x04, payload: None, zclSeq: 25

SO, how to handler this button ?
 

{
  "schema":"devcap1.schema.json",
  "manufacturername": "ADEO",
  "modelid": "LDSENK09",
  "product": "LDSENK09",
  "status": "Gold",
  "path": "/devices/adeo/ldsenk09.json",
   "vendor":"Adeo",
   "sleeper":true,
   "subdevices":[
      {
         "type":"$TYPE_SWITCH",
         "restapi":"/sensors",
         "uuid":[
            "$address.ext",
            "0x01",
            "0x0500"
         ],
         "fingerprint":{
            "profile":"0x0104",
            "device":"0x0401",
            "endpoint":"0x01",
            "in":[
               "0x0000",
               "0x0500"
		],
	    "out":[	
               "0x0501"
            ]
         },
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"config/enrolled",
               "public":false
            },
            {
               "name":"config/on"
            },
            {
               "name":"config/pending"
            },
            {
               "name":"config/reachable"
            },
            {
            	"name": "state/buttonevent",
		"awake": true
            },
            {
               "name":"state/lastupdated"
            },
            {
               "name":"state/lowbattery"
            }
         ]
      }
   ],
   "bindings":[
      {
         "bind":"unicast",
         "src.ep":1,
         "cl":"0x0500"
      },
      {
         "bind":"unicast",
         "src.ep":1,
         "cl":"0x0501"
      }
   ]
}

**Comment by didjoss** [comment]
after add information, i reopen this request

**Comment by Mimiix** [comment]
Hi please add all requested screenshots.

**Comment by didjoss** [comment]
Yes , i forgetten them.
Screenshots
Cluster
![cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93873938/6b870530-f077-45cd-9aaa-d2001f802428)

Node info:
![nodeinfo](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93873938/d429c521-9ddc-4d51-bf3a-dbf6d4a3ce43)

Basic:
![basic](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93873938/7948bfbe-cc3d-485c-93b6-6560b2fa6836)

Identify:
![identify](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93873938/9a8a527d-31b1-4495-8e1d-4855fb29bd2d)

Alarm/IASZONE
![iaszone](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93873938/623e02e3-1752-47df-b993-4bf2455513f8)

Diagnostics
![diag](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93873938/1a668a5e-03d5-4609-8dde-5e81b8c0284e)

Other clusters that are not mentioned above

**Comment by didjoss** [comment]
For IASZone , zone ID, now it's 0 ...

**Comment by didjoss** [comment]
Okay it's done on the same post with screenshots

**Comment by didjoss** [comment]
THanks for your answer.
I try it ... but it's almost the same ... 

17:58:55:378 [INFO] - No button handler for: LDSENK09, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ACE (0x0501), command: SOS (0x04), payload: None, zclSeq: 6

I think the problem is in de_web_plugin.php in  DeRestPluginPrivate::checkSensorButtonEvent , the error message 'No button handler' is from this. The command 0x04 isn't recognized ?

**Comment by Smanar** [comment]
Harrrr, you are right

```
                else if (ind.clusterId() == IAS_ACE_CLUSTER_ID)
                {
                    ok = false;
                    if (zclFrame.commandId() == 0x00 && zclFrame.payload().size() == 3 && buttonMap.zclParam0 == zclFrame.payload().at(0))
                    {
                        ok = true;
                    }
                    else if (zclFrame.commandId() == 0x02 && zclFrame.payload().isEmpty())
                    {
                        ok = true;
                    }
                }
```

There is something bad in the c++ code, that enable only some request ......

What is your OS ? We will need to edit the c++ code, not possible only with DDF because the device use different command.

**Comment by didjoss** [comment]
On raspbian. I can test if you give me the partial code. I know how to compile. But to test, i have only this ias Switch....

**Comment by Smanar** [comment]
You haven't problem to compile ? Else I can give you the command line to use ?
I have started to make a new branch if you can't compile on your side `https://github.com/Smanar/deconz-rest-plugin/tree/Adeo_7`

The usefull part for you is here https://github.com/Smanar/deconz-rest-plugin/commit/b5db305d39cb8bddbbda02ee65f72b41c4253fe5

**Comment by didjoss** [comment]
Fine !!! It's working !
Thanks very much for your fast answer !!!

I also remove the binding for the cluster 0x500 in LDSENK09.json

And if another device come with the command 0x05 ?   ;-) 
Perhaps this test is better : 

5221: else if (zclFrame.payload().isEmpty())
or
5221: else if ((zclFrame.commandId() <= 0x0F ) && zclFrame.payload().isEmpty())

What do you think about it ?

In buttons_maps,json: 
"AdeoKeyfobMap": {
            "vendor": "Adeo",
            "doc": "4 buttons remotes from Adeo",
            "modelids": ["LDSENK09"],
            "map": [
                [1, "0x01", "IAS_ACE", "ARM", "3", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Arm all zones"],
                [1, "0x01", "IAS_ACE", "ARM", "1", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Arm day/home zones only"],
                [1, "0x01", "IAS_ACE", "ARM", "0", "S_BUTTON_3", "S_BUTTON_ACTION_SHORT_RELEASED", "Disarm"],
                [1, "0x01", "IAS_ACE", "SOS", "0", "S_BUTTON_4", "S_BUTTON_ACTION_SHORT_RELEASED", "Sos"],
            ]
        },

I think  you can do a pull request for ADEO / LSENK09 ;-) 

Best regards
Didier

**Comment by Smanar** [comment]
```
#define IAS_ACE_CMD_ARM 0x00
#define IAS_ACE_CMD_BYPASS 0x01
#define IAS_ACE_CMD_EMERGENCY 0x02
#define IAS_ACE_CMD_FIRE 0x03
#define IAS_ACE_CMD_PANIC 0x04
#define IAS_ACE_CMD_GET_ZONE_ID_MAP 0x05
#define IAS_ACE_CMD_GET_ZONE_INFORMATION 0x06
#define IAS_ACE_CMD_GET_PANEL_STATUS 0x07
#define IAS_ACE_CMD_GET_BYPASSED_ZONE_LIST 0x08
#define IAS_ACE_CMD_GET_ZONE_STATUS 0x09
```

0x05 is a GET_ZONE_ID_MAP request, so for me used for more advanced device than a simple remote.

And I m agress with you, IDK why a blacklist is used here, but I prefer don't break the code of another dev, I can be sure only for 3 and 4 ATM ^^

And as you seem to have enought knowledge for that, do you want to make the PR yourself or want I make it myself ?

**Comment by didjoss** [comment]
OK 
for optimization and keep the blacklist, i propose: 
5221: else if ((zclFrame.commandId() < 0x05 ) && zclFrame.payload().isEmpty())

YOU have done the job, so i prefer that you make the pull request but if you have no time to do it, i can  this next week ...

**Comment by Smanar** [comment]
The 0x00 is already handled by code, so it will just add the command 0x01 and same than for the 0x05, a "bypass" request, not sure this one can be present on a remote command.

I have updated the button map with your code, your device don't have the "EMERGENCY" request ?

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6990

**Comment by didjoss** [comment]
no, only sos cmd ( 0x04 ) 
Thank you for your job.
