### ISSUE TITLE
EGLO Crosslink 2 Motion Sensor

### ISSUE THREAD

**Issue by jeceka201** [dresden-elektronik/deconz-rest-plugin#6996]
A IP44 motion sensor sold under the EGLO Crosslink 2 brand.  

## Device

- Product name: EGLO crosslink 2 motion sensor.
- Manufacturer: Awox.
- Model identifier: TLSR82xx.
- Device type : 
  - Sensor

## Screenshots

  Required screenshots:
  - Endpoints and clusters of the node
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/5e6d9a5d-d027-4ee9-85d6-6e804774a110)
  - Node Info panel
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/0b9e3fa2-6417-4dc8-9f95-801ea192f75c)

### Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/a81320ab-bb04-40b9-a38d-36b0c164de11)

### Identify
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/9eab3cf9-c997-442d-9a88-98c87cdffc9e)

### Groups
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/141ded72-9da0-4729-b914-a7560736c8c9)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/39248e58-2ea6-440a-9888-daebf9b22bd2)

### Other clusters that are not mentioned above
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26722271/d1373bd1-3f5a-4f8c-aea3-c14a50d22dd2)

**Comment by jeceka201** [comment]
I tried to Frankestein a DDF but my knowledge is lacking. So no luck. Any help?

**Comment by BabaIsYou** [comment]
It seems that quitte all Eglo devices use the same manufacture name and modelid ... Then even if we could make a DDF ,  that one would be loaded for all other Eglo devices :-/

**Comment by jeceka201** [comment]
> It seems that quitte all Eglo devices use the same manufacture name and modelid ... Then even if we could make a DDF , that one would be loaded for all other Eglo devices :-/

That's unfortunate. And a good reason not to buy any more of their products. If I wanted to make my own DDF, where do I look for al the right values? Or do I need to sniff the Zigbee network to figure out how a device really communicates?

**Comment by BabaIsYou** [comment]
As far as I can see, this device seesm not to provide any information about occupancy on standard Zigbee cluster. It seems to provided them using manufacturer specific clusters 0xFF50 and 0xFF551 on Endpoint 0x03. And at this time I didn't find any information about these clusters.
