### ISSUE TITLE
Any chance of getting a new release of deCONZ for x86 Linux so we can run the REST plugin on it?

### ISSUE THREAD

**Issue by FeepingCreature** [dresden-elektronik/deconz-rest-plugin#7]
Hi,

as the title says. I have a deRFUSB stick and would really like to use the API instead of the cumbersome GUI.

**Comment by SpencerSharkey** [comment]
same.

**Comment by manup** [comment]
Hello, meanwhile there are public versions for Raspberry Pi (Raspbian), Ubuntu x86 and Windows.
The development instructions for this plugin repository are suitable for ARM and x86 Linux.

https://www.dresden-elektronik.de/funktechnik/products/software/pc/deconz/

**Comment by FeepingCreature** [comment]
Thank you!
