### ISSUE TITLE
Raspberry cam as motion sensor?

### ISSUE THREAD

**Issue by perler** [dresden-elektronik/deconz-rest-plugin#70]
Is it possible to use the [raspberry pi camera module](https://www.raspberrypi.org/products/camera-module-v2/) as a motion sensor for deconz?

**Comment by manup** [comment]
Not out-of-the-box but it should be possible by using a `CLIPPresence` sensor which is controlled by an external python script, which monitors the camera.

**Comment by manup** [comment]
Closing the oldest issues for know to tidy up the tracker and duplicates in newer issues.
