### ISSUE TITLE
Tongou DIN Rail Circuit Breaker 63A with Power Monitoring

### ISSUE THREAD

**Issue by cornim** [dresden-elektronik/deconz-rest-plugin#7011]
## Device

- Product name: [Tongou DIN Rail Circuit Breaker 63A with Power Monitoring](https://zigbee.blakadder.com/Tongou_TO-Q-SY1-JZT.html)
- Manufacturer: _TZ3000_qeuvnohg
- Model identifier: TS011F
- Device type :
  - Sensor
  - Switch

### Node Info
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/2ab0c235-95db-40ba-95bf-619fb2c59286)

### Cluster List
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/d2e9854e-84b8-41f7-95b2-886b26f6c2f3)

### Basic
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/7c03563c-c22f-463d-b8ca-f2c639679e18)

### Identify
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/7ae18828-f9a3-434c-8903-a45f1e726be7)

### Groups
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/15efbf7e-f6e0-4bbb-af79-2f72e482ba9a)

### Scenes
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/4513a99b-a042-482b-9176-82d501991359)

### On/Off
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/015a7948-2b01-4192-b24c-b46d8ff108bc)

### Simple Metering
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/6e83bb03-3949-43b8-b276-4f451c02040e)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/1e0e6585-2aab-480f-ad22-9e66ba7ef477)

### Electrical Measurement
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/a02e3360-10a5-4f93-83d1-41044e4536bf)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/a00d8e80-1b14-405f-bc0d-6c4afa752605)

### Temperature measurement
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/9dde3309-0c9c-4b2c-a81f-38516bd1947e)

### Unknown
 -no attributes-

### Tuya specific
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/4417017/07100443-0b03-4a8e-b045-258587d9962c)

**Comment by cornim** [comment]
The DDF seems to work. I get consumption power and temperature as additional endpoints in HA now.

Thanks.

**Comment by Smanar** [comment]
>but the power measurement cluster (0x0B04) has 3 report bindings

It's the binded attributes inside this cluster, it's not a zigbee adress.

**Comment by BabaIsYou** [comment]
@cornim Do you want to make the pull request (PR) to have this DDF shared into a next release ?
