### ISSUE TITLE
deconz service will not start any more

### ISSUE THREAD

**Issue by vzografos** [dresden-elektronik/deconz-rest-plugin#7025]
## Environment

HEADLESS: NO GUI
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
- device RaspBee I

deconz         2.22.00-raspbian-buster-beta armhf
deconz_cli_plugin from source 2.04.35

**Comment by Mimiix** [comment]
Hi,

As this is not a bug report as described in #5113 i am closing this issue.

This might be your issue : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6937 

Please use the forum for furthur help as i am closing this one.

Additionally, opening 2 issues (this and #7026) is not really how this works.

Closing & locking.

Kind regards,
