### ISSUE TITLE
Any way to know if any of the lights in a group is off?

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#703]
I'd like to have a `any_off` parameter, so that I can quickly check if any light of a given group is off (I need this to automate a light switch).

Is there any API to get this information? If possible through Home Assistant it'd be even better.

**Comment by ebaauw** [comment]
Check whether `state.all_on` equals false.

**Comment by mariusmotea** [comment]
If  `"all_on":false` and `"any_on":true` then "any_off" will be true

**Comment by FezVrasta** [comment]
Thank you for the replies! Are any of these properties exposed through Home Assistant maybe?

**Comment by Kane610** [comment]
@FezVrasta why don't you move over all devices to deconz?

**Comment by FezVrasta** [comment]
I have a Philips TV with Ambilight+Hue (quite old) that doesn't play nicely with DeCONZ. I tried the DIYHue project but it adds a lot of latency... So I'm keeping the Hue bridge around just for the living room bulbs until I change TV with a newer model that may play better with DeCONZ.

**Comment by Kane610** [comment]
@FezVrasta I have added an all_on attribute to groups, fix for this here: https://github.com/home-assistant/home-assistant/pull/15752/commits/9c181d920efbbb3a718535e447a29d47690092b2
