### ISSUE TITLE
GIEXperience / Tuya Soil Sensor GXM-01

### ISSUE THREAD

**Issue by aldoushx** [dresden-elektronik/deconz-rest-plugin#7033]
## Device

- Product name: Soil Sensor GXM-01
- Manufacturer: GIEXperience / Tuya
- Model identifier: GXM-01
- Device type :  
  - Sensor (humidity, temperature)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35113380/4ca95b1e-cde3-43ad-81c0-fde15a1d595d)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35113380/5e9c631f-1139-4254-bd4f-04bb8dbb71c9)

**Comment by Mimiix** [comment]
Duplicate of https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6731
