### ISSUE TITLE
Sonoff SNZB-02D instead of SNZB-04

### ISSUE THREAD

**Issue by poltergejst** [dresden-elektronik/deconz-rest-plugin#7036]
Deconz found Multisensor SNZB-02D instead of SNZB-04.

  1. Go to Phoscon App
  2. Click on search new sensor
  3. Pair SNZB-04
  4. Get Multisensor

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/26001463/476ce916-aac4-4233-b091-ca895c46fce7)

**Comment by Mimiix** [comment]
Hi,

There's a template for a reason.

Try again, but following the rules now.
