### ISSUE TITLE
apt repo down

### ISSUE THREAD

**Issue by MasterofKungfu9999** [dresden-elektronik/deconz-rest-plugin#7040]
Currently http://phoscon.de/apt/deconz shows 404 , but according to https://phoscon.de/de/conbee2/install#raspbian this is still the correct URL.

Fehlschlag beim Holen von http://phoscon.de/apt/deconz/pool/main/d/deconz/deconz_2.21.02-raspbian-buster-stable_armhf.deb 404  Not Found [IP: 144.76.96.194 80]

**Comment by Mimiix** [comment]
Hi,
Please use the template as inteded. Additionally, this belongs on the forums as it has nothing to do with the Rest Plugin.

Closing.
