### ISSUE TITLE
EARU 1P MCB

### ISSUE THREAD

**Issue by SheriffDeputy** [dresden-elektronik/deconz-rest-plugin#7047]
## Device

- Product name: EARU EAYCBM-Z 1P : MCB- Micro circuit breaker
- Manufacturer:_TZE204_davzgqq0
- Model identifier: TS0601
- Device type  
  - Switch

## Screenshots

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45880789/8e0f5105-ba7c-4aac-8d7d-ebb372c3a862)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45880789/ed089611-afad-4591-8d31-7be3839a94c8)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45880789/e0d060ce-3a75-4c5b-bff0-5a123a38dce8)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45880789/8b380b75-d2ba-4cd9-9779-d8b41b5d8522)

### Other clusters that are not mentioned above
[deconz_logs.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/11714793/deconz_logs.log)

**Comment by Mimiix** [comment]
Hi,

Please add screenshots of all clusters.

**Comment by Smanar** [comment]
Can start with this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE204_davzgqq0",
  "modelid": "TS0601",
  "product": "EAYCBM-Z 1P",
  "vendor": "Tuya",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {
            "fn": "tuya",
            "dpid": 16,
            "eval": "Item.val = Attr.val;"
          },
          "write": {
            "fn": "tuya",
            "dpid": 16,
            "dt": "0x10",
            "eval": "Item.val == 1 ? 1 : 0;"
          },
          "read": {
            "fn": "tuya"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "parse": {
            "fn": "tuya",
            "dpid": 1,
            "eval": "Item.val = Attr.val * 10;"
          },
          "read": {
            "fn": "none"
          },
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": []
}
```

If I m right you will have on/off and consumption, for values will be harder, it seem they are all in the same dpid https://github.com/zigpy/zha-device-handlers/issues/2061#issuecomment-1575572651

**Comment by SheriffDeputy** [comment]
I loaded this JSON DDF in deconz but still the same behaviour

**Comment by Mimiix** [comment]
Please provide all screenshots.

**Comment by SheriffDeputy** [comment]
> Please provide all screenshots.

What screen shot should I post?

**Comment by Mimiix** [comment]
@Smanar why did this change ?

**Comment by SheriffDeputy** [comment]
After switching it off and on again it seems to be back as it was
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45880789/0546d9a6-84fe-4f5b-9720-f2437861f4ba)

**Comment by Mimiix** [comment]
The ias ace is also missing ?

**Comment by Smanar** [comment]
Loool, I think it's a realy stable device.
But from I m reading, all cluster are useless, then can come and leave, they are useless, this device use only the tuya cluster 0xEF00

With or without DDF you will see (at least need to see, but it seem it's random on this device) the same thing.
The only difference will be on the API.
Just add the DDF and re-include the device, don't care at what you can see in deconz, only check the difference in the API.

**Comment by SheriffDeputy** [comment]
After removing and re-adding the device in deconz, it still does not work. However home assistant now detects the switch and a sensor for the consumption. None of them works (the sensor is always 0).

Also now in home assistant I can see an error when I toggle the swith. It says the service call failed as the control is not available

**Comment by SheriffDeputy** [comment]
> Please provide all screenshots.

are you still waiting for screenshots? if so what exactly?

**Comment by Mimiix** [comment]
> > Please provide all screenshots.
> 
> are you still waiting for screenshots? if so what exactly?

Not sure.

@Smanar which ones do we like?

**Comment by Smanar** [comment]
Good question, I think for this device you can start direclty with the DDF.
From that I m reading on other zigbee project, all others clusters are useless, and from your tests totally random ^^.

If I m right only the tuya one is usefull, and for this one you can't have attribute.
So I think we can start with that, we will see later if we need the other "garbage" clusters.

**Comment by SheriffDeputy** [comment]
> Good question, I think for this device you can start direclty with testing the DDF. From that I m reading on other zigbee project, all others clusters are useless, and from your tests totally random ^^.
> 
> If I m right only the tuya one is usefull, and for this one you can't have attribute using the GUI. So I think we can start with that, we will see later if we need the other "garbage" clusters.

Thank you Smanar for your help.
The DDF  above does not work. It expose the power control (but no value is retrieved) but does not allow for the on/off service.

here the tuya tab (virtually empty)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45880789/c7bc2d7a-a17a-467e-9c58-9cdcb03ebebd)

**Comment by SheriffDeputy** [comment]
> > The DDF above does not work. It expose the power control (but no value is retrieved) but does not allow for the on/off service.
> 
> Wich one entry you have in API ? Visible with Phoscon/help/API Information (then lights and sensors, the DDF create 2 entries) You are using phoscon to test the on/off ? You can use the "previous DDF" entry in API, you have deleted the device before re-including after the DDF ?
> 
> You haven't "tuya debug" with flag "info" on deconz ?
> 
> `"TY_DATA_%s: seq %u, dpid: 0x%02X, type: 0x%02X, length: %u, val: %d\n",`

1) I am using phoscon deconz on/off feature but not always visible.

2) I have delete and readded the device many times after adding the previous ddf (saved as json file) in the /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices 
please note the filehas been saved there and no folder for manufacture

3)Sorry I am a newbe on phoscon/deconz/zigbee. I do not understand how to enable the TUYA debugging. how can I start deconz with tuya debug flag?

**Comment by Mimiix** [comment]
Please keep open until merged.

**Comment by Smanar** [comment]
Yep third app are able to act direclty on the API (and not deconz).
If it work we can add later tension/current but need more code in DDF. So better to keep this issue opened.
