### ISSUE TITLE
DIY CC2530 with ptvo firmware - Implementationin Deconze?

### ISSUE THREAD

**Issue by Maschler** [dresden-elektronik/deconz-rest-plugin#7056]
## Describe the bug
Hello, i flashed a CC25301 chip with ptvo firmware, the purpose is to return a on/off switch status. But something is strange. 

After flashing I can pair the cc2530 with my conbee2. I can see the device and also switch the input via the interface of Deconz (conbee2). BUT that's it.

In the web interface of the Conbee2 (Phoscon) the thing is not shown at the devices (light/sensor/switch). At the Node Info there is also only a "cryptic" name. Normally the name of the device is to be seen there like e.g. "Tradfri on/off...". Also in the Node List all the usual information is empty.

Is there something like a device description missing so it shows up in Phoscon as a light/sensor/switch?

Thanks !

## Device

    Product name: DIY CC2530 with ptvo firmware
    Manufacturer: N/A
    Model identifier: N/A
    Deconz v2.21.02
    Firmware:0x26780700
    Raspberry
    Device type :
        On/Off output

## Screenshots
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/5876a17b-346a-4798-9f2b-35e8ea51af3a)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/1bfcb220-235c-413f-bf67-5fc70b9fa146)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/66d12d9d-e843-4a15-b6e1-052dc828c774)

**Screenshot of the Basic cluster**
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/45272337-d951-49ce-82ac-9e73a00b1908)

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/6f675152-ea64-4966-8156-4aa78c86f79c)

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/59e69877-467d-406e-8b45-b9835548b8cc)

**Screenshot of the Node Info Panel**
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/142cc4e8-6f42-46bf-aa84-e0dd3ab5ae86)

### On/Off cluster
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/c5a5ab28-eb95-47f2-9961-17f1e50756b5)

By the way. The configuration Tool for the ptvo firmware also provides a "custom converter for Z2M". Here is the content of the .js file:

```
const zigbeeHerdsmanConverters = require('zigbee-herdsman-converters');
const zigbeeHerdsmanUtils = require('zigbee-herdsman-converters/lib/utils');


const exposes = zigbeeHerdsmanConverters.exposes;
const ea = exposes.access;
const e = exposes.presets;
const fz = zigbeeHerdsmanConverters.fromZigbeeConverters;
const tz = zigbeeHerdsmanConverters.toZigbeeConverters;

const ptvo_switch = zigbeeHerdsmanConverters.findByDevice({modelID: 'ptvo.switch'});
fz.legacy = ptvo_switch.meta.tuyaThermostatPreset;
fz.ptvo_on_off = {
  cluster: 'genOnOff',
  type: ['attributeReport', 'readResponse'],
  convert: (model, msg, publish, options, meta) => {
      if (msg.data.hasOwnProperty('onOff')) {
          const channel = msg.endpoint.ID;
          const endpointName = `l${channel}`;
          const binaryEndpoint = model.meta && model.meta.binaryEndpoints && model.meta.binaryEndpoints[endpointName];
          const prefix = (binaryEndpoint) ? model.meta.binaryEndpoints[endpointName] : 'state';
          const property = `${prefix}_${endpointName}`;
	  if (binaryEndpoint) {
            return {[property]: msg.data['onOff'] === 1};
          }
          return {[property]: msg.data['onOff'] === 1 ? 'ON' : 'OFF'};
      }
  },
};



const device = {
    zigbeeModel: ['ptvo test'],
    model: 'ptvo test',
    vendor: 'ptvo info',
    description: '[Configurable firmware](https://ptvo.info/zigbee-configurable-firmware-features/)',
    fromZigbee: [fz.ignore_basic_report, fz.ptvo_on_off,],
    toZigbee: [tz.ptvo_switch_trigger, tz.on_off,],
    exposes: [e.switch().withEndpoint('l1'),
],
    meta: {
        multiEndpoint: true,
        
    },
    endpoint: (device) => {
        return {
            l1: 1,
        };
    },
    configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
      await endpoint.read('genBasic', ['modelId', 'swBuildId', 'powerSource']);
    },

};

module.exports = device;
```

Is this useable for adopting a ddf?

**Comment by BabaIsYou** [comment]
Your device is not already supported by Deconz (that's why it's name is hexadecimal). Need to add a DDF file for it and then will be recognized by REST-API and perhaps by Phoscon.

Could you provide all the screenshots asked by the template for opening device request issue ?

**Comment by Maschler** [comment]
Thank you for the answer. I saw that something similar was done here. 


Since this is not yet my final configuration (wanted to understand the workflow first) it probably doesn't make sense to create a .dff now. 

But can I create something like that myself? Is there an editor or a manual for it?

[dresden-elektronik/deconz-rest-plugin/issues/5496](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5496)

**Comment by Mimiix** [comment]
Please add all requested screenshots.

**Comment by Maschler** [comment]
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/eafe0f59-2d5f-43fa-baa5-fba150719e99)

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/d7c1016a-7fcf-475c-9d94-689128327fde)

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/38862834/2fa21d42-1a94-4104-b671-b2f18bd37b85)

**Comment by Maschler** [comment]
By the way. The configuration Tool for the ptvo firmware also provides a "custom converter for Z2M". Here is the content of the .js file:

```
const zigbeeHerdsmanConverters = require('zigbee-herdsman-converters');
const zigbeeHerdsmanUtils = require('zigbee-herdsman-converters/lib/utils');


const exposes = zigbeeHerdsmanConverters.exposes;
const ea = exposes.access;
const e = exposes.presets;
const fz = zigbeeHerdsmanConverters.fromZigbeeConverters;
const tz = zigbeeHerdsmanConverters.toZigbeeConverters;

const ptvo_switch = zigbeeHerdsmanConverters.findByDevice({modelID: 'ptvo.switch'});
fz.legacy = ptvo_switch.meta.tuyaThermostatPreset;
fz.ptvo_on_off = {
  cluster: 'genOnOff',
  type: ['attributeReport', 'readResponse'],
  convert: (model, msg, publish, options, meta) => {
      if (msg.data.hasOwnProperty('onOff')) {
          const channel = msg.endpoint.ID;
          const endpointName = `l${channel}`;
          const binaryEndpoint = model.meta && model.meta.binaryEndpoints && model.meta.binaryEndpoints[endpointName];
          const prefix = (binaryEndpoint) ? model.meta.binaryEndpoints[endpointName] : 'state';
          const property = `${prefix}_${endpointName}`;
	  if (binaryEndpoint) {
            return {[property]: msg.data['onOff'] === 1};
          }
          return {[property]: msg.data['onOff'] === 1 ? 'ON' : 'OFF'};
      }
  },
};



const device = {
    zigbeeModel: ['ptvo test'],
    model: 'ptvo test',
    vendor: 'ptvo info',
    description: '[Configurable firmware](https://ptvo.info/zigbee-configurable-firmware-features/)',
    fromZigbee: [fz.ignore_basic_report, fz.ptvo_on_off,],
    toZigbee: [tz.ptvo_switch_trigger, tz.on_off,],
    exposes: [e.switch().withEndpoint('l1'),
],
    meta: {
        multiEndpoint: true,
        
    },
    endpoint: (device) => {
        return {
            l1: 1,
        };
    },
    configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
      await endpoint.read('genBasic', ['modelId', 'swBuildId', 'powerSource']);
    },

};

module.exports = device;
```


Is this useable for adopting a ddf?

**Comment by BabaIsYou** [comment]
> But can I create something like that myself? Is there an editor or a manual for it?

May be you could try with this : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by BabaIsYou** [comment]
> **Screenshot of the Basic cluster** 
> 

> 
> 
> 
> **Screenshot of the Node Info Panel** 

Screenshot of the On/Off cluster is still missing.

**Comment by Maschler** [comment]
Added at the end.

**Comment by Mimiix** [comment]
Please add them to the original post

**Comment by Maschler** [comment]
Done.

**Comment by Mimiix** [comment]
Thanks :)

**Comment by BabaIsYou** [comment]
> > But can I create something like that myself? Is there an editor or a manual for it?
> 
> May be you could try with this : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

@Maschler did you get a chance to read this ?
