### ISSUE TITLE
SilverCrest Smart Plug

### ISSUE THREAD

**Issue by KatyPurry** [dresden-elektronik/deconz-rest-plugin#7064]
## Device

- Product name: SilverCrest Smart Plug (I didn't find the official english name, only written in FR/DE/NL on the box)
- Manufacturer: _TZ3000_ynmowqk2
- Model identifier:  TS011F
- Device type : Please remove all unrelated device types. 
  - Router

## Screenshots

![image](https://www.lidl.cz/assets/gcpd59ca0d40f634436a55771be4ddb1b50.jpeg)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/27f942d0-1320-4bf6-a330-3120a959108f)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/4bd7e322-a0f2-42ed-a462-e91f3b73a2b9)

### Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/ad8924ed-386b-4f8b-90ce-14ca590ace8a)

### Identify
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/d354a2ee-f9ba-4df1-bdc4-892b6b2e6850)

### Groups
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/0fabe7b3-6f08-4d66-a4ea-e661515e0cd6)

### Scenes
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/de174079-9dc0-4669-a009-e31514594479)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/75cffdaf-465b-45e4-9218-9e54a2eb6247)

### Simple Metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/b815555b-407f-4e99-b947-e2401ee12344)

### Electrical Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/1e1e5d36-8259-4087-b139-ce6ea7c47c64)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/e59cc11a-73bd-489d-837c-1c518174bd5a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/6eb87cc3-ebd9-4cf3-bead-b08ea559c29d)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/4dbeac4b-d905-4c13-a6c8-1bf09d8bf136)

**Comment by BabaIsYou** [comment]
This device seems already supported :  https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/lidl/hg08673.json.

Do you have some trouble ?

**Comment by KatyPurry** [comment]
Thank you for your answer, i already checked Silver but it doesn't change. Is there anything else I need to do? 

> After changing that, you can simply load your DDF and "Hot Reload" to make it work.

What does it means ? How "load your DDF" ? Sorry English isn't my native language

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/89610869/49976ae8-72b1-45dd-a5c7-95fb628987a2)

**Comment by BabaIsYou** [comment]
Select your device, then Ctrl + E, ` File` / `Open` / select your DDF file / `File` / `Hot relaod` and verifiy that the DDF is loaded without error at the bootom of the screen ...

**Comment by KatyPurry** [comment]
Thank you very much ! It’s working 
![Uploading IMG_2011.png…]()

**Comment by Mimiix** [comment]
Case closed :)
