### ISSUE TITLE
Hue App not working?

### ISSUE THREAD

**Issue by Seaha4487** [dresden-elektronik/deconz-rest-plugin#708]
Hey i searched the net for 6 Hours without no result.
The Raspbee and the Phoscon webapp works just fine and i am also able to switch my hue bulb on and off. But i want to do this with Alexa and that this works i have to get the hue app working because of the skill for alexa.
My Problem is that the Hue App finds my Raspee but then i should name a Room and thats the problem i can not save this Room there is always an Errormessage.
Any Ideas

**Comment by ebaauw** [comment]
There’s some sublte differences between the Hue API and the deCONZ API., notably around scenes and groups (which Hue uses for rooms).  Consequently, the Hue app doesn’t work fully in combination with deCONZ.

**Comment by Seaha4487** [comment]
Hmm okay. But some guys say it worked but the dont say how. You say its not working fully okay but by me its totally not working. Is there no way to connect to the original hue app.

**Comment by mariusmotea** [comment]
On way is to use this https://github.com/mariusmotea/diyHue

**Comment by KodeCR** [comment]
The hue app now requires an https connection to the bridge it seems. Without it you can’t connect to deconz from the Philips hue app at all. See 
https://github.com/mariusmotea/diyHue/issues/284 and #675.
@manup would it be possible to add support for this?

**Comment by mariusmotea** [comment]
The certificate must contain the bridge serial number in CN and certificate serial (hex to decimal). The certificate generation i made it to be public service because  some people with older version of openssl complain about some errors during generation. I can share openssl syntax if needed.
