### ISSUE TITLE
IKEA Styrbar battery remaining percentage is not correct

### ISSUE THREAD

**Issue by Gloomyeye** [dresden-elektronik/deconz-rest-plugin#7088]
## Describe the bug

The issue #6761 with the pull request #6984 corrects the left and right buttons. However, after installing the current deconz version 2.22.2, the battery level of my IKEA styrbar with firmware 2.4.5 is always 0 in home assistant.
There was no success with a new reconnect / deletion of the device in deconz.

## Steps to reproduce the behavior

Check the battery percentage remaining attribute of the device

<img width="580" alt="Bildschirmfoto 2023-07-05 um 14 28 31" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/69754128/92ef4895-0f44-4ee0-b6fd-e9e89b9c7bc4">

## Expected behavior

The battery level / remaining percentage of the device should be given.

## Screenshots

<img width="894" alt="Bildschirmfoto 2023-07-05 um 14 23 54" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/69754128/617ff00a-a5a0-4791-9561-908a55bc0dfe">

<img width="619" alt="Bildschirmfoto 2023-07-05 um 14 23 47" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/69754128/6376ce0e-3a13-4ef8-9d58-73cb14b8048b">

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Raspbian with Docker container for Deconz and Home Assistant
 - Firmware version: 26780700
 - deCONZ version: 2.22.2
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## Additional context

This is the DDF binding:
```

  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_IKEA",
  "modelid": "Remote Control N2",
  "product": "STYRBAR remote control",
  "sleeper": true,
  "status": "Gold",
  "path": "/devices/ikea/styrbar_remote_control.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x1000"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0820",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x1000"
        ],
        "out": [
          "0x0006",
          "0x0008",
          "0x0005"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Math.round(Attr.val / 2)",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0008"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0005"
    }
  ]
}
```

**Comment by Gloomyeye** [comment]
@ebaauw : Maybe you can verify this with your device. Do you have the same behaviour?

**Comment by ebaauw** [comment]
Mine reports _Battery Percentage Remaining_ as 200 in the GUI and `config/battery` 100 in the API.

Double-check by reading the _Power Configuration_ cluster attributes in the GUI, while pressing buttons on the STYRBAR. to make sure it's awake.  If it still reports 255, you might need to remove and re-insert the battery.

**Comment by Gloomyeye** [comment]
Ah! Thanks for your quick response! That worked. Removing and inserting again the battery was the solution. Now, it reports 200 and not 255 (like before).
