### ISSUE TITLE
GiEX QT06 Smart irrigation valve

### ISSUE THREAD

**Issue by bennydiamond** [dresden-elektronik/deconz-rest-plugin#7103]
## Device

- Product name: GiEX QT06 smart irrigation valve
- Manufacturer: _TZE200_a7sghmms
- Model identifier: TS0601
- Device type : Irrigation Valve
  - Sensor
  - Switch

## Screenshots

![endpoints](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/6563977/60b008a0-2f98-4ab2-9a2b-e86d34a3a07b)
![basic_cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/6563977/f3b7dba1-6019-4fca-a3a7-9026a34efaff)
![Nodeinfo](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/6563977/9bdffeaa-020f-4ff4-adc4-0841d6f405d1)

### Basic
![basic_cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/6563977/dba60cde-1176-41fa-9f35-d682c368b9a1)

**Comment by bennydiamond** [comment]
Device already supported and documented in other Zigbee software suites:
https://zigbee.blakadder.com/GiEX_QT06.html
https://www.zigbee2mqtt.io/devices/QT06_2.html

**Comment by bennydiamond** [comment]
Thank, pardon my ignorance but I have no clue on how to do that!
I'm running the deCONZ official addon for Hassio.
I tryed adding a json file in the container at location `/usr/share/deCONZ/devices/tuya` but it is deleted on addon restart...

**Comment by BEskandari** [comment]
Try this https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6944
A Pull request was submitted https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6947

**Comment by milkplus27** [comment]
> Thank, pardon my ignorance but I have no clue on how to do that! I'm running the deCONZ official addon for Hassio. I tryed adding a json file in the container at location `/usr/share/deCONZ/devices/tuya` but it is deleted on addon restart...

hey there! I've also just purchased one of these GiEx Zigbee water valves and am running deCONZ in HA via a Conbee II - but seem incapable of getting it to pair. Did you have any luck in the end?

**Comment by bennydiamond** [comment]
Follow this video tutorial: https://www.youtube.com/watch?v=rgTQpOVg8w0

If you're using the Official HA deConz addon. Add the DDF file from above in the following relative directory path from the root of your Home Assistant config folder: `addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices/tuya`. You should only have to create the `devices` and `tuya`(optional) folder. All the other ones should already be there.

**Comment by milkplus27** [comment]
Awesome, thank you! I will give this a go. Then once the DDF file is added, do you have to load it from within deCONZ? And afterwards do you add the Giex valve as a an 'Other' switch in Phoscon?

**Comment by milkplus27** [comment]
> Add the DDF file from above in the following relative directory path from the root of your Home Assistant config folder: `addons/data/core_deconz/.local/share/dresden-elektronik/deCONZ/devices/tuya`

hmm, these folders don't seem to exist. the addons folder in my HA config folder is empty. which tbh... seems a bit odd as i have a bunch of addons

**Comment by milkplus27** [comment]
oh, you know what? I managed to figure it out... just has to delete the node from deCONZ and re-add and now it's showing up in HA. excellent. thanks for the assist :)
