### ISSUE TITLE
Strange LCL003 issue

### ISSUE THREAD

**Issue by posixx** [dresden-elektronik/deconz-rest-plugin#7105]
I have an issue with one of my LCL003 (Hue outdoor strip) device. I have 3 of them, only one does have the folllowing issue:

It is reported OK, but does not react to commands; does not go on/off, color change etc. This behaviour can be solved by:
- power cycling the LCL003; works for couple of hours
- remove device from deconz; light goes on immedialely and is found when searching for new lights --> works again for some hours

But, everytime it will eventially give the same problem; does not react to commands..

![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2280400/41c1a121-502d-472f-a813-0546eeafbd4a)

What to do? can this be a Hue light problem / warranty?

**Comment by Mimiix** [comment]
Hi,

This is not how bug reports are intended and the template should be used.

Im closing the issue. Feel free of creating a new one with proper template usage.

Closing.
