### ISSUE TITLE
View Zigbee mesh with Hass.io on RPi with Raspbee Premium and Deconz add-on

### ISSUE THREAD

**Issue by JBS5** [dresden-elektronik/deconz-rest-plugin#711]
I am wondering if it is possible to view the zigbee mesh when using Hass.io on a Raspberry Pi with a Raspbee Premium and the Deconz add-on? Any change to to using using e.g. xming?

**Comment by jantje88** [comment]
Any change this is possible @ebaauw ?

**Comment by ebaauw** [comment]
Why do you ask me?  I don't know anything about Hass.io nor the deconz add-on for it, but I guess it uses the deCONZ REST API.  There is an undocumented (and unmaintained?) endpoint in the REST API to deliver the neighbour information of a light, but last time I tried that, it caused deCONZ to crash.  See https://github.com/dresden-elektronik/deconz-rest-plugin/blob/9989b3efce58551710af89893060fe1b214d622c/rest_lights.cpp#L1629

**Comment by jantje88** [comment]
Saw your posts in many other issues and was hoping you also know something about this question :-)
Thanks for your reply. Maybe this helps others to jump into this. I suppose that I am not the only one with Hass.io and a raspbee and wish to see the zigee mesh.
