### ISSUE TITLE
Tuya Gas Leakage Detector TS0601/ _TZE200_mby4kbtq

### ISSUE THREAD

**Issue by KD9742** [dresden-elektronik/deconz-rest-plugin#7111]
## Device

- Product name: Tuya Smart ZigBee Gas Leakage Detector Sensor
- Manufacturer: _TZE200_mby4kbtq
- Model identifier: TS0601
- Device type : 
  - Sensor

## Screenshots

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/67157340-0421-4cae-968e-4ef599d30333)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/983a08f8-b860-4cc0-83d0-3de84663e5b2)

### Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/514b1627-6879-44be-a708-43af48c280c9)

### Groups
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/3b56e11b-e15b-4e06-9127-773c06df1275)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/113226b0-8372-474c-9c36-413d89108525)

### Scenes
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/81d6f28a-920f-4668-af69-03a99cb14d2c)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/60be9de8-666d-43df-b93c-c67f90d540d4)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/007bfa37-9f61-40ec-85d3-81b77fcd38d6)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/dbe00ec9-f85d-44cc-9c17-f37436608ce5)

### Other clusters that are not mentioned above
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/8a8e4003-7cc2-46b8-a22b-b7584bfd3d22)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/d339da75-6c17-49cc-a53f-2ab70b58aca4)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/b7308b98-3630-4cae-bb5a-8cf03603daa5)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/93686466/f5320ebe-c9f1-45d1-b312-c00b95212d0e)

**Comment by KD9742** [comment]
👀

**Comment by Mimiix** [comment]
@Smanar  perhaps?

**Comment by ebaauw** [comment]
> First question, there is no "gas sensor"

We expose other natural gas sensors as ZHAFire, since this is combustable gas.

**Comment by KD9742** [comment]
It is displaying as a sensor now, I'll set it off when I get home to verify the state changes. Thank you!

**Comment by KD9742** [comment]
So the state is reversed. When the alarm is going off it changes to safe and when it stops going off it changes to unsafe. I did try changing the default value for the alarm state to false but it didn't change the states being reversed.

**Comment by Smanar** [comment]
@ebaauw is right, better to use a ZHAFire.

Sorry, to prevent problem, better to delete your device, use the new DDF and re-include the device.
Have reversed the state too.
The value in "state/pm2_5" is fine too ? Perhaps need a convertion ?

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_mby4kbtq",
  "modelid": "TS0601",
  "vendor": "Tuya",
  "product": "Gas Leakage Detector",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_FIRE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/fire",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = (Attr.val == 0);" },
          "read": {"fn": "tuya"},
          "default": 0
        },
        {
          "name": "state/pm2_5",
          "parse": {"fn": "tuya", "dpid": 2, "eval": "Item.val = Attr.val;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

**Comment by KD9742** [comment]
That worked, the states are in the correct order! Thank you!
