### ISSUE TITLE
OTAU for Ubisys

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#712]
I found Ubisys released a newer version, 2018Q1, of their firmware (see http://ubisys.de/smarthome/download-firmware.html).  I downloaded it to the ~/otau directory, and it seems deCONZ v2.05.32 with RaspBee firmware 261F0500 picked it up alright.  Initially the upgrade aborted, but it seems it has been applied overnight anyways:
![untitled](https://user-images.githubusercontent.com/22179355/43780373-ba1a9278-9a5a-11e8-97fc-a1f4e2dd8c58.jpeg)

Checking the OTAU cluster, it seems like the firmware was installed to the dimmer:
![untitled 2](https://user-images.githubusercontent.com/22179355/43780382-c1b9164e-9a5a-11e8-8acb-c9d4cfd0a871.jpeg)

However, the _Basic_ clusters still report the old version (01020105, if memory serves):
![untitled 3](https://user-images.githubusercontent.com/22179355/43780473-f5291ce0-9a5a-11e8-860e-3f57998837cf.jpeg)

Do I need to do anything to activate the newly downloaded firmware?  I power cycled the dimmer to no avail.  Also, the D1's technical reference gives no clue.

**Comment by ebaauw** [comment]
According to the ZCL spec, _Data Code_ is the manufacturing date, not the date of the firmware.

**Comment by ebaauw** [comment]
The 2019Q1 ubisys firmware is out: http://share.ubisys.de/ubisys-zigbee-firmware-2019-q1.zip.   They're re-doing their website, so it's not yet listed there.  deCONZ seemed happy to install it, in 31:18 minutes.

![screenshot 2019-02-20 at 20 44](https://user-images.githubusercontent.com/22179355/53119897-cf1dc000-3550-11e9-91b0-c713a90ed3b8.png)

ubisys support tell me this version should fix the weird values of _Current Summation Delivered_, as they'll be reporting consumption through their gateway.  At least the dimmer seems to be reporting a reasonable value.

I still cannot make head nor tail from the values reported for _Instantaneous Demand_, _RMS Current_ and _RMS Power_.

**Comment by manup** [comment]
Cool hopefully some other routing related issues are also addressed, I'll forwarded it to the team to check.

>I still cannot make head nor tail from the values reported for _Instantaneous Demand_, _RMS Current_ and _RMS Power_.

Do you mean because of the data types?

**Comment by ebaauw** [comment]
> Do you mean because of the data types?

No, because of the values.  I'm no electrical engineer, but I would expect _RMS Voltage_ (V) x _RMS Current_ (A) to equal _Active Power_ (W) (modulo rounding/precision errors).  It doesn't.  _RMS Voltage_ is 234.  _RMS Current_ shows 53 when the dimmer and connected lights are off, and 26 when they're on at 100%.  _Active Power_ is 12 when off, and 5 when on.  I've got three 80W 230V halogen lights connected.

**Comment by manup** [comment]
Understand, hmm maybe these values need one of those Zigbee transformations similar to lightlevel/lux? Need to check the ZCL spec.

**Comment by ebaauw** [comment]
Ubisys support mentioned that the _Current Summation Delivered_ in the previous firmware version contained some internal sensor readings.  I think the other attributes might as well.

The ZCL spec (at least the version I have) is rather brief on this subject.  There’s multiplier and divisor attributes for each, but the D1 doesn’t support those.  There some more of these in the 0x0400 range missing from general.xml, but I don’t think it supports these either.

**Comment by strandman** [comment]
Hi, new here!
For Philips Hue Bridge users:
Happy to say that latest ubisys Firmware Version 1.14 (Q2 2019) fix that Philips Hue Bridge recognize the power switch S1 (-R) and S2 (-R) as an "On/Off plug". 
http://www.ubisys.de/en/support/firmware/

OTAU took me only about 6 minutes with ConBee II.

**Comment by strandman** [comment]
Hello again!
Ubisys has released new firmwares based on Zigbee Stack 2.0.13
http://www.ubisys.de/en/support/firmware/

But I'm unable to upgrade. The STD OTAU Plugin only stucks at "Queued" and nothing happens.
The change log for S2 states that: 
>  Migration is a one-way process and devices will have a different OTA image type after the upgrade. The new image type is 0x7b23

Could that cause problems? Just guessing? Is there someone else here that is able to upgrade to latest firmware?

Thanks!

**Comment by SwoopX** [comment]
The Change log from the J1:


- Migration to new factory block format (FB1)
- Migration to new Persistent Storage 2.0 format and increase of NVM space from 2KB to 20KB
- Migration to ubisys Compact Firmware Upgrade 2.0: CFWU 2.0 is an encrypted, signed and compressed OTA file format. This improves security, cuts update time per device in half with positive effects on battery life for battery powered devices and reduced network bandwidth utilization, and increases available space on the device for future upgrades and new features. We are making all ubisys devices ready for the next major Zigbee release with lots of new features – stay tuned
- Migration is a one-way process and devices will have a different OTA image type after the upgrade. The new image type is 0x7b24
- Added human readable version string
- Added product URL
- Added product code (EAN)

Not too sure if this is good or bad...

**Comment by SwoopX** [comment]
So, seems like it worked, but took litereally ages...

![grafik](https://user-images.githubusercontent.com/4005212/116514810-d298f880-a8cb-11eb-8134-be02d6f43dd1.png)

![grafik](https://user-images.githubusercontent.com/4005212/116514909-f1978a80-a8cb-11eb-9fe9-cfc496dda3ec.png)
