### ISSUE TITLE
ROBB smart 8-knoppen / ROb_200-007-0  not on supported productlist

### ISSUE THREAD

**Issue by sun-in-the-see** [dresden-elektronik/deconz-rest-plugin#7123]
Cluster info (followed the instructions at https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support
 - does not show anything. So i can only provide node info:

![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/140256261/f8048392-98c5-4115-af00-ae10b27737bb)

![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/140256261/ffeb89ed-8ff3-4ec9-ae7d-921450ea0360)

![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/140256261/f8c04215-2d8d-49d5-a051-9dd6e931df42)

the event get into H.A. but not recognized.
![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/140256261/f12b07bf-0bbd-4662-98a3-841ef1ac61ac)
when pressing keys the events are passed:
![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/140256261/bfa2619a-4d0f-42cf-bf4d-7b6c0fd5fdf4)
but battery is showing empty - while fully charged:
![afbeelding](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/140256261/a92a56bb-cea4-455c-ac61-7e4623fb46f5)

**Comment by Mimiix** [comment]
Missing all cluster screenshots. Make sure you have the correct panel open.
