### ISSUE TITLE
EasyAccess Locks

### ISSUE THREAD

**Issue by arevinje** [dresden-elektronik/deconz-rest-plugin#7125]
## Device

- Product name: EasyFingerTouch
- Manufacturer: EasyAccess AS
- Model identifier: easyCodeTouch_v1
- Device type : 
  - Lock

## Screenshots
![info panel](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2105982/45b99011-0865-4330-b77f-79be3454110d)
![clusters_3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2105982/4e187683-cd70-4e02-bf99-27d3477df62b)
![clusters_2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2105982/ed96036b-f165-4b96-ba9e-9588f66a4608)
![clusters_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2105982/c87f0cee-81c4-456a-bd14-0a7e0a0ae83e)
![endpoints](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2105982/d65bf350-c943-449e-9b4e-5321ca755783)

**Comment by Mimiix** [comment]
Hi

Please make sure the clusters are read and add a screenshot of the cluster list :)

**Comment by Smanar** [comment]
Yep, because I m seing this device in the native code.
So need to check why your device haven't native support.

**Comment by sliann** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/223a5ad4-f25d-4732-8277-368543a1cd92)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/39c90896-8313-4b0a-a74f-4a55acbffcde)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/27973388-ab56-4e8c-b9a1-c50eab2636da)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/3e7d988e-b7b0-4d4d-a160-56ab35a698da)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/72ca200a-6cc8-4342-9095-38396d0a8f7b)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/cd0f0be6-08d4-42cc-adb9-7f77617fa341)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/94217c21-73e6-4372-a33b-25f78c5edb85)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/859a1b97-ec50-439e-8637-4a120269035a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/f0d6079d-852b-4b4f-aa36-6405bb1488d4)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/2dbdb102-a15d-4c0a-a6b4-f4939e25207d)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/faf881b1-eb79-4df7-9bf2-db77d5a19e0b)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/b3145ff6-b890-48b9-a0bc-e1382beb5d40)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/07bae859-3e6a-4d21-b6f8-832809b22cbc)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/98724df9-0db7-41b7-8b9f-281c07c75579)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/4f546681-bca1-4b32-91c2-98b7a2ac69a0)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/56c4ab15-c96b-417b-aff6-1081ad07951a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/4ad9808c-1c47-451d-9ca3-0b389786b7c6)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/9b160fa5-6472-49fa-bcc9-3ad4b4560e07)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/4f8bedaa-a785-4a06-b06f-03248bc1903d)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/0e6cf876-99e7-4d00-92ec-2bdcbc8fd80d)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/cd30a298-033f-4afc-a73a-2867bb5548e5)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/ada27741-1365-4aa7-a000-08fdf18d7425)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/58ed0c3d-98f2-425b-8cd9-565665b47427)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/79062704/1837e0c4-fdeb-4ce0-9c65-3e9a08be9512)
