### ISSUE TITLE
chown warnings when updating deconz in Debian Bullseye/Bookworm

### ISSUE THREAD

**Issue by zenlord** [dresden-elektronik/deconz-rest-plugin#7127]
## Describe the bug
When updating to v2.22.02-debian-buster-stable, I see 3 warnings related to changing ownership:

    Setting up deconz (2.22.02-debian-buster-stable) ...
    chown: warning: '.' should be ':': ‘root.root’
    chown: warning: '.' should be ':': ‘root.root’
    chown: warning: '.' should be ':': ‘root.root’

This happens on a Debian Bookworm machine using the Debian Bullseye repo for deconz.

**Comment by manup** [comment]
Stumbled over this myself recently, it's already fixed and warning shouldn't be shown anymore with next version.

**Comment by Mimiix** [comment]
@manup We have templates for a reason.
