### ISSUE TITLE
ZGP Friends of Hue reported twice

### ISSUE THREAD

**Issue by dof250** [dresden-elektronik/deconz-rest-plugin#7130]
## Describe the bug

When pressing the buttons of a "Friends of Hue" (enocean, in my case a Senic Gira) multiple times, there are multiple responses send by deCONZ. So sometimes the switch reacts twice.

## Steps to reproduce the behavior

Press the switch multiple times, but sometimes only 1 press will do.

## Expected behavior

Trigger the press once.

## Environment

 - Host system: ESXi
 - Running method: Ubuntu VM
 - Firmware version: 0x26780700
 - deCONZ version: 2.22.2 (but the issue appears in all the last versions.)
 - Device: ConBee 2
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs
Below is the ZGP log when the issue appears. You can see the frameCounter 6830 was already there, but its triggered again half a second later by the GPP proxy with the same frameCounter 6830 number.

 (That GPP proxy 0x3D58 is a LWA004 Hue light, but it are different Hue lights that "repeat" the message)

10:26:09:528 ZGP srcId: 0x01729BE6 cmd: 0x13 frameCounter: 6829
10:26:09:529 ZGP button 3000 FOHSWITCH
10:26:09:648 ZGP srcId: 0x01729BE6 cmd: 0x17 frameCounter: 6830
10:26:09:649 ZGP button 3002 FOHSWITCH
10:26:10:066 ZGP srcId: 0x01729BE6 cmd: 0x13 frameCounter: 6831
10:26:10:067 ZGP button 3000 FOHSWITCH
10:26:10:183 ZGP via GPP proxy 0x3D58 for GPD srcId: 0x01729BE6 cmd: 0x17 frameCounter: 6830, GPD lqi: excellent, rssi: -74
10:26:10:183 ZGP button 3002 FOHSWITCH
10:26:10:230 ZGP srcId: 0x01729BE6 cmd: 0x17 frameCounter: 6832
10:26:10:231 ZGP button 3002 FOHSWITCH

**Comment by kopierschnitte** [comment]
This bug still exists for me. Almost every 2nd button press produces two events:

```
09:23:54:896 ZGP srcId: 0x01732B98 cmd: 0x12 frameCounter: 4962
09:23:54:896 ZGP button 4000 (null)
09:23:55:130 ZGP srcId: 0x01732B98 cmd: 0x16 frameCounter: 4963
09:23:55:130 ZGP button 4002 (null)
09:23:56:040 ZGP via GPP proxy 0x65EE for GPD srcId: 0x01732B98 cmd: 0x12 frameCounter: 4962, GPD lqi: moderate, rssi: -88
09:23:56:041 ZGP button 4000 (null)
09:23:56:150 ZGP via GPP proxy 0xFB09 for GPD srcId: 0x01732B98 cmd: 0x16 frameCounter: 4963, GPD lqi: excellent, rssi: -60
09:23:56:151 ZGP button 4002 (null)
```

I've noticed that in case it works as expected, the **ZGP via GPP** proxy entries are missing:

```
09:27:54:393 ZGP srcId: 0x01732B98 cmd: 0x13 frameCounter: 4964
09:27:54:394 ZGP button 3000 (null)
09:27:54:581 ZGP srcId: 0x01732B98 cmd: 0x17 frameCounter: 4965
09:27:54:582 ZGP button 3002 (null)
```
