### ISSUE TITLE
[sensor]: probably wrong battery readout: _TZ3000_ena8vgqb

### ISSUE THREAD

**Issue by labor4** [dresden-elektronik/deconz-rest-plugin#7138]
## Describe the bug
This may, or may not be the right repo to report this.

The Multisensor (Temp/Humidity) **shows an odd battery value of 0. Expected 100.**
Batteries are fresh, correct voltage according to vendor.

````
{
    "config": {
        "battery": 0,
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "etag": "a8761a1770e7f097b125e4ed1a925f2a",
    "lastannounced": null,
    "lastseen": "2023-08-02T15:55Z",
    "manufacturername": "_TZ3000_ena8vgqb",
    "modelid": "TS0201",
    "name": "SENSI 1",
    "state": {
        "lastupdated": "2023-08-02T15:31:10.669",
        "temperature": 2571
    },
    "swversion": "1.0.6",
    "type": "ZHATemperature",
    "uniqueid": "a4:c1:38:79:5e:04:aa:1d-01-0402"
}
````
## Steps to reproduce the behavior
- Pair using "other"

## Expected behavior
Battery expected to be 0-100 where 100 is full.
Should be 100.

## Screenshots
![Bildschirm­foto 2023-08-02 um 18 14 32](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18475375/26075616-e67a-40c9-b633-88cda5e5d20b)

## Environment
- v 2.22.02 / 19.9.2022
- firmware 26690700
- raspi, bare metal
- RaspBee II
- no USB devices attached

**Comment by Mimiix** [comment]
@Smanar can you check?

**Comment by Smanar** [comment]
The problem is I don't found information about this device, it seem it's not supported yet on other zigbee application and I don't found an issue on deconz about it.

Can you check using the GUI wich one cluster this device have ?
If it have cluster 0x0001, can you check attribute 0x0020 and 0x0021 ?

**Comment by labor4** [comment]
I'm guessing you don't mean the phoscon web GUI, but an external debugging tool?
Can you advise me on which tool/GUI is suited to get this info?

**Comment by labor4** [comment]
i'm a bit closer I think.
i managed to manually start deCONZ with an X window.
Is this what you are asking for?
couldn't find a "cluster" number.
<img width="1038" alt="Bildschirmfoto 2023-08-06 um 21 27 53" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18475375/e44d88a0-c1fe-4162-ad7b-3c7962fcd366">

**Comment by Smanar** [comment]
Cluster are Blue number, so clic on 0x0001 Power configuration, you will have on bottom the attribute list.
And on the attribute 0x0020 and 0x0021 the attributes we checkingfor battery.

Problem this device is a slepper, so you will need to wake it up in same time you press the "read" button (with short press on reset button generally)
Can ask only the 0x0020 and 0x0021 by selecting them.

**Comment by BabaIsYou** [comment]
Could it be related to the fact that into the DDF the max interval for binding is 86400 and that when using DDF editor it's limited to 65535 ?

**Comment by Smanar** [comment]
Haaaaa right, good question !
@labor4 on the DFF can you replace 

```
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 84600,
          "change": "0x00000002"
        }
      ]
    },
```

by
```

      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000002"
        }
      ]
    },
```

**Comment by labor4** [comment]
**One of the two** suddenly showed battery 100% in phoscon web GUI.
Even before editing the `_TZ3000_TS0201_temp_hum_sensor.json`:

>           "max": 43200,


I did a `systemctl status deconz` after that. Sufficient?

No change.

Need to investigate further, did not yet test the this part:
> Problem this device is a slepper, so you will need to wake it up in same time you press the "read" button (with short press on reset button generally)
Can ask only the 0x0020 and 0x0021 by selecting them.

thanks
m

**Comment by BabaIsYou** [comment]
DDF has been updated 2 weeks ago to add another device support #7159. But that’s the only change about this, no other fields into DDF. What are the values from GUI ?
