### ISSUE TITLE
IKEA RODRET Kabelloser Dimmer/Schalter

### ISSUE THREAD

**Issue by TheGreatNemo** [dresden-elektronik/deconz-rest-plugin#7147]
## Device
- Product name: RODRET Kabelloser Dimmer/Schalter - E2201
- Manufacturer: IKEA of SWEDEN
- Model identifier: RODRET Dimmer
- Device type :
  - Switch

### Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/42db0208-9478-48d9-90ea-c281a9048af5)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/abf79d4c-a026-4003-ba3c-fd3728d5e46e)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/677f8beb-4dd3-45d3-b15e-7d334b923586)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/a96f765c-2c64-4c44-bb80-ff21095c9f31)

### Identify
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/69ab2ea0-f8f4-45a9-9a8f-0e47bd8f6d12)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/5654d3e8-731f-46fd-967f-49df880dc593)

### Poll Control
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/b5a40bbf-30af-41a9-a7d1-2a93e02a4007)

### IKEA specific
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/026702cf-4005-4b59-b842-0a85c58f57dc)

## Node Panel
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62012121/c0e72720-ddb5-4842-a58e-51326e4cc7a6)

**Comment by DIYtechie** [comment]
I also have this request. Will not seem to pair.

**Comment by Mimiix** [comment]
Guys, it's not supported yet. That's why it's not showing up in phoscon. As long as it has the hex names it wont work. If you can't get it in deconz, it's a different issue and perhaps you need to ask for help on the forums with that.

**Comment by BabaIsYou** [comment]
As suggested by ebaauw in Discord, will begin by reusing DDF for Styrbar (adapted of course)

```
 {
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_IKEA",
  "modelid": "RODRET Dimmer",
  "product": "RODRET Dimmer - E2201",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x1000"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0820",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x1000"
        ],
        "out": [
          "0x0006",
          "0x0008",
          "0x0005"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {
            "fn": "zcl",
            "ep": 1,
            "cl": "0x0001",
            "at": "0x0021",
            "eval": "Item.val = Math.round(Attr.val / 2)"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0008"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0005"
    }
  ]
}
```

and adding these lines into `button_maps.json`
```
        "ikeaRodretMap": {
            "vendor": "IKEA",
            "doc": "Rodret dimmer remote",
            "modelids": ["RODRET Dimmer"],
            "buttons": [
                {"S_BUTTON_1": "Dim Up"},
                {"S_BUTTON_2": "Dim Down"},
            ],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],
                [1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_HOLD", "Move up (with on/off)"],
                [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "Stop_ (with on/off)"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],
                [1, "0x01", "LEVEL_CONTROL", "MOVE", "1", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "Move down"],
                [1, "0x01", "LEVEL_CONTROL", "STOP", "1", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Stop"],
                [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "1", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Stop_ (with on/off)"]
            ]
        },
```

**Comment by BabaIsYou** [comment]
> Looks good, except for the non-existent _Scenes_ client cluster (0x0005) in the fingerprint and in the bindings. On the STYRBAR, that cluster is used by the left/right buttons.

Thx ! Corrected in the above proposed DDF.

**Comment by TheGreatNemo** [comment]
> As suggested by ebaauw in Discord, will begin by reusing DDF for Styrbar (adapted of course)
> [...]
> and adding these lines into `button_maps.json`
> 
> ```
>         "ikeaRodretMap": {
>             "vendor": "IKEA",
>             "doc": "Rodret dimmer remote",
>             "modelids": ["RODRET Dimmer"],
>             "buttons": [
>                 {"S_BUTTON_1": "Dim Up"},
>                 {"S_BUTTON_2": "Dim Down"},
>             ],
>             "map": [
>                 [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],
>                 [1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_HOLD", "Move up (with on/off)"],
>                 [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "Stop_ (with on/off)"],
>                 [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],
>                 [1, "0x01", "LEVEL_CONTROL", "MOVE", "1", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "Move down"],
>                 [1, "0x01", "LEVEL_CONTROL", "STOP", "1", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Stop"],
>                 [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "1", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Stop_ (with on/off)"]
>             ]
>         },
> ```

Thanks a lot.
This seams to work 👍 I can add the switch, they show up in Phoscon App and look like they work pretty much as intendet 👍 

I only changed one small thing:
The line "{"S_BUTTON_2": "Dim Down"}," shoudn't have comma at the end.

**Comment by BabaIsYou** [comment]
Sorry about that typo ;-/
Do you want to make the pull request to have this included in a next release ?

**Comment by TheGreatNemo** [comment]
> Do you want to make the pull request to have this included in a next release ?

Done. 
Thanks again 👍

**Comment by x2005254** [comment]
Dear All,

I include the DDF and the button Map config in my deconz conf, as other I'm able to discover it with Phoscon now, But I cannot use it as group Binding to affect to a light without phoscon. the inclusion didn't create the proper group.

Second issue, it shown as empty battery : 
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63404676/b4be6664-139a-4538-bbd8-5bc8a1afe4b4)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63404676/a1b75d70-16bf-4569-8c39-9dcc91e9de7e)
by deconz.

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63404676/b6e170bd-7a1d-46e3-b79c-517a64bb311e)

**Comment by ebaauw** [comment]
Needed to visit IKEA to get new filters for my STARKVIND, so picked up a RODRET along the way.

The device does send groupcasts by default.  Group ID is picked randomly (on device reset) and reported through _ZLL Commissioning_.  I'll do a PR with updated DDF.

**Comment by BurningTheSky** [comment]
> > As suggested by ebaauw in Discord, will begin by reusing DDF for Styrbar (adapted of course)
> > [...]
> > and adding these lines into `button_maps.json`
> > ```
> >         "ikeaRodretMap": {
> >             "vendor": "IKEA",
> >             "doc": "Rodret dimmer remote",
> >             "modelids": ["RODRET Dimmer"],
> >             "buttons": [
> >                 {"S_BUTTON_1": "Dim Up"},
> >                 {"S_BUTTON_2": "Dim Down"},
> >             ],
> >             "map": [
> >                 [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],
> >                 [1, "0x01", "LEVEL_CONTROL", "MOVE_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_HOLD", "Move up (with on/off)"],
> >                 [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "Stop_ (with on/off)"],
> >                 [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "On"],
> >                 [1, "0x01", "LEVEL_CONTROL", "MOVE", "1", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "Move down"],
> >                 [1, "0x01", "LEVEL_CONTROL", "STOP", "1", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Stop"],
> >                 [1, "0x01", "LEVEL_CONTROL", "STOP_WITH_ON_OFF", "1", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Stop_ (with on/off)"]
> >             ]
> >         },
> > ```
> 
> Thanks a lot. This seams to work 👍 I can add the switch, they show up in Phoscon App and look like they work pretty much as intendet 👍
> 
> I only changed one small thing: The line "{"S_BUTTON_2": "Dim Down"}," shoudn't have comma at the end.

Mind if I ask how did you added the switch? Can it be done via Phoscon or does it have to go another way? I'm new to deCONZ so excuse my simple question!
