### ISSUE TITLE
Lonsonho (Tuya) 4 gang: ZBWS04A / _TZ3000_uaa99arv / TS0044

### ISSUE THREAD

**Issue by rafalw1277** [dresden-elektronik/deconz-rest-plugin#7157]
## Device

- Product name: Lonsonho (Tuya) 4 gang ZBWS04A
- Manufacturer: _TZ3000_uaa99arv
- Model identifier: TS0044
- Device type : Switch

## Screenshots
![Screen Shot 08-07-23 at 10 26 AM](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/59505711/de3f7c49-c5a7-41ae-91a6-24c89f0837c6)
## Basic
![Screen Shot 08-07-23 at 10 32 AM](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/59505711/0de3f4c9-f9b6-4e57-b4b7-7f4581131e71)
## On/Off
![Screen Shot 08-07-23 at 10 42 AM](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/59505711/9058bd76-02bd-48d7-85af-863e6f1a401c)

Purchased here:
[https://pl.aliexpress.com/item/4001095272467.html?spm=a2g0o.order_list.order_list_main.11.361f1c24SBNIVD&gatewayAdapt=glo2pol](url)

**Comment by BabaIsYou** [comment]
Seems that support is already in progress ;-) : https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7150
