### ISSUE TITLE
ROVF (TMZ02L-16A-B2) Mini Switch Module 16A No Neutral: _TZ3000_hkkkuk7k TS0012

### ISSUE THREAD

**Issue by str31ok** [dresden-elektronik/deconz-rest-plugin#7194]
## Device

- Product name: ROVF (TMZ02L-16A-B2)
- Manufacturer: _TZ3000_hkkkuk7k
- Model identifier: TS0012
- Device type :  
  - Switch

## Screenshots

![1 2 Node info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/f0cc86b0-9163-4ae8-8268-312f5fc92e92)
### Basic
![1 1 Basic cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/c8ab2966-a2cd-479e-90f1-d36d98a8634f)
### Identify
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/a77405b0-e28a-4701-bf85-468d7c745fed)
### Groups
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/f130959b-0cb4-45d9-b60d-a5e742dbd418)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/a499a100-81d7-4789-b4e0-75815468f4f4)
### Scenes
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/e71abc5f-6e7d-4847-a090-05613893b741)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/114de3fd-4d5e-4d55-ad4f-63f2dabe44bf)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/4265cbc9-a94f-4fec-b3e9-888a50c0596a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/4742835f-334e-4d42-b310-98dabc75fa60)
### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/e4ed128a-61fc-4175-9705-4ecac990f21e)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/b7b5fcfe-e404-42e3-935c-dde4eb8a8dc9)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/65dd518e-4bac-423e-98c1-6c0b9b44e690)
### Unknown
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/5cb49fcd-d052-4fab-b9c9-d2d729c3bd8e)
### Tuya specific
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/f1893695-bf2f-4acd-a0f7-3c7c7acf46a1)
### OTAU
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/9af929d8-1a15-41f5-bd9f-e8ea61669cea)
### Time
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/b8eb1f46-9fb2-4f57-8fde-e03be466dfd7)
### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/9d8a3148-f75b-4f5b-a5e3-3ffb23426255)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76436265/60d3131b-575a-4771-9a5f-7291a064d37a)

**Comment by str31ok** [comment]
It seems to me that it works.  At least the relay appeared in phoscon and i could add it in openhab. Thank you very much for your help

**Comment by BabaIsYou** [comment]
My pleasure 😇
