### ISSUE TITLE
Tuya Smart Button IH-663

### ISSUE THREAD

**Issue by HypeLaser** [dresden-elektronik/deconz-rest-plugin#7205]
- Product name: Tuya Smart Button
- Manufacturer: _TZ3000_fa9mlvja
- Model identifier: TS0041
- Device type : 
  - Switch

![Screenshot 2023-08-30 at 21 10 57](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/20632680-ce8f-4270-aa7a-d4051b459fcf)

![Screenshot 2023-08-30 at 21 10 49](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/e71ee76e-8708-42ab-a617-91550b2a5feb)

Screenshots

![Screenshot 2023-08-30 at 20 48 11](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/41d264f1-971d-4f58-9a73-692de1522882)

Node Info

![Screenshot 2023-08-30 at 20 49 06](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/9dba436d-554e-47b5-9e09-362d593da0e0)

Basic Cluster

![Screenshot 2023-08-30 at 21 14 39](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/82bf7a44-33f6-492a-8b47-b6390d25714f)

Power Config Attributes

![Screenshot 2023-08-30 at 20 57 49](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/e037db54-0a7a-49d2-bf18-8b7a89f28be3)

On/Off attributes (there are two On/Off listed. This is the Blue text one)

![Screenshot 2023-08-30 at 21 03 05](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/a16a8f84-b7b8-4242-b827-54b447c76966)

On/Off attributes (there are two On/Off listed. This is the Grey text one)

![Screenshot 2023-08-30 at 21 05 49](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/110939572/8a17eb34-0f33-47a4-b680-f407c225a956)

These Tuya Smart Buttons have three states: Single Press, Double Press, Long Press.

Obviously I can see them in DeCONZ, but it does not appear in Phoscon as anything. I've tried all devices.

I am trying to get this device to work in Home Assistant to trigger LED light states from the different button push states.

**Comment by 1100101** [comment]
Reopen please, I have this device as well and would like it to work with Phoscon.

**Comment by 1100101** [comment]
I took the DDF `_TZ3000_TS0041_1gang_bat.json`and modified it, by just adding `_TZ3000_fa9mlvja` to `manufacturername` and `TS0041` to `modelid`.

I can now pair the switch in Phoscon, it is recognized.

BUT: I do not get any button events via the API.  
Instead, it seems the device sends its battery status every second.

I haven't tried anything else, I don't know DDF at all :)

**Comment by Mimiix** [comment]
> I took the DDF `_TZ3000_TS0041_1gang_bat.json`and modified it, by just adding `_TZ3000_fa9mlvja` to `manufacturername` and `TS0041` to `modelid`.
> 
> I can now pair the switch in Phoscon, it is recognized.
> 
> BUT: I do not get any button events via the API. Instead, it seems the device sends its battery status every second.
> 
> I haven't tried anything else, I don't know DDF at all :)

If yours is not the same manufacturer name, you have to open a new device request.

**Comment by 1100101** [comment]
@Mimiix I have exactly this device mentioned by the original poster.

modifying the existing DDF apparently did not work, but could you still reopen the issue please?

**Comment by Mimiix** [comment]
> @Mimiix I have exactly this device mentioned by the original poster.
> 
> modifying the existing DDF apparently did not work, but could you still reopen the issue please?

Can you show me the basic cluster ?

**Comment by 1100101** [comment]
Sure:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1006337/57f6551b-57d7-4133-a473-35ed5768638d)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1006337/38438278-f28f-4f8a-8bbc-6fbed58ff8c3)

**Comment by Mimiix** [comment]
Thanks

@Smanar

**Comment by 1100101** [comment]
@Smanar I went ahead and did the change to `_TZ3000_TS0041_1gang_bat.json` again, as I did previously (see above).
This time I also modified the `button_maps.json` to include this device.

The switch can now be paired with Phoscon, and I see events coming trough deCONZ REST API, including button clicks (single press, double press, long press).

Still, strangely, once I hit the button, I get loads of events from the device, updating its values constantly for about 30 seconds, even though the values never change.

Is this expected behavior?

**Comment by 1100101** [comment]
I've added the `refresh.interval` from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7006/files#diff-5f7ad09495b8fb0da9809c7bc3f561c7e46102a8c3ef8142568f8ddea4554d81L50 
back into the DDF, and now it looks like I don't get bombarded with battery status events :)

**Comment by Smanar** [comment]
Oups sorry, have totally skipped this post

>Still, strangely, once I hit the button, I get loads of events from the device, updating its values constantly for about 30 seconds, even though the values never change.

>Is this expected behavior?


He, for me not, the device can wait for a "confirmation" from deconz.

The report from battery is set here
```
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
```

If this one is not working, and after the time set in refresh.interval (it's for that need to put greater value in it than in bind) deconz make a poll to get the value.
So this setting can't stop the spamming for me, perhaps the bind was not set before (deconz need to configure the device and can take time if you don't re-include the device, they are lazy device)

**Comment by atomphil** [comment]
I have a switch that appears to be identical to the one shown here, except that it reports "_TZ3000_mrpevh8p" as the manufacturer name. It is found in deconz, but not in Phoscon. How can I integrate it and use it in Home Assistant?
The "manual" names the model as RSH-SC07.

**Comment by Smanar** [comment]
You can do like him https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7205#issuecomment-1815918434

**Comment by Smanar** [comment]
You have edited too the Buttonmap file ?
Not possible if you are on docker (or harder)

**Comment by 1100101** [comment]
@manup @Smanar could we open this again?
The issue I described in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7205#issuecomment-1815918434 still persists:

Once I hit the button, the battery value is sent multiple times per second, for 20-30 seconds (I suppose the button goes to sleep after that time).

**Comment by Mimiix** [comment]
> @manup @Smanar could we open this again? The issue I described in [#7205 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7205#issuecomment-1815918434) still persists:
> 
> Once I hit the button, the battery value is sent multiple times per second, for 20-30 seconds (I suppose the button goes to sleep after that time).

Did you update to 2.25.0?

**Comment by Smanar** [comment]
Im looking on Z2M they are doing nothing special except adding the tuya magic packet.
Can try to add to the DDF
```
	{
	 "name": "config/tuya_unlock"
	},
```

New device don't support bind, so can try to remove
```
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    }
```

But this part can make the device not working.

You haven't some logs when you press the button ? To see if the problem is from the device or deconz, can be something normal, tuya is exotic stuff.

**Comment by 1100101** [comment]
@Mimiix Yes, I'm running v2.25.0-beta.
@Smanar I've removed the button from Phoscon/deCONZ, and re-learned it, but the issue remains.
I can produce some logs. Which log levels are you interested in?

**Comment by Smanar** [comment]
You have added 
```
	{
	 "name": "config/tuya_unlock"
	},
```

In your DDF ?

Can start with flags "info" and "info_l2" to start if its too much talkative, else an usefull one is "ZCL"

**Comment by 1100101** [comment]
@Smanar That did it!
Once I added the `tuya_unlock` bit, the event spam stopped.
Now I get only one update per attribute when the button is pressed.

Thanks!

**Comment by Hoeflers** [comment]
Hi,
I have exactly the same problem, but unfortunately I cannot see the Smart Buttons in Phoscon even after adjusting the json. files.

They are recognized in Deconz.
The button presses are also listed in the log of the Deconz addin in HA.
Is there anything else I need to consider?

Thanks

**Comment by Smanar** [comment]
@1100101 I have make a PR to update your device, if you can test it, but it just remove it from the original DDF to put it in another DDF with the tuya unlock request.

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7509

@Hoeflers if you can see event in HA, for me it mean phoscon just don't support it.

**Comment by Hoeflers** [comment]
Ich sehe nur im Log des add ins einen Eintrag wenn der Button betätigt wird. In ha selbst bekomme ich weder die Geräte noch Events angezeigt. 

Bei den anderen werden die Geräte nach den Änderungen ja angezeigt. 

Mache ic bda was falsch?

**Comment by Smanar** [comment]
Can you share some logs ?
IDK what kind of logs it can be, but without a good DDF you would have nothing, and with a working DDF I don't see what can be missing.

**Comment by Hoeflers** [comment]
Good morning,

happy to upload some logs later when I get back.
Can i get some logs from deconz inside which can help?
Must confess that deconz is something new for me. 

So far I have several plugs, lights and a button from Silvercrest working.
The buttons to be installed now are the same as in the first post except for the manufacture name.
_TZ3000_qgwcxxws

Apart from the described changes in _TZ3000_TS0041_1gang_bat.json and button_maps.json nothing has been changed.
The changes were entered via ssh docker.
Is this the right way?
Is there a possibility directly in Deconz?
Have I overlooked something?

Perhaps also important.
HA runs as VM in Proxmox with a Conbee II.

Thanks a lot

**Comment by Smanar** [comment]
>Can i get some logs from deconz inside which can help?

IDK, I just want to see the one you have, for the moment I realy don't understand what happen

>I only see an entry in the add ins log when the button is pressed

>The changes were entered via ssh docker.
Is this the right way?

You are using the official docker ? If yes DDF need to be in the `/opt/deCONZ/devices/` folder https://github.com/deconz-community/deconz-docker/issues/163

But all is native, you don't need to play with DDF, you can have a battery drain without the last version, but it will work natively.
Else you don't have a recent deconz version or you have a new model. If you have the GUI can take a look on the device to be sure you have the same model.

**Comment by Hoeflers** [comment]
I open Docker via the terminal addon Advanced SSH & Web Terminal
in HA there I followed this guide in the Phoscon forum.

Login via SSH to HA
Login deCONZ docker container: docker exec -it addon_core_deconz bash
Install a text editor e. g. nano for editing files on the CLI: apt update; apt install nano (note: this will be undone once the container is restarted or updated)
Edit your DDF file with e. g. nano /usr/share/deCONZ/devices/blitzwolf/bw_shp13_smart_plug.json
Don’t forget to “hot reload” the DDF changes using deCONZ (VNC GUI)
 
```
Login via SSH to HA
Login deCONZ docker container: docker exec -it addon_core_deconz bash
Install a text editor e. g. nano for editing files on the CLI: 
apt update; apt install nano (note: this will be undone once the container is restarted or updated)
Edit your DDF file with e. g. nano /usr/share/deCONZ/devices/blitzwolf/bw_shp13_smart_plug.json
Don’t forget to “hot reload” the DDF changes using deCONZ (VNC GUI)
``` 
I have the file _TZ3000_TS0041_1gang_bat.json from the path /usr/share/... to the /data/... folder as described and executed the hot reload.
Now the buttons are displayed in the Phoscon and I can also see when they are pressed.
One step further.

Unfortunately I cannot assign the buttons in the settings yet.
Only the Silvercrest is visible here.
I don't know where the product "Schalter" comes from.


![deconz_SW](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117538696/51d7ac23-853d-4762-a84b-b03329f7a4fe)
![verbundene_Schalter](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117538696/eb03fcd6-a75e-4d3c-8f51-5c542a3438ba)
![SW-verbinden](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117538696/4d79d4c3-7372-44db-a0b8-34be6cf43eb3)

**Comment by Smanar** [comment]
On HA you have a persistent folder here `/data/.local/share/dresden-elektronik/deCONZ/devices/`

And on HA you can edit DDF but harder to edit the buttonmap file, and you need it for button return.

For the schalter, better to look direclty in the API, phoscon/help/API Information/sensors. Phoscon is a third app like HA, they can add "stuff"

**Comment by Hoeflers** [comment]
Yes, I have copied the file to this folder. I just couldn't remember the exact path.

>On HA you have a persistent folder here 
 /data/.local/share/dresden-elektronik/deCONZ/devices/

Then I'll check the button map and see if I can do anything there.

Thanks for the support and have a nice weekend.

**Comment by Smanar** [comment]
>Then I'll check the button map and see if I can do anything there

Was just a remark, if you can see button event on phoscon, it mean the buttonmap file is fine, but on my side I don't see something native for the qgwcxxws.

**Comment by Hoeflers** [comment]
I can see the buttons, but unfortunately only an empty cover.
You can't add the buttons to a group.
Unfortunately, I have no idea how and where to edit this.
Unfortunately, I don't have a clear overview.
Any idea where I can start?

**Comment by Smanar** [comment]
>You can't add the buttons to a group.

This device don't have the group cluster, so I don't think it can support it.
You haven't third app ? other than phoscon ?

**Comment by Hoeflers** [comment]
No, unfortunately not. I think I'll buy supported buttons to get me started. 
Thanks for the great support.

**Comment by Smanar** [comment]
Ikea and philips are working for sure, but tuya it's more random.
