### ISSUE TITLE
What is FSM_STATE and VPIR ?

### ISSUE THREAD

**Issue by goermezer** [dresden-elektronik/deconz-rest-plugin#721]
I had some trouble with an Aqara motion detector. When I query the web service for my sensors via http://IP-Address/api/EC7C2010CB/sensors, I get two strange sensors additionally to the one, which I configured before.

ModelID: PHOSCON_FSM_STATE including a string "FSM_STATE" in the name (which was not given by me)

and another one: 

ModelID: PHOSCON_VPIR including an additional "VPIR" in the name like before. 

What does that mean? I removed the sensor in Phoscon. But these two still remain and I can not delete them?!

**Comment by goermezer** [comment]
Ah, I remembered that I created a sensor control rule and added two motion sensors to it. By the way I named one of it similar to the trouble maker sensor. Is it possible, that the above two strange named sensors (including FSM_STATE and VPIR)  are those two sensors, which are bound to the rule?

**Comment by manup** [comment]
Yes these two virtual sensors belong to the sensor control created for a group. To delete them, the related sensor control should be deleted under Group > Settings > Sensor control.
