### ISSUE TITLE
Bitron AV2010/34 aka. Climax WSS-4E-ZBS Wall Switch

### ISSUE THREAD

**Issue by rwsaxony** [dresden-elektronik/deconz-rest-plugin#722]
Hello everybody,

I have purchased from the Telekom 2 Bitron AV2010 / 34 wall switches, which are in reality Climax WSS-4E-ZBS wall switches.

The device is recognized by the deCONZ and is integrated in the network.
The switch is not recognized by the phoscon.

I am still quite new in deCONZ / Phoscon and have no idea what is needed to get the switch up and running.

Attached the basic things from deCONZ

Best regards,

Rene

Link to detailed product information:
https://www.zigbee.org/zigbee-products-2/#zigbeecertifiedproducts/productdetails3/58565312b09488924641fad3?ref=view_30_search%3DWSS-4E-ZBS%26view_30_page%3D1

![screenshot_1](https://user-images.githubusercontent.com/42265250/43946933-f1fb0744-9c86-11e8-9b67-24235bc0e310.png)
![screenshot_2](https://user-images.githubusercontent.com/42265250/43946939-f6e30e14-9c86-11e8-98de-4bb915d798c4.png)
![screenshot_3](https://user-images.githubusercontent.com/42265250/43946947-f9697876-9c86-11e8-9bfa-8af0f8c8b093.png)

**Comment by manup** [comment]
Just a wild guess but it looks like the switch might be able to send group commands in order to recall scenes.
I have one of these in the office, but never testet it, will check next week. Usually the Climax devices are quite easy to integrate.

**Comment by rwsaxony** [comment]
Thanks for the support!

**Comment by rwsaxony** [comment]
Hello together,

are there any newsworthy findings on the problem?

Kindest regards!

**Comment by rwsaxony** [comment]
Hello together,

are there any newsworthy findings on the problem?

Kindest regards!

**Comment by manup** [comment]
Sorry no updates yet but it is on the near todo list

**Comment by rwsaxony** [comment]
Hello again!

just wanted to ask quickly if there are any news regarding this issue?

Kindest regards!
