### ISSUE TITLE
Some devices looses connection after some time

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/deconz-rest-plugin#7224]
## Describe the bug
I have several device which will disconnect from the network and won't be reachable. Nevertheless the switching devices like relays or dimmer can be still controlled over the group... In the DECONZ gui they have no connection link. A Power off/on cykle doesn't help. 

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Raspbian
 - Firmware version: 26780700
 - deCONZ version: 2.22.01
 - Device: ConBee II
 - Do you use an USB extension cable: yes 0.5m long, because of USB3,0 disturbance
 - Is there any other USB or serial devices connected to the host system? No

## Additional context

Most sensors are Xiaomi, Aqara
Switches Aqara, Pulse,...
Actors div. GEDLOPTO, Müllerlicht, IKEA, OSRAM, LEDVANCE, ...

**Comment by Mimiix** [comment]
Hi,

Can you share some logs?

I'd like to get INFO, INFO L2, APS, APS L2, ERROR, ERROR L2.

I am tempted to close this issue as its not compliant with #5113, but i'll decide after the logs.

**Comment by MSchmitt67** [comment]
Hallo,
some months ago i had the same problem. I tried everything but the problem was overlapping wifi and zigbee channels. I changed my wifichannel and the problem was solfed.
![wlan_zigbee_kanal_überschneidung](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/92262454/82169cfc-5d58-4fdd-8696-4eb9849eafc0)

**Comment by Maddinthebrain** [comment]
Hi,
interesting, I will try that. I hope it won't cause chaos with the WLAN Devices. ;-)

@MiniiX
