### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by Idaho947** [dresden-elektronik/deconz-rest-plugin#7231]
## Device

- Product name: Nous door\windows sensor E3
- Manufacturer: _TZ3000_v7chgqso
- Model identifier: TS0203
- Device type : Please remove all unrelated device types. 
  - Sensor

## Screenshots
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/c2002963-9ccb-49f3-97f9-ccf9b15dd028)

### Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/a2d40582-1a8b-46a0-a5b5-3de08edb44d4)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/7dd2d774-62a1-4ac3-8d25-f32d5e832616)

### Identify
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/fa5e5654-aed3-488e-b227-1dc64509ec34)

### Groups
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/17be90d3-6e66-4271-9328-dac15f20f079)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/10b9a148-e13b-4656-8755-51f8ccb9f994)

### Scenes
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/8ad0d54b-128f-423e-8669-ef2f7a112cf0)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/1f110717-b3af-4ba8-8122-37c261ea9d90)

### Power
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/132d6656-a06a-46a8-9efc-cc57273ca200)

### IAS zone
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/dc84b7df-e46f-493d-b4e7-afd81762472f)

**Comment by Smanar** [comment]
Hello, I don't find information for this sensor, but probably a new clone
I have just edited the devices\tuya\_TZ3000_TS0203_door_sensor.json

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_n2egfsli", "_TZ3000_oxslv1c9", "_TZ3000_7tbsruql", "_TZ3000_7d8yme6f", "_TZ3000_rgchmad8", "_TZ3000_bzxlofth","_TZ3000_au1rjicn", "_TZ3000_4ugnzsli", "_TZ3000_decxrtwa", "_TZ3000_2mbfxlzr", "_TZ3000_6zvw8ham", "_TZ3000_v7chgqso"],
  "modelid": ["TS0203", "TS0203", "TS0203", "TS0203", "TS0203", "TS0203","TS0203","TS0203","TS0203", "TS0203", "TS0203", "TS0203"],
  "vendor": "Tuya",
  "product": "Smart Zigbee Door Window Contact",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
           "name":"state/tampered"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled",
          "public": false
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          }
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/open"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by Idaho947** [comment]
Perfect as usual.

**Comment by Smanar** [comment]
@Idaho947 so all is working ? I can make the PR ?

**Comment by Idaho947** [comment]
Yes youncan

**Comment by Smanar** [comment]
Thx, PR done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7260
