### ISSUE TITLE
password does not work after updating to 2.23.01

### ISSUE THREAD

**Issue by mani76** [dresden-elektronik/deconz-rest-plugin#7250]
## Describe the bug
After updating to 2.23.01 old login password does not work anymore.
Tried also to reset password but nothing happens when password is change button is pressed.

## Steps to reproduce the behavior
Update docker image version and try to login

## Expected behavior
Login using current password

## Environment
Latest 2.23.01 using deconzcommunity/deconz

**Comment by Mimiix** [comment]
Hi

As this is not a bug report as described by #5113 I am closing this issue.

Feel free to open a post on the forums.

Kind regards,
Dennis
