### ISSUE TITLE
nous lz1

### ISSUE THREAD

**Issue by madmax5900** [dresden-elektronik/deconz-rest-plugin#7261]
- Product name: nous lz1
- Manufacturer: _TZ3000 _3vf5bnrm
- Model identifier: TS0011
- Device type : Please remove all unrelated device types. 
  - Light
<img width="631" alt="Bildschirmfoto 2023-09-25 um 13 47 05" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/2ddd3691-2852-48f6-b00f-48d4607c993b">
<img width="657" alt="Bildschirmfoto 2023-09-25 um 14 49 08" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/bc3d83d7-cbd4-44d6-a2b4-4d6559ee1778">
<img width="666" alt="Bildschirmfoto 2023-09-25 um 14 49 38" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/8802feef-9e27-4f21-8670-fe2bd3a997c4">
<img width="910" alt="Bildschirmfoto 2023-09-25 um 14 52 21" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/e3a1cdcd-b75b-49d0-a2f2-765ad13f7271">

On/Off

**Comment by Mimiix** [comment]
Missing screenshots. Please add screens of all clusters.

**Comment by madmax5900** [comment]
OK, is that okay?
<img width="998" alt="Bildschirmfoto 2023-09-25 um 15 45 52" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/4ad17cdf-7ae1-4749-b7af-7d2135071515">
<img width="1012" alt="Bildschirmfoto 2023-09-25 um 15 46 01" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/8ab2597e-442e-41d3-834b-c8f942324ef1">
<img width="1009" alt="Bildschirmfoto 2023-09-25 um 15 46 12" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/cbe2c607-6b22-4100-9457-fb4cf81ab1a9">

<img width="1028" alt="Bildschirmfoto 2023-09-25 um 15 46 24" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/fe453098-5ed7-4fb3-b7c1-a825edba5c03">
t
<img width="1011" alt="Bildschirmfoto 2023-09-25 um 15 46 34" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/53ea4013-e247-4d94-bc1f-269788921e59">
<img width="1007" alt="Bildschirmfoto 2023-09-25 um 15 46 45" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/5d10cb09-8e9c-4be0-a764-09cbd80316e5">
<img width="1045" alt="Bildschirmfoto 2023-09-25 um 15 47 12" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/d6889b6b-a0c1-43d2-b532-49dbb3c0579d">
<img width="1040" alt="Bildschirmfoto 2023-09-25 um 15 47 19" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/f210ec3f-ff4a-4d62-8f31-c67e683ee0d2">
<img width="1013" alt="Bildschirmfoto 2023-09-25 um 15 47 25" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/d862d449-5261-4e57-b292-61f5c629ca39">
<img width="957" alt="Bildschirmfoto 2023-09-25 um 15 45 17" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/e1ce4cdc-7e3c-4951-8d4e-7f322155d205">
<img width="959" alt="Bildschirmfoto 2023-09-25 um 15 45 26" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/d6986664-6273-4e8c-98cf-782079777ca3">

**Comment by Mimiix** [comment]
Looks good, thanks :)

**Comment by Smanar** [comment]
Power source > battery !
It's a tuya joke ? It's a wired device ?

Can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_txpirhfq","_TZ3000_qmi1cfuq", "_TZ3000_ji4araar","_TZ3000_v7sopte0","_TYZB01_qeqvmvti", "_TZ3000_3vf5bnrm"],
  "modelid": ["TS0011", "TS0011", "TS0011","TS0011","TS0011", "TS0011"],
  "product": "1 gang switch module",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by madmax5900** [comment]
Hello!

Thanks for that.

The device is wired.

What do I do with it?

**Comment by Smanar** [comment]
What is your OS ?
It's simple you just need to edit a text file, the devices\tuya\_TZ3000_TS0011_1gang_switch_module.json.
If you are a real OS can take less than 10mn, if you have docker, ... more ...

**Comment by Mimiix** [comment]
The folder can be found here:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

After you need to rebind.

**Comment by Smanar** [comment]
Docker, the official deconz docker image ? So will be easy > https://github.com/deconz-community/deconz-docker/issues/163#issuecomment-1366432917

>But unfortunately it doesn't work.

What happen ? The type haven't a big impact on result.

**Comment by madmax5900** [comment]
I added the I to a group.
When I turn on the group it doesn't work.

If I click on the light itself it works.
<img width="277" alt="Bildschirmfoto 2023-09-25 um 21 36 14" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/2ca03e70-5001-4e87-96c8-4de37b21694e">
<img width="449" alt="Bildschirmfoto 2023-09-25 um 21 36 16" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/103837959/0bb94c5c-770b-4664-92c9-fdaa7ae4a07a">

**Comment by Mimiix** [comment]
Hi,

We only do deconz and the rest api here , Not phoscon.

**Comment by Smanar** [comment]
Can be from the DDF too, but for me I don't see problem on your device, you have the group cluster, and your device use normal cluster to work, the 0x0006.
You haven't error message ?
