### ISSUE TITLE
Frient A/S Alarm motion sensor 2 MOSZB-154

### ISSUE THREAD

**Issue by linhgg3** [dresden-elektronik/deconz-rest-plugin#7263]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Alarm motion sensor 2

### Manufacturer

frient A/S

### Model identifier

MOSZB-154

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117278413/903f93f5-97bc-45f1-a16a-69737ea652e3)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117278413/31bab0af-7ba3-406b-8c58-1e5a91a275cf)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117278413/39f6469a-2af7-4837-86d6-e5d4c85a1f90)

### Any other cluster of relevance/interest
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/117278413/e3e7deca-7855-4348-aa77-6fde2a43276a)

**Comment by SwoopX** [comment]
Oh, new toys from them. Should be fairly easy to intergrate. Will check their documentation later.

**Comment by Smanar** [comment]
He realy look than the previous one the MOSZB-141 https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6523

I think a big part of the DDF can be re-used.
