### ISSUE TITLE
Breathing Presence Detector - ZY-M100-1

### ISSUE THREAD

**Issue by jullit31** [dresden-elektronik/deconz-rest-plugin#7266]
### Is there already an existing issue for this?

- [x] I have searched the existing issues and there is none for my device

### Product name

ZY-M100-1

### Manufacturer

_TZE204_qasjif9e

### Model identifier

TS0601

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/19243986/09abc109-3294-42b0-bdac-1631396b0907)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/19243986/28b83d88-bd97-4b2c-b5c9-cc30dfed9c6c)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/19243986/11eb2291-1d6c-4977-8244-e6361d039df2)

### Scenes
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/19243986/7021766b-af8e-4962-847b-3065e185ecef)

**Comment by Mimiix** [comment]
Did you properly search the git?
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7184

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7183

Looks like its supported since 2.24.0.

Closing this issue.

**Comment by jullit31** [comment]
Ahh, thanks! I only searched for "ZY-M100-1", as that is the only identifier written on the box of my device...
So I'll just wait for 2.24.0.

**Comment by Mimiix** [comment]
@jullit31  No problem!

In the future, you should search for the model id/ manufacturer name combo. 

also, you might be able to add the device already by getting its DDF. For help on that, i recommend reading https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet 

If you need any help, check the forums or our discord (as Github is not the correct place)
