### ISSUE TITLE
Still not able to log into his Phoscon with a tablet or cell phone ios

### ISSUE THREAD

**Issue by sansonifabio** [dresden-elektronik/deconz-rest-plugin#7273]
### I truly want to report a bug

- [X] I definitively want to report a bug

### Is there already an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Still not able to log into his Phoscon with a tablet or cell phone.
Gateway is displayed but there is no log in window to log in.

### Steps to reproduce the behavior

xxx

### Expected behavior

xxxx

### Screenshots

xxxx

### Environment

- Host system: Raspberry Pi 
- Running method: Raspbian 
- Firmware version: 26780700
- deCONZ version 2.23.02
- Device: RaspBee I)
- Do you use an USB extension cable:  no
- Is there any other USB or serial devices connected to the host system? No

### deCONZ Logs

xxxx

**Comment by Mimiix** [comment]
Hi,

This is a issue with Phoscon, not deCONZ.

As mentioned in the template, this should be reported on the forums.

Closing.

Kind regards,
