### ISSUE TITLE
Schneider Electric Wiser Mech -> CH/DIMMER/1

### ISSUE THREAD

**Issue by jasonhnz** [dresden-elektronik/deconz-rest-plugin#7275]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Schneider Electric Wiser 40/300-Series Module Dimmer

### Manufacturer

Schneider Electric

### Model identifier

CH/DIMMER/1

### Device type to add

Switch

### Node info

<img width="582" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/49922e8e-afb3-4c4f-818e-00cd3aad0c24">

### Endpoints and clusters

<img width="414" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/c339a268-5399-427d-aaa4-fd0ec728e10c">

### Basic

<img width="539" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/33d4a105-ebd0-43db-8de5-54088d4f8711">

### On/Off

<img width="521" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/6c7b79f5-8f24-4087-b234-5566396863cb">
<img width="527" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/de72a6b8-8f6b-46b2-886e-8a7fa21a7cea">

### Level Control

<img width="519" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/1bf0d0d1-0bdc-4a9f-976f-b76b30214b1e">
<img width="526" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/0698ff0f-4728-41fa-b213-1dc416480e0f">

### Any other cluster of relevance/interest

[Identify]

<img width="533" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/5b612387-e493-4832-974e-9cf1ee01f3f2">

[Groups]

<img width="527" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/e38ec501-c25d-44c4-8d7f-5cb595bbdebf">
<img width="539" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/3d6b4d5e-ac82-4dd4-b139-c3978bae221e">

[Scenes]

<img width="531" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/faf60e5c-5088-4b33-ad22-0490c3d35b42">
<img width="518" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/9673e015-e719-4fc3-a6ef-0f357036950a">
<img width="522" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/ebe6b056-86f1-46df-b2a0-43fd09b1f0ea">
<img width="527" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/edfa8e8a-a453-4139-be2e-56ebe631cc71">

[Ballast Config]
<img width="529" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/ca9aee96-b7cd-4b8d-825f-f69459afccb7">

[Diagnostics]
<img width="534" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/f39b59eb-b4c3-4575-b713-1ad3102c5bc7">

[OTAU]
<img width="543" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/235c78a5-aef6-4d38-9fc3-305a4125f9d8">
<img width="503" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/71586e5e-555c-49bb-a619-e068b6934f10">

[Endpoint 15 - DImmer switch] 

[Basic]
<img width="535" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/ccce6aaf-e9bb-482a-920d-3c2d91760af0">
<img width="504" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/e8000305-5f2d-4386-a1a4-bb86c0ec2f71">

[Identify]
<img width="533" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/734209e1-905d-4a3d-9a5d-78953b800d8b">

[DIagnostics]
<img width="540" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/304e4bd4-c5dd-48c8-9fd8-645e46faf316">

[Schneider specific]
<img width="536" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/330b2c76-0903-490b-87d5-b3af93fb545e">

[Identify]

<img width="540" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/9e239a18-e810-4273-a50b-2d5e2c747a33">

[Groups]
<img width="531" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/8f493aed-f8e6-46ec-aa57-fa4f4e2c96bf">

[Scenes]
<img width="531" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/87b1f3cf-9426-4e87-9ed6-0baa104c0f86">
<img width="523" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/2acafc88-2af5-427e-b4b5-2943a5fd2047">

[On/Off]
<img width="543" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/0545113c-a872-4809-96ef-36fb36862c10">

[Level Control]
<img width="541" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/082d01a0-7a28-4cac-8c1d-7686dff23791">

**Comment by Mimiix** [comment]
Hi,

Looks like not all cluster screens are included. can you please add them?

**Comment by Smanar** [comment]
Waiting for missing clusters, I have started a squeleton.

So first your device have specific zigbee command not managed yet in the DDF, something about ballast and indicator, will see them later.
It seem your device is probably able to work as decoupled mode ? you have a "light" part and a "switch" part. So I have created the switch part on the DDF but this part will work only if we edit the buttonmap.json file, but can be usefull for your delay issue.

About DDF if you want to make try on your side https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet
```
        {
          "name": "state/on",
          "refresh.interval": 5
        },
```

The refresh is a poll, better to use report/bind for information return, so the value used need to be superior at the value set in bind/report configuration

```
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 600
        }
```

Min is the minimum delay without report and max is the maximum beetween 2 reports.

If you still have the report issue when using the device manualy you can see on logs (in help/debug view with flag "info" and "info_l2" if you can see an error about a missing buttomap, and ofc if this error appear without delay.

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Schneider Electric",
  "modelid": "CH/DIMMER/1",
  "product": "40/300-Series Module Dimmer",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x03"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/bri",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x15",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 21,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 21,
      "cl": "0x0008"
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 600
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 3,
      "cl": "0x0008",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x20",
          "min": 1,
          "max": 300,
          "change": "0x01"
        }
      ]
    }
  ]
}
```

**Comment by jasonhnz** [comment]
Adding additional cluster info (Is there any thing else missed, I couldn't find anything specifically about an indicator?) 

Level

<img width="528" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/1db549af-8271-472b-9719-83d830a34be5">
<img width="520" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/126654a4-a066-4e70-a3ee-a25e365947c2">

Ballast

<img width="538" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/f39e7b06-967d-4e49-ba1c-ae7061145168">

**Comment by Mimiix** [comment]
We require all screens of all clusters the device shows. 

Could you add them to the opening post?

**Comment by jasonhnz** [comment]
I have added screens for all clusters across both endpoints.  Thanks for your help.

**Comment by jasonhnz** [comment]
@Mimiix 
@Smanar 

I took the json document with devcap.1... schema and save it into the HASS docker image to the path /usr/share/deCONZ/devices/schneider_electric  (last folder path is what I made).

I created a new json document and pasted the json in. Then went into the deCONZ GUI, selected a Dimmer device node, Edit DDF and selected the json document and did a "Hot Reload"  
This worked! Pressing the physical button was updating the state immediately . 

Reading some additional blog posts about persisting these changes across device/addon restarts, I wanted to test this out so I did a reload of the deCONZ addin in HASSIO and then on reload, all the dimmer lights only were non responsive. 

Having a look in the deCONZ GUI, selecting the DDF for a dimmer device shows the device with params next to the sections.
On/Off Light (1) and Switch(2) which Im sure were not there previously. I suspect it has created a duplicate of sorts and is not aligned with the actual devices this why they are not responding. Any hints as to what I did wrong and how to resolve? 

<img width="191" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/7322514/4a6e2a47-dd82-4280-8c4e-e5bd26e9242f">

**Comment by jasonhnz** [comment]
By doing a device reboot, as well as the deCONZ add on restart, after. few minutes the network was up and connected again and the switches (dimmer) were working again. 

Thinking it may have been the path, i removed the old json file, added it to the path [/data/.local/share/dresden-elektronik/deCONZ/devices/] and did a hot reload, and it worked again. 

Doing a addon reset in HASS took the lights out again this having to restart the conbee2 device and HASS addon again. 
This time eveything else came back except the dimmer switches are still offline. Not sure what I'm doing wrong at this stage...

**Comment by Smanar** [comment]
If you have created a working DDF you can make a PR to submit it.
If you are using the GUI I can explain how to make "bind" and "report" like here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel
Thoses one are important because they are stored on the device, so if you remove them from the DDF, the device will work for you, but not for another users that will use the DDF and the device out of the box.


> I created a new json document and pasted the json in. Then went into the deCONZ GUI, selected a Dimmer device node, Edit DDF and selected the json document and did a "Hot Reload"
> This worked! Pressing the physical button was updating the state immediately .

Good new, it mean, the problem is from the outdated legacy code and not something exotic from your device.

About HA it's a long story https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839
But to resume there is "persistent" folder, and other "virtual" reseted at every restart. If I m right using the GUI, file are stored in the persistent one, else a next restart the device will work (using the legacy code instead) but you will loose all you have added in the DDF.

You can see if the DDF is used or not using the GUI, edit DDF, and look at the path name on the editor title.

On your capture I m seing "Ballast" command, thoses one are usefull ?

**Comment by jasonhnz** [comment]
Thanks, Im not sure why, but if I go into the phoscon web app, it appears that all of my dimmer lights are listed also as switches now. my HA deCONZ instance has picked this up and created a duplicate of all of these lights but created them as switches (not light so cant dim them) and they all are now listed as a switch.<device name> 

Any idea on why this might be? Is it related to maybe after one of the reboots it could not find the json file I imported into the DDF and somehow defaulted to just being a switch?

**Comment by jasonhnz** [comment]
If I was to restore the a previous days backup of HA before I made these changes, would my devices return to their previous state or are there changes physically stored on the switches now that will need to be applied to get them back to being a light within deCONZ.

**Comment by jasonhnz** [comment]
@Smanar My dimmer lights stopped working after a restart. For some reason, they were seen as switches, in addition to a light, which caused issues on the HA side. Removing them and adding them back didnt work until I renamed the json file in the devices folder to something else (with a different extension) and rejoined all the dimmer lights again from scratch.

They all seem to work now. It may be more successful if the json was added as a PR (If you could do it, it would be great) so these are supported out of the box. 
Secondly, as my devices have been readded, the low level latency has been lost. You mentioned being able to add/adjust the bindings for my devices only. Could you detail what that would look like so I could try that avenue ? Thanks

**Comment by Smanar** [comment]
Hu, I m not sure to understand how many operation you have done ^^.
But for a DDF persisitent, on HA it need to be in `/data/.local/share/dresden-elektronik/deCONZ/devices/` and I think it's the folder used by the GUI, if you make yourself a DDF using the editor.

On the DDF there is an unused part for a "sensor" a ZHASwitch, and we can remove this part.

On the DDF I m using a TYPE_ON_OFF_LIGHT, better to use a  TYPE_DIMMABLE_LIGHT.

Take care at what you are calling switch on deconz, a wired switch is a light for exemple.

So there is a working DDF ? wich one ? ^^ because you have done so much operation.

>the low level latency has been lost

Soi it's fine ?

>You mentioned being able to add/adjust the bindings for my devices only. Could you detail what that would look like so I could try that avenue ? Thanks

But you haven't already a workinbg DDF ? this one haven"t bind/report ?

**Comment by jasonhnz** [comment]
I suspect the cause of the problems on my side was the TYPE being [TYPE_ON_OFF_LIGHT] instead of [TYPE_DIMMABLE_LIGHT] 

Based on your suggestion above, I made the change locally and reloaded the ddf and the lights came back. 
Originally, with the type of on/off switch in the ddf file, all the entities became a light on/off switch instead of a dimmer so they dropped of within HA due to the name change.  With the update of the type to be a DIMMABLE_LIGHT, it reenabled all of the lights again within the deconz app. 

So I think the original json you created works, it just needs the TYPE to be changed.

**Comment by Smanar** [comment]
>So I think the original json you created works, it just needs the TYPE to be changed.

And do you want I remove the "sensor" SHASwich part ? As it seem this part is not usefull for you ?

**Comment by jasonhnz** [comment]
yes thanks. Its not needed in this instance.

**Comment by Smanar** [comment]
Done, if you want to take a look https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7282
