### ISSUE TITLE
Equation wire pilot heating

### ISSUE THREAD

**Issue by Mimic33** [dresden-elektronik/deconz-rest-plugin#7280]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Equation wire pilot heating

### Manufacturer

Adeo

### Model identifier

SIN-4-FP-21_EQU

### Device type to add

None

### Node info

![Node info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/ac20fd31-c8cd-4ae8-9763-fd50d2e06267)

### Endpoints and clusters

![Endpoints](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/5ea9b075-2995-4203-b92a-b8b030103091)

### Basic

![Basic1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/5c0b827e-0726-4c84-942c-00d71fc82e59)
![Basic2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/1d2e0239-5a8e-409c-91f3-4e086adc20c5)

### On/Off
![OnOff1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/b4c86674-9708-4ddc-8346-6386a595a834)
![OnOff2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/eb6784ea-5437-4e51-8100-7f48ec35ac5b)

### Simple Metering
![Metering1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/e9cc7628-9da0-4ceb-a164-ee4effa9147d)
![Metering2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/02733c19-593d-49a0-8493-d96a17429c0e)
![Metering3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/0b513b6d-4bb8-4dd7-aba8-196a999ba4cb)

### Green Power
![GreenPower](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/c9f28064-3bd4-4d8b-a5db-5a1186f9faf1)

### Identify :
![Identify](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/de7de9cc-a8dc-43aa-8974-e16352e716ba)

### Groups :
![Groups](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/bb4776aa-8dd6-410f-804b-9f82ea7a53db)

### Scenes :
![Scenes1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/b653d745-fc99-4010-87ae-7407b96d4dd1)
![Scenes2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/a43c3283-2c51-4f71-b4d6-771677948cef)

**Comment by Mimic33** [comment]
Hi, here an issue for a wire pilot heating module. It has been recognized in Deconz and Jeedom but I only have state/on and off in Jeedom. And the off option corresponds to the no frost protection on the heater, not the off option. Normally I would have 6 orders (Confort, Off, no frost protection, eco, ...). This module could also give the consumption. Thanks.

**Comment by Mimic33** [comment]
Identify :
![Identify](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/c25e3bc4-b5a6-44a3-8c27-6cda6b4175bd)

Groups :
![Groups](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/02ea4ea2-5670-45c0-93e1-b235dd18faa9)

Scenes :
![Scenes1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/6138bd3a-1501-4381-8961-2562c2e10499)
![Scenes2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105454698/dcaba639-49fe-4168-9630-dc16f19d6aad)

**Comment by Mimic33** [comment]
Do you want the OTAU also ?

**Comment by Mimiix** [comment]
> Do you want the OTAU also ?

No , thats fine.

Please add the screens in the opening post, makes it easier to read :)

**Comment by Mimic33** [comment]
OK, done :) Sorry it's my first time :)

**Comment by Mimic33** [comment]
Hello, any news ? Thanks.

**Comment by hcharbonnier** [comment]
News from Nodon (for zigbee2mqttsupport): "Integration is in progress. It will be done within a few days."

**Comment by Mimic33** [comment]
OK thanks, and for Deconz, you know ?

**Comment by pipiche38** [comment]
+1

**Comment by Smanar** [comment]
lol, @pipiche38 you are using deconz too ?
On my side, it's not my priority as I already have problem with the Legrand one, the "fil pliote" is something "exotic" for not french user, and hard to integrate it without making a "special" stuff for it.

**Comment by Mimic33** [comment]
OK thanks for the reply. Maybe ideas her https://github.com/Koenkk/zigbee-herdsman-converters/pull/6429

**Comment by Mimic33** [comment]
This subject has been closed ?

**Comment by Smanar** [comment]
Yep, by a bot after a period without reaction.
Can be re-opened, but I don't think someone have started something.

**Comment by Mimiix** [comment]
@Smanar happy to be re open but what do we need ?

**Comment by Smanar** [comment]
For me nothing, this device have a working mode too much exotic, it will be problematic in deconz and later in the HA plugin.
If someone want to spend some time, I think the DDF need to have something like

```
{
  "name": "config/mode",
          "values": [
              ["confort", 1], ["confort-1", 4], ["confort-2", 5], ["confort-2", 3], ["eco", 2], ["hors gel", 3], ["off", 0]
          ],
  "parse": {
    "fn": "zcl:cmd",
    "ep": 1,
    "cl": "0xFC00",
    "cmd": "0x00",
    "eval": "if (Attr.val == 0) { Item.val = 'off' } else if (Attr.val == 1) { Item.val = 'confort' } else { Item.val = 'confort-2' }"
  },
  "read": {
    "fn": "zcl:cmd",
    "ep": 1,
    "cl": "0xFC00",
    "cmd": "0x00",
    "eval": "if (Attr.val == 0) { Item.val = 'off' } else if (Attr.val == 1) { Item.val = 'confort' } else { Item.val = 'confort-2' }"
  },
  "write": {
    "fn": "zcl:cmd",
    "ep": 1,
    "cl": "0xFC00",
    "cmd": "0x00",
    "eval": "if (Item.val == 'off') { 0 } else if (Item.val == 'confort') { 1 } else { 3 }"
  }
}
```

**Comment by Mimic33** [comment]
Thanks, and if I want to use it, what I have to do ?

**Comment by Smanar** [comment]
Make a complete DDF.
For exemple to start

```
{
  "schema": "devcap1.schema.json",
  "ddfvalidate": false,
  "manufacturername": "Adeo",
  "modelid": "SIN-4-FP-21_EQU",
  "product": "Cable outlet",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0201"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0001",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0201",
          "0xFC40"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/mode",
          "values": [["confort",1],["confort-1",4],["confort-2",5],["confort-2",3],["eco",2],["hors gel",3],["off",0]],
          "parse": {
            "fn": "zcl:cmd",
            "ep": 1,
            "cl": "0xFC00",
            "cmd": "0x00",
            "eval": "if (Attr.val == 0) { Item.val = 'off' } else if (Attr.val == 1) { Item.val = 'confort' } else { Item.val = 'confort-2' }"
          },
          "read": {
            "fn": "zcl:cmd",
            "ep": 1,
            "cl": "0xFC00",
            "cmd": "0x00",
            "eval": "if (Attr.val == 0) { Item.val = 'off' } else if (Attr.val == 1) { Item.val = 'confort' } else { Item.val = 'confort-2' }"
          },
          "write": {
            "fn": "zcl:cmd",
            "ep": 1,
            "cl": "0xFC00",
            "cmd": "0x00",
            "eval": "if (Item.val == 'off') { 0 } else if (Item.val == 'confort') { 1 } else { 3 }"
          }
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0xFC00",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 1,
          "max": 3600,
          "change": "0x00000000"
        }
      ]
    }
  ]
}
```
