### ISSUE TITLE
Upgrade to Bookworm, Deconz works but apt throws warning

### ISSUE THREAD

**Issue by guitardoc** [dresden-elektronik/deconz-rest-plugin#7287]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I upgraded to bookworm today and so far all works fine. However, when I carry out 

`sudo apt update && sudo apt full-upgrade`

I get the following warning:

`W: http://phoscon.de/apt/deconz/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

What is there to do to remedy this?

Thank you for looking into it.

### Steps to reproduce the behavior

see above

### Expected behavior

see above

### Environment

- Host system: (Raspberry Pi)
- Running method: (Raspbian Bookworm)
- Firmware version: (12.1)
- deCONZ version (not Home assistant Addon version!): (2.xx.yy)
- Device: (ConBee II)
- Do you use an USB extension cable: (no)
- Is there any other USB or serial devices connected to the host system? (no)

**Comment by SwoopX** [comment]
Closing, as this is no bug as you wrote yourself. Questions may be raised in the forum.
