### ISSUE TITLE
Tuya Millimeter Wave Presence Detector ZG-205Z

### ISSUE THREAD

**Issue by m-kuutti** [dresden-elektronik/deconz-rest-plugin#7288]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Human presence detector ZQ-205Z

### Manufacturer

_TZE200_2aaelwxk

### Model identifier

TS0225

### Device type to add

Sensor

### Node info

<img width="552" alt="node" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76905228/0174d256-8f71-489f-82d3-4dc8de07a50e">

### Endpoints and clusters

<img width="341" alt="clusters" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76905228/163f080e-5780-4bf0-a5c9-9d208c0bb5d5">

### Basic

<img width="438" alt="Basic" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76905228/060edf0e-a2ee-4c76-8898-b804e611a589">

### Any other cluster of relevance/interest
<img width="425" alt="IAS Zone" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76905228/e5eef688-8570-4dca-b0bf-027f359cb1c0">

<img width="439" alt="Illuminance measurement" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76905228/e24cc3c1-5697-4149-95e7-8a42c1bda656">

**Comment by BabaIsYou** [comment]
Seems a clone of this one #7223

**Comment by Mimiix** [comment]
re-opening as theres someone else who can maybe test @BabaIsYou .

**Comment by m-kuutti** [comment]
I can of course also test when there’s something to test, or do.

**Comment by BabaIsYou** [comment]
What I meant i just that these two devices seems to be clone of each other. Then that a proposed DDF for one of them could probably fit for the second.

But I didn't proposed any DDF at this time ...

**Comment by kwatt67** [comment]
Did you get a DDF that worked for this sensor as I tried the one referenced but that hasn't worked?

**Comment by m-kuutti** [comment]
It hasn’t worked for me :(On 3. Feb 2024, at 22.15, kwatt67 ***@***.***> wrote:﻿
Did you get a DDF that worked for this sensor as I tried the one referenced but that hasn't worked?

**Comment by jeanmi-git** [comment]
Hello,

I have received this presence sensor and it did not pair with my deConz conBee 2 zigbee dongle.
I running deconz 2.25.3 with docker on a Synology NAS.

I hope it will be compatible soon.

**Comment by jeanmi-git** [comment]
> As there has not been any response in 28 days, this issue will be closed. **@ OP: If this issue is solved post what fixed it for you. If it is not solved, request to get this opened again.**

Could this issue be re-opened, please ?

**Comment by megamacy** [comment]
> > As there has not been any response in 28 days, this issue will be closed. **@ OP: If this issue is solved post what fixed it for you. If it is not solved, request to get this opened again.**
> 
> Could this issue be re-opened, please ? I tested with the last version : 2.26, and sensor is still not discovered.

It is discovered, but not usable cause of missing compatible DDF

**Comment by jeanmi-git** [comment]
I'm not familiar with the internal functionning of the deconz application.
How can we get a compatible DDF ?

**Comment by megamacy** [comment]
Im new to this too. only got to it because the sensor is not working with deconz 

As far as i know, deconz need to be compatible (it is since v2.25 changelog) and then someone who knows how, need to create that ddf. A file that point the events to recognized commands. 
Once it is done, we can download it and put it to the "devices" directory of our deconz server and set DDF handling to "strict" for  enable load custom files, then pair it again

heres a ddf imported example, but its not working
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/118570604/2f5493f1-7204-4eca-8f02-cedc98e9fa44)

**Comment by Jupp2** [comment]
I am also still looking for a working ddf. I modified existing once but only came to a point that general object detection worked. But it was useless because too sensible. The Sensor generally has adjustable sensitivity and 2 types of object sizes or movement Levels it can differentiate. With Zigbee2MQTT all this works Like many other Sensors. I have the Feeling Zigbee2MQTT is better maintained.

**Comment by megamacy** [comment]
> I am also still looking for a working ddf. I modified existing once but only came to a point that general object detection worked. But it was useless because too sensible. The Sensor generally has adjustable sensitivity and 2 types of object sizes or movement Levels it can differentiate. With Zigbee2MQTT all this works Like many other Sensors. I have the Feeling Zigbee2MQTT is better maintained.

Can you share that ddf? i dont know how to get anything working on this sensor

**Comment by Jupp2** [comment]
Will look for it when back home in about a week.

**Comment by jeanmi-git** [comment]
Hello,
Did you find your DDF ?

**Comment by Jupp2** [comment]
[ts0225.json](https://github.com/dresden-elektronik/deconz-rest-plugin/files/14865787/ts0225.json)
this is the DDF which works an a very basic level with my ZG-205Z. 
you may need to change the "manufacturername": "_TZE200_2aaelwxk" to the name you sensor has - they often differ slightly after the _ .

**Comment by Jupp2** [comment]
Here is what it looks like in zigbee2mqtt: 
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/63ed47ac-89a4-4623-80b1-68e6b2d8d21c)
Any idea how to implement these settings and readings in Deconz by DDF (esp. "Motion state" and "Large motion detection distance" are relevant to use it as a human presence sensor)?

**Comment by Tech4Ever** [comment]
Hi,

any progression on this issue? I received this sensor, too, but it´s not working.

**Comment by gituser-rk** [comment]
Hello,
replace the file /usr/share/deCONZ/devices/tuya/ZY-M100_human_breathing_presence.json with the attached version. this works for me. I did a restart of the gateway after replacing the file. After that, I was able to integrate the sensor via Phoscon WEB-GUI.
There are several datapoints missing for configiring the sensor and the light level is also missing. Maybe it helps someone.
[ZY-M100_human_breathing_presence.json](https://github.com/user-attachments/files/17852718/ZY-M100_human_breathing_presence.json)
