### ISSUE TITLE
Namron Multisensor

### ISSUE THREAD

**Issue by le-clu** [dresden-elektronik/deconz-rest-plugin#7290]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Namron Zigbee Multisensor

### Manufacturer

Namron AS

### Model identifier

4512770

### Device type to add

Sensor

### Node info

![AF9E9D14-DC60-4B1C-A5B2-56836C926420_1_105_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/f7ba6aab-6ecb-4449-994e-a6ea60b79680)

### Endpoints and clusters

![DE7604E2-2C0C-448C-99C9-0B757F24F1AE_4_5005_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/7c851fbe-d1b7-4c20-9e88-07c68708b5e2)

### Basic

![3C5FFAAA-EC18-4CD4-A122-65ACD67EAEB9_1_105_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/9512b61a-112e-4766-bb7b-27c9a9eac186)

![E54623ED-5F9A-4335-B092-317C82B24A70_1_105_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/9e67f603-58c0-43be-9a6c-71a6468690aa)

![E7D2C1E1-DC91-463C-9753-C05D41ED9EB0_1_105_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/91ab4850-1e6e-4d04-921e-fbe19e73dcae)

![AA3D8283-7958-4938-9559-CDB3D67EC186_1_105_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/84488ae9-e562-4353-a8a4-101bb955a7c9)

![891F3CA8-36FF-417F-8A3C-3234106D0443_1_105_c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/89c2c087-c2b1-45db-a1c8-5a93460cdb08)

### Power Configuration
<img width="386" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/b0d15de2-7260-42d3-b643-3e9330651b96">

### IAS Zone
<img width="580" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/8b49eb58-195a-4e41-ae6a-86eeb332f5b6">

### Occupancy sensing
<img width="384" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/e6df0dcd-c380-4f17-9eb1-6fa07f339aff">

**Comment by le-clu** [comment]
Hi. I already gave it a try to create a DDF file, and managed to see the sensors in Home Assistant. However, their values do not seem to update - and I don't really understand the motion sensor/IAS zone.

[namron-multisensor-4512770.json.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/12850096/namron-multisensor-4512770.json.txt)

Would really appreciate if anyone could help out - and of course make it an official device later on. :) 

Thanks!

**Comment by BabaIsYou** [comment]
Well, nice try, but how to start ? ;-)

1. There are a lot of screenshots that are missing (clusters 0400, 0405, 0402, 0400, etc ...)
2. Why is "sleeper" to false ? Surprising if it's a battery powered device.
3.  Why did you detailed "attr/manufacturername" ? It's a standard Zigbee attribute
4.    Please change temp sensor to  {
```
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x03",
        "0x0402"
      ],
``` 
and let "state/temperature" without useless details

```
        {
          "name": "state/temperature"
        }
```
5. Change hum sensor with : 
```
     "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x04",
        "0x0405"
      ],
```
6. Change presence sensor with
```
    {
      "type": "$TYPE_PRESENCE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0406"
      ],
```
and let "state/presence" without details

```
        {
          "name": "state/presence",
                  }
```

7. For light level we will see after the 0x0400 cluster screenshot to see if it returns lux or light level to adjust DDF. But for sure you can already change   ` "0x0106" `by `"0x0400"`
8. and last, but cetainly not least. there are no bindings into you're DDF, then may be some of the values won't be automatically reported. I suggest to read https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by le-clu** [comment]
Hi. First of all thanks for your help! Appreciate your elaborate answer!

It was the first time for me to create a DDF but after your comments, I do understand it much better.

Implemented all changes as per your suggestions. 
Pasting additional screenshots below.

Regarding binding: I need to read a bit more about that - don't understand the concept yet, so I need some time.

One more generic question: how do I safely exchange DDFs between docker container and host? I run Home Assistant OS on RPI and made it work using 
`docker exec -it addon_core_deconz bash`
`docker cp [...]`
and it did the trick. BUT afterwards the container/add-on couldn't be stopped anymore. So after re-installing and restoring everything (I may have overreacted), I am now a bit defensive....

Thanks!

### Screenshots
**Light sensor 0400**
<img width="960" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/dafc51b2-fd4c-4be7-8a32-517f77eab787">

**Humidity sensor 0405**
<img width="965" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/add16409-8a24-4ee1-a943-19fa9ae6c6b0">

**Temperature sensor 0402**
<img width="955" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/b6316eea-e35c-4614-9350-3e8bff7972cf">

**IAS Zone 0500**
<img width="958" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/31bf5832-14d5-48f8-9291-8f57aaab691d">

**Occupancy sensor 0406**
<img width="972" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/97918159/d9d4ff78-023f-45e4-a440-9437067123b0">

**Comment by le-clu** [comment]
Hi @BabaIsYou 
Would you be able to have a look at my last reply please?

thanks!

**Comment by BabaIsYou** [comment]
Hi,

sorry, very busy these last months. Can you display your last corrected DDF and saying what seems to work and what doesn’t ?

regarding docker and HA OS you’ll certainly find other posts on git, I’m not familiar with those.
