### ISSUE TITLE
Haozee zigbee pir

### ISSUE THREAD

**Issue by basbeheertje** [dresden-elektronik/deconz-rest-plugin#7291]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Haozee zigbee pir

### Manufacturer

_TZ3000_mg4dy6z6

### Model identifier

TS0202

### Device type to add

Sensor

### Node info

It looks a lot like https://raw.githubusercontent.com/dresden-elektronik/deconz-rest-plugin/master/devices/tuya/ts0202_presence_sensor.json but is not present as manufacturer.

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1433396/59608b57-810d-49ab-97d8-2c0be71c13fb)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1433396/6a521a33-405f-480c-96ea-476e286748ab)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1433396/05c30d1d-2a34-4db3-aa83-744b67bc4c21)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1433396/7308b061-c36d-4d36-a3d0-a7952f41cedb)

### Any other cluster of relevance/interest
Ali express link https://nl.aliexpress.com/item/1005005916424396.html?spm=a2g0o.order_list.order_list_main.23.32fa79d2yjQxbt&gatewayAdapt=glo2nld

**Comment by Mimiix** [comment]
Missing a few screenshots. Can you please add them?

**Comment by BabaIsYou** [comment]
> It looks a lot like https://raw.githubusercontent.com/dresden-elektronik/deconz-rest-plugin/master/devices/tuya/ts0202_presence_sensor.json but is not present as manufacturer.

You're right, may be then just try to add "_TZ3000_mg4dy6z6" into the "manufacturername" list, and aanother "TS0202" into the "modelid" list (you can try using DDF editor from the GUI) and I'm quite sure that it will do the trick.

**Comment by basbeheertje** [comment]
> _TZ3000_mg4dy6z6

Yes it works

**Comment by BabaIsYou** [comment]
Then you’re ready to make a pull request (PR) with the changes ;-)
