### ISSUE TITLE
Dresden Elektronik Scene Switch - dimming doesn't work 

### ISSUE THREAD

**Issue by jnmarczi** [dresden-elektronik/deconz-rest-plugin#7292]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Unfortunately, dimming no longer works with the Dresden Elektronik Scene Switch. 
It worked before, I have set the corresponding key assignment a long time ago. 
Dimming the light (group) using the Phoscon Web App works.

### Steps to reproduce the behavior

See attached screenshot for key assignment.

### Expected behavior

Working dimming functionality.

### Screenshots

![2023-10-11 16_41_02-Phoscon App – Mozilla Firefox](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9981735/4fdb9068-f2f9-4b60-bf50-c719eaae433c)
![2023-10-11 16_41_29-Phoscon App – Mozilla Firefox](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9981735/43def3bc-490b-49a4-ae77-9fb4d7ef5383)

### Environment

- Host system: Raspberry Pi
- Running method: Raspbian
- Firmware version: 26720700
- deCONZ version: 2.23.2 / 2.24.1-beta
- Device: RaspBee II

**Comment by Mimiix** [comment]
Hi

If you click Events under Help - api information in phoscon, do you see events while pressing the button?

Kind regards

**Comment by jnmarczi** [comment]
I see events while pressing and holding the lower button, but not at the upper button. i see events for short key press.

[events.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/12873288/events.txt)

**Comment by Mimiix** [comment]
> I see events while pressing and holding the lower button, but not at the upper button. i see events for short key press at both buttons.
> 
> [events.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/12873288/events.txt)

Can you try the upper a few more times?

Was this the same as before?

**Comment by jnmarczi** [comment]
Same behaviour... i even tried with different Scene Switches. Deterministic behaviour.

**Comment by Mimiix** [comment]
> Same behaviour... i even tried it with different Scene Switches. Deterministic behaviour.

Same as prior the update , just the phoscon switch mapping stopped working?

**Comment by jnmarczi** [comment]
Same bug at all three installed Scene Switches here. 
I just added a new dimming key mapping at another Scene Switch and it doesn't work either.

Unfortnunately I don't know since when this behaviour is this way, we haven't used that switch for months.

**Comment by jnmarczi** [comment]
Btw. the led at the Scene Switch signals data sent for the several events (key press, key hold, key release).

**Comment by Mimiix** [comment]
I want to find out if the issue is phoscon or deconz. Are the events correct like they were before or not?

If it's the mappings not working, I am closing this issue and you need to report it on the forums.

**Comment by jnmarczi** [comment]
The events are definitely not correct, since there are no "key hold" and "key release" events ( i assume buttonevent 1001 and 1003).

**Comment by Mimiix** [comment]
Clear. I've asked devs to check in

**Comment by manup** [comment]
Hi, this is definitively strange if I remember correctly we had fixed this very issue a while ago :thinking: 
I'll schedule a re-test

**Comment by Oliver-18** [comment]
I have the same issue with 11 scene switches with firmware 02010032, while one with version 02020010 works. My deConz version is 2.23.02

**Comment by noodles321** [comment]
I have the same issue with all of my Senic FoH switches. My deconz Version is 2.24.1 (Docker).

**Comment by manup** [comment]
Small Update here, I've now removed the crazy legacy code for this and added a DDF for Scene Switch which works as it should with the Phoscon App switch editor. For the Lighting Switch I'll make this too.

There is however one caveat, the group which the switch sends to can't be reconfigured (needs to be fixed in a future firmware update) and on a factory reset the group is a random new one.

As long as the switch is configured via Phoscon App and gateway is online that's not a problem (deCONZ gets the button messages and just sends the control command to the actual group), but it's not suitable for using the switch offline without gateway.
