### ISSUE TITLE
Elko dimmer not responding to switch

### ISSUE THREAD

**Issue by kristianwh** [dresden-elektronik/deconz-rest-plugin#730]
I have a bunch of Elko dimmers (Dimmer model: ELKO ESH Plus 316GLED dimmer RF http://bit.ly/2oLyvxs), ref. issue #464 
Using deconz V2_05_34

I have tried the new switch editor. It works on my Hue and IKEA bulbs, but I can not get it to do anything with these dimmers, even if they are added to the same group. It looks from Phoscon like they turn on/off when clicking the switch, but these dimmers remain dark. Manually switching/dimming from Phoscon/Home Assistant works fine.

**Comment by manup** [comment]
Can you control them as group from the Phoscon App?

The rules which are created by the switch editor currently only work on groups. There were devices in the past which only supported unicast commands and would ignore group commands.

**Comment by kristianwh** [comment]
Hmm, yes, I think I actually had some problems with controlling them in a group, so this might be the explanation. Is there any configuration I can do to achieve this, or is it just a limitation of these devices?

**Comment by manup** [comment]
The limitation is in the devices firmware (if this is the case here), only workaround is to send just unicast commands.

**Comment by kristianwh** [comment]
Ok, thanks. I'll close the issue, and hope for a firmware upgrade for my devices :)
