### ISSUE TITLE
Zemismart 2 gang switch _TZ3000_lupfd8zu

### ISSUE THREAD

**Issue by kuszek** [dresden-elektronik/deconz-rest-plugin#7301]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Zemismart Tuya 2 gang no neutral switch

### Manufacturer

_TZ3000_lupfd8zu

### Model identifier

TS0012

### Device type to add

Switch

### Node info

![00](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/579ca87b-a5f0-417e-8775-64428b3fb311)

### Endpoints and clusters

![02a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/22f6494d-9597-417c-ab76-4858fde07cbf)
![02b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/e07ccf11-a2a0-46bb-aadd-858f8484de23)

### Basic

![01](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/bac4f2c9-691d-4483-a368-44faffb980f9)

### Groups
![03](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/8dd154a1-290b-4cf1-9589-c41d57b95cf7)
![04](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/f1380a37-03ab-48a3-bd30-7340594febfd)

### Scenes
![05](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/787bbd82-e10f-4c90-9f31-9c6a53cbed5a)
![06](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/e3935d91-9c2e-41e5-9ce2-8f8962b143b8)
![07](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/6d1b26e9-e759-468f-bb81-76f175f5a14e)
![08](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/2f1b810d-b412-427f-9818-a37bae89ac0d)

### On/Off
![09](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/e54cf530-cf4d-4b02-b1bc-0506c0fbb396)
![10](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/b5da12c0-25b5-4a47-969b-6ab7797ac7cc)

### Tuya specific
![11](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/0f81e854-af0d-48f8-9c3a-85fab1298bc5)

### OTAU
![12](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66242908/a5dd2a8c-b511-4f9b-9f72-7f1a72c28137)

**Comment by kuszek** [comment]
This device might be releated to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6870 or https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6798

**Comment by Smanar** [comment]
Yeah ^^ probably. Can make a try just add the device to the list.
There is 2 kind of 2 gangs devices, the locked and the unlocked. Can try first the unlocked one

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_lupfd8zu",
  "modelid": "TS0012",
  "product": "Tuya 2 gangs wired without neutral",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "config/tuya_unlock"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001",
            "script": "tuya_swversion.js"
          },
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x0001"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by kuszek** [comment]
Thank you for such a quick response. It works :)

**Comment by Smanar** [comment]
Nice ^^
Do you want to make the PR or want I make it ?

I think we can create a new file, because all other are for locked device. So a file called devices/tuya
/TS0012_2gang_wired_not_locked.json for exemple.

And need to replace TYPE_ON_OFF_OUTPUT by TYPE_ON_OFF_LIGHT (I have copy/paste a switch module for test)

**Comment by kuszek** [comment]
I haven't created a PR yet so it would be best if you could do it.
Output worked fine for me. In Phoscon it shows up as a light and in Home Assistant it shows up a switch. It's the same for all my Zemismart switches, but if you want to fix I have no issue with that.

**Comment by Smanar** [comment]
>Output worked fine for me. In Phoscon it shows up as a light and in Home Assistant it shows up a switch. It's the same for all my Zemismart switches, but if you want to fix it, I have no issue with that.

No, it don't cause issue, it's more "cosmetic"

PR done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7304
