### ISSUE TITLE
Device Request: MHCOZY ZG-005-RF

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#7309]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name
MHCOZY 4-Channel Dry Contact Smart Wireless Zigbee Switch Relay Module

### Manufacturer
_TZ3000_u3oupgdy

It uses the Tuya convention for the _Manufacturer Name_, but the device itself shows `MHCOZY`.

### Model identifier

TS0004

It uses the Tuya convention for the _Model Identifier_, but the device itself shows `ZG-005-RF`.

### Device type to add

Other

Four relays, to be exposed as four `/lights` resources, of type _On/Off Output_.

### Node info

<img width="633" alt="Screenshot 2023-10-20 at 12 21 06" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/22179355/2c8a97d6-0d62-4491-b9b0-3eaed305f71b">

Note that the common info is already provided by my DDF in the works.

### Endpoints and clusters

<img width="255" alt="Screenshot 2023-10-20 at 12 21 44" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/22179355/d4cb3a3f-6ace-4d34-a94e-2ea0a54d8840">

This looks particularly good: four _On/off light_ endpoints (should have been _On/off output_ imho), each with _On/Off_, _Groups_, _Scenes_ and _Tuya Specific_ clusters.  Each endpoint controls and reports the corresponding relay.  There are some special device-wide features on the first endpoint.

### Basic

<img width="642" alt="Screenshot 2023-10-20 at 12 22 26" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/22179355/d3cfdd3c-e957-43b1-a9f2-879561798d23">

No _SW Build ID_ nor _Date Code_, but _Application Version_ seems to encode the firmware version in Tuya style, so 0xXYZZ for X.Y.Z.  So 80 = 0x50 = 1.1.0.

### On/Off
<img width="642" alt="Screenshot 2023-10-20 at 12 23 12" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/22179355/6b8f886a-73d8-4e9d-9892-00cad7b7e332">

0x8001 and 0x8002 are only supported on the first endpoint.  0x8001 doesn't seem to do anything; 0x8002 just sets the poweron behaviour (0xE001/0xD010) on all four endpoints.

### Tuya Specific
<img width="642" alt="Screenshot 2023-10-20 at 12 24 13" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/22179355/9eadbb56-3f4d-4f8b-87e2-07dbfde4878a">

0xD010 sets the poweron behaviour of the corresponding relay to _Off_, _On_, or _Previous_, similar to the standard 0x0006/0x4003 attribute on other devices.  Note that _Previous_ uses value 2, however, instead of 0xFF.

0xD030 is only supported on the first endpoint.  It controls the behaviour of the four physical push buttons on the device, controlling the four relays.  Values 0 (_Toggle_) and (_State_) cause the relay to toggle on press/release; value 2 (_Momentary_) causes the relay to be on, only while the button remains pressed.

There is a fifth physical push button on the device, that switches between self-locking, interlock, and jog mode.  I haven't been able to get this mode reported nor controlled over Zigbee.

### Other Remarks
All relevant attributes support attribute reporting, and by default report to the coordinator.  Even after a _Write Attributes_,  a report is sent.  However, I see no reports (nor any other Zigbee message) when changing the device mode.

In interlock mode, only one relay can be on at a given time.  The other relay turns off first, before the relay controlled turns on.  The reports are sent in revese order, though (first the endpoint of the relay controlled, then the other endpoint).

In jog mode, each relay switches off automatically after ~0.5 seconds.  The documentation suggests that this period would be configurable from the app, but it's not clear how the device supports that.  I did capture an attribute report with more attributes than currently defined in `general.xml`, not sure if that was on 0xE001 or on 0xE000.

**Comment by Smanar** [comment]
I don't understand how the manufacture name/model id can be different on basic cluster and node information ?

**Comment by Mimiix** [comment]
Erik and a Tuya device. Wauwie

**Comment by ebaauw** [comment]
Ping

**Comment by ebaauw** [comment]
Ping

**Comment by TKAB** [comment]
I also have a problem with this device.

**Comment by Smanar** [comment]
Wich one ?

**Comment by TKAB** [comment]
When controlled via zigbee I cannot control just one channel. Instead in most cases all four channels switch to on (not exactly at the same moment, but rather in short succession) or off; in other cases a single channel switches to on for a very short time and then off again; and then there are some rare cases that are difficult to describe and reproduce.
