### ISSUE TITLE
Cannot connect IKEA Tradfri Dimmer Switch

### ISSUE THREAD

**Issue by SillyTones** [dresden-elektronik/deconz-rest-plugin#731]
I use the RaspBee module on the RPi2 with headless deconz. After multiple attempts to connect to deConz (as described in the Phoscon WebApp) i still cannot get a connection.

**Comment by jantje88** [comment]
Do you have a recent firmware on your raspbee? Had the same problem with the Tradfri dimmer and raspbee firmware 26050500 but with 261F0500 it is working fine.
