### ISSUE TITLE
_TZ3000_yxqnffam - TS0203 - Tuya Smart Zigbee Door Window Contact Sensor ZigBee 3.0

### ISSUE THREAD

**Issue by Jupp2** [dresden-elektronik/deconz-rest-plugin#7318]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tuya Smart Zigbee Door Window Contact Sensor ZigBee 3.0

### Manufacturer

_TZ3000_yxqnffam

### Model identifier

TS0203

### Device type to add

Sensor

### Node info

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/c3fef041-3b69-49df-b251-f06ef5600a31)

### Endpoints and clusters

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/706c9d65-d2f1-456b-b25c-9bf081a53cb8)

### Basic

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/d45e492c-1e86-4e7c-9661-aab863eeed49)

### Power Configuration
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/e385b668-93b0-47cd-abe2-5e397af852c1)

### Any other cluster of relevance/interest
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/dcfb5f11-eb42-4c98-90aa-ed9b3a0b99c4)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/87aea60a-8a0a-49b2-aa55-cc6f7350017a)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/149000775/f9f4b7e3-63b4-43a0-a3bb-98fbda3f0982)

**Comment by Jupp2** [comment]
@Smanar
Hello Smanar, This is the Door Window Sensors I have. Only difference I see is manufacturer compared to:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5819 and https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5301#.
Could you add the clone manufacturer?
I made them somehow work at my home, by modifying the DDF.

**Comment by Mimiix** [comment]
Please add all screens.

**Comment by Mimiix** [comment]
> He have tested the device, so it's more an information than a device request. And it's certainly another clone, we can't make direclty a DDF update in this situation ?
> 
> He could have made a PR, so without capture.

I prefer to have all screens, regardless if its correct.

**Comment by Jupp2** [comment]
I added the screens which are not fully empty. Hopefully this is "all" ?

**Comment by Smanar** [comment]
Done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7321
