### ISSUE TITLE
TRADFRI bulb GU10 CWS 345lm

### ISSUE THREAD

**Issue by bluemoehre** [dresden-elektronik/deconz-rest-plugin#7319]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

TRADFRI LED 345lm

### Manufacturer

IKEA of Sweden

### Model identifier

TRADFRI bulb GU10 CWS 345lm

### Device type to add

Light

### Node info

![Screenshot 2023-10-26 140210](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1735386/b73389c3-735f-40d3-ac8e-a38207f2ba2d)

### Endpoints and clusters

![Screenshot 2023-10-26 140527](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1735386/d12862d5-386d-4079-8ee2-c38b92ee27e7)

### Basic

![Screenshot 2023-10-26 140707](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1735386/2cb47d6a-a036-4625-b83c-2ab564afac5e)

### On/Off

![Screenshot 2023-10-26 140935](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1735386/ccd3505f-d4dd-409c-b48b-a451c8c2eb40)

### Level Control

![Screenshot 2023-10-26 141042](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1735386/e2c24bd2-8ec9-4a5e-a312-b383d1d0483a)

### Color Control

![Screenshot 2023-10-26 141530](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1735386/7a23990b-e628-4902-a9d4-0b0a60d13ccc)

**Comment by ebaauw** [comment]
What's the _Image Type_ of this light?

**Comment by bluemoehre** [comment]
Yes, it's `0x2802`. But if you just merge it into the other light I am afraid we cannot fill the field `product` correctly. That's another point why I wrote in my linked PR #7320 that I prefer a JSON for each device. But maybe I am wrong?

**Comment by bluemoehre** [comment]
bump
