### ISSUE TITLE
TRADFRI on/off switch

### ISSUE THREAD

**Issue by kikher** [dresden-elektronik/deconz-rest-plugin#7323]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

TRADFRI On/Off Switch

### Manufacturer

IKEA of Sweden

### Model identifier

 TRADFRI on/off switch

### Device type to add

Remote

### Node info

<img width="585" alt="Captura de pantalla 2023-10-28 a las 13 22 16" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/75734843/fa29cc73-b990-48c2-bb71-876d85df3ffa">
<img width="582" alt="Captura de pantalla 2023-10-28 a las 13 22 27" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/75734843/761f9257-cf50-42a9-b460-4f6efbf30f12">

### Endpoints and clusters

<img width="297" alt="Captura de pantalla 2023-10-28 a las 13 35 12" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/75734843/03d38936-6a0f-48f0-bbc0-0355449bdc14">

### Basic

<img width="1016" alt="Captura de pantalla 2023-10-28 a las 13 26 45" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/75734843/de0a1273-2485-479d-b01c-4130aa2739e9">
<img width="1021" alt="Captura de pantalla 2023-10-28 a las 13 26 58" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/75734843/c7036427-921e-4f52-9158-6a79b9dced7d">

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7237
