### ISSUE TITLE
Support for LYWSD03MMC Xiaomi Sensor

### ISSUE THREAD

**Issue by vdiogo** [dresden-elektronik/deconz-rest-plugin#7327]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

LYWSD03MMC

### Manufacturer

Xiaomi

### Model identifier

LYWSD03MMC

### Device type to add

Sensor

### Node info

<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/201bb4f5-0900-4d6e-908b-e6038b93c700">

### Endpoints and clusters

<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/1c6b7abb-53a5-4b19-8783-dc1123c414f9">
<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/a108a415-2589-4ff6-b209-4a777fcc78de">
<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/14ab97e3-029a-413f-b07e-9103f783bc8e">
<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/5cf8bc75-e944-4593-8aa6-7f5c934747c5">

### Basic

<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/aceb1f94-7e9c-44fb-be61-f8b2232a0965">

### Power Configuration
<img width="256" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/fc8d545a-9f24-437f-a588-3ea9d57bbe02">

**Comment by olleelfsborg** [comment]
Anything new on this?

**Comment by molnarti** [comment]
how have you been able to pair the device to show up its data in deconz? mine is not pairing, no matter what i do (yes, i did flash it with the ZB firmware)

**Comment by vdiogo** [comment]
> how have you been able to pair the device to show up its data in deconz? mine is not pairing, no matter what i do (yes, i did flash it with the ZB firmware)

I opened the Phoscon app, added a sensor and pressed the button in the device, and waited for it to show in the deconz network. Of course it never added the sensor in Phoscon, was just to force the conbee stick to scan for new devices

**Comment by Mimiix** [comment]
> how have you been able to pair the device to show up its data in deconz? mine is not pairing, no matter what i do (yes, i did flash it with the ZB firmware)

It won't show in phoscon. Just deconz.

**Comment by molnarti** [comment]
OK, so mine is paired too (was expecting to see something in phoscon and did not check deconz). Hope this gets supported soon, would be a game changer in my smart home setup

**Comment by ostgardh** [comment]
I have add LYWSD03MMC in DDF editor, and now I can se LYWSD03MMC in phoscon

**Comment by ostgardh** [comment]
But I get no update from LYWSD03MMC.
Anyone know how to add temp report when the temperature changes?

**Comment by DrBlokmeister** [comment]
> I have add LYWSD03MMC in DDF editor, and now I can se LYWSD03MMC in phoscon. similarly as in this video.. https://www.youtube.com/watch?v=rgTQpOVg8w0

Could you share the .json file? As far as I understand, I can copy/paste that in my DDF editor, right?

**Comment by neutrino85** [comment]
Hello,
Here's mine :
`{
  "schema": "devcap1.schema.json",
  "manufacturername": "Xiaomi",
  "modelid": "LYWSD03MMC",
  "product": "LYWSD03MMC",
  "sleeper": true,
  "status": "Silver",
  "path": "/devices/lywsd03mmc.json",
  "subdevices": [
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "refresh.interval": 3600,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "awake": true,
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "refresh.interval": 7255,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl"
          },
          "default": 0
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true,
          "refresh.interval": 60,
          "default": 0
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001"
    }
  ]
}`

**Comment by ostgardh** [comment]
This is my.
But I still have problem that is not report new temp.
I have to press update in deconz ..

File
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Xiaomi",
  "modelid": "LYWSD03MMC",
  "product": "LYWSD03MMC",
  "sleeper": false,
  "status": "Silver",
  "path": "/devices/lywsd03mmc.json",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "description": "Relative offset to the main measured value.",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "default": 0
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "description": "Relative offset to the main measured value.",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_BATTERY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0001"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/battery",
          "description": "The current device battery level in range
0&ndash;100&nbsp;%.",
          "refresh.interval": 3600
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}
```

Den mån 20 nov. 2023 kl 21:15 skrev neutrino85 ***@***.***>:

**Comment by btk999** [comment]
I also cant get it work, the device is shown in deCONZ but not in Phoscon or Rest API. Neither with my own DDF nor the DDFs posted above. Also after every deCONZ restart i have to reload the DDF...

DDF-God @Smanar  can you help us out here? :-)

**Comment by Smanar** [comment]
Hello, can you share the node picture ? the one with all cluster and endpoint displayed ? (to be sure all is working on endpoint 0x01.
Else on your DDF you have set the bind, but forget to set the reporting

```
{
    "schema": "devcap1.schema.json",
    "manufacturername": "Xiaomi",
    "modelid": "LYWSD03MMC",
    "vendor": "Xiaomi",
    "product": "LYWSD03MMC",
    "sleeper": false,
    "status": "Gold",
    "subdevices": [
        {
            "type": "$TYPE_HUMIDITY_SENSOR",
            "restapi": "/sensors",
            "uuid": [
                "$address.ext",
                "0x01",
                "0x0405"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion"
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/battery",
                    "refresh.interval": 3600,
                    "read": {
                        "at": "0x0021",
                        "cl": "0x0001",
                        "ep": 1,
                        "fn": "zcl"
                    },
                    "parse": {
                        "at": "0x0021",
                        "cl": "0x0001",
                        "ep": 1,
                        "eval": "Item.val = Attr.val / 2",
                        "fn": "zcl"
                    },
                    "default": 0
                },
                {
                    "name": "config/offset",
                    "default": 0
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "state/humidity"
                },
                {
                    "name": "state/lastupdated"
                }
            ]
        },
        {
            "type": "$TYPE_TEMPERATURE_SENSOR",
            "restapi": "/sensors",
            "uuid": [
                "$address.ext",
                "0x01",
                "0x0402"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion"
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/battery",
                    "refresh.interval": 7255,
                    "read": {
                        "at": "0x0021",
                        "cl": "0x0001",
                        "ep": 1,
                        "fn": "zcl"
                    },
                    "parse": {
                        "at": "0x0021",
                        "cl": "0x0001",
                        "ep": 1,
                        "eval": "Item.val = Attr.val / 2",
                        "fn": "zcl"
                    },
                    "default": 0
                },
                {
                    "name": "config/offset",
                    "default": 0
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "state/lastupdated"
                },
                {
                    "name": "state/temperature"
                }
            ]
        }
    ],
    "bindings": [
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0001",
            "report": [
                {
                    "at": "0x0021",
                    "dt": "0x20",
                    "min": 3200,
                    "max": 3600,
                    "change": "0x00000002"
                }
            ]
        },
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0402",
            "report": [
                {
                    "at": "0x0000",
                    "dt": "0x29",
                    "min": 10,
                    "max": 300,
                    "change": "0x0000000A"
                }
            ]
        },
        {
            "bind": "unicast",
            "src.ep": 1,
            "cl": "0x0405",
            "report": [
                {
                    "at": "0x0000",
                    "dt": "0x21",
                    "min": 10,
                    "max": 300,
                    "change": "0x00000032"
                }
            ]
        }
    ]
}
```

**Comment by btk999** [comment]
> Hello, can you share the node picture ? the one with all cluster and endpoint displayed ? (to be sure all is working on endpoint 0x01. Else on your DDF you have set the bind, but forget to set the reporting
> 

Thanks! Seems that your DDF works - the sensor gets updated recently.
Here some screenshots - i hope this is what you asked for..?
![cluster_basic](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/7de960d5-ce2d-42c7-9ffa-12a4db85f7c3)
![nodeinfo](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/3c4774d9-158a-46fc-bf24-43c0f9792276)
![cluster_power](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/7140afba-2c00-40e6-a909-78df4914bfd9)
![cluster identify](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/3dcc9438-7930-4077-9031-f1c8bbd48b9c)
![cluster_temp](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/d206aba5-5dda-4502-a1f8-934019e7816a)
![cluster_humidity](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/5592d13e-08ef-4cb8-9c76-fb8f644e804c)

**Comment by Smanar** [comment]
Yep, But if it works, it's fine.
You can make a PR to submit the device ? or do you want I make it ?

**Comment by btk999** [comment]
> Yep, But if it works, it's fine. You can make a PR to submit the device ? or do you want I make it ?

to be honest i dont know how to do it. It would be great if you could do that :)

**Comment by ostgardh** [comment]
But have you get sensor to report when temperature changes?

**Comment by btk999** [comment]
> But have you get sensor to report when temperature changes?

yes, with the DDF from @Smanar this works.

**Comment by ostgardh** [comment]
Ok. I have to test your ddf 

Thanks

**Comment by GiacomoFilzi** [comment]
Looking very much forward to this release -awesome!

**Comment by molnarti** [comment]
i can't make the DDF "stick". I click on the entity, select edit DDF, load the saved json file - it seems everything went ok. I click on save, then hot reload, but nothing changes, the device is not visible in Phoscon. After restarting phoscon/deconz the DDF is gone and the node is empty again

**Comment by Smanar** [comment]
@molnarti what is your OS ? You areunder docker ?

PR done here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7373

**Comment by molnarti** [comment]
> @molnarti what is your OS ? You are under docker ?
 yes, docker. i have placed the DDF in a bind mount, and it can load without apparent issues, but seems its not applied

**Comment by Smanar** [comment]
The official deconz docker or the HA one ?
For the official one, DDF need to be in `opt/deCONZ/devices/`. Are you sure about your model, DDF are used according modelID+ManufactureName.

It's a custom device, you can have different one, actually the DDf check for

```
manufacturername : Xiaomi
modelid : LYWSD03MMC
```

**Comment by molnarti** [comment]
yes, that is the location where my DDF is placed. 

how can i confirm my device is really the same? are there other Xiaomi BT sensors that can be flashed to zigbee?
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/25829862/1ecefe46-7871-4cf2-959c-a2cbc75a2136)

**Comment by btk999** [comment]
@molnarti  did you try to set deCONZ to Hybrid Mode? 
![2023_11_25_11_09_20_Homeserver_server_RealVNC_Viewer](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/20415739/ed4ee6b0-7ed4-43f3-9083-5e9efe464a06)

**Comment by Smanar** [comment]
>how can i confirm my device is really the same? are there other Xiaomi BT sensors that can be flashed to zigbee?

The device is lazy, so you need to awake it when asking attribute.
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-read-Clusters

Model id and manufacture Name are in the cluster 0x0000 "Basic"

**Comment by kszabi777** [comment]
Thanks for sharing this, lifesaver.

Could you please explain to me what are the reporting values mean ? (at,dt,min,max,change) 
With the current settings how often the sensor reports the actueal temp/humidity ?

**Comment by Smanar** [comment]
yep.

```
                {
                    "at": "0x0000",
                    "dt": "0x21",
                    "min": 10,
                    "max": 300,
                    "change": "0x00000032"
                }
```

According thoses setting you need to have a report at least every 300s or if the humidity increase/decrease 0.5°% (0x32 = 50, humidity is 4980 on your capture so 49.80 %)
