### ISSUE TITLE
Unable to pair IKEA Trådfri Motion

### ISSUE THREAD

**Issue by eiaro** [dresden-elektronik/deconz-rest-plugin#733]
On the Raspbee I have had these working for a few months using a image from April I think. Because my HA plugin needed the deConz to be updated I flashed the current image onto my card and started setting up lights and sensors again. But for some reason the Motion sensors won't pair.

I had a USB deConz laying around so I plugged that into my PC and updated it to the same FW version. Not able to get the same web version though. No problem pairing the IKEA Motion to this controller.

I have these in every room and most of my system rely on those working. Need a fix or WIFE will be angry. :)

RaspBee: (not working)
Version 2.05.34 / 8/8/2018
Firmware 261F0500

USB: (working)
Version 2.05.20 / 4/8/2018
Firmware 261F0500

**Comment by manup** [comment]
You can  try to force it to pair to the RaspBee first by power off the lights while pairing, it might help in some cases.

**Comment by eiaro** [comment]
I appreciate the suggestion, but it isn't practical. Code is broken and should be fixed.

**Comment by manup** [comment]
The problem might not be at the gateway side but a link in between, for example we have seen several issues under some conditions with IKEA bulbs and battery powered devices. If this is the problem here we can't just fix it since it is bulb firmware related. That's why I suggested to check if the above works, if it doesn't we can dig deeper to check if there is indeed a problem in the gateway firmware.

**Comment by eiaro** [comment]
> How do you conclude that the code is broken?
Occam's razor. 

It would be better to downgrade the RaspBee then, as this would fix my issue. Unfortunately I have no idea on how to do it.

**Comment by eiaro** [comment]
I opened the UI on the RaspBee and [this](https://i.imgur.com/cZ0TO0W.png) is how it looks after trying to add 3 different motion sensors. Notice the last "circle" is missing on all of them, and neither is in the web UI.

Same result on .20 and .34.

**Comment by manup** [comment]
I did some tests with my IKEA motion sensor today to join it from the Phoscon App > Sensors > Add IKEA motion sensor.

Testet various start conditions:
* deCONZ version 2.05.34/35 firmware 0x261F0500
* fresh database
* sensor known in the database

All worked fine and the sensor was discovered after a few seconds. I honestly don't know why it doesn't work on you setup.

You may bring the RaspBee ZigBee network channel to the same channel as your ConBee is. This can be done in the *Phoscon App > Menu > Settings > Gateway > Advanced*.

**Comment by eiaro** [comment]
When I came home from work I tried to pair the three sensors I had on my desk. Did a quick test and I got one of them to pair. As you see on my screen shot it seems the sensors are in fact paired as they get a NWK#, but not fully identified as they have no manufacturer. I am sure if there was a heal function, this could be mitigated.

Later this weekend I replaced the original RPi in my Raspbee with a RPi 3+. Normal Rasberry install then added a docker container for deCONZ. I copied the DB from my old install into the new setup. Implementing all motion sensors went like a charm and I had absolutely no issues getting the sensors in, even from such a long distance they would have to be meshed through lamps.

It is all running now, but still I think there is issues around how detection is done. The biggest practical change I did was adding more CPU.

**Comment by udoewich** [comment]
I'm having the same issue with an IKEA wireless remote: when I have the Conbee connected to my Windows laptop running deCONZ .20 I can pair it just fine, but when I return the Conbee to my ODroid C2 with deCONZ .35 it just does not get found: four presses of the pair button makes the remote flash the red LED, but Phoscon does not find it.

I dont' know if it is relevant, but the original pairing of the remote was done with deCONZ .20 on my Windows laptop.

Is something of the paring information stored in the Conbee itself?  If so, is there a way to make the Conbee "forget" about the remote?

**Comment by manup** [comment]
>Is something of the paring information stored in the Conbee itself? If so, is there a way to make the Conbee "forget" about the remote?

ConBee and RaspBee don't store any device specific data in NVRAM other than basic ZigBee network parameters like channel and security key. So after a powercycle  everything  should be clean. 

However the files zll.db and session.default can hold data about devices. Currently the session.default is going to be replaced with a pure zll.db database solution to prevent any inconsistencies. It might be a problem here so you may try to backup and then delete session.default (not zll.db) to get a cleaner setup, but be aware that gui node positions will be lost and you need to reorder them.

**Comment by udoewich** [comment]
I managed to get the remote working in .35 by first setting everything up on my Windows laptop under .20 and then copying the session.default and zll.db files to the ODroid-C2.  Thanks for putting me on the right track!

BTW: the new button editor works great already!

Now if there was just some way of getting-rid of or hiding the "helper" groups that show up in HA or the Hue app, everything would be perfect. ;)
