### ISSUE TITLE
Device Request: SONOFF TRVZB Thermostat

### ISSUE THREAD

**Issue by fox34** [dresden-elektronik/deconz-rest-plugin#7334]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

TRVZB

### Manufacturer

SONOFF

### Model identifier

TRVZB

### Device type to add

Thermostat

### Node info

![Node Info Panel](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/99484c82-36d3-4478-9658-bd9111d3f76d)

### Endpoints and clusters

![Endpoints](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/9d3442fc-2f23-447a-a594-b62698b6d752)

### Basic

![Basic Cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/95240373-d48c-4f47-9fb0-b98f57b3147e)

### Power Configuration
![Power Configuration Cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/a0581b92-702b-4947-b5bc-f43143fc0ef8)

### On/Off
![OnOff 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/bff688dc-80fb-438d-94a6-50511da9b805)
![OnOff 2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/5e6476c7-bc28-4882-9321-6313ee6b7794)

### Thermostat
![Thermostat Cluster 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/a167a3f9-7ab8-4796-9bb9-e3990fdb5117)
![Thermostat Cluster 2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/e50a106e-e667-4c38-907a-46315e3059d6)
![Thermostat Cluster 3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/c4ac41d1-481b-4aaa-b5cb-e0983516f78b)
![Thermostat Cluster 4](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/b5df4a6d-8a3a-47ce-91a0-5f3a4510fa05)
![Thermostat Cluster 5](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/8ddd0804-2fcb-443c-b360-40b2b0be4bdf)
![Thermostat Cluster 6](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/18050078/659e9130-9bb4-44b8-ad15-9ff5374659b8)

**Comment by Smanar** [comment]
Hello, here you have a defaut DDF for thermostat

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "TRVZB",
  "vendor": "SONOFF",
  "product": "TRVZB Thermostat",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0201"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0301",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0201"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/heatsetpoint",
          "default": 0
        },
        {
          "name": "config/mode"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "state/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0201",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 30,
          "max": 360,
          "change": "0x0000000A"
        }
      ]
    }
  ]
}
```

But your device use too the on/off cluster, it have something special ?

**Comment by fox34** [comment]
Thank you very much. Now the Thermostat does show up in the Phoscon sensors list and in the REST-API after re-pairing. Controlling the temperature and on/off state works. The readonly OnOff state in the On/Off cluster apparently represents whether a temperature is selected or the thermostat is set to "OFF" (antifreeze).

**Comment by Smanar** [comment]
>The readonly OnOff state in the On/Off cluster apparently represents whether a temperature is selected or the thermostat is set to "OFF" (antifreeze).

Do you need it ?
It seem using state/on for thermostat cause issue. The config/mode is working ? it have the "off" state too ?

**Comment by fox34** [comment]
> Do you need it ? 

Since OnOff is read-only and mirrored by the Cluster "Thermostat", Attribute 0x001C, System Mode (Auto <-> Off), I don't think it's needed.

> The config/mode is working ? it have the "off" state too ?

config/mode is working, it also has the "off" state. Controlling the thermostat with Homebridge deCONZ generally works as intended (On/Off, reading and setting temperature).

**Comment by Smanar** [comment]
So what is missing ?

**Comment by fox34** [comment]
Nothing, as far as I can tell. Thank you!

**Comment by Smanar** [comment]
If all is working do you want to make the PR or want I make it ? (to add it officialy)

**Comment by fox34** [comment]
Created PR: #7357 
Checks seemingly failing because of other DDFs.

**Comment by Smanar** [comment]
>Checks seemingly failing because of other DDFs.

Yep, don't worry for that, if there is a real problem, a dev will react. Thx for the PR ^^

**Comment by Smanar** [comment]
@fox34 there is somes changes asked in the PR.
