### ISSUE TITLE
Device Request: Tuya micro motion sensor ZY-M100-24G - _TZE204_ijxvkhd0 - TS0601

### ISSUE THREAD

**Issue by tw090** [dresden-elektronik/deconz-rest-plugin#7335]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

ZY-M100 Series Breathing Presence Sensor

### Manufacturer

_TZE204_ijxvkhd0

### Model identifier

TS0601

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/146825760/38b05639-e64a-4f9c-87b4-14362fb0712c)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/146825760/b25d3e93-2f9f-4a28-8a2f-e89b08bebf39)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/146825760/0de13c5b-bf28-482c-9e14-85c8833f208f)

**Comment by tw090** [comment]
How can i support to add the device?

**Comment by tw090** [comment]
IT IS possible to convert/use this json?
https://github.com/Koenkk/zigbee2mqtt/issues/18237

**Comment by BabaIsYou** [comment]
Hi,

Could you try this DDF please : 

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE204_ijxvkhd0",
  "modelid": "TS0601",
  "product": "Tuya Human Presence Detector",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_LIGHT_LEVEL_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0400"
      ],
      "items": [
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "read": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr",
            "script": "tuya_swversion.js"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/dark"
        },
        {
          "name": "config/tholddark"
        },
        {
          "name": "config/tholdoffset"
        },
        {
          "name": "state/daylight"
        },
        {
          "name": "state/lightlevel"
        },
        {
          "name": "state/lux",
          "description": "The current light intensity in Lux (max is 2000)",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 104,
            "script": "../generic/illuminance_cluster/lux_to_lightlevel.js",
            "fn": "tuya"
          },
          "default": 0
        }
      ]
    },
    {
      "type": "$TYPE_PRESENCE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "read": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr",
            "script": "tuya_swversion.js"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/delay",
          "description": "Detection delay : target confirmation delay time in 10th of second (from 0 to 100). Default 0.1s",
          "read": {
            "fn": "none"
          },
          "write": {
            "dpid": 112,
            "dt": "0x2b",
            "eval": "Item.val;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 112,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          },
          "default": 1
        },
        {
          "name": "config/fadingtime",
          "description": "Fading time : target disapperance delay time in second (from 0 to 15000). Default 90s",
          "range": [
            0,
            15000
          ],
          "read": {
            "fn": "none"
          },
          "write": {
            "dpid": 110,
            "dt": "0x2b",
            "eval": "Item.val;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 110,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          },
          "default": 90
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/sensitivity",
          "description": "Presence sensitivity (from 1 to 10). Default 7",
          "range": [
            1,
            10
          ],
          "read": {
            "fn": "none"
          },
          "write": {
            "dpid": 111,
            "dt": "0x2b",
            "eval": "Item.val;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 111,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          },
          "default": 7
        },
        {
          "name": "config/triggerdistance",
          "description": "Far detection sensitivity",
          "read": {
            "fn": "none"
          },
          "write": {
            "dpid": 107,
            "dt": "0x2b",
            "eval": "Far = ['1','2','3','4','5']; Attr.val = Math.max(100,(Far.indexOf(Item.val)+1)*100+50);",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 107,
            "eval": "Item.val = String(Attr.val/100);",
            "fn": "tuya"
          },
          "values": [
            [
              "\"1\"",
              "1,5m"
            ],
            [
              "\"2\"",
              "2,5m"
            ],
            [
              "\"3\"",
              "3,5m"
            ],
            [
              "\"4\"",
              "4,5m"
            ],
            [
              "\"5\"",
              "5,5m"
            ]
          ],
          "default": "1"
        },
        {
          "name": "state/targetdistance",
          "description": "Distance from detected target in cm (from 0 to 1000).",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 109,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          },
          "default": 0
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/presence",
          "read": {
            "fn": "tuya"
          },
          "parse": {
            "dpid": 105,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          },
          "default": false
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0xEF00"
    }
  ]
}
```

**Comment by tw090** [comment]
> Hi,
> 
> Could you try this DDF please ? For lux to be updated into GUI you also need lux_to_lightlevel.js to be but in the right directory, or the DDF to be put directly into tuya subdir of your current DecONZ default DDF folder.
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TZE204_ijxvkhd0",
>   "modelid": "TS0601",
>   "product": "Tuya Human Presence Detector",
>   "sleeper": false,
>   "status": "Gold",
>   "subdevices": [
>     {
>       "type": "$TYPE_LIGHT_LEVEL_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0400"
>       ],
>       "items": [
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion",
>           "read": {
>             "at": "0x0001",
>             "cl": "0x0000",
>             "ep": 1,
>             "fn": "zcl:attr"
>           },
>           "parse": {
>             "at": "0x0001",
>             "cl": "0x0000",
>             "ep": 1,
>             "fn": "zcl:attr",
>             "script": "tuya_swversion.js"
>           }
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "state/lastupdated"
>         },
>         {
>           "name": "state/dark"
>         },
>         {
>           "name": "config/tholddark"
>         },
>         {
>           "name": "config/tholdoffset"
>         },
>         {
>           "name": "state/daylight"
>         },
>         {
>           "name": "state/lightlevel"
>         },
>         {
>           "name": "state/lux",
>           "description": "The current light intensity in Lux (max is 2000)",
>           "read": {
>             "fn": "none"
>           },
>           "parse": {
>             "dpid": 104,
>             "script": "../generic/illuminance_cluster/lux_to_lightlevel.js",
>             "fn": "tuya"
>           },
>           "default": 0
>         }
>       ]
>     },
>     {
>       "type": "$TYPE_PRESENCE_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0xef00"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion",
>           "read": {
>             "at": "0x0001",
>             "cl": "0x0000",
>             "ep": 1,
>             "fn": "zcl:attr"
>           },
>           "parse": {
>             "at": "0x0001",
>             "cl": "0x0000",
>             "ep": 1,
>             "fn": "zcl:attr",
>             "script": "tuya_swversion.js"
>           }
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/delay",
>           "description": "Detection delay : target confirmation delay time in 10th of second (from 0 to 100). Default 0.1s",
>           "read": {
>             "fn": "none"
>           },
>           "write": {
>             "dpid": 112,
>             "dt": "0x2b",
>             "eval": "Item.val;",
>             "fn": "tuya"
>           },
>           "parse": {
>             "dpid": 112,
>             "eval": "Item.val = Attr.val;",
>             "fn": "tuya"
>           },
>           "default": 1
>         },
>         {
>           "name": "config/fadingtime",
>           "description": "Fading time : target disapperance delay time in second (from 0 to 15000). Default 90s",
>           "range": [
>             0,
>             15000
>           ],
>           "read": {
>             "fn": "none"
>           },
>           "write": {
>             "dpid": 110,
>             "dt": "0x2b",
>             "eval": "Item.val;",
>             "fn": "tuya"
>           },
>           "parse": {
>             "dpid": 110,
>             "eval": "Item.val = Attr.val;",
>             "fn": "tuya"
>           },
>           "default": 90
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "config/sensitivity",
>           "description": "Presence sensitivity (from 1 to 10). Default 7",
>           "range": [
>             1,
>             10
>           ],
>           "read": {
>             "fn": "none"
>           },
>           "write": {
>             "dpid": 111,
>             "dt": "0x2b",
>             "eval": "Item.val;",
>             "fn": "tuya"
>           },
>           "parse": {
>             "dpid": 111,
>             "eval": "Item.val = Attr.val;",
>             "fn": "tuya"
>           },
>           "default": 7
>         },
>         {
>           "name": "config/triggerdistance",
>           "description": "Far detection sensitivity",
>           "read": {
>             "fn": "none"
>           },
>           "write": {
>             "dpid": 107,
>             "dt": "0x2b",
>             "eval": "Far = ['1','2','3','4','5']; Attr.val = Math.max(100,(Far.indexOf(Item.val)+1)*100+50);",
>             "fn": "tuya"
>           },
>           "parse": {
>             "dpid": 107,
>             "eval": "Item.val = String(Attr.val/100);",
>             "fn": "tuya"
>           },
>           "values": [
>             [
>               "\"1\"",
>               "1,5m"
>             ],
>             [
>               "\"2\"",
>               "2,5m"
>             ],
>             [
>               "\"3\"",
>               "3,5m"
>             ],
>             [
>               "\"4\"",
>               "4,5m"
>             ],
>             [
>               "\"5\"",
>               "5,5m"
>             ]
>           ],
>           "default": "1"
>         },
>         {
>           "name": "state/targetdistance",
>           "description": "Distance from detected target in cm (from 0 to 1000).",
>           "read": {
>             "fn": "none"
>           },
>           "parse": {
>             "dpid": 109,
>             "eval": "Item.val = Attr.val;",
>             "fn": "tuya"
>           },
>           "default": 0
>         },
>         {
>           "name": "state/lastupdated"
>         },
>         {
>           "name": "state/presence",
>           "read": {
>             "fn": "tuya"
>           },
>           "parse": {
>             "dpid": 105,
>             "eval": "Item.val = Attr.val;",
>             "fn": "tuya"
>           },
>           "default": false
>         }
>       ]
>     }
>   ],
>   "bindings": [
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0xEF00"
>     }
>   ]
> }
> ```

Thank you for the info with lux, now everything works with your DDF!

**Comment by BabaIsYou** [comment]
👍 ready to make a pull request to share it in next release ?

**Comment by tw090** [comment]
> 👍 ready to make a pull request to share it in next release ?

From my side - yes!

**Comment by BabaIsYou** [comment]
> From my side - yes!

Done !
