### ISSUE TITLE
Can't set power on behaviour with SONOFF ZBMINI

### ISSUE THREAD

**Issue by mariomaz87** [dresden-elektronik/deconz-rest-plugin#7343]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I can't set the Power On Behaviour for a SONOFF ZBMINI switch. The 0x8002 attribute is "Off" and it's not writeable.

### Steps to reproduce the behavior

In Deconz GUI, select the Sonoff ZBMini light, go to cluster info of the On/Off cluster and try to modify attribute 0x8002.

### Expected behavior

I expected to change the attribute to On

### Screenshots

![Screenshot from 2023-11-09 14-43-32](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/99350972/623d9d79-5f83-4ebe-8d4b-aa3f290420b8)

### Environment

- Host system: Raspberry Pi 4
- Running method: Raspbian
- Firmware version: 26780700
- deCONZ version (not Home assistant Addon version!): 2.23.02
- Device: ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? External drive and USB SD card reader

**Comment by Mimiix** [comment]
Hi,

This is not a bug. The device simply doesnt seem to support this attribute.

Try 0x4003.
