### ISSUE TITLE
Tradfri LED bulb E14 470 lumen

### ISSUE THREAD

**Issue by MSL-DA** [dresden-elektronik/deconz-rest-plugin#7349]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tradfri LED bulb E14 470 lumen

### Manufacturer

IKEA of Sweden

### Model identifier

TRADFRIbulbE14WSglobeopal470lm

### Device type to add

Light

### Node info

<img width="576" alt="Skærmbillede 2023-11-13 kl  14 15 24" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/2c9f6782-5eac-4d7b-85ef-5bde10c82809">

### Endpoints and clusters

<img width="255" alt="Skærmbillede 2023-11-13 kl  14 21 13" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/a9df3932-5929-4279-87b6-55b511b91c0a">

### Basic

<img width="576" alt="Skærmbillede 2023-11-13 kl  14 16 21" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/9cc46148-0e45-44b6-9de7-0c0e79f8729e">

### On/Off

<img width="667" alt="Skærmbillede 2023-11-13 kl  14 17 16" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/5b8bbde1-5fe9-4410-8bf8-6b6f4d3d13ec">

### Level Control

<img width="667" alt="Skærmbillede 2023-11-13 kl  14 18 09" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/352606f9-3858-4fae-85a1-ea4f3c928bef">

### Color Control

<img width="667" alt="Skærmbillede 2023-11-13 kl  14 18 59" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/8327ad86-a749-49e1-a8d2-24a7d485ed8b">

**Comment by ebaauw** [comment]
What’s the _Image Type_ of the light’s firmware?

**Comment by MSL-DA** [comment]
> What’s the _Image Type_ of the light’s firmware?

Do you mean the firmware version for the light?

**Comment by ebaauw** [comment]
No, the _Image Type_, the identifier for the firmware.  See the OTAU plugin (select the light and press _Query_), or read the attributes of the _OTAU_ cluster (and select another cluster, and re-select _OTAU_ to work around a GUI bug not showing the values after read).

**Comment by MSL-DA** [comment]
> What’s the _Image Type_ of the light’s firmware?

OTAU

<img width="745" alt="Skærmbillede 2023-11-13 kl  18 27 29" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/69ee2793-be19-4d8f-a9a2-7c2e6a027b13">

**Comment by ebaauw** [comment]
Attribute 0x0008, but it doesn't report it here.  Better check the OTAU panel.

**Comment by MSL-DA** [comment]
> Attribute 0x0008, but it doesn't report it here. Better check the OTAU panel.

You need to be more specific in your requests. I do not understand?

**Comment by ebaauw** [comment]
See https://phoscon.de/en/support#ota-update-osram-devices

**Comment by MSL-DA** [comment]
Nothing happens. Note that Homebridge/Homebridge deCONZ is on LAN 192.168.20.20 and deCONZ is published via docker on 192.168.10.4

**Comment by MSL-DA** [comment]
Is this what you are looking for?

<img width="740" alt="Skærmbillede 2023-11-15 kl  21 06 02" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/82e0c960-6a46-438c-aae3-986042d62538">

**Comment by ebaauw** [comment]
Yes, thanks

**Comment by MSL-DA** [comment]
I can add model number LED2002G5 and product code 504.867.87

**Comment by MSL-DA** [comment]
^^

**Comment by MSL-DA** [comment]
^^
