### ISSUE TITLE
Tradfri LED bulb GU10 345 lumen

### ISSUE THREAD

**Issue by MSL-DA** [dresden-elektronik/deconz-rest-plugin#7350]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tradfri LED bulb GU10 345 lumen

### Manufacturer

IKEA of Sweden 

### Model identifier

TRADFRIbulbGU10WS345lm

### Device type to add

Light

### Node info

<img width="681" alt="Skærmbillede 2023-11-13 kl  14 31 10" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/c121c223-98a4-449d-8858-7550fcf29991">

### Endpoints and clusters

<img width="284" alt="Skærmbillede 2023-11-13 kl  14 31 51" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/ae393c36-4b07-4214-8bed-6e8ae689c717">

### Basic

<img width="668" alt="Skærmbillede 2023-11-13 kl  14 32 26" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/d90fbbb5-4bf8-490b-8eb1-17e99b9450dc">

### On/Off

<img width="668" alt="Skærmbillede 2023-11-13 kl  14 33 13" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/564fc42d-8d69-40be-919c-e99262b113ba">

### Level Control

<img width="668" alt="Skærmbillede 2023-11-13 kl  14 33 53" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/4b1e3efa-282c-4220-a17e-fa985eda99e2">

### Color Control

<img width="668" alt="Skærmbillede 2023-11-13 kl  14 34 34" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/cac29720-26b1-49bc-84a0-3d2cde6c6061">

**Comment by ebaauw** [comment]
What’s the _Image Type_ of the light’s firmware?

**Comment by MSL-DA** [comment]
<img width="740" alt="Skærmbillede 2023-11-15 kl  23 52 49" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/50385a50-db10-4ffe-83d4-c354b34f96d9">

**Comment by MSL-DA** [comment]
^^

**Comment by djsmix** [comment]
is this still a problem?
