### ISSUE TITLE
IKEA Gunnarp LED Ceiling

### ISSUE THREAD

**Issue by MSL-DA** [dresden-elektronik/deconz-rest-plugin#7351]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Gunnarp LED Ceiling

### Manufacturer

IKEA of Sweden

### Model identifier

GUNNARP panel round

### Device type to add

Light

### Node info

<img width="691" alt="Skærmbillede 2023-11-13 kl  14 40 29" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/7f13a523-6b8f-4dbd-82a4-5e2448967f01">

### Endpoints and clusters

<img width="288" alt="Skærmbillede 2023-11-13 kl  14 40 57" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/9643960c-470b-4c43-a9ac-d6a835c154f6">

### Basic

<img width="675" alt="Skærmbillede 2023-11-13 kl  14 41 26" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/95241114-0920-471d-a65d-7584a088c199">

### On/Off

<img width="675" alt="Skærmbillede 2023-11-13 kl  14 43 17" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/b2626562-2ff1-44d0-b1e0-df0b1cd0db62">

### Level Control

<img width="675" alt="Skærmbillede 2023-11-13 kl  14 43 51" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/52d896a6-cfdc-4a96-98f9-2f2fc371a32c">

### Color Control

<img width="675" alt="Skærmbillede 2023-11-13 kl  14 44 24" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/566934a6-c9d8-48e8-b721-5ba9838b0dc3">

**Comment by ebaauw** [comment]
What’s the _Image Type_ of the light’s firmware?

**Comment by MSL-DA** [comment]
OTAU

<img width="745" alt="Skærmbillede 2023-11-13 kl  18 30 26" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/2f32948a-63ea-4d96-8ace-00ef14678e72">

**Comment by MSL-DA** [comment]
<img width="740" alt="Skærmbillede 2023-11-15 kl  23 51 35" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/d77e93d0-2699-47e9-9b12-f03c7856814a">

**Comment by MSL-DA** [comment]
^^

**Comment by MSL-DA** [comment]
^^
