### ISSUE TITLE
Hue White Ambiance Candle E14

### ISSUE THREAD

**Issue by MSL-DA** [dresden-elektronik/deconz-rest-plugin#7352]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Hue White Ambiance Candle E14

### Manufacturer

Philips

### Model identifier

LTW012

### Device type to add

Light

### Node info

<img width="687" alt="Skærmbillede 2023-11-13 kl  14 53 32" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/53a1e6a1-fedc-4aa1-97b3-7146bc3905ed">

### Endpoints and clusters

<img width="277" alt="Skærmbillede 2023-11-13 kl  14 54 11" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/1089a406-b182-4649-a078-b3ef1f4a0b4a">

### Basic

<img width="1088" alt="Skærmbillede 2023-11-13 kl  14 55 28" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/7675bbca-21e1-4935-bdd9-bea7b3e1561a">

### On/Off

<img width="665" alt="Skærmbillede 2023-11-13 kl  14 56 41" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/d8a6982f-03fd-4005-b58a-c871987d6537">

### Level Control

<img width="836" alt="Skærmbillede 2023-11-13 kl  14 58 11" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/aba6f5bd-3350-4a2d-a608-d2cf8dc7d4b6">

### Color Control

<img width="836" alt="Skærmbillede 2023-11-13 kl  14 59 52" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/ddf581c3-b005-4c37-997e-357379c671e4">

**Comment by ebaauw** [comment]
What’s the _Image Type_ of the light’s firmware?

**Comment by MSL-DA** [comment]
OTAU

<img width="745" alt="Skærmbillede 2023-11-13 kl  18 31 25" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/6fa5ccd8-caef-432b-91fd-c4fb298093fb">

**Comment by MSL-DA** [comment]
<img width="740" alt="Skærmbillede 2023-11-15 kl  23 50 39" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/61ac05f7-f8f8-4cb9-b6f2-ea2e681c464f">

**Comment by bluemoehre** [comment]
Got such a device here. Wanted to return it due to coil whine. I can generate a DDF via deCONZ, so you don't have to type all the config. Will this help, @ebaauw  ?

**Comment by ebaauw** [comment]
I need to check this weekend, but we probably already have a DDF for this firmware type.  In that case, we just need to add the _Model Identifier_ to that DDF.

**Comment by ebaauw** [comment]
Hm. this is an old ZLL light.  Existing white ambiant DDF is for ZB3 lights.   I think I might have one of those lying around somewhere.  See if I can find that this weekend.

**Comment by MSL-DA** [comment]
If time is short, I will look into it myself. Just say so.

**Comment by ebaauw** [comment]
The DDF is relatively simple, copying light_zll_gamut_C and removing out the colour stuff.  I run into one issue though: the light supports the `candle` effect (at least with the latest firmware 1.108.5), but, obviously, not `colorloop`.  Somehow that causes the API not to show `cap/color/effects`, and accept `colorloop` as value for `state/effect`, resulting in API error 901: Internal error, 951 (since the light doesn't support _Color Loop Set_).  Also the API doesn't understand to cancel the `candle` effect when setting `state/effect` to `none`.

I'm increasingly regretting my decision to expose special effects under `state/effect`, combined with `colorloop`.
