### ISSUE TITLE
Hue White Ambiance E27

### ISSUE THREAD

**Issue by MSL-DA** [dresden-elektronik/deconz-rest-plugin#7353]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Hue White Ambiance E27

### Manufacturer

Philips

### Model identifier

LTW001

### Device type to add

Light

### Node info

<img width="630" alt="Skærmbillede 2023-11-13 kl  18 37 06" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/8f4f1b7f-83ac-4882-bd8f-479f181e1952">

### Endpoints and clusters

<img width="212" alt="Skærmbillede 2023-11-13 kl  18 37 36" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/f6d5670c-de7e-4744-a01f-2c110ae9dbbc">

### Basic

<img width="734" alt="Skærmbillede 2023-11-13 kl  18 39 56" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/8241aec2-110a-4504-a992-9bfd66375843">

### On/Off

<img width="734" alt="Skærmbillede 2023-11-13 kl  18 40 37" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/b17d637d-5865-4c71-b85a-19e3750ad4e4">

### Level Control

<img width="734" alt="Skærmbillede 2023-11-13 kl  18 41 16" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/55e21f9d-dfb1-488e-8b3b-ea1639c728db">

### Color Control

<img width="734" alt="Skærmbillede 2023-11-13 kl  18 41 56" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/772adb56-b012-4f7b-8933-9330148243be">

### OTAU

<img width="734" alt="Skærmbillede 2023-11-13 kl  18 42 57" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/57627e6f-96ff-4dcb-8110-96f645bc57d5">

**Comment by MSL-DA** [comment]
<img width="740" alt="Skærmbillede 2023-11-15 kl  23 49 38" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/134940586/5c1a30d9-2671-447f-bdec-0cbc15857b1f">

**Comment by ebaauw** [comment]
These are old ZLL lights, that somehow share the firmware image with the gamut-B extended color lights.  I'm guessing/hoping they behave the same as the 0x010C.  I need to check if I have a color temperature light with this firmware build.

**Comment by ebaauw** [comment]
Bump.

I'll try and have a look this weekend.

**Comment by MSL-DA** [comment]
If time is short, I will look into it myself. Just say so.

**Comment by ebaauw** [comment]
I don't think I have any LTW001.  I found the E14 LTW012 from #7352 and an 800lm E27 LTW010, both with image type 0x010C.

Could you please list the Hue Effects cluster?

**Comment by MSL-DA** [comment]
Do you still need the Hue Effects cluster?
