### ISSUE TITLE
TCI MAXI JOLLY ZLL

### ISSUE THREAD

**Issue by rdrzewinski** [dresden-elektronik/deconz-rest-plugin#736]
How can I add TCI MAXI JOLLY ZLL driver to deCONZ?
In the WebApp/Restet Devices via Touchlink my driver is discovered and blinking,
When I search new lights in Phoscon App, nothing is found.

**Comment by manup** [comment]
Is it shown in deCONZ GUI?

**Comment by rdrzewinski** [comment]
It is shown in WebApi:
![screen](https://user-images.githubusercontent.com/40599735/44327065-e70b6e80-a45d-11e8-80ad-32e3c4ec22cc.png)
The position marked in red is TCI Maxi Jolly ZLL driver.
I do not know how to shown it in deCONZ GUI.

**Comment by rdrzewinski** [comment]
Today, TCI driver is discovered and added to deCONZ. All works perfectly. I don't know how.
