### ISSUE TITLE
Tuya ZigBee Button Smart Scene Switch

### ISSUE THREAD

**Issue by hakano14** [dresden-elektronik/deconz-rest-plugin#7364]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Smart Button

### Manufacturer

_TZ3000_qgwcxxws

### Model identifier

TS0041

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/30826138/af6c0025-0885-4cd4-ac8b-91ff5fefd792)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/30826138/2dc726be-c1ed-4b2f-b40d-4827e3e09824)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/30826138/2def23f6-51cd-427a-a893-e7e166f03f6b)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/30826138/5aa20644-bed6-4d88-a4dc-0cda89d988d4)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/30826138/0ef127ac-f184-4651-a393-0d6cd65f535e)

Sold here:
https://www.aliexpress.com/item/1005005363529624.html

**Comment by hakano14** [comment]
This looks very similor as #7205 - maybe this could be solved in the same mannar?!

**Comment by hakano14** [comment]
I think this can be fixed by adding
_TZ3000_qgwcxxws to 
_TZ3000_TS0041_1gang_bat.json and button_maps.json.

Someone who can make this changes?

**Comment by retrography** [comment]
@hakano14 Can you test this on your side?

**Comment by hakano14** [comment]
It works in Api and Phoscon on my side!
But no predefined events in HA (but event works )
1002 - click
1004 - double click

**Comment by Mimiix** [comment]
> It works in Api and Phoscon on my side! But no predefined events in HA (but event works ) 1002 - click 1004 - double click

That's because HA needs to add support. Events are fine

**Comment by hakano14** [comment]
Hi!

I'm sorry to say there was a typo error in the new version (2.25.2)...

The manufacturername should be **_TZ3000_qgwcxxws** not TZ3000_qgwcxxws as in devices/tuya/_TZ3000_TS0041_1gang_bat.json

In button_maps.json it is correct.

Hope you can fix this for the next release.

**Comment by Mimiix** [comment]
Re opened on request.

**Comment by retrography** [comment]
This has been resolved and merged.
________________________________

**Comment by Mimiix** [comment]
Great thanks !

**Comment by 7R0J4Ner** [comment]
Hello

Could you add this version of that Switch too?
_TZ3000_axpdxqgu 
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45797323/3e07979c-6977-420a-88fc-ddb88ad7e38b)

**Comment by retrography** [comment]
Submitted as a part of #7633
