### ISSUE TITLE
LIDL SILVERCREST Smart Plug

### ISSUE THREAD

**Issue by Splash005** [dresden-elektronik/deconz-rest-plugin#7367]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Livarno / Silvercrest / Lidl Smart Plug

### Manufacturer

_TZ3000_kdi2o9m6

### Model identifier

TS011F

### Device type to add

Switch

### Node info

Actually I was sure that this Switched used to be supported. It is a smart switch from the german Lidl.

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44831183/0c6cc558-70e6-4a73-86c7-63cb79317464)

### Endpoints and clusters

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44831183/158fd998-215d-474c-9519-38646e331a73)

### Basic

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44831183/755ef49d-d06b-429c-987c-59d8f8319a73)

### On/Off
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44831183/0e2937ce-ce71-40b6-8f97-6c6e6af9e954)

**Comment by LeoeLeoeL** [comment]
In my case, it's supported but Deconz reports a double smartplug.
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/854f31a1-cb45-436b-a8a9-bd1bfd28bfce)

**Comment by BabaIsYou** [comment]
"Basic" smart switch are usually supported by legacy code. Is there something special with this one that need a specific DDF to be used?

**Comment by Splash005** [comment]
Maybe if that is helping. Last year when I remember that I had it working I was running it on a raspberry pi and now it runs on a synology nas docker.

**Comment by BabaIsYou** [comment]
May be this kind of DDF should do the trick : 
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_kdi2o9m6",
  "modelid": "TS011F",
  "product": "Another Smart socket plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 5,
          "max": 300
        }
      ]
    }
  ]
}
```
