### ISSUE TITLE
HUE Lightstrip Plus V4 on PhosconAPP 2.24.2 cannot integrate into the system

### ISSUE THREAD

**Issue by jabba-76** [dresden-elektronik/deconz-rest-plugin#7368]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hello, I have the Phosconn APP version 2.24.2 version on it and I cannot integrate the HUE LED Lightstrips Plus V4 into the system. The strip is definitely in integration mode and the search for new lamps does not yield any results. What can I do? They are in the compatibility list
Thanks

### Steps to reproduce the behavior

permanent state

### Expected behavior

ok

### Environment

- Host system: PC
- Running method: Ubuntu
- Firmware version: (26780700)
- deCONZ version : (2.24.2)
- Device: ConBee II
- Do you use an USB extension cable: yes 

EDIT: 

It looks like you can't learn anything new anymore. I had an IKEA motion sensor in it, deleted it and wanted to retrain it. The system no longer recognizes it even though it worked before?

**Comment by Mimiix** [comment]
Hi,

As this is not an issue as described in #5113 I am closing this issue.

Please open an topic on the forums.

Kind regards,
Dennis
