### ISSUE TITLE
REST API to set multiple light states at once?

### ISSUE THREAD

**Issue by FezVrasta** [dresden-elektronik/deconz-rest-plugin#737]
Is there any API endpoint to set multiple light states with a single call?

**Comment by ebaauw** [comment]
Recall a scene, http://dresden-elektronik.github.io/deconz-rest-doc/scenes/.

**Comment by FezVrasta** [comment]
Thanks, but a scene needs to first be defined, I'd need a way to change of a lot of different lights in a dynamic way.

**Comment by ebaauw** [comment]
There's no way to do that in the ZigBee standard.

Philips hacked together something specific for Hue Entertainment, see https://developers.meethue.com/entertainment-blog, but that does require support in the light firmware, so it only works with Philips lights.  Not likely to be supported by deCONZ, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/167.

**Comment by FezVrasta** [comment]
I see, I just wonder why projects like DIYHue have problems turning on/off a lot of bulbs all together while Hue and DeCONZ bridges can do that just fine 😓

Maybe it's a problem of DIYHue
