### ISSUE TITLE
Blind with v2.24.2

### ISSUE THREAD

**Issue by MSL-DA** [dresden-elektronik/deconz-rest-plugin#7378]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Unable to add IKEA blinds

### Steps to reproduce the behavior

Add new blind

### Expected behavior

No blind found/ works with deconz:2.23.02

### Environment

Ubuntu/rpi
docker
gw-version: 2.24.2

### Additional context

works with deconz:2.23.02

**Comment by Mimiix** [comment]
Closing this as it's a possible duplicate and the template was not filled properly.

**Comment by MSL-DA** [comment]
> Closing this as it's a possible duplicate and the template was not filled properly.

Why are you closing it? I don't see any error message like this and I have filled out the template as prescribed

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7374

**Comment by MSL-DA** [comment]
> #7374

Thank you ☺️
