### ISSUE TITLE
Yet another Tuya Smart Button TS004F _TZ3000_abrsvsou

### ISSUE THREAD

**Issue by x0li** [dresden-elektronik/deconz-rest-plugin#7379]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tuya Smart Scene Button

### Manufacturer

_TZ3000_abrsvsou

### Model identifier

TS004F

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/92057167/ab2f2758-2c52-470e-be97-8e1edf1e61bc)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/92057167/7a7c2524-6d0e-48d4-887f-932add1d7604)

### Basic

![Captura de pantalla de 2023-11-24 20-27-17](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/92057167/45f7d0c9-dfb0-4971-991c-e873d2f5a56c)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/92057167/1debcb8b-1ebf-4b1b-aaaa-1d635e0a9cb2)

### Device picture
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/92057167/0df012eb-0fc6-487c-9501-6d977f87234f)

**Comment by BabaIsYou** [comment]
Can you please stick to the template and give screenshots to all relevant clusters after clicking Read button ?
Thanks

**Comment by x0li** [comment]
Sorry Babals, I thought I did.
Unfortunately, I'm not able to provide them anymore, as I moved all my Zigbee network to ZHA.
If it can't be fixed with the provided info, please feel free to close the issue.

Thanks for your efforts!
