### ISSUE TITLE
Deconz gui icon/shortcut missing on 2.24.2

### ISSUE THREAD

**Issue by phuongpham** [dresden-elektronik/deconz-rest-plugin#7380]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Shortcut/icon is missing from the menu on Rasbian after upgrading to deconz 2.24.2
<img width="436" alt="Skjermbilde 2023-11-25 kl  17 30 45" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/2634344/76a3a0c4-cd0d-40c5-83f6-3b11eedf234d">

On latest version (2.24.2) I have to start deconz-gui thru terminal. (sudo service deconz-gui start)

Works fine again if I downgrade to 2.23.01

### Steps to reproduce the behavior

1. Click on Rasbian menu
2. Go to development
3. The icon/shortcut is missing

### Expected behavior

The icon/shortcut should be visible in the menu

### Environment

Host system: RPI4
Running method: Rasbian with Deconz-GUI
Firmware version: (26780700)
deCONZ version (not Home assistant Addon version!): (2.24.2)
Device: ConBee II
Do you use an USB extension cable: no
Is there any other USB or serial devices connected to the host system? NO

**Comment by SwoopX** [comment]
This has nothing to do with the REST API.

**Comment by phuongpham** [comment]
@SwoopX which repo does this belongs to?
Something changes during the 2.42.2

**Comment by SwoopX** [comment]
You may raise this in the Phoscon forum.
