### ISSUE TITLE
Frient Keypad : adding more codes than just master code to alarm system in order to have RFID tags working

### ISSUE THREAD

**Issue by Gw3n4** [dresden-elektronik/deconz-rest-plugin#7386]
### Is there already an existing issue for this?

- [x] I have searched the existing issues and there is none for my device

### Product name

Frient keypad KEPZB-110

### Manufacturer

Frient

### Model identifier

KEPZB-110

### Device type to add

Other

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105949408/7a8666f7-41c1-4aac-96b3-ff5b4b663af3)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105949408/3f6391ee-0df8-43e2-9c7d-da96c3ba9a67)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105949408/a6f461e5-f62e-4c64-ae0e-cad89540d100)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/105949408/f32524af-a2be-40b8-8561-605ea15a0793)

**Comment by Gw3n4** [comment]
OK, thank you. I didn't know i could comment on the previous issue as it was closed.

**Comment by Mimiix** [comment]
You can unless it's locked :)!
