### ISSUE TITLE
zbeacon DS01 Open/Close Sensor

### ISSUE THREAD

**Issue by traschke** [dresden-elektronik/deconz-rest-plugin#7415]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

zbeacon

### Manufacturer

zbeacon

### Model identifier

DS01

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5337580/c6fe891f-6c84-4339-91ce-b09210f89c32)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5337580/861d628f-9a3f-4d53-812d-95972d8248ed)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5337580/9b6b0a0a-d3a5-44d8-bced-59baa6f40552)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5337580/9b7a7f08-05a9-487d-9050-2bef0a799954)

**Comment by traschke** [comment]
I have found the following forum post which states sensor could be a Sonoff/eWeLink clone/brand: https://community.smartthings.com/t/edge-driver-mc-zigbee-drivers-for-motion-open-close-moisture-smoke-co-sensors-and-others-devices/231689/4058
The model identifier DS01 is also used by the Sonoff SNZB-04, maybe it's the same sensor in another housing.

The product page I ordered this sensor from however states it uses some kind of Tuya chip: https://a.aliexpress.com/_EG3u95B

Other than that I could not find much about this sensor.

**Comment by Raupinger** [comment]
Hi there. not using dconz myself, but this was the only thing that came up when is searched for "zbeacon DS01" so here what i know: took mine apart and assuming [these](https://community.hubitat.com/t/sonoff-snzb-04-zigbee-door-window-contact-sensor-internal/47475) pictures of the sonoff sensor are accurate and current, mine looks very different. The main chip is a TLSR8258 F512ET32 In case anyone interested comes across this, here's a photo of the pcb as well as some of my notes on where the chips pins are connected:

![IMG_0178](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/29229062/43723870-58d5-4b60-9feb-f2a0e6de9532)


![IMG_0177](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/29229062/cfa4bde4-d6ed-429a-9bb8-ea86b4f355a7)
