### ISSUE TITLE
Device request for _TZ3000_0zfrhq4i

### ISSUE THREAD

**Issue by michaelblight** [dresden-elektronik/deconz-rest-plugin#7419]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

SIXWGH

### Manufacturer

_TZ3000_0zfrhq4i

### Model identifier

TS011F

### Device type to add

Switch

### Node info

Note that the switch functionality works indeConz, just not the powere metering.

<img width="109" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/eeb90892-fdc1-4750-ad8e-df54c690a40d">

<img width="173" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/1266adf3-5ab2-4ac9-9669-40be91beb978">

Simple Metering Cluster:
<img width="163" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/03ca2855-6397-4d6d-8652-0e79d354d22c">

Electrical Measurement Cluster:
<img width="161" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/d09a4a83-9dd2-4c3e-b3fe-a099e406f919">

### Endpoints and clusters

Simple Metering Cluster:
<img width="163" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/03ca2855-6397-4d6d-8652-0e79d354d22c">

Electrical Measurement Cluster:
<img width="161" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/d09a4a83-9dd2-4c3e-b3fe-a099e406f919">

### Basic

<img width="164" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/5baa75f8-a4d9-43a1-a4f9-4fbf78d84a85">

### On/Off
<img width="172" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/2354d377-296b-493c-acf3-00f75b062815">

### Simple Metering
<img width="163" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/03ca2855-6397-4d6d-8652-0e79d354d22c">

### Electrical Measurement
<img width="161" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/373079/d09a4a83-9dd2-4c3e-b3fe-a099e406f919">

**Comment by GitTheFOuttaHere** [comment]
Same problem here. No solution yet.

**Comment by Smanar** [comment]
Hello, can try this DDF
```

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_0zfrhq4i",
  "modelid": "TS011F",
  "vendor": "Tuya",
  "product": "Wired Switch 1 gangs",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/tuya_unlock"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "refresh.interval": 360,
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "eval": "Item.val = Attr.val * 10;"
          }
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "refresh.interval": 360
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 10,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000005"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000100"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 10,
          "max": 300,
          "change": "0x00000010"
        }
      ]
    }
  ]
}
```


Power/consumption and ect can need to be converted *10 ot /10 by exemple. Just tell me the value you have and the one you need.

**Comment by michaelblight** [comment]
Is it possible to use a DDF if I'm using the Home Assistant deCONZ addon? I can connect to the docker container if necessary to test, but I'm not sure what is required.

**Comment by michaelblight** [comment]
I tried the above, but after reloading deCONZ it didn't work. When editing the DDF through the GUI it said "unnamed file" (or something like that) and the log said DDF not found.

However, in the meantime I bought another plug from the same supplier, and this one showed up as "_TZ3000_typdpbpg", and was recognised properly. I took a punt and copied the DDF from that one (in /usr/share/deCONZ/devices/tuya/_TZ3000_typdpbpg_smart_plug_eu.json) and renamed the manufacturer name, and that seems to have worked.

Also, so I don't forget next time, I think you need to also reload the deCONZ integration in HA (not just restart the addon), although I have "Allow automatic addition of new devices" disabled, so maybe that's why.

Thanks for your help.

**Comment by Smanar** [comment]
But like this, the procedure you have done will be not persistent, it mean at next restart you will loose your changes, it's like that works dockers.

**Comment by michaelblight** [comment]
I copied from the source from /usr... into a modified file in /data, which is mapped to a folder on the host, so it's ok.
