### ISSUE TITLE
SNZB-01P Sonoff Button

### ISSUE THREAD

**Issue by Idaho947** [dresden-elektronik/deconz-rest-plugin#7423]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Sonoff Button

### Manufacturer

Sonoff

### Model identifier

SNZB-01P 

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/b4e80054-d906-460b-be09-2b1e1e654033)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/b4e80054-d906-460b-be09-2b1e1e654033)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/98dd6f30-55fd-455d-abf4-6bdb987317c8)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/514e899c-4b89-4157-91cc-67d477c9c769)

### Pull control
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/9b0fa8f1-78a2-4c5c-9f6a-65a685aea8f3)

**Comment by Idaho947** [comment]
Hello nobody is interested ?

**Comment by Mimiix** [comment]
@smanar perhaps :)>?

**Comment by veloc** [comment]
I also have one of these and would like to see them integrated into deconz!
If I can contribute in any way, please let me know.

**Comment by Smanar** [comment]
Can try with this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "eWeLink",
  "modelid": "SNZB-01P",
  "product": "SNZB-01P",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x000"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "refresh.interval": 7265,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 7200,
          "change": "0x00000002"
        }
      ]
    }
  ]
}
```

And this edition in button_maps.json file

        "sonoffOnOffMap": {
            "vendor": "Sonoff",
            "doc": "Switch SNZB-01",
            "modelids": ["WB01", "WB-01", "SNZB-01P"],
            "map": [
                [1, "0x01", "ONOFF", "ON", "0", "S_BUTTON_1", "S_BUTTON_ACTION_DOUBLE_PRESS", "double"],
                [1, "0x01", "ONOFF", "OFF", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "long"],
                [1, "0x01", "ONOFF", "TOGGLE", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "short"]
            ]
        },

**Comment by Idaho947** [comment]
Perfect as usual. It works very well.

**Comment by Smanar** [comment]
So all is fine ? I can make the PR ?

**Comment by Idaho947** [comment]
Yes you can

**Comment by Smanar** [comment]
Thx, done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7483
