### ISSUE TITLE
Devices keep dropping

### ISSUE THREAD

**Issue by easybeat** [dresden-elektronik/deconz-rest-plugin#7425]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

As in another handful bugs described here:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2710
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6201

I'm facing the same problem since I'm using Deconz for YEARS

![Connections 2023-12-10 161622](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/6ed276dc-2fdb-434c-98b1-85cbf4902d76)
5 Mins. after restart

![Connections 2023-12-10 162436](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/a2af65f8-1aaa-4ded-ac46-f9f6a75c0adc)
15 Mins. after restart

As @dawiinci mentioned here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6201 is this a bug in the firmware?

### Steps to reproduce the behavior

1. start deconz-gui
2. wait 5 Mins. and check connections
3. wait 15 Mins. and check connections again

### Expected behavior

No connections should be dropped

### Environment

- Host system:NAS with Proxmox 8.1
- Running method:  Ubuntu Desktop 20.04 as a Proxmox VM
- Firmware version: 26780700
- deCONZ version: 2.22.00 / 19.9.2022
- Device: ConBee II 
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? If so: USB3 ext. powered Hub + ZWave Stick

**Comment by easybeat** [comment]
Here my log files
[deconz log droping lights.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13629114/deconz.log.droping.lights.txt)

**Comment by Mimiix** [comment]
The discussion about closing issues is not going to be held here. If you want to have that, open a post on the forums.

For the latter, others are more suitable to answer it.

**Comment by manup** [comment]
Does this happen with the latest release too?
There were quite a bunch of fixes in regards to poll and keep devices alive.

**Comment by easybeat** [comment]
@manup And just to make clear I have 2 different systems which I have the same symptoms...just one gone completely by now. And this was running since about 3 years but always had this symptoms but whenever I power cycled the lights they came back on. But not now! Powercycle doesn't help.

I have a backup back from June which I try to restore now because there everything was ok.

**Comment by manup** [comment]
Currently I wouldn't recommend to switch between versions, but get to the cause where it fails.
Can you please check if DDFs are enabled via *Menu -> Panels -> Control*, should look like:

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/383386/57f7d01d-3849-4780-be33-5be7267a340a)

The logs above don't show hard networks errors as most/all commands get confirmed but there also appears to be mostly legacy traffic.

With DEV and DDF logging enabled in *Help -> Debug view* we should see more.
It would be helpful to then pick one device which goes unreachable and check what happens there.

**Comment by Mimiix** [comment]
> Yes DDF is on ![image](https://private-user-images.githubusercontent.com/37217887/289542930-a9e4cf89-7878-4b99-aef3-353d86ff97ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDAyNjIsIm5iZiI6MTcwMjI5OTk2MiwicGF0aCI6Ii8zNzIxNzg4Ny8yODk1NDI5MzAtYTllNGNmODktNzg3OC00Yjk5LWFlZjMtMzUzZDg2ZmY5N2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEzMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1M2Y3N2UyOGVmOTJiMWE2YTI3ODU4YWU1N2NmZjcxOTkzNjQ5NmI0YjQyM2IzN2RjYzI2YjUyODIwZmRiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.klZr4HQ3wMji5h1xWB5IHn6V-pavF9gjlhhWSZ184lI)
> 
> [DDF error log.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13635680/DDF.error.log.txt) here the ddf log

Are you sure the DEV log is enabled on that log ?

**Comment by easybeat** [comment]
sorry missed dev
[DDF error log.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13635774/DDF.error.log.txt)

**Comment by manup** [comment]
>14:08:44:311 DEV Poll Busy /devices/0x00178801011445B8 ZCL response seq: 59, status: 0x86, cluster: 0x0008

Now this looks interesting, which modelid does the 0x00178801011445B8 have – can be seen in the Node Info Panel  (it's a Philips / Signify device)?
The 0x86 means Unsupported Attribute, perhaps the DDF tries to read attributes which are only available in newer lights firmware, have to check with the other devs.

**Comment by manup** [comment]
And this Hue Go does drop off after a while as well?
When you power-cycle a light which has dropped off does it come back and can be controlled?

**Comment by easybeat** [comment]
No the Hue GO always works it's the lights WAND
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/8cb5bb6a-ac22-4eef-9291-198002645158)

or now even some IKEA Range Extenders
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/53cc28f6-1c65-445c-a2c6-5dda86678e1d)

all different manufactorers failing now

**Comment by manup** [comment]
Also can you please provide the firmware version for the Hue Go as shown in the Basic Cluster:
When you double click on the node and then double click on Basic (first item in the list)

Then press "read" in the attributes table:

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/383386/67924e37-0b28-4e23-8fe9-266bf19569e6)

**Comment by manup** [comment]
> No the Hue GO always works it's the lights WAND ![image](https://private-user-images.githubusercontent.com/37217887/289552928-8cb5bb6a-ac22-4eef-9291-198002645158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDIzMDAsIm5iZiI6MTcwMjMwMjAwMCwicGF0aCI6Ii8zNzIxNzg4Ny8yODk1NTI5MjgtOGNiNWJiNmEtYWMyMi00ZWVmLTkyOTEtMTk4MDAyNjQ1MTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEzNDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YjY2NDA3NjA3YTVlNTM3NTBmN2E3NjI3M2QyNmVmMTkxZDU0NjliYjMxNzY1NWM5NGZhZDFiMTVjZjdhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CP6hv9GmZqoDtANF081Lqm0C9sB0MG9iL59J5NVf6_0)
> 
> or now even some IKEA Range Extenders ![image](https://private-user-images.githubusercontent.com/37217887/289553147-53cc28f6-1c65-445c-a2c6-5dda86678e1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDIzMDAsIm5iZiI6MTcwMjMwMjAwMCwicGF0aCI6Ii8zNzIxNzg4Ny8yODk1NTMxNDctNTNjYzI4ZjYtMWM2NS00NDVjLWEyYzYtNWRkYTg2Njc4ZTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEzNDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjU1MWUyZmIzMWMxMzc5NThjODQ0ZGVhYTM0MWIwZmFlM2YyNDkxMGUyNDJhZDg5MDk4NDRjNWQ5NDAwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LH-e-gtg5wcWY_IqPymVEJKIKB-CYh00bMvcXlLLBY8)
> 
> all different manufactorers failing now

Hmm can't see these in the logs (perhaps too short), but this is still the old deCONZ version? It would be really helpful to make the tests with the recent version.

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/828b330b-f319-4258-89c9-cfca4bd11e5c)

**Comment by easybeat** [comment]
> > No the Hue GO always works it's the lights WAND ![image](https://private-user-images.githubusercontent.com/37217887/289552928-8cb5bb6a-ac22-4eef-9291-198002645158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDIzMDAsIm5iZiI6MTcwMjMwMjAwMCwicGF0aCI6Ii8zNzIxNzg4Ny8yODk1NTI5MjgtOGNiNWJiNmEtYWMyMi00ZWVmLTkyOTEtMTk4MDAyNjQ1MTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEzNDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YjY2NDA3NjA3YTVlNTM3NTBmN2E3NjI3M2QyNmVmMTkxZDU0NjliYjMxNzY1NWM5NGZhZDFiMTVjZjdhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CP6hv9GmZqoDtANF081Lqm0C9sB0MG9iL59J5NVf6_0)
> > or now even some IKEA Range Extenders ![image](https://private-user-images.githubusercontent.com/37217887/289553147-53cc28f6-1c65-445c-a2c6-5dda86678e1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDIzMDAsIm5iZiI6MTcwMjMwMjAwMCwicGF0aCI6Ii8zNzIxNzg4Ny8yODk1NTMxNDctNTNjYzI4ZjYtMWM2NS00NDVjLWEyYzYtNWRkYTg2Njc4ZTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEzNDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjU1MWUyZmIzMWMxMzc5NThjODQ0ZGVhYTM0MWIwZmFlM2YyNDkxMGUyNDJhZDg5MDk4NDRjNWQ5NDAwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LH-e-gtg5wcWY_IqPymVEJKIKB-CYh00bMvcXlLLBY8)
> > all different manufactorers failing now
> 
> Hmm can't see these in the logs (perhaps too short), but this is still the old deCONZ version? It would be really helpful to make the tests with the recent version.

well I can do the update to 2.24.2 if you want me too

**Comment by manup** [comment]
Ideally DDF + DEV APS, ZDP and INFO over 10-20 minutes. That's quite noisy but should show more what's going on

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/cc6edfa2-c760-4b81-84da-ebc63f35ad98)
on 2.24.2 looks the same after a few minutes they seem to connect

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/ee9fe533-d385-4a0a-bef4-854fe78f716b)
but if I go into Phoscon the lights show all greyed out

**Comment by easybeat** [comment]
[Deconz log 1504-1507.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13636500/Deconz.log.1504-1507.txt)
first 3 minutes

**Comment by easybeat** [comment]
[Deconz log 1504-1510.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13636548/Deconz.log.1504-1510.txt)
somehow it seems to work

**Comment by easybeat** [comment]
[Deconz log 1507-1513.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13636580/Deconz.log.1507-1513.txt)
6 Mins. steps I can do...hope that's ok

**Comment by easybeat** [comment]
[Deconz log 1513-1519.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13636664/Deconz.log.1513-1519.txt)
another 6 Mins.

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/4005f595-08ae-42bd-9fc6-05b06b38c9c6)
and by the way the Ikea Range Extenders have not been recognized anymore

**Comment by easybeat** [comment]
[Deconz log 1519-1525.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13636740/Deconz.log.1519-1525.txt)
that's 21 Mins. do you need more?

**Comment by manup** [comment]
Hmm interesting I'm looking after the 0x00158D0000B1EF40 (Wand04 ?)
This one is seen by many devices but no attempt yet to contact it (.. Deconz.log.1507-1513.txt).

This one doesn't have a DDF yet nor the Paul Neuhaus lights, so there seems to be something off with the legacy code :thinking: 

The Ikea repeaters however should work once they are queried (this may take a bit the first time they are used via DDF).

**Comment by easybeat** [comment]
[Deconz log 1525-1531.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13636826/Deconz.log.1525-1531.txt)
I think in this 6 minutes light wand 03 lost the green line
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/1d9f2420-2e89-48dd-bc8e-3c028bf3b33a)

**Comment by easybeat** [comment]
> Hmm interesting I'm looking after the 0x00158D0000B1EF40 (Wand04 ?) This one is seen by many devices but no attempt yet to contact it (.. Deconz.log.1507-1513.txt).
> 
> This one doesn't have a DDF yet nor the Paul Neuhaus lights, so there seems to be something off with the legacy code 🤔
> 
> The Ikea repeaters however should work once they are queried (this may take a bit the first time they are used via DDF).

Any more ideas how to get this system back to work...my friends are not very happy that they can't operate their lights :-(

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/5fbf54a9-0cdd-4342-b00d-105e420992be)
also the Ikea Range Extender are still not recognized

**Comment by easybeat** [comment]
@manup Any more help today?

**Comment by easybeat** [comment]
Thanks Manu.

yes live session tomorrow would be helpful. I'm available from 08.00 - 11.00 GMT+1

I expect you are in Germany? I'm from Switzerland...so we can then also change to German...

I've sent the backup files to you support e-mail.

**Comment by easybeat** [comment]
Thank you for the new version. But how do I have to install this?

I run it on an Ubuntu 20.04 desktop and get this error message:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/58b63655-feec-4c43-bd0d-a5c7648b46c5)

**Comment by easybeat** [comment]
> Unfortunately I can't manage to be available before 14/15.00.

And yes I could also do these times...let me know

**Comment by manup** [comment]
>Thank you for the new version. But how do I have to install this?
>I run it on an Ubuntu 20.04 desktop and get this error message:

Oh damn my bad, thought you're running on a Raspberry Pi. Here is the version for Desktop AMD64

[deconz_2.24.2-debian_amd64.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13648738/deconz_2.24.2-debian_amd64.zip)

**Comment by easybeat** [comment]
np...I'll try to install now

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/45bde496-3cc3-47bf-9d22-769704bdbb94)
It says now that a never version is already installed...should I try it on the machine with the 2.22.0 version?

**Comment by manup** [comment]
I guess that's the Ubuntu UI installer thing..
Better make this on the command line:

`sudo dpkg -i deconz_2.24.2-debian_amd64.deb`

**Comment by easybeat** [comment]
ok installed it from command line over the 2.22.0 installation...can also try on the box with 2.24.2 already installed

It looks not much different to me
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/3d95feb9-7bcb-4ade-8dbf-d87bd43b30b0)


![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/dd91ce80-89b0-4a39-8fce-0c857b9af78a)
in phoscon still all greyed out

here is the log from first 6 Mins.
[Deconz log 20231212 1455-1501.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13648989/Deconz.log.20231212.1455-1501.txt)

**Comment by easybeat** [comment]
[Deconz log 20231212 1501-1505.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13649036/Deconz.log.20231212.1501-1505.txt)
next 5 Mins.

**Comment by manup** [comment]
Cool thanks, the Ikea range extender and Greeble lights are loaded via DDF now (for Ikea repeater the actual name is shown which wasn't before so it did pick up the code changes here).
I think next it makes sense to let it run for a while to see if it settles on these devices, I'll check the logs

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/febc2812-eeb2-451b-9ddc-e4dcd7a0b105)
I don't think it works as it has lost a lot of green lines already to Ikea and Wand-Lights

**Comment by easybeat** [comment]
[Deconz log 20231212 1508-1511.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/13649099/Deconz.log.20231212.1508-1511.txt)

**Comment by easybeat** [comment]
[Uploading Deconz log 20231212 1512-1515.txt…]()

**Comment by manup** [comment]
Are you also on our deCONZ Discord? Or access via Teamviewer, there I can test a few things.
The logs so far don't show any errors but it seems the devices are not yet treated as reachable

**Comment by easybeat** [comment]
ready for tw session....detail on support email

**Comment by easybeat** [comment]
np...I'm ready

**Comment by manup** [comment]
WTF Teamviewer says session closed for a few minutes

**Comment by easybeat** [comment]
come back now

**Comment by easybeat** [comment]
come back in

**Comment by manup** [comment]
Only 5 minute sessions with a small delay :see_no_evil:  be back in a minute :)

**Comment by easybeat** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/b23c1c50-49e0-404f-a909-9f5e7ecbaaf1)
Hmmm at least in Phoscon the ikea's are back!!

**Comment by manup** [comment]
Hmmm don't think they are really back, Teamviewer drives crazy, perhaps we can try Anydesk? (see mail).
I think to know why the devices don't react

**Comment by manup** [comment]
The network is super weird, I've added a few notes in the text editor, would be good to try the power cycle next to see if some devices manage to come back.

**Comment by easybeat** [comment]
Ok. Thanks for you research.

Do you know the "other" network key? Just wondering if there has been a mixup with my other system... 

Is there no way to "migrate" the wrong devices to the new network key?

Powercycle some other devices will only happen tomorrow.

**Comment by manup** [comment]
Changing the network key remotely isn't possible yet (there is a Zigbee command to do this but nobody actually uses that, so I assume it's also not really tested/supported for devices).

If you can send me the network key from the other setup I can enter it in the sniffer log and see if it works.

**Comment by easybeat** [comment]
And just another thought. Looking at the connected devices now. It looks that even more are lost.
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/e62594cd-d844-47a1-a055-134214722f57)
the 2 hue go have gone now too?

**Comment by manup** [comment]
It's due the channel change, they'll be back after switching back or doing a power cycle. It's a bit messy but the Philips devices usually should be the easiest to deal with.

**Comment by easybeat** [comment]
Ok. 

Can you find out which is the other network key?

Sent you the key from other system in email

**Comment by manup** [comment]
Just checked the key from the mail, it doesn't match any traffic I've captured on channel 15 (ca. 3000 Zigbee messages).
It's not really possible to extract the encryption key from the traffic, only when a network is opened during pairing a key can be sniffed.

**Comment by easybeat** [comment]
Hmmm that worries me even more. Where should this network key coming from?

Is there a way in deconz to rgenerate a new network key?

**Comment by easybeat** [comment]
@manup Hi Manuel

nothing did work with powercycle and also no more lights were happy to join the network on new channel

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/dbe77122-d863-40d7-9e34-d4ab9c87b91c)

Do you have anymore ideas how to fix this or at least what could have caused it?

**Comment by manup** [comment]
Hm damn, but was worth a try often the power cycle can fix issues, but here it seems to broken.
Unfortunately I don't  have more ideas how to bring back the not responding devices other than to factory reset them.

I'd propose to move the network back to channel 15 via Phoscon App > Menu > SGateway Advanced Settings.
Important, **do not** delete the devices in the Phoscon App, so the settings groups and so on don't get lost.

Then start search for lights and reset a device, e.g. for Ikea repeaters this is done via the pin-hole, I think Greeble and Paul Neuhaus do have a reset sequence. (I'd start with the repeaters to see that it works).

----- 

In terms what could have caused this I'm still not totally sure, but the sniffer logs show that there was some nasty stuff with the network keys. Perhaps due a security counter overflow, here it could be that since the `config.ini` wasn't writeable did speed up the problem and deCONZ couldn't track the counter. (I guess at some point deCONZ was started as root user which changed permissions to the file... I fixed the file permissions yesterday).

I'm currently reading through the Zigbee spec to get a better picture how the overflow is usually treated, hopefully to be able to recreate the situation and check what happens via sniffer, but this won't help for your setup since it's already in this unfortunate state.

**Comment by easybeat** [comment]
First thank you very much Manuel for all the work you have done and tried to fix it. I really appreciate this!

As this system is running in a friends house I will have a discussion with him if he wants to stay on deconz or not. They will be without light controll in their house for a whole week. I would never have thought this can happen and have all different backup options in place but not for this. I might consider to move everything to zigbee2Mqtt and as there is a ioBroker running to the zigbee adapter from ioBroker. This will mean that operation the Groups and Scenes will be much more difficult as this is for me the biggest feature with deconz/phoscon.

My much bigger worry is that this could also happen on my own system because this is about 3x the size and will be even more stress!

What I don't understand is how this security counter works? Because what happens if I decide to restore a backup from 3 month ago on a complete new environment? Is the counter inside the backup? But then it will be reset also to a much lower number or why do you think there could have been an overflow of the counter?

And next I'm wondering if you maybe should rethink if the config.ini is the right place for the counter to be written? As you describe to start it as deconz as root can happen very easy and if it ends up in such a disaster then there is something wrong by design.

But I let you do your research and would be very interested to know what the problem is. If it helps I could provide you with a backup of the VM from proxmox so you could maybe run your test on this system even if you don't have the lamps?

**Comment by easybeat** [comment]
hi @manup 

Ok today I rejoned all the lights and switches to the system. A bit of work and interesting that I was unable to join back about 5 lights of different manufactors. Now it looks a bit better:

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/8ed9c44e-4a49-44fe-83e1-878017a281eb)

I did it in these steps:
1. rejoined all the lights on the old ubuntu 20.04 vm with your latest version installed
2. took a backup
3. setup a completely new ubuntu desktop 22.04 vm and your latest version on
4. restore the backup

Interesting was for me that the channel change to 25 was not coming with the backup and I had to change to channel 25 on the new environment again. Is this a bug in the backup?

But still had some very strange behaviours of some lights:

1. Wand06 a greeble light just didn't want to join back on. I did a full reset about 5x but no connection was possible
6. Gaestezimmer Bloom a hue bloom 1st generation: I did manage to bring it back 3x but after 5 Mins. it was gone again. So it is now unplugged and I took it home with me
7. Badezimmer 03 a philipps hue GU10: Was rejoined successfully but after about 1 or 2 hours it dissappeared. Tried to rejoin, no success. So deleted it and then it came back on. Only to disappear after 5 Mins. again. Also this is powered off now.

I think especially the Bloom could be interesting for you to investigate. If you want I could send you it and you could maybe test it with my backup and see if you can figure out what is going so wrong there that it is lost after 5 Mins.

Should I send you some startup logs (first 15 Mins. from the new system)?

Please let me know how to go on because I think it is in everybodies interest here that we find out more what went so wrong.

**Comment by easybeat** [comment]
Hi @manup 

Here an update after 24h + running on the new system. And the result is:

I AM ALREADY LOSING LIGHTS AGAIN!

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/2c687629-3bd1-487d-acaa-faae0ca1544d)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/f5be5e3b-ecfd-4a40-bcd8-52ef42548f54)

I need your help as this is a complete disaster.

Could you please help me to figure out what the next steps could be to stabilize this?

Thank you

**Comment by manup** [comment]
Currently compiling the new release we should try this once completed.
Is there any streaming stuff, TV or audio, via Bluetooth or WiFi going on at the location?

Where the lights controllable after rejoining them, here I mean not just the lines but actual controlling?

**Comment by easybeat** [comment]
There is a sonos system and a google chromecast both using wifi.

All the lights were ok to controll and I think they still are using the rest api!

**Comment by manup** [comment]
Hard to tell if this is a problem here but when streaming devices are active and overlap with Zigbee channels it can cause problems, but when not active it should be ok. I was asking because I had once a network to debug only to find out in the end that the house was packed with Bluetooth audio stuffing a good portion of RF channels.

In the deCONZ GUI a quick test to see if a light is around is to select the node and press `0`, normally it should blink blue afterwards if a response is received.

You mentioned another Zigbee network around, is that still active and nearby the location? Then we should compare the configurations.

**Comment by easybeat** [comment]
There is a Zwave network in the same house but no other zigbee.

If I right click on the node and choose rwad node then they blink blue about 4x but it never comes back active again in phoscon.

And using a group call over api by ioBroker and starting a scene still works absolutely fine.

**Comment by manup** [comment]
Zwave is fine as it doesn't overlap with 2.4 GHz.
Do the lights also react physically to the group commands?

**Comment by easybeat** [comment]
You mean if they turn on?

They work absolutely fine with group commands. On, off and change scene work fine

**Comment by beginnersguide** [comment]
Hi, I am following this issue because I have the same problems with some lights. Visually, in deconz, they are losing the connection.  I am only able to control the specific light over the group and not directly. In deconz the light is greyed out with no neighbor links.

**Comment by Paule-Panter** [comment]
Hi,  I'm also following this topic because i had similar problems for a while.
I don't want hijack this topic, just give my 2cent:
Not so dramatically, but lost sometimes some lights, sensors and switches. They greyed out in phoscon. The lights then only reachable via group commands. Sometimes a reboot of deconz helped a while (without a power reset of the light).
Sometimes i just repowered the lights, sensor and switches and everything will be fine for a while.

I have the feeling, if I use intensivly the rest-api (via openhab or hue essentials) there are I get more of this "zigbee-zoombies", that i have to recover with a power reset. But this is just feeling.

18.12.2023 22:03:39 beginnersguide ***@***.***>:

**Comment by easybeat** [comment]
@Paule-Panter do you say that these problems have gone now on your system or do they still exist?

If they gone what have you done? Just power reset all the time?

**Comment by Paule-Panter** [comment]
Everything is fine at the _moment_.
It's certainly a matter of time before some devices are unresponsive again.
And yes, i power reset all the time.
I didn't find any other way to recover and no indication for interference or other hw-faults.
However, I'm still on release 2.23.01.
After reading the changLogs, i preferred to wait. And I'm also considering whether I should switch to a different system.

19.12.2023 07:45:44 easybeat ***@***.***>:

**Comment by manup** [comment]
Little update, I'm testing various cases to recreate the issue in my network. Surprising results after messing around with a few parameters and wildly power cycling devices I could get a few devices (Ikea and Tuya but not in general all of them) to not be responsive to non group commands. So they become Zombies.

In the sniffer I see that they simply ignore messages send from the coordinator, which they shouldn't, I've checked the security counters as well and they are fine. Power cycle a light in this state and it became responsive again, I think like it was mentioned above. But that's rather fugly ...

Messing around a bit more I could get the lights into dialog again without power cycle but using a different (source) route to target the light over a path where the light knows the last hop (it should be irrelevant but somehow certain lights are sensitive to this). This might be a good workaround, I'm currently refining the code to improve trying alternative routes, should be part of the next smaller release this week.

**Comment by Paule-Panter** [comment]
That sounds good and gives me hope.
It occurs to me that I still have a hue light bulb, which my child still switches off completely from time to time using the light switch (230v switch-off).
As I understand it, zigbee should normally lead to rerouting (especially if source routing is activated, right?) Perhaps this is also the case with me for the occurrence of the zoombies and a new route is learned by powerreset/deconz restart and reactivation of source routing.
But it would be nice if the zoombies could be automatically revived.
Thanks so far for the in-depth investigations.




20.12.2023 11:46:50 Manuel Pietschmann ***@***.***>:

**Comment by easybeat** [comment]
> Little update, I'm testing various cases to recreate the issue in my network. Surprising results after messing around with a few parameters and wildly power cycling devices I could get a few devices (Ikea and Tuya but not in general all of them) to not be responsive to non group commands. So they become Zombies.
> 
> In the sniffer I see that they simply ignore messages send from the coordinator, which they shouldn't, I've checked the security counters as well and they are fine. Power cycle a light in this state and it became responsive again, I think like it was mentioned above. But that's rather fugly ...
> 
> Messing around a bit more I could get the lights into dialog again without power cycle but using a different (source) route to target the light over a path where the light knows the last hop (it should be irrelevant but somehow certain lights are sensitive to this). This might be a good workaround, I'm currently refining the code to improve trying alternative routes, should be part of the next smaller release this week.

Good morning @manup 

This sounds like a great plan.

Please let me know when ready to install. I will be offline for a few days until the 26th and will try to install it after.

**Comment by easybeat** [comment]
@manup Interesting! Checking today the 2 Greeble lights came back without a power cycle (as I know!)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/d0018397-1587-4fde-9494-6494e7483abf)

**Comment by easybeat** [comment]
> This might be a good workaround, I'm currently refining the code to improve trying alternative routes, should be part of the next smaller release this week.

@manup Hi Manuel
Is this workaround included in 2.25.1? If yes I would like to give it a try...please let me know.

Thanks

**Comment by manup** [comment]
Yes the improved source routing is in v2.25.1-beta, note it needs to enabled manually, for a small introduction please visit: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Source-Routing

This is currently only working for RaspBee / ConBee I and II, for ConBee III we are testing the application source routing support, this will be published in another firmware update.

**Comment by beginnersguide** [comment]
Can I easily switch from stable to beta releases in docker to test it?

**Comment by easybeat** [comment]
Hi @manup 

Sorry for delay. I decided to wait for final release 2.5.3 and do not more experiments on my home system.

Now I have 2.5.3 installed and waiting if my greyed out devices will come back to "live". 

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/37217887/ef843f01-2e19-4f25-90d3-cd1a6f993022)
my 2 kitchen lights are greyed out since weeks but work fine

I enabled source routing and created a source route from coordinator to kueche3 - kueche2 - kueche1.

Will let you know the results in a few days.

Thanks

**Comment by easybeat** [comment]
Hi @manup 

I waited now to weeks for the kitchen lights to come back on but no success. So now I powercycled them again (hopefully the last time ever!) and now they are back on!

Will update this thread here as maybe somebody will find it helpful.

Kind regards
