### ISSUE TITLE
Aqara E1 QBKG39LM Wall switch no neutral

### ISSUE THREAD

**Issue by Kipyneter** [dresden-elektronik/deconz-rest-plugin#7438]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Aqara E1 QBKG39LM

### Manufacturer

LUMI

### Model identifier

lumi.switch.b2lc04

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/747a492d-cf34-4fd9-a3d9-2133e45fa175)

### Endpoints and clusters

Clusters:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/09390916-cc02-401b-9205-f6723d5c1161)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/37549d9d-0c14-48aa-8756-4733aa374d48)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/d2782ff7-f932-4b68-8a01-0d3f729087dd)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/d04a1579-5a28-48fb-b12f-d696ee240fa8)

### Any other cluster of relevance/interest
Device Temperature Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/9244c928-39fa-4d2e-9a56-52f2882a9a50)

LUMI specific:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/c3f8d11f-1381-436a-99db-a9ad51612293)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/074d60e0-4439-4d57-b887-ab309aae968a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/719639f4-b474-424d-a90b-1b250f275fcb)

Multistate input:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/121611163/af22ea27-dc70-4c1f-a984-1279fe9f424e)

**Comment by Kipyneter** [comment]
That did the trick! Thank you so much.
I did not realize that I can change existing files that easy.

**Comment by SwoopX** [comment]
Nice. If you could test/note down the values for the Multistate Input Cluster attribute 0x0055 on the button presses, we could create the respective button map as well. Single/double/tripple/long press are the #1 candidates 👍
