### ISSUE TITLE
Device wrongfully recognized (Human Presence Detector, _TZE200_v6ossqfy)

### ISSUE THREAD

**Issue by raderack3948** [dresden-elektronik/deconz-rest-plugin#7448]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

The sensor is a MmWave presence detector, I've also found it listed as such in the code here in the repo. But when I connect it trough the phoscon app it is shown as a light switch?
Note: I'm using the deCONZ integration in Home Assistant.

Phoscon Version:
Version: 2.22.02 / 19/09/2022
Firmware: 26720700

*Edit* - Product Link:
https://www.amazon.de/gp/product/B0BSKSWV8V

*Edit #2* 
I've seen the behaviour in the device request - but did not see a solution:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6742

Phoscon View:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35975046/f6c55b8e-04a1-4dea-81be-38a3c41f5412)

Deconz View:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35975046/bdea5095-1410-43b6-9271-40602e3fa65e)

Node Info:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35975046/0fa86159-428c-4771-a566-518f849b4725)

Basic Info:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35975046/948e2307-484e-4ade-bfd3-8c3119e5f624)

### Steps to reproduce the behavior

Occurs on binding the sensor

### Expected behavior

That the device shows up as a motion sensor

### Environment

- Host system: Home Assistant
- Running method: HASS OS
- Firmware version: 26720700
- deCONZ version (not Home assistant Addon version!): 2.22.02
- Device: ConBee II
- Do you use an USB extension cable: no
- Is there any other USB or serial devices connected to the host system?: No

**Comment by Mimiix** [comment]
Hi,

This please read the template carefully. You are not reporting an issue with deCONZ but Phoscon.

Please use the correct channels.

Closing this.

Kind regards,

**Comment by raderack3948** [comment]
Sorry for asking - where do I find the phoscon repo? The phoscon repo here is archived, I cannot create an issue.

**Comment by Mimiix** [comment]
> Sorry for asking - where do I find the phoscon repo? The phoscon repo here is archived, I cannot create an issue.

Thats shown during creation of this issue. There a url to the forums.

**Comment by raderack3948** [comment]
> > Sorry for asking - where do I find the phoscon repo? The phoscon repo here is archived, I cannot create an issue.
> 
> Thats shown during creation of this issue. There a url to the forums.

Found it - Thank you!
