### ISSUE TITLE
IKEA SOMRIG Shortcut Button support

### ISSUE THREAD

**Issue by cook2000** [dresden-elektronik/deconz-rest-plugin#7449]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

IKEA SOMRIG Shortcut Button

### Manufacturer

IKEA

### Model identifier

SOMRIG

### Device type to add

Switch

### Node info

Can't pair it with deconz and therefore I can't make screenshot of the node.

### Endpoints and clusters

Can't pair it with deconz and therefore I can't make screenshot of the node.

### Basic

Can't pair it with deconz and therefore I can't make screenshot of the node.

**Comment by Mimiix** [comment]
If you cant pair it, there's no reason to open a request.

If you come to discord or something he forums we can check why you can't pair it.

Closing
