### ISSUE TITLE
IKEA SOMRIG Shortcut Button support

### ISSUE THREAD

**Issue by cook2000** [dresden-elektronik/deconz-rest-plugin#7450]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

IKEA SOMRIG Shortcut Button

### Manufacturer

IKEA of Sweden

### Model identifier

SOMRIG shortcut button

### Device type to add

None

### Node info

<img width="690" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/d611a2ff-5e53-4c40-b485-161392158df3">

### Endpoints and clusters

<img width="253" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/d04305a6-dbaf-4bbe-a0b9-6a83e786b50b">

<img width="189" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/2d270439-52ad-4c53-8e33-fe96ae8f254f">

### Basic

<img width="680" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/21a14733-84db-4486-a275-efa6a6e9a490">

### Power Configuration
<img width="694" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/b735087b-0e7e-46cd-b644-e56627f0df40">

### Poll Control
<img width="694" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/b9c863c9-58a2-4172-9b7f-66ab6650c82f">

### Identity
<img width="680" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/3ba07424-e423-4c9e-bb47-746ac3a71379">

### Groups
<img width="680" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/a8e6ebcb-03fe-4b0a-a26c-f51866cbfbb8">

### ZLL Commissioning
<img width="680" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/5bd172cd-e12c-42d8-8541-954eda9da906">

### IKEA specific
<img width="680" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/68708978/ac2652fe-274e-4f79-9f4a-ed22813f8147">

### Link to Product
https://www.ikea.com/at/de/p/somrig--shortcut-button-weiss-smart-50560334/

**Comment by Mimiix** [comment]
Can you please add all screenshots?

**Comment by cook2000** [comment]
added some more screenshots above and updated.

**Comment by Idaho947** [comment]
I bought this sensor and can t connect it to deconz. @Smanar have you a magic ddf ?

**Comment by Smanar** [comment]
Can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "IKEA of Sweden",
  "modelid": "SOMRIG shortcut button",
  "product": "SOMRIG Shortcut Button",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xFC80"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "refresh.interval": 86400,
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3200,
          "max": 3600,
          "change": "0x00000002"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0xFC80"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0xFC80"
    }
  ]
}
```

It will enable and configure the device (Need to use the 0xFC80 cluster) but it will not work yet.
After that (like usual), just enable deconz log with "info" + "info_l2" and share error about missing button map.

**Comment by Idaho947** [comment]
The device is paring but I see nothing in log when I press the button

**Comment by Smanar** [comment]
```
        "ikeaShortcutMap": {
            "vendor": "IKEA of Sweden",
            "doc": "IKEA SOMRIG Shortcut Button",
            "modelids": ["SOMRIG Shortcut Button"],
            "map": [
                [1, "0x01", "FC80", "COMMAND_3", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Button 1"],
                [1, "0x02", "FC80", "COMMAND_6", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Button 2"]
            ]
        },
```

But I think you can do some optimisation with this code from Z2M

```
            const lookup = {
                commandAction1: 'initial_press',
                commandAction2: 'long_press',
                commandAction3: 'short_release',
                commandAction4: 'long_release',
                commandAction6: 'double_press',
            };
```

On deconz value to use are

```
        "FC80": {
            "COMMAND_1": 1,
            "COMMAND_2": 2,
            "COMMAND_3": 3,
            "COMMAND_4": 4,
            "COMMAND_6": 6
        },
```

**Comment by Smanar** [comment]
For exemple by deduction to have a double press on button 1

`[1, "0x01", "FC80", "COMMAND_6", "0", "S_BUTTON_1", "S_BUTTON_ACTION_DOUBLE_PRESS", "Button 2 double press"]`

For a long press on button 2

`[1, "0x02", "FC80", "COMMAND_2", "0", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "Button 2 long press"]`

**Comment by Idaho947** [comment]
What do you think of :

`"ikeaSomrigMap": {
            "vendor": "IKEA of Sweden",
            "doc": "IKEA SOMRIG Shortcut Button",
            "modelids": ["SOMRIG Shortcut Button"],
            "map": [
                [1, "0x01", "FC80", "COMMAND_3", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Button 1"],
				[1, "0x01", "FC80", "COMMAND_4", "0", "S_BUTTON_1", "S_BUTTON_ACTION_HOLD", "Button 1"],
				[1, "0x01", "FC80", "COMMAND_6", "0", "S_BUTTON_1", "S_BUTTON_ACTION_DOUBLE_PRESS", "Button 1"],
                [1, "0x02", "FC80", "COMMAND_3", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Button 2"],
				[1, "0x02", "FC80", "COMMAND_4", "0", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "Button 2"]
				[1, "0x02", "FC80", "COMMAND_6", "0", "S_BUTTON_2", "S_BUTTON_ACTION_DOUBLE_PRESS", "Button 2"]
            ]
        },
`

**Comment by Smanar** [comment]
You have the device ^^, you can test your work.

On deconz we don't use the S_BUTTON_ACTION_INITIAL_PRESS, useless, we use instead the S_BUTTON_ACTION_SHORT_RELEASED to trigger event when the button is released.

Value can be different from z2m, but easy to correct whith try, else it seem good for me.

**Comment by Idaho947** [comment]
Ok it doen't work :

When I press on spot one time :
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/14037d82-86a0-4fe3-8552-36db156f86cf)

When I press two spot one time :
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/9cd15edd-9277-4ec2-84f9-af8ff665e61f)

My buttom map :
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/ce089f25-ce90-4eb5-9f24-205ef324baf8)

**Comment by Idaho947** [comment]
yes that's why :

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/b6301f2c-da87-4986-8f96-fa17db7819f8)

For me it's working.

**Comment by SwoopX** [comment]
@Idaho947 If you could share in text form what's working for you, we could quickly add it to the upcoming release 😉

**Comment by Idaho947** [comment]
I made that. Hope it's Ok :
`    "ikeaSomrigMap": {
            "vendor": "IKEA of Sweden",
            "doc": "IKEA SOMRIG Shortcut Button",
            "modelids": ["SOMRIG shortcut button"],
            "map": [
                [1, "0x01", "FC80", "COMMAND_2", "0", "S_BUTTON_1", "S_BUTTON_ACTION_HOLD", "Button 1"],
                [1, "0x01", "FC80", "COMMAND_3", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "Button 1"],
                [1, "0x01", "FC80", "COMMAND_4", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "Button 1"],
                [1, "0x01", "FC80", "COMMAND_6", "0", "S_BUTTON_1", "S_BUTTON_ACTION_DOUBLE_PRESS", "Button 1"],
                [1, "0x02", "FC80", "COMMAND_2", "0", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "Button 2"],
                [1, "0x02", "FC80", "COMMAND_3", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "Button 2"],
                [1, "0x02", "FC80", "COMMAND_4", "0", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "Button 2"],
                [1, "0x02", "FC80", "COMMAND_6", "0", "S_BUTTON_2", "S_BUTTON_ACTION_DOUBLE_PRESS", "Button 2"]
            ]
        }, `

**Comment by Smanar** [comment]
Ha right, I have made a typo ^^.
So thx for the corrected/tested button map :).

One of you want to make the PR ?

**Comment by noud-github** [comment]
I made a DDF file and changed buttons file here:

https://github.com/noud-github/deconz-rest-plugin/tree/somrig

not sure what the rules are for a PR, need to read up on that first ;-)

**Comment by Smanar** [comment]
There is an online validator for "rules" now.
Else there is a problem, you have created a buttonmap file in the "device" folder, you just need to edit the existing one (on the root)

**Comment by noud-github** [comment]
after testing I moved it back to the wrong folder, fixed now, 

simple question does the validator run on the |PR if I creat it?

**Comment by CerealPT** [comment]
@noud-github 
I updated my button_maps.json in the folder /usr/share/deCONZ/devices and also added the new DDF to the /devices/ikea.

After that I restarted deCONZ, paired the somrig shortcut button and when I press the buttons I see the following in the logs:

No button map for: SOMRIG shortcut button, unicast to 0x0000, endpoint 0x01, custer: FC80 (0xFC80), command: COMMAND_1 (0x01), payload: 00, zclseq: 95

What can be a cause for this? IS the buttons_map.json correctly loaded? is there something wrong there?

Thanks for your support!

**Comment by noud-github** [comment]
I added the buttons file in the wrong folder it should be : `/usr/share/deCONZ/`.  not /usr/share/deCONZ/devices

**Comment by noud-github** [comment]
> I noticed that when I restart the deCONZ addon in Homeassistant, the button_maps.json file inside the deCONZ docker container is overwritten and the mappings are lost. So I might not be updating the correct file.

That is docker behavior, I use command `docker compose restart` if you know hte conatainer name:
(docker ps) than you cloud do `docker restart <containername>`  from a CLI

**Comment by Smanar** [comment]
>simple question does the validator run on the |PR if I creat it?

> All checks have passed
> 2 successful checks
> @github-actions
> Verify DDF JSON / validate (pull_request) Successful in 6s
> [Details](https://github.com/dresden-elektronik/deconz-rest-plugin/actions/runs/7401026445/job/20166057464?pr=7511)
> @github-actions
> Verify button maps / build (pull_request) Successful in 12s
> [Details](https://github.com/dresden-elektronik/deconz-rest-plugin/actions/runs/7401026458/job/20166057474?pr=7511)

All is fine for me ^^

**Comment by CerealPT** [comment]
> > I noticed that when I restart the deCONZ addon in Homeassistant, the button_maps.json file inside the deCONZ docker container is overwritten and the mappings are lost. So I might not be updating the correct file.
> 
> defualt `docker compose DOWN` will remove the container inc your edits
> 
> That is docker behavior, I use command `docker compose restart` if you know hte conatainer name: (docker ps) than you cloud do `docker restart <containername>` from a CLI
> 
> other option is to map the changed files into your container so the will be there (mount -v option on docker)

Hi @noud-github!

Thanks for the hint!

I am now able to see the events inside Homeassistant, nevertheless I can't pick the right event id, in order to create an automation.

Is that something that needs to be done in the DDF?

**Comment by noud-github** [comment]
@CerealPT  I used this blueprint: https://github.com/noud-github/ha-blueprints

**Comment by CerealPT** [comment]
> @CerealPT I used this blueprint: https://github.com/noud-github/ha-blueprints
> 
> does a nice mapping between events and button names you can understand ;-)

Man....this is so sweet 🤟 
Made my life really easier!

Thanks a lot and hope to see all of these new developments on the new deconz release!

**Comment by ebaauw** [comment]
Picked one up today.  My observations:
- Indeed, it only reports button events through the 0xFC80 cluster.  Endpoint 0x01 is for the upper button (one dot); endpoint 0x02 for the lower button (two dots);  Binding the _On/Off_ or _Level Control_ clusters seems to have no effect?  From what I can tell, it sends the following commands from 0xFC80, which should be mapped to:
  Command | Action | Buttonevent
  -- | -- | --
  0x01 | Initial Press | x000
  0x02 | Hold | x001
  0x03 | Release (after press) | x002
  0x04 | Release (after hold) | x003
  0x06 | Double press | x004
- It does react to _Identify_, so should expose `config/alert`.
- The 0xFC80 bindings should go first; the device goes incommunicado without such binding.  Even pressing the link button won't wake it, but removing and re-inserting the battery will;
- It should expose `attr/productid`, after _Product Code_;
- _Image Type_ is 0x3B08.
- Maybe some setting on the (server) 0xFC80 cluster changes the behaviour for direct bindings of the (client) _On/Off_ and _Level Control_ clusters.  Need to check with the Dirigera hub.

**Comment by Smanar** [comment]
For supported command it use

```
            "map": [
                [1, "0x01", "FC80", "COMMAND_1", "0", "S_BUTTON_1", "S_BUTTON_ACTION_INITIAL_PRESS", "0x01"],
                [1, "0x01", "FC80", "COMMAND_2", "0", "S_BUTTON_1", "S_BUTTON_ACTION_HOLD", "0x02"],
                [1, "0x01", "FC80", "COMMAND_3", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "0x03"],
                [1, "0x01", "FC80", "COMMAND_4", "0", "S_BUTTON_1", "S_BUTTON_ACTION_LONG_RELEASED", "0x04"],
                [1, "0x01", "FC80", "COMMAND_6", "0", "S_BUTTON_1", "S_BUTTON_ACTION_DOUBLE_PRESS", "0x06"],
                [1, "0x02", "FC80", "COMMAND_1", "0", "S_BUTTON_2", "S_BUTTON_ACTION_INITIAL_PRESS", "0x01"],
                [1, "0x02", "FC80", "COMMAND_2", "0", "S_BUTTON_2", "S_BUTTON_ACTION_HOLD", "0x02"],
                [1, "0x02", "FC80", "COMMAND_3", "0", "S_BUTTON_2", "S_BUTTON_ACTION_SHORT_RELEASED", "0x03"],
                [1, "0x02", "FC80", "COMMAND_4", "0", "S_BUTTON_2", "S_BUTTON_ACTION_LONG_RELEASED", "0x04"],
                [1, "0x02", "FC80", "COMMAND_6", "0", "S_BUTTON_2", "S_BUTTON_ACTION_DOUBLE_PRESS", "0x06"]
            ]
        },
```

So all is fine, on this side.

**Comment by dklinger** [comment]
Can there be support added for the battery of the SOMRIG? It's currently showing 0%.

**Comment by Smanar** [comment]
You have just included it ? Can need time, because I m looking the DDF again, I don't see something bad.

**Comment by dklinger** [comment]
@Smanar Yes, I included it yesterday. How long can/should it take for the correct value to show up?

**Comment by Smanar** [comment]
Ha have see something, there is no poll in case the bind is not working
Can try to replace

```
        {
          "name": "config/battery",
          "refresh.interval": 86400,
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          }
        },
```

By

```
        {
          "name": "config/battery",
          "refresh.interval": 86400,
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          },
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl:attr"
          }
        },
```

After 24h if the bind is not working deconz will poll itself the device to have the value.

**Comment by DeviDarkL** [comment]
Hello, thank you for doing this integration. Battery still shows 0%. Will there be any fix?

**Comment by Smanar** [comment]
With the changes on previous post it still doesn't work ?

**Comment by DeviDarkL** [comment]
Hey, I am sorry but I am a total noob on this. I only added to deconz but neither the battery nor the button mapping works after adding the device. What DDF file are you using for this remote? Does someone has it with all the modifications from this conversation?

Best regards

**Comment by Smanar** [comment]
Make a try with this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/ikea/somrig_shortcut_button.json
And this changes https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7450#issuecomment-1983908694
