### ISSUE TITLE
IKEA Vallhorn motion sensor device request 

### ISSUE THREAD

**Issue by MagnusKazen** [dresden-elektronik/deconz-rest-plugin#7454]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

IKEA Vallhorn wireless motion sensor

### Manufacturer

IKEA of Sweden

### Model identifier

Vallhorn wireless motion sensor

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/0e0a4c17-50dc-407b-846e-dca6a6707e5e)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/cc7cdc19-a34b-4ad0-a437-d104b078b955)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/06e86fa8-6316-4b62-8e49-aa30f17a2461)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/c3d6ae48-784e-4975-b8db-6db1943cc2cc)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/e2d1ce5f-263e-41b5-81b9-7d3813ad2a90)
Just blank, seems to be no info here.
### Level Control
None
### Color Control
None
### Thermostat
None
### Simple Metering
None
### Electrical Measurement
None
### Any other cluster of relevance/interest
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/3348bc6d-283d-41c1-b777-4bd9ee73d605)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/06864be7-1dbb-403e-a970-e0429829f1b2)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/8797a38b-acb6-489a-819c-0680d86dbfe8)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/a6fba5d4-d499-4b9e-954c-a46934558ce3)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/48179782/05f12053-9389-455f-b111-68edcda6b285)

Just let me know if there is anything more You need. I'm pretty new at this...

**Comment by hyper2910** [comment]
any idea when Vallhorn is implemented?

**Comment by noud-github** [comment]
I made a DDF file and js file here

https://github.com/noud-github/deconz-rest-plugin/tree/vallhorn

not sure what the rules are for a PR, need to read up on that first ;-)

**Comment by Mimiix** [comment]
@noud-github  If you do a PR, theres a check automation running :)

@Smanar Perhaps you can help :)?

**Comment by Smanar** [comment]
I m answering on the PR page.

**Comment by hyper2910** [comment]
any update?

**Comment by Mimiix** [comment]
> any update?

Did you read the PR?

It has been merged. Support should be added in upcommimg 2.25.2.

**Comment by ebaauw** [comment]
(duplicate from my comment on the PR)

Finally managed to get hold of one of these.  As suggested by the screenshots, it's now a proper motion sensor on endpoint 0x02.  It sends "no more motion detected" events, and honours _PIR Occupied to Unoccuplied Delay_, which should be exposed as `config/delay` (cf. the Hue motion sensors).  As far as I can tell, it detects the next motion immediately after the delay has passed (so no cooldown period).

It still sends _On with Timed Off_ from endpoint 0x01, like the Trådfri motion "sensors" (or rather controllers).  It seems to use the configured _On Time_ before resending this command.  Haven't yet checked whether it still supports group bindings; if it does, we should expose `config/group`.

I think we should expose two ZHAPresence resources, one for the controller function on endpoint 0x01 (with `state/daylight`, `config/group`, and read-only `config/delay`, used for deCONZ to reset `state/presence`, cf the Trådfri motion "sensors") and one for the sensor function on 0x02 (with read/write `config/delay`, cf. the Hue motion sensors).

**Comment by Daniel-Ebert** [comment]
Hi there, I just also put mine into service and noticed, that the "Lux" information is always 0 in my case. Is this a known issue, or does the light sensor work for anybody?
I have version 2.25.2-beta installed (the first one adding "built in" support for Vallhorn)

Best regards

Daniel

**Comment by Daniel-Ebert** [comment]
Hi there @hyper2910 , thanks for your quick response! Did you also use the DDF delivered in the newest beta release, or did you use something from this thread here? And are you using the "official" LADDA batteries/ Batteries with 1,2V also specified in the manual? I've read in the Home Assistant forum, that Batteries with 1,5V do make VALLHORN behave weird.
(I currently have 1,5V ones installed)

**Comment by hyper2910** [comment]
Hi,

Using the ddfs from the thread, also using Lada Batteries. Still at 2.25.1

**Comment by marmic-hub** [comment]
They don't work for me either. I used the ddf from this thread.
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53650933/e2160546-e5e8-4883-880e-0d8e4d00d81e)

**Comment by Daniel-Ebert** [comment]
> Hi,
> 
> Using the ddfs from the thread, also using Lada Batteries. Still at 2.25.1

Okay, thanks for the information! I just bought 1,2V accumulators ( replacing the batteries with 1,5V I have put in initially) and I will update you if it works with them!
In these threads they have discussed it quite actively, that the Vallhorns seem to have problems with 1,5V batteries:
https://community.home-assistant.io/t/ikea-vallhorn-false-motion-detection/654298/22
https://forum.iobroker.net/topic/71681/gel%C3%B6st-ikea-vallhorn-bewegungsmelder-l%C3%B6st-st%C3%A4ndig-aus/21

**Comment by Daniel-Ebert** [comment]
I tested it with the 1,2V accumulators and at least for me the false detections disappeared (the sensor triggered approx. every minute falsefully with 1,5V alkalines).
The Lux sensor though does not work for me yet.

**Comment by marmic-hub** [comment]
I have 1.5V alkaline batteries in use and **no** false detections.
However, I do not get a the lux information either. 
Based on other posts, I assume that the sensor is simply not providing this information. 

It would be nice if someone could post a screenshot from deconz of a functioning lux display.

**Comment by SwoopX** [comment]
> It would be nice if someone could post a screenshot from deconz of a functioning lux display.

Please see the last screenshot of the first post showing the illuminance value.

**Comment by hyper2910** [comment]
![Screenshot_20240208_064843_Chrome](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/591f5a81-9555-41b8-b87a-1b0991aed497)
![Screenshot_20240208_064857_Chrome](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35178004/d77fb45e-f784-4515-a113-c269cb865c72)

**Comment by marmic-hub** [comment]
Thank you for the hint. I will check whether I need to do the binding again. Maybe that will solve the problem

**Comment by Daniel-Ebert** [comment]
Thanks for the provided steps to do this! Just to clarify for me: So the DDF is missing the binding information and in a future version this also will work automatically?

**Comment by SwoopX** [comment]
Correct. As part for illuminance measurement is entirely missing, there cannot be any set binding and reporting (except when added manually).

It's rather easy to add and once it is part of the DDF, it will be handles automatically.

**Comment by marmic-hub** [comment]
Perfect, it worked for me!
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53650933/393e0677-d811-49d7-8f6d-960c4aca2fb9)

**Comment by noud-github** [comment]
created a new PR with the add items

https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7584

**Comment by Daniel-Ebert** [comment]
Just as short feedback: Works perfectly with your new DDF-Additions in the latest beta :) 
Thank you very much again!

Best regards

Daniel
