### ISSUE TITLE
Request to add support for GLEDOPTO GL-S-004P

### ISSUE THREAD

**Issue by rstein5** [dresden-elektronik/deconz-rest-plugin#7455]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

GLEDOPTO GL-S-004P

### Manufacturer

GLEDOPTO

### Model identifier

GL-S-004P

### Device type to add

Light

### Node info

![GL-S_004P_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/44426c83-2003-4c68-b242-e5010885a280)

### Endpoints and clusters

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/1940cfe3-42c0-48ae-8843-0a1c32039fc5)
![GL-S-004P_4](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/0b58231b-67a1-4a86-bb22-619cc38343b0)
![GL-S-004P_5](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/826ae94e-73b4-4175-ad26-db7819b60fa4)
![GL-S-004P_6](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/92a1d4ad-8380-45b3-9aee-6d336db1148e)
![GL-S-004P_7](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/17ad63b2-ae87-4895-8854-633925dc2087)
![GL-S-004P_8](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/db6a0fc2-000f-4038-ad04-fcd554a25ead)
![GL-S-004P_9](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/dc05a58f-18a3-4fc7-bc47-17c791761cd3)
![GL-S-004P_10](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/d1c71238-77e3-4559-99e7-e154f5f1170a)
![GL-S-004P_11](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/6f895ac2-8c72-4290-b374-5ed63523eb03)
![GL-S-004P_12](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/5fc5fe43-d6a7-48a3-b62a-8e28d4567ebf)
![GL-S-004P_13](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/a07abc7a-cc2c-4ccf-ba45-8dfe4257f445)

### Basic

![GL-S-004P_2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/153868487/3b243900-567f-4954-9064-977f48e5bf3e)

**Comment by rstein5** [comment]
Diese RGBCCT Variante von ZigBee MR16 Spots arbeitet mit ZigBee 3.0 und ist so mit den gängigsten Gateways kompatibel.
Dieser Spot ist kann die Farbtemperatur zwischen 2200 und 6500 Kelvin einstellen sowie als RGB Farbwechsler, je nach Steuerung und Gateway auch zeitgleich um die Farbsättigung zu regulieren.

**Comment by Mimiix** [comment]
> Diese RGBCCT Variante von ZigBee MR16 Spots arbeitet mit ZigBee 3.0 und ist so mit den gängigsten Gateways kompatibel. Dieser Spot ist kann die Farbtemperatur zwischen 2200 und 6500 Kelvin einstellen sowie als RGB Farbwechsler, je nach Steuerung und Gateway auch zeitgleich um die Farbsättigung zu regulieren.

Please post in English.

**Comment by rstein5** [comment]
I translated the comment and uploaded the missing information. I hope they are complete now. Sorry, but it's my first post here
