### ISSUE TITLE
battery status

### ISSUE THREAD

**Issue by sanluca** [dresden-elektronik/deconz-rest-plugin#7456]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hi everyone,

I am unable to see the battery status of the two-button remotes. I have taken screenshots and attached the ddf file if anyone can help me.

Thanks in advance

`{
  "schema": "devcap1.schema.json",
  "manufacturername": [
    "_TZ3000_5e235jpa",
    "_TZ3000_t8hzpgnd",
    "_TZ3000_tzvbimpq",
    "_TZ3000_i3rjdrwu"
  ],
  "modelid": [
    "TS0042",
    "TS0042",
    "TS0042",
    "TS0042"
  ],
  "product": "Tuya remote 2 gangs",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/tuya/_TZ3000_TS0042_2gang_remote.json",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0006"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "refresh.interval": 86400,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 2,
      "dst.ep": 1,
      "cl": "0x0006"
    }
  ]
}`

### Steps to reproduce the behavior

the problem is always present

### Expected behavior

to see the battery status

### Screenshots

![Immagine3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14259923/2595d88c-99f4-48b2-adc4-0a9d01ae4372)
![battery](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14259923/ed5b652f-5ae2-4861-b316-041ec1e60e9f)
![Immagine](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14259923/fe24d9ff-11c1-4682-88d1-176a62a78a64)
![Immagine1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14259923/539bbce1-b0b6-4b1a-95b9-5770b0af4cb3)
![Immagine2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14259923/943ca535-d837-4b4e-a3b1-798123445692)

### Environment

deCONZ 2.4.2
ubuntu
openhab

**Comment by Smanar** [comment]
You haven't them direclty on the API too ?
It's a long story but there was 2  kind of device.

The old one need a battery bind, and not the second one else it cause battery drain, so was removed for all of them.

Can try ro add on your DDF

```
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3200,
          "max": 3600,
          "change": "0x00000002"
        }
      ]
    }
```

**Comment by sanluca** [comment]
Yes, my remote controls used to drain the battery immediately at first, so I guess I won't leave it without
thanks

**Comment by Smanar** [comment]
But on second version, with the battery drain, the report is automatic, you don't need the bind.

You haven't value after 24 ?

Try adding to the DDF

```
        {
          "name": "config/tuya_unlock"
        },
```

And re-include the device.

**Comment by sanluca** [comment]
I tried to modify it, but it drained the battery again, I'll leave it without battery control, maybe in the future I'll look for other remote controls, thanks
