### ISSUE TITLE
Status display bitron 902010/32 

### ISSUE THREAD

**Issue by dartoi** [dresden-elektronik/deconz-rest-plugin#7458]
### Describe the bug

Dears, I have a bitron 902010/32  thermostat, I have changed batteries but the show all symbols and not working. How could I fix it?
![camphoto_959030623](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/57129807/61456b1b-dea6-4358-b05c-6f0613de2dc2)

**Comment by Mimiix** [comment]
Hi

This issue does not belong here, nor did you fill the template.

Closing.
