### ISSUE TITLE
Philips Hue Centris 2-spot ceiling lamp

### ISSUE THREAD

**Issue by Finne75** [dresden-elektronik/deconz-rest-plugin#7470]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Philips Hue Centris 2-spot ceiling lamp

### Manufacturer

Philips

### Model identifier

5061030P7_01, 5061030P7_02, 5061030P7_03

### Device type to add

Light

### Node info

The lamp is a compound of three individual lights, two spots and one downlight. The model ID of each of the lights is as variant of 5061030P7 with a suffix _01, _02_, _03. E.g., in my case, 5061030P7_01 is the downlight. Apart of the model ID, the clusters of all lights are absolutely identically as far as I can see. I did some experimentation and with [this](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/philips/light_zb3_C.json) DDF, but the effects etc. don't seem to work.

See also: https://www.zigbee2mqtt.io/devices/5061030P7.html

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/e3cd8394-f03c-4f0c-b938-0312f98cce48)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/97996195-5741-4964-9e51-37564c75861e)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/67bf5ec1-58dd-428e-b30b-dbb2316dfb67)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/b29bfa82-e892-4000-aa7a-b2f7e4cea458)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/68c28c38-9840-4336-8d46-fcd411e723b4)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/be0860e0-14aa-4343-85eb-8082d40dda33)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/51132b3c-ba3e-4d17-b37a-8add96c0bdc7)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/d7b03709-5dab-4510-8e7a-7cb069c94030)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/2fc691b2-b0e2-4aef-b421-9e423bf9c5f3)

### Level Control
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/117ee79d-690c-47ec-b75b-8e71c88aa976)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/fa1dab56-773a-41bd-b952-1307ef6ae838)

### Color Control
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/6d390037-74b6-4dad-a119-0732829449dc)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/d8801a2a-2c26-4192-8745-34855b2fad48)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/ef109941-d2a5-4717-97e7-f697377cc2b9)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/1566df1c-ff2c-4359-894e-092930c3c473)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/98c3df99-33d7-4fb7-9442-e79a4cb5a672)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/afed6b6c-a2ad-4bf4-9e9a-8fa1362af227)

### Hue Entertainment Cluster
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/9f1761eb-e36f-4fc1-a46c-a13f018427db)

### Hue Effects Cluster
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76888443/e5b1c77a-6d90-48b8-9ad4-10c8c95a5cac)

**Comment by ebaauw** [comment]
The _Hue Effects_ cluster is missing.  You need to update the lights's firmwares (all three nodes separately).

**Comment by Finne75** [comment]
> The _Hue Effects_ cluster is missing. You need to update the lights's firmwares (all three nodes separately).

So I added one of them (_03) to the light_zb3_C.json DDF, and after reload, the Hue Effects Cluster appeared (see above). Can I update the firmware via deCONZ or do I need to use the Hue bridge?

**Comment by ebaauw** [comment]
You should be able to upgrade them through the deCONZ OTA plugin, or over Bluetooth, using the Hue app without a Hue bridge.  They probably won't upgrade to the latest version immediately; the upgrade might take several turns, and the _Image Type_ might change (to 0x011F) during this process.  In the end, _ZCL Version_ should be 8, and I expect the _SW Build ID_ to become 1.104.2.

I would expect them to be compatible with `light_zb3_C.json` after the upgrade.
