### ISSUE TITLE
bseed 3 gang switch tuya _TZ3000_xxxxxxxx TS0003 with new DDF is working

### ISSUE THREAD

**Issue by Onshuis** [dresden-elektronik/deconz-rest-plugin#7476]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

BSEED zigbee switch 3 gang Touch Smart

### Manufacturer

_TZ3000_eatarlvc

### Model identifier

TS0003

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/90712132/661dbbae-d6ea-45df-a0cd-1c5bc7ecd65b)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/90712132/29c28be8-0831-485f-adb2-f5694cbc12a3)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/90712132/0225fe69-2add-4cb1-b57d-7235144b6517)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/90712132/379b1fe2-fe57-437e-8d23-f56e896c8a41)

### Any other cluster of relevance/interest

The "On/Off light 35" in the screen shit is the same device. It is an inwall 3-gang switch. When i push the switches, it all works independently. 
If i switch within deCONZ, all 3 switches, switch at the same time.

**Comment by Onshuis** [comment]
Im happy though to see when i press the switch(light) from phoscon, only one gang is now operated instead of all 3!

Ok this seems the same as: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6682

So i changed the manufacturer and took the DDF json file inside :~/.local/share/dresden-elektronik/deCONZ/devices$
Restarted deconz and now i can individually switch the 3 gangs. 

But what to do next? Do i leave the DDF file, or what must i do?

**Comment by Mimiix** [comment]
> But what to do next? Do i leave the DDF file, or what must i do?

If you can: Make a PR out of it :)

**Comment by Onshuis** [comment]
No i dont know how, if i click new pull request it tells me to compare and everything is grayed out.

**Comment by Mimiix** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-create-a-pull-request-to-submit-a-new-Device-Description-File

There :)

**Comment by Onshuis** [comment]
Ok i did something, will do the same for the dimmer, thank you !

**Comment by Onshuis** [comment]
Ill keep using the DDF in my .local directory, it works fine this way.
