### ISSUE TITLE
Lightsensor Luxmeter Zigbee Tuya

### ISSUE THREAD

**Issue by ProductEigel** [dresden-elektronik/deconz-rest-plugin#7478]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Lightsensor Luxmeter Zigbee Tuya

### Manufacturer

_TZE200_khx7nnka

### Model identifier

TS0601

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/7574abea-e460-40c5-990f-c014ef18428d)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/d14f8b2f-4b14-4679-a3ba-22e68cd75617)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/b6ac7211-ef5e-4829-8448-307c20cb34f1)

**Comment by ProductEigel** [comment]
Noch nicht gelöst

**Comment by ProductEigel** [comment]
Noch nicht gelöst

**Comment by Mimiix** [comment]
@Smanar can you help out :)?

**Comment by Smanar** [comment]
Hello

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_khx7nnka", "_TZE200_yi4jtqq1"],
  "modelid": ["TS0601", "TS0601"],
  "product": "Tuya Lightsensor Luxmeter",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_LIGHT_LEVEL_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xEF00"
      ],
      "items": [
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "read": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr",
            "script": "tuya_swversion.js"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/dark"
        },
        {
          "name": "config/tholddark"
        },
        {
          "name": "config/tholdoffset"
        },
        {
          "name": "state/daylight"
        },
        {
          "name": "state/lightlevel"
        },
        {
          "name": "state/lux",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "script": "../generic/illuminance_cluster/lux_to_lightlevel.js",
            "fn": "tuya"
          },
          "default": 0
        }
      ]
    }
  ]
}
```

Just some remark:
This device is powered ? because it seem it can work as router ? Have set the "sleeper" mode to false.
To work this DDF NEED to be in the devices/tuya folder, because of relative path  `"script": "../generic/illuminance_cluster/lux_to_lightlevel.js",` if you are on docker, you can edit the path and copy too the file `lux_to_lightlevel.js` in the same folder

**Comment by ProductEigel** [comment]
@Smanar  
Hi I'm a bit confused right now :D what should I add where? I use Deconz as a container

**Comment by ProductEigel** [comment]
edit: 
Image: deconzcommunity/deconz:latest

**Comment by ProductEigel** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/3c84a362-ad43-4f99-9478-878ebb1f2977)

"script": "./lux_to_lightlevel.js",

doens't work...

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/9b8b5a8e-c1a2-430d-be38-c95ad0351999)

**Comment by ProductEigel** [comment]
i've tested also with a complett path, also with "/opt/deCONZ/devices/tuya/lux_to_lightlevel.js" or "/opt/deCONZ/devices/lux_to_lightlevel.js" or "/opt/deCONZ/lux_to_lightlevel.js"

**Comment by ProductEigel** [comment]
okay, I have found the error. The file must be called json not js

**Comment by Smanar** [comment]
You are using the official docker image ?

So when you make "ls -la" we need to see the *.js file and the *.json ?
And if both file are here you can just use

`"script": "lux_to_lightlevel.js",`

**Comment by ProductEigel** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/180ecd69-e39e-42af-972a-095cc701a4db)
but now the "lux" wont changed ....

**Comment by ProductEigel** [comment]
my mistake, I had named the DDF file "lux_to_lightlevel.js" :D and not after the device. I have now adjusted this so that there is no confusion. And yes I use the official Docker image, I just haven't found the "lux_to_lightlevel.js" yet and don't know the path either. I am an absolute newcomer to Deconz.

**Comment by ProductEigel** [comment]
@Smanar so I stole the "lux_to_lightlevel.js" from a Windows installation, but the device is still listed as a temperature controller and the display does not work. It always remains at 0 lux.

**Comment by Smanar** [comment]
>the device is still listed as a temperature controller

This is strange, can you take a look direclty in the API ? usig phoscon/help/API Information/sensors.

>It always remains at 0 lux

To make test withoutscript can you use instead
```
        {
          "name": "state/lux",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          },
          "default": 0
        }
```

You will need to  restart deconz after the change.

**Comment by ProductEigel** [comment]
{
    "config": {
        "on": true,
        "reachable": true,
        "tholddark": 12000,
        "tholdoffset": 7000
    },
    "etag": "06e57be68d9573ef96c4ed74dc4527e4",
    "lastannounced": null,
    "lastseen": "2024-02-16T19:11Z",
    "manufacturername": "_TZE200_khx7nnka",
    "modelid": "TS0601",
    "name": "Lichtsensor",
    "state": {
        "dark": false,
        "daylight": false,
        "lastupdated": "2024-02-16T19:11:45.128",
        "lightlevel": 0,
        "lux": 3
    },
    "swversion": "1.0.6",
    "type": "ZHALightLevel",
    "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
}

**Comment by ProductEigel** [comment]
and Events:

{
    "20:11:45:161": {
        "e": "changed",
        "id": "35",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-02-16T19:11:45.128",
            "lightlevel": 0,
            "lux": 3
        },
        "t": "event",
        "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
    },
    "20:11:59:706": {
        "e": "changed",
        "id": "35",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-02-16T19:11:59.656",
            "lightlevel": 0,
            "lux": 3
        },
        "t": "event",
        "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
    },
    "20:12:14:253": {
        "attr": {
            "id": "35",
            "lastannounced": null,
            "lastseen": "2024-02-16T19:12Z",
            "manufacturername": "_TZE200_khx7nnka",
            "mode": 1,
            "modelid": "TS0601",
            "name": "Lichtsensor",
            "swversion": "1.0.6",
            "type": "ZHALightLevel",
            "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
        },
        "e": "changed",
        "id": "35",
        "r": "sensors",
        "t": "event",
        "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
    },
    "20:12:14:256": {
        "e": "changed",
        "id": "35",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-02-16T19:12:14.185",
            "lightlevel": 0,
            "lux": 3
        },
        "t": "event",
        "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
    },
    "20:12:28:787": {
        "e": "changed",
        "id": "35",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-02-16T19:12:28.713",
            "lightlevel": 0,
            "lux": 3
        },
        "t": "event",
        "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
    },
    "20:12:43:231": {
        "e": "changed",
        "id": "35",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-02-16T19:12:43.241",
            "lightlevel": 0,
            "lux": 3
        },
        "t": "event",
        "uniqueid": "a4:c1:38:66:cf:78:e4:b0-01-ef00"
    }
}

**Comment by ProductEigel** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/63734865/5ba55f4f-4c07-456f-ae72-8a60a6487ef5)

**Comment by ProductEigel** [comment]
@Smanar the light is on, so it cannot be 0 lux

**Comment by ProductEigel** [comment]
@Smanar okay all commands back, it reacts now, although in my opinion with too little, it is displayed at full light 37Lux

**Comment by ProductEigel** [comment]
@Smanar thank you very much for your support :) the ticket can be closed :) have a nice weekend everyone ;)

**Comment by ProductEigel** [comment]
completed

**Comment by Smanar** [comment]
Lol, you was too fast for me.
On my last try the DDF just take a raw value and display it at lux and no more, so nothing in state/lightlevel for exemple.

**Comment by Idaho947** [comment]
Hello, can we reopen the ticket ? I've too off this sensor and still see as a plug...

**Comment by Smanar** [comment]
It's same manufacture name ? _TZE200_khx7nnka
Else better to open a new issue, or just add the new manufactureName at previous DDF to test if there are clone.

**Comment by Idaho947** [comment]
yes, it's exactly the same.
As the ddf isn't in a stable version and in view of your last message, I thought the integration wasn't complete.

**Comment by Smanar** [comment]
Oups sorry, my bad, have forget this device

**Comment by Smanar** [comment]
So have checked again, the first one need to work, it's a raw value for lux that can be converted for other field
```

{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_khx7nnka", "_TZE200_yi4jtqq1"],
  "modelid": ["TS0601", "TS0601"],
  "product": "Tuya Lightsensor Luxmeter",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_LIGHT_LEVEL_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xEF00"
      ],
      "items": [
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "read": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr",
            "script": "tuya_swversion.js"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/dark"
        },
        {
          "name": "config/tholddark"
        },
        {
          "name": "config/tholdoffset"
        },
        {
          "name": "state/daylight"
        },
        {
          "name": "state/lightlevel"
        },
        {
          "name": "state/lux",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "script": "../generic/illuminance_cluster/lux_to_lightlevel.js",
            "fn": "tuya"
          },
          "default": 0
        }
      ]
    }
  ]
}
```

With same requirement

> To work this DDF NEED to be in the devices/tuya folder, because of relative path "script": "../generic/illuminance_cluster/lux_to_lightlevel.js", if you are on docker, you can edit the path and copy too the file lux_to_lightlevel.js in the same folder


On your last try was just a "hack" to test code", so not good values.

**Comment by Idaho947** [comment]
Yes everything is fine ! It works perfectly.

**Comment by Smanar** [comment]
Wana make the DDF or want I make it ?

>turn of the bluelight

On the device ? I don't see something about that on this device ...

**Comment by Idaho947** [comment]
Yes... I put a scotch tape on it 😋

**Comment by Smanar** [comment]
Lool, I was searching zigbee features, there is guys doing same at my work for alarm "indicator light".

BTW do you want to submit the DDF, to have it officialy ?

**Comment by Idaho947** [comment]
Yes of course

**Comment by Smanar** [comment]
But do you want to make it yourself or want I make it ?

**Comment by Idaho947** [comment]
You can.
I will resend them to the seller in fact. The are ok when the lux is not 0. If the senser is in the dark, it send several message per second...

**Comment by Smanar** [comment]
if state/lux is 0 ?
Do you still have it ? It's possible to add a "filter" on the DDF. For exemple send update only if the value is different or > at a value.

**Comment by Idaho947** [comment]
Ok I can try

**Comment by Smanar** [comment]
You have a "spam" capture ?
To see what is the spammed request, and how to clock it ?

For exemple if it happen only if the state/lux  = 0 can use a check with the 0 value if it's just a spamming with the same value, can add a check that compare with prevous value and ignore it if it haven"t changed.

This code for exemple will work I think, replace

```
        {
          "name": "state/lux",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "script": "../generic/illuminance_cluster/lux_to_lightlevel.js",
            "fn": "tuya"
          },
          "default": 0
        }
```

by
```

        {
          "name": "state/lux",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "script": "{"fn": "tuya", "dpid": 2, "eval": "if R.item('state/valve').val != Attr.val {Item.val = Attr.val;}"}",
            "fn": "none"
          },
          "default": 0
        }
```

It's just a sample, it will update only state/lux with raw value, so "state/lightlevel" for exemple will stop working.
but if it work, it will block the  spam

**Comment by Idaho947** [comment]
It spam a lot when lux = 0 as you see in this logs :

`{
    "12:32:20:784": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:21.905",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:21:426": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:22.512",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:21:991": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:23.118",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:22:849": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:23.723",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:23:202": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:24.329",
            "lightlevel": 14625,
            "lux": 29
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:26:40": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:26.863",
            "lightlevel": 14625,
            "lux": 29
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:35:976": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:37.101",
            "lightlevel": 12042,
            "lux": 16
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:37:116": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:37.705",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:37:183": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:38.310",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:37:861": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:38.917",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:38:397": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:39.522",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:39:1": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:40.128",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:39:610": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:40.734",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:40:230": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:41.357",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:40:834": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:41.960",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:41:435": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:42.563",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:42:29": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:43.156",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:42:714": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:43.763",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:43:244": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:44.371",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:43:851": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:44.978",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:44:453": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:45.580",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:45:63": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:46.189",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:45:664": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:46.791",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:46:272": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:47.399",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:46:879": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:48.005",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:47:474": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": true,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:48.612",
            "lightlevel": 0,
            "lux": 0
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:48:77": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:49.215",
            "lightlevel": 13425,
            "lux": 22
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:48:735": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:49.833",
            "lightlevel": 14625,
            "lux": 29
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:49:777": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:50.909",
            "lightlevel": 13980,
            "lux": 25
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:50:384": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:51.516",
            "lightlevel": 13425,
            "lux": 22
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:50:980": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:52.118",
            "lightlevel": 13980,
            "lux": 25
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    },
    "12:32:51:685": {
        "e": "changed",
        "id": "657",
        "r": "sensors",
        "state": {
            "dark": false,
            "daylight": false,
            "lastupdated": "2024-04-27T10:32:52.724",
            "lightlevel": 14625,
            "lux": 29
        },
        "t": "event",
        "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
    }
}`

**Comment by Smanar** [comment]
It spam less with other value, but still spamming

```
  "12:32:23:202": {
    "e": "changed",
    "id": "657",
    "r": "sensors",
    "state": {
      "dark": false,
      "daylight": false,
      "lastupdated": "2024-04-27T10:32:24.329",
      "lightlevel": 14625,
      "lux": 29
    },
    "t": "event",
    "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
  },
  "12:32:26:40": {
    "e": "changed",
    "id": "657",
    "r": "sensors",
    "state": {
      "dark": false,
      "daylight": false,
      "lastupdated": "2024-04-27T10:32:26.863",
      "lightlevel": 14625,
      "lux": 29
    },
    "t": "event",
    "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
  },
```

>>With your new ddf, the lux doesn't change

Arf fuck, my fault, it's a copy/paste, can you replace

`"eval": "if R.item('state/valve').val != Attr.val {Item.val = Attr.val;}",`

by

`"eval": "if R.item('state/lux').val != Attr.val {Item.val = Attr.val;}",`

**Comment by Idaho947** [comment]
Not better with this ddf :

`{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_khx7nnka", "_TZE200_yi4jtqq1"],
  "modelid": ["TS0601", "TS0601"],
  "product": "Tuya Lightsensor Luxmeter",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_LIGHT_LEVEL_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xEF00"
      ],
      "items": [
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "read": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0000",
            "ep": 1,
            "fn": "zcl:attr",
            "script": "tuya_swversion.js"
          }
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/dark"
        },
        {
          "name": "config/tholddark"
        },
        {
          "name": "config/tholdoffset"
        },
        {
          "name": "state/daylight"
        },
        {
          "name": "state/lightlevel"
        },
        {
          "name": "state/lux",
          "read": {
            "fn": "none"
          },
          "parse": {
            "dpid": 2,
            "eval": "if R.item('state/lux').val != Attr.val {Item.val = Attr.val;}",
            "fn": "tuya"
          },
          "default": 0
        }
      ]
    }
  ]
}`

**Comment by Smanar** [comment]
I don't remember if you have access to the complete application ?
Perhaps something visible in log deconz/help/debug View with flag "DDF". Because all seem fine for me.

**Comment by Smanar** [comment]
I have made a synthax error, but I don't see my error, can you try with
`"eval": "if (R.item('state/lux').val != Attr.val) {Item.val = Attr.val;}",`

**Comment by Idaho947** [comment]
With you last code, the sensor spam when the lux = 0

**Comment by Idaho947** [comment]
It works but the change of the lux entitie is very long more tha 1 min.

The tuya sensor is not very compliant with the zigbee network

**Comment by Smanar** [comment]
But you have 2 devices like this one ?
the a4:c1:38...... is using the new DDF but the 04:cf:8c........ is still using another one.

>In HA the value doesn't change :

It's possible they are using state/lightlevel instead of state/lux ? Because they are using same API, not possible having different value on phoscon and HA.

On your log you have "-->undefined" probably because the value is ignored (not changed), it work because we can see lux=26 on the API, and just before it have worked for the 12 value.

But yes you still have lot of traffic, you are sure it's not the other device ? The 04:cf:8c........ ?
Can you check if you still have the "spam" on log ?

If the DDF is working (no more spam), yes, you can return thoses devices, not possible to set the reporting on this device, have checked Z2M too, if ignoring unchanged value don't work, I don't see what we can do ....

**Comment by Idaho947** [comment]
I have too of those device but delete the second one via the guid and reboot dexconz. I dont understand why it is already here.
Before the last change everything work in ha despite the spam.
The tuya is as the other of rhis brand cheap and create a lot of issue...

**Comment by Smanar** [comment]
But both are using the same DDF ? It's not possible, you haven't 2 similars device but using 2 different DDF ?

**Comment by Idaho947** [comment]
No I ve only one in my network. I dont understand what is the second one...

**Comment by Smanar** [comment]
It's a Xiaomi one according the mac adress.
But just remove the tuya one, look at traffic, and re-include it, to be sure it's the one that provole that.
And you still have the "spam" on logs ?

**Comment by Idaho947** [comment]
Yes I remove it and everything is fine. I reinclude it and the spam is here.

**Comment by Smanar** [comment]
And you still have spam like here

```
  "12:32:21:426": {
    "e": "changed",
    "id": "657",
    "r": "sensors",
    "state": {
      "dark": true,
      "daylight": false,
      "lastupdated": "2024-04-27T10:32:22.512",
      "lightlevel": 0,
      "lux": 0
    },
    "t": "event",
    "uniqueid": "a4:c1:38:9d:17:26:47:5c-01-ef00"
  },
  "12:32:21:991": {
    "e": "changed",
    "id": "657",
    "r": "sensors",
    "state": {
      "dark": true,
      "daylight": false,
      "lastupdated": "2024-04-27T10:32:23.118",
      "lightlevel": 0,
      "lux": 0
    },
```

Same value, in less than 1 s delay ?

This should not appear with the new DDF ...
