### ISSUE TITLE
innr SP 240 smart plug

### ISSUE THREAD

**Issue by baltena** [dresden-elektronik/deconz-rest-plugin#7479]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

SP 240 smart plug

### Manufacturer

innr

### Model identifier

SP240

### Device type to add

Switch

### Node info

![innr_node_info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/4b9c3971-7ef3-49b0-a9ab-866db4de4715)

### Endpoints and clusters

![innr_sp240_basic_cluster_info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/a50070f0-15a4-40b1-892b-0048452135ee)

### Basic

![innr_sp240_basic_cluster_info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/a50070f0-15a4-40b1-892b-0048452135ee)

### On/Off
![innr_sp240_cluster_onoff_info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/8f61851a-16c4-4994-a24b-8ac6a5fa7a1c)

### Simple Metering
![innr_sp240_cluster_simple_measuremens_info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/ac6f805b-40ae-4b8f-a96e-1e8bf19b2920)

### Electrical Measurement
![innr_sp240_cluster_electrical_measuremens_info_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/8c8d2b03-18bd-409d-b225-1cd336183c97)
![innr_sp240_cluster_electrical_measuremens_info_2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/b3bfa8d6-2c65-422a-82c5-95a9d5f7393c)
![innr_sp240_cluster_electrical_measuremens_info_3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/c4eb0dc8-9d3b-4e4d-8e39-80cd8e19244c)
![innr_sp240_cluster_electrical_measuremens_info_4](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/81caba24-54f5-4dd5-8e57-af8eb0a061f9)
![innr_sp240_cluster_electrical_measuremens_info_5](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5260499/95f2f8a7-7c5c-4938-ab42-30585905b4c4)

### Any other cluster of relevance/interest

**Comment by Smanar** [comment]
I m a bit affraid by the presence of the tuya cluster but have you tried a classic DDF like this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/innr/sp_120.json ?

With editing the modelid ?

**Comment by sven2c** [comment]
Hello,
I'm able to use the plug but just ON/OFF functionallity.
I'm using the API to control the plug via Node Red, but I'm not able to read out the Power Data.
Anyhow I'm including this in the DDF. 
I can see the Data working in the Deconz GUI, but the Phoscon RestAPI will not show up the sensor data

**Comment by Smanar** [comment]
There is a PR in waiting list for this device https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7486
