### ISSUE TITLE
Deconz (Conbee III) no longer recognize Aqara Smart Radiator Thermostat E1

### ISSUE THREAD

**Issue by Hanssie66** [dresden-elektronik/deconz-rest-plugin#7484]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I saw that deCONZ no longer recognize my Aqara Smart Radiator Thermostat E1 as a thermostat. At first I thought I had a problem with pairing. However, an in-depth analysis taught me that the thermostat did pair with the CONZ, but was not recognized as a thermostat. At first the thermostat was recognized as described [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6351). However, after a reset, the thermostat was no longer recognized as a thermostat (a lot of information had disappeared). How can I solve this issue? Or is this problem part of the deCONZ software?

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/154671623/e44707bb-f16f-46ce-baea-10e9a16ce60b)

### Steps to reproduce the behavior

1: Put thermosthat in pairing mode
2: select Thermostats and activate the button to Connect new thermostat
3: notting connected, however the pairing tree shows that the thermostat is paired 

### Expected behavior

The thermostat should be paired and recognized as thermostat and not as an unknown device. 

### Environment

- Host system: (Raspberry Pi 3B+)
- Running method: deCONZ Add-on
- Firmware version: (264D0900)
- deCONZ version (not Home assistant Addon version!): (2.24.2)
- Device:  ConBee III /
- Do you use an USB extension cable: yes 
- Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
Can you please retry with deconz v2.25.0?

**Comment by mendes588** [comment]
> ### Does the issue really belong here?
> 
>     * [x]  I definitively want to report a bug within deCONZ or its REST-API
> 
> 
> ### Is there already an existing issue for this?
> 
>     * [x]  I have searched the existing issues and there is none for the bug at hand
> 
> 
> ### Describe the bug
> 
> I saw that deCONZ no longer recognize my Aqara Smart Radiator Thermostat E1 as a thermostat. At first I thought I had a problem with pairing. However, an in-depth analysis taught me that the thermostat did pair with the CONZ, but was not recognized as a thermostat. At first the thermostat was recognized as described [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6351). However, after a reset, the thermostat was no longer recognized as a thermostat (a lot of information had disappeared). How can I solve this issue? Or is this problem part of the deCONZ software?
> 
> ![image](https://private-user-images.githubusercontent.com/154671623/292622536-e44707bb-f16f-46ce-baea-10e9a16ce60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MzQ0MzQsIm5iZiI6MTcwODczNDEzNCwicGF0aCI6Ii8xNTQ2NzE2MjMvMjkyNjIyNTM2LWU0NDcwN2JiLWYxNmYtNDZjZS1iYWVhLTEwZTlhMTZjZTYwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMDIyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDYwNTAzYzFlZjYyOGU1ZGM4NzdmMTc2NTcyNDUyZmE0N2MwYjNlMjU3MjZjZjFkZmQ2ZGU4ODFiOGRiYjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m8BUKsEqUNPkutL99GHABce3E60Bmm-ri2QWlBet40A)
> ### Steps to reproduce the behavior
> 
> 1: Put thermosthat in pairing mode 2: select Thermostats and activate the button to Connect new thermostat 3: notting connected, however the pairing tree shows that the thermostat is paired
> ### Expected behavior
> 
> The thermostat should be paired and recognized as thermostat and not as an unknown device.
> ### Screenshots
> 
> _No response_
> ### Environment
> 
>     * Host system: (Raspberry Pi 3B+)
> 
>     * Running method: deCONZ Add-on
> 
>     * Firmware version: (264D0900)
> 
>     * deCONZ version (not Home assistant Addon version!): (2.24.2)
> 
>     * Device:  ConBee III /
> 
>     * Do you use an USB extension cable: yes
> 
>     * Is there any other USB or serial devices connected to the host system? No
> 
> 
> ### deCONZ Logs
> 
> _No response_
> ### Additional context
> 
> _No response_

I can confirm the issue. It show's up on zigbee2mqtt but no values are shared and on the TRV itself the "connected" icon doesn't stay on (connected)
