### ISSUE TITLE
.deb Files for Ubuntu 16.04 or an [HowTo] for getting it compiled under Ubuntu.

### ISSUE THREAD

**Issue by Fl0ca** [dresden-elektronik/deconz-rest-plugin#749]
Hey everyone,
i would like to install deconz in an virtual maschine under esxi server, is it possible to get the binarys/.deb files for it too?
The .deb files you are sharing, are only for arm plattform and i ran into many failures during the try of compiling it myself. Maybe missing dependencies, i don't know.

The last failure was:
In file included from de_web_plugin_private.h:24:0,
                 from atmel_wsndemo_sensor.cpp:11:
./deconz.h:16:10: fatal error: deconz/types.h: Datei oder Verzeichnis nicht gefu                            nden
 #include <deconz/types.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile.Release:493: recipe for target 'release/atmel_wsndemo_sensor.o' failed
make[1]: *** [release/atmel_wsndemo_sensor.o] Error 1
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
In file included from de_web_plugin_private.h:24:0,
                 from authentification.cpp:13:
./deconz.h:16:10: fatal error: deconz/types.h: Datei oder Verzeichnis nicht gefu                            nden
 #include <deconz/types.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile.Release:475: recipe for target 'release/authentification.o' failed
make[1]: *** [release/authentification.o] Error 1
make[1]: Verzeichnis „/home/system21/deconz-rest-plugin“ wird verlassen
Makefile:40: recipe for target 'release' failed
make: *** [release] Error 2

Can you help me please, maybe an Tutorial for compiling or releases for x86_64 would be great.

regards

**Comment by ooii** [comment]
The ubuntu packages are available [here](https://www.dresden-elektronik.de/deconz/ubuntu/beta/).
