### ISSUE TITLE
New version of Hue Wall Switch (RDM004, 9290030171A)

### ISSUE THREAD

**Issue by koenheemskerk** [dresden-elektronik/deconz-rest-plugin#7490]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Philips Hue Wall Switch (2023)

### Manufacturer

Philips

### Model identifier

RDM004

### Device type to add

Switch

### Node info

![IMG_0546](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/39374992/42f98019-fa19-4883-baf9-276ecb02329c)

### Endpoints and clusters + Basic

<img width="797" alt="Screenshot 2023-12-29 at 22 41 46" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/39374992/cd0ed6e1-1c3b-4a4e-bbc0-d1a9d6cb1384">

<img width="492" alt="Screenshot 2023-12-29 at 22 45 06" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/39374992/76a405ff-6dc5-4f57-8b71-28d451d5caa6">

<img width="482" alt="Screenshot 2023-12-29 at 22 45 17" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/39374992/33af41e5-23bc-4623-8536-eebdc9e22574">

**Comment by Mimiix** [comment]
Can you please add all screenshots?

**Comment by ebaauw** [comment]
Where did you get it?  I cannot seem to find any mention of a new model.  Particularly interested to know if this model does support hybrid mode (as the previous model doesn’t).

**Comment by koenheemskerk** [comment]
Added the screens!

**Comment by Syorn630** [comment]
I've bought two of these RDM004 Philips hue wall switch modules this week as well and faced the same issue when trying to connect them to deconz via the Phoscon web app. Searching for a solution finally brought me here.

Has anybody an idea how to get the new version working? At least a quick fix? I've tried to copy the DDF file of the RDM001 version and just changed the Model ID. This got me one step further: the switch module now shows up in Phoscon but unfortunately it doesn't transmit anything when the switch is toggled.

When looking at the API events, every 5 minutes the following two events are received:

```
"16:26:27:436": {
    "attr": {
        "id": "6",
        "lastannounced": "2023-12-31T15:26:27Z",
        "lastseen": "2023-12-31T15:25Z",
        "manufacturername": "Signify Netherlands B.V.",
        "modelid": "RDM004",
        "name": "Switch 6",
        "productname": "Hue wall switch module",
        "swversion": "2.60.16",
        "type": "ZHASwitch",
        "uniqueid": "00:17:88:01:xxxx"
    },
    "e": "changed",
    "id": "6",
    "r": "sensors",
    "t": "event",
    "uniqueid": "00:17:88:01:xxxx"
},
"16:26:27:437": {
    "config": {
        "battery": 100,
        "devicemode": "singlerocker",
        "on": true,
        "reachable": true
    },
    "e": "changed",
    "id": "6",
    "r": "sensors",
    "t": "event",
    "uniqueid": "00:17:88:01:xxxx"
}
```

Additionally, if the switch was toggled, the first of the two event is received, but not more than once per minute.

Any ideas would be greatly appreciated.

**Comment by ebaauw** [comment]
> Particularly interested to know if this model does support hybrid mode (as the previous model doesn’t).

Yes, it does, see #7947.
