### ISSUE TITLE
Profalux ZigBee roller shutters

### ISSUE THREAD

**Issue by BEskandari** [dresden-elektronik/deconz-rest-plugin#7492]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Profalux ZigBee roller shutters

### Manufacturer

Profalux

### Model identifier

unknown

### Device type to add

Light

### Node info

![P2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/e60c0826-635f-4483-875a-4b597e4443ea)

### Endpoints and clusters

![P1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/6157c647-6087-4e78-b1be-b4204acd289f)

### Basic

![P3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/38c4ef6e-4f21-4e7e-9cf9-c2155ae4443a)

### Identify
![P4](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/0e834ab6-0bca-4b30-9026-611e62efa924)

### Groups
![P5a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/1b7fff69-3551-4902-86a8-79c946d50ec6)
![P5b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/acc61eec-364e-415f-b213-515e379d956a)

### Scenes
![P6a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/bfced7c1-8977-4e1e-bf8f-32e4c91967cd)
![P6b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/5f47501a-ad2f-4fa6-99dc-5f69ed67f784)
![P6c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/74c3a40f-6a83-4f5c-8354-4e245e2c6d06)
![P6d](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/05e3f901-8be3-47f9-b5cf-d576137c6215)

### On/off
![P7a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/d5791eff-04a0-47b4-adda-2c9a98ae1bb9)
![P7b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/506434f9-00a2-428b-a0e5-98ab02c1c718)

### Level Control
![P8a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/78053cf3-09ad-41d2-9355-5e0c7ddb86b9)
![P8b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/d64836cf-8e9c-40b2-bc67-e8a8e11ab860)

### Time
![P9](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/0f9ffd4a-e8c6-4e81-815e-e825244c22e6)

### Commissioning
![P10a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/c9318e46-3928-433a-ac04-184e2f1e9730)
![P10b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/926ddbf6-7d9f-4a20-a9e5-45258066e6f9)
![P10c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/e8241316-21ba-4c23-9ea2-ed6dfcfa9120)
![P10d](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/bd98b0ee-5756-4db4-b785-865244a9ccf0)
![P10e](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/09819e52-da32-455a-a7de-112faad808f4)
![P10f](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/15ad9191-3a40-4191-b751-e187c848a03c)
![P10g](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/e0e732f7-e02a-48d5-a17b-1518cd7ababe)
![P10h](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/fe06b287-4550-498b-bacd-80dbcc2a44c6)

### Shade Configuration
![P11](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/15bc39c8-96a7-4e36-8c9f-ff45bff2507d)

**Comment by BEskandari** [comment]
The device was configured without DDF in previous version by @Smanar https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2739

**Comment by Smanar** [comment]
It seem he have a strange version, without manufacture name and without Modelid.
If it's not a bug, not possible to include this model. Deconz need them to reconise the device.

**Comment by BEskandari** [comment]
Thanks, I have found this on other communities:
"manufId":4368,"manufName":"Profalux"
But I have to check with the vendor to see if there is an issue on that.

**Comment by Smanar** [comment]
Oups, @BEskandari is right I have just see a "hack" in the code to support this device, with missing information.

```
        //Add missing values for Profalux device
        if (existDevicesWithVendorCodeForMacPrefix(node->address(), VENDOR_PROFALUX))
        {
            //Shutter ?
            if (i->deviceId() == DEV_ID_ZLL_COLOR_LIGHT)
            {
                lightNode.setManufacturerName(QLatin1String("Profalux"));
                lightNode.setModelId(QLatin1String("PFLX Shutter"));
                lightNode.setNeedSaveDatabase(true);
            }
        }
```

So to work the device need to have
- Manufacture number 0x1110
- Device type DEV_ID_ZLL_COLOR_LIGHT
- Router device.

But this code is perhaps disabled with DD core, you can try to disable it, time to include the device.

**Comment by BEskandari** [comment]
Thanks @Smanar , but this is beyond my knowledge, I will follow your instructions in case to check the DDF and make it work.

**Comment by BEskandari** [comment]
> Just disable the DDF core, include your device with the legacy core, then re-enable DDF.

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/f864ce10-f292-495d-8bba-32077b3c06c1)

I don't see the option to disable DDF as mentioned in previous post by you by selecting "Draft". And last but not least how can I be sure that the node is included with the legacy code. Because now I have it in the deCONZ-gui but no mention in the API's.
