### ISSUE TITLE
Blind roller _TZE200_libht6ua TS0601

### ISSUE THREAD

**Issue by TonKro** [dresden-elektronik/deconz-rest-plugin#7494]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tuya brand zigbee blind motor 

### Manufacturer

_TZE200_libht6ua

### Model identifier

TS0601

### Device type to add

Other

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/69176976-0ecb-457e-b008-842b79aad4f1)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/534d4d17-5a41-4447-91b1-64b2ea77cc94)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/5ebb95cd-4b73-4d64-bd5e-c888901fa54c)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/8d43e40d-a436-4bf8-8c2f-f3c0e1246dce)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/7f12fc9e-bd54-4e6c-a0ef-600da2a339ca)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/ef766da5-6841-48a3-8b90-3bbf54bb689d)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/fee7e62d-3fc6-42fe-83f3-eb9e40faedfb)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65308845/2cfdcfdc-af74-4bde-84e2-78dfd1b3e3c7)

### Further relevant clusters

There is a js version available for this device for zigbee2mqtt

https://github.com/javilopezalarcon/Blind-motor-_TZE200_libht6ua-z2m/blob/main/README.md

**Comment by Mimiix** [comment]
Please add all screenshots

**Comment by TonKro** [comment]
Can you help me what is missing and needed?

**Comment by Mimiix** [comment]
Please add the screenshots in the first post.

**Comment by TonKro** [comment]
Tnx, all pictures are brought to the inititial request.

**Comment by Mimiix** [comment]
> Is there any expectation to make? Or is Zigbee2MQTT or ZHA a better solution?

Someone needs to help.

Nevertheless, it has been holidays and a lot of people are off.
