### ISSUE TITLE
Heiman RC-EF-3.0 keyfob not found

### ISSUE THREAD

**Issue by vdiogo** [dresden-elektronik/deconz-rest-plugin#7496]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I am trying to join a Heiman RC-EF-3.0 keyfob which as per https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3828 seems to be supported since 2.10, however I'm not able to get it mapped it in deconz, neither it shows up in the Phoscon app

### Steps to reproduce the behavior

1. Open deconz
2. Search for the keyfob
3.  Open Phoscon
4. Add new sensor

### Expected behavior

From reading the referenced issues, it should be supported since Phoscon 2.10

### Screenshots

This is the Deconz node:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/0aa13de4-59c1-4711-a605-ecc0924bb13e)

### Environment

- Host system: (Raspberry Pi)
- Running method: (Home Assistant deCONZ Add-on)
- Firmware version: (26720700)
- deCONZ version (not Home assistant Addon version!): (2.22.02)
- Device: (ConBee II)
- Do you use an USB extension cable: (yes)
- Is there any other USB or serial devices connected to the host system? If so: Which? Yes, external SSD

### deCONZ Logs

Cannot find any relevant logs

### Additional context

N/A

**Comment by SwoopX** [comment]
Hm, one caveat of the legacy code is that it heavily depends on specifics of the device, such as MAC prefix, manufacturer code, etc. Presumably, in this case the device has a different manufacturer code than expected.

Could you check if a DDF setup is suggested already if you right click on the node and go in the DDF Editor?

**Comment by vdiogo** [comment]
> Could you check if a DDF setup is suggested already if you right click on the node and go in the DDF Editor?

Thanks for looking into this. I don't think it does:
<img width="2205" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/24878195/3670d923-c24b-406d-b473-179e8d36f7ca">
