### ISSUE TITLE
LIDL SilverCrest Smart plug

### ISSUE THREAD

**Issue by Brian-lub** [dresden-elektronik/deconz-rest-plugin#7512]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

SilverCrest Smart plug HG08673-DK
IAN 383853_2110 SAZ1 A2

![20240103_204301](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/cb8b1485-f183-40a0-9905-a1d03496a1d9)

### Manufacturer

_TZ3000_nkcobies

### Model identifier

TS011F

### Device type to add

Light

### Node info

![node info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/43d8920d-7e38-4515-bfd6-134837b98015)

### Endpoints and clusters

![Cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/28d6f16e-44ca-443a-b6e0-3a10ff327fbd)

### Basic

![Basic cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/d062751e-1ba8-447a-afd2-fab9b1431acc)

### Any other cluster of relevance/interest
![overveiw](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/96db952d-e051-4768-ab9c-24b030ac6176)
![items](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/f6d91d25-90ec-4de9-b3e1-bfa75294e7ae)
![ddf](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/38675575-e50f-4324-bcf9-1f0c203f2829)
![identyfyer cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/32e66784-1149-42d8-b01c-e5875f9b0d7a)
![group cluster 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/0cd06e1c-b7bd-46e5-95ec-adf6e37ff46b)
![group cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/2a9cd0ad-7b53-4186-8f67-c01c696822fa)
![scene cluster 3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/0e5a73cf-d260-4443-8cd2-ea4fa064f343)
![scene cluster 2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/7ba26443-00eb-453b-bf16-8a89abfc4add)
![scene cluster 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/6846739c-0e2c-4031-a1e1-43a854c5d628)
![scene cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/f292403a-7bc8-4a58-8bc6-bd6e5c442000)
![on-off cluster 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/01514a7f-404b-4104-a972-6a7f5a2506af)
![on-off cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/df373d78-72c9-42e6-b403-bee66c45e8bc)
![simple metering cluster 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/3f23cfba-c883-450d-acb9-a5a87c6180e7)
![simple metering cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/657f5ea4-7873-4b83-a7d0-1740df16c6a0)
![electric measurement cluster 3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/9dcb45c1-b92b-4bfc-a91b-4b35e68c0900)
![electric measurement cluster 2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/905b45f3-ad79-4e1c-a2e2-774c3096b45f)
![electric measurement cluster 1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/dfe89ed8-61a1-4c9a-9628-c9b24986c510)
![electric measurement cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/29ccd7ea-2aef-4d38-b890-780a691c5079)
![tuca cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/c13e0fab-a545-416b-8a8b-e934237be263)

**Comment by Brian-lub** [comment]
Please let me know if you need more, i will be happy to help and test the device

**Comment by Mimiix** [comment]
@Smanar can you check :)?

**Comment by Smanar** [comment]
But I m seing this device in the DDf list https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/lidl/hg08673.json

Why deconz don't pick it ? what is your deconz version ?

**Comment by Brian-lub** [comment]
Im using HA addon deConz Current version: 6.22.0

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/68043cdf-081f-4a63-a0f4-0e81859df8ef)

**Comment by Smanar** [comment]
Can you take a look in phoscon/gateway to see wich one deconz version they are using ?
This device was enabled (gold status) in version v2.25.0-beta

**Comment by Brian-lub** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/47833231/58b377d8-891c-461e-b65f-ce73937e3404)

**Comment by Smanar** [comment]
You can see it in phscon too ^^, perhaps easier than lanching the GUI ?

But you haven't a recent enought version.
You can probably turn the status to "Gold" but at next restart it will return to "silver".
Perhpas in deconz setting on tab "control" lower the DDF level to "gold" from "Silver". On previous version, 2 month old , the DDF was "silver", but honnestly I havent checked the DDF state on 2.22 version (we are ATM on 2.25)

**Comment by Brian-lub** [comment]
i have state draft in DDF

**Comment by Mimiix** [comment]
> i have state draft in DDF. Do you have any influence on the HA add on?

Closing as it's a duplicate
