### ISSUE TITLE
Power monitor support requested for _TZ3000_kqvb5akv

### ISSUE THREAD

**Issue by Obelixje** [dresden-elektronik/deconz-rest-plugin#7524]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Mini Zigbee Switch 

### Manufacturer

_TZ3000_kqvb5akv

### Model identifier

TS0001

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/f4455930-3c4b-4012-875f-eab6093d53b7)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/b498ce8c-a157-4cbd-bdad-493ec2d9393a)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/cb054acb-c873-42c0-a5d7-2b759a745b7a)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/830930f8-d2ae-42ee-a532-2c551319dfce)

### Simple Metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/451bc30e-fc6b-4411-9186-da40bcbb4627)

### Electrical Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/dbdfe067-1945-441d-9065-5e41932ff148)

**Comment by Obelixje** [comment]
Endpoint:  

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/83656588/ce7dd0de-7ea6-44e9-a7b7-169df9ed2346)

**Comment by Mimiix** [comment]
@Smanar Can you take a look :)?

**Comment by Smanar** [comment]
It's a 1 gang switch wired ?

Can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZ3000_mkhkxx1p", "_TZ3000_tgddllx4", "_TZ3000_g92baclx", "_TZ3000_mkhkxx1p", "_TZ3000_tgddllx4", "_TZ3000_kqvb5akv"],
  "modelid": [ "TS0001", "TS0001", "TS0001", "TS0001", "TS0001", "TS0001"],
  "product": "1 gang wired switch",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "default": "none"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "refresh.interval": 360,
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "eval": "Item.val = 10*Attr.val"
          },
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "../tuya/tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360,
          "default": 0
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 360,
          "default": 0
        },
        {
          "name": "state/voltage",
          "refresh.interval": 360,
          "default": 0
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 5,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 15,
          "max": 500,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 15,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 5,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

Values power, current voltage consumption will need to be corrected (*10 or /10) but they are not visible on the capture.
So just tell me the value you have and the one you need for I make adapatation.

**Comment by Obelixje** [comment]
Hi @Smanar ,

Thank you for your help.
I am currently at my work. I have access to HA, bot I am not able to copy this ddf file to the correct folder in Deconz environment.
So I think I have to test this from home tomorrow.

**Comment by Smanar** [comment]
Ha yes on HA
Short way > need to install the DDF in /.local/share/dresden-elektronik/deCONZ/devices
long way > https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by Obelixje** [comment]
@Smanar 
Hi Smanar,

I am still not able to find the corret folder. My Deconz is installed on a HASSOS RPi,
Can you help me access the correct folder?

**Comment by Smanar** [comment]
No sorry, I don't use docker on my side.
But the previous link is just for HA without external deconz docker.

**Comment by Onshuis** [comment]
I have exactly the same device. I tried the DDF. I now see consumption, but ... the mini switch is still a light. When i press in phoscon on the light, the blue led on the mini is flasing, but the relais will not turn on. When i manually press the button on the mini switch, the relay goes on and i see the icon in foscon change to on status. So when using the DDF i got some consumption but i am unable to control the switch from the phoscon app.

**Comment by Smanar** [comment]
>the mini switch is still a light

Yes, it's not normal ? It's not  a plug ?

>Also the consumption of my soldering iron is only 25W

25W is a power, not a consumption. But the DDF can need adjustement, easy to correct, you are looking power or consumption ?

>When i press in phoscon on the light, the blue led on the mini is flasing, but the relais will not turn on

Not good, I can have forget the tuya unlock sequence. Can try with adding on the `$TYPE_ON_OFF_LIGHT`
```
        {
          "name": "config/tuya_unlock"
        }
```
(Take care at comma)

**Comment by Onshuis** [comment]
Okay, i added in "name": "config/tuya_unlock" under $TYPE_ON_OFF_LIGHT but i have a whole ohter problem now. So trying to fix this first i will get back on it. But im now unable to login to phoscon. I just get a black page with the P logo. So yes, im looking into tjis first and then ill come back to here. But thanks for the help so far.

**Comment by Onshuis** [comment]
Ah ok, i found some old issue where it logs into ...login2.html so in my address bar it says ....login.html i changed it manually to login2.html and now it works again. So im able to login again. Never had the issue, but now i know to chage it manually to login2.html i can at least login again. Different issue, so now back on  "name": "config/tuya_unlock" i will put this line in and wait for 24 hours to see what will happen. See you in 24 hours again.

**Comment by Onshuis** [comment]
25W is a power, not a consumption. But the DDF can need adjustement, easy to correct, you are looking power or consumption ?
Well normally it's both. I can see the actual power and also the consumption. 

So now i have it set as an plug, just like other power measurement switches i have.
On deCONZ i can see id0x0300 unit of measurement kW & kWh binairy.
In the electrical measurment cluster on id 508 and id 50B i can see rms 203 and active power 16.
However in the phoscon app there is no measurment of anything. There is meaurment for all the other power measurement switches i have.

I just do not know what to change in the DDF to make it all correct. I have deCONZ, phoscon and domoticz. 
In deconz i can see some values, in phoson there is nothing of measurement and in domoticz i see my soldering iron is taking 17watts.

What must i change in the ddf?

Im using this now for power measure to work:

`{
    "schema": "devcap1.schema.json",
    "manufacturername": ["_TZ3000_rmjr4ufz", "_TZ3000_kqvb5akv"],
    "modelid": "TS0001",
    "product": "Random tuya plug",
    "sleeper": false,
    "status": "Gold",
    "subdevices": [
      {
        "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
        "restapi": "/lights",
        "uuid": [
          "$address.ext",
          "0x01"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "state/alert",
            "description": "The currently active alert effect.",
            "default": "none"
          },
          {
            "name": "state/on"
          },
          {
            "name": "state/reachable"
          }
        ]
      },
      {
        "type": "$TYPE_CONSUMPTION_SENSOR",
        "restapi": "/sensors",
        "uuid": [
          "$address.ext",
          "0x01",
          "0x0702"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "config/on"
          },
          {
            "name": "config/reachable"
          },
          {
          "name": "state/consumption",
          "read": {"at": "0x0000", "cl": "0x0702", "ep": 1, "fn": "zcl:attr" },
          "parse": {"at": "0x0000", "cl": "0x0702", "ep": 1, "eval": "Item.val = Attr.val * 10"},
          "refresh.interval": 365
        },
          {
            "name": "state/lastupdated"
          }
        ]
      },
      {
        "type": "$TYPE_POWER_SENSOR",
        "restapi": "/sensors",
        "uuid": [
          "$address.ext",
          "0x01",
          "0x0b04"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "config/on"
          },
          {
            "name": "config/reachable"
          },
          {
            "name": "state/current"
          },
          {
            "name": "state/lastupdated"
          },
          {
            "name": "state/power"
          },
          {
            "name": "state/voltage"
          }
        ]
      }
    ],
    "bindings": [
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0006",
        "report": [
          {
            "at": "0x0000",
            "dt": "0x10",
            "min": 1,
            "max": 1800
          }
        ]
      },
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0702",
        "report": [
          {
            "at": "0x0000",
            "dt": "0x25",
            "min": 1,
            "max": 300,
            "change": "0x0000000A"
          }
        ]
      },
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0B04",
        "report": [
          {
            "at": "0x0505",
            "dt": "0x21",
            "min": 1,
            "max": 500,
            "change": "0x00000003"
          },
          {
            "at": "0x0508",
            "dt": "0x21",
            "min": 1,
            "max": 300,
            "change": "0x0000000F"
          },
          {
            "at": "0x050B",
            "dt": "0x29",
            "min": 1,
            "max": 300,
            "change": "0x00000003"
          }
        ]
      }
    ]
  }
`

**Comment by Onshuis** [comment]
Ok now it is working all, with power measurement and consumption. Im sorry to post in an already closed post. I am out of here now. Glad all is working. Thanks though.

**Comment by Obelixje** [comment]
Hi,

Can you please share the ddf you are now using?

**Comment by Smanar** [comment]
```
          {
          "name": "state/consumption",
          "read": {"at": "0x0000", "cl": "0x0702", "ep": 1, "fn": "zcl:attr" },
          "parse": {"at": "0x0000", "cl": "0x0702", "ep": 1, "eval": "Item.val = Attr.val * 10"},
          "refresh.interval": 365
        },
```

To correct consumption

```
          {
            "name": "state/power",
            "read": {"at": "0x050b", "cl": "0x0b04", "ep": 1, "fn": "zcl:attr" },
            "parse": {"at": "0x050b", "cl": "0x0b04", "ep": 1, "eval": "Item.val = Attr.val * 10"},
            "refresh.interval": 365
        },
```

For power
Just need to edit the "*10", save the file and restart deconz, can use the "hot reload" if doing with editor, but better to use text editor.

But take care, the actual DDF is "normaly" working, so you can have a special clone with different convertion, if yes better to create another DDF just for your device.

@Obelixje you have same issue ?

**Comment by Onshuis** [comment]
Im sorry, i do not know anymore. I have several devices, looking the same. Some of them worked with power measure consumption. Some of them didn't. I thought let's get the others working too, but now when i pair "_TZ3000_kqvb5akv" which is a TS0001, the "_TZ3000_xkap8wtb" which is a TS000F disappears to offline. Then when i remove the DDF of the  "_TZ3000_kqvb5akv" restart deconz "_TZ3000_xkap8wtb" re-appears again, but when i try to read values it keeps saying reading.... in deCONZ, but in phoscon it is online and i can see it. But here is the DDF i try to use for the "_TZ3000_kqvb5akv"

{
    "schema": "devcap1.schema.json",
    "manufacturername": "_TZ3000_kqvb5akv",
    "modelid": "TS0001",
    "product": "Random tuya plug",
    "sleeper": false,
    "status": "Gold",
    "subdevices": [
      {
        "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
        "restapi": "/lights",
        "uuid": [
          "$address.ext",
          "0x01"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "state/alert",
            "description": "The currently active alert effect.",
            "default": "none"
          },
          {
            "name": "state/on"
          },
          {
            "name": "state/reachable"
          }
        ]
      },
      {
        "type": "$TYPE_CONSUMPTION_SENSOR",
        "restapi": "/sensors",
        "uuid": [
          "$address.ext",
          "0x01",
          "0x0702"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "config/on"
          },
          {
            "name": "config/reachable"
          },
          {
          "name": "state/consumption",
          "read": {"at": "0x0000", "cl": "0x0702", "ep": 1, "fn": "zcl:attr" },
          "parse": {"at": "0x0000", "cl": "0x0702", "ep": 1, "eval": "Item.val = Attr.val * 10"},
          "refresh.interval": 365
        },
          {
            "name": "state/lastupdated"
          }
        ]
      },
      {
        "type": "$TYPE_POWER_SENSOR",
        "restapi": "/sensors",
        "uuid": [
          "$address.ext",
          "0x01",
          "0x0b04"
        ],
        "items": [
          {
            "name": "attr/id"
          },
          {
            "name": "attr/lastannounced"
          },
          {
            "name": "attr/lastseen"
          },
          {
            "name": "attr/manufacturername"
          },
          {
            "name": "attr/modelid"
          },
          {
            "name": "attr/name"
          },
          {
            "name": "attr/swversion"
          },
          {
            "name": "attr/type"
          },
          {
            "name": "attr/uniqueid"
          },
          {
            "name": "config/on"
          },
          {
            "name": "config/reachable"
          },
          {
            "name": "state/current"
          },
          {
            "name": "state/lastupdated"
          },
          {
            "name": "state/power"
            "read": {"at": "0x050b", "cl": "0x0b04", "ep": 1, "fn": "zcl:attr" },
            "parse": {"at": "0x050b", "cl": "0x0b04", "ep": 1, "eval": "Item.val = Attr.val * 10"},
            "refresh.interval": 365
        },
          {
            "name": "state/voltage"
          }
        ]
      }
    ],
    "bindings": [
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0006",
        "report": [
          {
            "at": "0x0000",
            "dt": "0x10",
            "min": 1,
            "max": 1800
          }
        ]
      },
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0702",
        "report": [
          {
            "at": "0x0000",
            "dt": "0x25",
            "min": 1,
            "max": 300,
            "change": "0x0000000A"
          }
        ]
      },
      {
        "bind": "unicast",
        "src.ep": 1,
        "cl": "0x0B04",
        "report": [
          {
            "at": "0x0505",
            "dt": "0x21",
            "min": 1,
            "max": 500,
            "change": "0x00000003"
          },
          {
            "at": "0x0508",
            "dt": "0x21",
            "min": 1,
            "max": 300,
            "change": "0x0000000F"
          },
          {
            "at": "0x050B",
            "dt": "0x29",
            "min": 1,
            "max": 300,
            "change": "0x00000003"
          }
        ]
      }
    ]
  }

I don't know anymore. Some strange behavior is going on here.
