### ISSUE TITLE
Add DDF for Aqara (Xiaomi) Smart Switch WXKG11LM Rev 2

### ISSUE THREAD

**Issue by wegi95** [dresden-elektronik/deconz-rest-plugin#7529]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

The switch was working fine so far, but all of a sudden, it seemed like something was missing.
Therefore, I got this message in the deconz-homebridge log: 
_[deCONZ] Phoscon-GW: warning: Smart Switch: exposed by legacy code_

It is possible to connect the switch to the phoscon-gw itself, but it won't be exposed to Apple HomeKit.
I know, this is not the place to ask for HomeKit/Homebridge support, but the warning "exposed by legacy code" is only displayed, when DDF for this device is missing (https://github.com/ebaauw/homebridge-deconz/issues/180).

The problem also exists with the v2.25.1 beta installed.

### Steps to reproduce the behavior

-

### Expected behavior

-

### Environment

- Host system: Raspberry Pi
- Running method: Raspbian
- Firmware version: -
- deCONZ version: 2.25.1
- Device: ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? No

**Comment by SwoopX** [comment]
No bug here, questions can be asked in the forum.
