### ISSUE TITLE
Support for new Namron 8 button switch

### ISSUE THREAD

**Issue by joernnilsson** [dresden-elektronik/deconz-rest-plugin#7533]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Zigbee Channel Switch

### Manufacturer

Namron AS

### Model identifier

4512772

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/521757/bd861577-d519-4d0e-a5c6-2a70a3564b8f)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/521757/d19db2e6-1e58-45f4-b1ba-c2ee14094589)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/521757/c3416baf-22b3-4eb4-9091-0a9c9ea738fa)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/521757/6c281400-7d3c-400d-a199-1074f0d2ec11)

There are 4 basic clusters, they repeat the same information

### Further relevant clusters

Power
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/521757/76d29ef3-361a-4506-b5bf-4fe85013e4d3)

Diagnostic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/521757/9307ff60-3179-4773-bc94-418e6e0af80a)

Manufacturor page and user manual:
https://www.namron.com/products/namron-zigbee-kanalbryter-hvit/
https://www.elektroimportoren.no/docs/lib/4512772-Brukerveiledning-5.pdf

This appears to be a new version of Namron's 8 button switch. The old one appears in Phoscon as expected.

**Comment by joernnilsson** [comment]
bump

**Comment by Mimiix** [comment]
@Smanar Perhaps you want to check?

**Comment by Smanar** [comment]
This one don't have dimmer like the 4512721 ?
Because both device relay look same (zigbee side speaking)
Can make a try just with adding the model in this DDF `devices\sunricher\8button_switch.json`

And in buttonmap file here

```
        "sunricherMap": {
            "vendor": "Sunricher",
            "doc": "Wireless switches from Sunricher, Namron, SLC and EcoDim",
            "modelids": ["ED-10010", "ED-10011", "ED-10012", "ED-10013", "ED-10014", "ED-10015", "ZG2833K2_EU07", "ZG2833K8_EU05", "ZG2833K4_EU06", "ZG2835", "4512701", "4512702", "4512703", "4512705", "4512719", "4512721", "4512728", "4512729", "S57003", "ROB_200-008", "ROB_200-009-0", "ROB_200-008-0", "ROB_200-007-0"],
            "buttons": [
```

**Comment by joernnilsson** [comment]
I can confirm that the two changes works perfectly :tada: 

Thank you very much @Smanar and @Mimiix.

I've created a PR with the changes: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7615
