### ISSUE TITLE
Schneider Electric / Merten Raumtemperaturregler-Modul, polarweiss, System M, ZB

### ISSUE THREAD

**Issue by sdriesche** [dresden-elektronik/deconz-rest-plugin#7539]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Connected Raumtemperaturregler- Modul, polarweiss, System M, ZB

### Manufacturer

Schneider Electric

### Model identifier

MEG5779

### Device type to add

Thermostat

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/a1edaa4c-b23b-4abc-bfa6-6937c1dbbcb7)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/026b7555-3553-4abc-b190-ee4bc34a18b1)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/d9c46f52-cac5-4d99-a7c4-b4529796856c)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/7e96f76e-1531-4266-81cf-e5bca4c06b56)

### Thermostat
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/56250fb1-11aa-4b2e-8f0f-ab8ba13b1cc7)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/6b0b6d8b-cf70-4716-9675-1dcfed1a2762)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/079c5602-98b1-4e21-b5c9-317dea1dc6bf)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/3a15087d-080a-42db-8e50-6ece597abe09)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/c50699cd-50cd-4cf3-9694-d5715181b854)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/876507ef-b013-495e-8153-d7fa67adfaa8)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/3c18b536-5477-4f97-8a26-fc37690f336a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/d600aca8-35ac-4f66-a87e-14890fb8c80f)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/eef99212-6c8f-46fd-b7ed-bb71662f5a54)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/f3bf6768-a497-4e0f-a560-8f1eee2d3d68)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/29fab82e-cb63-4baf-9811-b3f094f17418)

### Thermostat User Interface Configuration Cluster
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/4ffaaf52-98d7-4493-9a8d-021abfd1a1e3)

### 02 Home Automation Temperature Sensor - Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/02e111dc-e334-4c58-8ace-7e79de235cb0)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/7a415648-29ae-4ba4-aa53-e9eb9b247cfb)

### 02 Home Automation Temperature Sensor  - Temperature Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/809f8a5e-54d1-4d0b-a682-8f384e6adb72)

### 04 Home Automation Occupancy sensor - Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/f57d4fac-29ec-4370-a037-7fc2e8dcb0d0)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/13e0dc52-71fb-4a1b-897b-44f40243f56b)

### 04 Home Automation Occupancy sensor - Occupancy sensing
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/46b4ae75-f002-4694-8983-0d34948df6f1)

### 05 Home Automation Consumption Awareness Device - Basic
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/6509303d-c058-46f2-a3a8-7a280c8ec03a)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/415a8c03-8f9d-4af4-9c61-bb0e17d6a3c0)
 
### 05 Home Automation Consumption Awareness Device - 0702 Simple Metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/18807640-adf3-4542-8fe6-b6916c73c711)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/157237643/be0c18a9-d14a-4daa-a87c-d0b254ccdb28)

**Comment by sdriesche** [comment]
Hi, is there a quick way to get the basics (thermometer read-out, temperature set, and valve setting) of the thermostat working?

**Comment by Smanar** [comment]
And I was wrong, you can keep the TYPE_CONSUMPTION_SENSOR.
But Now I m looking better the DDF, but was same device ?
It use the TYPE_CONSUMPTION_SENSOR on same endpoint than your, the 0x05 ....
