### ISSUE TITLE
Philips Hue Signe floor lamp

### ISSUE THREAD

**Issue by BEskandari** [dresden-elektronik/deconz-rest-plugin#7541]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Philips Hue Signe

### Manufacturer

Philips

### Model identifier

4080248P9

### Device type to add

Light

### Node info

![ps2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/2b05a88a-a3ba-4ac5-a1d6-8060a4ffc0c3)

### Endpoints and clusters

![ps1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/6e93263f-234f-4601-bb5e-b1e63aa17f69)

### Basic

![ps3a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/d30236cd-85f4-4388-80e7-83dcb1b54865)
![ps3b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/e5f4d4f4-2d58-4f44-b4b4-933c4874ed78)
![ps3c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/67e57d40-fb3b-43d2-b84b-1ea90ecb335a)

### Identify
![ps4](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/0325cd4a-974d-4d3d-9ad4-24265d8b8af1)

### Groups
![ps5a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/110fea4b-bbd8-466c-8d5d-1b5373ea9c1e)
![ps5b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/28446aad-1120-441e-a7b2-471128e77c55)

### Scenes
![ps6a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/8ea641e9-8493-460a-8f0c-fe81a61f60ff)
![ps6b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/0d7fc4bf-e7d1-4c67-bc61-43c69027cbc5)
![ps6c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/d8542142-8064-4f0a-8137-f72ac50853a6)
![ps6d](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/716eda5c-1b34-49e9-8f1e-e5576a42855e)

### On/off
![ps7a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/cdc1ac3b-3ffe-414e-a07e-f926efaf5194)
![ps7b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/606dffee-7659-45c7-b9bc-027035688a1a)
![ps7c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/4c3a779f-8aa3-4ea0-ab7b-30935f9d0a40)

### Level Control
![ps8a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/1868b003-d01d-4f95-bf6d-fd1e5630a732)
![ps8b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/f33a9898-2705-4a20-aeb5-95bc9601a0d7)
![ps8c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/8583e071-87c7-465e-9932-aa889b57099f)

### Touchlink Commissioning
![ps9a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/67dbba9e-34ef-4625-b88e-f0163ee6249b)

### Hue Effects
![ps10](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/075b0a05-db09-440e-ac7b-06ba347ea96b)

### Color Control
![ps11a](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/7e6ad567-b504-4845-a0e3-4e9ae7961904)
![ps11b](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/8ba1a234-31f9-4e82-a8be-f7a16f73772b)
![ps11c](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/15f8f242-6350-498f-bf53-97b54fea884d)
![ps11d](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/cf803b74-4de0-40af-a37a-58c99264925a)
![ps11e](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/0c1749cd-4b03-40cb-90cb-fe96193883c7)
![ps11f](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/f59d687f-74aa-48a7-ae11-c9899c69d002)
![ps11g](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/3b742f2b-3771-49d9-b221-a8af105a5b00)

### Hue Entertainment
![ps12](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85784955/b2963047-0bd6-4425-80c8-8e4e52f5633c)

**Comment by BEskandari** [comment]
@ebaauw, by any chance do you think that with an existing Philips Hue DDF we can control this device?

**Comment by ebaauw** [comment]
Yeah, probably just another ZB3 gamut C light.  You might want to check the _Image Type_.

**Comment by BEskandari** [comment]
Thanks for the hint. I added the model identifier in light_zb3_C.json and it is working fine
