### ISSUE TITLE
Add Tuya Smart Zigbee Thermometer/Humidy reader

### ISSUE THREAD

**Issue by KRGT-NL** [dresden-elektronik/deconz-rest-plugin#7542]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tuya Smart Zigbee Thermometer

### Manufacturer

_TZE200_zl1kmjqx

### Model identifier

TS0601

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/86347728/41cc218a-0313-41e9-ad78-54030d4b0343)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/86347728/dd93e131-0319-44b7-a0f5-fa603ce1348c)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/86347728/5154ee0a-3290-4d4e-89bc-93b96df68aec)

### Any other cluster of relevance/interest
Ordered: https://nl.aliexpress.com/item/1005002836127648.html

**Comment by KRGT-NL** [comment]
As you can see i do not get enough information from this device to fill in all details...

**Comment by Mimiix** [comment]
Can you share the list of clusters ?

**Comment by KRGT-NL** [comment]
> Can you share the list of clusters ?
Do you mean this one?
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/86347728/68b53aa9-d994-4bb8-b731-a5c092dae3a3)

**Comment by Mimiix** [comment]
> > Can you share the list of clusters ?
> > Do you mean this one?
> > ![image](https://private-user-images.githubusercontent.com/86347728/298393730-68b53aa9-d994-4bb8-b731-a5c092dae3a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTc3ODYsIm5iZiI6MTcwNTg1NzQ4NiwicGF0aCI6Ii84NjM0NzcyOC8yOTgzOTM3MzAtNjhiNTNhYTktZDk5NC00YmI4LWI3MzEtYTVjMDkyZGFlM2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE3MTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NmFiOTZhZDkyNDYyOTQ4YzRhZWY0ODI5NDhiMjEzMWY5MWQ4N2ZiZmJiZTZiM2MxYjc4OGUxMWM4ZmJmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5K0Mcubj8-YFao5jmwoGPoJsAdLCGy9YcwvZTT3Q8NE)
> 
> As you can see it is not goodly recognized, as it;s just a sensor in all means, like the Ikea it misses a lot of clusters. ![image](https://private-user-images.githubusercontent.com/86347728/298393982-f156ec28-9827-45de-9652-5c94e60eec4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTc3ODYsIm5iZiI6MTcwNTg1NzQ4NiwicGF0aCI6Ii84NjM0NzcyOC8yOTgzOTM5ODItZjE1NmVjMjgtOTgyNy00NWRlLTk2NTItNWM5NGU2MGVlYzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE3MTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZjFhYTgxNjcwNTliMmVhMGJkYjU4NmI3ZmRkODQyYTRiN2FkNDM5OTE2MjcxNzg3YzdjZDg4MWI0YTdiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a68hST7CNUp6i45z0rV00YAe4riArF4ZLtXrfnw8KTk)

Thats often how Tuya works :) no problem there.

They just don't stick to the standard...

**Comment by KRGT-NL** [comment]
No update?

**Comment by Mimiix** [comment]
@Smanar Can you check in / help out :)?

**Comment by KRGT-NL** [comment]
Let me check how I do this!

**Comment by Smanar** [comment]
Depend of your OS, easier on real OS.

`All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired.`

If you are on the offical docker, you have a persistent folder.

If you are using HA, you have one too, but harder to use.

**Comment by KRGT-NL** [comment]
You can guess which one I have haha

I will check with Portainer the exact mapping in HassOS and will put the file on Hass with the Samba Share addon :-)

**Comment by Smanar** [comment]
Lol.
you have the short and long procedure here https://forum.phoscon.de/t/how-to-add-edit-a-ddf-on-home-assistant-using-text-editor/1839

**Comment by KRGT-NL** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/86347728/8dfa9ad8-17f2-4d09-bfba-df512fba4742)

Looks like that it works. :)

**Comment by Smanar** [comment]
Thx for return.
PR done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7658
