### ISSUE TITLE
deConz 2.25.1 on macOS - no function of LQI and Neighbor Links buttons

### ISSUE THREAD

**Issue by RP-Develop** [dresden-elektronik/deconz-rest-plugin#7555]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

The LQI and Neighbor Links buttons have no function. The LQI’s are not displayed and the Neighbor Links are displayed every time. When I switch the buttons, nothing changes.

### Steps to reproduce the behavior

click on LQI and/or Neighbor Links

### Expected behavior

LQI should display or not
Neighbor Links should display or not

### Screenshots

<img width="854" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/eb787c72-2543-4227-835b-c76a3b9c2195">

### Environment

- Host system: macOS 14.3
- Running method: deConz App runs with Rosetta
- Firmware version: 
- deCONZ version (not Home assistant Addon version!): 2.25.1
- Device: ConBee II / ConBee III 
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? If so: USB Stick

**Comment by manup** [comment]
Should be fixed in next release, closing this issue since already tracked in: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7457
