### ISSUE TITLE
SYMFONISK Sound Controller only displays 50% battery power

### ISSUE THREAD

**Issue by RP-Develop** [dresden-elektronik/deconz-rest-plugin#7561]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

The SYMFONISK Sound Controller E1744 only displays 50% battery power after insert of a brand new battery.

### Steps to reproduce the behavior

1. change the battery
2. check the value of battery power

### Expected behavior

It should display a real value, close to 100% after inserting of a brand new battery.

### Environment

- Host system: macOS 14.3
- Running method: deConz App, runs with Rosetta
- Firmware version: ConBee II 26780700 / ConBee III 264f0900
- deCONZ version (not Home assistant Addon version!): 2.25.1
- Device: ConBee II / ConBee III 
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? If so: USB Stick

### Additional context

I have changed the DDF file (symfonisk_sound_contoller.json) as follows to fix it for now:
`
{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_IKEA",
  "modelid": "SYMFONISK Sound Controller",
  "product": "SYMFONISK Sound Controller - E1744",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SWITCH",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x1000"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0006",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x1000"
        ],
        "out": [
          "0x0006",
          "0x0008"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/productid",
          "parse": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x000A",
            "eval": "Item.val = Attr.val"
          },
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x000A"
          },
          "refresh.interval": 86400
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/alert"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0001",
            "at": "0x0021",
            "eval": "Item.val = Math.round(Attr.val)"
          },
          "default": 0,
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0001",
            "at": "0x0021"
          },
          "refresh.interval": 86400
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/buttonevent",
          "awake": true
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_RELATIVE_ROTARY",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0008"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0006",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x1000"
        ],
        "out": [
          "0x0006",
          "0x0008"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/productid",
          "parse": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0000",
            "at": "0x000A",
            "eval": "Item.val = Attr.val"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/alert"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0001",
            "at": "0x0021",
            "eval": "Item.val = Math.round(Attr.val)"
          },
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/expectedeventduration"
        },
        {
          "name": "state/expectedrotation"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/rotaryevent",
          "awake": true,
          "parse": {
            "fn": "zcl:cmd",
            "ep": 1,
            "cl": "0x0008",
            "cmd": "0x01",
            "script": "0008_rotaryevent.js"
          }
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0008"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 2700,
          "change": "0x01"
        }
      ]
    }
  ]
}
`

**Comment by Mimiix** [comment]
Can you share a screenshot of the Power config cluster after reading it?

**Comment by RP-Develop** [comment]
I'm not sure, but like some examples I think you means the 0001. Please, but I think we have an additional problem. I don't see any information (deConz 2.25.1 on macOS). Do I have to activate other options to see it?
<img width="1445" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/cccd8e9a-7745-418e-9255-ebc3051c9ff3">

**Comment by Mimiix** [comment]
Asked devs to check.

**Comment by ebaauw** [comment]
> I think we have an additional problem. I don't see any information

Looks like `general.xml` is corrupt (or cannot be opened).

> The SYMFONISK Sound Controller E1744 only displays 50% battery power after insert of a brand new battery.

The controller probably doesn't run the latest firmware, which reports battery in 0.5% (as per the standard).  We hacked something to check the firmware version for some of the other IKEA devices, see e.g.
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/f72c9ef1d1cf82c206816ca35b6d70ac551ec984/devices/ikea/blind.json#L185

**Comment by RP-Develop** [comment]
it was set an path in preferences to:
/private/var/folders/8t/0928_fc17xn5854vv17n4q9m0000gp/T/AppTranslocation/0C9B23BF-6A55-485D-9752-42A7EE3B9561/d/deCONZ.app/Contents/Resources/zcl/general.xml

It was only possible to follow to:
/private/var/folders/8t/0928_fc17xn5854vv17n4q9m0000gp/T
...but not more

I found the general.xml file in the App package: 
/Applications/deCONZ.app/Contents/Resources/zcl/general.xml

It was not possible to set the settings to this path, because it is in the App package, so I copied it to:
/Users/home/Library/Application Support/dresden-elektronik/deCONZ/general.xml
...and set the path in the preferences.

Now it looks better. However, the path should already be set with the installation.
<img width="668" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/980ad78a-209a-4f8f-ac1e-c50d017e95c3">

now I can show the Power config cluster:
<img width="1309" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/6ee4b292-3753-4329-8aa7-273ebe57a92d">

I will report the changings of DDF later...

**Comment by Mimiix** [comment]
The cluster shows 100% here, so that seems to be correct :)

**Comment by RP-Develop** [comment]
I have 4x  SYMFONISK Sound Controller's. 1x with 2.1.022 3x with 2.1.024. I have copied the DDF file to:
/Users/home/Library/Application Support/dresden-elektronik/deCONZ/devices/symfonisk_sound_contoller.json (also /Users/home/Library/Application Support/dresden-elektronik/deCONZ/devices/0008_rotaryevent.js) and changed line 87 and 187 to your code. We have two places in this file for config/battery. The normal and the rotary event.

I will watch it a while and report later.

Many thanks for your support

**Comment by RP-Develop** [comment]
One more question, does the wrong path to general.xml also affect other functions / files? What else would be stored in this path?
/private/var/folders/8t/0928_fc17xn5854vv17n4q9m0000gp/T/AppTranslocation/0C9B23BF-6A55-485D-9752-42A7EE3B9561/d/deCONZ.app/Contents/Resources/zcl/general.xml
