### ISSUE TITLE
Door Window Detector, eWeLink, SNZB-04

### ISSUE THREAD

**Issue by Kreizbiggl** [dresden-elektronik/deconz-rest-plugin#7563]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Zigbee Door Window Detector

### Manufacturer

eWeLink

### Model identifier

SNZB-04

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/42786598/6962bb87-2b7d-43fa-83e8-fcf7a771bca8)

### Endpoints and clusters

Door Window Detector

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/42786598/91192f2d-ffc4-4412-92ff-c6b5dfa4975d)

### Further relevant clusters

 
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/42786598/3145eec4-9d69-402b-bbf8-ac3f78e2165d)

**Comment by SwoopX** [comment]
Hi there.

Unfortunately, the screenshots indicate that the clusters have not been read properly. [This page](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#read-device-clusters) explains how to read clusters. Please take new ones and update the issue accordingly and do not forget to include the correct one for the basic cluster. Thanks a lot!
