### ISSUE TITLE
Hiking Single Phase 65A DIN Rail Energy Meter (modelid: TS0601, manufacturer: _TZE204_bkkmqmyo)

### ISSUE THREAD

**Issue by maltekluever** [dresden-elektronik/deconz-rest-plugin#7564]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Hiking/Tuya Zigbee Single Phase 65A DIN Rail Energy Meter

### Manufacturer

_TZE204_bkkmqmyo

### Model identifier

TS0601

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/1d565112-5a7a-4b07-ab0f-84aa3d0ae029)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/0fba0165-b4cf-4d9e-96b5-a2ed5c70fab9)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/25f508dd-e5d4-4b0b-a999-3c1d6c3d881f)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/d0503a5f-6c13-4f46-825b-1bd246ee0e72)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/d8afff4c-f1c8-46ed-8deb-090c4176ea66)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/4c6c1c14-782e-4d9f-a8c9-4729faa5eae6)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/51c5b2f4-0a0e-485d-a2c8-f837b87510a1)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/1ef973cb-3f0b-4b26-86be-32fc9d992247)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/8fca032a-4430-4c5c-bf04-c7ac75b81752)

### Electrical Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/499e14a3-4e5a-496c-9cd4-1d3a574517df)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/3a9d37f9-bdf9-46aa-914f-56b081ae98d7)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/3ac96f40-216a-4a2f-8d38-b05bf239d275)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/d9695dc7-2f43-4d8e-a9cd-253dfa75b11c)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/3915fc80-6b3c-423f-aa47-4e308220a6d9)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/bdf98c52-a775-46f7-91de-f2833b0acf8e)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/8ea19a81-7989-4dd4-aa3c-f34b2e83b9a0)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/3949752c-24b5-4465-8d6c-92a109479204)

### Any other cluster of relevance/interest
**Groups**
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/4e378055-bbc7-4812-a9b3-7d3763e9147d)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/1977d905-5af5-426d-a1a3-e32fbe62c030)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/b9c16406-e11d-4055-afb1-30f34e3ba753)

**Scenes**
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/8a0a09f6-36ff-42ac-8c57-d54a41150d9d)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/476254ac-8444-441f-9f81-0d7b2589b638)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/24b3d7fd-be96-4d69-baf7-0466a6e53dc7)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/7ced9f47-d1b7-4b70-baee-abb6b5213756)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/035e167b-6cdb-45ae-8e66-2f792009587c)
 
**Tuya Specific**
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/308ea792-fb3e-41e8-b0db-e4f279fde4dd)

**OTAU**
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/9b87aa95-217e-41d3-9c58-e9d0d3f68e6b)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/20d2e63f-b647-4c4c-a5f5-1d5616b894b5)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/b034abaf-0494-4cea-8393-28d69ebadd6f)

**Time**
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/364f1e2f-9c1f-4dd3-9e85-c855eacb08a7)

**Comment by maltekluever** [comment]
push

**Comment by maltekluever** [comment]
Thanks a lot for your comments! If I understand correctly, the following DDF should work:
`
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_lsanae15", "_TZE200_bkkmqmyo", "_TZE200_eaac7dkw", "_TZE204_bkkmqmyo"],
  "modelid": ["TS0601", "TS0601", "TS0601", "TS0601"],
  "product": "Single Phase Din Rail Smart Energy Meter",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
      {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 16, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 16, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "tuya"}
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val * 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/current",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "const buffer = Buffer.from(Attr.val, 'hex'); Item.val = (buffer[4] | buffer[8] << 8) / 1000;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/voltage",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "const buffer = Buffer.from(Attr.val, 'hex'); Item.val = (buffer[1] | buffer[0] << 8) / 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/power",
          "parse": {"fn": "tuya", "dpid": 103, "eval": "Item.val = Attr.val / 10;" },
          "read": {"fn": "none"},
          "default": 0
        }
      ]
    }
  ]
}
`

I saved this json to a file "hiking.json".
If I edit the ddf via deconz (right click on the device > Edit DDF > Load the file "hiking.json" > "Hot Reload"), deconz shows me the correct json in preview and it seems to have it updated. If I close the editing-window though and right click > Edit DDF again on the device, the old json is there. It seems that somehow the changes were not saved. Am I overseeing something?

**Comment by Smanar** [comment]
>If I edit the ddf via deconz (right click on the device > Edit DDF > Load the file "hiking.json" > "Hot Reload"), deconz shows me the correct json in preview and it seems to have it updated. If I close the editing-window though and right click > Edit DDF again on the device, the old json is there. It seems that somehow the changes were not saved. Am I overseeing something?

Honneslty I don't fight with editor, so much problem.
Just create a file in a "devices" folder and use text editor.
what is your OS ? (To know the "devices" folder to use)

Else the result in the API don't look so bad, ecxept current/voltage can be not working, but power need to work.

**Comment by maltekluever** [comment]
I am running deconz on Raspbian, I guess the folder is then
`/home/pi/.local/share/dresden-elektronik/deCONZ/devices` ?

In there I created a file `hiking.json`, pasted the following content in it:
```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_lsanae15", "_TZE200_bkkmqmyo", "_TZE200_eaac7dkw", "_TZE204_bkkmqmyo"],
  "modelid": ["TS0601", "TS0601", "TS0601", "TS0601"],
  "product": "Single Phase Din Rail Smart Energy Meter",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
      {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 16, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 16, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "tuya"}
        },
        {
          "name": "config/tuya_unlock"
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val * 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/current",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "const buffer = Buffer.from(Attr.val, 'hex'); Item.val = (buffer[4] | buffer[8] << 8) / 1000;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/voltage",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "const buffer = Buffer.from(Attr.val, 'hex'); Item.val = (buffer[1] | buffer[0] << 8) / 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/power",
          "parse": {"fn": "tuya", "dpid": 103, "eval": "Item.val = Attr.val / 10;" },
          "read": {"fn": "none"},
          "default": 0
        }
      ]
    }
  ]
}
```
Then I restarted deconz and voilà, by right-clicking on the device and "Edit DDF" it shows now the proper DDF. Thanks for the hint.

However, in the API it looks now like this:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/8c2e7616-732f-4f66-b037-7d9acc5c07a0)

Regarding the logs I restarted phoscon and immediately open the debug view and waited for some time. I got this, but nothing with TYDATA:

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/cb0ecf78-6af1-4c14-bf69-dc2f4e4dbd34)

**Comment by Smanar** [comment]
>I am running deconz on Raspbian, I guess the folder is then
>/home/pi/.local/share/dresden-elektronik/deCONZ/devices ?

Yes, for exemple, you are using the "user" folder so the file will be never removed.
You will just have some issue on `attr/swversion` because the DDF use an external file that is not present for you, but not a problem for the moment.

>However, in the API it looks now like this:

You have only this one ?
You need to have 3 devices created with this DDF.

And you have tuya log from legacy core instead of DDF core (and from another device, you can compare the MAC adress), I think something have failed, now the DDF is correctly set, perhaps with deleting and re-including the device ?
To work this device need the "tuya unlock sequence" and the DDF do it only at inclusion and every 24h.

**Comment by Smanar** [comment]
Don't take care about the "line", when a device is offline, the bname is grayed.
It's a long story, but the line don't mean "connexion".

The tuya_unlock sequence is something invisible for you.

```
         {
          "name": "config/tuya_unlock",
          "public": false,
          "refresh.interval": 86400,
          "default": false
        },
```

You haven't saved ?
Because I suspect the editor corrupt DDF, if you take a look in the DDF on this topic there is just 

```
        {
          "name": "config/tuya_unlock"
        },
```

You can use it to take a look, but never save the change, always use a text editor to edit DDF.

Still nothing in logs with "info" ? for the device 70:ac:08:ff:fe:a1:65:fd ?

**Comment by maltekluever** [comment]
> Don't take care about the "line", when a device is offline, the bname is grayed. It's a long story, but the line don't mean "connexion".

okay, thanks for the clarification!
 
> The tuya_unlock sequence is something invisible for you.
> 
> ```
>          {
>           "name": "config/tuya_unlock",
>           "public": false,
>           "refresh.interval": 86400,
>           "default": false
>         },
> ```
> 
> You haven't saved ? Because I suspect the editor corrupt DDF, if you take a look in the DDF on this topic there is just
> 
> ```
>         {
>           "name": "config/tuya_unlock"
>         },
> ```
> You can use it to take a look, but never save the change, always use a text editor to edit DDF.

yep, in the DDF I saved in the corresponding folder only the `{"name": "config/tuya_unlock" }`. However, if I right-click on the DDF and check the Preview, then I see:
```json
{
"name": "config/tuya_unlock",
"public": false,
"refresh.interval": 86400,
"default": false
},
```

> Still nothing in logs with "info" ? for the device 70:ac:08:ff:fe:a1:65:fd ?

No, unfortunately not. I'll keep the debug-log-mode on for some days and see if something pop ups there.

**Comment by Smanar** [comment]
>However, if I right-click on the DDF and check the Preview, then I see:

Strange, but why not, the editor is something alive ^^.
But the path displayed on the editor title is the good one ?
The editor haven't changed other thing ?

I have checked again on Z2M project, and there is nothing special for this device, except the tuya unlock sequence
With the falg "Info" you need to have something like

21:44:58:632 TY_DATA_REPORT: seq 66, dpid: 0x69, type: 0x02, length: 4, val: 5003
21:44:58:633 TY_DATA_REPORT: seq 66, dpid: 0x69, type: 0x02, length: 4, val: 5003
21:44:58:634 TY_DATA_REPORT: seq 66, dpid: 0x69, type: 0x02, length: 4, val: 5003
21:44:58:635 TY_DATA_REPORT: seq 66, dpid: 0x69, type: 0x02, length: 4, val: 5003
21:44:58:637 TY_DATA_REPORT: seq 66, dpid: 0x69, type: 0x02, length: 4, val: 5003

And don't need to wait 24h to have them.

For me the problem is more on the zigbee side.
You have tried to delete and re-include it ?

**Comment by maltekluever** [comment]
Sorry for the delayed answer, I needed an electrician to do some work so I can test it again. 

And indeed, simply deleting it and pairing it again did the trick. Thank you so much!!! :) 

Now it works like a charm and I can see it like this:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/136569921/d0de5de9-62c2-49b9-91b7-e378b3a80c83)

Just to sum up, the following DDF (put into the file "~/.local/share/dresden-elektronik/deCONZ/devices/hiking.json) worked:
```json
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZE200_lsanae15", "_TZE200_bkkmqmyo", "_TZE200_eaac7dkw", "_TZE204_bkkmqmyo"],
  "modelid": ["TS0601", "TS0601", "TS0601", "TS0601"],
  "product": "Single Phase Din Rail Smart Energy Meter",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
      {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "parse": {"fn": "tuya", "dpid": 16, "eval": "Item.val = Attr.val;" },
          "write": {"fn": "tuya", "dpid": 16, "dt": "0x10", "eval": "Item.val == 1 ? 1 : 0;"},
          "read": {"fn": "tuya"}
        },
        {
          "name": "config/tuya_unlock"
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = Attr.val * 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "none"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/current",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "const buffer = Buffer.from(Attr.val, 'hex'); Item.val = (buffer[4] | buffer[8] << 8) / 1000;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/voltage",
          "parse": {"fn": "tuya", "dpid": 6, "eval": "const buffer = Buffer.from(Attr.val, 'hex'); Item.val = (buffer[1] | buffer[0] << 8) / 10;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "state/power",
          "parse": {"fn": "tuya", "dpid": 103, "eval": "Item.val = Attr.val / 10;" },
          "read": {"fn": "none"},
          "default": 0
        }
      ]
    }
  ]
}
```

**Comment by Smanar** [comment]
Ok so  nothing to do ? Just adding your model to the list ?
Do you want to make the PR to submit the device officialy or want I make it ?
