### ISSUE TITLE
IKEA Parasoll sensor not functioning in Domoticz after loading via the DDF

### ISSUE THREAD

**Issue by VincentvdH-91** [dresden-elektronik/deconz-rest-plugin#7568]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I've loaded the the IKEA Parasoll DDF as per #7445 into the devices folder on my RPI, after that the IKEA sensor did show up in my Domoticz Devices list, but it does not function. When I trigger the sensor (open/close door) there's no change in Domoticz.

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/84287293/984b6f3a-b5e6-4985-b660-22cdcc5556c5)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/84287293/99a26085-1473-4e5c-8270-6ab6af42c4cc)

The only item in the log is from the very first time the devices is added.

### Steps to reproduce the behavior

The issue happens all the time, I've waited a couple of days. Also rebooted the devices, but no luck.

### Expected behavior

I was expecting after succesfully adding the device to Domoticz to be able to see the door opening/closing

### Environment

- Host system: Raspberry Pi 3B
- Running method: Raspbian Bullseye - Domoticz 2024.2
- Firmware version: 26660700
- deCONZ version (not Home assistant Addon version!): (2.xx.yy)
- Device: ConBee II
- Do you use an USB extension cable: yes (in order to create some distance between Z-Wave & Conbee stick)
- Is there any other USB or serial devices connected to the host system? Yes; Z-Wave & RFXCOM

**Comment by Mimiix** [comment]
Hi

As this is not an issue as described in #5113 I am closing this issue.

Feel free to open a topic on the forums.

Kind regards,
Dennis
