### ISSUE TITLE
Phoscon Switch Editor broken in v2.05.35

### ISSUE THREAD

**Issue by oscar-b** [dresden-elektronik/deconz-rest-plugin#758]
The switch editor worked (ish) in v2.05.34, enough to configure my Hue Dimmer Switch, but after upgrading to v2.05.35 it seems completely broken.

When I load the switch editor, the old key assignments aren't there. And if I add a new one, it doesn't display in the list of key assignments.

The switch, however, still works as it did before the upgrade.

**Comment by manup** [comment]
I figure it's the mixed browser cached version of the site. It should work after "some" time or when the cache is cleared/updated.

In the next version we'll fix the cache refresh after an update.

**Comment by oscar-b** [comment]
I doubt that's the problem, I've cleared all caches (dev tools, application, clear storage). I also run without cache when dev tools is open (which seem to cause the Qt web server to freak out due to the amount of requests, but that's another issue).

**Comment by manup** [comment]
Hmm strange, do the browser dev tools show any error? Disabled cache shouldn't have a negative effect, in fact we're developing the App in this way (mostly in Chrome Dev Tools and Safari/Firefox for testing).

We'll try to reproduce the problem with the Hue Dimmer switch and update from .34 to .35.

**Comment by oscar-b** [comment]
At some point I got this message, not sure if it's related or not.

``` TODO: Schaltergruppe mit Lichtern verursacht Fehler, wenn Licht in Regel vorkommt```

**Comment by manup** [comment]
Found the issue should work again in 2.05.37.

**Comment by manup** [comment]
Close the Issue for now.

**Comment by oscar-b** [comment]
@manup Will test it as soon as the Docker image is updated

**Comment by Surfer2010** [comment]
Seems like this is still a problem.
Newest Docker Image (2.05.80 / 14.8.2020)
I have a Switch (Osram Lightyfy 4 Button Switch) in the "switches" menu, but no available switch in the switch editor in my Room

**Comment by Mimiix** [comment]
@Surfer2010 This issue is _minus 2 days_ 2 years old. Please open a new user question issue.
