### ISSUE TITLE
Thermor 286045

### ISSUE THREAD

**Issue by MauricioXavier13** [dresden-elektronik/deconz-rest-plugin#7620]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Thermor thermostat 286045

### Manufacturer

Thermor 

### Model identifier

286045

### Device type to add

Thermostat

### Node info

I don't know 

### Endpoints and clusters

I don't know

### Basic

I don't know

**Comment by Mimiix** [comment]
Please add all screenshots.
