### ISSUE TITLE
Sonoff ZBDongle-E (Router Firmware)

### ISSUE THREAD

**Issue by LeoeLeoeL** [dresden-elektronik/deconz-rest-plugin#7636]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Sonoff ZBDongle-E

### Manufacturer

ITEAD

### Model identifier

DONGLE-E_R

### Device type to add

Other

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/70e08041-2563-4111-b0eb-8c00c382d813)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/e71fd903-54cc-469d-9364-60ba6cb74810)
Deconz believes it's a lamp.

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/f698977b-1722-4ce7-8727-b4e906028a03)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/da920910-d5c0-495e-adfc-d64f5fc56747)
If I click on EXEC buttons I receive SUCCESS
### Any other cluster of relevance/interest

**Comment by BoBiene** [comment]
I have the same. It shows up in the phoscon app as two devices:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/23037659/d12ab090-54ed-40e4-9fd0-d42ee835e9e2)

For those hwo like to use the Sonoff ZBDongle-E as range extender in phoscon / deconz:

1. Download the router firmware from https://github.com/itead/Sonoff_Zigbee_Dongle_Firmware/tree/master/Dongle-E/Router
2. Use Chrome / Edge and flash the firmware (on windows) with https://darkxst.github.io/silabs-firmware-builder/
3. Disassemble the stick and power it on
4. start pairing in phoscon
5. press and hold the upper button on the stick (not the reset button) for 5-10 seconds and release the button
6. flasing of the led should indicated the pairing.

**Comment by LeoeLeoeL** [comment]
I can see a lack of support on github in the last months.

**Comment by LeoeLeoeL** [comment]
Keeping alive.

**Comment by LeoeLeoeL** [comment]
Hoping for a DDF...

**Comment by LeoeLeoeL** [comment]
Hope is the last to die

**Comment by Mimiix** [comment]
@Smanar can you help out :)?

**Comment by Smanar** [comment]
Hello, and you just want to see it as router ?
Can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "DONGLE-E_R",
  "product": "ZBDongle-E",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_RANGE_EXTENDER",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

**Comment by LeoeLeoeL** [comment]
Unable to load.

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/6a2c7817-5d43-4208-9e62-988b892c949a)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/f5d0e595-ce58-486f-965c-61652ef8e827)

**Comment by Mimiix** [comment]
You can't load a json, needs to be a bundle..

@Smanar can you do a PR so we get a bundle?

**Comment by Smanar** [comment]
>can you do a PR so we get a bundle?

Need to test it first, no ?

BTW have checked the file again, there is no typo inside.
You have a real OS ? Can try to put the DDF in a "device" folder.

> All DDF provided directly with deCONZ typically reside in /usr/share/deCONZ/devices/ on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. /home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices) will override the pre-packaged files to allow users to amend and keep their own files if desired

Then just restart deconz.

**Comment by Zehir** [comment]
@Smanar you can open a draft PR so you get a bundle and it's not get merged.

You can also use the cli tool to generate the bundle

**Comment by Mimiix** [comment]
This user can't or won't test the json, he can only use the phosocn upload.

Phoscon upload only takes bundles, no jsons. Serious flaw in my opinion,but owell.

**Comment by LeoeLeoeL** [comment]
Last time to check the "Avatto-ZWSM16-2" DDF I loaded the json from DDF Editor.Now I performed the same actions. Why doesn't work this time?

**Comment by Smanar** [comment]
With the DDF on the folder and after a deconz restart, it need to pick itself the DDF.
To choose them it use only
```
  "manufacturername": "SONOFF",
  "modelid": "DONGLE-E_R",
```

Perhaps you still have old entry created, just remove the device first, but I don't see something bad that can prevent the DDF be used.

**Comment by LeoeLeoeL** [comment]
Are we sure everything is ok with DDFs?
I say that because I just realized I lost DDF in my OSRAM plugs. I had in a previous release.

Anyway, I can't load DDF for this range extender. I tried everything.
There is a "default" DDF  (not created by me that doesn't want to be deleted.
{
  "schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "DONGLE-E_R",
  "product": "DONGLE-E_R",
  "sleeper": false,
  "status": "Draft",
  "subdevices": [
    {
      "type": "$TYPE_EXTENDED_COLOR_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "cap/color/capabilities",
          "description": "The supported color modes as bitmap.",
          "refresh.interval": 86400,
          "read": {
            "at": "0x400a",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x400a",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "cap/color/ct/max",
          "description": "Maximum supported color temperature.",
          "refresh.interval": 86400,
          "read": {
            "at": "0x400c",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x400c",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          },
          "default": "0xfeff"
        },
        {
          "name": "cap/color/ct/min",
          "description": "Minimum supported color temperature.",
          "refresh.interval": 86400,
          "read": {
            "at": "0x400b",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x400b",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          },
          "default": 0
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/bri",
          "description": "The current brightness.",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0008",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0008",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/colormode",
          "description": "The currently active color mode.",
          "refresh.interval": 300,
          "read": {
            "at": "0x0008",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0008",
            "cl": "0x0300",
            "ep": 0,
            "eval": "if (Attr.val <= 2) Item.val = ['hs', 'xy', 'ct'][Attr.val]",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/ct",
          "description": "The current Mired color temperature of the light. Where Mired is 1000000 / color temperature (in kelvins).",
          "refresh.interval": 5,
          "read": {
            "at": "0x0007",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0007",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/effect",
          "description": "The currently active effect.",
          "refresh.interval": 300,
          "read": {
            "at": "0x4002",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x4002",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val ? 'colorloop' : 'none'",
            "fn": "zcl:attr"
          },
          "default": "none"
        },
        {
          "name": "state/hue",
          "description": "The current color hue.",
          "refresh.interval": 5,
          "read": {
            "at": "0x4000",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x4000",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "state/sat",
          "description": "The current color saturation.",
          "refresh.interval": 5,
          "read": {
            "at": "0x0001",
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0001",
            "cl": "0x0300",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/x",
          "description": "The current color x coordinate.",
          "refresh.interval": 5,
          "read": {
            "at": [
              "0x0003",
              "0x0004"
            ],
            "cl": "0x0300",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0003",
            "cl": "0x0300",
            "ep": 255,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/y",
          "description": "The current color y coordinate.",
          "parse": {
            "at": "0x0004",
            "cl": "0x0300",
            "ep": 255,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        }
      ]
    },
    {
      "type": "$TYPE_DIMMABLE_LIGHT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert",
          "description": "The currently active alert effect.",
          "default": "none"
        },
        {
          "name": "state/bri",
          "description": "The current brightness.",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0008",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0008",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5,
          "read": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0006",
            "ep": 0,
            "eval": "Item.val = Attr.val",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

If I remove everything:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/a768b381-edd6-4ec4-a462-aaa485e34664)

add the range extender:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/ff2beba5-4ae0-4edd-8a74-61d28712442b)

save it:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/b59d519e-14e5-4421-bdbb-39bec85fa567)

If I make a HOT RELOD or Reboot Deconz....:
I have this again!!!!
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/af480ac7-5f71-4b6f-86c4-aa00b2d49704)

**Comment by Smanar** [comment]
What is your OS ?

>There is a "default" DDF (not created by me that doesn't want to be deleted.

Are you seeing the file ? In wich one folder ?

`sudo chmod -R 777 folder_name`

To get Full right for a file.
Can keep it, but replace the contain.

**Comment by LeoeLeoeL** [comment]
Deconz runs in a  Raspberry pi.
I don't see the file. That DDF exists but I don't know why.
The difference between the DDF you created and what DDF editor makes:

"schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "DONGLE-E_R",
  "product": "ZBDongle-E",
  "sleeper": false,
  "status": "Gold",

"schema": "devcap1.schema.json",
  "manufacturername": "SONOFF",
  "modelid": "DONGLE-E_R",
  "product": "DONGLE-E_R",
  "sleeper": false,
  "status": "Gold",
  "path": "/devices/dongle-e_r.json",

**Comment by LeoeLeoeL** [comment]
Is there anything different about DDFs between 2.26.3 and 2.27.2?

2.27.2
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/69eafd3d-34c0-4e80-be7d-88c959d35802)

2.26.3
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/1e623819-2e4d-4e26-9187-de451f1153c5)

As I wrote above. In the latest beta I lost some DDFs.

Ok, there is something "strange" in the latest beta.
With the last stable i loaded the DDF immediately.
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/85344315-2a0a-426c-b9ea-e4c69a11d6e8)
Anyway, the anomalyis still present (it's seen as 2 light devices)

**Comment by Mimiix** [comment]
> Is there anything different about DDFs between 2.26.3 and 2.27.2?
> 
> 2.27.2 ![image](https://private-user-images.githubusercontent.com/65825223/338321289-69eafd3d-34c0-4e80-be7d-88c959d35802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTQzNDcsIm5iZiI6MTcxODA1NDA0NywicGF0aCI6Ii82NTgyNTIyMy8zMzgzMjEyODktNjllYWZkM2QtMzRjMC00ZTgwLWJlN2QtODhjOTU5ZDM1ODAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDIxMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZjE0N2JmMGE2OGVjNGJlM2IwMTQ5YTdiZjAyMmQ0NDY3ODNjZDRjN2ExMmVlZjZlOTdlNjI5NzgwMzE1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pHeCg8V9T42UxaymnssSD4u5bif-kX3upc-vKSgzazE)
> 
> 2.26.3 ![image](https://private-user-images.githubusercontent.com/65825223/338321492-1e623819-2e4d-4e26-9187-de451f1153c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTQzNDcsIm5iZiI6MTcxODA1NDA0NywicGF0aCI6Ii82NTgyNTIyMy8zMzgzMjE0OTItMWU2MjM4MTktMmU0ZC00ZTI2LTkxODctZGU0NTFmMTE1M2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDIxMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMTZjOTM5MTM3NGI5MTcxNGU0NDA1Y2NkZDk5ZjMzYmNhZGUyZTk4MmZlNWQyNTBkOWRjOGJkMzM4ODg0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OEh4WsCkkhejyQfGAypw4T-O7Y8dDv7-oCc7W7iXZ98)
> 
> As I wrote above. In the latest beta I lost some DDFs.
> 
> Ok, there is something "strange" in the latest beta. With the last stable i loaded the DDF immediately. ![image](https://private-user-images.githubusercontent.com/65825223/338325604-85344315-2a0a-426c-b9ea-e4c69a11d6e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTQzNDcsIm5iZiI6MTcxODA1NDA0NywicGF0aCI6Ii82NTgyNTIyMy8zMzgzMjU2MDQtODUzNDQzMTUtMmEwYS00MjZjLWI5ZWEtZTRjNjlhMTFkNmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDIxMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMWUyMmU1MTNkOGM3YzI5ODU0YTJiMTk1ZDg3NmQzZjAyMzcyYTg3ZDRmY2Q4YmVmNWE2YTc3N2NiYzc2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3OBE5XpC0RdTAcOWNc7JExoTUTodJcItlrhNlnbKhlw) Anyway, the anomalyis still present (it's seen as 2 light devices)

The last beta is confirmed to have issues with ddfs in general. I recommend staying on 2.26.3 for now

**Comment by Smanar** [comment]
>Anyway, the anomalyis still present (it's seen as 2 light devices)

With the good DDF ? Deconz have picked the good one ? you will see the same thing in deconz, the difference will be only in the API.

>The difference between the DDF you created and what DDF editor makes:

Thoses difference are normal, but if you have only `"type": "$TYPE_RANGE_EXTENDER",` on the DDF I on't see why deconz still creating the 2 others one ...

>I don't see the file

No typo in file path ? File is not hidden.

**Comment by LeoeLeoeL** [comment]
I tried both.
Anyway, the DDF wasn't OK because, after minutes, the device lost all links with the others.

**Comment by Smanar** [comment]
>>the DDF wasn't OK because, after minutes, the device lost all links with the others.

The device is passive, the DDF too, it don't have impact on the device, It just have a cosmetic result (at least it need to have if working)
