### ISSUE TITLE
AVATTO ZWSM16-2-Zigbee

### ISSUE THREAD

**Issue by LeoeLeoeL** [dresden-elektronik/deconz-rest-plugin#7646]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

AVATTO ZWSM16-2-Zigbee

### Manufacturer

_TZ3000_mtnpt6ws

### Model identifier

TS0002

### Device type to add

Light

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/670382d7-1e85-4b43-8b64-d649376e15fd)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/caae0409-a171-4491-b13b-dd8f1fbd82ff)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/17f8c706-5397-41d5-b503-34924cf653c0)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/7ddcb3bc-2fe4-4fa9-93a0-efa9e4f0b8b7)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/ab1b7183-1f9e-4008-a162-7dd419728dd3)

### Simple Metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/cd8e13d1-2613-467c-9f26-9e3a98f2ae30)

### Electrical Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/65b8c8a5-6ffc-42d9-8af8-0ca644fc6594)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/fe9b3404-69b4-4388-87cd-cd77d9d0d076)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/9a7a0024-1f16-44b3-a7ae-7144c8ef71a9)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/e8980993-20fc-432e-a2cc-8b5e9125ee93)

**Comment by LeoeLeoeL** [comment]
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/1abec7a5-b5ad-43a2-b4c8-4bd8306f654a)
If I set ON light 10 , light 11 switches to ON too.

**Comment by SirBarkAlot** [comment]
i have one to, if there is support i would realy love it
if you would need somone to test it
PM me

**Comment by LeoeLeoeL** [comment]
I have 4 of them.
2 are paired to zigbee2Mqtt and work OK.
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/65825223/c0670871-309c-44cd-a3a2-87f4195a7d1d)
I think the energy meter is disabled by firmware

**Comment by LeoeLeoeL** [comment]
It could be a good thing to integrate this device because is not expensive.

**Comment by Mimiix** [comment]
@Smanar Can you take a look if you have time :)?

**Comment by Smanar** [comment]
Hello can you try this DDF 
```

{
  "schema": "devcap1.schema.json",
  "manufacturername": [
    "_TZ3000_zmy4lslw",
    "_TZ3000_lmlsduws",
    "_TZ3000_mtnpt6ws",
    "_TZ3000_nuenzetq"
  ],
  "modelid": [
   "TS0002",
   "TS0002",
   "TS0002",
   "TS0002"
  ],
  "product": "Tuya 2 output module",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "refresh.interval": 86400,
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        },
        {
          "name": "config/tuya_unlock"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x02"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "refresh.interval": 86400,
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}
```

Or if you want, just edit this DDF devices\tuya\_TZ3000_2channel_module.json

You need to re-include the DDF after that, because the tuya unlock sequence is done at inclusion or every 24h (you can wait 24h too)

**Comment by LeoeLeoeL** [comment]
It has been impossible to load your DDF so I copied your items (violet, blue and green) and generated this one:

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_mtnpt6ws",
  "modelid": "TS0002",
  "product": "TS0002",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/tuya_unlock",
          "public": false,
          "description": "Tuya sequence to unlock some device.",
          "refresh.interval": 86400,
          "default": false
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_ON_OFF_OUTPUT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "description": "True when device is on; false when off.",
          "refresh.interval": 5
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ]
}

Now the two ON/OFF switches are separated; If I switch on number 1 the number 2 stays off.
Too much easy. What's the catch?

**Comment by Smanar** [comment]
So it mean the first DDF is working ?
Can add your device to the previous DDF officialy ?

**Comment by Smanar** [comment]
>My DDF doesn't have 0x02 for the 2nd switch. Is it normal?

No ^^.
It's the endpoint, it's the number on title node, on your you have "01" "02 "F2", 0x01 is for the first gand and 0x02 for the second one.
So strange your DDF are working ....

BTW have added the device here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7712

**Comment by LeoeLeoeL** [comment]
Thank you
