### ISSUE TITLE
Yagusmart Zigbee Smart Wall Light Switch 1 Gang No Neutral Wire Required

### ISSUE THREAD

**Issue by BottlecapDave** [dresden-elektronik/deconz-rest-plugin#7660]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Yagusmart Zigbee Smart Wall Light Switch 1 Gang No Neutral Wire Required

### Manufacturer

unknown

### Model identifier

unknown

### Device type to add

Light

### Node info

<img width="339" alt="node" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/9a393768-92af-4f53-ae4a-2d8db79bc915">

### Endpoints and clusters

<img width="428" alt="cluster1" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/3b45a007-9583-4cab-ac51-e1f781a0e72a">

<img width="425" alt="cluster2" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/70305b87-af44-4922-8599-5e44c1e81e0d">

<img width="423" alt="cluster3" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/bd1475b3-eb9a-47c9-8384-3fda2cb45f89">

<img width="173" alt="cluster4" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/6494f93b-aacd-4cf5-a60f-d461bc3993b5">

### Basic

<img width="173" alt="cluster4" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/6494f93b-aacd-4cf5-a60f-d461bc3993b5">

### Any other cluster of relevance/interest

This is a simple on/off light switch.

This used to work, but not sure when it stopped working.

If I go to Edit DDF, I get

<img width="202" alt="ddf" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14993950/af8a909f-9e5f-4783-a321-f3c4033bfd44">

I am accessing this via Home Assistant

**Comment by Smanar** [comment]
Hello, try adding your device in this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0011_1gang_switch_module.json

Remember you need to add Manufacture name AND model id.

**Comment by BottlecapDave** [comment]
I edited this manually in the deconz view within HA and I managed to communicate with the device again. 

I've opened https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7699 to add the profile

**Comment by Smanar** [comment]
Thx, but why you haven't just added your device to the existing list ?
There new tuya clone every day, so we try to "group" them.

**Comment by BottlecapDave** [comment]
I was trying to follow the convention laid out by existing files (quite confusing of when you add to one vs when you create a new one). The file copied is just what's been working in my instance so I know it works. If the owners of this repo would like me to update my PR and just update one of the existing files, I'll do that.

**Comment by Smanar** [comment]
>quite confusing of when you add to one vs when you create a new one

Lol, right, I can understand, no logic.


>The file copied is just what's been working in my instance so I know it works

Yep, but if you can make a try with the bind/report working mode ? if it work, will be better for your network, the poll make lot of more request than the bind/report mode.
