### ISSUE TITLE
Bosch Light/shutter control unit II

### ISSUE THREAD

**Issue by sahnetorti** [dresden-elektronik/deconz-rest-plugin#7661]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Light/shutter control unit II

### Manufacturer

Bosch

### Model identifier

RBSH-MMS-ZB-EU

This device is a bit special as it has a "split personality": it can function as 2x switch (i.e. for controlling an on/off light) OR as a window covering device. For the latter it must be configured, which can be done  using the Bosch Gateway & proprietary app but not through deconz (yet?)

The magic seems to be in the cluster #FCA0, where some attributes must be set accordingly. Unfortunately these cluster attributes are not available in deconz. A reference to these attributes can be found in a discussion for ZHA [here](https://github.com/zigpy/zha-device-handlers/issues/2518)

BTW I was able to pair this device through the "pair with install code" method in the REST API.

### Device type to add

Other

### Node info

![Node_Info](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/b76d55ca-c997-4e23-adb0-77e19d71d91a)

### Endpoints and clusters

![Clusters_overview](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/5e36fb20-7eb8-48bd-8b1b-9cd961cc84bf)

### Basic

![Basic_cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/da4cdaf9-4441-4eba-bfdd-5005e20523f2)

### Simple Metering
![Cluster_Simple_metering](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/705626a5-93b2-4919-8a32-7ccabbdd674f)

### Electrical Measurement
![Cluster_electrical_measurement_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/5bb0d6fc-ef66-4aa8-b4f9-7a59a928ca7b)
![Cluster_electrical_measurement_2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/adae64f2-7c4e-46a7-9f11-d2577c754125)
![Cluster_electrical_measurement_3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/8cce745b-eba4-4cf7-86a0-45f7a80cf200)
![Cluster_electrical_measurement_4](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/ca832178-e4de-4b2a-a9a8-df91165708c9)

### Window covering
![Cluster_window_covering_1](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/47232b54-0d0e-4995-a360-7a61811529a0)
![Cluster_window_covering_2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/34fdab07-ac94-4123-93a5-9399ad2ead47)
![Cluster_window_covering_3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/d901fe23-8286-4a60-abcd-543bb5b4a477)

### Diagnostics
![Cluster_Diagnostics](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/85073046/6eac2720-bada-46f1-81d2-446a6507a707)

**Comment by Smanar** [comment]
To add the feature in deconz, edit the general.xml file and for

```
service: zha_toolkit.attr_write
data:
  ieee: ...
  manf: 0x1209
  endpoint: 1
  cluster: 0xfca0
  attribute: 0x0000
  attr_type: 0x30
  attr_val: 0x01
```

The result will be

```
   <cluster id="0xfca0" name="Bosch specific" mfcode="0x1209">
        <description>Bosch Specific cluster.</description>
        <server>
        <attribute id="0x0000" type="enum8" name="shutter mode" access="rw" required="o" mfcode="0x1209">
            <value name="xxxx" value="0x00"></value>
            <value name="yyyyy" value="0x01"></value>
        </attribute>
        <attribute id="0x0002" type="u32" name="calibration closing time" access="rw" required="o" mfcode="0x1209"></attribute>
        </server>
        <client>
        </client>
    </cluster>
```

So you miss feature, but the device is correclty reconized by defaut ? Or you need a DDF too ?

**Comment by sahnetorti** [comment]
Hi smanar,

  thanks for providing the relevant XML snippets. I added this to the general.xml:
```
    <cluster id="0xfca0" name="Bosch specific" mfcode="0x1209">
      <description>Bosch Specific cluster.</description>
      <server>
        <attribute id="0x0000" type="enum8" name="shutter mode" access="rw" required="o" mfcode="0x1209">
          <value name="Switch mode" value="0x00"></value>
          <value name="Rolershutter mode" value="0x01"></value>
        </attribute>
        <attribute id="0x0002" type="u32" name="calibration closing time" access="rw" required="o" mfcode="0x1209">
        </attribute>
      </server>
      <client>
      </client>
    </cluster>
```
which made the shutter work. I am not sure with the names for the modes&values, though, it might be that this is not accurate. I set the device to "rolershutter mode" / 0x01 and after that I could control the shutter (up/down/stop).

Additionjally I had to set the "calibration closing time" in my setup to make the shutters extend/pull back the full way. Without it they extended/pulled back only about 80%.

Also, reading the manual more thoroughly it mentions that when the device is "unconfigured" (no mode set) the inputs S1/S2 for physical switches will not work. I cannot confirm this as I do not have or need physical switches in my setup.

I will be happy to test the changes in the PR mentioned above when I find the time. Is there a better way to do it except adding the new sections manually to my local files?

**Comment by Smanar** [comment]
@SwoopX have started a PR for your device here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7683
You have a DDF and a more complete code to edit for the xml

**Comment by sahnetorti** [comment]
I have applied the changes manually to my installation. I can confirm that
- "Device mode"
- "Calibration opening time"
- "Calibration closing time"
- "Motor state"
all work.

I can control the shutters through Phoscon and through Homeassistant (via deconz integration).

In my install I cannot test the settings for
- "Child lock"
- Switch type"
