### ISSUE TITLE
Ikea Badring

### ISSUE THREAD

**Issue by Emlben** [dresden-elektronik/deconz-rest-plugin#7663]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Ikea Badring

### Manufacturer

Ikea

### Model identifier

BADRING Water Leakage Sensor

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5850880/add6f5f6-087a-4284-9033-9487a515c8ab)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5850880/a74bb06b-5f1c-4a90-b55f-9d2ee45c6dfe)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5850880/9e183157-169a-4f42-9533-b7e1fa79a346)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5850880/c8e6d720-bf8e-4826-af4c-306695b0b7fa)

### Any other cluster of relevance/interest 
(My first attempt to provide this information - please bare with me ;) )
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/5850880/c0f87c7b-0c40-46b6-8184-8e6a4283e75f)

**Comment by Hector47** [comment]
I also have the same sensor. How can I help ? Do you have an DDF a can use as base ?

**Comment by danielchansen** [comment]
Same. Have four of these sensors. Anything I can do to contribute?

**Comment by Mimiix** [comment]
@Smanar can you take a look?

**Comment by Smanar** [comment]
Someone have started a DDF here https://forum.phoscon.de/t/ddf-for-ikea-device-badring-water-leakage-senor/4736

**Comment by RP-Develop** [comment]
This DDF don't run. I get no alarm from the sensor. Only if I read it manually, so I get a changing in 0x0500 / 0x0002.
<img width="1466" alt="Bildschirmfoto 2024-04-07 um 15 11 11" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/85b90eda-85e8-4fff-a256-2313de71cf77">
<img width="1466" alt="Bildschirmfoto 2024-04-07 um 15 11 46" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/8f0614d7-2432-458e-8221-4129d3940a1b">
Is it possible to set the sensor so that it sends the alarm?

**Comment by Smanar** [comment]
Hello can you try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_IKEA",
  "modelid": "BADRING Water Leakage Sensor",
  "vendor": "IKEA",
  "product": "BADRING Water Leakage Sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_WATER_LEAK_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/productid",
          "refresh.interval": 86400
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/alert",
          "default": "none"
        },
        {
          "name": "config/battery",
          "awake": true,
          "refresh.interval": 86400,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Math.round(Attr.val / 2)",
            "fn": "zcl:attr"
          },
          "default": 0
        },
        {
          "name": "config/group"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "config/enrolled",
          "public": true
        },
        {
          "name": "state/water",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

You miss the enrollement on previous one.

**Comment by RP-Develop** [comment]
Hi Smanar,

sorry, but it don't work. I don't get the alarm. The state has no values. 

some from the Phoscon Web:
<img width="671" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/8022d097-ad8e-4d07-8597-f8c85812f2e1">
<img width="671" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/33df515d-0e40-40c9-b37b-68d65770c087">

**Comment by Smanar** [comment]
`"enrollled" : null.`

The enrollement have failed. Have you tried to re-include it ?

**Comment by RP-Develop** [comment]
maybe helpful:

When I read out the IAS manually, I get these messages in the debug view of the IAS::

19:13:26:010 Force binding of attribute reporting for node BADRING Water Leakage Sensor 2
19:13:56:091 [IAS ZONE] - Address 0xB0C7DEFFFE67151B, Payload 0000003000010000312a00020000190000100000f00000000000000000, Command 0x01
19:13:56:093 [IAS ZONE] - 0xB0C7DEFFFE67151B No IAS sensor found for endpoint: 0x01
19:13:57:100 [IAS ZONE] - Address 0xB0C7DEFFFE67151B, Payload 11000020ff, Command 0x01
19:13:57:101 [IAS ZONE] - 0xB0C7DEFFFE67151B No IAS sensor found for endpoint: 0x01

**Comment by RP-Develop** [comment]
> `"enrolled" : null.`
> 
> The enrollement have failed. Have you tried to re-include it ?

yes:
<img width="671" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/deb23748-9b1a-4ab1-90bd-d673bb9b3c93">

I started with your DDF.

**Comment by Smanar** [comment]
Ha my bad, I forget the fingerprint

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_IKEA",
  "modelid": "BADRING Water Leakage Sensor",
  "vendor": "IKEA",
  "product": "BADRING Water Leakage Sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_WATER_LEAK_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "attr/productid",
          "refresh.interval": 86400
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/alert",
          "default": "none"
        },
        {
          "name": "config/battery",
          "awake": true,
          "refresh.interval": 86400,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Math.round(Attr.val / 2)",
            "fn": "zcl:attr"
          },
          "default": 0
        },
        {
          "name": "config/group"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "config/enrolled",
          "public": true
        },
        {
          "name": "state/water",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

**Comment by RP-Develop** [comment]
<img width="1197" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/3cc96f74-8de4-487f-9bdc-af0b64464cae">
<img width="1197" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/3c18b24e-e379-4577-9bb1-3607f4820697">

**Comment by RP-Develop** [comment]
<img width="790" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/d6112f8a-98f2-4e7f-a893-2715bf08f452">

**Comment by RP-Develop** [comment]
<img width="662" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/b0f692cc-dea8-4380-bddd-f968fe8a9280">

Running on MAC mini M2 Sonoma 14.4.1

**Comment by SwoopX** [comment]
The device presumably needs to be poked on the IAS Zone cluster to start the enrollment process, like the Parasoll (and the battery binding was missing). This one should do the trick:

```{
  "schema": "devcap1.schema.json",
  "manufacturername": "$MF_IKEA",
  "modelid": "BADRING Water Leakage Sensor",
  "vendor": "IKEA",
  "product": "BADRING Water Leakage Sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_WATER_LEAK_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/productid",
          "refresh.interval": 86400
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "refresh.interval": 86400,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Math.round(Attr.val / 2)",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "config/enrolled",
          "public": true
        },
        {
          "name": "state/water",
          "parse": {
            "fn": "ias:zonestatus",
            "mask": "alarm1,alarm2"
          },
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0500",
            "at": "0x0000"
          },
          "awake": true,
          "refresh.interval": 84600
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000002"
        }
      ]
    }
  ]
}
```

**Comment by RP-Develop** [comment]
I have also tried this DDF, but unfortunately without success. I have also used the complete DDF from Parsoll Sensor, adapted accordingly of course, but unfortunately without success. I can't get a status change for "state/water". Only when I use "read" in 0x0500 in deConz do I see a status change in at 0x0002 and also an event in Phoscon. 

After the "read" is also the at 0x0000 changed to Enrolled.
<img width="785" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/df43e3cb-826e-43ff-b947-5235b4cea105">

Can I log some more? 

The IAS log in moment when I let beep the sensor and use the read button:

21:03:18:977 [IAS ZONE] - Address 0xB0C7DEFFFE62A297, Payload 0000003001010000312a00020000190100100000f0ff4305ffff2e2100, Command 0x01
21:03:18:978 [IAS ZONE] - 0xB0C7DEFFFE62A297 Read attributes response:
21:03:18:979 [IAS ZONE] - 0xB0C7DEFFFE62A297   -> IAS Zone State: enrolled.
21:03:18:980 [IAS ZONE] - 0xB0C7DEFFFE62A297   -> IAS CIE address = 0x00212EFFFF0543FF: already written.
21:03:18:980 [IAS ZONE] - 0xB0C7DEFFFE62A297 Sensor (ZHAWater) is enrolled.
21:03:19:931 [IAS ZONE] - Address 0xB0C7DEFFFE62A297, Payload 1100002064, Command 0x01
21:03:19:932 [IAS ZONE] - 0xB0C7DEFFFE62A297 Read attributes response:
21:03:19:933 [IAS ZONE] - 0xB0C7DEFFFE62A297 Sensor (ZHAWater) is enrolled.

...and the same without beep:

21:05:26:913 [IAS ZONE] - Address 0xB0C7DEFFFE62A297, Payload 0000003001010000312a00020000190000100000f0ff4305ffff2e2100, Command 0x01
21:05:26:914 [IAS ZONE] - 0xB0C7DEFFFE62A297 Read attributes response:
21:05:26:915 [IAS ZONE] - 0xB0C7DEFFFE62A297   -> IAS Zone State: enrolled.
21:05:26:916 [IAS ZONE] - 0xB0C7DEFFFE62A297   -> IAS CIE address = 0x00212EFFFF0543FF: already written.
21:05:26:916 [IAS ZONE] - 0xB0C7DEFFFE62A297 Sensor (ZHAWater) is enrolled.
21:05:27:885 [IAS ZONE] - Address 0xB0C7DEFFFE62A297, Payload 1100002064, Command 0x01
21:05:27:887 [IAS ZONE] - 0xB0C7DEFFFE62A297 Read attributes response:
21:05:27:887 [IAS ZONE] - 0xB0C7DEFFFE62A297 Sensor (ZHAWater) is enrolled.
21:05:27:933 [IAS ZONE] - Address 0xB0C7DEFFFE62A297, Payload 1100002064, Command 0x01
21:05:27:934 [IAS ZONE] - 0xB0C7DEFFFE62A297 Read attributes response:
21:05:27:934 [IAS ZONE] - 0xB0C7DEFFFE62A297 Sensor (ZHAWater) is enrolled.

many thanks

**Comment by Smanar** [comment]
Nothing to see but why this part on both DDF (this one and the praraoll)
```

          "read": {
            "fn": "zcl:attr",
            "ep": 2,
            "cl": "0x0500",
            "at": "0x0000"
          },
```

There is no endpoint 0x02, and we are not using this attribute (the 0x0000)
Not a problem as we don't use poll, but useless for me.

For your issue, all seem fine for me, the enrollement is done, you haven't log if the device detect water, without using the "read" button ?

**Comment by SwoopX** [comment]
> and we are not using this attribute (the 0x0000)
> Not a problem as we don't use poll, but useless for me.

In fact, attribute 0x0000 is imperative for any IAS Zone device correctly implementing the standard and deconz always uses it to determine the current state and if there's any to do.

I, personally, would put my bet on a missed device reset on every DDF update. This would explain everything what has been described here and also why things didn't work out as expected.

**Comment by RP-Develop** [comment]
> For your issue, all seem fine for me, the enrollement is done, you haven't log if the device detect water, without using the "read" button ?

No, nothing. I have two devices installed at the moment. I have the feeling that the battery event is also not like from other devices.

**Comment by RP-Develop** [comment]
> would put my bet on a missed device reset on every DDF update

Can I influence this?

**Comment by openKimchi** [comment]
I installed the sensor with this DDF. Then restarted the entire Deconz server. When triggered manually, the alarm jumps to true (state in ioBroker) and stays that way. When triggered again manually, it jumps to false and stays that way. And the battery indicator doesn't work at all.

**Comment by RP-Develop** [comment]
It looks as if the sensor is going into sleep mode. So if you have it read manually, do not wake it up. The first reaction after waking up is to hit the sensor with water and hear the beep. You can then see in the IAS log that all read commands have been processed.

**Comment by openKimchi** [comment]
By manual triggering I mean wetting it with water...almost embarrassing but where can I find this IAS log?

**Comment by RP-Develop** [comment]
(macOS) under Help - Debug view - select IAS
<img width="1922" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/b9f83df2-18ee-47c8-808d-0e7282bc9997">

**Comment by openKimchi** [comment]
ok, thx. Got;

`14:23:39:026 [IAS ZONE] - Address 0x38398FFFFE0AE1FD, Payload 000000640000, Command 0x00
14:23:39:027 [IAS ZONE] - 0x38398FFFFE0AE1FD Status Change, status: 0x0000, zoneId: 100, delay: 0
14:23:39:027 [IAS ZONE] - 0x38398FFFFE0AE1FD Sensor (ZHAWater) is enrolled.`

**Comment by RP-Develop** [comment]
> 14:23:39:026 [IAS ZONE] - Address 0x38398FFFFE0AE1FD, Payload 000000640000, Command 0x00 
14:23:39:027 [IAS ZONE] - 0x38398FFFFE0AE1FD Status Change, status: 0x0000, zoneId: 100, delay: 0 
14:23:39:027 [IAS ZONE] - 0x38398FFFFE0AE1FD Sensor (ZHAWater) is enrolled. 

I don't get it after wetting.

On which system is running your deConz?

**Comment by openKimchi** [comment]
> On which system is running your deConz?

it's a Ubuntu 22.04.4 LTS Server as a VM on a Proxmox System.

**Comment by openKimchi** [comment]
> One question: Why do I get a different view between the preview of the DDF editor and the file that I have edited with an external editor?

Same for me

**Comment by Smanar** [comment]
>One question: Why do I get a different view between the preview of the DDF editor and the file that I have edited with an external editor?

Honnestly there is so much "strange" thing that happen in the editor, don't take care of it. Just look at the file name on the window title and remember deconz check DDF only at start.

**Comment by Mimiix** [comment]
> One question: Why do I get a different view between the preview of the DDF editor and the file that I have edited with an external editor?
> 
> <img alt="image" width="1286" src="https://private-user-images.githubusercontent.com/156454090/321249273-33deb3b0-8836-4447-8fe9-53d07beaa04e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzMwNzksIm5iZiI6MTcxMjc3Mjc3OSwicGF0aCI6Ii8xNTY0NTQwOTAvMzIxMjQ5MjczLTMzZGViM2IwLTg4MzYtNDQ0Ny04ZmU5LTUzZDA3YmVhYTA0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxODEyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODQ5YWZlMWZlMWMzNGMxYmJmNzk4NGZjNTNjMGEwNjlmNDg0ZjUwMjZhMWZiNzBhZjgyOTA5OGIxNWQ2Mzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bGknWGO2wEwSgRtnzkLUt3XeJypxiisKE4amE2kxnXc">

It probably didn't load or the file is in the wrong location.

**Comment by RP-Develop** [comment]
the file should be loaded correctly, because I see the file name at the top line of editor frame.
<img width="506" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/156454090/50e6375a-94f2-44e0-b5f3-a89843310bf9">

The real path on my MAC is: /Users/home/Library/Application Support/dresden-elektronik/deCONZ/devices/badring_water_leakage_sensor.json

**Comment by RP-Develop** [comment]
I haven't touched anything for more than 24 hours now. I didn't get anything back. No battery status and no alarm - nothing

**Comment by openKimchi** [comment]
I just tried it again and everything still works. So it can't be the DDF file. But it only worked after I completely restarted the server. This is done quickly with Proxmox.

**Comment by RP-Develop** [comment]
Can you tell me the version of deConz? My version is v2.25.3.

**Comment by openKimchi** [comment]
2.26.3

**Comment by openKimchi** [comment]
2.26.3, the latest

**Comment by RP-Develop** [comment]
2.26.x don't work on my MAC - [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7698]

**Comment by Smanar** [comment]
> ok, thx. After wetting it I got;

`14:23:39:027 [IAS ZONE] - 0x38398FFFFE0AE1FD Status Change, status: 0x0000, zoneId: 100, delay: 0`

So your device react to water, but you need to have other value than 0x0000 for status

**Comment by DanielHabenicht** [comment]
The DDF also does not work for me (on homeassistant with deCONZ 2.25.3): 

IAS Log: 
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/13590797/15ec4ecf-ae42-44f0-8c85-70c832bb8f7d)

Nothing shows up in HA either, batter at 0 at no events registered.

**Comment by Smanar** [comment]
But on your logs all is fine, we can see the status go from 0x0000 to 0x0001.
Can you make the same log but with the flag "DDF" too ?

**Comment by DanielHabenicht** [comment]
I looked it up today and it now reports the battery (8 hours after initially enrolling it). But I do not receive any events in Homeassistant (is that a part that still must be programmed in the Homeassistant add on or should this work out of the box?)

**Comment by Smanar** [comment]
>is that a part that still must be programmed in the Homeassistant add on or should this work out of the box

For me it's out of the box, can check direclty in the API to be sure, phoscon/help/API Information/sensors.

**Comment by DanielHabenicht** [comment]
ok, yes whatever the system had... It's working now. Maybe it just had to do with all the manual stuff involved to add the DDF. 
Works now: 
![badring](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/13590797/7002df05-9ed9-4600-be9f-44831068e42a)

**Comment by poelzi** [comment]
I also had quite some trouble getting this sensor to work. After deleteing and pairing again with the latest DDF and triggering the sensor, everything works.
