### ISSUE TITLE
TS004F _TZ3000_ja5osu5g Tuya Smart Button

### ISSUE THREAD

**Issue by djsmix** [dresden-elektronik/deconz-rest-plugin#7665]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Smart Button (Tuya/Moes)

### Manufacturer

_TZ3000_8rppvwda

### Model identifier

TS0041

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62570067/08968ac8-5a05-41d3-8476-906dde85c9b4)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62570067/ebc9a685-ef6b-41c5-9739-ce0d70824e92)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62570067/a728d39b-a27d-4648-9570-75fbbbf951c6)

### Further relevant clusters

 Power Configuration

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62570067/10147c10-3e37-4ac6-858b-6d742cfd3b96)

On/Off

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/62570067/5a1cb81b-5673-4fb6-bc78-7f32b13e2ecc)

### Electrical Measurement

Any other cluster of relevance/interest

My first attempt to provide this information - please bare with me!

**Comment by Smanar** [comment]
Hello have you tried to add your device 
On this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0041_1gang_bat.json For unlocked version
On this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_ja5osu5g_smart_button.json for locked version.

You will miss button event, but return will be visible in logs.
To add button event, just add your device in button_maps.json file
```

            "doc": "3-gang remote",
            "modelids": ["_TZ3000_yw5tvzsk", "_TZ3000_czuyt8lz","_TZ3000_ee8nrt2l", "_TZ3000_ygvf9xzp", "_TZ3000_t8hzpgnd", "_TZ3000_wkai4ga5", "_TZ3000_bi6lpsew", "_TZ3400_keyjhapk", "_TYZB02_key8kk7r", "_TZ3400_keyjqthh", "_TZ3400_key8kk7r", "_TZ3000_vp6clf9d", "_TYZB02_keyjqthh", "_TZ3000_peszejy7", "_TZ3000_qzjcsmar", "_TZ3000_owgcnkrh", "_TZ3000_adkvzooy", "_TZ3000_arfwfgoa", "_TZ3000_a7ouggvs", "_TZ3000_rrjr1q0u", "_TZ3000_abci1hiu", "_TZ3000_dfgbtub0", "_TZ3000_rco1yzb1", "_TZ3000_gbm10jnj", "_TZ3000_5e235jpa", "_TZ3000_sj7jbgks", "_TZ3000_w8jwkczz", "_TZ3000_dziaict4", "_TZ3000_famkxci2", "_TZ3000_itb0omhv", "_TZ3000_tzvbimpq", "_TZ3000_mh9px7cq", "_TZ3000_b7bxojrg", "_TZ3000_ufhtxr59", "_TZ3000_4upl1fcj", "_TZ3000_i3rjdrwu", "_TZ3000_w3c7ouru", "_TZ3000_abci1hiu","_TZ3000_wqcbzbae", "_TZ3000_pkeqinnt", "_TZ3000_uaa99arv", "_TZ3000_wbfgbpxq", "_TZ3000_fa9mlvja", "_TZ3000_tk3s5tyg", "_TZ3000_mrpevh8p", "_TZ3000_qgwcxxws"],
            "map": [
```

**Comment by Smanar** [comment]
You just need to edit files with a text editor, or with command line with tools like "nano" for exemple if you are headless.
What is your OS ?
