### ISSUE TITLE
deCONZ.app on macOS has incorrect version string

### ISSUE THREAD

**Issue by apolgar-ms** [dresden-elektronik/deconz-rest-plugin#7670]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Both the latest stable and beta builds (as of this writing, 2.25.3 and 2.26.1) of the macOS application report 2.22.0 in the application's version string.

### Steps to reproduce the behavior

In the Finder, select the application bundle, then go to File > Get Info.

### Expected behavior

The application version string should report the correct deCONZ version.

### Screenshots

<img width="379" alt="Screenshot 2024-03-16 at 3 19 42 PM" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163553813/e20eb5aa-e9ae-4210-bc74-9991dc457e02">
<img width="379" alt="Screenshot 2024-03-16 at 3 19 39 PM" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/163553813/4159e821-a583-4295-a724-967c59e755d1">

### Environment

- Host system: macOS Sonoma 14.4

**Comment by manup** [comment]
Thanks for the report. Fixed in [v2.26.2-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.26.2-beta), closing for now.
