### ISSUE TITLE
Namron 4512737 thermostat - error in consumption calculation

### ISSUE THREAD

**Issue by Emlben** [dresden-elektronik/deconz-rest-plugin#7673]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

The consumption part is missing a factor 100,
the consumption section should be:
```
"name": "state/consumption",
          "refresh.interval": 300,
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 0,
            "eval": "Item.val = Attr.val * 100"
          },
          "default": 0
```

### Steps to reproduce the behavior

observed error

### Expected behavior

increase the consumption number by 100 times

### Environment

- Host system: Raspberry Pi 
- Running method: Raspbian 
- Firmware version: (26400500)
- deCONZ version (not Home assistant Addon version!): v2.24.2
- Device: ConBee I 
- Do you use an USB extension cable: yes 
- Is there any other USB or serial devices connected to the host system? If so: Which? N/A

**Comment by SwoopX** [comment]
Is there maybe anybody out there having the device who can confirm this? It would be beneficial to also compare the device firmware versions, as we've rarely seen this changing between the versions.
