### ISSUE TITLE
 Device Request: TY0201 _TZ3000_bjawzodf

### ISSUE THREAD

**Issue by 4MeInfo** [dresden-elektronik/deconz-rest-plugin#7684]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

TY0201

### Manufacturer

Tuya

### Model identifier

_TZ3000_bjawzodf

### Device type to add

Sensor

### Node info

<img width="1057" alt="Bildschirmfoto 2024-03-28 um 21 18 21" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/ff722ff6-2382-47a7-b8a6-f5f21887cce1">

### Endpoints and clusters

<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 26 07" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/7e61f009-300f-45da-ae00-c66b1bd89a6d">
<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 
<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 25 23" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/c1dcddcd-ded1-4920-ae45-a6d1f9c6a7ed">
25 46" src="https://github.com
<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 25 13" src="https://github.com/dresden-ele
![Uploading Bildschirmfoto 2024-03-28 um 21.24.52.png…]()
ktronik/deconz-rest-plugin/assets/53448222/3374a
<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 24 36" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/2faa3d34-09d5-4b7a-bb05-2074f8d5d839">
bcd-5074-434f-9563-95d7daac512c">
/dresden-elektronik/deconz-rest-plugin/assets/53448222/af7bd224-799c-47a0-b114-7c80c22060cd">

### Basic

<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 19 10" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/1ea84660-2a1b-4c78-83f2-5786f3cedf5e">
<img width="1051" alt="Bildschirmfoto 2024-03-28 um 21 26 31" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/07998046-7053-4b7c-9406-ecd82335cdf8">

**Comment by 4MeInfo** [comment]
https://de.aliexpress.com/item/1005005454107609.html?spm=a2g0o.order_list.order_list_main.6.12fe5c5fyoZDaC&gatewayAdapt=glo2deu

**Comment by 4MeInfo** [comment]
https://de.aliexpress.com/item/1005005951863680.html?spm=a2g0o.order_detail.order_detail_item.19.571d6368Hbd0hu&gatewayAdapt=glo2deu

**Comment by 4MeInfo** [comment]
[_TZ3000_bjawzodf_temp_hum_sensor.json](https://github.com/dresden-elektronik/deconz-rest-plugin/files/14800970/_TZ3000_bjawzodf_temp_hum_sensor.json)

I modify some existing file and it works.
<img width="538" alt="Bildschirmfoto 2024-03-29 um 08 32 55" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/1a0302f6-1519-488a-ae9c-d1d742167d02">

**Comment by 4MeInfo** [comment]
[_TZ3000_bjawzodf.json](https://github.com/dresden-elektronik/deconz-rest-plugin/files/14801022/_TZ3000_bjawzodf.json)
<img width="538" alt="Bildschirmfoto 2024-03-29 um 08 32 55" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/53448222/07a02ed3-f3b0-4dc2-80ea-bd20744b1afb">

I modify some existing file and it works.

**Comment by Smanar** [comment]
Ha yes there is already a DDF, but not for the same model

```
  "manufacturername": "_TZE200_bjawzodf",
  "modelid": "TS0601",
```

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZE200_bjawzodf_humidity_temp.json

If it's the one you have modified, can you submit a PR ?

**Comment by 4MeInfo** [comment]
I used the [https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json)

**Comment by Smanar** [comment]
Ha yes, one DDF work with tuya cluster, the second one with classics clusters.
And your device have both ....

Lol, so impossible to guess without the device.

**Comment by TheNON75** [comment]
hi @SwoopX, 

what is the progress on this?
Just bought one myself too. Can I support you somehow?

**Comment by TheNON75** [comment]
Ok, I will try it later tonight

**Comment by TheNON75** [comment]
it is kind of weird stuff.
phoscon state: not reachable, measurements from yesterday are shown
deconz gui: temp and rh clusters shows recent data
REST API: same as phoscon

Let me know what information you need, I will try to provide them, however I will be busy during the weekend by running around

**Comment by Smanar** [comment]
Yep, the battery status can need some time.
Tell me if it works to make the PR, or you can make it too if yoy want, just need to add the model to this DDf https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0201_temp_hum_sensor.json

**Comment by TheNON75** [comment]
Well, battery and version are still not okay, but apart from this the device works.

Do you want to dig into it, or see it later if it can be fixed at all? If the latter, then please proceed with a pr.

**Comment by Smanar** [comment]
Can try to fix the batrtery first, perhaps this device need something not standard.
Can you check the cluster 0x0001, to see if the attributes 0x0021 is used ?

On the DDF, can try replace 

```
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          }
        },
```

by

```
        {
            "name":"config/battery",
            "refresh.interval": 86400,
            "read":{
                "at":"0x0021",
                "cl":"0x0001",
                "ep":1,
                "fn":"zcl:attr"
            },
            "parse":{
                "at":"0x0021",
                "cl":"0x0001",
                "ep":1,
                "eval":"Item.val = Attr.val/2"
            },
            "default":0
        },
```

**Comment by TheNON75** [comment]
The adjusted part is in place, waiting for updated data.

**Comment by TheNON75** [comment]
@Smanar after 24H the battery is still not updated. Fyi in the gui it show simply 76
![image](https://github.com/user-attachments/assets/708450dc-e829-48fc-aa44-5a5beb89d58e)

![image](https://github.com/user-attachments/assets/1bcf6a71-9e21-4045-921f-b71c00e8da57)

**Comment by Smanar** [comment]
76 ?
Your device have a dead battery, or this device don't need the / 2.
You haven't another battery to make try ?

Another thing, when you read a value in the GUI, it update the value in the API too, so you need to have a 76/2 value for battery now.

Else can you enable log in deconz with only flag "DDF", will be not too much talkative and try to read this value again ?

**Comment by TheNON75** [comment]
Battery is swapped with an Ikea vallhorn where the battery was reported to be 200.
The batteries from the tuya reported in Ikea as 166
The batteries from Ikea reported in Tuya as 192 (instead of 200, see above), but .... (!!!!!)
Apparently this value was reported after insertion. By the next reporting it became c0 (!!!), which is in fact 192....

<img width="251" alt="image" src="https://github.com/user-attachments/assets/bf35558c-8c24-4f3e-9a8f-b944a7b7e61b">

**Comment by Smanar** [comment]
So fisrt bug, it seem sometime deconz show hexa value instead of decimal.

So the battery level is good on the API, but not on Phoscon ?
This device create 2 entries, a ZHATEmperature and a ZHAHumidity, both have good battery level ? Perhaps Phoscon use the bad one ?

**Comment by TheNON75** [comment]
I went back to 2.22 recently as aqara sensors were reporting very sporadically, sometimes for 4-6hours no updates at all.

Correct, good in API but not in phoscon.
No, humidity battery level is 0% (parsing is missing) and I agree, phoscon picks the second one (0%)
Imo battery shall be kept only for one sensor or perhaps add zhabattery(?)

**Comment by TheNON75** [comment]
On 2.28.1 the battery is shown in phoscon properly (however this version is less good for aquaria sensors)
The device is currently not reachable but it is normal as decent was restarted recently due to switching to latest stable.

Only the version is not defined yet in ddf and so it is missing
<img width="722" alt="image" src="https://github.com/user-attachments/assets/3a0aa970-433d-4389-a76a-c0ee51efa7f7">

**Comment by Smanar** [comment]
It's definied on the DDF

```
        {
          "name": "attr/swversion",                   
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
```

You have put the DDF on the "tuya" folder ? there is a relative path.

>No, humidity battery level is 0% (parsing is missing) and I agree, phoscon picks the second one (0%)
Imo battery shall be kept only for one sensor or perhaps add zhabattery(?)...in the other hand, the same battery level can be reported to both sensors if this is the standard

So it work for an entry and not the other ?
I m checking the DDF again, and I m seing the same code

```
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          }
        },
```

Or you are using the modified code only on one of them ?

```
        {
            "name":"config/battery",
            "refresh.interval": 86400,
            "read":{
                "at":"0x0021",
                "cl":"0x0001",
                "ep":1,
                "fn":"zcl:attr"
            },
            "parse":{
                "at":"0x0021",
                "cl":"0x0001",
                "ep":1,
                "eval":"Item.val = Attr.val/2"
            },
            "default":0
        },
```

**Comment by TheNON75** [comment]
You're right, adjusted only one of the batteries (however in the latest stable it is picked and shown properly)

The file is in the ```
/opt/deCONZ/devices``` (I am on docker) folder and this explains why the js did not run. Do you want me to copy it over or we accept the theory "it should work"?

**Comment by Smanar** [comment]
>or we accept the theory "it should work"

Lol, yes I think we can, it's the same code on ALL tuya DDF.

So do you want to submit a PR or want I make it ?

**Comment by TheNON75** [comment]
Let's accept it should work :) If you don't mind, I would leave the pr for you to avoid that I screw up something accidentally

**Comment by Smanar** [comment]
Done > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7993

**Comment by TheNON75** [comment]
Thank you!
