### ISSUE TITLE
Possibility to trigger mesh healing?

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/deconz-rest-plugin#770]
Is there any mechanism to be able to trigger the mesh to heal?

**Comment by manup** [comment]
The mesh should heal on it's own. When routing fails new route discovery from the source node to the destination node will be started. This may take a while and prior to route discovery several attempts to send an request might be made.

Thats the theory :)

In practise meshing between different vendors has been challenging, the spec leaves some grey areas for interpretation so not all products work the same, mixing IKEA and Philips has caused troubles in the past. With firmware updates this will hopefully improve over time.

**Comment by Kane610** [comment]
Thanks for educating me @manup!
