### ISSUE TITLE
Rain Seer (Tuya) water valve -TS0049 by _TZ3210_0jxeoadc

### ISSUE THREAD

**Issue by Addamka84** [dresden-elektronik/deconz-rest-plugin#7709]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Rain Seer

### Manufacturer

_TZ3210_0jxeoadc

### Model identifier

TS0049

### Device type to add

Other

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/167032629/3e0ae287-0771-40bb-b8e7-f89ff178e0fb)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/167032629/6a4c9dee-1fdb-4d11-a585-fd082911094c)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/167032629/09f573bc-da09-43b3-a369-2d34cbaa4742)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/167032629/7f728ccb-282c-4dfa-b683-0971b1dcd91f)

### Further relevant clusters

In ZHA its been implemented (if its help): https://github.com/zigpy/zha-device-handlers/issues/2377

**Comment by dlondero** [comment]
Would be great to have this added!

**Comment by kkossev** [comment]
@ devs - pay attention to the fact that this TS049 device requires Tuya cluster command 0x04 (instead of the usual command 0x00) for the open/close commands, setting the irrigation timer, etc.

**Comment by yulasinio** [comment]
Is there any chance that this device can be added to ZHA? I just recently purchased one and would be great to be supported nativelly so I don't have to install Z2M
