### ISSUE TITLE
Tuya 4CH Zigbee Switch Module-L TS0014 _TZ3000_cxw02yp3

### ISSUE THREAD

**Issue by janstenpickle** [dresden-elektronik/deconz-rest-plugin#7710]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

4CH Zigbee Switch Module-L

### Manufacturer

_TZ3000_cxw02yp3

### Model identifier

TZ-0014

### Device type to add

Light

### Node info

<img width="382" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1926225/b78552e2-6a38-4c1d-a164-65eec23e8b4c">

### Endpoints and clusters

<img width="268" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1926225/ea56eafa-2d94-493d-b058-9cf84a11f8d9">

### Basic

<img width="393" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1926225/ad3b0fb2-8281-46a3-af4f-e1dd594f79cd">

### On/Off

<img width="382" alt="image" src="https://github.com/dresden-elektronik/deconz-rest-plugin/assets/1926225/4e92a837-a549-4d58-9734-f102683e066d">

**Comment by janstenpickle** [comment]
@Smanar sorry for the delay replying to you, I've only just had a chance to try this again. Thank you so much for this, it worked perfectly! 👌

**Comment by Smanar** [comment]
Nice, do you to make the PR ?
Or want I make it ? to have it officialy.
