### ISSUE TITLE
Rule don't fire with deCONZ 2.05.37

### ISSUE THREAD

**Issue by Krocko** [dresden-elektronik/deconz-rest-plugin#772]
The following rule don‘t work anymore. If i go back to 2.05.35 the rule is working again. 
`/sensors/14` is the daylight sensor and `/sensors/35` is a ClipGenericFlag sensor. The rule should turn on the ClipGenericFlag sensor and turn off all lights shortly after deCONZ has started. As i said on deCONZ 2.05.35 this works perfect. 

` {
    "actions": [
      {
        "address": "/sensors/35/state",
        "body": {
          "flag": true
        },
        "method": "PUT"
      },
      {
        "address": "/groups/0/action",
        "body": {
          "on": false
        },
        "method": "PUT"
      }
    ],
    "conditions": [
      {
        "address": "/sensors/14/state/lastupdated",
        "operator": "ddx",
        "value": "PT00:00:02"
      },
      {
        "address": "/sensors/35/state/flag",
        "operator": "eq",
        "value": "false"
      }
    ],
    "name": "Boot Time",
    "periodic": 0,
    "status": "enabled"
  }`

**Comment by manup** [comment]
>So the deCONZ start is slower as with the previous versions?

Yes, .37 is slower at starting due some changes to support full lights restore.
See release notes: https://github.com/dresden-elektronik/deconz-rest-plugin/releases

This will be optimized in next versions.
