### ISSUE TITLE
Aqara Dual Relay Module T2

### ISSUE THREAD

**Issue by moddavid** [dresden-elektronik/deconz-rest-plugin#7720]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Aqara Dual Relay Module T2 (DCM-K01)

### Manufacturer

Xiaomi Aqara LUMI

### Model identifier

lumi.switch.acn047

### Device type to add

Switch

### Node info

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/3b3288d0-85c5-4b4b-b2de-4d616056f0bb)

### Endpoints and clusters

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/8f669db6-9c2b-425f-8d3d-454a19b6dfd2)

### Basic

![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/5551514c-616f-4616-9ace-7a898643e847)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/933a27e1-6145-46ed-b23f-a5ba89bb29d2)

### Electric Measurement
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/2fc91047-e0f4-4acc-b5b5-eccac7b6822a)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/5a65f7a5-7f71-4351-bc68-8e83e9e484f5)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/cdfc3ecf-0bfa-47a0-b717-cc7204b62e70)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/39ca07b5-d987-4cc1-91b1-30a873a20ea9)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/d2aeba28-0e9b-4905-9d54-b05aad7b5af2)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/95c9ab56-974d-49a7-9c9c-511410accb10)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/7f42a5a3-63b5-46b4-93fb-58eedfb72030)

### Simple Metering
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/f75985a7-1cb3-453d-9e99-2f330dda3705)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/b2bd2e37-8e68-4e5f-b881-a121843b2715)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/4df02639-3210-478a-8ebb-72dc72f1ee9c)

### Multistate Input (Basic)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/478abed6-dad3-4e49-9a73-dcc0f1ec7dc5)

### On/Off
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/ef62811c-d4b0-4e0d-8deb-c963db4e0b90)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/74086c4e-733d-4341-89fb-cf6ee028c359)

### Lumi Specific
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/e74f2117-464e-4358-95be-eb28b49306c9)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/e21e47a7-84cb-4fdf-8b5c-6d76c1e60a76)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/55e2d177-661f-4353-ab26-070e89234284)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/34506f9e-c05a-4575-9783-b85b6c354ec5)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/05a8123e-370a-4cf5-95b6-7ad167298315)

### Analog Input (Basic)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/59a52fb2-01e8-43fa-b779-5e1d6f1467d5)

### Additional information
Phoscon shows it currently as two On/Off lights. I have installed the T2 behind my existing roller shader switch to make it smart. While moving the shader up by activating the corresponding "light" worked, the other "light" for the down movement didn't do anything.
I'm running the docker image deconzcommunity/deconz:2.26.3 on an Intel NUC with Conbee II.

**Comment by SwoopX** [comment]
Hi there.

Unfortunately, the screenshots indicate that the clusters have not been read properly. [This page](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#read-device-clusters) explains how to read clusters. Please take new ones and update the issue accordingly. Thanks a lot!

**Comment by gee-jay-bee** [comment]
Screenshots taken in order shown (hope this is correct …):

![IMG_6424](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/acc60438-a704-4c76-8ec7-63685b2175d7)
![IMG_6425](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/4af0a1c8-056b-40e9-9207-772ec41482bc)
![IMG_6426](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/0ed2bed5-2791-467d-8752-d93ceead2137)
![IMG_6427](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/21c92180-e10f-422b-9bfc-ea429b0427da)
![IMG_6428](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/c8efa087-536e-4bfa-b1a1-6c32dc85537d)
![IMG_6429](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/de0416bb-80be-43f3-a32e-9d68f4c0543d)
![IMG_6430](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/d08ff9c1-6f90-4dfc-ad42-3a28d3d87770)
![IMG_6431](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/59c43046-8df6-427f-b3d2-35e686bd7e88)
![IMG_6432](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/b69c2ccb-2d50-4e0c-ac3a-6bb0f6ab26cd)
![IMG_6433](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/35b043aa-c033-4990-990c-c8bf410a3808)
![IMG_6434](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/1486143d-e36b-4571-895a-a83f1d1c4b97)
![IMG_6435](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/a6564226-792f-4c52-b743-41054f372c87)
![IMG_6436](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/85f9774b-2d2d-4c8d-bce6-1d89499dc37b)
![IMG_6437](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/ddc8e708-90a5-48ca-8395-c1e73b3e8dbf)
![IMG_6438](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/2987d50e-c755-4d29-bfdd-d3188bc657f6)
![IMG_6439](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/904eaa9d-d2a7-4b57-9e74-2835b484566b)
![IMG_6440](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/9aaf7312-432c-4b9f-9ca7-4146f0e1675d)
![IMG_6441](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/2158d94c-9149-4487-9be1-29c9cba5a360)
![IMG_6442](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/01243d5b-d930-4e85-9dda-4586dd9df0ac)
![IMG_6443](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/58dbcf2a-3bec-4af0-970c-122c675b2d96)
![IMG_6444](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/44155115/b88a7dc5-c2a6-40e3-bb0f-e7a72cf175a6)

**Comment by moddavid** [comment]
@SwoopX sorry for the delay, here are the new screenshots:

Node Info
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/0299db4b-f48a-4896-abab-bcd5a6343d80)


Endpoints and clusters
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/63a607c2-aee1-44ab-86cd-216b58c376da)


Basic
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/1401c22b-152a-43ce-8228-df0cfccc5266)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/0748feaf-89ca-4e77-9a0e-e50b62463fd8)


Electric Measurement
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/57c9df7c-2ef1-45c4-ae5e-95399995fb92)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/da5c50d8-5b99-458a-9cf1-4f435740e067)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/49786f16-f9f7-44a0-beef-59a08d15b62a)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/effa4614-8025-477b-bef3-9d694bf568df)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/8a3fa922-4dab-4c9b-bcda-3b70ee5f164d)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/e4349e6f-ab7b-47b5-9a64-49a6142f2eb3)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/15ce669e-e5e1-4875-8b9b-71dc254daa3b)


Simple Metering
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/8dd7db63-0b85-43b1-8e3f-bfe19e909c84)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/23129164-497a-4c36-9d5c-aea352b4841f)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/3c285ca0-2728-499c-ba6e-6ee3b030d8c9)


Multistate Input (Basic)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/1a57837f-7776-457a-8f0b-e0be7d45bd40)


On/Off
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/29712369-a062-4432-8a79-c22b0e68c85a)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/c23371a8-3962-46d6-8f6c-c90917d9377b)


Lumi Specific
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/da10af99-7b60-4826-9bd3-e201bc6dd639)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/f54fb7d3-acaf-4618-b32e-26d4e71345bc)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/47a2fbe0-8104-4afe-ae08-3c5e1a874506)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/6248abdb-0d47-45a6-9c32-c748425ccd89)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/96f27f95-c9d2-424a-ac8c-3161bdf01782)

Lumi Specific (second device - this is the only one which was different)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/7d0f07bc-4572-48f1-bcf5-19700f90458b)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/f8c70672-d453-4512-b0c2-e0ab3c8f96aa)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/14a0acc8-c339-4676-97bb-fb36742da120)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/2b8258e7-ab07-463d-b14e-31d67b9f3e43)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/3924ad35-58ca-4a06-a69c-b3c395856b60)


Analog Input (Basic)
![grafik](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9865358/4a65ddd9-3f39-4e59-b85c-95577a92004b)


This time both up and down movement worked just fine, I'm not sure why it didn't work the last time.

**Comment by moddavid** [comment]
Anything we can do here?
For me right now two options are missing: Measuring the power consumption (like the Aqara smart plug SP-EUC01 - 
lumi.plug.maeu01) and the child lock (like the Aqara Thermostat E1 - lumi.airrtc.agl001).

**Comment by gee-jay-bee** [comment]
Fwiw, I was experiencing some challenges with Deconz + Conbee II and finally took a chance on Zigbee2mqtt with a newer USB coordinator. This T2 is natively supported there and good news is the drop-out issue I was seeing isn't happening. There is power reporting (though it seems to be the combined power of both relays) but I don't see child lock. You can disconnect the relays from the inputs.

Deconz served me well for many years and I hope the new DDF strategy can accelerate device on-boarding. Good luck!

**Comment by moddavid** [comment]
I would rather don't stale this ticket for now. Maybe I find some time to compare the DDF files from the mentioned other devices to see if I get it somehow to work as intended.

**Comment by SwoopX** [comment]
I'll share a DDF candidate within the next days

**Comment by sch115** [comment]
Hello to all!
I ran into a issue with energy consumption statistics. Voltage and watts numbers are OK but Total Consumption in kWh is 1000 time higher. I believe this link was based on the same problem as mentioned: https://github.com/Koenkk/zigbee2mqtt/issues/22148

Current versions:
Raspbian GNU/Linux Bullseye (11)
Homebridge 1.8.4
deCONZ version 2.28.1
ConbeeII 26780700
lumi.switch.acn047 0.0.0_0030

Everything else looks good to me.
Thank you for your help!
