### ISSUE TITLE
_TZ3000_zl1kmjqx Temperatur Humidity sensor

### ISSUE THREAD

**Issue by amnesia106** [dresden-elektronik/deconz-rest-plugin#7738]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

_TZ3000_zl1kmjqx

### Manufacturer

_TZ3000_zl1kmjqx

### Model identifier

TY0201

### Device type to add

Sensor

### Node info

![nodeinfo](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/40226796/6ff1fc2e-da4f-4696-8241-83beb8a0bc37)

### Endpoints and clusters

![cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/40226796/501ff27e-9daa-4055-b90d-058399f5efb9)

### Basic

![basic](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/40226796/2bf6651d-96a5-44e3-96e4-f912f372b1ae)

### Any other cluster of relevance/interest

![hum](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/40226796/53c91102-96b5-4947-97ac-6b90ab6a687c)

![temp](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/40226796/3f6b869e-f9d9-4cd5-b951-84a42ea8fb5c)

**Comment by Smanar** [comment]
It seem it's just a classic device that don't need the tuya cluster, but need the tuya unlock sequence
Can try rhis DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZ3000_zl1kmjqx",
  "modelid": "TY0201",
  "vendor": "Tuya",
  "product": "Temperature and humidity locked sensor",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "config/offset"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "config/tuya_unlock"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "awake": true
        }
      ]
    },
    {
      "type": "$TYPE_HUMIDITY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0405"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",                   
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "config/offset"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/humidity",
          "awake": true
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 84600,
          "change": "0x00000002"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 300,
          "change": "0x00000064"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 60,
          "max": 300,
          "change": "0x00000064"
        }
      ]
    }
  ]
}
```

**Comment by amnesia106** [comment]
How can i change that?

**Comment by Smanar** [comment]
Depend of OS, what is your ?
You just need to create a text file called whatyouwant.json in a "devices" folder with this contain. But the "devices" folder location depend of OS.

**Comment by amnesia106** [comment]
> It seem it's just a classic device that don't need the tuya cluster, but need the tuya unlock sequence Can try rhis DDF
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TZ3000_zl1kmjqx",
>   "modelid": "TY0201",
>   "vendor": "Tuya",
>   "product": "Temperature and humidity locked sensor",
>   "sleeper": true,
>   "status": "Gold",
>   "subdevices": [
>     {
>       "type": "$TYPE_TEMPERATURE_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0402"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion",                   
>           "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
>           "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/battery",
>           "awake": true,
>           "parse": {
>             "at": "0x0021",
>             "cl": "0x0001",
>             "ep": 1,
>             "eval": "Item.val = Attr.val / 2;",
>             "fn": "zcl:attr"
>           }
>         },
>         {
>           "name": "config/offset"
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "config/tuya_unlock"
>         },
>         {
>           "name": "state/lastupdated"
>         },
>         {
>           "name": "state/temperature",
>           "awake": true
>         }
>       ]
>     },
>     {
>       "type": "$TYPE_HUMIDITY_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0405"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion",                   
>           "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
>           "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/battery",
>           "awake": true,
>           "parse": {
>             "at": "0x0021",
>             "cl": "0x0001",
>             "ep": 1,
>             "eval": "Item.val = Attr.val / 2;",
>             "fn": "zcl:attr"
>           }
>         },
>         {
>           "name": "config/offset"
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "state/humidity",
>           "awake": true
>         },
>         {
>           "name": "state/lastupdated"
>         }
>       ]
>     }
>   ],
>   "bindings": [
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0001",
>       "report": [
>         {
>           "at": "0x0021",
>           "dt": "0x20",
>           "min": 3600,
>           "max": 84600,
>           "change": "0x00000002"
>         }
>       ]
>     },
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0402",
>       "report": [
>         {
>           "at": "0x0000",
>           "dt": "0x29",
>           "min": 60,
>           "max": 300,
>           "change": "0x00000064"
>         }
>       ]
>     },
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0405",
>       "report": [
>         {
>           "at": "0x0000",
>           "dt": "0x21",
>           "min": 60,
>           "max": 300,
>           "change": "0x00000064"
>         }
>       ]
>     }
>   ]
> }
> ```

This DDF Works - Thanks !

**Comment by MalSve** [comment]
Were do i put the textfile?

**Comment by Smanar** [comment]
Depend of OS.
On classic OS

All DDF provided directly with deCONZ typically reside in `/usr/share/deCONZ/devices/` on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. `/home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices`) will override the pre-packaged files to allow users to amend and keep their own files if desired.
