### ISSUE TITLE
New Tuya soil sensor variant

### ISSUE THREAD

**Issue by CaptainTK** [dresden-elektronik/deconz-rest-plugin#7752]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Luminea Home Control ZX-8588 (Pearl)

### Manufacturer

_TZE200_9cqcpkgb

### Model identifier

TS0601

### Device type to add

Sensor

### Node info

![ _TZE200_9cqcpkgb_node](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14875435/db43eccb-200e-44ef-b370-e0d277aee822)

### Endpoints and clusters

![ _TZE200_9cqcpkgb_endpoints](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14875435/227d251f-d2c0-44f8-8702-ca652a980ca6)

### Basic

![ _TZE200_9cqcpkgb_cluster](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/14875435/328b1978-46d0-4c68-b117-bdf33cd68cfb)

### Further relevant clusters

Appears to be the same as [_TZE200_myd45weu](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6731), just with Manufacturer Name _TZE200_9cqcpkgb. I modified and renamed the DDF of _TZE200_myd45weu and it works well for me. Would be great if you could include it as a standard.

**Comment by Smanar** [comment]
Thx for information, done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7753
