### ISSUE TITLE
Third Reality 3RDS17BZ Door/Window Contact

### ISSUE THREAD

**Issue by Heiko1977** [dresden-elektronik/deconz-rest-plugin#7756]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Third Reality, Inc

### Manufacturer

Third Reality, Inc

### Model identifier

3RDS17BZ

### Device type to add

Sensor

### Node info

![NodeInfo](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/9e237c93-9b55-4e70-957d-d09f09ed66d9)

### Endpoints and clusters

![ClusterInfo](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/623a38af-d494-4a1b-a467-49a5eb126b85)
![Screenshot 2024-05-10 103150](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/1b3f0f06-3718-423e-8a24-65d5f6c505df)
![Screenshot 2024-05-10 103126](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/a6f9e732-f832-4e69-86e0-1d4283f43767)

### Basic

![Attributes](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/26a8ed41-f32d-472f-8b52-480e3ae1db05)

### Power Configuration
![Screenshot 2024-05-10 103753](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/48fcce78-3360-441e-9cff-fa3a3e7a3330)

### On/Off
![Screenshot 2024-05-10 103845](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/dbd2eead-b168-402f-97ae-d6057ac29d80)
![Screenshot 2024-05-10 103854](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/35807137/35f6136d-e1d0-4ab8-997f-2d1f2c9f3006)

**Comment by Heiko1977** [comment]
Perfect, works fine.

Thank you very much !!!

**Comment by Smanar** [comment]
No issue ?
Do you want to make the PR to submit the device or want I make it ?

**Comment by Heiko1977** [comment]
I’ve added 4 of them into deconz. Phoscon added them without a problem. States are fine.

if you like, you can submit it. 

Thanks for your work.

**Comment by Smanar** [comment]
>if you like, you can submit it.

I prefer, to have it under you name, I can explain how to do it if needed  ...

**Comment by Heiko1977** [comment]
> > if you like, you can submit it.
> 
> I prefer, to have it under you name, I can explain how to do it if needed ...

That would be very nice. I’ve never done it before.

**Comment by Smanar** [comment]
Easy:
- go on this page https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices/third_reality
- select "add file" (as name can use 3RDS17BZ_door_sensor.json
- The magic will happen, github will create a fork on your name, and switch to editor mode.
- Copy/paste the file, and make chnage you want.
- Save it
- Github will purpose you to make a PR automatically (but I m not sure, on my side I m using an application), else on your fork (the adress will be https://github.com/Heiko1977/deconz-rest-plugin) select "pull request" on follow github.

You PR will appear here https://github.com/dresden-elektronik/deconz-rest-plugin/issues

After that all change you will make on your fork, will be synchronised on this page, so if there is problem, no need to restart all.

Edit:
Have just see this page https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to-create-a-pull-request-to-submit-a-new-Device-Description-File
