### ISSUE TITLE
Simultaneous APSDE Requests

### ISSUE THREAD

**Issue by SwampNinja** [dresden-elektronik/deconz-rest-plugin#776]
I've noticed that if I were to send a MgmtLqiReq to enumerate the neighbor table simultaneously alongside an ActiveEpReqMsg, that it drops the second one. I get a ‘CONFIRM’ back, but no ‘INDICATION’.

Given that, I had a couple of questions:

1. Is there a limitation in terms of max # of outstanding APSDE requests I can issue to the 0000 NWK address (i.e the radio itself)? Currently, it looks like that is 1.
2. Is there a limitation in terms of max # of outstanding APSDE requests I can issue to other addresses in the network? I presume there is because of the bounded number of buffers present on the radio?

**Comment by manup** [comment]
The firmware supports multiple parallel APS requests, in fact deCONZ uses this a lot. Please make sure to use latest firmware version 0x26230500.

> 1. Is there a limitation in terms of max # of outstanding APSDE requests I can issue to the 0000 NWK address (i.e the radio itself)? Currently, it looks like that is 1.

I'll need to check this, but theoretically they are processed so fast (only loop back) that you shouldn't hit a limit given that you process the confirm and indications commands right away.

> 2. Is there a limitation in terms of max # of outstanding APSDE requests I can issue to other addresses in the network? I presume there is because of the bounded number of buffers present on the radio?

The total request amount is 8.

However you always should check the `APSDE-DATA.request free slots flag (0x20)` of the DEVICE_STATE (0x07) response before issuing a new request to the firmware.
