### ISSUE TITLE
Ikea Starkvind (air purifier) not providing the status thru REST-API after DECONZ update to v2.27.0-beta

### ISSUE THREAD

**Issue by kimosak** [dresden-elektronik/deconz-rest-plugin#7775]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

With DECONZ v2.27.0-beta airputifier stopped providing states thru API - there is only lastupdated, the rest is missing (deviceruntime, filterruntime, lastupdated, replacefilter, speed..)

Actual API output:
{"config":{"on":true,"reachable":true},"ep":1,"etag":"4a8fa5a53c922c754d4b69e3a23ce16a","lastannounced":"2024-04-01T15:30:16Z","lastseen":"2024-05-16T12:51Z","manufacturername":"IKEA of Sweden","modelid":"STARKVIND Air purifier table","name":"Cisticka vzduchu Ikea","state":{"lastupdated":"2024-05-14T18:23:08.819"},"swversion":"1.1.001","type":"ZHAAirPurifier","uniqueid":"50:32:5f:ff:fe:b4:ab:f8-01-fc7d"}

DECONZ attributes
![Screenshot 2024-05-16 150052](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66570437/aa67d6b8-a784-4b4b-ab4b-bdf65c9ba510)

### Steps to reproduce the behavior

It appears from latest DECONZ update

### Expected behavior

Fix the REST API for Ikea Air Purifier

### Environment

- Host system: (Raspberry Pi3b
- Running method: Raspbian
- Firmware version: (26780700)
- deCONZ version (not Home assistant Addon version!): (v2.27.0-beta)
- Device: RaspBee II

**Comment by kimosak** [comment]
Not 100% sure (2.25.2?), is there any way how to check it?

**Comment by Mimiix** [comment]
In that case,

please check:
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7246

**Comment by kimosak** [comment]
Will do, thank you very much :)

**Comment by kimosak** [comment]
Have I missed something? I checked #7246, but I am none the wiser. I’ve tried to update the DDF for the STARKVIND Air purifier from the deCONZ Toolbox, but there was no change. Also, there are no items under the DDF editor in deCONZ
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66570437/23da495b-cb87-448a-9d97-584920b78723)

**Comment by ebaauw** [comment]
Looks like the DDF wasn't applied?

**Comment by kimosak** [comment]
Basic mode and Gold status in Control panel, should I try anything else?

**Comment by Smanar** [comment]
Do the node have a little "DDF" displayed on titlebar ?
The "gold" for status in the editor is from you ?

How have you updated the DDF ?

**Comment by kimosak** [comment]
No "DDF" icon on title bar
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66570437/46dd3a30-6383-4af2-ad4b-aee5f73cce91)

I've tried to update DDF thru Phoscon web app but no luck, still missing the states from device
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66570437/00f133d8-7840-4fc6-92af-3df6a5baf78c)

Can I solve it by re-pairing of the device in deCONZ?

**Comment by Zehir** [comment]
The Device integration page use DDF bundle, not the DDF json file.

Could you try with this DDF Bundle ?

https://ddf.cryonet.io/bundle/download/ada38fd25cbc1fc9b4da0b86e8af1b4ed659f1074470916bbd9ea6288ef448fc

**Comment by kimosak** [comment]
I did it like first troubleshoot step and the Device integration report - Import successfull.  However, there was no change. The states are still not being reported through the RestAPI.

**Comment by Zehir** [comment]
Any updates on the deconz gui ?

**Comment by kimosak** [comment]
No change in GUI and DDF editor is still empty
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66570437/e422b983-65ff-4bc4-8ed2-cc586d98eab1)

**Comment by Zehir** [comment]
No DDF or DDB on the node ?

**Comment by kimosak** [comment]
What is DDB? I see onlu this on the node 
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/66570437/c3f94760-c5cf-4ca2-858f-30a6346c691b)
and the DDF Editor is empty, no content/device here

**Comment by Zehir** [comment]
DDB is a DDF bundle, the new feature in 2.27.0, a new way to import DDF in a single file.

It's seems that is there something wrong in your installation.
Did you try to install the last stable version ?

**Comment by kimosak** [comment]
Thank you @Zehir , downgrading deconz from 2.27.0-beta to 2.26.3 helped. Now I see the DDF and device reports the states thru rest-API. I will stay on this stable version now.

**Comment by Zehir** [comment]
Yes the 2.27 need more love to work perfectly, like everything, works in the lab but not in production ;)

**Comment by Smanar** [comment]
So there is something in Version 0.27 that prevent deconz use a DDF bundle AND json ?

**Comment by manup** [comment]
Hi had anyone the chance to test if this is fixed with version v2.27.2-beta?

**Comment by kimosak** [comment]
No, I am still on stable v2.26.3

**Comment by kimosak** [comment]
Yes and it is still same, not able to controll device thru API like in 2.26.3

**Comment by manup** [comment]
Does the device show the DDF label on the node in the deCONZ UI?

**Comment by kimosak** [comment]
Yes, DDF is visible in deCONZ UI

**Comment by manup** [comment]
Here in my test setup with v2.27.3-beta the device can be controlled via API and also reports changes done on the device back to the API.

```json
{
  "config": {
    "filterlifetime": 259200,
    "ledindication": true,
    "locked": false,
    "mode": "speed_2",
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "3f28aadd46c9bfed7234135ea277ed6b",
  "lastannounced": null,
  "lastseen": "2024-06-12T14:33Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "STARKVIND Air purifier",
  "name": "AirPurifier 343",
  "productid": "E2007",
  "state": {
    "deviceruntime": 37944,
    "filterruntime": 37944,
    "lastupdated": "2024-06-12T14:34:00.606",
    "replacefilter": false,
    "speed": 40
  },
  "swversion": "1.0.033",
  "type": "ZHAAirPurifier",
  "uniqueid": "0c:43:14:ff:fe:6e:65:55-01-fc7d"
}
```

Now setting a different speed:

```
curl -X PUT -d '{"mode":"speed_4"}' 127.0.0.1:8090/api/12345/sensors/343/config
```

```json
[{"success":{"/sensors/343/config/mode":"speed_4"}}]
```

Which also reports back as speed_4 and the damn thing is loud as hell:

```json
{
  "config": {
    "filterlifetime": 259200,
    "ledindication": true,
    "locked": false,
    "mode": "speed_4",
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "bd2f952d339277ac82fcbdbd8229c49c",
  "lastannounced": null,
  "lastseen": "2024-06-12T14:35Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "STARKVIND Air purifier",
  "name": "AirPurifier 343",
  "productid": "E2007",
  "state": {
    "deviceruntime": 37946,
    "filterruntime": 37946,
    "lastupdated": "2024-06-12T14:35:44.965",
    "replacefilter": false,
    "speed": 80
  },
  "swversion": "1.0.033",
  "type": "ZHAAirPurifier",
  "uniqueid": "0c:43:14:ff:fe:6e:65:55-01-fc7d"
}
```

Can you please share how your API output looks like when doing this?

**Comment by manup** [comment]
Hi could anybody with the issue retest with v2.27.4-beta?

**Comment by manup** [comment]
Closing for now please, please re-open if the issue can still be seen with v2.27.4-beta and up.
