### ISSUE TITLE
Trådfri Smart Plug

### ISSUE THREAD

**Issue by MrPsi** [dresden-elektronik/deconz-rest-plugin#779]
Hi,

Do you think the new Trådfri smart plug will work with deconz right away when it is released? Or does support have to be added?
https://www.ikea.com/se/sv/catalog/products/90356166/

Maybe hard to know before it has been released? :)

**Comment by ebaauw** [comment]
Controlling the plug through the `/lights` resource will probably work without any changes.  Supporting the new on/off switch and any metering the plug might provide will require changes.

**Comment by maxlein** [comment]
I just bought the new Outlet and it seems that it doesn't work with the current version. Gateway shows only my motion sensor. Is it configuration that needs to be changed or code?

**Comment by ebaauw** [comment]
Could you post deCONZ GUI screenshots of:
- The node, incl. the endpoints and clusters;
- the _Node info_ panel;
- The _Cluster info_ panel of the _Basic_ cluster, **after** reading the attributes;

**Comment by maxlein** [comment]
I am new to deconz, so I don't know if this is the right information:
Cluster info of the basic cluster I don't understand. I only see basic cluster info on the Osram plug.

![image](https://user-images.githubusercontent.com/11796203/45599292-41f69e00-b9e9-11e8-930d-292ab19c5103.png)
![image](https://user-images.githubusercontent.com/11796203/45599315-86823980-b9e9-11e8-8d67-9d6b51f48006.png)

**Comment by maxlein** [comment]
No, I have a Osram plug and an Ikea. But the ikea one doesn‘t even show up. I think I tried the old and new web gui to search for devices, but nothing but the already connected devices were found.

**Comment by manup** [comment]
Does it have a reset button or something like that?

Note: IKEA devices usually only try **once** to join the network.

* If they are factory new (which should be the case here)
* Directly after they are powered (light search must be started before that)

**Comment by maxlein** [comment]
No, I couldn't find one. The motion sensor has a button but not the plug, at least not on the surface.
Will have a look at it again whn I am home today.

**Comment by maxlein** [comment]
So the default app you have, gives me this screen:
![image](https://user-images.githubusercontent.com/11796203/45642219-e7784300-bab7-11e8-8ea2-8e666824263d.png)
Blink worked, but I can't see the plug anywhere but on this page.
The other app finds nothing:
![image](https://user-images.githubusercontent.com/11796203/45642311-21494980-bab8-11e8-9cb8-2559a47646e4.png)

**Comment by manup** [comment]
Looks like the plug is already assigned to another network, so it needs to be reset. You may try using the red reset button in the old webapp, the plug needs to be very close to the gateway.

As alternative you can use a Hue dimmer switch to reset the plug, holding it very close to it and press buttons <key>I</key> and <key>O</key> for over 10 seconds.

**Comment by zladukas** [comment]
@maxlein, 
manual says:

FACTORY RESET YOUR DEVICE For control outlet:
Push a pin into the pinhole on bottom of the control outlet for at least 5 seconds.

use it to pair device.

**Comment by maxlein** [comment]
Thanks @zladukas, I threw the manual away and I could not find anything online!
I can see the plug now in decent gui. 
![image](https://user-images.githubusercontent.com/11796203/45646171-e26cc100-bac2-11e8-8951-3c1416e298ee.png)

**Comment by manup** [comment]
Cool, interesting, so it doesn't have power measurement but as a goody it seems to support ZigBee Green Power which is needed to route Hue tab and soon to be released ZGP switches.

Is it shown in the Phoscon App under lights?

**Comment by ebaauw** [comment]
And, apparently, a different manufacturer, looking at the mac address.  (I should have done so earlier and recognised the first screenshot it was an OSRAM plug).

There's apparently an inconsistency in general.xml: the generic (ZigBee 3.0) device 0x010a is an `On/off plugin unit` without a `-`, the 0x0010 ZHA and ZLL devices are `On/off plug-in unit`.  Would this device ID be ZigBee 3.0 enough for the Hue bridge to support this plug?

> soon to be released ZGP switches

Interesting...

I think we still need deCONZ to configure the ZGP enabled routers or the ZGP devices will only work when in direct range of the RaspBee or ConBee, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/117.

**Comment by manup** [comment]
>There's apparently an inconsistency in general.xml: the generic (ZigBee 3.0) device 0x010a is an On/off plugin unit without a -, the 0x0010 ZHA and ZLL devices are On/off plug-in unit. Would this device ID be ZigBee 3.0 enough for the Hue bridge to support this plug?

Not sure, maybe but we only know for sure after testing.

>I think we still need deCONZ to configure the ZGP enabled routers or the ZGP devices will only work when in direct range of the RaspBee or ConBee, see #117.

Absolutely, I sadly hadn't time yet to dig deeper in the ZGP spec, hopefully it's not too complicated to configure the ZGP proxies.

**Comment by maxlein** [comment]
Yes, it shows in the Phsoscon app. Its also working in openhab through hue binding and in homekit. (y)

**Comment by Filialen** [comment]
IKEA now has released the package including both the plug and the new on/off switch.
Here are the details of the switch…

![skarmklipp](https://user-images.githubusercontent.com/36641760/45903534-57553900-bdea-11e8-9025-d366a5dcd2ce.PNG)

![skarmklipp2](https://user-images.githubusercontent.com/36641760/45903546-5f14dd80-bdea-11e8-97a8-5b44c7b28a11.PNG)

**Comment by sweebee** [comment]
Is the smart plug and remote already working? I cant get them paired. If it should work, how should i pair them?

**Comment by manup** [comment]
>manual says:

>FACTORY RESET YOUR DEVICE For control outlet:
>Push a pin into the pinhole on bottom of the control outlet for at least 5 seconds.
>
>use it to pair device.

From a previous comment.

The remote isn't supported yet. See also [Supported Devices](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#unsupported-switches)

**Comment by sweebee** [comment]
Hm, i resetted it with the 5s method. Activated search for lights mode in deconz, but nothing shows up.

**Comment by RudolfRendier** [comment]
Make sure the relay clicks (twice?) and the light on the device starts blinking.
For me it does show up when searching for lights.

**Comment by manup** [comment]
Often, at least in case of the IKEA bulbs, the device needs to be power cycled once after the reset in order to start joining.

**Comment by maxlein** [comment]
Well, I got the remote working. I just press the connect button a few times close to the antenna.
And with the plug, I just hold reset near the antenna, like described above from @zladukas

**Comment by jurriaan** [comment]
> The remote isn't supported yet. See also Supported Devices

@manup What's the issue with these switches, can I help with something to get them supported?

**Comment by robinjoh90** [comment]
> Well, I got the remote working. I just press the connect button a few times close to the antenna.
> And with the plug, I just hold reset near the antenna, like described above from @zladukas

@maxlein how did you add the remote? What type of switch did you choose when adding it?

**Comment by maxlein** [comment]
Are you talking about the remote, or the switch for the plug? 
I am talking about the remote with the 5 diefferent buttons. And as I said, just pressing the rear connect button a few times near the antenna with an open gateway did the trick.

**Comment by Filialen** [comment]
> I am talking about the remote with the 5 diefferent buttons. And as I said, just pressing the rear connect button a few times near the antenna with an open gateway did the trick.

We are talking about the small switch sold with the plug…
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/779#issuecomment-423656286
Of course, the remote control works. It has done that for a long time!

**Comment by manup** [comment]
Closing this for now since the plug is supported, for the on/off remote the discussion is continued in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/853

**Comment by mloebl** [comment]
Has anyone tried adding a smart plug recently?  I am running  2.05.50 and just got a couple of the smart plugs.  I did the reset thru the pin hole and they paired and showed up on my network, looking like the screen shots above in the deCONZ app.  I can also can control on/off them thru the deCONZ app.  However they are not showing up anywhere within the Phoscon app.  They do however seem to respond to All Lights off.

**Comment by 8engan** [comment]
For anyone else googling for this.
Do not give up, it took me a while but eventually I got it working and I think this was what made it work.
1. Add new light in phoscon
2. Reset plug (needle in bottom hole for 5 seconds, light starts cycling)
3. It showed up :)

**Comment by Cavemanz** [comment]
I bought 2 of these today hoping to pair them with Conbee/Deconz. No matter what order I try to reset the plugs, nothing happens in the logs of the Deconz Docker. Ive tried more or less everything in this thread, and others. What am I missing?:(

Ive updated to the latest release of deconz and the latest firmware for Conbee.

**Comment by manup** [comment]
I've paired one yesterday, here is what I did:

1. Start light search in Phoscon App
2. Press the button with a needle for approx. 10 seconds
3. Pull out the plug from power, reinsert after 5 seconds

It was then discovered quickly.

**Comment by Cavemanz** [comment]
> I've paired one yesterday, here is what I did:
> 
> 1. Start light search in Phoscon App
> 2. Press the button with a needle for approx. 10 seconds
> 3. Pull out the plug from power, reinsert after 5 seconds
> 
> It was then discovered quickly.

How fast do you pull the plug on step 2? Straight after the "click"?

**Comment by manup** [comment]
>How fast do you pull the plug on step 2? Straight after the "click"?

After a few seconds.

Do you have the ConBee connected directly to PC/RPi? If yes please try with an USB-extension cable.

**Comment by Cavemanz** [comment]
Its connected through an USB extension already. Tried doing the include further away from the server, but no success. The plug only blinks for 3-4 seconds before going solid white. No matter when I reinsert the plug, it always is solid white afterwards.

**Comment by masonevans** [comment]
@Cavemanz I had trouble resetting a couple of these.  It turns out I just wasn't pressing hard enough.  But if you're getting to the flashing then that doesn't seem like your issue.  Have you tried holding a pin in for longer?  The reset sequence is something like "click... flash a couple times... turn solid... fade out... flash again".  You need to hold until you get to that second flashing phase, then deCONZ should find it.

**Comment by Cavemanz** [comment]
I do get the second flashing phase, but Deconz doesnt pick it up. I assume these logs from the docker aint related? 

19:25:10:405 Search sensors done,
19:24:22:385 Beacon src: 0xD5F3 ch: 11 updateId: 1,
19:24:21:873 Beacon src: 0xEBC2 ch: 11 updateId: 1,
19:24:21:857 Beacon src: 0x2A08 ch: 11 updateId: 1,
19:24:21:873 Beacon src: 0xD5F3 ch: 11 updateId: 1,
19:24:38:152 Beacon src: 0xD5F3 ch: 11 updateId: 1,
19:24:38:664 Beacon src: 0xEBC2 ch: 11 updateId: 1,
19:24:44:972 ZCL attribute report 0x8418260000DA2415 for cluster 0x0300, ep 0x03,
19:24:44:003 ZCL attribute report 0x8418260000DA2415 for cluster 0x0300, ep 0x03,
19:24:56:672 Beacon src: 0xEBC2 ch: 11 updateId: 1,
19:24:56:672 Beacon src: 0xD5F3 ch: 11 updateId: 1,
19:24:57:184 Beacon src: 0xEBC2 ch: 11 updateId: 1,
19:24:57:184 Beacon src: 0xD5F3 ch: 11 updateId: 1

**Comment by manup** [comment]
The Beacons are a good sign that some device (the outlet?) tries to join.

One thing you can check: do you have by any chance multiple Phoscon App tabs open, perhaps on multiple devices? If so please close all tabs but the one in which the light search is running.

**Comment by Cavemanz** [comment]
Sadly, I only had 1 window open on my main computer. Any other suggestions I could try? Getting a bit desperate. Id return the 2 I bought to IKEA but its a 1h drive so Id rather not if possible :)

**Comment by manup** [comment]
Hmm strange, by the way which deCONZ and ConBee firmware are you running? Latest is deCONZ 2.05.64 and firmware version 0x26330500.

**Comment by Cavemanz** [comment]
Version 2.05.63 / 3.4.2019
Firmware 26320500.
Updated to the newest firmware at the time, is there a fresh release now?
Ill grab 2.05.64 Docker image and try again.

**Comment by manup** [comment]
Yes release is online, might be worth a try.

**Comment by Cavemanz** [comment]
Anything in these logs that makes sense? Upgraded to newest version of Deconz and the firmware for Conbee.

https://pastebin.com/2FTYW84q

**Comment by manup** [comment]
Log looks kinda ok, running out of ideas here.

Maybe try to power-off the the other mains powered devices while joining the plug? This should force it to join directly via ConBee.

**Comment by Cavemanz** [comment]
Tried that now, no luck either. I dont get any Beacon log entries now either with my 4 lights switched off. I increased the search time to 3 min. It should show up as an actionable entry in the Lights section, right?

**Comment by manup** [comment]
Yes should look like this:

![image](https://user-images.githubusercontent.com/383386/56691364-0c810400-66e0-11e9-8e13-c3e118ff8318.png)

Do you have access to the deCONZ GUI via VNC?

Only remaining thing to check are the Zigbee network parameters in the GUI.

**Comment by Cavemanz** [comment]
Into the Docker container you mean? I havent tried that before.
![image](https://user-images.githubusercontent.com/28234923/56691534-7a2d3000-66e0-11e9-9aec-517f26a78c4d.png)

**Comment by manup** [comment]
That's the Phoscon App, showing only a limited set of the parameters.

The full Zigbee configuration is only visible in deCONZ GUI, with marthocs docker container it can be accessed via VNC (unfortunately I haven't done this myself yet) .

Configuration looks like

![image](https://user-images.githubusercontent.com/383386/56691691-dbed9a00-66e0-11e9-829b-860c29ae4d1d.png)

**Comment by Cavemanz** [comment]
Managed to enable it in my docker compose file:
![image](https://user-images.githubusercontent.com/28234923/56692087-b319d480-66e1-11e9-8216-c939aee0b6a1.png)

**Comment by manup** [comment]
Hmm, these look fine too, all parameters are valid.
Very strange

**Comment by Cavemanz** [comment]
I powered on my 4 lights again. Tried pairing both of my plugs. The Beacon src messages are back now, but nothing happens :/

https://pastebin.com/mMtZ01Ti

**Comment by manup** [comment]
The beacons come from the lights, they are responses to the plug which requests them in order to find suitable routers to join.

**Comment by Cavemanz** [comment]
Ok, Im close to giving up on these. Annoying that they wont pair seeing how Philips/Osram/Xiaomi pairs without issue :/

**Comment by r41d** [comment]
A lot of times in this thread a hole in bottom of the plug is mentioned. Mine doesn't have one. How can I add it in deconz?

**Comment by masonevans** [comment]
@r41d  if yours really doesn't have a hole in the bottom then you should return it because it's defective.  But make sure you're looking in the right place.  I would describe it as the "outside" more than the bottom, it's on the curved part of the plastic, on the side between the male part of the plug and the female part of the plug.  It's pretty small, about the size of a pin, but it's possible the plastic didn't get punched/molded properly and the hole is filled in.

**Comment by r41d** [comment]
After taking pictures to show that I see no hole and uploading them I took another look and finally spotted the tiny hole at the bottom ^^. It's funny that you don't need it to for regular pairing with the official Gateway but that it's necessary for pairing with ConBee.
The pairing then worked flawlessly :)
What confused me was that the category was just called Light, it wasn't obvious to me that pairing of power plugs has to be done through this, as I also didn't really find any detailed instructions through Google. And I didn't notice the tiny hole, plus the normal pairing doesn't use it.

**Comment by thowi** [comment]
It was really hard to pair mine. I tried multiple times to pair the socket, but failed many times.
At some point, I got saw "Range extender" by IKEA in Phoscon, but it was marked gray. I removed it, paired again, and eventually I saw it properly listed as "On/Off plug-in unit 13". Not sure why it's "13", maybe because I had to try 13 (?) times.
Glad it worked finally, but quite frustrating to the point that I thought I'd have to trash the device.

Does anybody own the IKEA gateway an know if pairing is also such a PITA there?
I.e., are the devices the problem, or can this be improved in Conbee/deCONZ?

**Comment by ebaauw** [comment]
The IKEA hub works very differently: it only supports touchlink pairing.  You need to touchlink-pair a controller to the hub, and then touchlink-pair the controller to the light, plug, repeater, or window blind.  Note that the Trådfri motion sensors act as controllers.

**Comment by austwhite** [comment]
I know this is closed, but curious if it got resolved?  Could it be the Zigbee channel being 11?  
I use channel 15, was considering buying a couple of these plugs, but I don't want to waste money if they are temperamental to install.
