### ISSUE TITLE
Schneider Electric Room Thermostat

### ISSUE THREAD

**Issue by Feldi1606** [dresden-elektronik/deconz-rest-plugin#7795]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Schneider Electric CCTFR6400

### Manufacturer

Schneider Electric

### Model identifier

Thermostat

### Device type to add

Sensor

### Node info

![Bildschirmfoto vom 2024-05-28 23-41-05](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/ba5525c6-75dc-4b15-975a-ab06c11bf616)

### Endpoints and clusters

![Bildschirmfoto vom 2024-05-28 23-43-55](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/1cb71da3-156f-4b20-9685-c16be46da22a)

### Basic

![Bildschirmfoto vom 2024-05-28 23-52-48](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/02121184-0f73-4842-9184-746d025bf7a7)
![Bildschirmfoto vom 2024-05-28 23-53-13](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/0c38c55f-bdbe-48bc-84a4-b516e6e37ce8)

### Further relevant clusters

![Bildschirmfoto vom 2024-05-29 00-02-33](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/c5050e3c-423f-4fb1-8feb-0a8bdba18cef)

![Bildschirmfoto vom 2024-05-28 23-57-33](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/c9c09e61-1a82-48ac-9c6b-cae23413eaef)

![Bildschirmfoto vom 2024-05-28 23-58-03](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/d0df1631-68df-4e1c-a64d-b56abbf0eafb)

![Bildschirmfoto vom 2024-05-28 23-58-30](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/43e602aa-7eb0-4d98-888d-a0c249eb53cc)

![Bildschirmfoto vom 2024-05-28 23-59-23](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/e22429f6-2d83-4666-a6f5-926f5dedbe8f)
![Bildschirmfoto vom 2024-05-28 23-59-47](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/0be08fe9-3a7e-48fc-95b4-63ab26e0bb0c)

**Comment by Feldi1606** [comment]
Hello can anyone issue a DDF for this device or tell me which DDF might work?
And is it possible to peer this room thermostat with the heating thermostat so that the two can communicate directly? And I would also like to set up weekly programs. Unfortunately I haven't found any instructions or syntax on how to do this yet. I assume that the Cluster 0201 thermostat should be used for this.

**Comment by SwoopX** [comment]
Hi there.

Unfortunately, the screenshots indicate that the clusters have not been read properly. [This page](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/How-to...#read-device-clusters) explains how to read clusters. Please take new ones and update the issue accordingly. Thanks a lot!

**Comment by SwoopX** [comment]
If you update to the latest deconz version released yesterday, you should be able to get a draft DDF already by right clicking on the node and selecting the DDF editor entry. That is always a good starting point.

The device seems to be ale to communicate directly with thermostats, as it holds the grey thermostat client cluster, presumably allowing to set temperatures remotely. Schedules, however, cannot be set on this device.

**Comment by Feldi1606** [comment]
![Bildschirmfoto vom 2024-05-29 12-59-45](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/4c6422f9-dd16-47ea-b8d9-a132a11fe065)
![Bildschirmfoto vom 2024-05-29 13-00-21](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/a0accd1c-46ea-461c-8d14-0740075530a9)
![Bildschirmfoto vom 2024-05-29 13-01-21](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/ee16c325-a844-4a1a-85c0-6a6dce50f940)
![Bildschirmfoto vom 2024-05-29 13-02-33](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/6e961e03-65bb-4033-97b5-f8438932f6b9)
![Bildschirmfoto vom 2024-05-29 13-03-07](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/a31198c8-a181-4002-813e-77f9946ae317)
![Bildschirmfoto vom 2024-05-29 13-03-50](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/26e7787c-e8af-4a21-a6ec-9ab247f76c94)
![Bildschirmfoto vom 2024-05-29 13-04-42](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/04ac13f6-1680-4b34-9479-036b5446971b)
![Bildschirmfoto vom 2024-05-29 13-05-37](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/984875f3-bd31-42f4-9616-16f0593e1f7a)
![Bildschirmfoto vom 2024-05-29 13-06-22](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/e598a1cf-b395-477a-83b2-335e1a0e17e7)
![Bildschirmfoto vom 2024-05-29 13-07-38](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/a9353de1-61c7-43ad-92b7-95761f752a4f)
![Bildschirmfoto vom 2024-05-29 13-08-24](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/aeb4b9a9-6a1f-495a-8e84-72c0bacf2e40)
![Bildschirmfoto vom 2024-05-29 13-09-15](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/f2f23c79-7ea4-4ed5-aeec-2d89c30a82cf)
![Bildschirmfoto vom 2024-05-29 13-09-34](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/a042d89f-e37a-4c84-8b16-e341443c1a3f)

**Comment by Feldi1606** [comment]
So I hope all the screenshots are correct now. Unfortunately, the instructions do not say what you have to pay attention to with the clusters. 
What can I do with the DDF draft? Should I upload it somewhere?

**Comment by Smanar** [comment]
If you can copy/paste the "Draft", yes it can be usefull, but now too late ^^
Can try this DDF, based on another Schneider thermostat

```
{
  "schema": "devcap1.schema.json",
  "uuid": "e4ee14c0-c6a8-431c-8bff-4b4aa32d5de3",
  "manufacturername": "Schneider Electric",
  "modelid": "Thermostat",
  "product": "CCTFR6400",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_THERMOSTAT",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0201"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0301",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0201"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/heatsetpoint"
        },
        {
          "name": "config/unoccupiedheatsetpoint"
        },
        {
          "name": "config/mode"
        },
        {
          "name": "config/offset"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/on",
          "parse": {
            "at": "0x0008",
            "cl": "0x0201",
            "ep": 1,
            "eval": "Item.val = Attr.val > 3;",
            "fn": "zcl:attr"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "config/locked",
          "refresh.interval": 3660
        },
        {
          "name": "state/temperature"
        }
      ]
    },
      {
         "type":"$TYPE_TEMPERATURE_SENSOR",
         "restapi":"/sensors",
         "uuid":[
            "$address.ext",
            "0x01",
            "0x0402"
         ],
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"config/offset"
            },
            {
               "name":"config/on"
            },
            {
               "name":"config/reachable"
            },
            {
               "name":"state/lastupdated"
            },
            {
               "name":"state/temperature"
            }
         ]
      },
      {
         "type":"$TYPE_TEMPERATURE_SENSOR",
         "restapi":"/sensors",
         "uuid":[
            "$address.ext",
            "0x01",
            "0x0402"
         ],
         "items":[
            {
               "name":"attr/id"
            },
            {
               "name":"attr/lastannounced"
            },
            {
               "name":"attr/lastseen"
            },
            {
               "name":"attr/manufacturername"
            },
            {
               "name":"attr/modelid"
            },
            {
               "name":"attr/name"
            },
            {
               "name":"attr/swversion"
            },
            {
               "name":"attr/type"
            },
            {
               "name":"attr/uniqueid"
            },
            {
               "name":"config/offset"
            },
            {
               "name":"config/on"
            },
            {
               "name":"config/reachable"
            },
            {
               "name":"state/lastupdated"
            },
            {
               "name":"state/temperature"
            }
         ]
      }
  ],
  "bindings": [
      {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0201",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 300,
          "change": "0x00000032"
        },
        {
          "at": "0x0012",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0008",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0204",
      "report": [
        {
          "at": "0x0001",
          "dt": "0x30",
          "min": 1,
          "max": 3600
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 300,
          "change": "0x00000032"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0402",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x29",
          "min": 60,
          "max": 300,
          "change": "0x00000032"
        }
      ]
    }
  ]
}
```

**Comment by Feldi1606** [comment]
The DDF works so far. But what I've noticed is that I can't see any battery or humidity values. And the heatsetpoint is not displayed analogously to the device. How can I help you fix this Problems.

**Comment by SwoopX** [comment]
@Feldi1606 Can you please share the initially auto generated DDF here to have a fresh and good start? The suggested DDF above creates more issues than it actually solves, exposing lots of functionality the device does not offer. I assume Smanar had a bad day or posted any wrong version.

**Comment by Smanar** [comment]
>I assume Smanar had a bad day or posted any wrong version.

Not realy, have made a copy/paste of this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/elko/thermostat_16_a.json but you are right, this DDf is not compatible at all, no cluster 0x0201 ....

**Comment by Feldi1606** [comment]
Hello Yes, exactly the device is basically an external temperature and humidity measuring instrument and a remote control to control the temperature of one or I think even several ITRVs and also to change the mode. I'm attaching a link to the device.
[https://merten.de/produkt/cctfr6400-wiser-raumthermostat-mit-display.html](url)

The device is powered by 2 AA batteries with 1.5V so 3V should be suitable. 
But I can already see the attribute 0x0021 in deconz and it currently says 100, see screenshot
![Bildschirmfoto vom 2024-05-30 20-52-20](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/d70e7058-9abd-4bcd-9a08-e3a12133d2af)

**Comment by SwoopX** [comment]
> I think you don't need the automatically generated DDF or have I done something wrong?

Hm, I would have expected some more but agreed, that is not exactly helpful 🙂

**Comment by Smanar** [comment]
The value was "0" on your previous capture ....
Have added the battery support on the previous DDF, but still need the thermostat part.

**Comment by Feldi1606** [comment]
are you okay with that?

![Bildschirmfoto vom 2024-05-31 21-12-32](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/b1aa81b3-94ca-48ee-8aaf-f28e83d18c3e)
![Bildschirmfoto vom 2024-05-31 21-12-58](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/76537342/5fc2da56-7b71-46c1-a8c5-3ad2b608db9b)

**Comment by Feldi1606** [comment]
Is it correct that I see the room thermostat once under thermostats and once under sensors? 
The battery status is now shown to me as 50% even though Deconz says 100%.

**Comment by Smanar** [comment]
>The battery status is now shown to me as 50% even though Deconz says 100%

My bad 
`"eval": "Item.val = Attr.val / 2",`

Just need to remove the /2

>And the humidity value could be output without any decimal places. It is currently sending a lot of data with very small changes of 0.01%

Can set min/max/chnage here 

```
      "cl": "0x0405",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x21",
          "min": 60,
          "max": 300,
          "change": "0x00000032"
        }
      
```

>Is it correct that I see the room thermostat once under thermostats and once under sensors?

On phoscon ?

But the problem is for the ZHAThermostat. SwoopX have removed it but I m seing you can send request to it like for classic thermostat

> 
> Action (enum)
> 
> Triggered action (e.g. a button click). Value can be found in the published state on the action property. It's not possible to read (/get) or write (/set) this value. The possible values are: screen_sleep, screen_wake, button_press_plus_down, button_press_center_down, button_press_minus_down.
> Climate
> 
> This climate device supports the following features: occupied_heating_setpoint, local_temperature, pi_heating_demand.
> 
>     occupied_heating_setpoint: Temperature setpoint. To control publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"occupied_heating_setpoint": VALUE} where VALUE is the °C between 4 and 30. Reading (/get) this attribute is not possible.
>     pi_heating_demand: Position of the valve (= demanded heat) where 0% is fully closed and 100% is fully open. To control publish a message to topic zigbee2mqtt/FRIENDLY_NAME/set with payload {"pi_heating_demand": VALUE} where VALUE is the % between 0 and 100. Reading (/get) this attribute is not possible.

But not sure it's something usefull, better for automation to control direclty the TRV for exemple than the remote.
