### ISSUE TITLE
Tuya Soil Sensor (diff. manufacturer)

### ISSUE THREAD

**Issue by kopierschnitte** [dresden-elektronik/deconz-rest-plugin#7799]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Tuya Soil Sensor

### Manufacturer

_TZE204_myd45weu

### Model identifier

TS0601

### Device type to add

Other

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/28762191/d18cf339-06cc-44be-9eb6-bfce2a501308)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/28762191/2cb73786-a359-4bc2-acd0-f8147bea097f)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/28762191/c12c813b-dc3d-4f18-b8d1-7d089d061014)

### Further relevant clusters

The device is already supported by https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6731 but some units are sold with a different manufacturer-id. Mine reads _TZE**204**_myd45weu instead of _TZE**200**_myd45weu.

After cloning the current DDF and changing the manufacturer-id, the device works as expected. Therefore I guess, it's just an alias for the other device.

**Comment by Smanar** [comment]
So adding your device to this DFF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZE200_myd45weu_soil_sensor.json Make it working ?

So there is nothing to do ? (except make the PR)

**Comment by kopierschnitte** [comment]
Yes, indeed ;-)

**Comment by Smanar** [comment]
Thx, was fast ^^, PR done here > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7808

**Comment by kopierschnitte** [comment]
Great. Thanks!

**Comment by Mimiix** [comment]
Please keep it open until its merged.

**Comment by Smanar** [comment]
The DDF have worked ?
Do you want to make the PR or want I make it ?

**Comment by kopierschnitte** [comment]
Yes, perfectly. I'm not so skilled using Github. Would be great if you could do the PR.

**Comment by Smanar** [comment]
Oups, sorry, haven't see the PR was already done, and by me ....
