### ISSUE TITLE
Hue Tap Dial rotation not registered by Home Assistant

### ISSUE THREAD

**Issue by DrBlokmeister** [dresden-elektronik/deconz-rest-plugin#7804]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Note: I am unsure if this is a Home Assistant or a Deconz issue. I'm trying to pinpoint where the issue lies and how to fix it.

I recently bought a Hue Tap Dial switch which I integrated into Deconz without issue. I integrated it into Home Assistant. All buttons work perfectly, but rotation is not detected by the events listener. When I open the Phoscon app to check if the rotations are registered, I find that they are. When I then go back to Home Assistant and listen for events, I do suddenly see 5001 and 6001 events indicating rotation. When I reload the Home Assistant integration, these events are no longer detected.

### Steps to reproduce the behavior

1. Reload Home Assistant Deconz integration
2. Listen to deconz_event in the events listener. Rotations are not detected
3. Open Phoscon app
4. Listen to deconz_event in the events listener. Rotations are again detected.

Note: restarting the add-on without reload of the integration does not cause the issue to appear.

### Expected behavior

Rotation events should always be detected.

### Environment

- Host system: Intel NUC running Debian
- Running method: Home Assistent deCONZ Add-on
- Firmware version: 26720700
- deCONZ version (not Home assistant Addon version!): 2.25.3
- Device:  ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? Yes, P1 port reader.

### deCONZ Logs

I'm having problems trying to find the actual debug logs. I can't copy from the vnc interface. I do see INFO_L2 entries along the lines of:
No button map for: RDM002, unicast to 0x0000 endpoint: 0x01, cluster 0xFC00, command: 0x00 payload: 1400013001291E00216400291E00216400291E00219001, zlSeq: 197.

**Comment by DrBlokmeister** [comment]
If what you say is true, then it makes sense. The only thing we can't check is if the Phoscon page actually receives the signals when it is not open. However, I find that slightly unlikely.

One thing I do wonder is why I only see this problem for the hue tap dial switch and not for any other switch, sensor or light. So I'm not completely sure where to start with troubleshooting at the Home Assistant side. But I'll give that a shot.

**Comment by phqzgunsfjror** [comment]
I have the same problem but with OpenHab. My debugging indicates it is on deCONZ side.

In deCONZ UI: -> Help -> API information

```
{
    "config": {
        "battery": 100,
        "on": true,
        "reachable": true
    },
    "etag": "-----------",
    "lastannounced": "2024-06-14T17:42:39Z",
    "lastseen": "2024-06-14T17:45Z",
    "manufacturername": "Signify Netherlands B.V.",
    "mode": 1,
    "modelid": "RDM002",
    "name": "My Hue Tap",
    "productname": "Hue tap dial switch",
    "state": {
        "buttonevent": 4002,           <----------------------------------------HERE
        "eventduration": 1,
        "lastupdated": "2024-06-14T17:44:19.381"
    },
    "swversion": "2.59.19",
    "type": "ZHASwitch",
    "uniqueid": "-----------"
}
```

Normal button events (1xxx-4xxx) change all the time after pressing.
Rotation events (5xxx-6xxx) barely - almost never - occur. "Multiple Hue Tab Dial Switches" tested.

I fix would be great :)

**Comment by ebaauw** [comment]
deCONZ reports the rotations as `rotaryevent` values on the ZHARelativeRotary resource, not as `buttonevent` values 5xxx and 6xxx on the ZHASwitch resource.  This is similar to how the Hue bridge reports these (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6160).  This has been the case since the initial support of the Hue tap dial switch back in 2022 (see https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6164).

**Comment by DrBlokmeister** [comment]
Thanks for the response! I appreciate the help! :)

But these also don't show up to me. I'm viewing this page:
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/57352628/90e18db1-25a5-4274-8359-b9723f0161c6)

I then subsequently pressed all the buttons on the switch, rotated clockwise, rotated counter clockwise. I repeated the rotation events again, couple of times clockwise, couple of times counter clockwise. Below is the result. I only see buttonevents here. No rotaryevents.

```json
{
    "20:55:28:414": {
        "attr": {
            "id": "100",
            "lastannounced": "2024-06-14T18:50:30Z",
            "lastseen": "2024-06-14T18:55Z",
            "manufacturername": "Signify Netherlands B.V.",
            "mode": 1,
            "modelid": "RDM002",
            "name": "Babyroom Tap Dial",
            "productname": "Hue tap dial switch",
            "swversion": "2.59.19",
            "type": "ZHASwitch",
            "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
        },
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:48:42": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 1000,
            "eventduration": 0,
            "lastupdated": "2024-06-14T18:55:46.598"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:48:207": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 1002,
            "eventduration": 1,
            "lastupdated": "2024-06-14T18:55:46.773"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:48:778": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 2000,
            "eventduration": 0,
            "lastupdated": "2024-06-14T18:55:47.346"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:48:860": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 2002,
            "eventduration": 1,
            "lastupdated": "2024-06-14T18:55:47.429"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:49:485": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 3000,
            "eventduration": 0,
            "lastupdated": "2024-06-14T18:55:48.058"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:49:659": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "eventduration": 1,
            "lastupdated": "2024-06-14T18:55:48.226"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:50:222": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 4000,
            "eventduration": 0,
            "lastupdated": "2024-06-14T18:55:48.789"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    },
    "20:55:50:372": {
        "e": "changed",
        "id": "100",
        "r": "sensors",
        "state": {
            "buttonevent": 4002,
            "eventduration": 1,
            "lastupdated": "2024-06-14T18:55:48.940"
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
    }
}
```

Am I not looking at the correct thing here, or is this indeed weird?

I have looked for rotaryevents and did find some, but they don't have the same unique_id and it seems that they don't correspond to my tap dial switch. I also have some Aqara vibration sensors, so the events might correspond to these. This is a log snippet of these events:

```json
    "20:55:59:636": {
        "e": "changed",
        "id": "101",
        "r": "sensors",
        "state": {
            "expectedeventduration": 400,
            "expectedrotation": -15,
            "lastupdated": "2024-06-14T18:55:58.214",
            "rotaryevent": 1
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-14-fc00"
    },
    "20:56:00:787": {
        "e": "changed",
        "id": "101",
        "r": "sensors",
        "state": {
            "expectedeventduration": 400,
            "expectedrotation": 15,
            "lastupdated": "2024-06-14T18:55:59.366",
            "rotaryevent": 1
        },
        "t": "event",
        "uniqueid": "00:17:88:01:0d:d0:26:e0-14-fc00"
    },
```

**Comment by ebaauw** [comment]
Those are the events allright.
> "uniqueid": "00:17:88:01:0d:d0:26:e0-01-fc00"
> "uniqueid": "00:17:88:01:0d:d0:26:e0-14-fc00"

I put a fake endpoint, `14`, in the `uniqueid` of the ZHARelativeRotary, to make its value is unique.  You can match the ZHASwitch with the corresponding ZHARelativeResource on the Mac-address in the `uniqueid` (the part before the first `-`).

Note that both button and rotary events are reported through the same command on the FC00 cluster, but with a very different payload.  This can be seen in the deCONZ GUI.

**Comment by DrBlokmeister** [comment]
I updated my response above with some more info. 

Looking at your previous message, I wonder what's going on. If I have the device page open, the rotations get published as buttonevents and also forwarded to Home Assistant. But it seems that the individual rotaryevents are not. I'm left with two questions:

1. How come that I get the rotations as buttonevents when I have the device page open in Phoscon? And if I close the page, they don't?
2. If the rotaryevents do appear when the device page is unopened, why don't they show up in Home Assistant? I'm out of my depth here and speculating, but can it be that since the uniqueid is different, it cannot be coupled to the same device and therefore Home Assistant has no idea what to do with it?

**Comment by ebaauw** [comment]
Ad 1.  I don't use Phoscon.  Afaik, Home Assistant should connect straight to the web socket provided by deCONZ and Phoscon shouldn't be able to interfere in the messages published there.  I'm unfamiliar with the API Information page: is that offered by Phoscon or by Home Assistant?  Do you also see the 5xxx and 6xxx `buttonevent` values on other web socket clients, like the [Simple WebSocket Client](https://chromewebstore.google.com/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=af&pli=1) in Chrome (connected to the deCONZ web socket)?

Ad 2.  That's conceivable and would be an omission in the Home Assistant integration of deCONZ.  As I mentioned before, these events can be coupled based on the MAC address in the `uniqueid`.

**Comment by DrBlokmeister** [comment]
Okay. I think I figured it out. I found this github issue: https://github.com/Kane610/deconz/issues/359. Turns out that I shouldn't listen for deconz_event but to deconz_relative_rotary_event.

This is a horrible implementation. I have no idea why this should be published as a completely different event. No-one who buys a new device should have to scour the internet trying to find out which specific event type each possible action on the device should throw. This is also the first time I noticed this. I have a Moes rotary switch, I have many Aqara switches and every action just throws a deconz_event. Except this one.

I'm a bit struggling trying to wrap my head around this. Do you have a suggestion on how to proceed here? Is there a way to get this nicely implemented instead of how it's currently working?

**Comment by ebaauw** [comment]
> This is a horrible implementation.

In that case, you'd better complain to Signify (previously Philips Lighting), or buy another device.  As I mentioned before, deCONZ follows how the Hue bridge exposes the Hue tap dial switch.

> How come that I get the rotations as buttonevents when I have the device page open in Phoscon?

Still breaking my head on this one.  It's conceivable, at least in theory, that Phoscon would change the device mode when the device page is open.  This would cause the device to send slightly different payloads for the rotary events, that deCONZ wouldn't recognise correctly.  So it would report these button events instead.  As I mentioned above, both button events and rotary events are reported by the device using the same cluster and command, but a different payload.  
If this is indeed the case, you should be able to spot different payloads in the deCONZ GUI, as well as in the deCONZ debug view, with, I think, APS_L2, so you see the `asdu:` lines with the command payload.

**Comment by DrBlokmeister** [comment]
> > This is a horrible implementation.
> 
> In that case, you'd better complain to Signify (previously Philips Lighting), or buy another device. As I mentioned before, deCONZ follows how the Hue bridge exposes the Hue tap dial switch.

What I get from this is that the event type is chosen by the device itself and not by Deconz? But even so, then it's still a Home Assistant thing to decide how these events get exposed to Home Assistant, right? The fact that rotations show up as deconz_relative_rotary_events in Home Assistant and not as deconz_events is a decision by Home Assistant developers, right? It would surprise me if Signify engineers would send deconz_events around when developing their Hue products.


> If this is indeed the case, you should be able to spot different payloads in the deCONZ GUI, as well as in the deCONZ debug view, with, I think, APS_L2, so you see the asdu: lines with the command payload.

I have around 110 devices in my network and if I open the deconz viewer via VNC in my browser, I can't copy-paste the logs and go through them. So finding these events in the mess of all data will be a real pain. Is there an easier way to do this?

**Comment by ebaauw** [comment]
deCONZ sends websocket notifications, as seen in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7804#issuecomment-2168606913 .  I think the translation into deconz_event etc is done by the HA integration for deCONZ.  I don’t recognise the device id either, I think these are assigned by the HA integration as well.

If you open the _Cluster Info_ panel in the deCONZ GUI and then select the FC00 cluster of the Hue tap dial, you should see the command payload change as you press the buttons and turn the dial.

**Comment by Zehir** [comment]
If you prefer you can use the node red plugin to do what ever you want with the deconz event and send it to anything like home assistant.
In my setup I use it for complex cases where the rules from phoson is not enough

https://flows.nodered.org/node/node-red-contrib-deconz

**Comment by DrBlokmeister** [comment]
> deCONZ sends websocket notifications, as seen in [#7804 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7804#issuecomment-2168606913) . I think the translation into deconz_event etc is done by the HA integration for deCONZ. I don’t recognise the device id either, I think these are assigned by the HA integration as well.

As far as I understand, you're right indeed. Each device in my Home Assistant setup has a unique device ID. If I go to the URL of my HA box and append /devices/<device_id> I end up at the configuration page of this specific device.

Looking at the messages sent from deCONZ, I do see a field named 'id' and a field with 'unique_id'. The id is 100 for tap actions and 101 for rotation actions. Also the unique_id is different, the difference being this fake endpoint you already mentioned (although I don't exactly know what endpoint means in this case). Now I don't know what's the difference between the id and unique_id fields, but if Home Assistant only receives id and unique_id as device identifiers, it makes sense that Home Assistant doesn't recognize rotation events as coming from the same device, as both are different. Does this make sense?

This leads me to the question: why did you change the endpoint in the unique id? It seems to me that if the action is coming from the same device, it should have the same unique_id, right? Or is this unique_id not connected to a device but to an action?

Also: do you know what the id field is? It seems to me that 100 or 101 is a bit too short to be a real unique identifier, although it could be simply the 100th and 101st devices seen by deCONZ.

**Comment by ebaauw** [comment]
The `id` and `uniqueid` are per (REST API) _resource_, not per device.  The unique ID of a device is it’s Zigbee MAC address.  The `uniqueid` is created from this MAC address, the Zigbee endpoint and, for `sensors`, the Zigbee cluster.  The `id` is just the resource ID, so the resources for this device are `/sensors/100` and `/sensors/101`.  To find all resources for a device, match the MAC address part of `uniqueid`.  Alternatively, use the newer `/devices` API endpoint.

Note that `id` will change when you remove and re-pair the device, but `uniqueid` remains the same.

**Comment by DrBlokmeister** [comment]
Good to know. Then from the Home Assistant point of view, what would be best to use to identify which device has triggered a certain event? I would guess that's the `uniqueid`, but that cannot be used as-is. Instead the MAC address would need to be extracted from the `uniqueid` and then coupled to the Home Assistant internal `device_id`. I wonder how this is really done.

But I think these are all on the Home Assistant side as far as I understand now.

**Comment by talun2075** [comment]
Maybe I can Jump into this topic.
I have the same issue. the Buttons are working the rottaryevent is not fired over Websocket but I can see it over the deconz ui.

My Setting
deconz 2.27.04 from Setup file but 2.17.1 on the ui.
I use Windows 10 with a conbee II and USB extension.

The Button under the HUE BUTTON Info
On Deconz Start
![on start](https://github.com/user-attachments/assets/4562b3cd-6251-4b20-9abf-9e2d65ba3088)
Button Pressed
![button](https://github.com/user-attachments/assets/70d5a4ed-32f1-4608-819a-bccf43917faf)
On Rotary
![rota](https://github.com/user-attachments/assets/09c7a932-407b-49ef-907e-8f181cb340f9)

The Node Info
![nodeinfo](https://github.com/user-attachments/assets/35aa8768-22d6-4832-90f5-e2479dd22668)

The Deconz Information
![deconz](https://github.com/user-attachments/assets/18bed130-c80f-4fc6-81f6-a422d5dea273)


I don´t use a common Smart Home. I work only with the Websocket. For this Problem I use 2 simple Websockets clients to see is this a problem in my implementation but all of them got only stuff like this:

`{"attr":{"id":"97","lastannounced":null,"lastseen":"2024-07-13T19:42Z","manufacturername":"Signify Netherlands B.V.","modelid":"RDM002","name":"RDM002 97","swversion":"2.59.19","type":"ZHASwitch","uniqueid":"00:17:88:01:0d:d1:a5:f2-01-fc00"},"e":"changed","id":"97","r":"sensors","t":"event","uniqueid":"00:17:88:01:0d:d1:a5:f2-01-fc00"}

{"e":"changed","id":"97","r":"sensors","state":{"buttonevent":1000,"eventduration":0,"lastupdated":"2024-07-13T19:43:00.925"},"t":"event","uniqueid":"00:17:88:01:0d:d1:a5:f2-01-fc00"}
`

**Comment by talun2075** [comment]
I have looked a little deeper and found the issue on my System. The Path of installations was changed after 2.17 and I have not controll quiet installation. So I start since long time everytime a old solution.
Maybe other have the same problem.
Now it works. On Websocket and API I got two Sensors.

Thanks and hope I spell a smile to you ;-)
