### ISSUE TITLE
Tuya Water Leak Sensor - ZW06

### ISSUE THREAD

**Issue by telfax** [dresden-elektronik/deconz-rest-plugin#7805]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Water Leak Sensor ZW06

### Manufacturer

_TZ3000_wuep9zng

### Model identifier

TS0207

### Device type to add

Sensor

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9720579/c7c1df20-64ca-4cdb-a6fd-44dc9fbe4d10)

### Endpoints and clusters

Alarm 1 active when water is detected.
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9720579/bf9f89c6-f549-476d-a430-f85f4b21530a)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9720579/c194b0a2-e990-4956-9584-217cf44eafea)

### Power Configuration
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9720579/a06c0f52-17ac-481e-b7d6-da383e110d41)

**Comment by telfax** [comment]
Device details:
http://www.zz-power.com/product-5703-5274-109575.html

**Comment by Smanar** [comment]
Hello, can just try to add it in this looonnnggg list https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0207_water_leak_sensor.json

**Comment by telfax** [comment]
Unfortunately this did not work.
After adding, the device still does not show up in Phoscon ☹️

**Comment by Smanar** [comment]
@how you have done that ?
What is your OS ?
You need to edit 2 lines, Manufacture name AND model ID, then restart deconz and re include the device.

**Comment by telfax** [comment]
Added the two lines
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/9720579/85522557-8762-4d94-95bd-09fa15549911)

Stuff is running on a PI3, I uploaded the modified file restarted the phoscon gateway and tried to pair the sensor again.

Sensor indicated pairing succes by LED by it does not show up in Phoscon sensors.

**Comment by Smanar** [comment]
Strange, I don't see typo, all is fine for me.
Can you check if you can see it direclty in the API ? using Phoscon/HELP/API Information/sensors ?

**Comment by telfax** [comment]
Device is not listed in sensors API response :-/

**Comment by cosmo84** [comment]
Hi,
I have the same device but (unfortunately) I run Deconz in docker and I have some issues in adding/testing new DDF in Docker. I open the updated DDF and do a hot reload but nothing happens. When I close the window and select "edit DDF" again, the old one is shown again.
Is the updated DDF above working? If so, it could be added and I might get a solution that way :-)

Thanks!!

**Comment by Smanar** [comment]
Thx for return.
Added https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7886
