### ISSUE TITLE
Deconz Docker Image - Firmware Not Connected

### ISSUE THREAD

**Issue by andrzejom** [dresden-elektronik/deconz-rest-plugin#7806]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

While connecting to homebridge I receive following error/warning log _"[deCONZ] warning: 192.168.8.158:4530: 0000000000000000: not a RaspBee/ConBee mac address - retrying in 60s"_ . While accessing Deconz WebUI the issue is shown as "Firmware: Not Connected". I tried several options from different sources but I can't make it work. 

On raspberry PI USB is show as 
crw-rw----+ 1 root      dialout 188,  0 Jun  5 00:28 /dev/ttyUSB0
usb-dresden_elektronik_ConBee_III_DE03217198-if00-port0 - as I believe accesses should be handled okay.
In the docker compose files (each separate for the container I'm passing through not a serial USB but a device)
**DeConz Docker Compose File**
_version: '3'
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
      - ./deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03217198-if00-port0:/dev/ttyUSB0  
    environment:
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_WEB_PORT=4530
      - DECONZ_WS_PORT=443_

**Homebridge Docker Compose File**
_version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/London
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03217198-if00-port0:/dev/ttyUSB0_

### Steps to reproduce the behavior

1. Homebridge Accesories is empty. Using official Deconz plugin and discovery for gateways
2. Deconz webui doesn't change

### Expected behavior

So that Homebridge will see a mac address properly

### Environment

- Host system: (Raspberry Pi Ubuntu Focal Fossa (20.04.5 LTS))
- Running method: (Raspbian / homebridge-docker / deconz-docker container /)
- Firmware version: (0x26510900)
- deCONZ version (2.27.2)
- Device: (ConBee III)
- Do you use a USB extension cable: (Yes [1m])
- Is there any other USB or serial devices connected to the host system? (No)

**Comment by Mimiix** [comment]
Hi,

As this is not an issue as described in #5113 I am closing this issue.

Please open an topic on the forums.

Kind regards,
