### ISSUE TITLE
GreenSun Smart Socket

### ISSUE THREAD

**Issue by UserUnclassified** [dresden-elektronik/deconz-rest-plugin#7807]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Smart Socket
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/caf640bc-0576-4fb2-8f7f-64445b81ad41)

### Manufacturer

GreenSun

### Model identifier

TS011F

### Device type to add

Switch

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/d228f1f1-0fb5-4bf0-be2b-f60bb0c53a8e)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/3fb2b18b-2a2d-4f59-80d4-81c78caf5170)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/388af0c7-2fd8-457a-a5a6-92eba9778a7c)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/e57e93ce-6234-4bda-b898-11858b4d5f5b)

### Simple Metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/ac56ebb6-ef34-4172-8004-dd2e2dd856c4)

### Electrical Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/487f55c4-7989-4397-b2ec-0dd31ad70e4e)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/d0ccc7e9-7a70-487c-a39c-c6a6b1abf878)
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/12692021/05fff898-d4dc-4e5d-9cd3-d85f9ddd0cd0)

**Comment by UserUnclassified** [comment]
Is there anything else I can do to make the product compatible? On/Off switch is working, but no energy measurement.

**Comment by aksdb** [comment]
> Is there anything else I can do to make the product compatible? On/Off switch is working, but no energy measurement.

I have a similar device where I used the DDF editor to add the ZHAConsumption and ZHAPower entities/groups. That allowed me to use the full capabilities in HomeAssistant.
