### ISSUE TITLE
nedis zigbee smoke detector zbds10wt

### ISSUE THREAD

**Issue by ltspicer** [dresden-elektronik/deconz-rest-plugin#7812]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Nedis zigbee smoke detector zbds10wt

### Manufacturer

Nedis

### Model identifier

zbds10wt 

### Device type to add

Sensor

### Node info

![Auswahl_003](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/38fe2d94-76ff-4dbc-bd80-7f807b4d9951)

### Endpoints and clusters

![Auswahl_004](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/60e5c32d-b78a-4dfe-8396-3005949e2b45)

![Auswahl_001](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/0a079eac-ce74-456a-b0b7-2a382584ce63)

Identify:
![Auswahl_002](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/ee4a7e9e-1f1a-4363-9a6c-da1522f9b109)

IAS zone:
![Auswahl_003](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/351a8555-0750-450b-95f8-fe790905f669)

IAS WD:
![Auswahl_004](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/48250f00-b8a4-48cc-a474-7ec171c44308)

### Basic

![Auswahl_001](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/730a6250-3c9d-4291-bbc7-71442207cef3)
![Auswahl_002](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/f1bb5fab-b8ec-49ee-bbad-9b80c5e29fdd)

### Further relevant clusters

![Auswahl_001](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/08bb8e61-08c0-490b-99dd-4630edf07bdc)

**Comment by Mimiix** [comment]
Please make sure you clicked "read" on the clusters. Also, add all screenshots.

**Comment by ltspicer** [comment]
> Please make sure you clicked "read" on the clusters. Also, add all screenshots.

Ist das so ok?

**Comment by Smanar** [comment]
Hello, you can try this part for the detection 

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TYZB01_wqcac7lo",
  "modelid": "TS0205",
  "vendor": "Tuya",
  "product": "Smoke Sensor",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_FIRE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "config/enrolled"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/fire"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/test"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 600,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

But your device have too a siren ?

**Comment by ltspicer** [comment]
> Hello, you can try this part for the detection
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "_TYZB01_wqcac7lo",
>   "modelid": "TS0205",
>   "vendor": "Tuya",
>   "product": "Smoke Sensor",
>   "sleeper": false,
>   "status": "Gold",
>   "subdevices": [
>     {
>       "type": "$TYPE_FIRE_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0500"
>       ],
>       "fingerprint": {
>         "profile": "0x0104",
>         "device": "0x0402",
>         "endpoint": "0x01",
>         "in": [
>           "0x0000",
>           "0x0001",
>           "0x0500"
>         ]
>       },
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion",
>           "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
>           "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/battery",
>           "parse": {
>             "at": "0x0021",
>             "cl": "0x0001",
>             "ep": 1,
>             "eval": "Item.val = Attr.val / 2",
>             "fn": "zcl:attr"
>           }
>         },
>         {
>           "name": "config/enrolled"
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/pending"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "state/fire"
>         },
>         {
>           "name": "state/lastupdated"
>         },
>         {
>           "name": "state/lowbattery"
>         },
>         {
>           "name": "state/test"
>         }
>       ]
>     }
>   ],
>   "bindings": [
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0001",
>       "report": [
>         {
>           "at": "0x0021",
>           "dt": "0x20",
>           "min": 600,
>           "max": 43200,
>           "change": "0x00000001"
>         }
>       ]
>     },
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0500"
>     }
>   ]
> }
> ```
> 
> But your device have too a siren ?

How should I do this part?

Device has a siren.

**Comment by Smanar** [comment]
>How should I do this part?

Depend of your OS, on classic OS, just need to create a text file called what_you_want.json with this contain in a "devices" folder, then restart deconz.

> All DDF provided directly with deCONZ typically reside in `/usr/share/deCONZ/devices/` on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. `/home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices`) will override the pre-packaged files to allow users to amend and keep their own files if desired.

**Comment by ltspicer** [comment]
I have the deconz adapter in ioBroker.
Just restart this adapter after creation of the json?

**Comment by ltspicer** [comment]
$ sudo systemctl status deconz
● deconz.service - deCONZ: ZigBee gateway -- REST API
     Loaded: loaded (/lib/systemd/system/deconz.service; disabled; vendor preset: enabled)
     Active: inactive (dead)

But deCONZ-RaspBee is running...

**Comment by Smanar** [comment]
I don't remember for ioBroker, but from my memory they don't use dockers ?*
Wich one "devices" folder have you used ? it was empty ?

You can restart using the console I think
`sudo systemctl restart deconz` For the headless
`sudo systemctl restart deconz-gui` For the desktop

**Comment by ltspicer** [comment]
I inserted your code in this file:

![Auswahl_001](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/fbe1bcfc-0ef6-46d2-bc0a-3bafde5f2ade)

The GUI shows the device:

![Auswahl_002](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/852e4774-1220-433b-8f1c-e279f848502e)

But the DDF looks like this:

![Auswahl_003](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/d5c11012-d807-4c73-a4cd-b093bf44c261)

ioBroker and the Zigbee gateway (RaspBee) is on the same Raspberry.

**Comment by ltspicer** [comment]
Now it is online ^^
I push the test button.

![Auswahl_001](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/c7490a77-4b45-42df-9ab9-90efca155091)

![Auswahl_002](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/42c26e62-c5f8-445f-9a4d-b42455a4a9fd)

**Comment by Smanar** [comment]
Nice, so new version with the siren
```

{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TYZB01_wqcac7lo",
  "modelid": "TS0205",
  "vendor": "Tuya",
  "product": "Smoke Sensor",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_FIRE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2",
            "fn": "zcl:attr"
          }
        },
        {
          "name": "config/enrolled"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/fire"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery"
        },
        {
          "name": "state/test"
        }
      ]
    },
    {
      "type": "$TYPE_WARNING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/reachable"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 600,
          "max": 43200,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

Do you know how to use the siren ? By security you can't use state/on, but need to use state/alert

**Comment by ltspicer** [comment]
If works!!
Thank you.

What's the difference between your 1st and 2nd version?

**Comment by ltspicer** [comment]
"Or you can clone the tuya_swversion.js file too."
What/what content to clone to where?
... sorry, my english is terrible.

**Comment by Smanar** [comment]
Can just copy the file `tuya_swversion.js` in the same folder than your DDF (the "nedis" folder).
The difference with the previous DDF,now the DDF create 2 entries, a "sensor" for return and a "light" for the siren.

**Comment by ltspicer** [comment]
I use the version 1. It is easier and give the only right status.
Thx for support ;)

**Comment by ltspicer** [comment]
OK?

![Auswahl_001](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/4b34df2f-b994-460f-aaef-dfccf72f1547)

**Comment by ltspicer** [comment]
Info for dev:
Can you pls integrate this DDL?
Thx

**Comment by Smanar** [comment]
Strange you haven't more file in your "nedis" folder, you need to have at least 2 files https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices/nedis

I can make the PR to suport this device as it, but you don't want to test the siren stuff ?

**Comment by ltspicer** [comment]
I had 2 more files. I deleted them myself.
I didn't understand the siren stuff.
The smoke detector works great with the v1.
It already has an integrated 83dB buzzer (sirene).

**Comment by ltspicer** [comment]
If there's anything I can test for you, let me know.
But please express yourself precisely (and without abbreviations)!

**Comment by Smanar** [comment]
>I didn't understand the siren stuff.

No problem, it's for you, if you don't need it, we can stay like that.
I don't know the device, perhaps the siren is managed internaly and can't be used using zigbee request.

But with the second DDF, you need to see a new entry in your "light" devices, a "Warning device" that can be used to trigger the siren.
You can too make test using the GUI, it's on the cluster 0x0502 "IAS WD".

PR submitted here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7815

**Comment by ltspicer** [comment]
With V2 I see only "Warning device". The real device I can not see.
I use V1 ;)

**Comment by Smanar** [comment]
>With V2 I see only "Warning device"

HA ? So something is bad, you need to have 2 entries with the V2, 1 in "sensor" and 1 in "light", they are not at same pplace, IDK how your third app manage them.

**Comment by ltspicer** [comment]
> Strange you haven't more file in your "nedis" folder, you need to have at least 2 files https://github.com/dresden-elektronik/deconz-rest-plugin/tree/master/devices/nedis
> 
> I can make the PR to suport this device as it, but you don't want to test the siren stuff ?

I restored the 2 files ^^

**Comment by ltspicer** [comment]
Is everything ok for you at the moment?
Or do you need more data for a clean implementation?

**Comment by Smanar** [comment]
It's for you, not for me ^^, I haven't the device.
For me it's enought to submit a PR for the sensor part, the V1, thx.

If you want to use the siren, can try with the V2 and search where can be the "light entry", can be visible in phoscon/help/API Information/light.
But if you are happy with the V1, no problem for me.

**Comment by Smanar** [comment]
Ha nice, you are "mixing" radio and wired device ?

**Comment by ltspicer** [comment]
Yes. I have a system from 1998 and new ^^

**Comment by ltspicer** [comment]
Here you can see the old fire alarm control panel with my interface PCB (left).
In the meantime, I have registered a second Nedis detector.
It works perfectly.

![bmz3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/a2d2c03a-ca2f-4660-ab62-5c59dabd2cf5)

**Comment by Smanar** [comment]
>with my interface PCB (left).

It's DIY stuff ?

**Comment by ltspicer** [comment]
Yes. Schematic and PCB is made by me self.

**Comment by Smanar** [comment]
Lol, I don't have enought skill, realy profoessionnal, what are you using for PCB support ? the green "thing" compatible with DIN support

**Comment by ltspicer** [comment]
I milled the PCB with my small CNC milling machine.
The profile for the DIN rail is from there:

https://de.aliexpress.com/item/1005005574681794.html

![pcb](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/1abfc18a-ac62-4b43-965a-06edbcdfdaa6)
![pcb2](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/09f558e8-7276-456d-afb8-471f9f74c87e)
![pcb3](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/11616336/ae12f001-e88b-4f8a-b61a-ddc3a61db18f)
