### ISSUE TITLE
Adeo 16A plug power doesn't work

### ISSUE THREAD

**Issue by Idaho947** [dresden-elektronik/deconz-rest-plugin#7833]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I just buy adeo 16A plug. The plug is in my network. On\Off work very well. But I've no power. The section is here but nothing change when my PS5 work or not.

### Steps to reproduce the behavior

Add a plug in the network

### Expected behavior

The mesurement work.

### Screenshots

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/8b3095eb-395d-4024-a134-6f9385af0b2b)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/5716b340-0de0-40f7-b3d4-c00d7cff3038)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/9d297f11-e208-4629-ac33-a85e6772649a)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/2921fcb4-5a10-4d45-b4a8-6c876415ca2e)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/4cd37e72-9fc6-4d60-9450-9be47df4051d)

### Environment

- Host system: Nuc
- Running method: VM
- Firmware version: (26510900)
- deCONZ version : 2.26.3
- Device:  ConBee III
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? non

**Comment by Mimiix** [comment]
Hi :) looks like this device is not supported yet:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues?q=LDSENK02F

I recommend you to create a device request. However: Do the Clusters in deCONZ show any values on the Power measurement?

If that is not the case, they might not support power metering at all.

**Comment by Idaho947** [comment]
Yes I just see that. Don't understand why it show up in ha without ddf...
Yes it support power mesurement.

Create the issue : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7834

**Comment by Smanar** [comment]
>Yes I just see that. Don't understand why it show up in ha without ddf...

It's because "light" device are whitelisted by defaut but "sensor" device are Blacklisted.
So the  on/off is native but not the measurement.
