### ISSUE TITLE
ADEO LDSENK02F 16A plug

### ISSUE THREAD

**Issue by Idaho947** [dresden-elektronik/deconz-rest-plugin#7834]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Adeo plug 16 A

### Manufacturer

Adeo

### Model identifier

LDSENK02F

### Device type to add

Other

### Node info

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/c67bf807-6c73-46de-a0f9-98d0be48ac0e)

### Endpoints and clusters

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/3333a4ce-0e59-4682-9906-2afe082b8329)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/26f9c9aa-42e3-4254-a438-ac8c28e2945a)

### Basic

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/7519acb7-53b0-417d-ac9d-cfd1922422d4)

### On/Off
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/45dac565-baa8-4cca-b8e9-68c4967bd278)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/fd8831cf-f7e2-453c-b34a-443f3b792479)

###Simple metering
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/a121c6bd-4ba3-41bc-ba34-a5ce93b1aabd)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/5c861800-0ef0-403d-951d-b8405931f483)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/029090a9-72e4-4ac8-a273-df29f76546d8)

### Electrical Measurement
![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/132fe8d0-5d03-43f4-b423-dfb6a820eef5)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/a9787f0f-94db-4200-98ac-82134cea7c63)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/adb19a92-4c15-420f-bfdf-fbcab7bcaeeb)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/021cef3f-9709-4922-bc7a-90d9581fb414)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/cdd3f208-b988-4521-8089-fb7416c40846)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/53f1de29-ada8-4754-9980-f85d3b0f8b2c)

![image](https://github.com/dresden-elektronik/deconz-rest-plugin/assets/45599888/774e9095-3fc4-4f5a-92ec-6b55e54334d8)

**Comment by Smanar** [comment]
Hello, DDF to try

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "ADEO",
  "modelid": "LDSENK02F",
  "vendor": "Adeo",
  "product": "Plug 16A",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_SMART_PLUG",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "refresh.interval": 360
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 1,
          "max": 300,
          "change": "0x00000064"
        }
      ]
    }
  ]
}
```


Like usualy, some vaue can need to be "corrected" (*10 or / 100 for exemple) just give me the value and the needed convertion.

**Comment by Idaho947** [comment]
Power is good. I look at the consumption after a couple of hour.

**Comment by Smanar** [comment]
50 watt during 30 mn give 0.025 KW/h.
On your capture we have divisor 100, multiplicator 1.

Honnestly not enought consumption to be sure for me ^^

Can replace 

```
        {
          "name": "state/consumption"
        },
```

by

```
{
  "name": "state/consumption",
  "read": {
    "at": "0x0000",
    "cl": "0x0702",
    "ep": 1,
    "fn": "zcl:attr"
  },
  "parse": {
    "at": "0x0000",
    "cl": "0x0702",
    "ep": 1,
    "eval": "Item.val = Attr.val *XX"
  },
  "refresh.interval": 300,
  "default": 0
}
```

With a better convertion than `"eval": "Item.val = Attr.val *XX"`

**Comment by Idaho947** [comment]
What do you mean whith :
With a better convertion than "eval": "Item.val = Attr.val *XX" ?

**Comment by Smanar** [comment]
For exemple 
`"eval": "Item.val = Attr.val * 10"`

or

`"eval": "Item.val = Attr.val / 10"`

**Comment by Idaho947** [comment]
Ok I let it like that one week and see if it's relevant.

**Comment by Idaho947** [comment]
Ok everythinks seems OK. You can valid the ddf.

**Comment by Smanar** [comment]
So without changes ? the same than here > https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7834#issuecomment-2206784102

**Comment by Idaho947** [comment]
Yes no change needed

**Comment by Smanar** [comment]
DDF created https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7855
