### ISSUE TITLE
Please upload new Windows beta version

### ISSUE THREAD

**Issue by Fury1SOG** [dresden-elektronik/deconz-rest-plugin#784]
Hello,

The newest version of the Windows beta versions available on the Dresden site is v2.05.35.
Would it be possible to upload more recent versions please?

**Comment by manup** [comment]
Yes, sorry for the delay, the new version 2.05.39 will be available for all platforms this week.

**Comment by Fury1SOG** [comment]
Thank you! I look forward to trying the new version.
