### ISSUE TITLE
Sonoff SNZB-05P Water Leak Sensor

### ISSUE THREAD

**Issue by madisdev** [dresden-elektronik/deconz-rest-plugin#7842]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Zigbee Water Leak Sensor

### Manufacturer

SonOff

### Model identifier

SNZB-05P

### Device type to add

Sensor

### Node info

![Node Info](https://github.com/user-attachments/assets/d25a57a7-8794-4a68-b4c5-3b677874bc42)

### Endpoints and clusters

![BasicCluster2](https://github.com/user-attachments/assets/fc2e6881-b47b-4ab5-86b7-919024fae85f)
#### IAS Zone
![IASZone](https://github.com/user-attachments/assets/e8fc53d6-8e42-41ba-a685-f58a36b2ef78)
#### Poll Control
![PollControl](https://github.com/user-attachments/assets/88415607-42be-49e2-9f21-173cfccb51f8)
### Power Configuration
![Powerconfig](https://github.com/user-attachments/assets/1314a66f-2bf4-41f6-ba96-eea00a687c22)

### Basic

![BasicCluster2](https://github.com/user-attachments/assets/a17717b7-20aa-42c9-b736-88699834de7b)

**Comment by madisdev** [comment]
I feel I could probably create the json and PR if someone could give me some pointers of what needs to be done.

**Comment by Smanar** [comment]
For me better to use

  "sleeper": true,
  "status": "Gold",

```
        {
          "name": "state/water",
          "parse": {
            "fn": "ias:zonestatus",
            "mask": "alarm1,alarm2"
          },
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0500",
            "at": "0x0002"
          },
          "awake": true,
          "refresh.interval": 84600
        }
```
But only if just 
```
          {
            "name": "state/water",
            "awake": true
          }
```
not working

You miss the bind part too
```

  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000002"
        }
      ]
    }
  ]
```

**Comment by madisdev** [comment]
How should I verify if the state/water isnt enough? I can see it updates state on contact with water. I am not sure what the refresh.interval or awake: true is accomplishing. Can you elaborate, I would like to learn. Thanks.

**Comment by Smanar** [comment]
You can't test the DDF ?
Make a test with just 
```
          {
            "name": "state/water",
            "awake": true
          }
```

The code will use defaut value for the rest, if it don't work, need to use custom settings so the big one for exemple 

```
        {
          "name": "state/water",
          "parse": {
            "fn": "ias:zonestatus",
            "mask": "alarm1,alarm2"
          },
          "read": {
            "fn": "zcl:attr",
            "ep": 1,
            "cl": "0x0500",
            "at": "0x0002"
          },
          "awake": true,
          "refresh.interval": 84600
        }
```

You are using `"refresh.interval": 1` not possible for a sleeping device, the report need to be "natural" using bind/report setting.
And in the situation the report don't work, the poll can't work too, as you haven't set the "read" part

**Comment by Smanar** [comment]
"parse" is used with incoming request from the device.
"read" is used when deconz ask for information itself (not realy effective on slepping device).

The natural working mode is with value set in bind.
```
          "min": 3600,
          "max": 43200,
          "change": "0x00000002"
```
You are asking the device to make report a minimum every 3600s, at maximum 43200 s without report, or if the value move with a difference of 2.

If it don't work, there is a watchdog, deconz will use the "refresh.interval" and force a "read", this is a security, never used if possible.

```
            "fn":fonction
            "ep": endpoint
            "cl": cluster
            "at": attribute
```
There are the same you can see usng deconz, if you dont set them, deconz will use defaut one, generaly it's a better method.
