### ISSUE TITLE
Third Reality inc - Smart Plug E2(type F, power monitoring), Model 3RSPE01044BZ

### ISSUE THREAD

**Issue by TheBisk** [dresden-elektronik/deconz-rest-plugin#7852]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Third Reality 3RSPE01044BZ

### Manufacturer

Third Reality

### Model identifier

3RSPE01044BZ

### Device type to add

Switch

### Node info
![image](https://github.com/user-attachments/assets/80f6399e-36e0-4c58-8ec0-52d58bfa79e6)

### Endpoints and clusters
![image](https://github.com/user-attachments/assets/efdf1691-1f82-45a6-80ef-e7d0f678ecb5)
![image](https://github.com/user-attachments/assets/28d60eed-c88d-4601-9383-fb11419e8ef2)

### Basic
![image](https://github.com/user-attachments/assets/6eae8383-84ce-4f83-983e-e318987d622b)

### Identify
![image](https://github.com/user-attachments/assets/2c622bc0-f72b-425d-8c60-db48023d3457)

### Simple Metering
![image](https://github.com/user-attachments/assets/99f557bc-0e6b-4a60-9633-e2e039218f5c)

### Electrical Measurement
![image](https://github.com/user-attachments/assets/1f5c46ab-96e0-4552-bb4a-0deb7c2fd44f)

### DDF
![image](https://github.com/user-attachments/assets/fa6fd414-18c8-48da-9974-7a3390372953)

**Comment by SwoopX** [comment]
Hi,

please provide the remaining and requested screenshots. Many thanks!

**Comment by TheBisk** [comment]
Do need something else? 
Thanks

**Comment by Smanar** [comment]
Hello, can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Third Reality, Inc",
  "modelid": "3RSPE01044BZ",
  "vendor": "Third Reality",
  "product": "Smart plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "read": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "read": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 360
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption"
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 10,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 10,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
```

Based on this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/third_reality/3RSP02028BZ_smart_plug.json

**Comment by TheBisk** [comment]
Tested quiclky and it seems to work. 
Now i have the switch and the sensors for power and consuption. I will test it better next days.

Thank you Smanar

**Comment by TheBisk** [comment]
i made some test and it seems that **the consumption value is too high**.
is there a way to reset the consumption and start from 0? the value looks read only...

Power
![image](https://github.com/user-attachments/assets/830299db-d0e1-424a-b8dc-00002a83c91c)

Consumption
![image](https://github.com/user-attachments/assets/7d4bd070-9979-462c-87cf-134c5f20944e)

Simple meetering
![image](https://github.com/user-attachments/assets/821537e5-e7e2-4355-89be-50113e61fe73)
![image](https://github.com/user-attachments/assets/b28c68eb-128c-4a45-8f9e-11ac53dc5152)

**Comment by Smanar** [comment]
Do you have the same capture for electrical measurement ?
Or use a device with a known power to see the convertion needed ? (a 10W bulb for exemple).
what do you have as current ?

For consumption can replace
```
        {
          "name": "state/consumption"
        },
```
by
```
        {
          "name": "state/consumption",
          "read": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 365
        },
```
Here it's just a "/10" to show you how it work because a divisor = 360 000 (from your capture) I m not sure it's something reliable.
Better to get 2 value with 1 h delay and a constant power.

**Comment by Smanar** [comment]
To reset consumption, with the GUI try on cluster 0x0000 the reset factory request.

**Comment by TheBisk** [comment]
Electrical Measurement 
![image](https://github.com/user-attachments/assets/2743a10d-5ef1-429d-a8ee-9725479c19a6)
![image](https://github.com/user-attachments/assets/7c74cfc4-c003-4ed3-a0f6-40f710d86227)
![image](https://github.com/user-attachments/assets/c6c57f2b-ee32-4ea6-9675-c39c45a407a0)
![image](https://github.com/user-attachments/assets/1b0ce730-b428-4ce5-87ab-c578cb5a5904)

**Comment by Smanar** [comment]
So from the device, same convertion than for voltage 1/10 for power.

**Comment by TheBisk** [comment]
> To reset consumption, with the GUI try on cluster 0x0000 the reset factory request.

i dont know how to do that...

**Comment by TheBisk** [comment]
> Hello, can try this DDF
> 
> ```
> {
>   "schema": "devcap1.schema.json",
>   "manufacturername": "Third Reality, Inc",
>   "modelid": "3RSPE01044BZ",
>   "vendor": "Third Reality",
>   "product": "Smart plug",
>   "sleeper": false,
>   "status": "Gold",
>   "subdevices": [
>     {
>       "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
>       "restapi": "/lights",
>       "uuid": [
>         "$address.ext",
>         "0x01"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "state/alert"
>         },
>         {
>           "name": "state/on",
>           "refresh.interval": 360
>         },
>         {
>           "name": "state/reachable"
>         }
>       ]
>     },
>     {
>       "type": "$TYPE_POWER_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0b04"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "state/current",
>           "refresh.interval": 360
>         },
>         {
>           "name": "state/lastupdated"
>         },
>         {
>           "name": "state/power",
>           "read": {
>             "at": "0x050b",
>             "cl": "0x0b04",
>             "ep": 1,
>             "fn": "zcl:attr"
>           },
>           "parse": {
>             "at": "0x050b",
>             "cl": "0x0b04",
>             "ep": 1,
>             "eval": "Item.val = Attr.val / 10"
>           },
>           "refresh.interval": 360
>         },
>         {
>           "name": "state/voltage",
>           "read": {
>             "at": "0x0505",
>             "cl": "0x0b04",
>             "ep": 1,
>             "fn": "zcl:attr"
>           },
>           "parse": {
>             "at": "0x0505",
>             "cl": "0x0b04",
>             "ep": 1,
>             "eval": "Item.val = Attr.val / 10"
>           },
>           "refresh.interval": 360
>         }
>       ]
>     },
>     {
>       "type": "$TYPE_CONSUMPTION_SENSOR",
>       "restapi": "/sensors",
>       "uuid": [
>         "$address.ext",
>         "0x01",
>         "0x0702"
>       ],
>       "items": [
>         {
>           "name": "attr/id"
>         },
>         {
>           "name": "attr/lastannounced"
>         },
>         {
>           "name": "attr/lastseen"
>         },
>         {
>           "name": "attr/manufacturername"
>         },
>         {
>           "name": "attr/modelid"
>         },
>         {
>           "name": "attr/name"
>         },
>         {
>           "name": "attr/swversion"
>         },
>         {
>           "name": "attr/type"
>         },
>         {
>           "name": "attr/uniqueid"
>         },
>         {
>           "name": "config/on"
>         },
>         {
>           "name": "config/reachable"
>         },
>         {
>           "name": "state/consumption"
>         },
>         {
>           "name": "state/lastupdated"
>         }
>       ]
>     }
>   ],
>   "bindings": [
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0006",
>       "report": [
>         {
>           "at": "0x0000",
>           "dt": "0x10",
>           "min": 1,
>           "max": 300
>         }
>       ]
>     },
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0702",
>       "report": [
>         {
>           "at": "0x0000",
>           "dt": "0x25",
>           "min": 10,
>           "max": 300,
>           "change": "0x0000000A"
>         }
>       ]
>     },
>     {
>       "bind": "unicast",
>       "src.ep": 1,
>       "cl": "0x0B04",
>       "report": [
>         {
>           "at": "0x0505",
>           "dt": "0x21",
>           "min": 10,
>           "max": 300,
>           "change": "0x00000001"
>         },
>         {
>           "at": "0x0508",
>           "dt": "0x21",
>           "min": 10,
>           "max": 300,
>           "change": "0x00000064"
>         },
>         {
>           "at": "0x050B",
>           "dt": "0x29",
>           "min": 10,
>           "max": 300,
>           "change": "0x00000001"
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> Based on this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/third_reality/3RSP02028BZ_smart_plug.json

This is the last working DDF, thanks Smanar
 ```
{
  "schema": "devcap1.schema.json",
  "manufacturername": "Third Reality, Inc",
  "modelid": "3RSPE01044BZ",
  "vendor": "Third Reality",
  "product": "Smart plug",
  "sleeper": false,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_ON_OFF_PLUGIN_UNIT",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/alert"
        },
        {
          "name": "state/on",
          "refresh.interval": 360
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_POWER_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0b04"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/current",
          "refresh.interval": 360
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/power",
          "read": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x050b",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 360
        },
        {
          "name": "state/voltage",
          "read": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0505",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 360
        }
      ]
    },
    {
      "type": "$TYPE_CONSUMPTION_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0702"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/consumption",
          "read": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0000",
            "cl": "0x0702",
            "ep": 1,
            "eval": "Item.val = Attr.val / 10"
          },
          "refresh.interval": 365
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0006",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x10",
          "min": 1,
          "max": 300
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0702",
      "report": [
        {
          "at": "0x0000",
          "dt": "0x25",
          "min": 10,
          "max": 300,
          "change": "0x0000000A"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0B04",
      "report": [
        {
          "at": "0x0505",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000001"
        },
        {
          "at": "0x0508",
          "dt": "0x21",
          "min": 10,
          "max": 300,
          "change": "0x00000064"
        },
        {
          "at": "0x050B",
          "dt": "0x29",
          "min": 10,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    }
  ]
}
 ```

**Comment by Smanar** [comment]
> i dont know how to do that...

Do you have the GUI, you have used it for capture. Just select the cluster 0x0000 "basic" (the blue number) and on the cluster panel you will the button.

The DDF is finished ? do you want to make a PR or want I make it ? (to have it officialy)

**Comment by TheBisk** [comment]
I think that is better if you make the PR (I don't know how to do that).
Thanks

**Comment by Smanar** [comment]
Done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7875

**Comment by TheBisk** [comment]
Hi Smanar,
I did some tests and I can confirm that the **consumption value** **is too high** compared to the watts supplied. 
My dryer worked for 2 hours and consumed on average 500watts per hour so I would expect +1kwh of consumption for 2 hours and not +250kwh. what do you think? 

Thank you.

![SmartSelect_20240923_135926_Home Assistant](https://github.com/user-attachments/assets/bd8cca73-f648-4d43-8840-4b925aeff57a)

![SmartSelect_20240923_140005_Home Assistant](https://github.com/user-attachments/assets/9e413252-cefc-4eba-8539-2c8ed0c61837)

**Comment by Smanar** [comment]
Lol, I think too ^^, from your capture the divisor is 3600000
So can try with 
`"eval": "Item.val = Attr.val / 360000"`

It will make 6kw/h if I m right.

BTW you haven't issue too with curent and voltage ?

**Comment by TheBisk** [comment]
> Lol, I think too ^^, from your capture the divisor is 3600000 So can try with `"eval": "Item.val = Attr.val / 3600000"`
> 
> It will make 0.6kw/h if I m right.
> 
> BTW you haven't issue too with curent and voltage ?

Smanar,
I did some more testing and it seems the correct divisor is 36000. As regards current, the value does not seem to update, when the device is turned off it shows current 66 and 1W while it should be 0. 
The voltage however seems ok

![SmartSelect_20241004_223005_Home Assistant](https://github.com/user-attachments/assets/37c36a54-a53d-40de-9987-771936bae883)

**Comment by Smanar** [comment]
You mean when you turn off the device, it keep the last value for current and power ? Or it use lower one ?
For information it can be the power used by the plug itself ? If I m right a plug use at least 0.5W in stand by mode.
