### ISSUE TITLE
Translations Missing for sensor in Phoscon menu (German)

### ISSUE THREAD

**Issue by kolorfilm** [dresden-elektronik/deconz-rest-plugin#7856]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Since the latest version the menu in Phoscon is missing a translation.

I just updated to the latest version 2.27.6 on a Conbee II.

### Steps to reproduce the behavior

1. open phoscon in browser
2. open the left menu
3. see the undefined menu bar

### Expected behavior

Should be correctly translated to german.

### Screenshots

<img width="271" alt="Bildschirmfoto 2024-07-26 um 21 33 50" src="https://github.com/user-attachments/assets/b2bd90cb-0856-4246-9d56-1dd3f827c3c3">

### Environment

- Host system: Raspberry Pi 4
- Running method: Raspbian
- Firmware version: 26780700
- deCONZ version (not Home assistant Addon version!): 2.27.6
- Device: ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? no

**Comment by Mimiix** [comment]
Hi,

Thanks for the report.

Phoscon bugs are collected on the forums. I kindly request you to open a topic there.

Closing this issue as it does not belong here.

Kind regards,
Dennis
