### ISSUE TITLE
Sonoff SNZB-04P

### ISSUE THREAD

**Issue by Wuehli** [dresden-elektronik/deconz-rest-plugin#7857]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

SNZB-04P

### Manufacturer

Sonoff 

### Model identifier

SNZB-04P

### Device type to add

Sensor

### Node info

![grafik](https://github.com/user-attachments/assets/a6c9942f-5808-45c3-a876-215d641b35ff)

### Endpoints and clusters

![grafik](https://github.com/user-attachments/assets/5c7114bf-f89c-4f21-b405-3e762bb7b129)

### Basic

![grafik](https://github.com/user-attachments/assets/9aeecbb5-3506-4a02-9d46-dd37cf8ad7a7)
![grafik](https://github.com/user-attachments/assets/85fd9870-d2df-4033-8151-3edb1df3fa1e)

### Power Configuration
![grafik](https://github.com/user-attachments/assets/bd87e9d9-b57b-46db-909d-69eded6cdb97)

### Any other cluster of relevance/interest

![grafik](https://github.com/user-attachments/assets/1863f03e-064d-499f-ac71-1b3da138cd29)

![grafik](https://github.com/user-attachments/assets/3e127423-27f0-49b7-8f6d-d221a24613cc)

![grafik](https://github.com/user-attachments/assets/b6db929d-29cb-47f7-8059-8a11e22cd37a)
![grafik](https://github.com/user-attachments/assets/41e23a53-d744-4efd-8b25-a0c357316fff)

**Comment by 1Rolf** [comment]
Any updates here? Did i miss something?

**Comment by dab0u** [comment]
I can't include this device with my conbee 3 neither.  Can I do something to help ?

**Comment by Mimiix** [comment]
@Smanar perhaps you can help after your holiday :)?

**Comment by Smanar** [comment]
Hello can try this DDF

```
{
  "schema": "devcap1.schema.json",
  "uuid": "cd25fbd8-9b9b-4051-9c01-1c08a9d65203",
  "manufacturername": ["eWeLink", "zbeacon", "eWeLink"],
  "modelid": ["DS01", "DS01", "SNZB-04P"],
  "vendor": "eWeLink",
  "product": "Open/close sensor (DS01)",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_OPEN_CLOSE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0500"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0x0001",
          "0x0500"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/battery",
          "awake": true,
          "parse": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "eval": "Item.val = Attr.val / 2;",
            "fn": "zcl:attr"
          },
          "read": {
            "fn": "none"
          }
        },
        {
          "name": "config/checkin"
        },
        {
          "name": "config/enrolled"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/pending"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/lowbattery",
          "awake": true
        },
        {
          "name": "state/open",
          "awake": true
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 3600,
          "max": 43200,
          "change": "0x00000002"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0500"
    }
  ]
}
```

It's just an optimisation of this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/sonoff/snzb-04_open_close_sensor.json

**Comment by JasonMask** [comment]
Hi,

as you can see from my screenshots in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7995 the "Model Identifier" of my device is "SNZB-04" (with out the P given for this device)

once I added that to the manufacturername/modelid lines the device could be found in the phoscon app:
`"manufacturername": ["eWeLink", "zbeacon", "eWeLink", "eWeLink"],`
`"modelid": ["DS01", "DS01", "SNZB-04P", "SNZB-04"],`

I hope this helps

Best regards

**Comment by Smanar** [comment]
Sure it help, and thx for it
Added here > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8002
