### ISSUE TITLE
Add support for MOES 1 Gang Switch

### ISSUE THREAD

**Issue by svenvoss** [dresden-elektronik/deconz-rest-plugin#7867]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

MOES ZigBee Funkschalter, Smartschalter ohne Installation, 1 Gang

### Manufacturer

_TZ3000_axpdxqgu

### Model identifier

TS0041

### Device type to add

Switch

### Node info

![Bildschirmaufnahme vom 2024-08-03 15:39:06](https://github.com/user-attachments/assets/6cdc4b1d-db06-48c7-8f6e-d47d636c9064)

### Endpoints and clusters

![Bildschirmaufnahme vom 2024-08-03 15:48:43](https://github.com/user-attachments/assets/68824240-65de-42bf-a662-66d4b3b41d7f)

### Basic

![Bildschirmaufnahme vom 2024-08-03 15:35:04](https://github.com/user-attachments/assets/c47c5bab-b2e5-42a2-a881-b913a308c4f8)

![Bildschirmaufnahme vom 2024-08-03 15:38:03](https://github.com/user-attachments/assets/dd133d9a-b5de-4942-b2b4-32cfba97d56e)

**Comment by Smanar** [comment]
Hello, can try adding your device to this list https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0041_1gang_remote.json
And in the button_maps.json file to test.

**Comment by svenvoss** [comment]
Hi,
thank you for the quick reply. I am sorry, but it is not fully clear to me what I should do. Could you please give me some more details what I should do.

The device is currently recognized as light but it is light/scene switch.

**Comment by Smanar** [comment]
>The device is currently recognized as light but it is light/scene switch.

Ha yes, this device is already supported, sorry.
But from the DDF this device need to be reconised as a ZHAswitch.

If I m right you need to be able to see websocket notification every time you press it, visible in Phoscon/help/API information/event

**Comment by svenvoss** [comment]
Deconz 6.23.0 

Installation via Homeassistant Addon on Raspberry Pi. The requested log:

![Bildschirmaufnahme vom 2024-08-05 21:22:11](https://github.com/user-attachments/assets/c2ac54e0-dd82-4e69-9a44-2fd9aa13ea8b)

For any reason copying from the log doesn't working.

**Comment by Smanar** [comment]
>For any reason copying from the log doesn't working.

This is normal on HA, but I don't understand On my side I can see it in my file.


`[1, "0x01", "ONOFF", "0xfd", "0", "S_BUTTON_1", "S_BUTTON_ACTION_SHORT_RELEASED", "B1 short"],`

>Deconz 6.23.0

This is the plugin version, not the deconz version (you can see it in phoscon)
This device was added here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7718 so need a deconz version > v2.27.0

**Comment by svenvoss** [comment]
HI, sorry for the delay. Is this what you meant?: 
![Bildschirmaufnahme vom 2024-08-12 14:59:53](https://github.com/user-attachments/assets/69756cf7-b73d-4918-a2b1-fdf138d63c06)

I have tried to update the conbee FW as described  here: https://community.home-assistant.io/t/how-to-update-conbee-ii-on-hassio-with-deconz-phoscon-integration/402826/12 but he didn't find any new software. Do I need to update something else and if yes how.

**Comment by Smanar** [comment]
Ok so the problem is here, you are on older version 2.25.3 (I mean the deconz version, not the device firmware), and this device have it's support on version v2.27.0

**Comment by svenvoss** [comment]
Is there any manual how to update the deconz version?

**Comment by Smanar** [comment]
Not on HA if you are using the "integrated deconz version".
They are using only Stable version, so they can use the version 2.27.6 if I m right.

**Comment by svenvoss** [comment]
Thank you very much for your time and support.

**Comment by Zehir** [comment]
> Not on HA if you are using the "integrated deconz version".
> They are using only Stable version, so they can use the version 2.27.6 if I m right.

Latest version of the HA plugin in hassio (6.23.0) use deconz version 2.25.3

**Comment by Smanar** [comment]
Yep but as the version 2.27.6 is stable, they will use it nope ,

**Comment by svenvoss** [comment]
because of your hints I have checked the plugin page/repo. They have already a closed pull request for the actual stable version. Hopefully it is included in the next release. 
Thank you all for your support!
