### ISSUE TITLE
Osram Plug 01 1.4.12 - not acting as repeater?

### ISSUE THREAD

**Issue by etique57** [dresden-elektronik/deconz-rest-plugin#787]
Hello,

I start having what I assume is range issues in my setup. I thought the Osram plugs were acting as a repeater for the zigbee network (along with any other zigbee item connected to the mains), isn't it the case?

I have several OSRAM plugs, several Ikea bulbs, OSRAM ceiling lights connected all over the place, I would assume my apartment is correctly meshed.

Am I missing something?

Cheers!

**Comment by ebaauw** [comment]
> I thought the Osram plugs were acting as a repeater for the zigbee network

My OSRAM plugs (the old LIGHTIFY and the newer PLUG01) are ZigBee routers.  You can check in the deCONZ GUI: yellow nodes are routers, grey nodes are end-devices.

> along with any other zigbee item connected to the mains

As a general rule of thumb, but not all mains-powered devices are routers.

**Comment by etique57** [comment]
Thanks @ebaauw 

Am currently fighting to get access to this deCONZ GUI :)

Just wondering, does the meshing works as well during the pairing process?

**Comment by ebaauw** [comment]
It should, but some more exotic devices only seem to pair well, when they’re connected directly to the RaspBee or ConBee.

**Comment by etique57** [comment]
Just for the record, I finally found out what was going on:
- a reset of the deconz gateway didn't really erase much, if anything (many rules and stuff)
- I don't know what happened, but a couple of my Xiaomi wallswitch actually got readded as "Ikea devices", and I couldn't reset them from the switch
- I used the rest API to find out which they were and deleted them, and I could add them back with no problem
