### ISSUE TITLE
Woox water leak sensor R7050 

### ISSUE THREAD

**Issue by raderack3948** [dresden-elektronik/deconz-rest-plugin#7872]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Woox R7050

### Manufacturer

_TZ3000_arw23zcs

### Model identifier

TS0207

### Device type to add

Sensor

### Node info

![image](https://github.com/user-attachments/assets/01c24c9f-115e-4217-8715-a6027128759a)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/487e1052-13cc-45a8-80aa-6927ef879469)

### Basic

![image](https://github.com/user-attachments/assets/cf864255-0359-4687-929a-959860ecd368)

### Further relevant clusters

![image](https://github.com/user-attachments/assets/487e1052-13cc-45a8-80aa-6927ef879469)

### Any other cluster of relevance/interest

![image](https://github.com/user-attachments/assets/347ea92e-9c7a-4921-b43a-1bcfeec5f3dd)

**Comment by Smanar** [comment]
Hello, probably just one more clone, can you try adding this model in this DDF https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0207_water_leak_sensor.json

Need to add the modelID AND the manufacture name.

**Comment by raderack3948** [comment]
Added it, I can pair it and see it in phoscon - but w/o any values?
![image](https://github.com/user-attachments/assets/712600b8-feb6-4e9a-aec5-c61aef8c9328)

**Comment by Smanar** [comment]
Perhaps Phoscon issue, can you check direclty in the API ? Using Phoscon/help/API Information/sensor ?

**Comment by raderack3948** [comment]
Hello, sure - attached:

```
{
    "config": {
        "battery": 0,
        "on": true,
        "pending": [],
        "reachable": true
    },
    "ep": 1,
    "etag": "XXX",
    "lastannounced": null,
    "lastseen": "2024-08-06T16:25Z",
    "manufacturername": "_TZ3000_arw23zcs",
    "modelid": "TS0207",
    "name": "Water",
    "state": {
        "lastupdated": "none",
        "lowbattery": null,
        "tampered": null,
        "water": null
    },
    "type": "ZHAWater",
    "uniqueid": "XXX"
}
```

**Comment by Smanar** [comment]
Strange no "swversion" and nothing updated (even battery)
And same after 24h ...

It probably a new device, I can't found information about it on google, but Woox have ever locked their tuya device. Can you try to re-include the device, but without deleting it (just to trigger again an enrollement for the IAS stuff) ?

**Comment by raderack3948** [comment]
Sorry to ask - how to I reinclude the device? :-)

**Comment by Smanar** [comment]
Just set the network in permit join, using phoscon, add new sensor, and make again the reset procedure on the device, all settings will be keep.

**Comment by raderack3948** [comment]
It worked! Sensor works after repairing. On the first one I've got the following message, but the sensor is in the system and working:
![image](https://github.com/user-attachments/assets/d76f7d03-5402-43ac-a214-3e4c7ed7a3ae)

**Comment by Smanar** [comment]
Ok, so was because of a bad inclusion/enrollement.
Do you want to make a PR to add this device or want I make it ?

**Comment by raderack3948** [comment]
It would be great if you could do that (I don't know how) :-). Thanks a lot for your help!!

**Comment by Smanar** [comment]
Depend of OS, what is your ?
You just need to create a text file with this contain in a "devices" folder.

**Comment by Smanar** [comment]
Done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7878
