### ISSUE TITLE
Mumibiz TYZGTH4CH with temperature

### ISSUE THREAD

**Issue by enboer** [dresden-elektronik/deconz-rest-plugin#7874]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Mumibiz TYZGTH4CH

### Manufacturer

Mumibiz

### Model identifier

TYZGTH4CH

### Device type to add

Switch

### Node info

![nodeinfo](https://github.com/user-attachments/assets/328ba07c-0582-494a-bf8f-936ed70336e3)

### Endpoints and clusters

DEvice has 4 switches and a temp sensor. 4 switches are working fine. But I cannot get the temperature to work. Added the ZHA temperature as a new item (DDF edit). But I do not get that to work.

### Basic

![cluster](https://github.com/user-attachments/assets/34cb1d3f-3a2f-4bd9-a608-84e3a826bb64)

**Comment by Mimiix** [comment]
Please add all screenshots.

**Comment by enboer** [comment]
additional info
![onoff](https://github.com/user-attachments/assets/9bf74b5e-f0f7-4220-9c71-2078dfa9b83f)

![otau](https://github.com/user-attachments/assets/1f098cda-d9f0-41df-956f-9c7d7b0f2bee)

![tuya_spec](https://github.com/user-attachments/assets/b164328f-f9d0-47f4-a0df-037730aa2f58)

![identify](https://github.com/user-attachments/assets/70635181-f49a-4cbd-82cb-76669828cd91)

![basic](https://github.com/user-attachments/assets/b8786002-0037-4169-a4dc-ad501259e244)

**Comment by enboer** [comment]
Maybe this helps? https://www.zigbee2mqtt.io/devices/TYZGTH4CH-D1RF.html

**Comment by Smanar** [comment]
The temperature sensor need to be like this one

```
   {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/battery",
          "parse": {"fn": "tuya", "dpid": 4, "eval": "Item.val = Attr.val;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = 10 * Attr.val + R.item('config/offset').val;" },
          "read": {"fn": "none"},
          "default": 0
        }
      ]
    }
```

Not sure for the dpid, it's from https://github.com/Koenkk/zigbee2mqtt/issues/23041

**Comment by Smanar** [comment]
The temperature sensor need to be like 

```
   {
      "type": "$TYPE_TEMPERATURE_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0402"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/offset",
          "default": 0
        },
        {
          "name": "config/battery",
          "parse": {"fn": "tuya", "dpid": 4, "eval": "Item.val = Attr.val;" },
          "read": {"fn": "none"},
          "default": 0
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/lastupdated"
        },
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 1, "eval": "Item.val = 10 * Attr.val + R.item('config/offset').val;" },
          "read": {"fn": "none"},
          "default": 0
        }
      ]
    }
```

Just add it to your previous DDF, or if you share it I can complete it.

**Comment by enboer** [comment]
Sorry for replying this late... Thanks for your help. I added it to the json file I get the devices, but not the temp sensor. Also in Deconz I do not see the Temp section or the temp value.

[TZ3218.json](https://github.com/user-attachments/files/17167760/TZ3218.json)

In Deconz I see the updated file is used (changed the device description) but no temp updates

**Comment by enboer** [comment]
![2024-09-27_19-54-31](https://github.com/user-attachments/assets/ddb9634f-217f-4d62-8bc7-bb1ec93d72c6)

**Comment by Smanar** [comment]
It will be not visible on deconz but in the API, using for exemple Phoscon/help/API Information/sensor

**Comment by enboer** [comment]
Added device again. In Phoscon I see the temp sensor. Only temp value stays at 0 degree

**Comment by Smanar** [comment]
Have you aded the tuya unlock sequence ?
```
	{
	 "name": "config/tuya_unlock"
	},
```

You need to re-include the device after or wait 24h.

**Comment by enboer** [comment]
I have added this. unpaired, stopped deconz. Started deconz and paired again. But in the .json file I added the text you have suggested. But in the DDF in Deconz Gui I see some more info. See picture.
![2024-10-02_16-13-40](https://github.com/user-attachments/assets/e8cb66a8-800b-401d-9c9b-9dd9df968adc)

**Comment by Smanar** [comment]
Yeah, the editor make too much "magic".
On my side I use only text editor, but all codes are good, one is the 'light" code that use the defaut code, and the second one is the defaut code (complete).

And still no report for temperature ? lot of tuya device are locked and need this request.
You can too take a look on logs, deconz/help/debug view, with flag "DDF", to see DDF output, if you have nothing on them can use "info" and "info_l2" you will see "tuya output", perhaps I m using a bad dpid.

**Comment by enboer** [comment]
I am again debugging this  device as you suggest. This is what I see in the info/infl_l2 view. Tried with dpid 1 and 2, but same behavior. Does this info give you any clue?

![Image](https://github.com/user-attachments/assets/d490318e-abde-42eb-83c6-d93d0f3d3f42)

)

**Comment by Smanar** [comment]
Nope this device use tuya cluster, so need to catch tuya debug.
But I have found the dpid on another project

```
        {
          "name": "state/temperature",
          "parse": {"fn": "tuya", "dpid": 102, "eval": "Item.val = 10 * Attr.val + R.item('config/offset').val;" },
          "read": {"fn": "none"},
          "default": 0
        }
```

and 103 for humidity.

**Comment by enboer** [comment]
yes this is working thanks!!

**Comment by Smanar** [comment]
Sure, do you want to make the PR ?
Or want I make it ?

**Comment by enboer** [comment]
Can you do that, I do not exactly know the process. Thanks

**Comment by Smanar** [comment]
Done > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8142
Have edited the json, but for me it's fine, have just removed useless stuff.
