### ISSUE TITLE
Sonoff SNZB-02P Temperature and Humidity sensor

### ISSUE THREAD

**Issue by danieldemus** [dresden-elektronik/deconz-rest-plugin#7881]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

SNZB-02P Zigbee Temperature and Humidity Sensor

### Manufacturer

Sonoff/eWeLink

### Model identifier

SNZB-02P

### Device type to add

Sensor

### Node info

![SNZB-02P nodeinfo](https://github.com/user-attachments/assets/3669e690-594b-4351-b3b6-27cfe3e5f5b9)

### Endpoints and clusters

![SNZB-02P clusters](https://github.com/user-attachments/assets/ca447d63-349c-467f-b7b9-89b428b334c9)

### Basic

![SNZB-02P basic cluster](https://github.com/user-attachments/assets/6b3c57c9-2ad9-4f04-94d8-f07f58121b14)

### Power Configuration
![SNZB-02P power configuration cluster](https://github.com/user-attachments/assets/bd999081-3b5f-45d4-81a9-08b9ef9ce949)

#### Poll control
![SNZB-02P poll control cluster](https://github.com/user-attachments/assets/a6fbd092-428e-4ddc-abdc-2e9b367f5d0a)

#### Temperature measurement
![SNZB-02P temperature measurement cluster](https://github.com/user-attachments/assets/91d86034-60cf-4e64-b3ee-84ec68f8b3f9)

#### Relative humidity measurement
![SNZB-02P relative humidity measurement cluster](https://github.com/user-attachments/assets/09129233-166b-4386-afbe-fd8a0bfbe855)

#### OTAU
![SNZB-02P OTAU cluster 1](https://github.com/user-attachments/assets/9a270c06-6bc8-42b5-9c19-82261eda3332)
![SNZB-02P OTAU cluster 2](https://github.com/user-attachments/assets/e682d723-cf99-42ee-91b9-2c433da040b8)

#### Sonoff specific
![SNZB-02P sonoff specific cluster](https://github.com/user-attachments/assets/50865e56-0cb8-442d-9937-e19e9192bd64)

**Comment by Mimiix** [comment]
@SwoopX looks like they use a new manufacturer name? This was added before afaik in 2.25.0

**Comment by Smanar** [comment]
Ha yes right, there is a DDF but can be optimised > https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/sonoff/snzb-02-multisensor.json

Can you try editing the file to have

```
  "manufacturername": ["eWeLink","SONOFF","SONOFF", "eWeLink"],
  "modelid": ["TH01","SNZB-02D","SNZB-02P", "SNZB-02P"],
```

**Comment by SwoopX** [comment]
> @SwoopX looks like they use a new manufacturer name? This was added before afaik in 2.25.0

Yeah. What I dislike looking at Smanar's referenced DDF is that the old and new model of the sensor are getting mixed together, although content-wise, they might be the same. Would prefer to have that seperated in the future, but it can easily be detangled.

**Comment by danieldemus** [comment]
The manufacturername string is the same as the old SNZB-02: eWeLink. I don't know if that's mapped from some enum.
The main differences between the old and new SNZB-02 (aka TH01) and the SNZB-02P are the OTAU, Poll control and Sonoff specific clusters, which is quite a lot, so mashing it together with the old sensors DDF seems optimistic.
I am not aware of any light sensor in a temperature and humidity sensor, but YMMV...
