### ISSUE TITLE
Xiaomi Aqara FP1E

### ISSUE THREAD

**Issue by thomasgolda** [dresden-elektronik/deconz-rest-plugin#7885]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Aqara Millimeter Wave Presence Sensor FP1E

### Manufacturer

aqara

### Model identifier

lumi.sensor_occupy.agl1

### Device type to add

Sensor

### Node info

<img width="398" alt="screenshot_03" src="https://github.com/user-attachments/assets/4bd3e94e-d978-457d-a88d-5884d017f647">

### Endpoints and clusters

<img width="341" alt="screenshot_02b" src="https://github.com/user-attachments/assets/99adcf10-0715-4b8f-96fd-915867406237">

### Basic

<img width="237" alt="screenshot_01" src="https://github.com/user-attachments/assets/4c4bb116-4b3f-40a3-acc3-0bc5e857975a">

### Further relevant clusters

<img width="341" alt="screenshot_04a" src="https://github.com/user-attachments/assets/30538bea-b997-49ff-b416-65d27d45ca6a">
<img width="326" alt="screenshot_04b" src="https://github.com/user-attachments/assets/1aa5232d-bb42-4cc8-a0b5-10a6d0e67fc5">

**Comment by SwoopX** [comment]
@thomasgolda could you please change the model identifier and manufacturer as per our template? Thanks!

**Comment by thomasgolda** [comment]
@SwoopX I updated both as given in the basic cluster. Hope that's correct.

**Comment by SwoopX** [comment]
Looking good, thanks a lot! Helps finding the issue again 👍

**Comment by ebaauw** [comment]
Note that it uses _Manufacturer Code_ 0x1234, and consequently, that version of the 0xFCC0 cluster (with generic attributes).

Sniffing the device while connected to the Aqara Hub M1 reveals the following attributes:

Attr | DT | R | W | Description
-- | -- | -- | -- | --
0x00E8 | bool | - | W | Restart device.
0x010C| u8 | - | - | Motion Sensitivity (got a report, but no corresponding setting in the Aqara app).
0x0142 | u8 | R | - | Presence.
0x0157 | u8 | - | W | Reset Presence (app sets this on AI Learning).
0x0159 | u8 | R | W | Unknown (value 1).
0x015A | u32 | R | W | Unknown (value 600).
0x015B | u32 | R | W | Detection Range (in cm, Aqara app sets from 0 .. 600, in increments of 30).
0x015C | u8 | R | W | Unknown (value 1).
0x015D | u8 | R | W | Unknown (value 1).
0x015E | u8 | R | W | Unknown (value 1).
0x015F | u32 | R | - | Position (distance of detected human, in cm).
0x0160 | u8 | R | - | Unknown (seeing values 2 (when no presence), and 3, 4 (when presence)).

0x0142, 0x015F and 0x0160 are reported frequently, as soon as changes occur.  The other attributes where reported only on device restart.

Also got a Xiaomi special attribute 0x00F7:
```
                     1 2  3  4 5  6 7  8 9  0 1  2 3  4 5  6 7  8  9 0  1  2 3  4  5 6  7  8 9  0
	 attr tp  l    temp   RSSI dB  firmware    parent       ?       ?       ?       ?       ?
         ---- -- -- ------- --------- --------- --------- ------- ------- ------- ------- -------
fp1e:    00f7 41 1e 0328 22 0521 0400 0821 1c01 0a21 0000 0c20 14 1020 01 1220 00 6520 00 6620 01
                 30                  0.0.0_0028
```
This seems to be sent only on restart, not after occupancy changes.

Note that I got a firmware update to 0.0.0_0028.

Also note that the device reacts to _Identify_.

**Comment by ebaauw** [comment]
The DDF results in the following resource:
```json
{
  "config": {
    "detectionrange": 600,
    "on": true,
    "reachable": true,
    "resetpresence": false
  },
  "etag": "87b6a6502dc209729465632492469ebf",
  "lastannounced": null,
  "lastseen": "2024-08-23T20:18Z",
  "manufacturername": "aqara",
  "modelid": "lumi.sensor_occupy.agl1",
  "name": "Presence 155",
  "state": {
    "distance": 30,
    "lastupdated": "2024-08-23T20:18:45.196",
    "presence": true
  },
  "swversion": "0.0.0_0028",
  "type": "ZHAPresence",
  "uniqueid": "54:ef:44:10:00:db:19:b1-01-0406"
}
```
Note that the cluster in the `uniqueid` is a blatant lie, just as for the FP1.
