### ISSUE TITLE
Moes ZSS-S01-GWM-C - Smart Door/Window Sensor

### ISSUE THREAD

**Issue by alexborro** [dresden-elektronik/deconz-rest-plugin#7887]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Moes ZSS-S01-GWM-C - Smart Door/Window Sensor

### Manufacturer

_TZ3000_8yhypbo7

### Model identifier

TS0203

### Device type to add

Sensor

### Node info

![image](https://github.com/user-attachments/assets/b26cef6a-3d2c-44de-bce4-8b3dd8247e00)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/947a0654-565c-450d-8bee-6fc4ab7c19de)

### Basic

![image](https://github.com/user-attachments/assets/8a9bce82-7da9-485d-98af-dcc5ead14252)

### Power Configuration
![image](https://github.com/user-attachments/assets/c0b64333-8a50-426a-822f-b1004a324555)

### IAS Zone
![image](https://github.com/user-attachments/assets/4332a796-a4b0-406a-9650-6a9d188db6c9)

**Comment by Smanar** [comment]
Hello can you  try to adding your device to this list ?

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_TS0203_door_sensor.json

**Comment by alexborro** [comment]
Very good, it shows up like the pictures below.
The Open/Close state is working, but it didnt display any other information, like the battery level (it seems to have it according to the Power Configuration cluster).

Any idea how I can try to add it ?

When finished, I can make a PR for these changes.

Cheers.
Alex.

![image](https://github.com/user-attachments/assets/71362227-3056-473c-ab6e-96216f01b829)

![image](https://github.com/user-attachments/assets/b04f271f-290d-49b7-99bc-c12dd649f2b5)

**Comment by Smanar** [comment]
The DDF (try to) catch the battery level too, perhpas need some time or the settings have failed at inclusion.
But this device haven't a "force read" every 24h.

If after 24h you still have nothing, try to re-include the device, without deleting it.

If after 24h again try adding on config/battery part

```
          "refresh.interval": 86400,
          "read": {
            "at": "0x0021",
            "cl": "0x0001",
            "ep": 1,
            "fn": "zcl:attr"
          },
```
