### ISSUE TITLE
TZ3000 BSEED reports wrong power

### ISSUE THREAD

**Issue by enboer** [dresden-elektronik/deconz-rest-plugin#7888]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

_TZ3000_4ux0ondb

### Manufacturer

BSEED

### Model identifier

https://www.bseed.com/products/bseed-zigbee-eu-wall-sockets-power-outlets-with-energy-monitoring-kids-protection

### Device type to add

Switch

### Node info

https://www.bseed.com/products/bseed-zigbee-eu-wall-sockets-power-outlets-with-energy-monitoring-kids-protection

![bseed-identify](https://github.com/user-attachments/assets/31c1f1c0-e96a-4a04-9f28-10a16b53ea82)

### Endpoints and clusters

![bseed_cluster](https://github.com/user-attachments/assets/9fa34af8-a0f8-413c-8728-272fba8cc27d)

### Basic

![bseed-basic](https://github.com/user-attachments/assets/4b9b079f-cf40-4ec2-9b10-dc09c5ebbb37)

### On/Off
![bseed_metering](https://github.com/user-attachments/assets/033a6ba1-c344-43fb-9acb-267544f475b7)

### Level Control
![bseed-otau](https://github.com/user-attachments/assets/14a30b50-4e46-44cc-8d05-b60eaaf6547d)

### Simple Metering
![bseed_measurement](https://github.com/user-attachments/assets/4218b3e8-75f2-4559-ad8d-33f95a9792f8)

**Comment by enboer** [comment]
Device is working but reports wrong RMS current and Active Power. In this measurement picture the RMS current should be around 186, and the Active power should be around 42Watt

**Comment by Smanar** [comment]
>but reports wrong RMS current and Active Power

Youi have made a DDF ? I don't found this device on my side

**Comment by enboer** [comment]
Device was added to Deconz. When I do a added DDF I see this:
![bseed_added](https://github.com/user-attachments/assets/eee017a6-5b08-4de9-9fbf-af87d94ca40e)

The metering is then already working (then already with wrong values) but I do not see the Power/Voltage device in Domoticz.

I then dragged these metering to the binding section of the DDF Editor. But that does not work yet.

**Comment by Smanar** [comment]
Your DDF is not used, you have the "draft" status.
You can try with editing this one https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/tuya/_TZ3000_cehuw1lw_smartplug_EU.json

Can just replace the manufacture name by yours.

**Comment by enboer** [comment]
I did change that to Gold later. But you json file is working, however I still have incorrect power value. It reports 1000Watt, but this should be 40-45watt. I see these values already in the DeconzGUI.

**Comment by Smanar** [comment]
On your capture, I m seing U = 233 and I = 2.3A so the power is more than 500W, why 45 W, what is the device connected to the plug ?

**Comment by enboer** [comment]
Here are the correct screenshots. I have put 2 devices in serie. You see the difference in domoticz. And also 2 screenshots of the value in Deconz. The one is I 186 and Power of 42 is correct. The TZ3000 reports 2357 and 1130Watt for the same load.

![domoticz](https://github.com/user-attachments/assets/e170620f-6a9a-4c80-b070-35cb4d956f84)
![plug1](https://github.com/user-attachments/assets/54dd820a-4dde-45f0-b5f4-bef8cb5c431a)
![wall](https://github.com/user-attachments/assets/88c3c75b-b80a-49f7-8ed4-17df55e41a04)

**Comment by enboer** [comment]
That strange as for other zigbee devices these values can be used directly. Do I need to do that in the DDF? or in eg Domoticz via some automation?

**Comment by Smanar** [comment]
>Do I need to do that in the DDF

You mean a "convertion" like the /12 needed for the current ? So yes, but if you have another device with the same manufacture name / Model ID, I almost sure it will not need it, for me the problem is from this device.

If you want to use a "corrective", can create a DDF (or clone an existing one and change the ManufactureName/ModelID) and use for exemple

```
        {
          "name": "state/current",
          "read": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "fn": "zcl:attr"
          },
          "parse": {
            "at": "0x0508",
            "cl": "0x0b04",
            "ep": 1,
            "eval": "Item.val = Attr.val / 12"
          },
          "refresh.interval": 365
        },
```

This code will /12 the raw value for the current, and Domoticz will use the corrected one.

**Comment by enboer** [comment]
Thanks this works, seems it should be / 24. Is there a way to reset the total consumed power. I see the value in Deconz, but that is readonly.

**Comment by Smanar** [comment]
Yes If I remember, on the GUI on the cluster 0x0000 the "Basic", you have a "reset" command.
