### ISSUE TITLE
Zigbee Solar Rain Sensor RB-SRAIN01

### ISSUE THREAD

**Issue by Idaho947** [dresden-elektronik/deconz-rest-plugin#7892]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Zigbee Solar Rain Sensor

### Manufacturer

Tuya

### Model identifier

RB-SRAIN01

### Device type to add

Sensor

### Node info

![image](https://github.com/user-attachments/assets/a221b38c-356d-4ec6-b343-f5b4a6c285eb)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/0cad6d19-71f5-45f3-ad75-b97f6fe4c91c)

### Basic

![image](https://github.com/user-attachments/assets/9fa7acef-59ad-432d-8bd2-fd023da76c1e)

![image](https://github.com/user-attachments/assets/60a25de0-ad20-47fc-a1d9-9aff01547b2a)

### Power Configuration
![image](https://github.com/user-attachments/assets/948f9050-f267-48a2-a1a0-83164db9cfba)

### Scene
![image](https://github.com/user-attachments/assets/781a9674-dab8-43c5-916f-0b2502353040)

### IAS Zone
![image](https://github.com/user-attachments/assets/87ab300a-479e-42b8-af60-03737ffbd164)

### Groups
![image](https://github.com/user-attachments/assets/4fae92e9-c7f2-4502-aaf5-db07cab89e0b)

More usefull information here :
https://smarthomescene.com/reviews/tuya-zigbee-solar-rain-sensor-rb-srain01-review/

**Comment by Smanar** [comment]
Lol, seriously you are specialised in fucking exotic device .....

What to do with his one ....

`[101, 'illuminance', tuya.valueConverter.raw]`
ok can use `state/lightlevel`

But for others

```
            [102, 'illuminance_average_20min', tuya.valueConverter.raw],
            [103, 'illuminance_maximum_today', tuya.valueConverter.raw],
            [104, 'cleaning_reminder', tuya.valueConverter.trueFalse],
            [105, 'rain_intensity', tuya.valueConverter.raw],
```

?????

**Comment by Idaho947** [comment]
yes, I love testing things! Most of the time I resell them but this one, a zigbee peripheral with solar power, I couldn't pass it up ^^.

I've put a link in topic 1 that explains how it works in English much better than I could. 
https://smarthomescene.com/reviews/tuya-zigbee-solar-rain-sensor-rb-srain01-review

it displays intensities that must then be converted in the home automation software into something that corresponds to reality.

**Comment by Shikaban** [comment]
I have the same device, and while reading the information in raw format is possible, having it integrated into Deconz would be awesome. Is there any way I can contribute to help with this?

**Comment by Smanar** [comment]
But my problem is how to show the device in the API.
I can't use state/voltage for a ZHAHumidity, the API is realy locked.

 And not sure create 3 ZHAPower is a good thing, hard for you to reconise what is what ....

**Comment by Idaho947** [comment]
> Everything seams good, but I can't integrate the ddf file, it keeps failing

What do you mean ? It doesn't recongnize you sensor ?

**Comment by Shikaban** [comment]
No the sensor is inside the deconz ( I can only see him from the gui and not from phoscon )
But I've tried to load the ddf even restarting the raspberry or the service but nothing changed sensor is there but no information available.

**Comment by Idaho947** [comment]
I try this week end and my deconz server can't had the sensor...

**Comment by Idaho947** [comment]
OK done so got that in phoscon :
![image](https://github.com/user-attachments/assets/2409691e-d7bd-4e6b-a440-394c2e156d64)

But nothing in HA. The entitie is not created.

**Comment by Smanar** [comment]
For me it's normal.
ZHAHumidity for exemple have generaly a state/humidity but not a state/voltage, so HA ignore them.

**Comment by Idaho947** [comment]
Yes logic.

So I can t use it in home assistant ?

**Comment by Shikaban** [comment]
How you managed to import the ddf in deconz? I always get "failed to import"

**Comment by Idaho947** [comment]
I put it in the tuya folder in device folder.

**Comment by RneeJ** [comment]
I want to buy it to, would be great if it could be used. 

I found this recent info : [https://github.com/zigpy/zha-device-handlers/issues/3249](url)

**Comment by Beersteak** [comment]
Hi,

i dont know if its the right way but i like to reopen this device request. There has been some development in the meantime.
The sensor has been added to ZHA, before that you had to use a custom quirk.
I got it running in deCONZ, thanks to @Smanar 
I just changed the state/voltage to state/humidity for the dpid 105.

Here's my .json
`{
    "schema": "devcap1.schema.json",
    "manufacturername": "_TZ3210_tgvtvdoc",
    "modelid": "TS0207",
    "vendor": "Tuya",
    "product": "Solar Rain Sensor",
    "sleeper": true,
    "status": "Gold",
    "ddfvalidate": false,
    "subdevices": [
        {
            "type": "$TYPE_HUMIDITY_SENSOR",
            "restapi": "/sensors",
            "uuid": [
                "$address.ext",
                "0x01",
                "0x0405"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001",
                        "script": "../tuya/tuya_swversion.js"
                    },
                    "read": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/battery",
                    "parse": {
                        "fn": "tuya",
                        "dpid": 4,
                        "eval": "Item.val = (100 * Attr.val) + R.item('config/offset').val;"
                    },
                    "read": {
                        "fn": "none"
                    },
                    "default": 0
                },
                {
                    "name": "config/offset",
                    "default": 0
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "state/lastupdated"
                },
                {
                    "name": "state/humidity",
                    "parse": {
                        "fn": "tuya",
                        "dpid": 105,
                        "eval": "Item.val = Attr.val;"
                    },
                    "read": {
                        "fn": "none"
                    },
                    "default": 0
                }
            ]
        },
        {
            "type": "$TYPE_LIGHT_LEVEL_SENSOR",
            "restapi": "/sensors",
            "uuid": [
                "$address.ext",
                "0x01",
                "0x0400"
            ],
            "items": [
                {
                    "name": "attr/id"
                },
                {
                    "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001",
                        "script": "../tuya/tuya_swversion.js"
                    },
                    "read": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                    "name": "config/battery",
                    "parse": {
                        "fn": "tuya",
                        "dpid": 4,
                        "eval": "Item.val = Attr.val;"
                    },
                    "read": {
                        "fn": "none"
                    },
                    "default": 0
                },
                {
                    "name": "config/offset",
                    "default": 0
                },
                {
                    "name": "config/on"
                },
                {
                    "name": "config/reachable"
                },
                {
                    "name": "state/lastupdated"
                },
                {
                    "name": "state/voltage",
                    "parse": {
                        "fn": "tuya",
                        "dpid": 101,
                        "eval": "Item.val = Attr.val;"
                    },
                    "read": {
                        "fn": "none"
                    },
                    "default": 0
                }
            ]
        }
    ]
}`

it now looks like this:

![Image](https://github.com/user-attachments/assets/79bc866a-a36b-4052-b776-9d7b47f015db)

BUT it is still not exposed to Home Assistant. Can someone help me and maybe then we can add the sensor to a future release?

**Comment by Smanar** [comment]
Thx, do you want to make a Pr to correct the DDF or want I make it ?

And looking DDF you need to have at least the ZHAhumidity on HA.
But I m agree the ZHALightLevel is "exotic" with the state/voltage (dpid 101), It's not possible to convert the voltage to lightlvel ?

**Comment by Beersteak** [comment]
Thanks for your answer, i tried a few new things and i am a bit further; if we fix the problem i can make a Pr myself

The new Version is
```
{
   "schema": "devcap1.schema.json",
   "manufacturername": "_TZ3210_tgvtvdoc",
   "modelid": "TS0207",
   "vendor": "Tuya",
   "product": "Solar Rain Sensor",
   "sleeper": true,
   "status": "Gold",
   "ddfvalidate": false,
   "subdevices": [
       {
           "type": "$TYPE_LIGHT_LEVEL_SENSOR",
           "restapi": "/sensors",
           "uuid": [
               "$address.ext",
               "0x01",
               "0x0400"
           ],
           "items": [
               {
                   "name": "attr/id"
               },
               {
                   "name": "attr/lastannounced"
               },
               {
                   "name": "attr/lastseen"
               },
               {
                   "name": "attr/manufacturername"
               },
               {
                   "name": "attr/modelid"
               },
               {
                   "name": "attr/name"
               },
               {
                   "name": "attr/swversion",
                   "parse": {
                       "fn": "zcl:attr",
                       "ep": 1,
                       "cl": "0x0000",
                       "at": "0x0001",
                       "script": "../tuya/tuya_swversion.js"
                   },
                   "read": {
                       "fn": "zcl:attr",
                       "ep": 1,
                       "cl": "0x0000",
                       "at": "0x0001"
                   }
               },
               {
                   "name": "attr/type"
               },
               {
                   "name": "attr/uniqueid"
               },
               {
                   "name": "config/offset",
                   "default": 0
               },
               {
                   "name": "config/on"
               },
               {
                   "name": "config/reachable"
               },
               {
                   "name": "state/lastupdated"
               },
               {
                   "name": "state/lightlevel",
                   "parse": {
                       "fn": "tuya",
                       "dpid": 101,
                       "eval": "Item.val = Math.round(10000 * Math.log10(Attr.val) + 1);"
                   },
                   "read": {
                       "fn": "none"
                   },
                   "default": 0
               }
           ]
       },
       {
           "type": "$TYPE_HUMIDITY_SENSOR",
           "restapi": "/sensors",
           "uuid": [
               "$address.ext",
               "0x01",
               "0x0405"
           ],
           "items": [
               {
                   "name": "attr/id"
               },
               {
                   "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001",
                        "script": "../tuya/tuya_swversion.js"
                    },
                    "read": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
				{
				  "name": "config/battery",
				  "awake": true,
				  "refresh.interval": 7265,
				  "read": {
					"at": "0x0021",
					"cl": "0x0001",
					"ep": 1,
					"fn": "zcl:attr"
				  },
				  "parse": {
					"at": "0x0021",
					"cl": "0x0001",
					"ep": 1,
					"eval": "Item.val = Attr.val / 2"
				  },
				  "default": 0
				},
                {
                   "name": "state/humidity",
                   "parse": {
                       "fn": "tuya",
                       "dpid": 105,
                       "eval": "Item.val = Attr.val;"
                   },
                   "read": {
                       "fn": "none"
                   },
                   "default": 0
               }
           ]
       }
   ]
}
```
in deCONZ it now looks like this:

![Image](https://github.com/user-attachments/assets/201dd83c-0b4a-446e-bb43-df7565256576)

But in Home Assistant the Lightsensor is missing:

![Image](https://github.com/user-attachments/assets/0c441c39-20bf-444c-a097-02811037ae93)

i can see the Lightlevel in the Diagnostics:

![Image](https://github.com/user-attachments/assets/8a998225-98f7-49b7-819f-433c32a68c4c)

do you have an idea?

**Comment by Smanar** [comment]
Yep for me, the DDF is fine.
When the HA plugin detect a new device it make his magic, check the fields and add stuff or not to HA.
If the DDF is edited, the json in the API change, but if I m right HA don't remake his magic again.

You don't have a way to remove the device from HA for it detect it again ?

**Comment by Beersteak** [comment]
ok so, i tried adding the device from scratch with my DDF, works almost fine.
the state/voltage and state/lux are gone, but the battery is not there, but in deConz.

I tried adding it as TYPE_BATTERY_SENSOR
'''
{
   "schema": "devcap1.schema.json",
   "manufacturername": "_TZ3210_tgvtvdoc",
   "modelid": "TS0207",
   "vendor": "Tuya",
   "product": "Solar Rain Sensor",
   "sleeper": true,
   "status": "Gold",
   "ddfvalidate": false,
   "subdevices": [
       {
           "type": "$TYPE_LIGHT_LEVEL_SENSOR",
           "restapi": "/sensors",
           "uuid": [
               "$address.ext",
               "0x01",
               "0x0400"
           ],
           "items": [
               {
                   "name": "attr/id"
               },
               {
                   "name": "attr/lastannounced"
               },
               {
                   "name": "attr/lastseen"
               },
               {
                   "name": "attr/manufacturername"
               },
               {
                   "name": "attr/modelid"
               },
               {
                   "name": "attr/name"
               },
               {
                   "name": "attr/swversion",
                   "parse": {
                       "fn": "zcl:attr",
                       "ep": 1,
                       "cl": "0x0000",
                       "at": "0x0001",
                       "script": "tuya_swversion.js"
                   },
                   "read": {
                       "fn": "zcl:attr",
                       "ep": 1,
                       "cl": "0x0000",
                       "at": "0x0001"
                   }
               },
               {
                   "name": "attr/type"
               },
               {
                   "name": "attr/uniqueid"
               },
               {
                   "name": "config/offset",
                   "default": 0
               },
               {
                   "name": "config/on"
               },
               {
                   "name": "config/reachable"
               },
               {
                   "name": "state/lastupdated"
               },
               {
                   "name": "state/lightlevel",
                   "parse": {
                       "fn": "tuya",
                       "dpid": 101,
                       "eval": "Item.val = Math.round(10000 * Math.log10(Attr.val) + 1);"
                   },
                   "read": {
                       "fn": "none"
                   },
                   "default": 0
               }
           ]
       },
	   {
		  "type": "$TYPE_BATTERY_SENSOR",
		  "restapi": "/sensors",
		  "uuid": [
			"$address.ext",
			"0x01",
			"0x0001"
		  ],
		  "fingerprint": {
			"profile": "0x0104",
			"device": "0x0402",
			"endpoint": "0x01",
			"in": [
			  "0x0001",
			  "0x0102"
			]
		  },
		  "items": [
			{
			  "name": "attr/manufacturername"
			},
			{
			  "name": "attr/modelid"
			},
			{
			  "name": "attr/name"
			},
			{
			  "name": "attr/swversion",
			  "refresh.interval": 86400,
			  "parse": {
				"fn": "zcl:attr",
				"ep": 1,
				"cl": "0x0000",
				"at": "0x0001",
				"script": "tuya_swversion.js"
			  },
			  "read": {
				"fn": "zcl:attr",
				"ep": 1,
				"cl": "0x0000",
				"at": "0x0001"
			  }
			},
			{
			  "name": "attr/type"
			},
			{
			  "name": "attr/uniqueid"
			},
			{
			  "name": "attr/lastseen"
			},
			{
			  "name": "config/on"
			},
			{
			  "name": "config/reachable"
			},
			{
			  "name": "state/battery",
			  "parse": {
				"cl": "0x0001",
				"at": "0x0021",
				"eval": "Item.val = Attr.val / 2"
			  },
			  "read": {
				"cl": "0x0001",
				"at": "0x0021"
			  },
			  "refresh.interval": 3600
			},
			{
			  "name": "state/lastupdated"
			}
		  ]
	   },
       {
           "type": "$TYPE_HUMIDITY_SENSOR",
           "restapi": "/sensors",
           "uuid": [
               "$address.ext",
               "0x01",
               "0x0405"
           ],
           "items": [
               {
                   "name": "attr/id"
               },
               {
                   "name": "attr/lastannounced"
                },
                {
                    "name": "attr/lastseen"
                },
                {
                    "name": "attr/manufacturername"
                },
                {
                    "name": "attr/modelid"
                },
                {
                    "name": "attr/name"
                },
                {
                    "name": "attr/swversion",
                    "parse": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001",
                        "script": "tuya_swversion.js"
                    },
                    "read": {
                        "fn": "zcl:attr",
                        "ep": 1,
                        "cl": "0x0000",
                        "at": "0x0001"
                    }
                },
                {
                    "name": "attr/type"
                },
                {
                    "name": "attr/uniqueid"
                },
                {
                   "name": "state/humidity",
                   "parse": {
                       "fn": "tuya",
                       "dpid": 105,
                       "eval": "Item.val = Attr.val;"
                   },
                   "read": {
                       "fn": "none"
                   },
                   "default": 0
               }
           ]
       }
   ]
}
'''

![Image](https://github.com/user-attachments/assets/01b54e17-7ce9-4849-a393-965b8037d7ff)

![Image](https://github.com/user-attachments/assets/d3014d64-25d8-4b9b-9df3-43bebb4d5046)

i see it in the Diagnostic Data:

![Image](https://github.com/user-attachments/assets/db28ce0c-eee4-4bc6-a369-ecfa7bff4d56)

i deleted it, restartet Home Assistant completely, readded the device but its still the same

**Comment by Smanar** [comment]
The ZHABattery is used for "light type" device (by defaut this kind of device don't have the "config" field, so not possible to use config/battery).

But your first DDF was fine ? I can see a 93 value for config/battery ?

You can miss a bind report, but for me your first DDF was fine for battery.

```
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 60,
          "max": 3600,
          "change": "0x00000001"
        }
      ]
    },
```

**Comment by Beersteak** [comment]
#8171 i created a pull request, it seems to work now

**Comment by Smanar** [comment]
I have answered on your PR page, I think you have removed too much stuff ^^
