### ISSUE TITLE
Temp. Sensort Humidity Sensor Xiaomi Mi. (flashed from BT to Zigbee)

### ISSUE THREAD

**Issue by Obelixje** [dresden-elektronik/deconz-rest-plugin#7906]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Temp. humidity sensor Mi Zigbee

### Manufacturer

Xiaomi

### Model identifier

LYWSD03MMC-z

### Device type to add

Sensor

### Node info

![image](https://github.com/user-attachments/assets/d89a8fcf-e638-43e3-85d8-d69c3f5576ec)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/d314fe54-72e3-45ba-982d-422b8c91732b)
![image](https://github.com/user-attachments/assets/61f3b279-f29d-4d23-8329-215ab7dad86c)
![image](https://github.com/user-attachments/assets/89859a65-1a64-4a20-9f8f-53a831d3229d)
![image](https://github.com/user-attachments/assets/b7a6ace2-c128-4146-b913-e6103bd42c1e)
![image](https://github.com/user-attachments/assets/77e54244-db75-4782-aa1c-d2897502021d)
![image](https://github.com/user-attachments/assets/7a6c2c32-77cf-4e49-9eab-837a512bfc59)
![image](https://github.com/user-attachments/assets/3e41af7e-653d-4fba-acdd-f950c2e7124f)
![image](https://github.com/user-attachments/assets/1908eb97-1802-4f87-bd36-7e99dbf5b466)

### Basic

![image](https://github.com/user-attachments/assets/8ed2b12d-e5b8-42b8-823b-4f5b4bb6f655)

**Comment by Mimiix** [comment]
@Smanar can you help with a DDF?

**Comment by Smanar** [comment]
It's not a clone of this one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7327 ?
What is the difference with the previous one ? Same DDF can't be used ?

**Comment by Obelixje** [comment]
@Smanar 

Do I need to change anything in that DDF?
Or just upload it to DeConz?

**Comment by caspermet** [comment]
Is it any update on this topic? I have same issue.

**Comment by Smanar** [comment]
Pls try the previous procedure, if it work I can make a PR to add it.

**Comment by caspermet** [comment]
Hello Smanar, 

Sorry I am new to this topic, I have trouble modifying DDF. What is best practice? I tried this tutorial https://www.youtube.com/watch?v=rgTQpOVg8w0 but I wasn't able to edit DDF. 

And I think that LYWSD03MMC and LYWSD03MMC-z are the same models.

**Comment by Smanar** [comment]
>And I think that LYWSD03MMC and LYWSD03MMC-z are the same models

For me too, but need to be sure.

What is you OS ? On normal OS you can just edit the actual file `devices\xiaomi\xiaomi_lywsd03mmc.json` if you have HA or other dockers, you need to create a new DDF in the persistent folder.

**Comment by caspermet** [comment]
I am using HA in Docker, but for a quick test, I plugged the ConBee II stick into my Windows machine. I added xiaomi_lywsd03mmc.json file into devices folder, and after a reboot, it seems that the deCONZ app is now correctly reading data from the thermostat:
![image](https://github.com/user-attachments/assets/b9352cdb-ab7b-4816-b92b-a7ea100dd65e)

But I still don't see the thermostat in my Phoscon App.

**Comment by Smanar** [comment]
Ha yes, the DDF is selected, gold status, all seem fine.

Just one thing, the device was included before or not ? Deconz create entry in the database only if the gateway is in "permit join", so if you have nothing you can need to re-include the device.

**Comment by caspermet** [comment]
Nice! I finaly see my devices in Phoscon app. Thank you verry much! Do you have plans to create a PR to add the LYWSD03MMC-z model?

**Comment by Smanar** [comment]
Done https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7939
Thx for tests.
