### ISSUE TITLE
[Bug] Bosch RFDL-ZB-MS pairing never adds Motion (its a motion sensor!)

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/deconz-rest-plugin#7907]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Deconz never adds the Motion feature to the device. I have a dozen of these sensors and several on Deconz years ago, and they work fine. As of  2020 Deconz stopped properly as a different issue was reported prior...
[Bosch ZigBee Wireless Motion Detector RFDL-ZB-MS](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2289)

Please fix this, PLEASE

### Steps to reproduce the behavior

pair one, happens to all of them.

the only difference I can see between the working and not-working motion sensor is the 'IAS Zone' settings.
Unfortunately, the Deconz UI isnt properly designed to show them on screen at the same time.

working...
<img width="454" alt="image" src="https://github.com/user-attachments/assets/5672fc24-875b-480d-b59a-34d90f2988a8">

not working...
<img width="440" alt="image" src="https://github.com/user-attachments/assets/8eb9f594-04fb-4a79-b2a8-2d7b02dbe297">

Working...

### Expected behavior

Deconz to properly add MOTION feature (with the existing Temperature and Lux - which work fine)

### Screenshots

see how the newly added doesnt show as motion...

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/caebd1a1-9ed1-401b-97c4-7b62a467f150">

some of the nodes...

<img width="233" alt="image" src="https://github.com/user-attachments/assets/e1fc6e0f-8f28-4126-b568-155718fb4632">
<img width="464" alt="image" src="https://github.com/user-attachments/assets/9691f990-dfd8-491e-8a77-b43d7b4eb108">

### Environment
- Host system:  PC
- Running method:  Windows 
- Firmware version: 26510900
- deCONZ version (not Home assistant Addon version!): 2.28.1
- Device: ConBee III   (did same thing with Conbee 1)
- Do you use an USB extension cable:  yes, USB 3.0 certified
- Is there any other USB or serial devices connected to the host system? If so: Which?

### deCONZ Logs

[Deconz_Debug.txt](https://github.com/user-attachments/files/16767803/Deconz_Debug.txt)

**Comment by Mimiix** [comment]
@SwoopX you did some of these right? Can you check In :)?

**Comment by SwoopX** [comment]
I do not see any indication for a bug but rather consider this as an incomplete device support. See also https://forum.phoscon.de/t/pairing-not-enabling-rfdl-zb-ms-motion-sensing-did-before-just-fine/4888

A thoroughly tested DDF and a subsequent PR is highly recommendable.

**Comment by Ltek** [comment]
> I do not see any indication for a bug but rather consider this as an incomplete device support. See also https://forum.phoscon.de/t/pairing-not-enabling-rfdl-zb-ms-motion-sensing-did-before-just-fine/4888
> 
> A thoroughly tested DDF and a subsequent PR is highly recommendable.

If you can help make a DDF I'd love to test it. I'm far from an expert. 
I created a DDF from existing / fully working same-model devices and it does not make the non-working devices show the missing Motion features (temp and lux work fine)

**Comment by SwoopX** [comment]
@Ltek You could take the one mentioned in the forum thread as a start. Deconz should load the missing sensors in the DDF from database nevertheless, as I recently learned. If the motion detection part works (again), we can put the pieces together jointly.

**Comment by Ltek** [comment]
> @Ltek You could take the one mentioned in the forum thread as a start. Deconz should load the missing sensors in the DDF from database nevertheless, as I recently learned. If the motion detection part works (again), we can put the pieces together jointly.

working on it on/off... its just not working properly like it did 2 yrs ago or so. Z2M has it working correctly so I suspect Deconz should be able to
