### ISSUE TITLE
Lidl LIVARNO home windows blinds (tuya) new chip

### ISSUE THREAD

**Issue by Smibser** [dresden-elektronik/deconz-rest-plugin#7912]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

LIVARNO home Automatik-Verdunkelungsrollo, »Zigbee Smart Home«

### Manufacturer

_TZB000_yqjaollc

### Model identifier

TS030F

### Device type to add

Other

### Node info

<img width="523" alt="Bildschirmfoto 2024-09-04 um 20 30 42" src="https://github.com/user-attachments/assets/34ca57e2-d572-4eb5-8589-f4eb5a9cf467">

### Endpoints and clusters

<img width="279" alt="Bildschirmfoto 2024-09-04 um 20 35 57" src="https://github.com/user-attachments/assets/ac0ebc21-b352-4fd2-9ac1-cccaac9ea86d">

### Basic

<img width="523" alt="basic cluster 1" src="https://github.com/user-attachments/assets/a8f3eda2-8f3d-4a06-9409-ebe916e89720">
<img width="523" alt="basic cluster 2" src="https://github.com/user-attachments/assets/f69bce6a-fdd7-4e95-9e69-46873a1c6b32">

### Groups
<img width="722" alt="groups 1" src="https://github.com/user-attachments/assets/7a44f67a-9f84-40a9-b7a9-b09e19223c1f">
<img width="722" alt="groups 2" src="https://github.com/user-attachments/assets/cb62f160-4574-46ae-89f6-c39ec161c212">

### Scenes
<img width="722" alt="scenes 1" src="https://github.com/user-attachments/assets/6278b9eb-2400-4732-b1a0-3e0e285c6e40">
<img width="722" alt="scenes 2" src="https://github.com/user-attachments/assets/4d573acf-bcb4-4e8e-8928-6126d1ce5304">
<img width="722" alt="scenes 3" src="https://github.com/user-attachments/assets/dcf53235-63ba-48f5-a73c-235006afa45b">
<img width="722" alt="scenes 4" src="https://github.com/user-attachments/assets/14609f84-298d-40b6-8cd9-87588997301c">

### OTAU
<img width="722" alt="otau 1" src="https://github.com/user-attachments/assets/53f4ca0b-b05d-4457-8667-bbe21badd1f1">
<img width="722" alt="otau 2" src="https://github.com/user-attachments/assets/be529263-89f6-4c77-bbb7-93e7b87d59f6">

### Windows Covering
<img width="722" alt="wc1" src="https://github.com/user-attachments/assets/cb5ece0b-610d-4ff2-8399-6427d0f675fb">
<img width="722" alt="wc2" src="https://github.com/user-attachments/assets/6208cdf4-7765-4dd0-8e02-1db7f5fdce5a">
<img width="722" alt="wc3" src="https://github.com/user-attachments/assets/412186a2-68dd-4785-9f24-ccb66b9394d9">
<img width="722" alt="wc4" src="https://github.com/user-attachments/assets/e226a809-06cc-4842-b4af-4b5d63df40e6">
<img width="722" alt="wc5" src="https://github.com/user-attachments/assets/86438aea-2659-4571-806d-f7d843832f99">
<img width="722" alt="wc6" src="https://github.com/user-attachments/assets/29beeb5c-282d-45d6-97a5-d81100e6ce7c">

### Power Configuration
<img width="516" alt="Bildschirmfoto 2024-09-04 um 20 38 15" src="https://github.com/user-attachments/assets/d9466bbd-1e4f-48a2-86b2-3f69fb0e43bb">

**Comment by Smibser** [comment]
There was already a device request for this device in [this PR](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7325)
Unfortunately they changed the chip as I found out in [this forum post](https://forum.phoscon.de/t/cant-pair-with-livarno-home-window-covering-device/5099)

**Comment by Smanar** [comment]
Can try to add it on the DDF


```
{
  "schema": "devcap1.schema.json",
  "manufacturername": ["_TZB000_42ha4rsc", "_TZB000_yqjaollc"],
  "modelid": ["TS030F", "TS030F"],
  "vendor": "Livarno",
  "product": "Window blinds (TS030F)",
  "sleeper": true,
  "status": "Gold",
  "subdevices": [
    {
      "type": "$TYPE_WINDOW_COVERING_DEVICE",
      "restapi": "/lights",
      "uuid": [
        "$address.ext",
        "0x01"
      ],
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "state/lift"
        },
        {
          "name": "state/open"
        },
        {
          "name": "state/reachable"
        }
      ]
    },
    {
      "type": "$TYPE_BATTERY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0x0001"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0402",
        "endpoint": "0x01",
        "in": [
          "0x0001",
          "0x0102"
        ]
      },
      "items": [
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion",
          "refresh.interval": 86400,
          "parse": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001", "script": "tuya_swversion.js"},
          "read": {"fn": "zcl:attr", "ep": 1, "cl": "0x0000", "at": "0x0001"}
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/battery",
          "parse": {
            "cl": "0x0001",
            "at": "0x0021",
            "eval": "Item.val = Attr.val / 2"
          },
          "read": {
            "cl": "0x0001",
            "at": "0x0021"
          },
          "refresh.interval": 3600
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ],
  "bindings": [
    {
      "bind": "unicast",
      "src.ep": 1,
      "dst.ep": 1,
      "cl": "0x0102",
      "report": [
        {
          "at": "0x0008",
          "dt": "0x20",
          "min": 1,
          "max": 300,
          "change": "0x00000001"
        }
      ]
    },
    {
      "bind": "unicast",
      "src.ep": 1,
      "cl": "0x0001",
      "report": [
        {
          "at": "0x0021",
          "dt": "0x20",
          "min": 300,
          "max": 600,
          "change": "0x01"
        }
      ]
    }
  ]
}
```

Can create a new one or edit the old one for test.

**Comment by Smibser** [comment]
@Smanar sorry for the late response, I didn't get a notification.
When I try to open the DFF it says `Failed to open /home/pi/.local/share/dresden-elektronik/deCONZ/devices/ts030f.json`
Maybe I am doing something wrong. I did that:
1. Right click on the device and click 'Edit DFF'
2. File -> Save and saved it to the devices folder
3. I edit the created json file with your json. Compressed without line breaks
4. I open 'Edit DFF' again and try to File -> Open

**Comment by Smanar** [comment]
Better to avoid the editor.
Just create a new file, or edit the existing one `devices\tuya\_TZB000_42ha4rsc_window_blinds.json`

Then restart deconz, deconz load DDF only at start.
Then re-include the device.

**Comment by Smibser** [comment]
Thanks for the help. It works perfectly

**Comment by Smanar** [comment]
Nice, thx for return, have added the device here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/7919
