### ISSUE TITLE
Royal Gardineer NX-6476-919  Water Valve with Plug as Gateway

### ISSUE THREAD

**Issue by cartman10** [dresden-elektronik/deconz-rest-plugin#7917]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Royal Gardineer NX-6476-919

### Manufacturer

dresden elektronik

### Model identifier

ConBee ll

### Device type to add

Other

### Node info

![image](https://github.com/user-attachments/assets/7626533c-cdaa-4d68-858e-8166d5b4d5c0)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/88ff9ad4-114a-4b5c-a6ab-f662c175ee67)

### Basic

![image](https://github.com/user-attachments/assets/2a88c4bf-e6aa-4d24-a8c1-02aa9d3dc456)

### On/Off
![image](https://github.com/user-attachments/assets/23cd67c7-02f3-4848-8810-3f12b5cd5be8)
![image](https://github.com/user-attachments/assets/df69b105-30e1-433c-9007-e2eda7fd43b5)

**Comment by Mimiix** [comment]
Hi, 

This is the Conbee stick, not your device.

Please provide the device clusters

**Comment by cartman10** [comment]
Hi, obviouslsly the deivce didn't pair...  how do I pair it?

**Comment by Mimiix** [comment]
Just like you would with other devices. It should show up in deconz with a hex name and then you can make the correct screens.

**Comment by cartman10** [comment]
not a zigbee device
