### ISSUE TITLE
Smartenit ZBMLC30 ??

### ISSUE THREAD

**Issue by dem5867** [dresden-elektronik/deconz-rest-plugin#792]
What information would I need to get to you so you can add this device.. It presently shows up as a light {I'm a NOOB so it maybe just installed incorrectly } and it does switch on and off , but I beleave it can also supply power readings... Thank You.

**Comment by manup** [comment]
Best information are provided by screenshots from the node endpoints and *Cluster Info Panel* of basic cluster after reading its attributes.

Also Screenshot of *Node Info Panel*.

**Comment by dem5867** [comment]
Is the endpoint the data under the word dryer ?
![dryer 1](https://user-images.githubusercontent.com/22582221/45778700-53c58480-bc27-11e8-8e08-84726d7eb8fd.PNG)
![dryer 2](https://user-images.githubusercontent.com/22582221/45778744-6e97f900-bc27-11e8-94a5-171e2aa48b3e.PNG)
![dryer 3](https://user-images.githubusercontent.com/22582221/45778781-82435f80-bc27-11e8-9287-0ac3220bb33d.PNG)
I don't think the following EndPoint information is correct , how do I get the correct endpoint information ??
![dryer 4](https://user-images.githubusercontent.com/22582221/45778892-c0408380-bc27-11e8-95a1-08f2cda057fb.PNG)

**Comment by dem5867** [comment]
I don't know if this helps , yet could it be I did not add it correctly. I just held the button until it was blinking and it got added as the device above ,, yet it appears one has to join and bind the device... see below..
![dryer 5](https://user-images.githubusercontent.com/22582221/45780735-2f1fdb80-bc2c-11e8-8056-d0a5cc6552db.JPG)

**Comment by manup** [comment]
Thanks for the details, with the above screenshots we can add the power readings via Simple Metering cluster or at least start to whitelist them.

**Comment by ebaauw** [comment]
The _Simple Metering_ cluster usually only reports life-time consumption (kWh), and sometimes current power (W).  Try reading the cluster in the deCONZ GUI: _Current Summation Delivered_ (0x0000) is the life-time consumption; _Instanteneous demand_ (0x0400) the current power.  The scales typically differs per device, and only a few devices support the formatting attributes.

For voltage (V), current (A), and sometimes frequency (Hz), you'd need a _Electrical Measurement_ cluster (0x0B04).  This cluster also contains power (W).
