### ISSUE TITLE
JUNG ZLLLS5004M paired as "Device", instead of "WS_4f_J_1", resurrected Bug?

### ISSUE THREAD

**Issue by berhomeauto** [dresden-elektronik/deconz-rest-plugin#7928]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [x] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I have an identical issue that should have been fixed in #5880. 
There is a problem, when pairing a wall scene switch from JUNG type ZLLLS5004M.

When using the latest 2.28.1 the switch will be paired as "Remote" instead of "WS_4f_J_1"
The "Remote"-device has only one button, while the correct "WS_4f_J_1" has 8 buttons. So i can not map the different buttons to different actions, because there ist only on button showing up.

working, but very ugly workaround:
- downgrade to 2.23.01
- LLLS5004M
- and upgrade to latest version again.

please check and fix it. thanks.

### Steps to reproduce the behavior

pair a ZLLLS5004M in latest deconz Version

### Expected behavior

pair ZLLLS5004M like in 2.23.01 with the correct icon, the right descriptions and features

### Screenshots

upper device was paired with latest version
lower Device was paired with 2.23.01
![image](https://github.com/user-attachments/assets/a5a0cb7b-0222-41d6-a4fb-db8994880430)

![image](https://github.com/user-attachments/assets/fbc01b5e-b6d4-42fd-9357-e27566082390)
![image](https://github.com/user-attachments/assets/82c00ffc-4445-4ca9-8d2a-c52ef56675f9)

### Environment

- Host system: PC 
- Running method: Ubuntu, running in Docker Container
- Firmware version: (26720700)
- deCONZ version latest 2.28.1
- Device: (ConBee II)
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? yes, many? IMHO not relevant in this case.

### deCONZ Logs

please ask for specific logs

### Additional context

Switches:
6 x Insta WS_4f_J_1
4 x dresden elektronik Scene Switch
7 x lumi.remote.b686opcn01 Switch

Lights:
3 x dresden elektronik FLS-CT
1 x Philips LWB010
2 x innr RB 248 T
2 x GLEDOPTO GL-C-008P
7 x GLEDOPTO GL-C-006P

Sensors:
1 x TRADFRI motion sensor
5 x lumi.sensor_magnet.aq2
3 x lumi.weather
1 x lumi.sen_ill.agl01

**Comment by SwoopX** [comment]
I'm sorry, but there's no sign of any bug whatsoever right now in the REST API. Names are just names and how a devices is exposed in Phoscon is not handled around here. Best raise a topic in the forum.

Closing for now.
