### ISSUE TITLE
firmware 0x26240500?

### ISSUE THREAD

**Issue by vandalon** [dresden-elektronik/deconz-rest-plugin#793]
I see 0x26240500 on http://dresden-elektronik.de/rpi/deconz-firmware/, is there a changelog somewhere? and is it advisable to install this one?

**Comment by manup** [comment]
Not yet, it will be part of the next release with more details in the changelog.

In combination with next deCONZ version > 2.05.38 it fix some really nasty issues with end-devices and
non sleeping end-devices where rxOnWhenIdle = 1.

**Comment by vandalon** [comment]
Can I already install it with 2.05.38 via GCFFlasher_internal?

**Comment by manup** [comment]
Yes but only next version will fully use the modifications.

**Comment by manup** [comment]
Should be ready in the next 2–3 days, need to iron out two more bugs :)

**Comment by vandalon** [comment]
I might wait a few day then. You are doing awesome work, thanks!

**Comment by MattL0** [comment]
Did update to latest firwame with latest headlest minimal deconz .

What is the difference vs before?

**Comment by manup** [comment]
Have a look in the release notes: https://github.com/dresden-elektronik/deconz-rest-plugin/releases
