### ISSUE TITLE
Device support request: Orvibo in-wall dimmer switch

### ISSUE THREAD

**Issue by udoewich** [dresden-elektronik/deconz-rest-plugin#794]
I took a chance and bought an Orvibo in-wall Zigbee dimmer switch (US version; box says model# T10D1) from a local reseller to see if I could get it to work with Phoscon.  Alas, it does not show up with either a light or sensor scan.  It did however pair with my Conbee and shows up in deCONZ.  Here's the info:

![image](https://user-images.githubusercontent.com/5656393/45913028-42cc6d00-bdf9-11e8-9c33-3490c5ebbb7d.png)

Basic Cluster Info:

![orvibo-deconz-02](https://user-images.githubusercontent.com/5656393/45913030-52e44c80-bdf9-11e8-984f-4d36b297d720.png)

Basic Node Info:

![orvibo-deconz-03](https://user-images.githubusercontent.com/5656393/45913037-6d1e2a80-bdf9-11e8-8db0-16862757b078.png)

Would love to see this added as a light (or switch?) in Phoscon.  I was already able to turn the connected lights on, off and dim them via deConz.

**Comment by manup** [comment]
Link to the Orvibo product line https://www.orvibo.com/en/product/productList.html

**Comment by udoewich** [comment]
I wasn't sure if off-site links are allowed on GitHub, but yes, that's the manufacturers web site.  I'm holding off on getting more of their switches until I know I can control them via Phoscon.  I also have my eye on their simple on/off in-wall switch.

Is there a limit of how many such devices can be controlled by a Conbee?

**Comment by manup** [comment]
>Is there a limit of how many such devices can be controlled by a Conbee?

Officially we say 200 but there isn't really a hard limit, depends on the setup so more might be possible.

**Comment by udoewich** [comment]
Does it make sense for me to upgrade to 2.05.49, or is there no support for this device yet?  I'm still holding off buying more of these switches until I know I can remote control them via Phoscon...

Thanks in advance.
