### ISSUE TITLE
There is a new version (_TZ3000_imaccztn) or just different naming available in Ali Express, having similar issue, can it be also fixed for that?

### ISSUE THREAD

**Issue by thetornado76** [dresden-elektronik/deconz-rest-plugin#7945]
There is a new version (_TZ3000_imaccztn) or just different naming available in Ali Express, having similar issue, can it be also fixed for that?

Please see https://forum.phoscon.de/t/zigbee-4-channel-smart-relay-switch-tz3000-wkr3jqmr-only-switching-first-relay/3934

Thank you

_Originally posted by @FhemiR in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7211#issuecomment-1870989208_

**Comment by Mimiix** [comment]
As the template is not followed, I'm closing this.

Please create a device request :)
