### ISSUE TITLE
Conbee 1 : no links visible anymore (gui issue?)

### ISSUE THREAD

**Issue by pergolafabio** [dresden-elektronik/deconz-rest-plugin#7953]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hi, i'm using HA, and i"m quite sure in the past i saw connections lines, i wanted to add a new device today, and i dont see any lines/links anymore? where are they? i saw before all green lines, its all still working, just not visible
I already played with the LQI display to set to 0 , but  that doesnt help?

### Steps to reproduce the behavior

No steps here

### Expected behavior

.

### Screenshots

![image](https://github.com/user-attachments/assets/40370307-a081-4b20-a2e8-4eed6b48064c)

### Environment

- Host system: PC
- Running method: Home Assistent deCONZ Add-on
- Firmware version: 26400500
- deCONZ version (not Home assistant Addon version!): 2.28.1
- Device: ConBee I
- Do you use an USB extension cable: yes

**Comment by Mimiix** [comment]
Hi,

As this is not an issue as described in #5113 I am closing this issue.

Please open a topic on the forums.

Kind regards,
Dennis
