### ISSUE TITLE
Battery only with _TZE200_zah67ekd TS0601 BLINDS MOTOR AM43

### ISSUE THREAD

**Issue by YannSchuhler** [dresden-elektronik/deconz-rest-plugin#7958]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I try to add the Blinds Motor AM43-0.45/40-ES-EZ(TY) ZIGBEE TUYA in DECONZ on JEEDOM. After appair, i've a battery equipment. I try to connect the ConBee2 on windows, and i made a single desciption. now i've in deconz windows, a smart plug. I try to reconnect sur usb key in jeedom, but i don't have a smart plug, only a battery without command. 

On the deconz win app i've this : 
`{
  "schema": "devcap1.schema.json",
  "manufacturername": "_TZE200_zah67ekd",
  "modelid": "TS0601",
  "product": "TS0601",
  "sleeper": false,
  "status": "Draft",
  "subdevices": [
    {
      "type": "$TYPE_BATTERY_SENSOR",
      "restapi": "/sensors",
      "uuid": [
        "$address.ext",
        "0x01",
        "0xef00"
      ],
      "fingerprint": {
        "profile": "0x0104",
        "device": "0x0051",
        "endpoint": "0x01",
        "in": [
          "0x0000",
          "0xEF00"
        ]
      },
      "items": [
        {
          "name": "attr/id"
        },
        {
          "name": "attr/lastannounced"
        },
        {
          "name": "attr/lastseen"
        },
        {
          "name": "attr/manufacturername"
        },
        {
          "name": "attr/mode",
          "description": "Operational mode.",
          "default": 1
        },
        {
          "name": "attr/modelid"
        },
        {
          "name": "attr/name"
        },
        {
          "name": "attr/swversion"
        },
        {
          "name": "attr/type"
        },
        {
          "name": "attr/uniqueid"
        },
        {
          "name": "config/on"
        },
        {
          "name": "config/reachable"
        },
        {
          "name": "state/battery",
          "description": "The current device battery level in range 0&ndash;100&nbsp;%.",
          "refresh.interval": 3600
        },
        {
          "name": "state/lastupdated"
        }
      ]
    }
  ]
}`

### Steps to reproduce the behavior

Add and appair the blin motor with de deconz windows app and conbee 2 key.

### Expected behavior

Adding a curtain to open or close the curtain.

### Screenshots

![2d6823140522acb55102607016cc7b48083e391f_2_375x500](https://github.com/user-attachments/assets/9a4f0cb7-167c-4b0b-9d9d-2ae5426226b9)
![585a923b5e212c59f2f84e8fbf5cc09c8226239c_2_666x500](https://github.com/user-attachments/assets/dbc4d886-ad94-4b24-8fb7-c2d432fdc352)
![c62cdbd2283fd3df0e7d685ea75d2df34c9f3466](https://github.com/user-attachments/assets/25266230-a1f1-42db-89fb-9a3bee461550)
![ea05bba098b3394cd0564f9c7d74041c2d5a3573](https://github.com/user-attachments/assets/28bc977a-2cc4-4a4c-89a6-2064ffa76db3)

### Environment

- Deconz Windows and Deconz on JEEDOM
- JEEDOM DIY on LINUX Debian (Core 4.4.18)
- Firmware version: 26780700
- deCONZ version (not Home assistant Addon version!): 2.28.1
- Device: ( ConBee II )
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? If so: Zwave key + RFX Com Usb

### deCONZ Logs

LOG ON JEEDOM : 
[LOG_JEEDOM.txt](https://github.com/user-attachments/files/17269986/LOG_JEEDOM.txt)

**Comment by Smanar** [comment]
Hello, as you have the GUI.
- Remove your device using deconz
- Select Basic Cluster "0x0000"
- Ask for attributes, at least Manufacture name / Model ID.
- When value are filled, set Phoscon in permit join
- Return on deconz, right clic on node, use Request 1 7 8 (it's keyboard shortcut)
- With luck it will trigger the inclusion.
