### ISSUE TITLE
Philips Hue Lightguide E27 Edison ST72

### ISSUE THREAD

**Issue by pimw1** [dresden-elektronik/deconz-rest-plugin#7969]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Philips Hue Lightguide E27 Edison ST72

### Manufacturer

Signify Netherlands B.V.

### Model identifier

LCV001

### Device type to add

Light

### Node info

![image](https://github.com/user-attachments/assets/9721bc53-7226-4c00-9dd5-4c478b81da8c)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/8b99cef0-1d7a-402a-a18f-4c9c737d2e9c)

### Basic

![image](https://github.com/user-attachments/assets/a6c4b45b-b2aa-47d3-b72c-f970c7a612d5)
![image](https://github.com/user-attachments/assets/9fca9de5-1367-46ed-bf48-eec4b8994543)
![image](https://github.com/user-attachments/assets/be670cf7-5ab5-483d-a964-51fbf83fc1fb)
![image](https://github.com/user-attachments/assets/1a70a601-73a9-4a34-98aa-b4886dfe5437)
![image](https://github.com/user-attachments/assets/de9f7f1f-3670-4949-ad1f-feb8ef845744)

### On/Off
![image](https://github.com/user-attachments/assets/0193a8cc-fbce-4f85-ac33-564c0cea7275)
![image](https://github.com/user-attachments/assets/7784cb14-44c7-4602-9514-f68de8d8c605)
![image](https://github.com/user-attachments/assets/3890f0ba-a3e1-48fa-9593-b660b2d41c93)

### Level Control
![image](https://github.com/user-attachments/assets/c56d6921-4268-4113-a00c-930f180898e0)
![image](https://github.com/user-attachments/assets/27e680a8-339d-4df8-920b-3663bd5e6a30)
![image](https://github.com/user-attachments/assets/41434b68-84eb-425b-99b5-616540ab2787)

### Color Control
![image](https://github.com/user-attachments/assets/68645542-59b4-4407-9f5c-7a7b54561273)
![image](https://github.com/user-attachments/assets/66956666-3ac6-4b43-98c8-9b788ede7aa3)
![image](https://github.com/user-attachments/assets/048323ff-9312-4bcf-8561-7a4a2c9566bf)
![image](https://github.com/user-attachments/assets/3c4bdae3-d407-4769-b222-fecc05d1170a)
![image](https://github.com/user-attachments/assets/b4f3aaa2-8cc8-4c7b-9fe0-63263dde3754)
![image](https://github.com/user-attachments/assets/f78da437-3058-4732-9c61-a9a47b76a32a)
![image](https://github.com/user-attachments/assets/1282b31d-7e5e-43bf-9f1b-3fa693b4cf57)
![image](https://github.com/user-attachments/assets/18812d00-b40c-4b8a-b438-76200d3cb412)
![image](https://github.com/user-attachments/assets/7247093c-e2fa-4ac9-9aa6-2b33920615a2)
![image](https://github.com/user-attachments/assets/556c95f6-a8cc-4cdd-8860-fb75a65b8ee6)
![image](https://github.com/user-attachments/assets/b9862771-b40a-44e3-8dd1-e227f62b95ea)

### Thermostat
NA

### Simple Metering
NA

### Electrical Measurement
NA

### Any other cluster of relevance/interest
Identify
![image](https://github.com/user-attachments/assets/97176c2d-8c16-4905-ba51-1aaf4c1d4b64)

Groups
![image](https://github.com/user-attachments/assets/b7144843-8eb3-4670-9d04-f51994f5ba34)
![image](https://github.com/user-attachments/assets/40fc9251-d4dd-4741-b4dc-4b34d03fbe0f)

Scenes
![image](https://github.com/user-attachments/assets/8f8ae797-80e1-426b-975c-0f40fc8886a0)
![image](https://github.com/user-attachments/assets/46833acc-b80b-4ad1-a341-be8678b07102)
![image](https://github.com/user-attachments/assets/a862c2c1-899d-4784-a986-a4c84c766e51)
![image](https://github.com/user-attachments/assets/d0ad395f-4f12-4964-b856-c96a7a6efe01)

Touchlink
![image](https://github.com/user-attachments/assets/8cb78963-20e7-455a-bec3-80e8b48ad760)
![image](https://github.com/user-attachments/assets/65729415-5a20-41e6-b46c-9faef8f6477c)

Hue Effects
![image](https://github.com/user-attachments/assets/e263a4fd-5879-4cb5-84cf-8e5b46fa9691)

Hue Entertainment
![image](https://github.com/user-attachments/assets/8144d224-849d-402e-b114-edcabea67b44)

Hue Unknown
![image](https://github.com/user-attachments/assets/88550ba5-965b-44c7-bf0b-ade0b0d9cfae)

OTAU
![image](https://github.com/user-attachments/assets/49826903-3148-4661-8eaa-659af9b24a6f)
![image](https://github.com/user-attachments/assets/c4eaba7c-928e-471d-9d26-fecd982e9bb4)

Green Power
![image](https://github.com/user-attachments/assets/581cb410-0a2e-42fa-bb23-01ae1d22efb3)

**Comment by pimw1** [comment]
No DDF available yet

**Comment by ebaauw** [comment]
Also for this one: what’s the _Image Type_?  And you might want to upgrade it’s firmware; I expect it will support more special effects with newer firmware.

**Comment by pimw1** [comment]
Image type is 0x0000
![image](https://github.com/user-attachments/assets/b85c204c-ddeb-4829-9cf1-8f2bb6a07e6f)

I'll update the firmware in a bit via bluetooth and send the new printscreens

**Comment by ebaauw** [comment]
0x0114 is a familiar one.  I'll add this model to `light_zb3_C.json`.

**Comment by pimw1** [comment]
Great, thanks! This is the new info after updating to firmware 1.122.2

Basic
![image](https://github.com/user-attachments/assets/1b827669-d29a-4b2d-b108-905ea8b57188)
![image](https://github.com/user-attachments/assets/e4ae3ed1-2b05-4b98-a94a-7953d79e1942)
![image](https://github.com/user-attachments/assets/7972052a-014b-4a75-be36-d8405c26c227)
![image](https://github.com/user-attachments/assets/815a0313-428b-4355-a5d9-ca87420cfb1a)

Hue Effects
![image](https://github.com/user-attachments/assets/e4cad984-5eea-4a5b-8e94-29ae3a307442)

**Comment by pimw1** [comment]
I've tested the light_zb3_C.json with the Lightguide, most features seems to be working, but one is not working: the option to set brightness/color of the light while off.

![image](https://github.com/user-attachments/assets/1f283f0b-0152-4715-975b-cc32f6d20a99)

`pydeconz.errors.pydeconzException: {'address': '/lights/18/state/bri', 'description': 'parameter, bri, is not modifiable. Device is set to off.', 'type': 201}`

**Comment by ebaauw** [comment]
Did you set `config/bri/execute_if_off` and `config/color/execute_if_off`?

**Comment by pimw1** [comment]
Whoops, i did not set that (i totally forgot about it). It works as expected now.
