### ISSUE TITLE
Philips Hue Play Lightbar (LCT024)

### ISSUE THREAD

**Issue by bluemoehre** [dresden-elektronik/deconz-rest-plugin#7996]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

Hue Play Lightbar

### Manufacturer

Philips

### Model identifier

LCT024

### Device type to add

Light

### Node info

![Screenshot 2024-10-26 203845](https://github.com/user-attachments/assets/bfda7e21-4dab-4797-89d6-3714f0a52160)

### Endpoints and clusters

<img width="250" alt="image" src="https://github.com/user-attachments/assets/0e57bad7-8ed1-4f8a-b661-332e3179d11d">

### Basic

<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 22 25" src="https://github.com/user-attachments/assets/097defe0-39dd-4d93-a0f9-fbc8d8f1494f">
<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 22 39" src="https://github.com/user-attachments/assets/5b7d514b-9a9c-4842-a0ad-e477261dfae7">

### On/Off

<img width="332" alt="image" src="https://github.com/user-attachments/assets/6ca82463-550b-49a6-9aa7-5c8f0f8cbb29">

### Level Control

<img width="335" alt="image" src="https://github.com/user-attachments/assets/95aa9be0-e630-4355-8e07-08891c8c6cf6">
<img width="337" alt="image" src="https://github.com/user-attachments/assets/8f7f480f-b24b-4284-b646-2409350876b6">

### Color Control

<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 25 30" src="https://github.com/user-attachments/assets/6d9fc7ba-5334-4a18-b79d-77b0754e440b">
<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 25 40" src="https://github.com/user-attachments/assets/980984b1-d992-40d5-8b1d-8f28bb7f8c6c">
<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 25 48" src="https://github.com/user-attachments/assets/311b073c-97a7-4237-bdc8-c3c8eaaa351b">
<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 26 35" src="https://github.com/user-attachments/assets/ec2381dc-f067-4cd7-aaf6-22412d1e6602">
<img width="335" alt="Bildschirmfoto 2024-10-27 um 23 26 45" src="https://github.com/user-attachments/assets/419f921e-4ef1-4bcd-8f46-dfc91217ae81">

### HUE Entertainment

<img width="350" alt="Bildschirmfoto 2024-10-27 um 23 28 50" src="https://github.com/user-attachments/assets/760abb19-6a43-49c2-bad4-5bce2a038390">

### HUE Effects

<img width="350" alt="Bildschirmfoto 2024-10-27 um 23 29 09" src="https://github.com/user-attachments/assets/7890a554-1b46-4c74-99c8-5a355a072ed6">

**Comment by ebaauw** [comment]
You didn’t post the _Basic_ cluster, but given that it doesn’t carry the FC03 cluster, this light also has old firmware.  Also here: what’s the _Image Type_?

**Comment by bluemoehre** [comment]
> You didn’t post the Basic cluster […]

Copy-paste error … I updated the description.

> This light also has old firmware

Have you seen a newer image somewhere? Since this device is without BT I would need an OTA file. The current version is the latest I find.

**Comment by ebaauw** [comment]
Try https://firmware.meethue.com/v1/checkUpdate?version=16783620&deviceTypeId=100b-11e

**Comment by bluemoehre** [comment]
Looks to me the image types do not match. Anyhow I added the file, but the device does not update.

**Comment by ebaauw** [comment]
My bad.  It's `0x010e`, not `0x011e`.  And that _Image Type_ isn't listed on firmware.meethue.com (confirming the assumption that the site is used for BLE updates only).  There is a version ``0x01002600` listed on https://github.com/Koenkk/zigbee-OTA:
https://github.com/Koenkk/zigbee-OTA/blob/c1c4488759b9ef68f7d0bc8c649ca8f306f4478b/index.json#L187-195

**Comment by bluemoehre** [comment]
> There is a version 0x01002600

Many thanks - gonna update screenshots when update is done

> And that Image Type isn't listed on firmware.meethue.com (confirming the assumption that that site is used for BLE updates only).

Is it like that? Always thought its related to _when_ a device was manufactured - all the "original" Philips are on the old server and all the new Signify ones are at the new server.

**Comment by bluemoehre** [comment]
@ebaauw I updated the screenshots

**Comment by ebaauw** [comment]
Thanks.  This is a ZLL light, so I think it can be added to `light_zll_C.json`.

**Comment by bluemoehre** [comment]
@ebaauw I did some research and it looks like there are various generations of those lights. Some don't support effects at all (like this one), some only a few, and the most recent generation (see my other device request) from 2021 supports all.

As these differences between generations also affect some other models - how do we reflect this in the DDF? Is this why we have *A, *B, *C files?

**Comment by ebaauw** [comment]
The light reports what effects it supports, so no need to differentiate for that in the DDFs.  ZLL lights do offer fewer features than ZB3 lights (notably attribute reporting), so they do need different DDFs.  Gamut A vs B vs C indicate what colours the light support (or rather what RGB LEDs it contains).  While this is reported by the light as well, there’s differences in other features (like no `ct` for gamut A) that do require different DDFs.
