### ISSUE TITLE
TUYA dimmer switch in wrong section of Phoscon app

### ISSUE THREAD

**Issue by SvenMartin81** [dresden-elektronik/deconz-rest-plugin#7998]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Hi,
i have bought 2 of the TUYA "_TZE200_e3oitdyu" - Product "TS0601" in the version 1.0.4. This unit is a dimmer-switch.

After connecting to my rasbeeII-system I saw in the Phoscon app that the devices are directed into the "plug area" and not "light area". It is not a big thing as I am working with HomeAssistant but it should be sorted correctly.

Please let me know.

### Steps to reproduce the behavior

Hi,
i have bought 2 of the TUYA "_TZE200_e3oitdyu" - Product "TS0601" in the version 1.0.4. This unit is a dimmer-switch.

After connecting to my rasbeeII-system I saw in the Phoscon app that the devices are directed into the "plug area" and not "light area". It is not a big thing as I am working with HomeAssistant but it should be sorted correctly.

Please let me know.

### Expected behavior

Hi,
i have bought 2 of the TUYA "_TZE200_e3oitdyu" - Product "TS0601" in the version 1.0.4. This unit is a dimmer-switch.

After connecting to my rasbeeII-system I saw in the Phoscon app that the devices are directed into the "plug area" and not "light area". It is not a big thing as I am working with HomeAssistant but it should be sorted correctly.

Please let me know.

### Screenshots

![Screenshot 2024-10-26 234312](https://github.com/user-attachments/assets/5decf62a-54b6-459a-b19f-1ba48158167a)

### Environment

Hi,
i have bought 2 of the TUYA "_TZE200_e3oitdyu" - Product "TS0601" in the version 1.0.4. This unit is a dimmer-switch.

After connecting to my rasbeeII-system I saw in the Phoscon app that the devices are directed into the "plug area" and not "light area". It is not a big thing as I am working with HomeAssistant but it should be sorted correctly.

Please let me know.

### deCONZ Logs

Hi,
i have bought 2 of the TUYA "_TZE200_e3oitdyu" - Product "TS0601" in the version 1.0.4. This unit is a dimmer-switch.

After connecting to my rasbeeII-system I saw in the Phoscon app that the devices are directed into the "plug area" and not "light area". It is not a big thing as I am working with HomeAssistant but it should be sorted correctly.

Please let me know.

### Additional context

Hi,
i have bought 2 of the TUYA "_TZE200_e3oitdyu" - Product "TS0601" in the version 1.0.4. This unit is a dimmer-switch.

After connecting to my rasbeeII-system I saw in the Phoscon app that the devices are directed into the "plug area" and not "light area". It is not a big thing as I am working with HomeAssistant but it should be sorted correctly.

Please let me know.

**Comment by Mimiix** [comment]
Hi, 

This is either a missing device support or a issue in phoscon.  For the latter, you need to open a forum post.
