### ISSUE TITLE
Tuya TS0207 Range Extender Clone

### ISSUE THREAD

**Issue by johol** [dresden-elektronik/deconz-rest-plugin#8008]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Tuya TS0207 Range Extender Clone is not recognized.

### Steps to reproduce the behavior

Power the usb stick 3 times to connect to the zigbee network

### Expected behavior

Range Extender will connect

### Environment

- Host system: Raspberry Pi
- Running method: Raspbian

### Additional context

I had to do a small change to the _TZ3000__TS0207_range_extender.json file

`diff -au _TZ3000__TS0207_range_extender.json.orig _TZ3000__TS0207_range_extender.json
--- _TZ3000__TS0207_range_extender.json.orig    2024-11-01 14:14:06.193262355 +0100
+++ _TZ3000__TS0207_range_extender.json 2024-11-01 14:37:37.035288409 +0100
@@ -1,8 +1,8 @@
 {
   "schema": "devcap1.schema.json",
   "uuid": "9d273448-b13a-41a8-9dfe-1e1de9927214",
-  "manufacturername": ["_TZ3000_m0vaazab","_TZ3000_ufttklsz","_TZ3000_5k5vh43t","_TZ3000_gszjt2xx"],
-  "modelid": ["TS0207","TS0207","TS0207","TS0207"],
+  "manufacturername": ["_TZ3000_m0vaazab","_TZ3000_ufttklsz","_TZ3000_5k5vh43t","_TZ3000_gszjt2xx","_TZ3000_nlsszmzl"],
+  "modelid": ["TS0207","TS0207","TS0207","TS0207","TS0207"],
   "vendor": "Tuya",
   "product": "Range Extender (TS0207)",
   "sleeper": false,
`

**Comment by Mimiix** [comment]
Not a bug, looks like you need to request device support.
