### ISSUE TITLE
> 48 hours unavailability

### ISSUE THREAD

**Issue by andreibanaru** [dresden-elektronik/deconz-rest-plugin#802]
My rpi3 gateway was offline for more than 48 hours due to an SD card failure.
I've reinstalled everything on a new SD card and restored settings by using the Phoscon load backup option.

All my sensors and switches are listed as unavailable and no lights are shown in the WUI.

I've looked inside the zll.db and all entities are there.

What can I do besides repairing 19 lights, 5 switches and 7 sensors?

![image](https://user-images.githubusercontent.com/38393163/45938948-65b47800-bfd7-11e8-940e-57ae97035ae0.png)

Also, for some reason Phoscon WUI and the old WUI list the gateway as using the channel 0?!

![image](https://user-images.githubusercontent.com/38393163/45939046-33efe100-bfd8-11e8-9f0f-2243d9d49f39.png)

![image](https://user-images.githubusercontent.com/38393163/45939049-3b16ef00-bfd8-11e8-9f90-69013d6467cf.png)

**Comment by manup** [comment]
It looks very much like there is no connection between RaspBee and deCONZ.
Maybe the the serial port isn't configured yet?

Please check these steps:
https://github.com/dresden-elektronik/deconz-rest-plugin#software-requirements

**Comment by andreibanaru** [comment]
You are so right. I've moved to hassOS and forgot to migrate the config.txt settings.

After adding `dtoverlay=pi3-miniuart-bt` into config.txt and rebooting RPI all entities are displayed in Phoscon.

Thank you!
