### ISSUE TITLE
Wrong type for Legrand Teleruptor device - "On/Off plug-in unit" instead of "On/Off light"

### ISSUE THREAD

**Issue by Bluearrow75** [dresden-elektronik/deconz-rest-plugin#8031]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

I am using Legrand Teleruptor [Link](https://www.legrand.fr/pro/catalogue/telerupteur-connecte-drivia-with-netatmo-silencieux-1p-16ax-230v-1-module)
When added to Deconz the type is showing as "On/Off plug-in unit" instead of "On/Off light"
As a consequence all lights associated to Legrand modules are showing as separate outlets (instead of the room lights) in HomeKit and Google Home

Here is an export 

"etag": "xxxxxxxx",
    "hascolor": false,
    "lastannounced": "2024-11-03T13:19:43Z",
    "lastseen": "2024-11-16T12:39Z",
    "manufacturername": "Legrand",
    "modelid": "Teleruptor",
    "name": "Spots Cuisine",
    "state": {
        "alert": "none",
        "on": false,
        "reachable": true
    },
    "swversion": "0025",
    "type": "On/Off plug-in unit",
    "uniqueid": "xxxxxxxx"
}

Is it possible to fix the device type please for Legrand Teleruptor?
                    
                

### Steps to reproduce the behavior

1. Add Legrand Teleruptor Drive with Netatmo module
2. Check type in Help -> API Information, it shows "On/Off plug-in unit"

### Expected behavior

Type shows "On/Off Light"

### Environment

- Host system: Raspberry Pi 4
- Running method: Raspbian
- Firmware version: 26720700
- deCONZ version (not Home assistant Addon version!): 2.22.02 
- Device: ConBee II
- Do you use an USB extension cable: No
- Is there any other USB or serial devices connected to the host system? RFXCom

**Comment by Smanar** [comment]
Hello, effectively can use a "On/Off output" for exemple.
But the problem is it's an old device, so it use the legacy core, and it mean we need to create a complete DDF just for that.
