### ISSUE TITLE
Add Tuya vibration sensor TZE200_iba1ckek

### ISSUE THREAD

**Issue by jerrybboy** [dresden-elektronik/deconz-rest-plugin#8035]
### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for my device

### Product name

zigbee smart vibration sensor

### Manufacturer

Tuya

### Model identifier

_TZE200_iba1ckek

### Device type to add

Sensor

### Node info

![image](https://github.com/user-attachments/assets/ac83ee13-e07e-415c-806f-3fc5bbb8167a)

### Endpoints and clusters

![image](https://github.com/user-attachments/assets/73a07171-c0ae-4a81-94f9-05748ec9e42f)

### Basic

![image](https://github.com/user-attachments/assets/f2a82382-21c9-4f02-b93c-958eaea67fb5)

### Power Configuration
![image](https://github.com/user-attachments/assets/de7f1bac-9a26-4867-bc9e-b2f885824c17)

**Comment by c4coer** [comment]
just to say, it's good, it works, just missing the sensitivity adjustment. thanks

**Comment by Smanar** [comment]
Can try with adding to the DDF

```
        {
          "name": "config/sensitivity",
          "read": {
            "fn": "none"
          },
          "write": {
            "dpid": 104,
            "dt": "0x2b",
            "eval": "Item.val;",
            "fn": "tuya"
          },
          "parse": {
            "dpid": 104,
            "eval": "Item.val = Attr.val;",
            "fn": "tuya"
          }
        },
```

**Comment by c4coer** [comment]
Thanks, it works

**Comment by Smanar** [comment]
Can you make a PR to submit it or want I make it ?

**Comment by c4coer** [comment]
I don't know how to do it, but if you have an example, I can do it.
Or if you prefer I'll let you do it

**Comment by Smanar** [comment]
Done > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/8126
