### ISSUE TITLE
Firmware 26240500 just dropped mye HUE-1 remote

### ISSUE THREAD

**Issue by olemr** [dresden-elektronik/deconz-rest-plugin#804]
This did not happen with Firmware 26230500
REST API is not updated. No red light on remote though.
Restarting deconz does not get the HUE-1 back.

**Comment by manup** [comment]
Does it still don't work?
You can force the remote to powercycle by pressing all 4 buttons for about 5 seconds.

**Comment by olemr** [comment]
Today it happened again. Had to press all 4 buttons to regain contact.
