### ISSUE TITLE
Cannot link Hue Smart Button to Lamp in Phoscon Web App

### ISSUE THREAD

**Issue by mzielinskim** [dresden-elektronik/deconz-rest-plugin#8068]
### Does the issue really belong here?

- [X] I definitively want to report a bug within deCONZ or its REST-API

### Is there already an existing issue for this?

- [X] I have searched the existing issues and there is none for the bug at hand

### Describe the bug

Cannot link Hue Smart Button to Lamp in Phoscon Web App

### Steps to reproduce the behavior

1. I connect a Hue Smart Button to Phoscon. It is shown as it should in the Web Interface.
2. Then i select a Group to link the Button to.
3. I go into the Button-Editor, select the button, select the Action On/off and after klicking on "Next" nothing happens.

### Expected behavior

i Expeted the Button to be linked an switch the lamp on/off - but nothing happens.

when i klick on the Lamp-Icon of the group i can switch the lamp on/off as it should.

Other Switches like tradfri shortcut button work as expected with the same lamp.

### Screenshots

![image](https://github.com/user-attachments/assets/0d7c5f09-a2e5-425c-bd99-761daca9e247)

### Environment

- Host system: (Raspberry Pi 
- Running method: (Raspbian 
- Firmware version: 26780700
- deCONZ version 2.29.1
- Device: ConBee II 
- Do you use an USB extension cable: (yes) 

Hue Smart Button 2.47.8_h2F968624

**Comment by Mimiix** [comment]
Hi,
Looks like this is an bug within phoscon, not deconz. Please create a post on the forums as phoscon bugs are collected there.

Closing this issue.
