### ISSUE TITLE
Cant get WXKG02LM OR WXKG03LM to pair

### ISSUE THREAD

**Issue by fillwe** [dresden-elektronik/deconz-rest-plugin#811]
Been trying for 8 hours now to get these into my Conbee. Have tried following the advice on how to reset and pair from other threads here but with no luck. Have also tried to reset them via Touchlink but they are not showing up there either. Have also tried changing batteries. I'm able to pair other Xiaomi devices. Running 2.05.39 via Hass.io on a Raspberry Pi, any ideas?

**Comment by fillwe** [comment]
I'm starting to believe that there has been a new version of this realesed in August but with the same product name and . All listings on Gearbest, Aliexpress and Banggood are getting renewed and the older listings sold out. The packaging i got seems different from the old ones. https://www.banggood.com/Original-Xiaomi-Aqara-Wireless-Smart-Remote-Control-Switch-International-Version-Smart-Home-p-1341453.html?rmmds=search&ID=521034&cur_warehouse=CN

**Comment by ErnstEeldert** [comment]
Looks like a different model identifier than described [here](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG02LM). I just received these switches today, so assuming it's the new model.

![xiaomi_wxkg02lm_nodeinfo](https://user-images.githubusercontent.com/8919203/47878489-b2813f00-de1e-11e8-90fc-9b5bfc4f60d0.png)
![xiaomi_wxkg02lm_clusters](https://user-images.githubusercontent.com/8919203/47878491-b319d580-de1e-11e8-9c51-65da5faaaa6a.png)
![xiaomi_wxkg02lm_basic_cluster](https://user-images.githubusercontent.com/8919203/47878492-b319d580-de1e-11e8-837e-39ab9908cb05.png)

**Comment by fillwe** [comment]
Does not seem like we are getting any response, @ErnstEeldert could you post this in a new thread with device integration tag? We can close this one

**Comment by manup** [comment]
The issue is fine, to track the development of WXKG02LM OR WXKG03LM. It just takes time due all the other ongoing topics.

**Comment by manup** [comment]
Added pages to separate the WXKG02LM 2016 and 2018 versions.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG02LM-2016

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG02LM-2018

Can anybody please provide logs for WXKG02LM 2018 version when pressing buttons?

    deCONZ --dbg-aps=2 --dbg-zcl=1 --dbg-info=1

**Comment by goermezer** [comment]
Here is an output of:

- Press left button
- Press right button
- Press both buttons
- Double press left button
- Double press right button

Sensor which reports:  0x00158D00027C277E

Attached file:

[0x00158D00027C277E.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2566587/0x00158D00027C277E.txt)

Hope, it helps. I have 43 Nodes, which make a lot of noise...

**Comment by o0shojo0o** [comment]
I tried to match goermezer: 

- Press left button
- Press right button
- Press both buttons
- Double press left button
- Double press right button

Sensor which reports: 0x84182600000c787d

[0x84182600000c787d.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2568352/0x84182600000c787d.txt)

**Comment by ebaauw** [comment]
> Sensor which reports: 0x84182600000c787d

That’s an OSRAM device, not a Xioami.

**Comment by goermezer** [comment]
Thanks @ebaauw, you are right. It wasn`t the right id. I will test again...

**Comment by goermezer** [comment]
Ok, here is another test. The reporting sensor is 0x00158D00027C277E20.
[0x00158D00027C277E20.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2568664/0x00158D00027C277E20.zip)

**Comment by o0shojo0o** [comment]
> > Sensor which reports: 0x84182600000c787d
> 
> That’s an OSRAM device, not a Xioami.

Oh sorry, I caught the wrong device.
Am still quite new in the matter, and therefore have problems in the log to find the right entries.

**Comment by samsonovss** [comment]
Version - 2.05.47 WXKG02LM not work
![2018-11-15 22 53 21](https://user-images.githubusercontent.com/41430933/48571799-9c4ca600-e929-11e8-8f49-43e829ba4e84.png)
![2018-11-15 22 53 33](https://user-images.githubusercontent.com/41430933/48571802-9c4ca600-e929-11e8-8d41-eeab9697e2f3.png)

**Comment by manup** [comment]
They are not party of .47, I'm expecting the switches and some other Xiaomi to arrive next week and hopefully to complete, test and support for them in the API and Phoscon App quickly.

**Comment by goermezer** [comment]
@manup I saw .48 today, installed the version and tested again my WXKG02LM 2018. But the device is still not detected in REST API. With deconz GUI it joins the network and is identified as lumi.remote.b286acn01.

**Comment by o0shojo0o** [comment]
Hi manup,
have you already received your Xiaomi delivery?
And if so, is there something new?
Here are a few WXKG02LM waiting for their use ;)

**Comment by manup** [comment]
The switches are still not here :/ but I've started work on it based on the data provided here.

**Comment by carloscae** [comment]
@manup the unsung hero. thanks a lot.
do you plan on supporting the double and long presses as well? even if not initial release?

**Comment by manup** [comment]
If the switches support these yes, the above logs didn't indicate that. If you can provide this data the related events can be added quickly.

**Comment by carloscae** [comment]
The new switches do support single, double and long press. They are accessible via Aqara official hub.

I unfortunately have no windows machine to try the Deconz interface, but I'll get a virtual machine up and running to get those logs. I have both single and double rocker remotes.

**Comment by greencharlie100** [comment]
I am running deconz 2.05.49 on hassio. Is this the version with the updates to support the WXKG03LM wireless switches?
If so - how do I pair the switch with Phoscon?

**Comment by carloscae** [comment]
No. It isn't. Probably on 2.05.50

**Comment by carloscae** [comment]
@manup only send the commit for the update, but the new version was not yet released. once it is, we need to ask or wait for marthoc to update his Hassio plugin. Might be necessary to also update the firmware of your Conbee/Raspbee.

**Comment by greencharlie100** [comment]
Sorry, I did not realise that. I will wait patiently for the Hassio plugin update. Thanks for the info.

**Comment by carloscae** [comment]
I'm also looking forward very much to this. I currently have it paired directly on Homekit and its automations are extremely crappy. Anyway, you can follow the Hassio plugin development here:

https://github.com/marthoc/hassio-addons

**Comment by greencharlie100** [comment]
I will keep an eye on it. Thanks again.

**Comment by manup** [comment]
[copy and paste]
We are working on the Phoscon App Switch editor support for the following switches:

* WXKG01LM
* WXKG11LM
* WXKG12LM
* WXKG02LM
* WXKG03LM

Some of these have different versions wich will also be handled by the Switch Editor.

Current plan is to get a first preview online till Saturday, since I still don't have all switches here for testing there might be issues which need to be ironed out in further releases.

**Comment by Phoenix-DH** [comment]
Hey guys,

I got a ConbeeStick running since 3 days. Everything is working fine, except this xiaomi switch WXKG02LM.

I read a lot in this fork but am not sure if it normally should work or not.
On my package there was only something mentioned with a timestamp from 2016 ... I read nowhere something from 2018.
Should my version work?

I tried connecting as switch, as sensor, no response inside PHOSCON.
I tried to connect via reset of the switch, pushing both for 10 seconds until the LEDs will blink ...
Or am I doing something wrong?

I installed the deb from http://www.dresden-elektronik.de/rpi/deconz/deconz-latest.deb which should be the same than this one here, right? Is version 2.05.49.

Thanks!

**Comment by carloscae** [comment]
One way to know if you have a newer model is by the looks of the box. Does it have only a gray Aqara logo or is it a nicer box with a photo of the product?

**Comment by carloscae** [comment]
You have the new one which is not yet supported, so your issues as expected. Good news is that it should be fixed on the next release some time this week. I’m also on this boat. Now we have to wait just a little bit more. :)

**Comment by Phoenix-DH** [comment]
Okay, then my assumption is correct.
Thank you!

How can I then update my version from:
http://www.dresden-elektronik.de/rpi/deconz/deconz-latest.deb

Will this work directly via PHOSCON App like the initial FW Update?

**Comment by carloscae** [comment]
I assume once your case you can do that directly via Phoscon app once it's officially released: Keep an eye for 2.05.50. 
I only have experience with Hassio installation which is a bit more complicated to update than normal installations.

**Comment by OmikronApex** [comment]
@manup I might not have logs for the new WXKG02LM Switches yet, but I got my deconz hooked up to iobroker and the switch reports the following button events:
x001
x002
x004
for left, right and both buttons respectively as 1001, 2001, 3001 etc. 
No x003 sadly as it seems.

Do you still need exact deconz logs to add the events? I might be able to set up a clean version of deconz to get them later this day.

**Comment by manup** [comment]
>Do you still need exact deconz logs to add the events? I might be able to set up a clean version of deconz to get them later this day.

Yes, the output with what is received would is needed.

    deCONZ --dbg-info=1 --dbg-aps=2 --dbg-zcl=2

**Comment by OmikronApex** [comment]
@manup Alright, I'll post the logs once I got them.

**Comment by OmikronApex** [comment]
Didn't hav the time to do a clean setup of deCONZ but here are my logs for the new WXKG02LM:

- left single
- left double
- left hold
- right single
- right double
- right hold
- both single
- both double
- both hold

The corresponding node is 00158D00027C1631.

[00158D00027C1631.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2650349/00158D00027C1631.txt)

Hope this helps :)

**Comment by manup** [comment]
Thanks, I'm afraid the payload is missing was the log done with following debug options?

(note level 2)

    deCONZ --dbg-info=1 --dbg-aps=2 --dbg-zcl=2

**Comment by OmikronApex** [comment]
Yes I used these exact parameters

**Comment by manup** [comment]
First line in the log says `pi@phoscon:~ $ deCONZ --dbg-info=1 --dbg-aps=1 --dbg-zcl=1 --dbg-zdp=1 --http-port=80`

The needed information is only visible with ` --dbg-aps=2`

**Comment by manup** [comment]
Thanks this one works and also my switches and new sensors arrived today.

Just took a look at the WXKG02LM (lumi.remote.b286acn01) in the sniffer and it's weird ;)

Following happens for left, right and both buttons:

* Single click: multistate value 0x0001
* Double click: multistate value 0x0002
* Hold: multistate value 0x0000,
* ... followed by an report for Basic Cluster on attribute 0xfff0 with 9 character octed string  `aa:10:05:41:87:19:01:10:01`
* **Important** No Hold release indication is sent!
* Hold for more than 10 seconds the switch **leaves** the network and is no longer available

Therefore it won't be possible to support push dim like:
* hold: dim lights 
* release stop dim

I think it's dangerous to use the hold event since the switch does a reset by just pressing any button for greater than 10 seconds, but the same is true for the old WXKG02LM version.

**Comment by manup** [comment]
Version 2.05.50 supports more switches in the REST-API, Phoscon App switches view and the switch editor.
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_50

Support for double click events for the wall switches will be added in the next version.

**Comment by Phoenix-DH** [comment]
Thanks for the great work.
How can I perform the update?

I had a llok to the phoscon gsteway page. There is after esch reboot the message rhat there is a new firmware: 262F0500 although this version is alresdy installed.

But no hint about new version.

**Comment by manup** [comment]
Currently you need to manually update the version, update via app will be shown in a few days.

https://github.com/dresden-elektronik/deconz-rest-plugin#precompiled-deconz-packages

**Comment by Phoenix-DH** [comment]
Okay, thank you!

Can I follow this steps, only for the package?

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

For sure, take the latest package.

**Comment by manup** [comment]
Should be enough when you do steps 1–3 mentioned from here

https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz

**Comment by Phoenix-DH** [comment]
Worked, thanks.
Had to restart the service to update version in GUI.

**Comment by koen01** [comment]
4x WXKG02LM 2018 version tested and working. 
Added via phoscon. 

Thank you!

**Comment by Phoenix-DH** [comment]
I also get mine paired as switch.
In homekit with homebridge-hue plugin the switch is not recognized as switch.

Is this working for anybody? Some hints?

**Comment by manup** [comment]
>In the meanwhile I added a light to PHOSCON and the switch was not working too...

Can you please provide more information?

**Comment by Phoenix-DH** [comment]
What do you exactly need?

This are steps I did for PHOSCON:
I deleted one lamp in hue bridge, added via PHOSCON.
Created a group with this one lamp and the switch.
Added an action to each of the both buttons.
Pushed the button, but nothing is happening.

**Comment by Phoenix-DH** [comment]
I reconfigured everything, now within the phoscon app everything is fine.
Everything was also exposed to homekit.

Only after a period of time now I got the following:
```
[2018-12-10 16:47:05] [ConbeeStick] ConbeeStick: gateway error 3: resource, /lights/3, not available
[2018-12-10 16:47:05] [ConbeeStick] Schlafzimmer Fluter: homekit on changed from 0 to 1
```

Will have an eye on it ...

Switch the light on/off via hardware switch works as well as per PHOSCON ...
Only homekit is stucking now.

**Comment by manup** [comment]
The json looks fine, just testet websocket events are also fired.
@Kane610 Maybe the `modelid` isn't yet in supported in Home Assistent component?

**Comment by Kane610** [comment]
If the battery shows up as a sensor it works as expected since remotes are only exposed as events in home assistant.

**Comment by carloscae** [comment]
> I seem to have the same issue, with the switch being recognised in Phoscon, but somehow Home Assistant doesn't see the switch. Just the battery status.
> 
> If I do a get on /api/[key]/sensors, the switch shows up. So I don't know whether it's Home Assistant that doesn't parse the json correctly, or Phoscon/deConz that replies with wrong json data.
> 

Light switches will only trigger events.
You need to use automations like the example bellow:

`- alias: Aqara Toggle
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: aqara_1
      event: 1002
  action:
      data_template:
        entity_id: light.office
      service_template: >
        {% if is_state('light.office','off') %}
          homeassistant.turn_on
        {% else %}
          homeassistant.turn_off
        {% endif %}`

**Comment by greencharlie100** [comment]
Is the latest update available in hass.io? Or  is there any way I can implement this latest update myself in hass.io?

**Comment by greencharlie100** [comment]
Apologies - I see the latest deconz hass.io addon has been released 25mins ago...

**Comment by Phoenix-DH** [comment]
> I seem to have the same issue, with the switch being recognised in Phoscon, but somehow Home Assistant doesn't see the switch. Just the battery status.
> 
> If I do a get on /api/[key]/sensors, the switch shows up. So I don't know whether it's Home Assistant that doesn't parse the json correctly, or Phoscon/deConz that replies with wrong json data.
> 
> `"2": { "config": { "battery": 100, "on": true, "reachable": true, "temperature": 2300 }, "ep": 1, "etag": "2c397e05aa2fecab16740c872cbcdabd", "manufacturername": "LUMI", "mode": 1, "modelid": "lumi.remote.b286acn01", "name": "Schakelaars Boven", "state": { "buttonevent": 1002, "lastupdated": "2018-12-10T20:19:23" }, "type": "ZHASwitch", "uniqueid": "00:15:8d:00:02:7c:0d:e2-01-0012" },`

I did everything from the scratch...
Now it seems to work. I have no outages in Homekit until now.

I use the homebridge-hue plugin to expose the switches.
At the moment they are only known as unknown component, not shown like the original hue switch.
I can image that that will also came up within the next days.

**Comment by Phoenix-DH** [comment]
I do not have those values ... maybe somebody can provide them?
I already opened an issue for that yesterday:
https://github.com/ebaauw/homebridge-hue/issues/407

Maybe those values can be added.

Thank you all for the great work.

**Comment by greencharlie100** [comment]
I am looking to do an automation – toggle a wired switch with a wireless switch event…

Here are details of both my switches:

Wireless Switch - *Sensor:
"2": {
            "config": {
                "battery": 100,
                "on": true,
                "reachable": true,
                "temperature": 2300
            },
            "ep": 1,
            "etag": "340e11d662f566ff4f0f883ceaeeba02",
            "manufacturername": "LUMI",
            "mode": 1,
            "modelid": "lumi.remote.b186acn01",
            "name": "Hall Lower",
            "state": {
                "buttonevent": 1002,
                "lastupdated": "2018-12-11T17:59:59"
            },
            "type": "ZHASwitch",
            "uniqueid": "00:15:8d:00:02:7c:3e:0e-01-0012"
        },


Wired Switch -*Light:
"1": {
            "etag": "42da2d16d2c49503441d4ee524fbbb2e",
            "hascolor": false,
            "manufacturername": "Unknown",
            "modelid": null,
            "name": "Hall Lower",
            "state": {
                "alert": "none",
                "on": false,
                "reachable": true
            },
            "swversion": null,
            "type": "Smart plug",
            "uniqueid": "00:15:8d:00:02:a1:8a:76-02"
        },


I was trying something along these lines provided by @carloscae above:

automation:
  alias: Hall Lower - Toggle
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
    id: 1
    event: 1002
  action:
    data_template:
    entity_id: lights.1
    service_template: >
        {% if is_state('light.1','off') %}
        homeassistant.turn_on
        {% else %}
        homeassistant.turn_off
        {% endif %}



Can anyone help make this automation work?

**Comment by carloscae** [comment]
@greencharlie100 try using “hall_lower” as the ID on the automation. That’s normally how Hassio parses the Deconz names.

**Comment by greencharlie100** [comment]
I tried changing that Id - but still not working.

**Comment by carloscae** [comment]
Can you post the entity id of the battery status of the switch? Something like:
sensor.switc_bathroom_battery_level

**Comment by greencharlie100** [comment]
Where would that info be located?

**Comment by greencharlie100** [comment]
Also tried this - but still not working.

automation:
  - alias: 'Toggle lamp from dimmer'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: hall
        event: 1002
    action:
      - service: light.toggle
        data_template:
          entity_id: switch.light_1
          service_template: >
            {% if is_state('switch.light_1','off') %}
            homeassistant.turn_on
            {% else %}
            homeassistant.turn_off
            {% endif %}

**Comment by greencharlie100** [comment]
I am changing/testing here that's why some things have changed. I had used yours at the beginning. My 'Hall Lower' is now 'hall' in deconz API.

**Comment by greencharlie100** [comment]
Do you have this working ?

**Comment by carloscae** [comment]
The “service: light.toggle” is wrong. Will never work on a switch. You don’t need that line on this format I provided.

**Comment by greencharlie100** [comment]
Is 'event_type: deconz_event' correct or should it be: 'event_type: buttonevent'

**Comment by carloscae** [comment]
This is what I use. This works for anything that can be switched on/off.

```
- alias: Garden Switch Toggle
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: switch_garden
      event: 1002
  action:
      data_template:
        entity_id: light.garden_group
      service_template: >
        {% if is_state('light.garden_group','off') %}
          homeassistant.turn_on
        {% else %}
          homeassistant.turn_off
        {% endif %}
```

**Comment by greencharlie100** [comment]
Thanks @carloscae .

I copied and pasted your code and replaced both fields as you said.

I also removed 'automation:' from the top of my '/config/automations.yaml' file which prob should not have been there.

It works !!

During testing I realised that when I restart HA I cannot control the switches (any) through the HA app until i physically toggle every switch first.  Is there a solution to this?

**Comment by carloscae** [comment]
Have not noticed this issue. Can you describe in detail one switch ?

Ideally you won't be restarting it all the time, and for automations, you cannot don't need to. There is a button to reload automations.

**Comment by greencharlie100** [comment]
I was thinking in the event of a power failure and then the PI/HA booting up again.  What seems to happen:  if i restart HA and then try to toggle a switch/light within HA (after it has booted) - I cannot. The light doesn't toggle. But as soon as I physically toggle the switch with my hand the light can then be toggled through the HA interface again.

**Comment by greencharlie100** [comment]
If you aren't experiencing this - then maybe I need to give it more time to sync, and by physically toggling the switch it syncs quicker. Let me know if you can replicate the problem. I will get back in touch in the morning..

**Comment by greencharlie100** [comment]
I was able to add wired switches (QBKG03LM) earlier today but was unable to add one out of 4 wireless switches. I reinstalled deconz and was then able to add my four wireless switches again successfully. BUT now I cannot add ANY of my wired switches!
Any ideas what's going on?

**Comment by carloscae** [comment]
I had an issue yesterday that I couldn't pair some off my remote switches, which i think happened due to poorly handled unpairing from Aqara Bridge. Had to remove the batteries for some minutes then it worked. Maybe you wanna try that.

You can notice that when the pairing is working, after the lights blinking fast 3 times, it turns on again. When it wasn't working for me, it blinked 3 times and then was totally off.

**Comment by greencharlie100** [comment]
Yea, but it the wired switches that wont pair - they did perfectly before.

**Comment by carloscae** [comment]
So did my remote switches. Check the behaviour of your lights before dismissing the advice. ;)

**Comment by greencharlie100** [comment]
Just got it working - very strange behaviour.

In HA Configuration/Integrations I removed deconz.
Then added it again
And all my wireless switches AND wired switches are there.

They were not there before, nor were they in the API.

Thanks anyway @carloscae

**Comment by Vout** [comment]
A small kick, i just received 2 of these switches today and after adding them and seeing events on the websocket port i tried adding them in Hass.IO

Strange thing however is that after an reboot of the server everything is running on the switches are still there but for one or another reason they aren't woking / sending events anymore.

When i check the deconz addon inside home assistant i see this message,

`20:02:43:168 APS-DATA.indication from unknown node 0x00158D0002C93786
20:02:43:168 no button map for: lumi.remote.b286acn01 ep: 0x01 cl: 0x0012 cmd: 0x0A pl[0]: 055
20:02:43:168 ZCL attribute report 0x00158D0002C93786 for cluster 0x0012, ep 0x01`

So i still receives the data but for one or another reason it isn't mapped to the switches anymore. The single ones i added a week ago are still working fine.

**Comment by ErnstEeldert** [comment]
@manup I have the WXKG02LM 2018 model, and while it pairs fine, shows up in Phoscon just fine, only the following events are showing up (checking via dc_eventlog):

- 1002 -> single press
- 1001 -> hold
- 1004 -> double press

So what seems to be missing is the 1003 release hold event, which should be supported according to the wiki?

This is what the switch looks like over REST:
```json
{
  "config": {
    "battery": 100,
    "on": true,
    "reachable": true,
    "temperature": 2700
  },
  "ep": 1,
  "etag": "7c9b6dae04b8ec0630b6f5396c812392",
  "manufacturername": "LUMI",
  "mode": 1,
  "modelid": "lumi.remote.b186acn01",
  "name": "Enkele Schakelaar",
  "state": {
    "buttonevent": 1001,
    "lastupdated": "2019-01-09T20:29:25"
  },
  "swversion": "20180525",
  "type": "ZHASwitch",
  "uniqueid": "00:15:8d:00:02:8f:80:26-01-0012"
}
```

**Comment by PortalFreak** [comment]
Hi, 
im also not able to pair the switches WXKG02LM into the Phoscon-GW. I think i got model 2018, because you need for reset press 10 seconds the button, not 5 seconds like the 2017 model. 
I have several other sensors like temperature / door sensor by aqara, they are working fine. My Conbee is up to Date, the latest firmware is installed. 
Could anyone provide me some steps, to figure out how i got it connected? 

thanks a lot

**Comment by greencharlie100** [comment]
What version of deCONZ you running?

**Comment by PortalFreak** [comment]
hi, im running:
Version 2.05.40 / 8.10.2018
Firmware 26240500

**Comment by greencharlie100** [comment]
Thats your issue. 2018 switches (wireless aren't supported until later release). Update deCONZ and restart. Add switch as 'switch' in Phoscon app with normal procedure and they will add no problem.

**Comment by PortalFreak** [comment]
hi, i got some trouble during the flashing process. 

`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
-------------------------------------------------------------------

       marthoc/deconz Conbee/RaspBee Firmware Flashing Script

                       Version: 0.3

-------------------------------------------------------------------

Enter C for Conbee, R for RaspBee, or press Enter now to exit: C

Listing attached devices...

rmmod: ERROR: Module ftdi_sio is in use
rmmod: ERROR: Module usbserial is in use by: ftdi_sio
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
RaspBee: /dev/ttyS0 (default)

       1  FTDI device found

 device | vendor | product | serial  | description
--------|--------|---------|---------|----------------------
failed to open FTDI device (0) status = 3


Enter the Conbee device number, or press Enter now to exit.

Device Number : 1

-------------------------------------------------------------------

Firmware available for flashing:

deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x262e0500.bin.GCF
deCONZ_Rpi_0x262f0500.bin.GCF

Enter the firmware file name from above, including extension,
or press Enter now to exit.

File Name : deCONZ_Rpi_0x262f0500.bin.GCF

-------------------------------------------------------------------

Conbee Device Number: 1

Firmware File: deCONZ_Rpi_0x262f0500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

rmmod: ERROR: Module ftdi_sio is in use
rmmod: ERROR: Module usbserial is in use by: ftdi_sio
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
using firmware file: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF
reset via FTDI
FTDI can't open device 1, status = 2
`

what is the ftdi_sio module?

**Comment by manup** [comment]
>Version 2.05.40 / 8.10.2018

Note the WXKG02LM and WXKG03LM switches were added in later versions, current version is 2.05.55.

**Comment by greencharlie100** [comment]
I am not using docker so I cant help with the update. It may be easier to uninstall and reinstall the latest deCONZ version.

**Comment by PortalFreak** [comment]
> > Version 2.05.40 / 8.10.2018
> 
> Note the WXKG02LM and WXKG03LM switches were added in later versions, current version is 2.05.55.

thanks for your help, 

so, is the switch now supported? i bought them, because in your [wiki ](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices) it is a supported device. 
I am a bit confused

**Comment by manup** [comment]
Yes, these switches are supported since version 2.05.50

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_50

>You mean, i need Version 2.05.55, yes?

Yes that's the current and recommended version.

**Comment by greencharlie100** [comment]
@PortalFreak, I told you nearly 24 hours ago to update deCONZ (meaning dowload latest version) and your switches will add to Phoscon.

**Comment by PortalFreak** [comment]
yes. thanks. you did. but i didnt know whats the target version. The UI told me its up to date. anyway.. 
i found that "Firmware updates from the web UI will fail silently" through phoscon, so i needed to resolve that issue first. 
After fixed it, the logsfiles looks good. 

`
[marthoc/deconz] Websockets port: 443,
21:09:28:807 dev /dev/ttyAMA0,
20:53:00:582 $[marthoc/deconz] Starting deCONZ...,
[marthoc/deconz] Current deCONZ version: 2.05.55,
[marthoc/deconz] Web UI port: 80,
[marthoc/deconz] Starting without VNC GUI`

but i have no luck, the switch will not pair by 10 seconds reset and press 5 times quickly the left button.

**Comment by greencharlie100** [comment]
These are the details which I have recorded for my own personal use after a lot of trial and error:

You must have deCONZ version 2.05.50 or greater.
/////
******Add a wireless switch:*******
Phoscon APP -> settings/devices/switches
-> Add new switch (deconz will listen for connection)
Press wireless switch for 5-10 seconds until both blue LEDs come on together
Release switch
The wireless switch should be added to ‘Switches’ in Phoscon. 
/////

This procedure has worked for me and pairs to Phoscon on the first attempt. On many occasions, the procedure will only work if you haven't tried to pair the switch before (to a deconz version which cant accept the connection) with many combinations of button presses etc.. 

Try the following:
Remove the battery from the wireless switch for 20 minutes
Restart deconz ( or rather your whole system if you can)
Replace the battery
Try pairing the switch as per my instructions above

If this does not work you need to download the following image on an SD card and try to add the wireless switch. 
https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/raspbee-gw-sd-card-image/?L=1

Doing this will rule out any possible issues you have with your current system configuration. If the wireless switch does not add to your current system but does add to this new system (image) - then I would uninstall and reinstall deconz and hope that the switch will add after that.

Let me know how things go.

**Comment by PortalFreak** [comment]
hi, after setup and reinstall my pi and the deconz docker image, the switches are paired with phoscon. 
Thanks to anyone for your help, i cant retrace why the switched are not paired before that. 
In phoscon now is see the switch as "WXKG02LM Rev.2"  but there is no event visible when i hit a button.

**Comment by manup** [comment]
>In phoscon now is see the switch as "WXKG02LM Rev.2" but there is no event visible when i hit a button.

Checkout the switch editor:

https://doc.phoscon.de/app/doc.html#group-edit-switches-en

**Comment by wlatic** [comment]
Just gone through this. Had all sorts of issues trying to pair until I selected the Light section and put it to search.

Then held down the right button for 5 seconds until it reset and it then found it.

I'm seeing some strange issues of the switch toggling off / on, but it is paired.

**Comment by reprz** [comment]
Just got two of these in RPI3+Hassio+Conbee setup and had no problems pairing them using Deconz 2.05.59 version. Only issue I had is that sometimes using toggle the switch makes fast on/off switching.

**Comment by VivantSenior** [comment]
Hi,

for a few hours, I'm trying to pair my WXKG02LM to the Conbee 2 but without success. 

My config is:
- Conbee 2,
- RPi 3B+,
- Hass.io 0.103.3,
- deCONZ add-on 4.1.

It was working ok with [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt) addon but now I moved to Phoscon it doesn't work. The weird part is that different switch WXKG02LM and two WXKG03LM paired without any issues.

What I have done so far:
1. I have to tear it from the wall and move it closer to Conbee 2.
2. Changed battery in the wall switch.
3. Reset hass.io and deCONZ add-on.

**Comment by mhin76** [comment]
Hi all. I recently also bought such a two button switch but the newest version WXCJKG11LM seem not supported. I got it paired and it appears in deconz and I also see data on the log when I push the button but it does not appear on Phoscon. In deconz it gets identified my mistake as Switch Dimmer. Funny enough sometimes after pairing all my light do go on when I click on the button. 
Can I provide any data log file so this switch can be included? Would be really great!

**Comment by Smanar** [comment]
Ha you have the last opple device ?
It's not the same than this issue, yours is here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2061

But to resume, you will need the future deconz version for full support using the API.
