### ISSUE TITLE
Support for Salus SP600 Smart Plug

### ISSUE THREAD

**Issue by GadgetUK** [dresden-elektronik/deconz-rest-plugin#812]
This appears as a light switch, but no metering functionality is available.

Details of the device can be found here

https://salus-controls.com/uk/product/sp600/#description

Happy to provide more info if instructions on how to get required data are available.

**Comment by ebaauw** [comment]
See https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by GadgetUK** [comment]
Ok, think this the right stuff
<img width="387" alt="screen shot 2018-09-29 at 10 29 46" src="https://user-images.githubusercontent.com/1688999/46244149-cf1af900-c3d2-11e8-9750-67382cfcd052.png">
<img width="254" alt="screen shot 2018-09-29 at 10 30 08" src="https://user-images.githubusercontent.com/1688999/46244150-cf1af900-c3d2-11e8-8d8f-a999ae4945fc.png">
<img width="388" alt="screen shot 2018-09-29 at 10 30 30" src="https://user-images.githubusercontent.com/1688999/46244151-cf1af900-c3d2-11e8-86b6-01bbddd85c15.png">

**Comment by ebaauw** [comment]
Could you try and read the attributes for the _Basic_ cluster?  We need the _Model identifier_ and, preferably, the _Manufacturer name_.

Could you also please post a screenshot of the _Simple metering_ and _Temperature measurement_ clusters, again, after reading the attributes?  The metering might provide life-time consumption and current power, but the scale typically differs per device type.  I haven’t seen a plug before, that reports temperature, but if it’s functional, we could support it.

It would be good to know if the plug supports attribute reporting, but we haven’t yet described how to determine that in the Wiki.  I’ll see if I can find some for that time this weekend.

**Comment by GadgetUK** [comment]
Ok. Here goes.
<img width="546" alt="screen shot 2018-09-29 at 16 41 44" src="https://user-images.githubusercontent.com/1688999/46247657-9a289980-c406-11e8-8a85-ea139aa1ed39.png">


<img width="533" alt="screen shot 2018-09-29 at 16 40 12" src="https://user-images.githubusercontent.com/1688999/46247646-66e60a80-c406-11e8-9ba1-e75bd430a8f7.png">
<img width="531" alt="screen shot 2018-09-29 at 16 40 26" src="https://user-images.githubusercontent.com/1688999/46247649-6f3e4580-c406-11e8-8e95-871b6b3f9b72.png">
<img width="553" alt="screen shot 2018-09-29 at 16 41 18" src="https://user-images.githubusercontent.com/1688999/46247661-a0b71100-c406-11e8-8c85-73e81a99e781.png">

**Comment by GadgetUK** [comment]
If I've followed the deconz manual correctly....

<img width="295" alt="screen shot 2018-09-29 at 17 16 49" src="https://user-images.githubusercontent.com/1688999/46248019-98ada000-c40b-11e8-8a45-37db9ef0a0c2.png">

**Comment by ebaauw** [comment]
Thanks.

When you connect something to the plug and turn it on, does the value for _Instantaneous demand_ change?  _Current Summation Delivered_ typically takes a while - it's usually updates every 10Wh or so.  You want to try setting the reporting config to _Min_: 1, _Max_: 300, _Change_: 1 and create a binding from that cluster to the RaspBee.   Select the _Bind Dropbox_ from the _Panels_ menu, drag the 0x702 cluster to _Source_ and drag the 0x01 endpoint on the coordinator to _Destination_ and press _Bind_:
![screenshot 2018-09-29 at 19 05](https://user-images.githubusercontent.com/22179355/46248531-b6cecc80-c41a-11e8-9efb-fc596f54c678.png)
Could you try the same for the _OnOff_ attribute and the _OnOff_ cluster?

The temperature cluster seems to measure internal temperature (49°C), so that doesn't seem too useful.

**Comment by GadgetUK** [comment]
Ok. Writing changed values to the reporting configuration fails.

**Comment by ebaauw** [comment]
Does it come back quickly with an error message, or does it take a longer time?  Sometimes the GUI doesn’t seems to miss the ack.  What happens if you close the popup window, re-open it and read the config?

**Comment by GadgetUK** [comment]
Ok, seems to have worked
<img width="283" alt="screen shot 2018-09-30 at 17 45 31" src="https://user-images.githubusercontent.com/1688999/46260004-ad0b9e80-c4d8-11e8-8e90-82bcf3cab935.png">
Although the reportable change is now greyed out.

**Comment by ebaauw** [comment]
The GUI doesn’t handle the int24 well.

**Comment by GadgetUK** [comment]
Is there anything more that I can do to progress support ?

**Comment by GadgetUK** [comment]
Feel like this has stalled.

**Comment by Smanar** [comment]
Lol, I haven't the device so I can't make test but the GUI can handle int24 now ?
I had similar problem on another device, and the GUI was corrected.

**Comment by GadgetUK** [comment]
Ok, still seems that it's not possible to set the reporting configuration
![image](https://user-images.githubusercontent.com/1688999/50397963-ec5e2a00-076b-11e9-815e-9247be47727a.png)

**Comment by GadgetUK** [comment]
More info from the Smartthings support

https://github.com/paulsheldon/SmartThings-PS/blob/master/devicetypes/paulsheldon/zigbee-switch-power.src/zigbee-switch-power.groovy

`fingerprint profileId: "0104", inClusters: "0000, 0001, 0003, 0004, 0005, 0006, 0402, 0702, FC01", outClusters: "0019", manufacturer: "Computime", model: "SP600", deviceJoinName: "Salus SP600 Smart Plug"
`

**Comment by ebaauw** [comment]
@GadgetUK with 2.05.59, you should be able to set _Reportable Change_, at least for _Current Summation Delivered_.

@manup, I don't think _Instantaneous Demand_ is working.  This is `s24` instead of `u24`, which is working.

**Comment by manup** [comment]
>@manup, I don't think _Instantaneous Demand_ is working. This is `s24` instead of `u24`, which is working.

Good catch, on it.. this will work in 2.05.60.

**Comment by GadgetUK** [comment]
@ebaauw Ok Can now set _Reportable Change_ for _Current Summation Delivered_ so that's a positive step forward 👍 

![image](https://user-images.githubusercontent.com/1688999/52901513-7ec6fb00-31fc-11e9-9721-283a08725512.png)

**Comment by brettyj** [comment]
@gadgetuk how are you getting on with it? Is it working alright? I'm currently on the lookout for zigbee power plugs with reporting to replace my WiFi ones which keep dropping off the network. (I use them to monitor dishwasher, tumble dryer and washing machine)

**Comment by ebaauw** [comment]
> I use them to monitor dishwasher, tumble dryer and washing machine

Better double-check the power rating of the plug.  I blew a couple of innr plugs on my dryer, that apparently likes to draw a bit more power than its rating would suggest.

**Comment by hmonteiro** [comment]
Are there any plans for officially supporting this plug in the future?

**Comment by hmonteiro** [comment]
@ebaauw Any hints on how to hack something together to make the consumption visible to the Phoscon app as a sensor? When I look at the mesh, I see that the both the instantaneous and summary consumption appear to work, but I don't know what I have to do to make them visible.

In the logs I see some lines related to the 702 cluster:
```
16:35:29:633 APS-DATA.indication srcAddr: 0x518f, srcEp: 0x09 dstAddrMode: 2, profile: 0x0104, cluster: 0x0702, lqi: 255, rssi: -58
16:35:29:633 	asdu: 08430a00042a1b0000
16:35:29:633 Node data 0x001e5e09021460d5 profileId: 0x0104, clusterId: 0x0702
16:35:29:638 ZCL attribute report 0x001E5E09021460D5 for cluster 0x0702, ep 0x09
16:35:29:638 	payload: 00042a1b0000
16:35:29:638 APS-DATA.request id: 81, addrmode: 0x02, addr: 0x518f, profile: 0x0104, cluster: 0x0702, ep: 0x01 -> 0x09 queue: 1 len: 5 tx.options 0x00
```

**Comment by ebaauw** [comment]
Not a clue; Phoscon is not open source.

**Comment by SwoopX** [comment]
Better late than never, I can assist in properly integrating those. However, I need a lab rat for tweaking...

**Comment by djashjones** [comment]
Just got mine cus it was cheap. The only sensor I see is temperature.

**Comment by SwoopX** [comment]
Lemme double check the code.

Why are you buying all the stuff that keeps me busy??? 😁

**Comment by SwoopX** [comment]
Could you please provide a screenshot of the node info panel? In the screenshot further up, the value is missing. This could be the showstopper...

**Comment by djashjones** [comment]
It really sucks for certain things in the UK But I would not spend too much time on this mate. It's slightly cheaper than the samsung plug. The quality, well I'm not too impressed but it does come with a 5 year warranty.

![deconz](https://user-images.githubusercontent.com/55344114/77205759-6c00b300-6aed-11ea-887e-9d3c5c32e5ee.PNG)
![temp 50](https://user-images.githubusercontent.com/55344114/77205777-73c05780-6aed-11ea-94ef-83f7167d4f9b.PNG)
![mode](https://user-images.githubusercontent.com/55344114/77205799-7f138300-6aed-11ea-9940-c4a4a917bf8f.PNG)

**Comment by djashjones** [comment]
![HA](https://user-images.githubusercontent.com/55344114/77206126-2a243c80-6aee-11ea-82ee-c1d9fcc9c49b.png)

**Comment by SwoopX** [comment]
So you got consumpton, but power is missing?

**Comment by djashjones** [comment]
yes mate

**Comment by SwoopX** [comment]
Hm, strange that 2 sensors got created and 1 is still missing. But when there's load applied you see an according value under simple metering for attribute 0x0400 after the attributes have been read in deconz GUI? At times, it also helps to re-read the simple descriptors while searching for sensors in Phoscon...

**Comment by djashjones** [comment]
I've found a workaround for the time being. I'm still evaluating this plug but I am leaning more towards the samsung.
![sensor yaml](https://user-images.githubusercontent.com/55344114/77228791-aae04880-6b81-11ea-9662-901d52b14f59.png)
![power](https://user-images.githubusercontent.com/55344114/77228797-b03d9300-6b81-11ea-8865-8ed7e2dcf0b3.png)

**Comment by djashjones** [comment]
I've extracted the power from the consumption sensor in home assistant
![power2](https://user-images.githubusercontent.com/55344114/77228867-19250b00-6b82-11ea-90e9-5ffa248f9566.png)

**Comment by SwoopX** [comment]
Ah, so it requires amendments on the HA side. I don't have any such devices having power and consumption on the same sensor, but I could have thought about mentioning it. Sry.

Then we're good here?

**Comment by djashjones** [comment]
I think so. Hopefully this will useful to others. I did search for sensors and re-read the "read power descriptor" but that did nothing.

**Comment by SwoopX** [comment]
Alright, then I assume it is working as expected. Just to be clear on that detail: sensors are created on a cluster basis. Since it only has simple metering (besides temperature), there will be no further sensor. In case of this device, however, consumption and power is exposed. That is not a too common combination.

**Comment by mike182uk** [comment]
I might be missing something here, but why would a plug socket also report temperature?

I have set up via phoscon so i can use in Home Assistant (via deconz plugin) similar to what @djashjones has done and the temperature reads `~40°c`, which is not accurate for the room its in (by about 20°c) (unless some kind of conversion needs doing on the value)?

**Comment by SwoopX** [comment]
To be honest, no clue. A questions Salus has to answer. Maybe they consider it more as device temperature (although there's a cluster for it on its own).

**Comment by djashjones** [comment]
Could be for their heating products or a safety reason.

I've stopped using mine. Found a disturbing issue which would be nice if someone else can confirm this.

When the plug loses connection to the network, it switches itself one & off every so often. Which is no good if its attached to say something like a server!!!

**Comment by hmonteiro** [comment]
Regarding the temperature, I have other temperature sensors in the same room and, from anecdotal evidence, the socket temp always looks to be reading about twice as much, so maybe they just report 2x the value?

**Comment by keemyb** [comment]
> Could be for their heating products or a safety reason.
> 
> I've stopped using mine. Found a disturbing issue which would be nice if someone else can confirm this.
> 
> When the plug loses connection to the network, it switches itself one & off every so often. Which is no good if its attached to say something like a server!!!

I am experiencing this. what are you using as a replacement? I wanted to use this as something to track my server power usage as well, but I can't really afford an unexpected shut down just because of an intermittent connection loss. I've only had mine for a day or so, but when I was trying to set it up, I noticed them turning off /on when I left one in pairing mode.

I think I may just get a UPS with power monitoring functionality and get stats from there, because even if I use something less power hungry like a RasPi, I can't say for certain whether or not I could guarantee a connection 100% of the time. A shame, because otherwise it's perfect.

I do wonder if the plug behaves like this when paired with the official Salus hub. Seems strange to change the power state mid operation.

**Comment by djashjones** [comment]
All my zigbee plugs are the Samsung ST 2019 version

**Comment by incarvr6** [comment]
I know issue is closed but I found that now power reading is out 1 decimal
Total 500w showing as 5kw and load 5w showing 50w

**Comment by incarvr6** [comment]
![Screenshot_2021-12-02-13-14-54-64_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/49254419/144429098-cfe9a629-ec7e-48c5-b17c-63f87a2ea480.jpg)
