### ISSUE TITLE
Support for Samsung Smart Outlet (powerplug)

### ISSUE THREAD

**Issue by clementx2006** [dresden-elektronik/deconz-rest-plugin#819]
requesting through a dedicated post for the ease of tracking (and closing down quickly).  

I have got the UK version but assuming very similar with the ones for other regions. 

This is the plug: https://www.samsung.com/uk/smartthings/sensors-plug-f-app-uk-v2/

Screenshots:
**Clusters of the node** 
<img width="886" alt="screenshot 2018-10-01 at 12 18 53" src="https://user-images.githubusercontent.com/43098079/46286001-64ee8980-c575-11e8-84b7-ad58fedac30d.png">

**Basic cluster**
<img width="874" alt="screenshot 2018-10-01 at 12 20 29" src="https://user-images.githubusercontent.com/43098079/46286018-759eff80-c575-11e8-837e-8b97ab463fc1.png">

**Electrical Measurement cluster**
<img width="842" alt="screenshot 2018-10-01 at 12 22 01" src="https://user-images.githubusercontent.com/43098079/46286021-79cb1d00-c575-11e8-91a1-71f9d54a3992.png">

**On/off cluster**
<img width="925" alt="screenshot 2018-10-01 at 12 29 03" src="https://user-images.githubusercontent.com/43098079/46286064-9d8e6300-c575-11e8-9fa8-a0a699c5ecad.png">

Please let me know if anything else is required. 
reference also #432 where the discussion had started. 

Many thanks in advance!

**Comment by ebaauw** [comment]
The _Power Multiplier_ and _Power Divisor_ values suggest _Active Power_ is 9.5W so _RMS Current_ is 38mA?

**Comment by clementx2006** [comment]
Correct. There was only a Raspberry Pi on the circuit when the measurement was taken.

**Comment by flinthamm** [comment]
Can you confirm what is (if anything) working and what isn't with Deconz/Phoscon? Are you able to at least reliably switch the socket on/off?

**Comment by clementx2006** [comment]
Can switch. But would like to have power current monitoring. And not appear as a light...

**Comment by clementx2006** [comment]
Hello everyone - any update on when the power monitoring will be supported on this smart plug (also not appear as a light in Home Assistant)?

**Comment by stigvi** [comment]
Still nothing?

**Comment by clementx2006** [comment]
Same question as it’s been over a year and Samsung just released a new UK version. The support for usage monitoring is really what’s missing (and could be useful in so many scenarios).

**Comment by clementx2006** [comment]
And not sure how to reopen this...

**Comment by blair287** [comment]
Yea i also want power reporting why can it not do this?

**Comment by smartypantsuk** [comment]
The new 2019 Samsung plug outlet is now partially supported meaning on/off switching and the monitoring of load (watts) is working. The 2019 plug is not the same plug aforementioned in this plug. 

While the plug is working in Deconz on Linux, the Windows version has not been updated yet. 

Full post here.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2121#issue-527681957

**Comment by SwoopX** [comment]
Should work with the next release.

**Comment by smartypantsuk** [comment]
> Should work with the next release.

I'm not sure why the Windows version hasn't been updated in months. Prior to this year, it has been updated multiple times every month thought 2019. There's been no update for nearly 4 months now.

**Comment by SwoopX** [comment]
It's not just Windows, that goes for all of us.
