### ISSUE TITLE
Creating rules for Trust ZYCT-202 

### ISSUE THREAD

**Issue by jnmarczi** [dresden-elektronik/deconz-rest-plugin#823]
Just updated my raspBee to the latest version (2.05.39) and to the latest firmware...  
Added my Trust ZYCT-202 and it's now visible at the ReST api, which is great!!!

As far as i understood, the current selected group of the ZYCT-202 is available at the group property of the sensor's config (values 145 to 149 for groups/lights 1-6, and value 150 for all groups/lights).

The problem IMHO is, that adding a rule condition only works with the state of a sensor,  am I wrong about this? 

is it possible to move the group property to the state of the sensor? or will it be possible to address a config value at conditions in a future version?

**Comment by jee67** [comment]
How did you manage to pair the ZYTC-202? I’m trying for days now, but still no success. I have the latest deconz and firmware version too.

**Comment by jnmarczi** [comment]
Searched for a new sensor at the phoscon app
Removed the battery of the zyct-202 and inserted it again. then pressed & holt the button the 2 bulbs until all leds blinked.

**Comment by jnmarczi** [comment]
Damn, i closed this issue

**Comment by jee67** [comment]
For a ZYCT-202: New sensor or new switch?

**Comment by jnmarczi** [comment]
Think i used "new sensor", but i haven't got a success message from the phoscon app, just the lights of the remote blinked.

**Comment by jnmarczi** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/261
