### ISSUE TITLE
Need advice for 2.4 ghz!!

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#825]
HI, 

This is not related directly to any deconz gateway, but i am facing issues with 2.4 ghz.

I am renting a basement in a house. The whole house is getting good wifi signal ( 2.4 and 5 ghz) everywhere , and the router is installed in the basement.  
But,
In a particular room of the basement, it has big issue  in the 2.4 ghz band, and the Conbee ( on channel 15, (i was on channel 25 before but had the same problem)) too. With wifi I get constant disconnection when I am in this room. 
So... I have installed an Osram plug in this room for testing... and it is almost always unreachable in this room ( in a outlet very near of the entrance door)

I suspect something is interfering here . I have bought a ''lot'' a ''router '' but this do not fix the issue. It is ''funny'' that I get very good signal on the second floor of the house ( which is very far from the router), and in that room ( which is on the same floor..) i get poor signal...

I could somewhat fix the wifi issues with an access point router plugged into a powerline.. 
But for Zigbee, i do not know what to do. 

For now, i am using zwave devices in that room and it works great.

Do you guys have any suggestion for this?

Thanks,
Matt

**Comment by MattL0** [comment]
I would like to use Keen home vent in that room. But, this device is not cheap and i live in Canada. So, if it does not work.. It would be difficult to get a ''full'' refund.

**Comment by MattL0** [comment]
yes

**Comment by MattL0** [comment]
ok thanks for the graph. So i Could try channel 11 Conbee

**Comment by MattL0** [comment]
Can't control the plug with channel 11. is there a possibility to add another conbee ? This would be plugged into a raspberry pi with VirtualHere https://www.virtualhere.com/usb_client_software ?

**Comment by manup** [comment]
> yes

When the WiFi gets unstable it's unlikely that ZigBee is the cause, normally the other way around may happen for example when you stream Musik/Video over WiFi. ZigBee doesn't send enough data to disturb WiFi.

You can check this by just turning of the ConBee, and test if WiFi gets better.

>Can't control the plug with channel 11. is there a possibility to add another conbee ? This would be plugged into a raspberry pi with VirtualHere https://www.virtualhere.com/usb_client_software ?

Multiple ConBee dongles is not recommend since only one can be the coordinato, but you can extend the mesh with every router device like ZigBee lights and plugs.

To be honest I'm a bit confused what exactly is bad, the Wifi connection or ZigBee mesh?

**Comment by manup** [comment]
When you might need more repeaters (Wifi and ZigBee) to improve the signal to the room.
Note: all radio signals get weak when walls and doors contain metal or glass.
