### ISSUE TITLE
Phoscon app design didn't show "new sensor" button on mobile phone

### ISSUE THREAD

**Issue by Counterfeiter** [dresden-elektronik/deconz-rest-plugin#830]
Hi,

I was always using phoscon App with my iPhone SE (safari). I connected all sensors in the light menu with the button "add light". It works, but only sometimes.
I tought it is the way to go. As I displayed the phoscon app on the PC I saw for the first time the "add sensor" button.

![image1](https://user-images.githubusercontent.com/11742338/46519892-560c1d80-c87a-11e8-8b37-7f90a1fa3e1e.png)

Issue #827 is fixed if I use the correct button ;)

**Comment by jjlawren** [comment]
I'm only able to see the button in landscape mode.

**Comment by VoyteckPL** [comment]
> I'm only able to see the button in landscape mode.

That is really annoying. There should be a way to view this button in portrait mode
