### ISSUE TITLE
Safely delete junk data in the deCONZ database?

### ISSUE THREAD

**Issue by ACrazyConcept** [dresden-elektronik/deconz-rest-plugin#833]
I have some old devices which keep coming up in the list and is unreachable even though I have deleted them multiple times via Phoscon.
Is there a safe way to get rid of that junk data in the database?

Edit:
I have realised that it is the smart plugs where deCONZ also creates one or more sensors for power measuring. When the plug is deleted, the associated sensors are left there.

**Comment by ronaldvans** [comment]
+4

**Comment by manup** [comment]
The date is kept in the file `zll.db` this can be edited with tools like sqlitebrowser.

Normally devices should be deleted and stay so when they are deleted in the Phoscon App, I schedule some tests, seems there is somethings missing.

**Comment by mariusmotea** [comment]
I have same issue with some IKEA lights used in the past for some tests. Every time i restart the raspberry the lights are added back and marked as unknow / unreachable. I need to manually delete them every time.

**Comment by peer69** [comment]
Same here, I have some IKEA and OSRAM Light which I used to have, they magically come back every time deconz is restarted.

**Comment by jo-me** [comment]
But even if they stay in state "deleted" there is a problem when repairing those devices again. They are not really re-added but just undeleted which makes it a pain if certain sensors were not discovered on the first paring attempt.

**Comment by dem5867** [comment]
Can't seem to be able to find zll.db (Windows Based.).

**Comment by manup** [comment]
It should be in the user home folder easiest is Windows Explorer file search there for zll.db

**Comment by chimpy** [comment]
My experience with 58 and latest FW:

I had added and removed a Xiaomi round button switch in an earlier version:

<img width="1440" alt="screenshot 2019-02-01 at 13 33 40" src="https://user-images.githubusercontent.com/380577/52123509-a330ae00-2626-11e9-8445-b917665c2c12.png">

It was not visible in the Phoscon webUI. I tried to add it again in 58 to no avail, even after changing the battery. So I opened the zll.db and deleted the offending record:

<img width="1440" alt="screenshot 2019-02-01 at 13 34 14" src="https://user-images.githubusercontent.com/380577/52123553-c52a3080-2626-11e9-9d59-34ea12d508a4.png">

I then restarted deconz and tried to add the sensor. Added straight away:

<img width="1440" alt="screenshot 2019-02-01 at 13 41 56" src="https://user-images.githubusercontent.com/380577/52123650-1508f780-2627-11e9-9e52-15c436ebaa0c.png">

Hope that helps! (All my other sensors seem to be still working with no problems after this intervention).

**Comment by pepijnmm** [comment]
> Can't seem to be able to find zll.db (Windows Based.).
Found mine in: "C:\Users\My username\AppData\Local\dresden-elektronik\deCONZ" (took a while before windows found it so for the next person)

**Comment by mat1990dj** [comment]
So If I understand correctly, somebody needs to manually delete the "deleted" devices from zll.db?
Or even doing so they will reappear?

**Comment by pedolsky** [comment]
The problem is still exists.

**Comment by MattL0** [comment]
Yup

**Comment by BabaIsYou** [comment]
Seems still present #6665 (discovering it thru another issue)
