### ISSUE TITLE
Button editor feature, full brightness when already on

### ISSUE THREAD

**Issue by oscar-b** [dresden-elektronik/deconz-rest-plugin#834]
New button editor work excellent, but it would be nice to be able to set it up so that it turns on when tapped, dims when held but also goes to 100% when tapped when already on. So two taps would always give full brightness, now you need to tap then hold and wait to get to full brightness.

**Comment by manup** [comment]
It kinda is possible already by using a scene. Here is an example with the IKEA Tradfri remote.

* Short button press will call the scene
* The scene is configured to have full brightness, but could be anything
* Long button press will dimm up

![image](https://user-images.githubusercontent.com/383386/46571530-dc0d8e80-c976-11e8-8da6-6ee4dd75ddb9.png)

Dim down could be achieved in the same way on the down button of the remote.

**Comment by oscar-b** [comment]
Hm yeah but I like the fact that it turns on using the previous state as well :)

**Comment by manup** [comment]
Ah ok, interesting idea, it would be possible by adding a specific rule. Might be a good default configuration as well. I'll put it on the internal discussion list. :)

**Comment by oscar-b** [comment]
The “tap when already on” could be configured as “to 100%” or “next scene” perhaps, would work great for the small IKEA remote with two buttons.
