### ISSUE TITLE
busch jaeger light link switches keep on buttonevent:null

### ISSUE THREAD

**Issue by Wyphorn** [dresden-elektronik/deconz-rest-plugin#837]
Hello,

I am new at deconz, but I have a problem and no resolution right now; also searching did not help me.
I have two Busch jaeger light link switches; one 6737, one 6711U.

What I done:
1) reset switches with pressing both top buttons for 5 second until blink stops and they shine permanently. Then I press both top buttons one time and the switch glow up and out. 
2) In Phoscon, I search for new switch, pressing next
3) now I press both top buttons again for 5 seconds (like provided in phoscon dialog) and press next
4) I press both top buttons again
5) after waiting few seconds my zigbee bulbs start blinking and phoscon give me a success message
6) Switch is visible in Phoscon app and with REST I have four sensors:

`"30":{"config":{"group":"18","on":true,"reachable":true},"ep":10,"etag":"5eac160a419137b004b8a0b8a44731f1","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RB01","name":"Wandsender 4-Kanal","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:34:11-0a-1000"},"31":{"config":{"group":"18","on":true,"reachable":true},"ep":11,"etag":"5eac160a419137b004b8a0b8a44731f1","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RB01","name":"Wandsender 4-Kanal","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:34:11-0b-1000"},"32":{"config":{"group":"18","on":true,"reachable":true},"ep":12,"etag":"5eac160a419137b004b8a0b8a44731f1","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RB01","name":"Wandsender 4-Kanal","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:34:11-0c-1000"},"33":{"config":{"group":"18","on":true,"reachable":true},"ep":13,"etag":"5eac160a419137b004b8a0b8a44731f1","manufacturername":"Busch-Jaeger","mode":1,"modelid":"RB01","name":"Wandsender 4-Kanal","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"1.2.0","type":"ZHASwitch","uniqueid":"d8:5d:ef:11:a1:00:34:11-0d-1000"}`

But the buttonevent keeps "null". Even when I press a button.

Version 2.05.26 / 3.5.2018
Firmware 261F0500

Please help me. The WAF for my smarthome is sinking.
I attached two pictures from deCONZ.
![overview](https://user-images.githubusercontent.com/43927600/46583389-6bd63a00-ca56-11e8-8876-4ae8441f56db.png)
![switches](https://user-images.githubusercontent.com/43927600/46583390-6bd63a00-ca56-11e8-8657-bdebbb910764.png)

Best

**Comment by manup** [comment]
I would suggest making a backup of the current setup and try the recent version of deCONZ (currently 2.05.39) there were multiple improvements in regard to BJ switches since 2.05.26. Further with the new version you can use the new switch editor.

**Comment by Daniel0984** [comment]
The new switch editor works like a charm 👍  :)

**Comment by Wyphorn** [comment]
Oh my god. This was tricky.
The support told me to update to deCONZ 2.05.40, so I did today.
I am not sure, this was necessary, but my way to solve the problem:

- reset the switch
- join the network like phoscon tells you
- after joining search for bulbs with the switch with pressing both top buttons for 5s (till they shine) and press right top button 2s
- the switch will blink multiple seconds to find all bulbs in network
- after that - and just after that - the switch buttons will work regularly and will give you a buttonevent.

I will test it tomorrow with my other switch again and give feedback if it's reproduceable.

Best

**Comment by Wyphorn** [comment]
Yes, worked for me with my UP switch too.
Reset, join with phoscon, search bulbs with switch. After I get the events.

Perfect! Hopefully Busch jaeger gives benefit to dresden electronics. Without deconz and phoscon, I would sold my switches and would buy someones of homematic. But

**Comment by Wyphorn** [comment]
Okay... i tried to reproduce again and now the searching for bulbs was not necessary. I have no idea for that.
Maybe the update yesterday for 2.05.40 did the trick alone for resetted switches. I am happy both runs now and I will buy some others for other functionality.

**Comment by Dabbadoeber** [comment]
I have moved from HUE to Deconz
The top rocker switches the light, and works
the buttons how ever do not work. i have about 10 switches.
None of them work with Deconz (Except the top button).
I also use Homeseer here the switches are also listed (Jowihue).
In Homeseer the last event change is logged, but event change do never happen.
i Tried linking lights with the button editor in Deconz, this does not work (scene, on / off)
is there something i am missing ?
Do i have to add a switch in deconz or a light ?
After i add a light/switch does it work right a way or do i have to scan the network ?
