### ISSUE TITLE
Power attribute of Osram Plugs shows up in sensors category

### ISSUE THREAD

**Issue by dghh** [dresden-elektronik/deconz-rest-plugin#841]
Is there any specific reason why the power attribute e.g. Osram plugs (although no real value in) shows up in the sensors category ? 

It makes it awkward to map it in an external application to the depending plug which is in the lights category. Shouldn´t be all primary attributes of a single device in the same category ?

Eg. with motion sensors it is different (and it is good). 
Temperature, motion or lightlevel is in the same category although as different sub-devices. But this is ok. 

Should be the same with the power -"sensor". It should be an attribute or sub-device in the plug category  where the corresponding plug is in.

**Comment by manup** [comment]
Power sensor won't be shown with recent versions, since OSRAM plug doesn't provide meaningful power values.
