### ISSUE TITLE
Bitron 902010/23 4 Key Remote 

### ISSUE THREAD

**Issue by Hypfer** [dresden-elektronik/deconz-rest-plugin#845]
https://www.amazon.de/Bitron-Home-Fernbedienung-902010-23/dp/B00H3NIVLC

Not available via the REST interface. 

![image](https://user-images.githubusercontent.com/974410/46757901-c6c49700-cccb-11e8-9c42-7f8e05bbbc12.png)
![image](https://user-images.githubusercontent.com/974410/46757916-ccba7800-cccb-11e8-9b67-ebc1be4d4660.png)

**Comment by Hypfer** [comment]
This is still unsupported.

**Comment by Hypfer** [comment]
Still relevant

**Comment by joschaschultze** [comment]
I have two of them and would like to use this remote, too!

**Comment by kcdr** [comment]
I have three of them. Would like to use them too.
Please try to support it in REST-API / Phoscon.
Thank you

**Comment by Hypfer** [comment]
Still relevant

**Comment by kcdr** [comment]
For me too.

**Comment by nikolauzi11** [comment]
#2392

**Comment by ebaauw** [comment]
Bloody bot, it has already been closed. @Mimiix: config issue?

**Comment by Mimiix** [comment]
> Bloody bot, it has already been closed. @Mimiix: config issue?

Bot did not close it. OP did.

**Comment by ebaauw** [comment]
@Mimiix Then why is the bot is marking this closed issue as stale.

**Comment by Mimiix** [comment]
@ebaauw Because its retarded? i dont know 😂
