### ISSUE TITLE
Homeseer user. The deconz ip is always changing from local to standar ip.

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#848]
Hi , here is the Homeseer log.  I do not think this is a Homeseer plugin issues... so i post it here.

![capture](https://user-images.githubusercontent.com/27497561/46778772-309c6b00-cce3-11e8-89f0-de55db9b20b4.PNG)

**Comment by MattL0** [comment]
added   ExecStart=/usr/bin/deCONZ -platform minimal --http-listen=192.168.1.3 --http-port=80

to systemd service . Seems to do the tricks. I will report. I do not know why it can't stay on 127.0.0.1

**Comment by MattL0** [comment]
Seems to be ok with 2.05.40?

Will report

**Comment by manup** [comment]
I guess when the Websocket runs in a timeout after no events were delivered for some time, the plugin might close the connection?

**Comment by wvuyk** [comment]
I don't think so from here. The plugin changes IP only based on UPNP calls. I have the impression that when deCONZ runs on the same machine as the plugin UPNP can return both local and network IP? It seems to occur on Linux mainly.

**Comment by ebaauw** [comment]
> The plugin changes IP only based on UPNP calls.
> Seems to be ok with 2.05.40?

There was an issue that deCONZ would advertise the loopback IP address over UPnP, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/759#issuecomment-419644087.

**Comment by MattL0** [comment]
I tried to remove upnp .maybe it was that..

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by MattL0** [comment]
So what should we do?

**Comment by MattL0** [comment]
Up . 

Is disabling the upnp the only solution?

**Comment by manup** [comment]
We need to check the upnp code, and maybe just stick to the eth0 interface IP address.

**Comment by MattL0** [comment]
Just to be sure. Mine is enp4s0, not eth0

**Comment by manup** [comment]
>Just to be sure. Mine is enp4s0, not eth0

My arch linux box also has a different ethernet name, but it should be simple to filter for the ip prefixes to detect the "right" one.

**Comment by KodeCR** [comment]
The #817 pull request under discussion might help here, as it updates gwConfig["ipaddress"] once the network has initialised and that is used for the announce, while I believe the current code doesn't update this and just gets the ip-address each time it's needed for a rest-request without updating gwConfig["ipaddress"]/upnp.
