### ISSUE TITLE
Ikea On/Off button turns off all groups/lights 

### ISSUE THREAD

**Issue by vandalon** [dresden-elektronik/deconz-rest-plugin#853]
The Ikea On/Off button that comes with the new ikea tradfri plug seems to turn on/off all groups/lights in phoscon after connecting, without any configuration.

**Comment by manup** [comment]
Yes, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/846

We need to extend the setup process, so that the group binding happens automatically.

**Comment by ebaauw** [comment]
We need something similar for the innr RC 110 as well, but probably different commands to setup the groups, see #635.  Would that be in the REST API plugin or in Phoscon?

**Comment by vandalon** [comment]
I've tried the binding dropbox but that did not work for me, and after trying all my lights where unreachable, don't know why :) It would be good to have a way to ignore the "to all" broadcast. I use the switches, without binding them to groups, within home assistant. So I don't "need" to bind them to any groups.

**Comment by manup** [comment]
>We need something similar for the innr RC 110 as well, but probably different commands to setup the groups, see #635. Would that be in the REST API plugin or in Phoscon?

Should be done in the REST-API, for the Bush Jaeger switches it is done in functions:
```
checkSensorBindingsForClientClusters()
checkSensorGroup()
```

>I've tried the binding dropbox but that did not work for me, and after trying all my lights where unreachable, don't know why :) It would be good to have a way to ignore the "to all" broadcast. I use the switches, without binding them to groups, within home assistant. So I don't "need" to bind them to any groups.

A group cast to all can't be ignored :) the only way to workaround this is to create a binding.

**Comment by Kendobendo** [comment]
Any update on when deconz will officially support the new IKEA on/off remote?

**Comment by jurriaan** [comment]
I've got the same issue, but it only shows them as on in the API/Phoscon and after a while it detects they are not really on and one by one they 'turn off' in the API again.

**Comment by cappadanna** [comment]
Is it possible to use the Deconz app to create a binding between the on/off switch and a light? I’m new at this and don’t understand the group thing.

**Comment by Thomas-Vos** [comment]
I tried to bind the on/off switch to a group, it shows successful, but the API and Phoscon still shows it toggles all the lights. Is there anything I can do to get these switches supported in deCONZ?

**Comment by ebaauw** [comment]
You probably need to use the dimmer after binding it.  The REST API plugin only sets `config.group` when it sees the dimmer issues a group command.

**Comment by manup** [comment]
Per default the dimmer just broadcasts to the whole network, hence all lights react.
When a group binding is created the dimmer will only use that group.

Currently this isn't done automatically, I hope to get access of the switch in the next days and will add
the automatic binding so the dimmer is working more usable.

**Comment by Thomas-Vos** [comment]
Thanks for the quick replies. I pressed the buttons while it was binding, and a few times when the binding was complete, but the REST API still shows group `0` for the sensor: 
```
{
	"config": {
		"alert": "none",
		"battery": 87,
		"group": "0",
		"on": true,
		"reachable": true
	},
	"ep": 1,
	"etag": "7341a3579ba5348584aea3d1da718e0c",
	"manufacturername": "IKEA of Sweden",
	"mode": 1,
	"modelid": "TRADFRI on/off switch",
	"name": "TRADFRI on/off switch ",
	"state": {
		"buttonevent": 1002,
		"lastupdated": "2019-01-20T18:06:43"
	},
	"swversion": "1.4.018",
	"type": "ZHASwitch",
	"uniqueid": "d0:cf:5e:ff:fe:d6:f3:33-01-1000"
}
```
It might be that I am doing this wrong. I'm trying to bind the sensor to a group with id `17` I created using the API.
![deconz](https://user-images.githubusercontent.com/11077217/51443354-08f86e00-1ce8-11e9-8a02-559da64eaac5.png)
Does this look correct to you?

**Comment by Thomas-Vos** [comment]
Just did that as well. Again it shows "success" in the binding dropbox but the REST API still shows group 0.

**Comment by ebaauw** [comment]
> Are there any more clusters that need to be bound to the group? I just bound the On/Off and Level Control clusters.

Not that I can think of.

**Comment by Thomas-Vos** [comment]
Thanks @manup for the fix! I can confirm that this commit fixes the issue. A new group is now automatically created for the switch. It is not visible in the Phoscon app, but the REST API does show it.

I am not sure why the manual binding didn't work for me previously, but in the meantime I got that working as well (before your commit). So that was a temporary issue.

**Comment by Kendobendo** [comment]
> > Thanks @manup for the fix! I can confirm that this commit fixes the issue. A new group is now automatically created for the switch. It is not visible in the Phoscon app, but the REST API does show it.
> 
> Cool thanks for testing this. The switch be available within the next two releases in the Phoscon App and the switch editor.

Awesome! I'd like to extend my thanks as well. I'm sure there's a lot of happy campers right now. :)

**Comment by RedUlf** [comment]
Will the support for this be included in next release? It works now but since all paired remotes get the same event id in HA they will all work in the same way or is it some way of changing the event id manually?

The remote is not shown in Phoscon app but exported to HA successfully.

**Comment by manup** [comment]
>Will the support for this be included in next release?

Yes, group and Phoscon App + switch editor support is implemented and works very well. Hope to get the new version out in the next two days. 

![image](https://user-images.githubusercontent.com/383386/51938361-2a0a3e80-240d-11e9-96d9-2b51719d3e87.png)

**Comment by manup** [comment]
>Add it as generic switch works fine!

Yes, currently there is no setup wizard for the IKEA on/off switch, so it needs to be added as *Other* switch.

**Comment by spridarn** [comment]
Hi,
Thanks for adding this feature but I am wondering why this button is not integrated the same way as buttons from Xiaomi? I want to use this button for everything and not just IKEA TRADFRI switch or Zigbee lights in my Home Assistant setup. Then I maybe not will be able to group the button and ohter device together in Phoscon App. Wen using Xiaomi buttons I just add them with the Phoscon App and the when pressing the button it creates events that I can listen to in Home Assistant and the do the thing I want in Home Assistant. This IKEA TRADFRI on/off do the same BUT if I don´t add the button to a group it will broadcast message on and off to all lights connected to my Phoscon setup.

**Comment by manup** [comment]
I don't understand, the switch works the same like Xiaomi switches. Events are emitted in the same way.

>BUT if I don´t add the button to a group it will broadcast message on and off to all lights connected to my Phoscon setup.

This is the default mode which the switch uses once entering the network (broadcast to all lights). Since deCONZ version 2.05.58 the group is created automatically when the switch is joined, so it will no longer broadcast to the whole network but only to this (empty) group.

**Comment by HenkeDahl** [comment]
How do you pair this device? I was able to pair one button but have 8 more I want to pair. But non of the other pairs..

**Comment by jo-me** [comment]
So, I've just paired my RC110 with deconz Version 2.05.60 w/firmware 26320500 by adding a new "Other" switch..

What happened is that the paring apparently worked, but Phoscon did not show any indication of that.
Also, the switch did not appear anywhere near the other switches or sensors. 

The API had several (!?) RC 110 listed under sensors. one of them showed updated timestamps when pressing the 1-6 buttons.

The power button of the remote now turns on/off EVERY light in deconz.. 

@manup can you estimate when the remote will be properly supported? And properly configurable via Phoscon?

Thanks

**Comment by alexhardwicke** [comment]
I run deconz 2.05.66 with a Conbee 2 (firmware 26490700) via the docker container.

When I add an IKEA trådfri switch (I have tested with two, both have firmware 2.0.020), no group is created. Pushing buttons on the switch doesn't do anything, though, so maybe this should be a different issue, but the main issue (no groups being created for the switch) is the same.

I also can't connect custom groups to the switches - when I try to add the switch, there are no buttons for me to select:

![image](https://user-images.githubusercontent.com/6741401/61188551-1aac4400-a681-11e9-8bd7-b5acb6349d5a.png)

**Comment by alexhardwicke** [comment]
> @alexhardwicke ever get this working? I am having same issue.

The latest update to deconz solved it for me, actually, so I'd recommend trying that - that is, v2.05.67.

**Comment by thedannymullen** [comment]
@alexhardwicke thanks I am on .66 version will poke around and see if I can find the next rev.  I thought I was in the beta, need to check my repo settings.

**Comment by alundstroem** [comment]
@alexhardwicke and/or @thedannymullen, is the Ikea Trådfri on/off button working for you guys now? I’m using a ConBee1 (latest fw) and the .69 version of deconz and while able to add the switch as ”other” and having it recognized as Ikea Trådfri on/off I so not get any group created automatically ):

What can I do to resolve this?

**Comment by alundstroem** [comment]
Or... have I misunderstood how deconz is to handle the switch? I am able to add it to existing groups and have it toggle them just fine

**Comment by alexhardwicke** [comment]
@alundstroem I was also under the impression it was supposed to create a group, but just like you, I add the switch to existing groups and as of .67, I can actually configure the buttons (prior to 0.67 you could add the switch but had no way to configure the buttons).

**Comment by alundstroem** [comment]
Ah, good to know I'm not alone @alexhardwicke (:  

Now... if I could just get the IKEA Trådfri Remote to work as it does on its own through deconz as well... (using "<" and ">" to cycle the color loop)

**Comment by pergolafabio** [comment]
i have 2 of those on/off switches, they were packed together with the smartplug
really like those simple on/off switches
can they be bought seperately ?

**Comment by alundstroem** [comment]
@pergolafabio yes they are available separately! I might be a little late in the home automation game (: I think that they were only bundled previously... but for as long as I’ve interested in them they have been available on their own!

**Comment by pergolafabio** [comment]
indeed, after googling, its not in the webshops , but seems its indeed available as : ikea 004.684.32

**Comment by thedannymullen** [comment]
Hello All!  Yes my remotes are working fine even when deconz is not running.  

I have not figured out how to make the color change work yet.  I have not spent time on it though.

**Comment by alundstroem** [comment]
@thedannymullen I just created my own color switching by creating ”close enough” scenens, I got the idea from this issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/601

I’d like to remake it by (somehow) extracting the original scenes that the remote has... but I dont know how...

**Comment by ebaauw** [comment]
The colour (temperature) change buttons send manufacturer specific commands that are only understood by Trådfri lights in factory settings.  These setting are broken when deCONZ configures scenes (or even groups?) on the light.

**Comment by alundstroem** [comment]
Well... Darn it (: thanks for clarification @ebaauw

**Comment by FelixUster** [comment]
> 
> 
> Hello All! Yes my remotes are working fine even when deconz is not running.
> 
> I have not figured out how to make the color change work yet. I have not spent time on it though.

Can you tell me how you got it configured that your remotes still work if deconz is not running? mine are running the latest fw (AFAIK) but they do not create groups on their own. currently I added them as switches using the switch editor. But this only works if deconz is running. So I would be quite interested in your solution as it is what I am looking for

**Comment by thedannymullen** [comment]
@felixuster you have to program through the api.  I posted the command I used in another topic let me look.

**Comment by thedannymullen** [comment]
I can’t find the thread on my phone.  I posted in one of the issues out here the command I used.  
I would suggest a search.

It’s a one line command in the rest api.

**Comment by FelixUster** [comment]
> 
> 
> I posted in one of the issues out here the command I used.
> 
> Here is link you need to bind group. [#1137 (comment)](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1137#issuecomment-526774172)
> 
> It’s a one line command in the rest api.

@thedannymullen thank you very much. 

For someone with the same problem:

Here is everything necessary mentioned:
http://dresden-elektronik.github.io/deconz-rest-doc/

1. get an API Key
2. Check for the ID of the specific tradfri on/off switch

should look somehow like this:
`
  "16": {
    "action": {
      "bri": 127,
      "colormode": "hs",
      "ct": 0,
      "effect": "none",
      "hue": 0,
      "on": true,
      "sat": 127,
      "scene": null,
      "xy": [0, 0]
    },
    "devicemembership": ["43"],
    "etag": "f77f99bd9c267f2d1bae3dfee1d1e44e",
    "id": "16",
    "lights": [],
    "name": "TRADFRI on/off switch ",
    "scenes": [],
    "state": {
      "all_on": false,
      "any_on": false
    },
    "type": "LightGroup",
    "uniqueid": "xx:xx:xx:xx:fe:65:11:76"
  },
`

--> Switch Group id is "16"


3. Get Light id's

GET to `<Gateway IP>/api/<apikey>/lights`
should look somehow like this:
`
  "12": {
    "ctmax": 500,
    "ctmin": 153,
    "etag": "89ce272b42f0e784050ddf3f3bd7b9f6",
    "hascolor": true,
    "manufacturername": "Philips",
    "modelid": "LLC020",
    "name": "hue go",
    "state": {
      "alert": "none",
      "bri": 1,
      "colormode": "xy",
      "ct": 500,
      "effect": "none",
      "hue": 5448,
      "on": false,
      "reachable": true,
      "sat": 233,
      "xy": [0.5639, 0.3904]
    },
    "swversion": "5.127.1.26420",
    "type": "Extended color light",
    "uniqueid": "xx:xx:xx:xx:xx:0c:54:f6-0b"
  },
`

--> Light id is "12"

4. Add light(s) to group (the on/off switch)

( Check "Set group attributes" in the documentation )

PUT to `<Gateway IP>/api/<apikey>/groups/<group id>`

with body:

`
{
    "lights": [ "<light id>" ]
}
`
PS: It might be necessary to add "http://" in front of the Gateway IP

**Comment by thedannymullen** [comment]
Thanks for summarizing!

**Comment by capellavacancies** [comment]
Hello guys I've been trying to pair this remote with my conbee2 but I didn't succeed. 
I tried with the generic option, reset the remote pressing 4 times (red blinks) than start flashing slowly but deconz can't see it !
I've got deconz installed as an addon on hass.io installed inside docker on ubuntu.
Everything is last version, the phoscon webui is able to see a "light" that doesn't do anything but can't see this switch. This is the square one, not the round one

any idea ?
It's my second zigbee remote and I already had to send back the first one (osram smart+ mini) because it wasn't compatible with this implementation of zigbee.
Do you think that it could work with ZHA ?

thanks

**Comment by Elvys8** [comment]
> I've a question regarding this on/off switch. It's not an option for me in the GUI to choose. Have I done something wrong?
> 
> ### Solved
> Add it as generic switch works fine!
> 
> `pi# lsb_release -a No LSB modules are available. Distributor ID: Raspbian Description: Raspbian GNU/Linux 9.6 (stretch) Release: 9.6 Codename: stretch `
> 
> ![screenshot from 2019-02-03 11-23-59](https://user-images.githubusercontent.com/250092/52175618-ab175c00-27a6-11e9-992b-3284c79b8644.png)
> 
> I only have those two switches available:
> ![screenshot from 2019-02-03 11-24-19](https://user-images.githubusercontent.com/250092/52175621-b1a5d380-27a6-11e9-8cc7-0db6e92fba82.png)

@flysen
How did you pair it? I have the same options as you, but even as a generic switch nothing seems to happen. I've tried tu push the link button from 1 to 30 seconds with no success…

**Comment by Bond246** [comment]
Hello,
i want to reopen this topic while i get problems with this switch after using it very long time without any issues.

In my general configuration deconz is just the bridge to talk to my zigbee devices via Node-Red. So i don't use groups in general.
Some days ago my this switch stopped working because of low battery. Today i changed the battery but the switch was still not working. So first idea was to update my deconz container to latest stable -> no changes.
Ok then i removed the switch from phoscon and started a new connection process. Without any problems i saw the switch again, i saw all button events in my node-red but then i saw that it always seems to change the on/off-state of a device in deconz, from devices and from groups.

In combination with my node-red that works based on the device states this makes a big problem.

So se question is how can i get this tradfri switch again just sending its state instead of switching the device states in deconz :)

**Comment by Mimiix** [comment]
> Hello, i want to reopen this topic while i get problems with this switch after using it very long time without any issues.
> 
> In my general configuration deconz is just the bridge to talk to my zigbee devices via Node-Red. So i don't use groups in general. Some days ago my this switch stopped working because of low battery. Today i changed the battery but the switch was still not working. So first idea was to update my deconz container to latest stable -> no changes. Ok then i removed the switch from phoscon and started a new connection process. Without any problems i saw the switch again, i saw all button events in my node-red but then i saw that it always seems to change the on/off-state of a device in deconz, from devices and from groups.
> 
> In combination with my node-red that works based on the device states this makes a big problem.
> 
> So se question is how can i get this tradfri switch again just sending its state instead of switching the device states in deconz :)

Please check https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/What-you-can-do-when-a-switch-turns-(almost)-all-devices-on-off

Otherwise, ask on the forums :)
