### ISSUE TITLE
Supporting stop feature of Xiaomi Window Covering Cluster on API

### ISSUE THREAD

**Issue by cnrd** [dresden-elektronik/deconz-rest-plugin#858]
Hi

I'm not sure if this is already possible but:

Would it be possible to expose the stop feature of the Window Covering Cluster through the API?

**Comment by ebaauw** [comment]
Yes, that's possible, and it's already implemented.  Set `state.bri_inc` to 0.

**Comment by Kane610** [comment]
Does that command work on all devices or does it require specific support @ebaauw?

**Comment by ebaauw** [comment]
`bri_inc` should work for all `/lights` resources that have `state.bri`.  Normally, it generates the ZigBee _Move_ command to the _Level_ cluster.  For window covering devices, value `0` generates the _Stop_ command to the _Window Covering_ cluster.

**Comment by Kane610** [comment]
Great! Thanks for the info!
