### ISSUE TITLE
colormode is missing from group doc 

### ISSUE THREAD

**Issue by donnib** [dresden-elektronik/deconz-rest-plugin#86]
Hi,
I can see that the REST API returns a `colormode` but i can't set it or there is no doc about this.

**Comment by ebaauw** [comment]
`colormode` is read-only.  It reflects how the light or group colour was last set: using `ct`, using `hue` and `sat` (`hs`) or using `xy`.  Indeed it's missing from the documentation for /groups, but it's documented for /lights.

**Comment by donnib** [comment]
Yes i know but it's not shown for `groups` and also does it make sense ? Since i can use `ct` only. I don't know how this works when you have lights that support different `colormode` hmmm

**Comment by manup** [comment]
In my opinion it doesn't make sense, since all lights in the group need to be of same type and all set to equally color (and color mode), which is rarely the case.

**Comment by manup** [comment]
Closing this for now.
The lights state `colormode` is documented here: http://dresden-elektronik.github.io/deconz-rest-doc/lights/#getstate

As mentioned for groups colormode won't be implemented.
