### ISSUE TITLE
Version information under "help" in Phoscon Webapp

### ISSUE THREAD

**Issue by tubalainen** [dresden-elektronik/deconz-rest-plugin#860]
Is it me being a "n00b" to decondz, cause I cannot find anywhere in the GUI where I can read the current version of Deconz?

If my statement is true, then please add "Version: XXXX" under the help menu. :)

(I am using the Home Assistant Community container by @marthoc )

Thanks!
![image](https://user-images.githubusercontent.com/26795429/46913623-299a8480-cf91-11e8-84af-b0d4c857675f.png)

**Comment by manup** [comment]
Try Settings > Gateway :)

**Comment by tubalainen** [comment]
Oh okay, thanks @manup !

Thought that "version" refereed to the conbee hardware and not the deconz software.

May I still suggest that the version information regarding Deconz should be moved to "settings -> help"?
