### ISSUE TITLE
PWA WiFi settings screen issues on iPad

### ISSUE THREAD

**Issue by the-ress** [dresden-elektronik/deconz-rest-plugin#861]
I have 2.05.40 and the wifi settings screen show escaped `&mdash;` and the layout has some issues.

It’s also weird it says “active”, but I never activated it.

![fa787fa6-e7ed-4163-b84e-afa046a114f6](https://user-images.githubusercontent.com/1612377/46916230-046d3c80-cfb8-11e8-9437-5f7af524a261.jpeg)
![9d4a2fe9-c929-4fac-8ab0-f39efb7955dd](https://user-images.githubusercontent.com/1612377/46916231-0505d300-cfb8-11e8-9c09-7ed09eebcbda.jpeg)

**Comment by manup** [comment]
Indeed that looks like portrait mode wasn't checked.
We are currently working on a complete rewrite of WiFi settings for deactivated, access point- and client modes, the ui should be fixed then.

>It’s also weird it says “active”, but I never activated it.

There is a humble detection of wifi/networking configurations which not controlled by Phoscon App, the active here only means there is "something" active or configured and the screen is a extra step to allow 
 Phoscon to overwrite it.

**Comment by manup** [comment]
Closing this for now, new WiFi settings are available since 2.05.55.
