### ISSUE TITLE
lumi.sensor_switch and lumi.sensor_magnet not reporting battery.

### ISSUE THREAD

**Issue by cnrd** [dresden-elektronik/deconz-rest-plugin#863]
Any chance it would be possible to add battery reports for those two devices? Both of them report their battery status when connected to the Xiaomi gateway, so the data must be there somewhere?

These are both Xiaomi devices, one is the round one button switch, the other is the door/window sensor with rounded corners.

**Comment by manup** [comment]
This should work with current versions. Closing the issue for now in favor to newer issues related to these devices.
