### ISSUE TITLE
GE Zigbee Appliance Control Switch (45853GE) 

### ISSUE THREAD

**Issue by wayneflo** [dresden-elektronik/deconz-rest-plugin#868]
GE has an excellent wall plug called the GE Appliance Control (45853GE). I would appreciate you adding it to your supported device list.  Here is the basic info.  It is likely a similar footprint to the GE Smart Switch (45856GE), Issue 1058) and the GE Smart Dimmer (45857GE, Issue 891).

Product info and spec is here: https://byjasco.com/products/ge-zigbee-plug-smart-switch

![image](https://user-images.githubusercontent.com/44179318/47264177-360d6880-d4ce-11e8-8bd0-38242432963b.png)

![image](https://user-images.githubusercontent.com/44179318/47264169-0eb69b80-d4ce-11e8-9029-538d29053401.png)

![image](https://user-images.githubusercontent.com/44179318/47264279-e11f2180-d4d0-11e8-9b0f-c87a12ac0cd9.png)

![image](https://user-images.githubusercontent.com/44179318/47264295-352a0600-d4d1-11e8-94af-4b4f01385a23.png)

![image](https://user-images.githubusercontent.com/44179318/47264304-54c12e80-d4d1-11e8-83fc-7e73de1ff8e6.png)

![image](https://user-images.githubusercontent.com/44179318/47264313-7a4e3800-d4d1-11e8-9e09-3285911f62b8.png)

**Comment by ebaauw** [comment]
The GE in-wall dimmer has almost the same fingerprint, see #891.

**Comment by wayneflo** [comment]
I suspect the GE in-wall smart switch, 45857GE, is also the same footprint.  I don't have one to post the info.
