### ISSUE TITLE
Very (very) difficult to add devices on a Ubuntu NUC and Conbee, better on a Windows 10 laptop, how to backup/restore  database between the two?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/deconz-rest-plugin#869]
Hi, I am trying to add devices on a Conbee attached to a Ubuntu NUC, but it is very very complicated, in order to add I have to try 20+ times, and the device has to be very close to the NUC. Problem is that I have 100+ devices in the house, and can't move many of the devices (xiaomi sensor attached to door and windows), or move the NUC.

Hence I am using a laptop windows 10, which works a bit better (to add devices I need to try 3-5 times), and of course I can move the laptop around the house and go near devices to add them to the mesh.

Like this I added 5 devices, then I backed-up the configuration. I then removed the Conbee, attached it to the Ubuntu-NUC and restored the previous configuration from the Phoscon app.

But its not working, the configuration is not loaded.
Am I missing something?

Is it because I use Phoscon app from a different machine to iupload the configuration file, or?

**Comment by ebaauw** [comment]
I don't have much experience doing a restore, but the few times I tried it, it didn't run as smoothly as I'd hoped.  Make sure you have the same version of deCONZ on both machines.  Also, you might need to restart deCONZ after the restore.

You can use a USB extension cable (Female-A to A) to bring the ConBee closer to the devices without moving the NUC nor the device.  It might be a good idea even when not pairing new devices - I've seen several reports of ConBee not having optimal radio reception when plugged into a host directly.

I strongly advice to run deCONZ in full graphical mode, even on a headless server.  Use VNC or similar software to interact with the deCONZ GUI.  That way you can check whether the device has joined the network and force-read the _Basic_ cluster attributes to trigger the creation of the REST API resource.  Without the GUI, it's sort of hit and miss if the REST API resource is created after the device has joined the network, especially for battery powered end devices.

**Comment by Klagio** [comment]
Please note that one machine ia PC-Windows 10 machine and the other is a PC/NUC-Ubuntu.

I tried with an extension (40cm) but it does not help, in any case I can't move the NUC into other rooms (for example to pair Xiaomi sensor attached to doors and windows ...., and also some Hue bulbs are mounted in ceiling lamps, plus Dresden Fslp in recessed LED streips, almost impossible to move from ceiling); I rather use the laptop which I can move up to the ceiling .....

Tried to have deCONZ GUI on the Ubuntu but its NOT starting, I have opened another issue about this in github. That's why I wished to do everything with the laptop (easy to move around and deCONZ GUI working fine), and then move the database to the final server: the Ubuntu NUC

**Comment by MattL0** [comment]
How do you keep a headless install and be able to see the gui with vnc? 

I also tried get the gui working on ubuntu but no luck .

**Comment by Klagio** [comment]
I managed to see the GUI in Ubuntu. My problem was some dependencies missing.

Then to make it start from terminal (opened from Ubuntu desktop) type 
deCONZ

**Comment by SwoopX** [comment]
You can have the deconz GUI on a headless setup via SSH xforwarding. If enabled and all is configured correctly, uyou just run deconz command via ssh and the GUI will be rendered by the corresponding program locally.

This one is definitively missing in the wiki :)

**Comment by MattL0** [comment]
+ 1 for the wiki :)

**Comment by manup** [comment]
SSH forward can be useful (albeit I prefer VNC) if you like you can add a page for the SSH X forwarding to the wiki.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki

**Comment by SwoopX** [comment]
Yeah, got it...
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Access-deCONZ-GUI-in-headless-setups

**Comment by Shaolo** [comment]
With the import/export functionality updated, is this now possible?

When I swap my Conbee stick from my PI to my Windows machine and input the password for the Phoscon gateway, it won't let me in.

**Comment by manup** [comment]
I'm afraid due the different platform the password needs to be set again.

**Comment by Shaolo** [comment]
If I reset the gateway password, does that destroy the connections the conbee has made on the PI? Or do I reset, restore and I can do that to swap between platforms at will?

**Comment by manup** [comment]
It will just update the password on the machine where deCONZ is running. All other data stays untouched. Linux and Windows use different mechanics to store the password that why currently this can't be reused on another platform.

**Comment by Shaolo** [comment]
I should ask how that is done then.

**Comment by manup** [comment]
There is a forgot password function on the Phoscon App login page.

**Comment by Klagio** [comment]
> Maybe this would work better in your situation:
> #843
> 
> The idea is that USB device communication is sent over the network and programs interact with those devices as if they were locally connected.
> 
> If you had a battery powered RPI with the conbee that forwards everything to your NUC then you could walk around with it for pairing.
> Have not tried it personally but sounds promising.

I solved by using the Conbee an a Raspberry pi3 which has deCONZ. I then use the deCONZ  integration feature in Home Assistant (which is hosted on the NUC) to have all entities in Home Assistant. Works perfectly
