### ISSUE TITLE
Raspbee configuration reseted

### ISSUE THREAD

**Issue by mat1990dj** [dresden-elektronik/deconz-rest-plugin#872]
After investigating some issues I've found that my configuration inside deconz seems invalid:

![image](https://user-images.githubusercontent.com/5220059/47025754-62d71e00-d164-11e8-8413-790eea422872.png)

How can I get the default values? or previous values?

**Comment by manup** [comment]
Doesn't look like deCONZ has retreived the configuration at all.
Is the RaspBee connected and visible as node?

**Comment by mat1990dj** [comment]
Yes... :(

![image](https://user-images.githubusercontent.com/5220059/47026560-05dc6780-d166-11e8-92d3-51a603f8d113.png)

**Comment by manup** [comment]
That's weird, since there seems to be a active network and coordinator has valid mac address.
So when you press *Read* or restart deCONZ is still stays all zero?

**Comment by mat1990dj** [comment]
Yes
I'm thinking I'll have to reset my gateway

**Comment by manup** [comment]
I wouldn't do that. Please first check the zll.db file with the sqlitebrowser and look in the table `zbconf` here all prior configurations are stored.

**Comment by mat1990dj** [comment]
Ok, so I got the configuration from that table and put it into the deconz gui, still missing TC Link Key, can this missconfiguration be the source of various problems?

{"apsUseExtPanId":"0x0",
"curChannel":15,
"deviceType":0,
"extPanId":"0x212effff022ae6",
"fwversion":"0x26240500",
"macAddress":"0x212effff022ae6",
"networkKey":"00f4d0bcfc24f40064b4946440d0d8d8",
"nwkAddress":"0x0",
"nwkUpdateId":0,
"panId":"0xe4be",
"securityMode":3,
"staticNwkAddress":false,
"swversion":"2.05.40",
"tcAddress":"0x212effff022ae6"}

![image](https://user-images.githubusercontent.com/5220059/47030167-75a22080-d16d-11e8-878a-13d0bc0da9ab.png)

**Comment by manup** [comment]
The TC Link Key is normally:

`0x5a6967426565416c6c69616e63653039`

This is the default HA trust center link key (ZigBeeAlliance09) and is used when new devices join the network.

Note in order to apply network settings changes you need to Save > Leave > Join in deCONZ.
