### ISSUE TITLE
How to add Xiaomi wireless switch (round type) 

### ISSUE THREAD

**Issue by claudioita** [dresden-elektronik/deconz-rest-plugin#873]
I am having a hard time adding devices, but with this switch nothing worked so far.

From the phoscon app I clicked sensor add sensor other, the reset the switch with a pin, little blue led starts blinking, I am 5 cm away from the Conbee, and.... Nothing, after few minutes the phoscom tells failed to connect, nothing in the GUI. 

Somewhere I red to wait 10 minutes, but even if phoscom app tells failed to connect need to wait?

**Comment by manup** [comment]
Can you please provide more information:

* deCONZ and firmware version as shown in *Settings > Gateway*
* Switch model identifier as printed on the back

**Comment by claudioita** [comment]
Deconz 2.05.40
Firmware 2.05.39

**Comment by wmn79** [comment]
I have the same and the switch won't show up in the phoscon app. When I push the button I get it as an event in Home Assistant through the rest-api so I can use it in automations etc.  

To pair it unlock the gateway and push the reset/pair button with a pin. Then when the light starts blinking release the reset/pair button. If it starts blinking a couple of times after you released it is paired.

**Comment by claudioita** [comment]
What do you mean by unlock the gateway?

**Comment by wmn79** [comment]
What I mean is when you use the Old WebApp version (accessible through help in Phoscon) and then in Menu => Settings  under "System Settings" you have a button to unlock the gateway. But I think that does the same as when you go through Phoscon and try to add a switch through Add new switch => Other.

**Comment by manup** [comment]
The Unlock gateway button only accepts other apps to connect to the API it isn't used for joining devices.

**Comment by jkerekes99** [comment]
sorry for the noob question...

I have managed to pair the WXKG01LM round button, however as others have said, it doesn't appear in the Phoscon GUI...my question is how do I use it in Home Assistant?

On the HA deconz integration section I can see all the lights and sensors, but none of the buttons show up.

I have rebooted HA and re-paired, still cannot see the button.

**Comment by manup** [comment]
>I have managed to pair the WXKG01LM round button, however as others have said, it doesn't appear in the Phoscon GUI...my question is how do I use it in Home Assistant?

The WXKG01LM isn't supported yet in the Phoscon App. I've ordered two of them to complete integration and fix the long press/release issue.

I'm afraid I won't get the switches before new years eve so ETA is in January 2019.

**Comment by Klagio** [comment]
> I have the same and the switch won't show up in the phoscon app. When I push the button I get it as an event in Home Assistant through the rest-api so I can use it in automations etc.
> 
> To pair it unlock the gateway and push the reset/pair button with a pin. Then when the light starts blinking release the reset/pair button. If it starts blinking a couple of times after you released it is paired.

can you explain how the "rest-api" works, sorry a bit of a newb here

**Comment by wmn79** [comment]
@jkerekes99 [This page](https://www.home-assistant.io/components/deconz/#remote-control-devices) describes how the remote can be used in Home Assistant. It doesn't show up as a device but as an event.

@Klagio You connect your Home Automation software to the rest-api, through the rest-api you can control all devices that are available in deconz. For Home Assistant the description on how it works and should be configured is explained [here](www.home-assistant.io/components/deconz/).

**Comment by Klagio** [comment]
> [This page](https://www.home-assistant.io/components/deconz/#remote-control-devices) describes how the remote can be used in Home Assistant. It doesn't show up as a device but as an event.

ohhh never dealt it without the entity_id .... but what is the name of it remote_control_1  ??
```

platform: event
      event_type: deconz_event
      event_data:
        id: remote_control_1
        event: 1002
```
