### ISSUE TITLE
Xiaomi Aqara contact sensor (LUMI) reports temperature?

### ISSUE THREAD

**Issue by flobernd** [dresden-elektronik/deconz-rest-plugin#882]
Hi there,

I just added a Xiaomi Aqara contact sensor to my deCONZ bridge and noticed that the Phoscon App reports a temperature. The temperature is wrong for my room and does not change at all, so I guess this is a bug?

The exact model name is: `lumi.sensor_magnet.aq2`.

Best regards

**Comment by SwoopX** [comment]
I'd say that the fate for all of us. They have quite an awkward offset.

**Comment by Counterfeiter** [comment]
I think thats the internal temperature of the Zigbee microcontroller. It is not useable for normal measurment. The offsets and linearity is very bad. +- 10 degC is normal
