### ISSUE TITLE
Schedule turning lights on

### ISSUE THREAD

**Issue by m0rph13** [dresden-elektronik/deconz-rest-plugin#886]
The Schedule-panel holds no way to turn lights ON.

**Comment by manup** [comment]
You need to create a scene with the preferred light settings, this way you have full control.

**Comment by m0rph13** [comment]
So I make a scene to set lights etc, and then I use "fade out" to fade in, and "Fading time in seconds" to be "enhancement time in seconds" ?

Would it not make more sense to have the action "Turn Group on" as an alternaitve to "Turn Group off" ?
