### ISSUE TITLE
GE Zigbee Smart Dimmer Switch (45857GE)

### ISSUE THREAD

**Issue by wayneflo** [dresden-elektronik/deconz-rest-plugin#891]
GE has an excellent smart dimmer switch called the GE Smart Dimmer (45857GE). This is a powered light switch that replaces a standard wall switch. I would appreciate you adding it to your supported device list.  It likely has the same footprint as the GE Smart Switch (45856GE), Issue 1058) and the Appliance Control Switch (45853GE, Issue 868).

![image](https://user-images.githubusercontent.com/44179318/47270561-c083b580-d52a-11e8-8398-d05ee0268751.png)

![image](https://user-images.githubusercontent.com/44179318/47269728-3da92d80-d51f-11e8-8b39-f12ab535b69d.png)

![image](https://user-images.githubusercontent.com/44179318/47269764-a09ac480-d51f-11e8-9028-957d68516e1f.png)

![image](https://user-images.githubusercontent.com/44179318/47269772-bdcf9300-d51f-11e8-943c-acb2a167c528.png)

![image](https://user-images.githubusercontent.com/44179318/47269775-ce800900-d51f-11e8-9a00-2df394769505.png)

**Comment by ebaauw** [comment]
Please provide a screen shot of the _Node info_ panel, see 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

It should already be exposed as a dimmable light, to control the wired light(s).  To expose the _Simple metering_ cluster as ZHAConsumption, we need to whitelist the dimmer.  Does it report power (_Instantaneous demand_) in 0.1W and the lifetime consumption _Current summation delivered_ on 0.1 Wh, as the _Divisor_ would suggest?

I expect endpoint 0x02 is used to other smart lights (that are not wired to the dimmer).  The _OnOff_ and/or _Level_ client clusters probably need to be bound to a group for that to work.  If you can find out what commands are sent, we could expose that endpoint as a ZHASwitch.

**Comment by ebaauw** [comment]
The plug should also already be exposed as a `/lights` resource.  For the rest, it looks very similar to the dimmer - we can probably share most of the code.
