### ISSUE TITLE
With beta 42 one of three sensors are back

### ISSUE THREAD

**Issue by heitec11** [dresden-elektronik/deconz-rest-plugin#893]
With Beta 42 now one of my three Xiaomi sensors are back.
[response_42.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2501178/response_42.txt)
See #879

**Comment by manup** [comment]
Closing this issue to keep discussion in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/912
