### ISSUE TITLE
Xiaomi temperature sensor

### ISSUE THREAD

**Issue by oly13** [dresden-elektronik/deconz-rest-plugin#899]
Is the LCD display sensor compatible?

**Comment by rygel** [comment]
The temperature sensor with a LCD does not support Zigbee, but only Bluetooth. So it is not compatible.

**Comment by tomfritz1** [comment]
There is a plug-in for this device in homebridge -> mi-hygrothermograph - works perfectly!

**Comment by flavio20002** [comment]
I use this script, with a MQTT server. Change the xx.

#!/bin/bash

devices=( "4C:65:A8:D2:xx:xx" "4C:65:A8:D3:xx:xx" )
names=("cucina" "camera")

for i in "${!devices[@]}"; do 
    bt=${devices[$i]}
    sensor=${names[$i]}

    battery=$(/usr/bin/timeout 20 /usr/bin/gatttool -b $bt --char-read --handle=0x18 | cut -c 34-35)

    RET=1
    until [ ${RET} -eq 0 ]; do
        data=$(/usr/bin/timeout 20 /usr/bin/gatttool -b $bt --char-write-req --handle=0x10 -n 0100 --listen | grep "Notification handle" -m 2)
        RET=$?
        sleep 5
    done

    temp=$(echo $data | tail -1 | cut -c 42-54 | xxd -r -p)
    humid=$(echo $data | tail -1 | cut -c 64-74 | xxd -r -p)
    batt=$(( 16#$battery ))
    timestamp=$(date +"%Y-%m-%dT%H:%M:%SZ")

    if [[ "$temp" =~ ^[0-9]+(\.[0-9]+)?$ ]]
    then
        docker exec mosquitto mosquitto_pub -r -u flavio -P vegeta -t "homeassistant/xiaomi/$sensor" -m "{\"date\":\"${timestamp}\",\"temperature\":\"${temp}\",\"humidity\":\"${humid}\",\"battery\":\"${batt}\"}"
    fi

done

**Comment by manup** [comment]
Closing this issue since not related to Zigbee.
