### ISSUE TITLE
Sensor config.on not implemented?

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#90]
When I set a sensor's `config.on` attribute to false, it's state continues to be updated.  On the Hue bridge, setting `config.on` to false blocks updates to the sensor state.  This is used by the Hue app to disable the Hue motion sensor.

**Comment by manup** [comment]
Added to the todo list. Currently this is only possible by disabling the rules. The `config.on` makes sense and simplifies the task.

**Comment by ebaauw** [comment]
Still on the list, I hope.

**Comment by manup** [comment]
I thought this is already working :) need to check, so basically rules shouldn't be processed when the sensor is off. Should web socket events also be stopped?

**Comment by ebaauw** [comment]
If memory serves, the Hue bridge sets the `state` attributes to `0` or `null` or `"none"` or something and no longer accepts PUTs to CLIP sensors `state`.

**Comment by manup** [comment]
Ok guess this should be compared in more detail, can be handy to disable some automations without messing too much with the existing rules.

**Comment by ebaauw** [comment]
Bump

**Comment by ebaauw** [comment]
Bump

**Comment by ebaauw** [comment]
Not solved.

**Comment by ebaauw** [comment]
I suppose we just need to document that setting `config/on` only disables firing of rules.
