### ISSUE TITLE
Websocket sensor message does not contain unique id / mac address

### ISSUE THREAD

**Issue by mapero** [dresden-elektronik/deconz-rest-plugin#900]
Hi,

I noticed, that the websocket messages do not contain the mac address / unique id. The internal id is not sufficient and robust enough. (Deconz database was corrupt and I had to pair sensors again and also remap ids in all my applications).

A unique identifier would be much more robust.

Can you add the unique identifier to the websocket message?

Thanks.

**Comment by mapero** [comment]
Perfect, thank you. :blush:

**Comment by manup** [comment]
:) could be handy.

Closing the issue for now.
