### ISSUE TITLE
Orvibo Smoke Sensor

### ISSUE THREAD

**Issue by alonalon** [dresden-elektronik/deconz-rest-plugin#901]
Hi,
Would appreciate if someone could look into add support for [Orvibo Smoke Sensor.](https://www.orvibo.com/en/product/smoke_sensor.html)

I run everything on headless Linux server, so can't provide any cluster info unfortunately. 
But I think it's very much like [Trust smoke detector](https://www.trust.com/en/product/71197-zigbee-smoke-detector-zsdr-850) & [Heiman HS1SA Smoke detector](http://www.heimantech.com/product/96.html)

Maybe all those three devices can share most of the code?

**Comment by jonatanhost** [comment]
I have the same device connected but not recognized. Here is a screenshot of node info.

![image](https://user-images.githubusercontent.com/11466166/47442603-e3c09600-d7b2-11e8-8106-0c4a85fecedb.png)

**Comment by jonatanhost** [comment]
@manup Do you guys need more information from us of this smoke sensor to implement it?

**Comment by manup** [comment]
>@manup Do you guys need more information from us of this smoke sensor to implement it?

Some more screenshots as described here would be useful, especially `model identifier` from basic cluster is needed.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by alonalon** [comment]
@jonatanhost is it possible for you to get the info manup asks for?

**Comment by jonatanhost** [comment]
> > @manup Do you guys need more information from us of this smoke sensor to implement it?
> 
> Some more screenshots as described here would be useful, especially `model identifier` from basic cluster is needed.
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

I don't know how to get those attributes to show

**Comment by alonalon** [comment]
<img width="550" alt="screenshot 2019-02-06 at 20 37 59" src="https://user-images.githubusercontent.com/3322693/52368696-59452f00-2a4f-11e9-9796-4b3824db1e49.png">

think i got it, does this help @manup ?

**Comment by jonatanhost** [comment]
@manup 

Do you guys need any more information about the device or is this enough?

**Comment by jonatanhost** [comment]
@manup Hi, do you have any status on this? Have two sensor myself of this I would like to use as not just dumb smoke sensors :)

**Comment by manup** [comment]
Hi, sorry for the late reply. Yes one more thing, please provide a screenshot of the IAS Zone cluster after reading the attributes.

The modelid looks a bit random so it would be helpful if we can pin point the sensor via its IAS cluster attributes.

**Comment by alonalon** [comment]
<img width="408" alt="Screenshot 2019-05-02 at 17 48 47" src="https://user-images.githubusercontent.com/3322693/57088603-eae8d380-6d02-11e9-94ee-e6b21e006aa9.png">

<img width="404" alt="Screenshot 2019-05-02 at 17 51 48" src="https://user-images.githubusercontent.com/3322693/57088739-3602e680-6d03-11e9-84b1-d6e1a356a34e.png">


Got two different result for same device, the values changed during pairing process in deconz, don't know which is right

**Comment by alonalon** [comment]
@manup any news about this? :)

**Comment by alonalon** [comment]
#1763 adds support for this, closing

**Comment by arnonel** [comment]
Could we add SF21 smoke sensor please

**Comment by mn26826** [comment]
I opened a new issue for this device in #1875 .
