### ISSUE TITLE
Update description_in.xml in the deCONZ package

### ISSUE THREAD

**Issue by KodeCR** [dresden-elektronik/deconz-rest-plugin#902]
Hi @manup,

Can you please update the description_in.xml that is installed by de deCONZ package .deb to /usr/share/deCONZ/webapp/ to the one in the repository (that was part of #818). The old one doesn't currently get the serialNumber set correctly (and the new one is updated to match what the v2 HueBridge provides).

Thanks

**Comment by manup** [comment]
Thanks, updated it in 2.05.44. Would be cool if anyone can confirm that Alexa discovery still works (not sure if it uses description.xml).

**Comment by KodeCR** [comment]
I have an Echo so I checked this and it indeed uncovered some bugs. With the above fixes I'm able to discover and import devices.

**Comment by KodeCR** [comment]
Thanks
