### ISSUE TITLE
Ubuntu (x86_64) build of 2.05.43 missing

### ISSUE THREAD

**Issue by jurriaan** [dresden-elektronik/deconz-rest-plugin#908]
https://www.dresden-elektronik.de/deconz/ubuntu/beta/deconz-2.05.43-qt5.deb is not there.

**Comment by jurriaan** [comment]
@manup http://www.dresden-elektronik.de/rpi/deconz-firmware/ is also missing the latest firmware files

**Comment by manup** [comment]
Hi, Ubuntu version will be up tomorrow with some fixes for current config limbo.

>@manup http://www.dresden-elektronik.de/rpi/deconz-firmware/ is also missing the latest firmware files

Nope, all there but alpha numeric ordering :)
Please check the *Last modified* sort indicator.

**Comment by MattL0** [comment]
Firmware : http://www.dresden-elektronik.de/rpi/deconz-firmware/deCONZ_Rpi_0x262d0500.bin.GCF

**Comment by jurriaan** [comment]
@manup ah, oops :) ordering was the problem here 😅. Thanks!
