### ISSUE TITLE
Switch editor support for Xiaomi Cube

### ISSUE THREAD

**Issue by the-ress** [dresden-elektronik/deconz-rest-plugin#909]
Hi, is there any ETA for Xiaomi Cube support in the Phoscon switch editor? Thanks.

![image](https://user-images.githubusercontent.com/1612377/47608468-92bcd600-da2e-11e8-9b45-eee83ebbd259.png)

**Comment by manup** [comment]
Sadly no real ETA (I hope early 2019), we have a concept but need to figure out some stability fixes and the "normal" light switches range of Xiaomi first.
