### ISSUE TITLE
PWA cant be accessed with Safari Browser

### ISSUE THREAD

**Issue by peer69** [dresden-elektronik/deconz-rest-plugin#910]
Desktop Version of Safari gives me "Login failed" errors since updating to 2.05.43 when trying to access pwa. Mobile Safari starts searching for gateways, doesn't show any available gateways at all. 
Firefox and Chrome work fine. Clearing caches in Safari didn't work.

**Comment by peer69** [comment]
Port 80. I‘m using the preconfigured raspberry image which I updated to the latest version.

**Comment by peer69** [comment]
After updating to 2.05.44 and waiting for some time the interface can be accessed again with both safari desktop and mobile. Not sure what the issue was though.

**Comment by manup** [comment]
Interesting, might have also been a cache problem.

**Comment by balu-** [comment]
It seems i have the same problem,
using 2.05.46. Neigther on desktop nor on iphone pwa's discovery finds the gateway.
Is there anyway to tell it the ip manualy?

**Comment by manup** [comment]
Hmm interesting which port is your gateway running?

You can try two things:

1) Open PWA directly over IP and port

    http://192.168.90.33:8022:/pwa/login.html

2) Give it explicit hint about the gateway

    http://192.168.90.33:8022:/pwa/login.html#host/192.168.90.33:8022

**Comment by balu-** [comment]
thanks for your reply, im running the gateway on port 80.

unfortunately both tricks did not work, I looked at the Safari dev console, it seems https is tried and fails (tried ip and path matches)

     [Error] Failed to load resource: Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden. (config, line 0)

**Comment by manup** [comment]
That's true currently only http is supported, there was another issue in regard to a reverse proxy which required https, that will be supported in coming releases

**Comment by balu-** [comment]
interessting, just to be clear my gateway runs only http on port 80. Seems there is a problem why safari tries to request https (firefox does work, so not that big of a deal. But using it on ios would be nice)

**Comment by svenove** [comment]
@balu-: 
Are you running something else on the same host/domain name? I experience the same due to forced HTTPS on other ports on the same server.

**Comment by balu-** [comment]
@svenove oh interessting hint, thanks! I do run my own top layer on top of deconz-rest api that runs on the same machine. It does not use https but is running a python http server on port 8080 besides the deconz-rest api. I will stop the other service and report if that was the reason for the problem.

**Comment by balu-** [comment]
I deleted all local data, stoped the webserver on port 8080 of the same host  and tried again to use pwa on safari (ios / macos).
Unfortunately finding the gateway did not work.
I also tried hinting the js app where the gateway was like @manup described - also didn't work.

**Comment by manup** [comment]
The login and scanner code is now improve to better handle https / 80 / 443  hosts.
Will be available in .48.

Related issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/702
