### ISSUE TITLE
new device Aqara Wall Switch (WXKG03LM) Multistate cluster 12

### ISSUE THREAD

**Issue by wassfila** [dresden-elektronik/deconz-rest-plugin#915]
I got a new aqara switch 0x00158D00028CAD58 that I could not pair with phoscon, then I realized that it's actually paired with deconz and when I press it reports to deconz on cluster 12. It does not even has a cluster 6 (On Off).
Actually I had a previous aqara switch 0x00158D00024B3E45 pairing with phoscon displayed there, and reporting in the webapi. That old switch is reporting on cluster 6 (Of Off) that the new one does not have.
For the new one, I could not read any attribute even pressing read and switch click many times.

Should this be handled as a new device request or is there a change required to deconz to handle the cluster 12. I'm not sure how this relates to the special handling of Xiomi devices, I started reading the of the rest 

plugin code but still a bit lost in what is specified in the general.xml, what is coded in deconz and what is xiomi custom.

![2018-11-01-152031_1435x905_scrot](https://user-images.githubusercontent.com/1510763/47858604-bdbb7700-ddec-11e8-87d2-89bf78974ccc.png)

![2018-11-01-152314_1435x914_scrot](https://user-images.githubusercontent.com/1510763/47858620-c7dd7580-ddec-11e8-851e-feee47be4558.png)

![2018-11-01-152436_1435x914_scrot](https://user-images.githubusercontent.com/1510763/47858627-cd3ac000-ddec-11e8-92a9-126a70166e38.png)

extracts from logs

log with "deCONZ --dbg-info=1 --dbg-aps=1 --dbg-zcl=1 --dbg-zdp=1"

`15:26:08:318 ZCL attribute report 0x00158D00028CAD58 for cluster 0x0012, ep 0x01

15:26:08:398 ZDP status = 0x00 -> SUCCESS
`

[request_device_support.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2538888/request_device_support.log)

log with more options
`13:03:36:254 APS-DATA.indication srcAddr: 0x00158d00028cad58, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0012, lqi: 255, rssi: -16

13:03:36:254 	asdu: 18440a5500210100

13:03:36:254 ZCL attribute report 0x00158D00028CAD58 for cluster 0x0012, ep 0x01

13:03:36:254 	payload: 5500210100

13:03:36:254 APS-DATA.indication from child 0x3254

13:03:36:254 Delay APS request diff = 182

13:03:36:254 Node data 0x00158d00028cad58 profileId: 0x0104, clusterId: 0x0012

13:03:36:291 Node 0x00158D00028CAD58 is known by 1 neighbors, last seen 0 s

13:03:36:430 Delay APS request diff = 357
`

If needed the log file with more options
[OpenSwitch_full.log](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2538894/OpenSwitch_full.log)

I would like to give it a try to add the support for this switch myself, for that any hints would be appreciated.

**Comment by ebaauw** [comment]
What’s the _Model Identifier_ in the _Basic_ cluster?  Same as in #890?

**Comment by wassfila** [comment]
I tried a dozen times to click on read attributes, then keep waking up the switch by pressing it, did not manage so far.
It is likely that it is the #890 because we have the same screenshots where the On Off cluster 6 is not there.
I will give it more tries for the read attributes and I will go again through the details of #890 , From the name of the issue I wasn't sure if it's a new device but now that you mentioned I see more similarities.
Note I'm using deconz-dev-2.05.44.deb

**Comment by wassfila** [comment]
Additional info:
- this is a battery powered single switch, I do not have a Xiomi gateway so never updated its firmware.
![20181101_190902_s](https://user-images.githubusercontent.com/1510763/47872026-db4d0880-de0d-11e8-8ff2-f6a21929cc0e.jpg)

- I saw in the debug that it is well reporting on the Multistate Input cluster 12, and in the screenshot the Present value updated to 1, but contrary to #890 the Number of states is 0 not 6.
![cluster_12_states_0](https://user-images.githubusercontent.com/1510763/47872088-06cff300-de0e-11e8-94b7-a37db9d586c7.png)

So if I understood #890 right, same here, the model would have to be whitelisted and a buttonmap created.
I'll dig now in the deconz plugin to see if I can understand how to edit that.

**Comment by ebaauw** [comment]
> #890 has .b286 instead of .b186 not sure if that changes everything.
> this is a battery powered single switch

Probably the difference single vs dual switch.  Typically they share the same firmware, and they would be exposed as the same, as a ZHASwitch sensor, but with fewer buttonevent values.

**Comment by wassfila** [comment]
OK, great.

**Comment by manup** [comment]
The smart thing groovy device handler contains some useful information

https://github.com/bspranger/Xiaomi/blob/a7ecc57eddac0d9d8a8f7a429a3808b4324b05c7/devicetypes/bspranger/xiaomi-aqara-button.src/xiaomi-aqara-button.groovy

To get the model identifier I would suggest start sensor search and reset the switch by pressing both buttons for 10 (?) seconds, it should then rejoin and provide the information in basic cluster.

**Comment by wassfila** [comment]
@manup , I managed to get the model identifier already, it is : lumi.remote.b186acn01
as the 1 in .b186 stands for a single switch as visible in the picture, so long press of 10 sec has worked.
Thank you for the reference, I'll have a look at that.

**Comment by carloscae** [comment]
I also got single and double switch Aqara Remotes and I'm facing the same issue. It's the new international version (this is the new version that is supposed to work with their new homekit bridge). The previous version I could pair to Phoscom with no issues.

unfortunately I have no access to the rest api as I'm running it from Hassio.

**Comment by carloscae** [comment]
My devices are:
Aqara Wireless Remote Switch (Single Rocker) - WXKG03LM
Aqara Wireless Remote Switch (Double Rocker) - WXKG02LM

**Comment by wassfila** [comment]
@manup , @carloscae ,
note that the reference WXKG03LM was already supported with another model id, the novelty here is the new model id lumi.remote.b186acn01. Basically Xiaomi has multiple model ids for the same reference WXKG03LM and they don't work the same.

**Comment by ebaauw** [comment]
Or rather, they use the same reference for different products.  Maybe it's actually the same hardware, with different firmware versions (which is  _not_ upgradable over the air).  Anyways, we best use the _Model Identifier_ to refer to these devices.  Unfortunately, it's a bit of a wheel of fortune which one you'll get when ordering one.

**Comment by zilluss** [comment]
I confirmed that the switch worked if you just copy the cases for lumi.remote.b1acn01 and replace it with lumi.remote.b186acn01. Now I can use the switch with the button event 1002.

**Comment by carloscae** [comment]
Guess I’ll need a windows pc to try that out. :/

**Comment by manup** [comment]
Related wiki page https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG03LM-2018

**Comment by manup** [comment]
Please continue discussion in #811

Closing this issue so we have just one to track progress on the matter.
