### ISSUE TITLE
Missing attributes after paring - is this fixed?

### ISSUE THREAD

**Issue by jo-me** [dresden-elektronik/deconz-rest-plugin#916]
There was an issue on headless systems that, e.g. sensors were not created after pairing (basic cluster?) and there was no reliable way to fix this (see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/654)

So for my Innr SP120 plug, the switch part was created but not the power consumption sensors. 

Has this issue been addressed in the latest firmware / deconz version (2.05.44)?

Thank you

**Comment by manup** [comment]
There were some changes in the recent versions to improve integration of sensors and switches (ongoing) the Philips hue dimmer for example should now pair more reliable.

You may check 2.05.45 and firmware 0x262e0500 out (create a backup first).

**Comment by manup** [comment]
Closing this for now.
