### ISSUE TITLE
Pairing Aqara Smart Wireless Switch WXKG11LM

### ISSUE THREAD

**Issue by saxn-paule** [dresden-elektronik/deconz-rest-plugin#917]
Hello,

your list of supported devices contains the Aqara Smart Wireless Switch WXKG11LM.

Unfortunately I'm no able to pair it in the Phoscon App.

In the switches category there is no matching manufacturer. Trying to pair it via "Sensors --> Other" it isn't recognized.

Produkt ConBee
Version 2.05.23 / 24.4.2018
Firmware 261F0500

Phoscon says that no updates are available.

Some advices?

**Comment by manup** [comment]
This might be WXKG11LM Rev.2 which identifies itself with model identifier
`lumi.remote.b1acn01` can you confirm that?

I don't have the switch yet which makes testing a bit cumbersome, there is already code for it active but it seems not to work properly.

**Comment by saxn-paule** [comment]
Where can I see this information? I have a Conbee connected to a RasPi3 and installed deconz in headless mode.

**Comment by manup** [comment]
You may try a recent version (make sure to create a backup first), the switch might be visible in the REST-API, but not yet the Phoscon App switch editor.

https://github.com/dresden-elektronik/deconz-rest-plugin#precompiled-deconz-packages

**Comment by saxn-paule** [comment]
Thank you very much.

With Version 2.05.45 / 2.11.2018 and Firmware 262E0500
the switch could be found as sensor and is available via the API as lumi.remote.b1acn01

Will there be a frontend representation in Phoscon App in the near future too?

**Comment by saxn-paule** [comment]
On press the button provides the value "1002". Maybe this is helpful.

**Comment by manup** [comment]
Ok that means API works correctly.

> Will there be a frontend representation in Phoscon App in the near future too?

Yes the plan is to support all Xiaomi switches as soon as possible, I hope to receive the missing ones in the next 2 weeks to complete integration.

**Comment by saxn-paule** [comment]
That are great news :D

I'm waiting for my wall switches too.

I think this issue could be closed. 

Thanks for the support.

**Comment by ACrazyConcept** [comment]
I also have 2 WXKG12LM i believe the model is. They do not come up in Phoscon, but they do in deCONZ and they work. Except one does not send the long press events. But maybe that is the device and not deCONZ's fault.

**Comment by saxn-paule** [comment]
Cool, I didn't know about the doubleclick feature yet. Works for me (1004) . Thank you.

**Comment by ACrazyConcept** [comment]
@manup 
Sorry, I was wrong. It is also the WXKG11LM (b1acn01) I have. It has single double and hold/release like listed in that link.

**Comment by Elliott32224** [comment]
It's been over a couple of weeks, so I thought I would check. Anything happening with the fix for this? As for others, I have Phoscon issues with WXKG11LM (b1acn01). Thanks. Elliott

**Comment by manup** [comment]
In the last days more details were collected and documented to be used as base to complete the implementation (see the linked pages in supported devices wiki) hopefully my switches arrive soon to simplify testing.

**Comment by Elliott32224** [comment]
Thank you.

**Comment by manup** [comment]
Good catch, yes I didn't have it on the radar, will be added too.

Still a bit confused about the 1000/1002
As I understand it the switch supports:

short press: 1000
short release: 1002

But the switch doesn't support  hold (1001) hold release (1003)?

**Comment by esseki** [comment]
> As I understand it the switch supports:
short press: 1000
short release: 1002
But the switch doesn't support hold (1001) hold release (1003)

Exactly. That's a kind of weird behavior from this first version of the Xiaomi button. But it supports up to 4 clicks ;)

**Comment by esseki** [comment]
Hi @manup,

immediately after I saw the release of 2.05.50 I updated my setup.
But I could not find the way how to use the switch editor with my Xiaomi round buttons.
Here is what I tried : 

- for the buttons that were already included in my setup before 2.05.50 : I tried the switch editor for one of my groups. The problem is that I don't see my Xiaomi round button in the "select switch" screen (when my Ikea and Hue switch appear). See the screenshot: 

<img width="1680" alt="capture d ecran 2018-12-10 a 20 21 19" src="https://user-images.githubusercontent.com/9165877/49755721-5e893600-fcb9-11e8-949f-1f260c3ddcfb.png">

- Then I tried adding a new button. When  I went to "switches / Add a new switch" I did not see the brand Xiaomi. I tried to add a button without any success. I then went to "sensors / Add a new sensor", I could add my Xiaomi button but it does not appear in the list of sensors (it did not appear either before 2.05.50). It does not appear in the list of switches either. It shows in the Rest API "/api/apikey/sensors/" but that's it. I can not find this new button in the switch editor for a group. 

What am I missing ?

**Comment by manup** [comment]
The round button – WXKG01LM is not supported yet, only the switches listed in the release notes.
I've ordered two round buttons via Gearbest, hopefully they arrive soon to complete integration.

**Comment by saxn-paule** [comment]
Today my second charge of WXKG11LM arrived. If I could trust the prints on package and button, it is the 2018 version.

In phoscon it's detected as the old version (no Rev2.0 behind model).

The problem is, that I only get 1002 and 1004 events. No tripple, quad or long press events at all.

Manufacturing date is 10/2018

The upper one is a Rev 2.0 from my last order, the lower one is the new one from yesterday. As you could see, the glue pad is also much thinner.

![img_20181219_105023_resized_20181219_105145262](https://user-images.githubusercontent.com/8352690/50212921-809b4c00-037c-11e9-962f-79ee411e00e5.jpg)

**Comment by saxn-paule** [comment]
Okay, forget about it. I pressed the button too short. Its a rev 1 and tripple/quad press works.

So it seems to be luck wich version you get.

**Comment by manup** [comment]
Interesting, which firmware version do they show?

>So it seems to be luck wich version you get.

Sadly yes, it's hard to tell from the shop descriptions which version it is.

**Comment by saxn-paule** [comment]
> Interesting, which firmware version do they show?
How could I see this? Running deconz (2.05.50 / 8.12.2018 / 262F0500) in headless mode on a Raspi 3.

**Comment by manup** [comment]
In the *Phoscon App > Menu > Switches > Switch Details*

![image](https://user-images.githubusercontent.com/383386/50218233-792f6f00-038b-11e9-8f6d-a3635926708e.png)


I guess the date code as version is only queried and shown in newer deCONZ versions. On older versions usually all Xiaomi devices report 3000-0001 as version which isn't helpful.

**Comment by saxn-paule** [comment]
There is no version shown on all my Aqara devices:

![image](https://user-images.githubusercontent.com/8352690/50218831-9107f280-038d-11e9-83c4-b509299daa79.png)

![image](https://user-images.githubusercontent.com/8352690/50218835-96653d00-038d-11e9-8aea-94f7a98e8b5e.png)

![image](https://user-images.githubusercontent.com/8352690/50218846-9c5b1e00-038d-11e9-905c-e74b24622c7d.png)

![image](https://user-images.githubusercontent.com/8352690/50218851-a11fd200-038d-11e9-8067-2a744ad4515c.png)

**Comment by manup** [comment]
Jep, this is only queried from the devices in newer versions 2.05.51 and 2.05.52. It may take up to one hour, until the version shows up.

**Comment by saxn-paule** [comment]
Well, then lets update to the .52 version ;)

**Comment by manup** [comment]
And backup first ;)

**Comment by saxn-paule** [comment]
Always :)

**Comment by saxn-paule** [comment]
My first order is version "20180525". The ones from yesterday "20161128"

So I definitely got version 1. :(

**Comment by Xento** [comment]
I try to pair a WXKG11LM but it doesn't work.
I'm using this versions:
2.05.52 / 16.12.2018
262F0500

**Comment by saxn-paule** [comment]
You need to pair it as a sensor. Press the small button and hold it for some seconds. Then press the big button several times. Worked for me with all 8 buttons.

**Comment by Mr-REM-Esq** [comment]
I try to pair a WXKG11LM as a sensor but it doesn't work. 
I'm using this versions:
Version 2.05.59 / 14.02.2019
Firmware 262F0500

**Comment by manup** [comment]
How do you pair the device?

Usually:
* Start sensor search
* Press the small button on the side until the led blinks

**Comment by Mr-REM-Esq** [comment]
Sure. I did it the way you described it. Start sensor search, then press the small button on the side until the led blinks. It blinked 7-10 times and went out. Connection did not happen.
Before that, I successfully connected two Aqara temperature sensors.
The same button successfully worked with an earlier version of deconz.

**Comment by ademobile** [comment]
With my issues with IKEA sensors stopping working (events being forwarded #1200), I thought in the meantime to help remove the grief I am getting over this, I ordered one of these switches. It pairs, can be seen by Phoscon and GUI, however I am not getting any events from it. Also if I assign it to a group, it does not switch it. I seems to be the same issues as above. Here is what I can see:

<img width="556" alt="screenshot 2019-02-25 at 14 09 42" src="https://user-images.githubusercontent.com/25222110/53343169-9d697800-3907-11e9-82d9-f246ffd47aad.png">
<img width="195" alt="screenshot 2019-02-25 at 14 09 30" src="https://user-images.githubusercontent.com/25222110/53343171-9f333b80-3907-11e9-98ab-4eb24a41ca33.png">
<img width="571" alt="screenshot 2019-02-25 at 14 09 53" src="https://user-images.githubusercontent.com/25222110/53343210-b83bec80-3907-11e9-8ca2-c159a6963b9b.png">
<img width="651" alt="screenshot 2019-02-25 at 14 10 04" src="https://user-images.githubusercontent.com/25222110/53343213-ba9e4680-3907-11e9-9bf2-50149a38fa76.png">

So I am still stuck, and I am using the same versions as above

**Comment by ademobile** [comment]
As I need to get this switch work, I spent all morning, removing and adding it again, as I felt that it must work to get as far as I did. After a few attempts it started to work! Don't ask what I did (the only thing different was I pressed the middle button over and over whilst waiting for it to be 'seen')

**Comment by alinelena** [comment]
I do not seem to see how can one configure hold/long release events in switch editor. I see the events in the log.

**Comment by Mr-REM-Esq** [comment]
Unable to pair WXKG11LM in version 2.05.60 too.

**Comment by haakonstorm** [comment]
WXKG11LM here. Latest version of everything. HASSIO, RaspBee, RPI3B+.
Most of the Aqara devices I got are now _more or less_ running OK, either directly or via REST.
The devices I can't get to join are these simple buttons.
Not sure about the following, did anyone get any 100% info:
1. How to reset
2. How to set in pairing mode

**Comment by rb2k** [comment]
Same issue here. I was able to Pair WXKG12LM switches just fine (as switches), but the Xaomi Mija WXKG01LM doesn't seem to work as a switch or a sensor.

**Comment by Franco757** [comment]
Hi,

I am trying to pair an Aquara mini switch WXKG11LM with my ConBee II (ver 2.13.04 12/18/2021, Firmware 26660700) attached to a RPI3B+ running home asssitant 2021.12.8 but not successful. 

I am able to pair and use Aqara temperature/door/water/motion sensors without any issue but not the mini switch.

Any thoughts?
Thanks

**Comment by Mimiix** [comment]
@Franco757 please search this git as it's a known issue.

**Comment by Franco757** [comment]
I have and the suggestions do not work.

**Comment by Mimiix** [comment]
It's a known issue that it broke with the latest stable. Fix will be in next beta.

**Comment by insalada** [comment]
I have the same problem as some users above. All my aqara devices are perfectly recognized and working via Phoscon, except with aqara mini switch (WXKG11LM). I have tried everything, as a switch and as a sensor, all possible combinations, but no success so far. I am in the last version of Home Assistant and using conbee II. Any suggestion will be welcome. Thanks.

**Comment by Franco757** [comment]
@Mimiix this case has been closed and merged with #5647.
#5647 is listed as closed with a modificaton in the CPP file.
What are the users running Phoscon via HA running on a PI + ConBee II supposed to do with that modified CPP file?
I doubt we have to recompile the software ourselves.
Thanks

**Comment by Mimiix** [comment]
Wait until home assistant updates the addon. That only happen on stable releases so that can take a while unfortunately

**Comment by insalada** [comment]
@Mimiix thanks. Will this fix be included in the next stable release?

**Comment by Mimiix** [comment]
If it's in next beta's, it will be in next stable.

**Comment by Franco757** [comment]
thx

**Comment by simonfxr** [comment]
Any idea when there will be a beta release including this change?

**Comment by jankryh** [comment]
the problem still remains deConz version 2.14.1

**Comment by bumpyflea** [comment]
Hi @Mimiix 

I'm also using deConz version 2.14.01 / 2/6/2022 on firmware 26720700, and still am unable to pair any of my WXKG11LM switches. 

Have tried pairing through both the phoscon UI + the deconz UI,  but no success. 

Is there anything else I (or we, as seems like Jankryh and others are still having the same issue) should be doing to get it working?   

I have seen this new node appearing in the Deconz UI which doesn't how any model number or manufacturer. 
![image](https://user-images.githubusercontent.com/10327153/162940015-cabd16dd-9854-46b2-bd5f-fedae808ca95.png)

**Comment by Mimiix** [comment]
Looks like yours isn't paired fully as the clusters are missing.

This might help out : 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by bumpyflea** [comment]
@Mimiix  - you are a legend!!! thanks heaps for your help!. That worked beautifully.. 
Thanks again for the quick response!!
