### ISSUE TITLE
RaspBee works, but firmware update fails?

### ISSUE THREAD

**Issue by felixstorm** [dresden-elektronik/deconz-rest-plugin#921]
I am using a RaspBee that (still) works with deCONZ seemingly without issues, but suddenly fails when trying to update the firmware (which used to work without problems as well). To make sure that it is not a software problem, I just downloaded the latest sd card image dated 2018-10-30 to try again, but the problems remain.

Installed is 0x261F0500, but deCONZ 2.05.44 (which is part of the sd card image) does not ask to update the firmware, but keeps working with the old firmware installed, even though a newer version is available:
```
19:19:37:876 dev /dev/ttyS0 (/dev/ttyS0)
19:19:37:877 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262d0500.bin.GCF
19:19:37:877 GW firmware version: 0x261f0500
19:19:37:877 GW firmware version shall be updated to: 0x262d0500
```

When I try to update manually using `GCFFlasher_internal`, I get the error message that the bootloader would not be responding, even though deCONZ is definitely stopped:
```
pi@phoscon:~ $ sudo GCFFlasher_internal -f /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262d0500.bin.GCF 
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
no device specified use RaspBee (/dev/ttyS0)
using firmware file: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262d0500.bin.GCF 
reset target 

(several empty lines omitted)

error: bootloader not responding
device used by other application?
```

The situation is exactly the same when removing the `-overlay` from /boot/config.txt (see #920) - deCONZ works but does not try to update and a manual update fails again with "error: bootloader not responding".

**Comment by felixstorm** [comment]
The revision is `a02082`.

If it is of help, you could tell me the pin number and I could try to momentarily connect it to GND manually while running `GCFFlasher_internal`?

**Comment by heitec11** [comment]
If you use the image, then you have to close deConz. After then the GCFFlasher is working. I had the some problem and used the VNC viewer for close deConz.
