### ISSUE TITLE
No Rest API (Banana Pi)

### ISSUE THREAD

**Issue by Danny42** [dresden-elektronik/deconz-rest-plugin#923]
Hi,
I do not get the rest api running on a BananaPI M2U with (Ubuntu 18 based) Armbian linux and a ConnBee Stick (firmware 261F0500) at /dev/ttsUSB0. I followed the instructions on [https://github.com/dresden-elektronik/deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin) and installed the software version 2.05.45. Deconz and the Phoscon web app are working, I can add and group sensors, switches and lights. But the rest api does not work. The log ('journalctl -afn 1000 -u deconz' with debug information) always says “REST API plugin shutting down”. I can not find any problem.

log file: [deconz.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/2544986/deconz.txt)

Thanks

**Comment by manup** [comment]
If you can add groups/switches etc. the REST-API does work otherwise the Phoscon App wouldn't be able to talk with deCONZ :)

**Comment by Danny42** [comment]
I was not aware that Phoscon uses the Rest API and, therefore, I was looking at the wrong place for the problem. After fixing some permission issues I am now able to communicate withe the API (and so is my Home Assistant wich discovered deCONZ). Shame on me.

Thank you for the fast response.
