### ISSUE TITLE
Best dimmer switch?

### ISSUE THREAD

**Issue by ACrazyConcept** [dresden-elektronik/deconz-rest-plugin#924]
I am getting a bit tired of my IKEA Trådfri dimmers. They are hit and miss to pair. They are slow to respond when turning. They need multiple attempts before responding and for controlling multiple lights they can't seem to catch all of them every time.

Which is the best dimmer switch to use across lights of different manufacturers?

**Comment by ACrazyConcept** [comment]
A dimmer for the zigbee bulbs.  Like the Philips Hue or IKEA ones.

**Comment by manup** [comment]
Personally I really like the round Ikea switch with 5 buttons, compared to the Ikea dimmer it works very reliable in my setup.
