### ISSUE TITLE
REST-API reporting same Uniqueid on different ID's

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#927]
HI,

A user of my plugin has an issue where sensors are present with the same uniqueid, but with different ID. How is this possible?  
The valid entry:

`    "18": {
      "config": {
        "battery": 100,
        "on": true,
        "reachable": true,
        "temperature": 0
      },
      "ep": 1,
      "etag": "4f48d4221d76695f1d7c46d2287625ca",
      "manufacturername": "LUMI",
      "modelid": "lumi.sensor_magnet",
      "name": "Viktor Secure Window",
      "state": {
        "lastupdated": "2018-11-02T12:44:47",
        "open": false
      },
      "type": "ZHAOpenClose",
      "uniqueid": "00:15:8d:00:01:d6:31:22-01-0006"
    },`

The invalid entry (lastupdated='none')

`  "57": {
      "config": {
        "battery": null,
        "group": null,
        "on": true,
        "reachable": true,
        "temperature": 0
      },
      "ep": 1,
      "etag": "4f48d4221d76695f1d7c46d2287625ca",
      "manufacturername": "IKEA of Sweden",
      "mode": 1,
      "modelid": "lumi.sensor_magnet",
      "name": "lumi.sensor_magnet ",
      "state": {
        "buttonevent": null,
        "lastupdated": "none"
      },
      "type": "ZHASwitch",
      "uniqueid": "00:15:8d:00:01:d6:31:22-01-0006"
    },`

Is this caused by one of the earlier version of deCONZ maybe - this user is already along for more then a year. We can delete this entry ofcourse, but I just want to be sure it is not a new issue?

Also check the modelid, it seems the ID 57 is really mixed up somehow. The same se also has other ID's that seems to be mixed up......

**Comment by manup** [comment]
This should not happen anymore with recent versions and aded checks. Closing this for now.
