### ISSUE TITLE
Improve Change log Documentation

### ISSUE THREAD

**Issue by GadgetUK** [dresden-elektronik/deconz-rest-plugin#931]
Whilst changes are clearly documented under the Github Releases section

https://github.com/dresden-elektronik/deconz-rest-plugin/releases

The main Deconz Website change log remains significantly out of date.

Github releases also lag the downloadable packages from the downloads website, and finally there is no indication what version "deconz-latest.deb" actually is.

**Comment by wmn79** [comment]
Wouldn't it be possible to change the changelog link in the Phoscon Gateway page (under the firmware update button) to the above github releases page? That would make more sense than linking it to the current really outdated changelog page for the webapp and deCONZ.

**Comment by manup** [comment]
Status: A better change log is on the todo list. It will likely be based on machine readable RSS sources from which online version for the web page and Github will be created.
