### ISSUE TITLE
Meshing changed with  0x262f0500 and 2.05.46?

### ISSUE THREAD

**Issue by wvuyk** [dresden-elektronik/deconz-rest-plugin#933]
After upgrading, the deCONZ view chaged a lot here. Most lights ony have one connection in this view, and some have very many coonctions. Also one sensor seems to have changed in a router? I thin this is not looking well if this is correct? No more meshing?

This image is taken after 3 hours of running.

![2018-11-08 15_02_39-raspbee raspberrypi - vnc viewer](https://user-images.githubusercontent.com/30700296/48203378-a68a0580-e367-11e8-9b25-f75124209bf0.png)

**Comment by manup** [comment]
The meshing is fine under the hood, but sometimes it happens that neighbor tables aren't queried (used to display the relations between nodes) when the queue is busy with oder zdp requests. This bug exists for some versions now and is under investigation, as workaround when you restart deCONZ it starts with fresh queues.

>Also one sensor seems to have changed in a router?

Which one? Can you please post a screenshot of the Node Info Panel when it's selected?

**Comment by wvuyk** [comment]
It is a IKEA motion sensor... Very surprising!

![image](https://user-images.githubusercontent.com/30700296/48218361-fda0d200-e389-11e8-88df-e138a95cb4b3.png)

**Comment by wvuyk** [comment]
A restart did not change the visual display... never seen this before... but indeed all lights keep working, so I will just trust it is ok for now. 

Andother observation, this IKEA motion sensor seems not to be connected to anty other router of gateway. But then, some other sensors are also not visibly connected, so maybe that means nothing....

**Comment by ebaauw** [comment]
It's probably just a glitch reading the node descriptor.  I had some issues with my `lumi.ctrl_ln2` wired switch showing the wrong clusters in the fingerprint.  I deleted the node and all resources.  On re-detecting the node, the GUI wouldn't show the endpoints, then it showed it as an end-device.  Deleted it again.  Upon next discovery, it showed correctly.

**Comment by MattL0** [comment]
where are 0x262f0500 and 2.05.49?

**Comment by wvuyk** [comment]
The new version 2.0.47 is looking better again :-)

![image](https://user-images.githubusercontent.com/30700296/48432552-f821fe00-e774-11e8-851a-81e303da6c17.png)
