### ISSUE TITLE
How do I enable Echo mode in this commit? For on/off devices

### ISSUE THREAD

**Issue by saurabh984** [dresden-elektronik/deconz-rest-plugin#934]
https://github.com/dresden-elektronik/deconz-rest-plugin/commit/e05358f5b964d074d7558a70177ec67b952e5f6a

How do I enable this for devices like Ubysis S2?

**Comment by manup** [comment]
So the Ubisys S2 doesn't show up in Echo lights?

**Comment by saurabh984** [comment]
Yes @manup
