### ISSUE TITLE
Xiaomi Switch WXKG02LM reports as lumi.remote.b286acn01

### ISSUE THREAD

**Issue by goermezer** [dresden-elektronik/deconz-rest-plugin#936]
I bought a new Xiaomi Aqara switch seems to integrate into the network. It looks good in deconc gui. But it doesn`t show up in the webapp and even not in REST API. It is a WXKG02LM which reports as lumi.remote.b286acn01. Any idea, how to integrate it? 

I have another one which reports as lumi.sensor_86sw2. This could be easily integrated and works very well.

**Comment by manup** [comment]
Please continue discussion in the other WXKG02LM issue https://github.com/dresden-elektronik/deconz-rest-plugin/issues/811

I'm collecting and adding the details about the different models to the Wiki in device specific pages, like the WXKG11LM models. This should help to do the REST-API implementation and integration in the Phoscon App switch editor.
 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices
