### ISSUE TITLE
Using builtin daylight sensor

### ISSUE THREAD

**Issue by jaal2001** [dresden-elektronik/deconz-rest-plugin#949]
Hi,
I'm currently trying to use the builtin (virtual) daylight sensor.
I've removed the sensor from my previous exclude list an can now see events in the daemon.log:

Nov 15 17:20:04 raspberrypi homebridge[6074]: [2018-11-15 17:20:04] [Hue] Daylight: set homekit light level from 9.9977 lux to 1.2586 lux
Nov 15 17:20:04 raspberrypi homebridge[6074]: [2018-11-15 17:20:04] [Hue] Daylight: set homekit last event from Sunset to Dusk
Nov 15 17:20:04 raspberrypi homebridge[6074]: [2018-11-15 17:20:04] [Hue] Daylight: set homekit period from Twilight to Nautical Twilight
Nov 15 18:00:44 raspberrypi homebridge[6074]: [2018-11-15 18:00:44] [Hue] Daylight: set homekit status from 210 to 220
Nov 15 18:00:44 raspberrypi homebridge[6074]: [2018-11-15 18:00:44] [Hue] Daylight: set homekit light level from 1.2586 lux to 1.0231 lux
Nov 15 18:00:44 raspberrypi homebridge[6074]: [2018-11-15 18:00:44] [Hue] Daylight: set homekit last event from Dusk to Nautical Dusk
Nov 15 18:00:44 raspberrypi homebridge[6074]: [2018-11-15 18:00:44] [Hue] Daylight: set homekit period from Nautical Twilight to Astronomical Twilight
Nov 15 18:40:04 raspberrypi homebridge[6074]: [2018-11-15 18:40:04] [Hue] Daylight: set homekit status from 220 to 230
Nov 15 18:40:04 raspberrypi homebridge[6074]: [2018-11-15 18:40:04] [Hue] Daylight: set homekit light level from 1.0231 lux to 0.0001 lux
Nov 15 18:40:04 raspberrypi homebridge[6074]: [2018-11-15 18:40:04] [Hue] Daylight: set homekit last event from Nautical Dusk to Astronomical Dusk
Nov 15 18:40:04 raspberrypi homebridge[6074]: [2018-11-15 18:40:04] [Hue] Daylight: set homekit period from Astronomical Twilight to Night

Unfortunately I can't see the sensor in the "old" webinterface or the new webapp. 
I tried to search the forums here, but so far I could not find any documentation. In the end I want to use the virtual sensor to switch on my christmas lights when the sunset starts.
Can anyone point me here to the right documentation? Any help would be highly appreciated.

Thanks
J

**Comment by ebaauw** [comment]
You can use HomeKit automations (set up in Eve, as Apple Home app doesn't support custom characteristics) or deCONZ rules for that.  Easiest using `state.daylight` or `state.dark` of the built-in sensor; more advanced using `state.status`.
