### ISSUE TITLE
POST /config/restart

### ISSUE THREAD

**Issue by ebaauw** [dresden-elektronik/deconz-rest-plugin#95]
A POST to `/config/restart` (`/config/shutdown`) actually restarts (shuts down) the Raspberry Pi, not just deCONZ.  I didn't quite expect that looking at  https://github.com/dresden-elektronik/deconz-rest-plugin/commit/619749e0d63842a06799d0a5ce76c3e54f1852f0, but `deCONZ-autostart.sh` happily issues a `sudo reboot` (`sudo halt`) when deCONZ exits with the corresponding status.

Would it be possible to create a REST API call to restart (shutdown) deCONZ only?  I'm a bit reluctant to mess with deCONZ-autostart.sh and unintentionally break updating deCONZ or the ZigBee firmware.

**Comment by manup** [comment]
There is a new call `/config/restartapp` for this purpose, it still needs some more improments since it won't work on windows, only Linux based versions.

Related commit: https://github.com/dresden-elektronik/deconz-rest-plugin/commit/fb6f624b093e79832539934a7ffc8493e58ae5a2
