### ISSUE TITLE
setting up sandbox environment - need for specific config of networks?

### ISSUE THREAD

**Issue by ErnstEeldert** [dresden-elektronik/deconz-rest-plugin#955]
I am running a rather large network on a raspbee. To avoid disturbing the 'production' environment, I figured it would be a good idea to setup a separate sandbox environment, which I can use to play with new devices and do debugging if required. To that means, I've bought a conbee, which will run on a separate PI.

Are there any things I need to consider so that both environments do not interfere with one another? Network ids? Other specific controller settings?

Thanks!

**Comment by manup** [comment]
The two networks should just work, every network has a random network id (panid, extended panid). Further it is possible (optional) to use separated channels for the two network.

**Comment by ErnstEeldert** [comment]
Thanks for the clarification!
