### ISSUE TITLE
Single IKEA Tradfri remote not triggering rules

### ISSUE THREAD

**Issue by pheber** [dresden-elektronik/deconz-rest-plugin#958]
Just got my Phoscon gateway yesterday, spent a few hours mashing buttons trying to pair a couple of Tradfri remotes (is there any better way than to keep trying? holding the on button for 10 seconds when the PWA told me to did not work for me at all, had to keep resetting and then randomly mashing the buttons and retrying 25-30 times per remote) and got three remotes to successfully pair with the gateway (pushing buttons on the remote generates the correct websocket events, as far as I can tell). Until I got there, I had a few instances of the remotes being "somewhat" paired: I could see all the clusters in deCONZ and even read attributes, but the remote wouldn't send any button presses to the gateway.

Anyway, all three remotes now send events and I paired a couple of lights. However, in the PWA UI, while I can set up button rules for all three remotes, the rules will only execute for two of them. I had a look at the REST endpoint and as far as I can tell, I have identical rules for two different remotes. However, only for one of those remotes are the rules actually executing.

Working rule (Remote 1):

`  "20": {
    "actions": [
      {
        "address": "/groups/2/action",
        "body": {
          "on": true
        },
        "method": "PUT"
      },
      {
        "address": "/sensors/13/state/",
        "body": {
          "flag": false
        },
        "method": "PUT"
      }
    ],
    "conditions": [
      {
        "address": "/sensors/90:fd:9f:ff:fe:6e:66:97-01-1000/state/buttonevent",
        "operator": "eq",
        "value": "1002"
      },
      {
        "address": "/sensors/90:fd:9f:ff:fe:6e:66:97-01-1000/state/lastupdated",
        "operator": "dx"
      },
      {
        "address": "/sensors/13/state/flag",
        "operator": "eq",
        "value": "true"
      }
    ],
    "created": "2018-11-18T11:51:38",
    "etag": "b8e235c8a1ac953fca6a07eba784bed0",
    "lasttriggered": "2018-11-18T12:53:35",
    "name": "Rule TOOGLE_ON",
    "owner": "13B2AC3146",
    "periodic": 0,
    "status": "enabled",
    "timestriggered": 17
  }`

Non-working rule (remote 2):

`  "42": {
    "actions": [
      {
        "address": "/groups/2/action",
        "body": {
          "on": true
        },
        "method": "PUT"
      },
      {
        "address": "/sensors/26/state/",
        "body": {
          "flag": false
        },
        "method": "PUT"
      }
    ],
    "conditions": [
      {
        "address": "/sensors/00:0b:57:ff:fe:ec:2d:f4-01-1000/state/buttonevent",
        "operator": "eq",
        "value": "1002"
      },
      {
        "address": "/sensors/00:0b:57:ff:fe:ec:2d:f4-01-1000/state/lastupdated",
        "operator": "dx"
      },
      {
        "address": "/sensors/26/state/flag",
        "operator": "eq",
        "value": "true"
      }
    ],
    "created": "2018-11-18T12:50:11",
    "etag": "92a0d3af93f01904781d699da04b8285",
    "lasttriggered": "none",
    "name": "Rule TOOGLE_ON",
    "owner": "13B2AC3146",
    "periodic": 0,
    "status": "enabled",
    "timestriggered": 0
  }`

I can verify that both remotes generate the same websocket events. What could cause deCONZ not to process rules for one of them?

Websocket event remote 1 (working):

`{
  "e": "changed",
  "id": "10",
  "r": "sensors",
  "state": {
    "buttonevent": 1002,
    "lastupdated": "2018-11-18T13:20:39"
  },
  "t": "event",
  "uniqueid": "90:fd:9f:ff:fe:6e:66:97-01-1000"
}`

Websocket event remote 2 (not working):

`{
  "e": "changed",
  "id": "25",
  "r": "sensors",
  "state": {
    "buttonevent": 1002,
    "lastupdated": "2018-11-18T13:20:22"
  },
  "t": "event",
  "uniqueid": "00:0b:57:ff:fe:ec:2d:f4-01-1000"
}`

**Comment by manup** [comment]
Interesting, I recon this are newer models, the mac address looks different when the former models

Since the processing of Ikea remotes/sensors are partly make usage of the mac address prefix this might be the cause here.

Can you please provide the details as described here for the remote with the mac address `90:fd:9f:ff:fe:6e:66:97`

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by manup** [comment]
Is it still not working? By the way which deCONZ and firmware version are you using?

The websocket events and rules look fine, I can only recon that the rules weren't indexed yet, if that is the case a deCONZ restart will do this (this should be fixed in .48).

**Comment by berhomeauto** [comment]
Hello everybody.
In my case the effect is inverted.
Tradfri remotes:
-   macid starting with 90:fd are NOT triggering a ct change at left/right Button press
-   macid starting with d0:cf are NOT triggering a ct change at left/right Button press
-   macid starting with 00:0b are triggering a ct change at left/right Button press
I am on 2.5.50 on Raspbee with latest firmware.

all 00:0b are working
the only d0:cf ist my newest remote bought in August 2018
no 90:fd is working

Any ideas?

**Comment by manup** [comment]
With recent version all remote version should work.
The color temperature controls are also supported via Phoscon App Switch Editor.

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_54

**Comment by pheber** [comment]
Sorry for the long delay, I was out of action for a while. I was on the latest version at the time of my initial post, but I can confirm that as of 2.05.54, all remotes work (and they also seem to join the network with a lot less hassle).
