### ISSUE TITLE
Problem with Brightness used in same time than color

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#960]
Hello, I have a strange situation and idk if it's normal or not.
Deconz 2.05.48
Firmware 262F0500
And an ikea bulb RGB 600lm

If I use the command /api/XXXXXXXXX/lights/2/state with {"on":true,"bri":13} the light switch to ON with 13 as brighness
I have on websocket
{'e': 'changed', 'uniqueid': '90:fd:9f:ff:fe:83:1d:17-01', 't': 'event', 'r': 'lights', 'state': {'bri': 13}, 'id': '2'}

But if I use the command /api/XXXXXXXXX/lights/2/state with {"on":true,"bri":13,"xy":[0.415182,0.174429]} the light go on but stay with the same brighness.
`[{'success': {'/lights/2/state/on': True}}, {'success': {'/lights/2/state/bri': 13}}, {'success': {'/lights/2/state/xy': [0.415182, 0.174429]}}]`
Event I have on websocket
{'e': 'changed', 'uniqueid': '90:fd:9f:ff:fe:83:1d:17-01', 't': 'event', 'r': 'lights', 'state': {'bri': 13}, 'id': '2'}
{'e': 'changed', 'uniqueid': '90:fd:9f:ff:fe:83:1d:17-01', 't': 'event', 'r': 'lights', 'state': {'x': 27102}, 'id': '2'}
{'e': 'changed', 'uniqueid': '90:fd:9f:ff:fe:83:1d:17-01', 't': 'event', 'r': 'lights', 'state': {'y': 11386}, 'id': '2'}

So I have a return value for brightness of 13 but it's 255 in reality. Even in phoscon the slidebar is on 13.

Edit.
BTW: what are the x and Y values on state values ?

**Comment by Smanar** [comment]
Ok I have understand for x and y value, it's value * 65279.

But for my problem I have sniff the request and on the second case I have only
- on/off report attribute
- color control : move to color

And on the first test
- on/off report attribute
- level control : move to level

The brighness is totally ignored if you set a color. I can use 2 commands as workaround instead of one, but IDK if its something normal or not ?

**Comment by ebaauw** [comment]
It’s a bug in the Ikea firmware, see 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/445#issuecomment-373649142

**Comment by Smanar** [comment]
Nice to know, you are right, you can solve this issue with playing with transistion time.
Even if you use 2 commands, it will not work (the second cancel the first). But it work if you use "transitiontime":0 in the set level command (Maybe it speed up the first one, I m making first level then color)
But I m trying ATM this command

`Send Command /api/A2615C25A6/lights/2/state with {"on":true,"bri":15,"transitiontime":0,"on":true,"xy":[0.424541,0.173146]}`

And it seem working too fine.
