### ISSUE TITLE
Can't add ConBee as huebridge in harmony hub

### ISSUE THREAD

**Issue by Ullulaki** [dresden-elektronik/deconz-rest-plugin#961]
Hi there, I hope it's not a too stupid question but how do I get my conbee (connected to Raspi 3b+) added As a hue Bridge in my harmony hub? Target is to control a few lights with the harmony remote which worked perfectly with the original bridge. 
The stick is running with v39 as with newer ones I wasn't able to connect Aqara devices. 

The original bridge is offline, the hub tells me Bridge found but when I press connect app in phoscon nothing happens. I already reset the stick and tried it about 20 times, still nothing.
When I search for wifi devices in the harmony mobile app, I find the bridge but with the IP 127.0.0.1. Normally the IP from Raspi is 192.x.x.150.
I tried to Google it but didn't find any solution. :(

I hope this is enough information, if not I'll provide the necessary details. 
Please have merci with me as I'm pretty new to this in general :-)

**Comment by tomfritz1** [comment]
With the newest firmware update for Harmony Hub it should work again - it is out since few days.

**Comment by Ullulaki** [comment]
Do you know which it is? Currently I use 4.15.201 and I can't update to a newer one (yet?)

**Comment by tomfritz1** [comment]
I have the same version and app 5.4.4 (iOS)

**Comment by Ullulaki** [comment]
now, after updating the conbee device to newest version it works again, also the sensors, damn it.. could've saved so much time :-)
