### ISSUE TITLE
Contribute to Phoscon App

### ISSUE THREAD

**Issue by xeetsh** [dresden-elektronik/deconz-rest-plugin#963]
As I can't find the Phoscon App in dresden-elektroinks projects is there currently a way to contribute to it's development or is something like this planned? I have a few ideas that would improve the software at least for my use case but i think also for a lot of other users.

**Comment by abmantis** [comment]
Unfortunately, the project is closed source :cry: 
It would be great if dresden could opensource it and allow devs to submit pull requests.

**Comment by ethologus** [comment]
Wait what? What do you mean by saying closed? :-(

**Comment by dergreg** [comment]
Not closed but "closed source", which means you cannot provide changes to it via GitHub. Would be cool though.
