### ISSUE TITLE
deleted sensor still showing in Home Assistant despite no longer in deCONZ

### ISSUE THREAD

**Issue by clementx2006** [dresden-elektronik/deconz-rest-plugin#964]
I experimented with a couple of Xiaomi sensor / switch over the weekend. 

Both the leak sensor and the button switch seemed to be a pain to pair and only showed up in deCONZ and not in Phoscon - but I guess this has already been logged as open issues - and then I decided to delete them via 'Delete Selected Nodes' in deCONZ which was successful; however I then discovered that both of them were still showing in Home Assistant. So I am wondering whether there is any way of getting rid of them? I tried to restart the HA service, the deCONZ GUI to no avail...

**Comment by clementx2006** [comment]
Tried to connect through the REST API, but for some reason I am getting 'Body contains invalid JSON'? This is after unlocking the gateway...

**Comment by ebaauw** [comment]
Make sure there's no invisible characters in the body.  Run it through a JSON linter, like https://jsonlint.com.

**Comment by clementx2006** [comment]
seems to be working! Thanks a lot!
