### ISSUE TITLE
deCONZ_Rpi_0x26290500.bin.GCF

### ISSUE THREAD

**Issue by MattL0** [dresden-elektronik/deconz-rest-plugin#965]
is deCONZ_Rpi_0x26290500.bin.GCF the last firmware?

**Comment by ebaauw** [comment]
No, see https://www.dresden-elektronik.de/rpi/deconz-firmware/?C=M;O=D.

**Comment by MattL0** [comment]
this is why I ask. There is no 0x26290500 there. And last time with 0x262f0500.bin.GCF this repo was not updated.

But I saw deCONZ_Rpi_0x26290500.bin.GCF in usr/share/deCONZ/firmware/ 

so i was wondering if it was just not updated on the repo you posted, like last time

**Comment by Kane610** [comment]
It is hex, 9 is lower than f so it is easy to identify if the FW is newer.

**Comment by PrimaryInc** [comment]
This is the latest FW located there :)
deCONZ_Rpi_0x262f0500.bin.GCF | 07-Nov-2018 19:21 | 123K |

**Comment by MattL0** [comment]
haa ok i understand now thanks!

**Comment by manup** [comment]
Mystery solved, closing this for now :)
