### ISSUE TITLE
Litght Bulbs member of more than one group?

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/deconz-rest-plugin#966]
Hi,

Question, can a bulb be a member of more than one group in DeConz?
I have scenarios where I want to orchestrate functions that could require several groups and a few light bulbs in different groups.

**Comment by ebaauw** [comment]
Generally, yes.  The bulb’s firmware actually determines how many groups it supports.

**Comment by PrimaryInc** [comment]
Thanks for answer @ebaauw :)
