### ISSUE TITLE
Fehler bei Installation Debian debian-9.6.0-amd64

### ISSUE THREAD

**Issue by mister2212** [dresden-elektronik/deconz-rest-plugin#969]
Hallo
ich bin mit meinem iobroker auf einen intel nuc umgezogen. jetzt bekomme ich deon deconz usb stick nicht mehr installiert. bekomme immer den einen fehler paketarchitektur passt nicht. Wo bekomme ich eine passende installationsdatei her? Vielen dank für die Hilfe
![unbenannt](https://user-images.githubusercontent.com/45299650/48961766-9aad5e80-ef77-11e8-84dd-70e0a7e2c55d.PNG)

**Comment by ebaauw** [comment]
Try the Ubuntu package, see https://github.com/dresden-elektronik/deconz-rest-plugin#precompiled-deconz-packages.

**Comment by mister2212** [comment]
funktioniert auch leider nicht. egal ob ubuntu oder raspbian
![unbenannt](https://user-images.githubusercontent.com/45299650/48980790-ee31c080-f0cd-11e8-9670-829da6853ccf.PNG)
