### ISSUE TITLE
Is there a way to disable a device router functionality ?

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/deconz-rest-plugin#989]
My problem, I have some devices who are realy bad router. Some of them are fixed on wall or connected to electrical wires, so realy hard to turn them off.
When I m trying to pair new device, It s a circus to avoid them. Is there a way to "block" them in the GUI or another special trick ?

**Comment by manup** [comment]
Sadly, it is not possible to disable the router functionality of devices, the only workaround is to place better routers nearby.

As for joining and end-devices selecting a parent device there might be solutions in the future but this needs more testing and firmware improvements.

**Comment by Smanar** [comment]
Arf, because ATM, I m trying all possible magical receipe, even putting metal box on the device ^^.
Why the worst router are always the choosen one by the new devices ....

BTW, I will continue to search the perfect barrier for zigbee mesh, Thx :)
