### ISSUE TITLE
Device Integration: Samsung SmartThings Button

### ISSUE THREAD

**Issue by mysteryan** [dresden-elektronik/deconz-rest-plugin#993]
Is it possible to add compatibility for SmartThings Button: 
https://www.amazon.com/Samsung-SmartThings-GP-U999SJVLEAA-One-Touch-Appliances/dp/B07F8ZFFQK/
Hoping integration would be simple since other SmartThings products have been integrated and its already recognized by Deconz GUI.  Device transmits events for button press, double press, hold and temperature.  Node shows up in GUI, but missing from rest api.
![ef5cf35d-f3f6-46a5-a21b-3545a5319999](https://user-images.githubusercontent.com/15268211/49314641-e98b5480-f49f-11e8-8342-4a64f8103406.jpeg)
![45539a50-98d1-41d3-a7d7-c3872de957fe](https://user-images.githubusercontent.com/15268211/49314695-0e7fc780-f4a0-11e8-8969-16a1a6cf549d.jpeg)
![53f83a5b-5d78-4491-85da-9f2654abadcf](https://user-images.githubusercontent.com/15268211/49346392-98699500-f646-11e8-82c7-ec06a6f94692.jpeg)
![5b41d16c-3546-4bed-9a5e-2cd6fe05c161](https://user-images.githubusercontent.com/15268211/49314697-0e7fc780-f4a0-11e8-8ebd-4c316174834e.jpeg)
![e14271ee-9da3-4674-94bc-3b39ba839dea](https://user-images.githubusercontent.com/15268211/49314759-46870a80-f4a0-11e8-9309-34cbefd664ec.jpeg)
![95755626-1563-4ea7-9a4f-0ef3e18bedc6](https://user-images.githubusercontent.com/15268211/49314760-46870a80-f4a0-11e8-9ebe-435b79aab6c1.jpeg)
![af24b1c0-d50a-4426-8fa2-553dd0086b81](https://user-images.githubusercontent.com/15268211/49314761-471fa100-f4a0-11e8-8a75-c1819834ce1a.jpeg)
![6acef3ab-c936-418f-9ffe-cae5375b12fd](https://user-images.githubusercontent.com/15268211/49314762-471fa100-f4a0-11e8-9a8c-27c2c80f006c.jpeg)
![69ca7e68-c412-4270-b0d5-02d647996423](https://user-images.githubusercontent.com/15268211/49314763-471fa100-f4a0-11e8-95f4-3077c606991e.jpeg)
![81148e5f-dad4-48d8-b8f7-cfd698b71c70](https://user-images.githubusercontent.com/15268211/49314764-471fa100-f4a0-11e8-89f5-ff96f328fe11.jpeg)
![9fa34f2a-7fc8-40aa-aade-ad1984267d71](https://user-images.githubusercontent.com/15268211/49314765-47b83780-f4a0-11e8-8c36-5f8d9eb6cce1.jpeg)
![888f4ece-4356-423f-8ef9-dbb9cbe4dad3](https://user-images.githubusercontent.com/15268211/49314766-47b83780-f4a0-11e8-8842-3b146c769e12.jpeg)
![4dfd90be-bdef-4abe-b4e7-90115477192c](https://user-images.githubusercontent.com/15268211/49314767-47b83780-f4a0-11e8-8820-bf376ba8f3c6.jpeg)

**Comment by mysteryan** [comment]
Debug (aps,zcl,zdp) output doesn’t seem to with frep filtered result of nwk address doesn’t seem to yield anything useful.
![2865fc23-7c6e-4d9a-89c4-230505c56c45](https://user-images.githubusercontent.com/15268211/49409381-480d3880-f715-11e8-9474-58352caa8415.jpeg)

I do notice changes in zone status when I press the button shown in no press, press, double press and hold in that order:
![a5534016-e690-4a9a-a10e-bdb5d8d5afb5](https://user-images.githubusercontent.com/15268211/49409443-8d316a80-f715-11e8-8e29-57ecfef56756.jpeg)
![415982f3-11fe-4022-bce4-f55b73b742d3](https://user-images.githubusercontent.com/15268211/49409450-915d8800-f715-11e8-8973-8b506fbb0d45.jpeg)
![e083936b-6070-4fb0-8b56-1a0b3906b0f9](https://user-images.githubusercontent.com/15268211/49409452-9589a580-f715-11e8-904d-791f00e8d47d.jpeg)
![0008ea46-e24d-4335-a602-d17724d7ad7f](https://user-images.githubusercontent.com/15268211/49409454-9a4e5980-f715-11e8-93b9-0cf1681ff7b2.jpeg)

**Comment by mysteryan** [comment]
Just realized that it’s not necessary to manually press read to see the button presses.  It’s shown instantly in GUI as ticks in the zone status.  Alarm 1 for press, alarm 2 for double press, and alarm 1+2 for press hold.
![f1bc032a-1fa3-4abc-9fd9-cf52b5ce5b64](https://user-images.githubusercontent.com/15268211/49778068-28978200-fcb8-11e8-930e-051a53135b91.jpeg)
![119e3be5-8abe-41c7-97df-c98f24c3f2e8](https://user-images.githubusercontent.com/15268211/49778069-28978200-fcb8-11e8-9402-f437a30d07e7.jpeg)
![b611d63a-dba3-4a61-95ff-afd0b98191af](https://user-images.githubusercontent.com/15268211/49778070-28978200-fcb8-11e8-99ab-631887863a12.jpeg)

I’ve tried binding the IAS cluster to a group in hopes that I’ll get usable values in rest, but no luck.  So everything looks like its working within GUI, just can’t get it to publish the values in rest.

**Comment by blueleader07** [comment]
Any chance this will be available soon?  Looks like manup has provided the code?
https://github.com/mysteryan/deconz-rest-plugin/commit/876af0f427521ead699aa6e1e197a18a333d6510

Excited to use this one.  I'm in the same boat where I see the Alarm 1 / Alarm 2 status being updated ... but can't get the device added to the REST API.

**Comment by qtjupsrkb** [comment]
Is support for the Samjin button like to be added in the future?

**Comment by manup** [comment]
>Is support for the Samjin button likely to be added in the future?

Yes, we have it here for testing, but there is no ETA yet.

**Comment by qtjupsrkb** [comment]
Thanks for the update @manup !

That's exciting to hear :-)

**Comment by keithcroshaw** [comment]
Hello, Thanks for all the hard work going on here. 
I have one of these buttons that I'm looking to integrate.
Has it made it out of the lab yet?

**Comment by elmgrenen** [comment]
^Wondering the same thing as keithcroshaw

**Comment by indrora** [comment]
Is there a way we can test this using, e.g., Home Assistant?

**Comment by keithcroshaw** [comment]
Was support released @indora?
I'll gladly test if it was.

**Comment by manup** [comment]
The SmartThings button isn't integrated yet, but will be very soon :)

**Comment by mysteryan** [comment]
Button press, double press and hold seems now seems to fire the appropriate buttonevent in the latest commit.  Temperature reports also seem to be working properly now.  Thanks.

**Comment by manup** [comment]
Cool, thanks for testing.

**Comment by elmgrenen** [comment]
How do I add this to Home Assistant? I use conbee2 with deconz plugin so I use phoscon app

**Comment by manup** [comment]
You'll need to wait for the next version 2.05.70 (or compile the plugin).
The button is then available in the same manner as other switch resources.

**Comment by ecfitzgerald** [comment]
I have 2.05.71 and I can add the button, but in Phoscon its in Switches, but if I try to add the switch to a group with the switch editor, the switch does not appear.  I see the temperature and battery in Hassio.  I suspect the not seeing the switch in the switch editor is the primary symptom, I can see my Ikea switch and use it in phoscon and hassio, but not this.

**Comment by keithcroshaw** [comment]
I wonder if it shows up as an event in Home Assistant? I wish that all buttons would show up as binary sensor entities.

**Comment by bisby** [comment]
It does indeed show up as an event in Home Assistant. single, double, and long presses are all different event types.

```json
{
    "event_type": "deconz_event",
    "data": {
        "id": "button",
        "unique_id": "1",
        "event": 1004
    },
    "origin": "LOCAL",
    "time_fired": "2019-12-04T03:30:23.164600+00:00",
    "context": {
        "id": "1",
        "parent_id": null,
        "user_id": null
    }
}
```

"event" was 1002 for single press, 1004 for double press, and 1001 for long press.

**Comment by mysteryan** [comment]
> I have 2.05.71 and I can add the button, but in Phoscon its in Switches, but if I try to add the switch to a group with the switch editor, the switch does not appear. I see the temperature and battery in Hassio. I suspect the not seeing the switch in the switch editor is the primary symptom, I can see my Ikea switch and use it in phoscon and hassio, but not this.

Treat it like a sensor and create a rule to toggle an existing group according to its buttonevent.

**Comment by ebaauw** [comment]
Does this device support Tamper detection and low battery in the IAS Zone Status?  The code was inconsistent that `state.tampered` and `state.lowbattery` were not exposed on pairing, but were on restore from the database.  I now don't expose them for both situations, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2672#issuecomment-612491012.

**Comment by mattiasflodin** [comment]
This is listed in the [support page](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices) but I see no indication in the issue whether it was actually verified as working. Is it supposed to work? Because I'm having no success pairing this in deconz 10.0.0.4  (FW version 261F0500).
