### ISSUE TITLE
deconz with a cc2531 stick

### ISSUE THREAD

**Issue by sedony23** [dresden-elektronik/deconz-rest-plugin#995]
Hi there, I already have a cc2531 stick flashed with the CC2531ZNP-Prod.hex firmware. Can I use this stick with den deconz software or do I have to get a ConBee stick? Or could I flash the cc2531 stick with the ConBee firmware?

Thanks for your help!

**Comment by khzd** [comment]
thank @manup , no support planned for cc2531 or  CC2530
any workaroud to use such devices ?
thanks

**Comment by sedony23** [comment]
Hmm, too bad, that it won't work with th ecc253a stick. Looks like, that I have to get a ConBee stick instead...
